### ISSUE TITLE
Allow `typedesc` assignments with let/var at "compile time".

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#10004]
Currently `typedesc` assignments are only allowed with `const` variables, but they should also be allowed with `let`/`var` so long as they are in a `static`/`const`/`when` context:
```
const C = 
  block:
    let t : typedesc[int] = int
    ...

when(
  block:
    let t : typedesc[int] = int
    true
):
  ...

static:
  let t : typedesc[int] = int
  ...

**Comment by mratsim** [comment]
SHouldn't we use `type t: type int = int` anyway?

**Comment by deech** [comment]
I had no idea that syntax existed.

**Comment by krux02** [comment]
yes use type definitions please.
