### ISSUE TITLE
travis stuck on build

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#10013]
This build has been stuck for quite a long time https://travis-ci.org/nim-lang/Nim/builds/468568083 (so other PRs have been stuck in the queue for a long time
(It should have timed out by now)
(That commit is no longer in the PR due to a force push)

cc @timotheecour

**Comment by genotrance** [comment]
I've killed the build.

**Comment by timotheecour** [comment]
I reported it here: https://travis-ci.community/t/travis-stuck-on-build-but-doesnt-die-long-past-the-timeout-deadline/1479
