### ISSUE TITLE
regression: normalizePath("foo/..") now incorrectly returns `""`, should be `"."` like before + in almost all other languages

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10017]
/cc @Araq 
my code broke due to a recent regression introduced here: ce9815bcf5a0ae5549be116604c2ad8ddacb17af
 
```nim
import os
block:
  var s = "foo/.."
  normalizePath(s)
  echo "{", s, "}" # WAS {.}; now: {}
```

## other languages:
conflating `.` with empty string is a bad idea; empty string (as a path) represents un-initialized path; this is different from `.` which represents `current dir`

Pretty much all other languages I use don't do that mistake:
* D: buildNormalizedPath("foo/..") prints `.`
* python: os.path.normpath('foo/..') prints `.`
* C++: boost::filesystem::path("foo/..").lexically_normal().string() => `.`
* node JS: path.normalize('foo/..') prints `.`
* go:  fmt.Println(filepath.Clean("foo/..")) prints `.`

## note
there was already a test case in place:
doAssert normalizedPath(".") == "."
but it got overwritten by ce9815bcf5a0ae5549be116604c2ad8ddacb17af
`doAssert normalizedPath(".") == ""`

[EDIT]
see also @krux02 's comment from https://github.com/nim-lang/Nim/issues/10017#issuecomment-447877313:
> you forgot the most important example, the shell. No matter if it is Linux or Window, everywhere the current directory is ".". "" is not a valid path on my shell (fish).

**Comment by timotheecour** [comment]
=> PR https://github.com/nim-lang/Nim/pull/10018

**Comment by andreaferretti** [comment]
Same for me: my tests for Rosencrantz are broken since now `"." / "LICENSE"` equals `"/LICENSE"` instead of `"./LICENSE"` (nothing major, just the tests are broken)

**Comment by timotheecour** [comment]
@andreaferretti I'm confused about your msg:
> "." / "LICENSE" equals "/LICENSE" instead of "./LICENSE"

that doesn't seem true, and seems unrelated to this issue; `"." / "LICENSE"` returns `"LICENSE"` ; please show a minimized test example if that's not the case

**Comment by andreaferretti** [comment]
You are right, it was a previous mistake on my part, where I was doing (incorrectly) `"." / "/LICENSE"`, which used to return (incorrectly) `"./LICENSE"`. When I saw this issue, I thought it was the same - I am instead going to fix this in Rosencrantz tests

**Comment by timotheecour** [comment]
wow, you're bringing up a good point, looks like `"." / "/LICENSE"` now returns `/LICENSE` but used to return `./LICENSE` ; which is related to https://github.com/nim-lang/Nim/issues/8268 except it's now completely buggy because it's inconsistent : just filed https://github.com/nim-lang/Nim/issues/10025

**Comment by timotheecour** [comment]
adding high priority because regressions like this can cause a lot of harm (eg wrong file being deleted etc)

**Comment by krux02** [comment]
@timotheecour you forgot the most important example, the shell. No matter if it is Linux or Window, everywhere the current directory is `"."`.  `""` is not a valid path on my shell (fish).

**Comment by timotheecour** [comment]
added your comment on top post. So could someone please merge my PR to fix it? https://github.com/nim-lang/Nim/pull/10018
