### ISSUE TITLE
[regression] [os]  joinPath("usr/", "/lib")="usr/lib" but  joinPath(".", "/lib")="/lib"

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10025]
/cc @Araq 

```nim
echo joinPath("usr/", "/lib")
echo joinPath(".", "/lib")
echo joinPath("./", "/lib")
```
now prints

usr/lib
/lib
/lib

which is definitely wrong (inconsistent, regardless of which side of https://github.com/nim-lang/Nim/issues/8268 you're on)

the bug was introduced here: 9cc4a57768156883acc4e8190c78a69ed2c3d526 /cc @Araq 

before which it was printing:
usr/lib
./lib
./lib

## note
I had argued here https://github.com/nim-lang/Nim/issues/8268 that `joinPath("foo", "/bar")` should've returned "/bar" as it's the sane thing to do (and as done in most languges), but not sure whether we want to introduce this breaking change now; In this PR (sent out a while ago...) https://github.com/nim-lang/Nim/pull/8351 I've introduced instead an extra param to avoid this breaking change:
```
doAssert joinPath("foo", "/bar", "/baz", "tail", absOverrides = true) == "/baz/tail"
```
maybe now's a good time to revive it

* adding high priority because regressions like this can cause a lot of harm (eg wrong file being deleted etc)

**Comment by arnetheduck** [comment]
hahaha, think `rm -rf` and we have the perfect storm brewing..

**Comment by Araq** [comment]
If every term gets its own tag can we stop using tags and rely on github's text search?

**Comment by cabhishek** [comment]
@timotheecour Another possible regression? 
```
import os
const url = "http://foo.com/api/v1"
echo joinPath(url, "bar") # outputs => http:/foo.com/api/v1/bar
```
Looks like `joinPath` eats up `/` in `http://`. This doesn't hapeen in `0.19.0` and `0.18.0`.

**Comment by timotheecour** [comment]
@cabhishek  could you please file a separate issue so it can be discussed separately? it's a bit controversial whether joinPath should handle url's.

**Comment by timotheecour** [comment]
> If every term gets its own tag can we stop using tags and rely on github's text search?

it's a gray area; tags have a number of advantages over plain text for things that are common enough (`enough` is what's subject to debate).

* For example: in github you can very quickly edit tags on a number of issues, eg here you can select all 19 issues with os.path and re-tag them;

![image](https://user-images.githubusercontent.com/2194784/50118539-cb925380-0204-11e9-9ab9-eb0c76245124.png)

or you can bookmark issues tagged as `os.path` to follow them etc.

* plain text search is a good complement to tags but doesn't replace tags (eg you can't rely on ppl to name the same concept the same way)

* detailed tags (as opposed to just a few like `feature`, `bug` etc) are very popular and in things like stackoverflow and used effectively.

**Comment by timotheecour** [comment]
right, joinPath shouldn't handle URL's, if it did before, that's by chance.

**Comment by timotheecour** [comment]
=> my PR https://github.com/nim-lang/Nim/pull/10018 also fixes this
