### ISSUE TITLE
Building koch from nim devel fails when config.nims importing `os` present

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#10030]
I have been able to reproduce this issue on the latest Nim devel as of now ( https://github.com/nim-lang/Nim/commit/0409f2348e2ac69a717e4ec7628a99c49fd42f0d ).

## Steps to reproduce the issue

1. Build `koch` using the csources-built `nim` binary as you would normally do when building Nim from devel.
2. Create a `~/.config/nim/config.nims` with just `import os` line.
3. In your Nim build dir, where you build `koch`, do `./koch boot -d:release`.

You will get something like:

```
km²~/downloads/:git/Nim> ./koch boot -d:release                 12/17 2:46pm
iteration: 1
compiler/nim0 c -d:release --nimcache:nimcache/r_linux_amd64 compiler/nim.nim
Hint: used config file '/home/kmodi/downloads/git/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/compiler/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
../lib/system.nim(376, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
../lib/pure/os.nim(705, 14) Error: undeclared identifier: 'Stat'
FAILURE
```

---

An ugly workaround I use to allow Nim devel to build successfully on Travis is to temporarily remove the config.nims from Nim's search path: https://github.com/kaushalmodi/hello_musl/commit/ed97b4b248fa88097ef6a655219b5ea9722cf738

/cc @nc-x, @Araq

**Comment by kaushalmodi** [comment]
Note that even though the `--skipUserCfg` option is availabe for the csources-build `nim` binary, it doesn't work.. 

See below that it still is fetching `/home/kmodi/.config/nim/config.nims`:

```
km²~/downloads/:git/Nim> ./bin/nim c koch --skipUserCfg         12/17 1:44pm
Hint: used config file '/home/kmodi/downloads/git/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/koch.nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
lib/system.nim(376, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
lib/pure/os.nim(705, 14) Error: undeclared identifier: 'Stat'
```

**Comment by timotheecour** [comment]
@kaushalmodi remember to use permalinks instead of links to master, which are mutable, eg: https://github.com/kaushalmodi/nim_config/blob/e38fb2d1c5d70b1ee2fe47683b706d1059f352a2/config.nims#L1

**Comment by timotheecour** [comment]
> Note that even though the --skipUserCfg option is available for the csources-build nim binary, it doesn't work..
See below that it still is fetching /home/kmodi/.config/nim/config.nims:

seems like a separate bug... maybe file another bug for that?

**Comment by kaushalmodi** [comment]
> remember to use permalinks instead of links to master

Thanks for pointing that out.

*I always do that! Just forgot this time.*

**Comment by kaushalmodi** [comment]
> seems like a separate bug... maybe file another bug for that?

Done! https://github.com/nim-lang/Nim/issues/10031

**Comment by kaushalmodi** [comment]
Even if I skip my user config in the `koch` building step by doing `./bin/nim --skipUserCfg c koch`, I get the same failure when `koch` is used to build the final `nim` binary:

```
km²~/downloads/:git/Nim> ./koch boot -d:release                 12/17 2:29pm
iteration: 1
compiler/nim0 c -d:release --nimcache:nimcache/r_linux_amd64 compiler/nim.nim
Hint: used config file '/home/kmodi/downloads/git/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/compiler/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
../lib/system.nim(376, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
../lib/pure/os.nim(705, 14) Error: undeclared identifier: 'Stat'
FAILURE
```

**Comment by timotheecour** [comment]
confirmed the bug

**Comment by kaushalmodi** [comment]
@timotheecour @Araq Can you please re-open this issue? This is still not fixed.

See https://travis-ci.org/kaushalmodi/hello_musl/builds/477988027#L672:

```
Hint: used config file '/home/travis/build/kaushalmodi/hello_musl/nim/ab425d793af1a5c0b221bfbeab382b4781479c63/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: used config file '/home/travis/build/kaushalmodi/hello_musl/nim/ab425d793af1a5c0b221bfbeab382b4781479c63/config/config.nims' [Conf]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
lib/pure/os.nim(718, 14) Error: undeclared identifier: 'Stat'
/home/travis/.travis/job_stages: line 115: ./koch: No such file or directory
```


I can recreate the failure locally too. *You need to delete the earlier `koch` generated `nim` binary to reproduce this error locally.*

**Comment by timotheecour** [comment]
@kaushalmodi that's odd, my patch #10244 worked for me, and still does; 

can you please run these commands and let me know what you're getting?

```
cat ~/.config/nim/config.nims
import os

git clone https://github.com/nim-lang/Nim
cd Nim

git rev-parse HEAD
647066e378bdbc85646dd88ea90eb15eddbbbc50

sh build_all.sh
./bin/nim --version
Nim Compiler Version 0.19.9 [MacOSX: amd64]
Compiled at 2019-01-12
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 647066e378bdbc85646dd88ea90eb15eddbbbc50
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment]
@timotheecour 

Yes, I confirm that your snippet above works fine on my machine (RHEL 6.8). But it still fails on Travis. Probably there are some nuances about the 64-bit Linux OS on Travis that's causing the problem?

See the https://travis-ci.org/kaushalmodi/hello_musl/builds/478090554#L669 log of a Travis run that I just reran .. it is still failing.

Relevant bits from that log:

```text
int: used config file '/home/travis/build/kaushalmodi/hello_musl/nim/795e5e11ef53260a0a15e25eba36dddbd83900c1/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: used config file '/home/travis/build/kaushalmodi/hello_musl/nim/795e5e11ef53260a0a15e25eba36dddbd83900c1/config/config.nims' [Conf]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
lib/pure/os.nim(718, 14) Error: undeclared identifier: 'Stat'
/home/travis/.travis/job_stages: line 115: ./koch: No such file or directory
```

.. and from that same part in the Nim build locally, I see:

```text
bin/nim c --skipUserCfg koch
Hint: used config file '/tmp/kmodi/nim_i10030/Nim/config/nim.cfg' [Conf]
Hint: used config file '/tmp/kmodi/nim_i10030/Nim/koch.nim.cfg' [Conf]
Hint: used config file '/tmp/kmodi/nim_i10030/Nim/config/config.nims' [Conf]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
Hint: system [Processing]
lib/system.nim(392, 50) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
Hint: koch [Processing]
Hint: os [Processing]
```

So somehow, `os.nim` fails to compile on Travis with `import os` in `config.nims`. I have verified this with the latest Nim devel commit as of now: 795e5e11ef53260a0a15e25eba36dddbd83900c1.

**Comment by kaushalmodi** [comment]
Here's a minimum reproducible example: https://github.com/kaushalmodi/hello_musl/tree/nim-issue-10030

and its failure on Travis: https://travis-ci.org/kaushalmodi/hello_musl/builds/480134192.

Discussion on gitter: https://gitter.im/nim-lang/Nim?at=5c3e5ed31cb70a372ae4de0b

(I wanted to link to IRC logs but https://irclogs.nim-lang.org/16-01-2019.html gave a 404 error at the time of typing this.)

**Comment by juancarlospaco** [comment]
This still reproduces as of today as of exactly described above:

```nim
$ choosenim update self
   Updating choosenim
      Info: Already up to date at version 0.4.0

$ choosenim update devel
   Updating devel
Downloading Nim devel from GitHub
[##################################################] 100.0% 0kb/s
 Extracting devel.tar.gz
   Building Nim #devel
   Warning: Building from latest C sources. They may not be compatible with the Nim version you have chosen to install.
Downloading Nim C sources from GitHub
[##################################################] 100.0% 0kb/s
 Extracting master.tar.gz
   Building C sources
   Building koch
 Exception: Execution failed with exit code 1
        ... Command: ./bin/nim c koch
        ... Output: Hint: used config file '/home/juan/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
        ... Hint: used config file 'koch.nim.cfg' [Conf]
        ... Hint: used config file '/home/juan/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
        ... lib/system.nim(469, 48) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
        ... lib/system.nim(469, 48) Warning: unknown magic 'Destroy' might crash the compiler [UnknownMagic]
        ... lib/pure/os.nim(964, 14) Error: undeclared identifier: 'Stat'
   Cleaning failed build
     Error: Build failed


$ rm --verbose $XDG_CONFIG_HOME/nim/config.nims
removed '/home/juan/.config/nim/config.nims'

$ choosenim update devel
   Updating devel
Downloading Nim devel from GitHub
[##################################################] 100.0% 0kb/s
 Extracting devel.tar.gz
   Building Nim #devel
   Warning: Building from latest C sources. They may not be compatible with the Nim version you have chosen to install.
Downloading Nim C sources from GitHub
[##################################################] 100.0% 0kb/s
 Extracting master.tar.gz
   Building C sources
   Building koch
   Building Nim
   Building tools (nimble, nimgrep, nimpretty, nimsuggest)
    Updated to #devel
      Info: Version #devel already selected

$ nim --version
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-29
Copyright (c) 2006-2019 by Andreas Rumpf
active boot switches: -d:release

```

GitHub wont let me Re-Open Issue whatsoever.

**Comment by kaushalmodi** [comment]
It builds fine for me. May be choosenim needs to get fixed to use the appropriate switches when building koch.

**Comment by juancarlospaco** [comment]
Ok, maybe I need to reinstall the `choosenim` :+1:

**Comment by kaushalmodi** [comment]
Or I could be misremembering.. the fix was inside the `build.sh`. So as long as you are using that, it should be good: https://github.com/nim-lang/Nim/commit/0bb76dde547ff9f3e80f7421d4f2c556d7aefc4d
