### ISSUE TITLE
Unexpected behaviour on method dispatch

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#10038]
As reported on the Nim forum here: https://forum.nim-lang.org/t/4486#27999, I was asked to file this as an issue here:

```
type
  SNodeAny = ref object of RootObj
  SNode[T] = ref object of SNodeAny
  DNode[T] = ref object

method getStr(s: SNode[float]): string {.base.} = "blahblah"

method newDNode(s: SNodeAny) {.base.} =
  echo "newDNode base"

method newDNode[T](s: SNode[T]) =
  echo "newDNode generic"

let s = SNodeAny(SNode[float]())
newDnode(s)

```

What I expect to happen: variable ``s`` is a ``SNode[float]`` disguised as a ``SNodeAny``. Calling ``newDnode(s)`` should dispatch the ``newDnode[T](s: SNode[T])`` and the string ``newDNode generic`` should be printed.

Instead what happens is that the base method ``newDnode(s: SNodeAny)`` gets called, printing the string ``newDnode base``

Now the strangest part: when the ``getStr()`` method is removed from the code, the behaviour changes to the expected behaviour, and all is well. Alternatively, removing the ``SNodeAny()`` cast from the second last line also restores the expected behaviour.

How does the existence of the ``getStr()`` method affect the behaviour of the ``newDNode()`` dispatch?

**Comment by zevv** [comment]
For the record, @Araq's answer:

> This works
> 
> ```
> type
>   SNodeAny = ref object of RootObj
>   SNode[T] = ref object of SNodeAny
>   DNode[T] = ref object
> 
> method newDNode(s: SNodeAny) {.base.} =
>   echo "newDNode base"
> 
> method newDNode[T](s: SNode[T]) =
>   echo "newDNode generic"
> 
> method getStr(s: SNode[float]): string {.base.} = "blahblah"
> 
> let s = SNodeAny(SNode[float]())
> newDnode(s)
> ```
> 
> why? The instantiation SNode[float] is cached and by that time there are no methods attached to SNode yet. Then the cache is consulted and the instantation of method newDNode[T](s: SNode[T]) is skipped. Multi methods and generics are broken beyond repair IMO.

Not sure how to process from here though, this feels a bit like a minefield - I guess I will play safe and try to redesign so that I do need multimethods.

**Comment by mratsim** [comment]
This explains why I had this bug in Arraymancer https://github.com/mratsim/Arraymancer/issues/327 and had to remove all methods from my code base 3 days ago.
