### ISSUE TITLE
Combining object variants and inheritance leads to SIGSEGV during compilation

### ISSUE THREAD

**Issue by liwt31** [nim-lang/Nim#10033]
Object variants and inheritance are both good ideas and work quite well, but putting them together seems to lead to SIGSEGV during compilation. In my tests, if A is an object variant and B is inherited from A, then writing certain attributes of B (probably the discriminator) will result in SIGSEGV during compilation.

### Example

```nim
type
  Token = enum
    Int,
    Float 

  Base = ref object of RootObj
    case token: Token
    of Int:
      bInt: int
    of Float:
      bFloat: float

  Child = ref object of Base

let c = new Child
c.token = Int
```

### Current Output

```
$ nim c ghIssue.nim
Hint: used config file '/home/wtli/.choosenim/toolchains/nim-0.19.0/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: ghIssue [Processing]
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
What I'm trying to do in the code example might be illegal (although I couldn't find any reference in the manual), but I don't think it should result in a segmentation fault.

### Possible Solution
No idea. Thank you for your time for this!

### Additional Information
Nim Compiler Version 0.19.0 [Linux: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release

**Comment by Araq** [comment]
Strange bug, the compiler itself mixes both features freely.

**Comment by nc-x** [comment]
It is because object variants require simultaneous initialization of kind and value.
Changing last two lines to this makes it work -
```
var c = new Child
c = Child(token: Int, bInt: 1)
```
or even just
```
let c = Child(token: Int, bInt: 1)
```
(According to [the manual](https://nim-lang.org/docs/manual.html#types-object-construction), `For a ref object type system.new is invoked implicitly.`)

**Comment by deech** [comment]
This seems to be some issue with `ref`'s, this works:
```
type
  Token = enum
    Int,
    Float

  Base = object of RootObj
    case token: Token
    of Int:
      bInt: int
    of Float:
      bFloat: float

  Child = object of Base

let c = new Child
c.token = Int
```
