### ISSUE TITLE
CI should call `./koch tools` ; right now `nimfind` isn't even being compiled

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10039]
~~it'd be more DRY for CI to call `./koch tools` instead of duplicating its logic, nimfind was added to ./koch tools but is not being tested, so introducing compile errors won't even be tested for (i just tried)~~
EDIT:

CI should call `./koch tools` ; right now `nimfind` isn't even being compiled

### Example
N/A

### Current Output
N/A

### Expected Output
N/A

### Possible Solution
it'd be more DRY for CI to call `./koch tools` instead of duplicating its logic inside travis/appveyor, nimfind was added to ./koch tools but is not being tested, so introducing compile errors won't even be tested for (i just tried); Hence I suggest: 
replace 
```
- ./koch nimsuggest
```
by
```
- ./koch tools
```
so it'll at least build all tools (even if not testing all of them)
ditto with appveyor

### Additional Information
N/A

**Comment by krux02** [comment]
We have issue templates for a reason. Please use them.

**Comment by timotheecour** [comment]
just did, not sure what it buys in terms of clarity in this issue
