### ISSUE TITLE
stdlib modules should run via megatest (or megatest_stdlib), with special isMainModule handling

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10045]
This is a followup from https://github.com/nim-lang/Nim/issues/9581

testament uses `testStdlib` to compile and run stdlib modules.
It relies on this logic:
```
if "when isMainModule" notin contents:
       testObj.spec.action = actionCompile
```
This is ok-ish but can have false positives (if appears in a comment), or false negatives, eg with `when defined(osx) and isMainModule`.

Instead of fixing this logic, a much better way is to extend the `megatest` idea from https://github.com/nim-lang/Nim/issues/9581 to stdlib modules.
This can be done as follows, without having to patch any stdlib module:
* add each stdlib file to megatest (minus a blacklist of non-joinable tests)
* patch compiler so `isMainModule` is equal to `true` when `-d:isMainModuleIsAlwaysTrue` is provided

That'll give the speedup benefit from https://github.com/nim-lang/Nim/issues/9581, and make that logic less fragile

## note
on my machine, 
```
nim c -r testament/tester pcat lib # 102 seconds
nim c -r testament/tester all # 390 seconds
```
so we can save roughly 25% with this (minus time to compile/run the megatest)

But this saving will become more significant as we address remaining issues, eg I have ideas for joining certain failing tests using the new `--errorMax:N` flag (will discuss in other issue)

**Comment by Araq** [comment]
I had the same plan so go ahead already. :-)

**Comment by Araq** [comment]
I changed my mind, megatest is bad enough already, I don't want even more of the same.
