### ISSUE TITLE
import "path with space/bar.nim" gives error msg with wrong file name

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10042]
# Error: cannot open file: foobar/fun.nim
```nim
import "foo bar/fun.nim"
# ditto with abs path:
# import "/tmp/d02/foo bar/fun.nim"
```

I bumped into it while working on testament which contained one such test file with a space in dir

Note that nim c "path with space/main.nim" works

**Comment by Araq** [comment]
Look for 

```nim

    # hacky way to implement 'x / y /../ z':
    result = renderTree(n, {renderNoComments}).replace(" ")
```

in compiler/modulepaths.nim
