### ISSUE TITLE
nimpretty infinite newlines between comment and import statement

### ISSUE THREAD

**Issue by LorenzHenk** [nim-lang/Nim#10059]
When adding a comment above imports, a newline is created every time nimpretty is run.

### Example
```nim
# import algorithm
import strutils
```

### Current Output
After first save:
```
# import algorithm

import strutils
```
After second save:
```
# import algorithm


import strutils
```
After third save:
```
# import algorithm



import strutils
```
...

### Expected Output
```
# import algorithm
import strutils
```

### Additional Information
using vscode + nim extension

**Comment by tim-st** [comment]
I think it's related to https://github.com/nim-lang/Nim/issues/9144#issuecomment-430530626
