### ISSUE TITLE
cmpIgnoreStyle reimplemented 5 times

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10064]
/cc @Araq 
- [ ] I noticed `cmpIgnoreStyle` is reimplemented 5 times; this seems a clear DRY violation that could easily be fixed with a include file (or perhaps even import file):
```
[0  ] compiler/idents.nim:35:6                                      |proc cmpIgnoreStyle*(a, b: cstring, blen: int): int =
[1  ] lib/core/macros.nim:1307:8                                    |  proc cmpIgnoreStyle(a, b: cstring): int {.noSideEffect.} =
[2  ] lib/core/typeinfo.nim:303:6                                   |proc cmpIgnoreStyle(a, b: cstring): int {.noSideEffect.} =
[3  ] lib/pure/cstrutils.nim:46:6                                   |proc cmpIgnoreStyle*(a, b: cstring): int {.noSideEffect,
[4  ] lib/pure/strutils.nim:364:6                                   |proc cmpIgnoreStyle*(a, b: string): int {.noSideEffect,
[5  ] lib/system/nimscript.nim:108:6                                |proc cmpIgnoreStyle(a, b: string): int = builtin
```
=> see https://github.com/nim-lang/Nim/search?q=%22proc+cmpIgnoreStyle%22&unscoped_q=%22proc+cmpIgnoreStyle%22

- [x] we'd have to profile it to double check, but seems to me `cmpIgnoreStyle` could be a potential bottleneck (in sense of > 1% of compile time, but could be more) since:
* it's used in 73 locations
* it's typically used inside a linear scan over ids (complexity: O(num_ids) * big_constant)
* it's also being used to find whether an identifier is in scope (ie, a hotspot in compiler, where scope could contain tons of symbols)

EDIT: my analysis in https://github.com/nim-lang/Nim/issues/10132 suggests this isn't a performance bottleneck

## proposal
introduce `normalizeStyle` (defined below), and use lookup tables of precomputed `normalizeStyle` values in all performance-critical places where cmpIgnoreStyle is currently used.

```nim
proc normalizeStyle(a: string): string =
  var first = true
  for ai in a:
    if first:
      case ai
      of  'a'..'z','A'..'Z':
        result.add ai
        first = false
      else:
        doAssert false, "invalid 1st char:" & $ai
    else:
      case ai
      of '_': continue
      of 'a'..'z','0'..'9': result.add ai
      of 'A'..'Z':
        let ai2=chr(ord(ai) + (ord('a') - ord('A')))
        result.add ai2
      else:
        doAssert false, "invalid char:" & $ai

proc main()=
  doAssert normalizeStyle("Foo_BarRGB") == "Foobarrgb"
  doAssert normalizeStyle("foo__BarRGB") == "foobarrgb"

main()
```

Note, we can further optimize to avoid allocations in `normalizeStyle(needle)` when looking up needle against precomputed normalizeStyle(haystack)

## benefit
we go from O(n) to O(1); n could be large

**Comment by timotheecour** [comment]
added a link in above msg

**Comment by krux02** [comment]
I don't agree on your proposal. Creating a normalized string and then compare that isn't faster. You always need to allocate a new normalized version of the string just to make a lookup in that table. I see a very different problem:

`cmpIgnoreStyle` isn't the same everywhere. For example `strutils.cmpIgnoreStyle` makes you think it does identifier comparison properly, but it doesn't, it ignores the case of the first character. For reasons of backwards compatibility, `strutils.cmpIgnoreStyle` is been left untouched but it should never ever actually be used for ignore style comparison. It is just a false friend that will caause bugs later. That is why everywher there is now a local `cmpIgnoreStyle` implementation, because the shared implementation is wrong. I wanted to fix `strutils.cmpIgnoreStyle` but that PR was rejected. Leaving us with issues like this: https://github.com/nim-lang/Nim/issues/7686

And btw, you did the mistake of importing `strutils.cmpIgnoreStyle` as well here: https://github.com/nim-lang/Nim/pull/10063/files#diff-dc05830f41a222a0b826e05a04ebd1e0R14
Don't do it.

**Comment by timotheecour** [comment]
just replying on this here:
> And btw, you did the mistake of importing strutils.cmpIgnoreStyle as well here

as discussed on IRC, I just propagated what was done in code before this PR: wordrecg.findStr uses strutils.cmpIgnoreStyle, so the PR doesn't change behavior; and IIRC @araq said case insensitivity of 1st char for stuff like `--hint:success:on vs --hint:Success:on` was intentional (or at least historical to not break cmdlines when nim adopted case sensitivity for 1st char)

**Comment by timotheecour** [comment]
> I don't agree on your proposal. Creating a normalized string and then compare that isn't faster. You always need to allocate a new normalized version of the string just to make a lookup in that table

except you amortize that cost over all queries.

So we go from O(n*m) to O(n+m):


```
block existingCode: # cost = O(needles.len * haystack.len * averageIdentifierSize)
  proc findStyleInsensitiveMatch(needle: string, haystack: seq[string]): string=
    for a in haystack:
      if cmpIgnoreStyle(a, needle)==0: return a
    return ""
  for needle in needles:
    echo findStyleInsensitiveMatch(needle, haystack)

block proposal: # cost = O((needles.len + haystack.len) * averageIdentifierSize)
  var haystack2: HashSet[string]
  for a in haystack: haystack.add(a.normalizeStyle)
  for needle in needles:
    echo haystack2.getOrDefault(neede.normalizeStyle) # or maybe even use `hashIgnoreStyle`
```

**Comment by krux02** [comment]
I know about the theory. By my intuition and experience tells me that this change will make it noticeable slower in practice. So unless you can show that this is actually a performance improvement (time measurement) with practically relevant test cases, I am against this changes.

**Comment by mratsim** [comment]
If strutils.cmpIgnoreStyle doesn't follow what is done in the compiler, it should be changed even if breaking with a static bool parameter to get the old behaviour.

**Comment by krux02** [comment]
@mratsim I totally agree with that.

**Comment by timotheecour** [comment]
regardless of replacing some usages of `cmpIgnoreStyle` with `normalizeStyle`, we should definitely refactor the 5 different `cmpIgnoreStyle` into a single one, which could take extra `static bool` params as needed to account for differences in behavior
* B1: case of 1st char
* B2: taking `blen` as input vs using `\0' null string terminator (some overloads use blen, some dont)
```nim
proc cmpIgnoreStyle*(a, b: cstring, blen: int, caseFirstCharMatters: static bool = true, useNullTermination: static bool = false): int = ...
```

**Comment by timotheecour** [comment]
my analysis in https://github.com/nim-lang/Nim/issues/10132 suggests `cmpIgnoreStyle` isn't a performance bottleneck. So it's only a "code health" issue.

**Comment by krux02** [comment]
I am closing this issue now, because the discussions here really don't provide any useful information that we should keep for the future, but it is noted that cmpIgnoreStyle is actually implemented many times and that this isn't clean.
