### ISSUE TITLE
Object construction with 'let' allows reassignment of fields.

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#10076]
In the first case starting `let x ...` I initialize all the fields of `Object` and as expected `x.a = 3` is disallowed by the compiler.

In the second I construct `Object` with `new` expecting that `a` will be default initialized to 0 but I am able to reassign it. 

Is this a bug with `let` semantics?

```
type
  Object = object of RootObj
    a: int

let x = Object(a:2)
x.a = 3  # <--- compiler error here as expected

let y = new Object
y.a = 2  # <--- possible bug here
```

**Comment by slangmgh** [comment]
new Object create object ref, and it can be modified, it is not bug.

**Comment by deech** [comment]
Makes sense, thanks!
