### ISSUE TITLE
4 bugs with typedesc

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10078]
### Examples
```nim
template `$`(t: untyped): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)
const a2 = $(int)
```
output: `(4, 13) Error: identifier expected, but found '(int)'` (OK)

```nim
template name2*(t: untyped): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)
const a1 = name2(int)
```
This compiles, but should not compile as it injects `int` as the argument symbol of the `name` proc.

```nim
template name2*(t: untyped): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)

const a1 = name2(int) # comment this will remove the error

template `$`(t: untyped): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)
const a2 = $int
```
output: ``(8, 3) Error: implementation of 'name' expected``. Not really a bug as defining magic procs in user code is undefined behavior.
```nim
template foo(t: typedesc): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)
const a2 = foo(int)
```
output: ``(4, 16) Error: cannot use symbol of kind 'type' as a 'param'`` (OK)
```nim
proc foo(t: typedesc): string =
  proc name(t: typedesc): string {.magic: "TypeTrait".}
  name(t)
const a2 = foo(int)
```
compiles, but should not.

```nim
proc name(t: typedesc): string {.magic: "TypeTrait".}
proc name2(t: typedesc): string = name(t)

proc fun[T: typedesc](t: T) =
  const a1 = name(t) # works
  const a2 = name2(t) # gives the bug
fun(int)
```
output: ``(6, 20) Error: cannot evaluate at compile time: t``
Using the generic parameter as suggested it https://github.com/nim-lang/Nim/pull/11959 would solve it.
```nim
proc name(t: typedesc): string {.magic: "TypeTrait".}
proc name2(t: typedesc): string = name(t)

proc fun[T](t: typedesc[T]) =
  const a1 = name(T) # works
  const a2 = name2(T) # works now too
fun(int)
```

**Comment by krux02** [comment]
Well the most important problem that I see is, that the compiler doesn't throw an error when the magic pragma is used outside of the standard library. When that one has been fixed these errors should be rewritten without the usage of ``magic``.

**Comment by Araq** [comment]
Using ``magic`` outside of the stdlib is fine IMO, just don't expect any official support for it or bugfixes.

**Comment by krux02** [comment]
I just went though the issues list again. These are all non-bugs except from the last one, but that issue has been reported in other issues as well.
