### ISSUE TITLE
Infinite loop with uint32.high

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/Nim#1008]
In the following code, `i` wraps around and ends up in an infinite loop (caution!)

``` nimrod
for i in uint32.high - 100 .. uint32.high:
  echo i
```

The following works ok:

``` nimrod
for i in uint32.high - 100 .. uint32.high-1:
  echo i
```

**Comment by ReneSac** [comment]
#148 was "fixed" but this continues to give an infinite loop.

**Comment by ReneSac** [comment]
Also, not sure if I should open a different issue, because it is related:

``` nim
for i in int.high -1 .. int.high:
  echo i
```
Gives an overflow error now, where no overflow *should* be happening.

**Comment by Araq** [comment]
This is documented behaviour and the unsigned bug is just the buggy 'is' operator in action.

**Comment by ReneSac** [comment]
So will this loop with uint32 will work correctly even in 32bit versions of the compiler? And what about a uint64 loop?

And I don't think people will know or remember that gotcha with 32 bit integers. Only when it unexpectedly blows in their face. The inclusive interval syntax creates an expectation that you should be able do do it, and let's you input that number. Should all functions that iterate over an unknown range of integers put an extra "if" to check if the upper bound is not int.max? Or an try/except? This should be done behind the scenes by the compiler, or limited by the syntax, to give a safe language for everyone.

**Comment by TiberiumN** [comment]
It seems to be fixed for me.
Tested with MinGW and Visual Studio Compiler, also on playground - https://gist.github.com/zacharycarter/357681a9e66241eb7b30877f34dcd65e

**Comment by dom96** [comment]
Still gives an infinite loop for me.

**Comment by Araq** [comment]
Unsigned arithmetic is modulo arithmetic. Fixing this would create too much overhead for these very important ``for`` loops that must run as fast as possible.
