### ISSUE TITLE
building from source on windows: instructions lack necessary details and lead to errors

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10088]
I'm not a windows developper and only use it when I have to; but would be nice to have a simple setup on windows for those who want to build nim from source (as opposed to from binary distribution) and don't want to sort through lots of outdated forum posts on the topic or have to guess the correct choice to get a setup up and running.

I'm following this guide https://github.com/nim-lang/nim#compiling on a brand new machine (windows 10);

- [ ] Instructions don't work depending on context (eg terminal: command prompt, powershell, git bash); instructions should specify at least 1 option that works (bonus point: allow instructions for command prompt AND git bash); eg git bash can't understand build64.bat; it may be obvious to some but might as well specify to use such or such terminal.

- [ ] https://nim-lang.org/install_windows.html doesn't actually specify how to add `gcc` in your PATH

- [ ] when following instructions it says:
> # requires `gcc` in your PATH, see also https://nim-lang.org/install_windows.html

I've installed git via https://git-scm.com/download/win (and selecting install unix tools; btw if that's not compatible or requires a workaround, it should be noted in nim docs for building from source on windows). 
```
The following *incompatible* MingW installations exist

C:\Program Files\Git\mingw64\bin
C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\dist\mingw64\bin
*incompatible* means...
Do you want to download MingW from Nim's website? (y/n)
```
if i say `n`, `gcc` still won't be in PATH
if i say `y`, it gives a dialog "Confirm File Replace"  (destination folder already contains processed file, to be replaced with mingw64\opt\lib\terminfo\31\1178)

**Comment by Araq** [comment]
``finish.exe`` can add stuff to your PATH... The instruction on the website are correct, follow them. I don't know why we would need extra remarks about all the "Unix simulation nonsense" on Windows. It's like requesting we should assume you run Nim under Wine on Linux, not our problem.

**Comment by Araq** [comment]
> I'm following this guide https://github.com/nim-lang/nim#compiling on a brand new machine (windows 10);
>  https://nim-lang.org/install_windows.html doesn't actually specify how to add gcc in your PATH

Maybe don't follow two different sets of instructions at the same time. You unzip and run finish.exe, that's it. "Installation from source/github" are for the people who ... I dunno ... prefer to build from source.

**Comment by genotrance** [comment]
I primarily use Windows and my preferred workflow as a Nim dev. is to use `choosenim`. I have my Nim fork checked out using `git` and use `choosenim c:\path\to\checkout` to use my devel installation. I use `git` and `koch` to update and build as needed.

This way, I can also use `choosenim` to install and revert to release versions like v0.19.0 when I run into issues or for test purposes. I have installed and added MinGW myself so don't rely on Nim tools to do that for me. But even there, I think choosenim can help with that.

I believe the `finish.exe` method is appropriate for Nim users and not developers since they simply download and use the build as is.

Regardless, for your issue, from the [code](https://github.com/nim-lang/Nim/blob/devel/tools/finish.nim#L270), it seems `finish` offers to add `gcc` to your path if it is already installed (and is a matching arch). If `gcc` is installed by `finish` then it isn't added to your path, instead your nim.cfg gets [updated](https://github.com/nim-lang/Nim/blob/devel/tools/finish.nim#L265). It will help to check what's in [nim.cfg](https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L143) since you opted for `finish` to install for you.

One last thing, note that if finish does update your path, it is only reflected in a new cmd session and not in any existing sessions.

**Comment by timotheecour** [comment]
thanks @genotrance, it helped me figure out what's going on;

I think I found what the problem is; IMO installation instructions for windows should be improved 

* even if gcc and nim is in your PATH (so that `gcc -v` and `nim --version` work), it's not enough, I get:
```
cd C:\Users\timothee\git_clone\Nim
set PATH=%PATH%;"C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin";"C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin"
nim --version # works
gcc -v # works
nim c koch.nim # fails:

CC: stdlib_system
Error: invocation of external compiler program failed. The system cannot find the file specified.
Additional info: "Requested command not found: \'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\\Users\\timothee\\git_clone\\Nim\\lib -IC:\\Users\\timothee\\git_clone\\Nim -o C:\\Users\\timothee\\nimcache\\koch_d\\stdlib_system.c.o C:\\Users\\timothee\\nimcache\\koch_d\\stdlib_system.c\'. OS error:" 2
```

* finish.exe is misleading:
```
running C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\finish 
bin\nim.exe is already in your PATH [Skipping]
C:\Users\timothee\.nimble\bin is already in your PATH [Skipping]
MingW installation found at C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\dist\mingw64\bin
Do you want to patch Nim's config to use this?
(Not required since it's in your PATH!) (y/n) n
```
then same error as above

* if I click `y`,it'll change `git_clone\Nim\config\nim.cfg`, making git status not clean; and would still not work since that config wouldn't be read by C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin\nim

* so I need to run finish.exe from inside C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\ dir; that'll work, after that I get a functional nim binary (but only for C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin\nim : after building a new one under git_clone\Nim, I'd also need to patch up the corresponding config\nim.cfg).

## proposal
a much better approach IMO is to create/update this file:
%APPDATA%\nim\nim.cfg (on my laptop, it's C:\Users\timothee\AppData\Roaming\nim\nim.cfg)
gcc.path = r"C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\dist\mingw64\bin" # for example

that'll make any nim binary work, regardless where they are

## note:
* can't build from source either:
```
cd csources
build.bat # same with build64.bat
Forcing gcc arch
Building with 64 bit gcc
gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code\1_2\compiler_nim.c -o c_code\1_2\compiler_nim.o
gcc: error: CreateProcess: No such file or directory
FAILURE
```

* above commands are on command prompt; turns out powershell has different syntax, eg for setting PATH; git bash also has different syntax

**Comment by genotrance** [comment]
This makes no sense - how is `gcc -v` working and not these commands? Is it really in your path?

The fact that even the build64.bat which simply calls gcc doesn't work means there's something wrong with your gcc setup, not Nim.

What is the output for `echo %PATH%`?

**Comment by Araq** [comment]
> even if gcc and nim is in your PATH (so that gcc -v and nim --version work), it's not enough, I get:

Not true.

Solution: Don't use git's terminal.

**Comment by timotheecour** [comment]
@genotrance 
> This makes no sense - how is gcc -v working and not these commands? 

it could be because perhaps nim invokes `gcc` by using the value of gcc.path found in nim.cfg, but not using `poUsePath` (random hypothesis that would explain what I'm seeing)

> Is it really in your path?

it is in my PATH, since `gcc -v` works.

> What is the output for echo %PATH%?

```
echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\timothee\AppData\Local\Microsoft\WindowsApps;;"C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin";"C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin"
```

> Not true.

why would I make this up? it could be that it works for you (and, no doubt, other people) but on some setup it doesn't work. My setup doesn't look anything unusual though: I'm testing this on a brand new windows machine, where I installed git through usual way as described above, and where I opted for  the option "install unix tools", in case that's relevant.

> Solution: Don't use git's terminal.

I'm not, as described here https://github.com/nim-lang/Nim/issues/10088#issuecomment-449787627 I'm using windows command prompt

**Comment by timotheecour** [comment]
I found the bug, it's a Nim bug indeed, as far as I can tell. /cc @Araq 

here's a minimal example:
test1.nim:
```nim
import osproc
let temp = execCmdEx("nim", {poStdErrToStdOut, poUsePath, poEvalCommand})
```

nim c -r test1.nim
```
Hint: operation successful (34235 lines compiled; 1.787 sec total; 48.359MiB peakmem; Debug Build) [SuccessX]
Hint: C:\Users\timothee\git_clone\Nim\test1.exe  [Exec]
test1.nim(13)            test1
osproc.nim(1322)         execCmdEx
osproc.nim(582)          startProcess
oserr.nim(66)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
; Additional info: "Requested command not found: \'nim\'. OS error:" [OSError]
Error: execution of an external program failed: 'C:\Users\timothee\git_clone\Nim\test1.exe '
```
even though nim is in path:
```
C:\Users\timothee\git_clone\Nim>nim
Nim Compiler Version 0.19.0 [Windows: amd64]
...
```

This bug occurs when PATH contains quotes:

```
set PATH=%PATH%;"C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin";"C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin";"C:\Program Files\Sublime Text 3"
```

it works fine when there are no quotes:
```
set PATH=%PATH%;C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin;C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin;C:\Program Files\Sublime Text 3;
```

**Comment by dom96** [comment]
The PATH is `;` delimited, there should be no need to quote anything...

But if cmd.exe supports it then I guess we need to as well.
