### ISSUE TITLE
[osproc] `poUsePath`  doesn't work if PATH contains quotes on windows

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10096]
on windows, procs using `poUsePath` don't work if PATH contains quotes.
quotes are legal and supported by cmd.exe and found on many tutorials.

### Example
here's a minimal example:
test1.nim:
```nim
import osproc
let temp = execCmdEx("nim", {poStdErrToStdOut, poUsePath, poEvalCommand})
```

nim c -r test1.nim
```
Hint: operation successful (34235 lines compiled; 1.787 sec total; 48.359MiB peakmem; Debug Build) [SuccessX]
Hint: C:\Users\timothee\git_clone\Nim\test1.exe  [Exec]
test1.nim(13)            test1
osproc.nim(1322)         execCmdEx
osproc.nim(582)          startProcess
oserr.nim(66)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
; Additional info: "Requested command not found: \'nim\'. OS error:" [OSError]
Error: execution of an external program failed: 'C:\Users\timothee\git_clone\Nim\test1.exe '
```
even though nim is in path:
```
C:\Users\timothee\git_clone\Nim>nim
Nim Compiler Version 0.19.0 [Windows: amd64]
...
```

This bug occurs when PATH contains quotes:

```
set PATH=%PATH%;"C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin";"C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin";"C:\Program Files\Sublime Text 3"
```

it works fine when there are no quotes:
```
set PATH=%PATH%;C:\Users\timothee\Downloads\mingw64-6.3.0\mingw64\bin;C:\Users\timothee\Downloads\nim-0.19.0_x64\nim-0.19.0\bin;C:\Program Files\Sublime Text 3;
```

IIRC using quotes as I did above should be allowed in windows.

### Additional Information
* originally reported here: https://github.com/nim-lang/Nim/issues/10088#issuecomment-449833981
* this also affects building Nim from source on windows if user has a PATH with quotes

**Comment by Araq** [comment]
https://serverfault.com/questions/349179/path-variable-and-quotation-marks-windows
https://stackoverflow.com/questions/34353504/how-to-set-environment-variables-with-spaces

**Comment by timotheecour** [comment]
ok.
for future reference:

https://superuser.com/questions/119610/spaces-and-parenthesis-in-windows-path-variable-screws-up-batch-files

> You do not need to "escape" spaces or parentheses. If you need to escape special characters, then put quotes around the entire expression, including the variable name.
```
SET "PATH=%PATH%;C:\Program Files (x86)\path with special characters"
```
