### ISSUE TITLE
flaky test texceptions.nim: Coroutines executed in incorrect order

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10116]
travis failed in https://travis-ci.org/nim-lang/Nim/jobs/473126759 for https://github.com/nim-lang/Nim/pull/10089 at some point
NIM_COMPILE_TO_CPP=false
on OSX:

```
PASS: tests/async/tfuturevar.nim C                                 ( 3.49262714 secs)
FAIL: tests/coroutines/texceptions.nim C
Test "tests/coroutines/texceptions.nim" in category "coroutines"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
exitcode: 1
Output:
texceptions.nim(28)      texceptions
system.nim(3941)         failedAssertImpl
system.nim(3934)         raiseAssert
system.nim(2979)         sysFatal
Error: unhandled exception: /Users/travis/build/nim-lang/Nim/tests/coroutines/texceptions.nim(28, 9) `numbers == @[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]` Coroutines executed in incorrect order [AssertionError]
```

seems unrelated to PR https://github.com/nim-lang/Nim/pull/10089 so there may be a bug in `coro` (even if it's (potentially, I don't know) hard to reproduce that bug)

feel free to find a better mactching label if `async` is inappropriate

**Comment by timotheecour** [comment]
c4ad297 made the test disabled, so this won't be flaky but root cause remains

**Comment by Araq** [comment]
Well coroutines are not officially supported.
