### ISSUE TITLE
sizeof complains about illegal recursion on valid type definition

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10117]
`sizeof` fails on the following forward list definition:
```nim
type
  SharedPtr[T] = object
    val: ptr tuple[atomicCounter: int, value: T]

  Node[T] = object
    value: T
    next: SharedPtr[Node[T]]

  ForwardList[T] = object
    first: SharedPtr[Node[T]]
    len: Natural
```

**Comment by cooldome** [comment]
I have a fix

**Comment by krux02** [comment]
I cannot reproduce this problem. For me it just compiles fine. Even when I add a sizeof.

**Comment by cooldome** [comment]
Yes, this one is not easy to reproduce. The PR comes with a new test that does demonstrate the issue. PR is ready for review

**Comment by krux02** [comment]
I try to reproduce your problem with this. This is how far I could get:

```Nim
type
  SharedPtr[T] = object
    val: ptr tuple[atomicCounter: int, value: T]

  Node[T] = object
    value: T
    next: SharedPtr[Node[T]]

const size2 = sizeof(Node[int]) # scratch.nim(10, 21) Error: cannot evaluate 'sizeof/alignof' because its type is not defined completely

echo size2
```

It seems to be that this is a bug, because the type is defined completely. But this is not an illegal recursion in the type. So I still can't reproduce your original Bug.

**Comment by mratsim** [comment]
Does sizeof use OS specific logic?

**Comment by krux02** [comment]
Not os specific logic, but os and hardware specific initialization.

**Comment by krux02** [comment]
I can reproduce the problem now, even though the problem description is not entirely correct. And it has something to do with the detection of illegal recursions.
