### ISSUE TITLE
{.pushAcrossModuleBoundary profiler: off.} to push a compilation option all the way down

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10120]
## summary
This proposal is a variant of `{.push profiler: off.}` so that the provided compile flag (here, `profiler: off`) applies to procs used (recursively) inside a given scope even if they are defined in other modules:
```nim
{.pushAcrossModuleBoundary profiler: off.}
```

## motivating example
the root cause of https://github.com/nim-lang/Nim/issues/10106 was that `{.push profiler: off.}` used at top-level of nimprof.nim didn't apply to `==` proc which is defined in system.nim, in other words, `push` doesn't apply to a proc that's already defined in another module.

## details
```nim
{.pushAcrossModuleBoundary profiler: off.}
```
would, upon encountering a symbol, recompile it with pushed flags (here,  `profiler: off`), as a separate symbol from maybe already compiled symbol without that flag (the symbol would have a different name thanks to hashing that takes into account compilation options such as `profiler:off`, IIUC) 
that would have benefit of not having to litter stdlib with `{.push profiler: off.}` which IIUC are potentially skewing profile results (and are bad in terms of separation of concerns) eg:
with `pushAcrossModuleBoundary` we could potentially get rid of :
```
lib/system/alloc.nim:11:3:{.push profiler:off.}
lib/system/gc.nim:15:3:{.push profiler:off.}
lib/system/gc.nim:542:3:{.push profiler:off, stackTrace:off.}
lib/system/gc2.nim:20:3:{.push profiler:off.}
lib/system/gc2.nim:407:3:{.push profiler:off.}
lib/system/gc_ms.nim:13:3:{.push profiler:off.}
lib/system/gc_ms.nim:351:3:{.push profiler:off.}
lib/system/profiler.nim:19:3:{.push profiler: off.}
lib/system.nim:1481:3:{.push profiler: off.}
lib/system.nim:2966:5:  {.push profiler: off.}
lib/system.nim:3101:9:      {.push profiler: off.}
lib/system.nim:3491:7:    {.push profiler:off.}
```

Note that `pushAcrossModuleBoundary` would apply to other compiler flags, not just `profiler:off`

**Comment by Araq** [comment]
> the root cause of #10106 was that {.push profiler: off.} used at top-level of nimprof.nim didn't apply to == proc which is defined in system.nim, in other words, push doesn't apply to a proc that's already defined in another module.

How so? That proc is in a  {.push profiler: off.} environment too!

**Comment by Araq** [comment]
And bugfixes don't require more pragmas, more features, more RFCs anyway.
