### ISSUE TITLE
unittest: require doesn't work at CT

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10129]
```nim
import unittest

const a = 10

static:
  doAssert a == 10 # works
  require a == 10 # fails: Error: cannot evaluate at compile time: abortOnError
```

this prevents using `unittest` as drop-in replacement for doAssert when CT is needed

* there should be a sensible fallback implementation for `require` that works at CT
* for `check`, maybe only RT support makes sense (unless one wants to abort at later stage at CT, but that could be future enhancement)

**Comment by Araq** [comment]
It's ok, we don't claim you can use it at compile-time.
