### ISSUE TITLE
missing % for DateTime, leading to confusing error when converting an object with DateTime field

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#10126]
**Example**
```
import json, times
type ObjWithDateTime = object
  dt : DateTime
  x : int

proc newObjWithDateTime() : ObjWithDateTime = 
    result.x = 1
    result.dt = now()
    
proc mkJson(obj : ObjWithDateTime) : JsonNode =
    var jn = % obj 
    result = jn
    
proc main() =
  let obj = newObjWithDateTime()
  let jn = obj.mkJson()
```
**2 issues:**
1) The error message talks about % and DateTime, but could be clearer. (since it's a field inside the object)
2) In addition, need to implement % for DateTime in the stdlib.

**Comment by kobi2187** [comment]
> lib/pure/json.nim(807, 41) Error: type mismatch: got 
> but expected one of: 
> proc `%`(s: string): JsonNode
> proc `%`(n: BiggestInt): JsonNode
> proc `%`(n: float): JsonNode
> proc `%`(b: bool): JsonNode
> proc `%`(keyVals: openArray[tuple[key: string, val: JsonNode]]): JsonNode
> template `%`(j: JsonNode): JsonNode
> proc `%`[T](elements: openArray[T]): JsonNode
> proc `%`(o: object): JsonNode
> proc `%`(formatstr, a: string): string
> proc `%`(formatstr: string; a: openArray[string]): string
> proc `%`(o: ref object): JsonNode
> proc `%`(o: enum): JsonNode
> 
> expression: %o.zoneInfoFromUtc

**Comment by Araq** [comment]
JSON doesn't have a canon DateTime representation, so yes, you need to implement it on your own.
