### ISSUE TITLE
Nim compiler performance bottlenecks 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10132]
/cc @mratsim since you've done work on optimizing certain functions, and this post shows comparisons of several profilers:
* nimprof
* valgrind's callgrind
* OSX instruments based on sampling
* OSX /usr/bin/sample program

[still WIP, will add more details here...]

according to both callgrind and OSX instruments time profile, it looks like genericReset and genericResetAux are performance bottlenecks for nim compiler (with -d:release)

Here's a sample (best viewed interactively or via a text file rendering; this is just to give a feel)

![image](https://user-images.githubusercontent.com/2194784/50546418-c0afc980-0bdb-11e9-93f1-8b3eada56b36.png)

EDIT:

![image](https://user-images.githubusercontent.com/2194784/50545667-aec72a00-0bcd-11e9-889a-2f13a6f3822f.png)

as pointed by @araq, something's odd here: `genericReset` doesn't call `Marker_tyRef_oQuE3daAnIJJmmxLCZ80bA` (and doesn't show with `(lldb) disassemble --frame` nor does it stop with `(lldb) b Marker_tyRef_oQuE3daAnIJJmmxLCZ80bA`)) yet:
```
nim c -d:release -d:valgrind_workaround_10121 --passC:-g compiler/nim.nim
valgrind --tool=callgrind --fullpath-after= compiler/nim c compiler/nim.nim
callgrind_annotate --tree=both callgrind.out.19042 > /tmp/z05.txt # adjust for pid
```
=> see results here: https://gist.github.com/timotheecour/ff792c52e7f4abdb0b7289e83d06b0c4

shows it calls it (as does above graph):
not sure whether it's a valgrind bug.
Most other entries in `callgrind_annotate` seem to make sense though (on quick inspection).
Note also that since I'm using -d:release, calls may be indirect (eg `isOnStack_dJJW59cIgsBmT59aZrOM71Mg` isnt' called directly but is called indirectly, maybe its caller was inlined by optimizer)

```
8,005,377,631  < /Users/timothee/.cache/nim/nim_r/stdlib_system.c:genericResetAux_ruA1rosalqf8AhzZPPTBQg'2 (126844407x) [compiler/nim]
1,963,926,360  < /Users/timothee/.cache/nim/nim_r/stdlib_system.c:genericReset'2 (43642808x) [compiler/nim]
4,983,864,794  *  /Users/timothee/.cache/nim/nim_r/stdlib_system.c:genericReset'2 [compiler/nim]
   77,451,433  >   /Users/timothee/.cache/nim/nim_r/stdlib_system.c:genericResetAux_ruA1rosalqf8AhzZPPTBQg'2 (312571x) [compiler/nim]
2,456,162,719  >   ???:Marker_tyRef_oQuE3daAnIJJmmxLCZ80bA (136364453x) [compiler/nim]
  487,898,685  >   /Users/timothee/.cache/nim/nim_r/stdlib_system.c:isOnStack_dJJW59cIgsBmT59aZrOM71Mg (32526579x) [compiler/nim]
1,963,926,360  >   /Users/timothee/.cache/nim/nim_r/stdlib_system.c:genericReset'2 (43642808x) [compiler/nim]
```

**Comment by timotheecour** [comment]
using OSX instruments (sampling based profiler):

![image](https://user-images.githubusercontent.com/2194784/50546067-6c561b00-0bd6-11e9-9a94-6ba410590785.png)

**Comment by timotheecour** [comment]
and here are results using nimprof: https://gist.github.com/timotheecour/ba3e5a30a5c5d2edb65f1984f0793adf

**Comment by timotheecour** [comment]
one noteworthy point is that nimprof doesn't reveal that `zeroMem` (or any of what it calls, eg `memset` or `_platform_bzero$VARIANT$Haswell`) is a bottleneck, even though the 2 other profiling approaches reveal this (and the fact it is an actual bottleneck as argued here https://github.com/nim-lang/Nim/issues/10132#issuecomment-450550186)

**Comment by alehander42** [comment]
I can also do a full callgraph(not sampling) tomorrow, I have some local tools if this can help with something

**Comment by timotheecour** [comment]
and yet another sampling approach, using OSX built in `sample`  (/usr/bin/sample)

see https://gist.github.com/timotheecour/c18ba422b186eccae8eb3beb235bb060
(the full file is 43MB as it shows the full stacktraces, organized as a tree of all stacktrace semgents that were observed)
but it corroborrates results for the most part, ie genericReset, interiorAllocatedPtr, genericResetAux, _platform_bzero$VARIANT$Haswell, splitChunk as the bottlenecks

Note: 
/cc @Araq 
seems to me `/usr/bin/sample` has same goals as nimprof (each data sample is a stacktrace) but addresses my main concerns with it (uses interrupt at regular time intervals, thus avoiding bias from nimprofs's approach, and also avoids any instrumentation as it deals with a raw un-modified binary being run)
Only downsides:
* it's OSX only (but maybe available for linux too? maybe sources are available, idk)
* I don't know how to have <1ms sampling rate, but that can be worked around by using repeated calls to what we're sampling

**Comment by timotheecour** [comment]
`--profileVM` is relevant (but by no means a full solution)

**Comment by ringabout** [comment]
genericReset has already gone.

**Comment by ringabout** [comment]
It is a bit outdated.
