### ISSUE TITLE
PFrame,StackTraceEntry should use compressed representation (via index)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10140]
`--stackTrace:on` (which is the default) can be really expensive in terms of performance (see https://github.com/nim-lang/Nim/issues/8959, eg 6X slowdown in simple real example), and perhaps also in terms of memory (stack) usage.

`PFrame`,`StackTraceEntry` are rather heavy, and (IIUC) only actually used when displayed in a stacktrace:

```
type
  PFrame* = ptr TFrame  ## represents a runtime frame of the call stack;
                        ## part of the debugger API.
  TFrame* {.importc, nodecl, final.} = object ## the frame itself
    prev*: PFrame       ## previous frame; used for chaining the call stack
    procname*: cstring  ## name of the proc that is currently executing
    line*: int          ## line number of the proc that is currently executing
    filename*: cstring  ## filename of the proc that is currently executing
    len*: int16         ## length of the inspectable slots
    calldepth*: int16   ## used for max call depth checking
```

instead of storing all these, we could just store a single index (eg `idx: int`) and, only when needed (eg during stacktrace printing) compute the corrsponding fields via a lookup table (a bit similar to using `FileIndex* = distinct int32` in some of the compiler code)

- [ ] Using an index could improve these:
* memory: less stack usage
* faster nimprof (which IIRC uses procname to compare stackframes)
* speedup nim applications built with `--stackTrace:on` (the default), since there's less copying involved (could affect cache hit rate etc). Obviously this would need to be shown

- [ ] at the very least, `line` should be smaller than `int`, eg `int16` (if somehow we don't want to use an index)

- [ ] ditto with `StackTraceEntry`

- [ ] `PFrame,StackTraceEntry` should probably be refactored to avoid duplication (maybe 1 could embed the other for eg)

**Comment by Araq** [comment]
Every C compiler I know of merges ``cstring`` literals. An index could use 4 bytes instead of 8 on a 64 bit machine. You would need to prove that it's worth it, I doubt it. And even then the added complexity needs to be justified.

Btw this is an *issue tracker*, not a list of your musings. Not your personal todo list.
