### ISSUE TITLE
Nimpretty wrong indentation for doc comments

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#10156]
Nimpretty doesn't fix indentation for doc comments except for the first line.

### Before
```nim
proc foo =
    ## Comment
    ## Comment
    discard

proc bar =
  ## Comment
  ## Comment
  discard
```

### After
```nim
proc foo =
    ## Comment
    ## Comment
    discard

proc bar =
    ## Comment
  ## Comment
    discard

```

### Expected after
```nim
proc foo =
    ## Comment
    ## Comment
    discard

proc bar =
    ## Comment
    ## Comment
    discard

```

**Comment by timotheecour** [comment]
@GULPF the code you posted is invalid:
> Error: implementation of 't0094.bar()[declared in t0094.nim(9, 6)]' expected

not clear to me nimpretty should handle correctly invalid code (or at least, it's not as urgent as fixing all the other issues with nimpretty on valid code)

**Comment by GULPF** [comment]
@timotheecour It's not invalid, they are forward declarations. This compiles:
```nim
proc foo
    ## Comment
    ## Comment

proc bar
  ## Comment
  ## Comment

proc foo = discard
proc bar = discard
```

This bug happens for non-forward declarations as well.

**Comment by timotheecour** [comment]
still, the code you posted in top-post is invalid; can you update it with the version that's valid from https://github.com/nim-lang/Nim/issues/10156#issuecomment-450756466 ?
(and yes, your bug is indeed a nimpretty bug)

**Comment by timotheecour** [comment]
> There's no reason why code that doesn't survive semcheck can't be formatted

semcheck, maybe, but it should parse at least; is there a way to check for that? 
rationale: the code will reformat in un-intended way otherwise
