### ISSUE TITLE
master branch outdated (doesn't point to latest git release tag 0.19.2)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10164]
not sure if theres a doc outlining the release process but it should include: `update master` (at least until https://github.com/nim-lang/Nim/issues/8576 is done, after which it'd be called `stable`)

right now `master` branch points to some 0.19 + 1 commit (https://github.com/nim-lang/Nim/commit/72e15ff739cc73fbf6e3090756d3f9cb3d5af2fa)
it should point to latest release, ie, 0.19.2

## links
* see also https://forum.nim-lang.org/t/4344#27057 development and release model: use the `oneflow` model

**Comment by narimiran** [comment]
Merged `version-0-19` branch into `master`.

**Comment by timotheecour** [comment]
@narimiran  thanks; any way we could add this reminder to "release" instructions? (if that doc doesn't exist, then maybe in a new paragraph in https://nim-lang.github.io/Nim/contributing.html)
