### ISSUE TITLE
`proc dlclose(lib: LibHandle) {.importc, header: "<dlfcn.h>".}` should return cint instead of void

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10166]
http://pubs.opengroup.org/onlinepubs/007904975/functions/dlclose.html shows the signature:
int dlclose(void *handle);

`proc dlclose(lib: LibHandle) {.importc, header: "<dlfcn.h>".}` should return cint instead of void

even if it's `discardable` (probably shouldn't be), users may want to check return value

**Comment by alaviss** [comment]
It's not exported anywhere and only used as implementation for the `dynlib` module, so I don't think this is an issue.

On the other hand, the `dlclose` exported by the `posix` module does return `cint`.

**Comment by krux02** [comment]
@alaviss thank you for clearing this up. @timotheecour please do not open up issues so carelessly like this one. It is really bothering because you open up so many of them.

**Comment by timotheecour** [comment]
@krux02 @alaviss 

> I don't think this is an issue

it is, see https://github.com/nim-lang/Nim/pull/10171
it causes `unloadLib` to ignore failures in `dlclose`, so the code in https://github.com/nim-lang/Nim/pull/10171 doesn't catch the bug that libHandle wasn't initialized

**Comment by alaviss** [comment]
> it is a bug. It causes `unloadLib` to ignore failures in `dlclose`, instead of throwing and showing `dlerror()` msg (eg when libHandle wasn't initialized / isn't valid)

That is an implementation detail. It doesn't _cause_ `unloadLib` to ignore error, `unloadLib` is _designed_ like that. This issue would be treated differently if it was actually on point instead of complaining about an interface that's only used internally.
