### ISSUE TITLE
top level defer is executed when it encounters import

### ISSUE THREAD

**Issue by jiro4989** [nim-lang/Nim#10186]
### NG Example

```nim
import streams

var s = "test.dat".newFileStream fmWrite
defer: s.close
s.write '\x61'

# i think that here 'import' is problem.
import sequtils

for d in [1, 2, 3].mapIt($it):
  s.write d
```

### Current Output

```bash
nim c -r defer.nim   
```

```
Traceback (most recent call last)
defer.nim(10)            defer
streams.nim(136)         write
streams.nim(112)         writeData
streams.nim(421)         fsWriteData
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/defer '
```

### OK Example

```nim
import streams
import sequtils

var s = "test.dat".newFileStream fmWrite
defer: s.close
s.write '\x61'

for d in [1, 2, 3].mapIt($it):
  s.write d
```

### Output

Success executing.

### Other close Example

```nim
var f = "test.txt".open fmReadWrite
defer: f.close

import sequtils

# Error is not occured.
# and "1" is not written.
f.write "1"
echo "end"
```

### Output

```bash
$ nim c -r open.nim
end
$ cat test.txt | wc  
      0       0       0
```

### Possible Solution

I think that executing 'import' then `defer s.close`  is executed too.
This problem can be avoided, write imports at the beginning of the file.

Is it bad for compiler that writing the 'import' in the middle of file?

**Comment by krux02** [comment]
I think the top level defer is causing the problem. For this use case you don't technically need the defer. When the process terminates the operating system will reliably  close all remaining open file handles for you.

**Comment by nc-x** [comment]
```
import streams

var s = "test.dat".newFileStream fmWrite
defer: s.close
s.write '\x61'

echo s.f.isNil            # false                 (first, export `f` in `FileStreamObj`)
import sequtils
echo s.f.isNil            # true           


for d in [1, 2, 3].mapIt($it):
  s.write d
```
defer is executing when it encounters import

**Comment by krux02** [comment]
I guess somebody "fixed" that limitation.

**Comment by nc-x** [comment]
The code is still there https://github.com/nim-lang/Nim/blob/be0a4d1342b05815e25f9a51bda0cf199a6d439e/compiler/sem.nim#L558-L560
