### ISSUE TITLE
Nimscript doesn't raise any exceptions

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#10240]
I was working on implementing `stdin.readLine()` support in nimscript and was unable to get `EOFError` exposed. Just to verify, I tried to use the existing `rmFile()` code which should raise `OSError` if you try to remove a file that is currently in use. This doesn't work despite being raised in `checkOsError()` in [nimscript.nim](https://github.com/nim-lang/Nim/blob/devel/lib/system/nimscript.nim#L181).

Build and run any test.exe which stays resident and then try `nim e test2.nims` with the following code:
```nim
rmFile("test.exe")
```

Command just runs with no errors and test.exe is still present. Verified failure with #head 0.19.2 and 0.19.0.

**Comment by genotrance** [comment]
Went further back and tested with 0.18.0, 0.17.2, 0.16.0 and 0.15.2 and issue is still present. Unclear where it worked.

**Comment by Araq** [comment]
Can't reproduce.
