### ISSUE TITLE
megatest compilation failure gives no useful information, hence hard to investigate

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10249]
I am getting not helpful error message: ``megatest compilation failed``. No reason is specified. 
I have tried running testament with `--verboseMegatest`, it has zero effect. The error message stays the same. Megatest should display what nim command was executed with all the arguments and the file path in verbose mode.

https://api.travis-ci.org/v3/job/477244846/log.txt

**Comment by krux02** [comment]
well the nim command for megatest is always ``nim c -r megatest.nim`` in the Nim home folder, and when the megatest fails that file isn't deleted.

**Comment by timotheecour** [comment]
> Megatest should display what nim command was executed with all the arguments and the file path in verbose mode

=> PR https://github.com/nim-lang/Nim/pull/10266 for this particular point

the root cause of what you're seeing has nothing to do with testament nor megatest, I will explain in a bit what's going on

**Comment by Clyybber** [comment]
The logs now show megatest failures.
