### ISSUE TITLE
make graveyard an implicit dependency for nimble projects, to avoid breakages

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10265]
## proposal
* graveyard becomes an implicit dependency for nimble projects
* a warning (that can be turned off) is shown when something in graveyard is used

## motivation
* this PR https://github.com/nim-lang/Nim/pull/10248 broke some projects (eg `nimongo + others that depend on it, see also https://github.com/nim-lang/Nim/pull/10248#issuecomment-453306831); with this proposal, nothing would break, but a warning would be emitted when you start depending on modules that were moved to graveyard so you are reminded to use a better alternative
* this would make it easier to seamlessly evolve/cleanup stdlib without breaking "the world"

## alternative 
require users to call:
```
nimble install foo
```
for a pkg `foo` that was moved to graveyard

**Comment by Araq** [comment]
That we moved ``oids`` and ``smtp`` to the graveyard was a mistake, we're reverting this change. Graveyard is for abandoned modules.

**Comment by timotheecour** [comment]
closing, satisifed w the revert of oids, smtp

**Comment by alehander42** [comment]
graveyard shouldn't be an implicit dependency, I want to see what I depend on in my nimble files and people should take an explicit decision if they want to continue using those modules
