### ISSUE TITLE
generate and serve docs for `compiler/**`, `tools/**` `testament/**` etc

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10276]
given that `compiler`, `tools` `testament`, are under Nim repo, they should appear in https://nim-lang.github.io/Nim/
eg:

## exixting:
* https://nim-lang.github.io/Nim/lib.html stdlib (current)
* https://nim-lang.github.io/Nim/koch.html

## proposed:
* https://nim-lang.github.io/Nim/compiler/index.html
  * note: not https://nim-lang.github.io/Nim/compiler.html as it's a different nimble package and nim allows IIRC modules w same name so long they're in different nimble packages, so putting compiler docs in its own dir will avoid clashes
   * eg: https://nim-lang.github.io/Nim/compiler/btrees.html etc
* https://nim-lang.github.io/Nim/tools/index.html
  * https://nim-lang.github.io/Nim/tools/nimpretty.html

more generally, each nimble package `foo` hosted under Nim (maybe it's just `compiler` for now) should go under https://nim-lang.github.io/Nim/foo/index.html

## rationale
* out of sight, out of mind; ppl may not know stuff like https://nim-lang.github.io/Nim/compiler/btrees.html exists
* if it's not seen, it's not used, bugs won't be reported as much and improvements won't come as fast
* generally compiler sources have poorer documentation, and it makes it harder for contributors to dig in the code; this proposal would go towards improving docs and making it easier for ppl to contribute
* we can add a warning `experimental, may change, not stable` if needed

## note
* as noted on gitter, `segfaults` module also doesn't yet appear in docs; refs: https://irclogs.nim-lang.org/01-02-2019.html#11:16:21
> why is 'segfaults' nowhere in the docs?

**Comment by narimiran** [comment]
> as noted on gitter, segfaults module also doesn't yet appear in docs;

This, in particular, has been fixed.

**Comment by Araq** [comment]
I don't see why we need to do this. The compiler is for compiler devs.
