### ISSUE TITLE
Performance regression with --gc:markandsweep

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#10271]
As a result of [this commit](https://github.com/nim-lang/Nim/commit/4f08ed63cfc81f8da6658b2823c0d7fbc7f959ab), the GC can be triggered for every allocation in a series of small allocations if compiled with `--gc:markandsweep`, leading to massive overhead.

### Example

For example, on my machine the following code runs in 50ms with the default GC, but takes nearly 4 seconds with `--gc:markandsweep`.

```nim
const n = 1_000_000

type T =
  ref object
    val: int
    next: T

proc main =
  var t: T = nil
  for i in 1..n:
    t = T(val: i, next: t)

main()
```

**Comment by timotheecour** [comment]
maybe related to https://github.com/nim-lang/Nim/issues/10040
