### ISSUE TITLE
Exception types in the stdlib should inherit from `CatchableError` or `Defect`, not `Exception`

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#10288]
Exception types should always inherit from `CatchableError` or `Defect` (directly or indirectly) to indicate if they should be catched or not. Here is a list of exception types in the stdlib that breaks this rule:

- [ ] `nre.RegexError`
- [ ] `asyncfutures.FutureError`
- [ ] `net.SslError`
- [ ] `net.TimeoutError`
- [ ] `punycode.PunyError`
- [ ] `selectors.IOSelectorsException`

**Comment by Araq** [comment]
My guesses:

nre.RegexError --> CatchableError
asyncfutures.FutureError --> Defect (@dom96?)
net.SslError --> CatchableError
net.TimeoutError --> CatchableError
punycode.PunyError --> CatchableError
selectors.IOSelectorsException --> no idea (@cheatfate?)

**Comment by dom96** [comment]
What does "Defect" even mean? That I can't or that I shouldn't catch it?

**Comment by Araq** [comment]
That it's a bug, you don't catch bugs, you fix them.

**Comment by dom96** [comment]
Okay, well then ``FutureError`` is indeed a defect. It's only raised when you attempt to finish a future more than once.

**Comment by disruptek** [comment]
Currently, `Defect` is catchable.  I like the idea of differentiating from `CatchableError`, but maybe the semantic lacks teeth as long as it's inaccurate.  It would be handy to have to modify `{.raises.}` that can throw `Defect` as opposed to letting them get caught by overzealous exception handlers.  This is a breaking change, of course...
