### ISSUE TITLE
`type` parameters treated as "bind once" -- surprising and contradicts manual

### ISSUE THREAD

**Issue by deansher** [nim-lang/Nim#10298]
I define a template with two parameters, both having type `type`. Then I try to invoke it with two literal types. This doesn't compile, with a wrong-looking complaint about the second type parameter. If I eliminate one of the type parameters, it works.

### Example
```nim
template helloWorld(T1: type, T2: type): untyped = 
  echo "Hello, world!"

helloWorld(string, int)
```

### Current Output
```
template_param_is_type.nim(4, 11) Error: type mismatch: got <type string, type int>
but expected one of:
template helloWorld(T1: type; T2: type): untyped
  first type mismatch at position: 2
  required type: type
  but expression 'int' is of type: type int

expression: helloWorld(string, int)
```

### Expected Output
```
Hello, world!
```

### Additional Information
```
deans-mbp-3:the-edge-of-Nim dean$ nim -v
Nim Compiler Version 0.19.2 [MacOSX: amd64]
Compiled at 2018-12-31
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 7beea1642ddf7845a9a0034c7a93ccbe15894c36
active boot switches: -d:release
```

**Comment by GULPF** [comment]
I think this works as described in the manual. `type` is treated as a type class because you don't specify a generic parameter, which means that the implied generic parameter must match. 
```nim
template helloWorld(T1: type, T2: type): untyped = 
  echo "Hello, world!"

helloWorld(string, string) # Works!

template helloWorld2[A, B](T1: type[A], T2: type[B]): untyped = 
  echo "Hello, world!"

helloWorld2(string, int) # Works!
```

**Comment by narimiran** [comment]
I'm taking @GULPF's answer as a solution to this problem, so I'm closing this.

**Comment by zah** [comment]
`type` is currently a "bind once" type, but I consider this an oversight. It's not really convenient.

**Comment by krux02** [comment]
Well I guess this is a good example where all the features to provide a nice syntax and automatically try to do the right thing make everything worse. If you would be forced to provide the generic parameters all the time, then this error would be a bit more obvious. It is surprising that two different values of type parameters actually also have a different type.

Creating a procedures with two type parameters of the same type could emit a warning though, as I would guess that it is never intentional to write a function/template like `helloWorld(t1,t2: type)`, where t1 and t2 have to be the same type.

**Comment by deansher** [comment]
The current behavior contradicts the manual. Also, I'd argue that it is surprising, inconsistent with how other parameter types are handled (e.g. multiple `int` parameters can be given different integer values), and is probably not what the programmer wanted. Here's the manual on this subject (although for procs):

> When multiple type params are present, they will bind freely to different types.
> To force a bind-once behavior one can use an explicit generic param:

```
proc acceptOnlyTypePairs[T, U](A, B: type[T]; C, D: type[U])
```

**Comment by andreaferretti** [comment]
@krux02 I disagree, the feature to omit the generic parameter is nice, is the hidden assumption that there is only one generic parameter instead of multiple ones that is dangerous

**Comment by krux02** [comment]
I just tested this issue and the expected output is created.
