### ISSUE TITLE
compile pragma name collision

### ISSUE THREAD

**Issue by richard-jansson** [nim-lang/Nim#10299]
When creating a nim binding the compile pragma should not refer to the same filename / basename as the c file. 

### Example

```nim
{.compile: "/home/richard/proj/nimlisten/test.c".}
{.passC: "-I/home/richard/proj/nimlisten ".}

proc init*(port: cint) {.cdecl, importc: "init".}
```
Given that the nim file has the same filename as the c file. There'll be a collision on the temporary object files. The test.c.o path is specified twice in the argument given to the C compiler. 

### Current Output
```
richard@richard-ThinkPad-T430:~/proj/nimlisten$ nim c -r nimlisten.nim
Hint: used config file '/home/richard/src/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: nimlisten [Processing]
Hint: test [Processing]
CC: nimlisten
Hint:  [Link]
/home/richard/.cache/nim/nimlisten_d/test.c.o: In function `init':
test.c:(.text+0x0): multiple definition of `init'
/home/richard/.cache/nim/nimlisten_d/test.c.o:test.c:(.text+0x0): first defined here
/home/richard/.cache/nim/nimlisten_d/test.c.o: In function `close':
test.c:(.text+0x24): multiple definition of `close'
/home/richard/.cache/nim/nimlisten_d/test.c.o:test.c:(.text+0x24): first defined here
/home/richard/.cache/nim/nimlisten_d/nimlisten.c.o: In function `PreMainInner':
nimlisten.c:(.text+0x25): undefined reference to `unknown_testDatInit000'
nimlisten.c:(.text+0x2f): undefined reference to `unknown_testInit000'
/usr/bin/x86_64-linux-gnu-ld: /home/richard/proj/nimlisten/nimlisten: hidden symbol `unknown_testDatInit000' isn't defined
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o /home/richard/proj/nimlisten/nimlisten  /home/richard/.cache/nim/nimlisten_d/test.c.o /home/richard/.cache/nim/nimlisten_d/nimlisten.c.o /home/richard/.cache/nim/nimlisten_d/stdlib_system.c.o /home/richard/.cache/nim/nimlisten_d/test.c.o    -ldl'
```

Highlight of problematic part note that test.c.o is included twice. 
```
Error: execution of an external program failed: 'gcc   -o /home/richard/proj/nimlisten/nimlisten  /home/richard/.cache/nim/nimlisten_d/test.c.o /home/richard/.cache/nim/nimlisten_d/nimlisten.c.o /home/richard/.cache/nim/nimlisten_d/stdlib_system.c.o /home/richard/.cache/nim/nimlisten_d/test.c.o    
```

### Expected Output

```
richard@richard-ThinkPad-T430:~/proj/nimlisten$ nim c -r nimlisten.nim
Hint: used config file '/home/richard/src/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: nimlisten [Processing]
Hint: testi [Processing]
CC: nimlisten
Hint:  [Link]
Hint: operation successful (12325 lines compiled; 0.212 sec total; 16.23MiB peakmem; Debug Build) [SuccessX]
Hint: /home/richard/proj/nimlisten/nimlisten  [Exec]
initialzing at 20
hello
```

### Possible Solution
Changing the name of the file see additional information for example. 

According to shasclick on irc it's possible to tell compile to generate unique o files. 
https://github.com/genotrance/nimgen/blob/master/src/nimgen/gencore.nim

### Additional Information
Here it doesn't work 
https://github.com/richard-jansson/nimlisten/commit/cc12c5c48dc79f50bcf444b2370efe8c89501e12
Renaming does the trick:
https://github.com/richard-jansson/nimlisten/commit/41e6ac43c59cd00735fca65e7178946f0a5c3dd4

```
richard@richard-ThinkPad-T430:~$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2018-12-05
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 24106ade8fee790fcfbab17d6c7825d79e05c7f3
active boot switches: -d:release
```

**Comment by Araq** [comment]
Nah, we can simply simulate a ``nim`` Nimble package that everything is in.

**Comment by genotrance** [comment]
This also breaks when you have the same file name but in different directories like in some C/C++ libraries. Since nimcache is a flat directory, everything just gets the same name.

I've worked around this in nimgen by generating the correct compile pragma but a better message will definitely help to save debug time.

**Comment by krux02** [comment]
I don't have anything specific against flat simple name conversions without any visual noise added to the process. For example my editor plugin relies on the fact that the nim file and the generated c file have the exact same name.

**Comment by richard-jansson** [comment]
Hi

Instinctively I'd go about it like this. I'd simply add a hash of the
absolute path to the name to the name. That'd fix the problem in a few
lines of code. I don't know if that'd have any side effects but that'd be
my five cents.

The thing is that I suspect that quite a few people that get into nim will
find this, while the c2nim file by default generates a nim file with the
same basename as the header. C-coders quite often, more often than not
even, have c-files and h-files with the same basename.

Another route obviously would be to either supply a warning as I believe
someone said in the IRC channel and or to provide additional documentation.

Found an earlier reference to the issue. So perhaps this should be flagged
as a duplicate.
https://github.com/nim-lang/Nim/issues/3072

Again not the biggest issue I suppose, so maybe it's not worth putting that
much time into it. Still as it's something that beginners might run into it
might be a good idea to try to avoid that. It's a shame if they got the
perception that nim has faults, when it's such a elegant and well suited
tools in all the other areas.

regards
Richard Jansson

**Comment by genotrance** [comment]
I don't think this will fix all cases - if you have abc/test.c and def/test.c, they will still collide. This commit only handles Nim and C file collision.

**Comment by genotrance** [comment]
Here's how nimterop deals with C file collisions.

https://github.com/nimterop/nimterop/blob/master/nimterop/cimport.nim#L442

**Comment by genotrance** [comment]
Never mind, it is being tracked separately in https://github.com/nim-lang/Nim/issues/9370.
