### ISSUE TITLE
GC_ref on empty string fails with [GCASSERT] incRef: interiorPtr

### ISSUE THREAD

**Issue by iffy** [nim-lang/Nim#10307]
Calling `GC_ref()` on an empty string when running with `-d:useGcAssert` causes a GCASSERT error (which is different than if the string is non-empty).

### Example

```nim
proc someProc(x:bool):cstring =
  var res:string = ""
  if x:
    res = "yes"
  echo "res.repr: ", res.repr
  GC_ref(res)
  result = res

echo "running someProc(true)"
echo someProc(true)

echo "running someProc(false)"
echo someProc(false)
```

### Current Output
```
running someProc(true)
res.repr: 0x10d90f058"yes"
yes
running someProc(false)
res.repr: ""
[GCASSERT] incRef: interiorPtr
Traceback (most recent call last)
testthing.nim(13)        testthing
testthing.nim(6)         someProc
gc.nim(198)              nimGCref
gc.nim(116)              incRef
```

### Expected Output

```
running someProc(true)
res.repr: 0x10d90f058"yes"
yes
running someProc(false)
res.repr: ""

```

### Possible Solution

It seems from the repr output that empty strings are treated specially (and likely don't have a location in memory?)  I could change my code to only call GC_ref/unref on non-empty strings, though it would complicate things slightly.  If that's the solution, I'm happy to do it.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.1 [MacOSX: amd64]
Compiled at 2018-10-19
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 863d3ef4ed7d18877a42f0060ebe63c34a27cf32
active boot switches: -d:release
```

**Comment by ringabout** [comment]
It has been fixed since 0.19.2.
