### ISSUE TITLE
[NimScript] thisDir returns "" when script extension is not provided

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#10317]
Test.nims:
```nim
echo thisDir()

task foo, "bar":
  discard
```
CMD:
```nim
>nim foo Test.nims
[...]/nim/test/test_nims
>nim foo Test
[Empty String]
```
This wasn't an issue two days ago.
***
```nim
>nim -v
Nim Compiler Version 0.19.9 [Linux: i386]
Compiled at 2019-01-15
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 4355f23ee5fd53acfdaa8ecb5dbb50f9b43f98b2
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment]
Yeah, a "directory" string should never be an empty string; it doesn't make sense as "" directory means nothing.

**Comment by krux02** [comment]
cannot reproduce. Is it still a problem. With both commands I get the correct directory.

**Comment by Wh1teDuke** [comment]
> cannot reproduce. Is it still a problem. With both commands I get the correct directory.

In my computer the issue persists.

**Comment by Araq** [comment]
Works for me here too. Unreproducible.
