### ISSUE TITLE
Support for types which have potentially differing types? 

### ISSUE THREAD

**Issue by sillibird** [nim-lang/Nim#10311]
I've been working a lot with nethttp and unmarshalling json responses. I was hoping to, but don't seem to be able to have support for a blanket type that would allow varying data to it.

For example

```nim
type
    Response = object
        data: varyingType
```

where the placeholder of varyingType could be passed various types, such as a integer or a string.

**Comment by mratsim** [comment]
You can use JsonNode at the moment.

See also RFC https://github.com/nim-lang/RFCs/issues/80 for a similar proposition.

Closing as duplicate.

**Comment by bluenote10** [comment]
For the record: I posted an example in the linked RFC how I had solved the issue before...
