### ISSUE TITLE
Dynamic type field access via []?

### ISSUE THREAD

**Issue by absolutejam** [nim-lang/Nim#10350]
### Summary
I'm not sure about the implications of this, but it would be really great if we could access an object's field based on a string value, like how hashtables work, eg.
```nim
type Foo = ref object
  name*: string

aFoo = Foo(name: "Something")
aFoo["name"] # => "Something"
```

I did see a macro on the forums but couldn't get it to work as (Can't currently post on the forums :cry:).

### Description
Provides dynamic access to fields and cuts out unnecessary boilerplate.

### Alternatives
Honestly, I don't know the implications of this on a static language.

**Comment by mratsim** [comment]
Nim is getting a new RFCs repo as we're getting a lot of suggestions lately, can you reopen there? https://github.com/nim-lang/RFCs/issues.

**Comment by Araq** [comment]
Not gonna happen in this form. Workarounds:

- You can turn your object into JSON.
- you can use the ``fieldPairs`` iterator on an object
- you can pass object field names to templates to reduce boilerplate.

**Comment by mratsim** [comment]
Additional workaround, use typeinfo:

https://forum.nim-lang.org/t/4573

```Nim
import typeinfo

type
  Foo = object
    field: int

var foo = Foo(field: 123)
echo foo.field

let x = foo.toAny
echo x["field"].getInt
```
