### ISSUE TITLE
The value of low(<signed integer type>) cannot be used as a literal 

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#10369]
Test case:
```nim
discard -9223372036854775808'i64 # Error: invalid number: '9223372036854775808'i64'
discard -128'i8 # Error: number out of range: '128'i8'
```
The cause of this is that the lexer & parser treats all integer literals as positive, for example `-128'i8` is treated as `` `-`(128'i8)`` which is invalid. Since this affects the AST, changing it would be a breaking change.

Since the [manual](https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants) specifies that numerical constants can only be positive, I suppose this isn't a bug, just surprising behavior.

**Comment by Araq** [comment]
GCC doesn't accept it either. ``-9223372036854775808LL`` produces an overflow warning.
