### ISSUE TITLE
Feature request: anonymous var's

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#1037]
Consider these procs:
```nimrod
proc p1: int = 1
proc p2(i: var int): int = i + 1
```

Now compare this:
```nimrod
var x = p1()
var y = p2(x)
```
To something like this:
```nimrod
var y = p2(p1())
```
Or this, which would force the caller to document the fact that any modifications will essentially be discarded:
```nimrod
var y = p2(var p1())
```

This would of course be more useful in more complicated examples, possible involving more than just a single var. Sometimes wrapping a proc removes the need for this, but not always.

**Comment by BigBoneDaddy** [comment]
This does not make sense to me either

**Comment by dom96** [comment]
``var T`` params are designed to be used for "out parameters", so you want to get at that data. I guess if you wanted to discard that data it makes sense but this feature seems really niche.

**Comment by Araq** [comment]
Closing this. Feature is not going to be implemented.
