### ISSUE TITLE
oserr.nim fails with index out of bounds error

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#10380]
oserr.nim contains this line (as of Jan 19, it is line number 62)
`    if e.msg[^1] != '\n': e.msg.add '\n'
`
if msg is empty then a fatal error happens.
Can msg be empty? yes, if osErrorMsg returns the empty string.
When does it return an empty string? when conversion fails or OSErrorCode == 0.

can be fixed by doing:
`    if e.msg.len > 0 and e.msg[^1] != '\n': e.msg.add '\n'`

**Comment by kobi2187** [comment]
https://github.com/nim-lang/Nim/pull/10381

**Comment by dom96** [comment]
Please write "Fixes #10380" in your commit message next time to automatically close issues when your PR is merged

**Comment by kobi2187** [comment]
sure thing, I'm new to github :-) Thanks for merging so promptly!
