### ISSUE TITLE
Release mode - Float -> char conversion issue

### ISSUE THREAD

**Issue by teschty** [nim-lang/Nim#10421]
In release mode (c/cpp backend), incorrect values are produced by the char type converter. Debug mode (as well as JS target) produce correct values.

This appears to be an incorrect dead store elimination *somewhere*, as adding `{.volatile.}` or adding a read to the passed value before the conversion will make it return the appropriate value.

I'm unsure if this is a bug in Nim or GCC.

### Example

```nim
let num = 255.0
let clamped = max(128.0, min(255.0, num))
echo ord(char(clamped))
```

### Current Output
```
127
```

### Expected Output

```
255
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.2 [Linux: amd64]
Compiled at 2018-12-31
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 7beea1642ddf7845a9a0034c7a93ccbe15894c36
active boot switches: -d:release
```

**Comment by LemonBoy** [comment]
The faulty line is the following:
```C
	T1_[0] = nimIntToStr(((NU8) ((NIM_CHAR)clamped_KI4X3UjFbv7ruDkUsPBAOg)));
```
The `signed char` to `unsigned char` is misoptimized (?) into `127`. Replacing `char` with `byte` does the trick though.

**Comment by nc-x** [comment]
Related https://github.com/nim-lang/Nim/issues/10128

**Comment by narimiran** [comment]
~~This works correctly with Nim v1.0.6 and current devel.~~

I stand corrected. It works correctly without `-d:release`, but not with it.

**Comment by timotheecour** [comment]
this is UB IIUC, maybe we can close this in favor of https://github.com/nim-lang/Nim/issues/18540 which has more details
