### ISSUE TITLE
`>` - surprising arguments evaluation order

### ISSUE THREAD

**Issue by akva** [nim-lang/Nim#10425]
```
proc a(): int = echo "a"; 1

proc b(): int = echo "b"; 2

echo a() > b()
```
outputs
```
b
a
false
```
Even though the manual says "Order of evaluation is strictly left-to-right..." [https://nim-lang.org/docs/manual.html#order-of-evaluation]

**Comment by GULPF** [comment]
This is because `>` is a template which expands `a > b` into `b < a`, hence `b` is evaluated first. Perhaps the template should take special care to evaluate the parameters left to right.

**Comment by akva** [comment]
> This is because > is a template which expands a > b into b < a

I know. That's how I found out.

**Comment by Araq** [comment]
You can also read https://nim-lang.org/docs/tut2.html#templates which covers this.

**Comment by nocturn9x** [comment]
Sorry to necropost, but I was bitten by this (quite frankly absurd) issue just a few hours ago. My code looked something like

```nim

self.push(self.pop() > self.pop())
```

I was dead sure that the order of the arguments on the stack was correct, and I did in fact verify this by simply doing 

```nim
let a = self.pop()
self.push(a > self.pop())
```
which yields the expected result. I quite frankly don't understand 1) why and how templates work like this (in what context is it okay to just, oh I don't know, _arbitrarily reorder arguments_?) and 2) Why the greater than operator isn't defined like so

```nim
proc `>`[T: SomeNumber](a, b: T): bool {.inline.} = b < a
```

This achieves the same effect, without the gotchas of making it a template

**Comment by SolitudeSF** [comment]
> why and how templates work like this (in what context is it okay to just, oh I don't know, arbitrarily reorder arguments?)

how else would they work? how can they preserve the order if they substitute as?
