### ISSUE TITLE
Regression in sequtils

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#10433]
```nim
import sequtils

let
  nums = @[1, 2, 3, 4]
  strings = nums.mapIt(string, $(4 * it))
assert strings == @["4", "8", "12", "16"]
```

Now results in:

```
a1.nim(5, 38) Error: undeclared identifier: 'it'
```

We have runnable examples for this, so I'm not sure what happened here. Maybe only when importing the module?

**Comment by dom96** [comment]
This is because that variant of `mapIt` was deprecated. The error message could definitely be much better, hope people have good google chops

**Comment by Araq** [comment]
@narimiran Give us the old mapIt back but instead of a ``.deprecated`` it should have an ``.error``.
