### ISSUE TITLE
Getting the enum order right

### ISSUE THREAD

**Issue by exetoc** [nim-lang/Nim#1043]
... is tedious in some cases, specifically when attempting to turn a set of related constants into an enum, because you might end up performing tons of re-orderings in order to try to satisfy the ordered property of enums.

Here are some solutions:
+ Print the correct order on failure.
+ Optionally allow enums to be unordered.

**Comment by Araq** [comment]
Instead c2nim re-orders enum fields for us. I think that's good enough for now.
