### ISSUE TITLE
use OS random sources in math.randomize()

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#1044]
Currently, math.randomize() uses the current time as a seed value. This is fine for most use cases, but the standard solution nowadays is to use a random value provided by the OS itself. On some Unix-like systems, `/dev/urandom` is available and on Windows, there is `CryptGenRandom`:
http://msdn.microsoft.com/en-us/library/windows/desktop/aa379942(v=vs.85).aspx

**Comment by dom96** [comment]
Closing as duplicate of #1506.
