### ISSUE TITLE
gc:destructors does not compile for any program currently

### ISSUE THREAD

**Issue by rayman22201** [nim-lang/Nim#10457]
Any program I try to compile with gc:destructors results in the same error.
compiling even `echo "hello world"` with gc:destructors currently results in:

```
../../lib/system/excpt.nim(224, 5) Error: internal error: '=sink' operator is generic
```
This was tested on #head as of commit: 4d230db5abb630db71001e7f70b8a5bbdf6a3e7e

**Comment by Araq** [comment]
It now works but this feature is also actively being worked on. Closing.
