### ISSUE TITLE
ICE with sequtils + algorithm (mapIt, sortedByIt) + json 

### ISSUE THREAD

**Issue by Yardanico** [nim-lang/Nim#10456]
When running that code snippet:
```nim
import sequtils, strutils, algorithm, json


proc test() = 
  try: 
    let info = parseJson("""
    {"a": ["1", "2", "3"]}
    """)
    let prefixes = info["a"].getElems().mapIt(it.getStr()).sortedByIt(it).reversed()
    echo prefixes
  except:
    discard
  
test()
```
(sorry, I tried to make it smaller, but couldn't)

the compiler crashes with an internal error:
```
/home/dian/Stuff/Nim/lib/pure/collections/sequtils.nim(98, 17) Error: internal error: environment misses: :tmp
```

Used latest Nim compiler as of writing this (commit https://github.com/nim-lang/Nim/commit/268197add8e9fbcbf15d6a042c8095828c29869f)

**Comment by narimiran** [comment]
To narrow it a bit down, it seems to be `sortedByIt`'s fault, because 

```nim
import sequtils, strutils, algorithm, json

proc test() =
  try:
    let info = parseJson("""
    {"a": ["1", "2", "3"]}
    """)
    let prefixes = info["a"].getElems().mapIt(it.getStr()).reversed() # removed `sortedByIt`
    echo prefixes
  except:
    discard

test()
```
works just fine.

**Comment by ghost** [comment]
New error message:
``
/home/dian/Things/Nim/lib/pure/collections/sequtils.nim(938, 13) Error: 'it' is of type <lent JsonNode> which cannot be captured as it would violate memory safety, declared here: /home/dian/Things/Nim/lib/pure/collections/sequtils.nim(938, 13); using '-d:nimWorkaround14447' helps in some cases
``
Although if I compile with `-d:nimWorkaround14447` it's the same old error message.

**Comment by narimiran** [comment]
Wait, we have `-d:nimWorkaround14447`? Wtf?!
