### ISSUE TITLE
getAst crashes compiler when called with invalid expression

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#10479]
### Example (test with `nim check`)
```nim
import macros

macro m(): untyped =
  discard getAst nonexistant 0

m()
```

### Current Output
```
Hint: used config file 'config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t [Processing]
Hint: macros [Processing]
t.nim(4, 18) Error: expected a template that takes 1 arguments
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-01-28
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 5fa8a61a238c08bca12da272f71692f2f103b6d8
active boot switches: -d:release
```

**Comment by narimiran** [comment]
I get the same "Error: expected a template that takes 1 arguments", but I cannot reproduce the SIGSEGV.

Does it happen with the latest devel?

**Comment by alaviss** [comment]
Yes, it does. Only with `nim check` however.

**Comment by narimiran** [comment]
Yes, using `nim check` crashes on my end too.

**Comment by krux02** [comment]
Ok, I can explain it. Normal compilation detects the error message and then quits instantly. Nim check however does not quit it continues evaluating. And then when it tried to evaluate the marco invocation ``m()``, it tries to evaluate a macro that is in an illegal state. The solution would be to tag the macro somehow as illegal and then when nim check encounters ``m()`` and sees that the macro is illegal, it should eith skip it, or it should stop doing anything.

**Comment by narimiran** [comment]
> Yes, it does. Only with `nim check` however.

Currently (Nim 0.20.99) there seems to be no crash anymore when using `nim check`.
