### ISSUE TITLE
docgen doesn't create links for certain symbols

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10487]
I really like the new feature introduced by @araq in 13d667ee5312a4705a7ca51ead933739514c70dd (docgen: produce links for proc names).

it doesn't work in some cases eg:

in https://nim-lang.github.io/Nim/osproc.html

- [x] `Process = ref ProcessObj`  => no link for ProcessObj
- [x] no link for enum elements eg: `poStdErrToStdOut` here:
```
proc startCmd(command: string;
             options: set[ProcessOption] = {poStdErrToStdOut, poUsePath}): Process
```

- [ ] no links for symbols inside a `runnableExamples` block (this one is more controversial but would be nice IMO):
(non runnableExamples code block may be impossible as it's not guaranteed to be runnable, but `runnableExamples` should be)
```
var t = {"name": "John", "city": "Monaco"}.newStringTable
doAssert "${name} lives in ${city}" % t == "John lives in Monaco"
```

[EDIT]
- [x] no clickable links for constants, even though apparently they have anchor, eg:
https://nim-lang.github.io/Nim/os.html#ExeExt has anchor but no underline clickable links for it:
![image](https://user-images.githubusercontent.com/2194784/52302153-2a409780-2941-11e9-9167-9e394e5bb534.png)

**Comment by narimiran** [comment]
Two and a half raised points are fixed (with half being: there's no link for enum elements, but in the example `options: set[ProcessOption] = {poStdErrToStdOut, poUsePath}`: `ProcessOption` is clickable and there you can see each enum element).

The remaining point (links in runnableExamples) is, as stated, "more controversial but would be nice", and I don't see enough ROI in it. Therefore, I consider this issue to be fixed.
