### ISSUE TITLE
generic compilerproc should give CT error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10516]
this PR https://github.com/nim-lang/Nim/pull/10228 (at commit 38e82639541e660bb6d25b47f6ba76153e60666e) ran into that issue, but it didn't give a CT error because only 1 type was instantiated.

This snippet illustrates the problem:

```nim
proc foo[T](a: T) {.compilerproc.} =
  echo "ok1"

proc main()=
  #[
  uncomment either and it'll work
  otherwise gives cgen error:
  /tmp/nim/nimcache/timn_t0161.c:50:17: error: conflicting types for 'foo'
  N_NIMCALL(void, foo)(NF a);
  ]#
  foo(1)
  foo(1.1)

main()
```

**Comment by krux02** [comment]
the compilerproc pragma is for internal use only. So far this missing error message is not blocking development.
