### ISSUE TITLE
Nim extension for VS2019+

### ISSUE THREAD

**Issue by tbutton2005** [nim-lang/Nim#10526]
I CAN'T install the nim extension on VS2019 preview. https://github.com/Gravityzwell/NimStudio. Why? VSIX installer just does not want to install it. Help me!

**Comment by Yardanico** [comment]
That extension wasn't updated for almost 4 years, so I don't think you'll be able to use it at all

**Comment by alaviss** [comment]
@tbutton2005 I think you should ask in that project instead. And looks like the issue is already known https://github.com/Gravityzwell/NimStudio/issues/2.

**Comment by tbutton2005** [comment]
what if i install vs2015 and install this extension on it, and after all update it to vs2017 / 2019? maybe it will work

**Comment by mratsim** [comment]
Closing, if the extension is dead it might be a new case for https://github.com/nim-lang/needed-libraries
