### ISSUE TITLE
./koch docs error about sockets.nim

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#10534]
Running `./koch docs` on `devel` gives the following error:
```
...
bin/nim doc --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.19.9  --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.19.9/sockets.html --index:on lib/deprecated/pure/sockets.nim
Error: cannot open 'lib/deprecated/pure/sockets.nim'
```

**Comment by narimiran** [comment]
> `Error: cannot open 'lib/deprecated/pure/sockets.nim'`

`sockets.nim` was removed from that location 11 days ago.

What is the output of `nim -v`? Also, what does it say when you do `./koch --help`, when it was built?

**Comment by deech** [comment]
Yes, the issue was I hadn't done `nim c koch` in a while. It works now, thanks!

**Comment by timotheecour** [comment]
@deech just ran into it; it's a common problem; maybe `./koch` could give a warning if it's not fresh, using a simple/naive definition to cover most practical cases, eg:
`hash(koch.nim) != storedHash`
