### ISSUE TITLE
std/json fails to escape most non-printables, breaking generation and parsing

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#10541]
* The stdlib json library fails to escape all high bytes and apparently also vertical tab. This results in raw bytes slipping into the generated json, breaking the format and any attempt at parsing it.

* The generated unicode escape sequences "\uXXXX" are generated from ordinal values, but the spec requires them to be hexadecimal, resulting in the wrong character being written out. See: https://www.ecma-international.org/ecma-262/6.0/#sec-source-text

### Example

```nim
import json

var ary = newJArray()
for i in 0..255: ary.add(%($i & "=" & $i.chr))
let first = ary.pretty
let second = first.parseJson.pretty
echo first
echo second
doAssert(first == second)
```

### Current Output
```
  "10=\n",
  "11=
      ",
  "12=\f",
..
  "31=\u0031",
  "32= ",
..
  "127=",
  "128=�",
..
```

### Expected Output

```
  "10=\n",
  "11=\v",
  "12=\f",
..
  "31=\u001F",
  "32= ",
..
  "127=\u007F,
  "128=\u0080",
..
```

### Possible Solution

https://github.com/nim-lang/Nim/blob/master/lib/pure/json.nim#L607

This proc (and the accompanying parser) should probably be rewritten according to spec. 

### Additional Information

Discovered here: https://github.com/niv/neverwinter.nim/issues/4

Tested on 19.2 and latest #head.

**Comment by Araq** [comment]
Wasn't this fixed and backported a couple of weeks ago?

**Comment by narimiran** [comment]
> Wasn't this fixed and backported a couple of weeks ago?

Yes, here is the PR: https://github.com/nim-lang/Nim/pull/10437 — that solves one point of this issue ("The generated unicode escape sequences "\uXXXX" are generated from ordinal values, but the spec requires them to be hexadecimal")

The remaining points are:
* [ ] no vertical tabulator (`\v`) at position 11
* [ ] positions 128 .. 255
