### ISSUE TITLE
type(x) doesn't work for elements of a set

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10552]
```nim
proc fun[T](a: T) =
  echo "fun:", T, " ", a

proc fun2(a: int) =
  echo "fun2:", " ", type(a), " ", a

proc main()=
  var a = {10,12,15}
  for ai in a:
    echo type(ai) is int # true
    echo int is type(ai) # false; should be true
    echo type(ai), " ", ai
    var b = ai
    b.inc
    echo type(b), " ", b
    fun(b)
    fun2(b)
main()
```

prints:

```
true
false
range 0..65535(int) 10
range 0..65535(int) 11
fun:range 0..65535(int) 11
fun2: int 11
true
false
range 0..65535(int) 12
range 0..65535(int) 13
fun:range 0..65535(int) 13
fun2: int 13
true
false
range 0..65535(int) 15
range 0..65535(int) 16
fun:range 0..65535(int) 16
fun2: int 16

```

* all those `range 0..65535(int)` should be: `int`
* all those false should be true

**Comment by LemonBoy** [comment]
> all those range 0..65535(int) should be: int
> all those false should be true

That's questionable. According to the manual there's no such thing as a `set[int]` and the widest type you can accommodate is a `int16` and that's what the compiler does if you specify the set elements as integers.

In #10524 I made some modifications to how the range of accepted values is computed but maybe we should drop the range type altogether and use `int16`/`uint16`.

**Comment by Araq** [comment]
LemonBoy is right.

**Comment by timotheecour** [comment]
ya I feel like that's a gotcha; the code below reflects that in a clearer light: it works for all `T` except for `int` (and gives CT error for `uint` which is a different issue)

question: is there any practical use case for set with `int`? if not, let's deprecate?

```nim
## ok w these:
# type T = int16
# type T = uint16
# type T = uint16

## bad:
# type T = uint # Error: ordinal type expected
type T = int # bugs below

proc fun[V](a: V) =
  echo "fun:", V, " ", a

proc fun2(a: T) =
  echo "fun2:", " ", type(a), " ", a

proc main()=
  # var a = {10,12,15}
  # var a: set[int16] = {10,12,15}
  # var a: set[int16] = {10.int16,12,15}
  var a = {10.T,12,15}
  for ai in a:
    echo type(ai) is T # true
    echo T is type(ai) # false; should be true
    echo type(ai), " ", ai
    var b = ai
    b.inc
    echo type(b), " ", b
    fun(b)
    fun2(b)
main()
```

**Comment by LemonBoy** [comment]
> is there any practical use case for set with int

Because it's very practical. Consider the signature of `contains` for a `set[T]`, if `T` is a `int` (trough a `range` that makes sure it doesn't get too big) you can do `x in set` for pretty much every `x` since `int` matches its "subtypes".

**Comment by narimiran** [comment]
> According to the manual there's no such thing as a `set[int]` and the widest type you can accommodate is a `int16` and that's what the compiler does if you specify the set elements as integers.

> LemonBoy is right.

So there is no bug. Closing.
