### ISSUE TITLE
Latest 0.19.4 binary release is missing c2nim.exe and makelink.exe

### ISSUE THREAD

**Issue by kraptor** [nim-lang/Nim#10567]
Missing binaries in provided ZIP files: c2nim and makelink are missing.

### Example
Download any of:

- https://nim-lang.org/download/nim-0.19.4_x32.zip
- https://nim-lang.org/download/nim-0.19.4_x64.zip

The files c2nim.exe and makelink.exe are missing inside bin folder.

### Current Output
No exes for the 2 tools mentioned.

### Expected Output
Both exe files present in zip release file.

### Possible Solution
Seems the build process didn't include latest binaries for the tools.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4
```

Related issue: #10563

**Comment by narimiran** [comment]
To solve this, please download 0.19.5 from [our nightlies](https://github.com/nim-lang/nightlies/releases/tag/2019-02-08-version-0-19-f1a78b8), both `c2nim.exe` and `makelink.exe` which are missing in 0.19.4 are now inside of the `bin/` directory.

**Comment by kraptor** [comment]
Thank you for taking care of this, it is really appreciated :)
