### ISSUE TITLE
Undefined behaviour in the usage of incrSeqV3

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#10568]
Code like this:
```
proc xxx() =
  var a: seq[int]
  a.add 5

xxx()
```

generates the following C code (both on latest devel and on 0.18.1):

```

N_LIB_PRIVATE N_NIMCALL(void, xxx_yIubWxUz8g5WVxMecH6HtQ)(void) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	nimfr_("xxx", "a.nim");
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(4, "a.nim");
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) incrSeqV3(&(a)->Sup, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	T1_ = a->Sup.len++;
	a->data[T1_] = ((NI) 5);
	popFrame();
}
```

Note that we dereference a null pointer in `(a)->Sup`. This is an undefined behaviour and it's actually possible (but not trivial) to get Clang undefined behaviour sanitizer to report it. I fear this might produce miscompiled programs now or in the future (and it actually makes it harder to use Clang sanitizers).

Suggested fix would be to change `&(a)->Sup` to `(PGenericSeq*)a`. That would probably not violate aliasing rules (https://stackoverflow.com/a/50383349).

**Comment by Araq** [comment]
I don't know if we dereference, looks like an address computation to me. But your suggestion makes sense.
