### ISSUE TITLE
inline asm err

### ISSUE THREAD

**Issue by MissinA** [nim-lang/Nim#10570]
```
proc addInt(a,b:int):int {.asmNoStackFrame.} =
  asm """
    mov eax, `a`
    add eax, `b`
    ret
  """
echo addInt(3,4)
```
The above results run to 0.，I hope someone can help me. Thank you.

**Comment by Araq** [comment]
What C compiler used? OS? CPU arch? Calling convention?

**Comment by MissinA** [comment]
> C编译器使用了什么？OS？CPU拱门？召集会议？

msvc,win10,intel

**Comment by slangmgh** [comment]
https://forum.nim-lang.org/t/4630

**Comment by Araq** [comment]
Not a Nim bug.
