### ISSUE TITLE
raises pragma fails to report the missing unhandled exception

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#10579]
the raises pragma (in this case, from the yaml library) tells me I am missing an exception
"Error: can raise an unlisted exception:"
but then there is no more output, it doesn't tell me which exception.
I think it hints to an issue in the compiler.
This error prevents compilation, even though it seems nothing is wrong.

### Example
try to compile the latest yaml package:
https://github.com/flyx/NimYAML
Latest commit 053d5d1
```
nimble install yaml@#head
cd $(nimble path yaml)
nim c yaml.nim
```
### Current Output
```
yaml/serialization.nim(159, 15) template/generic instantiation from here
yaml/serialization.nim(146, 33) Error: can raise an unlisted exception: 
kobi7@sumak:~/.nimble/pkgs/yaml-#head$   (back to prompt)
```

### Expected Output

```
tell me which exception I am missing, or don't block compilation if all is ok.
```

### Additional Information

Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-05
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 2e880c726b0072bec93e897e5caef8f5bbe3d6b6
active boot switches: -d:release

It was working not long ago.

**Comment by timotheecour** [comment]
is that a duplicate?

**Comment by kobi2187** [comment]
awesome! thanks a lot for this prompt fix!
