### ISSUE TITLE
SetMaxPoolSize not heeded

### ISSUE THREAD

**Issue by brentp** [nim-lang/Nim#10584]
when using threadpool + spawn after setMaxPoolSize, it always uses all available CPUs. here is the code to reproduce. Even though it uses `setMaxPoolSize(1)` it will use all available CPUs:
```Nim
{.experimental.}
import threadpool
import math

proc work(k:int): float =
  for i in 0..<10000000:
    result += sin(i.float)
  result -= k.float

proc main() =
  setMaxPoolSize(1)

  var responses = newSeq[FlowVarBase](1000)

  for i in 0..<responses.len:
    responses[i] = spawn work(i)

  for i, fv in responses:
    blockUntil(fv)

main()
```

**Comment by LemonBoy** [comment]
Good news, this is easy to fix :)

- `setMaxPoolSize` (and `setMinPoolSize`) do not perform any check in order to maintain the `min < max` invariant.
- Nothing ever tears down the running worker threads, for some weird reason the `shutdown` flag in `slave` is reset and the pool size decreased but nothing at all is done about the thread. Adding a `return` makes the usage 100% on a single cpu only here (after setting `setMinPoolSize(1)`).

**Comment by brentp** [comment]
thanks for the fix!

**Comment by pb-cdunn** [comment]
@brentp, does `setMaxPoolSize()` still work for you with nim-0.20.2? I have to stop using it for now as it seems to cause `sync()` to hang.

* https://forum.nim-lang.org/t/5061

**Comment by brentp** [comment]
I stopped using it. I couldn't reliable get parallel stuff to work.

**Comment by pb-cdunn** [comment]
That's good to know. I guess we need to do our own thread orchestration until **threadpool** is fixed. See #11875 .

**Comment by pb-cdunn** [comment]
In my opinion, the ThreadPool should be a local variable. It should shut down all its threads when it goes out of scope. I guess if I have time, I'll write a simpler implementation that does just that.

**Comment by NatPRoach** [comment]
Wondering if anyone has `setMaxPoolSize()` working in nim-1.0.6. I'm running into a similar issue to the one raised above, with the threadpool always using the max available CPUs for the first iteration, even with `setMaxPoolSize()` and `setMinPoolSize()`both set to 1 like @LemonBoy suggested. After the first set of spawned threads it drops down to the correct number of threads. Has anyone else experienced this, and if so does anyone have a fix?

**Comment by brentp** [comment]
I also have this problem. The example I posted above is fixed but there are still problems with the pool.

**Comment by cdunn2001** [comment]
In such cases, prefer an instance threadpool instead of a global. I use this:

* https://github.com/yglukhov/threadpools
