### ISSUE TITLE
os.getCreationTime is incorrect/impossible on Posix systems

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1058]
The value that os.getCreationTime returns on posix systems is derived from stat.st_ctime, which is the time a files *attributes* were last changed.

On Linux and Mac OSX, stat.st_birthtimespec (or depending on age, just st_birthtime) is available.

Either this should be fixed, a warning should be put in the documentation concerning this, a deprecation notice be put in place, or both.

**Comment by dom96** [comment]
Let's fix it.

**Comment by dom96** [comment]
Are you sure ``st_birthtimespec`` is POSIX-compliant? I don't see it in the docs. http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html

Just looked it up: http://unix.stackexchange.com/a/91200. There is no kernel API in Linux to access it.

**Comment by dom96** [comment]
The documentation already contained this information in fact.

**Comment by sjuxax** [comment]
FYI, an extended statx call was merged in Linux 4.11, including birth time. See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a528d35e8bfcc521d7cb70aaf03e1bd296c8493f .
