### ISSUE TITLE
Enable experimental feature with command line argument has no effect.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#10606]
The tried the experimental feature with nim compiler command argument, but it has no effect.

```nim
#{.experimental: "codeReordering".}

proc p1() =
   echo "hello"
   p2()

proc p2() =
   echo "hello 2"

p1()

```

The code is fine with the pragma enabled. But when I comment out the pragma line, and compile with the following command:
```nim
> nim.exe c --experimental:codeReordering t9
t9.nim(5, 4) Error: undeclared identifier: 'p2'
```

It cannot compile.

**Comment by Araq** [comment]
Yeah, this is currently unsupported. Can't be hard to fix though.
