### ISSUE TITLE
`koch testinstall` fails

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#10623]
`koch testinstall` (on osx and linux) has been failing since 2019/02/08 nightlies build. See https://travis-ci.org/nim-lang/nightlies/builds

### Error

[travis error log][1]

```
/private/tmp/nim-0.19.9/testament/tester cat megatest

joinable specs: 468

tester.nim(654)          tester

tester.nim(619)          main

categories.nim(719)      processCategory

categories.nim(634)      runJoinedTest

tester.nim(95)           execCmdEx2

osproc.nim(808)          startProcess

osproc.nim(886)          startProcessAuxSpawn

oserr.nim(85)            raiseOSError

Error: unhandled exception: No such file or directory [OSError]

tests fai
```

[1]: https://api.travis-ci.org/v3/job/490388066/log.txt

**Comment by kaushalmodi** [comment]
- Failure detected commit: 55fe7c114ed04cb18a8c33c0039ae66d6125c24f
- Commit when it last passed: 4c3f8412122f20bac5a8812732b8a5762d0006d6
- Range of commits between those two: https://github.com/nim-lang/Nim/compare/4c3f8412122f20bac5a8812732b8a5762d0006d6...55fe7c114ed04cb18a8c33c0039ae66d6125c24f

**Comment by narimiran** [comment]
I've tried to reproduce this locally but I'm unable to — my `./testament/tester cat megatest` passes.

By looking at the changes, it might have to do with this commit: https://github.com/nim-lang/Nim/commit/c751c914fc1306b18209175a8c223cf39b90f0a0

**Comment by narimiran** [comment]
Here is a workaround: https://github.com/nim-lang/Nim/commit/9f986780081bedd43ff94387b6dda2a59e799d04

**Comment by kaushalmodi** [comment]
I've restarted the nightlies build ( [Build # 167](https://travis-ci.org/nim-lang/nightlies/builds/491154231) )  .. let's see how it goes.

**Comment by kaushalmodi** [comment]
Looks like that fix worked: https://travis-ci.org/nim-lang/nightlies/jobs/491154232

We can close this issue once all the sub-jobs in nightlies build 167 pass.

**Comment by kaushalmodi** [comment]
Closing this as the issue is fixed.

Proof: https://github.com/nim-lang/nightlies/releases/tag/2019-02-11-devel-242b6eb
