### ISSUE TITLE
megatest linking fails on local travis because it consumes too much memory

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10632]
As shown here: https://travis-ci.com/timotheecour/Nim/branches the last time megatest linking succeeded on my local appveyor was ~20 days ago around jan 20 2018

fix: see https://github.com/nim-lang/Nim/pull/10611

note: closing because of issue count limit but issue is valid

**Comment by Araq** [comment]
> note: closing because of issue count limit but issue is valid

The point is that you create PRs that fix the bugs that you created. The point is that you don't spam us with issues. Creating&Closing still counts as spam. Thanks.

**Comment by krux02** [comment]
This issue ignores the issue template. Please fill in the issue template properly when creating new issues.

**Comment by timotheecour** [comment]
> Please fill in the issue template properly when creating new issues.

done
