### ISSUE TITLE
`nim doc` uses wrong definition for DirSep on windows, causing all sorts of bugs

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10630]
`nim doc C:\pathto\main.nim` fails below

the root cause is `nim doc` has wrong definition of `DirSep` on windows (but also other symbols that are redefined for `nim doc`)

C:\pathto\main.nim:
```nim
import os
const a = currentSourcePath
const b = splitFile(a)
const b2 = b.dir / "test5.nim"
static: echo (b:b, DirSep: $DirSep) # will show b.dir as `""` and `DirSep` as `/` instead of `\` on windows

static: doAssert b.dir.len > 0 # this fails
const b3 = readFile b2 # this would also fail

# doesn't matter, just shows an example where nim doc could need b3
runnableExamples:
  # do something with b3 for example
  discard
```

**Comment by citycide** [comment]
> note: closing because of issue count limit but issue is valid

What exactly is this referencing?

**Comment by Araq** [comment]
> What exactly is this referencing?

I told him he has an issue cap at 100, he has to fix bugs before he can open even more. ;-)

**Comment by Araq** [comment]
> note: closing because of issue count limit but issue is valid

The point is that you create PRs that fix the bugs that you created. The point is that you don't spam us with issues. Creating&Closing still counts as spam. Thanks.

**Comment by genotrance** [comment]
This is a real issue.

Which style is acceptable to everyone? I prefer the first one since it collapses duplicates.

```nim
const
  CurDir* =
    when defined(macos): ':'
	else: '.'
    ## The constant character used by the operating system to refer to the
    ## current directory.
    ##
    ## For example: `'.'` for POSIX or `':'` for the classic Macintosh.

  DirSep* =
	when defined(macos): ':'
	elif doslikeFileSystem: '\\'
	elif defined(RISCOS): '.'
	else: '/'
    ## The character used by the operating system to separate pathname
    ## components, for example: `'/'` for POSIX, `':'` for the classic
    ## Macintosh, and `'\\'` on Windows.
```

Or:

```nim
proc selectDirSep(): char =
	when defined(macos): ':'
	elif doslikeFileSystem: '\\'
	elif defined(RISCOS): '.'
	else: '/'

const
  DirSep* = selectDirSep()
    ## The character used by the operating system to separate pathname
    ## components, for example: `'/'` for POSIX, `':'` for the classic
    ## Macintosh, and `'\\'` on Windows.
```

Or the original [PR](https://github.com/nim-lang/Nim/pull/10629) with `Impl`.

**Comment by genotrance** [comment]
cc @GULPF

**Comment by timotheecour** [comment]
> Which style is acceptable to everyone

the 1st one looks good; just make sure to fix not just `DirSep` but also the other symbols as I was doing it in https://github.com/nim-lang/Nim/pull/10629
