### ISSUE TITLE
compiling manual memory allocation to js leads to internal error

### ISSUE THREAD

**Issue by liwt31** [nim-lang/Nim#10648]
When compiling files with memory allocation functions in `system` module to JS target, the compilation fails with an internal error.

### Example

```nim
let k = createU(int, 10)
```
Compile command:
```bash
nim js test.nim
```

### Current Output
```
Hint: used config file '/home/wtli/.choosenim/toolchains/nim-0.19.4/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
../.choosenim/toolchains/nim-0.19.4/lib/system.nim(1836, 5) Error: internal error: genAsgn
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp js <file>
```

### Expected Output

Both followings seem to be more reasonable output:
* An error message showing manually memory allocation is not available with JS target
* Successful compilation. Memory allocation is dealt with by an indirect layer (not sure will work),

### Additional Information
```
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

**Comment by narimiran** [comment]
Compiles successfully on Nim 0.19.9

**Comment by GULPF** [comment]
@narimiran Still fails at runtime though... Is manual memory management even supposed to work with the js backend?
