### ISSUE TITLE
Missing lifting of type-bound operator for imported types

### ISSUE THREAD

**Issue by LemonBoy** [nim-lang/Nim#10654]
Compiling `foo2.nim` fails with the following error: `foo1.nim(5, 17) Error: internal error: '=' operator not found for type Foo`. After a cursory glance it seems that `liftTypeBoundOps` is not called here.

### foo1.nim

```nim
type
  Foo* = object
    discard

iterator items*(x: Foo): int =
  yield 42

proc `=destroy`*(x: var Foo) =
  echo "=destroy"
```

### foo2.nim

```nim
import ./foo1

type
  Bar = object
    x: Foo

proc newBar(): Bar =
  discard

proc foo(x: Bar) =
  for _ in x.x: discard

let m = newBar()
m.foo
```

**Comment by cooldome** [comment]
Fixed in latest Nim
