### ISSUE TITLE
testament/tester runs test out of order on linux (osx works)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10655]
example of a linux log: https://travis-ci.org/nim-lang/Nim/jobs/492356899
```
progress[all]: i: 0 / 111 cat: gc
progress[all]: i: 1 / 111 cat: effects
progress[all]: i: 2 / 111 cat: exprs
...
```

example of a OSX log: https://travis-ci.org/nim-lang/Nim/jobs/492356900
```
progress[all]: i: 0 / 111 cat: actiontable
progress[all]: i: 1 / 111 cat: alias
progress[all]: i: 2 / 111 cat: ambsym
...
```

**Comment by Araq** [comment]
> note: closing because of issue count limit but issue is valid

The point is that you create PRs that fix the bugs that you created. The point is that you don't spam us with issues. Creating&Closing still counts as spam. Thanks.
