### ISSUE TITLE
public proc may use non public argument/return types

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#10666]
When a procedure is marked as exported to be used in another module, all the types that are used for arguments should be usable in the other module as well. But Nim doesn't check that.

### Example
```nim
type
  Person = object
    name: string
    age: int

# This should at least give a warning as the argument type ``Person``
# cannot be used from the other module
proc setPerson*(arg: Person) =
  discard

# This should be rejected for the same reason.
proc getPerson*(): Person
  discard

# it is legal though to write the following in the other module

let tmp = getPerson()
setPerson(tmp)

# but this would be illegal, because ``Person`` is not exported:

let tmp: Person = getPerson()
setPerson()
```

### Possible Solution

In the semantic checking phase, when a function is marked as exported, the sem checker should enshure that the types that are used for arguments and return values are, when they are from the same module, also marked as exported.  

It doesn't need to be an error, I guess a warning is enough, as an error could make a lot of code not compile anymore that currently compiles.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-11
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 6cd3fff093b94aac5378792b169889b7f7959add
active boot switches: -d:release
```

**Comment by Araq** [comment]
"Voldemort" types are not a bug and a single ``runnableExample`` detects this problem as these are put into their own module.
