### ISSUE TITLE
Object with `=sink` will get wiped if set to self

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#10689]
### Example
```nim
type
  O = object
    v: int

proc `=sink`(d: var O, s: O) =
  d.v = s.v

var o = O(v: 10)
o = o
echo o
```

### Current Output
```
(v: 0)
```

### Expected Output
```
(v: 10)
```

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-14
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3520253a09cb8f32df834e619c7435092a370e9d
active boot switches: -d:release -d:useLinenoise
```

**Comment by cooldome** [comment]
I don't think it is an issue. The user code for `=`, `=sink` is responsible for checking for self assignments. Hence, it is a user code problem.

**Comment by alaviss** [comment]
I'm not sure why would I need to do that. In this code, the `int` inside the object is not anything special. The problem lies in the generated code:

```c
		eqsink__rLf2zcbwM6pKpSg9bDAkgXQ((&o_yKq9cI3rY7hoilaNIN8cN0w), o_yKq9cI3rY7hoilaNIN8cN0w);
		nimln_(10, "t2.nim");
		chckNil((void*)(&o_yKq9cI3rY7hoilaNIN8cN0w));
		nimZeroMem((void*)(&o_yKq9cI3rY7hoilaNIN8cN0w), sizeof(tyObject_O_anMkJITEbeI8SCSaxZg05w));
```

The compiler unconditionally insert a `zeroMem` here, so even if you check for self assignments, the object still get wiped.
