### ISSUE TITLE
nim doc ignores doc comment

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#10687]
`nim doc` doesn't find the doc comment for this proc:

```nim
proc foo*(x: int8): int =
  ## Doc comment
  x
```

It appears to be caused by a combination of the implicit int8->int conversion and the implicit return value, as changing either of these makes the issue disappear.

This causes some doc comments to disappear in the stdlib docs, here for example: https://nim-lang.github.io/Nim/times.html#nanoseconds%2CDuration

**Comment by narimiran** [comment]
Maybe it is related, so I'm posting it here:

From `options.nim`:
```nim
type
  Option*[T] = object
    ## An optional type that stores its value and state separately in a boolean.
    when T is SomePointer:
      val: T
    else:
      val: T
      has: bool
```

Doc produced:
```
Option[T] = object
  when T is SomePointer:
    val
  else:
      val
      has

  
```
(yes, with some empty lines at the bottom)

[See here](https://nim-lang.github.io/Nim/options.html#Option)

**Comment by nc-x** [comment]
@narimiran 
There is an issue open for that -> https://github.com/nim-lang/Nim/issues/9899
