### ISSUE TITLE
Negative times.Duration intermediate state is weird.

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#10683]
```nim
import times
var a1 = initDuration(seconds = 1, nanoseconds = 1)
var a2 = initDuration(seconds = 2, nanoseconds = 2)
var a3 = a1 - a2
echo a3.seconds
echo a3.nanoseconds
echo $a3
```
This small sample produces output:

```
-2
999999999
-1 second and -1 nanosecond
```

Looks like `.seconds` and `.nanoseconds` could not be used before some normalization, because it has some intermediate result, which `$` properly understands.

From my point of view negative `Duration` is nonsense. Exception must be generated or `DurationZero` must be returned.

**Comment by GULPF** [comment]
The nanosecond field is intentionally always positive. `times.Duration` is based on the [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) class from Java, which has the same behavior:
```java
import java.time.*;
import java.time.format.*;

class Main {
  public static void main(String[] args) {
    Duration a1 = Duration.ofSeconds(1, 1);
    Duration a2 = Duration.ofSeconds(2, 2);
    Duration a3 = a1.minus(a2);
    System.out.println(a3.getSeconds()); // -2
    System.out.println(a3.getNano());    // 999999999
  }
}
```

I doubt this is documented properly however.

**Comment by cheatfate** [comment]
Sorry this is not about documentation, its about `negative` nature of `Duration`. And i think question `is Distance can be negative` equal to question `is length can be negative`,

**Comment by GULPF** [comment]
> Sorry this is not about documentation, its about `negative` nature of `Duration`. And i think question `is Distance can be negative` equal to question `is length can be negative`,

`Duration` represents the time between two points in time. Naturally this can be negative, since "two days ago" is not the same thing as "two days into the future".

All the time handling libraries I know of that has a `Duration` type supports negative durations, so it's not some obscure design (C#, Java, D, NodaTime).

**Comment by cheatfate** [comment]
Sorry but comparison with other programming languages didn't convince me.

Duration is something you need to wait to get in time, so how much time i need to wait if the Duration is negative?

**Comment by GULPF** [comment]
> Duration is something you need to wait to get in time

That's not what `times.Duration` represents.

I don't understand what the advantage of removing support for negative durations would be. If you wish to disallow it in certain contexts, just add a `assert dur >= DurationZero`.

**Comment by cheatfate** [comment]
Currently in `times.nim` present two almost equal in behavior types `Duration` and `TimeInterval`. And i agree that `TimeInterval` can be negative, just because it represents exactly what you said `time between two points of time`. But `Duration` can (and i think should) have different behavior.

**Comment by FedericoCeratto** [comment]
This behavior is misleading. It's common to compare 2 events in time by subtracting them to obtain a delta and then compare the delta to a threshold. The times library makes it difficult to compare Time, Duration, Timeinterval in this use-case.

**Comment by GULPF** [comment]
@FedericoCeratto If you don't know the order of the events you can do `abs(event1 - event2) < threshold`. `TimeInterval` is a different story, but you're not supposed to compare two `TimeInterval`.

This issue can be closed imo, `seconds` and `nanoseconds` are deprecated so the normalization used by `Duration` is now just an implementation detail.
