### ISSUE TITLE
uint inplace add in if branch is omitted when compiled to JS

### ISSUE THREAD

**Issue by liwt31** [nim-lang/Nim#10697]
If an `if` branch contains one and only one inplace-add statement of an unsigned integer, the content of the branch is omitted when compiled to JS.

### Example

```nim
proc test =
  var val = uint16(0)
  var i = 0
  if i < 2:
    val += uint16(1)
  echo int(val)

test()
```

### Current Output
For c target, the output is correct, which is `1`. For JS target, the output is `0`. The compiled JS reads:
```
function test_25003() {
	var F={procname:"test.test",prev:framePtr,filename:"test.nim",line:0};
	framePtr = F;
		F.line = 2;
		var val_25005 = 0;
		F.line = 3;
		var i_25007 = 0;
		if ((i_25007 < 2)) {
		F.line = 5;
		}
		
		F.line = 6;
		rawEcho(cstrToNimstr((((val_25005)|0))+""));
	framePtr = F.prev;
}
```

### Additional Information

```
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

A workaround is to use things like `x = x + 1`

**Comment by alaviss** [comment]
With https://github.com/nim-lang/Nim/commit/257965e105c219f2504a2d1d0952fc43efb9598c merged I believe this issue should be closed.
