### ISSUE TITLE
DCE regression: modules can't be eliminated

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10703]
The following commit made module elimination not possible: https://github.com/nim-lang/Nim/commit/28cb81ea87aee0a6a2a9d8445abba2a580bb158e

The dependency on the `nimFrame` is raised without checking if it is actually used plus `cfsForwardTypes` section is always not empty, making module elimination not possible.

The commit claims that some DLL issue was fixed in the tests, there is no test changes.

@Araq: do you remember what was the problem? Should be a better way to fix it.

**Comment by Araq** [comment]
Well it was DLLs in C++ mode and my patch is really nice IMO. We can use a different section for it though, but I don't know how the module elimination works.

**Comment by cooldome** [comment]
The module elimination works in a simple way. `genModule` is generating final module's rope also checks if sections are empty using dead simple: `sectionrope.len > 0`. If all sections starting from `cfsForwardTypes` are empty then `nil` is returned and output file is not generated.

Using a different section before  `cfsForwardTypes`  will help, but I don't understand one thing.
`nimfr_` is now defined both in nimbase.h and each file output file. What is the purpose? Should be remove at least one of these definitions.

**Comment by Araq** [comment]
So that older versions can still bootstrap, they require it to be in ``nimbase.h``.
