### ISSUE TITLE
overloading on return value

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1070]
The compiler accepts when there are functions overloaded by return value only

```
proc foo() : int = 1                       # this compiles
proc foo() : string = "aaa"
```

However trying to use them fails even when there's no ambiguity

```
proc foo() : int = 1
proc foo() : string = "aaa"
var x : int = foo()       # fails to compile in 0.9.3
```

Perhaps clear cases could be allowed. It may be useful e.g. when returing more precise time value.:

```
proc now() : int = ...
proc now() : timeval = ...
proc now() : timeval_with_nanosecond_precision = ...

var precision_in_seconds : int = now()
```

**Comment by ozra** [comment]
Return type overloading is something I really miss in C++ and other langs, would be really handy in specific situations!

**Comment by mdeck** [comment]
Want

**Comment by hcorion** [comment]
Just ran into this issue, would appreciate it.

**Comment by dom96** [comment]
While this would be nice, it's not on our roadmap for v1.

**Comment by zah** [comment]
The classic use case of return-type overloading is not `let x: Foo = bar()`, but rather `foo(overloadedByReturnType())` or `object.field = overloadedByReturnType()`. 

Overloading by return type is mostly useful for generic algorithms that can populate any kind of Dictionary or Container for example. Any alternative allowing similar flexibility (by encoding the desired type in an extra parameter) would be just as verbose as the example you wanted to avoid.

**Comment by Araq** [comment]
> Any alternative allowing similar flexibility (by encoding the desired type in an extra parameter) would be just as verbose as the example you wanted to avoid.

Maybe, maybe not. Depends on the concrete alternative. And even if the alternative is "just as verbose" it might have the advantage of not being yet another language feature, we need to document, test, support and all of our users need to know about and understand.
