### ISSUE TITLE
genSymed symbol is not "usable"

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#10706]
```nim
import macros

macro genProc(): untyped =
  result = newNimNode(nnkStmtList)

  let prc = newProc()
  prc.name = genSym(nskProc, "hello")
  prc.body = quote do:
    echo "hi"

  result.add(prc)

  # The following line demonstrates that the sym can be used from the macro that created it
  result.add newCall(prc.name)

  echo repr result

genProc()
hello() # Error: undeclared identifier: 'hello'
```
**Expected result**: This should compile and print "hi" twice
**Actual result**: `test.nim(19, 1) Error: undeclared identifier: 'hello'`

**Comment by cheatfate** [comment]
According to `genSym()` documentation:
```
generates a fresh symbol that is guaranteed to be unique. The symbol needs to occur in a declaration context.
```
So this is not a bug, because generated name will not be ```hello```, but something like ```hello1234```. So everything is work like documented and expected.

**Comment by yglukhov** [comment]
Yeah, true.

**Comment by krux02** [comment]
just use ``ident"hello"`` instead of genSym and it should work just fine.
