### ISSUE TITLE
Argument List Too Long Error

### ISSUE THREAD

**Issue by zaferarican** [nim-lang/Nim#10701]
**Argument List Too Long Error when compiling csources using build.sh in a x386 linux system**

I tried to build nim#devel build on a linux shell emulator on iOS . (See [iSH](https://github.com/tbodt/ish). It is based on Alpine Linux and it has gcc installed. It helps me prototype Nim code on my iPad Pro)

When I run build.sh in csources, it gives
 `gcc: Argument List Too Long ` error. 
I think it is due to $LINKER -o followed by many .o files in build.sh script.

I found a workaround by dividing the .o files into small chunks and using 
```shell
ld -r <a small number of .o files> -o parts/p1.o 
``` 
and so on.  
and
```shell
gcc parts/p1.o parts/p2.o parts/p3.o -o ../bin/nim
```

It builds nim then. 
And it also builds koch. 

But afterwards 
./koch boot
./koch tools
Or 
./koch nimble 
Fails. It crashes.

I believe the problem with koch can be also related to the same problem causing `Argument List Too Long` error

* Changing the very long $LINKER -o line into small chunks using `ld -r` can overcome the argument list too long error. 
* Some modifications on nim compiler to handle very long list of generated .o files can prevent the crash too.

**Comment by Araq** [comment]
I think you can increase the command line length limit on Linux.

**Comment by zaferarican** [comment]
You can get the max argument list size with 
```shell
getconf ARG_MAX
```
But there is not a direct way to change the limit without recompiling the kernel with changed limit, I guess. 

Getconf gives
2097152 in a 64 bit system with 2GB of ram 

While it only gives
131072  In iSH
I think this is the problem. 

It is not a big issue but when solved, it can enable nim in machines with limited resources

ld -r (or dividing .o files into small chunks) seems to be a solution

**Comment by Araq** [comment]
We now generate "response files" for long linking commands so this issue should be a thing of the past.
