### ISSUE TITLE
Weird codegen bug

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#10714]
```nim
import sdl2, sdl2/ttf

block:
  for _ in [1]:
    discard renderGlyphShaded(nil, uint16 1, color(0, 0, 0, 0), color(0, 0, 0, 0))
    defer: discard # comment either this line \
    clear nil # or this line \
    # to get a rid of the error
```

> CC: stdlib_system
> CC: sdltest
> Error: execution of an external compiler program 'gcc -c  -w  -I'/home/dawkot/.choosenim/toolchains/nim-#devel/lib' -I/home/dawkot/nim/faketerm -o /home/dawkot/.cache/nim/sdltest_d/sdltest.c.o /home/dawkot/.cache/nim/sdltest_d/sdltest.c' failed with exit code: 1
> 
> /home/dawkot/.cache/nim/sdltest_d/sdltest.c: In function ‘NimMainModule’:
> /home/dawkot/.cache/nim/sdltest_d/sdltest.c:303:14: error: ‘T13_’ undeclared (first use in this function)
>        (void)(T13_);
>               ^
> /home/dawkot/.cache/nim/sdltest_d/sdltest.c:303:14: note: each undeclared identifier is reported only once for each function it appears in

**Comment by ghost** [comment]
@narimiran seems to be okay now, can you confirm? It doesn't error for me on latest devel with GCC 9.2.0

**Comment by ghost** [comment]
@narimiran ping again, it works fine for me here

**Comment by ghost** [comment]
Checked again, works fine. Reopen if it's still an issue.

**Comment by timotheecour** [comment]
@Yardanico issues should be closed with a regression test

**Comment by ghost** [comment]
@timotheecour I'm not sure how to make a test for this issue since it relies on sdl2

**Comment by ghost** [comment]
I'll try to find the nim version it wasn't working in, but no promises :P

**Comment by timotheecour** [comment]
actually the correct place to add regression test would be in sdl2 nimble package, which can then be tested in CI via important_packages eg:
```
grep sdl testament/important_packages.nim
pkg2 "sdl1", "nim c -r src/sdl.nim"
pkg2 "sdl2_nim", "nim c -r sdl2/sdl.nim"
```
