### ISSUE TITLE
Cross-Compiling with -d:mingw fails to locate compiler under OSX

### ISSUE THREAD

**Issue by teras** [nim-lang/Nim#10717]
According to the documentation, a command like `nim c  -d:mingw test.nim` should invoke mingw. Unfortunately, it can't find the executable, even if I provide the command 
```
nim c --path:/usr/local/bin -d:mingw test.nim
```
Note: the compiler exists at `/usr/local/bin/x86_64-w64-mingw32-gcc` , not `/usr/bin/x86_64-w64-mingw32-gcc`

### Example

```nim
echo "Hello World!"
```

### Current Output
```
Hint: used config file '/usr/local/Cellar/nim/0.19.4/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
CC: test
CC: stdlib_system
Error: execution of an external compiler program '/usr/bin/x86_64-w64-mingw32-gcc -c  -w -mno-ms-bitfields  -I/usr/local/Cellar/nim/0.19.4/nim/lib -o /Users/teras/.cache/nim/test_d/test.c.o /Users/teras/.cache/nim/test_d/test.c' failed with exit code: 127

/bin/sh: /usr/bin/x86_64-w64-mingw32-gcc: No such file or directory

```

### Expected Output

To properly compile!

### Possible Solution

The compiler should be able to accept the path, and not hard code the path of the copiler?

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4 [MacOSX: amd64]
Compiled at 2019-02-07
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```

**Comment by Araq** [comment]
So fix your ``nim.cfg``, we cannot guess where you installed mingw.

https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L76

**Comment by teras** [comment]
Indeed, I can do that.
Do you accept pull requests, that target this specific issue under OSX?
SInce you are already mentioning "using brew", and this is not the default path of brew.

**Comment by Araq** [comment]
Ah ok, sorry, I didn't realize.

**Comment by teras** [comment]
Hello again.

Although hard chagening the path does work (hurray!), when I try to do it dunamically, doesn't seem to understand the change.

The change I am considering is like this:

```nim
  @if macosx:
    amd64.windows.gcc.path = "/usr/local/bin"
  @else:
    amd64.windows.gcc.path = "/usr/bin"
  @end
```

Am I missing something?

**Comment by Araq** [comment]
That's how I would have done it too, what's wrong?

**Comment by genotrance** [comment]
`@if macosx` probably fails since `os = windows` a few lines above. Do the OS check before changing it.

**Comment by inadarei** [comment]
What worked:

Editing `~/.choosenim/toolchains/nim-0.19.4/config/nim.cfg`

and changing following section:

```
@if unix and mingw:
  # Cross compile for Windows from Linux/OSX using MinGW
  os = windows

  i386.windows.gcc.path = "/usr/bin"
  i386.windows.gcc.exe = "i686-w64-mingw32-gcc"
  i386.windows.gcc.linkerexe = "i686-w64-mingw32-gcc"

  # amd64.windows.gcc.path = "/usr/bin"
  # amd64.windows.gcc.exe = "x86_64-w64-mingw32-gcc"
  # amd64.windows.gcc.linkerexe = "x86_64-w64-mingw32-gcc"

  amd64.windows.gcc.path = "/usr/local/Cellar/mingw-w64/6.0.0/bin"
  amd64.windows.gcc.exe = "x86_64-w64-mingw32-gcc"
  amd64.windows.gcc.linkerexe = "x86_64-w64-mingw32-gcc"
@end
```

Please note that the last three instructions replace the default commented-out instructions.

What didn't work and was very surprising:

1. Creating nim.cfg locally (alongside .nim source files)
2. putting this section in nim.cfg or putting entire nim.cfg that is in the default location locally

This is VERY surprising because compiler hint says local file is being processed:

```
Hint: used config file '<redacted-path-to>/projects/nim/nim-async/nim.cfg' [Conf]
```

and yet that file doesn't seem to override the default. VERY strange.

Thoughts?

**Comment by Araq** [comment]
The config order is important but later configs can overwrite previous configs so I don't know what is goindg on here either.

**Comment by teras** [comment]
If the config is changed to 
```nim
@if unix and mingw:
  # Cross compile for Windows from Linux/OSX using MinGW
  i386.windows.gcc.exe = "i686-w64-mingw32-gcc"
  i386.windows.gcc.linkerexe = "i686-w64-mingw32-gcc"

  amd64.windows.gcc.exe = "x86_64-w64-mingw32-gcc"
  amd64.windows.gcc.linkerexe = "x86_64-w64-mingw32-gcc"

  @if macosx:
    amd64.windows.gcc.path = "/usr/local/bin"
    i386.windows.gcc.path = "/usr/bin"
  @else:
    i386.windows.gcc.path = "/usr/local/bin"
    amd64.windows.gcc.path = "/usr/bin"
  @end

  os = windows
@end
```

then the system is able to locate the compiler.
But now it fails with this error message:
```
/usr/local/Cellar/mingw-w64/5.0.4_1/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: cannot find -ldl
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: '/usr/local/bin/x86_64-w64-mingw32-gcc   -o /Users/teras/Sources/test.exe  /Users/teras/.cache/nim/test_d/test.c.o /Users/teras/.cache/nim/test_d/stdlib_system.c.o    -ldl'
```

probably due to this part of the config ?
```nim
@if not bsd or haiku:
    # -fopenmp
    gcc.options.linker = "-ldl"
    gcc.cpp.options.linker = "-ldl"
    clang.options.linker = "-ldl"
    clang.cpp.options.linker = "-ldl"
    tcc.options.linker = "-ldl"
  @end
```

If I replace the content of the strings with empty strings, it works, but I can't just comment them out.
