### ISSUE TITLE
Compiler complains about side effects with global func

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#10712]
Test
```nim
var f: (func: int)
f = (func: int = 5)

func test: int = f()
echo test()
```
Output
```nim
Error: 'test' can have side effects
```
Expected
No side effects at all.
***
```nim
>nim -v
Nim Compiler Version 0.19.9 [Linux: i386]
Compiled at 2019-02-13
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3520253a09cb8f32df834e619c7435092a370e9d
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
I guess the issue is that `f` here is a `var`. Hence you may later write

```nim
f = (func: int = 6)
```

and then `test()` would return `6`. This violates referential transparency, and the compiler correctly states that `test` is not a `func`, but only a `proc`

**Comment by krux02** [comment]
I am not 100% sure about this error in particular. 
But the smelling part that I see is, that func ``test`` depends on the global state ``f``. A func should not rely on any state at all, only on it's arguments.

The error message: ``'test' can have side effects`` is not correct or at least misleading, I think ``'test' depends on global state`` would be better.

**Comment by andreaferretti** [comment]
In any case, since we agree that the compiler is correct, but only the reported error is misleading, I am tagging as such
