### ISSUE TITLE
HTTP response without Content-Length is not accessible

### ISSUE THREAD

**Issue by konradmb** [nim-lang/Nim#10726]
When HTTP/1.1 server responds with proper content, but without `Content-Length` header, the response is not accessible, i.e. an empty response is returned.

This response is formally wrong, but for example Curl or Firefox displays the text irregardless.

#### Server
```nim
import asynchttpserver, asyncdispatch, asyncnet

var server = newAsyncHttpServer()
proc cb(req: Request) {.async.} =
  var msg = "HTTP/1.1 " & $Http200 & "\c\L"
  msg.add "\c\L\c\L"
  msg.add("Here comes reply")
  await req.client.send(msg)
  req.client.close()

waitFor server.serve(Port(8080), cb)
```
#### Client

```nim
import httpclient

var client = newHttpClient()
echo client.getContent("http://localhost:8080")
```

### Current Client Output
```
 
```

### Expected Client Output

```
Here comes reply
```

### Possible Solution
I've traced it to this if statement:

https://github.com/nim-lang/Nim/blob/b6d96cafc8bcad1f3d32f2910b25cd11a93f7751/lib/pure/httpclient.nim#L995

Changing it to true, makes the reply available.

**Comment by dom96** [comment]
I suppose it makes sense to also add ``or "Content-Length" notin headers`` into that if statement. Can you make a PR and test it?

**Comment by xenogenesi** [comment]
Any progress? I'm doing a get on a router that doesn't set the content-length.

Note that the line https://github.com/nim-lang/Nim/blob/b6d96cafc8bcad1f3d32f2910b25cd11a93f7751/lib/pure/httpclient.nim#L995 is in the else of a condition that has already verified the content-length is not empty (line 995 is executed if the content-length is not set)

**Comment by dom96** [comment]
@xenogenesi maybe you could look into fixing this? It should be relatively trivial.

**Comment by xenogenesi** [comment]
@dom96 Considering your previous comment to add `or "Content-Length" notin headers` I downloaded `httpclient.nim` locally, renamed and commented line 995 (the result is the same because the condition is already and always true), it works, but is this the way to go? Remove the conditions?

**Comment by konradmb** [comment]
@dom96 @xenogenesi I've removed that if line altogether and haven't seen any wrong behaviour. At least when I've tested it on that server (it's a router too).
I've tried to make a PR for this, but I wanted to find something about other edge cases. Then I've forgot about this. :grinning:

**Comment by xenogenesi** [comment]
@konradmb @dom96 I tested `newHttpClient` with` .getContent () `and` newAsyncHttpClient` with `.get ()` without encountering problems.

@konradmb go ahead with the PR , I mention mine only to compare the changes.

https://github.com/xenogenesi/Nim/commit/c8427620e8f94728ecc37aff10989dfc74dd2dff

**Comment by dom96** [comment]
Gotta love it when we gotta make things work for servers that don't respect the spec.

If you do this please make sure to write a comment describing this in detail and add a link to this issue

**Comment by dom96** [comment]
Also, it might be worth checking how other HTTP clients handle this in Python, Node, Go, etc.

**Comment by xenogenesi** [comment]
I took a look at python's requests, go's net / http and node's http (all three work with the router I'm trying) but the implementations aren't really easy to follow.

From what I understand content-length may not be set if it is a "chunked" communication, but in this case "Transfer-Encode: chunked" should be set (we could check if this header is also missing instead of deleting the " if ").

Curl with the router I am using ends here: `Info: no chunk, no close, no size. It takes close to signal end`
https://github.com/curl/curl/blob/cdf7d13bcb144756af8d3ae2dc92d638a65e0e0f/lib/http.c#L3424

> On HTTP 1.1, when connection is not to get closed, but no Content-Length nor Transfer-Encoding chunked have been received, according to RFC2616 section 4.4 point 5, we assume that the server will close the connection to signal the end of the document.

Note that it explicitly verifies that it is HTTP / 1.1 while the current nim / httpclient code proceeds only if it is HTTP / 1.0

**Comment by Araq** [comment]
Please create a PR for this!

**Comment by xenogenesi** [comment]
I ended up using the patch below, so there shouldn't be too many unforeseen cases or differences with the old one

    -      if headers.getOrDefault"Connection" == "close" or httpVersion == "1.0":
    +      if headers.getOrDefault"Connection" == "close" or (httpVersion == "1.0" or httpVersion == "1.1"):
