### ISSUE TITLE
dotcall mismatch

### ISSUE THREAD

**Issue by fowlmouth** [nim-lang/Nim#1072]
```
/tmp/aporia/a27.nim(9, 8) Error: type mismatch: got (int, int)
but expected one of:
a27.()(l: string, r: string): string
```

``` nimrod
var x: int

proc foo (some:int):int = some
when true:
  proc `()` (l,r:string): string = nil

block:
  var foo = 42
  echo x.foo
```

works when no `()` is defined

**Comment by data-man** [comment]
Nim-devel now outputs
<pre><b>(9, 9) </b><font color="#DC322F">Error: </font>type mismatch: got &lt;int, int&gt;
but expected one of: 
proc `()`(l, r: string): string
  first type mismatch at position: 1
  required type: string
  but expression &apos;foo&apos; is of type: int
</pre>
