### ISSUE TITLE
Tuple unpacking of `for` vars fails inside generic proc

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#10727]
The following snippet doesn't compile.
When the generic parameter is removed it does compile.

### Example

```nim
func test[n](s: seq[(int, int)]) =
  for (a, b) in s:
    discard
```

### Current Output
```
test.nim(2, 7) Error: illformed AST: (a) =
```

### Expected Output

```
It should just compile.
```

### Additional Information
Tuple unpacking for `for` variables introduced in #10152 by @nc-x 
```
$ nim -v
Nim Compiler Version 0.19.9
```

**Comment by deech** [comment]
Looking at this it looks like the constructs inside a `proc` parameterized by a type take a [completely](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L1860) path vs. those without one. The former ends up [here](https://github.com/nim-lang/Nim/blob/devel/compiler/semgnrc.nim#L350) while the latter ends up [here](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L666). Is there a reason there's two different ways of doing almost the same thing?

**Comment by Araq** [comment]
The reason is that generics have two-phase symbol lookup rules and non-generics don't. Covered by the manual.
