### ISSUE TITLE
runnableExamples that are only compiled

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#10731]
runnableExamples are run by `nim doc`. Some code examples should not be run due to side effects or other reasons, but parsing and compiling the code is still beneficial to prevent code rot.

For example: httpclient fetching a remote URL; deleting files; and so on.

This can become quite dangerous when running `nim doc` on 3rd party libraries where the authors might have written examples without realizing they would be execute automatically!

**Comment by FedericoCeratto** [comment]
For example examples of procs in posix.nim that create and delete files and directiories, memoryLockAll, kill processes, reboot the host, set the clock time...
Also, some code examples are helpful when echoing strings or data structures and this cannot be done during `nim doc`.

**Comment by juancarlospaco** [comment]
```
runnableExamples:
  if off:
    echo "I am and example, but too lazy to Run"
```
:grey_question:

**Comment by alaviss** [comment]
```nim
runnableExamples:
  proc main() =
    echo "I'm not running"
```

^ that's also a way.

**Comment by FedericoCeratto** [comment]
Any "if false", "when false", "def main" line is confusing to people reading the examples (as they are unaware of the hack). Also `nim doc` still tries to execute the file without need.

**Comment by Araq** [comment]
Non-running runnable examples are confusing, you might as well use ``.. code-block:: nim`` for the example then.

**Comment by FedericoCeratto** [comment]
@Araq the code-block renders differently and (as you said before) leads to code rot. I guess `proc example()` could be the least confusing:
```nim
runnableExamples:
  proc example() =
    echo "I'm not running"
```

**Comment by timotheecour** [comment]
fixing this more generally in https://github.com/nim-lang/Nim/pull/14384, which allows passing an arbitrary cmd

**Comment by FedericoCeratto** [comment]
This sounds like a good use-case for the Effect system - if there was a way to ensure that examples are not doing I/O and other unwanted activities.
