### ISSUE TITLE
GlobalVar warning with {.global.} pragma?

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#10738]
It seems silly to issue the `GlobalVar` warning for specifically marked global variables:
```
falcon/sys.nim(15, 7) Hint: global variable declared here [GlobalVar]
    let start {.global.} = times.epochTime()
        ^
```

Also, I have a question: How does the `{.global.}` pragma interact with threads? Would each thread automatically get its own thread-local global?

**Comment by andreaferretti** [comment]
I think this is not silly, one may want to use the compiler to be informed about such usages. It looks silly only if you have just written this line, not if you get such warnings about an old and complex code base.

About the second question, no: there's [`{.threadvar.}`](https://nim-lang.org/docs/manual.html#threads-threadvar-pragma) for that. Global is just global (hence thread-unsafe)

**Comment by pb-cdunn** [comment]
Well, I wrote "silly" only because it's very, very easy to search for, while unmarked globals can be difficult to find.

> About the second question, no: there's [`{.threadvar.}`](https://nim-lang.org/docs/manual.html#threads-threadvar-pragma) for that. Global is just global (hence thread-unsafe)

That's good to know! But if it's thread-safe, again, there is not much reason to warn about it.

**Comment by andreaferretti** [comment]
I think you have misread thread-unsafe for thread-safe, or else I did not understand your last sentence

**Comment by pb-cdunn** [comment]
Yes, I misread that.

Hmmm. Can a variable be both proc-defined-global and threadvar? That might be what I wanted.

**Comment by alaviss** [comment]
According to the `{.threadvar.}` [documentation][0]:

> A variable can be marked with the `threadvar` pragma, which makes it a thread-local variable; Additionally, this implies all the effects of the `global` pragma.

[0]: http://nim-lang.github.io/Nim/manual#threads-threadvar-pragma

**Comment by Araq** [comment]
The real question here is why you use ``[GlobalVar]``. :-) I use it to detect thread/GC-safety issues and for that ``.global`` variables definitely apply too.

**Comment by andreaferretti** [comment]
I think what @pb-cdunn wants is `threadvar`. If they confirm, we can close the issue
