### ISSUE TITLE
Error in lexbase when using parseJson in static block

### ISSUE THREAD

**Issue by ryukoposting** [nim-lang/Nim#10733]
When attempting to use the JSON library in a static block, I'm getting a rather confusing error.

### Example

```nim
import json, macros
static:
  let data = readFile("test.json").parseJson()     # test.json exists, and is valid json
  echo data
```

### Current Output
```
/home/epg/.choosenim/toolchains/nim-0.19.4/lib/pure/lexbase.nim(156, 13) Error: VM is only allowed to 'cast' between integers of same size
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "/home/epg/.nimble/bin/nim" c --noNimblePath "-r" "--path:."  "/home/epg/projects/ec2/tests/test1.nim"
```

### Expected Output
Not completely sure... My gut feeling is that the code should be a valid Nim program, so that should spit out the data from the file at compile-time. If it's supposed to be an error, it's not very clear in meaning.

### Additional Information
```
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

**Comment by ryukoposting** [comment]
I also found that this works fine:
```nim
macro foo: untyped =
  let js = readFile("test.json")
```
but this throws the same error as before:
```nim
macro foo: untyped =
  let js = readFile("test.json").parseJson
```

I'm really hoping this can be fixed. A lot of really big web services (e.g. AWS) describe their API spec in a [gigantic json](https://github.com/aws/aws-sdk-go/blob/master/models/apis/ec2/2016-11-15/api-2.json), and I want to use macros with these giant JSON files to generate API bindings.

**Comment by Vindaar** [comment]
Parsing JSON at compile time isn't supported at the moment unfortunately. There's a PR for it https://github.com/nim-lang/Nim/pull/10637, but it's not exactly a nice solution.

The main issue boils down to streams not being supported at compile time. The errors you get are really bad though, indeed.

For your use case I think you'd find that performance would not be up to the task anyways (CT performance isn't that great). Parsing all that JSON and generating everything seems like something that does not have to be done on each compilation anyways, right?

**Comment by ryukoposting** [comment]
> Parsing all that JSON and generating everything seems like something that does not have to be done on each compilation anyways, right?

I guess that's reasonable- even if it did work, it would probably be slow to compile just because of the sheer size of the files I want to process. However, that's a sacrifice I'm willing to make. Slow compile times are fine if it means I don't have to hand-roll the entire AWS SDK, maintain it manually, and document it manually, all while using a language that prides itself on its powerful metaprogramming capabilities. It's not like compiling the entire AWS SDK is going to be fast either way.

There are official AWS SDKs that generate their code from these JSON files, but they do it through a program that just spits out Go/C++/etc code. This is kind of fragile, as there's no compiler performing static analysis on the generated code. Your only sane option is to compile the generated SDK to make sure it's correct. Using macros to directly generate the library from JSON would eliminate many potential points of error.

In other languages, it simply isn't possible to directly generate an AST from the JSON. Nim is special because it has that capability- or rather, it *could* have that capability if the JSON library was compile-time friendly. At absolute worst, having a macro-generated AWS SDK would turn some heads. I'll leave "at best" up to your imagination.

In fairness, I don't know everything that's going on under the hood in the Nim standard library. I don't know how feasible it would be to have a separate, stream-free implementation of the JSON library that only gets used at compile time. Either way, I think lack of access to basic parts of the standard library cripples the potential of macros.

**Comment by krux02** [comment]
I don't know about your use case, but does it really need to be a json spec? I mean if you write your config directly as a nim constant in a nim file, there is no need to parse it from json anymore.

If the json does not come from you, but an external source you can still go this route and provide a transformation tool that transforms json into nim code and then start from there. This would also be faster, because there won't be a json parser that runs on a bytecode interpreter.

**Comment by ryukoposting** [comment]
> I don't know about your use case, but does it really need to be a json spec?

Yes, the JSON comes straight from an AWS repository. Good example of one of those files is [here](https://github.com/aws/aws-sdk-go/blob/master/models/apis/ec2/2016-11-15/api-2.json)

> If the json does not come from you, but an external source you can still go this route and provide a transformation tool that transforms json into nim code and then start from there

I think a lot of time is likely to be made up by 1) not having to make (and debug) a Nim codegen tool, 2) not having two separate stages of compilation (one to build the code generator, then the other to build the code generator's output). Maybe it's still not a perfect break-even, we don't really know since it simply isn't possible with the current JSON library.

Even if it is still slower, I think it's still worth considering how having such a capability (dynamically generating an SDK from a markup language spec without a bunch of intermediate steps) would facilitate rapid expansion of the Nim ecosystem, while simultaneously expressing one of the language's biggest strengths.

**Comment by krux02** [comment]
fixed in https://github.com/nim-lang/Nim/pull/10746
