### ISSUE TITLE
better navigation

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#10744]
given the current docs:

what            | link
----------------|--------------------------------------
manual devel    | https://nim-lang.github.io/Nim/manual
manual master   | https://nim-lang.org/docs/manual.html
overview devel  | https://nim-lang.github.io/Nim
overview master | https://nim-lang.org/learn.html
tutorial devel  | https://nim-lang.github.io/Nim/tut1
tutorial master | https://nim-lang.org/docs/tut1.html

you should be able to access the "other two" from each page, but here is result:

from            | to              | result
----------------|-----------------|-------
manual devel    | overview devel  | no
manual devel    | tutorial devel  | no
manual master   | overview master | no
manual master   | tutorial master | no
overview devel  | manual devel    | yes
overview devel  | tutorial devel  | yes
overview master | manual master   | no
overview master | tutorial master | yes
tutorial devel  | manual devel    | yes
tutorial devel  | overview devel  | no
tutorial master | manual master   | no
tutorial master | overview master | no

a few takeaways:

1. neet more "up", "previous" and "next" links or similar
2. the "manual master" AKA https://nim-lang.org/docs/manual.html is not linked
from anywhere that i saw, i manually constructed the link - is that intended?

**Comment by timotheecour** [comment]
@ghost maybe you can take a stab at a PR, see config/nimdoc.cfg and kochdocs.nim for a starting point

**Comment by timotheecour** [comment]
more or less fixed by https://github.com/nim-lang/Nim/pull/18272, feel free to re-open or improve things further
