### ISSUE TITLE
[Regression] --app:lib --out:foo.so is creating `foo` instead of `foo.so`

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#10747]
The `--app:lib --out:foo.so` switches are not creating the specified .so file on a GNU/Linux system (RHEL 6.8).

I see this regression on nim built using the latest devel as of now: ca4b971bc81b2e751e0388d80896fde7079b1679.

### Example

```nim
# some_lib.nim
proc hello() {.exportc.} =
  echo "Hello from Nim!"
```

With the above Nim file, below should have created a `some_lib.so`. But it is creating just `some_lib`.

```
nim c --app:lib --out:some_lib.so some_lib.nim
```

### Current Output

`some_lib` binary file gets created.

### Expected Output

`some_lib.so` binary file should get created.

**Comment by kaushalmodi** [comment]
@zah Seems like this regression was expected based on this comment:

> After reviewing the code more carefully, I've noticed that the old logic
will be broken when the user overrides the '--out:f' compiler option.

in that hot-reloading commit https://github.com/nim-lang/Nim/commit/ca4b971bc81b2e751e0388d80896fde7079b1679 ?

That would be a serious breaking change for my Nim<->SystemVerilog flow.

**Comment by kaushalmodi** [comment]
- I confirm that the regression was caused in https://github.com/nim-lang/Nim/commit/ca4b971bc81b2e751e0388d80896fde7079b1679
- Reverting to prior commit https://github.com/nim-lang/Nim/commit/ba38c05eb62a1b6e0b36b92886c43bed2cabd90a on devel makes `--app:lib --out:foo.so` work once again.

**Comment by Araq** [comment]
Don't worry, @kaushalmodi, we'll fix it.
