### ISSUE TITLE
Random garbage printed when trying to echo a tuple's field inside a macro

### ISSUE THREAD

**Issue by pgkos** [nim-lang/Nim#10751]
When trying to print a static tuple's field inside a macro, a random garbage string is printed instead.

### Example

```nim
type Tuple = tuple
  a: string
  b: int

macro foo(t: static Tuple): untyped =
  echo t.a
  echo t.b

foo((a: "foo", b: 12345))
```
### Current Output
During compilation, random garbage is printed, e.g.
```
��
140366958929960
```
### Expected Output

```
foo
12345
```
### Additional Information
Objects are not affected.

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-27
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by nc-x** [comment]
Somehow, using `repr` prints the correct output.

**Comment by stefantalpalaru** [comment]
@krux02, why is that fix just in your branch and not in the main Nim repo?
