### ISSUE TITLE
Bug in setTerminate()

### ISSUE THREAD

**Issue by cdunn2001** [nim-lang/Nim#10765]
### Example
https://github.com/bio-nim/pbbam/blob/f5a659e9fbed4b675f4458734fdfc9fe8162b2ac/nim/foo.nim

### Current Output
https://forum.nim-lang.org/t/4686
```
Traceback (most recent call last)
foo.nim(55)              foo
foo.nim(49)              main
system.nim(4341)         :anonymous
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
```
queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS
```
### Expected Output
We should see the exception message, similar to the default g++ terminate-handler.

### Possible Solution
I have added prints into `lib/system.nim::setTerminate()` in order to find where the crash actually occurs. The problem is that `let ex = getCurrentException()` is `nil`, so writing `ex.name` or `ex.msg` fails.

It's `nil` because nothing called `setCurrentException`.

I might be able to call `setTerminate()` (which is just`std::set_terminate()`) to install my own exception-trapping handler, as shown [here](https://stackoverflow.com/questions/3774316/c-unhandled-exceptions):
```cpp
   void terminate_handler()
   {
       try { throw; }
       catch(const std::exception& e) { log(e.what()); }
       catch(...) {}
   }
```
But I think this is a real bug anyway. Minimally, the anon proc given to `setTerminate()` should at least test `nil == ex`.

Ideally, we want _both_ the C++ exception _and_ the Nim stack-trace. Maybe a good approach is for Nim's default terminate-handler to show the Nim stack-trace first, and then to call `__gnu_cxx::__verbose_terminate_handler` if the Nim exception is `nil` and the backend is  `cpp` and GNU.

Even fancier, the C++ stack-trace is [harder to obtain](https://www.gnu.org/software/libc/manual/html_node/Backtraces.html), but that could be helpful too. (Would you like a pull-request for that, at least with GNU g++?)

### Additional Information
* Your Nim version:
  * `0.19.4`
* Was it working in the previous Nim releases?
  * Probably not.
* A link to a related issue or discussion.
  * https://gcc.gnu.org/onlinedocs/libstdc++/manual/termination.html
  * https://stackoverflow.com/questions/3774316/c-unhandled-exceptions
  * https://github.com/llvm-mirror/libcxxabi/blob/master/src/cxa_exception.cpp (to see how LLVN works)
  * https://github.com/llvm-mirror/libcxxabi/blob/master/src/cxa_handlers.cpp
  * https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libstdc%2B%2B-v3/libsupc%2B%2B/vterminate.cc#L37

**Comment by cdunn2001** [comment]
Another idea is for `lib/system.nim` to record the current terminate_handler, and for the replacement to call the old one after showing the Nim stack-trace. (We still need nil-checks, of course.) That way, we can avoid calling the very specific `__gnu_cxx::__verbose_terminate_handler` directly; it was probably the old handler anyway, installed by default.

**Comment by alaviss** [comment]
Maybe we can use [`std::current_exception`][0] to interface with C++ exceptions directly in `getCurrentException()`? With tweaks to the codegen we might be able to natively handle C++ exceptions in Nim.

As of stacktrace, on Linux, if you're using glibc, you can compile Nim compiler with `-d:useNativeStacktrace` (which employs `execinfo.h`).

[0]: http://www.cplusplus.com/reference/exception/current_exception/

**Comment by cdunn2001** [comment]
On `std::current_exception`, yes, I think it's fair to require >= C++11.

On `-d:nativeStacktrace`, I'll try that next week, when I'm near a Linux machine. I'm curious how that might compare with GNU `backtrace()`.

**Comment by alaviss** [comment]
If you read the source, then `-d:nativeStacktrace` uses GNU `backtrace()` ;)

**Comment by cdunn2001** [comment]
> `-d:nativeStacktrace` uses GNU `backtrace()` ;)

Oh, I see now. That's interesting. But it's not related to C++ exceptions. When an exception is thrown, unless someone actually attaches a backtrace to the exception, the stacktrace is lost. But I can see how that would be helpful for crashes in C/C++ code.

**Comment by cdunn2001** [comment]
Back to handling untrapped exceptions ...

The idea is to test for `getCurrentException() == nil` in Nim's terminate-handler, and to call the previous terminate-handler (which we would record at program start-up) in that case.

So we have 2 choices:

* `std::get_terminate()` to record the previous handler and call it after ours
  * http://www.cplusplus.com/reference/exception/get_terminate
  * Needs `-std=c++11` or higher, `__cplusplus >= 201103L`
* `__gnu_cxx::__verbose_terminate_handler()`
  * https://gcc.gnu.org/onlinedocs/libstdc++/manual/termination.html
  * Needs `__GNUG__`

Both work fine for me on Linux, but I do not know how to check for either C++11 or GNU.

**Comment by pb-cdunn** [comment]
In `Nim/lib/system.nim`:

```nim
4328   proc getTerminate: proc() {.noconv.}
4329     {.importc: "std::get_terminate", header: "<exception>".} # C++11
4330   var oldTerminate = getTerminate()
4331   proc setTerminate(handler: proc() {.noconv.})
4332     {.importc: "std::set_terminate", header: "<exception>".}
4333   setTerminate proc() {.noconv.} =
4334     # Remove ourself as a handler, reinstalling the default handler.
4335     setTerminate(nil)
4336
4337     let ex = getCurrentException()
4338     if nil == ex:
4339       stderr.writeLine "getCurrentException() -> nil";  # need template for `genode`?
4342       #verboseTerminate()
4343       if nil != oldTerminate:
4344         stderr.writeLine "Calling previous terminate_handler..."
4345         oldTerminate()
4346     let trace = ex.getStackTrace()
...
```
```
getCurrentException() -> nil
Calling previous terminate_handler...
terminate called after throwing an instance of 'std::runtime_error'
  what():  BamFile: could not open: foo
Traceback (most recent call last)
foo.nim(55)              foo
foo.nim(49)              main
system.nim(4345)         :anonymous
SIGABRT: Abnormal termination.
```
That's what I want! Both the C++ exception message _and_ the Nim stacktrace. (I don't actually know where the Nim stackrace is printed, but it is.)

**Comment by cooldome** [comment]
I will have computer next to for next 4 days to write full answer. getCurrentExeception works only for Nim exception. Use the following
```
try:
... 
except Exception as ex:
... 
except StdCppImportedException as ex:
...

```
Importcpp the std::exception for the last line

**Comment by pb-cdunn** [comment]
d70dd6f3cb043e3110e994f32cedc4fa143b24ce

This is a Nim standard library bug. I've submitted a sample PR, but if someone would tell me roughly what solution would be acceptable, I'd be happy to amend it myself.

**Comment by pb-cdunn** [comment]
@cooldome , I understand what you're saying: I can trap exceptions in Nim. That's pretty cool:
```nim
type
  StdCppImportedException* {.importc: "std::exception", header: "<exception>".} = object
proc what*(this: StdCppImportedException): cstring {.importcpp: "#.what()".}

try:
  main()
except Exception as ex:
  echo "trapped Nim exception"
  echo repr(ex) # THIS CRASHES -- another bug
except StdCppImportedException as ex:
  echo "caught C++ exception:", ex.what()
except:
  echo "trapped unknown exception"
  echo "msg:", getCurrentExceptionMsg()
```
(Note: I found a different Nim crash when printing `repr(ex)`.)

But I'm saying there is a seg-fault in the Nim standard library when we do _not_ trap all exceptions. See pr #10812 for possible fixes.

**Comment by cdunn2001** [comment]
Still not fixed. Please re-open so I don't have to file a new ticket.

I am on the top of `devel` now.
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Again, Nim crashes when a C++ exception is not trapped. I will *again* look into the exact line of code causing this ...

**Comment by cdunn2001** [comment]
Verified. Thanks.
