### ISSUE TITLE
Shipped dependency sqlite (library a bit outdated)

### ISSUE THREAD

**Issue by mikra01** [nim-lang/Nim#10767]
It is nice that (especially for beginners) some dependencies are downloadable from the project-page. Unfortunately (at least) the sqlite3 libraries (32 and 64bit)  are outdated ( at least windows platform; I didn't checked other platforms ). It would be great to update the native provided sqlite dependency ( https://nim-lang.org/download/dlls.zip ) to (at least) version 3.26.0. Some possible security flaws are fixed there.

**Comment by genotrance** [comment]
This might also mean updating the sqlite wrapper.

https://github.com/nim-lang/Nim/blob/master/lib/wrappers/sqlite3.nim

Should be quick with nimterop but never know.

**Comment by mikra01** [comment]
no need to update the wrapper. it run's with 3.27.2 still fine.

**Comment by genotrance** [comment]
This will also need to be updated in windeps.zip which is used by nightlies and soon choosenim.

**Comment by GULPF** [comment]
It's probably a good idea to update the wrapper anyway, it lacks some procs.

**Comment by genotrance** [comment]
I've attached updated zip files with v3.31.1 of sqlite. Please post them to the website.

[dlls.zip](https://github.com/nim-lang/Nim/files/4228766/dlls.zip)
[windeps.zip](https://github.com/nim-lang/Nim/files/4228768/windeps.zip)

**Comment by genotrance** [comment]
Can someone post these updated zips to the website?

@Araq @narimiran

**Comment by genotrance** [comment]
Bump.

**Comment by genotrance** [comment]
Bump or perhaps give me access to the website :D

**Comment by Araq** [comment]
Fixed.
