### ISSUE TITLE
Should we add isNumeric(), isInt() or isFloat() to strutils?

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#10761]
### Summary
In strutils we have ``isDigit()``, which will be deprecated in the next release.
https://nim-lang.github.io/Nim/strutils.html#isDigit%2Cstring
I couldn't find a proc to check whether a string is an integer (including negative sign) or a floating point number (including decimal point).
I use this in several projects and think it would be handy for many users.
Should we add such proc(s) to the stdlib?
Or do you think it is not worth to have it?

### Additional Information

For clear semantics, I think ``isInt()`` and ``isFloat()`` would be better than ``isNumeric()``.

Implementation can be based on parseInt() or on isDigit() (check of each character).
Example:
```nim
proc isInt*(s: string): bool =
  try:
    discard s.parseInt()
    result = true
  except:
    discard
```

**Comment by krux02** [comment]
Handy? maybe. Recommended? not at all. 

Please don't take it personal, but read the theory on how to write a lexer and parser properly. There are lot of examples in the standard library, not just json.  ``isInt``, ``isFloat``, etc is not what you need.

**Comment by awr1** [comment]
WRT to this:
```nim
  try:
    discard s.parseInt()
    result = true
  except:
    discard
```
If you did implement such a set of procedures, this is not how I would do it. Exceptions are for handling errors, not arbitrary flow control. 

I agree with @krux02. There are modules in the standard library like `strscans` that probably do what you want better.

**Comment by trustable-code** [comment]
No consensus to add those procs. Closing.
