### ISSUE TITLE
Wrong size for union in object

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#10762]
Consider following code:

### Example

```nim
type
  UNION = object {.union.}
    dwReserved1*: clong
    dwReserved2*: clong

  OBJECT = object
    u*: UNION

echo sizeof(OBJECT)
```

### Current Output
```
8
```

### Expected Output

```
4
```

I found this problem in Nim Compiler Version 0.19.9 [Windows: amd64]
The result of 0.19.0 is correct.

**Comment by krux02** [comment]
certainly related: https://github.com/nim-lang/Nim/issues/7665
