### ISSUE TITLE
Nim documentation's searchbox style is strange on Firefox and dark desktop themes

### ISSUE THREAD

**Issue by liquid600pgm** [nim-lang/Nim#10777]
I've seen this problem occur on many different websites, and it just looks out of place.

### Examples

[In the manual](https://nim-lang.github.io/Nim/manual.html)
![image](https://user-images.githubusercontent.com/16415678/53699166-c1d0c300-3de5-11e9-881e-e203db5abb38.png)

[In any module](https://nim-lang.github.io/Nim/system.html)
![image](https://user-images.githubusercontent.com/16415678/53699174-c85f3a80-3de5-11e9-9b7b-c5dd22c8cd0e.png)

This problem only occurs on Firefox with dark desktop environment themes, as the browser renders controls like text boxes, buttons, combo boxes by emulating the system style. This isn't as much of a problem on vanilla Windows, but it's very visible on Linux with dark themes.

The theme I'm using is `Arc-Dark` for GNOME – the issue disappears with `Arc` and `Arc-Darker`, as their controls are white.

### Possible Solution
This can simply be fixed by adding an explicit style to textboxes in the docs' default stylesheet.

**Comment by trustable-code** [comment]
Usually I have such problems, because use a dark GTK theme.
What exactly is wrong with the input box?
For me it has white text on black background, which is fine.

**Comment by liquid600pgm** [comment]
@trustable-code The text in the box is readable (light on dark background), but it just looks out of place with the bright look of the docs.

**Comment by dom96** [comment]
Is this really something we should be fixing?

**Comment by liquid600pgm** [comment]
It's not a major issue, but it would be nice if it were fixed. I can even take care of that, it's a pretty simple fix.

**Comment by narimiran** [comment]
["Today is the 18th anniversary of that bug where various UI elements are unreadable in Firefox if you use a dark GTK+ theme"](https://old.reddit.com/r/linux/comments/avmvqd/today_is_the_18th_anniversary_of_that_bug_where/)

**Comment by Clyybber** [comment]
Fixed in #11632
