### ISSUE TITLE
hashes:hash returns different values on Windows/Linux

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#10771]
Detected in nightlies build for runnableExamples:

https://travis-ci.org/nim-lang/nightlies/builds/500677963

```nim
  runnableExamples:
    doAssert hash("abracadabra") == -5600162842546114722
    doAssert hash("Abracadabra") == 2068684413884279454
```

Value is correct on my Linux x64 machine like on Travis but on Windows, it returns 1766020087. Not sure what value is returned on Linux x32 but that fails on Travis.

Commit that broke this:

https://github.com/nim-lang/Nim/pull/10752/files#diff-466aee2707291e60fe359bda6b675b86R146

cc: @narimiran

**Comment by narimiran** [comment]
Thanks for bringing it to my attention, will change it.

Btw, how come this passes both Travis and Appveyor here and fails in nightlies?

**Comment by genotrance** [comment]
I don't think the CI runs `koch docs` like nightlies does. Only `nim doc` tests snippets and runnable examples.
