### ISSUE TITLE
async call now treated as non-gc safed call?

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#10795]
waitFor async call now treated as non-gc safed call in the latest devel branch, is it bug or feature?

### Example

```nim
import asyncdispatch
import threadpool

proc f1() =
   waitFor sleepAsync(100)
   echo "hello"

spawn f1()

```

### Current Output
```
t9.nim(11, 9) Error: 'spawn' takes a GC safe call expression
```

### Expected Output

```

```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Windows: i386]
Compiled at 2019-03-06
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Araq** [comment]
It's a feature, the effect tracking in Nim was wrong. However, this will probably work again after a stdlib patch.

**Comment by slangmgh** [comment]
Thank you. @Araq 

Gc-safe call is difficult to find when it comes and compiler doesn't give any information about which proc is the culprits.

**Comment by Araq** [comment]
> Gc-safe call is difficult to find when it comes and compiler doesn't give any information about which proc is the culprits.

Oh it's not that bad, annotate ``proc f1() {.gcsafe.}`` and repeat until the real problem is listed.
