### ISSUE TITLE
closure is treated as non-gc safed call

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#10796]
Closure is treated as non-gcsafed call. 

Following code was compiled fine, now it fails.

### Example

```nim
import threadpool
proc f2(): proc () =
   proc f21() =
      echo "xx"

   f21

proc f1() =
   f2()()
   echo "hello"

spawn f1()

```

### Current Output
```
t9.nim(26, 9) Error: 'spawn' takes a GC safe call expression
```

### Expected Output

```
```

$ nim -v
Nim Compiler Version 0.19.9 [Windows: i386]
Compiled at 2019-03-06
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by slangmgh** [comment]
```nim
proc f2(): proc () {.gcsafe.} =
   proc f21() {.gcsafe.} =
      echo "xx"

   f21
```

Change the return proc as {.gcsafe.}, the compiler run fine.

**Comment by slangmgh** [comment]
So, it is not bug, just more strict check than previous version?

**Comment by Araq** [comment]
Yes, sorry. It was a bug that the compiler used to accept it.
