### ISSUE TITLE
Mismatch in ABI for C call on linux x64.

### ISSUE THREAD

**Issue by GrundleTrundle** [nim-lang/Nim#10798]
When calling an external C function that takes a struct of 4 floats as a parameter, nim cpp generates a signature for the external function that passes the struct as a pointer.  But the C code is actually expecting the struct to be pushed onto the stack as 4 quadwords.

### Example

```nim
# nim cpp this
type
  BB = object
    l, b, t, r: float

proc BBQuery(x: ptr int; bo: BB; y, z: int, p: pointer) {.cdecl, importc: "BBQuery", dynLib: "something.so".}

proc go() =
  var b : BB
  BBQuery(nil, b, 0, 0, nil)

go()
```
And here is the declaration for the function in C:
```c
struct BB {
 float l;
 float b;
 float r;
 float t;
};
void BBQuery(int* x, struct BB b, uintptr_t a, uintptr_t c, void* data);
```
Looking in the generated cpp file, here is the generated signature:

```c++
typedef N_CDECL_PTR(void, tyProc_rOkAnd5oBJludK9a9cLdAcDA) (NI* x, tyObject_BB_VC12rbhglIvYtYJVfbUeuQ* bo, NI y, NI z, void* p);
```

### Expected Output
I would expect the ``bo`` parameter to not be a pointer in the generated function signature.

### Additional Information
This was with the devel branch updated today:
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-03-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 3c0f01faa0125f8632951290ad1475e1d93b3b1a
active boot switches: -d:release
```

**Comment by krux02** [comment]
this is not a bug. ``float`` in Nim is an alias to ``float64``, which is 8 bytes. In C ``float`` is 4 bytes. Correct translation is:

``float``, ``float64`` → ``double``
``float32`` → ``float``

**Comment by GrundleTrundle** [comment]
Hmm, let me recheck that.  I know in the real library I hit this with,  it's using float64, but I screwed up the shortened example.

**Comment by GrundleTrundle** [comment]
I must need sleep.  What do you mean by "tag your type as value type"?  Is it a pragma I missed?

**Comment by krux02** [comment]
this is the pragma that I mean: https://nim-lang.org/docs/manual.html#foreign-function-interface-bycopy-pragma

**Comment by GrundleTrundle** [comment]
Well that did it.  I guess I've never run into this because (thankfully) most libraries don't pass larger structs by value like that.  Sorry for the confusion.
