### ISSUE TITLE
[docgen] Generic type pragmas in wrong place

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#10792]
As per #9993, pragmas in a generic type declaration are meant to go after the generic parameter list.

```nim
type
  # RIGHT!
  Foo*[T] {.bycopy.} = object
    x: int

  # WRONG!
  Bar* {.bycopy.} [T] = object
    x: int
```

`nim doc`, however, renders this the wrong way:

![image](https://user-images.githubusercontent.com/41453959/53825851-e2f7f780-3f3c-11e9-874b-0c86587ea96b.png)

**Comment by krux02** [comment]
@narimiran isn't this something for you?
