### ISSUE TITLE
Compiler tries to multiply two matrices as if they were vectors

### ISSUE THREAD

**Issue by BitPuffin** [nim-lang/Nim#1080]
https://gist.github.com/BitPuffin/10470877

The error happens when the compiler reaches https://gist.github.com/BitPuffin/10470877#file-matrix-nim-L383

Even though those procs return matrices the error I get:
vector.nim(7, 42) Error: ordinal type expected
suggests that it is treating them as vectors when clearly they are not.

So what I think is that it is mistaking matrix `*` with vector `*`, now the other interesting thing is, I noticed that I had when false'd `*`out, even when I added a dummy multiply proc (https://gist.github.com/BitPuffin/10470877#file-matrix-nim-L131) it STILL matched to the vector component by component `*`. So it wasn't like I initially thought, that it matched to it because there was no \* for matrices.

**Comment by gmpreussner** [comment]
Possibly related:

```Nimrod
type Vector*[N: static[int], T] = ...
proc x*[T](v: Vector[2, T]): T = v[0]
proc x*[T](v: Vector[3, T]): T = v[0]

var a: Vector[3, float]
echo a.x # Error: ambiguous call; both vector.x(v: Vector[2, x.T]) and vector.x(v: Vector[3, x.T]) match for: (Vector[3, system.float])
```

**Comment by gmpreussner** [comment]
Most of this seems fixed now. However, barcharcraz' code now throws an internal compiler error. Possibly related to https://github.com/nim-lang/Nim/issues/1082#issuecomment-152779991

**Comment by andreaferretti** [comment]
As of today:

* @gmpreussner says his code is now working fine
* @barcharcraz code is nowhere to be found
* the original example by @BitPuffin does not compile anymore, but for completely unrelated reasons to the original issue - mostly things that have changed in the last 4 years

I don't think there is a chance to figure out if there is something left to fix here. Should we close the issue?

**Comment by Araq** [comment]
Any existing bugs left likely have a duplicate somewhere anyway. Closing.
