### ISSUE TITLE
Unsafeaddr rendered as addr in typed AST 

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10807]
Example:
```nim
import macros

proc test_unsafeaddr(x: int): int = 
  cast[int](unsafeAddr(x))

macro dumpSym(someproc: typed): untyped = 
  echo someproc.getImpl.repr

dumpSym(test_unsafeaddr)
```

test_unsafeaddr rendered as:
```
proc test_unsafeaddr(x: int): int =
  result = cast[int](addr(x))
```
unsafety of addr is lost.

**Comment by cooldome** [comment]
@Araq:
In order to fix this one looks like new node kind will  be required. Are you ok with such solution?

**Comment by Araq** [comment]
I think we can instead make the backends aware of  ``mAddr`` magic instead of an ``nkAddr`` node kind.

**Comment by cooldome** [comment]
Make sense. I will do exactly that.
