### ISSUE TITLE
[Regression] "koch docs" fails at io.nim with "import os" in config.nims

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#10800]
I have a config.nims that does `import os`. With that present in the config search path, `koch docs` fails when building the `io.nim` docs.

This is a regression on `devel` branch that occurred over approximately past 1 week.

### Example

With an `import os` containing `config.nims`, this issue can be recreated with either of these commands run from the Nim build (git cloned) directory:

- `koch docs` (assuming `koch` is already built)
- `nim doc ./lib/system/io.nim` 

### Current Output

With `koch docs`, I get this error:

```
...
bin/nim doc --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.19.9  --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.19.9/system.html --index:on lib/system.nim
bin/nim doc --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.19.9  --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.19.9/io.html --index:on lib/system/io.nim
../pure/os.nim(2884, 27) Error: undeclared identifier: 'FileHandle'
```

With `nim doc ./lib/system/io.nim`, I get:

```
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/lib/system/io.nim.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/config.nims' [Conf]
/home/kmodi/usr_local/apps/6/nim/devel/lib/pure/os.nim(2884, 27) Error: undeclared identifier: 'FileHandle'
```

### Expected Output

The `koch docs` should not error out.

### Additional Information

I can bypass using my config.nims in the `nim doc` command by doing `nim --skipUserCfg doc ./lib/system/io.nim`. But I don't know how to do that with the `koch docs` command.

### Nim versions

- Current failing version: `devel`: 26f48437ca429f8e25f20d1f986c5b46e83cc90b

**Comment by kaushalmodi** [comment]
Very much related issue that was fixed in the past, but this time, it's affecting `koch docs`: https://github.com/nim-lang/Nim/issues/10030.

**Comment by Araq** [comment]
I'm beginning to think ``config.nims`` is beyond repair.

**Comment by kaushalmodi** [comment]
@Araq 

I see this issue on Nim 0.20.0 too:

```
bin/nim doc --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.20.0  --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.20.0/io.html --index:on lib/system/io.nim
/home/kmodi/downloads/git/Nim/lib/pure/os.nim(2897, 27) Error: undeclared identifier: 'FileHandle'
```
