### ISSUE TITLE
Enforce destructors are not used before definition

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#10811]
In order to fix the loopholes in the destructor *design* (this is not about implementation bugs), I propose the following solution.

From the destructor injection rules the so called "frontend marking rules" are derived:

- We treat assignment and sinks and destruction as identical.
- We attach a fake destructor to the involved type tracking
  its first usage. This process is called "marking".
- In the construct ``let/var x = expr()``  expr's type is marked.
- In ``x = y`` the type of ``x`` is marked.
- For every sink parameter of type ``T`` ``T`` is marked.
- For every call ``f()`` the return type of ``f()`` is marked.
- In ``deepCopy(x, y)`` we need to mark all involved types of ``x``
  recursively, but with a marker that is different from the
  general type-bound operation marker.

Now when we encounter a ``=destroy``, ``=sink``, ``=`` we check whether it
hasn't been used by ``typ.destructor.isNil``.

As an optimization we replace the tfHasAsgn flag with an tfHasObj
flag. Only objects or types involving objects have to be checked. This means in
practice at least integers, bools, floats and enums are skipped quickly and
don't slow down compilation.

These rules ensure that the type bound operations are not used before they
are defined.

**Comment by Araq** [comment]
ping @cooldome

**Comment by cooldome** [comment]
It does sound similar to what I had in mind, issues I have found so far:
`supportsCopyMem` trait doesn't work as at the time of its invocation it is not clear if object has destructor or not. Let's discuss over skype call.

**Comment by cooldome** [comment]
I think we forgot to discuss this one. Another call tomorrow?

**Comment by Araq** [comment]
This has been implemented but now destructors' documentation needs to be updated.

**Comment by Araq** [comment]
And now at least the new wiki page was updated, so closing.
