### ISSUE TITLE
Regression in destructor injection. Showstopper.

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10839]
Regression is caused by f39aa1b40bd617e5ac13f67b38548e91d49bf107

Multiple issues: sink calls missing, double destroy where should be no destroy,  generated cpp doesn't compile.

The following change has many problems:
```nim
  of nkDiscardStmt:
    result = n
    if n[0].typ != nil and hasDestructor(n[0].typ):
      result = genDestroy(c, n[0].typ, n[0])
```
First it doesn't recourse into n[0], but even if you fix it like that:
```nim
  of nkDiscardStmt:
    result = n
    result = pArg(n[0], c, isSink = true)
    if result[0].typ != nil and hasDestructor(result[0].typ):
      result = genDestroy(c, result[0].typ, n[0])
```
the missed sink and double destroy goes  away, but generated `cpp` code doesn't compile with gcc, error:
```
error: cannot bind non-const lvalue reference of type 'tyObject_MyObject_sfap0iBeXbWUXKElTMU2SQ&' to an rvalue of type 'tyObject_MyObject_sfap0iBeXbWUXKElTMU2SQ'
   eqdestroy__GN51R9b5K9bRFn9aZGp9bJKtJQ(sumObjs_9cvFmxz3PV9aAd08amWT9cB9bQ(x, y));
```

I suggest reverting for now

**Comment by Araq** [comment]
Your PR was merged.
