### ISSUE TITLE
Problem with borrow pragma

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#10830]
Maybe problem is that proc result is not void, maybe I apply it wrong?
For example try to borrow this one:

https://nim-lang.github.io/Nim/system.html#[]%2Cstring%2CBackwardsIndex

```nim
type
  AltString = distinct string

proc add(x: var AltString, y: string) {.borrow.}
proc `&=`*(x: var AltString, y: string) {.borrow.}
proc `[]`(s: string; i: BackwardsIndex): char {.borrow.}

var x: AltString

x.add("xx")
#echo string(x)
discard x[0]
```

```
b.nim(6, 1) Error: no symbol to borrow from found
stefan@nuc /tmp/hhh $ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-23
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 28a83a838821cbe3efc8ddd412db966ca164ef5c
active boot switches: -d:release
```

Forum Reference: https://forum.nim-lang.org/t/1417

**Comment by andreaferretti** [comment]
You are trying to borrow on a proc that does **not** involve `AltString`:

```nim
proc `[]`(s: string; i: BackwardsIndex): char {.borrow.}
```

**Comment by StefanSalewski** [comment]
Oh yes indeed. But this was only a result of my last try to be sure that there is no typo from me involved, so I copied the proc header again from system.nim before shipping this issue. Actual code was

```nim
proc `[]`(s: AltString; i: BackwardsIndex): char {.borrow.}
```

Exactly same error message.

**Comment by StefanSalewski** [comment]
One more remark: My initial goal was to borrow this:

https://nim-lang.github.io/Nim/system.html#[]%3D%2CopenArray[T]%2CBackwardsIndex%2CT

```nim
proc `[]=`[T](s: var openArray[T]; i: BackwardsIndex; x: T) {...}
```

```nim
type MinMaxHeap[T] = distinct seq[T]

proc `[]=`[T](s: var MinMaxHeap[T]; i: BackwardsIndex; x: T) {.borrow.}
```

But of course that is hard due to openArray and generic. But I think the above code with AltString should be possible.

**Comment by mratsim** [comment]
BackwardsIndex is also a distinct type. Maybe the compiler gets confused when using borrow with 2 distinct types?

**Comment by awr1** [comment]
workaround (also, 0 is not a valid BackwardsIndex, but ^1 is):

```nim
proc `[]`(s: AltString; i: BackwardsIndex): char = s.string[i]
```

https://github.com/nim-lang/RFCs/issues/22 might provide a partial fix, but avoids the issue of borrow not bleeding correctly through a generic type.
