### ISSUE TITLE
Generic closure fields do not work on JS backend

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#10849]
Codegen for generic closures seems to be broken on the JS backend (works fine when compiled to C).

### Example

```nim
type
  Generic[T] = ref object
    getState*: proc(): T

proc newGeneric[T](): Generic[T] =
  var state: T

  proc getState[T](): T =
    state

  Generic[T](getState: getState)

let g = newGeneric[int]()
let state = g.getState()
echo(state)
```

### Current Output

Running the resulting JS code crashes with:
```
/home/fabian/git/NimExperiments/closure_methods/draft4.js:118
		result_79051 = state_79038;
```
Note: The same pattern works on JS when the example doesn't use generics or when the closure is returned directly, i.e., not as an object field.

### Expected Output

Codegen for C works fine and prints 0.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-03-15
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 328901757a2bb5d482afafdd0e45bd54355c90b5
active boot switches: -d:release
```

The generated code is:

```javascript
function get_state_79048() {
	var result_79051 = 0;

	var F={procname:"getState.getState",prev:framePtr,filename:"draft4.nim",line:0};
	framePtr = F;
		F.line = 9;
		result_79051 = state_79038;
	framePtr = F.prev;

	return result_79051;

}

function new_generic_79027() {
	var result_79037 = null;

	var F={procname:"newGeneric.newGeneric",prev:framePtr,filename:"draft4.nim",line:0};
	framePtr = F;
		F.line = 6;
		F.line = 6;
		var state_79038 = 0;
		result_79037 = {getState: get_state_79048};
	framePtr = F.prev;

	return result_79037;

}
var g_79078 = new_generic_79027();
var state_79079 = g_79078.getState();
rawEcho(cstrToNimstr((state_79079)+""));
```

A guess: The compiler did not see that `get_state_79048` closes over `state_79038` and put it into global scope? If it would put the function between the lines `var state_79038 = 0;` and `result_79037 = {getState: get_state_79048};` it would work (which is what happens if I make the example non generic).

**Comment by ghost** [comment]
Still an issue
