### ISSUE TITLE
Assigning shallow string to a field makes a copy

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#10845]
Nim e26370268885718c6b48a9fa5e940fdc8b4df090

If shallow `string` or `seq` is assigned to a field, it gets copied. It's unclear what the expected behaviour is here, so at least documentation of `shallow()` should be improved.

Notice that this seems to be expected to work by some stdlib parts, for example: https://github.com/nim-lang/Nim/blob/e26370268885718c6b48a9fa5e940fdc8b4df090/lib/pure/asyncnet.nim#L390

All in all, if it currently works as expected, then `shallow()` seems pretty useless.

### Example
```nim
type
    TGenericSeq {.pure, inheritable.} = object
      len, reserved: int
      when defined(gogc):
        elemSize: int
    PGenericSeq = ptr TGenericSeq

const seqShallowFlag = low(int)

template checkShallow(str: string) =
  var s = cast[PGenericSeq](str)
  assert((s.reserved and seqShallowFlag) != 0)

type
  SomeObj = ref object
    s: string

let obj = new(SomeObj)
var str = newString(4000)
shallow(str)
obj.s = str
checkShallow(obj.s)
```

**Comment by Araq** [comment]
It's a valid bug.
