### ISSUE TITLE
Can't set an environment variable in a task

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#10851]
I don't seem to be able to set an environment variable in a nimble task, am I missing something?
```
task t, "t":
   echo existsEnv("FOO")
   putEnv("FOO", "foo")
   echo getEnv("FOO")
```
Doing `nimble t` outputs:
```
false
          <-- note empty line
```

**Comment by genotrance** [comment]
This has been fixed in Nimble and works as expected now.
