### ISSUE TITLE
entries in the stdlib docs should have a (perma)link

### ISSUE THREAD

**Issue by AvdN** [nim-lang/Nim#10859]
### Summary

Documentation entries have "Source" and "Edit" links at the bottom, they should also have a perma-link item after "Edit" Such an item can be clicked, just like the toc entry for such a documenation entry, to get the hash extension on the current URL, or it can be right-clicked to get a "copy-link-location" selection in a browser.

### Description

This makes it easier to link to a particular documentation entry from other documents, the forum, StackOverflow etc.

If you get to a particular entry via the toc, you will of course not need this, but if you get to the entry by scrolling through the file, it is not always quick to scroll to the toc and select the item you were looking at, especially if the page is long and the toc far above the entry.

A good example of documentation that has these links are the Python stdlib docs (where it is even more necessary as the toc is less detailed) E.g. go to https://docs.python.org/2/library/string.html and move the mouse to the right of the first entry `string.ascii_letters`  . A good example of documentation that doesn't have this is the YAML 1.2 specification (and it is a pain).

### Alternatives

I am used to the pilcrom symbol (¶) to provide this (perma) link, but using the world "Link" might be more in style. In the Python documentation this symbol is only shown when hovering over the approximate location. Since the "Source" and "Edit" links are already less prominent I think that is enough for the "Link" -link as well.

A completely different way to implement this is by making the name of an item clickable (i.e. terminate in the first line [here](https://nim-lang.org/docs/osproc.html#terminate%2CProcess)

### Additional Information

This can probably be implemented by extending the `doc.item.seesrc` entry in `config/nimdoc.cfg`, assuming `$itemSymOrIDEnc` used in `doc.item.toc` is also available when expanding the "full" item.

**Comment by SolitudeSF** [comment]
Entries are clickable on devel docs https://nim-lang.github.io/Nim/osproc.html#terminate%2CProcess

**Comment by narimiran** [comment]
This is something that has bothered me for a long time, and, as @SolitudeSF has already mentioned, now (in the last month or two) it is implemented in devel docs which available at https://nim-lang.github.io/Nim/lib.html (devel docs also have more detailed documentation and other improvements).

**Comment by AvdN** [comment]
Thanks for the reference, I had been using the "normal" docs, and not realiased the devel documents are available (and different).

(I did search the devel branch for itemSymOrIDEnc to see if that was used in some hidden way that I had not found out).
