### ISSUE TITLE
Type aliases do not work with Exceptions.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#10889]
When creating a type alias for an Exception, there's a compile time error of `raised object of type ref B does not inherit from Exception` (on devel).

```
type
    A = ref object of Exception
    B = A
raise newException(B, "")
```

The expected behavior is this throws a runtime error with a blank message.

On stable, the error is `only a 'ref object' can be raised`.

**Comment by Araq** [comment]
Btw ``newException`` works with non-ref object types.
