### ISSUE TITLE
Fail to compile because a procedure call is of type 'unknown'

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#10894]
### Example

```nim
import macros
proc pp(nn:NimNode) = echo nn.lisprepr
proc pp(nn:typedesc) = pp(nn.gettype)
macro p(n:typedesc):typed =
  n.pp
  newstmtlist()
p(float)
```

### Current Output
```
t0.nim(5, 4) template/generic instantiation of `pp` from here
t0.nim(3, 26) Error: expression 'pp(nn.getType)' is of type 'unknown' and has to be discarded
```

**Comment by jyapayne** [comment]
This is likely because you are trying to call `getType` on a `typedesc`. Not sure what you're trying to do, but the following works fine:

```nim
import macros
proc pp(nn: NimNode) = echo nn.lisprepr

macro p(n: typed): typed =
  n.pp
  newStmtList()
p(float)
```

**Comment by jxy** [comment]
Because `typedesc` is not passed in as `NimNode`, when some macros gets applied to real code where `proc` or `template` can specify `typedesc` as argument.

**Comment by krux02** [comment]
Just tested it, the output is ``(Sym "float")``. I guess that is what is expected.
