### ISSUE TITLE
`auto` return type in macros causes internal error

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#10904]
An `auto` return type specified in a macro definition causes an internal error of the compiler.  The commit bf592c4e9 introduced the bug.

### Example

```nim
import macros
macro m:auto = newStmtList()
```

### Current Output
```
t.nim(2, 16) Error: internal error: assignment requested for type: untyped
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

**Comment by andreaferretti** [comment]
I noticed because it affects https://github.com/andreaferretti/react.nim (it can be fixed with minor changes, but it is probably worth fixing in the compiler instead)
