### ISSUE TITLE
Check if `%` from `strutils` is used correctly at compile-time if all arguments are literals or constants

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#10924]
In other words, check if the number of arguments is such that it will not raise a ValueError when runtime.

**Comment by krux02** [comment]
I am sorry, but this is really a low effort feature request.

**Comment by mratsim** [comment]
AFAIK `strformat` is the way forward and does not has this ValueError and weird semantics.

**Comment by Araq** [comment]
Now we have strformat which is better all around, IMO. Closing.
