### ISSUE TITLE
`lent T` can return garbage

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10942]
I was able to reproduce this problem only with `--cpu:i386 --cc:vcc` compiler arguments, but the problem is fundamental. Test case:
```nim
type
  MyField = object
    b: seq[string]

  MyObject = object
    f: MyField

proc getX(x: MyObject): lent MyField = 
  x.f

let a = MyObject()
echo a.getX.b.len

# doAssert: a.getX().unsafeAddr == a.f
```

The generated code for `getX` proc has fundamental flaw:
```C

N_LIB_PRIVATE N_NIMCALL(tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA*, 
getX_bA682BkQAkX49bq4vsNGpig)(tyObject_MyObject_J9bt9aFMq9aaD4DaLIDS9cAW1Q x) {
	tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA* result;
	result = (tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA*)0;
	result = (&x.f);
	return result;
}
```
The `x` argument is passed by copy hence returned pointer is  a pointer to a temporary object. I am afraid it is not a valid C code.

If proc returns `lent T` then all object/tuple arguments needs be passed by reference.
I have tried fixing it by changing codegen, but it wasn't not enough. sempass needs to add hidden addr, derefs nodes to make it work.

**Comment by cooldome** [comment]
The last commented line in the test would have detected the problem, but `unsafeAddr` doesn't work for `lent T` at the moment. Should we add support for `lent T` in `semAddrArg` and/or `isAssignable`?

**Comment by Araq** [comment]
> If proc returns lent T then all object/tuple arguments needs be passed by reference.

Or maybe ``lent`` shouldn't be available here? Would it be too bad if we require a ``var MyObject`` here?

**Comment by cooldome** [comment]
`var MyObject` would be a problem.
I though about it once again, it should be possible to fix it only in the codegen as {.byref.} pragma on MyObject fixes the problem. I will give it another try.

**Comment by Araq** [comment]
I don't really like it but it's ok, at least it doesn't require yet another language extension.

**Comment by zah** [comment]
Why is this object passed by value in the first place? Is this some kind of optimization based on the object size? My assumption is that all object types are passed by `const &` by default.

**Comment by cooldome** [comment]
Yes,
It is an optimization based on the object/ tuple size. Taking this optimization out will solve the problem.
Araq, what do you think? Is it OK to always pass object/tuple by reference?

**Comment by Araq** [comment]
No way, it's a very useful optimization. But you can simply look at the return type, if ``lent`` then the first parameter needs to be passed as a pointer.
