### ISSUE TITLE
shallow() issues

### ISSUE THREAD

**Issue by fowlmouth** [nim-lang/Nim#1094]
``` nimrod
var x,y: seq[int]
y = @[]
shallow y

x = y
x.add 1

echo "x: ", x, ", y: ", y
```

output: `x: @[1], y: @[1563515712, 0, 0, 2]`

``` nimrod
var x,y: string
y = ""
shallow y

x = y
x.add "42"

echo "x: ", x, ", y: ", y
```

output: `x: 42, y:`

The string test works fine when the code is in a block or the initial string has len > 0

**Comment by andreaferretti** [comment]
With latest Nim, the output is `x: @[1], y: @[]`, consistent with the string case

**Comment by andreaferretti** [comment]
I think the current behaviour is correct, even though not very intuitive.

When `y` is assigned a literal, it becomes a sequence whose capacity is the same as its length. The copy `x = y` **is** actually shallow, but as soon as one adds an element to `x`, `x` is relocated and a copy is performed.

The following example, where `y` is created with enough capacity to start with, behaves as expected:

```nim
var x, y: seq[int]

y = newSeqOfCap[int](8)
y.add 1
y.add 2
y.add 3
shallow y

x = y
x.add 5

echo x # @[1, 2, 3, 5]
echo y # @[1, 2, 3, 5]
```

Similarly if one does not add to `x`, but replace existing elements:

```nim
var x, y: seq[int]

y = @[1, 2, 3]
shallow y

x = y
x[0] = 4

echo x # @[4, 2, 3]
echo y # @[4, 2, 3]
```

The inconsistency between strings and seqs does not happen anymore, as per my previous remark. I think this can be closed
