### ISSUE TITLE
httpclient: socket info is not accessible

### ISSUE THREAD

**Issue by shomodj** [nim-lang/Nim#10958]
```nim
  HttpClientBase*[SocketType] = ref object
    socket: SocketType
    connected: bool
    ...
```

I think socket either needs to be public or client should have a proc to return it.

why?

any serious debugging or error message printing needs access to socket.localAddr and socket.remoteAddr

let me know how I should approach this and I will create a PR

thx

**Comment by Araq** [comment]
A getter proc usually is more future-proof. (Sad, I know.)

**Comment by shomodj** [comment]
> A getter proc usually is more future-proof. (Sad, I know.)

Thanks, 

final Q: ;)

I was reading this https://nim-lang.org/docs/nep1.html and I'm assuming proc socket* is in order and not getSocket* ?

**Comment by Araq** [comment]
I think in this case ``getSocket`` is better because it isn't commonly used.
