### ISSUE TITLE
`str &= data` doesn't behave as `str = str & data`.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#10963]
If a string and an int are combined via `&`, a compilation error occurs. When combined via `&=`, the int is converted to a string via `$` and the code compiles. This error doesn't occur in Nimscript, and is localized to Nim.

```nim
var
    a: string = "abc"
    b: int = 5
a &= b
echo a
```

### Current Output
`abc5`

### Expected Output
Compilation Error of `Error: type mismatch: got <string, int>`

Tested on 0.19.0, 0.19.4, and devel (compiled as this issue was written). All three had Nimscript (tested via `nim secret`) throw an error, but Nim compile.

**Comment by PMunch** [comment]
According to Araq on IRC this is caused by an `add` proc that takes a string and an int, which I assume is this one: https://nim-lang.org/0.19.2/system.html#add%2Cstring%2Cint64

**Comment by mratsim** [comment]
I think a `&` overload for string, int should be in `sugar.nim` or `lenientops.nim`, same thing for `&=`.
