### ISSUE TITLE
toSeq on iterators does not work in Nimble

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#10969]
I wanted to use the same code as nimble's default `test` implementation does, but it fails when trying to combine `toSeq` with `walkDir`:

```nim
# Package

version       = "0.1.0"
author        = "you"
description   = "A new awesome nimble package"
license       = "MIT"
srcDir        = "src"

# Dependencies

requires "nim >= 0.19.9"

import sequtils
import oswalkdir

task wd, "test walkDir":
  let files = toSeq(walkDir("."))
  echo files
```

Error:

```
     Error: Could not read package info file in ...;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     test.nimble(15, 28) Error: attempting to call undeclared routine: 'walkDir'.
```

Not sure if this is a Nim error or Nimble specific.

**Comment by nc-x** [comment]
`t.nims` -
```
import sequtils
import oswalkdir

let files = toSeq(walkDir("."))
echo files
````
`nim c t.nims` works fine.

@dom96 nimble bug?

**Comment by dom96** [comment]
@nc-x did you run that with `nim e t.nims`?

**Comment by nc-x** [comment]
@dom96
I didn't know that command, so I will have to recheck.
  
But then what does the command `nim t.nims` do? Because I get the correct output with it.

**Comment by dom96** [comment]
I have no idea, that shouldn't be a correct invokation, maybe someone made that an alias for `e` though. In any case, I don't see how this could be a Nimble bug, even if it is it won't matter because @genotrance is working on completely rearchitecting how Nimble evals .nimble files.

**Comment by Araq** [comment]
``nim t.nims`` is the same as ``nim e .tnims``.

**Comment by bluenote10** [comment]
I verified again, and it seems to be a Nimble issue. The problem is also not related to `walkDir`. Reduced example:

```nim
# Package
version       = "0.1.0"
author        = "you"
description   = "A new awesome nimble package"
license       = "MIT"
srcDir        = "src"

# Dependencies
requires "nim >= 0.19.9"

import sequtils
let s = toSeq("asfd".items()) 'items'.
echo s

# /tmp/test.nimble(12, 21) Error: attempting to call undeclared routine: 'items'.
```

The same code works as a nimscript.

**Comment by dom96** [comment]
It's likely that you have just got Nimble compiled against an old Nim with this bug

**Comment by bluenote10** [comment]
I just recompiled both, and my versions are now:

Nim:
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-13
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f6ad071a46a2bec57db453343d8d8b75d3d16ac2
active boot switches: -d:release
```

Nimble:
```
nimble v0.9.0 compiled at 2019-04-13 12:48:58
git hash: c8d79fc0228682677330a9f57d14389aaa641153
```

The problem is still reproducible for me. Are they consistent now?

**Comment by dom96** [comment]
@bluenote10 it's hard to say, these version strings don't show what commit of the compiler was used in Nimble.

**Comment by krux02** [comment]
I just tried to test it and make sure that this bug is unrelated to nimble. Then I realized that walkDir doesn't seem to work at runtime at all.

```nim

import sequtils
import oswalkdir

proc main() =
  # does warkDir work?
  for a, b in walkDir(".", true):
    echo b

  # does toSeq warkDir work?
  let files = toSeq(walkDir(".", true))
  echo files

static:
  # does it work at compile time
  main()

# does it work at runtime
main()
```

``toSeq`` doesn't cause any problems here at all. Both the raw iterator and the ``toSeq`` version works. But at runtime the iteration is completely empty, at least on my linux system.

**Comment by bluenote10** [comment]
Very strange, your example works for me. There is also this issue https://github.com/nim-lang/Nim/issues/8096 ([regression]: in nimble tasks walkDir no longer works) which was recently closed, so I'd assume `walkDir` works/worked in general at compile time.

**Comment by nc-x** [comment]
This can be closed. With latest nimble (i.e. after shashlick's nocompiler pr), this works fine.
