### ISSUE TITLE
RFC: Disable hints for a Block, not the entire file.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#10973]
### Summary
Disabling hints, using `{.hint[HINT_NAME]: off.}` syntax, currently disables that hint for the entire file. That said, it'd be great if it could be used as a block statement, so hints are only disabled for a section, not everything.

### Reason
The specific hint that caused this request is `XDeclaredButNotUsed`. In my work, I need to disable the hint for unused functions, but would like for the hint to still work for raises pragmas.

**Comment by Araq** [comment]
Do you know about the ``.used`` pragma that was designed for this?

**Comment by mratsim** [comment]
This seems to be covered by

```Nim
template disableHint(body: untyped): untyped =
  {.push: hint[XDeclaredButNotUsed]: off.}
  body
  {.pop.}
```

However I'm pretty sure the push/pop doesn't work with specific hints but only for all hints because https://github.com/nim-lang/Nim/issues/4044 was only solved via workaround.

**Comment by kayabaNerve** [comment]
Thank you for informing me of that macro. I misinterpreted it's purpose.

That does solve my current problem, yet I would like to say I believe `{.hint[X]: off.}:` has potential advantages outside of `XDeclaredButNotUsed`. @mratsim provides a workaround, and between `used` and said workaround, I don't think this request has anymore validity. If you agree, please close my issue (I rather not close it if someone else thinks there should be further discussion).
