### ISSUE TITLE
`raise` works in a func, but `getCurrentException()` doesn't.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#10985]
I'm not sure if this counts as a feature request or a bug.

`raise`, which has the same effect as `raise (ref ExceptionType)(getCurrentException())`, can be called in a `func`, while `raise (ref ExceptionType)(getCurrentException())` cannot, which seems inconsistent, although I recognize the wider implications of `getCurrentException()`.

This means that in a `func` annotated with `raises`, you must add either `ReraiseException` and `Exception` to `raises`, or change the `func` to a `proc`.

Fails to compile:
```
proc called() {.raises: [KeyError].} =
    raise newException(KeyError, "This is a KeyError.")

func failure() {.raises: [KeyError].} =
    try:
        called()
    except:
        raise
```

Works:
```
proc called() {.raises: [KeyError].} =
    raise newException(KeyError, "This is a KeyError.")

proc failure() {.raises: [KeyError].} =
    try:
        called()
    except:
        raise (ref KeyError)(getCurrentException())
```

Works:
```
proc called() {.raises: [KeyError].} =
    raise newException(KeyError, "This is a KeyError.")

func failure() {.raises: [KeyError, ReraiseError, Exception].} =
    try:
        called()
    except:
        raise
```

Writing this out, I guess this is more of a feature request... That would make the feature a raise which doesn't add `Exception`, as `ReraiseError` can be easily handled via a nested try/catch statement, or a `getCurrentException()` which doesn't identify as a side effect, because there's already access through `raise` which doesn't.

**Comment by Araq** [comment]
But ``getCurrentException()`` has a side effect and newer code should use `` except Stuff as e`` to get the current exception as an object.

**Comment by kayabaNerve** [comment]
I totally missed that. Sorry. Closing this out.
