### ISSUE TITLE
Epoll does not support many file types (EPERM from epoll_ctl)

### ISSUE THREAD

**Issue by ccxcz** [nim-lang/Nim#10991]
The documentation for selectors.nim claims:
> Supported features: files, sockets, pipes, timers, processes, signals and user events.

For epoll that is not true, as it by design does not support notifications from file types which do not implement readiness and are always considered non-blocking. This includes plain files and some very common devices such as /dev/null.
Trying to use such file descriptors with epoll ioselector will yield error such as:
```
asyncdispatch.nim(1154)  addWrite
ioselectors_epoll.nim(164) updateHandle
selectors.nim(284)       raiseIOSelectorsError
Error: unhandled exception: Operation not permitted (code: 1) [IOSelectorsException]
```

The poll and select ioselectors don't have this issue, but there is no mechanism to use the ioselector or asyncdispatch API with those on Linux as epoll is hardcoded.
This can be remedied by adding compile-time define option to select the desired implementation. I will make pull request which does just that.
I would also suggest that ioselectors_poll should be the default on all POSIX platforms (or at least on Linux) to have most predictable application behaviour across platforms and let people manually select other if they need it.

**Comment by ringabout** [comment]
I propose to split `selectors` into `selector_base` and `selectors` modules instead.

Users could include/import `selector_base` to achieve their custom selectors backends. Before users can't achieve this because of `when defined` in `selectors` module. 

Like this:
![image](https://user-images.githubusercontent.com/43030857/98112866-c6fce400-1edd-11eb-9f4b-379a57d5e0c1.png)

**Comment by ringabout** [comment]
Another usage is when users want to extend `selectors` module, they want to reuse the type definitions in `selector`. But `when defined` stops them to define their condition variable. They have to maintain a separate duplicate type definitions.

[For example](https://github.com/xflywind/ioselectors/blob/master/src/ioselectors/base.nim)
