### ISSUE TITLE
Macros and zero-argument custom pragmas can't be defined on the same proc

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#10994]
```nim
import macros

macro foo(x): untyped = x
template bar {.pragma.}

proc a {.bar.} = discard # works
proc b {.bar, foo.} = discard # doesn't
```

**Comment by metagn** [comment]
This code works now, unless I am missing something? How did this not work in the first place?

**Comment by ringabout** [comment]
> How did this not work in the first place?

It didn't work before 1.0.2: `/usercode/in.nim(7, 10) Error: invalid pragma: bar`
