### ISSUE TITLE
Unable to build older versions of Nim (0.17.2/0.18) on macOS 10.14.4 (18E226)

### ISSUE THREAD

**Issue by OldhamMade** [nim-lang/Nim#10996]
When trying to build older versions of Nim via [asdf](https://github.com/asdf-vm/asdf) the builds fail with the following error:

    nimble.nim(7, 45) Error: cannot open 'sugar'

I've tried this with `0.17`, `0.17.2`, and `0.18`.

Clang details as follows:

    $ clang --version
    Apple LLVM version 10.0.1 (clang-1001.0.46.3)
    Target: x86_64-apple-darwin18.5.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

`asdf` uses [this nim plugin](https://github.com/rfrancis/asdf-nim), and the install is [quite basic](https://github.com/rfrancis/asdf-nim/blob/master/bin/install), essentially being:

1. clone version
2. clone & build `csources`
3. `bin/nim c koch`, `./koch boot -d:release`, `./koch nimble`, `./koch tools`

However, looking at the output of the build process, I can see the following:

    ...
    CC: stdlib_typetraits
    CC: compiler_nodejs
    CC: compiler_scriptconfig
    Hint:  [Link]
    Hint: operation successful (103726 lines compiled; 35.698 sec total; 326.426MiB peakmem; Release Build) [SuccessX]
    executables are equal: SUCCESS!
    git clone https://github.com/nim-lang/nimble.git dist/nimble
    Cloning into 'dist/nimble'...
    remote: Enumerating objects: 88, done.
    remote: Counting objects: 100% (88/88), done.
    remote: Compressing objects: 100% (45/45), done.
    remote: Total 3454 (delta 44), reused 76 (delta 43), pack-reused 3366
    Receiving objects: 100% (3454/3454), 1.19 MiB | 617.00 KiB/s, done.
    Resolving deltas: 100% (2142/2142), done.
    git checkout -f master
    Already on 'master'
    Your branch is up to date with 'origin/master'.
    git pull
    Already up to date.
    bin/nim c --noNimblePath -p:compiler -d:release dist/nimble/src/nimble.nim
    Hint: used config file '/Users/phillipoldham/.asdf/installs/nim/v0.17.2/config/nim.cfg' [Conf]
    Hint: used config file '/Users/phillipoldham/.asdf/installs/nim/v0.17.2/dist/nimble/src/nimble.nim.cfg' [Conf]
    Hint: system [Processing]
    Hint: nimble [Processing]
    ....
    Hint: json [Processing]
    Hint: lexbase [Processing]
    nimble.nim(7, 45) Error: cannot open 'sugar'
    FAILURE

So it looks as though the build process is cloning `nimble` from `master` rather than a version which matches that of the `nim` build. Is that correct?

This seems to be a recent issue; I've built `nim` via `asdf` multiple times over the past year or so without any problems. I'd try rebuilding with `v0.19.0` but I don't want to break my working build.

**Comment by mratsim** [comment]
The `future` standard library module has been renamed to `sugar` in 0.19.

By default, Nim uses the latest stable release:

https://github.com/nim-lang/Nim/blob/devel/koch.nim#L121-L129

which now depends on sugar existing. Unfortunately there is nothing we can do for older Nim version, however:

- The latest stable Nimble should work with older Nim versions. It seems to be the approach `choosenim` used in choosenim version switcher (https://github.com/dom96/choosenim/blob/7227aba1b858550f10f10025793142186b5e2e3b/src/choosenim/switcher.nim), cc @dom96.
- Maybe koch should target a specific Nimble commit or version in koch nimble that is known to work for the specific state of devel and it is bumped when needed.

**Comment by Araq** [comment]
> Maybe koch should target a specific Nimble commit or version in koch nimble that is known to work for the specific state of devel and it is bumped when needed.

Oh not that again, use ``http://nim-lang.org/download/nim-0.19.0.tar.xz`` to get a Nimble bundled with Nim. "koch" is used for building from source and that's what it does, it builds Nimble from source.

**Comment by OldhamMade** [comment]
Thanks @mratsim, @Araq. I'll refer to `choosenim` and fork the `asdf-nim` repo to see if I can tweak it to use a `koch`-less approach.

**Comment by dom96** [comment]
Yes, you should use the tarballs instead of cloning the Nim repo and trying to build that on a specific tag.
