### ISSUE TITLE
Varargs int literal conversion issues causing incorrect result

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10999]
if you compile the following example on x64:
```nim
proc varargsToSeq(vals: varargs[int32]): seq[int32] =
  result = newSeqOfCap[int32](vals.len)
  for v in vals:
    result.add v

echo varargsToSeq(1, 2, 3, 4)
```
the output is `@[1, 0, 3, 0]`

if you build with `cpp` command then you will get a compilation error:
```
compiler_varargs.cpp:272:45: error: cannot convert 'NI*' {aka 'long long int*'} to 'NI32*' {aka 'int*'}
  T2_ = varargToSeq_e6PoHJdK9b9cHORG644qSR2Q(TM_vaO0xTJrAGi9bV8KnEIdzxg_3, 4);                                 
```
The reason is that nim didn't covert int literals to int32.

**Comment by mratsim** [comment]
Seems like a similar issue to https://github.com/nim-lang/Nim/issues/10844, VM int64 semantics leaking at runtime for int32 types and int on 32-bit.

**Comment by krux02** [comment]
@mratsim neither this nor the issue you linked to is related to the vm. And no these issues don't seem to be related.

**Comment by krux02** [comment]
What I see is the following bug.
The sem checker sees that all arguments passed to varargsToSeq are ok, they are in the range of int32. Then the arguments are converted into an array: ``varargsToSeq([1,2,3,4])`` without realizing that now the signature does not match anymore. The first item ``1`` makes the array an array of type ``int`` (8 bytes) not ``int32`` (4 bytes). Nothing down the road in the Nim or C compiler notices that this is wrong, only the c++ compilear realizes that the type signature is wrong.

The workaround is the following:

``echo varargsToSeq(1'i32, 2, 3, 4)``
