### ISSUE TITLE
Trying to access {.compileTime.} variables at runtime crashes the compiler

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#10990]
```nim
var xs {.compileTime.} = @["a"]
echo xs[0]
```

**Comment by dawkot** [comment]
This is probably related:
```nim
var x {.compileTime.} = 123
inc x
const x2 = x
echo x2
```

> Error: execution of an external compiler program 'gcc -c  -w  -I'/home/dawkot/.choosenim/toolchains/nim-#devel/lib' -I/home/dawkot/nim/ss14 -o /home/dawkot/.cache/nim/abcd_d/abcd.c.o /home/dawkot/.cache/nim/abcd_d/abcd.c' failed with exit code: 1
> 
> /home/dawkot/.cache/nim/abcd_d/abcd.c: In function ‘NimMainModule’:
> /home/dawkot/.cache/nim/abcd_d/abcd.c:156:39: error: ‘x_ggGzvGpJeJKqS275fSJd5w’ undeclared (first use in this function)
>   TM_z2piaNlZjHPMfcRSfLQa1w_2 = addInt(x_ggGzvGpJeJKqS275fSJd5w, ((NI) 1));
>                                        ^
> /home/dawkot/.cache/nim/abcd_d/abcd.c:156:39: note: each undeclared identifier is reported only once for each function it appears in

**Comment by mratsim** [comment]
Related to https://github.com/nim-lang/Nim/issues/10962 but worse as `xs` is used as a const in the first case.

In the second example `inc x` should be in a static block in my opinion.

**Comment by krux02** [comment]
Even though I disagree that this should work. This compiles now and runs as it should. The second example runs as well even though it is not quite obvious why the result is as it is.
