### ISSUE TITLE
Make possible to write Unicode to console in Windows via _setmode C call

### ISSUE THREAD

**Issue by hernandp** [nim-lang/Nim#11008]
### Summary
Windows console already support proper Unicode character output from C code by changing the stdout stream mode to `_O_U16TEXT`. This is supported beginning with the VS2005 CRT.
However nim Runtime by default sets `stdout` stream mode to `O_BINARY`, crippling this possibility.  

Maybe it's possible to include an option/flag to modify  this behavior without calling C `_setmode` using FFI from the client program, or by requesting user to change codepage to 65001 which e.g breaks batch files. 

### Description

at system.nim we could change

`c_setmode(c_fileno(stdout), O_BINARY)`

to something in lines of:

```
when defined(u16stdout): 
  c_setmode(c_fileno(stdout), _O_U16TEXT)
else:
  c_setmode(c_fileno(stdout), O_BINARY)
```

### Alternatives

* User changing the codepage to 65001 (UTF8) by requesting user intervention or by using SetConsoleOutputCP APIs.
* Using WriteFileW directly to output characters.

### Additional Information
* Here Unicode Input is not considered.

http://blog.kalmbachnet.de/?postid=98
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=vs-2019

**Comment by krux02** [comment]
I am not familiar with the windows API, so I have a question, why do you suggest ``_O_U16TEXT``? Nim uses utf8, why didn't you suggest ``_O_U8TEXT``?

**Comment by Araq** [comment]
> Using WriteFileW directly to output characters.

Lets please try that instead.

**Comment by hernandp** [comment]
I think that requesting WriteFileW for users to get Unicode output in the WIndows console is a bit messy, specially when using the `terminal` module to do fancy things.

I expect for a portable language to echo '\u2510' and get the same output. 

This is not a fault of Nim, of course, but could be nice to offer a workaround for the CRT/Unicode/Windows mess.

As @krux02  mentioned, _O_U8TEXT is probably the correct setting. I will write some tests and comment accordingly.

**Comment by Araq** [comment]
I'm talking about ``WriteFileW`` in Nim's io.nim module, under the covers so that it just works for end users.

**Comment by hernandp** [comment]
Seems changing the stream to `_O_U16TEXT`   or `_O_U8TEXT` modes crashes the program. This is expected when not using wide printing functions (wprintf). I did some research and it's a showstopper already known at MS.  

This would open another can of worms and I doubt how many devs want to actually throw reliable UTF8 at the Windows Console.

I think the situation is bad enough to dismiss my proposal; maybe we can enhance the documentation on a  "specific platform notes" about Windows Console + Unicode and recommending the Nim developer to, if running on a Windows system, change temporarily the Codepage to UTF8 using SetConsoleOutputCP  API and restore the previous codepage on exit.

A nice compromise could be also adding `SetConsoleOutputCP`, `GetConsoleOutputCP` `SetConsoleCP`, `GetConsoleCP` APIs to `winlean` module to offer the door to handle this in the client program itself.

Thanks for your attention.

**Comment by massung** [comment]
> A nice compromise could be also adding SetConsoleOutputCP, GetConsoleOutputCP SetConsoleCP, GetConsoleCP APIs to winlean module to offer the door to handle this in the client program itself.

This would get my vote. Using `SetConsoleOutputCP(65001)` works great for me on Windows.

**Comment by Araq** [comment]
This has finally been fixed. Afaict.
