### ISSUE TITLE
Explicitly indexed out-of-order `const` arrays fail

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#11001]
The following fails:
```
const FOO = [ 1: "world", 0: "hello"]
when isMainModule:
  echo FOO
```
with:
```
Error: invalid order in array constructor
```

but these work:
```
const FOO = [ 0: "hello", 1: "world"]
when isMainModule:
  echo FOO
```

```
let FOO = [ 1: "world", 0: "hello"]
when isMainModule:
  echo FOO
```

**Comment by nc-x** [comment]
@deech 
I get error with `let` and `var` as well. Can you please re-check your last example?

**Comment by Araq** [comment]
Works as it should.

**Comment by jrfondren** [comment]
That it works this way makes enum-indexed arrays less useful. You get superficial readability but must be careful about order:
```
type
  DamageType = enum
    Bludgeoning, Cold, Fire, Radiation, Slashing
  Sens = array[DamageType, int]

let x: Sens = [Cold: 45, Fire: 10, Radiation: 20, Slashing: 0, Bludgeoning: 100]
```

**Comment by jrfondren** [comment]
And, arrays with explicitly indexed constructions that are at least sequential, result in a lie: the first index of `[2:3, 3:4]` is 0, not 2, as opposed to `let x: array[2..3, int] = [3, 4]`

**Comment by Araq** [comment]
"you don't have to be careful about the order", the compiler tells you about it...
