### ISSUE TITLE
strformat/fmt doesn't work for custom types [regression]

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11012]
With a recent update in devel, there's a severe regression that breaks almost all my Nim code.

Here's a simple example:

```nim
import strformat

type
  Animal = object
    name, species: string
  AnimalRef = ref Animal

proc print_object(animalAddr: AnimalRef) =
  echo fmt"Received {animalAddr[]}"

print_object(AnimalRef(name: "Foo", species: "Bar"))
```

## Error

```
t.nim(9, 11) Error: type mismatch: got <string, Animal, string>
but expected one of:
proc formatValue(result: var string; value: SomeFloat; specifier: string): void
  first type mismatch at position: 2
  required type: SomeFloat
  but expression 'animalAddr[]' is of type: Animal
proc formatValue(result: var string; value: SomeInteger; specifier: string)
  first type mismatch at position: 2
  required type: SomeInteger
  but expression 'animalAddr[]' is of type: Animal
proc formatValue(result: var string; value: string; specifier: string)
  first type mismatch at position: 2
  required type: string
  but expression 'animalAddr[]' is of type: Animal
template formatValue[T](result: var string; value: T; specifier: string)
  first type mismatch at position: 2
  required type: T: enum
  but expression 'animalAddr[]' is of type: Animal
template formatValue(result: var string; value: char; specifier: string)
  first type mismatch at position: 2
  required type: char
  but expression 'animalAddr[]' is of type: Animal
template formatValue(result: var string; value: cstring; specifier: string)
  first type mismatch at position: 2
  required type: cstring
  but expression 'animalAddr[]' is of type: Animal
proc formatValue[T](result: var string; value: openArray[T]; specifier: string)
  first type mismatch at position: 2
  required type: openarray[T]
  but expression 'animalAddr[]' is of type: Animal

expression: formatValue(fmtRes463027, animalAddr[], "")
```

It is very impractical to define formatValue for each and every arbitrary custom type.

---

## Nim version

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-11
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: de02fd0b898e41fa91087300d82573d83e357b34
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment]
Note that I am aware that adding an extra `$` in there makes this work .. but it is undesirable because:

- It reduces the code readability .. the concise `{ .. }` syntax was the whole reason to use `strformat`.
- I need to refactor literally hundreds of instances in my Nim experiments (and that's just me who doesn't yet use Nim that heavily).

**Comment by krux02** [comment]
@kaushalmodi 

did you try to provide your own overload of ``formatValue``?

just provide the following overload: 
```nim
proc formatValue(result: var string; value: Animal; specifier: string): void =
  result.add $value
```

And your all your old code will work again.

**Comment by kaushalmodi** [comment]
@krux02 I haven't tried that but as I mentioned earlier it isn't practical for me to do that as I have dozens of custom types like these per project. 

I am working on a larger scale project that interfaces Nim with a foreign language (SystemVerilog), and I transact arbitrary types between the two languages. 

It would be a pain to add this overhead of defining this formatValue for each; especially when it was working seamlessly before.

**Comment by krux02** [comment]
so even adding a generic ``formatValue`` would not do the trick for you?
```nim
proc formatValue[T](result: var string; value: T; specifier: string): void =
  result.add $value
```

**Comment by Araq** [comment]
@krux02 Just fix the regression already, don't lecture us about how your new way of brokeness is superior.

**Comment by kaushalmodi** [comment]
@Araq I confirm the fix. Many thanks!
