### ISSUE TITLE
newruntime - `t.destructor != nil`  [AssertionError] with `toTable()`

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#11014]
```
import tables

var x = {
    1: 1
}.toTable()

echo x
```
`nim c --newruntime t.nim`
```
..\lib\system\fatal.nim(37) sysFatal
Error: unhandled exception: C:\Nim\compiler\liftdestructors.nim(329, 14) `t.destructor != nil`  [AssertionError]
```

**Comment by cooldome** [comment]
tried with very latest dev nim. Seems to work fine with today's fixes by Araq.
Please keep on testing newruntime very useful.

**Comment by nc-x** [comment]
@cooldome 
I still get the crash on latest devel (`git hash: e33266ded1ad31cfd0776e6ec8d1a2c399994068`)

**Comment by cooldome** [comment]
hmmm true, issue still happes in fdc3f54f9760b6512c5bdc3af6ed034187e70ffe
my apologies

**Comment by zevv** [comment]
Also reproduces with:

```
var e = initTable[char, bool]()
e['a'] = true
```

**Comment by Clyybber** [comment]
I extracted this minimal repro snippet from the tables module:
```nim
type
  KeyValuePairSeq[T] = seq[tuple[x, y: int]]
  Table*[T] = object
    data: KeyValuePairSeq[T]

proc initTable*[T](initialSize=64): Table[T] =
  newSeq(result.data, initialSize)

proc enlarge[T]() =
  var n: KeyValuePairSeq[T]

var e = initTable[char]() #Remove this and it works again
enlarge[char]()
```
Whats interesting is, that upon removing the `var e = ...` line it compiles just fine, even though enlarge doesn't touch `e` at all ?!
