### ISSUE TITLE
Autogenerate Wep Api javascript bindings based on Web-IDL

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#11021]
### Summary
> Web IDL is an interface description language (IDL) format for describing application programming interfaces (APIs) that are intended to be implemented in web browsers.

From wikipedia [article](https://en.wikipedia.org/wiki/Web_IDL)
### Additional Information
This [repo](https://github.com/awkward-ninja/nim-whatwg) has a script, that does exactly that.

**Comment by Araq** [comment]
Should be provided as a Nimble package.
