### ISSUE TITLE
json module  cant encode the code with Macro,  Error: undeclared field: 'loaded'

### ISSUE THREAD

**Issue by encorehu** [nim-lang/Nim#11033]
when i use  [nim-orm](https://github.com/nanoant/nim-orm), this repo cant compiles for nim-0.19

use my version https://github.com/encorehu/nim-orm

nim-orm define a model use `loaded` to indicate index of fields.

but json module out put Error: undeclared field: 'loaded'

    type
      Model* {.inheritable.} = object of RootObj
        ## represents abstract ORM model class
        loaded: set[int8] ## maintains list of fields loaded from db
                           ## indexes of the field,
                          ## like 0, 1, 2, 3, 4
                          ##
                          ## int8 can't be modified as int32, Error: set is too large
        stored: set[int8] ## maintains list of fields to be stored in the db
                          ## indexes of the field, to be saving
        row: InstantRow   ## InstantRow of sqlite, mysql, pgsql

i found the error is in json.nim Line:357

      for k, v in o.fieldPairs: 
        #echo ("k,v", k)
        result[k] = %v  ##########here

devel version is line 396:

    proc `%`*[T: object](o: T): JsonNode =
      ## Construct JsonNode from tuples and objects.
      result = newJObject()
      for k, v in o.fieldPairs: result[k] = %v ##########here

my test code is:

    import ../orm_sqlite
    import strutils
    
    import json 
    
    type User = object of Model
      name: string
      password: string
      age: int
      ratio: float
      happy: bool
    
    Model.open(r"d:\Projects\Nim\nim-orm2\tests\mytest.db", "", "", "")
    
    var password = "abc"
    var name = "ann"
    
    var users: seq[ref User]
    users = newSeq[ref User]()
    
    for x in User:
      users.add(x)
      # (name: "joe", password: "123", age: 22, ratio: 1.2, happy: true, loaded: ..., stored: ..., row: ...)
      # name
      # password
      # age
      # ratio
      # happy
      # loaded
      # stored
      # row
    for x in users:
      for k,v in x[].fieldPairs:
        when compiles(v):
          echo k, v
      
    var context = %* {"title": "Title from nim", "users": users, "baa": "Baa!"}
    echo context
    

test_json_for_nim_orm.nim(37, 15) template/generic instantiation from here
C:\nim-0.19.0\lib\pure\json.nim(337, 36) template/generic instantiation from here
C:\nim-0.19.0\lib\pure\json.nim(365, 14) template/generic instantiation from here
C:\nim-0.19.0\lib\pure\json.nim(358, 18) Error: undeclared field: 'loaded'

**Comment by GULPF** [comment]
The json module cannot handle objects with inaccessible fields. Since the `loaded` field is a private field declared in another module it's inaccessible. You need to declare your own overload of `%` for `User` to make it work.

**Comment by encorehu** [comment]
GULPF  you are right, the loaded, stored is inaccessible fields.
maybe when compiles(v) is really not the right way to fix it. 
plz close this issue.
