### ISSUE TITLE
Float64 value was changed on runnableExamples

### ISSUE THREAD

**Issue by jiro4989** [nim-lang/Nim#11056]
Float64 value was changed on runnableExamples.

### Example
My code

```nim
  runnableExamples:
    var strm = newStringStream("000000001000000020000000")
    doAssert strm.readFloat64() == 1.39804328609528886042614983922832e-76'f64
    doAssert strm.readFloat64() == 1.39804328609528916724449142033623e-76'f64
    doAssert strm.readFloat64() == 1.39804328609528947406283300144414e-76'f64
    ## strm.readFloat64() --> raise IOError
    strm.close()
```

### Current Output

Generated source is here.

```nim
## autogenerated by docgen from streams.nim(642, 3)

import
  "/home/jiro4989/src/github.com/jiro4989/Nim/lib/pure/streams.nim"

block:
  var strm = newStringStream("000000001000000020000000")
  doAssert strm.readFloat64() == 1.398043286095289e-76'f64
  doAssert strm.readFloat64() == 1.398043286095289e-76'f64 ## <-- AssertionError
  doAssert strm.readFloat64() == 1.398043286095289e-76'f64
  ## strm.readFloat64() --> raise IOError
  strm.close()
```

### Expected Output

```nim
## autogenerated by docgen from streams.nim(642, 3)

import
  "/home/jiro4989/src/github.com/jiro4989/Nim/lib/pure/streams.nim"

block:
  var strm = newStringStream("000000001000000020000000")
  doAssert strm.readFloat64() == 1.39804328609528886042614983922832e-76'f64
  doAssert strm.readFloat64() == 1.39804328609528916724449142033623e-76'f64
  doAssert strm.readFloat64() == 1.39804328609528947406283300144414e-76'f64
  ## strm.readFloat64() --> raise IOError
  strm.close()
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf
```

**Comment by StefanSalewski** [comment]
Do you know that a float64 variable can store only about 16 significant digits?

So doing a comparison with a float64 literal with more than 16 digits makes no real sense, I assume the compiler may accept it, but has to ignore the additional digits, because they can not be stored.

So when the docgen would keep all the digits, it would generate example code which is nonsense.

Maybe I misunderstand your intent, sorry.

**Comment by mratsim** [comment]
I'm not too sure what you are trying to do but this is the bit pattern of your string:
00110000 00110000 00110000 00110000 00110000 00110000 00110000 00110000 00110001 00110000 00110000 00110000 00110000 00110000 00110000 00110000 00110010 00110000 00110000 00110000 00110000 00110000 00110000 00110000.

Encoding a float as string seems very strange.

Also as @StefanSalewski the maximum precision you can reasonably get for float64 is 1e-16.

Closing, feel free to re-explain with a test case in valid float range
