### ISSUE TITLE
Make parsing procedures in parsutils and strutils generic

### ISSUE THREAD

**Issue by avitkauskas** [nim-lang/Nim#11063]
### Summary
`parsBin`, `parsOct`, `parsHex` in `parsutils` give parsing result only into `int` variable, but sometimes you need the result to be of exact type like `uint64` or `int8`. These proc can be easily made generic and that would also open a way to make templates for `parsBinInt32`, `parsBinUint64` and siblings in `strutils` without much of code replication.

### Description
I suggest the following changes for `parsBin` (others would be similar):

```nim
proc parseBin*[T: SomeInteger](s: string, number: var T, start = 0, maxLen = 0): int {.
  var i = start
  var foundDigit = false
  let last = min(s.len, if maxLen == 0: s.len else: i+maxLen)
  if i+1 < last and s[i] == '0' and (s[i+1] in {'b', 'B'}): inc(i, 2)
  while i < last:
    case s[i]
    of '_': discard
    of '0'..'1':
      number = number shl 1 or cast[T](ord(s[i]) - ord('0'))
      foundDigit = true
    else: break
    inc(i)
  if foundDigit: result = i-start
```

runnableExamples could also be improved.

### Additional Information
Please give your oppinion on that. I have the code ready. Should I go with PR?

**Comment by Araq** [comment]
Go for it, sounds really good.

**Comment by avitkauskas** [comment]
When working on this, I found the fact that the result of parsing depends on the initial value of `number` very surprising. I think the benefits of potencial "chaining" of the parsing are very qustionable, but the surprise errors you get from that side effect are quite difficult to understand. Shouldn't this also be changed? Sure, that would be a breaking change, but maybe it's worth to eliminate such "surprises"?

**Comment by Araq** [comment]
You mean it should start with ``number = 0``? Ok with me, but then add a changelog entry as well.

**Comment by mratsim** [comment]
For reference this is my multi-radix parser for my big ints: https://github.com/status-im/nim-stint/blob/master/stint/io.nim#L137-L173

```Nim
func parse*[bits: static[int]](input: string, T: typedesc[Stint[bits]], radix: static[int8] = 10): T =
  ## Parse a string and store the result in a Stint[bits] or Stuint[bits].

  static: doAssert (radix >= 2) and radix <= 16, "Only base from 2..16 are supported"
  # TODO: use static[range[2 .. 16]], not supported at the moment (2018-04-26)

  # TODO: we can special case hex result/input as an array of bytes
  #       and be much faster

  # For conversion we require overflowing operations (for example for negative hex numbers)
  const base = radix.int8.stuint(bits)

  var
    curr = 0 # Current index in the string
    isNeg = false
    no_overflow: Stuint[bits]

  if input[curr] == '-':
    doAssert radix == 10, "Negative numbers are only supported with base 10 input."
    isNeg = true
    inc curr
  else:
    skipPrefixes(curr, input, radix)

  while curr < input.len:
    # TODO: overflow detection
    when radix <= 10:
      no_overflow = no_overflow * base + input[curr].readDecChar.stuint(bits)
    else:
      no_overflow = no_overflow * base + input[curr].readHexChar.stuint(bits)
    nextNonBlank(curr, input)

  # TODO: we can't create the lowest int this way
  if isNeg:
    result = -cast[Stint[bits]](no_overflow)
  else:
    result = cast[Stint[bits]](no_overflow)
```

**Comment by avitkauskas** [comment]
@Araq, should I put changelog entry into /changelog.md?

**Comment by Araq** [comment]
> should I put changelog entry into /changelog.md?

Yes.
