### ISSUE TITLE
Illegal storage access when adding to a ref seq

### ISSUE THREAD

**Issue by b3liever** [nim-lang/Nim#11065]
This crash happens with `--newruntime`

### Example

```nim
type
   Warm = seq[string]

var w: Warm
w = @["red", "yellow", "orange"]

w.add("pink")
echo w
```

### Current Output
```
Traceback (most recent call last)
alias.nim(10)            alias
system.nim(2006)         add
alloc.nim(953)           realloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
### Additional Information

- Tried to use a main proc, same result.

```
$ nim -v
git hash: 44ec66bd484e7cf952c20493a30cf1b29d49e3ca
```

**Comment by Araq** [comment]
Yeah, I know, we need to copy seq literals properly. :-)

**Comment by b3liever** [comment]
Oh sorry, I thought it was genuinely a bug, not a missing implementation.

**Comment by Araq** [comment]
It was indeed something else, thanks for reporting!
