### ISSUE TITLE
Expose nameToCodePage/codePageToName to public

### ISSUE THREAD

**Issue by Guevara-chan** [nim-lang/Nim#11068]
### Summary
I guess, 2 *s would be enough.

### Description
So far, codePageToName and nameToCodePage were set as private in `encodings.nim`, forcing me to manually extract their sourcecode as separate nanolib. 

Why ? Because Windows terminal is all about it's own separate CPs, of course.

### Alternatives
Making terminal in Windows to understand default Utf-8 out-of-box without codepaging dances would be nice as well.

**Comment by Bennyelg** [comment]
@mratsim , Merged can be closed.

**Comment by Nindaleth** [comment]
The related PR is #11218
