### ISSUE TITLE
Trying to use newStringStream results in 'undeclared identifier'

### ISSUE THREAD

**Issue by Zireael07** [nim-lang/Nim#11066]
I am not able to use the newStringStream() function from streams module (stdlib), whether by itself or as part of the marshal library.

### Example
```nim
import streams
var test = newStringStream("")
echo test

```

### Current Output
```
Error: undeclared identifier: 'newStringStream'
```

### Expected Output
 It should just work, especially where marshal module is concerned.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4
```

**Comment by Araq** [comment]
No, you need to use ``import streams`` and learn the very basics of Nim.

**Comment by Zireael07** [comment]
I use import streams, and the problem also happens when trying to use $$ in marshal library.

**Comment by Zireael07** [comment]
Ah, wait, some more googling points to streams not working in JS target?

**Comment by Zireael07** [comment]
I no longer use Nim, but thanks for fixing the issue <3

**Comment by Araq** [comment]
Well you should use Nim. ;-)
