### ISSUE TITLE
and 'sink' is for parameters, not for variables. 

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#11072]
Araq, you wrote in

https://irclogs.nim-lang.org/21-04-2019.html#07:56:39

>07:56:39 | Araq | and 'sink' is for parameters, not for variables.

But from

https://github.com/nim-lang/Nim/wiki/Destructors

we have

```
sink T is also a valid type for locals. For a variable v of type sink T no destructor call is injected and it is statically ensured that every code path leads to its consumption.
```

```
Like sink T lent T is a valid annotation for local variables too. For a variable v of type lent T it is statically ensured that no code path leads to its consumption,
```

That is a bit confusing, I was wondering how sink and lent is applied to local variables...

**Comment by Araq** [comment]
I've updated the wiki page and soon the manual will contain the final version of the destructors spec.
