### ISSUE TITLE
Feature request: Make it easier to reduce possible enum returns from libraries

### ISSUE THREAD

**Issue by jrfondren** [nim-lang/Nim#11086]
The practical example is the `parseopt.getopt` iterator. All code using this iterator will have a completely pointless `cmdEnd` case. The requirement for that case could be removed by updating `parseopt.getopt` to return a range of enums, instead. However, this improvement will break all code that uses `parseopt.getopt`.

Here's a similar toy example:

```nim
type
  Dirs = enum
    Up, Down, North, East, West, South
  Dirs2d = range[North .. South]

proc get2d(n: int): Dirs =
  case n and 3
  of 0: return North
  of 1: return East
  of 2: return West
  of 3: return South
  else: assert(false)

proc user(n: int) =
  case get2d(n)
  of North, East, South, West: echo "2d dir" & $get2d(n)
  of Up, Down: assert(false)

for i in 1 .. 10:
  user(i)
```

`get2d` returns a `Dirs` which requires its callers to have a dummy of-block for the 3d values that will never be seen. There is a Dirs2d that could be used, but `get2d` without also updating `user` results in this error:

```
range_enum.nim(15, 3) Error: not all cases are covered
```

Which is also a deceptive error: the problem is actually that it's testing cases outside the new range. There are no cases that could be added that would make this message go away.

I suggest that the "test too many cases" error-case be changed to a warning, with its own message. This would allow improvements to start at `get2d` (or `parseopt.getopt`) and then gradually also improve calling code, without breaking it outright.

**Comment by Araq** [comment]
-1 from me, I like exhaustive case statements and enjoy the compiler's error messages.

**Comment by jrfondren** [comment]
@Araq Fair enough. My thought was that moves towards greater precision should be treated more gently than moves towards less precision, but actually that might be a prejudicial way to describe a change in the number of possible enums from a return. It works for removing the cmdEnd non-return from getopt, but there's no guarantee that'll describe every situation.
