### ISSUE TITLE
DateTime field on Exception produces inconsistent C/++ handling

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#11081]
Admittedly, I'm a novice and may be missing something, but I'm finding this hard to reason about...

```nim
import times

type
        MyError = object of Exception
                clock: DateTime

try:
        var foo = newException(MyError, "")
        #foo.clock = now()
        raise foo
except MyError:
        echo "error"
except Exception:
        echo "exception"
except:
        echo "default"
```

When compiled with `nim c`, it yields `error`.
When compiled with `nim cpp`, it segfaults.
When compiled with `nim cpp --noCppExceptions`, it yields `default`.

Assigning the value to `clock` has no impact, but change `clock` from a `DateTime` to, say, a `string`, and all is well in the world -- all three compilations yield `error` when run.

This is devel on Linux.

**Comment by disruptek** [comment]
Problem remains as of
```
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-03
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 0718d6c2cddac89256e2fcde17407f1685f1a457
active boot switches: -d:release
```

**Comment by awr1** [comment]
Issue is related to inheritance.

```nim

type Foo* = object of RootObj

type
  MyError = object of Exception
    xyz: Foo

try:
  var foo = newException(MyError, "")
  raise foo
except MyError:
  echo "error"
except Exception:
  echo "exception"
except:
  echo "default"
```

gives the same result.

**Comment by Araq** [comment]
Will be fixed by https://github.com/nim-lang/Nim/pull/13065

**Comment by disruptek** [comment]
Another bug squashed!  Thanks!
