### ISSUE TITLE
strformat float printing doesn't print ".0" portion [regression]

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11089]
Earlier strformat printed a float *1.0* as `"1.0"`. Now it prints just `"1"`.

It was nice to have that ".0" portion printed that gave a clarity that the value being printed was a float.

### Example

```nim
import strformat

let
  foo: float = 1.0
  bar: float = 1.5
echo fmt"{foo}" # Prints "1" -- bad
echo fmt"{bar}" # Prints "1.5" -- good
```

### Current Output
```
1
1.5
```

### Expected Output

```
1.0
1.5
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-22
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 4f9366975441be889a8cd4fbfb4e41f6830dc542
active boot switches: -d:release
```

/cc @Araq @krux02 

---

I discovered as I was rerunning all the snippets in my Nim notes with the latest devel. `git diff` highlighted all the missing ".0"'s:

![image](https://user-images.githubusercontent.com/3578197/56536691-a4d68780-652c-11e9-8f77-d970b54b7f3b.png)

**Comment by Araq** [comment]
This was never explicitly in the program though as far as I know. Did your libc change?

**Comment by kaushalmodi** [comment]
Hmm, I definitely haven't updated my libc (glibc that ships with the OS, right?). My OS version is still RHEL 6.8. 

Are you not able to reproduce the same ".0" truncation?

**Comment by kaushalmodi** [comment]
@Araq The regression of this behavior from stable to devel was confirmed on IRC. 

Ref: https://irclogs.nim-lang.org/23-04-2019.html#07:01:10

**Comment by kaushalmodi** [comment]
If it helps trace down this problem, in my git diff, I had also noticed the resolution reduction when printing floats in general too. Printing *1.23456789* printed something like *1.23456*  instead. I can share the exact examples when I get to my PC.

**Comment by kaushalmodi** [comment]
@Araq Thank you for that quick fix! As I was past this regression fixes and evaluating other blocks in my notes, I ended up with https://github.com/nim-lang/Nim/issues/11092.
