### ISSUE TITLE
for loop is miscompiled into infinite loop given 0 ..< 0, with unsigned ints

### ISSUE THREAD

**Issue by jrfondren** [nim-lang/Nim#11099]
The following code throws an OverflowError at runtime when compiled without -d:release.
With -d:release, the for loop becomes an infinite loop. This is observed in 0.19.4 and in devel.

I don't know about what should happen normally ("nothing" is probably the more user friendly outcome, with the user free to write a while loop if he really wants the "FFFF_FFFF iterations" outcome), but an infinite loop definitely seems like a bad result.

### Example
```nim
var
  x: uint32
  y: float
for i in 0 ..< x:
  if i == 1: echo i
  y += 1
echo y
```

### Current Output
```
1
1
.
.
.
```

**Comment by Araq** [comment]
It should just work and iterate 0 times. system.nim bug, I doubt it's hard to fix?

**Comment by jrfondren** [comment]
Aye, it looks like it's hitting 

```nim
template `..<`*(a, b: untyped): untyped =
  a .. (when b is BackwardsIndex: succ(b) else: pred(b))
```

It this is still open by the weekend I'll submit a PR.

**Comment by krux02** [comment]
I tested to compile the snippit when the template `..<` doesn't exist in system.nim and this is the error:

```nim
scratch.nim(15, 12) Error: type mismatch: got <int literal(0), uint32>
but expected one of: 
iterator `..<`[T](a, b: T): T
  first type mismatch at position: 2
  required type: T
  but expression 'x' is of type: uint32

expression: 0 ..< x
```

Here are the alternatives that work without compilation errer:

```nim
for i in 0'u32 ..< x:
  [...]

for i in typeof(x)(0) ..< x:
  [...]
```

It is still an annoything problem that the above template overload is picked.

**Comment by krux02** [comment]
I am preparing a pull request that converts this bug into the following error message:

```
scratch.nim(15, 12) Error: type mismatch: got <int literal(0), uint32>
but expected one of: 
template `..<`[T](a, b: T): untyped
  first type mismatch at position: 2
  required type: T: not BackwardsIndex
  but expression 'x' is of type: uint32
iterator `..<`[T](a, b: T): T
  first type mismatch at position: 2
  required type: T
  but expression 'x' is of type: uint32
template `..<`[T](a: T; b: BackwardsIndex): untyped
  first type mismatch at position: 2
  required type: BackwardsIndex
  but expression 'x' is of type: uint32

expression: 0 ..< x
```

This is still not perfect, as the error message says that it needs type ``T`` (what is `T`?). But at least it doesn't crash or generate invalid code anymore.

**Comment by jrfondren** [comment]
(I thought it'd be called `dotdotRoofImpl` though)
