### ISSUE TITLE
newSeqOfCap is not working in newruntime

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11098]
The following example doesn't compile with `--newruntime`:
```nim
var s = newSeqOfCap[int](10)
echo s.len
```
I have tried to implement it myself, but realised that ` newSeqPayload`  from `seqs.nim`` will not for this case.

Possible ways forward:
1. Add to system.nim  `proc newSeqOfCap*[T](s: var seq[T], cap: Natural)` and make it a magic instead of  `proc newSeqOfCap*[T](cap: Natural): seq[T]` just like it is done for `newSeq`. Will allow a sequences to be created in a unified way.
2. Add new proc to `seqs.nim` just to implement `newSeqOfCap`.

Araq,
do you have a preference?

**Comment by Araq** [comment]
can't we have  a magic  ``proc newSeq[T](len, cap: Natural): seq[T]`` instead and clean up this mess?

**Comment by mratsim** [comment]
Note that I'm heavily relying on newSeqOfCap not zero-ing memory for trivial types (`typetraits.supportsCopyMem`) so if we have this overload `proc newSeq[T](len, cap: Natural): seq[T]`, I hope it doesn't zero memory between [len, cap], i.e. if len = 0, we get the raw seq.

**Comment by Araq** [comment]
> I hope it doesn't zero memory between [len, cap], i.e. if len = 0, we get the raw seq.

Uh oh, ``emplace_back`` here we come...
