### ISSUE TITLE
tyOwned can break type instantiation in old runtime

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11096]
Usage of `owned ref` can cause type instantiation in proc to fail in old runtime.
I will provide a PR to demonstrate the problem.

**Comment by cooldome** [comment]
Test case in PR: https://github.com/nim-lang/Nim/pull/11097

**Comment by andreaferretti** [comment]
> Usage of owned ref can cause type instantiation in proc to fail in old runtime.

Uh? Aren't owned refs just a [proposal](https://github.com/nim-lang/RFCs/issues/144) for now?

**Comment by cooldome** [comment]
IMO, owned refs are noop under old runtime.

**Comment by Clyybber** [comment]
@andreaferretti You can test the current implementation of the proposal with the --newruntime switch.

**Comment by cooldome** [comment]
I have tried investigating myself with little success. There is no newruntime specific logic in sigmatch and  semtypeist as far as I can tell. Not sure we're to look at. 
@Araq, please help

**Comment by Araq** [comment]
Well I think older Nims do not like ``template owned(t) = t`` for types?

**Comment by cooldome** [comment]
@Araq, thanks for fixing this issue
