### ISSUE TITLE
latest nim behaves differently/wrong than 0.19.2 

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#11093]
I suspect that it is caused by the faked fix in https://github.com/nim-lang/Nim/issues/10842#issuecomment-485360498

https://github.com/nim-lang/Nim/issues/10842#issuecomment-485360498 is closed, now the latest-cloned-built nim can compile the buggy demos I reported. But

1. for `demo.nim` and `autolayout\demo.nim`, if I click `Page2` of the notebook, `demo.exe` crashes and says
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'R:\khchen-wNim\examples\demo.exe '
``` 
But I can click `Page1` and `Page3` without crash

2. for `pickicondialog.nim`, no icons are drawn after I select one

3. for `tictactoe.nim`, `reversi.nim` and `scribble.nim`, no canvas (i.e. MemoryDC) is shown, so nothing is displayed. 

I think case 2 and 3 are the same one

BTW, is nim waiting for, or undergoing, a dramatic changes? Or nim finds it is self-contradictory and is going to aestivation for a long time?

**Comment by Araq** [comment]
> BTW, is nim waiting for, or undergoing, a dramatic changes? Or nim finds it is self-contradictory and is going to aestivation for a long time?

No and no. It's however the ``devel`` branch. Also, who knows if your code was correct to begin with, maybe you got lucky and it didn't crash and now it does.

**Comment by Araq** [comment]
Works for me if I add some checks like `` self.mPen != nil `` to wDC.nim. And in the end it dies because you iterate over the seq while also calling ``delete`` in it. These do not seem to be Nim bugs to me, but your bugs.
