### ISSUE TITLE
`except Exception as e: raise e` cannot be excepted.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#11118]
On the C++ backend, excepting an Exception as e, and then raising it, can not be caught by calling functions.

```nim
proc raises() =
    raise newException(ValueError, "Raising a ValueError")

proc raises2() =
    try:
        raises()
    except ValueError as e:
        echo "Triggered raises2 except."
        raise e

try:
    raises2()
except ValueError as e:
    echo "Triggered the main body's except."
    raise e
```

### Current Output
```
Triggered raises2 except.
```

### Expected Output
```
Triggered raises2 except.
Triggered the main body's except.
*crash*
```

This bug occurs on both Nim 0.19.4 and a devel compiled at the time of this bug report, The C backend works as expected.

As a side note, while no except branches are triggered, the code after the try/except isn't called either. A hang occurs.

**Comment by kayabaNerve** [comment]
Instead of using `raise e`, `raise newException(ValueError, e.msg)` is a valid workaround.

**Comment by kayabaNerve** [comment]
```cpp
catch (tyObject_ValueError_5aqBlilCK53e9cDu4kUyN5Q& caught) {
        Exception* T3_;
        setFrame(_nimCurFrame);
        T3_ = (Exception*) 0;
        T3_ = getCurrentException();
        tyObject_ValueError_5aqBlilCK53e9cDu4kUyN5Q* e = ((tyObject_ValueError_5aqBlilCK53e9cDu4kUyN5Q*) (T3_));
        echoBinSafe(TM_WX9c4deQnVN6K28HqUzXf2A_3, 1);
        raiseException((Exception*) e, "ValueError");
}
```

Manually editing the catch statement to include a variable name, and then raising the casted address of said variable works, although I don't know the wider implications of that.

**Comment by cooldome** [comment]
Correct workaround is to use `raise` without argument to reraise exception. It correctly extends the lifetime of Exception object. I will have a look for a fix

**Comment by kayabaNerve** [comment]
I'd like to clarify there is a valid reason for using `raise e` instead of `raise`, and that this isn't just a problem with a meaningless replacement of a language built in. `raise`, inside a proc with a raises pragma, causes the following error: `Error: can raise an unlisted exception:`. Adding ReraiseError doesn't remove it, yet adding Exception does, yet Exception makes the raises pragma meaningless.

**Comment by cooldome** [comment]
Found a reasonable two line fix for this one, I'll prepare a PR soon
