### ISSUE TITLE
Incorrect error message "paramCount is not implemented on Nintendo Switch" in nimscript

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#11120]
NimScript is treated as "weirdTarget" in https://github.com/nim-lang/Nim/blob/b350a9fc52d67cabc778887d8f81d0332eb9db91/lib/pure/os.nim#L2529 leading to an incorrect error message  "paramCount is not implemented on Nintendo Switch"

```
#!/usr/bin/env nim                    
import os     
echo commandLineParams()     
```

**Comment by Araq** [comment]
What's wrong with that error message? It's not available on Nintendo Switch.

**Comment by FedericoCeratto** [comment]
I was running a Nim script (not on a Nintendo Switch) and the elif in line 2529 is satisfied by the `or weirdTarget` on the right.

**Comment by Araq** [comment]
Ah! Ok.

**Comment by metagn** [comment]
This error is no longer raised in nimscript, but still is on JS. Minor refactoring issue.

**Comment by timotheecour** [comment]
as mentioned in https://github.com/nim-lang/Nim/pull/17009#issuecomment-778506113, shall we raise a defect instead or OsError? AssertionDefect or NotImplementedDefect
