### ISSUE TITLE
Arithmetic tests are expecting the wrong result. VM int32, int64, uint64 evaluation does not match runtime.

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#11138]
Test in tarithm.nim fails on armv6 and armv7 but passes on arm64.

https://github.com/nim-lang/Nim/blob/devel/tests/arithm/tarithm.nim#L129

Expected value is 1 but actual is 0. Tested 1 << 32 on a real RPi and it is 0 there as well. Seems like the test needs to be updated.

**Comment by mratsim** [comment]
The tests are completely wrong and linked to VM bug https://github.com/nim-lang/Nim/issues/9572.

Forcing runtime evaluation, we should get all 0:

```Nim
proc doShl(T: typedesc[SomeSignedInt], shift: int): T =
    1.T shl shift

block:
  let t0 = doShl(int8, 8)
  let t1 = doShl(int16, 16)
  let t2 = doShl(int32, 32)
  let t3 = doShl(int64, 64)
  echo t0
  echo t1
  echo t2
  echo t3
```

**Comment by krux02** [comment]
To be honest, I don't understand these tests. Bitshifting these amount of bits in C is undefined behavior. Since the `shl` is basically a wrapper for the C bitshifting operator, I don't get why these tests have been written in this way. Neither do I understand the logic behind them, nor do I have any clue on how we can ensure these results in the future.

**Comment by Araq** [comment]
Maybe because Nim is not C and it's defined behavior in Nim? Wasn't that hard to figure it out, was it...

**Comment by genotrance** [comment]
Well the results are inconsistent and blocking megatest on arm nightlies. Please suggest a fix - either when arm or removing these overflow bit-shift tests altogether.

**Comment by jangko** [comment]
Looks like the behavior is architecture dependent, see: [stackoverflow](https://stackoverflow.com/questions/3871650/gcc-left-shift-overflow).

If that is the case, the tests are tied to specific architecture. 

If we want to make VM and runtime produce the same result, we should not let it have undefined behavior as in C, but should define the behavior for both VM and runtime in case of shift overflow.

**Comment by krux02** [comment]
The tests in discussion have been removed by new, because they were incorrect.
