### ISSUE TITLE
re: memory leak when calling re proc repeatedly

### ISSUE THREAD

**Issue by Jjp137** [nim-lang/Nim#11139]
When calling the `re` proc repeatedly, as shown in the examples below, memory usage increases continuously.

Yes, it may be better not to do this, but it's easy to casually specify a regular expression literal as an argument to the various procs within the `re` module, so the memory leak can be surprising.

### Examples
```nim
import re

while true:  # Stop with Ctrl+C
  discard findAll("", re"[a-z]")
```

...and also:
```nim
import re

proc test() =
  let regex = re"[a-z]"
  discard findAll("", regex)

while true:  # Stop with Ctrl+C
  test()
```

### Workaround
Declaring the regex outside any loops entirely, such as within a global variable, and then using that instead does not noticeably leak memory, such as in this example:
```nim
import re

let regex = re"[a-z]"

while true:
  discard findAll("", regex)
```

### Additional Information

Output of `nim -v`:
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-28
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 55aa2129b5b32c0bb9862c66d3ebbd681f727274
active boot switches: -d:release
```

Also occurs with 0.19.4.

**Comment by narimiran** [comment]
Workaround: `import nre` instead, no memory leaks for the two original leaking examples.
