### ISSUE TITLE
Inheritance doesn't work with var ref objects as proc parameters

### ISSUE THREAD

**Issue by liquid600pgm** [nim-lang/Nim#11136]
When one has two objects, `A = ref object of RootObj`, and `B = ref object of A`, and passes a `var B` to a proc that expects `var A`, the compiler reports a type mismatch, and a type conversion is required.

### Example
```nim
type
  A = ref object of RootObj
  B = ref object of A

proc init(a: var A) =
  discard

var b = B()
b.init() # error
b.A.init() # OK
```

### Current Output

See example.

### Expected Output

The call should not need any extra conversions.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-13
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by bluenote10** [comment]
I think this is by design, see the [Covariance section in the manual](https://nim-lang.org/docs/manual.html#type-relations-covariance)

> The introduction of a var modifier or additional ptr or ref indirections would result in invariant treatment of these types.

**Comment by krux02** [comment]
Yes this should not work, it is by design. Look at the following example:

```nim


type
  A = ref object of RootObj
  B = ref object of A
  C = ref object of A

let myC: C = new(C)

proc init(a: var A) =
  a = myC

var b = B()
b.init() # error, because you cannot assign a value of type C to a variable of type B
```

**Comment by Clyybber** [comment]
@krux02 @bluenote10 Afaict this is not about covariance though, but about inheritance and thus I belive this is supposed to work according to https://nim-lang.org/docs/manual.html#type-relations-subtype-relation

**Comment by Araq** [comment]
Works as designed. Otherwise this would compile and crash

```nim

type
  A = ref object of RootObj
  B = ref object of A
    field: string

proc init(a: var A) =
  a = A()

var b = B()
b.init() 
echo b.field

```
