### ISSUE TITLE
Gen'ing of types with CPP backend replicates object hierarchy per module

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#11137]
With the CPP backend each backend file gets a copy of the entire object hierarchy instead of sharing types.

For example, if `A.nim` has:

```
type
   A* = object of RootObj
     a*: int

```

and `B.nim` has:

```
import A

type
  B* = object of A
    b*: int

echo B(b:99)
```

The CPP backend generates in `A.cpp`:
```
struct RootObj {
  TNimType* m_type;
};
struct tyObject_A_zG9biHVqrAgAHGws9b5adT9cQ : public RootObj {
  NI a;
};
```

and in `B.cpp`:
```
struct RootObj {
  TNimType* m_type;
};
struct tyObject_A_zG9biHVqrAgAHGws9b5adT9cQ : public RootObj {
  NI a;
};
struct tyObject_B_HKWOeFwm20LrOvFg3UomCA : public tyObject_A_zG9biHVqrAgAHGws9b5adT9cQ {
  NI b;
};
```

which is an entire copy of the hierarchy.

By pure chance methods called on `B` objects passed to methods in `A.cpp` that expect an `A` seem to work out probably because vtable offsets match but types should really be shared via an include.

**Comment by cooldome** [comment]
IMO. Includes achieve exactly what Nim does for you: copy&pasting of class declarations from file to file. I see zero benefit in introducing cpp header files, it will only slow down compilation. 

IMO, it works as expected no issues found.

**Comment by Araq** [comment]
Sorry but Nim is not a header file generator.
