### ISSUE TITLE
`$` cant be accessed properly for object created from other modules

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#11155]
Function `echo` outputs the wrong string.

### Example
`a.nim`
```nim
import tables

proc get*: Table[int, int] = initTable[int, int](2)

echo get()
```

`b.nim`
```nim
import a

echo get()
```

### Current Output
```
{:}
(data: @[(hcode: 0, key: 0, val: 0), (hcode: 0, key: 0, val: 0)], counter: 0)
```

### Expected Output
```
{:}
{:}
```

### Additional Information
Changing `a.nim` to
```nim
import tables

proc get*: TableRef[int, int] = newTable[int, int](2)

echo get()
```
makes the compilation fail with `b.nim(3, 9) Error: type mismatch: got <TableRef[system.int, system.int]>`

Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-01
git hash: c94ab46923852d2eb96eab5e518d392b0d705fce

**Comment by krux02** [comment]
Well, it actually is correct. Module `b` does not import ``tables.`$` `` nor does module `a` export ``tables.`$` ``. Therefor the overload resolution for `$` in module b cannot see ``tables.`$` `` and therefore it isn't picked.

You have to either export tables.`$` in module `a` or you need to import ``tables.`$` `` in module `b`. You can of course also do both:

`a.nim`
```nim
import tables
export tables.`$`

proc get*: Table[int, int] = initTable[int, int](2)

echo get()
```
`b.nim`
```nim
import a
from tables import `$`

echo get()
```

**Comment by SolitudeSF** [comment]
ah, true. dont know why did this throw me off.
