### ISSUE TITLE
Escaping the quote op doesn't seem to work

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#11151]
My interpretation of the [quote docstring](https://nim-lang.org/docs/macros.html#quote%2Ctyped%2Cstring) is that doubling up the quote op should escape it, i.e., I expected the following to work:

### Example

```nim
import macros

static:
  let node = quote:
    ``+``(a, b)
```

### Current Output
```
test.nim(5, 6) Error: identifier expected, but got '`'
```

### Expected Output

Should compile.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-13
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f6ad071a46a2bec57db453343d8d8b75d3d16ac2
active boot switches: -d:release
```

**Comment by bluenote10** [comment]
Hm, maybe I don't have to double up the backticks? What I'm actually trying to achieve is passing an AST involving backticks to a compile time proc:

```nim
proc test(n: NimNode) =
  echo n.treeRepr

static:
  test:
    quote:
      `+`(a, b)
```
which errors with `test.nim(13, 8) Error: cannot generate VM code for +` but works fine as long as the AST doesn't contain backticks.

On the other hand I noticed that this works in general:

```nim
import macros

dumpTree:
  quote:
    `+`(a, b)
```

**Comment by mratsim** [comment]
Duplicate: https://github.com/nim-lang/Nim/issues/7589

See also RFC: https://github.com/nim-lang/RFCs/issues/122
and PR: https://github.com/nim-lang/Nim/pull/10446
