### ISSUE TITLE
compiler generates js files

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#11193]
I don't know where these files come from, but the they keep reappearing in my folders. They are not in any gitignore. Deleting them is pointless as they are regenerated constantly.

```
Untracked files (5)
lib/pure/json.js
lib/pure/logging.js
lib/pure/random.js
lib/pure/strutils.js
lib/pure/times.js
```

The question is, are there just missing in gitignore or is the fact that they get generated a bug?

**Comment by Clyybber** [comment]
I think they are generated somewhere in testament, when it tests the js backend I guess.

**Comment by krux02** [comment]
is resolved by now
