### ISSUE TITLE
New module names break file-specific flags

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11202]
For SIMD vectorization I need to pass [file-specific compilation flags](https://github.com/numforge/laser/blob/3c3c6f526d877cb8fdb7c8bf6e0f0867259e6a42/nim.cfg#L18-L37) so that I can handle multiple architecture with the same binary.

However with the new changes I can't compile anymore because the naming changed.
What are the new rules for the names?

![image](https://user-images.githubusercontent.com/22738317/57394298-6e079f00-71c5-11e9-8c92-f280461ee469.png)

This is related to #11196 and https://github.com/nim-lang/Nim/commit/0121dda9ba903b764cbd234667cc03f79ebadf44

By the way, the ability to pass per-file compilation flag would be very useful because everyone would have to copy my nim.cfg otherwise.

**Comment by alaviss** [comment]
> By the way, the ability to pass per-file compilation flag would be very useful because everyone would have to copy my nim.cfg otherwise.

Does the `{.passC.}` pragma not work?
