### ISSUE TITLE
Newruntime: assignment to discriminant field in case objects not supported

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11205]
Test case:

```nim
type
  MyEnum = enum
    A, B, C
  MyCaseObject = object
    case kind: MyEnum
    of A: iseq: seq[int]
    of B: fseq: seq[float]
    of C: str: string


var x = MyCaseObject()
x.iseq.add 1
x.kind = B
x.fseq.add -3.0
```
`nim c --newruntime rt2.nim` fails with 
```
   Error: system module needs: FieldDiscriminantCheck`
```

The issue is more fundamental then it seems. Descriminator field assignments are quite widespread even in stdlib hence can't be forbidden. Such assignment needs destructor call or even more accurately subdestructor call. Subdestructor will destroy only branches of the union part of the object.

Looks like liftdestructor needs to generate extra destructor for the case field in the object. These destructors are field sym bound and not type bound which makes it difficult. Inject destructor needs to call them on descriminator assignments.

The good news once it is done, existing issues with object variants will be resolved.

@Araq: Possibly you have better ideas?

**Comment by Araq** [comment]
I would disallow assignments that trigger an object branch switch. :-) I consider it a messy legacy that is not even completely memorysafe.

**Comment by zevv** [comment]
The manual already states "The new value must not lead to a change of the active object branch. For an object branch switch `system.reset` has to be used".

**Comment by cooldome** [comment]
The problem is that example above comes from stdlib. Check for example https://github.com/nim-lang/Nim/blob/devel/lib/pure/json.nim: descriminator assignment happens 20+ times.

Manual doesn't mention actively used loophole: descriminant value of zero is treated differently.

@Araq,
Do you plan close the loophole and change all the libraries that is currently using it? It is quite a few.
All serialisation libraries will need to be rewritten for example.

**Comment by krux02** [comment]
In my opinion that code example is supposed to crash, even on the old runtime. The only question is how it should crash.

@cooldome Yes the descriminator is assigned many times, but the difference is, it isn't assigned after it's members have been assigned.

**Comment by Araq** [comment]
> Do you plan close the loophole and change all the libraries that is currently using it? It is quite a few.
All serialisation libraries will need to be rewritten for example.

Yeah, the serialisation problem is a big issue which I have no good solution for. 

That said, `FieldDiscriminantCheck` needs to be implemented for --newruntime but shouldn't rely on the old RTTI which doesn't exist for the new runtime anymore.
