### ISSUE TITLE
Parser issue when blank line between doc comments

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11209]
Surprisingly the following doesn't compile and doesn't seem to have been caught

```Nim
type
  Foo = object
    ## First line

    ## Space it out
    foo: int
```

`Error: identifier expected, but got 'Space it out'`

**Comment by Araq** [comment]
We already have 2 ways to write multi-line doc comments (with backslash and with ``##[]##``, we don't need a 3rd.
