### ISSUE TITLE
Initialization of types with conditional fields (nkRecWhen) differs in const and non-const contexts

### ISSUE THREAD

**Issue by linkmonitor** [nim-lang/Nim#11226]
I made a toy Point[] type, after seeing issue #7569, which is parameterized by a static[int] representing dimension.

The output from echoing instances of that type differs when the instance is const and non-const.

### Example
```nim
type
  Point[T; dim:static[int]] = object
    when dim >= 1: x:T
    when dim >= 2: y:T
    when dim >= 3: z:T

proc main =
  let a = Point[int,2](x:1, y:2)
  echo a

  const b = Point[int,2](x:1, y:2)
  echo b

when isMainModule:
  main()
```

### Current Output
```
(x: 1, y: 2)
(x: 2, y: 0)
```

### Expected Output
```
(x: 1, y: 2)
(x: 1, y: 2)
```

### Additional Information
Output of `nim -v` is

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-10
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

My Nim executable was built ~30 minutes before posting this issue, using choosenim update on the devel channel.

**Comment by mratsim** [comment]
This is not static related, just the VM being buggy with initialization, especially conditionals, like https://github.com/nim-lang/Nim/issues/7569, https://github.com/nim-lang/Nim/issues/8015, https://github.com/nim-lang/Nim/issues/9622

```Nim
type
  Point[T] = object
    when sizeof(T) >= 2: x:T
    when sizeof(T) >= 4: y:T
    when sizeof(T) >= 8: z:T

proc main =
  let a = Point[int32](x:1, y:2)
  echo a

  const b = Point[int32](x:1, y:2)
  echo b

when isMainModule:
  main()
```

**Comment by krux02** [comment]
I would like to point out that there is exists something like https://github.com/stavenko/nim-glm

**Comment by narimiran** [comment]
I've run the original example with the latest Nim and it produces the expected result.

@linkmonitor can you confirm this is solved?

**Comment by linkmonitor** [comment]
Works on my end; confirmed solved.
