### ISSUE TITLE
Newruntime: Shared closure environments are destroyed multiple times

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#11253]
The following crashes when run with `--newruntime`:
```nim
proc test(): tuple[a, b: owned proc()] =
  
  var i = 0

  result.a = proc() =
    inc i
    echo i

  result.b = proc() =
    inc i
    echo i

let (a, b) = test()
a()
b()

```
Output:
```
1
2
Traceback (most recent call last)
test.nim(15)           test11
runtime_v2.nim(81)       nimDestroyAndDispose
runtime_v2.nim(71)       nimRawDispose
alloc.nim(945)           dealloc
alloc.nim(860)           rawDealloc
avltree.nim(74)          del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
The environment is destroyed twice since its owned by both closures.
I suppose for shared environments some trivial form of ref-counting is still needed?

**Comment by Araq** [comment]
> I suppose for shared environments some trivial form of ref-counting is still needed?

I'm afraid instead should not compile. :-)

**Comment by Araq** [comment]
Now fails with:

> temp3.nim(14, 7) Error: '=' is not available for type <owned ref object>; requires a copy because it's not the last read of ':env'; another read is done here: temp3.nim(14, 7)

which is good enough ... for now.
