### ISSUE TITLE
Internal error: invalid kind for lastOrd(tyEmpty) when returning an empty set after echo

### ISSUE THREAD

**Issue by pgkos** [nim-lang/Nim#11259]
The following example fails to compile on both 0.19.4 and devel:

### Example
```nim
proc foo(): set[char] =
  echo "a"
  {}

discard foo()
```
### Current Output
```
Error: internal error: invalid kind for lastOrd(tyEmpty)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```
### Expected Output
No error.

### Additional Information
Removing the echo makes the example compile successfully.

**Comment by mratsim** [comment]
Note that this only happens when implicitly returning the last expression. Using `return` of `result` works.

Importantly, it also crashes for templates which have no result/return workaround
