### ISSUE TITLE
[request] Add removeDir, removeFile, etc. to nimscript

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#11262]
Given that we want NimScript to be [a more viable build tool](https://nim-lang.org/docs/nims.html), adding these procs would be greatly appreciated, especially for implementing "clean" tasks.

**Comment by kaushalmodi** [comment]
[`rmDir`][1] and `rmFile` already exist.

[1]: https://nim-lang.org/docs/nimscript.html#rmDir%2Cstring

**Comment by awr1** [comment]
hm, wasn't aware of this.
