### ISSUE TITLE
Shuffling algorithm produces biaised permutation

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11269]
The shuffling algorithm in the standard library is biaised and does not produce evenly distributed permutations.

https://github.com/nim-lang/Nim/blob/f1a8edc14dd861674d40c88261ea77338a5fd5dd/lib/pure/random.nim#L567-L580

It should implement an unbiaised pseudo-random permutation algorithm instead, here are some propositions:

- [Fisher-Yates](https://en.wikipedia.org/wiki/Fisher–Yates_shuffle)
- [Thorp shuffle](https://web.cs.ucdavis.edu/~rogaway/papers/thorp.pdf)
- [Feistel shuffle](https://arxiv.org/pdf/1703.08306.pdf)
- [Permutator Shuffle](https://www.iacr.org/archive/fse2007/45930457/45930457.pdf)
- [Swap-or-not](https://link.springer.com/content/pdf/10.1007%2F978-3-642-32009-5_1.pdf)

The most well known is Fisher-Yates, also often called Knuth Shuffle.

See in-depth explanations with demos:

- [How not to shuffle](https://www.i-programmer.info/programming/theory/2744-how-not-to-shuffle-the-kunth-fisher-yates-algorithm.html)
- [Randomness is hard](https://medium.com/@oldwestaction/randomness-is-hard-e085decbcbb2)

Here are implementations in Python of Fisher-Yates, Prime shuffling, Feistel Shuffling and Swap-or-not shuffling: https://github.com/ethereum/research/tree/260faf622ef5e8e84bda1258a9f98956baf72991/shuffling

**Comment by Araq** [comment]
I fail to see how the stdlib's implementation differs from what https://medium.com/@oldwestaction/randomness-is-hard describes

**Comment by narimiran** [comment]
I did a quick test of Nim's `shuffle` frequencies based on the article @Araq linked:

For the first test ("300k tries on a 4-item set"):
```
expected: 12500 (one in 24)
smallest: 12339 (one in 24)
largest: 12694 (one in 23)
```

For the second test ("1 million tries on a 6-item set"):
```
expected: 1388 (one in 720)
smallest: 1269 (one in 788)
largest: 1491 (one in 670)
```

Both examples show quite uniform distribution. Closing.
