### ISSUE TITLE
Can't pass openArray[char] to string parameter

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#11277]
Recently I tried to use the unicode module with `openArray` and found all functions accept a `string` instead of `openArray[char]`. IIRC, Araq said it would be possible to pass `openArray[char]` to a function taking a `string` parameter at some point. Is that the case?. Should I open a PR changing all string params to openArray[char] in the unicode module instead?

**Comment by mratsim** [comment]
Are you sure it's not pass string as openarray instead? String have custom handling and are always terminated with '\0' and can be passed to C `cstring` while an `openarray[char]` does not need to respect those requirements.

### Meta

The string/openarray matching rules are a bit confusing see https://github.com/nim-lang/RFCs/issues/70 (the meaning of strings):
- https://github.com/nim-lang/Nim/pull/2856 - string compatible with openarray[char]
- Issues when openarray[char] matching strings breaks libraries
  - Hashing/Tables and generic openarray[T]: https://github.com/nim-lang/Nim/issues/6350#issuecomment-328143713
  - Container[T] iterative and recursive proc relying on string not being transformed into chars: https://github.com/nim-lang/Nim/pull/6807

Also related
- StringLike concept: https://github.com/nim-lang/Nim/issues/9289

**Comment by nitely** [comment]
Hey mratsim, to illustrate I meant this:

```nim
proc strHandler(s: string) =
  echo s
strHandler("foo".toOpenArray(0, 1))
```

I'd expect the compiler to complain if `strHandler` does something not supported by `openArray` when passing an openArray. But I can see now how that would be problematic even if it worked. The code would break as soon as some operation not supported by openArray is made, without the library author realizing how that breaks others code. So, we need something that is always compatible with both string and openArray, and that would be `openArray[char]` I guess.

**Comment by Araq** [comment]
> Should I open a PR changing all string params to openArray[char] in the unicode module instead?

Yes.

**Comment by Araq** [comment]
PR exists, I'm closing this issue.
