### ISSUE TITLE
Passing code via stdin to Nim stopped working [regression Nim 0.19+]

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11294]
In Nim 0.18.0 and earlier, it was possible to pass it code via stdin. But the same method of passing code via stdin doesn't work in Nim 0.19.0+.

### Example

```
echo echo NimVersion | nim -r c -  
```

### Current Output

In Nim 0.19.0+, we get this error:

> command line(1, 2) Error: invalid command line option: '-'

### Expected Output

*Should print the value of `NimVersion`.*

### Additional Information

Ref: https://github.com/JRaspass/code-golf/issues/86#issuecomment-494376548

**Comment by kaushalmodi** [comment]
@Araq This issue is still not fixed for me.

```
> echo echo NimVersion | nim -r c -
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: stdinfile [Processing]
CC: stdinfile
Hint:  [Link]
collect2: fatal error: can't open nm output: Success
compilation terminated.
Error: execution of an external program failed: 'gcc   -o /home/kmodi/sandbox/nim/bug_reports/nim_doc__wrong_file_name_in_idx/-  /tmp/kmodi/.cache/nim/-_d/stdlib_io.c.o /tmp/kmodi/.cache/nim/-_d/stdlib_system.c.o /tmp/kmodi/.cache/nim/-_d/stdinfile.c.o  -lm   -ldl'
```

Looks like now the `echo echo NimVersion | nim -r c -` command creates a binary named `-` literally!

```
.rwxr-xr-x 85k kmodi 24 May 13:14 -*
```

**Comment by Araq** [comment]
Works on Windows and afaict it never worked better, so it's not a regression anymore, *shrug*.

**Comment by Clyybber** [comment]
You can always use `/dev/stdin` instead of `-`, though I think this should be supported properly still.

**Comment by kaushalmodi** [comment]
@timotheecour Thanks for your fix in https://github.com/nim-lang/Nim/commit/1f7c907e7d81ae454739a2db753661505a5ed3d6

Now it works!!

```
> echo echo NimVersion | nim -r --hints:off c -
1.1.1
```
