### ISSUE TITLE
nim doc: The value of "--out:" is not reflected in the idx file generated using "--index:on"

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11325]
When running `nim doc --out:foo.html --index:on t.nim", the value of "--out:" is not reflected in the idx file generated using "--index:on".

### Example

1. In any directory, create this `t.nim` file:
```nim
proc foo*() =
  ## I do foo
  echo "hello!"
```
2. Now generate its HTML doc + index:
```
nim doc --out:index.html --index:on t.nim
```
### Current Output

The `index.html` gets generated correctly. But the `t.idx` file still has references to `t.html` file (which got overridden to `index.html` using `--out:index.html`).

The `t.idx` looks like this:

```
foo	t.html#foo	t: foo()	
```

### Expected Output

The `t.idx` was expected to be:

```
foo	index.html#foo	t: foo()	
```

(because I overrode the generated HTML page name using `--out:index.html`.

### Workaround

For now, I need to run a `sed` command to fix the .idx file ([example][1]).

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: d67a9f024eeeb2bc26fb38a98be9a53956003290
active boot switches: -d:release
```

[1]: https://github.com/kaushalmodi/nim_config/blob/cc7509d1c6e479721fc811d50d68a8c5b87ea134/config.nims#L256

**Comment by Araq** [comment]
You should really use ``--outdir`` and stop messing with how Nim wants to do it.

**Comment by kaushalmodi** [comment]
I need the `--out:` to force the output specifically to `index.html` so that I can have cleaner URLs like https://kaushalmodi.github.io/elnim/.

Without the `--out:`, that URL would be https://kaushalmodi.github.io/elnim/elnim.html.
