### ISSUE TITLE
{.exportc.} broken (windows - any compiler)

### ISSUE THREAD

**Issue by sinkingsugar** [nim-lang/Nim#11334]
```
proc hello() {.exportc.} =
  echo "Hello exportc..."
```

`nim c --app:lib -o:dll.dll .\hello.nim`

check export section of dll: no hello...

**Comment by sinkingsugar** [comment]
this should be properly tested as it's quite critical,
hint:
```
dumpbin /exports "C:\....*path to your DLL*...."
```

**Comment by demotomohiro** [comment]
You need to add ``dynlib`` pragma.
https://nim-lang.github.io/Nim/manual.html#foreign-function-interface-dynlib-pragma-for-export

For example:
```nim
proc hello() {.exportc, dynlib.} =
  echo "Hello exportc..."
```

``Nim/tests/dll/client.nim`` and ``Nim/tests/dll/server.nim`` seems test code for ``dynlib`` pragma.

**Comment by sinkingsugar** [comment]
Hmm, good point.
Pretty sure this was not needed before cos this code used to work.
Thanks @demotomohiro !
