### ISSUE TITLE
Out of bounds access in CritBitTree

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#11344]
If the requested prefix is longer than a key, the library accesses past the end of string.  E.g.:
```nim
import critbits
var cb: CritBitTree[string]
cb.incl("help", "help")
for k in cb.keysWithPrefix("helpp"):
  echo k
```
### Current Output
```
critbits.nim(270)        cbBug
critbits.nim(256)        allprefixedAux
fatal.nim(39)            sysFatal
Error: unhandled exception: index 4 not in 0 .. 3 [IndexError]
```

### Expected Output
Should print nothing since "helpp" is not the prefix of any string in the CritBitTree.

### Possible Solution

Changing the offending line of code from 
```Nim
if p.key[i] != key[i]: return
```
to
```Nim
if i >= p.key.len or p.key[i] != key[i]: return
```
seems to work for me.  It may also be possible to do an earlier check of `p.key.len` vs `key.len` instead.

I believe this is a very old bug.

**Comment by Araq** [comment]
> I believe this is a very old bug.

Well it used to be no bug because of the zero termination, I think.

**Comment by c-blake** [comment]
Sounds plausible (former no bug-wise).  Thanks.
