### ISSUE TITLE
strutil.insertSep() fails on negative numbers

### ISSUE THREAD

**Issue by hiteshjasani** [nim-lang/Nim#11352]
Function `insertSep` outputs the wrong string.

### Example

```nim
insertSep($(-100), ',')
insertSep($(-100_000), ',')
```

### Current Output
```
-,100
-,100,000
```

### Expected Output

```
-100
-100,000
```

### Possible Solution

A couple options come to mind.  Don't know which fits better with the library, but placing separators in `ints` and `floats` is something done very often.

* Put in special case code in `insertSep` to handle the case when the first character is a minus sign.
* Create an overloaded proc of `insertSep(s: int): string` that handles the special case of negative numbers

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [MacOSX: amd64]
Compiled at 2019-05-21
```

**Comment by Araq** [comment]
I don't think ``insertSep`` which works on strings is the best solution for this. Maybe strformat.nim supports that? I don't remember... ;-)
