### ISSUE TITLE
sequtils delete behaviour differs from documentation

### ISSUE THREAD

**Issue by Stuffe** [nim-lang/Nim#11357]
When I run the following example from the documentation in 0.19.4 on osx or in the online playground I get an error

Documentation:
https://nim-lang.org/docs/sequtils.html#delete%2Cseq%5BT%5D%2CNatural%2CNatural

Example:
```
let outcome = @[1,1,1,1,1,1,1,1]
var dest = @[1,1,1,2,2,2,2,2,2,1,1,1,1,1]
dest.delete(3, 8)
assert outcome == dest
```

Error:
> Error: type mismatch: got <seq[int], int literal(3), int literal(8)>
> but expected one of: 
> proc delete(s: var string; first, last: int)
>   first type mismatch at position: 1
>   required type: var string
>   but expression 'dest' is of type: seq[int]
> proc delete[T](x: var seq[T]; i: Natural)
>   first type mismatch at position: 1
>   required type: var seq[T]
>   but expression 'dest' is of type: seq[int]
> 
> expression: delete(dest, 3, 8)
>

**Comment by narimiran** [comment]
For the curious: `import sequtils` is needed.
