### ISSUE TITLE
base64.encode should not "prettify" the result by default

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#11364]
### Description
Currently `base64.encode` prettify the result by adding CRLF after every 75 characters, which is not really useful for anything except printing. I've found myself using `encode(newLine = "")` a bit too much now for interfacing with various systems (ie. HTTP Basic Authentication).

My suggestion would be that we remove this feature or at least disable it by default.

### Alternatives
`encode(newLine = "")`

**Comment by Araq** [comment]
Now is the time to do this, before 0.20 is out...
