### ISSUE TITLE
CI is green when it shouldn't be

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#11373]
My [nimquery](https://github.com/GULPF/nimquery) package (which is listed in `important_packages.nim`) broke because of #11335, but the failure wasn't detected by the CI. If I run `koch test cat nimble-packages` locally it fails, as it should. Is something wrong with the CI environment?

**Comment by genotrance** [comment]
Nimble itself was broken - it doesn't fail during compile but during execution. I was also wondering why CI didn't fail here for last five days.

https://github.com/nim-lang/nimble/pull/660

**Comment by Araq** [comment]
The package still built but "nimble test" returned 0. So it is/was a Nimble bug.

**Comment by genotrance** [comment]
I created a PR for that bug a few hours ago. 

https://github.com/nim-lang/nimble/pull/661

cc @dom96
