### ISSUE TITLE
New case-object rules and parsecfg

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#11395]
The newly on-by-default `CaseTransition` warning produces this message compiling any code using `parsecfg.getKeyValuePair`:
```
lib/pure/parsecfg.nim(395, 17) Warning: Potential object case transition, instantiate new object instead [CaseTransition]
```

There's no test in `tests/` for this, but there probably should be.  It is used in `testament/specs.nim`, `tools/nimweb.nim`, and `tools/niminst/niminst.nim`, though.  All 3 places produce the warning (but run fine, for now).

If you try to change the `parsecfg` code to create the case object with the right `kind` in the first place then you get a full-on error:
```
lib/pure/parsecfg.nim(394, 22) Error: you must provide a compile-time value for the discriminator 'kind' in order to prove that it's safe to initialize 'key', 'value'.
```
Obviously we could do a `push` to silence the warning, but that may not be right.  `parsecfg`s input data is fundamentally run-time.  So, if you really want to block run-time `CaseTransition` then maybe `parsecfg.CfgEvent` should not be a case object at all which would be a more involved change.

**Comment by dumjyl** [comment]
Changes should be pretty minimal.

Replacing 394-395 with either:
```nim
result =
  if kind == cfgKeyValuePair:
    CfgEvent(kind: cfgKeyValuePair, key: c.tok.literal, value: "")
  else:
    CfgEvent(kind: cfgOption, key: c.tok.literal, value: "")
```
or:
```nim
let kind = kind # line unnecessary once #11397 is merged
case kind
of cfgOption, cfgKeyValuePair:
  result = CfgEvent(kind: kind, key: c.tok.literal, value: "")
else: discard
```
should work.

**Comment by c-blake** [comment]
Yeah.  That can also work.  The second way seems less ugly/repetitive to me, and it sounds like @Araq wants to merge your #11397 pronto.  After that merge, someone should also fix `parsecfg` accordingly and close this.
