### ISSUE TITLE
macros.bindSym cannot report overloaded proc declared at caller module

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#11407]
### Example
```nim
# a.nim
import macros

proc fooProc*(a: int) =
  discard

proc fooProc*(a: string) =
  discard
  
macro mixer*(): untyped =
  echo bindSym"fooProc".len
```

```Nim
# b.nim
import a

proc fooProc*(a: bool) =
  discard
  
mixer()
```

### Current Output
```
2
```

### Expected Output
```
3
```

The resolver works at caller module, I expect `bindSym` also knows the existence of `fooProc` at caller module. But in reality, `bindSym` and `dynamicBindSym` only know about `fooProc`s from the same module where the macro defined.

**Comment by krux02** [comment]
No, the output of 2 is expected and correct. Bind sym is resolved in the context where it is written. You have to create either an ``nnkIdent`` or an open sym choice to also see the third overload.


```nim
# a.nim
import macros

proc fooProc*(a: int) =
  discard

proc fooProc*(a: string) =
  discard

macro mixer*(arg: typed): untyped =
  let symChoice = bindSym("fooProc", brOpen)
  echo symChoice.len  # will still be 2
  result = newCall(symChoice, arg)

# b.nim

import a

proc fooProc*(a: bool) =
  echo "from third overload"

mixer(true) # will resolve to the local overload.
```

**Comment by jangko** [comment]
I know how `bindSym` works internally, and I know the details of the implementation. And I see that as a limitation, although you said it is 'correct'.

Your example doesn't cover my use case. In my use case, I need to know the existence of the extra overload proc from inside the macro and decide code generation when it involves distinct type. I don't want to uniformly delegate it to the resolver.

My example above only a simplification of the actual implementation.

**Comment by zah** [comment]
@jangko, I think I'm solving a similar problem in [Chronicles](https://github.com/status-im/nim-chronicles/blob/master/chronicles.nim#L333).

In order to know about the existence of certain procs in the caller scope, you can introduce an intermediate dirty template that will call the macro.

Since the template is dirty, it's expanded in the caller scope. Inside the template, there will be `bindSym` call creating a `OpenSymChoice` that will get passed to the final macro that will be able to inspect it.

**Comment by jangko** [comment]
Hmm, your trick will work if the 'entry point' already a macro/template.
The problem I'm facing is the 'entry point' is a generic proc located in the same module with the macro.

The caller module call the generic proc first, and inside the generic proc it call the macro. I don't have the flexibility to trick the compiler from a generic proc.

**Comment by zah** [comment]
Try calling the macro from the generic like this:

```
macro foo*(x: typed): untyped =
  echo x.treeRepr

proc bar*[T](x: T) =
  foo(bindSym("baz", brForceOpen))
```

`baz` here is the overload set. This seems to work for me.

**Comment by jangko** [comment]
Thank you, it works. But I still surprised to know that a `NimNode` can be passed to a macro and still arrived as a `NimNode`.  Is it documented?

**Comment by zah** [comment]
`bindSym` is defined to produce `OpenSymChoice` nodes even outside of macros. These are regular nodes that should appear naturally in code like this:

```nim
macro foo*(x: typed): untyped =
  echo x.treeRepr

proc bar*[T](x: T) =
  mixin baz
  foo(baz) # baz is overloaded, it produces an `OpenSymChoice` when passed to a macro
```

It's a bug that the above doesn't produce the same result and the `bindSym` business is just a more forceful way to trigger the desired behavior.

**Comment by krux02** [comment]
but it is noted that a ``bindSym`` that is evalutated in the context of macro expansion is desired. I do agree on this.
