### ISSUE TITLE
Nim ships latest nimble rather than stable

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#11402]
Latest 0.19.6 release ships with the latest version of Nimble [at the time](https://github.com/nim-lang/nimble/commit/f17eaef7957da23aab6e375400b37227394a632a) rather than stable. This version still has a few issues which were recently fixed in 0.10.2.

Since Nim is built after cloning from git typically, following line is always true.

https://github.com/nim-lang/Nim/blob/fc4f0808c45ab8e72e2c2e3792e4756d9380fe8c/koch.nim#L626

Seems like Nim has not shipped stable nimble in a while.

cc @dom96

**Comment by Araq** [comment]
> Since Nim is built after cloning from git typically

Well no, the idea is that if you git clone you want bleeding edge. We can change this of course, since it came up before, but it's not a bug, it's by design.
