### ISSUE TITLE
`debugger:native` no longer generates pdb file with `cc:vcc`

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#11405]
`nim c --cc:vcc --debugger:native t.nim` used to generate pdb file. Now it no longer does it.

According to `--listCmd`, these parameters are not being passed during linking phase to vccexe. 
https://github.com/nim-lang/Nim/blob/92308625347493b37951cb25e944c650a909565a/config/nim.cfg#L260-L261

**Comment by nc-x** [comment]
Is there something like `vcc.options.linker.debug` and `vcc.cpp.options.linker.debug` available in `nim.cfg`? If yes, then they need to have `"/Zi /FS /Od"`  as well.

**Comment by Araq** [comment]
I prefer to patch extccomp.nim these days. Less confusing to debug the logic when it's not split between configuration and code.
