### ISSUE TITLE
Nimble unhandled exception after update to 0.20

### ISSUE THREAD

**Issue by avatarwin** [nim-lang/Nim#11420]
After updating to 0.20.0 from 0.19.6 nimble refuses to run anymore:

### Example
```shell
$ nimble

/home/nicola/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: assignment to discriminant changes object branch; compile with -d:nimOldCaseObjects for a transition period [FieldError]
```

Other parts of the toolchain work fine however:

``` shell
$ nim -v
Nim Compiler Version 0.20.0 [Linux: amd64]
Compiled at 2019-06-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 7a670a6bc929ee497dfd119b4a502b5b1ee139b8
active boot switches: -d:release
```

### Additional Information

OS : Archlinux running 'zen' kernel and all packages up to date.
```
Linux arch-vm 5.1.7-zen1-1-zen #1 ZEN SMP PREEMPT Tue Jun 4 15:48:27 UTC 2019 x86_64 GNU/Linux
```
Installed via 'choosenim', not pacman.

**Comment by narimiran** [comment]
Thanks for the report. We are already aware of this issue and we're working on the solution.

**Comment by narimiran** [comment]
> Installed via 'choosenim', not pacman.

In the mean time, you can do:

```
choosenim update devel
choosenim devel
```

to install the working version of Nimble. (Currently `devel` == `stable` commit-wise, so no differences there when it comes to Nim compiler)

**Comment by dom96** [comment]
This has been resolved. To fix your choosenim install either do what @narimiran said, or remove the Nim 0.20.0 installation by rm'ing ``~/.choosenim/toolchains/nim-0.20.0`` and then run ``choosenim 0.20.0`` or run ``choosenim #v0.20.0``.
