### ISSUE TITLE
bin/nim loses "eXecute" bits

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#11427]
I follow the build/installation instructions for `devel` branch in `readme.md`, and I end up with this:
```sh
% ls -larth bin
-rw-rw-r--  1 cdunn Domain Users    63 Jun  7 06:59 empty.txt
-rwxrwxr-x  1 cdunn Domain Users   727 Jun  7 06:59 nim-gdb
-rwxrwxr-x  1 cdunn Domain Users  4.7M Jun  7 07:03 nim_csources
drwxrwxr-x 24 cdunn Domain Users  4.0K Jun  7 07:06 ..
-rwxrw-r--  1 cdunn Domain Users  4.7M Jun  7 07:13 nim
-rwxrwxr-x  1 cdunn Domain Users  2.4M Jun  7 07:15 nimsuggest
-rwxrwxr-x  1 cdunn Domain Users  341K Jun  7 07:15 nimgrep
-rwxrwxr-x  1 cdunn Domain Users  655K Jun  7 07:15 nimpretty
-rwxrwxr-x  1 cdunn Domain Users  3.2M Jun  7 07:15 nimfind
drwxrwxr-x  2 cdunn Domain Users  4.0K Jun  7 07:15 .
-rwxrwxr-x  1 cdunn Domain Users 1019K Jun  7 07:15 nimble
```
See? `koch tools` does it right, but the `nim` binary itself lacks execute permission for "group" and "other".

Whenever I forgot to fix this up installation, some user will complain to me later.

**Comment by pb-cdunn** [comment]
```sh
% umask
0002
```

**Comment by kaushalmodi** [comment]
@pb-cdunn I confirm this.. and as you show, it's only for the `nim` binary.

May be https://github.com/nim-lang/Nim/blob/99a4fed96b4e703ff490edfaa65e0832ad41ce34/koch.nim#L114 needs to include `fpGroupExec` and `fpOthersExec` too?

**Comment by kaushalmodi** [comment]
And this issue is only for the `nim` binary because it's the only one being copied using the `copyExe` in `koch.nim`:

https://github.com/nim-lang/Nim/blob/99a4fed96b4e703ff490edfaa65e0832ad41ce34/koch.nim#L310

**Comment by pb-cdunn** [comment]
Nice investigation, @kaushalmodi .
