### ISSUE TITLE
Bad 'fields not initialized' error

### ISSUE THREAD

**Issue by dumjyl** [nim-lang/Nim#11428]
This is a minimal reproduction of an error reported by @disruptek affecting case objects. It also affects `try/except`. See nim-lang/Nim#11081 for the exception variant of the bug. I'll try and investigate.

### Example

```nim
type
  Thing = object
    val: range[1..1] # the range cannot start at 0 to reproduce 
discard Thing()
```

### Current Output
```
Error: fields not initialized: val.
```

### Additional Information
tested on 19.6 and 20.0

**Comment by andreaferretti** [comment]
Seems right to me? `val` is actually not initialized

**Comment by dumjyl** [comment]
Yes, but the behavior is inconsistent. `Thing` is not a `{.requiresInit.}` object and `range[1..1]` can't be `not nil`. Change `range[1..1]` to any other type and the error should be more obvious.

**Comment by andreaferretti** [comment]
Still not obvious to me where the bug is. Everything in Nim is 0 initialiazed by default. 0 is not a valid value for `range[1..1]`, so you have to initialize it explicitly. Nim rightly complains that `val` is not initialized. I cannot see anything wrong

**Comment by disruptek** [comment]
Does this help?

https://gist.github.com/disruptek/0576f449ec24801abc545a59ef513ab7

**Comment by dumjyl** [comment]
I see this used to be the behavior for enums without a zero value, but it was changed/fixed in https://github.com/nim-lang/Nim/pull/10155.
```nim
type
  Enum = enum A = 1
  Obj = object
    val: Enum
echo Obj()
```

**Comment by disruptek** [comment]
Okay, I think I finally understand the problem.  :wink: 

How do you think it _should_ work?  I have to admit, it doesn't bother me so much that we have to specify values for types which may be inferred simply because they may hold only one possible value.  That, to me, seems like something we could issue a warning upon, which could be turned into an error if necessary.  To allow the field to hold a value outside its type feels like a bug.

What troubles me is instantiating these objects in the first place.  Do I really need to code the following boilerplate?  Is it desirable to force the user to enumerate all variant values with constants during instantiation?  I can make arguments for and against.

```nim
case d:
of Monday: Thing(day: Monday)
of Tuesday: Thing(day: Tuesday)
of Wednesday: Thing(day: Wednesday, b: now())
of Thursday: Thing(day: Thursday)
of Friday: Thing(day: Friday)
of Saturday: Thing(day: Saturday)
of Sunday: Thing(day: Sunday)
```

**Comment by dumjyl** [comment]
Since 0.20.0, in general less boilerplate for case objects is required. But I didn't think about `tfNeedsInit`/`tfNotNil`. In this case the boilerplate is required until fixed.

After this is fixed you should only need:
```nim
case d:
of Wednesday: Thing(day: d, b: now())
else: Thing(day: d)
```

The bug:
```nim
type
  Enum = enum A, B, C
  Thing = object
    case kind: Enum
    of A: discard
    of B: s: string
    of C: r: range[1..1] # DateTime

# Fine to not initialize 'r' because this is implicitly initialized and known to be branch 'A'.
let someThing = Thing()

let k = A
case k
of C: echo Thing(kind: k, r: 1)
# The bug: because we don't know what 'k' is or isn't and it might be branch 'C'
# which would require initialization.
# Really we do have enough info to know that k is 'A' or 'B', but the analysis
# isn't done for checking required missing fields.
else: echo Thing(kind: k)
```

So I think there are two issues:
1. The runtime discriminator analysis should be done for required initializations too.
2. Non-zero-enums and non-zero-ranges should become consistent, one way or the other. Or even better, initialize them to valid values. I saw some support for this on other issues too.

**Comment by Araq** [comment]
> Or even better, initialize them to valid values. I saw some support for this on other issues too.

I'm afraid this feature was overlooked in our v1 plan. :-( Maybe we can still try to do it and sell it as a "patch"?

**Comment by dumjyl** [comment]
I guess code breakage would depend on the initialization rule.
- `low(Range)` How common are negative ranges?
- `if 0 notin Range: low(Range)` 
- `clamp(0, low(Range), high(Range))`
