### ISSUE TITLE
Buffered socket used too long to get last several bytes

### ISSUE THREAD

**Issue by kitech** [nim-lang/Nim#11425]
Until the remote server closed the socket, I can got the last 13 bytes.

But seems the last 13 bytes has already buffered, so I think it should be return as early as possible, not wait until close.

### Example
```nim
import net
import times

var ip = "39.156.66.14" # "www.baidu.com"
var port = 80.Port

var sock = newSocket(buffered=true)
sock.connect(ip, port)
echo("connected")
var reqtxt = "GET / HTTP/1.1\r\n\r\n"
var rv = sock.send(reqtxt.cstring, reqtxt.len)
var lastrecv = times.now()
while true:
    var buf = sock.recv(123)
    if buf == "": break
    if buf.len != 123:
        echo("recved", " ", buf.len, "/", 123, ", ", times.now() - lastrecv)
    lastrecv = times.now()

echo("done")

```

### Current Output
```
connected
recved 13/123, 1 minute, 24 seconds, 983 milliseconds, ...
done

```

### Expected Output
```
connected
recved 13/123, 0 nanoseconds
done

```

### Possible Solution
use unbuffered socket

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.0 [Linux: amd64]
```

**Comment by dom96** [comment]
``sock.recv(123)``, you're asking for 123 bytes, the behaviour of ``recv`` on buffered sockets is to always return 123 bytes (unless something bad happens like the socket disconnecting)

This is documented for the async ``recv``: https://nim-lang.org/docs/asyncnet.html#recv%2CAsyncSocket%2Cint (we should copy these docs to ``net`` as well).

In any case, what you should really be doing here is using ``readLine``, that's how the HTTP protocol works.

**Comment by kitech** [comment]
I understand what you said of current code behaviour reason. Now I am thinking is this behaviour a proper behaviour.

Here are some points about buffered socket behaviour, if I misunderstand any, don't mind: https://stackoverflow.com/questions/2295737/case-when-blocking-recv-returns-less-than-requested-bytes

If remote send data length less than recv required, should be return avaliable in buffer data, or there will be a unneeded wait.

**Comment by dom96** [comment]
Maybe it doesn't match the semantics of the operating system's ``recv``, but these semantics have been in Nim for many years now. I don't think it would be wise to change them. If you want the OS behaviour then just disable buffering.

Personally I think that relying on this behaviour isn't a good idea. Protocols are deterministic, they always have a token that determines the length of bytes to read, so reading a random number and hoping that you get what you want is not how you should do it. The current semantics mean that you discover this quickly, which is actually a good thing.

**Comment by kitech** [comment]
Understand the design meaning and current code state thinking now. Of cause it good enough there is an option to disable buffering.

The random number parameter is just show the case, not good practice. Then, for a library that given a parameter, thinking fuzz values is better, at least works as expected are fine, even we believe programmer should not do that IMO.

**Comment by narimiran** [comment]
The behaviour is now (PR #12374) documented, closing.

**Comment by ghost** [comment]
The documentation additions are nice, but IMO we need to be more clear that if the client expects more bytes than the server sent and timeout is not changed, the `recv` will be stuck **forever**.
