### ISSUE TITLE
ENDB missing from Docs and TheIndex, remove ENDB from --fullhelp

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#11431]
- ENDB is now missing from TheIndex and the documentation.

That documentation was kind of complete and working, is just gone with the new `0.20.0`.

Being a feature shipped by default on Nim itself, the documentation should be back online.

:slightly_smiling_face:

**Comment by Araq** [comment]
ENDB is dead, that's why.

**Comment by juancarlospaco** [comment]
Oh, I didnt know that, it still shows on `nim --fullhelp` tho.
Maybe it should be removed from the Help command. :thinking:

**Comment by juancarlospaco** [comment]
Thanks.

For historical purposes I would comment that I try to fix endb, but its way too big, seriously big,
and kinda complex, I think we better fix more urgent stuff that has no alternative solution.

:slightly_smiling_face: :+1:
