### ISSUE TITLE
os.getTempDir() doesn't use the TMPDIR env var on POSIX systems

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#11439]
This environment variable is documented here: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

I ran into this by debugging a test failure in Gentoo's Portage sandbox which denies access to "/tmp" in favour of another directory defined in TMPDIR.

**Comment by kaushalmodi** [comment]
Yeah, even though the docstring suggests using `-d:tempDir`, I think that it should check if the `TMPDIR` env var is defined and then finally resort to the hard coded `/tmp`.
