### ISSUE TITLE
0.20.0 fails to bootstrap when passing "--verbosity:2" (or 3) to koch

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#11436]
Using https://nim-lang.org/download/nim-0.20.0.tar.xz:

```text
sh build.sh
bin/nim c koch
./koch boot --verbosity:2
```

I get this failure:

```text
/mnt/mypassport/storage/nim-0.20.0/compiler/semparallel.nim(456, 32) Warning: not GC-safe: 'transformSpawnSons(g, owner, n, barrier)' [GcUnsafe]
      result = transformSpawnSons(g, owner, n, barrier)
                                 ^
/mnt/mypassport/storage/nim-0.20.0/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: /mnt/mypassport/storage/nim-0.20.0/compiler/guards.nim(984, 12) `branch.kind == nkOfBranch`  [AssertionError]
FAILURE
```

With `rm -rf nimcache; ./koch boot --verbosity:3`, there's a different error:

```text
/mnt/mypassport/storage/nim-0.20.0/lib/system/io.nim(653, 1) Hint: 130047 [Processing]
???(0, 0) Hint: 131814 [Processing]
  
/mnt/mypassport/storage/nim-0.20.0/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: value out of range: -1 [RangeError]
FAILURE
```

**Comment by Vindaar** [comment]
This does not only happen during bootstrapping. Also just a simple hello world program is affected:
`hello.nim`:
```nim
echo "Hello :)"
```
```sh
nim c --verbosity:3 hello.nim
```
throws the same error:
```
???(0, 0) Hint: 174814 [Processing]
Hint: testecho [Processing]
/tmp/testecho.nim(1, 6) Hint: 175003 [Processing]
  echo "Hello world!"
       ^
???(0, 0) Hint: 175024 [Processing]
  
/home/schmidt/src/nim/nim_git_repo/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: value out of range: -1 [RangeError]
```

**Comment by Vindaar** [comment]
Hmm, for some reason the `col` field of the `TLineInfo` argument in `writeSurroundingSrc` is `-1` here:
https://github.com/nim-lang/Nim/blob/devel/compiler/msgs.nim#L455

`strutils.spaces` however takes a `Natural`, so we get the `RangeError`, since `-1` is not in `Natural`.

**Comment by narimiran** [comment]
> Also just a simple hello world program is affected

...if your `nim` was bootstrapped without `-d:danger` flag. I.e. if you need a workaround until this is fixed, bootstrap Nim with `./koch boot -d:danger`.

**Comment by Vindaar** [comment]
Ahh, indeed I just built the compiler with `-d:danger` today, heh.

**Comment by stefantalpalaru** [comment]
Time to reopen this one for Nim 1.0.0. Segfaults during:

`./koch boot -d:release --verbosity:2`

and 

`PATH="./bin:${PATH}" nim c -d:release --verbosity:2 -o:bin/nimpretty nimpretty/nimpretty.nim`

**Comment by Araq** [comment]
I already fixed it.
