### ISSUE TITLE
Niminst missing from installation

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#11433]
- `niminst` is missing from `0.20.0` installed via `choosenim` (Linux x86_64).

Documentation mention it as a tool that comes with Nim, and I see very recent commits on it.

It was useful and [documented](https://nim-lang.org/docs/niminst.html), I wont see its removal on the Changelog so assumed is a Bug, please ship it back.

:slightly_smiling_face:

**Comment by Araq** [comment]
This is not a regression though, afaict.

**Comment by juancarlospaco** [comment]
Still repro on `1.0.0`, updated the title. :crying_cat_face:

**Comment by juancarlospaco** [comment]
Repro `1.2.6`. :disappointed:

**Comment by timotheecour** [comment]
could be fixed as side effect of fixing https://github.com/nim-lang/Nim/issues/15946

**Comment by timotheecour** [comment]
@xflywind do we really need to bundle niminst with nim's installation or can we close this? isn't it good enough to clone nim for this use case?

**Comment by ringabout** [comment]
> Niminst missing from installation

Yeah, The source code of niminst` is shipped with Nim. You can compile `tools/niminst/niminst.nim`(installed by choosenim).

>  can we close this?

@timotheecour 
maybe update documentation regarding where it is and how to use it?

**Comment by juancarlospaco** [comment]
@xflywind 
What are the advantages of doing that ?.

In theory, sounds kinda Ok, 
in practice, when a tool goes not shipped or not built, and unused by people eventually gets broken beyond repair,
that happened with other tools on the tools folder in the past too, eventually the tool just wont build with devel,
and starts getting more and more abandoned, and the tool [only has 1 Bug](https://github.com/nim-lang/Nim/issues/11433).
:shrug:

**Comment by ringabout** [comment]
It is used internally, can't be broken easily as other tools.

For example `koch csource` will compile `tools/niminist`.

**Comment by juancarlospaco** [comment]
Assuming the tool is now distributed as source-only that the user needs to manually compile and not as a compiled binary anymore sadly.
