### ISSUE TITLE
c2nim missing from 0.20.0

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#11434]
- `c2nim` is missing from `0.20.0` installed via `choosenim` (Linux x86_64).

Documentation mention it as a tool that comes with Nim, and I see very recent commits on it.

It was useful and [documented](https://github.com/nim-lang/c2nim/blob/master/doc/c2nim.rst), it wasnt perfect but better than nothing, I wont see its removal on the Changelog so assumed is a Bug, please ship it back.

:slightly_smiling_face:

**Comment by mratsim** [comment]
I always had to `nimble install c2nim`. It's maintained by the core nim devs but installation is separate from nim.

**Comment by juancarlospaco** [comment]
I mean is not like I cant live without it, but I am just help testing details that should be good to have for a Release Candidate, which we are.
So is a Documentation Bug and Docs should say is installed separately, sounds good.

:slightly_smiling_face: :+1:

**Comment by Araq** [comment]
Looks like a 'choosenim' bug to me.
