### ISSUE TITLE
os:standalone Error: redefinition of 'nimToCStringConv' 

### ISSUE THREAD

**Issue by mikra01** [nim-lang/Nim#11445]
I would like to compile the following example with the gcc-cross toolchain:
"nim c --d:release --os:standalone --gcc.exe:i686-elf-gcc test.nim"

### test.nim
```nim
 asm """
       hlt;     
     """  
```
### gives me the error
```
Hint: system [Processing]
C:\Users\tst\Nim\lib\system\sysstr.nim(85, 1) Error: redefinition of 'nimToCStringConv'; previous declaration here: C:\Users\tst\Nim\lib\system.nim(3357, 8)
```

### Additional Information
my compiler version
```
Nim Compiler Version 0.20.99 [Windows: amd64]
Compiled at 2019-06-07
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: bce908f6ee9f24346641310d8f7f8971e92ffe01
active boot switches: -d:release
```

**Comment by mratsim** [comment]
It seems like a redeclaration introduced by the `standalone` flag

https://github.com/nim-lang/Nim/blob/3c62d4146899cd27f8926563fb071ea7db981899/lib/system/sysstr.nim#L85-L87

https://github.com/nim-lang/Nim/blob/3c62d4146899cd27f8926563fb071ea7db981899/lib/system.nim#L3356-L3359

**Comment by mikra01** [comment]
it is consumed within the compiler here:
https://github.com/nim-lang/Nim/blob/4296bddccb8da3d37b4bb8c3a1f704c3377a750f/compiler/ccgcalls.nim#L140
and here
https://github.com/nim-lang/Nim/blob/84ca1f3bf3d0095034973fae8c36999f8778c451/compiler/ccgexprs.nim#L1988
it seems (to me) that it´s more appropriate within sysstr.nim. I just removed the lines 3356-3359 within system.nim locally but unfortunately I run into another issue:

`nim c --os:standalone --gcc.exe:i686-elf-gcc test.nim
Hint: used config file 'C:\Users\tst\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\tst\Nim\config\config.nims' [Conf]
Hint: system [Processing]
C:\Users\tst\Nim\lib\system\gc.nim(445, 20) Error: type mismatch: got <int, int literal(16)>
but expected one of:
proc addInt(a, b: int16): int16
  first type mismatch at position: 1
  required type: int16
  but expression 'mulInt(len, typ.base.size)' is of type: int
expression: addInt(mulInt(len, typ.base.size), 16)`

`nim c --os:standalone --gc:stack --gcc.exe:i686-elf-gcc test.nim
Hint: used config file 'C:\Users\tst\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\tst\Nim\config\config.nims' [Conf]
Hint: system [Processing]
C:\Users\tst\Nim\lib\system\gc_regions.nim(338, 28) Error: type mismatch: got <int, int literal(16)>
but expected one of:
proc addInt(a, b: int16): int16
  first type mismatch at position: 1
  required type: int16
  but expression 'mulInt(len, typ.base.size)' is of type: int
expression: addInt(mulInt(len, typ.base.size), 16)`

the switch --gc:none  seems to prevent that crash...

**Comment by mikra01** [comment]
Hi, how could this be resolved? just removing these few lines (as mentioned) within system.nim? how could the 2nd "mulInt" issue resolved? Should I file another issue for that?  At the moment my workaround is: use 0.19.6..

**Comment by Araq** [comment]
I couldn't reproduce the mulInt issue, if still a problem open a new bug for that one. Thanks!

**Comment by mikra01** [comment]
Hi Araq, thank you very much - I'll investigate further...
