### ISSUE TITLE
--gc:go does not work anymore

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#11447]
I'm not sure if Go GC support has fallen by the wayside or if this is simply a regular bug.

Compiling with `nim cc --gc:go` doesn't work anymore (at least on the current devel branch).

Part of the problem is simply that `GC_getstatistics()` tries to call the `$` operator on uints, which doesn't work. While this is simple to fix, there also seem to be problems with `realloc()` that I haven't had time to figure out yet.

**Comment by mratsim** [comment]
cc @stefantalpalaru
