### ISSUE TITLE
Lock down csources version

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#11457]
Now that #9017 is fixed, the remaining moving piece (apart from the c compiler/environment itself of coz...) is `csources` - could we lock that down too, in `build_all.sh` and friends?

Practically, we're seeing build failures when we check out 0.19 - the current `csources` at the time of writing is no longer able to build it: https://ci.appveyor.com/project/nimbus/nim-http-utils/builds/25118413/job/4nj7qsfvwql9nlj5

**Comment by andreaferretti** [comment]
I think csources have tag as well. [This is how](https://gist.github.com/andreaferretti/d40af6a276fb3275d97d0f9585d8197e#file-mynim-L21-L28) I handle installing - goig to the csources folder and checking out the version

**Comment by Araq** [comment]
> could we lock that down too, in build_all.sh and friends?

Ok, if you tell me what "and friends" means.

**Comment by arnetheduck** [comment]
```
[arnetheduck@tempus Nim]$ agu clone.*csources
ci/nsis_build.bat
28:git clone --depth 1 https://github.com/nim-lang/csources.git

ci/build.sh
4:git clone --depth 1 https://github.com/nim-lang/csources.git

ci/build.bat
5:git clone --depth 1 https://github.com/nim-lang/csources.git

readme.md
68:# step 2 (posix) clones `csources.git`, bootstraps Nim compiler and compiles tools
72:git clone --depth 1 https://github.com/nim-lang/csources.git

csources/readme.markdown
10:$ git clone --depth 1 git://github.com/nim-lang/csources

appveyor.yml
43:  - git clone --depth 1 https://github.com/nim-lang/csources

build_all.sh
13:[ -d csources ] || echo_run git clone --depth 1 https://github.com/nim-lang/csources.git
```

**Comment by genotrance** [comment]
The csources repo itself is locked, this can be closed.

**Comment by arnetheduck** [comment]
a bit of a short-term solution though - I wonder how long it will take before someone forgets why it was    done..
just like keeping 1.0 100% compatible isn't sustainable, this policy will eventually end..

**Comment by Araq** [comment]
As I said, once the time comes, we'll simply have a csources2 repo and all the scripts out there continue to give you Nim version 1.0 or whatever people did setup.

**Comment by timotheecour** [comment]
this has been fixed via https://github.com/nim-lang/Nim/issues/11457, which refactors all invocations of building csources via a bash API `nimBuildCsourcesIfNeeded`, as well as offers a way to get the url and hash of the csources version used to bootstrap nim, see that PR for details
