### ISSUE TITLE
bootstrapping fails on master

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#11454]
My travis builds are failing when trying to bootstrap Nim on master.

### Example

```sh
$ git clone -b master --depth 1 git://github.com/nim-lang/nim
$ cd nim
$ git clone --depth 1 git://github.com/nim-lang/csources csources/
$ cd csources
$ sh build.sh
$ cd ..
$ bin/nim c koch
```

### Current Output
```
Hint: used config file '/tmp/bootstrap/nim/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: system [Processing]
/tmp/bootstrap/nim/lib/system.nim(207, 11) Error: undeclared identifier: 'is'
```

**Comment by ee7** [comment]
I noticed this problem too.

Since the 0.20.0 csources update, all builds from Nim's `master` and csources `master` will have failed. 

One workaround:

```sh
git clone -b v0.19.0 --depth 1 https://github.com/nim-lang/csources
```

Any fix for this issue should also update the [BuildServices](https://github.com/nim-lang/Nim/wiki/BuildServices#devel-branches) wiki page if necessary.

See also: https://github.com/nim-lang/Nim/issues/11457

**Comment by bluenote10** [comment]
Are there plans to solve this soon? I'm asking because my CI builds keep failing, and it's a pity that the standard way of clone + build_all doesn't work on master.

I'd like to contribute a fix, but I don't understand the motivation of the current setup: Why isn't `csources` tracked as a submodule, which would avoid these issues in the first place?

**Comment by DestyNova** [comment]
This hit me too while trying to update the Heroku buildpack for Nim.

**Comment by krux02** [comment]
@narimiran can you take a look at this.

**Comment by Araq** [comment]
> Why isn't csources tracked as a submodule, which would avoid these issues in the first place?

I don't understand git submodules and I don't use what I don't understand.

**Comment by genotrance** [comment]
Wasn't master on nim-lang/Nim going to be deleted? Devel is head, releases are tags and now also branches. Master was being updated to last release but is a headache and of little value. 

Meanwhile, choosenim already handles this properly. Clone the csources tag that matches the nim version.

**Comment by bluenote10** [comment]
> I don't understand git submodules and I don't use what I don't understand.

They aren't really rocket science, are they? Just tracking the commit hash of `csources` that is suitable for a particular state of the main repo, and the whole nested clone of csources would become `git submodule update --init --recursive` or so. If anything they are criticized for being too simple (like the simplicity doesn't allow for much convenience when reviewing pull requests across subrepos), but not tracking the relationship at all obviously doesn't make that any better and simply seems worse to me.

> Wasn't master on nim-lang/Nim going to be deleted?

That doesn't solve the underlying issue: The Nim repo has a dependency on the csources repo on any branch. Checking out an old release tag / branch followed by cloning `csources` HEAD revision simply won't work in general. Or git bisecting on devel.

**Comment by Araq** [comment]
> The Nim repo has a dependency on the csources repo on any branch. 

Huh? I don't use C sources to build Nim. There is no real dependency, you need a Nim to be able to compile Nim. You can also use the C sources instead but that doesn't make it a dependency.

**Comment by bluenote10** [comment]
> There is no real dependency, you need a Nim to be able to compile Nim.

Well, there are breaking changes in the compiler, so you cannot use **any** Nim -- otherwise we wouldn't be discussing broken bootstrapping on master ;).

If you want to bootstrap a commit X of the Nim repo, you have to guess some commit Y of csources to make bootstrapping work. In terms of bootstrapping csources is a dependency, and this issue (and all the issues of bootstrapping when jumping around in git history) clearly shows that it is a real dependency that requires versioning.

The current bootstrapping approach treats csources as a manually managed git submodule that always points to HEAD, which is simply inferior to a correctly handled submodule that would make bootstrapping 100% reproducible.

**Comment by Araq** [comment]
The older stable Nim release can always compile the newer release. By your logic, GCC should have a submodule to a repo of the generated ASM for a "real building from source" setup. But there is no such thing, every "entry point" to a bootstrapping process is from a **binary** executable.

**Comment by bluenote10** [comment]
> By your logic, GCC should have a submodule to a repo...

It's a different situation: For GCC there are no sources of a bootstrapping compiler in a different language (to my knowledge), and thus bootstrapping really has to start from an existing binary. In contrast, Nim has a bootstrapping compiler available in another language, and thus, allows reliable bootstrapping entirely from sources. Just because this is not possible for GCC doesn't imply that it shouldn't be done for Nim.

I'm just trying to solve the problem, if you have a better idea let's go for it. Currently checking out an arbitrary commit `X` of Nim comes with a bootstrapping instructions (via readme and/or install script) that simply don't work for commit `X`.

**Comment by genotrance** [comment]
I agree that a csources mismatch doesn't always work. @bluenote10's report in this issue is a newer csources with an older Nim (I don't believe master was updated in 0.20.0 release). I don't know for sure but I think older csources with newer Nim have also failed though I'll have to check to be sure. 

Regardless, for most normal users, it is recommended to download the release or nightly xz since those are tested combos. Only developers should consider head.

If anything, I would propose a simple script in the Nim repo that downloads the right csources and bootstraps, or updates and rebuilds to keep the checkout up to date. I know I have such scripts already and can contribute but Araq hasn't been too keen to add such stuff historically.

**Comment by arnetheduck** [comment]
https://github.com/nim-lang/Nim/issues/11457

**Comment by genotrance** [comment]
I tried to bootstrap v0.19.0 Nim with latest csources and devel Nim with v0.19.0 csources and both failed to bootstrap - i.e. `nim c koch` fails.

Basically, if koch.nim or the compiler source uses syntax that the binary nim doesn't understand, it won't work. So it is not always the case that an old Nim can compile newer code or the opposite.

**Comment by bluenote10** [comment]
This issue is not longer relevant -- according to [Araq's comment](https://forum.nim-lang.org/t/5394) the master is deprecated.
