### ISSUE TITLE
Add ability to "unset" an environment variable

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11452]
We have a way to check if an env var is *nil* (`existsEnv("FOO")`) vs `""` (`getEnv("FOO") == "" `). 

We can set an env var to `""` (`putEnv("FOO", "")`). But we cannot completely **unset** it.

When *nil* strings were allowed, `putEnv("FOO", nil)` would have been the way to do that. But that won't work any more. 

So we need a new proc in `osenv.nim` to pass *nil* to `c_putenv`.

I believe this loss of ability to unset an env var can be counted as a regression since *nil* strings got disallowed. 

I discovered this limitation as I was writing a test in https://github.com/nim-lang/Nim/pull/11443.

---

**Update**: May be this qualifies as a feature request. I see that `unsetenv` from C was never mapped to a Nim proc.

**Comment by SolitudeSF** [comment]
empty env variables count as unset.

**Comment by kaushalmodi** [comment]
@Araq I tried this locally on Linux and it works:

```nim
proc unsetEnv*(key: string) {.tags: [WriteEnvEffect].} =
  ## Removes the `environment variable`:idx: named `key`.
  ## If an error occurs, `OSError` is raised.
  ##
  ## See also:ven
  ## * `getEnv proc <#getEnv,string,string>`_
  ## * `existsEnv proc <#existsEnv,string>`_
  ## * `putEnv proc <#putEnv,string,string>`_
  ## * `envPairs iterator <#envPairs.i>`_

  when nimvm:
    discard "built into the compiler"
  else:
    var indx = findEnvVar(key)
    if indx < 0: return # Do nothing if the env var is not already set
    let
      keyToRemove = cstring($environment[indx].rsplit('=', maxsplit=1)[0])
    echo "key to remove = ", keyToRemove
    when defined(windows) and not defined(nimscript):
      # TBD
      discard
    else:
      if c_unsetenv(keyToRemove) != 0'i32:
        raiseOSError(osLastError())
      environment.delete(indx, indx)

when isMainModule:
  echo "ABC env var exists(1)? ", existsEnv("ABC")
  putEnv("ABC", "1")
  echo "ABC env var exists(2)? ", existsEnv("ABC")
  echo "ABC is set to ", getEnv("ABC")
  unsetEnv("ABC")
  echo "ABC env var exists(3)? ", existsEnv("ABC")
```

## Questions

- I don't know how to implement `unsetEnv` on Windows.
- I don't know if there's a foolproof way to extract the "key" from the `environment` in `os.nim`.. so I did `cstring($environment[indx].rsplit('=', maxsplit=1)[0])` and it works. But it's inefficient as I am doing cstring -> string -> cstring.

**Comment by cheatfate** [comment]
You can implement `unsetEnv` on Windows using this API call https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-setenvironmentvariable

SetEnvironmentVariable(pathVariableName, nil) will delete variable.

**Comment by kaushalmodi** [comment]
@cheatfate Looking at the current `osenv.nim` and `winlean.nim` code, we have only:

https://github.com/nim-lang/Nim/blob/7cf9b522b5d2735b5279e9c2bdcade5c177868f8/lib/windows/winlean.nim#L240-L241

and

https://github.com/nim-lang/Nim/blob/7cf9b522b5d2735b5279e9c2bdcade5c177868f8/lib/windows/winlean.nim#L255-L256

How do I pass *nil* as value to those string-type args?
