### ISSUE TITLE
const table with proc type does not compile anymore

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#11479]
The following snippet does not compile anymore:

```nim

import tables

proc test() =
  echo readfile(currentSourcePath())

const
  map = {
    "test": test,
  }.toTable

map["test"]()
```

See also: https://forum.nim-lang.org/t/4926

**Comment by narimiran** [comment]
`git bisect` shows that the first bad commit is https://github.com/nim-lang/Nim/commit/c3067e36bbdaecf292bb67bb8c8cf3010ce87b14

**Comment by Araq** [comment]
@narimiran But that makes no sense, it should be a different commit.

**Comment by narimiran** [comment]
> But that makes no sense

I've tested it manually and the commit before that one (and I tested even some previous commits too) compiles and prints the output, and starting from that one, it fails to compile.

Here is a [list of commits](https://github.com/nim-lang/Nim/commits/devel?after=b70fd0400eb976b7e1e60845b2bfe0bdb5bf137e+461) around the bisected one, maybe you'll find something else that might be suspicious to you.
