### ISSUE TITLE
Compile error when calling tables.newTable that is exported in another module.

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#11471]
Compile error when calling tables.newTable that is exported in another module.

I got compile error from following code with Nim 0.20.0 and latest devel.
It compiles without error with Nim 0.19.6.

testmod.nim:
```nim
import tables

export tables.newTable
```

prog.nim:
```nim
import testmod

let a = newTable([(1, 1), (1, 1)])
```

Error message from Nim 0.20.0:
```console
$ nim c ./prog.nim
Hint: used config file '/opt/wandbox/nim-0.20.0/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: prog [Processing]
Hint: testmod [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
/home/jail/prog.nim(3, 17) template/generic instantiation of `newTable` from here
/opt/wandbox/nim-0.20.0/lib/pure/collections/tables.nim(826, 27) template/generic instantiation of `toTable` from here
/opt/wandbox/nim-0.20.0/lib/pure/collections/tables.nim(324, 45) Error: type mismatch: got <Table[system.int, system.int], int, int>
but expected one of: 
proc `[]=`[Idx, T, U, V](a: var array[Idx, T]; x: HSlice[U, V]; b: openArray[T])
proc `[]=`[T, U, V](s: var seq[T]; x: HSlice[U, V]; b: openArray[T])
proc `[]=`[T, U](s: var string; x: HSlice[T, U]; b: string)
template `[]=`(s: string; i: int; val: char)
proc `[]=`[T](s: var openArray[T]; i: BackwardsIndex; x: T)
proc `[]=`(s: var string; i: BackwardsIndex; x: char)
proc `[]=`[I: Ordinal; T, S](a: T; i: I; x: S)
proc `[]=`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex; x: T)

expression: []=(result, key, val)
```

``proc newTable*[A, B](pairs: openArray[(A, B)]): <//>TableRef[A, B] `` in tables module calls ``toTable``.
In ``proc toTable*[A, B](pairs: openArray[(A, B)]): Table[A, B] =``, ``proc `[]=`*[A, B](t: var Table[A, B], key: A, val: B) =`` is called but it is not defined in above code?

**Comment by Araq** [comment]
I'm not sure we support arbitrary re-exporting of generic code. ;-) 

Better export everything from tables.

**Comment by demotomohiro** [comment]
@Araq Thank you for your replay!
I found 2 ways to fix this error.

- Adding ``export tables.`[]=` `` to ``testmod.nim``.

```nim
import tables

export tables.newTable
export tables.`[]=`
```

- In ``nim/lib/pure/collections/tables.nim`` module, forward declare `` `[]=` `` before ``toTable`` proc.
For example:
```nim
proc `[]=`*[A, B](t: var Table[A, B], key: A, val: B) 

proc toTable*[A, B](pairs: openArray[(A, B)]): Table[A, B] =
  ## Creates a new hash table that contains the given ``pairs``.
```


I simplified this problem.

Just importing ``testmod.nim`` and calling ``genProc1`` and ``newTestObj`` works.

testmod.nim:
```nim
proc genProc2[A](a:A): A = a
proc genProc1*[A](a:A): A = genProc2(a)

type
  testObj*[A] = object
    id: A

proc newTestObj*[A](a:A; b:int; c:int): testObj[A] =
  result[b] = c

proc `[]=`*[A](a: var testObj[A]; b: int; c: int) =
  ## This proc is called in ``newTestObj`` proc.
  a.id += b + c
```

prog.nim:
```nim
import testmod

echo genProc1(2)
let a = newTestObj(1, 2, 3)
```

Exporting a generic procedure that call other generic procedure (``testmod.genProc1``) works.
But calling exported ``testmod.newTestObj`` is compile error.

exportmod.nim:
```nim
import testmod

export testmod.genProc1
export testmod.newTestObj
```

prog.nim:
```nim
import exportmod

echo genProc1(2)
#This code cause compile error.
let a = newTestObj(1, 2, 3)
```

When I defined `` `[]=` `` proc before ``newTestObj``, that compile error was fixed.

testmod.nim:
```nim
proc genProc2[A](a:A): A = a
proc genProc1*[A](a:A): A = genProc2(a)

type
  testObj*[A] = object
    id: A

proc `[]=`*[A](a: var testObj[A]; b: int; c: int) =
  a.id += b + c

proc newTestObj*[A](a:A; b:int; c:int): testObj[A] =
  result[b] = c
```

When I wrote non-generic version of ``newTestObj`` and `` `[]=` ``, defining `` `[]=` `` proc after ``newTestObj`` result in compile error.

testmodNoGen.nim:
```nim
type
  testObj* = object
    id: int

proc newTestObj*(a:int; b:int; c:int): testObj =
  result[b] = c

proc `[]=`*(a: var testObj; b: int; c: int) =
  a.id += b + c
```

Calling a procedure that is defined below caller proc is compile error except generic `` `[]=` `` operator.
But when I export a procedure that call generic `` `[]=` `` operator defined after that proc, calling it is compile error.
I can fix it by moving generic `` `[]=` `` operator before that proc, or export `` `[]=` `` operator.

**Comment by narimiran** [comment]
@demotomohiro I tried your proposed solution by forward-declaring `[]=` and it sure does fix your problem. But this is just a one specialized case fixed. Now try a similar example with `initTable`, `newOrderedTable`, etc. — there are similar but different problems. (It is not always `[]=` that is missing)

I could go and try to fix one by one of those cases, and if I'm lucky (I don't forget something) I might fix all those cases in `tables.nim`. But a similar problem might arise in some other module too.
I'm not sure what is the best course of action.

My advice would be the same as @Araq's above: `export tables`.

**Comment by Araq** [comment]
We don't support it. Don't cut off implementations of an abstract data type.
