### ISSUE TITLE
TinyC is not documented

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#11495]
TinyC support is not documented, is builtin but Disabled by default, it prints an error and quit,
but the Nim manual dont explain how to enable TinyC, for users of the language.

I know how to manually git clone and pass compile params and manually build,
but I want Nim with TinyC support with the vanilla standard `choosenim` tooling,
I know that adding `-d:tinyc` somewhere on a `*.cfg` file probably will make `choosenim` install with TinyC support,
but I dont know how to do it, is not documented,
being a builtin feature it should be documented for v1.0.

I know is not better than the default target, but is like an intermediate step between NimScript and C targets.

If you quickly comment how to properly enable it with `choosenim` and vanilla tooling, I can send a Documentation PR.

:slightly_smiling_face:

**Comment by Araq** [comment]
I found TinyC to be unreliable on various OSes so I don't want to document it. We need fewer half-assed features in Nim. ;-)

**Comment by juancarlospaco** [comment]
Ok, I agree, you want to hide it from the help the end users see `--fullhelp` :grey_question:
