### ISSUE TITLE
The `-d:danger` flag is ambiguous and inflexible

### ISSUE THREAD

**Issue by massung** [nim-lang/Nim#11507]
If a lot of discussion/thought went into `-d:danger`, then just ignore this post. My hope, though, is that before 1.0, a flag such as `danger` will be replaced with something less ambiguous and more flexible (a level instead of a boolean) for the future. 

Given what - TMK - it does (removing safety checks for added performance)., my suggestion would be to take a page from Common Lisp and replace it with two flags: `speed` and `safety`. Or, at the very least, just `safety` or `safetyChecks`.

```bash
$ nim c --speed:2 --safety:0
```

Now it becomes considerably more clear what's taking place and what the intent is moving forward. 

Given that the compiler already has a series of runtime check flags (e.g. `--boundChecks`), I'd think it would be simple to map various safety levels with different checks. But, if multiple levels of safety seem a bit much, then I'd at least just name it `safetyChecks` or `runtimeChecks` and if it's `off` then _all_ the runtime checks are disabled.

Again, sorry if this is a new person jumping in and bringing up something that's an old, discussed ad nauseum topic, but my experience has been that names/flags like `danger`, `fast`, etc. end up being quite frustrating down-the-road to maintain and confusing to newcomers. They tend to have their meaning conflated with new features and become even more confusing/hard to maintain and even harder to use.

My 2c.

**Comment by Araq** [comment]
For more control use ``--checks:off`` or ``--boundChecks:on`` or whatever. I fail to see the problem with ``-d:danger``, if you use it and don't know what it means, well ... it's dangerous.

**Comment by massung** [comment]
> I fail to see the problem with `-d:danger`

My concern is just the meaning - while "specific" today - will likely conflate with time to include even more things because the name itself does not state what it actually does or what the trade-off is. Presumably there is one, otherwise why would anyone enable it? 😄 

Keep in mind, my only insight into `-d:danger` is from the devblog video. If it's strictly there just to enable short-term, backwards compatibility with what `-d:release` _used_ to do (and I assume intends to disappear in the future?), then I get that.

> For more control use `--checks:off`

I was unaware of a global `--checks:off`, which covers most everything else that I commented on. Thanks for pointing it out.

**Comment by Araq** [comment]
Well the switch is here to stay, but it won't "change" so much, rather it will include other options true to its spirit which is "trade safety for more speed". Also, what exactly ``-d:danger`` means can be figured out by reading ``config/nim.cfg``.

I don't think the design is so bad that we need to do anything, hence I'm closing this issue.
