### ISSUE TITLE
String or sequences inside a loop are not cleared in each iteration

### ISSUE THREAD

**Issue by b3liever** [nim-lang/Nim#11510]
A string needs to be explicitly initialized inside a loop so its contents are cleared in each iteration. There is a difference in the following program's output between nim "current" and newruntime. The bug is about newruntime.

### Example

```nim
proc main =
  for i in 0 ..< 4:
    var buffer: seq[int] # = @[] # uncomment to make it work 
    # var buffer: string # also this is broken
    buffer.add i
    echo buffer
main()
```

### Current Output
When compiling with ``--newruntime``
```
@[0]
@[0, 1]
@[0, 1, 2]
@[0, 1, 2, 3]
```

### Expected Output

```
@[0]
@[1]
@[2]
@[3]
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-08
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: bce908f6ee9f24346641310d8f7f8971e92ffe01
active boot switches: -d:release
```

**Comment by Wh1teDuke** [comment]
Related https://github.com/nim-lang/Nim/issues/10938
