### ISSUE TITLE
No ambiguity error on field overloaded by `field=`

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#11514]
```nim
type
  FooBar = object
    foo: string
 
proc `foo=`*(f: var FooBar, v: string) =
  echo("This isn't executed...")
  f.foo = v

var x = FooBar()
x.foo = "hello"
```

I expect to get an error in this case. Not it silently assuming I want to assign the field (but not via the proc I created). The same thing happens if ``FooBar`` is in another module and `foo` field is exported (which I how I ran into this)

**Comment by Araq** [comment]
It works according to the spec but the spec needs to be more explicit about this: ``obj.field`` is interpreted as ``obj.field`` unless it cannot be interpreted this way, then accessors are considered. Usually this rule produces good results, we cannot error with an ambiguity here, that would break far too much code.

**Comment by dom96** [comment]
> Usually this rule produces good results, we cannot error with an ambiguity here, that would break far too much code.

I find that surprising, is there really that much code which depends on this? If so then the semantics are quite confusing, do you have examples of code that does this?

**Comment by Araq** [comment]
How about we start with the insight that 

```nim

proc `foo=`*(f: var FooBar, v: string) =
  echo("This isn't executed...")
  f.foo = v
```

itself *only* works with this rule? Otherwise it would be an infinite recursion...

**Comment by bluenote10** [comment]
There could be solutions to this, right?
- Explicit: `f.foo {.field.} = v`
- Implicit: Within `foo=`, `f.foo` is treated as field access.

Despite being a fairly big break, I'd love to see a solution to this.

Example that suffers from the behavior: [nim-finals](https://github.com/Quelklef/nim-finals) which only works across modules, not within modules :confused: 

Would it be possible to use the "important packages test suite" to estimate the percentage of affected packages?

**Comment by Araq** [comment]
> Would it be possible to use the "important packages test suite" to estimate the percentage of affected packages?

Only after we implemented the required changes.
