### ISSUE TITLE
newruntime: error when modifying a sequence

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#11524]
proc creates a new sequence, modifies the first value, and then prints it. When compiled with newruntime modifying the value crashes it.

### Example

```nim
proc main() =
  var a = @[1,2,3]
  a[0] = 4
  echo "a: ", a

when isMainModule:
  main()
```

### Current Output when compiled with `nim c --newruntime`

```
Traceback (most recent call last)
/Users/bpr/src/nim/nim-examples/nr_bug00.nim(7) nr_bug00
/Users/bpr/src/nim/nim-examples/nr_bug00.nim(3) main
SIGBUS: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output compiled with `nim c -d:danger`

```
a: @[4, 2, 3]
```

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-06-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8268330be4de61541aa34eb82f7a93dc62e627c
active boot switches: -d:release
```

**Comment by Araq** [comment]
Reason: We move the const sequence into ``a`` which then points to a readonly data section.
