### ISSUE TITLE
Unexpected behaviour when constructing with `result`

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#11525]
```nim
type
  Point[T] = object
    x, y: T

proc adjustPos[T](width, height: int, pos: Point[T]): Point[T] =
  result = pos

  result = Point[T](
    x: pos.x - (width / 2),
    y: pos.y - (height / 2)
  )
  
proc adjustPos2[T](width, height: int, pos: Point[T]): Point[T] =
  result = pos

  result = Point[T](
    x: result.x - (width / 2),
    y: result.y - (height / 2)
  )

proc adjustPos3(width, height: int, pos: Point): Point =
  result = pos

  result = Point(
    x: result.x - (width / 2),
    y: result.y - (height / 2)
  )

echo adjustPos(200, 200, Point[float](x: 1000, y: 1000))
echo adjustPos2(200, 200, Point[float](x: 1000, y: 1000))
echo adjustPos3(200, 200, Point[float](x: 1000, y: 1000))
```

Result:

```
(x: 900.0, y: 900.0)
(x: -100.0, y: -100.0)
(x: -100.0, y: -100.0)
```

Perhaps this behaviour is expected. But I swear I had ``adjustPos3`` in the JS backend and it worked (I didn't re-test this), so there is at least 3 different behaviours here (!)

**Comment by krux02** [comment]
No, this behavior is not expected. It is a bug. It should either complain at compile time that you read a value that you are writing, or it should do it properly.

**Comment by jangko** [comment]
looks like this bug is not exclusively belong to `result`, local variable also suffer from this syndrome.

```Nim
type
  MyObject = object
    x, y: int
    
proc test() =
  var a = MyObject(x: 100, y: 200)
  a = MyObject(x: a.x - 10, y: a.y - 10)
  echo a # should be (x: 90, y: 190)

test()
```

Output:
```text
(x: -10, y: -10)
```

wow, after all these years nobody ever notice this bug exists.

**Comment by pgkos** [comment]
The result is correct on v0.17.2, broken from v0.18.0.

**Comment by krux02** [comment]
@pgkos then I guess this is a regression.

**Comment by pgkos** [comment]
bisect shows that d0a9fac36252a135dba6304b9f7ccc18c899c267 is the first bad commit.

**Comment by Araq** [comment]
Should be easy to fix.
