### ISSUE TITLE
Newruntime: setLen() not working on sequences of owned refs

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#11530]
```nim
var x: seq[owned(ref int)]
x.setLen(1)
```

fails to compile with

```../Nim/lib/core/seqs.nim(154, 20) Error: sink parameter `value` is already consumed at ../Nim/lib/core/seqs.nim(154, 20)```

as `grow` tries to initialize new elements from the same owned value.

**Comment by sinkingsugar** [comment]
Even `setLen(0)` on a empty seq fails, quite a blocker for newruntime.
