### ISSUE TITLE
When compiling to JS (in `-d:release`) output contains toolchain path on dev's machine

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#11545]
I'm working on a project right now where I'm leveraging Nim's JS target.  This is most likely more of a minor thing, but I noticed in the compiled output (when `-d:release` is defined), it's still includes some path paths from the developer's machines.

While what I found seems pretty miniscule, I'm not a fan when my compiled code has information about my system (or some of the tools that I used).  This is fine when compiling a debug build, but not so much for a release.

### Example
I'm finding this in the output. 

```javascript
function assert_valid_date_173456(monthday_173458, month_173459, year_173460) {
		if (!((monthday_173458 <= get_days_in_month_173419(month_173459, year_173460)))) {
		failed_assert_impl_14255((makeNimstrLit("/home/me/.choosenim/toolchains/nim-0.20.0/lib/pure/times.nim(624, 10) `monthday <= getDaysInMonth(month, year)` ") || []).concat(cstrToNimstr((year_173460)+"") || [],makeNimstrLit("-") || [],nsuIntToStr(month_173459, 2) || [],makeNimstrLit("-") || [],cstrToNimstr((monthday_173458)+"") || [],makeNimstrLit(" is not a valid date") || []));
		}
}
```

### Additional Information
Nim Compiler Version 0.20.0
This happens when I compile with the `-d:release` flag.

**Comment by nc-x** [comment]
It is because now `--listFullPaths:on` is the default, so at compile time the paths will be stored in your final executable/js. You will need to disable the above option through your project's nimble file/nims file/cfg file if you want the previous behaviour.

**Comment by alaviss** [comment]
The flag in concern should be `--excessiveStackTrace`, which is now on by default. Passing `--excessiveStackTrace:off` should be enough.

**Comment by define-private-public** [comment]
I tried setting both of those two flags to `off` in my compile step and it didn't work.  Is there something else I'm missing?

**Comment by alaviss** [comment]
https://github.com/nim-lang/Nim/blob/f94ec363abf5b1393014a0bca7202c405512cddd/lib/system/assertions.nim#L34-L36

That's because of how `assert` work. Either we disable assertions (`--assertions:off`), or figure out why  there's this note here.

**Comment by Araq** [comment]
@alaviss Just remove it and see what it breaks. :-)
