### ISSUE TITLE
Overloading assignment operator doesn't work

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#11553]
Broken on 0.20.0 and devel, works on 0.19.6.

```nim
type
  ss = object

proc `=`(a: var ss, b: ss) =
  echo "A"

var
  p: ss
  q = p
```

Prints "A" on 0.19.6 but nothing >= 0.20.0.

**Comment by Araq** [comment]
Well the compiler now moves. Also overload ``=sink`` to see this. But it is a bug, if no move exists, the  overloaded assignment should have been used.

**Comment by doongjohn** [comment]
Any update?

**Comment by Clyybber** [comment]
The spec changed, the compiler will now use `=sink` whenever possible, and if its not defined delegating to a combination of `=destroy` and copyMem. See https://github.com/nim-lang/Nim/blob/devel/doc/destructors.rst#sink-hook
