### ISSUE TITLE
Incorrect overflow/underflow error in case statements

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11551]
Hello,

The below snippet used to work correctly before Nim 0.20.0:

### Example

```nim
proc negativeOrNot(num: int): string =
    result = case num
    of low(int) .. -1:         
      "negative"
    else:
      "zero or positive"
  echo negativeOrNot(-1)
  echo negativeOrNot(10000000)
  echo negativeOrNot(0)
```

### Current Output

> Error: unhandled exception: over- or underflow [OverflowError]

### Expected Output

```
negative
zero or positive
zero or positive
```

### Additional Information

Interestingly, this works:

```nim
proc negativeOrNot(num: int): string =
    result = case num
    # of low(int) .. -1:         # Error: unhandled exception: over- or underflow [OverflowError]
    # of (low(int)+1) .. -1:     # Error: unhandled exception: over- or underflow [OverflowError]
    of (low(int)+2) .. -1:       # works
      "negative"
    else:
      "zero or positive"
  echo negativeOrNot(-1)
  echo negativeOrNot(10000000)
  echo negativeOrNot(0)
```

It's not clear why `low(int)` and `low(int)+1` cause underflow, but not `low(int)+2`.

```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-20
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 678beb8ef982a3477018ff7c8669c4a9c6f77545
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment]
I get a similar overflow error for `of 1 .. high(int):`, `of 1 .. (high(int)-1):` and `of 1 .. (high(int)-2):`, but not for `of 1 .. (high(int)-3):`.

**Comment by dumjyl** [comment]
It just silently overflowed before :-/

**Comment by kaushalmodi** [comment]
@dumjyl I am fine with that error if I understand why `high(int)`, `high(int)-1` and `high(int)-2` overflow but not `high(int)-3`.

**Comment by kaushalmodi** [comment]
As I am playing around with that snippet, this is giving a strange error:

```nim
  proc positiveOrNegative(num: int): string =
    result = case num
    of (low(int)+2) .. -1:
      "negative"
    of 0:
      "zero"
    else:
      "impossible"
```

> Error: invalid else, all cases are already covered

How does that else-less case cover all the cases?

**Comment by kaushalmodi** [comment]
@dumjyl 

> It just silently overflowed before :-/

If you go to https://scripter.co/notes/nim/#case-statements and scroll down a bit to the `positiveOrNegative` proc, that whole snippet actually worked and returned the correct results.

**Comment by dumjyl** [comment]
Before when we overflowed the result would be requiring an else even if not necessary, which is why your example worked.

There a couple places where improvements could be made to case, ones i've found:
```nim
# Error: unhandled exception: over- or underflow [OverflowError]
case 1:
of low(int)..high(int): discard # use to require else instead of erroring.

# Invalid values for type, there are a couple variations with invalid types.
case range[1..1](1):
of 2: discard

# Error: expression '"empty"' is of type 'string' and has to be discarded
# use efWantValue for a better error
var x = case "1":
of "": "empty"
```

The way case coverage is checked is seeing if the length of the ordinal type matches the sum of the lengths of the branch values. Possible solutions: using `BiggestUInt` as the counter, saturating arithmetic, or storing values as integer ranges.

**Comment by narimiran** [comment]
@kaushalmodi, @dumjyl is right when he says:

> It just silently overflowed before :-/

Bootstrap your Nim with `-d:danger` flag (which turns off overflow checks, like `release` was doing pre-0.20) and you'll see it still compiles.

**Comment by kaushalmodi** [comment]
@narimiran I wouldn't want to have code deployed with overflow checks disabled.

The root question is why is it overflowing/underflowing at `low(int)` and `high(int)`, the low and high values are technically within the bounds of the given type, right?

Also the mysterious behavior with ..

> It's not clear why low(int) and low(int)+1 cause underflow, but not low(int)+2.

**Comment by GULPF** [comment]
The issue is that the number of cases covered in a case statement/expression is stored in a `int64`, and the number of covered cases can be larger than `high(int64)`. Here's an example where it causes a bug even with `-d:danger`:

```nim
proc foo(T: typedesc) =
    var x: T
    case x
    of low(T) .. high(T): discard
foo(int8) # Works
foo(int64) # not all cases are covered
```

**Comment by krux02** [comment]
Hmm, well I guess we finally need to have an integer type in the compiler that exceeds the capacity of all natively supported integer types.

**Comment by kaushalmodi** [comment]
@GULPF

> The issue is that the number of cases covered in a case statement/expression is stored in a int64

Should that be stored in **uint64** instead? That will automatically double the count storing capacity.

**Comment by kaushalmodi** [comment]
@krux02 This is fixed too, by your https://github.com/nim-lang/Nim/commit/7d5d9f7703901e092422d682f7ab21995cfa1122 PR.

Can you please add this as a test case and close this too?
