### ISSUE TITLE
Incorrect "cases all covered" error

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11552]
The compiler throws incorrect "Error: invalid else, all cases are already covered" error when actually they are not.

### Example

```nim
  proc positiveOrNegative(num: int): string =
    result = case num
    of (low(int)+2) .. -1:
      "negative"
    of 0:
      "zero"
    else:
      "impossible"
```

---

[Nim playground link][1]

### Current Output

> Error: invalid else, all cases are already covered

How does that else-less case cover all the cases?

### Expected Output

That error should not happen.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-20
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 678beb8ef982a3477018ff7c8669c4a9c6f77545
active boot switches: -d:release
```
---

Ref: https://github.com/nim-lang/Nim/issues/11551#issuecomment-504075017

[1]: https://play.nim-lang.org/index.html#ix=1MiY

**Comment by kaushalmodi** [comment]
This bug is explained by @GULPF's comment in https://github.com/nim-lang/Nim/issues/11551#issuecomment-504150755.

The `case` statement can contain a max of `high(int)` (`high(int64)` on 64-bit machines) cases.

Now,

- `high(int64)` = 9223372036854775807
- Number of cases in `of (low(int)+2) .. -1:` statement above = 9223372036854775806
  - `low(int)` = -9223372036854775808
  - `low(int)+2` = -9223372036854775806
  - So number of cases from -9223372036854775806 down to -1 = 9223372036854775806
- The `of 0` adds one more case to that count, so 9223372036854775806 + 1 = 9223372036854775807

With that, that reaches the max count of all the cases. So Nim thinks that "Oh, now I cannot handle any more cases", and so that `else` throws:

> Error: invalid else, all cases are already covered

I believe this issue can be fixed by saving the "count of cases" in a `uint64` type instead of in `int64` type variable as I mention in https://github.com/nim-lang/Nim/issues/11551#issuecomment-504389780.

The count will anyways never need to be negative.

/cc @krux02 @Araq What do you think?

**Comment by Araq** [comment]
Sure.
