### ISSUE TITLE
Is Nim fully self-hosted?

### ISSUE THREAD

**Issue by catastrop** [nim-lang/Nim#11550]
sorry for asking questions here.

**Comment by narimiran** [comment]
As people already told you on your previous "issue": *for questions like this a look at the dozen community channels may help: https://nim-lang.org/community.html*

You can ask these kinds of questions on IRC/Gitter or on our forum. Github's issue tracker is not the place for these questions.

**Comment by alehander42** [comment]
it is self-hosted in : it is written in Nim. however it's not if you target JavaScript: you can't really build the Nim compiler for JavaScript using JavaScript backend currently, however most people assume C backend, so it's fully hosted there(maybe except nimbase.h, but that's minimal)
