### ISSUE TITLE
Module and type name collisions with generics

### ISSUE THREAD

**Issue by dumjyl** [nim-lang/Nim#11568]
When there is module with the same name as a type, the module (of type void) seems to be preferred.

### Example
```nim
import string # file named string, contents don't matter
type
  Generic[T] = T
  Test = Generic[string] # thinks this is the module, with type void
  # Test = Generic[system.string] # workaround
var y: Test
```
 
The issue is pretty easy to find in the above example, but is more confusing with 500 lines of non-generic code and is about missing fields in code you didn't write.
### Current Output
```
Error: invalid type: 'void' in this context: 'Test' for var
```

### Expected Output
Selecting the type, or an ambiguity warning.

### Possible Solution
Rename the module or type (if you can), or qualify the type in generics, or import the module with an alias.

**Comment by Wh1teDuke** [comment]
Related https://github.com/nim-lang/Nim/issues/6052

**Comment by dumjyl** [comment]
Yes, similar enough, closing.
