### ISSUE TITLE
Set with non existent enums compiles

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#11571]
```nim
type
  SettingsBindFlag* {.size: sizeof(cint), pure.} = enum
    get = 0
    set = 1
    noSensitivity = 2
    getNoChanges = 3
    invertBoolean = 4

  SettingsBindFlags* {.size: sizeof(cint).} = set[SettingsBindFlag]

proc main =
  var x: SettingsBindFlags
  x = {SettingsBindFlag.get, SettingsBindFlag.set}
  x = {SettingsBindFlag.default}
  echo "OK"

main()
```

I am not sure if this may be an intended feature, but it is very bad. Compiling fine

x = {SettingsBindFlag.default}

gave me the impression default is a valid value, but it is not, and it is not defined in gio.mod. (Would be const default = {SettingsBindFlag.set, SettingsBindFlag.get}

**Comment by SolitudeSF** [comment]
`SettingsBindFlag.default` is `SettingsBindFlag.get`
https://nim-lang.github.io/Nim/system.html#default%2Ctypedesc

**Comment by StefanSalewski** [comment]
Oh, so it is not a bug, but can be a big trap. Will close this issue.
