### ISSUE TITLE
SIGSEGV while compiling when trying to instantiate a case type, that uses an enum with non-zero start

### ISSUE THREAD

**Issue by noonien** [nim-lang/Nim#11585]
The compiler produces a SIGSEGV when trying to compile a file that has a case type, that switches on an enum that does not have a 0 start value

### Example

```nim
type
  FooKind = enum
    fkBar = 1 # if this would be 0, the SIGSEGV would not occur

  Foo = object
    case kind*: FooKind
    of fkBar: bar*: int

Foo(hello: 0)
```

### Current Output
```
Traceback from system (most recent call last)
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```
Error: undeclared field: 'hello'
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-15
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```
This is 2019-06-25-devel-0d50b0c nightly build.

**Comment by dumjyl** [comment]
To possibly save someone some time:
The bug is here: https://github.com/nim-lang/Nim/blob/devel/compiler/semobjconstr.nim#L306
That val should be a valid val of the enum/range, or do something else if 0 is invalid. The first option may not be strictly correct though because of zero init.
