### ISSUE TITLE
invalid object assignment when converting types

### ISSUE THREAD

**Issue by Arnaz87** [nim-lang/Nim#11592]
According to the [convertible relations](https://nim-lang.org/docs/manual.html#type-relations-convertible-relation) section, a child type should be explicitly convertible to it's base type.

Although the code does compile, at runtime it throws an `ObjectAssignmentError`. It should either not compile at all, or run correctly.

### Example
```nim
type
  Base = object of RootObj
    name: string
  Child = object of Base
    age: int

var child = Child(name: "foo", age: 42)
var base: Base = Base(child)
echo base
```

### Current Output
```
test.nim(8)              test
assign.nim(124)          genericAssign
assign.nim(97)           genericAssignAux
system.nim(2918)         sysFatal
Error: unhandled exception: invalid object assignment [ObjectAssignmentError]
Error: execution of an external program failed: '.../test'
```

### Expected Output
```
(name: "foo")
```

### Additional Information
It was working in a previous release, I don't know how long ago, but at least beginning 2018

```
$ nim -v
Nim Compiler Version 0.19.6 [Linux: amd64]
Compiled at 2019-05-14
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```

#### Backwards
 It doesn't work backwards either, from child to parent. Fails at runtime too rather than at compile. I don't know if this one worked before, but according to the manual it should too, I believe.
```nim
type
  Base = object of RootObj
    name: string
  Child = object of Base
    age: int

var base = Base(name: "foo")
var child = Child(base)
echo child
```

**Comment by Araq** [comment]
Types can be "convertible" but the conversion can fail at runtime. Which is what happens here and it's correct. Previously it went undetected.

**Comment by Arnaz87** [comment]
Why does it fail? It had predictable behaviour: everything in the child that's not part of the parent is dropped, and in the other way, those same fields are set to default values.

How does one know now what kind of conversions are valid and which are not?

**Comment by andreaferretti** [comment]
Notice that here only the last line fails

```nim
type
  Base = object of RootObj
    name: string
  Child = object of Base
    age: int

proc print(b: Base) =
  echo b.name

let child = Child(name: "foo", age: 42)
print(child) # this is ok
print(Base(child)) # strangely, this is also ok

let b = Base(child) # only when assigning, we have a failure
```

**Comment by Arnaz87** [comment]
Returning it from a procedure also fails, even if not assigning

```nim
proc convert (b: Base): Base = return b
echo convert(child)
```

**Comment by Araq** [comment]
Whenever data would be lost it fails. Consistent with all the other allowed but checked conversions.

**Comment by disruptek** [comment]
```nim
print(Base(child))
```
How is this not an example of the loss of data?

**Comment by Araq** [comment]
Because it's not stored anywhere?
