### ISSUE TITLE
New playground is available at https://nim.ide.judge0.com

### ISSUE THREAD

**Issue by hermanzdosilovic** [nim-lang/Nim#11599]
Hi,

I am the author of [Judge0](https://github.com/judge0) and I have deployed free alternative playground for Nim programming language. It is available at https://nim.ide.judge0.com.

Take a look at my [release notes](https://github.com/judge0/api/releases/tag/v1.2.0-nim0.20.0) that describe my current plan with maintaining this. Let me know what you think.

Best regards,
Herman

**Comment by andreaferretti** [comment]
That's great to know! I think you can spark more discussion by posting the same news on the [official forum](https://forum.nim-lang.org/)

**Comment by kaushalmodi** [comment]
@hermanzdosilovic Can we have an Emacs mode?

**Comment by kaushalmodi** [comment]
@hermanzdosilovic Can you also have a window to show compile time messages? They are very important when designing macros. 

E.g. I'd like to see what's printed on stdout when just compiling http://ix.io/1MUr.

**Comment by narimiran** [comment]
> Can you also have a window to show compile time messages?

Wouldn't these kind of comments/issues/discussion be better suited for https://github.com/judge0/ide/issues ?



And I agree with @andreaferretti, this is an announcement and our forum or other discussion channels (r/nim, twitter, IRC, etc.) are better suited for it than issue tracker.

**Comment by kaushalmodi** [comment]
> Shouldn't these kind of comments/issues/discussion be posted on https://github.com/judge0/ide/issues ?

Done.

**Comment by mratsim** [comment]
Closing then since there is a proper channel for feature requests.
