### ISSUE TITLE
source in Nim docs does not point to the correct location

### ISSUE THREAD

**Issue by komuw** [nim-lang/Nim#11604]
To reproduce;
- visit the nim documentation eg `proc debugEcho`: https://nim-lang.org/docs/system.html#debugEcho%2Cvarargs%5Btyped%2C%5D
- click on the `Source` link. 

What did I expect:   
I expected it to take me to the source code where `proc debugEcho` is defined.

Instead:  
It took me to  https://github.com/nim-lang/Nim/blob/master/lib/system.nim#L3332

Prognosis:  
I think the links should point to the github tag that the documentation was produced with. 
ie, the correct link should be; https://github.com/nim-lang/Nim/blob/v0.20.0/lib/system.nim#L3332

**Comment by narimiran** [comment]
Already fixed, but it will be visible when the next stable version is released.

If you want the working source links in the mean time, you can use devel docs at https://nim-lang.github.io/Nim/lib.html
