### ISSUE TITLE
Playground gives Error 502

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#11601]
Any input on https://play.nim-lang.org/ results into Error 502.

Output from https://play.nim-lang.org/compile:
```
Error 502 Ray ID: 4ecf6bdc1e65bec4 • 2019-06-26 13:10:27 UTC

Bad gateway

The web server reported a bad gateway error.
```

**Comment by mratsim** [comment]
cc @PMunch

**Comment by PMunch** [comment]
Yes, after trying to secure it a bit further I managed to remove sudo access from my account.. Waiting for @dom96 to restore it, and I'll get it up and running again.

**Comment by dom96** [comment]
@PMunch Resolved.

**Comment by PMunch** [comment]
The playground is back up and running now, so this can be closed :)
