### ISSUE TITLE
Converter interferes with overload resolution

### ISSUE THREAD

**Issue by rokups** [nim-lang/Nim#11622]
```nim
type ustring = distinct string

proc substr*[T, U](s: ustring; first: T; last: U): string =
  echo "worked!"
  return substr(string(s), first, last)

converter toString*(s: ustring): string = string(s)
    ## Converts ``ustring`` type to ``string``

echo ustring("foo").substr(1, 2)
```

When converter is available compiler generates a call to `system.substr(s: string, ...)` and "worked" does not get printed. Removing converter sample properly calls `substr*[T, U](s: ustring; ...)`.

### Additional Information
```
~ % nim -v
Nim Compiler Version 0.20.0 [Linux: amd64]
Compiled at 2019-06-19
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e7471cebae2a404f3e4239f199f5a0c422484aac
active boot switches: -d:release
```

**Comment by Araq** [comment]
Works as the spec says it works, ``system.substr`` has two exact matches, yours only has 2 "generic" matches. If you want to hijack system.substr, do it properly:

```nim

proc substr*(s: ustring; first, last: int): string =
  echo "worked!"
  return substr(string(s), first, last)
```

**Comment by rokups** [comment]
Oh thanks! And sorry for the noise. I thought this may be related to 9165. My bad.
