### ISSUE TITLE
Newruntime - Error: cannot return an owned pointer as an unowned pointer; use 'owned(Socket)' as the return type

### ISSUE THREAD

**Issue by stefanos82** [nim-lang/Nim#11629]
Here's the code:

```nim
import htmlgen
import jester

routes:
  get "/":
    resp h1("Hello world")
```
Here's the command: 
```bash
nim c --newruntime -r src/jst.nim
```
and here's the entire output it throws upon execution of the aforementioned command: 
```txt
/home/stefanos/GIT_CODES/Nim/lib/pure/net.nim(193, 10) Error: 
cannot return an owned pointer as an unowned pointer; 
use 'owned(Socket)' as the return type
```

**Comment by alaviss** [comment]
To fix this you'd only need to add `owned` to the `newSocket` proc in `net.nim`. That's pretty much how you port stuff to `newruntime`. Add `owned` until your program compiles.

**Comment by stefanos82** [comment]
Ah that means I need to edit `lib/pure/net.nim`. Shall I wait then until the official support? I don't want to mess the code with my limited knowledge.

**Comment by alaviss** [comment]
Edit it then if it works well open a PR :)

**Comment by narimiran** [comment]
This has been fixed in 5f515410a

**Comment by stefanos82** [comment]
I've just pulled the latest HEAD; this is what I get now:

```txt
nim c --newruntime -r src/jst.nim 
/home/stefanos/GIT_CODES/Nim/lib/impure/re.nim(50, 6) Error: type mismatch: got <ref RegexError>
but expected one of: 
proc new[T](a: var ref T; finalizer: proc (x: ref T) {.nimcall.})
  first type mismatch at position: 2
  missing parameter: finalizer
2 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: new(e)
```
Is this the expected behavior?

**Comment by alaviss** [comment]
Certainly unexpected, but appears to be a seperated bug. Please file an another issue for this
