### ISSUE TITLE
Compiler doesn't warn when using {.global.} and {.threadvar.} on JS backend despite it not working

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#11625]
This includes the `once` template from `system` which depends on the pragma working.

**Comment by timotheecour** [comment]
was about to report this but found this issue.
Ditto with `{.threadvar.}`
```nim
  proc getState*(): int =
    var state0 {.global.}: int # ditto w threadvar
    state0.inc
    return state0

  for i in 0..<3:
    echo getState()
```
prints:
```
1
1
1
```
instead of:
```
1
2
3
```

**Comment by krux02** [comment]
@timotheecour threadvar is a different case. A threadvar is often is global scope where it should have one instance per thread. When there is no other thread possible, it is technically working in js.

**Comment by timotheecour** [comment]
I don't see how that could be considered working with nim js + threadvar; it's as if `{.threadvar.}` annotation was ignored and `state0` was turned into a local variable. Each call to `getState()` clearly is from same thread. The fact that js is single threaded just means that global and threadvar should behave identically.

**Comment by dawkot** [comment]
I really think there should at least be a warning until it gets fixed.

**Comment by timotheecour** [comment]
@dawkot agreed, please send a PR

**Comment by krux02** [comment]
My PR that introduced an error message was rejected.

**Comment by timotheecour** [comment]
then we should bite the bullet and fix the bug, so that {.global.} and {.threadvar.} work for nim js, with no warning or error, and have same semantic as `nim c --threads:off` ; that's the least surprising, most useful behavior, avoiding to special case for nim js.

the fix should be to properly handle sfGlobal in compiler/jsgen.nim
