### ISSUE TITLE
'typedesc' inside a parameter list is treated incorrectly by the doc gen

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#1164]
As can be seen here http://nim-lang.org/docs/system.html#new,typedesc

**Comment by ephja** [comment]
Does it look correct now?

**Comment by ephja** [comment]
Is it rendering correctly now?

**Comment by Yardanico** [comment]
@ephja well it's the same as in source code:
![image](https://user-images.githubusercontent.com/21169548/30429321-b3fe35ae-995f-11e7-920d-3ef03310370d.png)
![image](https://user-images.githubusercontent.com/21169548/30429324-b83a42d4-995f-11e7-8296-4b4f1ba311d3.png)

**Comment by andreaferretti** [comment]
Guess can be closed then?
