### ISSUE TITLE
For loops over a hardcoded empty array crash the compiler.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#11684]
A for loop over a hardcoded empty array, which is meaningless, causes the compiler to have an internal error.

### Example
```nim
for _ in []:
  discard
```

### Current Output
```
Error: internal error: getTypeDescAux(tyEmpty)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

### Expected Output
```
```

This occurs on the latest devel and stable.

**Comment by ringabout** [comment]
Duplicate of https://github.com/nim-lang/Nim/issues/19224
