### ISSUE TITLE
cgen preprocessor directive placed after struct declaration

### ISSUE THREAD

**Issue by muiroc** [nim-lang/Nim#11691]
When compiling with --debugger:native this line gets generated:
(note the ifndef after the comma)
```
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {  NI len; tySequence_sM4lkSb7zS6F7OVMvW9cffQ_Content* p;};#ifndef tySequence_uB9b75OUPRENsBAu4AnoePA_Content_PP
```
causing a compile error:
```
error C2014: preprocessor command must start as first nonwhite space
fatal error C1020: unexpected #endif
```

### Possible Solution
temporarly I tried changing this
https://github.com/nim-lang/Nim/blob/b50ae6817a8cf558eedbee5e405dd68a7d22edd8/compiler/ccgtypes.nim#L410
to
```nim
          "};$N", [result])
```
seeing that by enabling debugger:native this options are set
https://github.com/nim-lang/Nim/blob/b50ae6817a8cf558eedbee5e405dd68a7d22edd8/compiler/commands.nim#L480
optLineDir is setted and then used in
https://github.com/nim-lang/Nim/blob/b50ae6817a8cf558eedbee5e405dd68a7d22edd8/compiler/cgen.nim#L168

For the record, there are other newline related differencies:
without debugger:native
```c
struct tyObject_Pixels_d9cAAoDxyHitNWVHpUYE8JA {
tyEnum_PixelFormat_pFNxyFdipagghtQvPb8fig format;
tyObject_Extent3_8mqbEC9c9ba9a2dnSHRkGEI9aw dim;
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ bytes;
};
```
with debugger:native
```c
struct tyObject_Pixels_d9cAAoDxyHitNWVHpUYE8JA {tyEnum_PixelFormat_pFNxyFdipagghtQvPb8fig format;
tyObject_Extent3_8mqbEC9c9ba9a2dnSHRkGEI9aw dim;
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ bytes;
};
```
and some "two structs on a line"
```c
struct tySequence_uB9b75OUPRENsBAu4AnoePA {  NI len; tySequence_uB9b75OUPRENsBAu4AnoePA_Content* p;};struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence_uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
```
### Additional Information
--newruntime
devel
```
git hash: 655cb084610cde787f9b78360b96b3b97541112b
active boot switches: -d:release
```

**Comment by mratsim** [comment]
Does it happen without the `--newruntime` switch?

**Comment by muiroc** [comment]
@mratsim 
Just tried and without --newruntime it compiles fine

Forgot to say that the generated file where this happens is ```stdlib_system.nim.c```

Without newruntime I see there are neither any "ifndef/define/endifs" blocks nor structs with ```tySequence_stuff_Content```

I tried creating a small repro project, but it compiles fine even with newruntime, I can't seem to trigger that declarations ordering...
