### ISSUE TITLE
Shorter method links

### ISSUE THREAD

**Issue by cup** [nim-lang/Nim#11698]
Links to Nim methods include the name of the method, as well as the type of all
arguments:

- https://nim-lang.github.io/Nim/strutils#replace,string,char,char
- https://nim-lang.github.io/Nim/strutils#replace,string,string,string

This is needed to disambiguate methods that have the same name, but different
sets of arguments. However I find the result pretty verbose. Compare with D
language:

- https://dlang.org/library/std/array/replace#0
- https://dlang.org/library/std/array/replace#1

**Comment by kaushalmodi** [comment]
> Compare with D language:

That's a terrible style of generating links IMO. Tomorrow if a new `replace` is documented above the first one, the original first `replace` will now have `#1` link instead of `#0` now. 

The links will keep on moving with such changes. 

That issue is averted by how Nim linkifies things.

**Comment by cup** [comment]
Ok good point.

Maybe another option is available that satisfies both sides, something like

https://nim-lang.github.io/Nim/strutils#replace,s,s,s

**Comment by SolitudeSF** [comment]
and if two types have same first letter?

**Comment by cup** [comment]
@SolitudeSF good point.

I see even on the page I linked that would be an issue. These:

- http://nim-lang.github.io/Nim/strutils#split,string,string,int
- http://nim-lang.github.io/Nim/strutils#split,string,set[char],int

would both become:

http://nim-lang.github.io/Nim/strutils#split,s,s,i

So in that case 2 letters would be needed:

- http://nim-lang.github.io/Nim/strutils#split,s,st,i
- http://nim-lang.github.io/Nim/strutils#split,s,se,i

I could work up an algorithm if people are open to it.

**Comment by kaushalmodi** [comment]
> I could work up an algorithm if people are open to it.

What's the benefit of shorter links?

I like the readable types in the links as we have right now. With the type acronyms, the links will get a bit shorter but then they will look gibberish.

**Comment by cup** [comment]
@kaushalmodi what about middle ground, something like this:

~~~
http://nim-lang.github.io/Nim/strutils#split-str-str-int
http://nim-lang.github.io/Nim/strutils#split-str-set-int
~~~

done like this:

1. remove any brackets
2. change commas to dashes
3. use 3 letter variant, still readable

**Comment by kaushalmodi** [comment]
Also, I believe it would need some maintenance to keep the algorithm always working to meet some signature that we haven't seen yet. And then when the algorithm is updated to support that, there's a risk that the links generated by the previous algorithm are now all changed. 

I'm saying so because I heavily use the Nim doc links in my notes: https://scripter.co/notes/nim/

**Comment by cup** [comment]
@kaushalmodi what about middle ground, something like this:

~~~
http://nim-lang.github.io/Nim/strutils#split-str-str-int
http://nim-lang.github.io/Nim/strutils#split-str-set-int
~~~

done like this:

1. remove any brackets
2. change commas to dashes
3. use 3 letter variant, still readable

**Comment by kaushalmodi** [comment]
> change commas to dashes

I prefer dashes to commas. 

But I don't understand the problem statement here? Now the docs have hyperlinked procs, so you just right click and copy, and paste anywhere you like. 

His change is going against my personal preference that "if it ain't broke, don't fix it" :)

*Note that I am not in any power to accept or deny your proposal, just giving my opinion.*

As an aside the docs have few open issues, where we can use your help. 

*I recognize you from an earlier issue where you helped me fix the link issue on IE, I believe. So your experience with web dev will be useful in those doc site issues.*

**Comment by cup** [comment]
@kaushalmodi thanks for the reasoned response. I am ok if the full proposal is
not adopted. if just the brackets removed and commas changed to dashes that
would be good start.

however i still link shorter link would be better, if it can be done in a
reasonable way. some people maybe avoid longer links, such at greater than 80
characters. Many JavaScript link are long:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

they can be shorten some as some path elements are optional:

https://developer.mozilla.org/JavaScript/Reference/Global_Objects/String/replace

but even then still pretty long. anyway I leave it for others to decide, just
wanted to give my point of view.

**Comment by narimiran** [comment]
Who will replace/fix all the manually created links in the documentation? (in `See also` sections)

This gets thumb down from me, I don't see the benefits.

**Comment by Araq** [comment]
Sorry, rejected. We would never find all old links and update them. Links must be stable, stability is FAR more important than conciseness.

**Comment by cup** [comment]
To any interested, here is a [Hugo](//github.com/gohugoio/hugo) shortcode that
solves this:

~~~html
{{ $href := .Get 0 -}}
{{ $a1 := split $href "," -}}
{{ $text := index $a1 0 -}}
<a href="https://nim-lang.github.io/Nim/{{ $href }}">{{ $text }}</a>
~~~

Input:

~~~
{{< nim "tables#toTable,openArray[]" >}}
~~~

Output:

~~~html
<a href="https://nim-lang.github.io/Nim/tables#toTable,openArray[]">tables#toTable</a>
~~~
