### ISSUE TITLE
array constructor with indices offset mismatch

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#11696]
I'd expect this constructor to create an array starting at offset 10:

```
let t = [ 10: "A", 11: "B", 12: "C" ]
echo t[10]
```

But instead the indices [0, 1, 2] are used:

```
/tmp/t.nim(2, 45) Error: index 10 not in 0 .. 2
```

**Comment by dumjyl** [comment]
This was fixed in https://github.com/nim-lang/Nim/pull/11424, but wasn't backported since old code using `0..2` indexing would break.

**Comment by zevv** [comment]
Fair enough, but in my opinon code using `0..2` is kind of broken by itself.

I think there can be no discussion about the intention of the programmer when writing `[ 10: "A", 11: "B", 12: "C" ]`. Ending up with an array where the indices are simply ignored kind of defeats the whole purpose of the constructor syntax. This feels very broken to me.

**Comment by dumjyl** [comment]
Yeah, I agree. It's the reason I'm still using nightlies...

**Comment by Araq** [comment]
Works on devel, closing.
