### ISSUE TITLE
static arg for `[]` causes deref to fail in typeof within template

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#11705]
### Example
```nim
type RefObj = ref object

proc `[]`(val: static[int]) = # works with different name/overload or without static arg
  discard

template noRef*(T: typedesc): typedesc = # works without template indirection
  typeof(default(T)[])

proc `=destroy`(x: var noRef(RefObj)) =
  discard
```

### Current Output
```
Error: type mismatch: got <static[RefObj](nil)>
but expected one of: 
proc `[]`(val: static[int])
... more overloads
```

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 87a2ced1baec059922a567e2000c0fe16cc1db52
```

**Comment by mratsim** [comment]
I've also had my woes with `[]` overloading preventing dereferencing: https://github.com/mratsim/Arraymancer/issues/185

This is especially annoying when you need a template with a `varargs[untyped]` signature:
```Nim
template `[]`*[TT](v: Variable[TT], args: varargs[untyped]): Variable[TT] =
```

Tagging language design. Personally I'd rather have a `proc deref[T](x: ref T or ptr T): T {.magic: mDeref.}` that maps to `nnkDerefExpr` to avoid the 2 corner cases:

- Cannot dereference when overloading unary `[]`
- Have to special-case the varargs.len = 0 when overloading a type + varargs `[]` which was already error-prone https://github.com/nim-lang/Nim/issues/8706

Should I open a RFC?
