### ISSUE TITLE
Converters don't work with tuple fields

### ISSUE THREAD

**Issue by liquid600pgm** [nim-lang/Nim#11703]
As mentioned in the title, converters do not work with tuple fields.
### Example
```nim
type
  A = object
  B = object
  Tup = tuple
    b: B

converter toB(a: A): B = B()

proc p(t: Tup) = discard

p((A()))

```

### Current Output
```
/usercode/in.nim(11, 2) Error: type mismatch: got 
but expected one of: 
proc p(t: Tup)

expression: p(A())
```

### Expected Output

The A passed as a tuple field should be converted into a B by the converter.

### Additional Information
```
❯ nim -v
Nim Compiler Version 0.20.0 [Linux: amd64]
Compiled at 2019-06-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e7471cebae2a404f3e4239f199f5a0c422484aac
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
I think this is intentional, converters are not applied recursively

**Comment by Araq** [comment]
This is not a bug, type conversions are not lifted into tuples. (And that's a good thing.)
