### ISSUE TITLE
Runtime crash with no stack trace when Nim HCR is used with streams

### ISSUE THREAD

**Issue by zacharycarter** [nim-lang/Nim#11718]
When reading from a FileStream using Nim HCR, a runtime crash occurs that is only reproducible when HCR is enabled. No stack trace is returned when the crash occurs.

### Example
https://gist.github.com/zacharycarter/2555ccf9e7afcb6f5a27cd0934942f38 - two files here. One is a map file I'm parsing, and the second is the parsing code. Place the map file in the same directory as the nim source.

Compile with - `nim c -r --hotCodeReloading:on .\foo.nim` - notice the crash.
Compile with - `nim c -r .\main.nim` - notice the program runs as expected.

### Current Output
```

C:\Users\carte\.choosenim\toolchains\nim-0.20.0\lib\pure\collections\tables.nim(263) []
Error: unhandled exception: key not found: failedAssertImpl_W9cjVocn1tjhW7p7xohJj6A [KeyError]
Error: execution of an external program failed: 'C:\Users\carte\projects\zeal\main.exe '
```

### Expected Output

```
@["grass.png", "cliffs.png", "cobblestone.jpg", "grass2.jpg", "dirty_grass.jpg", "cracked_dirt.jpg", "dirt_road.jpg", "metal_platform.jpg", "snowy_grass.jpg", "lava_ground.jpg", "sand.jpg"]
```

### Additional Information
I don't have Valgrind, but here's a link to some Dr. Memory output - https://gist.github.com/zacharycarter/85b15100361498a54077edd45f4a15b2
```
PS C:\Users\carte\projects\zeal> nim -v
Nim Compiler Version 0.20.0 [Windows: amd64]
Compiled at 2019-07-07
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches:
```

**Comment by zacharycarter** [comment]
I've taken a closer look as to what is going on here, and while I found a work-around that I can employ to unblock myself, the issue still remains at large.

If the following line is commented out - https://github.com/nim-lang/Nim/blob/devel/lib/system/assertions.nim#L38 - the program no longer crashes, however the program also does not produce the expected output of:

```
@["grass.png", "cliffs.png", "cobblestone.jpg", "grass2.jpg", "dirty_grass.jpg", "cracked_dirt.jpg", "dirt_road.jpg", "metal_platform.jpg", "snowy_grass.jpg", "lava_ground.jpg", "sand.jpg"]
```

which it will if you compile without the `--hotCodeReloading:on` compiler switch...

I find that if I just completely remove the asserts from my code, then the code runs and produces the correct output - so I imagine that a deeper issue is lurking here, but as to what exactly, I'm not sure.

**Comment by nc-x** [comment]
Minimal Repro -
```nim
var x = newSeq[string]()
echo x
```
```
C:\Nim\lib\nimhcr.nim(527) hcrInit
C:\Nim\lib\nimhcr.nim(498) initModules
C:\Nim\lib\nimhcr.nim(458) initPointerData
C:\Nim\lib\nimhcr.nim(350) hcrGetProc
C:\Nim\lib\pure\collections\tables.nim(263) []
Error: unhandled exception: key not found: failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A [KeyError]
```
