### ISSUE TITLE
Unable to alias echo from the system module

### ISSUE THREAD

**Issue by Obround** [nim-lang/Nim#11731]
When I try to import `echo` from the `system` module under the alias `my_echo`, I get this error:

```
c:\Users\Obround\Desktop\Nim_tests\my_test.nim(1, 25) Error: identifier expected, but found 'echo as my_echo'
```

This is my code:
```nim
from system import echo as my_echo
my_echo "Hello World"
```

I believe this error is happening because the compiler thinks I want to echo an output instead of alias it. Is this a bug, or am I doing something incorrect (I *think* its a bug)?

**Comment by SolitudeSF** [comment]
`as` is for importing modules under different name, not renaming symbols in the module.

**Comment by mratsim** [comment]
It seems like `echo` is treated as a keyword and only the following structure is allowed `from [module] import [identifier] as [identifier]`.

`echo` is not listed as a keyword in the manual though: https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords

**Comment by Araq** [comment]
That's not how ``as`` works, you can only use ``as`` to alias module names, not arbitrary identifiers. And for modules this feature only exists to allow for multiple modules of the same name to be imported.

**Comment by Obround** [comment]
@Araq -- Is there some other way I can alias `echo`?

**Comment by timotheecour** [comment]
my PR https://github.com/nim-lang/Nim/pull/11822 fixes this: `my_echo:=system.echo` works
