### ISSUE TITLE
Newruntime: Bad codegen for array literal of type containing a seq/string

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#11745]
The following produces bad C++ code with `--newruntime` for the default initialization of the `seq` field. Same for `bar: string`:
```nim
type
  Foo = object
    bar: seq[int]

var x = [Foo()]
```
Error:
```
error: cannot convert ‘std::nullptr_t’ to ‘NI’ {aka ‘long long int’} in initialization
```
here:
```c
NIM_CONST tyArray_Nni2tPVaSqbVPMO9bAfBdbA TM_H9aZRa5RQ4PW0NQPjTx0oeQ_2 = {{NIM_NIL}
```

**Comment by Araq** [comment]
Works for me.

**Comment by jwollen** [comment]
I can't say for sure which version of gcc I was using, but I can't reproduce it with gcc anymore.
The problem still persists with clang though.

**Comment by Araq** [comment]
But I tested on OSX which uses clang. But maybe a different clang version.

**Comment by jwollen** [comment]
Hm, curious!
I tried with both a fresh Nim build and packaged release and the code generated for `seq` is this:
```nim
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence_qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
```
which isn't compatible with literal `{NIM_NIL}`...
I believe the literal is generated [here](https://github.com/nim-lang/Nim/blob/58e0dad3712d4e423fd26bd91b26b8a31a85bf33/compiler/ccgexprs.nim#L2714).

Btw this only fails with `nim cpp`. With gcc and/or the c-backend the cast is swallowed.
