### ISSUE TITLE
db_mysql.nim is missing sql* proc

### ISSUE THREAD

**Issue by milosn** [nim-lang/Nim#1176]
I needed to add this to db_mysql.nim to make it work:

    proc sql*(query: string): TSqlQuery {.noSideEffect, inline.} =  
      ## constructs a TSqlQuery from the string `query`. This is supposed to be 
      ## used as a raw-string-literal modifier:
      ## ``sql"update user set counter = counter + 1"``
      ##
      ## If assertions are turned off, it does nothing. If assertions are turned 
      ## on, later versions will check the string for valid syntax.
      result = TSqlQuery(query)

**Comment by Araq** [comment]
db_common.nim exists now.
