### ISSUE TITLE
Compiler crash with variant object that has int discriminant

### ISSUE THREAD

**Issue by chr-1x** [nim-lang/Nim#11765]
Compiler crashes with the following error when compiling this code snippet:

### Example

``` Nim
type Foo = object
  case dim: int
  of 2:
    pos2: seq[int]
  else: discard

let foo = Foo(dim: 2, pos2: @[])
```

### Current Output
```$ nim c -r repro_crash
Hint: used config file '/home/chr/.choosenim/toolchains/nim-0.20.2/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: repro_crash [Processing]
fatal.nim(39)            sysFatal
Error: unhandled exception: over- or underflow [OverflowError]
```

### Expected Output

Successful compilation (maybe), or an actual error message instead of a fatal error.

### Possible Solution

¯\\\_(ツ)_/¯

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```
Installed with `choosenim stable`

Crash also occurs in 0.20.0. In 0.19.6, the following error is printed instead:

```
repro_crash.nim(2, 3) Error: low(dim) must be 0 for discriminant
```

**Comment by mratsim** [comment]
Tagging language design. I guess we probably should restrict variant to the same restrictions as the built-in `set`, `int16` at most?

**Comment by GULPF** [comment]
Interestingly the example works when `pos2` is not a seq or a string.
