### ISSUE TITLE
can't compile Nim 0.20.2 with nim-lang/csources 0.20.0 (latest Git HEAD)

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#11774]
```text
compiler/nim1 c  -d:release --nimcache:nimcache/r_linux_amd64 compiler/nim.nim
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/config/nim.cfg' [Conf]
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/nim.cfg' [Conf]
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/compiler/nim.cfg' [Conf]
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/config/config.nims' [Conf]
Hint: system [Processing]
/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/lib/system/threadlocalstorage.nim(111, 7) Error: 'passL' should be: 'passl'
FAILURE
```

**Comment by alaviss** [comment]
It compiles just fine here, in fact, this is even a part of the CI pipeline, which passed: https://travis-ci.org/nim-lang/Nim/jobs/559645455

I think there's a problem with your setup. Try removing the compiler executable from `bin/` and compile csources again?

**Comment by stefantalpalaru** [comment]
Found the problem: in my top level "nim.cfg", outside the Nim source directory, I have `--threads:on` which enables some code paths not normally enabled, where that style violation appears.

**Comment by stefantalpalaru** [comment]
Why are "--skipUserCfg" and "--skipParentCfg" only added to the first iteration here? https://github.com/nim-lang/Nim/blob/v0.20.2/koch.nim#L301

They should be enabled for all iterations.
