### ISSUE TITLE
import by referance

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#11784]
### Summary

Great! I don't think it is not the right place but I have a idea to improve coding style.

Think like that; You have a multiple modules and same variable names but different values. It could cause a complication. Am i right? actually i am new to nim programing language.

//# saying.nim
const say = "asd"
//# runsay.nim
import saying
echo "hello " & asd

### Description

//# saying.nim
const say = "asd"
//# saying2.nim
const say = "qwe"
//# runsay.nim
import saying
import saying2
echo "hello " & saying.asd

### Alternatives

//# saying.nim
const say = "asd"
//# runsay.nim
import saying.asd
echo "hello " & asd

-*-*-*-* OR -*-*-*-*-

//# saying.nim
const say = "asd"
//# runsay.nim
from saying import asd
echo "hello " & asd

**Comment by SolitudeSF** [comment]
you should read tutorial or manual before creating an issue. if there is a clash between symbols from different modules you can specify the module explicitly, import only selected symbols or import all but some symbols.
