### ISSUE TITLE
[Doc] [Suggestion] Typeclass/Variant clarification in Manual

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#11798]
A reoccurring theme I've noticed with certain newcomers to Nim (I assume coming from ML-related languages) is some confusion with the difference between a typeclass and a variant. It doesn't help that much that the syntax for a typeclass:
```nim
type SomeTypeclass = string | int
```
is very similar to the variant syntax in say, OCaml or Haskell. Therefore maybe the manual should probably recommend also looking at Nim variants in the type section (et vice versa?) and make it clear that typeclasses are purely a compile-time constraint enforced at instantiation.

**Comment by Araq** [comment]
A really good idea!
