### ISSUE TITLE
Sign of certain short constants is wrong

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#1179]
When using hexadecimal/binary constants with `'u8`, `'u16`, etc. with the highest bit is set, the compiler seems to have trouble with them. Also, having temporary `char(x)` values, where `x` is negative, seems to run into related problems.

```nimrod
import unsigned, typetraits

let x = 0x80'u8 shr 7
let y = 128'u8 shr 7
echo x.type.name, " ", y.type.name
echo x, " ", y
echo 0x80'u8
echo 0b10000000'u8
echo char(-1) < char(0)
```

**Comment by Araq** [comment]
@ozra Did your PR address this?

**Comment by ozra** [comment]
@Araq No, that part of the logic was left pretty much untouched in my PR, I focused on the test cases I had available and the _parsing_.

**Comment by Araq** [comment]
Ozra: Well you know what you have to do then. ;-)

**Comment by ozra** [comment]
Haha, I'll have a stab at it :)
