### ISSUE TITLE
Showstopper regression. Generated executable fails with heap memory corruption at the startup

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11792]
My nim app compiles and runs, but dies soon after the startup with heap corruption.
I have bisected the git and found offending commit: 20d0ef8afbd4b7b74c24f069841cce52cd5beaff

After analyzing the generated code before and after this commit I have managed to come up with the test case:
```nim
type
  m256d {.importc: "__m256d", header: "immintrin.h".} = object

  MyKind = enum
    k1, k2, k3

  MyTypeObj = object
    kind: MyKind
    x: int
    amount: UncheckedArray[m256d]

echo sizeof(MyTypeObj)
```
Current nim devel returns 0 as the size of ``MyTypeObj``, previously it was 32.

**Comment by cooldome** [comment]
I have the fix for this issue

**Comment by Araq** [comment]
Oh ok. Keep in mind that I'm on holidays. But I'm sure @krux02 or @narimiran will merge it ASAP.

**Comment by sinkingsugar** [comment]
not sure if related but `amount` should be `ptr UncheckedArray[m256d]`, afaik some commits ago `ptr` became mandatory, did that change again? (was legal before)
