### ISSUE TITLE
Incorrect "imported and not used" caused by reexport

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#11809]
Module usage is not detected when only reexported symbols are used.

#### module_b.nim
```nim
import unicode
export unicode
```
#### module_a.nim
```nim
import module_b
echo 67.Rune
```
### Current Output
```
Warning: imported and not used: 'module_b'
```

### Additional Information
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-21
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 67a6effb7bf4d319c8bafd65c75a4da47e007c24
active boot switches: -d:release -d:danger
```

**Comment by timotheecour** [comment]
likewise, `imported and not used` doesn't work with magics, eg:

mylib.nim:
```nim
# just an example; could be another magic
proc unsafeAddr2*[T](x: T): ptr T {.magic: "Addr", noSideEffect.} = discard
```

main.nim:
```nim
import ./mylib
var x = 12
echo cast[int](unsafeAddr2(x))
```
Warning: imported and not used: 'mylib'

**Comment by krux02** [comment]
I think the real issue here is that you are able to define a proc outside of the Nim repository without getting an error message.

**Comment by timotheecour** [comment]
no, it's the same if that magic is defined inside nim repo, eg in `typetraits.nim`

**Comment by timotheecour** [comment]
here's another example that I just ran into, that doesn't involve adding a new magic:

```nim
import macros

macro bar(): untyped =
  template baz() = discard
  result = getAst(baz())

bar()
```

# Warning: imported and not used: 'macros'

IIUC the problem is for magics defined in `semMagic` (with proc definitions outside system.nim); the magics defined in vmgen.nim don't have this problem.

**Comment by khchen** [comment]
This code also gets an incorrect "imported and not used" message:
```nim
import threadpool
proc thread() {.thread.} =   echo "thread"
spawn thread()
```

**Comment by disruptek** [comment]
How about this one?

```nim
import net

echo AF_UNIX
```
