### ISSUE TITLE
0.20.2 makes it impossible to print raw LF to stdout on Windows

### ISSUE THREAD

**Issue by akavel** [nim-lang/Nim#11801]
With the change 59fbd261a669e3f1bcd6e16a25371b720d5bd702 (adding the `-d:nimBinaryStdFiles` flag), it seems that **it is now impossible to emit a raw LF (0x10) on Windows stdout**. Previously, `echo "foobar"` seemed to result in `"foobar\n"` being printed on stdout (this still happens with `-d:nimBinaryStdFiles`), whereas now, it seems to result in `"foobar\r\n"`. This has an unfortunate consequence in that it seems to break e.g. `nimlsp`, which has lines like this: https://github.com/PMunch/nimlsp/blob/79e57f9456a420878b75a51774da504b9bb5683d/src/nimlsppkg/baseprotocol.nim#L18 which seem to effectively emit "\r\r\n\r\r\n" instead of the intended "\r\n\r\n" now on Windows.

**The main question behind this issue is: is it an intended consequence of the 59fbd261a669e3f1bcd6e16a25371b720d5bd702 commit? If yes, does it mean that code such as in nimlsp should now be modified to print "\r\n" on Linux, but "\n" on Windows, when compiled with Nim 0.20.2+?** (And then have it auto-converted to "\r\n".) **Or, is it intended for nimlsp to do something else with regards to stdout?** Currently the answer to this question is not clear to me, given that the change was introduced as part of a minor release of Nim, with no explicit guidance with regards to CR-LF vs. LF in the release notes.

### Example
```
C:\prog\dali>nim -v
Nim Compiler Version 0.20.2 [Windows: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release

C:\prog\dali>type tmpeol.nim
stdout.write "foo\n"

C:\prog\dali>nim c -d:nimBinaryStdFiles tmpeol.nim
Hint: used config file 'C:\dnload\nim-etc\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: tmpeol [Processing]
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: tmpeol.nim
Hint:  [Link]
Hint: operation successful (14190 lines compiled; 5.689 sec total; 15.98MiB peakmem; Debug Build) [SuccessX]

C:\prog\dali>tmpeol > tmp1.out

C:\prog\dali>nim c tmpeol.nim
Hint: used config file 'C:\dnload\nim-etc\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: tmpeol [Processing]
CC: stdlib_io.nim
CC: tmpeol.nim
Hint:  [Link]
Hint: operation successful (14190 lines compiled; 0.661 sec total; 15.965MiB peakmem; Debug Build) [SuccessX]

C:\prog\dali>tmpeol > tmp2.out

C:\prog\dali>dir *.out
 Volume in drive C is Windows
 Volume Serial Number is BC96-4BCD

 Directory of C:\prog\dali

23.07.2019  13:31                 4 tmp1.out
23.07.2019  13:31                 5 tmp2.out
               2 File(s)              9 bytes
               0 Dir(s)  15 194 406 912 bytes free
```

Length of tmp1.out is **4 bytes**, corresponding to: `foo` + LF.

Length of tmp2.out is **5 bytes**, corresponding to: `foo` + CR + LF.

### Additional Information

```
C:\prog\dali>nim -v
Nim Compiler Version 0.20.2 [Windows: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```

**Comment by Araq** [comment]
We need to revert this change then.

**Comment by krux02** [comment]
What is with "\r\l\r\l" to enforce windows line endings?
