### ISSUE TITLE
`to` from `json` should handle cstring fields

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#11803]
This code should compile:
```nim
import json

discard """{"foo": "bar"}""".parseJson.to tuple[foo: cstring] 
```
Currently it raises 

> \.choosenim\toolchains\nim-0.20.0\lib\pure\json.nim(1253, 18) `false` Unable to process nnkSym cstring

**Comment by krux02** [comment]
> This code should compile

Why?

**Comment by dawkot** [comment]
> Why?

Because it's convenient and the intent is very clear.

**Comment by krux02** [comment]
Who is allocating the cstring? Who should be the owner of that memory? When will it be freed?

**Comment by alehander42** [comment]
btw you can use the native javascript parse and just cast to your type in the javascript backend: i think it's a better idea

**Comment by Araq** [comment]
@krux02 is right, I see no chance of making this work either.
