### ISSUE TITLE
Bind no longer working in generic procs.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#11800]
Imagine you have two files foreignFile.nim and myFile.nim.

foreignFile.nim
```nim
template p[T:int|float](a : T) = 
  echo "Number:" & $a

template p(a : string) =
  echo "String:" & a

proc printVar*[T:int|float|string](a : T) = 
  p(a)
```
All the templates printVar should call are already defined but p isn't bound so it can potentially use new templates/procs/etc defined in the future.

myFile.nim
```nim
import foreignFile

var x = 0

template p(a : int) = 
  x += a
  echo x

p(7)

printVar(5)
printVar(5.0)
printVar("5.0")
```
In this example you've inadvertently overwritten p from myFile when aProc is passed an int.
It will echo 12 instead of Number:5.
You only wanted to call your new p definition directly.
In this case the generic printVar proc should probably be three seperate printVar definitions instead of 
```nim 
proc printVar*[T:int|float|string](a : T)
```

but you never know what your going to get when importing other peoples code.

**Comment by Araq** [comment]
Works as by the spec, ``p`` is overloaded and so is an "open sym choice". This is also not a regression afaict, or if it is, the compiler used to be wrong and now it's correct.
