### ISSUE TITLE
Incorrect sizeof() under --cpu:i386 mode (Regression).

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#11817]
### Example
```nim
type
  T = object
    a: int32
    b: int32
    c: int32
    d: int64
    e: int32

# echo sizeof(T) # Nim 0.19: 32 (correct)  Nim 0.20: 24 (wrong)

var t = T(e: 123)
zeroMem(t.addr, sizeof(T))
echo t.e

```
Nim Compiler Version 0.20.2 (include last devel)
```nim c --cpu:i386```

### Current Output
```
123
```

### Expected Output
```
0
```

**Comment by khchen** [comment]
This object has the similar problem, I think it is the same bug.
```
type
  T = object
    a: int32
    b: int64
    c: int64
```

**Comment by krux02** [comment]
I just tested your program on my 32 bit VM. Everything works as expected (output 0). What is your build environment?

**Comment by khchen** [comment]
Nim Compiler Version 0.20.2 [Windows: amd64]
Building environment: Windows 10 
I use following nim.cfg. 
```
@if windows:
  @if i386:
    gcc.path = r"$nim\dist\mingw32\bin"
    tcc.path = r"$nim\dist\tcc32"
  @else:
    gcc.path = r"$nim\dist\mingw64\bin"
    tcc.path = r"$nim\dist\tcc64"
  @end
@end
```
