### ISSUE TITLE
Bind no longer working in generic procs.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#11811]
I think you closed my issue prematurely araq.

Your example doesn't work on my compiler.

```nim
 proc p(a : int) =
  echo a

proc printVar*[T:int|float|string](a : T) =
  bind p
  p(a)

printVar(5)
```
gives Error: invalid expression: bind p

Oddly enough if you don't call the printVar at all it doesn't give you an error.

Nim Compiler Version 0.20.2 [Windows: amd64] Compiled at 2019-07-17 Copyright (c) 2006-2019 by Andreas Rumpf

compiled with nim c test.nim

I've actually had this problem for a few versions but I assumed you already knew about it before.

**Comment by solo989** [comment]
Nim Compiler Version 0.17.0 (2017-05-18) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

also gives Error: invalid expression: bind p

**Comment by solo989** [comment]
I should have been more explicit before. I was always referring to the bind command not working in generic procs. It works in templates for me but not for procs.

**Comment by mratsim** [comment]
Original issue #11800
