### ISSUE TITLE
Do notation inside proc crashes compiler

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#11812]
### Example
```nim
proc run(a: proc()) = a()

proc main() =
  var test: int
  run do:
    test = 0

main()
```

### Current Output
```
Hint: used config file '/<redacted>/Nim/config/nim.cfg' [Conf]
Hint: used config file '/<redacted>/Nim/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: test [Processing]
nim.nim(106)             nim
nim.nim(83)              handleCmdLine
cmdlinehelper.nim(92)    loadConfigsAndRunMainCommand
main.nim(200)            mainCommand
main.nim(96)             commandCompileToC
modules.nim(147)         compileProject
modules.nim(88)          compileModule
passes.nim(196)          processModule
passes.nim(86)           processTopLevelStmt
cgen.nim(1883)           myProcess
ccgstmts.nim(1284)       genStmts
ccgexprs.nim(2585)       expr
ccgcalls.nim(557)        genCall
ccgcalls.nim(195)        genPrefixCall
cgen.nim(599)            initLocExpr
ccgexprs.nim(2524)       expr
cgen.nim(1182)           genProc
cgen.nim(1147)           genProcNoForward
cgen.nim(980)            genProcAux
transf.nim(1130)         transformBody
lambdalifting.nim(846)   liftLambdas
lambdalifting.nim(489)   detectCapturedVars
lambdalifting.nim(489)   detectCapturedVars
lambdalifting.nim(489)   detectCapturedVars
lambdalifting.nim(484)   detectCapturedVars
lambdalifting.nim(411)   detectCapturedVars
lambdalifting.nim(391)   addClosureParam
lambdalifting.nim(183)   getEnvParam
ast.nim(1327)            lastSon
system.nim(4022)         []
fatal.nim(39)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

### Walkarounds
- Add parenthesis: `do():`
- Switch to `proc() =`

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-22
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 67a6effb7bf4d319c8bafd65c75a4da47e007c24
active boot switches:
```

**Comment by krux02** [comment]
I me, it looks like lambda lifting does not properly lift lambdas written in the do syntax. Then the crash happens in [``getEnvParam``](https://github.com/nim-lang/Nim/blob/devel/compiler/lambdalifting.nim#L183)

**Comment by dom96** [comment]
Instead of fixing this, consider removing the do notation. I believe @Araq is supportive.

**Comment by mratsim** [comment]
@dom96, I don't like the do notation but if we remove it we need a way to pass multiple block statements to templates or macros.

I currently rely on it in Arraymancer for parallel loops where for non-trivial loop you need:

- a prologue, that initializes variables and storage
- a steady state, the core body of your loop
- an epilogue, how you merge the result in your parallel threads

For a concrete example, this is how I compute [parallel variance](https://github.com/mratsim/Arraymancer/blob/2e7b193ee0554cbbca510a18be16f5564671803c/src/tensor/aggregate.nim#L90-L104).

```Nim
proc variance*[T: SomeFloat](t: Tensor[T]): T =
  ## Compute the sample variance of all elements
  ## The normalization is by (n-1), also known as Bessel's correction,
  ## which partially correct the bias of estimating a population variance from a sample of this population.
  let mean = t.mean()
  result = t.fold_inline() do:
    # Initialize to the first element
    x = square(y - mean)
  do:
    # Fold in parallel by summing remaning elements
    x += square(y - mean)
  do:
    # Merge parallel folds
    x += y
  result /= (t.size-1).T
```

As I don't really like the do notation, I'm currently phasing it out with a macro, for example on [parallel sum](https://github.com/numforge/laser/blob/fb1be488e14e8e5b310baf3d7cd750833fcc65ba/examples/ex05_tensor_parallel_reduction.nim#L15-L59).
```Nim
proc reduction_localsum_system_atomic[T](x, y: Tensor[T]): T =
  forEachStaged xi in x, yi in y:
    openmp_config:
      use_simd: false
      nowait: true
    iteration_kind:
      contiguous
    before_loop:
      var local_sum = 0.T
    in_loop:
      local_sum += xi + yi
    after_loop:
      result.atomicInc local_sum # This requires --threads:on
```
but at this point I'm writing a domain specific-language for for-loops.

**Comment by dom96** [comment]
> @dom96, I don't like the do notation but if we remove it we need a way to pass multiple block statements to templates or macros.

Yes, I agree. I'm happy to keep it for that use case, but for all others it should simply be removed. For the code in this issue in particular we shouldn't be using the do notation.
