### ISSUE TITLE
UnusedImport warning is displayed for every runnable example

### ISSUE THREAD

**Issue by Jjp137** [nim-lang/Nim#11819]
For every usage of `runnableExamples` within a module, an UnusedImport warning appears
when documentation is generated for that module, and the warnings occur in a file that `nim doc` itself generates.

For large modules with many documented procs and runnable examples, this can result in dozens of false warnings from the user's perspective.

### Example
```nim
## An example module.

proc addOne*(x: int): int =
  ## Adds one to an integer and returns the result.
  runnableExamples:
    doAssert addOne(1) == 2
  result = x + 1
```

Generate the documentation with `nim doc`.

### Current Output
Within the usual compiler output:

```
/home/jjp/.cache/nim/example_d/runnableExamples/example_examples.nim(1, 8) Warning: imported and not used: 'example_examples1' [UnusedImport]
```

### Expected Output

The UnusedImport warning should not appear.

### Possible Solution

Would disabling that warning via a pragma at the top of the generated file (in this case, example_examples.nim) work? Or are there better solutions?

### Additional Information
Version info:
```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8c93c692b95da7b19a88cc0d56a8cdd20e3ae576
active boot switches: -d:release
```

**Comment by Araq** [comment]
> Would disabling that warning via a pragma at the top of the generated file (in this case, example_examples.nim) work? 

Yeah and it's the right way to do it.
