### ISSUE TITLE
{.warning[XXX]: off.} doesn't work

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11826]
You still get a warning, test case:
```nim
{.warning[UnusedImport]: off.}
import tables

proc test*(a: float): float =
  a
```
Please note there is nothing specific to unused import in this test. I just used it as an example.

**Comment by mratsim** [comment]
Does it work with `push`? It seems like the canonical way to disable those (https://github.com/nim-lang/Nim/issues/5050 and https://github.com/nim-lang/Nim/issues/11805).

Otherwise it's probably another case of https://github.com/nim-lang/Nim/issues/4044

**Comment by Clyybber** [comment]
This does not work with `{.push warning[UnusedImport]: off.}`

**Comment by diegomrsantos** [comment]
why this doesn't work?

```nim
{.warning[UnusedImport]: off.}
import tables

proc test*(a: float): float =
  a
{.warning[UnusedImport]: on.}
```
