### ISSUE TITLE
get request with valid url throws "No uri scheme supplied" and exits

### ISSUE THREAD

**Issue by llum1na** [nim-lang/Nim#11827]
Tried to get the content of Spotify's web page but it ultimately fails every time with an unhandled exception. I debugged my code real hard and the issue seems to be located within `httpclient.nim`, although I passed a valid URL every time.

### Example
```nim
let client = newHttpClient()
let response1 = client.getContent("https://spotify.com") # Passes
let response2 = client.getContent("https://spotify.com/us") # Passes
let response3 = client.getContent("https://spotify.com/us/account") # Exception
let response4 = client.getContent("https://spotify.com/us/account/overview") # Exception
```
_(Don't even get me started on trying and trying without the slash at the end of the URL. I did try it and got the same results.)_

At the same time, a longer GitHub link (the link to this issue) works just fine.
```nim
let client = newHttpClient()
let response = client.getContent("https://github.com/nim-lang/Nim/issues/11827")
```
### Current Output
```
D:\projects\!NONDISCLOSURE\******\******\src\blitzchecker.nim(58) blitzchecker
C:\Program Files (x86)\Nim\lib\pure\httpclient.nim(1080) getContent
C:\Program Files (x86)\Nim\lib\pure\httpclient.nim(1075) get
C:\Program Files (x86)\Nim\lib\pure\httpclient.nim(1051) request
C:\Program Files (x86)\Nim\lib\pure\httpclient.nim(1034) request
C:\Program Files (x86)\Nim\lib\pure\httpclient.nim(987) requestAux
Error: unhandled exception: No uri scheme supplied. [ValueError]
```

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.2 [Windows: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```

**Comment by dom96** [comment]
Did you figure out the problem?

**Comment by Bennyelg** [comment]
I am experiancing the same issue. @ghost ?

**Comment by some-avail** [comment]
No uri scheme supplied. [ValueError]

I had it also; you dont see the echo when the string is empty but only an empty line...make sure the url is not empty  :-)

So indeed no bug here..
