### ISSUE TITLE
Nim code or project parser without completely compile

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#11825]
### Summary

C/C++ compliers doesn't give any information about existing code so that making c/c++ ide is very hard.
Let the compiler provide information about the existing code or project.

### Description

Is there any servise or package like to parse all the nim projects? If there is making ide for nim will be easy.
Information could be code structur or AST in different kind of file formats or a string stream. I don't know. it could be anything. Just give extra information.

**Comment by SolitudeSF** [comment]
nimsuggest already exists and is bundled with nim. there is also nimlsp.

**Comment by mratsim** [comment]
If @SolitudeSF is not enough you should ask in the forum. As this is neither a bug or a feature request I'm closing the question.

You can also checkout how [Aporia](https://github.com/nim-lang/Aporia) was built though it was Nim specific. Beyond nimsuggest (the current robust way), and [nimlsp](https://github.com/PMunch/nimlsp) (the most convenient way), another way you could go forward is by adding Nim support to tree-sitter.
