### ISSUE TITLE
string field incorrectly moved with assignment to result

### ISSUE THREAD

**Issue by dumjyl** [nim-lang/Nim#11842]
My understanding of the destructor spec isn't great, but strings usually have value semantics?

### Example
```nim
# build with --newruntime
type
  ScopedFile* = object
    filename*: string

proc `=destroy`*(f: var ScopedFile) =
  doAssert(f.filename == "test")

proc t: string =
  var file = ScopedFile(filename: "test")
  result = file.filename # steals the string
  # echo file.filename # works with this because it prevents the move?

echo t()
```

### Current Output
```
... `f.filename == "test"`  [AssertionError]
```

### Expected Output
```
test
```

**Comment by mratsim** [comment]
I think it works as designed.
in `result = file.filename` it's the last read of file.filename so it's implicitly moved to result.

If you add the echo, it's not the last read anymore so it's deep-copied. Nim strings indeed have value-semantics.

**Comment by mratsim** [comment]
Actually rereading the wiki https://github.com/nim-lang/Nim/wiki/Destructors,-2nd-edition#sink-parameters, a sink being re-used should be a compile-time error.

So in your snippet in the case of 

```Nim
proc t: string =
  var file = ScopedFile(filename: "test")
  result = file.filename
  echo file.filename
```

I expect `Error: variable used after sink` or something like this.

**Comment by dumjyl** [comment]
Is `result` implicitly a sink param?
I realize i'm only seeing this behavior under newruntime. Without, filename is copied to result and `=destroy` can still delete filename, the behavior I expected.
Newruntime strings seem broken. So this could just be a symptom of that.
```nim
var x = "A"
doAssert(x.len == 1)
x[0] = 'B' # segfault
```

**Comment by Clyybber** [comment]
This works as designed. You are allowed to pass a variable to a sink parameter even if you use that variable afterwards. The spec refers to the location, meaning that the compiler will create a copy.of the variable that is gonna be passed to the sink param. Also note that the 2nd version of the destructor spec is not yet merged into devel; https://github.com/nim-lang/Nim/pull/11248
