### ISSUE TITLE
--threads:on and --newruntime: "quit" proc has non-void return value

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11844]
The "quit" proc has a non-void return value when compiling with "--threads:on and --newruntime"

This causes the compiler to crash on "Hello World" when compiling the `nimRawDispose` proc

### Example
```nim
echo "Hello World!"
```

### Current Output
```
/home/beta/.choosenim/toolchains/nim-#devel/lib/core/runtime_v2.nim(91, 7) Error: expression '
rawWrite(cstderr, "[FATAL] unpaired dealloc\n")
quit 1' is of type 'int' and has to be discarded; start of expression here: /home/beta/.choosenim/toolchains/nim-#devel/lib/core/runtime_v2.nim(74, 5)
```

### Expected Output

```
Hello World!
```

### Additional Information
nim with the latest devel commit (bb949a75db490c9bccae975855310ee2de0b4b28)
https://github.com/nim-lang/Nim/blob/bb949a75db490c9bccae975855310ee2de0b4b28/lib/core/runtime_v2.nim#L72-L92

**Comment by GordonBGood** [comment]
This issue should be reopened as the problem it describes is still there.

**Comment by Araq** [comment]
Strange, for me it compiled. Maybe OS specific?

**Comment by GordonBGood** [comment]
That's the problem, it compiles but crashes on run as the `hasThreadSupport` isn't distributed across all files that need it such as this one when the `newruntime` compiler switch is activated.

**Comment by alaviss** [comment]
As of

```
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-08-12
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: da64c8762fd4af44866879061c10f707b0dcd310
active boot switches: -d:release -d:useLinenoise
```

This compiles on Linux.
