### ISSUE TITLE
regression: CI failing (texplain.nim)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#11854]
CI is failing (texplain.nim), making all recently rebased PR's fail since ~ july 26

see https://travis-ci.org/nim-lang/Nim/jobs/565206359 for nim's own CI:
```
FAIL: tests/concepts/texplain.nim C
Test "tests/concepts/texplain.nim" in category "concepts"
Failure: reMsgsDiffer
```

### Additional Information
https://github.com/nim-lang/Nim/commit/ceb1a1b6884b28f3f3f88a4be5663d7f0b1f1155 shows as the 1st red commit; not sure if that commit is the culprit though.

**Comment by mratsim** [comment]
Pure doc PR are also broken:

- https://github.com/nim-lang/Nim/pull/11831
- https://github.com/nim-lang/Nim/pull/11742
