### ISSUE TITLE
Comments allow compilation of invalid syntax with dangling `=`

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11850]
By adding a comment, we can bypass Nim indentation check and compile an invalid syntax.

Test case:

```Nim
proc foo(): int =
  ## This compiles even though we have a dangling `=`

proc bar(x: int): int =
  0

echo foo()
```

**Comment by krux02** [comment]
Not sure if I would count this as a bug. A procedure declaration with an empty statement list as body is not illegal in Nim. It is just that the there needs to be something in the body for the Nim parser.

**Comment by Araq** [comment]
Doc comments are part of the AST, so IMO the parser is correct, ``##`` is a valid Nim statement.

**Comment by mratsim** [comment]
So should I close this or do we want to prevent a body with just a comment and no explicit discard?

I suppose we could have such things compile as well:

```Nim
if true:
  ## No need 
else:
  ## for discard
```

**Comment by disruptek** [comment]
I'm finding it pretty useful to substitute comments for statements in AST construction.  Is there a good argument in favor of preventing it?  What does this do to other assumptions we make elsewhere about statements in the AST?

**Comment by krux02** [comment]
I don't see any good argument to prevent this syntax. If allowing this syntax causes problems somewhere, please report it. Until then I see this as a non-issue.
