### ISSUE TITLE
getImpl doesn't preserve export marker

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#11878]
# Example
```nim
import macros

proc test* = discard

macro check(p: typed) =
  echo p.getImpl[0].treeRepr

check test
```

### Current Output
```
Sym "test"
```

### Expected Output
```
Postfix
  Ident "*"
  Ident "test"
```

**Comment by mratsim** [comment]
With a `typed` macro input you get a symbol not an ident. A symbol has passed through semantic checking and symbol resolution and has visibibility rules attached to it.

Unfortunately there is currently no way currently to check if a symbol is exported or not so tagging as feature.

It might be a bug if getImpl was supposed to return the complete symbol definition but at this point changing the current getImpl will introduce too much breakage.

Either we introduce a `getDefinition` that gets the full definition or a magic `isExported`.

**Comment by krux02** [comment]
yes a +1 from me for the ``isExported`` proc in macros.
