### ISSUE TITLE
Side effects in function with noSideEffect pragma

### ISSUE THREAD

**Issue by Grinshpon** [nim-lang/Nim#11884]
Functions with the `noSideEffect` pragma (or `func`s) can take and mutate `vars`.

#### Example
```nim
proc mutate(x: var int) {.noSideEffect.} =
  x = 5

var x = 0
mutate x
echo x
```

#### Current Output
```
5
```

#### Expected Output
The expected output should give an error:
```
Error: 'mutate' can have side effects
```

This is on Nim Compiler Version 0.20.2

<br>

In the case that this behavior was left intentionally I will alter the issue and request that the behavior be changed.

**Comment by Araq** [comment]
Works as documented, https://nim-lang.org/docs/manual.html#pragmas-nosideeffect-pragma

**Comment by Grinshpon** [comment]
I feel like `noSideEffect` is not too well named then, because it does allow side effects. Is there a reason for this @Araq ? And may I make a feature request changing this behavior in a new issue?

**Comment by andreaferretti** [comment]
Well, you are explicitly passing a mutable location as an argument. You would not be able to mutate the global variable x otherwise

**Comment by Grinshpon** [comment]
I understand. I feel like you shouldn't be allowed to pass mutable arguments in the first place with this pragma on. Of course what I'm proposing would be a little hard to do because I don't know if refs or ptrs can be passed immutably.

**Comment by jamieghassibi** [comment]
Although this behavior is documented, elsewhere Nim describes functions as being side-effect-free using the definition on Wikipedia. From the [Nim github](https://github.com/nim-lang/Nim/wiki/Nim-for-Python-Programmers#def-vs-procfunc):

> Uses func for Functional Programming [side-effect free](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) functions like from "mathematical functions".

Thus, one would expect func to not to use mutable arguments or otherwise pass the arguments immutable, as if they were assigned to new name that is a const.

**Comment by Araq** [comment]
@JamieGhassibi I fixed the wiki page.

**Comment by Grinshpon** [comment]
@Araq I still feel that "noSideEffect" is misleading since mutating a passed variable is by definition a side effect.

**Comment by SolitudeSF** [comment]
@Grinshpon no, its not. all inputs are known, all outputs are known. there are no side effects since result of the function relies only on provided parameters. even if the parameters gets changed.

**Comment by jamieghassibi** [comment]
@SolitudeSF @Araq It may be worth adding a line about how side-effects in Nim are different than one might expect, for example this func with no return value.

```nim
func(x: var int) = inc x
var a = 0; func(a); echo a
```

It's also unexpected that if I don't pass a variable to a proc, I can modify it, but if I do pass a variable to a proc, I cannot modify it unless I use the var keyword. It's like globals are implicitly passed by reference and parameters are passed by value yet are immutable.

```nim
var b, c: int
proc h(c: int) = inc b; inc c
h(c); echo b; echo c
```

**Comment by Clyybber** [comment]
That is not unexpected. Thats how globals work. In the mathematical sense you can think of a global as being a parameter to every function that exists.
For functions with var parameters think of them as functions that return tuples which include the new value of the corresponding var parameter. You can think the same way about mutable globals.
Thus using the mathematical definition of functions is perfectly acceptable, even for `func`s with var parameters.

**Comment by jamieghassibi** [comment]
@Clyybber Ah, the unexpectedness must be due coming from Python where globals are read-only unless explicitly marked as modifiable in the function body

```python
x = 0
def f():
    global x
    x += 1
f()
print(x)
```

**Comment by Grinshpon** [comment]
@Clyybber I'm not sure I agree with that. I mean, you could generalize that all functions/methods/procedures in all languages are taking in global variables as parameters implicitly and returning a large tuple. One can consider it to be like that but the fact remains I can use a `func` to mutate a variable passed to it instead of returning a value and that goes against its intended purpose.

**Comment by jamieghassibi** [comment]
@Grinshpon Playing Devil's advocate, var parameters allow functions to mutate values in place, restricted of course to the values seen in the type declaration. I feel this allows functions to reduce side-effects without having to create new values, which can be expensive. I can see the allure.

**Comment by Araq** [comment]
Well Nim assumes that when you write ``func f(a: var T)`` you know what it means.

**Comment by obadz** [comment]
The `ref` can be hidden deep into one of the arguments and not actually show up in the function prototype, for instance:

```nim
type RZ = ref object
  z: int

type O = object
  i: int
  m: RZ

let x: O = O(i: 3, m: RZ(z: 0))

func blah(x: O): int =
  inc x.m.z # Mutates yet no var argument!
  result = x.i
  
echo blah(x)
echo repr(x)
```

I think the fix is:

```nim
{.experimental: "strictFuncs".}
```
