### ISSUE TITLE
raising in finally, intended behavior / crashing compiler

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#11887]
In C++, raising in destructors is generally discouraged because it leads to problems in stack unwinding and will terminate the application instead - in later c++ standards destructors have been changed to disallow throwing by default for this reason.

In nim, the language doesn't disallow raising in finally blocks - what does it mean to do so? what is the desired behaviour? 

This problem will grow more urgent with newruntime, as people start to actually clean up resources instead of letting them leak, as there will be more "hidden" opportunities for raising.

Currently, the behaviour is to crash the compiler with out-of-memory :)

```nim
try:
  try:
    raise newException(Exception, "Hello")
  except:
    echo "except1"
    raise
  finally:
    raise newException(Exception, "In finally")
except:
  echo getCurrentExceptionMsg() 
finally:
  echo "finally2"
```

```
[122692.762935] oom_reaper: reaped process 27023 (nim), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

```
[arnetheduck@tempus tmp]$ nim c --version
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```

**Comment by Araq** [comment]
> In nim, the language doesn't disallow raising in finally blocks - what does it mean to do so? what is the desired behaviour?

We usually look at what Python and C# do and copy their behaviour, at least that's what we did before.

**Comment by Araq** [comment]
This now produces the following output:

```
except1
In finally
finally2
``` 

which seems to be corect.

**Comment by arnetheduck** [comment]
> which seems to be corect.

It's correct only if you consider the hidden loss of the `"Hello"` exception acceptable - which it is not, _really_.

**Comment by Araq** [comment]
Debatable, consider:

```nim

try:
  try:
    raise newException(Exception, "Hello")
  except:
    echo "except1"
    raise
  finally:
    let e = getCurrentException()
    raise newException(Exception, "In finally", e)
except:
  let e = getCurrentException()
  echo e.parent.msg
  echo getCurrentExceptionMsg()
finally:
  echo "finally2"
```

`newException` does not set the parentException by default:

```
template newException*(exceptn: typedesc, message: string;
                       parentException: ref Exception = nil)
```

Maybe it should do that instead:

```
template newException*(exceptn: typedesc, message: string;
                       parentException: ref Exception = getCurrentException())
```

**Comment by arnetheduck** [comment]
> Maybe it should do that instead:

Hm, that's probably not a bad idea in general - ie it seems like a sensible default even when raising exceptions from within `catch`, sensible enough to outweigh the downsides (longer ref chains etc) - and it allows detecting the difference between finally-after-try and finally-after-catch in a reasonable way..

**Comment by arnetheduck** [comment]
btw, this is still a compiler-crashing bug in 1.6, cc @narimiran it would be nice to get a fix backported

**Comment by Araq** [comment]
Well I think it's fixed because we made `--exceptions:goto` the default, there is nothing to backport. ARC/ORC sometimes is more stable than the older GCs. ;-)

**Comment by arnetheduck** [comment]
from `nlvm`:s point of view (which is based on 1.6 and uses native dwarf / zerocost EH), the bug is an infinite recursion in the AST - ie it looks more like a transformation issue than `goto` or not.
