### ISSUE TITLE
Allow object fields to be visible in the C header

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1189]
Bitten again by the oversight of http://forum.nimrod-lang.org/t/96 which prevents me from initializing a Nimrod structure on the stack of a C calling function. Here is a small test case to compile with ``nimrod c --app:lib --header file.nim``:
```nimrod
type
  Nice_scale {.exportc.} = object
    theValue {.exportc.}: float

proc use(x: var Nice_scale) {.exportc.} =
  X.theValue = 5
```
Compilation will generate a ``file.h`` with only the struct typedef.

Maybe the ``{.exportc.}`` pragmas for the fields should trigger an error or a warning about not being useful at all, since C doesn't have a concept of visibility.

**Comment by Araq** [comment]
The ``--header`` switch will be removed.
