### ISSUE TITLE
hasCustomPragma fails on nnkVarTy/nnkBracketExpr nodes

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#11923]
So I've looked into the problem I was trying to fix in #11879 a little more closely and found another case where even my PR doesn't fix the problem. I think the root cause is that ``getImpl`` does not work when a ``nnkVarTy`` or a ``nnkBracketExpr`` are passed to it, this is something that `customPragmaNode` tries to work around.

### Example

```nim
import macros

type
  MyObj[T] = object
    test: Point[T]

  Point[T] = object
    x, y: T

template testPragma {.pragma.}

proc case1(x: var MyObj) =
  for k, v in fieldPairs(x):
    when v.hasCustomPragma(testPragma):
      echo("hi")

proc case2(x: MyObj) =
  for k, v in fieldPairs(x):
    when v.hasCustomPragma(testPragma):
      echo("hi")

var x = MyObj[float](test: Point[float](x: 1.3, y: 0.0))
case2(x)
case1(x)
```

### Current Output
```
stack trace: (most recent call last)
/Users/dom/projects/nim/lib/core/macros.nim(1538, 36) hasCustomPragma
/Users/dom/projects/nim/lib/core/macros.nim(1478, 25) customPragmaNode
/private/tmp/aporia/a1.nim(23, 6) template/generic instantiation of `case2` from here
/private/tmp/aporia/a1.nim(19, 11) template/generic instantiation of `hasCustomPragma` from here
/Users/dom/projects/nim/lib/core/macros.nim(1478, 25) Error: node is not a symbol
```

### Expected Output

No error. ``hasCustomPragma`` returns false.

### Possible Solution

A variant of #11879 or changing ``getImpl`` to support ``nnkVarTy``/``nnkBracketExpr``

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-08-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8407a574992ebd6bccec647a902cf54a4de8db18
active boot switches: -d:release
```

**Comment by Clonkk** [comment]
Just ran into the same issue.

I'm kinda confused as to why this hasn't been fixed already when there is a 2 year old commit that seem to do the trick : https://github.com/nim-lang/Nim/commit/5da931fe811717a45f2dd272ea6281979c3e8f0b
