### ISSUE TITLE
"lastReadOf" is not computed correctly for global variables...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#11936]
The destructors document says at the bottom of the following section:  https://github.com/nim-lang/Nim/blob/devel/doc/destructors.rst#rewrite-rules that passing a "lastReadOf" to a `sink` parameter of a `proc` should cause a move (and subsequent setting to zero by `wasmoved`), but instead it does an assignment `=` copy.

### Example - runnable link:  https://wandbox.org/permlink/HCKJpwfgGVHuH8L4
```nim
# "last use of" parameter passed to a "sink proc" should automatically
# `=sink`/move the parameter (and thus reset the last value) but doesn't...

type
  TstObj = object
    val: int
# hooks so we can see what is happening...
proc `=destroy`(x: var TstObj) =
  echo "destroying TstObj"; x.val = 0
proc `=`(dst: var TstObj; src: TstObj) =
  echo "copying TstObj"
  dst.val = src.val
proc `=sink`(dst: var TstObj; src: TstObj) =
  echo "moving TstObj"
  dst.val = src.val # the system should subsequently reset src automatically!
# ]#

let tstv = TstObj(val: 42)
# be able to examine the contents without actually using "last use of"
let tstvp = cast[ptr int](tstv.val.unsafeAddr); tstvp[].echo

proc tstsnk(x: sink TstObj) = echo "in tstsnk:  ", x

echo "just before calling tstsnk"

tstsnk(tstv) # last use of tstv

echo "expect zero here:  ", tstvp[] # should have done a move not a copy, with value zeroed but not

# the call of the "hooks" shows that the value was copied instead of moved!
echo "\ntesting with a primitive integer"

# The automatically generated `=sink` for a primitive such as an `int` should
# also cause a `=sink`/move and zeroing of the "last use of" but also doesn't...

let tstint = 49; let tstintp = cast[ptr int](tstint.unsafeAddr); tstintp[].echo

proc tstsnkint(x: sink int) = echo "in tstsnkint:  ", x

echo "just before calling tstsnkint"

tstsnkint(tstint) # the last use of tstint

echo "expect zero here:  ", tstintp[] # this should show up as zero'ed, but doesn't!

# last use of values should should up as zero'ed, showing a move was done, not a copy!
```
Outputs:
```
moving TstObj
42
just before calling tstsnk
copying TstObj
in tstsnk:  (val: 42)
expect zero here:  42

testing with a primitive integer
49
just before calling tstsnkint
in tstsnkint:  49
expect zero here:  49
destroying TstObj
```

### Expected Output
```
moving TstObj
42
just before calling tstsnk
in tstsnk:  (val: 42)
expect zero here:  0

testing with a primitive integer
49
just before calling tstsnkint
in tstsnkint:  49
expect zero here:  0
destroying TstObj
```
Note:  we expect the values to be zero'ed due to the move!

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.XXX # for any recent version on Linux or Windows!
```

**Comment by alaviss** [comment]
`reset` is mapped to `destroy()` in newruntime. Please zero out the memory manually.

**Comment by alaviss** [comment]
Looks like a move wasn't generated

```
just before calling tstsnk
copying TstObj
```

You'd want

```
just before calling tstsnk
moving TstObj
```

**Comment by GordonBGood** [comment]
@alaviss, thanks for the heads-up on the change for the newruntime; I'll change my code accordingly to avoid the (future, when using newruntime) race.  Does `wasmoved` also call `=destroy` currently or in the newruntime?

Meanwhile, this issue isn't about using the newruntime or `=destroy` but about the compiler generating `=` instead of `=sink` for a "lastUseOf" sink parameter, so still stands.

**Comment by alaviss** [comment]
> Meanwhile, this issue isn't about using the newruntime or `=destroy` but about the compiler generating `=` instead of `=sink` for a "lastUseOf" sink parameter, so still stands.

Yea, looks like the `lastUseOf` detection is a bit... off (pun intended)

Example code:
```nim
type O = object
  v: int

proc `=destroy`(o: var O) =
  echo "Destroying O"
  o.v = 0

proc `=`(d: var O, s: O) {.error.}

proc `=sink`(d: var O, s: O) =
  echo "Moving ", s
  d.v = s.v

proc sinkTest(o: sink O) = discard

let a = O(v: 10)

a.sinkTest()
```

Error message:
```
test.nim(18, 1) Error: '=' is not available for type <O>; requires a copy because it's not the last read of 'a'; routine: test
```

Nim version:
```
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-08-13
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 433613e2675064583ee5055d47aa89a43184e7f2
active boot switches: -d:release -d:useLinenoise
```

**Comment by alaviss** [comment]
However, if you put everything in a `main()` proc, this will work. I suspect that there might be restrictions regarding global scope variables that prevents the compiler from doing the optimization.

**Comment by GordonBGood** [comment]
@alaviss, Yes, it works as expected when put into a "main" `proc`, but then it doesn't call the custom "hook" for `=sink` so we don't get the "moving TstObj" message!  Is this a separate issue?

**Comment by alaviss** [comment]
According to the rewrite rule:

```
f_sink(lastReadOf y)
-----------------------     (move-to-sink)
f_sink(y)
wasMoved(y)
```

``` `=sink`() ``` is not generated in this case.

**Comment by GordonBGood** [comment]
@alaviss, so the remaining question is whether there is any issue at all if the problem is only when run at global scope?  Should this issue be closed, or should use in global scope be investigated and at least documented?

**Comment by alaviss** [comment]
I would not rule this out as a bug since the spec doesn't say anything about it. I'd say we wait for @Araq's assessment.

**Comment by alaviss** [comment]
The title should be: "lastReadOf is not computed correctly for global variables" IMO.

**Comment by GordonBGood** [comment]
@alaviss:

> I'd say we wait for @Araq's assessment.

Okay, that's what we'll do.  Thanks for your suggested refinements and corrections; I've edited the OP on the issue accordingly.

**Comment by Araq** [comment]
I don't see how the compiler could ever detect the "last read of" a global reliably. Will update the spec.

**Comment by GordonBGood** [comment]
@Araq: Sounds good enough to me.

**Comment by Araq** [comment]
It was documented:

> The employed static analysis is limited and only concerned with local variables;
however object and tuple fields are treated as separate entities:
