### ISSUE TITLE
Porting tables to new runtime some discussion

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#11933]
The next step to porting my project to the new runtime is making tables module new runtime friendly.

I have tried porting `tables.nim` to the newruntime and it opened multiple questions that I would like to discuss here.

 

Let's concentrate on the single example for now:

```nim
  import tables
  let x = {"a": new(int)}.toTable
```

Value in table is non-copyable and has to be moved into the table.
`toTable` is currently declared as as:

```nim
proc toTable*[A, B](pairs: openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  for key, val in items(pairs):
    result[key] = val
```

 

In presence of non copyable types, we need make sure we move whenever it is possible.

it is no longer a question of optimization only: sink is cheaper than copy.

Copy is not available at all, hence you have to sink. Period.

 

Question 1

----------

Do we need to support sink for openarray like this?

```nim

proc toTable*[A, B](pairs: sink openArray[(A, B)]): Table[A, B]

```

I would say yes and it would mean destroy all elements of openarray but not the openarray it self.

Openarray doesn't own array's memory hence you can't destroy openarray, but you can destroy each element of the openarray.

 

Question 2

----------

Suppose the ``toTable`` is now defined as:

```nim
proc toTable*[A, B](pairs: sink openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  for key, val in items(pairs):
    result[key] = val
```

The compilation now fails with the error that `items` iterator  for `pairs` variable tries to copy the non-copyable.

Iterator is defined as:

```nim
iterator items*[T](a: openArray[T]): T {.inline.} =
  var i = 0
  while i < len(a):
    yield a[i]
    inc(i)
```

Does it mean that the iterator declaration needs to be changed like that?

```nim
iterator items*[T](a: openArray[T]): lent T {.inline.}
```

IMO, this also means that `[]` declaration has to change from

```nim
proc `[]`*[I: Ordinal;T](a: T; i: I): T {.noSideEffect, magic: "ArrGet".}
```

to
```nim
proc `[]`*[I: Ordinal;T](a: T; i: I): lent T {.noSideEffect, magic: "ArrGet".}
```

My answer is yes. This is very important question that will affect very basic ops.
Let me know your thoughts.

Question 3
----------

Suppose we have fixed the iterator too and we have redeclared `[]=` for Table like this:

```nim
proc `[]=`*[A, B](t: var Table[A, B], key: sink A, val: sink B)
```

The `toTable` is now implemented in the following way:

```nim
proc toTable*[A, B](pairs: sink openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  for key, val in items(pairs):
    result[key] = val
```

`toTable` still fails compilation with error: it is not the last read of `val` hence it can't be moved.

IMO, it should be fixable with a simple move trick:

```nim
proc toTable*[A, B](pairs: sink openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  for key, val in items(pairs):
    result[key] = move(val)
```

However, `move` is declared for var type only : `proc move*[T](x: var T): T`. Hence, can't be used.

Should `move` declaration change to `proc move*[T](x: T): T`?

**Comment by Araq** [comment]
Q1: A tough one, since you don't move the openArray itself, the declaration should be `` openArray[sink (A, B)]``, maybe.

Q2: Lent annotations are not required if we instead avoid the copies in ``transf.nim`` and it would be a less disruptive change.

Q3: In ``result[key] = val`` ``val`` must be detected as the last read IMO. Changing the declaration of ``move`` is a recipe for much trouble.

**Comment by Araq** [comment]
Thinking more about this... At this point ``sink T`` is exactly C++'s "pass by value" feature. Since we have the full ownership of a sink parameter within the proc, a sink parameter should be an lvalue. Then you can mutate it freely, including passing it to ``system.move``.

**Comment by Araq** [comment]
In other words, it should be like this:

```nim

proc toTable*[A, B](pairs: sink openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  for key, val in mitems(pairs):
    result[key] = move(val)

```

**Comment by Araq** [comment]
I consider this question to be settled.

**Comment by Clyybber** [comment]
IMO the signature of move should be changed.
Requiring/allowing mitems and similar for sink is not a good idea IMO, since people can then pass sink to procs that take a var, and will be confused why it doesnt mutate the original variable.
