### ISSUE TITLE
Nim support for bare metal

### ISSUE THREAD

**Issue by catastrop** [nim-lang/Nim#11943]
can Nim run on bare metal ?

**Comment by krux02** [comment]
This is not an issue report. Please use the chat or forum for such questions. And no, bare metal is not something where you can run any programming language on. You need at least some silicone and microprocessors to be able to execute code.

**Comment by catastrop** [comment]
@krux02 , i am not making fun. I am asking than is nim has support for free standing binary.

**Comment by mratsim** [comment]
Yes: https://scripter.co/nim-deploying-static-binaries/

**Comment by catastrop** [comment]
@mratsim , this is sad. I have asked for free standing binary you give me a like about static binary.

**Comment by Clyybber** [comment]
@catastrop Nim can work in embedded: https://nim-lang.org/docs/nimc.html#nim-for-embedded-systems .  Also dom96 wrote a kernel in Nim: https://github.com/dom96/nimkernel
