### ISSUE TITLE
hex integer literals should be unsigned by default

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#11946]
First of all, hex iteger literals that work on signed types are rare. So unsigned might be the better default.

Then recently the compiler got stricter when it comes to conversions of integers. These strict rules, while being correct now come with surprining error messages, for example in this generated OpenGL header [here](https://glad.dav1d.de/generated/tmpLQT5Z7glad/glad/gl.nim).

The compiler complains about constructs such as ``uint64(0xFFFFFFFFFFFFFFFF)``, because `-1` is not in the range of unsigned integers. The literal doesn't specify the integer precision, and yet this code sets the sign bit by accident to ``-1``. Then there are also expressions such as ``GLenum(0xFFFFFFFF)``. On 64 bits this is not a problem, but will this work on 32 bits? I don't know. Accidentally setting the sign bit with hex literals should not be a thing to worry about.

**Comment by Araq** [comment]
Meh, if you cannot read the spec and write ``0xFF'u`` that's not the language's problem.

**Comment by krux02** [comment]
It is a problem of the language if the spec requires surprising behavior.

**Comment by krux02** [comment]
another solution that I see would be to enforce the suffix for types

**Comment by Araq** [comment]
There is no programming language without surprising behavior and this whole notion of "principle of least surprise" is what got us into the trouble in the first place.
