### ISSUE TITLE
nim accepts bad code with missing `&`, gives wrong runtime result

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#11956]
### Example
```nim
proc bar*(max: int) =
  echo("foo" & $max " children")
bar(12)
```

### Current Output
```
foor
```

### Expected Output
CT error

### Additional Information
* Your Nim version (output of `nim -v`).
devel c0d240b8cd3dc08d25c671b0dc7614fbfa980c2e

* this actually occurs in stdlib, eg in macros.nim see https://github.com/nim-lang/Nim/pull/11957

```
proc expectLen*(n: NimNode, min, max: int) {.compileTime.} =
  ## checks that `n` has a number of children in the range ``min..max``.
  ## If this is not the case, compilation aborts with an error message.
  ## This is useful for writing macros that check its number of arguments.
  if n.len < min or n.len > max:
    error("macro expects a node with " & $min & ".." & $max " children", n)
```
which gives a bad error msg eg: `macro expects a node with 3..r`

**Comment by Araq** [comment]
```nim

import macros

dumpTree:
  proc bar*(max: int) =
    echo("foo" & $max " children")
  bar(12)
```

--> It's a command ``max " children"`` returns ``r`` which then produces the ``foor`` output. No Bug here. :-)

**Comment by timotheecour** [comment]
yikes
