### ISSUE TITLE
Tut 3 typos

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#11980]
https://nim-lang.github.io/Nim/tut3.html

As this is an official document, you may consider fixing some typos:

sematic

marcos

From the output it is possible to see that the information that the argument is an infix operator

**Comment by krux02** [comment]
Well these typos are my typos. I do them regularly.

**Comment by StefanSalewski** [comment]
Yes, would be ok for a blog post. But for an official Nim document I would recommend fixing them. (There are many more errors in my own texts.)

I forgot one:

that the assert macro.

**Comment by Araq** [comment]
> Well these typos are my typos. 

Maybe install a spell checker for your editor then.
