### ISSUE TITLE
unreachable statement after 'return' statement

### ISSUE THREAD

**Issue by citrusn** [nim-lang/Nim#11984]
### Example

```nim
type EventTarget = string or int

proc attach(p: EventTarget): string =
  when p is string:
    return "string" # error only here 
    # result = "string" # it's ok
  when p is int:
    return "int"

proc detach(p: EventTarget): string =
  when p is string:
    return "string"
  when p is int:
    return "int"

echo attach("1")
echo detach(1)

```

### Current Output
```
testRepr.nim(6, 3) Error: unreachable statement after 'return' statement or '{.noReturn.}' proc
```
### Expected Output

```
string
int
```

**Comment by Araq** [comment]
Yeah that error should simply be removed, it also bites with async.

**Comment by nc-x** [comment]
Can't we fix it instead?

**Comment by Araq** [comment]
For async it's technically correct, but annoying.

**Comment by cooldome** [comment]
The check is required. The assumption of no statement after return It is used both in sempass2 and injectdestructors.

It is not difficult to fix properly

**Comment by timotheecour** [comment]
I like that `unreachable after return` error msg, it helped my catch some bugs. The workaround is trivial for cases like this: `if true: return "string"`

**Comment by Araq** [comment]
> The check is required. The assumption of no statement after return It is used both in sempass2 and injectdestructors.

How so? I mean the analysis is free to assume that in ``return; f()`` the ``f()`` is dead code, it's correct. But there is no reason to report it to the programmer.

**Comment by Clyybber** [comment]
@timotheecour Just the fact that this feature makes you write such workarounds is enough to warrant its removal IMO.

**Comment by Araq** [comment]
In any case, this example should be written as:

```nim
type EventTarget = string or int

proc attach(p: EventTarget): string =
  when p is string:
    return "string" # error only here 
  elif p is int:
    return "int"

proc detach(p: EventTarget): string =
  when p is string:
    return "string"
  elif p is int:
    return "int"

echo attach("1")
echo detach(1)
```

**Comment by ghost** [comment]
Should this be closed? We now have unreachable code as a warning instead.
