### ISSUE TITLE
Add build support for FreeBSD on PowerPC64

### ISSUE THREAD

**Issue by lenoil98** [nim-lang/Nim#11997]
### Summary
Add powerpc64 to the CPUs supported by FreeBSD.

### Description
Provide the ability to build Nim freebsd/powerpc64. 

### Additional Information
I’ve been able to build a working Nim compiler by manually editing the “build.sh” and “makefile” in the csources, by copying and pasting  the Linux/powerpc64 code sections to the FreeBSD/powerpc64 section. This results in a Nim compiler that works on freebsd.

**Comment by awr1** [comment]
What sort of ppc64 system did you test it on?

**Comment by lenoil98** [comment]
Tested on old Apple PowerMac G5 (970MP) big endian.  Hopefully, I should soon have my power9 system up and will be testing on that system.

**Comment by awr1** [comment]
`powerpc64be` and `powerpc64le` should really be made into compiler defines honestly, the compiler only seems to define `powerpc64`

**Comment by lenoil98** [comment]
Actually, powerpc64 is universally understood as "big endian" and powerpc64le as "little endian".  That being said linux has three defines, powerpc (32bit big endian), powerpc64 (64bit big endian) and powerpc64le (64bit little endian).  MacOSX also uses powerpc64 (big endian).  

By way of an update.  I modified the "niminst" templates to add powerpc64 support and used the koch tool that was created to bootstrap the Nim compiler, to recreate the Nim csources, along with new "build.sh" and "makefile".  Which now include code sections for freebsd/powerpc64.  I will soon submit a PR with my recommended code changes.

**Comment by awr1** [comment]
> Actually, powerpc64 is universally understood as "big endian" and powerpc64le as "little endian". That being said linux has three defines, powerpc (32bit big endian), powerpc64 (64bit big endian) and powerpc64le (64bit little endian). MacOSX also uses powerpc64 (big endian).

Even so, I think being more specific might be better. Nim doesn't even have `x86` as a compiler const (maybe it should, but IDK), instead opting for `i386` and `amd64` to reduce confusion about "which mode, 32-bit or 64-bit?"

[IBM themselves seem to use it.](https://www.ibm.com/support/knowledgecenter/en/SSYSP8_5.2.0/com.ibm.ess.v5r2.qdg.doc/bl8qdg_upgradeesscestoolkit_hmcupg.htm)

**Comment by lenoil98** [comment]
PR #12011 submitted to add support for FreeBSD/powerpc64.

**Comment by lenoil98** [comment]
PR #12011 is now merged into master.
