### ISSUE TITLE
Using variable without {.compileTime.} in macro leads to cryptic error

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#11999]
The following code will create an error when compiled because the table is lacking {.compileTime.}:

``` Nim
import tables

var myTable = initCountTable[string]()

macro createError(): untyped =
  myTable.inc("hello world")

createError()
```

The error is:
```
fatal.nim(39)            sysFatal
Error: unhandled exception: vm.nim(706, 16) `nfIsRef in regs[ra].node.flags`  [AssertionError]
```

This error should really be more informative.

**Comment by PMunch** [comment]
Tried to implement a dumb replacement for the `CountTable` and it suffers from the same error:
``` Nim
proc inc(table: var seq[tuple[name: string, count: int]], name: string) =
  for item in table.mitems:
    if item.name == name:
      item.count += 1
      return
  table.add (name, 1)

proc hasKey(table: var seq[tuple[name: string, count: int]], name: string): bool =
  for item in table.mitems:
    if item.name == name:
      return true

proc getOrDefault(table: var seq[tuple[name: string, count: int]], name: string): int =
  for item in table.mitems:
    if item.name == name:
      return item.count
  return 0

proc `[]`(table: var seq[tuple[name: string, count: int]], name: string): int =
  for item in table.mitems:
    if item.name == name:
      return item.count
  raise newException(KeyError, "Key " & name & " not found in count table")
```

**Comment by vitreo12** [comment]
Shouldn't it just be
```nim
var myTable {.compileTime.} = initCountTable[string]()
```
?

**Comment by PMunch** [comment]
Oh wow, yes indeed. Silly mistake on my end, but that error message should really be improved upon then..

**Comment by narimiran** [comment]
> ```Error: unhandled exception: vm.nim(706, 16) `nfIsRef in regs[ra].node.flags`  [AssertionError]```
>
> that error message should really be improved upon then..

Both on the latest devel and on 1.0.x branch I get: `Error: cannot evaluate at compile time: myTable` — @PMunch, can you confirm? If so, can this be closed?

**Comment by PMunch** [comment]
Indeed, this error message seems to have been improved sufficiently!
