### ISSUE TITLE
ambiguous empty table constructor ({:})

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#1199]
The syntactic sugar for an empty table ({:}) results in an "ambiguous call" error, when used like this: %{:}. These are the affected proc signatures:

``` nimrod
proc `%`*(fields: openarray[tuple[k: string, v: TBsonCtor]]): TBsonCtor
proc `%`*(arr: openarray[TBsonCtor]): TBsonCtor
```

and they can be found here: https://github.com/nimrod-code/mongo/blob/master/lib/db_mongo.nim#L181

change false to true here to trigger it: https://github.com/nimrod-code/mongo/blob/master/tests/tmongo.nim#L124

**Comment by andreaferretti** [comment]
Mongo db is not included in the standard library anymore, and the equivalent operation with the `%` operator from `json` works fine. Can I close?
