### ISSUE TITLE
Newruntime:  erroneous unwarned `=sink` copy of `owned` `proc`/closure...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#11993]
Owned `proc`'s/closures are copied when not "last use of", which is correct, but the copy is erroneously made an `owned`, which is incorrect as `owned` can't be copied but only cast.  Currently, copies for other `owned` types are compile time errors for the programmer to do an appropriate cast/conversion.

As the copy is deemed to be `owned` just as the original is with no `disarm`/`wasmoved` preventing double destruction, the double destruction causes a seg fault for closures, as they contain a pointer to the captured bindings on the heap; the error for non-closure `proc`'s does not cause a seg fault although incorrect, as there is no heap data involved.

Possibly related to closed  #11253 about closure environments being destroyed multiple times.

### Example
```nim
# compile with --newruntime
import sugar

let tstclsr = ( () => (let x = 42; () => x) )() # produces an owned closure as it should
let tstclsrp = cast[ptr (int, int)](tstclsr.unsafeAddr) # so we can check if zeroed

tstclsr.typeof.echo # notice that it is an owned closure as expected
tstclsrp[].echo # just to verify that it exists as valid pointers!

let tstclsr1 = tstclsr # automatically does a copy but forgets to prompt for unown casting!
let tstclsr1p = cast[ptr (int, int)](tstclsr1.unsafeAddr) # to check its state later
tstclsrp[].echo # the pointers for the original closure correctly not zeroed as it was a copy
tstclsr1.typeof.echo # should be dangling/unowned but it's not automatically cast or warned!
# tstclsr1().echo # this should just be a dangling we can use or not as we wish
tstclsr().echo # last use of here should preserve the owned to here if used and it does

# but since tstclsr1 was erroneously copied as owned instead of unowned,
# destruction tries to happen for both tstclsr and tstclsr1, causing a segfault!

# a non-closure proc is also copied as an owned, but it doesn't cause the
# segfault because it doesn't have any internal heap pointer for the captured binding(s)!
# ie. substituting the following still copies an owned but won't seg fault...
# let tstclsr = ( () => (() => 42) )() # produces an owned proc as it should, but then incorrectly copied!
```

### Current Output as run on [this Wandbox link](https://wandbox.org/permlink/E8SIL8wPbfX39dfy):
```
owned proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
(4242131, 140044004610128)
Traceback (most recent call last)
/home/jail/prog.nim(7)   prog
/opt/wandbox/nim-head/lib/core/runtime_v2.nim(107) nimDestroyAndDispose
/opt/wandbox/nim-head/lib/core/runtime_v2.nim(84) nimRawDispose
/opt/wandbox/nim-head/lib/system/alloc.nim(945) dealloc
/opt/wandbox/nim-head/lib/system/alloc.nim(860) rawDealloc
/opt/wandbox/nim-head/lib/system/avltree.nim(74) del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
(4242131, 140044004610128)
owned proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
42
1
```

### Expected Output
```
owned proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
(4242131, 140399425347664)
(4242131, 140399425347664)
proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
42
0
```

### Possible Solution or workaround:
As the problem is inconsistent behaviour in not warning the programmer for `proc` types when it does for other types, the workaround is to just add the `unown` template as is the usual solution after being warned as `let tstclsr1 = unown tstclsr`.

An even nicer solution would be for the compiler to automatically inject the `unown` template whereever it would otherwise warn as it should be doing here.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 nightly as of 19-08-2019, both Linux and Windows
```

**Comment by ringabout** [comment]
`newruntime` is taken over by `arc` and `orc`.
