### ISSUE TITLE
[style guide] [low priority] Naming conventions for modules?

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#12001]
I noticed in the [official style guide/NEP-1](https://nim-lang.org/docs/nep1.html) there is no mention of how module names should be written, this should be changed.

Personal opinion: I like `snake_case` for modules, but compiler/std seems to do `nocase`

**Comment by Araq** [comment]
We use ``snake_case`` too, ``db_sqlite`` etc. You're right that the style checker should check this.

**Comment by ghost** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/15590

**Comment by ghost** [comment]
Sorry, reopening, 
> We use snake_case too, db_sqlite etc. You're right that the style checker should check this.

is still not done
