### ISSUE TITLE
[ORC] `threadpool`'s `spawn(f(..))` won't compile when `f` has a return value...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#12005]
With `newruntime`, when `threadpool`'s `spawn` returns a `FlowVar[T]` due to the `spawn`'ed call `proc` having a return value `T`, the call to `spawn` has a compiler error.

### Example
```nim
# `spawn` returning FlowVar thinks it needs `system.newObj` when it shouldn't...
# likely do to that FlowVar's used to require a `deepCopy` and thus `newObj`;
# but don't anymore with "newruntime"...

# compile with "--newruntime" and "--threads:on"

from threadpool import spawn, `^`, sync

proc doworkok(i: int) {.thread.} = echo i
spawn(doworkok(42)); sync() # this works when returning void!

proc doworkbad(i: int): int {.thread.} = i
echo ^spawn(doworkbad(42)) # this doesn't when returning a FlowVar[T]!
```

### Current Output
```
Error: system module needs: newObj
```

### Expected Output
It should compile and run without error.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 HEAD/DEVEL nightly build of 19-August-2019 on Windows 64-bit
```

**Comment by xflywind** [comment]
`--newruntime` is taken over by `arc/orc`, so I add a testcase with `arc`.

**Comment by ringabout** [comment]
`newruntime` is taken over by `arc/orc`.

It works with `--gc:arc`.

It doesn't work with `--gc:orc`.

```nim
42
42
Traceback (most recent call last)
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\pure\concurrency\threadpool.nim(217) test
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\system\orc.nim(464) nimDecRefIsLastCyclicDyn
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\system\orc.nim(447) rememberCycle
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\system\orc.nim(140) unregisterCycle
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'D:\QQPCmgr\Desktop\Nim\test.exe '
```


It failed for all platforms on CI

![image](https://user-images.githubusercontent.com/43030857/110229855-64792a80-7f47-11eb-8d26-5f4d65f4f61f.png)

**Comment by timotheecour** [comment]
works for me on osx as of 1.5.1 b8c04bdb929f72ed8214122b255e88db9e713774

**Comment by Araq** [comment]
It got fixed indeed.

**Comment by ringabout** [comment]
Really? But the test can't pass CI with `--gc:orc`?
> It failed for all platforms on CI

**Comment by ringabout** [comment]
But I agree it it duplicated with https://github.com/nim-lang/Nim/issues/14901
