### ISSUE TITLE
Support msvc compiler (be able to produce Node.js native addons)

### ISSUE THREAD

**Issue by anurbol** [nim-lang/Nim#12009]
### Summary
Generated c/c++ code should not contain GCC-specific stuff (e.g. __attribute__).

### Description
I wanted to write a [node addon](https://nodejs.org/api/addons.html#addons_native_abstractions_for_node_js) in Nim, but unfortunately without success. I managed to do everything needed (getting generated .cpp files from `nimcache` folder, exporting nim symbols with .exportc.), but failed at the last stage. 
Turns out that Node addons binaries (Windows ones) are built [exclusively](https://github.com/nodejs/node-gyp/issues/402#issuecomment-35316212) by msvc (via [node-gyp](https://github.com/nodejs/node-gyp)), and the compiler does not understand Nim-generated c/c++ code, since the code is GCC specific.  To be more specific, Nim generates `__attribute__` things that's OK for GCC, but not for msvc, and msvc produces `c3646 unknown override specifier` errors.

### Alternatives
Well, I have to stick with c++ for now (I wanted to switch to Nim so badly)

**Comment by nc-x** [comment]
Use `--cc:vcc` for MSVC compiler. See https://nim-lang.org/docs/nimc.html#compiler-selection and https://nim-lang.org/faq.html (How do I use a different C compiler than the default one?).

**Comment by anurbol** [comment]
@nc-x  Lol what :smile:  Oh my God, I almost learned the contents of `nim --fullhelp` by heart, when I just should have to look at FAQ? LOL. Thanks!!! I'll try that!

**Comment by nc-x** [comment]
Yeah, i just checked, it is not there in --help or --fullhelp.

**Comment by anurbol** [comment]
> Yeah, i just checked, it is not there in --help or --fullhelp.

That's a material for another issue :smiley:

**Comment by anurbol** [comment]
Seems to work perfectly... Are Nim creators even Humans? I mean everything seems so good... I'll close this for now, but will reopen if something pops out.

**Comment by ohenepee** [comment]
@anurbol Did it work (I mean making the nodejs native addon thingy)? Any repo or tuts?
