### ISSUE TITLE
Detect command calls called with single tuple literal and emit warnings (i.e. `f(a, b)` vs. `f (a, b)`)

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#12006]
This seems to be a common issue with **new Nim users** - when calling procedures, `f(a, b)` is not the same thing as `f (a, b)` (note the space between `f` and the left parens) due to Nim allowing for parens-less calls (e.g. `f a, b, c`). [See here for more.](https://nim-lang.org/docs/manual.html#procedures-command-invocation-syntax)

Generally the metric by which we should emit a warning is:
1. Was the procedure called using command syntax?
2. Was the procedure called using a single tuple literal?

Also in addition:
1. Was the procedure called using command + method syntax (e.g. `a.f b`)?
2. Was the procedure called with only two arguments?
3. Was the last argument a tuple literal?

**Comment by Araq** [comment]
Reading the error message is all that is takes:

```nim

proc foo(x, y: int) =
  echo x, y

foo (1, 2)
```` 

```
Error: type mismatch: got <tuple of (int, int)>
but expected one of:
proc foo(x, y: int)
  first type mismatch at position: 1
  required type for x: int
  but expression '(1, 2)' is of type: tuple of (int, int)

expression: foo (1, 2)
```
