### ISSUE TITLE
Newruntime: with threads:on, channels module is missing...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#12004]
When a minimal program is compiled with "--newruntime" and "--threads:on", there is no `channels` module automatically imported as per the [documentation](https://nim-lang.org/docs/channels.html).

### Example
```nim
# missing `channels` module...
# compile with "--newruntime --threads:on"

var ch: Channel
```

### Current Output
```
Error: undeclared identifier: 'Channel'
```

### Expected Output
Successful compilation.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 HEAD nightly compiled 19-August-2019 (on Windows 64-bit)
```

**Comment by tiye** [comment]
weird, I see this error as well using `1.4.0`. it fails on CI https://github.com/Cirru/calcit-runner.nim/pull/82/checks

however as I ran locally, with 1.4.0 as well, no error occurred. CI is running Linux, and my local OS is macOS, only difference I could think of.

**Comment by ringabout** [comment]
I can't reproduce this issue in windows with Nim (v1.4.0, v1.2.6)
```nim
var ch: Channel
```
with `nim c -r --threads:on --newruntime test.nim`
get the expected output:
```nim
test.nim(1, 5) Error: invalid type: 'Channel' for var
```
And I remember `newruntime` will be deprecated in the future?

**Comment by tiye** [comment]
I don't have `--newruntime` in case. Unsure if that matters.

**Comment by ringabout** [comment]
Please open a new issue instead.

And I can't reproduce your issue in linux.

**Comment by ringabout** [comment]
You can't pass `threads:on` to `nimble test`. This is wrong`
https://github.com/Cirru/calcit-runner.nim/blob/43538faf2dd246f47ee9746c09d06be0c6468ab6/.github/workflows/tests.yaml#L18

**Comment by tiye** [comment]
Sounds reasonable... but way it worked on my mac?

**Comment by ghost** [comment]
@xflywind I think you actually can do that now.

**Comment by ghost** [comment]
From nimble readme:
"Nimble offers a pre-defined test task which compiles and runs all files in the tests directory beginning with 't' in their filename. Nim flags provided to nimble test will be forwarded to the compiler when building the tests."

**Comment by ringabout** [comment]
Yea, the CI uses Nim v1.2.6 and doesn't ship with this feature.

https://github.com/nim-lang/nimble/blob/master/changelog.markdown#0120

**Comment by tiye** [comment]
Oh, thanks. It's a lot easier to find a fix if that's a version problem. I just upgraded and it's working now https://github.com/Cirru/calcit-runner.nim/pull/85/files .

That task downloaded both 1.4.0 and 1.2.6, so I didn't notice 1.2.6 was actually used.

**Comment by ringabout** [comment]
It works with `newruntime` and `arc`.
