### ISSUE TITLE
Newruntime: owned nested closures not nesting destroy properly; dangling error...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#12008]
### Background

Closures can capture any sort of data from anywhere, including `var`'s, `owned` and "dangling" `ref`'s, `ptr T`, raw `pointer`, etc., with the `owned`/dangling (as is weak references to the same data as is `owned` by something else) bindings should be reference counted (if that option is enabled by debug or check settings), and with the bindings all stored as a (owned?) `ref` internal to the closure to the captured data stored on the heap.

For cross thread use, the old runtime provided a `deepCopy` that would copy the captured `ref` of the captured environment for a closure; however, there is no longer any `deepCopy` for the newruntime as it isn't usually necessary - any rare occasion where an `object`/`ref object` needs to be copied in order to produce two `owned` versions of the same data can be accomplished by a custom `proc` that just does this as the contents and contents size would be known by the author.

However, if we need a copy of a closure, we don't know the size of the captured environment to accomplish this, so can't do it

An alternative is a factory `proc` that can produce identical `owned` closures from capturing identical external data (or `var`'s or heap pointers, etc.) in order to share the same data across multiple closures.  This actually works as in the below code snippet. But...

### **The Actual problem**

When the factory `proc` producing closures is nested as in not a global, both the factory `proc`/closure and the closures it manufactures are currently automatically elevated to `owned` status.  This seems to confuse the destruction of the manufactured closures as to properly nullifying captures.  This may be because types captured in a closure's environment are not consistently considered whether to ref count or not:

### Example
```nim
# test newruntime closures...

# compile with "--newruntime"

proc main() =
  var x = 3
  proc clsrfctry(): auto = # an (owned) factory which is a closure itself, capturing x...
     (proc (): auto = result = x; x.inc) # produces an owned unless made unowned
  let clsr1 = clsrfctry(); clsr1.typeof.echo
  let clsr2 = clsrfctry()
  clsr1().echo; clsr1().echo; clsr2().echo; clsr2().echo
  x.echo # verify that the closures changed the stack value - it does!

main()
```
where one can play with this using [this Wandbox link](https://wandbox.org/permlink/7kB6hSUvxf8ueooO).

### Current Output
```
owned proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
3
4
[FATAL] dangling references exist
5
6
7
1 (this is the exit error code - GBG)
```

### Expected Output
```
owned proc (): int{.closure, noSideEffect, gcsafe, locks: 0.}
3
4
5
6
7
0
```
This should be possible to do without error in this case, as the stack variable `x` doesn't go out of scope until the end of `main` and the closures  `clsr1` and `xlsr2` should have been destroyed by then as well as before the destruction of the factory closure itself, so the dangling reference to x contained should be already gone. when the owned factory closure is destroyed.

I believe the problem is somehow to do with mis-tracking of ref counters with the nested closures' environments.  I think that perhaps the relationship of `owned` to non-`ref`'s hasn't been fully reasoned.

### Work around
```nim
# test newruntime closures...

# compile with "--newruntime"

proc main() =
  var x = 3
  proc clsrfctry(): auto = # an (owned) factory which is a closure itself, capturing x...
    unown (proc (): auto = result = x; x.inc) # produces an owned unless made unowned
  let clsr1 = clsrfctry(); clsr1.typeof.echo
  let clsr2 = clsrfctry()
  clsr1().echo; clsr1().echo; clsr2().echo; clsr2().echo
  x.echo # verify that the closures changed the stack value - it does!

main()
```
One can just add an `unown` for the factory manufactured returned closures to make this work without the Dangling error, which means that the manufactured closures, if owned, are treating the (unowned?) use of `x` as a dangling reference?

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.2 (on Windows 64-bit or Linux)
```

**Comment by narimiran** [comment]
The example produces the expected output with Nim devel v1.3.5 on my machine. @GordonBGood, can you confirm?

**Comment by ringabout** [comment]
newruntime is deprecated and taken over by ARC/ORC.
