### ISSUE TITLE
How do I mute "imported and not used" warnings?

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#12029]
I have a number of modules that get imported but which do not export any symbols, these have a bit of code which registers some data structures by calling a proc from the main code. All these modules generate a `imported and not used` warning because none of their symbols are used by other modules - which is intended.

Is there a way for a module to disable this "unused" warning about itself?

**Comment by Yardanico** [comment]
Yes, you can also do that with other types of messages, see, when you're trying to compile a file with unused imports you get a warning:
```
/home/dian/test.nim(1, 8) Warning: imported and not used: 'strutils' [UnusedImport]
```
In the brackets there's `UnusedImport`, which tells the name of the warning as it is like in the compiler.
To disable it, you add
```
warning("UnusedImport", off)
```
to <file_name>.nims config file (or to your main .nims file in your project), or, with `nim.cfg`:
```
--warning[UnusedImport]=off
```

**Comment by Araq** [comment]
You will be able to mark the module as ``{.used.}``.
