### ISSUE TITLE
Csources: huge size increase (x2.3) in 0.20

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12027]
Here are the sizes of the csources .zip files from the past 2 years

| Version | Commit  | Date       | Size      |
|---------|---------|------------|-----------|
| 0.17.0  | 9f7c507 | 2017-05-18 | 51.8 MiB  |
| 0.17.2  | 08c310b | 2017-09-07 | 64.8 MiB  |
| 0.18.0  | da97f85 | 2018-03-01 | 69.9 MiB  |
| 0.19.0  | b56e49b | 2018-09-26 | 80.8 MiB  |
| 0.20.0  | f72f471 | 2019-06-05 | **186.4 MiB** |

0.20.0 increased **compressed** csources size by 2.3x compared to before.

This is compounded when cloning the git repository (which might require some git garbage collection).

#### Potential rootcause

This might be related to the split of `-d:release` into `-d:release` and `-d:danger`. That would introduce lots of extra checks in the generated code if the sources are only built with `-d:release`. See also https://github.com/nim-lang/Nim/issues/11860.

**Comment by Araq** [comment]
That's indeed the reason. :-)
