### ISSUE TITLE
regression: new gensym handling incorrect for params, causing CT errors

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12020]
this is a regression introduced by the recent https://github.com/nim-lang/Nim/pull/11985 /cc @araq
params should not be gensym'd, this leads to CT errors in valid, previously working code

### Example
```nim
  macro foo(body: untyped): untyped =
    result = body

  template baz(): untyped =
    foo:
      proc bar2(b: int): int =
        echo b
        if b > 0: b + bar2(b = b - 1)
        else: 0
    echo (total: bar2(3))

  baz()
```

### Current Output
```
Error: type mismatch: got <b: int>
but expected one of:
proc bar2(b`gensym414421: int): int
  first type mismatch at position: 1
  unknown named parameter: b

expression: bar2(b = b`gensym414421 - 1)
          if b > 0: b + bar2(b = b - 1)
```

### Expected Output
```
3
2
1
0
(total: 6)
```

### Possible Solution
proc params should not be genesym'd (ie extend the rule that prevents `foo` to be gensym'd in  `(foo: bar)` to also consider params)

### Additional Information
https://github.com/nim-lang/Nim/issues/11091 is now also broken in a different way: prior to PR, it was broken because of ident=>sym conversion; now it's broken because `ident a => ident a`gensym414421 ` and indeed the assert fails in top post code

* Your Nim version (output of `nim -v`).
latest devel f2e8c39e851b1d1f55d387d80ae3d9f598a6ef0e

* Was it working in the previous Nim releases?
yes

**Comment by Araq** [comment]
Params *should* be gensym'ed. But maybe we can make the named parameter logic smarter.

**Comment by timotheecour** [comment]
> Params should be gensym'ed

why? they are introduced in routine scope so cannot pollute outer scope.
this causes all sorts of issues:
* this issue #12020
* this breaks https://github.com/nim-lang/Nim/pull/11916 (the tests break after new gensym rules, because it can't find the  `"result"`  parameter since it's now  result_gensym891082

* this makes following code compile when it shouldn't:
```nim
template baz() =
  proc fun1(a: int) = echo a
  proc fun1(a: int) = echo a
baz()
```
before  #11985 it correctly rejected with `Error: redefinition of 'fun1'`
after #11985 it now accepts this invalid code. And, there's no way to call `fun`.

* it makes `nim doc` ugly:
```nim
template generateProcs() =
  proc fun1(a: int) = echo a
generateProcs()

## nim doc output:
proc fun1(a`gensym405220: int) {...}
```
etc

**Comment by Araq** [comment]
Because this should be illegal:

```nim

template tmp(body) =
  proc foo(arg: int) = body

tmp:
  echo arg
```

**Comment by timotheecour** [comment]
/cc @araq
> To inject stuff use .inject or a .dirty template.

dirty changes semantics and puts everything in scope, so it's not an option.
for `inject`, how would you use it?

I couldn't make it work with templates (and don't want to use a macro just for that):
```nim
block:
  template funImpl() {.dirty.} =
    let z = 0
    # let z {.gensym.} = 0 # even that won't undo `dirty`
    proc fun(a: int) = discard
  funImpl()
  fun(a=1)
  echo z # I don't want `z` in scope, just the regular gensym'd symbols (`fun`)

block:
  template funImpl() =
    let z = 0
    proc fun(a: int) = discard
  funImpl()
  # fun(a=1) # Error: type mismatch: got <a: int literal(1)> but expected one of: t0713.fun(a`gensym423242: int) 

block:
  template funImpl() =
    let z = 0
    # proc fun(a : int) {.inject.} = discard # doesn't help with fun(a=1)
    when false:
      # parser error
      proc fun(a {.inject.} : int) = discard
  funImpl()
  # fun(a=1)
```

## proposal 1 (non controversial IMO)
* proc params and type fields can be annotated with `{.gensym.}` or `{.inject.}`

this makes every use case possible, albeit requires annotations where appropriate

## proposal 2 (complements proposal 1)
* default for proc params is `{.gensym.}`, just like for fields (https://nim-lang.github.io/Nim/manual.html#templates-hygiene-in-templates is underspecified: no mention of skField, skParam).

this makes every use case possible, and makes the common case require no annotation

**Comment by timotheecour** [comment]
this keeps causing issues, eg:
* [Docs: Remove gensym from arguments for procs defined in templates? - Nim forum](https://forum.nim-lang.org/t/6979)

**Comment by Clyybber** [comment]
@timotheecour you can use `{.inject.}` and `{.gensym.}` on params nowadays.
