### ISSUE TITLE
Emit interpolation of template parameters

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12038]
Branched off #12036 and very similar to https://github.com/nim-lang/Nim/issues/4730

`emit` does not interpolate properly template parameters.

Test case: 

```Nim
template myAdd*(a: var int, b: int) =
  {.emit: "`a` += `b`;".}

proc main() =
  var a_input = 10
  let b_input = 100

  myAdd(a_input, b_input)

  echo a_input

main()
```

```C
N_LIB_PRIVATE N_NIMCALL(void, main__MlSvLmAoyeZDbNlPTjOs9aw)(void) {
	NI a_input;
	NI b_input;
	tyArray__nHXaesL0DJZHyVS07ARPRA T1_;
	a_input = ((NI) 10);
	b_input = ((NI) 100);
	a += b;
	nimZeroMem((void*)T1_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T1_[0] = nimIntToStr(a_input);
	echoBinSafe(T1_, 1);
}
```
```
/home/beta/.cache/nim/gensym_emit_r/gensym__emit.nim.c: In function ‘main__MlSvLmAoyeZDbNlPTjOs9aw’:
/home/beta/.cache/nim/gensym_emit_r/gensym__emit.nim.c:64:2: error: ‘a’ undeclared (first use in this function)
   64 |  a += b;
      |  ^
/home/beta/.cache/nim/gensym_emit_r/gensym__emit.nim.c:64:2: note: each undeclared identifier is reported only once for each function it appears in
/home/beta/.cache/nim/gensym_emit_r/gensym__emit.nim.c:64:7: error: ‘b’ undeclared (first use in this function)
   64 |  a += b;
      |       ^
```

As a reminder here is the state of the emit pragma.

|                         | Issue in 0.20 | Issue in devel | Issue         |
|-------------------------|---------------|----------------|---------------|
| proc parameter          | no            | no             |               |
| proc local variable     | no            | no             |               |
| **template parameter**  | **yes**       | **yes**        | **Current issue** |
| template local variable | no            | yes            | #12036        |

**Comment by Araq** [comment]
As I said, use this instead:

```nim

template myAdd*(a: var int, b: int) =
  {.emit: [a, " += ", b].}

``` 

Templates don't look into string literals, surprise. (Not!)
