### ISSUE TITLE
Newruntime:  `shallow` doesn't work on `seq`...

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#12046]
The `shallow` `proc` hasn't been updated to reflect the new implementation of `seq` in `newruntime`.

### Example

```nim
# test new `seq`'s...

# compile with "--newruntime"

var sq1 = @[42]; sq1.shallow
```

### Current Output
```
Error: undeclared identifier: 'PGenericSeq'
1
```

### Expected Output
It is expected to compile and work as for before `newruntime`.

### Further Discussion
Even when it works as intended, this shows that every `seq` copy causes a deep copy of the `seq` (and `string`'s (and any `seq`'s or `string`'s contained in another object, according to the documentation) almost certainly work the same way) other than for some "special cases" that can be elided for function parameter passing by data flow analysis.  This "value" stack based semantics is the main reason that Nim is not performant as compared to languages that have "reference" heap based semantics for array-like structures depending on garbage collection (or reference counting) to prevent premature destruction of active data.

Yes, one can mark `seq`'s and `string`'s as `shallow` with this `proc` (when it works) to get a shallow copy with a common shared data array, but this is another "special case" which breaks the simplicity of everything always working the same, as should be Nim's goal.  Implementing `shallowCopy` in a special way, especially when one need to consider that `seq`'s may contain other `seq`'s and/or strings and any copied object may contain any level of nested `seq`'s and or strings makes this just as UGLY as `deepCopy` used to be before it was removed in `newruntime`.

Now that Nim will have a better memory model in `newruntime`, perhaps it's time to revisit the  decision to use "value" semantics by preference, as if `seq`/`string`/other structure based types that refer to heap data were rather `owned ref`, this would solve the problem of premature deallocation of nested pointers shared between copies, as `owned ref`'s can't be copied, unowned `ref`'s can be copied but can't be deallocated, and specialized overrides of  a "clone" would only be necessary in the reasonably rare case where one needs a new independently `owned` copy of the original, with possible alternate (user chosen) implementations of this "clone" including wrapping the data in a full reference counted structure, if necessary.

This would be similar to the way Rust backs up the its similar "owned/reference" model with the "Clone" trait that can be implemented in different ways as required (including as a reference counted structure).

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.XXX up to latest nightly as of 25-August-2019
```

**Comment by Araq** [comment]
``shallow`` always has been a bad idea and the new runtime cannot support it, so that doesn't count as a real bug, except that the error message could be better. And while I agree that with ownership we could design better seqs and strings this should be left to libraries to explore, too much code depends on the value semantics of seqs and strings. Having said that, with move semantics most silly copy operations are optimized away anyway, mitigating this problem substantially.

**Comment by GordonBGood** [comment]
Okay, I see your point that the best we can do for now is a more meaningful error message something to the effect that there is no `shallow` in the `newruntime`.

Yes, I also see your point that perhaps too much current code would be broken if `string` and `seq` were changed to "pure" `ref` based rather than the current value based embedding a pointer - pity.

It means that if one wants a pure `ref` based `seq` one has to write it oneself, which isn't hard but does take some 10's of lines of code.

**Comment by narimiran** [comment]
The example produces the expected output with Nim devel v1.3.5 on my machine. @GordonBGood, can you confirm?

**Comment by GordonBGood** [comment]
> The example produces the expected output with Nim devel v1.3.5 on my machine. @GordonBGood, can you confirm?

@narimiran, yes, the issue example does now compile with Nim devel 1.3.5 as of 10 hours ago whereas it didn't before.

Since `--gc:arc` and --gc:orc` didn't yet exist when this issue was written, I also tested with them and it also compiles and runs for them, with the call to `shallow` acting as a no-op (just as a call to `shallowCopy` just does a copy).

However, as there is now no mechanism for marking `seq`'s, `string`'s or any objects as candidates for shallow copying, running this `shallow` routine is a now a no-op under these runtime options so if a programmer is expecting the former behaviour, then they will be disappointed, and there is no warning that expecting shallow copies is now not supported for these new runtime's; that could lead to some frustration for some?

As per the above discussion with @Araq, I think there should be a warning issued when this feature is used with any of the new runtimes?

Also, the documentation needs to be changed to reflect that the whole concept of shallow copying `seq`'s and `string`'s only works with the "old" GC runtimes and the new behaviour just changes `shallowCopy` into a direct default copy with the use of the `shallow` function ignored.

**Comment by Araq** [comment]
Closing this for now, it works as it should. Documentation will improve.
