### ISSUE TITLE
Memory leak with set

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#12052]
I have been investigating the high memory usage of my application for some days now. One cause that I've just found is `set`. The memory grows unbounded in my program if I use it.

I've tried to reproduce this, but the best I could do is to get an application that uses a lot of memory (the memory usage doesn't grow). The example below uses 75MB of memory on my MacBook, and a simple [s/set/HashSet/](https://gist.github.com/dom96/6bb78b205e9dbc710ebcacb56644ee57) makes that decrease to 1.5MB so there is surely something wrong here.

As far as my application goes, switching to HashSet also fixes the unbounded growth.

### Example

```nim
import tables, sets

type
  BotEventKind* = enum
    DirectionChanged, SpeedChanged, SizeChanged, NearbyFoods, NearbyPlayers,
    PlayerDeath, FoodEaten

  Degrees = float
  PlayerID = distinct int16
  ParticleID = (PlayerID, int)
  Point[T] = object
    x, y: T

  NearbyPlayerTuple* = tuple[id: PlayerID, pos: Point[float], size: float, gap: float]
  NearbyFoodTuple* = tuple[id: ParticleID, pos: Point[float], size: uint8, dist: float]
  BotEvent* = object
    case kind*: BotEventKind
    of DirectionChanged: # Triggered on direction change as set/sent to server.
      direction*: Degrees
    of SpeedChanged: # Triggered when the speed changes.
      speed*: int # How fast the player is moving per second.
      burst*: bool
    of SizeChanged: # Triggered when the bot size changes.
      size*: float
      delta*: float
    of NearbyFoods:
      foods*: seq[NearbyFoodTuple]
    of NearbyPlayers:
      players*: seq[NearbyPlayerTuple]
    of PlayerDeath:
      deadPlayers*: set[PlayerID]
    of FoodEaten:
      foodEaten*: HashSet[ParticleID]
  
  Bot = ref object
    queuedEvents: Table[BotEventKind, BotEvent]
 

proc queueEvent(bot: Bot, event: BotEvent) =
  bot.queuedEvents[event.kind] = event

proc getEvents(bot: Bot): Table[BotEventKind, BotEvent] =
  return bot.queuedEvents

proc onTick(bot: Bot) =
  let events = bot.getEvents()
  if SpeedChanged in events:
    discard

proc eventLoop(bot: Bot) =
  bot.queueEvent(
    BotEvent(
      kind: SpeedChanged,
      speed: 12,
      burst: true
    )
  )
  bot.queueEvent(
    BotEvent(
      kind: DirectionChanged,
      direction: 4.5,
    )
  )
  
  bot.queueEvent(
    BotEvent(
      kind: PlayerDeath,
      deadPlayers: {PlayerID(12)}
    )
  )
  
  bot.onTick()
  bot.queuedEvents.clear()

proc runBots() =
  var bots: seq[Bot]
  for i in 0 .. 100:
    bots.add(Bot())
  
  while true:
    for b in bots:
      b.eventLoop()

runBots()
```

### Current Output
Memory usage is 75MB

### Expected Output

Memory usage should be lower, or alternatively we should disallow usage of `set` this way to prevent memory leaks (or perceived memory leaks).

### Possible Solution

Use HashSet instead

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-08-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8407a574992ebd6bccec647a902cf54a4de8db18
active boot switches: -d:release
```

**Comment by Araq** [comment]
Well ``set`` is implemented as a bitset and only allows for ``uint16`` for this reason. I don't see how further restricting it would help.

**Comment by dom96** [comment]
Well, from what I could tell the allocator doesn't handle this very well. Do you have any ideas why that might be?

**Comment by Araq** [comment]
Memory usage with Boehm is even higher for me, that rules out fragmentation. You have 101 bots each has a table with 64 entries, each entry takes roughly 8KB, total memory usage about 50.648MiB. Floating garbage and other stuff makes it 82MiB on my machine. Perfectly acceptable except that tables's ``defaultInitialSize* = 64`` is a bit high.

**Comment by dom96** [comment]
Is it acceptable? This is quite a gotcha that might make some feel that
there is a bug in Nim causing a mem leak. We should at least document this
well.

**Comment by Araq** [comment]
There is no leak and here is another workaround:

```nim

proc runBots() =
  var bots: seq[Bot]
  for i in 0 .. 100:
    bots.add(Bot(queuedEvents: initTable[BotEventKind, BotEvent](8)))
```
