### ISSUE TITLE
Negative floats are converted to double precision in the C backend

### ISSUE THREAD

**Issue by JDragan** [nim-lang/Nim#12056]
This results in performance drop

### Example

```nim
proc main() =
  
  let z = 10.0'f32
  
  if z > -0.1'f32:
    echo "more"
  if z < 0.1'f32:
    echo "less"

main()
```

### Generated C code
```c
N_LIB_PRIVATE N_NIMCALL(void, main__WT5bdlPWc6VHEZkxs56sUA)(void) {
        NF32 z;
        z = 1.0000000000000000e+01f;
        {
                if (!(-1.0000000000000001e-01 < z)) goto LA3_;
                echoBinSafe(TM__tJFdVcCXt79a8K7xYCw4R7g_2, 1);
        }
        LA3_: ;
        {
                if (!(z < 1.0000000000000001e-01f)) goto LA7_;
                echoBinSafe(TM__tJFdVcCXt79a8K7xYCw4R7g_4, 1);
        }
        LA7_: ;
}
```

### Expected C code

```c
// ...
if (!(-1.0000000000000001e-01f < z)) goto LA3_;
// ...
```
Notice how the minus uses a double "-1.0000000000000001e-01" instead of a single precision float "1.0000000000000001e-01f".
Benchmarking shows that a lot of time is spent on single to double conversion via cvtss2sd instruction.
### Discussion
https://forum.nim-lang.org/t/5124

```
$ nim -v
Nim Compiler Version 0.20.2 [Windows: amd64]
Compiled at 2019-07-17
```

**Comment by mratsim** [comment]
Perf impact is about 10%

view of ASM code
![DeepinScreenshot_select-area_20190826191206](https://user-images.githubusercontent.com/22738317/63726185-cb9b2680-c85c-11e9-8571-bbe8a3560c99.png)

**Comment by JDragan** [comment]
Nim 0.19.4 has the same issue
