### ISSUE TITLE
[IC] `--incremental:on -f` gives `Undefined symbols` error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12057]
### Example
```nim
echo "Hello World"
```
```
nim c --incremental:on --nimcache:/tmp/d05 -f main.nim # 1st one succeeds
nim c --incremental:on --nimcache:/tmp/d05 -f main.nim # 2nd fails
```
### Current Output
```
Undefined symbols for architecture x86_64:
_main
```

### Expected Output
should work

### Additional Information
* Your Nim version (output of `nim -v`).
latest devel 8117a949c58ce108b3de2f926602b6d57dddcbdf

**Comment by ghost** [comment]
@timotheecour works now, close? https://github.com/nim-lang/Nim/pull/17311 enables the hello world IC test but it already works in devel.

**Comment by timotheecour** [comment]
there should be a test before this can be closed

**Comment by Araq** [comment]
This works now.
