### ISSUE TITLE
Error: 'X' escapes its stack frame; context: 'X'; see https://nim-lang.org/docs/manual/var_t_return.html is 404

### ISSUE THREAD

**Issue by iffy** [nim-lang/Nim#12087]
I'm doing something wrong with variables, but the referenced manual page that supposedly tells me what I'm doing wrong does not exist.  Here's the error:

```
Error: 'proto' escapes its stack frame; context: 'proto'; see https://nim-lang.org/docs/manual/var_t_return.html
```

But <https://nim-lang.org/docs/manual/var_t_return.html> doesn't exist.

**Comment by Araq** [comment]
Correct link is: https://nim-lang.org/docs/var_t_return.html

:-)

**Comment by Bennyelg** [comment]
![image](https://user-images.githubusercontent.com/9398172/64619899-8db90900-d3eb-11e9-9bac-83ffbf635750.png)
How is `explanationsBaseUrl` populated ? thought it's global variable but nop.

**Comment by 3n-k1** [comment]
@iffy Could you post the code that's having issues? I'd like to try and test where exactly the issue is.

**Comment by 3n-k1** [comment]
Looks like the issue is coming from [this string](https://github.com/nim-lang/Nim/blob/ee36931f26de138afd59a6497debee42567962c0/compiler/lineinfos.nim#L16) which was fixed 15 days ago in 0118ebd

This can probably be closed.

**Comment by iffy** [comment]
@3n-k1 rats... I can't believe I didn't submit a code snippet.  I don't have the code handy.  It had something to do with returning a var type variable?  If I can reproduce, I'll check with the latest version to see if it's fixed.  But if someone else knows offhand how to make it happen, it might be faster.

**Comment by Araq** [comment]
Reopen if still an issue.
