### ISSUE TITLE
Newruntime: Destroy proc isn't called properly

### ISSUE THREAD

**Issue by ShieldHero** [nim-lang/Nim#12092]
Function `=destroy` isn't called when you define a function with a sink parameter before it. Forward declaration doesn't work on `=destroy` to solve it.

### Example

```nim
type Obj* = object
  v*: int

# proc `=destroy`(this: var Obj) # Error: Cannot bind another `=destroy`

proc something(this: sink Obj) = 
  discard

proc `=destroy`(this: var Obj) =
  echo "igotdestroyed"
  this.v = -1

var test* = Obj(v: 42)
```

### Expected Output

```
igotdestroyed
```

### Possible Solution
Putting the `=destroy` first fixes it.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [Windows: i386]
Compiled at 2019-08-28
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 20dec10722eecb1e9b9ee43a3e1cda7533837c72
active boot switches: -d:release
```

**Comment by cooldome** [comment]
The compiler would reject this code with error: destructor declared too late.
I will provide a fix

**Comment by cooldome** [comment]
added support for forward declared destructors too
