### ISSUE TITLE
Time collisions std lib

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12090]
I get into collisions playing with ZIP, Nimgen, Nimterop, posix, basically today on std lib theres 3 of:
- `times.Time` ➡️ `Time`
- `posix.Time` ➡️ `Time`
- `time_t.Time` ➡️ `Time`

#### Possible solutions

- Rename `posix.Time` to `posix.posixTime` ➡️ `posixTime`
- Rename `time_t.Time` to `time_t.TimeT` ➡️ `TimeT`
- Leave `times.Time` untouched ➡️ `Time`

OR

- Change Documentation everywhere that `Time` must be fully qualified always to avoid collisions.

I dont think they can be merged into 1 because they can be different things, but I dunno.

#### Example

- This kind of bug: https://github.com/nim-lang/zip/issues/47#issue-481984593 (I can not import `Time as FOO` here)

I think a simple solution can prevent future confusion.

:slightly_smiling_face:

**Comment by Araq** [comment]
What's wrong? The compiler enforces full qualification for these names.

**Comment by juancarlospaco** [comment]
Ok :+1: 
Maybe Docs can explicitly say that, because it uses `Time` everywhere then confuses new people.

**Comment by Araq** [comment]
Well ``times.Time`` is meant, the others are implementation details and platform specific.
