### ISSUE TITLE
CI for FreeBSD and OpenBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12103]
### Summary

We currently have CI support for Linux, macOS and Windows. It would be nice to expand this to cover other operating systems.

### Description

We currently have GitLab CI, Travis CI and AppVeyor CI, but none of these providers support FreeBSD or OpenBSD (or any other BSD for that matter).

It would be nice to expand this coverage and possibly provide pre-built binaries for these platforms.

I oppose that we use [builds.sr.ht](https://builds.sr.ht) to provide CI for other platforms as they support both [FreeBSD](https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd) and [OpenBSD](https://man.sr.ht/builds.sr.ht/compatibility.md#openbsd) and are growing rapidly so could include other platforms (and architectures!) in the future. They also have some cool features like being able to SSH in to build VMs to test builds.

### Alternatives

[Cirrus CI](https://cirrus-ci.org) support FreeBSD, but not OpenBSD.

**Comment by cheatfate** [comment]
@euantorano MacOS is actually BSD, so Travis CI can cover some of the problems here.

**Comment by euantorano** [comment]
macOS has some FreeBSD userland utilities, Utd they are still a little different, and OpenBSD is significantly different.

**Comment by cheatfate** [comment]
@euantorano but Nim language and stdlib do not interact with utilities. We using some syscalls and posix. Or you are talking about Nim's bootstrap process?

**Comment by euantorano** [comment]
I’m talking about bootstrapping on FreeBSD. 

See my PR linked to this issue for some of the OpenBSD issues I’ve found so far.

**Comment by euantorano** [comment]
(for an example of a FreeBSD bootstrapping problem, [see here](https://github.com/nim-lang/Nim/issues/12113)... 😉)

**Comment by lbartoletti** [comment]
@euantorano you can use [cirrus-ci](https://cirrus-ci.com/) for FreeBSD.

Let me know if you want some help or test.
