### ISSUE TITLE
Invalid CHMOD in `tests/async/tioselectors`

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12119]
The test `async/tioselectors` contains the following code:

```nim
# chmod testDirectory to 0777
chmodPath(testDirectory, 0x1FF)
```

`0x1FF` is `511` decimal and it seems that's what's passed in to `posix.chmod`, resulting in the following test failure on OpenBSD:

```
FAIL: tests/async/tioselectors.nim C
Test "tests/async/tioselectors.nim" in category "async"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
mexitcode: 1

Output:
tioselectors.nim(471)    tioselectors
tioselectors.nim(324)    vnode_test
tioselectors.nim(264)    chmodPath
fatal.nim(48)            sysFatal
Error: unhandled exception: value out of range: 511 [RangeError]
```

I'm not sure if I should just change the code to pass `777`? If so, there's at least one other place in the same tets that seems suspicious: https://github.com/nim-lang/Nim/blob/devel/tests/async/tioselectors.nim#L381

**Comment by cheatfate** [comment]
Its very weird, because `0777` is octal number which is equal to `511` decimal number which is equal to `0x1FF` hexadecimal number.

Same weird problem with `0666` is octal number which is equal to `438` decimal number which is equal to `0x1B6` hexadecimal number.

**Comment by euantorano** [comment]
Check the constant values defined here: http://man7.org/linux/man-pages/man2/chmod.2.html (for example `S_IRGRP (00040)`). Are we sure that `posix.chmod` is meant to take the octal values and not just standard decimal values?

**Comment by euantorano** [comment]
I've just tested on linux and the hex number works as expected there. I'm about to test on FreeBSD then OpenBSD.

**Comment by euantorano** [comment]
Ok, so running the following code on OpenBSD runs fine:

```nim
import posix, os

const dir_path = "./test_dir"

discard existsOrCreateDir(dir_path)

var info = getFileInfo(dir_path)

echo "Permissions before: ", info.permissions

let err = posix.chmod(dir_path, Mode(0x1FF))
if err == -1:
  raiseOsError(osLastError())

info = getFileInfo(dir_path)

echo "Permissions after: ", info.permissions
```

I get the following output:

```
Permissions before: {fpUserExec, fpUserWrite, fpUserRead, fpGroupExec, fpGroupRead, fpOthersExec, fpOthersRead}
Permissions after: {fpUserExec, fpUserWrite, fpUserRead, fpGroupExec, fpGroupWrite, fpGroupRead, fpOthersExec, fpOthersWrite, fpOthersRead}
```

Which is correct.

**However**

If I change the script to:

```nim

import posix, os

proc chmodPath(name: string, mode: cint) =
  let err = posix.chmod(cstring(name), Mode(mode))
  if err == -1:
    raiseOsError(osLastError())


const dir_path = "./test_dir"

discard existsOrCreateDir(dir_path)

var info = getFileInfo(dir_path)

echo "Permissions before: ", info.permissions

chmodPath(dir_path, 0x1FF)

info = getFileInfo(dir_path)

echo "Permissions after: ", info.permissions
```

I get the error:

```
Permissions before: {fpUserExec, fpUserWrite, fpUserRead, fpGroupExec, fpGroupWrite, fpGroupRead, fpOthersExec, fpOthersWrite, fpOthersRead}
/home/administrator/test/test.nim(17) test
/home/administrator/test/test.nim(4) chmodPath
/home/administrator/build/Nim/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: value out of range: 511 [RangeError]
Error: execution of an external program failed: '/home/administrator/test/test '
```

Which is... interesting 😄

**Comment by euantorano** [comment]
The following snippet also crashes with the same error on both OpenBSD and Linux (including the playground):

```nim
import posix

let m1: int = 0x1FF
let m2: cint = 0x1FF

echo Mode(m1)
echo Mode(m2)
```

However, changing it to:

```nim
import posix

let m1: int32 = 0x1FF
let m2: cint = 0x1FF

echo Mode(m1)
echo Mode(m2)
```

Works, so it seems to be a problem with the implicit cast from an `int` to `cint` on 64 bit systems.
