### ISSUE TITLE
Out of swapspace on FreeBSD/PowerPC64

### ISSUE THREAD

**Issue by lenoil98** [nim-lang/Nim#12115]
Nim compiler causes out of swapspace failure when run on FreeBSD/PowerPC64.  Compiler built with changes from PR #12011.

# bin/nim -v
Nim Compiler Version 0.20.0 [FreeBSD: powerpc64]
Compiled at 2019-08-24
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches:

### System config:
FreeBSD: 11.2-RELEASE
RAM: 12GB

### Output:
root@lenoil8:/usr/ports/tmp/Nim # bin/nim c koch
Hint: used config file '/usr/ports/tmp/Nim/config/nim.cfg' [Conf]
Hint: used config file 'koch.nim.cfg' [Conf]
Hint: used config file '/usr/ports/tmp/Nim/config/config.nims' [Conf]
/usr/ports/tmp/Nim/lib/system.nim(81, 3) Hint: 'nil' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(684, 5) Hint: 'NimString' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(3321, 7) Hint: 'NimStackTrace' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(2081, 10) Hint: 'sysAssert' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(251, 7) Hint: 'ThisIsSystem' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(1976, 3) Hint: 'hasSharedHeap' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(1948, 3) Hint: 'strlitFlag' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(3323, 10) Hint: 'coroutinesSupportedPlatform' is declared but not used [XDeclaredButNotUsed]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
/usr/ports/tmp/Nim/lib/system/avltree.nim(27, 6) Hint: 'find' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/cellsets.nim(66, 6) Hint: 'deinit' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/sysstr.nim(111, 6) Hint: 'newOwnedString' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(3686, 7) Hint: 'SafePoint' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/mmdisp.nim(38, 3) Hint: 'PByte' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(81, 3) Hint: 'nil' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(838, 8) Hint: 'GC_setStrategy' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(251, 7) Hint: 'ThisIsSystem' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/osalloc.nim(27, 7) Hint: 'doNotUnmap' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/cellsets.nim(184, 10) Hint: 'elements' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(142, 10) Hint: 'color' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/dyncalls.nim(18, 3) Hint: 'NilLibHandle' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/alloc.nim(809, 6) Hint: 'rawAlloc0' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(143, 10) Hint: 'setColor' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/dyncalls.nim(72, 8) Hint: 'dlerror' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(38, 3) Hint: 'rcPurple' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/alloc.nim(975, 6) Hint: 'getFreeMem' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc_common.nim(251, 8) Hint: 'isActiveStack' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/mmdisp.nim(39, 3) Hint: 'PString' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/cellsets.nim(237, 10) Hint: 'elementsExcept' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/cellsets.nim(45, 6) Hint: 'contains' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/mmdisp.nim(17, 3) Hint: 'debugGC' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/alloc.nim(998, 8) Hint: 'deallocOsPages' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/cellsets.nim(163, 6) Hint: 'excl' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/repr.nim(147, 8) Hint: 'reprBreak' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system.nim(3323, 10) Hint: 'coroutinesSupportedPlatform' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/alloc.nim(976, 6) Hint: 'getTotalMem' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(37, 3) Hint: 'rcWhite' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/excpt.nim(60, 3) Hint: 'raiseCounter' is declared but not used [XDeclaredButNotUsed]
/usr/ports/tmp/Nim/lib/system/gc.nim(36, 3) Hint: 'rcGray' is declared but not used [XDeclaredButNotUsed]
Hint: koch [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
/usr/ports/tmp/Nim/lib/pure/pathnorm.nim(45, 10) Hint: 'dirs' is declared but not used [XDeclaredButNotUsed]
Hint: posix [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
/usr/ports/tmp/Nim/lib/pure/times.nim(2455, 26) Warning: countLeapYears is deprecated [Deprecated]
/usr/ports/tmp/Nim/lib/pure/times.nim(2462, 15) Warning: countLeapYears is deprecated [Deprecated]
/usr/ports/tmp/Nim/lib/pure/times.nim(2470, 24) Warning: countLeapYears is deprecated [Deprecated]
/usr/ports/tmp/Nim/lib/pure/os.nim(2043, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
/usr/ports/tmp/Nim/lib/pure/os.nim(2160, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
/usr/ports/tmp/Nim/lib/pure/os.nim(2293, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
Hint: parseopt [Processing]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: kqueue [Processing]
/usr/ports/tmp/Nim/lib/pure/osproc.nim(1358, 8) Hint: 'select' is declared but not used [XDeclaredButNotUsed]
Hint: kochdocs [Processing]
swap_pager_getswapspace(32): failed
swap_pager_getswapspace(32): failed

### Expected:
Successful koch build.

### Additional Information:
System seems to hang.  Random processes are aborted due to out of swap space.  Compiler and tools will build if code for linux/powerpc64 is used.

**Comment by Araq** [comment]
There have been improvements to the build process that are not shipping in 0.20.0, please try Nim devel.

**Comment by lenoil98** [comment]
First, the csources does not contain support for freebsd/powerpc64, so I first used the linux/powerpc64 code and get the below:

bin/nim c --skipUserCfg --skipParentCfg koch
/Users/andreasrumpf-mac/projects/nim/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: value out of range: -1 [RangeError]

Can not use the macosx/powerpc64 code without modifications.  That is why I used the converted csources for the 0.20.0 release, generated on a freebsd/amd64 system.

The resulting compiler is what causes the swap space condition.  

### Here the summary of my efforts:
-- I can build a semi-working compiler, using code for linux/powerpc64 for releases up to 0.20.0.   However, frequently encounter " unhandled exception: value out of range" errors when compiling code or building applications.

-- I can build a semi-working compiler, using re-created csources for releases up to 0.20.0.  However, always encounter the swap space issue.  Smaller code will eventually complete successfully. But, larger code will result in an unstable or frozen system. Adding swap space only lengthens the process and delays the unstable or frozen condition.

**Comment by Araq** [comment]
This is not how to cross-compile.

**Comment by lenoil98** [comment]
I've seem instructions on cross-compiling apps, but haven't seen how to cross compile the nim compiler.  Where are the instructions/guidance for cross-compiling the compiler?

**Comment by lenoil98** [comment]
Although my process is not the way "to cross-compile" it works for my purposes.  However, I seem to have found a solution to my "out of swap space" issue, by turning off processor "auto-detect" in nim.cfg.
