### ISSUE TITLE
Prevent nimsuggest from executing staticExec

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12125]
See https://irclogs.nim-lang.org/04-09-2019.html#11:18:36
and https://irclogs.nim-lang.org/13-05-2019.html#15:36:04

Assume you start writing `staticExec('rm -rf ./...')` you don't have time to finish that you nuked your repo.

We could also expect malicious packages that would use this security hole.

**Comment by genotrance** [comment]
This is the beginning of the end. But hard to argue with.
