### ISSUE TITLE
`ByteAddress` broken for its intended purpose

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#12122]
https://github.com/nim-lang/Nim/blob/cb0450398a5695e1e1193e6c49ff9c7548980438/lib/system.nim#L2205

`ByteAddress` is an `int` - this is problematic for several reasons:

* you can't use it for its documented purpose of printing / readability: address space generally is not considered  to go into the negative
* you can't do arithmetic on it because `int` is a checked type that will raise even on seemingly valid pointer operations: for example linux in 32-bit mode uses a 3gb address space for pointers meaning that at least at the 2gb mark, it crosses into `int` negative space

It seems appropriate to deprecate this type and add a new `uint`-based distinct type that has a few pointer operations attached to its name along with documentation explaining the pitfalls of doing  so.

**Comment by arnetheduck** [comment]
#12101 is an example of where this can go wrong (casting real pointers and expecting arithmetic will work ok)

**Comment by mratsim** [comment]
usually all code that uses `ByteAddress` uses `+%` (which seems like a waste of an operator given the narrow use but that's another topic)

**Comment by krux02** [comment]
Yes I agree. ByteAddress should be a `uint`. The only reason I did not do it yet, it is a breaking change.

**Comment by awr1** [comment]
I assume the reason is historical? (since unsigned numbers used to be discouraged, and Nim once had `unsigned` as a module)

**Comment by krux02** [comment]
There was a time when there was no unsigned int at all. A few artifacts from that time are left in the language. This is one of them.
