### ISSUE TITLE
Regression: new hash function related

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#12146]
On latest Nim the following example no longer works:
```nim
import tables
const rMap = {"": "R", "R": "R", "14": "R_14", "R_14": "R_14", "NR": "NR"}.toTable

let rtype = "R"
echo rMap[rtype]
```

Examples compiles but now gives exception at runtime:
```
Error: unhandled exception: key not found: R [KeyError]
```

**Comment by narimiran** [comment]
I couldn't reproduce, i.e. on my machine this example prints `R`.

**Comment by Araq** [comment]
Works on Win64 too. Are you sure you used a completely bootstrapped Nim version?

**Comment by juancarlospaco** [comment]
Cant repro.

**Comment by cooldome** [comment]
Apologies, I indeed used nim_temp. With bootstrap compiler works fine.
