### ISSUE TITLE
nimpretty generates broken formatting

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#12155]
```nim
proc hid_open*(vendor_id: cushort; product_id: cushort; serial_number: cstring): ptr HidDevice {.
    importc: "hid_open", dynlib: hidapi.}
```

gets formatted into

```nim
proc hid_open*(vendor_id: cushort; product_id: cushort;
    serial_number: cstring): ptr HidDevice {.

importc: "hid_open", dynlib: hidapi.}
```

**Comment by timotheecour** [comment]
things would be so much easier without the 80 column limit causing hard line wrap. All modern editors allow soft-line-wrap when displaying long lines.

**Comment by Araq** [comment]
The editors don't understand how to wrap them properly though. Not even nimpretty knows so how could they... ;-)

**Comment by timotheecour** [comment]
source code for strutils.isUpperAscii (after I removed the hard line wrap in proc signature):
```nim
proc isUpperAscii*(c: char): bool {.noSideEffect, procvar, rtl, extern: "nsuIsUpperAsciiChar".} =
  ## Checks whether or not `c` is an upper case character.
  ##
  ## This checks ASCII characters only.
  ## Use `Unicode module<unicode.html>`_ for UTF-8 support.
  ##
  ## See also:
  ## * `toUpperAscii proc<#toUpperAscii,char>`_
  runnableExamples:
    doAssert isUpperAscii('e') == false
    doAssert isUpperAscii('E') == true
    doAssert isUpperAscii('7') == false
  return c in {'A'..'Z'}
```

heres's sublimetext in 3 different editor widths (on my monitor, even with lots of panes/tabs open concurrently, I almost never go even near 80 columns (remnant from the 80's terminals), but even if I do, the soft line wrap is perfectly readable: 

at ~ 40 colums editor width:
![image](https://user-images.githubusercontent.com/2194784/64550131-0d10e480-d2e7-11e9-8491-1e4a6ca9db46.png)
at ~ 82 colums editor width:
![image](https://user-images.githubusercontent.com/2194784/64550167-2023b480-d2e7-11e9-96b5-9a9c3f9a1e22.png)
at > 120 colums editor width:
![image](https://user-images.githubusercontent.com/2194784/64550219-3e89b000-d2e7-11e9-8038-3edb02998ffc.png)

**Comment by ghost** [comment]
still an issue

**Comment by ghost** [comment]
This patch "fixes" the problem but I'm 99% sure it's not correct.

```diff
diff --git a/compiler/layouter.nim b/compiler/layouter.nim
index c603c16ff..6d45a84e8 100644
--- a/compiler/layouter.nim
+++ b/compiler/layouter.nim
@@ -513,10 +513,16 @@ proc emitTok*(em: var Emitter; L: Lexer; tok: Token) =
     if tok.strongSpaceA > 0 and not em.endsInWhite and
         (not em.wasExportMarker or tok.tokType == tkCurlyDotLe):
       wrSpace em
-    wr(em, $tok.tokType, ltSomeParLe)
-    rememberSplit(splitParLe)
+    if tok.tokType != tkCurlyDotLe:
+      wr(em, $tok.tokType, ltSomeParLe)
+      rememberSplit(splitParLe)
+    else:
+      wr(em, $tok.tokType, ltOther)
   of closedPars:
-    wr(em, $tok.tokType, ltSomeParRi)
+    if tok.tokType != tkCurlyDotRi:
+      wr(em, $tok.tokType, ltSomeParRi)
+    else:
+      wr(em, $tok.tokType, ltOther)
   of tkColonColon:
     wr(em, $tok.tokType, ltOther)
   of tkDot:
   ```

**Comment by narimiran** [comment]
> This patch "fixes" the problem but I'm 99% sure it's not correct.

What about just having this change:

```nim
    if tok.tokType != tkCurlyDotLe:
      rememberSplit(splitParLe)
```

This gives the following result for the original example:

```nim
proc hid_open*(vendor_id: cushort; product_id: cushort;
    serial_number: cstring): ptr HidDevice {.
    importc: "hid_open", dynlib: hidapi.}
```
