### ISSUE TITLE
Tuple field names have to match for assignment

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12151]
I am not sure if this is a bug or intended, but it was surprising for me:

```nim
type
  W = object
    i, j: int

  H = object
    #dim: tuple[x: int; y: int]
    dim: tuple[xx: int; yy: int]

proc `default=`*(w: var W; dim: tuple[x: int; y: int]) =
  w.i = dim[0]
  w.j = dim[1]

var w: W
var h: H

w.default =  h.dim

```

```
/tmp/hhh/t.nim(16, 11) Error: type mismatch: got <W, tuple[xx: int, yy: int]>
but expected one of: 
proc default=(w: var W; dim: tuple[x: int, y: int])
  first type mismatch at position: 2
  required type for dim: tuple[x: int, y: int]
  but expression 'h.dim' is of type: tuple[xx: int, yy: int]

expression: default=(w, h.dim)
```

Compiles fine when field names of tuple match with

```
  H = object
    dim: tuple[x: int; y: int]
    #dim: tuple[xx: int; yy: int]
```

**Comment by kaushalmodi** [comment]
That's by design.

See https://nim-lang.github.io/Nim/manual.html#types-tuples-and-object-types:

> Different tuple-types are equivalent if they specify the same fields of the same type in the same order. **The names of the fields also have to be identical**.

**Comment by kaushalmodi** [comment]
If you want to avoid the issue in the example, you might want to create a type defined as that tuple first and then use that type everywhere instead of using the raw tuple definition .. as shown in the manual in that same section:

```
type
  Person = tuple[name: string, age: int] # type representing a person:
                                         # a person consists of a name
                                         # and an age
```

**Comment by Clyybber** [comment]
Regardless of this issue, I think it would be nice to have a tuple without field names match a tuple with the same fields but named.

**Comment by StefanSalewski** [comment]
>The names of the fields also have to be identical.

Oh, I missed that, sorry. What may have confused me may be that using anonymous tuples works, like

```nim
type
  W = object
    i, j: int

  H = object
    #dim: tuple[x: int; y: int]
    dim: tuple[xx: int; yy: int]

proc `default=`*(w: var W; dim: tuple[x: int; y: int]) =
  w.i = dim[0]
  w.j = dim[1]

var w: W
var h: H

w.default = (1, 2)
w.default =  (h.dim[0], h.dim[1])
```

But as it is intended and explained in the manual I will close this issue.

**Comment by kaushalmodi** [comment]
Yes, if you assign an anonymous tuple to a named tuple, Nim auto-resolves the anon tuple type to the named.

As it turns out, I played quite a bit with anon tuples and named tuples in my notes: https://scripter.co/notes/nim/#tuple-type-equality

**Comment by mratsim** [comment]
I think a note in the manual saying that Nim tuples use structural typing unless when named might help.
