### ISSUE TITLE
Error not triggered based on static value

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#12171]
I have a section in [Emmy](https://github.com/unicredit/emmy) where I perform a manual static dispatch (using `when ...`) based on a static value. In one of the branches I explicitly output an error, in order to prevent it from being compiled. This works as a nice pattern to test arbitrary conditions know at compile time. In recent versions of Nim, the error path is not triggered, and compilation goes through without issues.

As a toy example, I would expect that `onlyTwo` below accepts arguments of type `Foo[2]` but not of type `Foo[3]`.

```nim
type Foo[N: static[int]] = distinct int

proc isTwo(n: int): bool =
  n == 2

proc onlyTwo[N: static[int]](a: Foo[N]): int =
  when isTwo(N):
    int(a)
  else:
    {.error: $(N) & " is not two".}

when isMainModule:
  let foo: Foo[3] = Foo[3](5)
  echo onlyTwo(foo)
```

Instead, the code above compiles and prints `0` (!?). One actual use case is to define the inverse in integers modulo a prime [here](https://github.com/unicredit/emmy/blob/master/emmy/integers_modulo.nim#L54-L62).

I am using Nim 0.20.99, git hash ee36931f26de138afd59a6497debee42567962c0

This pattern used to work until a few days ago.

**Comment by andreaferretti** [comment]
Great, that was quick! :-)

**Comment by Araq** [comment]
It also was embarrassing... ;-)
