### ISSUE TITLE
system.nim unsigned operators use different rules than signed operators

### ISSUE THREAD

**Issue by mp035** [nim-lang/Nim#12177]
When using basic operators (+,-,*,div) on integers of different lengths (eg uint16 and uint32), implicit conversion only works when the longest type is first.  It is expected that the order of operands on these operators should not affect the operation.  

### Example
```nim
var a:uint16 = 1
var b:uint32 = 2

echo(b+a) # works
echo(b-a) # works
echo(b*a) # works
echo(b div a) #works

echo (a+b) # Error: type mismatch: got <uint16, uint32>
echo (a-b) # Error: type mismatch: got <uint16, uint32>
echo (a*b) # Error: type mismatch: got <uint16, uint32>
echo (a div b) # Error: type mismatch: got <uint16, uint32>
```

### Current Output
```
/home/user/nim/main.nim(9, 8) Error: type mismatch: got <uint16, uint32>
but expected one of: 
proc `+`[T: SomeUnsignedInt](x, y: T): T
  first type mismatch at position: 2
  required type: T: SomeUnsignedInt
  but expression 'b' is of type: uint32
15 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: a + b
```

### Expected Output
```
3
1
2
2
3
4294967295
2
0
```

### Possible Solution
None yet found.  Workaround is to explicitly convert operands eg:
```
echo (uint32(a) + b)
```

### Additional Information
* Nim version (output of `nim -v`):
```
Nim Compiler Version 0.20.2 [Linux: amd64]
Compiled at 2019-07-17
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 88a0edba4b1a3d535b54336fd589746add54e937
active boot switches: -d:release
```
* Was it working in the previous Nim releases? No (0.19.6 had same behavior)
* A link to a related issue or discussion:
[https://forum.nim-lang.org/t/5185#32509](https://forum.nim-lang.org/t/5185#32509)

**Comment by TinBryn** [comment]
It looks like what is happening is that the first argument binds the type parameter, in the case where the larger uint is first this isn't a problem as implicit widening conversions are allowed.

Could this be solved by binding both arguments individually and then picking whichever can be converted to from the other and using that to call the {.magic.} proc?

I'll see if I can figure out how to do that.
