### ISSUE TITLE
`mapViewOfFileEx` of `winlean.nim` has wrong FFI declaration

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#12186]
### Current 
```nim
proc mapViewOfFileEx*(hFileMappingObject: Handle, dwDesiredAccess: DWORD,
                      dwFileOffsetHigh, dwFileOffsetLow: DWORD,
                      dwNumberOfBytesToMap: DWORD,
                      lpBaseAddress: pointer): pointer{.
    stdcall, dynlib: "kernel32", importc: "MapViewOfFileEx".}
```

`dwNumberOfBytesToMap` is assigned DWORD type. but according to [official doc](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffileex) it should be [`SIZE_T`](https://social.msdn.microsoft.com/Forums/vstudio/en-US/35ea7202-41df-4f93-894f-c98caacb1421/sizet-vs-sizet-and-where-to-see-equivalent-of-what-type-sizet-was-defined-as?forum=vclanguage).

`SIZE_T` is uint32 on 32-bit target and uint64 on 64-bit target.

It has trigger almost [heisenbug like bug](https://github.com/status-im/nim-beacon-chain/issues/435) and very difficult to probe.

I think the fix is easy, so I left  it for you to handle it.

**Comment by Araq** [comment]
> I think the fix is easy, so I left it for you to handle it.

Not sure I like this attitute :P

**Comment by jangko** [comment]
Sorry, it doesn't meant to offend of insult anyone. But yeah, the sentence is ambiguous and may lead to a wrong interpretation.
