### ISSUE TITLE
FreeBSD - tests/js/tconsole fails with different output

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12182]
This is a bit of a weird one. On FreeBSD, `tests/js/tconsole.nim` fails with the following:

```
Category: js
Name: tests/js/tconsole.nim JS -d:nodejs
Action: run
Result: reOutputsDiffer
-------- Expected -------
Hello, console
1 2 3
1 'hi' 1.1
--------- Given  --------
Hello, console
1 2 3
1 hi 1.1
-------------------------

Category: js
Name: tests/js/tconsole.nim JS -d:nodejs -d:release
Action: run
Result: reOutputsDiffer
-------- Expected -------
Hello, console
1 2 3
1 'hi' 1.1
--------- Given  --------
Hello, console
1 2 3
1 hi 1.1
-------------------------
```

Node is installed via `pkg install node` and reports the following version information: `v12.4.0`

**Comment by euantorano** [comment]
Just to test it out, I created a file `index.js`:

```js
console.log("Hello, console")
console.log(1, 2, 3)
console.log(1, "hi", 1.1)
```

And ran it with `node index.js`:

```
Hello, console
1 2 3
1 hi 1.1
```

I did the same on the Mac (Node v12.10.0) and got the exact same output, but the test doesn't seem to fail on the Mac CI...

**Comment by euantorano** [comment]
Looks like the change happened in Node v12. Thanks to @bnb for opening an issue in the Node repository and helping track this down.

- [Changelog](https://github.com/nodejs/node/pull/23162) - see `treat format arguments equally`
- [PR](https://github.com/nodejs/node/pull/23162)

The [AppVeyor script currently installs Node 8](https://github.com/nim-lang/Nim/blob/devel/appveyor.yml#L20).

The Travis script doesn't install Node specifically, as Node is installed as part of the build environment. Currently, [the `xenial` build environment installs both v11.0.0 and v8.12.0](https://docs.travis-ci.com/user/reference/xenial/#javascript-and-nodejs-support).

I've ignored the test on FreeBSD now, so this issue can be closed when the FreeBSD CI PR gets merged.

**Comment by stefantalpalaru** [comment]
I see the same test failures on Linux with Node.js 12.10.0.

**Comment by stefantalpalaru** [comment]
Why would you disable a test on FreeBSD when the output mismatch is also seen on Linux and it's due to a newer Node.js version?

**Comment by euantorano** [comment]
It was the easiest solution to the problem. We can always revisit it at a later date.
