### ISSUE TITLE
FreeBSD Boehm GC - could not import: GC_allow_register_threads

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12180]
Running tests on FreeBSD result in a number of errors like the following:

```
Category: dll
Name: tests/dll/client.nim C --gc:boehm --threads:on
Action: run
Result: reExitcodesDiffer
-------- Expected -------
exitcode: 0
--------- Given  --------
exitcode: 1

Output:
could not import: GC_allow_register_threads
-------------------------
```

Running `readelf -Ws /usr/local/lib/libgc.so.1 | grep GC_allow_register_threads` returns no results, so it looks like that function isn't exported for some reason...

`libgc` was installed using `pkg install boehm-gc`.

**Comment by euantorano** [comment]
I've started [a thread on the FreeBSD forums](https://forums.freebsd.org/threads/gc_allow_register_threads-missing-from-devel-boehm-gc.72312/), hoping somebody there can offer some insight.

**Comment by lbartoletti** [comment]
@euantorano is it ok with devel/boehm-gc-threaded  ?

**Comment by euantorano** [comment]
@lbartoletti Yep, see [the FreeBSD CI](https://github.com/nim-lang/Nim/blob/devel/.builds/freebsd.yml) script for a list of packages that get installed:

- databases/sqlite3 (for `db_sqlite` module)
- devel/boehm-gc-threaded (for boehm GC)
- devel/pcre (for `re` module)
