### ISSUE TITLE
FreeBSD & OpenBSD: tests/stdlib/tgetaddrinfo fails

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12181]
Running tests on **FreeBSD** results in the following failure:

```
Category: stdlib
Name: tests/stdlib/tgetaddrinfo.nim C
Action: run
Result: reExitcodesDiffer
-------- Expected -------
exitcode: 0
--------- Given  --------
exitcode: 1

Output:
tgetaddrinfo.nim(22)     tgetaddrinfo
nativesockets.nim(262)   getAddrInfo
oserr.nim(94)            raiseOSError
Error: unhandled exception: Additional info: "servname not supported for ai_socktype" [OSError]
-------------------------
```

_____________

Running tests on **OpenBSD** results in the following failure:

```
Category: stdlib
Name: tests/stdlib/tgetaddrinfo.nim C
Action: run
Result: reExitcodesDiffer
-------- Expected -------
exitcode: 0
--------- Given  --------
exitcode: 1

Output:
tgetaddrinfo.nim(22)     tgetaddrinfo
nativesockets.nim(262)   getAddrInfo
oserr.nim(94)            raiseOSError
Error: unhandled exception: Additional info: "service not supported for ai_socktype" [OSError]
-------------------------
```

**Comment by alaviss** [comment]
I guess this block is linux-only?

https://github.com/nim-lang/Nim/blob/13960066cbc376849288792bc20599396a03a0a9/tests/stdlib/tgetaddrinfo.nim#L18-L36

**Comment by euantorano** [comment]
I'm closing this issue after having looked at source for the `getaddrinfo()` function in FreeBSD, OpenBSD and NetBSD. It seems that they intentionally don't support this.

- [FreeBSD](https://github.com/freebsd/freebsd/blob/master/lib/libc/net/getaddrinfo.c#L436)
- [OpenBSD](https://github.com/openbsd/src/blob/486285b1cedeb25e1fa9d1483c57ea6d406996c7/lib/libc/asr/getaddrinfo_async.c#L168)
- [NetBSD](https://github.com/NetBSD/src/blob/trunk/lib/libc/net/getaddrinfo.c#L496)
