### ISSUE TITLE
Low priority: I think we really need odd() and even()

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12198]
It is really ugly to always write `if (i and 1) != 0:` as recently again in

https://github.com/StefanSalewski/gintro/blob/master/examples/gtk3/css_colored_listview.nim#L71

Or to use always `import salewski`.

And note, there is a trap, people may use `i mod 2` which may not generate optimal code when i is signed!

**Comment by awr1** [comment]
>And note, there is a trap, people may use `i mod 2` which may not generate optimal code when i is signed!

Do you have a source on this? Seems to me most optimizing compilers will just substitute it with the bitwise-and-1 trick; don't see how that would be affected by `i` being signed or not.

**Comment by StefanSalewski** [comment]
I assume you know that integer division by a power of two is only a plain shift for unsigned ints -- for signed ints the compiler may have to do an additional sign test. That is why for time critical code C programmers like to use unsigned data types.

Of course the compiler can skip this sign test when it can prove that operands are not negative. In a loop with fixed bounds that is possible. But when we write a proc odd() or even() with int argument and using mod 2 the compiler would need additional knowledge to skip the sign test. I assume Gcc and clang may have this knowledge now, but there are other C compilers too.

**Comment by awr1** [comment]
Agh, I'm stupid, I completely forgot about two's complement. Even so, I would have taken compilers for doing something like `if x >= 0: (x and 1) == 0 else: ((not x) and 1) == 0`: I am unaware of this "shift trick" (I imagine it probably avoids the branch cost?)

Speaking more in general, I like the idea of using term-rewriting macros or `static` params to optimize for these types of cases at compile time in lieu of adding new procs (for this issue specifically, Nim would know what change for something `x mod 2`). But I'm not quite sure if we're ready for the stdlib to have term-rewriters and dealing with static params anyway means that we need to make a new overloaded function anyway.

**Comment by StefanSalewski** [comment]
It is not really about performance -- I just would like to have odd() and even() available. It makes it easier to read the code. And there should be really no issue with name pollution.

**Comment by StefanSalewski** [comment]
For the performance -- thinking about it, you may be right. I think for i mod j when j is a literal constant and a positive power of two, most C compilers should generate a plain bit AND operation. Problem with signed ints is more about div instruction.

**Comment by bluenote10** [comment]
I'd call them `isEven` and `isOdd`.

**Comment by awr1** [comment]
I just thought about this again, does two's complement actually necessitate changing anything? Isn't bitwise-and-one good enough?

https://play.nim-lang.org/#ix=1XDa

**Comment by StefanSalewski** [comment]
>I just thought about this again,

It was not really my intent to discuss code gen -- the devs know code gen well, and they have to decide if we get odd() and even at all.

My comment was related to additional operations which signed integers may cause, you can check at https://www.godbolt.org/ yourself. When we have

```C
int mod2(int i) {
    return (i % 2);
}

uint mod2u(uint i) {
    return (i % 2);
}
``` 

we get

```
mod2(int):
  mov edx, edi
  shr edx, 31
  lea eax, [rdi+rdx]
  and eax, 1
  sub eax, edx
  ret
mod2u(unsigned int):
  mov eax, edi
  and eax, 1
  ret
```

You see, mod for signed ints may generate additional operatins, a plain shift may not be sufficient as number can be negative. But indeed I think most compilers are smart enough so `i mod 2 == 0` should be fine.

**Comment by awr1** [comment]
The reason the first function generates more code is because negative mod positive gets you a negative (or zero), and you ask for an int back, not a bool.

Change the return value to a bool and you start getting the same machine code in spite of whether the input is signed or not:

```nim
bool mod2(int i) {
    return (i % 2) == 0;
}

bool mod2u(unsigned int i) {
    return (i % 2) == 0;
}
```

```asm
        push    rbp
        mov     rbp, rsp
        mov     DWORD PTR [rbp-4], edi
        mov     eax, DWORD PTR [rbp-4]
        and     eax, 1
        test    eax, eax
        sete    al
        pop     rbp
        ret
```

**Comment by StefanSalewski** [comment]
Closed as not really that important.

**Comment by al6x** [comment]
Still wonder why there's no isodd/even in nim. Pretty much every language has it.
