### ISSUE TITLE
Floating point and arrays

### ISSUE THREAD

**Issue by ArtificialLifeforms** [nim-lang/Nim#12194]
There is a problem similar to a problem python has with floating point. So, it is kind of a cool language, I like the ideas. It is like Pascal, yet also C and Python. It is refreshng and you take a swig of coffee. This day, well I think there is alot to admire about Nim. But, working with dynamic arrays. While I agree about the fine prints, I think it is helpful and not a bug but just a strange problem in why Nim and Python both interpret that algorithm the same way.

**Comment by bluenote10** [comment]
What "strange problem" or "that algorithm" are you referring to?

**Comment by krux02** [comment]
What?!

**Comment by ArtificialLifeforms** [comment]
Well, it is a very interesting language. Oh, well I am studying an algorithm, the ADALINE. It is an elementary artificial neural network. Now, I just am wondering, why the algorithm behaves deterministic in C and Pascal. Yet, when I code it in Python and NIm, it is non-deterministic. I think Nim is cool though, but I am not really sure what it is. It is like Pascal, and Python. Yet, what in the world is it doing? Arrays, they are not really encouraged in the documents. There is only scarce knowledge of seq and why, can I not translate an array I typed like a list [[1,2],[3,4]] to my seq[TYPE]. This is a pretty intense language, so I am only just doing elementary algorithm, without any kind of macro or any of the strange things I have seen the manual hint at, with no idea what at this time it even means.

**Comment by SolitudeSF** [comment]
is this a bot?

**Comment by mratsim** [comment]
Looking into the commit history it seems like a neural network bot trained to create:

- commits: https://github.com/ArtificialLifeforms/DeepSynthesis-Synthesizer-as-a-computable-function/commits/master
- README's: https://github.com/ArtificialLifeforms/neuralLOGIC/commit/7af4472feba0213d543d918cf147bd90a407b29e
- repos: https://github.com/ArtificialLifeforms/neuralLOGIC

**Comment by algorithmLOGIC** [comment]
I am not a bot. I have discovered the problem. It has something to do with initializing the weights randomly. If you are interested, the codes are in my repo. When I fix the weights to 1.0 in python and Nim, it works.

**Comment by b3liever** [comment]
Hi @algorithmLOGIC, and welcome to nim, can you provide an example of the problem you are describing? That would help us understand what you mean and help.

@mratsim when you have a hammer, everything looks like a nail :P
