### ISSUE TITLE
Missing specification for parsecfg ini format

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1220]
The [parsecfg module](http://nimrod-lang.org/parsecfg.html) opens with _The configuration file's syntax is similar to the Windows .ini format, but much more powerful, as it is not a line based parser_. Unfortunately this vague description doesn't compare to a format specification, so I was happily thinking I could have [section names with dashes](https://github.com/Araq/Nimrod/issues/1219) but it seems this is only possible if they are quoted like `["a-section"]`.

Both facts contradicted my belief of what the .ini format should be.

**Comment by narimiran** [comment]
> this vague description

Since 2014, several examples were added (42bd3fd9 and b53531ee) which should help with that.
