### ISSUE TITLE
ptr/ref/var typedesc crash

### ISSUE THREAD

**Issue by dumjyl** [nim-lang/Nim#12229]
### Example
```nim
proc foo(T: typedesc) = discard
foo(ref) # ptr | var
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

crash here:
https://github.com/nim-lang/Nim/blob/39185b46ca285ee9ca40d09331cea73056f524ca/compiler/sighashes.nim#L175

**Comment by narimiran** [comment]
It doesn't crash anymore on Nim devel 1.1.1, it produces:
```
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

**Comment by narimiran** [comment]
This works on Nim 1.5.
