### ISSUE TITLE
Regression in JS backend: invalid symbol generated

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#12246]
While testing [Rect.nim](https://github.com/andreaferretti/react.nim) for Nim 1.0, I found a regression in the generated JS. Namely, running `nimble example` in the linked repository generates a file `example/app.js` that contains the following at line 1235:

```js
		function HEX3Aanonymous_261801() {
			var result_261804 = null;

			BeforeRet: do {
				result_261804 = get_initial_state_259837(this`gensym258457.props);
				break BeforeRet;
			} while (false);

			return result_261804;

		}
```

The invalid symbol is 

```
this`gensym258457
```

and it is not parsed correctly by javascript engines. If we change that line to

```js
result_261804 = get_initial_state_259837(this.props);
```

the example app works as expected.

**Comment by Araq** [comment]
Permanent workaround:

```nim

  when compiles(getInitialState(c.props)):
    d.getInitialState = proc(): auto =
      var this {.importc: "this", nodecl.}: C
      return getInitialState(this.props)
```

**Comment by bluenote10** [comment]
Doesn't Nim's [`jsffi.bindMethod`](https://github.com/nim-lang/Nim/blob/f7a8fc46c0012033917582eb740dc0343c093e35/lib/js/jsffi.nim#L501) suffer from this problem as well?

**Comment by Araq** [comment]
Thanks, good point.

**Comment by andreaferretti** [comment]
@Araq Thank you, I had somehow missed your reply!
