### ISSUE TITLE
[regression] httpClient hangs

### ISSUE THREAD

**Issue by hendi** [nim-lang/Nim#12245]
After upgrading to 1.0.0 I'm having issues with httpClient. Simple GET and POST calls don't work anymore:

### Example

```nim
import httpClient
var client = newHttpClient()
echo client.getContent("http://example.com")
```

Compile and run with `nim c -d:ssl --threads:on foo.nim && ./foo`

### Current Output
Hangs, Ctrl-C gives:
```
/home/hendi/Projects/uplol-client/test.nim(3) test
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(960) getContent
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(955) get
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(931) request
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(906) request
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(891) requestAux
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(770) parseResponse
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(696) parseBody
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/httpclient.nim(604) recvFull
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/net.nim(1179) recv
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/net.nim(1155) recv
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/net.nim(1034) recv
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/net.nim(1021) readIntoBuf
/home/hendi/.choosenim/toolchains/nim-1.0.0/lib/pure/net.nim(1017) uniRecv
SIGINT: Interrupted by Ctrl-C.
```

### Expected Output
Works with 0.20.2

**Comment by narimiran** [comment]
What is the output of `nim -v`, specifically `git has`?

**Comment by narimiran** [comment]
What I'm aiming at is: the *officially* released version (the latest commit is https://github.com/nim-lang/Nim/commit/f7a8fc46c0012033917582eb740dc0343c093e35), not the one you might have picked up from GitHub yesterday afternoon (commit https://github.com/nim-lang/Nim/commit/5b43c98897ee7eb9f8ded8ceb7623f6caa23bace) works correctly, without hangs.

If you're using a https://github.com/nim-lang/Nim/commit/5b43c98897ee7eb9f8ded8ceb7623f6caa23bace version, it will hang.

**Comment by hendi** [comment]
That's strange, I updating using `choosenim` today, but got this:

```
hendi@x210:~/Projects/uplol-client$ choosenim 1.0.0
   Switched to Nim 1.0.0

hendi@x210:~/Projects/uplol-client$ nim -v
Nim Compiler Version 1.0.0 [Linux: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 5b43c98897ee7eb9f8ded8ceb7623f6caa23bace
active boot switches: -d:release
```

**Comment by dom96** [comment]
@hendi it looks like you have updated while a broken tarball was made available (the `stable` channel should have been reverted to pre-1.0.0 when this was discovered to prevent this, but alas...). Anyway, what you need to do to fix this is modify some choosenim files, you can just ``rm -r ~/.choosenim`` if you don't mind losing any older versions you may have and then run ``choosenim stable`` should get you the correct hash. If you don't want to rm that whole directory then you'll need to surgically remove v1 from inside that folder and change some files in there (if you look around you should be able to figure it out).

**Comment by hendi** [comment]
Thanks, I'm on the correct 1.0.0 now.

Good to hear that it was only broken for a short time and has been fixed already!

**Comment by MatthewScholefield** [comment]
Just mentioning in case anyone else gets here from a search result, in my case it hung because I was using an `httpClient` for a second request rather than creating a fresh one.
