### ISSUE TITLE
Make compile and --run default parameters for nim

### ISSUE THREAD

**Issue by filipux** [nim-lang/Nim#12248]
### Problem
Today you always have to provide the c parameter to compile a nim file but that seems like an unnecessary step. You almost always want to compile. For beginners every extra step like this can be a big hurdle.

### Proposed solution
I propose that running "nim mycode.nim" should compile the passed file and then run the built executable, i.e. making both c and --run default parameters for Nim. This would lower the bar for beginners and approach the usability of Node from the JavaScript world.

**Comment by alehander42** [comment]
notice that we have multiple backends

**Comment by alehander42** [comment]
(otherwise it sounds good to me as well as a default action)

**Comment by andreaferretti** [comment]
I don't know, it may lead to beginners keep recompiling the same program over and over in order to execute it without realizing that an executable was generated.

**Comment by juancarlospaco** [comment]
- [Binaries can now be built and run using the new run command.](https://github.com/nim-lang/nimble/blob/master/changelog.markdown#0110---22092019) (Built-in)
- [Another option to do the same.](https://github.com/kaushalmodi/nim_config#list-available-tasks) (Community)

**Comment by awr1** [comment]
This sounds like a potential security issue to me, honestly.

**Comment by awr1** [comment]
Also this would probably break tests and require a pretty hefty source change for what would be effectively a minor convenience

**Comment by Araq** [comment]
> I don't know, it may lead to beginners keep recompiling the same program over and over in order to execute it without realizing that an executable was generated.

We already cache it. Nothing is recompiled really when you do multiple ``nim c -r foo.nim`` commands.

**Comment by Araq** [comment]
How about we ship a simple script/program called ``nime`` (or similar) to do that?

**Comment by SolitudeSF** [comment]
> For beginners every extra step like this can be a big hurdle.
how is typing `c -r` even an issue?

**Comment by kaushalmodi** [comment]
> How about we ship a simple script/program called nime (or similar) to do that?

Why not just add `runc`, `runcpp`, etc targets in a default `config.nims` shipped by Nim? I do that in my config ([ref][1]).

[1]: https://github.com/kaushalmodi/nim_config

**Comment by alehander42** [comment]
I think the OP's point is misunderstood : `runc` etc don't really help, as it's about new user expecations: many languages run files when you type `lang <file>`

Otherwise those commands are useful @kaushalmodi, i have to add them to my config!

**Comment by filipux** [comment]
I do believe a solution like this would make Nim more user-friendly for beginners, but it seems like it would go against the expectations of more experienced developers.
