### ISSUE TITLE
"undeclared identifier: 'setCommand'" in nimscript

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12253]
```nim
setCommand "js"
```
> undeclared identifier: 'setCommand'

The error is shown both in the editor and when running the .nims file... but it actually does what it's supposed to when compiling the .nim file itself.

Nim Compiler Version 1.0.0 [Windows: amd64]

https://nim-lang.org/docs/nimscript.html#setCommand%2Cstring%2Cstring

**Comment by Araq** [comment]
You cannot "run" a Nimscript file, it's a configuration file, it gets picked up when you compile a .nim file.
