### ISSUE TITLE
Document all -d:flags of compiler

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12250]
- Document all `-d:flags` of the Nim compiler [on the Manual.](https://nim-lang.github.io/Nim/nimc.html#additional-compilation-switches) 

Some are mentioned on [the Manual](https://nim-lang.github.io/Nim/nimc.html#additional-compilation-switches), but is not complete, needs descriptions and info:

- `-d:quick` :arrow_right: ???, still works?, is Deprecated?, not documented.
- `-d:useStdoutAsStdmsg` :arrow_right: Use Std Out as Std Msg?, This is for Windows or Linux?, not documented on manual.
- `-d:nimOldShiftRight`  :arrow_right: http://forum.nim-lang.org/t/4891#30600 ?, but not documented on manual.
- `-d:nimOldCaseObjects`  :arrow_right: Old case switch?, still works?, not documented.
- I am missing some flag?.

Should be easy, I dont send PR because I am not sure of all of them. 
:slightly_smiling_face:

**Comment by Araq** [comment]
Covered here: https://nim-lang.org/docs/nimc.html#additional-compilation-switches

But probably miss a few.

**Comment by juancarlospaco** [comment]
You are right, is covered there, but few are missing, mostly new ones, I mentioned the ones I found.
:slightly_smiling_face:

**Comment by zevv** [comment]
I can pick this up, but I could need some hints how to approach this. The list of all defines checked for in code is quite extensive: [list.txt](https://github.com/nim-lang/Nim/files/3667975/list.txt). How do we know which are relevant, which are obsolete, which are essential?

**Comment by Araq** [comment]
What's the point in documenting them? Most are implementation details. The "nimc" document covers what should be covered.

**Comment by andreaferretti** [comment]
Because people may read about these options and be confused about their use. Even documenting them as "do not use" would be useful

**Comment by Araq** [comment]
Being confused when reading Nim's implementation doesn't mean the official documentation should mention it. By the same logic we could document ``c: PContext`` in the nimc document. Makes no sense. If you want to clean up the implementation and add documentation to it, be my guest but neither nimc.rst nor manual.rst are the right places.
