### ISSUE TITLE
Low priority compiler crash when calling `high` in arg list

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12252]
```nim
proc foo(a = 0, b = a.high) = discard
foo()
```

> (1, 22) Error: internal error: genArrayLen()
> No stack traceback available
> To create a stacktrace, rerun compilation with ./koch temp c <file>

**Comment by ghost** [comment]
This now works for both a.high (which is deprecated) and typeof(a).high, should we add a test case for this or not?
```nim
proc foo(a = 0, b = a.high, c = high(typeof(a))) = 
  discard

foo()
```
