### ISSUE TITLE
[JS] `reset` sets value types to null

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12256]
```nim
var x: bool

{.emit: ["console.log(", x, ")"].}

reset x

{.emit: ["console.log(", x, ")"].}
```
Console log:
> false
> null

Stable 1.0

**Comment by alaviss** [comment]
You can use `echo`, it's mapped to `console.log` afact

**Comment by dawkot** [comment]
> You can use `echo`, it's mapped to `console.log` afact

I did, but echo insisted that both values are false ;)

**Comment by dawkot** [comment]
I think this should be high priority because it can be very hard to detect if one doesn't know about the backend details...

**Comment by Clyybber** [comment]
Is these even a problem in practice?
When null is treated like false it shoulnt matter.

**Comment by dawkot** [comment]
> When null is treated like false it shoulnt matter.

It isn't

```nim
var x: bool
echo "before: ", x == false

reset x
echo "after: ", x == false

echo "(just to be sure) ", x == true
```

## Output:

> before: true
> after: false
> (just to be sure) false
