### ISSUE TITLE
a symbol redefinition bug

### ISSUE THREAD

**Issue by yuchunzhou** [nim-lang/Nim#12269]
code like this:
```
var access_token = new(Token) # line 38

proc accessToken(): string = discard # line 40
```
the compiler will throw this error when the code compiled:
```
xxx.nim(40, 6) Error: redefinition of 'accessToken'; previous declaration here:xxxx.nim(38, 5)
```
the nim version is 1.0.0

**Comment by trustable-code** [comment]
You have to choose another name, identifiers in Nim are style-insensitive, that means camelCase and snake_case is the same for the compiler.
https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality
Issue can be closed.
