### ISSUE TITLE
Documentation of PCRE is wrong

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12278]
https://nim-lang.org/docs/pcre.html Documentation literally says:

> Exec-time and get/set-time error codesSpecific error codes for UTF-8 validity checksSpecific error codes for UTF-16 validity checksSpecific error codes for UTF-32 validity checksRequest types for pcre_fullinfo()Request types for pcre_config(). Do not re-arrange, in order to remain compatible.Request types for pcre_study(). Do not re-arrange, in order to remain compatible.Bit flags for the pcre[16|32]_extra structure. Do not re-arrange or redefine these bits, just add new ones on the end, in order to remain compatible.TypesThe structure for passing additional data to pcre_exec(). This is defined in such as way as to be extensible. Always add new fields at the end, in order to remain compatible.The structure for passing out data via the pcre_callout_function. We use a structure so that new fields can be added on the end in future versions, without changing the API of the function, thereby allowing old clients to work without modification.User defined callback which provides a stack just before the match starts.

I think is a bug on the Documentation comments.
:thinking:

**Comment by Araq** [comment]
Where is the bug in that?

**Comment by juancarlospaco** [comment]
That the text do not make any sense, then is not really documenting anything whatsoever.
Looks like random documentation comments got all concatenated on the top for some reason.
:slightly_smiling_face:

**Comment by narimiran** [comment]
I'll fix it.

**Comment by juancarlospaco** [comment]
Thanks @narimiran , @Araq :+1:
