### ISSUE TITLE
Documentation missing from TheIndex

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12280]
https://nim-lang.org/docs/theindex.html is missing the following Standard Library modules:

- openssl
- iup
- posix
- pcre
- jscore
- segfaults

But they do exist and are listed and linked here: https://nim-lang.org/docs/lib.html
Documentation bug :grey_question: I found it searching TheIndex for `posix` and checked 1-by-1.
:thinking:

**Comment by Araq** [comment]
Not a bug, theindex shouldn't be bloated with long wrapper identifiers.

**Comment by juancarlospaco** [comment]
I was thinking `posix` was high level enought to be there at least. :+1:

**Comment by FedericoCeratto** [comment]
At least theindex.html should warn about the unlisted modules e.g. "The following modules are not listed: <link> <link>"
