### ISSUE TITLE
Boehm disables interior pointer checking

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#12286]
Using an issue to track this investigation.

In January, [this](https://github.com/nim-lang/Nim/commit/06e3d3ab4dea4aa11a1728c849799ce6aeecb3a4) commit disabled interior pointer checking for boehm GC for performance reasons. cc @rbehrends @Araq

Since that commit, my text editor [feud](https://github.com/genotrance/feud) no longer works. Before (0.19.6) or without that commit (tested with 1.0), everything works just fine.

Feud creates DLLs using `--app:lib` for multiple plugins and loads them in the main executable. These plugins implement the bulk of the functionality and are used in the main thread. All this loading and dispatch happens in [plugin.nim](https://github.com/genotrance/feud/blob/araq/src/plugin.nim).

Each plugin has a [Plugin](https://github.com/genotrance/feud/blob/araq/src/globals.nim#L14) object that is [created](https://github.com/genotrance/feud/blob/araq/src/plugin.nim#L274) in the main executable. Once the DLL is [loaded](https://github.com/genotrance/feud/blob/araq/src/plugin.nim#L303), the required [onLoad](https://github.com/genotrance/feud/blob/araq/src/pluginapi.nim#L76) proc is called.

In order to know which callbacks are exported by the plugins, each plugin [creates](https://github.com/genotrance/feud/blob/araq/src/pluginapi.nim#L62) a seq of string names at compile time. This is then assigned to `plg.cindex` in the [onLoad](https://github.com/genotrance/feud/blob/araq/src/pluginapi.nim#L78) call.

After onLoad, each callback in `plg.cindex` is [loaded](https://github.com/genotrance/feud/blob/araq/src/plugin.nim#L260) in `plg.callbacks` which is defined [here](https://github.com/genotrance/feud/blob/araq/src/globals.nim#L30).

It is this `plg.callbacks` table of procs that gets cleaned out by boehm after load and when any of these callbacks are [called](https://github.com/genotrance/feud/blob/araq/src/plugin.nim#L429), it fails since that callback no longer exists in the table.

I don't see how this has anything to do with interior pointers but am open to feedback.

**Comment by genotrance** [comment]
I did try the GC_ALL_INTERIOR_POINTERS env var but it does not seem to work for me on Windows.

More importantly, it is totally not clear why we need interior pointer checking since the code does not do any such thing explicitly.

**Comment by rbehrends** [comment]
This is odd, to say the least. There are a couple of things that may happen here in theory, though I consider them to be unlikely.

Enabling all interior pointers adds a byte of padding to all allocations to ensure that pointers to the ends of objects also keep them alive. If the object size is already a multiple of the word size, this adds another word of padding, which is also scanned by the GC. So, if you store a pointer one word past the end of an array, say, this would be scanned with all interior pointers on, but not with all interior pointers off and you might lose memory. But that would also mean that it should normally fail during bounds checking, unless this is done from C code or with bounds checking disabled.

Another theoretical problem might be that there is an issue with the roots of DLLs not being properly scanned and the object being accidentally kept alive by a pointer to the interior of the object in some other location.

The whole situation looks pretty strange.

**Comment by Araq** [comment]
Too bad, I'm also out of ideas. Need a debugger session I guess.

**Comment by genotrance** [comment]
Thanks to @disruptek, was able to recreate this issue on Linux and fix the same way by re-enabling interior pointer checking.

**Comment by genotrance** [comment]
Is such a fix good enough? I think interior pointer checking should only be disabled when people know what they are doing. Until we understand this issue, and I don't think anyone does right now, it should be enabled for everyone.

```nim
  when defined(boehmNoIntPtr):                                                                                                                                     
    boehmGC_set_all_interior_pointers(0)
```

Alternative is to comment it out and when a real understanding emerges, we can add the above code or the opposite as appropriate.

Ideally this goes into 1.0.2...

**Comment by Araq** [comment]
Yep, PR please.
