### ISSUE TITLE
system.Inf displayed wrong in documentation

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12287]
https://nim-lang.github.io/Nim/system.html#Inf

Inf = 0x0000000000000000'f64

**Comment by ridho9** [comment]
Is it okay for me to take this issue?

**Comment by narimiran** [comment]
> Is it okay for me to take this issue?

Of course!

**Comment by ridho9** [comment]
The problem part is at https://github.com/nim-lang/Nim/blob/ed1d41c51e5b3772fdea9e08733dbf46dfb4428e/compiler/renderer.nim#L328

But after I check that line was made by https://github.com/nim-lang/Nim/commit/69658ad396424e2b184e669e3835835a53a34775 to close issue #11131. Removing the line generates the correct documentation but makes the issue back.

**Comment by ridho9** [comment]
This should be closed

**Comment by narimiran** [comment]
> This should be closed

Yep, fixed by #12343.
