### ISSUE TITLE
Unknown compiler option "--platform:x86" for vcc

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#12297]
The nim compiler add an unknown compiler option "--platform:x86" for x86. 

### Example

```nim
echo "Hello World!"
```

### Current Output
```
> nim c hello
D:\Tool\Nim\tmp>nd hello
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: hello.nim
cl: command line warning D9002 :ignore unknown option“--platform:x86”
```

### Additional Information

```
OS: win10
32bit nim
c compiler: vc2008, vc2013, vc2017

D:\Tool\Nim\tmp>nim -v
Nim Compiler Version 1.0.0 [Windows: i386]
Compiled at 2019-09-28
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by demotomohiro** [comment]
I tested Nim-1.0.0 32bit on windows 8.1 but I didn't get such warning from `cl.exe`.

You need to add `--cc:vcc` option to command line or nim.cfg file to make Nim use vcc.
How did you changed nim.cfg or *.nims file to use vcc?

If you compile `hello.nim` with `--listcmd` option like this show how Nim call vccexe.exe.
```
nim c --listcmd hello.nim
```

Nim compiler doesn't call `cl.exe` directly but call `vccexe.exe` when you use `--cc:vcc` options.
Nim compiler call `vccexe.exe` with `--platform:x86` option and options that are passed to `cl.exe`.
`vccexe.exe` should pass given options to `cl.exe` except `--platform:x86`.

**Comment by slangmgh** [comment]
Yes, you are right. I don't use vcc.exe, I always setup the PATH myself.
I can setup a custom compiler to use msvc.

**Comment by slangmgh** [comment]
Compile speed using vccexe.exe is much slow than using plain "cl.exe".
Using vccexe.exe:
```nim
Hint: operation successful (144159 lines compiled; 8.631 sec total; 146.035MiB peakmem; Release Build) [SuccessX]
```

Using cl.exe:
```nim
Hint: operation successful (144131 lines compiled; 4.186 sec total; 145.824MiB peakmem; Release Build) [SuccessX]
```
