### ISSUE TITLE
why multi-thread slower than single-thread?

### ISSUE THREAD

**Issue by duyafeng** [nim-lang/Nim#12301]
why multi-thread slower than single-thread?

### test code . (run on macbook pro)

```nim
import times

var
  thr: array[0..10, Thread[int]]

proc f(num: int) {.thread.} =
  var k = 0
  for i in 0..num:
    inc(k)

let s = cpuTime()
for i in 0..high(thr):
  createThread(thr[i], f, 1_000_000_000)
joinThreads(thr)
echo "multi-thread cost:", cpuTime() - s

let k = cpuTime()

for i in 0..len(thr):
  f(1_000_000_000)
echo "single-thread cost:",cpuTime() - k
```

```
$ nim -v
Nim Compiler Version 1.0.0
$ nim c -d:release --threads:on test.nim
```

### output
```
multi-thread cost:20.567741
single-thread cost:0.1992869999999982
```

why multi-thread is so slowly than single thread?

@dom96 @Araq

**Comment by mikra01** [comment]
look at your code. the payload is the same for each thread. so each thread is counting up to 1_000_000_000. In almost the same time - that's about 5 times faster, isn't it? :-) - If you like to split your payload into chunks use modulo or something else..

**Comment by duyafeng** [comment]
> Hi just looked at your code. the payload is the same for each thread. so each thread is counting up to 1_000_000_000. In almost the same time - that's about 5 times faster, isn't it? :-) - If you like to split your payload into chunks use modulo or something else..

single thread: 64047000 ns
multi   thead:  633907000 ns
single thread is faster than multi thread

**Comment by mikra01** [comment]
oh sorry - missed a digit. Well now possibly you have contention. That is machine dependent. Are 5 physical threads possible on your machine? And look at your example code: your threaded example spawns 5times more workload...

**Comment by duyafeng** [comment]
> oh sorry - missed a digit. Well now possibly you have contention. That is machine dependent. Are 5 physical threads possible on your machine? And look at your example code: your threaded example spawns 5times more workload...

my computer is 8 core, is there a bug?

**Comment by mikra01** [comment]
I tried your code now. Better to use epochTime() for measurements. Do you have a linux box? on my win10 dualcore the multithreaded code runs about 1 time faster (regardless of the workload).. (I used --d:release flag)

**Comment by mratsim** [comment]
Don't use cpuTime to measure time in multithreaded application. Use the wall time (epochTime) otherwise.

**Comment by duyafeng** [comment]
> Don't use cpuTime to measure time in multithreaded application. Use the wall time (epochTime function).

but why multi-thread is slowly? I feel slowly so much from stdout

**Comment by mratsim** [comment]
> > Don't use cpuTime to measure time in multithreaded application. Use the wall time (epochTime function).
> 
> but why multi-thread is slowly? I feel slowly so much from stdout

Your work is:
  - Trivial, so the time is dominated by creating threads.
    CPUs are in the 3Ghz range, 1 billion increment takes ~300 ms at most, and if you are on personal machine, plenty of other processes (like your web browser) can induce a huge variation in timing.
  - The single threaded version  might even be instant because GCC sees that the increment has no effect so it removes it from the code.

**Comment by Araq** [comment]
No bug here.

**Comment by mikra01** [comment]
@mratsim related to cpuTime() the doc (https://nim-lang.org/docs/times.html#cpuTime) states : "This may be more useful for benchmarking than epochTime.". sounds a little bit misleading to me..

**Comment by mratsim** [comment]
if you run the unix `time` command on a multithreaded application you will see for example this:

```
real    0m2.856s
user    0m28.687s
sys     0m3.989s
```

real is wall-clock / epochTime
user is cpuTime. But if each CPU run 2 seconds, I get 2 x num_cpus.

cpuTime is monotonic, it will not get influenced by your OS unscheduling you for a higher priority process or any random thing that can impact your running time. But it's also not reliable in a multithreaded context because all your CPUs elpased time in your program increment the time.
