### ISSUE TITLE
small nimCopy jsgen bug: field is not copied to

### ISSUE THREAD

**Issue by alehander92** [nim-lang/Nim#12303]
Small jsgen bug: field is not copied to

### Example
```nim
import jsconsole, jsffi

type
  A = ref object
   b: B

  B = object
    b: int

var a = cast[A](js{})
a.b = B(b: 2)
console.log a.b
```

### Current Output
```
undefined
```

### Expected Output
```
{b: 2}
```

### Possible Solution

a small PR for jsgen with one line fix coming

**Comment by ringabout** [comment]
I think `cast` object may not be allowed in JS backend.
