### ISSUE TITLE
[Windows] finish.exe C:\Users\<USERNAME>\.nimble\bin is not in your PATH environment variable.

### ISSUE THREAD

**Issue by SoftwareApe** [nim-lang/Nim#12319]
When you run finish.exe twice you get (I decided I wanted the start menu entry after the fact)
`C:\Users\<USERNAME>\.nimble\bin is not in your PATH environment variable.`

This was an installation without admin rights. The variable is placed correctly in the user path without requiring (unnecessary) admin permissions.

### Example
Run finish.exe twice without admin privileges on Windows 10

### Current Output
See above

### Expected Output
1. Recognize the current path correctly.
2. Recognize it's already on the path.

### Possible Solution
Not sure where the installer comes from.

### Additional Information
* Your Nim version (output of `nim -v`).
```bash
Nim Compiler Version 1.0.0 [Windows: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f7a8fc46c0012033917582eb740dc0343c093e35
active boot switches: -d:release
```
* Was it working in the previous Nim releases?
Not sure (first time install)
* A link to a related issue or discussion.
Couldn't find one
* A project reference where (and how) the issue causes problems.
It's not a huge issue for me. Just a small issue since I didn't want it on my path twice.

**Comment by me7** [comment]
I've submit #12408 to fix the problem.
Test run on my windows machine and working ok.
Feel free to review and close the issue :)
