### ISSUE TITLE
Koch tools fails on OpenBSD with the 1.0.0 package

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#12320]
Running `koch tools` on openBSD using the 1.0.0 release package from the website fails with the following error:

```
/home/euant/src/nim-1.0.0/dist/nimble/src/nimble.nim(7, 20) Error: cannot open file: std/options
FAILURE
```

Steps to reproduce:

```
mkdir -p ~/src
cd ~/src
ftp https://nim-lang.org/download/nim-1.0.0.tar.xz
xz -d nim-1.0.0.tar.xz
tar -xf nim-1.0.0.tar
rm nim-1.0.0.tar
cd nim-1.0.0
env CC=/usr/bin/clang sh build.sh
bin/nim c --cc:clang koch
./koch tools --cc:clang
```

Note that these same steps worked with the 0.20.2 package, which I'm using for CI [here](https://github.com/euantorano/pledge.nim/blob/master/.builds/openbsd.yml).

This seems similar to #12139 which is a similar failure opening a standard library file.

**Comment by asiekierka** [comment]
It appears to me that this now works in 1.0.4. Can this issue be closed?
