### ISSUE TITLE
Facebook webpage

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#12322]
Hello. It is not an issue. I am from Turkey and I want to introduce nim in Turkish with facebook page. If you don't mind I want to create Nim Programing Turkey(in Turkish Nim Programlama Türkiye). Do you mind?
I need to use nim language logo.
https://www.facebook.com/Nim-Programlama-T%C3%BCrkiye-104452144296523/?modal=admin_todo_tour

**Comment by narimiran** [comment]
Yes, it is ok to create such page.

You might want to add, at some appropriate field, that it is an unofficial page.

**Comment by Araq** [comment]
Ok, go for it, thanks!
 

Gesendet: Dienstag, 01. Oktober 2019 um 12:11 Uhr
Von: "Mustafa Selçuk Çağlar" <notifications@github.com>
An: nim-lang/Nim <Nim@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [nim-lang/Nim] Facebook webpage (#12322)


Hello. It is not an issue. I am from Turkey and I want to introduce nim in Turkish with facebook page. If you don't mind I want to create Nim Programing Turkey(in Turkish Nim Programlama Türkiye). Do you mind?
I need to use nim language logo.
https://www.facebook.com/Nim-Programlama-T%C3%BCrkiye-104452144296523/?modal=admin_todo_tour
