### ISSUE TITLE
regression: Error: Locks requires --threads:on option

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12330]
D20191001T210000
/cc @rayman22201 https://github.com/nim-lang/Nim/pull/12231 introduced a regression, making some projects not compile anymore; eg any project depending on nimongo 

### Example
nim c -r main.nim
```nim
# main.nim
import pkg/nimongo/mongo
```

### Current Output
```
core/locks.nim(14, 10) Error: Locks requires --threads:on option.
```
(unlike what's mentioned in https://github.com/nim-lang/Nim/pull/12231 there is not necessarily a link error)

### Expected Output
should compile and run

### Additional Information
this is a regression introduced in https://github.com/nim-lang/Nim/pull/12231

note that forcing user to add `--threads:on` is not an option, it causes other errors when adding that flag (eg in jester routes that work without `--threads:on`) that are really hard to fix

* Your Nim version (output of `nim -v`).

Nim Compiler Version 1.0.99 [MacOSX: amd64]
Compiled at 2019-10-02
Copyright (c) 2006-2019 by Andreas Rumpf
git hash: c20778d2d3faa1ad1e9b11a54899b5eef5ac6bca

* Was it working in the previous Nim releases?
yes

## note
would be nice to add nimongo to the set of tested packages in testsuite to prevent such future regressions

**Comment by rayman22201** [comment]
Nimmongo is obviously relying on broken behavior. Locks require threads. This means my linker bug has now been reintroduced in #12331
😕

**Comment by rayman22201** [comment]
I might propose making an RFC with a transition period and compiler warning. Then make a breaking change to reintroduce the compiler error.

**Comment by rayman22201** [comment]
> note that forcing user to add --threads:on is not an option, it causes other errors when adding that flag (eg in jester routes that work without --threads:on) that are really hard to fix

@timotheecour can you elaborate more on this? What you are describing sounds more like a jester bug than a Nim bug?

**Comment by timotheecour** [comment]
> Nimmongo is completely bypassing the standard idiomatic nim way of turning on threads in Nim, and instead essentially forcing pthreads to be included directly on linux

@rayman22201 maybe (so we don't forget) could you please create an issue in https://github.com/SSPkrolik/nimongo/issues to track this? /cc @SSPkrolik

> @timotheecour can you elaborate more on this? What you are describing sounds more like a jester bug than a Nim bug?

I will follow up on that
