### ISSUE TITLE
IntelliJ Clion support,and support  GDB  debug

### ISSUE THREAD

**Issue by zhuxiujia** [nim-lang/Nim#12333]
need IntelliJ Clion  or  vscode   support  GDB  debug。

for now No good tools to debug programs。

**Comment by narimiran** [comment]
> for now No good tools to debug programs。

Did you see a [video about nim-gdb](https://www.youtube.com/watch?v=DmYOPkI_LzU), about how to use the GDB debugger with Nim code?

**Comment by RUSshy** [comment]
do we live in 1960 or 2020, telling people to debug with terminal instead of deep integration with editor is like saying, "we don't care about debugging"

this is why no adoption

even rust is getting it right by focusing on IDE integration

**Comment by alehander92** [comment]
Vs code did actually work with nims gdb support, but I'm not sure if
something changed here. What does Clion require? If it works with normal
dwarf info I suppose it should be possible to debug nim there as well

**Comment by bitnom** [comment]
He's right - Jetbrains, so hot right now; Jetbrains...

**Comment by bitnom** [comment]
Also, there's this: https://plugins.jetbrains.com/plugin/15128-nim (Which Jetbrains made to their credit) but of course it's not debugging.

**Comment by zhuxiujia** [comment]
Can't debug because Nim is compiled to C  ？？？

**Comment by saem** [comment]
FYI for future folks who find this issue:
* [nim-gdb.py](https://github.com/nim-lang/Nim/pull/16479) updates forth coming
* [example of how to setup debugging](https://github.com/nim-lang/nimsuggest/issues/94#issuecomment-751411499) with nim extension](https://github.com/saem/vscode-nim) debugging with the vscode extension needs MS' cppdbg extension (though others can be made to work)
* CLion should be able to make use of this

**Comment by ringabout** [comment]
https://plugins.jetbrains.com/plugin/15128-nim supports both IntelliJ and Clion, and it also provides basic debugging supports.

![image](https://user-images.githubusercontent.com/43030857/113234954-dccbd500-92d4-11eb-84cd-13c4d1d711ee.png)


So please files issues at https://youtrack.jetbrains.com/issues/NIM if someone has problems with it.
