### ISSUE TITLE
vm crash

### ISSUE THREAD

**Issue by fowlmouth** [nim-lang/Nim#1234]
calling a macro `defMsg` from inside a template (`x`) crashes the compiler.
```nimrod
import entoody # https://bitbucket.org/fowlmouth/entoody

proc msg* (arg:int) {.unicast.}

template x (ty;body:stmt): stmt {.immediate.} =
  defMsg(ty, msg) do (arg:int):
    body

type Foo = object
x(Foo): 
  echo "FOO!"
```

**Comment by jangko** [comment]
no longer crash the vm, but also produce nothing

**Comment by Araq** [comment]
Like the 'anon proc' at compile-time bug which I finally fixed. Also no feedback. Closing.
