### ISSUE TITLE
Different shl behaviour depending in backend

### ISSUE THREAD

**Issue by ridho9** [nim-lang/Nim#12344]
Trying to `shl` an integer more than the integer width produces different results with C and js backend.

### Example
```nim
let x = 1
echo x shl 32
echo x shl 64
```

### Current Output
in C
```
4294967296
1
```
in js
```
1
1
```

### Expected Output
I don't really know, that shl should be an undefined behavior in C

### Possible Solution
Better documents the behavior and make it consistent across different backends

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.0 [Linux: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f7a8fc46c0012033917582eb740dc0343c093e35
active boot switches: -d:release
```

**Comment by Clyybber** [comment]
This is addressed by https://github.com/nim-lang/Nim/pull/11555

**Comment by ridho9** [comment]
Ah I didn't found that, thanks!
