### ISSUE TITLE
docgen: anchors for procs with arguments like seq[int] has extra [T]

### ISSUE THREAD

**Issue by Jjp137** [nim-lang/Nim#12357]
If a proc has an argument of type `seq[int]`, the generated HTML anchor for that part of the proc ends up being `seq[T][int]` in Nim 0.20.0 and later instead of `seq[int]`, which was the case in 0.19.6. This is incorrect because `T` was specified as `int`, so the extra `[T]` should not be there.

This issue does not occur for `set[int16]` or `openArray[int]` parameters, and I did not see it occur for any generic types the user defines. It may only occur for `seq[T]` parameters where the `T` is specified, although there may be other cases that I did not check.

### Example
Generate the documentation for this example with `nim doc`:
```nim
proc example*(x: seq[int]) =
  ## An example with an incorrect anchor.
  discard
```

### Current Output
Excerpt from the generated HTML:
```html
<a id="example,seq[T][int]"></a>
<dt><pre><span class="Keyword">proc</span> <a href="#example%2Cseq%5BT%5D%5Bint%5D"><span class="Identifier">example</span></a><span class="Other">(</span><span class="Identifier">x</span><span class="Other">:</span> <span class="Identifier">seq</span><span class="Other">[</span><span class="Identifier">int</span><span class="Other">]</span><span class="Other">)</span> <span><span class="Other">{</span><span class="Other pragmadots">...</span><span class="Other">}</span></span><span class="pragmawrap"><span class="Other">{.</span><span class="pragma"><span class="Identifier">raises</span><span class="Other">:</span> <span class="Other">[</span><span class="Other">]</span><span class="Other">,</span> <span class="Identifier">tags</span><span class="Other">:</span> <span class="Other">[</span><span class="Other">]</span></span><span class="Other">.}</span></span></pre></dt>
<dd>

An example with an incorrect anchor.

</dd>
```
Note that the id attribute of the first anchor tag has an extra `[T]` in it.

### Expected Output
This is what Nim 0.19.6 generated for that same proc:
```html
<a id="example,seq[int]"></a>
<dt><pre><span class="Keyword">proc</span> <span class="Identifier">example</span><span class="Other">(</span><span class="Identifier">x</span><span class="Other">:</span> <span class="Identifier">seq</span><span class="Other">[</span><span class="Identifier">int</span><span class="Other">]</span><span class="Other">)</span> <span><span class="Other">{</span><span class="Other pragmadots">...</span><span class="Other">}</span></span><span class="pragmawrap"><span class="Other">{.</span><span class="pragma"><span class="Identifier">raises</span><span class="Other">:</span> <span class="Other">[</span><span class="Other">]</span><span class="Other">,</span> <span class="Identifier">tags</span><span class="Other">:</span> <span class="Other">[</span><span class="Other">]</span></span><span class="Other">.}</span></span></pre></dt>
<dd>
An example with an incorrect anchor.

</dd>
```

### Additional Information
Output of `nim -v`:
```
Nim Compiler Version 1.0.99 [Linux: amd64]
Compiled at 2019-10-04
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 4ab9b6146b02bd707e8918aeab14ecbd5569a0b7
active boot switches: -d:release
```
Also occurs with 1.0 and 0.20.0. Does not occur with 0.19.6.

If you're wondering how I noticed this, it's because this issue breaks a few links in the documentation for `parseopt`. (Sadly, I didn't notice until now...)

**Comment by Jjp137** [comment]
Found the commit that broke it: https://github.com/nim-lang/Nim/commit/84f0a33bf0b0dc040c97205914d0b03c16e7c71a

This also explains why it only happens with sequences.

**Comment by narimiran** [comment]
I've tried to reproduce it with Nim 1.3.5, and it seems it has already been fixed.
