### ISSUE TITLE
nim.cfg syntax for --define:FOO:VAL undocumented or absent

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#12367]
I could not figure out how to add the following define syntax to my `nim.cfg`:

```
nim c -d:git2SetVer:0.28.3 some.nim
```

I tried many permutations with and without `"`, `=`, `:`. Maybe I missed the
magic incantation?  The solution was to use `config.nims` thusly:

```nim
switch("define", "git2SetVer:0.28.3")
# fwiw this seems to be parsed identically
#switch("define", "git2SetVer=0.28.3")
```

Thanks to @leorize and @shashlick.

**Comment by Araq** [comment]
True and also ``patchFile`` has no equivalent, NimScript is the future of Nim's configuration system and ``nim.cfg`` a legacy. Unfortunately I nowadays like the old ``.cfg`` better.... :-(

**Comment by kaushalmodi** [comment]
> Unfortunately I nowadays like the old .cfg better.... :-(

Seems like I will the last standing user of config.nims ..
