### ISSUE TITLE
[Feature] Extend dereference operator to types to get base

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#12363]
I could have sworn this was already an issue, but I can't seem to find it:

Right now you cannot `[]` on say `ref` types - and I mean *types themselves* and not instances thereof. So something like:

```nim
type
  X = ref object
  Y = X[]
```

is unallowed currently. However, via using instances of types you can currently get the root value type of a `ref` type in a kind of janky way:

```nim
type X = ref object

var 
  y: X
  z: y[].type
  
echo(z.type)
```

I propose that we just implement `[]` on `ref`/`ptr` types to lead us to the root type. I suppose the syntax could be bikeshedded but it would be more orthogonal for it just to be `[]`.

**Comment by Araq** [comment]
I'd rather have a ``varof`` then it becomes ``typeof(varof(X)[])``

**Comment by krux02** [comment]
```nim
type
  X = ref object
  Y = typeof(default(X)[])
```

not an issue.

**Comment by zevv** [comment]
Still worth an RFC maybe? Because `X[]` is *way* more readable then `typeof(default(X)[])`. I also find a practical need for this in finalizers, as there is now now way for creating a finalizer for a ref type without having a corresponding object type:

```
proc `=destroy`(f: var Foo[]) =
```

versus

```
proc `=destroy`(f: var type(default(Foo)[])) =
```

Cc: @Clyybber  @alaviss

**Comment by krux02** [comment]
@zevv 

have fun with it.

```nim
template unref[T](arg: typedesc[ref T]): untyped = T

proc `=destroy`(f: var unref(MyType)) =
    echo typeof(f)
```

Sorry you can't name it ``[]`` though. And allowing it would probably very expensive to implement for very little gain.
