### ISSUE TITLE
Documentation of setLen() is not clear enough, very low priority

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12360]
https://nim-lang.github.io/Nim/system.html#setLen%2Cseq%5BT%5D%5BT%5D%2CNatural
https://play.nim-lang.org/

```nim
var s = @[1, 2, 3]
echo s
s.setLen(1)
echo s
s.setLen(3)
echo s
```

```
@[1, 2, 3]
@[1]
@[1, 0, 0]
```

I had not really expected that elements are set to binary zero.  Indeed I hoped for that data is preserved -- I had a bunch of test data in a seq which generates an error, and I wanted to increase length of seq with preserved data until bug occurs. Have to rewrite it now.

**Comment by andreaferretti** [comment]
It makes sense, the sequence may be moved as a consequence of shrinking. Otherwise, that could be a memory leak

**Comment by StefanSalewski** [comment]
It may makes sense, but the doc should be clear. And as the proc is magic, we can not look at its source.

And stating if the buffer cmay shrink would be welcome too.

Current statement `If the current length is greater than the new length, s will be truncated.` is not really helpful, seems to be obvious for me.

**Comment by awr1** [comment]
Maybe we should have another proc that avoids a move in spite of a shrink (leaving the effects of an enlargement potentially undefined)

**Comment by andreaferretti** [comment]
The issue is not the enlargement. The issue is that if you do this, you will hold potentially on much more memory than is actually reachable. If you do this frequently enough, you have a memory leak. If you need a sequence that can be shrunk and then rehydrated to its original form, you can write a wrapper container using a stanrdard sequence and a capacity

**Comment by StefanSalewski** [comment]
>The issue is not the enlargement.

The issue is that the documentation is not clear and exact. But maybe it is good enough for now, bright people can guess well, others may not care. Will close this issue tomorrow then.

**Comment by StefanSalewski** [comment]
Closed as not really that important.
