### ISSUE TITLE
compiler crash in type with _ member

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12386]
```nim
type Foo = object
  case _: string
  else: discard

let x = Foo()
```
> Error: internal error: invalid kind for lastOrd(tyString)

**Comment by awr1** [comment]
Interesting that it compiles without being instantiation. IIRC Nim should not allow idents that start with `_`

**Comment by dawkot** [comment]
`_` idents have some special behaviour associated with them, so I'm pretty sure they're intentionally allowed (but probably not for object fields...)

**Comment by awr1** [comment]
The only use case I know for `_` is for tuple unpacking purposes (in both normal variable instantiation and iterators that yield tuples)

**Comment by narimiran** [comment]
This doesn't crash anymore, it produces `Error: selector must be of an ordinal type, float`.
