### ISSUE TITLE
typeof returns wrong type for string slice

### ISSUE THREAD

**Issue by koranza** [nim-lang/Nim#12383]
According to the tutorial, both ways of specifying the string slice pattern below are the same, but they return a different type when using 'typeof'
(https://nim-lang.github.io/Nim/tut1.html#advanced-types-slices)

### Example
```nim
var b = "some string"
echo $typeof(b)              

echo $typeof(b[0..^1])        
echo $typeof(b[0..b.len-1])   # wrong type
```

### Current Output
```
string
string
char
```

### Expected Output
```
string
string
string
```

A slice pattern that contains "^" will return "string" correctly, but other patterns return "char"

### Additional Information
* Nim Compiler Version 0.20.2

**Comment by timotheecour** [comment]
still a bug in 1.5.1 0d74f60742ecff2ac96d97e9ad421aa1b2e8fc85
```nim
when true:
  var b = "some string"
  echo typeof(b)
  echo typeof(b[0..^1])
  echo typeof(b[0..b.len-1], typeOfProc)
  echo type(b[0..b.len-1]) # BUG: prints char
  echo typeof(b[0..b.len-1]) # BUG: prints char
```
prints:
string
string
string
char
char

note that even though it prints char instead of string, the following allocates a new string for `b[2..b.len-1]` (as it should; this is why we have `toOpenArray`) as evidenced by coden
```nim
when true:
  for ai in b[2..b.len-1]:
    discard
```

**Comment by Araq** [comment]
That is just `typeof` working according to its spec.
