### ISSUE TITLE
HttpClient socket handle leak

### ISSUE THREAD

**Issue by zenywallet** [nim-lang/Nim#12381]
It seems that the HttpClient socket handle leaks when the server port is not open.

### Example
```nim
import httpClient

proc test() =
  var client = newHttpClient()
  discard client.getContent("http://localhost:8000")

for i in 0..<10000:
  try:
    test()
  except:
    let e = getCurrentException()
    echo e.name, ": ", e.msg
    if e.msg != "Connection refused":
      echo "break=", i
      break
```

### Current Output
```
OSError: Connection refused
OSError: Connection refused
...
OSError: Connection refused
OSError: Device or resource busy
Additional info: "System error"
break=1021
```

### Expected Output

```
OSError: Connection refused
OSError: Connection refused
...
OSError: Connection refused
```

### Possible Solution

This problem seems to be caused by the net.dial, the commit is 
https://github.com/nim-lang/Nim/commit/ecf278c4672aa680803ee82e1a59a686c765f226#diff-df7c4ae903eab01bc8c4f64f425b48c3R1492

```nim
proc dial*(address: string, port: Port,
           protocol = IPPROTO_TCP, buffered = true): Socket
           {.tags: [ReadIOEffect, WriteIOEffect].} =
  ...
  var fdPerDomain: array[low(Domain).ord..high(Domain).ord, SocketHandle]
  for i in low(fdPerDomain)..high(fdPerDomain):
    fdPerDomain[i] = osInvalidSocket
  ...
  
    lastFd = fdPerDomain[ord(domain)]
    if lastFd == osInvalidSocket:
      lastFd = newNativeSocket(domain, sockType, protocol)
      ...
      fdPerDomain[ord(domain)] = lastFd
```
fdPerDomain is always initialized by osInvalidSocket(-1) when called.
When I moved the var and initialization out of the proc, it seems to work fine.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.99 [Linux: amd64]
Compiled at 2019-10-07
```

**Comment by teroz** [comment]
Another issue as well is that the underlying socket file descriptor is no closed. I added a sleep in the loop and did a **lsof** of the running process.

![Screenshot from 2020-07-22 15-45-58](https://user-images.githubusercontent.com/853846/88184780-6a79ff80-cc33-11ea-8991-ad41ada3679b.png)


## Additinal info
```bash
teroz@wolverine:~$ nim --version
Nim Compiler Version 1.2.2 [Linux: amd64]
Compiled at 2020-06-16
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by simonkrauter** [comment]
I had the same problem. As workaround I call ``close`` on the ``httpclient`` object.

**Comment by ghost** [comment]
I think that there's no issue here - you must call `close` on httpclient, otherwise FDs will leak.
@dom96 what do you think?

**Comment by zenywallet** [comment]
I tried calling close, but the result is the same.
If the connection fails, client.getSocket() is nil.
It can be closed only if the connection is successful.

```nim
proc test() =
  var client: HttpClient
  try:
    client = newHttpClient()
    discard client.getContent("http://localhost:8000")
  finally:
    # If the connection fails, client.getSocket() is nil here.
    client.close()
```

**Comment by dom96** [comment]
so the problem here is that there is an fd leak when the connection fails

**Comment by kennymalac** [comment]
Critical that this should get fixed, it's been open for way too long...

**Comment by ringabout** [comment]
Does someone have reliable way to reproduce. I cannot reproduce on my ubuntu 20.04


```nim
import httpClient

proc test() =
  var client = newHttpClient()
  discard client.getContent("http://localhost:8000")

for i in 0..<10000:
  try:
    test()
  except:
    let e = getCurrentException()
    echo e.name, ": ", e.msg
    if e.msg != "Connection refused":
      echo "break=", i
      break
```

with Nim 1.0.6, Nim 1.2.6, Nim devel; --d:debug or --d:danger

**Comment by narimiran** [comment]
> Does someone have reliable way to reproduce

I've run your example on Manjaro Linux with Nim devel, Nim 1.4.2 and Nim 1.2.10, with or without `-d:release`, and for all of them I got:

```
...
OSError: Connection refused
OSError: Connection refused
OSError: Connection refused
OSError: Too many open files
break=1020
```

**Comment by narimiran** [comment]
> When I moved the var and initialization out of the proc, it seems to work fine.

I tried to do that in #17891, and while it fixed the problem for this example, it created new problems. So it is not a general fix, we need to come up with something else.

Any ideas?

**Comment by dom96** [comment]
Why can't we close the fds that are leaking?
