### ISSUE TITLE
typedesc as array members are still allowed

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12398]
### Example

```nim
var xs = [int, float, string]
```

### Error

> Error: internal error: symbol has no generated name: int

### Example

```nim
const xs = [int, float, string]

echo xs[0]
echo xs[1]
echo xs[2]
```
### Output

>None
None
None

### Expected output

Neither should compile (?)

**Comment by krux02** [comment]
This is strage, because I have memories implementing a compiler check to prevent exactly this. False memories? Anyway, these issue are related.

https://github.com/nim-lang/Nim/issues/8654
https://github.com/nim-lang/Nim/issues/8610

This PR is related:
https://github.com/nim-lang/Nim/pull/11959

**Comment by ghost** [comment]
Shows a proper error on latest devel:
```
~/P/ircord ❯❯❯ nim c -r "/home/dian/Projects/ircord/a.nim"
Hint: used config file '/home/dian/Things/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dian/Things/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dian/nim.cfg' [Conf]
....
/home/dian/Projects/ircord/a.nim(1, 5) Error: invalid type: 'typedesc' in this context: 'array[0..2, typedesc]' for var
```

Do we have a test case for that?

**Comment by timotheecour** [comment]
* dup of https://github.com/nim-lang/Nim/issues/9932 which was fixed in https://github.com/nim-lang/Nim/pull/13261 however I don't see a test case for that in that PR /cc @nc-x so I'd simply add a test case (for both [int] and @[int]) in some tests/errmsgs/t12398.nim test as done in https://github.com/nim-lang/Nim/pull/13261 (or better, use a `doAssert not compiles ...` test, which can be megatest-joined)

**Comment by timotheecour** [comment]
closed by https://github.com/nim-lang/Nim/pull/14795

**Comment by kamilchm** [comment]
Is there a way to have some sort of list of `typedesc`s in a `static` block?

**Comment by Araq** [comment]
You can do type introspection via Nim's macro system.

**Comment by timotheecour** [comment]
> Is there a way to have some sort of list of typedescs in a static block?

`type A = (int, float)` ?

**Comment by kamilchm** [comment]
I was looking for something to use a list of types in a loop, eg.:
```
macro x(t: typedesc) =
  ...

static:
  for t in [MyType1, MyType2, ....]: # <- I want to use it here
    x(t)
```

**Comment by tsoj** [comment]
> I was looking for something to use a list of types in a loop, eg.:
> 
> ```
> macro x(t: typedesc) =
>   ...
> 
> static:
>   for t in [MyType1, MyType2, ....]: # <- I want to use it here
>     x(t)
> ```

In this specific example, you could probably use a `macro xMany(args: varargs[untyped])`, where each args[i] is a type. But something like `openArray[T1, T2, T3]` would still be really helpful in cases, where one wouldn't want to use a macro (or a template), but a proper function.  
Though I currently can't think of an example other than an entity component system, if I'm honest.
