### ISSUE TITLE
expression in type body causes incorrect/useless error message

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#12415]
### Example
```nim
import macros

macro isSomePointerImpl(t: typedesc): bool =
  var impl = t.getTypeInst[1].getTypeImpl
  if impl.kind == nnkDistinctTy:
    impl = impl[0].getTypeImpl
  if impl.kind in {nnkPtrTy,nnkRefTy}:this
    result = newLit(true)
  elif impl.kind == nnkSym and impl.eqIdent("pointer"):
    result = newLit(true)
  else:
    result = newLit(false)

proc isSomePointer[T](t: typedesc[T]): bool {.compileTime.} =
  isSomePointerImpl(t)

type
  Option*[T] = object
    ## An optional type that stores its value and state separately in a boolean.
    when isSomePointer(typedesc(T)):
      val: T
    else:
      val: T
      has: bool
```

### Current Output

```
/tmp/scratch.nim(20, 23) Error: type mismatch: got <type T>
but expected one of: 
proc isSomePointer[T](t: typedesc[T]): bool
  first type mismatch at position: 1
  required type for t: type T
  but expression 'type(T)' is of type: type T
```

 * The expression is ``typedesc(T)`` not ``type(T)``, some remains of the failed attempt to allow the keyword ``type`` in more expressions.
 * Required is ``type T``, but got ``type T``? How is that really the cause of the problem?

### Expected Output

This should just compile

### Possible Solution

I think the body of the generic type is instantiated immediately. So ``isSomePointer(typedec(T))`` is resolved immediately before ``T`` is even resolved to a concrete type value. I think the evaluation of ``isSomePointer(typedesc(T))`` should be delayed until the parameter ``T`` has been give to the type, similar to how ``isSomePointer(typedesc(T))`` is resolved within the body of a generic function.

### Additional Information

This is code that I wrote in order to fix issue https://github.com/nim-lang/Nim/issues/9566. When this issue has been fixed, #9566 can be fixed as well.

**Comment by metagn** [comment]
Given example compiles in 2.0

> I think the evaluation of isSomePointer(typedesc(T)) should be delayed until the parameter T has been give to the type

#22029
