### ISSUE TITLE
wrong analysis of data usage

### ISSUE THREAD

**Issue by b3liever** [nim-lang/Nim#12431]
In this example compiler complains ``s`` is consumed in ``inner``, before ``add1`` is called. However order of evaluation of functions is different, ``add1`` is called first, before ``inner`` and so ``s`` in not consumed yet.

### Example

```nim
proc inner(s: sink string, len: int) =
   discard

proc add1(i: int): int =
   i+1

proc outer(s: sink string) =
   inner(s, add1(s.len))

var s = "aeon"
outer(s)
```

### Current Output
```
bug.nim(11, 7) Hint: passing 's' to a sink parameter introduces an implicit copy; use 'move(s)' to prevent it [Performance]
bug.nim(8, 18) Error: sink parameter `s` is already consumed a bug.nim(8, 10)
```

### Expected Output

```
compile successfully
```

### Additional Information

compile with ``--gc:destructors`` or ``--newruntime``
```
$ nim -v
Nim Compiler Version 1.0.99
```

**Comment by Araq** [comment]
It's "use after consume", IMO the compiler is correct and your code isn't.

**Comment by b3liever** [comment]
Its the same as writing:

```nim
proc outer(s: sink string) =
   let i = add1(s.len)
   inner(s, i)
```

**Comment by Araq** [comment]
It's not, evaluation is left-to-right as by the spec.

**Comment by b3liever** [comment]
OK.

**Comment by Clyybber** [comment]
But the execution order is *not* left to right here, because of the nesting.
This example should work IMO.

**Comment by Araq** [comment]
Huh? It's exactly something like ``inner(consume(s), add1(s.len))`` as ``inner``` takes a ``sink`` parameter.
