### ISSUE TITLE
Inner template defined more than once

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#12446]
**Test**
```nim
template foo(body: untyped) =
  template bar(i: int) = echo i
  body
  
proc main =
  foo:
    bar(1)
  foo:
    bar(2)

main()
```
**Result**
```nim
Test.nim(8, 3) template/generic instantiation of `foo` from here
Test.nim(9, 8) Error: ambiguous call;
both main.bar(i`gensym173010: int) [declared in Test.nim(2, 12)]
and main.bar(i`gensym173016: int) [declared in Test.nim(2, 12)]
match for: (int literal(2))
```
Used to be alright, but now it seems that the second 'foo:' is defining 'bar' again.

**Workaround**
```nim
template foo(body: untyped) =
  block:
    template bar(i: int) = echo i
    body
```
***
```nim
Nim Compiler Version 1.0.99 [Linux: i386]
Compiled at 2019-10-16
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 734da9e1dfdd5cb441a5c1461539f10ab331596a
active boot switches: -d:release
```

**Comment by Araq** [comment]
Well, the compiler got fixed. Why should this work?

**Comment by Wh1teDuke** [comment]
>Why should this work?

It stops being hygienic:
```nim
template foo =
  type MyFoo = int
  var i: MyFoo
  template showValue(i) = echo i
  showValue(i) 

proc main =
  foo()
  foo()

main()
```

Why does 'showValue' leaks but not 'i' or 'MyFoo' ?

**Comment by Araq** [comment]
Because according to the spec some symbols default to ``.inject`` (like templates, procs, etc) and others default to ``.gensym`` (everything else). Now ... whether that part of the spec was a good idea is a different topic...

**Comment by krux02** [comment]
My personal recommendation: don't use inner templates. For the most part they only cause fragile unnecessary complexity.

**Comment by Araq** [comment]
Not a bug here.
