### ISSUE TITLE
comparison on csize is broken

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#12458]
csize behaves differently at compile time and runtime

### Example

```nim
proc foobar(x,y: csize): void =
  echo x, " < ", y, ": ", x < y

const
  a = csize(-1)
  b = csize(123)

foobar(a,b)
static:
  foobar(a,b)
```

### Current Output
```
Hint: scratch [Processing]
-1 < 123: true
CC: stdlib_io.nim
CC: scratch.nim
Hint:  [Link]
Hint: operation successful (21870 lines compiled; 0.159 sec total; 25.812MiB peakmem; Debug Build) [SuccessX]
Hint: /tmp/scratch  [Exec]
-1 < 123: false
```

### Expected Output

```
# /tmp/scratch.nim(5, 12) Error: -1 can't be converted to csize
```

### Additional Information
bug was introduced by https://github.com/nim-lang/Nim/pull/12447

### Possible Solution
revert https://github.com/nim-lang/Nim/pull/12447

**Comment by Araq** [comment]
There is not a regression here and it's already an open bug.
