### ISSUE TITLE
Namespace unittest.TestStatus usage to avoid collisions with user-defined types/methods

### ISSUE THREAD

**Issue by ducdetronquito** [nim-lang/Nim#12465]
Defining a type or a method with name already used by `unittest.TestStatus` values raises a compile error.

### Example
```nim
import unittest


proc Ok(): string =
  return "Yes"

suite "Suite":
    
    test "Are you Ok ?":
      check(Ok() == "Yes")
```

### Current Output
```
tests.nim(31, 7) template/generic instantiation of `suite` from here
tests.nim(33, 10) template/generic instantiation of `test` from here
nim-1.0.0\lib\pure\unittest.nim(490, 9) Error: invalid type: 'None' for var
```

### Expected Output

```
[Suite] Are you ok ?
  [OK] Yes
```

### Possible Solution

I imagine we could get rid of these errors by namespacing `TestStatus` properly in `lib/pure/unittest.nim`

### Additional Information

- Nim Compiler Version: **1.0.0** / Windows 10 (64bits)

**Comment by ducdetronquito** [comment]
If one can confirm that this a bug/regression, and that my possible solution is fine, I am willing to make a pull-request in the upcoming hours :)

**Comment by Araq** [comment]
Confirmed.
