### ISSUE TITLE
Nim compiler produces C code with incompatible type assignment

### ISSUE THREAD

**Issue by TinBryn** [nim-lang/Nim#12464]
I have a variant type (case on discriminant) and one of the variants contains a proc type.
There are a few cases where I have specific values (these variants don't contain procs) that are known at compile time so I want them to be declared `const`.
When both of those conditions are met, as assignment from a const value results in a compiler failure from C, not from nim.

### Example

```nim
type
  Foo = object
    case isFunc: bool
    of false: nil
    of true:
      fun: proc(): int

const i = Foo(isFunc: false)

let j = i
```

### Current Output
gcc fails to compile

### Expected Output

program should compile

### Possible Solution

declaring the values `let` results in correct compilation, but ideally nim shouldn't produce incorrect C code without diagnostics, as the generated code is difficult to diagnose.

### Additional Information

```
$ nim -v
Nim Compiler Version 1.0.0
```

**Comment by Araq** [comment]
``const`` case objects are not supported. Unfortunately some code relies on the fact that Nim doesn't diagnose this and "happens" to work...

**Comment by Clyybber** [comment]
We should add support for them IMO.

**Comment by Araq** [comment]
@Clyybber Tried, IMO it's quite impossible when sticking to C89 and C++98.

**Comment by ghost** [comment]
This seems to be fixed on devel, need to add a test case?

**Comment by timotheecour** [comment]
yes please, with this template: https://github.com/timotheecour/Nim/issues/534#issuecomment-769565033
possibly under `tests/misc/t12464.nim` or elsewhere

**Comment by ringabout** [comment]
!nim c
```nim
type
  Foo = object
    case isFunc: bool
    of false: nil
    of true:
      fun: proc(): int

const i = Foo(isFunc: false)

let j = i
```
