### ISSUE TITLE
issues in the manual

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#12486]
There is a lot of false/misleading information in the tuple/object section of the manual. This is what I found so far.

* [A tuple also defines an *order* of the fields](https://github.com/nim-lang/Nim/blob/2ccd1c34284f08ba8e4c7b5b4986de8899f60354/doc/manual.rst#L1475)
    I think this relates to ``(1,2) < (2,1)`` being a thing, but
  without context, _order_ might mean many things. Also for objects it
  is defined that the members will be in the same order in memory as
  they are in the definition. This is not clear here.
* [Tuples are meant for heterogeneous storage types with no overhead and few abstraction possibilities](https://github.com/nim-lang/Nim/blob/2ccd1c34284f08ba8e4c7b5b4986de8899f60354/doc/manual.rst#L1476)
  This is very misleading. Objects also don't have overhead unless
  they explicity use inheritance. I feel like I have false memories
  fixing this part of the manual.
* [The constructor `()` can be used to construct tuples](https://github.com/nim-lang/Nim/blob/2ccd1c34284f08ba8e4c7b5b4986de8899f60354/doc/manual.rst#L1477)
  Nim does not have such a thing as a constructor. What is meant is
  the tuple constructor syntax. This is very misleading.
* [Objects have access to their type during at  runtime](https://github.com/nim-lang/Nim/blob/2ccd1c34284f08ba8e4c7b5b4986de8899f60354/doc/manual.rst#L1524)
  This is just wrong. Objects only have a field with type information (overhead),
  if inheritance is used. I have again false memory of correcting this.

EDIT:
  [The assignment operator can be overloaded](https://github.com/nim-lang/Nim/blob/devel/doc/tut1.rst#the-assignment-statement)
    Aparently the assignment statement can be overloaded. This statement here sits in isolation. It is not explained how the assignment can be overloaded. Here should be a link to a section explaining the assignment operator, how it works, how it can be overloaded, and if it should be overloaded.

**Comment by Clyybber** [comment]
There is an assignment operator, its `=`  and you can define it for different types.

**Comment by Clyybber** [comment]
It isn't called because it is optimized to a `=sink` operation.
```nim
type
  MyType = object

proc `=`(dest: var MyType, src: MyType) =
  echo "myasgn"

proc main() =
  var mt: MyType
  mt = mt
  var mt2 = mt #Will get `=` copied
  var tmp = mt #Will get `=sink` ed
  mt = mt2
  echo "done"

main()
```
This should work.

**Comment by krux02** [comment]
My complains about the assignment operator are now different.
