### ISSUE TITLE
`os.splitPath()` behavior is inconsistent with `os.splitFile()`

### ISSUE THREAD

**Issue by luav** [nim-lang/Nim#12482]
`os.splitFile("/tmp")` results in `dir = "/"` and `name = "tmp"` or `("/", "tmp", "")`, which is expected, correct and works like in other languages.  
However, another path processing procedure from the same module, `os.splitPath("/tmp")`, results in `("", "tmp")`, which is  
1) inconsistent with other path processing procedures (`splitFile`) and  
2) prevents distinguishing of the current sub-directory from root directory:  
the expected parent directory for `os.splitPath("/tmp")` is root (`"/"`) but not the current directory (empty `""`, which is interpreted by the OS as `"."`).

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.0
```

**Comment by luav** [comment]
Fixed in #12481

**Comment by disruptek** [comment]
Close or revert?
