### ISSUE TITLE
Imports in blocks

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#1248]
I'd like to be able to use imports inside any block, so that the things the import provides are scoped to that block

```
proc dostuff() =
  import unsigned
  discard 1u32 + 3u32

var node: PJsonNode
block:
  import mydsl
  node = P{
    a: 231
  }
```
This avoids littering the module with procedures that may be ambiguous or not generally useful, or to contain DSLs to specific areas

**Comment by Araq** [comment]
That feature introduced various troublesome scoping problems for D.
