### ISSUE TITLE
nim check allows gorgeEx but doesn't allow writeFile

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#12491]
Nim 1.0 onwards disabled dangerous actions in `nim check`. However, it is unclear what should and should not work. I couldn't find an issue/PR or commit related to the topic so opening this.

This works with nim check.
```nim
static:
  echo gorgeEx("sleep 5")
```

This does not work with `nim check`.
```nim
static:
  writeFile("/tmp/abc.txt", "ABC")
  doAssert fileExists("/tmp/abc.txt")
```

Context for this issue is [this](https://github.com/nimterop/nimterop/issues/144) nimterop issue.

**Comment by Araq** [comment]
This is a showstopper bug for 1.0.4, neither nimsuggest nor nim check run staticExec nor writeFile.
