### ISSUE TITLE
Documentation request about integer literals in the compiler

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#12503]
I am requesting this, because my brain can't store the specification. I know we talked about this, but I pretty bad at memorizing this information. I also need a specification that I can reference in order to report bugs. Sometimes the integer node is constructed incorrectly. To report this I need a specification that I can quote.

So this is the situation so far:

The integer node cane be one of these node kinds:

    nkIntLit, nkInt8Lit, nkInt16Lit, nkInt32Lit, nkInt64Lit, nkUIntLit, nkUInt8Lit, nkUInt16Lit, nkUInt32Lit, nkUInt64Lit

On top of the node kind, there is a `typ` field. This can be nil, or it can be one of these type kinds:

    tyInt, tyInt8, tyInt16, tyInt32, tyInt64, tyUInt, tyUInt8, tyUInt16, tyUInt32, tyUInt64

These are the questions that I have:

 * What does it mean when the `typ` field is nil?
 * What does it mean when the type kind and the node kind do mismatch?
 * How is an integer represented that isn't put into a concrete type yet (e.g. the `13` in `let x: int8 = 13` before type checking)?
 * What does it mean when node kind and typ kind mismatch? Does one have priority over the other?
 * Why is there no [type suffix](https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants)  for the type `int`?

### Additional Information

There are many parts of the compiler that I would like to be documented further, but currently this is important for the VM bugs that I am working on.

**Comment by m-holger** [comment]
For clarity, would it be worthwhile to add after the last code example:

This holds true even if one of the overloaded procedures can be instantiated for 
the int type. 
```
  proc foo[T : int] (n : T) =
      echo ("abc")

  proc  foo[T : uint] (n : T) =
    echo ("def")

  foo(123) # output : abc


  proc bar[T : int | string] (n : T) =
    echo ("abc")

  proc  bar[T : uint] (n : T) =
    echo ("def")

  bar(123) # Error: ambiguous call
```
