### ISSUE TITLE
List of processes and get information on process

### ISSUE THREAD

**Issue by agentsofshield** [nim-lang/Nim#12507]
Hello,

I was not able to find any pure Nim functions which handles running processes. First, there is no native way to get a list of running processes, like CreateToolhelp32Snapshot in C. Second, I want to get a handle for a process, in C I would use OpenProcess function, in Nim I would have to use the winlean module. In the osproc module there is a process object which I think could be usable for other processes and not only owned processes.

Code example for what I wish I could do in Nim, for getting a process object from a PID:

`proc getProcess(pid: Pid): Process = ... ... ...`

Thank you in advance.

**Comment by Araq** [comment]
This was solved on the forum. Closing.

**Comment by guzba** [comment]
https://forum.nim-lang.org/t/5390
