### ISSUE TITLE
 Error: illegal context for 'nimvm' magic if 'nimvm' is used with single branch 'when'

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#12517]
Time consuming bug.

### Example
```nim
proc abc(x: SomeInteger) =
  when nimvm:
     echo "hello"
  echo "world"

static:  
  abc(10)
```

### Current Output
```
 Error: illegal context for 'nimvm' magic
```

### Expected Output
```
hello
world
```

### Possible Solutions
```
when nimvm:
  echo "hello"
else:
  discard  # ugly
```

```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 193b3c66bbeffafaebff166d24b9866f1eaaac0e
active boot switches: -d:release
```

**Comment by krux02** [comment]
I think this should be easy to fix.

**Comment by krux02** [comment]
hmm, try latest version of Nim. I can't reproduce it in devel.

**Comment by SolitudeSF** [comment]
doesnt work for me in latest devel.

**Comment by jangko** [comment]
> hmm, try latest version of Nim. I can't reproduce it in devel.

sorry, the example is incomplete. edited.

**Comment by vinitextos800** [comment]
proc abc(x: SomeInteger) =
  when nimvm:
     echo "hello"
  echo "world"

static:  
  abc(10)
Se você utilizar esse código então você terá sucesso mesmo

O [Duralong funciona](https://www.maesabetudo.com.br/duralong/) combatendo a impotência sexual, aumenta a libido e garante mais prazer e disposição sexual. Ele é um produto totalmente natural, criado para reestabelecer completamente a saúde sexual masculina.

**Comment by krux02** [comment]
@vinitextos800 English please.

**Comment by narimiran** [comment]
The requirement to must have an `else` branch for `nimvm` is [documented in the manual](https://nim-lang.github.io/Nim/manual.html#statements-and-expressions-when-nimvm-statement), so I would say that this works as expected/designed. :/

**Comment by jangko** [comment]
among the 4 points of the manual about `nimvm`, point about `else` branch is the most ridiculous.
why can't the compiler insert a synthetic `else` branch if it really needed by other parts of the compiler?

at least, fix the error message rather confusing `illegal context`, because the syntax is correct even without `else` branch.

**Comment by Araq** [comment]
Well ``when nimvm`` is an expensive special case, that's why. Maybe we should have used ``if nimvm`` and optimize the ``if`` away in the backends. Would have been much easier to implement...

**Comment by krux02** [comment]
I don't think the `if` would work, because the `when nimvm` construct is often used when there is something that doesn't even compile in one backend. I think the best idea is a special construct, for example ``whennimvm: ``, because it really is a special thing. It also makes it obvious why things like ``when nimvm and something()`` can't be written.

**Comment by jangko** [comment]
iirc Nim parser is handcrafted LL(1). why defer until it become expensive in later compiler phase?
doesn't the parser can handle this special case without sacrificing syntax and performance?

**Comment by Araq** [comment]
The parser has nothing to do with this.
