### ISSUE TITLE
Low level arithmetics bug: -3 mod 7 == 3

### ISSUE THREAD

**Issue by snjax** [nim-lang/Nim#12514]
Function mod returns the wrong result.

Nim versions affected by the bug: >= 1.0

### Example
```nim
echo -3 mod 7
```

### Current Output
```
3
```

### Expected Output
```
-3
```

### Possible Solution

rollback mod operation to 0.20.2 version

**Comment by narimiran** [comment]
An easier example to see the buggy behaviour:

```nim
echo -3 mod 5
echo -13 mod 5
```

```
3
-3
```
