### ISSUE TITLE
tables.take() is defined only for `Table` and missed for other table containers

### ISSUE THREAD

**Issue by luav** [nim-lang/Nim#12519]
`tables.take()` is defined only for `Table` and missed for other table containers, though module functions are expected to work properly for all related containers.

### Example
```nim
import tables

let t = newOrderedTable[string, string]()
var v: string
echo t.take("k", v)
```

### Current Output
```
Error: type mismatch: got <OrderedTable[system.string, system.string], string, string>
```

### Expected Output
```
false
```

### Possible Solution

Implement `tables.take()` for `OrderedTable` and `CountTable`.

## Additional Information
```sh
$ nim -v
Nim Compiler Version 1.0.0
```

**Comment by narimiran** [comment]
Btw, `CountTable` doesn't even have `del` proc, so I'm not sure if it should have `take` proc (which uses `del` behind the scenes for `Table`).

**Comment by luav** [comment]
Yes, the `CountTable` differs in many aspects from the `Table` in terms of the implementation but not in terms of the basic expected capabilities: `CountTable` should provide at least all the methods defined for the `Table` and might add some specific methods.
It is reasonable to expect a uniform interface of the standard library for the standard data structures having the same semantic meaning (i.e., defined in the same module and having similar functionality: non/hash table, ordered table, etc.). The implementation of this functionality is indeed might differ a lot for each particular data type but it should not concern the end users expecting intuitive and uniform interfaces.

**Comment by Araq** [comment]
> The implementation of this functionality is indeed might differ a lot for each particular data type but it should not concern the end users expecting intuitive and uniform interfaces.

Sure, agreed.
