### ISSUE TITLE
Complex: complex proc does not create Complex[float32] from float32 argument

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12525]
Test case

```Nim
import complex

let a = complex(1'f32)
doAssert a is Complex[float32]
```

**Comment by xflywind** [comment]
`complex` function has a param ` im` with a default value 0.0. So if not specify generics T or both params with float32, will get float64.
```nim
import complex

let a = complex(1'f32, 0'f32)
doAssert a is Complex[float32]
```
or
```nim
import complex


let a = complex[float32](1'f32)
doAssert  a is Complex[float32]
```

**Comment by Clyybber** [comment]
IMO the explicitly supplied arguments should have a higher priority then the default values, meaning that to match the generic, default values should be checked for a convertible relation first, and then the explicitly supplied ones(if necessary).

**Comment by krux02** [comment]
Well, I wrote this program here to point out the bug. I should make an issue out of it.

```nim
proc foo[T](a: T; b: T) =
  echo T

foo(0.0'f32, 0.0)

proc bar[T](a: T; b: T = 0.0) =
  echo T

bar(0.0'f32)
```
output:
```
float32
float64
```
The output should be the same in both cases. But I guess I can write a workaround for it.
