### ISSUE TITLE
Broken link to c2nim in backends.rst/.html

### ISSUE THREAD

**Issue by AvdN** [nim-lang/Nim#12537]
While reading the [backends manual page](https://nim-lang.org/docs/backends.html), I came across a link to c2nim that doesn't work. The .rst contains

```
c2nim tool <https://nim-lang.org/docs/c2nim.html>
```
Which is a dead link.

Googling brought two alternatives, older versions of nim seem to have supported a converted .html version:
```
https://nim-lang.org/0.15.0/c2nim.html
```

, and  the tools page directly refers to github and lets it resolve the .rst to html display:

```
https://github.com/nim-lang/c2nim/blob/master/doc/c2nim.rst
```

I can of course provide a PR for the second alternative, but I am not sure that is the better option.

**Comment by Araq** [comment]
Please fix the "backends manual page".

**Comment by AvdN** [comment]
> Please fix the "backends manual page".

@Araq does that mean you want use the link to the github page for c2nim?

**Comment by Araq** [comment]
Yes.
