### ISSUE TITLE
[1.0.0]iup programm using iup.imageLibOpen() fails to run with 'could not import: IupImageLibOpen'

### ISSUE THREAD

**Issue by Heribert17** [nim-lang/Nim#12534]
Program start fails with 'could not import: IupImageLibOpen'

### Example
Source:
discard iup.open(nil, nil)
iup.imageLibOpen()

```Hint: c:\Users\herib\Documents\Projekte\Privat\Test_nim\GUI_Tutorial\Simple_Notepad.exe  [Exec]
could not import: IupImageLibOpen
Error: execution of an external program failed: 'c:\Users\herib\Documents\Projekte\Privat\Test_nim\GUI_Tutorial\Simple_Notepad.exe '
```

### Possible Solution
The import file iup.nim doesn't open the windows dll with the images, it only opens the standard iup.dll

Solutin:
Modifed \nim-1.0.0\lib\wrappers\iup.nim:
line 39 and following changed to:
when defined(windows):
  const dllname = "iup(|30|27|26|25|24).dll"
  # Heribert added:
  const dllname_img = "iupimglib.dll"

line 103 change to:
# Heribert removed:  proc imageLibOpen*() {.importc: "IupImageLibOpen", cdecl, dynlib: dllname.}
# Heribert added:
proc imageLibOpen*() {.importc: "IupImageLibOpen", cdecl, dynlib: dllname_img.}

### Additional Information

* Because I sarted to learn nim under windows, I didn't check if the same error exist under Linux or Mac

```
PS nim -v
Nim Compiler Version 1.0.0 [Windows: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f7a8fc46c0012033917582eb740dc0343c093e35
active boot switches: -d:release
```

**Comment by ringabout** [comment]
`iup` has been remove from this repo.

And this issue seems to be solved already.
https://github.com/nim-lang/iup/commit/dfc63f3167177f617833d3f4db55b505d1022393
