### ISSUE TITLE
Cannot global import 'times'

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#12540]
**Test**
```nim
# .cfg file
import: times
```
**Result**
```nim
/Nim/lib/pure/times.nim(231, 7) Error: cannot 'importc'
variable at compile time; tzset
```
***
```nim
>nim -v
Nim Compiler Version 1.1.0 [Linux: i386]
Compiled at 2019-10-28
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 5ed99f8d3fc67d6f02172ab9cbcc67c17eeee5c9
active boot switches: -d:release
```

**Comment by Araq** [comment]
That's not a bug, you cannot do time-handling at compile-time.

**Comment by Wh1teDuke** [comment]
> That's not a bug, you cannot do time-handling at compile-time.

I'm not doing anything at compile time tho. Why can I import:strutils but not times? I expect the same behavior for both modules.

**Comment by Araq** [comment]
Ah ok.

**Comment by andreaferretti** [comment]
> you cannot do time-handling at compile-time

Why not? We could use a restricted subset of features. With dates, for instance, one can perform a lot of perfectly pure computations that should be doable at compile time

**Comment by ringabout** [comment]
Now you can import it in the nimscript file.
