### ISSUE TITLE
to add non-destructive procedure `shuffled`

### ISSUE THREAD

**Issue by tkdalic** [nim-lang/Nim#12543]
### Summary
I want to add a non-destructive function `shuffled`.

### Description

Now, shuffle procedure is bang procedure.
But,please make shuffle procedure make nondestructive.

now, shuffle procedure's type is
```
proc shuffle*[T](x: var openArray[T]) =
```

please make `shuffled` procedure is

```
proc shuffled[T](x: seq[T]): seq[T] =
  result = x
  shuffle(result)
```

**Comment by SolitudeSF** [comment]
non-destructive version should be called `shuffled`.

**Comment by andreaferretti** [comment]
`openArray[T]` is not a concrete type and as such cannot be returned. You can write something for seq, though, like this

```nim
proc shuffled[T](x: seq[T]): seq[T] =
  result = x
  shuffle(result)
```

**Comment by krux02** [comment]
> [...] bang procedure.

We don't use that terminology here.

Regarding your suggestion to make a breaking change. We can't do that, because we don't make breaking changes.

**Comment by tkdalic** [comment]
I understood!
Thank you

**Comment by tkdalic** [comment]
I understood,thank you.

Is it possible to add `shuffled`?

**Comment by krux02** [comment]
Yes shuffled would be ok, but please edit your issue that you now want `shuffled`. Then I still can't guarantee that it will be implemented/merged, but I personally think it would be ok.

**Comment by tkdalic** [comment]
@krux02 
Thank you.
I edit my issue.
Next I will make PR.

**Comment by tkdalic** [comment]
The request is solved by `outplace`.
I close this issue.
