### ISSUE TITLE
Chinese input yields "unhandled exception" in DOS prompt

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#12556]
Chinese input yields "unhandled exception" in DOS prompt

1. First of all, I know someone will say "DOS prompt of WINDOWS is crappy", but since there is still some( or a lot of) users of it, I think it will be better to support it too.

2. Secondly, a C source for comparasion
or this heading says "https://github.com/nim-lang/Nim/issues/11618" may be not right

```C
// a_c.c which is saved as UTF8 encoded file
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

int main()
{
    char result[20];
    //printf("please input string\n");
    scanf("%s", result);
    printf("strlen = %i\n", strlen(result));
    printf("%s\n", result);
}

```

in MSYS2
```bash
$ gcc a_c.c -o a_c.exe

$ ./a_c.exe
你好        <-- please note that we input this one with IME( Input Method Editors)
strlen = 6
你好        <-- this is just what we have input above
```

in DOS prompt
```
R:\>chcp
active codepage: 936

R:\>a_c.exe
你好        <-- please note that we input this one with IME( Input Method Editors)
strlen = 4
你好        <-- this is just what we have input above

R:\>

```

if we change the code page via `chcp 65001`, where 65001 is used in the solution(https://github.com/nim-lang/Nim/issues/11618), then
```
R:\>chcp
Active code page: 65001

R:\>a_c.exe
你好        <-- please note that we CAN NOT input this one with IME( Input Method Editors)
strlen = 1
              <-- please note there is no echo

R:\>
```
we will find 2 things: 1. we can not input Chinese with IME( Input Method Editors), so I have to copy&paste `你好` here, however this will be useless if the user can not input what he needs. 2. no expected information is echoed since `strlen(result) == 1`. My humble conclusion is `codepage 65001` is not a real solution

3.Thirdly, let's go into nim part

I am using latest nim on Windows 7 64 bits in MSYS2+MingW

https://github.com/nim-lang/Nim/issues/11618 fixed the displayed Chinese problem in DOS prompt, now the Chinese can be show same in DOS prompt and MSYS2

for
```nim
# a_nim.nim save in utf8
echo "please input string"
var result = readLine stdin
echo "strlen = ", len result
echo result
```
in MSYS2, we get what we expected
```bash
$ nim c -r a_nim.nim
please input string
你好
strlen = 6
你好
```
however, in DOS prompt
```bash
R:\>a_nim.exe
please input string
你好
R:\a_nim.nim(3)          a_nim
E:\msys64\home\USER\_nim\nim\lib\system\io.nim(351) readLine
E:\msys64\home\USER\_nim\nim\lib\system\io.nim(138) raiseEOF
Error: unhandled exception: EOF reached [EOFError]

R:\>
```

**Comment by jangko** [comment]
unicode input cannot be handled by simple 'readLine'. a portable yet capable of handling unicode input with various OS and terminals requires very complex input handling. 

you can use one of [nim-prompt](https://github.com/surf1nb1rd/nim-prompt) or [nim-noise](https://github.com/jangko/nim-noise) to replace simple 'readLine'.

IMO it will be a heavy burden for Nim dev team to maintain or implement a more powerful 'readLine'. Let's delegate it to an independent package.

**Comment by Araq** [comment]
We don't support MSYS2 btw, we cannot support all these alternative DOS-Boxes each with their own bugs when it comes to Unicode.

**Comment by narimiran** [comment]
> IMO it will be a heavy burden for Nim dev team to maintain or implement a more powerful 'readLine'. Let's delegate it to an independent package.

> We don't support MSYS2 btw, we cannot support all these alternative DOS-Boxes each with their own bugs when it comes to Unicode.

I'm closing it with `won't fix` tag. If you don't agree, please reopen.
