### ISSUE TITLE
`mapIt` from `sequtils` not working in `{.push compile_time.}` context

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12558]
### Example
```nim
import sequtils

{.push compile_time.}

proc foo =
  discard map_it([1, 2, 3], $it)

{.pop.}
```

### Current Output
```
/usercode/in.nim(6, 17) template/generic instantiation of `mapIt` from here
/playground/nim/lib/pure/collections/sequtils.nim(824, 13) Error: cannot evaluate at compile time: it
```

### Additional Information

It works with macros, which are also compile-time only
```nim
import sequtils

macro foo =
  discard map_it([1, 2, 3], $it)

foo
```

```
$ nim -v
Nim Compiler Version 1.0.99 [Windows: amd64]
Compiled at 2019-10-10
```

**Comment by krux02** [comment]
```nim
import sequtils

proc foo() {.compileTime.} =
  echo map_it([1, 2, 3], $it)

static:
  foo()
```

It is just this ``{.push compile_time.}`` that I didn't know would be possible, that doesn't work. Maybe the solution is to raise a compilation error at ``{.push compile_time.}`` already.

**Comment by krux02** [comment]
I renamed it, because map_it does work in compileTime procs, it is the `{.push compile_time.}` that causes the problem.
