### ISSUE TITLE
isNil() is wrong for typed and untyped macro parameter

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12579]
Function `isNil()` gives wrong result.

### Example
```nim
macro m(x: untyped): untyped =
  echo x == nil
  echo x.isNil

macro m2(x: typed): untyped =
  echo x == nil
  echo x.isNil

m(nil)
m(0)

m2(nil)
m2(0)
```

### Current Output
```
Hint: t [Processing]
true
false
false
false
true
false
false
false

```

### Expected Output
```
Hint: t [Processing]
true
true
false
false
true
true
false
false
```

### Possible Solution

* fix it, or do not use

### Additional Information

* I wasted two hours with that

```
$ nim -v
Nim Compiler Version 1.0.99 [Linux: amd64]
Compiled at 2019-10-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 822078ed12a48aa61eda0c65bc9ee675836a9fd3
active boot switches: -d:release
```

**Comment by krux02** [comment]
I would argue that the output of everything should be false, because your argument is a nil literal. A nil literal is something, it is a nod and it has line information. This is very different from `x` actually being nil where truly no node exists.

**Comment by StefanSalewski** [comment]
But how can I test then that an optional argument is nil? See

https://forum.nim-lang.org/t/5452
