### ISSUE TITLE
Add ASM output to the compiler

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12578]
I often want to inspect the assembly generated for my code, the current possibilities to inspect assembly are quite cumbersome:
  - objdump the object files in the compiler cache
  - use a debugger
  - compile with --passc:"-S" and --noLinking and the assembly will be in the nim cache as file.nim.c.o

Ideally nim compiler provides an assembly output. This will also ease integration with Godbolt (https://github.com/mattgodbolt/compiler-explorer/issues/206)

## Default flags
Here are useful flags that can probably be default for ASM output.
```
nim c --passC:"-fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -masm=intel -S" --noLinking:on "path/to/file.nim"
```
"-fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti" is needed to remove the cfi directives which is extra noise that doesn't correspond to assembly code but tell the debugger and exception handlers how to unwind the stack.

"-masm=intel" for Intel syntax (opcode dst src) order vs ATT (opcode src dst) and a difference in addressing convention.

## Interleaving with generated C code
Add "-fverbose-asm"

```
nim c --passC:"-fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -masm=intel -fverbose-asm -S" --noLinking:on "path/to/file.nim"
```

Note that `-d:danger` will keep that inforomation.

## Interleaving with Nim source code
Add "-fverbose-asm" --debugger:native

```
nim c --passC:"-fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -masm=intel -fverbose-asm -S" --debugger:native --noLinking:on "path/to/file.nim"
```

## Testing

I recommend using a simple module like "[options.nim](https://github.com/nim-lang/Nim/blob/4e0f12092ebb64047dc0ecfc86e348e4d93eab4c/lib/pure/options.nim)"

The disassembled output will be in nim cache, on unix: $HOME/.cache/options_d/options.nim.c.o

## Windows

Contributions welcome.

**Comment by juancarlospaco** [comment]
https://github.com/kaushalmodi/nim_config/blob/master/config.nims#L313

**Comment by demotomohiro** [comment]
I tested all commands posted by @mratsim on my Windows 8.1 with gcc 8.1.0 and all worked in the same way.

Following command generate assembly code when vcc backend is set.
```console
nim c --passC:"/FA" --cc:vcc --noLinking:on test.nim
```

But all assembly file is created in the current directly, not under nimcache directory.
A path to the assembly file need to be specified with `/Fa` argument when you want to place it in different directory.
https://docs.microsoft.com/en-us/cpp/build/reference/fa-fa-listing-file?view=vs-2019

**Comment by mratsim** [comment]
> https://github.com/kaushalmodi/nim_config/blob/master/config.nims#L313

Interesting flags, I'm not sure about the `-fno-math-errno` but since I want to inspect the default ASM output to check its quality (or debug it), I wouldn't change the inlining with "-fno-inline-functions -fno-inline-functions-called-once -fno-inline-small-functions"

**Comment by 98982872** [comment]
Is anybody considering the nlvm backend?

**Comment by mratsim** [comment]
> Is anybody considering the nlvm backend?

I think this is a discussion more suited to the forum, or if you have fleshed out ideas and want to discuss how to have an officially supported LLVM backend, in the RFCs repo: https://github.com/nim-lang/RFCs/issues.

**Comment by Araq** [comment]
This has been implemented. Further improvements via PRs please.
