### ISSUE TITLE
Trailing dot is returned for formatFloat with precision 0

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#12586]
`strututils.formatFloat` returns a trailing dot when using `precision = 0`.

### Example
```nim
import strutils
echo formatFloat(2.123, ffDecimal, precision = 0)
```

### Current Output
```
2.
```

### Expected Output
```
2
```
### Additional Information
With the JS backend the expected result is returned. Tested with latest devel.

**Comment by mratsim** [comment]
I don't really mind the trailing dot, it actually reminds me that I'm using floats.
It seems like Python does remove it as well though and AFAIK we want to be Python-like for formatting.
```
a = 3.14159

print(f'{a:.0f}')
print('%.0f' % a)
print("{0:.0f}".format(a))
```

**Comment by juancarlospaco** [comment]
Maybe you want to format a float for SASS for example.
