### ISSUE TITLE
function return enum type cause wrong.

### ISSUE THREAD

**Issue by huaxk** [nim-lang/Nim#12589]
enum type return wrong.

### Example
```nim
type
  OGRwkbGeometryType* {.size: sizeof(cuint).} = enum
    wkbPoint25D = 0x80000001.cuint, wkbLineString25D = 0x80000002,
    wkbPolygon25D = 0x80000003

proc typ*(): OGRwkbGeometryType =
  return wkbPoint25D

echo typ()
```

### Current Output
```
-2147483647 (invalid data!)
```

### Expected Output
```
wkbPoint25D
```

### Possible Solution

* The enum type is a 32-bit cuint, which causes an error when the first bit is 1.

### Additional Information

*I working in version 1.0.2

```
$ nim -v
Nim Compiler Version 1.0.2 [Linux: amd64]
```

**Comment by Araq** [comment]
Wrappers are better off with ``distinct cuint`` types instead.

**Comment by huaxk** [comment]
Thanks, could you tell me more about it.

In addition, the following code：
```
echo OGRwkbGeometryType(wkbPoint25D.cuint)
```
output:
```
wkbPoint25D
```
but:
```
let v = wkbPoint25D.cuint
echo OGRwkbGeometryType(v)
```
raise exception:
```
Unhandled exception: value out of range: 2147483649 [RangeError]
```
