### ISSUE TITLE
Add more types like zig has

### ISSUE THREAD

**Issue by bdezonia** [nim-lang/Nim#12596]
### Summary

zig supports more data types than nim. zig supports float16 and float128 and int/uint of any bit depth <= 64K. it would be great if nim expanded in this direction.

### Description

I have a java library (zorbage: https://github.com/bdezonia/zorbage) that supports many various types for numeric processing including some I'm requesting of nim. nim seems like a good target for a rewrite of my library. but zig is more attractive at the moment because of all the free types I'd get.

###  Alternatives

Other languages. Or else generating lots of unnecessary code in my nim app.

**Comment by demotomohiro** [comment]
There are nimble packages that provide larger ints/floats.
https://nimble.directory/search?query=numbers

**Comment by Araq** [comment]
Not planned, can be done as a library. The type zoo we inherited from C is already bad enough and hinders productivity.

**Comment by bdezonia** [comment]
That's too bad. I think zig is forward thinking on this issue. Nearly anything can be a library; that's not a real answer. The support of varied numeric types by a language, if the code is well designed, should not cause a lot drag on development.

**Comment by demotomohiro** [comment]
Why it should be supported by Nim language?

Nim has user defined operators. A library should be able to provide bigger int/float that 
works like primitive types in Nim language.

If supporting these type by a language was really good idea, Nim has to support not only big int/floats, but also vector, matrix, GUI, sound, major file formats, 2D, 3D, deep learning things, etc.
But I don't think Nim core team can support so many thing.
And building or install Nim would take very long time.

**Comment by bdezonia** [comment]
I think I've misunderstood what a library is in nim versus other languages. If the language syntax can be extended/integrated with libraries via operators then maybe it doesn't need to be in the language.

**Comment by bdezonia** [comment]
Just a note that I read on reddit (I misplaced the link, sorry) that C and C++ are considering things like uint13, int21, etc. with a good chance the proposal will go through. Their bit limits were significantly beyond 64K.

**Comment by Araq** [comment]
The required additions for ``printf`` alone will demonstrate how bad of an idea this really is.

**Comment by bdezonia** [comment]
If other languages are implementing such a feature (C and C+ who btw both support printf and apparently Zig is trying to also) maybe you should consider if some of your approaches need reconsideration. I am not a Nim user so I can't really speak to it. But if something other languages are tackling is impossible in your design then maybe take note.

**Comment by Araq** [comment]
It's "not impossible in my design", we can implement it too, but it's simply bad design.
