### ISSUE TITLE
'when' ignores duplicated cases silently with no warning when compiling

### ISSUE THREAD

**Issue by kraptor** [nim-lang/Nim#12623]
When using 'when' with multiple cases in a generic proc, should there be 2 (or more cases) covering the same condition only the first is used, silently discarding other cases with no warning at all.

### Example
```nim
import strformat

proc test[T:uint32|uint16](value: T) =
  when T is uint32:
    echo fmt"32: {value}"
  elif T is uint16:
    echo fmt"16: {value}"
  elif T is uint32:
    echo "I was expecting a compiler warning here, as the 'when' already covered this case before."
    echo "But this case is silently ignored."
  else:
    discard
 
test(12'u32)
test(12'u16)
```

### Current Output
```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: in [Processing]
Hint: strformat [Processing]
Hint: macros [Processing]
Hint: parseutils [Processing]
Hint: unicode [Processing]
Hint: strutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_assertions.nim.c.o /usercode/nimcache/stdlib_assertions.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_io.nim.c.o /usercode/nimcache/stdlib_io.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_system.nim.c.o /usercode/nimcache/stdlib_system.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_parseutils.nim.c.o /usercode/nimcache/stdlib_parseutils.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_strutils.nim.c.o /usercode/nimcache/stdlib_strutils.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/stdlib_strformat.nim.c.o /usercode/nimcache/stdlib_strformat.nim.c [Exec]
Hint: gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/@min.nim.c.o /usercode/nimcache/@min.nim.c [Exec]
Hint:  [Link]
Hint: operation successful (28420 lines compiled; 1.771 sec total; 37.785MiB peakmem; Debug Build) [SuccessX]

32: 12
16: 12
```

### Expected Output
Some kind of warning/hint regarding a duplicated case in when.

### Possible Solution

I don't know.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-22
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 193b3c66bbeffafaebff166d24b9866f1eaaac0e
active boot switches: -d:release
```

**Comment by Araq** [comment]
Oh come on, a compiler cannot detect every piece of bad code.

**Comment by kraptor** [comment]
I understand you work really hard on this and that this would most probably be a 'won't fix' but I don't understand harsh comments, tbh. 

That is something you have to improve on or you may expel people otherwise willing to contribute. 

I don't really care as I've been working with many benevolent dictators in foss projects, but others may not understand that kind of behavior and think Nim community is toxic when it isn't.

**Comment by bluenote10** [comment]
@kraptor To clarify: `when` behaves exactly like `if` (in I guess almost any other language):

```
if x == 1:
  echo "one"
elif x == 1:
  echo "also one"
```

A branch with a duplicated condition is always "silently ignored".

**Comment by kraptor** [comment]
@bluenote10 Thank you for the clarification. I really understand.

But then, this statement in the docs doesn't hold true anymore:

```The statements that belong to the expression that evaluated to true are translated by the compiler, the other statements are not checked for semantics! However, each condition is checked for semantics.```

Then, this should be rewritten something like:

``` Only the first statement that belong to the expression that evaluated to true are translated by the compiler, the other statements are not checked for semantics! However, each condition is checked for semantics.
```

Reference: https://nim-lang.org/docs/manual.html#statements-and-expressions-when-statement

**Comment by bluenote10** [comment]
The example is indeed a bit misleading, because it speaks of "statements" plural although the active branch in the example only has a single expression. I think what it is trying to say is:
- All conditions must be semantically correct.
- In the active / true branch, all statements must be semantically correct.

**Comment by Araq** [comment]
> I understand you work really hard on this and that this would most probably be a 'won't fix' but I don't understand harsh comments, tbh.

I don't see where I was harsh tbh.
