### ISSUE TITLE
`is` operator won't recognize procs

### ISSUE THREAD

**Issue by StasRuinsEverything** [nim-lang/Nim#12622]
Hello! Here's a strange one:
All the checks return `false`, when I'd expect them to return `true`:
```nim
proc dummy() = echo "dummy"

type Dummy = proc()                      

echo typeof(dummy)                       #proc (){.gcsafe, locks: 0.}

echo dummy is Dummy                      #false
echo dummy is proc()                     #false
echo (proc() = echo "dummy") is proc()   #false
```

On the other hand, this works as expected:
```nim
proc dummy() = echo "dummy"

type Dummy = proc()       
               
let p: Dummy = dummy
let q: Dummy = (proc() = echo "dummy")

echo p is proc()                         #true
echo p is Dummy                          #true
echo q is proc()                         #true
echo q is Dummy                          #true
```

Compiler version:
```
$ nim -v
Nim Compiler Version 1.0.0 [Windows: i386]
```
[EDIT]

This bug seems to be present all the way down to at least v0.13.0

**Comment by demotomohiro** [comment]
It is not a bug.

Quote from
https://nim-lang.org/docs/manual.html#types-procedural-type

> A subtle issue with procedural types is that the calling convention of the procedure influences the type compatibility: procedural types are only compatible if they have the same calling convention. As a special extension, a procedure of the calling convention nimcall can be passed to a parameter that expects a proc of the calling convention closure.

> Nim supports these calling conventions:

> `nimcall`
> is the default convention used for a Nim proc. It is the same as fastcall, but only for C compilers that support fastcall.
> `closure`
> is the default calling convention for a procedural type that lacks any pragma annotations. It indicates that the procedure has a hidden implicit parameter (an environment). Proc vars that have the calling convention closure take up two machine words: One for the proc pointer and another one for the pointer to implicitly passed environment.


Test code:
```nim
import macros

proc dummy() = echo "dummy"
type Dummy = proc()
let o = dummy
let p: Dummy = dummy
let q: Dummy = (proc() = echo "dummy")
let r = (proc() = echo "dummy")

echo typeof(dummy)
echo proc()

doAssert dummy is proc() {.nimcall.}
doAssert Dummy is proc() {.closure.}
doAssert o is proc() {.nimcall.}
doAssert p is proc() {.closure.}
doAssert q is proc() {.closure.}
doAssert r is proc() {.nimcall.}
```

**Comment by StasRuinsEverything** [comment]
My bad. Guess it's time for me to re-read the manual.
