### ISSUE TITLE
osproc: support for passing arbitrary fds to child processes

### ISSUE THREAD

**Issue by mikroskeem** [nim-lang/Nim#12628]
### Summary
Support for passing arbitrary file descriptors to child processes in `startProcess`

### Description
Let's consider a scenario where child process needs to write to a file descriptor - e.g special network socket, file handle etc. opened by parent process. One example is Xvfb - e.g when you run command `Xvfb -displayfd 3`, it'll write selected display number into fd 3.
While Xvfb can freely write that number into fd 1 or 2 (stdout/stderr), then I think that they are for more general-purpose logging than for actually grabbing the important data in my case.

Besides, I can do that freely in C using `execv`* and `fork` - the fd opened in parent process gets freely passed to child process (unless I use `O_CLOEXEC` or close it manually).

### Alternatives

Writing own `startProcess` function, but that means a lot of copy-pasting.

### Additional Information

None?

**Comment by demotomohiro** [comment]
Following code worked in my ubuntu machine.
It open a file, get the file discriptor from it and pass it to read command in bash.

```nim
#Text comes from here
import osproc, streams

let
  f = open("prog.nim")
  fd = getFileHandle(f)
  p = startProcess("/bin/bash", args = ["-c", "read -u " & $fd & ";echo $REPLY"])
  strm = p.outputStream

doAssert p.waitForExit == 0
echo strm.readAll
p.close
f.close
```

**Comment by mikroskeem** [comment]
Interesting... Maybe I'm doing something wrong with `memfd_create` then :smile: I'll keep the issue open for now if I figure out the issue.

**Comment by mikroskeem** [comment]
I'm unable to pass fd created by memfd_create to child process though 😕 

```nim
proc c_memfd_create(name: cstring, flags: cint): cint {.header: "<sys/mman.h>", importc: "memfd_create".}

let fd = c_memdf_create("test", 0)
```

Let's say fd=3, then that fd does not appear in /proc/childpid/fd (virtual) directory. More interesting is that if child process opens files on its own then fd number 3 will be skipped (so 0, 1, 2, 4, 5... etc are open).

Am I doing something wrong?
