### ISSUE TITLE
Compiler should complain if you `except` something that doesn't exist

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12638]
### Example
```nim
import std / strutils except editdstance # looks almost like `editdistance`!
```

### Current Behaviour
Compiler doesn't complain and imports `editdistance`

### Expected Output
Compiler should either refuse to compile, or at least warn about the typo

```
$ nim -v
Nim Compiler Version 1.0.2
```

**Comment by nc-x** [comment]
Quoting from https://github.com/nim-lang/Nim/pull/10023#discussion_r242288497, `import x except doesntExist is valid for forward and backward compatibility reasons.`

**Comment by Araq** [comment]
Works as designed and the spec gives the reason for this behaviour.
