### ISSUE TITLE
C-backend link failure for let with {.global, compileTime.} pragma

### ISSUE THREAD

**Issue by foldl** [nim-lang/Nim#12640]
When defining a `let` value with `{.global, compileTime.}` pragma on C-backend, linker reports that
the value is not defined.

### Example
```nim
proc doIt(a: openArray[int]) = discard

proc foo() = 
  let bug {.global, compileTime.} = [1,2,3]
  doIt(bug)

if isMainModule:
  foo()
```

### Current Output
```
... undefined reference to `bug__maw0iw4sXYmMR4fqohWCPA'
```

### Expected Output
```
Program can be built successfully.
```

### Possible Solution

N/A.

### Additional Information

N/A

```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
```

**Comment by kaushalmodi** [comment]
Should the "expected output" be a better error? Because `let` variables are assigned values at runtime and not at compile time.

**Comment by kaushalmodi** [comment]
I mean that if one needs compile time car, they can just use `const`, right?

**Comment by foldl** [comment]
If nim don't allow this, it should report error. Or, it should generate proper C  code. Isn't it?

**Comment by kaushalmodi** [comment]
@foldl Yes, that's what I said.. that this probably should be a good user-friendly error.

I am not an expert at this, but I'd do this if I wanted a proc to have a compile-time constant: https://play.nim-lang.org/#ix=21t1.

**Comment by kaushalmodi** [comment]
On the other hand, the manual does say that the `{.compileTime.}` pragma is designed for variables too: https://nim-lang.github.io/Nim/manual.html#pragmas-compiletime-pragma. So may be the bug is with the use of that pragma inside procs.. because this works: https://play.nim-lang.org/#ix=21t2.
