### ISSUE TITLE
stdalign.h is not available in Visual Studio

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#12656]
Visual studio is one of those weird ones. it is C++/14 standard compliant but not C11 standard compliant.  I have tested it with VS2015, not sure if situation has improved in later VS versions.

For C++ it is easy, we can just write in nimbase.h because alignas is keyword in C++:
#ifndef __cplusplus
#include <stdalign.h>
#endif

But in order to save C builds looks like `__declspec(align(X))`  will be required

**Comment by Araq** [comment]
Fixed.
