### ISSUE TITLE
File-specific compilation flags

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12662]
As mentioned a long time ago on IRC and here https://github.com/nim-lang/Nim/issues/11202#issuecomment-492172071 file-specific compilation flags would be useful.

Currently I have to maintain a complex cfg and/or nimble files with variations for Windows/Mac/Linux + making sure that the compiler doesn't compile a SSE2 file with AVX2 otherwise the SSE2 platform will not get SSE2 SIMD.

https://github.com/numforge/laser/blob/3c3c6f526d877cb8fdb7c8bf6e0f0867259e6a42/nim.cfg#L18-L37
https://github.com/mratsim/Arraymancer/blob/master/arraymancer.nimble#L40-L81

This would be useful for:
- restricting CUDA/OpenCL compilation to specific files as the compilers sometime break on things that GCC/Clang support. And it also requires stripping all compilation flags of Nim and the users and me maintaining parity with the official Nim.cfg
- allow me to mix SSE2 and AVX in the same codebase. I can use the GCC Function attribute `__attribute(target('avx'))` as a workaround with codegendecl but it also forces me to rewrite all Nim macros like N_INLINE, N_CLOSURE, ... see https://github.com/nim-lang/Nim/issues/10682
- avoid people being confused when import or copy my code: https://github.com/numforge/laser/issues/22
- having file-level fast-math when the loss of precision is acceptable and the normal behaviour otherwise.

I'm not alone in needing this:
- see @zacharycarter and @genotrance for GLSL: https://irclogs.nim-lang.org/06-11-2018.html#16:38:40
- @slomp: https://irclogs.nim-lang.org/09-10-2018.html and https://irclogs.nim-lang.org/26-02-2019.html#15:27:04

@Araq I couldn't find the last discussion (April) where you said that it was planned for the future, so tracking here so that it's not forgotten.

**Comment by slomp** [comment]
Related: idea for `push/pop` pragmas to work with `passC` pragmas et al.:
https://irclogs.nim-lang.org/09-10-2018.html#21:19:24

**Comment by timotheecour** [comment]
one example use case among many: it would allow compiling different nim files with different modes, eg: `nim c`, `nim cpp`, `nim objc` and linking all them together. In particular it would simplify https://github.com/nim-lang/Nim/issues/12653#issuecomment-553779201 by compiling the objective C code inside nimextras_objc (as an emit statement inside a nim program) as `nim objc`  so there wouldn't be a separate compilation step needed for that `nimextras_objc.mm`.

**Comment by slomp** [comment]
> it would allow compiling different nim files with different modes, eg: `nim c`, `nim cpp`, `nim objc` and linking all them together.

Hi @timotheecour 
Would you mind elaborating a bit more on that?
Suppose I have a set of `.c` files, a set of `.cpp` files, and a set of `.mm` files, and that I have some nim files (say, `cfiles.nim`, `cppfiles.nim` and `mmfiles.nim`) that call the appropriate compile/pass pragmas. How do you tell nim to generate objects out of each of them and then subsequently link those objects together into an executable?
( I know this Issue is closed, but I'm really curious :) )
