### ISSUE TITLE
[JS] Confusing error message

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12671]
Function `echo` outputs the wrong string.

### Example
```nim
proc foo =
  var x: seq[int]
  inc x[0]

foo()
```

### Current Output
```
Uncaught TypeError: Cannot read property 'length' of null
    at foo_42003 (x.js:531)
    at x.js:536
```
### Expected Output
Information that no element of such index exists

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.2
```

**Comment by metagn** [comment]
Now gives `index out of bounds, the container is empty`
