### ISSUE TITLE
base64 changes break code

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#12675]
The base64 changes in #12436 are breaking changes in the stdlib and at least two packages are affected. It's very likely that most usages of base64 are affected. We should provide a deprecation path.

### Example in Nim JWT
```
/Users/dom/other_projects/nim-jwt/jwt/private/utils.nim(21, 25) Error: type mismatch: got <openArray[byte], newLine: string>
but expected one of: 
proc encode[T: SomeInteger | char](s: openArray[T]): string
  first type mismatch at position: 2
  unknown named parameter: newLine
1 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them
```

**Comment by disruptek** [comment]
I patched Yuriy's fork of jwt and it now works in 1.0 and devel, but yes, this seems like it was avoidable and it was annoying because it broke Google API signing in gcplat.

**Comment by Araq** [comment]
One year later and I hope people have patched the code by now.
