### ISSUE TITLE
Symbol binding bug with generics and template

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#12683]
This doesn't compile but probably should:

### Example
module `A.nim`
```nim
import B
heh(0..40, "|")
```
module `B.nim`
```nim
import unicode
#  v---change to proc to make it compile
template toRune(s: string): Rune = s.runeAt(0)
#     v---works if not generic
proc heh*[T](x: Slice[T], chars: string) = discard chars.toRune
```

### Current Output
```
Error: attempting to call undeclared routine: 'runeAt'
```

### Expected Output
```
Hint: operation successful
```

```
$ nim -v
Nim Compiler Version 1.1.1 (#devel)
```

**Comment by mratsim** [comment]
Mentioned in the manual, you should not use method call syntax in templates

```
import unicode
#  v---change to proc to make it compile
template toRune(s: string): Rune =
  runeAt(s, 0)

#     v---works if not generic
proc heh*[T](x: Slice[T], chars: string) = discard chars.toRune
```

**Comment by Clyybber** [comment]
But the compiler could do symbol lookup and typechecking at instantiation on the `chars` parameter just fine, because the `char` parameter is not a generic.
I guess this would require some kind of partial instantiation of the generics body.
Anyways this can and should work IMO.

**Comment by Araq** [comment]
The limitations only affect ``untyped`` parameters.

**Comment by mratsim** [comment]
I guess with have to put that in the https://github.com/nim-lang/Nim/issues/8677 bucket along with its new friends https://github.com/nim-lang/Nim/issues/6387, https://github.com/nim-lang/Nim/issues/11800, https://github.com/nim-lang/Nim/issues/11811, https://github.com/nim-lang/Nim/issues/11947

**Comment by metagn** [comment]
Seems to work in 2.0
