### ISSUE TITLE
unhandled exception: 'Z' is not a valid pattern in httoclient.lastModified

### ISSUE THREAD

**Issue by zaphodef** [nim-lang/Nim#12692]
Reproducible with the following code:

```nim
import httpclient
discard lastModified(new Response)
```

When compiling, it will return the following error: `Error: unhandled exception: 'Z' is not a valid pattern [TimeFormatParseError]`

The error comes from parsing, as you can see running the following snippet:
```nim
import times
discard parse("12 Feb 2019", "dd MMM yyyy")
discard parse("12 Feb 2019 Z", "dd MMM yyyy Z")  # will crash at compilation
```

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
git hash: a88004114d6bfbef31268c96f4d1fc871e70ab03
active boot switches: -d:release
```

**Comment by juancarlospaco** [comment]
The error is really on `times.parse` isnt it?.

**Comment by GULPF** [comment]
The pattern used in `httpclient` is wrong and the error message is correct. Based on [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified), the call to parse should look like this: `parse(lastModifiedHeader, "ddd, dd MMM yyyy HH:mm:ss 'GMT'", utc())`

**Comment by zaphodef** [comment]
I took the liberty of making a PR :)
