### ISSUE TITLE
detectOs doesn't find Ubuntu 18.04

### ISSUE THREAD

**Issue by ArMour85** [nim-lang/Nim#12691]
Hello,

The function **detectOs** doesn't work to detect Ubuntu version 18.04. In **distros.nim** the command used to detect Ubuntu OS is **uname -o** (see **template uname()**) return **GNU/Linux** but never with Ubuntu.

### Check
```nim
echo "Is Ubuntu ?"
if detectOs(Ubuntu):
  echo "Yes"
else:
  echo "No"
```
### Possible Solution
For Ubuntu replace **uname -o** by **cat /etc/issue** because this command return "Ubuntu 18.04.3 LTS".

**Comment by Araq** [comment]
Fixed in devel.
