### ISSUE TITLE
Destructor doesn't work for structural equivalence of tuples

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1269]
This compiles (fresh 0.9.5):

```
type
  t1 = tuple [i : int, j : int]
  t2 = tuple [i : int, j : int]

proc destruct(t: t1) {.destructor.} =
  echo "destructor"

block:
  echo "start"
block:
  var t : t1
block:
  var t : t2
block:
  echo "done"
```

and produces:

```
start
destructor
done
```

The destructor is _not_ called for the second variable of t2 type. This feels as bug, common function overloading works for such types

When  I defined second destructor it resulted in a really strange compiler message:

> Error: pragmas are only allowed in the header of a proc

```
type
  t1 = tuple [i : int, j : int]
  t2 = tuple [i : int, j : int]

proc destruct(t: t1) {.destructor.} =
  echo "destructor"

proc destruct(t: t2) {.destructor.} =
  echo "destructor2"
```

**Comment by andreaferretti** [comment]
If I try this today (with `--newruntime`):

```nim
type
  T1 = tuple [i : int, j : int]
  T2 = tuple [i : int, j : int]

proc `=destroy`(t: var T1) =
  echo "destructor"

block:
  echo "start"
block:
  var t : T1
block:
  var t : T2
block:
  echo "done"
```

I get the error `signature for '=destroy' must be proc[T: object](x: var T)` which means that in fact destructor **are** only allowed for `object` now.

Should we close this?

**Comment by Araq** [comment]
Ok.
