### ISSUE TITLE
Keyword var ignored in tuple definition

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1270]
I wrote:

```
type T = tuple [i : int, xx : var T]
```

and it compiled. (I intended to write `ref` instead of `var`.) Only when I tried to instantiate the type it announced an error:

>  Error: invalid type: 'T'

It feels like semantic check is delayed way too much.

**Comment by Yardanico** [comment]
@Araq this code now gives "test.nim(1, 6) Error: illegal recursion in type 'T'", which I think is good enough error message
