### ISSUE TITLE
Unittest Syntax Seems Strange (Looking for Common Thread)

### ISSUE THREAD

**Issue by jjzmajic** [nim-lang/Nim#12710]
Why does `unittest` use colons like so:
```nim
suite "description for this stuff":
  echo "suite setup: run once before the tests"
  
  setup:
    echo "run before each test"
  
  teardown:
    echo "run after each test"
  
  test "essential truths":
    # give up and stop if this fails
    require(true)
```
Unlike python, nim seems to favour `=` for declaring everything, including procs such as
```nim
proc getWelcomeMessage*(): string =
    "Hello, World!"
```
over
```nim
proc getWelcomeMessage*(): string: 
    "Hello, World!"
```

Wouldn't  it be more consistent for tests to be declared like so:
```nim
  test "essential truths" =
    # give up and stop if this fails
    require(true)
```

Or is there a reason for this that I am missing?

**Comment by mratsim** [comment]
The unittest uses common Nim syntax.

If you create any template with

```Nim
template myNiftyTemplate(name, string: body: untyped): untyped =
  echo "Entering the main body \"" & name & "\"" 
  body
  echo "Exiting"
```

You can call it with

```Nim
myNiftyTemplate "description for this stuff":
  echo "suite setup: run once before the tests"
```

This is consistent with the syntax of blocks:
`static`, `defer`, code `block`, `if`/`elif`/`else`, `case` block, `when`, `macro`, `try`/`finally`, `while` and `for`.

`=` are only used for proc definition and assignation, the common block scope is opened with colons `:`.

**Comment by jjzmajic** [comment]
Thanks for the clarification!
