### ISSUE TITLE
Unnamed distinct type

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1272]
This compiles:

```
type
  T = tuple [i : int, xx : distinct ptr T]

var n : t
#n.xx = addr n # if uncommented it fails to compile - types are distinct
```

It looks I created unnamed distinct type that cannot be used. I am not sure whether this trick makes any sense or whether it is an error. 

Perhaps distinct type should always require explicit name in `type` section.

**Comment by narimiran** [comment]
> This compiles:

It doesn't anymore.

> the compiler should warn you if not abort

`Error: illegal recursion in type 'T'`
