### ISSUE TITLE
Surprising behaviour of compileTime variables "modified" at runtime

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12729]
### Example
```nim
var x {.compileTime.} = 123
echo x
inc x
echo x
```

### Current Output
```
123
123
```

### Expected Output
Either a compile-time error or the value of `x` getting modified

### Other
```
$ nim -v
Nim Compiler Version 1.0.2
```

**Comment by narimiran** [comment]
I can confirm the reported output on v1.0.2 and v1.0.4, but in the latest devel (v1.1.1) the output is:

```
123
124
```

I'm closing this as solved.
