### ISSUE TITLE
VM instruction addressing limitation: Error: internal error: (filename: "vmgen.nim", line: 179, column: 16)

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#12727]
@sealmove reported a VM internal error when trying to run a relatively large piece of Npeg-generated code in at compile time, which I'm able to reproduce. The assert comes from this snippet:

```
                                         
proc patch(c: PCtx, p: TPosition) =                            
  # patch with current index                                                              
  let p = p.int           
  let diff = c.code.len - p        
  #c.jumpTargets.incl(c.code.len)
  internalAssert(c.config, -0x7fff < diff and diff < 0x7fff)    # <----- There you have it
  let oldInstr = c.code[p]                                               
  # opcode and regA stay the same:                                       
  c.code[p] = ((oldInstr.uint32 and 0xffff'u32).uint32 or                
               uint32(diff+wordExcess) shl 16'u32).TInstr  
```

As far as my limited understanding goes, it seems that the Nim VM only allows relative addressing up to 32Kbytes VM instructions, larger offsets do not fit in to the IM opcode format.

Reproduce by trying to compile this example: http://ix.io/22KC/nim (a protobuf IL compiler in npeg)

**Comment by sealmove** [comment]
A somewhat simpler example which runs on Nim playground as is: https://play.nim-lang.org/#ix=22KQ

**Comment by zevv** [comment]
And a minimal example:

```
import macros

                                        
static:    
  macro foo(): untyped =
    let s = newStmtList()                      
    for i in 1..16384:
      s.add nnkCommand.newTree(
        newIdentNode("echo"),  
        newLit(i)              
      )                        
    newTree(nnkWhileStmt, ident "true", s)
                                          
  foo() 
```

Change the iteration count to 16383 and things work again.

**Comment by mratsim** [comment]
I think metaprogramming in Nim has been a bit too convenient and we should create a forum thread or a RFC to discuss our needs.

I will probably also hit those limits with my linear algebra / high-performance computing / image processing / deep-learning compiler (https://github.com/numforge/laser/tree/master/laser/lux_compiler)

Unfortunately the compiler as library / DLL option is not focused on at the moment (https://github.com/nim-lang/Nim/issues/12293) but it would probably be much faster to compile DSLs and it would scale to complex code-generation.
