### ISSUE TITLE
Cannot take the compile-time sizeof Atomic types

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12726]
`sizeof` doesn't work for types that store Atomics. This would be useful to size the memory buffer for thread-safe memory allocators with what is left from the synchronization primitives.

```Nim
import std/atomics

type
  Node = ptr object
    # works
    next: Atomic[pointer]

  MyChannel = object
    # type not defined completely
    back: Atomic[ptr int]

static:
  echo sizeof(Node)
  echo sizeof(MyChannel)
```

The workaround is to add a "raw" field for all the trivial types with their actual types so that sizeof works.

There is a similar concern for Locks and Condition Variables though I don't think there is an easy way to make sizeof deduce their size.

**Comment by shirleyquirk** [comment]
This is simple for the c backend, but i'm totally stumped on C++.
For C, it's as simple as annotating each imported type with {.size:N.}
i.e.
```nim
AtomicInt8 {.importc: "_Atomic NI8", size:1.} = object
```
(maybe {.completeStruct.} is necessary too, needs more testing.)

for C++ sizeof(std::atomic<T>)==sizeof(T), locks don't take up any space, very simple.
So this would be nice:
```nim
when defined(cpp):
   type Atomic*[T]{.importcpp: "std::atomic", size:sizeof(T).} = object
```
but it would require changing {.size.} to accept more than just 1,2,4, or 8, which is probably a bad idea? 
and also injecting ``T`` inside the pragma, which i guess would be nice to have.

that all seems a bit much for a small feature

@mratsim would this be useful if it were just on the c backend?

**Comment by mratsim** [comment]
> but it would require changing {.size.} to accept more than just 1,2,4, or 8, which is probably a bad idea?
> and also injecting `T` inside the pragma, which i guess would be nice to have.

Not necessarily a bad idea, but it would need test. In particular it would help wrapping SIMD and int128 has opaque types https://github.com/nim-lang/Nim/issues/7674

The workaround that should work is this:

```Nim
type Atomic*[T]{.importcpp: "std::atomic".} = object
  raw: T
```
