### ISSUE TITLE
sizeof default in type section fails with concept

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12720]
In a similar vein to #12714 and #12636 

```Nim
const CacheLineSize = 128

type
  Enqueueable = concept x, type T
    x is ptr
    x.next is Atomic[pointer]

  MyChannel*[T: Enqueueable] = object
    pad: array[CacheLineSize - sizeof(default(T)[]), byte]
    dummy: typeof(default(T)[])
```

```
.../bug_sizeof.nim(9, 46) template/generic instantiation of `default` from here
../.choosenim/toolchains/nim-1.0.2/lib/system.nim(1818, 16) Error: invalid type: 'T: Enqueueable' in this context: 'proc (T: type T: Enqueueable): T: Enqueueable{.noSideEffect.}' for proc
```

Unfortunately there is no workaround since typedesc are now NimNode in macros (https://github.com/nim-lang/RFCs/issues/148 and https://github.com/nim-lang/Nim/pull/11400) and there is no way to convert in NimNode back into a typedesc (https://github.com/nim-lang/Nim/issues/6785)

Otherwise somehing like this would probably work
```Nim
macro sizeofDeref(T: typedesc): untyped =
  let x = default(T)[]
  result = newLit sizeof(x)
```

**Comment by metagn** [comment]
Seems to compile now with `import std/atomics` but no idea if just the code in the issue is a sufficient test
