### ISSUE TITLE
wrong `Error: cannot generate VM code` depending on unrelated code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12732]
very strange bug: we get a CT error `Error: cannot generate VM code` for valid code, and the CT error disappears when commenting out or making private an unrelated constant (or when using `currentPkgDir2()` instead of `currentPkgDir2`)

D20191124T182358

### Example
nim c t0796.nim

t0796.nim:
```nim
import t0796b
const s0 = currentPkgDir2
```

t0796b.nim:
```nim
import std/macros
const getPrivate3_tmp* = 0
const foobar1* = 0 # comment this or make private and it'll compile fine
macro foobar4*(): untyped =
  newLit "abc"
template currentPkgDir2*: string = foobar4()
macro currentPkgDir2*(dir: string): untyped =
  newLit "abc2"
```

### Current Output
```
t0796.nim(22, 12) Error: cannot generate VM code for currentPkgDir2
```

### Expected Output
should compile

### Additional Information
fails on all versions of nim, including recent devel f22d3c75aa68833ae1b01d747d0c71074ccef310

**Comment by metagn** [comment]
Now gives

```
t0796.nim(2, 12) Error: ambiguous identifier: 'currentPkgDir2' -- use one of the following:
  t0796b.currentPkgDir2: template (): string
  t0796b.currentPkgDir2: macro (dir: string): untyped{.noSideEffect, gcsafe.}
```

Is this fine?
