### ISSUE TITLE
existsDir,existsFile can't be used at CT (dirExists & fileExists can)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12733]
The docs for ` fileExists` are misleading: `Alias for existsFile proc.`  even though behavior is different:
existsDir,existsFile can't be used at CT (dirExists & fileExists can)

### Example
```nim
import std/os
const dir1 = dirExists(".") # ok
const dir2 = existsDir(".") # Error: cannot import symbol: S_ISDIR from current exe:

const f1 = fileExists(".") # ok
const f2 = existsFile(".") # Error: cannot 'importc' variable at compile time; stat
```

### Current Output
```
Error: cannot import symbol: S_ISDIR from current exe:
Error: cannot 'importc' variable at compile time; stat
```

### Expected Output
works

### Possible Solution
adjust vmops

### Additional Information
nim recent devel f22d3c75aa68833ae1b01d747d0c71074ccef310

**Comment by ringabout** [comment]
Since `existsFile` and `existsDir` in os are deprecated, this issue can be closed.
