### ISSUE TITLE
exportcpp needs to support const/ref argument modifiers

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12730]
There is currently no easy way to declare a c++ signature that involves const (or && or &) arguments, eg:
this doesn't work:
```nim
proc fun1*(msg: cstring) {.exportcpp: "void fun1(const char*msg)".} = discard
```

I found the following workaround, but it's far from ideal because:
* it involves generating a new type `cstring2` just to get a `const` modifier for `char*`
* it'll lead to different (ie incompatible) types if these `type cstring2 {.importcpp:"const char*".} = cstring`  are redefined in 2 nim modules, even though it should be the same type mapping to `const char*`
* it involves having to cast back to cstring, see below:

### Example
```nim
type cstring2 {.importcpp:"const char*".} = cstring
proc fun1*(msg: cstring2) {.exportcpp.} =
  let msg2 = cast[cstring](msg) # cast needed other CT error
  echo msg2

proc fun2() {.importc.}

{.emit:"""
void fun1(const char*msg);
NIM_EXTERNC void fun2(){
  fun1("abc");
}
""".}

proc main()=
  fun1("asdf")
  fun2()

main()
```

### Possible Solution
support this:
```nim
proc fun1*(msg: cstring) {.exportcpp: "void fun1(const char*msg)".} = discard

# should also support the usual substitutions as is case for importcpp (#, $1 etc)
proc fun1*(msg: cstring, msg: cstring) {.exportcpp: "void fun1(const char*msg, #)".} = discard
```
also, would make it easier to port from C++ declaration

Note: this would be similar to importcpp syntax which supports this:
```nim
proc strEnd(cstr: WideCString, c = 0'i32): WideCString {.importcpp: "(NI16*)wcschr((const wchar_t *)#, #)", header: "<string.h>".}
```

## note
I had also thought of the following proposal (in addition to main proposal above), but that is not as flexible, as it wouldn't distinguish between `const char*` and `char const*` etc, and would be more complicated to implement than main proposal

```nim
# maps to void fun1(const char* msg);
proc fun1*(msg: cstring {.importcpp:"const")) {.exportcpp.} = discard

# also works for return type
# maps to void*& fun1(const char* msg);
proc fun1*(msg: cstring {.importcpp:"const")): pointer {.importcpp:"&".} {.exportcpp.} = discard
# note: no cast should be needed here
```

**Comment by Araq** [comment]
Would ``.codegenDecl`` work for this?

**Comment by timotheecour** [comment]
codegenDecl does indeed help, thanks; however it's still not as good as could be:

* `cast[cstring](msg)` is still needed even though we have: `static: doAssert msg is cstring` ; so the type system seems subverted
* I don't see how to use `$i` to access ith argument inside codegenDecl (instead, have to re-state each argument, except for return value, this one works

```nim
  proc fun1*(msg: cstring, b: bool) {.exportcpp, codegenDecl: "$1 $2(const char*msg, bool b)".} =
    static: doAssert msg is cstring
    echo ("in fun1", cast[cstring](msg), b)
  proc fun2() {.importc.}

  {.emit:"""
  void fun1(const char*msg, bool b);
  NIM_EXTERNC
  void fun2(){
    fun1("abc", true);
  }
  """.}

  proc main()=
    fun1("asdf", false)
    fun2()

  main()
```

**Comment by jmgomez** [comment]
This can be closed as with `member` you can define a functor and pass it around (see the last example) https://nim-lang.github.io/Nim/manual_experimental.html#member-pragma
