### ISSUE TITLE
assignment of objects erroneously zeroed LHS before object construction on the RHS

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#12753]
When assigning an object constructor to an object, the left hand side got zeroed before the object construction happens.  Thus it gives wrong results, when the right hand side uses the left hand side object in the constructor.

### Example
```nim
type
  V = object
    v:array[2,float]
  M = object
    v:array[2,V]

var
  a = M(v:[ V(v:[0.0,1.0]), V(v:[2.0,3.0]) ])
  b = M(v:[ V(v:[0.0,0.1]), V(v:[0.2,0.3]) ])

echo M(v: [V(v: [b.v[0].v[0] + a.v[0].v[0], b.v[0].v[1] + a.v[0].v[1]]),
       V(v: [b.v[1].v[0] + a.v[1].v[0], b.v[1].v[1] + a.v[1].v[1]])])
b = M(v: [V(v: [b.v[0].v[0] + a.v[0].v[0], b.v[0].v[1] + a.v[0].v[1]]),
      V(v: [b.v[1].v[0] + a.v[1].v[0], b.v[1].v[1] + a.v[1].v[1]])])
echo b
```

### Current Output
```
(v: [(v: [0.0, 1.1]), (v: [2.2, 3.3])])
(v: [(v: [0.0, 1.0]), (v: [2.0, 3.0])])
```

### Expected Output
```
(v: [(v: [0.0, 1.1]), (v: [2.2, 3.3])])
(v: [(v: [0.0, 1.1]), (v: [2.2, 3.3])])
```

### Possible Solution

Have to save the RHS to a separate object before assigning back to the intended LHS.

### Additional Information

* It was working in version 0.16.0.  I'm not sure when it starts to break.

```
$ nim -v
Nim Compiler Version 1.0.4 [MacOSX: amd64]
Compiled at 2019-11-25
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 97e0ce3c75c9348226ea1fcdfc601c6fbe5c0e75
active boot switches: -d:release
```

Edit: updated the example without template, as the issue is not about template.

**Comment by nc-x** [comment]
Took a quick look at this. 
The generated C code contains unnecessary (I think) `nimZeroMem()` for both `a` and `b`. The `nimZeroMem()` comes from -
https://github.com/nim-lang/Nim/blob/b0c06aa7110fc46d3158b620f07aba33b6cd9976/compiler/cgen.nim#L404-L407
Removing this code fixes this issue (but probably breaks other stuff).

**Comment by jxy** [comment]
OK.  It's not about template at all.  The following gives a wrong result in `b`.

```nim
type
  V = object
    v:array[2,float]
  M = object
    v:array[2,V]

var
  a = M(v:[ V(v:[0.0,1.0]), V(v:[2.0,3.0]) ])
  b = M(v:[ V(v:[0.0,0.1]), V(v:[0.2,0.3]) ])

echo M(v: [V(v: [b.v[0].v[0] + a.v[0].v[0], b.v[0].v[1] + a.v[0].v[1]]),
       V(v: [b.v[1].v[0] + a.v[1].v[0], b.v[1].v[1] + a.v[1].v[1]])])
b = M(v: [V(v: [b.v[0].v[0] + a.v[0].v[0], b.v[0].v[1] + a.v[0].v[1]]),
      V(v: [b.v[1].v[0] + a.v[1].v[0], b.v[1].v[1] + a.v[1].v[1]])])
echo b
```

So `b` got wiped clean before the object construction happens.

**Comment by jxy** [comment]
I have updated the issue description for the issue is not related to templates.

**Comment by Araq** [comment]
@nc-x The codegen does alias analysis in other cases to prevent that from happening. But it might not be up for the task. The general idea is: 

- Detect partial self-assignments.
- If a partial self-assign, fill in a temporary with the data and then copyMem the temporary into the final location.

Note that reseting the memory to all zero is required for partial object construction where some fields are not specified...
