### ISSUE TITLE
Different raises behaviour for newTerminal between Linux and Windows

### ISSUE THREAD

**Issue by kdeme** [nim-lang/Nim#12759]
It seems there is a different raises behaviour for [newTerminal()](https://github.com/nim-lang/Nim/blob/devel/lib/pure/terminal.nim#L44)

### Example
```nim
import terminal

proc test() {.raises:[IOError, ValueError].} =
  setBackgroundColor(stdout, bgRed)

test()
```

This will compile on Linux, but not on Windows. Error:

```
C:\Users\deme\repos\getterminalraises.nim(3, 22) template/generic instantiation from here
C:\Users\deme\repos\Nim\lib\pure\terminal.nim(44, 24) Error: can raise an unlisted exception: Exception
```
`setBackgroundColor` used as example here but it will fail on many more. Spotted this when using logging from nim-chronicles.

`Nim Compiler Version 1.0.2 [Windows: amd64]` & `Nim Compiler Version 1.0.2 [Linux: amd64]`

A similar error was seen and fixed [here](https://github.com/cheatfate/nimcrypto/issues/33).

**Comment by ringabout** [comment]
It is caused by forward declaration.
The Code below works and `{.raise: [].}` works.
```nim
proc hello() =
  discard

proc test() {.raises:[IOError, ValueError].} =
  hello()

test()

# proc hello() {.raises: [].}


# proc test() {.raises:[IOError, ValueError].} =
#   hello()

# proc hello() =
#   discard

# test()

```

Failed case:
```nim
proc hello()

proc test() {.raises:[IOError, ValueError].} =
  hello()

proc hello() =
  discard

test()
```

**Comment by lguzzon** [comment]
Hi got an error compiling for **windows** **console** apps the test "tests/stdlib/tterminal_12759.nim" [here](https://github.com/nim-lang/Nim/commit/9ec9a31f46697a615630fce3614e68e57d390a74)
using "nim c -r -d:consoleapp test.nim" or using `switch "app", "console"` 
the compilation goes in error 
...\lib\pure\terminal.nim(40, 56) template/generic instantiation from here
...\lib\pure\terminal.nim(904, 17) Error: can raise an unlisted exception: ref OSError

The exceptions are "inserted" [here](https://github.com/nim-lang/Nim/blob/11c377c1149a23657a7f0dd897866cb550ade8d1/lib/pure/terminal.nim#L191) and [here](https://github.com/nim-lang/Nim/blob/11c377c1149a23657a7f0dd897866cb550ade8d1/lib/pure/terminal.nim#L196) 

In **windows**  [here](https://github.com/nim-lang/Nim/blob/11c377c1149a23657a7f0dd897866cb550ade8d1/lib/pure/terminal.nim#L40) can fixit adding "OSError" to the "raise" but in Linux?

Can you fix it?
Thanks
