### ISSUE TITLE
Float16 support

### ISSUE THREAD

**Issue by linkerlin** [nim-lang/Nim#12769]
For ML/DL and Math programming, float16 is important for GPU speed-up.
So what about to support float16 in nim for GPU?

**Comment by Araq** [comment]
We don't compile to GPUs though. There are Nimble packages to do that and they can introduce ``float16``, Nim supports general operator overloading.

**Comment by mratsim** [comment]
Float16 is dying, we will have brain float16 (bf16) next year with CPU support anyway ;).
