### ISSUE TITLE
htmlparser collapses empty tags generating invalid html

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1276]
The following example parses an HTML file and generates a modified version:

``` nimrod
import htmlparser, xmltree, strtabs, streams

const
  test = """
<html>
<title></title>
<body>
<h1>Hey</h1>
<img src="test.txt">
</body></html>
"""

proc mangle() =
  var
    html = test.new_string_stream.parse_html
    DID_CHANGE: bool

  for img in html.find_all("img"):
    let src = img.attrs["src"]
    if not src.is_nil:
      img.attrs["src"] = "Something else"
      DID_CHANGE = true

  if DID_CHANGE:
    echo "Did change, output:", html
    write_file("out.html", $html)

when isMainModule: mangle()
```

While the output HTML contains a `document` wrapper tag, even if tricks like those mentioned at http://forum.nimrod-lang.org/t/473 are used to avoid the tag, the `title` tag gets collapsed into something invalid. Neither Safari nor Chrome seem to be able to render properly the generated file:

``` html
<html>
<title />
<body>
<h1>Hey</h1>
<img src="Something else" />
</body></html>
```

Only when the xml-like `title` tag is removed browsers show anything at all.

**Comment by andreaferretti** [comment]
The above example does not work at all with latest Nim.

In any case, according to [these answers](https://stackoverflow.com/questions/19400657/empty-title-element-in-html-stops-html-from-loading-if-written-as-title) the title, if present, must not be empty anyway.

The w3c validator accepts this as valid:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title/>
</head>
<body>
</body>
</html>
```

**Comment by dom96** [comment]
Okay, I'm going to close this because the HTML isn't considered valid.
