### ISSUE TITLE
proc to get stdout and stderr with executing command

### ISSUE THREAD

**Issue by jiro4989** [nim-lang/Nim#12776]
### Summary

I need a proc to get stdout and stderr.

### Description

I want to handle stdout and stderr with executing shell command.
I searched the proc from `osproc` module, but I could not find like that.

I want to do like below:

```nim
let (outputStdout, outputStderr, exitCode) = execProcess("ls -lah /path/to/file")
echo "stdout: " & outputStdout
echo "stderr: " & outputStderr
```

**Comment by Araq** [comment]
Use ``startProcess`` + ``running`` + ``outputStream`` + ``errorStream`` + ``close``.

**Comment by jiro4989** [comment]
Thanks
