### ISSUE TITLE
newruntime and computed goto: variables inside the loop are in generated code uninitialised

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#12785]
Here's an example:

### Example
```nim
proc test(a: range[0..1]) =
    while true:
        {.computedGoto.}
        
        let b = int(a) * 2

        case a
        of 0:
            echo b
            break
        of 1:
            echo b
            break

test(1)
```

The reason for this is that in C code b is always [re](https://gist.github.com/RSDuck/891144dcdb84b7c9ff9d6ec2d2f5f816#file-generated-c-code-c-L197)[de](https://gist.github.com/RSDuck/891144dcdb84b7c9ff9d6ec2d2f5f816#file-generated-c-code-c-L228)[fined](https://gist.github.com/RSDuck/891144dcdb84b7c9ff9d6ec2d2f5f816#file-generated-c-code-c-L197), for each individual case. This is the reason the value assigned to `b` during the previous iteration is lost.

### Current Output

This can vary based on what's still in register/memory
```
42
```

### Expected Output
```
2
```

### Additional Information

```
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2019-11-29
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c5c6bae2a42734df2ba5fdb7cd8cf327d4e7005f
active boot switches: -d:release
```

**Comment by Araq** [comment]
Is this related in any way to ``--newruntime``? Cause it looks like it isn't.

**Comment by RSDuck** [comment]
yes, atleast I think so. If you compare the [generated code without newruntime enabled](https://gist.github.com/RSDuck/a0ab33fecd874e53a073a26d04c17bfa#file-c-code-not-new-runtime-c-L99), you see that `b` is only declared once, while it is [declared multiple times with newruntime enabled](https://gist.github.com/RSDuck/891144dcdb84b7c9ff9d6ec2d2f5f816#file-generated-c-code-c-L197).

I'm still using the same git revision as in the original post.
