### ISSUE TITLE
orderedTable.del() crashes with unitialized table

### ISSUE THREAD

**Issue by Stuffe** [nim-lang/Nim#12798]
I think the code is pretty self explanatory

https://play.nim-lang.org/#ix=23qw
```
import tables

var table: Table[int, int]

table.del(1) # works

var ordered_table: OrderedTable[int,int]

ordered_table.del(1) # Should have worked according to docs
```

**Comment by c0ntribut0r** [comment]
Hm, works if you manually init ordered table, or if you assign anything before calling `del`. Seems that if ordered table was not manually initialized, it will be initialized during first access, but not during `del` call.
```nim
import tables

var ordered_table = initOrderedTable[int,int]()
ordered_table.del(1)  # ok

var ordered_table2: OrderedTable[int, int]
ordered_table2[9] = 9
ordered_table2.del(1)  # ok

var ordered_table3: OrderedTable[int, int]
ordered_table3.del(1)  # err
```

**Comment by Stuffe** [comment]
Yes, someone mentioned on discord that it may have to do with the orderedTable not being converted to the new nil system yet, whatever that means. It is inconvenient when you have on object type like this used all over the place: 
```
import tables

type thing = object 
  value*: OrderedTable[int, int]

var test: thing
thing.del(0)
```
