### ISSUE TITLE
Less verbose procedures

### ISSUE THREAD

**Issue by beuthkaiser** [nim-lang/Nim#12811]
**Introduction:**

Nim clearly separates data from procedures. Which is great because that avoids introducing a lot of unnecessary complexity.
__But:_ This can be verbose_.
A general way in which languages rise to a higher level of expressiveness is by using contextual information. E.g. when you ask "When is Maria coming home?", you don't have to specify which Maria.
What classical OOP-methods (procedures bound to objects) do right is, that they provide context.

**Observations:**
- object methods mostly operate on the objects data, oftentimes ONLY on the objects data
- this comes up A LOT, many nim modules are just a datatype definition followed by procedures that operate on it (basically nims take on classes)
- even though to a human it's obvious from the context which variables are meant inside a proc, they have to repeatedly be explicitly specified
      
It is a similar problem to pythons controversial 'self'. I did some measurements on OOP python files and found that around 10% of the code was the word self. To quote the wise: "Repetition renders the ridiculous reasonable." I will refer to the first parameter of a nim proc as 'self reference' for lack of a better word (and because it kind of is the same).

**Example:** 
```
type Triangle = object
  a,b,c:float

#proc that does some math
proc incircle_radius(triangle : Triangle) : float =
  (triangle.a/2)*sqrt((2*triangle.b-triangle.a)/(2*triangle.b+triangle.a))

#same thing with abbreviation, not great either
proc incircle_radius(t : Triangle) : float =
  (t.a/2)*sqrt((2*t.b-a)/(2*t.b+t.a))
```

Now imagine writing thousands of lines of code like this, there are scenarios (e.g. equation heavy stuff, 3D graphics) where it is not uncommon to have 5-10 'self references' per line.    
Also note that it is currently easier (less verbose) to write a singleton-module than a class-like datatype. 

**Usability problems:**
- remembering the 'self reference' -> increased cognitive strain
- forgetting the 'self reference' -> easy to fix bug, but takes a couple of seconds, and there are a lot of mistake opportunities
 -- note: I assume you do not use 'a' and 't.a' in the same proc, because then it would be harder to find bugs (and more confusing)     
- decreased readability

_Self-check: Did you notice the mistake in the example? Is it obvious what was meant? Could the same idea be expressed in a more intuitive fashion?_

**Required solution:**
- allow specifying procs with a context
- (also has to specify mutability) 

**Proposed solution:**
```
    Triangle.proc incircle_radius() : float =
      (a/2)*sqrt((2*b-a)/(2*b+a))
```
We specify with TYPE.proc what datatype we operate on (same thing as first parameter) and make the fields of the type directly accessible inside the proc. Mutability could be declared similar to sequences with @ like:
        
> @Triangle.proc rescale(size:float) = ...

A keyword for when we actually want to reference the object itself would be nice. Maybe something like: `proc.$` reasoning that proc. is kind of the namespace and so that we avoid new keywords. A keyword would also be nice so you can let tooling help when you don't remember the available identifiers.      
    
I think this would fit beautifully into the language, it seems like a pendant to:

```
print(triangle)
triangle.print()
    
proc print(t : Triangle) = echo t.a,t.b,t.c
Triangle.proc print() = echo a,b,c
```
    
**Benefits:** 
    - increased readability
    - less typing, ca. 5-10% less code, same functionality = more expressiveness
    - less errors and thinking
    - high frequency use case

**Cost:**
    - easy to learn and understand language feature
    - keyword  
    - may shadow global identifiers

**Comment by kaushalmodi** [comment]
Here the procs have just one arg. This wouldn't work for 2 or more args. 

Even for one arg proc, there would be ambiguity.. what if the a, b, c are global vars?

I would pick verbosity over ambiguity.

**Comment by kaushalmodi** [comment]
On a related note, check out:

- https://github.com/zevv/with
- https://github.com/citycide/cascade

**Comment by SolitudeSF** [comment]
i too love using a language for 10 minutes and then submitting a language breaking proposal just so it could remind me of language i already know.

**Comment by dumjyl** [comment]
> increased readability
> less errors and thinking

Not my experience with c++.

> less typing, ca. 5-10% less code, same functionality = more expressiveness

You still have to write the type every-time. An indentation based approach is more idiomatic, less typing, and already works.

```nim
impl Triangle:
  proc incircle_radius() : float =
    (a/2)*sqrt((2*b-a)/(2*b+a))
  proc print =
    echo self

impl var Triangle:
  proc set_a(val: float) =
    a = val
```

**Comment by demotomohiro** [comment]
Your proposed solution is very similar to C++'s member functions.
In C++, I can use class's member variables like local variables inside member function.
And I have to define member functions inside class definition or with class name.

If a number of object fields are small and proc use a few local variable, it would easier to read and code is smaller.
And also when I want to move a local variable to object field, I can do that with fewer code change.

But your proposal decrease readability when a number of object fields and local variables are large.
When there are 10+ object fields and 10+ local variables, it is very hard to distinguish object fields from local variables.
That is why there are C++ people who always use member variables with `this->` or name member variables like `m_a` or `_a`.

I heard that someone declare a local variable that has same name to member variable and trying to write member variable but that actually writes to local variable.
Such a bug can take long time to fix because a C++ compiler doesn't show errors.
Compiler can show warnings to this case, but there are people who ignore warnings or disable it.
Compiler can prevent this by making declaration of local variable same name to object field to error.
Then, when you add an object field, you have to choose a name that is not used in local variable or change local variable names in existing code. This could be hard when you have large code.
Or you have to use different naming convention between object field and local variable like some C++ programmers do.

**Comment by Araq** [comment]
Actually we did have ``{.this: self}`` to mitigate the burden @beuthkaiser identified but IMHO it made the language too terse. Instead we got the under-used (?) ``using`` mechanism.

**Comment by alehander92** [comment]
I think `using` fixes this well: it can be used for many args, not one

**Comment by alehander92** [comment]
e.g. you can have 
```
using 
  t: Triangle
  arg: int

func a(t, arg) ..
func b(t, arg) ..
```
otherwise great analysis indeed!

**Comment by alehander92** [comment]
you can notice you have maybe even less repetition with using, as you can use a shorter variable name each time instead of Triangle:

**Comment by kaushalmodi** [comment]
@dumjyl 

> ```nim
> impl Triangle:
> ```

I have never heard of `impl` and I do not see it in the manual.. what is it? Where is it documented?

**Comment by SolitudeSF** [comment]
@kaushalmodi by `already works` he means that it doesn't require language changes, not that its already implemented.

**Comment by Araq** [comment]
> I have never heard of impl and I do not see it in the manual.. what is it? Where is it documented?

I've seen macro implementations for this but it's been a while ago.

**Comment by beuthkaiser** [comment]
@kaushalmodi: Multiple arguments should not be a problem. Examples (also for readability comparison)

```
proc rescale(t : var Triangle, s : float) =
    t.a *= s
    t.b *= s
    t.c *= s    
    echo "new incircle radius: ", (t.a/2)*sqrt((2*t.b-t.a)/(2*t.b+t.a))

@Triangle.proc rescale(s : float) =
    a *= s
    b *= s
    c *= s    
    echo "new incircle radius: ", (a/2)*sqrt((2*b-a)/(2*b+a))
```
```
proc fall(player: var Player, physics: Physics, ms: int):
    if not player.is_grounded and not player.is_jumping:
        player.y -= physics.gravity * player.weight * ms
        player.fall_distance += physics.gravity * player.weight
    else:
        player.health -= player.fall_distance
            
@Player.proc fall(physics: Physics, ms: int):
    if not is_grounded and not is_jumping:
        y -= physics.gravity * weight * ms
        fall_distance += physics.gravity * weight
    else:
        health -= fall_distance
```

@SolitudeSF: I too enjoy being mean to strangers. If I was not clear enough: I was wondering about the feasibility  of an **_alternate_** way to declare functions _**without breakage**_ in order to avoid possibly confusing boiler plate code. 

@dumjyl: I don't think C++ readability vs nim is a fair comparison because there is too much other stuff affecting it. Do you think C is more readable than C++? I believe the correct answer is: it depends.     

@demotomohiro: Solid explanation, those are the advantages of a more verbose approach. My reasoning is that often times those are non-issues (e.g. when you do not have a lot of local or global variables and/or they are easily differentiated). IMHO this is a common case in which you end up writing less readable code because of a dogmatism ("we never do X because it is bad in case Y so it always is bad"). I view it as a tradeoff that should be the developers choice. Sure if you are less explicit there is a risk off being less clear what was meant, but you can also be more clear by leaving out unnecessary information that is implicitly understood. 

I have a Sudoku solver in nim that provides hints based on non-bruteforce techniques, basically it takes a little bit of input and then mostly what it does is process its own data. If I implement this as a Singleton-module (global variables = fields, procs = methods) it's easy. If I want to do (or worse: refactor) this as a class the 'self references' start getting in the way when developing complicated algorithms. When I want to say `if board[x][y] in number_in_block[x][y]` the compiler complains "which board? Which number_in_block?' and I have to go `if sudoku.board[x][y] in sudoku.number_in_block[x][y]`. That does not reflect the way I reason about the problem, it feels painfully redundant. Yes, it is not the end of world. In many cases it is not a big deal. But it can become a nuisance, the more 'self references' per line you have the more so. I was thinking about using nim for procedural geometry but I know there are going to be a ton of 'self references' that I won't have to deal with in other languages. This should not need to be a pain point! All that is needed is a way to tell the compiler "now I am talking about X" to avoid repetition when it is not beneficial. Surely this can be achieved without C++ing the language.

@Araq:
The general notion of declaring shorthands for when we want to avoid repetition seems like a reasonable middle ground to me. That said I do not see how 'using' is relevant to the problem. afaik, 'using' can only be used top level and is only useful to avoid repetition in function signatures. I do not care about the head, I care about the body (no pun intended) where the logic happens.

How about:
```
proc incircle_radius(triangle : Triangle) : float =
    #declare a bunch of shorthand notations
    using 
     a : triangle.a
     b : triangle.b
     c : triangle.c 
    (a/2)*sqrt((2*b-a)/(2*b+a))

# or more aggressively
proc incircle_radius(triangle : Triangle) : float =
    using triangle: # expose triangles members inside the scope 
      (a/2)*sqrt((2*b-a)/(2*b+a))
```
This would be less invasive than my original proposal and have the benefit that it would also work for other parameters. E.g. you could have verbose parameter names and still easily be able to use abbreviations.

@alehander92:

I think what you are proposing does not really need 'using' and results in this:
```
import math
type Triangle = object
  a,b,c : float 

proc incircle_radius(a,b,c:float) : float =
    (a/2)*sqrt((2*b-a)/(2*b+a))

proc incircle_radius(t: Triangle) : float =
    incircle_radius(t.a,t.b,t.c)

echo Triangle().incircle_radius()  
```
Seems like a reasonable but boiler plate heavy solution to me.

**Comment by Clyybber** [comment]
@beuthkaiser What you propose already exists as a macro :)
See https://github.com/zevv/with .

**Comment by alehander92** [comment]
@beuthkaiser generally most of those ideas can be implemented with macros

**Comment by alehander92** [comment]
so they might be good ideas, but i dont think they require changes in the language (except maybe a sugar macro)

**Comment by beuthkaiser** [comment]
nice :), I'll try out 'with'. Having something like that as a standard language feature might be beneficial so that its more standardized and more people know about it. Depending on how useful you think it is...

**Comment by mratsim** [comment]
If there is one reason I prefer reading C code over C++ code it's the obscure member fields that are very annoying to grok through as you need often need to back dozens to hundreds of lines of code to remember the scope you are in.

While this proposal does not have this issue, I don't see clear benefits, just use a short identifier instead like `t` was proposed.

And there is `using` that I always forget of course.

Lastly I'm curious to know if there are that many Nimmers developing OOP style, personally I use it very very rarely. Objects/mutable state:
- are not thread safe
- don't play well with async either
- are harder to unit-test due to the need of mocking

As I focus on procedures instead of objects, I'm not really bothered by such a repetition.

**Comment by beuthkaiser** [comment]
@mratsim 
Yeah, I think one subtle way in which nim makes your life easier is that it naturally tends to produce many small, relatively self-contained parts, which are easier reasoned about.
Personally I went FP for a while. Then I found more use cases where OOP modeled the problem easy to think about and now I just don't care anymore. I don't think FP is going to take over the world, I think OOP was overhyped, overenforced and riddled with malpractices and now FP will be hyped for a while and then it is going to settle down to 'mix whatever fits the job best'. I think any self-respecting mainstream-GPL these days needs to support both (I don't think OOP and FP are mutually exclusive anyways). And then stuff like writing DSLs is going to matter more.

**Comment by dumjyl** [comment]
My remark about c++ readability was the navigation gymnastics @mratsim mentioned.

Nim likes placing what a thing is (`type`, `var`, `proc`, etc.) right in the front so the proposal doesn't read well with the rest of the language. 

@kaushalmodi code not pseudo anymore, docs non-existent.

**Comment by dawkot** [comment]
If you just want to expose all the fields:
```nim
import macros



iterator symsFromIdentDefs(nodes: NimNode or openarray[NimNode]): NimNode =
  for n in nodes:
    expectKind n, nnkIdentDefs
    for it in n[0..^3]:
      yield it

macro use(x: object or ref object or tuple or ref tuple) =
  let typ = if x.getTypeImpl.kind == nnkRefTy: x.getTypeImpl[0].getTypeImpl else: x.getTypeImpl
  let defs = if typ.kind == nnkObjectTy: typ[2] else: typ
  result = newStmtList()
  for sym in symsFromIdentDefs defs:
    let id = ident $sym
    result.add quote do:
      template `id`: untyped {.used.} = `x`.`id`



type MyObj = object
  a: int
  b: float
  c: string

block:
  let x = MyObj(a: 1, b: 2.0, c: "3")
  use x
  assert (a, b, c) == (1, 2.0, "3")

block:
  type MyRef = ref MyObj
  let x = MyRef(a: 1, b: 2.0, c: "3")
  use x
  assert (a, b, c) == (1, 2.0, "3")

block:
  let x = (a: 1, b: 2.0, c: "3")
  use x
  assert (a, b, c) == (1, 2.0, "3")
```

**Comment by beuthkaiser** [comment]
@dawkot: ty for the code

Closing this and opening https://github.com/nim-lang/Nim/issues/12873 for an improved proposal.
