### ISSUE TITLE
Macros: semcheck on untyped param when an optional arg is not passed.

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12819]
The following compiles:

```Nim
import macros

macro parallelFor(loopParams: untyped, step: int = 1, body: untyped): untyped =
  result = body

parallelFor i in 0 ..< 10, step = 1:
  echo "Hello"
```

The following doesn't
```Nim
import macros

macro parallelFor(loopParams: untyped, step: int = 1, body: untyped): untyped =
  result = body

parallelFor i in 0 ..< 10:
  echo "Hello"
```

The error is `undeclared identifier i`.
Note that due to https://github.com/nim-lang/Nim/issues/12019 which obscures semcheck error on untyped parameters, it might be something else entirely.

Overloading with a proc of the same name is not an option as the position of untyped parameter must match at the moment https://github.com/nim-lang/Nim/issues/9414

**Comment by timotheecour** [comment]
this works:
```nim
import macros
macro parallelFor(loopParams: untyped, step: int = 1, body: untyped): untyped = result = body
parallelFor(i in 0 ..< 10, body = block:
  echo "Hello")
```

so the premise (`Macros: semcheck on untyped param when an optional arg is not passed`) is not correct analysis.

This reduces to https://github.com/nim-lang/Nim/issues/14346 ; closing this in favor of https://github.com/nim-lang/Nim/issues/14346  which has more analysis
