### ISSUE TITLE
json decode is slower than go!

### ISSUE THREAD

**Issue by zhuxiujia** [nim-lang/Nim#12833]
Faster than Java, but seven times slower than golang

### Nim Code
```nim
import os
import json
import util/benchmark_util

proc getNano() :float64=
    return cpuTime()*1000000000

proc benchmark_item(count_index:int64,count_time:int64,total:float64,callback:proc():void): void =
    echo "bench:",count_index
    let cpuStartTime =  getNano()
    for index in 1..total.toBiggestInt():
         callback()
    var useTime=getNano() - cpuStartTime
    var ns_op=useTime/total
    echo "Time taken: ", useTime,"ns"
    echo ">      number:",total,"      bench: ",ns_op,"  ns/op"

# Statistics execution time
proc benchmark(count_time:int64,total:float64,callback:proc():void) =
    for count_index in 1..count_time:
       benchmark_item(count_index,count_time,total,callback)


type User = object
            id: string
            name: string
            version: int

# echo(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>now  start runing")


proc test(): void =
      let js="""{"id": "","name": "","version": 0}"""
      let jsonNode = parseJson(js)
      let u=to(jsonNode, User)
      #echo u

benchmark(1,3000000,test)
echo "done"

```

### golang Code
```go
type User struct {
	id string
	name string
	version int32
}
func BenchmarkJSON(b *testing.B) {
	b.StopTimer()
	var u=User{
		id:"",
		name:"",
		version:0,
	}
	var v,_=json.Marshal(u)
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		var u=User{}
		 e:=json.Unmarshal(v,&u)
		 if e!=nil{
		 	panic(e)
		 }
	}
}
```

### nim output
```nim
nim c  -d:release -r main.nim
number:3000000.0      bench: 1568.333333333333  ns/op [Windows: amd64]
```
### go output
```go
nim c  -d:release -r main.nim
number:3000000.0      bench: 205  ns/op   [Windows: amd64]
```

### Expected Output
```
nim c  -d:release -r main.nim
golang:   number:3000000.0      bench: 205  ns/op   [Windows: amd64]
nim:        number:3000000.0      bench: 1568.333333333333  ns/op   [Windows: amd64]
```

### Possible Solution

JSON standard library optimizes performance

```
$ nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]
```

**Comment by Yardanico** [comment]
What about using `-d:danger` instead of `-d:release`. Also, did you try packedjson (or other nimble JSON decode libs) ? And does that JSON performance affect your actual app (not some microbenchmarks)?

**Comment by zhuxiujia** [comment]
> What about using `-d:danger` instead of `-d:release`? Also, did you try `packedjson` (or other nimble JSON decode libs)? And does that JSON performance affect your actual app (not some microbenchmarks)?

### use -d:danger  it  also  slow....   my 
number:3000000.0      bench: 1390.666666666667  ns/op


### and .... My program requires high JSON parsing

**Comment by Araq** [comment]
Dunno, probably you measure different things.

**Comment by zhuxiujia** [comment]
> Dunno, probably you measure different things.


### use packedjson

 number:3000000.0      bench: 947.6666666666666  ns/op

**Comment by Araq** [comment]
It's not surprising Go's implementation is faster, they deserialize directly into the struct
which we could also do but don't.

One problem is that Go's implementation is also full of stuff where I can trigger pathological behaviour, you can't just "write a fast JSON library". what if the JSON has a 10GB string literal inside? what if it has object fields with 1000 entries?

JSON is used for **everything** and so you need to protect against so many different things and then once you did, it's kinda slow for the general case.

Having said that, we'll of course improve the performance further.

**Comment by zhuxiujia** [comment]
> It's not surprising Go's implementation is faster, they deserialize directly into the struct
> which we could also do but don't.
> 
> One problem is that Go's implementation is also full of stuff where I can trigger pathological behaviour, you can't just "write a fast JSON library". what if the JSON has a 10GB string literal inside? what if it has object fields with 1000 entries?
> 
> JSON is used for **everything** and so you need to protect against so many different things and then once you did, it's kinda slow for the general case.
> 
> Having said that, we'll of course improve the performance further.



If it's fast, it's a great programming language

**Comment by ringabout** [comment]
faster JSON implementation
https://github.com/disruptek/jason

**Comment by disruptek** [comment]
Jason doesn't deserialize (yet).

**Comment by FedericoCeratto** [comment]
Related to #3809 and #12152
