### ISSUE TITLE
Enum with holes cannot be used as Table index

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#12834]
An enum type with holes cannot be used as a Table index type.

### Example
```nim
import std/[tables]

type
  SomeEnum = enum
    seOne = 1
    seTwo
    seTen = 10 # will compile if this lines is commented

let
  spec: Table[SomeEnum, int] = {seOne: 100, seTwo: 200}.toTable()
echo spec
```

Same code on Nim playground: https://play.nim-lang.org/#ix=23Pc

### Current Output

```
/usercode/in.nim(10, 56) template/generic instantiation of `toTable` from here
/playground/nim/lib/pure/collections/tables.nim(341, 45) template/generic instantiation of `[]=` from here
/playground/nim/lib/pure/collections/tableimpl.nim(58, 21) template/generic instantiation of `rawGet` from here
/playground/nim/lib/pure/collections/hashcommon.nim(64, 14) template/generic instantiation of `genHashImpl` from here
/playground/nim/lib/pure/collections/hashcommon.nim(54, 12) Error: type mismatch: got <SomeEnum>
but expected one of: 
..
```

### Expected Output

This code was expected to compile and run fine.

### Workaround

I already have that enum type in my code. So I need to use `enumVar.ord` as the Table index, with the index type as `int`.

### Additional Information

- I came across this while working on an Advent of Code solution. [This is my workaround][1] there for now.

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2019-12-05
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 3fbb3bfd3f440c059d6290c12834a38a61da98f2
active boot switches: -d:release
```

[1]: https://github.com/kaushalmodi/aoc2019/blob/674a85140b3a714dd65153c4d92b9c336ae8ba8f/day2/day2.nim#L34-L44

**Comment by nc-x** [comment]
Not a bug AFAIK. You need to define your own hash function for your enum.
Rust style `derive` is a good idea, and there is a proposal for it here - https://github.com/nim-lang/Nim/issues/7731
I don't like the macro version but custom pragma looks good :)
