### ISSUE TITLE
Add a 32x32 favicon to the docs site

### ISSUE THREAD

**Issue by elliotwaite** [nim-lang/Nim#12838]
### Summary
The current docs favicon is 16x16 image, which looks pixelated on retina displays. This update would add a 32x32 alternative icon to be displayed on screens that can render that resolution.

This code would be added below the current favicon:
```
<link rel="icon" type="image/png" sizes="32x32" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH4QQQEwksSS9ZWwAAAk1JREFUWMPtll2ITVEUx39nn/O7Y5qR8f05wtCUUr6ZIS++8pEnkZInPImneaCQ5METNdOkeFBKUhMPRIkHKfEuUZSUlGlKPN2TrgfncpvmnntnmlEyq1Z7t89/rf9a6+y99oZxGZf/XeIq61EdtgKXgdXA0xrYAvBjOIF1AI9zvjcC74BSpndrJPkBWDScTF8Aa4E3wDlgHbASaANmVqlcCnwHvgDvgVfAJ+AikAAvgfVZwLnSVZHZaOuKoQi3ZOMi4NkYkpe1p4J7A8BpYAD49hfIy/oqG0+hLomiKP2L5L+1ubn5115S+3OAn4EnwBlgMzCjyt6ZAnQCJ4A7wOs88iRJHvw50HoujuPBoCKwHWiosy8MdfZnAdcHk8dxXFJ3VQbQlCTJvRBCGdRbD4M6uc5glpY3eAihpN5S5w12diSEcCCEcKUO4ljdr15T76ur1FDDLIQQ3qv71EdDOe3Kxj3leRXyk+pxdWnFWod6Wt2bY3de3aSuUHcPBVimHs7mK9WrmeOF6lR1o9qnzskh2ar2qm1qizpfXaPeVGdlmGN5pb09qMxz1Xb1kLqgzn1RyH7JUXW52lr5e/Kqi9qpto7V1atuUzfnARrV7jEib1T76gG2qxdGmXyiekkt1GswPTtek0aBfJp6YySGBfWg2tPQ0FAYgf1stUfdmdcjarbYJEniKIq6gY/Aw+zWHAC+p2labGpqiorFYgGYCEzN7oQdQClN07O1/EfDyGgC0ALMBdYAi4FyK+4H3gLPsxfR1zRNi+NP7nH5J+QntnXe5B5mpfQAAAAASUVORK5CYII=">
```
This code was generated from the favicon here: https://nim-lang.org/assets/img/logo_bw.png (which is the favicon that is used outside of the docs, for example on the home page: https://nim-lang.org).

The base64 code can be confirmed [here](https://onlinepngtools.com/convert-base64-to-png?input=iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAACXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH4QQQEwksSS9ZWwAAAk1JREFUWMPtll2ITVEUx39nn%2FO7Y5qR8f05wtCUUr6ZIS%2B%2B8pEnkZInPImneaCQ5METNdOkeFBKUhMPRIkHKfEuUZSUlGlKPN2TrgfncpvmnntnmlEyq1Z7t89%2Frf9a6%2By99oZxGZf%2FXeIq61EdtgKXgdXA0xrYAvBjOIF1AI9zvjcC74BSpndrJPkBWDScTF8Aa4E3wDlgHbASaANmVqlcCnwHvgDvgVfAJ%2BAikAAvgfVZwLnSVZHZaOuKoQi3ZOMi4NkYkpe1p4J7A8BpYAD49hfIy%2FoqG0%2BhLomiKP2L5L%2B1ubn5115S%2B3OAn4EnwBlgMzCjyt6ZAnQCJ4A7wOs88iRJHvw50HoujuPBoCKwHWiosy8MdfZnAdcHk8dxXFJ3VQbQlCTJvRBCGdRbD4M6uc5glpY3eAihpN5S5w12diSEcCCEcKUO4ljdr15T76ur1FDDLIQQ3qv71EdDOe3Kxj3leRXyk%2BpxdWnFWod6Wt2bY3de3aSuUHcPBVimHs7mK9WrmeOF6lR1o9qnzskh2ar2qm1qizpfXaPeVGdlmGN5pb09qMxz1Xb1kLqgzn1RyH7JUXW52lr5e%2FKqi9qpto7V1atuUzfnARrV7jEib1T76gG2qxdGmXyiekkt1GswPTtek0aBfJp6YySGBfWg2tPQ0FAYgf1stUfdmdcjarbYJEniKIq6gY%2FAw%2BzWHAC%2Bp2labGpqiorFYgGYCEzN7oQdQClN07O1%2FEfDyGgC0ALMBdYAi4FyK%2B4H3gLPsxfR1zRNi%2BNP7nH5J%2BQntnXe5B5mpfQAAAAASUVORK5CYII%3D).

**Comment by elliotwaite** [comment]
Does anyone know why the build for https://github.com/nim-lang/Nim/pull/12839 failed?

**Comment by nc-x** [comment]
@elliotwaite The failure looks unrelated to the pr. You can restart the CI's by closing and reopening the PR (the build will restart in both Azure and  sr.ht), or someone from the core team (@narimiran?) should be able to restart only the sr.ht build to verify.

**Comment by nc-x** [comment]
Well, creating a new PR is not necessary, just close and re-open the same PR and it would restart the build :)

Anyways, lets see the build this time to confirm that the failure was unrelated.

**Comment by elliotwaite** [comment]
Ah, got it. Oops.

**Comment by elliotwaite** [comment]
Nice, it passed this time. Thanks for the suggestion.

**Comment by elliotwaite** [comment]
The PR has been merged: https://github.com/nim-lang/Nim/pull/12856. Closing issue.
