### ISSUE TITLE
distinct types get stripped of every operation

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1284]
My understanding is that `distinct` serves to create "incompatible" type, to avoid unwanted reuse of user written code.

But it also removes all default operations associated with a type:

```
type
  t1 = array[0..5, int]
  t2 = distinct array[0..5, int]

var
  v1 : t1
  v2 : t2

echo v1[0]  # OK
echo v2[0]  # fails to compile, no fitting system.[] found
```

Woudn't it makes sense to keep certain functions from `system` available by default, and, if needed, allow the user to replace them w/o producting redefinition errors? Forcing `{.borrow.}` for array access seems to be over the top.

Edit: perhaps the solution could be ability to specify what function are inherited automatically:

```
type
  t1 = distinct base_type {.borrows: *.} # every API available by default
  t2 = distinct base_type {.borrows: [].} # no API available
  t3 = distinct base_type {.borrows: [[], +, -, whatever].} # only explicitly specified API
```

Edit2: As I see now 0.9.5 provides similar feature for dot operator, but it is a bit hard to read with those `` and a long pragma would be more readable if at the end of line.

**Comment by narimiran** [comment]
```nim
 type
   t1 = distinct base_type {.borrows: *.} # every API available by default
```

I know that more than 4 years have passed, but this seems useful. Could we have something like this implemented?

**Comment by andreaferretti** [comment]
Well, what is the point of using distinct types if any operation is still available? You certainly don't gain in type safety

**Comment by narimiran** [comment]
> Well, what is the point of using distinct types if any operation is still available?

I've quoted the wrong example, should have been `t3`, where you explicitly declare what operations you would like to borrow. (`{.borrows: [[], +, -, whatever].}`)

From [the manual](https://nim-lang.org/docs/manual.html#types-distinct-type), there is this:

```nim
type
  Foo = object
    a, b: int
    s: string
  
  Bar {.borrow: `.`.} = distinct Foo

var bb: ref Bar
new bb
# field access now valid
bb.a = 90
bb.s = "abc"
```

but, as it says under the example: *"Currently only the dot accessor can be borrowed in this way."*, and trying to `{.borrow: [].}` raises: *"Error: a type can only borrow `.` for now"*.

It would be nice if this syntax is not limited only to `.`, as it would greatly simplify declaring what you would like to borrow.

**Comment by Araq** [comment]
Just use a type alias then if you need all the operations from the base type. We don't need more complexity in the core language, you can ``.borrow`` and/or use Nim's macro system.
