### ISSUE TITLE
importc type silently ignored 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12866]
importc type silently ignored 

D20191209T140120

### Example
nim c t0819.nim
t0819.nim:
```nim
  type TFOO* {.importc: "Foo".} = object # codegen error: error: unknown type name 'Foo'
  # type TFOO* {.importc: "struct Foo".} = object # works with nim cpp and nim c
  # type TFOO* {.importc: "class Foo".} = object # works with nim cpp and nim c
  # type TFOO* {.importc: "Foo", header: "t0819c.h".} = object # works with nim cpp
    x*: cint
  type Foo = ptr TFoo
  var a: Foo
```

t0819c.h:
```
struct Foo{
  int x;
};
```

### Current Output
@mt0819.nim.cpp:30:1: error: unknown type name 'Foo'
Foo* a__gZc8twzFQrfbnfGjEbjqCg;

### Expected Output
code snippet should work.
At very least, if for some reason it can't work, `type TFOO* {.importc: "Foo".} = object` itself should give CT error

### Additional Information

recent devel 7213969901a4232013a6e6732d7b434970922510

**Comment by cooldome** [comment]
I don't think there is a bug.  When you importc a type it is your responsibility to make sure it is declared. It is possible to make Nim forward declare importc type, but Nim will forward declare it as struct. However, it is common to use `type TF* {.importc: "F".} = object` syntax to import not just structs. In this case it will cause a conflict between actual type definition and Nim's forward declaration, so it will cause more harm than good.

**Comment by Araq** [comment]
Use ``{.importc: "Foo", header. "t0819c.h".}``  instead. No bug here.
