### ISSUE TITLE
Nim object variant issue

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1286]
https://github.com/dom96/jester/blob/master/jester.nim#L24

i.e.:

``` nimrod
type
  TJester = object
    isHttp*: bool
    case isAsync: bool
    of true:
      asyncHTTP: PAsyncHTTPServer
      asyncSCGI: PAsyncScgiState
    of false:
      dummyA, dummyB: pointer # workaround a Nimrod API issue
      s: TServer
      scgiServer: TScgiState
```

**Comment by yglukhov** [comment]
Its kinda unclear what this issue is about. @dom96, is it still actual?

**Comment by dom96** [comment]
Not sure. @Araq will know. It's regarding this line:

> dummyA, dummyB: pointer # workaround a Nimrod API issue

**Comment by Araq** [comment]
It's in fact one top priority in my todo.txt for version 1 to fix this language problem. It's definitely still an issue.

**Comment by andreaferretti** [comment]
I still do not understand why these two dummy pointers are needed, @dom96 can you write a line of explanation?

**Comment by dom96** [comment]
Araq can explain it better than I can.

**Comment by Araq** [comment]
The transition from false to true in the object variant doesn't trigger a ``system.reset`` which is why these two dummy pointers are required in order to not break memory safety.

**Comment by genotrance** [comment]
This change is a little last minute and breaks nimble in multiple places. I am creating a PR to fix but it might break several others. Also, it doesn't help that it fails at runtime rather than compile time so you never know until a certain code path is exercised.
