### ISSUE TITLE
{.booldefine.} are not considered constants in type sections

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12880]
Test case:

```Nim
const True {.booldefine.} = true

type
  Foo = object
    a: int
    when True:
      b: int
```

Error:
`Error: constant expression expected`

Workaround with `static` so tagging low priority.

```Nim
const True {.booldefine.} = true

type
  Foo = object
    a: int
    when static(True):
      b: int
```

**Comment by timotheecour** [comment]
wondering if same root cause as https://github.com/nim-lang/Nim/issues/12929

EDIT: no because issue still there despite #12880 being fixed

**Comment by disruptek** [comment]
Maybe this should be backported?
