### ISSUE TITLE
Marshal module doesn't work with `--gc:destructors`

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#12881]
Compile with `--gc:destructors`
```nim
import marshal

type
  MyObject = object
    x: seq[float]
    y: string


let z = MyObject(x: @[1.0], y: "name")
echo $$z
echo to[MyObject]($$z)
```
Compiler error:
```
Error: system module needs: newSeq
```
The required function
```nim
proc newSeq(typ: PNimType, len: int): pointer
```
doesn't exist in newruntime

**Comment by Araq** [comment]
The old RTTI is not supported with ``--gc:destructors`` so marshal.nim cannot work. I have plans to support it, but it's going to be a bit messy...

**Comment by Araq** [comment]
Tried to make it work but failed. For now it's not planned to fix it, sorry.
