### ISSUE TITLE
Cannot explicitly instantiate a generic template inside a generic proc

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#12905]
The following simple code fails to compile:

```nim
template newFuture*[T](): auto =
  10

proc someGeneric(x: auto) =
  var ff = newFuture[int]()

someGeneric 10
```

```
Error: 'newFuture' has unspecified generic parameters
```

Possible work-arounds are to turn `newFuture` into a proc or to use type parameters like this:

```nim
template newFuture*(T: type): auto =
  10

proc someGeneric(x: auto) =
  var ff = newFuture(int)

someGeneric 10
```

Within our codebase, we had to go for the second option, because the `newFuture` template uses `instantiationInfo` to obtain line information about the call-site.

```
$ nim -v
Nim Compiler Version 1.0.4
```

**Comment by metagn** [comment]
Works now probably fixed by #21671
