### ISSUE TITLE
strformat ought to support comma (,) format

### ISSUE THREAD

**Issue by mark-summerfield** [nim-lang/Nim#12903]
strformat ought to support the comma (,) format for simple thousands grouping
For example:
```nim
import strformat
n = 1_234_567
echo  &"{n} {n:,}"
```
would output (just like Python does):
```
1234567 1,234,576
```

**Comment by Araq** [comment]
But that's language specific so then strformat would depend on your current locale. Not good.

**Comment by mark-summerfield** [comment]
OK.
