### ISSUE TITLE
Pragmas async+discardable should be a Syntax Error

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12912]
Pragmas `{.async.}` and `{.multisync.}` combined with `{.discardable.}` 
should be a Syntax Error or at least a compile time Warning.

### Example
```nim
import asyncdispatch

proc foo(): Future[void] {.async, discardable.} = discard
proc bar(): Future[void] {.multisync, discardable.} = discard

```

Similar but not the same https://github.com/nim-lang/Nim/issues/11912#issue-478298948
recommends adding an  `{.undiscardable.}` pragma for `discard asyncProc()`, 
this bug is about the combination of `{.async, discardable.}` should be a Syntax Error.
I guess should not be too complicated to get a list of pragmas and if both found together thrown error.

**Comment by Clyybber** [comment]
I think #11912 is a better solution. (Hardcoding a check like proposed in this issue into the compiler is a bad idea/hack IMO)
In this case with `type T {.undiscardable.}` a definition like this: `proc foo(): T {.discardable.} = ...` should error.

**Comment by juancarlospaco** [comment]
I agree, but still something can be done to improve when using `{.async, discardable.}`, 
it can even be improving the documentation on that specific topic, 
Ive observed new people tend to try to use such construct when the compiler says that the `Future` can not be discarded.
:thinking:

**Comment by juancarlospaco** [comment]
I am not sure what you mean by *Hardcoding checks*, 
all Syntax Errors are kinda "Hardcoded checks" arent they?,
how do you configure a Syntax Error?, theres no way a `{.async, noreturn.}` is the desired syntax whatsoever.
:thinking:

**Comment by dawkot** [comment]
I think you're missing that `async` is a custom pragma, not one built into the compiler. 
https://nim-lang.org/docs/manual.html#macros-macros-as-pragmas

**Comment by mratsim** [comment]
macros as pragmas have visibility into the other pragmas of a proc

```Nim
import macros

macro myPragma(procDef: untyped): untyped =
  echo procDef.toStrLit()
  result = procDef

proc randomInt(): int {.myPragma, discardable.} =
  result = 4 # A perfectly random integer

randomInt()
```
CompileTime output:
```Nim
proc randomInt(): int {.discardable.} =
  result = 4
```
So it's just a matter of policy, the change is easy.

**Comment by dom96** [comment]
Yeah, this should be a trivial change in the macro.

**Comment by alehander92** [comment]
and what if it is discardable, async

**Comment by Clyybber** [comment]
@alehander92 Doesn't matter, the compiler is magic :)

**Comment by alehander92** [comment]
sorry, i now realized how it must work :D
