### ISSUE TITLE
stdout cannot be reassigned on some systems

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#12939]
Consider:
```nim
var f: File
  
stdout = f
```

On Ubuntu and OSX, this works fine. In my code, I am backing up stdout and restoring it later.

However, on Windows I see:
```
error: lvalue required as left operand of assignment
  stdout = f__diPCTL71W7KGJSC9aB9avGTw;
```

On the Nim playground, I see:
```
error: assignment of read-only variable 'stdout'
  stdout = f_aaZ4Cbdkmq1Yxbybfr175A;
```

stdout is a [var](https://github.com/nim-lang/Nim/blob/devel/lib/system/io.nim#L38) so it should be writable in theory.

**Comment by Araq** [comment]
Use ``system.reopen`` instead.

**Comment by genotrance** [comment]
I am using reopen for Windows but cannot recover stdout when I want it back later on in my program.

https://github.com/nimterop/nimterop/blob/master/nimterop/toast.nim#L171

Any reason why this shouldn't work consistently across OS?

**Comment by genotrance** [comment]
stdout cannot be reassigned on some systems. glibc is okay with it but it fails on Windows and musl based systems. This isn't a Nim issue.

https://stackoverflow.com/questions/1908687/how-to-redirect-the-output-back-to-the-screen-after-freopenout-txt-a-stdo
