### ISSUE TITLE
nim compiler assertion fail when literal integer is passed as template argument for array size

### ISSUE THREAD

**Issue by damirjugovic** [nim-lang/Nim#12938]
As the title says - compiler crashes when I try to pass literal integer to array type construct.
### Example
```
type
  ExampleArray[Size, T] = array[Size, T]

var integerArray : ExampleArray[32, int]  # Compiler crash!
echo(integerArray.len)
```

### Current Output
```
$ nim compile --run array.nim
Hint: used config file 'C:\nim-1.0.4\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: array [Processing]
fatal.nim(39)            sysFatal
Error: unhandled exception: int128.nim(72, 11) `arg.sdata(2) == 0` out of range [AssertionError]
```

It works when I specify type only, but I can't get the array length:
```
type
  ExampleArray[T] = array[32, T]

var integerArray : ExampleArray[int]
echo(integerArray.len)   # I get 32, as expected
```

I can implement this by using sequence instead of array, but I'm curious why this doesn't work since array length is known at compile time. Here's my nim version:
```
$ nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by dumjyl** [comment]
It works with static int.
```nim
type ExampleArray[Size: static int, T] = array[Size, T]
```

**Comment by damirjugovic** [comment]
That seems to work, thanks.
Still, it would be nice to see friendlier compile error message.

**Comment by bung87** [comment]
this is more specifc to generic type, the array size will turns to a range, after instantiation you get range[int64], it calculate length of that range, then it will overflow. so `static int` is needed here.
