### ISSUE TITLE
Compile, run and discard output file

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#12940]
If I have this file:

~~~nim
echo "sunday monday"
~~~

I can run like this:

~~~
nim c -r day.nim
~~~

However this creates `day.exe`. I dont want that. I mean, I *do* want that, but
not when using `-r`. Does Nim have a way to deal with this? Something like:

- create file in local directory, but delete it right after running
- create and run file from temp directory
- something else

I see these options:

~~~
--out:FILE
--outdir:DIR
~~~

but they are not ideal, as I would only want to use them with `compile --run`,
not `compile`.

Go has `go run` and D has `ldc2 -r`, which accomplish what I am looking for.

**Comment by dumjyl** [comment]
Nim can add custom commands through its nimscript based configuration system.

See: https://github.com/kaushalmodi/nim_config/blob/master/config.nims#L386
To achieve the desired behavior you would only need to add `switch("outdir", os.get_temp_dir())`
Then `nim runc day`

**Comment by juancarlospaco** [comment]
`nim c -r` is because Nim multiple compilation targets, can also be `nim cpp -r` or `nim js -r` or can also be Interpreted `nim e`, etc.

**Comment by cup** [comment]
@juancarlospaco 

> because Nim multiple compilation targets

because Nim what?

> can also be `nim cpp -r` or `nim js -r` or can also be Interpreted `nim e`

even if thats true, so? `nim c -r` doesnt have to have the same behavior as anything else. Also your examples seems like counter examples, as I would suspect that users of `nim cpp -r` and `nim js -r` dont have a need for any resultant file either.

**Comment by SolitudeSF** [comment]
you can create your own command. current behavior shouldnt change.

**Comment by cup** [comment]
This seems to do the trick:

~~~nim
# %APPDATA%\nim\config.nims
import os
task run, "run":
   setCommand("compile")
   switch("run")
   switch("outdir", os.get_temp_dir())
~~~

**Comment by cup** [comment]
https://github.com/kaushalmodi/nim_config/issues/18

**Comment by cup** [comment]
@dumjyl isnt it `getTempDir`?

https://nim-lang.github.io/Nim/os#getTempDir

**Comment by SolitudeSF** [comment]
@cup https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality
might wanna read this document before proceeding with anything else

**Comment by Araq** [comment]
Problem with deleting the ``.exe`` is that it's not cached then anymore and caching is *very* useful. We could output the .exe file to nimcache/ though...

**Comment by timotheecour** [comment]
as mentioned in https://github.com/nim-lang/Nim/issues/7402#issuecomment-375810580, the way rdmd handles this in D allows caching multiple binaries:
```
rdmd -version=foo1 main.nim # fresh compilation 1
rdmd -version=foo2 main.nim # fresh compilation 2
rdmd -version=foo1 main.nim # uses cached compilation 1 => instant
rdmd -version=foo2 main.nim # uses cached compilation 2 => instant
```
the hashing itself is very similar to nim's hashing (which hashes cmd line options, nim binary, etc)

**Comment by Benjamin-Lee** [comment]
I don't think requiring every user to make their own command for this is particularly user friendly. As a new user, I think that a `run` command would be a great addition. The argument that

>nim c -r is because Nim multiple compilation targets

Doesn't make sense to me since `nim c` *already* assumes the C compilation target if I understand correctly.

**Comment by juancarlospaco** [comment]
Doesn't make sense because `nim cpp` assumes the C++ compilation target too.
:man_shrugging:

**Comment by Araq** [comment]
Let's cache it in ``nimcache`` then.

**Comment by Clyybber** [comment]
This has been implemented as `nim r file.nim`.
