### ISSUE TITLE
non owned ref outlive owned ref it stems from without any kind of error

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#12953]
### Example
```nim
type A = ref object
  x: int

let a: A = A() # a ref of the owned ref is taken, the owned ref is discarded

echo a.x
```

```nim
type
    B = ref object
    A = ref object
        b: B
proc narg(): owned A =
    result = A()
    result.b = B() # the same as above

discard narg()
```

### Current Output
Both run without any problem

### Expected Output
A compile error, both cases are simple enough to be detectable at ct.

### Additional Information

```
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2019-12-22
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 2e7c9eb6a8dea7e4ca6b268020058b46f6b16580
active boot switches: -d:release
```

**Comment by RSDuck** [comment]
after a little bit of debugging it seems like both examples show the same symptom they aren't related in their origin. While the second one barely passes without the [appropriate error](https://github.com/nim-lang/Nim/blob/devel/compiler/semexprs.nim#L1610), for the first one I don't even know if it ever gets near such a check.

**Comment by Araq** [comment]
I digged a bit and this check is not implemented yet. It requires us to distinguish between locations of type ``owned`` that can be aliased because they are not constructions.

**Comment by ringabout** [comment]
`newruntime` has been deprecated, it is taken over by `ARC` and `ORC`.
