### ISSUE TITLE
Regression rst2html devel

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12980]
`nim rst2html file.rst` is broken on Devel `1.1.1`, but works Ok on Stable `1.0.4`,
this is important for people contributing Documentation.

# Devel Vs Stable

![rst2html](https://user-images.githubusercontent.com/1189414/71542429-2a74c780-2945-11ea-945d-8949c36d7a37.png)

Basically a file `nimdoc.css` is missing. `nimdoc.css` is not written anywhere on output directory.

For this to have good UX and usability it should just `staticRead` the CSS into the HTML directly,
if you have to download additional files to view the HTML it kinda defeats the purpose IMHO.

**Comment by juancarlospaco** [comment]
This does not Repro anymore on devel. Some PR Fixed it.

**Comment by Clyybber** [comment]
Probably https://github.com/nim-lang/Nim/pull/13176
