### ISSUE TITLE
Incorrect stack traces for exception in iterators

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1298]
It seems that the following code produces an incorrect stack trace:

``` nimrod
import json

var blah = newJArray()

proc test(foo: PJsonNode) =
  for key, val in pairs(foo):
    echo key

test(blah)
```

Output:

```
Traceback (most recent call last)
a11.nim(9)               a11
json.nim(869)            test
system.nim(2823)         failedAssertImpl
system.nim(2061)         raiseAssert
Error: unhandled exception: node.kind == JObject  [EAssertionFailed]
```

According to the stack trace, the `test` proc appears to be in json.nim but it's really not.

**Comment by mbaulch** [comment]
This seems to be fixed in 0.14.2 (and devel). Not sure when or how. Time to close this issue?

**Comment by mbaulch** [comment]
Correction: not fixed. The example given by @flaviut has a slightly different trace. test is *still* in json. Sorry!

**Comment by Yardanico** [comment]
Still wrong stack trace on devel

**Comment by andreaferretti** [comment]
Currently it gives this stack trace

```
t1298.nim(9)             t1298
system.nim(3769)         test
system.nim(3759)         failedAssertImpl
system.nim(3752)         raiseAssert
system.nim(2805)         sysFatal
Error: unhandled exception: /Users/andrea/.mynim/devel/lib/pure/json.nim(696, 10) `node.kind == JObject`  [AssertionError]
```

which still looks wrong since `test` has now moved to `system.nim`

**Comment by Araq** [comment]
> It seems that the issue is that the stack trace does not push the frame information when control flips back to the iterator.

Iterators have no stack frame that's attached to them as they are inlined.

> I'm not sure about the feasibility of fixing this, especially as its still understandable once you know whats happening.

Yep.
