### ISSUE TITLE
`_` is treated differently as a parameter name (than as a variable name)

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#12999]
### Example
```nim
proc foo(_: int, _: float) = discard
```

### Current Output
```
attempt to redefine: '_'
```

### Expected Output
No error because constructs named `_` are normally inaccessible and so can be defined in the same scope, like this:
```nim
var
  _: int
  _: float
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.0.4
```

**Comment by metagn** [comment]
Works since #21192

**Comment by metagn** [comment]
This is already plenty tested: https://github.com/nim-lang/Nim/blob/devel/tests/proc/tunderscoreparam.nim, just closing
