### ISSUE TITLE
string add '&' replace to '+'

### ISSUE THREAD

**Issue by zhuxiujia** [nim-lang/Nim#13005]
string add '&' replace to '+'，  Improve readability
for example like python :
``` nim
var sql="select * from "
sql=sql + "table"
echo sql
#  select * from table
```

**Comment by hlaaftana** [comment]
Your example can be written as

```nim
var sql = "select * from "
sql.add("table")
echo sql
```

which is arguably more readable than using an operator, in which case you would use `&=`. `&` will most likely never be replaced with `+`, so you're just going to have to accept it as is.

**Comment by cooldome** [comment]
You can find a lot of information in the internet on why using `+` for string concatenation is a bad idea.
Operator priorities is clear wrong when `+` operator is used.

Sorry, won't fix.
