### ISSUE TITLE
regression(1.0.4): undeclared identifier: 'readLines'; plus another regression and bug

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13013]
/cc @cooldome  @araq
the recent #12807 introduced 2 regressions and a bug; see my proposal below for the proper fix to #12788

### Example
```nim
echo readLines(currentSourcePath, 3)
```

### Current Output
nim devel as of #12807:
Error: undeclared identifier: 'readLines'
nim before #12807:
works

### Expected Output
works

## problem 2: BUG 
`staticReadLines` is a bad name as it indicates the proc is evaluated at CT but that's misleading:
this compiles and runs but returns the lines read at runtime
```
echo staticReadLines(currentSourcePath, 3)
```
it should instead behave like `staticRead`:
`Error: 'staticRead' can only be used in compile-time context`

## problem 3: regression
* before this PR, we could build nim directly in 1 step from latest release 1.0.4
* after this PR, we cannot and have to use the much slower bootstrap via `koch boot`, which is really bad for working on nim
```
nim_104 c -o:bin/nim.temp.3 compiler/nim.nim
compiler/vmops.nim(150, 13) Error: undeclared identifier: 'staticReadLines'
```

## proposal
A better fix for https://github.com/nim-lang/Nim/issues/12788 is to:

* add a deprecated proc with 1 arg:
```nim
proc readLines(filename: string, n: Natural): seq[TaintedString] = # same as before
proc readLines(filename: string): seq[TaintedString] {.deprecated: "use the 2 arg version".} = readLines(filename, 1)
```
* not bother renaming readLines to staticReadLines at CT, **this static prefix just causes more issues** (the const or non-const is deduced by calling context instead), just like we have `fileExists` that works at RT and CT without needing `staticFileExists`.

The static prefix in practice just kicks the problem further in user hand as he has to write ugly code like that:

```nim
proc fun()=
  when nimvm:
    funAux(staticReadLines(input, 1));
  else: 
    funAux(readLines(input, 1));
```

## Additional Information
D20200102T174949
occurs in nim devel c949b81efdeb08b38224e1678ad140b7b7663b15

**Comment by cooldome** [comment]
@Araq: should I do the proposed changes?

**Comment by Araq** [comment]
Alright, let's try it.
