### ISSUE TITLE
C++ based exception handling

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#13039]
I have no test for now that shows the problem but for C++ we generate Exceptions with a VTable and C++ puts the VTable at offset 0. However, the Nim runtime (both old and new) assumes that at offset 0 there is the PNimType field for objects with enabled inheritance. Can we avoid the VTable in C++? Or maybe we can come up with other solutions...

@cooldome

**Comment by disruptek** [comment]
The test is in #11081, no?

**Comment by Araq** [comment]
@disruptek Probably.

**Comment by cooldome** [comment]
Hi Araq, 
The reason for VTable is the following:
```nim
try:
  call()
except:
 # compiles to `catch(...)`  and can catch either cpp or nim exception. 
 # We don't know what we caught, but if it is a Nim exception we need to call popCurrentExceptionEx 
```
The only idea I have is to implement cpp exception handling in `excpt.nim` such that  it doesn't use global variable `currException` then `popCurrentException` will not be needed and we can get rid of VTable as well.

**Comment by Araq** [comment]
Why don't we generate this code instead

```C++

try {

} catch (Exception e) { // Should have been exported as NimException btw
  // Exception from Nim land, what else
} catch (...) {
  // Exception from C++ land, what else
}
```

**Comment by cooldome** [comment]
That should work too. This case needs extra care to avoid duplicate catch, but it is straightforward exercise:
```nim
try:
   xx:
except Exception:
  ...
except:
  ...
```

**Comment by ringabout** [comment]
implemented by https://github.com/nim-lang/Nim/pull/13695
