### ISSUE TITLE
ARC repr is not available for newruntime Minor

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#13076]
When you compile with `nim c --gc:arc file.nim` and you used `repr` the compiler says that is not available when using `--newruntime`.

I did not use `--newruntime`, I used `--gc:arc` and `--gc:orc`, 
then the compiler message is kind of confusing for new users, 
is just that changing the compiler message.

### Example
```nim
echo repr(42)
```

### Current Output
```
Error: 'repr' is not available for --newruntime
```

### Possible Solution

```
Error: 'repr' is not available for --newruntime or --gc:arc or --gc:orc
```
But enumerating one-by-one feels kinda verbose, maybe something like:

```
Error: 'repr' is not available for the compiler options used.
```

### Additional Information

* Nim devel.
* This is a Minor bug. This is an Easy bug.

**Comment by Araq** [comment]
*sigh* we can also simply support the old type information with the new runtime.

**Comment by juancarlospaco** [comment]
Oh, fixing the message was good, but if it can be improved, even better.
