### ISSUE TITLE
Think about the title, twice

### ISSUE THREAD

**Issue by mahedi7up** [nim-lang/Nim#13074]
#@Function `echo` outputs the wrong string.

### Example
```nim
echo "Hello World!"
```

### Current Output
```
Hola mundo!
```

### Expected Output
```
Hello World!
```

### Possible Solution

* In file xyz there is a call that might be the cause of it.

### Additional Information

* It was working in version a.b.c
* Issue #abc is related, but different because of ...
* This issue is blocking my project xyz

```
$ nim -v
Nim Compiler Version 0.1.2
```

**Comment by mratsim** [comment]
Welcome to the Nim community,

Be sure to checkout out our IRC, Gitter, Telegram, Matrix and/or Discord channels (all bridged except Telegram): https://github.com/nim-lang/Nim#community

**Comment by mahedi7up** [comment]
Yes

**Comment by mahedi7up** [comment]
https://ira-phone-bazer.business.site
