### ISSUE TITLE
VM: const case object gets some fields zeroed out at runtime

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13081]
when a const case object is used at runtime, some fields get re-initialized to 0. But not all, see below

### Example
```nim
  type Kind = enum
    k0, k1, k2, k3

  type Foo = object
    x0: float
    case kind: Kind
    of k0: discard
    of k1: x1: int
    of k2: x2: string
    of k3: x3: string

  const j1 = Foo(x0: 1.2, kind: k1, x1: 12)
  const j2 = Foo(x0: 1.3, kind: k2, x2: "abc")
  const j3 = Foo(x0: 1.3, kind: k3, x3: "abc2")
  static:
    echo j1
    echo j2
    echo j3
  echo j1
  echo j2
  echo j3
```

### Current Output
```
(x0: 1.2, kind: k1, x1: 12)
(x0: 1.3, kind: k2, x2: "abc")
(x0: 1.3, kind: k3, x3: "abc2")
Hint: 29857... [SuccessX]
(x0: 1.2, kind: k1, x1: 0)
(x0: 1.3, kind: k2, x2: "")
(x0: 1.3, kind: k3, x3: "abc2")
```

### Expected Output
```
(x0: 1.2, kind: k1, x1: 12)
(x0: 1.3, kind: k2, x2: "abc")
(x0: 1.3, kind: k3, x3: "abc2")
Hint: 29857... [SuccessX]
(x0: 1.2, kind: k1, x1: 12)
(x0: 1.3, kind: k2, x2: "abc")
(x0: 1.3, kind: k3, x3: "abc2")
```

### workaround
use `const x2 = j2.x2`, the x2 will get correct value at RT since it's not a case object

### Additional Information

* devel 5e9ebe9ec1d1df62e3b1347bb7b8c9c8a08a3cc5

* related: https://github.com/nim-lang/Nim/issues/11862
* related: https://github.com/nim-lang/Nim/issues/8015#issuecomment-491424148
> Const case objects never were supposed to compile, there is logic in the compiler to detect and reject that but as we can see it's not triggered.

however IMO compiler SHOULD support case objects, instead of outright disabling them. It makes more code usable at CT, even if above mentioned caveats; the workaround mentioned above works; whereas if we outright disabled const case objects, we'd have no easy equivalent of this (not without some contorsions at least)
```nim
const j = getFoo() # potentially expensive computation at CT; => only do it once
const x1 = j.x1
const x2 = j.x2
```
so let's fix it instead of disabling it :)

If there's one thing we may disable until this is fixed, it's the runtime access to a const case object field

**Comment by cooldome** [comment]
I believe it is related issue
https://github.com/nim-lang/Nim/pull/13178.

**Comment by timotheecour** [comment]
@cooldome  I just tried your PR, it doesn't fix the above bug (note that this issue isn't using `--gc:arc`, and your PR mentions `arc`)

**Comment by cooldome** [comment]
Retested on latest dev and it works for me.
@timotheecour please retest

**Comment by timotheecour** [comment]
* just retested, the top example now works, the underlying problem is still there as shown in https://github.com/nim-lang/Nim/pull/15529:
```nim
block: # bug #13081
  type Kind = enum
    k0, k1, k2, k3

  type Foo = object
    x0: float
    case kind: Kind
    of k0: discard
    of k1: x1: int
    of k2: x2: string
    of k3: x3: string

  const j1 = Foo(x0: 1.2, kind: k1, x1: 12)
  const j2 = Foo(x0: 1.3, kind: k2, x2: "abc")
  const j3 = Foo(x0: 1.3, kind: k3, x3: "abc2")
  static:
    doAssert $j1 == "(x0: 1.2, kind: k1, x1: 12)"
    doAssert $j2 == """(x0: 1.3, kind: k2, x2: "abc")"""
    doAssert $j3 == """(x0: 1.3, kind: k3, x3: "abc2")"""
  doAssert $j1 == "(x0: 1.2, kind: k1, x1: 12)"
  doAssert $j2 == """(x0: 1.3, kind: k2, x2: "abc")"""
  doAssert $j3 == """(x0: 1.3, kind: k3, x3: "abc2")"""

  when true:
    # BUG: this doesn't work yet
    # Error: unhandled exception: 'sons' is not accessible using discriminant 'kind' of type 'TNode' [FieldDefect]
    discard j1.x1
    static:
      # ditto
      discard j1.x1
```

note, this also affects https://github.com/nim-lang/Nim/pull/15528

* we also need to git bisect to find which commit fixed at least the top example

EDIT: => https://github.com/nim-lang/Nim/issues/15532
