### ISSUE TITLE
(debian/ubuntu) apt repository nim version is old.

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#13087]
### Summary

(debian/ubuntu) apt repository update more frequently

### Description

nim reached 1.0 but ubuntu 18.04.03 lts apt repository nim version is 0.17.2-1ubuntu2

**Comment by dom96** [comment]
This isn't a Nim bug, Debian/Ubuntu releases usually contain pretty old versions of software.

@FedericoCeratto can say more.

**Comment by FedericoCeratto** [comment]
Debian ships Nim 1.0.4 in the Unstable (aka Sid), the Testing and the Buster-backports archives and they are usually kept up-to-date with new releases within one or two days.

Ubuntu fetches the packages from Debian automatically, but with their own time. Right now Ubuntu focal is on 1.0.4
