### ISSUE TITLE
system.nim errors out when compiling with --gc:arc

### ISSUE THREAD

**Issue by Kaleidosium** [nim-lang/Nim#13107]
When running my code using --gc:arc, it seems like system.nim errors out for some reason.

### Current Output
```powershell
λ make
Hint: used config file 'C:\Users\rifkik\nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\rifkik\Documents\Code\RioluCookies\nim.cfg' [Conf]
Hint: used config file 'C:\Users\rifkik\nim\config\config.nims' [Conf]
Hint: system [Processing]
C:\Users\rifkik\nim\lib\system\mmdisp.nim(505, 24) Error: undeclared identifier: 'Cell'
make: *** [Makefile:129: all] Error 1
```

### Expected Output
Successfully compiles system.nim

### Additional Information

* This never worked in the nightly builds either.
* This issue is blocking my project which is currently closed source, but I will make it public on demand.

```powershell
λ nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-01-11
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 767592a3c350fca6fc6f01f519a814c0498167f9
active boot switches: -d:release
```

**Comment by Araq** [comment]
This is most likely an installation problem, the new Nim picks up an outdated system.nim. Or maybe your Nim configuration contains wrong --defines.

**Comment by Kaleidosium** [comment]
> This is most likely an installation problem, the new Nim picks up an outdated system.nim. Or maybe your Nim configuration contains wrong --defines.

Even on a clean install of the OS, The new Nim does not compile.

Here's my nim.cfg.
```cfg
arm.standalone.gcc.path = "$DEVKITARM/bin"
arm.standalone.gcc.exe = "arm-none-eabi-gcc"
arm.standalone.gcc.linkerexe = "arm-none-eabi-gcc"

--cpu:arm
--os:standalone
--gc:arc
--compileOnly
--nimCache:"source"  # output to 'source' directory
--lineTrace:off
--stackTrace:off
--checks:off
-d:release
--path:"nim-tonc"
```

**Comment by Araq** [comment]
Do not *bootstrap* with --gc:arc that is not supported for now...

**Comment by Kaleidosium** [comment]
Well, that means I can't use ARC, good day sir.

**Comment by Araq** [comment]
You can use it for your own programs and projects but not for ``koch boot -d:release``.
