### ISSUE TITLE
newException terminates msg early from NULL byte, other IO does not

### ISSUE THREAD

**Issue by D-Nice** [nim-lang/Nim#13115]
Error output produced by `raise newException` is inconsistent with other IO such as `echo` or `stdout.write`.

### Example
```nim
const b_null: char = 0.char
var msg = "This char is `" & $b_null & "` and works fine!"

echo msg

raise newException(Exception, msg)
```

### Current Output
```nim
echo msg
# This char is `` and works fine!

raise newException(Exception, msg)
# Error: unhandled exception: This char is `
```

### Expected Output
```nim
echo msg
# This char is `` and works fine!

raise newException(Exception, msg)
# Error: unhandled exception: This char is `` and works fine! [Exception]
```

### Additional Information

* This issue was found via fuzzing some CLI utility, which takes piped input. The error messsage was being cutoff, because the input contained a NULL byte.
EDIT:
* Consistency is the main thing I'd ask for, however, if both could output `^@` for NULL char, that may be better assuming it doesn't introduce needless complexity. 

```
$ nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release

```

**Comment by timotheecour** [comment]
reopening since it doesnt' work for cpp
refs #15930

works in js, vm

**Comment by ringabout** [comment]
Workaround for cpp backend:
```nim
nim cpp -r -d:noCppExceptions app.nim
```

**Comment by timotheecour** [comment]
no need for workaround => https://github.com/nim-lang/Nim/pull/16167

**Comment by timotheecour** [comment]
now that https://github.com/nim-lang/Nim/pull/16167 was merged, the only thing remaining is js backend on openbsd; it's due to an upstream nodejs bug that has been patched in more recent nodejs version, ie outside of nim's control; closing for now, feel free to re-open if you disagree
