### ISSUE TITLE
[TODO] pathutils.`/` can return invalid AbsoluteFile

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13121]
pathutils.`/` can return invalid AbsoluteFile

### Example
```nim
import compiler/pathutils
proc main()=
  var a: AbsoluteDir
  let b = "../foo".RelativeFile
  let c: AbsoluteFile = a/b
  echo c

main()
```

### Current Output
```
../foo
```

### Expected Output
`../foo` is not absolute so there's a loophole in API

### Possible Solution
* making a empty behave as `cwd`
* throwing an exception is another option

### Additional Information

* devel a33b72af4960073b0dca95af3b430baade745b0b
* root cause of https://github.com/nim-lang/Nim/pull/13116#discussion_r365580322

Note: I dislike `AbsoluteFile,AbsoluteDir,RelativeFile,RelativeDir` as I've written in https://github.com/nim-lang/RFCs/issues/71 and I think we can find a better API; at least it's not exposed outside compiler

**Comment by Araq** [comment]
But I like the design very much, bugs are bugs. Empty behave the same as ``cwd`` seems reasonable but who knows what it'll break.

**Comment by timotheecour** [comment]
IMO the correct fix is to throw instead of implying `cwd`.
We've already agreed (see https://github.com/nim-lang/Nim/pull/10018#issuecomment-448192956) it's a bad idea to conflate empty `""` (which means uninitialized) with `cwd`; but while os.`/` can handle the empty case just fine (returning a relative path), it would be a bug (this bug actually) to return a relative path in pathutils.`/` ; one of those gotchas with the current design.

**Comment by Araq** [comment]
Sounds convincing indeed. Let's give it a try.
