### ISSUE TITLE
[wontfix] --gc:arc silently gives different results (when using unsafeAddr )

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13139]
--gc:arc silently makes code behave differently, without warnings, compiler error nor runtime crash, which is bad as it means code may break in subtly hard to diagnose ways when porting to --gc:arc

### Example
```nim
  type Foo = object
    x: string
  proc fun(a: Foo) =
    a.unsafeAddr[].x[0] = 'H'
  let b = Foo(x: "hello")
  fun(b)
  echo b
```

### Current Output
with --gc:arc:
```
(x: "hello")
```

### Expected Output
should give same result as without `--gc:arc`:
```
(x: "Hello")
```

### Additional Information
* recent devel a33b72af4960073b0dca95af3b430baade745b0b

**Comment by Araq** [comment]
This is not "hard to diagnose" though, it's a simple store into readonly memory, 100% deterministic failure.

**Comment by Clyybber** [comment]
It is called `unsafeAddr` for a reason.

**Comment by Araq** [comment]
Here is what happens: ``Foo`` is not passed by pointer so the compiler produces:

```C

N_LIB_PRIVATE N_NIMCALL(void, fun__EL1WmQbdBmRaBaOXHLtIjw)(tyObject_Foo__1uVPNKHIiGEx9aKC34R4aPg a) {
	if ((NU)(((NI) 0)) >= (NU)a.x.len) raiseIndexError2(((NI) 0),a.x.len-1);
	nimPrepareStrMutationV2((&a.x));
	a.x.p->data[((NI) 0)] = 72;
}
```

Which mutates the byvalue parameter's string. You need to use a ``var`` parameter and use ``unsafeAddr`` less frequently.
