### ISSUE TITLE
--gc:arc SIGSEGV with ptr aliasing

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13137]
--gc:arc gives SIGSEGV in snippet below; it works without `--gc:arc`

### Example
```nim
when true:
  var x = "abc"
  let y: ptr char = addr x[0]
  echo y[]
  y[] = 'A'
  echo x
```

### Current Output
```
a
Traceback (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0919.nim(118) t0919
SIGBUS: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
a
Abc
```

### Additional Information
* recent devel a33b72af4960073b0dca95af3b430baade745b0b
* maybe related to https://github.com/nim-lang/Nim/issues/13133 (no idea though because code snippet in that issue is quite large)

**Comment by Araq** [comment]
I'm afraid this cannot be supported with the new string implementation. You have to call ``ensureNoLiteral(x)`` first, an API we don't have yet (?)

The implementation for this is in ``nimPrepareStrMutationV2``.

**Comment by cooldome** [comment]
Closed as won't fix

**Comment by timotheecour** [comment]
I think closing is premature; there are things that can be done to at least improve things here
