### ISSUE TITLE
--gc:arc SIGSEGV, while --gc:refc works fine.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#13133]
Code: https://gist.github.com/treeform/038fe8269f149678e199a71fb8c5388d

I was looking at some benchmarks from https://github.com/kostya/benchmarks#mandelb to try out with `arc`, this one does not work

Crash:
`nim c --gc:arc -d:release /p/nimbench/bf.nim`

While this works:
`nim c --gc:refc -d:danger /p/nimbench/bf.nim`

```
Nim Compiler Version 1.1.1 [MacOSX: amd64]
Compiled at 2020-01-08
Copyright (c) 2006-2019 by Andreas Rumpf
```

**Comment by timotheecour** [comment]
@treeform can you fix the title? s/arg/arc (to make it more searchable)

**Comment by timotheecour** [comment]
I realized the code you provided is large, can you try to generate a minimal example? this helps with de-duping (eg is this same as https://github.com/nim-lang/Nim/issues/13137 ?) and fixing

**Comment by jyapayne** [comment]
I just tested this on latest devel and it works for me with no SIGSEGV. Maybe it's fixed?

```bash
Nim Compiler Version 1.1.1 [MacOSX: amd64]
Compiled at 2020-02-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: ceb3d5ad68a29d8800333c2f5065bc12cdce9cd1
active boot switches: -d:release
```

**Comment by Araq** [comment]
Reopen if still a problem, we fixed plenty of bugs.
