### ISSUE TITLE
Error detection of pcLinkToFile

### ISSUE THREAD

**Issue by EchoPouet** [nim-lang/Nim#13174]
Hello,

File info of a symbolic link return pcFile and not pcLinkToFile.

### Example
To create symbolic link :
```
$ echo "Hello World" > hello.txt
$ ln -s hello.txt hello_link.txt
$ ll
lrwxrwxrwx 1 XXX domain users    9 janv. 16 19:09 hello_link.txt -> hello.txt
-rw-r--r-- 1 XXX domain users   12 janv. 16 19:08 hello.txt
```

and the code to check info :
```nim
import os

echo "hello_link.txt is link ? -> ", getFileInfo("hello_link.txt").kind == pcLinkToFile
```

### Current Output
```
hello_link.txt is link ? -> false
```

### Expected Output
```
hello_link.txt is link ? -> true
```

### Additional Information

* Ubuntu 18.04 64 bits

```
$ nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by a-mr** [comment]
Not a bug.  
According to [getFileInfo doc](https://nim-lang.org/docs/os.html#getFileInfo,string) :

> When `followSymlink` is true (default), symlinks are followed and the information retrieved is information related to the symlink's target. Otherwise, information on the symlink itself is retrieved.

This works fine:
> getFileInfo("hello_link.txt", **followSymlink=false**).kind == pcLinkToFile
