### ISSUE TITLE
Type tyAnything can't be matched to proc argument of typedesc type

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#13193]
Building on #13095 and its fix #13181, supportsCopyMem in a type section doesn't work with implicit generic parameters.
The error message in particular mentions `type any` which makes it hard to debug as there is no `type any`  in the codebase.

Test case
```Nim
import typetraits

type
  CpuStorage[T] {.shallow.} = ref object
    when supportsCopyMem(T):
      raw_buffer*: ptr UncheckedArray[T] # 8 bytes
      memalloc*: pointer                 # 8 bytes
      isMemOwner*: bool                  # 1 byte
    else: # Tensors of strings, other ref types or non-trivial destructors
      raw_buffer*: seq[T]                # 8 bytes (16 for seq v2 backed by destructors?)

  Tensor*[T] = object
    storage*: CpuStorage[T]

proc foo(t: Tensor): bool =
  # This breaks
  return false

proc bar[T](t: Tensor[T]): bool =
  return false
```

Error
```
Error: type mismatch: got <type any>
but expected one of: 
proc supportsCopyMem(t: typedesc): bool
  first type mismatch at position: 1
  required type for t: type T
  but expression 'T' is of type: type any

expression: supportsCopyMem(T)
```

**Comment by cooldome** [comment]
Test case is not complete, it doesn't reproduce the issue

**Comment by mratsim** [comment]
It does for me on commit bc14453f69b9bde449cb52655eb6ffe571d6a28b

![image](https://user-images.githubusercontent.com/22738317/72679529-57357e00-3ab0-11ea-9f15-a55e183b82a3.png)

**Comment by cooldome** [comment]
Apologies, I managed to replicate this issue. I had a look, issue is not type trait specific. Generally type `tyAnything` can't be matches against type `tyTypeDesc`. Simplified example that fails with the same error
```nim
proc mycheck(t: typedesc): bool =
  true

type
  CpuStorage[T] {.shallow.} = ref object
    when mycheck(T):
      raw_buffer*: ptr UncheckedArray[T] # 8 bytes
      memalloc*: pointer                 # 8 bytes
      isMemOwner*: bool                  # 1 byte
    else: # Tensors of strings, other ref types or non-trivial destructors
      raw_buffer*: seq[T]                # 8 bytes (16 for seq v2 backed by destructors?)

proc foo(t: CpuStorage): bool =
  # This breaks
  return false
```

**Comment by Clyybber** [comment]
The underlying issue here is that in `Generic[T]`, `T` defaults to `any` instead of `type` as it IMO should. (I think @timotheecour also discovered that in some PR)

Both examples compile after replacing `CpuStorage[T]` with `CpuStorage[T: type]`

**Comment by mratsim** [comment]
For posterity, from our IRC discussion back in April

From IRC: https://irclogs.nim-lang.org/21-04-2020.html#14:46:18

![image](https://user-images.githubusercontent.com/22738317/94531427-d6cd3c80-023c-11eb-8a22-59dd9a2144cb.png)

**Comment by metagn** [comment]
Both examples above seem to work now? Probably because of #22029
