### ISSUE TITLE
toSeq and openarray iterators interact weirdly.

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#1320]
Passing the result of `toSeq` to an iterator that takes an `openarray` argument and iterates over that argument generates C code with duplicate variables that cannot be compiled.

Example:

```nimrod
import sequtils

iterator pp(s: openarray[int]): int =
  for a in s:
    yield a

for p in pp(toSeq(1..10)):
  echo p
```

**Comment by Araq** [comment]
Now compiles, runs and produces the right result.
