### ISSUE TITLE
Template calls with no parentheses have type None if proc has the same name

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#13209]
Even when the proc has parameters.

### Example
```nim
proc typing(a: int) =
  echo a

template typing =
  echo "foo"

typing
```

### Current Output
```
/usercode/in.nim(7, 1) Error: expression 'typing' is of type 'None' and has to be discarded
```

### Expected Output
```
foo
```

The `typing` statement is of node kind OpenSymChoice

```
$ nim -v
Nim Compiler Version 1.0.4
```

**Comment by SolitudeSF** [comment]
~~you still need to call the template with `()`~~
nvm

**Comment by metagn** [comment]
No

**Comment by Araq** [comment]
There is no rule in the spec that says "for a choice of symbols, pick the template because templates can be called without ``()``". And such a rule would be terrible. You overloaded it, you must resolve it, don't make the compiler guess, you might as well might have meant the proc's address.

**Comment by metagn** [comment]
I was just thinking in a void context with no discard, the template wins. But I can see how annoying that would be to implement. The error message took a while for me to decipher though. This isn't as confusing, but demonstrates the lack of information:

```nim
proc foo(a: int) = echo a
proc foo(a: string) = echo a

let y = foo
```

`/usercode/in.nim(4, 5) Error: invalid type: 'None' for let`

Do I open a seperate issue for this?

**Comment by Araq** [comment]
Yes, please.

**Comment by metagn** [comment]
#6359 reported it already
