### ISSUE TITLE
relativePath("foo", "/") and relativePath("/", "foo") is wrong

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13222]
relativePath("foo", "/") and relativePath("/", "foo") is wrong.
more generally, `relativePath(absPath, relPath)` and `relativePath(relPath, absPath)` should raise

### Example
```nim
import std/os
echo relativePath("foo", "/")
echo relativePath("/", "foo")
```

### Current Output
```
../foo
..//
```

### Expected Output
* ideally, this would throw
* else, this would return `""` (empty, meaning invalid; although not all procs treat empty as invalid, eg `"" / "foo"` would return "foo", masking the error)

### Additional Information
* devel 2fad7f134fa8cf871cdf6ccdcedc6df0d62c2f64

**Comment by a-mr** [comment]
Ideally it would resolve relative paths w.r.t. current working directory. But `getCurrentDir` is not available for nimscript. So we would have to either remove `relativePath` from nimscript or add `getCurrentDir` to nimVM?

**Comment by disruptek** [comment]
`getCurrentDir` will be accepted if implemented for the VM.

**Comment by andreaferretti** [comment]
> Ideally it would resolve relative paths w.r.t. current working directory.

Agreed
