### ISSUE TITLE
[ARC] Too many =destroy calls

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#13250]
@Clyybber:

```
# nim c --gc:arc -r /tmp/t.nim

type Foo = object
  val: int

proc `=destroy`(f: var Foo) =
  echo "del foo ", f.val

var foos: seq[Foo]

foos.add Foo(val: 1)
foos.add Foo(val: 2)
```

Output is:

```
del foo 0
del foo 0
del foo 0
del foo 0
del foo 1
del foo 2
```

**Comment by Clyybber** [comment]
This is expected. With the current design an `if f.notZeroedOut: ...` is required in `=destroy`.

**Comment by Araq** [comment]
How is this expected? We move the object constructions into ``foos`` without a destructor injection and then we destroy the seq.

**Comment by Araq** [comment]
Never mind, I figured it out too. Bummer.
