### ISSUE TITLE
Flag Latest Release

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#13264]
@narimiran 
I am trying to automate the creation of Dash/Zeal documentation for Nim. It would be really helpful if the latest Nim release would be flagged as such.

[Linking to releases](https://help.github.com/en/github/administering-a-repository/linking-to-releases)

Thanks for your support! Awesome project, awesome community!

**Comment by ghost** [comment]
Aren't they tagged though?
https://github.com/nim-lang/Nim/releases

**Comment by schmidh** [comment]
They are tagged, but not as "Latest". 

[Example for "Latest Release." tag](https://github.com/atom/atom/releases)

I just found five minutes ago a different solution. More work, but it's ok.
