### ISSUE TITLE
Invalid codegen with array of empty objects

### ISSUE THREAD

**Issue by refi64** [nim-lang/Nim#13271]
### Example
```nim
type
  A = object

let a = [A(), A(), A()]
echo a
```

### Current Output
```
/usercode/nimcache/@min.nim.c:70:75: error: expected expression before ',' token
 NIM_CONST tyArray__8B6FAtvwPwpwcMNdXldGVQ TM__JXJjWlLylejo6nWONmO6cA_2 = {,
```

### Expected Output
Compilation should succeed.

### Possible Solution

I'm thinking there just needs to be a special case somewhere for handling this?

### Additional Information

Leaving the array with only one `A()` inside causes compilation to succeed. Any more than that fails.

```
$ nim -v
Nim Compiler Version 1.0.6
```

**Comment by ghost** [comment]
This works on latest devel though
