### ISSUE TITLE
seq have `del` strings have `delete` decide for one

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#13287]
seq have `del` strings have `delete`.
but should have similar interface.

### Possible Solution

* decide for either `del` or `delete` and deprecate the other

**Comment by SolitudeSF** [comment]
they do different things. and having del for strings doesnt really make sense.

**Comment by metagn** [comment]
Seqs also have delete

**Comment by narimiran** [comment]
From https://nim-lang.github.io/Nim/system.html#system-module-seqs:

Proc | Usage
-- | --
delete | Delete an item while preserving the order of elements (O(n) operation)
del | O(1) removal, doesn't preserve the order
