### ISSUE TITLE
Control proc string argument output in compiler - not always mirrored with surrounding "

### ISSUE THREAD

**Issue by kristianmandrup** [nim-lang/Nim#13297]
Been trying to get Nim to work with ES modules...

### Summary

How to make the JS compiler {.importcpp.} not always interpolate string arguments as a string with `"` in the compiler output?

```nim
# import { x } from 'xyz'
proc esImport*(name: cstring, nameOrPath: cstring) {.
    importcpp: "import { # } from #".}
```

JS compiler Output

```js
import { "x" } from "./x"
```

Should ideally produce un-stringified output for the first string argument

```js
import { x } from "./x"
```

Solution: A new placeholder character or node kind (type) other than `cstring`?

```nim
importcpp: "import { ~# } from #".}
```

### Description

Sample binding functions to import ES6 modules (`esmodules` Nim module):

```nim
import macros, jsffi

# import * from 'xyz'
proc esImportAll*(nameOrPath: cstring) {.importcpp: "import * from #".}

# import xyz from 'xyz'
proc esImportDefault*(name: cstring, nameOrPath: cstring) {.
    importcpp: "import # from #".}

# import { default as abc } from 'xyz'
proc esImportDefaultAs*(name: cstring, nameOrPath: cstring) {.
    importcpp: "import { default as # } from #".}

# import { x } from 'xyz'
proc esImport*(name: cstring, nameOrPath: cstring) {.
    importcpp: "import { # } from #".}
```

Using the ES module bindings in Nim

```nim
import esmodules # custom binding module we created above

# import { default as $ } from 'xyz'
esImportDefaultAs("$")
# import * from 'xyz'
esImportAll("game")  

# referencing constants imported (implicitly available)
const levels {.importjs.} # links to imported var levels via * import
const characters {.importjs "_characters".} 

const game {.importjs "$".} # links to imported default var with alias $
```

The Nim JS compiler by default spits out all the Nim JS code inside a scope, 
so that `import` and `export` statements are invalid (must be in global/outer scope of file).

Compile `my-game.nim` to nodejs compatible JavaScript using: 

`$ nim js -d:nodejs -r my-game.nim`

```js
// ... loads of Nim generated code

import { "x" } from "./x";
rawEcho(makeNimstrLit("Hello World"));
```

Replace `import { "x" } from "./x";` with `import { x } from "./x";` 

We could run a small script to replace, using a RegExp like this: `import\s+{\s+("\w+")+\s+}`

The included file must be an `mjs` file as well, such as `x.mjs`

Then you must either run it using the `--experimental-modules` option

`¢ node --experimental-modules my-game.mjs`

Alternatively compile it to old-school compatible JavaScript using Babel (or another JS transpiler)

### Alternatives

Post processing the file output using a script with one or more RegExp like this: `import\s+{\s+("\w+")+\s+}`

**Comment by kristianmandrup** [comment]
From what I can see in the Nim compiler:

```nim
proc getOptionalStr(c: PContext, n: PNode, defaultStr: string): string =
  if n.kind in nkPragmaCallKinds: result = expectStrLit(c, n)
  else: result = defaultStr
```

In `pragmas.nim` I see:

```nim
of wExportc, wExportCpp:
  makeExternExport(c, sym, getOptionalStr(c, it, "$1"), it.info)

of wImportCpp:
  processImportCpp(c, sym, getOptionalStr(c, it, "$1"), it.info)

of wImportJs:
  if c.config.cmd != cmdCompileToJS:
    localError(c.config, it.info, "`importjs` pragma requires the JavaScript target")
  let name = getOptionalStr(c, it, "$1")

of wImportObjC:
  processImportObjC(c, sym, getOptionalStr(c, it, "$1"), it.info)
```

Which looks similar to what I'm after (ideally both proper ES module `import` and `export`).

The key issue looks to be in setting the `name` or the `setExternName(c, sym, name, it.info)` perhaps due to `getOptionalStr`?

```nim
      of wImportJs:
        if c.config.cmd != cmdCompileToJS:
          localError(c.config, it.info, "`importjs` pragma requires the JavaScript target")
        let name = getOptionalStr(c, it, "$1")
        // ...
        if sym.kind in skProcKinds and {'(', '#', '@'} notin name:
          localError(c.config, n.info, "`importjs` for routines requires a pattern")
        setExternName(c, sym, name, it.info)
```

Perhaps it is the `setExternName`? what does `rope` do?

```nim
proc setExternName(c: PContext; s: PSym, extname: string, info: TLineInfo) =
  # special cases to improve performance:
  if extname == "$1":
    s.loc.r = rope(s.name.s)
  elif '$' notin extname:
    s.loc.r = rope(extname)
  else:
    try:
      s.loc.r = rope(extname % s.name.s)
    except ValueError:
      localError(c.config, info, "invalid extern name: '" & extname & "'. (Forgot to escape '$'?)")
  when hasFFI:
    s.cname = $s.loc.r
  if c.config.cmd == cmdPretty and '$' notin extname:
    # note that '{.importc.}' is transformed into '{.importc: "$1".}'
    s.loc.flags.incl(lfFullExternalName)
```

**Comment by timotheecour** [comment]
* the formatting in top-post is wrong (eg `### Alternatives` appears inside nim code block, etc); would make it easier to follow 
* related discussion: [could javascript backend make use of new javascript ES6 module support? - Nim forum : could javascript backend make use of new javascript ES6 module support? - Nim forum](https://forum.nim-lang.org/t/3755#23369)
* I don't understand this issue. This works:

```nim
proc esImportImpl(name: string, nameOrPath: string): string =
  result = "import { " & name & " } from "
  result.addQuoted nameOrPath

template esImport*(name: string, nameOrPath: string) =
  {.emit: esImportImpl(name, nameOrPath).}

esImport("foo", "bar")
```

producing:
```
...
import { foo } from "bar"
```

**Comment by kristianmandrup** [comment]
Oh wow! Still learning Nim (first week). Didn't know these approaches. 
So cool :) Live and learn...

**Comment by timotheecour** [comment]
if you're interested in improving js interop, IMO one big issue to fix is https://github.com/nim-lang/Nim/issues/4714 :)
