### ISSUE TITLE
I can use times.epochTime() in func.

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#13306]
I write a func that call times.epochTime() and Nim compiles it without error or warning.

### Example
```nim
import times

func testEpo(x: float): float = epochTime() + x

echo testEpo(1.0)
```

### Current Output
```
1580491911.732826
```

### Expected Output
```
Error: 'testEpo' can have side effects
```

According to Araq in IRC, "noSideEffect = proc result only depends on its parameters = proc doesn't use global state".

Using `times.cpuTime` in func show compile error.

```nim
import times

func testCPU(x: float): float = cpuTime() + x

echo testCPU(1.0)
```

Output:
```
test.nim(3, 6) Error: 'testCPU' can have side effects
```

```
>nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-01-31
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: adc52b003960817553aa3481e21a9b335a504e7f
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
you can try to submit a fix by annotating the root cause of the effect (the importc proc), then it should bubble up to callers

**Comment by demotomohiro** [comment]
times.epochTime() on windows calls `getSystemTimeAsFileTime`.
Adding `sideEffect` pragma to `getSystemTimeAsFileTime` fix this issue.

But I have some questions.
times.epochTime() has `tags: [TimeEffect]` pragma but Nim doesn't count it as the effect?
Because Nim compiler doesn't know whether `importc` procs have sideEffect, Nim should assume `importc` procs have a sideEffect unless it has `noSideEffect` pragma, isn't it?
(But it can be breaking change.)

**Comment by Araq** [comment]
> Because Nim compiler doesn't know whether importc procs have sideEffect, Nim should assume importc procs have a sideEffect unless it has noSideEffect pragma, isn't it?

No, the default should be "assume .noSideEffect" for C functions, most of them are in libraries and need to be re-entrant so assuming that works better out, all things considered. IMO.

**Comment by demotomohiro** [comment]
If people forgot to add `sideEffect` pragma to an importc proc that actually have a side effect and wrote a func that call it, compiler would show no errors. In this case, people might use that func for long time without realizing that the func actually has a side effect.
If the default of `importc` were assumed `sideEffect` and forgot to add `noSideEffect` pragma to importc proc, compiler show error when the importc proc is used in a func. So I can check all procs called from the func and add a `noSideEffect` pragma to the `importc` proc.

**Comment by Araq** [comment]
Good point but who is gonna update millions of lines of wrapper code?
