### ISSUE TITLE
koch fails if nim executable is located on a path containing spaces

### ISSUE THREAD

**Issue by fredrikhr** [nim-lang/Nim#13311]
If the nim executable is located on a path that contains spaces `koch` will fail to run.

### Current Output
```
koch boot
iteration: 1
C:\Program Files\Nim\nim-1.0.4\bin\nim.exe c  --skipUserCfg --skipParentCfg  --nimcache:nimcache/d_windows_amd64 --compileOnly compiler\nim.nim
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
FAILURE
```

In the example above, `nim.exe` is in the `PATH` environment variable and located at `C:\Program Files (x86)\nim-1.0.4\bin\nim.exe`

**Comment by timotheecour** [comment]
@couven92 you can open a PR that inserts `quoteShell` in the right place
