### ISSUE TITLE
OS elevation required to run a Nim executable with the word "update" in its name

### ISSUE THREAD

**Issue by ducdetronquito** [nim-lang/Nim#13327]
With Nim 32bits, an OS error is raised when running a Nim executable with the word "update" in its name.
The error is not raised when compiled and ran with Nim 64bits.

### Example
This file name is **test_update.nim**
```nim
import unittest

suite "Suite":
    test "test":
        check(1 == 1)

```

### Current Output
The compilation works fine, but the execution requires some higher priviledge.
```
Hint:  [Link]
Hint: operation successful (48480 lines compiled; 3.696 sec total; 48.176MiB peakmem; Debug Build) [SuccessX]
Hint: C:\Users\someone\some_dir\test_update.exe  [Exec]
oserr.nim(94)            raiseOSError
Error: unhandled exception: L’opération demandée nécessite une élévation.
 [OSError]
```

### Expected Output
```
[Suite] Suite
  [OK] test
```

### Additional Information

* OS: Windows 10 / 64 bits
* Nim installed via **choosenim** (which seems to [only install 32bits version of Nim](https://github.com/dom96/choosenim/issues/128))
* Seems related to a (missing?) window application manifest required for 32bits application (Cf: https://superuser.com/a/103012)

```
λ nim -v
Nim Compiler Version 1.0.4 [Windows: i386]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by Araq** [comment]
Ok. Well. *Shrug*.
