### ISSUE TITLE
gc:arc mode does not terminate conversions to cstring

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#13322]
Strings seem to be non-terminated (that may be all that goes wrong).

### Example
```nim
import posix  # Stat, lstat

type StrGen* = iterator(): string

proc fileStrings*(): StrGen =
  result = iterator(): string =
    for entry in lines(stdin): yield entry

iterator checkThem*(paths: StrGen): string =
  var st: Stat
  for path in paths():
    if lstat(path, st) != 0: stderr.write(path, " fails\n")

for e in checkThem(fileStrings()): discard
```

### Current Output
```
$ nim c --gc:arc stringArcItrBug.nim
$ find . -print | ./stringArcItrBug
many failures
```

### Expected Output
```
No failures at all.
```

### Additional Information

* It works fine without `gc:arc`
* https://github.com/nim-lang/Nim/issues/13289 seems maybe vaguely related but is about leaking memory while this is about corruption.
* This issue came up testing `examples/newest.nim` in `cligen`, but surely would impact many projects.
```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-03
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 1ab37ccfc604ed108886a0eed63707c3be17b67d
active boot switches: -d:release -d:useLinenoise -d:nativeStackTrace
```

**Comment by c-blake** [comment]
For what it's worth, I did try to reduce this to a more minimal/OS-independent bug manifestation, but did not have any luck getting it to fail that way.  E.g., this *succeeds* (and so does not reproduce the problem) in `gc:arc/newruntime` mode:
```Nim
var actualPaths: seq[string]
type StrGen* = iterator(): string
proc fileStrings*(): StrGen =
  result = iterator(): string =
    for entry in lines("myFile"): yield entry
iterator checkThem*(paths: StrGen): string =
  var i = 0
  for path in paths():
    if path != actualPaths[i]: echo (path, " fails\n")
    i.inc
for line in lines("myFile"):
  actualPaths.add line
for e in checkThem(fileStrings()): discard
```
Maybe someone else can find a more easily reproduced bug/something that could become a new `tests/` entry.  I have at least 3 programs not working in `gc:arc` mode from this.

**Comment by jyapayne** [comment]
Actually, this looks like an issue with passing a Nim string to a C function. The following works (by adding a null termination to the string):

```nim
import posix  # Stat, lstat

type StrGen* = iterator(): string

proc fileStrings*(): StrGen =
  result = iterator(): string =
    for entry in lines(stdin): yield entry

iterator checkThem*(paths: StrGen): string =
  var st: Stat
  for path in paths():
    if lstat(path & '\0', st) != 0: # Null terminate the string
      stderr.write(path, " fails\n")

for e in checkThem(fileStrings()): discard
```

**Comment by c-blake** [comment]
Aha.  Good catch, @jyapayne.  It also fails with `lstat(path.cstring, st)`, also only in `gc:arc` mode.  So maybe "`gc:arc` & compatible strings not getting along" is a better issue title? I also think your observation points the way forward to maybe a simple resolution.

**Comment by jyapayne** [comment]
Yeah the title change makes sense since it highlights the real issue. Hope it's a simple fix!

**Comment by narimiran** [comment]
@c-blake I've tried to run the original example with the commands you provided, and on the latest devel I get no errors. Can you confirm?

**Comment by c-blake** [comment]
I can confirm this works for me now.  (Just in the past few days a new ``gc:arc`` issue arose for me that had a not so hard workaround.  I will try to search for similar/get a minimal reproducer on that new one later today, but you can close this one, as far as I know.)  Thanks!

**Comment by Clyybber** [comment]
Hmm, we should add a test I think.

**Comment by Araq** [comment]
When I fixed this bug I did add a test.
