### ISSUE TITLE
Block-local types with the same name can silently give wrong runtime results

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13340]
Block-local types with the same name can silently give wrong runtime results.

this is directly caused by https://github.com/nim-lang/Nim/issues/5170 but hesistant to call it a duplicate because in following case the result is worse:
* no warning, no error
* wrong results at runtime; and this could be detected only in production (eg in following case, you'd never know there was a bug until you tried a value > int8.max)

### Example
```nim
  type Foo = object
    bar: int8
  var f1: Foo
  block:
    type Foo = object
      bar: int
    var f2 = Foo(bar: 300)
    echo f2.bar # prints 44 instead of 300
```

### Current Output
```
44
```

### Expected Output
```
300
```

### Additional Information

* latest devel 574f61315d015033dbf20e4840a645057b0c2060
* directly caused by https://github.com/nim-lang/Nim/issues/5170

**Comment by juancarlospaco** [comment]
Should type declarations be allowed inside blocks ?, Whats does it solves?.

**Comment by timotheecour** [comment]
that feature is used heavily, removing it would be a pointless breaking change; it's a sensible feature IMO, for scoping (eg very useful in tests, but not just that)

**Comment by narimiran** [comment]
@timotheecour why the hell your code examples (in multiple issues that I've opened) have indentation??

Maybe it is indented in your files so it is easier and faster *for you* to just copy-paste them as they are, but it is harder and slower *for everybody else* to reproduce it.
Please, slow yourself down, read and double-check both your issues and PRs before submitting them, remove all unneeded stuff, fix quirks, and only then post them.

Thank you in advance.

**Comment by narimiran** [comment]
> this is directly caused by #5170 but hesistant to call it a duplicate because in following case the result is worse

To me it looks like a duplicate. In all cases the wrong `Foo` is picked up, and now we're making different examples of the same behaviour: one is `Foo` with different field (`baz` vs `bar`), other is with different int type (`int8` vs `int`) and the last one is with different types (`array` vs `int`).
