### ISSUE TITLE
Some remarks to stdlib documentation

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#13352]
Miran, I think for https://nim-lang.github.io/Nim/io.html#lines.i%2CFile there should be a note on the top that io is part of system so that we do not have to import module io. (I just tried to import it :-( )

And for https://nim-lang.github.io/Nim/algorithm.html are you sure that at top 

```nim
proc myCmp(x, y: People): int =
  if x.name < y.name: -1 else: 1
```

is really fully correct? Should it not return zero for equality?

**Comment by kaushalmodi** [comment]
> are you sure that at top ..

The fix is to use `runnableExamples` or code blocks with `:test:` annotation (ref: https://github.com/nim-lang/Nim/commit/c4ff4e553e7cb9aca375fd07ffe21b23755fcd7a).
