### ISSUE TITLE
asynchttpserver form data/body broken with #13147

### ISSUE THREAD

**Issue by zedeus** [nim-lang/Nim#13361]
#13147 claims it does not break anything (and states it's an option), but it broke Jester's form data handling. Since there is a transition from body to bodyStream, this might have been intended.

```nim
import jester
routes:
  post "/":
    resp $request.params
```
`nim c -d:useStdLib test.nim`
`curl -d 'q=foo' http://localhost:5000`

With devel: `{:}`
Before the change: `{"q": "foo"}`

The [Jester code](https://github.com/dom96/jester/blob/master/jester/request.nim#L101) responsible for getting the form data is not easily modifiable to support this change as it's non-async and relies on the old `body` field which is now useless.

**Comment by ghost** [comment]
But https://github.com/nim-lang/Nim/pull/13146 wasn't merged (it's closed)?
Maybe you mean https://github.com/nim-lang/Nim/pull/13339/files#diff-3133183ae7c444b928e3e590f4b1d217R222 ?

**Comment by zedeus** [comment]
Sorry, relied on Github's inline preview menu and didn't notice the duplicate.

**Comment by mrhdias** [comment]
> #13147 claims it does not break anything (and states it's an option), but it broke Jester's form data handling. Since there is a transition from body to bodyStream, this might have been intended.
> 
> ```nim
> import jester
> routes:
>   post "/":
>     resp $request.params
> ```
> 
> `nim c -d:useStdLib test.nim`
> `curl -d 'q=foo' http://localhost:5000`
> 
> With devel: `{:}`
> Before the change: `{"q": "foo"}`
> 
> The [Jester code](https://github.com/dom96/jester/blob/master/jester/request.nim#L101) responsible for getting the form data is not easily modifiable to support this change as it's non-async and relies on the old `body` field which is now useless.

Possible solution:
request.body = await req.bodyStream.readAll();

**Comment by mrhdias** [comment]
> #13147 claims it does not break anything (and states it's an option), but it broke Jester's form data handling. Since there is a transition from body to bodyStream, this might have been intended.
> 
> ```nim
> import jester
> routes:
>   post "/":
>     resp $request.params
> ```
> 
> `nim c -d:useStdLib test.nim`
> `curl -d 'q=foo' http://localhost:5000`
> 
> With devel: `{:}`
> Before the change: `{"q": "foo"}`
> 
> The [Jester code](https://github.com/dom96/jester/blob/master/jester/request.nim#L101) responsible for getting the form data is not easily modifiable to support this change as it's non-async and relies on the old `body` field which is now useless.

Sorry, but, my first proposal didn't break anything, you can see the code here: . https://github.com/nim-lang/Nim/pull/13147/commits/4fdbf8f7f71bdadf9e938869b7d8b83e1767d415

But Dominik Picheta asked me if I could implement it with Future Streams. Yes, with Future Streams it break the things. But, now you can upload large files without exhaust all resources ;-)

**Comment by andreaferretti** [comment]
Rosencrantz was also broken recently, I am going to check if this is the reason

**Comment by mrhdias** [comment]
> #13147 claims it does not break anything (and states it's an option), but it broke Jester's form data handling. Since there is a transition from body to bodyStream, this might have been intended.
> 
> ```nim
> import jester
> routes:
>   post "/":
>     resp $request.params
> ```
> 
> `nim c -d:useStdLib test.nim`
> `curl -d 'q=foo' http://localhost:5000`
> 
> With devel: `{:}`
> Before the change: `{"q": "foo"}`
> 
> The [Jester code](https://github.com/dom96/jester/blob/master/jester/request.nim#L101) responsible for getting the form data is not easily modifiable to support this change as it's non-async and relies on the old `body` field which is now useless.

**Comment by andreaferretti** [comment]
I confirm that #13147 also broke Rosencrantz. It passes all tests on bfe96e069, but crashes starting from 955465e5, which is the merge commit.

I will have a look and see if I can fix them, but wasn't there a promise not break things randomly after 1.0?

**Comment by Araq** [comment]
> I will have a look and see if I can fix them, but wasn't there a promise not break things randomly after 1.0?

Actually the promise is two-fold:

1. Your code **will** continue to work with ``nim --useVersion:1.0``.
2. Your code has a >95% chance of continuing to work without the --useVersion emulation switch.

And yeah, it means we need to revert the PR that introduced the problem.

**Comment by andreaferretti** [comment]
> Your code will continue to work with nim --useVersion:1.0.

Cool! I had missed that, and in fact Rosencrantz still works with that flag :-)

**Comment by mrhdias** [comment]
> > I will have a look and see if I can fix them, but wasn't there a promise not break things randomly after 1.0?
> 
> Actually the promise is two-fold:
> 
>     1. Your code **will** continue to work with `nim --useVersion:1.0`.
> 
>     2. Your code has a >95% chance of continuing to work without the --useVersion emulation switch.
> 
> 
> And yeah, it means we need to revert the PR that introduced the problem.

Please, check the fix for this issue: https://github.com/nim-lang/Nim/pull/13394

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/pull/13147 was reverted by https://github.com/nim-lang/Nim/commit/ec8a17cc861c8282ae33ae36030d1702e41b275a
