### ISSUE TITLE
Valgrind errors in string operations

### ISSUE THREAD

**Issue by dvolk** [nim-lang/Nim#13360]
When running the following code without --gc:arc, valgrind show many errors

### Example
```nim
import os

proc parse_fasta_file*(filepath: string): (string, string) =
  var
    is_first = true
    sequence = ""
    header = ""
  for line in lines(filepath):
    if is_first:
      is_first = false
      header = line
    else:
      sequence.add(line)
  return (filepath, sequence)


proc main(filepath: string) =
  var (n, s) = parse_fasta_file(filepath)
  echo n & " " & $(s.len)

when isMainModule:
  main(paramStr(1))
```

### Current Output
```
ERROR SUMMARY: 1668 errors from 98 contexts (suppressed: 0 from 0)
```
mix of Conditional jump or move depends on uninitialised value(s) and Use of uninitialised value of size 8 

### Additional Information

* Issue doesn't seem to occur on small files
* Does not occur with --gc:arc
* Test file may be downloaded from eg. https://www.ncbi.nlm.nih.gov/nuccore/NC_000962.3 (send to -> File -> FASTA)

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
```

**Comment by timotheecour** [comment]
* can you show the valgrind command used?
* can you show (maybe in a https://gist.github.com/ link) the vlagrind errors
* ideally, can you minimize a bit your example, and maybe even make the test self-contained instead of relying on an external file to download? 
any of these would help whoever's gonna look into it

**Comment by dvolk** [comment]
I'm just running valgrind ./cmd

(part of) the valgrind output:

https://gist.github.com/dvolk/e9bae58e2b5cff25a38b062f0a8d24ca

Here's an minimal example:

```
import strutils

var
  sequence = ""

for i in 0..100_000:
  for j in 0..100:
    sequence.add('a')

for line in sequence.splitLines():
  discard
```

**Comment by ghost** [comment]
@dvolk with the current default GC the memory might not be freed when the program ends probably because the GC didn't really kick in , try with `--gc:arc -d:useMalloc` on devel

**Comment by Araq** [comment]
There is a tools/nimgrind.supp suppression file that sometimes works with valgrind, use ``koch valgrind``.
