### ISSUE TITLE
stdlib needs ryu for compact and performant float to string

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13365]
as of https://github.com/nim-lang/Nim/pull/13364 json works with roundtrip correctness in mind, but sacrifices shortness of representation.
python's json doesnt' have this issue.

### Example
```nim
import std/json
echo(%* 0.6) # 0.59999999999999998
```

### Current Output
```
0.59999999999999998
```

### Expected Output
```
0.6
```

### Possible Solution

port/wrap/implement ryu https://github.com/ulfjack/ryu which has several benefits:
* speed
* compactness

> Ryu generates the shortest decimal representation of a floating point number that maintains round-trip safety. That is, a correct parser can recover the exact original number. For example, consider the binary 32-bit floating point number 00111110100110011001100110011010. The stored value is exactly 0.300000011920928955078125. However, this floating point number is also the closest number to the decimal number 0.3, so that is what Ryu outputs.

## example: python's print wrt float:
as a nice-to-have, we can also have `echo` behave same as in python:
```py
  a = 0.1
  import numpy
  for i in range(0,10):
    print(a)
    a = numpy.nextafter(a, float('Inf'))
```
```
0.1
0.10000000000000002
0.10000000000000003
0.10000000000000005
0.10000000000000006
0.10000000000000007
0.10000000000000009
0.1000000000000001
0.10000000000000012
0.10000000000000013
```

this isn't the case currently in nim
```nim
  var a = 1.0
  for i in 0..<10:
    echo a
    a = nextafter(a, Inf)
```

```
1.0
1.0
1.0
1.000000000000001
1.000000000000001
1.000000000000001
1.000000000000001
1.000000000000002
1.000000000000002
1.000000000000002
```

## links
* https://forum.nim-lang.org/t/5983 Nim's float issue?
* [https://github.com/ulfjack/ryu : Share a paper: How to Print Floating-Point Numbers Accurately - Nim forum](https://forum.nim-lang.org/t/6004)
* [ulfjack/ryu: Converts floating point numbers to decimal strings : ulfjack/ryu: Converts floating point numbers to decimal strings](https://github.com/ulfjack/ryu)
* [disruptek/ryu: ryu for nim : disruptek/ryu: ryu for nim](https://github.com/disruptek/ryu) (archived)
* [Clyybber/nimryu: nim port of ryu : Clyybber/nimryu: nim port of ryu](https://github.com/clyybber/nimryu)
* [LemonBoy/dtoa.nim: Port of Milo Yip's fast dtoa() implementation : LemonBoy/dtoa.nim: Port of Milo Yip's fast dtoa() implementation](https://github.com/LemonBoy/dtoa.nim)
* [Is there a reliable way to round? - Nim forum](https://forum.nim-lang.org/t/7850)
* [Fast and accurate float to string conversion (ryu) · Issue #104 · nim-lang/needed-libraries](https://github.com/nim-lang/needed-libraries/issues/104)
* [⚙ D70631 Microsoft's floating-point to_chars powered by Ryu and Ryu Printf](https://reviews.llvm.org/D70631)
* [alaviss/nim-ryu: An implementation of the ryū float-to-string conversion algorithm. This version is written from scratch based on the paper.](https://github.com/alaviss/nim-ryu)
* [mir-algorithm/generic_128.d at master · libmir/mir-algorithm](https://github.com/libmir/mir-algorithm/blob/master/source/mir/bignum/internal/ryu/generic_128.d)
* [D Ryu implementation reference by 9il · Pull Request #194 · ulfjack/ryu](https://github.com/ulfjack/ryu/pull/194)

## alternative: the newer dragonbox
* [jk-jeon/dragonbox: Reference implementation of Dragonbox in C++](https://github.com/jk-jeon/dragonbox)

**Comment by disruptek** [comment]
I said I'd do it and I will. :laugh: Do you need it soon?

**Comment by disruptek** [comment]
Decided to do a syntax port and then once the tests pass and we can benchmark it, we can twiddle the bits and make it our own.

https://github.com/disruptek/ryu

**Comment by timotheecour** [comment]
we now have dragonbox, closing
