### ISSUE TITLE
niminst source code duplicated (with divergences): nim-lang/niminst vs Nim/tools/niminst/niminst.nim

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13406]
niminst source code is duplicated between https://github.com/nim-lang/niminst and inside Nim repo: Nim/tools/niminst/niminst.nim
along with lots of other duplicated files.

It's **pretty bad** because both versions are getting updated independently and they've diverged:
```
  1│ 2b368bc 2020-02-12 01:35 timothee.cour2  o fix linenoise regression (#13395)
   │ c6a451c 2019-11-06 04:59 narimiran       o remove unused imports from tests
   │ 944fcc0 2019-09-26 06:45 glaubitz        o Add build support for Linux/hppa (#12271)
   │ e1539c7 2019-08-23 04:54 hamiltcl        o Add build support for FreeBSD PowerPC64
   │ 806f3b5 2019-08-23 04:50 hamiltcl        o Add build support for FreeBSD PowerPC64
```

```
  1│ b30ea96 2019-12-02 01:28 rumpf_a         M─┐ [master] {origin/master} {origin/HEAD} Merge pull request #4 from yewpad/patch-broken-code
   │ 5c893b2 2019-12-02 01:03 yewyewpad       │ o Upgrade to current standard, fixes a lot of broken code
   │ f81e194 2015-11-04 15:36 rumpf_a         M─┤ Merge branch 'master' of https://github.com/nim-lang/niminst
```

### Possible Solution

* there should be a single source for niminst, and the other copy should be removed
* if that source is in https://github.com/nim-lang/niminst, the correct way is to copy during install/CI like is done for other nimble packages eg:
```
git clone -q https://github.com/nim-lang/nimble.git dist/nimble
```

**Comment by Araq** [comment]
https://github.com/nim-lang/niminst is a fork of niminst for Nim users to produce installers, our niminst is for the Nim compiler only. Probably still a terrible idea but that was the reasoning behind it.

**Comment by timotheecour** [comment]
this type of fork tends to get worse and worse over time, as bugs/features are fixed/introduced on one fork but not the other ... merging these back to just 1 niminst (with perhaps use-case specific flags) would probably cause less pain over time

**Comment by ringabout** [comment]
close in favour of https://github.com/nim-lang/Nim/issues/15946

**Comment by timotheecour** [comment]
> close in favour of #13406

@xflywind wrong link?
