### ISSUE TITLE
`as` is usable as infix operator but its existence and precedence are not documented

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#13409]
https://nim-lang.org/docs/manual.html#precedence https://nim-lang.org/docs/manual.html#lexical-analysis-operators

### Example
```nim
template `as`[T, U](x: T, _: typedesc[U]): U = U(x)

echo(65 as char)
```

### Current Output
```
A
```

### Possible Solution

* List it as an operator in the manual and add it to the operators with precedence 5

```
$ nim -v
Nim Compiler Version 1.0.6
```

**Comment by Araq** [comment]
Wow what an oversight. :-)

**Comment by Clyybber** [comment]
hehe, "showstopper" : P
