### ISSUE TITLE
tested packages continuously break and hinder Nim development

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#13419]
Just a recent example, my current PR here: 

https://github.com/nim-lang/Nim/pull/13401

Fails with the following error message:

```
C:\Users\VssAdministrator\.nimble\pkgs\unicodedb-0.8.0\unicodedb\casing.nim(34, 5) Error: 'lowercaseblockSize' should be: 'lowercaseBlockSize'
```

This error message is unrelated to my changes, and yet it blocks my contributions.

### Possible Solution

Attach a git hash to every tested package. This will prevent developers of theses "important" packages to break their master branch without affecting Nim development. Hashes should be easy to update though.

Another idea would be to have these important packages tested on releases only.

**Comment by Araq** [comment]
You can always say "unrelated CI failure, merging" and that's what we do. I don't like to pin down specific commit hashes as the idea is to ensure an ecosystem where stuff "just works". We can always remove specific packages that tend to break more frequently than others.
