### ISSUE TITLE
Iterator with openArray parameter make the argument evaluated many times

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#13417]
When using openArray type in iterator, if the argument is function call, it will be evaluated many times.

### Example
```nim
proc p1(): seq[int] =
   echo "next"
   @[1,2]

iterator ip1(v: openArray[int]): auto =
   for x in v:
      yield x

for x in ip1(p1()):
   echo x
```

### Current Output
```
next
next
1   
next
next
2   
next
```

### Expected Output
```
next
1
2
```

```
$ nim -v
Nim Compiler Version 1.1.1 [Windows: i386]
Compiled at 2020-01-27
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by metagn** [comment]
The issue #2563 covers this

**Comment by krux02** [comment]
one could argue that this is a duplicate. But personally I don't like to close this issue, because it provides a nice example and follows the issue template correctly unlike the issue mentioned above.

**Comment by krux02** [comment]
There is a workaround for this bug:

```nim
proc p1(): seq[int] =
   echo "next"
   @[1,2]

iterator ip1(v: openArray[int]): auto =
   for x in v:
      yield x

for x in ip1((discard;p1())):
   echo x
```

Yea, don't ask me why this works.

**Comment by timotheecour** [comment]
proper fix is making openArray first class, see https://github.com/nim-lang/RFCs/issues/88
