### ISSUE TITLE
`echo 'echo 1' | nim c -r -`  silently gives wrong results (nimBetterRun not updated for stdin)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13412]
Function `echo` outputs the wrong string.

### Example
```nim
echo 'echo 0' | nim c -r -f - # just to force re-initializing, but not part of this bug
echo 'echo 1' | nim c -r -
echo 'echo 2' | nim c -r -
```

### Current Output
```
0
1
1
```

### Expected Output
```
0
1
2
```

### Possible Solution

* the logic for -r (nimBetterRun) doesn't handle stdin input

### Additional Information

* recent devel 1.1.1 1e303100f8ca32e60b154bf997a9102f36eb23d0

**Comment by Araq** [comment]
IMO we should simply not support reading from stdin via pipes, Nim is a compiler, it's not for throwaway code. Besides, there is already ``nim secret`` for that.

**Comment by timotheecour** [comment]
I fixed it in some recent PR
