### ISSUE TITLE
template return type ignored in type check, accepts invalid code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13426]
template return type is ignored in type check when template called inside a generic, and it accepts invalid code.

### Example 1
```nim
  template bar(t): string = high(t)
  proc fun[A](key: A) =
    var h = 1 and bar(@[1])
  fun(0)
  # if calling `var h = 1 and bar(@[1])` directly (not inside a generic), we get a correct error msg
```

### Current Output 1
compiles

### Expected Output 1
`Error: type mismatch: got <int> but expected 'string'`

### Example 2
```nim
template bar(t): string = high(t)
proc fun[A](key: A) =
  var h = 1'u and bar(@[1])
fun(0)
```

### Current Output 2
```
Error: type mismatch: got <uint, int>
but expected one of:
proc `and`(x, y: uint): uint
  first type mismatch at position: 2
  required type for y: uint
  but expression 'high(@[1])' is of type: int
proc `and`(x, y: uint64): uint64
  first type mismatch at position: 2
  required type for y: uint64
  but expression 'high(@[1])' is of type: int
10 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: 1'u and high(@[1])
    var h = 1'u and bar(@[1])
```

### Expected Output 2
`Error: type mismatch: got <int> but expected 'string'`

### Additional Information
* recent devel 1.1.1 1e303100f8ca32e60b154bf997a9102f36eb23d0
* related but different from https://github.com/nim-lang/Nim/issues/11794

**Comment by metagn** [comment]
Correct output since 1.6.18 (not 1.6.16)
