### ISSUE TITLE
SIGSEGV from an if statement implicit return in function returning a proc type

### ISSUE THREAD

**Issue by hugh-fox** [nim-lang/Nim#13437]
Function `ruleMatch` segfaults.

### Example
```nim
proc ruleMatch(): proc(): string =
  if false: return proc(): string = "abc"

echo ruleMatch()()
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'program '
```

### Expected Output
```
Empty String or default string
```

### Possible Solution

None

### Additional Information

I could only get this using a combination of implicit returns (prepending with ```result =``` fixes it), ```proc(): string``` as return type, and an if statement with no else branch.

```
$ nim -v
Nim Compiler Version 1.0.6 [Linux: amd64]
```

**Comment by Araq** [comment]
No bug here, you return a ``nil`` callback that crashes when called.

**Comment by hugh-fox** [comment]
Ah ok, forgot they are function pointers and can be nil.
