### ISSUE TITLE
Nested tuple unpacking

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#13439]
#12412 # Summary
The following fails:

const foo = ("Pi", (3.141, 5))
let (name, (fv, i)) = foo
echo("Name=", name, " fv = ", fv, "i = ", i)

### Description
Obvious

### Alternatives
One alternative is to use single level tuples and unwrap each nesting separately. 

const foo = ("Pi", (3.141, 5))
let (name, fvi) = foo
let (fv, i) = fvi
echo("Name=", name, " fv = ", fv, "i = ", i)

Having nested tuples work without this limitation seems more Nim-ish to me. If it makes it easier, I'd be fine with mandatory parens on tuples.

### Additional Information
https://github.com/nim-lang/Nim/pull/10152
https://github.com/nim-lang/Nim/issues/2436

**Comment by Araq** [comment]
New features should start as RFCs, see https://github.com/nim-lang/RFCs

**Comment by bpr** [comment]
I wasn't sure if this was considered a new feature, or a defect in the implementation of the existing feature. Shame on me for not reading the RFC list! Thanks for the link @hlaaftana.
