### ISSUE TITLE
passing by let is unsafe/buggy

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13431]
passing by let is buggy.

probably root cause of https://github.com/nim-lang/Nim/issues/13430

### Example
```nim
  type Foo = object
    s: seq[int]
  var foo: Foo
  let n = 5
  for i in 1 .. n:
    foo.s.add i

  proc inner() =
    for i in n+1 .. n+n:
      foo.s.add i

  proc outer*(foo2: Foo) =
    echo foo2
    inner()
    echo foo2

  outer(foo)
```

### Current Output
with --gc:arc:
```
(s: @[1, 2, 3, 4, 5])
(s: @[29480, 4, 540701480, 4, 5])
```
without --gc:arc:
```
(s: @[1, 2, 3, 4, 5])
(s: @[])
```

### Expected Output
 [EDIT]
```
(s: @[1, 2, 3, 4, 5])
(s: @[1, 2, 3, 4, 5])
```

### Additional Information
* recent devel d1f9f11245a29f00bfa8cd86f9b4eb4ab0963a15 1.1.1

not sure how this should be handled; if `let` does a copy always, this could have a major negative performance impact.

## proposal: adapt D's slices to nim

Maybe it's high time to look at whether we can adopt D's slices in Nim, this could have a dramatic performance positive impact.

Here's analog D code, as you can see, it's both safe and efficient (not copy on write, but smarter).
How it works is explained in details here: https://dlang.org/articles/d-array-article.html ; it's one of D's best features.

```d
import std.stdio;

struct Foo{
  int[] s;
}

void main(string[]args){
  Foo foo;
  int n = 5;
  for(int i=1; i <= n; i++) foo.s ~= i;

  void innerSmall(){
    for(int i=0; i < 2; i++) foo.s ~= i;
  }

  void inner(){
    for(int i=n+1; i <= n+n; i++) foo.s ~= i;
  }
  void outer(Foo foo2){
    assert(&foo2.s[0] == &foo.s[0]);
    assert(foo2.s == [1, 2, 3, 4, 5]);

    innerSmall();
    assert(&foo2.s[0] == &foo.s[0]); // not realloc'd yet

    inner();
    assert(&foo2.s[0] != &foo.s[0]); // realloc'd

    assert(foo2.s == [1, 2, 3, 4, 5]);
  }
  outer(foo);
  assert(foo.s == [1, 2, 3, 4, 5, 0, 1, 6, 7, 8, 9, 10]);
}
```

**Comment by Araq** [comment]
It's really not "one of D's best features", it introduces aliasing everywhere that is so hard to reason about that you need reference counting or a fullblown GC in order to make it safe. The better solution is to implement Ada Spark's aliasing restrictions. See https://nim-lang.org/docs/manual_experimental.html#aliasing-restrictions-in-parameter-passing for more information.

**Comment by Araq** [comment]
As I said.
