### ISSUE TITLE
"(let v = true; (if v or (let v = false; v): doAssert v))" AssertionError

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#13438]
**Test**
```nim
let v = true
if v or (let v = false; v):
  doAssert v
```
**Expected**
`Nothing`

**Got**
```nim
Error: unhandled exception: Test.nim(3, 12) `v`  [AssertionError]
```
Specially bad when v is a gc pointer
***
```nim
>nim -v
Nim Compiler Version 1.1.1 [Linux: i386]
Compiled at 2020-02-19
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8c22518d673cf792fa064d2d561d1c6f03b823bb
active boot switches: -d:release
```

**Comment by metagn** [comment]
This doesn't mean `let v = false` is still evaluated, just `v` remains uninitialized.

```nim
let a = 1
if a == 1 or (let a = 2; a == 1):
  echo a # 0
```

**Comment by Araq** [comment]
No bug here, you shadow the old ``v`` and the new ``v`` is false, because variables are default initialized.

**Comment by Wh1teDuke** [comment]
How did it get shadowed when the old v is true? I didn't expect the second half to be evaluated at all.

To make my point clearer:
```nim
proc greet: bool =
  echo "Hi"
  return true

var i = 5
if greet() or (let i = 0; i == 0):
  echo "Bye"
  echo "i=", i
```
```
Hi
Bye
i=0
```
If greet returns true, I would expect i to be 5, not 0. Quite surprising.

**Comment by Araq** [comment]
Scoping is not dynamic. In every commonly used programming language.

**Comment by andreaferretti** [comment]
This is not about dynamic scoping. It is about the fact that the second branch of an `or` should not be evaluated if the first one evaluates to `true`. As in the following example

```nim
proc greet(): bool =
  echo "hello"
  return true

proc crash(): bool =
  doAssert(1 == 2, "CRASH")
  return false

if greet() or crash():
  echo "no crash"
```

**Comment by andreaferretti** [comment]
If I understand correctly, you are saying that the part that declares new variables is evaluated unconditionally, because variables are not dynamic

**Comment by Araq** [comment]
I'm saying that the variable **shadowing** is not dynamic. The scope of the let in the or expression **always** shadows the outer variable, that's all that happens.
