### ISSUE TITLE
Mixing GC'ed memory with ptr does not work as in the manual 

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#13447]
GC'ed memory gets corrupted after full collect.  Function `echo` outputs the wrong string.  The example is taken from the manual with a slightly modified `Data` type and calling `GC_fullCollect` in between two `echo` calls.

### Example
```nim
type Data = tuple[x: int, s: string]
var d = cast[ptr Data](alloc0(sizeof(Data)))
d.s = "abc"
echo d[]

GC_fullCollect()

echo d[]

GCunref(d.s)
dealloc(d)
```

### Current Output
```
(x: 0, s: "abc")
(x: 0, s: "(x: ")
```

### Expected Output
```
(x: 0, s: "abc")
(x: 0, s: "abc")
```

### Possible Solution

* The result seems correct if I call `GCref(d.s)` before full collect. Is it safe this way?

### Additional Information

* Not sure if it worked in previous versions.

```
$ nim -v
Nim Compiler Version 1.0.6 [FreeBSD: amd64]
Compiled at 2020-01-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 89b39ee8fe271d0e1b75c15a4c6cf82eb9c13aea
active boot switches: -d:release
```

Edit: `GCref` appears to fix the output.

**Comment by Araq** [comment]
With ORC everything changed.
