### ISSUE TITLE
A "made with Nim" website!

### ISSUE THREAD

**Issue by littledivy** [nim-lang/Nim#13441]
Hi, I would love to build a website that displays projects made with Nimlang😋.

**Comment by andreaferretti** [comment]
You may want to discuss this proposal on the [forum](https://forum.nim-lang.org/)

**Comment by timotheecour** [comment]
can we close this? see https://forum.nim-lang.org/t/5957 [A 'made with Nim' website?! - Nim forum : A 'made with Nim' website?! - Nim forum](https://forum.nim-lang.org/t/5957)
