### ISSUE TITLE
runnableExamples transforms `do: => :` and `(expr) => expr`, producing invalid code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13491]
runnableExamples code transformation produces invalid code from valid code

### Example 1
```nim
proc fun*(): int = doAssert false
proc main*()=
  runnableExamples:
    doAssertRaises(AssertionError, (discard fun())) # BUG
doAssertRaises(AssertionError, (discard fun())) # ok
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/build/nimcache/runnableExamples/t10250_examples.nim(1, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/build/nimcache/runnableExamples/t10250_examples1.nim(7, 3) Error: expression expected, but found 'keyword discard'
    discard fun())
    ^
```

### Expected Output
works

### Additional Information

* devel 3dad130034e3212159dda5d61988ca2b18959b24 1.1.1

code transform:
```nim
import
  "/Users/timothee/git_clone/nim/timn/tests/nim/all/t10250.nim"

doAssertRaises(AssertionError,
  discard fun())
```
expected transform:
```nim
...

doAssertRaises(AssertionError,
  (discard fun()))
# or:
doAssertRaises(AssertionError, (discard fun()))
```

* workaround:
`doAssertRaises(AssertionError): discard fun()`
but that's just for this particular example; the bug remains

### Example 2
see https://github.com/nim-lang/Nim/issues/13491#issuecomment-731519848

## [EDIT] potential solution
use same technique as in https://github.com/nim-lang/Nim/pull/14439

**Comment by timotheecour** [comment]
related issue:
```nim
# D20200622T145049
template foo(body) = discard
foo (discard) # works

template bar*()=
  runnableExamples:
    foo (discard) # Error: invalid indentation
```

**Comment by narimiran** [comment]
I've tried to reproduce it with Nim 1.3.5, and it seems it has already been fixed.

**Comment by timotheecour** [comment]
the 1st bug seems fixed indeed, but the 2nd bug in https://github.com/nim-lang/Nim/issues/13491#issuecomment-647787102 is still there on latest devel 341cd844b282cc6ed3b1fc4c1ef10c38fc06d5e7
producing Error: invalid indentation

the runnableExamples code generated is:
```nim
foo
  discard
```

**Comment by timotheecour** [comment]
just hit this again, this time with `do:` notation that gets stripped:
```nim
when defined case7:
  # works:
  template fn(body: untyped): untyped = true
  doAssert(fn do: nonexistant)
when defined case7b:
  # nim doc will give: Error: type expected
  runnableExamples:
    template fn(body: untyped): untyped = true
    doAssert(fn do: nonexistant)
```

`nim doc -d:case7b main` produces:
```nim
import
  "/Users/timothee/git_clone/nim/timn/tests/nim/all/t11345.nim"

template fn(body: untyped): untyped =
  true

doAssert(fn:
  nonexistant)
```
giving Error: type expected

whereas `nim r -d:case7 main` works

**Comment by timotheecour** [comment]
potential fix: use same approach as https://github.com/nim-lang/Nim/pull/14439

**Comment by metagn** [comment]
Just ran into this:

```nim
import macros

macro foo*(x, y) =
  runnableExamples:
    foo:
      a = 1
    do: discard

  result = newLetStmt(x[0][0], x[0][1])
```

```
Error: type mismatch: got <a: int literal(1), void>
but expected one of:
macro foo(x, y)
  first type mismatch at position: 1
  unknown named parameter: a

expression: foo(a = 1):
  discard
```

Related or separate issue?

**Comment by metagn** [comment]
Same question for:

```nim
import macros
template `+`*(x, y, body) =
  runnableExamples:
    1 + 2:
      echo it
  let it {.inject.} = x + y
  body
```

```
Error: expression '3' is of type 'int literal(3)' and has to be used (or discarded)
```

(Yes this syntax works in normal Nim and my library relies on it)

**Comment by timotheecour** [comment]
> Related or separate issue?

you have to look/report the generated examples: `runnableExamples/t11355_examples1.nim(8, 4) Error: type mismatch: got <a: int literal(1), void>`

as you can see it's the same issue:
```nim
when defined case1:
  import macros
  macro foo*(x, y) =
    runnableExamples:
      foo:
        a = 1
      do: discard
    result = newLetStmt(x[0][0], x[0][1])

when defined case2:
  import macros
  macro foo*(x, y) =
    result = newLetStmt(x[0][0], x[0][1])
  foo:
    a = 1
  do: discard
```
case2 works, case1 (doc) fails, generating this code:
```
foo(
  a = 1):
  discard
```

> Same question for:

generated code: `1 + 2`

same or not, the bugfix recommended here https://github.com/nim-lang/Nim/issues/13491#issuecomment-731522402 should work; or we can also fix the rendering used by runnableExamples logic, or do both
