### ISSUE TITLE
Error: Nim build failed

### ISSUE THREAD

**Issue by alessindi** [nim-lang/Nim#13494]
Nim build fails on OSX 10.13

Tried to workaround this but with no luck.
Here's the terminal:

`choosenim-init: Downloading choosenim-0.5.1_macosx_amd64
Downloading Nim 1.0.6 from nim-lang.org
      Info: /Users/Ale/.choosenim/downloads/nim-1.0.6.tar.xz already downloaded
 Extracting nim-1.0.6.tar.xz
   Building Nim 1.0.6
 Exception: Execution failed with exit code 1
        ... Command: sh build.sh
        ... Output: # OS: macosx
        ... # CPU: amd64
        ... clang -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_assertions.nim.c -o c_code/1_2/stdlib_assertions.nim.o
        ... xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
   Cleaning failed build
     Error: Build failed`

**Comment by Clyybber** [comment]
As the error message tells you, you are missing `xcrun`, whatever that is..

**Comment by alessindi** [comment]
Been days of troubleshooting. 
Installed many times XCode developer tools with no luck with automatic installer (it starts when Nim is building in the terminal).
The solution is to install XC tools from within the terminal

[https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue](url)
