### ISSUE TITLE
Wrong compile-time integer result

### ISSUE THREAD

**Issue by markus-oberhumer** [nim-lang/Nim#13517]
Wrong compile-time integer result:

### Example
```nim
type MyUint64 = distinct uint64

proc `==`(a: MyUint64, b: uint64): bool = uint64(a) == b

block:
  doAssert MyUint64.high is MyUint64
  doAssert MyUint64.high == 18446744073709551615'u64     # works

static:
  doAssert MyUint64.high is MyUint64
  doAssert MyUint64.high == 18446744073709551615'u64     # FAILS !!
```

### Current Output
```
Compilation fails:

.../nim-git/lib/system/fatal.nim(55, 5) Error: unhandled exception: /tmp/test.nim(11, 12) `MyUint64.high == 18446744073709551615'u64`  [AssertionError]
```

### Expected Output
```
Program should compile.
```

### Additional Information

* Issue #6733 might be somewhat related.

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 42dad3a836f7eed860f300e68b33d4c0b39bd1f4
active boot switches: -d:release
```

**Comment by krux02** [comment]
I label this as high priority as integers and distinct types are such a core part of the language that this just has to work.

**Comment by mratsim** [comment]
Note that in my cryptographic lib where everything is a distinct type, I have to duplicate all my procs that are used at compile-time due to this issue: https://github.com/mratsim/constantine/blob/986245b5/constantine/config/precompute.nim#L25-L29
