### ISSUE TITLE
[CI] `builds.sr.ht: freebsd.yml` does not restart when a PR is closed/re-opened

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13553]
I've observed this a number of times; when a test is flaky and the PR is closed and re-opened to re-trigger CI, azure-pipelines tests are restarted (and so were travis and circle back in the days IIRC), but not `builds.sr.ht: freebsd.yml` (at least a lot of times it doesn't), so you end up with wasted CI cycles because the test still fails 

### Example
in https://github.com/nim-lang/Nim/pull/13546 (same problem with other recent PR's I've just restarted after the feb 29 bug, eg https://github.com/nim-lang/Nim/pull/13537)
![image](https://user-images.githubusercontent.com/2194784/75634702-d09eb100-5bc4-11ea-8beb-8318472744e6.png)

### Current Output
![image](https://user-images.githubusercontent.com/2194784/75634698-c7addf80-5bc4-11ea-8a3d-29a33340e5c8.png)

also, 1st few lines of https://builds.sr.ht/~araq/job/160965#task-test show the test wasn't restarted and was from yesterday:
```
[#160965] 2020/02/29 22:25:38 Booting image freebsd/latest (default) on port 22021
[#160965] 2020/02/29 22:25:41 Waiting for guest to settle
[#160965] 2020/02/29 22:26:02 Sending tasks
```

### Expected Output
freebsd test restarts

### workaround
do a dummy edit and force-push (not great)

**Comment by Clyybber** [comment]
This is not something we can solve. You can open a ticket on sr.ht (dispatch.sr.ht handles github integration). But from their docs this is expected, as builds gets triggered on a push to a branch.

**Comment by timotheecour** [comment]
I've asked here https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/21#comment-6963 and currently the only workaround is to create an account (https://meta.sr.ht/) after which a "resubmit build" button is shown in https://builds.sr.ht/~araq/job/160965  ; it does work indeed

sadly, the feature request itself (as already supported by azure-pipelines etc) doesn't seem to be on their radar currently
> I don't know. I've never found it a priority to fix someone else's bugs. Your test suite needs work.
