### ISSUE TITLE
No nimble bin in PATH in azure windows pipeline

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#13560]
It seems there's no `.nimble/bin` dir in `PATH` env var in azure windows pipeline, which results in this issue https://github.com/yglukhov/nimx/issues/397. Apparently all other pipelines are fine?

**Comment by timotheecour** [comment]
pending https://github.com/nim-lang/Nim/pull/13348 only windows runs important_packages; IMO the title of this issue should be changed and the problem may lie elsewhere
