### ISSUE TITLE
Treat `except` keyword like `of`: Infix operator in imports

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#13571]
### Summary
This will relax the syntax of the `except` keyword to make `import` statements more flexible.

### Description
The `of` keyword in Nim has 2 purposes, an operator like `a of b` and a control flow branch. As a control flow branch, it can only be used after a `case` statement. The `except` statement also has 2 purposes: to exclude symbols from imports, and as a control flow branch, only following a `try` statement. Turning `except` into an operator makes the following syntax possible:

```nim
import std/[strutils except split, math]
```

Since this is already invalid syntax by itself, it won't break `except:` blocks if implemented like `of`:

```nim
of a:
  discard
```

### Alternatives
I have no idea. The current workaround is to just import individually, like so:

```nim
import std/[math]
import std/strutils except split
```

These don't work:

```nim
import std/[math, strutils] except split # invalid module name: [math, strutils]
import std/[math, strutils] except strutils.split # same error

import std/[math, strutils]
import std/strutils except split # ignored, split is still in scope
```

**Comment by timotheecour** [comment]
how do you to except split1,split2 from strutils?
```nim
# ugly
import std/[strutils except (split1, split2), math]
# ambiguous
import std/[strutils except split1, split2, math]
```

so I don't think that's a good idea.

another idea i had proposed a while back is this:
```nim
import std/[strutils, math] except split1, split2, round # require full qualification for split1, split2, round
import std/[strutils, math] except split1, strutils.split2, round # ditto but don't exclude math.split2 if that exists
```
