### ISSUE TITLE
--gc:arc not self-consistent, not consistent with default gc regarding catching AssertionError

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13585]
--gc:arc not self-consistent, not consistent with default gc regarding catching AssertionError

* consistency is important otherwise migrating code from non-gc:arc to gc:arc will be a pain.
* This is **especially true for any code involving testing**, where it's common to catch AssertError, eg doAssertRaises, which is important to support to check that asserts in place work as intended.
* there are other use cases beyond testing, eg for writing repl's and other tool where user input may raise non-catchable exceptions
* ditto, when writing production servers that just shouldn't crash and would be caught at some root-level to perform important cleanups instead of exiting

### Example
```nim
try:
  doAssert false # BUG
  # assert false # BUG
  # raiseAssert("foo") # BUG
  # raise newException(Exception, "foo") # works
  # raise newException(AssertionError, "foo") # works
  # raise newException(CatchableError, "foo") # works
except:
  echo "caught"
echo "after main"
```

### Current Output
```
("goto", true)
Traceback (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10302.nim(8) t10302
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(27) failedAssertImpl
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assertions.nim(20) raiseAssert
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(45) sysFatal
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(33) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10302.nim(8, 12) `false`  [AssertionError]
```

### Expected Output
* should be same as without --gc:arc and other gc's
* should be same as with `raise newException(AssertionError, "foo")` etc
all of which give:
```
caught
after main
```

### Additional Information
* devel 1.1.1 34c16f5ecae765c014335525ef518233832832db

**Comment by Araq** [comment]
This is the documented behaviour of --goto:exceptions and hence not a bug. I know it's disliked by many but that doesn't make it a bug.

**Comment by timotheecour** [comment]
> This is the documented behaviour of --goto:exceptions

do you have a link? I'm not seeing any mention of `assert` here https://nim-lang.org/araq/gotobased_exceptions.html nor any mention of `goto` under https://nim-lang.github.io/Nim/manual.html#exception-handling

EDIT: I do see `Caveats` section in https://nim-lang.org/araq/gotobased_exceptions.html saying:

> In the "goto based exceptions" mode checked runtime errors like "Index out of bounds" or integer overflows are not catchable and terminate the process. This is in compliance with the Nim spec, quoting the manual: Whether a checked runtime error results in an exception or in a fatal error is implementation specific.

https://nim-lang.github.io/Nim/manual.html#exception-handling should probably have some explicit mention of  --exceptions:goto's behavior, instead of merely saying `implementation specific` under https://nim-lang.org/docs/manual.html#definitions

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/13626
