### ISSUE TITLE
strscan can't get value of last element in format

### ISSUE THREAD

**Issue by dmknght** [nim-lang/Nim#13605]
### Example

```nim
import strscans

let teststr = "0x030000:0x10de:0x1401"

var class, vendor, device: string

if scanf(teststr, "$+:$+:$+", class, vendor, device):
  echo "Class: " & class
  echo "Vendor: " & vendor
  echo "Device: " &  device
```

### Current values of variables from strscans
The device variable contains empty string
```
class = "0x030000"
vendor =  "0x10de"
device =  ""
```

### Expected Output
```
class = "0x030000"
vendor =  "0x10de"
device =  "0x1401"
```

### Possible Solution

* The value of `device` should show `0x1401`

### Additional Information

@yardanico_temp  on telegram helped me debug this issue. Here is his comments:
```
I think it doesn't work because $+ is defined (in the docs) as : "Matches until the token following the $+ was found. The match must consist of at least one char.".

But in our case we don't have any token following $+ at the end of the string so it doesn't work.
so in this case it doesn't work because it uses parseUntil with "" (empty) character at the end for last $+.
```

An other way to "fix" the problem  is  adding a space in last position of pcidevice and add a space in format to use strscan
`pcidevice = "0x030000:0x10de:0x1401 "`
`scanf(pcidevice, "$+:$+:$+ ", class, vendor, device)`

 * Im having the code in `https://pastebin.com/jK0uWzg1`

```
$ nim -v
Nim Compiler Version 1.0.6 [Linux: amd64]
```

**Comment by krux02** [comment]
please verify your sourcecode. The bug is not reproducable with the current version of the code.

**Comment by dmknght** [comment]
> please verify your sourcecode. The bug is not reproducable with the current version of the code.

Thank you for your test and reply. Which platform did you use for reproduce? I used Linux and the guy helped me on telegram (Nim lang channel) used Linux as well.

**Comment by ghost** [comment]
@dmknght krux02 meant that the code is not complete (you can't run it as standalone)

**Comment by dmknght** [comment]
Oh i'm verry sorry  it must be my mistake when i  copied it. I rewrote the test code here
```
import strscans

let teststr = "0x030000:0x10de:0x1401"

var class, vendor, device: string

if scanf(teststr, "$+:$+:$+", class, vendor, device):
  echo "Class: " & class
  echo "Vendor: " & vendor
  echo "Device: " &  device
```
My output
```
Class: 0x030000
Vendor: 0x10de
Device: 
```
