### ISSUE TITLE
Templates can't be made discardable

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#13609]
The Nim manual contains the following snippet under [push and pop pragmas](https://nim-lang.github.io/Nim/manual.html#pragmas-push-and-pop-pragmas):

```nim
{.push discardable, boundChecks: off, compileTime, noSideEffect, experimental.}
template example(): string = "https://nim-lang.org"
{.pop.}
```

But if you try to use this template like so:

```nim
example()
```

You get:
```
Error: expression '"https://nim-lang.org"' is of type 'string' and has to be discarded
```

I'm not sure how many of the demonstrated pragmas are supposed to be meaningful (I can see that it's just a loose example after all), but this one stuck out to me because I've previously run into a situation where I've wished discardable would work with templates. My workaround was to wrap the result in a helper function like so:

```nim
func makeDiscardable[T](a: T): T {.discardable, inline.} = a
template example(): string = makeDiscardable("https://nim-lang.org")
example()
```

But regardless, I think either {.discardable.} for templates should be a real thing, or the manual should be changed so that people don't think the code in the snippet would actually work.

**Comment by alaviss** [comment]
That code have to be changed.

I'd say that templates can be misleading. On one hand they look and feel similar to proc, but people generally forget their true nature: AST substitution, which I don't think is highlighted well enough in the manual.

What templates do is that it takes the AST nodes passed as the parameter (if any) then substitute them into the placeholders in the prepared AST (if any), then substitute the resulting AST in place of the call.

Which means this template:

```nim
template example(): string = "https://nim-lang.org"
```

Resolves into:

```nim
"https://nim-lang.org"
```

On call. And since `{.discardable.}` don't apply to literals, the compiler errors out.

**Comment by krux02** [comment]
Well, `discardable` was designed as procedure tag only. So:

#### Possible Solutions

 * Improve documentation of `discardable` about what it can and should do.
 * Improve compiler error messages about `discardable` about what it can and can't do.

If you want discardable to just work with `templates` then this issue becomes a feature request. Do you want that? Or are you happy with the suggested fixes?

**Comment by juancarlospaco** [comment]
`template` has no return to discard by definition.

**Comment by exelotl** [comment]
Right, so I was thinking there could feasibly be a way to use `discardable` to annotate an expression

```nim
{.discardable.} "hello world"   # this would compile
var s = {.discardable.} "hello world"   # and so would this
```
And then `{.push discardable.}` could apply this behaviour to all expressions going forward. Also, a `discardable` tag for templates would simply be the same as making the final expression in the template discardable.

That said, I don't know if any of this is a good idea. Feel free to just update the docs and close the issue, it's not a huge problem.

**Comment by juancarlospaco** [comment]
I do not think this `discardable` everything is a big improvement, and may bring even more bugs.

Ive seen new people coming to Nim having problem understanding the differences and benefits of `template` Vs `proc` already,
so please do not give `template` a `return result` even if it is `discardable`.

But if you are interested on something similar but maybe more useful,
something similar to Scala `implicit` as a Nim macro would be nice.

**Comment by krux02** [comment]
@juancarlospaco do you mean implicit argument?

**Comment by Clyybber** [comment]
Templates don't make sense to be discardable, so I'll tag this as documentation instead.
