### ISSUE TITLE
gc:arc bug with ReraiseError

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#13616]
### Example
```nim
try:
  raise

except:
  echo "here"
```

### Current Output
```
Error: unhandled exception: no exception to reraise [ReraiseError]
```

### Expected Output
```
here
```

### Possible Solution

```nim
try:
  raise newException(ReraiseError, "")

except:
  echo "here"
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-03-09
```

**Comment by Araq** [comment]
Excuse me but this is not a bug. There is indeed no previous exception to re-raise.

**Comment by khchen** [comment]
However, the result is different between with and without --gc:arc.

**Comment by Araq** [comment]
My bad, I misremembered the spec.

**Comment by Araq** [comment]
Er no, Defects cannot be caught, no bug here, goto-based exception handling doesn't allow you to catch programming bugs.
