### ISSUE TITLE
Range types don't work with `BackwardsIndex` (and possibly others)

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#13618]
I was trying to combine the two `[]` procedures in the `deque` module, one that takes `Natural` and one that takes `BackwardsIndex`. When I changed the type to `Natural or BacwardsIndex` and added a `when` switch in the body of the procedure it stopped accepting integers.

### Example
```nim
proc test(x: Natural or BackwardsIndex): int =
  int(x)
  
echo test(^1) # This works
echo test(1)  # This doesn't
```

### Current Output
```
Error: type mismatch: got <int literal(1)>
but expected one of: 
proc test(x: Natural or BackwardsIndex): int
  first type mismatch at position: 1
  required type for x: Natural or BackwardsIndex
  but expression '1' is of type: int literal(1)

expression: test(1)
```

### Expected Output
```
1
1
```

**Comment by PMunch** [comment]
Changes the `Natural` to an `int` makes this example work fine.

**Comment by krux02** [comment]
probably related: https://github.com/nim-lang/Nim/pull/7265

**Comment by Clyybber** [comment]
Not really related I think. I think this is a sigmatch bug.
