### ISSUE TITLE
The documentation for "hot code reloading" references a non-existent npm package

### ISSUE THREAD

**Issue by drk-mtr** [nim-lang/Nim#13621]
Please see here: [https://nim-lang.org/docs/hcr.html](https://nim-lang.org/docs/hcr.html)

At the bottom of the page it states: `Once your code is compiled for hot reloading, the nim-livereload NPM package provides a convenient solution for implementing the actual reloading in the browser using a framework such as LiveReload or BrowserSync.`

The `nim-livereload` package doesn't appear to exist - does anyone know whether this was worked on but never published to npm?

I'd be really interested in trying to get this up and running. I'm hugely impressed that this is even possible. I got auto updates working using an elm-style architecture with almost no effort, so now I'm keen to be able to make updates and get auto-refresh while still preserving some client-side state.

**Comment by alehander92** [comment]
EDIT: nvm, sorry, i just saw there is a separate nim-livereload package in the docs 

[the package : it doesn't have anything to do with nim i guess :) maybe this one https://www.npmjs.com/package/livereload ? ]
