### ISSUE TITLE
`nim doc` - only whitespace on first line causes segfault

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#13631]
The `nim doc` command will segfault given a file containing the following. Note the trailing whitespace on the first line!

```nim
##   
## .. raw:: html
##   <p>hello</p>
```

Result:

```
$ nim doc test.nim
Hint: used config file 'C:\msys32\home\geckojsc\nim\nim-current\config\nim.cfg' [Conf]
Hint: used config file 'C:\msys32\home\geckojsc\nim\nim-current\config\nimdoc.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: test [Processing]
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

If a `code-block` is used instead of a `raw` block, no segfault occurs, but the correct formatting is not applied to the block.

```nim
##   
## .. code-block:: nim
##   echo "hello"
```

Result:

![image](https://user-images.githubusercontent.com/569607/76475940-c2406880-6400-11ea-8a26-208b63aa0a62.png)

### Additional Information

If the extraneous whitespace is removed (so we only have 1 trailing space instead of 3), the bug doesn't happen.

```nim
## 
## .. raw:: html
##   <p>hello</p>
```

It also doesn't occur if there is any content before the whitespace:

```nim
## foo
##   
## .. raw:: html
##   <p>hello</p>
```

I tried to replicate the bug in a program using the `rstgen` module, but nothing bad seems to happen:

```nim
import packages/docutils/[rst, rstgen]
import strtabs

echo rstToHtml("""
  
.. raw:: html
  <p>hello</p>
""", {roSupportRawDirective}, newStringTable(modeStyleInsensitive))
```

Result:
```
<p>hello</p>

```

Here's my Nim version. The bug also still happened on a recent devel build.

```
$ nim -v
Nim Compiler Version 1.0.6 [Windows: amd64]
```

**Comment by timotheecour** [comment]
@exelotl  PR welcome, this should be an easy fix, you can build compiler with --stacktrace:on and see where the SIGSEGV happens (something is likely nil and wasn't checked for)
