### ISSUE TITLE
asyncftpclient document example demo have bug

### ISSUE THREAD

**Issue by liyang1009** [nim-lang/Nim#13641]
The code example in  [https://nim-lang.org/docs/asyncftpclient.html](url) . about the function onProgressChanged is to be defined to have a bug, that does not return a Future[void]. this can cause the exception raise by function asyncCheck'statement  
```nim
assert(not future.isNil, "Future is nil")  
```
in lib/pure/asyncfutures.nim. so the onProgressChanged defined must have a return value.

**Comment by Clyybber** [comment]
Fixed with #15476
