### ISSUE TITLE
incorrect UnusedImport warning for const symbols

### ISSUE THREAD

**Issue by mfiano** [nim-lang/Nim#13673]
Nim doesn't appear to consider using a const as using a module

### Example
```nim
# common.nim
import math
const DEGREE* = PI/180

# test.nim
import common

proc radians*[T: Vec](o: var T, v: T) =
  for i, _ in o: o[i] = v[i] * DEGREE
```

### Current Output
`nim check` reports:
```
UnusedImport: imported and not used: 'common'
```
If I remove the `import common` line, `nim check` reports:
```
error| undeclared identifier: 'DEGREE'
```

### Expected Output
Nothing

### Possible Solution

Consider using a const as using its module

### Additional Information

None
```
$ nim -v
Nim Compiler Version 1.0.6 [Linux: amd64]
```

**Comment by timotheecour** [comment]
the snippet doesn't compile (because of `Vec`), is un-necessarily complicated (it should've been minimized), and the diagnostic is wrong (unrelated to const, but related to generics), I'm closing this issue in favor of https://github.com/nim-lang/Nim/issues/17941
