### ISSUE TITLE
Error message too generic for attempted type inference of generic proc's return value

### ISSUE THREAD

**Issue by capocasa** [nim-lang/Nim#13683]
When attempting to have a generic's return value's type be inferred, like so

### Example
```nim
type
  Foo = object
    foo: int
    bar: int

proc init[T](): T =
  result = T()

proc stringify[T](o: T):string =
  return $o

# fails with "cannot instantiate"
# let t:Foo = init()

# works
let t = init[Foo]()

# works
echo stringify(t)

```

### Current Output
```
Error: cannot instantiate: 'T'
```

### Expected Output
```
T is being returned from a generic proc, yet no explicit type has been set. Type inference is not supported for return values of procs.
```

### Possible Solution

Even better, [swallow pride](https://forum.nim-lang.org/t/3025#19018) and support type inference for return values like so
```nim
let t:Foo = init()
```
because it allows transferring existing knowledge which greatly eases learning.

### Additional Information

I'm aware this may be a bit high-detail for providing error information, and taking this approach may result in significantly more granularity in error reporting, however I believe from experience that a big part of PHP's popularity comes from being able to learn it from the error messages, which they achieved with about this level of granularity. (Pardon the wording of this last paragraph before the edit, it was meant to be funny but didn't seem to be on re-reading)

**Comment by metagn** [comment]
This type inference now exists with `{.experimental: "inferGenericTypes".}`
