### ISSUE TITLE
http response code bug 

### ISSUE THREAD

**Issue by suconghou** [nim-lang/Nim#13680]
Http200 works not ok 

### Example
```nim
import strutils
import httpclient


proc get*(url: string, timeout: int, str: string): bool =
    let client = newHttpClient(timeout = timeout)
    let resp = client.request(url)
    echo resp.status, " = ", Http200
    if resp.status == Http200:
        if str != "":
            return resp.body.contains(str)
        return true
    return false


echo "test 1 ", get("http://qrc.gszl.gov.cn/docs/changelog.html", 60000, "")
echo "test 2 ", get("http://tomcat.apache.org/", 60000, "")

```

### Current Output
```
200  = 200 OK
test 1 false
200 OK = 200 OK
test 2 true
```

### Expected Output
both of them should be true

### Additional Information

* the difference is the response line , `http://qrc.gszl.gov.cn/docs/changelog.html` response has no reason , as the document say `sendReasonPhrase` has been deprecated, tomcat 9 will only send `HTTP/1.1 200` 
* both mac and linux has the same issue 

please fix it as soon as possible
bye the way 
how can i fix this temporarily

```
$ nim -v
Nim Compiler Version 1.0.6 [MacOSX: amd64]
Compiled at 2020-01-29
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```

**Comment by juancarlospaco** [comment]
Which "document" ?, you forgot to link it or something.

Is it a bug?, as a lib developer I want to know if the server responded `"OK"` or `""` tho.
:thinking:

**Comment by suconghou** [comment]
@juancarlospaco  the document is tomcat's change log , open `http://qrc.gszl.gov.cn/docs/changelog.html` and search `sendReasonPhrase `
this means tomcat responded `HTTP/1.1 200`, but nginx responded `HTTP/1.1 200 OK`
thus  Example code works failed

**Comment by suconghou** [comment]
and other http code tomcat responsed similarly

tomcat  `HTTP/1.1 404` VS  nginx `HTTP/1.1 404 Not Found`

...

**Comment by juancarlospaco** [comment]
I understand, but hardcoding an `"OK"` or `"Not Found"` is losing information, by definition. :man_shrugging:

**Comment by suconghou** [comment]
maybe you can look at go's http package 

![image](https://user-images.githubusercontent.com/4580719/76975516-9d527500-696d-11ea-9579-b4a4d0c82af2.png)

**Comment by alaviss** [comment]
Here's how you should compare the result: https://play.nim-lang.org/#ix=2eC3

According to HTTP/1.1 standard:

> The reason-phrase element exists for the sole purpose of providing a
> textual description associated with the numeric status code, mostly
> out of deference to earlier Internet application protocols that were
> more frequently used with interactive text clients.  A client SHOULD
> ignore the reason-phrase content.
>
>     reason-phrase  = *( HTAB / SP / VCHAR / obs-text )

You can't expect that the `OK` is there. Instead compare only the code as in the linked snippet. This is not a bug, though the ability to compare a string with an integer constant does make this misleading if you're not familiar with the code.

 /cc @dom96 for that part of the issue.

**Comment by de-odex** [comment]
@alaviss `though the ability to compare a string with an integer constant does make this misleading` i'm pretty sure its still string to string comparison, just that the enum has a string value too apart from the int value, and that's what's being compared

**Comment by alaviss** [comment]
Yea, it does have an operator in `httpcore` for that, but I'd say that it's misleading.

**Comment by juancarlospaco** [comment]
If you can choose to compare between integers or compare between strings, 
go compare between integers, on any lang, probably is better.

**Comment by suconghou** [comment]
yes , I use ` resp.code == Http200` to compare, it works great 
thank you .
