### ISSUE TITLE
[wontfix] changes to gitattributes cause weird CRLF errors

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13690]
recent changes to gitattributes cause weird errors and deleting it in  a96842a didn't make things any better
This affects most of my PR's in progress after I rebase against devel, it causes `tests/arc/timportedobj.nim` to be marked as dirty, etc

### Example
```nim
git clone -q https://github.com/nim-lang/Nim
cd Nim
git rev-parse HEAD
15ba765ebd83e44d18a0a2c23016bdf3b4bbecca
cat -ve tests/tools/second.nim
import tables$
$
let dataEx* = {1: 2, 3: 4}.toTable$

git checkout 5017320
cat -ve tests/tools/second.nim
import tables^M$
^M$
let dataEx* = {1: 2, 3: 4}.toTable^M$

git checkout devel

```

### Current Output
```
error: Your local changes to the following files would be overwritten by checkout:
        tests/arc/timportedobj.nim
        tests/tools/second.nim
Please commit your changes or stash them before you switch branches.
Aborting
```

### Expected Output
no error

### Additional Information
* likely related to changes to gitattributes eg in https://github.com/nim-lang/Nim/pull/13670
* EDIT: might be due to a96842a too 
* as of git rev-parse HEAD
15ba765ebd83e44d18a0a2c23016bdf3b4bbecca
* I'm on OSX

the 1st time i got this:
```
warning: CRLF will be replaced by LF in tests/arc/timportedobj.nim.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in tests/tools/second.nim.
The file will have its original line endings in your working directory
```

* `git stash` doesn't even help, nor does `git checkout origin/devel -- tests/arc/timportedobj.nim`

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/13693 shows 2 things:
* a workaround (via `git add -A`) that can be used regardless of whether #13693 is merged
* a fix to prevent this issue from happening in the future

**Comment by timotheecour** [comment]
the 2nd type of error is:

suppose you have an old PR (or maybe a PR that was started after 5017320 ; I'm not sure)
```
$ git pull --rebase origin devel
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

$ git status
modified:   tests/arc/timportedobj.nim # just CRLF stuff
```

the workaround I'm using here:
```
$ git commit -am PRTEMP
$ git pull --rebase origin devel
# after resolving conflicts as usual, the last step may be the CRLF stuff

$ git rebase --continue
Applying: PRTEMP
No changes - did you forget to use 'git add'?
$ git rebase --skip
```
and you're back to a sane state rebased against devel

**Comment by cooldome** [comment]
try deleting local git repository and clone it again. Don't forget saving local the progress to github.

**Comment by timotheecour** [comment]
Deleting it can be disruptive   ( esp when you have non checked in files that you need to keep). Any other approach? Also what do you mean with your 2nd sentence?

**Comment by Araq** [comment]
Can we close this? ``.gitattributes`` doesn't exist anymore. (I got the same incomprehensible bugs and refuse to learn even more of git's many many quirks.)

**Comment by timotheecour** [comment]
Closed as Wontfix since bug is still there but only occurs when checking out / rebasing interacts  in a range of commits. The bigger problem is that we still allow CRLF to be checked in the repo, for which my PR would've provided a fix. But i can live with it.
