### ISSUE TITLE
detectOs in distros does not properly detect Ubuntu on WSL

### ISSUE THREAD

**Issue by sirredbeard** [nim-lang/Nim#13703]
Function `echo` outputs the wrong string.

### Example

On Ubuntu 18.04 on WSL.

```nim
import distros
if detectOs(Ubuntu):
    echo "Ubuntu"
else:
    echo "Not Ubuntu"
```

### Current Output
```
Not Ubuntu
```

### Expected Output
```
Ubuntu
```

### Possible Solution

Ubuntu is detected by distros by parsing the pattern of `uname -a` [here](https://github.com/nim-lang/Nim/blob/35fb38629f2f56d15afea15ba8597f18e2794229/lib/pure/distros.nim#L159)

On Ubuntu on WSL1 the output of uname -a is:
```
Linux T470s 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
On WSL2 it reports as:
```
Linux T470s 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I would propose that Ubuntu be detected by release, not uname.

### Additional Information

I am using Nim to write a tool that detects if it is running on Ubuntu and then installs a corresponding third-party apt repo.

**Comment by Araq** [comment]
I think you fixed that one.
