### ISSUE TITLE
New nim-gdb.bat has error

### ISSUE THREAD

**Issue by Angluca** [nim-lang/Nim#13705]
new nim-gdb.bat has error, I use python2.7
```
Type "apropos word" to search for commands related to "word"...
"C:\nim-1.0.6\\tools\nim-gdb.py": not in executable format: File format not recognized
"D:\test/test.exe": no core file handler recognizes format
source command requires file name of file to source.
```
old nim-gdb.bat can use, no error (nim-gdb script)
```
#new nim-gdb.bat
9  %@NIM_GDB% -eval-command="source  %@GDB_PYTHON_MODULE_PATH%" %*

#old ...
9  @echo source %@GDB_PYTHON_MODULE_PATH%> wingdbcommand.txt
10 %@NIM_GDB% --command="wingdbcommand.txt" %*
11 del wingdbcommand.txt /f /q
```

and nim/config/nim.cfg set debug -Og will optimizedout, Must set -O0
```
214 gcc.options.debug = "-g3 -O0 -gdwarf-3" 
```

**Comment by jyapayne** [comment]
I'll have to revert this change. The issue is that older GDB versions have a bug that doesn't allow the `eval-command` arg. And since most windows users are using the MinGW version on the Nim download page, the GDB version is 7.11.
