### ISSUE TITLE
Variable escaping parentheses scope

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#1371]
``` nimrod
(
var res = newSeq[float]();
for i in 0..1000:
res.add(i.float);)
res

#square.nim(12, 0) Error: value of type 'seq[float]' has to be discarded
# res
# ^
```

Expected result would be unexpected symbol or undeclared identifier.

**Comment by data-man** [comment]
Nim-devel now outputs
<pre><b>(5, 1) </b><font color="#DC322F">Error: </font>expression &apos;res&apos; is of type &apos;seq[float]&apos; and has to be discarded</pre>
