### ISSUE TITLE
typeof expressions are passed incorrectly to macros with typedesc argument

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#13724]
### Example
```nim
import macros

macro inspectType(arg: typedesc): untyped =
  echo arg.lispRepr

proc foobar() =
  var arg: int
  inspectType(typeof(arg))
```

### Current Output
```
(TypeOfExpr (Sym "arg"))
```

### Expected Output
```
(Sym "int")
```

**Comment by Araq** [comment]
Huh? Isn't that the "no special treatment of 'typedesc' " at work here that *you* implemented? I'm confused.

**Comment by krux02** [comment]
I am thinking right now. At least for me yesterday I thought ``(TypeOfExpr (Sym "arg"))`` should have been resoved into a typedesc node. But yes I get the typedesc node if I call ``getTypeInst`` on the argument.

**Comment by Clyybber** [comment]
The expected output makes more sense to me, IMO typedesc should behave more like `static T` here.
