### ISSUE TITLE
[regression, performance] iterator makes deep copy for openArray, can cause major slowdowns

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13726]
the recently merged https://github.com/nim-lang/Nim/pull/13712 causes a performance regression. Inline iterators are intended for speed, we shouldn't introduce un-necessary copies. /cc @krux02 

### Example
```nim
block:
  let n = 10_000_0000
  var s = newSeq[int](n)
  proc p2(): var seq[int] = s

  iterator ip1(v: openArray[int]): auto =
    yield v[0]
    yield v[^1]

  import times
  let t = cpuTime()
  for i in 0..<100:
    for x in ip1(p2()):
      doAssert x != -1
  echo cpuTime() - t
```

### Current Output
12.171379 # seconds

### Expected Output
7.000000000034756e-06 # seconds, before that PR, eg with nim 1.0.6

### Possible Solution
* revert https://github.com/nim-lang/Nim/pull/13712, and fix https://github.com/nim-lang/Nim/issues/13417 differently, by making openArray first class, see https://github.com/nim-lang/RFCs/issues/88

EDIT: the revert has been done in https://github.com/nim-lang/Nim/pull/13728

### Additional Information
* regression introduced in https://github.com/nim-lang/Nim/pull/13712

**Comment by krux02** [comment]
> [``# arrays will deep copy here (pretty bad).``](https://github.com/nim-lang/Nim/pull/13712/files)

Well I even put a comment about this performance problem in the code. So this is nothing new. I would have been nicer if this would have been complained ahead of time. But I guess performance is ranked higher than correctness in this particular case.
