### ISSUE TITLE
Illegal distinct seq causes compiler crash

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#13720]
### Example
```nim
type
  MutualCyclicSeqA = distinct ref seq[MutualCyclicSeqB]
  MutualCyclicSeqB = distinct ref seq[MutualCyclicSeqC]
  MutualCyclicSeqC = distinct ref seq[MutualCyclicSeqA]

var mt: MutualCyclicSeqA
```

### Current Output
```
SIGSEGV
```

### Expected Output
```
illegal recursion in type
```

### Additional Information

* I hit this bug during my refactorings in  #13687

**Comment by timotheecour** [comment]
title could be improved for searchability

**Comment by krux02** [comment]
@timotheecour not only that, but the issue still contained some text of the issue template.
