### ISSUE TITLE
A regression (?) with --gc:arc and repr

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#13731]
repr doesn't work with a File object on devel 

### Example
```nim
# Compile with nim c --gc:arc file.nim
import os
var a: File
echo repr a
```

### Current Output
```
/home/dian/stuff/nim-cephei/test.nim(5, 11) Error: ambiguous call; both repr_v2.repr(x: ref T or ptr T) [declared in /home/dian/.nim/lib/system/repr_v2.nim(106, 6)] and repr_v2.repr(x: ptr T) [declared in /home/dian/.nim/lib/system/repr_v2.nim(102, 6)] match for: (File)
```

Nim compiler hash is fc5dd11b3da555a3617c1163dc3105973d101b97

**Comment by Clyybber** [comment]
I think narimirans fix is correct, but there is also a sigmatch issue.. I think `ptr T` shouldn't be ambiguous with `ptr T or ref T` as `ptr T` is more specific.

**Comment by timotheecour** [comment]
> I think narimirans fix is correct, but there is also a sigmatch issue.. I think ptr T shouldn't be ambiguous with ptr T or ref T as ptr T is more specific.

not 100% sure whether it's already covered in https://nim-lang.github.io/Nim/manual.html#overloading-resolution but I disagree, sigmatch is correct in this case and I see no use case for `A` overloading `A or B` (it just indicates library error)

**Comment by Clyybber** [comment]
From the manual:
> Likewise for generic matches the most specialized generic type (that still matches) is preferred
