### ISSUE TITLE
bool conversion produces vcc 2019 warning at cpp compilation stage

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#13744]
The following example produces warning with cpp target and vcc 2019:
```nim
var i = 1
let x = bool(i)
echo x
```

vcc 2019 warning:
```
a.nim(4): warning C4804: '<': unsafe use of type 'bool' in operation
a.nim(4): warning C4804: '>': unsafe use of type 'bool' in operation
```

Warning is produced on the following generated range check code:
```
if ((i) < NIM_FALSE || (i) > NIM_TRUE){ raiseRangeErrorI(i, NIM_FALSE, NIM_TRUE); }
x = ((NIM_BOOL) (i));
```

`<` and `>` comparison with `true` and `false` is not quite correct cpp.

**Comment by cooldome** [comment]
Possible solutions.
1. silence `C4804` warning
2. change range check code to use `0` and `1` in generated code.
3. another solution is to generate the following bool conversion code instead:
```
x = ((NIM_BOOL) (i != 0));
```
in this case no range checks are required at all.
I like the last one.

@Araq, let me know your preference

**Comment by Araq** [comment]
Every solution is fine with me including not emitting any check at all.
