### ISSUE TITLE
`tests/exception/t9657` fails on OpenBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#13760]
The test [`tests/exception/t9657`](https://github.com/nim-lang/Nim/blob/devel/tests/exception/t9657.nim) fails on OpenBSD, as the test exits with exit code 0.

The following C file also exits without any output and a status code of 0:

```
#include <stdio.h>
#include <string.h>

int main(int argc, char** argv)
{
        char* msg = "exception!";
        int ret = fclose(stdout);

        if (ret != 0) {
                perror("fclose error");
                return 1;
        }

        fwrite(msg, 1, 10, stdout);
        ret = ferror(stdout);

        if (ret != 0) {
                char* errmsg = strerror(ret);
                fprintf(stderr, "fwrite error %d: %s", ret, errmsg);
                return 1;
        }

        return 0;
}
```

We should probably disable this test for OpenBSD, though it seems odd that this isn't an error in OpenBSD...

**Comment by brynet** [comment]
Calling fwrite/ferror after fclose is undefined behaviour. If that's what the test is boiling down to, then the test is bogus.

>  After the call to fclose(), any use of stream results in undefined behavior.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html
