### ISSUE TITLE
`tosprocterminate` fails on OpeBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#13775]
The test [`tosprocterminate`](https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/tosprocterminate.nim) fails on OpenBSD fails as the `/bin/sh` process doesn't terminate after receiving a `SIGKILL`:

```
Category: stdlib
Name: tests/stdlib/tosprocterminate.nim C
Action: run
Result: reOutputsDiffer
-------- Expected -------
SUCCESS
--------- Given  --------
starting /bin/sh
stopping process
FAILED
-------------------------
```

Manually testing killing `/bin/sh` in OpenBSD via `SIGTERM` also fails:

1. Run `/bin/sh` and get it's PID (`echo $$`)
2. Run `kill -s TERM $pid` (where `$pid` is the PID from above) from another session (easiest approach is to use emu with two windows)
3. The `/bin/sh` process is not terminated

Looking at the sh documentation, `SIGTERM` is ignored if a session is interactive: https://man.openbsd.org/sh.1#ASYNCHRONOUS_EVENTS

I'm not sure if disabling this test is the best idea, or if another long-running command should be used instead...

**Comment by alaviss** [comment]
Try `/bin/cat`? It won't terminate until you close its `stdin`.

**Comment by euantorano** [comment]
Will give it a try and see what happens.

**Comment by euantorano** [comment]
`/bin/cat` does appear to work locally, just waiting for CI to finish. Thanks for the suggestion!
