### ISSUE TITLE
DateTime initializes to invalid state by default

### ISSUE THREAD

**Issue by capocasa** [nim-lang/Nim#13797]
DateTime initializes to invalid state by default

This makes it necessary to perform manual initiation to have valid data, something which nim is designed to avoid.

Without manual initialization, the common programming pattern of comparing a value to a default value is not possible, because the default value cannot be reproduced without the hackily creating another empty mutable datetime

### Example
```nim
var a:DateTime
import times

var d:DateTime

for k, v in fieldPairs(d):
  echo "k: ", k, " v: ", v

```

### Current Output
```
k: nanosecond v: 0
k: second v: 0
k: minute v: 0
k: hour v: 0
k: monthday v: 0
k: month v: 0 (invalid data!)
k: year v: 0
k: weekday v: Monday
k: yearday v: 0
k: isDst v: false
Traceback (most recent call last)
/home/carlo/a.nim(7)     a
/usr/lib/nim/pure/times.nim(1039) $
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

output equivalent to a valid zerodate, similar to zeroduration

### Possible Solution

I currently manually initialize to fromUnix(0) as a workaround, but it would be good to have a valid nim-specific zero date to initialize from, such as the actual beginning of the gregorian calendar (Jan 1 0000)

### Additional Information

Minor inconsistency but these do consume brain cycles during application development, and these do add up

```
Nim Compiler Version 1.0.6 [Linux: amd64]
Compiled at 2020-02-08
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace


```

**Comment by kaushalmodi** [comment]
I've noticed this too.. so I end up doing this at few places: https://play.nim-lang.org/#ix=2fSB (initializing using `now()`).

**Comment by capocasa** [comment]
I found a reasonably good workaround for checking if a datetime changed after implicit initialization: Use a compiletime var to compare with.

```
import times

var zdt {.compileTime.} : DateTime

var d:DateTime

if false:
  d = now()

if d == zdt:
  echo "unchanged"
```

**Comment by timotheecour** [comment]
> I found a reasonably good workaround for checking if a datetime changed after implicit initialization: Use a compiletime var to compare with.

this is simpler:
```nim
when true:
  import times
  var d:DateTime
  if d == DateTime.default:
    echo "unchanged"
```

I think it's fine that the 0-initialized date is invalid; however I'm fishing the segfault here:  #13812

**Comment by capocasa** [comment]
`DateTime.default`

Good enough for me!

Edit: [found documentation](https://nim-lang.org/docs/system.html#default%2Ctypedesc), I'll see if there's a nice unobtrusive place in the `times` docs explanations for a cross reference.

Edit 2: Actually, the real need here is an automatically generated list of cross references to applicable generic procs for every type in every module, and in the index.
