### ISSUE TITLE
hashset regression

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#13794]
It appears that #13418 has regressed the `HashSet` implementation.

The repro isn't straightforward but this actually leads to a leak from what I can tell. Lucky for me I spent the whole day tracking it down in my game :/

Here is the repro: https://gist.github.com/dom96/f84dd692f42a35c30bbee14309529d9e

**In order to compile it you'll need to export `data` in `HashSet` type**.

**For devel:**

```
$ nim c -r repro.nim
1024
7
```

**For 1.0.6:**

```
$ nim c -r repro.nim
64
7
```

During the runtime of my game the set's size keeps growing, which makes iterating over it slower and slower.

**Comment by narimiran** [comment]
cc @timotheecour @c-blake

**Comment by timotheecour** [comment]
@dom96 thanks for bug+repro, can you please check if https://github.com/nim-lang/Nim/pull/13800 fixes your issue?
It should work but if not, I'll investigate further.
