### ISSUE TITLE
_ (underscore) is not ignored inside templates

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#13804]
### Example

1. _ gets gensym'd if used as a variable name:

```nim
template foo() =
  let _ = 3

foo()
```

2. _ is substituted if used as a parameter name for the template

```nim
template foo(_: int) =
  for _ in 1..3: # Error: identifier expected, but found '4'
    echo "hello"

foo(4)
```

### Current Output

1.

```
(2, 7) Hint: '_`gensym133006' is declared but not used [XDeclaredButNotUsed]
```

2.

```
(5, 5) Error: identifier expected, but found '4'
```

### Expected Output
doesn't warn or error, correctly does not gensym in the first case, and does not try to substitute in the second case

### Workaround
```nim
template foo() =
  let _ {.inject.} = 3

foo()
```

```
$ nim -v
Nim Compiler Version 1.2.6
```

**Comment by Araq** [comment]
What's the use case though? Your example should use ``discard``.

**Comment by SolitudeSF** [comment]
```nim
template foo =
  let (_, a, b) = (3, 4, 5)
```
warns when unpacking a tuple

**Comment by demotomohiro** [comment]
When 2 "`_`" are used in tuple unpacking in a template, it generate compile error.

```nim
#No compile error
let (_, _, x) = (1, 2, 3)
echo x

template test() =
  #Error: redefinition of '_`gensym3387051'; previous declaration here: f:\temp\testTU.nim(5, 8)
  let (_, _, x) = (1, 2, 3)
  echo x

test()
```

**Comment by metagn** [comment]
Just ran into this bug again, but in a different way. Not only do templates not ignore `_`, they also try to substitute with it if it's the name of a parameter.

```nim
template foo(_: int) =
  for _ in 1..3: # Error: identifier expected, but found '4'
    echo "hello"

foo(4)
```

**Comment by ringabout** [comment]
It can be used inside procs too.

```nim
proc main(_: int) = echo _
```

https://github.com/nim-lang/Nim/issues/13443#issuecomment-809838183

**Comment by metagn** [comment]
Fixing #13443 should fix second part (although should still be tested) so don't need to specifically fix it yet.

Edit: This might not be true, `semtempl` might still need to be patched
