### ISSUE TITLE
`os.getApplFreebsd` could return incorrect paths in the case of a long path

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#13806]
As [noticed by @timotheecour](https://github.com/nim-lang/Nim/pull/12179#discussion_r399875661), [`os.getApplFreebsd`](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2793) seems like it has a possibility to return incorrect paths in the case of a path being a very long value.

> The information is copied into the buffer specified by oldp. The size of the buffer is given by the location specified by oldlenp before the call, and that location gives the amount of data copied after a successful call and after a call that returns with the error code ENOMEM. If the amount of data available is greater than the size of the buffer supplied, the call supplies as much data as fits in the buffer provided and returns with the error code ENOMEM. If the old value is not desired, oldp and oldlenp should be set to NULL.

It is recommended to instead use two calls to `sysctl` - the first with `oldp` set to `NULL` in order to get the required capacity, then another with the required capacity:

> The size of the available data can be determined by calling sysctl() with the NULL argument for oldp. The size of the available data will be re- turned in the location pointed to by oldlenp. For some operations, the amount of space may change often. For these operations, the system attempts to round up so that the returned size is large enough for a call to return the data shortly thereafter.

https://www.freebsd.org/cgi/man.cgi?sysctl(3)

**Comment by timotheecour** [comment]
> There are two options:
> Keep the data from the first call, and grow the buffer
> Delete the old data, and start with a clean buffer (eg: first call is just used to get the required buffer size, then a second call is made to get the actual data)
> I think the second option would be easiest to implement.

I agree with 2nd option
