### ISSUE TITLE
Nim locks: unspecified re-entrantism

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#13802]
From the [docs](https://nim-lang.org/docs/locks.html):

`Nim lock; whether this is re-entrant or not is unspecified!`

This is pretty bad.

**Comment by juancarlospaco** [comment]
- https://nim-lang.org/docs/rlocks.html

**Comment by ghost** [comment]
@juancarlospaco it is nice that rlocks exist but locks should be either re-entrant or not and let the developer decide when to use the other. This is unspecified behavior.

**Comment by Araq** [comment]
Well you can reliably use it by not entering the locking code in a re-entrant way...
