### ISSUE TITLE
streams.readStr() allocates new string on each call

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#13857]
### Summary
We have

`streams.readLine(s: var string)`

but we also have

`streams.readStr(length: int): string`

which allocates a new string on each call.

### Description
Usually, the purpose of `readStr()` is to be called repeatedly, on same-length or similar-length records, so I'd like to re-use the allocated string memory. It's a minor optimization.

### Alternatives
The alternative is to avoid the **streams** library.

### Additional Information
I'm happy to code this change myself. Would it be accepted?

**Comment by Araq** [comment]
Yes, will be accepted.
