### ISSUE TITLE
Converting len of cstring to signed int types causes RangeError

### ISSUE THREAD

**Issue by mrgaturus** [nim-lang/Nim#13859]
Converting len of cstring to signed int types causes RangeError, but the number is in the range

### Example
```nim
let str = "abc".cstring
echo len(str).int8
echo len(str).int16
echo len(str).int32
var str2 = "cde".cstring
echo len(str2).int8
echo len(str2).int16
echo len(str2).int32
```

### Current Output
```
Error: unhandled exception: value out of range: 3 notin -128 .. 127 [RangeError]
```

### Expected Output
```
3
3
3
3
3
3
```

### Additional Information

* It was working in version 1.0.x

```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by juancarlospaco** [comment]
- Can Repro.
- Works with `-d:danger`.
- Works with cstring Literal `echo len("abc".cstring).int16`.
- Works with float `echo len("abc".cstring).float32`.
- Works with `const`:

```nim
const str = "abc".cstring
echo len(str).int32
```
