### ISSUE TITLE
inconsistent status of "not nil" in docs vs. compiler

### ISSUE THREAD

**Issue by akavel** [nim-lang/Nim#13861]
The main Nim Manual mentions `not nil` as a regular feature, not in the "experimental features" appendix, and with no mention of pragma, but the compiler complains that it wants a pragma:

### Example
```nim
type Foo = ref int not nil
```

### Current Output
```
Error: enable the 'not nil' annotation with {.experimental: "notnil".}
```

### Expected Output
Expected to compile just fine without "experimental" pragma.

### Possible Solution

If "not nil" is still experimental, I'd expect its section to be moved from the main Nim Manual to the "experimental features" appendix (https://nim-lang.org/docs/manual_experimental.html)

```
$ nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by ghost** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/14027
