### ISSUE TITLE
Use #include to include Nim modules instead of static linking

### ISSUE THREAD

**Issue by Keithcat1** [nim-lang/Nim#13901]
Currently, Nim compiles each generate C file and then links all the object files together to form the final binary.
However, if all nim modules could be #included into the main C file, the compilation process would be faster. Additionally, the C compiler could dod cross-module optimization with out LTO.
Would this be feasible?

**Comment by Araq** [comment]
But the current setup allows us to compile the C files in parallel, so it's faster. Feel free to enable LTO, it's 2020, it works well.

**Comment by Keithcat1** [comment]
Can you add a way to enable LTO for all compilers? I doubt everyone knows how to turn it on.

**Comment by ghost** [comment]
> Can you add a way to enable LTO for all compilers? I doubt everyone knows how to turn it on.

It's usually just passing --passC:-flto --passL:-flto
(I'm not 100% sure if you need to specify -flto for both compiler and linker)
