### ISSUE TITLE
HCR: Can not link exported const, in external library

### ISSUE THREAD

**Issue by TC218** [nim-lang/Nim#13915]
I'm trying to use this library: https://github.com/Vindaar/shell
  with Nim HCR, and LD linker can't link exported const symbol, for some reason:

  This is my fork of this library, with added export symbol (original didn't have):
    [https://github.com/xtazy-drop/test-nim-hcr-shell](https://github.com/xtazy-drop/test-nim-hcr-shell)

```
    ...
    
    const defaultDebugConfig*: set[DebugOutputKind] =
      block:
        var config: set[DebugOutputKind] = {
          dokOutput, dokError, dokCommand, dokRuntime
        }
        
    ...
```     
        
### Compilation output:
  
```
$ nim c --outdir:f --hotcodereloading:on  --hints:off test_nim_hcr_shell.nim

/usr/bin/ld: /home/ubuntu-mate/.cache/nim/test_nim_hcr_shell_d/@mtest_nim_hcr_shell.nim.c.o: in function `NimMainModule':
@mtest_nim_hcr_shell.nim.c:(.text+0xec8): undefined reference to `defaultDebugConfig__LgOdL9aGyblIQIS067yE8vw'
collect2: error: ld returned 1 exit status
```

  When I link manually, against .so file of this library, then it links fine (nim v1.0.6):
    ```
    $ gcc   -o f/test_nim_hcr_shell $cache_dir/@mtest_nim_hcr_shell.nim.c.o  $cache_dir/lib@mf@sshell@sshell.nim.c.so   -lm -lrt   -ldl
    ```
      - works for nim v1.0.6
      - doesn't work for nim v1.2.0

### Test script:
  
  ```
  $ git clone https://github.com/xtazy-drop/test-nim-hcr-shell
  $ cd test-nim-hcr-shell/
  $ ./get-shell.sh
  $ ./compile.sh
  ```
  

### defaultDebugConfig_* symbol generations: 

  Nim v1.0.6:
    Generated file ```@mf@sshell@sshell.nim.c```, line 230:
```
NIM_CONST tySet_tyEnum_DebugOutputKind__RLJKb7vjqsoNJNVirVUgNg defaultDebugConfig__LgOdL9aGyblIQIS067yE8vw = 15;
```

  Symbol record in .so file:
```
   $ objdump -t /home/ubuntu-mate/.cache/nim/test_nim_hcr_shell_d/lib@mf@sshell@sshell.nim.c.so | grep defaultDebugConfig
      00000000000031e0 g     O .rodata	0000000000000001              defaultDebugConfig__LgOdL9aGyblIQIS067yE8vw
```
      
  Nim v1.2.0:
    Generated file @mf@sshell@sshell.nim.c, line 194:
```
N_LIB_PRIVATE NIM_CONST tySet_tyEnum_DebugOutputKind__RLJKb7vjqsoNJNVirVUgNg defaultDebugConfig__LgOdL9aGyblIQIS067yE8vw = 15;
```

  Symbol record in .so file::
```
  $ objdump -t ~/.cache/nim/test_nim_hcr_shell_d/lib@mf@sshell@sshell.nim.c.so | grep defaultDebugConfig
      00000000000031e0 l     O .rodata	0000000000000001              defaultDebugConfig__LgOdL9aGyblIQIS067yE8vw
```

**Comment by alaviss** [comment]
Simpler example:

a.nim:
```nim
const A* = [1, 2, 3]
```

b.nim:
```nim
import a
echo A
```

I have a good idea of where this issue came from. Testing a fix right now.

**Comment by alaviss** [comment]
We might need to bring in whoever implemented HCR to deal with this. Look like the engine wasn't designed to deal with constants.

**Comment by alaviss** [comment]
@onqtam Can you take a look? Looks like the codegen didn't consider the case where `const` is a complex type.

**Comment by onqtam** [comment]
@alaviss I'll try to take a look this weekend.

**Comment by onqtam** [comment]
@alaviss you mentioned you have an idea where the issue comes from (perhaps a specific commit..?) & a supposed fix?

**Comment by alaviss** [comment]
https://github.com/nim-lang/Nim/blob/devel/compiler/cgen.nim#L1166

There you go. This part of the codegen is not HCR-aware. I thought `N_LIB_PRIVATE` was the problem, but then I realize that HCR have more hooks than that :P, so I ping you.

**Comment by onqtam** [comment]
Well, I didn't get to this during the weekend but will try to take a look whenever possible. Sorry for the broken promise.

**Comment by onqtam** [comment]
I opened a PR for this problem: https://github.com/nim-lang/Nim/pull/14115
However I did hit another problem while testing, which seems to have already been reported: https://github.com/nim-lang/Nim/issues/11974 - that is something I definitely have to look into - hopefully *soon* (whatever that means).

Out of curiosity - is hot code reloading being used somewhere? @alaviss you seem to be pretty active around HCR issues... I see that someone has written some documentation about it: https://nim-lang.org/docs/hcr.html

**Comment by Vindaar** [comment]
> Out of curiosity - is hot code reloading being used somewhere?

Not by me at least (and I'm not aware of anywhere, but that doesn't say a lot). I tried to write a prototype repl, but failed pretty badly. I put the code here:

https://github.com/vindaar/brokenrepl

Maybe what I'm doing there is pretty stupid in the first place (regarding the usage of HCR, the repl logic is obviously primitive), but the errors I stumbled upon where too weird for me to make much of. 

Feel free to take a look if you want to see another failed usage.

**Comment by onqtam** [comment]
@Vindaar I should definitely first fix the remaining known issues (such as https://github.com/nim-lang/Nim/issues/11974 ) and also look into the new GC/arc/etc. options...

@xtazy-drop did hot code reloading work for you when you were using Nim `v1.0.6`?

**Comment by Vindaar** [comment]
I just read my last message again and realized it might be read in a kind of entitled way. Sorry about that @onqtam. It was supposed to be humorous.

**Comment by onqtam** [comment]
Lol don't worry - it doesn't sound entitled and even if it did - so what :D
Regardless of that - I feel a bit guilty of not pushing this to completion year ago - having a REPL would be super cool - I just reached only 1/3 of the original goal...
