### ISSUE TITLE
combine `ref object` definition and `not nil`

### ISSUE THREAD

**Issue by c-cube** [nim-lang/Nim#13942]
### Summary
be able to combine a `ref object` definition with nil annotation

### Description
Allows to use `not nil` in the common case where one defines a ref object

```nim
type Foo = ref object not nil
  a: int
  b: string
```

### Alternatives
NA

### Additional Information

**Comment by Araq** [comment]
Instead use 

```nim

type Foo = object 
  a: int
  b: string

```
