### ISSUE TITLE
Call link.exe instead of cl.exe when compiling with VCC

### ISSUE THREAD

**Issue by Keithcat1** [nim-lang/Nim#13956]
When linking .obj files created by VCC, Nim calls cl.exe and passes it linker options. However this makes it awkward to pass -l options, I need to do it like:
nim c -l:"/link /LTCG" test.nim
To fix this, it would be really nice if Nim just called link.exe instead.

**Comment by Araq** [comment]
Calling the linker directly is a never ending PITA, nobody knows what to link to get the standard C(++) library to the program.

**Comment by Keithcat1** [comment]
msvcrt.lib or ucrt.lib, I think
