### ISSUE TITLE
Documentation search is too fuzzy

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#13955]
I was not sure if add() for strings needs import strutils, so I went to

https://nim-lang.org/docs/lib.html

and typed in "add" in the search entry. 

add() for strings and add() for seq is not displayed -- that is really bad for beginners.

**Comment by metagn** [comment]
The search there is limited to 20 results, [theindex](https://nim-lang.org/docs/theindex.html#add) is much more comprehensive (lib.html actually fetches this page first then does a search on it). Maybe theindex should be linked at the start of lib.html or something but I don't see how this needs fixing otherwise. Also bad issue title.

**Comment by StefanSalewski** [comment]
Whatever, it is very bad.

Beginners may guess that something like append may exist, and additional try add. But only strange procs like dom: addEventListener() appears.

When I enter add, I want to get procs exactly matching that name first. And maybe after that the procs from system module. And only to the bottom the exotic ones.

I have no idea how we can do that unfortunately.

**Comment by metagn** [comment]
I should have mentioned, the search is fuzzy ([source code](https://github.com/nim-lang/Nim/blob/devel/tools/dochack/fuzzysearch.nim)). If you search "add string" the first 3 results give what you want. [Full search code is in here](https://github.com/nim-lang/Nim/blob/devel/tools/dochack/dochack.nim)

**Comment by StefanSalewski** [comment]
That is interesting., did not know that. OK, then I will close this issue tomorrow.

**Comment by Araq** [comment]
> That is interesting., did not know that. OK, then I will close this issue tomorrow.

I hope by sending us a PR that fixes/changes the behaviour! :-)

**Comment by narimiran** [comment]
> Whatever, it is very bad.

I've tried to tweak parameters of `fuzzysearch.nim` to accommodate to your wishes:
> I want to get procs exactly matching that name first. And maybe after that the procs from system module. And only to the bottom the exotic ones.

but whatever I did the results wouldn't satisfy your criteria.
Until somebody more capable than me manages to tweak it better, you'll have to use the workaround @hlaaftana posted and give the search more information to work with.

**Comment by StefanSalewski** [comment]
Thanks. Indeed when one knows that one can type in something like "add string" then it works fine.

Maybe you can add after "Read this document for a quick overview of the API design."

a comment like

"On the left is an entry for fuzzy search, you can type in for example proc names or proc name and type of parameter like "add string"".
