### ISSUE TITLE
os.splitFile isn't working on windows, but on linux

### ISSUE THREAD

**Issue by faulander** [nim-lang/Nim#13971]
ext = correct
name = the full path including the filename, without extension
dir = empty

### Example
```import os, strutils

var fullFile = r"c:\users\xxx\Pictures\2019 - Scotland the beautiful\img-001.jpg"
var (dir, name, ext) = splitFile(fullFile)
echo dir
echo name
echo ext
```

### Current Output
```
"" (empty string)
c:\users\xxx\Pictures\2019 - Scotland the beautiful\img-001
.jpg
```

### Expected Output
```
c:\users\xxx\Pictures\2019 - Scotland the beautiful
img-001
.jpg
```

### Possible Solution

* use const DirSep from os?

**Comment by timotheecour** [comment]
can't reproduce. works on 1.2.0, 1.0.6 and on latest devel c2699648604cc57cd55ecd7d88ccd55ed38099fb   (using windows 10)

@faulander please always mention which version of nim (either git tag or git hash) you're using, otherwise it's not actionable; can this be closed?

**Comment by Araq** [comment]
Can't reproduce. Maybe your ``\`` is not a real ``\`` but some other Unicode thing that merely looks like ``\``.

**Comment by stisa** [comment]
Just ran into this, seems to affect the playground too: [https://play.nim-lang.org/#ix=2wKg](https://play.nim-lang.org/#ix=2wKg)

**Comment by Araq** [comment]
The playground uses Linux. No bug here.

**Comment by stisa** [comment]
True, but I swear I was running into this on Windows, but I can't reproduce it anymore, I don't get it. Sorry about that.
