### ISSUE TITLE
array subscripts in untyped template inside generic proc using Nim 32 bit produce undeclared identifier error

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#13979]
using undeclared identifier inside untyped template with Nim 32 bit will produce 'undeclared identifier error' but Nim 64 bit version allow it.

### Example
```nim
proc filterScanline*[T](input: openArray[T]) =
  template currPix: untyped = input[i]
  for i in 0..<input.len:
    debugEcho currPix
    
let pix = [1, 2, 3]
filterScanline(pix)
```

### Current Output
```
F:\projects\nimPNG\nimPNG\bug.nim(2, 37) Error: undeclared identifier: 'i'
```

### Expected Output
```
1
2
3
```

### Possible Solution
* it works with non generic proc
* it works if we add (i) param to the template

### Additional Information

* it works with Nim 64 bit

```
$ nim -v
Nim Compiler Version 1.3.1 [Windows: i386]
Compiled at 2020-04-14
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by metagn** [comment]
What if you use `mixin i`?

**Comment by jangko** [comment]
it works with `mixin i` put before template declaration.
seems similar with https://forum.nim-lang.org/t/5822 symptoms.

I'm not sure if it is a bug or not for this 32bit behavior. But the inconsistency between 64 and 32 bit compiler is a bug.
