### ISSUE TITLE
Using type seq when seq[string] should be specified results in a confusing error message

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#13992]
If the type should be seq[string] but only seq is used then the following error is encountered:

    Error: internal error: genTypeInfo(tyNone)
    No stack traceback available
    To create a stacktrace, rerun compilation with ./koch temp c <file>

Example incorrect code (confusing error message produced):

    let test:seq = @[ "abc" ]

Should have correct code (no error message):

    let test:seq[string] = @[ "abc" ]

I have tested this with Nim v.1.2.0 and v.1.3.1 (development: compiled at 2020-04-16).

**Comment by OneArb** [comment]
The issue only occurs when the variable remains unused:

`var seq1: seq = @[1, 3, 5, 7]`

`Error: internal error: genTypeInfo(tyNone)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
`

`var seq1: seq = @[1, 3, 5, 7]
echo seq1[0]`

` Error: type mismatch: got <None>`

**Comment by jfilby** [comment]
> 

The compiler also errors when used for me:

```Nim
let test: seq = @[ "abc" ]

echo $test
```

The internal error occurs on compilation. This is really just a request for a less confusing error message, instead of an internal error.

**Comment by ringabout** [comment]
Now, it gives error: `Error: invalid type: 'None' in this context: 'seq' for let` on the devel branch

**Comment by jfilby** [comment]
That's much better, thanks.
