### ISSUE TITLE
Cant use expressions with `when` in `type` sections.

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#14007]
Using expression in `when` in `type` section results in compiletime error.

### Example
```nim
const val = 10
 
type t = object
  when val >= 10:
    a: int
```

### Current Output
```
Error: constant expression expected
```

### Expected Output
Successfull compilation

Assigning result of an expression to another constant workarounds the issue.
```nim
const
  val = 10
  v = val >= 10

type t = object
  when v:
    a: int
```

### Additional Information
This was never working

**Comment by metagn** [comment]
`static(val >= 10)` also works

**Comment by cooldome** [comment]
I have a fix
