### ISSUE TITLE
appendString needed when casting integers to range types with os:standalone

### ISSUE THREAD

**Issue by clj** [nim-lang/Nim#14011]
When using `--os:standalone` together with `--gc:none` and cast integers (and presumably floats) to a range type compilation fails with `Error: system module needs: appendString`.

### Example
```nim
type
  rangeType = range[0..1]

var
  r: rangeType = 0
  i = 2

r = rangeType(i)
```

### Current Output
```
$ nim  c --os:standalone --gc:none test.nim
...
Error: system module needs: appendString
```

### Expected Output
a successful compile

### Possible Solution

Having separate code for the case when `hostOS == "standalone"` for these two procs:
 
https://github.com/nim-lang/Nim/blob/f10689d3d40d67b185c918440ceef6a6bcee9999/lib/system/chcks.nim#L31-L35

### Additional Information

* #10978 is a similar issue (fixed)

```
nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by argonotix** [comment]
I've verified that the proposed solution works locally on the current development hash of e4e5a0c65ab10f48746f8f9b2417e8ca69724a04.
