### ISSUE TITLE
CI broken for release branches (version-1-0, version-1-2)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14026]
while backporting a feature (to make `nim dump` work better with prior releases), I noticed that CI is broken for both version-1-0 and version-1-2:
see https://github.com/nim-lang/Nim/pull/14024 and https://github.com/nim-lang/Nim/pull/14022

Without a working CI it's impossible to tell whether a backport will introduce a regression.

**Comment by alaviss** [comment]
CI is passing for `version-1-2`, but not for `version-1-0` though.

**Comment by timotheecour** [comment]
it was failing in https://github.com/nim-lang/Nim/pull/14024 but https://github.com/nim-lang/Nim/commit/dd0e823a0ca94ada3a8e155838da07f76e223012 just backported https://github.com/nim-lang/Nim/pull/13984 to `version-1-2`

**Comment by narimiran** [comment]
In future, please don't open issues for stuff like this.
