### ISSUE TITLE
Nim In Action SFML test fails on OpenBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#14033]
The Nim In Action SFML test `tests/niminaction/Chapter8/sfml/sfml_test.nim` fails on OpenBSD with the following error:

```
$ nim c -r tests/niminaction/Chapter8/sfml/sfml_test.nim
Hint: used config file '/home/euant/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/euant/Nim/config/config.nims' [Conf]
Hint: used config file '/home/euant/Nim/tests/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: sfml_test [Processing]
Hint: sfml [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/stdlib_system.nim.c.o /home/euant/.cache/nim/sfml_test_d/stdlib_system.nim.c [Exec]
Hint: clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/stdlib_posix.nim.c.o /home/euant/.cache/nim/sfml_test_d/stdlib_posix.nim.c [Exec]
Hint: clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/stdlib_times.nim.c.o /home/euant/.cache/nim/sfml_test_d/stdlib_times.nim.c [Exec]
Hint: clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/stdlib_os.nim.c.o /home/euant/.cache/nim/sfml_test_d/stdlib_os.nim.c [Exec]
Hint: clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/@msfml_test.nim.c.o /home/euant/.cache/nim/sfml_test_d/@msfml_test.nim.c [Exec]
/home/euant/.cache/nim/sfml_test_d/@msfml_test.nim.c:10:10: fatal error: 'SFML/Graphics.hpp' file not found
#include <SFML/Graphics.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
Error: execution of an external program failed: 'clang -c  -w   -I/home/euant/Nim/lib -I/home/euant/Nim/tests/niminaction/Chapter8/sfml -o /home/euant/.cache/nim/sfml_test_d/@msfml_test.nim.c.o /home/euant/.cache/nim/sfml_test_d/@msfml_test.nim.c'
```

SFML is installed with `doas pkg_add sfml`:

```
-rw-r--r--  1 root  bin  186952 Oct 11  2019 /usr/local/lib/libsfml-audio.so.1.0
-rw-r--r--  1 root  bin  474184 Oct 11  2019 /usr/local/lib/libsfml-graphics.so.1.0
-rw-r--r--  1 root  bin  188400 Oct 11  2019 /usr/local/lib/libsfml-network.so.1.0
-rw-r--r--  1 root  bin  107704 Oct 11  2019 /usr/local/lib/libsfml-system.so.1.0
-rw-r--r--  1 root  bin  209368 Oct 11  2019 /usr/local/lib/libsfml-window.so.1.0
```

**Comment by demotomohiro** [comment]
You need header file `SFML/Graphics.hpp` to compile that test file.
When you run a program that use SFML, you need these libsfml-*.so.1.0 files.
When you compile C/C++/Nim code that use SFML, you need both `*.so` files and header files (`*.h` or `*.hpp`).

Do you have header files of SFML?
I think they are installed in `/usr/include` or `/usr/local/include`.

**Comment by euantorano** [comment]
Yes, the header files are installed:

```
$ tree -L 1 /usr/local/include/SFML
/usr/local/include/SFML
|-- Audio
|-- Audio.hpp
|-- Config.hpp
|-- Graphics
|-- Graphics.hpp
|-- Main.hpp
|-- Network
|-- Network.hpp
|-- OpenGL.hpp
|-- System
|-- System.hpp
|-- Window
`-- Window.hpp

5 directories, 8 files
```

SFML is installed via `doas pkg_add sfml`.

This test is also disabled on FreeBSD for similar reasons, and is also disabled on Windows.

**Comment by lbartoletti** [comment]
Confirmed on FreeBSD. I can build it with:

`nim cpp -r --cincludes="/usr/local/include" --clibdir="/usr/local/lib" tests/niminaction/Chapter8/sfml/sfml_test.nim`

cpp is important, elsewhere there is multiple include errors

**Comment by j-bm** [comment]
A hint from a user who is new-to-Nim but well-experienced-with-OpenBSD:  

The clang compiler needs to be pointed at the local include directory:  -I /usr/local/include

This is almost mandatory for any compilation on OpenBSD building add-on software or with add-on software.  The FreeBSD choice listed above should work.

**Comment by euantorano** [comment]
It seems adding the two options to `config/nim.cfg` works:

```
cincludes = "/usr/local/include"
clibdir = "/usr/local/lib"
```

The test still fails on my machine as I don't have X configured, I'm going to get X configured locally then look at getting this to work on the CI.

**Comment by timotheecour** [comment]
> The test still fails on my machine as I don't have X configured

are you sure you need X? the test is `action: compile`, so won't run, just compile

> It seems adding the two options to config/nim.cfg works:

maybe instead something like:
```nim
# in config/config.nims
when defined(openbsd) and defined(nimSetDefaultUsrPaths):
  switch("cincludes", "/usr/local/include") # or maybe: --cincludes:"/usr/local/include", untested...
  switch("clibdir", "/usr/local/lib")
```

**Comment by euantorano** [comment]
> are you sure you need X? the test is action: compile, so won't run, just compile

I was running from the command line, where running fails with the following output:

```
Hint: used config file '/home/euant/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/euant/Nim/config/config.nims' [Conf]
Hint: used config file '/home/euant/Nim/tests/config.nims' [Conf]
Hint: 48428 LOC; 0.056 sec; 61.582MiB peakmem; Debug build; proj: sfml_test; out                                                                       : sfml_test [SuccessX]
Hint: /home/euant/Nim/tests/niminaction/Chapter8/sfml/sfml_test  [Exec]
Failed to open X11 display; make sure the DISPLAY environment variable is set co                                                                       rrectly
Traceback (most recent call last)
sfml_test.nim(10)        sfml_test
SIGABRT: Abnormal termination.
pthread_mutex_destroy on mutex with waiters!
pthread_mutex_destroy on mutex with waiters!
Error: execution of an external program failed: '/home/euant/Nim/tests/niminacti                                                                       on/Chapter8/sfml/sfml_test '
```

Simply compiling works fine though.

> maybe instead something like:

It seems we want these set for FreeBSD as well as OpenBSD. I'm not sure about NetBSD.

**Comment by timotheecour** [comment]
> Simply compiling works fine though.

well ideally the test would be enhanced to also run, not just compile, but that's future work (and would need customization per platform); eg saving the window content as png and making sure it matches some groundtruth


> It seems we want these set for FreeBSD as well as OpenBSD. I'm not sure about NetBSD.


might as well do it simply for `bsd` ; once CI works for netbsd, we'll know soon enough if it fails

**Comment by euantorano** [comment]
Yep, I'll make a PR after work tonight and see what happens.
