### ISSUE TITLE
Annoying warning: inherit from a more precise exception type like ValueError, IOError or OSError [InheritFromException]

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#14052]
This is not a bug.

### Example
```nim
type PbError* = object of Exception
type GenomeCoverageError* = object of PbError
type FieldTooLongError* = object of PbError
type TooFewFieldsError* = object of PbError
...
```

### Current Output
at compile time:
```
Warning: inherit from a more precise exception type like ValueError, IOError or OSError [InheritFromException]
```

### Possible Solution

I don't understand why this was added at all. It's intentional. I might want to trap _only_ the exceptions from the standard library. Besides, this just makes me scratch my head; the exceptions from my own library could be I/O errors, precondition violations, coding errors, etc.
 
### Additional Information

* It was working in version 1.0.0. Started with 1.2.0 for me.

**Comment by alaviss** [comment]
Looks like it doesn't even mention the split between `CatchableError` and `Defect`...

So Nim's exception hierarchy is now split into two types: `CatchableError` and `Defect`. You should inherit from them instead.

`CatchableError` are for errors that can be caught (ie. `OSError`, `ValueError`), and `Defect` are for programming errors (ie. `IndexError`, `DivByZero`, etc.), and with `--panic:on` (it's off by default), any `Defect` will crash the program instantly, allowing the compiler to do some additional optimization by not assuming that everything can throw.

I guess the message should also recommend inheriting from either `CatchableError` or `Defect`.

**Comment by pb-cdunn** [comment]
TIL! Yes, a change in the message would be perfect.
