### ISSUE TITLE
xmlparser removes significant white space

### ISSUE THREAD

**Issue by kemifl** [nim-lang/Nim#14056]
If the parseXml procedure is used to create an XmlNode object from the following XML/HTML:

`<p>one <em>two</em> three</p>`

and the XmlNode object is then immediately serialized again, the result is:

`<p>one <em>two</em>three</p>`

That is, the white space preceding "three" (which is clearly significant) is missing from the output version. It gets lost during parsing, not during serialization as far as I can see.

I haven't tested it, but I suspect that the following input:

`<p>one <em>two</em> <strong>three</strong> four</p>`

would be output as:

`<p>one <em>two</em><strong>three</strong>four</p>`

That is, the space between "two" and "three" would be lost as well as the space before "four".

**Comment by bung87** [comment]
https://play.nim-lang.org/#ix=2lQi fusion htmlparser solved this.

**Comment by kemifl** [comment]
I got back to this eventually ... Using htmlparser is a solution for (X)HTML content, but not for other "text document" XML formats such as Docbook or DITA, so it's not really a workaround for me.

I looked into it a bit deeper, and found a superficially simple solution. xmlparser configures the underlying parsexml parser to ignore white space (by not setting the reportWhitespace option). So modifying xmlparser to set the reportWhitespace option fixes my problem. 

I assume that if I submit a PR with this change, however, that it will be rejected since it breaks backwards compatibility - it breaks one of the tests in the Nim test suite. How about adding a "preserveWhiteSpace" (default false) parameter to all of htmlparser's parsing procs? Would that be better?

**Comment by Araq** [comment]
> How about adding a "preserveWhiteSpace" (default false) parameter to all of htmlparser's parsing procs? Would that be better?

I assume you mean "xmlparser's parsing procs". Yes, that would be better, depending on what you mean by "all of", only the constructor procs should be affected.

**Comment by kemifl** [comment]
Yes, I did mean xmlparser. OK, thanks for the quick reply, I will have a go at that then.
