### ISSUE TITLE
--gc:arc, copyMem, string not playing nice together

### ISSUE THREAD

**Issue by JorySchossau** [nim-lang/Nim#14078]
With arc enabled, the below snippet prints nothing to stdout, whereas it should print `hello`, as it does without the arc GC. Is this related to the new string implementation? (similar? #13137)

### Example
```nim
proc main =
  let str = "hello"
  var sptr = string.createU(str.len)
  copyMem(sptr, unsafeAddr str, str.len)
  echo sptr[]

when isMainModule:
  main()
```

### Additional Information

nim 1.2.0

**Comment by alaviss** [comment]
I'm pretty sure this is not even correct, even in old runtime. A `string` **is not** a pointer to the string buffer. So actually you're not copying the string data here, just the supporting structure (which contains the pointer to the buffer).

The fact that this worked on old runtime might just be pure luck.

**Comment by JorySchossau** [comment]
So you're saying it should be this? (`unsafeAddr str[0]` not `unsafeAddr str`) That makes sense.
Then nim complains I'm reading from `nil`. But I just initialized and copied data... didn't I?

```nim
proc main =
  let str = "hello"
  var sptr = string.createU(str.len)
  copyMem(sptr, unsafeAddr str[0], str.len)
  echo sptr[]

when isMainModule:
  main()
```

**Comment by JorySchossau** [comment]
Okay, I'll keep playing with it - there's something I don't understand about strings. Thanks!

**Comment by alaviss** [comment]
Here's the idiomatic way to copy a `string` data to another `string`:

```nim
proc main =
  let str = "hello"
  var another = str # Nim strings are value types, so this performs a copy.
  another.add "hi!"
  doAssert str != another

when isMainModule:
  main()
```

If you wanna access the internal buffer, then use `addr str[0]` or `cstring str`.

Hope this helps :)
