### ISSUE TITLE
codegen errors with cpp --gc:arc --exceptions:goto on clang++

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#14080]
It doesn't seem to work; I get codegen errors on Linux and OS X.  Should exceptions be forced to setjmp for clang++?

https://api.travis-ci.org/v3/job/678018940/log.txt

```
git hash: b36f843d00264bd43d0196430363747e18d0e0c2
```

**Comment by cooldome** [comment]
cpp has its own exceptions, its different from setjmp or goto? Any specific reason you want `goto` exceptions in cpp?

**Comment by disruptek** [comment]
I'm happy with an error message.

**Comment by Araq** [comment]
goto:exceptions have a different performance profile and should be supported for C++ too, IMO.

**Comment by Araq** [comment]
The code repository seems to be disruptek/bump

**Comment by disruptek** [comment]
I gave up testing the `cpp` backend and `exceptions:goto` with my balls because I have enough codegen errors without the extra compiler irritation.  Feel free to reopen with your own reproduction.
