### ISSUE TITLE
Koch does not run in Nim nightly 1.3.1

### ISSUE THREAD

**Issue by pkphilip** [nim-lang/Nim#14113]
I am getting the following error when I attempt to run koch in Nim version 1.3.1 binary release:

bash: ./koch: cannot execute binary file: Exec format error

### Expected Output
This ought to be running

### Possible Solution

* I got around the issue by downloading the source of Nim and then rebuilding from scratch.
* Noticed that Koch does have give this error in v1.2.0

**Comment by genotrance** [comment]
Few questions - how was the nightlies installed? Which specific version of nightlies - which day or hash? Lastly, what distro and version are you running?

**Comment by Araq** [comment]
No feedback, closing.
