### ISSUE TITLE
RVO not exception safe

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#14126]
### Example
```nim
type X = object
  a, b, c: string

proc f(): X =
  result.a = "a"
  result.b = "b"
  raise (ref ValueError)()

var x: X
x.a = "1"
x.b = "2"
x.c = "3"

try:
  x = f()
except:
  discard

echo x
doAssert x.c == "3", "shouldn't modify x if f raises"

```

### Current Output
```
(a: "a", b: "b", c: "")
```

### Expected Output
```
(a: "1", b: "2", c: "3")
```

```
[arnetheduck@tempus nim-beacon-chain]$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-04-21
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b4e9f8e814373fc38741736197d88475663ce758
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
tricky issue but I'm not sure this is a bug, ensuring x doesn't get mutated when the call raises would prevent important optimization opportunities.

* in C++, this wouldn't happen as RVO can't happen in assignment `x = f();`, only in copy construction `auto x = f();` eg see https://stackoverflow.com/questions/20250043/why-doesnt-rvo-happen-for-assignment-operator-c

* nim should be allowed to rewrite a call that returns an object-like type (object,array,tuple,string etc) as follows:

(pseudo-code, not actual code)
```nim
proc f(): A =
  nimZeroMem(result) # initialization of result
  op(result) # body

x = f()
```

rewritten into:

```nim
proc fRewrite(result: var A)=
  genericReset(result) # re-initialization of result (same as nimZeroMem depending on type)
  op(result) # body

fRewrite(x)
```

so that if `f` throws, `x` can be mutated in side `op`

* when sizeof(A) is small enough to fit into registers (say 1 or 2), then a copy would happen instead as it's more efficient, and the mutation on throw wouldn't happen, as an implementation detail

**Comment by arnetheduck** [comment]
#14390  causes significant regressions in stack usage due to RVO not being applied even in safe cases (no exceptions involved) - the proposed fix is too aggressive!

**Comment by timotheecour** [comment]
that's what I predicted in https://github.com/nim-lang/Nim/issues/14126#issuecomment-619827991 and https://github.com/nim-lang/Nim/pull/14390#issuecomment-630167152 ... 
> given that try/catch can happen very far from where exception is thrown (eg at application root, say in some main loop), it'd imply that every single x = fun() would have NRVO disabled. IMO that's potentially a performance killer. I'm honestly not convinced #14126 is a real problem to begin with, once you acknowledge existence of NRVO.

(even with heuristics like https://github.com/nim-lang/Nim/pull/14390#issuecomment-630248363 it can hurt)

@arnetheduck do you have a minimal example?

**Comment by arnetheduck** [comment]
Taking that back for the moment - there are regressions, but there are also exceptions involved in the example I was looking at - it was a "fresh" instance but the template instantiated it separately from RVO meaning the exception behaviour was observable in the case.

@timotheecour you're proposing to break with the most basic and fundamental correctness guarantees about function invocations in the name of a minor performance benefit that can easily be had by changing the return to a `var` parameter or improving analysis in the compiler.

**Comment by Araq** [comment]
The problem with ``x: var T`` is that it is a workaround that is a little lie, it's actually ``x: out T`` (except that we don't have ``out`` parameters in Nim). A workaround like this seems more harmful in the long run than even hacking an ``.enforceNrvo`` pragma into the language.

**Comment by arnetheduck** [comment]
yes - it's a lie/workaround indeed - but at least it's within expectations of how it should work - ie if you write to a `var` and then raise, the write doesn't get undone - that's obvious - if you return something however, conceptually those are separate instances and the compiler should maintain "as-if" guarantees.

`out` is interesting - I'd love to see an `out` where at the call site I have to say `out` as well, instead of the current `var` stuff which is invisible to the caller (unless they look it up which breaks flow when reading code) - but what should `out` do for exception safety? probably the same as `var` - ie no guarantees - but maybe not.

**Comment by Araq** [comment]
Offtopic but you can use ``template byvar(x: untyped): untyped = x`` and annotate it at the callsite. It's currently hard to enforce without a little compiler help but it's a start.
