### ISSUE TITLE
newHttpClient.getContent throws "400 Bad Request" on windows, if filename contains a questionmark

### ISSUE THREAD

**Issue by faulander** [nim-lang/Nim#14120]
newHttpClient().getContent() throws "400 Bad Request" on windows, if filename contains a questionmark.

### Example
```nim
var client = newHttpClient()
var content= client.getContent("https://trantor.is/download/WUZtEAQGlK24XICI/Coronavirus - Beginn einer Pandemie?: Fakten, Schutz und Vorsorge.epub")
```
### Current Output
```
C:\Users\xxx\scoop\apps\nim\current\lib\pure\httpclient.nim(1075) getContent
C:\Users\xxx\scoop\apps\nim\current\lib\pure\httpclient.nim(1053) responseContent
Error: unhandled exception: 400 Bad Request [HttpRequestError]
```
### Additional Information

* Working fine on linux

```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by simonkrauter** [comment]
When I enter the URL in Chromium, I get `502 Bad Gateway`.
This is a server-side error message, which the http client translates into an exception.
Looks ok to me.

To download the file, I guess you need to escape characters like space and question mark in the URL.

**Comment by faulander** [comment]
That's not true. It works on my machine when using chromium:
![image](https://user-images.githubusercontent.com/38588197/80385374-46ae5400-88a6-11ea-9899-c655e480acc9.png)
and it does NOT work, when using HttpClient.getContent.

**Comment by SolitudeSF** [comment]
because chromium implicitly encodes/decodes url

**Comment by ghost** [comment]
@faulander as @SolitudeSF said, you need to use https://nim-lang.org/docs/uri.html#encodeUrl%2Cstring on the file name (not the whole url)

**Comment by ghost** [comment]
Like so:
```nim
import uri, httpclient
var client = newHttpClient()

let encPart = encodeUrl("Coronavirus - Beginn einer Pandemie?: Fakten, Schutz und Vorsorge.epub")
var content = client.getContent("https://trantor.is/download/WUZtEAQGlK24XICI/" & encPart)
echo "true"
```

**Comment by faulander** [comment]
Of course you're right, works now as expected.
