### ISSUE TITLE
macOS: dsymutil should not be called on static libraries

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#14132]
https://travis-ci.org/github/status-im/nim-beacon-chain/jobs/679826271 :

```text
error: cannot parse the debug map for "/Users/travis/build/status-im/nim-beacon-chain/build/libnfuzz.a": No such file or directory

Error: execution of an external program failed: 'dsymutil /Users/travis/build/status-im/nim-beacon-chain/build/libnfuzz.a'

make: *** [libnfuzz.a] Error 1
```

Command executed by the nim-beacon-chain Make target:

`nim c -d:release --app:staticlib --noMain --nimcache:nimcache/libnfuzz_static -o:build/libnfuzz.a  --verbosity:0 -d:usePcreHeader --passL:"-lpcre" -d:release -d:stack_size=1000000 nfuzz/libnfuzz.nim`

(there's also a "--debugger:native" in a top-level config.nims)

```
$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-04-24
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b4e9f8e814373fc38741736197d88475663ce758
active boot switches: -d:release
```

Paging @timotheecour - this probably needs an extra check for the "staticlib" target: https://github.com/nim-lang/Nim/pull/12931/files#diff-d7d89c7eb9bee7025e7b6bdc0bcd657bR842

(I see "`if optGenStaticLib in conf.globalOptions`" is available there)

**Comment by timotheecour** [comment]
if you have a minimized example handy, I can make a quick PR, if not, it'll take me a bit longer

**Comment by timotheecour** [comment]
meh, i went ahead and sent it out: https://github.com/nim-lang/Nim/issues/14132 ; let me know if works for you, and if you have a minimzed example let me know, otherwise seems good enough; thanks for the ping!

**Comment by stefantalpalaru** [comment]
Just try to create a static lib on macOS with `nim c --app:staticlib --noMain --debugger:native foo.nim`.

BTW, I think something similar should be added to Nim's test suite.
