### ISSUE TITLE
Unable to detect stdin from pipe in non-interactive environment

### ISSUE THREAD

**Issue by danielecook** [nim-lang/Nim#14144]
I am unable to detect stdin from a pipe in a non-interactive environment.

### Example

```nim
import os
import terminal

if isatty(stdin) == false:
    # ./program foo
    # ./program foo | cat
    echo  "--> Input from terminal"
else:
    # echo bar | ./program
    # echo bar | ./program | cat
    echo "--> Input from a PIPE/FILE"
```
### Current Output (Locally); Interactive session

```shell
> ./program foo
--> Input from terminal

echo bar | ./program
--> Input from PIPE/FILE
```

### Current Output (Using Github Actions or Travis CI); non-interactive session

```shell
> ./program foo
--> Input from PIPE/FILE

echo bar | ./program
--> Input from PIPE/FILE
```

[Real Example](https://github.com/danielecook/seq-collection/runs/624597198?check_suite_focus=true#step:12:190)

### Expected Output both locally and on a testing VM

```shell
> ./program foo
--> Input from terminal

echo bar | ./program
--> Input from PIPE/FILE
```

**Comment by alaviss** [comment]
You're doing it wrong. `isatty()` checks if a file is an interactive terminal, not if it's from a pipe :)

On *nix, you can try using [`fstat`](https://linux.die.net/man/2/fstat) (it's in `posix.nim`), on `stdin`'s file descriptor to see if it's a pipe.

A more detailed solution depends on what you're trying to do.

**Comment by alaviss** [comment]
You can also refer to this stackoverflow answer to see why `isatty` is inadequete: https://stackoverflow.com/a/30520299

**Comment by danielecook** [comment]
Thanks for your suggestion!

I gave it a try, but it still seems to think input is coming from stdin.

Specifically:

See https://github.com/danielecook/seq-collection/runs/627497363?check_suite_focus=true#step:12:9

Here is the code I was trying:

```nim
proc is_stdin_pipe(): bool = 
    var st: posix.Stat
    assert posix.fstat(0, st) == 0
    echo " --> ISFIFO() == ", st.st_mode.S_ISFIFO()
    echo " --> ISREG() == ", st.st_mode.S_ISREG()
    echo " --> ISCHR == ", st.st_mode.S_ISCHR()
    return st.st_mode.S_ISFIFO()
```

Relevant: https://stackoverflow.com/a/1312948/2615190

**Comment by alaviss** [comment]
They probably launched the CI with a closed input pipe, which will tell applications that there won't be any input.

There's nothing much that you can do here.

**Comment by danielecook** [comment]
Ok thanks!

**Comment by Araq** [comment]
Beyond our control.
