### ISSUE TITLE
Operator precedence inconsistency

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#14169]
This compiles:

### Example
```nim
import rationals
echo not 0//1 > 1//1
```

because the expression in the last line is parsed as `(not 1) // 1` which is wrong according to the spec: https://nim-lang.github.io/Nim/manual.html#syntax-precedence

(and this doesn't:
```nim
import rationals
var a = 0//1
echo not a > 1//1
```
)

This in combination with the fact that `not` has the same precedence as `>` causes this weird issue where: `echo not 0//1 > 1//1` compiles but `var a = 0//1; echo not a > 1//1` does not.

This is not exclusive to the `//` operator from rationals either, but also affects the normal division operator:

```nim
echo not -1 / 1
```
outputs `0.0` because it is wrongly parsed as `(not -1) / 1`.
It should actually error out because `(-1 / 1)` is a `float` and `not` is not defined on `float`.

```
$ nim -v
Nim Compiler Version #devel
```

**Comment by metagn** [comment]
> wrongly parsed as (not -1) / 1.

That is actually the correct parsed expression.

> Unary operators always bind stronger than any binary operator

Same with `not 0//1 > 1//1`, its `((not 0) // 1) > (1 // 1)`

**Comment by Araq** [comment]
Yeah, as @hlaaftana says.
