### ISSUE TITLE
db_postgres' tryInsertID expects a field named ID

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#14167]
### Summary
Right now db_postgres' tryInsertID function expects the ID field to be named ID. This forces a naming standard in the schema when the developer should be able to choose the name of the ID field. A new feature to provide the ID field name would be better.

### Description
The solution is to pass the name of the ID field to tryInsertID. This allows more flexibility in naming the table's ID field.

### Alternatives
The alternative is to name (or rename) your ID field to ID.

### Additional Information
N/A

**Comment by Araq** [comment]
The problem here is that the ``db_`` modules all follow the same interface and PostGres lacks the essential API feature so we have to emulate it via SQL string hacking.

**Comment by jfilby** [comment]
Are you saying you don't want to add an extra parameter to db_postgres' tryInsertId function to keep the parameters standard across different DB modules? If so you could add a parameter called options which is of of a type of a class which has a field for insertIdName that is only used by the db_postgres module, even if available across all modules.

**Comment by Araq** [comment]
I'm saying if you add this feature introduce a new proc that is Postgres specific and document it well.
