### ISSUE TITLE
Compiler Segfaults with default generic proc 

### ISSUE THREAD

**Issue by hbwales** [nim-lang/Nim#14164]
Compiler Segfaults with the below

### Example
```nim
import sugar
proc f[T](a: proc(x: string): T = x => T(x)) = discard
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
(no segfault)
```

### Possible Solution

* ?

### Additional Information

```
nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by ghost** [comment]
Compiles fine on devel unless I add a line
```
f[int]()
```
with that line it shows an error:

`Error: A nested proc can have generic parameters only when it is used as an operand to another routine and the types of the generic paramers can be inferred from the expected signature.`

**Comment by ringabout** [comment]
no segfault on the devel branch
