### ISSUE TITLE
Docs shouldn't collapse pragmas inside runnableExamples/code blocks

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#14174]
### Example
```nim
template byaddr*(lhs, typ, ex) =
  ## Allows a syntax for lvalue reference, exact analog to
  ## `auto& a = ex;` in C++
  runnableExamples:
    var s = @[10,11,12]
    var a {.byaddr.} = s[0]
    a+=100
    doAssert s == @[110,11,12]
    doAssert a is int
    var b {.byaddr.}: int = s[0]
    doAssert a.addr == b.addr
```

### Current Output
![image](https://user-images.githubusercontent.com/10591326/80737272-f0e2e180-8b1b-11ea-9f7d-39a762a1904d.png)

### Expected Output
![image](https://user-images.githubusercontent.com/10591326/80737287-f8a28600-8b1b-11ea-8036-38ce4f8bc5cd.png)

### Additional Information

* This is currently in 1.2 docs, see https://nim-lang.org/docs/decls.html

**Comment by timotheecour** [comment]
auto-collapsed pragmas (at least as currently implemented) is a misfeature IMO. I keep clicking on `uncollapse` in docs so it ends up wasting more time that it saves in "cosmetics".
Either we disable the collapsing, or we refine the blacklist to only collapse a very short list, eg:
* `raises: []`
* `tags: []`
and maybe a few more, but that's it
