### ISSUE TITLE
localPassC pragma should come *after* other flags

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#14194]
I love the new [localPassC pragma](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-localpassc-pragma), but unfortunately it does not actually override anything.

### Example
```nim
{.localpassc: "-O0".}
```

### Current Output
```
gcc -c  -w -pthread  -O0 -O3 -fno-strict-aliasing -fno-ident  -I/mnt/software/n/nim/1.2.0/lib -I/localdisk/scratch/cdunn/repo/falconc/src -o /home/UNIXHOME/cdunn/.cache/nim/falconc_r/@mfalconc.nim.c.o /home/UNIXHOME/cdunn/.cache/nim/falconc_r/@mfalconc.nim.c
```

### Expected Output
```
... -O3 -O0 ...
```

### Possible Solution

* I think it would be safe to append the local cflags instead of prepend.

### Additional Information

* New in version 1.2 (I think).
* I need this in order to speed up **cligen**, which generates a lot of boilerplate for delegating from the command-line to multiple functions in a single executable.

```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
```

**Comment by pb-cdunn** [comment]
This is a pretty simple change, right?

**Comment by Araq** [comment]
Maybe.

**Comment by timotheecour** [comment]
the command line should be able to override this, see also https://github.com/nim-lang/Nim/pull/13798

> --passc:-std=c++17 (or similar flags) are now honored instead of silently ignored, by putting --passc options after instead of before the default

**Comment by pb-cdunn** [comment]
Yes, it does make sense for `--passc` on the command-line to override this. But I still need this.

What's the hold-up? I really, really, really need this. Compile-time of the top `.c` file using **cligen** has become abysmal.

**Comment by pb-cdunn** [comment]
Works great!
