### ISSUE TITLE
Use -d:nimEmulateOverflowChecks by default?

### ISSUE THREAD

**Issue by lh3** [nim-lang/Nim#14209]
### Summary

Since 1.2.0, nim starts to require the `__builtin_saddll_overflow` compiler builtin by default. I believe this builtin was added to gcc in 5.x. Unfortunately, CentOS/RHEL 6/7, which is widely used in academia due to their stability, comes with gcc-4.8.5 that doesn't support this builtin. The requirement of this builtin means we can't build programs with the default `nim c` on CentOS/RHEL 6/7. This is inconvenient especially given that `-d:nimEmulateOverflowChecks` is long to type and is not exposed to command line help.

How much does `__builtin_saddll_overflow` help performance? If the improvement is minor, I guess users would prefer to disable it by default for portability. Thank you.

EDIT: perhaps the better solution is to test gcc version with macros.

**Comment by Araq** [comment]
> EDIT: perhaps the better solution is to test gcc version with macros.

I'm trying to do that, yes.
