### ISSUE TITLE
Returning procedures with different noSideEffect pragmas

### ISSUE THREAD

**Issue by adelq** [nim-lang/Nim#14216]
I am trying to write a procedure that returns different procedures conditionally, and one variant of the procedure returned happens to have no side effects and the other does not. This is unexpected behavior since both returned procedure variants adhere to the procedure signature (`(int) -> void`) but because one of them gets annotated with the `{.noSideEffects.}` pragma, the other variant is rejected as well. The following code should reproduce the error:

### Example
```nim
import sugar

proc makeAdder(a: int): (int) -> void =
  proc discard_adder(x: int) {.closure.} =
    discard a + x

  proc echo_adder(x: int) {.closure.} =
    echo("printing from adder")

  if a > 0:
    discard_adder
  else:
    echo_adder

let newAdder = makeAdder(0)
newAdder(5)
```

### Current Output
```
Error: type mismatch: got <proc (x: int){.closure, gcsafe, locks: 0.}> but expected 'proc (x: int){.closure, noSideEffect, gcsafe, locks: 0.}'
```

### Expected Output
```
printing from adder
```

### Possible Solution

* Adding a pragma that is the inverse of the `{.noSideEffects.}` pragma such that a function can be marked as potentially having side effects.
* Using the loosest annotation rather than the strictest annotation for the `{.noSideEffects.}` pragma when determining procedure return pragmas.

### Additional Information

```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by cooldome** [comment]
This works:
```nim
import sugar

proc makeAdder(a: int): (int) -> void =
  proc discard_adder(x: int) {.closure.} =
    discard a + x

  proc echo_adder(x: int) {.closure.} =
    echo("printing from adder")

  if a > 0:
    result = discard_adder
  else:
    result = echo_adder

let newAdder = makeAdder(0)
newAdder(5)
```

The issue is that `  if a > 0: x else: y` needs to return one type. Nim struggles a bit.

**Comment by adelq** [comment]
Thanks, that worked perfectly.

**Comment by Clyybber** [comment]
The original snippet should still work though :)

**Comment by adelq** [comment]
I think this is actually the same bug as #12642, because re-ordering the branches of the if statement makes it compile correctly. This bug has been present since v0.15.0 and is currently present in v1.2.0.
