### ISSUE TITLE
Discarding output with nested for/if statements

### ISSUE THREAD

**Issue by adelq** [nim-lang/Nim#14227]
The collect macro does not seem to like nested `for` and `if` statements when they are interspersed in a certain order. The examples below should illustrate the issue:

### Example
```nim
import sugar

let y = @[@[1, 2], @[2, 4, 6]]
let x = collect(newSeq):
  for i in y:
    if i.len > 2:
      for j in i:
        j
echo(x)
```

### Current Output
```
Error: expression 'j' is of type 'int' and has to be discarded
```

### Expected Output
```
@[2, 4, 6]
```

### Reordered example works

However, if we switch the order of the `if` and second `for`, it works as expected:

```nim
import sugar

let y = @[@[1, 2], @[2, 4, 6]]
let x = collect(newSeq):
  for i in y:
    for j in i:
      if i.len > 2:
        j
echo(x)
```

### Current Output
```
@[2, 4, 6]
```
This is not ideal however because I would like to iterate only on items that match a conditional.

### Additional Information

This bug is similar to #12874, but the issue there was more related to branching than the order of control flow, and I tested it on my install of Nim 1.2.0 and it works, so it was fixed.

```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by ringabout** [comment]
It works since Nim v1.4.0.
