### ISSUE TITLE
[ARC] Code with a finaliser and object initialisation doesn't compile

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14226]
That code compiles with the default GC but not with `--gc:arc`, found in https://github.com/brentp/hts-nim 

### Example
```nim
type
  VCF* = ref object of RootObj
    fname: string
  
  Variant* = ref object
    p: pointer
    vcf*: VCF
    own: bool

  INFO* = ref object
    v: Variant
    i: int32

proc info*(v: Variant): INFO =
  result = INFO(i: 0, v: v)

proc destroy_variant(v: Variant) =
  discard

proc from_string*(v: var Variant, s: var string) =
  if v == nil:
    new(v, destroy_variant)
    v.own = true
```

### Current Output
```
/home/dian/Projects/data/ff.nim(22, 8) Error: cannot bind another '=destroy' to: Variant:ObjectType; previous declaration was constructed here implicitly: /home/dian/Projects/data/ff.nim(15, 16)
```

```
$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-05-04
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 603010f8c9d9655bb0fa3f91dc0bd1b76d3a0bd3
active boot switches: -d:release
```

**Comment by ghost** [comment]
https://gist.github.com/Yardanico/5a9f7e9842101443ebf662c58340f406#gistcomment-3289689

**Comment by brentp** [comment]
this still doesn't work (and this is from hts-nim). how should i re-order the code as indicated in the gist?
and/or why was this closed?

**Comment by brentp** [comment]
I found this: https://nim-lang.org/docs/system.html#new%2Cref.T%2Cproc%28ref.T%29 :
> Note: The finalizer refers to the type T, not to the object! This means that for each object of type T the finalizer will be called!

But I don't see how to adjust the code as a result of that.

**Comment by brentp** [comment]
bump

**Comment by Araq** [comment]
This compiles for me:

```nim


type
  VCF* = ref object of RootObj
    fname: string

  Variant* = ref object
    p: pointer
    vcf*: VCF
    own: bool

  INFO* = ref object
    v: Variant
    i: int32

proc destroy_variant(v: Variant) =
  discard

proc from_string*(v: var Variant, s: var string) =
  if v == nil:
    new(v, destroy_variant)
    v.own = true

proc info*(v: Variant): INFO =
  result = INFO(i: 0, v: v)

```

**Comment by brentp** [comment]
so is this a GC bug that will be fixed or does the new GC dictate that I re-order code in a certain (unknown-to-me) order?

**Comment by Araq** [comment]
You need to reorder your code in a certain, well specified order. See https://nim-lang.org/docs/destructors.html#hook-generation for details. I'll also document it in my upcoming ORC/ARC article. This is now the only remaining incompatibility with the old GCs btw. (Aside from certain ``cast`` operations.)

**Comment by brentp** [comment]
ok. thank you for the clarification.
