### ISSUE TITLE
Difficult to read search results of nim standard library documentation in dark mode

### ISSUE THREAD

**Issue by nothratal** [nim-lang/Nim#14232]
The search results of the standard library documentation are very difficult to read in dark mode due to color scheme. More detailed information if not self-explanatory.

Steps to reproduce:

1. open website: https://nim-lang.org/docs/lib.html
2. activate Dark Mode by clicking on the option switch in the left upper corner
3. enter "encoding" in the search box

![image](https://user-images.githubusercontent.com/44500242/81068641-fd32ba00-8ee0-11ea-8a60-22b3ba2b9908.png)

**Comment by Clyybber** [comment]
Fixed in the bleeding edge docs: https://nim-lang.github.io/Nim/ :)

For the stable docs it will be fixed with the next release
