### ISSUE TITLE
Crash in compiler when using system.any by accident.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#14255]
Reproduce the error with:

```nim
var a = newSeq[bool](1000)
if any(a):
  echo "ok?"
```

Get compiler crash:

```
Error: internal error: getTypeDescAux(tyFromExpr)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

I think i am using system.any which is a "meta type" and not sequtils.any. Even though I am using sequtils.any wrong. I expect to get an error some thing like: "system.any can't be created from an seq". Or even some thing less fancy like "invalid type" at line 2.

**Comment by ringabout** [comment]
More cases, `auto` is same as `any`:

```nim
block:
  var a = newSeq[bool](1000)
  if false:
    echo "ok?"
  elif any(a):
    echo "false"

block:
  var a = newSeq[bool](1000)
  while any(a):
    echo "ok?"

block:
  when any(a):
    echo "when"
```
It also causes problems in VM:
```nim
static:
  ## unhandled exception: 'intVal' is not accessible using discriminant 'kind' of type 'TFullReg' 
  let a = newSeq[bool](1000)
  if any(a):
    echo "ok?"
```
It works in JS backend.

**Comment by ringabout** [comment]
Could it be fixed before `ccg`?

It seems hard to fix it in sem phase I guess?
```nim
proc hello(a: int): any =
  true

if hello(12):
  echo "ok?"
```
