### ISSUE TITLE
Cross-module refusal of method call syntax for type conversion in generic

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#14254]
```nim
# importme.nim
type Foo = int32
proc baz*[T](y :int) =
  echo y.Foo
```
```nim
# main.nim
import importme
baz[float](1'i8)
```
`baz[float](1'i8)` can be called in `importme` just fine, but not in `main`, giving the error:
```
Error: undeclared field: 'Foo' for type system.int [declared in c:\dev\fork\Nim\lib\system\basic_types.nim(2, 3)] 
```
Using the normal call syntax allows the code to compile fine, however:
```nim
proc baz*[T](y :int) =
  echo Foo(y)
```

**Comment by awr1** [comment]
This issue is also generic-specific, removing the generic param permits compilation.

**Comment by timotheecour** [comment]
pretty related: https://github.com/nim-lang/Nim/issues/14819
