### ISSUE TITLE
TableRef example appears to be incorrect?

### ISSUE THREAD

**Issue by mickgardner** [nim-lang/Nim#14268]
https://github.com/nim-lang/Nim/blob/75abd4dc68f8cef3e8e02b7eb23ea43b1823d864/lib/pure/collections/tables.nim#L50

The example in the documentation that shows how to create a new table seems to the exactly the same as the new TableRef example. I'm no expert but that doesn't seem correct.

**Comment by ghost** [comment]
What do you exactly mean?
`toTable` is for the `Table` type, `newTable` is for the `TableRef` type

**Comment by mickgardner** [comment]
Gah! My mistake.
