### ISSUE TITLE
Compiletime vars cannot be declared inside procs

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14274]
### Example
```nim
proc myProc =
  var myVar {.compileTime.} = 123
```

### Current Output
```
Cannot evaluate at compile time error
```

### Additional Information
Nim 1.2.0

**Comment by ghost** [comment]
Should this be allowed though? I think compileTime only works for symbols (procs, vars) at top-level https://nim-lang.org/docs/manual.html#pragmas-compiletime-pragma, it doesn't make sense to have compileTime in a proc really since you can just have const or even
```nim
const doSomething = block:
   # do some work
   val = computeData()
   val
```

**Comment by dawkot** [comment]
You get the same error if you try to return a var inside a block like this.
```nim
proc p =
  const c = block:
    var v = 123 # Error: cannot evaluate at compile time: v
    v
```

**Comment by ringabout** [comment]
In devel, you could use:

```nim
proc myProc =
  var myVar {.global, compileTime.} = 123
```

**Comment by ringabout** [comment]
First problem
According to #8733
> This is not supposed to work.

Second problem is duplicated:
#12172
