### ISSUE TITLE
`nimble doc` fails with exception "Can't obtain a value from a `none` [UnpackError]"

### ISSUE THREAD

**Issue by snej** [nim-lang/Nim#14281]
I'm developing a Nimble package and finished adding a bunch of doc-comments.
When I run `nimble doc`, it immediately fails with what looks like an internal error.

### Example
At a shell prompt, in my package's root directory, I enter `nimble doc`.

### Current Output
```
options.nim(185)         get
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]
```

### Expected Output
Expected the documentation to be compiled.

### Extra Info

My `.nimble` file just looks like:

```
# Package
version       = "0.1.0"
author        = "...."
description   = "...."
license       = "Apache-2.0"
srcDir        = "src"

# Dependencies

requires "nim >= 1.2.0"
```

### Nim Version

```
$ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-04-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise

$ nimble -v
nimble v0.11.0 compiled at 2020-04-04 07:59:18
git hash: couldn't determine git hash
```

**Comment by snej** [comment]
The error output includes `options.nim` -- I don't have a source file of that name. I do have one source file that imports the `options` module, though.

**Comment by alaviss** [comment]
> ### Current Output

Is this the full output? If yes then this seems to be a nimble bug rather than a nim bug.

**Comment by snej** [comment]
Yes, that's all she wrote :/
If I run `nim doc path/to/file.nim` for each source file individually, it works.

**Comment by alaviss** [comment]
This is a nimble bug then.

@narimiran please move the bug to nim-lang/nimble.

/cc @genotrance @dom96

**Comment by narimiran** [comment]
> @narimiran please move the bug to nim-lang/nimble.

I don't have admin rights for that repo, I cannot move it there.

**Comment by genotrance** [comment]
This isn't Nim related.
