### ISSUE TITLE
generic destructor gives: `Error: unresolved generic parameter`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14315]
generic destructor gives: `Error: unresolved generic parameter` when object has no field from which you could infer the type of object.
This is a problem in particular (but not limited to) importc generic types for which it may be undesirable to add concrete fields (eg these could be ABI dependent)

### Example
```nim
when true: # D20200511T212358 gitissue
  type Vector*[T] = object
    x1: int
    # x2: T # uncomment will remove error

  # proc `=destroy`*(x: var Vector[int]) = discard # this will remove error
  proc `=destroy`*[T](x: var Vector[T]) = discard
  var a: Vector[int] # Error: unresolved generic parameter
```

### Current Output
```
Error: unresolved generic parameter
```

### Expected Output
```
works
```

### Additional Information
* I was trying to fix https://github.com/kaushalmodi/std_vector/issues/4 by adding a `=destroy` proc but ran into this /cc @kaushalmodi 
* devel a39123c93c9d2976300f1b8eba09d40b16f1c46c

/cc @cooldome since you seem quite familiar with this area :-)

**Comment by mratsim** [comment]
Also blocked by this to implement move-only generic types that are typed shims over a type-erased raw backend.

```Nim
type
  Flowvar[T] = object

proc `=`[T](dst: var Flowvar[T], src: Flowvar[T]) {.error: "copying not allowed".}

proc newFlowvar(T: typedesc): Flowvar[T] =
  discard

let x = newFlowvar(int)
```

I.e. if we switch Nim channels to destructors that will be a blocker.
