### ISSUE TITLE
Some default arg values crash the compiler

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14311]
### Example
```nim
import sequtils

type MyEnum = enum a, b

proc myProc[T](arg = toSeq(T)) =
  discard

myProc[MyEnum]()
```

### Current Output (at compiletime)
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Additional Information
Nim 1.2.0

**Comment by timotheecour** [comment]
devel:
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10736.nim(11, 15) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim_devel/lib/system.nim(1508, 11) Error: cannot instantiate: 'U: Ordinal'
  proc len*[U: Ordinal; V: Ordinal](x: HSlice[U, V]): int {.noSideEffect, inline.} =
            ^
```

and indeed, we can't instantiate; the program seems incorrect (although error message could be improved but doesn't sound easy to do so)

should we close using "works_in_devel" tag ? (and if someone wants to they can backport whatever fixed this but it's lower priority)

**Comment by Araq** [comment]
> "works_in_devel" tag?

All issues are closed under the constraint "works in devel". I think it's wise to keep it this way, there is already the big problem of how to select which bugs to work on.
