### ISSUE TITLE
Crash with gc:arc

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#14325]
This causes a double free, since the backend introduces too many temporaries.
Extracted from https://github.com/nim-lang/Nim/issues/13780#issuecomment-606024178

### Example
```nim
type
  TPassContext = object of RootObj
  PPassContext = ref TPassContext

  PCtx = ref object of TPassContext
    a: int

  ModuleGraph = object
    vm: RootRef

proc main() =
  var g = ModuleGraph(vm: new(Pctx))
  PPassContext(PCtx(g.vm)) = nil #This compiles, but crashes at runtime with gc:arc

main()
```

### Current Output
```
Traceback (most recent call last)
/home/clyybber/projects/tests/t13780.nim(16) t13780
/home/clyybber/projects/tests/t13780.nim(12) main
/home/clyybber/builds/nim/lib/system/refs_v2.nim(140) nimDestroyAndDispose
/home/clyybber/builds/nim/lib/system/refs_v2.nim(125) nimRawDispose
/home/clyybber/builds/nim/lib/system/alloc.nim(971) dealloc
/home/clyybber/builds/nim/lib/system/alloc.nim(870) rawDealloc
/home/clyybber/builds/nim/lib/system/avltree.nim(74) del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

```
$ nim -v
Nim Compiler Version #devel
```

**Comment by ghost** [comment]
Still crashes when compiled without stacktrace, runs forever with it

**Comment by cooldome** [comment]
@Clyybber  @Araq 
Gents, we need to make progress on this one

**Comment by Araq** [comment]
Depends a bit on whether other code beyond bootstrapping is affected. I did look into this months ago -- without any progress. (For bootstrapping I'm not concerned as I plan many big refactorings for IC support anyway, that will change how many allocations the Nim compiler performs.)
