### ISSUE TITLE
`macros.error` can't be used as an expression

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14329]
### Example
```nim
import macros

macro myMacro(n) =
  let x = if true: newLit"test" else: error "error", n
```

### Current Output
```
expression 'newLit"test"' is of type 'NimNode' and has to be discarded
```

### Expected Output
Compiling, just like it would with `raiseAssert` in place of `error`

### Additional Information

* Nim 1.2.0

**Comment by alaviss** [comment]
This is because `error` don't have `{.noreturn.}`. Should be an easy fix I think, though I'm not sure how `error()` interacts with `nim check`. If it keeps going after `error()` then maybe we can "fix" this by making `error()` return a discardable `NimNode(nil)`

The current walkaround would be:

```nim
import macros

macro myMacro(n) =
  let x =
    if true:
      newLit"test"
    else:
      error "error", n
      nil
```

**Comment by treeform** [comment]
I run into this as well. Using `err` as a work around:

```
proc err(msg: string, n: NimNode) {.noreturn.} =
  error(msg, n)
```

error still does not have {.noreturn.}, not sure why this issue was closed.

**Comment by Araq** [comment]
I don't understand, the issue is open.

**Comment by treeform** [comment]
Sorry my mistake, I though the close was for this issue, but its the close for the duplicate. I am just dumb.
