### ISSUE TITLE
nre throws internal error (only) when used with the js backend

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14338]
I have a fairly simple nim program compiled with **Nim 1.2.0** . Neither `nim js -r "[...]/code.nim"` nor my `nimble build` work - they're throwing the same error, once I use the js backend instead of the c or cpp one: 
```
/home/me/.choosenim/toolchains/nim-1.2.0/lib/impure/nre.nim(255, 25) Error: internal error: expr(nkBracketExpr, tyUncheckedArray)

No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp js <file>
```

I didn't manage to install koch unfortunately and I don't think that this will help a lot since this error itself is not very descriptive. This seems to be the problematic line in nre.nim by the way:
```
let num = (int(table[pos]) shl 8) or int(table[pos + 1]) - 1
```

and I'm just using such nre functions:
```
input = input.replace(re"(?m)\#.*$", "")        # remove comments
```

I hope you will be able to fix this error. Thank you in advance!

**Comment by ghost** [comment]
nre and re are both based on PCRE which obviously can't be used in the JS backend

**Comment by kaushalmodi** [comment]
@Yardanico May be those libraries need to add something like this at the very top?

```nim
when not defined(c) and not defined(cpp):
  {.error: "This library needs to be compiled with the c or cpp backend, and depends on PCRE.".}
```

@famecastle Try using the `regex` module, after installing using `nimble install regex`. That regex library does not depend on PCRE.
