### ISSUE TITLE
nimvm: CritBitTree does not work: "limited VM support for 'addr'"

### ISSUE THREAD

**Issue by akavel** [nim-lang/Nim#14339]
The CritBitTree type does not work at compile time.

### Example
```nim
import critbits
static:
  var strings: CritBitTree[int]
  discard strings.containsOrIncl("foo", 1)
  echo strings["foo"]
```

### Current Output
```
stack trace: (most recent call last)
C:\prog\dali\q_ct01.nim(5, 15) q_ct01
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) []
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) Error: limited VM support for 'addr'
```

### Expected Output
```
1
```

### Additional Information

* I am [using CritBitTree][dali] in my project [dali][], which allows emitting Android .dex files from Nim. I would like to be able to emit .dex files at compile time, when writing Android apps in Nim. Currently, I have to instead:
  - generate strings with Nim code and emit them to a helper file,
  - [compile and run this auxillary file separately](https://github.com/akavel/hellomello/blob/531e869dd7c04ba6622a23a56c70dada6b0cd49d/hellomello.nimble#L24-L25) to generate the final .dex file.

[dali]: https://github.com/akavel/dali/blob/911fea3b41ca4f9bc8eb2013f7456dff38a65af0/src/dali/dex.nim#L60

*Nim version:*
```
C:\prog\dali>nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by ringabout** [comment]
@akavel 
Workaround:

```nim
import critbits

proc getKey*[T](c: CritBitTree[T], key: string): T {.inline.} =
  c[key]

static:
  var strings: CritBitTree[int]
  discard strings.containsOrIncl("foo", 1)
  echo strings.getKey("foo")
```

https://play.nim-lang.org/#ix=2rsd

**Comment by timotheecour** [comment]
reduced without stdlib:
```nim
when true:
  type
    Node = ref object
      val: int
  proc bar(c: Node): var int =
    var n = c # Error: limited VM support for 'addr'
    c.val
  proc main =
    var a = Node()
    discard a.bar()
  static: main()
  main()
```

**Comment by akavel** [comment]
@timotheecour ❤️ thanks for working on this!
