### ISSUE TITLE
when assign literal int to float in tuple, it can't convert internally.

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#14344]
when assign literal int to float in tuple, it can't convert internally.

### Example
```nim
var x:(string,float);x = ("hello",10)
```

### Current Output
```
Error: type mismatch: got <tuple of (string, int)> but expected 'tuple of (string, float)'
```

### Expected Output
nothing

**Comment by Araq** [comment]
No bug here, compare to 

```nim

let y = ("hello", 10)
var x: (string, float); x = y
```

However, there is https://github.com/nim-lang/RFCs/issues/149 for better type inference for constructors.

**Comment by bung87** [comment]
current solution is not I expected, I dont want insert new one before it and then assign it. not fit my transpiler tool.

**Comment by Araq** [comment]
So write a real compiler and not a "transpiler".

**Comment by bung87** [comment]
:(

**Comment by Clyybber** [comment]
Or generate `var x:(string,float);x = ("hello",10'f64)` or `var x:(string,float);x = ("hello",10.float)` instead

**Comment by bung87** [comment]
ok, I could add `.float` sound fit the case well.
