### ISSUE TITLE
edge doc ImportJs pragma section refers to importc pragma should be importcpp pragma

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#14366]
ImportJs pragma
Similar to the **importcpp pragma for C++**, the importjs pragma can be used to import Javascript methods or symbols in general. The generated code then uses the Javascript method calling syntax: obj.method(arg).

https://nim-lang.github.io/Nim/manual.html#implementation-specific-pragmas-importjs-pragma
### Current Output
 link to https://nim-lang.github.io/Nim/manual.html#foreign-function-interface-importc-pragma

### Expected Output
link to https://nim-lang.github.io/Nim/manual.html#implementation-specific-pragmas-importcpp-pragma

**Comment by timotheecour** [comment]
@bung87 yes you are right; but could you please send a PR instead for simple things like this? it would've probably taken you just as long

**Comment by bung87** [comment]
@timotheecour  ok,see https://github.com/nim-lang/Nim/pull/14367

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/14367
