### ISSUE TITLE
import strformat produces file not found error because clearlinux does not deploy starter nim.cfg

### ISSUE THREAD

**Issue by rbucker** [nim-lang/Nim#14374]
I have the smallest `nim` program.

```
import strformat
let msg = "hello"
doAssert &"{msg}\n" == "hello\n"
```

When I try to build this app...

```
$ nim c -r d.nim 
```

I get the error

```
/d.nim(1, 8) Error: cannot open file: strformat
```

(I also get similar error messages when I the numble commands. The challenge there is that nimble has it's own nim scripts that also depends on the standard library.)

So in order to get my compile to work, I created a `nim.cfg` in the current folder. Granted there are plenty of places where I can create that file... 

I started with:

```
verbosity:1                                                                                                                                                                                  
PATH:"$lib/pure" 
```

(`$lib` will be substituted with the correct folder path `/usr/lib/nim`)

When I compile... I see that I'm missing another standard file `macros`. This continues until my `nim.cfg` files looks like:

```
verbosity:1                                                                                                                                                                                  
PATH:"$lib/pure"                                                                                                                                                                            
PATH:"$lib/core"                                                                                                                                                                            
PATH:"$lib/posix"                                                                                                                                                                           
PATH:"$lib/pure/collections" 
```

On the one hand it makes perfect sense to force the developer to manually choose which and where the packages are... but on the other hand since `nimble` is included in the dist you'd expect that the path and the standard libs would be included. On the other hand... this `nim` installation was pre-packaged in Intel's ClearLinux not to be confused with ClearOS and so they could have made a mistake.

Some debug: I performed a `nim dump`.

```
...
-- end of list --
/usr/lib/nim
...

It happens that I have an OpenBSD installation and so I performed the dump

```
...
-- end of list --
/usr/local/lib/nim/pure
/usr/local/lib/nim/core
/usr/local/lib/nim/arch
/usr/local/lib/nim/pure/unidecode
/usr/local/lib/nim/js
/usr/local/lib/nim/posix
/usr/local/lib/nim/windows
/usr/local/lib/nim/wrappers/linenoise
/usr/local/lib/nim/wrappers
/usr/local/lib/nim/impure
/usr/local/lib/nim/pure/concurrency
/usr/local/lib/nim/pure/collections
/usr/local/lib/nim/deprecated/pure
/usr/local/lib/nim/deprecated/core
/usr/local/lib/nim
```

and I happen to see that there is a comprehensive `nim.cfg` on th openbsd installation that is not present in the clearlinux....

**Comment by ghost** [comment]
IMO that's not a Nim issue, you should instead open an issue in the bug tracker for Clear Linux.

**Comment by ghost** [comment]
You can see the proper full nim.cfg here - https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg (and as you can see it's a part of repository)

**Comment by rbucker** [comment]
I see that... I have been reading all of the DOCs for 2 days and see no mention of that in the installation. I did not read the installer code. But we can close this. THANKS!!
