### ISSUE TITLE
Broken example on hot code reloading

### ISSUE THREAD

**Issue by frankschmitt** [nim-lang/Nim#14380]
When trying to compile the example from https://nim-lang.org/docs/hcr.html, you get an error message (using Nim 1.2.0):

`
logic.nim(51, 17) Error: type expected, but got: Rect(x: posX - 25, y: posY - 25, w: 50, h: 50)
`
which is caused by this line in the source code:
`var rect: Rect(x: posX - 25, y: posY - 25, w: 50, h: 50)`

The fix is quite simple - just replace `rect:` with `rect = `

`var rect = Rect(x: posX - 25, y: posY - 25, w: 50, h: 50)`

(PR will follow shortly)

**Comment by dom96** [comment]
Yeah, these docs are in the Nim repo. Transferred this issue there.
