### ISSUE TITLE
[ARC] destructive move destroys the object too early

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14396]
This code works with the default GC, but with ARC it crashes with a SIGSEGV because ``spinny`` is getting sinked into ``createThread`` but it's being used after that.
### Example
```nim
# Compile with --threads:on
type
  Spinny = ref object
    t: Thread[Spinny]
    text: string

proc newSpinny*(): Spinny =
  Spinny(text: "hello")

proc spinnyLoop(spinny: Spinny) {.thread.} =
  echo spinny.text
# Adding {.nosinks.} either to this proc or to createThread solves the issue
proc start*(spinny: Spinny) =
  createThread(spinny.t, spinnyLoop, spinny)

proc stop*(spinny: Spinny) =
  joinThread(spinny.t)

var spinner1 = newSpinny()
spinner1.start()
spinner1.stop()
```

### Current Output
```
Traceback (most recent call last)
/home/dian/Projects/spinny/spinny.nim(19) spinny
/home/dian/Projects/spinny/spinny.nim(13) start
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
hello
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-17
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 40ac19572a86b5bfa7b57cf0482ae3a30432176a
active boot switches: -d:release -d:danger
```

**Comment by ghost** [comment]
Also - if you declare the thread on the global level like
```
var t: Thread[Spinny]
```
it works.

**Comment by cooldome** [comment]
Simplified example that demonstrates the problem and is not thread related:
```nim
# Compile with --threads:on
type
  Spinny = ref object
    t: ref int
    text: string

proc newSpinny*(): Spinny =
  Spinny(t: new(int), text: "hello")

proc spinnyLoop(x: ref int, spinny: sink Spinny) =
  echo x[]

proc start*(spinny: sink Spinny) =
  spinnyLoop(spinny.t, spinny)

var spinner1 = newSpinny()
spinner1.start()
```
Expected output is zero, but you get either crash or random number. Issue caused by destructive move of spinny variable inside start proc

**Comment by ghost** [comment]
@cooldome is it related to https://github.com/nim-lang/Nim/issues/14345 ?

**Comment by cooldome** [comment]
Very likely related

**Comment by cooldome** [comment]
Generated code for start proc that causing a problem:
```cpp
tyObject_SpinnycolonObjectType___FkdhZbjlq5AppF9cuiMsEQw* blitTmp = spinny;
spinny = 0;
spinnyLoop__EGGH3eUCe9bGzDkothRoCUg((*spinny).t, blitTmp);
```
spinny is reset with `wasMoved()` before passing `(*spinny).t`.

@Araq:
Does it mean we should replace destructive moves with boolean flags? Any other ideas? 
we can introduce temporary for every parameter passed, but it will cause problems for var/lent arguments. 

Should we copy-on-sink in this case and amend CFG to understand that all parameters of one call are access simultaneously, not sequentially. 

@Clyybber, please opine what you think what correct solution for this problem. 

IMO, for sink argument we need to start isLastRead analysis not argument, but a bit earlier on the call itself. Then it will correctly identify that copy-on-sink is required here.

**Comment by Clyybber** [comment]
IMO its a codegen problem. `spinnyLoop(spinny.t, (let tmp = spinny; reset spinny; tmp))` should be evaluated left to right, so `spinny.t` must be stored in a temporary for the first argument.
This must be done in general if later argument stmtlists could modify earlier arguments, for example this:
```nim
proc say(a: int, b: int) =
  echo a,",",b

var a = 1
say a, (a += 1; a)
```
prints `2,2` but should print `1,2`

**Comment by cooldome** [comment]
Isn't temporaries are going to cause problems when arguments need be passed by reference?
Example:
```nim
proc spinnyLoop(x: ref int, spinny: sink Spinny): lent (ref int) =
  echo x[]
  result = x

proc start*(spinny: sink Spinny) =
  doAssert(unsafeAddr(spinnyLoop(spinny.t, spinny)) == addr(spinny.t)) # returned address should be the same

```

**Comment by Clyybber** [comment]
I don't think we should guarantee that the addresses are the same. They wouldn't be the same for a sink parameter either (due to destructiveMoveVar)

**Comment by cooldome** [comment]
For sink parameter can be different I do agree. But for spinny.t which is not sink it should natch address. This how `lent T/var T` works you can't return hidden pointer to a temporary variable.

**Comment by Clyybber** [comment]
Hmm, maybe we should just warn or error on such cases and not store the parameter we borrow from in a temporary.
Additionally we can try to change injectdestructors to generate the `reset(param)` after the call, but that could get tricky with exceptions.

**Comment by Clyybber** [comment]
Actually, shouldn't the code you provided be forbidden, because we sink the variable we borrow from, and the lent result will outlive the sink parameter?

**Comment by cooldome** [comment]
Agree my example with `lent T` is not correct, no valid after `sink`.
What if replace destructive move with a boolean flag `disableDestructorForXXX`? It will be set to `true` on sink just before the call. Destructive move is done to silence the destructor, we will silence it with:
```nim
if not disableDestructorForX:
  `=destroy(X)`
```

**Comment by Clyybber** [comment]
I think introducing temporaries in the backend for cases where stmtlist arguments modify previous arguments is a better solution, because then we don't need to generate all these booleans, but only generate a temporary in these edge cases. Also it would make the implementation adhere to the spec for the strict left-to-right evaluation.

**Comment by cooldome** [comment]
Ok

**Comment by Araq** [comment]
I think @Clyybber is right.

**Comment by Araq** [comment]
I think I have a fix for it.
