### ISSUE TITLE
The index does not list enum values

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1439]
Should [the index](http://build.nimrod-lang.org/docs/theindex.html) contain entries for enum values like `fmRead` for example?

The reason I ask is because one user had trouble with this. Including enum values in the index would possibly increase it's size tremendously though.

**Comment by andreaferretti** [comment]
Should it? I personally think not, but after three years, I think a decision one way or the other can be taken :-)

**Comment by dom96** [comment]
I still think it should :)

**Comment by Araq** [comment]
This has been implemented.
