### ISSUE TITLE
Bad codegen/emit for hashes.hiXorLo in some contexts.

### ISSUE THREAD

**Issue by MortimerSnerd** [nim-lang/Nim#14394]
Using devel branch, the C target, using gcc.
```
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-18
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 5beed56d0a5d9827680b34e7964da2031611dd6d
active boot switches: -d:release
```

In some contexts, the C code that gets generated for hashes.hiXorLo is invalid, and gcc fails with syntax errors.  The variables produced in a emit section don't match the generated parameters (a vs a_0):

```C
static N_INLINE(NU64, hiXorLo__wWqo9alrSZddOyokrApfNaQhashes)(NU64 a_0, NU64 b_0) {
        NU64 result;
        nimfr_("hiXorLo", ".../Nim/lib/pure/hashes.nim");
        result = (NU64)0;
        nimln_(100, ".../Nim/lib/pure/hashes.nim");
        __uint128_t r = a; r *= b; result = (r >> 64) ^ r;    // <<<<< From the emit in hashes.nim
        popFrame();
        return result;
}
```

This is the object and hash function this code was generated for:
```nim
type
  # In another module, V2X[T] = tuple[x, y: T]
  ShortCoord* = V2X[int16]
  # Used as a value for a table, ie: Table[ShortCoord,ASNodeInfo]
  ASNodeInfo = tuple[estScore, curScore: float32; parent: ShortCoord]

proc hash*(sc: ShortCoord) : Hash = 
  result = result !& hash(sc.x)
  result = result !& hash(sc.y)
  result = !$result
```

The bad news is extracting out this code from my module does not reproduce the problem.  My hope is this is enough to see what's going on.  If not, I can do some more work to either extract a reproducible case, bisect to where it stopped working, or push the project up so it can be compiled by someone else.

**Comment by Clyybber** [comment]
Can you check if https://github.com/nim-lang/Nim/pull/14395 fixes the issue?

**Comment by MortimerSnerd** [comment]
> Can you check if #14395 fixes the issue?

That fixes it.  I've avoided emit so far, so I didn't know you could quote like that.  Thanks.
