### ISSUE TITLE
`dup` documentation in release note is better than in sugar

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#14405]
The `dup` documentation in sugar is not detailed enough:

![image](https://user-images.githubusercontent.com/22738317/82477911-682ee400-9ad0-11ea-923a-8f01419865e4.png)

Compared to the release notes:

![image](https://user-images.githubusercontent.com/22738317/82477955-767d0000-9ad0-11ea-9882-92fea8c8c9eb.png)

it's missing the part of the underscore placeholder

Furthermore, the block syntax with one transformation per line is quite appealing visually and missing from the documentation as well.

**Comment by luismanfroni** [comment]
Doing this task, could i be assigned to it?

**Comment by luismanfroni** [comment]
Was merged in PR: https://github.com/nim-lang/Nim/pull/15455
Review if can be closed
