### ISSUE TITLE
[arc, destructors] Weird SIGSEGV with {.noinit.} pragma

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14425]
This code works fine with the default GC but fails with ``--gc:destructors|arc|orc``. 

Extracted from Arraymancer (it seems to compile with ``--gc:arc`` now - at least the ``tests_cpu.nim`` file which tests everything for the Arraymancer's CPU backend, but then it  fails at runtime on the simplest test ``tests/tensor/test_init.nim`` and this issue is about that fail)

### Example
```nim
type
  Tensor = object
    data: array[1, int]
    len: int
    offset: int
    storage: seq[int]

proc newTensor(): Tensor {.noinit.} =
  result.len = 1
  result.data[0] = 1
  result.offset = 0
  result.storage = newSeq[int](6)

let a = newTensor()
echo a.storage
```

### Current Output
```
Traceback (most recent call last)
/home/dian/Projects/data/test.nim(16) test
/home/dian/.nim/lib/system.nim(649) newTensor
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
@[0, 0, 0, 0, 0, 0]
```

### Additional info
Fails on 1.2.0 (with ``--gc:arc`` too)

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-21
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3eaa870c0a3ac0a97c1726278412141140d35b9b
active boot switches: -d:release
```

**Comment by ghost** [comment]
Really weird - works with ``--debugger:native``, hangs (if you don't provide ``-d:danger``) if you remove ``offset`` or ``len`` (from both ``newTensor`` and object definition)

EDIT: That example seem to actually work for me with Clang 10.0, so might be a GCC-specific bug? My GCC version is 9.3 (Although Arraymancer's test still fails).

**Comment by Yardanico** [comment]
Oh lol, it actually works with Clang, so might be a GCC-specific bug? My GCC version is 9.3

**Comment by ghost** [comment]
More confusing stuff - **Sometimes** doesn't crash with ``--opt:speed``

All in all seems like the crash is really flaky

**Comment by Yardanico** [comment]
Ah nevermind, seems like it's flaky - sometimes it crashes, but sometimes it does not.

**Comment by alaviss** [comment]
> ```nim
>   result.storage = newSeq[int](6)
> ```

My guess is that this creates a `sink`, and since it was `{.noInit.}`, `result.storage` might be filled with garbage, which then causes trouble when the destructor thinks there's valid data in there and try to free it.

I don't see a good solution for this.

**Comment by Araq** [comment]
Solution is easy, use this:

```nim

type
  Tensor = object
    data: array[1, int]
    len: int
    offset: int
    storage: seq[int]

proc newTensor(): Tensor {.noinit, nodestroy.} =
  result.len = 1
  result.data[0] = 1
  result.offset = 0
  result.storage = newSeq[int](6)

let a = newTensor()
echo a.storage
```

**Comment by alaviss** [comment]
ping @mratsim so he can prepare his library for destructors.
