### ISSUE TITLE
moveFile() does not replace when file exists on Windows

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#14432]
Original issue: https://github.com/dom96/choosenim/issues/199.

nimarchive calls `moveFile()` which is [documented](http://nim-lang.github.io/Nim/os.html#moveFile%2Cstring%2Cstring) with `If dest already exists, it will be overwritten.`

If you see the [code](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L1804) for Windows however, it fails if file already exists. Per the docs, [MoveFileExW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw) requires the `MOVEFILE_REPLACE_EXISTING` flag to overwrite.

This needs to be fixed in the stdlib and backported to 1.2.x and 1.0.x.

cc @vegansk @yglukhov @timotheecour

**Comment by ghost** [comment]
duplicate of https://github.com/nim-lang/Nim/issues/14057 though :)
