### ISSUE TITLE
line number missing from stacktrace 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14444]
originally reported here: [Traceback missing line number - Nim forum](https://forum.nim-lang.org/t/6355)
but the problem is frequent, annoying (makes debugging harder), and fixable.

### Example
```nim
when true: # D20200524T202847
  var i: string
  i[10] = 'j'
  echo i
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10814.nim t10814
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

### Expected Output
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10814.nim t10814
=>
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10814.nim(2) t10814
```

### Additional Information
* never worked
* acae3b02c7d3b7d916430223c5a2948e68d83ea4 1.3.5

in more complex cases, the lack of line number would be more problematic, eg:
```nim
when defined case4:
  template bar(i) =
    i[10] = 'j' # <- stacktrace should show this line number

  proc fun() =
    var i: string
    bar(i)
  fun() # <- stacktrace only shows this line number
```

**Comment by mratsim** [comment]
templates don't stacktrace properly in general, they eat one line.

**Comment by timotheecour** [comment]
> templates don't stacktrace properly in general, they eat one line.

that's an unrelated issue, the line number is missing even without templates, eg:
```nim
when true: # example i gave in https://forum.nim-lang.org/t/6355#39311
  echo "ok0"
  var i = ""
  var u0 = 12
  echo "ok1"  ## <- line number points to here
  const u1 = 12
  var u2 = 12
  i[10] = 'j'
  echo i
```

For templates, I think we can also improve things (see https://github.com/timotheecour/Nim/issues/259); the idea is to add nimfr_ + popFrame + goto to templates so that they appear as regular procs as far as stacktraces are concerned (controlled by a `--stacktraceForTemplates` + pushable pragma to localize it as this would be costly)
