### ISSUE TITLE
{.borrow:`.`.} not working with distinct generics

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#14449]
The following fails to compile

```Nim
type Foo[T] = object
  foo: T

type Bar[T] {.borrow:`.`.} = distinct Foo[T]
```

**Comment by Vindaar** [comment]
Yep, just noticed that too.

**Comment by boyanl** [comment]
Sorry for the newbie question, but is there a way to work around this, apart from re-declaring accessors for the `distinct` type? (it's not too bad, but I'm wondering if there's something shorter)

**Comment by mratsim** [comment]
Working around type bugs is not a newbie question but an art. I use though mutable parameters requires some tricks with casts to raw addresses:

https://github.com/mratsim/trace-of-radiance/blob/99f7d85dec857f0efa0c9b0eafd339871599c0e1/trace_of_radiance/scenes_animated.nim#L71-L88

```Nim
# workarounds https://github.com/nim-lang/Nim/issues/14440
# so ugly ...
func `+=`(a: var Distance, b: Distance) {.inline.}=
  cast[var float64](a.addr) += b.float64
func `-=`(a: var Velocity, b: Velocity) {.inline.}=
  cast[var float64](a.addr) -= b.float64

func `+=`(a: var ATime, b: ATime) {.inline.}=
  cast[var float32](a.addr) += b.float32
template `<`(a, b: ATime): bool =
  a.float32 < b.float32

template `*`(accel: Acceleration, dt: ATime): Velocity =
  Velocity(accel.float64 * dt.float64)
template `*`(v: Velocity, dt: ATime): Distance =
  Distance(v.float64 * dt.float64)
template `*`(k: float64, v: Velocity): Velocity =
  Velocity(k * v.float64)
```

**Comment by boyanl** [comment]
Thanks, but unless I'm missing a subtler point, it seem like it's a different issue?
I'll just do without the generic type for now, it's easy enough

**Comment by mratsim** [comment]
Ah right it was https://github.com/nim-lang/Nim/issues/14440, my bad. I created many distinct issues at that time.

**Comment by ringabout** [comment]
Related: https://github.com/nim-lang/Nim/issues/6039
