### ISSUE TITLE
`nim doc --project ..` pulls in a specific Nimble module (cairo) only when generating the index

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#14453]
The `nim doc --project` is pulling in the procs, etc. only from one Nimble installed module: `cairo`, which is a dependency of the `ggplotnim` package.

This issue can be reproduced using the latest nim devel as of today (2020-05-25) as well.. https://github.com/nim-lang/Nim/commit/55758920f446ebf1eecab980460bf6e664b8dba7

I have set up a [minimal example repo][1] to show this issue.

### Example

1. Install nim using the latest devel as of today (2020-05-25)
2. `nimble install ggplotnim` 
3. `git clone --single-branch --branch nimdoc-indexes-nimble-module https://gitlab.com/kaushalmodi/nim-doc-bug-reports.git nimdoc-indexes-nimble-module`
4. `cd nimdoc-indexes-nimble-module/prj_top`
5. `nim doc --project top.nim`
 

### Current Output

Open htmldocs/theindex.html in a browser, and you will see something like this at the top
    
![image](https://user-images.githubusercontent.com/3578197/82858611-55f2e280-9ee2-11ea-9b7d-78ef52896f51.png)

### Expected Output

None of the nimble installed packages should show up in the index.

In this example, the cairo module got installed as a dependency of the ggplotnim package (also nimble-installed), which was imported is this example's `top.nim`.

### Additional Info

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-26
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 55758920f446ebf1eecab980460bf6e664b8dba7
active boot switches: -d:release
```

/cc @timotheecour

[1]: https://gitlab.com/kaushalmodi/nim-doc-bug-reports/-/tree/nimdoc-indexes-nimble-module

**Comment by ringabout** [comment]
We shouldn't be worried about .bable files now.
