### ISSUE TITLE
`nim doc ..` on a user project is attempting to run runnableExamples from stdlibs, and failing incorrectly [devel] [regression]

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#14473]
`nim doc ..` is failing because of 2 reasons:
- runnableExamples are attempted to be run from an imported stdlib (`sequtils` in this example). This is not expected. 
- While above should not be happening, it is failing for not finding a proc from the imported stdlib module (`toSeq` from `sequtils` in this example).

### Example
```nim
# https://forum.nim-lang.org/t/6382#39363
import std/[sequtils]

# "nim doc t.nim" will work once below line is uncommented
# export sequtils

template doit():untyped =
  ## doit
  ## return output only
  toSeq([1,2,3,4,5])

echo doit()
```

### Current Output

```
/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_examples1.nim(15, 12) Error: undeclared identifier: 'toSeq'
[runnableExamples] failed: generated file: '/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_group0_examples.nim' group: '(rdoccmd: "", docCmd: "", code: "# autogenerated by docgen\n# source: /home/kmodi/sandbox/nim/bug_reports/nim_doc_over_eager_runnableExamples/t.nim\n# rdoccmd: \nimport r\"/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_examples1.nim\"\n", index: 0)' cmd: /home/kmodi/usr_local/apps/6/nim/devel/bin/nim c -r --warning:UnusedImport:off --path:/home/kmodi/sandbox/nim/bug_reports/nim_doc_over_eager_runnableExamples --nimcache:/tmp/kmodi/.cache/nim/t_d/runnableExamples   /tmp/kmodi/.cache/nim/t_d/runnableExamples/t_group0_examples.nim
```

### Expected Output
```
# (no runnable examples should be running from stdlibs or imported nimble packages)
@[1, 2, 3, 4, 5]
```

### Additional Information

* Minimal example was provided by @qqtop on https://forum.nim-lang.org/t/6382#39363
* This issue is blocking generation of docs for my projects.
* This regression is starting to fail the `nim doc` executions on Travis done using the latest nim devel. Example: https://travis-ci.org/github/kaushalmodi/version/jobs/692027081#L355
* I haven't confirmed but probably this commit ( https://github.com/nim-lang/Nim/commit/f96555bd102d534342eac14063bd8d93ec08a6dc ) caused this regression /cc @timotheecour Can you please take a look at this issue?

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-26
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2a4a43b05fa3fa6ad3f85543ccfbd9ea450c9be0
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment]
I confirm that pulling to the latest devel as of now (1fc40db984041ebc65470677ec69e621d26fd4df) and then reverting just f96555bd102d534342eac14063bd8d93ec08a6dc fixes this regression.

**Comment by timotheecour** [comment]
@kaushalmodi indeed; this should be fixed in https://github.com/nim-lang/Nim/pull/14439 (I just tried), can you confirm on your end and also for your project that #14439 works?

I can revert #14441 also if https://github.com/nim-lang/Nim/pull/14439 will take too long to merge
