### ISSUE TITLE
Memory corruption with --gc:arc with a seq of objects with an empty body.

### ISSUE THREAD

**Issue by MortimerSnerd** [nim-lang/Nim#14472]
This is on the latest devel branch: cc65ae6011eeb7f85726e6eebfc8dee922ad3451

I declared a object with no body, as a placeholder, and then later I made a seq of them.  With certain code paths, it would crash in the Nim allocator.  Compiling with -d:useMalloc showed assertions from `malloc`, and valgrind shows reads outside of allocated areas.  Valgrind runs clean if I compile without `--gc:arc` and just `-d:useMalloc`.  

Here's a reproduction:

```nim
type
  ImportMaterial* = object
    # Adding a field here makes the problem go away.

  Mesh* = object
    vertices: seq[float32]
    material: ImportMaterial

  ImportedScene* = object
    meshes*: seq[Mesh]

proc bork() : ImportedScene =
  var mats: seq[ImportMaterial]

  setLen(mats, 1)
  add(result.meshes, Mesh(material: mats[0]))

var s = bork()
```

Compiled with `nim c --gc:arc -d:useMalloc test.nim`

The `vertices` field  in Mesh isn't necessary to reproduce, but on my system, it makes malloc spit out asserts.  Without it, I can only see the problem under valgrind.
 
```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: cc65ae6011eeb7f85726e6eebfc8dee922ad3451
active boot switches: -d:release
```

**Comment by Clyybber** [comment]
Fixed on devel.
