### ISSUE TITLE
RVO not applied to object with large array

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#14470]
```nim
type X = object
  v: array[1024*1024*8, int]

proc f(): X =
  result.v[0] = 1

var x = (ref X)()
x[] = f()
echo x.v[0]
```

note how huge object is placed on stack, crashing the application on linux (which has an 8mb default stack size)
```
N_LIB_PRIVATE N_NIMCALL(tyObject_X__KqwtR1mZdQ5eNccTtsN3pA, f__KQQBzps5MRoTwkbIifdBMQ)(void) {
        tyObject_X__KqwtR1mZdQ5eNccTtsN3pA result;
...
        return result;
```

```
[arnetheduck@tempus tmp]$ nim --version
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by mratsim** [comment]
`var x = f()` should be changed to
```Nim
var x: ref X
new x
x[] = f()
```
Otherwise the caller would overflow as well.

Second, I think Nim is actually the C-array semantics there (so there is a conflict between RVO and C-arrays)

**Comment by arnetheduck** [comment]
fixed example - `C` array sematics are not relevant - in fact, if you change to `f(): array[...]` it'll pass return value by pointer like it should

**Comment by Araq** [comment]
Yeah, I noticed this too after I wrote the RFC... ;-)
