### ISSUE TITLE
Can't attach a pragma to a cased field.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#14511]
Attaching a pragma to a field used in a case within an object has no effect on the AST.

### Example
```nim
import macros

template myPragma() {.pragma.}

type
  XType = enum
    XInt,
    XString
  X = object
    case y {.myPragma.}: XType
      of XInt:
        a: int
      else:
        b: string
  
var x: X = X(y: XInt, a: 5)
echo x.y.hasCustomPragma(myPragma)
echo x
echo X(y: XString, b: "abc")
```

### Current Output
```
nim/lib/core/macros.nim(1546, 25) Error: index 1 not in 0 .. 0
```

### Expected Output
```
true
(y: XInt, a: 5)
(y: XString, b: "abc")
```

### Additional Information
I did also try `X.y.hasCustomPragma(myPragma)`; that compiles, yet returns false.

```
$ nim -v
Nim Compiler Version 0.1.2
```

**Comment by ghost** [comment]
It's a known bug https://github.com/nim-lang/Nim/pull/11526

**Comment by kayabaNerve** [comment]
While that seems to cover hasCustomPragma being problematic, it doesn't seem to address this specific issue.

**Comment by ghost** [comment]
@kayabaNerve it does though, I've been using parts of the code from that PR in my JSON.to fork to support field annotations - https://github.com/Yardanico/telenim/blob/master/src/telenim/json_custom.nim (especially https://github.com/Yardanico/telenim/blob/master/src/telenim/json_custom.nim#L194)
And see how I use it in https://github.com/Yardanico/telenim/blob/master/src/telenim/types.nim, e.g. in https://github.com/Yardanico/telenim/blob/master/src/telenim/types.nim#L74

**Comment by ghost** [comment]
The main trick there is that you have to do "yourSym.owner.getImpl()[2]" where yourSym is a symbol of a field of the object you want to get pragma of.

**Comment by kayabaNerve** [comment]
Got it; I read through the discussion, not the source. Thanks for pointing that out; should I close this issue?

**Comment by kayabaNerve** [comment]
Thanks for the workaround.

**Comment by ghost** [comment]
@kayabaNerve not sure, probably you should keep it open unless that PR is merged :)

**Comment by kayabaNerve** [comment]
Sure. Thanks again for linking the relevant PR and a workaround.

**Comment by kayabaNerve** [comment]
Sorry, was browsing this issue on my phone and clicked the wrong button.
