### ISSUE TITLE
sleepAsync takes forever with poll(-1)

### ISSUE THREAD

**Issue by gabearro** [nim-lang/Nim#14525]
Using sleepAsync with poll(-1) seemingly causes a program to stall forever and in larger programs can result in weird compile behavior where there is a drastically reduced number of lines being compiled after adding sleepAsync to procs.

### Example
```nim
import asyncdispatch

var fut = sleepAsync(100)

if not fut.finished:
  poll(-1)

echo fut.finished
```

### Current Output

Nothing happens

### Possible Solution

* In file xyz there is a call that might be the cause of it.

```
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by dom96** [comment]
poll(-1) will wait forever for IO events. You've got no events that you're waiting on... so you'll wait forever. There is no bug here.
