### ISSUE TITLE
javascript backend produces javascript code with syntax error in object syntax

### ISSUE THREAD

**Issue by mildred** [nim-lang/Nim#14534]
In nim code involving macros with a javascript target, I sometimes get syntax errors.

The generated code looks like (it was all in one line but I indented it):

```js
{
  get: HEX7C_12545226(access_12534241(s_12533414).get, HEX3Aanonymous_12545001),
  set: HEX3Aanonymous_12545285,
  id: HEX26_12555266(access_12534241(s_12533414).id, [makeNimstrLit("doc")])
}.set(dataHEX60gensym12555340_12575498, dataHEX60gensym12555340_12575498_Idx, val2HEX60gensym12555342_12585011);
```

The javascript error seems hard to tell at first glance, but it is a `SyntaxError: unexpected token: ':'` inside the object definition. indeed, the object expression is a correct javascript expression but not a correct statement.

Another example triggering the error is:

```js
{hello: 1, world: 2}.hello
```

The correct syntax for whatever reason is:

```js
({hello: 1, world: 2}).hello
```

I do not have a small reproducible example (yet?) but it is easy to reproduce and can be demonstrated with the following commit: https://github.com/mildred/nclearseam/tree/2a25724d9bb4e4fabde25261b5d0e09ba0c662e7

```
$ nim js samples/compute/calcul_meubles
$ python -m http.server 8000
$ firefox http://localhost:8000/samples/compute/
```

### Additional Information

```
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by mildred** [comment]
Workaround is to use the following proc in Nim to add parenthesis:

```nim
proc paren[T](x: T): T {.importcpp: "(#)", nodecl.}
```

**Comment by timotheecour** [comment]
> I do not have a small reproducible example

please try to minimize, it's the first step towards bug fixing
