### ISSUE TITLE
Default proc param is undefined when function is called from js console.

### ISSUE THREAD

**Issue by fuzzthink** [nim-lang/Nim#1454]
```nimrod:
proc test(a=2) {.exportc.} =
  if a==2:
    echo "got 2"
  else:
    echo a
test()
```

both ``./test`` and ``node test.js`` echoed: "got 2"

running it in browser also echoed "got 2", but when calling test() in browser console, it echoed: "undefined"

**Comment by yglukhov** [comment]
Vote for closing this:
1. FFI calling convention is just something you must know about, when using it. Can you blame C codegen for having the same "issue"?
2. Runtime check has it's cost, while compile-time doesn't. When there's a traidoff between code effectiveness and debugability we should tend to the former.
3. Semantically such runtime checks are hardly compatible with asmjs, which someday nim might target.

**Comment by dom96** [comment]
Agree with @yglukhov. A JavaScript developer cannot reasonably expect a JS function to support default variables.

**Comment by Perelandric** [comment]
@dom96: JavaScript now has default parameters and the ES6 to ES3 transpilers currently have at least partial support, so it seems like a reasonable expectation of developers.

Runtime cost... meh, it's JS and modern engines are very well optimized. Is it impossible to generate an asm.js-friendly check?

I think Nim will be the odd man out if it doesn't work as expected. I don't plan on using this feature; just putting it out there.

**Comment by dom96** [comment]
If ES6 supports it then that's a different story. But I doubt many browsers support that spec yet. It's the emulation of default parameters which is not a good idea in my opinion.

**Comment by Perelandric** [comment]
Currently it is emulated, though imperfectly. But again, this isn't my battle. I'll leave it for others to worry about.

**Comment by dom96** [comment]
It's emulated for procedures which are called in Nim code. That's fine.
