### ISSUE TITLE
lib/pure/ssl_certs.nim: missing conversion of TaintedString to string

### ISSUE THREAD

**Issue by akavel** [nim-lang/Nim#14561]
There seems to be a missing TaintedString->string conversion in ssl_certs.nim

### Example
```nim
import asyncdispatch
```

### Current Output
```
c:\prog> nim c --taintMode:on tmp.nim
...
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\ssl_certs.nim(71, 5) Error: type mismatch: got <TaintedString> but expected 'string'
```

### Expected Output
should compile successfully

### Possible Solution

* In lib/pure/ssl_certs.nim, the [iterator scanSSLCertificates](https://github.com/nim-lang/Nim/blob/devel/lib/pure/ssl_certs.nim#L64-L98) performs [a call to getEnv](https://github.com/nim-lang/Nim/blob/devel/lib/pure/ssl_certs.nim#L71), which returns TaintedString, and yields the result immediately; however, the iterator is declared as yielding string. Maybe the result of getEnv should be converted to string there? Or maybe the whole scanSSLCertificates should return TaintedString, and a conversion be done by callers?

### Additional Information

```
C:\prog\mana>nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by narimiran** [comment]
As of Nim 1.5.1, taint mode is deprecated.

I'm closing this because I doubt there's any chance something that's on its way out will be fixed, sorry.
