### ISSUE TITLE
withDir also available on Nim

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14560]
### Summary
[withDir()](https://nim-lang.github.io/Nim/nimscript.html#withDir.t%2Cstring%2Cuntyped) feels *very* useful on NimScript, being a [simple tiny `template`](https://github.com/nim-lang/Nim/blob/devel/lib/system/nimscript.nim#L329), 
I was wondering if is possible to also have it on Compiled Nim std lib, just 1 convenience proc,
should be relatively easy, same API, same Documentation, same Examples, just moved into Nim.
:)

**Comment by timotheecour** [comment]
Maybe in std/scripting
Along with other procs intended to write high level scripts, std/os staying a bit lower level to avoid kitchen sink; eg:
* pipe (analog to shell `|`)

**Comment by juancarlospaco** [comment]
I dont have an opinion on where it should live, as long as I can import it and use it on compiled Nim.
:smile:

**Comment by ringabout** [comment]
I want this function too. Where should I place this function? `std/scripting` or in fusions?

**Comment by Araq** [comment]
I use it all the time too... It should be in ``fusion / scripting``, I think.
