### ISSUE TITLE
many unittests + optimizations = huge compile time

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1457]
Basically I have something like this:

``` nimrod
import unittest

test "foo": echo "hi"
```

When I copy the foo test 500 times (I have a lot of tests), optimized compile time with gcc goes up to 25 seconds, with clang to 35 seconds.
The real program is over at https://github.com/def-/nimrod-unsorted/blob/master/test_all.nim and takes up to 70 seconds.

**Comment by Araq** [comment]
Will be fixed eventually by re-implementation of unittest.
