### ISSUE TITLE
`lent` gives wrong results with -d:release

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14578]
`lent` gives wrong results with -d:release

### Example
```nim
proc byLent[T](a: T): lent T = a
block:
  let a = 10
  let a2 = byLent(a)
  doAssert a2 == a2, $a2 # ok
  doAssert byLent(a) == a, $byLent(a) # bug
```

### Current Output
```
nim c -r -d:release -f t10897.nim
Error: unhandled exception: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10897.nim(9, 12) `byLent(a) == a` 140732898775544 [AssertionDefect]
```
looks like it returns the address instead

### Expected Output
```
works
```

### Additional Information
* devel 0824fdd06100282a853fa50efb66e2161f4235d8 1.3.5

**Comment by cooldome** [comment]
The issue here is the same as https://github.com/nim-lang/Nim/issues/14420
```nim
proc byLent[T](a: T): lent T = a
```
byLent contains stmtListExpr and stmtListExpr involves temporary object in backend

**Comment by timotheecour** [comment]
@cooldome if what you say were true, the same workaround would apply here, but this is not the case:
`result = a` still gives `AssertionDefect`

at the very least there is some different here (even if, perhaps, there is a common root cause)
