### ISSUE TITLE
static uint64 at compileTime: 'intVal' is not accessible using discriminant 'kind' of type 'TFullReg' [FieldDefect]

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#14585]
`static uint64` parameter cannot be accessed in a VM context they raise the error

```
'intVal' is not accessible using discriminant 'kind' of type 'TFullReg' [FieldDefect]
```

Test case:
```Nim
const foo_m0ninv = 0x1234'u64

proc foo(m0ninv: static uint64) =
  echo m0ninv

static: # Execute in a VM context
  foo(foo_m0ninv)
```

Tracing the bug, the crash happens line 450 of vm.nim: https://github.com/nim-lang/Nim/blob/32083c7ff88c46b81c30df95ff5c81c57935bc23/compiler/vm.nim#L441-L453

At that point we have a `rkNode` instead of a `rkInt` and we crash.

This prevents me from using the same code for both runtime and compile-time (i.e. I need to dispatch with `when nimvm`)

I also suspect that it's linked to the nimsuggest crashed mentioned by @alaviss here https://github.com/alaviss/nim.nvim/issues/18#issuecomment-564831930

**Comment by cooldome** [comment]
works as expected now

**Comment by narimiran** [comment]
> works as expected now

For me it produces the same thing as reported in the original report:

```
Error: unhandled exception: 'intVal' is not accessible using discriminant 'kind' of type 'TFullReg' [FieldDefect]
```

**Comment by timotheecour** [comment]
@cooldome please always write git hash instead of `now`, `works as expected now` is very vague.

I'm fixing this here: https://github.com/nim-lang/Nim/pull/17590
