### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by nu8** [nim-lang/Nim#14600]
Using this file:

~~~nim
import httpclient
let s1 = "https://speedtest.lax.hivelocity.net"
let o1 = newHttpClient()
let s2 = o1.getContent(s1)
echo s2
~~~

and this command:

~~~
nim c -d:ssl https.nim
~~~

With MSYS2 works fine. But if I instead use LLVM (Clang):

<https://github.com/mstorsjo/llvm-mingw>

I get this:

~~~
lld-link: error: undefined symbol: _setjmp
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_system.nim.c.o:(markStackAndRegisters__U6T7JWtDLrWhtmhXSoy9a6g)
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_system.nim.c.o:(showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_net.nim.c.o:(close__UCnvqeCP6HY9ax9cmybKvMtw)
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_net.nim.c.o:(isIpAddress__lty7O9aUHIZT9cqYHeC2n5zA)
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_streams.nim.c.o:(fsPeekData__xdahQHwcesKp9bR6BAtJSqA_4)
>>> referenced by C:\Users\Steven\nimcache\https_d\stdlib_httpclient.nim.c.o:(newConnection__OTRwNmMCrM24z6RZ2ZmLqg)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
~~~

**Comment by timotheecour** [comment]
windows specific

@nu8 please:
* minimize ; it's. likely triggered simply by having a raised exception somewhere
* try with all of these: `--exceptions:setjmp|cpp|goto|quirky` and report which work, which don't

**Comment by nu8** [comment]
I think I figured it out - seems to work fine with this:

~~~
nim c -d:ssl -l:-lmsvcrt-os https.nim
~~~

**Comment by timotheecour** [comment]
still, this could pop up in different contexts; the question is whether there's something to change in nim compiler, like adding `-l:-lmsvcrt-os` on windows when --cc:clang is passed; that's why would be nice if you could minimize with some code that doesn't depend on -d:ssl nor any imports; can you try:

```nim
try: raise newException(ValueError, "foo")
except: discard
```

**Comment by nu8** [comment]
Your example works fine with just `nim c a.nim`

**Comment by Araq** [comment]
We don't support MSYS2 or other Unix emulators, we run on Windows natively.

**Comment by nu8** [comment]
@Araq with all due respect, do you know what you are talking about? Here is
what happens on Windows before you install anything:

~~~
PS C:\> nim c a.nim
Hint: used config file 'C:\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: a [Processing]
CC: stdlib_io.nim
Error: invocation of external compiler program failed. The system cannot find
the file specified.
Additional info: "Requested command not found: \'gcc.exe -c  -w
-mno-ms-bitfields   -IC:\\nim\\lib -IC: -o
C:\\Users\\Steven\\nimcache\\a_d\\stdlib_io.nim.c.o
C:\\Users\\Steven\\nimcache\\a_d\\stdlib_io.nim.c\'. OS error:" 2
~~~

Where do you think `gcc.exe` comes from? Windows users get it from MSYS2,
Cygwin, or LLVM.

**Comment by Yardanico** [comment]
@nu8 there are MinGW builds for Windows without any MSYS2/Cygwin stuff. Also there's VCC (Visual Studio C Compiler)

**Comment by nu8** [comment]
@Yardanico where are they? I wasnt aware of that so I made my own:

https://github.com/nu8/gulf/blob/master/chapter-3/pkg-gcc.ps1

**Comment by Yardanico** [comment]
@nu8 for example http://mingw-w64.org/doku.php/download/mingw-builds

**Comment by nu8** [comment]
@Yardanico you realize those are all 2 years old right?

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/

**Comment by RSDuck** [comment]
you can get the latest mingw gcc versions via [msys2](https://www.msys2.org/). It's a bit confusing, as it's integrated into the compability layer (also you get package for libraries management which is helpful).

**Comment by nu8** [comment]
@RSDuck yeah I know. I am now using Clang, but before I was doing same as you. However this is what I am confused about:

> Araq commented 9 hours ago\
> We don't support MSYS2 or other Unix emulators, we run on Windows natively.

**Comment by RSDuck** [comment]
that's what I was talking about when I said the naming was confusing. Msys2 is on one hand the software distribution (which you probably meant), but also the posix compability layer for Windows (which Araq was probably pointing to). Via the msys2 distro you can install both gcc and clang compiling for the msys2 and the mingw ABI, the latter produces native windows binaries.

**Comment by nu8** [comment]
It seems this was closed without regard for the fact that this issue is now, and has always been about making native Windows binaries.

**Comment by RSDuck** [comment]
have you tried mingw clang installed via msys2?

**Comment by nu8** [comment]
No, because for some reason MSYS2 thinks that Clang requires GCC:

https://packages.msys2.org/package/mingw-w64-x86_64-clang

which it doesnt. So I just the package I linked in the original post.
