### ISSUE TITLE
`heapqueue.nim` missing `proc find`

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#14617]
The `proc del` interface takes an index.  The automated `when isMainModule:` tests in the same module already show how useful it would be to have a `proc find*(hq: HeapQueue[T], x: T): int`.

### Summary

```Nim
proc find*[T](hq: HeapQueue[T], x: T): int =
  ## Linear scan to find index of item ``x`` or -1 if not found
  result = -1
  for i in 0 ..< hq.len:
    if hq[i] == x: return i
```

### Description

Adding this would eliminate the need for client code re-implementing this simple proc all the time.  That's about it.

**Comment by Araq** [comment]
Alright. RFC accepted please proceed to the implementation phase.

**Comment by c-blake** [comment]
Ok.  PR filed as https://github.com/nim-lang/Nim/pull/14628 .  Tests should pass.  Let me know if you need me to change anything.
