### ISSUE TITLE
Constructing a uint64 range on a 32-bit machine leads to incorrect codegen

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#14616]
### Example
```nim
let limit = 1'u64

let rangeVar = 0'u64 ..< limit
echo "Things are broken here already:"
echo "range len : ", len(rangeVar)
echo "range repr: ", repr(rangeVar)

# Normal iteration works:
for i in 0'u64 ..< limit:
  if i > limit:
    echo "We won't get here"

for i in rangeVar:
  if i > limit:
    echo "We shouldn't get here"
    quit 1
```

### Current Output

```
Things are broken here already:
range len : 1
range repr: [a = 0,
b = 18225216979206144]

We shouldn't get here
```

As seen in the example above, merely executing the `..<` operator produces an invalid `HSlice` value. Since such a construction is used in the `mapIt` template, this leads to `IndexError` being raised in otherwise correct code. If I hadn't called `quit` in the example above, the loop would have iterated until `18225216979206144`.

### Nim version

```
Nim Compiler Version 1.3.1 [Windows: i386]
Compiled at 2020-06-09
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b4e9f8e814373fc38741736197d88475663ce758
active boot switches: -d:release
```

**Comment by stefantalpalaru** [comment]
Is it related to this? https://github.com/nim-lang/Nim/issues/13902

**Comment by zah** [comment]
It's possible. My testing was with the Nim version used in our nim-beacon-chain project (which is Nim 1.2 with a single patch applied). Haven't tested it in Nim 1.2.2 RC or Nim devel yet.

**Comment by Yardanico** [comment]
@zah works on Nim devel:
```
Things are broken here already:
range len : 1
range repr: [a = 0,
b = 0]
```

**Comment by ghost** [comment]
Broken on devel too (`nim c --cpu:i386 --passC:-m32 --passL:-m32 -r main.nim`). 
```
Things are broken here already:
range len : 1
range repr: [a = 0,
b = 4294967296]

We shouldn't get here
```
