### ISSUE TITLE
dynamicBindSym issue (experimental)

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#14622]
Related to 

https://github.com/nim-lang/Nim/issues/14605 and timotheecour

I tried with {.push experimental:"dynamicBindSym".}

And while that seem to work fine if all code is in the same module for my real world use case with multiple modules I get issues: I have for testing two modules:

```nim
# module m
import macros

{.push experimental:"dynamicBindSym".}

macro mconnect*(p: typed): untyped =
  let pro = bindSym($p)
```

```nim
# module t
import m

proc p27(i: int) =
  echo i * 27

mconnect(len)

mconnect(p27)
```

```
$ nim c t.nim 
......
/tmp/kkk/m.nim(6, 7) Hint: 'pro' is declared but not used [XDeclaredButNotUsed]
/tmp/kkk/t.nim(8, 9) template/generic instantiation of `mconnect` from here
/tmp/kkk/m.nim(6, 20) Error: undeclared identifier: 'p27'
```

The strange fact is that it seems to work for len() proc which is from system, but not for local proc with unique name.

**Comment by timotheecour** [comment]
this can't work but my PR https://github.com/nim-lang/Nim/pull/11754 would allow that
