### ISSUE TITLE
No short-circuit evaluation in static context (ex. `when`)

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14631]
Because `compiles((let _ = (echo ""))` is false, compiler probably shouldn't try to compile `(echo "") is int`.

### Example
```nim
template foo(x) =
  when compiles((let _ = x)) and x is int:
    discard

foo:
  echo ""
```

### Current Output
```
Error: expression 'echo [""]' has no type (or is ambiguous)
```

### Additional Information
Nim 1.2.0 and current devel 6aa971d39f1339a27a953972cd329f9cbe791f98

**Comment by timotheecour** [comment]
see https://github.com/nim-lang/Nim/pull/13541 + whole discussion around it

**Comment by jibal** [comment]
It doesn't and shouldn't work that way. `compiles((let _ = x)) and x is int` is an expression and must be well formed.
Use `when (when compiles((let _ = x)): x is int else: false):`
