### ISSUE TITLE
Nim 1.2.0 --gc:arc makes going over a large file much slower

### ISSUE THREAD

**Issue by marnix** [nim-lang/Nim#14651]
My apologies that this is not a small example yet.

With nim 1.2.0 (from current nixpkgs), running the code from https://gist.github.com/marnix/48cbcb00ced295c3e182c765f4a74939 with
```
nim c --opt:speed -d:release arcperfdiff && time ./arcperfdiff
```
takes ~1 second, but adding `--gc:arc` increases that to 5+ seconds:
```
nim c --gc:arc --opt:speed -d:release arcperfdiff && time ./arcperfdiff
```
(In my scenario I'm using file set.mm from https://github.com/metamath/set.mm/raw/b0925f0afd5963577ea76b252cb6613c885b393d/set.mm.)

```
❯ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```

**Comment by marnix** [comment]
Note that @zevv and Rika have already looked at this: see https://irclogs.nim-lang.org/13-06-2020.html, 08:12:46 - 08:33:10 UTC, and http://zevv.nl/div/diff.png: Apparently the difference is causes by a lot of integer overflow checks?

**Comment by juancarlospaco** [comment]
`-d:danger` ?, or a local push / pop pragma?. :thinking:

**Comment by Araq** [comment]
Since this is overflow checking we cannot do much about it. As @juancarlospaco suggested use a ``{.push overflowChecks: off.}`` around the procs in your inner loops or compile with ``-d:danger``.
