### ISSUE TITLE
seq.setLen sometimes doesn't zero memory

### ISSUE THREAD

**Issue by silent-observer** [nim-lang/Nim#14655]
Sometimes the seq.setLen method leaves garbage without zeroing it which is probably wrong.

### Example
```nim
for i in 0..10000:
  var test = newSeqOfCap[uint32](1)
  test.setLen(1)
  echo test
```

### Output
Output is big but contains things like
```
...
@[0]
@[0]
@[0]
@[52]
@[0]
@[0]
@[0]
@[875912000]
@[1563450176]
@[0]
@[0]
@[0]
@[0]
@[0]
@[54]
@[0]
@[0]
...
```
I've looked into the setLen code and it seems like it should set memory to zero always. Also for some reason comparisons like `test[0] != 0` always fail (optimization?), and the amount of garbage changes depending on the other code with no obvious pattern. Also about 150 of the first iterations are always correctly zeroed out. The amount of garbage seems to be the biggest for sequences with length = 4 but completely disappears for all lengths >=5.

### Additional Information
Bug was spotted in 1.2.0 version installed via choosenim, unfortunately couldn't test it on devel channel because it won't compile.
```
$ nim -v
Nim Compiler Version 1.2.0 [Windows: i386]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
same problem with `setLen(a: string, n: int)`
## proposal
* add `isInit: bool` optional param, as noted in compiler/strutils2.nim, and default to true
```nim
proc setLen*(result: var string, n: int, isInit = true)
proc setLen*[T](result: var seq[T], n: int, isInit = true)
```
* make sure destructors are called when setLen(seq) truncates

## related
`newString` and `newSeq` are also inconsistent in how `newString` is uninitialized, whereas newSeq is initialized.
likewise, we should add `isInit = true` optional param.

it's safe by default, and code that needs it for optimization can use `isInit = true` (same rationale as with `{.noinit.}` being non-default)

**Comment by Araq** [comment]
Under ARC it's clear the destructors should be called and they are. I don't see the need for ``isInit = false`` for now.

**Comment by timotheecour** [comment]
> I don't see the need for isInit = false for now.

well that's the current behavior of `setLen(string)` (but not `setLen(seq)`), which is an -inconsistentcy that would be fixed under this proposal.

as for `isInit=false` (with the default `isInit = true`), it's needed for the exact same reason `{.noinit.}` exists, which allows users to optimize code they know are in a hot spot; and this applies to `newString` as well as `setLen`
