### ISSUE TITLE
--debugger:on fails (compiling c2nim using recent nimrod devel build)

### ISSUE THREAD

**Issue by julienaubert** [nim-lang/Nim#1466]
compiling c2nim, commit aabc743a6451f36c4312937e8062ec91692a0cd0
using nimrod built from commit: 0db99beecb6c28e2a5d9ee54670125d88d0b9378

nimrod c --debugger:on --parallelBuild:1 c2nim.nim 

$ nimrod c --debugger:on --parallelBuild:1 c2nim.nim 
config/nimrod.cfg(38, 2) Hint: added path: '/Users/julien/.babel/pkgs/c2nim-0.9.6' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/julien/.babel/pkgs/nim-portaudio-0.1.1' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/julien/.babel/pkgs/babel-0.4.0' [Path]
config/nimrod.cfg(38, 2) Hint: added path: '/Users/julien/.babel/pkgs/' [Path]
Hint: used config file '/Users/julien/Documents/projects/nimrod/config/nimrod.cfg' [Conf]
Hint: used config file '/Users/julien/Documents/projects/c2nim/nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: c2nim [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: os [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: parseopt [Processing]
lib/pure/parseopt.nim(54, 34) Warning: 'quoteIfContainsWhite' is deprecated [Deprecated]
c2nim.nim(11, 23) Warning: 'parseopt' is deprecated [Deprecated]
Hint: llstream [Processing]
Hint: ast [Processing]
Hint: msgs [Processing]
Hint: options [Processing]
Hint: lists [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: osproc [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
lib/pure/osproc.nim(250, 13) Warning: 'startCmd' is deprecated [Deprecated]
lib/pure/osproc.nim(274, 19) Warning: 'startCmd' is deprecated [Deprecated]
lib/pure/osproc.nim(282, 14) Warning: 'startCmd' is deprecated [Deprecated]
lib/pure/osproc.nim(756, 6) Warning: 'osError' is deprecated [Deprecated]
lib/pure/osproc.nim(922, 10) Warning: 'startCmd' is deprecated [Deprecated]
lib/pure/osproc.nim(724, 7) Hint: 'osproc.startProcessAuxFork(data: TStartProcessData): TPid' is declared but not used [XDeclaredButNotUsed]
Hint: sets [Processing]
Hint: math [Processing]
lib/pure/math.nim(200, 7) Hint: 'math.gettime(dummy: ptr cint): cint' is declared but not used [XDeclaredButNotUsed]
lib/pure/collections/sets.nim(716, 5) Hint: 'sets.testModule()' is declared but not used [XDeclaredButNotUsed]
compiler/options.nim(262, 7) Hint: 'head' is declared but not used [XDeclaredButNotUsed]
compiler/options.nim(290, 7) Hint: 'head' is declared but not used [XDeclaredButNotUsed]
Hint: tables [Processing]
Hint: ropes [Processing]
Hint: platform [Processing]
Hint: crc [Processing]
compiler/ropes.nim(162, 5) Hint: 'ropes.ropeSeqInsert(rs: var TRopeSeq, r: PRope, at: Natural)' is declared but not used [XDeclaredButNotUsed]
Hint: sockets [Processing]
Hint: unsigned [Processing]
Hint: nversion [Processing]
Hint: idents [Processing]
Hint: intsets [Processing]
Hint: idgen [Processing]
compiler/ast.nim(1466, 5) Hint: 'ast.sonsNotNil(n: PNode): bool' is declared but not used [XDeclaredButNotUsed]
Hint: renderer [Processing]
Hint: lexer [Processing]
Hint: nimlexbase [Processing]
Hint: wordrecg [Processing]
compiler/lexer.nim(219, 5) Hint: 'lexer.getColumn(L: TLexer): int' is declared but not used [XDeclaredButNotUsed]
compiler/renderer.nim(482, 16) Hint: 'rfNoIndent' is declared but not used [XDeclaredButNotUsed]
compiler/renderer.nim(131, 5) Hint: 'renderer.putLong(g: var TSrcGen, kind: TTokType, s: string, lineLen: int)' is declared but not used [XDeclaredButNotUsed]
compiler/renderer.nim(664, 5) Hint: 'renderer.gmacro(g: var TSrcGen, n: PNode)' is declared but not used [XDeclaredButNotUsed]
compiler/renderer.nim(258, 5) Hint: 'renderer.popCom(g: var TSrcGen)' is declared but not used [XDeclaredButNotUsed]
Hint: clex [Processing]
Hint: cparse [Processing]
Hint: pegs [Processing]
Hint: unicode [Processing]
Hint: astalgo [Processing]
Hint: rodutils [Processing]
compiler/astalgo.nim(255, 5) Hint: 'astalgo.strTableToYaml(n: TStrTable, marker: var TIntSet, indent: int, maxRecDepth: int): PRope' is declared but not used [XDeclaredButNotUsed]
compiler/astalgo.nim(462, 2) Hint: 'EmptySeq' is declared but not used [XDeclaredButNotUsed]
Hint: algorithm [Processing]
cparse.nim(408, 5) Hint: 'cparse.skipTypeIdentExport(p: var TParser, prefix: char): PNode' is declared but not used [XDeclaredButNotUsed]
/Users/julien/Documents/projects/c2nim/nimcache/msgs.c:3297:3: error: expected expression
                else {
                ^
1 error generated.
/Users/julien/Documents/projects/c2nim/nimcache/stdlib_osproc.c:2107:2: error: expected expression
        else {
        ^
/Users/julien/Documents/projects/c2nim/nimcache/stdlib_osproc.c:2450:3: error: expected expression
                else {
                ^
/Users/julien/Documents/projects/c2nim/nimcache/stdlib_osproc.c:2462:2: error: expected expression
        else {
        ^
3 errors generated.
Error: execution of an external program failed

**Comment by TiberiumN** [comment]
Still crashing

**Comment by narimiran** [comment]
Cannot reproduce, it works now (almost 5 years later :)).
