### ISSUE TITLE
Visual Studio(VCC) 2019 cannot compile empty tuple generated by Nim

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#14667]
It works with gcc.

### Command line

```bash
nim c -r --cc:vcc bugtup
```

### Example
```nim
var bugTup = ()

proc main() =
  debugEcho bugTup
  
main()
```

### Current Output
```
C:\Users\AndriLim\nimcache\bugtup_d\@mbugtup.nim.c(64): error C2059: syntax error: '}'
Error: execution of an external compiler program 'cl.exe /c /nologo   /IF:\projects\status-nim\lib /IF:\projects\bug /FoC:\Users\AndriLim\nimcache\bugtup_d\@mbugtup.nim.c.obj C:\Users\AndriLim\nimcache\bugtup_d\@mbugtup.nim.c' failed with exit code: 2
```

### Expected Output
```
()
```

The compiler produce this C code and VCC 2019 seems doesn't like the `{}`.

```C
N_LIB_PRIVATE tyTuple__qERWGavQjzug69cyzEYP39bQ bugTup__XaG7QrFzC9aZhBgUBoCX3SQ = {};
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-06-10
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 8bbdb8f43fb0da04d4b75bca011662f690972bfe
active boot switches: -d:release
```

**Comment by cooldome** [comment]
What is the error? Possibly some compiler command line switch is required.

**Comment by Chris3606** [comment]
EDITED FROM PREVIOUS STATE: I've got what looks to be the same bug in v1.4.2; the code I used to get codegen to produce that code was different, but the result is the same.  The generated code is definitely not valid for MSVC; using `= { }` for structure initialization simply isn't supported by MSVC AFAIK; the closest I can think of right now is `= { 0 }` for 0-initialization.

MSVC makes a number of "odd" choices regarding what features of struct initialization it supports, and this is an unfortunate result.  I believe there may be significantly more cases than the one the OP mentioned that produce code like this, particularly when the `orc` GC is used; I've had two libraries now that fail to compile when code like this is generated (at least one of which only generates such code when `orc` is the GC).  The libraries in question are rather large, but I could attempt to boil it down to a reproducible case.  Bottom line though, unless I've missed something (and please correct me if so), this appears to be a hard blocker for compiling a lot of Nim code with MSVC.

**Comment by Chris3606** [comment]
Updated previous post with some actually useful information.

**Comment by ringabout** [comment]
It works with `nim cpp -r --cc:vcc ttest.nim`.

`()`

**Comment by Chris3606** [comment]
I moved my conversation over to the [likely duplicate](https://github.com/nim-lang/Nim/issues/15117) to avoid confusion.
