### ISSUE TITLE
No overload for indexing NimNodes as var.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#14670]
### Summary

this exists
```nim
proc `[]`*(n: NimNode, i: int): NimNode {.magic: "NChild", noSideEffect.}
```
this does not
```nim
proc `[]`*(n: NimNode, i: int): var NimNode 
```
simply changing 
```nim
proc `[]`*(n: NimNode, i: int): NimNode {.magic: "NChild", noSideEffect.}
```
to
```nim
proc `[]`*(n: NimNode, i: int): var NimNode {.magic: "NChild", noSideEffect.}
```
results in 
fatal.nim(49)            sysFatal
Error: unhandled exception: vm.nim(768, 22) `typ != nil`  [AssertionError]

### Alternatives
```nim
proc t(a : var NimNode) =
  a = newLit(1)
proc t2(a : NimNode) =
  for i in 0..<len(a):
    var x = a[i]
    t(x)
    a[i] = x
```

**Comment by solo989** [comment]
The error
fatal.nim(49) sysFatal
Error: unhandled exception: vm.nim(768, 22) typ != nil [AssertionError]
was from 1.2.0

in 1.2.2
Error: attempt to access a nil address
is reported instead
and in some simple test cases
no error is reported at all

**Comment by timotheecour** [comment]
tricky to implement due to the way it's implemented
