### ISSUE TITLE
unroll should be implemented or deprecated

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14695]
Please consider that the `{.unroll.}` pragma should be implemented or deprecated for the next Final Stable Release.

I know Nim has some Experimental features so why specifically `{.unroll.}` ?,
because `{.unroll.}` is not behind any `--experimental:` nor `--legacy:` nor `--define:` nor `import`,
is not on the Experimental documentation, is on the Stable documentation manual,
is enabled by default, but is useless, so maybe is time to think about starting its deprecation process,
or implement it, at least gradually, like for 1 target, maybe it can be implemented first for JavaScript target (?).

- https://nim-lang.org/docs/manual.html#pragmas-unroll-pragma

I think is a nice feature to have!, can be good for the package ecosystem.
:)

**Comment by Araq** [comment]
Nim's iterators and templates make unrolling particularly simple to do on your own so this feature should be removed.

**Comment by juancarlospaco** [comment]
`{.unroll.}` is not visible anymore for end users, the pragma remains on the compiler but is hidden and is removed from stdlib, 
I think I can close this.

:)
