### ISSUE TITLE
Docs: Make `..<`, `.. ^` more discoverable

### ISSUE THREAD

**Issue by snej** [nim-lang/Nim#14717]
Follow-up from #14671 -- to improve the discoverability of slice operations, make a few minor additions to the `system` module docs:

1. In the [Misc table](https://nim-lang.org/docs/system.html#system-module-misc), add `^b` and `a ..^ b`.
2. In the [Seqs table](https://nim-lang.org/docs/system.html#system-module-seqs), after `x[a..b]`, add `x[a..<b]` and `x[a..^b]`. (Yes, technically these are features of slice, not seq, but a new user [read: me] may not be aware of the distinction.)

**Comment by timotheecour** [comment]
@snej why not instead make a PR?

**Comment by juancarlospaco** [comment]
Meanwhile [Wiki has some info that can be useful for you.](https://github.com/nim-lang/Nim/wiki/Nim-for-Python-Programmers#Slices) 
:)
