### ISSUE TITLE
[TODO] make `parseExpr` and `parseStmt` raise an error

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#1473]
Currently `parseExpr` and `parseStmt` simply print an error message if the passed string is not a correct expression or statement, respectively. However, this makes it impossible to react on errors in some macro code.

It would be nice if those functions raise an exception, say `EInvalidFormat`, if called with an invalid string.

**Comment by timotheecour** [comment]
@dom96  @Araq is current behavior correct? code below shows `parseStmt` throws only in last case; in other cases it just errors 

```nim
import macros
macro test(text: string): untyped =
  try:
    result = parseStmt(text.strVal)
  except ValueError:
    echo getCurrentExceptionMsg()

when defined(case0): # parseStmt doesn't throw but errors
  test """
block:
  let a1=1
  let a1=1
"""


when defined(case1): # parseStmt doesn't throw but errors
  test """
block:
  let a1=1
  a1=1
"""


when defined(case2): # parseStmt doesn't throw but errors
  test """
block:
  var a1=1
  a1=[1]
"""

when true: # parseStmt throws
  test """
var a1=1
 var a2=1
"""
```
