### ISSUE TITLE
Uninitialized `not nil` ref/ptr is nil

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#14730]
An uninitialized `not nil` `ref`/`ptr` is `nil`, even though it should not be. I'm not sure if this is intended behaviour, but it would be really weird if it was.

### Example
```nim
{.experimental: "notnil".}

var a: ref int not nil
echo a.isNil
```

### Current Output

`true`

### Expected Output

Compiler error

### Possible Solution

* Force (`not nil`) `var`s to be initialized
* Check if the `var` is used before being initialized and output an error if that's the case

```
$ nim -v
Nim Compiler Version 1.2.2
```

**Comment by timotheecour** [comment]
we need `{.ignoreNotNil.}` escape hatch, see https://github.com/timotheecour/Nim/issues/319

**Comment by konsumlamm** [comment]
The experimental manual has an example of this, claiming that the compiler would catch it (the second example), when in fact, it doesn't (see https://nim-lang.github.io/Nim/manual_experimental.html#not-nil-annotation):

**Comment by ringabout** [comment]
It works as expected if you put it in the function:
```nim
{.experimental: "notnil".}

proc foo =
  var a: ref int not nil
  echo a.isNil

foo()
```
