### ISSUE TITLE
Ready-to-use Nim Windows release, with gcc included

### ISSUE THREAD

**Issue by josephernest** [nim-lang/Nim#14744]
For better adoption / ease-of-use for new Nim users, could you maybe release a ready-to-use package for Windows with GCC already included (something like mingw-g64)?

Indeed, installing gcc on Windows is quite complex, there are many choices to do (cygwin? mingw? mingw-w64? msys2?), and even when installing mingw-w64, there are many cryptic questions: `i686 dwarf` or `86_64` with i-dont-remember-which-option?  
Even if I'm an active programmer, installing this on Windows is really non-trivial, and I'm sure that many people maybe give up during this process.

**A ready-to-use Nim package for Windows with GCC already included would be awesome!**

**Comment by genotrance** [comment]
Both finish.exe and choosenim install mingw for you already if no compiler is found on Windows.

**Comment by juancarlospaco** [comment]
Installation will install mingw at the end on Windows.

**Comment by Araq** [comment]
Well we already do that.

**Comment by josephernest** [comment]
Thanks everydone, I didn't notice that.
