### ISSUE TITLE
Minor, Repo description "Garbage-Collector"

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14746]
GitHub repo description still says "Garbage-Collected", and that description shows up on Google search,
it should be changed from old "Garbage Collector" naming to new "multi-paradigm memory management strategies" or similar,
I can not send PR to fix that, but should be an easy change. Minor bug.
- Follow up from https://github.com/nim-lang/Nim/pull/14619#issue-432020551 kinda

![bugy](https://user-images.githubusercontent.com/1189414/85212624-0d84e400-b32b-11ea-90d6-a8a442cc2bb7.png)

**Comment by Clyybber** [comment]
Fixed, thanks! (It now uses the website description combined with the "efficiency, expressiveness, and elegance" slogan)
