### ISSUE TITLE
Nim source archive install: 'install.sh' fails with error: cp: cannot stat 'bin/nim-gdb': No such file or directory

### ISSUE THREAD

**Issue by wiremoons** [nim-lang/Nim#14748]
Installing Nim version 1.2.2 from the nim-lang web site using the Unix *source archive* file. URL: https://nim-lang.org/install_unix.html

Build runs fine until the step to run the Nim provided: `install.sh` script. The script fails trying to copy `bin/nim-gdb` and then exits leaving a partial non-working Nim install.

Build steps used from within the direrctory containing the extract '1.2.2' source archive files:
```
./build.sh
bin/nim c koch
./koch tools
```
When the `install.sh` step is executed the output is as below:
```
simon@alienmoons:~/scratch/nim-1.2.2$ ls
bin/         build.bat  compiler/        copying.txt    doc/       install.sh*  lib/        nimsuggest/  tools/
build32.bat  build.sh*  compiler.nimble  deinstall.sh*  examples/  koch*        makefile    testament/
build64.bat  c_code/    config/          dist/          icons/     koch.nim     nimpretty/  tests/
simon@alienmoons:~/scratch/nim-1.2.2$ sh install.sh $HOME/.nimble
Nim build detected
copying files...
cp: cannot stat 'bin/nim-gdb': No such file or directory
```
Install script now stops, resulting in a failed Nim install with only a partial install completed. No `nim-gdb` file is in the source archive when seached for with command: `find -name "nim-gdb" -print`.

The contents of the `bin` directory are:
```
simon@alienmoons:~/scratch/nim-1.2.2$ ls bin/
nim*  nimble*  nimfind*  nimgrep*  nimpretty*  nimsuggest*  testament*
```

### Possible Solution

To fix the above and obtain a working Nim install, the lines **107 to 110** of the `install.sh` were commented out, and then the script re-run. Lines commented out are shown below:

```
  #cp bin/nim-gdb $bindir/nim-gdb
  #chmod 755 $bindir/nim-gdb
  #cp bin/nim-gdb.bash $bindir/nim-gdb.bash
  #chmod 755 $bindir/nim-gdb.bash
```

### Additional Information

Output of newly installed `nim` verison is below.  Not sure why it shows `Compiled at 2020-06-16` when it was just built today on my computer which has the current date of *2020-06-21*:

Is this another issue (ie I can open another new issue if required?) or does the `nim -v` not supposed show the actualy date it was built from the source archive? Maybe it is meant to state: `Release on 2020-06-16` (ie *relased* not *compiled*)?

```
simon@alienmoons:~$ date
Sun 21 Jun 11:07:31 BST 2020
```

```
simon@alienmoons:~/.nimble/nim/bin$ ./nim --version
Nim Compiler Version 1.2.2 [Linux: amd64]
Compiled at 2020-06-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: be34b5abe23e027b71a3a9da67037aac7afea6bc
active boot switches: -d:release
```

**Comment by Araq** [comment]
> Not sure why it shows Compiled at 2020-06-16 when it was just built today on my computer which has the current date of 2020-06-21:

Because you didn't bootstrap successfully?

**Comment by alaviss** [comment]
Currently this is caused by `niminst` not including `nim-gdb{,.bash,.bat}` in the source archive due to those being listed in `[UnixBin]` and `[Windows]` in `compiler/installer.ini`. Should not be too hard to fix.

**Comment by wiremoons** [comment]
> > Not sure why it shows Compiled at 2020-06-16 when it was just built today on my computer which has the current date of 2020-06-21:
> 
> Because you didn't bootstrap successfully?

Not sure what **bootstrap** step I am missing in the process?  I followed the steps on the Nim downloads page here: https://nim-lang.org/install_unix.html

These are stated as:

1. download the compressed archive, extract its contents into the desired installation directory
2. open a new terminal window, cd into the extracted directory, and execute the following commands:
```
sh build.sh
bin/nim c koch
./koch tools
```
I then also ran the `install.sh` script - which is not documented in the above steps for some reason?  Is there another **bootstrap** step I need to also run somewhere?

The whole process I run is actually in a script which I use to install a new system, or *nuke and pave* my Nim install when a new version is released. This is here: https://github.com/wiremoons/GenIsys-Ubuntu/blob/master/install/nim-install.sh

I can add in missing steps if I know what they are :)

SImon

**Comment by alaviss** [comment]
>  Is there another **bootstrap** step I need to also run somewhere?

Yes, it's `./koch boot -d:release`.

`build.sh` only builds the csources compiler.

**Comment by wiremoons** [comment]
> > Is there another **bootstrap** step I need to also run somewhere?
> 
> Yes, it's `./koch boot -d:release`.
> 
> `build.sh` only builds the csources compiler.

Thank you @alaviss - I have re-run the build process using the steps:

```
sh ./build.sh
bin/nim c koch
./koch boot -d:release
./koch tools
```
The version of the Nim compiler created with the above steps now shows the correct '**Compiled at**' date, now that additional *bootstrap* step is also carry out, as originally suggested by @Araq  

Will the fix for this issues be included in the archive file available from Nim downloads page here: https://nim-lang.org/install_unix.html ?  Also perhaps update the web page build steps (as above) too - so others don't have the same issue?

Currently the archive file still contains the broken `build.sh` script version - as you probably know :)

Thanks for your help with fixing this issue!
