### ISSUE TITLE
os.getEnv does not find an existing environment variable

### ISSUE THREAD

**Issue by ArthurZ** [nim-lang/Nim#14762]
os.getEnv does not find an existing environment variable

### Example
Windows 10 Pro
checking for whether an environment variable exists that I do know I set
`existsEnv("Blah")` 
the result is false. Even if I set it up with `setEnv` it does not find.
```

### Current Output
Env. variable not found
```

### Expected Output
```
Env. variable value retrieved
```

$ nim -v
Nim Compiler Version 1.2.2
```

**Comment by Araq** [comment]
```nim

import os

putEnv("mykey", "value")

echo existsEnv("mykey")
echo getEnv("mykey")

```

Works fine.
