### ISSUE TITLE
Variable declaration pragma does not work with `const`

### ISSUE THREAD

**Issue by haxscramper** [nim-lang/Nim#14781]
It is possible to use variable declaration pragma with `var` and `let` but when using `const` it fails to compile with `Error: cannot attach a custom pragma to ...`

### Example
```nim
macro varPragma(a, b, c: untyped): untyped =
  discard

let v {.varPragma.} = 111
var v {.varPragma.} = 111
const v {.varPragma.} = 111
```

### Current Output

Compilation error on last line in example:

```
Error: cannot attach a custom pragma to 'v'
```

### Expected Output

No compilation error

### Compiler version

```
$ nim -v
Nim Compiler Version 1.2.2 [Linux: amd64]
Compiled at 2020-06-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: be34b5abe23e027b71a3a9da67037aac7afea6bc
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
refs https://github.com/nim-lang/RFCs/issues/220
