### ISSUE TITLE
Multipart upload in httpclient broken

### ISSUE THREAD

**Issue by vimal7370** [nim-lang/Nim#14794]
Hi,

```nim
var client = newAsyncHTTPClient()
var data = newMultipartData()
data.addFiles({"hello.txt": "/tmp/hello.txt"}) # a 12 byte file
await client.postContent("http://127.0.0.1:7777/", multipart = data)
```
Older versions (tested on v0.20.0) will post 162 bytes to the server, while v1.2.2 httpclient sends only 160 bytes. From quick glance, this seem to also affect v1.2.0 as well.

https://github.com/nim-lang/Nim/blob/v1.2.2/lib/pure/httpclient.nim#L938

```nim
  result.add "--" & bound & "--"
```

should be..

```nim
  result.add "--" & bound &  "--" & httpNewLine
 ```

Related discussion:  https://github.com/nim-lang/Nim/pull/12982

**Comment by zedeus** [comment]
From the testing I did when writing it I found no errors. Indeed I just tried your example with a simple asynchttpserver that prints the body. hello.txt contains the string "12345678912":
```
--4292486321577947087
Content-Disposition: form-data; name="hello.txt"; filename="hello.txt"
Content-Type: text/plain

12345678912

--4292486321577947087--
```

I'll gladly admit I'm by no means an expert on http requests, but after reading https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html I can't see any errors here. I looked around and cannot find a source that claims you need a newline after the boundary of a multipart request. It's true this was done before 1.2.0, but I don't think it should. The content-length header dictates the length of the request, and I made sure it's correct.

**Comment by vimal7370** [comment]
Thank you for checking this.

HTTP clients like curl and httpie also seems to add a carriage return at the end when I test it on a simple HTTP server: 

```python
import SimpleHTTPServer
import SocketServer

PORT = 7777

class ServerHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def do_POST(self):
      content_len = int(self.headers.getheader('content-length', 0))
      post_body = self.rfile.read(content_len)
      print self.headers
      print "---"
      print post_body
      print "--- end ---"

Handler = ServerHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)

print "serving at port", PORT
httpd.serve_forever()
```
**Test using curl:**
$ curl -F 'hello.txt=@hello.txt' http://localhost:7777/

```
Host: localhost:7777
User-Agent: curl/7.54.0
Accept: */*
Content-Length: 204
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------69c5509be7c9f0a5

---
--------------------------69c5509be7c9f0a5
Content-Disposition: form-data; name="hello.txt"; filename="hello.txt"
Content-Type: text/plain

hello world

--------------------------69c5509be7c9f0a5--

--- end ---
```

**Test using httpie:**
$ http --form http://localhost:7777/ hello.txt@hello.txt

```
Host: localhost:7777
User-Agent: HTTPie/2.2.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 188
Content-Type: multipart/form-data; boundary=0e3bb4b92001fc7179fc0e133b808354

---
--0e3bb4b92001fc7179fc0e133b808354
Content-Disposition: form-data; name="hello.txt"; filename="hello.txt"
Content-Type: text/plain

hello world

--0e3bb4b92001fc7179fc0e133b808354--

--- end ---
```

**Test using nim 0.20.0:**

```
Host: 127.0.0.1:7777
Connection: Keep-Alive
content-type: multipart/form-data; boundary=5955470471231250137
content-length: 162
user-agent: Nim httpclient/0.20.0

---
--5955470471231250137
Content-Disposition: form-data; name="hello.txt"; filename="hello.txt"
Content-Type: text/plain

hello world

--5955470471231250137--

--- end ---
```

**Test using nim 1.2.2:**

```
Host: 127.0.0.1:7777
Connection: Keep-Alive
content-length: 160
content-type: multipart/form-data; boundary=5955470471231250137
user-agent: Nim httpclient/1.2.2

---
--5955470471231250137
Content-Disposition: form-data; name="hello.txt"; filename="hello.txt"
Content-Type: text/plain

hello world

--5955470471231250137--
--- end ---
```

In my case, I have a file uploader script written in nim that uploads files to a server written in Cowboy (Erlang). Updating nim from v0.20.0 to v1.2.2 broke the upload process because of the CRLF missing at the end. This broke the basic functionality of my program and had me running v0.20.0 all along, until yesterday when I decided to take time and compare the changes in recent versions of httpclient. 

> I looked around and cannot find a source that claims you need a newline after the boundary of a multipart 
> request. It's true this was done before 1.2.0, but I don't think it should.

You are correct. But other HTTP clients (curl, httpie) do send a CRLF at the end, probably due to compatibility reasons in order to make it work with different web servers. This change has broke multipart upload with at least one web server (Cowboy), and there might be others as well.

Httpclient is the defacto HTTP client library shipped with nim. While it must for sure follow known standards, my humble submission is that it must also be sending requests in manner other clients do.

**Comment by andreaferretti** [comment]
I never had the time to investigate the issue from https://github.com/nim-lang/Nim/pull/12982 but this behaviour may be exactly the reason it fails
