### ISSUE TITLE
Error compiling with gc:orc and a config.nims file: "system module needs: nimDestroyAndDispose"

### ISSUE THREAD

**Issue by snej** [nim-lang/Nim#14813]
The compiler immediately fails when compiling with `--gc:orc` if there is a `config.nims` file present (even if that file is empty!) It outputs:
```
...nim-#devel/lib/system/assertions.nim(23, 11) template/generic instantiation of `sysFatal` from here
...nim-#devel/lib/system/fatal.nim(49, 5) Error: system module needs: nimDestroyAndDispose
```
This happens in 1.2.2 and in the current devel build.

### Example

(Using dev channel, checked out & built this morning with `choosenim devel`, on macOS 10.15.5)

```bash
$  tree
.
├── config.nims
├── foo.nim
└── nim.cfg

0 directories, 3 files
$  cat config.nims
$  cat foo.nim
echo "foo!"
$  cat nim.cfg
--gc:orc
$  nim c foo.nim
Hint: used config file '/Users/snej/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/snej/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
Hint: used config file '/private/tmp/oops/nim.cfg' [Conf]
Hint: used config file '/private/tmp/oops/config.nims' [Conf]
.
/Users/snej/.choosenim/toolchains/nim-#devel/lib/system/assertions.nim(23, 11) template/generic instantiation of `sysFatal` from here
/Users/snej/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(49, 5) Error: system module needs: nimDestroyAndDispose
```

### Current Output

See error at end of above transcript.

### Expected Output

Should compile without errors.

### Additional Information

* Removing the [empty] config.nims file makes the problem go away.
* Removing the line `--gc:orc` from nim.cfg also makes the problem go away.

```
$ nim -v
Nim Compiler Version 1.3.5 [MacOSX: amd64]
Compiled at 2020-06-25
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Clyybber** [comment]
Works when moving the `--gc:orc` from nim.cfg into the cmdline or to config.nims as `switch "gc", "orc"`.

**Comment by genotrance** [comment]
I see this failure even with `switch("gc", "orc")` or `arc` for that matter. I'm compiling with `--app:lib` if that makes any difference.

**Comment by stisa** [comment]
Just wanted to say that this is still happens on devel (Compiled at 2020-09-07, git hash: e08b802d79e173d230b893ed96fd82c3c5228161)

When the `switch` is in the nimscript file, I get:
```
C:\Dev\nim-git\lib\pure\parseutils.nim(403, 21) Error: system module needs: nimDestroyAndDispose
```
when it's the cfg file, I get:
```
C:\Dev\nim-git\lib\system\assertions.nim(23, 11) template/generic instantiation of `sysFatal` from here
C:\Dev\nim-git\lib\system\fatal.nim(49, 5) Error: system module needs: nimDestroyAndDispose
```

**Comment by ghost** [comment]
This is still an issue on latest devel - maybe we just need to make NimScript ignore GC options if that's possible?
