### ISSUE TITLE
Rewrite old async modules to use asyncnet module

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1486]
The following modules need to be rewritten to use the new async await features:

- [x] ftpclient
- [x] smtp
- [ ] scgi
- [x] <del>db_*</del>

The following modules need to be rewritten to use the new async await features **and** need to be moved out of the standard library into separate babel packages:

- [x] irc
- [x] redis

**Comment by Araq** [comment]
Still an issue?

**Comment by dom96** [comment]
scgi is missing but I don't think it's necessary anyway. In fact it might be a good idea to remove the ``scgi`` module.
