### ISSUE TITLE
Please revert my commit

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14876]
Due to several issues I have had in the Nim community, as well as general behavior I've noticed from browsing IRC logs, I no longer wish to be associated with the Nim community or Nim projects in any way, including through the use of my code.

As such, I'd like to request that you revert the following commit: `d81feed3edc21521ba7107d435390c9edd0a7006`

This is by no means a legal threat, simply a request. I would prefer my code not be used, but I can't force you to stop using it.

Apologies for any disruption this may cause.

**Comment by 3n-k1** [comment]
Last time I tried to be as vague as I could people got upset, so here's backstory: The issues I've personally had are not the driving force here. What is the driving force is the community's refusal to be polite at all is disgusting. The IRC logs for July 1st 2020 contain multiple core contributors talking about how they think they should be "more blunt" despite their rudeness driving people away.

I don't want to be associated with that at all.

**Comment by 3n-k1** [comment]
Heads up to beef and friends; I am in your IRC rooms ~~(killin' your doodz)~~, and the screenshots I've posted on fedi alone have convinced a few people to not check out Nim, further proving my point.

Go full mask off, my guy, I'm begging you.
![image](https://user-images.githubusercontent.com/51172302/86307673-55d2ba80-bbe5-11ea-9e24-aa7957dc4aa7.png)

**Comment by 3n-k1** [comment]
Thank you Zachary, for not only banning me from a discord server I am not a part of, but also purposefully misinterpreting everything I have said about this. Grats, buddy.

I don't want to spam these issues, but since I've now been silenced, and a contributor is threatening to lock my issues, I feel the need to share my side.

![image](https://user-images.githubusercontent.com/51172302/86308057-46a03c80-bbe6-11ea-
9192-9afff76f8840.png)

**Comment by 3n-k1** [comment]
I'm really glad "fuck you for being an ass when I politely asked you not to" is considered harassment now.
![image](https://user-images.githubusercontent.com/51172302/86308793-1194e980-bbe8-11ea-8d59-12f60ef04e02.png)

**Comment by 3n-k1** [comment]
I let it slip several times, since I don't have my pronouns here, but you've been corrected multiple times now
![image](https://user-images.githubusercontent.com/51172302/86308978-8e27c800-bbe8-11ea-821e-8ba15611733d.png)

**Comment by 3n-k1** [comment]
Aaaaaand point proven. Thanks Zach.
![Uploading image.png…]()

**Comment by 3n-k1** [comment]
Users are now misgendering me and defending transphobia in the IRC. Interesting.

**Comment by 3n-k1** [comment]
As users have officially been given the go-ahead to misgender me, this is now a legal threat.

To quote [this](https://hackaday.com/2018/09/27/can-you-take-back-open-source-code/) Hackaday article: "Section 6 of the Berne Convention explains that the original author of a work, even if they have granted their rights to another entity, can object to its further use if they feel it has been utilized in a way which “would be prejudicial to his honor or reputation.” So in theory a disgruntled developer need only convince a judge that the maintainers of a project have damaged their reputation, say by publicly banning them for violating the Code of Conduct, and have a case for forcing the project to stop using their code regardless of preexisting licensing agreements."

Revert my code or I sue. You wanna be transphobes? Let's fuckin' go.

**Comment by 3n-k1** [comment]
All I asked was to have an issue closed. Y'all couldn't let it go.

**Comment by 3n-k1** [comment]
Alternatively, a formal apology and a complete ban on any and all transphobia (including misgendering) from your Github, Discord, IRC, Gitter, and forums will suffice.

**Comment by 3n-k1** [comment]
Don't "confused reacc" this, zach, my guy, my buddy, my pal. You're one of the main reasons this is happening.

**Comment by wltsmrz** [comment]
This one? https://github.com/nim-lang/Nim/commit/d81feed3edc21521ba7107d435390c9edd0a7006

It would be an interesting one to revert as it's pretty much linting / no behavior change? I would be surprised if this commit is reverted, but good luck.

Either way, I don't think the unprofessionalism here is necessary. As the internet becomes increasingly socialized these things seem likely to happen, but the text input box on github.com/a/b/issues/n should probably be treated a bit differently from the text input box on Discord. Personally, I subscribe to new issues reported to nim to see the cool things people are working on, but here I am seeing chat logs, "fuck yous," and ultimatums. It would be cool to keep the e-drama down to a dull roar.

**Comment by 3n-k1** [comment]
Actually, after the transphobia, the "fuck yous" are absolutely warranted. I'm disgusted with how my boy, my friend, my buddyguypal Zach has let people harass and misgender me despite multiple corrections.

All I wanted was to be left alone, buddy. But apparently, Yardanico and Beef thought that was too much. The finding out will continue until the fucking around improves.

**Comment by 3n-k1** [comment]
And you know, I wouldn't really call "Revert my code or just apologize and stop being transphobic" an ultimatum. Just apologize, it isn't hard.

**Comment by liquid600pgm** [comment]
Wtf mate, since when is using the wrong pronoun considered transphobia? Zachary simply didn't know that and shared his speculations of your actual gender. Keep in mind, you're on the Internet, people can't see your face and instantly use the correct pronoun after they see you, so mistakes *are* going to be made.

Using the wrong pronoun isn't transphobia. Just stop. It's you who's causing more and more drama, and whining isn't gonna get you anywhere.
