### ISSUE TITLE
readLine can only handle ASCII characters in the Windows console

### ISSUE THREAD

**Issue by ktamp** [nim-lang/Nim#14883]
**readLine** procedure, when used to read input from the **Windows console**, can only handle ASCII characters (characters with **ord** between 0 and 127).
Any other character is automatically converted to a NUL character ('\\0'); this is actually a feature of **fgets**.
You can test this by using the following code:

```nim
  import strutils
  import unicode

  let s = stdin.readLine
  echo s
  for cp in s.utf8:
    echo cp.toHex, ' ', cp
```
where input should be:
* Latin characters with accent or diacritics (e.g. Ü)
* Greek / Russian / Korean / any non-Latin characters

PR #14782 fixes this.

**Comment by ghost** [comment]
Is this still an issue after https://github.com/nim-lang/Nim/pull/14782? Do we have a test-case for it?

**Comment by ktamp** [comment]
This should not be an issue any more.
Try the code above. Copy/paste "καλημέρα" or "안녕" as input.

For "καλημέρα" the output should be:
καλημέρα
CEBA κ
CEB1 α
CEBB λ
CEB7 η
CEBC μ
CEAD έ
CF81 ρ
CEB1 α

For "안녕" the output should be:
안녕
EC9588 안
EB8595 녕
