### ISSUE TITLE
nimpretty multiple file support

### ISSUE THREAD

**Issue by memoryhole** [nim-lang/Nim#14891]
### Summary
Allow nimpretty to operate on multiple files.

### Description
By allowing nimpretty to operate on a list of files it will be easier to use. Currently you have to invoke the executable on every file in your project individually which is inconvenient.

### Additional Information
I've opened a PR to implement this: #14890
Alternative ideas and suggestions are welcome of course :)

**Comment by Araq** [comment]
Alternative idea: Config your editor to run nimpretty on save. 

Note that I don't have anything against this feature request but you asked for alternative ideas. ;-)

**Comment by narimiran** [comment]
Implemented in https://github.com/nim-lang/Nim/pull/14890
