### ISSUE TITLE
devel exceptions:quirky d:ssl httpclient error

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14936]
`--exceptions:quirky -d:ssl` always crash, I dont know how supported this is, but repro on devel and stable,
maybe it can add a `{.warning: "--exceptions:quirky is experimental and unstable".}` or similar, 
the Traceback is always the same, so maybe can be patched to work correctly,  ...or not.
 
I dont understand if development on `--exceptions:quirky` stopped in favor of `--exceptions:goto`,
if so then `--exceptions:quirky` should start its Deprecation process, if not then this bug should be fixed.

# Examples

```nim
import httpclient              # HTTPS
echo newHttpClient().getContent("https://api.ipify.org")
```

# Current Output

```nim
lib/pure/httpclient.nim(1074) getContent
lib/pure/httpclient.nim(1069) get
lib/pure/httpclient.nim(1045) request
lib/pure/httpclient.nim(1021) request
lib/pure/httpclient.nim(976) requestAux
lib/pure/httpclient.nim(871) newConnection
lib/pure/net.nim(743) wrapConnectedSocket
lib/pure/net.nim(409) isIpAddress
lib/pure/net.nim(403) parseIpAddress
lib/pure/net.nim(267) parseIPv4Address
Error: unhandled exception: Invalid IP Address. Address contains an invalid character [ValueError]
```

# Expected Output

- Work correctly.

# Possible Solution

Do not use `--exceptions:quirky` OR do not use `-d:ssl`:

```nim
import httpclient              # HTTP
echo newHttpClient().getContent("http://api.ipify.org")
```

# Additional Information

- Without SSL it works Ok.
- Without  `--exceptions:quirky` it works Ok.
- Traceback is always the same.
- IP Address is valid.
-  `--exceptions:goto` works Ok.

# System Information

<details>

```json

{
  "compiled": "2020-04-12T10:45:59",
  "NimVersion": "1.2.0",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2020-07-08T10:29:11-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 397312,
  "getTotalMem": 528384,
  "getOccupiedMem": 70224,
  "countProcessors": 6,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-1.2.0/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.11.4 compiled at 2020-06-26 10:22:53\ngit hash: couldn't determine git hash",
  "nimgrep": "1.5",
  "nimsuggest": "Nim Compiler Version 1.2.4 [Linux: amd64]\nCompiled at 2020-06-26\nCopyright (c) 2006-2020 by Andreas Rumpf\n\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.6.0 (2020-03-06 18:24:57) [linux/amd64]",
  "gcc": "gcc (GCC) 10.1.0",
  "clang": "clang version 10.0.0",
  "git": "2.27.0",
  "node": "v14.5.0",
  "python": "3.8.3",
  "ssd": true
}
```

</details>

# Proposed Labels

```csv
minor
```

**Comment by Araq** [comment]
The stdlib does not support "quirky exceptions". We could document that somewhere though...

**Comment by juancarlospaco** [comment]
@Araq 
I can send a PR to Document that as you say, but where should it be ?. (link it).
