### ISSUE TITLE
[ARC] segmentation fault when using implicit result

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#14961]
### Example
```nim
type
  Foo = object
    data: seq[int]

proc initFoo(len: int): Foo =
  let s = newSeq[int](len)
  Foo(data: s)

var f = initFoo(2)
```

### Current Output

```
Traceback (most recent call last)
nico/nico/ringbuffer.nim(15) arcbug2
Nim/lib/system/alloc.nim(972) dealloc
Nim/lib/system/alloc.nim(871) rawDealloc
Nim/lib/system/avltree.nim(74) del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Additional Information
use ``result = Foo(data: s)`` as a workaround.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-07-10
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 425972c4e8bde84ff8b84a64f1e68356dc0a1a3a
active boot switches: -d:release --gc:boehm
```

**Comment by timotheecour** [comment]
can't reproduce (but I tried on OSX), can you try:
* to git bisect
* on 1.2

**Comment by ee7** [comment]
I can reproduce this issue on Linux/amd64 using the same commit (latest `devel` https://github.com/nim-lang/Nim/commit/425972c4e8bde84ff8b84a64f1e68356dc0a1a3a).

But it works on Nim 1.2.4.

(I won't `git bisect` right now - sorry).

**Comment by alaviss** [comment]
Bisect first bad: 112511084d61edc0bb748ff8c267fb54bc7e9716

**Comment by Clyybber** [comment]
This is not arch specific. The transformation is wrong, the =destroy hook is inserted too early.

**Comment by timotheecour** [comment]
> This is not arch specific

but I'm not getting SIGSEGV and OP is...

**Comment by Clyybber** [comment]
@timotheecour Are you sure you compiled with `--gc:arc`?

**Comment by timotheecour** [comment]
my bad, sorry for the noise; I do get SIGSEGV as well with --gc:arc

**Comment by khchen** [comment]
There is a similar error (mabe, not sure) when compile https://github.com/yglukhov/kiwi/blob/master/tests/common.nim with --gc:arc.

```
Traceback (most recent call last)
kiwi\kiwi\symbolics.nim(87) common
kiwi\kiwi\expression.nim(8) +
nim\lib\system\refs_v2.nim(69) nimIncRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
