### ISSUE TITLE
Gotcha with `not`.

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1498]
``` nimrod
echo(not 0 >= 5)
```

Will output `false` because `not 0` is evaluated first as a bitwise not. @Araq mentioned on IRC the possibility of using `~` instead.

**Comment by mrordinaire** [comment]
@dom96, can you please point me to the relevant code snippet responsible for this? `not` is quite liberally used in the codebase.

**Comment by dom96** [comment]
@mrordinaire hrm? i'm not sure what you mean, the code snippet is right there.

**Comment by mrordinaire** [comment]
@dom96 I don't know what's the objective for this issue is. `grep`ping for the code snippet does not turn up anything.

**Comment by dom96** [comment]
The code snippet is just an example of a gotcha.

**Comment by keyle** [comment]
```nimrod 
echo(not(0 >= 5))
```

would work right? 

if so, I don't see this as a deficiency in the language. Many languages will not like

```
! false == false
```

and would require

```
!(false == false)
```

**Comment by benjolitz** [comment]
For the record, Python evaluates the test as True:
```
>>> not 0 >= 5
True
```

**Comment by dom96** [comment]
The difference between Python and Nim here is that Nim's ``not`` is overloaded for ints, whereas Python uses `~` as a bitwise not.

I'm assuming that @Araq would like to see `~` used for Nim as well, and for `not` to work only for booleans.

**Comment by mubaris** [comment]
@dom96 @Araq I would like to work on this. How do I approach this issue?

**Comment by Araq** [comment]
Patch system.nim so that ``not`` for integers is .deprecated and introduce proc bnot*() that maps to the underlying magics like the then .deprecated ``not`` operators.

**Comment by mubaris** [comment]
@Araq Why `proc bnot*()`, shouldn't it be ``` proc `~`*() ```

**Comment by Araq** [comment]
`~` is too useful as an user definable operator but it's debatable, if it's only defined for integers I can still overload it.

**Comment by krux02** [comment]
I would vote for a compiler warning the suggests to put parenthesis. This is done in some C compilers as well and works well. On the other hand, who writes that example?

```nim
echo(not(0 >= 5)) # should be echo(0 < 5)
echo(not a == b) # should be echo(a != b)
```

**Comment by dom96** [comment]
I think that was @Araq's plan but it turned out to be tough to implement reliably.

**Comment by krux02** [comment]
Interesting though. AFAIK nim already has term rewriting macros. Shouldn't this be a simple term rewriting macro that emits a warning and does nothing otherwise?

**Comment by Araq** [comment]
Warning about this is unresonably hard to implement. I think we can live with a wart that comes up once in a decade.
