### ISSUE TITLE
Presence of unused macro causes illformed AST error

### ISSUE THREAD

**Issue by iffy** [nim-lang/Nim#15004]
### Example
```nim
macro fn*(fun:untyped):untyped =
  echo "first"
  fun

macro fn*(key:string, fun:untyped):untyped =
  echo "second"
  fun

let c = fn(proc(count:int):string =
  return "x = " & $count
)
```

### Current Output
Compiling produces this error:

```
first
/usercode/in.nim(9, 12) Error: illformed AST: proc (count: int): string = return "x = " & $count
```

### Expected Output
```
first
```

### Possible Solution

If I remove the second `fn` macro, the program compiles as expected.

```
$ nim -v
Nim Compiler Version 1.0.6 [MacOSX: amd64]
Compiled at 2020-01-23
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 89b39ee8fe271d0e1b75c15a4c6cf82eb9c13aea
active boot switches: -d:release
```

I've also tested with 1.2.4 locally and with the [latest playground](https://play.nim-lang.org/#ix=2rOJ).

**Comment by ynfle** [comment]
2 possible solutions that I found were:
1. switching the order of the arguments of the second macro 
```nim
macro fn*(fun:untyped, key:string):untyped =
```
2. putting parentheses around the anon. proc
```nim
let c = fn((proc(count:int):string =
  return "x = " & $count)
)
```

**Comment by metagn** [comment]
Now gives "redefinition of :anonymous"
