### ISSUE TITLE
Test failed @ PASS: lib/packages/docutils/rstgen.nim C  ( 4.40 sec)  

### ISSUE THREAD

**Issue by verbus** [nim-lang/Nim#15015]
The build went ok but the test failed...

$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-07-18
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: ffe7b3a9bf1596e5016c8fcaf775f9261188d349
active boot switches: -d:release

verbus@ubuntu-s-4vcpu-8gb-nyc3-03:~/Nim$ time ./koch tests
.
.
.
.
.
PASS: lib/packages/docutils/rst.nim C                              ( 2.30 sec)
PASS: lib/packages/docutils/rstast.nim C                           ( 1.93 sec)
PASS: lib/packages/docutils/rstgen.nim C                           ( 4.40 sec)
tests failed

real 16m49.560s
user 55m20.157s
sys 6m12.969s

```

**Comment by timotheecour** [comment]
please change the title, I don't see how rstgen is related; you need to provide more details (give a link to full logs) otherwise this should be closed.
it's probably some prior test that failed (megatest?)
