### ISSUE TITLE
Testament: don't use the Nim in my PATH

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#15013]
When running tests using koch, testament uses the Nim in my PATH which is not what I want (and I don't see why anyone would want this)...

```
/mnt/c/Users/morfe/projects/nim/testament/testament r tests/async/tasynceagain.nim
FAIL: tests/async/tasynceagain.nim C
Test "tests/async/tasynceagain.nim" in category "tests"
Failure: reNimcCrash
$ /home/dom/.nimble/bin/nim c --hints:on -d:testing --nimblePath:tests/deps --nimCache:nimcache/tests/async/tasynceagain.nim_0d61f8370cad1d412f80b84d143e1257 tests/async/tasynceagain.nim
```

Why not just use ./bin/nim?

**Comment by ringabout** [comment]
Isn't testament a exposed tool? I use testament heavily in my project.

**Comment by dom96** [comment]
Really? That's the first time I hear of it being used for projects other than Nim.

Even so, it should check for the presence of bin/nim and use that instead of whatever is in the PATH. It's primary purpose is to test Nim.

**Comment by ringabout** [comment]
In `unittest` module, it said "instead of `unittest.nim`, please consider to use the testament tool which offers process isolation for your tests". 

https://nim-lang.org/docs/unittest.html

**Comment by ringabout** [comment]
I agree that `testament` should first check the bin directory. But It also should check the path. Otherwise, testament shouldn't be documented as a test tool.

BTW, my use case:
https://github.com/iocrate/netkit/tree/master/tests
https://github.com/planety/prologue/tree/master/tests

**Comment by ringabout** [comment]
BTW, you can specify the path of Nim executable.
```
--nim:path                use a particular nim executable (default: $PATH/nim)
```

**Comment by timotheecour** [comment]
it should default to `--nim:bin/nim`, and users who want to use nim in PATH can use: `--nim:nim`

**Comment by alaviss** [comment]
> When running tests using koch, testament uses the Nim in my PATH which is not what I want (and I don't see why anyone would want this)...

Then this is a `koch` bug that has to be fixed.
