### ISSUE TITLE
AsyncSocket.getPeerAddr appears to not work.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#15022]
I am getting this error even though it connects and can send and receive data otherwise.
```
raiseOSError
Error: unhandled exception: A request to send or receive data was disallowed 
because the socket is not connected and (when sending on a datagram socket 
using a sendto call) no address was supplied
```

### Example
```nim
import asyncdispatch, asyncnet, strformat
var socket = newAsyncSocket()
waitFor socket.connect("google.com", Port(80))
let (host, port) = socket.getPeerAddr()
echo &"connected to {host}:{port.int}"
```

### Non Async Example
Here is a non async example and it works without issues.
```nim
import net, strformat
var socket = newSocket()
socket.connect("google.com", Port(80))
let (host, port) = socket.getPeerAddr()
echo &"connected to {host}:{port.int}"
```
I correctly get:
```
connected to 172.217.14.206:80
```

```
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-14
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by ghost** [comment]
Can't reproduce on Linux

**Comment by treeform** [comment]
It must be a windows issue, Nim uses windows sockets they must have
different API or something.

**Comment by enthus1ast** [comment]
Could be this issue:

https://stackoverflow.com/questions/60591081/getpeername-always-fails-with-error-code-wsaenotconn


> When the WSAConnectByName function returns TRUE, the socket s is in the default state for a connected socket. The socket s does not enable previously set properties or options until SO_UPDATE_CONNECT_CONTEXT is set on the socket. Use the [setsockopt](https://docs.microsoft.com/windows/desktop/api/winsock/nf-winsock-setsockopt) function to set the SO_UPDATE_CONNECT_CONTEXT option.
