### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by isaacrg** [nim-lang/Nim#1504]
Please could a Debian package be made available for Nimrod, perhaps for submission to the [Debian Package Repo](https://www.debian.org/distrib/packages), such that Debian/Ubuntu/(Et al) could get automatic updates, and quicker downloads, for Nimrod, Babel, and Aporia.

**Comment by FedericoCeratto** [comment]
You might want to open a RFP: https://www.debian.org/devel/wnpp/

**Comment by reactormonk** [comment]
Having a debian package would also mean we commit to a specific version as soon as there's a version freeze.

**Comment by FedericoCeratto** [comment]
Debian is currently in freeze; any new package will go only in the Debian Unstable archive. The next freeze might be in more than a year from now.

**Comment by sirex** [comment]
+1 for debian package, because I could not get nim via apt and compiling it takes time...

**Comment by reactormonk** [comment]
IIRC we had someone from debian in the IRC channel a while back and he was concerned that the bootstrapping can't go all the way back. He said he would prefer to be able to build the current nim compiler incrementally from the pascal sources.

**Comment by FedericoCeratto** [comment]
@reactormonk the concern was from infinitiy0 and me due to the security implications.
Anyhow, we decided to upload the current package, for the time being, and it is currently in the "new" queue.

**Comment by dom96** [comment]
@FedericoCeratto What's the status on the debian package? Also, did you write any more information about what we can do to resolve these security issues anywhere?

**Comment by dgellow** [comment]
Any news ?

**Comment by FedericoCeratto** [comment]
Unfortunately the packaging of the current release is blocked by licensing issues. Commit 87f65f5e72148d6b44e09cfd4834c9366bfacd4c (in the devel branch) removes some files, but it hasn't been released yet.

**Comment by FedericoCeratto** [comment]
I'm happy to announce that Nim is now in Debian: https://tracker.debian.org/pkg/nim

    apt-get install nim

...have fun!
