### ISSUE TITLE
Command calls don't work with a single named arg

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#15050]
### Example
```nim
proc myProc(x = 0) = discard

myProc x=1 # error: undeclared identifier: 'x'
```

### Additional Information
* 1.2.4, 14d16c2174a4fcefd405f8c4eeaf57a6dcd2731d

**Comment by metagn** [comment]
It only works when the first argument is unnamed.

```nim
proc foo(a, b: int) = echo a + b

foo 4, b = 5 # 9
```

**Comment by timotheecour** [comment]
IIUC it's because of precedence rules, look at 
```nim
import macros
macro deb(a): untyped =
  echo a.treeRepr
  echo a.repr
deb:
  myProc x=1
```

```
StmtList
  Asgn
    Command
      Ident "myProc"
      Ident "x"
    IntLit 1

myProc x = 1
```

EDIT: looks like a common gotcha, see this recent post: https://forum.nim-lang.org/t/8037

the question is: how can we improve things here without introducing parser ambiguties?

on possible rule is:
```
myProc x = 1 # still parsed as (myProc x) = 1
myProc x = 1, expr # previously rejected by parser, now accepted as myProc(x = 1, expr)
```
which does not sound ambiguous
