### ISSUE TITLE
Docker scratch + Static Compilation + SSL produces "could not load: libcrypto.so"

### ISSUE THREAD

**Issue by atkinsonbg** [nim-lang/Nim#15058]
I'm trying to compile and place my executable into a Docker scratch container. It works fine until I introduce SSL. Running the container produces the following error: "could not load: libcrypto.so"

### Example

Compile command
```
nim c --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --passL:-static -d:ssl -d:release --opt:size api.nim
```

Dockerfile:

```
FROM nimlang/nim:latest as BUILD
RUN nimble -y install https://github.com/dom96/jester \
    https://github.com/status-im/nim-chronicles
RUN apt-get clean && \
    apt-get update && \
    apt-get install -y musl musl-tools binutils upx
COPY . .
RUN nim c --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --passL:-static -d:ssl -d:release --opt:size api.nim
RUN strip -s ./api
RUN upx --best ./api

FROM scratch
COPY --from=BUILD api api
CMD ["./api"]  
```

### Current Output

Compiles fine, but when I try to run it gives the following error:
```
could not load: libcrypto.so(.1.1|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.47|.46|.45|.44|.43|.41|.39|.38|.10|)
```

### Expected Output

SSL works as expected.

### Possible Solution

Hopefully, I'm just missing something easy on this one ;)

### Additional Information
None

**Comment by dom96** [comment]
Either ``apt-get install openssl`` (or libressl) or ``--dynlibOverride:openssl`` (the ``openssl`` part may need to be different) may also work.

**Comment by alaviss** [comment]
If you want to statically link with libssl, pass `--dynLibOverride:ssl` and `--passL:'-lssl -lcrypto'`

**Comment by atkinsonbg** [comment]
Hey! Thanks for the suggestions!

@dom96 openssl is already on the nimlang/nim:latest image, so good there. Using `--dynlibOverride:openssl` gave the same error. Checking the build container it's in there:
```
root@f31f80b8eca9:/# find -name "libcrypto*"
./usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

@alaviss Using those flags I get the following error:
```
#9 7.276 /usr/bin/ld: cannot find -lssl
#9 7.276 /usr/bin/ld: cannot find -lcrypto
```

**Comment by dom96** [comment]
Hrm, maybe you need to set LD_LIBRARY_PATH to include ./usr/lib/x86_64-linux-gnu/?

**Comment by alaviss** [comment]
> Hey! Thanks for the suggestions!
> 
> @dom96 openssl is already on the nimlang/nim:latest image, so good there. Using `--dynlibOverride:openssl` gave the same error. Checking the build container it's in there:
> 
> ```
> root@f31f80b8eca9:/# find -name "libcrypto*"
> ./usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
> ```
> 
> @alaviss Using those flags I get the following error:
> 
> ```
> #9 7.276 /usr/bin/ld: cannot find -lssl
> #9 7.276 /usr/bin/ld: cannot find -lcrypto
> ```

You don't have musl libc versions of those libraries, as such they can't be linked to your program. This is also why Nim couldn't catch `libcrypto.so.1.1`, since that version is linked against glibc, not musl libc.

**Comment by atkinsonbg** [comment]
Thanks again, I tried all sorts of combinations and nothing worked. I installed LibreSSL into the build image and still no luck. 

Going to go with this: https://scripter.co/nim-deploying-static-binaries/

Either use this guy's setup entirely or steal the bits I need.

Thanks for the suggestions.

**Comment by atkinsonbg** [comment]
**UPDATE**

I did end up using this: https://scripter.co/nim-deploying-static-binaries/

It was very easy to incorporate, just copy the `config.nims` file in and use the proper switches. This got me ssl, and a super small executable, so very happy!

Updated Dockerfile with the appropriate installs on the base Nim image:
```
FROM nimlang/nim:latest as BUILD
RUN apt-get clean && \
    apt-get update && \
    apt-get install -y musl musl-tools binutils upx curl build-essential
COPY . .
RUN nimble -y install
RUN nim musl -d:libressl ./src/api.nim

FROM scratch
COPY --from=BUILD ./src/api api
CMD ["./api"]  
```
