### ISSUE TITLE
os.lastPathPart does not work with --gc:arc.  

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#15069]
Function `lastPathPart ` outputs the wrong empty string when using VC++ and --gc:arc.

### Example
```nim
import os

let folderPath = "data/vox/mobs/qbdude2"
echo repr(folderPath.lastPathPart)
```

### Output with Arc
nim cpp --cc:vcc --gc:arc -r src/testarc.nim
```
""
```

### Output without Arc
nim cpp --cc:vcc -r src/testarc.nim
```
0000023D5D9A00C0"qbdude2"
```

### Possible Explanations

* Arc some how frees the out put of folderPath.lastPathPart before it has chance to echo but only with VC++ function call order?
* Windows usually supports linux path separators "/" but odd combination of VC++ and --gc:arc breaks it?

```
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-14
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Araq** [comment]
Cannot reproduce on devel, most probably because of the massive amount of bugfixes arc has received.
