### ISSUE TITLE
Wrong type inference

### ISSUE THREAD

**Issue by rockcavera** [nim-lang/Nim#15119]
The compiler is inferring the wrong type in this situation:

### Example
```nim
let a = -2147483648

echo typeof(a)
```

### Current Output
```
int64
```

### Expected Output
```
int
```

### Additional Information
* In the [manual](https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants) we have the following: "This integer type is `int` if the literal is in the range `low(i32)..high(i32)`, otherwise it is `int64`"
* `echo low(int32)` = -2147483648
* `echo high(int32)` = 2147483647

```
nim --version
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: e6f0d4a5a59f8230133481d25ce1c3f6e8daf0a5
active boot switches: -d:release
```

**Comment by Araq** [comment]
But it is unary operator '-' followed by the literal 2147483648 which does not fit into an int32. Works correctly.
