### ISSUE TITLE
Missing installation/deinstallation option on download page

### ISSUE THREAD

**Issue by nerdboy4200** [nim-lang/Nim#15146]
Download page talks of using OS repository version or choosenim - but does not mention install.sh or deinstall.sh - which can be used for manual installing/deinstalling.

This is used for those who like to use it to install nim globally while not using a version from the OS.

I know that the install script is somewhat documented in the packaging doc file - but finding this took time and is not really documented for the general user - some basic documentation on the unix install page for installing or de-installing would be appreciated.

**Comment by Araq** [comment]
These scripts are for Linux package creators and not for the general public. If you want installation to /usr/bin, use your Linux package manager.
