### ISSUE TITLE
Expand on the ways Nimrod may be built from source

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1515]
The website should list the three different ways to build a developmental version of Nimrod from source, since it isn't guaranteed that any particular one will work:
  - Via bootstrapping from csources
  - Via bootstrapping from a stable release
  - Via bootstrapping from a binary generated by one of the build bots

**Comment by Araq** [comment]
I think the current docs are sufficient and more ways to do things makes testing even harder.
