### ISSUE TITLE
(Re-)raise exceptions from the spawned proc when a `flowVar` is queried with `^flowVar`

### ISSUE THREAD

**Issue by sschwarzer** [nim-lang/Nim#15167]
### Summary

Exceptions occurring in spawn'ed procs should be re-raised when the `flowVar` is queried with `^flowVar`.

### Description

The [manual](https://nim-lang.org/docs/manual.html#threads-threads-and-exceptions) says:

> The interaction between threads and exceptions is simple: A handled exception in one thread cannot affect any other thread. However, an unhandled exception in one thread terminates the whole process!

I suggest that an exception raised in a spawn'ed proc should *not* stop the program, but instead should be (re-)raised when the `flowVar` is queried with `^flowVar` (or some other means, like `awaitAndThen`).

With this change, the following program (compiled with `--threads:on`)
```nim
import os
import threadpool

proc test(): bool =
  echo "in `test`"
  raise newException(CatchableError, "ouch, an exception")

proc main() =
  var f = spawn test()
  try:
    discard ^f
  except CatchableError:
    echo "The exception from the spawned thread should be caught, but " &
         "in current Nim isn't."
  # Make sure that the main thread finishes after the spawned thread, so that
  # we see the message if the spawned thread doesn't crash.
  sleep(1000)
  echo "after catching"

main()
```
would print "The exception from the spawned thread ..." and then "after catching". The actual behavior is that only "in `test`" is printed.

### Alternatives

At the moment, the suggested behavior can be "simulated" by creating a proc, say `wrappedTest`, which wraps `test` in a `try/except`. If an exception is raised, this wrapped proc could *return* (not *raise*) some information to the calling thread (the main thread above). The calling thread would then need to inspect this information and possibly raise an exception on behalf of `test`. Obviously this is rather cumbersome (although it could probably be simplied with a macro, but ideally a macro shouldn't be necessary, i. e. if this ticket is implemented).

A variant of this workaround is to modify the original spawned proc instead of wrapping it (so the proc has the API that the wrapped original proc would have). This variant has the disadvantage that the new ("wrapped") proc has an API which is very weird when used for a direct call (instead of a spawn). Also the disadvantage remains that the calling thread must inspect and unwrap the flowVar result.

### Additional Information

- Python's `concurrent.futures` has the described behavior: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future.result
- I'm not sure inhowfar the suggested change could/would break existing code. I think it's unlikely that a program *relies* on crashing if there's an exception in a thread.
- I tried to find out whether an issue like this here had been raised before, but didn't find any. Neither did I find useful information in the forum.
- Currently there are different approaches to concurrency in Nim, for example spawn/flowvars, channels, asyncio (intended for async IO though, as the name says) and external libraries like Weave. It may be that the above problem can be solved more easily with one of the other approaches, but nonetheless I think enhancing `threadpool` as described would improve the user experience a lot in cases where `threadpool` would be fine with the enhancement.
- I have applied the above workaround in one program. The wrapper of the spawned proc would return a string with an exception message while the proc normally needed to return anything.

  In a program I'm writing now, the proc to wrap regularly returns a string and has five parameters. So to return exception information instead of the string, I'd need an additional variant type and the wrapper proc would need to accept five arguments and pass them on to the wrapped proc. That would be very cumbersome.

**Comment by Araq** [comment]
Use Malebolgia instead which does exception re-raising.
