### ISSUE TITLE
async with tags:XXEffect cause Error: can have an unlisted effect: RootEffect

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#15192]
async with tags:XXEffect cause Error: can have an unlisted effect: RootEffect

### Example
```nim
import asyncdispatch
import db_common
proc a(){.async, tags:[DbEffect].} = discard
```

### Current Output

```
/playground/nim/lib/pure/asyncmacro.nim(319, 33) Error: can have an unlisted effect: RootEffect
```

### Expected Output
compile without error

```
$ nim -v
Nim Compiler Version 1.3.5 [MacOSX: amd64]
```
### playground:  
https://play.nim-lang.org/#ix=2umq

**Comment by ghost** [comment]
https://nim-lang.org/docs/asyncdispatch.html#limitationsslashbugs

**Comment by bung87** [comment]
hi yardanico , what's the relationship between `tags:[XXEffect]` and `raises:[]` ?

**Comment by ghost** [comment]
@bung87 well, they're both a part of the effect system

**Comment by ghost** [comment]
Also see https://github.com/nim-lang/Nim/issues/6639, but keep this issue open :)

**Comment by bung87** [comment]
ok , thanks! I'll leave it as is.

**Comment by Araq** [comment]
This is not supported and won't be anytime soon.
