### ISSUE TITLE
var_t_return.html wrong link for stdlib modules

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#15209]
The var_t_return link is linking to the wrong place **for standard library proc only**.
See https://github.com/nim-lang/Nim/pull/15208/checks?check_run_id=1011793080#step:10:77
![image](https://user-images.githubusercontent.com/22738317/90878372-b5f40a80-e3a5-11ea-9ee8-df17ab7ccf53.png)

From: https://github.com/nim-lang/Nim/pull/15208/commits/7e1d2e41d51439927fa3821eec686a35b97d1ba4

Note, an external module will have proper links (without an extra "manual" folder)

```Nim
type MyOption[T] = object
  case isSome: bool
  of true:
    val: T
  of false:
    discard

proc get*[T](self: MyOption[T], otherwise: T): lent T {.inline.} =
  if self.isSome:
    result = self.val
  else:
    result = otherwise
    
    
let a = MyOption[int](isSome: true, val: 1)
let b = a.get(0)
```

```
Error: 'otherwise' is not the first parameter; context: 'otherwise'; see https://nim-lang.org/docs/var_t_return.html
```

**Comment by narimiran** [comment]
This is fixed in devel and it points to https://nim-lang.github.io/Nim/var_t_return.html

This was the PR where it was changed: https://github.com/nim-lang/Nim/pull/14477/files#diff-dc05830f41a222a0b826e05a04ebd1e0R16-R18
