### ISSUE TITLE
[Feature request] Make asyncdispatch easy to integrate with other event loop in main thread

### ISSUE THREAD

**Issue by hackwaly** [nim-lang/Nim#15214]
### Summary

Currently `asyncdispatch` provides `poll`, `drain` to give ability to drive event loop manually. But both `poll` and `drain` process events in calling thread. Make it hard to wait events in background thread and process them in main thread. So hard to integrate with other event loop (Such as Cocoa NSApplication) in main thread.

I propose that `asyncdispatch` to give an optional parameter `process` with default value `true` as additional parameter of `poll`. If `process` is `false`, then retain events not process them. Give ability to manually process them in thread other than calling thread.

### Description

`proc poll(timeout = 500, process = true)`

**Comment by dom96** [comment]
I don't understand this proposal. There is no getting around having to call `poll` in the thread that you want to process the events in. You cannot access the dispatcher for that thread otherwise.

Furthermore, you can integrate with another event just fine. I've done it for Cocoa and for SDL's.

**Comment by hackwaly** [comment]
Hello @dom96 

Where I can see your code about integrate with another event loop? I'd love to study how to achieve that.

**Comment by dom96** [comment]
There are different ways you can do it. Most event loops have a way to run things every x miliseconds, then you can call asyncdispatch.poll in that callback.

Another way is to do it the way I did it in this library https://github.com/dom96/notifications
