### ISSUE TITLE
Bind does not work with dot call syntax

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#15246]
I haven't written much Nim recently, so I hope I'm not doing anything stupid.

##### `lib.nim`

```nim
import os

template sourceBaseName*(): string =
  bind splitFile
  instantiationInfo().filename.splitFile().name
```

##### `user.nim`

```nim
import lib

echo sourceBaseName()
```

##### `$ nim c user.nim`

```
Hint: used config file '/home/fabian/bin/nim-repo/config/nim.cfg' [Conf]
Hint: used config file '/home/fabian/bin/nim-repo/config/config.nims' [Conf]
...................
/tmp/nimtest/user.nim(3, 20) template/generic instantiation of `sourceBaseName` from here
/tmp/nimtest/lib.nim(5, 31) Error: attempting to call undeclared routine: 'splitFile'
```

### Expected Output

Expected to compile because `lib.nim` explicitly does `bind splitFile`.

The code works if the user manually imports `os`, but my understanding was that the purpose of `bind` is to avoid that.

### Additional Information

I can't say for sure, but it could be a regression, because:
- I think I have used `bind` in that way before.
- NimData recently broke, because of https://github.com/brentp/nim-plotly/issues/63, which I also tried to fix using `bind`, but couldn't.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-08-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b5424b826e57c791a751bf31b69549c7d8daab0b
active boot switches: -d:release
```

**Comment by Araq** [comment]
Not sure either but please try it to call ``splitFile`` without the dot call syntax.

**Comment by bluenote10** [comment]
> please try it to call splitFile without the dot call syntax.

Yes that seems to work, so the problem is specific to dot call syntax.

**Comment by metagn** [comment]
Compiles as of 2.0
