### ISSUE TITLE
toHex results in RangeDefect exception when used with large uint64

### ISSUE THREAD

**Issue by VP8M8** [nim-lang/Nim#15257]
Function `toHex(x)` results in RangeDefect exception when used with a large uint64 in devel.

### Example
```nim
let bigInt = high(uint64)
echo bigInt.toHex
```

### Current Output
```
fatal.nim(49)            sysFatal
Error: unhandled exception: value out of range [RangeDefect]
```

### Expected Output
```
FFFFFFFFFFFFFFFF
```

### Possible Solution

* `toHex(x)` accepts SomeInteger but casts it to BiggestInt when internally calling `toHex(x, len)`. Probably that?

### Additional Information
Looks like a regression since the example works correctly in 1.2.6.

* Using Ubuntu 20.04 with GCC 9.3

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-09-01
```

**Comment by Araq** [comment]
Ah thanks!
