### ISSUE TITLE
s390x architecture support

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#15253]
The packaging guide mentions that Nim is "seldom tested" on s390x: https://github.com/nim-lang/Nim/blob/59c212607ee1982e810464e390daee38ef678c33/doc/packaging.rst#supported-architectures

This architecture is available on Travis on native hardware and is the only big endian architecture in CI services which makes it an attractive target for endian code.

However trying to build the csources on s390x will throw `Error: unknown processor: s390x`

Was this arch ever supported?

**Comment by FedericoCeratto** [comment]
@mratsim it was never included in platforms.nim - if there's interest I can try to add it and build it on a zSeries host I have access to.
