### ISSUE TITLE
typed does not check return type on a procedure with a static argument

### ISSUE THREAD

**Issue by gabbhack** [nim-lang/Nim#15269]
### Example
```nim
macro test(a: typed): untyped =
  discard

test:
  proc foo(a: int, b: static[string]): bool = 123
```

### Current Output
```
```
### Expected Output
```
Error: type mismatch: got <int literal(123)> but expected 'bool'
```

$ nim -v
```
Nim Compiler Version 1.2.6 [Windows: amd64]
Compiled at 2020-07-29
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bf320ed172f74f60fd274338e82bdc9ce3520dd9
active boot switches: -d:release
```

**Comment by Araq** [comment]
This is caused by the fact that ``static[string]`` means your ``foo`` is generic code. You don't instantiate it, hence the proc body isn't checked. In fact, that ``static[string]`` produces a generic is the desired behaviour because we want proc specialization to occur. So, no bug here.
