### ISSUE TITLE
No documentation for distinctBase

### ISSUE THREAD

**Issue by hugosenari** [nim-lang/Nim#15266]
Hi,

Nim Manual in [Distinct Types](https://nim-lang.org/docs/manual.html#types-distinct-type) mentions `distinctBase`.
> See also distinctBase to get the reverse operation.

Since I'm new here, I can't say if expected behavior would be:
1. No mention to distinctBase (deprecated feature).
2. A link or more information about distinctBase (new feature).

**Comment by juancarlospaco** [comment]
https://nim-lang.github.io/Nim/typetraits.html#distinctBase.t%2CT

**Comment by ringabout** [comment]
You can use search box to find `distinctbase`. 

![image](https://user-images.githubusercontent.com/43030857/93314329-32aac500-f83c-11ea-8f43-3d056f86c8b6.png)

Or use Ctrl + F(or similar operations) to search in theindex
https://nim-lang.org/docs/theindex.html

**Comment by Araq** [comment]
Direct link would be nice but it's not required.
