### ISSUE TITLE
Symbols lookup regression

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#15324]
Used to compile before:
### Example
```nim
import macros

var interesting_funcs {.compileTime.}: seq[NimNode] = @[]

macro interest(fns: varargs[typed]): typed =
  for fn in fns:
    interesting_funcs.add fn[0]

proc myproc(x: float): float {.interest.} =
  2*x

myproc(3.0)
```

Now fails on the last line with error: `undeclared identifier 'myproc'`

**Comment by cooldome** [comment]
Regression is caused by this change: https://github.com/nim-lang/Nim/commit/fb58066b61b14f4a1d6cdb0f4a8f0a9ea4174d82

@Clyybber please have a look

**Comment by Clyybber** [comment]
This is intended. Previously calling it would have just created cgen errors (at least with `fns: typed`, not sure if varargs elided the bug).

**Comment by Clyybber** [comment]
Adapted code would be:
```nim
import macros

var interesting_funcs {.compileTime.}: seq[NimNode] = @[]

macro interest(fns: varargs[typed]): typed =
  result = newNimNode(nnkStmtList)
  for fn in fns:
    interesting_funcs.add fn[0]
    result.add fn

proc myproc(x: float): float {.interest.} =
  2*x

echo myproc(3.0)
```
but this fails currently, due to a bug thats fixed with #15252

**Comment by cooldome** [comment]
Hi @Clyybber, 
cgen is not related at all.

The problem is that `myproc` now disappears from symbol list if you apply typed macro to it.
`interest` here plays a role of pragma that should not affect the visibility of the `myproc`.

This is simplified example that fails with the same error:
```nim
import macros

macro interest(fn: typed) =
  discard

proc myproc(x: float): float {.interest.} =
  2*x

myproc(3.0)
```

**Comment by Clyybber** [comment]
Yeah, this is intended. cgen is related because before my PR this would just call a proc that codegen would never encounter, thus generate invalid C code.

In this case the proc is generated anyways on older Nim (not sure why, I haven't investigated), but other cases like
```nim
import macros

macro interest(fn: typed) =
  discard

interest:
  var x = 1

echo x
```
show why the previous behaviour was broken.

**Comment by cooldome** [comment]
Agree you change is useful and I am not suggesting reverting it, but it has unintended consequences that we should fix. 

Possibly the issue is in the way sempass is handling pragmas:
```nim
proc p {.mymacro.}
```
internally is rewritten into:
```nim
mymacro:
  proc p
```
which is no the same from the scope handling point of view. 
Once you have fixed the scope handling the issue started to manifest itself.

**Comment by Clyybber** [comment]
Yeah, but this is how it should work I'm arguing. There is no bug here.

**Comment by cooldome** [comment]
Not sure I agree, for the  following use case yes it is clearly local function that can be swallowed:
```nim
mymacro:
  proc p
```
but this one, I believe is not what users expect
```nim
proc p* {.mymacro.}
```
you don't expect that pragma can make proc disappear, it is even exported function.

Anyway, it is more of design question. Let's get #15252 over the line that will help.

**Comment by Araq** [comment]
@cooldome we're about to release, is this really a bug that should block 1.4?

**Comment by cooldome** [comment]
Yes, absolutely. Please block the release. 
I am working hard to make it fixed asap

**Comment by jyapayne** [comment]
@cooldome is this fixed now with the merge of the above two fixes?

**Comment by Clyybber** [comment]
The original snippet adapted is, but @cooldome is still hitting issues in a different codebase. We will keep this open until they are fixed (The PR that caused this issue won't ship with 1.4, so it only affects devel)

**Comment by Araq** [comment]
What's the status of this bug?

**Comment by Clyybber** [comment]
IMO this can be closed. macro pragmas consuming the definition they are attached to is better and more consistent (untyped does the same) and is needed for typed async/cps macros.
