### ISSUE TITLE
default GC fails to call a finalizer

### ISSUE THREAD

**Issue by slonik-az** [nim-lang/Nim#15321]
In the following MWE nim's default GC fails to call the finalizer proc passed to `new`. 
When compiled with `--gc:arc` the finalizer is called as expected.

### MWE Example
```nim
# file mwe.nim
proc main() =
    type 
        Person = ref object
            name: string

    proc finalizerPerson(x: Person) =
        echo "finilizerPerson called on object:"
        echo "    ", x.repr
        echo "----"

    var p: Person
    new p, finalizerPerson
    p.name= "Douglas Adams"

main()
```

### Current Output
When compiled with default GC there is no output from the program 
```
$ nim c -d:release  mwe.nim
$ ./mwe
```
On the other hand, when compiled with ARC GC everything works as expected:
```
$ nim c -d:release --gc:arc -o:mwe-arc  mwe.nim
$ ./mwe-arc
finilizerPerson called on object:
    Person(name: Douglas Adams)
----
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.2.6 [MacOSX: amd64]
Compiled at 2020-09-02
Copyright (c) 2006-2020 by Andreas Rumpf
git hash: 211868b85cf8b11baabf06d75aaf7e2015d82e2b
active boot switches: -d:release
```
MacOS Mojave (10.14.6). CLang backend: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

**Comment by Araq** [comment]
No bug here, finalizers are a "best effort" thing. We all don't like it which is why we have ``--gc:arc`` and it's about the become the new default anytime soon now *cough*. ;-)
