### ISSUE TITLE
New comment syntax.

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1535]
Let's implement a new comment syntax for 0.10.0. Current syntax ``discard """ ... """`` is too ugly and too much hassle to write. It's about time I make this feature request official and create an issue for it. So here it is.

@Araq's suggestion on IRC was ``#[ ... ]#``.

Other possible contenders: ``### ... ###``, ``{- ... -}``, ``(* ... *)``.

Suggestions and discussion encouraged.

Also, let's be democratic: so in your reply tell us if you think this is a good idea or not with a unambiguous ``Yes`` or ``No``.

Forum discussion [here](http://forum.nimrod-lang.org/t/560).

**Comment by ReneSac** [comment]
I don't see the need of yet another syntax for comments, as both `discard """ """` and editor support for `#` seems sufficient for me (the last one has the advantage of being nestable). If I were to chose one of the suggested syntaxes, I prefer the `#[` ... `#]` suggested by fowlmouth. 

Is there a non-aesthetical reason for `#[` ... `]#` be preferred over the foulmouth suggestion? Not that aesthetical reasons aren't important (they seem to be the main reason for this RFC after all).

@gmpreussner: kate highlights `#if 0` for C, as that is basically another way to comment code. It is kinda equivalent to Nim's `when false`. But w/o compiler support it is difficult to know if a more complex expression also evaluates to false.

**Comment by erikenglund** [comment]
No

**Comment by Deco** [comment]
I think Nim should definitely have a multiple comment levels; Lua does and I find it to really help with productivity.
In C, you can't nest multiline comments `/* /*  */ */`.
In Lua, you can't nest but you can introduce a new comment level like so `--[===[ outer --[[ inner ]] outer --]===]`. The parser doesn't see `--[[ inner ]]` as a nested comment, it just treats it as a comment.
Because the outer comment started with three `=` symbols, it won't end the comment until it sees `--]===]`.
How about, for nim:
```Nimrod
code
broken code 1
#[
commented code A
#]
broken code 2
```
In C/C++, you'd need to individual comment the broken code sections, or remove the multiline comment terminator of `commented code A`.
Proposed solution:
```Nimrod
code
#[[
commented broken code 1
#[
commented code A
#]
commented broken code 2
#]]
```

I suggest the terminator be `#]` rather than `]#`, otherwise it may be written accidentally:
```Nimrod
a[0] = b[0]
#[
a[1] = b[1]# this is a comment, note that it accidentally terminates the comment!
a[2] = b[2]
]#
a[3] = b[3]
```

Also +1 for `##[ ... ##]` being a doc-comment!

**Comment by keyle** [comment]
Why does a language need multi-line comments? :-1: 

```
# this is
# quite clean
# and IDEs
# won't mess it up

if ## indicates a documentation comment

### should
start a multiple line 
comment? ###
```

although clever, ### could get out of hand.

**Comment by crashoverdrive** [comment]
Single line comments makes for better code documentation. The present syntax is alright.

**Comment by Varriount** [comment]
Since there seems to be an abundance of opinions on this subject, I propose that anyone who really wants another comment type write up something akin to Python's PEP's, rather than simply stating opinion.

**Comment by oderwat** [comment]
I mainly need inline comments. Don't care about multiline to much but `#[  ]#` serves both. Done.

**Comment by EXetoC** [comment]
@keyle Araq has said that modern tools should be embraced, which I agree with, and programmers really ought to rely on capable editors. I'm not sure where the line is drawn though, but batch commenting doesn't exactly rely on complex technology.

**Comment by bluenote10** [comment]
Yes for `#[ ... ]#`. The big advantage over `"""` or `###`: Even without syntax highlighting one can easily distinguish between the start and the end of a comment. In contrast to:

    """ """
    """"""
    """ ""
    "" """"""
    """

I do like multiline comments in cases where I want complete text editor freedom for documentation purposes. Some advantages of multiline comments:

- Much easier modification of text wrapping. Image you want to change the comments text wrap width from 120 characters to 80. Typically the repeated line prefixes `#` of single line comments makes both manual and automatic text wrapping more difficult to edit.
- Easier copy/past within doc strings. Imaging copy/pasting multiline console output in a `should output:` example into doc string.
- For some IDEs/editors the features for automatic inserting/extension of single-line comments often do not exactly what I want. To be fair: If I write a single comment, it is impossible for an editor to guess if I want to continue writing a comment in the next line.

**Comment by BlaXpirit** [comment]
I 100% agree with @Deco's comment which shows that `#[` `]#` is completely non-viable. I vote for `#[` `#]`, nestable like shown by @Deco.

**Comment by yglukhov** [comment]
I've suddenly seen some scala example that brought me to the following "why nots":
```
#!/bin/sh
echo This is a shell script.
echo Also this happens to be a multiline comment :-P
# Why not install nim if it's not installed here %)
!#
echo "This is a nim program"
#! another comment here. #! Also why not nest them !# !#
```

**Comment by kirbyfan64** [comment]
@yglukhov Scala is an excellent example of what not to do. :)

Really, though, I think this needs to be in Nim before 1.0. `discard """""` gets annoying quickly, especially when what you're trying to comment out triple quotes.

**Comment by rbehrends** [comment]
@kirbyfan64 What I'm still not seeing for this particular use case is why this isn't something that an editor cannot do for you. I hit `Command-/` in TextMate or `,c` in Vim, and I'm done. Incidentally, if you're using Vim and need it for that, here are some convenient bindings:

```vim
map ,c :Comment<CR>
map ,u :Uncomment<CR>

com! -range Comment <line1>,<line2>s/^/# /
com! -range Uncomment <line1>,<line2>s/^# //
```

The other use case where you may need comments with a begin and end are inline comments, e.g. something like this (borrowing Haskell syntax for inline comments):

```nim
proc foo(arg1: Type1 {-comment1-}, arg2: Type2 {-comment2-}) = ...
```

I'd argue that this is a much less important use case and can easily wait until after 1.0.

**Comment by kirbyfan64** [comment]
Yeah, IDEs can definitely do it. Which is great.

When you use an IDE.

**Comment by rbehrends** [comment]
@kirbyfan64 I do not use an IDE. Any editor more advanced than edlin should be able to do it.

**Comment by oderwat** [comment]
I still really just want some inline comments... block and line comments are simply not enough. And comments should nest.  #[ ... #[ ... #]  #[ ... #] ... #]...

**Comment by reactormonk** [comment]
@oderwat Give me a use case.

**Comment by oderwat** [comment]
```nim
proc doSomething(a,b,c: int) = ...doit...

doSomething(1543231#[1544291#]#[996584#],"bla"#["blub"#],3#[or any prime#])
```

```nim
let x=y*1.14[#was 1.16 till yesterday#]*123.4#[should be calculated#]+100
let z=doSomething#[or doOtherthing#](1,2,3)
```

```nim
#[ need to fix that proc
proc ohMy(y: float): float =
  y*1.14[#was 1.16 till yesterday#]*123.4#[should be calculated but how?#]+100
#]
proc ohMy(y: float): float = 1234.5 # just use that for now
```

**Comment by Araq** [comment]
I think now that the lack of inline comments is against Nim's design philosophy. We support ``foo x, y``, ``x.foo y`` etc and yet cannot have 2 ways to write comments? That's just weird. While I personally don't need more comment syntaxes, others request inline comments and so we should introduce these:

```nim
#[comment here]
#[[comment here]]
#[[[comment here]]]
#[[[[comment here]]]]
```

With the level of [] up to 4. This means that regex based syntax highlighters can still process them properly (it adds 4 new regexes to the highlighter) and yet is flexible enough to allow for nesting in practice as well as crazy stuff like

```nim
code here
#]]] # end marker here left for easy code section deactivations
```

**Comment by Araq** [comment]
Implemented multi-line comments.

**Comment by dom96** [comment]
For reference: the syntax for multi-line comments we settled on is ``#[ ...
]#`` not ``#[ ... ]``. They also should be nestable :)
