### ISSUE TITLE
The decodeData Iterator from cgi module crash

### ISSUE THREAD

**Issue by mrhdias** [nim-lang/Nim#15369]
The decodeData Iterator from cgi module crash if '=' is not present in a key instead of continuing decoding (please look at Additional Information)!

### Example
```nim
from cgi import decodeData

let queryString = "a=1&b=0&c=3&d&e&a=5&a=t%20e%20x%20t&e=http%3A%2F%2Fw3schools.com%2Fmy%20test.asp%3Fname%3Dst%C3%A5le%26car%3Dsaab"

for pair in decodeData(queryString):
  echo pair
```

### Current Output
```
Hint: /home/hdias/Work/Development/kiss/examples/test  [Exec]
(key: "a", value: "1")
(key: "b", value: "0")
(key: "c", value: "3")
/usr/local/programs/x86_64/nim-1.2.6/lib/pure/cgi.nim(108) test
/usr/local/programs/x86_64/nim-1.2.6/lib/pure/cgi.nim(67) cgiError
Error: unhandled exception: '=' expected [CgiError]
Error: execution of an external program failed: '/home/hdias/Work/Development/kiss/examples/test '
```

### Expected Output
```
(key: "a", value: "1")
(key: "b", value: "0")
(key: "c", value: "3")
(key: "d", value: "")
(key: "e", value: "")
(key: "a", value: "5")
(key: "a", value: "t e x t")
(key: "e", value: "http://w3schools.com/my test.asp?name=ståle&car=saab")
```

### Additional Information

Copy & Paste:
http://127.0.0.1:8080/fcgi/testget?a=1&b=0&c=3&d&e&a=5&a=t%20e%20x%20t&e=http%3A%2F%2Fw3schools.com%2Fmy%20test.asp%3Fname%3Dst%C3%A5le%26car%3Dsaab

To test:
https://www.freeformatter.com/url-parser-query-string-splitter.html

```
$ nim -v
Nim Compiler Version 1.2.6 [Linux: amd64]
Compiled at 2020-07-29
```

**Comment by Araq** [comment]
Can you please give me a link to the spec that mentions how to interpret a key value pair without an '='?

**Comment by ghost** [comment]
@Araq 
https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value
https://tools.ietf.org/html/rfc3986#section-3.4

Seems like there's no actual "spec" for the URL query as-is.

Key only pairs not disallowed by the spec (but it mentions that people usually use the key=value syntax), and apparently they are used by some people, but I'm not sure if it would be okay to parse them as keys with empty values

**Comment by mrhdias** [comment]
There is no definitive standard, most web frameworks allow key's syntax without an '=''

PHP:
https://www.w3schools.com/php/phptryit.asp?filename=tryphp_func_string_parse_str

```pho
<!DOCTYPE html>
<html>
<body>

<?php
parse_str("name=Peter&age=43&test&abc=1");
echo $name."<br>";
echo $age . "<br>";
echo $test . "<br>";
echo $abc;
?>
 
</body>
</html>
?>
 
</body>
</html>
```

**Comment by mrhdias** [comment]
Thanks for fixing the issue.
