### ISSUE TITLE
toSeq does not work with UFCS when using iterators

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#15373]
`toSeq` does not work with UFCS when using iterators but does work when on the outside.

### Example
```nim
import sequtils

iterator kmers*(x: string, k: Positive): string =
  ## Yields all of the *k*-mers in a given string.
  for i in 0..(x.len - k):
    yield x[i ..< i + k]
echo toSeq(kmers("ATGCA", 3)) # works => @["ATG", "TGC", "GCA"]
echo kmers("ATGCA", 3).toSeq() # doesn't work => Error: attempting to call routine: 'kmers'
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
Error: attempting to call routine: 'kmers'
  found 'example.kmers(x: string, k: Positive) [declared in example.nim(14, 10)]' of kind 'iterator'```
```

### Expected Output
```nim
@["ATG", "TGC", "GCA"]
```

### Possible Solution

* No idea, frankly. I looked at the source code but am not sure I fully understand it.

### Additional Information

The old [0.11.0 docs](https://nim-lang.org/0.11.0/sequtils.html#toSeq.t,expr) mention that you cannot always invoke it as `x.toSeq()` but the [current docs](https://nim-lang.org/docs/sequtils.html#toSeq.t%2Cuntyped) don't mention anything.

```
$ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-04-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by Benjamin-Lee** [comment]
Just as a follow up, using a closure iterator for `kmers` compiles but does not run:

```nim
proc kmers*(x: string, k: Positive): auto =
  return iterator: string =
    ## Yields all of the *k*-mers in a given string.
    for i in 0..(x.len - k):
      yield x[i ..< i + k]
echo toSeq(kmers("ATGCA", 3))
echo kmers("ATGCA", 3).toSeq()
```

yields:

```
~/D/P/R/example ❯❯❯ ./src/example
example.nim(19) example
/usr/local/Cellar/nim/1.2.0/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 3 not in 0 .. 2 [IndexError]
```

**Comment by bluenote10** [comment]
Perhaps related to https://github.com/nim-lang/Nim/issues/15246?

**Comment by Clyybber** [comment]
https://github.com/nim-lang/Nim/pull/14863 should fix this.

**Comment by metagn** [comment]
This is literally in the manual: https://nim-lang.org/docs/manual.html#templates-limitations-of-the-method-call-syntax. There is nothing to be done here, except maybe about the fact that the closure iterator behavior is odd.

**Comment by Araq** [comment]
It's annoying, it's well documented, it'll work eventually, it's been reported elsewhere. Closing.

**Comment by Benjamin-Lee** [comment]
Thanks for pointing that out; I hadn't seeing it. At the very least, can we get this documented again in sequtils? The reason I reported it as a bug was that its removal from the docs led me to believe it was a regression. 

From a higher level, is there an issue on the tracker for this limitation?
