### ISSUE TITLE
Wrapping IndexedDB API

### ISSUE THREAD

**Issue by sdmcallister** [nim-lang/Nim#15396]
### Summary

Wrap IndexedDB api in the dom library (or as separate library).

### Description

Alternative to localstorage api and a standard api for clientside storage.   Used often for offline first web applications (pwas). 

### Alternatives

Other options like local storage/cookies have storage size limitations. 
Web sql is being deprecated as far as I'm aware.

### Additional Information

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

**Comment by Araq** [comment]
Report it here instead: https://github.com/nim-lang/needed-libraries
