### ISSUE TITLE
Update MinGW related info and packages

### ISSUE THREAD

**Issue by VP8M8** [nim-lang/Nim#15391]
Both on the [Nim website](https://nim-lang.org/install_windows.html) and [Github readme](https://github.com/nim-lang/Nim) the recommended Windows compiler is listed as MinGW. I downloaded the provided zip files from the Nim website but they are actually MinGW-W64, not MinGW. MinGW-W64 forked from MinGW over a decade ago to improve compatibly and provide the ability to compile 64 bit executables. The Github page insists "MinGW 4.3.0 (GCC 8.10) is the minimum recommended compiler", yet the MinGW-W64 version provided on the Nim website is GCC 6.3.0. The latest provided versions (GCC 8.1.0) can be found on their [SourceForge readme](https://sourceforge.net/projects/mingw-w64/files/) as [x86_64-win32-seh](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z) and [i686-win32-dwarf](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/dwarf/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z). Whoever added the information to begin with probably just abbreviated the name but seeing as they're two independent projects I think clarification (and credit) is due. 

I asked on the MinGW-W64 IRC for updated Windows binaries and, while I wasn't the only one asking, they basically said to compile it yourself or use the binaries from MSYS2 which are tested.

**Comment by zeitbit** [comment]
If you want to use the latest version of GCC (Windows, 32 and 64 bits) I recommend you: http://winlibs.com

**Comment by VP8M8** [comment]
I asked on the [closed ticket](https://github.com/brechtsanders/winlibs_mingw/issues/1) about getting the build scripts. As much as I would like to, I don't think telling your users to use a compiler from some random person on the internet is a good idea. Ideally it should be provided by upstream but I think MSYS2 or being compiled by the main Nim devs are also fine.

**Comment by VP8M8** [comment]
I checked the Nim website and the Windows mingw 7zipped binaries were updated to gcc-11.1.0-mingw-w64-8.0.2-r1 (MinGW-W64 x86_64-posix-seh and i686-posix-dwarf). Seeing as the decision has been made to use [winlabs.com](https://winlibs.com/) binaries, I suggest updating them to the [latest version](https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-ucrt-r3). On the [Windows Installation page](https://nim-lang.org/install_windows.html) the manual installation zip files have SHA256 links. Posting SHA256 links for the mingw files should be considered for additional integrity and consistency.

I opened an [issue](https://github.com/nim-lang/website/issues/320) in the website repo for the SHA265 file.

**Comment by VP8M8** [comment]
The SHA256 files were added to the website but MinGW wasn't updated to GCC 11.2.0. It's still much better than the previous 6.3.0, so I'll close this.
