### ISSUE TITLE
Deepcopy in arc crashes

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#15405]
Deepcopy recently appeared  for arc runtime, first test results.
Test case:
```nim
import lexbase, streams
const test = "<A><B>value</B></A>"
var stream = newStringStream(test)
var lex: BaseLexer
open(lex, stream)
var lex2 = deepCopy(lex)
```
Crashes on the nil pointer dereference with stacktrace:
```nim
C:\Nim\t8.nim(24)        t8
C:\Nim\lib\system.nim(2881) deepCopy
C:\Nim\lib\system\deepcopy.nim(192) genericDeepCopy
C:\Nim\lib\system\deepcopy.nim(130) genericDeepCopyAux
C:\Nim\lib\system\deepcopy.nim(72) genericDeepCopyAux
C:\Nim\lib\system\deepcopy.nim(68) genericDeepCopyAux
C:\Nim\lib\system\deepcopy.nim(168) genericDeepCopyAux
```

I have done a bit of investigation.: `.typeInfoV1` member is nil for the `NTIv2` struct of the `StringStreamObj` object.

`typeInfoV1` is not nil for `StreamObj` which is inheritance base for `StringStreamObj`. AFAIK,  `genTypeInfoV1` codegen is done only for type `BaseLexer` that includes reference to  `StreamObj`. Because `StringStreamObj` is not directly referenced, `genTypeInfoV1` is not executed for it.

**Comment by cooldome** [comment]
I don't see how you can get all child objects of the given base object to fix it.

**Comment by Araq** [comment]
The compiler has no such data-structure that would allow for that. :-)

**Comment by cooldome** [comment]
Any idea how it can be fixed? running  `genTypeInfoV1` for all inheritable objects?

**Comment by Araq** [comment]
Seems like ``genTypeInfoV2`` is missing a simple loop over the parent objects.

**Comment by cooldome** [comment]
IMO, in arc mode `genTypeInfoV1` is executed only from `genDeepCopy`. At least this is what I see. 
`StringStreamObj` is not reachable from `genDeepCopy`. 

Unless we start calling `genTypeInfoV1` from `genTypeInfoV2` I don't see how to reach `StringStreamObj`.
Are you ok with such fix?

**Comment by Araq** [comment]
That means we always get the V1 type info bloat. Thinking about a better way...

**Comment by Araq** [comment]
There is a good workaround which IMO we should officially document:

```nim

template enableDeepCopy(x) =
  discard getTypeInfo(x)

import parsexml, streams
const test_xml_str = "<A><B>value</B></A>"
var stream = newStringStream(test_xml_str)
enableDeepCopy(stream)
var xml: XmlParser
open(xml, stream, "test")
var xml2 = deepCopy(xml)
```

**Comment by cooldome** [comment]
Workaround doesn't work if you don't have accesss to internals of the objects. Imagine you have only `XmlParser` and its content is opaque and contains non exported refs to objects.
This won't work:
```nim
var xml: XmlParser
enableDeepCopy(xml)
```
You need to do:
```nim
enableDeepCopy(xml.f1)  # but f1 is not exported and its type is not exported either
enableDeepCopy(xml.f2)  # but f2 is not exported and its type is not exported either
```
Also xnk f1 can contain ref to base type not the actual type you want to be enabled.

**Comment by Araq** [comment]
The question is: Does the workaround work for you?

**Comment by cooldome** [comment]
It helps me to progress in arc adoption. It helps with the deecopies in the parsers, there is one more deepcopy that will be hard to workaround like that but my code crashes before this step, investigating.

**Comment by SFR0815** [comment]
I have seen deepCopy crashing in the following code:

Module "element.nim":
`
type
  Element* = ref object of RootObj
    is_null: bool
    name: string
    content_description: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)
    getInt_Impl: proc(element: Element): int
    setInt_Impl: proc(element: Element, value: int)
    resetElement_Impl: proc(element: Element)

# Element content definition:
proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string),
            getInt_Impl: proc(element: Element): int,
            setInt_Impl: proc(element: Element, value: int),
            resetElement_Impl: proc(element: Element)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl
  element.getInt_Impl = getInt_Impl
  element.setInt_Impl = setInt_Impl
  element.resetElement_Impl = resetElement_Impl

# Element procs
proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc getInt*(element: Element): int =
  return element.getInt_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)
proc `value =`*(element: Element, value: int) =
  element.setInt_Impl(element, value)
proc resetElement*(element: Element) =
  element.resetElement_Impl(element)

proc `is_null`*(element: Element): bool =
  return element.is_null
proc `is_null =`*(element: Element, is_null: bool) =
  element.is_null = is_null
proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
proc `content_description`*(element: Element): string =
  return element.content_description
proc `content_description =`*(element: Element, content_description: string) =
  element.content_description = content_description
`
module "spec_element.nim":
`import ./element

export element

type
  StringElement* = ref object of Element
    value: string

const
  c_string_default = ""

proc getString_Impl_StringElement(element: Element): string =
  return element.StringElement().value
proc setString_Impl_StringElement(element: Element, value: string) =
  element.StringElement().value = value
proc getInt_Impl_StringElement(element: Element): int =
  raise newException(ValueError, "No int output permissible for StringElements")
proc setInt_Impl_StringElement(element: Element, value: int) =
  raise newException(ValueError, "No int input permissible for StringElements")
proc resetElement_Impl_StringElement(element: Element) =
  element.setString_Impl_StringElement(c_string_default)
  `is_null =`(element.StringElement(), true)

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl_StringElement,
              setString_Impl = setString_Impl_StringElement,
              getInt_Impl = getInt_Impl_StringElement,
              setInt_Impl = setInt_Impl_StringElement,
              resetElement_Impl = resetElement_Impl_StringElement)
  result.resetElement()
  `content_description =`(result, "string")
  `name =`(result, name)
`
module "main.nim"
`import ./spec_element

let element_1: Element = newStringElement("element_1")

let copy_element_1 = element_1.deepCopy()

echo copy_element_1.name`

Without --gc:arc it works fine - with --gc:arc it crashes with

main.nim(5) main
system.nim(2908) deepCopy
deepcopy.nim(190) genericDeepCopy
deepcopy.nim(166) genericDeepCopyAux

If you put the code all together in one module, it works fine even with --gc:arc 

`type
  ElementPrcs* = ref object of RootObj
    getString_Impl: proc(element: ElementPrcs): string
    setString_Impl: proc(element: ElementPrcs, value: string)
    getInt_Impl: proc(element: ElementPrcs): int
    setInt_Impl: proc(element: ElementPrcs, value: int)
    resetElement_Impl: proc(element: ElementPrcs)
  Element* = ref object of ElementPrcs
    is_null: bool
    name: string
    content_description: string
  StringElement* = ref object of Element
    value: string

const
  c_string_default = ""

# ElementPrcs content definition:
proc setElementDefinitions*(
            element: ElementPrcs,
            getString_Impl: proc(element: ElementPrcs): string,
            setString_Impl: proc(element: ElementPrcs, value: string),
            getInt_Impl: proc(element: ElementPrcs): int,
            setInt_Impl: proc(element: ElementPrcs, value: int),
            resetElement_Impl: proc(element: ElementPrcs)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl
  element.getInt_Impl = getInt_Impl
  element.setInt_Impl = setInt_Impl
  element.resetElement_Impl = resetElement_Impl

# ElementPrcs procs
proc getString*(element: ElementPrcs): string =
  return element.getString_Impl(element)
proc getInt*(element: ElementPrcs): int =
  return element.getInt_Impl(element)
proc `value =`*(element: ElementPrcs, value: string) =
  element.setString_Impl(element, value)
proc `value =`*(element: ElementPrcs, value: int) =
  element.setInt_Impl(element, value)
proc resetElement*(element: ElementPrcs) =
  element.resetElement_Impl(element)

# Element procs
proc `is_null`*(element: Element): bool =
  return element.is_null
proc `is_null =`*(element: Element, is_null: bool) =
  element.is_null = is_null
proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
proc `content_description`*(element: Element): string =
  return element.content_description
proc `content_description =`*(element: Element, content_description: string) =
  element.content_description = content_description

# StringElement specification
proc getString_Impl_StringElement(element: ElementPrcs): string =
  return element.StringElement().value
proc setString_Impl_StringElement(element: ElementPrcs, value: string) =
  element.StringElement().value = value
proc getInt_Impl_StringElement(element: ElementPrcs): int =
  raise newException(ValueError, "No int output permissible for StringElements")
proc setInt_Impl_StringElement(element: ElementPrcs, value: int) =
  raise newException(ValueError, "No int input permissible for StringElements")
proc resetElement_Impl_StringElement(element: ElementPrcs) =
  element.setString_Impl_StringElement(c_string_default)
  `is_null =`(element.StringElement(), true)

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl_StringElement,
              setString_Impl = setString_Impl_StringElement,
              getInt_Impl = getInt_Impl_StringElement,
              setInt_Impl = setInt_Impl_StringElement,
              resetElement_Impl = resetElement_Impl_StringElement)
  result.resetElement()
  `content_description =`(result, "string")
  `name =`(result, name)

let element_1 = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name`

**Comment by SFR0815** [comment]
I got a crash as follows:

element.nim:

`afaf`
`afafa445


`

**Comment by SFR0815** [comment]
With me deepCopy crashed as follows using --gc:arc:

element.nim:

```
type
  Element* = ref object of RootObj
    is_null: bool
    name: string
    content_description: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)
    getInt_Impl: proc(element: Element): int
    setInt_Impl: proc(element: Element, value: int)
    resetElement_Impl: proc(element: Element)

proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string),
            getInt_Impl: proc(element: Element): int,
            setInt_Impl: proc(element: Element, value: int),
            resetElement_Impl: proc(element: Element)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl
  element.getInt_Impl = getInt_Impl
  element.setInt_Impl = setInt_Impl
  element.resetElement_Impl = resetElement_Impl

proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc getInt*(element: Element): int =
  return element.getInt_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)
proc `value =`*(element: Element, value: int) =
  element.setInt_Impl(element, value)
proc resetElement*(element: Element) =
  element.resetElement_Impl(element)

proc `is_null`*(element: Element): bool =
  return element.is_null
proc `is_null =`*(element: Element, is_null: bool) =
  element.is_null = is_null
proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
proc `content_description`*(element: Element): string =
  return element.content_description
proc `content_description =`*(element: Element, content_description: string) =
  element.content_description = content_description

```

**Comment by SFR0815** [comment]
With me deepCopy crashed as follows using --gc:arc:

element.nim:
```
type
  Element* = ref object of RootObj
    is_null: bool
    name: string
    content_description: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)
    getInt_Impl: proc(element: Element): int
    setInt_Impl: proc(element: Element, value: int)
    resetElement_Impl: proc(element: Element)

proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string),
            getInt_Impl: proc(element: Element): int,
            setInt_Impl: proc(element: Element, value: int),
            resetElement_Impl: proc(element: Element)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl
  element.getInt_Impl = getInt_Impl
  element.setInt_Impl = setInt_Impl
  element.resetElement_Impl = resetElement_Impl

proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc getInt*(element: Element): int =
  return element.getInt_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)
proc `value =`*(element: Element, value: int) =
  element.setInt_Impl(element, value)
proc resetElement*(element: Element) =
  element.resetElement_Impl(element)

proc `is_null`*(element: Element): bool =
  return element.is_null
proc `is_null =`*(element: Element, is_null: bool) =
  element.is_null = is_null
proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
proc `content_description`*(element: Element): string =
  return element.content_description
proc `content_description =`*(element: Element, content_description: string) =
  element.content_description = content_description
```
spec_element.nim: 
```
import ./element

export element

type
  StringElement* = ref object of Element
    value: string

const
  c_string_default = ""

proc getString_Impl_StringElement(element: Element): string =
  return element.StringElement().value
proc setString_Impl_StringElement(element: Element, value: string) =
  element.StringElement().value = value
proc getInt_Impl_StringElement(element: Element): int =
  raise newException(ValueError, "No int output permissible for StringElements")
proc setInt_Impl_StringElement(element: Element, value: int) =
  raise newException(ValueError, "No int input permissible for StringElements")
proc resetElement_Impl_StringElement(element: Element) =
  element.setString_Impl_StringElement(c_string_default)
  `is_null =`(element.StringElement(), true)

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl_StringElement,
              setString_Impl = setString_Impl_StringElement,
              getInt_Impl = getInt_Impl_StringElement,
              setInt_Impl = setInt_Impl_StringElement,
              resetElement_Impl = resetElement_Impl_StringElement)
  result.resetElement()
  `content_description =`(result, "string")
  `name =`(result, name)
```
main.nim:
```
import ./spec_element

let element_1: Element = newStringElement("element_1")

let copy_element_1 = element_1.deepCopy()

echo copy_element_1.name
```

Results in 
main.nim(5) main
\system.nim(2908) deepCopy
\system\deepcopy.nim(190) genericDeepCopy
\system\deepcopy.nim(166) genericDeepCopyAux

There is no issue if you put it all together in one module though. 
```
type
  ElementPrcs* = ref object of RootObj
    getString_Impl: proc(element: ElementPrcs): string
    setString_Impl: proc(element: ElementPrcs, value: string)
    getInt_Impl: proc(element: ElementPrcs): int
    setInt_Impl: proc(element: ElementPrcs, value: int)
    resetElement_Impl: proc(element: ElementPrcs)
  Element* = ref object of ElementPrcs
    is_null: bool
    name: string
    content_description: string
  StringElement* = ref object of Element
    value: string

const
  c_string_default = ""

# ElementPrcs content definition:
proc setElementDefinitions*(
            element: ElementPrcs,
            getString_Impl: proc(element: ElementPrcs): string,
            setString_Impl: proc(element: ElementPrcs, value: string),
            getInt_Impl: proc(element: ElementPrcs): int,
            setInt_Impl: proc(element: ElementPrcs, value: int),
            resetElement_Impl: proc(element: ElementPrcs)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl
  element.getInt_Impl = getInt_Impl
  element.setInt_Impl = setInt_Impl
  element.resetElement_Impl = resetElement_Impl

# ElementPrcs procs
proc getString*(element: ElementPrcs): string =
  return element.getString_Impl(element)
proc getInt*(element: ElementPrcs): int =
  return element.getInt_Impl(element)
proc `value =`*(element: ElementPrcs, value: string) =
  element.setString_Impl(element, value)
proc `value =`*(element: ElementPrcs, value: int) =
  element.setInt_Impl(element, value)
proc resetElement*(element: ElementPrcs) =
  element.resetElement_Impl(element)

# Element procs
proc `is_null`*(element: Element): bool =
  return element.is_null
proc `is_null =`*(element: Element, is_null: bool) =
  element.is_null = is_null
proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
proc `content_description`*(element: Element): string =
  return element.content_description
proc `content_description =`*(element: Element, content_description: string) =
  element.content_description = content_description

# StringElement specification
proc getString_Impl_StringElement(element: ElementPrcs): string =
  return element.StringElement().value
proc setString_Impl_StringElement(element: ElementPrcs, value: string) =
  element.StringElement().value = value
proc getInt_Impl_StringElement(element: ElementPrcs): int =
  raise newException(ValueError, "No int output permissible for StringElements")
proc setInt_Impl_StringElement(element: ElementPrcs, value: int) =
  raise newException(ValueError, "No int input permissible for StringElements")
proc resetElement_Impl_StringElement(element: ElementPrcs) =
  element.setString_Impl_StringElement(c_string_default)
  `is_null =`(element.StringElement(), true)

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl_StringElement,
              setString_Impl = setString_Impl_StringElement,
              getInt_Impl = getInt_Impl_StringElement,
              setInt_Impl = setInt_Impl_StringElement,
              resetElement_Impl = resetElement_Impl_StringElement)
  result.resetElement()
  `content_description =`(result, "string")
  `name =`(result, name)

let element_1 = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name
```

**Comment by SFR0815** [comment]
My issue with deepCopy is as follows:
1. element.nim:
```
type
  Element* = ref object of RootObj
    name: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)

proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl

proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)

proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
```
2. spec_element.nim:
```
import ./element

export element

type
  StringElement* = ref object of Element
    value: string

proc getString_Impl(element: Element): string =
  return element.StringElement().value
proc setString_Impl(element: Element, value: string) =
  element.StringElement().value = value

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl,
              setString_Impl = setString_Impl)
  `name =`(result, name)

let element_1 = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name
```
3. main.nim:
```
import ./spec_element

let element_1: Element = newStringElement("element_1")

discard element_1.deepCopy()
```
Works smoothly without --gc:arc

With --gc:arc is results in 
```
system.nim(2908) deepCopy
system\deepcopy.nim(190) genericDeepCopy
system\deepcopy.nim(166) genericDeepCopyAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Putting it all together in one module:
```
type
  Element = ref object of RootObj
    name: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)
  StringElement = ref object of Element
    value: string

proc setElementDefinitions(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl

proc getString(element: Element): string =
  return element.getString_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)

proc `name`(element: Element): string =
  return element.name
proc `name =`(element: Element, name: string) =
  element.name = name

proc getString_Impl(element: Element): string =
  return element.StringElement().value
proc setString_Impl(element: Element, value: string) =
  element.StringElement().value = value

proc newStringElement(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl,
              setString_Impl = setString_Impl)
  `name =`(result, name)

let element_1 = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name
```
Works with --gc:arg as well ...

**Comment by SFR0815** [comment]
I have come across an issue as follows:
1. element.nim
```
type
  Element* = ref object of RootObj
    name: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)

proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl

proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)

proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
```
2. spec_element.nim:
```
ype
  Element* = ref object of RootObj
    name: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)

proc setElementDefinitions*(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl

proc getString*(element: Element): string =
  return element.getString_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)

proc `name`*(element: Element): string =
  return element.name
proc `name =`*(element: Element, name: string) =
  element.name = name
```
3. main.nim:
```
import ./spec_element

let element_1: Element = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name
```
Works without --gc:arc and crashes with. 

If you put all together into one module is works with AND without --gc:arc:
```
type
  Element = ref object of RootObj
    name: string
    getString_Impl: proc(element: Element): string
    setString_Impl: proc(element: Element, value: string)
  StringElement = ref object of Element
    value: string

proc setElementDefinitions(
            element: Element,
            getString_Impl: proc(element: Element): string,
            setString_Impl: proc(element: Element, value: string)) =
  element.getString_Impl = getString_Impl
  element.setString_Impl = setString_Impl

proc getString(element: Element): string =
  return element.getString_Impl(element)
proc `value =`*(element: Element, value: string) =
  element.setString_Impl(element, value)

proc `name`(element: Element): string =
  return element.name
proc `name =`(element: Element, name: string) =
  element.name = name

proc getString_Impl(element: Element): string =
  return element.StringElement().value
proc setString_Impl(element: Element, value: string) =
  element.StringElement().value = value

proc newStringElement(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl,
              setString_Impl = setString_Impl)
  `name =`(result, name)

let element_1 = newStringElement("element_1")

let element_2 = element_1.deepCopy()

echo element_2.name
```

**Comment by SFR0815** [comment]
Sorry, 

messed up #2 above. Should be as follows:

2. spec_element.nim:
```
import ./element

export element

type
  StringElement* = ref object of Element
    value: string

proc getString_Impl(element: Element): string =
  return element.StringElement().value
proc setString_Impl(element: Element, value: string) =
  element.StringElement().value = value

proc newStringElement*(name: string = ""): StringElement =
  result.new()
  result.setElementDefinitions(
              getString_Impl = getString_Impl,
              setString_Impl = setString_Impl)
  `name =`(result, name)
```
