### ISSUE TITLE
{.compileTime.} variables' values do not get transitioned over to runtime

### ISSUE THREAD

**Issue by liquidev** [nim-lang/Nim#15441]
The runtime value of {.compileTime.} variables gets initialized to whatever the initial value was when the variable was declared, instead of the value during the variable's last usage.

### Example
```nim
import tables

var
  i {.compileTime.} = 0
  s {.compileTime.}: seq[int]
  t {.compileTime.}: Table[string, int]

static:
  i.inc
  s.add [1, 2, 3]
  t["a"] = 1
  t["b"] = 2
  t["c"] = 3
  echo i
  echo s
  echo t
echo i
echo s
echo t
```

### Current Output
```
0
@[]
{:}
```

### Expected Output
```
1
@[1, 2, 3]
{"b": 2, "c": 3, "a": 1}
```

### Additional Information

```
Nim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-09-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: eb2a4961c71029c874ebdacd1b23a349eb8e61d5
active boot switches: -d:release
```

**Comment by Vindaar** [comment]
Pretty sure there were related issues in the past.

In general the "workaround" (if one wants to call it that) is to assign the compile time variable to a `const` once the computation at CT is done. 
In my opinion it makes some sense, that a `{.compileTime.}` variable is _not_ automatically a constant at RT. 

As mentioned on IRC:
```nim
import tables

var
  t {.compileTime.}: Table[string, int]

static:
  t["a"] = 1
  t["b"] = 2
  t["c"] = 3
  echo t
const tRt = t
echo tRt
```

**Comment by metagn** [comment]
Wasn't this an intended change made recently? It's weird because I can't find it in changelogs.

**Comment by mratsim** [comment]
Duplicate https://github.com/nim-lang/Nim/issues/13375
