### ISSUE TITLE
setControlCHook(nil) disables registered quit procs

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1546]
The following example program running on OSX with 0.9.4 shows the unexpected behaviour of previously registered quit procs not being run:

``` nimrod
proc oneQuitProc() {.noconv.} = echo "\toneQuitProc"
proc anotherQuitProc() {.noconv.} = echo "\tanotherQuitProc"

proc didGetControlC() {.noconv.} =
  echo "\nGot Ctrl+C, dying!"
  quit()

proc test() =
  addQuitProc(oneQuitProc)
  addQuitProc(anotherQuitProc)
  setControlCHook(didGetControlC)
  setControlCHook(nil)
  while true: discard
  echo "Unreachable code"

when isMainModule: test()
```

Not calling `setControlCHook(nil)` or leaving a dummy hook registered by reversing the order of the calls to `setControlCHook` in this example will run the registered quit procs on exit. Does setting Ctrl+C hook as nil count as a bug or should this be documented as a feature?

**Comment by ringabout** [comment]
It doesn't work on devel.

**Comment by Araq** [comment]
Leaving it unspecified is fine too.
