### ISSUE TITLE
VM segmentation faults with swap

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#15463]
Found through trying general examples from #15461. I swear I checked if this is a duplicate, I couldn't find anything.

### Example
```nim
static:
  var s = @[1, 2, 3]
  swap(s[0], s[2])
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
s becomes @[3, 2, 1]

### Additional Information

* In versions before 0.19, this says `cannot evaluate at compile time: :tmp`, and ever since 0.19 this segmentation faults.

```
$ nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
(latest devel)
```

**Comment by ringabout** [comment]
I could make it recover to the error messages(cannot evaluate at compile time: :tmp) before:
```nim
let temp =
    if owner == nil:
      newSym(skVar, getIdent(g.cache, genPrefix), nextId(idgen), owner, n.info)
    else:
      newSym(skVar, getIdent(g.cache, genPrefix), nextId(idgen), owner, n.info, owner.options)
```
