### ISSUE TITLE
unittest: wrong exit code (at least on Mac)

### ISSUE THREAD

**Issue by slonik-az** [nim-lang/Nim#15489]
I am using nim-1.2.6 on MacOS Mojave (10.14.6).

When running a compiled test binary, if there are failed tests exit code is always `1` no matter how many tests actually failed.  The documentation https://nim-lang.org/docs/unittest.html
explicitly says that
> Compiled test files return the number of failed test as exit code,...

which is not the case at illustrated by the following MWE:

### MWE
```nim
# File:  t.nim
import std/unittest

test "1+1 == 3":
    check 1+1 == 3

test "1+1 == 4":
    check 1+1 == 4

test "1+1 == 5":
    check 1+1 == 5
```
Compile with `nim c t.nim`. Run as `./t`. Exit code as reported by `echo $?` is `1`. 

#### Current Output (edited for privacy)
```
XXXX/t.nim(5, 14): Check failed: 1 + 1 == 3
1 + 1 was 2
[FAILED] 1+1 == 3
XXXX/t.nim(8, 14): Check failed: 1 + 1 == 4
1 + 1 was 2
[FAILED] 1+1 == 4
XXXX/t.nim(11, 14): Check failed: 1 + 1 == 5
1 + 1 was 2
[FAILED] 1+1 == 5
```
There are three failed tests. Therefore, the correct exit code should be 3, not 1.

### Nim Info
```
$ nim -v
Nim Compiler Version 1.2.6 [MacOSX: amd64]
Compiled at 2020-09-02
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 211868b85cf8b11baabf06d75aaf7e2015d82e2b
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
> number of failed test as exit code

I suggest we change the docs and ensure the behavior is to return either 0 or 1 for success/error; exit codes shouldn't encode unbounded numerical information such as number of failed tests, it's brittle and interferes with how bash/your shell interprets error codes, causing one to mis-interpret signals being raised for anything larger than ~128

```nim
# std/os
proc exitStatusLikeShell*(status: cint): cint =
  ## Converts exit code from `c_system` into a shell exit code.
  when defined(posix) and not weirdTarget:
    if WIFSIGNALED(status):
      # like the shell!
      128 + WTERMSIG(status)
    else:
      WEXITSTATUS(status)
  else:
    status
```

instead, the number of failed tests should be obtainable via a different mean (eg via a library call)

## links
https://unix.stackexchange.com/questions/418784/what-is-the-min-and-max-values-of-exit-codes-in-linux etc

**Comment by slonik-az** [comment]
Yes, exit code is not the best way to report number of failures. One can simply provide summary at the end like
```
Test file: test_foo.nim
Total tests run: 100
Failed tests: 3
```
in addition to providing access to this information via `unittest` API.

**Comment by Araq** [comment]
The documentation is wrong, the implementation looks correct.

**Comment by fuzzmz** [comment]
@Araq, updated the docs. Hopefully the behavior will now be clear.
