### ISSUE TITLE
Argument order affects set intersection performance

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#15496]
I'm working on some scientific that involves performing a large number of set intersections between very large (~500,000 elements) and very small (~10 elements) sets, though the sizes are variable within an order of magnitude or so. 

From looking at the source code and from testing, which set is s1 and which is s2 can have a dramatic impact on performance:

https://github.com/nim-lang/Nim/blob/4e438f9096fc413824bdbe8377a4ca376d63be35/lib/pure/collections/sets.nim#L425-L426

After experimenting with my code in which the only change is the argument order, here is the runtime performance:

`bigSet.intersection(littleSet)` => 11,400 seconds
`littleSet.intersection(bigSet)` => 127 seconds

That's a **90x** performance difference. I propose fixing this with a check to ensure that the set being iterated over is the smaller of the two.

**Comment by juancarlospaco** [comment]
Makes sense, send pull request?.
:P

**Comment by Benjamin-Lee** [comment]
Happy to help out with one. On it now.
