### ISSUE TITLE
Sizeof of case object is incorrect. Showstopper

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#15515]
Test case for 64bit arch:
```nim
type
  Kind = enum
    K1, K2
  
  AnotherEnum = enum
    X1, X2, X3

  MyObject = object
    s: string
    case k: Kind
    of K1: nil
    of K2:
        x: float
        y: int32
    z: AnotherEnum

import macros

macro c_sizeof(a: typed): int32 =
  result = quote do:
    var res: int32
    {.emit: [res, " = sizeof(", `a`, ");"] .}
    res

proc test =
  echo sizeof(MyObject)
  echo c_sizeof(MyObject)

test()
```
Nim size is 32 bytes, while C compiler size is 40 bytes.

It took me a week to trace it down. Somehow crashes were happening only in `--gc:arc` mode where Nim size is 40 bytes while C size is 48 bytes.

I believe nim doesn't take into account that elements `x` and `y` are wrapped into struct that needs its own alignment 8 byte alignment

**Comment by ghost** [comment]
Seems like you double-posted for some reason :) Closing in favour of https://github.com/nim-lang/Nim/issues/15516
