### ISSUE TITLE
Can't set other GCs after gc = orc or gc = arc is set in the global config

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#15535]
Basically after https://github.com/nim-lang/Nim/pull/15525 you can now use gc = orc in the global config just fine, but then if you try to do
```
nim c --gc:refc file.nim
```
it will fail with
```nim
Error: system module needs: nimGCvisit
```

To repro:
```nim
# write this in ~/.config/nim/nim.cfg or other global nim config
gc = orc
```

```nim
# Save in a.nim
echo "hello world"
```

```nim
nim c --gc:refc a.nim
```

**Comment by ringabout** [comment]
update: see https://github.com/nim-lang/Nim/pull/19455

**Comment by kobi2187** [comment]
global config overrides command line parameters? this means the evaluation (replacement) order is wrong.
