### ISSUE TITLE
Out of date error message for GC options

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#15547]
From the blame, this line is three years old:

https://github.com/nim-lang/Nim/blob/992952d86844805231bcc8a92063c122f721658d/compiler/commands.nim#L232

I encountered it since I missed the "c" in `--gc:arc`, which does work (extraordinarily well, I'll add):

```
Error: 'none', 'boehm' or 'refc' expected, but 'ar' found
```

**Comment by timotheecour** [comment]
@Benjamin-Lee a PR would be welcome, this should be straightforward
