### ISSUE TITLE
ambiguous call error for int litteral with int64 and uint64 overloads

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15546]
ambiguous call error for int litteral with int64 and uint64 overloads

I'm not sure whether this is a bug or not.

### Example
```nim
when true:
  proc fn1(a: int) = discard
  proc fn1(a: uint) = discard
  # works
  fn1 1

  proc fn2(a: int64) = discard
  proc fn2(a: uint64) = discard
  # error ambiguous call
  fn 2
```

### Current Output
Error: ambiguous call

### Expected Output
prefer int64 overload in this case (for consistency with `fn1`)

### Additional Information
3eaacac2303ab9fc1aef62208a112fae0ddd9152 devel 1.3.7

**Comment by Araq** [comment]
The spec says 2 is of type "int" and neither int64 nor uint64 are int, both calls require an implicit conversion hence the ambiguity. No bug here.
