### ISSUE TITLE
[RFC] Support for Multiple Inheritance

### ISSUE THREAD

**Issue by avahe-kellenberger** [nim-lang/Nim#15551]
## What is Multiple Inheritance (MI)

MI allows an object/class to inherit the characteristics and features of more than one parent object or class.

From this point forward I am going to refer to object types as `classes` for simplicity.

## Why would we want it?

I will start by saying, MI is not always the right tool for the job - but sometimes, it is (or at least is a decent option).

Multiple inheritance allows for easy composition of small classes that implement independent functionality and can manage their own state. When used correctly, we end up with a lot of small and reusable code without having to duplicate functionality or data structures.

## Why don't you just use ECS?

I've yet to see an ECS implementation that wasn't tedious and difficult to deal with.

MI reads and writes cleanly.

## Example of MI in Nim

This is how I envision multiple inheritance in Nim:

```nim
type
  Locatable = ref object of RootObj
    x*, y*: float
  Updatable = ref object of RootObj
    elapsedTime: float
  Player = ref object of Locatable, Updatable

method update*(this: Updatable, deltaTime: float) {.base.} = 
  this.elapsedTime += deltaTime

let player = Player(x: 3, y: 15)
echo "x: ", player.x, " y: ", player.y
player.update(1.17)
```

In this example, Player inherits the `x` and `y` properties of `Locatable`, and we could now invoke the method `update` with a `Player` as a parameter.

Locatable and Updatable are free to be reused by any new objects, without having to affect the structure of `Player`.

## Deadly Diamond of Death!

Most complaints regarding the implementation of MI, is [The Diamond Problem](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem).

Here is an example:
![image](https://user-images.githubusercontent.com/34498340/95684896-7f2abb80-0bc2-11eb-88e8-507d75d04608.png)

Let's create the problem with some Nim pseudo code to illustrate:

```nim
type
  Updatable = ref object of RootObj
    elapsedTime: float
  Projectile = ref object of Updatable
  ParticleEmitter = ref object of Updatable
  Missile = ref object of Projectile, ParticleEmitter

method update*(this: Updatable, deltaTime: float) {.base.} = 
  this.elapsedTime += deltaTime

method update*(this: Projectile, deltaTime: float) = 
 echo "I update projectiles"

method update*(this: ParticleEmitter, deltaTime: float) = 
 echo "I update particle emitters"

# Here, our Missile is a projectile that emits particles.
let missile = Missile()
missile.update(0.15)
# What happens when update is called?
```

The Diamond:

If we invoke `missile.update(0.15)` as shown above, we don't know which update should be invoked. Should it call `Projectile`'s update, or `Missile`'s update? In this case, a complier error should be thrown due to ambiguity.

## Solutions
There are many ways other languages have solved the diamond problem ([see this wiki article about mitigation](https://en.wikipedia.org/wiki/Multiple_inheritance#Mitigation))

My proposed solution is to force the user to implement the method, and use [procCall](https://nim-lang.github.io/Nim/manual.html#methods-inhibit-dynamic-method-resolution-via-proccall) to invoke any parent implementations they want.

From the above example, the user could write this for the `Missile`:

```nim
method update*(this: Missile, deltaTime: float) = 
  # Invoke both super class implementations of `update`
  procCall Projectile(this).update(deltaTime)
  procCall ParticleEmitter(this).update(deltaTime)
```

## Closing Thoughts
I've seen multiple people wanting some sort of multiple inheritance in Nim (see [this post](https://old.reddit.com/r/nim/comments/j6usu4/does_nim_have_interfaces_yet/) as a recent example) - I think it would be a good change that would not negatively affect those who don't care for the object oriented paradigm.

**Comment by ghost** [comment]
Transfer to https://github.com/nim-lang/RFCs please :) @Clyybber maybe

**Comment by avahe-kellenberger** [comment]
Will do, thanks!

**Comment by ghost** [comment]
well, I meant "transfer" as a direct transfer by one of the org members, don't closing/reopening, but okay :)

**Comment by avahe-kellenberger** [comment]
Woops.
