### ISSUE TITLE
--gc:arc segfaults when a constant string returned from an unloaded library is read

### ISSUE THREAD

**Issue by geekrelief** [nim-lang/Nim#15552]
### Example
```nim
#lib.nim
#--app:lib --gc:arc --d:useMalloc --debugger:native
proc getString():string {.exportc, dynlib.} =
  "lib string"

```
```nim
#main.nim
#--gc:arc --d:useMalloc --debugger:native
import dynlib
var lib = loadLib("lib.dll")

var getString = cast[proc():string {.nimcall.}](lib.symAddr("getString"))

var s = getString()
unloadLib(lib)
echo s
```

### Current Output
from gdb
```
Starting program: ...\main.exe 
[New Thread 3260.0x6cec]
[New Thread 3260.0x2694]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffcbf4cf8b6 in ungetwc () from C:\WINDOWS\System32\msvcrt.dll
```

### Expected Output
```
lib string
```

### Possible Solution

* A work around is to create a new string or not use arc.
```nim
var s = getString() & ""
```

### Additional Information
```
Nim Compiler Version 1.3.7 [Windows: amd64]

git hash: 992952d86844805231bcc8a92063c122f721658d
active boot switches: -d:release
```

**Comment by cooldome** [comment]
Checked it. Looks like it is related to the constants. String is constant in this case. Pointer to the constant was passed though the dll and then dll was unloaded making pointer to constant invalid.

Needs conceptual discussion on how to handle "foreign constants"

**Comment by geekrelief** [comment]
Thanks for taking a look! I wish I could help debug this. Any pointers would be appreciated.

Anyway, I could create another function in lib.nim to store the string in a var, or maybe the string could come from the keys of a Table[string, proc()] (where I initially encountered the bug) and copying the string will segfault. 

What I don't understand is how I can print the length of the string without it crashing? I'd assume would have to dereference a pointer...

```nim
#in  main.nim
var s = getString() # crash on echo
#var s = getString() & "" # ok
unloadLib(lib)
echo s.len # this ok
echo "ok"
```
The initial assignment from getString() to s should result in a copy, right? At least that's what the manual says should happen.

**Comment by cooldome** [comment]
Nim has optimization for the constants and `var s = getString()` doesn't make a copy here, it is the pointer to original constant. `nimPrepareStrMutationV2` need to called for `s` before unloading the dll. Unfortunately
`nimPrepareStrMutationV2`is not exported function. Best option is to make some kind of mutation on dll side for now.

**Comment by cooldome** [comment]
You can create proc
```nim
proc prepareForMutation(s: var string) =
  s = s & ""
```
and call it in side dll before returning results.

**Comment by geekrelief** [comment]
> You can create proc
> 
> ```nim
> proc prepareForMutation(s: var string) =
>   s & ""
> ```
> 
> and call it in side dll before returning results.

Yeah that's basically what I'm doing for now.  I assume you still have to set the return type for prepareMutation as string, and s isn't being modified right?

**Comment by cooldome** [comment]
Thanks for pointing out the bugs in `prepareForMutation`, I have fixed them above

**Comment by ringabout** [comment]
> nimPrepareStrMutationV2is not exported function.
It is now exported as `prepareMutation`.

Hi @geekrelief 
Now there is a better solution with latest devel.

```nim
#--gc:arc --d:useMalloc --debugger:native
import dynlib
var lib = loadLib("lib.dll")

var getString = cast[proc():string {.nimcall.}](lib.symAddr("getString"))

var s = getString()
prepareMutation(s)

unloadLib(lib)
echo s
```

**Comment by Araq** [comment]
You need to use `prepareMutation` in this case.
