### ISSUE TITLE
dbQuote additional escape regression

### ISSUE THREAD

**Issue by lbcheng888** [nim-lang/Nim#15560]
Function `echo` outputs the wrong string.

### Example
```nim
import db_mysql

var db = open("","","","")
var email = "cloudfastnet@cncarecc.com"
var row = db.getRow(sql "SELECT password,id,cloudfast_group,name,source,email,mobile,telephone,company,address,position,is_open FROM user WHERE email=?",email)
echo row
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
SELECT password,id,cloudfast_group,name,source,email,mobile,telephone,company,address,position,is_open FROM user WHERE email='cloudfastnet\64cncarecc\46com'

```

### Expected Output
```
SELECT password,id,cloudfast_group,name,source,email,mobile,telephone,company,address,position,is_open FROM user WHERE email='cloudfastnet@cncarecc.com'
```

### Possible Solution

* restore dbQuote as
```nim
proc dbQuote*(s: string): string =
  ## DB quotes the string.
  result = "'"
  for c in items(s):
    if c == '\'': add(result, "''")
    else: add(result, c)
  add(result, '\'')
```

### Additional Information
If it's a regression, you can help us by identifying which version introduced
the bug, see [Bisecting for regressions](https://nim-lang.github.io/Nim/intern.html#bisecting-for-regressions),
or at least try known past releases (eg `choosenim 1.2.0`).

If it's a pre-existing compiler bug, see [Debugging the compiler](https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler)
which should give more context on a compiler crash.

* Issue #abc is related, but different because of ...
* This issue is blocking my project xyz

```
$ nim -v
Nim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-10-11
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d66e274e1ac8e86266151ad0c48f7705b3bd1582
active boot switches: -d:release
# make sure to include the git hash if not using a tagged release
```

**Comment by Araq** [comment]
Well but MySQL supports these escape sequences, why does it cause problems for you?

**Comment by euantorano** [comment]
> Well but MySQL supports these escape sequences, why does it cause problems for you?

I don't see any mention of such support sequences in [the documentation](https://dev.mysql.com/doc/refman/8.0/en/string-literals.html):

Escape Sequence | Character Represented by Sequence
-- | --
\0 | An ASCII NUL (X'00') character
\\' | A single quote (') character
\\" | A double quote (") character
\b | A backspace character
\n | A newline (linefeed) character
\r | A carriage return character
\t | A tab character
\Z | ASCII 26 (Control+Z); see note following the table
\\\\ | A backslash (\) character
\\% | A % character; see note following the table
\\_ | A _ character; see note following the table

Running the following SQL:

```sql
SELECT 'cloudfastnet\64cncarecc\46com', 'cloudfastnet@cncarecc.com';
```

Also gives incorrect results:

- cloudfastnet64cncarecc46com
- cloudfastnet@cncarecc.com
