### ISSUE TITLE
-d:lto doesn't work on OSX: invalid linker name in argument '-fuse-ld=lld'; + other issues with -d:lto

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15578]
* -d:lto doesn't work on OSX: invalid linker name in argument '-fuse-ld=lld'
* -d:lto should be renamed to `-d:nimlto` to avoid clashes with user/3rd party packages
* -d:lto isn't documented in https://nim-lang.github.io/Nim/nimc.html (reason more to rename to `-d:nimlto`)

### Example
```nim
echo 'echo 1' | nim r -d:lto -
```

### Current Output
```
clang: error: invalid linker name in argument '-fuse-ld=lld'
Error: execution of an external program failed: 'clang   -o /Users/timothee/.cache/nim/stdinfile_d/stdinfile  /Users/timothee/.cache/nim/stdinfile_d/stdlib_io.nim.c.o /Users/timothee/.cache/nim/stdinfile_d/stdlib_system.nim.c.o /Users/timothee/.cache/nim/stdinfile_d/@mstdinfile.nim.c.o    -ldl -fuse-ld=lld -flto'
```

### Expected Output
works

### Additional Information
* devel c2ba4ef9799a097fec8b2bb1b033448860d60f1b 1.3.7
* it works on ubuntu
* --passc:-flto works on OSX
* -d:lto was added recently in https://github.com/nim-lang/Nim/pull/14013 /cc @Keithcat1 
### questions
* is `--passl:-flto` actually needed or just `--passc:-flto`? at least on some tests, only `--passc:-flto` seemed to matter

**Comment by juancarlospaco** [comment]
@timotheecour https://github.com/nim-lang/Nim/pull/15498#issuecomment-704323820

**Comment by ghost** [comment]
@juancarlospaco not sure how that is related, but thanks for the link :)

**Comment by ghost** [comment]
@timotheecour I actually got the same error if you check that PR - https://github.com/nim-lang/Nim/pull/14013#issuecomment-620942417
