### ISSUE TITLE
[ARC] Question on allocation handlings for seqs, string and refs

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#15574]
Seqs and strings in arc mode are using `sharedAlloc` and `deallocShared` for memory management.

However refs are using:
```nim
when  defined(useMalloc):
    c_malloc(cuint s)    
elif compileOption("threads"):
    allocShared0(s)
else:
    alloc0(s)
```

I would like to aligns the approaches, but I am not sure if I would fix seqs/strings or refs.
Bare in mind that `alloc`, `allocShared` and `c_malloc`  are the same thing under `useMalloc`, but are different otherwise.

Araq,
Please opine on what is the desired memory allocation approach and I will prepare a PR.

**Comment by Araq** [comment]
seqs/strings should follow ref's implementation strategy. Unless you can come up with good arguments for a different setup.

**Comment by cooldome** [comment]
Possibly, we can simplify it a little bit:
```nim
when compileOption("threads"):
    allocShared0(s)
else:
    alloc0(s)
```
When `useMalloc` is defined both `allocShared` and `alloc` means `c_malloc` already.
Does it sound good?

**Comment by Araq** [comment]
Yes.
