### ISSUE TITLE
Broken posix/posix_linux_amd64_consts

### ISSUE THREAD

**Issue by fox0430** [nim-lang/Nim#15586]
Can't compile posix/posix_linux_amd64_consts

### Example
```nim
import posix/posix_linux_amd64_consts
```

### Current Output
```
Hint: used config file '/home/fox/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/fox/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
.....
/home/fox/.choosenim/toolchains/nim-#devel/lib/posix/posix_linux_amd64_consts.nim(315, 21) Error: undeclared identifier: 'InAddrScalar'
```

### Expected Output
Compile success.

### Additional Information

```
$ nim -v
Nim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-10-15
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: a4c28394beab558a160671ab216e736b36276a94
active boot switches: -d:release
```

**Comment by ghost** [comment]
IIUC this module is not meant to be imported directly.

**Comment by fox0430** [comment]
@Yardanico 

Thank you for your reply.

What is this?
I can't use this module?

**Comment by ghost** [comment]
@fox0430 no, you don't need to - these posix modules for specific platforms/architectures exist so then posix module can have when conditions for switching between them. Did you try using the posix module?

**Comment by fox0430** [comment]
@Yardanico 

I understand. I was in the wrong.

Thank you.
