### ISSUE TITLE
1.4.0 cannot open file: exitprocs

### ISSUE THREAD

**Issue by iffy** [nim-lang/Nim#15600]
I'm unable to import exitprocs without `std/`

### Example
```nim
import exitprocs
proc something() = echo "exiting!"
addExitProc(something)
```

### Current Output

```
$ nim c -r /tmp/something.nim 
Hint: used config file '/Users/matt/.choosenim/toolchains/nim-#head/config/nim.cfg' [Conf]
Hint: used config file '/Users/matt/.choosenim/toolchains/nim-#head/config/config.nims' [Conf]
....
/private/tmp/something.nim(1, 8) Error: cannot open file: exitprocs
```

### Expected Output
```
$ nim c -r /tmp/something.nim 
exiting!
```

### Workaround

Importing `std/exitprocs` works fine.

```
$ nim --version
Nim Compiler Version 1.4.0 [MacOSX: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 018ae963ba83934a68d815c3c1c44c06e8ec6178
active boot switches: -d:release
```

```
$ nim --version
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 6b8baab536d25c744150e0190d2e172165faf92e
active boot switches: -d:release
```

**Comment by alaviss** [comment]
It's expected. New modules will be introduced into the `std/` namespace by default.

**Comment by iffy** [comment]
That's reasonable. Then maybe the fix here is that the deprecation warning for `addQuitProc` should use the `std/` prefix?  Here's the current warning:

```
Warning: use exitprocs.addExitProc; addQuitProc is deprecated
```

**Comment by timotheecour** [comment]
I don't think it's needed, other module references in the docs dont add that you need std

**Comment by iffy** [comment]
I suppose it's not needed, now that I know that importing from `std/` is the preferred method. And maybe newcomers to Nim won't encounter the deprecation warning before they know to import from `std/`.
