### ISSUE TITLE
Nim's doc looks broken a bit

### ISSUE THREAD

**Issue by albmelon** [nim-lang/Nim#15603]
It seems it's broken. I don't know how to fix it. Maybe CSS/JS problem?

- [list](https://nim-lang.org/docs/lists.html)
- [algorithm](https://nim-lang.org/docs/algorithm.html)

Environment: desktop on linux
Browser: chrome and firefox 

![a](https://user-images.githubusercontent.com/48589065/96295113-57a37b00-1028-11eb-8326-c26b1dd66532.png)

**Comment by ghost** [comment]
Yeah, that's a known issue, it should be fixed soon (your issue is fine, don't close it)

**Comment by EchoPouet** [comment]
I have the same problem but I have also a problem with the dark mode. The color of the background isn't the best to read.

![image](https://user-images.githubusercontent.com/5129154/96363227-3bd8cb80-1133-11eb-8231-b7e0e0eb3900.png)

I use Firefox.

**Comment by Clyybber** [comment]
Both issues are fixed on #devel docs: https://nim-lang.github.io/Nim/manual

**Comment by narimiran** [comment]
> Both issues are fixed on #devel docs

...and after Cloudfare cache finally expires, the fix should also be visible for the stable docs on the website.
