### ISSUE TITLE
Procedures from system should have a lower priority then procedures from outside system.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#15608]
Procedures created outside of system should have higher priority then procedures created inside system.
If an ambiguity error would be thrown the procedure created outside of system would be chosen over any procedures defined in system.

Any additions to the standard library shouldn't cause conflicts with procedures defined in user code.
This would be minimized if user defined procedures took priority.

I noticed this problem when I recently switched from the standard gc to arc and my overwrite of repr(NimNode) was causing ambiguity errors. I also tried to overwrite $(type) but ultimately made by own toStr procedure for types.

This can be worked around by putting import system except repr,`$` at the top of your file but unfortunately that also drops a lot of other useful procedures. Also requiring users of your code to do this as well in the case of generics would be tedious.
You could also qualify imports with myModule.repr.

Let me know if this should be put in the rfc section.

**Comment by alaviss** [comment]
You can qualify the procs to call your own, for example:

`mymodule.nim`:

```nim
proc repr(n: NimNode): string = ""
proc `$`(n: NimNode): string = ""

discard mymodule.repr(node)
discard mymodule.`$`(node)
```

And yes this qualifies as an RFC. Please migrate the issue to https://github.com/nim-lang/RFCs

**Comment by solo989** [comment]
Posted in rfcs. [#268](https://github.com/nim-lang/RFCs/issues/268)
