### ISSUE TITLE
[Regression] JS: HashSet hash at compile time and run time not equal

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#15624]
This works in C and C++ backends, but fails in JS.

### Example
```nim
import sets
const foo = ['a'].toHashSet
echo 'a' in foo
```

### Current Output
```
false
```

### Expected Output
```
true
```

### Additional Information

* `const a = hash('a'); echo a` outputs `0`, it's probably related, or maybe another bug
* This used to work in v1.0.x and v1.2.x

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-10-18
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b16b2eb06fa09b22ab50b3bd2703fe79c0ca4fc6
active boot switches: -d:release
```

**Comment by ringabout** [comment]
@nitely
This is caused by new hash algorithm:

Workaround:
```
-d:nimIntHash1
```

**Comment by ringabout** [comment]
Related:
#13823
