### ISSUE TITLE
[JS] `$` on an enum in an if expression causes bad codegen

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#15651]
### Example
```nim
type
  Enum = enum A

let
  enumVal = A
  tmp = if true: $enumVal else: $enumVal
```

### Current Output
```
Uncaught TypeError: src_1470024 is undefined
```

### Additional Information
Tested with 1.4.0 and 78cbb52fa01d6c73307fe276bdf7d4c34d7a556c

**Comment by metagn** [comment]
Is this different from #13602? You reported both bugs

**Comment by dawkot** [comment]
No, sorry. But I'll close #13602 instead of this one because that example is less clear.
