### ISSUE TITLE
`$`(s: WideCString) changes result to repr on --gc:arc

### ISSUE THREAD

**Issue by coffeepots** [nim-lang/Nim#15663]
### Example
```nim
let ws = newWideCString("Test")
echo ws
```

### Current Output
Tested with Nim 1.4 and 1.5.1 git hash: `319aac4d43b04113831b529f8003e82f4af6a4a5`
```
(bytes: 10, data: Test)
```

### Expected Output
```
Test
```

### A Hint to a Possible Solution

At the exit point of ```proc `$`*(s: WideCString): string``` the `result` variable is as expected, but immediately after exit of the proc the result appears to be transformed into the `repr` of the `WideCStringObj` object.

### Additional Information
The result is as expected without `--gc:arc`/`--gc:orc` in the latest version 1.5.1 mentioned above.

**Comment by coffeepots** [comment]
Interestingly, either a `proc` or `template` proxy seems to fix the problem.

```nim
proc proxy*(s: WideCString): string = $s
template tproxy*(s: WideCString): string = $s

let ws = newWideCString("Test")
echo ws.proxy   # Test
echo ws.tproxy  # Test
echo $ws        # (bytes: 10, data: Test)
```

**Comment by ringabout** [comment]
This is causes by `converter`.

This works.
```nim
let ws = newWideCString("Test")
let s = ws
echo s
``` 
output:
`Test`

**Comment by ringabout** [comment]
This is due to overloading `$`(from system) for object so `converter` doesn't work.

Like this:
```nim
proc len*(w: WideCStringObj): int =
  100

proc hello() =
  let ws = newWideCString("Test")
  echo ws.len

hello()
```

Output:
`100` # instead of 4
