### ISSUE TITLE
sql subtitution '?' compatibility problem 1.2.6 and 1.4.0

### ISSUE THREAD

**Issue by zendbit** [nim-lang/Nim#15664]
sql subtitution '?' compatibility problem

This is the problem I am facing when using the new 1.4.0, maybe someone have the solution for this problem to make it  work on the version 1.4.0. Thanks

### issue
When I use the version 1.2 the subtitution of '?' on email for example admin@my.com, will not force to quote the '@' and '.' char
```
admin@my.com

the sql statement will be:

sql statement:
select email from users where email=?

output version 1.2.6:
select email from users where email='admin@my.com'
```

### Current Output
This happen on sql '?' subtitution, version 1.4.0 will automatically quote the subtitution, so for example admin@my.com will convert to this
```
admin@my.com

the sql statement will be:

sql statement:
select email from users where email=?

output version 1.4.0:
select email from users where email='admin\64my\46com'
```

```
$ nim -v
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

**Comment by ghost** [comment]
This is a consequence of https://github.com/nim-lang/Nim/pull/15234

**Comment by ringabout** [comment]
It seems to be fixed already? I don't know whether it is backported.
https://github.com/nim-lang/Nim/issues/15560

**Comment by ghost** [comment]
I don't think we should consider this as an issue, since previously this behaviour resulted into possible SQL injection attacks.

**Comment by ghost** [comment]
Duplicate of https://github.com/nim-lang/Nim/issues/15560
@xflywind is right - fixed in https://github.com/nim-lang/Nim/pull/15587

**Comment by zendbit** [comment]
thanks, work on the devel channel
