### ISSUE TITLE
Type casting -2147483648 to int32 with generics causes compilation error

### ISSUE THREAD

**Issue by tejasjadhav** [nim-lang/Nim#15668]
### Example
Nim playground: https://play.nim-lang.org/#ix=2BuV

```nim
type 
  Int32 = int32

proc printMessage[T](value: T)=
  if T is Int32:
    stdout.writeLine T(value)

printMessage[Int32](-2147483648)
```

### Current Output
```
/usercode/in.nim(8, 20) Error: type mismatch: got <int64>
but expected one of: 
proc (value: Int32){.gcsafe, locks: 0.}
```

### Expected Output
```
-2147483648
```

### Possible Solution
Explicitly casting it to `int32` while passing it to the function makes it work
```nim
type 
  Int32 = int32

proc printMessage[T](value: T)=
  if T is Int32:
    stdout.writeLine T(value)

printMessage[Int32](int32(-2147483648)) # explicit casting 
```
The above code correctly gives the output as,
```
-2147483648
```

### Additional information

Surprisingly, it works for the following cases,
* When using `value` as `-2147483647`
* When using `type Int16 = int16` with `value` as `-32768` (similarly for `type Int8 = int8` with `value` as `-128`)

### Nim version
```
$ nim -v
Nim Compiler Version 1.4.0 [MacOSX: amd64]
Compiled at 2020-10-17
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by tejasjadhav** [comment]
Not sure if this is related, but printing out the smallest int64 number also causes compilation error even though [it's within the int64 range](https://en.wikipedia.org/wiki/Integer_(computer_science)#Common_integral_data_types)

Nim playground: https://play.nim-lang.org/#ix=2Bv8
```nim
stdout.writeLine -9223372036854775808
```

Gives the following error,
```
/usercode/in.nim(1, 19) Error: number out of range: '9223372036854775808'
```

---

But the same works for `-9223372036854775807`
```nim
stdout.writeLine -9223372036854775807
```

Gives output,
```
-9223372036854775807
```

**Comment by Araq** [comment]
Works as according to the spec. ``-1`` is unary minus followed by 1, ``2147483648`` is not a valid int32 number. Use ``low(int32)`` instead which is much more readable too.
