### ISSUE TITLE
No link to std/enumerate in the stdlib docs

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#15694]
Is this intentional? If not, I'm happy to PR it. I took a look at the discussion (https://github.com/nim-lang/Nim/pull/15297#issuecomment-696124868) surrounding the inclusion of `enumerate` not in `sugar` but in `std/enumerate` and wasn't sure if it was a temporary solution or not.

**Comment by timotheecour** [comment]
https://nim-lang.github.io/Nim/enumerate.html ?

**Comment by Benjamin-Lee** [comment]
Looking here to be specific: https://nim-lang.github.io/Nim/lib.html

**Comment by timotheecour** [comment]
kochdocs could add some logic to check that all docgen'd stdlib modules are mentioned in lib.rst, that way, it'd always stay in sync.

I'm sure other modules are missing.

**Comment by timotheecour** [comment]
duplicate of https://github.com/nim-lang/Nim/issues/16046
