### ISSUE TITLE
regression: docgen drops enum doc comments

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#15702]
Check out http://nim-lang.github.io/Nim/io.html:
![image](https://user-images.githubusercontent.com/21169548/97065007-0ad51c80-15b3-11eb-9096-ab2c3c697583.png)

On 1.2.8
![image](https://user-images.githubusercontent.com/21169548/97065010-0dd00d00-15b3-11eb-8d6e-5cec99711799.png)

**Comment by Jjp137** [comment]
From what I can tell, it seems that the comments disappear if the item involved is an enum (although there may be other cases).

Here's a test file:
```nim
type Point* = object
  ## A coord pair.
  x*: int  ## The x coord
  y*: int  ## The y coord

type Shapes* = enum
  ## Some shapes.
  Circle,     ## A circle
  Triangle,   ## A three-sided shape
  Rectangle   ## A four-sided shape

proc example*() =
  ## An example proc.
  runnableExamples:
    discard 1 + 1     ## Some math
    discard "hello!"  ## A string
  discard
```
Upon running `nim doc` on 1.4.0, the aligned comments for the Shapes enum are not kept in the HTML output.

**Comment by timotheecour** [comment]
git bisect finds this:
```
5db0bb744c08feb0c2c17ecd9cba12c276cde374 is the first bad commit
commit 5db0bb744c08feb0c2c17ecd9cba12c276cde374
Author: cooldome <cdome@bk.ru>
Date:   Tue Apr 21 19:12:32 2020 +0100

    Replace enum fields idents with syms (#14048)

    * replace enum fields idents with syms
    * Trigger build

    Co-authored-by: cooldome <ariabushenko@bk.ru>

 changelog.md          |  4 ++++
 compiler/semtypes.nim | 10 +++++++++-
 2 files changed, 13 insertions(+), 1 deletion(-)
bisect run success

```

so nimdoc logic needs to be updated after https://github.com/nim-lang/Nim/pull/14048 /cc @cooldome 

## note
for future reference, here's my git bisect command to find this:
```
git bisect start v1.4.0 v1.2.0 

git bisect run zsh -c "source ~/.zshrc && nim=$nim_csources_local_X d_nim_build_simple_local --skipusercfg --hints:off -o:bin/nim.bisect && bin/nim.bisect doc -o:/tmp/z01.html $timn_D/tests/nim/all/t11183.nim && grep D20201024T143000 /tmp/z01.html"
```

(adapt as needed)
