### ISSUE TITLE
could not load: ( libmysql.dll | libmariadb.dll ) 

### ISSUE THREAD

**Issue by coinrazzi** [nim-lang/Nim#15720]
Hi, 
I am using Visual Studio Code for Nim coding. 
I am new bie for nim lang. I tested this basic mysql connection example code. 
import db_mysql

#database connection (local mysql i am using wampserver)
let db = open("localhost", "root", "", "mydatabase")
#close db
db.close()

-----------------------------------------------------------
I am getting this error. 

could not load: (libmysql.dll|libmariadb.dll)
Error: execution of an external program failed:

Is there native support for mysql in Nim?

**Comment by ringabout** [comment]
You could them in [Nim forum](https://forum.nim-lang.org) or [Nim discord](https://discord.gg/pMrwVNwc) to get answers.

I think you should download libmysql.dll/libmariadb.dll and put them in the right path. Nim doesn't ship with them(only ship with sqlite.dll).
