### ISSUE TITLE
`cstring("") != nil` fails at CT; `isNil` sometimes returns false for nil cstring

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15730]
`cstring("") != nil` fails at CT

### Example 1
```nim
proc main()=
  const s: cstring = ""
  doAssert s != nil

static: main()
main()
```

### Current Output
fails

### Expected Output
works

### [EDIT] Example 2
```nim
when true: # D20201026T185255:here gitissue
  proc fn(x, y: cstring): bool = y.isNil
  proc main()=
    const s1: cstring = nil
    doAssert s1.isNil # ok
    const s: cstring = "a"
    doAssert fn(s, nil) # fails at CT
  static: main()
  main()
```

### [EDIT] Example 3
`repr` is different for cstring at RT vs CT

### Additional Information
devel 1.5.1 86d7726fb8044d4e2fc55b0eac3d1d42f5ffc94f
code fix likely involves handling `tyCstring` in vm.nim or similar around opcEqRef or opcEqNimNode IIRC
EDIT: `regs[ra].intVal = ord(regs[rb].node.strVal == regs[rc].node.strVal)`

**Comment by metagn** [comment]
I thought `cstring` in VM was the same as `string` in implementation, so `nil` and `""` wouldn't be different.

**Comment by timotheecour** [comment]
that's an implementation artifact; CT code should behave same as RT code otherwise working code written for RT might be buggy when used at CT

**Comment by Clyybber** [comment]
But `cstring` is by definition an implementation artifact, mapping to null-terminated strings for the C backend, and js strings for the js backend.

**Comment by ringabout** [comment]
Yeah, it is buggy and should be fixed.

It makes VM inconsistent with C/JS backend when passing `nil` as parameters.
https://github.com/nim-lang/Nim/pull/16590
