### ISSUE TITLE
Jester uses more memory per page load

### ISSUE THREAD

**Issue by ITwrx** [nim-lang/Nim#15749]
as reported in https://github.com/dom96/jester/issues/270, Jester uses more memory per page load. Currently testing with:

`import jester, strutils`
`include Views/index`

```
routes:
  get "/":
    resp INDEX_HTML.format("")
```
and for Views/index.nim:

```
const INDEX_HTML = """
  <html>                                                                                                                                                      
  <head>
  <meta name="title" content="ITwrx-Jester" />  
  </head>
  <body>
  <h1>Responding with html from separate file with Jester.</h1>                                                                                                <body>                                                                                                                                                      
  <p>This is only a test. If this were a real paragraph, it would be much more interesting.</p>                                                               
  </body>                                                                                                                                                     
  </html>
  """
```
with the above html-only testing code it takes 5-10 page loads to notice a bump of 0.1-0.2 MB of ram increase. If the page has images, css or videos, the mem usage will climb in proportion to the amount of data being served. For example, if you add an html5 video tag with a video file asset, it will climb 30MB (or was it 3MB?, I can't recall) at a time (depends on vid size). With css and a background image of about 60k combined, it climbs about 0.3MB per page load.

Jester compiled with: `-d:useStdlib` and either the default GC, `--gc:boem`, `--gc:markAndSweep`, `--gc:orc`, or -`-gc:orc -d:useMalloc`.

I haven't tried with any other http frameworks yet.

Tried with nim versions: `1.0.10, 1.2.8, and 1.4.0`

OS is fedora32, if that matters any.

Thanks

**Comment by Araq** [comment]
If --gc:boehm reproduces the problem it is a stdlib problem or a jester problem. Please provide an example that doesn't use Jester.

**Comment by ITwrx** [comment]
first, i decided to go ahead and spell `--gc:boehm` correctly and rerun my jester example. :) It still used more ram per request. so i created a simple test with asynchttpserver and it did **not** use more ram per request with `--gc:boehm` or `--gc:orc`.

```
import asynchttpserver, asyncdispatch, strutils

include Views/index

var server = newAsyncHttpServer()
proc cb(req: Request) {.async.} =
  #await req.respond(Http200, "Hello World")
  await req.respond(Http200, INDEX_HTML.format(""))

waitFor server.serve(Port(8080), cb)
```
So, it seems it's a jester problem. Thanks for the help, and sorry for the noise. I didn't think i knew how to make a asynchttpserver test, but on second look, it was easy.

**Comment by dom96** [comment]
I mean... just because Jester reproduces it doesn't mean it's a Jester problem :)

But sure, let's continue investigation in the Jester issue.
