### ISSUE TITLE
OrderedTable.== throws error on empty table: unhandled exception: index out of bounds...

### ISSUE THREAD

**Issue by gcao** [nim-lang/Nim#15750]
OrderedTable.== throws error on empty table: unhandled exception: index out of bounds, the container is empty [IndexDefect]

### Example
```nim
import tables

var t1 = OrderedTable[int, string]()
var t2 = OrderedTable[int, string]()

echo t1 == t2
```

### Current Output
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]

### Expected Output
true

$ nim -v
Nim Compiler Version 1.4.0 [MacOSX: amd64]
Compiled at 2020-10-27
Copyright (c) 2006-2020 by Andreas Rumpf
active boot switches: -d:release

**Comment by ringabout** [comment]
You should use `initOrderTable` to initialize `OrderTable`.

```nim
import tables

var t1 = initOrderedTable[int, string]()
var t2 = initOrderedTable[int, string]()

doAssert t1 == t2
```
