### ISSUE TITLE
HashSet misses elements when excl'ing while iterating over it

### ISSUE THREAD

**Issue by liquidev** [nim-lang/Nim#15767]
### Example
```nim
import std/sets
import std/hashes

type
  Vec2i = tuple[x, y: int32]

proc hash(vec: Vec2i): Hash =
  result = Hash(0)
  result = result !& hash(vec.x)
  result = result !& hash(vec.y)
  result = !$result

var set: HashSet[Vec2i]

for y in 1..4:
  for x in 0..<32:
    let vec: Vec2i = (x.int32, y.int32)
    set.incl(vec)

let i = set.len

var j = 0
for vec in set:
  inc(j)
  set.excl(vec)
echo (i, j)
```

### Current Output
```
(128, 96)
```
32 elements are magically gone from the set while we're iterating over it.

### Expected Output
```
(128, 128)
```

### Additional Information
If we change the `HashSet` to an `OrderedSet`, the program gets stuck at an infinite loop. Adding `echo vec` to the loop at the end of the program yields that it gets stuck at `(x: 22, y: 1)`. ^C'ing out of the program, I could trace that it gets stuck in this `while` loop:
https://github.com/nim-lang/Nim/blob/a156484553d7fa9b3b174f8371159af81574f77c/lib/pure/collections/sets.nim#L620-L629

If sets cannot handle excluding elements while iterating over them, then that should be clearly stated in the documentation and ideally also trigger an assertion.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-10-22
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2cb484cefb13e4663afd8e0eb2ad81d43f097803
active boot switches: -d:release
```

**Comment by cooldome** [comment]
Yes, it is not safe to iterate over container and modify it at the same time. Nim should raise an error in debug build.
