### ISSUE TITLE
Conversion of nil string to cstring is not equal to cstring(nil)

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1577]
The following test case shows a problematic conversion between a `string` Nimrod type and a `cstring`:

``` nimrod
proc test() =
  var a: string
  var b = cstring(a)
  var c: cstring
  var d = cstring(nil)
  echo "Is a nil? ", a.is_nil
  echo "Is b nil? ", b.is_nil
  echo "Is c nil? ", c.is_nil
  echo "Is d nil? ", d.is_nil
  {.emit: """
  char *p = 0;
  printf("C printf is nil? => %p\n", p);
  """.}

proc printf(formatstr: cstring) {.importc: "printf", varargs,
                                  header: "<stdio.h>".}

when isMainModule:
  test()
  var a: string = nil
  printf("Nimrod printf is nil? => %p\n", a)
```

The result of running this program is:

```
Is a nil? true
Is b nil? false
Is c nil? true
Is d nil? true
C printf is nil? => 0x0
Nimrod printf is nil? => 0x10
```

What happens is that a `string` with a nil value is not converted to a `cstring` nil value, but rather some other pointer value. I found this while interfacing with C and having stuff crash in an API where passing a nil value as a parameter is valid. The conversion between `cstring` and `string` caused the failure.

The [manual CString type](http://nimrod-lang.org/manual.html#cstring-type) section implies conversions should be equivalent, so I guess this is a bug. If not, the documentation will need updating.

**Comment by krux02** [comment]
Honest I doubt that adding a nil check on the ``string`` to ``cstring`` conversion will ever be a bottleneck. But if you care about performance it can be implemented jump free:

```C
#include <stdio.h>
#include <stddef.h>

typedef struct{
  long length;
  long capacity;
  char data[];
} NimString;

char* NimString2CString(NimString* arg) {
  return (arg->data) - (arg == 0) * offsetof(NimString, data);
}

int main() {
  NimString* str = 0;
  printf("%p\n", str);
  printf("%p\n", NimString2CString(str));
}
```

So my recommendation is to just support this.
