### ISSUE TITLE
Heap Corruption after accessing public field in JSON Objects

### ISSUE THREAD

**Issue by elcritch** [nim-lang/Nim#15774]
Json parsing and handling when combined with using JArray field like: `someNode.elems` corrupts the heap and introduces possible memory leaks. In my case it comes from a [marshalling hanlder](https://github.com/elcritch/nesper/blob/1d8eba9b4117b1aff9dc0e457985f9606e596930/src/nesper/servers/rpc/marshal.nim#L216). 

That line produces a compiler warning: 
```sh
/home/elcritch/.asdf/installs/nim/1.4.0/compiler/semstmts.nim(626, 16) compiler msg initiated here [MsgOrigin]
/home/elcritch/projects/bessel/esp32/nesper/src/nesper/servers/rpc/rpcsocket_json.nim(60, 6) template/generic instantiation of `rpc` from here
/home/elcritch/projects/bessel/esp32/nesper/src/nesper/servers/rpc/marshal.nim(216, 22) Warning: cannot prove that field 'params.elems' is accessible [ProveField]
            `jsonIdent`.elems[`pos`]
                       ^
```

### Example

I've created a branch [compiler-1_4_0_failure-test](https://github.com/elcritch/nesper/tree/compiler-1_4_0_failure-test) in my project [Nesper](https://github.com/elcritch/nesper) with an example of the memory corruption when using JsonNode `.elems` field (even when done so correctly AFAICT). There are two script, one for compiling the server, one for the client:
[src/nesper/servers/rpc/compile_rpc_tests.sh](https://github.com/elcritch/nesper/blob/compiler-1_4_0_failure-test/src/nesper/servers/rpc/compile_rpc_tests.sh)
[tests/compile_rpc_cli.sh](
https://github.com/elcritch/nesper/blob/compiler-1_4_0_failure-test/tests/compile_rpc_cli.sh)

Steps to reproduce (Linux, amd64): 

Clone Nesper and checkout the branch `compiler-1_4_0_failure-test`. 

In Console 1: 
```sh
cd src/nesper/servers/rpc/
src/nesper/servers/rpc/compile_rpc_tests.sh
valgrind -v --leak-check=yes ./rpcsocket_json
```

In Console 2:
```sh
cd tests/
./compile_rpc_cli.sh
```

### Current Output

[Valgrind Log](https://gist.github.com/elcritch/d825af308434a29c5d9b06e4d119d9fc#file-valgrind-log)

### Expected Output

Changing the line to ``jsonIdent`[`pos`]` fixes the issue. However, it seems that using a variant field after checking it's type shouldn't corrupt the heap.

### Additional Information

For the steps above: 
```
$ nim -v
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-19
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 018ae963ba83934a68d815c3c1c44c06e8ec6178
active boot switches: -d:release
```

This also occurs when cross-compiling for the ESP32, where the heap corruption detection will crash the server after a while.

**Comment by Araq** [comment]
Your valgrind log shows no corruptions.

**Comment by elcritch** [comment]
Bummer, I thought I'd reproduced the issue. Well I'm glad the compiler is working fine in this case, but it's an annoying crash that's occurring on the ESP32. I re-ran this test case and when there's a clean exit of the app it clears up most of those possible memory leaks. 

I'll look into it a bit more. The original problem arose on the ESP32, and is fixed by changing that `elem` access. Otherwise it produces errors linked back to either the JSON node parsing, or the destroyers on the JSON nodes.

**Comment by planetis-m** [comment]
Do you use ``--noMain:on``?

**Comment by timotheecour** [comment]
@elcritch bugs with small, self-contained reproducible examples are much more likely to get fixed (yes, it requires some effort on your part to minimize the bug)

**Comment by elcritch** [comment]
Hi @planetis-m and @timotheecour it was a hard to track down issue. The same code ran fine on x86, vagrind, etc. but regularly failed on the device. The issue has not occurred for a while so it was either esp-idf library code (particularly their malloc), or a combination of Nim and embedded gcc. It also may have been due to multithreaded issues. 

Given that I’m fine closing the issue. @planetis-m yah I use -d:nomain but call nimInit (or whatever the unit code is).

**Comment by planetis-m** [comment]
Also consider that with `--nomain:on` unhandled exceptions are getting caught on the wrong `try except` block: https://github.com/planetis-m/libfuzzer/blob/80790da9591fe93e6de6972bd2493a739a3d5931/tests/traise.nim
