### ISSUE TITLE
One-off destructor call in inner proc with --gc:arc

### ISSUE THREAD

**Issue by pmetras** [nim-lang/Nim#15798]
A destructor for an object in a inner proc is called twice when compiled with `--gc:arc`.

### Example
```nim
type
  AutoClose = object
    ss: seq[string]

proc `=destroy`(o: var AutoClose) =
  echo "In AutoClose destructor; releasing=", o.ss

proc foo =
  let ac = AutoClose(ss: @["In", "foo"])
  proc bar =
    let ca = AutoClose(ss: @["In", "bar"])
    echo "'Now in bar proc and ca.ss=", $ca.ss, " and ac.ss=", $ac.ss
  echo "I'm in foo proc and ac.ss=", $ac.ss
  bar()

foo()
```
There are 2 `AutoClose` variable objects defined and I would expect 2 calls to the destructor, one per object. Also, because my custom destructor has not freed the `ss` field yet, I would expect to see its value printed. That's not what happens...

### Current Output
```
$ nim c --gc:arc bar3
Hint: used config file '.../.choosenim/toolchains/nim-#head/config/nim.cfg' [Conf]
Hint: used config file '.../.choosenim/toolchains/nim-#head/config/config.nims' [Conf]
....
Hint:  [Link]
Hint: 20593 lines; 0.219s; 20.555MiB peakmem; Debug build; proj: .../bar3; out: .../bar3 [SuccessX]

$ ./bar3
In AutoClose destructor; releasing=@[]
I'm in foo proc and ac.ss=@["In", "foo"]
'Now in bar proc and ca.ss=@["In", "bar"] and ac.ss=@["In", "foo"]
In AutoClose destructor; releasing=@["In", "bar"]
In AutoClose destructor; releasing=@["In", "foo"]
```

### Expected Output
When compiled without `--gc:arc`, the destructor is only called once per object variable. But it still does not display the content of the `ss` field (I don't understand why).
```
$ nim c bar3
Hint: used config file '.../.choosenim/toolchains/nim-#head/config/nim.cfg' [Conf]
Hint: used config file '.../.choosenim/toolchains/nim-#head/config/config.nims' [Conf]
....CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: bar3.nim

Hint:  [Link]
Hint: 22210 lines; 0.692s; 25.57MiB peakmem; Debug build; proj: .../bar3; out: .../bar3 [SuccessX]

$ ./bar3
In AutoClose destructor; releasing=@[]
I'm in foo proc and ac.ss=@["In", "foo"]
'Now in bar proc and ca.ss=@["In", "bar"] and ac.ss=@["In", "foo"]
In AutoClose destructor; releasing=@["In", "bar"]
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-10-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3bdc0005211b0d543e0ff48ccf6bc5a9f2a2a30b
active boot switches: -d:release
```

**Comment by ghost** [comment]
IIRC destructors are allowed to be called on uninitialized objects and you need to check for that.

**Comment by jrfondren** [comment]
You can explore what's going on with `--expandArc:foo`

In your code:

```
var                                                                                 
  :env                                                                              
  :tmpD
  :tmpD_1
try:
  `=destroy`(:env)
  internalNew(:env)
  `=sink`(:env.ac1, AutoClose(ss:
    wasMoved(:tmpD)
    `=copy`(:tmpD, ["In", "foo"])
    :tmpD))
  proc bar(:envP) =
    let ca = AutoClose(ss: ["In", "bar"])
    echo ["\'Now in bar proc and ca.ss=", `$`($_1ca.ss), " and ac.ss=", `$`(
        $_1ac.ss)]

  echo ["I\'m in foo proc and ac.ss=",
    :tmpD_1 = $_1:env.ac1.ss
    :tmpD_1]
  (bar, :env)()
finally:
  `=destroy_1`(:tmpD_1)
  `=destroy`(:env)
```

In a version where `bar` is moved out of `foo` (and no longer refers to `ac`:

```
var                                                                                 
  ac                                                                                
  :tmpD                                                                             
  :tmpD_1                                                                           
try:
  ac = AutoClose(ss:
    wasMoved(:tmpD)
    `=copy`(:tmpD, ["In", "foo"])
    :tmpD)
  echo ["I\'m in foo proc and ac.ss=",
    :tmpD_1 = $ac.ss
    :tmpD_1]
  bar()
finally:
  `=destroy`(:tmpD_1) 
  `=destroy_1`(ac)
```

So in your current output you get the two expected destroys, once per object, and then you also see a destroy on the closed-over environment for `bar`.

**Comment by pmetras** [comment]
I can now understand that the `--gc:arc` version is *more* correct than the default one as it calls the destructor I defined on `ac` and `ca` variables, giving me the chance to free the `ss` field. But this custom destructor should not be called for the inner environment. It should be a system generated one, and it should not print `In AutoClose destructor; releasing=[]` shouldn't it?

**Comment by pmetras** [comment]
And if I interpret correctly the output of `--expandArc`, the custom ``proc =`destroy`(x: var AutoClose)`` is named ``destroy_1``. The other ``destroy`` calls are the default ones, so they should not print the AutoClose message.

Like @Yardanico said, for the moment I can test if the destructor is called on a non-initialized object (that's what seems to happen in my project code) to work around this behaviour.

**Comment by Clyybber** [comment]
@pmetras No, this is in the spec https://github.com/nim-lang/Nim/blob/devel/doc/destructors.rst#destroy-hook
You have to check the state of your object in your destructor in this case to get the behaviour you want.

**Comment by cooldome** [comment]
Closed as not an issue
