### ISSUE TITLE
HI! I just came across some DateTime conversion issue seeing soem 40 minutes getting lost on the way. testing on linux

### ISSUE THREAD

**Issue by LucasUllon** [nim-lang/Nim#15799]
``` import times

let date_time_format_string = "YYYY-MM-dd'T'HH:mm:ss'.'ffffffzzz"
let date_time_format = date_time_format_string.initTimeFormat()
let date_time = initDateTime(1, mJan, 1900, 0, 0, 0, 0, utc()).local()

let date_time_string = date_time.format(date_time_format_string)

let current_time = times.now()
echo "system time :" & current_time.format(date_time_format_string)
echo "timezone    : " & $current_time.timezone 
echo "utcOffset   : " & $current_time.utcOffset
echo "isDst       : " & $current_time.isDst
echo "\n1900-01-01&00:00:00.00000+00:00 in local time zone: "
echo "date_time       : " & $date_time 
echo "date_time_string: " & date_time_string
echo "date_time parse : " & $date_time_string.parse(date_time_format, local()) ```
```

### Output
system time :2020-10-30T17:44:17.553106-03:00
timezone    : LOCAL
utcOffset   : 10800
isDst       : true

1900-01-01&00:00:00.00000+00:00 in local time zone: 
date_time       : 1899-12-31T20:09:20-03:50
date_time_string: 1899-12-31T20:09:20.000000-03:50
date_time parse : 1899-12-31T20:08:40-03:50

**Comment by SFR0815** [comment]
Hi ran it on a Windows machine and got the following: 

```
system time :2020-10-30T22:24:58.123156-04:00  
timezone    : LOCAL
utcOffset   : 14400 
isDst       : true   
1900-01-01&00:00:00.00000+00:00 in local time zone:           
date_time       : 1899-12-31T19:00:00-05:00       
date_time_string: 1899-12-31T19:00:00.000000-05:00        
date_time parse : 1899-12-31T19:00:00-05:00
```

**Comment by GULPF** [comment]
@LucasUllon What timezone are you in? You can run `timedatectl` to see the proper timezone name.

**Comment by LucasUllon** [comment]
@GULPF hi, this is what throws me on the console:
timedatectl: 
               Local time: lun 2020-11-02 04:28:21 -03  
           Universal time: lun 2020-11-02 07:28:21 UTC  
                 RTC time: lun 2020-11-02 07:28:21      
                Time zone: America/Asuncion (-03, -0300)
System clock synchronized: no                           
              NTP service: inactive                     
          RTC in local TZ: no

**Comment by GULPF** [comment]
@LucasUllon Thank you. What's happening is that the actual UTC offset for `America/Asuncion` on `1899-12-31` is not `-03:50` but `-03:50:40` (many timezones have subminute UTC offsets for very old dates), which accounts for the missing 40 seconds. You can show the full UTC offset of a `DateTime` using the `zzzz` format. Here's a modified example:

```nim
import times

const Format = "YYYY-MM-dd'T'HH:mm:ss'.'ffffffzzzz"
let date_time = initDateTime(1, mJan, 1900, 0, 0, 0, 0, utc()).local()

echo "date_time_string: " & date_time.format(Format)
echo "date_time parse : " & date_time.format(Format).parse(Format, local()).format(Format)
```
Output (when using `America/Asuncion` as the local timezone):
```
date_time_string: 1899-12-31T20:09:20.000000-03:50:40
date_time parse : 1899-12-31T20:09:20.000000-03:50:40
```

**Comment by LucasUllon** [comment]
@GULPF Thank U !
