### ISSUE TITLE
Can't exportc predefined types from standard library with a stable name

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1579]
The [exportc pragma](http://nimrod-lang.org/manual.html#exportc-pragma) is fine for procs or types you have control over, but it can't be used to export to C types previously defined by the standard library. In my case I'm trying to export a proc to C which uses a [PStringTable](http://nimrod-lang.org/strtabs.html#PStringTable). I've tried several things, like creating aliases:

``` nimrod
type
  LR_StringTable {.extern:"hahah".} = distinct PStringTable

  #LR_StringTable {.exportc.} = ref TStringTable

  TestStruct {.exportc:"thehu".} = object
    nil

proc testProc*(options: TestStruct, another: LR_StringTable) {.exportc.} =
  var a = another
  discard
```

However in all cases the generated header file contains a numbered symbol which doesn't sound like a good idea for source code compatibility, should this number change in the future:

``` c
...
typedef struct thehu thehu;
typedef struct tstringtable128812 tstringtable128812;
struct  thehu  {
char dummy;
};
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(NI, getRefcount)(void* p);
N_NIMCALL(void, testProc)(thehu options, tstringtable128812* another);
...
```

**Comment by andreaferretti** [comment]
The identifier mangling logic is changed nowadays - it needed to be stable for compilation caching. So I get

```c
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw 
```

Is this guaranteed to be stable?

**Comment by Araq** [comment]
> Is this guaranteed to be stable?

No.

**Comment by Araq** [comment]
But it's stable enough for header file support. Closing.
