### ISSUE TITLE
Please re-enable semistatic[t]

### ISSUE THREAD

**Issue by fowlmouth** [nim-lang/Nim#1580]
Considering that the code below does not compile, there is no alternative to semistatic[t] except to implement it. Ref #1472

``` nimrod
proc foo (some: static[string]) = echo "static ", some
proc foo (some: string) = echo "dynamic ", some

let x = "dynamic"
foo "static"
foo x
```

**Comment by zah** [comment]
Implemented in f663ca7. `static[T]` overloads will have precedence over normal procs (similar to `var` overloads)
