### ISSUE TITLE
[docs] search results section is not suitable for dark mode

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#15837]
search index style does not fit with dark mode
![image](https://user-images.githubusercontent.com/33235928/98050612-5cdb3500-1e32-11eb-8eee-1580ba33cdfa.png)

**Comment by ringabout** [comment]
This issue has been fixed in devel docs
https://nim-lang.github.io/Nim/system.html

![image](https://user-images.githubusercontent.com/43030857/98058258-30013f00-1e7f-11eb-8bbe-c40643bf9590.png)
