### ISSUE TITLE
json.to crashes (SIGSEGV) when object attribute is a JsonNode and the key is not there

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#15835]
json.to crashes when object attribute is a JsonNode and the key is not there

### Example
```nim
import json
type
  Foo = object
    ii*: int
    data*: JsonNode

block:
  const jt = """{"ii": 123, "data": ["some", "data"]}""" # edit: had typo (a123) here
  let js = parseJson(jt)
  echo js.to(Foo) # <--- works as expected data is a JsonNode

block:
  const jt = """{"ii": 123}"""
  let js = parseJson(jt)
  echo js.to(Foo) # <--- crash illegal storage access, but should give KeyError
```

### Current Output
Traceback (most recent call last)
c:\Users\david\projects\muk\private\jsonBug.nim(15) jsonBug
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(1244) to
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(1137) initFromJson
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(1014) initFromJson
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(562) copy
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'c:\Users\david\projects\muk\private\jsonBug.exe '

### Expected Output
```
c:\Users\david\projects\muk\private\jsonBug.nim(10) jsonBug
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(1244) to
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(1137) initFromJson
C:\Users\david\.choosenim\toolchains\nim-1.4.0\lib\pure\json.nim(958) initFromJson
Error: unhandled exception:  [KeyError]
```

### Additional Information
C:\Users\david>nim --version
Nim Compiler Version 1.4.0 [Windows: amd64]
Compiled at 2020-10-24
Copyright (c) 2006-2020 by Andreas Rumpf                                                                                                                                                                        active boot switches: -d:release

**Comment by Araq** [comment]
There is no crash for me, I get "Error: { expected".

**Comment by ghost** [comment]
@Araq there was a typo in the original code sample I think:
```nim
import json
type
  Foo = object
    ii*: int
    data*: JsonNode

block:
  const jt = """{"ii": 123, "data": ["some", "data"]}"""
  let js = parseJson(jt)
  echo js.to(Foo) # <--- works as expected data is a JsonNode

block:
  const jt = """{"ii": 123}"""
  let js = parseJson(jt)
  echo js.to(Foo) # <--- crash illegal storage access, but should give KeyError
```
