### ISSUE TITLE
Compiler warning on mismatching case/spelling

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#15848]
Nim allows identifiers that differ in `cAse` and `sp_ell_ing` - however, the spelling used in the declaration can be considered canonical. 

For security-critical code, the introduction of alternate spellings can lead to vulnerabilities code injection (specially considering name clashes in larger project), and makes it harder to audit the code using tooling that is unaware of the naming, and generally creates confusion for developers reading the code.

As such, we would benefit from a compiler flag that, similar to `--styleCheck`, emits a warning when an alternate spelling is used, along with an option to disable it per-module, per-symbol or per-use (via pragmas?)

**Comment by Araq** [comment]
Well ``--styleCheck`` exists and to disable it per-module, use this construct

```nim

when defined(nimHasStyleChecks):
  {.push styleChecks: off.}

# code here

when defined(nimHasStyleChecks):
  {.pop.} # {.push styleChecks: off.}
```

What else do you need?

**Comment by arnetheduck** [comment]
the style check is slightly different - it checks that symbols adhere to NEP-1 - ie that variables use the right capitalization etc - but for various reasons, we might be using a different style for some symbols, and what we need is that the compiler _only_ checks that usage matches the declaration.

**Comment by Araq** [comment]
Ah ok.
