### ISSUE TITLE
Error: cannot 'importc' variable at compile time; FE_DIVBYZERO [devel regression]

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#15843]
Hello,

There's a recent regression on devel that's causing all my Nim project Travis CI jobs to fail with:

```
Hint: used config file '/home/travis/build/kaushalmodi/hello_musl/nim/4c19c5dfae01638ae66fc2c1561762d94fb36a1a/config/config.nims' [Conf]

/home/travis/build/kaushalmodi/hello_musl/nim/4c19c5dfae01638ae66fc2c1561762d94fb36a1a/lib/pure/fenv.nim(17, 3) Error: cannot 'importc' variable at compile time; FE_DIVBYZERO

FAILURE
```

[Travis failure log][1]

The error happens when my [`config.nims`][2] is used on Travis, and nim devel is being built. I am unable to reproduce this error locally.

### Example

Build nim devel 4c19c5dfae01638ae66fc2c1561762d94fb36a1a on Travis CI.

### Current Output

Fails with the above error, probably because of the config.nims.

### Expected Output

nim devel is expected to build fine.

### More Info

- The last known nim devel that built successfully on Travis was 485d4ff802c361f363d2f455b98abc5db1a7082d, about a week back (I run weekly Travis cron jobs).
- Here the the commits between the last known good commit and the first known failing commit: https://github.com/nim-lang/Nim/compare/485d4ff802c361f363d2f455b98abc5db1a7082d...4c19c5dfae01638ae66fc2c1561762d94fb36a1a

```
$ nim -v
Nim devel version 4c19c5dfae01638ae66fc2c1561762d94fb36a1a
```

[1]: https://travis-ci.org/github/kaushalmodi/hello_musl/jobs/741498569#L725
[2]: https://github.com/kaushalmodi/nim_config/blob/master/config.nims

**Comment by ringabout** [comment]
I find a situation with similar error messages(but it is wrong indeed in Nim v 1.4): use it in compile time:
```nim
var
  FE_DIVBYZERO* {.importc, header: "<fenv.h>".}: cint


const x = FE_DIVBYZERO
```

got:

```
Error: cannot 'importc' variable at compile time; FE_DIVBYZERO
```

**Comment by ringabout** [comment]
find a similar issue:
https://github.com/nim-lang/Nim/issues/10056

**Comment by Araq** [comment]
Report the problem in a way that we can reproduce it.

**Comment by kaushalmodi** [comment]
Hello @Araq , I always provide a recipe to reproduce the issue, except for this case. This issue shows up only on Travis CI when building Nim devel. The link in my original post of this thread shows where this error happens during the build process.

**Comment by kaushalmodi** [comment]
Using `build_all.sh` to build Nim devel on Travis fixed this problem.

Thanks to @timotheecour for his comment in https://github.com/nim-lang/Nim/issues/17907#issuecomment-831654235 .
