### ISSUE TITLE
Nim community survey questions about compilation errors

### ISSUE THREAD

**Issue by haxscramper** [nim-lang/Nim#15855]
### Summary

Nim community survey 2020 to include the following questions:

- `how satisfied you are with compilation errors messages?` (scale 1-5/1-10/whatever number of alternatives other questions like this have).
- `what would you improve in compilation errors?` (free-form text input (maybe some common options and "other", but I'm not sure what the "other" part should be))

### Description

I'm planning (thinking about) improving nim compilation errors - *this is of course will be first submitted as RFC and properly discussed* - and responses to these question would be highly valuable in for this task.

### Additional Information

The 2016 community survey had a listing of free-form questions for "aspects of Nim do you find most displeasing", and "Quality of error messages" is ranked third (after "Small community size." and "Lack of in-depth tutorials."). 2017 survey does not free-form responses by popularity but this response is still present, and 2018/2019 does not provide full (or top-10) listings for this, but I believe the issue is still present - I'm not aware of any dramatic quality changes in compiler errors since 2017.

**Comment by Araq** [comment]
- Improve error messages for "X can have side effects" would probably be high in the list.
- Also "Expected X but got X" (you got the thing you wanted?!) are sometimes hard to understand.

**Comment by timotheecour** [comment]
Expand `--declaredLocs` to other errors.

Instantiation errors should show details as in sigmatch errors (eg, 1st mismatch at position 2 etc)

Discriminant kind errors should show what kind we got

More generally, show more relevant runtime/CT context, at least optionally; context is usually more informative than even a well crafted static string error message.

**Comment by haxscramper** [comment]
I think `what would you improve in compilation errors?` should be a write-in instead of some default options + "other". The reason: if something is added to the default option we *already know* this is something that needs to be optimized and therefore don't need to tell us about this.
