### ISSUE TITLE
Error: 'newHttpHeaders' can have side effects

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#15851]
# Examples

```console
$ nim c --experimental:strictFuncs Nim/lib/pure/httpcore.nim
Nim/lib/pure/httpcore.nim(122, 6) Error: 'newHttpHeaders' can have side effects

$
```

# Current Output

```nim
Error: 'newHttpHeaders' can have side effects
```

# Possible Solution

Make `newHttpHeaders` back to `proc`.

# Additional Information

- Bug introduced in https://github.com/nim-lang/Nim/pull/15457#issue-496662964 /cc @xflywind 

# System Information

<details>

```json

{
  "compiled": "2020-10-20T01:21:43",
  "NimVersion": "1.5.1",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2020-11-05T10:37:07-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 397312,
  "getTotalMem": 528384,
  "getOccupiedMem": 68400,
  "countProcessors": 4,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "/home/juan/.cache/nim/nimbug_r",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-1.4.0/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.12.0 compiled at 2020-10-30 00:39:01\ngit hash: couldn't determine git hash",
  "nimgrep": "1.5",
  "nimsuggest": "Nim Compiler Version 1.5.1 [Linux: amd64]\nCompiled at 2020-10-30\nCopyright (c) 2006-2020 by Andreas Rumpf\n\ngit hash: 33e258c72fe9c06410b30c5bc4364626c4f6ecb1\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.7.2 (2020-10-17 14:56:03) [linux/amd64]",
  "gcc": "gcc (GCC) 10.2.0",
  "clang": "clang version 10.0.1",
  "git": "2.29.2",
  "node": "v15.1.0",
  "python": "3.8.6",
  "ssd": true
}
```

</details>

# Proposed Labels

```csv
minor, easy
```

**Comment by ringabout** [comment]
Thanks!
I will revert some `func` to `proc`.

**Comment by Araq** [comment]
@xflywind It seems wiser to override the compiler's analysis with a ``{.cast(noSideEffect).}: `` block.

**Comment by ringabout** [comment]
Yea, I do think these funcs shouldn't have side effects.

I will use `{.cast(noSideEffect).}:`.

Edited:
```nim
{.cast(noSideEffect).}:
  func newHttpHeaders*(keyValuePairs:
      openArray[tuple[key: string, val: string]], titleCase=false): HttpHeaders =
```
This doesn't work.

**Comment by dom96** [comment]
The commit that caused this bug shouldn't have been merged, why wasn't running ``nim c --experimental:strictFuncs Nim/lib/pure/httpcore.nim`` part of the test plan? Do we have other files that need to be checked?

**Comment by ringabout** [comment]
testament already has `tests/effects/tstrict_funcs.nim` to test strictfuncs.

Have added it in last pull request.
https://github.com/nim-lang/Nim/pull/15852/files

I don't know whether we should document that and where to document it?
