### ISSUE TITLE
[docs] overlapping texts

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#15857]
![image](https://user-images.githubusercontent.com/33235928/98297128-3e04ac00-1fb4-11eb-83da-27874fa41352.png)

**Comment by ghost** [comment]
that was fixed already :)

E.g. check https://nim-lang.org/docs/algorithm.html - no issue (maybe your browser cached it)

**Comment by AmjadHD** [comment]
No still seeing it.

**Comment by ghost** [comment]
@AmjadHD in that link? Then clear your browser's cache, or maybe it has to do with Cloudflare CDN or something, but it is already fixed and we even dropped the caches so it updates.

![image](https://user-images.githubusercontent.com/21169548/98310495-280be100-1fde-11eb-903d-86b09433697d.png)
That's how it looks for me right now

**Comment by AmjadHD** [comment]
@Yardanico Thanks, that was it 👍
