### ISSUE TITLE
[docs] distracting table rows on hover

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#15882]
I'm not sure what is the benefit or the aesthetic in having table rows change style when hovered:
![table_row_hover](https://user-images.githubusercontent.com/33235928/98454335-c2e1f800-2163-11eb-9fbd-cc6ea984eb61.gif)
just a suggestion, remove it.

**Comment by Araq** [comment]
The benefit is readability for more complex tables. I think it's fine.

**Comment by AmjadHD** [comment]
Can't you just change style on click ? That would be less distracting and still provides good readability.

**Comment by Araq** [comment]
Why would I even "click" on the row? It's not a button.
