### ISSUE TITLE
Dynamic linking to a C library, (raylib) causes incorrect behaviour, on Linux

### ISSUE THREAD

**Issue by Ryan1729** [nim-lang/Nim#15899]
Trying to dynamically link Nim code to [raylib](https://www.raylib.com/) via [Raylib-Forever](https://github.com/Guevara-chan/Raylib-Forever), on Linux, and then playing audio, produces incorrect sound output.

### Example
The code is available at [this repo](https://github.com/Ryan1729/nim-raylib-forever-raylib-audio-bug) containing a single `.nim` file and some additional data. I'm not aware of a way to make it smaller.

### Current Output
The code linked above plays the one of two sound files twice, when it should play one sound then another.

### Expected Output
The code linked above plays the one of two sound files twice, when it should play one sound then another.

### Possible Solution

* I don't really know, but it seems like an issue with the generated C to me. Undefined Behavior maybe?

### Additional Information
[Raylib-Forever](https://github.com/Guevara-chan/Raylib-Forever) provides Nim bindings to a C library called [raylib](https://www.raylib.com/). The code that reproduces the bug is based of an example for raylib, that was ported from C to Nim. If I compile the C version of the example it works correctly, but the Nim version does not. I reduced down the bug to a single `.nim` file, (that dynamically links to raylib) by taking just the amount needed from the example code and Raylib-Forever to play the sounds and immediately exit, but the bug persisted. That's why I think this is a Nim bug, rather than a bug in either raylib or Raylib-Forever.

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-10
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d8e7caf5dd4ab70b7429896c1587cde992e7855a
active boot switches: -d:release
```

**Comment by Araq** [comment]
The wrapper is wrong, it must use the ``.bycopy`` pragma for the object declarations. c2nim would have added these btw.
