### ISSUE TITLE
Crash dereferencing object via a view object

### ISSUE THREAD

**Issue by snej** [nim-lang/Nim#15897]
Getting a property of an object, via a view object on it, crashes or produces a bogus value.

### Example
```nim
type Outer = ref object 
  value: int
type Inner = object
  owner: var Outer
  
var o = Outer(value: 1234)
var v = Inner(owner: o).owner.value
echo "Got value = ", v
assert v == 1234
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Running with LLDB:
```
Process 98834 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4d2)
    frame #0: 0x00000001000125ea NimRunner`NimMainModule + 218
NimRunner`NimMainModule:
->  0x1000125ea <+218>: movq   (%rcx), %rcx
    0x1000125ed <+221>: movq   %rcx, 0x16e9c(%rip)       ; v__2fsGT829agC1BeFmwktokVg
    0x1000125f4 <+228>: movq   $0x8, -0x50(%rbp)
    0x1000125fc <+236>: leaq   0x1337(%rip), %rcx        ; "/private/var/folders/14/5kpdsdb13gqfmg00gx2_kdlr0000gn/T/CodeRunner/NimRunner.nim"
(lldb) p $rcx
(unsigned long) $0 = 1234
```

### Expected Output
```
Got value = 1234
```

### More info

Note that this did not require `{.experimental: "views".}`, probably since the view object is only a temporary.

If I change the type of `Outer` to `ref object of RootObj`, the crash goes away, but the value of `v` is 8. That value is quite repeatable, and also occurs in my real code that this is reduced from. In my code `value` is declared as `pointer`; it's a pointer to a C struct, so a crash results when a C function tries to dereference it, which is how I found the bug.

If I change `Outer` to `object`, I instead get a C compile error, which is probably #15885.

### Configuration

Found in 1.4, but reproduces with latest devel:
```
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2020-11-09
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 49f68122e658ba7bcc13340fe157e276b4033a90
active boot switches: -d:release
```

**Comment by RSDuck** [comment]
this seems to work now.
