### ISSUE TITLE
Config: allow custom sections

### ISSUE THREAD

**Issue by cybernetlab** [nim-lang/Nim#15902]
### Summary

It would be nice to allow custom section names in `*.nimble` files like it done in `package.json` for example or in another package managers.

### Description

Sometimes user libs needs to store project-specific configurations somewere. The `*.nimble` whould be the best choise.

**Comment by ringabout** [comment]
It sounds like an issue/feature regarding nimble.
Please open issue here instead:
https://github.com/nim-lang/nimble

Or you can ask question in `nimble` channel in Discord server of Nim
https://discord.gg/HgfXCNY8
