### ISSUE TITLE
'--genMapping' doesn't work

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1592]
Trying to use '--genMapping' on koch.nim doesn't work:

```
gcc: error: koch.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_system.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_os.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_strutils.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_parseutils.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_times.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_winlean.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_parseopt.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_osproc.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_strtabs.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_hashes.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_streams.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: stdlib_cpuinfo.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: nversion.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
Error: execution of an external program failed
```

A mapping file _is_ created, however it contains only a small amount of information about what is being compiled. The 'symbols' section of the file is empty.

First glance suggests that the compiler isn't correctly referencing the generated C files.

**Comment by PMunch** [comment]
Has this been broken since 2014? I can't get `--genMapping` to work, complaining that libregex.c isn't found.

**Comment by PMunch** [comment]
Turns out I can get it to compile by setting `--nimcache:./` and copying `nimbase.h` to the current directory before compiling. The symbol section of the the mapping is still empty however.

**Comment by Araq** [comment]
``--genMapping`` should just be removed.

**Comment by data-man** [comment]
> --genMapping should just be removed.

Please, don't remove. It can be very useful.

**Comment by andreaferretti** [comment]
@data-man how so? If I understand correctly it has not been working from 2014

**Comment by data-man** [comment]
@andreaferretti 
> how so?

In some tool for demangle Nim's identifiers and for their readability for humans, e.g.

> If I understand correctly it has not been working from 2014

Then I'll investigate this.

**Comment by narimiran** [comment]
As [stated](https://github.com/nim-lang/Nim/pull/9992#issuecomment-450954219) in #9992: "It's not worth it. Let's do nothing instead." — I guess that means we can put `won't fix` label on this one.
