### ISSUE TITLE
both tools/niminst and nim-lang/niminst are getting updated / diverge; need to mark 1 of those as readonly

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15946]
(extracted from https://github.com/nim-lang/RFCs/issues/206 which sadly got closed despite several points left unaddressed)

As mentioned in https://github.com/nim-lang/RFCs/issues/206, external projects should be moved out of Nim's index; this issue focuses on niminst;

it's pretty bad, both copies (tools/niminst => nim-lang/niminst) have diverged, with different bugs being fixed in both (see nim-lang/Nim#13406 or https://github.com/nim-lang/Nim/pull/15945 which just got sent out).

## proposal
* rebase tools/niminst onto nim-lang/niminst
* then remove tools/niminst, and (if needed) install it similarly to https://github.com/nim-lang/Nim/pull/13850 (and preferably in dist)

### Additional Information
devel 1.5.1 1413818aa14fd694d362326f428b470fa22e1a0a

**Comment by ringabout** [comment]
I agree on removing one of them.
And Niminst is missing from installation
https://github.com/nim-lang/Nim/issues/11433

**Comment by Araq** [comment]
> proposal
> rebase tools/niminst onto nim-lang/niminst
> then remove tools/niminst, and (if needed) install it similarly to #13850 (and preferably in dist)

Accepted. Bring it on please.

**Comment by xflywind** [comment]
> rebase tools/niminst onto nim-lang/niminst
no need to rebase, no useful new commits

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/17580#issuecomment-809932505
> Instead the niminst Nimble package should be removed.

@xflywind in that case we should:
* merge changes from nim-lang/niminst into tools/niminst
* manually merge remaining PR https://github.com/nim-lang/niminst/pull/1 (if applicable)
* archive https://github.com/nim-lang/niminst after adding a final note in the README pointing to use nim/tools/niminst

**Comment by ringabout** [comment]
> merge changes from nim-lang/niminst into tools/niminst

no useful additions.

> archive https://github.com/nim-lang/niminst after adding a final note in the README pointing to use nim/tools/niminst

it is inconvenient for me. Please someone has rights to do that.

**Comment by timotheecour** [comment]
> no useful additions.

indeed, I just checked as well.

> it is inconvenient for me. Please someone has rights to do that.

done; i added a note in https://github.com/nim-lang/niminst description on the right pointing to this issue, and marked it as archived; it can always be unarchived if every needed
