### ISSUE TITLE
In for loop `_` is accessible

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#15972]
Unlike pretty much anywhere else `_` is accessible as a single parameter in a for loop.
### Example
```nim
for _ in ["a"]:
  echo _
```

### Current Output
```
a
```

### Expected Output
```
Error: undeclared identifier: '_'
```

Tested on pretty much all Nim versions.

**Comment by disruptek** [comment]
Feature.

**Comment by timotheecour** [comment]
> Feature.

agreed; but should be documented (maybe it is, haven't found it)

**Comment by beef331** [comment]
@timotheecour why is this a feature, does it not defeat the purpose of `_` being an unused value, which is consistent for `for _, _ ...`, tuple unpacking, and variable declaration?

**Comment by timotheecour** [comment]
my bad, i misread accessible as inaccessible.
you're right, this should give `Error: undeclared identifier: '_'` in top post.
```nim
when true:
  let (_, a, _) = (1,2,3)
  echo _ # Error: undeclared identifier: '_'
when true:
  let _ = 1
  echo _ # Error: undeclared identifier: '_'
```

**Comment by beef331** [comment]
Ah, thanks. Thought I was losing my mind after both you and disruptek said it's a feature.

**Comment by ringabout** [comment]
How about this?
```nim
block _:
  echo "123"
  break _
```
I would expect this to error too.

```
Error: undeclared identifier: '_'
```
