### ISSUE TITLE
initNimsuggest fails ,reporting compiler/extccomp.nim 631 `externalFileChanged` ` of backendInvalid: doAssert false` 

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#15978]
initNimsuggest fails ,reporting compiler/extccomp.nim 631 `externalFileChanged` ` of backendInvalid: doAssert false`  

I checked this PR, backend default to `backendInvalid`
https://github.com/nim-lang/Nim/commit/c777f2fb608e1f42daf31d314dda0050f6354acd#diff-2179cfe66f0e3b26b6475c540e7af193fcaef3ccad352b45f43ecb488e99cc8b

### Current Output
```
AssertDefeat  
```

### Expected Output
externalFileChanged ignore backendInvalid at that time.
```

```

### Possible Solution

* specify `--backend:c` to project config
*  of backendInvalid: return false or just discard

```
$ nim -v
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2020-11-14
# make sure to include the git hash if not using a tagged release
```

**Comment by Clyybber** [comment]
See https://github.com/nim-lang/nimsuggest/issues/117 and https://github.com/nim-lang/Nim/pull/15602
