### ISSUE TITLE
regression(0.20.0 => devel): var params assignment gives silently wrong results in VM

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15974]
regression(0.20.0 => devel): in VM, a copy of a var param is affected when that param is later re-assigned.

### Example
```nim
when true:
  type Foo = object
    f0: int

  proc fn(a: var Foo) =
    var s: Foo
    a = Foo(f0: 2)
    s = a
    doAssert s.f0 == 2
    a = Foo(f0: 3)
    echo s.f0

  proc main()=
    var a = Foo(f0: 1)
    fn(a)

  static: main()
  main()
```

### Current Output
CT:
3
RT:
2

### Expected Output
CT:
2
RT:
2

### Additional Information
regression:
* fails with: devel 1.5.1 c39fa0d49535da7f803d9972abdb15d09eed92a6, and 1.0.2
* works with: nim 0.20.0
* 1.0.0 gives: `nfIsRef in regs[ra].node.flags`  [AssertionError]
* likewise in other cases where you'd have a copy, eg: `var s: seq[Foo]` and `s.add a`
* root cause for https://github.com/flyx/NimYAML/issues/91 (nimyaml gives wrong results at CT), after a painful, painful reduction

## git bisect output
```
162d74db91412d98a4a67b28c1e1c9c1d79a9873 is the first bad commit
commit 162d74db91412d98a4a67b28c1e1c9c1d79a9873
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Thu Sep 19 14:34:56 2019 +0200

    fixes #10981; fixes #7261 (#12217)

 compiler/vmgen.nim    |  5 ++-
 tests/vm/tmisc_vm.nim | 99 +++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 103 insertions(+), 1 deletion(-)
bisect run success
```
=> points to https://github.com/nim-lang/Nim/pull/12217 /cc @Araq

**Comment by jangko** [comment]
same first bad commit with #12551 and similar symptom involving var param.
