### ISSUE TITLE
`repr` inserts a spurious newline at RT (unlike in VM)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16025]
repr inserts a spurious newline at RT (unlike in VM)

### Example
```nim
when true:
  const a = cast[pointer](nil)
  echo a.repr
  static: echo a.repr
```

### Current Output
CT:nil
RT:nil\n

### Expected Output
CT:nil
RT:nil

### Additional Information
devel 1.5.1 632af8afad92594da050a5f7fd784ea111c3cc54

**Comment by ringabout** [comment]
It works with `--gc:arc`.

```nim
when true:
  const a = cast[pointer](nil)
  echo a.repr
  echo "end"
  static: echo a.repr
```

```
nil
CC: test.nim
Hint:  [Link]
Hint: 21274 lines; 0.574s; 28.906MiB peakmem; Release build; proj: D:\QQPCmgr\Desktop\Nim\test.nim; out: D:\QQPCmgr\Desktop\Nim\test.exe [SuccessX]
Hint: D:\QQPCmgr\Desktop\Nim\test.exe  [Exec]
nil
end
```

**Comment by ringabout** [comment]
`repr` will add `\n` for nilable types. Maybe it works as expected.
```nim
type Test = ref object
let t = Test()
echo t.repr
echo "end"
```
Output:
```
ref 00007FF4FDE0F050 --> []

end
```

![image](https://user-images.githubusercontent.com/43030857/99542055-8f695e00-29ec-11eb-9fe9-e3f1214c3830.png)

**Comment by timotheecour** [comment]
> Maybe it works as expected.

nah, it's arbitrary, see https://github.com/nim-lang/Nim/pull/16034
