### ISSUE TITLE
`nim js --gc:arc` gives bad error:  undeclared identifier: '+!'

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16033]
Function `echo` outputs the wrong string.

### Example
```nim
# can be an empty file
```

### Current Output
nim js --gc:arc --skipparentcfg --skipusercfg main.nim
lib/system/arc.nim(84, 42) Error: undeclared identifier: '+!'

### Expected Output
* either make `--gc:arc` a noop (and code should work)
* or give error `--gc:arc` not supported with js backend

### Additional Information
devel 1.5.1 87d3e5331a7838aa255deca8a840c2080b5424ce

this (or fixing it by making it not work with js backend) would prevent things like this in testament:
```nim
discard """
  targets: "c cpp js"
  matrix: ";--gc:arc"
"""
```
but testament could also be made smart about this and skip `js --gc:arc` combination, although this isn't trivial to do it cleanly

### note
curiously, this works:
```nim
# main2.nim:
echo compileOption("gc", "arc")

# cmd:
nim r -b:js --gc:arc main2.nim
false
```
likewise with `nim js -r -b:js --gc:arc main2.nim`

but this doesn't:
```
nim js -r --gc:arc main2.nim
Error: undeclared identifier: '+!'
```

**Comment by Clyybber** [comment]
@timotheecour It seems `conf.backend` isn't set early enough when doing `nim js --gc:arc` for https://github.com/nim-lang/Nim/pull/15059/files to pick up
