### ISSUE TITLE
Create NuGet/Chocolatey Package

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1603]
If one hasn't been already, create and/or update Nim packages for NuGet and Chocolatey, and advertise that fact on the website

**Comment by reactormonk** [comment]
What are either of those?

**Comment by kirbyfan64** [comment]
Chocolatey is basically apt-get for Windows.

I can probably do this since I'm familiar with Chocolatey and uploaded a PyPy package (although it's like 6 months old...).
