### ISSUE TITLE
unittest.check (or setProgramResult) doesn't work with js (works with nodejs)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16074]
# Example
```nim
import std/unittest
proc main()=
  check 1 == 2
  check 1 == 3
main()
```

### Current Output
nim r -b:js main
Error: Error: unhandled exception: /Users/timothee/git_clone/nim/Nim_devel/lib/std/exitprocs.nim(87, 16) `false`  [AssertionDefect]

nim r -b:js -d:nodejs main
gives proper error (giving Expected Output)

### Expected Output
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11338.nim(7, 10): Check failed: 1 == 2
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11338.nim(8, 10): Check failed: 1 == 3
Error: execution of an external program failed: '/usr/local/Cellar/node/14.7.0/bin/node /Users/timothee/git_clone/nim/timn/build/nimcache/t11338.js '

### Possible Solution

I added support for unittest.check for `js -d:nodejs` in https://github.com/nim-lang/Nim/pull/14676
But for `js` it doesn't yet work, but could with a possibly simple solution.

emulate `setProgramResult` by intercepting calls to `exit` in js (the rare case) and adding a top-level proc to check whether a programResult variable was set to != 0 (the common case).
This should cover most (or all) cases.

Note that -d:nodejs may not be suitable as a workaround, it affects semantics (eg unsuitable for use in browser)

### Additional Information
devel 1.5.1 d9038ed792b923cfbb9593ab82825fdb48728adc

**Comment by xflywind** [comment]
It works in Nim 1.2.6.
![image](https://user-images.githubusercontent.com/43030857/99902422-aebc0000-2cf8-11eb-8b8f-d0da98d48c13.png)

**Comment by ringabout** [comment]
Yea, it doesn't raise exception before

Nim v 1.2.6: `nim js -r test.nim`
```
D:\QQPCmgr\Desktop\Nim\test.nim(3, 10): Check failed: 1 == 3
D:\QQPCmgr\Desktop\Nim\test.nim(4, 10): Check failed: 1 == 2
```

**Comment by timotheecour** [comment]
> Yea, it doesn't raise exception before

the `regression` tag is arguable; the behavior in 1.2.6 was even more buggy as it would silently make a program have return code 0 (success) even if check failed happened.

regression or not regression, we should just fix this.
