### ISSUE TITLE
`sugar.collect` doesn't work with `string` + other bugs

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16078]
`sugar.collect` doesn't work with `string`
It's a special case but an important one.

### Example 1
```nim
when true:
  import std/sugar
  let s = collect(newStringOfCap(4)):
    for j in 0..<4: char(j)
```

### Current Output
`Error: cannot instantiate: 'newStringOfCap[typeof:`

### Expected Output
works

### Example 2
`collect` doesn't work with `when`
```nim
when true:
  import std/sugar
  let s = collect(newSeqOfCap(4)):
    when true:
      for j in 0..<4: char(j)
    else:
      for j in 0..<3: char(j)
  echo s
```
### Additional Information
* devel 1.5.1 d9038ed792b923cfbb9593ab82825fdb48728adc
* also reported in forum [  TITLE: one more "collect" question (bug?) - Nim forum](https://forum.nim-lang.org/t/7253)

**Comment by ringabout** [comment]
`collect` is a bit hacky, it only supports generics constructor now.

```nim
import std/sugar

proc newStringI[T](size: int): string =
  newStringOfCap(size)


let s = collect(newStringI(4)):
  for j in 55 ..< 59: char(j)

echo s
```

**Comment by timotheecour** [comment]
> collect is a bit hacky, it only supports generics constructor now.

ya, and it seems hard/impossible to fix in a way that's not ambiguous, given that a symbol can have both generic and non-generic overloads. Hence https://github.com/nim-lang/Nim/pull/16082 which also offers other advantages

**Comment by Araq** [comment]
This works fine:

```nim

import sugar

proc newString[T: string](len: int): string = system.newString(len)

var st = collect(newString(3)):
  for i in 0..2: "this does not work"

echo st
```

**Comment by timotheecour** [comment]
this should work without having to introduce this overload, this is clunky.
