### ISSUE TITLE
db_sqlite: Error: undeclared field: 'untypedLen'

### ISSUE THREAD

**Issue by RokkuCode** [nim-lang/Nim#16080]
The following code taken from the db_sqlite isMainModule section does not compile:

```
var db = open(":memory:", "", "", "")
exec(db, sql"create table tbl1(one varchar(10), two smallint)", [])
exec(db, sql"insert into tbl1 values('hello!',10)", [])
exec(db, sql"insert into tbl1 values('goodbye', 20)", [])
var p1 = db.prepare "create table tbl2(one varchar(10), two smallint)"
exec(db, p1)
finalize(p1)
```

Compiler Error:
```
s.nim(31, 5) template/generic instantiation of `exec` from here
~/.choosenim/toolchains/nim-1.4.0/lib/impure/db_sqlite.nim(795, 12) Error: undeclared field: 'untypedLen'
```
I took a look at line 795 of db_sqlite:
```
macro untypedLen(args: varargs[untyped]): int =
  newLit(args.len)

template exec*(db: DbConn, stmtName: SqlPrepared,
          args: varargs[typed]): untyped =
  when args.untypedLen > 0:								#<-- Error happens here
    if reset(stmtName.PStmt) != SQLITE_OK:
      dbError(db)
    if clear_bindings(stmtName.PStmt) != SQLITE_OK:
      dbError(db)
    stmtName.bindParams(args)
  if not tryExec(db, stmtName): dbError(db)
```

If I change the code to:

```
-  when args.untypedLen > 0:
+  when untypedLen(args) > 0:
```

It compiles and works fine.

Nim Version:
```
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

**Comment by ringabout** [comment]
You could make a PR with your fix/workaround.

**Comment by RokkuCode** [comment]
Yes I could but I am not sure. As far as I understand macros the should work in both ways:
```
val.myMarco
myMacro(val)
```
So the question is: Why not here?

**Comment by Clyybber** [comment]
@RokkuCode This is a limitation that I'm lifting here: #14863, it is this way because the compiler has to analyze `val` to tell if `.myMacro` is a method call or a field of `val`.

**Comment by bung87** [comment]
Problem is not there, that code first added by me , run main successfull and pass CI. https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_1_4_0.md I checked it added in 1.4 , no idea what changes after that.

**Comment by bung87** [comment]
oh, probably `untypedLen` need export, old bug symbol can't resolved outside of that module

**Comment by RokkuCode** [comment]
I've tested that. If I export `untypedLen` it works. without further changing the code. I prepare a PR for it.
