### ISSUE TITLE
nre.escapeRe is not gcsafe

### ISSUE THREAD

**Issue by mildred** [nim-lang/Nim#16103]
Moved from https://github.com/flaviut/nre/issues/25

To use nre in a gcsafe environment, it would be great to have escapeRe to be gcsafe. Currently, it is not because it uses a global variable:

https://github.com/nim-lang/Nim/blob/eb2a4961c71029c874ebdacd1b23a349eb8e61d5/lib/impure/nre.nim#L745-L749

Because it depends on PCRE, the global variable cannot be declared `const` and creates non gcsafe behaviour. It would be great to allow using compiled regexp in gcsafe functions somehow.

**Comment by ringabout** [comment]
Two solutions:
- mark it as `threadvar`
- move it to the inner of function at the cost of performance

**Comment by metagn** [comment]
~~You could mark it as `global` and move it inside the function for no performance cost.~~

**Comment by mildred** [comment]
Using `{.global.}` variables in a function makes in incompatible with `{.gcsafe.}` I believe.

There is the possibility of re-implementing the function without a regular expression, for example: https://github.com/nitely/nim-regex/pull/91/files

Perhaps also Nim could allow variables that cannot be computed at compile-time to be declared const. This way it would not be impacted by the garbage collector and using the global regular expression would still be compatible `{.gcsafe.}`

**Comment by hlaaftana** [comment]
> Using `{.global.}` variables in a function makes in incompatible with `{.gcsafe.}` I believe.

I don't think it does, the following does not complain with --threads:on:

```nim
proc foo() =
  let x {.global.} = 3
  echo x
foo()
```

**Comment by metagn** [comment]
> Using `{.global.}` variables in a function makes in incompatible with `{.gcsafe.}` I believe.

For some reason I thought this was wrong. This same problem has been encountered before and dealt with in `httpclient` like so:

https://github.com/nim-lang/Nim/blob/79ec1bdcbb6a9d957def958bc9eff3b4c4a7f1d4/lib/pure/httpclient.nim#L316-L326

I meant to say that you can still move it inside the proc because no other proc uses it, unlike with defaultSslContext where it is used in multiple places. So:

```nim
proc escapeRe*(str: string): string = 
  ## Escapes the string so it doesn’t match any special characters. 
  ## Incompatible with the Extra flag (``X``).
  var specialCharMatcher {.threadvar.}: Regex
  if specialCharMatcher.isNil:
    specialCharMatcher = re"([\\+*?[^\]$(){}=!<>|:-])" 
  str.replace(specialCharMatcher, "\\$1") 
```

**Comment by Araq** [comment]
> Perhaps also Nim could allow variables that cannot be computed at compile-time to be declared const. This way it would not be impacted by the garbage collector and using the global regular expression would still be compatible {.gcsafe.}

It's often brought up, but that doesn't make it less wrong. Readonly memory doesn't help Nim's GC's threading architecture.
