### ISSUE TITLE
Unexpected output of dbQuote for db_mysql

### ISSUE THREAD

**Issue by shayanhabibi** [nim-lang/Nim#16112]
Procedure dbQuote in db_mysql outputs an unexpected string when provided special characters such as
```
{';' , ':' , '.' , '-'}
```

### Example
```nim
import db_mysql
echo dbQuote("1:P")
```

### Current Output
```
'1\58P'
```
* The current iteration over the string will check the character against several cases for special escaping, however does not include the characters that are in my use case
* Any character that is not in this check, and is not a letter or digit, is converted to its UTF-8 Dec value (or uint8) and escaped with double backslash. This inappropriately converts and escapes the characters in my use case.
### Expected Output
```
'1\:P'
```
* I have added my own constant containing characters that I want to be escaped using double backslash without being converted using $ord(c) first.
### Possible Solution
* Provide capability for user to provide character set which will be escaped without conversion to ordinal number.

```
$ nim -v
Nim Compiler Version 1.4.0
```

**Comment by ringabout** [comment]
This [regression](https://github.com/nim-lang/Nim/pull/15234) has been [fixed](https://github.com/nim-lang/Nim/commit/b3c77bb98277c2224234ffac7a33ffa9bcc0c014#diff-f422e17dbc26b5b1e03bfc999cfde2f789a0c5412c7e801e134702b7322a1fac).

devel works for me



```nim
import db_mysql
echo dbQuote("1:P")
```

output: `1:P`
