### ISSUE TITLE
Const seq into sink arg: =copy operator not found

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#16120]
### Example
```nim
proc main =
  let avals = @[@[1.0'f32, 4.0, 7.0, 10.0]]
  let rankdef = avals
  echo avals.len

main()
```

### Current Output
`a.nim(2, 16) Error: internal error: '=copy' operator not found for type array[0..0, seq[float32]]`

### Additional Information

Caused by #16115 confirmed.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-24
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d306a04466b7f1129620dc3ab35443119ed4c867
active boot switches: -d:release --gc:markAndSweep
```

**Comment by timotheecour** [comment]
can't reproduce; works for me, on osx, same nim version d306a04466b7f1129620dc3ab35443119ed4c867

**Comment by jangko** [comment]
same with me, cannot reproduce on both WSL Ubuntu 20.04 and Windows 10.

**Comment by planetis-m** [comment]
Guys its ``--gc:arc`` specific..

**Comment by jangko** [comment]
i see, now both wsl ubuntu and windows 10 produce the same error

**Comment by cooldome** [comment]
I have a fix. I don't think this is regression.
