### ISSUE TITLE
`out T` is documented in manual as alternative to `var T` but simplest example breaks

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#16131]
https://github.com/nim-lang/Nim/pull/14521 tried to add `out T` parameters to Nim, but it seems like they were removed at the last second. However, [this section](https://nim-lang.github.io/Nim/manual.html#overloading-resolution-overloading-based-on-var-t-slash-out-t) in the manual lists it alongside `var T`. The simplest example we can infer here ends up being:

```nim
proc p(x: out string) = x = "a"
var v: string
p(v)
```

The compile output is:

```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
....fatal.nim(49)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

Same happens for any other variant.

So it currently makes no sense in the manual, and if the feature was going to be implemented, it could go in as an experimental feature or be completely different. So it should probably be removed from the documentation for now to not mislead users.

In addition to the section I linked first, `out T` is also mentioned [here](https://nim-lang.github.io/Nim/manual.html#generics-generic-inference-restrictions) and [here](https://nim-lang.github.io/Nim/manual.html#pragmas-nosideeffect-pragma). It's not mentioned in the experimental manual (but the variant of `out T` meaning covariance is, whatever the covariance section is supposed to say)

```
$ nim -v
Nim Compiler Version 1.4.0
```

**Comment by codehz** [comment]
Here is minimal example
```nim
proc t(v: out int) = discard
```

**Comment by timotheecour** [comment]
> So it should probably be removed from the documentation for now to not mislead users.

@codehz please make a PR?

**Comment by metagn** [comment]
Closing because removed from docs, error message not really needed here, should be easier to remove it entirely from the compiler
