### ISSUE TITLE
Can we improve error message for wrong proc result type?

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#16150]
```nim
type
  O = object
    i: int

proc p(str: string): seq[string] =
  return result

var o: O

o = p("hello")
```

```
nim c --gc:arc t.nim 
....
/tmp/hhh/t.nim(10, 6) Error: type mismatch: got <seq[string]> but expected 'O = object'
salewski@nuc /tmp/hhh $ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-12
```

In a similar but much more complicated case I got from the error message the impression that the argument of the proc has wrong type. Took me a few minutes to recognize that problem is the proc result.

Error pos column 6 is the start of the proc argument, and when argument and return types are both exotic types it is confusing.

**Comment by timotheecour** [comment]
> Error pos column 6 is the start of the proc argument, and when argument and return types are both exotic types it is confusing.

columns start at 0 but the point is indeed that the column isn't sufficient to disambiguate, you'll get the same column if you write `o = p(12)` (which in this case is a sigmatch error)

=> fixing this in https://github.com/nim-lang/Nim/pull/16152

**Comment by Clyybber** [comment]
> columns start at 0

Nope, the issue here is that the error message is pointing to the call braces, not the sym of the callee.
