### ISSUE TITLE
Cross-compiled files cannot run on Raspberry Pi 4B

### ISSUE THREAD

**Issue by SOVLOOKUP** [nim-lang/Nim#16204]
Cross-compiled files cannot run on Raspberry Pi 4B.

### compile env：

```nim -v 
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-01
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2e4b6b94e675a7de96fcf2b3e8ed4224dccd5747
active boot switches: -d:release
```

```
 ██████████████████  ████████     sovlookup@sovlookup-pc
 ██████████████████  ████████     OS: Manjaro 20.2 Nibia
 ██████████████████  ████████     Kernel: x86_64 Linux 5.9.11-3-MANJARO
 ██████████████████  ████████     Uptime: 1h 45m
 ████████            ████████     Packages: 1355
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.76.0 / Plasma 5.20.3
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Disk: 152G / 480G (33%)
 ████████  ████████  ████████     CPU: AMD Ryzen 7 4800U with Radeon Graphics @ 16x 1.8GHz
 ████████  ████████  ████████     GPU: AMD RENOIR (DRM 3.39.0, 5.9.11-3-MANJARO, LLVM 11.0.0)
                                  RAM: 3896MiB / 15433MiB
```

### compile commands
have been tried:

1. `nim c -d:ssl --cpu:arm64 --os:linux -d:danger convert.nim`

2. `nim c --cpu:arm64 --os:linux --aarch64.linux.gcc.exe:aarch64-linux-gnu-gcc --aarch64.linux.gcc.linkerexe:aarch64-linux-gnu-gcc convert.nim`

3. `nim c -d:ssl --cpu:arm64 --os:linux -d:release convert.nim`

### error info
runs on Raspberry Pi 4B centos8

uname -a
`Linux localhost 5.4.65-v8.2.el8 #1 SMP PREEMPT Tue Sep 22 18:25:28 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

```
$ ./hello 
-bash: ./hello: cannot execute binary file: Exec format error
```

**Comment by Araq** [comment]
Try:

```
nim c --cpu:arm64 --os:linux --arm64.linux.gcc.exe:aarch64-linux-gnu-gcc --arm64.linux.gcc.linkerexe:aarch64-linux-gnu-gcc convert.nim
```

**Comment by SOVLOOKUP** [comment]
I tried this command but it runs with err:

```
$ nim c --cpu:arm64 --os:linux --arm64.linux.gcc.exe:aarch64-linux-gnu-gcc --arm64.linux.gcc.linkerexe:aarch64-linux-gnu-gcc hello.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....CC: stdlib_io.nim
CC: stdlib_system.nim
CC: hello.nim
Assembler messages:
Assembler messages:
Error: unknown architecture `x86-64'

Error: unrecognized option -march=x86-64
Error: unknown architecture `x86-64'

Error: unrecognized option -march=x86-64
Assembler messages:
Error: unknown architecture `x86-64'

Error: unrecognized option -march=x86-64
cc1: error: unknown value 'x86-64' for '-march'
cc1: error: unknown value 'x86-64' for '-march'
cc1: error: unknown value 'x86-64' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a

Error: execution of an external compiler program 'aarch64-linux-gnu-gcc -c  -w -fmax-errors=3 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2   -I/usr/lib/nim -I/home/sovlookup/nim -o /home/sovlookup/.cache/nim/hello_d/stdlib_io.nim.c.o /home/sovlookup/.cache/nim/hello_d/stdlib_io.nim.c' failed with exit code: 1
```

I tried add `-march=armv8-a` and  `--march=armv8-a` but shows:

`command line(1, 2) Error: invalid argument for command line option: '-h'`

`command line(1, 2) Error: invalid command line option: '--march'`

My nim.cfg:

```
...
# Cross-compiling for Raspberry Pi.
# (This compiler is available in gcc-arm-linux-gnueabihf package on Ubuntu)
#arm.linux.gcc.exe = "arm-linux-gnueabihf-gcc"
#arm.linux.gcc.linkerexe = "arm-linux-gnueabihf-gcc"
arm.linux.gcc.exe = "aarch64-linux-gnu-gcc"
arm.linux.gcc.linkerexe = "aarch64-linux-gnu-gcc"
...
```

**Comment by Aiyarree** [comment]
Hi,
i had the exact same stuff going on. Two times.
First time was with Solus-Linux/Rust.
This time with Manjaro/Nim.

Both times i installed the Programming Language from the Distros-Repositories.
Just uninstall all the nim-stuff using your package manager again.
Than reinstall it with the method recommended by the programming language.
In Nim's case and for me it was the: "choosenim"-script.

Everything else goes now by the "fucking manual":

- Download the toolchain. In my case i used Linaro:
[https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/](url)
- Put it where ever you like and add it to your $Path.
- Edit the nim.cfg and add these lines to the category "# Cross-compiling for Raspberry Pi."
`# Cross-compiling for Raspberry Pi 64
arm64.linux.ccc.path = "<Path-to-aarch64-linux-gnu-gcc>"
arm64.linux.gcc.exe = "aarch64-linux-gnu-gcc"
arm64.linux.gcc.linkerexe = "aarch64-linux-gnu-gcc"`

Worked like charm.

Please note that this is the example for 64bit compiler flag "arm64" not! "arm". What is partly pre-configured in the nim.cfg and used as example in the cross-compiling article of nim [https://nim-lang.org/docs/nimc.html](url) is the 32bit example. Most linux images for the Raspi dropped support for 32bit entirely. So do not get confused.

**Comment by SOVLOOKUP** [comment]
it really work,thanks!

this nim.cfg is ok:
```
...
# Cross-compiling for Raspberry Pi.
arm64.linux.gcc.exe = "aarch64-linux-gnu-gcc"
arm64.linux.gcc.linkerexe = "aarch64-linux-gnu-gcc"
...

```
