### ISSUE TITLE
Error parsing INI section names with spaces

### ISSUE THREAD

**Issue by BarrOff** [nim-lang/Nim#16206]
I was trying out the [example program from the documentation](https://nim-lang.org/docs/parsecfg.html) for parsing INI files. If the section name contains spaces, it would parse the INI file incorrectly.

### Example INI file
```INI
[SectionA]
[Section B]
```

### Current Output
```
new Section: SectionA
test.ini(2, 10) Error: ']' expected, but found: B
key-value-pair: B:
test.ini(2, 11) Error: invalid token: ]
```

### Expected Output
```
newSection: SectionA
newSection: Section B
```

### Possible Solution

* The documentation states, that the configuration syntax is similar to Windows Ini, so maybe this is the expected output?

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.2
```

**Comment by ringabout** [comment]
Looks like a bug
Ref:
https://docs.python.org/3.10/library/configparser.html#supported-ini-file-structure

Could you provide your program?

**Comment by BarrOff** [comment]
@xflywind here is the program, but this is just a copy from the documentation, see the link in OP

```nim
import os, parsecfg, strutils, streams

var f = newFileStream(paramStr(1), fmRead)
if f != nil:
  var p: CfgParser
  open(p, f, paramStr(1))
  while true:
    var e = next(p)
    case e.kind
    of cfgEof: break
    of cfgSectionStart:   ## a ``[section]`` has been parsed
      echo("new section: " & e.section)
    of cfgKeyValuePair:
      echo("key-value-pair: " & e.key & ": " & e.value)
    of cfgOption:
      echo("command: " & e.key & ": " & e.value)
    of cfgError:
      echo(e.msg)
  close(p)
else:
  echo("cannot open: " & paramStr(1))
```
