### ISSUE TITLE
With experimental

### ISSUE THREAD

**Issue by cpbotha** [nim-lang/Nim#16215]
Function `echo` outputs the wrong string.

### Example
```nim
echo "Hello World!"
# This code should be a minimum reproducible example:
# try to simplify and minimize as much as possible. If it's a compiler
# issue, try to minimize further by removing any imports if possible.
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
Hola mundo!
```

### Expected Output
```
Hello World!
```

### Possible Solution

* In file xyz there is a call that might be the cause of it.

### Additional Information

Could be related to https://github.com/nim-lang/Nim/issues/15745

If it's a regression, you can help us by identifying which version introduced
the bug, see [Bisecting for regressions](https://nim-lang.github.io/Nim/intern.html#bisecting-for-regressions),
or at least try known past releases (eg `choosenim 1.2.0`).

If it's a pre-existing compiler bug, see [Debugging the compiler](https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler)
which should give more context on a compiler crash.

* Issue #abc is related, but different because of ...
* This issue is blocking my project xyz

```
$ nim -v
Nim Compiler Version 0.1.2
# make sure to include the git hash if not using a tagged release
```

**Comment by timotheecour** [comment]
@cpbotha please fix the top message `Function echo outputs the wrong string.` plus the rest of this issue; don't copy the issue template blindly

in fact, closing because I don't understand what this issue is about

**Comment by cpbotha** [comment]
I am so sorry @timotheecour ! I started with filing this issue and then decided against it. I was not aware that I had somehow submitted the 0% draft. Thank you for closing.

**Comment by timotheecour** [comment]
no worries:)
