### ISSUE TITLE
`hasArgOfName` misses the tail of a list of parameter names with the same type

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#16219]
The arguments `j` and `k` are not found:

### Example
```nim
import macros

macro m(u:untyped):untyped =
  echo:
    [ hasArgOfName((params u),"i"),
      hasArgOfName((params u),"j"),
      hasArgOfName((params u),"k")
    ]

proc p(i,j,k:int) {.m.} = discard
```

### Current Output
```
[true, false, false]
```

### Expected Output
```
[true, true, true]
```

### Possible Solution

`echo u.params.len` outputs `2`, the first is the empty node for the function output type so the length of input parameters is wrongly detected as `1`. Since `hasArgOfName` uses it to search the param list it only finds `i`.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-01
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 1d1b3f79fdccfdd359781dbde3c5aea3b67bf05b
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
@deech a PR would be appreciated, this doesn't seem too hard to fix

**Comment by deech** [comment]
https://github.com/nim-lang/Nim/pull/16233
