### ISSUE TITLE
-d:fulldebug switch does not compile with gc:arc

### ISSUE THREAD

**Issue by olliNiinivaara** [nim-lang/Nim#16214]
-d:fulldebug switch does not compile with gc:arc

### Example
nim c --gc:arc -d:fulldebug fullfail.nim

(fullfail.nim can be empty file)

### Current Output
```
Hint: used config file '/home/olli/.choosenim/toolchains/nim-1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/home/olli/.choosenim/toolchains/nim-1.4.2/config/config.nims' [Conf]
.
/home/olli/.choosenim/toolchains/nim-1.4.2/lib/system/mmdisp.nim(78, 25) template/generic instantiation of `instantiateForRegion` from here
/home/olli/.choosenim/toolchains/nim-1.4.2/lib/system/alloc.nim(1022, 36) Error: type mismatch: got <MemRegion, pointer>
but expected one of: 
proc interiorAllocatedPtr(p: pointer): pointer
  first type mismatch at position: 1
  required type for p: pointer
  but expression 'allocator' is of type: MemRegion

expression: interiorAllocatedPtr(allocator, p)
```

### Additional information

```bash
Nim Compiler Version 1.4.2 [Linux: amd64]
Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 5.4.0-54-generic
```

**Comment by Araq** [comment]
Do we claim to support ``-d:fulldebug`` in any way? Where is it documented?

**Comment by olliNiinivaara** [comment]
I expected that "*fulldebug*" behaves like any other *non-documented* (user-defined, that is) compile-time symbol:
compiles, no side effects, no interference with any other switch.

Realizing that *alloc.nim* uses this symbol is against my expectations. No damage done - easy solution is that I "search and replace" "*fulldebug*" to another symbol everywhere in my codes (if I want my code to compile with arc/orc, which I definitely do). 

But to prevent this from happening in the future, predefined symbols should be prefixed "*nim*". This would be according to compiler user guide, quote: "Compile-time symbols starting with the nim prefix are reserved for the implementation and should not be used elsewhere".

(Also "*threadsafe*"  should have been "*nimthreadsafe*" (used in stdlib/selectors), but then maybe that symbol could be totally removed (who would ever want to define --threads:on without defining -d:threadsafe anyway...)).

**Comment by Araq** [comment]
Completely agreed. Consider it done.
