### ISSUE TITLE
magic procs accept body that isn't used

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16222]
* magic procs accept body that isn't used
* maybe even the `=` should be disallowed or at least issue a warning

### Example
```nim
proc `<<=`*(x, y: string): bool {.magic: "LeStr", noSideEffect.} =
  ## Compares two strings and returns true if `x` is lexicographically
  false

echo ("a" <<= "b")
```

### Current Output
```
true
```

### Expected Output
Error: this magic proc can't have a body

### Additional Information
* 1.5.1 fd9870568020939aae902ef5ccb26d12e45673b6
* note that `=` is (at least currently) needed when you have `runnableExamples` (eg https://github.com/nim-lang/Nim/pull/16201#discussion_r533825339)

**Comment by Araq** [comment]
But this feature allows us to add new magics to Nim without ``when nimHasX`` workarounds. Plus ``magic`` is an implementation detail, we can do what we like, "accepts invalid" doesn't apply.

**Comment by ringabout** [comment]
I can't make `runnableExamples` for borrowed function.
```nim
proc `==` *(a, b: Color): bool {.borrow.} =
  ## Compares two colors.
  runnableExamples:
    var
      a = Color(0xff_00_ff)
      b = colFuchsia
      c = Color(0x00_ff_cc)
    assert a == b
    assert not a == c
    assert not a == c
```
implementation of '==' is not allowed

**Comment by Araq** [comment]
That has nothing to do with ``magic``.
