### ISSUE TITLE
regression + RFC to deprecate prelude

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16238]
I dislike `prelude` for many reasons, but we can do better.

 - [x] bug1: it can't be used for any file for which we want to generate docs, otherwise you run into one of the (many) classic gotchas with include files, see Example
=> PR https://github.com/nim-lang/Nim/pull/17111

 - [x] bug2: it can't be used with a prefix, eg `include std/prelude` or `include system/prelude` don't work because it's in `lib/prelude.nim`; scoping is good to avoid confusion (eg karax/prelude etc) and to allow indicating it comes from a given package eg stdlib.
=> PR https://github.com/nim-lang/Nim/pull/17110

 - [ ] bug3: it's an arbitrary list of modules, and not flexible
=> see RFC https://github.com/timotheecour/Nim/issues/388

### Example
```nim
include prelude
proc main*() =
  runnableExamples:
    doAssert 1 == 1
```

### Current Output
`nim doc -r main` shows the doc comment of prelude in main.html [1]

### Expected Output
no doc comment pollution in main.html

### Possible Solution
* deprecate prelude
* replace it with `std/stdimports`, as described in https://github.com/timotheecour/Nim/issues/388
```nim
# include prelude
# =>
import std/stdimports # more flexible, user chooses what imports they want
importCommonCollections() # import all standard collections
importCommonRepl() # for use in a repl
importCommonScripting() # for use with scripting
# etc...
```

originally proposed in https://github.com/nim-lang/Nim/pull/16135#discussion_r530644051, and not I'm not convinced by https://github.com/nim-lang/Nim/pull/16135#discussion_r530897095 `You don't get the convenience of "don't make me think" by providing options.`, because for me "1 size fits-all" here means "1 size fits-none".

furthermore, unlike with prelude include file, it's easy to write a macro to auto-generate the list of imports that each `importCommonRepl` + friend calls (ie, DRY).

### Additional Information
* devel 1.5.1 629b22e3d50e9903512ec893174eb797d9ed431b
* "regression" introduced in https://github.com/nim-lang/Nim/pull/16135 (/cc @xflywind ) but really this is a problem with prelude

[1]
![image](https://user-images.githubusercontent.com/2194784/100959373-fb5ec280-34d2-11eb-97e5-29d693542fd9.png)

**Comment by Araq** [comment]
I like ``include prelude`` very much but then I don't generate documentation for the short programs "prelude" was made for. Come on, the mentioned downsides are silly. All you really need to do is to know what "prelude" is meant for.

**Comment by ringabout** [comment]
regression is fixed, bug3 is not a bug.

**Comment by timotheecour** [comment]
indeed; followup https://github.com/timotheecour/Nim/issues/388 for bug 3
