### ISSUE TITLE
nim-1.4.2 :: no html doc provided ? how to generate

### ISSUE THREAD

**Issue by EricDeveaud** [nim-lang/Nim#16241]
Hello, 

upgrading nim from 1.2.6 to 1.4.2 and building from source. 
i noticed that doc/html is not provided as it was in earlier distribution.

how can I build the html docs

regards

Eric

**Comment by timotheecour** [comment]
`./koch --localdocs docs`

I don't believe doc/html should be bundled, since they're online and can be built from source easily.

can this be closed?

**Comment by narimiran** [comment]
> can this be closed?

Why reopen?

**Comment by timotheecour** [comment]
my previous message was: `I'll close this; if you disagree, feel free to re-open with an explanation.`; I'll close this again since issue author hasn't responded.
