### ISSUE TITLE
Use multiple buffers for compiler output

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1624]
Currently, when invoking the C compiler, the Nim compiler simply passes it's own standard output handle to the C compiler processes. This has the unfortunate effect of sometimes scrambling output when the compiler is invoked more than once at the same time, requiring users to run the compiler with `--parallelBuild:1`

A better (albeit more complex) approach would be to send the output for each compiler process to it's own buffer, and then read synchronously from those buffers when their associated processes are done.

**Comment by Bulat-Ziganshin** [comment]
yeah, it's standard problem with `make -j` or any standalone multi-file compiler (msvc, icl)
