### ISSUE TITLE
[ARC] codegen error when init seq[T] in callback if T aliased w/ {.nodecl.}

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#16246]
This is a bit of a bizarre one. Took a while to find the culprit, thanks to a mix of code bases involved.

It seems like using callbacks with ARC can lead to a codegen error when sequences are involved with (certain?) type aliases, in particular `cuint` + `uint32` or any alias using `{.nodecl.}`.

### Example

This is the actual issue I isolated:
```nim
proc test() =
  var values = newSeq[cuint](8)
  # var values: seq[cuint] does not produce codegen error
  var drawCb = proc(): seq[uint32] =
    result = newSeq[uint32](10)

test()
```
After I noticed that `cuint` is just an alias for `uint32` I tried it with a custom alias, which works fine. However, a look at the source made me realize that `cuint` uses `{.nodecl.}`. So the following produces a similar issue:
```nim
type
  myInt {.nodecl.} = int # works if `myInt = int` used instead

proc test() =
  var values = newSeq[myInt](8)
  # var values: seq[cuint] does not produce codegen error
  var drawCb = proc(): seq[int] =
    result = newSeq[int](10)

test()
```

### Current Output

```
/home/basti/.cache/nim/testArr_d/@mtestArr.nim.c: In function 'colonanonymous___o5QORvA9cwDAJXgNLYWpaQQ':
/home/basti/.cache/nim/testArr_d/@mtestArr.nim.c:117:11: error: incompatible types when assigning to type 'tySequence__9bAGqSvkAaFL9bWjsEPslrFA' {aka 'struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA'} from type 'tySequence__U48dCdy0noze9bNL2psZZGA' {aka 'struct tySequence__U48dCdy0noze9bNL2psZZGA'}
  117 |  result = newSeq__MSj7lRk8D7wQIj3uPO6UrA(((NI) 10));
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/basti/src/nim/nim_git_repo/lib -I/tmp -o /home/basti/.cache/nim/testArr_d/@mtestArr.nim.c.o /home/basti/.cache/nim/testArr_d/@mtestArr.nim.c' failed with exit code: 1
```

### Expected Output
Compilation without issue.

### Possible Solution

Possibly fix handling of name mangling (?) for aliased types using `{.nodecl.}`.

### Additional Information

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-29
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d29eddf92a1b8147c4709fd828f77152c1f3aab2
active boot switches: -d:release -d:danger
```

**Comment by Vindaar** [comment]
Any update on this? It's still blocking usage of ARC for me for some projects (among others in `nimhdf5`). 

Also there seems to be a related issue on the C++ backend (without ARC) for a generic proc that calls `newSeq[T]`. If `T` is `uint64` I get a similar code gen error. I can try to reproduce this and open another issue, if that helps.

**Comment by Araq** [comment]
Seems easy to fix. Want to give it a try?

**Comment by Vindaar** [comment]
> Seems easy to fix. Want to give it a try?

In principle I can try. Though the fact that @cooldome started in #16440, but didn't finish led me to believe there's some more subtle stuff going on. 
I'll take a look at it.

**Comment by Araq** [comment]
Never mind, I think I have a fix. But please take a look and learn. :-)
