### ISSUE TITLE
`proc fn(): auto = 1; fn()+1.0` wrongly compiles

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16244]
`proc fn(): auto = 1; fn()+1.0` wrongly compiles.

### Example
```nim
when true:
  proc g(): auto = 1
  proc h(): auto = 1.0
  var a = g() + h()
```

### Current Output
compiles

### Expected Output
error: type mismatch (g() is typed int, h() is typed float)

This would be fine if `g()` were a template, but it's a proc so `auto` should be resolved (to int).

### Additional Information
* devel 1.5.1 2220aaeaef74cb6018f4689af8f280db22cb30dd
* likewise with iterator; test case should include this too:
```nim
when true:
  iterator fn(): auto = yield 1
  for ai in fn(): echo ai + 1.0
```

**Comment by bung87** [comment]
the literal `int` implicitly convert to `float` , so I dont see problem here.

**Comment by Vindaar** [comment]
> the literal `int` implicitly convert to `float` , so I dont see problem here.

But that only holds for the first line. In the example snippet (as written under "Expected output")
```nim
when true:
  proc g(): auto = 1
  proc h(): auto = 1.0
  var a = g() + h()
```
`g` returns `int` and `h` returns `float`. So indeed the `g() + h()` call should throw a CT error.

**Comment by bung87** [comment]
I understand now , the `auto` should strip out the literal info.
