### ISSUE TITLE
[ARC] SIGSEGV for objects storing `seq[string]` in `{.noInit.}` procs using `shallowCopy`

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#16257]
This is another bug I encountered using ARC, however there is similar `shallowCopy` bug lurking using the default GC that I cannot pin down in an isolated case unfortunately (segmentation fault in `rawAllow`).

In this case we have a tensor that cannot be memcopied and thus uses a `seq` as its storage. Attempting to use `shallowCopy` in a `{.noInit.}` proc causes a segmentation fault in `reset`.

Avoiding a `shallowCopy` by using `deepCopy` works fine as a workaround for the default GC, but because `deepCopy` is not supported by default under ARC, this is not a good workaround for ARC.

### Example
```nim
# compile with `--gc:arc` to get a SIGSEGV in `reset`
type
  CpuStorage*[T] = ref CpuStorageObj[T]
  CpuStorageObj[T] = object
    raw_buffer*: seq[T]
  Tensor[T] = object
    buf*: CpuStorage[T] # if tensor stores a `seq` itself it works fine

proc allocCpuStorage[T](s: var CpuStorage[T], size: int) =
  new(s)
  s.raw_buffer = newSeq[T](size)

proc newTensor[T](size: int): Tensor[T] =
  allocCpuStorage(result.buf, size)

proc `[]`[T](t: Tensor[T], idx: int): T = t.buf.raw_buffer[idx]
proc `[]=`[T](t: Tensor[T], idx: int, val: T) = t.buf.raw_buffer[idx] = val

proc toTensor[T](s: seq[T]): Tensor[T] =
  result = newTensor[T](s.len)
  for i, x in s:
    result[i] = x

proc data*[T](t: Tensor[T]): seq[T] {.inline, noSideEffect, noInit.} =
  shallowCopy(result, t.buf.raw_buffer)

proc main() =
  var s: seq[string]
  for i in 0 ..< 5:
    s.add $i
  var y = s.toTensor
  let res = y.data

main()
```

### Current Output

```
Traceback (most recent call last)
/home/basti/org/Misc/arc_shallow_bug.nim(34) arc_shallow_bug
/home/basti/org/Misc/arc_shallow_bug.nim(32) main
/home/basti/src/nim/nim_git_repo/lib/system.nim(2203) data
/home/basti/src/nim/nim_git_repo/lib/system/fatal.nim(49) reset
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/basti/org/Misc/arc_shallow_bug '
```

### Expected Output
```
@["0", "1", "2", "3", "4"]
```

### Additional Information

If the `Tensor` object above does not store a `CpuStorage` object, but rather contains a `seq[string]` as its `buf` directly it works fine. It also works if the `data` proc does not use `{.noInit.}`.

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-04
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: edce5897a52aac308fbe9b14f155139f15da02cd
active boot switches: -d:release -d:danger
```

**Comment by Araq** [comment]
I don't see why it has to work with `noInit` plus `shallowCopy` for `--gc:arc`, this code never was supported and your code works much better under ARC without these hacks.
