### ISSUE TITLE
Nimcache confusion compiling files with the same name in different directories

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#16271]
When having multiple file with the same name, living in different directories, Nim does not properly understand these are different files and re-uses the wrong nimcache result.

Reproducing:

- Create 2 Nim files with the same base name in different directories:

  * `a/t.nim`: `echo "a"`
  * `b/t.nim`: `echo "b"`

- Compile and run `t.nim` in `./a`
```
$ cd a
$ nim r t.nim
Hint: used config file '/home/idoornekamp/external/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/idoornekamp/external/Nim/config/config.nims' [Conf]
....CC: stdlib_io.nim
CC: stdlib_system.nim
CC: t.nim

Hint:  [Link]
Hint: 22400 lines; 0.594s; 30.547MiB peakmem; Debug build; proj: /tmp/a/t.nim; out: /home/idoornekamp/.cache/nim/t_d/t [SuccessX]
Hint: /home/idoornekamp/.cache/nim/t_d/t  [Exec]
a
```

- Compile and run `t.nim` in `./b`
```
$ cd b
$ nim r  t.nim 
Hint: used config file '/home/idoornekamp/external/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/idoornekamp/external/Nim/config/config.nims' [Conf]
Hint: 7853 lines; 0.021s; 11.359MiB peakmem; Debug build; proj: /tmp/b/t.nim; out: /home/idoornekamp/.cache/nim/t_d/t [SuccessX]
Hint: /home/idoornekamp/.cache/nim/t_d/t  [Exec]
a
```

Observe that the second run of `b/t.nim` results in `a/t.nim` getting executed, and no compilation is performed.

**Comment by timotheecour** [comment]
fixed it in https://github.com/timotheecour/Nim/pull/427

**Comment by zevv** [comment]
Thanks!
