### ISSUE TITLE
Wrong result on operations on sets of different types

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#16270]
When doing some operations on sets of different types, the result is wrong.

### Example
```nim
var s1: set[char] = {'a', 'b'}
var s2: set['a'..'z'] = {'a', 'c'}
s2 = s2 + s1
echo s2
```

### Current Output
```
{'a', 'c', 'i', 'm', 'n', 'o', 'q', 'w'}
```

### Expected Output
```
{'a', 'b', 'c'}
```

### Possible Solution
Do not use operations between a set of a type and a set of a subtype.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```
Doesn’t work with development version either.

**Comment by narimiran** [comment]
More test cases (that produce different results):

Put the union in `s1` instead of `s2`:
```nim
s1 = s2 + s1
```

gives `SIGSEGV`.

Also change the order of the operands:
```nim
s1 = s1 + s2
```

gives:
```
@mfoo.nim.c:134:97: error: subscripted value is neither array nor pointer nor vector
  134 |   s1__SizQHgzLoidLdZgDW2Trjw[T1_] = s1__SizQHgzLoidLdZgDW2Trjw[T1_] | s2__x06HXi7OCBrxZErnja7cvw[T1_];
      |                                                                                                 ^

Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/miran/code/nim-lang/Nim/lib -I/home/miran/code/nim-lang/Nim -o /home/miran/.cache/nim/proba_d/@mproba.nim.c.o /home/miran/.cache/
nim/proba_d/@mproba.nim.c' failed with exit code: 1
```

----

Doing intersection also gives either a wrong result (`s2 = s2 * s1`; `s2` is an empty set instead of `{'a'}`),  or it doesn't work (change the order of the operands: `s2 = s1 * s2` or put the result in `s1`)

----

All these various combinations should be part of the test case!

**Comment by narimiran** [comment]
Ah, now I see that `s1 = s1 + s2` case is already reported in https://github.com/nim-lang/Nim/issues/16269

**Comment by lscrd** [comment]
Yes, I encountered #16269 first, then #16270. The order of operands changes the behavior but the cause is likely the same.

**Comment by cooldome** [comment]
IMO,
it should be like this
```nim
var s1: set[char] = {'a', 'b', '0'}
var s2: set['a'..'z'] = {'a', 'c'}

s1 = s1 + s2 # should work
s2 = s1 + s2 # s2 has narrower type, check range is required

s1 = s2 + s1 # should work but with range check
# proc `+`*[T](x, y: set[T]): set[T] {.magic: "PlusSet".} in here T is bound to 'a'..'z' and char is not 'a'..'z' check range is required.
```

Looks like the main problem we don't have range checks for sets.

**Comment by lscrd** [comment]
I’m not sure what should be allowed. In fact, there is no need to do an operation; assignment is enough to show the issue. Assigning "s1" to "s2" gives a wrong result. Assigning "s2" to "s1" causes an illegal storage access.

So, the question is: what assignment should be considered legal? If I replace the sets by sequences, neither assignment is allowed as types are considered as incompatible. It might make sense to use the same rule for sets.

**Comment by cooldome** [comment]
I am wrong above. corrected myself

**Comment by cooldome** [comment]
@Araq,
What is your opinion on how `set['a'..'z']` should be represented in codegen. Is it the same as `set[char]` with 256 bits? or more efficient one with 26 bits? 

Currently `set['a'..'z']` is trying to be more efficient, but there is no type conversion between `set['a'..'z']` and `set[char]` hence the problem. Fix would be to add conversion operation.

Another solution is drop optimization and represent  `set['a'..'z']` as `set[char]`

**Comment by Araq** [comment]
Drop the optimization.

**Comment by timotheecour** [comment]
I agree with https://github.com/nim-lang/RFCs/issues/298#issuecomment-740871060 that we should keep the optimization and fix the conversion instead. Otherwise `set[range]` is less useful. 

Unless I'm missing something, this all sounds feasible.

**Comment by cooldome** [comment]
For reference I have tried to drop the optimization. It is breaking existing code and existing tests actually . This is because `set['a'..'z']` actually works well as long as it is not mixed with `set[char]`.
I guess we have no choice but to implement conversion.

**Comment by Araq** [comment]
Breaking existing code is bad of course but tests can always be adapted.
