### ISSUE TITLE
[GC] possible ref counting bug when assigning to ptr UncheckedArray

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#16274]
Ok, here I honestly don't quite understand if this can be supported in a safe way and is a GC bug or if this is broken code in general.

Essentially when having a assignment proc for some type not directly assign a value using the types `[]=`, but rather do it indirectly via a `ptr UncheckedArray`, we "forget" a GC unref of the assigned value. That causes the reference counting to be off and will eventually cause a segfault somewhere in the GC.

~~I'm still either chasing a bug in arraymancer when using the normal GC or possibly have an issue similar to this one in a way I cannot find. At least here I was able to isolate it to a reference counting bug.~~
edit: I found the root cause for the GC segfaults I was having. It was indeed just a bug in ggplotnim, because I was still using a `deepCopy` indirectly on a `Tensor`. For the ptr + len pairs tensors that of course leads to a tensor with invalid memory after the original is freed.
edit2: While the first edit is correct, this issue is still happening in arraymancer. For some reason almost exactly the same code works on arraymancer's current master though. 

I feel bad for opening all these. :)

### Example
```nim
# compile without `--gc:arc` to get a SIGSEGV in the gc
type
  RawMutableView*[T] = ptr UncheckedArray[T] # in original code is distinct

  CpuStorage*[T] = ref CpuStorageObj[T]
  CpuStorageObj[T] = object
    raw_buffer*: seq[T]
  Tensor[T] = object
    buf*: CpuStorage[T] # if tensor stores a `seq` itself it works fine

proc allocCpuStorage[T](s: var CpuStorage[T], size: int) =
  new(s)
  s.raw_buffer = newSeq[T](size)

proc newTensor[T](size: int): Tensor[T] =
  allocCpuStorage(result.buf, size)

proc `[]`[T](t: Tensor[T], idx: int): T =
  t.buf.raw_buffer[idx]

proc `[]=`[T](t: var Tensor[T], idx: int, val: T) =
  var dat: RawMutableView[T]
  dat = cast[RawMutableView[T]](t.buf.raw_buffer[0].addr)
  dat[idx] = val
  # works if we use:
  #t.buf.raw_buffer[idx] = val
  # also works if we manually unref the `dat[idx]`
  # GC_unref(dat[idx])

proc toTensor[T](s: seq[T]): Tensor[T] =
  result = newTensor[T](s.len)
  for i, x in s:
    result[i] = x

proc main() =
  var s: seq[string]
  for i in 0 ..< 1000: # works for small numbers
    s.add $i
  var y = s.toTensor
  # now overwrite the data using the `[]=` proc
  for i in 0 ..< 1000:
    y[i] = $i
  echo y.buf.raw_buffer
  # alternative causes segfault in `[]` access in this file
  #for i in 0 ..< 10:
  #  echo y[i].repr

main()
```

### Current Output

```
Traceback (most recent call last)
/tmp/gc_assign_bug.nim(48) gc_assign_bug
/tmp/gc_assign_bug.nim(44) main
/home/basti/src/nim/nim_git_repo/lib/system/dollars.nim(170) $
/home/basti/src/nim/nim_git_repo/lib/system/dollars.nim(153) collectionToString
/home/basti/src/nim/nim_git_repo/lib/system.nim(2853) addQuoted
/home/basti/src/nim/nim_git_repo/lib/system.nim(2812) addEscapedChar
/home/basti/src/nim/nim_git_repo/lib/system/gc.nim(435) newObjNoInit
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/gc_assign_bug '
```

If instead of echoing the whole `raw_buffer` we just  echo the first 10 elements we instead get a segfault in `[]` accessing the data and can see that the accessed data is completely borked at this point:
```
0x7fdfd04342d0"839" # this is supposed to be the 1st element
""
Traceback (most recent call last)
/tmp/gc_assign_bug.nim(45) gc_assign_bug
/tmp/gc_assign_bug.nim(43) main
/tmp/gc_assign_bug.nim(19) []
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/gc_assign_bug '
```

### Expected Output

Should echo either the full `seq[string]` buffer or the first 10 elements of the tensor (strings of values 0 .. 9).

### Possible Solution

Adding an additional `GC_unref` to the copied string in the `dat[idx]` makes it work.  

### Additional Information

It is related to this issue: https://github.com/nim-lang/Nim/issues/13598.

I checked the generated C code to understand what's different for 3 different cases. `[]=` with the following contents each:
1. segfaulting code:
```nim
  var dat: RawMutableView[T]
  dat = cast[RawMutableView[T]](t.buf.raw_buffer[0].addr)
  dat[idx] = val
```
2. working code using normal assignment:
```nim
  t.buf.raw_buffer[idx] = val
```
3. "repaired" version of code 1 using a manual `GC_unref`:
```nim
  var dat: RawMutableView[T]
  dat = cast[RawMutableView[T]](t.buf.raw_buffer[0].addr)
  dat[idx] = val
  GC_unref(dat[idx])
```

These produce the following C code (compiled with `-d:danger` to remove the fluff) for the assignment proc:
1.
```C
	NimStringDesc** dat;
	dat = (NimStringDesc**)0;
	dat = ((NimStringDesc**) ((&(*(*t).buf).raw_buffer->data[((NI) 0)])));
	dat[idx] = copyString(val);
```
2.
```C
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*(*t).buf).raw_buffer->data[idx]; (*(*t).buf).raw_buffer->data[idx] = copyStringRC1(val);
	if (T1_) nimGCunrefNoCycle(T1_);
```
3. 
```C
	NimStringDesc** dat;
	dat = (NimStringDesc**)0;
	dat = ((NimStringDesc**) ((&(*(*t).buf).raw_buffer->data[((NI) 0)])));
	dat[idx] = copyString(val);
	if (dat[idx]) { nimGCunref(dat[idx]); }
```

As we can see, the main difference is that the default assignment automaticaly unrefs the helper `T1_` and uses `copyStringRC1` instead of `copyString`. 
Intuitively it makes sense that we'd want to unref the copy of the string, since the memory of it needs to be freed when the array it's assigned to will be freed.
The thing I find _really_ confusing: shouldn't assignment to a raw pointer always unref the reference counted object to say: "you copy over a reference counted object to some ptr, so now you're responsible for cleaning it up"? 

But it's super possible I misunderstand something here and such code can never safely work with a GC. Feel free to close in that case. Some explanation would be much appreciated!

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-04
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: edce5897a52aac308fbe9b14f155139f15da02cd
active boot switches: -d:release -d:danger
```

**Comment by Araq** [comment]
> Some explanation would be much appreciated!

Still investigating. Your example is hard to understand. :-)

**Comment by Araq** [comment]
Good thing ORC is now the default.
