### ISSUE TITLE
[Suggestion] Deprecate intsets and special-case HashSet[int]

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#16278]
Right now the Nim standard library exposes three types for representing the notion of a mathematical set:

- `set[T]`, which is a language feature, acting as an alternative to using bitflags and is not aiming at being generaly; only supports specific types e.g. enums, `int8`, `char`, etc.
- `HashSet[T]`, which is more general than `set[T]` and will work on anything that has a hash function defined for it
- `IntSet`, which is a little less known but aims to be more optimized than `HashSet[T]` for `int` by use of a sparse bitset

My question here: what `IntSet` provides as an optimization is good, but is there a reason for it to be a seperate API? Would it not be better for the existing `intsets` code to be reframed as a special case for `HashSet[T]` where `T` is `SomeInteger`, or is there a good reason for `intsets` to stick around as a seperate public module? The [`intsets`](https://nim-lang.org/docs/intsets.html) API is more or less the same as [`sets`](https://nim-lang.org/docs/sets.html), so ultimately it may just be easier and cleaner to keep `IntSet` as a separate private module imported internally by `sets`. 

As an aside in special-casing for `SomeInteger` instead of just `int` we can also add a little bit more flexibility to the `intsets` code in the process, being able to adjust for `int32` and `int64` if needed instead of the platform-defined `int`.

**Comment by Araq** [comment]
This is how intsets now looks like:

```nim

import std/packedsets
export packedsets

type
  IntSet* = PackedSet[int]

proc toIntSet*(x: openArray[int]): IntSet {.since: (1, 3), inline.} = toPackedSet[int](x)

proc initIntSet*(): IntSet {.inline.} = initPackedSet[int]()
```

We introduced "packedsets". Seem to be exactly what you had in mind. :-)

Coming in 1.6.
