### ISSUE TITLE
`rand(a: HSlice)` fails with large ranges of int64 or uint64 values

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16296]
`rand` fails with large ranges of int64 or uint64 values

### Example
```nim
when true:
  import std/random
  echo rand(10'u64 .. uint64.high) # bug RangeDefect
  echo rand(-2.. int.high-1) # bug: OverflowDefect
```

### Current Output
RangeDefect or OverflowDefect

### Expected Output
works

### Additional Information
devel 1.5.1 2297b9623843bb4c1dbd201a8fb57f9ec334c164
EDIT: related: https://github.com/nim-lang/Nim/issues/10258

**Comment by arnetheduck** [comment]
#16360
