### ISSUE TITLE
openArray views in VM and js give errors

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16306]
`--experimental:views` don't seem to work well with VM and js:
`toOpenArray` errors in VM, while using it in js as below gives: `Error: internal error: genTypeInfo(tyOpenArray)`

### Example 1: vm
```nim
when true:
  {.experimental: "views".}
  proc test(x: openArray[int]) =
    let y: openArray[int] = toOpenArray(x, 0, 2)
    echo (y[0],)
  template fn=
    test([0,1,2,3,4,5])
  fn() # ok
  static: fn() # Error: cannot generate code for: mSlice
```

### Current Output
Error: cannot generate code for: mSlice

### Expected Output
works

### Example 2: js
nim r -b:js main
Error: internal error: genTypeInfo(tyOpenArray)

```nim
when true:
  {.experimental: "views".}
  proc test(x: openArray[int]) =
    echo (toOpenArray(x, 1, 3),) # ok
    let y: openArray[int] = toOpenArray(x, 1, 3) # Error: internal error: genTypeInfo(tyOpenArray)
    echo (y,)
  var a = [0,1,2,3,4,5]
  test(a)
```

### Possible Solution
see proposal in https://github.com/nim-lang/Nim/issues/16305#issuecomment-742109729
related: https://github.com/nim-lang/Nim/issues/15952

### Additional Information
* devel 1.5.1 f344a704123a4b55e2b3b8a4f736a6739d0683bb

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/21440
