### ISSUE TITLE
Syntax error when `not nil` in return type is followed by `{.inline.}`

### ISSUE THREAD

**Issue by snej** [nim-lang/Nim#16324]
Declaring a proc return type as `not nil` causes a syntax error if a pragma immediately follows:

### Example
```nim
{.experimental: "notnil".}

type Foo = ref object
  value: int
  
proc newFoo1(): Foo not nil =               # This compiles
  return Foo(value: 1)
  
proc newFoo2(): Foo not nil {.inline.} =    # This does not
  return Foo(value: 1)
```

### Current Output
```
NimRunner.nim(9, 40) Error: Invalid syntax. When used with a type, 'not' can be followed only by 'nil'
```

### Expected Output

No compile errors.

### Additional Information
$ nim -v
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2020-12-09
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 4c533b2d92162980dc8fac2332b0eb0739dbda25
active boot switches: -d:release
```

**Comment by snej** [comment]
The same "When used with a type, 'not' can be followed only by 'nil'" error occurs when trying to use `not nil` in a sum type:

```nim
type Foo = ref object
  value: int
type Bar = object
  value: int
type FooBar = Foo not nil | Bar    # Error: Invalid syntax. When used with a type, 'not' can be followed only by 'nil'
type BarFoo = Bar | Foo not nil    # error: Invalid type
```

Workaround is
```nim
type FooNotNil = Foo not nil
type FooBar = FooNotNil | Bar
```

**Comment by metagn** [comment]
The parser normally doesn't accept pragmas at the end of types, but the expression after `not` is parsed as a full expression. This is super easy to remove if only `nil` is allowed after `not` at parser-level, but if the syntax is supposed to be reserved for something else, then it's more complicated, especially with the `Foo not nil | Bar` issue.
