### ISSUE TITLE
Wrong assignment for tuples in some contexts with refc

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#16331]
Issue  #9177 has been solved but there are still situations where we get a wrong result. Here is one:

### Example
```nim
type T1 = tuple[a, b: int]

proc p(b: bool) =
  var x: T1 = (10, 20)
  x = if b: (x.b, x.a) else: (-x.b, -x.a)
  echo x

p(false)  # Expected (-20, -10), got (-20, 20).
p(true)   # Expected (20, 10), got (20, 20).

```

### Current Output

```
(a: -20, b: 20)
(a: 20, b: 20)
```

### Expected Output
```
(a: -20, b: -10)
(a: 20, b: 10)

```

### Possible Solution

Replace ``x = ...`` by ``(x.a, x.b) = ...``.
Instead of ``x = if ...``, use ``if ...: x = ...``.

### Additional Information
This is the same issue as #9177 (closed) in a more complicated context.
Using a case statement instead of an if statement causes the same error.
The issue is present in stable and development compilers.

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

**Comment by awr1** [comment]
Did you run into this issue doing AOC day 12? I just ran into the same issue doing it just now and it looked like a compiler bug.

**Comment by lscrd** [comment]
Yes. I have reported several issues since I try to solve AOC 2020, some of them were already known. I don’t know why I have encountered these issues now. Maybe there is something in AOC problems which leads to write somewhat atypical code.

I reported #9177 issue on 2018 and it was corrected. I’m afraid this new one may be more difficult to solve.
