### ISSUE TITLE
testament: `matrix` in spec should prevent test from joining megatest

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16340]
I found this while reviewing https://github.com/nim-lang/Nim/pull/16320:
it uses `matrix: "-d:ssl"` but still is joined in megatest. Note that this probably should've used `cmd: nim $target -d:ssl $file` but that's not the point of this issue (and in fact `matrix: "-d:ssl"` actually makes more sense even with single entry since it's shorter)

`isJoinableSpec` should handle this properly

### Example
see https://github.com/nim-lang/Nim/pull/16320
```nim
discard """
  matrix: "-d:ssl"
"""
import openssl
```

### Current Output
test is joined in megatest

### Expected Output
test is not joined in megatest, or alternatively we can create 1 megatest per unique matrix options, so that we still get performance benefit of megatest, while honoring matrix spec.

### Additional Information
devel 1.5.1 0b73106ccf983565d34654ee8b1167827b53b01a
`isJoinableSpec` is what should be fixed

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/16577
