### ISSUE TITLE
`&` shows as `&amp;` in docs

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16364]
### Example
in https://nim-lang.github.io/Nim/lib.html search for `&`

### Current Output

![image](https://user-images.githubusercontent.com/2194784/102255601-2677e780-3ebf-11eb-86b4-55d667e99cbe.png)

### Expected Output
show `&`, as it did in stable docs 1.4.x

![image](https://user-images.githubusercontent.com/2194784/102257417-8ff8f580-3ec1-11eb-8dbe-fdf2f8b185a5.png)

### Additional Information
devel 1.5.1 e843492b1334ded1d8fcd0e0eb6dc94fcf970aba
there could be more such symbols

**Comment by xflywind** [comment]
I will fix this. The regression was introduced in this PR:
https://github.com/nim-lang/Nim/pull/15433

**Comment by ringabout** [comment]
It appears in https://nim-lang.org/1.4.2/lib.html
![image](https://user-images.githubusercontent.com/43030857/102488766-89c46e00-40a7-11eb-8b6e-f0282430fc89.png)


notin https://nim-lang.org/1.4.0/lib.html
![image](https://user-images.githubusercontent.com/43030857/102488734-7b765200-40a7-11eb-8787-801c4b737ad7.png)

**Comment by ringabout** [comment]
The regression is introduced in this PR: https://github.com/nim-lang/Nim/pull/15433
I will fix it.

**Comment by ringabout** [comment]
`&`, `>`, `>` etc. are escaped twice which causes this regression.

**Comment by timotheecour** [comment]
unrelated but still worthy to report:
https://nim-lang.github.io/Nim/system.html#disarm.t%2Ctyped

![image](https://user-images.githubusercontent.com/2194784/102527862-9c608800-4052-11eb-8eaa-1e1976ddfc50.png)

EDIT => https://github.com/nim-lang/Nim/pull/16383
