### ISSUE TITLE
Changing all URLs to the new repo after 0.10.0

### ISSUE THREAD

**Issue by Kentoseth** [nim-lang/Nim#1637]
I think I'll be able to handle this admin type of work.

Assign this task to me, so that once Nim 0.10.0 is released during the weekend, I will go about looking for the old URLs to get them changed (where it is accessible) and I'll create a forum post for inaccessible links.

Btw, is it possible to keep both the /Araq/Nimrod and /Araq/Nim repos?

I'd keep the /Nimrod and move 0.10.0 to /Nim .

**Comment by yasoob** [comment]
Kindly check the links now :)

**Comment by Araq** [comment]
0.13.0 is out since a while now. Links have been updated.
