### ISSUE TITLE
regression since 1.4.2: vm crash with lists.SinglyLinkedRing

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16384]
### Example
```nim
import lists

template fn() =
  var L: SinglyLinkedRing[int]
  L.prepend(4)
  doAssert $L == "[4]" # ok

  L.prepend(4)
  doAssert $L == "[4, 4]" # bug: crash wo stacktrace or error

static: fn() # bug
fn() # ok
```

### Current Output
crashes with no output if running via choosenim nim shim
crashes with segmentation fault (no output) if running without nim shim on devel nim binary or 1.4.2, eg:
[1]    97786 segmentation fault nim r main.nim

### Expected Output
works

### Additional Information
1.4.2:
[1]    97786 segmentation fault nim r main
devel 5d8f862bc644e1db076e7e8cc8a2fe8c99009329 1.5.1: 
ditto

1.4.0:
works

discovered while reviewing https://github.com/nim-lang/Nim/pull/16362 and was trying to wrap test inside the classic pattern:
```nim
template main =
  # all the tests here
main()
static: main()
```

which is yet another argument while this pattern is useful, as it'd have prevented this regression

**Comment by Araq** [comment]
> which is yet another argument while this pattern is useful, as it'd have prevented this regression

I don't remember anybody disliking this pattern, it's good.

**Comment by ringabout** [comment]
The regression is introduced by this PR https://github.com/nim-lang/Nim/pull/15724/files
