### ISSUE TITLE
recursive distinct object: compiler frozen at 100% CPU

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#16393]
The following code snippet will stuck the compiler at 100% CPU for 1.2.6, 1.4.2 and devel

```Nim
type
  TrustedSig = distinct TrustedSig
```

**Comment by timotheecour** [comment]
side note:
should be easy to fix; actually that's a good stress test for nimsuggest; IMO nimsuggest should be spawned by another process that would restart (with exponential backoff) it when it "misbehaves" such as using 100% cpu for > n seconds

**Comment by ee7** [comment]
I remember this one. Previously reported in https://github.com/nim-lang/Nim/issues/13008, with slightly different examples.

**Comment by timotheecour** [comment]
duplicate of https://github.com/nim-lang/Nim/issues/13008
