### ISSUE TITLE
Mention requirement of importing 'unsigned' lib in order to use basic arithmetic operators for unsigned integers in the manual.

### ISSUE THREAD

**Issue by woodgiraffe** [nim-lang/Nim#1640]
Trying to use basic arithmetic operators without importing the 'unsigned' lib gives rather cryptic error messages.

While mentioned in the libs documentation, it is not mentioned in the manual.

Propose to mention this requirement in the "Pre-defined integer types"-section.

**Comment by Araq** [comment]
Not required anymore, unsigned is being moved into system.
