### ISSUE TITLE
Incorrect closure code generation

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#1641]
The following program generates code that doesn't compile.

Note that either replacing `do(x):` with `do(x: int)` or putting the code inside a function will prevent the error.

``` nimrod
proc baz() =
  echo "baz"

proc bar(x: int, p: proc()) =
  echo "bar ", x
  p()

proc foo(x: int, p: proc(x: int)) =
  echo "foo ", x
  p(x)

let x = 0
x.foo do(x): x.bar do: baz()
```

**Comment by Araq** [comment]
```nim
# bug #1641
proc baz() =
  echo "baz"

proc bar(x: int, p: proc()) =
  echo "bar ", x
  p()

proc foo(x: int, p: proc(x: int)) =
  echo "foo ", x
  p(x)

let x = 0
x.foo do(x: int): x.bar do(): baz()
```

Produces the correct result with the new lambda lifting.

**Comment by dom96** [comment]
Isn't the use of the ``do`` notation like that deprecated now?

**Comment by Yardanico** [comment]
Was fixed (checked by myself)

**Comment by Araq** [comment]
@Yardanico Please add more test cases and commit with the message "closes #xyz" to close issues like these.
