### ISSUE TITLE
rdstdin (linenoise) breaks the C++ backend

### ISSUE THREAD

**Issue by HJarausch** [nim-lang/Nim#16449]
```nim
import rdstdin
echo "Merry Christmas"
let ans= readLineFromStdin("do you follow the Corona rules ")
if ans != "yes" :
  echo "but you should!"
else :
  echo "fine"
```

#[
Compiling this with   nim cpp -r Hello.nim
gives
/usr/lib/nim/wrappers/linenoise/linenoise.c: In function 'void abAppend(abuf*, const char*, int)':
/usr/lib/nim/wrappers/linenoise/linenoise.c:462:11: error: expected unqualified-id before 'new'
  462 |     char *new = realloc(ab->b,ab->len+len);
      |           ^~~
/usr/lib/nim/wrappers/linenoise/linenoise.c:464:13: error: expected type-specifier before '==' token
  464 |     if (new == NULL) return;
      |             ^~
/usr/lib/nim/wrappers/linenoise/linenoise.c:465:15: error: expected type-specifier before '+' token
  465 |     memcpy(new+ab->len,s,len);
      |               ^
]#
```

**new** is a keyword in C++ and must not be used as an identifier.
linenoise.c should be fixed to be valid C++ .
e.g. by applying the attached patch
[linenoise.c.diff.txt](https://github.com/nim-lang/Nim/files/5735670/linenoise.c.diff.txt)

Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b1c3dab2089bb4327627c2152a1148b299f1a930
active boot switches: -d:release
5

**Comment by ringabout** [comment]
see https://github.com/nim-lang/Nim/issues/3720
and https://github.com/antirez/linenoise/pull/87

**Comment by ringabout** [comment]
Note that

>> This module contains code for reading from `stdin`:idx:. On UNIX the
 linenoise library is wrapped and set up to provide default key bindings
(e.g. you can navigate with the arrow keys). On Windows ``system.readLine``
is used. This suffices because Windows' console already provides the
 wanted functionality.

`nim cpp` works in windows since ``system.readLine`` is used.

**Comment by ringabout** [comment]
PR is welcome

**Comment by timotheecour** [comment]
proposed approach to fix this: see https://github.com/nim-lang/Nim/pull/16451#issuecomment-750759693

**Comment by timotheecour** [comment]
@HJarausch I can't reproduce

on osx: works
(fee5fbc722295a49aad4980a915ff2d41c1fa701 1.5.1 and also 1.4.2 work)


on linux: works

ya works for me on linux too w 1.5.1
d34d023da1d7af972366c3af58a144b395964b4c
g++
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)


command:
`nim r -b:cpp main`

**Comment by krux02** [comment]
I have a déjà vu here. This discussion has been there in the past. It had been resolved. The problem was fixed. This is a regression.
https://github.com/nim-lang/Nim/pull/5357#issuecomment-278658195

**Comment by ringabout** [comment]
If someone can reproduce this issue, feel free to reopen.
