### ISSUE TITLE
nim can't handle integer literal -9223372036854775808i64 and -2147483648i32 properly

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#16466]
nim can't not handle literal value -9223372036854775808 and -2147483648 properly, please see example code.

Example code: 

### Example
https://play.nim-lang.org/#ix=2JpF

```
echo int64.low
echo int32.low

var a = -9223372036854775807i64
assert a == -9223372036854775807i64
assert (a-1) == int64.low
# Error: unhandled exception: over- or underflow [OverflowDefect]
#echo a-2

var b = -2147483647i32
assert b == -2147483647i32
assert (b-1) == int32.low
# Error: unhandled exception: over- or underflow [OverflowDefect]
#echo b-2

# number out of range: '9223372036854775808i64'
#let c = -9223372036854775808i64
# number out of range: '9223372036854775808'
#let d: int64 = -9223372036854775808
# number out of range: '9223372036854775808'
# let e = int64(-9223372036854775808)

# number out of range: '2147483648i32'
#let f = -2147483648i32
# type mismatch: got <int64> but expected 'int32'
#let g: int32 = -2147483648

let h = int32(-2147483648)
assert h == int32.low
```

### Current Output
I have tried latest version, the problem remain.
```
nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-25
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: a29bbeee41e43f00ba7a3b1951445ff5d21ccc52
active boot switches: -d:release
```

### Expected Output
nim should compile without any problem.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-12-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```
I also tried to run above example code as nim script, the same problem.

**Comment by metagn** [comment]
I believe there is an issue for this? If there is not, then I do remember it being mentioned that this is because `9223372036854775808i64` is evaluated first and then negated. There might just be a RFC about solving it and no actual issue.

**Comment by Araq** [comment]
Nim handles it properly, according to its spec. ``-1`` is not a literal, it's unary minus followed by a literal. This needs a language change in order to support it.

**Comment by derekdai** [comment]
I saw this language change in manual and tried it, work perfectly, thank you @Araq.
