### ISSUE TITLE
regression: rst2html broken (eg: manual.html gets truncated to a small part)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16490]
see https://nim-lang.github.io/Nim/manual.html vs https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords

the manual in devel now stops at the section `Identifiers & Keywords`

![image](https://user-images.githubusercontent.com/2194784/103183211-b9bcff80-4865-11eb-8d3b-596abb4a316e.png)

![image](https://user-images.githubusercontent.com/2194784/103183222-c6415800-4865-11eb-94ad-663c91f54095.png)

I'm suspecting this could be due to recent rst PR's

EDIT: indeed, this PR https://github.com/nim-lang/Nim/pull/16438 seems responsible (works right before, fails right after)

**Comment by ringabout** [comment]
Yeah, I can confirm the regression,
