### ISSUE TITLE
`1.0 / abs(-0.0)` returns -inf instead of inf

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16494]
* abs(-0.0) returns -0.0 instead of 0.0, which causes further issues, eg:
`1.0 / abs(-0.0)` returns -inf instead of inf
* likewise, it should behave like fabs even for NaN (ie setting the sign bit) 

### Example1: -0.0
```nim
doAssert 1.0 / abs(-0.0) == Inf
```

### Current Output
fails

### Expected Output
works

### Example 2: same issue with nans
```nim
when true:
  proc fabs(a: cdouble): cdouble {.importc.}
  proc signbit(a: cdouble): cint {.importc, header: "<math.h>".}
  proc copySign(a, b: cdouble): cdouble {.importc: "copysign", header: "<math.h>".}
  let nan2 = copySign(NaN, -1.0)
  doAssert nan2.fabs.signbit == 0 # ok
  doAssert nan2.abs.signbit == 0 # fails
```

### Possible Solution
for implementation of `abs(SomeFloat)`, use importc fabs and fabsf in RT + VM (via vmops), with a fallback for js as usual; the fallback for js can use the same logic as for copySign(see https://github.com/nim-lang/Nim/pull/16406)

### Additional Information
devel 1.5.1 6d442a40a6f89572052d61aeb73ec26d1f3451ce

**Comment by ringabout** [comment]
```nim
proc abs*(x: float64): float64 {.noSideEffect, inline.} =
  if x < 0.0: -x
  elif x == 0.0: 0.0
  else: x
proc abs*(x: float32): float32 {.noSideEffect, inline.} =
  if x < 0.0: -x
  elif x == 0.0: 0.0
  else: x
```
