### ISSUE TITLE
Asynchttpserver example doesn't work

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#16506]
https://github.com/nim-lang/Nim/blob/95f599ca2d94e4d58055390c4b9c7761bbd60d01/lib/pure/asynchttpserver.nim#L26-L43

Runs out of memory with default gc as well as orc. OS arch linux

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-29
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 95f599ca2d94e4d58055390c4b9c7761bbd60d01
active boot switches: -d:release --gc:markAndSweep
```

**Comment by timotheecour** [comment]
bug 1: looks like it's a busy loop, `runForever()` isn't even used, the example seems bad, PR welcome

bug 2: also, that block of code is duplicated at bottom inside `when not defined(testing) and isMainModule:`, this is bad and should be replaced by a single `runnableExamples` (with `if false` pattern); EDIT: => https://github.com/nim-lang/Nim/pull/16586

**Comment by planetis-m** [comment]
If only I knew how async works..
