### ISSUE TITLE
Nim's docs only apply dark mode theming after page content loads

### ISSUE THREAD

**Issue by omentic** [nim-lang/Nim#16515]
Nim's dark mode doesn't load in until after the page content does, so it flashes white on every new page load. Extremely critical, I know, but it is somewhat jarring when coding late at night.

### Example

https://user-images.githubusercontent.com/35242550/103350458-e5eaa300-4a54-11eb-8f9a-243fad3a7c20.mp4

Reproducible by clicking reload while holding `Shift` on any docs page.

https://user-images.githubusercontent.com/35242550/103350471-edaa4780-4a54-11eb-9103-38348f88e3f5.mp4

Similarly reproducible on Firefox, but much less noticeable.

### Current Output
This was tested on the nightly docs.

### Expected Output
The dark theme should be styled as the docs load, rather than afterwards.

**Comment by planetis-m** [comment]
Related: https://github.com/nim-lang/Nim/pull/16247

**Comment by omentic** [comment]
Interesting, strange the issue still persists after that got merged. Does nim-lang.github.io not load from `devel`?

**Comment by ghost** [comment]
@j-james can you try on https://nim-lang.github.io/Nim/system.html again?

**Comment by omentic** [comment]
@Yardanico I'm not seeing any difference from the videos above, unfortunately.

**Comment by timotheecour** [comment]
> Reproducible by clicking reload while holding Shift on any docs page.

i can reproduce this indeed. I'm marking this as low priority, however.
