### ISSUE TITLE
`delete(seq, index)` with invalid index deletes an element instead of raising

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16544]
### Example
```nim
when true:
  var a = @[1,2,3]
  a.delete 6
  echo a
```

### Current Output
@[1, 2]

### Expected Output
raise `IndexError` via `raiseIndexError2`

### Additional Information
devel 1.5.1 505d04389ad5c83b50001e3108d89fcdec9c462f
a fix should include a comprehensive test 

note that `RangeDefect` is raised if passing `i` == 0 with x.len == 0
> Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]

note that `del` correctly raises:
`Error: unhandled exception: index 6 not in 0 .. 2 [IndexDefect]`

**Comment by juancarlospaco** [comment]
I hit the bug too, more examples:

```nim
var a: seq[int] = @[0]
a.delete(999999999999)
```

```nim
var a: seq[int] = @[0]
discard a.pop()
a.delete(999999999999)
```

```nim
var a: seq[int] = @[0]
discard a.pop()
a.insert(42, 0)
a.delete(999999999999)
```

`del` works consistently on all cases:

`Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]` or similar.

**Comment by ringabout** [comment]
What do you expect `subStr` with invalid index?
subStr(s, -4, 10) or ?

See also
https://github.com/nim-lang/Nim/pull/16280#discussion_r580971110

**Comment by arnetheduck** [comment]
well, I argue in https://github.com/nim-lang/Nim/issues/16492 that first and foremost, all these operations would ideally present a logically consistent picture, both native types, library types and at compile time - in fact, the most important thing is that they are consistent with each other - ie when one is defined in a particular way, the others follow.

Generally, I probably have a slight preference for being lenient with ranges / slices (towards python, but also C++ allows some leniency in these kinds of operations), ie simply return the overlapping part, but one could argue for strictness I guess - there's already lots of `Defect`/panics all over the place which don't _really_ need to be panics, so from that point of view, strictness and lots of panics that users have to guard against is more nim-like.

**Comment by hnicke** [comment]
Just stumbled across this too.
Coming from kotlin and python, I really didn't expect `delete` to remove the last element if index is out of bounds.
I consider this to be dangerous.
Instead, I expect it too either raise an Exception or return nil (where else it would return the removed value).

**Comment by hnicke** [comment]
Is the general consensus that `delete` should behave exactly like `del` in this case, e.g. like below?
```nim
let xs = @[0,1]
xs.delete(2)
# Error: unhandled exception: index 2 not in 0 .. 1 [IndexDefect]
```

**Comment by Araq** [comment]
Can confirm, yes.
