### ISSUE TITLE
cast float to int doesn't work in JS VM

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#16547]
```nim
static:
  echo cast[int](12.0)
```
Error: VM does not support 'cast' from tyFloat to tyInt

Work in C VM.

**Comment by timotheecour** [comment]
nim r -b js main:
```nim
when true:
  static:
    echo cast[int64](12.0) # 4622945017495814144
    echo cast[uint64](12.0) # 0 (bug)
    # echo cast[int](12.0) #  Error: VM does not support 'cast' from tyFloat to tyInt
    # echo cast[uint](12.0) #  Error: VM does not support 'cast' from tyFloat to tyUInt

```

**Comment by metagn** [comment]
Original issue is 32 bit related, see `srcSize == dstSize` [here](https://github.com/nim-lang/Nim/blob/c6c85f84db3bd7bd2d1c5823020c7df007f1bb69/compiler/vmgen.nim#L901-L902) (basically you can only cast between the same size ints and floats, but `int` is 32 bit and `float` is 64 bit).

> `echo cast[uint64](12.0) # 0 (bug)`

Gives correct output on 1.6.

**Comment by metagn** [comment]
Is there a bug here? It's specifically documented:

```nim
# vmdef.nim
type
  TOpcode* = enum
    ...
    opcCastIntToFloat32,    # int and float must be of the same byte size
    opcCastIntToFloat64,    # int and float must be of the same byte size
    opcCastFloatToInt32,    # int and float must be of the same byte size
    opcCastFloatToInt64,    # int and float must be of the same byte size
    ...
```

`int` in JS is `int32` and `12.0` is `float` which is `float64`, casting `float64` to `int32` is not allowed because they're not the same size.

Make this clear in the error message maybe?
