### ISSUE TITLE
hash float doesn't work in JS or VM backend

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#16542]
```nim
import hashes

echo hash(0.3456)
```
devel

Output:

```
D:\QQPCmgr\Desktop\Nim\pair.js:265
          var res   = hi_xor_lo_js(hi_xor_lo_js(P0, BigInt(x_486539499) ^ P1), P58);
                                                    ^

RangeError: The number 0.3456 cannot be converted to a BigInt because it is not an integer
```

I will revisit https://github.com/nim-lang/Nim/pull/16403 and make it work for JS backend.

**Comment by timotheecour** [comment]
worked in 1.2.6, fails in 1.4.0

**Comment by ringabout** [comment]
Not really, it should return int, never return float

Nim 1.2.6
```nim
import hashes

echo hash(0.1234)
```
>> 0.1234

**Comment by timotheecour** [comment]
indeed, it's only a "partial regression"; depending on use case, it could've been good enough or not; but ya, this should be fixed properly

**Comment by ringabout** [comment]
It doesn't work in VM too.
