### ISSUE TITLE
Regression with cast[int](any value) when using --gc:arc (invalid C code generated).

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#16558]
Works with normal GC, breaks with arc. I use the cast anything to an int as a way to tell the compiler benchmarking stuff to not compile the code out. See real use here: https://github.com/treeform/benchy/blob/master/src/benchy.nim#L51

Here is the toy example that breaks:

```nim
var value = "hi there"
var keepInt: int
keepInt = cast[int](value)
```

### Current Output with
```
nim c -r --gc:arc .\src\arcissue.nim
C:\Users\me\nimcache\arcissue_d\@marcissue.nim.c: In function 'NimMainModule':
C:\Users\me\nimcache\arcissue_d\@marcissue.nim.c:147:2: error: aggregate value used where an integer was expected
  keepInt__rIGajyDYT9czKslPCVr6AfQ = ((NI) (value__y9cVUe9aNnWzZaTs9bUkcUffg));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Output

It compiles. Does not optimize the value out. Or a compiler error saying some thing "cast[int] does not work with --gc:arc".

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2020-12-02
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Clyybber** [comment]
This cannot work with `gc:arc` because strings are a `(len, pointer)` tuple there.

https://github.com/nim-lang/Nim/issues/13154 and https://github.com/nim-lang/Nim/issues/13864 are similar.

**Comment by treeform** [comment]
This should be a nim error not a c compiler error.

Do you have any idea on how I can keep the optimizer out with --gc:arc?

Could the cast just take the len... first 64 bits of the tuple?

**Comment by Clyybber** [comment]
Yeah, of course nim should catch this error.
Maybe you could take the addr and cast it?

**Comment by treeform** [comment]
Yes I tried `addr` and `unsafeAddr`, but it says `Error: expression has no address` not in this case, but in other cases.

Maybe there is a C thing I could do with {.emit.}?
