### ISSUE TITLE
Unexpected behaviour of `longestMatch` in ...WithPrefix iterators from critbits

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#16575]
It is not clear to me how the `...WithPrefix` iterators from the `critbits` module should behave when used with `longestMatch`.

### Example
```nim
import critbits
from sequtils import toSeq

var c: CritBitTree[int]
c["key1"] = 1
c["key2"] = 2

echo toSeq(c.keysWithPrefix("lol", longestMatch = true))
echo toSeq(c.keysWithPrefix("keys", longestMatch = true))
```

### Current Output
```
@["key1", "key2"]
@["key2"]
```

### Expected Output
The documentation currently says:

> If `longestMatch` is true, the longest match is returned, it doesn't have to be a complete match then. 

I initially assumed this means that (if no elements match exactly) only a single element is yielded, which is a longest match. However, as you can see in the first part of the example, that is not always the case. But it doesn't yield every longest match either, as you can see in the second part of the example.

### Possible Solution

* It is a bug and the intended behaviour is to only yield a single element which is a longest match.
* It is a bug and the intended behaviour is to yield all the longest matches.
* The current behaviour is intended.

In any case, a better explanation of the intended behvaiour is needed. Alternatively, we could just remove the `longestMatch` parameter, since it doesn't seem particularly useful to me.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1
git hash: 297c8e403d110dd872e070563328f4e0c734cd01
```

**Comment by timotheecour** [comment]
I vote for:
It is a bug and the intended behaviour is to yield all the matches with longest prefix match. 
so:
if keys are keyfoobar, key1, key2, kelp
`echo toSeq(c.keysWithPrefix("lol", longestMatch = true))`
should return all keys (keyfoobar, key1, key2, kelp)

`echo toSeq(c.keysWithPrefix("keys", longestMatch = true))`
should return (keyfoobar, key1, key2) but not kelp which has a smaller prefix match


rationale: user can always break in iterator after 1st item, so it subsumes other behavior

**Comment by konsumlamm** [comment]
@Araq you may be able to clarify this, since you added this feature in e9313dd3621f41ce6be875462769636ab67c2032. I skimmed over the paper the `critbits` implementation is based on, but couldn't find a mention of this.

**Comment by Araq** [comment]
I don't remember this code, fix it in the way you seem fit please.

**Comment by konsumlamm** [comment]
After looking at the crit-bit tree paper more closely, I don't think this could be easily fixed, since the trees are encoded based on the (differences in the) bits of the strings, not the individual chars. Moreover, the actual strings are only stored in the leafs, so it's impossible to know what char is encoded in the current node (and in particular if the current node still belongs to a prefix).

As for the current behaviour, it is not something a user would expect, for example (even worse than my initial examples):
```nim
let c = ["ab", "bc", "be"].toCritBitTree
echo toSeq(c.itemsWithPrefix("c", longestMatch = true)) # => @["bc", "be"]
```

So (unless I missed something and someone has a fix for the longest match algorithm), I think the crit-bit tree just doesn't lend itself to iterate over the longest matching prefixes. I would just remove the `longestMatch` parameter or, if that's not possible because of backwards compatibility, document it as not working or make it have no effect.

EDIT: Of course another solution would be to write an (inefficient) algorithm that converts the crit-bit tree to a seq and then searches for the longestMatch.

**Comment by Araq** [comment]
> I would just remove the longestMatch parameter or, if that's not possible because of backwards compatibility, document it as not working or make it have no effect.

Let's please do that then, yes.

**Comment by konsumlamm** [comment]
> > I would just remove the longestMatch parameter or, if that's not possible because of backwards compatibility, document it as not working or make it have no effect.
> 
> Let's please do that then, yes.

Which option do you mean?

**Comment by timotheecour** [comment]
How about add an overload with this param and deprecate it

**Comment by Araq** [comment]
> Which option do you mean?

Please remove the "longestMatch" parameter for good. And document that it never worked reliably in the changelog.
