### ISSUE TITLE
renderSQL can't handle special charaters (e.g. Umlaut)

### ISSUE THREAD

**Issue by SFR0815** [nim-lang/Nim#16585]
Function `renderSQL` outputs the wrong string.

### Example
```import parsesql
let word = "Schätze"
let word_sql = newNode(k = nkStringLit, s = word)
echo word_sql.renderSQL()
echo word_sql.strVal
```

### Current Output
```
'Sch\xC3\xA4tze'
Schätze
```

### Expected Output
```
'Schätze'
Schätze
```

### Comment
Let's ask Liselotte Pulver for some Umlaut-classes as granted to James Cagney (One, Two, Three - Billy Wilder, 1961).

**Comment by Araq** [comment]
What does the SQL standard say about it?

**Comment by SFR0815** [comment]
Well, did not invest to download the ISO-standard but got this one from [https://www.postgresql.org/docs/9.2/sql-syntax-lexical.html](url): 

**4.1.2.1. String Constants**

A string constant in SQL is an arbitrary sequence of characters bounded by single quotes ('), for example 'This is a string'. To include a single-quote character within a string constant, write two adjacent single quotes, e.g., 'Dianne''s horse'. Note that this is not the same as a double-quote character (").

**Comment by Araq** [comment]
Good enough for me.
