### ISSUE TITLE
Change names of inverse hyperbolic functions

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#16587]
### Summary
Change the names of the inverse hyperbolic functions (from the `math` and `complex` modules) to use the `ar` prefix and deprecate the old version.

### Description
Currently, the inverse hyperbolic functions from `math` and `complex` start with `arc` (`arcsinh`, `arccosh`, ...). This comes from arcus, which is used for the inverse *trigonometric* functions. The usual prefix for the inverse hyperbolic functions is `ar` (coming from area), so the names should be `arsinh`, `arcosh`, ..., see also: https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions#Notation. The versions with the `arc` should be deprecated then.

### Alternatives
Keep the names as they are, since as mentioned in the linked article, the `arc` prefix is also commonly seen, the `ar` prefix is just more mathematically correct. I completely understand if you don't want to change the names.

**Comment by awr1** [comment]
Other languages/libraries (e.g. GLSL, JS) tend to use `acosh`, some use `ArcCosh` e.g. [Mathematica](https://reference.wolfram.com/language/ref/ArcCosh.html), [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html), etc.

I will take the descriptivist route and say that "arccosh/arcsinh/..." have clearly become established terminology at this point in spite of the technical linguistic quirks. There is no real need to rename these procedures.

**Comment by timotheecour** [comment]
i prefer current names (even if we were to do it from scratch)
rationale: only `h` is added to distinguish hyperbolic vs not (arccos vs arccosh)

ditto with C++ (asin vs asinh)
ditto with numpy (arccos vs arccosh)

in that sense, nim is also consistent with other languages.

**Comment by juancarlospaco** [comment]
You can create a library with template aliases/sugar maybe.

**Comment by konsumlamm** [comment]
Closing, since apparently noone is interested in this changes and the arc prefix is common emough (e.g. numpy).
