### ISSUE TITLE
[false virus report] Real Protect.cb!AF8DE0A703A1 by os.getConfigDir()

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#16623]
I compiled the simple code in Mingw64+Msys2 on windows 10. 
```
import os

echo getConfigDir()
```

```nim c -r a.nim```
The exe shows the result, but was quarantined by McAfee as "Real Protect.cb!AF8DE0A703A1" virus

so why this happens and how to avoid it? Thanks

**Comment by alaviss** [comment]
It's McAfee... I would recommend you to get rid of it from your machine.

As for the false positive, looks like it's a common thing: https://community.mcafee.com/t5/Malware/False-Positive-Real-Protect-EC-DEB4BEA88807/td-p/592174

You should follow the instructions laid out by McAfee to submit false positives: https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&articleId=TS103032&_afrLoop=1080398082792797&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25

**Comment by Araq** [comment]
Nothing we can do anything about. We cannot fix Antivir software bugs (plus their whole approach to "security" is completely flawed).
