### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by srbehera** [nim-lang/Nim#16626]
I am getting the following error while installing and this is coming because there is no space in the home directory (`/users/xyz/`). I am just wondering where do I need to replace the home directory with another directory i.e. `/users/xyz/` with `/PATH/`.
```
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3  -I/PATH/Nim/lib -I/PATH/Nim -o /users/u236519/.cache/nim/koch_d/stdlib_assertions.nim.c.o /users/xyz/.cache/nim/koch_d/stdlib_assertions.nim.c' failed with exit code: 1
```

**Comment by Araq** [comment]
Incomprehensible. What is ``/PATH/``? Why would spaces matter, we quote things when you have spaces in your home directory, but apparently you lack the spaces just like everybody else.

**Comment by srbehera** [comment]
I have TBs of space in the project directory that is assigned to me in the server, but only a few MBs in the home directory. The `/PATH/` is the project directory (the full path looks like this `/abc/xyz/......../projects/MyID`) where the source codes are present.

I could install on my personal laptop, but git these issues when I tried to use on school cluster where each user is assigned with few MBs in their home directory.

**Comment by Araq** [comment]
Ah, "space on disk", not "space -- the ASCII symbol"! Try to set ``--nimcache`` to somewhere where you have space left.

**Comment by srbehera** [comment]
Do I need to change it in `nimc.rst` ? Else, could you please let me know the file where I need to make changes.

**Comment by srbehera** [comment]
Previously I tried replacing `$HOME` and `~ `with the directory with enough space. But I got the same error.

**Comment by timotheecour** [comment]
`nim c --nimcache:somedirwithenoughspace main.nim`

closing; feel free to re-open or comment if there's still an issue
