### ISSUE TITLE
Modules not linked in the main stdlib documentation

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#16656]
### Summary

Looking at [the index](https://nim-lang.github.io/Nim/theindex.html), there are quite a few modules that are not linked from the main stdlib documentation (https://nim-lang.github.io/Nim/lib.html):

* https://gist.github.com/konsumlamm/d19d217ddd138d2172c7f48be2e9d71d

Most of them seem to be internal/experimental/unstable (note that some unstable modules are nevertheless linked), but some look like they should be linked from the main stdlib documentation page, for example:

* [x] assertions
* [x] atomics (#17430)
<del> * [] channels </del>
* [x] enumerate (#17430)
* [x] io
* [x] jsbigints
* [x] jsonutils (#17430)
* [x] nre
* [x] packedsets (#16715)
* [x] parsejson (#17430)
* [x] rdstdin (#17430)
* [x] setutils (#16791)
* [x] tempfiles (#19807)
* [x] with (#17430)
* [x] std/exitprocs

Is there a reason they aren't linked? Are there more modules that should be linked? And perhaps there are some modules that are currently linked, but shouldn't be (like `intsets`)?

Related issue: #16046.

### Possible solution

I'd be willing to create a PR to link all the missing modules.

As mentioned in the linked issue, while generating the documentation, one could automatically check that all modules are linked. For modules that are not supposed to be linked (internal, experimental, deprecated or unstable modules), there could be a way (a pragma or a special comment?) to mark them as such. Alternatively, they could be linked in a separate section ("Internal modules").

**Comment by metagn** [comment]
io and assertions are submodules of the system module

**Comment by konsumlamm** [comment]
> io and assertions are submodules of the system module

I'm aware, but so are channels and threads, or are these different (other than only being available with `--threads:on`)? I think they should be linked at the top level anyway, since the system module is not necessarily where I would expect these things (when starting with Nim, I couldn't find anything related to File IO iirc). I'd still put them in the "Automatic imports" section of course, to make it clear that they're part of the system module. Though I'd also be fine with keeping them only being linked from the system docs.

**Comment by juancarlospaco** [comment]
Send PR maybe...

**Comment by ghost** [comment]
There's quite a lot of modules that are nowhere to be found in https://nim-lang.github.io/Nim/lib.html, for example quite a lot of modules from https://github.com/nim-lang/Nim/tree/devel/lib/std

**Comment by AFaurholt** [comment]
I noticed rdstdin was missing

**Comment by iacore** [comment]
Also missing:
- [x] [posix](https://nim-lang.org/docs/posix.html)

**Comment by konsumlamm** [comment]
> Also missing:
> 
>   * [x]  [posix](https://nim-lang.org/docs/posix.html)

@locriacyber it's linked here: https://nim-lang.github.io/Nim/lib.html#wrappers-unix-specific.

**Comment by iacore** [comment]
Not searchable, not in "The Index" in 1.6.4. Try searching "fork".

**Comment by konsumlamm** [comment]
That's not what this issue is about though (it's about modules linked from https://nim-lang.github.io/Nim/lib.html). The index apparently not including the `posix` module seems to be a different issue, I'd suggest opening a new issue for it.

**Comment by Araq** [comment]
It's not a bug, we want the index to contain useful information and not the Posix API. You're not supposed to use the Posix APIs unless you know what you're doing and in that case, you don't need the index.
