### ISSUE TITLE
Borrowing `.` (dot access operator) doesn't work from alias type

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#16666]
### Example
```nim
type
  AImpl = object
    i: int
  
  A = AImpl
  
  B {.borrow: `.`.} = distinct A

let b = default(B)

echo b.i
```

### Current Output
```
test.nim(11, 7) Error: undeclared field: 'i' for type in.B [declared in test.nim(7, 3)] 
```

### Expected Output
```
0
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-05
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2c2baa9fad1d144c42baf30ed004decdf8bb0483
active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by metagn** [comment]
Relevant lines:

https://github.com/nim-lang/Nim/blob/fb80d2ff85fc5db2996d6660075941e1256564fe/compiler/semexprs.nim#L1244-L1246

https://github.com/nim-lang/Nim/blob/fb80d2ff85fc5db2996d6660075941e1256564fe/compiler/semexprs.nim#L1374-L1375

The `skipTypes` calls are most likely supposed to also be added after the `while`, but not sure if the skipped type sets should stay the same.
