### ISSUE TITLE
cstring.default.len raises a js error instead of returning 0 as in other backends

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16674]
### Example
```nim
proc main()=
  var a: cstring
  echo a.len
static: main()
main()
```

### Current Output
c:
vm: 0
rt: 0
js:
vm: 0
rt: TypeError: Cannot read property 'length' of null

### Expected Output
c:
vm: 0
rt: 0
js:
vm: 0
rt: 0

### Additional Information
* 1.5.1 2c6f5ae6815367dcb44e441c8f3bda2e2513b061
* (different issue) https://github.com/nim-lang/Nim/issues/15730

**Comment by metagn** [comment]
`a.length` => `a != null ? a.length : 0` in jsgen with a temp should do it

**Comment by ringabout** [comment]
ditto: low/high(`cstring(nil)`) in JS backend
