### ISSUE TITLE
Error adding object with an openarray field to seq of base type

### ISSUE THREAD

**Issue by benob** [nim-lang/Nim#16671]
I am new to nim, sorry if this issue is inappropriate. While trying to add an openarray to an object, I encountered a c compiler error. 

The following code:
```nim
type X = ref object of RootObj
type Y = ref object of X
  field: openarray[int]

var s: seq[X]
proc f() =
  s.add(Y(field: [1]))

f()
```
Results in
```
/home/user/.cache/nim/test_d/@mtest.nim.c: In function ‘f__9bYThM6NliRXN1SXFwqXl9aw’:
/home/user/.cache/nim/test_d/@mtest.nim.c:415:2: error: cannot convert to a pointer type
  415 |  nimCopyMem((void*)(*T1_).field, (NIM_CONST void*)TM__wUwZNZbM8FcO0T0cAKGahQ_4, sizeof(tyArray__GAcaPw08Gj9cXYhAaMMr9cfw));
      |  ^~~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I'/home/user/.choosenim/toolchains/nim-#devel/lib' -I/home/user/saved/devel/games/expelled-rl/nim -o /home/user/.cache/nim/test_d/@mtest.nim.c.o /home/user/.cache/nim/test_d/@mtest.nim.c' failed with exit code: 1
```
If the sequence is not on the base class, the compiler spits an (not very explicit) error:
Error: invalid type: 'openArray[int]' in this context: 'seq[Y]' for var

### Additional Information
Tested on nim 1.4.2 and #devel dbff2cd938b326279de0f3f97b2dd8c54a90468a

**Comment by metagn** [comment]
If you explicitly convert like so:

```nim
type X = ref object of RootObj
type Y = ref object of X
  field: openarray[int]

var s: seq[X]
proc f() =
  s.add(Y(field: openarray [1])) # this is allowed for some reason, means openarray([1]), you can use openarray[int]([1]) too

f()
```

it works (same behavior for experimental views on/off). So the conversion behavior is still short circuitting in this case as it would for proc arguments.

**Comment by benob** [comment]
I am quite confused by the fact that it compiles for seq[X] but not for seq[Y].

``` nim
type X = ref object of RootObj
type Y = ref object of X
  field: openarray[int]

var s: seq[Y] # change X to Y
proc f() =
  s.add(Y(field: openarray [1]))

f()
```
Results in
```
Error: invalid type: 'openArray[int]' in this context: 'seq[Y]' for var
```

**Comment by metagn** [comment]
> I am quite confused by the fact that it compiles for seq[X] but not for seq[Y].

If you add {.experimental: "views".} before (which is how you enable openarray outside of proc parameters for now), it instead gives `Error: cannot determine the target of the borrow`, which I don't know the meaning of. Information about view types is here: https://nim-lang.github.io/Nim/manual_experimental.html#view-types

Also, I found out that while `openarray[int]([1])` instead of `openarray([1])` gives the same codegen error as before
