### ISSUE TITLE
`add(a, b)` buggy in RT js or in VM when a or b is a nil cstring

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16686]
### Example 1
```nim
proc main()=
  block:
    var a: cstring = nil
    a.add "ba"
    echo (a,)
  block:
    var b: cstring = "ba"
    var b2: cstring
    b.add b2
    echo (b,)
  block:
    var a: cstring = nil
    a.add a
    echo (a,)
  block:
    var a: cstring = "ab"
    a.add a
    echo (a,)
  block:
    var a: cstring = nil
    echo (a,)

static: main()
main()

```

### Current Output
vm js:
("ba",)
("ba",)
("",)
("abab",)
("",) # this is a separate issue, fixed in https://github.com/nim-lang/Nim/pull/16026

rt js:
("nullba",)
("banull",)
("",)
("abab",)
(nil,)

### Expected Output
vm js:
("ba",)
("ba",)
("",)
("abab",)
(nil,)

rt js:
("ba",)
("ba",)
("",)
("abab",)
(nil,)

### Example 2
```nim
when true:
  proc main()=
    block:
      var a: cstring = nil
      a.add "ba".cstring
      echo (a,)
    block:
      var b = "ba"
      var b2: cstring
      b.add b2
      echo (b,)
  # static: main()
  main()
```
prints:
("nullba",)
/Users/timothee/git_clone/nim/timn/build/nimcache/t11680.js:376
      x_33556413[x_33556413_Idx].length += y_33556414.length;
(2 bugs here)

### Example 3: js vm
uncomment `static: main()` in Example 2
gives CT error:
```
system.nim(1987, 5) Error: cannot generate VM code for asm "      if ("x
```

### Example 4: vm (eg c vm)
```nim
when true:
  proc main=
    var a = "abc"
    a.add nil
    echo (a,)
  static: main()
  main()
```
VM:
 Error: index out of bounds, the container is empty
        while y[i] != '\0':

### Additional Information
1.5.1 be6e8916faa51d227d51e1291d1f24751385b010

**Comment by metagn** [comment]
This overload add(var cstring, cstring) is not in the system docs. The block that [declares it](https://github.com/nim-lang/Nim/blob/f6c2450cdb7e24b5dbd118494560cc8452dd3688/lib/system.nim#L1985) does not check for defined(nimdoc). The overload here uses `AppendStrStr`, for which I, without thinking of the possibility that cstrings might be nil, deleted the null checks for and simply turned into `a += b` for some reason in #14158. Dead easy fix, just revert this line and add back the deleted temp to the cstring branch (#16674 is also introduced by this PR though so you might need to look for more problems), but also add `or defined(nimdoc)` to the when statement in the system module and maybe look for other declarations that might not have docs in the standard library.

As for VM, maybe `when nimvm: add(x, string(y)) else: asm ...` in the same proc.
