### ISSUE TITLE
testament spec `nimout` too lax

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16693]
nimout spec seems to just check that each line in nimout is a contiguous substring of a line in compilation output. This is way too lax for being usable, as shown here:

### Example 1
```nim
discard """
  nimout: '''
foobar2
foobar
foobar
foobar2
oobar
ba
'''
"""

static: echo "foobar1"
static: echo "foobar2"
```

XDG_CONFIG_HOME= nim r testament/testament.nim r tests/misc/t11682b.nim

### Current Output
PASS: tests/misc/t11682b.nim c 

### Expected Output
fails

### Example 2
this can go horribly wrong, see https://github.com/nim-lang/Nim/pull/16698#discussion_r556938409

### Possible Solution
* each line in nimout should be a complete line in compilation output (no substring match)
* it's ok to have unmatched lines in output (useful for new warnings/hints etc)
* order cannot change
* each matched line should only be used once

EDIT: this is maybe the thing to fix (in testament.nim):
```nim
proc greedyOrderedSubsetLines*(lhs, rhs: string): bool =
  ## returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
  let rhs = rhs.strip
  var currentPos = 0
  for line in lhs.strip.splitLines:
    currentPos = rhs.find(line.strip, currentPos)
    if currentPos < 0:
      return false
  return true
```

### Additional Information
* 1.5.1 fd5c8ef20845a511ad4e0af8dd8ad4331bf46ffc
* marking high priority because test suite should have sane behavior
* not caused by https://github.com/nim-lang/Nim/pull/16189 since I verified this was the case right before that PR too
* odd behavior noticed by @xflywind in some other PR

**Comment by ringabout** [comment]
Related
```nim
proc greedyOrderedSubsetLines*(lhs, rhs: string): bool =
  ## returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
  let rhs = rhs.strip
  var currentPos = 0
  for line in lhs.strip.splitLines:
    currentPos = rhs.find(line.strip, currentPos)
    if currentPos < 0:
      return false
  return true
```

**Comment by timotheecour** [comment]
indeed, was using an outdated proc before greedyOrderedSubsetLines was introduced; I fixed issue message.
