### ISSUE TITLE
hintProcessing dots are annoying

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#16707]
```nim
static: echo "1234"
import std/sets
static: echo "3456"
```
prints
```
....
1234
......
3456
```

see https://play.nim-lang.org/#ix=2LU4

workaround:
```nim
import std/sets
static: echo "1234"
static: echo "3456"
```

**Comment by timotheecour** [comment]
* you can disable them with `--hint:processing:off`
* you had the exact same issue with the old form without dots, see `XDG_CONFIG_HOME= $nim_120_X c -r -f t11696` which shows
```
Hint: t11696 [Processing]
1234
Hint: sets [Processing]
```
except that you just "need to know" that dots must be disablabled via `--hint:processing:off` which admittedly is not obvious
* most dot hintProcessing interference bugs have been fixed except for 1 case I'm aware of (see https://github.com/nim-lang/Nim/pull/16495, it affects windows when called within `execCmdEx`, refs https://github.com/xflywind/Nim/issues/15)
* erasable log lines would further improve things but PR not finished yet (https://github.com/nim-lang/Nim/pull/14438; it works though)


## proposal
* introduce a flag `--processing:dots|path` to control whether to use dots or (as before) path
* make --processing:path honor listFullPaths
* in future, erasable log lines (https://github.com/nim-lang/Nim/pull/14438) could be controlled via `--processing:erasable`
