### ISSUE TITLE
`genericAssignAux` runtime error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16706]
reduced a bit from a case mentioned in forum /cc @xflywind 
> <adnan338> Hi, could anybody help me understand the error here? https://play.nim-lang.org/#ix=2LRt

### Example
```nim
when true:
  import tables, times
  type
    Shift* = object
      date*: DateTime
  type
    Data* = object
      shifts*: OrderedTable[int, Shift]


  var shifts = initOrderedTable[int, Shift]()
  var data = Data(shifts: shifts)
```

### Current Output
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11694.nim(76) t11694
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(175) genericSeqAssign
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(139) genericAssign
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(100) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(128) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(26) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(22) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(128) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(22) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/assign.nim(125) genericAssignAux
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: invalid object assignment [ObjectAssignmentDefect]

### Expected Output
works

### Additional Information
devel 1.5.1 61fd19c7e6880d77d20be01d25266e4195e631fa
* links: https://forum.nim-lang.org/t/7378#46755

**Comment by ringabout** [comment]
Reduced examples:
```nim
import std/times

type
  Data = object
    shifts*: seq[DateTime]

var shifts = newSeq[DateTime](5)
var data = Data(shifts: shifts)
```

**Comment by timotheecour** [comment]
further reduced without any import:
```nim
when true:
  type
    A = object of RootObj
      a0: string
    B = object
      b0: seq[A]
  var c = newSeq[A](2)
  var d = B(b0: c)
```

=> https://github.com/nim-lang/Nim/pull/16721
