### ISSUE TITLE
regression: compilation 5x slower (33s => 171s for nim_temp c testament)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16703]
https://github.com/nim-lang/Nim/pull/16480 causes some compilations to be 5x slower /cc @juancarlospaco 

### Example
./koch temp
t1: XDG_CONFIG_HOME= bin/nim_temp c testament/testament.nim
t2: XDG_CONFIG_HOME= nim c testament/testament.nim

right before https://github.com/nim-lang/Nim/pull/16480 (1d2e2b5a5b70cc20c79fc3d02a8f3e220b00b3a3)
t1: 33s
t2: 2.6s

right after:
t1: 171s
t2: 6.5s

### Additional Information
still a problem on 61fd19c7e6880d77d20be01d25266e4195e631fa
--stackTraceMsgs + `-d:nimHasStacktraceMsgs` really helped when trying to figure out the culprit:
when I ^C in a seemingly frozen compilation (t1) it showed:
```
compiler/semexprs.nim(2861) semExpr /Users/timothee/git_clone/nim/Nim_prs/lib/pure/mimetypes.nim(1933, 3) nkConstSection
compiler/semstmts.nim(647) semConst
compiler/semexprs.nim(77) semExprWithType
compiler/semexprs.nim(68) semExprCheck
compiler/semexprs.nim(2758) semExpr /Users/timothee/git_clone/nim/Nim_prs/lib/pure/mimetypes.nim(1934, 27) nkCall
compiler/semexprs.nim(1011) semDirectOp
compiler/semexprs.nim(908) afterCallActions
compiler/semexprs.nim(812) evalAtCompileTime
compiler/vm.nim(2208) evalStaticExpr
compiler/vm.nim(2200) evalConstExprAux
compiler/vm.nim(755) rawExecute
compiler/vm.nim(240) writeField
compiler/vm.nim(193) copyValue
compiler/ast.nim(1153) newNode
lib/system/gc.nim(439) newObj
```

which points to `mimetypes.nim(1934, 27)`, leading me to https://github.com/nim-lang/Nim/pull/16480

EDIT: root cause is https://github.com/nim-lang/Nim/issues/16790

**Comment by juancarlospaco** [comment]
Yep, [originally my idea was run-time](https://github.com/nim-lang/Nim/pull/16480/commits/aac8c84a62462695140a750e1f9292c626e216aa#diff-82c841095d0b0273dc49ea2f2d0ffe2d969e9c3fba0ee9218dff87300aee3995R1921) but [it was requested to pre-calc at compile time.](https://github.com/nim-lang/Nim/pull/16480#issuecomment-752630190) :shrug:

**Comment by timotheecour** [comment]
I think we should revert https://github.com/nim-lang/Nim/pull/16480; even if it didn't cause this regression (see also fixable issues in https://github.com/nim-lang/Nim/pull/16480/files#r556247845), there are better ways to get the same effect in a more generic way (see below) without having to add any symbol to `std/mimetypes`; IMO mimesExtMaxLen, mimesMaxLen, mimesLongest is code bloat.

Instead we can do as follows:

```nim
template wrapStatic(s): untyped =
  # needed pending https://github.com/nim-lang/RFCs/issues/276
  (proc(): auto = s)()

# to add to sequtils
template foldlIt*(s, op, ret): untyped =
  block:
    var a {.inject.} = ret
    for b {.inject.} in s:
      a = op
    a

import std/mimetypes
doAssert foldlIt(mimes3, (max(a[0], b[0].len), max(a[1], b[1].len)), (0,0)) == (24, 73)
static:
  doAssert wrapStatic foldlIt(mimes3, (max(a[0], b[0].len), max(a[1], b[1].len)), (0,0)) == (24, 73)
```

and perhaps even add a `maxIt`:

```nim
static:
  doAssert maxIt(mimes3, (a[0].len, b[0].len) == (24, 73)
```

* note that there's still an underlying performance bug in VM here, likely due to the fact that `const` variables gets pasted at each iteration instead of referenced:
```nim
    static:
      # this is very fast (milliseconds)
      for i in 0..<3:
        echo wrapStatic(block:
          let z = mimes3
          foldlIt(z, (max(a[0], b[0].len), max(a[1], b[1].len)), (0,0)))
      # this is very slow (4 seconds per iter)
      for i in 0..<3:
        echo wrapStatic foldlIt(mimes3, (max(a[0], b[0].len), max(a[1], b[1].len)), (0,0))
```

## links
see also https://github.com/nim-lang/Nim/pull/15528 which woud avoid this using ref types

**Comment by Araq** [comment]
Please revert or improve it.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/16711

**Comment by juancarlospaco** [comment]
`Sorry, this pull request couldn’t be reverted. It may have already been reverted.` :shrug: 
GitHub seems to autodetect the other PR.
