### ISSUE TITLE
symbol identity as desired for typed macro rewrite purposes

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#16718]
### Summary

It's harder than it should be to find differences between different symbols in typed AST.

### Description

Signature hashes are insufficient:

```nim
import std/macros

macro foo(x: typed) =
  var x = x[0]
  x.expectKind nnkVarSection
  echo "1 ", signatureHash x[0][0]
  echo "3 ", signatureHash x[0][2]
  echo x[0][0] == x[0][2]

var a = 3
block:
  foo:
    var a = a
```
yields
```
1 __SIJaZ1T8Zi6DvGaJvEyWLw
3 __SIJaZ1T8Zi6DvGaJvEyWLw
false
```

### Alternatives

The best alternative is currently to track scopes, but the language doesn't provide any helpful machinery in the standard library.

### Additional Information

This is blocking the `shadow mission impossible` test in CPS.

**Comment by cooldome** [comment]
can't you just use `==`, imo on sym nodes it works as expected. You will get false.

**Comment by disruptek** [comment]
> can't you just use `==`, imo on sym nodes it works as expected. You will get false.

No.

**Comment by disruptek** [comment]
I updated the example, but we've been using `==` and found it insufficient; I just need a little time to minimize my reproduction.

**Comment by disruptek** [comment]
Thanks to @alaviss, the problem in CPS evaporated with more selective resym.
