### ISSUE TITLE
Template can't find proc

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#16747]
Depending on the way the template called, in one case it works and in another doesn't. Seems like a bug.

### Example

The example requires multiple files. The object `B` uses template `build_type` to build object `A`.

It works if the `buildB()` (commented out) called, but doesn't work if `B.buildB()` called. Complaining it can't find the `build` proc, although it's able to find it if the `buildB()` called.

[playground](https://repl.it/@alexeypetrushin/template-dependency-1#main.nim)

```nim
# main.nim ------------------------------------------
import bobject

# echo buildB()
echo B.buildB()

# bobject.nim ---------------------------------------
import lib, aobject

type B* = tuple[a: A]

proc buildB*(): B = (a: build_type(A))
proc buildB*(_: type[B]): B = (a: build_type(A))

# aobject.nim ---------------------------------------
type A* = tuple[v: int]

proc build*(_: type[A]): A = (0,)

# lib.nim -------------------------------------------
template build_type*[T](_: type[T]): T = T.build()
```

### Current Output
```
/main.nim(5, 7) template/generic instantiation of `buildB` from here
/bobject.nim(6, 45) template/generic instantiation of `build_type` from here
/lib.nim(1, 43) Error: attempting to call undeclared routine: 'build'
exit status 1
```

**Comment by metagn** [comment]
As a workaround, you may be able to use `mixin build` in the template, cannot confirm though

**Comment by al6x** [comment]
@hlaaftana I tried, doesn't work, same error

```Nim
template build_type*[T](_: type[T]): T = 
  mixin build
  T.build()
```

**Comment by metagn** [comment]
Simplified/minimized:

```nim
# a.nim
template templ*(_: int) = # params don't matter as long as not all untyped
  foo()

# b.nim
proc foo*() = echo "yes"

# c.nim
import a, b
proc generic*[T]() = templ(123)

# d.nim
import c
generic[int]()
```

Basically the resolution of `foo` is delayed to generic instantiation time, by which time `b` is no longer in context, and `bind`/`mixin` have no effect because the use of `foo` is not in the generic body.

**Comment by Araq** [comment]
So the solution is to typecheck generic code which is on the horizon but I'm closing the issue for now.
