### ISSUE TITLE
"Error: invalid type: 'void' for var" compile error on AsyncHttpClient.downloadFile (devel branch)

### ISSUE THREAD

**Issue by rominf** [nim-lang/Nim#16741]
Nim from the devel branch doesn't compile simple example with `AsyncHttpClient.downloadFile`.

### Example
```nim
import asyncdispatch
import httpclient

proc test_async {.async.} =
  var client = newAsyncHttpClient()
  await client.downloadFile("http://speedtest-ams2.digitalocean.com/10mb.test", "/tmp/10mb.test")
  
waitFor test_async()
```

### Current Output
```
Hint: used config file '/home/rominf/dev/nim/config/nim.cfg' [Conf]
Hint: used config file '/home/rominf/dev/nim/config/config.nims' [Conf]
................................................
/tmp/test_asynchttpclient_downloadfile_bug.nim(4, 19) template/generic instantiation of `async` from here
/tmp/test_asynchttpclient_downloadfile_bug.nim(6, 15) template/generic instantiation of `downloadFile` from here
/home/rominf/dev/nim/lib/pure/httpclient.nim(1250, 28) template/generic instantiation of `downloadFileEx` from here
/home/rominf/dev/nim/lib/pure/httpclient.nim(1226, 3) Error: invalid type: 'void' for var
```

### Expected Output
[downloaded file]

### Possible Solution
If I change `httpclient` implementation:
```
-proc downloadFile*(client: AsyncHttpClient, url: Uri | string,
+proc downloadFile*(client: AsyncHttpClient, url: string,
```
it works again. 

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-17
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 6c07b0a1f8daf96078ae68b83ead1d48675969d7
active boot switches: -d:release
```

**Comment by ghost** [comment]
Seems to be caused by https://github.com/nim-lang/Nim/pull/15919 - on line 1226 there's a generic proc inside of another generic proc, so the compiler doesn't like that (or maybe it's not allowed at all).

One possible solution is to move `downloadFileEx` out of `downloadFile`, then it starts working again.

**Comment by timotheecour** [comment]
> on line 1226 there's a generic proc inside of another generic proc, so the compiler doesn't like that (or maybe it's not allowed at all).

wrong diagnostic, generic inside generic is ok. I just filed https://github.com/nim-lang/Nim/issues/16786 which shows root cause
