### ISSUE TITLE
Allow object initialisation for Named Tuples

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#16753]
### Summary

It would be convenient to support both tuple and object initialisation for Named Tuples.

```Nim
type Person = tuple[name: string]

echo Person(name: "John")
```

1) Frequently code that uses tuple doesn't need to know how it's implemented - if it's an object or tuple. Say I decided to change Person from object to tuple - and now I have to update tons of old code `Person(name: name)`.

2) It just feels right and uniform.

**Comment by timotheecour** [comment]
it's probably possible as library code via a macro `init`: `Person.init(name: "John")` but it's worth considering each option

**Comment by Araq** [comment]
This is the wrong issue tracker, the one you want to use is here: https://github.com/nim-lang/rfcs

**Comment by al6x** [comment]
Ok, copied it to the RFCs https://github.com/nim-lang/RFCs/issues/321
