### ISSUE TITLE
assign int64 to int on 64 bit system does not compile

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1676]
```
C:\Nimrod\bin>nim -v
Nim Compiler Version 0.10.0 (2014-10-24) [Windows: amd64]
Copyright (c) 2006-2014 by Andreas Rumpf

active boot switches: -d:release

C:\Nimrod\bin>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.1/lto-wrapper.exe
Target: x86_64-w64-mingw32
```

I have code:

```
var 
  i : int = 1
  i64 : int64 = 11

echo sizeof i    # prints 8
echo sizeof i64  # prints 8

i64 = i  # OK
i = i64  #  Error: type mismatch: got (int64) but expected 'int'
```

Is the inability to assign `int64` value to `int` value intentional? They have the same size. At least the documentation should mention this.

This bug/feature also applies to dot-operator resolution and probably also to other situations.

---

There is also inconsistency between `int/int64` and `float/float64`.

I can define dot-operator for both `int` and `int64` and they live happily together, but I can define only one dot-operator for `float` and `float64`. `float` acts like weak typedef, `int` as strong typedef.

**Comment by Araq** [comment]
From the manual: 

>  This integer type is ``int`` if the literal is in the range ``low(i32)..high(i32)``, otherwise it is ``int64``.
