### ISSUE TITLE
`swap` silently broken for objects inside functions (js target)

### ISSUE THREAD

**Issue by salvipeter** [nim-lang/Nim#16771]
In the example below, `foo` should do the same as `swap` (at least that's what the C target does).

### Example
```nim
type A = object
    n: int

proc foo(a, b: var A) =
  swap a, b

var a, b: A
a.n = 42
b.n = 1
doAssert a.n == 42
doAssert b.n == 1
a.swap b
doAssert a.n == 1
doAssert b.n == 42
a.foo b
doAssert a.n == 42
doAssert b.n == 1
```

### Additional Information

The above function compiles (basically) to this JavaScript code:
```js
function foo(a, b) {
    var tmp = a;
    a = b;
    b = tmp;
}
```
However this only swaps the local variables of the function, as JavaScript uses "call by sharing".

In contrast, the C target compiles to
```c
void foo(A *a, A *b) {
    A tmp = *a;
    *a = *b;
    *b = tmp;
}
```
... where the whole struct is swapped.

* This caused a problem in [a pull request for lists](https://github.com/nim-lang/Nim/pull/16536).

```
$ ./nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
git hash: 61fd19c7e6880d77d20be01d25266e4195e631fa
```

**Comment by timotheecour** [comment]
see also workaround mentioned in https://github.com/nim-lang/Nim/pull/16536#discussion_r561377618 which can potentially serve as basis for fixing swap
