### ISSUE TITLE
httpclient contentLength error when missing

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#16770]
# Examples

```nim
import httpclient
let client = newHttpClient()  # OK
let rspons = client.head("http://google.com")  # OK
echo rspons.contentLength  # BUG
```

# Current Output

```nim
$ nim r example.nim
nim-#devel/lib/pure/httpclient.nim(248) contentLength
nim-#devel/lib/pure/strutils.nim(1073) parseInt
Error: unhandled exception: invalid integer:  [ValueError]

$
```

- This is a `parseInt` error.

 
# Expected Output

I see 2 options, if `contentLength` is missing:

- Return `0`.
- Return a better specific error message instead of a `parseInt` error, [`httpclient` has specific errors already](https://nim-lang.github.io/Nim/httpclient.html#HttpRequestError).

# Additional Information

- Repro on any version of Nim, should be kinda easy to fix.
- HTTP Standard says is Ok for `contentLength` to be missing.

# System Information

<details>

```json

{
  "compiled": "2021-01-18T00:58:04",
  "NimVersion": "1.5.1",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2021-01-20T14:42:58-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 401408,
  "getTotalMem": 528384,
  "getOccupiedMem": 96064,
  "countProcessors": 4,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "/home/juan/.cache/nim/nimbug_r",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-#devel/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.12.0 compiled at 2021-01-20 01:09:43\ngit hash: couldn't determine git hash",
  "nimgrep": "1.6.0",
  "nimsuggest": "Nim Compiler Version 1.5.1 [Linux: amd64]\nCompiled at 2021-01-20\nCopyright (c) 2006-2021 by Andreas Rumpf\n\ngit hash: fbdf3f2cebc4d492b458cecfad1f19fdd1375f5a\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.7.4 (2020-10-20 17:30:52) [linux/amd64]",
  "gcc": "gcc (GCC) 10.2.0",
  "clang": "clang version 11.0.1",
  "git": "2.30.0",
  "node": "v15.6.0",
  "python": "3.9.1",
  "ssd": true
}
```

</details>

# Proposed Labels

```csv
httpclient
```

**Comment by dom96** [comment]
Really what this should return is an `Option[int]`, but it seems we missed that boat...

**Comment by juancarlospaco** [comment]
Ok if it returns an `Option[int]` too, can be like a third potential solution.

**Comment by bung87** [comment]
I've investigate exists lib behaviours 

- java  apache http client

>  This is not a problem, the page you requested simply doesn't provide a Content-Length header in its response. As such, the HttpEntity#getContentLength() returns -1.

https://stackoverflow.com/questions/18726892/apache-httpclient-response-content-length-returns-1

- go

https://pkg.go.dev/net/http

> // ContentLength records the length of the associated content.
	// The value -1 indicates that the length is unknown.
	// Values >= 0 indicate that the given number of bytes may
	// be read from Body.
	//
	// For client requests, a value of 0 with a non-nil Body is
	// also treated as unknown.
	ContentLength int64

- .net 

https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebresponse.contentlength?view=net-6.0
> Remarks
     The [ContentLength](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebresponse.contentlength?view=net-6.0) property contains the value of the Content-Length header returned with the response. If the Content-Length header is not set in the response, [ContentLength](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebresponse.contentlength?view=net-6.0) is set to the value -1.

**Comment by ringabout** [comment]
@bung87

Sounds like a good option if it is well documented.

**Comment by dom96** [comment]
Unfortunately changing to return `-1` will be a breaking change, but anything we do here will be a breaking change, even changing the exception type that is raised. Perhaps we shouldn't care in this instance.

Alternatively we can provide a `contentLengthOpt` proc (naming up for debate) which returns an `Option[int]` to allow new code to be safer.

**Comment by bung87** [comment]
I dont think it's a breaking change, at least it does not change the type. I dont think end developer will write code depend on the ValueError Exception.

I can't imaging developer choose between two procs when they just want get http content length .
