### ISSUE TITLE
Fix out parameters

### ISSUE THREAD

**Issue by carpall** [nim-lang/Nim#16804]
When compile using `out` instead of `var` in procedure parameters
```
fatal.nim(49)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```
the code:
```nim
proc matchDigit(self: string, digit: out char): bool =
  for letter in self:
    if isDigit(letter):
      digit = letter
      return true

var digit: char
if matchDigit("", digit):
  echo "matched digit: ", digit
```
it works replacing `out` with `var`

### Summary
Consider adding the out parameters for procedures / fixing / adding the inline out or var declaration

### Description
`out` parameters should be a more compact way to return multiple values, mostly with procs that have to return a bool followed by a value. example:
```nim
proc match(kind: TokenKind, token: out Token): bool =
  let match = current().kind == kind
  if match:
    inc index
  return match

if match(tkOpenPar, out var token): # or `out let token`
  echo "matched `(` at: ", token.pos
# or
var token: Token
if match(tkOpenPar, out token):
  echo "matched `(` at: ", token.pos
```

### Alternatives
I know that, like in python, in nim there is already the way to return multiple values in a proc, but it is not more confortable then 'out' parameters, mostly if the proc is called in a conditional expression, for example
```nim
if matchThis(someKind, out var matched):
  echo "matched: ", matched
```
that's for sure better (more compact, useful) then
```nim
let (match, matched) = matchThis(someKind)
if match:
  echo "matched: ", matched
```
in long expressions or where there is need for a few multiple proc values return, it could result so bad to use

### Additional Information
look at the c# out parameter (useful imho)
https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/keywords/out-parameter-modifier

**Comment by metagn** [comment]
`out T` is not supposed to be in the language, you are supposed to use `var T`. It was removed from the docs in #16378. Previous issue: #16131

**Comment by carpall** [comment]
ok, at the end I succeeded at using `var` instead of `out`, getting so the result I wanted. At this point, assuming that `out` doesn't work, shouldn't better remove it to allow user to use the `out` keyword as identifier, and so maybe using it to build a template to short `(var res: type; res)`?

**Comment by timotheecour** [comment]
> shouldn't better remove it to allow user to use the out keyword as identifier,

it's better to keep `out` as a reserved identifier IMO, we can always make it un-reserved in the future whereas the other way around would be a breaking change if we ever do need it.
Closing for now, feel free to re-open if you have additional arguments
