### ISSUE TITLE
--putenv compiler option not working for LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by elliotwaite** [nim-lang/Nim#16803]
The `--putenv` compiler option doesn't seem to work for setting the `LD_LIBRARY_PATH` environment variable.

### Example
Running the below file (`test.nim`) with `nim r --putenv:LD_LIBRARY_PATH=test_val test.nim`:
```nim
import os
echo "LD_LIBRARY_PATH=" & getEnv("LD_LIBRARY_PATH")
```
... will output:
```
LD_LIBRARY_PATH=
```
... but I expected:
```
LD_LIBRARY_PATH=test_val
```
However, when setting a different environment variable, for example `FOO`, it works as expected. For example, running the below file (`test.nim`) with `nim r --putenv:FOO=test_val test.nim`:
```nim
import os
echo "FOO=" & getEnv("FOO")
```
... will output:
```
FOO=test_val
```
... as expected.

### Additional Information
I am trying to set `LD_LIBRARY_PATH` to a custom path for the run command to resolve the following error I get when trying to use [imgui](https://github.com/nimgl/imgui):
```
dlopen(cimgui.dylib, 2): image not found
could not load: cimgui.dylib
```
If I set `LD_LIBRARY_PATH` using `export LD_LIBRARY_PATH=...`, and then compile the script, and then run the executable all as separate steps, it works. However, I would prefer to be able to set the `LD_LIBRARY_PATH` variable for the run command so that I can compile and run the code all in one step.

```
$ nim -v
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2021-01-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d34d023da1d7af972366c3af58a144b395964b4c
active boot switches: -d:release
```

**Comment by Araq** [comment]
That's an OSX "design choice". We cannot do anything about it.

**Comment by elliotwaite** [comment]
Ah, got it.

For others who come across this issue, it's due to a security feature on macOS called [System Integrity Protection (SIP)](https://en.wikipedia.org/wiki/System_Integrity_Protection). As described in the Wikipedia article:

> System Integrity Protection will also sanitize certain environmental variables when calling system programs when SIP is in effect. For example, SIP will sanitize LD_LIBRARY_PATH and DYLD_LIBRARY_PATH before calling a system program like /bin/bash to avoid code injections into the Bash process.

A simple workaround is to compile and run the code separately, chaining the commands with `&&`:
```
nim c test.nim && LD_LIBRARY_PATH=test_val ./test
```
Another workaround is to [disable SIP](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).
