### ISSUE TITLE
lent field after any operation fails on JS

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#16800]
On the JS backend, if using `lent T` and the body has anything above the implict returned field of an object it errors.

### Example
```nim
type A = object
  b: int
var t = A(b: 100)
proc getValues: lent int =
  echo "hmm" # Removing this makes it compile
  t.b
  # below also compiles if used
  #result = t.b 
echo getValues()
```

### Current Output
```
/tmp/test.nim(4, 1) Error: internal error: ("genAsgn", etyInt, etyBaseIndex)
  proc getValues: lent int =
```

### Expected Output
Compilation without error.

Tested on stable and devel.

**Comment by juancarlospaco** [comment]
I wonder if those should be just NOP and ignored, because for that target wont change the generated code.
