### ISSUE TITLE
Integer casts don't work right in JS mode.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#16808]
I expect for casts to work the same way they do normally to also work in JS mode. Its surprising that int8 and int16 casts don't work but int32 cast does work.

This works with `nim c` but does not work with `nim js`:

```nim
echo cast[int8](cast[uint8](int8(-12)))
echo cast[int16](cast[uint16](int16(-12)))
echo cast[int32](cast[uint32](int32(-12)))  # works...
```

## Using `nim c`
```
-12
-12
-12
```

## Using `nim js`
```
10
10
-12
```

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-01-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

Similar to https://github.com/nim-lang/Nim/issues/16547

**Comment by beef331** [comment]
Probably related to #16806

**Comment by metagn** [comment]
> I expect for casts to work the same way they do normally to also work in JS mode. 

Why would you expect this? I get it in this case, Nim has to specifically add behavior for casting to unsigned integers for JS because there's no other recommended way to do it, but I don't think you should assume JS cast and C cast should be the same in general.

[Here's the relevant proc for JS cast generation](https://github.com/nim-lang/Nim/blob/8241e55023ee32c9ec0b5443723bbe91f4fe875f/compiler/jsgen.nim#L2410), perhaps the "minuend" variable is selected incorrectly for 1 and 2 bytes.

**Comment by treeform** [comment]
"Why would you expect this?" - turning unsigned integers to signed integers is almost universal because most things use two complement mode.  It works for 64bit and 32bit so I expect it to work a for 16bit and 8bit. I expect casts to be non destructive casting to and from should get back same result. Its very hard to write code that does bit fiddling if casts don't work the usual way.

**Comment by treeform** [comment]
I was able to use this code in the `jsgen.nim`:

```nim
  if src.kind == tyInt8 and dest.kind == tyUInt8:
    echo "gen int8 -> uint8"
    r.res = "($1 < 0 ? 0x100 + $1: $1)" % [r.res]
  elif src.kind == tyUInt8 and dest.kind == tyInt8:
    echo "gen uint8 -> int8"
    r.res = "($1 > 128 ? $1 - 0x100: $1)" % [r.res]

  elif src.kind == tyInt16 and dest.kind == tyUInt16:
    echo "gen int16 -> uint16"
    r.res = "($1 < 0 ? 0x10000 + $1: $1)" % [r.res]
  elif src.kind == tyUInt16 and dest.kind == tyInt16:
    echo "gen uint16 -> int16"
    r.res = "($1 > 32767 ? $1 - 0x10000: $1)" % [r.res]

  elif src.kind == tyInt32 and dest.kind == tyUInt32:
    echo "gen int32 -> uint32"
    r.res = "($1 < 0 ? 0x100000000 + $1: $1)" % [r.res]
  elif src.kind == tyUInt32 and dest.kind == tyInt32:
    echo "gen uint -> int32"
    r.res = "($1 >  0x7FFFFFFF ? $1 - 0x100000000: $1)" % [r.res]
```

It works how I expect... but then other things start to break:

```js
(0x100000000 + -12) >> 0
-12
```

```js
(0x100000000 + -12) & 0xffffffff
-12
```

I expect it to be 4294967284 because that fits into the JS int. Very confusing!

**Comment by treeform** [comment]
Maybe all integer computations in nim-js-mode should use BigInt?

```js
Number((BigInt(0x100000000) + BigInt(-12)) & BigInt(0xffffffff))
4294967284
```

**Comment by treeform** [comment]
Hmm another way of casting could be done with ArrayBuffers:

```js
(new Uint8Array(new Int8Array([-12]).buffer))[0]
244
(new Uint16Array(new Int16Array([-12]).buffer))[0]
65524
(new Uint32Array(new Int32Array([-12]).buffer))[0]
4294967284
Number((new BigUint64Array(new BigInt64Array([BigInt(-12)]).buffer))[0])
18446744073709552000
```

**Comment by Araq** [comment]
> "Why would you expect this?" - turning unsigned integers to signed integers is almost universal because most things use two complement mode. It works for 64bit and 32bit so I expect it to work a for 16bit and 8bit. 

Sure, yes, we're in total agreement, don't worry.
