### ISSUE TITLE
`==`(a, b: PNimrodNode): bool uses refrence equality

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#1681]
Whether two nodes are the same reference seems like an implementation detail, it might be better to use value equality.

Should the equality also include the position, or should it just compare the structure of the AST?

**Comment by reactormonk** [comment]
The corresponding code is here: https://github.com/Araq/Nim/blob/devel/compiler/vm.nim#L687-L689

**Comment by Araq** [comment]
Has been fixed.
