### ISSUE TITLE
Tuple unpacking in for loops does not work on js backend

### ISSUE THREAD

**Issue by haxscramper** [nim-lang/Nim#16822]
When using `js` backend with `-d:nodejs` enabled following code errors out with `Cannot read property '0' of null`.

### Example
```nim
var scores: seq[(set[char], int)] = @{{'/'} : 10}

for item in items(scores):
  echo item[0]

for (chars, value) in items(scores):
  echo chars
```

### Current Output

For nim `1.4.2` compiled js code crashes with error. Compiled on `devel` code does not crash, but prints incorrect output (empty set `{}` for loop unpacking)

**1.4.2. output**
```
{'/'}
/mnt/workspace/github/hax-nim/jsback/nimcache/arriter.js:697
            if ((x_1860665[i_1861194] != undefined)) {
                          ^

TypeError: Cannot read property '0' of null
```

**devel output**
```
{'/'}
{}
```

### Expected Output
C backend produces following output:

```
{'/'}
{'/'}
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release -d:danger
```

**Comment by timotheecour** [comment]
related: https://github.com/nim-lang/Nim/issues/14574
