### ISSUE TITLE
rst2html doesn't recognize `:tok:` but it's used in docs

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16858]
### Example
manual.rst contains:
```nim
`.`:tok: `=`:tok:, `:`:tok:, `::`:tok: are not available as general operators; they
are used for other notational purposes.
```

### Current Output
see https://nim-lang.github.io/Nim/manual.html#lexical-analysis-other-tokens
![image](https://user-images.githubusercontent.com/2194784/106223478-568cf880-6196-11eb-95b0-07914391140b.png)

see also:

![image](https://user-images.githubusercontent.com/2194784/106223615-a4a1fc00-6196-11eb-9500-eab8dd250a7c.png)

### Expected Output
either `:tok:` should be recognized and rst2html should show render the tokens as highlighted somehow, or the rst files shouldn't use `:tok:`

### Additional Information
1.5.1 b0f38a63c4916be139f1a289264a5df68bcb4c07

**Comment by ghost** [comment]
Seems like the `:tok:` has been there since the first Nim commit in the repo, rst2html generates a span of a class `tok`:
![image](https://user-images.githubusercontent.com/21169548/109693678-0214d880-7b9b-11eb-8cb2-fbad1051109a.png)

Maybe this should just be a simple CSS fix? But I'm not sure why exactly is `:tok:` needed.

And `:tok:` is only used in the manual.

**Comment by ghost** [comment]
Actually apparently a loooooooong time ago there was CSS for it:
https://github.com/nim-lang/Nim/blob/405b86068e6a3d39970b9129ceec0a9108464b28/config/doctempl.cfg#L129-L133

**Comment by ghost** [comment]
~~And that file was removed in 0.7.0 - https://github.com/nim-lang/Nim/commit/8b2a9401a147bd0b26cd2976ae71a1022fbde8cc#diff-227121f448614b245374ea5594545d2341290eaf49558ae690bc95f660c28998~~ it was renamed

**Comment by timotheecour** [comment]
seems redundant with backticks, should we just remove all instances of `:tok:` ?

**Comment by ghost** [comment]
Final answer: it was removed in https://github.com/nim-lang/Nim/commit/fb93cee95de2300f863057efdf163e2413177c3d :)

**Comment by ghost** [comment]
> seems redundant with backticks, should we just remove all instances of `:tok:` ?

I think so, don't know if ":tok:" was there because of some other reason.

**Comment by timotheecour** [comment]
PR welcome to remove :tok: (since redundant and doesn't work) (and was inconsistently used anyways)

**Comment by Araq** [comment]
RST allows for custom annotations like "tok" and it had special CSS, as you noticed. I don't mind if we remove it but the idea was to highlight it a bit differently.
