### ISSUE TITLE
Suspecting of memory leak in Jester with --gc:arc

### ISSUE THREAD

**Issue by BLeAm** [nim-lang/Nim#16862]
I've tested a simple "Hello World" and compiled it with these parameters:
```
--define:release
--define:danger
--define:useMalloc
--define:useStdLib
--gc:arc
```
then benchmarked it with wrk like this:
```
wrk -t2 -c5 -d20s --timeout 2s http://localhost:9090
```

with all these setups, the server's process consumed 976.2MB of memory,
but when compile it with --gc:orc and the default one everything seems to be okay with a memory usage of 478KB and 4.4MB respectively.

The code is as below:
```nim
import jester

settings:
  port = Port 9090

routes:
  get "/":
    resp "Hello World"

runForever()
```

Tested on:
```shell
$ uname -a
Linux iMachine 4.15.0-134-generic #138-Ubuntu SMP Fri Jan 15 10:52:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-23
Copyright (c) 2006-2021 by Andreas Rumpf

```

**Comment by ghost** [comment]
> but when compile it with --gc:orc and the default one everything seems to be okay with a memory usage of 478KB and 4.4MB respectively.

This is known behavior, async leaks with ARC since it can't collect the cycles that async creates. So you can only use ORC for async code based on asyncdispatch (and jester uses asyncdispatch)

**Comment by Araq** [comment]
This is not a bug, async requires ``--gc:orc``. Note that orc is hard realtime too (for async) and doesn't slow down your code when you use the ``.acyclic`` prama. No bug here.

**Comment by BLeAm** [comment]
@Yardanico @Araq Noted and thank you for the clarification.

**Comment by dom96** [comment]
Maybe we should fail at compile-time when asyncdispatch is compiled with arc?
