### ISSUE TITLE
Allow recursion inside iterators

### ISSUE THREAD

**Issue by tontinton** [nim-lang/Nim#16876]
### Summary
I really want to be able to call an iterator function inside the same iterator.

### Example
```nim
iterator a(num: int): int =
    if num == 1:
        yield num
    else:
        # Throws: "recursion is not supported in iterators"
        for i in a(num - 1):
            yield i
```

### Description
So I don't know where to look as It's my first time looking at the compiler's source code and I would like to fix it myself if possible (you tell me if it's easy or not).
I only need to know why the check exists in the first place.

Inside `semexprs.nim:semOverloadedCallAnalyseEffects:860`:
```nim
if callee.kind == skIterator and callee.id == c.p.owner.id:
  localError(c.config, n.info, errRecursiveDependencyIteratorX % callee.name.s)
  # error correction, prevents endless for loop elimination in transf.
  # See bug #2051:
  result[0] = newSymNode(errorSym(c, n))
```

I tried to delete this check, and the example successfully compiles, but it doesn't really `yield` any result.

### Tests
Instead of deleting `tests/iter/treciter.nim`, I can actually test that recursive iterations work.

**Comment by metagn** [comment]
Use `{.closure.}` iterators. Inline iterators are essentially AST transforms and you cannot infinitely unpack them

**Comment by tontinton** [comment]
I tried adding `{.closure.}` and it still didn't compile for the same reason.

**Comment by metagn** [comment]
This works:

```nim
iterator a(num: int): int {.closure.} =
  if num == 1:
    yield num
  else:
    let recur = a
    for i in recur(num - 1):
      yield i

for i in a(5):
  echo i
# output: 1
```

**Comment by tontinton** [comment]
Yeah it works now, but I think keeping this issue is still justified, as if this example works, it should probably work without assigning to a variable first.
