### ISSUE TITLE
`{.push nodecl.}` should but doesn't apply to importc var/let symbols, can give silently wrong results

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16890]
### Example 1
```nim
{.push nodecl, header: "<copyfile.h>".}
# let COPYFILE_DATA* {.nodecl.}: cint # ok
let COPYFILE_DATA*: cint # bug:  Error: 'let' symbol requires an initialization
{.pop.}
```

### Current Output
Error: 'let' symbol requires an initialization

### Expected Output
works 

### Example 2: silently wrong results with var
```nim
when true:
  {.push nodecl, header: "<copyfile.h>".}
  # var COPYFILE_DATA* {.nodecl.}: cint # ok
  var COPYFILE_DATA*: cint # bug: initializes to 0
  {.pop.}
  doAssert COPYFILE_DATA == 8, $COPYFILE_DATA # fails
```

### Example 2
{.push nodecl.} also doesn't apply for types as shown below (even though we have `{.push nodecl.}` and even though `{.push header: ....}` should imply nodecl

this example requires osx but the problem isn't specific to osx
```nim
# t11796b:
when true:
  {.push nodecl, header: "<copyfile.h>".}
  type
    # copyfile_state_t {.nodecl.} = pointer # workaround: would work
    copyfile_state_t = pointer # bug
    copyfile_flags_t = cint
  proc copyfile_state_alloc*(): copyfile_state_t
  proc c_copyfile*(src, dst: cstring,  state: copyfile_state_t, flags: copyfile_flags_t): cint {.importc: "copyfile".}
  {.pop.}

# main.nim:
impor t11796b
if false:
  let state = copyfile_state_alloc()
  discard c_copyfile("", "",  state, 0)
```

nim r -b:cpp -d:case5 $timn_D/tests/nim/all/t11796.nim
```
/Users/timothee/git_clone/nim/timn/build/nimcache/@mt11796.nim.cpp:130:13: error: no matching function for call to 'copyfile'
                int T5_ = copyfile("", "", state__WkrHkIAbpCAcQ7Yk35nGFw, ((int) 0));
                          ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/copyfile.h:55:5: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to
      'copyfile_state_t' (aka '_copyfile_state *') for 3rd argument
int copyfile(const char *from, const char *to, copyfile_state_t state, copyfile_flags_t flags);
    ^
```

### Example 3
the docs of nodecl should be improved a bit IMO, eg:
`Note: This will not work for the LLVM backend.` => remove this, that backend was removed (and there'd be a way around this anyways)

they should also illustrate better when it's needed, and also explain that you need 2 files to see the need for header and nodecl, eg main.nim that imports fun.nim which contains c declarations (ohterwise cgen errors may be masked).

### Additional Information
1.5.1 eef2948ec2725d69358ab647a25bfa4ac675ed91
importc let without initialization was enabled since #14258
that specific example requires osx but the general bug is the same

**Comment by veksha** [comment]
total mess:

```nim
proc getint*():cint =
    
    var i {.nodecl}: cint
    {.emit:"int i; i = 14;"}
    return i

echo getint()

```
>14



```nim
proc getint*():cint =
    
    {.emit:"int i; i = 14;"}
    var i {.nodecl}: cint
    return i

echo getint()
```

>0


```nim
proc getint*():cint =
    
    var i {.nodecl}: cint
    {.emit:"int i; i = 14;"}
    result = i

echo getint()
```

>error: redeclaration of 'i'




```nim
proc getint*():cint =
    
    let i {.nodecl}: cint
    {.emit:"int i; i = 14;"}
    return i

echo getint()
```

>Error: 'let' symbol requires an initialization



```nim
proc getint*():cint =
    
    let i {.importc, nodecl}: cint
    {.emit:"int i; i = 14;"}
    return i

echo getint()
```

>14

**Comment by ghost** [comment]
@veksha your examples are all wrong because you don't actually backtick quote i inside of emit. If you don't do that Nim will not understand that you want it to be assigned to your Nim `i` variable.
EDIT: Or use arrays with string literals and Nim symbols, since that seems to be a more up-to-date way - https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-emit-pragma

**Comment by veksha** [comment]
@Yardanico no. i don't need to pass nim variables inside c code. i know how to do that. i want to connect existing c-world variable to nim-world variable. that is why nodecl exist. but it doesn't work correctly in all cases.

**Comment by ghost** [comment]
@veksha then you have to use `importc`, `nodecl` by itself is NOT enough. Even the manual shows importc together with nodecl. Can you show the part in the manual where it shows that `nodecl` alone is enough to use C variables in Nim?

Your last example works fine.

**Comment by Araq** [comment]
It does work and your issue has nothing to do with "push".
