### ISSUE TITLE
strictFuncs + views: cannot import `pegs`

### ISSUE THREAD

**Issue by ee7** [nim-lang/Nim#16892]
### Example
Compile the below with `nim c --experimental:strictFuncs --experimental:views`
```Nim
import pegs
```

### Current Output
```
/nim/lib/pure/pegs.nim(344, 6) Error: 'nonterminal' can have side effects
```

### Expected Output
No error.

### Additional Information
Note that the error does not occur with just `nim c --experimental:strictFuncs`

To "solve" this issue by removing instances of `noSideEffect`, the minimal number of `noSideEffect` that must be removed is shown in this commit: https://github.com/ee7/Nim/commit/23945aa2522ac618564f0c911519663f533549dc. I assume that this approach isn't what we want, but tell me otherwise and I'll make the PR for it. 

Apart than `critbits` (see https://github.com/nim-lang/Nim/issues/16873) and `pegs`, it looks like every stdlib module can be imported when compiling with
```
--experimental:strictFuncs --experimental:views
```
See https://github.com/nim-lang/Nim/pull/16878.

### Nim version
This issue occurs in:
- the latest devel commit (https://github.com/nim-lang/Nim/commit/c05d1aab13dab0cc5e8337cb032dc580d2379d68)
- Nim 1.4.2
- Nim 1.4.0

**Comment by timotheecour** [comment]
@ee7 how about:
* close this issue and merge it into https://github.com/nim-lang/Nim/issues/16873, and rename that issue to `strictFuncs: cannot import X`; it's the same underlying reason, no need to open N issues for that; it'll also make tracking easier (use check boxes)
* ditto with any similar issue created by you or others

**Comment by ee7** [comment]
@timotheecour I see your argument, but at this moment I think it's cleanest to keep the issues separate.

The issues differ in at least these ways:
- The `critbits` issue is a regression since the latest stable release, and so might be resolved more quickly. But `import pegs` has never worked with strictFuncs + views; the `critbits` issue can be tagged with "regression", but the `pegs` one can't.
- The `critbits` issue also is easier to "fix" via the approach of `func` -> `proc`, or removing `noSideEffect`.  
- The `pegs` issue requires `--experimental:views`.


> it'll also make tracking easier (use check boxes)

I was guessing that the `critbits` issue would be resolved more quickly - I could argue that it's better for a commit to close an issue than to tick a box.


> no need to open N issues for that

As far as I can tell, there are only two stdlib modules affected - I hope that N is exactly 2. Furthermore, we can guarantee that N does not increase (due to the current stdlib modules at least) if something like https://github.com/nim-lang/Nim/pull/16878 is merged.

However, if we find any more "cannot import X with strictFuncs/views" then I'm happy to do as you say and have one combined issue.

Does that work for you?

Edit: https://github.com/nim-lang/Nim/pull/16877 was merged, which closed https://github.com/nim-lang/Nim/issues/16873. If we find any new "cannot import X with strictFuncs/views" problems then I'm fine with tracking them in this issue.

**Comment by nc-x** [comment]
It can now be reproduced without enabling views - see https://github.com/nim-lang/Nim/issues/18057
The issue here is that with strictFuncs, if we are calling a function inside a noSideEffect function, then that called function must also be marked as noSideEffect. I am not sure whether this is expected behaviour or not.

**Comment by juancarlospaco** [comment]
This still repro as of today. :(
