### ISSUE TITLE
./koch docs fails in a directory with spaces

### ISSUE THREAD

**Issue by n5m** [nim-lang/Nim#16909]
Running `./koch docs` in a directory with a space fails to generate `*.html` files from `.nim` source code.

### Example
```bash
mkdir 'spaced name'
cd 'spaced name'
git clone --depth 1 https://github.com/nim-lang/Nim
cd Nim
./build_all.sh
./koch docs
```
Fails to create `web/upload/1.5.1/system.html` in the `Nim/` directory. Running the same commands without a space in the full path works, however.

**Comment by timotheecour** [comment]
@n5m please consider a PR by adding a `quoteShell` or `quoteShellCommand` in the appropriate place
