### ISSUE TITLE
Possible bug in nativesockets.nim on JS

### ISSUE THREAD

**Issue by thisago** [nim-lang/Nim#16930]
When using this lib with C/Cpp/ObjC it runs well:

### Example
```nim
import httpclient

when isMainModule:
  let
    client = newHttpClient()
    response = client.get("http://example.com/")

  echo response.status
```

### Command
```
nim cpp -d:danger -d:release ./main.nim
```

### Current Output
```
200 OK
```
But when I run on JS, it gives a error

### Command
```
nim js -d:danger -d:release ./main.nim
```

### Current Output
```
Hint: used config file '/data/files/config/home/.choosenim/toolchains/nim-1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/data/files/config/home/.choosenim/toolchains/nim-1.4.2/config/config.nims' [Conf]
.....................
/data/files/config/home/.choosenim/toolchains/nim-1.4.2/lib/pure/nativesockets.nim(346, 20) Error: undeclared identifier: 'cstringArrayToSeq'
```

I haven't found the `cstringArrayToSeq` procedure anywhere... It is `magic`?

### Additional Information

* This issue is blocking me to create a Google translate API lib because I will need it working on JS too

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

**Comment by metagn** [comment]
`nativesockets`, therefore `httpclient` etc, are not supposed to work on the JS backend, since they are "native" sockets and bind to native code. On JS, you should wrap `fetch` or AJAX, there is [this PR](https://github.com/nim-lang/Nim/pull/12531) for fetch and [this library](https://github.com/stisa/ajax) for ajax.

**Comment by thisago** [comment]
Thanks, I will close this issue

**Comment by juancarlospaco** [comment]
I am working on JS libs so that once they all merged, an "httpclient for the browser" on stdlib would be possible.
