### ISSUE TITLE
compiler flag --clib prefixes unnecessary path component to library name

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#16937]
Currently the compiler flag `--clib:...` prefixes the project src path to the specified C library name.

### Example
I have created an example project here: https://github.com/samdmarshall/nim-compiler-clib-bug

The relevant files are the `nim.cfg`:
```cfg
--clibdir:"/brew/lib"
--cincludes:"/brew/include"
--clib:"notmuch"
```
generates the following command:
```log
/brew/bin/ld: cannot find -l/home/demi/Desktop/nim-compiler-clib-bug/src/notmuch
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang   -o /home/demi/Desktop/nim-compiler-clib-bug/main  /home/demi/.cache/nim/main_d/stdlib_assertions.nim.c.o /home/demi/.cache/nim/main_d/stdlib_io.nim.c.o /home/demi/.cache/nim/main_d/stdlib_system.nim.c.o /home/demi/.cache/nim/main_d/stdlib_parseutils.nim.c.o /home/demi/.cache/nim/main_d/stdlib_strutils.nim.c.o /home/demi/.cache/nim/main_d/stdlib_times.nim.c.o /home/demi/.cache/nim/main_d/stdlib_os.nim.c.o /home/demi/.cache/nim/main_d/stdlib_strformat.nim.c.o /home/demi/.cache/nim/main_d/@mmain.nim.c.o  -lm -lrt   -l/home/demi/Desktop/nim-compiler-clib-bug/src/notmuch -L/brew/lib -ldl'
```

### Current Output
at the end of this command the flags are ordered as such:
```
-l/home/demi/Desktop/nim-compiler-clib-bug/src/notmuch
-L/brew/lib
```

### Expected Output
```
-lnotmuch
-L/brew/lib
```

### Possible Solution

currently, using `--passL: "-lnotmuch"` flag instead of the preferred `--clib:"notmuch"` flag allows for the correct flags to be passed to the linker.

### Additional Information

Nim Compiler:
```
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

**Comment by KamijoToma** [comment]
I met the same question on my project, and I finally build a modified compiler which seems to be worked properly.

Simply, I changed [this line](https://github.com/nim-lang/Nim/blob/6319b00ef7f93fa8d7d44c981f850262d8e0ed6a/compiler/commands.nim#L793) to:
`      conf.cLinkedLibs.add arg`
and it seems to link the library without an extra path.

**Comment by demotomohiro** [comment]
@KamijoToma 

> I met the same question on my project, and I finally build a modified compiler which seems to be worked properly.
> 
> Simply, I changed [this line](https://github.com/nim-lang/Nim/blob/6319b00ef7f93fa8d7d44c981f850262d8e0ed6a/compiler/commands.nim#L793) to: ` conf.cLinkedLibs.add arg` and it seems to link the library without an extra path.

Thank you! That fixes this issue.
I have sent PR https://github.com/nim-lang/Nim/pull/19754 to fix this.
