### ISSUE TITLE
array initialisation literals for distinct type

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1695]
This is small feature request, follow-up to the dismissed #1682

```
type  iint = distinct int
var a : array[0..2, iint]
a = [ 1, 2, 3]                     # doesn't compile ... well ... OK
a = [ iint(1), 2, 3]               # still doesn't compile 
a = [iint(1), iint(2), iint(3)]    # only this compiles
```

Is it _really_ needed to cast every single item here? Couldn't the compiler be just a little bit smarter and deduce the type for the second and further items?

**Comment by data-man** [comment]
Now we have sequtils.mapLiterals
Can be closed?
