### ISSUE TITLE
-r option for JS does not imply -d:nodejs

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#16985]
Passing `-r` or `--run` to a `nim js` command is supposed to run the JS output through node.js, but it does not define `nodejs` for the code that is going to be ran. Tested on some recent devel version; I thought this was already implemented.

This causes errors with `std/exitprocs`, where you need `nodejs` defined to set the program result. Maybe `nodejs` should be assumed by default in cases like these

**Comment by timotheecour** [comment]
I agree.

In future we may also want to support `-d:nimbrowser` or `--browser` which would then override this (ie unset -d:nodejs when -r or --run is passed), refs https://github.com/timotheecour/Nim/issues/197 and https://github.com/timotheecour/Nim/issues/165

> This causes errors with std/exitprocs, where you need nodejs defined to set the program result

there are ways to fix with js without nodejs, refs https://github.com/nim-lang/Nim/issues/16074, but I agree with the rest

## note
`nim doc -b:js -r main` should not imply -d:nodejs (current behavior correct)

**Comment by dom96** [comment]
IMO `-r` for JS should by default open the browser with HTML that loads the JS. Node.js isn't the primary target for this backend and just there to aid testing.

**Comment by metagn** [comment]
> IMO `-r` for JS should by default open the browser with HTML that loads the JS. Node.js isn't the primary target for this backend and just there to aid testing.

Maybe we can have a ``--html`` or whatever switch which opens the given HTML file when `-r` is passed, that way node is known not to be used and it would `-d:browser` instead.
