### ISSUE TITLE
Windows: math functions buggy edge cases

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17017]
`math.sqrt` does not return `NaN` on Windows for negative arguments and instead returns the argument.

### Possible Solution
This seems to be a [MinGW-w64 bug](https://sourceforge.net/p/mingw-w64/bugs/567/) that is fixed by now, so updating the MinGW-w64 version should fix this.

### Additional Information
I actually only tested this via the CI, see https://github.com/konsumlamm/Nim/runs/1883950662.

---

EDIT: Other `math` functions also have edge cases.
* [x] sqrt
* [x] gamma
* [x] c_frexp2

**Comment by ringabout** [comment]
it works on my win10 machine
```nim
import std/math

echo sqrt(-12.0) # nan
```

```
Thread model: posix
gcc version 8.1.0 (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project)
```

**Comment by timotheecour** [comment]
mildly related bug affecting math on windows reported by @xflywind in https://github.com/nim-lang/Nim/pull/16725#discussion_r568301726

```nim
func c_frexp2(x: cdouble, exponent: var cint): cdouble {.
    importc: "frexp", header: "<math.h>".}

var x = cdouble(-0.0)
var exponent: cint
echo c_frexp2(x, exponent)
```
> prints 0.0 in my Win10 gcc, but works in linux(-0.0).


> It seems to have some bugs with frexp for special value handling(0.0, -0.0, NaN, -Inf, Inf) in my win10 machine.

> I even write a test.c program, it seems there is something wrong with frexp c99.


it would be good to check other edge cases, eg `log(-1.0, math.E)`

**Comment by konsumlamm** [comment]
Another possibly related bug I found: `gamma(-1.0)` doesn't return `NaN` either on windows (for CI).

**Comment by timotheecour** [comment]
@konsumlamm how about broadening this issue title to:
`math procs buggy on windows for edge case numbers`  ?

and then this issue can list each proc affected along with versions of windows that have the bug.

how to fix this is a separate issue, but could involve at very least a doc comment specifying this

**Comment by rockcavera** [comment]
These errors are more related to the backend than to Nim himself. Here the three cases pointed out as bugs do not occur.

Example:
```nim
import math

func c_frexp2(x: cdouble, exponent: var cint): cdouble {.
    importc: "frexp", header: "<math.h>".}

var x = cdouble(-0.0)
var exponent: cint

echo c_frexp2(x, exponent)
echo sqrt(-1.0)
echo gamma(-1.0)
```

Output:
```
-0.0
nan
nan
```

Versions:
```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-02-11
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f3c39bf2d99d964c5b8fd88c3b8940b0cf5c1b9b
active boot switches: -d:release

Windows 10

Mingw64 GCC 10.2.0
```

**Comment by konsumlamm** [comment]
> These errors are more related to the backend than to Nim itself.

Well, they do occur in the CI, so it's still relevant.

**Comment by timotheecour** [comment]
refs https://github.com/nim-lang/Nim/pull/17375#issuecomment-810483656 
> The MingW we ship with Nim has been updated. The next release will have it.

given that azure-pipelines.yml contains
`curl -L https://nim-lang.org/download/mingw64.7z -o dist/mingw64.7z`

we should check again whether CI is still affected by those bugs and if not add tests and close this
