### ISSUE TITLE
Reserved primitive types shadowed breaks compilation

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#17013]
This breaks compilation:

```nim
var string = "string"  # Comment out this line then compiles Ok.
var z: string = "This works"
echo string("This fails")
echo string"This fails"
```

```console
$ nim c example.nim
example.nim(1, 9) Error: attempting to call routine: 'string'
  found 'string' of kind 'var'
  found 'system.string [declared in nim/lib/system.nim(34, 3)]' of kind 'type'

$
```

Same with `float`, `bool`, `int`, and all primitive types. 
Found teaching Nim to new people, new users sometimes make this mistake kinda frequently.

- Compiler should emit an Error or at least a Warning for names that overwrite reserved builtin names.
- Maybe is useful for FFI purposes (?), then can be a Warning.

**Comment by Araq** [comment]
> Compiler should emit an Error or at least a Warning for names that overwrite reserved builtin names.

No, that's not how the language was defined and the error messages are acceptable.
