### ISSUE TITLE
[docgen] export causes duplicate doc generation

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17016]
If `export` is used on a public binding (for example a proc), the documentation for it is generated twice.

### Example
```nim
proc test*() = discard

export test
```

### Current Output
![](https://i.imgur.com/arzrYE6.png)

### Expected Output
![](https://i.imgur.com/Z1L9vEg.png)

### Additional Information
This bug appears in the `random` module (see https://github.com/nim-lang/Nim/pull/16953#discussion_r574811739), where the documentation for `initRand(int64)` is generated twice.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-08
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c548f97241c9f0da8f9442c07b99dd9d6adf225a
```

**Comment by timotheecour** [comment]
for motivation (since some would object provided example is contrived), a use case is when you already have an exported overload, and then conditionally export another overload.

relevant past PR: https://github.com/nim-lang/Nim/pull/13123

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23074
