### ISSUE TITLE
callWith macro for proc arguments in statement list

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#17029]
EDIT: The name started with `callWith`, but I think `spreadArgs` or `spread` is better. If anyone is going to PR this with the code below, please decide which name is best, don't directly go with `callWith`.

### Summary
There should be a new `sugar.callWith` (will take alternative name and module suggestions) macro which spreads a given statement list into call arguments, for better structuring arguments and named arguments passed to routines.

### Description
```nim
import macros

macro callWith*(call, args): untyped =
  result = if call.kind in {nnkCall, nnkCommand}: copy(call) else: newCall(call)
  if args.kind == nnkStmtList:
    for arg in args:
      if arg.kind == nnkAsgn:
        result.add(newTree(nnkExprEqExpr, arg[0], arg[1]))
      else:
        result.add(arg)
  else:
    result.add(args)

proc foo(a, b, c: int) =
  echo "a: ", a
  echo "b: ", b
  echo "c: ", c

foo.callWith:
  1
  c = 3
  b = 2

callWith foo(1): # limitation: can't call with dot syntax for calls
  c = 3
  b = 2
```

This is best when you have a lot of arguments or your arguments can be really long.

```nim
let client = newHttpClient(
  userAgent = existingUserAgent & " SomeUserAgent 1.0",
  context = newContext(protVersion = protTLSv1,
    verifyMode = CVerifyNone),
  maxRedirects = 3)

# becomes

let client = newHttpClient.callWith:
  userAgent = existingUserAgent & " SomeUserAgent 1.0"
  context = newContext.callWith:
    protVersion = protTLSv1
    verifyMode = CVerifyNone
  maxRedirects = 3
```

### Alternatives
Don't put this in standard library. It's so small though, I think it's worth doing it.

Name of it can also be different (this was the best I could come up with), module could change too but I don't see any real alternative. One alternative I can think of for the name is `...`, but it's too common of an operator name/seems unrelated or it may be too restrictive because it's an operator.

```nim
... foo:
  1
  c = 3
  b = 2

... foo(1):
  c = 3
  b = 2
``` 

I didn't PR this directly because I was unsure of the name and where it would go.

EDIT: Maybe `spread` would be good.

```nim
spread foo:
  1
  c = 3
  b = 2

foo.spread:
  1
  c = 3
  b = 2

spread foo(1):
  c = 3
  b = 2
```

### Additional Information
There was some issue or RFC where someone asked for this but as a Nim feature. I can't find it now.

**Comment by haoyu234** [comment]
naming is so difficult, just ignore it 😂

```nim
proc​ ​foo​(a, b, c: ​int​) ​=​
  ​echo​ ​"a: "​, a
  ​echo​ ​"b: "​, b
  ​echo​ ​"c: "​, c

foo:
  ​a = 1
  ​b = 2
  ​c = 3
```

**Comment by metagn** [comment]
was also https://github.com/nim-lang/RFCs/issues/277, implemented in https://github.com/metagn/spread
