### ISSUE TITLE
Export sslHandle in net and asyncnet

### ISSUE THREAD

**Issue by ardek66** [nim-lang/Nim#17021]
### Summary

Export the `sslHandle` field of sockets in `net` and `asyncnet` respectively,
just like `SslContext` exports `context`.

### Description
Currently, the only way of using libssl procedures that take an ssl handle as a parameter(be them from `openssl` or imported through FFI separately) is by either rewritting the socket wrapping procedure or `include`-ing `net` or `asyncnet`, both of which being quite overkill for achieving simple tasks, even calling simple procedures from the stdlib `openssl` such as [SSL_get_error](https://nim-lang.org/docs/openssl.html#SSL_get_error%2CSslPtr%2Ccint) or [SSL_get_peer_certificate](https://nim-lang.org/docs/openssl.html#SSL_get_peer_certificate%2CSslCtx).

The `SslContext` itself allows us to access the low-level `context`, why shouldn't `Socket`?

### Alternatives

One could add the needed procedures to the nim openssl, but then comes the problem if it is actually needed, or if it keeps
compatibility with the rest, making development of both `openssl` and the program itself harder.

### Additional Information

This problem can be seen discussed [here](https://forum.nim-lang.org/t/7484)

**Comment by ringabout** [comment]
@ardek66 

make a PR?
