### ISSUE TITLE
PackedSet name is misleading: is sparse

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#17057]
So I just discovered packedsets following a discussion with @haxscramper.
- https://nim-lang.github.io/Nim/packedsets.html
- https://github.com/nim-lang/Nim/blob/0a9a90d/lib/std/packedsets.nim

The packedsets name is misleading as those are

>  implemented as a sparse bit set.

Something sparse cannot be packed.

In particular, people might be looking for an actual packed bitset that is a [succinct data structure](https://en.wikipedia.org/wiki/Succinct_data_structure) and would for example pack 16 3-bit elements in 6 bytes (16*3 / 8) which the packedset name suggest.

Side-note, I have implemented the logic for succinct data structures [here](https://github.com/mratsim/constantine/blob/8a7c35af598d3a1d08c7b31c85234853d849eea7/constantine/elliptic/ec_endomorphism_accel.nim#L148-L181) though it's missing a way to toggle a 1 bit to 0 at a specific location. It can be easily adapted to any `BitSize`, `Shift` and `WordMask` depends on whether we use byte or uint64 or anything in between to store the values.

```Nim
const
  BitSize   = 1
  Shift     = 3                    # log2(sizeof(byte) * 8) - Find the word to read/write
  WordMask  = sizeof(byte) * 8 - 1 #                        - In the word, shift to the offset to read/write
  DigitMask = 1 shl BitSize - 1    # Digits take 1-bit      - Once at location, isolate bits to read/write

proc `[]`(recoding: Recoded,
          digitIdx: int): uint8 {.inline.}=
  ## 0 <= digitIdx < LengthInDigits
  ## returns digit ∈ {0, 1}
  const len = Recoded.LengthInDigits
  # assert digitIdx * BitSize < len

  let slot = distinctBase(recoding)[
    (len-1 - digitIdx) shr Shift
  ]
  let recoded = slot shr (BitSize*(digitIdx and WordMask)) and DigitMask
  return recoded

proc `[]=`(recoding: var Recoded,
           digitIdx: int, value: uint8) {.inline.}=
  ## 0 <= digitIdx < LengthInDigits
  ## returns digit ∈ {0, 1}
  ## This is write-once, requires zero-init
  ## This works in BigEndian mode
  const len = Recoded.LengthInDigits
  # assert digitIdx * BitSize < Recoded.LengthInDigits

  let slot = distinctBase(recoding)[
    (len-1 - digitIdx) shr Shift
  ].addr

  let shifted = byte((value and DigitMask) shl (BitSize*(digitIdx and WordMask)))
  slot[] = slot[] or shifted
```

**Comment by Araq** [comment]
"sparse" is a property of your input data, not of the involved data structure and it would be even more misleading for the current implementation, ymmv. There was a discussion about the name and `PackedSet` was the winner.
