### ISSUE TITLE
JS bool set invalid output with BSD

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#17093]
Akin to #17076 there is an issue with `set[bool]`  on bsd in js.
[CI error](https://builds.sr.ht/~araq/job/429388)
### Example
```nim
import macros
macro enmRange(enm: typed): untyped = result = newNimNode(nnkCurly).add(enm.getType[1][1..^1])

proc fullSet*(T: typedesc): auto {.inline.} =
  when T is Ordinal:
    {T.low..T.high}
  else: # Hole filled enum
    enmRange(T)
assert fullSet(bool) == {true, false}
```

### Current Output
Program fails at runtime for whatever reason.
```
`fullSet(bool) == {true, false}`  [AssertionDefect]
```

**Comment by timotheecour** [comment]
* for whoever has a freebsd/openbsd VM, please minimize; i'm assuming this would also fail:
```nim
proc fullSet*(T: typedesc): auto {.inline.} =
  {T.low..T.high}
doAssert fullSet(bool) == {true, false}
```
and possibly simpler even
* please also look at:
```nim
import std/jsconsole
proc fullSet*(T: typedesc): auto {.inline.} =
  {T.low..T.high}
template fn(a) =
  echo a
  console.log a
fn fullSet(bool)
fn {true, false}
```
(/cc @euantorano )

**Comment by euantorano** [comment]
Will give this a go tomorrow. The most common causes for errors like this are different versions of node. It seems the CI run used node 15.8.0.

**Comment by timotheecour** [comment]
I finally found root cause: see https://github.com/nim-lang/Nim/issues/17097 (@euantorano please read that issue since it may affect you in other PR's)

**Comment by euantorano** [comment]
> I finally found root cause: see #17097 (@euantorano please read that issue since it may affect you in other PR's)

Yeah, I just saw your email to lists.sr.ht and was reading through it. I wonder if we can fix it in the CI script if the actual platform can’t/won’t change.
