### ISSUE TITLE
strformat and strutils.repeat() 

### ISSUE THREAD

**Issue by zetashift** [nim-lang/Nim#17112]
When using https://nim-lang.org/docs/strutils.html#repeat%2Cstring%2CNatural in a formatted string using `strformat` I can't call repeat directly with the string, I have to create an intermediate variable first, see playground: https://play.nim-lang.org/#ix=2Q0P/

### Example
```nim
echo &"{repeat("foo", 5)}"
echo fmt"{repeat("foo", 5)}"
```

### Current Output
```
Error: undeclared identifier: 'foo'
```

### Expected Output
```
foofoofoofoofoo
```
### Additional information

Is it not possible to use `strings` directly in strformat? 'Cause it works fine like this:
```nim
let foo = "foo"
echo &"{foo.repeat(5)}"
```

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
-------------------------------------------------------------
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c05d1aab13dab0cc5e8337cb032dc580d2379d68
active boot switches: -d:release
```

**Comment by SolitudeSF** [comment]
just escape the quotes? `echo &"{repeat(\"foo\", 5)}"`

**Comment by zetashift** [comment]
Ah alright I'll use that! I thought everything within ` { }` did not need to be escaped.
