### ISSUE TITLE
Strange results when echoing the memory address of some pointers 

### ISSUE THREAD

**Issue by jovial** [nim-lang/Nim#1711]
Trying to print the memory address of some pointers yields strange results. Yet it is fine if I assign the result of the cast to a variable and then print the result. 

```nimrod
type CArray*{.unchecked.}[T] = array[0..0, T]

proc main =
  var a = cast[CArray[ptr int]](alloc0(4 * sizeof(ptr int)))
  for i in 0..3:
    a[i] = cast[ptr int](alloc0(sizeof(int)))
    a[i][] = i
    
  let before = cast[int](a[2])
  echo cast[int](a[2])

  #let after = cast[int](a[2])
  echo cast[int](a[2])
  #assert before == after

main()
```

example output

```
140209307041920
0
```

Think this was leading to some other issues due to memory corruption.

**Comment by jangko** [comment]
no longer a valid issue for nim 0.12.0

**Comment by reactormonk** [comment]
What would the expected output be?

**Comment by jangko** [comment]
@reactormonk: both of the echos output the same value

**Comment by reactormonk** [comment]
Works with `-d:release`, but not without. Close it?

**Comment by jangko** [comment]
need more investigation, my system:
windows 7-32bit, minGW/GCC 4.8.1, both mode with/without -:release, don't have problem
don't know about other system/platform, need more feedback from other users

**Comment by dom96** [comment]
Works with both ``-d:release`` and without for me (Mac OS X/clang/Nim 0.12.1). Closing.
