### ISSUE TITLE
SIGWINCH in posix

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17125]
### Summary

As far as I know SIGWINCH is a posix signal, which is not included in the posix library. (I tried looking for SIGWINCH in issues,
but didn't see anyone talk about it, so I don't know if there is a particular reason to exclude it.)

source: I looked through the docs and tried `import posix` then `echo SIGWINCH`.

Note: I went through the posix docs and signals 16, 28 and 30 seem to be missing (SIGSTKFLT, SIGWINCH and SIGPWR) from the 0-31 signals

**Comment by ringabout** [comment]
posix is not complete wrapper. PR is welcome.

And
> the signal SIGWINCH is not specified in the POSIX specification.

https://github.com/hut/lscd/issues/2

**Comment by ghost** [comment]
The hut/lscd#2 is quoting a wikipedia article in 2014, the same article now lists SIGWINCH in the specification.
In fact, the talk page https://en.wikipedia.org/wiki/Talk:Signal_(IPC) references https://austingroupbugs.net/view.php?id=1151 and states that it is about to be included/has been included.

I've looked for the 2017 published standard and SIGWINCH does not seem to be in it in the 2017 version.

edit: I rechecked and the wrapper's signal definitions seem to be complete against the 2017 standard. closing i guess.

**Comment by viega** [comment]
This should be reopened; if it was fixed, there appears to be a regression.

```
👑 INim 0.6.1
Nim Compiler Version 2.0.0 [MacOSX: amd64] at /Users/viega/.nimble/bin/nim
nim> import posix
nim> echo SIGWINCH
Error: undeclared identifier: 'SIGWINCH'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 3): 'SIGINT'
 (3, 3): 'SigInfo'

```
