### ISSUE TITLE
`nre` has quadratic behavior, unlike `re` and `pkg/regex` (ie can be orders of magnitude slower)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17129]
I just hit this bug while working on https://github.com/nim-lang/Nim/pull/17127 and noticing very slow search/replace behavior on some inputs.

I've reduced it as follows:

### Example
this test case generates strings of the form:
```
foo abcd
bar
bar
bar
...
```
with 2^n repetitions of bar it iteration n, and compares performance of re,nre,pkg/regex for `replace` with a pattern `abcd`

```nim
when true:
  import std/[times,strutils]
  when defined case3a:
    import std/re
  elif defined case3b:
    import std/nre
  elif defined case3c:
    import pkg/regex
  else:
    static: doAssert false
  proc main()=
    let reg = re"abcd" # quadratic behavior
    # let reg = re"\babcd\b" # no quadratic behavior
    template fn(s) =
      let s2 = s
      let t = epochTime()
      let output = s2.replace(reg, "blah")
      let t2 = epochTime()
      echo (s2.len, t2-t)

    let s1 = "foo abcd"
    fn(s1)
    let n = 18
    for i in 0..<n:
      let si = "bar\n".repeat(1 shl i)
      echo "\n" & $(i, si.len)
      fn(si)
      fn(s1 & si)
  main()
```

nim r -d:danger -d:case3a main (re)
nim r -d:danger -d:case3b main (nre)
nim r -d:danger -d:case3c main (pkg/regex)

### Current Output
-d:case3b is quadratic running time

each iteration doubles the input size; for the last iteration:
-d:case3a takes ~ 0.0009 seconds
-d:case3c takes ~ 0.0005 seconds
-d:case3b takes 108 seconds, ~ 500K times slower
if you look at each iteration, with -d:case3b, the running time is 4x the running time of the previous iteration. This means a quadratic running time.

### Expected Output
linear running time

### Additional Information
* 1.5.1 ac82be07d8ed9795caa0778f0f8577b3934d1d86
* not a regression

### notes
if i instrument nre as follows (see EDIT):
```nim
proc matchImpl(str: string, pattern: Regex, start, endpos: int, flags: int): Option[RegexMatch] =
  echo (start, endpos, flags, str) # EDIT
  var myResult = RegexMatch(pattern: pattern, str: str)
  ...
  let execRet = pcre.exec(pattern.pcreObj,

```

the following program shows that after it finds a match, the algorithm makes 1 call to pcre library per start position. This explains the quadratic behavior.

```nim
when true:
  import std/nre
  let reg = re"abc"
  let s = "x abc 123456789"
  echo s.len
  let output = s.replace(reg, "blah")
```
15
(0, 9223372036854775807, 0, "x abc 123456789")
(5, 9223372036854775807, 0, "x abc 123456789")
(6, 9223372036854775807, 0, "x abc 123456789")
(7, 9223372036854775807, 0, "x abc 123456789")
(8, 9223372036854775807, 0, "x abc 123456789")
(9, 9223372036854775807, 0, "x abc 123456789")
(10, 9223372036854775807, 0, "x abc 123456789")
(11, 9223372036854775807, 0, "x abc 123456789")
(12, 9223372036854775807, 0, "x abc 123456789")
(13, 9223372036854775807, 0, "x abc 123456789")
(14, 9223372036854775807, 0, "x abc 123456789")
(15, 9223372036854775807, 0, "x abc 123456789")

**Comment by dom96** [comment]
It's time we adopt an API for this (I guess either `re` or `nre`?) and the regex package into the stdlib.

**Comment by Araq** [comment]
How would that help? The API is ok, nre has a performance bug.

**Comment by dom96** [comment]
We should consolidate behind a single API and implementation instead of offering two in the stdlib, with a third in Nimble that is the only one that doesn't depend on pcre.

**Comment by Araq** [comment]
We couldn't agree on an API, which is why we have `nre`...

**Comment by xflywind** [comment]
A silly bug
