### ISSUE TITLE
Reference count leak in async / closure transformation

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17153]
```
import asyncdispatch

type X = ref object

proc testit123(xxx: X) {.async.} =
  callSoon() do ():
    discard testit123(xxx)

discard testit123(X())
while true:
  poll()
```

```
nim c -r -d:loggc -d:nimtypenames testit
...
[GC] incRef: 0x7f1b73f01040 22 X rc=158273; thread=0
[GC] incRef: 0x7f1b73f01040 22 X rc=158274; thread=0
[GC] incRef: 0x7f1b73f01040 22 X rc=158275; thread=0
[GC] incRef: 0x7f1b73f01040 22 X rc=158276; thread=0
[GC] incRef: 0x7f1b73f01040 22 X rc=158277; thread=0
[GC] incRef: 0x7f1b73f01040 22 X rc=158278; thread=0
```

```
[arnetheduck@tempus tmp]$ nim  --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

naturally, there's only one or two references to the `X` instance, but in this example, the reference count keeps growing meaning that somewhere, there's a `decRef` missing

curiously, memory usage is stable, so the closure environment is getting collected as it should.

**Comment by arnetheduck** [comment]
This issue was originally found in https://github.com/status-im/nim-chronos/issues/160

**Comment by Araq** [comment]
The memory usage is stable because the mark&sweep step kicks in after 4MB and does not use the reference counts. Async causes cycles and cycles mean there are too few `decRef`s happening. However, it's not clear to me yet why the RC numbers raise to these bizzarely high values.

**Comment by arnetheduck** [comment]
this also affects 1.2.6

**Comment by Araq** [comment]
I don't see a bug here tbh. You create an X object via X() that keeps being referenced in the closures. It increments the RC. The RC inc is an a while true loop. It can come to arbitrarily high values -- the `X` object is alive forever. What am I missing?

**Comment by arnetheduck** [comment]
well, each invocation of `testit123` also terminates and should thus release its reference count - ie we should be seeing a reference count of roughly 2 - one "in-flight" and one in the current invocation?

**Comment by arnetheduck** [comment]
specially because like you say, the closures are actually being collected - ie there's no growth in closure environments that take up more and more memory and reference `x` ?

**Comment by Araq** [comment]
When the closure is collected, it doesn't cause a decref. Instead the mark&sweep GC runs again (eventually) in order to free objects that have invalid ("much too high") RC values.

**Comment by arnetheduck** [comment]
alright - thanks for looking into it - this looked odd when investigating a larger issue we're having with the freelist being corrupted and leading to segfaults.

**Comment by jlokier** [comment]
The refcount keeps increasing, even with GC running (refc).

Eventually it looks like it will overflow on 32-bit (and on 64-bit for long-lived processes).

Presumably things can go wrong after that, for example the object might be freed at the next decrement of the refcount when it's still live.

On 32-bit (e.g. Raspberry Pi), it's a signed value and the lower 3 bits aren't part of it (4 in ORC).  That's leaves a max value of about 286 million. I tested on x86-64 not an RPi because I don't have one handy.  But the speeds are not wildly different.

The value overflowed the range of 32-bit signed refcount field after 43 seconds.

**Comment by jlokier** [comment]
@Araq wrote:
> When the closure is collected, it doesn't cause a decref. Instead the mark&sweep GC runs again (eventually) in order to free objects that have invalid ("much too high") RC values.

In the Nim manual it says:
> One can use the builtin procs `GC_ref` and `GC_unref` to keep the string data alive for the rare cases where it does not work.

Does the mark&sweep behaviour you described mean that the manual is wrong, i.e. `GC_ref` will _not_ keep data alive, because the GC ignores the RC values anyway?  Or is it only "insanely high" RC values that are freed?

**Comment by Araq** [comment]
> Eventually it looks like it will overflow on 32-bit (and on 64-bit for long-lived processes).

Correct. 

> The value overflowed the range of 32-bit signed refcount field after 43 seconds.

As I suspected, good to know. We should make the RC ops sticky.

**Comment by Araq** [comment]
> Does the mark&sweep behaviour you described mean that the manual is wrong, i.e. GC_ref will not keep data alive, because the GC ignores the RC values anyway? Or is it only "insanely high" RC values that are freed?

```nim

proc nimGCref(p: pointer) {.compilerproc.} =
  # we keep it from being collected by pretending it's not even allocated:
  let c = usrToCell(p)
  add(gch.additionalRoots, c)
  incRef(c)

```

The implementation looks correct as it's also registered as an additional root. It seems to work as documented.
