### ISSUE TITLE
destructor for `seq[T]` elements not called with gc:refc upon `setLen 0`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17186]
destructor not called for elements in a seq after a shrink via for example `setLen 0`

### Example
```nim
when true:
  type Foo = object
    f0: int

  proc `=destroy`(a: var Foo) =
    echo ("dtor", a.f0)

  proc main() =
    block:
      var b: seq[Foo]
      b.add Foo(f0: 1)
      b.add Foo(f0: 2)
    echo "ok2"
    block:
      var b: seq[Foo]
      b.add Foo(f0: 11)
      b.add Foo(f0: 12)
      echo "ok3"
      b.setLen 0
      echo "ok4"
    echo "ok5"
    # GC_fullCollect() # makes no difference
  main()
```

### Current Output
("dtor", 1)
("dtor", 2)
ok2
ok3
ok4
ok5

### Expected Output
should output same as with gc:arc
("dtor", 1)
("dtor", 2)
ok2
ok3
("dtor", 12)
("dtor", 11)
ok4
ok5

### Additional Information
* 1.5.1 578d1ee751fa8165a64c842c40216a752caf47e2
* EDIT: similar to https://github.com/nim-lang/Nim/issues/14604 but different and hopefully this isse is easier to fix, as it concerns setLen directly

**Comment by timotheecour** [comment]
## note
destructors should work, even for gc:refc, and even for vm and js, otherwise you end up with a language split, where code needs to be rewritten for specific backends.

example use case: auto-closing FILE:
```nim
type CFileWrap = object
  cfile: File

proc open2(path: string): CFileWrap =
  result.cfile = open(path)

proc `=destroy`(a: var CFileWrap) =
  if a.cfile != nil: close(a.cfile)
```

**Comment by ringabout** [comment]
`refc` shouldn't accept dedicated destructor support anymore.
