### ISSUE TITLE
[ARC] Compiler crashes with a case statement with more than ~2000 branches

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17198]
Found in https://github.com/soasme/nim-markdown/blob/master/src/markdownpkg/entities.nim. That code seems to have worked until recently because the recursion depth didn't hit the 2000 limit, but with the new ARC analysis, it crashes the compiler since the recursion has become a bit deeper.

### Example
Short example (generate with a macro):
```nim
import std/macros

macro bigCaseStmt(arg: untyped): untyped = 
  result = nnkCaseStmt.newTree(arg)

  # try to change 2000 to a bigger value if it doesn't crash
  for x in 0 ..< 2000:
    result.add nnkOfBranch.newTree(newStrLitNode($x), newStrLitNode($x))

  result.add nnkElse.newTree(newStrLitNode("other"))

proc test(arg: string): string = 
  result = bigCaseStmt(arg)

discard test("test")
```

Original example - https://gist.github.com/Yardanico/e4e75123ae4b8b93eb99a7c97b7c5e9b

### Current Output
Hard compiler crash (no stack trace at all)

### Expected Output
Successful compilation.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-28
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 26a6ceb34eb2bfca4e39dec2dac2d0a2cdc1bade
active boot switches: -d:release -d:danger
```

**Comment by juancarlospaco** [comment]
Can reproduce with `if`, `elif`, `else` too.
Crashes on exactly `1797` and higher, 
`1796` and lower works, for me.

**Comment by saem** [comment]
It's because of the way the DFA is built, the branches lead to nested forks, leading to the graph becoming wider and wider for each additional branch. This means that when it comes time to collectLastReads it ends up recursing and hitting the call limit. Here is a snippet of the the control flow listing which illustrates the issues:

```
           0 use     arg   #17
           1 fork    L3    #17
           2 goto    L3001 #17
L3:                           
           3 fork    L5    #17
           4 goto    L3001 #17
L5:                           
           5 fork    L7    #17
           6 goto    L3001 #17
L7:                           
           7 fork    L9    #17
           8 goto    L3001 #17
L9:                           
           9 fork    L11   #17
           10 goto   L3001 #17
L11:                          
           11 fork   L13   #17
           12 goto   L3001 #17
L13:                          
           13 fork   L15   #17
           14 goto   L3001 #17
L15:                          
           15 fork   L17   #17
           16 goto   L3001 #17
```
