### ISSUE TITLE
Generics issue

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#17212]
Yesterday I tried to save some lines of code in gen.nim file by using one more generic parameter.

Was no problem to join proc glistObjects2seq() and proc gslistObjects2seq() by making parameter l generic, but it does not work for 

https://github.com/StefanSalewski/gintro/blob/master/tests/gen.nim#L2910

Issue is related to this:

```nim
proc t[T](x: T; z: int | float): seq[T] =
  result.add(x & $z)

var y = t[string]("Hallo", 2.0)

proc t2[T](z: int | float): seq[T] =
  result.add($z)

var y2 = t2[string](2.0)
```

/tmp/hhh/t.nim(9, 10) Error: cannot instantiate: 't2[string]'; got 1 typeof(s) but expected 2

/tmp/hhh/t.nim(4, 9) Error: cannot instantiate: 't[string]'; got 1 typeof(s) but expected 2

**Comment by mattrbeck** [comment]
I don't think I'm providing any new information, but just want to document that I'm observing the same thing!
```nim
proc f[b: bool](i: uint8 | uint32) = discard
f[true](0'u32)
```
```
Error: cannot instantiate: 'f[true]'; got 1 typeof(s) but expected 2
```

**Comment by shirleyquirk** [comment]
another one, it's anything that makes it implicitly generic:
```nim
proc f[T](k:static bool):T = discard
```
also https://github.com/nim-lang/Nim/issues/2177

the hack of `f[int,true]()` doesn't work if there's another parameter:
```nim
proc g[T](x:int,k:static bool) = discard
g[int,true](5) # got int expected (int,static[bool](true))
g[int,true](5,true) # got (int,bool) expected (int,static[bool](true))
```

**Comment by beef331** [comment]
To be more exact the issue is "Explict generics and inferred generics cause an error if used together". The only workaround I've found is to make use only of explict generics. It's not nice whatsoever though :smile: 
```nim
proc t[T; Y: int or float](x: T; z: Y): seq[T] = discard

proc t2[T; Y: int or float](z: Y): seq[T] = discard

proc f[b: bool, c: uint8 or uint32](i: c) = discard

proc g[T; Y: static bool](x:int) = discard

discard t[string, int]("H", 3)
discard t2[string, int](3)
f[true, uint8](127u8)
g[string, true](0)
```
