### ISSUE TITLE
redefinition of typedef ‘NIM_STATIC_ASSERT_AUX’  in x32

### ISSUE THREAD

**Issue by h4cnull** [nim-lang/Nim#17247]
I try to use musl-gcc build a 32bit file。
system: centos6.8 i386
command: nim --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --passL:-static -d:release -d:danger -d:strip --opt:size c xxx.nim
error out:
 
Hint: used config file '/opt/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/nim/config/config.nims' [Conf]
...............................................
Hint: musl-gcc -c  -w -fmax-errors=3 -Os -fno-ident   -I/opt/nim/lib -I/root -o /root/.cache/nim/xxx_r/stdlib_assertions.nim.c.o /root/.cache/nim/xxx_r/stdlib_assertions.nim.c [Exec]
In file included from /root/.cache/nim/xxx_r/stdlib_assertions.nim.c:12:
/opt/nim/lib/nimbase.h:542: error: redefinition of typedef ‘NIM_STATIC_ASSERT_AUX’
/opt/nim/lib/nimbase.h:323: note: previous declaration of ‘NIM_STATIC_ASSERT_AUX’ was here
Error: execution of an external program failed: 'musl-gcc -c  -w -fmax-errors=3 -Os -fno-ident   -I/opt/nim/lib -I/root -o /root/.cache/nim/xxx_r/stdlib_assertions.nim.c.o /root/.cache/nim/xxx_r/stdlib_assertions.nim.c'

**Comment by timotheecour** [comment]
@h4cnull PR welcome

**Comment by h4cnull** [comment]
I back up lib/nimbash.h  and add comment these lines，error fixed。
274 //#else
275 //#define NIM_STATIC_ASSERT(x, msg) typedef int NIM_STATIC_ASSERT_AUX[(x) ? 1         : -1];

323 //NIM_STATIC_ASSERT(sizeof(NIM_BOOL) == 1, ""); // check whether really needed
542 //NIM_STATIC_ASSERT(sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8        , "");

**Comment by FedericoCeratto** [comment]
I'm able to reproduce the issue by using gcc 4.1 or 4.2:
```
./bin/nim c --gcc.exe:gcc-4.2 koch.nim
[trimmed]
.........................................................
CC: stdlib_assertions.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
In file included from /home/fede/.cache/nim/koch_d/stdlib_assertions.nim.c:8:
/home/fede/projects/Nim/lib/nimbase.h:546: error: redefinition of typedef ‘NIM_STATIC_ASSERT_AUX’
/home/fede/projects/Nim/lib/nimbase.h:327: error: previous declaration of ‘NIM_STATIC_ASSERT_AUX’ was here
In file included from /home/fede/.cache/nim/koch_d/stdlib_io.nim.c:8:
/home/fede/projects/Nim/lib/nimbase.h:546: error: redefinition of typedef ‘NIM_STATIC_ASSERT_AUX’
/home/fede/projects/Nim/lib/nimbase.h:327: error: previous declaration of ‘NIM_STATIC_ASSERT_AUX’ was here
CC: stdlib_unicode.nim
[trimmed]
```
