### ISSUE TITLE
regression (1.4 => devel): rst: paragraph incorrectly created on line break, in 1st line of a list

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17249]
### Example
```nim
Conventions
-----------
1. New stdlib modules should go under `Nim/lib/std/`. The rationale is to require
users to import via `import std/foo` instead of `import foo`, which would cause
potential conflicts with nimble packages. Note that this still applies for new modules
in existing logical directories, e.g.:
use `lib/std/collections/foo.nim`, not `lib/pure/collections/foo.nim`.

2. New module names should prefer plural form whenever possible, e.g.:
`std/sums.nim` instead of `std/sum.nim`. In particular, this reduces chances of conflicts
between module name and the symbols it defines. Furthermore, module names should
use `snake_case` and not use capital letters, which cause issues when going
from an OS without case sensitivity to an OS with it.
```

### Current Output
the bug is that there is a new paragraph after `The rationale is to require` and after `possible, e.g.:`
![image](https://user-images.githubusercontent.com/2194784/109904033-7ad66c00-7c51-11eb-9e08-0a1070f2009b.png)

### Expected Output
![image](https://user-images.githubusercontent.com/2194784/109904072-86299780-7c51-11eb-89a4-2cfb77a790e8.png)

### Additional Information
* bug in 1.5.1 507873be25baa06d7da3c44b0c36d253c850625d
* works in 1.4.4
/cc @a-mr

**Comment by a-mr** [comment]
@timotheecour Thanks, well spotted. Also this problem is present in 2 other places in the nim repo.

However you are not quite right: RST requires to have indentation on the second and subsequent lines of enum.item, otherwise the entire thing should be parsed as a single paragraph.
