### ISSUE TITLE
Macro generating an internal error

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#17285]
I'm uncertain about how to minify this issue so will mention everything I can.

I have this [macro](https://play.nim-lang.org/#ix=2RZv) which generates [identical AST](https://www.diffchecker.com/LPTy2r7X) to what `dumptree` responds with. Which is where this weirdness starts, if I take the `astGenRepr` and put it in a macro it compiles and runs with no [problem](https://play.nim-lang.org/#ix=2RZy). This weirdness continues as it [compiles just fine](https://play.nim-lang.org/#ix=2RZA) with only a single variant type.
The compiler error is:
`Error: internal error: environment misses: g`
Currently my workaround is doing `parseStmt(result.repr)` which allows it to compile properly.

Tested on Devel and Stable.

**Comment by LotfiAghel** [comment]
hi
two symbols have same name but not equal you cloned the AST whitout cloning symbols
your code return AST same as following code

```
proc FUN1():int=
     var v =1
     return v

proc FUN2():int=
     int v = 2
     return v (but this v is FUN1::v)
```

on echo every things seems true but not true
when you use parseStmt convert to string and parse truly

**Comment by beef331** [comment]
I do not know what you mean, the AST of the `treeRepr` is identical to the `dumptree` result of the `repr`, the `astgenrepr` also compiles just fine. I remove all remnants of the symbols and use identifiers.

edit: If I understand your implication that the ident is already looked up that's not how it works since this compiles just fine
```nim
import macros
macro test: untyped =
  let idnt = ident("a")
  quote do:
    proc thing(`idnt`: int) = echo `idnt`
    proc thing2(`idnt`: int) = echo `idnt`
test()
100.thing
300.thing
```
