### ISSUE TITLE
`rst.whichMsgClass` is buggy: relies on $enum instead of $ast(enum)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17280]
/cc @a-mr
root cause for https://github.com/nim-lang/Nim/pull/17257#discussion_r588589346

> Currently we have a more basic problem that I haven't learned how to handle rstMessage invocation in test, it just throws AssertionDeffect by some reason, which is ridiculous :-(

the problem is this code:
```nim
  MsgKind* = enum          ## the possible messages
    meCannotOpenFile = "cannot open '$1'",
    meExpected = "'$1' expected",
    ...
    meGeneralParseError = "general parse error",
    meInvalidDirective = "invalid directive: '$1'",
    mwRstStyle = "RST style: $1"

proc whichMsgClass*(k: MsgKind): MsgClass =
  ## returns which message class `k` belongs to.
  case ($k)[1]
  of 'e', 'E': result = mcError
  of 'w', 'W': result = mcWarning
  of 'h', 'H': result = mcHint
  else: assert false, "msgkind does not fit naming scheme"
```
relies on `$k` which doesn't reflect the ast symbol of the enum

### Additional Information
1.5.1 07df4fe560850b036e84750aced746daa58e2427

### proposed solution
I'd like all 3 things below:

## fix 1
use range:
```nim
const
  MsgKindErrors = meCannotOpenFile..mwRedefinitionOfLabel
  MsgKindWarnings = mwRedefinitionOfLabel.next..mwRstStyle
  MsgKindHints = mwRstStyle.next..MsgKind.high
```
then:
```nim
proc whichMsgClass*(k: MsgKind): MsgClass =
  case k
  of MsgKindErrors: mcError
  of MsgKindWarnings: mcWarning
  of MsgKindHints: mcHint
```

## fix 2
replace
```nim
    # TODO: find out hot to catch warning here instead of throwing a defect
    echo input8
    expect(AssertionDefect):
      let output8 = input8.toHtml
```
(eg from https://github.com/nim-lang/Nim/pull/17257)
accordingly now that the bug gets fixed, ditto for all (or most) of the other `expect(AssertionDefect):`

## fix 3 + proposal: enumutils.symbolName
(EDIT: => https://github.com/nim-lang/Nim/pull/17281)
not needed to fix this issue but still useful in general (and would provide an alternative way to fix this): add `proc nativeString(a: enum): string` which returns the native string for an enum, ignoring the string definition. This should address remaining concerns for using this kind of enums:
```nim
type A = enum
  a0 = "human name"
```
(refs https://github.com/nim-lang/Nim/pull/15775#issuecomment-719428113) 
since it gives both stringified form (most common case) as well as access to native name ("a0"):
```nim
let x = A.low
assert $x == "human name" # common case
assert nativeString(x) == "human name" # when needed
```

**Comment by a-mr** [comment]
To have `symbolName` (fix 3) is generally useful. And it's closest to the original idea of code `$k[1]`; to change it to `k.symbolName[1]`

**Comment by timotheecour** [comment]
@a-mr fix 3 has been merged so you can go ahead and use it to close this issue
