### ISSUE TITLE
Ambiguities in the Windows Installing Instructions

### ISSUE THREAD

**Issue by nilslindemann** [nim-lang/Nim#17291]
It is not a big thing, but I wonder, in the [Windows Installing instructions](https://nim-lang.org/install_windows.html), shouldn't the headings "Binary installation", "Compiler dependencies" and "Other dependencies" be h2 headings instead of h1 headings? Because they seemingly belong to "Manual Installation". And is the "Binary Installation" heading needed?

Otherwise, these are noob-friendly installing instructions.

**Comment by ringabout** [comment]
it's the issue of
 https://github.com/nim-lang/website/blob/master/jekyll/install_windows.md
PR is welcome there.

**Comment by nilslindemann** [comment]
Thanks @xflywind, I will make a PR
