### ISSUE TITLE
Impossible to generate binary without run it

### ISSUE THREAD

**Issue by kunitoki** [nim-lang/Nim#17313]
After looking the documentation, i am not able to link an executable without running it too. There seems to be no command line option to generate a binary only.

There seems to be options for `--compileOnly` (will just generate c, cpp or objc files in cache) and `--noLinking` where i get compiled objects in the cache but no final binary. Using `--run` it's the only flag that will generate the binary, but it's also running it.

It would be nice to split binary linking from running. Or there is a way to accomplish this ?

**Comment by timotheecour** [comment]
```
nim c foo.nim
```
?

**Comment by timotheecour** [comment]
closing, please re-open or add a comment if this doesnt' work

**Comment by kunitoki** [comment]
doh, that works indeed. i think i might have used `nim c -c foo.nim` when i was thinking i just used `nim c foo.nim`.

thanks for the clarification !
