### ISSUE TITLE
unhelpful error message when using [N: int] instead of [N: static[int]] in generic

### ISSUE THREAD

**Issue by ShadowElf37** [nim-lang/Nim#17362]
This error message is particularly confusing for beginners, who may forget or simply not know to put `static`. Getting compiler noise makes it impossible to determine what the actual issue is with the code.

### Error
```
fatal.nim(53)            sysFatal
Error: unhandled exception: int128.nim(72, 11) `arg.sdata(2) == 0` out of range [AssertionDefect]
```

### Expected Output
```
test.nim(4)            test
Error: unhandled exception: Please put static thank you. [AssertionDefect]
```

### Sample Bad Code
```nim
type IntArrayContainer[N: int] = object
    arr: array[N, int]

discard IntArrayContainer[3]()
```

### Version
```
Nim Compiler Version 1.4.4 [MacOSX: arm64]
Compiled at 2021-02-24
Copyright (c) 2006-2020 by Andreas Rumpf
```

**Comment by timotheecour** [comment]
PR welcome

**Comment by konsumlamm** [comment]
This is an internal assertion failure, which shouldn't occur in the first place, there should be a normal Nim error message instead. So changing the assertion message wouldn't fix the actual issue.

Duplicates:
#17163
#15862
#6834
