### ISSUE TITLE
json.`%` raises `Defect` for `uint64`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17383]
https://github.com/nim-lang/Nim/blob/51a04a3674d62707506774b11a4376a914735aeb/lib/pure/json.nim#L315

converting a `uint64` to a `JsonNode` raises a `Defect` on values outside the `BiggestInt` range, defeating the purpose of using this overload to begin with - to resolve, one would either deprecate / remove the overload or output a string instead - the latter would require parsing strings as well in the opposite direction.

**Comment by timotheecour** [comment]
see https://github.com/nim-lang/Nim/pull/17389
