### ISSUE TITLE
Distinct type comparison operator infinite loop

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17381]
Hello everyone!

I'm new to nim and like it a lot so far, but I run into a problem, which I think is a bug.
It might be related with bug #13008, but I'm not sure, so I've created a new issue.
I was playing around with the comparison operator != for the made up distinct type DT.
Executing the following code however resulted into an infinite loop.

```
type
  DT = distinct uint64

proc `!=`(h1, h2: DT): bool =
  return h1 != h2
  
let h1 = 0x1.DT
let h2 = 0x2.DT
  
if h1 != h2:
  echo("not equal")
```
During debugging on an assembler level it seems the operator resulted into a jump instruction towards itself, creating that loop.

`00007FF6A9E110DC jmp 00007FF6A9E110DC`

I was able to solve the problem by coercing the DT type variables h1 and h2 into the base type utin64:

```
proc `!=`(h1, h2: DT): bool =
  return h1.uint64 != h2.uint64

```

**Comment by SolitudeSF** [comment]
not a bug. you wrote recursive function.

**Comment by ringabout** [comment]
Another possible solution

```nim
type
  DT = distinct uint64

proc `==`(h1, h2: DT): bool {.borrow.}
  
let h1 = 0x1.DT
let h2 = 0x2.DT
  
if h1 != h2:
  echo("not equal")
```

You can ask questions on [discord](https://discord.com/invite/nim) or [Nim forum](https://forum.nim-lang.org) too.

**Comment by ghost** [comment]
@riedmu when you create a **distinct** type procedures that work on the original type won't work on a distinct - that's the main feature of `distinct`. As @xflywind showed, you need to either borrow the comparison operator from the original type or convert your types into the original to compare.

**Comment by Clyybber** [comment]
Nim doesn't automatically convert distinct arguments to their base type, which would be very unintuitive behaviour IMO.
