### ISSUE TITLE
Strict funcs doesn't work with the JSON module

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17387]
As usual, the title is bad; code speaks for itself. Originally reported by @zidsal on Discord.

### Example
```nim
type
  Table = object
    data: seq[int]

  JsonNode = ref object
    fields: Table

proc `[]`(t: var Table, key: string): var int = 
  result = t.data[0]

proc `[]`(x: JsonNode, key: string): int = 
  result = x.fields[key]

func parseColumn(columnNode: JsonNode) =
  var columnName = columnNode["test"]

parseColumn(JsonNode())
```

Not minimized example:
```nim
import json

func parseColumn(columnNode: JsonNode) =
  let columnName = columnNode["name"].str

parseColumn(%*{"a": "b"})
```

### Current Output
```
/home/dian/Things/Nim/other.nim(14, 6) Error: 'parseColumn' can have side effects
Traceback (most recent call last)
/home/dian/Things/Nim/compiler/nim.nim(125) nim
/home/dian/Things/Nim/compiler/nim.nim(84) handleCmdLine
/home/dian/Things/Nim/compiler/main.nim(242) mainCommand
/home/dian/Things/Nim/compiler/main.nim(213) compileToBackend
/home/dian/Things/Nim/compiler/main.nim(90) commandCompileToC
/home/dian/Things/Nim/compiler/modules.nim(177) compileProject
/home/dian/Things/Nim/compiler/modules.nim(97) compileModule
/home/dian/Things/Nim/compiler/passes.nim(186) processModule
/home/dian/Things/Nim/compiler/passes.nim(73) processTopLevelStmt
/home/dian/Things/Nim/compiler/sem.nim(607) myProcess
/home/dian/Things/Nim/compiler/sem.nim(575) semStmtAndGenerateGenerics
/home/dian/Things/Nim/compiler/semstmts.nim(2306) semStmt
/home/dian/Things/Nim/compiler/semexprs.nim(1042) semExprNoType
/home/dian/Things/Nim/compiler/semexprs.nim(2911) semExpr
/home/dian/Things/Nim/compiler/semstmts.nim(2089) semFunc
/home/dian/Things/Nim/compiler/semstmts.nim(2008) semProcAux
/home/dian/Things/Nim/compiler/sempass2.nim(1343) trackProc
/home/dian/Things/Nim/compiler/msgs.nim(552) liMessage
/home/dian/Things/Nim/compiler/msgs.nim(420) handleError
/home/dian/Things/Nim/compiler/msgs.nim(403) quit
```

### Expected Output
Successful compilation

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-15
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 51a04a3674d62707506774b11a4376a914735aeb
active boot switches: -d:release -d:danger
```

**Comment by beef331** [comment]
This is a valid error(if using strict funcs).
> Any mutation to an object does count as a side effect if that object is reachable via a parameter that is not declared as a var parameter.

`columnNode["test"]` calls this `proc [](t: var Table, key: string): var int`  which returns a mutable pointer and `strictFunc` says it's a possible side effect due to the fact you could mutate the supposedly immutable object.  

Because of the strictness of strictfunc `func parseColumn(columnNode: var JsonNode)` needs to be used.

Atleast this is my take on why this error happens, in strictFunc `ref objects` are not inheritely mutable.

**Comment by ghost** [comment]
@beef331 but that [] is only used in [] for JsonNode which does not modify the variable and returns an immutable int

**Comment by beef331** [comment]
Remember the strict func checker doesnt check if it does modify it's if it can. Even a reference of a `let` value can result in an error. The following doesnt compile even though it doesnt mutate. Strict funcs checks for any possibillity of mutation. If that compiled the jsonNode `[]`  could have changed the returned int before returning it which would be impure. I see this as it working as intended. Strict functions should not allow any chance of mutation regardless what the function calls, so the strict func rules are applied to any called procedures aswell.
```nim
let a = "hello"
proc t1 = 
  var b = a
func test = t1()
test()
```

**Comment by ghost** [comment]
@beef331 maybe you're right, I don't know, but then strictFuncs should somehow be able to select the non-var overload for [] Table (see the original example with JSON) because otherwise we'll have parts of stdlib unusable in funcs for no real reason.

**Comment by ghost** [comment]
It's worth noting that the example works if you enable strictFuncs in the code itself, but not with --experimental:strictFuncs
