### ISSUE TITLE
getHomeDir and expandTilde should not include trailing `/`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17393]
IMO it's a bug that should be fixed (with the usual `-d:nimLegacyHomeDir`)

also recently reported in forum [getCurrentDir vs getHomeDir output - Nim forum](https://forum.nim-lang.org/t/7635)

pretty much all the languages don't include the trailing `/` except nim; consistency with other languages here is more important than historical baggage IMO.

nim also isn't consistant with itself because (almost all or all) other procs don't include trailining `/` (eg getCurrentDir + others)

### Example
* D
rdmd --eval 'writeln(expandTilde("~"))'
/Users/timothee

* bash
echo $HOME
/Users/timothee
echo ~
/Users/timothee

* C, C++
```c
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
int main (int argc, char *argv[]) {
  struct passwd *pw = getpwuid(getuid());
  const char *homedir = pw->pw_dir;
  printf("%s\n", homedir);
  return 0;
}
```
/Users/timothee

* swift
```swift
import Foundation
print(NSString(string: "~").expandingTildeInPath)
print(NSHomeDirectory())
```
/Users/timothee
/Users/timothee

* python3
```nim
python3 -c 'from pathlib import Path; print(Path.home()); from os.path import expanduser; print(expanduser("~"))'
/Users/timothee
/Users/timothee
```

* nim:
nim --eval:'import os; echo expandTilde("~")'
/Users/timothee/
nim --eval:'import os; echo getHomeDir()'
/Users/timothee/

### Expected Output
nim should match other languages

### Additional Information
1.5.1 d5eb658034a8a1fffefbc4acdf9cb89f9f741f95

## links
see https://stackoverflow.com/a/2910392/1426932 + is caveat mentioning `getpwuid(getuid());` vs `getenv("HOME")`

**Comment by Araq** [comment]
> pretty much all the languages don't include the trailing / except nim; consistency with other languages here is more important than historical baggage IMO.

So in other words, we care more about the people porting snippets over from language X than the people who already use Nim and don't want constant subtle code breakages just so that Nim is more consistent with language X. We never claimed os.nim to be compatible with Bash or Python, you know. If we claimed that we would have done a much better job at it...

**Comment by timotheecour** [comment]
nim prior to the bugfixes wasn't just inconsistent with pretty much all other languages, it was inconsistent with itself: all other nim APIs I'm aware of that return a dir did not include a trailing `/` in 1.4:

* getCurrentDir
* getAppDir
* parentDir
* splitFile.dir
* splitPath.head
* parentDirs
* walkDirs
* thisDir
* projectDir
* nimcacheDir
* normalizedPath

the fact that getHomeDir().normalizedPath removes the `/` is yet another sign.

After the bugfix, nim is consistent with all other languages and consistent with itself so you don't need the mental overhead to constantly try to remind yourself about which API returns a trailing `/` vs not. This is a big win.

What we can do is introduce `{.migration(nimLegacyHomeDir): "getHomeDir now doesn't include a trailing DirSep".}` to help migration, but there's no point in reverting this; I'll explain this in more details later.

**Comment by dom96** [comment]
Why does it matter if there is a trailing slash or not?
