### ISSUE TITLE
Tuples documentation in language manual

### ISSUE THREAD

**Issue by m4r35n357** [nim-lang/Nim#17403]
Documentation on tuples: "The names of the fields also have to be identical."

They do not; you can put underscores in.  Reported on IRC, and Rika told me to do it ;)

**Comment by de-odex** [comment]
to clarify further, they meant that "identical" doesnt sufficiently imply "identical subject to nim's ident rules" or so

**Comment by ghost** [comment]
@de-odex but shouldn't that be implied? It would be quite redundant to repeat "identifier names have to be identical per nim's ident equality rules" each time you mention identifier equality

**Comment by m4r35n357** [comment]
"Identical" has a very clear and unequivocal meaning in the world of computing.  I don't think you should use the word unqualified unless you really mean it.  Docs are meant to be used by newbies as well as experts.  I think I have hardened my opinion on this; after all, I was misled.

**Comment by PMunch** [comment]
"The names of the fields also have to be the same" would be less confusing. But that whole section is a bit messy.
