### ISSUE TITLE
`seq.pop` deletes the whole seq at compile time using ARC-bootstrapped Nim

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#17412]
To reproduce this, **you need to bootstrap using ARC**: `koch boot --gc:arc`.

This behavior was spotted in several `important_packages`, and this is an extracted minimal example.

### Example
```nim
var a {.compileTime.} = @["a"]

proc foo =
    a.add("b")
    a.add("c")
    a.add("d")
    echo a
    let c = a.pop() # causes trouble
    echo c
    echo a # should be: @["a", "b", "c"]; it is: @[]
    a.add("z") # "attempt to access a nil address"

static:
  foo()
```

### Current Output
```
@["a", "b", "c", "d"]
d
@[]
stack trace: (most recent call last)
(...)/filename.nim(11, 6) Error: attempt to access a nil address  
```

### Expected Output
```
@["a", "b", "c", "d"]
d
@["a", "b", "c"]
```

cc @Clyybber

**Comment by deech** [comment]
Related? https://github.com/nim-lang/Nim/pull/17348

**Comment by Clyybber** [comment]
> Related? #17348

Nope, issue here is that `=copy` for case objects doesn't handle self assignment correctly.
