### ISSUE TITLE
"undeclared identifier" in generic bound

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17411]
### Example
```nim
proc foo[A, B: A]() = discard
```

### Current Output
```
Error: undeclared identifier: 'A'
```

### Expected Output
No error.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-17
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 4bfc5a955120b90faf07f50b54ae29f2c6e6f123
active boot switches: -d:release
```

**Comment by metagn** [comment]
It's supposed to be

```nim
proc foo[A; B: A]() = discard
```

Semicolon not colon, otherwise you get `A: A`

**Comment by konsumlamm** [comment]
> Semicolon not colon, otherwise you get `A: A`

Ohh, i see, thank you!

Perhaps this should be mentioned as a gotcha in the docs (if it already is, ignore this suggestion)? I'll leave this issue open, but feel free to close it if you deem it appropriate.

**Comment by timotheecour** [comment]
I documented it here recently: https://github.com/nim-lang/Nim/pull/17192

closing, feel free to re-open if not clear enough
