### ISSUE TITLE
`raises` not enforced for proc type parameters

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17475]
`f` should imo also fail.

```
type
  Callback = proc()
  X = object
    callback: Callback

proc f(callback: Callback) {.raises: [].} =
  callback() # No error, why?

proc g(x: X) {.raises: [].} =
  x.callback() # Error: can raise an unlisted exception: Exception
```

nim 1.2.6, 1.4.4

**Comment by Clyybber** [comment]
I think this follows the same logic as the `noSideEffect` tracking. The effects for the callback argument are checked at callsite:
```nim
type
  Callback = proc()

proc f(callback: Callback) {.raises: [].} =
  callback()

proc main {.raises: [].} =
  f(proc () = raise newException(IOError, "IO"))
```
In the case of `g` I think the compiler is just pessimistic about it, since the callback is wrapped inside an object.

**Comment by arnetheduck** [comment]
That's wrong though: _no_ exception should come out of `f` per the `raises` annotation on `f`!

Ie this shouldn't compile, and it certainly shouldn't raise a `IOError` inside f, yet it does

```nim
type
  Callback = proc()

proc f(callback: Callback) {.raises: [].} =
  callback()

proc main =
  f(proc () = raise newException(IOError, "IO"))

main()
```
