### ISSUE TITLE
Excessive use of builds.sr.ht

### ISSUE THREAD

**Issue by ddevault** [nim-lang/Nim#17479]
Hi folks. I've spoken with ~araq about this several times, but it continues to be a problem. Nim makes excessive use of builds.sr.ht, far more than almost any other project does. You have submitted 275 builds today alone, totaling over 200 hours of build time. For context, a similar level of usage on CircleCI would cost you almost $75 per day. This is causing disruptions for other users.

Please reduce your OpenBSD builds to just one manifest, and do whatever testing you need to do in serial rather than in parallel. Please also disable your builds for pull requests and only build commits - your contributors are too often pushing and repushing tens of commits to each pull request, most of which don't need to be built.

I've been trying to address this issue with the Nim project for several months now. If a timely resolution is not found, I will be terminating service for your project.

**Comment by narimiran** [comment]
> Please also disable your builds for pull requests

Agreed. We should do this ASAP.

**Comment by Araq** [comment]
> Please reduce your OpenBSD builds to just one manifest

This means to delete ``.builds/openbsd_1.yml``, right?

> Please also disable your builds for pull requests and only build commits - your contributors are too often pushing and repushing tens of commits to each pull request, most of which don't need to be built.

How to accomplish that?

**Comment by narimiran** [comment]
> How to accomplish that?

I've now disabled the webhooks which were triggered by pull requests. Now it should be commits-only. (I'll monitor new pull requests to see if that's really the case, to be sure.)

**Comment by ddevault** [comment]
>This means to delete .builds/openbsd_1.yml, right?

Yep, and merge anything it would have done into the other manifest.

> > Please also disable your builds for pull requests and only build commits - your contributors are too often pushing and repushing tens of commits to each pull request, most of which don't need to be built.
> 
> How to accomplish that?

Head to https://dispatch.sr.ht and disable the appropriate task.

**Comment by ddevault** [comment]
Thanks @narimiran

**Comment by Araq** [comment]
> Head to https://dispatch.sr.ht and disable the appropriate task.

Thanks, done.

**Comment by Araq** [comment]
> I've now disabled the webhooks which were triggered by pull requests. Now it should be commits-only. (I'll monitor new pull requests to see if that's really the case, to be sure.)

Ooops...

**Comment by narimiran** [comment]
@ddevault See https://github.com/nim-lang/Nim/pull/17480: no sr.ht BSD CIs anymore.

> I've been trying to address this issue with the Nim project for several months now. If a timely resolution is not found, I will be terminating service for your project.

I had no information about this being an old well-known problem. Hopefully, this change should bring our usage way down. If there's a similar problem in the future, please ping me too (together with @Araq).

**Comment by ddevault** [comment]
Thanks for the speedy response!
