### ISSUE TITLE
int128.nim gives AssertionDefect

### ISSUE THREAD

**Issue by junknet** [nim-lang/Nim#17470]
I'm developing nimlsp vscode extension.
When i start nimlsp,the error  raise.
This is nimlsp log:

Hint: used config file '/home/junknet/.choosenim/toolchains/nim-1.4.4/config/nim.cfg' [Conf]
Hint: used config file '/home/junknet/.choosenim/toolchains/nim-1.4.4/config/config.nims' [Conf]
Hint: used config file '/home/junknet/Desktop/nimlsp/src/config.nims' [Conf]
/home/junknet/Desktop/nimlsp/src/nimlsp.nim(486) nimlsp
/home/junknet/Downloads/Nim-1.4.4/nimsuggest/nimsuggest.nim(727) initNimSuggest
/home/junknet/Downloads/Nim-1.4.4/nimsuggest/nimsuggest.nim(684) mockCommand
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(160) compileProject
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(208) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2839) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2246) semStmtList
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2727) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1008) semDirectOp
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(891) afterCallActions
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(474) semMacroExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(417) semAfterMacroCall
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2839) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2246) semStmtList
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(217) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(214) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(215) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(214) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(217) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(214) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(217) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(211) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(217) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(214) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2872) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(217) evalImport
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(188) impMod
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/importer.nim(158) myImportModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(110) importModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/modules.nim(96) compileModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(214) processModule
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/passes.nim(86) processTopLevelStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(606) myProcess
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/sem.nim(569) semStmtAndGenerateGenerics
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2304) semStmt
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1026) semExprNoType
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2857) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2085) semProc
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2004) semProcAux
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(1777) semProcBody
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2839) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(2246) semStmtList
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semexprs.nim(2850) semExpr
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semstmts.nim(969) semCase
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/semtypes.nim(571) semCaseBranch
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/nimsets.nim(135) deduplicate
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/nimsets.nim(72) toBitSet
/home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/int128.nim(71) toInt64
/home/junknet/.choosenim/toolchains/nim-1.4.4/lib/system/assertions.nim(30) failedAssertImpl
/home/junknet/.choosenim/toolchains/nim-1.4.4/lib/system/assertions.nim(23) raiseAssert
/home/junknet/.choosenim/toolchains/nim-1.4.4/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /home/junknet/.choosenim/toolchains/nim-1.4.4/compiler/int128.nim(71, 11) arg.sdata(3) == 0 out of range [AssertionDefect]
[Info - 4:21:43 PM] Connection to server got closed. Server will restart.
[Error - 4:21:43 PM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 4:21:43 PM] Request textDocument/hover failed.

**Comment by ringabout** [comment]
Please provide the code that causes the crash.

And similar/same issue -- https://github.com/nim-lang/Nim/issues/12684 already works in devel.
