### ISSUE TITLE
instantiationInfo returns "???" when called outside of a template

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#17482]
```nim
echo instantiationInfo().filename


proc fn2(): string =
  instantiationInfo().filename

echo fn2()


template fn3(): string =
  instantiationInfo().filename

echo fn3()
```

shows:

    ???
    ???
    ppp.nim

I would expect, in order of most desirable:

1. instantiationInfo working outside of a template
2. a compilation error
3. an exception

Returning "???" does not make sense to me.

**Comment by ringabout** [comment]
Duplicate of #11689
