### ISSUE TITLE
Nim Website: Guide only for Nimble

### ISSUE THREAD

**Issue by akaufmann** [nim-lang/Nim#1749]
I think it would be beneficial if Nimble would has an own guide. Accessible via the main nav.

Maybe a guide like Rust's Cargo ...
http://doc.crates.io/guide.html

**Comment by narimiran** [comment]
There is a detailed Nimble guide in its own repo: https://github.com/nim-lang/nimble

This should be closed.

**Comment by andreaferretti** [comment]
Still not linked from the main site, though, AFAICT

**Comment by narimiran** [comment]
> Still not linked from the main site, though, AFAICT

I just made a PR to solve that.
