### ISSUE TITLE
lent type causes issues

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#17507]
```nim
type
  Test = object
    id: int

iterator keys(t: Test): int =
  yield t.id

iterator sections(t: Test): lent int =
  for i in t.keys:
    yield i
```
Gives: Error: address of 'i' may not escape its stack frame

Workaround(or solution?): `keys` also uses `lent` return types.
```nim
type
  Test = object
    id: int

iterator keys(t: Test): lent int =
  yield t.id

iterator sections(t: Test): lent int =
  for i in t.keys:
    yield i
```

An example which shows where the workaround is needed
https://github.com/nim-lang/Nim/pull/17505
https://github.com/nim-lang/Nim/pull/15450

**Comment by Araq** [comment]
This is not a bug, that the compiler catches this mistake is great!
