### ISSUE TITLE
`--boundChecks:off` disables compile-time bound checks

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17503]
As far as the documentation is concerned, `boundChecks` should **only** disable runtime bound checks, but right now it also disables them at compile-time if you pass `--boundChecks:off` or `-d:danger` (which implies `boundChecks`). Originally reported in Discord by @de-odex

### Example
```nim
let a = ["data"]
echo a[1] # out of bounds
```

### Current Output
```
$ nim c --verbosity:0 --boundChecks:off -r bug.nim
Traceback (most recent call last)
/home/dian/Stuff/test/bug.nim(2) bug
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/dian/Stuff/test/bug'
```

### Expected Output
```
/home/dian/Stuff/test/bug.nim(2, 6) Error: index 1 not in 0 .. 0
```

### Additional Information
Might be related to https://github.com/nim-lang/Nim/issues/14950.
Not a regression, I checked on older Nim versions and the behavior is the same at least since 0.16.0.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: b70e33f5bbb7b9c146c97d39aabae57504f4ee75
active boot switches: -d:release -d:danger
```

**Comment by ghost** [comment]
Relevant code - https://github.com/nim-lang/Nim/blob/devel/compiler/ccgexprs.nim#L930, it only triggers if optBoundsCheck is enabled. Not sure why that compile-time check is in the backend though :P

**Comment by Araq** [comment]
What makes you think that `a[1]` is not a runtime bounds check.
