### ISSUE TITLE
var doing same thing as let

### ISSUE THREAD

**Issue by drbuckleyjr** [nim-lang/Nim#17516]
Don't understand what difference there is between var and let in nim 1.4.4

What is difference between var and let? Documentation states there is a difference. What is the difference?

**Comment by zambrottahr** [comment]
variable declared with var are mutable while those declared with let are immutable.

**Comment by drbuckleyjr** [comment]
Yes, I wasn't careful enough in my remarks. It's not the value of a var that cannot change within a given scope, it's the type of a var that cannot change within a given scope. Example:
block a:
   var x: int = 10
   echo x  # displays 10
   var x: string = "abc"  # will cause an error because within the scope of the block a I have attempted to change the type
   x = "abc"  # will cause an error because I have attempted to change the type of x

It would be more correct to say that var permits (within a given scope) a value to be changed so long as it is of the same type
as the initial type for the variable within the scope.

**Comment by ghost** [comment]
@drbuckleyjr I'm not sure if we actually need to specify that - Nim is statically-typed, a variable can only have one type, it doesn't matter if you declare it with `var` or `let`

**Comment by SolitudeSF** [comment]
@drbuckleyjr this has nothing to do with mutability, you are not changing the type, you are redefining variable in the same scope, which you cant do.

**Comment by drbuckleyjr** [comment]
Thank you. It's clear now.
