### ISSUE TITLE
[doc] templates

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1755]
Few suggestions for the documentation of templates.

Overall, I would like more small examples (not like the gigant for generics), even incomplete. I can grok code snippets much faster and much more reliably than narrative.

---

_A template is a simple form of a macro: It is a simple substitution
 mechanism that operates on Nim's abstract syntax trees._
1. It has unintentional patronizing tone ("you must be idiot if you do not get it")
2. The term "macro" is unclear. Does it refer it C macros or the Nim macros described only later in the docs?
3. It gives no hint what does it do. Does it insert tokens into the code (ala C macro) or does it generate (inlinable) helper functions (ala C++ templates)?
4. Why should the reader care about templates? The docs already covered procs and generics, what is the difference and advantage? Every advanced feature should, IMHO, justify its existence to the reader.

---

_The syntax to invoke a template is the same as calling a procedure._
1. Example just bellow shows an operator. Why cannot it show the promised proc?

---

_< the first example >_ 
1. The very first example should be something trivial, w/o `stmt` and `expr`. Those words feel like magic, as if the feature is topic only for the wizzards.

---

_The "types" of templates ..._
1. It should be explained what return value means in text substitution. Whether one can return someting else than `expr` or nothing. What if I make a mistake (say always returning nothing), what would happen?
2. There should be example for every suggested type: stmt, expr, typedesc, "real type".
3. The sentences _These are "meta types", they can only be used in certain 
   contexts. Real types can be used too; this implies that expressions are 
   expected._ are vague on the level of medieval alchemists.

---

Section _Ordinary vs immediate templates_
1. Compiler lingo (_overloading resolution_) should not be used as familiar-to-everyone reference.
2. There should be example that shows how they differ. "This doesn't work, this does."
3. Is the new term (_ordinary_) really needed? Ordinary usually does not need to be stressed.
4. The ability to use undefined symbols should be explored a bit deeper. It can be quite suprising (e.g. the possibility to use unexported types). Use cases could be given.

---

Section _Passing a code block to a template_
1. Why does the name of local variable (f) need to be parameter? The template is intermediate (= unchecked), after all. 
2. Another example w/o `expr` would be handy, say executing given code block N-times.
3. Explicit attention could be drawn to the ability to automate the common init-action-deinit pattern.

---

Section _Symbol binding in templates_
1. This section reads as from a heavy-handed computer science textbook (binding, hygienic, mixin). I gave up trying to understand. Pairs of small examples would be better than the high jargon: (a) this doesn't work, (b) this fixes it.
2. Btw, **mixin keyword is not documented at all** (at least in 0.9.6 docs).
3. The hygiene is futher discussed in section down bellow. For me it makes it even more confusing.
4. The second section about hygiene recommends to use otherwise undocumented (as of 0.9.6) "dirty" pragma.

---

Section _Identifier construction_
1. This section is inserted into the middle of long talk about symbol binding. It seems unrelated.

**Comment by Araq** [comment]
Most of these things have been reworded.
