### ISSUE TITLE
./koch web fails on latest devel

### ISSUE THREAD

**Issue by boydgreenfield** [nim-lang/Nim#1757]
Here's the error message:

```
Hint: operation successful (1839 lines compiled; 0.009 sec total; 1.154MB) [SuccessX]
nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.10.1 --docSeeSrcUrl:master -o:web/upload/system.html --index:on lib/system.nim
system.nim(2547, 15) Info: instantiation from here
system.nim(1115, 15) Error: undeclared identifier: 'useSysAssert'
system.nim(2547, 15) Info: instantiation from here
system.nim(2547, 15) Info: instantiation from here
system.nim(1115, 14) Error: internal error: cannot generate code for: mDefined
```

This is as of 7d80a26b3fad2859208b3fd53f5fef61048d62c9, and goes at least a few days back (tested it on a slightly older fork). Will try to look into this in more detail later, but wanted to quickly record it here for now.

**Comment by ljgww** [comment]
nim c src/nimble
		config/nim.cfg(45, 2) Hint: added path: '/Users/lj/.babel/pkgs/' [Path]
		config/nim.cfg(46, 2) Hint: added path: '/Users/lj/.nimble/pkgs/' [Path]
		Hint: used config file '/Users/lj/dev/Nim/config/nim.cfg' [Conf]
		Hint: used config file 'src/nimble.nimrod.cfg' [Conf]
		Hint: system [Processing]
		lib/system.nim(3130, 31) Warning: unknown magic 'ProcCall' might crash the compiler [UnknownMagic]
		Hint: nimble [Processing]
		Hint: httpclient [Processing]
		Hint: net [Processing]
		Hint: rawsockets [Processing]
		Hint: unsigned [Processing]
		Hint: os [Processing]
		Hint: strutils [Processing]
		Hint: parseutils [Processing]
		Hint: times [Processing]
		Hint: posix [Processing]
		Hint: openssl [Processing]
		lib/wrappers/openssl.nim(522, 45) Hint: 'IOError' is declared but not used [XDeclaredButNotUsed]
		Hint: uri [Processing]
		lib/pure/uri.nim(30, 13) Warning: $ is deprecated [Deprecated]
		lib/pure/uri.nim(31, 11) Warning: $ is deprecated [Deprecated]
		lib/pure/uri.nim(45, 12) Warning: / is deprecated [Deprecated]
		Hint: strtabs [Processing]
		Hint: hashes [Processing]
		Hint: base64 [Processing]
		Hint: asyncnet [Processing]
		Hint: asyncdispatch [Processing]
		Hint: oids [Processing]
		Hint: endians [Processing]
		Hint: tables [Processing]
		Hint: math [Processing]
		Hint: macros [Processing]
		Hint: selectors [Processing]
		lib/pure/asyncdispatch.nim(1254, 6) Hint: Processing recvLine as an async proc. [User]
		stack trace: (most recent call last)
		lib/pure/asyncdispatch.nim(1288) async
		lib/pure/asyncdispatch.nim(1202) processBody
		lib/pure/asyncdispatch.nim(1331, 49) Info: instantiation from here
		lib/pure/asyncdispatch.nim(1202, 43) Error: index out of bounds
		Ljs-MacBook-Pro:nimble lj$ 

osx 1.6.8 / gcc
$ gcc --version
i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Araq** [comment]
> lib/system.nim(3130, 31) Warning: unknown magic 'ProcCall' might crash the compiler [UnknownMagic]

That's not "nim devel" then.

**Comment by ljgww** [comment]
Thanks! Noticed nim branch on github is devel. Therefore downloaded zip instead instead of prescribed 'git clone'. Recompiled nim from scratch (changed clang to gcc). Managed to compile koch and nimble. Seems to be working.

:) <- me happy!
