### ISSUE TITLE
Different results when computing at compile-time and at run-time

### ISSUE THREAD

**Issue by romstad** [nim-lang/Nim#17572]
In the following simple program (compiled with Nim 1.4.4), the assert in the final line fails:

```nim
type T = distinct uint64

func f(x: T): T =
  T(uint64(x) shl 63)

func `==`(x, y: T): bool {.borrow.}

const
  x = T(1'u64)
  y = f(x)

assert y == f(x)
```

The constant `y`, computed at compile-time, gets the incorrect value 0. When replacing the `const` with `let`, there is no error. 

This problem seems to be caused by the combination of a `distinct` type and unsigned 64-bit ints. Everything works as expected with `uint64` replaced by `int64` or `uint32` (shifting left by 31 rather than by 63 in the latter case), and also when using "plain" `uint64` instead of a `distinct` type.

(EDIT(timotheecour): originally reported in [Mysterious problem with shift left, uint64 and compile-time constants - Nim forum](https://forum.nim-lang.org/t/7717))

**Comment by shirleyquirk** [comment]
reducing further, the issue happens when converting from uint64 with high bit set to T in the VM
```nim
type T = distinct uint64

func `$`(x:T):string{.borrow.}
func f(x: uint64): T =
  result = T(x)
  debugecho "x: ",x, " res: ",result
func `==`(x, y: T): bool {.borrow.}

const
  x = 1'u64 shl 63 or 7
  y = f(x)
  z = T(x)#works as expected, only occurs inside a proc
discard f(x)
```
compiletime:
x: 9223372036854775815 res: 7
runtime:
x: 9223372036854775815 res: 9223372036854775815

**Comment by timotheecour** [comment]
## reduced a bit:
unrelated code affects correctness
```nim
when true:
  type T = distinct uint64
  func f(x: uint64): auto =
    let a = T(x)
    (x, a.uint64)
  const x = 1'u64 shl 63 or 7
  const b = T(x)
  static: echo b.uint64 # works
  static: echo f(x) # fails
  echo f(x) # works
```

ct:
9223372036854775815
(9223372036854775815, 7)
rt:
(9223372036854775815, 9223372036854775815)

## very strange:
```nim
when true:
  type T = distinct uint64
  func f(x: uint64): auto =
    let a = T(x)
    when defined caseOK:
      let b = cast[uint64](a)
    else:
      let b = 33
    (x, a.uint64, b)
  const x = 1'u64 shl 63 or 7
  const b = T(x)
  static: echo b.uint64 # works
  static: echo f(x) # fails
  echo f(x) # works
```

ct with -d:caseOK
9223372036854775815
(9223372036854775815, 9223372036854775815, 9223372036854775815)

ct without -d:caseOK:
9223372036854775815
(9223372036854775815, 7, 33)

**Comment by timotheecour** [comment]
=> PR https://github.com/nim-lang/Nim/pull/17586
