### ISSUE TITLE
crosscompile and --genScript:on : unsure which compiler is invoked

### ISSUE THREAD

**Issue by mikra01** [nim-lang/Nim#17575]
The project setup which I am talking about can be found here:

https://github.com/mikra01/nim_arm_template

I have multiple compilers (gcc) installed. The compiler "gcc" references to my host-compiler.
"arm-none-eabi-gcc" is my arm-crosscompiler.

I invoke the buildscript with "nim build_lpc2148 project.nims" within the projects directory "nim-arm-template" (where my
"project.nims" resides)

If I use the switch "--genScript:on" there is a file named "compile_main.sh" created. It has the following content:
```
gcc -c  -w -fmax-errors=3 -mcpu=arm7tdmi-s  -DROM_RUN -Os -Wl,--gc-sections -Wextra -Wcast-align -Wimplicit  -Wpointer-arith -Wswitch -Wredundant-decls -Wreturn-type -Wshadow -Wunused -Wa,-adhlns=main.lst   -Wcast-qual -MD -MP -MF  -Wnested-externs  -std=gnu99 -Wmissing-prototypes  -Wstrict-prototypes -Wmissing-declarations   -IC:\Users\mk\Nim\lib -IC:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src -o stdlib_io.nim.c.o stdlib_io.nim.c
gcc -c  -w -fmax-errors=3 -mcpu=arm7tdmi-s  -DROM_RUN -Os -Wl,--gc-sections -Wextra -Wcast-align -Wimplicit  -Wpointer-arith -Wswitch -Wredundant-decls -Wreturn-type -Wshadow -Wunused -Wa,-adhlns=main.lst   -Wcast-qual -MD -MP -MF  -Wnested-externs  -std=gnu99 -Wmissing-prototypes  -Wstrict-prototypes -Wmissing-declarations   -IC:\Users\mk\Nim\lib -IC:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src -o stdlib_system.nim.c.o stdlib_system.nim.c
gcc -c  -w -fmax-errors=3 -mcpu=arm7tdmi-s  -DROM_RUN -Os -Wl,--gc-sections -Wextra -Wcast-align -Wimplicit  -Wpointer-arith -Wswitch -Wredundant-decls -Wreturn-type -Wshadow -Wunused -Wa,-adhlns=main.lst   -Wcast-qual -MD -MP -MF  -Wnested-externs  -std=gnu99 -Wmissing-prototypes  -Wstrict-prototypes -Wmissing-declarations   -IC:\Users\mk\Nim\lib -IC:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src -o @mmain.nim.c.o @mmain.nim.c
gcc.exe   -o main  stdlib_io.nim.c.o stdlib_system.nim.c.o @mmain.nim.c.o   -mcpu=arm7tdmi-s   -specs=nano.specs -DROM_RUN  -Os -Wall -Wcast-align -Wimplicit  -Wpointer-arith -Wswitch -Wredundant-decls -Wreturn-type -Wshadow -Wunused  -Wcast-qual -MD -MP -MF Startup.o   --output main.elf -nostartfiles -lc  -lm -lc -lgcc -TROM.ld  

```

From my point of view the extra output is strange. If I invoke this shellscript, my host compiler is invoked. 
I would expect "arm-none-eabi-gcc" or "arm-none-eabi-gcc.exe" instead of "gcc" or "gcc.exe". 

### Additional Information
My compiler version is

```
Nim Compiler Version 1.4.4 [Windows: amd64]
Compiled at 2021-03-29
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2ff517462bf8609b30e6134c96658aa7912b628a
active boot switches: -d:release```

**Comment by timotheecour** [comment]
can you try passing `--gcc.exe:arm-none-eabi-gcc` or similar?
(see also config/nim.cfg)

**Comment by mikra01** [comment]
I modified now line 15 of my project.nims and added the flag "--gcc.exe:arm-none-eabi-gcc" but there is no change in behaviour. More funny if I pass a invalid compiler-name (see below) it still compiles... seems like that my host-compiler is invoked...
```
exec "nim c --gcc.exe:arm-none-eabi-bcc --verbosity:3 --listFullPaths:on --genDeps:on --genScript:on --cpu:arm --os:any --gc:arc --d:useMalloc --nimcache:../out/nimcache main.nim"
```
From a user perspective I thought I could override all flags of the parent configs (so given flags in my project's nim.cfg are overriding the parent ones). But it seems it's not the case...

Edit: to be clear - the nim.cfg of my nim-compiler installation is the original one (unchanged). I also made more tests: 
If I invoke the compilation step without the nimscript-task, i.e. 
```
C:\Users\mk\projects\github\nim_arm_template\nim_arm_template>nim c --verbosity:3 --listFullPaths:on --genDeps:on --genScript:on --cpu:avr --os:any --gc:arc --d:useMalloc --nimcache:../out/nimcache src/main.nim
```
with the flag "--cpu:avr" I would expect an error because I have no avr toolchain installed. But it still compiles.. (with my host compiler?). Still unsure about that.  btw, the --verbosity:3 flag is not suitable for debugging these kind of problems...

**Comment by mikra01** [comment]
I just glanced in commands.nim and there are some other flags (don't know the difference between --skipprojconf and --skipuserconf). When I add these flags, it still compiles (but it seems that the parent configs are not used anymore)
```
C:\Users\mk\projects\github\nim_arm_template\nim_arm_template>nim c --verbosity:3 --skipcfg --skipprojcfg --skipusercfg --skipparentcfg --listFullPaths:on --genDeps:on --genScript:on --cpu:avr --os:any --gc:arc --d:useMalloc --nimcache:../out/nimcache src/main.nim
........................................................................................................................
C:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src\main.nim(11, 7) Hint: 'cpyseq' is declared but not used [XDeclaredButNotUsed]
    let cpyseq = x
        ^
C:\Users\mk\Nim\compiler\lookups.nim(183, 18) compiler msg initiated here [MsgOrigin]
Hint: 11266 lines; 0.194s; 13.301MiB peakmem; Debug build; proj: C:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src\main.nim; out: C:\Users\mk\projects\github\nim_arm_template\out\nimcache\main.json [SuccessX]
C:\Users\mk\Nim\compiler\main.nim(395, 15) compiler msg initiated here [MsgOrigin]
[GC] total memory: 13946880
[GC] occupied memory: 11185200
[GC] stack scans: 844
[GC] stack cells: 4234
[GC] cycle collections: 0
[GC] max threshold: 0
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 89408
```

**Comment by timotheecour** [comment]
> Still unsure about that. btw, the --verbosity:3 flag is not suitable for debugging these kind of problems...

use `--listCmd --hint:cc --hint:link` and show results (these flags should show compile and link cmd at least on devel / 1.5.1 if not before); use `-f` to force rebuild to make sure those flags take effect

> don't know the difference between --skipprojconf and --skipuserconf). When I add these flags, it still compiles (but it seems that the parent configs are not used anymore)

did you see nim --fullhelp?
```
  --skipCfg:on|off          do not read the nim installation's configuration file
  --skipUserCfg:on|off      do not read the user's configuration file
  --skipParentCfg:on|off    do not read the parent dirs' configuration files
  --skipProjCfg:on|off      do not read the project's configuration file
```
(if that's not clear enough, feel free to suggest alternate wording)

it's very possible there's a bug, PR welcome :)

**Comment by timotheecour** [comment]
I think i can reproduce at least some of your problems:


```
nim r --clang.exe:/usr/bin/gcc --hint:cc --hint:link --listcmd -f --skipusercfg $timn_D/tests/nim/all/t12103.nim
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/config.nims' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/timn/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/timn/config.nims' [Conf]
....
CC: stdlib_assertions.nim: /usr/bin/gcc -c  -w -ferror-limit=3   -I/Users/timothee/git_clone/nim/Nim_devel/lib -I/Users/timothee/git_clone/nim/timn/tests/nim/all -o /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_assertions.nim.c.o /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_assertions.nim.c
CC: stdlib_system.nim: /usr/bin/gcc -c  -w -ferror-limit=3   -I/Users/timothee/git_clone/nim/Nim_devel/lib -I/Users/timothee/git_clone/nim/timn/tests/nim/all -o /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_system.nim.c.o /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_system.nim.c
CC: t12103.nim: /usr/bin/gcc -c  -w -ferror-limit=3   -I/Users/timothee/git_clone/nim/Nim_devel/lib -I/Users/timothee/git_clone/nim/timn/tests/nim/all -o /Users/timothee/git_clone/nim/timn/build/nimcache/@mt12103.nim.c.o /Users/timothee/git_clone/nim/timn/build/nimcache/@mt12103.nim.c
Hint: clang   -o /Users/timothee/git_clone/nim/timn/build/nimcache/t12103  /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_assertions.nim.c.o /Users/timothee/git_clone/nim/timn/build/nimcache/stdlib_system.nim.c.o /Users/timothee/git_clone/nim/timn/build/nimcache/@mt12103.nim.c.o  -lm -lm   -ldl [Link]
Hint: 47082 lines; 0.589s; 60.809MiB peakmem; Debug build; proj: /Users/timothee/git_clone/nim/timn/tests/nim/all/t12103.nim; out: /Users/timothee/git_clone/nim/timn/build/nimcache/t12103 [SuccessX]
Hint: /Users/timothee/git_clone/nim/timn/build/nimcache/t12103  [Exec]
```

=> link step doesn't honor `--clang.exe`

IMO we need a proper nim flags --compilerexe:exe, --linkerexe:exe, which would be invoked regardless backend (c or cpp), OS, etc. exe would be searched in PATH (could be absolute paths), and just be forwarded as is to linker and backend compilation commands

the current situation is not good, as those flags --clang.exe (mips.linux.gcc.linkerexe, amd64.windows.gcc.cpp.linkerexe, vcc.cpp.linkerexe etc) are platform/backend/compiler specific, violate DRY-ness, and not typesafe (no warning/error if misused)

@mikra01 would --compilerexe:exe --linkerexe:exe solve your problem?

**Comment by mikra01** [comment]
> --listCmd --hint:cc --hint:link

Thanks for the hint. But for 1.4.4 these flags do nothing - I am switching to devel now (need a few minutes).

> 
> did you see nim --fullhelp?

wasn't aware of it. I just glanced in "commands.nim" and thought I will get some clarification about these flags. Unfortunately there are not much comments in it :-).

> ```
>   --skipCfg:on|off          do not read the nim installation's configuration file
>   --skipUserCfg:on|off      do not read the user's configuration file

I assume now the User config is the nim.cfg within the user's working directory...

From my point of view there are too much flags with overlapping(?) building blocks around..

**Comment by mikra01** [comment]
> @mikra01 would --compilerexe:exe --linkerexe:exe solve your problem?

yep - that would be great. 

my output is now:
```
C:\Users\mk\projects\github\nim_arm_template\nim_arm_template>nim --version
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-03-29
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: ed126794b6af8b39960a7acc603cee1abc73da4a
active boot switches: -d:release

C:\Users\mk\projects\github\nim_arm_template\nim_arm_template>nim c --listCmd --hint:cc --hint:link --verbosity:3 --skipcfg --skipprojcfg --skipusercfg --skipparentcfg --listFullPaths:on --genScript:on --cpu:arm --os:any --gc:arc --d:useMalloc --nimcache:../out/nimcache src/main.nim
..........................................................................................................................
C:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src\main.nim(11, 7) Hint: 'cpyseq' is declared but not used [XDeclaredButNotUsed]
    let cpyseq = x
        ^
C:\Users\mk\Nim\compiler\lookups.nim(285, 18) compiler msg initiated here [MsgOrigin]
Hint: 11544 lines; 0.216s; 13.133MiB peakmem; Debug build; proj: C:\Users\mk\projects\github\nim_arm_template\nim_arm_template\src\main.nim; out: C:\Users\mk\projects\github\nim_arm_template\out\nimcache\main.json [SuccessX]
C:\Users\mk\Nim\compiler\main.nim(377, 15) compiler msg initiated here [MsgOrigin]
[GC] total memory: 13770752
[GC] occupied memory: 12463456
[GC] stack scans: 953
[GC] stack cells: 3900
[GC] cycle collections: 0
[GC] max threshold: 0
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 92320
```

unfortunately the output is still not beneficial... But according to the generated compiler's MASM output it seems that "arm-none-eabi-gcc" is invoked...

**Comment by mikra01** [comment]
It seem's that the flags "--listCmd --hint:cc --hint:link " are not functional on a windows host... 
And also I am unsure which linker is invoked. I will now test with "--noLinking:on" and invoke the linker manually as a workaround

**Comment by timotheecour** [comment]
> It seem's that the flags "--listCmd --hint:cc --hint:link " are not functional on a windows host...

--hint:link isn't shown probably because you're using genscript:
```
  of "genscript", "gendeps":
    if switch.normalize == "gendeps": deprecatedAlias(switch, "genscript")
    processOnOffSwitchG(conf, {optGenScript}, arg, pass, info)
    processOnOffSwitchG(conf, {optCompileOnly}, arg, pass, info)
```

> It seem's that the flags "--listCmd --hint:cc --hint:link " are not functional on a windows host...

"any sufficiently advanced compiler/program..."
clang --help|wc -l
     926
nim --fullhelp|wc -l
     202
man git | wc -l
    1440

number of flags isn't the problem, what matters more is their design/organization/orthogonality

> I assume now the User config is the nim.cfg within the user's working directory...

~/.config/nim/ on osx (https://nim-lang.github.io/Nim/os.html#getConfigDir / "nim")

**Comment by mikra01** [comment]
"--listCmd --hint:cc --hint:link" work as expected (without genscript option - this could be mentioned in the "compiler user guide"). don't like to introduce new features so I think this can be closed.
