### ISSUE TITLE
No overloading resolution with deprecated procs

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#1762]
See https://github.com/StefanSalewski/nim-cairo/

In src/cairo.nim

```
{.deprecated: [cairo_surface_destroy: destroy]
{.deprecated: [cairo_move_to: move_to].}
```

In test/test_png.nim

```
cairo_move_to(cr, 10.0, 50.0) # fine but twice deprecated warning: use move_to instead

destroy(cr)
#destroy(s) # fine
cairo_surface_destroy(s) # does not work: Error: type mismatch: got (Surface)
```

This is for Nim devel (bigbreak) built in November 2014 on Gentoo-Linux AMD64.

**Comment by StefanSalewski** [comment]
This bug is really ugly unfortunately. I just tried to convert a gtksourceview C example to Nim and discovered, that c2nim is really helpful for this task. But of course original proc names are preserved, and would even work if deprected list would work properly. But so I get

test_completion.nim(38, 20) Error: type mismatch: got (GList)
but expected one of: 
glib.next(iter: GSequenceIter)
glib.next(iter: GVariantIter, format_string: cstring)
glib.next(type: GVariantType)
glib.next(match_info: GMatchInfo, error: var GError)
glib.next(iter: GHashTableIter, key: ptr gpointer, value: ptr gpointer)

for this commented out line.
#selection = g_list_prepend(selection, prop.data)
selection = glib.prepend(selection, prop.data)

Of course converting it to the line above is not difficult, but unfortunately the error message is complete misleading. So other people may give up early.

**Comment by reactormonk** [comment]
See https://github.com/Araq/Nim/issues/2414 for some further information.

**Comment by Araq** [comment]
Now says "the .deprecated pragma is unreliable for routines"
