### ISSUE TITLE
rst: invalid use of admonition silently removes line

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17646]
/cc @a-mr 
just found this in docs https://nim-lang.github.io/Nim/iterators.html for `fieldPairs`, which were missing a line `This really transforms the 'for' and unrolls the loop. The` because docs used `.. warning:::` instead of `.. warning::`

### Example
```nim
iterator fieldPairs2*[T: tuple|object](x: T): tuple[key: string, val: RootObj] =
  ## Iterates over every field of `x` returning their name and value.
  ##
  ## .. warning::: This really transforms the 'for' and unrolls the loop. The
  ##   current implementation also has a bug that affects symbol binding in the
  ##   loop body.
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
Hola mundo!
```
![image](https://user-images.githubusercontent.com/2194784/113609743-0fd9d580-9601-11eb-987c-d071474c250b.png)

### Expected Output
if it's illegal in RST, give a CT error (simplest) or warning when running nim doc
if it's legal in RST, give a warning and probably render the skipped line as text

### Additional Information
1.5.1 70a30317f7b0a5711e248e0653b50d1c057bd16b

**Comment by a-mr** [comment]
Unfortunately `..` syntax is reused for comments in rst, so it's legal.

But I agree that a warning should be given. Especially easy is to input single `:` after a directive name instead of `::`.
