### ISSUE TITLE
segfault on trivial uncaught exception with `--exceptions:goto`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17647]
```nim
proc f() =
  if true: raise (ref ValueError)(msg: "hello")
f()
echo "again"
```

```
[arnetheduck@tempus tmp]$ nim c --exceptions:goto testit
[arnetheduck@tempus tmp]$ ./testit
Segmentation fault (core dumped)
[arnetheduck@tempus tmp]$ nim --version
Nim Compiler Version 1.4.4 [Linux: amd64]
Compiled at 2021-02-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2ff517462bf8609b30e6134c96658aa7912b628a
active boot switches: -d:release
```

Expected a backtrace..

**Comment by ghost** [comment]
FWIW works with `--gc:arc`

**Comment by arnetheduck** [comment]
> FWIW works with --gc:arc

that would seem orthogonal to the issue though? ie if `goto` is not supposed to work with the default gc, it shouldn't be selectable?

**Comment by beef331** [comment]
Suppose it's worth noting with `--newRuntime` and the default gc it does properly error, just missing stack trace, but I'd wager `goto` should imply `newRuntime`.
Output with `--exceptions:goto --newRuntime`:
```
                         
                         
Error: unhandled exception: hello [ValueError]
```

**Comment by ghost** [comment]
@arnetheduck why orthogonal? I just meant that it works with gc:arc, and arc uses goto exceptions by default too.

**Comment by arnetheduck** [comment]
> @arnetheduck why orthogonal?

orthogonal because.. it doesn't work with the default gc and arc doesn't generally work yet? as in, it looks like it's a separate feature from arc that can be used standalone (or if it isn't, it should be advertised as such rather that segfaulting - it's hard to trust a feature when trivial examples like this fail)

**Comment by Araq** [comment]
It's an orthogonal feature that has seen much testing with --gc:arc and not much with the default GC. Not ideal, but so far nobody has found a good way to tame exponential explosions.

**Comment by arnetheduck** [comment]
@Araq that   fix looks odd, given this bug.. how does raises affect the stack trace?

**Comment by Araq** [comment]
Tough to explain ... There must not be any "if error: goto ret" statements produced for this section:

```nim

proc reportUnhandledError(e: ref Exception) {.nodestroy.} =
  ...
  when hostOS != "any":
    ...
    var buf = newStringOfCap(2000)
    if e.trace.len == 0:
      rawWriteStackTrace(buf)
    else:
      var trace = $e.trace
      add(buf, trace)
      `=destroy`(trace)
    add(buf, "Error: unhandled exception: ")
```

And with my patch the compiler knows that `newStringOfCap` cannot raise. A different solution would have been:

```nim

proc reportUnhandledError(e: ref Exception) {.nodestroy.} =
  ...
  when hostOS != "any":
    let ex = currException
    currException = nil # we're handling this error here

    ...
    var buf = newStringOfCap(2000)

```

And maybe that would have been the better fix.
