### ISSUE TITLE
SSL certificate loading breaks after first found certificate

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#17658]
SSL certificate validation is currently failing on NetBSD.

Given the following code:

```nim
import httpclient

var client = newHttpClient()
echo client.getContent("https://github.com/nim-lang/packages/raw/master/packages.json")
```

The output is:

```
/home/euant/test_ssl/main.nim(4) main
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1161) getContent
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1156) get
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1083) request
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(988) requestAux
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(891) newConnection
/home/jenkins/workspace/Nim/lib/pure/net.nim(804) wrapConnectedSocket
/home/jenkins/workspace/Nim/lib/pure/net.nim(916) socketError
/home/jenkins/workspace/Nim/lib/pure/net.nim(518) raiseSSLError
[[reraised from:
/home/euant/test_ssl/main.nim(4) main
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1161) getContent
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1156) get
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(1083) request
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(988) requestAux
/home/jenkins/workspace/Nim/lib/pure/httpclient.nim(895) newConnection
]]
Error: unhandled exception: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [SslError]
```

However, the following commands all work so SSL is configured correctly:

```
ftp https://github.com/nim-lang/packages/raw/master/packages.json
```

```
curl https://github.com/nim-lang/packages/raw/master/packages.json
```

SSL certificates are installed via the `security/mozilla-rootcerts` package (`pkgin install mozilla-rootcerts && mozilla-rootcerts install`).

The `ssl_certs` module successfully finds the installed certificates in `scanSSLCertificates`, including the symlinked certificates.

The only possible cause I can see is that `net.newContext()` [seems to break](https://github.com/nim-lang/Nim/blob/04520c0ce4ed38a3fbae37731a4979480144c77b/lib/pure/net.nim#L657) on the first successfully found certificate? I'm not sure if this is intentional as I'm not well versed in the mysteries of OpenSSL.

**Comment by euantorano** [comment]
Note: it may be worth looking a how Go handles things, as the design seems similar:

- Paths: https://github.com/golang/go/blob/master/src/crypto/x509/root_bsd.go
- Loading certs: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/crypto/x509/root_unix.go#L34

**Comment by paulmr** [comment]
I also experienced this with Termux on android. Although the android certificate directory is listed in `ssl_certs.nim`, it tries to `yield` each file contained therein, and stops after the first one. Instead it should add the directory itself as the `caDir` parameter for the SSL context.

**Comment by euantorano** [comment]
I’ve updated the title of this issue, as I believe the logic is flawed as it currently stands and is likely also broken on other platforms as well.

**Comment by paulmr** [comment]
I did put together a fix but it is kind of a compromise because I didn't want to completely remove the existing behaviour in case it is useful. 

https://github.com/nim-lang/Nim/compare/devel...paulmr:ssl-cert-dir?expand=1

**Comment by ghost** [comment]
Any updates on this topic? The same problem also exists on OpenIndiana. I added the patch to the package, now it works fine here. It would be nice to have that fixed upstream anyways.

**Comment by Araq** [comment]
What is the patch? I'm happy to take it.

**Comment by ghost** [comment]
The link in the message above: https://github.com/nim-lang/Nim/compare/devel...paulmr:ssl-cert-dir?expand=1
