### ISSUE TITLE
The compiler optimizes out unused constants marked with the `exportc` pragma

### ISSUE THREAD

**Issue by japplegame** [nim-lang/Nim#17681]
The compiler must never optimize out constants marked with the `expotrc` pragma.
For example:
```nim
const foo {. exportc .} = 10
```
Expected C output:
```c
N_LIB_PRIVATE NIM_CONST NI foo = ((NI) 10);
```

Current output:
Nothing (optimized out)

**Comment by metagn** [comment]
This isn't optimized out, it's ignored. `exportc` should error on `const`. You should be using `let`.

**Comment by Araq** [comment]
No, `const` should work too.

**Comment by japplegame** [comment]
@hlaaftana, look in the corresponding thread: https://forum.nim-lang.org/t/7763
`let` does not guarantee that the initializing value will be evaluated at compile time and can be successfully placed in the`rodata ' section.

**Comment by PMunch** [comment]
If `exportc` should work for `const` then I would say `codegenDecl` should as well. Would probably solve my gripes with https://github.com/nim-lang/Nim/issues/17497

**Comment by auxym** [comment]
Adding on, if `exportc` should work on consts, then should we also be able to take the `addr` of a const, or at least an exported const? If so this is related to this RFC: https://github.com/nim-lang/RFCs/issues/257
