### ISSUE TITLE
Nim requires PATH to be set to work with external tools

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#1768]
As per request by dom96:

When running nim from external tools, the PATH to nim's /bin directory must be set. It is not sufficient to simply create a symlink to /bin/nim in the current PATH, i.e. /usr/local/bin. If PATH does not include nim's /bin directory, nim will try to import its core libraries from relative to the directory where the symlink is located at.

For example, when installing or running nimble without nim's /bin in the path, but a symlink to nim in /usr/local/bin, nim will try and fail to include /usr/local/lib/system.nim, etc.

**Comment by davidpelaez** [comment]
I have faced the exact same issue in OSX and I see the following alternatives to solve it:

* Use a wrapping script that always sets the `--path` option. 
* Increase the list of possible paths to look for for `nim.cfg`.
* Set a list of possible paths to resolve libraries by default.
* Rely on a environment variable, similar to what Golang uses with $GOPATH.

In any case whatever the solution it could be nice to actually display a more verbose error regarding what was tried and hence pointing out a clear solution for someone new.

Also, isn't it possible to bundle all this in the binary and hence removing entirely the need for extra files?

**Comment by davidpelaez** [comment]
@jpoirier is case it's any use I solved it placing the `lib` folder and `bin` folders in a common `nim` folder, e.g: `/usr/local/nim/0.13`. Then but the following script in `/usr/local/bin/nim`:

```bash
#!/bin/bash

# Actual path of the nim compiler
nim="/usr/local/nim/0.13/nim/bin/nim"

if [ -z "$1" ]; then
  # There were no args
  exec "$nim"
else
  # Take the first arg, the command and then append the path
  command="$1"
  shift # move all params to the right to remove the command
  exec "$nim" $command --path:"/usr/local/nim/0.13/nim/lib" $@
fi
```

That would take care of always adding the path to any command.

**Comment by Araq** [comment]
> Rely on a environment variable, similar to what Golang uses with $GOPATH.

I don't see how this can solve any problem, if people do not want to update their environment vars, they don't want to update their environment paths. This includes a hypothetical $NIMPATH (or should it be $NIM_PATH?)

**Comment by sjxxHero** [comment]
+1

**Comment by reactormonk** [comment]
I think an (optional) environment variable would make nim easier to package - just drop `$NIMPATH` into `/etc/profile.d/` and you're good to go.

**Comment by dom96** [comment]
> Perhaps the compiler could detect whether it's running via a symlink and follow that symlink to get its proper stdlib location.

Pretty sure this is still the best solution. Does anyone disagree?

**Comment by Araq** [comment]
> Pretty sure this is still the best solution. Does anyone disagree?

I think it already does that.

**Comment by dom96** [comment]
I tested this on Mac OS X and it looks like it is now working.
