### ISSUE TITLE
Range bounds in generics do not always compile

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#1771]
The following compiles and works as expected:

```
type
  Foo[X, T] = object
    bar: array[X, T]
```

However, this does not compile (fails to match X.low, X.high):

```
type
  Foo[X, T] = object
    bar: array[X.low..X.high, T]
```

Interestingly, this will compile and work though:

```
proc test[X, T](f: Foo[X, T]) =
  for i in X.low..X.high:
    echo f.bar[i]
```

But this doesn't compile (fails to match X.low):

```
proc test[X, T](f: Foo[X, T]) =
  echo f.bar[X.low]
```

All of the above instantiated with:

```
var a: Foo[range[0..2], float]
test(a)
```

I'm not 100% sure if I'm doing things wrong or have the wrong expectations wrt ranges, but this looks like a bug to me.

**Comment by Araq** [comment]
Still an issue. -.-

**Comment by metagn** [comment]
All compile in 2.0 (`low`/`high` were probably special cased for this way before though):

```nim
type
  Foo[X, T] = object
    bar: array[X.low..X.high, T]

proc test[X, T](f: Foo[X, T]) =
  echo f.bar[X.low]

var a: Foo[range[0..2], float]
test(a)
```

**Comment by gmpreussner** [comment]
Woohoo... time to check out 2.0 :)
