### ISSUE TITLE
Cannot overload generic types based on number of generic parms

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#1772]
The following will generate "Error: redefinition of 'Foo'"

```
type
  Foo[X] = object
    a: X

  Foo[X, Y] = object
    a: X
    b: Y
```

However, this works:

```
proc foo[X](a: X) = echo a
proc foo[X, Y](a: X, b: Y) = echo a, b

foo(2)
foo(2, 3)
```

**Comment by gmpreussner** [comment]
I don't remember the context in which I experimented with this, and looking at it now, I cannot think of a good use case for overloading types based on number of generic parameters. We should probably close this!?

**Comment by andreaferretti** [comment]
Agreed, I think it makes sense to close this - overloading generics seems a complex feature with no obvious use cases

**Comment by Araq** [comment]
Cool.
