### ISSUE TITLE
Dot operators with type mismatch, shows assertion instead of compiler error

### ISSUE THREAD

**Issue by jtiai** [nim-lang/Nim#17779]
The following code doesn't compile and causes unhandled exception:

### Example
```nim
{.experimental: "dotOperators".}

type
    Flag = enum
        A

    Flags = set[Flag]

template `.=`*(flags: Flags, key: Flag, val: bool) =
    if val: flags.incl key else: flags.excl key

var flags: Flags

flags.A = 123

```

### Current Output
```
....fatal.nim(53)            sysFatal
Error: unhandled exception: semcall.nim(233, 18) `nArg != nil`  [AssertionDefect]

```

### Expected Output
Compiler provides meanful error message or compiles.

### Possible Solution

If `flags.A = 123` is written as `flags.A = bool(123)` code compiles as expected.

```
$ nim -v
Nim Compiler Version 1.4.6 [Linux: amd64]
# make sure to include the git hash if not using a tagged release
```

**Comment by beef331** [comment]
As I mentioned in the realtime chat this is not due to the `bool`, it seems to be a dot operators with type mismatch bug.
This code shouldnt compile either, since you're passing an int as a bool and Nim doesnt implictly convert.
You can do the following and it'll work fine for you.
```nim
{.experimental: "dotOperators".}

type
    Flag = enum
        A

    Flags = set[Flag]

template `.=`*(flags: Flags, key: Flag, val: int | bool) =
    if val.bool: flags.incl key else: flags.excl key

var flags: Flags

flags.A = 123
```

**Comment by metagn** [comment]
Now gives

```
(14, 9) Error: undeclared field: 'A=' for type in.Flags [type declared in (7, 5)]
```

which seems reasonable?
