### ISSUE TITLE
Need for an alternative build on Windows for nim-1.4.6 zip release on nim-lang.org

### ISSUE THREAD

**Issue by m33m33** [nim-lang/Nim#17803]
The current official prebuilt binaries raises some false positive with a few antivirus, including avast, avg, mcafee.
Many .exe are affected, see [the forum thread](https://forum.nim-lang.org/t/7830)

A rebuild based on the 1.4.6 source tarball, mingw on windows 10 produces a nim.exe with zero false positives.

Prebuilt nim.exe: [virustotal report](https://www.virustotal.com/gui/file/169bf05dcb59eec41fe3bd1dfee311279185caa2a3ab301d040cd0ea4462bab5/detection)
Custom rebuild of nim.exe: [virustotal report](https://www.virustotal.com/gui/file/0ae603ded88d6e358fe8dce4d08ffb045b3db503e259c47f040b2ab89ff5ba88/detection)

I suggest 

- an alternative rebuild of the official binaries, to clear any doubt (yes, false positives, but this is not good for acceptance)
- some enlightment on the current build environment for official binaries (for comparaison, reproductibility)

**Comment by Araq** [comment]
For the enlightenment:  

 https://github.com/nim-lang/nightlies/

https://github.com/nim-lang/nightlies/releases/tag/2021-04-15-version-1-4-2b6b08032348939e5d355a6cb4faa0169306c17f

**Comment by m33m33** [comment]
Thanks, ok so the release zip is just the product of the nightly tool chain. I thought it would be compiled in a production environment, but I am a bit old fashioned.

I will look if I can reproduce the build here, and if minor tweaks helps avoiding false positives.

**Comment by m33m33** [comment]
> I will look if I can reproduce the build here, and if minor tweaks helps avoiding false positives.

Well, looking at the build logs, the windows binaries are built on "Microsoft Windows Server 2019", that I can't reproduce here.

As the current (1.5.1) nightly build does not produce false positive, like previous binaries (1.4.0 and so on) : I guess it's just bad luck to have the 1.4.6 binaries flagged as false positive, and better to wait for the next release build to be pulled off nightlies :/
