### ISSUE TITLE
Custom mySeq in Move Semantics documentation has a bug

### ISSUE THREAD

**Issue by btcross26** [nim-lang/Nim#17822]
The custom sequence laid out in the move semantics document [here](https://nim-lang.org/docs/destructors.html) does not work as expected.

### Example
After copying the custom sequence code, if I include the following...

```nim
discard createSeq[int](0, 1, 2, 3, 4)
```

### Current Output
Compiling the copied custom sequence with the above discarded value leads to a compilation error:

```bash
Error: type mismatch: got <int>
but expected one of:
proc `=destroy[T](x: var T)
  first type mismatch at position: 1
  required type for x: var T
  but expression 'x[I]' is immutable, not 'var'
proc `=destroy`[T](x: var myseq[T])
  first type mismatch at position: 1
  required type for x: var myseq[=destroy.T]
  but expression 'x[I]' is of type: int
```

### Expected Output
Successful compilation.

### Possible Solution

* This happens because the overloaded indexing operator returns a 'lent' value that is immutable. Changing the return type to a `var` allows compilation, i.e.,
    * This causes the compilation error due to lending:
        ```nim
        proc `[]`*[T](x: myseq[T]; i: Natural): lent T =
          assert i < x.len
          x.data[i]
        ```
    * This will compile with return type changed to var:
        ```nim
        proc `[]`*[T](x: myseq[T]; i: Natural): var T =
          assert i < x.len
          x.data[i]
        ```

### Additional Information
After changing the above, if I add the following to the file:

```
var a: mySeq[int] = createSeq[int](0, 1, 2, 3)
`=destroy`(a)
echo $a[1]
```
I get a successful compilation that errors out running the executable with bash "Input/output error on the first run.
If I run again, I get the printout of `1`, which I assume means that the memory was accessed, followed by a traceback ending in:
```bash
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Should this be caught during compilation?

```
$ nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
```

**Comment by ringabout** [comment]
It should be fixed on devel already.

see https://nim-lang.github.io/Nim/destructors.html

**Comment by btcross26** [comment]
Got it. Thanks! The above works. So the better fix was in modifying the destructor to operate on the data attribute of the seq, avoiding the need to change the 'lent' return type.

**Comment by ringabout** [comment]
So I assume this issue can be closed :)
feel free to reopen it if not. 

Maybe document should be backported?
