### ISSUE TITLE
`yield in expr not lowered` on `case await`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17849]
fails with both asyncdispatch / chronos

```nim
import asyncdispatch
proc f*() {.async.} =
  case await newFuture[bool]()
  of true: discard
  of false: discard

discard f()
```

```
Error: internal error: yield in expr not lowered
```

nim 1.2.6, 1.4.4

**Comment by ringabout** [comment]
Related https://github.com/nim-lang/Nim/issues/13583

**Comment by arnetheduck** [comment]
yeah, saw that one, though here we're actually consuming the (fictive) return value from "await"

**Comment by dom96** [comment]
The workaround here is easy (just assign the `await` expression to a variable). Personally I think that unless fixing this is really trivial we should deprioritise it, Nim is already extremely flexible when it comes to where you can `yield`.

**Comment by arnetheduck** [comment]
I'm not sure I understand - are you saying it's acceptable that the compiler crashes with an unintelligible message on a seemingly valid construct? I mean, I found what the issue was only because I've worked around lots of similar bugs in the past, but these kind of problems are extremely hard to diagnose and we lose lots of time and manpower over them.
