### ISSUE TITLE
Compiler json dump inserts invalid json character at end of output

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/Nim#17853]
This is causing the nim vim plugin to throw an error every time a Nim file is opened.

### Example

```nim
# x.nim
echo "Hello World!"
# Compile with `nim --dump.format:json --verbosity:0 dump x.nim > out.json`
```

### Current Output

<img width="821" alt="Screen Shot 2021-04-25 at 5 22 31 PM" src="https://user-images.githubusercontent.com/2645657/116012997-f4079500-a5ea-11eb-883d-5ec3ab906401.png">

### Expected Output

<img width="829" alt="Screen Shot 2021-04-25 at 5 24 06 PM" src="https://user-images.githubusercontent.com/2645657/116013019-100b3680-a5eb-11eb-85d5-72dc3e119bfc.png">

### Possible Solution

Seems to be something from [this PR](https://github.com/nim-lang/Nim/pull/17730) after investigating using git bisect.

```
Nim Compiler Version 1.5.1 [MacOSX: arm64]
Compiled at 2021-04-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9e6f2d7d186f760d8eb7dc26c863f23bd044b9c9
active boot switches: -d:release
```

**Comment by xflywind** [comment]
Another issues which seems to be a regression
```nim
proc log(x: cstring) {.importjs: "console.log(#)".}
```


![image](https://user-images.githubusercontent.com/43030857/116027464-8cebee00-a687-11eb-9aa3-44b35d5d433f.png)

**Comment by timotheecour** [comment]
I was going to report the same issue:
`nim dump --dump.format:json . | jq -r .nimExe` now fails after that PR
