### ISSUE TITLE
Documentation of stripLineEnd says "returns" but it transforms the string in-place

### ISSUE THREAD

**Issue by mkrieger1** [nim-lang/Nim#17878]
https://nim-lang.org/docs/strutils.html#stripLineEnd%2Cstring (generated 2021-04-15 08:26:21) says:

> ```nim
> proc stripLineEnd(s: var string) {...}
> ```
> Returns `s` stripped from one of these suffixes: ...

But it doesn't return a modified string. It modifies it in-place which was surprising to me because I couldn't pass an immutable string.

Either the procedure should be changed to return the modified string, or the documentation should make this more clear.

**Comment by ringabout** [comment]
Nice catch! PR is welcome.

**Comment by timotheecour** [comment]
yes @mkrieger1 please make a PR, thanks!
