### ISSUE TITLE
Sophos thinks 1.4.6 has a virus

### ISSUE THREAD

**Issue by sigzero** [nim-lang/Nim#17877]
See the upload screenshot. I just download 1.4.6 today off the Nim website links. False positive?

![screenshot](https://user-images.githubusercontent.com/540937/116302617-6903d780-a76f-11eb-922a-e52c60dede06.png)

**Comment by ringabout** [comment]
see https://forum.nim-lang.org/t/7830

Duplicate of https://github.com/nim-lang/Nim/issues/17820
