### ISSUE TITLE
After update to 1.4.6, Windows thinks an executable from nim is a Trojan (finish.exe)

### ISSUE THREAD

**Issue by EriKWDev** [nim-lang/Nim#17886]
### Example
![image](https://user-images.githubusercontent.com/19771356/116463266-c892dd80-a86a-11eb-9517-e89b8c702347.png)

### Current Output
Windows thinks an executable from nim is a trojan?

### Expected Output
Windows shouldn't think that an executable from nim is a trojan

### Additional Information
I used choosenim to upgrade to 1.4.6 from 1.4.4 today and I got this.
Windows provides this [Learn more](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Phonzy.A!ml&threatid=2147772966) link.

```
> nim -v
Nim Compiler Version 1.4.6 [Windows: amd64]
Compiled at 2021-04-15
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by EriKWDev** [comment]
nimsuggest as well?
![image](https://user-images.githubusercontent.com/19771356/116463849-7e5e2c00-a86b-11eb-9195-2a7f03c57188.png)

**Comment by SolitudeSF** [comment]
duplicate #17877 #17820

**Comment by EriKWDev** [comment]
Didn't see! Sorry. Should I close this one in favour of those?

**Comment by EriKWDev** [comment]
Closing as duplicate.
