### ISSUE TITLE
Pakku build issues from fix #16651 (#16658)

### ISSUE THREAD

**Issue by zqqw** [nim-lang/Nim#17880]
https://github.com/zqqw/pakku/issues/9

Bisecting, it seems to have been introduced by this:
commit 0286a0879bc44e5267a5fd36e6f4aac8f78713ea (HEAD)
Author: cooldome <ariabushenko@gmail.com>
Date:   Mon Jan 11 09:09:38 2021 +0000
    fix #16651 (#16658)
    * fix #16651

Any suggestions to fix it appreciated, it seems to be confusing some complex closure usage, I can probably rewrite that section but maybe there's a quick way, or perhaps this is useful to highlight here as a Nim issue.

**Comment by shirleyquirk** [comment]
reduction:
```nim
proc foo(): (int,proc) = (5,proc {.closure.} = discard)
```
workaround:
```nim
proc foo(): (int,proc()) = (5,proc {.closure.} = discard)
```

**Comment by zqqw** [comment]
It looks like the problem commit isn't exactly the problem, rather it reveals that particular code section is getting wrongly flagged as being a tuple.

**Comment by shirleyquirk** [comment]
regression is the same for any typeclass, naturally, e.g.
```nim
proc foo: (SomeNumber,) = (3,)
```

**Comment by shirleyquirk** [comment]
@zqqw in the pakku code the return type is indeed a tuple, specifically (proc(a,b:int),typeclass[proc]). am i missing your point?

but you're right, seeing as how it's not just tuples that cause the issue, there's another instantiation bug here somewhere

**Comment by shirleyquirk** [comment]
ok, digging deeper:

```nim
proc foo: SomeNumber = 3
```
has always worked

anything containing a typeclass has never worked, e.g.
```nim
proc foo: seq[SomeNumber] = @[3] #Error  cannot instantiate: 'SomeNumber'
```
the exception was tuples, as they were broken and didn't turn the proc generic.

**Comment by zqqw** [comment]
Yes, it is a tuple after all, you are correct, there are several ways to declare them. I was just generally wondering if it was possible to fix this in Nim before 1.6 is released, when this would break regular pakku not pakku-git and it might take a while to get a reply from kitsunyan. It seems to be usually considered valid to declare procs without needing () parentheses although mostly people use them anyway.

**Comment by shirleyquirk** [comment]
i'm working on a fix to allow inferring composite return types containing typeclasses.  

but don't worry about 1.6, that bird has sailed.
pakku v0.14 already doesn't compile with 1.4.6 (no 'lc') 
and pakku-master doesn't compile either, with:
`pakku/src/feature/syncinstall.nim(912, 49) Error: 'p' is of type <lent PackageInfo>`

maybe we can vote to remove pakku from the aur, then replace it with pakku-git. i don't know.
> Say hello to stillborn AUR helper written in stillborn programming language!

That tagline seemed cutely ironic when i first read it, but now it's just infuriating.

**Comment by zqqw** [comment]
From what I gather reading GitHub and various comments on issues, kitsunyan may be not using an Arch based distro as a main OS now, and is concentrating on other things, and also finds it generally difficult to switch back to old projects.
Myself, I use pakku constantly and there is nothing to match it's capabilities, so I have a great incentive to keep it working.
I think the AUR might resolve that itself if it's left unmaintained, it would eventually be flagged as out of date.
And what are the changes in your Pakku patch in src/format.nim for? They seem unrelated to the build error issue?

**Comment by shirleyquirk** [comment]
maybe we can take this off the nim tracker, i'll respond to you on that pull request

but insofar as it's relevant to preventing breaking code when updating Nim:

the other break was that passing `('a','b')` as an untyped argument to a macro used to be nnkPar and now it's nnkTupleConstr, breaking macros that depended on the previous behaviour.
mwe:
```nim
import macros
macro foo(s:untyped) =
  assert s.kind == nnkPar
foo((1,2))
```

**Comment by metagn** [comment]
The reduction seems to work, can this be closed, or do we need to add a test case (though there might be one already)?
