### ISSUE TITLE
nim doc shows symbols in random/non-intuitive order, should be sorted

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17910]
as reported in https://forum.nim-lang.org/t/7894:

> Take https://nim-lang.org/docs/system.html as example. pop is first item in left side Procs list, and `not` is the first item in right side. Moreover, both of them are not first proc in the source.

I agree, and we should show them in sorted order; the ordering in the code is usually not relevant and result of historical artifacts / lack of `codeReordering`.

### Additional Information
1.5.1 34a09574ce4fd95a859d61ec234c37591e319e03

**Comment by zetashift** [comment]
I'd be interesting picking this up, seems doable(hopefully :P)!

Am I right that I need to look somewhere in this proc: https://github.com/nim-lang/Nim/blob/8f79bc5f3dfdfd13ef6be1fbcb300872931801f8/lib/packages/docutils/rstgen.nim#L820 to sort the entries?

**Comment by timotheecour** [comment]
@zetashift sounds reasonable but you'll have to give it a try :)

also this only addresses the TOC (ie, left side) not the main declarations (ie right side); which is fine for starters

**Comment by timotheecour** [comment]
@a-mr does your 2-pass rst processing make this easier?

**Comment by a-mr** [comment]
@timotheecour ,

not sure, at least for TOC it appears not related as it could already be processed in `genSection`.

But some refactoring with saving strings to data structures (in the same vein as 2-pass) is needed anyway.
