### ISSUE TITLE
testament give `reInvalidSpec` (wrongly treats code as testament spec); and: testament spec can silently be ignored

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17952]
I've hit this a few times:

### Example 1
add a test `tests/misc/tfoo.nim` containing:

```nim
const a = """
ok
"""
doAssert a.len > 0
```

XDG_CONFIG_HOME= nim r testament/testament.nim r tests/misc/tfoo.nim

### Current Output
```
FAIL: tests/misc/tfoo.nim c
Test "tests/misc/tfoo.nim" in category "misc"
Failure: reInvalidSpec
Expected:


Gotten:
invalid key for test spec: ok
```

### Expected Output
works

## Example 2
self explanatory; turns out `extractSpec` is hacky and buggy:
```nim
# here is a comment; if this line exceeds 40 chars, only c target will run!

discard """
targets: "c js"
"""

echo (defined(js), defined(c))

```

### Additional Information
1.5.1 34625f2202354bcd5fe917760ad88bc88d43a1dc

**Comment by Araq** [comment]
> turns out extractSpec is hacky and buggy

Yeah. I sometimes wonder why I did it this way. I'm sure I had my reasons but it just makes no sense...
