### ISSUE TITLE
array[uint8, uint8] vs array[256, uint8]

### ISSUE THREAD

**Issue by amnr** [nim-lang/Nim#17958]
Hi, I've encountered weird bug when using 'uint8' for array size.

This works:

```nim
var mem: array[256, uint8]
let val = 0xffff'u16
echo mem[uint8 val]
```
This produces IndexDefect:

```nim
var mem: array[uint8, uint8]
let val = 0xffff'u16
echo mem[uint8 val]   # Error: unhandled exception: index 65535 not in 0 .. 255 [IndexDefect]
```

**Comment by Menduist** [comment]
This actually works:
```nim
var mem: array[uint8, uint8]
let
  val = 0xffff'u16
  valu8 = uint8 val
echo mem[valu8]
```
So the cast seems to be ignored inside the brackets for some reason

**Comment by amnr** [comment]
Casting with cast[]() works too:

```nim
var mem: array[uint8, uint8]
let val = 0xffff'u16
echo mem[cast[uint8](val)]
```

**Comment by Clyybber** [comment]
It's because the conversion is done at compile time and behaves differently there.
Probably we should get rid of that difference or restrict it to "direct" literals.

**Comment by Menduist** [comment]
```nim
let val = 0xffff'u16
let valu8 = uint8 val
```
Fails CT (eg, in a static block), works in RT
```nim
let val = 0xffff'u16
let valu8 = int8 val
```
Fails both at CT & RT

So my understanding is that the uint8 conversion should also fail at RT
EDIT: Clyybber pointed out that is is actually documented behaviour, and I guess it would be error prone to let this kind of conversion happen at CT?

**Comment by metagn** [comment]
`transf` straight up skips conversions for array indices: https://github.com/nim-lang/Nim/blob/3e47725c08b42515d17d77b3a6c9cc3029e5681c/compiler/transf.nim#L870
