### ISSUE TITLE
isNilOrWhitespace still in documentation for strutils, not even deprecated, though removed in 1.4.0

### ISSUE THREAD

**Issue by randycread** [nim-lang/Nim#17966]
I don't know if the removal was wrong or the documentation.  I ran into this with the nimgraphviz module which was unusable for me because of this.

**Comment by timotheecour** [comment]
can't reproduce, not in https://nim-lang.github.io/Nim/strutils.html

searching `isNilOrWhitespace` returns only this:
changelogs/changelog_1_4_0.md

**Comment by randycread** [comment]
Sorry, I was looking at 1.0.6 strutils doc.  But nimgraphviz is still using it.
