### ISSUE TITLE
Allow better optimization for the Intel C compiler to target Xeon Phi

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1797]
I've converted some C code to Nim to use the full speed of the Xeon Phi. I can reach the memory bandwidth of 140 GB/s out of the box with Nim: https://github.com/def-/nim-mic/blob/master/hellomem.nim

```
$ ./hellomem 
Initializing
Starting BW Test on on 240 threads
GBytes = 1073.741824, Secs = 7.847460985183716
GBytes per sec = 136.8266533630766
```

Unfortunately getting 2 TFlops/s does not immediately work: https://github.com/def-/nim-mic/blob/master/helloflops.nim

There are 2 reasons for this:
1. Variables inside a "pragma omp parallel for" are shared between all threads by default. If you create a loop inside, the loop variable will be shared between all threads, as Nim declares the variable outside of the loop. The declaration would have to happen inside the loop, then the variable is automatically private. Alternatively all variables that are generated by the compiler could be set to be private in such loops. The j and k are the problem here: https://gist.github.com/def-/64f10c359a6962e06d75/c7034f115027dd4e8db76a037454c075aeee3008#file-helloflops-c-L127
2. icc needs to be able to analyze the loop to auto-vectorize it. This works well with C's _for_ loops, but Nim uses _while(1)_ loops with a goto to exit them instead, which throws icc off. There is already code in the compiler to transform _||_ loops to C _for_ loops. The same should be applied to regular for loops where it is possible. (simple counts for example)

I've applied the necessary changes to the emitted C code by hand: https://gist.github.com/def-/64f10c359a6962e06d75/revisions

```
$ ./helloflops                              
Initializing
Starting Compute on 240 threads
GFlops = 6143.99951171875, Secs = 3.235508918762207
GFlops per sec = 1898.92831884674
```

```
```

**Comment by Araq** [comment]
Would it help to use the while condition instead of a goto exit? That might be easier to generate than transforming it into a 'for', I think.

**Comment by Bulat-Ziganshin** [comment]
When I first tried Nim in 2014, I also found that it can't generate code as efficient as C because it generates `while` loops that GCC cannot unroll. So, this is general issue for HPC code, even for usual CPUs and scalar single-threaded code. I think I should go with example to show how it limits the speed.

**Comment by ringabout** [comment]
> When I first tried Nim in 2014, I also found that it can't generate code as efficient as C because it generates `while` loops that GCC cannot unroll. So, this is general issue for HPC code, even for usual CPUs and scalar single-threaded code. I think I should go with example to show how it limits the speed.

Now Nim compiler added `unroll` supports(see https://github.com/nim-lang/Nim/pull/16472):

```nim
iterator unroll*[S, T](a: S, b: T, annotation: static string): T {.
  inline, magic: "OmpParFor", sideEffect.} =
  discard

template unroll*(a, b: SomeInteger; unroll: static Positive = 4): untyped =
  when defined(gcc):
    system.unroll(a, b, "GCC unroll " & $unroll)
```

then

```nim
for i in unroll(0, 20, 4):
  echo i
```

Generates C codes:

```c
#pragma GCC unroll 4
for (i = ((NI) 0); i <= ((NI) 20); ++i)	{
		tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
		nimZeroMem((void*)T2_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T2_[0] = nimIntToStr(i);
		echoBinSafe(T2_, 1);
	}
```

**Comment by mratsim** [comment]
Such a hack :O

**Comment by planetis-m** [comment]
Still, these while (1) loops break clangs ability to perform auto vectorization. Random output with -t:"-Rpass-analysis=loop-vectorize":

```
remark: loop not vectorized: could not determine number of loop iterations [-Rpass-analysis=loop-vectorize]
                        while (1) {
remark: loop not vectorized: instruction cannot be vectorized [-Rpass-analysis=loop-vectorize]
                                if (!(i_5 < ((NI) 10000))) goto LA30;
remark: loop not vectorized: value that could not be identified as reduction is used outside the loop [-Rpass-analysis=loop-vectorize]
                        while (1) {
```

**Comment by Araq** [comment]
9 years later optimizers might have improved.

**Comment by mratsim** [comment]
Actually Intel cancelled research into Xeon Phi and produced actual GPUs (Intel Arc).
