### ISSUE TITLE
The `std/json` doesn't support `ref variant` object

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#17975]
The `std/json` converts `ref variant` object to JSON, but fails to parse it.

[playground](https://play.nim-lang.org/#ix=3mei)

### Example
```nim
import json

type User = ref object
  case is_anon: bool
  of true:
    source_id: int
  of false:
    email: string

let data = User(is_anon: true, source_id: 1).`%`.`$`
echo data
echo data.parse_json.to(User).repr # <== Error
```

### Current Output
```
Error: unhandled exception: key not found: .email [KeyError]
```

```
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by timotheecour** [comment]
try std/jsonutils

**Comment by al6x** [comment]
Thanks, I like the new API, closing the issue.

One possible improvement, adding ability to specify options in `jsonTo`, like

```Nim
proc jsonTo*(json: JsonNode, T: typedesc, options: Joptions): T =
  fromJson(result, json, options)
```

**Comment by timotheecour** [comment]
@al6x what do you mean? that's already the case:
```nim
proc jsonTo(b: JsonNode; T: typedesc; opt = Joptions()): T:type
```

**Comment by al6x** [comment]
Hmm, maybe I have older version of `std/jsonutils`, as I have different version of `jsonTo` in sources (see below). Please ignore my suggestion then, as it's already implemented.

```
proc jsonTo*(b: JsonNode, T: typedesc): T
```
