### ISSUE TITLE
Add a warning or notification to "nimrod compile --run" when certain .nim files are compiled

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#180]
Hi,

On IRC I was told to not name my file system.nim, as this will conflict with nimcache/ or something like that.

This is fine, renaming it to system2.nim is a workaround.

I think, however, it would be more convenient for the user, if the above command, nimrod compile, could give a warning that it is unwanted to have a file called system.nim (as long as this limitation exists, at least, and the file in question is called system.nim or any other name that would conflict with the content of nimcache/).

That way, a user could be told that this is not expected to work.

Example for output to the user could be:

"Please do not name your file system.nim. This is currently not supported."
"It is suggested to rename the file instead." (or another workaround here. Reason could also be given why this does not work)

**Comment by narimiran** [comment]
@flaviut I see that you've been working on this 4 years ago, but from what I can tell, nothing has been merged — naming your file `system.nim` still produces an error:

```
/usr/bin/ld: /home/miran/.cache/nim/system_d/stdlib_system.c.o: in function `systemDatInit000':
stdlib_system.c:(.text+0xe181): multiple definition of `systemDatInit000'; /home/miran/.cache/nim/system_d/compiler_system.c.o:compiler_system.c:(.text+0x23e): first defined here
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o /home/miran/Documents/programming/nim/Nim/system  /home/miran/.cache/nim/system_d/compiler_system.c.o /home/miran/.cache/nim/system_d/stdlib_system.c.o    -ldl'
```

> This should be an error I think. I'm not sure if it's possible though, as the compiler has to compile the system.nim that is imported implicitly.

What's the plan with this issue? (It is one of the oldest still open issues)

**Comment by Araq** [comment]
> What's the plan with this issue? (It is one of the oldest still open issues)

We ... fix it? I hope to support it, no error message, it just works.

**Comment by Araq** [comment]
Now works.
