### ISSUE TITLE
significant performance difference between `openArray` and `seq` as argument type

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#18005]
there are significant performance difference with following `proc`s that just differ in argument type

### Example
```nim
import sequtils
import benchy

proc doWithOpenArray[T](a: var openArray[T]) =
  for i in 0..<a.len:
    discard a[i]

proc doWithSeq[T](s: var seq[T]) =
  for i in 0..<s.len:
    discard s[i]

var s1 = newSeqWith(100000000, 0)
  
timeIt "do something With OpenArray":
  s1.doWithOpenArray
  
timeIt "do something With Seq":
  s1.doWithSeq

```

### Current Output
significant performance difference
```
name ............................... min time      avg time    std dv   runs
do something With OpenArray ...... 222.087 ms    227.084 ms    ±3.073    x22
do something With Seq ............ 287.518 ms    326.428 ms   ±68.706    x16
```

### Expected Output
no performance difference

### Possible Solution
* maybe checking the generated C code could help

### Additional Information
nim compiler version: 1.4.6
os: windows 10

**Comment by beef331** [comment]
Difference disappears with `--newRuntime` (or ofcourse using arc/orc which imply that). Based off the speed I believe you were not benchmarking with `-d:release` which is pretty important as it enables more optimizations.

**Comment by hamidb80** [comment]
I used ` -d:release` actually.

**Comment by Araq** [comment]
> Expected Output
> no performance difference

I would expect an output difference, `var seq` is one indirection more than `var openArray`, you pay for the possibility that `var seq` can grow. However, you're right in that the optimizer should hoist the additional load out of the loop.

**Comment by timotheecour** [comment]
please check whether this is a duplicate of https://github.com/nim-lang/Nim/issues/14909

**Comment by hamidb80** [comment]
> please check whether this is a duplicate of #14909

yeah , it's duplicated

**Comment by hamidb80** [comment]
> possibility that `var seq` can grow ... the optimizer should hoist the additional load

I Think with adding `GrowthEffect` effect to the functions that can possibly cause grows of the data, the detection of such situations is gonna be simple
