### ISSUE TITLE
Nim error msgs and hints have a weird character at the end

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#18058]
Sometime back, error msgs and hints were modified to include a non-printable character at the end for easy use from tools. However, the character is displayed on cmd/windows terminal/cmder atleast.
It would be good if those characters can be moved behind a switch or something.

### Example
![image](https://user-images.githubusercontent.com/43749640/119155231-955dfb80-ba70-11eb-8f90-230ecd04610a.png)

### Nim version
```
git hash: 9f7e2e30573a377770fa630f12a47bac09751282
```

**Comment by Araq** [comment]
When I brought it up @Clyybber assured me these would be invisible. :P

**Comment by Clyybber** [comment]
Heh, I guess we should provide an option to disable them for those outlier fonts/configurations :D

**Comment by juancarlospaco** [comment]
I see it on GitHub Actions and VS Code. :slightly_smiling_face:

**Comment by timotheecour** [comment]
> Heh, I guess we should provide an option to disable them for those outlier fonts/configurations :D

that's what the earlier version of https://github.com/nim-lang/Nim/pull/17887 was doing, should we revisit it then?
refs https://github.com/nim-lang/Nim/pull/17887#issuecomment-829023900

(see 1st commit: https://github.com/nim-lang/Nim/pull/17887/commits/2368f700e4a6f2d5bc1232c4006303b74312ddb1)

**Comment by Varriount** [comment]
> 
> 
> Heh, I guess we should provide an option to disable them for those outlier fonts/configurations :D

@Clybber I'm getting them with the stock settings on both Windows terminal and the command prompt. Unfortunately, not outliers.

**Comment by kaushalmodi** [comment]
@Clyybber 

>  I guess we should provide an option to disable them for those outlier fonts/configurations

Instead, shouldn't the invisible chars be disabled by default, and only the tools that need those enable those with a switch?

**Comment by timotheecour** [comment]
I agree, this should be opt-in, not opt-out (most common use is directly on command line, where you don't want to see those; use in tooling is not the most common use case for displayed messages

**Comment by timotheecour** [comment]
see also https://github.com/nim-lang/Nim/issues/18143, which is also suggesting making UnitSep opt-in
