### ISSUE TITLE
Compiler doesn't catch Not nil annotation error

### ISSUE THREAD

**Issue by gavr123456789** [nim-lang/Nim#18073]
Link to code example: https://nim-lang.org/docs/manual_experimental.html#not-nil-annotation  
Not initialized object passed to not nil type parameter.  
### Example
```nim
import sugar
{.experimental: "notnil"}

type
  TObj = ref object not nil
  PObject = ref TObj not nil

  TProc = (proc (x, y: int)) not nil

proc p(x: PObject) =
  echo "not nil"
  dump x == nil

# compiler catches this:
# p(nil)

# and also this:
var x: PObject
p(x)
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
not nil
x == nil = true
```

### Expected Output
```
Error
```
```
nim -v

Nim Compiler Version 1.4.6 [Linux: amd64]
Compiled at 2021-04-26
Copyright (c) 2006-2020 by Andreas Rumpf
```  
Same with devel version:  `1.5.1`  
P.S. Also TProc unused here, and there are no declaration of TObj in original example

**Comment by alaviss** [comment]
`strictNotNil` doesn't catch this either
