### ISSUE TITLE
`getHostname` silently truncates to 64 bytes

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18088]
getconf HOST_NAME_MAX
255
but could potentially be larger, see https://stackoverflow.com/questions/8724954/what-is-the-maximum-number-of-characters-for-a-host-name-in-unix

While the POSIX standard says it is guaranteed not to exceed 255 bytes, that does not necessarily mean that each implementation will adhere to that.

### Example
change `const size = 64` to `const size = 5` (for eg) then run:
`nim r --lib:lib --eval:'import nativesockets; echo getHostname()'`

### Current Output
shows my hostname truncated to 4 chars, and no error

### Expected Output
don't truncate, or at least raise

### Possible Solution
```nim
var buf {.noinit.}: array[256, char]
```
etc

### Additional Information
1.5.1 7f077a76fea389ce4f55e18857c499fadb3958fa

## links
just filed https://stackoverflow.com/questions/67844865/gethostname-silently-truncates-result-instead-of-giving-enametoolong-error

**Comment by micycle8778** [comment]
I tried reducing the size, but I just end up getting an OSError instead of a truncated hostname.
```
cmdfile.nim(1)           cmdfile
/home/rainbow/Documents/Nim/Nim/lib/pure/nativesockets.nim(449) getHostname
/home/rainbow/Documents/Nim/Nim/lib/pure/includes/oserr.nim(94) raiseOSError
Error: unhandled exception: File name too long [OSError]
```
I'm using voidlinux with linux verison 5.11.22_1

**Comment by timotheecour** [comment]
* so looks like the bug (name too long not being raised) affects osx but not linux
* the other part is still a bug (64 is too small)
