### ISSUE TITLE
`scrollIntoView()` lacks additional arguments for JavaScript

### ISSUE THREAD

**Issue by thetek42** [nim-lang/Nim#18093]
When compiling Nim to JavaScript using `dom`, you cannot specify any additional "object arguments" (see example below) to certain function. I ran across it when trying to use the `scrollIntoView()` function. In JavaScript, you can specify if the scroll animation should be smooth or static. In Nim, you cannot pass any more arguments.

### Example

Nim:
```nim
import dom
document.getElementById("element-id").scrollIntoView() # <- you cannot specify any additional parameters
                                                       # in the parentheses of scrollIntoView()
```

Additional arguments in JavaScript:
```javascript
document.getElementById("element-id").scrollIntoView(
    { behaviour: "smooth", block: "start" }
);
```

### Current Output
Using `scrollIntoView()` with any additional arguments throws an error, as it cannot accept multiple arguments.
```
Error: type mismatch: got <Element, array[0..0, (string, string)]>
but expected one of: 
proc scrollIntoView(n: Node)
  first type mismatch at position: 2
  extra argument given
```

### Expected Output
Use e.g. `behaviour="smooth"` in the function arguments to output a valid JavaScript file with `{behaviour:"smooth"}`

### Possible Solution

Add additional arguments to the function, such as `behaviour: string` which defaults to `auto` (it's also the default for JavaScript).

### Additional Information

The documentation for this JavaScript feature can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

I am using Jester and Karax in order to build a website.

```
$ nim -v
Nim Compiler Version 1.4.6 [Linux: amd64]
Compiled at 2021-04-15
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2b6b08032348939e5d355a6cb4faa0169306c17f
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
@thetek42 PR welcome
