### ISSUE TITLE
elif in case statement is not documented in the manual

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#18092]
This form is nowhere to be seen in the "Case statement" section

### Example
```nim
case true:
of false:
  doAssert false
elif true:
  echo "true"
else:
  doAssert false
```

Note that the fact that there can not be any `of` branches after an `elif` must be documented.

Found during implementation of CPS expression flattening.

**Comment by timotheecour** [comment]
ok, but this is pure documentation issue, not language design (nothing to be fixed on the design side)

**Comment by metagn** [comment]
It's in "case expression" https://nim-lang.org/docs/manual.html#statements-and-expressions-case-expression

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/18105
