### ISSUE TITLE
Wrong argument evaluation order involving a variable and an operation that mutates it

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#18099]
### Example
```nim
var i = 0

proc print(a, b: int) =
  echo a, ' ', b

print i, (inc i; i)
```

### Current Output
```
1 1
```

### Expected Output
```
0 1
```

### Additional Information
- `--gc:arc/orc` give the correct result

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 478f717377c4cd60cfce112b8b21d58031b118b4
active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by timotheecour** [comment]
* cgen:
```
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	i_t4950514951_1 += ((NI) 1);
	print_t4950514951_2(i_t4950514951_1, i_t4950514951_1);
}
```
* happens in js, c, but not in VM, which prints 0, 1:
```nim
when true:
  proc main =
    var i = 0
    proc print(a, b: int) =
      echo a, ' ', b
    print i, (inc i; i)
  static: main()
  main()
```

note that C suffers from similar issues, and IIRC this is undefined behavior, for performance reasons.
This aliasing of memory location cannot be detected robustly without hurting runtime performance, eg consider this case:
```nim
when defined case3:
  proc main =
    var x = [10, 11, 12]
    let ind = 0
    proc print(a, b: int) =
      echo a, ' ', b
    print x[0], (inc x[ind]; x[ind])
  static: main()
  main()
```
maybe in the case of original snippet, aliasing could be detected, but what about the 2nd case?

IIRC there are similar other issues in nim, eg: https://github.com/nim-lang/Nim/issues/17444#issuecomment-803895535

**Comment by Araq** [comment]
The reduced example doesn't help in understanding why it's a "severe" issue for CPS. What's the real world code that underlies this issue report?

**Comment by alaviss** [comment]
> The reduced example doesn't help in understanding why it's a "severe" issue for CPS. What's the real world code that underlies this issue report?

We need to know what is the expected behavior for the implementation of expr flattening in CPS. We want to eliminate or reduce the differences between outside cps and inside cps as much as possible

**Comment by Araq** [comment]
The correct behavior is what `--gc:orc` already does. It requires an annoying expensive analysis but better than the alternative solutions.
