### ISSUE TITLE
feature request: fine tuning type of args for exported procedures

### ISSUE THREAD

**Issue by d3m1gd** [nim-lang/Nim#1810]
Low priority feature request described here: http://forum.nim-lang.org/t/702

In brief: Nim always prefer call by ref for procedures, which is sometimes not desirable (especially interfacing with C code). Only way to affect this behaviour for now is to use `bycopy` pragma on a type used for the procedure.

Proposal: allow more fine control over representation of argument types, used for procedures. Maybe `bycopy` in procedure declaration for affected args.

**Comment by Araq** [comment]
This is a bad idea as then proc types (callbacks) can have different ABIs in subtle ways. Sorry, let's better not do this.
