### ISSUE TITLE
Sequtils bug: cannot attach a custom pragma to 's2'

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#18113]
A combination of pragma + `toSeq` + `filterIt` causes this.

### Example
```nim
import sequtils

{.push raises: [Defect].}

var a = toSeq([1, 2, 10, 20]).filterIt(it > 5)
```

### Current Output
```
sequtils.nim(738, 18) Error: cannot attach a custom pragma to 's2'
```

### Possible Solution

Several walkarounds:

```nim
import sequtils

# {.push raises: [Defect].}         <--- commenting out this line

var a = toSeq([1, 2, 10, 20]).filterIt(it > 5)
```

```nim
import sequtils

{.push raises: [Defect].}

var a = toSeq([1, 2, 10, 20])     # <--- doing toSeq and filterIt separately
var b = a.filterIt(it > 5)
```

### Additional Information

This is a regression, and `git bisects` says it is caused by this PR: https://github.com/nim-lang/Nim/pull/17448. cc @saem 

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 1e0165186bb8539cfd8aca1a7af8d01dc278bd46
active boot switches: -d:release
```

**Comment by saem** [comment]
I took a quick look at the change. The pragma handling was moved prior to setting generic parameters, which seems to be one of the more substantive changes. I wonder if that's what's causing the issue? The earliest I might be able to look at it is this weekend.

**Comment by saem** [comment]
The issue is exposed by the fact that I moved `s.ast = n` ahead of the pragma handling.

Moving that after pragma handling "fixes" the problem but really it's just papering over what's likely a more fundamental issue. I can't really think about it sufficiently at this point in time.
