### ISSUE TITLE
`koch docs` fails if `node` is not installed

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#18112]
`koch docs` fails on my system as I do not have `node` installed.

### Example

- Clone this repo
- Run `sh build_all.sh`
- `koch docs`

### Current Output

```
/home/kmodi/downloads/git/Nim/lib/system/jssys.nim(54, 6) Warning: 'getCurrentException' is not GC-safe as it accesses 'lastJSError' which is a global using GC'ed memory [GcUnsafe2]
Hint: used config file '/home/kmodi/downloads/git/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/config/config.nims' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: used config file '/home/kmodi/downloads/git/Nim/config.nims' [Conf]
Hint: 63722 lines; 0.694s; 95.418MiB peakmem; proj: /home/kmodi/downloads/git/Nim/web/upload/1.5.1/nimcache/runnableExamples/jsbigints_group0_examples.nim; out: /home/kmodi/downloads/git/Nim/web/upload/1.5.1/nimcache/runnableExamples/jsbigints_group0_examples.js [SuccessX]
Hint: ***SLOW, DEBUG BUILD***; -d:release makes code run faster. [BuildMode]
Hint:  --unhandled-rejections=strict /home/kmodi/downloads/git/Nim/web/upload/1.5.1/nimcache/runnableExamples/jsbigints_group0_examples.js  [Exec]
sh: --unhandled-rejections=strict: command not found
Error: execution of an external program failed: ' --unhandled-rejections=strict /home/kmodi/downloads/git/Nim/web/upload/1.5.1/nimcache/runnableExamples/jsbigints_group0_examples.js '
[runnableExamples] failed: generated file: '/home/kmodi/downloads/git/Nim/web/upload/1.5.1/nimcache/runnableExamples/jsbigints_group0_examples.nim' group: 'rdoccmd:
docCmd:
code: # autogenerated by docgen
```

### Expected Output

Skip the `node` -requiring snippets during doc generation and throw warning saying that those examples won't be rendered as `node` was not found.

Alternatively, throw error saying that `node` needs to be installed. But do we want Nim installations to have `node` as a dependency? Above error is confusing. Looking at the source:

https://github.com/nim-lang/Nim/blob/1e0165186bb8539cfd8aca1a7af8d01dc278bd46/compiler/nim.nim#L98-L101

.. above error happened because `findNodeJs()` returns an empty string. I think empty string should not be allowed here.. it should either error out or if that function returns empty, the node related examples should be skipped.

### More info

I was attempting to install nim devel locally using `build_all.sh`. This was the commit ( https://github.com/nim-lang/Nim/commit/1e0165186bb8539cfd8aca1a7af8d01dc278bd46 ) I tried, but the issue is not related to that commit.

**Comment by timotheecour** [comment]
node is also needed for compiler dochack: `nimexec("js tools/dochack/dochack.nim")` to get working search

we already have: `--doccmd:skip` to skip all runnableExamples, maybe `--doccmd:skipjs` could be added

we should add: `findNodeJs(check = true)` and raise if empty and check = true

**Comment by Araq** [comment]
> node is also needed for compiler dochack: nimexec("js tools/dochack/dochack.nim") to get working search

I don't think so, we compile some .nim code to js and run it in the browser, no NodeJS required.

**Comment by timotheecour** [comment]
after https://github.com/nim-lang/Nim/pull/18165, we still need to error when findNodeJs = "" and calling `cmdPrefix = findNodeJs() & " --unhandled-rejections=strict " ` (ie error early to get proper context), so the `findNodeJs(check = true)` suggestion is still the simplest (=> bug https://github.com/timotheecour/Nim/issues/749)

**Comment by kaushalmodi** [comment]
Thanks, I confirm the fix. Now `koch docs` passes without `node` present in PATH.
