### ISSUE TITLE
Returning a Tuple With a Polymorphic Field Causes a Compiler Crash

### ISSUE THREAD

**Issue by jayvanderwall** [nim-lang/Nim#18125]
When returning a tuple where one of the types is the base class of the actual class returned, the compiler terminates with an internal error.

### Example
```nim
type
  Parent = ref object of RootObj

  Child = ref object of Parent
    c: char

func foo(c: char): (Parent, int) =
  # Works if you use (Parent(Child(c: c)), 0)
  (Child(c: c), 0)

if isMainModule:
  let x = foo('x')[0]
  echo Child(x).c
```

### Current Output
The problem exists from at least version 1.0.0 up to the latest devel build from choosenim.
```
/home/jay/code/bug.nim(5, 5) Error: internal error: genCheckedRecordField
No stack traceback available
```

### Additional Information
No issue is present when :
- returning the parent type alone: `func foo(c: char): Parent`
- using the child type in the return type: `func foo(c: char): (Child, int)`
- converting the child object to the parent reference type before creating the tuple to return (the workaround I'm using).

Additionally, running `nim check` passes with no issues; only compiling with `nim c` causes the error.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-29
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9eae6b4fe312035daadd8dcb0ca488a3e5897c11
active boot switches: -d:release
```

**Comment by metagn** [comment]
The compiler thinks it can convert `(Child, int)` to `(Parent, int)` but the codegen doesn't know how (only how to convert individual `Child` to `Parent`). 

If we change `< isSubtype` to `<= isSubtype` here:

https://github.com/nim-lang/Nim/blob/f46f26e79aada7195f4d83d8601f0d856520763d/compiler/sigmatch.nim#L591

the compiler will error at semantic check time that `(Child, int)` cannot be converted to `(Parent, int)`.

We can still make this example compile by using the new type inference to convert the `Child()` field to `Parent`, by calling `fitNode` on `n[i]` and `expectedElemType` here (it would still error if we did `let x = (Child(c: c), 0); return x`):

https://github.com/nim-lang/Nim/blob/f46f26e79aada7195f4d83d8601f0d856520763d/compiler/semexprs.nim#L2794-L2795
