### ISSUE TITLE
find and rfind differ on empty needle

### ISSUE THREAD

**Issue by n5m** [nim-lang/Nim#18128]
[`find`](https://nim-lang.github.io/Nim/strutils.html#find%2Cstring%2Cstring%2CNatural%2Cint) and [`rfind`](https://nim-lang.github.io/Nim/strutils.html#rfind%2Cstring%2Cstring%2CNatural%2Cint) return different values when the string that is being searched for has length 0.

### Example
```nim
import strutils

doAssert "abc".find("") == 0
doAssert "abc".rfind("") == -1
```

### Current Output
Both assertions pass.

### Expected Output
One of the following:
1. `find` and `rfind` both return 0
1. `find` and `rfind` both return -1
1. `find` returns `low("abc")`, and `rfind` returns `high("abc")`

Which one is the best?

### Additional Information
git hash cfe19247e856950f7facaf7adbc50bca8dec3990
```console
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-29
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: cfe19247e856950f7facaf7adbc50bca8dec3990
active boot switches: -d:release
```

**Comment by Clyybber** [comment]
Option 3 is the most intuitive and logical to me.

**Comment by timotheecour** [comment]
> One of the following:

none of the following. instead it should be:
4: find returns low("abc"), and rfind returns len("abc")

eg:
```nim
doAssert "abc".find("") == 0
doAssert "abc".rfind("") == 3
doAssert "abc".rfind("c") == 2
doAssert "abc".rfind("bc") == 1
doAssert "abc".rfind("abc") == 0
```

**Comment by kaushalmodi** [comment]
@timotheecour How would you distinguish between

```nim
doAssert "abc".find("a") == 0 # expected and current behavior
```

and

```nim
doAssert "abc".find("") == 0 # current and proposed behavior
```

**Comment by kaushalmodi** [comment]
### API that we wouldn't want to break

- `find` or `rfind` should return -1 only when the find fails

### Proposal

```nim
import std/[strutils]

# find
doAssert "abc".find("foo") == -1 # Return -1 on failure to find searched string

doAssert "abc".find("a") == 0
doAssert "abc".find("b") == 1
doAssert "abc".find("c") == 2
doAssert "abc".find("") == 3  # This returns 0 right now

# rfind
doAssert "abc".rfind("foo") == -1 # Return -1 on failure to find searched string

doAssert "abc".rfind("") == 3  # This returns -1 right now
doAssert "abc".rfind("c") == 2
doAssert "abc".rfind("bc") == 1
doAssert "abc".rfind("abc") == 0
```

https://play.nim-lang.org/#ix=3ovN

---

I know that my proposed  `doAssert "abc".find("") == 3` is differing from the Python `find`. But I find the Python `find` behavior weird; it returns 0 whether the search string matching the first char or even an empty string. So how would you distinguish between the 2 cases.

Also we cannot have `doAssert "abc".find("") == -1` because we want to be consistent that a return of -1 means that the searched string wasn't found.

**Comment by timotheecour** [comment]
@kaushalmodi just replying to your comment here: https://github.com/nim-lang/Nim/issues/18128#issuecomment-852058175

I don't understand this comment; my proposal would change `"abc".rfind("")`, not `"abc".find("")`

both currently and under my proposal, you'd still have:
```nim
doAssert "abc".find("") == 0
doAssert "abc".find("a") == 0
doAssert "abc".find("ab") == 0
doAssert "abc".find("abc") == 0
```
which makes sense

**Comment by kaushalmodi** [comment]
> my proposal would change `"abc".rfind("")`, not `"abc".find("")`

Yes, I understand. I brought it up as this issue is about fixing the `find` and `rfind` for `""`.

---

>     doAssert "abc".find("") == 0
>     doAssert "abc".find("a") == 0
>
> which makes sense

It feels strange to me that the first occurrence of both `""` and `"a"` is at index 0 of the `"abc"` string. Technically, `"abc"[0] == 'a'`.

**Comment by kaushalmodi** [comment]
Thinking more on this, `"abc".find("") == 0 ` makes sense if I think in this manner:

```nim
doAssert "abc".find("") == 0
doAssert "abc".find("" & "a") == 0
doAssert "abc".find("" & "ab") == 0
doAssert "abc".find("" & "abc") == 0
```

---

### Summary

No objection with `"abc".find("") == 0` and `"abc".rfind("") == 3` :+1:
