### ISSUE TITLE
Casting the destroy call away -- intended?

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#18130]
Following a Nim forum post from https://forum.nim-lang.org/t/7360#46632 and the example in http://ssalewski.de/nimprogramming.html#_destructors I finally found out that a cast can suppress a destroy call.

Well not really a bug, personally I do not like casts at all and avoid them, and maybe the cast below is invalid. But it compiles, and while for the three commented out lines the destructor is executed each, for the actual example with the cast there is no destructor execution. It was surprising for me and took me some hours to discover.

Well, maybe I should  "phrase my post in a more civilized manner." or better post at reddit.

```nim
type
  O = ref object of RootRef
    i: int
    
  O1 = ref object of O
  O2 = ref object of O
    
proc `=destroy`(o: var typeof(O()[])) =
  echo "destroying O"
  
proc `=destroy`(o: var typeof(O1()[])) =
  echo "destroying O1"
  
proc `=destroy`(o: var typeof(O2()[])) =
  echo "destroying O2"

proc test =

  #let o = O()
  #let o1 = O1()
  #let o2 = O2()

  let o3 = cast[O2](O1()) # no destroy call

test()
```

```
nim c --gc:arc --expandArc:test t2.nim 
....
/tmp/hhh/t2.nim(23, 7) Hint: 'o3' is declared but not used [XDeclaredButNotUsed]
--expandArc: test

var o3
`=copy`(o3, cast[O2](O1()))
`=destroy`(o3)
-- end of expandArc ------------------------
salewski@nuc /tmp/hhh $ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 6a5973882bb0c4134a0e454ea4ae69dc54815f27
active boot switches: -d:release
salewski@nuc /tmp/hhh $ ./t2
salewski@nuc /tmp/hhh $ 
```

**Comment by Araq** [comment]
> Well, maybe I should "phrase my post in a more civilized manner." or better post at reddit.

This issue report is perfectly fine. Wether something is civilized or not is not all that hard to judge but there are also good books written about it. "Do not to bring up unrelated topics." would be a start.

**Comment by planetis-m** [comment]
The same bug causes a memory leak in snappy/supersnappy's `compress`/`uncompress` templates. Found with the llvm address sanitizer.

```
template compress*(src: string): string =
  cast[string](snappy.encode(cast[seq[byte]](src)))
```

`--expandarc` on the caller looks like:

```nim
var data
`=copy`(data, cast[string](decode(data_1)))
...
`=destroy`(data)
```

**Comment by Araq** [comment]
Er, so `data` is destroyed, where is the bug?

**Comment by planetis-m** [comment]
> Er, so data is destroyed, where is the bug?

The problem was, the destruction of src was missing. I cant reproduce now, my test was:

```nim
func encode*(src: openArray[byte]): seq[byte] =
  result = newSeq[byte](src.len)

template compress*(src: string): string =
  cast[string](encode(cast[seq[byte]](src)))

proc main =
  var
    s = newString(100)
  let data = compress(s)
  echo data.len

main()

proc main1 =
  var
    s = newString(100)
  let data = cast[string](encode(s.toOpenArrayByte(0, s.len-1)))
  echo data.len

main1()

proc main2 =
  var
    s = newSeq[byte](100)
  let data = cast[string](encode(s))
  echo data.len

main2()
```
