### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by DAddYE** [nim-lang/Nim#1814]
Hi there,

Following this: https://news.ycombinator.com/item?id=8822925

I suggest that the compiler will enforce the same style within a codebase.

I also suggest (I know, I know :disappointed:) a `nim format` tool (if not already there) as well.

The reason of that is because within a team (like at work) some rules must be enforced instead to simply follow a "code style guideline".

**Comment by Araq** [comment]
It's nice you're still with us.

**Comment by DAddYE** [comment]
Never left, I have always being :eyes:

**Comment by dyu** [comment]
Probably you got used to golang's way of doing it.
Nim offers a good compromise for the early adopters and the new comers.
The T/P prefixes you promised to remove are now gone though :-)

**Comment by DAddYE** [comment]
@dyu honestly for me now it is fine. See: https://news.ycombinator.com/item?id=8822925 and my reply.

**Comment by Araq** [comment]
We now have a ``--nep1`` switch in the compiler and the ``nimpretty`` tool. Closing.
