### ISSUE TITLE
Message with `UnitSep` should only add with some command line options

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#18143]
UnitSep is added to every message after following commit:

```
commit 0b116310bfb691755481293e8f9af11190fe0999
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Tue Apr 20 16:30:17 2021 +0200

    unit separator (#17730)

    * use the ASCII Unit Separator so that error messages can be handled precisely by the tooling
    * updated testament
```

However, this cause some problems.
1. It is not actually invisible for some console. ![Snipaste_2021-06-01_11-33-39](https://user-images.githubusercontent.com/5612339/120262998-68f67a80-c2cd-11eb-8c3d-19dd06d15cec.png)

2. After copy and paste the messages, I must modify it, otherwise...

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-06-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c0e8199acc9f49caa36bae34d103600d112b66f3
active boot switches: -d:release
``` 

Since UnitSep is add for tool that handle error message, IMO, it should be turned on only if necessary.

**Comment by timotheecour** [comment]
please check if duplicate of https://github.com/nim-lang/Nim/issues/18058, if so close it

**Comment by khchen** [comment]
You are right. closing...
