### ISSUE TITLE
std/monotimes not strictly monotonic on Linux_amd64 and windows

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18158]
as discovered in CI failures from https://github.com/nim-lang/Nim/pull/18149

### Example
```nim
# main.nim
# adapted from tests/stdlib/tmonotimes.nim from #18149
import std/[monotimes, times]
const n = 1000000
for i in 0..<n:
  let a = getMonoTime()
  let b = getMonoTime()
  doAssert b > a
```

nim r main

### Current Output
assert fails

### Expected Output
works

### Additional Information
1.5.1 0de3d4292f328f94c7a94af7e3e61e58ff43a252
* the test passes on linux 32bit in CI
* it passes locally in docker from ubuntu:20.04
* it passes on osx locally and in CI
* it fails in CI in Linux_amd64 and windows
note that the implementation of monotimes is indeed OS-specific

### notes
I can actually reproduce on my mac locally if I change the code to use the same code as for linux; and after further investigation, it looks like CLOCK_MONOTONIC is low-res, unlike CLOCK_MONOTONIC_RAW:

```nim
when defined case2:
  import std/[monotimes, times]
  const n = 1000000
  import posix
  var CLOCK_MONOTONIC* {.importc: "CLOCK_MONOTONIC", header: "<time.h>".}: cint
  var CLOCK_MONOTONIC_RAW* {.importc: "CLOCK_MONOTONIC_RAW", header: "<time.h>".}: cint
  proc mach_absolute_time(): int64 {.importc, header: "<mach/mach.h>".}
  template algo(): untyped =
    # getMonoTime()
    # mach_absolute_time()
    var ts: Timespec
    # discard clock_gettime(CLOCK_MONOTONIC, ts) # b > a fails
    discard clock_gettime(CLOCK_MONOTONIC_RAW, ts) # b > a works
    ts.tv_nsec.int64

  proc main =
    for i in 0..<n:
      let a = algo()
      let b = algo()
      # doAssert b >= a
      echo b-a
      doAssert b > a
  main()
```

after more research (man pages are surprisingly not clear at all on this), I found https://reviews.llvm.org/D74341 which confirms that CLOCK_MONOTONIC_RAW sounds like the solution, on linux at least

## question: windows?
no idea here

**Comment by Varriount** [comment]
As far as I know, the definition of a "monotonic" clock is merely a clock that always increases. The definition does not imply that querying the clock multiple times will never return the same value. I don't know if it's wise to try to include that as an additional guarantee, as it may not be available on all systems (not just for Windows, but Mac, BSD, etc.).

Regarding Windows, the general function used as a [monotonic](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps#general-faq-about-qpc-and-tsc) counter is [QueryPerformanceCounter](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter). _That being said_, it can [return the same value over multiple calls](https://stackoverflow.com/questions/9816608/can-queryperformancecounter-or-stopwatch-gettimestamp-return-the-same-value).

If a strictly increasing monotonic clock is needed, I think the only solution is using a global variable to remember the last value returned:
```
proc getMonotonicClock(): int =
  var lastValue: int {.threadvar.}
  while true:
    result = QueryPerformanceCounter()
    if result != lastValue:
      lastValue = result
      break
```
(I don't know offhand how this would be done with multiple threads. Obviously you would need to lock, read, and write `lastValue` from multiple threads)

**Comment by Clyybber** [comment]
monotimes isn't supposed to be strictly monotonic, only montonic.

**Comment by Araq** [comment]
There is no bug here. The test in tmonotimes is correct, it's your test that is incorrect as it is based on wrong assumptions.

**Comment by Varriount** [comment]
@Araq I don't think this was intentional or even all that naive, just a mistake in comprehension. I could certainly see myself accidentally assuming something similar.
