### ISSUE TITLE
nim doc issue with templates with nested templates (continuation of #18054)

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#18157]
The issue reproduction test in #18054 now works after the fix in https://github.com/nim-lang/Nim/commit/0de3d4292f328f94c7a94af7e3e61e58ff43a252 . But oddly, the documentation of nested templates does not get generated if:

1. I remove the `when isMainModule` from that example, OR
2. I remove the export markers (`*`) after the inner templates. Ideally the inner templates should not have the export markers.

#### Test `t1`

Below is the same example in #18054 except that:

1. I have removed the export markers from inner templates, and
2. I have removed the `when isMainModule:` block. 

Run `nim doc t1.nim`.

```nim
# t1.nim
template outer*(body: untyped) =
  ## outer template doc string.
  runnableExamples:
    doAssert 1 == 1
  ##
  template inner1() =
    ## inner1 template doc string.
    runnableExamples:
      doAssert 2 == 2
    ##
    echo "inner1"

  template inner2() =
    ## inner2 template doc string.
    runnableExamples:
      doAssert 3 == 3
    ##
    echo "inner2"

  body
```

#### Test `t2`

Below is the same example in #18054 except that:

1. I have removed the export markers from inner templates

Run `nim doc t2.nim`.

```nim
# t2.nim
template outer*(body: untyped) =
  ## outer template doc string.
  runnableExamples:
    doAssert 1 == 1
  ##
  template inner1() =
    ## inner1 template doc string.
    runnableExamples:
      doAssert 2 == 2
    ##
    echo "inner1"

  template inner2() =
    ## inner2 template doc string.
    runnableExamples:
      doAssert 3 == 3
    ##
    echo "inner2"

  body

when isMainModule:

  echo "in main module"

  outer:
    inner1()
    inner2()
```

### Current Output

I get similar output with both t1 and t2 tests above i.e. documentation and runnableExamples of the inner templates is not exported.

![image](https://user-images.githubusercontent.com/3578197/120536916-a7199a00-c3b2-11eb-9bab-53140d792e5d.png)

### Expected Output

I expect an output similar to below with both t1 and t2 tests above i.e. documentation and runnableExamples of the inner templates do get exported.

![image](https://user-images.githubusercontent.com/3578197/120537038-cfa19400-c3b2-11eb-8529-eef8adcb5830.png)

### Additional Information

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-02
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0de3d4292f328f94c7a94af7e3e61e58ff43a252
active boot switches: -d:release
```

/cc @timotheecour

**Comment by kaushalmodi** [comment]
Note: `unittest` failed the test when I had export markers on the inner templates in [the `ptr_math`](https://github.com/kaushalmodi/ptr_math) module.

**Comment by timotheecour** [comment]
I'm not sure I follow, the current output is correct, private symbols don't get docgen'd unless you pass `--docInternal`

if you remove the isMainModule block (that calls outer), inner1 and inner2 don't get generated, so don't get docgen'd

if you make inner1 and inner2 private, calling outer won't docgen them unless `--docInternal` is passed

everything seems to work as expected, including `--docInternal:on|off`

> Note: unittest failed the test when I had export markers on the inner templates in the ptr_math module.

seems like a separate issue, please write here a minimized self contained example

**Comment by kaushalmodi** [comment]
> >  Note: unittest failed the test when I had export markers on the inner templates in the ptr_math module.

> seems like a separate issue, please write here a minimized self contained example

Is that an issue? I was just making a note. It made sense that we don't export the inner templates as they are part of the output template being exported.

**Comment by kaushalmodi** [comment]
> unless you pass `--docInternal`

I was missing that piece of information, and also that fact that I need the `isMainModule` calling the outer template if I want the inner templates to get documented.

So this works!

```nim
template outer*(body: untyped) =
  ## outer template doc string.
  runnableExamples:
    doAssert 1 == 1
  ##
  template inner1() =
    ## inner1 template doc string.
    runnableExamples:
      doAssert 2 == 2
    ##
    echo "inner1"

  template inner2() =
    ## inner2 template doc string.
    runnableExamples:
      doAssert 3 == 3
    ##
    echo "inner2"

  body

when isMainModule:

  # Below call to `outer` is needed so that the inner templates get
  # generated and picked up by docgen.
  outer:
    discard
```

**Comment by kaushalmodi** [comment]
@timotheecour One more question on this topic of generating docs for internal unexported templates.

I get the `gensym` identifier next to each template arg. Do you see that as a bug? If so, I can open another ticket:

https://kaushalmodi.github.io/ptr_math/#%2B.t%2Cptr.T%2Cint

![image](https://user-images.githubusercontent.com/3578197/120544038-fc59a980-c3ba-11eb-8c41-f0e3f6622786.png)

**Comment by timotheecour** [comment]
> Do you see that as a bug?

works as intended, docgen reflects the truth and consistent with macros.treeRepr/repr

see also inject, eg:
```nim
template main =
  template foo*(a {.inject.}: int) = discard
main()
```

**Comment by kaushalmodi** [comment]
As I am cleaning up the tests and docs of that ptr_math project, I found another usability issue.

With the current ptrMath template code, I cannot call that template more than once in the same scope, because the nested templates are then expanded in the same scope and cause ambiguous calls error. Ref: https://forum.nim-lang.org/t/8075#51673

The fix for that is that I wrap all the nested templates inside a `block:`. But then the docgen fails to generate the docs for those nested templates and we are back to square 1 :|

### Fails compilation if outer template used multiple times in same scope

But the docgen is correct if the second `ptrMath:` call is removed.

```nim
template ptrMath*(body: untyped) =
  ## `ptrMath` template doc string.
  template `+`[T](p: ptr T, offset: int): ptr T {.used.} =
    ## `+` template doc string.
    cast[ptr T](cast[ByteAddress](p) +% (offset * sizeof(T)))

  template `+=`[T](p: ptr T, offset: int) {.used.} =
    ## `+=` template doc string.
    p = p + offset

  body

when isMainModule:

  ptrMath:
    discard

  var
    a: array[0 .. 3, int]
    p = addr(a[0])

  ptrMath:
    p += 1
```

### Passes compilation but the docgen doesn't export docs from the templates inside `block:`


```nim
template ptrMath*(body: untyped) =
  ## `ptrMath` template doc string.
  block:
    template `+`[T](p: ptr T, offset: int): ptr T {.used.} =
      ## `+` template doc string.
      cast[ptr T](cast[ByteAddress](p) +% (offset * sizeof(T)))

    template `+=`[T](p: ptr T, offset: int) {.used.} =
      ## `+=` template doc string.
      p = p + offset

    body

when isMainModule:

  ptrMath:
    discard

  var
    a: array[0 .. 3, int]
    p = addr(a[0])

  ptrMath:
    p += 1
```

**Comment by timotheecour** [comment]
this still works as intended; you can't export routines at block scope; what you need instead is:
```nim
template ptrMath*() =
  # define routines

ptrMath()
```

then use the routines that were generated
