### ISSUE TITLE
regression: tests/dll/client.nim fails on openbsd: could not load: libgc.so.4.0

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18177]
### Example
https://azusa.runners.sr.ht/logs/519617/test/log

### Current Output
```
[31mFAIL: [36mtests/dll/client.nim c  --gc:boehm --threads:on             [34m ( 0.82 sec)[0m

Category: dllName: tests/dll/client.nim c  --gc:boehm --threads:onAction: runResult: reExitcodesDiffer-------- Expected -------exitcode: 0--------- Given  --------exitcode: 1
Output:could not load: libgc.so.4.0(compile with -d:nimDebugDlOpen for more information)<br class="Apple-interchange-newline">

```

could not load: libgc.so.4.0

### Additional Information
1.5.1 a77360da5bad40d22e942cdd5cb9614c3548bf34
https://gist.github.com/timotheecour/734653f1aab6021f87d1e742a6257dcb
my guess is the fix in https://github.com/nim-lang/Nim/pull/12134 was fragile, and the version should be picked in a more robust way /cc @euantorano

**Comment by euantorano** [comment]
I'd guess this is due to `freebsd/latest` now being OpenBSD 6.9 rather than 6.8, and picking up a newer version of boehm.

**Comment by euantorano** [comment]
Yep, in OpenBSD 6.9 it's now `libgc.so.5.0`. That would definitely cause this breakage.
