### ISSUE TITLE
readAsText should support File as supports Blob

### ISSUE THREAD

**Issue by mantielero** [nim-lang/Nim#18187]
I think that it is missing the `File`case. 

[Here](https://github.com/nim-lang/Nim/blob/b9843b156dfc16f1f99cbee8fc8e55b7abd6c21b/lib/js/dom.nim#L1770) it is supported the `Blob` case, but in accordance with the [API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText):

> The `readAsText()` method is used to read the contents of the specified `Blob` or `File`. 

So I think the following lines should be included:
```nim
  proc readAsText*(f: FileReader, b: File, encoding = cstring"UTF-8") {.importcpp: "#.readAsText(#, #)".}
    ## https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText
```

**Comment by timotheecour** [comment]
@mantielero instead, please make a PR?

**Comment by mantielero** [comment]
I'd love to, but that would be my second PR ever. Any advice/tutorial? I'd like to do it using the embedded `GitPod`if possible.

**Comment by timotheecour** [comment]
look at recent PRs to get an idea; best way to get something fixed is to fix it yourself ;-)

**Comment by mantielero** [comment]
Did I did it fine?
