### ISSUE TITLE
Add reference to style guide in tutorial and documentation

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#1818]
Leave references to the style guide, located at https://github.com/Araq/Nim/wiki/NEP-1-:-Style-Guide-for-Nimrod-Code, in the tutorial and documentation - otherwise how are newcomers supposed to know the correct style?

**Comment by reactormonk** [comment]
New URL: https://github.com/Araq/Nim/wiki/Style-Guide-for-Nim-Code

**Comment by jochenvdv** [comment]
Maybe it would be a good idea to make the style guide part of the documentation instead of maintaining it in the GitHub wiki while we're at it?

**Comment by Varriount** [comment]
Seconded.

**Comment by ReneSac** [comment]
Isn't this already done now? I see NEP 1 here: http://nim-lang.org/docs/nep1.html

**Comment by dom96** [comment]
Are there any links to it from the site anywhere?

**Comment by daneb** [comment]
@dom96 I believe the style guide is now on the [Documentation](https://nim-lang.org/documentation.html) page.
