### ISSUE TITLE
Codegen bug with inheritance and calling a method/proc taking a var parameter

### ISSUE THREAD

**Issue by jovial** [nim-lang/Nim#1821]
If you try and call a `method` or `proc` that takes a `var` parameter of an objects basetype from within a method taking in the inherited type, the generated c fails to compile. Here is an example: 

```nimrod
import tables

type QObject* = ref object of RootObj
    name*: string
    data*: pointer
    slots*: Table[string, cint]
    signals*: Table[string, cint]
    properties*: Table[string, cint]
    
type MyQObject = ref object of QObject
  m_name: string

proc test(a: var QObject) = discard
proc create(a: var MyQObject) = 
  test(a)

var x = MyQObject(name: "test")
create(x)
```

The error is:

```
/tmp/aporia/nimcache/a6.c: In function ‘create_111063’:
/tmp/aporia/nimcache/a6.c:280:11: error: request for member ‘Sup’ in something not a structure or union
  LOC1 = &a->Sup;
           ^
Error: execution of an external program failed
```

The error occurred on GNU/Linux x86_64 using commit e751a0af573a5a65eaaabf15fecb1f1c010b6bf6

**Comment by Araq** [comment]
The compiler should not allow this. There is no subtype relation from 'var ref MyQObject' to 'var ref QObject'. There is rarely a reason for 'var ref' and certainly none for your use case.

**Comment by Araq** [comment]
The compiler now outputs a proper error message.
