### ISSUE TITLE
The original AST of an proc modified by typed macros still persist across module boundary

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#18235]
### Example
`a.nim`:
```nim
import macros

macro rename(n: typed): untyped =
  result = copyNimTree(n)
  # turn exported nnkSym -> nnkPostfix(*, nnkIdent), forcing re-sem
  result[0] = nnkPostfix.newTree(ident"*").add:
    n.name.strVal.ident

macro unexport(n: typed): untyped =
  result = copyNimTree(n)
  # turn nnkSym -> nnkIdent, forcing re-sem and dropping any exported-ness
  # that might be present
  result[0] = n.name.strVal.ident

proc foo*() {.unexport.} = discard
```

`b.nim` (compile this file):
```nim
import a
foo()
```

### Current Output
Compilation successful

### Expected Output
Error about `foo` not existing/exported.

### Additional Information
* If you use `rename`, which is what CPS would do (force a re-sem on the bootstrap to take the original place), you will be met with this error:
  ```
  Error: ambiguous call; both a.foo() [proc declared in a.nim(15, 6)] and a.foo() [proc declared in a.nim(7, 18)] match for: ()
  ```

* This is blocking CPS procs from being used across module boundary

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-08
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 51ab7ccec1ffa21cef67f1a75dea889653751cfc
active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by timotheecour** [comment]
regardless of this bug and https://github.com/nim-lang/Nim/pull/18249, for unexport/reexport, can't we use untyped macros and avoid all those issues?

**Comment by Clyybber** [comment]
@timotheecour Those are just minimal reproductions.
