### ISSUE TITLE
unsigned ints don't cause exception on overflow

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#18245]
Not sure what the expectation here is, but for signed integers we get overflow errors, whereas for unsigned we don't.

### Example
```nim
var x: uint = high(uint)
echo(x+1)
```

### Current Output

```
0
```

### Expected Output
```
Overflow exception
```

**Comment by Clyybber** [comment]
> Unsigned operations all wrap around; they cannot lead to over- or underflow errors.

https://nim-lang.org/docs/manual.html#types-preminusdefined-integer-types
