### ISSUE TITLE
error running build.sh when trying to install the nim compiler

### ISSUE THREAD

**Issue by 0x447a** [nim-lang/Nim#18242]
I just tried to run build.sh and it failed to run. I'd like to know what the following means:

# Git Bash error: 
$ cd csources && sh build.sh

gcc -w -O3 -fno-strict-aliasing -Ic_code -c c_code/1_2/stdlib_assertions.nim.c -o c_code/1_2/stdlib_assertions.nim.o
In file included from c_code/1_2/stdlib_assertions.nim.c:6:0:
c_code/nimbase.h:493:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^

**Comment by timotheecour** [comment]
csources isn't used anymore in devel, please retry on devel with: `sh build_all.sh`

**Comment by timotheecour** [comment]
closing, feel free to re-open if needed
