### ISSUE TITLE
`except` branch catching multiple type of exceptions are undocumented

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#18258]
This is not shown anywhere in the manual.

### Example
```nim
try:
  raise newException(ValueError, "test")
except ValueError, IOError:
  discard
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-08
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 51ab7ccec1ffa21cef67f1a75dea889653751cfc
active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by vercingetorx** [comment]
It is implied [here](https://nim-lang.org/docs/macros.html#statements-try-statement). I can add a more explicit and visible example though; question is where?

**Comment by alaviss** [comment]
It should be in the manual, since that's the specification of the language

**Comment by vercingetorx** [comment]
Ah I see.

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/18323
