### ISSUE TITLE
unescape from strutils is not dealing with '\r', '\n', etc 

### ISSUE THREAD

**Issue by glyh** [nim-lang/Nim#18268]
(Consider writing a PR targetting devel branch after filing this, see [contributing.html](https://nim-lang.github.io/Nim/contributing.html)).

Function `echo` outputs the wrong string.

### Example
```nim
import strutils
echo unescape("\"\\n\"")

```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
\n
```

### Expected Output
```

# A new line
```

### Possible Solution

Fix the unescape function. 

```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 44e653a9314e1b8503f0fa4a8a34c3380b26fff3
active boot switches: -d:release
```

**Comment by Araq** [comment]
Works as documented, unescape reverses escape, nothing more, nothing less:

```nim

const r = "\"\"\n"

assert r == unescape(escape(r))
```

**Comment by Patitotective** [comment]
Then how am I supposed to convert `"\\n"` into `"\n"`?
https://forum.nim-lang.org/t/8825

**Comment by Araq** [comment]
By learning how to program.
