### ISSUE TITLE
int32 should be int in log2Impl in math.nim

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#18284]
in https://github.com/nim-lang/Nim/blob/99411674a6da72f608bfa870f51b3a296cd85eee/lib/pure/math.nim#L1000 the var `exp` is typed as `int32` - it should be `int` since `frep` expects an `int` not an `ìnt32`. 
This code path is rarely used with a 64bit architecture, that's why it was never reported.
git hash:  99411674a6da72f608bfa870f51b3a296cd85eee

**Comment by timotheecour** [comment]
@AdrianV you're right, PR welcome

also, as indicated in the issue template, please always mention the nim git hash at which you observed this

**Comment by AdrianV** [comment]
ah sorry, I am always on git head :). I will make a PR for this.

**Comment by timotheecour** [comment]
> ah sorry, I am always on git head :). I will make a PR for this.

git head is a moving target, so the git hash is needed so that someone looking at this issue anytime in the future can reproduce this

**Comment by AdrianV** [comment]
updated

**Comment by Clyybber** [comment]
Fixed by #18285
