### ISSUE TITLE
Orc: an inner function in a closure can write over memory allocated for the closure environment

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#18295]
A small example showing how a closure stomp over a value captured by the closure environment. I ran across this trying to pass closures over the C/C++ FFI:

### Example
```nim
import strformat
type
  Closure = ref object
    fp: proc (env:pointer) {.inline.}
    env: pointer

var c : Closure

proc createClosure() =
  new c
  let i = 1
  echo fmt"i outside closure: {i}"
  proc inner() {.closure.} =
    echo fmt"i inside closure: {i}"
  let fp = cast[proc(env:pointer){.inline.}](rawProc inner)
  let env = rawEnv inner
  c[].fp = fp
  c[].env = env

createClosure()

c[].fp(c[].env)

```

### Current Output
```
i outside closure: 1
i inside closure: 0
```

### Expected Output
```
i outside closure: 1
i inside closure: 1
```

### Additional Information
* This issue is blocking a project that creates bindings to a C++ library

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-18
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 87cd9b24a3df66dcde96bbdec2bd7620015ddeba
active boot switches: -d:release
```

**Comment by deech** [comment]
It works as expected with `-d:useMalloc` but why do I need that?

**Comment by Araq** [comment]
` fp: proc (env:pointer) {.inline.}` is not valid code and should be rejected by the compiler. Did you mean `.cdecl`?

**Comment by deech** [comment]
Changing that makes no difference, without `-d:useMalloc` it changes environment.

**Comment by deech** [comment]
FWIW this works  but it's not ideal to explicitly `move` environment resources into the closure.
```
import strformat
type
  Closure = ref object
    fp: proc (env:pointer) {.cdecl.}
    env: pointer

var c : Closure

proc createClosure() =
  new c
  var i = 1   # <--- change var to let
  echo fmt"i outside closure: {i}"
  proc inner() {.closure.} =
    let i = move i # <-- explicitly move it into the closure
    echo fmt"i inside closure: {i}"
  let fp = cast[proc(env:pointer){.cdecl.}](rawProc inner)
  let env = rawEnv inner
  c[].fp = fp
  c[].env = env

createClosure()

c[].fp(c[].env)
```

**Comment by deech** [comment]
This may be a terrible idea but I've managed to keep `arc` from destroying the closure environment by adding:
```
GC_ref(cast[ref Any](env))
```
to the end of `createClosure`. At least this small example runs memory clean according to valgrind.

**Comment by Araq** [comment]
But why would 

```nim

  let env = rawEnv inner
  c[].fp = fp
  c[].env = env

```

keep the env data alive?

**Comment by deech** [comment]
This was my mistake. The right way to pass a closure env to C++ is the store it in a `ref` object and `GC_ref` it when it is passed and `GC_unref` it in the destructor.
