### ISSUE TITLE
IRC logs gives  Error 502 Bad gateway

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#18294]
I have a dozen bookmarks for the Nim IRC logs, mostly advice from mratsim, like

https://irclogs.nim-lang.org/13-09-2020.html#13:59:21

Seems to be all dead since a few days, same for log of actual day https://irclogs.nim-lang.org/.

Of course it is strange that nobody other noticed that, but I tried with my smartphone too, it is the same. So maybe a regional problem for central Europe?

I heard from the IRC freenode trouble, but that should not concern old logs?

**Comment by dom96** [comment]
Indeed it's down because of Freenode troubles. I am working on bringing it back up, old logs are still there the server just isn't running, apologies :)

**Comment by StefanSalewski** [comment]
Seems to work again, thanks. Will close this issue then.
