### ISSUE TITLE
`HashSet` ignores `hash` function

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#18309]
### Example
```nim
type MyObject = object
  field: int
  anotherField: int

func hash(b: MyObject): Hash = hash b.field

var visited: HashSet[MyObject]

for (f, af) in [(0, 1), (1, 1), (2, 1), (1, 2), (1, 3)]:
  visited.incl MyObject(field: f, anotherField: af)

for v in visited: echo v
```

### Current Output
```nim
(field: 2, anotherField: 1)
(field: 1, anotherField: 1)
(field: 1, anotherField: 2)
(field: 1, anotherField: 3)
(field: 0, anotherField: 1)
```

### Expected Output
```nim
(field: 2, anotherField: 1)
(field: 1, anotherField: 1)
(field: 0, anotherField: 1)
```

### Additional Information
the commiunity suggested that i should define a `==` proc and it fixes the problem, 
[but i think it's quite unnecessary because it should check the hashed value only]
```nim
func `==`(a,b: MyObject): bool = a.field == b.field
```

## compiler version
```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-06-20
Copyright (c) 2006-2021 by Andreas Rumpf
```
OS: windows 10

**Comment by timotheecour** [comment]
works as designed IMO.
the only requirement is that hash and == should be defined such that
if a == b, then hash(a) == hash(b).

with what you're suggesting (ignoring ==), hash collisions would lead to incorrect results, eg:
```nim
s.incl "some string"
assert "some other string that collides" notin s # could fail under your proposal
```

**Comment by hamidb80** [comment]
> ```nim
> assert "some other string that collides" notin s # could fail under your proposal
> ```

Why does it could fail? The hashes are different

**Comment by timotheecour** [comment]
hash collisions
