### ISSUE TITLE
NimNode Comparison with system.`==`

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#18310]
When you try to do a system.`==` comparison between two nnkTupleConstr nodes the compiler spits out a SIGSEGV error. This is on 1.48 and 1.51 from about a month ago and on the most recent 1.5.1 version. Was working on 1.4.4.

**Comment by timotheecour** [comment]
@solo989 please follow issue template: show a reproducible example, and git hashes, not "1.5.1 from about a month ago" which is not very helpful

**Comment by solo989** [comment]
What is the command to get the git hash while compiling?
Regardless it didn't work on 1.51 I downloaded right before posting 3 hours ago.
Also it didn't work back as far back as 1.48. So it not working on the 1.5.1 from about a month ago is not important.

Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-06-20
Copyright (c) 2006-2021 by Andreas Rumpf

Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-05-24
Copyright (c) 2006-2021 by Andreas Rumpf

Nim Compiler Version 1.4.8 [Windows: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

```nim
import macros
macro t() : untyped =
  let
    x = nnkTupleConstr.newTree(newLit(1))
    y = nnkTupleConstr.newTree(newLit(2))
  echo system.`==`(x,y)
t()
```

works on
Nim Compiler Version 1.4.4 [Windows: amd64]
Compiled at 2021-02-23
Copyright (c) 2006-2020 by Andreas Rumpf

**Comment by timotheecour** [comment]
> What is the command to get the git hash while compiling?

`nim -v` as explained in the issue template

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/18313
