### ISSUE TITLE
s.high refers to the current seq instead of the old one

### ISSUE THREAD

**Issue by BlaXpirit** [nim-lang/Nim#1832]
```nim
var s = @[5]

# Works fine:
let x = s[s.high]
s.add x

# Causes the 0 to appear:
s.add s[s.high]

echo s # @[5, 5, 0]
```

**Comment by reactormonk** [comment]
Works as expected in the VM with `nim i`, and on the js compiler, but
fails on the c compiler.

C:

    s_88021 = (TY88017*) incrSeq(&(s_88021)->Sup, sizeof(NI));
    s_88021->data[s_88021->Sup.len-1] = s_88021->data[(s_88021->Sup.len-1)];

JS:

    s_14022[0].push(s_14022[0][(s_14022[0].length-1)]);

The C version first increases the seq size, then executes the adding
operation, while the JS operation gets the value first, then pushes
it. Sounds like the seq adding needs a new temp variable with the
value to be assigned. I'd assume the compiler would get rid of it if
needed, but it's yet another copy.

**Comment by Varriount** [comment]
Rather than generating a temporary variable, the modifying the length field of the sequence should be deferred until *after* the the elements have been added.
