### ISSUE TITLE
Double free with --gc:orc

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#18326]
Compiled with:
```
nim c --gc:orc --panics:on --threads:on -d:release --threadanalysis:off
```

### Example
**Edit reason**: simplified
```nim
import std/[os, isolation, atomics]

const
  numThreads = 4

var
  threads: array[numThreads, Thread[void]]
  exc: ref Exception
  excIsSet: Atomic[bool]

proc exceptHook(e: sink Isolated[ref Exception]) =
  # Only one's thread exception will be propagated to the main.
  if not exchange(excIsSet, true, moAcquire):
    exc = e.extract

proc routine {.thread.} =
  try:
    echo("Raising exception... ", getThreadId())
    sleep(100)
    raise newException(CatchableError, "From thread: " & $getThreadId())
  except:
    exceptHook(isolate(getCurrentException()))

proc main =
  for i in 0..<numThreads:
    createThread(threads[i], routine)
  try:
    joinThreads(threads)
    if excIsSet.load(moRelaxed): # no need for atomic!
      raise exc
  except:
    echo "Exception caught! ", getCurrentExceptionMsg()
    #wasMoved(exc) uncomment to make it work!

main()
```

### Current Output

```
Raising exception... 2605
Raising exception... 2607
Raising exception... 2606
Raising exception... 2608
Exception caught! From thread: 2607
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
Nim/lib/system/threads.nim(329) bthrerror
Nim/lib/system/orc.nim(477) nimDecRefIsLastCyclicDyn
Nim/lib/system/orc.nim(460) rememberCycle
Nim/lib/system/orc.nim(146) unregisterCycle
```

### Additional Information
Works with --gc:arc. Uncomment wasMoved to make it work.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 1b3c0f142dd5abc3b3509feb194f54e6acf046c0
active boot switches: -d:release --gc:markAndSweep
```

**Comment by Araq** [comment]
The global `exc: ref Exception` is not safe and `--threadanalysis:off` is a blunt tool, I suppose. However Try to run `GC_runOrc` to drain the ORC data structures and see if it makes a difference please.

**Comment by planetis-m** [comment]
I tried adding it to a few places like right after join, however there is no difference. The trackback is always the same.

Couldn't reproduce without exceptions: https://gist.github.com/planetis-m/7465c48c8ba3b70428a706fbc32d2c06

With Isolated it works somehow: https://github.com/planetis-m/dumpster/blob/master/multithread/threrror.nim

**Comment by planetis-m** [comment]
> The global exc: ref Exception is not safe

Can you expand on that? I'm guarding its setting trough atomic bool excIsSet and accessing it only after joinTreads. TSan reports no data races.

**Comment by Araq** [comment]
> Can you expand on that? I'm guarding its setting trough atomic bool excIsSet and accessing it only after joinTreads. 

I don't know if that suffices as the RC implementation is still not atomic. Dangerous waters. But the real culprit might be `exceptHook(isolate(getCurrentException()))`, and this should not compile at all, the call must be a .noSideEffect call.

**Comment by planetis-m** [comment]
i see, thanks for the explanation!
