### ISSUE TITLE
cursorinference regression

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#18320]
My project segfaults when compiling with --gc:arc and cursor inference not disabled. The crash happens inside allocator code and I suspect it's a heap corruption, so I don't really know where to start minimising.

Though I managed to bisect the issue to be introduced with this commit: https://github.com/nim-lang/Nim/commit/47acc80f4e05053d2653c7218434bc7fad880741

Note that I don't have strictfuncs enabled.

This seems to be a different issue from #18287 as it didn't work before that commit.

**Comment by Araq** [comment]
Maybe you can point us to your project? If it is not open source, you can uncomment the last line in compiler/varpartitions.nim and see what cursors the working compiler inferred and what the broken compiler inferred. This should help quite a bit with coming up with a test case.

**Comment by RSDuck** [comment]
thanks for the answer, that was exactly what I needed.

There was only one a single difference which lies in the std lib: https://github.com/nim-lang/Nim/blob/version-1-4/lib/pure/collections/heapqueue.nim#L80 `newitem` is assumed to be a cursor. I added a hacky check to prevent this from happening and everything works again.

**Comment by RSDuck** [comment]
here's a testcase for that:
```nim

type HeapQueue*[T] = object
  ## A heap queue, commonly known as a priority queue.
  data: seq[T]

proc heapCmp[T](x, y: T): bool {.inline.} =
  return (x < y)

proc len*[T](heap: HeapQueue[T]): int {.inline.} =
  ## Returns the number of elements of `heap`.
  heap.data.len

proc `[]`*[T](heap: HeapQueue[T], i: Natural): lent T {.inline.} =
  ## Accesses the i-th element of `heap`.
  heap.data[i]

proc siftdown[T](heap: var HeapQueue[T], startpos, p: int) =
  ## 'heap' is a heap at all indices >= startpos, except possibly for `pos`. `pos`
  ## is the index of a leaf with a possibly out-of-order value. Restores the
  ## heap invariant.
  var pos = p
  var newitem = heap[pos]
  # Follow the path to the root, moving parents down until finding a place
  # newitem fits.
  while pos > startpos:
    let parentpos = (pos - 1) shr 1
    let parent = heap[parentpos]
    if heapCmp(newitem, parent):
      heap.data[pos] = parent
      pos = parentpos
    else:
      break
  heap.data[pos] = newitem

proc push*[T](heap: var HeapQueue[T], item: sink T) =
  ## Pushes `item` onto heap, maintaining the heap invariant.
  heap.data.add(item)
  siftdown(heap, 0, len(heap)-1)

type
    ScheduledEvent = object
        priority: int32 # over engineering: it's over 9000!
        timestamp: int64
        handler: proc(timestamp: int64)
        token: EventToken

    EventToken* = distinct int

proc `<`(a, b: ScheduledEvent): bool =
    if a.timestamp == b.timestamp: a.priority < b.priority else: a.timestamp < b.timestamp

proc `==`*(a, b: EventToken): bool {.borrow.}

var x: HeapQueue[ScheduledEvent]
x.push(ScheduledEvent())
```
