### ISSUE TITLE
--gc:arc creates un-necessary temporaries for block expressions, causing large slowdowns

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18341]
2nd reduction from investigation of the mysterious differences between --gc:arc -d:danger and -d:danger when applying some modifications to the code, refs https://github.com/nim-lang/Nim/pull/18324#issuecomment-867160869 (see https://github.com/nim-lang/Nim/issues/18339 for the other reduction; it's a different problem)

* Example 1 shows the codegen issue showing that --gc:arc creates temporaries that shouldn't be generated (they don't get generated with --gc:refc)
while it may seem like a non-problem because C optimizer might optimize those away, it actually is a problem:
* Example 2 shows the same code but with bigger objects than `int`, and the resulting code is 25X slower with --gc:arc (the factor depends on the object size)

### Example 1
```nim
when true: # D20210623T232346:here
  proc foo(x: int) =
    let y =
      if x > 3:
        if x > 5: 1
        else: 2
      elif x > 1: 3
      else: 4
  foo(3)
```

### Current Output
nim r -d:danger --gc:arc t12463.nim
```c
N_LIB_PRIVATE N_NIMCALL(void, foo_t4950525451_1)(NI x) {
	NI colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	NI y;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	{
		NI colontmpD__4;
		NI colontmpD__5;
		if (!(((NI) 3) < x)) goto LA3_;
		colontmpD__4 = (NI)0;
		colontmpD__5 = (NI)0;
		{
			if (!(((NI) 5) < x)) goto LA7_;
			colontmpD__4 = ((NI) 1);
			colontmpD_ = colontmpD__4;
		}
		goto LA5_;
		LA7_: ;
		{
			colontmpD__5 = ((NI) 2);
			colontmpD_ = colontmpD__5;
		}
		LA5_: ;
		y = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(((NI) 1) < x)) goto LA11_;
		colontmpD__2 = ((NI) 3);
		y = colontmpD__2;
	}
	goto LA1_;
	LA11_: ;
	{
		colontmpD__3 = ((NI) 4);
		y = colontmpD__3;
	}
	LA1_: ;
}
```

### Expected Output
should be same was what we get without `--gc:arc`, which doesn't have any temporary:
```c
N_LIB_PRIVATE N_NIMCALL(void, foo_t4950525451_1)(NI x) {
	NI y;
	{
		if (!(((NI) 3) < x)) goto LA3_;
		{
			if (!(((NI) 5) < x)) goto LA7_;
			y = ((NI) 1);
		}
		goto LA5_;
		LA7_: ;
		{
			y = ((NI) 2);
		}
		LA5_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(((NI) 1) < x)) goto LA11_;
		y = ((NI) 3);
	}
	goto LA1_;
	LA11_: ;
	{
		y = ((NI) 4);
	}
	LA1_: ;
}
```

### Example 2
```nim
when true:
  type A = object
    a0: int
    a1: array[50, int]

  proc foo(x: int): A =
    if x > 3:
      if x > 5: A(a0: 1)
      else: A(a0: 2)
    elif x > 1: A(a0: 3)
    else: A(a0: 4)

  import std/times

  proc main()=
    let n = 100_000_000
    let t = cpuTime()
    var c = 0
    for i in 0..<n:
      let ai = foo(i)
      c+=ai.a0 + ai.a1[3]
    let t2 = cpuTime()
    echo (c, t2 - t)
  main()
```
nim r -d:danger --gc:arc main:
(100000012, 2.050024)
nim r -d:danger main:
(100000012, 0.079962)
=> 25X slower in this case

### Additional Information
1.5.1 9a81e91fa5d01cd6d60a408d0888dce4a9f49898

the fix should be to generate same code for --gc:refc as for --gc:arc, if possible, eg, transform:
```nim
let ret = if cond: a1 else: a2
=>
var ret {.noInit.}: A # ret is guaranteed to be assigned in each branch
if cond:
  ret = a1
else:
  ret = a2
```

but more generally for expressions, not just for if-expressions

Ideally, this could be handled by semantic pass, before codegen

**Comment by ghost** [comment]
For some reason with latest compiler (dc4cc2dca53e3772efb3654a4ddbbe8350d1db43) the difference is much bigger:
- refc - `(100000012, 0.03969771)`
-  arc - `(100000012, 14.133797404)`

Which accounts to ~350 **times** (!) difference

Modified to use monotimes:
```nim
import std/monotimes

type A = object
  a0: int
  a1: array[50, int]

proc foo(x: int): A =
  if x > 3:
    if x > 5: A(a0: 1)
    else: A(a0: 2)
  elif x > 1: A(a0: 3)
  else: A(a0: 4)

import std/times

proc main()=
  let n = 100_000_000
  let t = getMonoTime()
  var c = 0
  for i in 0..<n:
    let ai = foo(i)
    c+=ai.a0 + ai.a1[3]
  let t2 = getMonoTime()
  echo (c, t2 - t)
main()
```


- refc `(100000012, 40 milliseconds, 258 microseconds, and 678 nanoseconds)`
- arc `(100000012, 14 seconds, 28 milliseconds, 593 microseconds, and 309 nanoseconds)`

**Comment by ghost** [comment]
Update: with Clang there is virtually no difference between ARC and refc. Not sure why, but the times speak for themselves:
- ARC `(100000012, 50 milliseconds, 358 microseconds, and 821 nanoseconds)`
- refc `(100000012, 50 milliseconds, 967 microseconds, and 183 nanoseconds)`


Guess Clang is smart enough to optimize all the temporary variables away...

**Comment by Araq** [comment]
Good enough for closing this then.

**Comment by ghost** [comment]
@Araq is it really fine if with GCC it's 350x slower? I mean Clang works fine, but most people still use GCC nowadays for Nim, even on Windows.
