### ISSUE TITLE
Expression can't be isolated, when passing a ref object between threads

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#18368]
Complete example:  [ring.nim](https://github.com/planetis-m/dumpster/blob/6e0c705bfd2185b37ba041325da95b5ef9fe98fa/multithread/atomics/ring.nim) and [tring.nim](https://github.com/planetis-m/dumpster/blob/6e0c705bfd2185b37ba041325da95b5ef9fe98fa/multithread/atomics/tring.nim)

### Example
Compile tring.nim with `--gc:arc --threads:on`

```nim
type
  Foo = ref object
    id: string

proc producer =
  for i in 0 ..< numIters:
    var p = isolate(Foo(id: $(i + seed)))
    while not rng.push(move p): cpuRelax()
    #echo " >> pushed ", p.id
```

### Current Output

```
 >> popped 99
 >> popped  �4G�P�4G���4G���4G���4G��4G�@�4G�p�4G���4G���4G��4G�0�4G�/home/planetis/code/repos/dumpster/multithread/atomics/tring.nim(27) consumer
/home/planetis/build/Nim/lib/system/io.nim(795) echoBinSafe
/home/planetis/build/Nim/lib/system/io.nim(156) checkErr
/home/planetis/build/Nim/lib/system/io.nim(139) raiseEIO
Error: unhandled exception: errno: 14 `Bad address` [IOError]
```

### Expected Output
Compiles and runs without an error.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0d194cdbf90953f28450c4bf1db744d2c1332996
active boot switches: -d:release --gc:markAndSweep
```

**Comment by planetis-m** [comment]
I would expect extract(value) to work without: https://github.com/nim-lang/Nim/blob/devel/lib/std/channels.nim#L460 It feels like a hack

**Comment by ringabout** [comment]
> I would expect extract(value) to work without: https://github.com/nim-lang/Nim/blob/devel/lib/std/channels.nim#L460 It feels like a hack

This line is not related to isolated, `trySend` passes data between threads by pointers. So if `data` wasn't specified as `wasMoved`, it would be freed twice. `wasMove` tells the compiler not to insert `=destroy` here.

It is also what channel_builtin does: https://github.com/nim-lang/Nim/blob/1b9b8060075efab82912dc33ba64e671d102b999/lib/system/channels_builtin.nim#L383

**Comment by ringabout** [comment]
> Complete example at https://github.com/planetis-m/dumpster/tree/master/multithread/atomics
you need to copy ring.nim and tring.nim

I think that's what was `isolated` designed for. `ref object` cannot be isolated unless they are ref object literals. It is used to prevent data races(make sure there is only one owner of the specified ref object).

Maybe you should do this: 
```nim
    while not rng.push(Person(name: names[i and 3])): cpuRelax()
```

**Comment by planetis-m** [comment]
> If T does not contain a ref or closure type, it is isolated.

Yep, thanks @xflywind for the information, it was very helpful.

**Comment by planetis-m** [comment]
Reopening because the example in https://github.com/nim-lang/RFCs/issues/244 uses JsonNodes which are ref objects. Also the updated test compiles without the error, but crashes at runtime.

**Comment by planetis-m** [comment]
s*** my bad, I blame the heat wave.
