### ISSUE TITLE
Distinct type does not capture inheritance information

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#18363]
### Example
```nim
import typetraits
type
  O = object of RootObj
  OO = object of O
  OODistinct = distinct OO

echo (OODistinct is O) # false
echo (OO is O) # true
echo (OODistinct.distinctBase is O) # true
```
Like with the `{.borrow.}` pragma which allows a `distinct` type to use the operations of its underlying type, I would expect there should be some way of `borrow`ing the inheritance chain as well so something of type `OODistinct` can be passed into, eg. `proc p(o:O) ...`.

### Current Output

```
false
true
true
```

### Expected Output
```
true
true
true
```

### Additional Information

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 5d15bd7b618cda06e3ae88883914467f89d38112
active boot switches: -d:release
```

**Comment by Araq** [comment]
Why would it work like you think it does? A `distinct` type is its own type and even hides the fact that it's an object at all.

**Comment by deech** [comment]
I suppose I figured since a `distinct` type can `borrow` operations it might also be able to do the same with type semantics without a `distinctBase`. If it doesn't work that way that's fine, a misunderstanding on my part.
