### ISSUE TITLE
schubfach & dragonbox & dollar bug

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#18400]
Arrays formatted differently from elements and both formattings incorrect.

### Example
```nim
var s = [-13.888888'f32]
echo s    # [-13.888888359069824]
echo s[0] # -13.333333
var x = 1.23456789012345'f32
echo x # 1.2222222
```

### Current Output
In side comments.

### Expected Output
```
[-13.888888]
-13.888888
1.2345679
```

It seems both schubfach and dragonbox are broken (in different ways) and additionally somehow dispatch from `$` on `openArray[T]` to individual elements is also wrong (promoting to `float64`).

### Additional Information

[The C++ reference dragonbox implementation](https://github.com/jk-jeon/dragonbox) produces -1.3888888E1 for both 32- and 64-bit floats.  While I could provide that program upon request, it seems tangential.

This has been reproduced by at least @disruptek.  I would call the bug(s) showstoppers, personally.  None of GC/release/danger/backend seem have any impact at least for me.
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-30
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: eaa1c3a37754725f91f54f23080980b82c2f2356
active boot switches: -d:release -d:nimUseLinenoise -d:nimHasLibFFI
```

**Comment by Araq** [comment]
Ha, the one place I wasn't sure about is what I got wrong and we had no test to cover it. A classic.

**Comment by c-blake** [comment]
The dragonbox guy just cross checked his impl with ryu and [ryu](https://github.com/ulfjack/ryu) itself has a rather extensive test suite..in particular some 36,000 line [d2fixed_test.cc](https://github.com/ulfjack/ryu/blob/master/ryu/tests/d2fixed_test.cc) which is basically just a large database of tricky cases.  That file looks like it would be very amenable for c2nim and really enhance our test coverage at least for the 64-bit case.  There is probably some analogue for 32-bit floats, too. (EDIT: and of course there may be many other test suites, some even more amenable to translation to Nim...but this is an old problem with many impls/test suites.  So, there should be something easy to just use.)

**Comment by c-blake** [comment]
I know github just auto-closes issues and apologies if you are still working on it, but I now get:
```
[-13.888888359069824]
-13.888888
1.2345679
```
Correct me if I am wrong, but the first row is still wrong in 2 ways - using the wrong output algo, and said algo producing the wrong string.

**Comment by Araq** [comment]
I misread your bug report, my bad.

**Comment by Araq** [comment]
Assuming a convertion to 64 bits (which is a pre-existing behavior), does it really produce the wrong string?

**Comment by c-blake** [comment]
Well, I compiled a C++ program using the reference dragonbox.  I set `float x = -13.888888;`  Then I assigned a `double y = x;` and formatted the `y` and got "-13.888888".  So, I think that ref impl will produce that small result.  The only uncertainty is that the C++ `to_chars` prints out "-1.3888888E1" and it is theoretically possible there is some formatting option that is rounding it.  I did do `-1.3123456789012346E1` the same way and got "-1.3123456789012346E1" to try to eliminate that uncertainty, but I am unfamiliar enough with the library that I could be missing something.

Plus, yeah, it should be the 32-bit schubfach version, too.  Admittedly it is a lot of bugs for a few lines of code... :-)

**Comment by c-blake** [comment]
I can provide that C++ program if it would help.

**Comment by c-blake** [comment]
I will say that the relative error of `-13.888888359069824 + -13.888888 = -3.59...e-07` suspiciously close to what 32-bit float precision is.  So, it is possible that the 32-bit/64-bit issue could be the only remaining bug.  If I just do `echo -13.888888` it works fine, for example.

**Comment by c-blake** [comment]
Also, `echo float64(-13.888888'f32)` also produces "-13.888888".

**Comment by c-blake** [comment]
It may/may not help to observe that while `echo [-13.888888'f32]` ~~fails with~~ gives excess digits, `echo [-13.888888]` ~~succeeds at producing~~ produces just "[-13.888888]".

**Comment by abolz** [comment]
This seems to be an issue with float32/float64 conversions (and calling the wrong conversion routine). Note that
```
13.888888'f32 = 14563555 * 2^-20 = 13.88888835906982421875 (exactly)
```
and this value is exactly representable as a float64. Actually the output of `echo float64(13.888888'f32)` seems to produce the wrong output. The correct outputs should be
```
echo 13.888888'f32  =>  "13.888888"
echo 13.888888'f64  =>  "13.888888"
echo float64(13.888888'f32)  =>  "13.888888359069824"
```
I'm unfamiliar with Nim, so I might be missing something, but
```
echo float64( 13.888888'f32 ) == 13.888888359069824'f64
```
prints `false` in https://play.nim-lang.org/, while it should print `true`.

**Comment by c-blake** [comment]
Thanks @abolz.  The plot thickens! ;-)  Maybe the extra digits are the right answer and my C++ test was somehow flawed, but something is still amiss as you note.  Another maybe helpful code snippet/observation in tracking this down - storing in a variable (even a `let`) alters behavior:
```Nim
let d = float64(-13.888888'f32) # same happens with `var`
echo d                          # "-13.88888835906982"
echo float64(-13.888888'f32)    # "-13.888888"
```
..but if you change the `let` -> `const` the results match (but are maybe incorrect..).

Also, @Araq - does this pre-existing promotion to 64-bits for format only in `$x[0]` but not in top-level `$x` really make sense?

**Comment by juancarlospaco** [comment]
Float sux. 😐
