### ISSUE TITLE
Calling a procedure in an exception handler which re-raise and handle that exception will result in a SIGSEGV

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#18411]
Marked "Showstopper" because we can use safe Nim mechanics to crash the program.

### Example
```nim
proc bar(e: ref Exception) =
  try:
    if e != nil:
      raise e
  except:
    doAssert getCurrentExceptionMsg() == "foo"

proc foo() =
  try:
    raise newException(ValueError, "foo")
  except:
    bar(getCurrentException())

foo()
```

### Current Output

Only happens on `--gc:arc` or `--gc:orc`

```
Traceback (most recent call last)
/tmp/test.nim(14)        test
/usr/lib/nim/lib/system/excpt.nim(89) foo
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Possible Solution

* `pushCurrentException()` doesn't push if the raised exception is the same as the current exception, however after any exception handler the exception is pop-ed unconditionally

### Additional Information
* This is blocking CPS exception handling across continuations.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0f91b67f5c15328330f74a8769aed9961940aab2
active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by Araq** [comment]
Showstopper > Severe.
