### ISSUE TITLE
os.`/` trailing slash behaviour

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#18423]
```nim
import os
echo("/foo/bar" / "") # /foo/bar/ (on <= 1.0) /foo/bar (on > 1.0)
echo("/foo/bar" / "/") # /foo/bar/ (on > 1.0) /foo/bar (on <= 1.0)
```

Feel free to close as Won't Fix if this is expected. I'm reporting it because it broke something in Jester.

I guess I cannot rely on this behaviour and just need to append "/" if it's not at the end of the path.

**Comment by Clyybber** [comment]
I believe this was changed in #13467 ?

**Comment by dom96** [comment]
CC @timotheecour

**Comment by timotheecour** [comment]
indeed, it's intentional.
just to clarify:

since 1.2:
```nim
import os
echo("/foo/bar" / "") # /foo/bar
echo("/foo/bar" / "/") # /foo/bar/
```

1.0 behavior didn't make sense:
```nim
import os
echo("/foo/bar" / "") # /foo/bar/
echo("/foo/bar" / "/") # /foo/bar
```
