### ISSUE TITLE
The error message must contain the name of the package from which the type is taken

### ISSUE THREAD

**Issue by gavr123456789** [nim-lang/Nim#18441]
For example here I have gdk.Window and gtk4.Window. And I cant understand from this error why it doesn't work.  
(You need to guess that you need a window from GDK and not GTK)
![image](https://user-images.githubusercontent.com/30507409/124668675-df346100-deb9-11eb-878f-8b8715705bbb.png)

I think it should look like this:  
```
required type for self: gtk4.Window
  but expression 'window' is of type: gdk.Window
  ```

**Comment by beef331** [comment]
Devel has `--declaredLocs` which enables similar behaviour.
Given:
```nim
import pixie
type Image = object

var a = Image()
encodeImage(a, ffPng)
```
The following error is emitted
```
Error: type mismatch: got <test.Image, pixie.FileFormat>
but expected one of: 
proc encodeImage(image: Image; fileFormat: FileFormat): string [proc declared in /home/jason/.nimble/pkgs/pixie-2.1.0/pixie.nim(55, 6)]
  first type mismatch at position: 1
  required type for image: Image [ref declared in /home/jason/.nimble/pkgs/pixie-2.1.0/pixie/images.nim(9, 3)]
  but expression 'a' is of type: Image [object declared in /tmp/test.nim(2, 6)]

expression: encodeImage(a, ffPng)
```

**Comment by timotheecour** [comment]
see also https://github.com/nim-lang/Nim/pull/18389 which further improves `--declaredLocs` to disambiguate

`--declaredLocs` (and its improvements eg https://github.com/nim-lang/Nim/pull/18389) seem good enough to close this, feel free to re-open if you disagree or have concrete suggestions
