### ISSUE TITLE
Compiler error sysFatal when importing nashorn.nim

### ISSUE THREAD

**Issue by halloleo** [nim-lang/Nim#18455]
The Compiler exits with a  `sysFatal` error when `nashorn.nim` is imported.

### Example

Write the file `app.nim`:

```nim
import nashorn

echo "Hello World!"
```

Download the file [nashorn.nim](https://raw.githubusercontent.com/metagodcore/nimnashorn/master/src/nashorn.nim) from GitHub and compile with

```
nim js  app.nim
```

### Current Output 

```
.................fatal.nim(49)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

_Note: This applies at least to Nim Compiler 1.4.6 under CentOS 6 - I have no way on my Nim machine to install easily a newer version._

### Additional Information

See Nim forum thread [Compiler sysFatal when I include nashorn.nim](https://forum.nim-lang.org/t/8208).

```
$ nim -v
Nim Compiler Version 1.4.6 [Linux: amd64]
Compiled at 2021-04-15
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2b6b08032348939e5d355a6cb4faa0169306c17f
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
@halloleo please reduce to a minimum reproducing example as indicated in issue template

> I have no way on my Nim machine to install easily a newer version.

doesn't `git clone https://github.com/nim-lang/Nim && cd Nim && sh build_all.sh` work? what error does it give?

**Comment by halloleo** [comment]
Can't do easily git on that machine - all downloads have to go through an audit. I _just_ got the `nashorn.nim` file approved. (That is in the first place the reason why I want to run the JavaScript under Nashorn: Nashorn is as part of Java installed while nodejs is not...)

Maybe it is all to hard - and I don't think many people use  `nashorn.nim`...

**Comment by timotheecour** [comment]
then can you get a VM on some cloud provider (or maybe via docker) to test? 
bugs without a simple repro are unlikely to be fixed

**Comment by halloleo** [comment]
If I get a chance I'll install Nim on my personal laptop. _Then_ I can easily test against the current version. 😃

I'll reopen the issue then.
