### ISSUE TITLE
A simple way of checking failure in unittest

### ISSUE THREAD

**Issue by schneiderfelipe** [nim-lang/Nim#18466]
I would like to propose a simple template to mean the opposite of `check` in `unittest` (similar to [`xfail` found in `pytest`](https://doc.pytest.org/en/latest/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail)):

```nim
template fail(conditions: auto): auto =
  ## A convenience meaning the exact opposite of `check`.
  check(not (conditions))
```

It would allow simple failures to be checked as [follows](https://play.nim-lang.org/#ix=3skD)

```nim
import unittest


test "works":
  check 2 + 2 == 4

test "does not work":
  fail 2 + 3 == 4
```

```
[OK] works
[OK] does not work
```

**Comment by kaushalmodi** [comment]
I find `check not` to be more evident as to what the user is trying to test.

```nim
import std/[unittest]


test "works":
  check 2 + 2 == 4

test "does not work":
  check not (2 + 3 == 4)
  check 2 + 3 != 4
```

A kind of related available macro in `unittest` is [`expect`](https://nim-lang.github.io/Nim/unittest#expect.m%2Cvarargs%5Btyped%5D%2Cuntyped) which checks whether an exception got triggered.

**Comment by schneiderfelipe** [comment]
Hi, @kaushalmodi thanks for the suggestion, I agree `check not` is very evident. I believe I haven't properly motivated my suggestion. The thing is that sometimes the parentheses are annoying. Your example does not work without parentheses, for instance ([playground](https://play.nim-lang.org/#ix=3szF)):

```nim
import std/[unittest]


test "does not work":
  check not (2 + 3 == 4)
  # =>
  # [OK] does not work

  check not 2 + 3 == 4
  # =>
  # /tmp/asdf.nim(6, 18): Check failed: not 2 + 3 == 4
  # not 2 + 3 was 0
  # [FAILED] does not work
```

Of course, this is really fine for simple cases like this. As a motivation for a more interesting use case, I've been working on a small library for property-based testing ([quickcheck](https://github.com/schneiderfelipe/quickcheck)) which works with `check`:

```nim
import unittest, quickcheck, algorithm


template fail(conditions: auto): auto =
  ## A convenience meaning the exact opposite of `check`.
  check(not (conditions))


test "reversed invariant":
  check satisfy do (xs, ys: string) -> bool:
    (xs & ys).reversed == ys.reversed & xs.reversed
  # =>
  #   +++ OK, passed 100 quick checks.


  # Using `check not` without parentheses:
  check not satisfy do (xs, ys: string) -> bool:
    (xs & ys).reversed == xs.reversed & ys.reversed
  # =>
  # /tmp/asdf.nim(3, 6) template/generic instantiation of `test` from here
  # /tmp/asdf.nim(11, 3) template/generic instantiation of `check` from here
  # /home/schneider/.choosenim/toolchains/nim-1.4.8/lib/pure/unittest.nim(677, 14) Error: type mismatch: got
  # <proc (f: proc): bool, void>
  # but expected one of:
  # proc `not`(a: typedesc): typedesc
  #   first type mismatch at position: 1
  #   required type for a: typedesc
  #   but expression 'satisfy' is of type: proc (f: proc): bool


  # Using `check not` and parentheses:
  check not (
    satisfy do (xs, ys: string) -> bool:
      (xs & ys).reversed == xs.reversed & ys.reversed  # exchanged `xs` and `ys`
  )
  # =>
  #   *** Failed! Falsifiable (after 1 quick check).


  # Using `fail`:
  fail satisfy do (xs, ys: string) -> bool:
    (xs & ys).reversed == xs.reversed & ys.reversed  # exchanged `xs` and `ys`
  # =>
  #   *** Failed! Falsifiable (after 1 quick check).


  # =>
  # [OK] reversed invariant
```

So, although a small convenience, something like `fail` might be more ergonomic for tests that don't fit in a single line.

**Comment by saem** [comment]
`check not` isn't better at all. Negations are harder to parse, at the very least for native English speakers.

We're using the _command_ syntax which is "speaking" in the imperative form and it's much more natural to say `fail`, the imperative command, than `check not`.

With that said, `fail` shouldn't take a condition, it should simply fail that test, with an optional message, it reads the same way as you'd want something like a `skip` or `pass`.

I think a better term might be something like `disallow` or `falsify`.

**Comment by juancarlospaco** [comment]
I said this a lot of times, but those arbitrary "aliases" like
`fail`, `skip`, `ignore`, `pass`, `disallow`, `falsify`, `checkNot`, etc
are just the lack of a proper DBC module in stdlib,
thats the standard way to do these kind of condition checking since decades.
