### ISSUE TITLE
Wiki page 'Editor Support' - add item about CudaText

### ISSUE THREAD

**Issue by Alexey-T** [nim-lang/Nim#18462]
Nim lexer is present in CudaText addons. To install it, use menu item "Plugins / Addons Manager / Install".

Plugin "LSP Client" supports Nim LSP server good. Config file: https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_Nim

**Comment by kaushalmodi** [comment]
@Alexey-T I believe anybody should be able to edit any wiki page or even add a new wiki page in this repo. You don't need to open an issue for that.
