### ISSUE TITLE
Can't access StringTableRef at compile-time with the JavaScript backend

### ISSUE THREAD

**Issue by schneiderfelipe** [nim-lang/Nim#18489]
It's OK to create a `StringTableRef` at *compile-time*, iterate over it, etc., but accessing any key throws a compile-time error in JS.

### Example

```nim
import strtabs

macro m =
  var t = {"name": "John"}.newStringTable
  echo t["name"]

when isMainModule:
  var t = {"name": "John"}.newStringTable
  echo t["name"]  # works fine
  
  m()  # errors
```

### Current Output

With the JavaScript backend (see C backend below):

```
$ nim js -d:danger -r --verbosity=0 asdf.nim
.............
/tmp/asdf.nim(11, 4) template/generic instantiation of `m` from here
/home/schneider/.choosenim/toolchains/nim-1.4.8/lib/system/jssys.nim(327, 3) Error: cannot generate VM code for asm "    if ("a
```

Commenting out the error line works fine with JS:

```
$ nim js -d:danger -r --verbosity=0 asdf.nim  # after commenting out the error line
.............
/tmp/asdf.nim(3, 7) Hint: 'm' is declared but not used [XDeclaredButNotUsed]
John
```

### Expected Output

With the C backend:

```
$ nim c -d:danger -r --verbosity=0 asdf.nim
...................
John
John
```

### Additional Information

The relevant function of `lib/system/jssys.nim` seems to be `cmpStrings`:

https://github.com/nim-lang/Nim/blob/12da32a891b08f34acbb676001f0c211ecfe1af8/lib/system/jssys.nim#L333-L343

Nim version:

```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 44e653a9314e1b8503f0fa4a8a34c3380b26fff3
active boot switches: -d:release
```

**Comment by ringabout** [comment]
Can you try it on [devel](https://github.com/nim-lang/nightlies)? It seems to be fixed already.

**Comment by schneiderfelipe** [comment]
> Can you try it on [devel](https://github.com/nim-lang/nightlies)? It seems to be fixed already.

Yes, the example works with devel, thanks!

```bash
$ choosenim devel
   Switched to Nim #devel

$ nim js -d:danger -r --verbosity=0 asdf.nim
John
John
```
