### ISSUE TITLE
`iterator []` with  fails to resolve overload when used with `head[arg]` syntax. 

### ISSUE THREAD

**Issue by haxscramper** [nim-lang/Nim#18492]
### Example

```nim
type Custom = distinct string

iterator `[]`(a: Custom, r: int): char = 
  for q in 0 .. r:
    yield a.string[q]
    
for val in Custom("test")[2]:
  echo val
```

### Current Output

Fails with compilation error
```
Error: type mismatch: got <Custom, int literal(2)>
but expected one of: 
iterator `[]`(a: Custom; r: int): char
  first type mismatch at position: 0
proc `[]`(s: string; i: BackwardsIndex): char
  first type mismatch at position: 0
```

### Expected Output
```
t
e
s
```

### Additional Information

- Calling with `` `[]`(Custom("test"), 2)`` works correctly
- Other operators (like `Custom("test) -> 2`) also work correctly

### Compiler version

```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf
```

Issue present on `devel` as well.

**Comment by ynfle** [comment]
> Defining [] as an iterator with argument other than Slice works correctly (```iterator `[]`(a: Custom, r: int): char =```)

This throws the same error for me

**Comment by haxscramper** [comment]
Yes, it seems like I wrote a check for that incorrectly. Updated issue description
