### ISSUE TITLE
Arc/Orc with `--threads:on`; `getOccupiedMem()` always zero

### ISSUE THREAD

**Issue by GordonBGood** [nim-lang/Nim#18494]
As per the title:  compile with "--gc:arc --threads:on" or "--gc:orc --threads:on".

### Example
```nim
echo "pre-mem:  ", getOccupiedMem()
var tst = newSeq[int](10)
echo "post-mem:  ", getOccupiedMem()
```

### Current Output
```
pre-mem:  0
post-mem:  0
```

### Expected Output
```
pre-mem:  0
post-mem:  136 # 144 with Nim versions 1.4.0 and newer
```

### Additional Information
This bug has been present ever since `--gc:arc` and `--gc:orc` hit production with Nim version 1.2.0 and is still there up to latest devel as of 7h August 2021.

**This issue will affect all memory leak acceptance tests when using threading with Arc/Orc, so is extremely important!**  As my contributions have much to do with improving the threading ecosystem, I really need this to be fixed ASAP.

This turns out to be a documentation issue, see comment below!

```
$ nim -v
All versions between:

Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-23
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release

up to:

Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-08-04
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 6563a685c1076cb5342f65d192b8f2a983220dba
active boot switches: -d:release
```

**Comment by GordonBGood** [comment]
After searching the repo extensively, this is actually somewhat expected but undocumented behavior:  With `--threads:on`, the expected function to call to get the occupied memory is changed from `getOccupiedMem()` to `getOccupiedSharedMem()`.  When that substitution is made, the above code snippet works properly with ARC/ORC and `--threads:on`:

```nim
echo "pre-mem:  ", getOccupiedSharedMem()
var tst = newSeq[int](10)
echo "post-mem:  ", getOccupiedSharedMem()
```
returns:

```
pre-mem:  0
post-mem:  136 # 144 for versions 1.4.0 and newer
```
as expected.
The functions that are not documented that **must be used instead of the non-Shared versions with** `--threads:on` are as follows:  `getOccupiedSharedMem*()`,  `getFreeSharedMem*()`, and `getTotalSharedMem*()`.

**This is not documented anywhere, at least in current documents!** Of course the reason it isn't documented "officially" is that the documentation is generated automatically from the source files from embedded documentation (##) comments, but as these three functions are behind a `when` barrier only compiled when threading is turned on and since documentation is generated without threading turned on, these don't appear.

**Comment by Araq** [comment]
In this case it seems wiser to patch the library rather than documenting yet another quirk.

**Comment by GordonBGood** [comment]
@araq:

> In this case it seems wiser to patch the library rather than documenting yet another quirk.

I agree, in pointing out that it is very difficult to find documentation for these three "Shared" versions of `proc`'s, I didn't mean that they **should** be documented.

I think we agree that the best solution would be that there is no "Shared" versions and the shared behavior should automatically be assumed when the threads on switch is thrown.  I am just not certain how to accomplish this reliably although there are other instances of functionality being replaced when a "switch" is thrown.
