### ISSUE TITLE
Wrong compile date in -v

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#18508]
I just bootstrapped a compiler at 00:30 on 17/07/2021:

```
$ ./bin/nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-07-16
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 25efb5386293540b0542833625d3fb6e22f3cfbc
active boot switches: -d:release
$ ls -l ./bin/
total 6416
-rwxrwxrwx 1 dom dom      64 Jul  2 11:05 empty.txt
-rwxrwxrwx 1 dom dom 6565144 Jul 17 00:30 nim
-rwxrwxrwx 1 dom dom     957 Jul  2 11:05 nim-gdb
lrwxrwxrwx 1 dom dom       7 Jul  2 11:05 nim-gdb.bash -> nim-gdb
-rwxrwxrwx 1 dom dom     369 Jul  2 11:05 nim-gdb.bat
```

The date is wrong.

Why did we remove the time from this version info btw?

**Comment by Varriount** [comment]
Was it at  00:30 GMT?

**Comment by dom96** [comment]
BST, whatever that is.

**Comment by juancarlospaco** [comment]
We should refine that info, `--version` for humans, `--dump` for machines https://github.com/nim-lang/Nim/issues/13740

**Comment by Araq** [comment]
> Why did we remove the time from this version info btw?

Reproducible builds.

**Comment by dom96** [comment]
> Reproducible builds.

Won't the date also create a build that isn't reproducible?

**Comment by Araq** [comment]
Probably but the chances are reduced.
