### ISSUE TITLE
os.putEnv is buggy, and should use C `setenv`, not `putenv`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18502]
As noticed by @juancarlospaco, os.putEnv is buggy and should use C `setenv`, not `putenv`; quoting relevant passage from https://github.com/timotheecour/Nim/issues/783:

Python has a Warning in the documentation:

> Note: On some platforms, including FreeBSD and Mac OS X, setting environ may cause memory leaks. Refer to the system documentation for putenv().

- https://docs.python.org/3.10/library/os.html#os.putenv

Nim uses `putenv` from C:

- https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/osenv.nim#L224
- https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/osenv.nim#L48

StackOverflow recommends using `setenv` from C:

- https://stackoverflow.com/questions/4777909/how-does-one-maintain-memory-with-the-putenv-system-call

### Example
```nim
import os
putEnv("foo=bar", "baz")
echo getEnv("foo")
```

### Current Output
prints: "bar=baz"

### Expected Output
prints: ""

### Additional Information
1.5.1 1d6863a7899fd87fd9eb017ae370ef37db18ad32
I haven't investigated whether there are memory leaks due to using C putenv instead of C setenv, but the example above is enough to show the behavior is buggy

**Comment by juancarlospaco** [comment]
Because is a memory leak, would be better to mention `memory leak` in the title, for search, filtering, and historical purposes, 
besides "is buggy" description in a Bug list is not too useful IMHO.
