### ISSUE TITLE
Iterator doesn't run at compile time after removing {.closure.} pragma

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#18528]
To reproduce this issue a multi-compilation step is required

### Example
Run this and get expected output
```nim
iterator defaultFor[T](arg: typedesc[T], n: int): T =
  for i in 0..n-1: 
    yield default(arg)

static:
  for i in int.defaultFor(5):
    echo $i
```
then edit iterator signature by adding `{.closure.}` pragma to it. Compile and let it fail with `Error: Closure iterators are not supported by VM!`

```nim
iterator defaultFor[T](arg: typedesc[T], n: int): T {.closure.} =
  for i in 0..n-1: 
    yield default(arg)

static:
  for i in int.defaultFor(5):
    echo $i
```
then switch back to first version without changing anything else, compile and run. You get compilation successful but you won't get any output.
You get correct output only by forcing rebuild by adding any code (and possibly cleaning compilation cache)

### Current Output
```
*no output*
```

### Expected Output
```
0
0
0
0
0
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c0e8199acc9f49caa36bae34d103600d112b66f3
active boot switches: -d:release
```

**Comment by beef331** [comment]
No bug, compiler didnt generate any C code since the compiler didnt finish processing Nim code in the second run, meaning generated hashs were still valid. Do this with `nim c -f  your.nim` and it'll always echo the output.
