### ISSUE TITLE
nimyaml doesn't work on devel anymore

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#18543]
# Issue 1
```
git clone https://github.com/flyx/NimYAML
nim r test/tserialization
```

Gives

```
stack trace: (most recent call last)
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(1685, 10) getCustomPragmaVal
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(134, 7) template/generic instantiation of `suite` from here
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(559, 8) template/generic instantiation of `test` from here
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(562, 9) template/generic instantiation of `load` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1341, 14) template/generic instantiation of `construct` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1319, 19) template/generic instantiation of `constructChild` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1166, 18) template/generic instantiation of `constructObject` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(416, 19) template/generic instantiation of `constructChild` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1145, 20) template/generic instantiation of `constructObject` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(904, 25) template/generic instantiation of `constructObjectDefault` from here   
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(840, 29) template/generic instantiation of `getCustomPragmaVal` from here       
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(1685, 10) Error: O doesn't have any custom pragmas
```
It works on Nim 1.4.8

Related PR probably:
https://github.com/nim-lang/Nim/pull/11526
https://github.com/nim-lang/Nim/pull/17725
etc

Similarly
arraymancer, weave don't work on devel too.
https://github.com/mratsim/Arraymancer/issues/505
https://github.com/mratsim/weave/pull/175

**Comment by ringabout** [comment]
# Issue 2

`nim lexerTests`

```
/home/runner/.nimble/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
/home/runner/work/NimYAML/NimYAML/yaml/private/lex.nim(136, 6) Hint: 'lineWithMarker' is declared but not used [XDeclaredButNotUsed]
io.nim(866)              writeFile
Error: unhandled exception: cannot open: /home/runner/.cache/nim/tlex_d/test/tlex.json [IOError]
```
`nim r tests/tlex` works and `nim lexerTests` works on Nim 1.4.8, quite strange.

**Comment by narimiran** [comment]
> Related PR probably: #11526

`git bisect` shows exactly this PR that broke `nim r test/tserialization`.

I'll see if I can find the same for Arraymancer and Weave.

**Comment by Araq** [comment]
Why is "nimyaml" not in the list of important packages?

**Comment by ringabout** [comment]
> I'll see if I can find the same for Arraymancer and Weave.

Nice!

IMO, the package which calls compiler APIs or Macros deeply is likely to be broken. If the author want to maintain them, they should submit it to important packages(a compile test at least). For instance I ever wanted to try https://github.com/disruptek/dust but it had been broken at that time.

In other word, now I think https://github.com/beef331/nimscripter, https://github.com/SciNim/Unchained and the stuffs of https://github.com/haxscramper should be added to important packages. We can also collect the intentions to important packages periodically on Nim forum or consider the packages on "Nim monthly".

**Comment by disruptek** [comment]
Sure, because Nim needs more excuses to not fix bugs?

No thanks.  Leave my stuff out of it and fix the damned language, please.

While I'm at it, DUST broke because Nim was changed for IC.  Where is IC?

**Comment by Araq** [comment]
> While I'm at it, DUST broke because Nim was changed for IC. Where is IC?

It's stagnating, some compiler devs have to fix showstopper bugs, others have moved on to help with "continuations". ;-)

**Comment by narimiran** [comment]
> Issue 2; `nim lexerTests`

According to `git bisect`, this was broken by https://github.com/nim-lang/Nim/pull/18100 (cc @timotheecour).

**Comment by ringabout** [comment]
> According to git bisect, this was broken by #18553 (cc @timotheecour).

wrong link?

**Comment by narimiran** [comment]
> wrong link?

Yep, it was. Fixed the link.

**Comment by timotheecour** [comment]
fixing issue 2 in https://github.com/nim-lang/Nim/pull/18555
