### ISSUE TITLE
[cpp] segfault in a loop while parsing JSON

### ISSUE THREAD

**Issue by veksha** [nim-lang/Nim#18552]
Hello. i'm new and learning. got this weird error while developing my application with --gc:orc
and compiling it with cpp backend `nim cpp -r --gc:orc qqc.nim`

### Example
```nim
import segfaults
import json

let j1 = """ {} """
let j2 = """ {"x":"1"} """

for i in 0..1:
    stdout.write i,":"
    try:
        let node = parseJson((if i == 0: j1 else: j2))
        echo node["x"]
    except:
        echo getCurrentExceptionMsg()
```

### Current Output
```
0:key not found: x
1:"1"

D:\Programm\Nim\Nim-devel\lib\system\fatal.nim(53) qqc
Error: unhandled exception: Could not access value because it is nil. [NilAccessDefect]
```

### Expected Output
```
0:key not found: x
1:"1"
```

### Possible Solution

* use --gc:refc
or
* use c backend with any gc

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-07-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f86a530214d56f39664d6aaca3ddddf3b2fdba0c
active boot switches: -d:release
```

**Comment by Araq** [comment]
The "segfaults" module is not supported with arc/orc. Will add a warning.

**Comment by veksha** [comment]
> The "segfaults" module is not supported with arc/orc. Will add a warning.

but without "segfault" module the problem persists
### output
```
0:key not found: x
1:"1"

Error: execution of an external program failed: 'd:\Programm\Nim\nimwrap\sources\qqc.exe '
```

**Comment by Araq** [comment]
For me it worked. Need to check --os:windows

**Comment by ringabout** [comment]
Original case works for me too. I'm on win10.

```nim
import segfaults
import json

let j1 = """ {} """
let j2 = """ {"x":"1"} """

for i in 0..1:
    stdout.write i,":"
    try:
        let node = parseJson((if i == 0: j1 else: j2))
        echo node["x"]
    except:
        echo getCurrentExceptionMsg()
```

Using `nim c -r --gc:orc test3.nim`

Works on Nim devel and Nim 1.4.8
```
nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-07-21
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by veksha** [comment]
further investigation shows that error actually happens only when compiling with cpp backend and gc:orc.
like this `nim cpp --gc:orc -r test3.nim`

(updated issue)

**Comment by ringabout** [comment]
The program segfaults with cpp backend(with or without arc) on Win10
```nim
try:
  raise
except:
  discard
```

`SIGSEGV: Illegal storage access. (Attempt to read from nil?`

works on C backend

**Comment by heterodoxic** [comment]
> The program segfaults with cpp backend(with or without arc) on Win10
> 
> ```nim
> try:
>   raise
> except:
>   discard
> ```
> 
> `SIGSEGV: Illegal storage access. (Attempt to read from nil?`
> 
> works on C backend

Great find! There's another C++ codegen issue going on here, though: nothing gets rethrown, which is illegal in C++, causing a std::terminate call (cf. https://en.cppreference.com/w/cpp/language/throw). This find deserves another issue being raised IMHO, and the fix seems pretty trivial, AFAIU (will try to deliver it ASAP).
