### ISSUE TITLE
Warn on dangling `cstring` return

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#18550]
```nim
proc f(c: char): cstring =
  var x = newString(109*1024*1024)
  x[0] = c
  x
 
var v = f('a')
GC_fullcollect()

var v2 = f('b')

debugecho v[0] # prints `b`
```

this prints `b` because the old string gets collected. One can imagine safe code that returns `cstring`, but returning the `cstring` conversion of a local `string` should be warned about so as to avoid this loophole.

Double points for the conversion being implicit.

**Comment by Araq** [comment]
It's high time we deprecate this loophole. Sorry for not having done it years ago. :-(
