### ISSUE TITLE
Returning a proc named result is accepted by the compiler but segfaults

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#18564]
### Example
```nim
proc p(): proc() =
  proc result = echo "hello world"

(p())()
```

### Current Output

```
nim c -r --verbosity\:0 --hint\[Processing\]\:off --excessiveStackTrace\:on /home/deech/Nim/functest.nim
/home/deech/Nim/functest.nim(2, 8) Hint: 'result' is declared but not used [XDeclaredButNotUsed]
Traceback (most recent call last)
/home/deech/Nim/functest.nim(4) functest
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
Error: execution of an external program failed: '/home/deech/Nim/functest '
```

### Expected Output
```
hello world
```

### Additional Information
Changing it to this works but the compiler should catch the above:
```nim
proc p(): proc() =
  result = proc () = echo "hello world"

(p())()
```

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-07-12
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 195300a938c7c8dd4ec7db3ca7cc76dddeab953e
active boot switches: -d:release
```

**Comment by Araq** [comment]
No bug here, you don't return the inner proc at all so you return a "nil" proc which crashes when you try to call it.

**Comment by Araq** [comment]
See also https://github.com/nim-lang/RFCs/issues/378 (upvote it) :-)

**Comment by deech** [comment]
I think the bug here is that in the first example `result` is manually initialized but the compiler doesn't see that `proc result() ...` and `result = proc () ...` are equivalent.

**Comment by Araq** [comment]
> that proc result() ... and result = proc () ... are equivalent.

They are not equivalent at all. In one case you **declare** a proc named `result` (i.e. the builtin result is shadowed), in the other case you assign an anon proc to `result`.
