### ISSUE TITLE
Method dispatch is slow

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#18612]
Currently method dispatch is generated as a bunch of `isObj` checks (depends on hierarchy size), which in turn uses `strstr` to check subtype relationship. Funnily enough it gets pretty noticeable in the profiler.

What's the status of vtable method dispatch implementation?

**Comment by Araq** [comment]
vtable is beyond reach but we can do some caching so that it's about as fast as the old runtime's implementation.

**Comment by ringabout** [comment]
I have run the benchmark on Nim forum -> https://forum.nim-lang.org/t/3702

https://github.com/mratsim/Arraymancer/blob/master/benchmarks/implementation/proc_method_closure_bench.nim

-d:release ---gc:refc

```
 Proc with ref object 0.157
 Closures 3.269
 Methods 0.5680000000000001
```

-d:release ---gc:arc

```
 Proc with ref object 0.118
 Closures 2.481
 Methods 10.77
```

-d:release --gc:arc -d:useMalloc

```
 Proc with ref object 0.206
 Closures 15.652
 Methods 12.798
```

18x slower than before
nearly 100x slower than regular procs

**Comment by yglukhov** [comment]
> ... about as fast as the old runtime's implementation.

Speaking of which, `isObjSlowPath` takes an embarrassing 2.21% of profiler scale :/

**Comment by Varriount** [comment]
> 
> 
> vtable is beyond reach but we can do some caching so that it's about as fast as the old runtime's implementation.

What prevents vtable from being feasible?

**Comment by Araq** [comment]
> What prevents vtable from being feasible?

Nim's ``method`` design and the current compiler architecture. I'm flirting with copying more of Modula 3's (or C++'s) design but it's way too early for an RFC.

**Comment by xflywind** [comment]
> https://github.com/mratsim/Arraymancer/blob/master/benchmarks/implementation/proc_method_closure_bench.nim

I tried the same cache method as before, gives
`koch temp c -r --gc:arc -d:danger test6.nim`
```
 Proc with ref object 0.151
 Closures 2.157
 Methods 0.6790000000000003
```
