### ISSUE TITLE
Can't construct identifier in template

### ISSUE THREAD

**Issue by oprypin** [nim-lang/Nim#1863]
``` nim
template test(cls: expr): expr {.immediate.} =
  `"new" cls`[int]()   # (same error without quotes)

var a = test(seq)
```

(2, 10) Error: identifier expected, but found '`(system.new|system.new|system.new|...) seq`'

Workaround...

``` nim
template test(cls: expr): expr {.immediate.} =
  `ne w cls`[int]()

var a = test(seq)
```

**Comment by BlaXpirit** [comment]
As it is right now, the identifier construction syntax seems very limited to me, and even difficult to read.

The `"` quotes syntax that I tried seems to make no change whatsoever, but it would be nice if it was added to the language and allowed any text to be passed in without parsing it in any way.

**Comment by Araq** [comment]
You currently have to use a macro for this but it is not a bug.
