### ISSUE TITLE
wiki might have missleading content

### ISSUE THREAD

**Issue by MarcWeber** [nim-lang/Nim#18639]
https://github.com/nim-lang/Nim/wiki/Nim-for-TypeScript-Programmers
says nim has dependent types. Couldn't find it in docs. Discord told me 'don't have this'
So maybe fix that [x] or explain what it means ?

**Comment by juancarlospaco** [comment]
According to Wikipedia a "dependent type" is:

> In computer science and logic, a dependent type is a type whose definition depends on a value. 
> A "pair of integers where the second is greater than the first" is a dependent type,
> because of the dependence on the value. 

I think you can implement it via Concepts, should be doable.

I did not add that specific feature in the wiki, but feels like it is not too crazy to be there anyway.

Wiki says you can directly edit it without opening bugs in the repo.

:)

**Comment by konsumlamm** [comment]
> According to Wikipedia a "dependent type" is:
> 
> > In computer science and logic, a dependent type is a type whose definition depends on a value.
> > A "pair of integers where the second is greater than the first" is a dependent type,
> > because of the dependence on the value.
> 
> I think you can implement it via Concepts, should be doable.

The important part is that the values a type depends on don't necessarily have to be known at compile time, which is (afaik) impossible in Nim.

**Comment by juancarlospaco** [comment]
Wikipedia definition does not differentiate between compile-time and run-time 🤷

**Comment by konsumlamm** [comment]
> Wikipedia definition does not differentiate between compile-time and run-time :shrug:

Yeah, but Nim does... That just proves my point, the value doesn't have to be known at compile time.

**Comment by juancarlospaco** [comment]
Therefore it is still a dependent type, maybe not the same as in other programming languages but still is.

It is like saying "Nim does not have array types", 
because `array` is compile-time, but Nim does have `array`... 🤷

It is like saying "Nim does not have integer types", 
because in Python I can put `uint64.high * 9` in `int` but Nim cant, but Nim does have `int`... 🤷

**Comment by juancarlospaco** [comment]
Another example `JsonNode` does not know the value of floats at compile-time,
but if the value is `NaN` or `Inf` it will be a `string` instead of `float` depending on the value.

You can use metaprogramming to create your own too.

**Comment by dom96** [comment]
Feel free to edit the wiki to fix it :)

**Comment by Araq** [comment]
The wiki has been updated.
