### ISSUE TITLE
Wrong line number in error message

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#18647]
## Example 1
```nim
type A = object
  bar: int

let a: ref A = nil

proc foo(a: ref A) =
  if a == nil:
    echo "nil"
  else:
    echo a[]

foo(a)

a[] = A(bar: 42)
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
nil
Traceback (most recent call last)
.../test.nim(12) test
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '.../test '
```

### Expected Output
```
.../test.nim(14)
```

## Example 2

**The following example is worse**

```nim
type A = object
  bar: int

let a: ref A = nil

proc foo(a: ref A) =
  if a == nil:
    echo "nil"
  else:
    echo a[]

# foo(a)

a[] = A(bar: 42)
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
```
Traceback (most recent call last)
.../test.nim(4) test
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '.../test '
```

### Expected Output
```
.../test.nim(14)
```

```
$ nim -v
Nim Compiler Version 1.4.8
```

**Comment by rockcavera** [comment]
I reported something similar/identical [here](https://github.com/nim-lang/Nim/issues/13159).

**Comment by ringabout** [comment]
fixed
