### ISSUE TITLE
Passing anonymous proc params to templates may fail

### ISSUE THREAD

**Issue by etan-k** [nim-lang/Nim#18648]
Passing an anonymous proc to a template may fail under Nim 1.2.12.

### Example
```nim
type
  X* = ref object
    bar: proc (p: proc(v: openArray[byte]))

template foo(x: X, p: proc(v: openArray[byte])) =
  x.bar(p)

X().foo(proc(v: openArray[byte]) = discard @v)
```

### Current Output
```
Error: internal error: expr: param not init v_4602025
```

### Expected Output
Compilation should succeed

### Possible Solution
* Defining a named proc and passing the proc by name works fine.
* Using a proc instead of a template works fine.

### Additional Information
* This bug is only present on the 1.2 branch of Nim.
* On 1.4, the bug has been fixed as of 341be0b61cc0603dc921c99b891208dcda274c98.
* Backporting said commit on top of 1.2 fixes the bug, but this may introduce breaking changes as the AST representation of procs is modified.

```
$ nim -v
Nim Compiler Version 1.2.13 [MacOSX: amd64]
Compiled at 2021-08-05
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 76560576d2dd8ab1876fd4f81029d55467088354
active boot switches: -d:release
```

**Comment by metagn** [comment]
As mentioned in the issue, works in 1.4 and now
