### ISSUE TITLE
db_mysql: bug with queries with character `?` in strings

### ISSUE THREAD

**Issue by bolinocroustibat** [nim-lang/Nim#18650]
In `db_mysql` library, it seems that when a "?" character is in a string to be written in a DB field, it returns an error.

For example:

`̶d̶b̶.̶e̶x̶e̶c̶(̶s̶q̶l̶(̶"̶R̶E̶P̶L̶A̶C̶E̶ ̶I̶N̶T̶O̶ ̶t̶a̶b̶l̶e̶ ̶"̶ ̶&̶ ̶(̶u̶r̶l̶,̶a̶n̶o̶t̶h̶e̶r̶_̶f̶i̶e̶l̶d̶)̶ ̶&̶ ̶"̶V̶A̶L̶U̶E̶S̶ ̶(̶'̶h̶t̶t̶p̶:̶/̶/̶d̶o̶m̶a̶i̶n̶.̶c̶o̶m̶/̶t̶e̶s̶t̶?̶p̶a̶r̶a̶m̶=̶1̶'̶,̶ ̶'̶1̶2̶3̶'̶)̶;̶"̶)̶)̶`̶
EDIT: `db.exec(sql("REPLACE INTO table (url,another_field) VALUES ('http://domain.com/test?param=1', '123');"))`

Output:
`
/usr/local/Cellar/nim/1.4.8/nim/lib/impure/db_mysql.nim(162) exec
/usr/local/Cellar/nim/1.4.8/nim/lib/impure/db_mysql.nim(144) dbFormat
/usr/local/Cellar/nim/1.4.8/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
`
After several tests it would seem that it's related to the `?` character in the url field. Any idea on why and how to solve that?

Nim Compiler Version 1.4.28

**Comment by simonkrauter** [comment]
I think your code has several issues.
A working example looks like this:
```nim
var db = db_sqlite.open("db.sqlite3", "", "", "")
db.exec(sql("CREATE TABLE table1 (url TEXT, other_field INT);"))
db.exec(sql("INSERT INTO table1 (url, other_field) VALUES (?, ?);"), "http://domain.com/test?param=1", 123)
```
_Edit: The escaping of ? was wrong._

**Comment by bolinocroustibat** [comment]
Sorry, indeed my example was mistaken. While I'm at it, more precision: this is assuming there is a MySQL connection already established of course, and that there is a table existing, with the `url` field in my case being a MySQL VARCHAR field.

Anyway

`db.exec(sql("INSERT INTO table (url,another_field) VALUES ('test', '123');"))`
...is working as expected with no error, writing in the DB, while:

`db.exec(sql("INSERT INTO table (url,another_field) VALUES ('test?', '123');"))`
...throw the above mentioned error.

Is that normal?

I also tried with the escaping characters like in your example:
`db.exec(sql("INSERT INTO table (url,another_field) VALUES ('test\\?', '123');"))`
...with no chance.

**Comment by simonkrauter** [comment]
The escaping of ? in my example was wrong. I think escaping is not possible.
The ? is a placeholder for a value, which will be passed as additional parameter to ``db.exec()``. This means, in the SQL query you write ? instead of the URL, and you add the URL string as parameter.

**Comment by bolinocroustibat** [comment]
>The ? is a placeholder for a value, which will be passed as additional parameter to db.exec(). This means instead of the URL you write ? and add the URL string as parameter.

I know about parameter substitution with `?` as a placeholder, but I believe the SQL query without parameter substitution should work anyway, like it does in native SQL or SQL librairies in other languages. In my case the `?` is inside a string (i.e. inside quotes) so I don't see why it should be read as the parameter placeholder.

My point is that it looks like the character `?`would be mistakenly written as the placeholder by the lib, even when inside a string.

(I simplified my example, I don't use parameter substitution with ? placeholder since I insert many rows at once. My example shows only the inserting of one row.)

**Comment by Araq** [comment]
You're supposed to use:

```nim

db.exec(sql("INSERT INTO table1 (url, other_field) VALUES (?, ?);"), "http://domain.com/test?param=1", 123)

```
