### ISSUE TITLE
compiler crash on {.push injectstmt: echo"hello".}

### ISSUE THREAD

**Issue by veksha** [nim-lang/Nim#18666]
Don't know if its even legal code (is it?), however compiler should not crash.

### Example
```nim
{.push injectstmt: echo"hello".}
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Additional Information

happens on all versions of Nim.

```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-08-09
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 8ce782d463b0bca091be5a34db190dc441c23ce4
active boot switches: -d:release
```

**Comment by timotheecour** [comment]
it's experimental / half-broken, refs https://github.com/nim-lang/Nim/pull/18300

**Comment by Araq** [comment]
`injectstmt` can savely be removed afaict.
