### ISSUE TITLE
Porting Nim to Zephyr RTOS

### ISSUE THREAD

**Issue by elcritch** [nim-lang/Nim#18684]
This is a meta-issue for porting Nim to run on [https://www.zephyrproject.org/](Zephyr RTOS). 

From Zephyr's homepage it's described as: 

> The Zephyr Project is a scalable real-time operating system (RTOS) supporting multiple hardware architectures, optimized for resource constrained devices, and built with security in mind.

Currently Nim code compiles after a minor tweak. However, my goal is to get a proper Nim OS support for Zephyr, similar to FreeRTOS. Since I'm unsure how much work this will involve I'm creating this issue to be able to track multiple PR's for this project. I'm not sure whether this should be labeled a bug, improvement, request for feature, etc. 

Later I'll likely create a library for Zephyr specific API's.

**Comment by quantimnot** [comment]
@elcritch Are you able to build on a zephyr platform using `build_all.sh` and make use of your changes? I'm a bit confused, but it seems to me that may not work since it isn't in the csources. Do you only ever cross-compile for this platform?

**Comment by elcritch** [comment]
> @elcritch Are you able to build on a zephyr platform using `build_all.sh` and make use of your changes? 

It's not really feasible to run the Nim compiler on Zephyr. It wouldn't be strictly impossible on some hardware just way too much effort. Though I've thought it'd be cool to try and run NimVM on a Zephyr device. 

> I'm a bit confused, but it seems to me that may not work since it isn't in the csources. Do you only ever cross-compile for this platform?

Yes it's usually cross compiled, which Zephyr itself handles. The Nim code can be compiled to C sources which can be included in Zephyr's build system. I'm going to write some nimble tasks to help automate that step. 

You can see a demo here where I put the steps into a simple makefile: https://github.com/elcritch/zephyr_example-dumb_http_server_/blob/main/Makefile

**Comment by quantimnot** [comment]
Very cool. 
I was studying the flow of the host OS and CPU symbols and noticed your recently committed check in `compiler/options.isDefined`. I was thinking that wasn't needed if it was in the csources that are generated for bootstrapping. Makes sense that it's not needed in csources. I'm just trying to understand. Thank you for clarifying.
