### ISSUE TITLE
/tmp/nim/box2.nim(10, 18) Warning: implicit conversion to 'cstring'

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#18698]
Full message:

```
/tmp/nim/box2.nim(10, 18) Warning: implicit conversion to 'cstring' from a non-const location: el; this will become a compile time error in the future [CStringConv]
```

We get such messages since a few weeks now. I hoped they would disappear due to many user complains, but they are still there :-(

Well message may be OK, but compile time error later?

I assume that the message was introduced because some people did strange things with cstrings.

But for most people cstring use is fine when creating C lib bindings, as for C libs a NULL string pointer is very different from an empty string, the Null pointer may indicate the special void case. And for C lib bindings we may have to use trampoline functions, to which we really want to pass cstrings. Passing Nim strings to the trampoline function would not only be some overhead (passing Nim String object to trampoline function, which then passes ctring to C lib), but would make distinction between nil and empty string impossible, so we would have to use Option types maybe.

Here is one full examplem from the Nim GTK4 book:

```nim
cat box2.nim 
import gintro/[gtk4, gobject, gio]

proc activate(app: gtk4.Application) =
  let window = newApplicationWindow(app)
  let hbox1 = newBox(Orientation.horizontal, 25)
  let hbox2 = newBox(Orientation.horizontal, 25)
  let vbox = newBox(Orientation.vertical)
  var l: Label
  for el in ["A", "B", "C"]:
    l = newLabel(el)
    l.hexpand = true
    hbox1.append(l)
  for el in ["D", "E"]:
    l = newLabel(el)
    l.hexpand = true
    hbox2.append(l)
  vbox.append(hbox1)
  vbox.append(hbox2)
  window.setChild(vbox)
  window.show

proc main =
  let app = newApplication("org.gtk.example")
  app.connect("activate", activate)
  let status = app.run
  quit(status)

main()
```

```nim
$ grep -C16 -A4 "proc newLabel" ~/.nimble/pkgs/gintro-#v0.9.2/gintro/gtk4.nim
proc gtk_label_new(str: cstring): ptr Label00 {.
    importc, libprag.}

proc newLabel*(str: cstring = nil): Label =
  let gobj = gtk_label_new(str)
  let qdata = g_object_get_qdata(gobj, Quark)
  if qdata != nil:
    result = cast[type(result)](qdata)
    assert(result.impl == gobj)
  else:
    fnew(result, gtk4.finalizeGObject)
    result.impl = gobj
    GC_ref(result)
    discard g_object_ref_sink(result.impl)
    g_object_add_toggle_ref(result.impl, toggleNotify, addr(result[]))
    g_object_unref(result.impl)
    assert(g_object_get_qdata(result.impl, Quark) == nil)
    g_object_set_qdata(result.impl, Quark, addr(result[]))
```
It is obvious that passing a cstring to the trampoline function newLabel() is fine, as it passes that cstring directly to the C lib.

**Comment by Araq** [comment]
Why not make it:

```nim

proc newLabel*(str: string = ""): Label

```
? What's the benefit of keeping the `cstring` in the non-wrapping code?

**Comment by StefanSalewski** [comment]
I have really tried hard to explain it. Sometimes I have the feeling I am writing with invisible ink :-)

>as for C libs a NULL string pointer is very different from an empty string, the Null pointer may indicate the special void case.

**Comment by StefanSalewski** [comment]
Or to say it with different words: When we pass a Nim string to the trampoline function, then we would have to convert an empty Nim string "" to a NULL cstring passing it to the C lib, as the C lib only recognizes NULL as the special void case. We would need a converter function for that, and the user would not be able to pass a real empty "" string to the C lib, which may be intended in some cases. (Indeed we had that for early gintro versions, it was an oversight, a user told us that passing cstring is a better solution.)

**Comment by Araq** [comment]
Other solutions are thinkable:

- Use overloading:

```nim

proc newLabel*(str: string): Label
proc newLabel*(): Label

```

- Use ``Option[string]``:

```nim

proc newLabel*(str: Option[string]): Label

```

We can patch the logic for the warning too so that your example works without one. But the API doesn't feel idiomatic with `cstring` which is why I made these suggestions.

Fwiw: https://gtk-rs.org/gtk3-rs/stable/latest/docs/src/gtk/auto/label.rs.html#219-222 uses the Optional.

**Comment by StefanSalewski** [comment]
Yes you are right, overloading would work. Would increase the source code size and compile time a bit. I mentioned Option types myself in my initial post. Have always avoided option types myself, would have to see how well they work for users.

**Comment by Araq** [comment]
For `newLabel` in particular I would map "" to nil as I cannot see the benefits of otherwise empty labels. But I am probably missing something.

**Comment by StefanSalewski** [comment]
Indeed newLabel() may be not the best example, but the API docs

https://docs.gtk.org/gtk4/ctor.Label.new.html

tell us that NULL is a valid value: "The argument can be NULL"

In earlier gintro versions we passed a Nim string to the trampoline functions and use function safeStringToCString() to convert empty string to nil. That was OK in most cases, but looked like some unneeded overhead and restriction, so we changed it to use cstrings only. Note that Nim strings could be nil itself in early Nimrod days!

```nim
$ grep "safeStringToCString" ~/gintro/tests/gen.nim 
          # result.arglist.add("safeStringToCString" & '(' & name & ')')
    # output.writeLine("proc safeStringToCString*(s: cstring): cstring = (if s.len == 0: nil else: s)")
```

For gintro we have about 1k procs which accept NULL cstrings:

```
$ grep ": cstring = nil" ~/.nimble/pkgs/gintro-#v0.9.2/gintro/* | wc -l
1039
```

My feeling is still, as long as Nim supports cstrings at all, it is the best solution to pass cstrings to the trampoline function. It is like using uint, float32, cast or addr -- not really nice but it helps to get the work done. If that will generate a compiler error in the future, then I will revert to passing a Nim string and applying safeStringToCString() function again. Generating 1k overload functions seems to be a bit much, and I guess option types may be not that nice for users, I have seen Rust GTK code passing Some("ButtonName") which makes the code really ugly.

I will close this issue then, when people will complain I will point them to this issue.
