### ISSUE TITLE
[stdlib] Add full set of Hash function

### ISSUE THREAD

**Issue by evan0greenup** [nim-lang/Nim#18716]
### Summary

Add more hash function in stdlib, like sha256, sha384, sha512, shake256, blake256 ... and sha3 series, and whirlpool ...

It would be awesome.

### Description

currently, it only have md5, and I don't think it is good to just include md5 in an independent module. I suggest to concentrate all algorithm implementation together inside a single module as an API.

### Alternatives

Maybe python's hashlib can be a reference.

**Comment by ringabout** [comment]
> currently, it only have md5

Not just md5 => https://nim-lang.github.io/Nim/lib.html#pure-libraries-hashing

You can also checkout https://github.com/cheatfate/nimcrypto (which supports almost what you have mentioned: sha256, sha384, sha512, shake256, blake256 ... and sha3 series and is already used in production)

https://cheatfate.github.io/nimcrypto

**Comment by juancarlospaco** [comment]
I dont know if *all* of those, but having the classic and more standard ones would be nice.


[`sha3`, `shake_256`, `shake_128`, `sha512_224`, `mdc2`, `sha3_384`, `md4`, `sha3_256`,
`blake2b`, `sha512`, `sha224`, `blake2s`, `sha512_256`, `whirlpool`, `ripemd160`, 
`sha384`, `sha256`, `sm3`, `sha3_224`, `pbkdf2_hmac` and more for Nim.](https://juancarlospaco.github.io/cpython/hashlib.html)

**Comment by ghost** [comment]
@juancarlospaco I don't think using hash functions from CPython is a good idea for this issue...

**Comment by disruptek** [comment]
Please leave this out of the standard library so that implementations and support can evolve without your interference.

https://github.com/khchen/hashlib

**Comment by Araq** [comment]
Yeah, it's time to learn from past mistakes. Use one of our package managers.
