### ISSUE TITLE
[Feature request]: reverse() as a part of the built-in standard libary?

### ISSUE THREAD

**Issue by marek-lach** [nim-lang/Nim#18719]
The reasoning for why this basic functionality's needed bundled in, is already well laid out here: https://forum.nim-lang.org/t/5458.

**Comment by ghost** [comment]
I don't understand the feature request - we do have https://nim-lang.org/docs/algorithm.html#reverse%2CopenArray%5BT%5D and https://nim-lang.org/docs/algorithm.html#reversed%2CopenArray%5BT%5D and that was pointed out in the forum post. Is there anything I'm missing?
