### ISSUE TITLE
Expression-returning and discarding anonymous proc syntax-error

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#18714]
Using anonymous `func`s and `proc`s in certain syntactical contexts results in syntax errors.

### Example
This example compiles and shows some things one can do with anonymous `func`s or `proc`s. This example uses `func`, but so far `func` and `proc` behave the same way in what works and doesn't.
```nim
func c(_: auto) = discard

func r(): auto =
  # Compiles
  c(func(): int = 2)

  # Compiles
  let w = func(): int = 2

  # Doesn't compile
  # discard (func(): int = 2)

  # Compiles
  return func(): int = 2

  # Expression return fails
  # func(): int = 2

echo r()()
 ```

An example which doesn't build:
```nim
func r(): auto =
  func(): int = 2
echo r()()
```

### Current Output
The example which builds prints `2`, as expected.

On all of
```
$ ./env.sh nim --version
Nim Compiler Version 1.2.12 [Linux: amd64]
Compiled at 2021-08-19
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 121628357ec7fae91335bd392f03b0e6dd249319
active boot switches: -d:release
```
```
$ nim --version
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-08-18
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
and current git head:
```
$ Nim/bin/nim --version
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-08-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 7b58dc2de0f606b757a558dfdda9d930ae63f41a
active boot switches: -d:release
```

The not-building example shows:
```
anon_proc_expr_return.nim(2, 7) Error: identifier expected, but got '('
```

### Expected Output
```
2
```

**Comment by metagn** [comment]
There is a simpler workaround than the ones mentioned, being `(proc() = discard)`.

The [statement versions of routines](https://github.com/nim-lang/Nim/blob/2bd1aa186e09565b2103394bd281478fa1b10ef1/compiler/parser.nim#L1134) are only parsed inside [`complexOrSimpleStmt`](https://github.com/nim-lang/Nim/blob/2bd1aa186e09565b2103394bd281478fa1b10ef1/compiler/parser.nim#L2259-L2293), which is also supposed to accept lambda syntax. Routine expression syntax is just routine statement syntax without names and generics, So the proc that parses routine statements can be unified with [the proc that parses routine expressions](https://github.com/nim-lang/Nim/blob/2bd1aa186e09565b2103394bd281478fa1b10ef1/compiler/parser.nim#L1134) with an enum argument of 3 values, each of which mean only proc types; only proc types or expressions; or any of proc types, expressions or statements are allowed.

**Comment by Araq** [comment]
Nim has a formal grammar and the implementation tries to follow it. There is no bug here.

**Comment by arnetheduck** [comment]
> Nim has a formal grammar and the implementation tries to follow it. There is no bug here.

the formal grammar is surprising and inconsistent in this case - it makes nim less of a pleasure to use when you run into paper cuts like this - now, since `proc` is a keyword, I imagine it's fixable at the grammar level without breaking any existing code?

The other option would be a better error message that says that you have to add a work-around to make the code work - more formally, what's going on is that returning `proc`:s become less of a first-class construct, meaning that writing higher-functions in general become second-class constructs in one more way, which is sad.

**Comment by Araq** [comment]
Improvements and changes to the grammar should go though the RFC process. "I think this should work" is how we developed the language for far too long.

Developing against a spec is already hard enough, "the spec is wrong anyway and you should always trust our instincts instead" is impossible to develop against. Been there, done that.

**Comment by metagn** [comment]
The grammar allows this though. `complexOrSimpleStmt` checks for `'proc' routine` first, and this fails, but it is also supposed to allow `routineExpr` after via `simpleStmt -> exprStmt -> simpleExpr -> ... -> primary`. The parser doesn't implement this. There is no conflict between routine declaration and routine expression, one needs a name first, the other needs `(` first.
