### ISSUE TITLE
[Feature request]: Syntax - define to act as a keyword for variables, intuitive for newcomers

### ISSUE THREAD

**Issue by marek-lach** [nim-lang/Nim#18723]
For implementing such a functionality, where define becomes a reserved keyword in Nim, to also act as another possible way of defining variables, in addition to var, but similar to how it acts in Scheme/Racket: see https://docs.racket-lang.org/guide/define.html, and https://docs.racket-lang.org/guide/syntax-overview.html, if you're searching for some more context...

A basic definition where it would act as simply just another way of defining variables, has the form of e.g.:

_define_ age 37 , while for strings this could also be as: _define_ age "37" .

In Nim, this is also served through e.g. `var age = 37`, which is also good, and using define could simply be just a mere another possible way of defining variables for beginning programmers comming from other languages, such as Scheme and still adjusting to the ways of Nim itself.

Reasoning for this addition:

The basic reasoning for doing this in some future (if perhaps distant?) release, is the basic philosophy behind Nim, that it aims to be as expressive, and easy to understand with its written code as possible, while borrowing good ideas from other languages to achieve that goal. Including Lisp.
For some, `define` variable value may seem more natural/intuitive then using `var` variable = value ,when they're still learning _Nim_.

**Comment by StefanSalewski** [comment]
Variable definitions with the var keyword are well known from Pascal, Modula, Oberon and maybe some more languages. So that notation is really not strange, and it is maybe the most simple construct that Nim has. So there is really no need for another keyword. And it would not help the people who refuse to read at least one tutorial.

**Comment by Araq** [comment]
>  is the basic philosophy behind Nim, that it aims to be as expressive, and easy to understand with its written code as possible, while borrowing good ideas from other languages to achieve that goal. Including Lisp.

Correct, but we don't copy syntax from other languages anymore, only the good ideas.
