### ISSUE TITLE
`genDepend` broken for duplicate module names in separate folders

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#18735]
Consider a project with modules `folder0/mod.nim` and `folder1/mod.nim` - genDepend will create a dependency file that doesn't disambiguate the two modules and thus creates false dependencies in the graph.

nim 1.2.12

**Comment by arnetheduck** [comment]
How did you construct the "full path" in the example? it looks like a "semi-full" path which .. I think mostly should work but still possibly can be broken, but maybe not - one option I can imagine work would be to have a "shortest-unique-path" where you keep adding things with the shortest name possible and when there's a conflict, add parent folders to each entry until they're unique, so `a/b/c` and `b/b/c` start off as `c`, then `b/c` and finally the disambiguator is added - this would require a multi-pass approach of course.

the other thing to consider would be "stability" - it might be a good idea that as much as possible of the module name is stable so it might make sense to always start with project-rooted paths - ie everything from std lib starts with `std/`, nimble packages start with their nimble package name etc, then the "shortest-unique-path" done afterwards as a final disambiguator - this would also help identify where modules come from in general, which in a larger project might be .. tricky .. specially if you're using 3rd-party libraries in your code.

**Comment by arnetheduck** [comment]
> For larger project, no matter which means looks terrible.

So I think the priority is correctness - what we want to use gendepend for is simplify the import graph and detect cycles - there are tools that analyze dot files for such opportunities, so the "looks" are secondary.

> For larger project, no matter which means looks terrible.

The graph looks messy perhaps because it's big, but I think it's an improvement already to see where modules are coming from - this way it's easier to track down suspicious dependencies.

> regex

I still see a "plain" regex module in `test8.svg` - this is the kind of name I'd suspect can collide easily - with `toProjPath`, what would typically break it?

**Comment by Araq** [comment]
Why not simply use absolute paths everywhere? The DOT output is not that important, the same information in a text file is usually much better because you can search for things. The DOT graphs quickly become unmanagable anyway.

**Comment by arnetheduck** [comment]
while we're here: `dot` keywords are not escaped, so a module named `node` will cause an invalid `dot` file to be generated.

> Why not simply use absolute paths everywhere

that's an extreme in the other direction - `toProjPath` + add a minimum parents on conflict seems like a reasonable middle ground perhaps?

**Comment by arnetheduck** [comment]
notably, this same problem exists when nim prints the module name while compiling the module - full path would be messy, no path means "hard-to-find-and-maybe-conflict".

**Comment by arnetheduck** [comment]
for reference, here's where we are today: https://gist.githubusercontent.com/arnetheduck/9cfde349c31747e96fb3c1b8a9974afa/raw/506057822306751d555376b6d011b56ccab585ea/nbc.svg

**Comment by arnetheduck** [comment]
>  use pkg/ prefix for nimble packages. (or packages: )

what if this was the long-nimble-name, like `regex-0.17.0`?

**Comment by arnetheduck** [comment]
>  no special prefix for current project modules.

what happens to `foldera/mod` and `folderb/mod` within the project?

**Comment by arnetheduck** [comment]
cc @xflywind what was the latest state of this?

**Comment by ringabout** [comment]
I will revisit it on weekends since it seems easier.

**Comment by ringabout** [comment]
@arnetheduck update => https://github.com/nim-lang/Nim/pull/19988
