### ISSUE TITLE
atlas overwrites user files

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18750]
### Example
```
cd $dir
git clone https://github.com/nim-lang/Nim
cd Nim
sh build_all.sh
ls ..
Nim
bin/nim c -r tools/atlas/atlas.nim clone https://github.com/disruptek/balls
ls ..
```

### Current Output
it generates directories outside of source tree
```
Nim             balls           grok            nim-bytes2human npeg            packages        sync            testes          ups
```
and in fact in my use case that prompted this issue, it affected and modified existing files I had in Nim/.. as that directory already contained some cloned packages.

### Expected Output
it should generate directories self-contained within source tree:
```
Nim
```
possibly under: Nim/.atlas, similar to `node_modules/`

rationale: things should be kept self contained, so you won't interfere with other local installations of nim (i have more than 1 nim folder for development purposes, branches don't solve everything).

### Additional Information
1.5.1 98f7254fb25d402a3cad8e7de81207448fc7b322

see also https://github.com/nim-lang/Nim/issues/18751

**Comment by Araq** [comment]
Works as documented.
