### ISSUE TITLE
atlas installs a different version of packages (and even different packages) than nimble

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18754]
while attempting to fix the other atlas issues I've reported, I encountered the following problem: atlas installs a different version than nimble; this obviously poses problems as packages are designed to work with certain assumptions and typically tested using nimble, but if atlas installs different versions than nimble, those assumptions break down.

### Example
starting from scratch:
```
NIMBLE_DIR=$HOME/.nimble_fake78 XDG_CONFIG_HOME= nimble install https://github.com/disruptek/balls
bin/nim c -r tools/atlas/atlas.nim clone https://github.com/disruptek/balls
```

### Current Output
* for nimble:

ls -1 $HOME/.nimble_fake78/pkgs
balls-3.4.2
grok-0.5.3
npeg-0.24.1
sync-1.4.0
ups-0.0.7

* for atlas:
grok is at 349c15fd1e03f1fcdd81a1edefba3fa6116ab911, with tag 0.0.4, instead of 0.5.3
npeg is at 5d80f93aa720898936668b3bc47d0fff101ec414, with no tag (most recent is 0.24.1 which is same tag but different commit)
sync is at 4036beb8c83acfa59ffdcbadcb3926bd953cfb39, with no tag (most recent is v1.4.0, which is same tag but different commit)
ups is at 74c31af8030112dac758440aa51ef175992f71f3, with tag 0.0.2 instead of 0.0.7

and it installs more packages than nimble:
```
balls
grok
nim-bytes2human
npeg
packages (not an actual package)
sync
testes
ups
```

### Expected Output
versions match

### Additional Information
1.5.1 98f7254fb25d402a3cad8e7de81207448fc7b322
this is related to https://github.com/nim-lang/Nim/issues/18753 but different

**Comment by Araq** [comment]
That's by design...

**Comment by timotheecour** [comment]
> That's by design...

where is that design documented / explained?
The problem here is nimble packages are developed and tested via nimble install+friends, not via atlas, so if these resolve to different hashes, it's a recepie for broken packages.
