### ISSUE TITLE
Module strscans -- typos and suggested Option[int] return type for parsing optional arguments.

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#18757]
First it may be time to fix two old typos:

```
It also possible to pass arguments to a user definable matcher: # It IS

Matches a floating pointer number. Uses parseFloat. # floating POINT number.
```

And finally it may be useful to allow optional arguments for the user defined matchers.

Mr. Rumpf suggested to use Option[int] as return type, see

https://forum.nim-lang.org/t/8368#53963

**Comment by StefanSalewski** [comment]
And finally even after reading the API docs for the second time I can not understand why in the user defined skip matcher the last parameter is a seq[char] with default value:

```nim
proc someSep(input: string; start: int; seps: set[char] = {':','-','.'}): int =
```

My feeling is, that this seq[char] parameter is necessary, it has to have a default, but the default value does not really matter. (First guess was that the proc is only called when the current char in input string matches one of the default values, but I was not able to confirm that guess.)

So why do we have that parameter at all -- the proc could just use a local const to investigate characters to ignore?

**Comment by kaushalmodi** [comment]
@StefanSalewski 

> it has to have a default, but the default value does not really matter. 

The default values matter if the user defined proc is actually using the `seps` parameter.

Here's an example extracted from tstrscans.nim:

```nim
import std/[strscans]

var
  key: string
  intVal: int

proc someSep(input: string; start: int; seps: set[char] = {';', ',', '-', '.'}): int =
  result = 0
  while start+result < input.len and input[start+result] in seps: inc result

proc twoDigits(input: string; x: var int; start: int): int =
  if start+1 < input.len and input[start] == '0' and input[start+1] == '0':
    result = 2
    x = 13
  else:
    result = 0

let yy = scanf(";.--Breakpoint00 [output]",
    "$[someSep]Breakpoint${twoDigits}$[someSep({';','.','-'})] [$+]$.",
    intVal, key)
doAssert yy
doAssert key == "output"
doAssert intVal == 13
```

Running this passes.

But if you change the default values of `seps` to `{'-'}`, it will fail.
