### ISSUE TITLE
atlas treats `requires: <=` as `requires: >=`, etc

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18755]
### Example
atlas uses:
```nim
proc toDepRelation(s: string): DepRelation =
  case s
  of "<": strictlyLess
  of ">": strictlyGreater
  else: normal
```

this is incorrect for operators other than > and <, see https://github.com/nim-lang/nimble
```
There are also following version selector operators available for "requires": <,>, >=, <=, ==, ^= and ~=.
```
* furthermore, what about exact hashes, eg: "https://github.com/user/pkg#5a54b5e" ? or other forms (eg branch/tag)
* ditto with multi-constraints, eg `"https://github.com/disruptek/grok >= 0.0.4 & < 1.0.0"`

### Additional Information
1.5.1 98f7254fb25d402a3cad8e7de81207448fc7b322

why not reuse / port the code from nimble?

**Comment by Araq** [comment]
Because Atlas is not Nimble, Atlas uses the minimum version (or more precisely: the maximum of the minimum versions) for reproducible builds.
