### ISSUE TITLE
atlas cmd writes nim.cfg to wrong destination: cannot open: balls/nim.cfg [IOError]

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18751]
### Example
```
cd $dir
git clone https://github.com/nim-lang/Nim
cd Nim
sh build_all.sh
bin/nim c -r tools/atlas/atlas.nim clone https://github.com/disruptek/balls
```

### Current Output
[Warning] (nim-bytes2human) package has no tagged releases

/private/tmp/d04/foo2/Nim/tools/atlas/atlas.nim(473) atlas
/private/tmp/d04/foo2/Nim/tools/atlas/atlas.nim(456) main
/private/tmp/d04/foo2/Nim/tools/atlas/atlas.nim(396) patchNimCfg
/private/tmp/d04/foo2/Nim/lib/system/io.nim(866) writeFile
Error: unhandled exception: cannot open: balls/nim.cfg [IOError]
Error: execution of an external program failed: '/private/tmp/d04/foo2/Nim/tools/atlas/atlas clone https://github.com/disruptek/balls'

### Expected Output
should write to $nim/config/nim.cfg, not $nim/balls/nim.cfg,

### Example 2
bin/nim c -r tools/atlas/atlas.nim clone cligen
Error: unhandled exception: cannot open: cligen/nim.cfg [IOError]

### Additional Information
1.5.1 98f7254fb25d402a3cad8e7de81207448fc7b322

**Comment by Araq** [comment]
It should really write to `$nim/balls/nim.cfg`, as documented.

**Comment by timotheecour** [comment]
since you've closed this issue, I have to assume that crashing with `cannot open: balls/nim.cfg` is the expected behavior

(that command came from `koch.nim:602:19:    execFold("Run atlas tests", "nim c -r -d:atlasTests tools/atlas/atlas.nim clone https://github.com/disruptek/balls")` adapted by removing `-d:atlasTests` which is test-only)

**Comment by Araq** [comment]
I don't know why it could not write into this directory, but it should write into $nim/balls/nim.cfg, as documented.

**Comment by timotheecour** [comment]
> I don't know why it could not write into this directory

because it creates $nim/../balls ...
