### ISSUE TITLE
Probable bug with identifiers

### ISSUE THREAD

**Issue by samsamros** [nim-lang/Nim#18763]
I was building a basic object in nim to later feed into a mongo database. According to the documentation, identifiers can't have double underscores. However, I ran into the following issue for several variable names. I list one example that gave me the following error: 
"only single underscores may occur in a token and token may not end with an underscore: e.g. '1__1' and '1_' are invalid"
 
type Transact* = object
  outlayed_amount_funded_by_COVID-19_supplementals_for_overall_aw*: float

Also tried stropping and this didn't work either:
type Transact* = object
  \`outlayed_amount_funded_by_COVID-19_supplementals_for_overall_aw\`*: float

When I change the variable's name like this: 

"outlayed_amount_funded_by_COVID_19_supplementals_for_overall_aw" 
used **COVID_19_ instead of COVID-19_**
I no longer get the error. 

However, there is no double underscore as the main error says; and the identifier does not start with a number. 
I had to create a nim object and later rename the variables on the fly (using another function, see: https://github.com/nim-lang/Nim/issues/18763#issuecomment-907644919) to insert them in my database. But this seems to be a bug, as it did not work even when I used stropping for the identifier. 

Edit August 30th:

as @haxscramper pointed out: https://github.com/nim-lang/Nim/issues/18763#issuecomment-907790108

the error is reproducible:
\# Error: only single underscores may occur in a token and token may not end with an underscore: e.g. '1__1' and '1_' are invalid
                    \# compiler/lexer.nim(221, 17) compiler msg initiated here [MsgOrigin]

**Comment by juancarlospaco** [comment]
The `-` in the name.

**Comment by samsamros** [comment]
@juancarlospaco Thank you for your response. I did not see that in the documentation. In deed, when I removed the `-` the problem was gone, but I don't understand why. 
https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords
Any idea as to why this is happening?

**Comment by hasanyasin** [comment]
If you checked the manual, identifiers are defined like this:

```
IDENTIFIER ::= letter ( ['_'] (letter | digit) )*

letter ::= 'A'..'Z' | 'a'..'z' | 'x80'..'xff' digit ::= '0'..'9' 
```

The error message probably could be better, but this probably broke the parser in a weird way. As a general principle, such identifiers (extremely long and with underscores) are not really conventional nor good. I use Nim daily and have many thousands of lines of code in the last ~2 years and have never had such an issue. The right place to discuss these would be Nim forums, probably. The final two paragraphs in the original message confused me completely.

**Comment by samsamros** [comment]
@hasanyasin  thank you for your response. I did not choose to use those identifiers, those are the variable names in a database. 

As for the two paragraphs. I just renamed the identifiers and later reparsed them when converting to bson.

```
proc toBson1*(obj: Transactions_bson): BsonDocument =
  #[
    Convert to bson
  ]#
  result = bson()
  var l: string
  for k, v in obj.fieldPairs:
    if k == "outlayed_amount_funded_by_COVID_19_supplementals_for_overall_aw":
      l = "outlayed_amount_funded_by_COVID-19_supplementals_for_overall_aw"
....
    else: 
      l = k

    result[l] = v
```
I've never had that issue before, and seldom use such long identifiers. I much rather use data dictionaries to decode variable names. So, from what I understand, `-` should not be used in identifiers?
I did go to the Telegram group and asked it there, and a kind fellow said it might be a bug and better to report it to be sure. I'm sorry for the confusion.

**Comment by juancarlospaco** [comment]
Use Stropping to use `-` and Kebab-case
https://nim-lang.github.io/Nim/manual.html#lexical-analysis-keywords-as-identifiers

**Comment by Araq** [comment]
Your DB layer should support something like  `reasonableName {.importMongo: "outlayed_amount_funded_by_COVID-19_supplementals_for_overall_aw".}`

**Comment by haxscramper** [comment]
The main issue that was not mentioned is that stropping also breaks. @samsamros 's example does not have properly formatted code, it only has backticks around db field name. So in this case it is a bug in stropping - 

```nim
var `a_a_12_f`: int # Ok
var `a-a-12-f`: int # Ok
var `a_a_12-f`: int # Ok
var `a_a-12_f`: int # Error: only single underscores may occur in a token and token may not end with an underscore: e.g. '1__1' and '1_' are invalid
                    # compiler/lexer.nim(221, 17) compiler msg initiated here [MsgOrigin]
```

**Comment by samsamros** [comment]
@haxscramper thank you for jumping in. I'm sorry my formatting didn't ilustrate the problem. In fact, as you point out I did use stropping, but didn't know how to format it properly on github. I will correct my main post to point out the issue and avoid further confusion. 

> Also tried:
> type Transact* = object
>   \`outlayed_amount_funded_by_COVID-19_supplementals_for_overall_aw\`*: float

**Comment by haxscramper** [comment]
@samsamros https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by Araq** [comment]
The compiler's error message could be better but there is no bug here.
