### ISSUE TITLE
Unexpected result of `getCurrentException()` in `finally` clause for a more complex situation

### ISSUE THREAD

**Issue by ChengCat** [nim-lang/Nim#18779]
### Example
```nim
proc fn() =
   try:
      try:
         assert false
      except:
         return
   finally:
      echo getCurrentException() != nil

fn()
```

### Current Output
Both `--exceptions:goto` and `--exceptions:setjmp` result in the same output:

```
true
```

### Expected Output
The exception should be already handled and consumed in the `except:` clause.

```
false
```

### Additional Information

The equivalent Python program works as expected:

```python
import sys

def fn():
    try:
       try:
           assert False
       except:
           return
    finally:
        print(sys.exc_info()[1] != None)

fn()
```

```
git hash: 3469f3a39320cf35d02d11b78c7db0be79e992f8
active boot switches: -d:release
```

**Comment by Araq** [comment]
We don't follow Python's spec as it has none. Wether the exception is already completely handled or not in the `finally` is up to the implementation.

**Comment by ChengCat** [comment]
Let me clarify that I am not asking you to blindly follow any other language's behavior. This is clearly wrong semantics to my eyes, and I only referred to Python to back up my claim.

To further convince you, the following equivalent Ruby program also works as expected:

```
def fn
   begin
      begin
         assert false
      rescue
         return
      end
   ensure
      puts $! != nil
   end
end

fn()
```

**Comment by Araq** [comment]
Just use 

```nim

proc fn() =
   try:
      try:
         assert false
      except Exception as e:
         echo e
         return
   finally:
      discard

fn()
```

and stop messing with `getCurrentException` if you don't like it. The behavior is sane, before the `return` all `finally` handlers have to be run and while that happens there still is a current exception.

**Comment by ChengCat** [comment]
My use case in context is a macro to wrap LMDB transactions:

```nim
template with_txn*(env: ptr MDB_env, write: bool, tx, actions: untyped) =
   block:
      let tx = dbret mdb_txn_begin(env, nil, (if write: 0.cuint else: MDB_RDONLY))
      try:
         try:
            actions
         finally:
            if getCurrentException() == nil:
               dbcheck mdb_txn_commit(tx)
      except:
         mdb_txn_abort(tx)
         raise
```

This was the cleanest way I thought of. Ideally there is a `else` branch of `try` to run if no exception is raised, but I've checked Python, unfortunately Python's `else` branch doesn't do what I expect. I'm not sure what's the reasoning behind that design.

With the current behavior of `getCurrentException()`, the macro has to be written in an awkward way:

```nim
template with_txn*(env: ptr MDB_env, write: bool, tx, actions: untyped) =
   block:
      let tx = dbret mdb_txn_begin(env, nil, (if write: 0.cuint else: MDB_RDONLY))
      var aborted = false
      try:
         actions
      except:
         mdb_txn_abort(tx)
         aborted = true
         raise
      finally:
         if not aborted:
            try:
               dbcheck mdb_txn_commit(tx)
            except:
               mdb_txn_abort(tx)
               raise
```

> before the return all finally handlers have to be run

This is more from a perspective of compiler implementation than what is conceptually to the programmer. Conceptually, upon `return` the control flow should exit lexical scopes one by one, and the outer `finally` clause should not see an exception already handled in a inner lexical scope.

To be fair, behavior of `getCurrentException` in `finally` is indeed undefined in the documentation. But we all dislike undefined behaviors. Either define the behavior to be similar to Python/Ruby, or make `getCurrentException` return `nil` in `finally` (like C++'s `std::current_exception()` in destructors) would be good. Given my use case above, the former choice seems better.

**Comment by ChengCat** [comment]
I've just re-checked LMDB, it turns out I shouldn't do `mdb_txn_abort` if `mdb_txn_commit` failed. So my use case don't actually need this `getCurrentException()`.

But this issue still stands, one can easily imagine other situations in which checking `getCurrentException() == nil` in `finally` would be useful.
