### ISSUE TITLE
gcsafe ignored with --experimental:strictEffects; noSideEffects still gives error instead of warning

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18786]
### Example 1
```nim
when true:
  var a2 = ""
  proc fn(b: int) {.gcsafe.} =
    a2.add $b
  fn(1)
  echo (a2,)
```
before https://github.com/nim-lang/Nim/pull/18777:
gives GcUnsafe2

after PR, and with `--experimental:strictEffects`:
no warning (but it should give one)

### Example 2
```nim
when true:
  func fn(b: int) =
    echo b
  fn(1)
```
after PR, still gives error instead of warning despite this comment:
https://github.com/nim-lang/Nim/pull/18777#discussion_r700520014
(refs https://github.com/nim-lang/RFCs/issues/419; maybe that's why the RFC wasn't closed :) )

this is odd because all other effects besides `sideEffect` give warnings instead of error by default after https://github.com/nim-lang/Nim/pull/18777

### Example 3
this works as designed (gives warnings, no errors; refs https://github.com/nim-lang/RFCs/issues/419)
```nim
when defined case2:
  block:
    type A = object
    proc fn1() {.tags: [A].} = discard
    proc fn2() {.tags: [].} = fn1()
  block:
    proc fn1() {.raises: [ValueError].} = discard
    proc fn2() {.raises: [].} = fn1()
  block:
    var a2 = ""
    proc fn(b: int) {.gcsafe.} = a2.add $b
    fn(1)
```

### Additional Information
1.5.1 f46569bafdfdd3290baf132f025d61a0e550dd58
EDIT: ditto with `strictFuncs`, should give warning instead of error

**Comment by Araq** [comment]
I don't understand your "example 2", I think there is a typo somewhere. The warning feature is not completely implemented, a sigmatch.nim patch would be required for that but it's risky.

**Comment by timotheecour** [comment]
> I don't understand your "example 2", I think there is a typo somewhere.

i verified, there is not typo; 
`nim r main` for example 2 gives:

Error: 'fn' can have side effects

but instead should give a warning

**Comment by Araq** [comment]
Ah well, as I said warnings vs errors has not completely been resolved and warnings are so easy to miss. Maybe we need --warnOnEffectViolations instead.

**Comment by timotheecour** [comment]
=> followup https://github.com/nim-lang/Nim/pull/18795
