### ISSUE TITLE
Calling an {.exportc.} Nim proc from C issue: big object unexpectedly passed by pointer.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#18807]
Nim internally optimizes passing 25+ byte objects into pointers. This makes interfacing with C difficult when using {.exportc.}. How do I prevent this?

---

I have a small and big object and I expect C to give them to me.

```nim

type Small = object
  a: int
  b: int
  c: int

type Bigger = object
  a: int
  b: int
  c: int
  d: int

proc giveMeSmall(s: Small) {.exportc.} =
  echo s

proc giveMeBigger(b: Bigger) {.exportc.} =
  echo b

```

If we look at generated C code, small object works like we expect:

```c
N_LIB_PRIVATE N_NIMCALL(void, giveMeSmall)(tyObject_Small__40L5YgI9asGpFvyWZE8E7lA s) {
	tyArray__nHXaesL0DJZHyVS07ARPRA T1_;
	nimZeroMem((void*)T1_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T1_[0] = dollar___t4FwCKiitWRfhaPRP9cyy8A(s);
	echoBinSafe(T1_, 1);
}
```

But the big object gets passed by pointer `*b` (which breaks the C call):

```c
N_LIB_PRIVATE N_NIMCALL(void, giveMeBigger)(tyObject_Bigger__p06m63fDYP1piQG0nkxO0w* b) {
	tyArray__nHXaesL0DJZHyVS07ARPRA T1_;
	nimZeroMem((void*)T1_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T1_[0] = dollar___mwz3i3bvZqp3BpPteIoS9ag(b);
	echoBinSafe(T1_, 1);
}
```

According to @PMunch here ( https://www.reddit.com/r/nim/comments/ktqj22/a_few_questions_about_ptr_ref_and_function/ ):

> When passing something to a procedure in Nim the object won't be copied if it is larger than four ints. Since the compiler makes sure you don't actually write to an object it passes a pointer under the hood so that you can read from the object without having to copy it.

I think the check happens here? `ccgIntroducedPtr`: https://github.com/nim-lang/Nim/blob/ed126794b6af8b39960a7acc603cee1abc73da4a/compiler/ccgutils.nim#L129

Called from the here? `genArg`: https://github.com/nim-lang/Nim/blob/e0ef859130f429df1891e31a85955daa753346b4/compiler/ccgcalls.nim#L278

I like the pointer optimization if it speeds up Nim code, but how can I prevent it from happening when I need to `{.exportc.}` exactly how some one else wants? I feel like `{.exportc.}` should be special and generate the most pain C API. How can I prevent this behavior in my case?

---

```
nim -v
Nim Compiler Version 1.4.8 [Windows: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by guzba** [comment]
This happens for {.cdecl, exportc, dynlib.} too, not just for a solo {.exportc.} pragma.

**Comment by ghost** [comment]
You use `{.byref.}` to always pass by reference, or `{.bycopy.}` to always pass objects by copy.

https://nim-lang.org/docs/manual.html#foreign-function-interface-byref-pragma
https://nim-lang.org/docs/manual.html#foreign-function-interface-bycopy-pragma

**Comment by treeform** [comment]
Thank you. The {.bycopy.} did work for us. It seems to cause no perf issues. 

I timed some stuff its not clear that passing byref wins out, not sure why nim does it, but its good I can disable it.

**Comment by PMunch** [comment]
I'm not sure this should be closed. The point of exportc is to have C interop and this makes it less obvious which C code is generated. I'd say `exportc` should mean to keep the signature as exact as possible.

The optimisation of rewriting large objects being passed on the stack to be a pointer is a nice one, but I don't think you'll see much of a benefit if you don't have objects of a certain kind and usage patterns of a certain type.

**Comment by Araq** [comment]
>  The point of exportc is to have C interop and this makes it less obvious which C code is generated. I'd say exportc should mean to keep the signature as exact as possible.

No, features should do one thing and not try to outsmart or outguess the programmer. `exportc` is for name mangling, not for changing how data is passed around. Usually large structs really are passed by pointer in C anyway.

**Comment by PMunch** [comment]
I agree that features shouldn't try to outsmart or outguess the programmer. That's exactly _why_ I'd like `exportc` to disable the Nim feature that does exactly that. It guesses that I want to not pass data as large objects on the stack but rather as a pointer, but when interfacing with C code (which is what you're doing with `exportc`) then this guess is probably wrong because I'm trying to match some signature.

**Comment by Araq** [comment]
Er, but being able to write `proc p(x: Foo) {.exportc.}` and knowing that it produces `Foo*` in C-land is a feature.

**Comment by PMunch** [comment]
If `Foo` was an object I'd honestly expect to write `ptr Foo` to get that in C. Most people don't really think about these optimisations that Nim does under the hood, even knowing about them this issue surprised me.

**Comment by Araq** [comment]
But then you couldn't use the proc without `addr` shenanigans from Nim itself. Sure, you could add an overload but still. But as I said, `exportc` is about name mangling, it also doesn't change the calling convention to `cdecl` either, for example.

**Comment by PMunch** [comment]
True, but I don't think I've ever really seen an `{.exportc.}` proc that was used internally. Maybe with the exception on some experimental dynamic library code I once wrote. Maybe we should have another pragma that does a combination of `cdecl`, `exportc`, and `byCopy` (as long as that doesn't deep copy pointers). Basically a way to actually export a function to C in a way that is as compatible with C as possible.

**Comment by Araq** [comment]
Actually, Nim's DLL support and the full stdlib does use `exportc` and relies on the feature as it is.

**Comment by treeform** [comment]
Is there a way to do `proc p(x: Foo {.bycopy.} ) {.exportc.}` so that its only required to be the stack in that one call instance?
