### ISSUE TITLE
Type mismatch with SomeNumber

### ISSUE THREAD

**Issue by GabrielLasso** [nim-lang/Nim#18819]
### Example
```nim
proc a(a, b: SomeNumber): float =
  float(a) + float(b)

echo a(1, 2.5)
```

### Current Output
```
Error: type mismatch: got <int literal(1), float64>
but expected one of: 
proc a(a, b: SomeNumber): float
  first type mismatch at position: 2
  required type for b: SomeNumber
  but expression '2.5' is of type: float64

expression: a(1, 2.5)
```

### Expected Output
```
3.5
```

### Additional Information
If I change `SomeNumber` to `int | float` it works as expected...
```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 44e653a9314e1b8503f0fa4a8a34c3380b26fff3
active boot switches: -d:release
```

**Comment by beef331** [comment]
Not a bug, named typeclasses bind to the same type https://nim-lang.org/docs/manual.html#generics-implicit-generics. Solved by `proc a(a: SomeNumber, b: distinct SomeNumber): float`

**Comment by GabrielLasso** [comment]
> Not a bug, named typeclasses bind to the same type https://nim-lang.org/docs/manual.html#generics-implicit-generics. Solved by `proc a(a: SomeNumber, b: distinct SomeNumber): float`

Oh, I didn't now that

Given that SomeNumber is defined as `SomeInteger | SomeFloat`, I thought I could just substitute it there.

I'm closing here, thanks for the reply
