### ISSUE TITLE
#18784 broke arraymancer autograd code

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#18828]
The backported PR #18784 broke the autograd logic in arraymancer, as I noticed here https://github.com/mratsim/Arraymancer/pull/525. Arraymancer's Nim 1.4 CI still passed ~1 month ago, but fails now.

### Description

In arraymancer we have the following structure. A general `Gate` object from which we inherit for the specific gates, e.g. a `LinearGate`. In addition we need to define the backward propagating type, which is defined as taking this base `Gate` argument:

```nim
  Gate*[TT] = ref object of RootObj 
    ## Base operator or layer. You can describe your custom operations or layers
    ## by inheriting from Gate and add a forward and optionally a backward method.
    ## Each operations should set the number of gradients produced during backpropagation.
    ## Additional fields specific to the operations like weights or inputs cache should be added too.

  Backward*[TT] = proc(self: Gate[TT], payload: Payload[TT]): SmallDiffs[TT] {.nimcall.}
    ## ⚠️ Warning: make sure the identifier is not overloaded
    ## https://github.com/nim-lang/Nim/issues/9997
```

A specific gate now looks like:

```nim
type LinearGate*[TT] {.final.} = ref object of Gate[TT]
  input, weight, bias: Variable[TT]

proc linear_backward_ag[TT](self: LinearGate[TT], payload: Payload[TT]): SmallDiffs[TT] =
```

So `linear_backward_ag` conforms to the `Backward` type, given that `LinearGate` inherits from `Gate`.

We have a `register_node` procedure that takes a `Backward` as an argument:

```nim
func register_node*[TT](
        name: static string,
        gate: Gate[TT],
        backward: Backward[TT],
        result: Variable[TT] or seq[Variable[TT]],
        parents: varargs[Variable[TT]]) 
```

### Current output

Since the aforementioned PR compiling code using the arraymancer NNs, yields the following error:

```
arraymancer/nn/layers/linear.nim(57, 18) Error: type mismatch: got <string, LinearGate[Tensor[system.float32]], proc (sel
f: LinearGate[Tensor[system.float32]], payload: Payload[Tensor[system.float32]]): SmallDiffs[Tensor[system.float32]]{.gcsafe, locks: 0.}, Variable[Tensor[sys
tem.float32]], Variable[Tensor[system.float32]], Variable[Tensor[system.float32]], Variable[Tensor[system.float32]]>
but expected one of:
func register_node[TT](name: static string; gate: Gate[TT];
                       backward: Backward[TT];
                       result: Variable[TT] or seq[Variable[TT]];
                       parents: varargs[Variable[TT]])
  first type mismatch at position: 3
  required type for backward: Backward[register_node.TT]
  but expression 'linear_backward_ag' is of type: proc (self: LinearGate[Tensor[system.float32]], payload: Payload[Tensor[system.float32]]): SmallDiffs[Tenso
r[system.float32]]{.gcsafe, locks: 0.}
```

when it should match the procedure to the `Backward` type.

### Possible Solution

The PR #18784 changed the semantics for matching precisely such procedures:
https://github.com/nim-lang/Nim/blob/devel/compiler/sigmatch.nim#L598
by restricting the comparison from `isIntConv` to `isSubrange`.  

When compiling the arraymancer example, the argument is `isSubtype` and thus the comparison is true, meaning the type relation is set to `isNone`.

Any advice on how to keep allowing such conversions, but still failing for the example given in issue #16325? I suppose we need to compare the pragmas to see if the calling convention matches.

### Additional Information

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-09-04
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 5c85e480a6a13ac12c69f7e5500322eb5474be11
active boot switches: -d:release -d:danger
```

**Comment by Araq** [comment]
Please give me a single, complete, reduced program that you think should compile.

**Comment by Vindaar** [comment]
> Please give me a single, complete, reduced program that you think should compile.

Yup, will try to extract something. I had the secret hope that just by showing the existing type logic here it would be an obvious oversight in the PR that caused the regression.

**Comment by Araq** [comment]
As far as I can tell the compiler should always have rejected arraymancer's code. If you have:

```nim

type
  T = proc (x: Base)

proc foo(x: InheritedFromBase) = ...
```

then `foo` is not compatible with `T`. You need to use this workaround:

```nim
type
  T = proc (x: Base)

proc foo(x: Base) = 
  let x = InheritedFromBase(x)
  ...

```

**Comment by Vindaar** [comment]
Thanks @Araq, totally forgot about this issue. Your proposed solution works fine!

Should this be closed then?

**Comment by Araq** [comment]
Ok.
