### ISSUE TITLE
Handle NaN better

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#18842]
Any operation with `NaN` should either throw error or produce `NaN`. It should not produce number.

### Example
```nim
echo max(0/0, 1) # => 1.0
```

```
nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

P.S.

Also, I personally would prefer to not have `NaN` at all and throw error for `0/0` and similar operations producing `NaN`, as in wast majority it's an hidden error, and not intentional usage. I can't remember a single usage in my code when `NaN` wasn't error.

**Comment by hamidb80** [comment]
> Any operation with `NaN` should either throw error

have you tried this ?
```
--floatChecks:on|off  | turn all floating point (NaN/Inf) checks on|off
--nanChecks:on|off | turn NaN checks on|off
```

they are parts of runtime checks: https://nim-lang.org/docs/nimc.html

**Comment by al6x** [comment]
Thanks, I discovered it after I created the issue.
