### ISSUE TITLE
Is it a good idea that unknown warning pragmas gives compile errors?

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#18857]
I was going to add

{.warning[CStringConv]: off.}

to all my files to get ride of all these warnings.

But now people tell me that older compiler gives an error,

>/tmp/gintrosalewski/gen.nim(44, 23) Error: invalid pragma: warning[CStringConv]: off

See https://github.com/StefanSalewski/gintro/commit/29c5d63967d8b937201516a016457f88abea5176#commitcomment-56557830

Would ignoring unknown warning pragmas makes some sense? Well I may use some conditional code to fix that.

**Comment by juancarlospaco** [comment]
You can use `since (1, 5):` blocks in libs too.

**Comment by StefanSalewski** [comment]
>You can use since (1, 5): blocks in libs too.

The point is that we try to turn a warning of but forget that older compiler versions then create an error.

For the since (1, 5): how would I know/ensure that for example warning[CStringConv] was introduced after v1.4?

I think this "when compiles()" would be a relatively safe test.

Well, I will close this issue now, most people should have seen it.
