### ISSUE TITLE
cannot import addFloatRoundtrip and addFloatSprintf from system/formatfloat

### ISSUE THREAD

**Issue by ianfun** [nim-lang/Nim#18869]
Nim failed to import `addFloatRoundtrip` and `addFloatSprintf` from system/formatfloat
when using [vmops](https://github.com/nim-lang/Nim/blob/devel/compiler/vmops.nim)

### Example
```nim
from system/formatfloat import addFloatRoundtrip, addFloatSprintf
```

### Current Output
```
Nim\compiler\vmops.nim(32, 32) Error: undeclared identifier: 'addFloatRoundtrip'
```

### Additional Information
Nim build from c-source successfully before. (use build_all.bat)
$ nim -v
Nim Compiler Version 1.4.8 [Windows: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

**Comment by Araq** [comment]
Well you're not supposed to be able to import these directly. Not from version 1.4.8 anyway which simply lacks the feature.

**Comment by ianfun** [comment]
thanks.
I forgot to build with new compiler.
