### ISSUE TITLE
Nimfix does incomplete type substitution

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/Nim#1886]
It only substitutes the first type of the line in those examples;

> proc `++`_(x: var TInteger): TInteger {.discardable.} = inc(x); return x
> proc `|=`_[T:TInteger](x: var T, y: TInteger) {.inline, noSideEffect.} =   x = x or y

gets transformed in:

> proc `++`_(x: var SomeInteger): TInteger {.discardable.} = inc(x); return x
> proc `|=`_[T:SomeInteger](x: var T, y: TInteger) {.inline, noSideEffect.} =   x = x or y

**Comment by Araq** [comment]
Yeah, known bug. Running nimfix multiple times helps though... *cough*

**Comment by Araq** [comment]
Nimfix is not officially supported anymore.
