### ISSUE TITLE
Bug, openarray something wrong with closure scope

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#18874]
Using `openarray` causes problems. Don't know what's the problem, seems like it's related to closure scope or something like that. If `seq` used instead of `openarray` it works.

### Example

[playground](https://play.nim-lang.org/#ix=3zru)
```nim
import sugar, sequtils

proc diff*(values: openarray[float]): seq[float] =
  discard

echo @[@[1.0]].map((v) => v.diff) # Works
echo @[@[1.0]].map(diff)          # Fails
```

### Current Output
```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
........
/usercode/in.nim(7, 15) Error: type mismatch: got <seq[seq[float64]], proc (values: openArray[float]): seq[float]{.noSideEffect, gcsafe, locks: 0.}>
but expected one of: 
proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
  first type mismatch at position: 2
  required type for op: proc (x: T): S{.closure.}
  but expression 'diff' is of type: proc (values: openArray[float]): seq[float]{.noSideEffect, gcsafe, locks: 0.}

expression: map(@[@[1.0]], diff)
```

```
$ nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by beef331** [comment]
It's not a bug and just due to how openarray works, any collection to an openarray call requires a conversion to openarray which means there is a hidden operation done, as such `openArray[float]` != `seq[float]` in this case. Same as if you did
```nim
proc doStuff(p: proc(a: openarray[int]){.nimcall.}) = discard
doStuff(proc(a: seq[int]) = echo a)
```

**Comment by al6x** [comment]
The code in these two lines are equivalent, either both should work, or none, no? And so, if one is working and another does not, it looks like a bug.

```Nim
echo something.somefn((v) => v.dosomething) # Works
echo something.somefn(dosomething)          # Fails
```

**Comment by beef331** [comment]
They're not the same doing `v.diff` does the afformentioned implicit conversion. Take
```nim
proc doStuff(a: seq[int]) = echo a
doStuff(openarray[int](@[10, 20, 30])) # typemismatch got openarray expected seq
```
Openarray isnt a typedesc of `array or seq`, it's a unique type that without ambiguitity is callable with array or seq since it converts to a pointer with length, which is why it works with `array[bool, float]` or `array[-1..1, float]`. As such it doesnt match for type matches. This is not a bug, it's just simply how it works.

One possible alternative is the following:
```nim
import sugar, sequtils
type
  Array[T] = concept a
    a is array
    a[a.low] is T
  AnyArray[T] = seq[T] or Array[T]
  

proc diff*(values: AnyArray[float]): seq[float] =
  discard

echo @[@[1.0]].map((v) => v.diff)
echo @[@[1.0]].map(diff)
```

**Comment by Araq** [comment]
As others explained it's not a bug.
