### ISSUE TITLE
Cannot install master 2015-01-06T11:30

### ISSUE THREAD

**Issue by russel** [nim-lang/Nim#1887]
I installed successfully from master yesterday about 2015-01-06T17:48. This is on Fedora Rawhide. I updated my Git clone and run "sh build.sh" which completes fine. When I execute "koch install ~/Built" exactly as yesterday, I now get:

> [Linking]
> gcc: error: tools/niminst/nimcache/libzip_all.o: No such file or directory
> Error: execution of an external program failed

**Comment by dom96** [comment]
Instead of installing the compiler I would recommend just adding the ``bin`` directory to your PATH that way you can also easily update it.

**Comment by russel** [comment]
That is a workaround, but not a fix. I can do that for now, but it is much better to be able to install so as to always have a working Nim compiler even if master/HEAD will not compile.

**Comment by russel** [comment]
I am still getting:

[Linking]
gcc: error: tools/niminst/nimcache/libzip_all.o: No such file or directory
Error: execution of an external program failed

when I try to install Nim :-(

**Comment by Araq** [comment]
niminst doesn't use libzip anymore.
