### ISSUE TITLE
Warn about ambiguous function call

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#18903]
The `list.map(fn)` and `list.map((v) => v.fn)` produce different results.

Its not Nim bug, but Nim may warn on such cases. 

### Example

I was exploring some prices, and there was something unusual.

Price rates calculated as `price(t+span)/price(t)` with 

```Nim
proc rates*(values: seq[float], span = 1): seq[float] =
```

And these two lines produced different results:

```Nim
prices.map(rates)
prices.map((p) => p.rates)
```

Because, as it turned out, they were expanded in two different versions:

```Nim
prices.map((p, i) => p.rates(span = i))
prices.map((p) => p.rates(span = 1))
```

Full example, [play](https://play.nim-lang.org/#ix=3A5C)

```Nim
import std/sugar, std/options, std/sequtils

func map*[V, R](list: openarray[V], op: (v: V, i: int) -> R): seq[R] =
  for i, v in list: result.add(op(v, i))

proc rates*(values: seq[float], span = 1): seq[float] =
  result.set_len values.len - span
  for i in 0..<(values.len - span):
    result[i] = values[i+span] / values[i]

let prices = @[@[1.0, 2.0]]
echo prices.map(rates)          # => @[@[1.0, 1.0]]
echo prices.map((p) => p.rates) # => @[@[2.0]]
```

### Possible Solution

Maybe Nim could help with such cases by warning about such ambiguous calls, as `prices.map(rates)` satisfies both calls and could be expanded as any of those.

### Additional Information

```
nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by haxscramper** [comment]
This is not a bug, nor it is "unusual". You created overloaded version for map that takes callback which has two arguments, and supplies value and index to it. If you run the code from your snippet you can see that's exactly what is going on when you call first map

```nim
import std/sugar, std/options, std/sequtils

func map*[V, R](list: openarray[V], op: (v: V, i: int) -> R): seq[R] =
  for i, v in list: result.add(op(v, i))

proc rates*(values: seq[float], span = 1): seq[float] =
  dump((values, span))
  result.set_len values.len - span
  for i in 0..<(values.len - span):
    result[i] = values[i+span] / values[i]

let prices = @[@[1.0, 2.0], @[1.0, 2.0]]
echo prices.map(rates)   

# (values, span) = (@[1.0, 2.0], 0)
# (values, span) = (@[1.0, 2.0], 1)
# @[@[1.0, 1.0], @[2.0]]
       
```

In second case you supply callback with a single argument, that in turn calls 'rates' with defaulted argument. Again, code functions exactly as you wrote it, and there is nothing unusual about it.
