### ISSUE TITLE
Cross Compiler As Backend

### ISSUE THREAD

**Issue by sls1005** [nim-lang/Nim#18905]
I've tried to build a Hello World program for Windows with Mingw cross-compiler as backend on my Fedora. When I use "nim c --os:windows --cc:x86_64-w64-mingw32-gcc file.nim" on command line, My Nim compiler said that x86_64-w64-mingw32-gcc can't be recognized as a C compiler, since it doesn't appear in: gcc, switch_gcc, llvm_gcc, clang, lcc, bcc, dmc, wcc, vcc, tcc, pcc, ucc, icl, icc, clang_cl. Then I just "cd" to the cache directory and use "x86_64-w64-mingw32-gcc -I/usr/share/nim *.c" and It eventually worked.
C cross-compilers can be used as the backend for Nim, but Nim can't recognize them. I don't know if this is a bug or not. If it is, please fix it to support backends for cross-compile.

**Comment by ghost** [comment]
You're doing cross-compilation a bit wrong - `cc` is used to specify the "type" of the compiler, not the path to it. The correct way to do it is:
```
nim c --gcc.exe:"x86_64-w64-mingw32-gcc" --gcc.linkerexe:"x86_64-w64-mingw32-gcc" --os:windows file.nim
```

Of course, you don't need to call the Nim compiler with a lot of options each time, you can just put those into a .nim.cfg or a .nims file.

**Comment by ghost** [comment]
Also nim has a `-d:mingw` switch (see https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L83) that makes cross-compilation with mingw a bit easier:

```
nim c -d:mingw file.nim
```

**Comment by sls1005** [comment]
Thank you.
