### ISSUE TITLE
DocGen Copy button for code snippets 

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#18944]
Would be great to add a "Copy" button to the code blocks rendered by the Docgen,
just like GitHub itself has nowadays on the code blocks, the Docgen needs to add 1 line:

```html
<button onclick="document.querySelector('#SELECTOR').select();document.execCommand('copy');">Copy</button>
```

I copied from https://github.com/timotheecour/Nim/issues/802
@juancarlospaco

**Comment by vj-abishek** [comment]
I would like to contribute to this awesome project. Would you guide me on which file should I change? 

Here is my quick prototype

![image](https://user-images.githubusercontent.com/43115551/135740923-b96510e5-d4da-445d-9043-19cc581426c1.png)

**Comment by ringabout** [comment]
Hi @vj-abishek 

You may start from here: https://github.com/nim-lang/Nim/blob/6b0db5be1f21cec1b75822c021ccee79035a6f74/compiler/docgen.nim#L617

https://github.com/nim-lang/Nim/blob/6b0db5be1f21cec1b75822c021ccee79035a6f74/lib/packages/docutils/rstgen.nim#L1034

https://github.com/nim-lang/Nim/blob/devel/tools/dochack/dochack.nim

After fixing the file, you can use `koch temp doc -r ...` to test whether the fix works.

**Comment by vj-abishek** [comment]
![image](https://user-images.githubusercontent.com/43115551/135743069-52644e01-0519-4b8d-92b1-5dddd0718ed0.png)

I'm getting this error. 
How to run locally

**Comment by ringabout** [comment]
What's your command? Does `/home/abishek/opensource.nim` exist? How about putting the file under /Nim directory?

**Comment by vj-abishek** [comment]
I ran `./koch temp doc -r ..`  
When I run `koch temp doc -r ..` it says command not exists

> Does /home/abishek/opensource.nim exist?

No

> How about putting the file under /Nim directory?

 The dir structure is /home/abishek/opensource/Nim

Any documentation available on how to run locally. That docs page

**Comment by ringabout** [comment]
> I ran ./koch temp doc -r ..

Well, I mean `./koch temp doc -r yourdocfile.nim` 😄 
The reference docs: https://nim-lang.github.io/Nim/koch.html
