### ISSUE TITLE
Change branch of an object variant is allowed

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#18977]
In section [Object variants](https://nim-lang.org/docs/manual.html#types-object-variants) of manual, the example says
```nim
# invalid: would change the active object branch:
n.kind = nkInt
```

But in fact compiler accept it, and `=destroy` is called to prevent resources leak.

### Example
```nim
type
  E = enum
    a, b, c, d
  X = object
    v: int
  O = object
    case kind: E
    of a:
      a: int
    of {b, c}:
      b: float
    else:
      d: X

proc `=destroy`(x: var X) =
  echo "x destroyed"

var o = O(kind: d, d: X(v: 12345))
echo o.d

o.kind = a
echo o.a
```

### Current Output
```shell
$ nim r --gc:arc test.nim
(v: 12345)
x destroyed
0
```

`=destroy` will be called event with refc.

### Expected Output
Compile with error.

### Additional Information
If I change `d: X` to `d: ref X`, with arc or orc, output
```shell
$ nim r --gc:arc test.nim
(v: 12345)
x destroyed
139738855620680
```

With refc
```shell
(v: 12345)
test.nim(22) test
~/.choosenim/toolchains/nim-#devel/lib/system/assign.nim(294) FieldDiscriminantCheck
~/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: assignment to discriminant changes object branch [FieldDefect]
```

Tested with 1.4.8 and devel
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-10-07
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f03872d99ec2d25de829415a75162f9d8297bb19
active boot switches: -d:release
```

**Comment by ghost** [comment]
This is expected - newruntime (arc and orc) do support changing active branch at runtime as long as you don't have a custom destructor attached to your object variant

**Comment by Araq** [comment]
I think this should continue to be disallowed, the workaround is `o = O(kind: a, ...)` (reassign the complete structure).

**Comment by ringabout** [comment]
> I think this should continue to be disallowed

I agree. It should be covered by `{.cast(uncheckedAssign).}` instead.
