### ISSUE TITLE
"koch web" fails in HEAD

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#1898]
Relevant output:
```
nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.10.3 --docSeeSrcUrl:https://github.com/Araq/Nim/tree/master/lib -o:web/upload/system.html --index:on lib/system.nim
system.nim(2547, 15) Info: instantiation from here
system.nim(1115, 15) Error: undeclared identifier: 'useSysAssert'
system.nim(2547, 15) Info: instantiation from here
system.nim(2547, 15) Info: instantiation from here
system.nim(1115, 14) Error: internal error: cannot generate code for: mDefined
No stack traceback available
external program failed
Error: execution of an external program failed
```

**Comment by stefantalpalaru** [comment]
The error was actually my fault because a previous version of nim was used due to the wrong PATH order. After putting "./bin" first I get another error from 'PATH="./bin:$PATH" ./koch web':
```
nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.10.3 --docSeeSrcUrl:https://github.com/Araq/Nim/tree/master/lib/pure -o:web/upload/redis.html --index:on lib/pure/redis.nim
lib/pure/redis.nim(17, 7) Warning: sockets is deprecated [Deprecated]
lib/pure/redis.nim(156, 14) Hint: conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]
lib/pure/redis.nim(157, 36) Hint: conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]
lib/pure/redis.nim(159, 35) Hint: conversion from string to itself is pointless [ConvFromXtoItselfNotNeeded]
lib/pure/redis.nim(1036, 5) Hint: 'redis.assertListsIdentical(listA: seq[string], listB: seq[string])' is declared but not used [XDeclaredButNotUsed]
lib/pure/redis.nim(989, 5) Hint: 'redis.someTests(r: Redis, how: SendMode): seq[string]' is declared but not used [XDeclaredButNotUsed]
lib/pure/redis.nim(169, 5) Hint: 'redis.readArrayLines(r: Redis): RedisList' is declared but not used [XDeclaredButNotUsed]
lib/pure/redis.nim(149, 5) Hint: 'redis.readSingleString(r: Redis): RedisString' is declared but not used [XDeclaredButNotUsed]
Hint: operation successful (20620 lines compiled; 0.285 sec total; 22.225MB) [SuccessX]
nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.10.3 --docSeeSrcUrl:https://github.com/Araq/Nim/tree/master/lib/impure -o:web/upload/graphics.html --index:on lib/impure/graphics.nim
SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.)
external program failed
Error: execution of an external program failed
FAILURE
```

**Comment by Araq** [comment]
OS? Used C compiler? CPU?

**Comment by stefantalpalaru** [comment]
Linux amd 3.18.1-gentoo #1 SMP PREEMPT Thu Dec 18 17:45:09 CET 2014 x86_64 AMD FX-8320E Eight-Core Processor AuthenticAMD GNU/Linux

gcc-4.8.4

**Comment by Araq** [comment]
Works for me on Linux 64, gcc-4.8.2.

**Comment by reactormonk** [comment]
Works here as well. @stefantalpalaru could you provide some more information? To get a stracktrace, boot the compiler without the `-d:release` flag.

**Comment by oderwat** [comment]
Is this related? I tried to create the docs on my system (osx) with `./koch web` and got a similar error. 

Short version:

```
# in nim repo root
nim doc2 lib/system.nim

...
...
system.nim(2612, 15) Info: template/generic instantiation from here
system.nim(1117, 15) Error: undeclared identifier: 'useSysAssert'
system.nim(2612, 15) Info: template/generic instantiation from here
system.nim(2612, 15) Info: template/generic instantiation from here
system.nim(1117, 14) Error: internal error: cannot generate code for: mDefined
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

I also have an earlier problem with includes not working well. Line 23 in `system.nim` does:

```
## .. include:: ../doc/exception_hierarchy_fragment.txt
```

But that fails when I `./koch web`. First failure is when it descent into `lib/wrapper/mysql` .. copying `/doc/exeption...` there works :) .. but not the right thing to do!

I then included the `exception_hierarchy_fragment.txt` manual into `system.nim` and installed the compiler new. It loads the libs for creating the docs from the installed version when runnig `./koch web` what I think is a bit odd to do? 

Anyway after this I run into the above problem with `system.nim` failing to doc2 itself.

**Originally I wanted to call `nim doc2 somefile.nim` on a file to look for effects annotations as described in the docs.**

This failed with:

```
lib/nim/system.nim(24, 3) Error: cannot open '../doc/exception_hierarchy_fragment.txt'
Error: unhandled exception: lib/nim/system.nim(24, 3) Error: cannot open '../doc/exception_hierarchy_fragment.txt' [ERecoverableError]
```

and lead to this odyssey...

**Comment by stefantalpalaru** [comment]
It now works with gcc-4.9.2.

**Comment by eyan** [comment]
I get a similar error when doing './koch web'. Using nim-0.11.2 release on OSX Mavericks.

    lib/pure/asyncdispatch.nim(1410, 7) Hint: Processing main as an async proc. [User]
    lib/pure/httpclient.nim(825, 17) Info: template/generic instantiation from here
    lib/pure/asyncdispatch.nim(1196, 8) Warning: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory
    external program failed
    Error: execution of an external program failed
    FAILURE
    ~/bin/nim-0.11.2
    eyan@Devi$ E[V]? uname -a
    Darwin Devi 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by Araq** [comment]
``koch web`` now works on Mac OS X.
