### ISSUE TITLE
Import/except doesn't work on devel

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#18986]
I came across this when trying to compile my epaper project with the devel compiler. I managed to boil it down to a sample like this:

```nim
import macros

converter Lit(x: uint): NimNode = newLit(x)

var x = 0.uint
echo "Found a ", x
```

The `converter` was originally from my `macroutils` package (I think I'm going to remove this converter, it keeps creating weird bugs). The original code uses Futhark, and in that package I import `macroutils` with `import macroutils except Lit`. First of should an imported converter trickle through two modules? Secondly shouldn't `import macroutils except Lit` stop those converters from getting imported into Futhark in the first place?

NOTE: The above fails both on devel and on stable, the bug is in the following snippets

### Example
```nim
import macroutils except Lit
import macros

var x = 0.uint
echo "Found a ", x
```

### Current Output
```
(5, 6) Error: type mismatch: got <string, uint>
but expected one of:
proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 2
  required type for x: varargs[typed]
  but expression 'x' is of type: uint

expression: echo "Found a ", x
```

### Expected Output
```
Found a 0
```

**Comment by unclechu** [comment]
`nim-dbus` packages stops working in 1.6.0 because of this line:

https://github.com/zielmicha/nim-dbus/blob/74ec59f1813ae701764426c4ea0f11e092aefbe6/dbus/private/bus.nim#L3

``` nim
converter toBool(x: dbus_bool_t): bool = x != 0
```

Any further attempt to convert `uint32` to `string` fails with:

> /build/invert-window-colors-nim/app.nim:133:29 Error: ambiguous call; both dollars.$(x: bool) [proc declared in /nix/store/yl80s2wgj1zza5n8c8x96y8ym95vx5v2-nim-unwrapped-1.6.0/nim/lib/system/dollars.nim:34:6] and dollars.$(x: uint64) [proc declared in /nix/store/yl80s2wgj1zza5n8c8x96y8ym95vx5v2-nim-unwrapped-1.6.0/nim/lib/system/dollars.nim:18:6] match for: (uint32)

**Comment by unclechu** [comment]
```
/build/invert-window-colors-nim/app.nim:162:62 Error: type mismatch: got <string, uint32>
but expected one of:
func format(formatstr: string; a: varargs[string, `$`]): string
  first type mismatch at position: 2
  required type for a: varargs[string]
  but expression 'childWnd' is of type: uint32

expression: format("Parent window id for \'$1\' not found!", childWnd)
```

**Comment by unclechu** [comment]
@PMunch I took Nim 1.6.2 from `nixos-unstable` NixOS channel. My program was successfully compiled with no changes and works as before. I think this regression ca be considered as *fixed* and the issue can be closed?

**Comment by SolitudeSF** [comment]
still broken on devel (https://github.com/nim-lang/Nim/commit/731eabc9309997775c8be41f3e5eb5512460aad0)

**Comment by PMunch** [comment]
@xflywind, I saw you pinged me on Discord about this issue. Please try to keep everything in this issue, makes it easier to find and track messages :) I don't have a test case in Futhark unfortunately. Tried to build the project I mentioned above again now and I seem to have worked around this problem in Futhark somehow.

**Comment by ringabout** [comment]
I see, thanks
