### ISSUE TITLE
Regression in proc symbol resolution; Error: attempting to call routine 

### ISSUE THREAD

**Issue by quantimnot** [nim-lang/Nim#18990]
### Example
File `a.nim`
```nim
type A* = object
  a: uint8
```

File `b.nim`
```nim
type B* = object
proc A*(a, b: float): B = discard
```

File `tmain.nim`
```nim
import a, b
discard A(1f, 1f) # works
proc x(b = A(1f, 1f)) = discard # doesn't work
```

### Current Output
```
Error: attempting to call routine: 'A'
  found a.A [type declared in REDACTED/a.nim(1, 6)]
```

### Expected Output
[x] compiles

### Additional Information
I bisected it to commit 72b89eff82c54e771b6842674a4de3cbf714eae3.
#17379

**Comment by quantimnot** [comment]
Maybe a duplicate of #18959

**Comment by beef331** [comment]
in this case `a` is a module and file name, as such `a()` isnt callable doing `a.a()` should resolve it i believe.

**Comment by quantimnot** [comment]
I don't think the module name matters.

This is a simplified version from a different case in https://github.com/Ethosa/nodesnim/issues/32.

Changing `proc a(b = A(1f, 1f))` to `proc a(b = b.A(1f, 1f))` fixes it, but it still a regression.

I changed the simplified example to not confuse the issue.
