### ISSUE TITLE
hideCursor doesnt hide the cursor on DragonFlyBSD

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#18997]
terminal.hideCursor() in DragonFlyBSD dos not hide the cursor for tty

Example
```nim
import terminal,os
case commandLineParams()[0]:
 of "hide": hideCursor()
 of "show": showCursor()
 else: discard
```

Current Output
```
25lroot@:~ #
```

Solutions?
* Use a suited/different escape sequence for dragonfly specifically?

Compiler Info:
```
root@:~ # nim -v
Nim Compiler Version 1.4.8 [DragonFly: amd64]
Compiled at 2021-08-20
Copyright (c) 2006-2021 Andreas Rumpf

active boot switches: -d:release
```

**Comment by Araq** [comment]
We don't have access to a DragonFly machine and maybe they can accept ANSI escape sequences like the rest of the universe.
