### ISSUE TITLE
SIGSEGV during failed `of` check for ptr object

### ISSUE THREAD

**Issue by dsrw** [nim-lang/Nim#18999]
A failing `of` check for a `ptr object` throws a SIGSEGV rather than returning false. Tested with refc and orc on 1.4.8 and 1.6 RC3.

### Example
```nim
type
  Animal = ptr object of RootObj
  Cat = ptr object of Animal
  Plant = ptr object of RootObj

var cat = cast[Cat](alloc(sizeof(Cat)))

# works:
assert cat of Cat
assert cat of Animal

# crashes:
assert cat of Plant
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
AssertionDefect
```

**Comment by Araq** [comment]
Why should this work? You allocate the memory and you don't set the header. However, maybe the compiler should disallow the "of" operator for "ptr" types altogether when it cannot be determined statically.

**Comment by Araq** [comment]
This works:

```nim

type
  Animal = ptr object of RootObj
  Cat = ptr object of Animal
  Plant = ptr object of RootObj

var cat = cast[Cat](alloc(sizeof(Cat)))
cat[] = typeof(cat[])()

# works:
assert cat of Cat
assert cat of Animal

# crashes:
assert not (cat of Plant)
```

Watch out when you use `ptr`.
