### ISSUE TITLE
Casting compound types to incompatible types are allowed

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#18996]
Casting compound types such as objct/tuple/object variants to incompatible types are allowed.

### Example
```nim
type
  A = object
    v: string
  B = (float)
  E = enum
    e1
  C = object
    case kind: E
    of e1:
      v: seq[int]

let a = A(v: "hello")
let b: B = (3.14)
let c = C(kind: e1, v: @[1, 2, 3])

discard cast[ByteAddress](a)
discard cast[ByteAddress](b)
discard cast[ByteAddress](c)

discard cast[int](a)
discard cast[B](a)
discard cast[C](a)
discard cast[E](a)
#discard cast[pointer](a)    # expression cannot be cast to pointer
discard cast[seq[int]](a)
discard cast[set[char]](a)

discard cast[int](b)
discard cast[A](b)
discard cast[C](b)
discard cast[E](b)
discard cast[pointer](b)
discard cast[seq[int]](b)
discard cast[set[char]](b)

discard cast[int](c)
#discard cast[A](c)          # expression cannot be cast to A=object
discard cast[B](c)
discard cast[E](c)
#discard cast[pointer](c)    # expression cannot be cast to pointer
#discard cast[seq[int]](c)   # expression cannot be cast to seq[int]
discard cast[set[char]](c)
```

### Current Output
Compiled without error.

### Expected Output
Teat all these kinds of casting as error.

### Additional Information
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-10-15
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 73330711a3d753d25b073fb1dc24cb16e559724d
active boot switches: -d:release
```

**Comment by RSDuck** [comment]
I think this is right. As the [manual](https://nim-lang.org/docs/manual.html#statements-and-expressions-type-casts) says: "Type casts are a crude mechanism to interpret the bit pattern of an expression as if it would be of another type".

There are [safe casts or (conversions)](https://nim-lang.org/docs/manual.html#statements-and-expressions-type-conversions) in Nim which are done by using the type as a function.

**Comment by derekdai** [comment]
This issue is about object, not `ref` or `ptr`, the latter change the way how we see the bit pattern of pointing value, but cast compound value types to any other types (not parent or child object) feel not so right. As far as I know, C/C++ prevent programmer from doing these kind of casting.

Also, if these kind of casting are valid, commented cases above should pass compiling to make it consist.

**Comment by Araq** [comment]
Why would it not be allowed, it's a `cast`.
