### ISSUE TITLE
Varargs broken in 1.6.0 when len is 0 and preceding block arguments.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#19015]
Varargs is broken with block arguments when varargs len is 0.

### Example
```nim
import macros
macro hi(a : untyped, b : varargs[untyped]) : untyped =
  echo treeRepr a

hi:
  echo "hmm1"
```

### Current Output
```
Error: type mismatch:
got <void>
but expected one of:
macro hi(a: untyped; b: varargs[untyped]): untyped
  first type mismatch at position: 2
  missing parameter: a

expression: hi do:
  echo "hmm1"
```

### Expected Output
```
Hello World!
```

```
$ nim -v
Nim Compiler Version 1.6.0
```

**Comment by shirleyquirk** [comment]
workaround:
```nim
import macros
macro hi(a : untyped, b : varargs[untyped]) : untyped =
  echo treeRepr a

hi(void):
  echo "hmm1"
```
or
```nim
import macros
macro hi(a : untyped, b : varargs[untyped] = void) : untyped =
  echo treeRepr a

hi:
  echo "hmm1"
```

**Comment by solo989** [comment]
Your second solution only works if you do a check on b to see if the len is zero and only then because the symbol void happens to return a length of zero.
```nim
import macros
macro hi(a : untyped, b : varargs[untyped] = void) : untyped =
  echo treeRepr a
  echo treeRepr b
  #b.insert 0, a #broken

hi:
  echo "hmm1"
```

in this case the treeRepr of b is void so if I tryed to add a to it directly it wouldn't work.

If nim supported a minimum number of arguments on its varargs I would probably write this instead
```nim
import macros
macro hi(a : varargs[1,untyped]) : untyped =
  echo treeRepr a
```

and then it wouldn't accept hi() as a valid call

or alternatively call
```nim
macro hi() : untyped =
  discard
```
if it exists without any conflict.

**Comment by solo989** [comment]
Better solution
```nim
import macros
macro hi(a : untyped, b : varargs[untyped] = []) : untyped =
  echo treeRepr a
  echo treeRepr b
  b.insert 0, a

hi:
  echo "hmm1"
```
Still not a nnkArgList but at least  its something that has a default len of zero and can be added to.
Works with procs too
```nim
proc hi2(a : int, b : varargs[int] = []) =
  echo a
  echo b

hi2:
  5
```

**Comment by solo989** [comment]
Unfortunately this still doesn't work.
```nim
import macros
macro hi(a : untyped, b : varargs[untyped] = []) : untyped =
  echo treeRepr a
  echo treeRepr b
  b.insert 0, a
  #b == nnkArgList.newTree(a,nnkBracket.newTree())

template hi2(a : untyped, b : varargs[untyped] = []) : untyped =
  hi(a,b)

hi2:
  echo "hmm1"
```

**Comment by solo989** [comment]
A fix could be that the sigmatch matches the first non default argument that hasn't already been matched instead of working backwards like it does now.

**Comment by ghost** [comment]
FYI - this regression breaks https://github.com/yglukhov/iface as its `iface` macro signature is `macro iface*(arg1, arg2: untyped, moreArgs: varargs[untyped]): untyped =`. The workaround from this issue does fix it, but is still quite ugly.
