### ISSUE TITLE
Redefinition of anonymous function in parameters 1.6.0

### ISSUE THREAD

**Issue by shujidev** [nim-lang/Nim#19019]
Is this a bug?
Defining default values for function in parameters result in anonymous redefinition error
I just installed nim 1.6.0, I had 1.4.8

### Example
```nim
proc start(draw:proc=(proc()=echo "default"), init:proc=(proc()=echo "default"), reshape:proc=(proc()=echo "default"))=discard
start()
```

### Current Output
```
C:\Users\...\test.nim(75, 6) template/generic instantiation of `start` from here
C:\Users\...\test.nim(73, 58) Error: redefinition of ':anonymous'; previous declaration here: C:\Users\...\test.nim(73, 24)
```

```
$ nim -v
Nim Compiler Version 1.6.0 [Windows: amd64]
Compiled at 2021-10-19
```

**Comment by ynfle** [comment]
It is an issue of generics. The following works
```nim
proc start(draw: proc() = (proc() = echo "default"), init: proc() = (proc() = echo "default"), reshape: proc() = (proc() = echo "default")) =
  discard
start()
```
Not sure what the issue regression here is or if it was even supposed to work like that originally, but changing `proc` to `proc()` allows it to compile. The difference is the type `proc` is generic for any type of proc that has any amount and types of parameters and outputs and then `start` is treated as a generic proc. `proc()`, however, is a proc that takes no inputs and produces no outputs. Not sure why this makes a difference, what the error message is saying or what is the "correct" behaviour, but I hope this solves your issue.

**Comment by ringabout** [comment]
@github-actions nim c

```nim
proc start(draw:proc=(proc()=echo "default"), init:proc=(proc()=echo "default"), reshape:proc=(proc()=echo "default"))=discard
start()
```
