### ISSUE TITLE
Testament won't see installed packages

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/Nim#19017]
Since updating to Nim 1.6.0 from 1.4.8, testament can't run my tests in Norm anymore.

The reason—ndb package can't be imported.

This happens because `--clearNimblePath` flag was added to testament. I'm not entirely sure why it affects the tests this way but I can clearly see that its presence is the only difference between testament in 1.4.8 and 1.6.0, and my tests run OK in 1.4.8.

### Example

1. Clone Norm repo: https://github.com/moigagoo/norm
2. Update Dockerfile: `FROM nimlang/nim:1.6.0`
3. Run `docker-compose run tests`

See it fail:
```
FAIL: tests/postgres/tcount.nim c                                  ( 5.21 sec)
Test "tests/postgres/tcount.nim" in category "postgres"
Failure: reNimcCrash
$ /nim/bin/nim c --hints:on -d:testing --clearNimblePath --nimblePath:build/deps/pkgs   --nimCache:nimcache/tests/postgres/tcount.nim_4a8a08f09d37b73795649038408b5f33  tests/postgres/tcount.nim
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: used config file '/nim/config/config.nims' [Conf]
Hint: used config file '/usr/src/app/tests/config.nims' [Conf]
Hint: used config file '/usr/src/app/tests/postgres/config.nims' [Conf]
...........................................................................................................
/usr/src/app/src/norm/postgres.nim(3, 11) Error: cannot open file: ndb/postgres
```

Now revert Dockerfile: `FROM nimlang/nim:1.4.8`

Rebuild the image and run the tests again. They'll pass with time:
```
$ docker-compose build && docker-compose run tests
PASS: tests/common/tmodel.nim C                                    ( 8.78 sec)
PASS: tests/sqlite/tcount.nim C                                    (11.15 sec)
...
```

### Possible Solution

Remove `--clearNimblePath` from testament call command.

### Additional Information

```
$ docker run --rm nimlang/nim:1.6.0 nim -v
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release -d:danger
```

**Comment by Araq** [comment]
Ping @timotheecour

**Comment by moigagoo** [comment]
I'd be happy to send a PR but I so far failed to find where this flag is added.

**Comment by Araq** [comment]
testament/specs.nim

```nim

proc getCmd*(s: TSpec): string =
  if s.cmd.len == 0:
    result = compilerPrefix & " $target --hints:on -d:testing --clearNimblePath --nimblePath:build/deps/pkgs $options $file"
  else:
    result = s.cmd
```

**Comment by moigagoo** [comment]
I'm trying to fix this in https://github.com/nim-lang/Nim/pull/19018.

However, testament doesn't seem to be available in the CI environment as I'm getting "testament: not found" error.

I've tried looking in funs.sh and ci_packages.yml for the setup routine but couldn't find where I should squeeze testament installation in.

Could anyone please give me a hint?

**Comment by Araq** [comment]
I don't know more than you, you need to get testament in the $PATH somehow. I don't know enough about the CI setup to help you.

**Comment by ringabout** [comment]
> Could anyone please give me a hint?

Before it never puts testament to `bin/` directory for package CI. 
=> https://github.com/nim-lang/Nim/pull/19092

Related issues: https://github.com/nim-lang/Nim/issues/16838

**Comment by ringabout** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/19018

@timotheecour you may know more about the reason of setting `clearNimblePath`, it was introduced in this PR: https://github.com/nim-lang/Nim/pull/17132/files
