### ISSUE TITLE
Cannot instantiate generic type with not nil parameter type

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#19014]
Function `echo` outputs the wrong string.

### Example
```nim
{.experimental: "notnil".}
import tables

type FooObject = object
type Foo = ref FooObject not nil
type Bar = object
    table: Table[int, Foo]

proc `=init`(x: var Foo) =
    x = new(Foo)

let bar = Bar()
```

### Current Output
```
> nim c -r test.nim
Hint: used config file '/home/user/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/user/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
...................................................................
/home/user/computing/test/test.nim(12, 14) Error: The Bar type requires the following fields to be initialized: table.
```

#### 1
There should be some way to specify default value of `not nil` reference type.

#### 2
The error message doesn't tell why `table` can't be initialized.

#### 3
```nim
let table: Table[int, Foo] = newTable()
```
yields the compile error
```
Error: cannot instantiate: 'A'
```
not
```
Error: cannot instantiate: 'Foo'
```

### Possible Solution
Use [`=init` hook](https://github.com/nim-lang/RFCs/issues/252) or some other `proc` for the default value.

### Additional Information

This is related to https://nim-lang.github.io/Nim/manual_experimental_strictnotnil.html
This is related to [user defined default value](https://github.com/nim-lang/RFCs/issues/233).

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-10-15
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 73330711a3d753d25b073fb1dc24cb16e559724d
active boot switches: -d:release
```

**Comment by iacore** [comment]
## Trying to instantiate not nil ref type

```nim
{.experimental: "notnil".}
import tables

type FooObject = object
type Foo = ref FooObject not nil
type Bar = object
    table: Table[int, Foo]

proc `=init`(x: var Foo) =
    x = new(Foo)

let foo: Foo
```

### Output
```
Error: 'let' symbol requires an initialization
```

**Comment by Araq** [comment]
> Use =init hook or some other proc for the default value.

There is no `=init` hook in today's Nim. The RFC hasn't been implemented.

> Error: 'let' symbol requires an initialization

That's not a bug either.
