### ISSUE TITLE
cannot access a value in tuple by name in templates | but works by index

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#19016]
here"s a minimal example

### Example
```nim
type Group = tuple[field: bool]

proc withProc(a: int, b: Group) =
  echo a, b.field    # works fine

template withTempl(a: int, b: Group) =
  echo a, b.field    #  <-----------------  Error: undeclared field 'field'
  echo a, b[0]       #  works fine

withProc 1, (false,)
withTempl 1, (false,)
```

### Current Output
compile Error `undeclared field 'field'` 

### Expected Output
compiles successfully

### Additional Information
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-10-10
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 787def271b1cabc6f898caa42f892125de9fa908
active boot switches: -d:release
```

**Comment by beef331** [comment]
`(false, )` is a implictly converted to Group, but it doesnt have a `field` name unconverted so the template doesnt know `field` doing the following works as intended
```nim
type Group = tuple[field: bool]

proc withProc(a: int, b: Group) =
  echo a, b.field    # works fine

template withTempl(a: int, b: Group) =
  echo a, b.field    #  <-----------------  Error: undeclared field 'field'
  echo a, b[0]       #  works fine

withProc 1, (false,)
withTempl 1, (field: false,)
```
`b.field` is turned into `(false, ).field` and that tuple doesnt have a field hence the error.

**Comment by bj0** [comment]
I found this because I ran into the same thing and was really confused.  It still seems like a bug to me.   Another workaround:  The behavior works as expected if you define the field name as a template:

```nim
type Group = (bool,)  # either works
#type Group = tuple[field:bool]

template field(g:Group):auto = g[0]  
  
proc withProc(a: int, b: Group) =
  echo a, b.field    # works fine

template withTempl(a: int, b: Group) =
  echo a, b.field    #  <-----------------  works now
  echo a, b[0]       #  works fine

withProc 1, (false,)
withTempl 1, (field: false,)
withTempl 1, (false,)
```

Which makes the actual tuple syntax seem superfluous?

**Comment by beef331** [comment]
Well it should work, `field` is compiler magic which isn't properly handled in templates/array definitions, when you declare a `field` template it has a `call` which is sem'd and called. The issue with what you've done is now you can only have one tuple named `Group` with `field` being `[0]`.
