### ISSUE TITLE
Neither `=copy` nor `=sink` are called.

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#19023]
```nim
type
  Foo = object
    refC: ptr int

proc newFoo(): Foo =
  result.refC = cast[ptr int](alloc(sizeof(int)))
  result.refC[] = 1

proc `=destroy`(f: var Foo) =
  echo "Will destroy"
  assert(not f.refC.isNil)
  dec f.refC[]
  if f.refC[] == 0:
    dealloc(f.refC)
    f.refC = nil
    echo "Destroyed"

proc `=copy`(dst: var Foo, src: Foo) =
  echo "copy"
proc `=sink`(dst: var Foo, src: Foo) =
  echo "sink"

echo 1
var f = newFoo()
echo 2
var f2 = f
echo 3
```
```
nim c -r --gc:orc test.nim
```
**Actual result:**
```
1
2
3
Will destroy
Destroyed
Will destroy
...\test.nim(9Error: unhandled exception: ...\test.nim(11, 9) `not f.refC.isNil`  [AssertionDefect]
```
**Expected result:** there should be either "copy" or "sink" in the output.

**Nim version:** 62701cd3b92677c2014cf70b1cf5a5ba6e0468bf

**Disclaimer:** Maybe I'm misunderstanding how it should work. I'm trying to make a wrapper over refcounted foreign reference, but for that I would need either `=copy` or `=sink` called during `var f2 = f`.

**Comment by Araq** [comment]
Works if I put it in a `main` proc. Also destructors need to be protected against the `wasMoved` call:

```nim

proc `=destroy`(f: var Foo) =
  if f.refC != nil:
    echo "Will destroy"
    assert(not f.refC.isNil)
    dec f.refC[]
    if f.refC[] == 0:
      dealloc(f.refC)
      f.refC = nil
      echo "Destroyed"

```

As to why it doesn't call `=sink`, it's because there is no old object to destroy for `f2` (it's a fresh declaration).

**Comment by yglukhov** [comment]
> Also destructors need to be protected against the wasMoved call:

Ah, that explains it. Thank you.
