### ISSUE TITLE
Compiler version 1.6.0 does not work on Windows XP

### ISSUE THREAD

**Issue by rockcavera** [nim-lang/Nim#19038]
I have a Windows XP virtual machine on which I run some tests. I decided to test the new version of Nim and it didn't work. I get this error message: "Could not find procedure entry point _putenv_s in dynamic link library msvcrt.dll" (a translation of the message as the message is in Portuguese). The error occurs when trying to run the compiler with a simple `nim -v` or any other command.

Version 1.4.8 works normally.

The commit that caused this problem is this one: [6b3c77e7f4421267c551b1cd84717a19c65be2c5](https://github.com/nim-lang/Nim/commit/6b3c77e7f4421267c551b1cd84717a19c65be2c5).

Should Nim maintain Windows XP compatibility or not?

Edit: The `mbstowcs_s` function is also not supported by Windows XP crt and it is also present in the commit.

**Comment by ghost** [comment]
I don't really think that the effort should be spent for Windows XP officially, but you can of course have a fork that works with WinXP or a collection of patches. Also check out https://github.com/Skulltrail192/One-Core-Api

**Comment by dom96** [comment]
I think we can merge PRs that keep Win XP support, as long as the PR doesn't require too many changes.

**Comment by rockcavera** [comment]
I saw this possible solution [here](https://github.com/Tinkerforge/brickd/blob/master/src/brickd/fixes_msvc.c) and I believe it can be used on Nim. Haven't tested it yet. As I'll be out of time for a few weeks, at least I'll leave it here in case anyone is interested.
