### ISSUE TITLE
tcc compilation error when doing math

### ISSUE THREAD

**Issue by SebastianMpl** [nim-lang/Nim#19041]
Tiny c compiler throws error when doing compilation of math related stuff, e.g fibo

### Example
```nim
proc fib(n: uint64): uint64 =
    if n <= 1: return 1
    fib(n - 1) + fib(n - 2)

echo fib 40
```

### Current Output

```
tcc: error: undefined symbol 'fabs'
```

### Expected Output
```
165580141
```
### Additional Information
Compilation with gcc works fine. Issue with tcc happens in Nim1.6 and devel.
In version 1.4.8 it also works fine.

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-10-23
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 6621e1a3ead7166fa116bfbb8f0d2acb4e318d81
active boot switches: -d:release

```

**Comment by ponyatov** [comment]
nim.cfg
```
CC = tcc

tcc.options.linker = "-ldl -lm"
```

**Comment by SebastianMpl** [comment]
Now it works great. Thank you

**Comment by ajusa** [comment]
This also solved the problem for me, thanks! This issue can probably be closed I would think.
