### ISSUE TITLE
Compile error from backend gcc when generic int type is defined

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#19051]
Following code causes compile error on backend gcc:
```nim
type GInt[T] = int

var a = 1
echo -a
```

Compile log:
```
f:\temp>nim c -r -f test.nim
Hint: used config file 'f:\project\Nim\config\nim.cfg' [Conf]
Hint: used config file 'f:\project\Nim\config\config.nims' [Conf]
Hint: used config file 'C:\Users\xyzw\AppData\Roaming\nim\nim.cfg' [Conf]
.........................................................
f:\temp\test.nim(1, 6) Hint: 'GInt' is declared but not used [XDeclaredButNotUsed]
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: test.nim
f:\temp\nimcache\test\debug\@mtest.nim.c: In function 'NimMainModule':
f:\temp\nimcache\test\debug\@mtest.nim.c:143:41: error: expected ')' before '-' token
  143 |  T1_[0] = dollar___systemZdollars_3(((NI-24)-(a__test_3)));
      |                                      ~  ^
      |                                         )
Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fmax-errors=3   -If:\project\Nim\lib -If:\t
emp -o f:\temp\nimcache\test\debug\@mtest.nim.c.o f:\temp\nimcache\test\debug\@mtest.nim.c' failed with exit code: 1
```

Following code compiles successfully.
It seems defining generic int type and `-a` cause this problem.

Without GInt type:
```nim
var a = 1
echo -a
```

Without generics:
```nim
type GInt = int

var a = 1
echo -a
```

Use bool instead of int for GInt[T]:
```nim
type GInt[T] = bool

var a = 1
echo -a
```

Echo a as is:
```nim
type GInt[T] = int

var a = 1
echo a
```

Multiply `-1` instead of `-a`:
```nim
type GInt[T] = int

var a = 1
echo a * -1
```

`distinct int` type:
```nim
type GInt[T] = distinct int

var a = 1
echo -a
```

Tested on devel Nim:
```
nim -v
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2021-10-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 582468da1cc266d0dd922ec5c620713bbc45d02a
active boot switches: -d:release
```

**Comment by Araq** [comment]
What the ...? This is the weirdest bug I've ever seen.

**Comment by demotomohiro** [comment]
I have tested same code on Nim playground.
It compiles successfully on v0.19.6 but similar compile error comes from gcc in newer version of Nim.
https://play.nim-lang.org/#ix=3CRo

**Comment by EliteTK** [comment]
It took a bit of effort to bisect this but it looks like this was introduced in https://github.com/nim-lang/Nim/commit/745f1642d6faf3a30543cd76196a7462d7460d6d

**Comment by EliteTK** [comment]
So the buggy code is emitted in `ccgexprs` in `unaryArithOverflow` in the `mUnaryMinusI` case. `getSize` returns a negative value which gets multiplied by 8. Looks like prior to the bisected version `computeSizeAux` which was used to implement `getSize` via `computeSize` returned `conf.target.intSize` based on `typ.kind` if `typ.size` was negative (which appears to be the case for GInt in this case).

I'm still trying to figure out what exactly the right behaviour is here. If anyone has any ideas that would help.
