### ISSUE TITLE
Misplaced export marker '*' on generic iterator produces wrong error message.

### ISSUE THREAD

**Issue by geekrelief** [nim-lang/Nim#19063]
I'm running off devel.

In the code sample below I incorrectly exported `items[T]*` when it should be `items*[T]`.   And Nim reports: `Error: iterator needs a return type`.

```nim
iterator items[T]*(s: seq[T]): T = # Error: iterator needs a return type
  for i in  system.items(s):
    yield i
```

It should say ` Error: invalid indentation; an export marker '*' follows the declared identifier`.  Nim correctly reports the error for procs and types in the sample below.

```nim
#type SomeOtherObject[T]* = object
proc test[T]*(a: T) = echo a.repr
```

**Comment by ynfle** [comment]
Using `nim check` yields the intended error, but only as the third one, which is why it doesn't show up

**Comment by metagn** [comment]
Both give same error now
