### ISSUE TITLE
Stack traces broken with arc/orc

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#19078]
### Example
```nim
proc test =
    assert false

test()
```

### Current Output

something like
```
c:\Users\...\miauz.nim(5Error: unhandled exception: c:\Users\...\miauz.nim(3, 12) `false`  [AssertionDefect]
```

### Expected Output
```
c:\Users\...\miauz.nim(5) miauz
c:\Users\...\miauz.nim(3) test
C:\Nim\lib\system\assertions.nim(38) failedAssertImpl
C:\Nim\lib\system\assertions.nim(28) raiseAssert
C:\Nim\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: c:\Users\...\wegwerfscripte\miauz.nim(3, 12) `false`  [AssertionDefect]
```

### Additional Information
It's definitely a regression, I remember this worked some time ago, but I haven't bisected it yet.

```
$ nim -v
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2021-10-31
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 2f730afe9e7eb981258aea257deba0240f488dd1
active boot switches: -d:release
```

**Comment by disruptek** [comment]
FWIW, it works on 7b58dc2de0f606b757a558dfdda9d930ae63f41a which is dated 2021-08-19.

**Comment by RSDuck** [comment]
the issue seems to have been introduced with this commit: https://github.com/nim-lang/Nim/commit/394f4ac7bb92fe5aaf902495c6b43b3451667602

**Comment by RSDuck** [comment]
the issue only occurs with --exceptions:goto

EDIT: also if [this line](https://github.com/nim-lang/Nim/blob/devel/lib/std/private/miscdollars.nim#L10) is removed it "works".

**Comment by RSDuck** [comment]
ah I think I found the issue in the C code generated from this function: https://github.com/nim-lang/Nim/blob/devel/lib/system/excpt.nim#L252

```c
						if (!(((NI) 0) < s.p->data[i].line)) goto LA15_;
						prepareAdd((&result), 1);
appendString((&result), TM__Q5wkpxktOdTGvlSRo9bzt9aw_116);
						addInt__stdZprivateZdigitsutils_180((&result), s.p->data[i].line);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
```

the exception code is still non zero, that's why that goto after addInt__stdZprivateZdigitsutils_180 is followed and the string is incomplete.

**Comment by Araq** [comment]
Workaround `--panics:on`.
