### ISSUE TITLE
isAdmin() in OS module does not exist/is undeclared

### ISSUE THREAD

**Issue by WeebNetsu** [nim-lang/Nim#19089]
I'm running this on Manjaro Linux, and both my IDE (VSCode) and compilier tells me that the isAdmin() procedure in the OS module does not exist. However, it is in the docs, [right here](https://nim-lang.org/docs/os.html#isAdmin).

### Example
```nim
import os
echo isAdmin() # does not exist
```

### Current Output
`Error: undeclared identifier: 'isAdmin'`

### Expected Output
```
true (or false)
```
### Compiler Version
```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
```

**Comment by ghost** [comment]
The docs URL you linked always shows the docs of the latest Nim release which is 1.6.0 at the time of writing, but your Nim is 1.4.8 which does not have that feature in the `std/os` module.
`isAdmin` was only introduced in 1.6.0 - https://github.com/nim-lang/Nim/blob/version-1-6/changelogs/changelog_1_6_0.md#os-stdos-stdio-stdsocketstream-stdlinenoise-stdtempfiles

Also if you want to check docs for older Nim versions you can get them like this - https://nim-lang.org/1.4.8/os.html, or build them yourself locally.
