### ISSUE TITLE
One line if/else doesn't compile with nim 0.10.2 or nimrod 0.9.6

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1909]
When [line 154 of lazy_rest_pkg/lrstgen.nim](https://github.com/gradha/lazy_rest/blob/22c5d8dda7cca8da947e160765f585772c700001/lazy_rest_pkg/lrstgen.nim#L154) is uncommented, the code won't compile:
```
$ nim c lazy_rest_pkg/lrstgen.nim
lrstgen.nim(154, 63) Error: type mismatch: got (Find_file_handler) but expected 'proc (string, string): string{.gcsafe, locks: 0.}'
```
Same thing happens for [line 165](https://github.com/gradha/lazy_rest/blob/22c5d8dda7cca8da947e160765f585772c700001/lazy_rest_pkg/lrstgen.nim#L165):
```
lrstgen.nim(165, 61) Error: type mismatch: got (TMsgHandler) but expected 'proc (string, int, int, TMsgKind, string): string{.gcsafe, locks: 0.}'
```
These if/else won't compile with 0.9.6, but they do compile with 0.9.4.

**Comment by Araq** [comment]
Please extract a small test case out of this, shouldn't be hard. I get: 

lazy_rest/lazy_rest_pkg/lrst.nim(15, 39) Error: cannot open 'bb_system'

**Comment by gradha** [comment]
Running ``nimble build`` will deal with the dependency.

**Comment by Araq** [comment]
Well I need a test case out of this anyway since it's a regression, so please do it.

**Comment by Araq** [comment]
I think this might just be an unfortunate side-effect of the new 'locks' effect.

**Comment by Araq** [comment]
No feedback.
