### ISSUE TITLE
Casting from smaller type to bigger type can produce random bits

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#19101]
When `cast[T]` is used to cast smaller size value to bigger size value, a part of the resulting value contains random bits.

Example code:
```nim
import std/[strutils]

type
  Small = object
    a: int

  Big = object
    a, b, c, d: int

proc main =
  var
    n = 1'i8
    f = 2.0
    s = Small(a: 1)
    b = Big(a: 12345, b: 23456, c: 34567, d: 45678)

  echo cast[int](f).toBin(64)
  f = cast[float](n)
  echo cast[int](f).toBin(64)

  echo b
  b = cast[Big](s)
  echo b
main()
```

Output:
```
0100000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000010000000011010000000001
(a: 12345, b: 23456, c: 34567, d: 45678)
(a: 1, b: 16, c: 4260937, d: 11)
```

Expected output:
```
0100000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000001
(a: 12345, b: 23456, c: 34567, d: 45678)
(a: 1, b: 0, c: 0, d: 0)
```
(Result of casting `int8` to `float` depends on endianness)

This is a part of C code generated by Nim:
```c
N_LIB_PRIVATE N_NIMCALL(void, main__testcast_9)(void) {
  NI8 n;
  NF f;
  ...
  union { NI8 source; NF dest; } LOC3;
  ...
  LOC3.source = n;
  f = LOC3.dest;
```

Nim uses C's union to implement `cast[T]` but that union variable is used without initialization and it can contains any value.
So if a source of `cast[T]` is smaller than the union variable, a part of the union variable is unchanged when the source value is copied to it.
If your code reads these random value, it can cause a bug randomly happens.

Possible solutions:
1. Fix C/C++ code gen so that random value is never generated
   - Initialize a C union with zero like Nim variables.
   - Implement it with `memcpy` or `memmove` and copy only sizeof(source value) bytes

2. Show warning or error when `cast[T](s)` is used and sizeof(T) > sizeof(s) (or sizeof(T) != sizeof(s))
   - std::bit_cast in C++20 looks similar to Nim's `cast` but it compiles only if sizeof(To) == sizeof(From)
     - https://en.cppreference.com/w/cpp/numeric/bit_cast
   - Making it compile error is a breaking change?

3. It is not an issue as manual says "Type casts are inherently unsafe"

Nim version
```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2021-11-04
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Araq** [comment]
(1) or (3), maybe (1) only if -d:danger is not used.

**Comment by demotomohiro** [comment]
Another strange code using `cast`.
This code initialize an object type with all bits 1 using cast.
Then set all fields of it but that doesn't change bits on padding.
And comparing fields ignores bits on padding.
All `cast` in this code casts between same size type.

```nim
import strutils

type
  ObjWithPadding = object
    x: int8
    y: int32

proc main =
  let a = ObjWithPadding(x: 7, y: 123)

  var b = cast[ObjWithPadding](not 0'i64)
  b.x = 7
  b.y = 123

  doAssert a == b
  doAssert cast[int64](a) != cast[int64](b)

  echo cast[int64](a).toBin(64)
  echo cast[int64](b).toBin(64)

  var c = cast[ObjWithPadding](not 0'i64)
  c = ObjWithPadding(x: 7, y: 123)

  doAssert a == c
  doAssert cast[int64](a) == cast[int64](c)

  echo cast[int64](c).toBin(64)

main()
```

Output:
```
0000000000000000000000000111101100000000000000000000000000000111
0000000000000000000000000111101111111111111111111111111100000111
0000000000000000000000000111101100000000000000000000000000000111
```

**Comment by demotomohiro** [comment]
I have implemented 2 procedures that works like `cast` but slightly safer.
They are in bitwiseCopy module in this project:
https://github.com/demotomohiro/littlesugar

**Comment by Varriount** [comment]
> (1) or (3), maybe (1) only if -d:danger is not used.

I vote for (1) by default.

**Comment by konsumlamm** [comment]
I think this should at the very least be a warning. As of right now, casting from a smaller type to a bigger type is UB (not just "producing random bits"), so every program doing that is already broken. Initializing to zero would be a solution, but that's not always a valid value for the type that is produced. In fact, the only types I can think of right now where this makes sense is integer types, but for those you shouldn't use `cast` in the first place (as you can use `uint32`, `int`, etc.). So my preferred option would be to make it a hard error, as I'd expect casting to a bigger type to be a programmer mistake usually (perhaps they thought that the sizes were equal, but they're not?). Another option would be to simply have two versions of `cast`: one that doesn't compile when the target size is bigger and one that just pads the remaining bits with zeroes.

**Comment by Araq** [comment]
What you said makes sense. We can make it a warning first before it turns into an error.
