### ISSUE TITLE
Out-of-bounds in strformat

### ISSUE THREAD

**Issue by christoph-ehm** [nim-lang/Nim#19107]
The ampersand macro allows for an out-of-bounds-access of `f` at two places. This happens, when a single brace is not closed properly. With high probability, this is not noticed but there is little probability that no error message occurs.

https://github.com/nim-lang/Nim/blob/5845716df8c96157a047c2bd6bcdd795a7a2b9b1/lib/pure/strformat.nim#L307

I'm a very new learner of Nim so that I don't know the software quality standards for Nim's library code but I think the readability of this macro (and the other big thing in the file) is not good. The unfortunate combination of missing parentheses with 2-space indentation makes it hard for me to see the end of big blocks. It's low-level spaghetti code but could have historical reasons. Better variable names and outlining procedures could improve the readability.

**Comment by juancarlospaco** [comment]
> 2-space indentation makes it hard for me

😕

**Comment by abisxir** [comment]
I still face this issue in version 2.2.0:
Works:
`
let key = "LIGHTS[" & $(lightCount) & "].TYPE"
`
Fails:
`
let key = fmt"LIGHTS[{lightCount}].TYPE" # Same for &"LIGHTS[{lightCount}].TYPE"
`

**Comment by narimiran** [comment]
Please, show a full self-contained example of the code that fails, and what would be the expected behavior. 
(You can follow all the things you have to fill out when you open a new bug report)
