### ISSUE TITLE
os.getFileInfo reports wrong filesize for big files (>2GB), as the computed int64 value from two int32 values is wrong.

### ISSUE THREAD

**Issue by eulores** [nim-lang/Nim#19135]
File sizes under Windows OS reported through `os.getFileInfo()` are wrong when the size of the file on disk is at least 0x80000000 bytes big (> 2GB).

### Example
```nim
import std/os
const fn = "deleteme.big"
var f = open(fn, fmWrite)
block:
  defer:
    f.close()
  f.setFilePos(0x80000000)
  f.write('x')
  echo f.getFileSize() # correct: 2147483649
var fi = getFileInfo(fn)
echo fi.size # wrong: -2147483647
removeFile(fn)
```

### Current Output
```
2147483649
-2147483647
```

### Expected Output
```
2147483649
2147483649
```

### Possible Solution

In file os.nim, cast both arguments of the `merge` template defined in the `rawToFormalFileInfo` template to `uint64`, and the result back to `int64`.
I'm not that familiar with the nim syntax, but this seems to do the trick for me:
`template merge(a, b): untyped = (int64)((uint64)(cast[uint32](a)) or (uint64)(cast[uint32](b)) shl 32)`

Other similar code in the library uses the deprecated `ze64` procedure (see `winlean.rdFileTime` and `winlean.rdFileSize`)

### Additional Information

See this code segment in `os.nim`:
```nim
template rawToFormalFileInfo(rawInfo, path, formalInfo): untyped =
  when defined(windows):
    template merge(a, b): untyped = a or (b shl 32)
    formalInfo.size = merge(rawInfo.nFileSizeLow, rawInfo.nFileSizeHigh)
```

Argument `a` and `b` used in the merge template are `winlean.DWORD` (`int32`), the return is `BiggestInt` (`int64`).

For the `a` argument:
- Any `int32` value with the highest bit set (any negative number), stays negative when cast to `int64`. Therefore, `if nFileSizeLow >= 0x8000`, then the resulting `formalInfo.size` becomes negative.

For the `b` argument:
- The `shl 32` operation shifts any 32 bit wide argument into nirvana.

This is also related to #12327, #11555, #344 (DWORD defined differently in winlean and os)

```
$ nim -v
Nim Compiler Version 1.6.0 [Windows: amd64]
```

**Comment by Varriount** [comment]
Thanks!
