### ISSUE TITLE
Add link to std/tempfiles in the docs

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#19155]
The name says it all. https://nim-lang.github.io/Nim/lib.html shows no reference to it, only the index does.

**Comment by konsumlamm** [comment]
I added it in https://github.com/nim-lang/Nim/issues/16656, which is a more general issue, so ig this is a duplicate now.

The underlying "problem" is that modules don't automatically get added to `lib.rst`, but it doesn't seem like there are any plans to change that...

**Comment by Araq** [comment]
It would require us to patch every library to use something like `under topic: operating system related` and then new stdlib modules could forget to do that just like we can forget to add it to lib.rst today. Maybe the better idea is to simply check that every stdlib module name occurs in lib.rst?
