### ISSUE TITLE
Weird static macro parameter issue

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#1916]
```nimrod
import macros
macro t(n: static[int]): stmt = echo n
t(1)
```
outputs `140225971302872` instead of `1`.

**Comment by fowlmouth** [comment]
:+1:

**Comment by reactormonk** [comment]
`140449013738584` here.

**Comment by dom96** [comment]
``16398968`` here!

**Comment by flaviut** [comment]
Well, the exact value isn't really important. Some uninitialized value is being used instead of the correct value.

**Comment by dom96** [comment]
I know, I'm just stating what I get for fun :)

**Comment by gmpreussner** [comment]
Seems to work correctly now. Output: ```1``` with latest devel compiler on Windows.

**Comment by Araq** [comment]
Indeed, Zahary fixed this.
