### ISSUE TITLE
Linking to your web page produces unexpected output

### ISSUE THREAD

**Issue by BruceEckel** [nim-lang/Nim#19160]
![image](https://user-images.githubusercontent.com/1001900/142066134-7a8636e6-5e55-472b-a05f-12bce3b42ad6.png)

I don't think you mean "compiles to" those languages, at least the text on the home page suggests otherwise.

**Comment by konsumlamm** [comment]
I don't see the problem, Nim does indeed compile to these languages. The home page also says

> Support for various backends: it compiles to C, C++ or JavaScript so that Nim can be used for all backend and frontend needs.

If you wanna be pedantic and say that it actually should say "transpiles", I don't think that's a useful discussion to have (if you still care, I suggest reading https://peterme.net/is-nim-a-transpiler.html).

**Comment by BruceEckel** [comment]
OK, that was not clear to me. I can see that "compiling to binary" could
mean "compiling to binary via C/C++ etc." but I didn't get that impression
right away.

*Bruce Eckel*

**Comment by hamidb80** [comment]
https://peterme.net/is-nim-a-transpiler.html

**Comment by dom96** [comment]
Closing as the text isn't problematic.
