### ISSUE TITLE
Experimental features in normal manual instead of experimental manual/undocumented

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#19162]
The experimental features `compiletimeFFI`, ~~`dynamicBindSym`~~ and `vmopsDanger` are not documented in the experimental manual as of 1.6.0 ([full list](https://github.com/nim-lang/Nim/blob/a8611c665f26adbf7f6dd2438359b4c5d930bf86/compiler/options.nim#L189)). Since `vmopsDanger` seems to do very little and `compiletimeFFI` seems to be unfinished, I'm not sure if they need to be documented. `dynamicBindSym` is documented in [macros.bindSym](https://nim-lang.org/docs/macros.html#bindSym%2C%2CBindSymRule) and in [0.19 changelog](https://github.com/nim-lang/Nim/blob/dbf8d0b8946419311ac710b1adc995ad206b52c1/changelogs/changelog_0_19_0.md#compiler-changes) however, which may be enough.

However the following experimental features are documented in the regular manual instead of the experimental manual. Don't know if this is intended.

- `strictEffects` ([manual](https://nim-lang.org/1.6.0/manual.html#effect-system-effectsof-annotation))
- ~~`unicodeOperators` ([manual](https://nim-lang.org/1.6.0/manual.html#lexical-analysis-unicode-operators))~~ 
- ~~`overloadableEnums` ([manual](https://nim-lang.org/1.6.0/manual.html#types-overloadable-enum-field-names))~~

**Update:** Since #19173, only `compiletimeFFI` and `vmopsDanger` are not documented, and `strictEffects` is still in the regular manual, because it may eventually leave experimental status.

**Comment by beef331** [comment]
I think you missed strict not nil in the [manual](https://nim-lang.org/docs/manual_experimental.html#strict-not-nil-checking)

**Comment by metagn** [comment]
I swear it wasn't there when I checked, multiple times. Now there's no concrete issue, except that maybe the 1.6 experimental features should be in the experimental manual instead of the normal manual, which I'm not even sure is a mistake, or maybe some of the undocumented obscure experimental features should be documented.
