### ISSUE TITLE
allow case of on single line

### ISSUE THREAD

**Issue by levovix0** [nim-lang/Nim#19178]
### Summary
allow
```nim
case x of y:
  # ...
```
syntax

It may be useful with caseStmtMacros ~or to match values (`case x of y, z` instead of `if x == y or x == z`, where y and z are static)~

**Comment by demotomohiro** [comment]
You can write `if x in [y, z]` instead of `if x == y or x == z` and y and z doesn't need to be const.

**Comment by juancarlospaco** [comment]
Maybe you can use chained boolean comparisons via metaprogramming,
kinda like https://juancarlospaco.github.io/nodejs/nodejs/jschainedcomparisons

**Comment by Araq** [comment]
There is always `if` and for 10 years nobody complained, which indicates there is no wide need for your proposal.

**Comment by levovix0** [comment]
Example with fusion/mathing. This is not easy replaceable by if
```nim
import fusion/matching
{.experimental: "caseStmtMacros".}

proc sumFirst(x: seq[int]): int =
  case x of [@a, @b, .._]:
    a + b
  else: 0
```
