### ISSUE TITLE
`dup`can easily be defined as a template on `with`

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#19175]
I have noticed that the implementations for [`with`](https://github.com/nim-lang/Nim/blob/c7920e9f87f0c30b3d7db8dd6e8cf528c0ba15be/lib/std/with.nim#L38-L39) and [dup](https://github.com/nim-lang/Nim/blob/c7920e9f87f0c30b3d7db8dd6e8cf528c0ba15be/lib/pure/sugar.nim#L284-L288) use a module in std/private unique to them and is only 40 lines long. However, you can just define `dup` as

```nim
import std/with

template dup(value: untyped, args: varargs[untyped]): untyped =
  var dupResult = value
  dupResult.with(args)
  dupResult
```

Why is this not the case? Why have a separate module for `with` named `with`, especially given that `with` is also the name of the macro in the [Nimble package named `with`](https://github.com/zevv/with) which could very well go in the standard library/`sugar` but behaves completely differently? The standard library `with` has to be imported as `std/with` which I imagine means it was known that it would conflict with the Nimble package, but why not just put it in `sugar`? Why are `with` and `dup` named so differently as well? Couldn't you name them something like `apply` and `applyDup`?

I am sorry if I am coming across as rude, but I really do not understand this if it was intended. I think more simple, primitive macros or templates in the standard library would be better but I imagine people will be put off from using them if they are incoherent/inconsistent like this.

To me it makes the most sense for the underscored_calls module and `with` to go in `sugar`, and then to define `dup` as a template on `with`. Ideally they would also be renamed and documented to reflect each other, with the old names and `std/with` as an alias. Is this a good idea?

**Comment by Araq** [comment]
This was extensively discussed here: https://github.com/nim-lang/RFCs/issues/192

`dup` is regarded to be useful enough to be in "sugar", allowing us to simplify some APIs eventually, `with` is far less important, so it got a separate import.
