### ISSUE TITLE
Well, SDLAda is my project. That requirement is really quite idiotic.

### ISSUE THREAD

**Issue by chatchai-hub** [nim-lang/Nim#19186]
Well, SDLAda is my project. That requirement is really quite idiotic.

_Originally posted by @Lucretia in https://github.com/github/explore/pull/2707#issuecomment-976411953_

**Comment by Lucretia** [comment]
What??

**Comment by Yardanico** [comment]
@xflywind maybe also add the "invalid" label and lock the issue? And if the same person creates multiple spammy issues, ban them from the org?

**Comment by xflywind** [comment]
> maybe also add the "invalid" label and lock the issue

I agree

> ban them from the org

Only owner can ban people for this org afaik
