### ISSUE TITLE
variables in closure iterators loop are not correctly unassigned

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#19193]
### Example
```nim
iterator test(): int {.closure.} =
  for i in 0..<1000000:
    var heavy: seq[int]
    heavy = newSeq[int](10000)
    yield heavy.len

GC_disableMarkAndSweep()

for i in test():
  discard
```

will use a lot of memory, because the lines:
```nim
var heavy: seq[int]
heavy = newSeq[int](10000)
````
will generate:
```c
(*colonenvP_).heavy2 = (tySequence__qwqHTkRvwhrRyENtudHQ7g*)0;
asgnRef((void**) (&(*colonenvP_).heavy2), newSeq__eA9b5cYyFZe7gRm4F9aRTKlA(((NI) 10000)));
```
which erases the last reference before calling `asgnRef`.

Assigning directly avoids this issue:
`var heavy = newSeq[int](10000)`
Because the `heavy2 = 0` line is not generated, and `asgnRef` will call `decRef` on the last value.

### Possible Solution
It seems that in regular procs, the var line will be translated to:
```c
asgnRef((void**) (&fut__JYhQvJxHhtC8fq7FzTRUVQ), NIM_NIL);
asgnRef((void**) (&fut__JYhQvJxHhtC8fq7FzTRUVQ), testInner__bhBT5he32hyARROogQacKg());
```
Since we assign to NIL instead of setting to 0 manually, the reference count is correctly updated

### Additional Information
Happens both on 1.2.6 & devel.
Obviously, the mark & sweep will catch that, but as part of optimizing ram consumption in nimbus, we're trying to rely on it as little as possible

**Comment by Araq** [comment]
I cannot prioritize this bug, as a workaround exists and IMHO in order to optimize memory consumption you should compile with --gc:orc and 1.6.0 and run the sanitizers, esp. valgrind on it.

**Comment by arnetheduck** [comment]
> optimize memory consumption

our issue is not so much in finding memory issues, that's not too hard :) This issue is about addressing the ones we do find that are systemic with the default GC - all this while we wait for ORC to work well enough that we reliably can use it.
