### ISSUE TITLE
Unexported converters propagate through imports and affect code

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#19213]
If you have an unexported converter in a module that is imported by another module that calls a procedure that takes the same type as the converter, then the code might break in unexpected ways.

### Example
```nim
# other.nim
converter toBool(x: uint32): bool = x != 0
```

```nim
# main.nim
import other

let a = 5'u32
echo a
```

### Current Output
```
/home/dian/Projects/NimExperiments/other.nim(1, 11) Hint: 'toBool' is declared but not used [XDeclaredButNotUsed]
/home/dian/Projects/NimExperiments/main.nim(4, 6) Error: type mismatch: got <uint32>
but expected one of:
proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 1
  required type for x: varargs[typed]
  but expression 'a' is of type: uint32

expression: echo a
```

### Expected Output
```
5
```

### Additional Information
One example of a module that has a converter which can affect user code is https://github.com/zielmicha/nim-dbus/blob/master/dbus/private/bus.nim#L3 - if you import the `dbus` module and try to `echo` an uint32, the code won't compile. 

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-12-04
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0d0c249074d6a1041de16108dc247396efef5513
active boot switches: -d:release
```
Also tested on Nim 1.6.0 through Wandbox - https://wandbox.org/permlink/yFWPFOlTo72o5Rmc

**Comment by unclechu** [comment]
Related: https://github.com/nim-lang/Nim/issues/18986#issuecomment-985960287

**Comment by ghost** [comment]
The code stopped compiling after #15935 - "979148e863c4142a00632059f3e2a57f4ab0f960 is the first bad commit"

**Comment by PMunch** [comment]
This seems to be broken again.. At least I'm getting the same kind of issues on 1.6.4 when using Futhark. I have `import macroutils except Lit` but in the code which imports the module I wrap with Futhark I get `Error: request to generate code for .compileTime proc: Lit`
