### ISSUE TITLE
Anonymous functions at compiletime

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1922]
I'd like to make list comprehensions work at compile time as well and found 2 problems during it (and still no solution how to do it at compiletime):

```nim
const c = (proc(): int = 10)()
```
Gives the error:
```
lcc.nim(20, 28) Error: constant expression expected
```
So instead I tried this:
```nim
proc foo: seq[int] = (proc(): seq[int] = result = @[2])()
const bar = foo()
echo bar
```
No error now, but bar ends up being `nil`.

**Comment by Araq** [comment]
Now works for me.
