### ISSUE TITLE
Internal error on trying to iterate on an empty array/seq

### ISSUE THREAD

**Issue by ZoomRmc** [nim-lang/Nim#19224]
Internal error on trying to iterate on an empty array/seq
This probably requires a proper handling:

### Example
```nim
for _ in []: discard
# Error: internal error: getTypeDescAux(tyEmpty)
```
```nim
for _ in @[]: discard
# Error: internal error: getTypeDescAux(tyEmpty)
```

### Expected Output
Not an internal error.

---

Same output starting from Nim 0.15.0.

**Comment by ghost** [comment]
At least a part of this issue (about the array) is a duplicate of https://github.com/nim-lang/Nim/issues/11684

**Comment by ZoomRmc** [comment]
Yep, sorry, a duplicate.
