### ISSUE TITLE
Error: internal error: expr(skModule); unknown symbol on "import X; X"

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#19225]
I encountered an internal error by accident due to wrong copy/paste.

### Example
it really works with any `import X; X` pattern
```nim
import std/sequtils; sequtils
```

### Current Output
```
Error: internal error: expr(skModule); unknown symbol
```

### Expected Output
```
compilation successful
```

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-12-06
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: e5475768ba5b540489fb47bdb6fdd338d75175e1
active boot switches: -d:release
```
it also happens on stable 1.6.0

**Comment by ghost** [comment]
Not sure why this should be a "compilation successful", you're referencing the module symbol without doing any action on it

**Comment by arkanoid87** [comment]
My fault, I didn't mean to write "compilation  successful" but actually "returns proper error"
