### ISSUE TITLE
internal error: expr: var not init - in custom finalizer

### ISSUE THREAD

**Issue by izackp** [nim-lang/Nim#19231]
Using a variable inside of an iterator does not work. 

### Example
```nim
type
  Game* = ref object

proc free*(game: Game) =
  var mixNumOpened:cint = 0
  for i in 0..<mixNumOpened:
    mixNumOpened -= 1

proc newGame*(): Game =
  new result, free

var
  game*: Game
```

### Current Output
It results in this error. 
```
/opt/homebrew/Cellar/nim/1.6.0/nim/lib/system/iterators_1.nim(129, 17) Error: internal error: expr: var not init mixNumOpened_452984858
```

### Expected Output
It's expected to compile successfully or with an error that's not internal

### Possible Solution
Changing the object around to use =destroy seems to fix the issue

```nim
type
  GameObj = object
    fTest: cint
  Game* = ref GameObj

proc `=destroy`(obj: var GameObj) =
    echo "destroy"
    var mixNumOpened:cint = 0
    for i in 0..<mixNumOpened:
        mixNumOpened -= 1

var
  game*: Game

echo "hello"
game = new Game
game.fTest = 3
echo game.fTest
```

### Additional Information
This was an attempt at compiling nimgame2 using 1.6.0

Tested mostly on Nim Compiler Version 1.6.0 [MacOSX: arm64], but issue also appears on the latest devel branch at 99f8793502e65cd43f6e301557d428758948c3ca

**Comment by ghost** [comment]
~~See https://github.com/nim-lang/Nim/issues/14243 about nimgame2, probably a duplicate.~~

**Comment by izackp** [comment]
I'm not sure if this is 100% related. Though it seems to add to the fact that `new type, free` on reference types is pretty damn buggy

```nim
type
    Game* = ref object
        test:cint
        test2:cint

proc freeTexture*(graphic: Game) =
    if not (graphic.test != 0):
        graphic.test = 0

proc free*(graphic: Game) =
    freeTexture(graphic)
    graphic.test2 = 0
    echo "test ", graphic.test

proc newGame*(): Game =
  new result, free

proc example(game: Game) =
    game.freeTexture()
    game.test2 = 1
    echo "test2 ", game.test2

var game = newGame()
game.example()
```

build fails with cpp backend
```
nim cpp --cc:clang --gc:arc -d:useMalloc -g --nimcache:out --debugger:native -r -o:/Users/isaacpaul/Projects/nim/TestZone/bin/finalizerBug src/finalizerBug.nim
```
Succeeds with c backend
```
nim c --cc:clang --gc:arc -d:useMalloc -g --nimcache:out --debugger:native -r -o:/Users/isaacpaul/Projects/nim/TestZone/bin/finalizerBug src/finalizerBug.nim
```

The error:
```
 no matching function for call to 'freeTexture_finalizer66ug_5'
 ```
 it seems like only `freeTexture_finalizer66ug_5(tyObject_GamecolonObjectType___5QKBBJ9bXZNJgqPQ4M8DYeQ* graphic)` is generated but it's used twice in the code with different arguments Game& vs Game*
 
 Tested on Nim Compiler Version 1.6.0 [MacOSX: arm64]
