### ISSUE TITLE
Don't use numbers, use const variables ?

### ISSUE THREAD

**Issue by olusis** [nim-lang/Nim#19242]
https://github.com/nim-lang/Nim/blob/a3ef5df680e55d9bf68027fcb0ec6358b4279d09/tools/urldownloader.nim#L77

**Comment by ghost** [comment]
Can you please explain the problem more thoroughly? I can't understand what's the issue here.

**Comment by Araq** [comment]
There is no issue here, sometimes rules can safely be ignored.
