### ISSUE TITLE
Manual example: `{.cast(uncheckedAssign).}` assignment to discriminator produces `[FieldDefect]`

### ISSUE THREAD

**Issue by geekrelief** [nim-lang/Nim#19266]
In the manual.rst under the `cast uncheckedAssign` section there a two issues.  
1) A typo `unsafeAssign` should be `uncheckedAssign`.

2) The manual says assignment to the discriminator under `{.cast(uncheckedAssign).}` should work, but it produces: 
`Error: unhandled exception: assignment to discriminant changes object branch; compile with -d:nimOldCaseObjects for a transition period [FieldDefect]`

Here's the manual sample on nim playground: https://play.nim-lang.org/#ix=3IGq

And a smaller repro:
```nim
type
  TokenKind* = enum
    strLit, intLit
  Token = object
    case kind*: TokenKind
    of strLit:
      s*: string
    of intLit:
      i*: int64

var t = Token(kind: strLit, s: "abc")

{.cast(uncheckedAssign).}:

  # inside the 'cast' section it is allowed to assign to the 't.kind' field directly:
  t.kind = intLit
```

### Expected Output
I'd assume this should compile cleanly, or the the manual needs updating.  I don't know which would be correct.

### Additional Information
Tested on (v1.6.0) on nim playground.

**Comment by ringabout** [comment]
compiles with ARC
