### ISSUE TITLE
Logging requires specific GLIBC version

### ISSUE THREAD

**Issue by bluemax75** [nim-lang/Nim#19263]
If I compile the following on Archlinux (nim c test.nim):
```nim
import logging

debug "hello"
```
And then try to run it on Redhat 7 I get the following error:
```$ ./test
./test: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./test)
```

This happens with both devel and 1.6.0

If logging is not used the error does not appear

**Comment by ghost** [comment]
That's not really a Nim problem - it's a common C problem when you dynamically link against libc, and that's done by the C compiler, not Nim. If you want to be able to run your binary on older versions of glibc, use a cross-compiler that targets older glibc or set up an environment with your target (e.g. a RHEL7/CentOS 7 VM or a container for compilation). See https://askubuntu.com/questions/1021420/glibc-2-25-not-found-on-ubuntu-windows-subsystem-for-linux for some more info.

Another way you can fix this is by statically linking libc, for example with musl.

**Comment by dom96** [comment]
You can also give this a try: https://github.com/wheybags/glibc_version_header.

But yeah, this is unrelated to `logging`. Simplest way is to build on a really old Linux. This isn't a Nim bug though so closing.
