### ISSUE TITLE
`!=` overloading across modules and via templates creates "cannot attach a custom pragma"

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#19277]
This doesn't seem to occur with other operators that I've tested thus far. Whether or not `!=` is meant to be overloadable separately (or redefined in the case of `int`s), it does seem to work within modules, when templates don't come into play much, or when there aren't pra

### Example
I haven't yet reproduced this without using at least two modules. The main module:
```nim
# This push raises, or something like it, is thus far necessary.
{.push raises: [Defect].}

# This isn't required for anything in the main module, but if it doesn't
# export its `!=` operator, it won't have any effect. But it affects the
# otherwise unrelated `!=` operators for, e.g., type `S`.
import b

when false:
  # Not only does this version not cause any problems, it allows the importing
  # of b without any compilation error.
  type N = object
    d: float    # Not necessary, just ensuring it's structurally distinct
  template `!=`(a, b: N): bool = true

# Can be a wide range of types
type S = object
#type S = int    # e.g., this triggers the issue identically

template e(x: S, r: untyped): untyped =
  template h: untyped {.inject.} = x
  r

template m(x: S): S = e(x): h

# The types don't seem to matter here -- b(x: X), whether its return type is
# auto, untyped, or something else, et cetera.
template b(x: untyped): untyped = x

# As long as S().m.b() is on a side of the inequality, it triggers. This is
# neither type Z (from module b) nor type N, but another unrelated type and
# which has what should be an unrelated inequality operator.
discard default(S).m.b != default(S)
```

Module `b`, imported by the main module:
```nim
type Z = object
template `!=`*(a, b: Z): bool = true
doAssert Z() != Z()  # the operator overload does seem to work, just not across

# This does work, and triggers the same behavior as using `Z`.
#template `!=`*(a, b: int): bool = true
#doAssert 5.int != 5.int
```

### Current Output
```
$ Nim/bin/nim c a
Hint: used config file '/home/anden/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/anden/Nim/config/config.nims' [Conf]
..........................................................
/home/anden/a.nim(30, 24) template/generic instantiation of `!=` from here
/home/anden/a.nim(18, 3) Error: cannot attach a custom pragma to 'h'
```

Tested, with the same error, with current Nim head:
```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-12-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 19898e1225862560b216b765187fc0b98dca7608
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

and
```
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2020-02-04
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

### Expected Output
Successful compilation, or if not, internally consistent behavior.

**Comment by Araq** [comment]
You cannot overload `!=`.

> Successful compilation, or if not, internally consistent behavior.

It's logically impossible for a program not to be "internally consistent". ;-)

**Comment by tersec** [comment]
I can, indeed, overload `!=`:
```nim
type
  A = distinct int
  B = distinct int
  C = distinct int
  D = distinct int

template `!=`(x, y: A): bool = x.int != y.int * 2
template `!=`(x, y: B): bool = x.int == y.int
template `!=`(x, y: C): bool = true
template `!=`(x, y: D): bool = false

for i in -10000 .. 10000:
  doAssert A(i) != A(i) or i == 0
  doAssert not(A(2*i) != A(i))
  doAssert A(3*i) != A(i) or i == 0
  doAssert B(i) != B(i)
  doAssert not (B(i + 1) != B(i))
  doAssert C(i) != C(i)
  doAssert not(D(i) != D(i))

template `!=`(x, y: int): bool = x == y
for i in -10000 .. 100000:
  doAssert i != i
```

Tested on Nim 1.6.2 and Nim head.

**Comment by metagn** [comment]
Simplified:

```nim
# untypedtemplate.nim
template foo*(x: untyped) =
  echo "got: ", x

# specialized.nim
proc foo*(a: string) =
  echo "got string: ", a

# main.nim
import untypedtemplate, specialized

template injector(val: untyped): untyped =
  template subtemplate: untyped = val
  subtemplate()

template methodCall(val: untyped): untyped = val

{.push raises: [Defect].}

foo(injector(0).methodCall())
```

* The overload in `untypedtemplate.nim` must be an untyped (immediate) template and not for example a generic proc, and its argument must be evaluated.
* It does not matter if the overload in `specialized.nim` is a proc or a template, but the argument has to be typed, not necessarily evaluated.
* `untypedtemplate.nim` must be imported first.
* It does not matter if `subtemplate` has arguments or is invoked with parentheses. I looked at this issue to see if it intersects with #13515, but it doesn't.
* Method call syntax only breaks for the `methodCall` template. Parentheses are optional.
* `0` can be anything that isn't accepted by the overload in `specialized.nim`. Otherwise it compiles.

Overload resolution between immediate template and typed overload + nested templates + template indirection + method call syntax + `push` pragma. As far as I can tell all of these are necessary.

**Comment by demotomohiro** [comment]
@tersec 
You don't need to overload `!=` operator.
When `!=` operator is used, Nim automatically transform it to `not (x == y)`.
https://nim-lang.org/docs/system.html#!=.t,untyped,untyped
So this code works without overloading `!=` operator.

```nim
type
  Foo = object
    x: int

proc `==`(x, y: Foo): bool = x.x == y.x

let
  a = Foo(x: 1)
  b = Foo(x: 2)

echo a != b
```

You cannot use the method call syntax with templates or macros that first parameter is `untyped`.
https://nim-lang.org/docs/manual.html#templates-limitations-of-the-method-call-syntax

First paramter of template `b` in main module in your code is `untyped`.
So Nim compiles without error when `discard default(S).m.b != default(S)` in your code is rewritten to `discard b(default(S).m) != default(S)`.

**Comment by Araq** [comment]
> I can, indeed, overload !=:

The compiler currently allows it, but it's not supported and unnecessary. Define `==` and you always have the corresponding `!=`.
