### ISSUE TITLE
Slice type error

### ISSUE THREAD

**Issue by inv2004** [nim-lang/Nim#19281]
### Example
```nim
>>> let t = "asd"
>>> echo typeof(t[0..1]) 
```

### Current Output
```
chat
```

### Expected Output
```
string
```

```
Nim Compiler Version 1.6.0
```

**Comment by ringabout** [comment]
Workaround: use `typeof(t[0..1], typeOfProc)`.

Duplicated of https://github.com/nim-lang/Nim/issues/12383
