### ISSUE TITLE
Request: Ability to start doc comments for fields on next line (like types)

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#1929]
type
      Foo = object
        ## This really long doc comment works just fine
        someReallyLongFieldNamex: int ## This doc comment works, too
        anotherReallyLongFieldName: int
          ## This really long doc comment does not work, because
          ## it does not end up in the AST

**Comment by Araq** [comment]
Use this: 

```nim
type
  Foo = object
    ## This really long doc comment works just fine
    someReallyLongFieldNamex: int ## This doc comment works, too
    anotherReallyLongFieldName: int ## \
      ## This really long doc comment does not work, because
      ## it does not end up in the AST

**Comment by gmpreussner** [comment]
That will work, but it's not as pretty. Why not keep this open as a low priority issue? Is my proposal not possible syntax wise?

**Comment by dom96** [comment]
I will reopen this because I agree with @gmpreussner

**Comment by gmpreussner** [comment]
This is fixed.
