### ISSUE TITLE
strictEffects: regression in recursive effect tracking

### ISSUE THREAD

**Issue by ee7** [nim-lang/Nim#19303]
### Example
Compile the below with `nim c --experimental:strictEffects`.

```nim
type
  Foo = object
    bar: seq[Foo]

proc `==`(a, b: Foo): bool =
  a.bar == b.bar
```

### Current output
```
/tmp/foo.nim(6, 9) template/generic instantiation of `==` from here
/tmp/nim/lib/system/comparisons.nim(284, 6) Error: '==' can have side effects
> /tmp/nim/lib/system/comparisons.nim(309, 13) Hint: '==' calls `.sideEffect` '=='
>> /tmp/foo.nim(5, 6) Hint: '==' called by '=='
```

### Expected output
No error.

### Additional information
The error was introduced by fce89cb60a34, and was not fixed by the commit that fixed https://github.com/nim-lang/Nim/issues/19159.

When compiling with `strictEffects`, Nim is complaining that the `==` operator for seqs has side effects, despite being annotated with `noSideEffect`. In particular, Nim complains about the per-item comparison on line 309:
https://github.com/nim-lang/Nim/blob/ac37eed5a28042d50e23d9ae145f2d46b8dc5058/lib/system/comparisons.nim#L284-L312

The error occurs with the latest `devel` commit (ac37eed5a280) and Nim 1.6.2, but not Nim 1.6.0 (which introduced `strictEffects`). Occurs on Linux, macOS, and Windows.

The example code is reduced from code in the [`parsetoml`](https://github.com/NimParsers/parsetoml) package. To reproduce the problem, compile this Nim file:

```Nim
import pkg/parsetoml
```

with `strictEffects`. That works with Nim 1.6.0, but Nim 1.6.2 and `devel` produces:

```
/home/foo/.nimble/pkgs/parsetoml-0.6.0/parsetoml.nim(1745, 27) template/generic instantiation of `==` from here
/tmp/nim/lib/system/comparisons.nim(284, 6) Error: '==' can have side effects
> /tmp/nim/lib/system/comparisons.nim(309, 13) Hint: '==' calls `.sideEffect` '=='
>> /home/foo/.nimble/pkgs/parsetoml-0.6.0/parsetoml.nim(1725, 6) Hint: '==' called by '=='
```

In that case, the error-producing line is [this one](https://github.com/NimParsers/parsetoml/blob/9cdeb3f65fd1/src/parsetoml.nim#L1745).

**Comment by Araq** [comment]
This works:

```nim

{.experimental: "strictEffects".}

type
  Foo = object
    bar: seq[Foo]

proc `==`(a, b: Foo): bool {.noSideEffect.} =
  a.bar == b.bar
```

So it's another case of https://github.com/nim-lang/RFCs/issues/435
