### ISSUE TITLE
`compiles` does not allow exported symbols

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#19302]
### Example
```nim
# top level
when compiles((let x* = 3;)):
  echo "yes"
else:
  echo "no"
```

### Current Output
```
no
```

### Expected Output
Not sure, but there should be some mechanism to make this work.

### Additional Information
* `export` statement also fails.
* `import` statement works.

```
$ nim -v
Nim Compiler Version 1.6.2
```

**Comment by Araq** [comment]
`compiles` is not concerned with syntax errors and this fails to compile too:

```nim

template ignore(x): bool = false

when ignore((let x* = 3;):
  echo "yes"
else:
  echo "no"
```

No bug here.

**Comment by metagn** [comment]
Typo lol. I meant `((let x* = 3;))`.

The point is that no symbols can be exported in the expression passed to `compiles`. This is inconvenient because I want to give `compiles` an expression that will go to top level. `import` works, `export` doesn't.
