### ISSUE TITLE
Request: Pragma to specify the alignment of object fields

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#1930]
I was looking for something like {.align: 8.} to override how fields in an object are packed in memory, but couldn't find anything. I'm currently creating some bindings for C library that make heavy use of align().

Example:

```
type Foo {.align: 8.} = object
  x: int
  y: int
```

Or maybe we can reuse the {.packed.} pragma for that.

**Comment by Araq** [comment]
Is there a C library left that's not full of junk? ;-)
