### ISSUE TITLE
tinyc compiler flag is undocumented

### ISSUE THREAD

**Issue by n5m** [nim-lang/Nim#19329]
The `-d:tinyc` compiler flag is not documented anywhere:
https://github.com/nim-lang/Nim/blob/9df195ef581879cf9e5c3c3154755bd1dba677c6/compiler/commands.nim#L35

It is not clear what it does, since compilation (usually? always?) can succeed with the flag omitted.

```nim
# hello.nim
import httpclient
let c = newHttpClient()
echo repr(c)
```

```console
$ nim --CC:tcc --out:first --hints:off c hello.nim
$ nim -d:tinyc --CC:tcc --out:second --hints:off c hello.nim
$ diff -q -s first second 
Files first and second are identical
```

```console
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9df195ef581879cf9e5c3c3154755bd1dba677c6
active boot switches: -d:release
```
9df195ef581879cf9e5c3c3154755bd1dba677c6

**Comment by Araq** [comment]
Remove the flag please.

**Comment by Araq** [comment]
TinyC is not officially supported.
