### ISSUE TITLE
Broken recvFrom on devel

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#19326]
recvFrom in net.nim has been broken since 4b5cecd902cc4126ff9d6cda9edb78a13a421239

This line causes an issue because of invalid casting syntax for the untyped parameter [123d798b39756a95de82d119d2fe6661157ebb20407e2c394b7490e7588d2294R1630](https://github.com/nim-lang/Nim/commit/4b5cecd902cc4126ff9d6cda9edb78a13a421239#diff-123d798b39756a95de82d119d2fe6661157ebb20407e2c394b7490e7588d2294R1630)

Example to cause the problem:
```nim
import std/net
let socket = newSocket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
var
  buff, address: string
  port: Port
discard socket.recvFrom(buff, 0, address, port)
```

**Comment by rockcavera** [comment]
I get this error when compiling:
```
nim c test
Hint: used config file 'D:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'D:\Nim\config\config.nims' [Conf]
................................................................................................
c:\Users\Jose\Desktop\test.nim(7, 15) template/generic instantiation of `recvFrom` from here
D:\Nim\lib\pure\net.nim(1657, 26) template/generic instantiation of `adaptRecvFromToDomain` from here
D:\Nim\lib\pure\net.nim(1631, 38) Error: undeclared field: 'SockLen' for type system.int [type declared in D:\Nim\lib\system\basic_types.nim(2, 3)]
```

For some unknown reason the Nim compiler is assuming that the cast from `int` to `SockLen`, via dot notation, is an access of some field of an object. Does this compiler issue need further investigation?
