### ISSUE TITLE
`httpclient` memory leak

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#19337]
Hey, 
Yersterday I ran a telegram bot that is written in Nim on my server, I found out that the memory usage keeps increasing untill it crashes.

I tried to make a minimal example:

### Example
```nim
import httpclient

while true:
  let
    ahc = newHttpClient()
    body = ahc.getContent("https://jsonplaceholder.typicode.com/posts")

  echo body.len
```

### Possible Solution

* I have no idea

### Additional Information
tested on windows 10 64bit and [nimlang/nim:1.6.2-alpine-onbuild](https://hub.docker.com/layers/nimlang/nim/1.6.2-alpine-onbuild/images/sha256-11c9bc9bd8b8f42cdebd66e45beb4878b7f42c5bd3ae81f31e6ef7d9a8a837ce?context=explore)

```
>> nim -v
Nim Compiler Version 1.6.2 [Windows: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

compiled with:
* `nim -d:ssl --mm:arc -d:usemAlloc r .\src\raw.nim`
* `nim -d:ssl --mm:arc r .\src\raw.nim`
* `nim -d:ssl r .\src\raw.nim`
* `nim -d:ssl -d:release r .\src\raw.nim`

**Comment by Araq** [comment]
Async requires --gc:orc, not arc. Please try it and report back.

**Comment by hamidb80** [comment]
Thank u for responding, 
It's not async, its just a simple sync httpclient

**Comment by Araq** [comment]
Yes but there might be callbacks involved that create cycles regardless.

**Comment by hamidb80** [comment]
same with `--mm:orc`

**Comment by ghost** [comment]
@hamidb80 that's not a bug, you forgot to `close` the httpclient which is needed to close the connection and deallocate all relevant things (like the SSL context).
```nim
import httpclient

while true:
  let
    ahc = newHttpClient()
    body = ahc.getContent("https://jsonplaceholder.typicode.com/posts")

  echo body.len
  ahc.close()
```

With this code I can't see any leaks with `--gc:orc -d:danger -d:useMalloc` with valgrind.

**Comment by hamidb80** [comment]
thanks, i think it's good idea to mention it in top of https://nim-lang.org/docs/httpclient.html
