### ISSUE TITLE
able to redefine a tuple variable

### ISSUE THREAD

**Issue by jpoirier** [nim-lang/Nim#1935]
Say we have a procedure that returns a tuple, then

The following correctly fails due to "a" being redefined:
    var (a, b) = test()
    ...some code...
    var (a, c) = test()

There is no redefinition error when a defer statement is inserted somewhere between the two calls:
    var (a, b) = test()
    ...some code...
    defer: goodbye()
    ...some code...
    var (a, c) = test()

**Comment by Araq** [comment]
defer is rewritten to a 'try finally' which gets its own scope. It's definitely something we need to look at though.

**Comment by dom96** [comment]
@jpoirier Why are you closing so many of your own issues?

**Comment by Araq** [comment]
Now fails with "redefinition of 'a'" as expected.
