### ISSUE TITLE
CrowdStrike Falcon (Anti-Virus) thinks that the binaries that Nim creates are malicious. 

### ISSUE THREAD

**Issue by robert-mcdermott** [nim-lang/Nim#19387]
Nim version 1.6.2

I can compile a program just fine, but when I attempt to execute it, the CrowdStrike agent will delete it and my IT department contacts me thinking my computer is infected. I can't use Nim programs at work until this is fixed. Not sure why they think it's a virus. Here is what my IT department sees:

![image](https://user-images.githubusercontent.com/7399563/149424432-818b1572-2fc8-4495-b992-5d443a9f7431.png)

**Comment by ghost** [comment]
That's quite unfortunate, but we already have an issue about the malware detections - https://github.com/nim-lang/Nim/issues/17820, so closing this as a duplicate

**Comment by robert-mcdermott** [comment]
Thanks, can't use Nim at my work to build tools then. Too bad I like Nim, Golang it is then.

**Comment by ghost** [comment]
@robert-mcdermott yes indeed, but that's not Nim's fault, it's the fault of bad AVs and people who write malware in Nim

**Comment by robert-mcdermott** [comment]
Sorry to hear that, but Nim doesn't have a future if this is not resolved.

**Comment by SolitudeSF** [comment]
lol
