### ISSUE TITLE
Finalizer not called for type `ref object of RootObj` when using ARC/ORC + Forward declaration

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#19402]
### Example
compile with --gc:arc
```nim
type Foo = ref object of RootObj
proc delete(self: Foo) 
proc newFoo: Foo = new(result, delete)
proc delete(self: Foo) = echo("delete Foo")

if isMainModule:
  proc test() = discard newFoo()
  test()
```

### Current Output
```
none
```

### Expected Output
```
delete foo
```

### Additional Information
Tested nim version 1.4.2 up to devel (15e3813d96ad5646476b629f3a20ece89dff064d)

It works with --gc:refc, it gives a different problem if `type Foo = ref object` (see https://github.com/nim-lang/Nim/issues/19401)

**Comment by filcuc** [comment]
This impact NimQml. See 
https://github.com/filcuc/nimqml/issues/43
 https://github.com/filcuc/nimqml/issues/42

**Comment by filcuc** [comment]
without RootObject with Nim 1.6.2
```nim
type Foo = ref object

proc delete(self: Foo) 
proc newFoo: Foo = new(result, delete)
proc delete(self: Foo) = echo("delete Foo")

if isMainModule:
  proc test() = discard newFoo()
  test()
```
I get 
```
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

**Comment by arkanoid87** [comment]
> without RootObject with Nim 1.6.2
> 
> ```nim
> type Foo = ref object
> 
> proc delete(self: Foo) 
> proc newFoo: Foo = new(result, delete)
> proc delete(self: Foo) = echo("delete Foo")
> 
> if isMainModule:
>   proc test() = discard newFoo()
>   test()
> ```
> 
> I get
> 
> ```
> No stack traceback available
> To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
> ```

see https://github.com/nim-lang/Nim/issues/19401

**Comment by xflywind** [comment]
Looking into it, it turns out to print `internal error: expr: proc not init delete` like https://github.com/nim-lang/Nim/issues/19401 after I made a simple fix.

**Comment by ringabout** [comment]
Workaround: use codeReordering

```nim
{.experimental: "codeReordering".}

type Foo = ref object of RootObj
proc delete(self: Foo)  # it can be omitted
proc newFoo: Foo = new(result, delete)
proc delete(self: Foo) = echo("delete Foo")

if isMainModule:
  proc test() = discard newFoo()
  test()
```

**Comment by filcuc** [comment]
@xflywind it seems code reordering is not enough for making NimQml work..probably code reordering is experiemental for a reason :D

**Comment by ringabout** [comment]
Yeah, I agree. It needs a real fix.

**Comment by filcuc** [comment]
@Araq and @xflywind  any tip for debugging this one. Maybe i can try to look and debug this one in the compiler but a couple of hints could increase my success chances. I quickly skimmed the output in the c files but didn't noticed anything interesting (or maybe failed to understand them).

**Comment by Araq** [comment]
Look at `lifdestructors.nim` and maybe at `injectdestructors.nim`

**Comment by ringabout** [comment]
Hello, @filcuc Here is the progress => https://github.com/nim-lang/Nim/pull/20295, but I cannot try it out with nimQML

**Comment by filcuc** [comment]
@ringabout i'll try your fix asap

**Comment by filcuc** [comment]
@ringabout i've tested it and it works! nice!!!

**Comment by filcuc** [comment]
@ringabout the only thing i've notice is that even if i'm using orc/arc deletion of object is not called immediately. However if i make a call to GC.forceFullCollect i see the finalizers being called...seems like something is "deferring" the deletion
