### ISSUE TITLE
base64.encode breaks at non ending \x00 on Windows, resulting in different results from Linux

### ISSUE THREAD

**Issue by hlizard** [nim-lang/Nim#19411]
nim (compile to util.dll/.so):
```nim
import base64

proc b64decode(str: cstring): cstring {.cdecl, exportc, dynlib.} =
  ($str).decode.cstring

proc b64encode(str: cstring): cstring {.cdecl, exportc, dynlib.} =
  ($str).encode.cstring
```

lib.py (cffi to call nim):
```python
# coding=utf-8
import cffi
import platform

ffi=cffi.FFI()

ffi.cdef("""
char* b64decode(char* str);
char* b64encode(char* str);
""")

lib=ffi.dlopen("util."+('dll' if platform.system() == 'Windows' else 'so'), ffi.RTLD_GLOBAL)


def b64decode(s):
    return ffi.string(lib.b64decode(s))

def b64encode(s):
    return ffi.string(lib.b64encode(s))

```

test.py (call lib.py):
```python
# coding=utf=8

# import base64
import util as base64

print base64.b64encode('test测试')

print base64.b64decode('dGVzdOa1i+ivlQ==')


with open(u'./success.png', 'wb') as f2:
    with open(u'./static/risk/success.png', 'rb') as f:
        content = f.read()
        print 'base64:'+ base64.b64encode(content)  # lost data :(
        f2.write(base64.b64decode(base64.b64encode(content.replace('\x00', '[]'))).replace('[]', '\x00'))  # monkey patch :)
```

**Comment by metagn** [comment]
That's how `cstring` works. [Also how ffi.string works](https://cffi.readthedocs.io/en/latest/ref.html#ffi-string-ffi-unpack). Either use an array as a [buffer](https://cffi.readthedocs.io/en/latest/ref.html#ffi-string-ffi-unpack) or find a way to attach lengths. In Nim, a `cstring` with a specific length can be converted to an `openarray` by doing `s.toOpenArray(0, len - 1)`.

No idea why linux works.

**Comment by hlizard** [comment]
Thank you for your advice. According to your suggestion, I have changed the program right now. But why the previous error program can execute normally under Linux is still an interesting question. Isn't the end tag of C string under Linux '\0'? I will try to verify it.

**Comment by metagn** [comment]
If `strlen` is being used I believe the OS can map that to the length of the full allocation.
