### ISSUE TITLE
[Discussion / Future] Nim on GraalVM

### ISSUE THREAD

**Issue by rubyFeedback** [nim-lang/Nim#19423]
Hey Nim folks,

I filed this under issues mostly because I don't like the github discussions. I think the issue tracker is sooo much better than the forum, but anyway. :P

I guess all of you or most of you know GraalVM. Since I am writing quite some java code as of late (but I am still a semi-noob), I ran graalvm, in particular native-image, and ... it worked on the first try! \o/ That's rare that something works for me on a first attempt. :)

Anyway. Languages that are available on GraalVM are, I believe, kotlin, ruby, python, javascript ... perhaps I forgot some more.

How about Nim?

The GraalVM team describes the first steps here https://www.graalvm.org/graalvm-as-a-platform/implement-language/ and I am sure they would be happy to help get Nim to work on GraalVM too. This may not be that necessary for Nim, since nim will work on other platforms anyway, but there is also the polyglot (polylanguage) aspect, which I think is kind of nice. Combine different languages and have it work.

I don't know how difficult it is to get other languages to work on GraalVM, but that's what this issue here is all about after all. :)

If people don't think this is useful or not a good suggestion please just feel free to close as-is. I recommend to not keep this issue open for longer than ~3 months anyway at max, to avoid populating the issue tracker (I'd wish there would be an auto-close functionality people who start an issue could activate the moment they suggest one; I am horrible at closing my own old issues ...)

**Comment by ghost** [comment]
Can't you just use Clang to get LLVM bitcode and then use something like https://www.graalvm.org/reference-manual/llvm/ ?

**Comment by Araq** [comment]
I've looked into GraalVM myself and it seems most useful, but with `nim --gc:orc` Nim uses no platform specific code anymore that would break the setup. All you have to do is to compile to LLVM bitcode and integrate it.
