### ISSUE TITLE
Regression: Block arguments no longer support optional parameters

### ISSUE THREAD

**Issue by possdog** [nim-lang/Nim#19428]
Support for optional parameters for templates with block arguments was added in Nim 1.6.0, but no longer works in Nim 1.6.2 or devel.

### Example
```nim
template foo(a = 3, b = 7, body: untyped) =
  echo a + b
  body

foo:
  echo "Test!"
```

### Current Output
```
/Users/reillymoore/Desktop/Code Scraps/162_regression/proof.nim(5, 1) Error: type mismatch: got <void>
but expected one of:
template foo(a = 3; b = 7; body: untyped)
  first type mismatch at position: 1
  required type for a: int
  but expression '
echo ["Test!"]' is of type: void

expression: foo do:
  echo ["Test!"]
```

### Expected Output
```
10
Test!
```

**Comment by ringabout** [comment]
It becomes an experimental feature, see https://github.com/nim-lang/Nim/pull/19204

```nim
{.experimental: "flexibleOptionalParams".}

template foo(a = 3, b = 7, body: untyped) =
  echo a + b
  body

foo:
  echo "Test!"
```
works

**Comment by possdog** [comment]
Why was a feature added and then quietly made into an experimental feature in a patch? Generally speaking, patches shouldn't be breaking code.

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/issues/19015 which breaks code means that feature is not mature enough for 1.6.x, so it becomes an experimental feature and needs more polish.

**Comment by Araq** [comment]
The new feature is breaking code and needs to be behind a switch. Just like other new features are.
