### ISSUE TITLE
Anonymous proc doesn't parse in implicit return context

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#19429]
When returning an anonymous proc, implicit return doesn't parse, apparently expecting the named proc syntax, while using the `return` statement works. In this example, `f()` and `g()` should be equivalent, but only `f()` compiles.

Other ways of explicitly creating an expression context for the parser similarly can be used to achieve this.

### Example
```nim
proc f(): auto =
  return proc() = discard
proc g(): auto =
  proc() = discard
```

### Current Output
`anonproc.nim(4, 7) Error: identifier expected, but got '('`

Tested with
```
Nim Compiler Version 1.2.16 [Linux: amd64]
Compiled at 2022-01-17
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: c6a9f27b3e36bae9aacec1bd6c37893fb98fd33f
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 2bd1aa186e09565b2103394bd281478fa1b10ef1
active boot switches: -d:release
```

### Expected Output
Successful compilation.

**Comment by metagn** [comment]
Same as #18714?

**Comment by tersec** [comment]
Oh, indeed.
