### ISSUE TITLE
Plan9 platform support

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#19469]
### Summary
Unix was deprecated by [Plan 9 from Bell Labs](https://en.wikipedia.org/wiki/Plan_9_from_Bell_Labs).
Unfortunately there are not many [languages available](http://fqa.9front.org/appendixl.html) for Plan9.

### Description
I've done quite a bit of the work already - https://github.com/ehmry/Nim/compare/master...ehmry:plan9

Programs crash at runtime during the first garbage collection run. I suspect this is an alignment problem. The Plan9 C compilers do not support the alignment extensions needed to implement `NIM_ALIGN` and `NIM_ALIGNOF`.

I don't have plans to continue working on this, but if anyone is interested I'm happy to guide them through what's already been done.

**Comment by rubyFeedback** [comment]
I liked the idea from Plan 9. Not sure if they ever worked that well (I am more of an oldschool Unix guy at heart; fanboi of Brian Kernighan here) but I like nice ideas.

**Comment by Araq** [comment]
Plan 9 takes Unix's wrong ideas to the next level. Who needs APIs when you can open/write/read/close files of unspecified structure instead? Everybody. APIs are superior and don't introduce as many security bugs.

**Comment by ghost** [comment]
I agree that trees of obscure control files that read and consume arbitrarily formated text is not practical, but I do like the C APIs.
