### ISSUE TITLE
`parseEnum` causes `Invalid Tuple Syntax` on Enum if enum has values assigned through `const` variables

### ISSUE THREAD

**Issue by PhilippMDoerner** [nim-lang/Nim#19463]
When calling parseEnum with an enum whose members have values that are assigned through variables, it causes an `Invalid Tuple Syntax` Error. Without the `parseEnum` call, no Error occurs and the tuple can be used as normal. When using the same enum, but with values directly assigned to it, it causes no Error.

### Example
```nim
import strutils

const CAMPAIGN_TABLE* = "wikientries_campaign"
const CHARACTER_TABLE* = "wikientries_character"

type Tables = enum
  a = CAMPAIGN_TABLE,
  b = CHARACTER_TABLE,

let myA = CAMPAIGN_TABLE
echo parseEnum[Tables](myA)
```

### Current Output
> please check whether the problem still exists in git head before posting,
> see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).

I was unable to do so. There is no 'rebuilding-the-compiler' section on the "intern.html" page. I assume `Bootstrapping the compiler` might be the section that is meant, but it speaks of some `koch` file that I do not have (I think?).

Output below is from https://play.nim-lang.org/#ix=3NNb
```nim
/playground/nim/lib/std/enumutils.nim(52, 18) genEnumCaseStmt
/usercode/in.nim(12, 15) template/generic instantiation of `parseEnum` from here
/playground/nim/lib/pure/strutils.nim(1236, 18) template/generic instantiation of `genEnumCaseStmt` from here
/usercode/in.nim(8, 7) Error: Invalid tuple syntax!
```

### Expected Output
```
wikientries_campaign
```

### Additional Information
This error is solely caused by parseEnum and by the fact that the value assignment in the enum is through `const` variables.
The below for example works flawlessly:

```nim
import strutils

const CAMPAIGN_TABLE* = "wikientries_campaign"
const CHARACTER_TABLE* = "wikientries_character"

type Tables = enum
  a = "wikientries_campaign",
  b = "wikientries_character",

let myA = CAMPAIGN_TABLE
echo parseEnum[Tables](myA)
```

Nim version
```
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9084d9bc02bcd983b81a4c76a05f27b9ce2707dd
active boot switches: -d:release
```

**Comment by ringabout** [comment]
update: see https://github.com/nim-lang/Nim/pull/19466

**Comment by ringabout** [comment]
> I was unable to do so. There is no 'rebuilding-the-compiler' section on the "intern.html" page. I assume Bootstrapping the compiler might be the section that is meant

Nice catch! It is correct now: https://nim-lang.github.io/Nim/intern.html#bootstrapping-the-compiler

> but it speaks of some koch file that I do not have (I think?).

First, you need to clone this repo and switch to the path of your repo. Then you can find `koch.nim` there. Finally, you need to `nim c -r koch.nim` to obtain koch executable.

**Comment by PhilippMDoerner** [comment]
> update: see #19466

Holy dang that was fast. Thanks for the quick fix ! Excited to see this in the next nim version!

> First, you need to clone this repo and switch to the path of your repo. Then you can find koch.nim there. Finally, you need to nim c -r koch.nim to obtain koch executable.

Ahhhh alrighty, thanks! I'll keep it in mind!

**Comment by PhilippMDoerner** [comment]
As a sidenote, I just noticed another variant of parseEnum that fails with `Invalid Tuple Syntax`, though I think chances are that one is also fixed by your PR @xflywind :

https://play.nim-lang.org/#ix=3OyV
```nim
import norm/model
import std/[typetraits, strutils]

type AModel = ref object of Model
  name: string

type BModel = ref object of Model
  otherName: string


type AllModels = enum
  amA = name(AModel)
  amB = name(BModel)

let modelEnumVar: AllModels = parseEnum[AllModels]("AModel")
```

**Comment by ringabout** [comment]
> As a sidenote, I just noticed another variant of parseEnum that fails with Invalid Tuple Syntax, though I think chances are that one is also fixed by your PR

Yeah, It indeed works. I confirmed.
