### ISSUE TITLE
Calling proper proc requires explicit cast

### ISSUE THREAD

**Issue by dev-pts** [nim-lang/Nim#19470]
Having a simple object hierarchy, to call custom proc, which handles custom object types, it is required to do an explicit cast to parent type.

### Example
```nim
type
  A = ref object of RootObj
    name: string
  B = ref object of A

proc `==`(a: A, b: A): A =
  A(name: a.name & " == " & b.name)

let
  a = A(name: "a")
  b = B(name: "b")
  c = B(name: "c")
echo (a == b).name # First echo: OK
echo (A(b) == c).name # Second echo: OK
echo (b == c).name # Third echo: ERROR
```

### Current Output
```
/usercode/in.nim(15, 14) Error: undeclared field: 'name' for type system.bool [type declared in /playground/nim/lib/system/basic_types.nim(15, 3)]
```

Third echo causes error because custom proc `==` is not called. Instead, system proc `==` is called which returns bool.
As you can see, the first echo and the second one does not require an explicit cast - custom proc is called just fine.

### Expected Output
```
a == b
b == c
b == c
```

### Additional Information
https://play.nim-lang.org/#ix=3NTB with "Latest" version.

The same example in C++ works fine:
```c++
#include <string>
#include <iostream>

struct A {
	std::string name;

	A(std::string name) : name(name) {}

	A operator==(A& b) {
		return A(this->name + " == " + b.name);
	}
};

struct B: A {
	B(std::string name) : A(name) {}
};

int main()
{
	A a("a");
	B b("b"), c("c");

	std::cout << (a == b).name << std::endl;
	std::cout << (b == c).name << std::endl;

	return 0;
}
```

**Comment by beef331** [comment]
In this case Nim is searching for the first to be `A` to know that it's supposed to call this `==` since Nim does not do return type inference. So without passing an `A` it calls the `==: bool`. 

A possible solution is as follows: 
```nim
type
  A = ref object of RootObj
    name: string
  B = ref object of A

proc `==`[T: A, Y: A](a: T, b: Y): A =
  A(name: a.name & " == " & b.name)

let
  a = A(name: "a")
  b = B(name: "b")
  c = B(name: "c")
echo (a == b).name
echo (A(b) == c).name
echo (b == c).name
```

**Comment by dev-pts** [comment]
@beef331 Thank you! But let me think of this a little bit. It makes sense from the one side, but from another - my project still don't work with this fix. Moreover, it generates an error like:
```
required type for b`gensym13: T: Node
but expression `full` is of type: Node
```
which confused me even more than before...

**Comment by dev-pts** [comment]
Oh wow. It is essential to have two generic types `[T: A, Y: A](a: T, b: Y)` and not just one`[T: A](a: T, b: T)`. Okay, I think it's solved.

**Comment by beef331** [comment]
Indeed with two it's bound to the types provided with only one it's bound to the same type and if they do not match a mismatch will occur.
