### ISSUE TITLE
[Blog / News] Nim in the first ~3/4 months of 2022

### ISSUE THREAD

**Issue by rubyFeedback** [nim-lang/Nim#19476]
Hey Nimsters,

You lot have a blog here:

https://nim-lang.org/blog.html

However had, it is a bit sparse. Well, not necessarily sparse, but it focuses on some aspects
only. Like ~2 entries on the survey, which is fine, but imagine if the blog entries are a bit more
varied. (I know I know, may depend on getting people to report stuff and people are lazy,
I understand that ... out with the whip and whip them into working frenzy!)

Andreas sometimes does videos (I think; was it on youtube? I think I saw it somewhere), but
time is often limited and watching videos takes quite some time. That's why written text is
IMO best - we can get a lot of news quite quickly. Perhaps not as detailed as via video, 
but if you are time constrained then I think a blog is great.

So, what does this have to do with the nim blog?

Well - I am curious what is going on in the nim world. And yes, the nim-blog has almost
biweekly updates, I get that too. But the thing is ...

If I am just reading the blog, do I really know what the ~major things are being worked on
in, say, a time frame of 3-4 months? 

For instance, we have one update here:

https://nim-lang.org/blog/2021/11/02/this-month-with-nim.html

This is actually very good. This should become a series. :D

Like, every 3-4 months or so, something like that. I am not saying Andreas has to do that;
this can be community-run as update, people can just chime in and comment and then
just cherry-pick "randomly" which project may seem interesting - like on that blog entry.

However had, I don't necessarily mean this to be SOLELY confined to user contributions.
I also specifically mean to include what the "big things" are that the nim core dev team
tackles. The time frame of 3-4 months is picked arbitrarily so, just to focus on something
that is not too long, and not too short - evidently in 2 weeks such blog entries would be
quite shortish, so 3-4 months seems more viable.

Anyway, I hope I was able to explain why I created this issue request, so please feel
free to close it (or at the latest close it at the end of march 2022, whenever the next
blog update happens). Nim on! \o/

**Comment by ghost** [comment]
This month with Nim (TMWN) is already a recurring project, there are just no new posts of TMWN because there's not enough projects submitted to it. If you actually check the blog history you'll see a lot of TMWN posts

**Comment by beef331** [comment]
Yea I'm the numpty that runs TMWN so... uhhh get people to submit their projects monthly, and you'll get monthly postings :smile:

**Comment by ringabout** [comment]
> Anyway, I hope I was able to explain why I created this issue request, so please feel
free to close it (or at the latest close it at the end of march 2022, whenever the next
blog update happens). Nim on! \o/

see https://nim-lang.org/blog/2022/02/01/this-month-with-nim.html
