### ISSUE TITLE
Compiletime code evaluation failing on code path it shouldn't be running

### ISSUE THREAD

**Issue by guzba** [nim-lang/Nim#19492]
Code appears to be getting evaluated at compile time and failing where it should not fail. I don't know the exact right words to describe what is happening so I have produced some minimal examples.

Minimal example:

```nim
template find*(s: string, body: untyped) =
  if s.len == 0 or s[0] != '/':
    raise newException(ValueError, "Raise")
  body

find "":
  echo "HERE"
```
`Error: index out of bounds, the container is empty""[0]`

A more defensive version still failing with index out of bounds:

```nim
template find*(s: string, body: untyped) =
  if s.len == 0:
    raise newException(ValueError, "Raise")
  elif s == "":
    raise newException(ValueError, "Raise")
  else:
    assert s.len > 0
    if s[0] != '/':
      raise newException(ValueError, "Raise")
  body

find "":
  echo "HERE"
```

If I force this code to be executed at runtime, it works as expected (raises ValueError, not failing at index out of bounds):

```nim
proc find*(s: string) =
  if s.len == 0 or s[0] != '/':
    raise newException(ValueError, "Raise")

find ""
```

I tried this on https://play.nim-lang.org/ and the issue reproduces.

```
Nim Compiler Version 1.6.2 [Windows: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by beef331** [comment]
Remember that templates replace all instances of `s` with `""` which means the code is just:
```nim
if "".len == 0 or ""[0] != '/':
    raise newException(ValueError, "Raise")
```
As that is `""[0]` it's evaluated at compile time, which means it's a compile time error. Cache your `s` to a runtime variable if you do not want this. This is ideal behaviour IMO and a non-issue.
```nim
template find*(sOrig: string, body: untyped) =
  var s = sOrig
  if s.len == 0 or s[0] != '/':
    raise newException(ValueError, "Raise")
  body

find "":
  echo "HERE"
```

**Comment by guzba** [comment]
Even after it is replaced with `if "".len == 0 or ""[0] != '/':`, it still does not make sense to me that anything after the first true condition would be evaluated. `"".len == 0` is true, so why does it even evaluate a no-op additional `or` condition? This seems unnecessarily contrary to normal code evaluation.

Closing since it's not worth distracting if this is desired behavior.

**Comment by guzba** [comment]
A concrete example of what I am saying:

```nim
template find*(s: string, body: untyped) =
  if true or s[0] != '/':
    raise newException(ValueError, "Raise")
  body

find "":
  echo "HERE"
```
`Error: index out of bounds, the container is empty""[0]`

**Comment by beef331** [comment]
Nim evaluates all static expressions it can statically, which is why it does the right hand of an `or`. It does not have a check for if any of the other conditions are met, so perhaps there is an issue here, just not the one you intended.

**Comment by guzba** [comment]
@beef331 Thanks for your input here,

I am now uncertain if [this](https://github.com/nim-lang/Nim/issues/19492#issuecomment-1030679343) is a bug or correct behavior. To me, it looks like a bug but perhaps there is another aspect to this I am not thinking of that the compiler needs to think about?

I am used to conditions in an if short-circuiting (not evaluating further conditions once it is clear to succeed or fail). It appears Nim's evaluation of static expressions breaks that expectation. This appears to make certain things impossible to represent without avoiding all the static evaluation as suggested earlier.

In your opinion am I just kind of wrong in my expectations and should learn from this or is this a bug but perhaps not a priority?

**Comment by beef331** [comment]
Well the compiler does not know that `true or ""[0] != '\'` is short circuited it blindly evaluates the expressions statically. So I'd say there is an issue of "Static evaluation does not short circuit". The bug here is simply Nim not knowing that it does not need to further evaluating chained boolean ops, if a previous condition makes it true or false(depending on context). To get around this I can only really think about:

```nim
template find*(str: string | static string, body: untyped) =
  when str is static string:
    var s = str
    if s.len == 0 or s[0] != '/':
      raise newException(ValueError, "Raise")
  else:
    if str.len == 0 or str[0] != '/':
      raise newException(ValueError, "Raise")
    
  body
var a = ""
find a:
  echo "Here"
find "":
  echo "HERE"  
  ```
