### ISSUE TITLE
`strutils.find` uses cstring optimization that stops after \0

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#19500]
### Example
```nim
import strutils

echo "abc \0 def".find("def")
```

### Current Output
```
-1
```

### Expected Output
```
6
```

### Possible Solution

* Remove [this cstring optimization in strutils.find](https://github.com/nim-lang/Nim/blob/6b302bb71b6d9aab708b91f8d68957652ec30480/lib/pure/strutils.nim#L1875-L1880) and maybe move it as an overload to `cstrutils`.

### Additional Information

* From forum thread https://forum.nim-lang.org/t/8874

```
$ nim -v
Nim Compiler Version 1.6.2
```

**Comment by ringabout** [comment]
With Nim 1.4.8, it prints 6

Related: https://github.com/nim-lang/Nim/pull/17672

**Comment by Menduist** [comment]
Also hit this regression

**Comment by ringabout** [comment]
Rebased my PR => https://github.com/nim-lang/Nim/pull/19714

**Comment by ringabout** [comment]
I bump the priority because people keep encountering this problem (on Discord also) It causes rfind and find have different behaviours.

**Comment by auxym** [comment]
Also got hit by this, looking forward to #19714 getting merged.
