### ISSUE TITLE
The unicode $ (runes to string) procedure allows surrogates and code points over 0x10FFFF.

### ISSUE THREAD

**Issue by flenniken** [nim-lang/Nim#19526]
The unicode $ (runes to string) procedure allows surrogates and code points over 0x10FFFF. 

I expect it to throw an exception or return an error since the string returned is invalid UTF-8. 

* U+D800 to U+DBFF -- high surrogates
* U+DC00 to U+DFFF -- low surrogates

Surrogate test:

~~~
    if $(@[Rune(0xD800)]) == "\uD800":
      echo "$ allows surrogates"
~~~

 Rune too big:

~~~
echo $(@[Rune(0x110000)])
~~~
See https://github.com/flenniken/utf8tests for more information.

**Comment by Araq** [comment]
To validate unicode, use `validateUtf8`. A dollar operator should not validate.
