### ISSUE TITLE
Segmentation fault with custom `=copy` on `refc` GC

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#19523]
### Example
```nim
type String = object
  field: string

proc `=copy`(dest: var String, src: String) =
  `=copy`(dest.field, src.field)

func test(str: String) =
  var str = str
  str.field[0] = 'a'

test(String(field: "hello"))
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
No segmentation fault.

### Additional Information
This only happens with the `refc` GC (not with ARC/ORC).
I know that that's probably not how I'm supposed to use `=copy`, but that shouldn't cause a segfault regardless.
```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-27
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 4b723c0f5350c5bfb9722dace7a40c66a4630a68
active boot switches: -d:release
```

**Comment by ringabout** [comment]
`=copy` should not be used with seqs/strings in refc.

**Comment by konsumlamm** [comment]
> `=copy` should not be used with seqs/strings in refc.

Can't we just forbid that then? "Just don't do things that can cause segfaults" seems like a weird advice.

**Comment by ringabout** [comment]
That has been covered by https://github.com/nim-lang/Nim/issues/20846

**Comment by Araq** [comment]
> "Just don't do things that can cause segfaults" seems like a weird advice.

Likewise is weird advice: "just make the compiler as complex as required in order to catch every possible oversight by the people who hack custom =hooks on a runtime that wasn't built for it":

**Comment by konsumlamm** [comment]
> > "Just don't do things that can cause segfaults" seems like a weird advice.
> 
> Likewise is weird advice: "just make the compiler as complex as required in order to catch every possible oversight by the people who hack custom =hooks on a runtime that wasn't built for it":

Catching this doesn't seem hard (or am I missing something?), so I don't see a reason not to do it. I would like the compiler to tell me if I made a mistake somewhere (especially if it's an obvious one). Simply defining a (special) function shouldn't be considered a hack, it's not really obvious that the lifetime-tracking hooks don't work without ARC/ORC and might even segfault.
