### ISSUE TITLE
Parser tiny fault in an invocation 

### ISSUE THREAD

**Issue by abdulbadii** [nim-lang/Nim#19548]
Parser has invocation imperfection    
only when one line with if/elif

### Example

resticted to 
``` 
elif node( str, strMore ) :

```
only, cannot be else eg: 
``` 
elif node ( str, strMore ) :

elif node str, strMore :

```

### Current Output
```
Error :  type mismatch: got <(string, string)>
but expected one of: 
proc node(str: string;    
```
.... so on

### Expected Output

Go on running fine

### Possible Solution

Beyond my knowledge for now

### Additional Information
Has no idea/ knowledge for it
```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-06-07
```

**Comment by beef331** [comment]
Due to Nim's command syntax `elif node ( str, strMore ) :` is a command call that is equivlent to `node((str, strMore))` which is invalid for your procedure. This is not a bug just a common mistake.

**Comment by metagn** [comment]
See the last part here: https://nim-lang.org/docs/manual.html#syntax-precedence

Similarly `node str, strMore` syntax with multiple arguments is not supported in an expression. This is due to ambiguity with lists that use commas to separate items, such as `(a, b, c)`.
