### ISSUE TITLE
`fromJson` in `std/jsonutils` converting GCed string to `cstring` from a non-const location

### ISSUE THREAD

**Issue by dangbinghoo** [nim-lang/Nim#19566]
`fromJson` in `std/jsonutils` has a bug for deal with `cstring` type:

### fromJson proc code in std/jsonutils
```nim
proc fromJson*[T](a: var T, b: JsonNode, opt = Joptions()) =
  ## inplace version of `jsonTo`
  #[
  adding "json path" leading to `b` can be added in future work.
  ]#
  checkJson b != nil, $($T, b)
  when compiles(fromJsonHook(a, b)): fromJsonHook(a, b)
  elif T is bool: a = to(b,T)
  elif T is enum:
    case b.kind
    of JInt: a = T(b.getBiggestInt())
    of JString: a = parseEnum[T](b.getStr())
    else: checkJson false, $($T, " ", b)
  elif T is uint|uint64: a = T(to(b, uint64))
  elif T is Ordinal: a = cast[T](to(b, int))
  elif T is pointer: a = cast[pointer](to(b, int))
  elif T is distinct:
    when nimvm:
      # bug, potentially related to https://github.com/nim-lang/Nim/issues/12282
      a = T(jsonTo(b, distinctBase(T)))
    else:
      a.distinctBase.fromJson(b)
  elif T is string|SomeNumber: a = to(b,T)
  elif T is cstring:
    case b.kind
    of JNull: a = nil
    of JString: a = b.str
```
Hint warning message from VSCode :
```
implicit conversion to 'cstring' from a non-const location: b.str; this will become a compile time error in the future [CStringConv]
```

Code to produce the bug:

```nim
import std/[json,jsonutils]

type
  dev_info* {.bycopy.} = object
    name*: cstring

let jsnode = parseJson("""{"name": "LED"}""")
var a = jsnode.jsonTo(dev_info)

```
compile this code produces: 

/tmp/test.nim(8, 15) template/generic instantiation of `jsonTo` from here
/home/user/.choosenim/toolchains/nim-#devel/lib/std/jsonutils.nim(296, 11) template/generic instantiation of `fromJson` from here
/home/user/.choosenim/toolchains/nim-#devel/lib/std/jsonutils.nim(159, 17) template/generic instantiation of `fromJson` from here
/home/user/.choosenim/toolchains/nim-#devel/lib/std/jsonutils.nim(240, 22) Warning: implicit conversion to 'cstring' from a non-const location: b.str; this will become a compile time error in the future [CStringConv]

**Comment by ringabout** [comment]
This is correct. See https://github.com/nim-lang/Nim/pull/19705#issuecomment-1093601374
