### ISSUE TITLE
Add warning for bare `except:` clause

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#19580]
Bare `except:` clauses have more or less undefined behavior, due to changes between Nim versions and panic dialects that cause problems for libraries - in particular, it's difficult to write library code when the user switches panic on or off and get predictable behavior: in one mode, bugs are swallowed / hidden along with regular exceptions and in the other, there's a crash.
Over time, this contributes to poor library quality.

A better alternative with the present split in exception types is being explicit about `except Defect` and `except CatchableError`, this avoids any confusion - thus, introduce a new warning `BareExcept`, enabled by default, that triggers for:

* no exception given in `except`
* any exception deriving from `Exception` but _not_ `Defect` or `CatchableError`

~~A similar warning should be added for exception types that don't inherit from one of `Decect` or `CatchableError`~~ _already exists (`InheritFromException`)_

**Comment by ringabout** [comment]
Hello,  what do you think regarding handling foreign exception?

```nim
  try:
    if true:
      code
    wrong = true
  except Exception as e: discard
  except: raisedForeign()
```

Should we suppress the warnings for now?

**Comment by arnetheduck** [comment]
> Should we suppress the warnings for now?

I'm not sure, I'm not too familiar with the foreign exception support in nim, and how it cooperates with other features such as `goto` exception handling (if at all) - if the foreign exceptions are declared as such, `except {.foreign.}` for example could be a possibility to be explicit about that too.

**Comment by arnetheduck** [comment]
Basically, DWARF EH allows handling foreign exceptions at a cross-language level (this is something `nlvm` can implement, but "normal" `nimc` not) - then we have Nim's emulation mode with C++ which requires that C++-level try/catch are generated - then we have goto exceptions and panics to consider.

**Comment by planetis-m** [comment]
I use bare except clauses for performance reasons (you broke my space-bar heater!), checking the type involves a strcmp and its expensive. Please consider improving the performance of run-time type checking before making it the default.

**Comment by arnetheduck** [comment]
> I use bare except clauses for performance reasons

Have you measured that? I imagine a string comparison is nothing compared to the ordinary cost of raising an exception, which includes several round trips to the memory allocator, collecting a call stack and a number of other, rather heavy, operations .. in other words, you can't have good performance using excpetions, in general, if they actually happen, and are not, haha, exceptional.

**Comment by planetis-m** [comment]
I don't remember exactly, the benchmark's code is buried somewhere in the issues, but it's symbol did come up in the "Top Hotsposts" view in hotspot (with -d:release so no call stacks).

**Comment by ringabout** [comment]
> A similar warning should be added for exception types that don't inherit from one of Decect or CatchableError

There is already a warning for this one:

`Warning: inherit from a more precise exception type like ValueError, IOError or OSError. If these don't suit, inherit from CatchableError or Defect. [InheritFromException]`

It should be good enough.

**Comment by arnetheduck** [comment]
ping @xflywind what happened with your PR that implements this?

**Comment by ringabout** [comment]
I'm going to revisit it when I have some free time.

**Comment by arnetheduck** [comment]
@ringabout ping?

**Comment by ringabout** [comment]
@arnetheduck, progress https://github.com/nim-lang/Nim/pull/21099, feedback will be appreciated.
