### ISSUE TITLE
Force compiler generate declaration of a type

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#19585]
### Summary
Nim will not generate type declaration for which types it seen not used, that is good for compiling time, but sometimes we need a way to force compiler generate it.

### Description
For example, C compiler will reports `unknown type name 'X'` for the following code snippet
```nim
type
  X* {.exportc.} = object
    v: int

{.emit:"""
X x = { 1234 };
""".}
```

This works
```nim
type
  X* {.exportc.} = object
    v: int

discard X.sizeof

{.emit:"""
X x = { 1234 };
""".}
```

### Alternatives
According to nim manual, there is a `{.used.}` pragma, can we use it to inform compiler that we need it to generate type declaration? For example
```nim
type
  X* {.exportc, used.} = object
    v: int

{.emit:"""
X x = { 1234 };
""".}
```

**Comment by shirleyquirk** [comment]
The workaround I'm using is to create a dummy proc that returns that type.
```nim
proc dummy():X = discard
```

**Comment by metagn** [comment]
The example in the issue now works, `{.exportc.}` should always generate the types. Maybe the issue was related to the order they were defined.

**Comment by ringabout** [comment]
!nim c
```nim
type
  X* {.exportc.} = object
    v: int

{.emit: """
typedef struct X X;
struct X {
	NI v;
};""".}
{.emit:"""X x = { 1234 };""".}
```

**Comment by ringabout** [comment]
It seems to make a good test for https://github.com/nim-lang/Nim/pull/21648

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/Nim/issues/21645

**Comment by ringabout** [comment]
Later we should really implement https://stackoverflow.com/questions/15407075/how-could-i-use-git-bisect-to-find-the-first-good-commit in order to find the good commit
