### ISSUE TITLE
Cannot compile source code that contains `stdout` to JavaScript

### ISSUE THREAD

**Issue by bichanna** [nim-lang/Nim#19608]
Nim could not compile source code that contains `stdout` to JS even after importing `system`.

I used the command below.
```
$ nim js main.nim 
```

### Example
```nim
import system
stdout.write("some string")
```

### Current Output
```
/some/path/blah.nim(15, 5) Error: undeclared identifier: 'stdout'
```

### Expected Output
```
Compilation succeeded. # or something like that
```

**Comment by beef331** [comment]
`stdout` is a symbol that only exists for C/C++. What would it even represent with JS?

**Comment by bichanna** [comment]
Is there any workaround? I use it a lot in my code.
I don't want to switch to `echo`es.

**Comment by beef331** [comment]
Arent any good work arounds aside from putting `when not defined(js)` around it or :
```nim
when defined(js):
  type stdout* = distinct void
  proc write*(_: typedesc[stdout], msg: string) =
    var buffer {.global.} = ""
    buffer.add msg
    if buffer[^1] == '\n':
      echo buffer
      buffer.setLen 0
```

**Comment by Varriount** [comment]
As was said, this isn't really an issue - Javascript (in the browser) just doesn't have the concept of non-newline-delimited console streams.
