### ISSUE TITLE
nim doc crashes when processing comment with an asterisk

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#19607]
### Example
```nim
const
  PixelformatUncompressedGrayAlpha* = 2 ## 8*2 bpp (2 channels)
```

### Current Output
```
test.nim(3, 7) Error: '*' expected
lineinfos.nim(289)       raiseRecoverableError
Error: unhandled exception: '*' expected [ERecoverableError]
```

### Additional Information
Remove the asterisk in the comment to make it compile

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-03-09
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 6773ffa63d0b3ab8b8894e84ed417f4eaced9122
active boot switches: -d:release --gc:markAndSweep
```

**Comment by ringabout** [comment]
workaround:

use backtick to enclose the expression contains asterisk

```nim
const
  PixelformatUncompressedGrayAlpha* = 2 ## `8*2` bpp (2 channels)
```

I'm not sure whether it is intentional. It seems special characters need to be escaped:

Similarily

```nim
const
  PixelformatUncompressedGrayAlpha* = 2 ## `8*2 bpp (2 channels)
```

Single backtick doesn't work either.

**Comment by planetis-m** [comment]
Thanks for the workaround!

**Comment by ringabout** [comment]
It is a regression. It works in 1.4.x

**Comment by a-mr** [comment]
This is a side effect of our (incomplete) move from RST to Markdown.
Well, it's legal in both RST and Markdown, but by different reasons:
- in RST `*` would not start an emphasized text if no whitespace to the left of `*`
- in Markdown any `*` which was not finished by second `*` is considered literally

But currently we require closing `*` as if it were RST but the inline formatting rules are as if they are Markdown's.

Another workaround is to put spaces around `*` or add `\`:
```nim
## 8 * 2
## 8\*2
```
