### ISSUE TITLE
Using --exceptions:goto or --mm:arc fixes mystery segfault in default refc

### ISSUE THREAD

**Issue by guzba** [nim-lang/Nim#19623]
Treeform and I have run into some really strange segfaults lately on Windows locally and are confused about both how to report this and how to fix it but we are trying here.

What we do know is that using --mm:arc or --exceptions:goto fixes the segfaults, or including some seemingly random junk code also fixes things.

This is very strange so I have not been able to narrow it down to a functional tiny example but it is fortunately trivial to reproduce for us.

See https://github.com/guzba/zippy/blob/master/src/zippy/inflate.nim#L219. The if and doAssert false are nonsense, but if you comment them out and run `nim c -r -d:release tests/test.nim` on Windows, you will get a SIGSEGV. If you use `--exceptions:goto` or `--mm:arc` suddenly everything works even without the voodoo if.

Further, if you comment out or remove the `{.push checks: off.}`  and `{.pop.}` from the top and bottom of inflate.nim, things suddenly work too even with refc.

Works: https://github.com/guzba/zippy/commit/cdd577ef1aaf5396cf61a82139e95355b5d3a780
Does not work: https://github.com/guzba/zippy/commit/7a92ac2027c819fda773cfe8fde3a90ec836a28a
Works again: https://github.com/guzba/zippy/commit/5cc6e3b5377e968e7be9939b7c6e67738368cc54
Even this works: https://github.com/guzba/zippy/commit/0de1d2a0a159761347579931303d56168a36e316

Are we running into this issue with setjmp? https://github.com/nim-lang/Nim/pull/19197 and https://github.com/status-im/nimbus-eth2/issues/3121 or does this have a different possible explanation?

The fact that making 0 code changes and just using --exceptions:goto or --mm:arc fixes things leads us to believe this is something related to codegen but when we look at the generated C, nothing jumps out at us. I should also mention using --cc:vcc also makes things work.

Further, please note that this is not writing past the end or anything like that. We've tested and asserted and fuzzed all of this to  death. There may be bugs, but we have done our homework.

```
Nim Compiler Version 1.6.4 [Windows: amd64]
Compiled at 2022-02-09
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by stefantalpalaru** [comment]
> Are we running into this issue with setjmp?

Easy to check by passing "-d:nimRawSetjmp" on Windows, which [became the default](https://github.com/nim-lang/Nim/pull/19891) in the mean time.

**Comment by guzba** [comment]
Ah sure, thanks for the tip on how to check this.

We also found and fixed a different issue recently that may have been the culprit. I need to try to reproduce this issue again to see the state of things.

I'm going to close this issue since it is unfortunately pretty vague but will re-open if I am able to reproduce the issue and see a behavior change based on -d:nimRawSetjmp.
