### ISSUE TITLE
strutils.validIdentifier does not comply with the manual

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#19657]
What the manual says: https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords
What `validIdentifier` allows https://play.nim-lang.org/#ix=3TQ1:

**TEST**
```nim
import strutils
doAssert not validIdentifier("_foo")
doAssert not validIdentifier("_foo_")
doAssert not validIdentifier("_1foo_")
```

***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-03-23
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: a8b5ad845c4218b4f20595df097c593acee53d50
active boot switches: -d:release
```

**Comment by Wh1teDuke** [comment]
Correct algorithm:
```nim
  if str[0] notin {'A' .. 'Z', 'a' .. 'z', '\x80'..'\xff'}: return
  if str[^1] == '_': return

  for i in 1 .. high(str):
    if str[i] notin IdentChars: return
    if str[i] == '_' and str[i - 1] == '_': return

  return true
```
Edit: fixed

**Comment by juancarlospaco** [comment]
PR it?.

**Comment by Araq** [comment]
Nim doesn't allow for two underscores though so your algorithm is still wrong. ;-)

**Comment by ringabout** [comment]
The docs doesn't seem to imply it implements "isValidNimIdentifier"? It says "A valid identifier starts with a character of the set `IdentStartChars` and is followed by any number of characters of the set `IdentChars`."

**Comment by Araq** [comment]
The implementation does what the documentation says.
