### ISSUE TITLE
let ````1fo```` = 1 throws 'Error: invalid number suffix: 'fo''

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#19651]
**Test**
```nim
let `1fo` = 1
``` 
**Result**
```nim
Test.nim(1, 7) Error: invalid number suffix: 'fo'
```
Is this a bug in the parser?
***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-03-23
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: a8b5ad845c4218b4f20595df097c593acee53d50
active boot switches: -d:release
```

**Comment by Wh1teDuke** [comment]
I give up

**Comment by beef331** [comment]
Seems it's an issue of "accquoted identifiers starting with numbers followed by letters are considered numeric literals". Parser hits the number then tries to parse a number literal.

**Comment by Araq** [comment]
The parser does what the spec says and the spec says https://nim-lang.org/docs/manual.html#lexical-analysis-other-tokens
A single backtick is a single token, not a string literal.
