### ISSUE TITLE
Broken behavior with string ranges in case labels

### ISSUE THREAD

**Issue by nocturn9x** [nim-lang/Nim#19678]
Using ranges like `"0" .. "9"` inside case labels is completely borked and sometimes even crashes the C code generator.

### Example
```nim
case "5":
    of "0" .. "9":
        echo "Hello!"  # Does not run
    else:
        discard

echo "5" in "0" .. "9"  # This does and correctly prints "true"
```

### Current Output

```
true
```

### Expected Output
```
Hello!
true
```

### Possible Solution

Minimal investigation by @Yardanico suggests this may be due to how the compiler handles string ranges in case labels, which apparently does not use the regular `..` operator. No solution is immediately obvious other than, well, fixing string ranges?

### Additional Information
The issue originally arised as a C codegen crash with the following error message: 
```
Error: unhandled exception: ccgstmts.nim(836, 11) `b[i].kind != nkRange  [AssertionDefect]`
```
```
$ nim -v
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9084d9bc02bcd983b81a4c76a05f27b9ce2707dd
active boot switches: -d:release
```

**Comment by Araq** [comment]
This simply shouldn't compile.

**Comment by nocturn9x** [comment]
The case statement or the echo? or both? Anyway it's still a bug :P

**Comment by Araq** [comment]
The "range of string" construct.

**Comment by nocturn9x** [comment]
I see! I actually kinda expected it not to work, but I would've expected an error along the lines of "expecting an integral type". This is pretty minor anyway, just thought reporting it so it doesn't get lost. Thanks for what you did and still for the Nim community! :D
