### ISSUE TITLE
Using case expression on object result in weird error message

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#19682]
### Example
In this example, the type of X in `case X` is apparent. However, if the X is a complex expression, the error message isn't clear that it is programmer's fault.
```nim
type A = object

case A()
else:
    discard
```

### Current Output
```
test.nim(3, 1) Error: attempting to call undeclared routine: 'case'
```

### Expected Output
A better error message.

### Additional Information

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-04-05
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: fa12c59ff0e59e85cf5105bc276d6b151e07c1fa
active boot switches: -d:release
```

**Comment by Araq** [comment]
This is caused by the support for case statement macros.
