### ISSUE TITLE
StringStream created from string segfaults on write when when using arc

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#19707]
Pretty self-explanatory, when you do what's shown in the example below it will segfault at runtime when using arc/orc. @beef331 thinks it may have something to do with the sink parameter here https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/streams.nim#L1255

### Example
```nim
import std/streams
var s = newStringStream("Hello World!")
s.write("h")
```

**Comment by ghost** [comment]
Looks like it's because `streams` does `copyMem` into the string buffer, and it doesn't call `prepareMutation` beforehand.

I guess the correct fix would be to add `prepareMutation` to `newStringStream` (thanks beef) in `std/streams` where `copyMem` into the buffer occurs?
