### ISSUE TITLE
Bad float64 typeKind of object field in 64-bit env

### ISSUE THREAD

**Issue by amnr** [nim-lang/Nim#19710]
There's currently no way to differentiate between implementation defined `float` and fixed-width `float64`. Tested on 64-bit Linux.

### Example
```nim
import macros

type
  Obj = object
    a: float
    b: float32
    c: float64

macro iterfields*(t: typed) =
  for row in t.getTypeImpl[2].children:
    echo row[1].typeKind

var o: Obj

o.iterfields
```

### Current Output

```
$ nim r --verbosity=0 testcase.nim
ntyFloat
ntyFloat32
ntyFloat
```

### Expected Output
```
$ nim r --verbosity=0 testcase.nim
ntyFloat
ntyFloat32
ntyFloat64
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.6.4 [Linux: amd64]
Compiled at 2022-02-10
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

$ uname -a
Linux karnak 5.16.0-6-rt-amd64 #1 SMP PREEMPT_RT Debian 5.16.18-1 (2022-03-29) x86_64 GNU/Linux
```

**Comment by beef331** [comment]
`float` is `float64`.
> the generic floating-point type; its size used to be platform-dependent, but now it is always mapped to float64. This type should be used in general.

https://nim-lang.org/docs/manual.html#types-preminusdefined-floatingminuspoint-types

**Comment by Araq** [comment]
Yeah, it works as designed. There is no platform specific "float" type, it's always 64 bits.
