### ISSUE TITLE
StringStream in static context (arc) now broken after recent write fix

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#19716]
Recent fix meaning #19708

It now seemingly attempts to use prepareMutation in the VM (when using arc/orc)  which gives the error `Error: opcCastIntToPtr: regs[rb].kind: rkNodeAddr`,   from here https://github.com/nim-lang/Nim/blob/devel/lib/system/strs_v2.nim#L177

This code was valid before and is still valid when using refc.

### Example:
```nim
import streams
static:
  let s = newStringStream("a")
  echo s.data # only added for illustrative purposes, breaks before this point
```

**Comment by ghost** [comment]
Reopening as #19717 didn't fix it
