### ISSUE TITLE
`newSeqUninitialized` over-constrained, `setLenUninitialized` missing

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#19727]
`newSeqUninitialized` allows creating `seq`:s that are not initialized, for use as general-purpose buffers.

It is however constrained to `SomeNumber`, which is unnecessarily restrictive: any type composed only of "trivial" types qualifies for this kind of treatment, similar to how `copyMem` is constrained to types that `supportsCopyMem`.

The above functionality is needed to create efficient serializers that preallocate memory then fill it with data from a source (disk/network/etc).

Growing a sequence uninitialized is needed likewise to reuse memory buffers in the above serializers - they do not have access to the capacity of the seq, so there is no way to write an optimal deserializer that reuses the existing capacity of a `seq`.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/22739 and https://github.com/nim-lang/Nim/pull/22767
