### ISSUE TITLE
[ARC] Sink inference prevents the usage of stdlib procedures for functional style

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#19724]
Any stdlib procedure that gets sink inference applied to it can't be used as an argument to procedures like `map` or similar.

### Example
```nim
import std/[os, sequtils]

proc main = 
  let saves = @["/path/to/file.txt"].map(extractFilename)
  echo saves

main()
```

Found in https://github.com/WonkySpecs/rolldice

### Current Output
```
/home/dian/Projects/ficsraper/tast.nim(4, 37) Error: type mismatch: got <seq[string], proc (path: sink string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
  first type mismatch at position: 2
  required type for op: proc (x: T): S{.closure.}
  but expression 'extractFilename' is of type: proc (path: sink string): string{.noSideEffect, gcsafe, locks: 0.}

expression: map(@["/path/to/file.txt"], extractFilename)
```

### Expected Output
Successful compilation and `@["file.txt"]`

### Additional Information
`--sinkInference:off` doesn't seem to work, I assume this is because sink inference is explicitly enabled for stdlib so a user flag can't override it.

### Workaround
In this specific case you can workaround it by using `mapIt`, but I assume there might be cases where it's harder to do.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-04-14
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: dc4cc2dca53e3772efb3654a4ddbbe8350d1db43
active boot switches: -d:release
```

**Comment by Araq** [comment]
Why is `extractFilename` inferred to use a sink parameter anyway?

**Comment by metagn** [comment]
Sink inference is correct IMO, `extractFilename` calls `splitPath(path: string)` which has a `if` branch:

```nim
result.head = ""
result.tail = path
```

Unless it's desired that for a parameter to be sink, all branches must infer sink for that parameter. Currently it just processes each branch sequentially.

`map` doesn't work because `(proc (x: sink string): string) isnot (proc (x: string): string)` and vice versa despite `string is (sink string)`.

**Comment by Araq** [comment]
But sink inference should not judge about probabilities. Maybe the `if` is rarely executed and then inferring the parameter as `sink` is a pessimization.
