### ISSUE TITLE
SIGSEGV when parsing type `proc (val: untyped): void` in tuple type

### ISSUE THREAD

**Issue by morganholly** [nim-lang/Nim#19725]
prints `SIGSEGV: Illegal storage access. (Attempt to read from nil?)` after unused import warnings. may also apply to other procedural types containing `untyped`. i was intending to use it for a template and wanted to enforce some type constraints when i happened on this error. `foo = tuple[bar: proc (val: untyped): void]` is enough to cause it.

nim version 1.6.4 [MacOSX: amd64], macos 10.15.7 (19H1715)

**Comment by bung87** [comment]
can't reproduce, now a `Error: 'untyped' is only allowed in templates and macros or magic procs`, should close I think

**Comment by ringabout** [comment]
Can you reproduce it with version 1.6.4?

**Comment by bung87** [comment]
it reproduced at v1.6.8
