### ISSUE TITLE
`import` can't handle second statement under specific (but in theory valid) circunstances

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#19731]
**Test**
```nim
# Compiles
import strutils, sequtils as sq
import strutils except find, sequtils
# Error
import strutils except find, sequtils as sq
```
**Error**
```nim
Test.nim(1, 45) Error: identifier expected, but found 'sequtils as sq'
```
***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-04-12
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 26bcf18f918b2bcc7b6b2e230ae74d7726dca6d0
active boot switches: -d:release
```

**Comment by metagn** [comment]
It parses as `import strutils except (find, sequtils)` not `import (strutils except find), sequtils`. The compiler just ignores that `sequtils` is not a symbol in strutils.

**Comment by Wh1teDuke** [comment]
> It parses as `import strutils except (find, sequtils)` not `import (strutils except find), sequtils`. The compiler just ignores that `sequtils` is not a symbol in strutils.

You are right, apparently the except accepts invalid idents for backwards compatibility. Was fooled by that.
