### ISSUE TITLE
Documentation generator builds index in current working directory

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1976]
If you go to your nim checkout and type:

``` sh
$ nim doc --index:on lib/pure/os.nim
```

you will get a file named `os.idx` rather than `lib/pure/os.idx`. Bug or feature? I'd argue this is a bug, because the paths to the html file contained in the index file are relative to the source code and thus creating an index page from it will generate broken links.

**Comment by BlaXpirit** [comment]
doc2 generates everything in the current directory and I like that.

**Comment by gradha** [comment]
Running ``nim doc2 --index:on lib/pure/os.nim`` produces the same result, the index file in the current directory, the html file in ``lib/pure/os.html``.

**Comment by andreaferretti** [comment]
With latest devel, the .idx file is created under `htmldocs`

**Comment by andreaferretti** [comment]
Sorry, it is actually under `lib/pure/htmldocs`. I believe the bug is fixed in devel

**Comment by narimiran** [comment]
> Sorry, it is actually under `lib/pure/htmldocs`.

I've checked and this is the behaviour in both stable v0.19 and the latest devel.

> I believe the bug is fixed in devel

Can this be closed then?

**Comment by andreaferretti** [comment]
Yes, I was just waiting for someone to confirm
