### ISSUE TITLE
ARC has different `setLen` behaviour compared to refc

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#19763]
Posting from https://github.com/nim-lang/Nim/issues/19728. When shrinking some sequence/string and then growing it back to the old length with `setLen`, the resulting contents of the sequence/string differ under ARC/ORC and refc

### Example
```nim
proc main1 = 
  var my = @[1, 2, 3, 4, 5]
  my.setLen(0)
  my.setLen(5)
  echo my

proc main2 = 
  var my = "hello"
  my.setLen(0)
  my.setLen(5)
  echo @my

main1()
main2()
```

### Current Output
With `refc`
```
@[0, 0, 0, 0, 0]
@['\x00', 'e', 'l', 'l', 'o']
```

With `arc`:
```
@[1, 2, 3, 4, 5]
@['\x00', '\x00', '\x00', '\x00', '\x00']
```

### Expected behaviour
Not sure, if refc or ARC is the more correct one here since `setLen` doesn't clearly explain what happens in case of shrinking + growing the data. Is it supposed to be an internal detail?

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 278ecad973c6581aeea0a6ff9372109b0dd6df5e
active boot switches: -d:release
```

**Comment by metagn** [comment]
Would it make sense to have `setLen` zero the memory and add a `setLenUninitialized` that keeps the memory as is?

**Comment by Araq** [comment]
Both implementations seem to be wrong according to the newer semantics. The supposed semantics are now (and previously it was underspecified):

`setLen` is either:

- A nop if the new length == old length.
- A "shrink" that frees the entries if the new length < the old length.
- A "grow" that sets the new entries to `default(ElemType)` if the new length > old length.
