### ISSUE TITLE
Compiler crashes when defining recursive type

### ISSUE THREAD

**Issue by oakes** [nim-lang/Nim#19779]
### Example
```nim
type
  ThingProc = proc (t: Thing)
  Thing = seq[ThingProc]
```

### Current Output
```
Execution failed with exit code 35584
```

Interestingly, if I define them together like `type Thing = seq[proc (t: Thing)]` it also fails, but it includes this error:

```
fatal.nim(53)            sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

I don't know if this kind of recursive type is allowed by the language, but it should at least produce a understandable error message.

### Expected Output
Successful compilation.

### Additional Information

```
$ nim -v
Nim Compiler Version 1.6.6 [MacOSX: amd64]
Compiled at 2022-05-08
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by oakes** [comment]
Oh, this is a dupe of https://github.com/nim-lang/Nim/issues/19271

**Comment by beef331** [comment]
> I don't know if this kind of recursive type is allowed by the language

It's completely impossible to represent as there is no concrete definition. Just an issue with how Nim reasons aliases and cannot cull the recursive types.

**Comment by oakes** [comment]
How is it impossible to represent? The compiler has no problem with this:

```nim
type
  ThingProc = proc (t: Thing)
  Thing = object
    things: seq[ThingProc]
```

So wrapping the seq in an object makes it work, but the seq on its own crashes the compiler.

**Comment by beef331** [comment]
> So wrapping the seq in an object makes it work, but the seq on its own crashes the compiler.

Yes cause the seq inside an object references the object not an alias. To showcase how this is not capable to be instantiated I'll walk through the way something is instantiated. Consider `var a: Thing` we need to instantiate `Thing` so that's where we'll start.

```
Thing is an alias to seq[ThingProc]
ThingProc is an alias to proc(t: Thing)
We look up Thing it is an alias to seq[ThingProc], so we look up ThingProc.
ThingProc is an alias to proc(t: Thing)
....
```
As this shows there are no concrete types, Now looking at the second example, with the same `var a: Thing`
```
Thing is a concrete definition that has a field of type ThingProc.
ThingProc is an alias to proc(t: Thing)
We look up Thing, it is a object definition, we stop here.
```

If this still does not make sense consider the following
```nim
type
  B = A
  A = object
```
Versus
```nim
type
  B = A
  A = B
```

**Comment by oakes** [comment]
Interesting, thank you for the explanation. It would still be ideal to have an error message, but since that is already covered by #19271 i'll close.
