### ISSUE TITLE
--panics:on fails to catch

### ISSUE THREAD

**Issue by Zectbumo** [nim-lang/Nim#19777]
The documentation says "--panics:on Defects become unrecoverable errors."
I have to guarantee no exceptions slip through and it seems RangeDefects slip through checks.

compile this example with --panics:on
### Example
```nim
type Month = 1..12

var a: Month

proc p() {.raises: [].} =
  for i in 1..13:
    a = i
    echo a

p()
```

### Current Output
```
Error: unhandled exception: value out of range: 13 notin 1 .. 12 [RangeDefect]
```

### Expected Output
```
Error: ... can raise unlisted exception RangeDefect
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-05-07
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 0455d24d555e4f83537af535c0b2e44291d1fe97
active boot switches: -d:release
```

**Comment by SolitudeSF** [comment]
Defects are not tracked by `raises`.

**Comment by Zectbumo** [comment]
> Defects are not tracked by `raises`.

raises may be a distraction in my example here but basically I am trying to say I cannot accept anything thrown. No raises and panics on. Yet I wasn't warned of a possibility of a RangeDefect

**Comment by planetis-m** [comment]
So the issue is .raises doesn't warn about the possibility of a RangeDefect.

**Comment by ee7** [comment]
@Zectbumo Have you seen that the manual [contains](https://github.com/nim-lang/Nim/blob/2c73e84436a11cae1676c7da0228158ba1a885cc/doc/manual.rst#exception-tracking) the below?

> Exceptions inheriting from `system.Defect` are not tracked with the `.raises: []` exception tracking mechanism. This is more consistent with the built-in operations. The following code is valid:
>
> ```Nim
> proc mydiv(a, b): int {.raises: [].} =
>   a div b # can raise an DivByZeroDefect
> ```
>
> And so is:
>
> ```Nim
> proc mydiv(a, b): int {.raises: [].} =
>   if b == 0: raise newException(DivByZeroDefect, "division by zero")
>   else: result = a div b
> ```
>
> The reason for this is that `DivByZeroDefect` inherits from `Defect` and with `--panics:on` Defects become unrecoverable errors. (Since version 1.4 of the language.)

---

This compiles:
```Nim
proc foo {.raises: [].} =
  raise newException(IndexDefect, "")
```

But this does not:
```Nim
proc bar {.raises: [].} =
  raise newException(IOError, "") # Error: can raise an unlisted exception: ref IOError
```

Also:
```Nim
proc baz {.raises: [IndexDefect].} = # Hint: 'baz' cannot raise 'IndexDefect' [XCannotRaiseY]
  raise newException(IndexDefect, "")
```

See also:
- https://forum.nim-lang.org/t/7514
- [nim-lang/RFCs#222](https://github-redirect.dependabot.com/nim-lang/RFCs/issues/222)

**Comment by Zectbumo** [comment]
okay I think I misunderstood what panics:on does. closing the issue
