### ISSUE TITLE
result.repr produces unparsable Nim code from valid astGenRepr

### ISSUE THREAD

**Issue by joswik** [nim-lang/Nim#19778]
I've stumbled on this problem after viewing `result.repr` from 'curried' macro (currying package)
Example:
` proc sum(x, y: int): int {.curried.} = x + y`

produced this:

<pre>
proc sum(x: int; y: int): int =
  x + y

proc sum(x: int): auto =
  proc (y: int): auto =
    sum(x, y)
</pre>

When I tried to compile this directly, it blew up on the last proc:
`Error: identifier expected, but got '('`
 expecting name for that proc,
 but the real reason is that either `return` or `result =` is missing:
<pre> proc sum(x: int): auto =
   return proc (y: int): auto = sum(x, y)
</pre>
But if you compile generated AST directly, it works fine.

Below is the AST for `proc sum(x: int): auto = ... `;
you can call this macro with any argument (e.g. `bb(2)`) just to see the generated Nim source code (without `result=`)
or you can write something like: `echo bb(2)`, to provoke an error and view the real code in the error message:
<pre>expression: echo proc sum(x: int): auto =
  result = proc (y: int): auto = result = x + y</pre>

<pre>
macro bb(x:untyped):untyped =
  result =
    nnkStmtList.newTree(
    nnkProcDef.newTree(
      newIdentNode("sum"),
      newEmptyNode(),
      newEmptyNode(),
      nnkFormalParams.newTree(
        newIdentNode("auto"),
        nnkIdentDefs.newTree(
          newIdentNode("x"),
          newIdentNode("int"),
          newEmptyNode()
        )
      ),
      newEmptyNode(),
      newEmptyNode(),
      nnkStmtList.newTree(
        nnkLambda.newTree(
          newEmptyNode(),
          newEmptyNode(),
          newEmptyNode(),
          nnkFormalParams.newTree(
            newIdentNode("auto"),
            nnkIdentDefs.newTree(
              newIdentNode("y"),
              newIdentNode("int"),
              newEmptyNode()
            ) ),
          newEmptyNode(),
          newEmptyNode(),
      nnkStmtList.newTree(
        nnkInfix.newTree(
          newIdentNode("+"),
          newIdentNode("x"),
          newIdentNode("y")
        ) ) ) ) ) )

  echo result.repr
</pre>
BTW, unrelated to this, something else changed in the Nim compiler, 
since 'currying' macro doesn't work any more from Nim 1.4 and up.
(That's how I found this problem in the first place...)

**Comment by metagn** [comment]
Same issue as #18714, fixed in #20935 which is in 2.0 and 1.6.18 it seems
