### ISSUE TITLE
I have new Feature and I also found bug about this code {'a'..'Z'} 

### ISSUE THREAD

**Issue by mnboot** [nim-lang/Nim#19792]
nim 1.6.6

the bug:
`var x = {'a'..'Z'}` 
`echo x` 
`# the output is: {} `
`# no error `

my Idea/Feature
`var x = {'a'..'Z'}`
`echo x`
`# my idea output is: {"abc...xyzABC...XYZ"}`
or
`var x = {'a'..'Z'}`
`echo x`
`#my idea output is: {"aAbBcC ... yYzZ" }`

**Comment by ringabout** [comment]
There is no bug, `ord(a)` is more than `ord(Z)`.

```nim
var x = {'A'..'z'}
echo x
```
prints

```
{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}
```

Or you need

```nim
var x = {'a'..'z', 'A'..'Z'}
echo x
```

prints

```
{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}
```

**Comment by mnboot** [comment]
but why {'a'..'Z'} did not display anything not even error, still a bug or/and useless function

**Comment by RSDuck** [comment]
no `'a'..'Z'` is just an empty range like `0..-1`

**Comment by ee7** [comment]
> but why {'a'..'Z'} did not display anything not even error

Because:

```Nim
echo ord('A')
echo ord('Z')
echo ord('a')
echo ord('z')

for i in 2..3:
  echo i

for i in 7..5:
  echo i

for c in 'a'..'b':
  echo c

for c in 'z'..'x':
  echo c
```

```
65
90
97
122
2
3
a
b
```

From [wikipedia](https://simple.wikipedia.org/wiki/ASCII):

![ascii](https://user-images.githubusercontent.com/45465154/168417059-9bc95e24-eeeb-49d6-bb06-83ed967f8888.png)

**Comment by mnboot** [comment]
> Because:
> ```nim
> echo ord('A')
> echo ord('Z')
> echo ord('a')
> echo ord('z')

ook
Now I understand what just happen thx
