### ISSUE TITLE
Punycode not working for emojis

### ISSUE THREAD

**Issue by makinori** [nim-lang/Nim#19804]
I'm trying to use std/punycode and I'm not having luck decoding these emojis in particular. I'm using punycode urls such as: https://xn--3h8h64hda.ws which turns into the below image in nim, but displayed correctly looks fine on my twitter for example.

This javascript library is able to convert 3h8h64hda to emojis correctly using .decode()
https://github.com/mathiasbynens/punycode.js/blob/master/punycode.js

<img width="400" src="https://user-images.githubusercontent.com/8362329/169199017-ffdffcb7-ba4f-4e04-82f2-3553d9df3a18.png"/>

**Comment by ghost** [comment]
Fixed in devel, see https://github.com/nim-lang/Nim/pull/19136. It wasn't backported to 1.6 because no one mentioned it, but it should get backported if another 1.6 version gets released.

**Comment by narimiran** [comment]
> it should get backported if another 1.6 version gets released.

Correct. It will be part of the next 1.6.x release.
