### ISSUE TITLE
Where is testament?

### ISSUE THREAD

**Issue by cacilhas** [nim-lang/Nim#19815]
I would like to use [Testament](https://nim-lang.org/docs/testament.html), however:

```
[I] ✘[Sat 21, 2022-05-21 13:41:29 -03]cacilhas@valfenda 𝄞~/W/P/predation
fish-3.4> testament
fish: Unknown command: testament
[I] ✘[Sat 21, 2022-05-21 13:41:30 -03]cacilhas@valfenda 𝄞~/W/P/predation
fish-3.4> nimble install testament
    Prompt: testament not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Package not found.
```

How to install it?

**Comment by quantimnot** [comment]
testament is inside the compiler repo and is not a standalone package

How do you have nim installed? It may not be installed along with nim for your install method.

I commonly track and hack on the devel branch of the compiler, so I have the git repo cloned and its bin directory in a my PATH environment variable. I build nim and support binaries with the build_all.sh script.

**Comment by DavideGalilei** [comment]
Is the `~/.nimble/bin` folder included in your PATH environment variable?

**Comment by ringabout** [comment]
Feel free to reopen the issue if the methods provided don't work.
