### ISSUE TITLE
support more than `&` as a seperator in std/uri

### ISSUE THREAD

**Issue by Zectbumo** [nim-lang/Nim#19824]
### Summary
The uri module only supports `&` as a separator. There are other separators that are available in the uri space. 

### Description
Exposing a `sep` parameter will give access to the use of other separators.

### Alternatives
develop or use other libraries that support other separators.

**Comment by Zectbumo** [comment]
commit 45f4b019a4883b6ba577ade1f94677266beb5960

**Comment by dom96** [comment]
> There are other separators that are available in the uri space.

What are these? Are they non-standard?

**Comment by Zectbumo** [comment]
That's the thing, there is no standard for query parameters. Only the characters that is available at our disposal that the URI/URL RFC specifies. So the more flexible the query decoder library is, the better. Adding a separator parameter gives a little more access to the multiple possibilities that the query string has to offer with very little impact and effort. The only standard where we get the '&' separator from is the `application/x-www-form-urlencoded` encoding algorithm which is specified by the w3c. This only is used for URL-encoded form data submissions. This familiarity is where we derive the "standard" URL parameter list. If the only interest is to support `application/x-www-form-urlencoded` encoding then the library is fine standing as it is.

**Comment by Zectbumo** [comment]
In addition, to show that this is not out of the norm. Here is the python urllib parser for the query string which they specify using the `separator` parameter:
https://docs.python.org/3/library/urllib.parse.html?highlight=url#urllib.parse.parse_qs
`urllib.parse.parse_qs(qs, keep_blank_values=False, strict_parsing=False, encoding='utf-8', errors='replace', max_num_fields=None, separator='&')`

**Comment by dom96** [comment]
Nice, thanks for the links! Sounds good to me.

**Comment by Zectbumo** [comment]
> What are these?

To answer your question, uri rfc 3986 allows for these delimiters:
```
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```
https://datatracker.ietf.org/doc/html/rfc3986#section-2.2
in practice, it really just comes down to `&` and `;`

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/19825
