### ISSUE TITLE
[docgen]: Scroll sidebar separately from main documentation

### ISSUE THREAD

**Issue by omentic** [nim-lang/Nim#19837]
The sidebar containing proc/types/etc currently scrolls alongside the main documentation. This is a problem because Nim's documentation pages are usually very long: after clicking a signature and jumping to its documentation, you often find yourself far enough down the page that there's no sidebar in sight.

`.columns { overflow-y: auto; height: 100vh; }` basically does the trick, but causes other problems. I'll need to play around with the CSS some more before looking into rearranging the HTML structure. Getting it to work like [OCaml's documentation](https://ocaml.org/docs/garbage-collection) would be nice.

**Comment by juancarlospaco** [comment]
Also you can wrap whole sections into a `<details>`,
then you can collapse Types section or Templates section, etc.
