### ISSUE TITLE
`multiple definition of` in Nim generated static libraries

### ISSUE THREAD

**Issue by JDragan** [nim-lang/Nim#19830]
### Example
lib_a.nim
```nim
proc foo(): int32 {.exportc.} = return 24
```
lib_b.nim
```nim
proc bar(): int32 {.exportc.} = return 42
```
app.c
```c
#include "stdio.h"
int main() {
  printf("%i\n", foo());
  printf("%i\n", bar());
}
```
```
nim c -d:release --mm:arc --app:staticlib --noMain --nimMainPrefix:libA --nimcache:ncache --out:libA.a lib_a.nim
nim c -d:release --mm:arc --app:staticlib --noMain --nimMainPrefix:libB --nimcache:ncache --out:libB.a lib_b.nim
gcc app.c libA.a libB.a -o app
```
### Current Output
```
/usr/bin/ld: libB.a(@mlib_b.nim.c.o): in function `PreMainInner':
@mlib_b.nim.c:(.text+0x10): multiple definition of `PreMainInner'; libA.a(@mlib_a.nim.c.o):@mlib_a.nim.c:(.text+0x10): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o): in function `PreMain':
@mlib_b.nim.c:(.text+0x20): multiple definition of `PreMain'; libA.a(@mlib_a.nim.c.o):@mlib_a.nim.c:(.text+0x20): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o): in function `NimMainInner':
@mlib_b.nim.c:(.text+0x40): multiple definition of `NimMainInner'; libA.a(@mlib_a.nim.c.o):@mlib_a.nim.c:(.text+0x40): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o): in function `NimMainModule':
@mlib_b.nim.c:(.text+0x70): multiple definition of `NimMainModule'; libA.a(@mlib_a.nim.c.o):@mlib_a.nim.c:(.text+0x70): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o):(.bss+0x0): multiple definition of `gEnv'; libA.a(@mlib_a.nim.c.o):(.bss+0x0): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o):(.bss+0x8): multiple definition of `cmdLine'; libA.a(@mlib_a.nim.c.o):(.bss+0x8): first defined here
/usr/bin/ld: libB.a(@mlib_b.nim.c.o):(.bss+0x10): multiple definition of `cmdCount'; libA.a(@mlib_a.nim.c.o):(.bss+0x10): first defined here
collect2: error: ld returned 1 exit status
```

### Expected Output
```
24
42
```

### Possible Solution

* Emit `NimMainModule_source_name_qwerty12345()` instead of `NimMainModule()`
* Emit `cmdCount_source_name_qwerty12345()` instead of `cmdCount()`
* etc, etc...

### Additional Information
Tested with `--mm:arc` `--mm:orc` `--mm:refc` `--mm:none` + with the `--header` option

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
git hash: 19001c070bbe7645ff45fcbd66ab221235715302
```

**Comment by ghost** [comment]
You have to use the `--nimMainPrefix` switch https://github.com/nim-lang/Nim/commit/7ff43d07b2b983271d666b1c654b1426cbbbf236 so that each static library has it's own prefixes.

**Comment by JDragan** [comment]
The thing is that only `NimMain()` is renamed to `libANimMain()`.
NimMainInner(), PreMain(), PreMainInner() are not prefixed with libA/libB, so their symbols clash...

**Comment by deech** [comment]
This issue is currently blocking progress for me, any way to get it prioritized?

**Comment by JDragan** [comment]
Maybe this will help, works on Windows. On Linux however, `gEnv`, `cmdCount` and `cmdLine` are still in the generated code, which shouldn't happen since the `--noMain` switch is used

```diff
diff --git a/compiler/cgen.nim b/compiler/cgen.nim
index ad59b759f..bb91b8624 100644
--- a/compiler/cgen.nim
+++ b/compiler/cgen.nim
@@ -1322,7 +1322,7 @@ proc getSomeInitName(m: BModule, suffix: string): Rope =
 proc getInitName(m: BModule): Rope =
   if sfMainModule in m.module.flags:
     # generate constant name for main module, for "easy" debugging.
-    result = rope"NimMainModule"
+    result = rope m.config.nimMainPrefix & "NimMainModule"
   else:
     result = getSomeInitName(m, "Init000")
 
@@ -1351,11 +1351,11 @@ proc genMainProc(m: BModule) =
     preMainCode.add("\tvoid* rtl_handle;\L")
     preMainCode.add(loadLib("rtl_handle", "nimGC_setStackBottom"))
     preMainCode.add(hcrGetProcLoadCode(m, "nimGC_setStackBottom", "nimrtl_", "rtl_handle", "nimGetProcAddr"))
-    preMainCode.add("\tinner = PreMain;\L")
+    preMainCode.add("\tinner = " & m.config.nimMainPrefix & "PreMain;\L")
     preMainCode.add("\tinitStackBottomWith_actual((void *)&inner);\L")
     preMainCode.add("\t(*inner)();\L")
   else:
-    preMainCode.add("\tPreMain();\L")
+    preMainCode.add("\t" & m.config.nimMainPrefix & "PreMain();\L")
 
   const
     # not a big deal if we always compile these 3 global vars... makes the HCR code easier
@@ -1370,20 +1370,20 @@ proc genMainProc(m: BModule) =
 
     PreMainVolatileBody =
       "\tvoid (*volatile inner)(void);$N" &
-      "\tinner = PreMainInner;$N" &
+      "\tinner = $3PreMainInner;$N" &
       "$1" &
       "\t(*inner)();$N"
 
     PreMainNonVolatileBody =
       "$1" &
-      "\tPreMainInner();$N"
+      "\t$3PreMainInner();$N"
 
     PreMainBodyStart = "$N" &
-      "N_LIB_PRIVATE void PreMainInner(void) {$N" &
+      "N_LIB_PRIVATE void $3PreMainInner(void) {$N" &
       "$2" &
       "}$N$N" &
       PosixCmdLine &
-      "N_LIB_PRIVATE void PreMain(void) {$N"
+      "N_LIB_PRIVATE void $3PreMain(void) {$N"
 
     PreMainBodyEnd =
       "}$N$N"
@@ -1394,21 +1394,21 @@ proc genMainProc(m: BModule) =
     MainProcsWithResult =
       MainProcs & ("\treturn $1nim_program_result;$N")
 
-    NimMainInner = "N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {$N" &
+    NimMainInner = "N_LIB_PRIVATE N_CDECL(void, $5NimMainInner)(void) {$N" &
         "$1" &
       "}$N$N"
 
     NimMainVolatileBody =
       "\tvoid (*volatile inner)(void);$N" &
       "$4" &
-      "\tinner = NimMainInner;$N" &
+      "\tinner = $5NimMainInner;$N" &
       "$2" &
       "\t(*inner)();$N"
 
     NimMainNonVolatileBody =
       "$4" &
       "$2" &
-      "\tNimMainInner();$N"
+      "\t$5NimMainInner();$N"
 
     NimMainProcStart =
       "N_CDECL(void, $5NimMain)(void) {$N"
@@ -1488,9 +1488,9 @@ proc genMainProc(m: BModule) =
     else: ropecg(m, "\t#initStackBottomWith((void *)&inner);$N", [])
   inc(m.labels)
   if m.config.selectedGC notin {gcNone, gcArc, gcOrc}:
-    appcg(m, m.s[cfsProcs], PreMainBodyStart & PreMainVolatileBody & PreMainBodyEnd, [m.g.mainDatInit, m.g.otherModsInit])
+    appcg(m, m.s[cfsProcs], PreMainBodyStart & PreMainVolatileBody & PreMainBodyEnd, [m.g.mainDatInit, m.g.otherModsInit, m.config.nimMainPrefix])
   else:
-    appcg(m, m.s[cfsProcs], PreMainBodyStart & PreMainNonVolatileBody & PreMainBodyEnd, [m.g.mainDatInit, m.g.otherModsInit])
+    appcg(m, m.s[cfsProcs], PreMainBodyStart & PreMainNonVolatileBody & PreMainBodyEnd, [m.g.mainDatInit, m.g.otherModsInit, m.config.nimMainPrefix])
 
   if m.config.target.targetOS == osWindows and
       m.config.globalOptions * {optGenGuiApp, optGenDynLib} != {}:
```

**Comment by deech** [comment]
This is nice for now but we really need symbol isolation otherwise it's impossible to create C ABIs for Nim libraries because any two will clash on any common parts of their respective dependency tree including the standard library. It might be worth generalizing `--nimMainPrefix=...` to something like `--nimPrefix=...` that will do to all other visible symbols what `nimMainPrefix` does for `NimMain`, there is still potential for unpleasant overlap if two people pick the same prefix and the binary that uses them will be a little bloated with some redundant symbols but IMO it's worth it to be able to use Nim from other languages.

**Comment by deech** [comment]
This also seems promising, I had no idea you could use `objcopy` this way. https://stackoverflow.com/questions/6940384/how-to-deal-with-symbol-collisions-between-statically-linked-libraries/6940389#6940389

**Comment by JDragan** [comment]
imo `--nimMainPrefix` shouldn't exist.

When using `--app:staticlib`, `--noMain` should be activated and the prefix for these functions should be taken from the `--out:SomeLib.a` switch (instead `NimMain()`, one will call the initialization with `SomeLibMain()`) and this would be general rule no matter if you compile 1 or 1000 libraries.

**Comment by deech** [comment]
I discovered that if you can use the `cpp` backend the `--cppCompileToNamespace:myLib` flag will wrap all the generated C++ code in a namespace and prevent symbol clashes.

**Comment by Araq** [comment]
This works now.

**Comment by dmknght** [comment]
Hello! I'm having similar issue trying to build a static lib in Nim and then use an other Nim script to import the lib. (It's for testing only). I got similar issue and add `--passL:-Wl,--allow-multiple-definition` to Nim worked for me.

**Comment by waruqi** [comment]
> Hello! I'm having similar issue trying to build a static lib in Nim and then use an other Nim script to import the lib. (It's for testing only). I got similar issue and add `--passL:-Wl,--allow-multiple-definition` to Nim worked for me.

It does not work now.

```
ld: unknown option: --allow-multiple-definition
clang: error: linker command failed with exit code 1 (use -v to see invocati
on)
```

https://github.com/xmake-io/xmake/issues/4042#event-10016603435

**Comment by dmknght** [comment]
> ld: unknown option: --allow-multiple-definition
clang: error: linker command failed with exit code 1 (use -v to see invocati
on)

This is **NOT** the error mentioned in the issue. The error log showed the compiler was `clang`.

**Comment by waruqi** [comment]
> > ld: unknown option: --allow-multiple-definition
> > clang: error: linker command failed with exit code 1 (use -v to see invocati
> > on)
> 
> This is **NOT** the error mentioned in the issue. The error log showed the compiler was `clang`.

I know, but earlier I used this method to solve this issue as well, but now it doesn't work.

Also, nim always calls clang as a linker on my machine. if this flag is not available, how should I resolve this issue. `multiple definition of `NimMainModule` `
