### ISSUE TITLE
Can't pass local const with generic object type to a template.

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#19849]
You cannot pass to a template an expression yielding a local `const` whose type is a generic object.

### Example

```nim
type
  Vec2[T] = object
    x, y: T
  
  Vec2i = Vec2[int]

template print(p: Vec2i) =
  echo p.x

print:
  const t = Vec2i()
  t
```

### Current Output

```
test.nim(10, 1) template/generic instantiation of `print` from here
test.nim(11, 9) Error: inconsistent typing for reintroduced symbol 't': previous type was: Vec2[system.int]; new type is: object
```

### Expected Output

Program compiles and prints `0`.

### Additional Information

- The problem doesn't seem to occur for generic tuples or other generic types.

- The problem doesn't occur if the receiving template merely forwards the parameter `p` to another proc, e.g. `echo p`. But it does occur if it tries to access a field such as `p.x`, or assign `p` to a variable.

- The example does compile on Nim 0.17.2.

```
$ nim -v
Nim Compiler Version 1.6.6 [Linux: amd64]
```

**Comment by lilkeet** [comment]
Some sort of information loss seems to be happening inside of templates, both typed and untyped.
This also occurs with tuples with named attributes:
```nim
const Outer: tuple[a, b: int] = (1, 2)

proc printProc(c: tuple[a, b: int]): void =
  echo c.a # Works

printProc:
  const InnerProc = Outer # Works
  InnerProc

template printTemplateUntyped(c: tuple[a, b: int]): untyped =
  echo c.a # Error: undeclared field: 'a'

printTemplateUntyped:
  const InnerTemplate1 = Outer #[Error: inconsistent typing for reintroduced
                                 symbol 'InnerTemplate': previous type was:
                                 tuple[a: int, b: int]; new type is:
                                 (int, int, int, int)]#
  InnerTemplate1

template printTemplateTyped(c: tuple[a, b: int]): void =
  echo c.a # Error: undeclared field: 'a'

printTemplateTyped:
  const InnerTemplate2 = Outer #[Error: inconsistent typing for reintroduced
                                 symbol 'InnerTemplate': previous type was:
                                 tuple[a: int, b: int]; new type is:
                                 (int, int, int, int)]#
  InnerTemplate2
```
Work-around is to explicitly (re)type anything that these errors occur on:
```nim
const Outer: tuple[a, b: int] = (1, 2)

template printTemplateUntyped(c: tuple[a, b: int]): untyped =
  let workaround: tuple[a, b: int] = c
  echo workaround.a # Works

printTemplateUntyped:
  const InnerTemplate1: tuple[a, b: int] = Outer # Works
  InnerTemplate1

template printTemplateTyped(c: tuple[a, b: int]): void =
  let workaround: tuple[a, b: int] = c
  echo workaround.a # Works

printTemplateTyped:
  const InnerTemplate2: tuple[a, b: int] = Outer # Works
  InnerTemplate2
```
The compiler complains about the "undeclared field: 'a'" on all nim versions past 1.0. On nim version 0.17.2, it complains about the "inconsistent typing for reintroduced symbol" instead.
```
$ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
```

**Comment by metagn** [comment]
Information loss is intentional for the VM and happens on the `Vec2i()` expression. We can either:

- ignore attempts to mutate `const` symbols
- in the typed AST, re-emit the unevaluated but typed RHS in the const definition, meaning `Vec2i()` etc keeps the correct type but is re-evaluated

First one is safer but might remove functionality for macro authors.
