### ISSUE TITLE
Release mode still shows a line of stack trace

### ISSUE THREAD

**Issue by Zectbumo** [nim-lang/Nim#19842]
After doing a -d:release the executable still has a one line stack trace. Release shouldn't have any stack trace.

### Example
```nim
discard open("/doesnotexist")
```

### Current Output
```
syncio.nim(764)          open
Error: unhandled exception: cannot open: /doesnotexist [IOError]
```

### Expected Output
```
Error: unhandled exception: cannot open: /doesnotexist [IOError]
```
and possibly leave off the `[IOError]` signature:
```
Error: unhandled exception: cannot open: /doesnotexist
```
on release, I don't even see the point on mentioning "unhandled exception" either. Here is my preferred error:
```
Error: cannot open: /doesnotexist
```

### Possible Solution

When -d:release is used it should not show any part of a stacktrace, and possibly not show the Exception name too. 

### Additional Information
I have tried several flags. Nothing will remove the one line stack from the output:
```
-d:release
-d:danger
--lineTrace:off
--opt:size
--checks:off
--debugInfo:off
--stackTrace:off
--verbosity:0
--stackTraceMsgs:off
--excessiveStackTrace:off
```

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-05-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 06f02bb7716066241b04b2a92a3a61f539eadff2
active boot switches: -d:release
```

**Comment by ghost** [comment]
I don't think this is a good idea, without even the file where the exception happened debugging would be a nightmare. At *most* we could add yet (heh) another flag that will remove the file where the exception happened.

**Comment by SolitudeSF** [comment]
wrap entire program in `try/except`

**Comment by ghost** [comment]
If you really want your program to not show any exceptions you can just wrap the starting part in a bare try/except block like
```nim
try:
  mainProgramProc()
except:
  quit(1) # don't output anything, no exception name, no filename, just exit without clarifying further
```

Yes, that solution is pretty ugly, but I don't think most people would want the behaviour you describe anyway.

**Comment by Zectbumo** [comment]
> debugging would be a nightmare

`-d:release` <------ debugging is over. All debug symbols stripped. 

> add yet (heh) another flag

If we must. yes. Right now there is no way to actually do a release and stop trying to print trace. I would rather see sensible defaults so if we do add a flag then, when doing a release, have the flag default off (zero stack). If you want one in a release, then turn it on.

> wrap entire program in try/except

I'm not looking to eliminate all exceptions. I'm looking for cleaned up errors. Like any typical unix command behaves. Not dumping a stack, even if it is a limited one.

**Comment by Araq** [comment]
It's a feature, not a bug.
