### ISSUE TITLE
Can't implicitly instantiate proc with generic params and generic type constraint

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#19848]
A generic proc that takes some collection as an argument, cannot be implicitly instantiated if the generic type is constrained by a generic typeclass.

### Example

```nim
type
  Maybe[T] = object
  List[T] = object

proc dump[M: Maybe](a: List[M]) =
  echo "todo"

var a: List[Maybe[int]]
  
dump(a)
```

### Current Output

```
generics_bug.nim(10, 5) template/generic instantiation from here
generics_bug.nim(5, 11) Error: cannot instantiate 'Maybe[T]' inside of type definition: 'dump'; Maybe generic arguments are missing?
```

### Expected Output

Program compiles and prints `todo`.

### Additional Information

The program compiles if you make any of the following changes:

* Change the proc to a template.

* Use a built-in container instead of `List`, such as `seq`.

* Remove the constraint, i.e. `proc dump[M](a: List[M])`

* Fully specialise the constraint, i.e. `proc dump[M: Maybe[int]](a: List[M])`

* Explicitly instantiate the proc, i.e. `dump[Maybe[int]](a)`

Additionally, the program compiles on Nim 0.16.0 but not on 0.17.0, so there was apparently a time when this worked.

```
$ nim -v
Nim Compiler Version 1.6.6 [Linux: amd64]
```

**Comment by beef331** [comment]
```nim
type
  Maybe[T] = object
  List[T] = object

proc dump(a: List[Maybe[auto]]) =
  echo "todo"

var a: List[Maybe[int]]
  
dump(a)
```
For posterity sakes also works.
