### ISSUE TITLE
[Idea / Proposal / Discussion] Nim dialect variants

### ISSUE THREAD

**Issue by rubyFeedback** [nim-lang/Nim#19858]
Note: I did not go to https://github.com/nim-lang/RFCs because I feel it is a little bit too bureaucratic. My proposal
is more like a "loose thought"; the rationale is the more important part in the proposal here.

Background: I have been using ruby since a very long time. I am also using python and I am fine with both 
languages for the most part.

My proposal here is aimed at Nim, though. That is to make Nim more flexible in regards to the parser. Thus,
something like a "Nim dialect".

For example, to output text in Nim one uses something like:

    echo("What's your name? ")

So we use echo().

I would like to be able to use:

    print()
    puts()

as well.

I would also like to be able to e. g. alias "e" to "echo". Saving 3 characters may seem insignificant but
I actually use "e" in ruby since decades literally, including colour support on the commandline. So I 
am not even using "puts" in ruby as such.

On top of that I would also like to be able to omit the (), at the least for echo (output) related stuff.

Now: I am NOT necessarily proposing that Nim itself changes. I am fine to keep Nim the way it is.

My proposal instead means that we could change the parser itself and make it more flexible.

The above examples, e. g. using e(), puts() and print(), as well as being able to omit (), are
just examples, though. I am sure that other people may want to change other aspects of nim.

Now, it is also important to add that I do NOT mean that craziness should be encouraged.
100 different people suggest 101 different things and I understand that one can not support
every crazy idea. So I am NOT proposing any ad-hoc suggestion per se.

But!

What I AM suggesting is kind of to add a "guided" path towards Nim, in regards to "dialects"
(slight variations) that may be community-chosen and/or voted by the community and be
kept in a conservative manner. Let me give you an example what I mean here.

Say we have 2000 registered nim users, just for a number. Now we have some proposal
for more syntax flexibility. As example, to omit () (but retain it just for output-related parts
for now). Ok, it is discussed for a few months. Then, when it seems useful, a vote is made.
20% participate, and of these 20% 80% are in favour of adding this as a dialect variant.
So it will be added eventually. Past that point it is possible to omit ().

So this is what I mean with community-driven decisions. Note: It is also important that
I am NOT proposing to undermine Andreas or the core devs in any way. So they are
the language designers, and they should get complete freedom to decide from A to
Z. Matz in ruby is already the main designer, and I am absolutely fine with that. One
has to keep the language itself consistent, I understand that completely. My above 
suggestion is more a way how to deal with language changes, a bit like Crystal does
(though some crystal devs are kind of main devs too).

Ok. So, how is this then implemented?

Well - various ways. One could be to add this feature by default into the language by
itself. Then we need a way to select this. This could be like leading import statements
on top of the file or something like that. Like "enable omitting parens" or something.
Alternatively it could be an add-on gathered like in "dialects/" or something.

What is the use case or rationale here?

I think this could make the language in general somewhat more flexible, syntax-wise,
but also when it may come to some ideas that are popular but may not necessarily
be implemented or wanted to be implemented for whatever the reason. So I also
mean a bit more flexibility in the design of nim as such.

Every some years, say 5-15 years interval or something, dialects can be evaluated
and if people think the trade-off is not worth it, to considered a removal. (This may
be different depending whether dialects are a core part, or an add-on only part. If
it is add-on only then it's not so important to change, as opposed to a core part of
Nim.)

Anyway. I'll leave the proposal here now. I think the most important part is as an
idea and discussion. If possible I would like to see this be open for a few weeks
before it is closed, but it's fine to close the idea at any moment in time - I understand
that keeping the issue tracker clean is important, so perhaps it can be closed
after ~some weeks of people saying pro/con/neutral on the idea. Thank you for
reading!

**Comment by SolitudeSF** [comment]
the only concrete feature that you ask here

> The above examples, e. g. using e(), puts() and print(), as well as being able to omit (), are
just examples, though. I am sure that other people may want to change other aspects of nim.

you can already do. you talk about parser yet half of your motivation isnt related to parsing at all.

**Comment by Araq** [comment]
"puts" and "print" are both poorly named, "print" is not related to a real printing device and "puts" is wrong grammar.

But the real problem with your proposal is that you spent more time writing this proposal than you spent using Nim, otherwise you would know you can leave out the `()`. This may sound harsh but it's not meant to be, you simply give your feedback **much** too quickly and so I'm gonna dismiss it quickly too.
