### ISSUE TITLE
Symlinks to directories reported as symlinks to files

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1985]
Under OSX and Linux symlinks to directories are reported as symlinks to files. See the following ``test.nim``:
```nimrod
import os

const target = "target_dir"

proc test() =
  discard execShellCmd("mkdir -p source_dir")
  if not target.existsDir:
    discard execShellCmd("ln -s source_dir " & target)

  for kind, path in walkDir("."):
    echo kind, " with path '", path, "'"

when isMainModule: test()
```
Compiling and running generates:
```
$ nim c -r test.nim
…
pcDir with path './nimcache'
pcDir with path './source_dir'
pcLinkToFile with path './target_dir'
pcFile with path './test'
pcFile with path './test.nim'
```
I was expecting to get a ``pcLinkToDir`` instead.

**Comment by Varriount** [comment]
I don't have a linux system at the moment to test this on, but I suspect this might be due to [S_ISDIR](https://github.com/Araq/Nim/blob/devel/lib/pure/os.nim#L1292) not returning true for symlinks to directories.
