### ISSUE TITLE
Templates with references to same-named types across imports resolve oddly

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#19866]
Templates with references to same-named types across imports resolve oddly: accessing them most ways allows one to properly disambiguate which module (here, modules `a` and `b`, with type `A`) one means.

However, when using backtick-constructed template references to these modules, while it does check whether the module exists (asking Nim to compile ``doAssert f(`nomodule`) == g(a.A)`` properly fails, and it notices that `nomodule` does not exist), if the module does exist, it doesn't necessarily resolve and bind to the type in the module specified.

### Example
`a.nim`:
```nim
type A* = object
  x*: int
```

`b.nim`:
```nim
type A* = object
  x*: array[1000, byte]
```

Which are imported by
```nim
# Switch module import order to switch which of last two
# doAsserts fails
import a
import b

template f(moduleName: untyped): int = sizeof(`moduleName`.A)
template g(someType:   untyped): int = sizeof(someType)

# These are legitimately true.
doAssert sizeof(a.A) != sizeof(b.A)
doAssert g(a.A) != g(b.A)

# Which means that this should not be true, but is in Nim 1.6
doAssert f(`a`) == f(`b`)

# These should be true, but depending on import order, exactly one
# fails in Nim 1.2, 1.6 and devel.
doAssert f(`a`) == g(a.A)
doAssert f(`b`) == g(b.A)
```

### Current Output
please check whether the problem still exists in git head before posting,
see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
When `import a` is followed by `import b`:
```
c.nim(17) c
Nim/lib/std/assertions.nim(44) failedAssertImpl
Nim/lib/std/assertions.nim(34) raiseAssert
Nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: c.nim(17, 10) `f(`b`) == g(b.A)`  [AssertionDefect]
```

When `import b` is followed by `import a`:
```
c.nim(16) c
Nim/lib/std/assertions.nim(44) failedAssertImpl
Nim/lib/std/assertions.nim(34) raiseAssert
Nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: c.nim(16, 10) `f(`a`) == g(a.A)`  [AssertionDefect]
```

Tested with:
```
Nim Compiler Version 1.2.16 [Linux: amd64]
Compiled at 2022-06-06
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: c6a9f27b3e36bae9aacec1bd6c37893fb98fd33f
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-14
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
and current devel:
```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-06-06
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: d0232f0e5b97b697a640c2f622c7596ce6d10eb5
active boot switches: -d:release
```

### Expected Output
Asserting on `doAssert f(`a`) == f(`b`)` and not on either of `doAssert f(`a`) == g(a.A)` or `doAssert f(`b`) == g(b.A)`.

**Comment by metagn** [comment]
Would work in devel since #23997 if `qualifiedLookUp` for `nkDotExpr` allowed symchoices on the RHS rather than just [idents and accents](https://github.com/nim-lang/Nim/blob/3b85c1a2e9b913a11fc7cd202b7e0a617d782cf4/compiler/lookups.nim#L688-L691). Don't see any reason not to do this.
