### ISSUE TITLE
Should `(x,)` produce a 1-element tuple?

### ISSUE THREAD

**Issue by MasonMcGill** [nim-lang/Nim#1987]
It currently doesn't (it just produces `x`), but this would be helpful. Currently, generic routines that build tuples don't have to choose between
1. failing when they should produce 1-element tuples.
2. producing tuples with named elements that are now incompatible with other tuples (see abb7381).

This parsing also seems to be consistent with the grammar. The relevant snippet:

```
tupleConstr = '(' optInd (exprColonEqExpr comma?)* optPar ')'
```

**Comment by tobimpub** [comment]
+1
this is also a problem wehn you bulid a tuple in a macro. If your generated tuple has only one member the wrapping tuple is implicitly removed.
Adding dummy members as a workaround is not long term solution.

**Comment by Araq** [comment]
It never occured to me that singleton tuples are useful in a statically typed language. ;-)

**Comment by MasonMcGill** [comment]
If you ever get a chance, play around with Julia's type-safe (relative to Python/MATLAB) approach to computing with multidimensional arrays. Singleton tuples sometimes come up when you're working with those sorts of APIs.

They're also helpful when you're trying to emulate or implement variadic generics.

**Comment by drbo** [comment]
This should definitely produce a 1-element tuple.  Julia, Python, and Rust all do this, while in Haskell, OCaml, and Standard ML `(1,)` is a syntax error.  Since Nim accepts this syntax, the syntax should refer to a 1-element tuple.  1-element tuples can be useful for generic programming.

**Comment by timotheecour** [comment]
+1 ; conflating 1-element tuples and elements breaks generic code.

**Comment by Araq** [comment]
This has been implemented. Closing.
