### ISSUE TITLE
Nim 1.6.6 not generating Windows Executable

### ISSUE THREAD

**Issue by ikzettel** [nim-lang/Nim#19872]
I have a fresh installation of Nim on Windows 10 64 bit system. While the installation is fine, trying to compile a simple hello.nim is not working. I see that the executable is not getting generated. 

hello.nim
```
echo "Hello, World"
```

Compile command
```
nim c -r hello.nim
```

```
Hint: used config file 'C:\tools\Nim\nim-1.6.6\config\nim.cfg' [Conf]
Hint: used config file 'C:\tools\Nim\nim-1.6.6\config\config.nims' [Conf]
.........................................................
Hint:  [Link]
Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
26671 lines; 0.586s; 31.668MiB peakmem; proj: D:\TBS\workspace\nimlearn\hello.nim; out: D:\TBS\workspace\nimlearn\hello.exe [SuccessX]
Hint: D:\TBS\workspace\nimlearn\hello.exe  [Exec]
oserr.nim(95)            raiseOSError
Error: unhandled exception: Access is denied.
 [OSError]
```

While checking the directory, the executable is not generated. 

nim and gcc are in path, and can be invoked. gcc can compile c programs and has been verified. 

```
$ nim -v
Nim Compiler Version 
Nim Compiler Version 1.6.6 [Windows: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf
```

**Comment by Araq** [comment]
Disable your antivirus software and check the file/directory permissions.

**Comment by ikzettel** [comment]
@Araq Unfortunately I don't have privilege to disable anti-virus software. But for file / directory permission there is no issue. I have full access. May I know how antivirus software has anything to do here, knowing that would help me to look for some workaround.

**Comment by rockcavera** [comment]
@ikzettel , when compiled without `-r`, is the .exe in the folder? `nim c hello.nim`?

You installed Nim how? Where did you download mingw from? Could you try different gcc options?

You can try compiling with clang, tcc or vcc too.

Antivirus are marking Nim executables as false positives (see https://forum.nim-lang.org/t/7885). I've heard it's a problem with MinGW. But I've already managed to reproduce false positive with just a "hello world" in C, compiling with mingw.

**Comment by rockcavera** [comment]
@ikzettel, you can test this compiler [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.4.0/threads-posix/seh/x86_64-6.4.0-release-posix-seh-rt_v5-rev0.7z/download). I did some tests with several versions of mingw64 and this version, with gcc 6.4.0, was the one that generated the least false positives within the Nim compiler tools (devel did not generate any false positives and 1.6.6 generated only in nimgrab - see [this](https://github.com/nim-lang/Nim/pull/19767)). I also tested vcc, llvm(clang), llvm-mingw(clang) and tdm64-gcc but they all generated false positives. I wasted a long time recompiling (18 times) Nim and its tools for windows...

**Comment by Elementals** [comment]
So the output shows that the nim compiler does not have permission to write to your D disk.
Try opening cmd or powershell as administrator and then compile.
