### ISSUE TITLE
Non-anchored Regular Expression

### ISSUE THREAD

**Issue by flenniken** [nim-lang/Nim#19889]
Add support for non-anchored regular expression matching.  

In my experience the non-anchored option is the default in different languages and I was surprised that anchored is used in the re module and that you cannot use non-anchored.

I'm having to find the start position or running multiple searches where I would normally use one regex.

The underlining PCRE code supports an anchored flag but it is not exposed to the public procedures. The re module hard codes the PCRE's anchored option (pcre.ANCHORED).

One example where it is harder with non-anchored is when you try to search for optional things at the end of a line:

```
/(""")[ \t]*([\r]{0,1}[\n]{0,1})$/gm
/([+]{0,1})([\r]{0,1}\n){0,1}$/gm
```

**Comment by Araq** [comment]
Match vs find. `find` exists too and does what you want it to do. Nim sometimes uses the correct words for its concepts.
