### ISSUE TITLE
Improve error message when instantiating generics that lack a type

### ISSUE THREAD

**Issue by capocasa** [nim-lang/Nim#19882]
I wish this were a PR but I would require some guidance to where to start differentiating this error condition from others.

Improve error message when instantiating generics that lack a type

### Example
```nim
import critbits
proc init(): ref CritBitTree =      
  new(result)
var a = init()
```

### Current Output
```
 Error: cannot instantiate: 'CritBitTree'
```

Not helpful. Consider a programmer on a deadline after an all nighter at six in the morning. Shouldn't happen, but...

### Expected Output
```
Error: cannot instantiate: 'CritBitTree'
Might the type definition be missing its concrete type, e.g. 'CritBitTree[void]' instead of 'CritBitTree'`?
```

Sleep deprived programmer now loves the compiler.

### Possible Solution

Errors due to lacking concrete type would have to be isolated from other "cannot instantiate" error conditions and this message emitted.

**Comment by beef331** [comment]
The issue with your suggestion though is that the code is valid. The following is how you'd call it.
```nim
import critbits
proc init(): ref CritBitTree =      
  new(result)
var a = init[CritBitTree[void]]()
```

`ref CritBitTree` is an implicit generic typeclass which makes the proc definition equivalent to `proc init[T: CritBitTree[auto](): ref T = new result`.

As such the error message needs to mention that the issue might be the callsite or the definition.

**Comment by capocasa** [comment]
Thanks!! How about this?

```
Error: cannot instantiate: 'CritBitTree'
`CritBitTree` is a generic, need concrete type information to instantiate, e.g. 'CritBitTree[void]').
```
Probably too hard to list all the ways to provide the concrete type n the error message, but at least this clearly states what the problem is.

**Comment by beef331** [comment]
Yea in the case it's a typeclass lacking parameters I think `Cannot instantiate 'CritBitTree', it is a typeclass lacking generic parameter(s)` or similar is fine.

**Comment by beef331** [comment]
A cursory look seems to indicate changing https://github.com/nim-lang/Nim/blob/e2e663a14389500b07e2f6fcd5c231536bdf76a0/compiler/seminst.nim#L57-L77
to should suffice in adding the error message desired.
```nim
const
  errCannotInstantiateX = "cannot instantiate: '$1'"
  errCannotInstantiateXLackingParams = "cannot instantiate: '$1' it is a typeclass lacking generic parameter(s)."

iterator instantiateGenericParamList(c: PContext, n: PNode, pt: TIdTable): PSym =
  internalAssert c.config, n.kind == nkGenericParams
  for i, a in n.pairs:
    internalAssert c.config, a.kind == nkSym
    var q = a.sym
    if q.typ.kind in {tyTypeDesc, tyGenericParam, tyStatic, tyConcept}+tyTypeClasses:
      let symKind = if q.typ.kind == tyStatic: skConst else: skType
      var s = newSym(symKind, q.name, nextSymId(c.idgen), getCurrOwner(c), q.info)
      s.flags.incl {sfUsed, sfFromGeneric}
      var t = PType(idTableGet(pt, q.typ))
      if t == nil:
        if tfRetType in q.typ.flags:
          # keep the generic type and allow the return type to be bound
          # later by semAsgn in return type inference scenario
          t = q.typ
        else:
          if q.typ.kind == tyCompositeTypeClass:
            localError(c.config, a.info, errCannotInstantiateXLackingParams % s.name.s)
          else:
            localError(c.config, a.info, errCannotInstantiateX % s.name.s)
```
So have fun with that PR and accompanying tests! :stuck_out_tongue:
