### ISSUE TITLE
[discussion] nimsuggest crash resilience

### ISSUE THREAD

**Issue by yyoncho** [nim-lang/Nim#19896]
This is a follow-up from the discussion in https://github.com/nim-lang/Nim/pull/19826#pullrequestreview-999972300

Currently, when `nimsuggest` is performing incremental build it often may crash. These failures have to be fixed but it is not a trivial task. As a result, there is a need for process monitor like [nimlangserver](https://github.com/nim-lang/langserver) which can handle process failures. The challenges here arrive from the fact that it is not trivial to find a reliable automatic restart strategy in the monitoring process because the failure may come from a clean build and that may result in a crash loop.

My proposal is to alter `nimsuggest` to handle as many crashes caused by partial recompilation internally as possible by handling null pointer-related problems (IME most of the crashes are nil pointer) by adding `import segfaults` and also replacing the `quit` calls with throwing exceptions. Once recompilation fails, `nimsuggest` will throw the internal data and it will start clean compilation(i. e. "internal restart"). This functionality can be hidden behind a build flag(or even command-line one) and by its nature will be something that we will throw away once the recompilation process is stabilized.

The drawback of this approach is that we are risking problems being hidden and not reported because the errors will be handled internally and they won't be visible for the end-user. My plan here is to address the immediate ones that happen very often and that are currently causing poor user experience and then make the crashes evident again.

(Please let me know if this is not the right place for discussions so I can move it somewhere else)

**Comment by Araq** [comment]
It's ok to have this discussion here.

Already nimsuggest uses multiple threads in order to stay responsive when a query takes long. We could replace that threading with multi-processing and gain the reliability benefits of multi-processing that I've outlined already.

**Comment by yyoncho** [comment]
I might be missing the whole picture, but what cannot be handled in single process ATM? Are we expecting crashes/leaks that cannot be recovered by throwing away `ModuleGraph` and starting with clean one?

**Comment by Araq** [comment]
> Are we expecting crashes/leaks that cannot be recovered by throwing away ModuleGraph and starting with clean one?

We tried for weeks to get rid of nimsuggest's leaks, yes, it's a hard problem. We didn't throw away the ModuleGraph though but I don't understand why we shouldn't keep it simple and make good use of the features the OS offers us for free: Close to perfect resource cleanups and process isolation.

**Comment by yyoncho** [comment]
My concern is that it will be more work and if we manage to stabilize
recompilation it will be throw-away work. On the other hand, it will be
easy/trivial to catch the errors in `nimsuggest` and restart under the hood.
This, although not perfect, will improve the UE right away and it will allow us
to focus on other things:

1. Optimizing incremental compilation(checking if public interfaces are changed, etc)
2. Stabilizing recompilation - I believe that most of the crashes are related to
   generics cache, this is one of the things I want to address next


As an alternative to this, I can change `nimlangserver` to opportunistically
restart the `nimsuggest` once after a crash. Although my hope was to run
`nimlangserver` in one process with `nimsuggest` to avoid the need to
implement the commands in two places. That would be possible if we prove
`nimsuggest` to be stable.

**Comment by yyoncho** [comment]
> As an alternative to this, I can change `nimlangserver` to opportunistically
> restart the `nimsuggest` once after a crash.

I think that I can go with that implementation for now. It has also one advantage - I will send notifications to the user. I will close the issue for now to reduce the backlog but I may reopen the discussion in the future. 

Thank you for your time.
