### ISSUE TITLE
`cannot generate VM code for and` when using `math.ceilDiv` with generic type argument

### ISSUE THREAD

**Issue by cmd410** [nim-lang/Nim#19916]
Cannot generate VM code for seemingly correct `and` operator in assertion in `math.ceilDiv`

https://github.com/nim-lang/Nim/blob/a65db5e2e924c51af7c654f8e564332299b95cb3/lib/pure/math.nim#L976

When used to operate on generic argument.

### Example
```nim
import math

type
  Test[S: static[Natural]] = object
    a: array[ceilDiv(S, 8), uint8]

let a = Test[32]()
echo a
```

### Current Output
```
/.../nim/lib/pure/math.nim(977, 17) Error: cannot generate VM code for and
```

### Expected Output

Should compile, don't see why not...

### Possible Solution

No idea.

### Additional Information
```console
$ nim --version
Nim Compiler Version 1.6.6 [Windows: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
Also tried on 1.6.2, same error.

**Comment by bung87** [comment]
it result to `nkOpenSymChoice` in `vmgen.gen`, duno what expected here, `Natural` is range of `int` , `ceilDiv` returns `SomeInteger`,  well `SomeInteger` defined as `SomeSignedInt | SomeUnsignedInt`, so it could be negtive number, that's not the point, the point here is array index type here should be static int

**Comment by metagn** [comment]
Related but not the same #19284, this issue is a generic object with an array field, #19284 is a generic alias to an array type
