### ISSUE TITLE
Missing path substitution documentation and tests

### ISSUE THREAD

**Issue by quantimnot** [nim-lang/Nim#19928]
I can't find any documentation or thorough tests of the path substitution performed by `compiler/options/pathSubs`.

From looking at the code, these are the substitutions:
* `$nim`: global nim prefix directory path
* `$lib`: stdlib directory path
* `$home`: user's home directory path
* `$config`: I think this is the directory path to the either the nimscript calling
  `compiler/options/pathSubs` or the directory path of the module being compiled.
   This needs confirmed with tests.
* `$projectname`: project file's name without extension
* `$projectpath`: project file's directory path
* `$projectdir`: project file's directory path (same as `projectpath`)
* `$nimcache`: nimcache directory path
* leading `~`: user's home directory path

Here is where the substitutions are performed:
* import/include string literals: `import "$home/module"`
* these compiler settings:
  * `path`, `p`
  * `nimblepath`
  * `excludepath`
  * `nimcache`
  * `out`, `o`
  * `outdir`
  * `cincludes`
  * `clibdir`
  * `clib`
  * `lib`
* replacement path of `nimscript.patchFile`

I think this documentation needs added:
* `docs/manual.rst`: mention that substitution is performed on import/include string literals
   and link to documentation
* `docs/nimc.rst`: list or annotate options subject to substitution and link to documentation
* `nimscript.patchFile`: mention substitution is performed and link to documentation

A testcase needs added that covers all of the substitutions.

This is an easy first issue.

**Comment by raynei86** [comment]
I'm assuming `$config` is the directory of module currently being compiled.
When I run `nim c --run foo/test.nim` with the contents
```nim
import "$config/bar"
```
The compiler will give the error: `cannot open file: /home/user/foo/bar`

Even if you put `nims` config files in places specified by [this doc](https://nim-lang.org/docs/nims.html), it doesn't seem to have any effects.
