### ISSUE TITLE
Table hashing fails on JS in browser.

### ISSUE THREAD

**Issue by Labdabeta** [nim-lang/Nim#19929]
Both the default and built-in user-defined hash functions cause the standard tables to fail when compiled for JS and run in the browser.
The circumstances where this occurs are a bit strange, in that it seems to only happen when the table is loaded in a procedure (pre-initializing result with `initTable[S, T]()` does not fix the issue).

Attempting to define my own hash function only works if it doesn't fall back on the builtin hash implementation. **NOTE**: Even with the "failing" hash function, the hashes are distinct when echoed with `echo xs[0].hash, xs[1].hash`.
Two workarounds (at the construction phase and the hashing phase) are presented as definable alternative compilations.

### First example
```nim
import std/[tables, hashes]

type Foo = object
    a: int

proc hash(f: Foo): Hash =
    when defined(workaround2):
        var h: Hash = f.a
    else:
        var h: Hash = 0
        h = h !& hash(f.a)
    result = !$h

proc transpose[T, S](data: array[T, S]): Table[S, T] =
    for i, x in data:
        result[x] = i

const xs = [Foo(a: 5), Foo(a: -5)]

when defined(workaround):
    var x : Table[Foo, int]
    x[Foo(a: 5)] = 0
    x[Foo(a: -5)] = 1
else:
    const x = transpose(xs)

echo x # Always works
echo x[Foo(a: -5)] # Fails in browsers
```

#### Linux x86/NodeJS
```
{(a: -5): 1, (a: 5): 0}
1
```

#### JS in Browsers
```
{(a: -5): 1, (a: 5): 0}
Uncaught Error: Error: unhandled exception: key not found: (a: -5) [KeyError]
```

### Expected Output
As seen on Linux/NodeJS (and likely others)

### Possible Solution

* This seems to somehow be a result of the hash function's behaviour on JS. 
* Some aspect of the transpose function seems to trigger the behaviour, perhaps when returning the table?

### Additional Information

Fairly new to Nim, could be misunderstanding expected behaviour.

```
$ nim -v
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-22
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by ghost** [comment]
As a workaround you can use `let` instead of `const` - it seems to me that this is the result of the difference of hash calculation during compile-time vs hash calculations in JS at runtime.

You create a table at compile-time, so the hashes are computed at compile-time, but then try to access the values at runtime, so the hash is different for some reason.

**Comment by ghost** [comment]
Aha, found another workaround - `-d:nimIntHash1`.  Maybe after that change the relevant JS hashing code wasn't updated to match the other backends.

**Comment by ghost** [comment]
Yeah, I think I found the root cause - in https://github.com/nim-lang/Nim/blob/devel/lib/pure/hashes.nim#L175 `when defined(js)` seems to be never true, even if we're compiling to the JS backend. I'm not sure if this is intended or a `nimvm` bug, but for it to work without a compiler change we need to rework this logic somewhat.

**Comment by ghost** [comment]
Okay, so the fix seems a bit wrong, but the root cause is that the compile-time hash for negative integers doesn't match the runtime hash when compiling to JS.

**Comment by bung87** [comment]
to reproduce, the workaround is avoiding use tables for js target, use jsobject is sufficient and effective.  
``` nim
import std/[tables, hashes]

type Foo = object
  a: int

proc hash(f: Foo): Hash =
  hash(f.a)

var x: Table[Foo, int]
x[Foo(a: 5)] = 0
x[Foo(a: -5)] = 1

echo x # Always works
echo x[Foo(a: -5)] # Fails in browsers
```
