### ISSUE TITLE
niminst: Order of platforms matters

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1993]
With these platforms:

```
[Project]
Platforms: """
  windows: amd64
  linux: amd64
  macosx: amd64
"""
```

settings for macosx (gcc options) are applied to all platform build scripts, so the script ends up not compiling on Linux because `-fasm-blocks` is not known.

**Comment by Varriount** [comment]
Could you please give a more in depth explanation of the problem?

**Comment by def-** [comment]
Make a new directory `project`. Inside create a `hello.nim` like this:
```nim
echo "Hello World"
```
And this `hello.ini`:
```
[Project]
Platforms: """
  windows: amd64
  linux: amd64
  macosx: amd64
"""
```
Run `niminst csource hello.ini`. Try to run the created `build.sh` on Linux and this error appears:
```
gcc -w -fasm-blocks -Ic_code -c c_code/2_1/hello.c -o c_code/2_1/hello.o
gcc: error: unrecognized command line option ‘-fasm-blocks’
```
You can see that `-fasm-blocks` is set in `$NIMDIR/config/nim.cfg` only for macosx and freebsd, but in our build script it still ends up being used for Linux. You can switch the order in the `hello.ini` like this:
```
[Project]
Platforms: """
  windows: amd64
  macosx: amd64
  linux: amd64
"""
```
And it works fine. In the `buildsh.tmpl` it's line 32 causing the problem:
```
COMP_FLAGS="?{c.ccompiler.flags}$extraBuildArgs"
```
Not sure how this should be solved ideally.

**Comment by Araq** [comment]
@Varriount 'installation' means the Nim installation is borked, it's not about 'niminst' (which should get its own repository!)

**Comment by andreaferretti** [comment]
Since `niminst` did get its own repo, should this issue be moved?

**Comment by narimiran** [comment]
> Since niminst did get its own repo, should this issue be moved?

bump

**Comment by Araq** [comment]
``niminst`` is now a Nim specific tool that can live on with this gotcha.
