### ISSUE TITLE
dynlib/exportc special character escaping does not work

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [nim-lang/Nim#19945]
Using escaped special characters for a function name, which is exported via `exportc, dynlib` results in a broken function name in the generated C-Code, as it's not escaped there:

Nim Compilation:
![image](https://user-images.githubusercontent.com/27858067/176525351-28fe7041-0df3-4a83-9495-3ab40ef3f398.png)

Generated C-Code:
![image](https://user-images.githubusercontent.com/27858067/176526482-2476ff7d-01fc-40ea-afe6-cfa6cc143981.png)

### Example
```nim
import winim
import dynlib
proc NimMain() {.cdecl, importc.}
proc `^/??@`(): BOOL {.stdcall,exportc, dynlib.} =
    NimMain()
    return true

discard `^/??@`()
echo "Hello world"
```

Doing the same without `exportc,dynlib` however does escape the characters correctly in the generated C-Code

Compilation:
![image](https://user-images.githubusercontent.com/27858067/176527702-4b7d3e53-dfd9-4ffe-86a4-4e0ce84a05a2.png)

Generated C-Code with correctly escaped characters:
![image](https://user-images.githubusercontent.com/27858067/176528001-e8f3e59e-0dc0-43c9-9eff-8e277bf48735.png)

### Expected Output

The same escaped function name in the C-Code even when using `exportc,dynlib`.

```
$ nim -v
Nim Compiler Version 1.6.6
```

**Comment by Araq** [comment]
This is not a bug, use `exportc: "nameHere"` to tell the compiler which external name to use, otherwise it uses the Nim name, no matter what it contains.

**Comment by S3cur3Th1sSh1t** [comment]
Thanks for the info!

So I tried
```
proc funcname(): BOOL {.stdcall,exportc: "^/??@".} =
```

now which results in the same behaviour. Also didn't find a solution yet on how to escape the characters in this string.

Passing `exportc` to the compiler as argument is not possible I guess? At least I didn't find anything about it in the DOCS.
