### ISSUE TITLE
OS library "execShellCmd" does not always allow command to finish before moving on

### ISSUE THREAD

**Issue by wreedb** [nim-lang/Nim#19951]
I was using execShellCmd() to run a perl command removing every quotation mark from a file, when I noticed, it would only write exactly 146 of the lines in the file before moving on with the rest of my program.

The reason I say doesn't _always_ is because you can mitigate this by avoiding nested func/proc calls that include an execShellCmd in them

Let's say _cmdProc_ contains an execshellcmd call, and it takes a parameter _fname_ of the filename it's operating on. I am used to writing in a functional style so my instinct was to call the func/proc which returns the filename that I need from inside a call to _cmdProc_, like this

```
cmdProc(otherProc())
```

However this will not give the desired result, as it will not allow for the execShellCmd to finish, and just move on. 

The only way I have been able to mitigate this is by declaring a variable and assigning it's value as the _otherProc_ and _**then**_ calling _cmdProc_ on that variable after.

```
let x: string = otherProc()
cmdProc(x)
```

At first i thought it was an issue with my perl command, but then I tried it with sed, and even just cat-ing a file with execShellCmd into another file seemed to be hard limited where when it hits 146 lines in the file, it will just move on from that call.

**Comment by Araq** [comment]
I've no idea what you're talking about but execShellCmd simply wraps system() and inherits all of its limitations. For a more powerful solution use something from `std / osproc`.
