### ISSUE TITLE
Compilation error with --app:lib

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#19964]
When compiling with app:lib and using anything that pulls os/paramStr a compilation error will occur.  

### Example
```nim
import compiler/scriptconfig
```

### Current Output
```

/nim-1.6.6/compiler/scriptconfig.nim(144, 10) template/generic instantiation of `cbconf` from here
/nim-1.6.6/compiler/scriptconfig.nim(145, 21) Error: undeclared identifier: 'paramStr'

```

### Expected Output
```
 gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
142057 lines; 3.091s; 348.879MiB peakmem; proj: /Volumes/Store/Projects/nimlab/nimscripttest/repro.nim; out: /Volumes/Store/Projects/nimlab/nimscripttest/librepro.dylib [SuccessX]
```

### Possible Solution

* Define paramStr and throw an exception is used at runtime. As it is done with other targets. 

### Additional Information
The issue is a stopper for using NimScript in dynamic libraries.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/19965
