### ISSUE TITLE
`reset` does not work on `set`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#19967]
```nim
type
  X = object
    a: string
    b: set[char]

var y = X(b: {'a'})

reset(y)

doAssert y.b == {}
```
nim 1.6.6
https://play.nim-lang.org/#ix=41uB

**Comment by ringabout** [comment]
Works with arc/orc. I'm looking into it.

**Comment by ringabout** [comment]
Made a quick dirty patch in ccgreset.nim

```nim
  of tySet:
    lineCg(p, cpsStmts, "#nimZeroMem($1, sizeof($2));$n",
        [accessor, getTypeDesc(p.module, typ)])
```

I will consider the size of the set afterwards when I make my PR.

**Comment by ringabout** [comment]
Works in 1.2.0, se also https://github.com/nim-lang/Nim/pull/14398
