### ISSUE TITLE
execCmd returns the incorrect value on macos

### ISSUE THREAD

**Issue by danielclarke** [nim-lang/Nim#19962]
proc execCmd returns the incorrect value on macos

### Example
```nim
import osproc

proc main =
  echo execCmd("exit 1")

main()
```

### Current Output
```
echo execCmd("exit 1") -> 256
echo execCmd("exit 2") -> 512
```

### Expected Output
```
echo execCmd("exit 1") -> 1
echo execCmd("exit 2") -> 2
```

### Possible Solution

change the `when defined(linux)` in `execCmd` to `when defined(posix)`

I have a PR with this change and tests

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/19963
