### ISSUE TITLE
The changelog.md file is missing in the release tarball

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#19997]
[changelog.md](https://github.com/nim-lang/Nim/blob/devel/changelog.md) and the previous files are not found in https://nim-lang.org/download/nim-1.6.6-linux_x64.tar.xz

**Comment by ringabout** [comment]
[changelog.md](https://github.com/nim-lang/Nim/blob/devel/changelog.md) doesn't always  reflect the correct changes, and the `changelogs` directory can be shipped instead.
