### ISSUE TITLE
Migration to v2

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#20017]
## Cannot cast ref to RootRef in Arc/Orc

affected important packages: 
- [x] https://github.com/yglukhov/nimsl  https://github.com/nim-lang/Nim/issues/20016

**Solution**

```nim
type
  Color = ref object

var x = Color()
let y = cast[pointer](x)
# use Gc_ref(y) when it is needed
```

## shallowCopy/shallow

- [x] https://github.com/andreaferretti/cello https://github.com/nim-lang/Nim/issues/20015

**Solution**

`shallowCopy`/`shallow` becomes a compile-time error with ARC/ORC. `move` seqs/strings instead. 

```nim
proc main()
  var x = "123"
  var y = move(x)
```

You can also use `sink` to let the compiler decide whether to move the data or copy the data.

```nim
proc main(x: sink string) =
  var y = x
```

Another solution is to use `{.cursor.}`.

## deepcopy
- [x] https://github.com/def-/nim-iterutils/pull/15
- [x] https://github.com/moigagoo/norm/pull/155

**Solution**

Enable deepcopy for ARC/ORC. Use `--deepcopy:on`. Note that the option appears since 1.4.0 and it is ignored with refc.

## cannot bind another destructor to ref object

https://github.com/nim-lang/Nim/issues/19231

affected important packages: 
- [ ] https://github.com/Vladar4/nimgame2

**minimal testcase**
```nim
type
  A = ref object

var x1: A
new(x1, proc (x: A) {.nimcall.} = discard)
var x2: A
new(x2, func (x: A) {.nimcall.} = discard)
```

## {.global.} pragma doesn't work when the variable is initialized with non-value types

https://github.com/nim-lang/Nim/issues/17552

**Solution**

None

## threadpool doesn't work with ORC

**Solution**

Switch to https://github.com/status-im/nim-taskpools or use createThreads.

## Mixing declarations and statements at the top level causes undefined behaviour

https://github.com/nim-lang/Nim/issues/19795

affected important packages: 
- [x] https://github.com/zero-functional/zero-functional

**Solution**

None.

Workaround: move the top level statements to the main procs.

## defaults to ORC
https://github.com/nim-lang/Nim/pull/19972

## stricteffects

`experimental:stricteffects` is enabled for v2. There is a switch `--legacy:laxeffects` to keep backwards compatibility with old behaviors.

ref https://github.com/nim-lang/Nim/issues/19303
ref https://github.com/nim-lang/RFCs/issues/435

**Comment by exelotl** [comment]
Hey, is this the right place to report that programs using [nimPNG](https://github.com/jangko/nimPNG) don't compile on devel?

shallowCopy usage:
https://github.com/jangko/nimPNG/blob/master/nimPNG/buffer.nim

**Comment by ringabout** [comment]
> Hey, is this the right place to report that programs using [nimPNG](https://github.com/jangko/nimPNG) don't compile on devel?

I think you probably need to open an issue on the issue track of `nimPNG` and link this issue. `sink` parameters seems to be good enough.
