### ISSUE TITLE
cmp with enum result

### ISSUE THREAD

**Issue by rotu** [nim-lang/Nim#20028]
### Summary

Replace the return value of `cmp` with an `enum`.
The result of `cmp` is an integer, which prevents using a `case` statement.

### Description
Replacing the magic numbers of `cmp` with an enum results in more natural code, and the compiler can check that the case statement is exhaustive.

In the below code, for example, accidentally omitting a case results in an error like:
> /usercode/in.nim(5, 3) Error: not all cases are covered; missing: {<}

```nim
type
  Cmp = enum `<`,`=`,`>`

proc foo(a, b: int) =
  case cmp(a, b)
    of `<`:
      # ...
    of `=`:
      # ...
    of `>`:
      # ...
```
### Additional Information
* See `binarySearch`, where this would improve readability https://github.com/nim-lang/Nim/blob/9508b06513b170ffbe91cfcfcd7ca09fa9b675cc/lib/pure/algorithm.nim#L155

**Comment by hamidb80** [comment]
I think this is a better idea:
```nim
ComparisonResult = enum
  Smaller = -1
  Equal = 0
  Greater = +1
```

**Comment by Araq** [comment]
Pointless code breakage, rejected.

**Comment by rotu** [comment]
@Araq of course this can be done without breakage - e.g. introduce a `comp` function that returns an enum and have its default implementation wrap `cmp`. Or define a `converter` so the comparison result can implicitly decay to an `int`.

This is not pointless. It's the same reason we have `bool` instead of using int everywhere to represent truth values.
