### ISSUE TITLE
IPv6 support for httpserver on Windows

### ISSUE THREAD

**Issue by ayourtch** [nim-lang/Nim#2003]
Currently looks like httpserver is IPv4-only.

I've forked and started a branch to experiment with adding IPv6 support, trying to be backwards compatible.

Feedback welcome:

https://github.com/ayourtch/Nim/commits/ipv6

**Comment by dom96** [comment]
That looks pretty good. Keep in mind though that both the ``httpserver`` and ``sockets`` modules are deprecated. What you should use is ``asynchttpserver`` and ``net``.

**Comment by ayourtch** [comment]
Oh, okay, thanks! I've just started learning Nim today using various examples - so did not play with the asynchttpserver and net yet, will take a further look over the weekend.

**Comment by Araq** [comment]
Please make a proper PR. Closing it since no bug.

**Comment by dom96** [comment]
I disagree. This is a bug.

**Comment by Araq** [comment]
but httpserver is already deprecated?

**Comment by dom96** [comment]
It affects ``asynchttpserver`` too.

**Comment by ayourtch** [comment]
Coming back to this after a long silence...

Following Dominik's recommendation to look at asynchttpserver instead, I finally made a sizable chunk of code that can be used as a testbench (a HTTP server using Jester + UDP server listening for mDNS and decoding packets), and tried to toy further with IPv6 support using that code as a consumer of the library.

Turns out if I add a "getSockDomain" function into rawsockets which returns a Domain of the socket, then most of the obvious changes for the server side can be contained in bindAddr:

https://github.com/ayourtch/nimstdlib/commit/951fda13b2a597a4f3c0ce455f07271b0075016f?diff=split

In that commit I also deleted the special-case for address == "" since getaddrinfo handling seems to be happy with processing "0.0.0.0"  (this might have been too aggressive as maybe it is not the case on all systems ? The whole chunk of code comes from https://github.com/nim-lang/Nim/commit/bb1e87ce4d3e3e81e65609354667e5ed860f02c8 with no hint on why there's a special-case for addr = "" vs. using "0.0.0.0"+getaddrinfo).

Then with another small change which makes AsyncSocket dualstack:

https://github.com/ayourtch/nimstdlib/commit/9b39e9f3aa52f7b1440b613785eb99a1b9913df1

...Jester is happily answering on the dualstack socket!

Though that last change looks a bit drastic - but given my limited experience with Nim I'm not sure of a good way to make the AsyncSocket dualstack by default system-wide rather than changing its constructor... But then, having a dualstack default early could be beneficial to avoid IPv4-only code.

Would love to hear feedback/thoughts.

**Comment by dom96** [comment]
Looks pretty good. But it needs to be against the ``devel`` branch not the ``master`` branch. Please make a PR and I will review it.

**Comment by ayourtch** [comment]
Thanks! By looking at asyncdispatch.nim, such a default change will impact connect() and acceptAddr() - both of which still use Sockaddr_in which is IPv4-only, so I had to do a few more code changes. The result seems to be relatively backwards compatible despite of the default change of AF_INET into AF_INET6.

https://github.com/nim-lang/Nim/pull/2976

**Comment by dom96** [comment]
PR #2976 merged but it implements IPv6 support for POSIX only, keeping this open until Windows support lands.

**Comment by ayourtch** [comment]
Thanks a lot for merging! And makes sense to keep this one open. While it is, I will do more testing on POSIX - and if I find anything else is it ok to reference the additional PRs still here ?

**Comment by dom96** [comment]
Yes.

**Comment by ayourtch** [comment]
My suspicion was rawsockets.getSockName which has some Sockaddr_in in it, but the tests show it indeed returns the correct port on both Linux and OSX - so I assuming "if it ain't broke, don't fix it", all clear from my side.

**Comment by Araq** [comment]
We now support IPv 6 everywhere via the ``dial`` proc.

**Comment by dom96** [comment]
Does asynchttpserver support it?
