### ISSUE TITLE
Documentation: website needs source about the MinGW release package

### ISSUE THREAD

**Issue by josephernest** [nim-lang/Nim#20036]
Hi!
On this page https://nim-lang.org/install_windows.html, we are recommended to install this MinGW64 package:

> The following versions of MinGW are known to work with the latest version of Nim:  
> 64 bit - [mingw64.7z](https://nim-lang.org/download/mingw64.7z) ([SHA256](https://nim-lang.org/download/mingw64.7z.sha256))

Could we include some information/link about where this binary release comes from? about the build process, etc.
It would be useful for future reference. I guess it comes from https://www.mingw-w64.org/downloads/, but which version more precisely: msys2 or mingw64-builds, if so who does this binary release?

Thanks

**Comment by Araq** [comment]
https://github.com/Araq/nimrelease/blob/master/nimrelease.nim#L12-L16

The Nim team (me included) do the releases.

**Comment by josephernest** [comment]
Thank you @Araq. Do you mean, it is directly the package distributed from Brecht Sanders or do you rebuild it based on source from https://github.com/brechtsanders/winlibs_mingw or https://winlibs.com/?

I ask these questions because I'm trying to understand the full big picture of all Mingw-based C++ compilers available on Windows: 

* "Mingw-w64-builds" (available on [MingW-W64-builds](https://www.mingw-w64.org/downloads/#mingw-builds)), 
* Msys2 (which is a nearly 10 times bigger package, requiring to use pacman etc.), 
* WinLibs/Brecht Sanders's releases, 
* and also your releases (if different from the previous ones)

Thanks :)

**Comment by Araq** [comment]
It is the package as distributed by Brecht Sanders. We merely mirrored it on our server. We did not build from source.
