### ISSUE TITLE
Improve documentation for compiler

### ISSUE THREAD

**Issue by mavavilj** [nim-lang/Nim#20032]
### Summary

I want to learn how the Nim compiler works in order to understand what the computer does when I use Nim. When reading this document https://nim-lang.org/docs/intern.html#the-compiler-s-architecture I can find some information, but compared to the compiler docs of Rust at https://rustc-dev-guide.rust-lang.org/ the Nim docs seem pathetical. This actually motivates me to not continue using Nim, because it gives an unprofessional impression just like a library that has a lot of undocumented code.

### Description

I hope that the documents for the compiler could be made more like that of https://rustc-dev-guide.rust-lang.org/ or https://gcc.gnu.org/onlinedocs/gccint/.

### Alternatives

The docs are not improved and users of Nim language treat the compiler just as a black box without understanding how it works.

**Comment by Araq** [comment]
I'm so sorry the compiler's code base doesn't manage to motivate you to continue using Nim.

**Comment by mavavilj** [comment]
So is there any chance the documentation would improve?

**Comment by Araq** [comment]
Sure, if you create a PR. It's open source. It works by contributions not by telling us what to do.

**Comment by mavavilj** [comment]
Yes, but the compiler is obviously best understood by who designed it.

**Comment by Araq** [comment]
And I'll review the PR, don't you worry.
