### ISSUE TITLE
Make `random.rand` work with `Ordinal`

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#20042]
### Summary
`rand(EnumName.low .. EnumName.high)` --> `rand(EnumName)`

### Description
```nim
type SpriteKind = enum
  car
  truck
  bus
  taxi
  bike

# get a random sprite
foo(rand(SpriteKind.low .. SpriteKind.high))
# much like rand(uint), rand(int8) ...
foo(rand(SpriteKind))

# Also useful for a random character or bool
let randChar = rand(char)

```

### Alternatives
replace `SomeInteger` with `Ordinal`
https://github.com/nim-lang/Nim/blob/60dd38c50262774cadb1d365e649696380c0595e/lib/pure/random.nim#L356

**Comment by Araq** [comment]
PR please

**Comment by AmjadHD** [comment]
https://github.com/nim-lang/Nim/blob/60dd38c50262774cadb1d365e649696380c0595e/lib/pure/random.nim#L369-L374
Should I change these like so: `rand(int8) in low(int8) .. high(int8)`
