### ISSUE TITLE
`+=` with `if` expression

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#20040]
### Example
```nim
var a: int
a = if true: 1 else: 0
a += (if true: 1 else: 0)
a += if true: 1 else: 0 # Error: expression expected, but found 'keyword if'
```

### Current Output
```
Error: expression expected, but found 'keyword if'
```

### Expected Output
Compiles without error

### Additional Information
Tried with all nim versions

**Comment by hamidb80** [comment]
`=` represents a "assign statement", on the other hand, every other infix operators like `=+` , `==`, ... Is parsed as "infix" 


By the way, I use this:

```nim
+= a:
  if true: 1
  else: 0

```

**Comment by metagn** [comment]
The grammar just doesn't include this syntax. `=` has special treatment but `+=` is treated the same as any other operator like `+`, it does not support crazy operands like `if`. Even if it did, it could only support them on the right hand side, which is hard to reason about. Maybe the error message could be changed to "simple expression expected".
