### ISSUE TITLE
`repr` produces invalid code when a proc has an empty body

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#20044]
The `repr` function produces invalid code for `proc`s with an empty body which are common in FFI bindings, eg. `proc p() {.importc: "p".}`

### Example
```nim
import macros

static:
  let pRepr = newProc(name = ident("p")).repr
  echo pRepr
  discard parseStmt(pRepr)
```

### Current Output
```
$ nim c -r --verbosity\:0 --hint\[Processing\]\:off --excessiveStackTrace\:on /tmp/test.nim
proc p() =
  
stack trace: (most recent call last)
/tmp/test.nim(6, 20)     test
/home/deech/Nim/lib/core/macros.nim(542, 17) parseStmt
/home/deech/Nim/lib/core/macros.nim(542, 17) Error: unhandled exception: (2, 3) Error: invalid indentation [ValueError]
```

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-07-11
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: fb5fbf1e087563f0288b8ed684c8dcc1891730b0
active boot switches: -d:release
```

**Comment by metagn** [comment]
> The repr function produces invalid code for procs with an empty body which are common in FFI bindings, eg. proc p() {.importc: "p".}

This is incorrect, those are rendered correctly. `newProc` here without a body argument sets the body to an empty statement list, which doesn't have a proper render. Procs like `proc p() {.importc: "p".}` have an `nnkEmpty` body, while the invalid body is `nnkStmtList`.

**Comment by deech** [comment]
You're right! Closing.

**Comment by metagn** [comment]
I think it's still a valid complaint, maybe empty statement lists should render as `(;)` or something (despite this meaning `nnkStmtListExpr`), or `newProc` should not initialize with invalid AST by default (despite maybe some macros relying on this).
