### ISSUE TITLE
branch version-1-6 cannot be built by csources_v1 due to recent bad commit

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#20056]
Because of [this commit](https://github.com/nim-lang/Nim/commit/3fd11d7e96aaa654795a4e14eb6becd22f5294f1),
when building branch `version-1-6` using csources_v1 will produce following error message:

```text
...
Hint: depends [Processing]
/home/jangko/build/nim/compiler/depends.nim(73, 80) Error: undeclared identifier: 'belongsToStdlib'
FAILURE
```

**Comment by narimiran** [comment]
The `belongsToStdlib` func was added in [this PR](https://github.com/nim-lang/Nim/commit/d30c6419a051a815e3fdb354ac79522f17e55bda#diff-0c173bd488fe9ea567c0baf93d6e1220d58068cfe93c8c39b8c8ec43d5c09187R611), which was not backported to the 1.6 branch.

I'll backport it now.

**Comment by jangko** [comment]
I can confirm branch version-1-6 now can be built by csources_v1 binary successfully. thank you for your hardwork. close
