### ISSUE TITLE
Manual misdocuments `func`'s syntax-sugarness for `proc`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#20074]
https://nim-lang.org/docs/manual.html#procedures-func states
> The `func` keyword introduces a shortcut for a `noSideEffect`:idx: proc.
>
>  `func binarySearch[T](a: openArray[T]; elem: T): int`
>
> Is short for:
>
> `proc binarySearch[T](a: openArray[T]; elem: T): int {.noSideEffect.}`

While this mostly explains the semantic effects of `func`, templates and macros which care about the AST cannot rely on this.

### Example
```nim
import std/macros

dumpAstGen() do:
  func f() = discard

dumpAstGen() do:
  proc f() {.noSideEffect.} = discard
```

displays
```
nnkStmtList.newTree(
  nnkFuncDef.newTree(
    newIdentNode("f"),
    newEmptyNode(),
    newEmptyNode(),
    nnkFormalParams.newTree(
      newEmptyNode()
    ),
    newEmptyNode(),
    newEmptyNode(),
    nnkStmtList.newTree(
      nnkDiscardStmt.newTree(
        newEmptyNode()
      )
    )
  )
)
nnkStmtList.newTree(
  nnkProcDef.newTree(
    newIdentNode("f"),
    newEmptyNode(),
    newEmptyNode(),
    nnkFormalParams.newTree(
      newEmptyNode()
    ),
    nnkPragma.newTree(
      newIdentNode("noSideEffect")
    ),
    newEmptyNode(),
    nnkStmtList.newTree(
      nnkDiscardStmt.newTree(
        newEmptyNode()
      )
    )
  )
)
```

That is, one is an `nnkFuncDef`, while the other is an `nnkProcDef`. https://nim-lang.org/docs/macros.html documents this clearly enough, but also therefore contradicts the language manual.

Tested with
```
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-14
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
and
```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-07-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 1a9123eb90db68d037b5ba5ad11fa0e8534b83c8
active boot switches: -d:release
```

### Possible Solution

More precisely and guardedly phrase the Nim manual's characterization of `func`. It's probably better, and certainly more compatible with existing Nim, to keep the current AST representation and allow macros to operate with full AST information, so this issue is not suggesting any change in Nim semantics, but rather that the `func` description reads as if it's solely syntax sugar, when it's not.

**Comment by Araq** [comment]
The manual doesn't mention a func's AST so it's not wrong either.

**Comment by tersec** [comment]
Fair enough.
