### ISSUE TITLE
`nimble test` is broken with ORC

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#20099]
```
git clone https://github.com/treeform/netty
cd netty
nim c -r --mm:orc ../nimble.nim test
```

**Comment by ringabout** [comment]
It is actually an issue regarding global pragmas plus ORC.

Related code:

```nim
  var pkgList {.global.}: seq[tuple[pkginfo: PackageInfo, meta: MetaData]] = @[]
  once: pkgList = getInstalledPkgsMin(options.getPkgsDir(), options)
```

**Comment by bung87** [comment]
this is fixed in fdc8dd41288c78052c21796b7e65e37cba71d316

**Comment by ringabout** [comment]
=> https://github.com/nim-lang/Nim/pull/20780

**Comment by ringabout** [comment]
Probably not, CI failed => https://github.com/nim-lang/Nim/pull/20780

**Comment by bung87** [comment]
hmm , so the commands can't verify this. I used it locally works fine.

**Comment by ringabout** [comment]
It seems to work now. ref https://github.com/nim-lang/Nim/pull/20780
