### ISSUE TITLE
Compiler hint/warning for failing sink defaulting to copy (move semantics)

### ISSUE THREAD

**Issue by ayman-albaz** [nim-lang/Nim#20096]
I was watching araqs talk on move semantics. Specifically this part: https://youtu.be/zPlBZkWvuug?t=625

TLDR: The video shows that the compiler hints `Passing copy to a sink parameter` when a variable it used after being passed to a function with a sink parameter.

I tried reproducing his output with
```nim
import tables, hashes

func put(t: var Table; key: string; value: sink seq[int]) =
  var h = hash(key)
  t[h] = value

proc main() =
  var tab = initTable[Hash, seq[int]]()
  var values = @[1, 2, 3]
  tab.put "key", values
  echo values

main()
```
`nim --mm:arc c -r test.nim`
(Tried this on 1.6.2, stable and devel)

But I'm not getting the warning error message that he got that. After looking for the warning in the nim source code, I was unable to find it, so this is why I'm putting this as a feature request and not a bug.

IMO, it would be extremely helpful to verify that my sinks are not useless.

**Comment by Araq** [comment]
The code still exists in the compiler:

```nim

      message(c.graph.config, n.info, hintPerformance,
        ("passing '$1' to a sink parameter introduces an implicit copy; " &
        "if possible, rearrange your program's control flow to prevent it") % $n)
```

And should trigger.

**Comment by ayman-albaz** [comment]
You're correct!
I needed to run `nim --mm:arc --hint[Performance]:on c -r test.nim` to get the hint.

Thanks to ElegantBeef from discord for pointing this out.
