### ISSUE TITLE
Typed `const` AST deletes pragmas

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#20114]
Might be a duplicate. In any case, I know and have the fix for this, just opening to document.

### Example
```nim
import macros

expandMacros:
  # any pragma, not just strdefine
  const foo {.strdefine.} = "abc"
```

### Current Output
```
const
  foo = "abc"
```

### Expected Output
```
const
  foo {.strdefine.} = "abc"
```

### Possible Solution

I am about to PR the solution. [Bad line](https://github.com/nim-lang/Nim/blob/528b6d1c3f001944a7a7754c8884178e365e6871/compiler/semstmts.nim#L805)

```
$ nim -v
Nim Compiler Version 1.7.1
528b6d1c3f001944a7a7754c8884178e365e6871
```

**Comment by Menduist** [comment]
Linked https://github.com/nim-lang/Nim/issues/19766
