### ISSUE TITLE
Replace wide string copying techniques with in-place string translation

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#2012]
Many places in the stdlib interface with the Windows API, where most Windows API procedures dealing with strings have wide character and ANSI versions. Currently, most of the Windows API calls that accept a wide string are given an array of int16's, which, after the call is finished, is converted and copied into a regular string. 

A more efficient technique would be to pass the Windows API procedures the address to the first character of a regular string, and then do an in-place decoding of the string's data (which is in a wide character format) to regular utf8.

Pseudocode example:

``` nimrod
proc foo: string =
  result = newStringOfLen(64)
  someWindowsCall(addr result[0])
  translateToUtf(result)
```

**Comment by Araq** [comment]
Would not help, internally Windows uses the W versions of its routines.
