### ISSUE TITLE
SomeNumber != SomeInteger|SomeFloat 

### ISSUE THREAD

**Issue by o5k4r** [nim-lang/Nim#20136]
The compiler expects the second parameter to be the same type as it encounters it for the first parameter, but only if the type is defined explicitly. 

### Example
```nim
proc test(a: SomeInteger|SomeFloat, b: SomeInteger|SomeFloat) = echo a, ", ", b
#proc test(a: SomeNumber, b: SomeNumber) = echo a, ", ", b
#proc test(a, b: SomeNumber) = echo a, ", ", b
#proc test(a, b: SomeInteger|SomeFloat) = echo a, ", ", b

test 1, 1.0  

```

The second and third function in the example throws following error ...

```nim
# <int literal(1), float64>
# but expected one of: 
# proc test(a: SomeNumber; b: SomeNumber)
#   first type mismatch at position: 2
#   required type for b: SomeNumber
#   but expression '1.0' is of type: float64
```
The fourth function works again as expected, which let me assume this is not intended behaviour. 

```
$ nim -v
Nim Compiler Version 1.6.6
```

**Comment by beef331** [comment]
There is a slightly tricky feature that named typeclasses use, any usage of them expects the same type as such the following works(distinct overrides that logic):
```nim
proc test(a, b: distinct SomeNumber) = echo a, ", ", b
test 1, 1.0
```
The reason this binding happens is for things like
```nim
proc doThing(s: seq[SomeNumber]): SomeNumber = s[0]
```
This is documented [here](https://nim-lang.org/docs/manual.html#generics-implicit-generics)

**Comment by o5k4r** [comment]
Slightly tricky is the right phrase. 

I created a type Number which does the job just fine ...

```nim
type 
  Number = distinct SomeNumber
  #Number = distinct SomeInteger or distinct SomeFloat
  #Number = distinct SomeInteger or SomeFloat
  #Number = distinct (SomeInteger or SomeFloat)

proc test(a, b: Number) = echo a, ", ", b

test 1, 1.0  
```
Again, the second and third option won't compile but the fourth is fine again.

OT: While playing around I found the following curiosity, which sends the compiler into an infinte loop ...

```nim
  type SomeNumber = distinct SomeNumber
```

Anyway, thanks for pointing out how to use distinct. Let's close that issue?
