### ISSUE TITLE
On js backend, same pattern repeated hundred of times

### ISSUE THREAD

**Issue by piertoni** [nim-lang/Nim#20186]
### What happened?

Implementing a really simple nim program that uses dom, I noticed the same pattern generated hundred of times.
Note: **The program is working as expected**, but I thought that there could be a code generation issue.
 
In particular the following is generated more or less 200 times in the output javascript file.
```javascript
var F = {procname: "module dom", prev: framePtr, filename: "/home/user/.choosenim/toolchains/nim-1.6.6/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
```
This one (my module) is just repeated 3 times:
```javascript
var F = {procname: "module provajs", prev: framePtr, filename: "/home/user/Dropbox/programmazione/nim/provajs/src/provajs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
```

### Nim Version

Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0565a70eab02122ce278b98181c7d1170870865c
active boot switches: -d:release

### Additional Information

The actual source code is:
```nim
import dom

proc clicked(ev: Event) =
  echo "clicked"

proc ready(ev: Event) =
  var b1 = document.getElementById("b1")
  b1.addEventListener("click", clicked)


when isMainModule:
  document.addEventListener("DOMContentLoaded", ready)
```

**Comment by ringabout** [comment]
They are used to generate nice stacktraces for debugging purpose. Try `-d:release`.
