### ISSUE TITLE
Opening a number of DB connections with db_postgres can crash the program

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#20231]
### What happened?

I've attached a program that opens and closes 100 DB connections with db_postgres. Most of the time it fails for me, the program aborts.

If I use a lock around the open() call to open the DB connection it works every time. However such a lock would be better placed in the db_postgres module to save others from this problem.

The same issue could also apply to db_sqlite and db_mysql.

I wrote this minimal test case because I found that DB queries were sometimes being corrupted in a larger program.

[data_race_db_conn_test.zip](https://github.com/nim-lang/Nim/files/9337583/data_race_db_conn_test.zip)

### Nim Version

1.6.6

### Current Standard Output Logs

```shell
Traceback (most recent call last)
...\.choosenim\toolchains\nim-1.6.6\lib\pure\concurrency\threadpool.nim(368) slave
...\db_conn_data_race_test.nim(40) dbThreadWrapper
...\db_thread.nim(7) dbThread
...\.choosenim\toolchains\nim-1.6.6\lib\impure\db_postgres.nim(637) open
SIGABRT: Abnormal termination.
```

### Expected Standard Output Logs

```shell
No SIGABRT.
```

### Possible Solution

Use a lock in db_postgres' open() proc, and possibly for db_sqlite and db_mysql too.

**Comment by Araq** [comment]
Nim wraps the C libraries and is not responsible for bugs and omissions in the C libs. Nor does it add thread safety.

**Comment by jfilby** [comment]
OK I've added a lock to the Nexus framework for this purpose then.
