### ISSUE TITLE
Can't isolate an object with a DateTime field

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#20239]
### What happened?

Here's my test:

```Nim
import times
import std/isolation

type
  Test* = object
    d*: DateTime

# Main
var test = Test()
let isoTest = isolate(test)
```

Compile fails with: `Error: expression cannot be isolated: notificationMsg`

Other field types work fine, but I can't isolate an object with a DateTime field.

### Nim Version

1.6.6

### Additional Information

For context, I'm trying to send a message with threading/channels. However, the send() call for one message type fails, which contains DateTime fields. The error is `Error: expression cannot be isolated`.

I could convert the DateTime fields to ints with toUnix(), but this means having to create an extra object every time and convert the DateTime fields to/from ints on each side of the channel.

**Comment by treeform** [comment]
This is a design issue - DateTime has pointers to functions and other things that can't be isolated, serialized or converted to json.

Your best bet is to never hold on or transfer DateTime object but only use it in computations. Better to always use a unix timestamp and if you need timezone name pair.

This and other issues with DateTime led me to write my own Timestamp/Calendar/Timezone library: https://github.com/treeform/chrono

In my library I made sure everything can be serialized and isolated.

**Comment by jfilby** [comment]
> This is a design issue - DateTime has pointers to functions and other things that can't be isolated, serialized or converted to json.

Thanks! Does that mean that objects with DateTime would have memory issues with stdlib channels? Because that's what I seemed to be seeing. The new channels gives this isolate error.

**Comment by ringabout** [comment]
I haven't checked the detail. Workaround is to pass object construction directly
```nim
import times
import std/isolation

type
  Test* = object
    d*: DateTime

# Main
let isoTest = isolate(Test())
```

**Comment by treeform** [comment]
@ringabout that looks like a bug.

See here DateTime includes Timezone: https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/times.nim#L310

Timezone includes callbacks: https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/times.nim#L359-L367

I don't think you can isolate callbacks.

**Comment by ringabout** [comment]
TimeZone is a ref object, according to the speciation. ref object cannot be isolated unless using object construction directly.

**Comment by Araq** [comment]
Not a bug. But I agree it's bad.
