### ISSUE TITLE
How to extract text from double-hash documentation comment

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#2024]
I would like my code to extract double-hash documentation comments and use them for introspection documentation.  However, I can't work out how to extract the comment text in my code. I can't access any internal structure in the nnkCommentStmt node, and I can't find any procs (outside the Nim compiler code) that handle nnkCommentStmt nodes.

Is it possible for non-compiler (non-docgen) code to extract the text of double-hash documentation comments?  If so, could the appropriate procs/macros be documented?

**Comment by Araq** [comment]
yup, that's currently impossible

**Comment by Araq** [comment]
That has been implemented. You can use ``strVal`` to access the comment.
