### ISSUE TITLE
strutils.nim(954, 13) Warning: target type is larger than source type [CastSizes]

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#20244]
### What happened?

I am talking about examples from https://github.com/khchen/winim/tree/master/examples/clr

when I compile winim-master\examples\clr\simple_gui.nim with nim 1.7.1, the message says
```bash
E:\msys64\home\USER\_nim\nim\lib\pure\strutils.nim(954, 13) Warning: target type is larger than source type [CastSizes]
```

### Nim Version

latest cloned-and-compiled nim 1.7.1

```
$ nim -v
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-08-16
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: https://github.com/nim-lang/Nim/commit/9f408ea9430b104eb6c14a84d7a1650bf115b6a0
active boot switches: -d:release
```

### Expected Standard Output Logs

```shell
there is no such information

E:\msys64\home\USER\_nim\nim\lib\pure\strutils.nim(954, 13) Warning: target type is larger than source type [CastSizes]
```

### Additional Information

I don't know whether this is porblem in nim or winim, but since the indicated file is nim's lib, I report it as a bug here.

**Comment by ringabout** [comment]
related 
https://github.com/nim-lang/Nim/issues/19101
https://github.com/nim-lang/Nim/pull/20103
