### ISSUE TITLE
Default gc causes undefined behavior with setLen on an nil seq.

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#20278]
### What happened?

UBSan complains with the following snippet:

```nim
proc main =
  var x: seq[byte] # = @[]
  x.setLen(10)
  echo x

main()
```

### Nim Version

Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-08-27
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 16f6dc05fdb2e1ca3086936c15c2ad3de542d991
active boot switches: -d:release --gc:markAndSweep

### Current Standard Output Logs

```shell
t.nim:3:66: runtime error: member access within null pointer of type 'tySequence__6H5Oh5UUvVCLiakt9aTwtUQ' (aka 'struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior t.nim:3:66 in 
@[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

### Additional Information

Same pattern is used in json.initFromJson

Compile with:

```
nim c --cc:clang --threads:off -d:useMalloc -t:"-fsanitize=address,undefined" -l:"-fsanitize=address,undefined" -d:nosignalhandler -d:release -g t
```

**Comment by ringabout** [comment]
Works on the devel branch, but not with 1.6.12 in refc.
