### ISSUE TITLE
attempting to call undeclared routine: 'case'

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#20283]
### What happened?

Compiler report `ttempting to call undeclared routine: 'case'` for this code snippet
```nim
case @[]
else: discard
```

### Nim Version

Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-08-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: ee11302c2493795c630b080fe3dd7ea7721a9fdc
active boot switches: -d:release

### Current Standard Output Logs

```shell
test.nim(1, 1) Error: attempting to call undeclared routine: 'case'
```

### Expected Standard Output Logs

```shell
test.nim(1, 6) Error: selector must be of an ordinal type, float or string
```

### Additional Information

Versions prior 1.7 work as expected.

**Comment by ringabout** [comment]
related https://github.com/nim-lang/Nim/issues/19682

**Comment by Araq** [comment]
If you use a non-supported type for `case` then case statement macros are tried and the macro's name shall be `case`. No bug here but the error message could be better I guess.

**Comment by derekdai** [comment]
Thank you for the explanation.
