### ISSUE TITLE
Tests fail in 2038

### ISSUE THREAD

**Issue by bmwiedemann** [nim-lang/Nim#20285]
### What happened?

As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our `nim` package build.
See https://reproducible-builds.org/ for why this matters.

### Nim Version

nim-1.6.6

### Current Standard Output Logs

```shell
[Suite] inet_ntop tests
 megatest:processing: [469] tests/stdlib/tnre.nim
 megatest:processing: [470] tests/stdlib/toids.nim
 oids.nim(82)             oids
 fatal.nim(53)            sysFatal
 Error: unhandled exception: value out of range: 2168246819 notin -2147483648 .. 2147483647 [RangeDefect]
```
```


### Expected Standard Output Logs

_No response_

### Possible Solution

Ensure timestamps are processed as 64-bit values.

### Additional Information

_No response_

**Comment by Araq** [comment]
OIDs were defined to use 32bit timestamps, there is not much we can do about it except deviating from the spec which was originally taken from MongoDB.

**Comment by bmwiedemann** [comment]
You could also follow python (.pyc file timestamps) and define it as `timestamp&0xffffffff` as long as it does not need to be continuously increasing.

**Comment by bmwiedemann** [comment]
See also the fix for OIDs in BSON: https://github.com/py-bson/bson/pull/117/files

**Comment by ringabout** [comment]
@bmwiedemann How does the test look like? I probably need to set one for Linux in https://github.com/nim-lang/Nim/pull/20338 Thank you in advance!
