### ISSUE TITLE
Final facelifiting nimrod -> nim

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2032]
Any chance to get this down to zero?

```
grep -i nimrod **/*.nim | wc -l
332
```

**Comment by dom96** [comment]
Create a PR?

**Comment by Varriount** [comment]
I've got a local branch with the icons renamed, fyi

**Comment by reactormonk** [comment]
@dom96 I considered just running a `sed`, but it will break any macro-related code.

**Comment by Araq** [comment]
Make PRs please. ;-) And as you noticed renaming PNimrodNode is quite some work.

**Comment by Araq** [comment]
PNimrodNode is now NimNode.

**Comment by reactormonk** [comment]
cd compiler
    git grep -i nimrod | wc -l
    50

still work to be done.

**Comment by TiberiumN** [comment]
In compiler:
$ grep -i nimrod **/*.nim | wc -l
1
In whole nim repository:
$ grep -i nimrod **/*.nim | wc -l
31

**Comment by dom96** [comment]
hah, I love this. Someday we'll reach 0... someday :P

**Comment by TiberiumN** [comment]
@dom96 
can we remove this?
https://github.com/nim-lang/Nim/blob/ab31b776ef00df4a43f8afccb2e7c39a05616d2a/compiler/main.nim#L85

**Comment by dom96** [comment]
Probably not. Could break things.
