### ISSUE TITLE
Problem with foreign threads and emulated thread local vars.

### ISSUE THREAD

**Issue by GrundleTrundle** [nim-lang/Nim#2035]
I have a SDL2 app that calls back into a gcsafe callback written in Nim.  It runs on linux, but I've run into a problem running it on Windows.  The callback is actually happening on a thread created by SDL2 (audio), so the first callback will crash on windows inside of the nimFrame() for my callback, because the thread local vars haven't been setup, so `TlsGetValue(globalsslots_*)` just returns 0. 

Searching through the code, I don't see any way to 'offically' do this. It looks like, I could _maybe_ hack around it by setting up my own `TGcThread` for the foreign thread, and setting up the thread local vars myself. 

Am I missing something obvious here, like a pragma?  Or am I the first schmuck who's done this? :)

**Comment by Araq** [comment]
No, it's "widely known" that setupForeignThreadGc cannot work with emulated threadvars. Get some C compiler that can generated thread local storage on Windows properly and disable thread var emulation please.

**Comment by Araq** [comment]
Thread local storage for Windows/GCC has been fixed properly so shouldn't be an issue anymore.
