### ISSUE TITLE
There should be an "unsafe" block like Rust that the compiler ignores all checks inside.

### ISSUE THREAD

**Issue by xTrayambak** [nim-lang/Nim#20366]
### Summary

I'd like a unsafe block-like feature in Nim that lets you write unsafe code, and also, the compiler should not let code that can segfault compile at all, it should simply throw an error. For example, deallocating an already deallocated pointer can cause the binary to segfault, like this, a minimal example.

```nim
proc main() =
    dealloc nil

main()
```

### Description

A simple check at compile time to check for situations like these can help people write safer code.

### Standard Output Examples

```shell
$ nim c segfault.nim
$ ./segfault

SIGSERV: Illegal storage access. (Attempt to read from nil?)
[1]    3724 segmentation fault (core dumped)    ./segfault
```

**Comment by beef331** [comment]
https://nim-lang.org/docs/manual_experimental_strictnotnil.html

Nim does not consider things unsafe the same as Rust does, Nim considers low level operations unsafe but assumes if you use them you know what you're doing. You do not write with pointers in Nim if you want to use safe code.

**Comment by Araq** [comment]
There have been RFCs before suggesting this and they have all been rejected for various good reasons..
