### ISSUE TITLE
ORC cast from Wstr to ptr WCHAR or LPWSTR

### ISSUE THREAD

**Issue by TechThupport** [nim-lang/Nim#20372]
### What happened?

Code compiles fine with other GCs but fails when using ORC. This cast is needed for same winapis on windows. 

```nim
import winim
let test = newWideCString("mystring")
var testlpwstr = cast[LPWSTR](test)
```

### Nim Version

```text
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0565a70eab02122ce278b98181c7d1170870865c
active boot switches: -d:release
```

### Current Standard Output Logs

```shell
Error: expression cannot be cast to LPWSTR=ptr WCHAR
```

### Expected Standard Output Logs

```shell
Compiles successfully.
```

### Possible Solution

Thanks to ElegantBeef on the discord, below code compiles when using orc

```nim
var b = newWideCstring("hello")
discard cast[pointer](b[0].addr)
```

### Additional Information

I'm probably doing something wrong but would like to know if this is an actual bug or we just need to do things different when using orc

**Comment by bung87** [comment]
`newWideCString` returns `WideCStringObj` you should use `b[0].addr`

**Comment by beef331** [comment]
Like i said this isnt an issue. Nim does not allow  casting from object to pointer. When I said it was an issue it's cause i didnt realise the new runtime had it's own implementation of WideStrings.

**Comment by Araq** [comment]
I can confirm that you're supposed to use some different code for mm:orc, it's not 100% compatible with all of the old runtime.
