### ISSUE TITLE
23e0160 caused nimlsp regression

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#20375]
### What happened?

This commit https://github.com/nim-lang/Nim/commit/23e0160af283bb0bb573a86145e6c1c792780d49, makes nimlsp not respond to lsp requests https://github.com/PMunch/nimlsp/issues/140.
cc @havardjohn.

### Nim Version

1.7.1

**Comment by havardjohn** [comment]
Is there some some command line command I can execute of nimlsp or nimsuggest to reproduce this? Or some tests in nimlsp/nimsuggest?

**Comment by havardjohn** [comment]
I would guess that the nimlsp proc `uriToPath` that uses std/os `normalizedPath` is causing the issue. Could you provide your nimlsp log file? They would be in your editor's LSP log (at least for Vim). I would like to see what kind of paths you're using, so I can reproduce. I don't use a LSP on Windows, so I can't test this myself.

**Comment by AmjadHD** [comment]
@havardjohn, It's `getProjectFile` stuck in an infinite loop, because `splitFile` now always keeps the `dir` part.
https://github.com/PMunch/nimlsp/blob/ef43975fc138fc73dd5d28246b29a5d9658979ef/src/nimlsp.nim#L152-L154
here's a repro:
```nim
import std/os

const path = r"D:\User\test_2.nim"

var dir = path.splitFile
echo dir
dir = dir[0].splitFile
echo dir
dir = dir[0].splitFile
echo dir
dir = dir[0].splitFile
echo dir

# bug:
# (dir: "D:\\User", name: "test_2", ext: ".nim")
# (dir: "D:", name: "User", ext: "")
# (dir: "D:", name: "", ext: "")
# (dir: "D:", name: "", ext: "")
# working:
# (dir: "D:\\User", name: "test_2", ext: ".nim")
# (dir: "D:", name: "User", ext: "")
# (dir: "", name: "D:", ext: "")
# (dir: "", name: "", ext: "")

```

**Comment by havardjohn** [comment]
@AmjadHD Nice! I see that `splitFile` behavior has changed for Windows, but this new behavior is exactly how it works on Linux. E.g. on Linux in both Nim 1.6.2 and devel:

```nim
import os
let path = "/home"
var dir = path.splitFile
echo dir
dir = dir[0].splitFile
echo dir
dir = dir[0].splitFile
echo dir

# (dir: "/", name: "home", ext: "")
# (dir: "/", name: "", ext: "")
# (dir: "/", name: "", ext: "")
```

Because of this, I think the new behavior of `splitFile` on Windows should not be removed.

It looks like nimlsp assumes that root dir is "/" in the code you linked. If you change the while condition to the following, does it fix the hanging issue? I can remove path.len > 0 because `""` counts as root dir. I'll submit a PR if it works.

```diff
diff --git a/src/nimlsp.nim b/src/nimlsp.nim
index 8bd2c5f..3161d20 100644
--- a/src/nimlsp.nim
+++ b/src/nimlsp.nim
@@ -149,7 +149,7 @@ proc getProjectFile(fileUri: string): string =
   var
     path = dir
     certainty = None
-  while path.len > 0 and path != "/":
+  while not path.isRootDir:
     let
       (dir, fname, ext) = path.splitFile()
       current = fname & ext
```

**Comment by AmjadHD** [comment]
@havardjohn, yeah that works !
