### ISSUE TITLE
Compiler error when using a string generated with the `fmt""` macro twice in a template.

### ISSUE THREAD

**Issue by jesvedberg** [nim-lang/Nim#20381]
### What happened?

If I pass a string generated using the `fmt""` macro from `strformat` to a template that accepts a string, and then use that string twice in the template, I get a C compiler error. Here's a minimal example:

```nim
import strformat

template myTemplate(s: string) =
  echo s
  echo s

proc main() =
  myTemplate fmt"hello"

main()
```

When trying to compile this, I get an error message from the C compiler step shown below. If I don't use the `fmt""` macro, this compiles as expected, and if I remove the the `main()` function and just call `myTemplate` globally it also compiles. Furthermore, the issue remains if I change the template argument type to `typed`, but it disappears if I change it to `untyped`.

### Nim Version

Tested with 1.6.6 and 1.2.0 with the same result.

### Current Standard Output Logs

```shell
Hint: used config file '/home/XXX/.choosenim/toolchains/nim-1.6.6/config/nim.cfg' [Conf]
Hint: used config file '/home/XXX/.choosenim/toolchains/nim-1.6.6/config/config.nims' [Conf]
..........................................................................
CC: template_test.nim
/home/XXX/.cache/nim/template_test_d/@mtemplate_test.nim.c: In function ‘main__template95test_4’:
/home/XXX/.cache/nim/template_test_d/@mtemplate_test.nim.c:118:24: error: redeclaration of ‘fmtRes’ with no linkage
  118 |         NimStringDesc* fmtRes;
      |                        ^~~~~~
/home/XXX/.cache/nim/template_test_d/@mtemplate_test.nim.c:116:24: note: previous declaration of ‘fmtRes’ with type ‘NimStringDesc *’
  116 |         NimStringDesc* fmtRes;
      |                        ^~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/XXX/.choosenim/toolchains/nim-1.6.6/lib -I/home/XXX/projects/nim -o /home/XXX/.cache/nim/template_test_d/@mtemplate_test.nim.c.o /home/XXX/.cache/nim/template_test_d/@mtemplate_test.nim.c' failed with exit code: 1
```

### Expected Standard Output Logs

```shell
hello
hello
```

### Possible Solution

I have no solution, but the issue can be worked around by either using specifying the template argument as `untyped` or by using a temporary variable in the template:

```nim
template myTemplate(s: string) =
  let s2 = s
  echo s2
  echo s2
```

### Additional Information

As far as I can tell, this is a different issue than the limitation with `strformat` discussed here: https://nim-lang.org/docs/strformat.html#limitations

**Comment by metagn** [comment]
"Simpler" case:

```nim
import macros

macro foo() =
  let symName = genSym(nskLet, "tmp")
  result = newLetStmt(symName, newLit(123))

template myTemplate(x: typed): untyped =
  x
  x

proc main =
  myTemplate(foo())

main()
```

**Comment by metagn** [comment]
Workaround is wrap result of macro with `block`, which #21761 does for strformat and should close this issue. 

The general case I posted above is still an issue but it's a separate priority and might not have an easy fix (again a workaround exists).
