### ISSUE TITLE
`of` operator doesn't consider generics under orc/arc

### ISSUE THREAD

**Issue by dsrw** [nim-lang/Nim#20391]
### What happened?

Under refc the following works:

```nim
type Container[T] = ref object of RootRef
  item: T

let a = Container[int]()

assert a of Container[int]
assert not (a of Container[string])
```

Under arc/orc it fails, as both `a of Container[int]` and `a of Container[string]` evaluate to `true`.

### Nim Version

Nim Compiler Version 1.7.1 [MacOSX: arm64]
Compiled at 2022-09-19
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 7a756bfaef29ff521059b3310b67a0344001f5fd
active boot switches: -d:release

(behavior is the same with 1.6.6)

### Current Standard Output Logs

```
Error: unhandled exception: /Users/scott/src/github.com/dsrw/enu/src/t.nim(7, 1) `not (a of Container[string])`  [AssertionDefect]
```

### Expected Standard Output Logs

passes

**Comment by ringabout** [comment]
It is the same for 1.4.x and 1.2.x.

**Comment by dsrw** [comment]
Excellent, thanks for taking care of this so quickly!
