### ISSUE TITLE
--styleCheck:off does not work (and --styleCheck:hint is now the default?)

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#20397]
### What happened?

```nim
var a_b = 1
```
Compiling the above code gives -
```
t.nim(1, 5) Hint: 'a_b' should be: 'aB' [Name]
```
Using `--styleCheck:error` I get -
```
t.nim(1, 5) Error: 'a_b' should be: 'aB'
```
Using `--styleCheck:off` I still get -
```
t.nim(1, 5) Hint: 'a_b' should be: 'aB' [Name]
```

It should not give this hint when styleCheck:off is given
Also styleCheck:hint should not be the default (if that was an intentional change and not just this bug itself)

### Nim Version

```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-09-20
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 4a1bda667c74361c121460ca7d80cfcbf003d8d7
active boot switches: -d:release -d:danger
```

**Comment by ringabout** [comment]
I ran a git bisect, it seems that https://github.com/nim-lang/Nim/pull/19822 causes the issue.

**Comment by nc-x** [comment]
There is also a follow up pull request - https://github.com/nim-lang/Nim/pull/20095
Maybe check if that already fixes this issue or not

**Comment by ringabout** [comment]
Not sure, I will open a pull request
