### ISSUE TITLE
Logical operators generate suboptimal c (cpp) code

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#20410]
### What happened?

Related: https://github.com/nim-lang/Nim/issues/20219

```nim
proc p(x: int) =
  if 1 < x and x <= 10:
    discard

p(2)
```
generates:
```c
N_LIB_PRIVATE N_NIMCALL(void, p__test_1)(NI x) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) < x);
		if (!(T3_)) goto LA4_;
		T3_ = (x <= ((NI) 10));
		LA4_: ;
		if (!T3_) goto LA5_;
	}
	LA5_: ;
}
```
it should generate:
```c
N_LIB_PRIVATE N_NIMCALL(void, p__test_1)(NI x) {
	{
		if (!((((NI) 1) < x) && (x <= ((NI) 10)))) goto LA4_;
	}
	LA4_: ;
}
```

### Nim Version

1.7.1

### Possible Solution

https://github.com/nim-lang/Nim/blob/be4bd8a0edd527b24679372b8cb9d2afa548056d/compiler/ccgexprs.nim#L1097
`isSimpleExpr` is not used anywhere unlike in jsgen.

**Comment by demotomohiro** [comment]
Could you explain what is the problem in existing Nim's generated C code?

Temporary variables in generated C code is optimized away by backend C compiler and your Nim code and your "should generate" C code result in same assembler code:
https://godbolt.org/z/6cTahEfxM
https://godbolt.org/z/EaYs9P8sn

**Comment by AmjadHD** [comment]
Very useful website, I had to compare the two c snippets to see that they produce the same code.
Fair enough, Compilers seem to be smart enough to optimize this so closing.

**Comment by AmjadHD** [comment]
@demotomohiro
msvc seems to not be smart enough:
https://godbolt.org/z/1czodb6n6
