### ISSUE TITLE
A segfault occurs with Nim 1.6.8 compiling "pakku" but not with --verbosity:2

### ISSUE THREAD

**Issue by zqqw** [nim-lang/Nim#20450]
### What happened?

Reported here, where further details can be found:
https://github.com/zqqw/pakku/issues/27

### Nim Version

$ nim -V
Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release

### Possible Solution

Adding --verbosity:2 to the Nim options avoids the segfault happening for some reason.

### Additional Information

It starts to compile Pakku and gets a reasonable way through the process but then segfaults near the end. The obvious way to investigate was to enable a more verbose output from Nim but then it builds fine!

**Comment by zqqw** [comment]
Trying with nim-git to use the latest nim, the --verbosity:2 no longer works. I tried 4 times after removing that again, and it failed to build with 4 different errors:
```
$ nim -V
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-09-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: a8cc5d1379bbf3197e3e7a040cac2f7376a4949a
active boot switches: -d:release


With --verbosity:2

stack trace: (most recent call last)
sets.nim(264, 23)        package
/usr/lib/nim/pure/collections/sets.nim(264, 23) Error: index 6 not in 0 .. 1
      if isFilled(s.data[h].hcode):
                        ^
??? compiler msg initiated here [MsgOrigin]
make: *** [Makefile:121: src/pakku] Error 1



Without --verbosity:2

Attempt 1:
stack trace: (most recent call last)
/usr/lib/nim/pure/collections/sets.nim(264, 18) package
/usr/lib/nim/pure/collections/sets.nim(264, 18) Error: attempt to access a nil address ("kind", nkIntLit, "typ", "int", "rc", 0)
make: *** [Makefile:121: src/pakku] Error 1

Attempt 2:
src/pakku/src/config.nim(203, 11) Error: type mismatch: got <array[0..-1, string]>
but expected one of:
proc `@`[IDX, T](a: sink array[IDX, T]): seq[T]
  first type mismatch at position: 1
  required type for a: sink array[0..-1, empty]
  but expression '[]' is of type: array[0..-1, string]

expression: @[]
make: *** [Makefile:121: src/pakku] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

Attempt 3:
/src/pakku/src/feature/localquery.nim(7, 61) template/generic instantiation of `withAlpmConfig` from here
/src/pakku/src/config.nim(203, 11) Error: type mismatch: got <array[0..-1, string]>
but expected one of:
proc `@`[IDX, T](a: sink array[IDX, T]): seq[T]
  first type mismatch at position: 1
  required type for a: sink array[0..-1, empty]
  but expression '[]' is of type: array[0..-1, string]

Attempt 4:
expression: @[]
make: *** [Makefile:121: src/pakku] Error 1
==> ERROR: A failure occurred in build().
    Aborting...


CC: install.nim
CC: tools.nim
......SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:121: src/pakku] Segmentation fault


```
I think I have seen this kind of thing with segfaults in C programs though, the segfault happens somewhere but it might not always crash right there, plus there might be some multithreading going on and there could be some other things that need updating in Pakku for the latest Nim Git build.

**Comment by zqqw** [comment]
Building Nim at tag v1.6.8 with debug symbols the behaviour is the same, but when I ran it under valgrind it did not crash. It found lots of errors, mostly involving the use of uninitialised variables. Disabling the 1000 limit gave a much larger log file, there might be too much background noise here for this approach to help, but here is the short file:
[valgrind-nimlog.zip](https://github.com/nim-lang/Nim/files/9680511/valgrind-nimlog.zip)

**Comment by Araq** [comment]
Valgrind only works reliably with `--mm:orc -d:useMalloc`.

**Comment by zqqw** [comment]
I found the problem commit:
9508b06513b170ffbe91cfcfcd7ca09fa9b675cc Fix nested finally handling in closureiters [backport] (#19933)                                    (This segfaults, not working)

b1f325d6416ba0a5acbd2f3c9fd6f4986e889ed4 sysrand: fix syscall signature [backport] (#19982)                                                 (This was OK, working)

Adding those flags in build_all.sh in place of -d:release didn't work, it wouldn't build nor would it with some options for gdb to get a backtrace, not sure how to build the Nim compiler for these, but hopefully it doesn't matter now the commit has been found.
echo_run ./koch boot -d:release --skipUserCfg --skipParentCfg --hints:off

**Comment by zqqw** [comment]
It is this hunk in the commit that causes the problem, in the file: compiler/closureiters.nim
```
@@ -861,6 +873,13 @@ proc transformReturnsInTry(ctx: var Ctx, n: PNode): PNode =
 
   of nkSkip:
     discard
+  of nkTryStmt:
+    if n.hasYields:
+      # the inner try will handle these transformations
+      discard
+    else:
+      for i in 0..<n.len:
+        n[i] = ctx.transformReturnsInTry(n[i])
   else:
     for i in 0..<n.len:
       n[i] = ctx.transformReturnsInTry(n[i])


```
So what is going on there, that would make it say:
......SIGSEGV: Illegal storage access. (Attempt to read from nil?)
and then segfault and crash?

**Comment by zqqw** [comment]
If I change that hunk to this, it works OK, as you might expect because the else would do that anyway in the original code.
```
  of nkTryStmt:
    for i in 0..<n.len:
      n[i] = ctx.transformReturnsInTry(n[i])
```
So I guess the problem is probably introduced by this line:
  ```  if n.hasYields: ```
hasYields is a proc defined previously in the same file.

**Comment by ringabout** [comment]
Hello @zqqw would you possibly check the devel branch? If it doesn't compile, try the patch below.

```
diff --git a/src/config.nim b/src/config.nim
index 7a037da..4c18aad 100644
--- a/src/config.nim
+++ b/src/config.nim
@@ -200,4 +200,5 @@ proc obtainConfig*(config: PacmanConfig): Config =
 template withAlpmConfig*(config: Config, passDbs: bool,
   handle: untyped, alpmDbs: untyped, errors: untyped, body: untyped): untyped =
   withAlpm(cstring(config.root), config.db, if passDbs: config.common.dbs
-    else: @[], cstring(config.common.arch), handle, alpmDbs, errors, body)
+    else: newSeq[string](), cstring(config.common.arch), handle, alpmDbs, errors, body)
```

**Comment by zqqw** [comment]
Building Nim from the nim-git package using makepkg, the nim-git build fails, so I can't test how it compiles anything as it doesn't build itself at this commit. I tried it a couple of times, first updating my existing repo, then building an entirely fresh instance, which gave the same result.

```
commit c0824b9b80f50807fc41b621760c4b685d1d7497 (HEAD -> devel, origin/devel, origin/HEAD)
Author: ringabout <43030857+ringabout@users.noreply.github.com>
Date:   Tue Oct 18 02:29:00 2022 +0800

    [`std/os` clean up] import and export `osseps` (#20580)
    
    import and export osseps




nim-git/src/Nim/tools/niminst/niminst.nim(222, 6) Error: 'ignoreFile' can have side effects
> nim-git/src/Nim/tools/niminst/niminst.nim(226, 55) Hint: 'ignoreFile' calls `.sideEffect` 'eqT'
>> nim-git/src/Nim/tools/niminst/niminst.nim(201, 6) Hint: 'eqT' called by 'ignoreFile'
>>> nim-git/src/Nim/tools/niminst/niminst.nim(206, 16) Hint: 'eqT' calls routine via hidden pointer indirection

FAILURE
==> ERROR: A failure occurred in package_nim-git().
    Aborting...
```

**Comment by ringabout** [comment]
Sure, I will look into it.

progress => https://github.com/nim-lang/Nim/pull/20587

**Comment by zqqw** [comment]
Building nim-git at 0510a2be0d6df674aa91ae3f2884d98473cade4c and adding your patch above to Pakku does result in a clean build, thank you for your fine endeavours.

**Comment by ringabout** [comment]
The remaining problem seems to be caused by type inference on the devel branch.

**Comment by metagn** [comment]
Can this be closed?

**Comment by ringabout** [comment]
It should at least work on the devel branch.
