### ISSUE TITLE
Uninstantiated generics raises error only during type instantiation

### ISSUE THREAD

**Issue by dlesnoff** [nim-lang/Nim#20477]
### What happened?

I have asked if the following behaviour was an error first in this forum post https://forum.nim-lang.org/t/9436 .
We can define types whose fields are uninstantiated generics.

```nim
type
  myObject = object
    tab: seq

var a1 = myObject(tab: @[1, 2, 3])
```
This code raises an error during object instantiation but not at the type definition. If we remove the last line, the code compiles while I think it should not/raises a hint and propose some code like:
```nim
type
  myObject[T] = object
    tab: seq[T]
```

### Nim Version

Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0565a70eab02122ce278b98181c7d1170870865c
active boot switches: -d:release

Same with 1.6.8 and devel:
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-01
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 96c5586d030a97d9da2f08b2faacad8d34ebd2e4
active boot switches: -d:release

### Current Standard Output Logs

```shell
type
  myObject = object
    tab: seq

var a1 = myObject(tab: @[1, 2, 3])

~/Documents/dev/typeGenericsIssue.nim(5, 5) Error: invalid type: 'T' in this context: 'myObject' for var
```

### Expected Standard Output Logs

```shell
type
  myObject = object
    tab: seq

~/Documents/dev/typeGenericsIssue.nim(3, 12) Error: uninstantiated generical type `seq` in field `tab` for object type `myObject` definition

or

~/Documents/dev/typeGenericsIssue.nim(3, 12) Hint: You may want to instantiate generical type `seq` for the field `tab` in object type `myObject` definition
```

### Possible Solution

`seq` actually seems to be the only typeclass concerned by this problem. Other typeclass makes the type definition fails with error:
> Error 'seq' is not a concrete type

According to @beef331 the error is likely here :
https://github.com/nim-lang/Nim/blob/86f7f4ffa5b8d84cbff12afbcd9b88d3ceb429c8/compiler/semstmts.nim#L1441-L1467 

### Additional Information

This is my first compiler issue.

**Comment by dlesnoff** [comment]
Probably will be fixed by https://github.com/nim-lang/Nim/pull/20412 PR
Thus very similar to:
https://github.com/nim-lang/Nim/issues/19546
https://github.com/nim-lang/Nim/issues/13992
https://github.com/nim-lang/Nim/issues/19164

**Comment by Araq** [comment]
Not a bug, generics are checked at instantiation.
