### ISSUE TITLE
Consider xorg.freedesktop.org (~/.local/bin) installation by default with choosenim

### ISSUE THREAD

**Issue by rwxrob** [nim-lang/Nim#20484]
### Summary

Normally such things are installed under `~/.local/bin` under modern desktop configuration conventions. This would only be for `choosenim`. Perhaps it could be changed or selected during installation.

### Description

See title and summary.

**Comment by beef331** [comment]
Issue should be made [here](https://github.com/dom96/choosenim). Even though most people use choosenim to install Nim it's not officially apart of the Nim tooling.

**Comment by dom96** [comment]
This won't happen because choosenim depends on Nimble's installation structure. You can suggest changing it in Nimble but it won't be an easy change so IMO not worth the effort.
