### ISSUE TITLE
system.create doesn't work with bitfield objects

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#20516]
### What happened?

in Nim 1.7.x you can no longer use `system.create` to allocate an object that uses the bitsize pragma.

### Example

```nim
type Foo = object
  x {.bitsize:4.}: uint
  y {.bitsize:4.}: uint

let a = create(Foo)
```

### Current Output

```
main.nim(5, 15) template/generic instantiation of `create` from here
system/memalloc.nim(148, 18) Error: 'sizeof' requires '.importc' types to be '.completeStruct'
```

### Additional Information

This works fine in Nim 1.6 and older.

The error is related to https://github.com/nim-lang/Nim/issues/19040 , but only recently has it started triggering for `system.create`. I don't understand why the compiler would be trying to evaluate `sizeof` at compile time in this scenario, if it wasn't doing so before.

### Nim Version

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-07
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 0d23419e681c4ce561ec43dc4a66a0ed40b8009e
active boot switches: -d:release
```

**Comment by ringabout** [comment]
related https://github.com/nim-lang/Nim/commit/2bda4a30a6b12dd0840dc347e454e54fe26721e7

**Comment by Araq** [comment]
No need to do anything but what we do in 1.6.
