### ISSUE TITLE
Threads and channels modules' docs leak into system module docs

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#20526]
### What happened?

After [this point](https://nim-lang.github.io/Nim/system.html#system-module-misc) in the system module docs:

<details>
<summary>threads docs</summary>

![image](https://user-images.githubusercontent.com/10591326/194752964-5fd0ad29-714c-4b52-b6a9-5eff46e2af5a.png)

</details>

Also:

<details>
<summary>channels docs</summary>

![image](https://user-images.githubusercontent.com/10591326/194752971-2c4f6bed-f4af-4774-ae95-3d7cc718b2ae.png)

</details>

Both the docs from [threads](https://nim-lang.org/docs/threads.html) and [channels](https://nim-lang.org/docs/channels_builtin.html) are also added to the system module docs, even though they aren't formatted properly.

### Nim Version

fbc6975922ea644f0bcf1ad034edd780b3dcfa87

### Possible Solution

Change [`include "system/channels_builtin"`](https://github.com/nim-lang/Nim/blob/fbc6975922ea644f0bcf1ad034edd780b3dcfa87/lib/system.nim#L2204) and [`include "system/threads`](https://github.com/nim-lang/Nim/blob/fbc6975922ea644f0bcf1ad034edd780b3dcfa87/lib/system.nim#L2095) to `import`/`export` if possible.

**Comment by ringabout** [comment]
I will move threads out of system. It will be converted into an import.
`system/channels_builtin` doesn't work with ORC, it should be part of `nimPreviewSlimSystem`.
