### ISSUE TITLE
Nimpretty mangles numeric literal procs

### ISSUE THREAD

**Issue by rotu** [nim-lang/Nim#20553]
### What happened?

Running `nimpretty` on the implementation of a custom numeric literal results in broken code.
In general, the proc name has the first letter duplicated with a space between (e.g. `'XYYY` becomes `'X XYYY`)

For example the declaration:

```nim
proc `'u4`(n: string): u4 =
```

becomes:
```nim
proc `'u u4`(n: string): u4 =
```

### Nim Version

Nim Compiler Version 1.7.3 [MacOSX: amd64]
Compiled at 2022-10-12
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 7394587217c3ab26867d698b2ad89fb37cdcf3bb
active boot switches: -d:release

### Current Standard Output Logs

```shell
proc `'u u4`(n: string): u4 =
  # The leading ' is required.
  result = (parseInt(n) and 0x0F).u4
```

### Expected Standard Output Logs

```shell
proc `'u4`(n: string): u4 =
  # The leading ' is required.
  result = (parseInt(n) and 0x0F).u4
```

**Comment by ringabout** [comment]
`nimpretty` is broken for Stropping identifiers with a single apostrophe because it is parsed as tkCharLit and rendered incorrectly

```nim
let `'hello` = 12
echo `'hello`
```
Neither does this work.
