### ISSUE TITLE
Compiler replaces =sink for =copy

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#20572]
### What happened?

Explicitly calling =sink doesn't work. It's rewritten as copy.

```nim
proc main =
  var a = "abc"
  var b = "de"
  `=sink`(a, b)
  echo a

main()
```

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-15
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 0510a2be0d6df674aa91ae3f2884d98473cade4c
active boot switches: -d:release --gc:markAndSweep

### Current Standard Output Logs

```shell
# --expandArc:main

var
  a
  b_cursor
try:
  a = "abc"
  b_cursor = "de"
  `=copy`(a, b_cursor)
  echo [a]
finally:
  `=destroy`(a)
```

### Additional Information

std/isolation is affected from this bug because in:

```nim
proc `=sink`*[T](dest: var Isolated[T]; src: Isolated[T]) {.inline.} =
  # delegate to value's sink operation
  `=sink`(dest.value, src.value)
```

It's replaced by =copy!

**Comment by beef331** [comment]
You dont call `=sink` you do `move` so `a = move b` and `dest.value = move src.value`. Though given these are string literals copying the cursor is the same as a move afaik.

**Comment by Araq** [comment]
@beef331 In this case `move` cannot be used.
