### ISSUE TITLE
find in strutils cannot handle with "\0\0" since Nim 1.6.0.

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#20576]
### What happened?

```nim
import strutils
echo "abc\0\0\0".find("\0\0")
```

### Nim Version

Nim Compiler Version 1.6.8 [Windows: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Current Standard Output Logs

```shell
0
```

### Expected Standard Output Logs

```shell
3
```

**Comment by ringabout** [comment]
It has been fixed by https://github.com/nim-lang/Nim/pull/19714
