### ISSUE TITLE
Error: internal error: getTypeDescAux(tyFromExpr) when using auto + arc, works with refc

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#20588]
### What happened?

```nim
# works with --gc:refc
# Error: internal error: getTypeDescAux(tyFromExpr) with --gc:arc

func hakunaMatata[N, D](n: N, d: D): auto =
    if d.float > 0: (n/d) else: 0.0.auto

echo hakunaMatata(42.0, 0.42)
```

### Nim Version

```
Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release
```

### Current Standard Output Logs

```shell
Error: internal error: getTypeDescAux(tyFromExpr)
No stack traceback available
```

### Expected Standard Output Logs

```shell
100.0
```

**Comment by metagn** [comment]
Compiles with `0.0.auto` -> `0.0`. Don't know what `0.0.auto` is supposed to mean, it's not needed as far as I can tell:

```nim
func hakunaMatata[N, D](n: N, d: D): auto =
    if d.float > 0: (n/d) else: 0.0

echo hakunaMatata(42.0, 0.42).type # float
echo hakunaMatata(42f32, 3f32).type # float32
```

**Comment by bung87** [comment]
where the `0.0.auto` goes in compiler? from my view `auto` is not suitable for a dotcall

**Comment by Vindaar** [comment]
> where the `0.0.auto` goes in compiler? from my view `auto` is not suitable for a dotcall

I would assume the symbol `auto` will be mapped to an implicit generic. Therefore the dot call for `0.0.auto` just converts the literal to the implicit generic that `auto` was determined to be.

edit: I mean that's what I would understand the syntax to imply.

**Comment by bung87** [comment]
I debug in serveral places, in the end I start from `semIf` , found it's 

``` nim
proc semExprBranch(c: PContext, n: PNode; flags: TExprFlags = {}; expectedType: PType = nil): PNode =
  result = semExpr(c, n, flags, expectedType)
  echo result.typ
```
outputs `typeof(auto(0.0))`
