### ISSUE TITLE
Regression when accessing a variable generic type

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#20645]
### What happened?

```nim
type Zzz[Gen] = object

proc test(z: Zzz) =
  echo z.Gen(5)

test(Zzz[float]())
```

### Nim Version

1.2.18: works
1.6.8: works
1.6.8 with orc: works
devel 684a862526847c39597e345d00b8323353012c07: fails

### Current Standard Output Logs

```shell
/tmp/test.nim(6, 5) template/generic instantiation of `test` from here
/tmp/test.nim(4, 9) Error: attempting to call undeclared routine: 'Gen'
```

**Comment by Araq** [comment]
@bung87 can you bisect?

**Comment by bung87** [comment]
> @bung87 can you bisect?

ok, am on it.

**Comment by bung87** [comment]
07b645342abd06b2323df042c170eb847f51880d is the first bad commit

**Comment by Menduist** [comment]
Thanks for the insta-fix!
