### ISSUE TITLE
Parent CatchableError is not show in the stack trace

### ISSUE THREAD

**Issue by diegomrsantos** [nim-lang/Nim#20677]
### What happened?

`raise newException(CatchableError, "child", newException(CatchableError, "parent"))` 

outputs no info about the parent exception:
```
/usercode/in.nim(1)      in
Error: unhandled exception: child [CatchableError]
```

For comparison, the following Kotlin code

```
fun main() {
    throw Exception("Child", Exception("Parent"))
}
```
outputs:
```
Exception in thread "main" java.lang.Exception: Child
 at FileKt.main (File.kt:6) 
 at FileKt.main (File.kt:-1) 
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (:-2) 
Caused by: java.lang.Exception: Parent
at FileKt .main(File.kt:6)
at FileKt .main(File.kt:-1)
at jdk.internal.reflect.NativeMethodAccessorImpl .invoke0(:-2)
```

### Nim Version

Nim Compiler Version 1.7.1 [MacOSX: amd64]
Compiled at 2022-08-31
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: d4c0d35b32e51eae06e65e78c253cdaf8bb42446
active boot switches: -d:release

**Comment by Araq** [comment]
I had no idea we care about Kotlin compatibility. Instead I checked Nim's docs and they say

```
    parent*: ref Exception ## Parent exception (can be used as a stack).
```

I don't see the requirement here "and in the default error message that happens when you don't catch it this stack is reported".
