### ISSUE TITLE
Can not use nim 2's new default instantiation with any object type with a `DateTime` field

### ISSUE THREAD

**Issue by PhilippMDoerner** [nim-lang/Nim#20681]
### What happened?

It is currently impossible to instantiate a DateTime object at compile time. That makes it impossible to make use of nim 2's new feature of [default instantiation](https://github.com/nim-lang/Nim/pull/20480) for any object with fields of the `DateTime` type.

These are the ways I tried so far:

Attempt 1:
```nim
import std/times

type A = object
  d: DateTime = DateTime()

let x = default(A)
```
Attempt 2:
```nim
import std/times

type A = object
  d: DateTime = dateTime(2020, 1.Month, 1)

let x = default(A)
```
Attempt 3:
```nim
import std/times

type A = object
  d: DateTime = now()

let x = default(A)
```

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-23
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: fa1606c6d6799823de51f7a273ae5da2f3fa6e3a
active boot switches: -d:release

### Current Standard Output Logs

```shell
Attempt 1:
Error: the field 'nanosecond' is not accessible.


Attempt 2:
/.choosenim/toolchains/nim-#devel/lib/pure/times.nim(1366, 6) Error: cannot evaluate at compile time: localInstance


Attempt 3:
/.choosenim/toolchains/nim-#devel/lib/pure/times.nim(971, 13) Error: cannot 'importc' variable at compile time; clock_gettime
```

### Expected Standard Output Logs

```shell
No Error message as above
```

### Possible Solution

Suggestions:

1. Provide a separate proc that can solely be used to instantiate some dummy value for DateTime at compileTime.
2. Make the fields of DateTime public so that one can use `DateTime()` to instantiate a DateTime themselves with dummy values

### Additional Information

I believe this to be pretty relevant in particular for the feature provided by https://github.com/nim-lang/Nim/pull/20480 , as types with DateTimes aren't all that rare. Unless such a feature can be provided I effectively am unable to make use of it, as I must use ElegantBeef's `constructor` package for all types with DateTime fields and when I have that dependency anyway I might as well use it in general.

**Comment by PhilippMDoerner** [comment]
For reference, ultimately I want to be able to default instantiate objects with a type that is a distinct version of DateTime, something like this:

```nim
# What I'd like to work
import std/times

type DjangoDateTime = distinct DateTime

type Default = object
  data: DjangoDateTime = DateTime().DjangoDateTime

let x = default(Default)
echo x.repr
```

Ringabout granted me an example that should work for now with fields that have pure DateTime types:

```nim
# Works - workaround for objects with pure DateTime fields
import std/times

import std/importutils

privateAccess DateTime

type
  Default = object
    data: DateTime = Datetime(second: 10)

let x = default(Default)
echo x.data.second
```

Sadly it is impossible to make use of this for default instantiation
```nim
# Doesn't work, attempted workaround for distinct Datetime Fields
import std/times

import std/importutils

type DjangoDateTime = distinct DateTime

privateAccess DateTime
privateAccess DjangoDateTime

type Default = object
  data: DjangoDateTime = DateTime().DjangoDateTime

let x = default(Default)
echo x.repr
```
Errors out with:
```txt
 Error: type mismatch: got 'DateTime' for 'DateTime(nanosecond: 0, second: 0, minute: 0, hour: 0, monthdayZero: 0,
         monthZero: 0, year: 0, weekday: dMon, yearday: 0, isDst: false,
         timezone: nil, utcOffset: 0)' but expected 'DjangoDateTime = distinct DateTime'
```

**Comment by ringabout** [comment]
Likewise for the second example

```nim
import std/times

import std/importutils

type DjangoDateTime = distinct DateTime

privateAccess DateTime
privateAccess DjangoDateTime
import std/macros
block:
  macro foo(x: static DjangoDateTime) =
    discard x

  macro foo2: untyped =
    var x: DjangoDateTime = DjangoDateTime(DateTime())

    result = quote do:
      foo(`x`)

  foo2()
```
outputs
```
macro foo(x: static DjangoDateTime)
  first type mismatch at position: 1
  required type for x: static[DjangoDateTime]
  but expression '(nanosecond: 0, second: 0, minute: 0, hour: 0, monthdayZero: 0, monthZero: 0,
 year: 0, weekday: dMon, yearday: 0, isDst: false, timezone: nil, utcOffset: 0)' is of type: DateTime

expression: foo((nanosecond: 0, second: 0, minute: 0, hour: 0, monthdayZero: 0,
     monthZero: 0, year: 0, weekday: dMon, yearday: 0, isDst: false,
     timezone: nil, utcOffset: 0))
```

**Comment by ringabout** [comment]
The first case has been covered by https://github.com/nim-lang/Nim/pull/20639

The second and third case shouldn't work according to the RFC. The default field shouldn't have side effects. And the procs called should work at compile time.

The fourth case seems to be pre-existing as the example I have shown.
