### ISSUE TITLE
arithmetic operation between int and complex or float

### ISSUE THREAD

**Issue by shoaib-mi** [nim-lang/Nim#20689]
### Summary

I think for scientific purposes, it would be better if we could do arithmetic operation between `int` types and `float` or `complex` types.

### Description

Following functions are missing and I suggest to add them to the `math` and `complex` modules.

```
const I: Complex[float] = complex(0.0,1.0)

# --------------------plus--------------------------
proc `+`(a,b:int or float): float = a.float + b.float # add this line to the math module and rest of the code to the complex module
proc `+`(a:int, b:Complex[float]): Complex[float] = a.float.complex + b
proc `+`(a:Complex[float], b:int): Complex[float] = a + b.float.complex
# --------------------minus--------------------------
proc `-`(a:int, b:Complex[float]): Complex[float] = a.float.complex - b 
# --------------------multiply--------------------------
proc `*`(a:Complex[float], b:int): Complex[float] = a * b.float
proc `*`(a:int, b:Complex[float]): Complex[float] = a.float * b
# --------------------division--------------------------
proc `/`(a:int, b:Complex[float]): Complex[float] = a.float / b
```

**Comment by ghost** [comment]
For int/float mixed arithmetics there's already https://nim-lang.org/docs/lenientops.html

**Comment by Vindaar** [comment]
To push back on this a little bit. As Yardanico already mentions, there's a module for at least the int / float mixing. If anything `Complex` could be added there as well, but personally I'm not sure it's a good idea, given that `Complex` is a much "heavier" type (being an object of two floats). Good to be mindful about imo.

But you should try to embrace the fact that Nim has a much stricter type system. I've never imported `lenientops` in any of my code. Once you get around to it, it's amazing to be certain you don't have any nasty bugs, due to accidentally mixing ints / floats and losing information that way. Typing a few conversions here and there where the mixed types comes up is worth it. 

AIso without Nim's strong type system we couldn't build things like [unchained](https://github.com/SciNim/unchained) (which effectively defines a whole bunch of `distinct float` types and performs checks for you and required conversions at CT).

**Comment by shoaib-mi** [comment]
There are already other programs that can do mathematical operations and simulations like `matlab` and `mathematica` and of course plenty more. Students that needs to deal with mathematical equation, logical operation, physical and chemical simulation, are already doing their job using those programs. Beside them, `python` has been more developed to cover all typical and special needs, that any type of student from any field of study encounters, and it's a good thing. But what is bad with python is its  horrible speed. There are some modules that tried to solve this problem like `numpy` but they just made it worse, since you are not a programmer any more, and more like an operator of some kind of machine (in my opinion).
What I find interesting and good about `Nim` is its simplicity and speed, so we could use such language as a replacement for `python`. In order to do that, `Nim` must at least has some functionality that are expected from any other languages. for example, it should know by default that `2 + 3.5` is `5.5`, and not throw an error regarding mismatching of types for operand `+`.
I think `Nim` has a beautiful syntax (at least most part of it), and by developing their main modules or modules that are currently unavailable, it could attracts more attention from different types of users, which makes nim community more bigger and more inclusive.
for students of computer sciences, it may seems unnecessary to have such functionalities `(int + complex or int + float)`, but for students from mathematics, physics and chemistry, it is of crucial importance.

**Comment by Vindaar** [comment]
I'm sure Nim's success in that regard won't depend on whether one imports a single module (like `lenientops`, but possibly custom) that either defines procedures (like `lenientops` does) including `Complex` or simply using `converters`:

https://nim-lang.org/docs/manual.html#converters


But in any case, also regarding students, it's a _good_ thing if they need to learn and understand that an `int` and a `float` are conceptually different things and neither is the same as any kind of number in maths. I'd think you would agree with that, as you already say things like `numpy` rather make you an "operator".

edit: I am a physicist btw, who has supervised multiple students over the years. The two that took up Nim upon my recommendation never took the lack of implicit conversions as a negative once they understood what's going on.

**Comment by shoaib-mi** [comment]
I agree with you @Vindaar, there should be some reasons why they did not write those suggestion in the main modules, and probably they are good ones. But regarding nasty bugs you mentioned, I think it is be a good thing to have them. this way we have the possibility of knowing where we messed up in the past.

I also agree with you that `int` and `float` are different even in mathematics (specially regarding significant figures), but I don't see how converting `int` to `float` which just add `.0` to the end of it, could possibly do any harm on other already written codes? because no one has ever do arithmetic operations on them in their code unless they explicitly converted them, so reconverting what is already converted does not do any harm.

By the way, my knowledge about details of computer science is limited, and I thought that the mentioned procedures makes working with `nim` more delightful.

Thank you all for your responses.

**Comment by Araq** [comment]
You cannot convert a 64 bit integer into a 64 bit float without losing something and Nim's builtin implicit conversions are lossless.
