### ISSUE TITLE
[Meta] template identifier unqiue

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#20693]
https://github.com/nim-lang/Nim/issues/20381

https://github.com/nim-lang/Nim/issues/17851

https://github.com/nim-lang/Nim/issues/16072

https://github.com/nim-lang/Nim/issues/13973

https://github.com/nim-lang/Nim/issues/9843

**Comment by ringabout** [comment]
You should probably only open one issue for these meta issues.
