### ISSUE TITLE
initTable with self-declared Table types

### ISSUE THREAD

**Issue by elpres** [nim-lang/Nim#2071]
If you declare a type which is a `Table` with a given combination of key and value types, as far as I can see, it's not possible to call `initTable` with that type, since it expects two parameters. Example:

``` nim
import tables

type
  CustomTable = Table[int, string]

var
  table1 = initTable[int, string]()  # works
  table2 = initTable[CustomTable]()  # doesn't
```

The reason I think that would be useful is if you have a routine that returns a custom table, the instantiation of `result` looks awkward:

``` nim
proc tableFromFile(filename: string): CustomTable =
  result = initTable[int, string]()
  # do something more...
```

From that code it's not clear that you are actually creating a table of the correct type until you look up its definition. And if you ever change its definition, you'd have to remember to adapt the call to `initTable` accordingly.

**Comment by def-** [comment]
I think it should work like this instead:

```nim
var
    table3: CustomTable = initTable()  # this should work

proc tableFromFile(filename: string): CustomTable =
  result = initTable()
```

**Comment by elpres** [comment]
Agreed, that would be even better.

**Comment by reactormonk** [comment]
Another call for return type overloading?

**Comment by def-** [comment]
> Another call for return type overloading?

I don't know, how does `@[]` do it?

**Comment by Varriount** [comment]
This is more in the realm of type inference with regards to return types

**Comment by andreaferretti** [comment]
https://github.com/nim-lang/Nim/issues/1070 was closed a few days ago as "not going to happen", and this is essentially a special case for it - should we close it as well?

**Comment by Araq** [comment]
I don't see it arguing for overloading by return type. Instead it argues for more type inference for generics. So no, this should remain open. :-)

**Comment by andreaferretti** [comment]
On a second read, I agree, there's no overloading here, just type inference from the return type.

**Comment by yglukhov** [comment]
Why not define an
```nim
proc init[K, V](t: var Table[K, V])

# And then
proc tableFromFile(filename: string): CustomTable =
  result.init()
```
This pattern would be really useful for object fields of `Table` type.
```nim
type Foo = ref object
  t: Table[string, int]

proc newFoo(): Foo =
  result.new()
  result.t.init()
  # instead of:
  result.t = initTable[string, int]()
```
Downsides of the current `initTable` is that you have to spell out the `K, V` again and again (not DRY), and that the result might get unnecessarily copied in memory.

**Comment by zah** [comment]
I've proposed how the entirely standard library should switch to the pattern above here:
https://github.com/nim-lang/Nim/issues/7832

**Comment by narimiran** [comment]
This (and much more) is now tracked and discussed in the mentioned @zah's RFC here: https://github.com/nim-lang/RFCs/issues/48
