### ISSUE TITLE
String literals should be not nil

### ISSUE THREAD

**Issue by philip-wernersbach** [nim-lang/Nim#2072]
By definition, string literals are of type "string not nil". The compiler should be aware of this.

```
type
    Test = tuple
        a: string not nil

let a: Test = (a: cast[string not nil]("Hello World!")) # OK
let b: Test = (a: "Hello World Again!") # Error
```

**Comment by Araq** [comment]
The compiler IS aware of this, but this is not carried over to tuples.

**Comment by philip-wernersbach** [comment]
@Araq, a couple questions about your last comment:

1. Does `not nil` work as expected?
2. How much work is needed to shore up `not nil`'s functionality? I like the idea of using `not nil` in my code because it eliminates the need to check for `nil` everywhere, but I don't want to use it if it's far from done.

**Comment by Araq** [comment]
1. Yes, but I compare it to Optional[T] where is adds some expressitivity.
2. It works as I intended it to work, but we need to use it in the stdlib and see how well things work out.

(Btw you don't have to check for 'nil' everywhere!)

**Comment by Araq** [comment]
Strings cannot be 'nil' anymore.
