### ISSUE TITLE
multiReplace / replace taking a long time to execute in VM since commit: ae050b05e9ce6f4e356c46de8722724a2f706e18 

### ISSUE THREAD

**Issue by geekrelief** [nim-lang/Nim#20746]
### What happened?

In NimForUE, we're running macros that do string replacements.  Since ae050b05e9ce6f4e356c46de8722724a2f706e18 the sample code below takes many minutes to finish executing. In prior commits or example v1.6.8 the following code would take a couple seconds to execute, and if fully compiled the resulting executable finishes instantly:
```nim
#nim.cfg:
--mm:orc # is orc the default on this commit? this doesn't seem necessary, but it's what we use to be clear.
```
```nim
#main.nim
import std/strutils
const source = staticRead("importedengine.txt")

static:
  echo "multiReplace - takes a long time in VM since: ae050b05e9ce6f4e356c46de8722724a2f706e18"
  let res = source.multiReplace(
              ("{.inject.}", ""),
              ("{.inject, ", "{."),
              ("<", "["),
              (">", "]"), #Changes Gen. Some types has two levels of inherantce in cpp, that we dont really need to support
              ("::Type", ""), #Enum namespaces EEnumName::Type
              ("::Mode", ""), #Enum namespaces EEnumName::TypeB
              ("::", "."), #Enum namespace
              ("__DelegateSignature", ""))
  writeFile("replaced_importedengine.nim", res)
  echo "finished"
```
Attached is the sample file we produce for the replacement. [importedengine.txt](https://github.com/nim-lang/Nim/files/9933180/importedengine.txt) I renamed the extension to `.txt` because of github.

### Nim Version

PS C:\Nim> nim --version
Nim Compiler Version 1.7.3 [Windows: amd64]
Compiled at 2022-11-03
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: ae050b05e9ce6f4e356c46de8722724a2f706e18
active boot switches: -d:release

### Current Standard Output Logs

```shell
Compiling with `nim c main`, the output prints:

multiReplace - takes a long time in VM since: ae050b05e9ce6f4e356c46de8722724a2f706e18

and can take many minutes to finish on my Ryzen 9 5950x. I Ctrl+C to kill it.
```

### Expected Standard Output Logs

```shell
The output should say `finished` after a couple seconds.
```

### Additional Information

The problem doesn't happen when not in the VM. If you remove the `static` block, compile and run the executable, it finishes instantly

**Comment by bung87** [comment]
change `--mm` to other options doesn't help, I get better performance via `./koch temp --mm:refc r -d:release tests/misc/t20746.nim` , note `--mm:refc` is apply to compiler , not the file.

**Comment by metagn** [comment]
So this is still an orc bug, the bug is in the VM running `multiReplace`.

**Comment by ringabout** [comment]
A similar case

```nim
import std/strutils

const translationTable = splitLines(staticRead"unidecode/unidecode.dat")
```

2.166s (orc 1.6.8) => 5.475s (orc devel)

I'm working on reducing this case.

**Comment by bung87** [comment]
in the loop vm always free and alloc memory for string no matter the variable already called `newStringOfCap`
