### ISSUE TITLE
[Meta] borrow

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#20755]
https://github.com/nim-lang/Nim/issues/4121 `distinct seq[T]`

https://github.com/nim-lang/Nim/issues/19097 `distinct Table[A, B]`

https://github.com/nim-lang/Nim/issues/6026 `type Amount[date: static[int]] = distinct float` and `+`

https://github.com/nim-lang/Nim/issues/3564 `distinct array[4, float32]` and `[]`

https://github.com/nim-lang/Nim/issues/2684  `distinct seq[T]` and `[]`

**Comment by yuanweixin** [comment]
It would be great if this receives attention in nim v2, seeing as we still can't do something like 
```
type stack[T] = distinct seq[T] 
```
and borrow some of the seq procs.
