### ISSUE TITLE
Allow to skip compiling `runnableExamples` when generating docs

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#20774]
### Summary

`koch docs` takes a long time to finish, most of the time is spent compiling and running `runnableExamples`.
I want to skip that when building docs of the devel branch, because it already passed the CI.

### Description

Add an option to nim's `doc` command that makes it skip compiling `runnableExamples`.

**Comment by Araq** [comment]
Already possible via `--docCmd:skip`.

**Comment by AmjadHD** [comment]
This should to be added to the docs then.

**Comment by ringabout** [comment]
It has been in the command line documentation:

```
  --docCmd:cmd              if `cmd == skip`, skips runnableExamples
                            else, runs runnableExamples with given options, e.g.:
                            `--docCmd:"-d:foo --threads:on"`
```
Run `nim --fullhelp`.
