### ISSUE TITLE
Root object types with only one `UncheckedArray[T]` field generate invalid C code

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#20787]
### What happened?

```nim
type
  Obj = object
    f: UncheckedArray[byte]

let o = new Obj
```

gcc (11.3) reports (confusing error message)
```shell
error: flexible array member in a struct with no named members
```

clang (14.0) reports
```shell
error: flexible array member 'f' not allowed in otherwise empty struct
```

### Nim Version

0.20..devel

### Current Standard Output Logs

```shell
$ nim r test2.nim 
Hint: used config file '/home/user/Projects/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/user/Projects/Nim/config/config.nims' [Conf]
Hint: used config file '/home/user/.config/nim/config.nims' [Conf]
...................................................................
test2.nim(5, 5) Hint: 'o' is declared but not used [XDeclaredButNotUsed]
CC: Projects/Nim/lib/system/exceptions.nim
CC: Projects/Nim/lib/std/private/digitsutils.nim
CC: Projects/Nim/lib/system/dollars.nim
CC: Projects/Nim/lib/system.nim
CC: test2.nim
/home/user/.cache/nim/test2_d/@mtest2.nim.c:34:5: error: flexible array member in a struct with no named members
   34 | NU8 f[SEQ_DECL_SIZE];
      |     ^
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -pthread   -I/home/user/Projects/Nim/lib -I/home/user -o /home/user/.cache/nim/test2_d/@mtest2.nim.c.o /home/user/.cache/nim/test2_d/@mtest2.nim.c' failed with exit code: 1


user@dd-laptop:~$ /home/user/.cache/nim/test2_d/@mProjects@sNim@slib@ssystem.nim.c:269:5: error: flexible array member in a struct with no named members
  269 | NU8 f[SEQ_DECL_SIZE];
      |     ^
```

### Expected Standard Output Logs

```shell
Compiles with error report by nim compiler.
```

### Possible Solution

forbid root object types with only one field which type is `UncheckedArray[T]`

**Comment by Araq** [comment]
Nim should insert a `char dummy;` field before it like it does for other otherwise empty structs. But who cares: you need some length information anyway so the object has more fields in practice.

**Comment by derekdai** [comment]
I guess `UncheckedArray[T]` should only be allowed to be used in the last field in `tuple` and `object`, just like in C. Otherwise this will happen
````nim
type
   Tup = tuple
     i1: UncheckedArray[int]
     i2: int
````

It looks like `i1` is an alias for `i2`, but since `i1` has size 1 in C, address is not equal to `i2` unless `i1` is a flexible array in C, but the C compiler This is not allowed.

Another example, `sizeof Tup` is 1 in nim, but is actually 2 in C
````nim
type
   Tup = tuple
     i1: UncheckedArray[int]
     i2: UncheckedArray[int]
````

**Comment by heterodoxic** [comment]
Thank you for your report and taking the time to reflect on further issues in regards to the use of C's flexible array members in Nim, @derekdai!

I humbly offer a simple solution already primed by @Araq for this particular case in #21979, along with the note that more work is to be done in the future to handle flexible array members properly.
