### ISSUE TITLE
Regression of type inference when using templates and a proc with the same name as one of them

### ISSUE THREAD

**Issue by diegomrsantos** [nim-lang/Nim#20807]
### What happened?

The following code doesn't compile

```
var s: seq[string]

template fail =
  s = @[]

template test(body: untyped) =
  body

proc test(a: string) =
   discard

test:
  fail()
```

Note that the `test` proc must have the same name as the `test` template and at least one parameter in order to reproduce the issue. It compiles If we change `s = @[]` to `s = newSeq[string]()`.

### Nim Version

Nim Compiler Version 1.7.3 [MacOSX: amd64]
Compiled at 2022-11-10
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 82e99f2332b97ec3c86eea319bc44fc6c8ab35b3
active boot switches: -d:release

### Current Standard Output Logs

```shell
test.nim(12, 6) template/generic instantiation of `test` from here
test.nim(4, 7) Error: type mismatch: got <array[0..-1, string]>
but expected one of:
proc `@`[IDX, T](a: sink array[IDX, T]): seq[T]
  first type mismatch at position: 1
  required type for a: sink array[0..-1, empty]
  but expression '[]' is of type: array[0..-1, string]

expression: @[]
```

### Additional Information

It works fine with Nim 1.6.8

**Comment by Menduist** [comment]
Seems to be introduced by https://github.com/nim-lang/Nim/pull/20091 cc @metagn

**Comment by ringabout** [comment]
It is the same issue as https://github.com/nim-lang/Nim/issues/20450

**Comment by Araq** [comment]
Overloading between `untyped` and `string` never was supported properly anyway. The real solution is to get rid of `untyped` as it leads to non-composable DSLs. Easier said than done, I know.

**Comment by metagn** [comment]
I came across this in #20091 but I thought it was an unrelated bug with calling templates with MCS instead.

Seq type inference currently replaces the `[]` part of `@[]` nodes with a typed node, but not the `@` part which may be a symbol with a resolved generic parameter (in this case `empty`). The fix would be to either unresolve this symbol or replace the `empty` generic parameter. I'm not sure exactly how to do these, hopefully someone can understand my explanation and implement it. Relevant lines (deal with `n[0]` here): https://github.com/nim-lang/Nim/blob/a15872ba9ecd118dc69f2346285d5c039e1efd42/compiler/semexprs.nim#L2408-L2411
