### ISSUE TITLE
Build failure with Pakku

### ISSUE THREAD

**Issue by zqqw** [nim-lang/Nim#20820]
### What happened?

There seem to be 2 new errors, both appear after the same commit yet are not present before:

```
pakku/src/utils.nim(448, 35) template/generic instantiation of `toHex` from here
/usr/lib/nim/pure/strutils.nim(954, 13) Warning: target type is larger than source type
  target type: 'BiggestUInt' (8 bytes)
  source type: 'uint8' (1 byte) [CastSizes]


pakku/src/format.nim(79, 8) Error: type mismatch: got <openArray[string], proc (s: string): int{.inline, noSideEf
fect, gcsafe.} | proc (s: openArray[char]): int{.noSideEffect, gcsafe.}>
but expected one of:
proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
  first type mismatch at position: 2
  required type for op: proc (x: T): S{.closure.}
  but expression 'runeLen' is of type: None
2 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them
```

### Nim Version

Nim devel, problem apparently created by:
commit 0b1989d7369d8616f623aafb0658a2b6d8cb5f73
Date:   Thu Oct 27 06:16:41 2022 -0600

**Comment by beef331** [comment]
The first is only a warning, the second is cause an overload was added and one must do `(proc(s: string): int {.inline.})(runeLen)` due to that change.

**Comment by beef331** [comment]
It seems there is a compiler bug as the above fix does not work here. One cannot disambiguate the two procs from `std/unicode`.

**Comment by metagn** [comment]
Can this be closed?
