### ISSUE TITLE
utf-8 (windows 7)

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [nim-lang/Nim#20835]
### What happened?

all executables change the console to utf-8 but dont restore them back when they exist, which causes all kinds of trouble with windows 7 and earlier. (like just doing DIR after NIM... closes the console)

### Nim Version

Nim Compiler Version 1.6.8 [Windows: i386]
Compiled at 2022-09-27

### Possible Solution

restore previous codepage before exit.

### Additional Information

nim
dir

**Comment by demotomohiro** [comment]
Compile with `-d:nimDontSetUtf8CodePage` option that stop changing code page.
