### ISSUE TITLE
Segfault on large memoized fibonacci computation

### ISSUE THREAD

**Issue by Siltaar** [nim-lang/Nim#20853]
Using drujensen's Nim implementation of the fibonacci computation and adding memoization :

```nim
import memo
proc fib(n: int): int {.memoized.} =
  if n <= 1:
    return n
  result = fib(n - 1) + fib(n - 2)
echo fib(261980)
```

I get 20 segfaults over 20 runs.

```console
$ ./nim --version
Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release
$ ./nim c -d:release -r ~/[…]/fib_memo.nim
Hint: used config file '/home/[…]/nim-1.6.8/config/nim.cfg' [Conf]
Hint: used config file '/home/[…]/nim-1.6.8/config/config.nims' [Conf]
Hint: gc: refc; opt: speed; options: -d:release
9914 lines; 0.024s; 8.637MiB peakmem; proj: /home/[…]/fib_memo.nim; out: /home/[…]/fib_memo [SuccessX]
Hint: /home/[…]/fib_memo  [Exec]
Error: execution of an external program failed: '/home/[…]/fib_memo '
$ /home/[…]/fib_memo
[1]    12079 segmentation fault  /home/[…]/fib_memo
```
The same behavior was seen with nim 1.6.6 Compiled at 2022-05-22.
With a slightly smaller rank I get 50% of segfaults and 50% of OverflowDefect.

`echo fib(261864)  # segfault over 50% of 14 executions`

I would expect the OverflowDefect to popup each time with `-d:release` option.

With `-d:danger` overflow defects seems not be detected at all, example :  `echo fib(261864) -> -480436062371201312` (but I guess it's part of the danger).

**Comment by Araq** [comment]
"out of memory" cannot be reliably detected on Linux if overcommitting is enabled which is the default.

**Comment by Siltaar** [comment]
I don't know what is the performance gain of using "overcommitting", nor exactly what it is, but I do know that segfaults should not occur in release mode / production.

If it's an unsafe settings, shouldn't it be bundled with `-d:danger` ?

**Comment by Araq** [comment]
Well it's a Linux specific thing. We cannot do anything about it except educating people about it. "out of memory" cannot be reliably detected on Linux, that's just a fact and Nim is only programming language, not magic.

**Comment by Siltaar** [comment]
Ah, ok… thanks for the education then.
