### ISSUE TITLE
[ORC] Bad codegen for global pointer to iterator

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#20866]
### What happened?

```nim
proc foo() =
  iterator bar() {.closure.} =
    discard
  var g {.global.} = rawProc(bar)

foo()
```
```
nim c test.nim
```
```
.../y/.cache/nim/test2_d/@mtest.nim.c: In function ‘NimMainModule’:
.../.cache/nim/test2_d/@mtest.nim.c:269:9: error: ‘colonenv_’ undeclared (first use in this function)
  269 |         colonenv_ = T100001_;
      |         ^~~~~~~~~
.../.cache/nim/test2_d/@mtest.nim.c:269:9: note: each undeclared identifier is reported only once for each function it appears in
```

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-11-17
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 1707bc4a992bc966a7439facb9ee819023c22f77
active boot switches: -d:release

### Additional Information

Compiles and runs fine with `--mm:refc`.

**Comment by bung87** [comment]
shall we disallow this as well after https://github.com/nim-lang/Nim/pull/20812, let user seperate the declaration and initialization

**Comment by yglukhov** [comment]
Maybe, but unlike #3505 and #5132, there's no local captures, so the code is technically correct.

**Comment by yglukhov** [comment]
Also like I said, it works as expected with `--mm:refc`, so disallowing it is a breaking change kinda

**Comment by bung87** [comment]
I know they are slightly different, however the solution are same, whether transform by compiler or by user. let me see other compiler developer says.

**Comment by yglukhov** [comment]
This code cannot be transformed by user if you take generics into account

**Comment by bung87** [comment]
I mean 

```nim
proc foo() =
  iterator bar() {.closure.} =
    discard
  var g {.global.} :pointer 
  g = rawProc(bar)

foo()
```

**Comment by yglukhov** [comment]
Ah I see what you mean, makes sense. However, I'm currently relying on a trick that involves using a "local" global before it's "definition" function is called, if that makes sense. It's some involved macro stuff in https://github.com/yglukhov/yasync. Simplified, it looks like this:

```nim
proc foo() =
  iterator bar() {.closure.} =
    discard
  var g {.global.}  = rawProc(bar)
  registerIterPtr(foo, g) # This is a macro that stores association of sym `foo` to `g` in compile time.
```
So that later we can retrieve `g` belonging to `foo`. Note that it cannot be done outside of `foo` if it is generic. The sample omits some details for the sake of simplicity. I'm not entirely sure if that's valid to rely on this behavior, but it's been working great so far with refc and I couldn't yet find a better way to do it.

**Comment by bung87** [comment]
I don't look deep into your project code , u may try my patch for https://github.com/nim-lang/Nim/pull/20784 see if it works , I guess better do transform on user side , otherwise when there's error occurred user may get confusing error message, so basically separate declaration and initialization then use `once`
