### ISSUE TITLE
Doesn't work, calculated values of type arguments of type `static` cannot be type arguments of fields.

### ISSUE THREAD

**Issue by momeemt** [nim-lang/Nim#20880]
### What happened?

When a value obtained by some simple calculation on a static type variable of a structure is set to a field type variable, the calculation is not performed and the type is wrong.
Also, simply calculating `echo Parent[1]().child.data.len` would output the correct value of `3`, but if another `Parent` type structure existed, the output would be wrong.

```nim
type
  Child [n: static int] = object
    data: array[n, int]
  
  Parent [n: static int] = object
    child: Child[3*n]

const n = 3
echo typeof Parent[n*3]()
echo typeof Parent[1]().child
echo Parent[1]().child.data.len
```

This is broken even in the development version, ver. 1.7.3 (x86_64 intel macos).

### Nim Version

Nim Compiler Version 1.6.8 [MacOSX: arm64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise

### Current Standard Output Logs

```shell
Parent[9]
Child[3 * n]
27
```

### Expected Standard Output Logs

```shell
Parent[9]
Child[3]
3
```

**Comment by momeemt** [comment]
I am interested in contributing to Nim and would like to fix it if possible. But I am new to compiler reading so I didn't know where the `static` type is made. I would like some hints if possible.

**Comment by bung87** [comment]
you can start from `proc semArrayIndex`

**Comment by momeemt** [comment]
thanks! I'll try to read some of it.

**Comment by momeemt** [comment]
I have looked for the code in question as follows, but could not find it with my current knowledge. I will try to find other problems that I can tackle and will look into it again when I have a better understanding of the Nim compiler.

https://zenn.dev/momeemt/scraps/4c1b2e06c74514
