### ISSUE TITLE
Unspecified generic on default value segfaults the compiler

### ISSUE THREAD

**Issue by HugoGranstrom** [nim-lang/Nim#20883]
### What happened?

```nim
proc foo*[U](x: U = U(1e-6)) =
  echo x
  
foo()
```
Not providing the type `U` causes a segmentation fault in the compiler instead of giving an error. Removing the `U(...)` around `1e-6` works, though. 

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-11-19
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: fe43f751eb9a83f84cc93aa0d752c3658232002d
active boot switches: -d:release

### Current Standard Output Logs

```shell
Segmentation fault (core dumped)
```

### Expected Standard Output Logs

```shell
That the compiler gives an error about the unspecified generic.
```

### Additional Information

This segfaults on all versions of Nim. (tested back to v1.0)

**Comment by juancarlospaco** [comment]
!nim c

```nim
func f[U](x: U = U(1e-6)) = discard
f()
```
