### ISSUE TITLE
Extremely confusing error message with invalid syntax `of: '+':`

### ISSUE THREAD

**Issue by skyfallwastaken** [nim-lang/Nim#20922]
### What happened?

When using this bad code:

```nim
type Token = enum 
    incDataPtr,
    incDataPtrByte

proc mapInstrToToken(instr: char): Token = 
    case instr:
    of '>':
        incDataPtr
    of: '+':
        incDataPtrByte
```

You get an  _extremely_ confusing error message (see "Current Standard Output Logs")

### Nim Version

❯ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Standard Output Logs

```
/home/skyfall/Projects/quickbf/src/lexer.nim(17, 5) Error: illformed AST: 
of :
  '+'(
    incDataPtrByte,
  of :
    '-':
      decDataPtrByte)
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: quickbf
        ... Execution failed with exit code 1
        ... Command: /home/skyfall/.nimble/bin/nim c --colors:on --noNimblePath -d:NimblePkgVersion=0.1.0 --hints:off -o:/home/skyfall/Projects/quickbf/quickbf /home/skyfall/Projects/quickbf/src/quickbf.nim
```

### Possible Solution

The error should probably tell you that `of: x:` is invalid and to use `of x:` instead.

**Comment by metagn** [comment]
The issue is that `of:` parses at all
