### ISSUE TITLE
VM breaking at template parameter evaluation.

### ISSUE THREAD

**Issue by quantumedbox** [nim-lang/Nim#20937]
### Description

VM breaks at trying to execute `volume` procedure:
```nim
type
  Vec3*[T: SomeNumber] {.bycopy.} = tuple[x, y, z: T]

func volume*[T](v: Vec3[T]): T =
  when T is SomeUnsignedInt:
    v.x * v.y * v.z
  else:
    abs (v.x * v.y * v.z)

type
  Matrix3*[C: static Vec3[uint], T] = object
    cells: array[C.area, T]

let m = Matrix3[(1.uint, 1.uint, 1.uint), uint](cells: [0.uint])
```

### Nim Version

1.6.8

### Current Output

```text
/usercode/in.nim(7, 15) Error: cannot generate VM code for *
```

### Expected Output

```text
Successful compilation.
```

### Additional Information

Changing 'volume' func to template fixes the problem, so, breaking probably happens on procedure boundaries.

**Comment by metagn** [comment]
Related #19916, #20514 (generic object, static parameter, array index)
