### ISSUE TITLE
`discardable` procedure with arc/orc generate unnecessary `=destroy` call and crash the program.

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#20941]
### Description

Example code:
```nim
type Node = ref object

proc newNode(): Node {.discardable.} =
  new(result)

proc main() =
  if false:
    newNode()

main()
```

Compile with --expandArc:
```nim
var :tmpD
if false:
  :tmpD = newNode()
  :tmpD
`=destroy`(:tmpD) # <- crash for complex object because :tmpD is not avaliable
```

Add discard:
```nim
if false:
  var :tmpD
  discard
    :tmpD = newNode()
    :tmpD
  `=destroy`(:tmpD) # <- OK
```

Add a left value
```nim
if false:
  var tmp
  tmp = newNode()
  `=destroy`(tmp) # <- OK
```

### Nim Version

Nim Compiler Version 1.7.3

**Comment by ringabout** [comment]
It is a bit hard to fix since the compiler doesn't distinguish the the if statement from the if expression well.

```nim
type Node = ref object

proc newNode(): Node {.discardable.} =
  new(result)

proc main() =
  if false:
    newNode()

  var x = if true:
     ...
     else:
       newNode()
    
main()
```

for example, `semIf` even transitions between `nkIfStmt` and `nkIfExpr` according to the type of the node. It's hard to know in the case above, since both of the cases have the type of `Node`.

```nim
  if isEmptyType(typ) or typ.kind in {tyNil, tyUntyped} or
    result.transitionSonsKind(nkIfStmt)
  else:
    result.transitionSonsKind(nkIfExpr)
```

**Comment by Araq** [comment]
Where is the bug? The resulting C code does set the temporary to `nil` first even though the AST listing doesn't show it. No crash for me either.

**Comment by Araq** [comment]
Valgrind also says it's fine, feel free to re-open.

**Comment by ringabout** [comment]
IIRC, I reproduced the issue based on https://github.com/khchen/xl/tree/22d4ea2d147467967527d8fd64e77d2c040f1e91

```shell
nim c -r xl/demo.nim
```

**Comment by Araq** [comment]
That's still not a bug report, we need a minimal example.
