### ISSUE TITLE
The proc parameter appears to hand over ownership

### ISSUE THREAD

**Issue by AndrewGPU** [nim-lang/Nim#20948]
### Description

import std/threadpool
{.experimental: "parallel".}

proc sum(i, j: int; a: array[8, int]): int =
  echo a.len
  for k in i .. j:
    result += a[k]

proc main =
  var a: array[8, int]
  for i in a.low .. a.high:
    a[i] = i

  var s1, s2: int
  parallel:
    s1 = spawn sum(0, 3, a)
    s2 = spawn sum(4, 7, a)
  echo s1, " + ", s2

main()

### Nim Version

Nim Compiler Version 1.6.10 [MacOSX: amd64]
Compiled at 2022-11-27
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
nim c --threads:on  --gc:arc -d:useMalloc --passC:-flto --passC:-march=native -r "t.nim"

............................................................................................SIGSEGV: Illegal storage access. (Attempt to read from nil?)

remove --gc:arc ，can work normally
```

### Expected Output

```text
6 + 22
```

### Possible Solution

remove --gc:arc ，can work normally

or 
modify the code
import std/threadpool
{.experimental: "parallel".}

proc sum(i, j: int; a: ptr array[8, int]): int =
  for k in i .. j:
    result += a[][k]

proc main =
  var a: array[8, int]
  for i in a.low .. a.high:
    a[i] = i

  var s1, s2: int
  parallel:
    s1 = spawn sum(0, 3, addr(a))
    s2 = spawn sum(4, 7, addr(a))
  echo s1, " + ", s2

main()

but :

I think there should be no transfer of ownership in this place, it should be passed by value or by reference, and the second thread needs to be used.

**Comment by ringabout** [comment]
Works with the devel branch.
