### ISSUE TITLE
use thread  inexplicable pannic

### ISSUE THREAD

**Issue by AndrewGPU** [nim-lang/Nim#20949]
### Description

proc sum(i: int) {.thread.} =
  var j, result: int
  while j < i:
    inc(j)
    result += j
  echo result

proc main =
  var th1, th2: Thread[int]
  createThread(th1, sum, 1e7.int)
  createThread(th2, sum, 1e7.int)
  joinThreads(th1, th2)

main()

### Nim Version

Nim Compiler Version 1.6.10 [MacOSX: amd64]
Compiled at 2022-11-27
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
.....................................................fatal.nim(54)            sysFatal
Error: unhandled exception: index 6 not in 0 .. 5 [IndexDefect]
```

### Expected Output

```text
50000005000000
50000005000000
```

**Comment by ringabout** [comment]
Please format your code.

**Comment by ringabout** [comment]
I cannot reproduce it on Linux with ARC in 1.6.10

```nim
proc sum(i: int) {.thread.} =
  var j, result: int
  while j < i:
    inc(j)
    result += j
  echo result

proc main =
  var th1, th2: Thread[int]
  createThread(th1, sum, 1e7.int)
  createThread(th2, sum, 1e7.int)
  joinThreads(th1, th2)

main()
```

**Comment by AndrewGPU** [comment]
It is because the compilation did not add --threads:on, but this error report is completely incomprehensible, because it did not add --threads:on, you can try without adding parameters, whether it can be reproduced

**Comment by AndrewGPU** [comment]
> 我无法在 1.6.10 中使用 ARC 在 Linux 上重现它
> 
> ```nim
> proc sum(i: int) {.thread.} =
>   var j, result: int
>   while j < i:
>     inc(j)
>     result += j
>   echo result
> 
> proc main =
>   var th1, th2: Thread[int]
>   createThread(th1, sum, 1e7.int)
>   createThread(th2, sum, 1e7.int)
>   joinThreads(th1, th2)
> 
> main()
> ```

It is because the compilation did not add --threads:on, but this error report is completely incomprehensible, because it did not add --threads:on, you can try without adding parameters, whether it can be reproduced

**Comment by ringabout** [comment]
I don't think so, please specify your compilation options.

With `nim c -r --threads:on --mm:arc`

```
50000005000000
50000005000000
```

With `nim c -r --threads:off --mm:arc`

```
Error: undeclared identifier: 'Thread'
```

**Comment by AndrewGPU** [comment]
> nim c -r  --mm:arc 
able to reproduce， won't remind Error: undeclared identifier: 'Thread'
