### ISSUE TITLE
nimPreviewSlimSystem deprecation messages are weird

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#20967]
### Description

Knew about this already (and I bet others did as well) and couldn't think of a solution so didn't report for a while.

Currently deprecation messages for `nimPreviewSlimSystem` are either:

1. directly in system whenever `nimPreviewSlimSystem` is not defined:
   https://github.com/nim-lang/Nim/blob/5658e8e5c5e3852f877eb0501b12e664114de567/lib/system/formatfloat.nim#L4
   These do not get emitted as messages because system has `warnings:off` by default or something, but doing `import system` or `from system import ...` gives `Warning: system is deprecated`.
2. (bad one) directly inside the new modules themselves whenever `nimPreviewSlimSystem` is not defined:
   https://github.com/nim-lang/Nim/blob/5658e8e5c5e3852f877eb0501b12e664114de567/lib/std/formatfloat.nim#L13
   This means whenever we do the right thing and import these modules, we get a complaint (although we should probably only import `when (NimMajor, NimMinor) >= (1, 7)`).

### Nim Version

09b8f98

### Possible Solution

This might require adding temporary behavior for this situation to the compiler. For example:

```nim
when not defined(nimPreviewSlimSystem):
  import std/formatfloat
  export formatfloat {.slimSystemDeprecated.}
  # or
  export formatfloat {.deprecated: "import std/formatfloat explicitly".}
```

Don't know if this is feasible.

**Comment by Araq** [comment]
Is this problem really so bad to justify the added complexity in the compiler?

**Comment by metagn** [comment]
The problem IMO defeats the entire purpose of the preview flag. The messages are confusing enough that you're better off enabling it by default.

At least if you generalize the new required compiler behavior to `export {.deprecated.}` it wouldn't have to be a temporary behavior and would prevent this problem from happening again in the future. I wouldn't know how to implement this though and my implementation of the specialised version is already flawed.

**Comment by zqqw** [comment]
This discussion seemed helpful to me, in terms of amending compiled projects, not sure if it's relevant here, and you may have seen it already, or have something better in mind:
https://forum.nim-lang.org/t/9680
cblake  ...
```
when not declared(system.stdout): import std/syncio
```
is maybe better -  allowing code to work like before in both old & new Nim's with or without -d:nimPreviewSlimSystem or probably later Nim's...

**Comment by metagn** [comment]
At the very least for now we can remove the confusing deprecated messages.

**Comment by metagn** [comment]
I agree that this code from above should be the natural conclusion:

```nim
when not declared(system.stdout): import std/syncio
```

Deprecation messages in general kind of conflict with this, and as there are no deprecation messages anymore, I think this is good to close
