### ISSUE TITLE
Regression in `int64` type matching since #20829

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#20995]
### Description

The recent PR #20829 caused a regression in how `int64` is type matched:

```nim
echo int64 is (SomeNumber and not(uint32|uint64|uint|int))
echo int64 is SomeNumber
echo int64 is ((uint32|uint64|uint|int))
echo int64 is (not(uint32|uint64|uint|int))
```

### Nim Version

```nim
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-02
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 10b6e4f5b4a119a8fa42f82a24ae7e4b08b2c103
active boot switches: -d:release -d:danger
```

### Current Output

```text
false
true
false
false
```

### Expected Output

```text
true
true
false
true
```

edit: oops, that new issue form made me _forget_ about the title. :see_no_evil:

**Comment by metagn** [comment]
1st, 2nd and 4th line are consistent with `int is int64`, which I believe that PR intended to make true when `sizeof(int) == sizeof(int64)`, but that does not explain the 3rd line at all.

**Comment by arnetheduck** [comment]
> 1st, 2nd and 4th line are consistent with `int is int64`, which I believe that PR intended to make true when `sizeof(int) == sizeof(int64)`, but that does not explain the 3rd line at all.

wait, when did this happen? it's a significant (breaking) change

**Comment by metagn** [comment]
It is significant, as said it was in #20829 which didn't document the change
