### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by russellb23** [nim-lang/Nim#21003]
`OrderedTableRef` seems to generate the above error/bug.

My code is as below:
```

import strutils
import std/tables
import std/sha1
import os

proc getFileHashe(loc: string): OrderedTableRef[string, SecureHash] =
  var file_hashes = initOrderedTable[string, string]()
  for f in os.walkDirRec(loc):
    file_hashes[f] = f

when isMainModule:
  var dirname = "/home/russellb/Documents/"

  let ss = getFileHashe(dirname)
  for file, val in ss:
    echo(file,  $val)
```

Error stack: 

> 
> 
> ~~> nim c -r src/dupfinder.nim                                                   1 
> Hint: used config file '/etc/nim/nim.cfg' [Conf]
> Hint: used config file '/etc/nim/config.nims' [Conf]
> .............................................................................................
> /home/russellb/Development/nim_devel/projects/dupfinder/src/dupfinder.nim(5, 8) Warning: imported and not used: 'strutils' [UnusedImport]
> CC: stdlib_io.nim
> CC: stdlib_system.nim
> CC: stdlib_sha1.nim
> CC: stdlib_tables.nim
> CC: dupfinder.nim
> Hint:  [Link]
> Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
> 53268 lines; 3.323s; 75.555MiB peakmem; proj: /home/russellb/Development/nim_devel/projects/dupfinder/src/dupfinder.nim; out: /home/russellb/Development/nim_devel/projects/dupfinder/src/dupfinder [SuccessX]
> Hint: /home/russellb/Development/nim_devel/projects/dupfinder/src/dupfinder  [Exec]
> Finding duplicates...
> Traceback (most recent call last)
> /usr/lib/nim/pure/collections/tables.nim(2125) dupfinder
> /usr/lib/nim/pure/collections/tables.nim len
> SIGSEGV: Illegal storage access. (Attempt to read from nil?)
> Error: execution of an external program failed: '/home/russellb/Development/nim_devel/projects/dupfinder/src/dupfinder

**Comment by hamidb80** [comment]
`getFileHashe ` does not return anything

**Comment by russellb23** [comment]
> `getFileHashe ` does not return anything

oh my bad.
