### ISSUE TITLE
iterator index for split not working

### ISSUE THREAD

**Issue by depperm** [nim-lang/Nim#21007]
### Description

Putting `split(myString, " ")` in the same line of an iterator with an index does not work. Setting a variable before hand to the result of `split` does work

Working code:
```
import strutils
var n = "this is a test"

var x = split(n," ")
for i, a in x:
  echo i,a
```
Code that does not work:
```
import strutils
var n = "this is a test"

for i, a in split(n," "):
  echo i,a
```

Related #15360?

### Nim Version

1.6.8

### Current Output

```text
Error: wrong number of variables
```

### Expected Output

```text
0this
1is
2a
3test
```

**Comment by bung87** [comment]
`var x = split(n," ")` when assign to variable, `x` is `seq[string]` so the index is concept belongs to `seq` not iterator.

**Comment by metagn** [comment]
You can use `enumerate`.

```nim
import strutils, std/enumerate
var n = "this is a test"
for i, a in enumerate(split(n," ")):
  echo i,a
```

The first example calls the `pairs` iterator on `seq`, the second example directly calls the `split` iterator (in contrast to the `split` proc) which it is not possible to define a pairs iterator on and you have to use `enumerate`.

**Comment by metagn** [comment]
Why reopen? I guess we could have more info in the error message

**Comment by ringabout** [comment]
Workaround which calls the `func` version of split

```nim
import strutils
var n = "this is a test"

for i, a in pairs(split(n," ")):
  echo i,a
  ```
