### ISSUE TITLE
setutils import behaves strangely

### ISSUE THREAD

**Issue by DestyNova** [nim-lang/Nim#21015]
### Description

This code produces the error "cannot open file: setutils" whether I use `nim c` or `nim r`:

```nim
import setutils

echo "Hello"
```

It works with `std/setutils`.

This program produces a compile error in both 1.6.10 and 1.6.8:

```nim
import std/setutils,sequtils

proc wat(xs: seq[string]): int =
  xs.map(toSet)
  0
```

Output:
```
nim c test_setutils.nim
Hint: used config file '/home/omf/.choosenim/toolchains/nim-1.6.8/config/nim.cfg' [Conf]
Hint: used config file '/home/omf/.choosenim/toolchains/nim-1.6.8/config/config.nims' [Conf]
..............................................................
Error: internal error: /home/runner/work/nightlies/nightlies/nim-1.6.8/compiler/seminst.nim(336, 18)
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```
### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release
```

**Comment by MichalMarsalek** [comment]
The first seems to work in the playground: https://play.nim-lang.org/#ix=4hF9

**Comment by ringabout** [comment]
I cannot reproduce it on Windows either.

**Comment by DestyNova** [comment]
Hmm, I can't reproduce the first bit with `nim r` anymore, but I'm still getting "cannot open file: setutils" if I write `import setutils` instead of `import std/setutils`. Is that just some basic read-the-docs thing I've gotten wrong?

(update)
Ok, I had assumed the `std/` was always an optional thing to differentiate between stdlib modules and user modules. But [according to this](https://forum.nim-lang.org/t/7307) that's not the case.

**Comment by DestyNova** [comment]
@MichalMarsalek try this program in the playground:

```nim
import std/setutils,sequtils

proc wat(xs: seq[string]): int =
  xs.map(toSet)
  0
```
I guess it's a separate issue to the "setutils vs std/setutils" thing?

**Comment by metagn** [comment]
The modules in the [lib/std folder](https://github.com/nim-lang/Nim/blob/devel/lib/std/) need to be imported using `std/` AFAIK

**Comment by ringabout** [comment]
> I guess it's a separate issue to the "setutils vs std/setutils" thing?

It has been fixed on the devel branch and reports the right error

```
Error: type mismatch: got <seq[string], template (iter: untyped): untyped>
but expected one of:
proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
  first type mismatch at position: 2
  required type for op: proc (x: T): S{.closure.}
  but expression 'toSet' is of type: template (iter: untyped): untyped
  Calling convention mismatch: got '{.nimcall.}', but expected '{.closure.}'.

expression: map(xs, toSet)
```

**Comment by DestyNova** [comment]
> The modules in the [lib/std folder](https://github.com/nim-lang/Nim/blob/devel/lib/std/) need to be imported using `std/` AFAIK

Gotcha. I'm not sure why some modules are in the "std" folder and some aren't, though. And you can (I think) add the std prefix to the ones that aren't. Just seems a bit inconsistent from a UX point of view.

**Comment by DestyNova** [comment]
> > I guess it's a separate issue to the "setutils vs std/setutils" thing?
> 
> It has been fixed on the devel branch and reports the right error
> 
> ```
> Error: type mismatch: got <seq[string], template (iter: untyped): untyped>
> but expected one of:
> proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
>   first type mismatch at position: 2
>   required type for op: proc (x: T): S{.closure.}
>   but expression 'toSet' is of type: template (iter: untyped): untyped
>   Calling convention mismatch: got '{.nimcall.}', but expected '{.closure.}'.
> 
> expression: map(xs, toSet)
> ```

Thanks, I'll close this issue then if one part is me not knowing how "std/" works and the other part is already fixed in devel.

**Comment by metagn** [comment]
> I'm not sure why some modules are in the "std" folder and some aren't, though. 

New modules tend to go in the std folder, while old modules have always been in the lib/pure folder. Otherwise I don't really know the reason for requiring the `std/` prefix.

**Comment by DestyNova** [comment]
> > I'm not sure why some modules are in the "std" folder and some aren't, though.
> 
> New modules tend to go in the std folder, while old modules have always been in the lib/pure folder. Otherwise I don't really know the reason for requiring the `std/` prefix.

I see what you mean. Could be an artifact of old decisions that are hard to change for compatibility reasons I guess.
