### ISSUE TITLE
Wrong default for "last" in strutils.find.

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#21032]
### Description

One signature of "find" is

`find(s: string; sub: char; start: Natural = 0; last: Natural = 0): int`

If "last" is 0, it is interpreted as "s.high". This is wrong as 0 is a valid final index. That means that "abcde".find('d', 0, 0) returns 3 instead of -1.

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
For"abcde".find('d', 0, 0), the current output is 3.
```

### Expected Output

```text
For"abcde".find('d', 0, 0), the expected output is -1.
```

### Possible Solution

No solution except writing its own function or finding a way to avoid value 0 for "last".

### Additional Information

This issue has been fixed in current development version. The default value for "last" is now -1 which is interpreted as "s.high". The value 0 is interpreted as a standard index.

**Comment by Araq** [comment]
Closing as it's fixed in devel.
