### ISSUE TITLE
Don't allow vars of the same name to be declared in nested blocks

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#21035]
### Description

Here's a sample test case:

```nim
proc myTest(input: string) =

  var str = "abc"

  if input == "def":
    var str = "def"  ## BUG, doesn't assign to the outer var str

  echo str


# Main
myTest("def")
```

### Nim Version

1.6.10

### Current Output

```text
Output: abc
```

### Expected Output

```text
The compiler should raise an error for the 2nd declaration of str in the nested block.
```

### Possible Solution

A change to the Nim compiler to raise an error for this case.

### Additional Information

By not raising an error, subtle bugs can be introduced into the source that are difficult to track down.

**Comment by juancarlospaco** [comment]
`if` has its own scope, therefore by definition thats Ok.
Same happens with `block` and others, `when` does not create a new scope.

**Comment by jfilby** [comment]
I will have to think of writing my own Nim linter in that case. To me it's begging for bugs to be introduced, even if theoretically it is OK. But thanks for replying.

**Comment by juancarlospaco** [comment]
If you change it likely a lot of code may break,
because some stuff may be triggered by going out of scope like Destructors,
also because function arguments are immutable by default its a common practice to do:

```nim
proc f(a: int) =
  var a = a
  inc a
```

**Comment by jfilby** [comment]
OK I'll close the issue.
