### ISSUE TITLE
Querying `ccompilerPath` returns empty string

### ISSUE THREAD

**Issue by ire4ever1190** [nim-lang/Nim#21033]
### Description

Trying to find the path to the compiler being used returns nothing

```nim
import std/compilesettings

echo "Compiler: ", querySetting(ccompilerPath)
```

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-11-26
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 2709898a5eeb97ca4692296b25932aeb15456c0d
active boot switches: -d:release

### Current Output

```text
Compiler:
```

### Expected Output

```text
Compiler: /usr/bin/gcc (Or which ever compiler I am using)
```

### Possible Solution

Either mimic the logic or call [extccomp/initVars](https://github.com/nim-lang/Nim/blob/devel/compiler/extccomp.nim#L364) to make sure the compiler is properly set. Not too certain if that would fix it though

**Comment by rockcavera** [comment]
I don't think this is a problem, but an expected result when `<compiler>.path` is not set, as it uses the compiler executable that is in the system PATH.

**Comment by ire4ever1190** [comment]
Ah, thought it returned path to compiler
Passing `--gcc.path:/usr/bin` returns `Compiler: /usr/bin` so it works
