### ISSUE TITLE
getTime with vmopsDanger is broken

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#21045]
### Description

`vmopsDanger` is an undocumented experimental feature that has to be enabled in the command line, and unlocks 3 compile time hooks to procs with side effects:

https://github.com/nim-lang/Nim/blob/d6b485493d712a20155a3e77f44c19c34e47ea73/compiler/vmops.nim#L321-L332

I don't know the full extent of the problems with this but one of these, `getTime`, is broken:

```nim
# compile with --experimental:vmopsDanger
import times

const foo = getTime()
let bar = foo
```

### Nim Version

b2c7019

### Current Output

```text
unhandled exception: field 'sym' is not accessible for type 'TNode' using 'kind = nkStrLit' [FieldDefect]
```

### Expected Output

```text
compiles
```

**Comment by ringabout** [comment]
It is a long-standing issue because `toLit` is too broken irrc.
