### ISSUE TITLE
do: without parentheses crashes the compiler

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2104]
Example:

``` nim
proc foo(f: proc()) =
  f()

foo do:
  echo 1
```

Using:

``` nim
foo do():
  echo 1
```

instead works.

Also, is it intentional that:

``` nim
foo:
  echo 1
```

doesn't work anymore (I realize that this is part of the language that is in flux; I just want to ascertain whether it's a feature or a bug)?

**Comment by Araq** [comment]
I get no crashes here, but slightly confusing error messages.

**Comment by rbehrends** [comment]
Hmm, upon further review, it looks like I was actually experiencing this with an older version of the compiler.

That said, I'm not sure why ``do`` and ``do()`` would exhibit different behavior. At the very least, it's confusing.

**Comment by Araq** [comment]
do() is a lambda, do is a block. do() will go away, 'do' will stay. That's my current plan, at least.

**Comment by Yardanico** [comment]
@Araq works now and doesn't display any warnings/errors

**Comment by Yardanico** [comment]
All 3 of these work:
```nim
proc foo(f: proc()) =
  f()

foo do:
  echo 1


foo do():
  echo 1

foo:
  echo 1
```
