### ISSUE TITLE
Sourcemaps don't include line number information

### ISSUE THREAD

**Issue by leo60228** [nim-lang/Nim#21052]
### Description

Sourcemaps were implemented for the JS backend in #7508 by adding a `// line` comment to the JS output and searching for that string in the sourcemap code: https://github.com/nim-lang/Nim/blob/f8e64d879cba1a035eec699fa41007b8a5a96913/compiler/sourcemap.nim#L178

However, #18048 made many aesthetic changes to JS output, including changing `// line` to a block comment: https://github.com/nim-lang/Nim/commit/6a5973882bb0c4134a0e454ea4ae69dc54815f27#diff-23cf9e17bd5f77efe59980e5e3a715c3d2bba381c98e16097cca8cd461c7ab28L707

```diff
 proc lineDir(config: ConfigRef, info: TLineInfo, line: int): Rope =
-  ropes.`%`("// line $2 \"$1\"$n",
+  ropes.`%`("/* line $2 \"$1\" */$n",
          [rope(toFullPath(config, info)), rope(line)])
```

The sourcemap code was not updated to match. This means that sourcemaps no longer include line number information, which is the primary use for them.

### Nim Version

Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Possible Solution

The comment should either be changed back to `//` or the sourcemap code should be updated to handle it being a block comment.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Can confirm this also is an issue for 1.6.10, and the latest devel build (if confirmation is even needed)

**Comment by rafi16jan** [comment]
When will Nim 2.0 stable version be released?
