### ISSUE TITLE
Docs options list is parsed incorrectly by markdown

### ISSUE THREAD

**Issue by ire4ever1190** [nim-lang/Nim#21055]
### Description

An options list gets wrongly parsed when using the markdown parser

Example is the devel [Compiler User Guide](https://nim-lang.github.io/Nim/nimc.html#compiler-usage) which looks fine when using `rst2html` instead of `md2html`

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-08
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: d6b485493d712a20155a3e77f44c19c34e47ea73
active boot switches: -d:release

### Current Output

```text
https://nim-lang.github.io/Nim/nimc.html#compiler-usage
```

### Expected Output

```text
https://nim-lang.org/docs/nimc.html#compiler-usage
```

**Comment by ringabout** [comment]
cc @a-mr

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/21633
