### ISSUE TITLE
Please define both xxxxxA and xxxxxW function in winlean

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#21071]
### Description

There is define symbol -d:useWinAnsi to control we should use unicode version function or ansi version function, but some file will always use the unicode function like getEnvironmentStringsW in std/envvars, formatMessageW in std/oserrors.nim, so when I add -d:useWinAnsi flag, the compiler will complain "cannot find the function xxxxW".

```nim
import os
putEnv("hello", "world")
```

I think we should define both xxxxA and xxxxW function in winlean, because they have different name. So you can always use any of them despite of useWinAnsi defined or not.

### Nim Version

Nim Compiler Version 1.7.3 [Windows: amd64]
Compiled at 2022-12-11
Copyright (c) 2006-2022 by Andreas Rumpf

active boot switches: -d:release

### Current Output
```
nim c -d:useWinAnsi t1.nim
d:\Tool\Nim\lib\std\oserrors.nim(54, 70) template/generic instantiation of `!=` from here
d:\Tool\Nim\lib\std\oserrors.nim(53, 10) Error: undeclared identifier: 'formatMessageW'
d:\Tool\Nim\lib\std\oserrors.nim(54, 70) template/generic instantiation of `!=` from here
d:\Tool\Nim\lib\std\oserrors.nim(53, 24) Error: attempting to call routine: 'formatMessageW'
  found 'formatMessageW' [unknown declared in d:\Tool\Nim\lib\std\oserrors.nim(53, 10)]
d:\Tool\Nim\lib\std\oserrors.nim(54, 70) template/generic instantiation of `!=` from here
d:\Tool\Nim\lib\std\oserrors.nim(53, 24) Error: attempting to call routine: 'formatMessageW'
  found 'formatMessageW' [unknown declared in d:\Tool\Nim\lib\std\oserrors.nim(53, 10)]
d:\Tool\Nim\lib\std\oserrors.nim(54, 70) template/generic instantiation of `!=` from here
d:\Tool\Nim\lib\std\oserrors.nim(53, 24) Error: attempting to call undeclared routine: 'formatMessageW'
d:\Tool\Nim\lib\std\envvars.nim(189, 16) Error: undeclared identifier: 'getEnvironmentStringsW'
```

**Comment by tersec** [comment]
What's are remaining use cases of `useWinAnsi`? The last Windows versions which required the `*A` versions were Win9x.

If it's not working now, by definition, people are not relying on it, so no compatibility issues in not addressing it.

**Comment by Araq** [comment]
`useWinAnsi` is a dead switch. Officially since version x.y.
