### ISSUE TITLE
Add a way to set the line info of a NimNode

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#21098]
### Summary

I have a macro which generates code from a template file. If the user writes something incorrect in their template (e.g. misspell an identifier) the macro generates invalid code. However the compilation error only points to where the erroneous node was created in the macro. It would be nice if macros where able to attach line information to NimNodes or use something similar to the `line` pragma in order to add information about what file the node was actually generated from.

### Description

Having this feature would allow us to write more debugable macros.

### Links

Might be related to this old issue, but I believe this has been kind-of solved: https://github.com/nim-lang/Nim/issues/5832

**Comment by Araq** [comment]
The idea is that you copy from nodes that have the line information you seek, not that you're able to conjure up line information which might have no connection to reality.

**Comment by PMunch** [comment]
Problem is that there is no node with the line info I seek. I read in a HTML file which gets turned into a procedure that replaces parts of it with information from the code. But say I want to give the user a hint about which file caused the error (my system reads all files in a folder), and where in the file they made their mistake there is currently no way to do that. And as with everything I could lie to the user, but why would I? It would be like throwing an exception if nothing had gone wrong.

**Comment by Araq** [comment]
From my point of view making up line information is where the macro code would begin to "lie".

**Comment by PMunch** [comment]
But it's not actually making up line information, it's extracting line information that Nim on its own is unable to get. I'm reading a file which isn't valid Nim, but which contains some valid Nim code. I extract the valid Nim parts and make strings out of the parts which isn't valid Nim. Now I want to add information to the valid Nim code which makes the Nim compiler able to actually show which file and where in that file the error came from. As it stands now the only error I get is from the macro code which reads the file. So the error message at the moment is completely useless and I'd much rather have it point to the Nim code in the file I'm reading.

**Comment by ire4ever1190** [comment]
This is sort of already possible with the [line pragma](https://nim-lang.org/docs/manual.html#pragmas-line-pragma) but its messy to work with

`example.nim`
```nim
import macros, strutils

template errorSomeWhere(file: static[string], line: static[int]) =
  {.line: (file, line).}:
    # If this was a macro then the lineInfo for `fake`
    # would also be pointing to index.html, but column would be off which is why
    # I used exceptions instead of "errorMsg".error(NimNode)
    # let fake = genSym(ident = "test")
    raise (ref ValueError)(msg: "Invalid line of html")
    
macro parseHtml(file: static[string]) =
  for i, line in file.staticRead().splitLines().pairs():
    if "invalid" in line:
      # {.line.} requires static values which is why we have the template
      return quote do:
        errorSomewhere(`file`, `i` + 1)
    echo line

parseHtml("index.html")
```
`index.html`
```html
<html>
  invalid
</html>
```

Returns this output

```
/tmp/index.html(2)       l
Error: unhandled exception: Invalid line of html [ValueError]
```

**Comment by PMunch** [comment]
What I want to catch is compile-time errors though. I had already tried the line pragma, and believed that it wouldn't work. But after fiddling around with it some more I have found that this works:

```nim
import macros, strutils

template hello() = echo "Message: Hello"
template world() = echo "Message: World"
template goodbye() = echo "Message: Goodbye"

macro parseHtml(file: static[string]) =
  result = newStmtList()
  for i, line in file.staticRead().splitLines().pairs():
    if line == "": break
    let ident = newIdentNode(line)
    {.line: ("index.html", 3, 1).}:
      discard result.add quote do:
        `ident`()

parseHtml("index.html")
```

With an input of:

```
hello
world
invalid
goodbye
```

The error now reads:
```
/tmp/linetest.nim(16, 10) template/generic instantiation of `parseHtml` from here
/tmp/index.html(3, 11) Error: undeclared identifier: 'invalid'
```

Which is almost perfect (the column there is from the source code, and even though I try to pass a column value to `{.line.}` it is ignored. This would be a bit confusing since my editor now tries to highlight where the error is in the index.html file and it will highlight a different part of the line. But it's much better than before.

**Comment by PMunch** [comment]
Oh and I have no idea why  that `discard` has to be there, but Nim complains if it isn't

**Comment by ire4ever1190** [comment]
If the macro code can already "lie" about line information with `{.line.}` then maybe it would be a good idea to support directly setting it on `NimNode` so messy use of `{.line.}` isn't needed in macros?

And to stop issues like "This is saying theres an error on like 32456 but that line doesn't exist" have a define like `-d:noFakeLines` which converts line info setters / `{.lineInfo.}` into no-ops?

**Comment by PMunch** [comment]
That sounds like a good idea. I'm currently trying to get my example to use the passed in filename instead of a hardcoded one, and it's really messy..

**Comment by PMunch** [comment]
Really messy indeed. The problem is that `{.line.}` won't accept strings created in the macro because it takes `static[string]` and apparently strings generated at compile-time in a macro isn't static enough.. So you end up jumping hoops where one macro generates another macro and an immediate call of said macro which actually generates the code. This is what I ended up with for the above:

```nim
import macros, strutils

template hello() = echo "Message: Hello"
template world() = echo "Message: World"
template goodbye() = echo "Message: Goodbye"

template rewriteLines(file: static[string], linenum: static[int]) =
  block:
    macro parseHtmlImpl(): untyped =
      result = newStmtList()
      for i, line in file.staticRead().splitLines().pairs():
        if line == "": break
        {.line: (file, linenum).}:
          discard result.add newCall(newIdentNode(line))
    parseHtmlImpl()

macro parseHtml(file: static[string]) =
  result = quote do:
    rewriteLines(`file`, 0)

parseHtml("index.html")
```

Curiously the line number is now gone from the error:
```
/tmp/linetest.nim(21, 10) template/generic instantiation of `parseHtml` from here
/tmp/linetest.nim(18, 12) template/generic instantiation of `rewriteLines` from here
/tmp/linetest.nim(15, 18) template/generic instantiation of `parseHtmlImpl` from here
/tmp/index.html Error: undeclared identifier: 'invalid'
```

**Comment by Araq** [comment]
Fine. If a PR comes along that implements the feature I won't complain.

**Comment by PMunch** [comment]
There, implemented the functionality. During my testing I also found a tiny gotcha which I added to the documentation for the procedure.
