### ISSUE TITLE
internal error:  compiler/vmgen.nim(1691, 23)

### ISSUE THREAD

**Issue by choltreppe** [nim-lang/Nim#21094]
### Description

when I try to compile the tests in my project: https://github.com/choltreppe/parlexgen/tree/devel

I get a internal compiler error.

unfortunatly I cant give a minimal example since I have no clue whats causing that problem.

### Nim Version

1.6.10

**Comment by bung87** [comment]
it compiles fine in 100b304ac2aaa65222d7a9043acd0c534ed484cb
