### ISSUE TITLE
Socket `send` for strings does not handle partial sends properly (fix before V2?)

### ISSUE THREAD

**Issue by elcritch** [nim-lang/Nim#21154]
### Description

The socket `send` variant that for strings does not properly handle the case where only part of the data is sent. There is also no way to get the correct information for the end-user to properly handle either. 

This means it is impossible to properly use this `send` variant. It'd be a shame if this was left unfixed in the V2 api! 

Likely the best solution is to make this `send` variant try to send all the data. It's what most people new to socket programming would want when they go for the "easy" version of send. There's already precedent for this behavior in asyncnet. The asyncnet string send version handles this properly and retries on `EAGAIN` or when the data is only partly sent. 

Though, just returning the number of bytes send would enable proper usage of the API as well. However, it could require more code changes if int wasn't discardable, or improper behavior if it was. 

I can create a PR for this as well.

### Nim Version

Present on the Nim development branch. 

### Expected Output

```text
All the data should be send, or the number of bytes written returned. 

The code should handle it similar to how the asyncnet `send` version does: 


  proc send*(socket: AsyncFD, buf: pointer, size: int,
             flags = {SocketFlag.SafeDisconn}): owned(Future[void]) =
    var retFuture = newFuture[void]("send")

    var written = 0

    proc cb(sock: AsyncFD): bool =
      result = true
      let netSize = size-written
      var d = cast[cstring](buf)
      let res = send(sock.SocketHandle, addr d[written], netSize.cint,
                     MSG_NOSIGNAL)
      if res < 0:
        let lastError = osLastError()
        if lastError.int32 != EINTR and
           lastError.int32 != EWOULDBLOCK and
           lastError.int32 != EAGAIN:
          if flags.isDisconnectionError(lastError):
            retFuture.complete()
          else:
            retFuture.fail(newOSError(lastError))
        else:
          result = false # We still want this callback to be called.
      else:
        written.inc(res)
        if res != netSize:
          result = false # We still have data to send.
        else:
          retFuture.complete()
    # TODO: The following causes crashes.
    #if not cb(socket):
    addWrite(socket, cb)
    return retFuture
```

### Possible Solution

This is a clone of what asyncnet send does: 

```nim
proc send*(socket: Socket, data: string,
           flags = {SocketFlag.SafeDisconn}, maxRetries = 127) {.tags: [WriteIOEffect].} =
  ## sends data to a socket.
  var written = 0
  var attempts = 0
  while data.len - written > 0:
    let sent = send(socket, cstring(data), data.len)

    if sent < 0:
      let lastError = osLastError()
      if lastError.int32 != EINTR and
          lastError.int32 != EWOULDBLOCK and
          lastError.int32 != EAGAIN:
        let lastError = osLastError()
        socketError(socket, lastError = lastError, flags = flags)
      else:
        if attempts > maxRetries:
          raiseOSError(osLastError(), "Could not send all data.")
        attempts.inc()
    else:
      written.inc(sent)

```

Though on the last one, in theory you wouldn't ever need the `maxRetries` but in practice a mis-behaving OS could end up in an infinite loop. I'm sure there's some edge case where after a NIC is unplugged that the OS would always just return `EAGAIN` or whatnot and the program would just hang forever. 

The value could also be hardcoded as a `const nimMaxSendRetries {.define.} = 1000` or something. 

Alternatively, let the end-user handle the error case:

```nim
proc send*(socket: Socket, data: string,
           flags = {SocketFlag.SafeDisconn}): int {.tags: [WriteIOEffect].} =
  ## sends data to a socket.
  let sent = send(socket, cstring(data), data.len)
  if sent < 0:
    let lastError = osLastError()
    socketError(socket, lastError = lastError, flags = flags)

  if sent != data.len:
    raiseOSError(osLastError(), "Could not send all data.")
```

### Additional Information

The Linux man page for `send`: 
   https://man7.org/linux/man-pages/man2/send.2.html

Python's PEP475 discussing EAGAIN and their changes to `socket.send` and `socket.sendAll`:
  https://peps.python.org/pep-0475/
  https://docs.python.org/3/library/socket.html#socket.socket.sendall

**Comment by Araq** [comment]
> This means it is impossible to properly use this send variant. It'd be a shame if this was left unfixed in the V2 api!

It is not too late to fix this for 2.0, we only have a release candidate so far.

**Comment by elcritch** [comment]
@Araq great! It's been merged into devel. Anything I need to do to get it into RC land?

**Comment by ringabout** [comment]
@narimiran backport https://github.com/nim-lang/Nim/pull/21155 pls, thanks!
