### ISSUE TITLE
Fatal memory overwrite bug with `acyclic` pragmas

### ISSUE THREAD

**Issue by lenis0012** [nim-lang/Nim#21171]
### Description

I am experiencing an issue where it seems that sometimes a reference (pointer) is overwritten to nil
It appears to occur (thank you @ringabout ) when using the acyclic pragma in ORC. Which makes me believe this is a bug.

It is relatively hard to reproduce. I tried to make the minimal version of my program that creates the issue.

In this sample code, I have a node hierarchy with templates to construct a node tree.
When this code is ran, after a few thousand succesful iterations, the root node has a 'nil' pointer in it's list of children.
This then causes the dynamic dispatch to error because it cannot determine the type of the child node.

This issue is super weird and again, only happens on ORC. I would really like if someone helped me understand what is going on, and whether or not this is a serious bug in nim.

The issue can be avoided if you don't use the acyclic pragma, don't manually allocate memory (which seems to be responsible for overwriting the pointer) or if you use a template for the textNode constructor instead of a proc.

Either way, if the textNode inserts itself into it's parents children list it should not be overwritten when calling alloc0, because it should still be referenced.

### Nim Version

Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2022-12-24
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 86a6c90c9e23f2e79d9d43927e114eedec0c230d
active boot switches: -d:release

### Current Output

```text
Hint: /home/lennart/Projects/nim-game/reftest [Exec]
/home/lennart/Projects/nim-game/reftest.nim(71) reftest
/home/lennart/Projects/nim-game/reftest.nim(56) doTest
/home/lennart/Projects/nim-game/reftest.nim(32) printChildren
/home/lennart/.choosenim/toolchains/nim-#devel/lib/system/chcks.nim(105) printNode
/home/lennart/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: cannot dispatch; dispatcher is nil [NilAccessDefect]
Error: execution of an external program failed: '/home/lennart/Projects/nim-game/reftest'
```

### Expected Output

```text
Nothing
```

### Possible Solution

I believe this potential bug deserves further diagnosis before a solution can be proposed.

### Additional Information

I created the following program to reproduce the bug.
I am sorry for the lengthy code, but it is still substantially more simple than my own program which uses lots of dynamic libraries.

```nim
import std/[with]

type
  Node* {.acyclic.} = ref object of RootObj
    name: string
    data: pointer
    children: seq[Node]
  TextNode = ref object of Node
    text: string

proc fakeEcho(s: string) =
  if s.len < 0:
    echo s

proc newNode[T: Node](parent: Node): T =
  new result
  result.data = alloc0(250)
  parent.children.add(result)

proc newRootNode(): Node =
  new result
  result.data = alloc0(250)

method printNode(node: Node) {.base.} =
  fakeEcho node.name

method printNode(node: TextNode) =
  procCall printNode(Node(node))
  fakeEcho node.text

proc printChildren(node: Node) =
  for child in node.children:
    child.printNode()
    printChildren(child)

proc free(node: Node) =
  for child in node.children:
    free(child)
  dealloc(node.data)

template node(parent: Node, body: untyped): untyped =
  var node = newNode[Node](parent)
  with node:
    body

proc textNode(parent: Node, text: string) =
  var node = newNode[TextNode](parent)
  node.text = text

template withRootNode(body: untyped): untyped =
  var root = newRootNode()
  root.name = "root"
  with root:
    body
  root.printNode()
  printChildren(root)
  root.free()

proc doTest() =
  withRootNode:
    node:
      name = "child1"
      node:
        name = "child2"
        node:
          name = "child3"
          textNode "Hello, world!"

if isMainModule:
  while true:
    doTest()
```

**Comment by Araq** [comment]
In debug mode it dies instantly on OSX with

Error: unhandled exception: cannot dispatch; dispatcher is nil [NilAccessDefect]

**Comment by ringabout** [comment]
I'm debugging `proc atomicRefOp(c: var TLiftCtx; t: PType; body, x, y: PNode)` which seems to be related.

> However, 'decRef dest' might trigger a cycle collection and then the collector
  traverses the graph. It is crucial that when it follows the pointers the assignment
  'dest[] = source' already happened so that we don't do trial deletion on a wrong
  graph -- this causes premature freeing of objects!

**Comment by ringabout** [comment]
Adding `{.acyclic.}` to `TextNode` it works though, I'm not sure whether it is a bug. I'm checking whether there is something wrong with the liftdestructor.

**Comment by ringabout** [comment]
The barrier is probably needed for acyclic refs, which is not a final object in ORC.

**Comment by ringabout** [comment]
I reckon that the problem is caused by the destructor of `Node`

```c
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test57_33) {
  nimDecRefIsLast((*dest).p->data[colontmp_]);
}
```

```c
eqdestroy___test57_33((&(*dest).children));
```
The `Node` calls its acyclic destructor, namely `nimDecRefIsLast` to destroy the children. But `TextNode` is a potential cyclic object, and it should be destroyed by `nimDecRefIsLastCyclicDyn`.

Should we produce a warning/error for this situation?

**Comment by lenis0012** [comment]
None of the nodes should have a reference to themselves or a child that references one of it's parents. that's why I added the pragma.

I would assume as a developer that when I apply the pragma to the root object that it does not cause child objects to break. Especially not considering that from what I understand in the documentation acyclic is just a hint for the cycle collector to ignore references to this specific object in the tree, which I thought means it should behave exactly as ARC would for those objects.

**Comment by ringabout** [comment]
Yeah, it will be solved differently. See also the discussion from the internal channel on the discord. Basically refs will be treated as dyn now.
