### ISSUE TITLE
panicoverride / patching fatal, doesn't work for assertions in Nim 2.0 RC1

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#21195]
Since https://github.com/nim-lang/Nim/pull/20743, patching `sysFatal` is no longer adequate to provide e.g. a custom crash screen on an embedded platform.

This means that:

* `--mm:none --os:standalone` is effectively broken, because panicoverride.nim only patches `sysFatal`.

* the alternative of using `patchFile` to replace fatal.nim (good for `--mm:arc --os:any`) is kind of messy now: You have to also patch assertions.nim, and you have to somehow ensure both have access to your custom panic procedure.

## Example

```nim
# panicoverride.nim

proc printf(fmt: cstring) {.varargs, importc, header:"stdio.h".}
proc exit(code: cint) {.importc, header:"stdlib.h".}

{.push stack_trace: off, profiler:off.}

proc rawoutput(s: cstring) =
  printf("RAW: %s\n", s)
  
proc panic(s: cstring) {.noreturn.} =
  printf("PANIC: %s\n", s)
  exit(0)

{.pop.}
```

```nim
# main.nim
var n = 11
assert(n == 12)
```

### Current Output

```
$ nim c --verbosity:0 --os:standalone --mm:none main.nim
Error: system module needs: newObj
```

### Expected Output

```
$ nim c --verbosity:0 --os:standalone --mm:none main.nim
$ ./main
PANIC: /home/exelotl/Dev/nim-tests/panics/main.nim(2, 7) `n == 12`
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2022-12-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 81d8ea95af0cfaaedca2fd1881199e113e6f5b41
active boot switches: -d:release
```

**Comment by ringabout** [comment]
Sure, I will keep the old behavior for programs which don't use `nimPreviewSlimsystem`. Since `std/asserions` has been moved out of the system with `-d:nimPreviewSlimSystem`; you may choose your own assertion implementation (simply quits or printf) in the future.

**Comment by exelotl** [comment]
Thanks!

> Since std/asserions has been moved out of the system with `-d:nimPreviewSlimSystem`; you may choose your own assertion implementation (simply quits or printf) in the future.

Ah right, I was wondering how to future-proof things, so this is certainly good to know.
