### ISSUE TITLE
ImportC not working as usual(?)

### ISSUE THREAD

**Issue by JewishLewish** [nim-lang/Nim#21198]
### Description

ImportC not working as expected? I decided to look at the importC feature (that was written on the docs) and I thought it would be cool to play around. After playing around, it shows that it wasn't workin as usual so I used the example and even that wasn't working as usual.

calc.nim
```nim
{.compile: "logic.c".}
proc addTwoIntegers(a, b: cint): cint {.importc.}

when isMainModule:
  echo addTwoIntegers(3, 7)
  ```

logic.c
```c
int addTwoIntegers(int a, int b)
{
  return a + b;
}

### Nim Version

1.6.10

### Current Output


(Running this five times)
17037320
17037316
17037312
17037308
17037304
```

### Expected Output
10

**Comment by JewishLewish** [comment]
Update it looks like it sort of works. When making the code return string then it works flawlessly. 

```c
int addTwoIntegers(int a)
{
  return "Hello world";
}
```

```nim
{.compile: "logic.c".}
proc addTwoIntegers(a: cint): cstring {.importc.}

when isMainModule:
  echo addTwoIntegers(3)
```

Output: Hello world

**Comment by JewishLewish** [comment]
After doing more testing, it seems that it really doesn't like input. 

```c
int Combine(int a)
{
  return 2 * 3;
}
```
This c code would give 6 completely normally

However code like:
```c
int Combine(int a)
{
  return a * 3;
}
```
completely breaks it(?)

**Comment by JewishLewish** [comment]
Adding more, returning declared variables from C seems to work. 
```c
int Example(int a)
{
  int x = 10;
  return x;
}
```
Output, 10.

**Comment by JewishLewish** [comment]
Update: I FOUND THE SOLUTION.
![image](https://user-images.githubusercontent.com/65754609/209886583-8b80a37b-203e-4ce4-993c-25d04766c352.png)

**Comment by ringabout** [comment]
The first example works for in 1.6.10 and devel on Windows.

**Comment by metagn** [comment]
Calling convention difference?

**Comment by dinau** [comment]
Try this (added calling convention 'cdecl')
```nim
proc addTwoIntegers(a, b: cint): cint {.importc,cdecl.}
```
