### ISSUE TITLE
Is default impotc "cdecl" is changed, codes doesn't work for vcc 32bit.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#21226]
The code works previous version now desn't work with the latest devel, I need to add ``cdecl`` manually for every proc importc to make the code works when compile with vcc 32bit.
like pacakge nimblas, tinyre.

This is output with arraymancer/example/ex04_fizzbuzz_interview_cheatsheet.nim when compile using vcc 32bit:
```
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
 ** On entry to SGEMM  parameter number  0 had an illegal value
```
### Nim Version

Nim Compiler Version 1.9.1 [Windows: amd64]
Compiled at 2023-01-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

**Comment by ringabout** [comment]
>  I need to add cdecl manually for every proc importc to make the code works when compile with vcc 32bit.
like pacakge nimblas, tinyre.

Hello @slangmgh what's you vcc version? Where can I download it? How can I reproduce it with tinyre?

`tinyre` relies on `tinyre.c` which doesn't seem to work with msvc, but it is probably unrelated to Nim.

```
C:\Users\blue\Desktop\Nim\tinyre\re.c(664): error C2057:
```

It doesn't seem that I can compile the example mention before with visual stdio 2019

![image](https://user-images.githubusercontent.com/43030857/215044656-343d0f6e-54ab-4624-ae11-1cdcbc19f12f.png)

**Comment by slangmgh** [comment]
@ringabout Yes, I modify the tinyre.c to make it be compiled by msvc.
Sorry, I check the code again and find it't my fault.
I used the memlib/rtlib to import the function, and which is the cause, when I change the ``rtlib`` to ``dynlib``, all is fine, the default importc calling convention is cdecl.
So please close the issue as it is not a bug.
Thanks.
