### ISSUE TITLE
`template` with module as parameter elides usage/checking of module name specifier

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#21231]
### Description

```nim
var x: int

template f(y: untyped) = echo y.x   # Builds, and
for i in 1 .. 10:
  x = i
  f(system)                         # outputs 1, 2, 3, ..., 9, 10

template h(y: auto) = echo y.x      # Builds, and
for i in 1 .. 10:
  x = i
  h(system)                         # outputs 1, 2, 3, ..., 9, 10

static: echo typeof(system)         # void

# template g(y: untyped) = echo y.3 # Error: identifier expected, but got '3'
# echo system.3                     # Error: identifier expected, but got '3'
# echo system.x                     # Error: undeclared identifier: 'x'
```

1) The oddity here isn't any one behavior: maybe it makes sense for `system.x` to access `x` in the current module instead, but doing so only in the context of a template seems to be bypassing some checks valid identifiers or constants which occurs in other usages of module names and the `.` operator;

2) If `system` is a `void`, it's not clear how any version of `SomeVoid.someSymbol` should work the way it does here, which also is seemingly inconsistent;

3) and practically, having Nim look at some `y.x` and just treat it as `x`, when the `y.x` form is kind of nonsensical hides bugs and generates arguably invalid code as a result.

### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-23
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2023-01-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2620da9bf9994d09da3d5b31b29c95855fb79a41
active boot switches: -d:release
```

### Current Output

```text
void
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
```

**Comment by Araq** [comment]
There is no reason why 

```nim

var x: int

template f(y: untyped) = echo y.x   # Builds, and
for i in 1 .. 10:
  x = i
  f(system)      
```

should compile.
