### ISSUE TITLE
Destructor not called for all fields when raising

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#21245]
### Description

```nim
type X = object
  v: int

type Y = object
  x: X
  y: X

var destroys: int
proc `=destroy`(x: var X) =
  echo "destroying"
  inc destroys
  raise (ref ValueError)(msg: $destroys)
  
  
proc f() =
  var y: Y = Y()
  echo y

echo "calling f"
try:
  f()
except ValueError as e:
  echo "got ", e.msg
```

This is a continuation of #21004 and #11887 - similarly, an exception in `=destroy` causes the other destructor not to run, but this time for another field in an object meaning that objects are not fully destroyed if any destructor raises.

If instead we raise from a destrutor on `Y`, none of the fields are destroyed, ie only the "main" object destructor runs.

### Nim Version

play latest

**Comment by Araq** [comment]
The destructor for `Y` is just `=destroy(this.x); =destroy(this.y)`, it's very to understand what is going here. `raise` inside a destructor is not special in any way.

I remember you telling me that C++ supports raising in destructors but I don't see how, it always calls `terminate` at runtime when that happens. For example:

```c++

#include <iostream>
using namespace std;

class X {
  public:
  ~X() noexcept(false) {
    cout << "destroyed!";
    throw "something!";
  }
};

class Y {
  public:
  Y(X a_, X b_): a(a_), b(b_) {}
  X a; 
  X b;
};


int main() 
{
    Y y {X{}, X{}};
    cout << "Hello, World!";
    return 0;
}

```

What am I missing?

**Comment by arnetheduck** [comment]
The relevant C++ rules are:
* you cannot throw while another exception is in-flight (so the first one is not lost)
* you cannot throw from `noexcept(true)`

destructors are a special case of the above, ie they are noexcept(true) and "sometimes" invoked while an exception is "in-flight" - thus, you can raise from a destructor as long as that destructor is not invoked because another exception is already unwinding the stack (regardless if that exception came from a destructor or not).

So, re example, a few things to see some output:

* `cout` is buffered, need to `endl`
* Y destructor needs `noexcept(false)`
* raising _while_ unwinding still causes terminate

Here's something to play with:
```c++
#include <iostream>
using namespace std;

class X {
  public:
  ~X() noexcept(false) {
    cout << "destroyed!"<<endl;
    throw "something!";
  }
};

class Y {
  public:
  Y(X a_, X b_): a(a_), b(b_) {}
  ~Y() noexcept(false){}
  X a; 
  X b;
};


int main() 
{
    try {
        X x{};
        cout << "here"<< endl;
    } catch(...) {cout << "test" <<endl;}
    try {
     Y y {X{}, X{}};
    } catch(...) {cout<< " catch"<<endl;}
    cout << "Hello, World!"<<endl;
    return 0;
}
```

More about this: https://akrzemi1.wordpress.com/2011/09/21/destructors-that-throw/

**Comment by Araq** [comment]
This would be hard to implement for the C++ backend but I fail to see the advantage of this model. Consider this:

```cpp

#include <iostream>
using namespace std;

class X {
    bool doraise;
  public:
  X(bool b): doraise(b) {}
  ~X() noexcept(false) {
    cout << "destroyed!"<<endl;
    if (doraise)
      throw "something!";
  }
};

class Y {
  public:
  Y(X a_, X b_): a(a_), b(b_) {}
  ~Y() noexcept(false){}
  X a; 
  X b;
};


int main() 
{
    try {
     Y y {X{false}, X{false}};
    } catch(...) {cout<< " catch"<<endl;}
    cout << "Hello, World!"<<endl;
    return 0;
}
```

It produces 4 destructor calls. Now change that to `Y y {X{false}, X{true}};` and it produces 3 destructor calls but you still cannot catch the exception (no "catch" is produced). Why is that? I have no idea but it doesn't look like a solution that can be understood by mere mortals.

**Comment by arnetheduck** [comment]
> I fail to see the advantage of this model.

"dropping" an in-flight exception is pretty bad, pretty much always because things are are supposed to happen don't (freeing memory, resources, running destructors and so on) - the model simply ensures that this fails fast instead of producing "random" unexpected behavior in the precise case that it happens.

Somewhat related is raising in `finally` - ie you could argue that the developer writing the raising code _explicitly_ wants to drop the "hidden" in-flight exception in the "exception" branch of finally and replace it with a new one that is shared between normal and exception branches, but this requires stretching your imagination quite a bit - at least this is "well-defined", unlike raising while unwinding.

There's nothing wrong with raising in destructors per se when they're thought of as "ordinary functions" - it's the fact that the compiler liberally sprays hidden invokations all over the control flow that "causes" the unsound behavior since the language can no longer concurrently service the destructor guarantee.

Indeed, the simple solution here remains to disable destructor raising until a better solution is found - this is returns the destructor feature overall to sound territory (assuming no `Defect` of course).

**Comment by arnetheduck** [comment]
> Why is that? I have no idea

```c++
#include <iostream>
using namespace std;

class X {
    bool doraise;
  public:
  X(bool b): doraise(b) {}
  ~X() noexcept(false) {
    cout << "destroyed!" <<doraise<<endl;
    if (doraise)
      throw "something!";
  }
};

class Y {
  public:
  ~Y() noexcept(false){}
  X a; 
  X b;
};


int main() 
{
    try {
     Y y {X{false}, X{true}};
    } catch(...) {cout<< " catch"<<endl;}
    cout << "Hello, World!"<<endl;
    return 0;
}
```

The Y::Y constructor you introduced causes an "additional" copy of each of x, y to exist (the temporary that initializes the members) - when this temporary is destroyed, so is `y` and therefore the a, b inside y _also_ are destroyed as part of unwinding and you and up with std::terminate per no-raising-while-unwinding-already rule - if you remove the constructor, the `{}` initialization syntax will do what you wanted to, ie in-place-construct a, b and thus cause only one exception to be raised.

**Comment by Araq** [comment]
> Indeed, the simple solution here remains to disable destructor raising until a better solution is found - this is returns the destructor feature overall to sound territory (assuming no Defect of course).

Will try that yes.
