### ISSUE TITLE
Source download from Nim releases doesn't have build_all.sh

### ISSUE THREAD

**Issue by elcritch** [nim-lang/Nim#21243]
### Description

It's not clear how to do a full install the latest release from the release [tarball](https://nim-lang.org/download/nim-1.6.10.tar.xz). The `build.sh` script only builds `nim` and `nim-gdb` but not the support tools like nimsuggest, nimble, or testament. 

This complicates installing Nim on platforms without choosenim support like Linux/ARM64 (or Mac/ARM64 pending PR's). This probably affects other platforms as well. 

### Nim Version

1.6.10

### Expected Output

```text
Provide a `build_all.sh` script or similar in release tarballs.
```

### Additional Information

Possibly related:

- https://github.com/nim-lang/Nim/issues/19815

**Comment by elcritch** [comment]
Here's the list of binaries when the pre-built Linux x64_64 tarball is downloaded:

- nimgrep
- nim
- nim_dbg
- nimble
- testament
- nimpretty
- nim-gdb
- nimsuggest
- atlas

**Comment by Araq** [comment]
Is the 2.0 line affected?

**Comment by elcritch** [comment]
I haven't tested 2.0 on my projects yet, but tonight I can take a look and see.

**Comment by elcritch** [comment]
Yes, the latest nightly for 2.0 also has the same issue. 

You can see it here: https://github.com/nim-lang/nightlies/releases/tag/2022-12-22-version-2-0-81d8ea95af0cfaaedca2fd1881199e113e6f5b41
