### ISSUE TITLE
Default valued generic proc parameter causes missing parameter in generated C code. 

### ISSUE THREAD

**Issue by yuanweixin** [nim-lang/Nim#21258]
### Description

Code:
```nim
type
  Item*[T] = object
    pos*: int

proc initItem[T](p:int=10000) : Item[T] = 
    result = Item[T](p)

proc doit[T](x:Item[T], s:Item[T]=initItem) : string = 
    return $x.pos

let x = Item[string](pos:100)
echo doit(x)
```

### Nim Version

Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-10-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release

### Current Output

```text
Output:

vagrant@devvm:~/nimly$ nim c -r tests/nim_bug_repro.nim 
Hint: used config file '/home/vagrant/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/vagrant/Nim/config/config.nims' [Conf]
Hint: used config file '/home/vagrant/nimly/tests/config.nims' [Conf]
..................................................................
CC: ../../Nim/lib/system/io.nim
CC: ../../Nim/lib/system.nim
CC: nim_bug_repro.nim
/home/vagrant/.cache/nim/nim_bug_repro_d/@mnim_bug_repro.nim.c: In function ‘NimMainModule’:
/home/vagrant/.cache/nim/nim_bug_repro_d/@mnim_bug_repro.nim.c:169:62: error: expected expression before ‘)’ token
  169 |  T1_[0] = dollar___nim95bug95repro_25(x__nim95bug95repro_11, );
      |                                                              ^
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/vagrant/Nim/lib -I/home/vagrant/nimly/tests -o /home/vagrant/.cache/nim/nim_bug_repro_d/@mnim_bug_repro.nim.c.o /home/vagrant/.cache/nim/nim_bug_repro_d/@mnim_bug_repro.nim.c' failed with exit code: 1
```

### Expected Output

I'd expect `proc doit[T](x:Item[T], s:HashSet[T]=initHashSet) : string =` to be either valid code or I should get a compile error. 

I do get an error, but it shows up as a gcc error, complaining about a missing parameter in a call. 

This feels very opaque and doesn't show me what is wrong. My expectation would have been for the Nim compiler to error out, not for it to show up as a gcc error.

### Possible Solution

Could Nim compiler error out instead of gcc crapping out on generated code? 

### Additional Information

This came up in a project where I defined `$` on a generic type, with a generic second parameter as HashSet[T]=initHashSet. In a unit test I got the error above. So it's not an academic question ;)

**Comment by juancarlospaco** [comment]
!nim c

```nim
type Item[T] = object
  a: int
proc initItem[T](p=10000): Item[T] = Item[T](p)
proc doit[T](x:Item[T], s:Item[T]=initItem): string = $x.a
let x = Item[int](a:100)
discard doit(x)
```

**Comment by AmjadHD** [comment]
The problem is caused when the default value's type doesn't match the parameter's declared type which is the case here.
(a `proc` passed to a parameter of type `Item[T]`).
Here's another repro:
```nim
proc foo*[T](x: seq[T], y: T = "foo") =
  discard

foo @[1, 2, 3]
```

**Comment by metagn** [comment]
The compiler notices this and [sets an error node](https://github.com/nim-lang/Nim/blob/cb7bcae7f73bb907170f67e5e245f474a48760b3/compiler/seminst.nim#L294) but the error node doesn't actually error.
