### ISSUE TITLE
Possible bug in latest(1.6.10) realese - binary not working on first complie - starts working on changing realeses

### ISSUE THREAD

**Issue by nobodybusiness** [nim-lang/Nim#21267]
### Description

After first installation of nim 1.6.10, creating simple helloword file and compiling to C - running binary do nothing.
helloword.nim :
`echo "Hello"`
I tried compailing by terminal and in vscode with extension. There is no errors on compile

> [Done] exited with code=0 in 0.261 seconds
When i run binary with sudo terminal show up for split of second with nothing inside.
I'm begginer so I assumed I did something wrong, but after 10 times going thru helloword example and searching for my mistake I decided for another aproach.
I used choosenim to change realese to 1.6.8. After that and compaling again everything works fine.
Then I decided to check again and switched to 1.6.10 realese.
And everything work fine.

If there is more information I can give you to reproduce this possible bug let me know :) 

### Nim Version

Working:
Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release

First time not working, after reswitched working:
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

**Comment by Araq** [comment]
> When i run binary with sudo terminal show up for split of second with nothing inside.

So it's a terminal problem or a problem with how you setup your VS code.
