### ISSUE TITLE
koch: less zealous clean

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#2127]
We're packaging Nim for debian and currently have to use a custom "clean" target because `koch clean` removes _everything except sources_, including Debian packaging files in "debian/*". It would be good if `koch clean` (perhaps with an option) could only remove things that were actually generated.

**Comment by reactormonk** [comment]
As a quick & dirty fix, I could add `"debian"` to https://github.com/Araq/Nim/blob/devel/koch.nim#L222

**Comment by Varriount** [comment]
No hacks please. The proper fix is to add an optional command parameter specifying what to add/remove.

**Comment by FedericoCeratto** [comment]
The problem is more general than the Debian use-case: I just lost a small log file to koch clean.

The help says "cleans Nim project; removes generated files" but koch deletes any file without extension.

Steps to reproduce:
touch hello{.sh,.bak,.txt,.tar.gz,} && ./koch clean

**Comment by Araq** [comment]
Well on Unix executables have no extension and 'koch tests' produces hundreds of extensions and so every extensionless file is removed.

**Comment by Araq** [comment]
I don't have any ideas what to do instead and I don't know why you need to have a ``debian/`` sub dir in Nim and at the same time want to use ``koch clean``.

**Comment by FedericoCeratto** [comment]
A very common pattern across tools that generate (and cleanup) multiple files is to use a dedicated output directory by default. For example Sphinx and Doxygen are typically used run with output directories.
This would:
- prevent overwriting files user-created files outside of the output directory
- prevent deleting unrelated files e.g. TODO, TODO.bak , mytest.exe , mytest ...
- make it easier to locate and collect the files generated by the tool
