### ISSUE TITLE
`shallowCopy` cannot be evaluated in template

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#21282]
### Description

```nim
proc foo(): int =
  template test1(x: string) =
    discard x
  var v: seq[int]
  test1(block:
    shallowCopy(v[0], v[1])
    "Hello")
```

```
 Error: invalid expression: v[0] = v[1]
```

This prevents `keepItIf` and similar users of `shallowCopy` from working under said conditions as well.

### Nim Version

Nim 1.6.10

**Comment by ire4ever1190** [comment]
Running on devel I get this error instead (Actually putting items inside the seq removes the out of bounds)
```
/tmp/test.nim(9)         test
/tmp/test.nim(6)         foo
/home/user/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(51) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```
Think I fixed this in https://github.com/nim-lang/Nim/pull/20939 when I ran into #20938

**Comment by arnetheduck** [comment]
perhaps that's the answer then - @narimiran can you take a look at backporting?

**Comment by arnetheduck** [comment]
> Running on devel I get this error instead

right, that's expected, the example is a bit buggy - thanks for the fixes though, really nice idea.

**Comment by ringabout** [comment]
The example mentioned works with `refc` on devel.

**Comment by ringabout** [comment]
Yeah, I confirmed. I will backport it.

**Comment by narimiran** [comment]
> @narimiran can you take a look at backporting?

#20939 is now backported to 1.6
