### ISSUE TITLE
Undefined behaviour in clang when in release mode

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2131]
``` nimrod
    echo("Counting to ten: ")
    for i in countup(1, 10):
        var k: ref int = nil
        var l = k[]
        echo($l)
```

See [here](https://news.ycombinator.com/item?id=9050999).

**Comment by Varriount** [comment]
What's the proper fix for this?

**Comment by Araq** [comment]
To implement --nilchecks:on|off.

**Comment by andreaferretti** [comment]
I am not sure whether something changed in nim or in clang in the meantime, but if I try `nim c -d:release -r t2131.nim` I get

```
Counting to ten: 
SIGILL: Illegal operation.
```

which looks good

**Comment by andreaferretti** [comment]
@dom96 Do you think we can close this?
