### ISSUE TITLE
proc `*%`, `+%`, etc not treating ints as unsigned

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21332]
### Description

I am reading through the [system manpage](https://nim-lang.org/docs/system.html#12)

and for all of the `%` type operators it says something to the affect of

- `Treats x and y as unsigned and multiplies them.`
- `Treats x and y as unsigned and adds them.`
- etc

I am running the following code

```sh
# shouldnt this be 3 * toUnsignedInt(-3) == 9 ? it returns -9
echo "3 *% -3 = ", 3 *% -3
# and shouldnt this be 3 + toUnsignedInt(-3) == 6 ? it returns 0
echo "3 +% -3 = ", 3 +% -3

```
- [the source code indeed calls cast on each operand](https://github.com/nim-lang/Nim/blob/version-1-6/lib/system/arithmetics.nim#L418)
- im unsure why the `-` is not being removed before the calculation 

### Nim Version

$ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release
- [these are the bootswitches when running on cmd line](https://github.com/noahehall/theBookOfNoah/blob/master/linux/bash_cli_fns/nimlang.sh#L84)
- [these are the bootswitches when running in vscode](https://github.com/noahehall/theBookOfNoah/blob/master/vscode.settings.jsonc#L191)

### Current Output

- [runnable nim code](https://github.com/noahehall/nim/blob/develop/yolowurl/modules/typeGlobals.nim#L64)
```text
############################ global operators (numbers)
10 %% 3 = 1
3 *% -3 = -9
3 +% -3 = 0
```

### Expected Output

```text
echo "3 *% -3 = 9"
echo "3 +% -3 = 6"
```

### Possible Solution

pretty sure im just doing something wrong or not understanding the docs

**Comment by metagn** [comment]
"Treat as unsigned" does not mean "perform the operation on the absolute value of both operands", it means "treat both numbers as their unsigned counterparts with the same bitwise structure". So `3 +% -3` is the same as `cast[int](cast[uint](3) + cast[uint](-3))`, which is the same as `3 + 18446744073709551613`. With unsigned integers this causes an overflow and becomes 0.

These are legacy procs for when `uint` did not exist, and aren't useful anymore as you can just use the `cast` version. For what you want, you can use `abs(3) + abs(-3)` etc.

**Comment by noahehall** [comment]
Thank you for the explanation @metagn 

I will take note not to use these sorts of operators
