### ISSUE TITLE
Request: update documentation with `##[ ... ]##` syntax

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21357]
### Summary

I was looking through the [testament source](https://github.com/nim-lang/Nim/blob/devel/testament/important_packages.nim) and notice the documentation syntax there was different than the current examples on the [docgen manpage](https://nim-lang.org/docs/docgen.html)

It would be super useful for doc-heavy orgs/people to know about this syntax; its a bit more ergonomic than prefixing every line with `##`

### Description

```sh
You can also create multiline documentation comments 
by creating double-bang code blocks

##[
## title
subtitle
--------
:Authors: 
  Araq
:Org:
  nim-lang

- bullet lists
  - can be nested with [some link](https://to.somewhere.com)
  - [check reStructured docs for full syntax](https://docutils.sourceforge.io/docs/user/rst/quickref.html)

.. code-block:: Nim
  proc codeBlocks: auto =
    result = " are styled as expected"
  echo "code blocks" & codeBlocks()
]##

```

### Alternatives

nim-lang has no alternatives, bow to the crown

**Comment by ghost** [comment]
Not sure what's the issue here - this syntax is documented in https://nim-lang.org/docs/manual.html#lexical-analysis-multiline-comments.

Or you mean it should also be added to https://nim-lang.org/docs/tut1.html#lexical-elements-comments? I guess that won't hurt

**Comment by noahehall** [comment]
oh wow thanks @Yardanico i didn't realize it was already mentioned
