### ISSUE TITLE
closure types with default values don't work in VM

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#21353]
```nim
(var s: proc () = default(proc ()); doAssert s == nil)
```
I found it when debugging https://github.com/nim-lang/Nim/pull/21351. It doesn't work in VM, because the type of is not correct. 

![image](https://user-images.githubusercontent.com/43030857/218266362-1778876e-e1bd-412a-a1e9-dc7d32508cf6.png)

It will become `((nil, nil), (nil, nil))` instead of `(nil, nil)`.

**Comment by juancarlospaco** [comment]
!nim c

```nim
(var s: proc () = default(proc ()); doAssert s == nil)
```
