### ISSUE TITLE
{.all.} appears to do nothing

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#21366]
### Description

This feature, implemented in https://github.com/nim-lang/Nim/pull/17706, seems to either not do anything or not work for fields in objects:

```nim
import osproc {.all.}

var p = startProcess("sleep 1")
echo p[].id
```

### Nim Version

1.6.10

### Current Output

```text
Error: undeclared field: 'id' for type osproc.ProcessObj [type declared in /playground/nim/lib/pure/osproc.nim(53, 3)]
```

### Expected Output

```text
Some PID
```

**Comment by Araq** [comment]
IIRC it only affects not-exported procs and the like, yes.

**Comment by Menduist** [comment]
I think you need to do `privateAccess(ProcessObj)`, `all` will just impact procs AFAIK
https://nim-lang.org/docs/importutils.html#privateAccess%2Ctypedesc

**Comment by PMunch** [comment]
Is there any particular reason why it doesn't export private fields? With a name like `all` I would expect to be able to access *all* of the module.

**Comment by Araq** [comment]
Object fields are tied to the object though, not to the module.

**Comment by mratsim** [comment]
I think this should be closed and whether `{.all.}` should imply `privateAccess` or not should be discussed in a RFC if we want to evolve the current status quo.
