### ISSUE TITLE
Compiler crash on improper use of tuples

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#21380]
### Description

Played around with something today and discovered that this crashes the compiler:

```nim
var test: proc (x: tuple)

proc t(x: tuple) =
  echo x
  
test = t
  
test (name: "Hello", num: 42)
```

Whether or not that could conceivably be made to work is besides the point, it shouldn't crash the compiler in any case.

### Nim Version

1.6.10 (tested on the playground)

### Current Output

```text
Error: internal error: getTypeDescAux(tyBuiltInTypeClass)
```

**Comment by ringabout** [comment]
On the devel, it gives

```
Error: cannot instantiate: 'x:type'
```
