### ISSUE TITLE
memfiles.nim(347, 3) Error: invalid indentation

### ISSUE THREAD

**Issue by georgelemon** [nim-lang/Nim#21386]
```
memfiles.nim(347, 3) Error: invalid indentation
```
version-1-6 (branch)

https://github.com/nim-lang/Nim/blob/d070ccbc031c70f3476d43e0670f94bc2ddc03cc/lib/pure/memfiles.nim#L347-L369

**Comment by c-blake** [comment]
Yeah.  It looks like maybe one hunk of a patch (EDIT: of the backport) did not get applied correctly due to some kind of outer `when` guard (with nimdoc).

**Comment by narimiran** [comment]
Should be fixed now.
