### ISSUE TITLE
`\s` is an invalid character constant

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21399]
### Description

```js
// throws invalid character constant
var stringWithSpace = "string\swith\sspace"

```

### Nim Version

```sh
04:17 PM (develop * u=) 
$ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release
```

### Current Output

```text
/home/poop/git/foss/nim/deepdives/strings.nim(108, 31) 
Error: invalid character constant
  var stringWithSpace = "string\swith\sspace"
```

### Expected Output

```text
stringWithSpace.escape == "string with space"
```

**Comment by PMunch** [comment]
Not quite sure why you think this is a bug. The valid character literals are [clearly documented](https://nim-lang.org/docs/manual.html#lexical-analysis-character-literals) and `\s` is not one of them. You can use `\x20` or `\32` to create a space, or of course just the literal space character. If Nim where to add a space character there would have to be some good reason for it, and I'm not quite sure why you want to use `\s` over just typing a space.

**Comment by noahehall** [comment]
>  I'm not quite sure why you want to use \s over just typing a space.

`\s` catches any whitespace character (space, tab, return, etc), but then the question is why not use a regex?  
lol i just havent reached that point in the docs yet - noob mistakes ;)

Thanks for the clarification will update my notes
