### ISSUE TITLE
Incomplete error message

### ISSUE THREAD

**Issue by bsljth** [nim-lang/Nim#21395]
### Description

I just tried to assign a new value to a constant. The error message is incomplete.

```nim
const x = 2222
x = 5555
```

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
Hint: used config file '/home/basilajith/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '/home/basilajith/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
.........................................................
/home/basilajith/learning/nim/narimiran/immutable.nim(2, 1) Error: '2222' cannot be assigned to
```

### Expected Output

```text
Hint: used config file '/home/basilajith/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '/home/basilajith/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
.........................................................
/home/basilajith/learning/nim/narimiran/immutable.nim(2, 1) Error: '2222' cannot be assigned to 'x'
```

### Possible Solution

Just include the identifier in the error message.

### Additional Information

**System info**
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 5 5600H with Radeon Graphics
    CPU family:          25
    Model:               80
    Thread(s) per core:  2
    Core(s) per socket:  6

**Comment by Araq** [comment]
It's proper English regardless. PRs are welcome but I don't think we should spend effort on this.

**Comment by bsljth** [comment]
But isn't the error message omitting the identifier?
