### ISSUE TITLE
ambiguous proc call causes `nim doc` to fail if `--warnings|hints:off` is set

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21397]
### Description

the good
- `nim doc somefile.nim` successfully creates htmldocs even if ambiguous proc call is found

the bad 
- turning warnings/hints off when executing `nim doc somefile.nim` fails to create htmldocs if ambiguous proc call is found
- passing `--multimethods:on` has no effect

### Nim Version

```sh
$ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release
``` 

### Current Output

```text
/home/poop/git/foss/nim/yolowurl/modules/tupleObjectTable.nim(394, 8) 
Error: ambiguous call; both yolowurl.collide(a: Thing, b: Unit) 
[method declared in /home/poop/git/foss/nim/yolowurl/modules/tupleObjectTable.nim(383, 8)]
 and yolowurl.collide(a: Unit, b: Thing) 
[method declared in /home/poop/git/foss/nim/yolowurl/modules/tupleObjectTable.nim(386, 8)] 
match for: (Unit, Unit)
```

### Expected Output

```text
I can disable hints/warnings and `nim doc ...` doesnt fail
```

### Additional Information

- copy the [second runnable example](https://nim-lang.org/docs/tut2.html#object-oriented-programming-dynamic-dispatch) from nim tutorial number 2 into somefile.nim
- copy paste the below into a terminal (with either hints:off or warnings:off)

```sh
# FYI: dont enable these, ambiguous calls fails docgen
# --warnings:off
# --hints:off
# --multimethods:on # has no effect


read -r -d '' doc_opts <<'EOF'
--verbosity:0
--docInternal
--index:on
--project
EOF


filepath=somefile.nim

nim doc -b:c $doc_opts $filepath
```

**Comment by ire4ever1190** [comment]
Can't seem to reproduce

If I run without `--multimethods:on` it fails with the ambiguous error but using this command works 
```sh
nim doc --multimethods:on --warnings:off --hints:off test.nim
```

Tried with both stable and devel

**Comment by noahehall** [comment]
@ire4ever1190 you are indeed correct, the htmldocs are still produced if i remove `--multimethods:on`
