### ISSUE TITLE
IntSet mutates inside func

### ISSUE THREAD

**Issue by ITR13** [nim-lang/Nim#21393]
### Description

The current code eventually mutates a. For me it mutates at 35, but might vary depending on your machine.
Ran with `nim c -r test.nim -d:strictFuncs`

```nim
import intsets

func Foo(original_set: IntSet): IntSet =
  var new_set = original_set
  for i in original_set:
    for j in i-1..i:
      if j in new_set:
        new_set.excl(j)
      else:
        new_set.incl(j)
  new_set

var a = initIntSet()

for i in 0..int.high:
  a.incl(i)
  let lenBefore = len(a)
  let b = Foo(a)
  if len(a) != lenBefore:
    debugEcho "a was mutated at length ", lenBefore, " to length ", len(a), ". B is len ", len(b)
    break
```

### Nim Version

Nim Compiler Version 1.6.10 [Windows: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
a was mutated at length 35 to length 34. B is len 35
```

### Additional Information

NB: Expected Output intentionally left blank 

The [packedsets](https://nim-lang.org/docs/packedsets.html#assign,PackedSet[A],PackedSet[A]) documentation states: 
"Note: Currently the assignment operator = for PackedSet[A] performs some rather meaningless shallow copy. Since Nim currently does not allow the assignment operator to be overloaded, use the [assign proc](https://nim-lang.org/docs/packedsets.html#assign,PackedSet[A],PackedSet[A]) to get a deep copy."
Which most likely is related. Using assign prevents the issue from happening.

It also seems to be related to the memory of the application/gc, as the way it mutates varies based on how many items are inserted into the set, and whether or not Foo is called inbetween every insertion or not (if not called it requires more items to be inserted before Foo mutates a).

Somebody on the nim discord tried on v2-rc and experienced the same issue.

**Comment by Araq** [comment]
@ringabout might even indicate a design problem with our new "strict funcs" definition.

**Comment by ringabout** [comment]
Reduced Examples:

```nim
{.experimental: "strictFuncs".}

type
  Node = ref object
    num: int

  Data = object
    name: Node

proc mutData(d: Data) =
  d.name.num = 99

func mutate(node: Data) =
  let node2 = node
  mutData(node2)

var node = Data(name: Node(num: 7))
mutate(node)
doAssert node.name.num == 99
```

A potential solution is to propagate the `hasDangerousAssign` flag to its parents or something. Looking into it...

**Comment by ringabout** [comment]
A potential solution is to propagate `hasDangerousAssign` to its owner like what has been done for sideeffects.

```nim
func mutate(node: Data) =
  let node2 = node
  mutData(node2) # -> errors: mutData contains dangerous assign
```

A potential fix is https://github.com/nim-lang/Nim/pull/21420
