### ISSUE TITLE
VisualViewport in std/dom

### ISSUE THREAD

**Issue by ryukoposting** [nim-lang/Nim#21407]
### Summary

`std/dom` does not provide access to the `VisualViewport` API.

### Description

Adding `VisualViewport` to `std/dom` is trivial. The API is very simple.

`VisualViewport` provides information about the visual viewport of the window and iframes; in simpler terms, it helps your JS code understand what part of the window you're zoomed into. `VisualViewport` has been supported by all major browsers for about 1.5 years.

### Alternatives

I could create a Nimble package that provides extensions to std/dom, including implementations of things like `VisualViewport` and `IndexedDB`. Seems like a kludge, though.

### Examples

This code implements the VisualViewport API:

```nim
import std/dom

type
  VisualViewport* {.importc.} = ref object of EventTarget
    offsetLeft*: float
    offsetTop*: float
    pageLeft*: float
    pageTop*: float
    width*: float
    height*: float
    scale*: float
    onresize*: proc (event: Event) {.closure.}
    onscroll*: proc (event: Event) {.closure.}

proc visualViewport*(w: Window): VisualViewport {.importcpp: "#.visualViewport", nodecl.}
```

For use cases of VisualViewport, refer to the MDN docs linked below.

### Backwards Compatibility

Users that use their own VisualViewport implementation (like the one I shared above) may have some issues with conflicting typedefs/names.

### Links

[MDN description of VisualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport)

[Can I use visualViewport?](https://caniuse.com/#search=visualViewport)

**Comment by juancarlospaco** [comment]
> implementations of things like `VisualViewport` and `IndexedDB`. 

- https://juancarlospaco.github.io/nodejs/nodejs/jsindexeddb
- https://juancarlospaco.github.io/nodejs/nodejs/jsviewport

**Comment by ryukoposting** [comment]
@juancarlospaco I'm glad this exists, but:

1. Not a fan of requiring people to use modules outside the stdlib for standardized JS features
2. Importing a library called `nodejs` for in-browser JS code is counterintuitive.

**Comment by juancarlospaco** [comment]
> Not a fan of requiring people to use modules outside the stdlib for standardized JS features

I agree, how that can be fixed ?. 🤔
