### ISSUE TITLE
fail to build NimRtl with arc/orc

### ISSUE THREAD

**Issue by tommo** [nim-lang/Nim#21414]
### Description

When trying to compile NimRtl with orc/arc, the compiler reports the following error message:
`
Error: system module needs: nimAddInt
`
With refc, the compilation is ok.

### Nim Version

Nim Compiler Version 1.9.1 [MacOSX: arm64]
Compiled at 2023-02-21
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: bdc850916fb5d23fa4b9282309985e0fdfb0db36
active boot switches: -d:release

**Comment by PMunch** [comment]
nimRtl isn't required for ARC/ORC, I believe, so there just isn't any reason to build nimRtl with those memory managers.

**Comment by tommo** [comment]
It's not about the allocator and gc, which are working fine with -d:useMalloc. It's the exception and calling frame part that I want to use across the dll boundary. 

I'm trying to build some kind of plug-in framework, it is working well until I want to deal with exceptions. I know the best solution is to avoid using exceptions across dlls, I just think it would be cool to have them.

**Comment by ringabout** [comment]
How can I reproduce the issue on Linux?

`nim c lib/nimrtl.nim` works.

**Comment by tommo** [comment]
@ringabout Wow, it's working with the latest devel version! I guess the change made about the compiler pass fixed this too.
I'm closing this. Thank you for your hard work!

**Comment by tommo** [comment]
closed
