### ISSUE TITLE
can't infer when initializing tuple attributes other than int using numeric constants

### ISSUE THREAD

**Issue by mrgaturus** [nim-lang/Nim#21426]
### Description

initializing tuple attributes different than int (like cint) with numeric constants leads to type error, it cannot infer
```nim
when isMainModule:
  var a: tuple[x, y: cint]
  a = (0, 256) # Type Error
  a = (x: 0, y: 256) # Also Type Error
  echo a.repr
```
this error doesn't appear when initializing an object, it can infer
```nim
type
  Position = object
    x, y: cint

when isMainModule:
  a = Position(x: 0, y: 256)
  echo a.repr
```

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
Error: type mismatch: got '(int, int)' for '(0, 256)' but expected 'tuple[x: cint, y: cint]'
Error: type mismatch: got 'tuple[x: int, y: int]' for '(x: 0, y: 256)' but expected 'tuple[x: cint, y: cint]'
```

### Expected Output

```text
Allow infer a numeric constant on an tuple attribute different to int
```

### Possible Solution

Workarounds:
```nim
when isMainModule:
  var a: tuple[x, y: cint]
  # Defining each attribute compiles
  a.x = 0
  a.y = 256
  echo a.repr
  # Creating constants compiles
  const
    x: cint = 0
    y: cint = 256
  a = (x, y)
  echo a.repr
  # explicit conversions on each attribute
  a = (0i32, 256i32)
  a = (cint 0, cint 256)
  echo a.repr
```

### Additional Information

misc bug, numeric type infer should be better

**Comment by metagn** [comment]
> Nim Compiler Version 1.6.10 

These work on devel. https://github.com/nim-lang/Nim/blob/devel/tests/types/ttopdowninference.nim
