### ISSUE TITLE
devel+threads is not compatible with tcc

### ISSUE THREAD

**Issue by vaguinerg** [nim-lang/Nim#21446]
### Description

Trying to compile a simple "hello world" with threads on and tcc produces an error.

### Nim Version

Nim Compiler Version 1.9.1 [Windows: amd64]
Compiled at 2023-02-27

### Current Output

```text
\nim\lib\system\alloc.nim(767, 5) template/generic instantiation of `atomicPrepend` from here
\nim\lib\system\alloc.nim(758, 18) template/generic instantiation of `storea` from here
\nim\lib\system\alloc.nim(140, 36) Error: undeclared identifier: 'atomicStoreN'
candidates (edit distance, scope distance); see '--spellSuggest':
 (4, 3): 'atomicStatDec'
 (4, 3): 'atomicStatInc'
```

### Expected Output

```text
hello world
```

### Possible Solution

Revert -mm default back to refc 

### Additional Information

it compiles with --mm:refc, markAndSweep, boehm, none and regions (not tested go)

**Comment by Araq** [comment]
TCC is not officially supported.
