### ISSUE TITLE
Move nim-gdb.py and add nim-lldb.py

### ISSUE THREAD

**Issue by EchoPouet** [nim-lang/Nim#21461]
Simple proposition to create a folder `debug` in `tools` and move `nim-gdb.py` in this folder.

In addition, add file named `nim-lldb.py` with the content of [nimlldb.py](https://gist.github.com/jyapayne/396a45f7bd0f95b2e22e6389c79b4948#file-nimlldb-py) proposed by @jyapayne. This script can be found everywhere on the internet, it is better to combine efforts.

**Comment by jyapayne** [comment]
I agree. I'm still working on the lldb script to update it to work for both Orc and refc. I was planning on filling a PR soon.

**Comment by Araq** [comment]
Fine with me.
