### ISSUE TITLE
Feature request: unbuffered I/O

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#2146]
Python offers a command-line argument `-u` that offers an unbuffered version of stdio.  This is extremely useful in some circumstances.  Would it be possible to add this feature to Nim such that the compiled executables use unbuffered stdio?

**Comment by abudden** [comment]
Having looked into this a bit further, the implementation is relatively simple (lifted wholesale from python's C source code):

```c
#ifdef HAVE_SETVBUF
        setvbuf(stdin,  (char *)NULL, _IONBF, BUFSIZ);
        setvbuf(stdout, (char *)NULL, _IONBF, BUFSIZ);
        setvbuf(stderr, (char *)NULL, _IONBF, BUFSIZ);
#else /* !HAVE_SETVBUF */
        setbuf(stdin,  (char *)NULL);
        setbuf(stdout, (char *)NULL);
        setbuf(stderr, (char *)NULL);
#endif /* !HAVE_SETVBUF */
```

Thinking about this further, it probably wouldn't be the end of the world if this were a function that could be called from the source code of the program rather than as a predefined compiler option.  This would at least have the advantage that I wouldn't have to work out where to put it if I did a pull request!  The application code could then be written as something like:

```nim
when defined(unbuffered_io):
    setIOUnbuffered()
```

This could then be a compiler option `-d:unbuffered_io` (with maybe a recommended standard name for the define).

Which is preferred out of the following?

1. A standard lib function with a name like `setIOUnbuffered` that runs the above `C` code in C or does nothing in javascript (in the system module or somewhere else?)
2. A compiler option that inserts the above C code somewhere into the initialisation process of the generated application (and therefore is closer in terms of user experience to python's implementation).

If 1, I'm happy to do a PR as long as someone can confirm whether the name is okay and in which module it should reside.  If 2, I'm happy to do a PR as long as someone can help me find the right place to add the code and can suggest a suitable argument name (as `-u` is taken), maybe `--unbuffered`?

Oh, I might also need some help figuring out what to do about `HAVE_SETVBUF` from the C code above.

**Comment by abudden** [comment]
Oh, I probably should have included a reference for the python code: https://hg.python.org/cpython/file/f477ce0d2345/Modules/main.c#l602

**Comment by Araq** [comment]
Nim is not Python. Command line arguments that affect every Nim program secretly (because it's processed in the stdlib) are not acceptable.

**Comment by abudden** [comment]
> Nim is not Python. Command line arguments that affect every Nim program secretly (because it's processed in the stdlib) are not acceptable.

Okay, but I don't think that precludes option 1 or am I missing something?

**Comment by Araq** [comment]
So pass 0 as the bufSize to ``open``?

http://nim-lang.org/docs/system.html#open,File,string,FileMode,int

**Comment by abudden** [comment]
If that works, that would be great; I had assumed that `stdout` was already open (see C example above).  What would I pass in to `open` to make it re-open `stdout` and make `echo` unbuffered?  It looks like it is expected a filename which doesn't apply in this case.

**Comment by abudden** [comment]
> What would I pass in to `open` to make it re-open `stdout` and make `echo` unbuffered?

Actually, that was a bad example given that `echo` automatically does `flushFile(stdout)`.  A better example would have been using `write(stdout, "Some text")` or similar.

**Comment by Araq** [comment]
``system.reopen`` exists for that. But it needs to grow a ``bufSize`` parameter.

**Comment by abudden** [comment]
> `system.reopen` exists for that. But it needs to grow a `bufSize` parameter.

That looks like it should be fairly easy to implement (the `bufSize` parameter in `open` just calls `setvbuf` in the same way as the python implementation).  However, I've been playing around with a modified version of `reopen` and I can't see how I can use it as it seems to require q

**Comment by abudden** [comment]
Sorry - somehow hit "Comment" too early.  I'll edit my post.

**Comment by abudden** [comment]
For what it's worth, I've just tested a simple `setStdIoUnbuffered` function as follows and it works beautifully:

```nim
proc setStdIoUnbuffered*() =
  discard setvbuf(stdout, nil, IONBF, 0)
  discard setvbuf(stderr, nil, IONBF, 0)
  discard setvbuf(stdin, nil, IONBF, 0)
```

I could, of course, include this in the project code, but then rather than typing:

```nim
when defined(unbuffered_io):
  setStdIoUnbuffered()
```

I'd have to type:

```nim
when defined(unbuffered_io):
  when NoFakeVars:
    when defined(windows):
      const
        IOFBF = cint(0)
        IONBF = cint(4)
    else:
      # On all systems I could find, including Linux, Mac OS X, and the BSDs
      const
        IOFBF = cint(0)
        IONBF = cint(2)
  else:
    var
      IOFBF {.importc: "_IOFBF", nodecl.}: cint
      IONBF {.importc: "_IONBF", nodecl.}: cint

  proc setvbuf(stream: File, buf: pointer, typ, size: cint): cint {.
    importc, header: "<stdio.h>", tags: [].}

  proc setStdIoUnbuffered*() =
    discard setvbuf(stdout, nil, IONBF, 0)
    discard setvbuf(stderr, nil, IONBF, 0)
    discard setvbuf(stdin, nil, IONBF, 0)
```

So obviously I'd much rather have this functionality in `system.nim` (where most of the above already exists).  I guess it wouldn't be so horrible (just a little horrible) to have a `setBufSize(stream: File, bufSize: int = -1)` function so that I have to type:

```nim
when defined(unbuffered_io):
  setBufSize(stdout, 0)
  setBufSize(stderr, 0)
  setBufSize(stdin, 0)
```

but a single function would be much cleaner and could be easily documented as being the solution to those wanting to replicate python's `-u` option.

**Comment by Varriount** [comment]
Do people actually use Python's `-u` though? Most functions in Python's stdlib have a buffered parameter.

**Comment by abudden** [comment]
> Do people actually use Python's -u though? Most functions in Python's stdlib have a buffered parameter.

I certainly do, and I had no involvement with the implementation of the feature, so I can only assume that others do too.

**Comment by Araq** [comment]
Feel free to put your setStdIoUnbuffered  in lib/system/sysio.nim and create a PR.

**Comment by abudden** [comment]
Okay, will do.  Just to confirm: should the news entry go in `2016_06_08_version_0_14_2_released.rst`?
