### ISSUE TITLE
backport PRs

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#21479]
backport https://github.com/nim-lang/Nim/pull/21274 to version-1-6 branch

**Comment by jyapayne** [comment]
It would be cool to have [#21466](https://github.com/nim-lang/Nim/pull/21466) as well for debugging.

**Comment by narimiran** [comment]
> backport https://github.com/nim-lang/Nim/pull/21274 to version-1-6 branch

I've cherry-picked the original PR: https://github.com/nim-lang/Nim/commit/19dd56f018fdacebeaf6605e5915defc66d88d0f
