### ISSUE TITLE
give a better message if `dot` is not found locally when using gendepend

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#21474]
```bash
 nim gendepend compiler/nim.nim
```

gives

```
oserrors.nim(92)         raiseOSError
Error: unhandled exception: The system cannot find the file specified.
 [OSError]
```
You might use `findExe` and raises a reasonable exception.

https://nim-lang.github.io/Nim/os.html#findExe%2Cstring%2Cbool%2CopenArray%5Bstring%5D

**Comment by sslime336** [comment]
Hey @ringabout I'd like to work on this as my first contribution to Nim-lang. But since I am not familiar with `gendepend`, it may take more time for me to finish it. Please assign me if you think it's okey and I will start working on it :)

**Comment by ringabout** [comment]
Basically, you might change the logic here, namely checking the existence of graphiz using `findExe`. Look at `compiler/nodejs` for an example.

```nim
proc commandGenDepend(graph: ModuleGraph) =
  setPipeLinePass(graph, GenDependPass)
  compilePipelineProject(graph)
  let project = graph.config.projectFull
  writeDepsFile(graph)
  generateDot(graph, project)
  # <----------------------> ensure the dot program exists here
  execExternalProgram(graph.config, "dot -Tpng -o" &
      changeFileExt(project, "png").string &
      ' ' & changeFileExt(project, "dot").string)
```
