### ISSUE TITLE
Touching `result` prevents returning with proc's body as an expression

### ISSUE THREAD

**Issue by ZoomRmc** [nim-lang/Nim#21494]
### Description

```nim
func foo(): bool =
  result = true
  false
```

### Nim Version

Verified for Nim `1.6.10` and `1.9.1`.

### Current Output

```text
`Error: expression 'false' is of type 'bool' and has to be used (or discarded)`
```

### Expected Output

```text
Evaluate to `false`
```

### Additional Information

Mixing different kinds of returns is not such a good style, but looks like it should be valid. If it's somehow not, the error message has to reflect that.

Seems to be related: #16855

**Comment by ghost** [comment]
As far as I know that's intended, it was even documented somewhere, will try to find it.

**Comment by Araq** [comment]
Works as intended.

**Comment by Araq** [comment]
From the manual:

Void context
------------

In a list of statements, every expression except the last one needs to have the
type `void`. In addition to this rule an assignment to the builtin `result`
symbol also triggers a mandatory `void` context for the subsequent expressions:

  ```nim
  proc invalid*(): string =
    result = "foo"
    "invalid"  # Error: value of type 'string' has to be discarded
  ```

  ```nim
  proc valid*(): string =
    let x = 317
    "valid"
  ```
