### ISSUE TITLE
Ambiguous calls compiles when module name are equal

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#21496]
### Description

fizz/t.nim:
```nim
proc fb* = echo "fizz!"
```

buzz/t.nim:
```nim
proc fb* = echo "buzz!"
```

test.nim
```nim
import fizz/t, buzz/t
t.fb()
```

### Nim Version

9afb466d733bc16f5ac0fef7477c2ac919046eb2

### Current Output

```text
test.nim(1, 20) Hint: duplicate import of 't'; previous import here: test.nim(1, 12) [DuplicateModuleImport]
[...]
buzz!
```

### Expected Output

```text
ambiguous call etc
```

### Additional Information

The `DuplicateModuleImport` is also a bug

**Comment by ringabout** [comment]
It is a regression.

**Comment by ringabout** [comment]
Let me hazard a guess that https://github.com/nim-lang/Nim/commit/fd76c004794e1cd163450465fa6e493735e6dee4 is the root cause. Bingo! I'm right.

**Comment by ringabout** [comment]
It seems that comparing `sym.position` works. I might look into it later.

**Comment by tersec** [comment]
Can reproduce this on current `version-1-6` (`a8c6e36323601a64dcb6947a694f0bde97b632b2`). Would be useful to have a backport -- it's silent invalid code generation.

**Comment by arnetheduck** [comment]
ping @narimiran ^
