### ISSUE TITLE
importcpp types with explicit constructor "producing chosen constructor is explicit in copy-initialization"

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#21505]
### Description

Codegen is now producing an extra `{}` for cpp types which breaks types with explicit constructors 
The change is originated here: https://github.com/nim-lang/Nim/pull/21378/files

Minimal repro

```nim

{.emit:"""/*TYPESECTION*/
struct FVector4
{
    int a;
    explicit FVector4(int inA = 0) {}  
};

""".}

type FVector4 {.importcpp.} = object
    a : int32



proc vector4_Zero*(): FVector4 {.exportcpp: "$1_" .} =
  type
    Params  = object
      returnValue : FVector4 = FVector4()
  var param   = Params()
  return param.returnValue
```

### Nim Version

1.6.9

### Current Output

```text
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/@mcppinitissue.nim.cpp:81:48: error: chosen constructor is explicit in copy-initialization
        tyObject_Params__JEe9afTCYqDowNJPGU6j9a3Q T1_{};
                                                      ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/@mcppinitissue.nim.cpp:35:14: note: explicit constructor declared here
    explicit FVector4(int inA = 0) {}   // error in C++20, OK in C++17
             ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/@mcppinitissue.nim.cpp:41:10: note: in implicit initialization of field 'returnValue' with omitted initializer
FVector4 returnValue;
         ^
1 error generated.
Error: execution of an external compiler program 'clang++ -c -std=gnu++17 -funsigned-char  -pthread   -I/Volumes/Store/Nim/lib -I/Volumes/Store/Dropbox/Code/Projects/nimlab/lab -o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/@mcppinitissue.nim.cpp.o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/@mcppinitissue.nim.cpp' failed with exit code: 1
```

### Expected Output

```text
Ok
```

### Possible Solution

Dont emit `{}`

**Comment by ringabout** [comment]
cc @heterodoxic

**Comment by heterodoxic** [comment]
Thanks for posting this!

The purpose of this change was to prevent the fundamental problem raised here https://github.com/nim-lang/Nim/issues/21279 about nullifying (literally!) the default constructor of imported C++ objects in a rather easy manner. Too simple in the case of explicit constructors (https://eel.is/c++draft/over.match.ctor)...

One solution appears to be enforcing **more** default-initialization (of C++ structs/classes in the overarching container), brace yourself for more braces!

I will open a pull request for this hypothesis tomorrow.

**Comment by heterodoxic** [comment]
Sorry for the delay, I am quite overwhelmed by RL stuff right now, yet I promise to return soon to this issue for a proper fix!
