### ISSUE TITLE
app:staticLib creates unexpected main function

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#21501]
### Description
Now if you use nim to create a static lib via `nim c --app:staticLib`, then the created lib will also contain a `main` function.

As `--noMain` flag is added, then it'll has no `main` included.
However I don't think it's a tradition to include the `main` function within a lib.

### Nim Version
Nim Compiler Version 1.6.10/1.6.12
### Current Output
* clang:`... duplicate symbol: main`
* gcc:`... multiple definition of main`
### Expected Output
_No Response_
### Possible Solution
Let `app:staticLib` behaves the same as `app:lib`
### Additional Information
Anyway, I am not sure if it's a designed behavior, so the issue is asked.

**Comment by metagn** [comment]
I'm not sure about any of these but from what I know it's needed to start the cycle collector for ORC, GC for non-ARC/ORC memory management methods, and global variables. You will not always need these (for example using ARC and no cyclic memory, or not using managed memory at all (seq, string, ref), or not using global variables), but other times it's needed to call the main function. There is the `--nimMainPrefix:abc` option to add a prefix to the main function name to not cause clashes with other Nim static libraries.

**Comment by litlighilit** [comment]
What about the shared lib, which contains no `main` function.(created via `app:lib`)

**Comment by litlighilit** [comment]
Also,
as I can see from the internal generated C code (in nimcache),
maybe it's `PreMain`'s duty to init GC and so on, which is called by `NimMain`.
On the other hand, `main` function just does some deriving work (i.e. handle args,argv and env as well as _call_ `NimMain`

**Comment by metagn** [comment]
Sorry, I mixed up main with NimMain.

The relevant code for generating `main` is [here](https://github.com/nim-lang/Nim/blob/af086b68f2f718a4ad20e37bf3a00d9a57abec4d/compiler/cgen.nim#L1543-L1590). `optGenDynLib` (`--app:lib`) is accounted for but not `optGenStaticLib` (`--app:staticLib`). So this was probably unintentional, and the fix would be to also check for `optGenStaticLib` here where `optGenDynLib` is checked.

**Comment by beef331** [comment]
@metagn I do not think the orc cycle collector needs started, but one should always call the `NimMain` of your static library, since you can have top level code that needs called.

**Comment by litlighilit** [comment]
Ok,
at least the [document](https://nim-lang.org/docs/backends.html#backend-code-calling-nim-nim-invocation-example-from-c) has metion this.
But I think it's still a little strange to make containing `main` a default behavior when `--app:staticLib`
