### ISSUE TITLE
Wrong  not GC-safe warning

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#21503]
### Description

Compiler wrongly warns about non GC safety: "Warning: 'processing' is not GC-safe as it accesses 'counters' which is a global using GC'ed memory [GcUnsafe2]". 

It's wrong because I it is single threaded mode `nim r --mm:orc --threads:off play.nim` and so in single threaded environment it is thread safe.

```Nim
import std/[tables, asyncdispatch]

var counters = { "some": 1 }.to_table
proc processing(_: AsyncFD): bool {.gcsafe.} =
  counters["some"] += 1

add_timer(1000, false, processing)
run_forever()
```

### Nim Version

1.6.12

**Comment by bung87** [comment]
the Warning is about gc safety, your description is about thread safe.

**Comment by Araq** [comment]
--threads:on is becoming the default anyway and that's what the warning is about
