### ISSUE TITLE
nimlang1.6.12: chkrootkit reports possible Linux.Xor.DDos

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21506]
### Description

- [chrootkit](http://www.chkrootkit.org/) reports possible infection
- [interwebs](https://askubuntu.com/questions/1086572/i-ran-chkrootkit-and-came-up-with-a-infected-file-i-need-help/1297583#1297583) say any executable in /tmp will be flagged

### Nim Version

01:14 PM 
$ nim -v
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

### Current Output

```text
# if your /tmp dir has been cleaned: you need to remove 1.6.12 so its recreated
choosenim remove 1.6.12

# now reinstall 1.6.12
choosenim stable 

# run
sudo chkrootkit

# log
Searching for Linux.Xor.DDoS ...                            INFECTED: Possible Malicious Linux.Xor.DDoS installed
/tmp/choosenim-extraction/nim-1.6.12/install.sh
/tmp/choosenim-extraction/nim-1.6.12/tests/vm/tgorgeex.sh
/tmp/choosenim-extraction/nim-1.6.12/tests/vm/tgorge.sh
/tmp/choosenim-extraction/nim-1.6.12/tests/dll/test_nimhcr_integration.sh
/tmp/choosenim-extraction/nim-1.6.12/tests/destructor/tgotoexceptions.nim
/tmp/choosenim-extraction/nim-1.6.12/deinstall.sh
/tmp/choosenim-extraction/nim-1.6.12/bin/testament
/tmp/choosenim-extraction/nim-1.6.12/bin/nimsuggest
/tmp/choosenim-extraction/nim-1.6.12/bin/nimgrep
/tmp/choosenim-extraction/nim-1.6.12/bin/nim-gdb
/tmp/choosenim-extraction/nim-1.6.12/bin/nim
/tmp/choosenim-extraction/nim-1.6.12/bin/nimpretty
/tmp/choosenim-extraction/nim-1.6.12/bin/nimble
/tmp/choosenim-extraction/nim-1.6.12/bin/atlas
/tmp/choosenim-extraction/nim-1.6.12/bin/nim_dbg
/tmp/choosenim-extraction/nim-1.6.12/koch
```

### Expected Output

```text
nothing is reported
```

### Possible Solution

- `rm -rf /tmp/choosenim-extraction`
- refresh your shell

### Additional Information

- updated to include steps to recreate /tmp dir

**Comment by Araq** [comment]
For which file exactly does it report the virus? Chances are we didn't even touch this file in the patch release. :P

**Comment by noahehall** [comment]
@Araq each file listed is flagged

any executable in /tmp will be flagged by chkrootkit 

and you are correct
i reinstalled 1.6.10 to check if the behavior existed before, and it does 
i'm using choosenim 0.8.4 (2022-07-06) so i just happened to notice the false report on this update


 safe to ignore - i assumed this was a new issue
