### ISSUE TITLE
Bug in example code in `Nim for Python Programmers` related to object creation for `ref object` types

### ISSUE THREAD

**Issue by evenprimes** [nim-lang/Nim#21515]
### Description

In the [Nim for Python tutorial, in the object attribute default values](https://github.com/nim-lang/Nim/wiki/Nim-for-Python-Programmers#object-attribute-default-values), code unexpectedly fails when trying to use `initCat()`.

I added 3 lines to the `main` proc:
```nim
proc main() =
  var kitten = Cat(name: "Tom")
  kitten.increase_age()

  assert kitten.name == "Tom"
  assert kitten.age == 1

  var kitten2 = initCat()  # new kitten
  assert kitten2.age == 2
  assert kitten2.name == "adopt_me"
```

I note that the `Cat` type is a `ref object` type, leading me to think that it should have been `newCat()` not `initCat()`, but the documentation said that was merely a convention, not a requirement. I was hoping to understand the syntactical difference between the 2 types and their init methods.

### Nim Version

Nim Compiler Version 1.6.10 [Windows: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
 733ms  nimintro  ❯ .\cat.exe      
Traceback (most recent call last)
C:\Users\didge\Source\nimintro\cat.nim(32) cat
C:\Users\didge\Source\nimintro\cat.nim(26) main
C:\Users\didge\Source\nimintro\cat.nim(13) initCat
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
No output expected. The asserts should pass.
```

### Possible Solution

An updated example with the correct object creation code would be great. I think that would involve changing `initCat()` to `newCat()` and using whatever syntax is appropriate for object creation.

**Comment by jyapayne** [comment]
Fixed. It should have been:

```nim
func initCat(age = 2): Cat =
  result = new Cat # must initialize a ref object
  result.age = age            
  result.name = "adopt_me" 
```

**Comment by beef331** [comment]
It really should've been :stuck_out_tongue: 
```nim
func newCat(age = 2): Cat = Cat(age: age, name = "adopt_me")
```

**Comment by evenprimes** [comment]
Wow, thanks for the super quick fix. :)
