### ISSUE TITLE
`elementType` from `std/typetraits` doesn't work in generic procs

### ISSUE THREAD

**Issue by cmd410** [nim-lang/Nim#21532]
### Description

Not able to use `typetraits.elementType` in generic procs, which defeats the purpose of this template.

Example code:
```nim
import typetraits

func thisWorks(v: seq[int]) =
  doAssert elementType(v) is int

func thisDoesNot[T](v: T) =
  doAssert elementType(v) is int

@[1,2,3].thisDoesNot
```
Compilation fails with `Error: wrong number of arguments`.

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
Error: wrong number of arguments
```

### Expected Output

```text
works
```

### Additional Information

Probably related to #15833

**Comment by beef331** [comment]
A work around is as follows:
```nim
import std/typetraits
template typedElementType(t: typed): auto = elementType(t)

func thisNowWorks[T](v: T) =
  doAssert typedElementType(v) is int

@[1,2,3].thisNowWorks
```

The `untyped` elementType was attempted to be ran inside the generic declaration as it's an `untyped` macro, this results in calling a compiler magic incorrectly.
