### ISSUE TITLE
update `asyncmacro.createCb` template to nim1.6.12 ~ `bare except clause is deprecated`

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21537]
### Description

- [line that throws deprecation](https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/asyncmacro.nim#L42)

### Nim Version

08:30 AM (manifest *$) 
$ nim -v
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

### Current Output

```text
/home/poop/.choosenim/toolchains/nim-1.6.12/lib/pure/asyncmacro.nim(42, 5) 
Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
```

**Comment by ghost** [comment]
Same applies to devel - https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncmacro.nim#L41:
```
/home/dian/Projects/promat/scratch.nim(3, 36) template/generic instantiation of `async` from here
/home/dian/Things/nim/lib/pure/asyncmacro.nim(41, 5) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
```
do we change the code to catch CatchableError, or silence the compiler in this case? 
@ringabout

**Comment by ringabout** [comment]
> do we change the code to catch CatchableError,

That's probably a breaking change? Perhaps Silence the error or catch `CatchableError or Defect`.
