### ISSUE TITLE
newSeqWith: Unexpected behavior when len template parameter contains side effects

### ISSUE THREAD

**Issue by ericvw** [nim-lang/Nim#21538]
### Description

I stumbled across an odd behavior when using `pop` in an expression that is an argument to `newSeqWith`. 

For the following program:

```nim
import std/sequtils

var foo: seq[string] = @["1", "2", "3"]

echo newSeqWith(ord(foo[^1][0]) - ord('0'), 3)
echo foo
echo newSeqWith(ord(foo.pop[0]) - ord('0'), 3)
echo foo
let length = ord(foo.pop[0]) - ord('0')
echo newSeqWith(length, 2)

```

`echo newSeqWith(ord(foo.pop[0]) - ord('0'), 3)` yields an unexpected result as if `pop` was called twice.

### Nim Version

```
Nim Compiler Version 1.6.12 [MacOSX: amd64]
Compiled at 2023-03-13
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

### Current Output

```text
@[3, 3, 3]
@["1", "2", "3"]
@[3, 3, 0]
@["1"]
@[2]
```

### Expected Output

```text
@[3, 3, 3]
@["1", "2", "3"]
@[3, 3, 3]
@["1", "2"]
@[2, 2]
```

### Additional Information

When looking at the generated C code, it appears that `pop__*` is called before and within `assgnRef()` for line 7, which is the double `pop` being observed.

**Comment by metagn** [comment]
If you use `expandMacros` for the first 2 lines:

```nim
var foo: seq[string] = @["1", "2", "3"]
echo [
  var result`gensym1 = newSeq(ord(foo[BackwardsIndex(1)][0]) - 48)
  for i`gensym1 in 0 ..< ord(foo[BackwardsIndex(1)][0]) - 48:
    result`gensym1[i`gensym1] = 3
  move(result`gensym1)]
```

The `len` template parameter of `newSeqWith` is substituted twice, as you can see [in the code](https://github.com/nim-lang/Nim/blob/a9d0124b5d6e75df708497fc288d602bb2585369/lib/pure/collections/sequtils.nim#L1063). The solution is to replace `0 ..< len` with `0 ..< result.len` or add `let L = len` at the start and replace uses of `len` with `L`.

**Comment by ericvw** [comment]
@metagn, thanks for pointing me to `expandMacros`! I just started learning Nim two weeks ago and wouldn't have as quickly stumbled across `expandMacros` in initially debugging the issue 😄.

Even though you pointed out various solutions, I would like to attempt to contribute the fix.

**Comment by ghost** [comment]
@ericvw it shouldn't be too hard, see https://github.com/nim-lang/Nim/blob/devel/lib/pure/collections/sequtils.nim#L1063, you basically need to move the length into a separate variable that is initialized from the template argument, this is actually a common gotcha with templates in Nim because they're code substitution, that's why those errors exist in the stdlib

**Comment by ericvw** [comment]
Thanks, @Yardanico.

I created #21543, including a test case and the change.
