### ISSUE TITLE
Error: execution of an external program failed

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#21565]
### Description

I try to test https://github.com/neroist/webui/blob/main/examples/hello_world.nim
I can generated hello_world.exe in MSYS2+Mingw64 on my windows 10 64bits with just `nim c -r hello_world.nim`

hello_world.exe can be launched, but crashes no matter what pwd is used. It says
`Error: execution of an external program failed: 'C:\tmp\webui-main\examples\hello_world.exe'`

### Nim Version

Nim Compiler Version 1.9.1 [Windows: amd64]
Compiled at 2023-03-24
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 55636a2913d0b0dec6b24568cb6baef43a9220c1
active boot switches: -d:release

### Current Output

```text
when I click "check password", it crashed and said
`Error: execution of an external program failed: 'C:\tmp\webui-main\examples\hello_world.exe'`

```

### Expected Output

```text
some message should be printed in MSYS2 console
```

### Additional Information

as for nim-1.6.10, the generated exe works as expected

**Comment by ghost** [comment]
Can you show how you are compiling your program? The command-like I mean

**Comment by retsyo** [comment]
the command line is just `nim c -r hello_world.nim`

**Comment by ringabout** [comment]
https://github.com/neroist/webui/issues/5#issuecomment-1483727540

It seems to be a tlsemulation issue on windows, you might disable it.

**Comment by retsyo** [comment]
yes, `threads:off` solves the issue
