### ISSUE TITLE
`is` type check with procs is broken

### ISSUE THREAD

**Issue by cmd410** [nim-lang/Nim#21596]
### Description

Checking type of proc with `is` operator is somehow very broken, take a look:

```nim
proc test(a: int): int = discard

echo typeof(test)
echo test is typeof(test)
echo test is proc (a: int): int
echo test is proc (a: int): int{.noSideEffect, gcsafe, locks: 0.}

```

This prints out:

```nim
proc (a: int): int{.noSideEffect, gcsafe, locks: 0.}
true
false
false
```

### Nim Version

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

### Current Output

```text
proc (a: int): int{.noSideEffect, gcsafe, locks: 0.}
true
false
false
```

### Expected Output

```text
proc (a: int): int{.noSideEffect, gcsafe, locks: 0.}
true
true
true
```

**Comment by beef331** [comment]
Not broken `proc` inside type language is a `closure` and requires a conversion:
```nim
proc test(a: int): int = discard

echo typeof(test)
echo test is typeof(test)
echo test is proc (a: int): int {.nimcall.}
echo test is proc (a: int): int {.noSideEffect, gcsafe, nimcall.}
```
