### ISSUE TITLE
Restrict hints to the current project

### ISSUE THREAD

**Issue by dhasenan** [nim-lang/Nim#2159]
I am writing an application that uses a library with a number of hint problems. I want to suppress hints from that library while displaying them from my own project. I probably can't alter my upstream dependencies, at least not very quickly, but I want to keep my own code squeaky clean. Either I deal with the extra hints (and become inured to them, becoming less likely to deal with problems I should be solving), or I turn them off (which means I never fix my own code).

**Comment by Varriount** [comment]
A workaround might be to use the push and pop pragmas along with the hint pragmas. I don't know how hard this would be to implement though. From my understanding, the compiler makes little distinction between two projects included in one compilation process.

**Comment by dhasenan** [comment]
Specifying a comma-delimited set of directories to do hint checking for would also work. Or conversely a set of directories to ignore for hint checking.
