### ISSUE TITLE
treeRepr does not show values of uint literals

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#21593]
### Description

```nim
import macros

dumpTree:
  1'u
```

### Nim Version

devel as of this issues creation

### Current Output

```text
StmtList
  UIntLit
```

### Expected Output

```text
StmtList
  UIntLit 1
```

### Possible Solution

Extremely simple, change `nnkInt64Lit` here to `nnkUInt64Lit`

https://github.com/nim-lang/Nim/blob/1c7fd717206c79be400f81a05eee771823b880ca/lib/core/macros.nim#L948

Personally too lazy to do this

**Comment by chmod222** [comment]
I had some time to kill.
