### ISSUE TITLE
Hope nim have pragma let us easy use c code function

### ISSUE THREAD

**Issue by Angluca** [nim-lang/Nim#21608]
### Description

```nim
converter n2b*(n: SomeInteger): bool = (n!=0)
proc getx() = 22

if getx(): echo "1: ", true
if not (getx()) : echo  "2: ", true # It's (not 22)=-22 != 0

if not getx().bool: echo true 
# It's ok, Maybe let ultimate goal of the converter comparison should be `if` not `not` function
# also has priority levels?
```
All true ...

*** Hope nim add like c language easy use function pragma, It's can reducing the stringency of variable judgments
Bacause my more project must add these converters, Don't want every project define them T^T ***
```nim
# converts
converter n2b*(n: SomeInteger): bool = (n>0)
converter n2key*(n: SomeInteger|char): TKey = n.TKey
converter n2ci*(n: SomeNumber|char|enum): cint = n.cint
converter n2cf*(n: int): cfloat = n.cfloat
converter n2str*(n: SomeNumber): string = $n
converter s2cstr*(s: string): cstring = s.cstring
converter p2cstr*(p: pointer|ptr): cstring = cast[cstring](p)
converter sz2pt*(sz: array|UncheckedArray): pointer = sz[0].addr
converter sz2cstr*(sz: array|UncheckedArray): cstring = cast[cstring](sz[0].addr)
```

### Nim Version

Nim Compiler Version 1.9.1 [MacOSX: amd64]
Compiled at 2023-03-29

### Current Output

```text
1: true
2: true
```

**Comment by beef331** [comment]
`not` is a bitwise operator on integers so it is invoked on `22` then it converts it boolean for the `if` condition.

**Comment by Angluca** [comment]
OK, Hope nim have pragma let us easy use function like c lang T^T ....
my project copy these same converters, Don't want every project define them 555 T_T

**Comment by beef331** [comment]
Well write Nim instead of writing C inside Nim.

**Comment by Angluca** [comment]
We like nim , But no more time to rewrite all the c libraries in nim language T_T
So use c funcion in nim must convert type more time. 
(Maybe... another language programmer study nim first time to see these will feel nim language is difficult)
```nim
# xxx.addr is pointer,  so all ptr variant must cast[ptr xxx]
# of course all can change to proc(s:pointer), but prone to problems at a later easy bug.
proc xxx(s: ptr char) {.importc.} # xxx(cast[ptr char](v[0].addr))
proc xxx(s: ptr int) {.importc.} # xxx(cast[ptr int](v.addr))
proc xxx(s: ptr object) {.importc.} # xxx(cast[ptr object](v.addr))
proc xxx(key: ctypes) {.importc.} # must write xxx(k.ctypes) everytime
```

**Comment by beef331** [comment]
> So use c funcion in nim must convert type more time.

Yes Nim is more strongly typed than that of C.

```nim
proc xxx(s: ptr char) {.importc.} # xxx(cast[ptr char](v[0].addr))

# just write
proc xxx(s: cstring) {.importc.}


proc xxx(s: ptr int) {.importc.}

# just write

proc xxx(s: var int) {.importc.}
```

**Comment by Angluca** [comment]
```nim
proc xxx(s: cstring) {.importc.} # must cast[cstring](v[0].addr) too T^T
# ----
proc xxx(s: var int) {.importc.} 
# look like well, But we use c2nim covert c to nim hasn't generation similar nimfunc
# So newbie must test many times before know how to use
# Mainly, there are not many tutorials T_T
```

**Comment by beef331** [comment]
> proc xxx(s: cstring) {.importc.} # must cast[cstring](v[0].addr) too T^T

No you do not strings convert with just `cstring myString`

**Comment by demotomohiro** [comment]
Implicity type conversion can create bugs hard to find.

In Nim, sizeof(int) and sizeof(cint) can be different and conversion between them can fail.
Conversion between int and float can lose precision even if they are same size.
Implicitly converting Nim string to cstring is not safe:
https://nim-lang.github.io/Nim/manual.html#types-cstring-type
> Even though the conversion is implicit, it is not safe: The garbage collector does not consider a cstring to be a root and may collect the underlying memory.

How int should be converted to bool depends on context.
In C lang, 0 is false and non-zero value is true.
(`assert(-1);` in C doesn't fail)
Some C API returns negative value when there is an error.
Most of programs return 0 on success and return non-zero on error.

Bugs waste your time more than writing explicit type conversion.
Understanding how implicit type conversion is bad might be hard without having spending time to debug C code for long time.

**Comment by Angluca** [comment]
Well, You are right, Staying away bugs is best !
