### ISSUE TITLE
Ideally, this line would work on it's own, but any reference to `m21496` would cause an ambiguous error, no?

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#21620]
Ideally, this line would work on it's own, but any reference to `m21496` would cause an ambiguous error, no?

_Originally posted by @Menduist in https://github.com/nim-lang/Nim/pull/21500#discussion_r1133308601_

**Comment by jmgomez** [comment]
@ringabout what should cause an ambiguos error exactly?

i.e. 
```nim
import buzz/a
import fizz/a

let test = Buzz()

```
The code above should cause it or dont? (Buzz is inside buzz/a as an exported symbol). 

Edit: My understanding is to use a symbol through the module qualifier, i.e. a.Buzz() what should make the trigger? but if there is no symbol collision it should be fine. Is it correct?

**Comment by ringabout** [comment]
See also https://discord.com/channels/371759389889003530/768367394547957761/1093862426509852724
