### ISSUE TITLE
Old documentation websites

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2162]
Many of the documentation websites are still old. For example http://nim-lang.org/nimrodc.html should redirect to http://nim-lang.org/nimc.html . Another example is http://nim-lang.org/trmacros.html

**Comment by Araq** [comment]
I deleted these two instead (was easier). Reopen if you have more.

**Comment by def-** [comment]
Where do you read about trmacros now? The link here was just deleted: http://nim-lang.org/tut2.html#term-rewriting-macros

**Comment by dom96** [comment]
Reopening until TR macros docs are restored.

**Comment by def-** [comment]
I'm not going to click through each link in http://nim-lang.org/lib.html but some still have old sites: http://nim-lang.org/sdl_mixer.html

**Comment by def-** [comment]
Looks like we can read about TR macros here now: http://nim-lang.org/docs/manual.html#term-rewriting-macros

Rest looks fixed as well.
