### ISSUE TITLE
Pragma to force the exportc of a type. 

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#21645]
### Summary

Right now the only way to `exportc` a type is if it's used in a function, which is not a big deal because you can create a function of the type:

```nim

proc keepMyType(myType:MyType) = discard {.exportc.}

``` 

The issue is, that if MyType is big enough, it will create a pointer, so you need to use `{.bycopy.}` on the type which affects all usages. 

Im willing to implementing it myself if it's approved, and maybe with some minimal guidance. 

### Description

See above

**Comment by juancarlospaco** [comment]
`{.push exportc, used.}` ?. 🤔

(I used this in nodejs modules)

**Comment by Araq** [comment]
> (I used this in nodejs modules)

(That only means that you screwed up. ;-) )

**Comment by Araq** [comment]
> Im willing to implementing it myself if it's approved, and maybe with some minimal guidance.

Go ahead.

**Comment by juancarlospaco** [comment]
> (That only means that you screwed up. ;-) )

Why `{.push exportc.}` would not work?. 😐

**Comment by Araq** [comment]
The question is why do you think `push used` is a good idea. It's not.

**Comment by ringabout** [comment]
Or implementing `{.bycopy.}` pragmas for functions, which could be a workaround for this case.

```nim
proc keepMyType(myType:MyType) {.exportc, bycopy.} = discard
```

**Comment by jmgomez** [comment]
When I suggested/asked about using bycopy in discord was like that, as a workaround. But do we want to add a workaround or a solution? 
Anyways, I pushed the changes so it works with the headers too.

**Comment by jmgomez** [comment]
Just to add some context of the magnitude of the "issue": in a version of the bindings with reduced functions (it's like 30% of the full version) and no plugins (the user can add as many as they want). There are 2498 extra generated functions just to prevent the types for going away.
