### ISSUE TITLE
Enable Private Vulnerability Reporting

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#21646]
### Summary

Private vulnerability reporting is a new feature of GitHub for vulnerability reporting,
that replaces old markdown templates and copypaste blank examples, 
its OFF by default, 1 click to enable, other Nim repos can follow,
then no one has to maintain markdown templates for vulnerability reporting.

### Description

Someone with Admin permissions needs to:

- Go to https://github.com/nim-lang/Nim/settings/security_analysis
- Enable " Private vulnerability reporting " near the top of the page.

### Backwards Compatibility

- No Backwards Compatibility problems. No RFC because its literally 1 click.

### Links

- https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

**Comment by ringabout** [comment]
done
