### ISSUE TITLE
for-sequence iteration compile error when using operator "..<"

### ISSUE THREAD

**Issue by 123swk123** [nim-lang/Nim#21640]
### Description

nim compiler generates compilation error for the following code even though the array size valid

``` nim
import sequtils

proc overrideASlice(val:ref seq[int], offset: int) =
    val[offset..<offset+3] = @[10,11,12]
    

when isMainModule:
    var seqInp: ref seq[int] = new seq[int]

    seqInp[] = sequtils.repeat(0, 10)

    echo seqInp[], ", slice:", seqInp[0..2]
    overrideASlice(seqInp, 0)
    echo "0,1,2 ovrw ", seqInp[], ", slice:", seqInp[0..2]
    overrideASlice(seqInp, 7)
    echo "7,8,9 ovrw ", seqInp[]

    block testIterationSequenceIssue:
        let tstArray: array[7,int] = [0,10,20,30,40,50,60]
        echo tstArray.low, ",", tstArray.high
        for i in tstArray.low..<7: echo tstArray[i]
        # for i in 0..<7: echo tstArray[i]
```
nim compile command
`nim compile --nimcache:$CODERUN_CACHE --verbosity:0 --hints:off --threads:on --run test_seq_slice_ref.nim`

Compilation error
`test_seq_slice_ref.nim(21, 33) Error: conversion from int literal(7) to range 0..6(int) is invalid`

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-04-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 4d683fc689e124cfb0ba3ddd6e68d3e3e9b9b343
active boot switches: -d:release

### Current Output

```text
test_seq_slice_ref.nim(21, 33) Error: conversion from int literal(7) to range 0..6(int) is invalid
```

### Expected Output

```text
@[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], slice:@[0, 0, 0]
0,1,2 ovrw @[10, 11, 12, 0, 0, 0, 0, 0, 0, 0], slice:@[10, 11, 12]
7,8,9 ovrw @[10, 11, 12, 0, 0, 0, 0, 10, 11, 12]
0,6
0
10
20
30
40
50
```

### Additional Information

if we don't use lower bound built-in proc `low()` then the same code works.

```nim
    block testIterationSequenceIssue:
        let tstArray: array[7,int] = [0,10,20,30,40,50,60]
        echo tstArray.low, ",", tstArray.high
        # for i in tstArray.low..<7: echo tstArray[i] <-- Doesn't work
        for i in 0..<7: echo tstArray[i]            # <-- Works
```

**Comment by metagn** [comment]
`tstArray.low` has a type of `range[0..6]` and the second operand is also expected to be of this type but it's not, meaning the workaround is `tstArray.low.int ..< 7`.

Wonder why you are using `tstArray.low` but not `tstArray.high`, `tstArray.low .. tstArray.high` also works

**Comment by 123swk123** [comment]
I am in early stage of creating multi-processor simulation using multiple object arrays of same size and dimension. some features are still under development so during early stage integration I have to activate and run those implemented functions only on some virtual processor even though all of them are instantiated and initialized. 

by the way I understand the workaround and I am surprised to see the type of `tstArray.low`.

**Comment by 123swk123** [comment]
`for i in tstArray.low..6` works, `for i in tstArray.low..<7` doesn't so some how range check is not taking `<` operator into consideration.

**Comment by Araq** [comment]
Others have already explained to you why it doesn't work, there is no bug here.
