### ISSUE TITLE
References Broken on ARC/ORC

### ISSUE THREAD

**Issue by sls1005** [nim-lang/Nim#21656]
##### Example
```nim
proc main =
  let a: ref int = new int
  let b: ref int = a
  a[] = 1 
  echo b[]

main()
```
The above example got `SIGSEGV` on `--mm:orc`.

### Nim Version

Nim Compiler Version 1.6.12 [Android: arm64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release -d:danger

### Current Output

```text
Traceback (most recent call last)
/data/data/com.termux/files/home/test4.nim(7) test4
/data/data/com.termux/files/home/test4.nim(4) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```

### Expected Output

```text
1
```

### Additional Information

* It does not happen on default GC, nor does it happen on `--mm:none`
* It happens no matter `a`, `b` are global or local variables.
* In the generated C code, `a` (not `*a`) was set to `0` after the call to `new`, but before `*a` assigned with `((NI) 1)`.

**Comment by ringabout** [comment]
Works on the devel branch.
