### ISSUE TITLE
An alias type breaks code with a construct template under certain circumstances

### ISSUE THREAD

**Issue by rockcavera** [nim-lang/Nim#21677]
### Description

I wanted to create a construction template, which creates an object and a procedure. When I pass just a `typedesc` in the template, everything works fine. However, when I pass two `typedesc` over a type alias, a compiler error occurs.

I don't know if the title is the best possible, but anyone who wants to give a better suggestion, feel free.

This code does not compile:
```nim
type
  Uints = uint16|uint32

template constructor(name: untyped, typ: typedesc[Uints], typ2: typedesc[Uints]) =
  type
    name* = object
      data*: typ
      data2: typ2

  proc `init name`*(data: typ, data2: typ2): name =
    result.data = data
    result.data2 = data2

constructor(Test, uint32, uint16)
```

However, if you use it like this it will compile:
```nim
template constructor(name: untyped, typ: typedesc[uint16|uint32], typ2: typedesc[Uints]) =

template constructor(name: untyped, typ: typedesc[Uints], typ2: typedesc[uint16|uint32]) =

template constructor(name: untyped, typ: typedesc[uint16|uint32], typ2: typedesc[uint16|uint32]) =

template constructor(name: untyped, typ: typedesc, typ2: typedesc) =
```
See that I only changed the template declaration to make the report smaller. The rest of the code remains the same.

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-04-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: ea8aafa7c9e28e13c73640256505f75b196231b2
active boot switches: -d:release

### Current Output

```text
nim c -f bug
Hint: used config file 'E:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'E:\Nim\config\config.nims' [Conf]
........................................................................
C:\Users\josep\desktop\bug.nim(14, 13) Error: undeclared identifier: 'Test'
candidates (edit distance, scope distance); see '--spellSuggest':
 (2, 2): 'lent'
 (2, 2): 'reset'
 (2, 2): 'set'
```

### Expected Output

```text
Compile correctly
```

### Additional Information

- I tested it with compiler 1.0.0, 1.2.0, 1.4.0, 1.6.0 and 1.6.12 and they all compiled fine. So it's a regression in devel.
- from what I was able to trace, this PR #21227 that introduced the problem.

**Comment by metagn** [comment]
That is extremely weird because the test added in #21227 works even when reverting the patch

**Comment by metagn** [comment]
This fixes it too:

```nim
template constructor[T, U: Uints](name: untyped, typ: typedesc[T], typ2: typedesc[U])
```

The real culprit is implicit generics combining the type of `typ` and `typ2` because their type has the same AST of `typedesc[Uints]` but that never gets fixed for some reason
