### ISSUE TITLE
`effectsOf` doesn't handle property access

### ISSUE THREAD

**Issue by ire4ever1190** [nim-lang/Nim#21697]
### Description

I am unable to make `effectsOf` access a `proc` that is inside an object passed to a function.

```nim
type
  Foo = object
    handler: proc ()
# This works
proc runFoo(x: proc ()) {.effectsOf: x.} = discard
# This gives error 'parameter name expected' but I want it to have the effects of the handler
proc runFoo(x: Foo) {.effectsOf(x.handler).} = discard
```

It also has property access problems when using generics
```nim
type
  Foo[T] = object
    handler: proc (): T
# Error: undeclared field: 'handler' for type runFoo.Foo
proc runFoo(x: Foo) {.effectsOf(x.handler).} = discard
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-04-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: ea8aafa7c9e28e13c73640256505f75b196231b2
active boot switches: -d:release

### Possible Solution

https://github.com/nim-lang/Nim/blob/f9477396a6f21beaa8ffd3de19129b11fe7169f1/compiler/pragmas.nim#L808-L814
The processing of `effectsOf` should handle dot expressions along with normal properties

**Comment by ire4ever1190** [comment]
I have a workaround where I call another function that has `effectsOf` except this seems to then remove the GC safe analysis

```nim
var x = ""

type Foo = object
    handler: proc ()

proc run(x: proc ()) {.effectsOf: x.} = 
  x()

proc run(x: Foo) = 
  # We extract that handler and call that with a proc so we can use effectsOf
  run x.handler

proc notGCSafe() =
  x &= "test"

proc main() {.gcsafe.} =
  # Indirectly calling the handler doesn't give any errors
  run Foo(handler: notGCSafe)
  # Calling it with the version that has effectsOf does
  run notGCSafe

main()
```

**Comment by Araq** [comment]
This is currently not supported and also not documented that it should work.
