### ISSUE TITLE
Compiler thinks an unused proc is used when an auto parameter is used

### ISSUE THREAD

**Issue by diegomrsantos** [nim-lang/Nim#21724]
### Description

When executing

```nim
type
  SomeObj = object
    hey: bool

proc hey() {.deprecated: "Shouldn't use this".} = echo "hey"

proc gen(o: auto) =
  if o.hey:
    echo "bool"

gen(SomeObj(hey: true))
```

The compiler thinks the `hey` proc is being called and outputs the warning, but it is not actually being called. 

### Nim Version

Nim Compiler Version 1.6.12 [MacOSX: amd64]
Compiled at 2023-03-16
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
.................................................................
t.nim(8, 8) Warning: Shouldn't use this; hey is deprecated [Deprecated]
CC: t.nim
Hint:  [Link]
Hint: gc: refc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
64653 lines; 0.353s; 75.875MiB peakmem; proj: t; out: t [SuccessX]
Hint: t  [Exec]
bool
```

### Expected Output

```text
.................................................................
t.nim(5, 6) Hint: 'hey' is declared but not used [XDeclaredButNotUsed]
CC: t.nim
Hint:  [Link]
Hint: gc: refc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
64653 lines; 0.353s; 75.875MiB peakmem; proj: t; out: t [SuccessX]
Hint: t  [Exec]
bool
```

**Comment by Menduist** [comment]
When using `error` instead of `deprecated`, the code doesn't even compile, making this issue more problematic

**Comment by beef331** [comment]
Could not help but minimize it further, the issue is that closed symbol causes semantic analysis to be done, which means it compiles the `deprecated`. Swapping `bind` for `mixin` causes this `deprecation` to disappear.
```nim
proc hey() {.deprecated: "Shouldn't use this".} = echo "hey"

proc gen(o: auto) =
  bind hey
```

**Comment by metagn** [comment]
~~Is there a use case to marking each sym in a sym choice as used?~~ my bad, was not related to symchoices

**Comment by beef331** [comment]
I assume it's just to do exactly as this issue does but in a sensible way
```nim
proc doThing(x: auto) = discard
proc myGen(x: auto) = doThing(x) # We use `doThing` so it's used
```

Arguably the issue here is really that `o.hey` does field access instead of invoking the closed symbol and erroring that it expects 0 parameters.
