### ISSUE TITLE
With Nim 2.0 RCs and devel `nim c` can't resolve packages when `NIMBLE_DIR` env var is set

### ISSUE THREAD

**Issue by michaelsbradleyjr** [nim-lang/Nim#21730]
### Description

Using e.g. Nim `#version-2-0` or `#devel` branches built and installed via choosenim, if I have `NIMBLE_DIR` set in my shell environment, `nim c` is unable to locate installed packages in `${NIMBLE_DIR}/pkgs2`. In my shell, if I `unset NIMBLE_DIR` then `nim c` works correctly.

The problem has already been diagnosed in nim-lang/nimble/issues/1061 but the required fix will need to be made in Nim rather than nimble.

https://github.com/nim-lang/Nim/blob/f0ae1ed54490bdce4f32cc7adf7ac3d85c706f3a/compiler/commands.nim#L614

### Nim Version

```
Nim Compiler Version 1.9.3 [MacOSX: amd64]
Compiled at 2023-04-23
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

The problem is not exclusive to macOS, I've also experienced it on Linux and Windows+MYS2.

### Possible Solution

A workaround is to pass `--nimblePath:"${NIMBLE_DIR}/pkgs2"` as an option to `nim c`.

However, I'm not sure of the best solution. The code referenced above could simply be changed to
```nim
path = nimbleDir / RelativeDir"pkgs2"
```
But should the solution be more robust, i.e. should it take into consideration the version of nimble accessible in `PATH`?

**Comment by ghost** [comment]
That's strange - isn't it supposed to work because of https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L70 ? I've also had weird issues with pkgs2 with an older nimble pkgs folder (not sure what they are), but after cleaning it I've had no issues - I guess it would be strongly recommended to do that for Nim v2.

**Comment by michaelsbradleyjr** [comment]
I checked again and am not seeing the problem on Linux and macOS (I'm pretty sure I did earlier, but may be misremembering), but it still seems to be a problem on Windows.

See: [`093197e`](https://github.com/michaelsbradleyjr/nim-notcurses/commit/093197e90bc15bfd359c02a41890e33a04c1572b)

Since I manually busted the GHA caches in that commit, it's effectively a fresh install of choosenim, Nim, nimble, etc. on all platforms for all the versions/branches of Nim in the build matrix.

The results are here: https://github.com/michaelsbradleyjr/nim-notcurses/actions/runs/4820941830

Example error in the failed builds for Windows with `version-2-0` and `devel` branches:
```
Error: cannot open file: pkg/stew/byteutils
```

**Comment by michaelsbradleyjr** [comment]
While perhaps not worthy of the `Showstopper` label, the problem reported in this issue persists in the `version-2-0` and `devel` branches:

https://github.com/nim-lang/Nim/blob/version-2-0/compiler/commands.nim#L614-L616

https://github.com/nim-lang/Nim/blob/devel/compiler/commands.nim#L614-L616

Fresh failures can be seen here: https://github.com/michaelsbradleyjr/nim-notcurses/actions/runs/5423337434

The compile-time error is the same as before, but now all platforms are affected (at one point it seemed only Windows was affected):
```
Error: cannot open file: pkg/stew/endians2
```

**Comment by Araq** [comment]
Please also check that no nimble .lock file is used.

**Comment by michaelsbradleyjr** [comment]
> Please also check that no nimble .lock file is used.

There is none: I blasted the cache in [`dc5602f`](https://github.com/michaelsbradleyjr/nim-notcurses/commit/dc5602f1fd70876a6379b49ffaaabda68a967eb6), so on each platform and for each version of Nim, it's a fresh download/install of choosenim; then Nim, nimble, & tools are built from source; then dependencies are newly downloaded with nimble. Also, there is no .lock file checked into my repo.
