### ISSUE TITLE
Compiler fails to detect invalid code

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#21733]
### Description

Example below would compile and fail. The code is invalid and shouldn't be compiled.

```Nim
import std/[sugar, tables]

type
  Block = ref object of RootObj
    id: string

  TextBlock = ref object of Block
    text: string

type BlockParser = (string) -> Block
let parsers = (ref Table[string, BlockParser])()

proc parse_text*(text: string): TextBlock =
  TextBlock(id: "1", text: text)

parsers["text"] = (blk) => parse_text # <= invalid code, should be `parse_text(blk)`

echo parsers["text"]("some text").id
```

P.S.

Additionally, it would be nice if Nim understand that `parsers["text"] = parse_text` is a valid code, as `TextBlock` is a subclass of `Block`. So the workaround `parsers["text"] = (blk) => parse_text(blk)` won't be needed.

### Nim Version

nim -v
Nim Compiler Version 1.6.12 [MacOSX: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise

### Current Output

```text
./play.nim 
Traceback (most recent call last)
/alex/projects/nim/play.nim(20) play
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/alex/projects/nim/build/play_0CCF'
```

**Comment by Araq** [comment]
Fails on devel with:

temp.nim(28, 28) Error: type mismatch: got 'proc (text: string): TextBlock{.noSideEffect, gcsafe.}' for 'parse_text' but expected 'Block = ref Block:ObjectType'

As it should.
