### ISSUE TITLE
Allow codegendecl to work on types

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#21747]
### Summary

codegendecl is a nice low level pragma that allow to extend Nim's interop in the user space. This feature request pretends to make it available for object types as well.

### Description

- Custom constructors/destructors in the C++ backend. This will allow users to workaround delete constructrors in cpp

- overrides/virtual functions: will allow to write a macro in the user space that allows the user to write overrides for virtual functions which unfortunately it's the way most C++ frameworks/libraries are extended. 

$1 the type name
$2 the params for the type
$3 the base type

### Examples

For the vfunctions piece it could be also done by modifying further the compile. It isnt mutually exclusive but there is much more friction and it's way more invasive to the compiler codebase.

**Comment by Araq** [comment]
I like it.
