### ISSUE TITLE
coro.`nimcfg` should be named core.`nim.cfg` ?

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21744]
### Description

see [coro.nimcfg](https://github.com/nim-lang/Nim/blob/v1.6.12/lib/pure/coro.nimcfg) on both devel and 1.6.12 branches

however all other files [e.g. asyncdispatch.nim.cfg](https://github.com/nim-lang/Nim/blob/v1.6.12/lib/pure/asyncdispatch.nim.cfg) have `.cfg` file extension

is `.nimcfg` a valid file extension?

### Nim Version

github

**Comment by ringabout** [comment]
All of ".nims", ".cfg", ".nimcfg", ".nimble" are valid configuration extensions.
