### ISSUE TITLE
The send proc in the net module may not be blocking.

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#21756]
### Description

There's an issue I'm having while trying to make a TCP client and server in Nim. I did some debugging and ultimately came to these files.
Client:
```nim
import net
import strformat

let socket = newSocket()
socket.connect("127.0.0.1", Port(5543))
var data = "1234567891023456789202345678930234567894023456789502"
let status = socket.send(addr data, 52)
echo(fmt"Send status: {status}")
var response = ""
while true:
  var buffer = ""
  try:
    buffer = socket.recv(25)
  except TimeoutError:
    discard
  echo(buffer.len)
  if buffer.len > 0:
    response = fmt"{response}{buffer}"
  else:
    break
echo(response)
socket.close()
```

Server:
```nim
import net
import strformat

let socket = newSocket()
socket.bindAddr(Port(5543))
socket.listen()

var client: Socket
var address = ""
var loop = true
var connections = 0
while loop:
  socket.acceptAddr(client, address)
  connections = connections + 1
  # echo(fmt"New client: {address}")
  if address == "127.0.0.1":
    var response = ""
    while true:
      let buffer = client.recv(25)
      echo(buffer.len)
      if buffer.len > 0:
        response = fmt"{response}{buffer}"
      else:
        break
    echo(response)
    client.send("data")
    client.close()
  else:
    echo(fmt"Connection from {address} is not allowed.")
  if connections == 5:
    break

socket.close()
```
I suspect that `send` is not blocking because even though it says it sent 52 bytes of data, the server only receives 50 before both the client and server hang. Using ctrl+c on the client causes the rest of the data to be sent to the server.

### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-12-06
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

### Current Output

```text
Server:
25
25
<hang>


Client:
Send status: 52
<hang>
```

### Expected Output

```text
Server:
25
25
2
0
<data from client>

Client:
Send status: 52
4
0
<data from server>
```

### Possible Solution

`send` should be blocking if it's not already.

### Additional Information

OS: Arch linux
uname -a: `Linux RikuPC 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000 x86_64 GNU/Linux`

**Comment by ghost** [comment]
This might not be related to the issue itself, but anyway - `addr data` is wrong - it takes the address of the Nim managed string, which also contains the reference count and capacity. You should instead use `addr data[0]`, or just send(data) to send the string itself.

**Comment by ghost** [comment]
Sorry about that, you're right. Passing in `addr data[0]` produces valid output when using ctrl+c on the client. It's also worth noting that using the high level version of `send` produces the same results. (Server doesn't get data past the first 50 bytes)

**Comment by Araq** [comment]
It may not be blocking and this may not be a bug report and so I may close it.

**Comment by ghost** [comment]
So the net module that's supposed to be blocking contains a function that doesn't block..

**Comment by ghost** [comment]
And also your reply doesn't even address whether you even read the bug report, it's just mocking me for no good reason.

**Comment by rockcavera** [comment]
> Sorry about that, you're right. Passing in `addr data[0]` produces valid output when using ctrl+c on the client. It's also worth noting that using the high level version of `send` produces the same results. (Server doesn't get data past the first 50 bytes)

With Wireshark you will be able to see that the 52 bytes are being sent.

The fact that the server only reads 50 bytes is because you programmed it to do so. It reads every 25 bytes while the TCP connection is active. That is, until 25 bytes arrive, the server will wait for 25 bytes or until the connection is closed.

I don't see any bugs. Expected and predictable behavior.
