### ISSUE TITLE
unable to set `--useRealtimeGC` in config.nims

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21771]
### Description

using realtime GC in config.nims throws error

```sh
$ .github/scripts/test.nims 
bookofnim/config.nims(1, 2) Error: invalid command line option: '--useRealtimeGC'
```

however, the docs state:

Enables support of Nim's GC for soft realtime systems. See the documentation of the [mm](https://nim-lang.github.io/Nim/mm.html) for further information.

however, the mm page does not have any further details on using this switch

### Nim Version

$ nim --v
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-02
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: aec5a4c4744a81e19954daf330bafac948098835
active boot switches: -d:release

**Comment by Araq** [comment]
You enable it via `-d:useRealtimeGC`.

**Comment by Araq** [comment]
It's documented further in `docs/refc.md`
