### ISSUE TITLE
Redundant `nnkCallKinds` and `CallNodes` in `macros`

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#21781]
The `macros` module has 2 redundant constants, `nnkCallKinds` and `CallNodes`:

https://github.com/nim-lang/Nim/blob/44736d26cdbb0ea5e6010a9ae2bbeadb635d62a1/lib/core/macros.nim#L148-L149

https://github.com/nim-lang/Nim/blob/44736d26cdbb0ea5e6010a9ae2bbeadb635d62a1/lib/core/macros.nim#L1211-L1212

They have only one difference, CallNodes has nnkHiddenCallConv but nnkCallKinds does not.

One of these should be removed or deprecated, or they should have the same value, or they should have more distinct names, or the difference should be documented. They should at least acknowledge the other exists.

**Comment by Araq** [comment]
They should have the same values, both including `nnkHiddenCallConv` (what a strange name...)

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/21829
