### ISSUE TITLE
Adding item to an empty seq crashes sometimes

### ISSUE THREAD

**Issue by omer4d** [nim-lang/Nim#21780]
### Description

This will crash with --gc:arc/orc (but not the default setting):
```nim
proc main() =
    var x: seq[tuple[s: seq[int]]]
    x.add((s: @[]))
    x[0].s.add(0)

main()
```
If it's any help, I've noticed that it doesn't crash if: 
- ```newSeq[int]()``` is used instead of ```@[]```
- ```s``` is initialized with a non-empty seq
- I get rid of the tuple wrapper and use a simple ```seq[seq[int]]``` as the type for ```x```.

### Nim Version

Nim Compiler Version 1.6.12 [Windows: amd64]

**Comment by ghost** [comment]
Same behavior on devel

**Comment by ringabout** [comment]
Valgrind doesn't give useful messages, here is the result of gdb

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555b37c in add__test53_u197 (x_p0=0x5555555612a8, value_p1=value_p1@entry=0) at /home/wind/.choosenim/toolchains/nim-#devel/lib/system/seqs_v2.nim:127
127           if xu.p == nil or xu.p.cap < newlen:
```

**Comment by Araq** [comment]
The problem is that `(s: @[])` is kept in readonly memory and while the `add` does copy the memory the `p` inside it still points to readonly memory. But why this then doesn't trigger

```nim

    if xu.p == nil or xu.p.cap < oldLen+1:
      xu.p = cast[typeof(xu.p)](prepareSeqAdd(oldLen, xu.p, 1, sizeof(T), alignof(T)))

```

escapes me right now.

**Comment by Araq** [comment]
Never mind, found it.
