### ISSUE TITLE
Missing range or overflow check in "sum" or "prod" functions.

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#21792]
### Description

When computing the sum or the product of an array of a Range type, no range check is done. The result has the same type of the elements of the array, but its value may be out of range.

Here is an example:

```import std/math
type Digit = 0..9
var x = [Digit 4, 7]
var p = sum(x)     # "p" should be of type "Digit".
echo type(p)       # And this is actually the case.
echo p             # Out of range, but no exception has been raised.
var q: Digit = p   # Neither when assigning to a Digit variable.
```

Note that a similar problem occurs with "int8" instead of "Digit". In this case, the missing exception is OverflowDefect:

```import std/math
var x = [int8 124, 127]
var p = sum(x)     # "p" should be of type "int8".
echo type(p)       # And this is actually the case.
echo p             # But the result (-5) is wrong.
```

### Nim Version

Encountered with stable and development version.

Stable release:

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

### Current Output

```text
In first program:
Digit
11

In second program:
int8
-5
```

### Expected Output

```text
In first example, an exception RangeDefect raised at line 3 when computing the sum.
In second example, an example OverflowDefect raised at line 2 when computing the sum.
```

### Possible Solution

There is no workaround: avoid to use "sum" and "prod" if there is a risk for the result to be out of range or to overflow.

**Comment by beef331** [comment]
https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/math.nim#LL123C1-L123C54 the culprit, the checks need to be turned off for non float based operations I assume.
