### ISSUE TITLE
Can't compile nimhcr.nim in devel

### ISSUE THREAD

**Issue by actondev** [nim-lang/Nim#21803]
### Description

Following the instructions from https://nim-lang.org/docs/hcr.html , compiling nimhcr.nim fails.
The command I'm running:
`nim c --outdir:$PWD $(choosenim show path)/lib/nimhcr.nim`

When using stable (`choosenim stable`)  it works.

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-06
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 85dbfc68b5c2020b32be9e3dc0d711b749fb5c6f
active boot switches: -d:release

### Current Output

```text
.choosenim/toolchains/nim-#devel/lib/std/private/osdirs.nim(319, 14) Error: add(stack, rel) can have an unlisted effect: RootEffect
```

**Comment by metagn** [comment]
nimhcr was not updated for arc/orc

**Comment by metagn** [comment]
For the record, hot code reloading is still wildly broken/unimplemented for arc/orc, so try adding `--mm:refc`
