### ISSUE TITLE
parseFloat Inf bug

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#21847]
### Description

```console
$ echo 'import std/strutils;echo parseFloat"0e+42949672970"' > bug.nim
$ nim js -r bug.nim
0.0

$ nim c -r bug.nim
inf

$ nim cpp -r bug.nim
inf

$
```

### Nim Version

```
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 71f2e1a502ad231e3356217398e2d7fcd6137967
active boot switches: -d:release

```

devel

### Current Output

```text
inf
```

### Expected Output

```text
0.0
```

### Additional Information

```console
$ python -c 'print(float("0e+42949672970"))'
0.0

$ node -e 'console.log(parseFloat("0e+42949672970"))'
0

```

- https://github.com/nim-lang/Nim/blob/ddce5559981ac5dedd3a5dfb210eb25296e69307/lib/system/strmantle.nim#LL184C24-L184C24
- https://github.com/nim-lang/Nim/blob/ddce5559981ac5dedd3a5dfb210eb25296e69307/lib/system/strmantle.nim#LL151C7-L151C14
- Maybe `nimParseBiggestFloat` is missing some code to check that `integer` is not zero or something (???).
- I hate floats.

**Comment by Araq** [comment]
> I hate floats.

I hate the JS target. :-)
