### ISSUE TITLE
--mm:arc doesn't support msvc c compiler

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#21848]
### Description

When using msvc c compiler, --mm:arc will generate struct initializer which deson't supportted by compiler.
```nim
import tables

proc main*() =
   const cfg_system = {
      "WT_FONTSIZE": "1",
      "WT_FONTSTYLE": "1",
      "CANCEL_HOTKEY_TIP": "1",
   }.toTable

   const tbl_all = {
      "SYSTEM": cfg_system,
   }.toTable

   for key, val in tbl_all:
      echo key, val

when isMainModule:
   main()
```

When compile with msvc c, the error message:
``D:\Tmp\Temp\nimcache\release\vcc-x64\mma56.nim.c(130): error C2059: syntax error: '}'``

And this is the generated c code which cannot compile:
```c
static const struct {
  NI cap; tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[0];
} TM__5pMwZL7vIJhNbn5JYMH1OQ_4 = {0 | NIM_STRLIT_FLAG, {}};
```

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-05-14
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

**Comment by metagn** [comment]
Pretty sure MSVC doesn't support 0 length arrays in general, it just gives an early syntax error here

**Comment by heterodoxic** [comment]
Both ISO C and C++ standards actually forbid 0-size arrays (cf. [ISO C99 draft 2007 $6.7.5.2.1](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf), even though there are compiler extensions for supporting it. Maybe we shouldn't be emitting this at all (`-Wpedantic` will show you this for Clang and GCC, too)).

This looks like a rather  easy codegen issue, I will sort of self-assign myself to this if no one objects (thanks @ringabout! :heart:).
