### ISSUE TITLE
Optimize tail call in non-release

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#21844]
### Summary

Tail call optimization is currently only available in release mode. I'd like it to be available in debug mode as well.

### Description

See example

### Alternatives

Writing the function as a non-recursive one.

### Examples

The following code only works in release mode.

```nim
proc recur(x: int): int =
  if x <= 0:
    return 0
  return recur(x - 1) + x

proc tailrecur(x: int): int =
  if x <= 0:
    return 0
  return tailrecur(x - 1)

echo recur(10000)
echo tailrecur(10000)
```

```
❯ nim r tailrecur.nim
...
Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=<int> but really try to avoid deep recursions instead.
```

```
❯ nim r -d:release tailrecur.nim
...
50005000
0
```

**Comment by Araq** [comment]
Tail calls only happen to be supported when the underlying C compiler supports them and are a bad idea anyway. Use local variables instead of accumulator parameters and accept the fact that academia has fooled you once again as proofs by induction over functions using accumulator parameters are much harder to do than using Hoare logic.

**Comment by iacore** [comment]
Debug mode:
```c
        result = (NI)(TM__fpwKNEdUGOqBRrtoqn9aqrQ_3);
        }
BeforeRet_: ;
        popFrame();
        return result;
}
```

Release mode:
```c
        result = (NI)(TM__fpwKNEdUGOqBRrtoqn9aqrQ_3);
        goto BeforeRet_;
        }
BeforeRet_: ;
        return result;
}
```

It seems like `popFrame()` is stopping the C compiler from optimizing tail call. Is it possible to call `popFrame()` before `result = ...`?

Here's the Nim program I used: [About -foptimize-sibling-calls](https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Optimize-Options.html#index-foptimize-sibling-calls)

```nim
{.localPassC: "-foptimize-sibling-calls".}

proc recur(x: int): int =
  if x <= 0:
    return 0
  recur(x - 1) + x

proc tailrecur(x: int): int =
  if x <= 0:
    return 0
  tailrecur(x - 1)

echo recur(10000)
echo tailrecur(10000)
```

**Comment by heterodoxic** [comment]
Out of sheer curiosity, I have been toying with the codegen of this a tiny bit. The only actual difference, between the release and debug C code output in the sample code you provided, lies in the call frame management, which is absent in the release version. Merely moving `popFrame()` around, which is only a small part of this mechanism, would not change the outcome in any way, as the limiting factor is not the C compiler's inlining heuristics, but Nim's call depth threshold (which you can override with the `nimCallDepthLimit` switch). **Maybe** some optimizations in the call frame management code could do the job, but why not actually honor `nimCallDepthLimit=<int>` here?

**Comment by iacore** [comment]
So in release mode call depth is not checked?

**Comment by heterodoxic** [comment]
AFAIK, as long as you do not use `--stackTrace:on` in release mode, the call depth won't be checked.

**Comment by iacore** [comment]
Should I close this issue?

**Comment by beef331** [comment]
Probably, there is no bug here. Debug builds have a debug utility to prevent deeply recursive procedures.

**Comment by mildred** [comment]
If using tail call optimization as a form of looping, you really need to pop the stack frame before you jump to the tail call. Possibly, you are loosing stack frames on exceptions, depending on what you do that might or might not be ok.

If we really want to have tail calls I believe a specific instruction should be used to flag tail calls and tell the compiler you do not want the stack frames:

```nim
def count2(n: int)

def count1(n: int) =
  if n <= 0:
    return
  echo $n
  tailcall count2(n-1)

def count2(n: int) =
  if n <= 0:
    return
  echo $n
  tailcall count1(n-2)
```

Note: the tailcall must call a function that has the exact same return type else it will not work.

Lua has tail call optimization that can be used as a form of looping, and when it is in effect, you miss stack frames but it is explicit. You get an ellipsis in your stack trace where tail calls happened.
