### ISSUE TITLE
Cannot convert  UncheckedArray to openArray

### ISSUE THREAD

**Issue by actondev** [nim-lang/Nim#21858]
### Description

Both devel and stable seem broken with this.
What I've tried:

``` nim
let x = cast[ptr UncheckedArray[int]](nil)
let y = toOpenArray(x, 0, 0)
```
Gives
```
Error: invalid type: 'openArray[int]' for let
```

Following [this](https://nim-lang.org/docs/destructors.html#motivating-example) example, I was trying to convert my custom vector to openArray:

``` nim
type
  Vector*[T] = object
    len, cap: int
    data*: ptr UncheckedArray[T]

proc toOpenArray*[T](x: var Vector[T]): openArray[T] =
  toOpenArray(x.data, 0, x.len - 1)

var vec: Vector[int]
let arr = vec.toOpenArray()
```
Gives
```
Error: 'result' cannot be assigned to
```
[sic]! This error refers to the beginning of the line of the `proc toOpenArray` definition.

I've seen some other open bugs with `openArray` & `UncheckedArray` but they're mostly for some edge cases, here the most basic thing seems to not work

### Nim Version

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

**Comment by ghost** [comment]
That's because you can't store `openArray`s in a variable unless you use experimental views https://nim-lang.org/docs/manual_experimental.html#view-types

**Comment by actondev** [comment]
Oh, I see! thanks!
