### ISSUE TITLE
Overloaded enum not resolved properly

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#21861]
### Description

Example below would fail to compile. In large projects name clash for enum/proc/varname are very common and you frequently have these problems. 

```Nim
proc home() = discard

type E1 = enum home, post

proc fn(e: E1) =
  case e
  of home: discard
  of post: discard
```

Error:

```
cannot generate VM code for home
```

### Nim Version

Nim Compiler Version 1.6.12 [MacOSX: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise

### Expected Output

```text
In both cases enum should be resolved correctly.
```

**Comment by beef331** [comment]
1) Yes, you're right
2) No you're wrong. It's ambiguous if you want a `proc` or enum field.

**Comment by al6x** [comment]
@beef331 thanks, you are right, I updated the ticket.

**Comment by metagn** [comment]
Works in devel?
