### ISSUE TITLE
Compilation regression on generic parameter with default

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#21883]
### Description

Not sure what causes this bug exactly, but here is a minimal repro:
```nim
import chronos/apps/http/httptable
proc sendResponse*(headers: HttpTables = HttpTable.init()) =
  var headers = headers
  headers.set("Content-Length", "hey")
sendResponse()
```
(relies on chronos, but the relevant things from httptable could be extracted to another module)

On devel (b14043c39e40e941a79ef3794e2998b04387f5d2):
```
test.nim(7, 13) template/generic instantiation of `sendResponse` from here
test.nim(5, 10) Error: attempting to call routine: 'set'
  found system.set [type declared in /Nim/lib/system.nim(165, 3)]
```

On 2 weeks old devel (71f2e1a502ad231e3356217398e2d7fcd6137967):
```
56191 lines; 0.774s; 71.512MiB peakmem [SuccessX]
```

### Nim Version

b14043c39e40e941a79ef3794e2998b04387f5d2

**Comment by ringabout** [comment]
The regression is caused by https://github.com/nim-lang/Nim/pull/21837
