### ISSUE TITLE
Type conversion on overloaded enum field does not always call

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#21887]
### Description

```nim
type
  EnumA = enum A = 300, B
  EnumB = enum A = 10
  EnumC = enum C

echo EnumC(A)
```

### Nim Version

Recent devel

### Current Output

```text
`A` 
```

### Expected Output

Should error either '`A` cannot be converted to EnumC' or '`A` is ambiguous'

**Comment by beef331** [comment]
Testing further seems the issue is that `EnumC(A)` evaluates as `EnumA`
```nim
type
  EnumA = enum A = 300, B
  EnumB = enum A = 10
  EnumC = enum C

assert typeof(EnumC(A)) is EnumA
```

**Comment by ringabout** [comment]
Seems to be a known issue https://github.com/nim-lang/RFCs/issues/294

But I assume it might be disabled for v2 → https://github.com/nim-lang/Nim/pull/18546

It gives a warning fwiw

> Warning: suspicious code: enum to enum conversion [EnumConv]

**Comment by beef331** [comment]
Notice the secondary code example, it's not even converting. We're telling it to convert `A` to `EnumC` but it's staying as `EnumA`. The issue name is now incorrect with that, sorry.
