### ISSUE TITLE
hotcodereloading requires programResult

### ISSUE THREAD

**Issue by SrMordred** [nim-lang/Nim#21885]
### Description

```nim 
# main.nim
echo "Hello"
```
`nim c --hotcodereloading:on -r main.nim`
Output:
```
(...)
Error: system module needs: programResult
```

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]

**Comment by metagn** [comment]
Reason is hot code reloading tries to get `programResult` symbol in every compiled and imported module but some modules are imported in `system` before `programResult` is defined, these imports are only in devel and not in 1.6

**Comment by SrMordred** [comment]
This fix created other bug:
```nim
Error: unhandled exception: cgen.nim(1474, 7) `prc != nil`  [AssertionDefect]
```

**Comment by metagn** [comment]
Use `--mm:refc`, there is no support for arc/orc in hot code reloading for now

**Comment by SrMordred** [comment]
Didn´t solved :(
At least in `devel --latest` 
Received a wall of errors with `--mm:refc`

**Comment by metagn** [comment]
I managed to get it working in #21940 but can you check if current version-1-6 works?

**Comment by SrMordred** [comment]
With `devel --latest` : Same issues
With `1.6.12` : After reading about the missing `nimhcr.dll`  and `nimrtl.dll` and creating then, it works, both with `--mm:recf` and without it.
