### ISSUE TITLE
int parameter in `{.global.}` assignment generates invalid code

### ISSUE THREAD

**Issue by Gruruya** [nim-lang/Nim#21896]
### Description

Procedure that accepts int/bool and then assigns that to a global variable generates invalid code, strings work fine.

Example:
```Nim
proc example(a = 1) =
  let b {.global.} = a

example()
```

### Nim Version

bdccc9fef93d6598ec453a19152c4e98539f783f
Also occurs on 1.2, 1.4, 1.6; arc, refc, markandsweep, none

### Current Output

```text
......................................................................
/home/user/test.nim(2, 7) Hint: 'b' is declared but not used [XDeclaredButNotUsed]
CC: .nim/devel/lib/std/private/digitsutils.nim
CC: .nim/devel/lib/system/dollars.nim
CC: .nim/devel/lib/system.nim
CC: test.nim
/home/user/.cache/nim/test_d/@mtest.nim.c: In function ‘NimMainModule’:
/home/user/.cache/nim/test_d/@mtest.nim.c:122:22: error: ‘a_p0’ undeclared (first use in this function)
  122 |         b__test_u3 = a_p0;
      |                      ^~~~
/home/user/.cache/nim/test_d/@mtest.nim.c:122:22: note: each undeclared identifier is reported only once for each function it appears in
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -pthread -g3 -Og   -I/home/user/.nim/devel/lib -I/home/user -o /home/user/.cache/nim/test_d/@mtest.nim.c.o /home/user/.cache/nim/test_d/@mtest.nim.c' failed with exit code: 1
```

**Comment by heterodoxic** [comment]
Is this supposed to be disallowed on a language level, as I understand your attempt to fix this issue with #21900, @bung87? If not, it seems to me that the change introduced [here to tackle #576](https://github.com/reactormonk/nim/commit/08193e0a5bbb71b275246d6fd93457396c85d2f8#diff-3c6741ab46d3e800b2f5450aa5dbb98bf1de09088ccbc6146ab54d978aa57044R154-R156) leads to the wrong proc (the module's `preInitProc` ) being targeted for codegen.

**Comment by bung87** [comment]
I dont know the language design part, I've tested from nim 1.2,1.4,1.6, none of them works, as parameter decared at local scope, and the message `"cannot assign local to global variable"`  exists, so I think it's fine just follow these behaviors.

**Comment by heterodoxic** [comment]
To clarify: I myself am not a friend of the `global` pragma, because besides offering a higher degree of syntactic flexibility in how to express static storage duration, it dilutes the scopes of variables on the other hand (and ARC/ORC emphasize scope based memory management), and requires not only a cognitive but also architectural overhead for keeping this speciality around. With the adjustment you suggest, I wonder if globally "pragmatized" variables will become less useful...?

**Comment by Gruruya** [comment]
Guys I think it's a bug, it only happens with ordinals. For instance this works:
```Nim
proc example(a = @[1]) =
  let b {.global.} = a

example()
```

**Comment by bung87** [comment]
It only works on arc/orc, generated code
```c
N_LIB_PRIVATE N_NIMCALL(void, example__t5049565754_u1)(tySequence__qwqHTkRvwhrRyENtudHQ7g a_p0) {
	nimfr_("example", "t21896.nim");
	nimln_(7);
	eqcopy___t5049565754_u14((&b__t5049565754_u7), a_p0);
	popFrame();
}
```

**Comment by Gruruya** [comment]
Still producable with the below, if it matters.
```Nim
proc example(a = @[0]) =
  let b {.global.} = a[0]

example()
```
