### ISSUE TITLE
seq[T] is opaque in generated C header

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#21894]
### Description

While compiling nim code to C static library with `--header`, a header file is generated.

Even though memory layout `seq[T]` is trivial, it's not exposed in the header file.

\> [Reproduction repo](https://github.com/iacore/nim-c-header-repro) <

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 71f2e1a502ad231e3356217398e2d7fcd6137967
active boot switches: -d:release

### Additional Information

I don't think `--header` is documented in `nim --fullhelp`.

**Comment by Araq** [comment]
`--header` is not officially supported and creating a `seq[T]` from C is not trivial anyway, trivial memory layout hin oder her.

**Comment by iacore** [comment]
Reading memory of `seq[T]` from C is trivial.

What's the supported way to use Nim functions from C?
