### ISSUE TITLE
SIGSEGV when trying to read from Channel while the Thread variable is freed

### ISSUE THREAD

**Issue by iacore** [nim-lang/Nim#21907]
### Description

A simple usage of `Channel` with `createThread` doesn't work.

```nim
var ch: Channel[int]
ch.open()

proc f(arg: int) {.thread.} =
  ch.send(arg)

var thread: Thread[int]

createThread(thread, f, 1)
thread.dataFn.reset() # the line that causes crash

let i = ch.recv()
echo i
```

Another example:
```nim
var ch: Channel[int]
ch.open()

proc f(arg: int) {.thread.} =
  ch.send(arg)

for i in 0..2:
  var thread: Thread[int]

  createThread(thread, f, 1)

let i = ch.recv()
echo i
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-24
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 9493e6729138ecfdbc3f6ad433a32fcf19467a34
active boot switches: -d:release

### Current Output

```text
No stack traceback available
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
It should not crash
```

**Comment by iacore** [comment]
Found this issue mentioned [here](https://github.com/nim-lang/Nim/issues/4621#issuecomment-241205211)

**Comment by ringabout** [comment]
Have you tried https://github.com/nim-lang/threading which intends to work with ORC better?

**Comment by Araq** [comment]
So learn how to use the API.
