### ISSUE TITLE
Module and filename collision: module 'foo' cannot import itself

### ISSUE THREAD

**Issue by actondev** [nim-lang/Nim#21938]
### Description

Consider the scenario:
- install the `fooBackend` library from nimble
- you develop a library and want to support multiple backends (`fooBackend`, `barBackend`)
- add the `fooBackend` implementation under `mylib/fooBackend.nim`
- in that file you have `import fooBackend`
- run `nim c -r mylib/fooBackend.nim`. This gives an error

`Error: module 'fooBackend' cannot import itself`

AFAIU it has to do with the search paths. `import fooBackend` searches for both the directory of the current nim file, and any other search path (eg of nimble packages). It seems that the current directory is higher on priority than the other search paths. IMO the search path should have higher priority, and the local directory should be searched afterwards. If one prefers a local file over a library of the same name the `import ./myLocalFile` syntax should be used (given that a `myLocalFile` library is installed in the search path)

Some specific context:
While working on some vector graphics library, I wanted to have `svg` and `pixie` backends, and the `pixie` backend would be under `myLib/pixie.nim`, which would `import pixie`.. But that's an error

### Nim Version

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

**Comment by SolitudeSF** [comment]
if you want to enforce importing from a package you should use `pkg/` prefix. https://nim-lang.org/docs/manual.html#modules-pseudo-importslashinclude-paths
i disagree that local paths should be lower priority over external packages.

**Comment by actondev** [comment]
Thank you for pointing to the `pkg/`, didn't know of it. Closing since it already addresses this scenario.
