### ISSUE TITLE
Can't use generic function for initializing field of generic object

### ISSUE THREAD

**Issue by tsoj** [nim-lang/Nim#21941]
### Description

The following snippet doesn't compile:
```nim
func what[T](): T =
    discard

type MyObject[T] = object
    f: T = what[T]()

var m: MyObject[float] = MyObject[float]()
echo m
```
However, this one works fine:
```nim
func what[T](): T =
    discard

type MyObject = object
    f: float = what[float]()

var m: MyObject = MyObject()
echo m
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-27
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2beea7281061822b69e77715c8b0c30ed4d55a5c
active boot switches: -d:release

### Current Output

```text
/tmp/testtest/main.nim(5, 12) Error: cannot instantiate: 'what[T]'
```

### Expected Output

```text
(vec: 0.0)

# or an easier to understand error message
```

**Comment by Araq** [comment]
We only want to allow constant values in object field initializers anyway. Ping @ringabout

**Comment by ringabout** [comment]
`f: T = what[T]()` cannot be evaluated at the compile time when the object is defined, which might be improved by a better error message.

**Comment by tsoj** [comment]
Does this mean that even the second example with
```nim
type MyObject = object
    f: float = what[float]()
```
shouldn't compile, or is it just that any generic parameter can't be used for default initialization?

**Comment by ringabout** [comment]
The default value of object fields is handled by `semConstExpr`  when it semchecks the definition of an object. The second example works because `what[float]()` is known at the compile time and is instantiated when it is evaluated. It is not the case of `what[T]()`.

**Comment by beef331** [comment]
> We only want to allow constant values in object field initializers anyway.

@Araq  what about when it comes to things like mathematical vectors? If only constant values and not constant expressions are allowed anything that has it's own constructors procedures cannot be used.

**Comment by arnetheduck** [comment]
> We only want to allow constant values in object field initializers anyway.

this seems like an unnecessary limitation, ie anything that evaluates to a constant should be fair game - there's no fundamental reason `func f(): float = 42.0` shouldn't work as an initializer - generic or not.

**Comment by metagn** [comment]
Now crashes the compiler with `Error: VM problem: dest register is not set`, probably since #24010
