### ISSUE TITLE
[Regression] Type conversion by calling generic does not compile anymore

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#21958]
For the past couple days, I get errors in CI on the following:

https://github.com/mratsim/constantine/actions/runs/5114102019/jobs/9194006421#step:20:12

![image](https://github.com/nim-lang/Nim/assets/22738317/d58479ce-5bcb-4992-9e69-c154fc5c3fbb)
![image](https://github.com/nim-lang/Nim/assets/22738317/27678fa1-6e89-4c25-9273-f35d3f6426cb)

I strongly suspect this is due to https://github.com/nim-lang/Nim/commit/446e5fbbb3941820847ad209576493a73d78bb61

**Comment by metagn** [comment]
Should have been same as #21883? Will investigate

**Comment by mratsim** [comment]
I think this is a minimal repro

```Nim
type
  Ct*[T: SomeUnsignedInt] = distinct T

template `shr`*[T: Ct](x: T, y: SomeInteger): T = T(T.T(x) shr y)

var x: Ct[uint64]
let y = x shr 2
```

Trying to compile the 1.6.13 branch to confirm

**Comment by mratsim** [comment]
I can confirm this reproduces the issue.

> Should have been same as #21883? Will investigate

I don't think so, it worked 2 weeks ago when that issue was raised. And my issue involves generics conversion. The syntax has been working for years:

![image](https://github.com/nim-lang/Nim/assets/22738317/e5c0a882-fc1e-463f-96dc-1a0129d1e311)

**Comment by metagn** [comment]
Sorry, I didn't realize it was 1.6. The issue surrounding #21883 is entirely in devel, and your test case works in devel for me.

It might be https://github.com/nim-lang/Nim/commit/42ff3aa75a3c352c2b6bcb2301538f25ee8006e8?

**Comment by metagn** [comment]
It was 42ff3aa75a3c352c2b6bcb2301538f25ee8006e8, the minimal test case works before it and breaks after it. It works in devel though (probably depends on some changes in devel)

**Comment by metagn** [comment]
@narimiran could you also revert https://github.com/nim-lang/Nim/commit/42ff3aa75a3c352c2b6bcb2301538f25ee8006e8 in 1.6?

**Comment by narimiran** [comment]
> @narimiran could you also revert https://github.com/nim-lang/Nim/commit/42ff3aa75a3c352c2b6bcb2301538f25ee8006e8 in 1.6?

Reverted.
