### ISSUE TITLE
`os.dirExists` and `os.fileExists` validity in `func` depends on Windows or Linux target

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#21977]
### Description

`os.dirExists` and `os.fileExists` validity in `func` depends on Windows or Linux target. For example,

```nim
import os
func f() = discard dirExists("")
```
and
```nim
import os
func f() = discard fileExists("")
```
both compile without warnings or errors on both Nim 1.6 and current `devel` on Linux, but fail to compile on Windows, because `Error: 'f' can have side effects` and `Hint: 'f' calls .sideEffect 'fileExists'`.

This is a surprising result and it reduces the portability of purely standard library-using Nim code. Ideally, this code either compiles on Linux, macOS, and Windows, or it compiles on none of them. This basic usage of `std/os`, not `std/posix` or `std/winlean` which are by their nature platform-dependent, should abstract away the underlying differences causing this.

### Nim Version

```
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-05-21
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release
```

```
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-31
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b880cdff49576c0eb83a043cbae595d3587c95b4
active boot switches: -d:release
```

### Current Output

```text
Compilation on Linux and macOS and side effect error on Windows.
```

### Expected Output

```text
Consistent either compilation or not, regardless of platform
```

**Comment by Araq** [comment]
Should be rejected on UNIX too, we regard the filesystem as a global mutable variable.

**Comment by ringabout** [comment]
On it.
