### ISSUE TITLE
Error compiling with ARC/ORC

### ISSUE THREAD

**Issue by zeitbit** [nim-lang/Nim#21974]
### Description

Compiling this code with _ARC/ORC_ produces the exception "_fatal.nim(53) sysFatal Error: unhandled exception: field 'intVal' is not accessible for type 'TNode' using 'kind = 29' [FieldDefect]_".
It works compiling with _--mm:none_ or _--mm:refc_.

```nim
type Test*[T] = ref object
    values : seq[T]
    counter: int

proc newTest*[T](): Test[T] =
    result         = new(Test[T])
    result.values  = newSeq[T](16)
    result.counter = 0

proc push*[T](self: Test[T], value: T) =
    self.counter += 1
    if self.counter >= self.values.len:
        self.values.setLen(self.values.len * 2)
    self.values[self.counter - 1] = value

proc pop*[T](self: Test[T]): T =
    result         = self.values[0]
    self.values[0] = self.values[self.counter - 1] # <--- This line
    self.counter  -= 1

when isMainModule:
    type X = tuple
        priority: int
        value   : string

    var a = newTest[X]()
    a.push((1, "One"))
    doAssert a.pop.value == "One"
```

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-05-29

**Comment by ringabout** [comment]
fwiw, with my fieldDefect fixing commit, at least it shows the kind is `nkInfix`: `Error: unhandled exception: field 'intVal' is not accessible for type 'TNode' using 'kind = nkInfix'`
