### ISSUE TITLE
Lifting the =dup hook broke existing code

### ISSUE THREAD

**Issue by Pylgos** [nim-lang/Nim#21989]
### Description

The `=dup`hook is now lifted by #21903, causing the compiler to insert `=dup` in some places where it originally inserted `=copy`. This breaks existing code that implements only the `=copy` hook, such as  [nim-lang/threading/smartptrs.nim](https://github.com/nim-lang/threading/blob/03a5b433313b1db283d4294dc2ee7e15c2899c1b/threading/smartptrs.nim).

Here is an example
```nim
type Rc = object
  counter: ptr int

proc `=destroy`(self: var Rc) =
  if self.counter != nil:
    dec self.counter[]
    if self.counter[] == 0:
      echo "destroy!"
      # deallocShared self.counter

proc `=copy`(dest: var Rc, src: Rc) =
  `=destroy`(dest)
  wasMoved(dest)
  if src.counter != nil:
    echo "copy!"
    inc src.counter[]
    dest.counter = src.counter

proc use(self: sink Rc) =
  discard

proc newRc(): Rc =
  result.counter = createShared(int)
  result.counter[] = 1

proc main =
  var x: Rc
  block:
    var a = newRc()
    use(a)
    x = a
  echo x.counter[]

main()

# --expandArc: main
# var
#   x
#   :tmpD
# try:
#   block :tmp:
#     var
#       a
#       :tmpD_1
#     a = newRc()
#     use:
#       :tmpD_1 = `=dup`(a)
#       :tmpD_1
#     x = a
#   echo [
#     :tmpD = `$`(x.counter[])
#     :tmpD]
# finally:
#   `=destroy`(:tmpD)
#   `=destroy_1`(x)
# -- end of expandArc ------------------------
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1133f20fe2c834d14454c32d7d9fc2cd1fe8ffa2
active boot switches: -d:release

### Current Output

```text
destroy!
0
```

### Expected Output

```text
copy!
1
destroy!
```

**Comment by planetis-m** [comment]
I will take care of this with a PR in threading.

**Comment by ringabout** [comment]
for the record => https://github.com/nim-lang/threading/pull/34 which is related to this issue
