### ISSUE TITLE
nimfix no longer building since path changed in nimfix.nim.cfg

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#2200]
This is the change: https://github.com/Araq/Nim/commit/b6cde0bab01086f0d0e840f05a2f7ea375e2d3a8

And the error is "cannot open 'doc/basicopt.txt'".

Reverting that change fixes the problem.

**Comment by oderwat** [comment]
I would like to know why the former version does not compile for me while after the change it does not compile for you. I guess the best solution may be to have both paths in the config.

**Comment by Araq** [comment]
'nim c compiler/nimfix/nimfix' does work again.
