### ISSUE TITLE
`try` expression misdetects type when raising

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22007]
### Description

```nim
let v =
  try:
    raise (ref ValueError)()
  except ValueError:
    42
```

The above should be an `int`,

### Nim Version

1.6.12, devel

### Current Output

```text
testit.nim(5, 5) Error: expression '42' is of type 'int literal(42)' and has to be used (or discarded)
```

**Comment by heterodoxic** [comment]
Hey, would you mind checking if this happens for both the C and C++ backend, and, if you wanted to be superduper-nice: for all three exceptions implementations (CPP, goto, quirky)? 🙂

**Comment by arnetheduck** [comment]
this is a compile-time error during type checking, it shouldn't matter what backend it is - that said, unfortunately I don't have time to entertain them really, they're incomplete / experiments as far as I'm concerned so it's better someone familiar with them looks into it.

**Comment by Araq** [comment]
Why should the type be `int`? Makes no sense. The type is taken from the body after the `try` which is `void` because it raises. There is not even a `finally`. The type checking does not depend on a control flow graph, you cannot say "ah but the compiler sthould detect that this construct in particular will always raise"

**Comment by arnetheduck** [comment]
>  The type is taken from the body after the try which is void because it raises.

arguably the `raise` doesn't have a type, ie consider:

```nim
let v = if false:
    raise (ref ValueError)()
  else:
    32
```

this resolves to `int` as expected - `try/except` is just another branchy control-flow statement

**Comment by arnetheduck** [comment]
ie the type of a `try/except` should be equal in all branches that don't escape but `raise` does escape, so just like in `if/else` it should not be considered. same with `case/of/else`.

**Comment by Araq** [comment]
Fair enough.
