### ISSUE TITLE
Some procs appear twice in documentation

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2201]
For example writeStackTrace: http://nim-lang.org/system.html#writeStackTrace,_2

**Comment by def-** [comment]
This only happens with `nim doc2` (not `nim doc`), a proc that is split between definition and declaration, and enclosed in a `defined`. Minimal example:

```nimrod
when defined(posix):
  proc foo*

  proc foo =
    discard
```

**Comment by Araq** [comment]
This has been fixed.
