### ISSUE TITLE
vcc fails with `The filename or extension is too long.` when linking

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#22025]
### Description

When the Nim produced file is too long (i.e. the compiler API included in another application) `vcc` will fail when linking

### Nim Version

All

### Current Output

```text
PS C:\Users\juama\5.2\NimTemplate\Plugins\NimForUE> vccexe.exe "@vm_linkerArgs.txt"
Hint: using C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat
C:\NimSources\Nim\tools\vccexe\vccexe.nim(226) vccexe
C:\NimSources\Nim\lib\pure\osproc.nim(747) startProcess
C:\NimSources\Nim\lib\std\oserrors.nim(92) raiseOSError
Error: unhandled exception: The filename or extension is too long.
Additional info: cl.exe [OSError]
```

### Expected Output

```text
Creating library C:\Users\juama\5.2\NimTemplate\Plugins\NimForUE\Binaries\nim\vm.lib and object C:\Users\juama\5.2\NimTemplate\Plugins\NimForUE\Binaries\nim\vm.exp
```

### Possible Solution

Force relative paths in vcc will remediate the issue to some extend.

**Comment by zhmt** [comment]
When compiling the following program, I encountered this issue:
https://github.com/vacp2p/nim-libp2p/blob/master/examples/circuitrelay.nim

nim version: 2.2.4
OS: windows 10
compiler: vcc (cl.exe) from Visual studio 2022

How to reproduce the error:
1. nimble install libp2p
2. set cc=vcc in config.nims
3. copy source code into a nim file
4. build it
5. It will failed to link.
