### ISSUE TITLE
`import ./modulename` ignores the `./` path prefix

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#22065]
### Description

```nim
import "."/tables
import ./tables
```
even in a directory with no `tables.nim` or other way of finding a `tables` module` to import, compiles.

https://nim-lang.org/docs/manual.html#modules-import-statement doesn't seem to explicitly document what should happen in this situation, but "." is a way of specifying a path. Indeed, attempting to import `./std/tables`, for example, does not work, because it is being treated as a path, so there's an inconsistency here at least.

### Nim Version

```
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b2d77619757c73a8b14a8ccf127eaf3e630159cf
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-06-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release
```

### Current Output

```text
/tmp/b.nim(2, 8) Hint: duplicate import of 'tables'; previous import here: /tmp/b.nim(1, 11) [DuplicateModuleImport]
/tmp/b.nim(1, 11) Warning: imported and not used: 'tables' [UnusedImport]
/tmp/b.nim(2, 8) Warning: imported and not used: 'tables' [UnusedImport]
```

### Expected Output

```text
Error: cannot open file: tables
```

**Comment by metagn** [comment]
I think there is no special casing for relative paths, it just checks `path / importedPath` for every path supplied by `--path`:

```nim
import ../sugar # compiles because of lib/pure/collections/../sugar
import ../tables # fails
```

There might be related issues here or in https://github.com/nim-lang/RFCs with the keyword "relative"

**Comment by tersec** [comment]
Yeah, generally related RFCs:

- https://github.com/nim-lang/RFCs/issues/73 is a kind of meta-issue around the inconsistency across different ways of specifying paths, but doesn't address `import` in any specific way
- https://github.com/nim-lang/RFCs/issues/267 is especially related -- suggests `this` keyword which enforces the path aspect
- https://github.com/nim-lang/RFCs/issues/291 notes other oddities/surprises about what kinds of paths/pseudo-paths are/aren't allowed in `import`

**Comment by arnetheduck** [comment]
+1 on this, `.` and other explicitly relative paths should not resolve in random locations .. this also opens for including nastiness like `../../etc/passwd` and other security-sensitive files

**Comment by Araq** [comment]
That's the final thing I wanted to do for 2.0.
