### ISSUE TITLE
{.emit.} may crash compiler when a symbol has overloads

### ISSUE THREAD

**Issue by mrgaturus** [nim-lang/Nim#22068]
### Description

for example, "handle" is overloaded but i want pass my proc called handle to {.emit.} it can crash the compiler because handle is overloaded with other symbol from threads module

```nim
proc handle(obj: pointer, d, u, m, y: cint) = discard
{.emit: ["// ", handle].} #" crashes if proc is called "handle"
```

```nim
{.emit: ["// ", handle].} #" also crashes if "handle" is not defined
```

```nim
var handle = 10
{.emit: ["// ", handle].} #" this compiles
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-02
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c507ced51e19f530f39ee059e0c272638229a7b1
active boot switches: -d:release

### Current Output

```text
Error: internal error: getTypeDescAux(tyNone) # when "handle" is a proc
Error: internal error: getTypeDescAux(tyGenericParam) # when "handle" does not exists
```

### Expected Output

```text
generate on c code:
// <symbol name on c generated>
```

### Possible Solution

is there a way for choose which symbol i want to pass?

**Comment by metagn** [comment]
> is there a way for choose which symbol i want to pass?

You can specify the type:

```nim
{.emit: ["// ", (proc(obj: pointer, d, u, m, y: cint))(handle)].}
```

Or you can qualify with the name of the module `handle` is defined in:

```nim
{.emit: ["// ", thismodule.handle].}
```

**Comment by mrgaturus** [comment]
Thanks @metagn, so, should the expected output be an ambiguity error?

**Comment by metagn** [comment]
Maybe there is something else to do here but yeah that is the most obvious option

**Comment by metagn** [comment]
The ``{.emit: "// `handle`".}`` version seems to special case this to ignore identifier ambiguity:

https://github.com/nim-lang/Nim/blob/21d941c16a84daa855870717f064802b052d6792/compiler/pragmas.nim#L607-L614
