### ISSUE TITLE
`let` string between a proc's declaration&call and definition is yet not initialized

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#22079]
## Description
If you write in the order (see the following example):
1. declare of a proc
2. call it
3. define the string by `let` that is inferred
4. define the proc that infers outer's `let` string

Example:
```nim
proc arun()
arun()

let CnfPath = "cnf"
#const CnfPath = "cnf"  # if using `const` instead, there'll be no bug
# Also, if `CnfPath` is not a string, e.g. an int, there'll be no bug

proc arun() = echo CnfPath
```
Then the above `CnfPath` will just be a `""`(empty string) when referred.

(If looking at C code, you can find that string is assigned after referred by that pre-declared proc.)
## Nim Version
Nim Compiler Version 1.6.6/12

## Current Output
(None i.e. an empty string)
## Expected Output
cnf
## Possible Solution
May the string's init be put before being referred
## Additional Information
Also, above describes the C backend's output
What's more, when it comes js backend, there is also an error "Cannot read properties of undefined (reading 'length')"

(As that string's definition is after that proc, thus is an `undefined` when that proc is called)

**Comment by Araq** [comment]
Where it the bug? You run `arun` before the variable initialization.

**Comment by litlighilit** [comment]
> You run arun before the variable initialization.

`CnfPath` is before `arun`'s definition
And as mentioned above if you change the example into(use an `int` instead of `string`):
Example1: 
```nim
proc arun()
arun()

let CnfPath = 1

proc arun() = echo CnfPath
```
then its output is `1`

If you change it to(use `const` instead of `let`):
Example2: 
```nim
proc arun()
arun()

const CnfPath = "cnf"

proc arun() = echo CnfPath
```
then its output is `cnf`

**Comment by demotomohiro** [comment]
Following code runs `arun()` first, then runs `let y = (inc x; echo &"Set x({x}) to y"; x)` later.
```nim
import std/strformat

var x = 0

proc arun()
arun()

let y = (inc x; echo &"Set x({x}) to y"; x)
echo &"After let y = ..., x = {x}, y = {y}"

proc arun() =
  inc x
  echo &"In arun(), x = {x}, y = {y}"
```

Output:
```
$ nim c -r testlet.nim 
In arun(), x = 1, y = 0
Set x(2) to y
After let y = ..., x = 2, y = 2
```

But do you think `(inc x; echo &"Set x({x}) to y"; x)` should be evaluated before `arun()` is called and output should be like this?

```
Set x(1) to y
In arun(), x = 2, y = 1
After let y = ..., x = 2, y = 1
```

let variable having a value different from the initial value might looks strange.
But also the initial value is evaluated before statements above that let statement also looks strange.

```
$ nim -v
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 65c412e3f01bc00f5c6f318edfbfe561ab1bf438
active boot switches: -d:release
```

**Comment by litlighilit** [comment]
@Araq 
Is Nim's lexiacl scope rule different from others( e.g. C )? 
Is there any document describing it?


> Where it the bug? 

Now if take C as an example[^1]:
```c
#include<stdio.h>
void arun(void);
int main(void){arun();}

const char* CnfPath = "cnf";

void arun(void){puts(CnfPath);}
```
then its output is `cnf` 

[^1]: Of cource C's `char*` differs from Nim's `string`, but this example is to tell the C's lexical scope rule

**Comment by litlighilit** [comment]
@demotomohiro 
> But also the initial value is evaluated before statements above that let statement also looks strange. 

But it's normal in many languages. 

Now if take C as an example[^1]:
```c
#include<stdio.h>
void arun(void);
int main(void){arun();}

const char* CnfPath = "cnf";

void arun(void){puts(CnfPath);}
```
then its output is `cnf` 

[^1]: Of cource C's `char*` differs from Nim's `string`, but this example is to tell the C's lexical scope rule

**Comment by litlighilit** [comment]
All right, I understand it's reasonable. 
But if you combine my origin example, Example1, Example2 and demotomohiro's example, it's just a lot confusing. 

In summary, it's inconsistent: 
If one "let stmt" is split into more than one logical stmt, then it'll be evaluted separatedly. 
else the variable will be assigned even the assignment is after its being referred.

**Comment by Araq** [comment]
It cannot be "inconsistent" because it's a compiler which follows its steps deterministically.
