### ISSUE TITLE
uint32 conversion inconsistencies between nimvm, semfold, and runtime

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#22085]
### Description

```Nim
const 
  x = uint32(uint64.high) # vm error
  u = uint64.high
  v = uint32(u) # vm error

let 
  z = uint64.high
  y = uint32(z)  # runtime ok
    
let
  w = uint32(uint64.high)  # semfold error
```

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-06-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 25fe4124e66dd44a10609d531081e650e3d557aa
active boot switches: -d:release

----------------

Nim Compiler Version 1.6.12 [Windows: amd64]
Compiled at 2023-06-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

### Current Output

```text
Error: 18446744073709551615 can't be converted to uint32

or

Error: conversion from uint64 to uint32 is invalid
```

### Expected Output

```text
nothing in the manual, so I don't know what to expect
```

### Possible Solution

bitmasking to make sure the value stays within safe zone works

**Comment by metagn** [comment]
Also #12700
