### ISSUE TITLE
VM crash when passing toOpenArray to var openArray func

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#22095]
### Description

```Nim
type
  StUint = object
    limbs: array[4, uint64]

func shlAddMod(a: var openArray[uint64]) =  
  a[0] = 10

func divRem(r: var openArray[uint64]) =
  shlAddMod(r.toOpenArray(0, 3))

func fn(): StUint =
  divRem(result.limbs)
       
const
  z = fn()
```

The crash happen at the assignment

### Nim Version

Nim Compiler Version 1.6.12 [Windows: amd64]
Compiled at 2023-06-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

----

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-06-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 20dfdba2df7c0d4f65c90561ebf75c2084bbd64f
active boot switches: -d:release

### Current Output

```text
........................................................................fatal.nim(53)            sysFatal
Error: unhandled exception: field 'node' is not accessible for type 'TFullReg' using 'kind = rkInt' [FieldDefect]
```

### Expected Output

```text
no error
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
type Y = object
  x: array[2, int]
func a(a: var openArray[int]) = a[0] = 0
func b(r: var openArray[int]) = a(r.toOpenArray(0, 1))
func f(): Y = b(result.x)
const _ = f()
```
