### ISSUE TITLE
View types lifetime tracking does not work with defer

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/Nim#22117]
### Description

```nim
proc main =
  var a = 10
  var aref: var int = a
     #└──── 'aref' borrows from location 'a' which does not live long enough

  echo aref
```

```nim
proc main =
  var a = 10
  var aref: var int = a

  echo aref
  discard a # extend a's lifetime
```

`discard a` makes compiler happy but writing discard statement at the bottom of a function is imo hard to read. So I tried `defer`.

```nim
proc main =
  var a = 10
  defer: discard a # extend a's lifetime

  var aref: var int = a
     #└──── 'aref' borrows from location 'a' which does not live long enough

  echo aref
```
But it does not compile.

---

PS
  Is there a better way to extend a's lifetime other than using the discard statement?

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 77beb152141f0efe4d5c93b784e42f973ba46551
active boot switches: -d:release

### Current Output

```text
'aref' borrows from location 'a' which does not live long enough
```

### Expected Output

```text
no error
```

**Comment by juancarlospaco** [comment]
defer should have a warning listing all the weirdo behaviours it has,
and mark it as unsafe because potentially it may be.

**Comment by Araq** [comment]
Fwiw `try finally` does work but doesn't solve your stylistic problem, of course.
