### ISSUE TITLE
`exportc` code not exported to static library

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22134]
### Description

```nim
proc myFunction() {.exportc, cdecl.} = discard
```

```sh
nim c --app:staticlib --noMain myfile.nim
```

```c
  #define N_LIB_PRIVATE __attribute__((visibility("hidden")))
  N_LIB_PRIVATE N_CDECL(void, myFunction)(void);
```

When a function is marked with `visibility("hidden")`, it can no longer be called from C code, contrary to the intent of `exportc`.

### Nim Version

1.6.12

**Comment by metagn** [comment]
https://github.com/nim-lang/Nim/blob/db41f04ab0734b0ac5267b46f306b0a311f7fc71/compiler/ccgtypes.nim#L1202-L1210

`lfExportLib` is set with the `dynlib` pragma, so one would use `exportc, dynlib` to export to the static library. What is the expected output in the case with just `exportc`?

**Comment by ringabout** [comment]
> If the symbol should also be exported to a dynamic library, the `dynlib`
pragma should be used in addition to the `exportc` pragma. See
[Dynlib pragma for export].

As documented in the manual, a single exportc shouldn't export it to libs. So I suppose there should be an `exportLib` or `staticlib` pragma, which exports functions to libs/staticlibs. `dynlib` can probably be used as a workaround for staticlib.

**Comment by arnetheduck** [comment]
> As documented in the manual, a single exportc shouldn't export it to libs.

that's not what it says though: it only talks about dynamic libraries and the need to use `dynlib` for those - ie for static libraries, it doesn't say anything. 

`exportc` is kind of useless really if you always need another pragma to make it actually export the code to make it usable from c (for which library linking is needed).

**Comment by arnetheduck** [comment]
> dynlib to export to the static library.

this is wrong / orthogonal with respect to static libraries:
```
#    define N_LIB_EXPORT  NIM_EXTERNC __declspec(dllexport)
```

Consider the case of including a static library in a dynamic library: you do not want the symbols of the static library to escape into the "final" dynamic library unless they are `dynlib`-marked.

Basically, the sensible thing for `exportc` to do is to leave the default C symbol visibility - `dynlib` can then be used to further export the symbol when building shared libraries from the static library (and other sources).

**Comment by Araq** [comment]
>  ie for static libraries, it doesn't say anything.

Because static libraries are not really supported. ;-)

**Comment by arnetheduck** [comment]
> Because static libraries are not really supported. ;-)

meh. they're advertised by the compiler and the manual - one would thus expect them to (minimally) work at that point - here, the compiler goes out of its way to break them by marking the symbols hidden instead of just doing nothing.

**Comment by Araq** [comment]
There is the problem of how to combine 2 statically linked libraries, you can get conflicts because there are then 2 `nimAddInt` procs defined or other such nonsense.

**Comment by ringabout** [comment]
> When a function is marked with visibility("hidden"), it can no longer be called from C code, contrary to the intent of exportc.

Does it affect static libs though, it works on windows/Linux.

```nim
from system/ansi_c import cprintf

proc myFunction() {.exportc, cdecl.} =
  cprintf("12354\n")
```

```c
#include <stdio.h>

int main() {
  myFunction();
  printf("done");
}
```

ref https://stackoverflow.com/questions/67414559/hidding-symbols-from-a-static-library

> Visibility is ignored during static library link i.e. when linking libB.a and pulling functions from it linker will not look at visibility annotations at all. On the other hand, after functions are pulled (from libB.a) into final shared library (libA.so) they will be exported and pollute libA's interface unless you've hidden them via -fvisibility=hidden when compiling the static library itself.

**Comment by Araq** [comment]
> meh. they're advertised by the compiler and the manual - one would thus expect them to (minimally) work at that point

Agreed, but many problems were discovered afterwards and never really resolved as far as I know.

**Comment by arnetheduck** [comment]
Ok, nevermind, false alarm - I got the attributes wrong and managed had a bug in the build script, `hidden` is fine in this context and the current behavior is ok.

Ie linking to a static library with hidden symbols in it still allows those symbols to be used in that linking process - hidden just affects what happens afterwards.
