### ISSUE TITLE
Consistent nimsuggest crash on generics in first class functions

### ISSUE THREAD

**Issue by omentic** [nim-lang/Nim#22137]
### Description

Nimsuggest consistently crashes on the following code (minimal reproducible version)

```nim
import std/sugar

proc handle[T](op: (T, T) -> T) =
  discard

func named[T](a, b: T): T = typeof(a)(a == b)

handle(named)
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-06-20
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

**Comment by ringabout** [comment]
for the record, `nim check` gives

```
Error: internal error: C:\Users\blue\Documents\GitHub\Nim\compiler\seminst.nim(355, 3)       
Traceback (most recent call last)
```
