### ISSUE TITLE
Unknown hint: LineTooLong

### ISSUE THREAD

**Issue by notnoahpp** [nim-lang/Nim#22145]
### Description

trying to execute file with latest nim fails with `Unknown hint: LineTooLong`
- perhaps related to https://github.com/nim-lang/Nim/pull/21819

### Nim Version

09:29 AM (nimv2-mac|u=) 
$ nim -v
Nim Compiler Version 1.9.5 [MacOSX: amd64]
Compiled at 2023-06-23
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
09:49 AM (nimv2-mac *|u=) 
$ nim r -b:c src/bookofnim.nim
/Users/noahhall/git/foss/nim/config.nims(1, 2) Error: unknown hint: LineTooLong
```

```sh

10:05 AM (nimv2-mac|u=) 
$ nimble test
  Verifying dependencies for bookofnim@1.9.3
  Executing task test in /Users/noahhall/git/foss/nim/bookofnim.nimble
/Users/noahhall/git/foss/nim/config.nims(1, 2) Error: unknown hint: LineTooLong
stack trace: (most recent call last)
/private/var/folders/b8/0_b0vfsj2w53vykzj73r2xmr0000gq/T/nimblecache-4110388044/nimscriptapi_791643861.nim(210, 16)
/Users/noahhall/git/foss/nim/bookofnim.nimble(25, 3) testTask
/Users/noahhall/.choosenim/toolchains/nim-#version-2-0/lib/system/nimscript.nim(265, 7) exec
/Users/noahhall/.choosenim/toolchains/nim-#version-2-0/lib/system/nimscript.nim(265, 7) Error: unhandled exception: FAILED: nim e .github/scripts/test.nims [OSError]
       Tip: 1 messages have been suppressed, use --verbose to show them.
nimscriptwrapper.nim(160) execScript

    Error:  Exception raised during nimble script execution
```

### Expected Output

```text
file is executed
```

### Additional Information

<img width="863" alt="image" src="https://github.com/nim-lang/Nim/assets/129184615/f8cbfa32-d9b0-4a3b-a8a2-5cc8a32c2eef">

**Comment by notnoahpp** [comment]
also `nim -v` reports the apple m2 chip as amd, but shouldnt it be arm?

**Comment by metagn** [comment]
#21819

This hint was removed. Maybe it should have just become a no-op instead. Or at the very least, maybe we should stop fatal erroring on stuff like this.

Also the changelog in the PR says that hint was deprecated, but I don't see a record of that.

**Comment by notnoahpp** [comment]
lol @metagn  i'm an idiot

I was searching for `linetoolong` but it was case-sensitive so  it didnt match the line with `LineTooLong`
