### ISSUE TITLE
Generic constraints should affect match level

### ISSUE THREAD

**Issue by Graveflo** [nim-lang/Nim#22142]
### Summary

Consider the following:
```nim
type
    GenericObj[T] = object

proc test[T: GenericObj](param: T): T = param
proc test(param: object): int = 0
echo test(GenericObj[int]())
```
Nim will say that this is an "ambiguous call" but I have yet to understand what value this matching rule brings to Nim. It seems more appropriate to me that this call should not be ambiguous. Similarly, this code:
```nim
type
    GenericObj[T] = object

proc test[T: GenericObj](param: T): T = param
proc test(param: GenericObj): int = 0
echo test(GenericObj[int]())
```
which is currently not ambiguous, I think should be.

### Description

I will be accompanying this issue with a PR that I believe fixes this. The problem is that I am not sure if the current ambiguity rule is intentional, so I would appreciate some discussion if you think this is a bad idea.
Also the compiler code surrounding these matching rules is complex and I have *not*(<-edit) fully wrapped my head around it. Although I am submitting a PR I believe scrutiny is in order here.

**Comment by Araq** [comment]
This also needs to put into the spec and don't just add a paragraph, edit the existing rules so that we can see the changes.
