### ISSUE TITLE
BareExcept warning is sometimes not silenceable

### ISSUE THREAD

**Issue by ZoomRmc** [nim-lang/Nim#22163]
### Description

BareExcept warning is sometimes not silenceable:
```
toolchains\nim-#devel\lib\pure\unittest.nim(776, 5) Warning: The bare except clause is deprecated;
use `except CatchableError:` instead [BareExcept]
```
Minimal reproduction, `test.nim`:
```nim
import std/unittest

test "f":
  expect(ValueError): discard
```
Tested with: `nim -f --skipParentCfg --skipProjCfg --warning[BareExcept]:off r test.nim`
Adding `-w:list` shows ` [ ] BareExcept` both times.
Alternative form `--warning:BareExcept:off` changes nothing.
Setting from `config.nims` doesn't help.

**Does not** happen on current stable.

### Nim Version

Nim Compiler Version 1.9.5 [Windows: amd64]
Compiled at 2023-06-26

**Comment by ringabout** [comment]
will be fixed by https://github.com/nim-lang/Nim/pull/21390
