### ISSUE TITLE
redefining for loop variable semantics

### ISSUE THREAD

**Issue by anzhi0708** [nim-lang/Nim#22178]
### Summary

Go 1.21 is expected to support `GOEXPERIMENT=loopvar` as a way of trying out [new semantics](https://github.com/golang/go/wiki/LoopvarExperiment). 

Although previously, counter-intuitive **closure capture in loops** has appeared in some languages other than Go, such as Groovy, 

**modern languages like Scala, Dart, Kotlin, and Swift have all avoided this counter-intuitive situation**. JS can also define a local variable in a loop with `for(let i = 0; ....`
Currently, Nim requires the import of the sugar module to achieve this.
```nim
import std/sugar
var functions: seq[proc(): int] = @[]
for i in 1 .. 5:
  capture i:
    functions.add(proc(): int = i)

for fn in functions:
  echo fn()
```

### Description

I believe this is a very awkward and counter-intuitive behavior. 
The Go language team has been trying to correct this behavior, and I think the outcome is more understandable and easier to learn.

### Alternatives

I suggest changing the original default loop behavior, i.e., not creating a new scope with each loop, to something more intuitive. The original default behavior, which is more efficient and faster, can be available through the sugar module. In other words, the usage of the two should be switched.

### Examples

- this (**without** `std/sugar`)
```nim
var functions: seq[proc(): int] = @[]
for i in 1 .. 5:
  functions.add(proc(): int = i)

for fn in functions:
  echo fn()
```
result:
```
1
2
3
4
5
```

- while this
```nim
import std/sugar

var functions: seq[proc(): int] = @[]

for i in 1 .. 5:
  ref i:
    functions.add(proc(): int = i)

for fn in functions:
  echo fn()
```
prints
```
5
5
5
5
5
```

### Backwards Compatibility

I believe the Go language team's approach to solving this issue is worth referencing

**Comment by Araq** [comment]
Nim used to do it correctly but we had to make it compatible with JS semantics. It's a widely known problem. Of course the Go language designers wouldn't know about it...

**Comment by anzhi0708** [comment]
> Nim used to do it correctly but we had to make it compatible with JS semantics. It's a widely known problem. Of course the Go language designers wouldn't know about it...

@Araq 
❤️ Thank you for your hard work! I really like this language. It sounds reasonable. May I ask, will Nim Version 2.0 make any changes to this feature?
