### ISSUE TITLE
Regression when calling proc in generic instancing

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#22188]
### Description

Sorry about the long repro, couldn't reduce further:
a.nim:
```nim
import b

proc write*[T: uint32](value: T) =
  var length = 5
  var buffer: seq[byte]
  PB.putUVarint(buffer.toOpenArray(0, 1), length, value)

write(uint32(5))
```

b.nim:
```nim
import c

type 
  PB* = object 
  LP* = object


proc putUVarint*[T: PB|LP](vtype: typedesc[T],
                           pbytes: var openArray[byte],
                           outlen: var int,
                           outval: uint32) =
  let bytes = toBytes(outval, Leb128)
```

c.nim:
```nim
type Leb128* = object

func maxLen*(T: type Leb128, I: type): int8 = 1
  
type Leb128Buf*[T: SomeUnsignedInt] = object
    data*: array[maxLen(Leb128, T), byte]

func toBytes*[I: SomeUnsignedInt](v: I, T: type Leb128): Leb128Buf[I] {.noinit.} = discard
```

Nim devel: `c.nim(6, 18) Error: undeclared identifier: 'maxLen'`
Nim 1.6.14: `compiles`

### Nim Version

13b7e4e0e5f6edf573ee725dd52669ac5687cb5b

### Additional Information

This started approximately on the 14th of june, so maybe this PR caused it? https://github.com/nim-lang/Nim/pull/22029

**Comment by metagn** [comment]
Try any commit after 6d2163724550ed3a115d22e00f9d40150534a8b9, the hash given above is 3 days before it

**Comment by Menduist** [comment]
Oh right my bad, didn't realized you already fixed it
Sorry, and thanks for the quick fix!
