### ISSUE TITLE
Duplicate 'extern' declaration specifier when using Clang

### ISSUE THREAD

**Issue by DiThi** [nim-lang/Nim#22199]
### Description

Create a file with:

    proc foo*() {.exportc,dynlib.} = discard

Compile in Linux with:

    nim cpp --app:lib --cc:clang --passC:"-Werror"

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-06-30
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 210b10dd0d47c8c79b686a69eb8646df869cf207
active boot switches: -d:release

### Current Output

```text
/home/dithi/.cache/nim/bug_r/@mbug.nim.cpp:21:12: error: duplicate 'extern' declaration specifier [-Werror,-Wduplicate-decl-specifier]
extern "C" N_LIB_EXPORT N_CDECL(void, foo)(void);
           ^
/home/dithi/.choosenim/toolchains/nim-#devel/lib/nimbase.h:214:24: note: expanded from macro 'N_LIB_EXPORT'
#  define N_LIB_EXPORT NIM_EXTERNC __attribute__((visibility("default")))
                       ^
/home/dithi/.choosenim/toolchains/nim-#devel/lib/nimbase.h:159:23: note: expanded from macro 'NIM_EXTERNC'
#  define NIM_EXTERNC extern "C"
                      ^
```

### Expected Output

```text
(No error)
```

### Possible Solution

Remove one of the two `extern "C"` when using N_LIB_EXPORT, I guess?

Removing `-Werror` in my current use case may be tricky so it's much easier for me to just edit the N_LIB_EXPORT macro for now.

**Comment by Araq** [comment]
We cannot support -Werror as the warnings are a moving target and irrelevant for generated code.
