### ISSUE TITLE
Compile error when running a Nimscript that compares seq with switch("mm", "arc")

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#22212]
### Description

Compile error from following code only when it runs as Nimscript and set mm compile option to arc in `config.nims` in the same directory as the Nimscript file.

testmm2.nims:
```nim
discard @[1] == @[1]
```

config.nims:
```nim
switch("mm", "arc")
```

### Nim Version

$ nim -v
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1ad618d96cab3f518b77c22432600e6b6bf56fae
active boot switches: -d:release

### Current Output

```text
$ nim e --skipUserCfg testmm2.nims
Hint: used config file 'Nim/config/nim.cfg' [Conf]
Hint: used config file 'Nim/config/config.nims' [Conf]
Hint: used config file 'testnim/config.nims' [Conf]
testnim/testmm2.nims(1, 14) template/generic instantiation of `==` from here
Nim/lib/system/comparisons.nim(323, 18) template/generic instantiation of `seqToPtr` from here
Nim/lib/system/comparisons.nim(319, 25) Error: undeclared identifier: 'NimSeqV2'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (5, 5): 'NimMajor'
 (5, 5): 'NimMinor'
 (5, 5): 'NimNode'
```

### Expected Output

```text
No compile error
```

### Additional Information

This error doesn't happen when I remove `switch("mm", "arc")` from `config.nims` and add `--mm:arc` to the command line.
Also doesn't happen when I run same code as .nim file and run `nim c testmm.nim`.

**Comment by ringabout** [comment]
It's not a regression and I can reproduce it in old versions.
