### ISSUE TITLE
Always errors the first time a uint rational is declared

### ISSUE THREAD

**Issue by WyattBlue** [nim-lang/Nim#22227]
### Description

Nim will produce an uncatchable when a uint rational such as `3u//1` is declared. Using `nim secret`, I was able to observe that subsequent calls so work.

```nim
import std/rationals

try:
    3u//1
except CatchableError:  # Never executes (this is a compile time error)
    echo "error"

# Never executes
echo 3u//1  
```

### Nim Version

Nim Compiler Version 1.6.14 [MacOSX: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
>>> import std/rationals
>>> 3u//1

 Error: type mismatch: got <uint>
but expected one of:
func `-`[T](x: T; y: Rational[T]): Rational[T]
  first type mismatch at position: 2
  missing parameter: y
proc `-`(x, y: uint): uint
  first type mismatch at position: 2
  missing parameter: y
proc `-`(x, y: uint64): uint64
  first type mismatch at position: 2
  missing parameter: y
21 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

>>> 3u//1
3/1: Rational[system.uint]
```

### Expected Output

```text
>>> import std/rationals
>>> 3u//1
3/1: Rational[system.uint]
```

### Additional Information

This issue existed on version 1.6.12 too.

**Comment by beef331** [comment]
Nim folds constant logic, as such `3//1` is invoked at compile time, of course it's not catchable.

**Comment by metagn** [comment]
Can fix by wrapping [this part](https://github.com/nim-lang/Nim/blob/dfa0d2569e772d6fc4568796db03f65dc2e94771/lib/pure/rationals.nim#L49-L50) in `when T isnot SomeUnsignedInt:` or something more general like `when compiles(-x.den):`. But then we would support unsigned rationals, for which [Boost says](https://www.boost.org/doc/libs/1_61_0/libs/rational/rational.html#Integer%20Type%20Requirements):

> It is valid for I to be an unsigned type. In that case, the derived rational class will also be unsigned. Underflow behaviour of subtraction, where results would otherwise be negative, is unpredictable in this case. 

The reason it works the second time in the REPL is the Nim compiler suppresses the error in the node which originally gave an error so it doesn't repeat again for `nim check` (by matching a random overload of `-`), so there are no errors "left" in the original code and it compiles.
