### ISSUE TITLE
incremental compilation breaks strformat with enums

### ISSUE THREAD

**Issue by Rellikeht** [nim-lang/Nim#22226]
### Description

This is minimal example of  code that generates compile error when using --incremental:on

```nim
import strformat

type E = enum a

echo fmt"{a}"
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 86ff37fab8656f7acd08fc9c3fa237f9e022dbf4
active boot switches: -d:release

### Current Output

```text
Error: 'newNimNode' can only be used in compile-time context
```

### Expected Output

```text
This should compile
```

### Additional Information

It does that too on stable versions (1.6.x)

**Comment by juancarlospaco** [comment]
!nim c --incremental:on

```nim
import strformat
type E = enum a
echo fmt"{a}"
```

**Comment by Araq** [comment]
Development of IC is on hold until 2.0 has been released. And we know it doesn't work, thanks.
