### ISSUE TITLE
compile a standalone executive on macos

### ISSUE THREAD

**Issue by congvmit** [nim-lang/Nim#22236]
### Description

I just want to compile a standalone executive on macos with this command: `nim c -d:release --os:standalone app.nim`
But this error is raised. Seems that nim does not support macos in this period of time.

```
Error: no implementation for dynlib
```
am I correct?  if no, can you please help me debug?

### Nim Version

1.6.14

### Current Output

```text
nim c -d:release --os:standalone app.nim
Hint: used config file '/opt/homebrew/Cellar/nim/1.6.14/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/homebrew/Cellar/nim/1.6.14/nim/config/config.nims' [Conf]
............................................................................
/opt/homebrew/Cellar/nim/1.6.14/nim/lib/pure/dynlib.nim(195, 10) Error: no implementation for dynlib
```

**Comment by Araq** [comment]
Don't use `--os:standalone` and you'll be fine. It doesn't do what you think it does.
