### ISSUE TITLE
Calling `seq.add` with named argument fails with arc/orc.

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#22243]
### Description

```nim
var a = newSeq[int]()
a.add(y = 1)
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: f47edabc7cd7c3f9db49b9bfb392dc1f5761b40a
active boot switches: -d:release -d:nimUseLinenoise

### Current Output

```text
test.nim(2, 2) Error: type mismatch
Expression: add(a, y = 1)
  [1] a: seq[int]
  [2] y = 1: y: int literal(1)

Expected one of (first mismatch at [position]):
[1] proc add(x: var string; y: char)
[1] proc add(x: var string; y: cstring)
[1] proc add(x: var string; y: string)
[2] proc add[T](x: var seq[T]; value: sink T)
[2] proc add[T](x: var seq[T]; y: openArray[T])
```

### Expected Output

```text
compiles
```

### Additional Information

works with `refc`.

**Comment by ringabout** [comment]
Well, 

```nim
var a = newSeq[int]()
a.add(value = 1)
```

works

**Comment by SolitudeSF** [comment]
Okay, didnt notice the paramter getting renamed in one instance for no reason.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/22244
