### ISSUE TITLE
Cannot instantiate generic proc when used in method call style

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#22247]
### Description

```nim
proc thing[T](x: int): T =
  discard

let x: int = 1
echo thing[int](x) # works
echo x.thing[int]() # doesn't work
```

### Nim Version

9ddd768cce291e5c562cde23baeeefb47aa79c86

### Current Output

```text
Error: cannot instantiate: 'T'
```

### Expected Output

```text
Compiles
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
proc thing[T](x: int): T = discard
let x: int = 1
echo thing[int](x)
echo x.thing[int]()
```

**Comment by metagn** [comment]
https://nim-lang.org/docs/manual.html#procedures-method-call-syntax

> The method call syntax conflicts with explicit generic instantiations: `p[T](x)` cannot be written as `x.p[T]` because `x.p[T]` is always parsed as `(x.p)[T]`.
> 
> See also: [Limitations of the method call syntax](https://nim-lang.org/docs/manual.html#templates-limitations-of-the-method-call-syntax).
> 
> The `[: ]` notation has been designed to mitigate this issue: `x.p[:T]` is rewritten by the parser to `p[T](x)`, `x.p[:T](y)` is rewritten to `p[T](x, y)`. Note that `[: ]` has no AST representation, the rewrite is performed directly in the parsing step.

#21720 for better error message
