### ISSUE TITLE
`browsers.nim`'s bugfix & doc-change review required

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#22250]
## overview
The issue is around `browsers` stdlib in `lib/pure`, aiming to:
-  fix bug that `openDefalutBrowser()` doesn't work correctly in some OSes, e.g. Windows.

<sub> Currently I just have tested it in Linux(Debian) and Windows. Others e.g. Mac OS, remains unknown </sub>

## Nim Version
Nim 1.6.14/devel

## background 
footprint| PR connected|url used|result
:-    | -  | :- | -:
born  |[^1]|http:about:blank|open a default page
change|[^2]|file://`cwd`/http:about:blank[^4]|try opening a non-existing file
try fixing|[^3]|about:blank|confuse Windows and it won't invoke browser

## solution
While it's possible to pile up a lot of code[^5] to invoke a browser to open a blank page, it'll not only hard but unnecessary  
What's more, maybe in other OSes, it can be harder  
After all, what is use to open a blank page?

### recommended solution
To change it to open a default page, which is easy to implement:
1. change the used url to http://
2. update the document

*Is the solution approved?*
I've implemented it

[^1]: https://github.com/nim-lang/Nim/pull/13835
[^2]: https://github.com/nim-lang/Nim/pull/15045
[^3]: https://github.com/nim-lang/Nim/pull/22052

[^4]: It results from being incorrectly passed to `prepare` function and processed
[^5]: The way I find requires to enquiry the Register twice, also making it costly

**Comment by litlighilit** [comment]
To improve,  here are some other proposals:
1. make `openDefaultBrowser(url)` able to accept an empty string, which will open a default page.
2. export a function that will just pass its `url` argument "AS IS" (maybe called `openDefaultBrowserRaw`).  

These are backward compatibility.  
What's more, in this way, the structure of this module can become simpler and better

**Comment by litlighilit** [comment]
The proposals above is implemented

What's more, after refined, this module becomes totally v1-backward compatible,  
meaning it can be pushed straightly into nimv1.6.14

[^1]: Except that it doesn't export `openDefaultBrowserRaw`  
(remained discussed)

**Comment by litlighilit** [comment]
*All in all*  
I can open PR according to which proposal is approved:  
1. fix bug as the first comment: [commits](https://github.com/nim-lang/Nim/compare/devel...litlighilit:Nim:patch-1)
2. also refine as the above comment: [commits](https://github.com/nim-lang/Nim/compare/devel...litlighilit:Nim:litlighilit-patch-1)
3. also export the  function,  called  `openDefaultBrowserRaw` in the above mentioned commit

**Comment by Araq** [comment]
Just remove the `proc openDefaultBrowser*() {.since: (1, 1).}` variant, why was this ever added? Who ever needs that?

**Comment by litlighilit** [comment]
@Araq I used to think it's the best solution (anyway it's easiest), but there are reasons:

Who wants to call `openDefaultBrowser("")` may need it,  
which used to cause an external error.See <https://github.com/nim-lang/Nim/pull/13818#issue-396473868>.  

So `doAssert url.len > 0, "URL must not be empty string"` was added in `openDefaultBrowser(url: string),  
and `openDefaultBrowser()` was added <https://github.com/nim-lang/Nim/pull/13835>

**Comment by litlighilit** [comment]
And if refined as the 2nd mentioned solution <https://github.com/nim-lang/Nim/compare/devel...litlighilit:Nim:litlighilit-patch-1>, 
not only will it keep every exported symbol unchanged
but also it'll remove the dependency of `std/assertions`, which needs importing explicitly in v2
