### ISSUE TITLE
`-d:nimArcIds` broken with `--mm:orc`

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#22273]
### Description

`-d:nimArcIds` broken with `--mm:orc`, its suppose to be for ARC/ORC debugging (?).

But looks like dead code if it does nothing, so in that case maybe can be removed?.

If this is not a bug feel free to close.

### Nim Version

devel

### Current Output

```text
nim-#devel/lib/system/orc.nim(87, 16) Error: undeclared field: 'name' for type system.PNimTypeV2 [type declared in nim-#devel/lib/system.nim(1629, 5)]
```

### Expected Output

```text
compile
```

### Possible Solution

Deprecate `-d:nimArcIds` ?.

### Additional Information

`-d:nimArcDebug` Works.

**Comment by juancarlospaco** [comment]
!nim c --gc:orc -d:nimArcIds

```nim
echo 42
```

**Comment by juancarlospaco** [comment]
Maybe https://github.com/nim-lang/Nim/commit/f11b7debf#diff-c7ae564e61082887ea50f0d58a637cb12fa78261f51aa4eface24ababfeee299R1598-R1599 ? 🤔

**Comment by kovalensky** [comment]
Same for -d:nimOrcLeakDetector
