### ISSUE TITLE
system.=destroy does not accept non-var types

### ISSUE THREAD

**Issue by Pylgos** [nim-lang/Nim#22286]
### Description

The following code cannot be compiled.
```nim
type
  A = object
  B = object
    a: A
  C = object
    b: B

proc `=destroy`(self: A) =
  echo "destroyed"

# Uncomment this out and it will work
# proc `=destroy`(self: B) =
#   `=destroy`(self.a)

proc `=destroy`(self: C) =
  `=destroy`(self.b)

var c = C()
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: f9280090f623d8fddbf753ec50e0ecd21f388d00
active boot switches: -d:release

### Current Output

```text
Error: type mismatch
Expression: `=destroy`(self.b)
  [1] self.b: B

Expected one of (first mismatch at [position]):
[1] proc `=destroy`(self: A)
[1] proc `=destroy`(self: C)
[1] proc `=destroy`(x: string)
[1] proc `=destroy`[T](x: ref T)
[1] proc `=destroy`[T](x: seq[T])
[1] proc `=destroy`[T](x: var T)
```

### Expected Output

```text
destroyed
```

**Comment by bung87** [comment]
so the current implementation doesn't match the manual.

> A =destroy hook is allowed to have a parameter of a var T or T type. Taking a var T type is deprecated. The prototype of this hook for a type T needs to be:
> 
> proc `=destroy`(x: T)

**Comment by litlighilit** [comment]
> so the current implementation doesn't match the manual.

@bung87 
But ```
proc `=destroy`(self: A)```
is really allowed and works.

And the reason is simple.  
For an object (eg. B), its ```proc `=destroy`(self: B)``` is not defined by default[^1], meaning you have to explicitly define one.

[^1]: Now, `system` has ```proc `=destroy`[T: object](self: var T)``` pre-defined while no ```proc `=destroy`[T: object](self: var T)``` pre-exists

**Comment by drkameleon** [comment]
I've been having related issues as well.

This: https://github.com/arturo-lang/arturo/blob/master/src/helpers/bignums.nim#L93

is triggering this type of warnings:

> Warning: A custom '=destroy' hook which takes a 'var T' parameter is deprecated; it should take a 'T' parameter [Deprecated]

**Comment by bung87** [comment]
> > so the current implementation doesn't match the manual.
> 
> @bung87 But `` proc `=destroy`(self: A) `` is really allowed and works.
> 
> And just some edge cases like the example above don't work correctly

yeah, it allow user defined proc `=destroy` for non-var type, but nim builtins don't have proc `=destroy`[T](x: T) like the error shows, I think the manual is bit confusing, or nim have't yet implemented it.

**Comment by litlighilit** [comment]
> nim haven't yet implemented it.

So is it,  exactly.  
But what if it's scheduled?  

A pre-defined `=destroy` for non-var object  has never exists ever, afterall.

**Comment by litlighilit** [comment]
@drkameleon it is warning that when it comes to `=destroy` object, nimv2 is going a different way from v1
