### ISSUE TITLE
`DWORD` in std/winlean inconsistent with MS's definition.

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#22298]
According to <https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types>,  
`DWORD` is "A 32-bit unsigned integer".
<https://github.com/nim-lang/Nim/blob/c1a82aa5c5ab68dfc2ab6f09779d9ab9bbf3758f/lib/windows/winlean.nim#L36>  
Why not `uint32`
Does this difference matter?

**Comment by demotomohiro** [comment]
Dupulicate of : https://github.com/nim-lang/Nim/issues/12327

**Comment by ringabout** [comment]
Duplicate of https://github.com/nim-lang/Nim/issues/12327
