### ISSUE TITLE
Name clash resolution regression when renaming imports

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#22296]
#### `a/utils.nim`

```nim
proc foo*() = echo "foo A"
```

#### `b/utils.nim`

```nim
proc foo*() = echo "foo B"
```

#### `main.nim`

```nim
from a/utils as utilsA import foo
import b/utils

utilsA.foo()
utils.foo()
```

## Results

Run with `nim r main`.

### Nim 1.6.12

Works as expected.

```
foo A
foo B
```

### Nim 1.6.14

I think this is a regression as I've explicitly renamed `a/utils` to `utilsA`, so there should be no ambiguity. I haven't seen it being mentioned in the release notes that the import rules have changed.

```
/Users/jnovak/jn/nim-test/main.nim(5, 6) Error: ambiguous identifier: 'utils'
```

I can make it work with this workaround, which is not horrible, but I see no point in dropping the 1.6.12 behaviour.

```nim
from a/utils as utilsA import foo
import b/utils as utilsB

utilsA.foo()
utilsB.foo()
```

### Nim Version

```
Nim Compiler Version 1.6.14 [MacOSX: amd64]
Compiled at 2023-07-19
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by metagn** [comment]
Should work in devel after #22211 which could be backported

**Comment by johnnovak** [comment]
> Should work in devel after #22211 which could be backported

Great, thanks!

**Comment by metagn** [comment]
Was backported: https://github.com/nim-lang/Nim/commit/01ef1e15008b27bf49ab7b0548c5e902c106a5a2
