### ISSUE TITLE
`defer` can introduce new symbols and cause internal errors

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#22309]
#### Case 1
```nim
block:
  defer:
    let a = 42
  echo a
```
#### Case 2
```nim
proc lol() =
  defer:
    let a = 42
  echo a

lol()
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-21
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2f817ee5b45db3a7152b87e6921188afd65486cc
active boot switches: -d:release

#### Case 1
```
42
```
#### Case 2
```
Error: internal error: expr: var not init a_520093698
```

### Expected Output

In both cases I'd expect a compiler error that `a` is not defined.

### Additional Information

I'm not sure if it is intended that `a` is in scope here. If it is, that should definitely be documented in the manual, as that's quite unintuitive imo. In principle, the `defer` block is only evaluated at the end of the scope, so why should symbol definitions be treated differently?

**Comment by Araq** [comment]
`defer` does not open a scope, currently. I suppose it should.
