### ISSUE TITLE
Default initialization does not work with Object Variants and parseEnum

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#22301]
### Description

The code below does not work for the parseEnum case

```nim
import strutils

type
  Enum = enum
    A
  Object = object
    case a: Enum
    of A:
      integer = 200

echo Object(a: A)
echo Object(a: parseEnum[Enum]("A"))
```

### Nim Version

```
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-19
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c1a82aa5c5ab68dfc2ab6f09779d9ab9bbf3758f
active boot switches: -d:release
```

### Current Output

```text
(a: A, integer: 200)
(a: A, integer: 0)
```

### Expected Output

```text
(a: A, integer: 200)
(a: A, integer: 200)
```

**Comment by metagn** [comment]
Minimized:

```nim
type
  Enum = enum A
  Object = object
    case a: Enum
    of A:
      integer = 200

let x = A
echo Object(a: x)
```

**Comment by ringabout** [comment]
Yeah, it should probably be rejected (or a warning that the fields of runtime selection won't be initialized to its default values) since default values cannot handle object invariants runtime selection because the selector needs a value which can be evaluated at the compile time.

**Comment by nc-x** [comment]
I know this feature was implemented only for default values which can be evaluated at compile time but especially for cases like this, these restrictions would remove lots of usecases and we would be back in pre-historic times. Can we revisit this decision and think about supporting runtime values?

> Yeah, it should probably be rejected (or a warning that the fields of runtime selection won't be initialized to its default values) 

how is this going to work anyways? if you allow default values which are only available at compile time, then you would be basically asking people to not use the runtime features like parseenum at all or complicate the code so that we are manually calling a constructor function for dynamic cases and let default values work otherwise.

**Comment by ringabout** [comment]
It might be relaxed if there is a new RFC for runtime default values. It's a new feature, which means it is experimental and improvements will be made gradually. But for 2.0, it has been decided that only compile-time values are supported, which means the changes will stick with the rule. We obviously cannot afford big changes before imminent 2.0 release.

**Comment by nc-x** [comment]
I am fine with not having support for it as of now, but my point is that unless with support it properly we should not allow default values at all for object variants, i.e. - 
- **[No]** Allow defining variants with default values, people will use it at lots of places, later they have a usecase for runtime values, they find it is not supported and they now have to rework their code
- **[Yes]** Don't allow defining variants with default values at all because the discriminator is not guaranteed to be known at compile time and we don't support runtime values yet.

And i say this because for me personally the current behaviour is a "bug" and not a "working as designed but missing a warning or an rfc to support it" so unless we are actually fixing the bug, we should remove the unreleased misfeature.

**Comment by metagn** [comment]
There is a broad workaround, that does basically what the compiler would have to do.

```nim
type
  Enum = enum A, B
  Object = object
    case a: Enum
    of A:
      integer = 200
    of B:
      float = 1.23

let x = A
let obj =
  case x
  of A: Object(a: A)
  of B: Object(a: B)
echo obj
```

For it to work normally, the compiler would have to generate something like:

```nim
echo Object(a: x)
# =>
echo (block:
  var objTmp = Object(a: x)
  case objTmp.a
  of A: objTmp.integer = 200
  of B: objTmp.float = 1.23
  objTmp)
```

which, while simple, has `case` overhead the user is not privy to.
