### ISSUE TITLE
Regression, Nim 2: Ref Object suddenly nil in thread after "adds T destructor for refs" PR was merged

### ISSUE THREAD

**Issue by turbo** [nim-lang/Nim#22319]
### Description

I'm still working on a minimal example, in the meantime, here's all the info I have.

After pulling in latest changes in the `version-2-0` branch, my webservice experiences non-deterministic crashes because database handles passed to threads suddenly disappear.

This regression does not present in https://github.com/nim-lang/Nim/commit/43a3de9077955031e55691ebb84ee958f6aa260e, but starts with https://github.com/nim-lang/Nim/commit/4546f5dfe539ff4f37a5100bdfedaf4867293f3a, which comes from https://github.com/nim-lang/Nim/pull/22147

The server uses https://github.com/guzba/mummy and on startup allocates a [waterpark Pool](https://github.com/guzba/waterpark/blob/master/src/waterpark.nim) with SQLite connections. See the link for the implementation of the `Pool` type. Here's the concrete implementation of the SQLite pool:

<details>
  <summary>Pool implementation</summary>

```nim
proc close*(pool: SqlitePool) =
  ## Closes the database connections in the pool then deallocates the pool.
  ## All connections should be returned to the pool before it is closed.
  let entries = toSeq(pool.pool.items)
  for entry in entries:
    entry.close()
    pool.pool.delete(entry)
  pool.pool.close()

proc newSqlitePool*(
  size: int, 
  database: string, 
  mode: DbMode, 
  mmapSize = 0
): SqlitePool =
  ## Creates a new thead-safe pool of SQLite database connections.
  if size <= 0:
    raise newException(SqliteError, "Invalid pool size")
  result.pool = newPool[DbConn]()
  try:
    for _ in 0 ..< size:
      let c = openDatabase(database, mode)
      if mode == dbReadWrite:
        c.exec("PRAGMA journal_mode=WAL;") # writers don't block readers
      c.exec("PRAGMA foreign_keys=ON;") # tiny_sqlite default
      
      # up to 1TB, 0 disables
      let mmapConfirm = c.value(
        &"PRAGMA mmap_size={mmapSize};"
      ).get.intVal

      assert mmapConfirm == mmapSize,
        &"mmap config failed to allocate {mmapSize}, got {mmapConfirm}"

      result.pool.recycle(c)
  except SqliteError as e:
    try:
      result.close()
    except CatchableError:
      discard
    raise e

proc borrow*(pool: SqlitePool): DbConn {.inline, raises: [], gcsafe.} =
  pool.pool.borrow()

proc recycle*(pool: SqlitePool, conn: DbConn) {.inline, raises: [], gcsafe.} =
  pool.pool.recycle(conn)

template withConnnection*(pool: SqlitePool, conn, body) =
  block:
    let conn = pool.borrow()
    try:
      body
    finally:
      pool.recycle(conn)

proc close*(client: SqliteClient) =
  client.readPool.close()
  client.writePool.close()
```
</details>

This pools a collection of `DbConn` types, which are defined as:

```nim
type
  Sqlite3* = ptr object
  DbConnImpl = ref object
    handle: Sqlite3 ## The underlying SQLite3 handle
    cache: StmtCache # not important

  DbConn = distinct DbConnImpl ## Encapsulates a database connection.
```

On startup the root thread spawns another worker thread (unrelated to mummy) and passes the `SqlitePool` to it via thread arguments to `createThread`. In the worker thread, the pools (one for readers, one for writers) is used.

Before the regression, this worked fine. After it, at a random point in time, the worker thread will now throw an exception, because this assertion gets violated:

```nim
template assertCanUseDb(db: DbConn) =
  doAssert (not DbConnImpl(db).isNil) and (not db.handle.isNil), "Database is closed"
```

It's important to note that the db hasn't been closed (there wasn't an error and all file handles are still open). It's the DbConn implementation that is "suddenly" nil and crashes the program during the assertion.

The condition `db.handle.isNil` is the one that fails. This is initialized from a direct call into the SQLite library:

```nim
proc open*(filename: cstring, db: out Sqlite3): cint
    {.cdecl, header: "sqlite3.h", importc: "sqlite3_open".}
```

### Nim Version

See commit hashes above. Regression still exists with the (today) latest commit on the `version-2-0` branch, but starts with https://github.com/nim-lang/Nim/commit/4546f5dfe539ff4f37a5100bdfedaf4867293f3a

**Comment by turbo** [comment]
Can no longer repo with Nim 2.0 stable

**Comment by Araq** [comment]
Somewhat related: Nim now supports `mm:atomicArc` which allows for more sharing between threads, if you know what you're doing.
