### ISSUE TITLE
`getImpl` of `range` type contains default value

### ISSUE THREAD

**Issue by etan-status** [nim-lang/Nim#22324]
### Description

When querying `getImpl` on a range type, in Nim 2.0, a default value is included despite the actual source code not containing one.

```nim
import std/macros

type X = object
  foo: range[1 .. 3]

macro bar(): untyped =
  let x = typeof(X).getType[1].getImpl
  echo repr(x)

bar()
```

### Nim Version

Nim Compiler Version 2.0.0 [MacOSX: amd64]
Compiled at 2023-07-24
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1d7af15d1dc031860679555b5d48b332e9bf8a71
active boot switches: -d:release

### Current Output

```text
X = object
  foo: range[1 .. 3] = 1
```

### Expected Output

```text
X = object
  foo: range[1 .. 3]
```

### Possible Solution

Nim 1.6 has expected output, it is only Nim 2.0 that has the extra `= 1` in the output.

### Additional Information

Same problem for `Natural` and other types building on top of `range`.

**Comment by ringabout** [comment]
Yeah, I made `nimPreviewRangeDefault` default, to solve problems caused by range within objects. I will make it opt-in.

As a workaround, use `-u:nimPreviewRangeDefault`.
