### ISSUE TITLE
`create Lock` error, importc regression

### ISSUE THREAD

**Issue by Gruruya** [nim-lang/Nim#22344]
### Description

Regression found on [easy_sqlite](https://github.com/codehz/easy_sqlite3/actions/runs/5698389451/job/15446205737), exclusively errors on 1.6.14 and 1.6.15, not 1.6.12 or devel.

Minimal repro:
```nim
import locks
var a = create Lock
```

`sizeof(Lock)` does compile however.

### Nim Version

1.6.14-1.6.15

### Current Output

```text
/reproduce.nim(2, 16) template/generic instantiation of `create` from here
/lib/system/memalloc.nim(148, 18) Error: 'sizeof' requires '.importc' types to be '.completeStruct'
```

### Expected Output

```text
/reproduce.nim(2, 5) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
```

**Comment by ringabout** [comment]
!nim eval
```nim
import locks
var a = create Lock
```

**Comment by ringabout** [comment]
!nim c
```nim
import locks
var a = create Lock
```

**Comment by ringabout** [comment]
!nim c --gc:arc
```nim
import locks
var a = create Lock
```

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/pull/20518 needs to be backported
