### ISSUE TITLE
Debugging/stepping is broken in 2.0.0 and 2.1.1

### ISSUE THREAD

**Issue by DiThi** [nim-lang/Nim#22366]
### Description

Compile this program with `--debugger:native`

    type
        Node[T] = ref object
            value: T
            next: Node[T]
    
        LinkedList*[T] = object
            first: Node[T]
    
    proc unshift*[T](list: var LinkedList[T], val: T) =
        var n = new Node[T]
        n.value = val
        n.next = list.first
        list.first = n
    
    proc shift*[T](list: var LinkedList[T]): T =
        var n = list.first
        list.first = n.next
        return n.value
    
    var list = LinkedList[int]()
    list.unshift(7)               # Put a breakpoint on this line
    echo list.shift() == 7

Then:

- Try to debug the application adding a breakpoint in the line marked above.
- Try stepping in.
- Or try stepping over, then in.

### Nim Version

Failing with all these versions:

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-02
git hash: da368885da8850c0c87e6b9dcff64393985aff27

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-06-30
git hash: 210b10dd0d47c8c79b686a69eb8646df869cf207

It works correctly with 1.6.14

### Current Output

```text
When stepping in unshift(7) it's stepping into an unrelated function (probably part of the previous line), then advancing to the next line.

When stepping over and then stepping in shift(), it instead steps into unshift().
```

### Expected Output

```text
It should step into the actual functions.
```

### Possible Solution

Possibly fixing an off-by-one error.

### Additional Information

It works correctly with 1.6.14, HOWEVER, it seems there's another off-by-one error (present in all tested versions):

![image](https://github.com/nim-lang/Nim/assets/1127198/728cdd2c-5c70-4b17-b657-eff4f2da1662)

Note that the cursor points to the second column. I don't know if it's related.

Using CodeLLDB v1.9.2 in Code-OSS (VS Code) which ships its own version of lldb (16.0.0-custom).

**Comment by DiThi** [comment]
Edited to add what debugger I'm using. To use it: Click "run and debug", it asks you to create a launch.json, click OK then replace `<executable file>` by the generated executable file.

**Comment by juancarlospaco** [comment]
VS Code plugin is not maintained in this repo.

**Comment by DiThi** [comment]
> VS Code plugin is not maintained in this repo.

I just mentioned it for completeness sake, but since it works correctly with nim 1.6.14 I assumed it was fault of the compiler. In fact I just tried with nim-gdb in the command line and obtained **exactly the same result**.

I don't know if the cursor on the second column is related at all, but I mentioned it just in case. Gdb doesn't seem to have a concept of columns though.

**Comment by DiThi** [comment]
I have a question for linux nim developers... does **nobody** use debuggers? I expected this bug to get a little more attention to be honest.

This still happens even for a much simpler example:

    proc hello() =
        echo "hello"
    
    proc world() =
        echo "world"
    
    hello()
    world()

Break on like 7 (`hello()`), then step into (`s` in gdb) and it will instead go to `world()`. Only after being in that line stepping in does step into... `proc hello`.

Just in case I compiled with `--debugger=gdb` instead of `--debugger=native` with the same result. And just in case I also reproduced the same problem in windows. Latest devel (2.1.1) build in both cases.

I'm arguing with someone that says that debugging is a PITA if you can get it to work. For me it was really easy to get a debugger running. And I would tell them that, if we were in the version 1.6.14 where it worked. But as it is, I can't.

I will try to compile the compiler and get my hands dirty to see if I can figure it out, but it puzzles me that nobody else had this issue.

**Comment by juancarlospaco** [comment]
I use a macro to debug, but I agree it should be fixed.

**Comment by DiThi** [comment]
I found the offending commit through bisection: 91abf35442d6f0861db659c5332b481bd24dfedb

Skimming the code it seems it overhauls some of the code generation, and I'm sure there's a off-by-one error there with line numbers, because some compilers consider the first line 0, and for some others it's 1 (all editors start at 1, after all). I'll try to figure out which is which.

**Comment by DiThi** [comment]
I've found the problem, it was not exactly an off-by-one error: the old generator generated duplicate line directives and this commit assumed removing the duplicates wouldn't change the result, when actually it's the second "duplicate" the one that is being used by the C compiler, not the first. The solution should be to put the line directives after `nimln_`/`nimlf_` and before the actual statement. If I understand correctly, the information set in `nimln_` is only used when there's an exception, but those are only ever checked after the statement and before another `nimln_`. Tomorrow I'll see if I can make that change.
