### ISSUE TITLE
`rand(bool)` always returns `false`

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#22360]
### Description

```nim
import std/random

randomize()

for _ in 1..10:
  echo rand(bool)
```
outputs
```
false
false
...
```

### Nim Version

1.7.1 a52918a99456dc705e6daed7febb0d0b06803fcd

### Possible Solution

fix a52918a99456dc705e6daed7febb0d0b06803fcd

### Additional Information

the js backend is affected too.

**Comment by juancarlospaco** [comment]
`1.rand.bool` ? 🤔
