### ISSUE TITLE
memory leak with nested Exceptions

### ISSUE THREAD

**Issue by inv2004** [nim-lang/Nim#22398]
### Description

```nim
while true:
  try:
    try:
      raise newException(ValueError, "")
    except CatchableError:
      raise newException(ValueError, "") # or raise getCurrentException(), just raise works ok
  except ValueError:
    discard
  echo getOccupiedMem()
```

`--mm:arc` or `--mm:refc` - does not matter

### Nim Version

- 2.0.0
- 1.6.14

### Current Output

```text
increased memory usage (visible in top too)
```

### Expected Output

```text
constant memory usage
```

### Additional Information

It was suggested to check with `-d:useMalloc`. It made the `getOccupiedMem` to 0 (like it is ok), but top still shows growing rss

**Comment by inv2004** [comment]
It was suggested to check with `-d:useMalloc`. It made getOccupiedMem to 0 (like it is ok), but top still shows growing rss

**Comment by ringabout** [comment]
The leak is caused a chain formed by the exceptions, which might indict that some logics related to `popCurrentException` are wrong. I'm gonna break the chain somehow.

**Comment by ringabout** [comment]
Related to https://github.com/nim-lang/Nim/issues/18070
