### ISSUE TITLE
distinctBase matching regression

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22417]
### Description

```nim
import std/typetraits

type A = distinct int

var v: A

distinctBase(v) = 42

echo distinctBase(v)

distinctBase v = 42

```

### Nim Version

works in 1.6, fails in 2.0

**Comment by ringabout** [comment]
!nim c
```nim
import std/typetraits

type A = int

var v: A

distinctBase v = 42
```

**Comment by arnetheduck** [comment]
a more meaningful version, ie `type A = distinct int` probably works all the way back to 1.2...

**Comment by metagn** [comment]
Why was the issue edited to the `distinct int` version if it works? @bung87 

`distinctBase v = 42` fails because parsing rules were changed in 2.0 and it parses as `distinctBase(v = 42)`.

**Comment by bung87** [comment]
it doesn't work, the problem here is not related to the type definition, the matched `distinctBase`  is template, `v = 42` treat as the template first argument. the result is 
```
Error: type mismatch: got <v: int literal(42)>
but expected one of:
proc distinctBase(T: typedesc; recursive: static bool = true): typedesc
  first type mismatch at position: 1
  unknown named parameter: v
template distinctBase[T](a: T; recursive: static bool = true): untyped
  first type mismatch at position: 1
  unknown named parameter: v

expression: distinctBase v = 42
```

**Comment by metagn** [comment]
Yes. That is new parser behavior in 2.0.

From the [changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_2_0_0_details.md):

> `foo a = b` now means `foo(a = b)` rather than `foo(a) = b`. This is consistent with the existing behavior of `foo a, b = c` meaning `foo(a, b = c)`. This decision was made with the assumption that the old syntax was used rarely; if your code used the old syntax, please be aware of this change.

Maybe the "porting guide" was not comprehensive enough.

**Comment by bung87** [comment]
so this is expected behavior, not a issue now.

**Comment by metagn** [comment]
@arnetheduck Any further problems?

**Comment by arnetheduck** [comment]
weird but ok, whatever. I think the most accurate summary of the change is "command syntax has many weird quirks, avoid it" - ie when you see `foo a = b` on its own, I don't think many people would think it'll bind `=` more tightly because an assignment is typically not thought of as an expression, even if in fact it can be one. 

consider:

```
proc f(v: int): int =
  echo v
  var x: int
  x = 44

var v: int
echo f(v = 42)
```

x = 44 in the above case is _not_ an expression: the function will return 0 which means that assignment only "sometimes" exhibits expression properties - if this change was made, the above should reasonably also see expression treatment and turn into a return value for `f`.

Closing for now, this bug is probably not the right place for this discussion, though it's certainly an oddball change that broke compat.

**Comment by metagn** [comment]
Read https://github.com/nim-lang/RFCs/issues/442 for reasoning
