### ISSUE TITLE
macro pragmas doesnt seem to work on params

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#22410]
### Description

Im not sure if this ever worked or if there is another way of specifying it, but I cant get this to work:

```nim
import std/macros

macro constcpp(body: untyped): untyped = 
  body

proc test(param {.constcpp.}: bool) = discard
```

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: arm64]
Compiled at 2023-08-06
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8b061e6605ea2d1be2795023ee4fdbc9b5cabf6d

### Current Output

```text
`Error: invalid pragma: constcpp`
```

### Expected Output

```text
Compiles ok
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
import std/macros
macro constcpp(body: untyped): untyped = body
proc test(param {.constcpp.}: bool) = discard
```

**Comment by juancarlospaco** [comment]
It never worked it seems... 🤔

**Comment by jmgomez** [comment]
ouch, maybe is there another way to specify it that we are not seeing?

**Comment by metagn** [comment]
This was never a feature, it would need an RFC (would the macro take an `IdentDefs` with just the 1 parameter? would it output an `IdentDefs`? how would it know it's a routine parameter and not another kind of `IdentDefs`). You can maybe use something like

```nim
proc test(param: bool) {.constcpp: [param].} = discard
```

[outparams](https://nim-lang.org/docs/outparams.html) in the standard library does something like this.

**Comment by jmgomez** [comment]
> This was never a feature

Thanks for confirming, I suspected it but wasnt sure. 

> it would need an RFC

Yes, I will prepare it more down the road when I also have the time to attempt to implement it

> You can maybe use something like

Not sure if I like that as a `proc` too can be made `const` and it wouldnt too natural.
