### ISSUE TITLE
`hash(openArray)` fails to use full `Hash` type range

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22426]
### Description

`Hash` is a 64-bit type on 64-bit systems, yet the hash for arrays uses only half that range:

https://github.com/nim-lang/Nim/blob/989da75b84e15a6d585e8b03d2bcd0c42a90c2fb/lib/pure/hashes.nim#L306

This unnecessarily makes the hash function weaker than it has to be, specially when combined with other hash values.

While we're here, one has to wonder if `Hash` could be an `uint` as would make sense - probably not, for backwards compat.

### Nim Version

devel

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23735
