### ISSUE TITLE
Strange openArray size

### ISSUE THREAD

**Issue by ASVIEST** [nim-lang/Nim#22427]
### Description

```nim
proc getSize(x: openArray[int]): int =
  x.sizeof()

echo getSize([3, 14, 15]) == sizeof([3, 14, 15]) # -> false
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-09
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d136af012298b58be5abfb5e095cabd158feeb2e
active boot switches: -d:release

### Current Output

```text
false
```

### Expected Output

```text
true
```

**Comment by juancarlospaco** [comment]
!nim c --gc:arc

```nim
proc f(x: openArray[int]): int = sizeof(x)
doAssert f([0, 1]) == sizeof([0, 1])
doAssert f([0]) == sizeof([0])
```

**Comment by juancarlospaco** [comment]
It never really worked properly it seems.
AFAIK `openArray` is kinda like sugar for a `[pointer, length]`.

**Comment by beef331** [comment]
This is `sizeof(openArray[int])` vs `sizeof(array[3, int])` of course they're not the same.

```nim
proc getSize(oa: openArray[int]): int = sizeof(oa)
echo getSize([3, 14, 15]), " ", sizeof([3, 14, 15].toOpenArray(0, 3))
```
