### ISSUE TITLE
Default GC memory leak vs. Boehm

### ISSUE THREAD

**Issue by onionhammer** [nim-lang/Nim#2242]
The websockets library is still experiencing some GC issues

Steps to reproduce:
```
git clone https://github.com/onionhammer/onion-nimrod.git
cd onion-nimrod/websockets/
open client/index.html
nim c -r -d:release websocketmem.nim
```

Refresh the index.html (using chrome or another browser which supports websockets) and it the terminal should start displaying the occupied memory.

As you can see, the memory keeps going up, and often times it crashes in the GC (sigsegv). However, using --gc:boehm you can see the GC is able to keep up

**Comment by Araq** [comment]
What OS? What happens with ``--gc:markAndSweep``?

**Comment by oderwat** [comment]
As he writes `open client/index.html` it must be macosx. I can reproduce the problem too:

```
Running websocket test
98304
102400
102400
114688
114688
139264
message: Client: Message received: hello world!
139264
client left, remaining: 0
139264
147456
147456
147456
.
.
.
.

message: Client: Message received: hello world!
180224
client left, remaining: 0
180224
188416
188416
192512
message: Client: Message received: hello world!
192512
client left, remaining: 0
192512
200704
200704
200704
message: Client: Message received: hello world!
200704
client left, remaining: 0
200704
212992
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```

Compiling it with `--gc=boehm` lets it run indefinitely with "fast pulsating" memory allocation numbers.
Compiling it with `--gc=markAndSweep` lets it run indefinitely with "slow pulsating" much higher memory allocation numbers.

**Comment by elbow-jason** [comment]
I had similar results as @oderwat. Running Linux Mint 17 Rebecca x86_64.

**Comment by onionhammer** [comment]
Oderwat is correct, I tested this on OS X

**Comment by Araq** [comment]
ws.buffer = cstring(newString(4000)) # unsafe

**Comment by onionhammer** [comment]
Note thats only done during initialization at the start of the program

**Comment by onionhammer** [comment]
It seems like commenting out the 'ws.send' in the onConnected callback fixes the leak; so it must be in there -- i'm continuing to investigate :)

**Comment by Araq** [comment]
Cannot reproduce on Linux 64 with devel.

**Comment by onionhammer** [comment]
Araq reproduced agai on os x

```
Traceback (most recent call last)
websocketmem.nim(324)    websocketmem
asyncio.nim(649)         poll
asyncio.nim(229)         asyncSockHandleRead
websocketmem.nim(263)    :anonymous
websocketmem.nim(247)    handleAsyncUpgrade
websocket_utils.nim(40)  parseHTTPHeader
strtabs.nim(145)         []=
strtabs.nim(128)         rawInsert
gc.nim(486)              newObjRC1
gc.nim(1068)             collectCT
gc.nim(1035)             collectCTBody
gc.nim(757)              collectCycles
gc.nim(629)              markRoots
gc.nim(597)              markGray
gc.nim(369)              forAllChildren
gc.nim(736)              nimGCvisit
gc.nim(715)              doOperation
gc.nim(597)              markGray
gc.nim(367)              forAllChildren
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```

**Comment by Araq** [comment]
Cannot reproduce on Mac OS X under new GC.
