### ISSUE TITLE
[docs] broken link to sha-2 in "see also" section for sha-1

### ISSUE THREAD

**Issue by MatrixManAtYrService** [nim-lang/Nim#22441]
### Description

This page has some broken links: https://nim-lang.org/docs/sha1.html The pages (and the modules?) for sha2 and sha3 don't exist.

Sorry if this is the wrong place.  I had hoped to contribute a PR but I couldn't find the actual content I wanted to correct in this repo or in the website repo.  If it's in the contribution guidelines, I overlooked it. (maybe the page itself could have a link at the bottom?}

### Nim Version

n/a

**Comment by ringabout** [comment]
You might add them here https://github.com/nim-lang/Nim/blob/devel/tools/kochdocs.nim#L169-L169 like other modules  under checksums. Use `koch doc` locally to test whether it is right.
