### ISSUE TITLE
connect fails with IPv6 only hosts (because it defaults to AF_INET and not AF_UNSPEC)

### ISSUE THREAD

**Issue by mildred** [nim-lang/Nim#22442]
### Description

When using connect with default parameters and an IPv6 only host, it fails to connect because it resolves by default only IPv4 addresses

```nim
import asyncdispatch
import asyncnet
import net

proc main() =
  var socket: Socket = newSocket()
  socket.connect("ipv6.google.com", Port(80))
  socket.send("GET / HTTP/1.0\r\n\r\n")

proc main_async() {.async.} =
  var socket: AsyncSocket = newAsyncSocket()
  await socket.connect("ipv6.google.com", Port(80))
  socket.send("GET / HTTP/1.0\r\n\r\n")

main()
asyncCheck main_async()
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
/home/mildred/Projets/sqlemail.nim/testipv6.nim(15) testipv6
/home/mildred/Projets/sqlemail.nim/testipv6.nim(7) main
/home/mildred/.choosenim/toolchains/nim-2.0.0/lib/pure/net.nim(2055) connect
/home/mildred/.choosenim/toolchains/nim-2.0.0/lib/pure/nativesockets.nim(311) getAddrInfo
/home/mildred/.choosenim/toolchains/nim-2.0.0/lib/std/oserrors.nim(92) raiseOSError
Error: unhandled exception: Additional info: Name or service not known [OSError]
Error: execution of an external program failed: '/home/mildred/Projets/sqlemail.nim/testipv6'
```

### Expected Output

```text
It should connect
```

### Possible Solution

Use AF_UNSPEC sockets by default

**Comment by juancarlospaco** [comment]
!nim c

```nim
import asyncdispatch, net
var s: Socket = newSocket()
s.connect("ipv6.google.com", Port(80))
s.send("GET / HTTP/1.0\r\n\r\n")
s.close()
```

**Comment by mildred** [comment]
From [the forum](https://forum.nim-lang.org/t/10397):

> The correct way of doing things is to:
>
> - run getaddrinfo with AF_UNSPEC
> - create the socket after that using the domain (AF_INET or AF_INET6) returned by getaddrinfo
>
> The problem is that the Nim standard library does things in the wrong order, it first creates the socket (and you have to choose AF_INET or AF_INET6 before resolving the DNS and knowing if it will be IPv4 or IPv6). When resolving the address, if the address type does not match it will not work.

The problem is that when using `newSocket` and then `connect` (as many packages do) create IPv4 only apps. One should use `dial` instead. The standard library should make it easier to use dial and should make it difficult to use `newSocket`... In the meantime, I had the issue with the SMTP package and I believe this might not be a stdlib issue.

**Comment by mildred** [comment]
feel free to close
