### ISSUE TITLE
C codegen error when object type contains a ref and proc takes a var param

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#2245]
The Nim compiler generates incorrect C code when:
1. an object type `Foo` contains a ref, and
2. a proc takes a variable `f` of type `Foo` as a var param, and then
3. the proc returns a result that is assigned back to that same variable `f`.

The codegen error occurs because the Nim compiler uses `memset` to zero out the value of the variable `f` that is going to be used as the lvalue of the assignment, BUT this occurs before `f` is supplied as the argument to the proc.

The following minimal test case code demonstrates this problem.  Change the value of `const hasRefField` from `true` to `false` to observe that the problem doesn't occur when object type `Foo` doesn't contain a ref.

```Python
const hasRefField = true

type Foo = object
  m*: int
  when hasRefField:
      r: ref int


proc initFoo*(m1: int): Foo =
  result.m = m1
  when hasRefField:
      new(result.r)
      result.r[] = 999


proc inc*(f: var Foo, delta: int) =
  f.m += delta


proc nonVarParam*(f: Foo, delta: int): Foo =
  echo("inside nonVarParam: f.m = ", $f.m)
  result = f
  echo("inside nonVarParam 2: f.m = ", $f.m)
  result.inc(delta)


proc varParam*(f: var Foo, delta: int): Foo =
  echo("inside varParam: f.m = ", $f.m)
  result = f
  echo("inside varParam 2: f.m = ", $f.m)
  result.inc(delta)


proc testBug() =
  var f = initFoo(5)
  echo("before nonVarParam: f.m = ", $f.m)
  f = f.nonVarParam(13)
  echo("after nonVarParam: f.m = ", $f.m)

  echo("\nbefore varParam: f.m = ", $f.m)
  f = f.varParam(44)
  echo("after varParam: f.m = ", $f.m)


testBug()
```

When `const hasRefField` is true, the output is this:
```
before nonVarParam: f.m = 5
inside nonVarParam: f.m = 5
inside nonVarParam 2: f.m = 5
after nonVarParam: f.m = 18

before varParam: f.m = 18
inside varParam: f.m = 0
inside varParam 2: f.m = 0
after varParam: f.m = 44
```

Observe the printed output: `inside varParam: f.m = 0`

When `const hasRefField` is false, the output is this:
```
before nonVarParam: f.m = 5
inside nonVarParam: f.m = 5
inside nonVarParam 2: f.m = 5
after nonVarParam: f.m = 18

before varParam: f.m = 18
inside varParam: f.m = 18
inside varParam 2: f.m = 18
after varParam: f.m = 62
```

In the former case (the broken case), the generated C code looks like this:
```C
        chckNil((void*)(&f));
        memset((void*)(&f), 0, sizeof(f));
        varparam_88256((&f), 44, (&f));
```

but in the latter case (the correct case), the generated C code looks like this:
```C
        f = varparam_88247((&f), 44);
```

**Comment by Araq** [comment]
So don't alias. ;-)

**Comment by jboy** [comment]
Eh, it's an iterator idiom.  I have iterators over 2-D arrays, and the code above is a simplified version of this sort of thing:
``iter = iter + [row_delta, col_delta]``

So the code is idiomatic, and not as arbitrarily strange as it may initially appear.

**Comment by kirbyfan64** [comment]
I believe this was fixed by https://github.com/nim-lang/Nim/commit/fa177076842d5a5e7900469d6b5ec0e2e432d17c?

**Comment by dom96** [comment]
Looks like it. Tested with devel and it appears to give correct output.

**Comment by jboy** [comment]
Great, thanks.  It now gives correct output for me too.
