### ISSUE TITLE
Resetting object field with {.union.} type with string field segfaults

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#22459]
### Description

```nim
type
  T {.union.} = object
    x: string
    y: (int, int)
  U = object
    t: T

var u = U()
u.t = T(y: (1, 2))
reset(u.t)
```

### Nim Version

2.0

### Current Output

```text
lib/system.nim(942) reset
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
success
```

### Additional Information

Happens on both refc and arc

In the C output, `reset(u.t)` calls a destructor on `u.t.x` which tries to deallocate the invalid memory on arc, on refc, and `incRef` is attempted on `u.t.x` on refc which attempts to dereference the `refcount` field

**Comment by juancarlospaco** [comment]
!nim c

```nim
type
  T {.union.} = object
    x: string
    y: (int, int)
  U = object
    t: T

var u = U()
u.t = T(y: (1, 2))
reset(u.t)
```

**Comment by metagn** [comment]
Before someone says "disallow union with gc types", this also segfaults with arc:

```nim
proc bar(x: string) = discard

proc foo() =
  let x = cast[string]((1, 2))
  let y = x
  bar(y)

foo()
```

**Comment by metagn** [comment]
Actually there's probably no way this could work anyway, it's fine to avoid casting invalid memory to GC'ed types
