### ISSUE TITLE
Exceptions in top level statements of submodule not being reported/handled

### ISSUE THREAD

**Issue by JimMcInerney** [nim-lang/Nim#22469]
### Description

If a package with ModuleA and submodule ModuleB raises an exception in the top-level statements initializing ModuleB, the exception is not reported, and it seems to mess up subsequent error-handling in ModuleA.

```nim
# ModuleA
import ModuleA/ModuleB
echo "ModuleA about to have exception"
echo high(int) + 1

```
```nim
# ModuleB
echo "First top-level statement of ModuleB"
echo high(int) + 1
echo "ModuleB last statement"

```

### Nim Version

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
nimtest>nim c -o:bin\ModuleA.exe src\ModuleA
Hint: used config file 'C:\Program Files\nim-2.0.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\Program Files\nim-2.0.0\config\config.nims' [Conf]
.........................................................................
d:\nimtest\src\ModuleA.nim(2, 15) Warning: imported and not used: 'ModuleB' [UnusedImport]
CC: ModuleA/ModuleB.nim
CC: ModuleA.nim
@mModuleA@sModuleB.nim.c
@mModuleA.nim.c
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
27778 lines; 1.579s; 30.355MiB peakmem; proj: d:\nimtest\src\ModuleA; out: d:\nimtest\bin\ModuleA.exe [SuccessX]

nimtest>bin\ModuleA
First top-level statement of ModuleB
ModuleA about to have exceptionTraceback (most recent call last)
d:\nimtest\src\ModuleA.nim(4) ModuleA
C:\Program Files\nim-2.0.0\lib\system\fatal.nim sysFatal
C:\Program Files\nim-2.0.0\lib\system\arc.nim(81) nimNewObj
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

nimtest>
```

### Expected Output

```text
Something like:

First top-level statement of ModuleB
d:\nimtest\src\ModuleB.nim(3) ModuleB
C:\Program Files\nim-2.0.0\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]
```

### Additional Information

This occured with the Visual Studio vcc compiler.  With gcc, the overflow in ModuleB still is not reported (though execution breaks and returns to ModuleA), but ModuleA then reports its overflow without a segment fault.

**Comment by ringabout** [comment]
On it

**Comment by PMunch** [comment]
Seems Windows specific, I'm not able to reproduce the bug with Nim 2.0.0 and the same files on Linux.

**Comment by ringabout** [comment]
I can reproduce it on WSL2. It's expected to report errors in moduleB. "ModuleA about to have exception" shouldn't be printed at all.

**Comment by PMunch** [comment]
Oh yeah, it does print that on Linux as well. But it doesn't SIGSEGV, it shows the exception from ModuleA. If I make ModuleA not throw an exception then the exception from ModuleB is thrown in an arbitrary position in ModuleA..
