### ISSUE TITLE
Error: unknown hint: LineTooLong

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#22464]
### Description

Starting from bf5d173bc65aea071e5ffdf593f6b8797b56816d, the compiler doesn't compile (`nim c`).

### Nim Version

2.1.1 bf5d173bc65aea071e5ffdf593f6b8797b56816d

### Current Output

```text
C:\Users\User\.choosenim\toolchains\nim-#devel\config\nim.cfg(18, 3) Error: unknown hint: LineTooLong
```

### Possible Solution

Revert bf5d173bc65aea071e5ffdf593f6b8797b56816d.

**Comment by ringabout** [comment]
Why don't you update your devel version isstead?

**Comment by AmjadHD** [comment]
wdym ?
I'm already on latest devel:
```
Microsoft Windows [Version 10.0.19044.3086]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User\.choosenim\toolchains\nim-#devel>nim -v
Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2023-08-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 84f30d7c11741119f96ce63a9ea417d5ca233e1a
active boot switches: -d:release

C:\Users\User\.choosenim\toolchains\nim-#devel>koch boot -d:release
iteration: 1
bin\nim.exe c  --skipUserCfg --skipParentCfg -d:nimKochBootstrap --nimcache:nimcache/r_windows_amd64 -d:release --noNimblePath --compileOnly compiler\nim.nim
C:\Users\User\.choosenim\toolchains\nim-#devel\config\nim.cfg(18, 3) Error: unknown hint: LineTooLong
FAILURE

C:\Users\User\.choosenim\toolchains\nim-#devel>
```

**Comment by ringabout** [comment]
Did you remove the cache and the pre-existing `bin/nim` and `bin/nim_temp` binaries?

**Comment by AmjadHD** [comment]
You mean I have to build from csources ?

**Comment by ringabout** [comment]
Nope. After removing binaries, rerun `koch boot -d:release`.

**Comment by AmjadHD** [comment]
and what cache do you mean ? `nimcache/r_windows_amd64` ?
I also have no `bin/nim_temp`, do you mean `bin/nim_csources_86990...` ?

**Comment by ringabout** [comment]
That's so weird. I can build the source with 8.10 version. I will investigate it soon.

**Comment by AmjadHD** [comment]
I rebuilt from csources and now it works fine.
