### ISSUE TITLE
Wrong instance of the generic destructor is called

### ISSUE THREAD

**Issue by Pylgos** [nim-lang/Nim#22479]
### Description

```nim
type Obj[T] = object

proc `=destroy`[T](self: var Obj[T]) =
  echo T

block:
  let intObj = Obj[int]()

block:
  let floatObj = Obj[float]()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a660c17d309e2b077c610fd8c8c697944cff676d
active boot switches: -d:release

### Current Output

```text
int
int
```

### Expected Output

```text
int
float
```

### Additional Information

https://github.com/nim-lang/Nim/blob/a660c17d309e2b077c610fd8c8c697944cff676d/compiler/liftdestructors.nim#L1243-L1247
Since the hash values of `Obj[int]` and `Obj[float]` are the same, it seems that the destructor of the first generated `Obj[int]` is used for `Obj[float]`.

This issue is the root cause of https://github.com/nim-lang/Nim/issues/22305.

**Comment by beef331** [comment]
Tangentially related: https://github.com/nim-lang/Nim/issues/22445
The type system just does not see a generic body without generic parameters as a different type.
```nim
type Obj[T] = object
  a: int
 ```
 Has the same behaviour, but using the generic parameter chooses the right type.
 
 ```nim
 type Obj[T] = object
  a: T
  ```

**Comment by ringabout** [comment]
!nim c
```nim
type Obj[T] = object

proc `=destroy`[T](self: var Obj[T]) =
  echo T

block:
  let intObj = Obj[int]()

block:
  let floatObj = Obj[float]()
```

**Comment by haoyu234** [comment]
!nim c
```nim
type Obj[T] = object
  a: string

proc `=destroy`[T](self: var Obj[T]) =
  assert $typeof(T) == self.a

block:
  let intObj = Obj[int](a: "int")

block:
  let floatObj = Obj[float](a: "float")
```

**Comment by SirOlaf** [comment]
Also related #21742

Tried fixing that one, but all ideas I've had so far were breaking.

**Comment by jmgomez** [comment]
Related: https://discord.com/channels/371759389889003530/768367394547957761/1181972678945550397

Goes away with 
```nim

type 
    TMap*[K, V] {.importcpp .} = object
      fake: K
```

**Comment by Araq** [comment]
Not a regression, it never worked. The bugfix is also WIP and very risky to do so close to a release.
