### ISSUE TITLE
docs: Search CSS broken on devel

### ISSUE THREAD

**Issue by omentic** [nim-lang/Nim#22492]
### Description

![2023-08-16-224513](https://github.com/nim-lang/Nim/assets/35242550/a33688d0-fa65-4275-a0f6-9b0af08ae78c)

This occurs on https://nim-lang.github.io/Nim, not on https://nim-lang.org/docs/, and appears to be a recent regression.

### Nim Version

N/A

**Comment by bung87** [comment]
the search results floating same as left sidebar since https://github.com/nim-lang/Nim/pull/22394, if you think that's "css broken", please tell the detail.

**Comment by omentic** [comment]
The search results covers the full middle of the screen: neither clicking out of them nor escape gets rids of them. This makes them a pain for searching within the same module, as you can only escape by deleting all of the search query and clicking elsewhere. The search results go off the bottom of the screen and scrolling inconsistently scrolls either the manual or the results. So any results off the bottom of the screen are frequently inaccessible.

I don't like the floating search at all, actually, but IMO there are three big issues:
- There should be top and bottom padding to make it clear if there are results left or if the end of the screen is hit.
- Scrolling inconsistently scrolls the manual and the search results. I remember hitting a similar issue when implementing the left sidebar, but I don't remember how I fixed it.
- Escape and clicking off of the search results should dismiss them.

**Comment by omentic** [comment]
The scroll issue is still present, and I do still think that at least the escape key should dismiss the search results.
