### ISSUE TITLE
Proc naming issue in concept

### ISSUE THREAD

**Issue by Nmerryman** [nim-lang/Nim#22528]
### Description

Using `ready` as an identifier seem to cause issues. I think it's a bug because other names seem to work fine.

```nim
type
    ValidEvent* = concept C
        other(C) 
        ready(C) 

proc tick[T: ValidEvent](e: T) =
    # mixin ready   # <- mixin fixes the issue
    e.other()
    e.ready()   # <- Only this one errors

type
    TestEvent = object
        count: int

proc other(s: TestEvent) = discard
proc ready(s: TestEvent) = discard

var e = TestEvent(count: 1)
e.tick()
```

### Nim Version

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
d:\dump\Git\Finnese\tests\cd2.nim(9, 6) Error: type mismatch
Expression: ready(e)
  [1] e: TestEvent

Expected one of (first mismatch at [position]):
[1] proc ready[TMsg](c: var Channel[TMsg]): bool
```

### Expected Output

```text
None
```

**Comment by beef331** [comment]
This is not a bug, `ready` is defined inside `system` so it tightly binds to an `nnkClosedSym`. With generics a single overload binds tightly meaning it expects `var Channel[T]`

https://nim-lang.org/docs/manual.html#generics-bind-statement
