### ISSUE TITLE
`newString` zeroes memory contrary to its documentation, significantly slowing it down

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22555]
### Description

`newString` is supposed to return an uninitialized string, and thus presumably be fast:

https://github.com/nim-lang/Nim/blob/d677ed31e50a322851b476f20fd1719eb17cd426/lib/system.nim#L976

However, the actual implementations zero the full string leading to significant overhead making the function unfit for its purpose:

https://github.com/nim-lang/Nim/blob/devel/lib/system/strs_v2.nim#L113

### Nim Version

1.6, devel, both refc and orc

**Comment by ringabout** [comment]
Isn't it potentially a potential runtime breaking change supposing someone relies on the quirky behaviour? Yeah, let's find out whether it breaks something.

**Comment by ringabout** [comment]
It breaks https://github.com/jangko/nimPNG/issues/85

**Comment by mratsim** [comment]
But aren't all Nim data structures supposed to be zero-initialized?

I think the correct least-surprising way forward is to introduce newStringUninit / newStringUninitialized.

**Comment by Araq** [comment]
Hmm good point.

**Comment by arnetheduck** [comment]
Came to a similar conclusion while thinking about it over the weekend (`newStringUninitialized`).

_but_ to complete this section of nim, #19727 really needs addressing as well - the current situation is silly, ie can't `newSeqUninitialized` a `seq[Complex64]` nor `array[byte, 32]`  and so on making it impossible to write any sane deserialization code.

**Comment by ringabout** [comment]
As you wish, I will add a new function and remove outdated documentation.

**Comment by ringabout** [comment]
>  ie can't newSeqUninitialized a seq[Complex64] nor array[byte, 32]

Hi, @arnetheduck, `supportCopyMem` excludes types containing managed memory or having destructors. Is it enough?

**Comment by arnetheduck** [comment]
> Hi, @arnetheduck, supportCopyMem excludes types containing managed memory or having destructors. Is it enough?

It's a good enough to start with - I can imagine a few cases where this is too strict as well but it's easy to further relax in the future - ie consider a `ref` - strictly, if we had the expressivity saying that the instance is not a valid instance, we could allow uninit for ref as well - the situation is similar to what happens with an instance _after_ you moved from it (it's "destroyed" and therefore could be reused without zero-init in theory) but expressing this is tricky - I haven't followed arc closely enough to know for sure where this stands.
