### ISSUE TITLE
std/enumutils : Possible bug in documentation

### ISSUE THREAD

**Issue by heysokam** [nim-lang/Nim#22550]
Shouldn't this block of comments be `##` so it shows up in its [documentation page](https://nim-lang.org/docs/enumutils.html#genEnumCaseStmt.m%2Ctypedesc%2Ctyped%2Ctyped%2Cstatic%5Bint%5D%2Cstatic%5Bint%5D%2Cstatic%5Bproc%28string%29%5D)?
https://github.com/nim-lang/Nim/blob/ef63d47ecd10b4f1cd96da7a491a85fee6ab5965/lib/std/enumutils.nim#L21-L23

**Comment by ringabout** [comment]
You're right, PR is welcome!
