### ISSUE TITLE
`offsetof(T, anFieldOfUncheckedArray)` returned the wrong value

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#22553]
### Description

Here is my code example:
```nim
type
  ChunkObj = object
    data: UncheckedArray[byte]

proc main() =
  let n = offsetOf(ChunkObj, data)
  echo n
  assert n != 0                          # By looking at the generated C code, it should be 1 or something else
```
This is the C code generated by the NIM compiler:
```c
struct tyObject_ChunkObj__mOTFrUaGXmv4xFi10w76AA {
	char dummy;                                      // offset 0
	NU8 data[SEQ_DECL_SIZE];                // offset 1
};
```
From the above c code, you can see that the offset of the 'data' field should not be 0.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

### Current Output

```text
output '0' and assertion exception.

0
/root/repos/spaces/src/spaces.nim(33) spaces
/root/repos/spaces/src/spaces.nim(13) main
/root/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim(41) failedAssertImpl
/root/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim(36) raiseAssert
/root/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /root/repos/spaces/src/spaces.nim(13, 3) `n != 0`  [AssertionDefect]
```

### Expected Output

```text
1
```

### Additional Information

I also ran into another issue, which I'll explain in a new issue.

**Comment by juancarlospaco** [comment]
!nim c

```nim
type O = object
  data: UncheckedArray[byte]
proc f() =
  let n = offsetOf(O, data)
  doAssert n != 0, $n
f()
```

**Comment by litlighilit** [comment]
@haoyu234 
Beware nim is not C-backend only.  

Firstly,  `dummy` is to deal with the limit of C implementation. For example, it won't appear if using js backend [^1]

What's more, `offsetof` in fact works in compilation-time, which means it shall not consider how `Chunk` is implemented in backend language.

All in all, nim shall not be aware if a `dummy` exists;
And, if seeing nim-code, everyone will tell `data` is in the first i.e. 0-index.  
Therefore, making offset `1` may not be a good idea

[^1]: just a non-practical example

**Comment by ringabout** [comment]
there is no bug here. And the result of `offsetOf` in this case is alway 0 in every version.

**Comment by Araq** [comment]
No, the bug is very real.

**Comment by shirleyquirk** [comment]
on gcc, clang, icc, zigcc:
struct{} dummy; //zero bytes, but enough to shut up the 'named field' error
on msvc:
//cant use empty struct, but works without a dummy char.
[godbolt](https://godbolt.org/z/9qGhq165r)

either way, offsetOf and sizeOf are correct at 0,0

**Comment by ringabout** [comment]
> on gcc, clang, icc, zigcc:
struct{} dummy; //zero bytes, but enough to shut up the 'named field' error
on msvc:
//cant use empty struct, but works without a dummy char.

It's undefined behavior

> (C11, 6.7.2.1 Structure and union specifiers p8) "If the struct-declaration-list does not contain any named members, either directly or via an anonymous structure or anonymous union, the behavior is undefined."

> but a GNU C extension:

ref https://stackoverflow.com/questions/24685399/c-empty-struct-what-does-this-mean-do

C/C++ returns different results for `offsetOf and sizeOf`

C: 0, 0
C++: 1, 1
