### ISSUE TITLE
Non-GCed data structures could be copied more efficiently

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2256]
Right now every element of a seq and array is copied one by one in `genericAssignAux`. For gc-less data structures a single `copyMem` call would work as well and be much more efficient on modern machines for large data structures.

```
23:00 < def-> Araq: How would I best discover whether there is gc-ed memory 
              inside a data structure?
23:00 < Araq> missing typetrait
23:01 < Araq> we need a typetrait for that
```

**Comment by Araq** [comment]
This has been fixed recently and there is a typetrai ``supportsCopyMem`` now.
