### ISSUE TITLE
Types declared in non-top-level scope gensym their symbols to workaround bad mangling

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#22571]
### Description

```nim
macro foo(x: typed) =
  result = x
  echo result.repr

block: # or `proc main =`
  foo:
    type Foo = object
  echo Foo()
```

### Nim Version

2.0.0

### Current Output

```text
type
  Foo_520093702 = object
(7, 8) Error: undeclared identifier: 'Foo'
```

### Expected Output

```text
type
  Foo = object
()
```

### Possible Solution

Read comments below (https://github.com/nim-lang/Nim/issues/22571#issuecomment-1699046459 and https://github.com/nim-lang/Nim/issues/22571#issuecomment-1699240236) for description of why this happens. The issue is caused by the compiler intentionally gensymming these types to workaround a codegen issue that should have been solved in codegen. 

### Additional Information

Works if the macro is called at top level, or with declarations that are not types like `proc` or `const`

**Comment by juancarlospaco** [comment]
!nim c

```nim
macro foo(x: typed) =
  result = x
  echo result.repr

block:
  foo:
    type Foo = object
  echo Foo()
```

**Comment by metagn** [comment]
Culprit (https://github.com/nim-lang/Nim/commit/840e13deb79db7b072595658e6aa8328d55d7889 and https://github.com/nim-lang/Nim/commit/83e715c5b6b2501c02459398a2f394c457758a55):

https://github.com/nim-lang/Nim/blob/2e4e2f8f5076b39e5976ba20f231f468b1b5052c/compiler/semstmts.nim#L1589-L1591

Not sure if this code is sound

**Comment by metagn** [comment]
So while the code above in semstmts is the issue, when that code is removed, codegen fails because the codegen just uses the sighash to mangle the type name, and the sighash doesn't receive `block` information (relevant test is https://github.com/nim-lang/Nim/blob/devel/tests/ccgbugs/tsamename3.nim). Type mangling here:

https://github.com/nim-lang/Nim/blob/2e4e2f8f5076b39e5976ba20f231f468b1b5052c/compiler/ccgtypes.nim#L143-L144

I couldn't find where this was done at first so I attempted a more sweeping refactor where `skLabel` syms of the blocks are set as sym owners (and unnamed blocks gensym a name), but this still caused the issue for some types defined in templates.

So the simpler fix for now is to handle sighash conflicts in the type name mangling. I don't know how to do this properly and I would appreciate someone else looking into it because the "workaround" in semstmts is really bad.
