### ISSUE TITLE
collections/bytes (97, 23) Error: type mismatch: got <string, newline: string>

### ISSUE THREAD

**Issue by dmk28** [nim-lang/Nim#22588]
### Description

Hello,

Upon trying to code a very basic port scanner, I came across this particular error:

(97, 23) Error: type mismatch: got <string, newline: string>

Upon checking my code, I realized that there was no actual newline to my revision. However, on the submodule itself this was the culprit:
```

proc urlsafeBase64Encode*(s: string): string =
  return base64.encode(s, newline="").replace('+', '-').replace('/', '_').strip(chars={'='})

proc urlsafeBase64Decode*(s: string): string =
  var d = s.replace('-', '+').replace('_', '/')
  while len(d) mod 4 != 0:
    d.add('=')
  return base64.decode(d)
```

After I applied this fix:
```

proc urlsafeBase64Encode*(s: string): string =
  return base64.encode(s).replace('+', '-').replace('/', '_').strip(chars={'='})

proc urlsafeBase64Decode*(s: string): string =
  var d = s.replace('-', '+').replace('_', '/')
  while len(d) mod 4 != 0:
    d.add('=')
  return base64.decode(d)

```
My code ran normally. I'm not sure if there was any syntax mistake I missed or if this is a bona fide bug, but I decided to throw it out here to figure out what caused this. I am rather new at this so I am not sure if I made any mistakes that could have caused that error or if the collection itself presented this bug, but still, here it is. 

Hopefully this helps.
  
  

### Nim Version

Nim Compiler Version 1.6.14 [Windows: amd64]
Compiled at 2023-06-27
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
Error: type mismatch: got <string, newline: string>
but expected one of:
proc encode(s: string; safe = false): string
  first type mismatch at position: 2
  unknown named parameter: newline
proc encode[T: SomeInteger | char](s: openArray[T]; safe = false): string
  first type mismatch at position: 2
  unknown named parameter: newline

expression: base64.encode(s, newline = "")
```

### Possible Solution

proc urlsafeBase64Encode*(s: string): string =
  return base64.encode(s).replace('+', '-').replace('/', '_').strip(chars={'='})

proc urlsafeBase64Decode*(s: string): string =
  var d = s.replace('-', '+').replace('_', '/')
  while len(d) mod 4 != 0:
    d.add('=')
  return base64.decode(d)

**Comment by juancarlospaco** [comment]
https://nim-lang.github.io/Nim/base64.html#basic-usage-url-safe-base64

**Comment by juancarlospaco** [comment]
`base64.encode(s, newline="")` is not valid code, because `encode()` do not take `newline=""`, 
please read the documentation about URL-safe Base64: 
https://nim-lang.github.io/Nim/base64.html#basic-usage-url-safe-base64
