### ISSUE TITLE
Regarding the `coro.nimcfg` filename, is it typo?

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#22596]
### Description

I've seen many config files ending in `.nim.cfg`, but `coro.nimcfg` ending in `.nimcfg`, which seems to be typo.

https://github.com/nim-lang/Nim/blob/devel/lib/pure/coro.nimcfg

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

**Comment by ringabout** [comment]
It's not. `nimcfg` is a valid configuration suffix.

**Comment by haoyu234** [comment]
Okay, I thought it was a typo, I'll close the issue now.
