### ISSUE TITLE
 Static generic parameter does not work in param type scopes in procs

### ISSUE THREAD

**Issue by ASVIEST** [nim-lang/Nim#22607]
### Description

```nim
proc test[x: static bool](
  t: (
    when x:
      int
    else:
      float
     )
) = discard
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-09
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d136af012298b58be5abfb5e095cabd158feeb2e
active boot switches: -d:release

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-31
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b3912c25d3dcb78bc1c8f7d6acc3c512964d3ea8
active boot switches: -d:release

### Current Output

```text
Error: cannot generate code for: x
```

**Comment by ASVIEST** [comment]
!nim c
```nim
proc test[x: static bool](
  t: (
    when x:
      int
    else:
      float
     )
) = discard
```

**Comment by metagn** [comment]
Unfortunate workaround:

```nim
template foo(x): untyped = x
type T[x: static bool] = foo(when x: int else: float)
proc test[x: static bool](
  t: T[x]
) = discard
```

Really tempted to add the `untyped` escape hatch removed from #22029 that would make this as simple as `untyped(when x: int else: float)`

Related #22342
