### ISSUE TITLE
Missing type inference in loop + case + if + continue

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22604]
### Description

broken:

```nim
for i in 0..<10:
  let x =
    case false
    of true:
      42
    of false:
      if true:
        continue
      else:
        raiseAssert "Won't get here"

  echo x
```

works:
```nim
for i in 0..<10:
  let x =
    case false
    of true:
      42
    of false:
      if true:
        33
      else:
        raiseAssert "Won't get here"

  echo x
```

### Nim Version

1.6.14

### Current Output

```text
testit.nim(12, 7) Error: expression '42' is of type 'int literal(42)' and has to be used (or discarded)
```

**Comment by metagn** [comment]
The noreturn checks are not deep IIRC, they just check the last node in a branch, then check if it's a noreturn call or `continue`/`raise`/`return`/`break`. In this case the last node is an `if` statement with 2 noreturn branches, which isn't inferred to be noreturn.

https://github.com/nim-lang/Nim/blob/b3912c25d3dcb78bc1c8f7d6acc3c512964d3ea8/compiler/sem.nim#L209-L215
