### ISSUE TITLE
IndexDefect or RangeDefect, how to decide

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#22615]
### Description

I read the source code of `indices.nim` and I noticed that some of the data slicing operations here actually throw an out-of-bounds subscript exception, should a range error exception be thrown when the slice range is not legal? 

some code:
```nim
let data: array[4, byte] = [1, 2, 3, 4]

proc main() = 

  proc sliceOutOfBound[U, V](s: openArray[byte], x: HSlice[U, V]) =
    discard s[x]

  proc assignOutOfBound[U, V](a: var array[4, byte], x: HSlice[U, V], s: openArray[byte]) =
    a[x] = s

  sliceOutOfBound(data, 0 .. 5)  # Unhandled exception: index 4 not in 0 .. 3 [IndexDefect]
  # assignOutOfBound(data, 0 .. 5, data.toOpenArray(0, 2))  # Unhandled exception: different lengths for slice assignment [RangeDefect]

main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

**Comment by metagn** [comment]
The second error is a different case, it's not complaining that the index range given is out of bounds, it's complaining that the index range and the openArray to assign to the index range have different lengths. So IndexDefect would not be appropriate.

Doing `assignOutOfBound(data, 0 .. 5, [byte 1, 2, 3, 4, 5, 6])` for example would give an IndexDefect.
