### ISSUE TITLE
incorrect UnreachableCode warning generated

### ISSUE THREAD

**Issue by tommo** [nim-lang/Nim#22626]
### Description

The following code generates incorrect UnreachableCode warnings with the latest devel version.

```nim
{.warningAsError[UnreachableCode]:on.} 

for i in 0 ..< 10:
  block namedBlock:
    if i>1: 
      break namedBlock
    continue
  echo "reach here"
```

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: arm64]
Compiled at 2023-09-02
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 9f1fe8a2da27abc1e93a05debbb2622b524aae0d
active boot switches: -d:release -d:danger

**Comment by ringabout** [comment]
probably related: https://github.com/nim-lang/Nim/pull/22612

**Comment by ringabout** [comment]
!nim c
```nim
{.warningAsError[UnreachableCode]:on.} 

for i in 0 ..< 10:
  block namedBlock:
    if i>1: 
      break namedBlock
    continue
  echo "reach here"
```

**Comment by ringabout** [comment]
!nim c --warningAsError:UnreachableCode
```nim
for i in 0 ..< 10:
  block namedBlock:
    if i>1: 
      break namedBlock
    continue
  echo "reach here"
```

**Comment by SirOlaf** [comment]
Yeah that's my mistake, forgot blocks just eat continue and break. Even without that though it would fail to understand named blocks, but at least that isn't a regression
