### ISSUE TITLE
Weird underscore naming in docs

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#22630]
### Description

Generating docs with Nim v2.0 for procedures with an underscore argument leads to signatures in the docs which looks like this:

```nim
proc init(__520093753: type MyType): MyType
```

I'm pretty sure this has to do with the new "Consistent underscore handling" added in v2.0

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/22538

**Comment by PMunch** [comment]
Damn, so fast response time it went back into the past! I searched for open and closed issues, didn't think to look for a PR.

**Comment by ringabout** [comment]
Lol, there is a similar one https://github.com/nim-lang/Nim/issues/22628 raised today showing how hot this topic is!
