### ISSUE TITLE
Defining an object type contains imported C++ struct without default constructor causes backend C++ compiler error

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#22633]
### Description

When imported a C++ struct/class without default constructor and define an object type contains that,
C++ backend compiler reports errors.

Example code:
testcpp.hpp:
```c++
#pragma once

struct CppStruct {
  CppStruct(int x): x(x) {}

  void doSomething() {}

  int x;
};
```

testcpp.nim:
```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp".} = object

proc constructCppStruct(x: cint): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
proc doSomething(this: CppStruct) {.importcpp, header: "testcpp.hpp".}

type
  HasCppStruct = object
    cppstruct: CppStruct

proc initHasCppStruct(x: cint): HasCppStruct =
  HasCppStruct(cppstruct: constructCppStruct(x))

proc main =
  var hasCppStruct = initHasCppStruct(2)
  hasCppStruct.cppstruct.doSomething()

main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-02
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2542dc09c829a709050335066b0f414d6fc68fe2
active boot switches: -d:release

### Current Output

```text
/tmp/nimcache123/testcpp/debug/@mtestcpp.nim.cpp:39:29: Error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<
brace-enclosed initializer list>’ to ‘CppStruct’
   39 |         CppStruct cppstruct{};
      |                             ^
      |                             |
      |                             <brace-enclosed initializer list>
```

### Expected Output

```text
Compiles without error
```

### Additional Information

In Nim generated C++ code, `HasCppStruct` object type in Nim code is defined like this:
```c++
struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA {
	CppStruct cppstruct{};
};
```
It results in compile error as `CppStruct` doesn't have default constructor.

If the member variable is declared without brace-enclosed initializer list and the constructor initialize it with proper argument, C++ code compiles:
```c++
struct CppStruct {
  CppStruct(int x): x(x) {}

  void doSomething() {}

  int x;
};

struct HasCppStruct {
  CppStruct cppstruct;

  HasCppStruct(int x): cppstruct(x){}
};

int main() {
  HasCppStruct a(1);
}
```

Workaround:
Define an object type in C++ code instead of Nim code and import it.
```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp".} = object

proc constructCppStruct(x: cint): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
proc doSomething(this: CppStruct) {.importcpp, header: "testcpp.hpp".}

{.emit: """
  struct HasCppStruct {
    HasCppStruct(int x): cppstruct(x) {}

    CppStruct cppstruct;
  };
""".}

type
  HasCppStruct {.importcpp.} = object
    cppstruct: CppStruct

proc constructHasCppStruct(x: cint): HasCppStruct {.importcpp: "HasCppStruct(@)", constructor.}

proc main =
  var hasCppStruct = constructHasCppStruct(2)
  hasCppStruct.cppstruct.doSomething()

main()
```

**Comment by jmgomez** [comment]
With the new constructor pragma you can get around it. 
There is a similar example on the docs: https://nim-lang.github.io/Nim/manual_experimental.html#constructor-pragma

I don't think this is really a Nim issue though. We could sem check it but probably wouldn't matter as everyone doing interop should know what is doing

**Comment by demotomohiro** [comment]
I can define a constructor that initialize the member variable with new constructor pragma.
But I still get the same compile error as Nim adds '{}' after a member variable declaration.
I need to declare the member variables without '{}' to stop the compile error.

testcpp.hpp:
```c++
#pragma once

struct CppStruct {
  CppStruct(int x): x(x) {}

  void doSomething() {}

  int x;
};
```

testcpp.nim:
```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp".} = object

proc constructCppStruct(x: cint): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
proc doSomething(this: CppStruct) {.importcpp, header: "testcpp.hpp".}

type
  HasCppStruct = object
    cppstruct: CppStruct

proc initHasCppStruct(x: cint): HasCppStruct {.constructor:"HasCppStruct('1 #1): cppstruct(#1)".} =
  discard

proc main =
  var hasCppStruct = initHasCppStruct(2)
  hasCppStruct.cppstruct.doSomething()

main()
```

Compile it with `nim cpp testcpp.nim` and got following compile error:
```
/tmp/nimcache123/testcpp/debug/@mtestcpp.nim.cpp:38:29: Error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<
brace-enclosed initializer list>’ to ‘CppStruct’
   38 |         CppStruct cppstruct{};
      |                             ^
      |                             |
      |                             <brace-enclosed initializer list>
```

In Nim generated C++ code:
```c++
struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA;
struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA {
	CppStruct cppstruct{};                                // '{}' after member variable name causes compile error.
N_LIB_PRIVATE N_NOCONV(, tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA)(int x_p0);
tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA() = default;
};
```

Following C++ code result in same compile error:
```C++
// Compile this with `g++ testcpp.cpp`.

#include "testcpp.hpp"

struct HasCppStruct {
  CppStruct cppstruct{};
  //CppStruct cppstruct;   //Removing '{}' like this fix the compile error.

  HasCppStruct(int x): cppstruct(x) {}
};

int main() {
  HasCppStruct a(1);
}
```

> With the new constructor pragma you can get around it. There is a similar example on the docs: https://nim-lang.github.io/Nim/manual_experimental.html#constructor-pragma

That example code compiles without errors because it inherits imported C++ struct.
If `NimClass` has `CppClass` instead of inherits it, I got same compile error.
example.nim:
```nim
{.emit:"""/*TYPESECTION*/
struct CppClass {
  int x;
  int y;
  CppClass(int inX, int inY) {
    this->x = inX;
    this->y = inY;
  }
  //CppClass() = default;
};
""".}

type
  CppClass* {.importcpp, inheritable.} = object
    x: int32
    y: int32
  #NimClass* = object of CppClass
  NimClass = object
    cppClass: CppClass

proc makeNimClass(x: int32): NimClass {.constructor:"NimClass('1 #1) : cppClass(0, #1)".} =
  discard

proc main =
  var a = makeNimClass(1)
  echo a.cppClass.y

main()
```

Compile it with `nim cpp example.nim` and got following error:
```
/tmp/nimcache123/example/debug/@mexample.nim.cpp:75:27: Error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<
brace-enclosed initializer list>’ to ‘CppClass’
   75 |         CppClass cppClass{};
      |                           ^
      |                           |
      |                           <brace-enclosed initializer list>
```

**Comment by jmgomez** [comment]
I see. As a workaround you could also use `codegenDecl` (notice since Nim 2.0 it also works on types, https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-codegendecl-pragma) which is better than defining and importing the type. But yes, we can do better.

I had this idea for a while where we could use use the `constructor` pragma to do a lookup for initialisers. So if in the codegen there is a default function constructor defined (we can go further and store values as default in the Nim function itself) we just use it instead.
For example, in the code above: 

```nim
proc constructCppStruct(x: cint = 10): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
```

It will produce
```
 CppStruct cppstruct = CppStruct(10);
```

@Araq any thought? If you like the idea I can work on it.

**Comment by demotomohiro** [comment]
Thank you for your advice.
`codegenDecl` still adds '{}' after member variable name and I got same compile error.

testcpp.hpp:
```c++
#pragma once

struct CppStruct {
  CppStruct(int x): x(x) {}

  void doSomething() {}

  int x;
};
```

testcpp.nim:
```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp".} = object

proc constructCppStruct(x: cint): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
proc doSomething(this: CppStruct) {.importcpp, header: "testcpp.hpp".}

const strTemplate = """
  struct $1 {
    // How codegenDecl works?
    $2
  };
"""

type
  HasCppStruct {.codegenDecl:strTemplate.} = object
    cppstruct: CppStruct

proc initHasCppStruct(x: cint): HasCppStruct {.constructor:"HasCppStruct('1 #1): cppstruct(#1)".} =
  discard

proc main =
  var hasCppStruct = initHasCppStruct(2)
  hasCppStruct.cppstruct.doSomething()

main()
```

Compile it with `nim cpp testcpp.nim` and got following compile error:
```
/tmp/nimcache123/testcpp/debug/@mtestcpp.nim.cpp:39:29: Error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<
brace-enclosed initializer list>’ to ‘CppStruct’
   39 |         CppStruct cppstruct{};
      |                             ^
      |                             |
      |                             <brace-enclosed initializer list>
```

In Nim generated C++ code:
```c++
struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA;
  struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA {
    // How codegenDecl works?
    	CppStruct cppstruct{};
N_LIB_PRIVATE N_NOCONV(, tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA)(int x_p0);
tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA() = default;

  };
```

How about to add `noDefaultConstructor` pragma that is used for imported C++ types to remove '{}' after member variable?

```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp", noDefaultConstructor.} = object

type
  HasCppStruct = object
    cppstruct: CppStruct

proc initHasCppStruct(x: cint): HasCppStruct {.constructor:"HasCppStruct('1 #1): cppstruct(#1)".} =
  discard
```

In Nim generated C++ code:
```c++
struct tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA {
  CppStruct cppstruct;
  N_LIB_PRIVATE N_NOCONV(, tyObject_HasCppStruct__9c2ljVEQbf8xtWpuut9bV6cA)(int x_p0);
};
```

**Comment by jmgomez** [comment]
Do not declare the field in Nim as it would be injected via `$2`. The idea here is to make the field invisible to Nim (you can still access to it by importing it later in a `proc` getter/setter)

**Comment by demotomohiro** [comment]
Thank you.
This code compiled without errors.

testcpp.hpp:
```c++
#pragma once

struct CppStruct {
  CppStruct(int x): x(x) {}

  void doSomething() {}

  int x;
};
```

testcpp.nim:
```nim
type
  CppStruct {.importcpp, header: "testcpp.hpp".} = object

proc constructCppStruct(x: cint): CppStruct {.importcpp: "CppStruct(@)", constructor, header: "testcpp.hpp".}
proc doSomething(this: CppStruct) {.importcpp, header: "testcpp.hpp".}

const strTemplate = """
  struct $1 {
    CppStruct cppstruct;

    CppStruct& getCppStruct() {
      return cppstruct;
    }

    $2
  };
"""

type
  HasCppStruct {.codegenDecl: strTemplate.} = object

proc getCppStruct(this: HasCppStruct): var CppStruct {.importcpp: "#.getCppStruct()".}

proc initHasCppStruct(x: cint): HasCppStruct {.constructor:"HasCppStruct('1 #1): cppstruct(#1)".} =
  discard

proc main =
  var hasCppStruct = initHasCppStruct(2)
  hasCppStruct.getCppStruct.doSomething()

main()
```

**Comment by juancarlospaco** [comment]
> This code compiled without errors.

Then Close ?, or something else is going on...

**Comment by jmgomez** [comment]
Since Nim can do better, I will add a RFC soon that references this and also a `result` issue I had not so long ago. I dont mind to have it open/close just FYI

**Comment by jmgomez** [comment]
This can be closed now: https://nim-lang.github.io/Nim/manual_experimental.html#constructor-initializer

**Comment by demotomohiro** [comment]
I recently relearned about C++ constructors.
Importing C++ types with deleted default constructor to Nim, and adding default values to the imported constructor so that it can be initialized without arguments seems not a good idea.
C++ programmers delete default constructor and define constructors with parameters when it should be constructed with arguments and want to make constructing without arguments compile error.
https://stackoverflow.com/q/8068088
https://stackoverflow.com/a/48664769
It is similar to `requiresInit` pragma in Nim.
But adding default values to every constructor's parameters allows user to construct without arguments.
When a C++ class doesn't have a default constructor, finding default value that makes sense will be hard.
https://en.cppreference.com/w/cpp/thread/lock_guard/lock_guard
What default value to lock_guard makes sense?
https://doc.qt.io/qt-6/qguiapplication.html#QGuiApplication
How to provide argc and argv to it as default value?
If there is the default value that makes sense, that C++ class would already have a constructor without parameter or a constructor with parameters and all parameters have the default value.
In Named Constructor idiom, constructors are private and the class can be constructed only by calling specific functions:
https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Named_Constructor
https://stackoverflow.com/a/6568587

So when importing a C++ class without default constructor, keep it unable to construct without arguments is better.
But when defining an object type that has a field which is imported C++ class without default constructor and doesn't have constructors with default values, it still cause compile error because that field is declared with '{}' in the class in generated C++ code.
I can workaround this problem by inheriting imported C++ class and define a proc with constructor pragma and parameters to construct base class.
But this workaround cannot be used in some cases:
- Defining an object type contains two or more imported C++ class with deleted default constructor (Nim doesn't support multiple inheritance like C++)
- It need to inherits from specific type
- Imported C++ class was defined with 'final' and cannot inherit from it

So I think adding new pragma (like `cppRequiresInit` or reuse `requiresInit`) that is used with importcpp type is better.
When declaring a variable of `cppRequiresInit` type, it must be initialized with constructor that takes arguments or procedure returns the object.
When a field of object types was `cppRequiresInit`, corresponding member variable is declared without '{}' in generated C++.
And the field must be initialized in member initializer list in constructor proc of the object contains that field.
But text parameter given to constructor pragma is almost C++ code.
So checking if `cppRequiresInit` type is properly initialized in the constructor is hard for Nim and when there is any errors, it will come from back end C++ compiler.

**Comment by jmgomez** [comment]
You have a point but in general I think if anything it must be the other way around, negating it (i.e. `noInit` or `cppNoInit` and maybe only in fields instead of the `type`). There are a couple of scenarios where `{}` are used, one of them is temps. The moment Nim produces a temp, it will spin one and we cant do much about it other than providing the default values. 

> Nim doesn't support multiple inheritance like C++

There is support to some extend to multiple inheritance. From the 2.0 release post: 

```nim

struct Base {
  int someValue;
  Base(int inValue)  {
    someValue = inValue;
  };
};

class IPrinter {
public:
  virtual void print() = 0;
};
type
  Base* {.importcpp, inheritable.} = object
    someValue*: int32
  IPrinter* {.importcpp.} = object

const objTemplate = """
  struct $1 : public $3, public IPrinter {
    $2
  };
""";

type NimChild {.codegenDecl: objTemplate.} = object of Base

```

**Comment by demotomohiro** [comment]
While I tried to solve this issue in better way, I accidentally found an easier way to fix.

When a member variable is defined like following code, it compiles without errors even if the type of member variable doesn't have default constructor.

```c++
#include <type_traits>
#include <iostream>

using namespace std;

struct NoDC {
  int x;

  NoDC(int x): x(x) {
    cout << "Construct NoDC: " << x << endl;
  }

  void print() {
    cout << "NoDC::print: " << x << endl;
  }
};

template<bool Cond = true>
struct Example {
  std::conditional_t<Cond, NoDC, void> noDC{};

  Example(int x): noDC(x){}
};

int main() {
  Example<> e(11);

  e.noDC.print();

  return 0;
}
```

It just put the type of member variable inside `std::conditional_t`, put it inside template class and that `std::conditional_t` uses the template parameter.

I have tested it on gcc, clang and msvc on godot, and compiled without error on all of them.
x86-64 gcc 13.2
https://godbolt.org/z/ovPKMc9Yb
x86-64 clang 17.0.1
https://godbolt.org/z/h46sWaG39
x64 msvc v19.latest
https://godbolt.org/z/rGqPc4d7f

Nim compiler doesn't need to know whether importedcpp types have default constructor or not.
Adding new pragma or reusing existing pragma to fix this issue is not needed.
But user have to write a constructor initializes importcpp type with parameters if it doesn't have default constructor.

If Nim's object types are defined like following code in generated C++ code,
other code doesn't need to be changed.
```c++
namespace NimPrivate {
  template<bool Cond = true>
  struct Example {
    std::conditional_t<Cond, NoDC, void> noDC{};

    Example(int x): noDC(x){}
  };
}

using Example = NimPrivate::Example<>;
```

But generated C++ code become less readable.
If someone don't know about this issue read generated C++ code, it would looks like using meaningless template. Maybe add some comments in generated code?

Nim still generates local variables initialized with '{}' in functions and causes compile errors if it doesn't have default constructor.
This doesn't fix the issue. I think it can be fixed in different way.
