### ISSUE TITLE
[github setting] Set the default commit message to "Pull request title and description"

### ISSUE THREAD

**Issue by MaskRay** [nim-lang/Nim#22634]
### Summary

Select `Pull request title and description`

### Description

The current setting appears to be

> **Default message**: commit title and commit message (if the pull request contains a single commit), or the pull request title and number and list of commits (if the pull request contains multiple commits)

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

In short, the squashed commit message contains concatenated messages from fixup commits, so there are often 
```
* tiny fixes
* fixes an omittance
* clean test
```

When the merger does not carefully clean them up.

Changing to "Pull request title and description" will solve the problem.

Related feedback from https://github.com/orgs/community/discussions/30439 

> This is great, no more test / test / fix typo / ... commit messages when squashing!

**Comment by metagn** [comment]
Pretty easy to do, any objections? I thought this already was the case, I write PR descriptions but basically no commit messages.

**Comment by ringabout** [comment]
Done, we can always revert to the old change if someone objects to it.

**Comment by ringabout** [comment]
@MaskRay Hi, I see that you are still following the progress of the Nim project. Thanks for your suggestion on commit messages!
