### ISSUE TITLE
Regression in `{.borrow.}` for generic type with static size

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#22646]
### Description

After updating today for the `sizeof` fix (thanks!) I notice a regression in `{.borrow.}`. I have a distinct type based on the `Vec` of `glm`. Borrowing for them is not possible anymore. It was compiling just fine yesterday on commit https://github.com/nim-lang/Nim/commit/c5495f40d5d881e6bd155c9e6c9c6e5e49b749a7.

However, only procedures that return a type with the static size not explicitly specified are affected. As long as either the static size `N` is given explicitly or the return type does not contain `N` it works fine:

```nim
type
  Vec*[N : static[int], T: SomeNumber] = object
    arr*: array[N, T]
  Vec3*[T: SomeNumber] = Vec[3, T]

proc `[]=`*[N,T](v: var Vec[N,T]; ix:int; c:T): void {.inline.} = v.arr[ix] = c
proc `[]`*[N,T](v: Vec[N,T]; ix: int): T {.inline.} = v.arr[ix]

proc dot*[N,T](u,v: Vec[N,T]): T {. inline .} = discard
proc length*[N,T](v: Vec[N,T]): T = discard
proc cross*[T](v1,v2:Vec[3,T]): Vec[3,T] = discard
proc normalizeWorks*[T](v: Vec[3,T]): Vec[3,T] = discard ## <- Explicit size makes it work!
proc foo*[N,T](u, v: Vec[N,T]): Vec[N,T] = discard ## <- broken
proc normalize*[N,T](v: Vec[N,T]): Vec[N,T] = discard ## <- broken

type
  Color* = distinct Vec3[float]

template borrowOps(typ: typedesc): untyped =
  proc `[]=`*(v: var typ; ix: int; c: float): void {.borrow.}
  proc `[]`*(v: typ; ix: int): float {.borrow.}
  proc dot*(v, u: typ): float {.borrow.}
  proc cross*(v, u: typ): typ {.borrow.}
  proc length*(v: typ): float {.borrow.}
  proc normalizeWorks*(v: typ): typ {.borrow.} ## Up to here everything works
  proc foo*(u, v: typ): typ {.borrow.} ## Broken
  proc normalize*(v: typ): typ {.borrow.} ## Broken
borrowOps(Color)
```

*UPDATE*: This also seems to affect other things. I'm struggling to reproduce it at the moment, but just trying to convert a `Vec3d` to a `Color` using `Color(foo)` is broken too. Based on the error message I think the problem is the same. It seems like the compiler is confused about the type equality.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: eb91cf991aa9840639cc358c21d503e4cf27e268
active boot switches: -d:release -d:danger

### Current Output

```text
/tmp/bug_regression.nim(28, 10) template/generic instantiation of `borrowOps` from here
/tmp/bug_regression.nim(26, 3) Error: borrow from proc return type mismatch: 'Vec[3, system.float]'
```

### Expected Output

```text
Compile :)
```

### Additional Information

https://github.com/nim-lang/Nim/issues/22069 seems related?

**Comment by juancarlospaco** [comment]
!nim c

```nim
type
  Vec*[N : static[int], T: SomeNumber] = object
    arr*: array[N, T]
  Vec3*[T: SomeNumber] = Vec[3, T]

proc `[]=`*[N,T](v: var Vec[N,T]; ix:int; c:T): void {.inline.} = v.arr[ix] = c
proc `[]`*[N,T](v: Vec[N,T]; ix: int): T {.inline.} = v.arr[ix]

proc dot*[N,T](u,v: Vec[N,T]): T {. inline .} = discard
proc length*[N,T](v: Vec[N,T]): T = discard
proc cross*[T](v1,v2:Vec[3,T]): Vec[3,T] = discard
proc normalizeWorks*[T](v: Vec[3,T]): Vec[3,T] = discard ## <- Explicit size makes it work!
proc foo*[N,T](u, v: Vec[N,T]): Vec[N,T] = discard ## <- broken
proc normalize*[N,T](v: Vec[N,T]): Vec[N,T] = discard ## <- broken

type
  Color* = distinct Vec3[float]

template borrowOps(typ: typedesc): untyped =
  proc `[]=`*(v: var typ; ix: int; c: float): void {.borrow.}
  proc `[]`*(v: typ; ix: int): float {.borrow.}
  proc dot*(v, u: typ): float {.borrow.}
  proc cross*(v, u: typ): typ {.borrow.}
  proc length*(v: typ): float {.borrow.}
  proc normalizeWorks*(v: typ): typ {.borrow.} ## Up to here everything works
  proc foo*(u, v: typ): typ {.borrow.} ## Broken
  proc normalize*(v: typ): typ {.borrow.} ## Broken
borrowOps(Color)
```

**Comment by juancarlospaco** [comment]
Fixed on devel ?. 🤔

**Comment by Vindaar** [comment]
> Fixed on devel ?. 🤔

Does the git bisecting helper always use the latest HEAD?

**Comment by juancarlospaco** [comment]
> Does the git bisecting helper always use the latest HEAD?

Yeah it does, maybe try compiling latest head on your local?, which platform?.

**Comment by Vindaar** [comment]
> > Does the git bisecting helper always use the latest HEAD?
> 
> Yeah it does, maybe try compiling latest head on your local?, which platform?.

Uh, see my Nim version above. That _is_ the latest head.
