### ISSUE TITLE
generic types parameter asserts the compiler (#2)

### ISSUE THREAD

**Issue by dagan-deon** [nim-lang/Nim#22647]
### Description

```nim
proc c0(n: static int): int = 8
proc c1(n: static int): int = n div 2
proc c2(n: static int): int = n * 2

type
  a[N: static int] = object
    f0 : array[N, int]

  b[N: static int] = object
    f0 : a[c0(N)]  # does not work
    f1 : a[c1(N)]  # does not work
    f2 : a[c2(N)]  # does not work
    f3 : a[N * 2]  # does not work
    f4 : a[N]      # works

proc p[N: static int](x : a[N]) = echo x.f0[0]
proc p[N: static int](x : b[N]) =
  x.f0.p()
  x.f1.p()
  x.f2.p()
  x.f3.p()
  x.f4.p()

var x: b[4]
x.p()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f7aedb3d1941650e6650c07aa4bcf6a7dee0b90
active boot switches: -d:release

### Current Output

```text
......................................................................assertions.nim(34)       raiseAssert
Error: unhandled exception: int128.nim(66, 11) `arg.sdata(3) == -1` out of range [AssertionDefect]

shell returned 1
```

**Comment by dagan-deon** [comment]
!nim c
```nim
proc c0(n: static int): int = 8
proc c1(n: static int): int = n div 2
proc c2(n: static int): int = n * 2

type
  a[N: static int] = object
    f0 : array[N, int]

  b[N: static int] = object
    f0 : a[c0(N)]  # does not work
    f1 : a[c1(N)]  # does not work
    f2 : a[c2(N)]  # does not work
    f3 : a[N * 2]  # does not work
    f4 : a[N]      # works

proc p[N: static int](x : a[N]) = echo x.f0[0]
proc p[N: static int](x : b[N]) =
  x.f0.p()
  x.f1.p()
  x.f2.p()
  x.f3.p()
  x.f4.p()

var x: b[4]
x.p()
```

**Comment by metagn** [comment]
Not an early generic semchecking bug, for some reason `N` stays unresolved inside the type during the proc instantiations. The `var x: b[4]` by itself instantiates completely fine for example if you do `echo x`

**Comment by dagan-deon** [comment]
What is the status/plan for this?
1. fixable: long-term or short-term?
2. not fixable, but there is a workaround.
3. not fixable, won't be supported by the language in the foreseeable future.

**Comment by metagn** [comment]
I mean it should work. Can't really say when it will be fixed if someone doesn't have a solution, and no one has suggested one.

Can't think of a workaround right now either.

**Comment by dagan-deon** [comment]
ok thanks. I think I will need to make time to dig into the compiler internals.

**Comment by metagn** [comment]
Seems to work now? No idea how

**Comment by metagn** [comment]
It compiles but the `p(a[N])` overload seems to infer `N` as 1 for every field except `f4`. If you change it to `echo x.f0.len` instead of `echo x.f0[0]`, the output is:

```
1
1
1
1
4
```

And changing it to `echo x.f0` just crashes the compiler. It seems the type of the array literally becomes something like `array[typeof(c0(N)), int]`.
