### ISSUE TITLE
Redundant `result` variable in closure iterator environment

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22666]
### Description

```nim
proc abc(): iterator: int =
  iterator def(): int {.closure.} =
    yield 42
  return def


echo abc()()
```

```c
struct tyObject_Env_testitdotnim_def___vUN23H2tO69bUwRr82sbbAA {  RootObj Sup;	NI colonstate_;
	NI result1;
};
```

There's obviously no reason for the environment to contain such a variable nor does it get used - this wastes space and time to zero it making closures less efficient than they need to be.

### Nim Version

1.6.14, 2.x

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23787

```c
struct tyObject_Env_test17dotnim_def___qsVcFH9baM19ceq2CnDTzqfA {
  RootObj Sup;
  NI colonstate_;
};
```
