### ISSUE TITLE
Procs with constructor pragma doesn't initialize object's fields

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#22662]
### Description

Procedures defined with constructor pragma doesn't initialize object's fields.
Example:
testcpp2.nim:
```nim
type
  NimClass* = object
    x: int          # Not initialized

proc makeNimClass(): NimClass {.constructor.} =
  discard

proc main =
  for i in 0 .. 1:
    var n = makeNimClass()
    echo n.x
    n.x = 123
    echo n.x

main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f7aedb3d1941650e6650c07aa4bcf6a7dee0b90
active boot switches: -d:release

### Current Output

```text
268435456
123
123
123
```

### Expected Output

```text
0
123
0
123
```

### Possible Solution

When generating C++ code, initialize fields in constructor or in struct definition:
```c++
struct tyObject_NimClass {
  NI x{};
  // or NI x = 0;
};

// Or
tyObject_NimClass::tyObject_NimClass() {
  x = 0;
}
```

### Additional Information

In Nim generated C++ code, field `x` is not initialized:
```C++
struct tyObject_NimClass__ZFCcrp08suVyruEm60R7mA {
	NI x;
N_LIB_PRIVATE N_NOCONV(, tyObject_NimClass__ZFCcrp08suVyruEm60R7mA)(void);
};

...

N_LIB_PRIVATE N_NOCONV(, tyObject_NimClass__ZFCcrp08suVyruEm60R7mA::tyObject_NimClass__ZFCcrp08suVyruEm60R7mA)(void) {
	nimfr_("makeNimClass", "/home/player/worktmpfs/testnim/testcpp2.nim");
	popFrame();
}
```

When an object contains the struct type imported C++ code, it is initialized but Nim type fields are not.
```nim
{.emit:"""/*TYPESECTION*/
struct CppClass {
  int x;
};
""".}

type
  CppClass* {.importcpp.} = object
    x: cint

  NimClass* = object
    x: int          # Not initialized
    cpp: CppClass   # Initialized to zero

proc makeNimClass(): NimClass {.constructor.} =
  discard

proc main =
  for i in 0 .. 1:
    var n = makeNimClass()
    echo n.x, " ", n.cpp.x
    n.x = 123
    n.cpp.x = 321
    echo n.x, " ", n.cpp.x

main()
```

Output:
```
0 0
123 321
123 0
123 321
```

Expected output:
```
0 0
123 321
0 0
123 321
```

In Nim generated C++ code:
```c++
struct tyObject_NimClass__wPhP74Yg7WO49cvrXHdusjQ {
	NI x;
	CppClass cpp{};
N_LIB_PRIVATE N_NOCONV(, tyObject_NimClass__wPhP74Yg7WO49cvrXHdusjQ)(void);
};

...

N_LIB_PRIVATE N_NOCONV(, tyObject_NimClass__wPhP74Yg7WO49cvrXHdusjQ::tyObject_NimClass__wPhP74Yg7WO49cvrXHdusjQ)(void) {
	nimfr_("makeNimClass", "/home/player/worktmpfs/testnim/testcpp.nim");
	popFrame();
}
```

Field `cpp` is initialized as it has '{}' but field `x` is not initialized.

**Comment by Araq** [comment]
`constructor` was designed for `importcpp`. Generating a constructor is currently full of problems:

```nim

proc makeNimClass(): NimClass {.constructor.} =
  NimClass(x: 10) # cannot use `result`, wtf

```

> Error: type mismatch: got 'NimClass' for 'NimClass(x: 10)' but expected 'ptr NimClass'

What?

**Comment by jmgomez** [comment]
@Araq as discussed on internals (and the manual) we changed `result` to `this` so they behave like in Cpp. You dont suppose to return anything from them but to access the fields via `this`

Can someone assign the issue to me? I will look into it once I have the chance

**Comment by jmgomez** [comment]
AFAIK the generated code is correct (ints are zeroed by default in C++). Still looking into it but just so 
you know it works with `d:release` and it doesnt work with only `--lineTrace:off --stackTrace:off`. Not sure, beside the compiler flags, what else `release` is doing but FYI

**Comment by jmgomez** [comment]
Gets worst but definitely not a `constructor` issue as this works as expected
```nim
proc print(s: string) = echo s
proc main =
  for i in 0 .. 1:
    var n = makeNimClass()
    print $n.x & " " & $n.cpp.x  #using echo directly here instead, reproduces the issue
    n.x = 123
    n.cpp.x = 321
    print $n.x & " " & $n.cpp.x
```

Update: Long story short, some paths zeroid it (sometimes it seems to be the C compiler even) and some dont. I thought it was always the case.

**Comment by demotomohiro** [comment]
> AFAIK the generated code is correct (ints are zeroed by default in C++).

No, ints and any types without constructor can have undetermined value.
https://stackoverflow.com/questions/2614809/what-is-the-default-value-for-c-class-members
https://stackoverflow.com/questions/3053057/do-i-have-to-initialize-simple-class-member-variables

Here is a simple test code and result:
https://wandbox.org/permlink/y1gmrWKFgI4Hl846

**Comment by jmgomez** [comment]
Yes, I see I was wrong. A PR initializing the fields is on its way, as stated before the reason why it doesnt happen in other parts of the code is because `result` seems to be always `{}`. That and `d:release` activates something else the inits them.

Thanks for reporting it and looking into it!
