### ISSUE TITLE
moveFile fallback should use copyFileWithPermissions instead of copyFile

### ISSUE THREAD

**Issue by kreatoo** [nim-lang/Nim#22674]
### Description

Moving files should preserve permissions.
Fallback on moveFile uses copyFile which doesn't preserve permissions on *nix systems.

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Possible Solution

use `copyFileWithPermissions` instead of `copyFile` on [moveFile](https://github.com/nim-lang/Nim/blob/devel/lib/std/private/osfiles.nim#L402)

**Comment by litlighilit** [comment]
It's added from https://github.com/nim-lang/Nim/commit/9e8308fabd8fd9dd81511f7de1d9f20970b34e7e  (which seems to just follow the logic of the Windows version with no special purpose)   
 and its code logic is kept in https://github.com/nim-lang/Nim/commit/434a7c842694469c532287319049e35340bb8494

**Comment by litlighilit** [comment]
It's added in https://github.com/nim-lang/Nim/commit/434a7c842694469c532287319049e35340bb8494

**Comment by litlighilit** [comment]
before PR,  
beware `copyFileWithPermissions`
is  `{.noWeirdTarget.}`

**Comment by litlighilit** [comment]
Can `{.noWeirdTarget.}` be handled via `when`?

**Comment by kreatoo** [comment]
IMHO, `copyFileWithPermissions` isnt a good fallback either since it doesnt preserve ownership (unlike how moving a file should) but since I dont know if theres a function in Nim about preserving ownership `copyFileWithPermissions` should do well for most cases.

**Comment by litlighilit** [comment]
see sh-command `cp`'s [doc](https://www.gnu.org/software/coreutils/manual/html_node/cp-invocation.html#cp-invocation)
> Preserve the owner and group. On most modern systems, only users with appropriate privileges may change the owner of a file, and ordinary users may preserve the group ownership of a file only if they happen to be a member of the desired group. 

So maybe `preserving ownership` isn't a usually available operation.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/22719
