### ISSUE TITLE
Nim zero clear an object contains/inherits C++ imported class when a proc return it

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#22675]
### Description

Nim zero clear all bit of an object contains/inherits class/struct imported from C++ when a proc returns it.
Some C++ classes initialize member variables to non-zero value in construtor.
If C++ class allocate heap memory and store the address to member variable in construtor, zero clearing that class causes memory leak.

Example:
testnzcpp.nim:
```nim
import std/sugar

{.emit:"""/*TYPESECTION*/
struct CppNonZero {
  int x = 123;
};
""".}

type
  CppNonZero {.importcpp, inheritable.} = object
    x: cint

  HasCpp = object
    cppnz: CppNonZero

  InheritCpp = object of CppNonZero

proc initCppNonZero: CppNonZero =
  CppNonZero()

proc initHasCpp: HasCpp =
  HasCpp()

proc ctorHasCpp: HasCpp {.constructor.} =
  discard

proc initInheritCpp: InheritCpp =
  InheritCpp()

proc ctorInheritCpp: InheritCpp {.constructor.} =
  discard

proc main =
  var cppNZ: CppNonZero
  dump cppNZ.x

  var cppNZInit = initCppNonZero()
  dump cppNZInit.x

  var hascpp: HasCpp
  dump hascpp.cppnz.x

  var hasCppInit = initHasCpp()
  dump hasCppInit.cppnz.x

  var hasCppCtor = ctorHasCpp()
  dump hasCppCtor.cppnz.x

  var inheritCpp: InheritCpp
  dump inheritCpp.x

  var inheritCppInit = initInheritCpp()
  dump inheritCppInit.x

  var inheritCppCtor = ctorInheritCpp()
  dump inheritCppCtor.x

main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5f13e15e0a6f90c462a71cd30addc677f688c4dc
active boot switches: -d:release

### Current Output

```text
cppNZ.x = 123
cppNZInit.x = 123
hascpp.cppnz.x = 123
hasCppInit.cppnz.x = 0
hasCppCtor.cppnz.x = 123
inheritCpp.x = 123
inheritCppInit.x = 0
inheritCppCtor.x = 123
```

### Expected Output

```text
cppNZ.x = 123
cppNZInit.x = 123
hascpp.cppnz.x = 123
hasCppInit.cppnz.x = 123
hasCppCtor.cppnz.x = 123
inheritCpp.x = 123
inheritCppInit.x = 123
inheritCppCtor.x = 123
```

### Possible Solution

Remove `nimZeroMem` when the object contains/inherits C++ class?

### Additional Information

Nim Generated C++ code:
```
N_LIB_PRIVATE N_NIMCALL(tyObject_HasCpp__czTl6AwEoxqGwrV8MEZRVw, initHasCpp__testnzcpp_u34)(void) {
	tyObject_HasCpp__czTl6AwEoxqGwrV8MEZRVw result{};
  nimZeroMem((void*)(&result), sizeof(tyObject_HasCpp__czTl6AwEoxqGwrV8MEZRVw));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initInheritCpp__testnzcpp_u57)(tyObject_InheritCpp__VPZjeC448K58zh5sMFWV9cw* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_InheritCpp__VPZjeC448K58zh5sMFWV9cw));
	popFrame();
}
```

**Comment by jmgomez** [comment]
I can take a look at it soon. Do you mind to split it in two issues though? It will be easier to iterate over the CI when things break.

**Comment by demotomohiro** [comment]
> I can take a look at it soon. Do you mind to split it in two issues though? It will be easier to iterate over the CI when things break.

Thank you!
I have splited it to following issues.

Object has C++ class:
https://github.com/nim-lang/Nim/issues/22679
Object inherits C++ class:
https://github.com/nim-lang/Nim/issues/22680

**Comment by jmgomez** [comment]
Thank you Demo, I really appreciate you taking the time to do this and how detailed they are!
