### ISSUE TITLE
Using `merge` for a macro name causes it to silently get ignored

### ISSUE THREAD

**Issue by PhilippMDoerner** [nim-lang/Nim#22676]
### Description

Merge appears to be a keyword of sorts like `export` etc. that nim claims for itself.
However, it appears that it is not supposed to act keyword-like based on my questions in the discord #internals channel.

If you write a macro and name it merge and use it as a pragma, the macro will not get called.
Instead nothing will happen, the compiler will compile and execute the code without issue - it's just that your macro gets entirely ignored and thus silently fails.

Here a minimal example:

```nim
import std/macros

macro merge*(procDef: typed): untyped =
  echo "MERGE MACRO GETS CALLED"
  return procDef

macro otherName*(procDef: typed): untyped =
  echo "OTHERNAME MACRO GETS CALLED"
  return procDef

proc mergeProc() {.merge.} = discard
proc otherProc() {.otherName.} = discard
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
"OTHERNAME MACRO GETS CALLED"
```

### Expected Output

```text
"MERGE MACRO GETS CALLED"
"OTHERNAME MACRO GETS CALLED"
```

### Additional Information

Araq mentioned that this stems from merge being an old pragma that does not do anything anymore.

Looking at [this part](https://github.com/nim-lang/Nim/blob/5f13e15e0a6f90c462a71cd30addc677f688c4dc/compiler/wordrecg.nim#L52) of the compiler (thanks SirOlaf for linking it to me!) it becomes clear that it is regarded as a Special Word.

[Here](https://github.com/nim-lang/Nim/blob/5f13e15e0a6f90c462a71cd30addc677f688c4dc/compiler/pragmas.nim#L32) it is also put into a set of proc pragmas.

The seemingly only actual use is [here](https://github.com/nim-lang/Nim/blob/5f13e15e0a6f90c462a71cd30addc677f688c4dc/compiler/pragmas.nim#L974C1-L976C21) : 

```nim
...
      of wMerge:
        # only supported for backwards compat, doesn't do anything anymore
        noVal(c, it)
...
```

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/Nim/pull/22526 which allows non-pragma special words as user pragmas

**Comment by ringabout** [comment]
I'm going to remove it since it's deprecated for more than 8 years. Though, we can always fall back to adding it to the nonPragmaWords list.
