### ISSUE TITLE
Add destructors to standard library objects

### ISSUE THREAD

**Issue by raynei86** [nim-lang/Nim#22695]
### Summary

Many standard library objects and containers still require `close()` to be called manually.
This is mostly alleviated with `defer`, but you still need to remember to close it.
This also isn't consistent with how some parallelization related modules have a `=destroy` hook.

### Description

Provide destructors for standard library modules so cleanup is done automatically.
This should also simplify many parsers in the standard library since they all use `std/streams` and need to call `close()`; they also have many short functions that just opens a stream, then closes it two lines afterwards. Having a `defer` there breaks the succinct flow.

**Comment by Araq** [comment]
That's a good idea but should be moved to the RFCs repo.

**Comment by raynei86** [comment]
Got it, moved issue to [here](https://github.com/nim-lang/RFCs/issues/534).
