### ISSUE TITLE
"undeclared identifier" when using local type in `tuple`

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#22699]
### Description

Using a local type (in this case `Private`) as a tuple field type in a generic function causes an "undeclared identifier" error when the function is called in another module.

```nim
# a.nim
import b

echo chop[bool](42)

# b.nim
type Private = distinct int

proc chop*[T](x: int): int =
    cast[int](cast[tuple[field: Private]](x))
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: ac1804aba665b34a01cb014183f8fff0ba6db738
active boot switches: -d:release

### Current Output

```text
Error: undeclared identifier: 'Private'
```

### Expected Output

```text
42
```

### Additional Information

This only seems to happen with `tuple`, not with other generic types.

**Comment by juancarlospaco** [comment]
!nim c

```nim
import temp1
echo chop[bool](42)
```

```nim
type Private = distinct int
proc chop*[T](x: int): int = cast[int](cast[tuple[field: Private]](x))
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
import temp1
echo chop[bool](42)
```

```nim
type Private = distinct int
proc chop*[T](x: int): int = cast[int](cast[tuple[field: Private]](x))
```

**Comment by metagn** [comment]
Object and tuple type nodes are ignored entirely in semgnrc (nkTupleClassTy is atomic so it's fine):

https://github.com/nim-lang/Nim/blob/cd0d0ca5304528e33eb10e87ea27936f38bfea1e/compiler/semgnrc.nim#L460-L461

Object types might be handled by the handling of type sections, but tuple types can also be declared in regular code. So this either causes the same issue or is a workaround (replacing the object type with a tuple type):

```nim
type Private = distinct int

proc chop*[T](x: int): int =
  type Foo = object
    field: Private
  cast[int](cast[Foo](x))
```
