### ISSUE TITLE
C++ mode generates bad initialization code for union type

### ISSUE THREAD

**Issue by tommo** [nim-lang/Nim#22708]
### Description

```nim
type
  Union{.union.} = object
    a:int32
    b:bool
const i = Union(b:true)
echo i
```
C++ backend generates incorrect initialization code for this ( see below ).
C backend works fine.

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: arm64]
Compiled at 2023-09-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f5b90f886501862bd27d4e0e8244e2f7f0ebc2a
active boot switches: -d:release -d:danger

### Current Output

```text
.................................................................../Volumes/prj/pil/test/cpptest/_build/debug/.nimcache/@munionbug.nim.cpp:60:93: error: excess elements in union initializer
N_LIB_PRIVATE NIM_CONST tyObject_Union__TAj7qkZEjaueQFP7zLlauw i__unionbug_u4 = {((NI32)0), NIM_TRUE}
                                                                                            ^~~~~~~~
/Volumes/prj/dev/nimdev/lib/nimbase.h:320:18: note: expanded from macro 'NIM_TRUE'
#define NIM_TRUE true
                 ^~~~
1 error generated.

Error: execution of an external compiler program 'clang++ -c -std=gnu++17 -funsigned-char  -pthread -g   -I/Volumes/prj/dev/nimdev/lib -I/Volumes/prj/pil/test/cpptest -o /Volumes/prj/pil/test/cpptest/_build/debug/.nimcache/@munionbug.nim.cpp.o /Volumes/prj/pil/test/cpptest/_build/debug/.nimcache/@munionbug.nim.cpp' failed with exit code: 1
```

**Comment by juancarlospaco** [comment]
!nim cpp

```nim
type Union {.union.} = object
  a: int32
  b: bool
const i = Union(b: true)
echo i
```

**Comment by jmgomez** [comment]
@juancarlospaco is the action updated to take a look at the OK codegen? 

!nim cpp

Edit: How do you suppose to trigger it?

**Comment by juancarlospaco** [comment]
@jmgomez Docs with examples linked at https://github.com/juancarlospaco/nimrun-action#nimrun-action

I have not updated it yet.

**Comment by jmgomez** [comment]
!nim cpp
```nim

type Union {.union.} = object
  a: int32
  b: bool
const i = Union(b: true)
echo i

```

**Comment by jmgomez** [comment]
This is not a C++ (only) issue: 
C fails silently with unions too:
```nim
type
  Union{.union.} = object
    a:int32
    b:bool
let unionVar {.exportc.} = Union(b:true)
echo unionVar #(a: 1, b: true)

proc test() = 
  const unionConst {.exportc.} = Union(b:true)
  echo unionConst #(a: 0, b: false)

test()
````

**Comment by juancarlospaco** [comment]
See https://github.com/nim-lang/Nim/issues/22708#issuecomment-1734570803 the bisect found an interesting commit. 🤔

**Comment by jmgomez** [comment]
> See [#22708 (comment)](https://github.com/nim-lang/Nim/issues/22708#issuecomment-1734570803) the bisect found an interesting commit. 🤔

wdym? I took a look at the sources before commenting and `tfUnion` is barely handled. Probably it "worked" as a side effect of something else not being implemented.
