### ISSUE TITLE
Error on syncio.nim

### ISSUE THREAD

**Issue by aftalavera** [nim-lang/Nim#22700]
### Description

Error when trying to write a file bigger than 2147483647. 

when defined(windows):
  proc writeWindows(f: File; s: string; doRaise = false) =
    # Don't ask why but the 'printf' family of function is the only thing
    # that writes utf-8 strings reliably on Windows. At least on my Win 10
    # machine. We also enable setConsoleOutputCP(65001) now by default.
    # But we cannot call printf directly as the string might contain \0.
    # So we have to loop over all the sections separated by potential \0s.
    var i = c_fprintf(f, "%s", s)
    while i < s.len:
      if s[i] == '\0':
        let w = c_fputc('\0', f)
        if w != 0:
          if doRaise: raiseEIO("cannot write string to file")
          break
        inc i
      else:
        let w = c_fprintf(f, "%s", unsafeAddr s[i])
        if w <= 0:
          if doRaise: raiseEIO("cannot write string to file")
          break
        inc i, w

### Nim Version

2.0

### Current Output

```text
Error: unhandled exception: over- or underflow [OverflowDefect]
```

### Possible Solution

When changing 
var i = c_fprintf(f, "%s", s) to
var i:int64 c_fprintf(f, "%s", s)

the problem seems to be fixed

**Comment by litlighilit** [comment]
So it's just about `i` is overflow  
(`i` is of type `cint`, which is likely to be of size 32, so can't be larger than 2147483647).   

And your `Possible Solution`:

> var i:int64 = c_fprintf(f, "%s", s)

does solve this.

**Comment by aftalavera** [comment]
Thanks for your email
