### ISSUE TITLE
`parseEnum()` is (sometimes) confused by indirect types or aliases

### ISSUE THREAD

**Issue by fsh** [nim-lang/Nim#22726]
### Description

`parseEnum` from `std/strutils` isn't able to resolve the enum type in (some?) cases involving a `type x = y` in generic functions (? I am unsure of the exact conditions; see examples below).

The problem seems to be in `genEnumCaseStmt` in `std/enumutils`: my _guess_ is it should be using `getType()` rather than `getTypeInst()`?

### Minimalish Examples

```nim
import std/strutils

type SomeEnum = enum A, B, C

# Implicitly generic using Nim's "type classes":
proc assignEnum(dest: var enum, s: string) =
  type ty = typeof(dest)
  dest = parseEnum[ty](s) # Error: Expected a node of kind nnkEnumTy, got nnkCall
  # ...

  # Confusingly, the following works though:
  # dest = parseEnum[typeof(dest)](s)

  # Of course the dream would be for the type/logic system to infer it:
  # dest = parseEnum(s)

var v: SomeEnum
v.assignEnum("A") # fails

# Explicitly generic:
proc assignEnum2[T: enum](dest: var T, s: string) =
  type ty = T
  dest = parseEnum[ty](s) # Error: Expected a node of kind nnkEnumTy, got nnkSym

  # But this works:
  # dest = parseEnum[T](s)

v.assignEnum2("B") # fails
```

What is confusing me most is that the "type-indirection" does not seem to happen outside of generics (why?):

```nim
# ... continuation from above

proc foo(ex: SomeEnum): auto =
  type ty = typeof(ex)
  return parseEnum[ty]("C")

echo foo(v) # Works.

type ty2 = typeof(v)
echo parseEnum[ty2]("C") # Also works.
```

### Other Problems

1. The final error refers to the line of the `type ty = ...` definition, not to the `parseEnum` line; arguably it should show a report from `parseEnum` with the error?

2. The error messages are also rather "technical" and unfriendly (being done by `expectKind`).

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f5b90f886501862bd27d4e0e8244e2f7f0ebc2a
active boot switches: -d:release

### Possible Solution

Maybe use `getType()` instead of `getTypeInst()`? (I'm unsure of their internals.) Or do a loop to resolve the various `Sym`s and `TypeOfExpr`s, similar to how `std/typetraits`' `genericParams()` works? (I.e. why isn't that function using `getType()`?)

**Comment by ringabout** [comment]
!nim c
```nim
import std/strutils

type SomeEnum = enum A, B, C

# Implicitly generic using Nim's "type classes":
proc assignEnum(dest: var enum, s: string) =
  type ty = typeof(dest)
  dest = parseEnum[ty](s) # Error: Expected a node of kind nnkEnumTy, got nnkCall
  # ...

  # Confusingly, the following works though:
  # dest = parseEnum[typeof(dest)](s)

  # Of course the dream would be for the type/logic system to infer it:
  # dest = parseEnum(s)

var v: SomeEnum
v.assignEnum("A") # fails

# Explicitly generic:
proc assignEnum2[T: enum](dest: var T, s: string) =
  type ty = T
  dest = parseEnum[ty](s) # Error: Expected a node of kind nnkEnumTy, got nnkSym

  # But this works:
  # dest = parseEnum[T](s)

v.assignEnum2("B") # fails
```

**Comment by metagn** [comment]
Yes, it should probably be `getTypeImpl` instead of `getTypeInst`. Even `type ty = SomeEnum` fails.

Edit: Changing `getTypeInst` doesn't fix it.
