### ISSUE TITLE
parsexml and htmlparser not parsing google.com

### ISSUE THREAD

**Issue by runvnc** [nim-lang/Nim#2276]
Hello, I tried using a few Nim standard modules like parsexml and htmlparser on http://google.com.  There were some problems with class names showing up in the tag name and then later on in the document random bits of Javascript coming in as tag (element) names.

I did not know exactly why it was happening and I didn't want google.com to defeat me so I made a sort of naive parser of my own.  I could not make it work until I specifically acounted for `<script>` tags and the contents of the script tags (like `<` inside of script).

Here is my rough code https://github.com/runvnc/pwl/blob/master/it.nim

I'm not sure if accounting for `<script` is necessary but it might be.

**Comment by GULPF** [comment]
Not reproducible anymore.
