### ISSUE TITLE
Can't use a macro on proc typeclass

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#22765]
### Description

Regression from 1.6:
```nim
macro hey(node: untyped): untyped = node
proc test1 = discard
let callback: proc {.hey.} = test1
```
Compiles on 1.6, devel:
`Error: invalid pragma: hey`

### Nim Version

a7a0cfe8eb5942d799b4b7e2fdf26bcb9ff8ffab

### Additional Information

```nim
macro hey(node: untyped): untyped = node
proc test1: int = 5
let callback: proc: int {.hey.} = test1
```
works on all versions

**Comment by Vindaar** [comment]
Note that it does work, if you're explicit about the return type being `void`:

```nim
macro hey(node: untyped): untyped = node
proc test1 = discard
let callback: proc: void {.hey.} = test1
```

**Comment by metagn** [comment]
`proc {.hey.}` is the `proc` typeclass with the `hey` pragma (like `proc {.closure.}`) since #21629. Previously it was just ignored during parsing and just became the `proc` typeclass. You can also do `proc () {.hey.}` along with `proc: void`.

So, this is kind of a feature request, allowing macros on the `proc`/`iterator` typeclasses.

**Comment by Menduist** [comment]
It was not ignored
```nim
import macros
macro hey(x: untyped): untyped =
  x.params[0] = ident"string"
  x

proc zz: string = "hi" 
let xx: proc {.hey.} = zz
```
Compiles on 1.6.14, so it is a regression

**Comment by metagn** [comment]
It was ignored.

```nim
import macros
macro hey(x: untyped): untyped {.error: "ignored".} =
  doAssert false
  error("ignored")
  x


proc zz: string = "hi" 
let xx: proc {.hey.} = zz
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
import macros
macro hey(x: untyped): untyped {.error: "ignored".} =
  doAssert false
  error("ignored")
  x

proc zz: string = "hi"
let xx: proc {.hey.} = zz
```

**Comment by Menduist** [comment]
Ok, I got confused by the fact that
```nim
proc zz: string = "hi"
let xx: proc = zz
```
works on its own (it's quite confusing that `proc` and `proc: int` have such different meanings)

So I guess this is a duplicate of #22036
