### ISSUE TITLE
Different results on orc/refc or global/procedure scope with orc

### ISSUE THREAD

**Issue by lassejansson** [nim-lang/Nim#22787]
### Description

Upgraded to nim 2 and some code stopped working.

Isolated it to:

```
var s:seq[string]

for i in 0..3:
  s.add ("test" & $i)
  s.add ("test" & $i)

var lastname:string

for i in s:
  var name = i[0..4]

  if name != lastname:
    echo "NEW:",name
  else:
    echo name,">",lastname

  lastname = name     
```

var name = i[0..4]

The problem seems to be in the i[0..4] part with orc.

https://play.nim-lang.org/#ix=4I8a

### Nim Version

2.0.0

### Current Output

```text
NEW:test0
test0>test0
test1>test1
test1>test1
test2>test2
test2>test2
test3>test3
test3>test3
```

### Expected Output

```text
NEW:test0
test0>test0
NEW:test1
test1>test1
NEW:test2
test2>test2
NEW:test3
test3>test3
```

### Additional Information

Expected output is generated with -refc or if the code is written in global scope.
Wrong output is generated with -orc if the code is written in a procedure.

**Comment by ringabout** [comment]
works with `--cursorinference:off`, related to https://github.com/nim-lang/Nim/issues/15883 because if you swap the order of `name != lastname`, it works as expected.
