### ISSUE TITLE
nimsuggest unhandled exception on `echo "hello"`

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/Nim#22816]
### Description

```nim
# src/main.nim
echo "hello"
```
This code crashes nimsuggest.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-10-11
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d790112ea4600c847fed830171333fde308421a3
active boot switches: -d:release

### Current Output

```text
nimsuggest src/main.nim
> chk src/main.nim
chk     skUnknown               Hint    ???     0       -1      ">>> (toplevel): import(dirty): /home/doongjohn/projects/exp-nim/src/main.nim [Processing]"     0
fatal.nim(53)            sysFatal
Error: unhandled exception: liftdestructors.nim(624, 5) `t.destructor != nil`  [AssertionDefect]
```

### Expected Output

```text
no error
```

**Comment by ire4ever1190** [comment]
Can't reproduce. Do you still run into this problem with latest devel?

**Comment by doongjohn** [comment]
It is working as expected with the latest devel.
