### ISSUE TITLE
Invalid type checking for two instances of the same Generic type

### ISSUE THREAD

**Issue by can-lehmann** [nim-lang/Nim#22826]
### Description

When instancing the `Table` type with the same key type and value types `T` and `SomeGenericThatUsesTable[T]`, typechecking fails.

Minimal example

```nim
import std/tables

var a: Table[string, float]

type Value*[T] = object
  table: Table[string, Value[T]]

discard toTable({"a": Value[float]()})
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-10-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: f5d70e7fa7195658e3200f71a1653e07fe81275a
active boot switches: -d:release

### Current Output

```text
PATH/main.nim(8, 16) template/generic instantiation of `toTable` from here
NIM_PATH/lib/pure/collections/tables.nim(313, 45) template/generic instantiation of `[]=` from here
NIM_PATH/lib/pure/collections/tableimpl.nim(61, 38) Error: type mismatch: got 'sink Value[system.float]' for 'val' but expected 'float'
```

### Expected Output

```text
Compiles correctly
```

### Additional Information

It seems to be present at least in devel, 2.0.0, 1.6.8 and 1.6.0.

**Comment by ringabout** [comment]
!nim c
```nim
import std/tables

var a: Table[string, float]

type Value*[T] = object
  table: Table[string, Value[T]]

discard toTable({"a": Value[float]()})
```
