### ISSUE TITLE
Error: cannot evaluate at compile time: unameRes

### ISSUE THREAD

**Issue by theAkito** [nim-lang/Nim#22825]
### Description

With such code.

```nim
when not (Alpine.detectOs): echo "hello"
```

The following error is raised.

```
/home/user/.choosenim/toolchains/nim-2.0.0/lib/pure/distros.nim(151, 52) Error: cannot evaluate at compile time: unameRes
```

### Nim Version

```
Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release
```

### Current Output

```text
/home/user/.choosenim/toolchains/nim-2.0.0/lib/pure/distros.nim(151, 52) Error: cannot evaluate at compile time: unameRes
```

### Expected Output

```text
Should work fine.
```

### Possible Solution

Fix the `unameRes` & similar fields.

https://github.com/nim-lang/Nim/blob/f5d70e7fa7195658e3200f71a1653e07fe81275a/lib/pure/distros.nim#L143

https://github.com/nim-lang/Nim/blob/f5d70e7fa7195658e3200f71a1653e07fe81275a/lib/pure/distros.nim#L150

### Additional Information

I wasn't able to build the latest devel, to test, whether the issue still exists.

```
Error: invalid package name: /home/user/.nimble/pkgs2/smtp-0.1.0-df9380a905e6f2f9f4228474077ca15f2ccbde29
```

I remember, there was some issue with this package, because it was moved away from the standard library.

**Comment by Araq** [comment]
Use `if` instead of `when`.
