### ISSUE TITLE
New styled concepts doesn't work with generic recursive types when T is specified explicitly

### ISSUE THREAD

**Issue by saffage** [nim-lang/Nim#22839]
### Description

The following example produces a compilation error.

```nim
type
  Comparable = concept
    proc `<`(a, b: Self): bool
  
  # Works with this.
  # Comparable = concept a
  #   `<`(a, a) is bool
  
  # Doesn't work with the new style concept.
  Node[T: Comparable] = object
    data: T
    next: ref Node[T]
    
  # Works without specifying a concept.
  # Node[T] = object
  #   data: T
  #   next: ref Node[T]
```

### Nim Version

Nim Compiler Version 1.6.16 [Windows: amd64]
Compiled at 2023-10-10
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

---

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

---

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2023-10-17
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
Error: cannot instantiate Node{None} [type declared in C:\Projects\TestNim\recursive_concept.nim(13, 3)]        
got: <typedesc[T: Comparable]>
but expected: <T: Comparable>
```

### Expected Output

```text
Successful compilation
```

**Comment by metagn** [comment]
Doesn't need to be recursive, just needs to match a constraint again:

```nim
type
  Comparable = concept
    proc `<`(a, b: Self): bool
  Foo[T: Comparable] = object
  Node[T: Comparable] = Foo[T]
```

The problem is the type `Comparable` doesn't match itself, it only checks for concrete types
