### ISSUE TITLE
high(float) is infinity rather than a finite value

### ISSUE THREAD

**Issue by ggb-sw** [nim-lang/Nim#22849]
### Description

Because `high(float)` is returned as `inf` it means that `high(float) - 1` is also infinity (i.e. you can subtract from a number and still get the same number you started with).

      #!/usr/bin/env -S nim r
      
      # Nim Compiler Version 2.0.0 [Linux: amd64]
      
      proc high_minus_one(ty: type) =
          let val = high(ty)
          let val1 = val - 1
          let cmp = (val1 < val)
          echo "Type: ", type(val1), " -- val1(", val1,") < val(",val,") = ", cmp, " where val1 = val - 1"
      
      high_minus_one(int32)
      high_minus_one(float)

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Expected Output

```text
Type: int32 -- val1(2147483646) < val(2147483647) = true where val1 = val - 1
Type: float -- val1(inf) < val(inf) = false where val1 = val - 1
```

**Comment by metagn** [comment]
Isn't it better that for all float values `x`, `x <= high(float)` holds?

**Comment by Araq** [comment]
Works as designed. The rationale behind it is that algorithms like `min` and `max` work properly when starting with `low/high(T)` and so for this Infinity works well.
