### ISSUE TITLE
Inconsisitent way uint8 and int8 are processed

### ISSUE THREAD

**Issue by ggb-sw** [nim-lang/Nim#22847]
### Description

The following short bit of code raises an exception when using int8 as the target, but merely corrupts the output for uint8.

        #!/usr/bin/env -S nim r
        
        # Nim Compiler Version 2.0.0 [Linux: amd64]
        
        let x = 70000
        # Change this to be int8 rather than uint 8 and you get an 
        # value out of range exception raised
        # As a uint8 it just corrupts the output when assigning x
        var y: uint8
        let z = 20
        
        echo "x is y => ", x is type y
        echo "y is x => ", y is type x
        y = (type y)z # OK every time
        echo "Value y[z] => ", y, ", should be => ", z
        y = (type y)x # Exception for int8, but corrupt for uint8
        echo "Value y[x] => ", y, ", should be => ", x
        `

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

**Comment by beef331** [comment]
Unsigned integers explicitly do not overflow, signed integers do. If you want to prevent overflow use signed integers.

**Comment by ggb-sw** [comment]
It is not so much whether I want one thing or the other, it is simply that when writing generic code it becomes a problem that they behave differently.  It also seems to me like exactly the kind of non-obvious behaviour that can lead to obtuse code bugs.

For any language that strives for safety it seems to be exactly the kind of thing to avoid.

If it is as designed then I will just have to live with it, but it does seem like a poor design decision (unless creating inconsistent behaviour was the goal).

I can see advantages to both checking for overflow and not checking for overflow.  Checking provides safety, but at a cost to performance.  But I find very little justification for being safe and costly for signed and unsafe but fast for unsigned.

**Comment by Araq** [comment]
Unsigned integers wrap around.
