### ISSUE TITLE
SIGSEGV when slicing `string` or `seq[T]` with index out of range

### ISSUE THREAD

**Issue by derekdai** [nim-lang/Nim#22852]
### Description

Run following code + devel version of Nim compiler, it SIGSEGV instead of throwing `RangeDefect`
```nim
echo [0][2..^2]
```

### Nim Version

devel

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
Error: unhandled exception: value out of range: -2 notin 0 .. 9223372036854775807 [RangeDefect]
```

### Additional Information

ARC/ORC specific.

**Comment by ringabout** [comment]
! nim c --gc:arc
```nim
echo [0][1..^1]
```

**Comment by ringabout** [comment]
!nim c --gc:arc
```nim
echo [0][1..^1]
```

**Comment by ringabout** [comment]
@derekdai Hi, I cannot reproduce the rangedefect with your example.

**Comment by derekdai** [comment]
Sorry, it should be `echo [0][2..^2]`, my bad.

**Comment by ringabout** [comment]
!nim c --gc:arc
```nim
echo [0][2..^2]
```

**Comment by derekdai** [comment]
@ringabout The latest bisect results are as expected. However, the devel version terminates with SIGSEGV instead of RangeDefect, which is the issue reported in this issue.

**Comment by ringabout** [comment]
I have investigated the case using `git bisect`. It seems that 8f5b90f886501862bd27d4e0e8244e2f7f0ebc2a was the cause
