### ISSUE TITLE
Compiler thinks StringStream operations produce side effects 

### ISSUE THREAD

**Issue by foresto** [nim-lang/Nim#22853]
### Description

The compiler rejects any func that calls StringStream read/write methods, claiming that it can have side effects. This is surprising because (unless I'm misunderstanding something) part of StringStream's utility is that it is self-contained.

Consequently, it is impossible to use StringStream for purposes to which it is otherwise well-suited, such as a func that uses only memory-safe operations to parse or build string-encapsulated struct fields.

```nim
include std/streams

func getint8(s: string): int8 =
    newStringStream(s).readInt8

echo getint8("@")
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-10-19
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
.......................................................................
/tmp/ssfunc.nim(3, 6) Error: 'getint8' can have side effects
> /tmp/ssfunc.nim(4, 23) Hint: 'getint8' calls `.sideEffect` 'readInt8'
>> /usr/lib/nim/lib/pure/streams.nim(538, 6) Hint: 'readInt8' called by 'getint8'
>>> /usr/lib/nim/lib/pure/streams.nim(555, 7) Hint: 'readInt8' calls `.sideEffect` 'read'
>>>> /usr/lib/nim/lib/pure/streams.nim(409, 6) Hint: 'read' called by 'readInt8'
>>>>> /usr/lib/nim/lib/pure/streams.nim(425, 14) Hint: 'read' calls `.sideEffect` 'readData'
>>>>>> /usr/lib/nim/lib/pure/streams.nim(229, 6) Hint: 'readData' called by 'read'
>>>>>>> /usr/lib/nim/lib/pure/streams.nim(242, 26) Hint: 'readData' calls routine via pointer indirection
```

### Expected Output

```text
no errors
```

### Additional Information

One can work around the problem by writing a proc instead of a func, of course, but that rather defeats the value of using funcs. :)

**Comment by Araq** [comment]
In what world are streams "no side effect"...

**Comment by foresto** [comment]
As far as I can tell from the StringStream documentation, it only changes local data (the string it contains), not anything external like a file or global objects. That makes sense, as similar data structures in other languages do the same.

The docs say this:

> The noSideEffect pragma is used to mark a proc/iterator that can have only side effects through parameters. This means that the proc/iterator only changes locations that are reachable from its parameters and the return value only depends on the parameters.

Does converting a parameter to a temporary local variable (a StringStream) and then returning data from that variable not qualify? That would be surprising. If that is the case, then I think an explanation would be worth including in the docs.

**Comment by foresto** [comment]
Perhaps this will make the issue more clear:

```nim
include std/streams

type StringBuf = ref object
    data: string
func newStringBuf(s: string): StringBuf =
    new(result)
    result.data = s
func readInt16(sb: StringBuf): uint16 =
    var tmp: uint16
    tmp = sb.data[0].uint16 or sb.data[1].uint16 shl 8
    return tmp

func getint16_good(s: string): uint16 =  # this compiles
    s.newStringBuf.readInt16

func getint16_bad(s: string): int16 =  # this fails to compile
    s.newStringStream.readInt16

echo getint16_good("AB")
echo getint16_bad("AB")
```

**Comment by beef331** [comment]
The `std/stream` api uses pointer procs which lose type information, so it's assumed all are side effectful. A generic interface variation of streams would be a nice thing to have.

**Comment by foresto** [comment]
> The std/stream api uses pointer procs which lose type information, so it's assumed all are side effectful. 

Yes, I suspected the cause was something like that.

> A generic interface variation of streams would be a nice thing to have.

Indeed, as the current interface is leaking an implementation detail that generates false alarms, making StringStream somewhat less useful than it should be.

Can this issue be re-opened? I can rephrase the title if it will help.

**Comment by beef331** [comment]
> StringStream somewhat less useful than it should be.

To be fair you can always do the ugly `{.cast(noSideEffect).}:` if you really really want to use `func`.

**Comment by foresto** [comment]
> In what world are streams "no side effect"...

In what word is reading from a local variable considered a side effect?

> you can always do the ugly {.cast(noSideEffect).}: if you really really want to use func.

I reported this not because I need help with it, but to help improve Nim, by documenting a defect in its library. The rude and dismissive response was discouraging.

**Comment by Araq** [comment]
"Help" is a pull request, as an issue it's not helping anybody.

**Comment by Varriount** [comment]
> "Help" is a pull request, as an issue it's not helping anybody.

@Araq That's neither a fair nor constructive comment, and honestly comes off as insulting. Not everyone has the time or expertise to fix these problems, especially when they might turn out to be intended behavior. At least filing an issue makes it known that this behavior is unexpected or undesirable. A better response would be to give a description of how to go about implementing a fix, and request a PR. 

@foresto Technically, from an OS perspective, every memory access has [potential for side effects](https://devblogs.microsoft.com/oldnewthing/20060927-07/?p=29563). Whether that's the precise reason Nim behaves in this way, I don't know.

**Comment by Araq** [comment]
> Whether that's the precise reason Nim behaves in this way, I don't know.

If only it was documented somewhere in a document. What was the name again? "Spec-safisfaction"? "Womanual"? "Mankindual"? Who knows...
