### ISSUE TITLE
Calling delete on an empty sequence results in invalid sequence

### ISSUE THREAD

**Issue by elcritch** [nim-lang/Nim#22856]
### Description

Calling delete with 0 on an empty sequence results in a negative sequence len.

```sh
Nim Compiler Version 2.0.1 [MacOSX: arm64] at /Users/jaremycreechley/.asdf/shims/nim
nim> var x: seq[int]
nim> x.len()
0 == type int
nim> x.delete(0)
nim> x.len()
-1 == type int
nim> x.delete(0)
nim> x.len()
-2 == type int
nim> 
```

### Nim Version

2.0.0, 2.0.1

### Current Output

```text
var x: seq[int]
x.delete(0)
assert x.len() > 0
```

### Expected Output

```text
Non-negative sequence len
```

**Comment by elcritch** [comment]
It's good on the 1.4.8 release, but fails on the 1.6.14 release.

**Comment by ringabout** [comment]
>   .. note:: With `-d:nimStrictDelete`, an index error is produced when the index passed
    to it was out of bounds. `-d:nimStrictDelete` will become the default
    in upcoming versions.

It raises as expected with  `-d:nimStrictDelete`. Perhaps, we should enable it.

**Comment by elcritch** [comment]
Yah, whatever fixes it. That's a pretty bad behavior. 🤕 Also, it breaks adds to the seq as well.
