### ISSUE TITLE
Cannot getContent with httpClient for specific website

### ISSUE THREAD

**Issue by some-avail** [nim-lang/Nim#22862]
### Description

While I can retrieve the website in Firefox, I get a  HttpRequestError with httpClient.

It applies for website:
https://distrowatch.com/weekly.php?issue=20200622#devuan

### Nim Version

2.0.0

### Current Output

```text
ref Exception(parent: nil, name: "HttpRequestError", msg: "400 Bad Request", trace: @[StackTraceEntry(procname: "test_00330_httpclient_website_ophalen", line: 12, filename: "/media/OnsSpul/1klein/1joris/k1-onderwerpen/computer/Programmeren/nimtaal/testnim/test_00330_httpclient_website_ophalen.nim"), StackTraceEntry(procname: "getContent", line: 1225, filename: "/home/bruik/.choosenim/toolchains/nim-2.0.0/lib/pure/httpclient.nim"), StackTraceEntry(procname: "responseContent", line: 1203, filename: "/home/bruik/.choosenim/toolchains/nim-2.0.0/lib/pure/httpclient.nim")], up: nil)
****End exception****
```

### Expected Output

```text
Website-content
```

### Possible Solution

Apparently a exception is raised at  responseContent.
But somehow firefox can retrieve the content.

**Comment by ghost** [comment]
Not a Nim bug - DistroWatch's web server seems to be unable to parse the default user-agent that `std/httpclient` uses despite it being fully valid:
```
$ curl -H "User-Agent: Nim httpclient/2.1.1" "https://distrowatch.com/weekly.php?issue=20200622#devuan"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

To "fix" (workaround for the broken web-server) you can set a working User-Agent in the code manually:
```nim
import std/httpclient

proc main = 
    let c = newHttpClient()
    c.headers["User-Agent"] = "curl/8.4.0"
    let content = c.getContent("https://distrowatch.com/weekly.php?issue=20200622#devuan")
    echo content[0..10]

main()
```

**Comment by ghost** [comment]
Hm, reading on it a bit more, seems like HTTP specification does mention User-Agent specifically, so the current Nim httpclient user-agent will be parsed as separate entities ("Nim" and "httpclient/2.1.1"), but the web server shouldn't **refuse** the request anyway. So, even if it's not a bug, maybe it'll be better to change the User-Agent to something like `Nim-httpclient/2.1.1` so it conforms to the spec?

See e.g. https://github.com/Azure/azure-sdk-for-node/issues/694 https://github.com/elastic/beats/issues/14747

**Comment by some-avail** [comment]
Thanks. Seems logical to me.

Based on:
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#library_and_net_tool_ua_strings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#library_and_net_tool_ua_strings)
and:
[https://www.rfc-editor.org/rfc/rfc9110#field.user-agent](https://www.rfc-editor.org/rfc/rfc9110#field.user-agent)

So the line:
const defUserAgent* = "Nim httpclient/" & NimVersion

would become for example:
const defUserAgent* = "Nim-httpclient/" & NimVersion
or ?:
const defUserAgent* = "NimHttpclient/" & NimVersion

Generally speaking I suppose a website can block any undesired or obscure user-agent.
