### ISSUE TITLE
cstring modification example on Nim Manual cause SIGSEGV

### ISSUE THREAD

**Issue by sxq112358** [nim-lang/Nim#22867]
### Description

When running this code it gives a SIGSEGV
```nim
proc main()=
  var x = "123456"
  var s: cstring = x
  s[0] = 'u' # This is ok #<---SIGSEGV here
main()
```
If adding a line to mutate the string before then it runs fine.
```nim
proc main()=
  var x = "123456"
  x[2] = x[2]
  var s: cstring = x
  s[0] = 'u' # This is ok
main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-10-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 10c3ab626941d9c1ec69a2921696f4b7d0c2a6ac
active boot switches: -d:release

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
no SIGSEGV when running
```

**Comment by ghost** [comment]
Yeah, it should be updated to something like this:
```nim
proc main()=
  var x = "123456"
  prepareMutation(x)
  var s: cstring = x
  s[0] = 'u' # This is ok #<---SIGSEGV here
main()
```

In https://github.com/nim-lang/Nim/blob/devel/doc/manual.md?plain=1#L1496

**Comment by ringabout** [comment]
Should `convStrToCStr` call `nimPrepareStrMutationV2`? Since `cstring` simply points to the buffer of a string that could be a constant, which causes troubles when `cstring` is modified.

**Comment by Araq** [comment]
Nah, the manual should be updated. The vast majority of conversions to cstring does not need mutability.

**Comment by ringabout** [comment]
Okay

**Comment by skandalfo** [comment]
Wouldn't the logical thing be to have distinct mutable and immutable cstring types?
