### ISSUE TITLE
`{.noSideEffect.}` leads to double-free when inlining `template` in `--mm:orc`

### ISSUE THREAD

**Issue by etan-status** [nim-lang/Nim#22874]
### Description

When a template contains a `{.noSideEffect.}` block, and it allocates memory within it, e.g., by growing a `seq`, and the resulting value is then immediately passed to another function or used in construction of a new object, under `--mm:orc`, the generated C code will contain multiple `colontmp` variables. They get assigned using regular C assignment, and then both copies get `eqdestroy`'ed, resulting in double free because `eqcopy` wasn't used for copying from one `colontmp` to the other while maintaining ref counts.

```nim
type
  Foo = object
    f: seq[byte]

  FooWrapper = object
    x: Foo

template create(): auto =
  {.noSideEffect.}:
    var v: Foo
    v.f.setLen(123)
    v

discard FooWrapper(x:
  create())
```

Enable additional assertions in the allocator to visualize the problem, or simply `echo` the allocated seq, it will contain garbage values:

```sh
nim c --mm:orc -d:useGcAssert -d:useSysAssert -r test
```

### Nim Version

```
Nim Compiler Version 1.6.16 [MacOSX: amd64]
Compiled at 2023-10-26
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 3c9b68dc157804885b14a1984efc25e8b7cc861d
active boot switches: -d:release
```

### Current Output

```text
[SYSASSERT] rawDealloc: negative occupied memory (case B)
```

### Expected Output

```text
No memory corruption
```

### Possible Solution

Surrounding usage with `block` works. e.g., this is fine:

```nim
discard FooWrapper(x: block:
  create())
```

Also, getting rid of `{.noSideEffect.}`, using `--mm:refc`, using a `func` instead of `template`, and so on, also work around the problem.

### Additional Information

_Seems_ to be fine in `version-2-0` Nim, but not sure if this is by chance (as in, problem will appear if the code is more complex), or if there is actually some fix that is simply not backported to `version-1-6`.

**Comment by metagn** [comment]
#22088 which fixed #22058 was [backported to the 1.6 branch](https://github.com/nim-lang/Nim/commit/7b9b173476d03d0cb035f4ccb01803146b1bb9c6) but then [reverted](https://github.com/nim-lang/Nim/commit/503e7b708b1558b909c8630ca4b4d8699046dc8d), so it is possible this is fixed in 2.0 with #22088.

**Comment by ringabout** [comment]
@narimiran Hello, could you try to incorporate https://github.com/nim-lang/Nim/pull/22088 into the version-1-6 branch when you have some free time?

If there is any emerging issue, feel free to ping me.

**Comment by narimiran** [comment]
> @narimiran Hello, could you try to incorporate https://github.com/nim-lang/Nim/pull/22088 into the version-1-6 branch when you have some free time?

I've tried to backport it (both originally and now), but it breaks CIs:
```
injectdestructors.nim(714, 10) Error: undeclared identifier: 'whichPragma'
```

If you can make a separate PR targeting `version-1-6`, I would appreciate it.

**Comment by ringabout** [comment]
Here you are ⇾ https://github.com/nim-lang/Nim/commit/75c36636210a4db2526597d1821e18232964252f Hopefully, it won't break anything.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/commit/47010a391967b52f4f9fe294b0a0fc8f530b9852
