### ISSUE TITLE
Unable to display single backslash between backticks in documentation

### ISSUE THREAD

**Issue by ggb-sw** [nim-lang/Nim#22875]
### Description

It may be the following is as designed, although I have not found in the documentation where this is so.

```
#!/usr/bin/env -S nim -f doc
## :File: test2.nim
##
#  Test 1
## Double backslash (`\\`) in backtick quotes shows double backslash.
##
# End test 1
# Test 2
## Single backslash (`\`) in backtick quotes loses second backtick and causes
## error that treats entire block as in backtick quotes.
# end test2
##
## How does one display a single backslash in backtick quotes?`
```
### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

**Comment by Araq** [comment]
Feel free to read about Nim's documentation generator and its RST syntax.
