### ISSUE TITLE
Problems with spaces between backticks

### ISSUE THREAD

**Issue by ggb-sw** [nim-lang/Nim#22876]
### Description

Since it does show an error in nim doc, so maybe it is as designed, although I am not sure where it is documented or how I would achieve the ends desired.
```
#!/usr/bin/env -S nim -f doc
## :File: test1.nim
##
## Problems with spaces in backtick quoted text.
##
# start test 1
##
## This is a line with a backtick quoted A (`A`)
##
# End test 1
# Start test 2
##
## This is a line with a backtick quoted A with spaces (` A `)
##
# End test 2
# Test 2 causes error message in nim doc, and causes entire block to be
# treated as backtick quoted.
#
# Test 1 only backtick quotes the letter 'A', which is what is desired.
#
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

**Comment by Araq** [comment]
Feel free to read about Nim's documentation generator and its RST syntax.
