### ISSUE TITLE
Improve osproc module's API

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2288]
Reading properly from a `Process` currently requires some pretty convoluted code. Add a procedure which abstracts this.

**Comment by Varriount** [comment]
If any major API changes are planned, it would probably be worth it to come up with a design overview (I'm thinking something like an enhancement proposal, but... less. Like a sketch, or something.

**Comment by dom96** [comment]
No API changes are needed. Just an addition of some helper procedures.

**Comment by dom96** [comment]
Also specifying precisely how to read data from a process successfully.

**Comment by Araq** [comment]
You know that I only touch this code when I'm drunk.

**Comment by dom96** [comment]
I'll get some Vodka then.

**Comment by dom96** [comment]
I think this falls under the stdlib review and may consist of some breaking changes so I will mark it as high priority.

**Comment by Araq** [comment]
> I think this falls under the stdlib review and may consist of some breaking changes so I will mark it as high priority.

No... we don't have the competence to do anything like that.

**Comment by Araq** [comment]
``osproc`` is mostly fine, bugs have been fixed, APIs have been clarified.

**Comment by dom96** [comment]
Let me review it, please.

**Comment by Araq** [comment]
The API is fine, review it and open specific issues when you feel like it but this issue tracker is not your personal TODO tracker.
