### ISSUE TITLE
Procedure with non-void return type warning

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#2289]
Could a warning be shown if a procedure has a declared non-void return type
but doesn't assign to 'result' or use a explicit 'return' statement?

Example:

``` nim
proc someProcThatReturns(): int =
    #no "result = ..." or "return someInt" in the entire proc
```

Compiler: 0.10.3

**Comment by Araq** [comment]
Sure but it's always initialized anyway. It's fully deterministic, so testing your code helps. ;-)

**Comment by yglukhov** [comment]
This code can no longer be compiled, requiring some explicit statement. So this can be closed.

**Comment by ozra** [comment]
@Araq - is @yglukhov conclusion right - so this can be closed?

**Comment by yglukhov** [comment]
Well, sorry, what I meant that the proc requires at least some statement to compile. E.g. discard would work in this case. So strictly speaking that's not what @matkuki wants.

**Comment by Araq** [comment]
Closing it works as designed, I don't like the design either so there is an RFC to correct this design. Eventually.
