### ISSUE TITLE
"Error: borrow from proc return type mismatch: 'lent string'" when borrowing `[]` from Table

### ISSUE THREAD

**Issue by dxxb** [nim-lang/Nim#22902]
### Description

The following code fails to compile with `devel` but used to work fine until a few weeks ago (and still compiles on 2.0)

!nim c
```nim
import std/tables

type
  DistinctTable = distinct Table[int, int]

proc `[]`(t: DistinctTable; key: int): int {.borrow.}
```

### Nim Version

$ nim -v
Nim Compiler Version 2.1.1 [MacOSX: amd64]
Compiled at 2023-10-31
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: f61311f7a0f1a4c2fab1eeaa747654d4281bc56b
active boot switches: -d:release

### Current Output

```text
borrow_mismatch.nim(7, 1) Error: borrow from proc return type mismatch: 'lent int'
```

### Expected Output

```text
Compile succeeds
```

### Additional Information

The following code compiles just fine with the compiler version mentioned above:
``` nim
  type
    OrigType[T] = T
    DistinctType = distinct OrigType[int]

  proc testProc[T](o: OrigType[T]): T = T(o)
  proc testProc(o: DistinctType): int {.borrow.}
```

**Comment by scroot** [comment]
```nim
import std/tables
type
  DistinctTable = distinct Table[int, int]

proc `[]`(t: DistinctTable; key: int): lent int =
  discard
```

**Comment by dxxb** [comment]
!nim c
``` nim
import std/tables

type
  DistinctTable = distinct Table[int, int]

proc `[]`(t: DistinctTable; key: int): int {.borrow.}
```

**Comment by ringabout** [comment]
!nim c
```nim
import std/tables

type
  DistinctTable = distinct Table[int, int]

proc `[]`(t: DistinctTable; key: int): int {.borrow.}
```

**Comment by metagn** [comment]
Does changing the return type to `lent int` not work? Because if it does, then this is a bugfix if anything.

**Comment by dbrignoli** [comment]
> Does changing the return type to lent int not work?

No, it doesn't work even with lent int.

**Comment by ringabout** [comment]
Well, it is caused by https://github.com/nim-lang/Nim/commit/9d7acd001f268e2b9dab9228ca5e22bf75028704 but the pre-existing culprit is that borrow didn't handle lent properly.

**Comment by ringabout** [comment]
Okay, I found the cause. I'm working on it.

related to https://github.com/nim-lang/Nim/issues/22673
