### ISSUE TITLE
`nimsuggest` runs at 100% CPU load.

### ISSUE THREAD

**Issue by k4nedito** [nim-lang/Nim#22911]
### Description

System: Ubuntu 22.04.3 LTS

`nimsuggest` eats 100% of the random CPU core. Nothing needs to be added IMHO, this has been an issue since 2019! ([111](https://github.com/nim-lang/nimsuggest/issues/111), [11679](https://github.com/nim-lang/Nim/issues/11679), [93](https://github.com/saem/vscode-nim/issues/93)) and developers must know exactly what's going on. 

I've seen some solutions, mostly a mishmash of some workarounds and cryptic config files, someone also blamed the VSC extension, which is plausible as I have [this extension installed](https://marketplace.visualstudio.com/items?itemName=kosz78.nim) but Im not in a position where I want to spend time debugging it.

It's worth mentioning that VSC was long closed when I saw these processes in htop after the system started lagging seriously and no substantial work was done, no libraries were installed, just happened after running very basic, almost empty code from fresh install. 

![Screenshot from 2023-11-04 14-35-48](https://github.com/nim-lang/Nim/assets/68785244/10333543-4077-4f25-a366-fc947d3a74a4)

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c

**Comment by Araq** [comment]
> and developers must know exactly what's going on.

Indeed.
