### ISSUE TITLE
About custom destroy hook

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#22935]
### Description

Q1: When I customize the destructor, do I need to call `=destroy` for each field? After my simple test, it seems that nim will not call `=destroy` for me.

Q2: Some structures that come with the standard library do not support active calls to `=destroy`, such as Deque (Error: type mismatch). A memory leak may occur here.

This is my test code:
```nim
import std/deques

type
  InnerObj = object
    data: int

  Inner = ref InnerObj

  SthObj = object
    obj2: Inner
    d2: seq[Inner]
    d3: Deque[Inner]

proc `=destroy`(o: InnerObj) =
  echo "InnerObj ", o.data

proc `=destroy`(o: SthObj) =
  echo "SthObj"

  `=destroy`(o.obj2)
  `=destroy`(o.d2)
  # `=destroy`(o.d3) # Error: type mismatch

var v = SthObj(obj2: Inner(data: 1))
v.d2.add(Inner(data: 2))
v.d3.addLast(Inner(data: 3))

```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-11-02
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 40e33dec45b98e1c5385f844e241011a8351d364
active boot switches: -d:release

### Current Output

```text
SthObj
InnerObj 1
InnerObj 2
```

### Expected Output

```text
SthObj
InnerObj 1
InnerObj 2
InnerObj 3
```

### Additional Information

I'm not very familiar with memory management options, so I used the default settings for my tests.

```
[root@haoyu cbuf]# nim c tdtor.nim
[root@haoyu cbuf]# ./tdtor 
SthObj
InnerObj 1
InnerObj 2
```

After uncommenting:
```
[root@haoyu cbuf]# nim c tdtor.nim
/root/repos/cbuf/tdtor.nim(22, 13) Error: type mismatch
Expression: `=destroy`(o.d3)
  [1] o.d3: Deque[tdtor.Inner]

Expected one of (first mismatch at [position]):
[1] proc `=destroy`(o: InnerObj)
[1] proc `=destroy`(o: SthObj)
[1] proc `=destroy`(x: string)
[1] proc `=destroy`[T](x: ref T)
[1] proc `=destroy`[T](x: seq[T])
[1] proc `=destroy`[T](x: var T)
```

**Comment by beef331** [comment]
1) Yes
2) A workaround is as follows
```nim
import std/deques

type
  InnerObj = object
    data: int

  Inner = ref InnerObj

  SthObj = object
    obj2: Inner
    d2: seq[Inner]
    d3: Deque[Inner]

proc `=destroy`(o: InnerObj) =
  echo "InnerObj ", o.data

proc `=destroy`(o: SthObj) =
  echo "SthObj"

  `=destroy`(o.obj2)
  `=destroy`(o.d2)
  `=destroy`(o.d3.addr[])

var v = SthObj(obj2: Inner(data: 1))
v.d2.add(Inner(data: 2))
v.d3.addLast(Inner(data: 3))
```

**Comment by haoyu234** [comment]
Thank you very much for your reply, it is very useful to me. @beef331 

Maybe Q1 should be clearly stated in the documentation. I have read [the description of `=destroy`](https://nim-lang.org/docs/destructors.html#lifetimeminustracking-hooks-nimeqdestroy-hook) several times, and it does not mention what Q1 mentioned.

**Comment by beef331** [comment]
To echo what will be said "PRs welcome"
