### ISSUE TITLE
Type section typed AST does not retain postfix node

### ISSUE THREAD

**Issue by Mycsina** [nim-lang/Nim#22933]
### Description

Using `expandMacros`  only displays the `*` character on object fields.
```nim
expandMacros:
    type
        A* = object
            a*: int
        B = object
            b: int
    proc foo*(bar: int): string =
        return "baz"
```

I also tried adding a `echo repr(n)` to the `toStrLit` function that `expandMacros` uses but the output was the same.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-11-11
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 52784f32bbb6c764eb67a1abdbbbd9f54dc6030e
active boot switches: -d:release

### Current Output

```text
type
  A = object
    a*: int

  B = object
    b: int

proc foo(bar: int): string =
  return "baz"

iterator foo2(bar2: int): string =
  yield "baz"
```

### Expected Output

```text
type
  A* = object
    a*: int

  B = object
    b: int

proc foo*(bar: int): string =
  return "baz"

iterator foo2*(bar2: int): string =
  yield "baz"
```

### Possible Solution

None

### Additional Information

Versions 2.0.0 and 1.6.6 gave the same output.

**Comment by metagn** [comment]
Typed AST of type sections do not retain the postfix nodes on the LHS (just becomes nnkSym), not a rendering problem, can confirm with `macro foo(a: typed) = echo a.treeRepr`

**Comment by Mycsina** [comment]
Oh okay, thought it might be a bug instead. Closing the issue then.

**Comment by metagn** [comment]
Did not mean it was intended behavior, sorry.

**Comment by elcritch** [comment]
Ran into this issue as well. It's annoying because you think you've screwed up the template or macros.
