### ISSUE TITLE
Unable to write to files inside a proc

### ISSUE THREAD

**Issue by andre-de-lorde** [nim-lang/Nim#22931]
### Description

I noticed that i couldnt write to a file inside a proc, and reproduced the bug here:

```nim
proc brokenWrite(): void =
   writeFile("BrokenWrite.txt","Test")

writeFile("WorkingWrite.txt","Test")
brokenWrite()
``` 

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: amd64]

### Current Output

```text
Only the file named WorkingWrite.txt is written to
```

### Expected Output

```text
Both files are written to with the text "Test"
```

**Comment by andre-de-lorde** [comment]
This applies to opening the file with fmWrite and attempting to write to it as well

**Comment by SolitudeSF** [comment]
Is this the full snippet? You arent running the proc.

**Comment by andre-de-lorde** [comment]
oh oops, i am running the proc. I didnt copy paste the last part lol

**Comment by andre-de-lorde** [comment]
Okay, tried this again, i dont know what was broken about it before but it fixed itself.
I'm very confused.
