### ISSUE TITLE
`std/options` don’t consider closure iterators to be pointer types

### ISSUE THREAD

**Issue by SirNickolas** [nim-lang/Nim#22932]
### Description

https://github.com/nim-lang/Nim/blob/4d11d0619d11d8aecdaff998981efcd054de9760/lib/pure/options.nim#L83-L88

We see `proc` here but not `iterator`. I’m suspicious about such asymmetry.

```nim
import std/options

var it = iterator: int = discard
assert it.option.isSome # Passes.
it = nil
assert it.option.isNone # Fails; equivalent to `it.some.isNone`.
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
Error: unhandled exception: /home/nickolas/c/test/a.nim(6, 1) `it.option.isNone`  [AssertionDefect]
```

### Possible Solution

Append `| iterator` to the definition of `SomePointer`.

**Comment by ringabout** [comment]
!nim c
```nim
import std/options

var it = iterator: int = discard
assert it.option.isSome # Passes.
it = nil
assert it.option.isNone 
```
