### ISSUE TITLE
Pushing `used` suppresses the `XDeclaredButNotUsed` hint for some identifiers, but not others

### ISSUE THREAD

**Issue by ee7** [nim-lang/Nim#22939]
### Example

```nim
{.push used.}
const a = 42
proc b = echo "hi"
{.pop.}
```

### Current behavior

The compiler outputs an `XDeclaredButNotUsed` hint for `a` (but not `b`):

```
/tmp/used.nim(2, 7) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
```

### Expected behavior

No such hint for `a` or `b`.

### Nim Version

Nim 2.0.0 and devel (https://github.com/nim-lang/Nim/commit/57ffeafda016a9772f6548d462f8d9acdcad33bd).

### Additional Information

The below works as expected, to suppress both hints:

```Nim
const a {.used.} = 42
proc b {.used.} = echo "hi"
```

Issue https://github.com/nim-lang/Nim/issues/4044 was closed 5 years ago, citing the above workaround for

```nim
{.push hint[XDeclaredButNotUsed]: off.}
const a = 42
proc b = echo "hi"
{.pop.}
```

which still produces the `XDeclaredButNotUsed` hint for both `a` and `b`.

The issue in the example was [reported in the #main channel](https://irclogs.nim-lang.org/14-11-2023.html#16:39:34).

**Comment by ringabout** [comment]
It's a subtle bug. I discovered it yesterday in https://github.com/nim-lang/Nim/issues/22913.

```nim
{.push used.}
let a {.deprecated.} = 42
proc b = echo "hi"
{.pop.}
```
Somehow for var/let/const sections, it needs a pre-existing pragma to make push in effect. Let me investigate it later.

**Comment by ringabout** [comment]
Yeah, the reason is that `implicitPragmas` is not applied to Identifiers withouu pragmas.
