### ISSUE TITLE
Incorrect hostCPU variable on MacOS

### ISSUE THREAD

**Issue by vanyle** [nim-lang/Nim#22946]
### Description

The `hostCPU` variable is `amd64` when compiling a Nim program on an M1 Mac. It should be `arm64`.

Program to reproduce:
```nim
static:
    echo hostCPU
```

`nim r file.nim`

When compiling with `--cpu:arm64`, the `hostCPU` is correct once again. \
Using `file`, we can check that the executable producted in an `Mach-O 64-bit executable arm64` despite what the `hostCPU` variable claims. 

### Nim Version

Nim Compiler Version 2.0.0 [MacOSX: amd64]
Compiled at 2023-09-14
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
CPU: amd64
```

### Expected Output

```text
CPU: arm64
```

### Possible Solution

Properly define the `arm64` variable so that check in `platforms.nim` passes.

### Additional Information

Currently, when no `hostOS` information is provided on the command line, the Nim compiler uses the `hostOS` information from when it was compiled as can be seen in `platforms.nim`:
```
proc setTargetFromSystem*(t: var Target) =
  t.hostOS = nameToOS(system.hostOS)
  t.hostCPU = nameToCPU(system.hostCPU)
  t.setTarget(t.hostOS, t.hostCPU)
```

I'd argue this behavior is incorrect. The CPU type should be checked here at run-time using the `uname -m` command. While this issue only affects M1 Macs, it could soon affect ARM Windows users as ARM on Windows gets more widespread.

**Comment by Araq** [comment]
Works for me but then I bootstrapped Nim with arm64 once and ever since then it was an arm64 compiler. How did you get your Nim?

**Comment by vanyle** [comment]
I installed it using `choosenim`. I installed choosenim using `curl https://nim-lang.org/choosenim/init.sh -sSf | sh`.

Choosenim version: `choosenim v0.8.4 (2022-07-06 14:57:51) [macosx/amd64]`

I think that my nim compiler runs using rosetta and thinks that cpu is amd64.

**Comment by Araq** [comment]
Iirc choosenim doesn't support ARM, yes.

**Comment by vanyle** [comment]
What do you think about using something like `execProcess("uname -m")` inside the `setTargetFromSystem` function (and maybe caching the result for performance) when the system is posix compliant ?

**Comment by Araq** [comment]
That assumes that you got the CPU architecture wrong but somehow the OS detection good enough to know that `uname -m` makes sense. Seems rather silly and makes things even harder to trace.

**Comment by vanyle** [comment]
The `--cpu` should still take precedence over everything else, but the architecture stored inside `system.hostCPU` can be wrong.

If I compile Nim for `amd64` and run the compiler on a Mac with Rosetta, I should expect the hostCPU to still say `arm64` even though the `system.hostOS` variable of the Nim compiler should be `amd64` as the compiler was compiled for an `x86_64` CPU.

As a temporary workaround, I can detect the CPU myself using `staticExec`, but in that case, I don't have access to the `--cpu` value.

For context, I am writing a SIMD library that generates neon or avx instructions based on the CPU detected.
`when defined(arm64):` does not work as it is always false.
`const targetCPU* = staticExec("uname -m")` works, but it ignores the `--cpu` switch.

**Comment by viega** [comment]
@vanyle you're definitely running the compiler in Rosetta, so detection SHOULD report you're running on an x86, because you are.

If you don't want to build the compiler yourself, you can definitely use some trickery to determine whether you're in the VM, and set things up to cross-compile properly. 

We have had people hit this problem, so we did automate away the problem, and you're welcome to use it. From nimscript (config.nims) you can use the module linked below to do the detection (in `setupTargetArch()`), or do the arch detection and set up the compiler flags by calling `applyCommonLinkOptions()`. 

https://github.com/crashappsec/nimutils/blob/dev/nimutils/nimscript.nim
