### ISSUE TITLE
`compiles(e: untyped)` false positive for module `re` 

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#22979]
### Description

`compiles re"(-|_|\/|\.|\s)"` returns `true` but it should be `false`

here a unittest that fails 

```nim
import unittest
from re import re

suite "compiletime":
  test "PASS but it should fail":
    check not compiles re"(-|_|\/|\.|\s)"

  test "Doesn't compile": # .choosenim/toolchains/nim-2.0.0/lib/impure/re.nim(115, 28) Error: VM does not support 'cast' from tySet to tyInt32
    static:
      discard re"(-|_|\/|\.|\s)"
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
`compiles re"(-|_|\/|\.|\s)" was true` for first test

`.choosenim/toolchains/nim-2.0.0/lib/impure/re.nim(115, 28) Error: VM does not support 'cast' from tySet to tyInt32` for second test
```

### Expected Output

```text
`compiles re"(-|_|\/|\.|\s)"` should be `false`
```

**Comment by beef331** [comment]
What is the issue here, the following compiles?
```nim
from re import re
let expr = re"(-|_|\/|\.|\s)"
```

**Comment by arkanoid87** [comment]
it doesn't run at compile time, but compiles(...) returns true

**Comment by beef331** [comment]
Right but you did not do `compiles(static(...))`. `compiles` checks whether the code compiles and it does.

```nim
jason@jason-desktop /tmp> cat test.nim
from re import re
echo compiles(re"(-|_|\/|\.|\s)")
echo compiles(static(re"(-|_|\/|\.|\s)"))
echo compiles(static(100))
jason@jason-desktop /tmp> nim c -r --verbosity:0 ./test.nim
true
false
true
```

**Comment by arkanoid87** [comment]
then it's not an issue! `compiles(static(thanks))`!
