### ISSUE TITLE
`base64.encode` and `base64.encodeMime` have unnecessary side effects

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#22985]
### Description

```nim
import std/base64
func f() = discard base64.encodeMime("")
func g() = discard base64.encode("")
```

There's nothing intrinsically side-effecty about these functions, since they're pure sequence to sequence mappings based on (effectively, which is the implementation issue) reading out of one of two constant lookup tables:
https://github.com/nim-lang/Nim/blob/502a4486aeb8d0a5dcdf86540522d3dc16960536/lib/pure/base64.nim#L69-L75
and
https://github.com/nim-lang/Nim/blob/502a4486aeb8d0a5dcdf86540522d3dc16960536/lib/pure/base64.nim#L136-L144
are where the issue lies. The side effect analysis is correct, because `encodeImpl` uses this approach where it needs a pointer and therefore can't reliably use one of the truly `const` `cb64safeVM` / `cb64VM` but one of the nominally variable `cb64safe` / `cb64`.

### Nim Version

```
Nim Compiler Version 1.6.17 [Linux: amd64]
Compiled at 2023-11-25
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6f0cad684358fc3b15463bead13684437c7d4798
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.1 [Linux: amd64]
Compiled at 2023-11-25
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 489dd89a45d8c354c8b69b9e6f5ba379250c472a
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-11-25
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 502a4486aeb8d0a5dcdf86540522d3dc16960536
active boot switches: -d:release
```

### Current Output

```text
/tmp/r.nim(2, 6) Error: 'f' can have side effects
> /tmp/r.nim(2, 37) Hint: 'f' calls `.sideEffect` 'encodeMime'
>> NimDevel/lib/pure/base64.nim(168, 6) Hint: 'encodeMime' called by 'f'
```

### Expected Output

```text
Compiles
```

**Comment by Araq** [comment]
Seems easy to fix. Can you create a PR please?

**Comment by tersec** [comment]
Sure, will do.
