### ISSUE TITLE
newSeqUninit -> CT Error: opcCastIntToPtr

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/Nim#23006]
### Description

`const seq = newSeqUninit[byte](8)`

### Current Output

```text
nim\lib\system.nim(1622, 9) newSeqUninit
nim\lib\system.nim(1622, 9) Error: opcCastIntToPtr: regs[rb].kind: rkRegisterAddr
```

### Expected Output

```text
no error
```

### Nim Version

Nightly build on 2023-11-28 for branch devel
nim-2.1.1-windows_x64.zip

nim -v
```
Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2023-11-28
```

### Additional Information

compiled with the cmdLine
`nim compile test_newSeqUninit.nim`
on the gcc version :
`winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r3`

**Comment by ringabout** [comment]
Well, its precursor `newSeqUninitialized` didn't support VM neither. I don't think it's  
beneficial to implement it for VM. But we could provide a better error messages for VM.

Fine, I will take the implementaion of `newStringUninit`.
