### ISSUE TITLE
Problem removing cstring unsafe conversion warning

### ISSUE THREAD

**Issue by zqqw** [nim-lang/Nim#23001]
### Description

```

import options, posix

var time = (posix.Time) 1700000000
var ltime: Tm
discard localtime_r(time, ltime)
var buf1: array[100, char]
let res = strftime(addr(buf1), buf1.len, "%c", ltime)
#let res = strftime(addr(cstring(buf1)), buf1.len, "%c", ltime)
#let res = strftime(cstring(addr(buf1)), buf1.len, "%c", ltime)
echo "res = ", res, "\nbuf1 = ", buf1

```

### Nim Version

Tried latest Nim git earlier today, but it has been like this for a while.

### Current Output

```text
Warning: unsafe conversion to 'cstring' from 'ptr array[0..99, char]'; this will become a compile time error in the future [PtrToCstringConv]
```

### Additional Information

https://forum.nim-lang.org/t/8608#55905

That solution doesn't seem to work here, I tried a few things with no luck, I would have expected one of the commented lines to have helped. Is this strftime line not being interpreted correctly by Nim, or is something else causing the problem?

**Comment by ringabout** [comment]
`cast[cstring]` should work for your case

```nim
let res = strftime(cast[cstring](addr(buf1)), buf1.len, "%c", ltime)
```

But perhaps the error messages should provide an explicit recommendation for the general way of `cast[cstring]`.

**Comment by ringabout** [comment]
It was in the changelog
```
- Pointer to `cstring` conversions now trigger a `[PtrToCstringConv]` warning.
  This warning will become an error in future versions! Use a `cast` operation
  like `cast[cstring](x)` instead.
```

**Comment by zqqw** [comment]
Thank you, that does fix the warning and works as before.
