### ISSUE TITLE
strutils.multiReplace replaces left to right, not in order of arguments

### ISSUE THREAD

**Issue by jhereth** [nim-lang/Nim#23016]
### Description

The [documentation](https://nim-lang.org/docs/strutils.html#multiReplace%2Cstring%2Cvarargs%5B%5D) for `multiReplace` says

> The order of the replacements does matter. Earlier replacements are preferred over later replacements in the argument list.

I understand this to mean that a multiReplace is equivalent to iterating through the argument list and doing a replace for each pair.

This is not happening

## Example

```
import std/strutils


echo "twone".multiReplace(@[("one", "a"), ("two", "b")])
echo "twone".replace("one", "a").replace("two", "b")
echo "twone".multiReplace(@[("two", "b"), ("one", "a")])
```

Expected Output:

```
twa
twa
bne
```

Actual Output:
```
bne
twa
bne
```

### Nim Version

Nim Compiler Version 2.0.0 [MacOSX: arm64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise

(also tested on https://play.nim-lang.org/ with other v1.6.16)

### Current Output

```text
bne
twa
bne
```

### Expected Output

```text
twa
twa
bne
```

### Possible Solution

1. Adjust documentation or
2. Switch inner and outer loop [here](https://github.com/nim-lang/Nim/blob/5dfa1345fa2c046a42730a6357b12245e5ee3f06/lib/pure/strutils.nim#L2302-L2310)

### Additional Information

I'm fine with both solutions - I was just surprised that `multiReplace` worked other than advertised.

**Comment by ringabout** [comment]
!nim c
```nim
import std/strutils

doAssert "twone".multiReplace(@[("one", "a"), ("two", "b")]) == "twa"
```

**Comment by Araq** [comment]
The implementation is correct and the documentation needs to be updated. But the documentation is not incorrect either, just your interpretation of it.

**Comment by jhereth** [comment]
> The implementation is correct and the documentation needs to be updated. But the documentation is not incorrect either, just your interpretation of it.

It seems like.

The explicit mention of the order of the argument list made me think that these are processed in order _first_. Something like

> Replacements are done left to right in the string. If at a given position multiple replacements match, earlier replacements are preferred over later replacements in the argument list. 

would be less ambiguous.

Example

```
echo "ab".multiReplace(@[("a", "1"), ("ax", "2")])
echo "ab".multiReplace(@[("ab", "2"), ("a", "1")])
```

gives

```
1b
2
```

@Araq I can submit a PR for the doc change. But feel free to close this issue if you think it's not worth the effort.

**Comment by Araq** [comment]
PR please.

**Comment by jhereth** [comment]
> PR please.

@Araq  Here it is: #23022
