### ISSUE TITLE
Local timezone not detected / unable to set in module times

### ISSUE THREAD

**Issue by JorySchossau** [nim-lang/Nim#2301]
It is impossible to convert times from the underlying UTC to any timezone other than UTC, because it is impossible to change the local timezone from UTC.
Mac OSX Yosemite.
Nim 0.10.3

```nim
import times
echo($getTzname()) 
```
Results in not "EST" or "GMT" or even "UTC" but "WILDABBR" for which comments in localtime.c (ftp://ftp.iana.org/tz/code/localtime.c) imply the c library is being used incorrectly.

[Original Nim Forum thread](http://forum.nim-lang.org/t/1002)

**Comment by oderwat** [comment]
I pointed out that one need to call `posix.tzset()` before `times.getTzname()` workes (at least on os x). I think that should at least be in the documentation.

**Comment by dom96** [comment]
The ``times`` module should call it. Create a PR for this if it fixes it on Mac OS X.

**Comment by dom96** [comment]
Fixed via #2309. Tested to be sure on El Capitan and it works.
