### ISSUE TITLE
`openArray` doesn't match for `array`/`seq` in a concept

### ISSUE THREAD

**Issue by ire4ever1190** [nim-lang/Nim#23011]
### Description

Having a proc that takes `openArray` doesn't implement a concept for `seq` and `array`

```nim
type
  Foo = concept
    proc bar(x: Self)

# openArray should match for both array/seq so that
# the proc doesn't need to be implemented twice
proc bar[T](x: openArray[T]) = discard

assert openArray[int] is Foo # This passes
assert array[3, int] is Foo # Fails
assert seq[int] is Foo # Fails
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-11-29
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 30cf33f04dfb768182accb3ad35ec6364c998664
active boot switches: -d:release

### Current Output

```text
Assertion fails for last two checks
```

### Expected Output

```text
All assertions pass
```

**Comment by shirleyquirk** [comment]
new-style concepts are still a work in progress.

until then, you can:
```nim
type
  Foo = concept c
    bar(c)
```

**Comment by Araq** [comment]
Well neither `array` nor `seq` has a `bar` proc so I think the compiler is correct.
