### ISSUE TITLE
Error: a case selecting discriminator 'k' with value 'a.k' appears in the object construction, but the field(s)  are in conflict with this value.

### ISSUE THREAD

**Issue by inv2004** [nim-lang/Nim#23024]
### Description

```nim
type
  K = enum A, B
  KK = enum C, D
  T = object
    case k: K
    of A: discard
    of B:
      case kk: KK
      of C: discard
      of D:
        d = 100

let a = T(k: B)
echo T(k: a.k, kk: D)
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]

### Current Output

```text
Error: a case selecting discriminator 'k' with value 'a.k' appears in the object construction, but the field(s)  are in conflict with this value.
```

### Expected Output

```text
T(k: B, kk: D)
or maybe runtime discriminator error
```

### Possible Solution

spread operator would be much better:
```nim
let a = T(k:B)
let b = T(kk:D, ..a)
echo b
```

### Additional Information

`d = 100` is not a root cause, but can limit amount of solutions

**Comment by metagn** [comment]
Simplified:

```nim
type
  K = enum A, B
  T = object
    case k: K
    of A: discard
    of B:
      x: int

let a = T(k: B)
echo T(k: a.k, x: 123)
```

This is more of a limitation of the strictness of object constructors (which is probably there for a reason) than a bug. It's very hard for the compiler to know at compile time that `a.k` is B. You can do something like:

```nim
var b = T(k: a.k)
b.x = 123
```

Also, is there a reason you're nesting case object branches rather than just creating a separate case object? That would probably be much easier to work with.

**Comment by Araq** [comment]
No bug here.

**Comment by inv2004** [comment]
@metagn 
I can extend it a bit. The few points I wanted to show:
1) The issue is about confusing message, the fields are not in conflict, but the runtime discriminant detection problem
2) The main problem I have - I want to change the `kind` field or to recreate object from the same type with another discriminant and default values and have some problems with it. If you have any macros which can do it - please let me know

I think that I can copy default values with template, but I have to generate default(T) with correct discriminant or several discriminants
