### ISSUE TITLE
gctest segfaults with --gc:markandsweep on x86_64

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2305]
Compiling with `nim --linetrace:on --stacktrace:on -d:release c --gc:markandsweep tests/gc/gctest.nim`. Segfaults:

```
Traceback (most recent call last)
gctest.nim(201)          gctest
gc_ms.nim(582)           GC_fullCollect
gc_ms.nim(554)           collectCT
gc_ms.nim(542)           collectCTBody
gc_ms.nim(379)           sweep
alloc.nim(334)           isCell
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

This is on Linux x86_64.

**Comment by def-** [comment]
By now this also fails without `-d:release`.

**Comment by def-** [comment]
This used to work in 0.10.2

**Comment by def-** [comment]
Works on 32bit x86.

**Comment by rbehrends** [comment]
This is probably not a bug per se, but caused by `n.data` being freed before `n` and the finalizer breaking as a result. Changing the test to either not access `n.data` in the finalizer or storing it as a cstring in the shared heap avoids the crash.

**Comment by yglukhov** [comment]
Is it a valid usecase to access fields subjected to gc in a finalizer?
