### ISSUE TITLE
`std/random` initRand() has a double identical entry in nim-lang.org/docs

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/Nim#23051]
https://nim-lang.org/docs/random.html#initRand%2Cint64

https://nim-lang.org/docs/random.html#initRand%2Cint64_2

the second one can be deleted , it is identical to the first .

**Comment by ringabout** [comment]
It seems to be a pretty weird regression since 1.6.0

**Comment by ringabout** [comment]
I see,  `export initRand` caused the problem

**Comment by dreamflow** [comment]
https://nim-lang.org/docs/random.html#initRand%2Cint64

https://nim-lang.org/docs/random.html#initRand%2Cint64_2

the second unnecessary double entry is still there .
the fixes didn't got through to
https://nim-lang.org/docs/random.html .
