### ISSUE TITLE
nim doc doesn't work when calling =destroy(x: var seq[T]) in =destroy(x: Foo)

### ISSUE THREAD

**Issue by Clonkk** [nim-lang/Nim#23065]
### Description

```nim
type
  ## Foo type
  Foo* = object
    s: seq[int]

proc `=destroy`(foo: Foo) =
  `=destroy`(foo.s)

```

Compiling ``nim c|cpp foo.nim`` works. Trying to generate documentation using ``nim doc foo.nim`` fails.

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
[...]/foo.nim(7, 13) Error: type mismatch
Expression: `=destroy`(foo.s)
  [1] foo.s: seq[int]

Expected one of (first mismatch at [position]):
[1] proc `=destroy`(foo: Foo)
[1] proc `=destroy`[T](x: var T)
```

### Expected Output

If the code compiles, then the documentation generation should too. Either both should fail or both should work.

**Comment by ringabout** [comment]
Probably, it is a bug of documentation generation: `nim doc --mm:orc  test6.nim` seems to work for me

**Comment by Clonkk** [comment]
I thought --mm:orc was the default configuration if you specified nothing.

Anyway, thanks for the workaround
