### ISSUE TITLE
`sha2` & `sha3` not in nim-lang.org/docs

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/Nim#23076]
first hit of the google search for : `nim sha`
is `src/checksums/sha1` https://nim-lang.org/docs/sha1.html
that's very good 🙂
but on that page are the dead links
`sha2 module` -> https://nim-lang.org/docs/sha2.html
`sha3 module` -> https://nim-lang.org/docs/sha3.html

the sha2 & sha3 docs are available on
https://nim-lang.github.io/checksums/src/checksums/sha2.html
https://nim-lang.github.io/checksums/src/checksums/sha3.html
but not findable via a google search .
to find them one has to know , to go there via
https://github.com/nim-lang/checksums
to https://nim-lang.github.io/checksums/src/checksums/sha1.html
( = mirror page of https://nim-lang.org/docs/sha1.html )

**Comment by ire4ever1190** [comment]
Think this was fixed by #22453

- https://nim-lang.github.io/Nim/sha2.html
- https://nim-lang.github.io/Nim/sha3.html

The nim-lang.org links should work again next stable release

**Comment by dreamflow** [comment]
on https://nim-lang.org/docs/sha1.html
the 2 links are still dead :
`sha2 module` -> https://nim-lang.org/docs/sha2.html
`sha3 module` -> https://nim-lang.org/docs/sha3.html
