### ISSUE TITLE
Parser does not correspond to grammar for `concept`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23085]
### Description

https://github.com/nim-lang/Nim/blob/9648d97a8dab053067e2c50b2f5b0d7c3650d5e3/compiler/parser.nim#L2196

>  #| conceptParam = ('var' | 'out')? symbol

according to grammar, a conceptParam is limited to a few tokens but the actual parser accepts a much wider range

### Nim Version

devel

**Comment by metagn** [comment]
Also the concept parameter `out x` seems to parse the same as `var x` (this line predates the new out type):

https://github.com/nim-lang/Nim/blob/9648d97a8dab053067e2c50b2f5b0d7c3650d5e3/compiler/parser.nim#L2192

**Comment by silly-carbon** [comment]
Hi @arnetheduck @metagn 

I'd like to try to solve this issue. But as I can see from the codebase, other symbols other than `var` & `out` are also supported, e.g., `ptr`, `ref`, `static`, `type`.
But I can see from this link (https://nim-lang.org/docs/manual_experimental.html#concepts):
> You can apply any of the standard type modifiers such as var, ref, ptr and static to denote a more specific type of instance

It seems that those symbols are supported as described in the doc listed above, just the grammar files need to be updated.

Could you please advise whether we need to change the grammar files (to add more symbols like `ptr`, `ref`, `static`, `type`. IMHO, this is more feasible),  
or to change the codebase(to remove support of `ptr`, `ref`, `static`, `type`)?

**Comment by arnetheduck** [comment]
well, the grammar, parser and AST for concepts is .. experimental as a whole at best - its indentation rules generally deviate from the language, keywords such as `type` are used in an irregular way compared to the rest of the language etc.

I think there are deeper questions to resolve than this grammar quirk before venturing further.

**Comment by silly-carbon** [comment]
Thanks very much for your responses. Could you please share more suggestions on this?

________________________________

**Comment by metagn** [comment]
> Could you please advise whether we need to change the grammar files 

The comments in the `parser.nim` file starting with `#|` are turned into the grammar documentation file when executing the parser file as the main module, i.e. `nim r compiler/parser.nim`. So to change the wrong line in the grammar, one would change the comment in this line:

https://github.com/nim-lang/Nim/blob/9648d97a8dab053067e2c50b2f5b0d7c3650d5e3/compiler/parser.nim#L2208

to say `('var' | 'out' | 'ptr' | 'ref' | 'static' | 'type')`, then run `nim r compiler/parser.nim`.

A separate issue exists where this line:

https://github.com/nim-lang/Nim/blob/9648d97a8dab053067e2c50b2f5b0d7c3650d5e3/compiler/parser.nim#L2192

needs to be split into `of tkVar: nkVarTy` and `of tkOut: nkOutTy` (`nkOutTy` is new).
