### ISSUE TITLE
Docgen: Search results may be outside of the viewport

### ISSUE THREAD

**Issue by ruuda** [nim-lang/Nim#23103]
### Description

In the generated documentation, for example on <https://nim-lang.org/docs/sequtils.html>, when you type in the search box to the left, the search results appear at the top of the page. If you are currently viewing the middle of the page, and type in the search box, then it appears as if nothing happens. In fact it is producing search results, they are just not visible. This behavior occurs in both Firefox and Chromium.

I’ve been trying to learn Nim for the past two weeks, and I thought the search function was broken. Only today I realized that it works, but I need to scroll to the top of the page to see the search results.

### Nim Version

The version deployed to https://nim-lang.org/docs as of 2023-12-19. <https://nim-lang.org/docs/manual.html> says _Version: 2.0.2_.

### Current Output

```text
When I type in the search box and the top of the page is not visible, nothing appears to happen.
```

### Expected Output

```text
When I type in the search box, I see search results as I type, regardless of scroll position.
```

### Possible Solution

A very crude solution is to apply a `position: fixed` style to the `div.search_results` element, though that breaks many other things.

**Comment by ire4ever1190** [comment]
Devel docs does sorta have a fix (See: https://nim-lang.github.io/Nim/sequtils.html)

**Comment by ire4ever1190** [comment]
Stable docs have this fix, issue can be closed I think
