### ISSUE TITLE
Type mismatch error when importing strutils on platforms where ints are less then 32-bits wide

### ISSUE THREAD

**Issue by Abathargh** [nim-lang/Nim#23125]
### Description

Importing strutils or any other module that imports strutils on systems where `int` is less than 32-bits wide causes a compile error because of the following function:

```nim
proc cmpRunesIgnoreCase*(a, b: openArray[char]): int {.rtl, extern: "nuc$1".} =
  ## Compares two UTF-8 strings and ignores the case. Returns:
  ##
  ## | 0 if a == b
  ## | < 0 if a < b
  ## | > 0 if a > b
  var i = 0
  var j = 0
  var ar, br: Rune
  while i < a.len and j < b.len:
    # slow path:
    fastRuneAt(a, i, ar)
    fastRuneAt(b, j, br)
    result = RuneImpl(toLower(ar)) - RuneImpl(toLower(br))
    if result != 0: return
  result = a.len - b.len
```

This is due to the fact that `RuneImpl` is an alias for `int32`, which cannot be implicitly converted to an `int` within the result variable, on systems where `int`s are, for example, 16-bit, like on AVR.

### Minimum example:

```nim
import strutils
```

### panicoverride.nim:

```nim
proc exit(code: int) {.importc, header: "<stdlib.h>", cdecl.}

{.push stack_trace: off, profiler:off.}

proc rawoutput(s: string) = discard

proc panic(s: string) =
  rawoutput(s)
  while true:
    discard
  exit(1)

{.pop.}
```

### config.nims

```nim
switch("os", "standalone")
switch("cpu", "avr")
switch("gc", "none")

switch("avr.standalone.gcc.options.linker", "-static")
switch("avr.standalone.gcc.exe", "avr-gcc")
switch("avr.standalone.gcc.linkerexe", "avr-gcc")

when defined(windows):
  switch("gcc.options.always", "-w -fmax-errors=3")
```

### Nim Version

Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c4c44d10df8a14204a75c34e499def200589cb7c
active boot switches: -d:release

### Current Output

```text
[~/poc_unicode]$ nim c u.nim
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/config.nims' [Conf]
Hint: used config file '/home/mar/poc_unicode/config.nims' [Conf]
.............................................................
/home/mar/.choosenim/toolchains/nim-2.0.2/lib/pure/unicode.nim(849, 36) Error: type mismatch: got 'int32' for 'RuneImpl(toLower(ar)) - RuneImpl(toLower(br))' but expected 'int'
```

### Expected Output

```text
[~/poc_unicode]$ nim c u.nim    
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/config.nims' [Conf]
Hint: used config file '/home/mar/poc_unicode/config.nims' [Conf]
................................................................
/home/mar/poc_unicode/u.nim(1, 8) Warning: imported and not used: 'strutils' [UnusedImport]
Hint:  [Link]
Hint: mm: none; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
44814 lines; 0.314s; 57.844MiB peakmem; proj: /home/mar/poc_unicode/u.nim; out: /home/mar/poc_unicode/u [SuccessX]
```

### Possible Solution

There could be multiple solutions to this:

- Changing the return type to `int32` (which I guess may break something)
- Checking for the diff sign and setting result to a value that can be expressed with an int with size less than 32-bits, e.g.:
```nim
proc cmpRunesIgnoreCase*(a, b: openArray[char]): int {.rtl, extern: "nuc$1".} =
  ## Compares two UTF-8 strings and ignores the case. Returns:
  ##
  ## | 0 if a == b
  ## | < 0 if a < b
  ## | > 0 if a > b
  var i = 0
  var j = 0
  var ar, br: Rune
  while i < a.len and j < b.len:
    # slow path:
    fastRuneAt(a, i, ar)
    fastRuneAt(b, j, br)
    when sizeof(int) < 4:
      let diff = RuneImpl(toLower(ar)) - RuneImpl(toLower(br))
      result = case diff
        of 0: 0
        of low(int)..(-1): -1
        else: 1
    else:
      result = RuneImpl(toLower(ar)) - RuneImpl(toLower(br))
    if result != 0: return
  result = a.len - b.len
```

### Additional Information

Tested with avr.gcc as a backend.

**Comment by metagn** [comment]
Maybe:

```nim
when sizeof(int) < 4:
  result = clamp(RuneImpl(toLower(ar)) - RuneImpl(toLower(br)), low(int).int32, high(int).int32).int
else:
  result = RuneImpl(toLower(ar)) - RuneImpl(toLower(br))
```

**Comment by Abathargh** [comment]
Sounds good to me, it seems like with any of these fixes, I can import strutils and compile fine for AVR; I also ran the test suite with `./kock test cat lib` without any errors. 
If it is ok I can open a PR for this.

**Comment by 123swk123** [comment]
with this approach I see an another problem.

These are the `openarray[int]` present in [unicode_ranges.nim](https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/unicode_ranges.nim)

- [toLowerRanges ](https://github.com/nim-lang/Nim/blob/devel/lib/pure/includes/unicode_ranges.nim#L4C3-L4C17)
- [toLowerSinglets](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L52C3-L52C18)
- [toUpperRanges](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L665C3-L665C16)
- [toUpperSinglets](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L714C3-L714C18)
- [toTitleSinglets](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L1341C3-L1341C18)
- [alphaRanges](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L1352C3-L1352C14)
- [alphaSinglets](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L1826C3-L1826C16)
- [spaceRanges](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/includes/unicode_ranges.nim#L1976C3-L1976C14)

some entries in those array are way over than int 16-bit ranges which is causing the problem, for now I force cast them to int32 and also [modified](https://github.com/nim-lang/Nim/blob/33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f/lib/pure/unicode.nim#L467C1-L467C77) `proc binarySearch(c: RuneImpl, tab: openArray[int], len, stride: int): int =`  to `proc binarySearch(c: RuneImpl, tab: openArray[int32], len, stride: int): int =` 

by the way I am using nim for 8051 uC which is similar to AVR in terms of word length.

**Comment by Abathargh** [comment]
I was having the same issue lately, with the same exact fix.
Now, I don't know if that's the best course of action, but I will say that making this work is quite useful, since right now this issue disables completely the possibility to do compile time checks/assertions on your data when using certain modules in the stdlib.

For example, I'm using the `avr_io` library to develop a PWM-based DAC outputting some audio from an ATMega chip, and I was using `static` blocks to check for the correctness of wav files and outputting some metadata at compile time.

This issue specified by @123swk123 right now disables this kind of stuff, if you're using `strutils` or `strformat`.

**Comment by Araq** [comment]
@Abathargh Changing the lookup tables to use `int32` sounds reasonable, PR ahead.
