### ISSUE TITLE
[Yearly commentary on Nim] At the end of the year summary of news happening in Nim and the Nim-ecosystem

### ISSUE THREAD

**Issue by rubyFeedback** [nim-lang/Nim#23136]
Hey guys,
2023 is soon over. Happy new year!

My request: would it be possible to, say, do some kind of yearly summary of what happened in Nim?

Does not have to be long, perhaps 2-3 paragraphs or so, just mentioning the big things. And a tiny
bit more verbose than merely a changelog entry.

This would be quite nice for people who have been away from Nim for some time but are curious
about the things that are new in a yearly digest. If this takes too much time don't worry, just
close this issue request, but no matter what, remember to celebrate the outgoing year before
you go into 2024! \o/

**Comment by ringabout** [comment]
Instead, you could open a post on https://forum.nim-lang.org to get better invisbility. The GitHub issue is dedicated for problems and feature requests.
