### ISSUE TITLE
Cannot get repr of range type of enum

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#23139]
### Description

```nim
type Foo = enum a, b

var x: range[a..b]
echo repr x
```

### Nim Version

2.0.2

### Current Output

```text
(4, 11) Error: ambiguous call; both repr_v2.repr(x: T: distinct or range) [template declared in /playground/nim/lib/system/repr_v2.nim(101, 10)] and repr_v2.repr(x: Enum: enum) [proc declared in /playground/nim/lib/system/repr_v2.nim(69, 6)] match for: (range 0..1(Foo))
```

### Expected Output

```text
a
```

**Comment by ringabout** [comment]
That's intersting to know. I suppose something might be wrong with sigmatch. Since `range` is supposed to take precedence over `enum`. Well, one way or the other, it should behave just like `range[int]`.
```nim
template repr*[T: distinct|(range and not enum)](x: T): string
```
works though

**Comment by metagn** [comment]
> Since range is supposed to take precedence over enum.

Since they are both `tyBuiltInTypeClass` in this case (I think?) they are likely treated equal.
