### ISSUE TITLE
importjs pragma on proc returning a proc leads to a compile error

### ISSUE THREAD

**Issue by turbo** [nim-lang/Nim#23142]
### Description

Works (primitive type):

```nim
proc env*[T](fn: int, bar: T): int
  {. importjs: "(#).bind(#)" .}
```

Fails to compile:

```nim
proc env*[T](fn: proc(), bar: T): proc()
  {. importjs: "(#).bind(#)" .}
```

Workaround (works):

```nim
type F = proc()

proc env*[T](fn: F, bar: T): F
  {. importjs: "(#).bind(#)" .}
```

Compile using `nim js scratch.nim`

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: amd64]
Compiled at 2023-12-19
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8614f35dc2801bc8a24b393bd526370099404095
active boot switches: -d:release

### Current Output

/Users/turbo/scratch2.nim(2, 14) Error: invalid pragma: importjs: "(#).bind(#)"

### Expected Output

Successful compilation

### Possible Solution

See workaround

### Additional Information

Also occurs with latest `stable`

**Comment by metagn** [comment]
The pragma is parsed on `proc ()` instead of the proc, do `(proc ())`
