### ISSUE TITLE
Wrong line in error message with implicit returns

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2315]
``` nimrod
proc foo: string =
  let x = "foo"
  x.len
```

This reports:

```
min.nim(2, 2) Error: type mismatch: got (int) but expected 'string'
```

But the error is actually in line 3.

**Comment by def-** [comment]
The line number can be fixed here: https://github.com/Araq/Nim/blob/devel/compiler/semexprs.nim#L1338

```
a.sons[1].info.line = 3
```

But I'm not sure what to set it to. The error dosn't always come from the last line, for example in a `case-of` or `if`.

**Comment by Araq** [comment]
That's not how to fix it! Don't mess with the line numbers, nimsuggest uses them too, for instance.

**Comment by Araq** [comment]
The expression list that yields the 'int' starts at line 2 though, so it's arguably not even a bug.

**Comment by def-** [comment]
I agree that this makes sense once you know how the compiler transforms the proc body, but we can't assume people to know.

**Comment by andreaferretti** [comment]
With latest devel, the line number is correct
