### ISSUE TITLE
Integer overflows don't normally working.

### ISSUE THREAD

**Issue by ASVIEST** [nim-lang/Nim#23177]
### Description

```nim
var x: int8
x = 256
echo x # 0
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-01-06
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 3dee1a3e4c81448b67b75068fef06a121f320758
active boot switches: -d:release

### Current Output

```text
0
```

### Expected Output

```text
Error: unhandled exception: over- or underflow [OverflowDefect]
```

**Comment by beef331** [comment]
Errors as intended in 1.6.16 but works in 1.6.18

**Comment by juancarlospaco** [comment]
!nim c

```nim
var x: int8
x = 256
echo x
```

**Comment by metagn** [comment]
Maybe caused by the new type inference? (the type of 256 is changed from int literal to int8 without any checks)

Edit: [changeType with check=true](https://github.com/nim-lang/Nim/blob/devel/compiler%2Fsemexprs.nim#L3065) is called but maybe this doesn't account for int8
