### ISSUE TITLE
ambiguous call with `$` when using `distinct`

### ISSUE THREAD

**Issue by etan-status** [nim-lang/Nim#23172]
### Description

a.nim
```nim
type
  Foo* = object
  Bar* = object

func `$`*(x: Foo | Bar): string =
  "X"
```

b.nim
```nim
import ./a

type FooX = distinct Foo

func `$`*(x: FooX): string =
  $a.Foo(x)
```

### Nim Version

```
% nim -v
Nim Compiler Version 2.1.1 [MacOSX: amd64]
Compiled at 2024-01-05
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 3dee1a3e4c81448b67b75068fef06a121f320758
active boot switches: -d:release
```

### Current Output

```text
Error: ambiguous call; both objectdollar.$(x: T: object) [proc declared in Nim/lib/std/objectdollar.nim(5, 6)] and a.$(x: Foo or Bar) [func declared in a.nim(5, 6)] match for: (Foo)
    $a.Foo(x)
    ^
```

### Expected Output

```text
Success
```

### Possible Solution

It works when `a.nim` defines two separate `$` implementations for `Foo` and `Bar`. Only with `Foo | Bar` is broken.

### Additional Information

OK on version-2-0 and version-1-6.

**Comment by metagn** [comment]
Caused by ccc7c45d718c13714e8e9e1040c29b9b286d2448 @Graveflo

**Comment by Graveflo** [comment]
Pretty sure I know what the problem is here. I can explain if there is a want for that, but I'll just make a PR soon with a fix.

**Comment by hkl615** [comment]
**done**💯 @Araq
