### ISSUE TITLE
Changing discriminator enum field will call =destroy to the old value unnecessarily

### ISSUE THREAD

**Issue by gcao** [nim-lang/Nim#23189]
### Description

When we change a discriminator enum field, a `=destroy` call to the old value of the field is generated. This is unnecessary and has negative impact to the performance.

```nim
type
  TestKind* = enum
    tkA
    tkB

  Test* = ref object
    case kind*: TestKind
      of tkA:
        a*: int
      of tkB:
        b*: string

var t = Test(kind: tkA, a: 1)
{.cast(uncheckedAssign).}:
  t.kind = tkB    # <= this triggers calling =destroy on the old value
  t.b = "hello"

echo $t.kind
echo t.b
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
colontmpD_ = ((tyEnum_TestKind__3sXsB62p9avj0UyiGh3zbCg)1);
	{
		if (!!(((*t__enum95destroy_u12).kind == colontmpD_))) goto LA5_;
		eqdestroy___enum95destroy_u88((&(*t__enum95destroy_u12).kind));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA5_: ;
	T7_ = (tyEnum_TestKind__3sXsB62p9avj0UyiGh3zbCg)0;
	T7_ = colontmpD_;
	(*t__enum95destroy_u12).kind = T7_;
```

### Expected Output

```text
No `=destroy` should be called for the old value of the discriminator field.
```

### Possible Solution

If the field type is an enum, no `=destroy` call should be generated.

### Additional Information

Based on my basic benchmark, the `=destroy` call is ~20 times slower than changing the discriminator enum value.

**Comment by ringabout** [comment]
It is an old bug:

![image](https://github.com/nim-lang/Nim/assets/43030857/2bc0b1b4-42e4-491c-a57d-701c8eae2c83)

generated by Nim 1.6.0

**Comment by ringabout** [comment]
Well, it actually destroyed the old object. Look at that `&`. It is the hacky way to destroy the variants.

`eqdestroy___enum95destroy_u88((&(*t__enum95destroy_u12).kind));`

**Comment by gcao** [comment]
That makes sense. Please close the bug or I can close it.
