### ISSUE TITLE
`system.insert` wipes the string if `item` is an empty string

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#23223]
### Description

This code currently works with `--mm:refc`, but with `--mm:arc` or ORC (default) it replaces all characters in the string with null bytes:
```nim
proc main = 
  var stuff = "hello"
  stuff.insert ""
  echo repr stuff
  echo stuff.len

main()
``` 

### Nim Version
```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-01-17
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: f46f26e79aada7195f4d83d8601f0d856520763d
active boot switches: -d:release
```

### Current Output

```text
"\0\0\0\0\0"
5
```

### Expected Output
Either a runtime error when calling `insert` with an empty `item`, or fixing the bug so that the output becomes:
```
"hello"
5
```

**Comment by ringabout** [comment]
Yeah, it needs to prevent self movement.
