### ISSUE TITLE
Regression when using generic type with Table/OrderedTable

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#23233]
### Description

If only one type `JsonValueRef[uint64]` or `JsonValueRef[string]` is instantiated, the code will compile.
But if both is present, the compiler will refuse to compile. And the error message hinted at something wrong with generic cache.

```Nim
import tables

type 
  JsonObjectType*[T: string or uint64] = Table[string, JsonValueRef[T]]

  JsonValueRef*[T: string or uint64] = ref object  
    objVal*: JsonObjectType[T]
    
proc scanValue[K](val: var K) =  
  var map: JsonObjectType[K.T]
  var newVal: K
  map["one"] = newVal
  
var a: JsonValueRef[uint64]
scanValue(a)
    
var b: JsonValueRef[string]
scanValue(b)
```

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-01-01
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: b280100499fafe43657c860e3c79d9347be5b4b6
active boot switches: -d:release

### Current Output

```text
.... test_break.nim(18, 10) template/generic instantiation of `scanValue` from here
.... test_break.nim(12, 14) template/generic instantiation of `[]=` from here
.... nim\lib\pure\collections\tableimpl.nim(61, 38) Error: type mismatch: got 'sink JsonValueRef[system.string]' for 'val' but expected 'JsonValueRef[system.uint64]'
```

### Expected Output

```text
the code compiles
```

### Additional Information

The code compile and works fine with

Nim Compiler Version 1.6.18 [Windows: amd64]
Compiled at 2024-01-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a749a8b742bd0a4272c26a65517275db4720e58a
active boot switches: -d:release

**Comment by ringabout** [comment]
!nim c
```nim
import tables

type 
  JsonObjectType*[T: string or uint64] = Table[string, JsonValueRef[T]]

  JsonValueRef*[T: string or uint64] = ref object  
    objVal*: JsonObjectType[T]
    
proc scanValue[K](val: var K) =  
  var map: JsonObjectType[K.T]
  var newVal: K
  map["one"] = newVal
  
var a: JsonValueRef[uint64]
scanValue(a)
    
var b: JsonValueRef[string]
scanValue(b)
```
