### ISSUE TITLE
Operations on inline toOpenArray len return a wrong result

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#23280]
### Description

The title is likely wrong, idk what the issue is, TBH. The code:

```nim
let foo = @[1,2,3,4,5,6]
echo toOpenArray(foo, 0, 5).len
echo toOpenArray(foo, 0, 5).len mod 6  # this should output 0
echo toOpenArray(foo, 0, 5).max mod 6
let L = toOpenArray(foo, 0, 5).len
echo L mod 6
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-03
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: dd753b33830ab084686f9cf9c7d573702f175bb5
active boot switches: -d:release

### Current Output

```text
6
6
0
0
```

### Expected Output

```text
6
0
0
0
```

### Additional Information

it works as expected with JS target, but not in C and C++

**Comment by ringabout** [comment]
!nim c
```nim
proc foo =
  let foo = @[1,2,3,4,5,6]
  doAssert toOpenArray(foo, 0, 5).len == 6
  doAssert toOpenArray(foo, 0, 5).len mod 6 == 0 # this should output 0
  doAssert toOpenArray(foo, 0, 5).max mod 6 == 0
  let L = toOpenArray(foo, 0, 5).len
  doAssert L mod 6 == 0 

foo()
```

**Comment by ringabout** [comment]
I have figured out a fix, which will be pushed soon
