### ISSUE TITLE
Nim Windows installation file marked as Virus.

### ISSUE THREAD

**Issue by prakis** [nim-lang/Nim#23307]
### Description

I downloaded the Nim 'Manual installation' x86_64 zip for Windows from nim-lang.org site.
And Windows defender marked the downloaded file as virus.

Downloaded file
https://nim-lang.org/download/nim-2.0.2_x64.zip

Browser used: Chrome
OS: Windows 10 Enterprise

![image](https://github.com/nim-lang/Nim/assets/492450/604aa979-39b5-4527-912c-6d294b7e42b9)

### Nim Version

2.0.2 x64 binary

**Comment by Varriount** [comment]
Just to add: This *may* be a false positive (it appears that "Win32/Vigorf" is identified via heuristic scanning), however it might be worth checking file signatures.

**Comment by prakis** [comment]
Windows Defender is immediately deleting the file after download. No way to check file signature.

**Comment by Clonkk** [comment]
This is most likely a false positive. It's not the first time antivirus vendor falsely flag Nim binaries as virus.

You should be able to add an exception for a given folder and extract the binary in said folder (assuming you have the rights on your computer).

**Comment by demotomohiro** [comment]
This problem was reported by many windows users:
https://internet-of-tomohiro.netlify.app/nim/faq.en.html#nim-compiler-is-nimslashnimble-virus-or-malwareqmark

**Comment by firephil** [comment]
Yeah after you disable defender and copy it to folder, nimgrab is flagged as malware...
![Screenshot 2024-02-18 023011](https://github.com/nim-lang/Nim/assets/698336/5c4afe3f-13ad-4a13-bf9e-08462bce4db5)


https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505

**Comment by prakis** [comment]
This problem needs to be addressed, it scares to see a compiler shown as virus. I can't disable anti-virus for it.

**Comment by Goldenlion5648** [comment]
Not sure how much can be done besides reporting it as a false positive. Though currently with the compiler being flagged as a virus, it makes it much harder for new users to try the language

**Comment by prakis** [comment]
@Goldenlion5648 that is true, I am afraid to install it on windows. 'Trust me it is safe' statements won't give confidence, this is a high severtiy issue.

**Comment by anohako** [comment]
Bizarrely, Windows Security on my machine (64-bit Win10 v22H2) seems to **only** have issues with _nim-2.0.2_x64.zip_ but does **not** alert on the uncompressed folder contents. I've pointed it at the extracted product several times now and it's just shrugged. In any case, I can confirm that the SHA256 of the archive matches the checksum posted on nim-lang.org.

**Comment by Goldenlion5648** [comment]
@prakis I agree, it seems like this is just kind of being shrugged off. I enjoy the nim language and I know no one in good faith would put malware inside. But theoretically if it was hacked or a bad actor snuck something in, the "trust me" response seems like the wrong course of action.

@anohako while the SHA256 does match, if the nim website actually was hacked, they could just change the "expected SHA" to the SHA of the malicious file, no?

**Comment by demotomohiro** [comment]
@prakis @Goldenlion5648 If you think prebuilt Nim binary could have malware, you can build Nim from source code.
Install GCC if your system doesn't have it, git clone Nim repo or download Nim source code from https://github.com/nim-lang/Nim/tags
Then, execute `build_all.bat` in the Nim source directory and you will get Nim in `bin` directory.

**Comment by anohako** [comment]
> @anohako while the SHA256 does match, if the nim website actually was hacked, they could just change the "expected SHA" to the SHA of the malicious file, no?

Definitely. I'm not a security person, but I figured confirming that it matches still rules out a couple cases, such as the download being targeted in-transit by local malware or a discontinuity in the build tooling. Just throwing a tiny bit more evidence on the pile that points to a false positive on Microsoft's part.

**Comment by prakis** [comment]
@Goldenlion5648 I don't mean to be rude, I was pointing out a concern. Maybe the build machine is compromised (some accidental means) Or as @Clonkk said it maybe false alarm. But when we see a Microsoft Anitvirus warning and auto-deleting it, there is a serious concern about it.

I will try to locally build it and debug the virus warning.

**Comment by Clonkk** [comment]
> @Goldenlion5648 I don't mean to be rude, I was pointing out a concern. Maybe the build machine is compromised (some accidental means) Or as @Clonkk said it maybe false alarm. But when we see a Microsoft Anitvirus warning and auto-deleting it, there is a serious concern about it.
> 
> I will try to locally build it and debug the virus warning.

Fair warning, you will most likely not get anywhere. I have had Virus warning on a Nim program that was a simple hello world.

This problem is not exclusive to Nim, for instance I've had Windows flag the go compiler as a virus in the past, so I doubt you could permanently fix it by modifying code. This is a reoccurring problem, even if you could fix it for this iteration, chances are that it would come back a few months later and we'd be back in the same situation.

**Comment by Varriount** [comment]
So, I'm going to try to track down any "official" channels that Microsoft has to validate software. If nothing else, perhaps we can buy & digitally sign the released compiler binaries?

**Comment by beef331** [comment]
> Fair warning, you will most likely not get anywhere

False positives are horrendous even in C:
```C
#include <stdio.h>

int main() {
  printf("Hello world\n");
  return 0;
}
```
Compiled with mingw thrown on virustotal trips 9/70 of their 'security' vendors https://www.virustotal.com/gui/file/323f01cf10ab9889d374391028e3809c71c069269fcb76f98d81eb436a6f7cca/summary

**Comment by AmricprogrammerReal** [comment]
Bro Nim is safe no problem with this.
