### ISSUE TITLE
Refrain from using `sprintf()`, which triggers warnings in macOS 13/Xcode 14.1 `clang`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#23304]
### Description

https://developer.apple.com/documentation/kernel/1441083-sprintf notes that this function is deprecated, and as of macOS 13, a `deprecated-declarations` warning appears when one tries to use it:
```
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```

Affected stdlib functions include [strutils.formatBiggestFloat()](https://github.com/nim-lang/Nim/blob/3be251468365250a1ad2e86bb2fa634ff7297b61/lib/pure/strutils.nim#L2485-L2489), [formatfloat.writeFloatToBufferSprintf](https://github.com/nim-lang/Nim/blob/3be251468365250a1ad2e86bb2fa634ff7297b61/lib/std/formatfloat.nim#L47-L52) and various calling functions in `formatfloat` also in the stdlib, and [`repr` on a pointer](https://github.com/nim-lang/Nim/blob/3be251468365250a1ad2e86bb2fa634ff7297b61/lib/system/repr.nim#L18-L21) .

For example:
```nim
import std/formatfloat
var buf: array[65, char]
discard writeFloatToBufferSprintf(buf, 1.0)
echo buf

import std/strutils
echo formatBiggestFloat(1.0)
```

### Nim Version

```
Nim Compiler Version 1.6.19 [Linux: amd64]
Compiled at 2024-02-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d08bba579da7df36c51d987c04085628d81cb92f
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.3 [Linux: amd64]
Compiled at 2024-02-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 3be251468365250a1ad2e86bb2fa634ff7297b61
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-14
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 35ec9c31bd0bd413f1740feea90f3b97ad5d1b65
active boot switches: -d:release
```

### Current Output

```text
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```

### Expected Output

```text
No usage of `sprintf` and therefore no `deprecated-declarations` warnings
```

### Possible Solution

- remove various module-internal declarations of `c_sprintf()` and use `snprintf` instead
- deprecate the exported declaration in `system/ansi_c.nim` for later removal

It's of course possible to disable or hide this warning, but it's legitimate: it's not possible to safely use `sprintf()` in any situation where one can't deterministically bound its output using `snprintf()`

**Comment by Araq** [comment]
How is this warning legitmate? We know 64bit floating point numbers cannot exceed N characters and our format string is known at compile-time.

**Comment by tersec** [comment]
Then it should be easy to use `snprintf`.

**Comment by Araq** [comment]
Fair enough I guess.
