### ISSUE TITLE
Regression in 32-bit Nim 2.0.2 from 1.6 in implicit convertibility of `int32` to `int`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#23319]
### Description

```nim
type K = tuple
  g, w: int

static:
  doAssert sizeof(int32) == sizeof(int)
  doAssert low(int32) == low(int)
  doAssert high(int32) == high(int)

let
  a: int32 = 1
  i: int = 1
  v: K = (i * a, i * a)
```

https://nim-lang.org/docs/manual.html#type-relations-convertible-relation notes that
> A type `a` is **implicitly** convertible to type `b` iff the following algorithm returns true
where one of the options is
```nim
of int32:   result = b in {int64, int}
```
i.e. the `int32` to `int` conversion. In this example code, Nim 1.6 allows this, but Nim 2.0 does not, even though the manual seems to state that it's supported.

### Nim Version

Compiles:
```
Nim Compiler Version 1.6.10 [Linux: i386]
Compiled at 2022-12-07
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

Does not compile:
```
Nim Compiler Version 2.0.2 [Linux: i386]
Compiled at 2024-01-06
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

### Current Output

```text
a.nim(12, 10) Error: type mismatch: got '(int32, int32)' for '(i * a, i * a)' but expected 'K = tuple[g: int, w: int]'
```

**Comment by metagn** [comment]
!nim c

```nim
type K = tuple
  g, w: int

let
  a: int32 = 1
  i: int = 1
  v: K = (i * a, i * a)
```

**Comment by metagn** [comment]
!nim js

```nim
type K = tuple
  g, w: int

let
  a: int32 = 1
  i: int = 1
  v: K = (i * a, i * a)
```

**Comment by metagn** [comment]
Maybe caused by #20829 and followup PRs, maybe works but not fixed (can be confirmed by trying to pass the tuple to a proc parameter of type K) because of #23228?

**Comment by metagn** [comment]
Confirmed that #20829 causes it locally. However it should be known that this always errored when using `int64` on a 64 bit machine and #20829 likely made it consistent between the two.

`int32` and `int64` are convertible to `int` in their respective machines, however convertible matches do not cascade from tuple elements. The example in the issue works on devel due to type inference, this still fails (again, this always failed for int64):

```nim
type K = tuple
  g, w: int

let
  a: int32 = 1
  i: int = 1

proc foo(v: K) = discard

foo (i * a, i * a)
```

**Comment by Araq** [comment]
This never should have compiled.

**Comment by tersec** [comment]
> Confirmed that #20829 causes it locally. However it should be known that this always errored when using `int64` on a 64 bit machine and #20829 likely made it consistent between the two.
> 
> `int32` and `int64` are convertible to `int` in their respective machines, however convertible matches do not cascade from tuple elements. The example in the issue works on devel due to type inference, this still fails (again, this always failed for int64):
> 
> ```nim
> type K = tuple
>   g, w: int
> 
> let
>   a: int32 = 1
>   i: int = 1
> 
> proc foo(v: K) = discard
> 
> foo (i * a, i * a)
> ```

This compiles for me on:

```
Nim Compiler Version 1.6.20 [Linux: amd64]
Compiled at 2024-03-20
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f9fde0615c686357774736c0bce6f3c2075a94d
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.4 [Linux: amd64]
Compiled at 2024-03-20
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d4b58b0b068475e937e9e25af4f11f649285274c
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-03-20
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 6c4c60eade66e45448a220f4c8a91f866b76baf7
active boot switches: -d:release
```

on `amd64`.

> This never should have compiled.

This also seems reasonable, but then it's inconsistent between 32-bit and 64-bit Nim versions, see above.

**Comment by Araq** [comment]
> This also seems reasonable, but then it's inconsistent between 32-bit and 64-bit Nim versions, see above.

I don't understand. "This never should have compiled" applies to all bit versions of Nim.

**Comment by tersec** [comment]
Yeah, this probably never should have compiled.
