### ISSUE TITLE
nimsuggest creates an error message for a valid destroy hook

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/Nim#23316]
### Description

```nim
1| type SomeSturct = object
2| 
3| proc `=destroy`(x: SomeSturct) =
4|   echo "SomeSturct destroyed"
```
This is a valid destroy hook according to <https://nim-lang.org/docs/destructors.html#lifetimeminustracking-hooks-nimeqdestroy-hook>.
However nimsuggest creates an error message at line 3.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-13
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 35ec9c31bd0bd413f1740feea90f3b97ad5d1b65
active boot switches: -d:release

### Current Output

```text
chk     skUnknown               Hint    ???     0       -1      ">> (toplevel): import(dirty): /home/.../main.nim [Processing]"      0
chk     skUnknown               Error   /home/.../main.nim   3       0       "signature for \'=destroy\' must be proc[T: object](x: var T)"  0
```

### Expected Output

```text
no error
```

**Comment by jmgomez** [comment]
Seems to be a regression due to: https://github.com/nim-lang/Nim/pull/23156 
cc @ringabout

**Comment by doongjohn** [comment]
I found out the message is defined here (line: 2144):
https://github.com/nim-lang/Nim/blob/31ee75f10e6482cd482d329507190ac850eee2cf/compiler/semstmts.nim#L2133-L2147
I guess nimsuggest is not using the `--mm:orc` as a default.

So I set the mm to orc via config.nim like this:
```nim
# config.nims
--mm: orc
```

After that nim suggest `chk` crashes here (line 639):
https://github.com/nim-lang/Nim/blob/31ee75f10e6482cd482d329507190ac850eee2cf/compiler/liftdestructors.nim#L638-L640
```
> chk src/main.nim
chk     skUnknown               Hint    ???     0       -1      ">> (toplevel): import(dirty): /home/..../src/main.nim [Processing]"      0
fatal.nim(53)            sysFatal
Error: unhandled exception: liftdestructors.nim(639, 5) `t.destructor != nil`  [AssertionDefect]
```
I created a new Issue for this: https://github.com/nim-lang/Nim/issues/23867#issue-2420874187
