### ISSUE TITLE
Using a template in a type definition to derive, from the generic type parameter, the generic type parameter of a field no longer works

### ISSUE THREAD

**Issue by fulllness** [nim-lang/Nim#23339]
### Description

The following code works with Nim 1.4.2, but not with Nim 2:
```
type
    A = object
    B = object

template aToB(t: typedesc[A]): typedesc = B

type
    Inner[I] = object
        innerField: I
    Outer[O] = object
        outerField: Inner[O.aToB]

var x: Outer[A]
echo typeof x.outerField.innerField  #-> B
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-21
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 773c066634d831a968bb464eab35b25a00026525
active boot switches: -d:release

### Current Output

```text
(11, 26) Error: cannot instantiate Inner [type declared in (8, 5)]
got: <typeof(O.aToB)>
but expected: <I>
          outerField: Inner[O.aToB]
                           ^
```

### Expected Output

```text
B
```

### Additional Information

- It fails with the same error even if `Outer` is only declared, not instantiated.
- It also doesn't work in 2.0.0 and 2.0.2.
- It works in 1.4.2, unless you replace `O.aToB` with `aToB(O)`.
- Workaround for all mentioned Nim versions:
    ```
    type
        A = object
        B = object
    
    template aToInnerB(t: typedesc[A]): typedesc = Inner[B]
    
    type
        Inner[I] = object
            innerField: I
        Outer[O] = object
            outerField: O.aToInnerB
    
    var x: Outer[A]
    echo typeof x.outerField.innerField  #-> B
    ```
- Curiously, the following variant also works with all Nim versions, showing a difference between user-defined and built-in generic types:
    ```
    type
        A = object
        B = object

    template aToB(t: typedesc[A]): typedesc = B

    type Outer2[O] = object
        f1: O.aToB
        f2: seq[O.aToB]
    
    var x2: Outer2[A]
    echo typeof x2.f1  #-> B
    echo typeof x2.f2[0]  #-> B
    ```

**Comment by ringabout** [comment]
!nim c
```nim
type
    A = object
    B = object

template aToB(t: typedesc[A]): typedesc = B

type
    Inner[I] = object
        innerField: I
    Outer[O] = object
        outerField: Inner[O.aToB]

var x: Outer[A]
echo typeof x.outerField.innerField  #-> B
```

**Comment by juancarlospaco** [comment]
> !nim c

"IOException: No space left on device." ☹️

Works on `1.6.14`, fails on `2.0.0`.

**Comment by juancarlospaco** [comment]
!nim c

```nim
type
    A = object
    B = object

template aToB(t: typedesc[A]): typedesc = B

type
    Inner[I] = object
        innerField: I
    Outer[O] = object
        outerField: Inner[O.aToB]

var x: Outer[A]
echo typeof x.outerField.innerField  #-> B
```

**Comment by metagn** [comment]
Previously the template `aToB` prematurely matched `O` to `typedesc[A]` at the generic declaration site which is incorrect since O isn't resolved yet. Now it saves it as a "partially typed" expression but doesn't know how to deal with this in a generic invocation (should be in something like `semGenericInvocation` in `semtypes`).
