### ISSUE TITLE
sink parameters sometimes not copied even when there are later reads (refc)

### ISSUE THREAD

**Issue by gmega** [nim-lang/Nim#23354]
### Description

While tracking down a bug, I have accidentally bumped into some funny behavior with sink parameters while using refc: namely, that the locations passed to sink parameters are sometimes not copied, even when there are later accesses to those locations at the caller. 

Example:

```nim
type AnObject* = object of RootObj
  value*: int

proc mutate(a: sink AnObject) =
  a.value = 1

var obj = AnObject(value: 42)
echo "Value is: ", obj.value
mutate(obj)
echo "Value is: ", obj.value
```

this, however, works as expected:

```nim
type AnObject* = object
  value*: int
```

I was able to understand this behavior by looking at [ccgIntroducedPtr](https://github.com/nim-lang/Nim/blob/version-1-6/compiler/ccgutils.nim#L123) and realizing that `object of RootObj` is always passed by reference whereas final objects depend on the size, but this is definitely not what I expected. 

### Nim Version

```text
Nim Compiler Version 1.6.18 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a749a8b742bd0a4272c26a65517275db4720e58a
active boot switches: -d:release
```
I tried on a number of versions ranging from `1.0.0` to `2.0.2` (+ devel branch), and they all share the same issue.

### Current Output

```text
Value is: 42
Value is: 1
```

### Expected Output

```text
Value is: 42
Value is: 42
```

### Possible Solution

I don't understand the compiler well enough to propose a solution but, naively, there seem to be a few ways to go: from disabling pass-by-reference with sink on refc (probably not acceptable as a solution) to repurposing [the machinery that's used to the same end by ARC/ORC](https://github.com/nim-lang/Nim/blob/version-1-6/compiler/injectdestructors.nim#L1049).

**Comment by arnetheduck** [comment]
does this also affect 2.0/refc?

**Comment by gmega** [comment]
@arnetheduck yes it does, unfortunately.

**Comment by gmega** [comment]
!nim c --gc:refc
```nim
type AnObject* = object of RootObj
  value*: int

proc mutate(a: sink AnObject) =
  a.value = 1

var obj = AnObject(value: 42)
mutate(obj)
doAssert obj.value == 42
```

**Comment by gmega** [comment]
Btw, I've seen that force-enabling `injectDestructorCalls` fixes the issue, as (equivalently) does declaring a bogus destructor for `AnObject`. My currently working hypothesis is that the sink copy logic is only triggered if the type has a destructor.

**Comment by gmega** [comment]
Btw, I've realized that force-enabling `injectDestructorCalls` (in [genProcAux](https://github.com/nim-lang/Nim/blob/version-1-6/compiler/cgen.nim#L1045)) fixes the issue, as does creating a bogus destructor for `AnObject`. My currently working hypothesis is that the sink copy logic (which is embedded in `injectDestructorCalls`) only gets triggered for refc when there's a destructor defined for one of the types in the proc's signature.

**Comment by gmega** [comment]
!nim c --gc:refc

```nim
type AnObject = object of RootObj
  value*: int

proc `=destroy`(x: var AnObject) = discard

proc mutate(a: sink AnObject) =
  a.value = 1

var obj = AnObject(value: 42)
mutate(obj)
doAssert obj.value == 42
```

**Comment by elcritch** [comment]
> !nim c --gc:refc
> 
> ```nim
> type AnObject = object of RootObj
>   value*: int
> 
> proc `=destroy`(x: var AnObject) = discard
> 
> proc mutate(a: sink AnObject) =
>   a.value = 1
> 
> var obj = AnObject(value: 42)
> mutate(obj)
> doAssert obj.value == 42
> ```

@gmega oh odd, adding a destructor for the test object fixes it? Hmmm, maybe it'll be an easy fix of triggering whatever logic gets triggered when there's a destructor.

**Comment by ringabout** [comment]
!nim c --gc:arc
```nim
type AnObject* = object of RootObj
  value*: int

proc mutate(a: sink AnObject) =
  a.value = 1

proc foo =
  var obj = AnObject(value: 42)
  doAssert obj.value == 42
  mutate(obj)
  doAssert obj.value  == 42

foo()
```

**Comment by gmega** [comment]
> @gmega oh odd, adding a destructor for the test object fixes it? Hmmm, maybe it'll be an easy fix of triggering whatever logic gets triggered when there's a destructor.

Well, either that or forcing `injectDestructorCalls`, which I think is the same path. I'm not entirely sure what an acceptable solution would be here as that logic that handles sink args is intertwined with injection of destructors. If it's just a matter of triggering it, then I suppose adding a weaker condition (or no condition at all) to `injectDestructorCalls` (e.g. something that checks if the proc has a sink arg) would be enough.

**Comment by ringabout** [comment]
arc is affected as well, which is a regression, I will fix that first => https://github.com/nim-lang/Nim/pull/23359

**Comment by ringabout** [comment]
related issues: https://github.com/nim-lang/Nim/issues/22175 https://github.com/nim-lang/Nim/issues/12340 https://github.com/nim-lang/Nim/issues/22173

**Comment by Araq** [comment]
So what should be done here? You cannot pass a subtype to a `sink Object`? Otherwise we get a sliced copy.

**Comment by arnetheduck** [comment]
>  Otherwise we get a sliced copy.

Broadly, I view slicing copies as the generalisation of a narrowing integer conversion and ideally they should be handled the same way in the language: there should be a compiler error that can be solved by an explicit conversion where needed (same as when you try to convert an `int64` to `int32`).

**Comment by arnetheduck** [comment]
Also, in this example there is no slicing so no special casing should be needed, leaving `sink` to behave unpredictably with respect to "normal" value semantics
