### ISSUE TITLE
for JS, `abs BiggestInt -1` failed to run

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#23378]
### Description

A smallest demo
```Nim
var neg = -1  # prevent compile-time evaluation
let n{.used.} = abs BiggestInt neg
```
run the generated JS code either on web browser or nodejs, error:
`Cannot mix BigInt and other types, ...`

If looking into that JS code, it's due to:

- `abs`  is implemented as `<arg> * (-1)` if `<arg>` is negative
- when for Nim's BiggestInt (a.k.a int64), JS uses BigInt
- BigInt cannot be mixed with `-1` (an int)

And, it's a regression (see `Additional Information`)

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-03-07
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

And

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
TypeError: Cannot mix BigInt and other types, use explicit conversions
```

### Expected Output

```text
1
```

### Additional Information

At least I found Nim-1.6.14 didn't have this problem:

```
Nim Compiler Version 1.6.14 [Windows: amd64]
Compiled at 2023-06-27
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

Also, just take `BiggestInt -1` as an example,

e.g. `abs -140140140140` will fail on run, too

**Comment by litlighilit** [comment]
!nim js -r
```Nim
echo BiggestInt -1
```

**Comment by litlighilit** [comment]
!nim js
```Nim
echo abs BiggestInt -1
```

**Comment by litlighilit** [comment]
Emm...first time to use nimrun-action... Maybe I haven't learnt how to use it right

---

 In addition, code used for `nimrun-action` above is not suitable to reproduction that error

as it may cause compile-time evaluation,

 which has no such problem.

**Comment by metagn** [comment]
If you encounter more regressions with int64 you can get the old behavior back with `--jsbigint64:off` as a workaround (though in general having it on helps us discover its issues).
