### ISSUE TITLE
Nim 2.0.2 ignores backticks for interface as a field in type.

### ISSUE THREAD

**Issue by verbunk** [nim-lang/Nim#23384]
### Description

In nim 1.6.18

```nim
type
  MyType = object
    fieldA:string
    fieldB:int
    `type`:string
    `interface`:string
```
works.

In nim 2.0.2, the use of backticks are ignored only for the reserved word, interface giving the error,

```
Error: expression expected, but found 'keyword interface'.
```

### Nim Version

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release

Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c4c44d10df8a14204a75c34e499def200589cb7c
active boot switches: -d:release

### Current Output

```text
Error: expression expected, but found 'keyword interface'.
```
```


### Expected Output

```text
No error
```

### Possible Solution

Between 1.6.18 and 2.0.2 there may have been a regression in how the reserved work interface is treated.

**Comment by ringabout** [comment]
!nim c
```nim
type
  MyType = object
    fieldA:string
    fieldB:int
    `type`:string
    `interface`:string
```

**Comment by verbunk** [comment]
Found an issue with the linter which was causing the backtick and colon to not be saved correctly on write (!!) This only became evident in the IDE after save and reload so I was seeing a different view than compiler. 

Nim is all good here so I'm closing!
