### ISSUE TITLE
when compile lambda iterator for JS, internal error: symbol has no generated name: true 

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#23382]
### Description

The smallest demo:
```Nim
let i{.used.} = iterator(): char =
  yield 'c'
```
can compile for c/cpp other than js.

If compiled via `nim js`, then Nim compiler terminates with an error:
`error: <nim path>\lib\system\basic_types.nim(46, 16) Error: internal error: symbol has no generated name: true  
`

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-03-07
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

And

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

And

Nim Compiler Version 1.6.14 [Windows: amd64]
Compiled at 2023-06-27
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

<compiler inner error: ... > (describled above)

**Comment by juancarlospaco** [comment]
!nim js

```nim
let i{.used.} = iterator(): char =
  yield 'c'
```

**Comment by metagn** [comment]
JS backend doesn't support closure iterators, this is supposed to give a legible error since #7109 was fixed but doesn't seem to in this case.

Would also be fixed by implementing closure iterators in JS.
