### ISSUE TITLE
pairs (and mpairs) over iterator not recognized if put in lib/system.nim

### ISSUE THREAD

**Issue by Aszarsha** [nim-lang/Nim#2338]
See comments in https://gist.github.com/Aszarsha/32c68e654d384e363c59

Those exact pairs (and mpairs) function in extractFasta.nim make the program compile (and work), but if moved to lib/system.nim, compilation fail with the same error as if the functions did not exist.

**Comment by def-** [comment]
Doesn't compile for me, even if I leave the pairs in extractFasta.nim:

```
extractFasta.nim(44, 32) Error: undeclared identifier: 'lines'
```

**Comment by Aszarsha** [comment]
Well, it does for me with devel faad6ed (did yesterday too, don't know the exact hash though).
I added test.nim in the gist without all the comments just in case.

**Comment by def-** [comment]
I don't know, maybe I just did something wrong. Works for me now.

**Comment by andreaferretti** [comment]
Is this a bug? I mean, this is something that does not work if put in the standard library. But these functions are not in the standard library. I mean, if Nim was to introduce them, of course they ought to work, but I don't think that users putting things into the standard library should be a supported use case.

**Comment by Araq** [comment]
> but I don't think that users putting things into the standard library for their own modified version of Nim should be a supported use case.

Agreed.
