### ISSUE TITLE
Error message 'ambiguous identifier' shows wrong module for re-exported symbols

### ISSUE THREAD

**Issue by simonkrauter** [nim-lang/Nim#23397]
### Description

Minimal example:

File module1.nim:
```nim
const test* = "foo"
```
File module2.nim:
```nim
import module1
export test
```
File module3.nim:
```nim
const test* = "bar"
```
File main.nim:
```nim
import module2
import module3
echo test # this produces the error
```

The error message shows the module name where the `test` is originally defined (`module1` and `module3`), but it show where it is imported (`module2` and `module3`).

### Nim Version

Nim Compiler Version 2.0.2 [Linux: amd64]

### Current Output

```text
Error: ambiguous identifier: 'test' -- use one of the following:
  module1.test: string
  module3.test: string
```

### Expected Output

```text
Error: ambiguous identifier: 'test' -- use one of the following:
  module2.test: string
  module3.test: string
```

**Comment by quantimnot** [comment]
I think #23123 broke this more. This is the result after commit b280100:

```
Error: type mismatch
Expression: echo test
  [1] test: string | string

Expected one of (first mismatch at [position]):
[1] proc echo(x: varargs[typed, `$`])
```

This is *way* more confusing. @metagn

**Comment by metagn** [comment]
I knew there was a different error message now given I disabled `tpure_enums_conflict` in #23123 but I didn't consider it completely obscures which symbols are ambiguous, I have an idea of what to do now but it's a bit verbose
