### ISSUE TITLE
Confusing error message when defining a variable using a case statement

### ISSUE THREAD

**Issue by CharlesEnding** [nim-lang/Nim#23408]
### Description

Hello,

The code below raises `/***/test2.nim(11, 3) Error: expression '3' is of type 'int' and has to be used (or discarded)`
```Nim
type
  Foo = enum Bar1, Bar2, Bar3
  
var
  a: int
  b: Foo = Bar2

a = case b
of Bar1:
  3
of Bar2:
  4
else:
  echo "Bamboozle"
```

The error message does not reflect the actual error or its location. 
I don't know whether it should be a type mismatch error, or something else, but ideally it'd point to the first location that would break the expectations set by using `a =`.

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
/***/test2.nim(11, 3) Error: expression '3' is of type 'int' and has to be used (or discarded)
```

### Expected Output

```text
/***/test2.nim(15, 3) Error: ...
```

**Comment by Araq** [comment]
Error message aside, what was this code supposed to do? It makes no sense.

**Comment by CharlesEnding** [comment]
It's not supposed to do anything, it's a minimal example showcasing the error message issue.

The actual code was:
```Nim

proc nextPosition(previous: Geometry, next: Geometry, relative: RelativePosition, margin: Margin = Margin(0)): Position =
  result = case relative
  of Center:
    Position(x: center(previous).x - center(next).x, y: center(previous).y - center(next).y)
  of InLeft:
    Position(x: previous.position.x + Units(margin), y: center(previous).y - center(next).y)
  of InRight:
    Position(x: previous.position.x + previous.size.width - Units(margin), y: center(previous).y - center(next).y)
  else:
    echo "I'm going to implement this later."
```
plus a few more hundred lines of types and calculations.

**Comment by metagn** [comment]
Related #14665

**Comment by CharlesEnding** [comment]
Seems to be a duplicate of #11928.
