### ISSUE TITLE
NRVO can kick in on `exportc, dynlib` procedures

### ISSUE THREAD

**Issue by beef331** [nim-lang/Nim#23401]
### Description

The following generates `N_LIB_EXPORT N_CDECL(void, test)(tyObject_Type__d6JzYIj7fDQMy5fjQ0vO7Q* Result);`. Simply switching to `ptr int`  generates the expected `N_LIB_EXPORT N_CDECL(tyObject_Type__d6JzYIj7fDQMy5fjQ0vO7Q, test)(void);`
```nim
type Type = object
  intr: ref int

proc test(): Type {.exportc, dynlib.} = discard
```

### Nim Version

2.0.2 and devel

**Comment by Araq** [comment]
Why is this a bug? A `ref` inside triggers Nim's ABI so Nim is allowed to do that.

**Comment by beef331** [comment]
There is no way to disable it without changing all your `ref T` to `ptr T` which means even if you want to treat Nim references as opaque pointers you cannot easily write an FFI'd API for any language but Nim. So at the very least a `{.nonrvo.}` or similar should exist I guess to allow making Nim dynlibs that can be used by other languages with internal opaque pointers.

**Comment by juancarlospaco** [comment]
out parameters as workaround?. 🤔

**Comment by Araq** [comment]
What do you mean "opaque pointers"? The C must adjust the refcounts when copying these structs around, a `ref` is not "opaque".

**Comment by beef331** [comment]
You can treat it as an opaque reference just fine. If you want a copy you can call an exported copy, same goes for the destroy. An opaque pointer does nothing but hide away the implementation details from the FFI side which is welcomed when dealing with ref counts. The issue is that the RVO makes it highly unpredictable to write FFI procedures. 

For reference:
```nim
type MyObject = object
  someRef: ref int


proc createObj(): MyObject {.exportc, dynlib, cdecl.} =
  MyObject(someRef: new int)

proc copyObj(obj: MyObject): MyObject {.exportc, dynlib, cdecl.} = obj

proc destroyObj(obj: MyObject) {.exportc, dynlib, cdecl.} =
  `=destroy`(obj)
```

One would expect the following would work.
```nim
struct MyRef;
struct MyObject{
  struct MyRef* someRef;
};
extern struct MyObject createObj(void);
extern struct MyObject copyObj(struct MyObject*);
extern void destroyObj(struct MyObject*);
```

So perhaps a procedure marked `cdecl` should not do RVO?
