### ISSUE TITLE
`internal error: getTypeDescAux` with `void` in generic array instantiation

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23419]
### Description

```nim
import sequtils

type F[T, E] = object
  dummy: array[0, E]

proc stop(v: int): F[void, void] = discard

var b = mapIt([1, 2, 3], stop(it))
```

### Nim Version

1.6, devel

### Current Output

```text
Error: internal error: getTypeDescAux(tyVoid)
```

**Comment by beef331** [comment]
Min repro
```nim
var a: (array[0, void], )
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
var a: (array[0, void], )
```

**Comment by litlighilit** [comment]
An array of void type is just not allowed[^1],

so the only thing that shall be improved is the error message.


[^1]: `array[0, void]` will gives `Error: invalid type: 'void' in this context: 'array[0, void]'`, that's, the code above is invalid.
