### ISSUE TITLE
Recursive call in function expression rejected by compiler

### ISSUE THREAD

**Issue by starmonger999** [nim-lang/Nim#23426]
### Description

why is this allowed
```
proc g(x: int): auto = result = g(x)
```

but not this
```

let g = proc (x: int): auto = result = g(x)
```

```

Error: undeclared identifier: 'g'
```

### Nim Version

```
Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c4c44d10df8a14204a75c34e499def200589cb7c
active boot switches: -d:release
```

**Comment by rudyryk** [comment]
I'd argue that the second one is not allowed reasonably.

It's indeed undeclared in terms of compile-time resolved declarations. Because assignment is applied after evaluation. The first one is valid because definition goes first.

**Comment by Araq** [comment]
No bug here and `let x = x # create a copy from the parameter x` is an idiom.
