### ISSUE TITLE
Using tables at compile/runtime causes a compiler error on devel for systems where sizeof(int) < 4

### ISSUE THREAD

**Issue by Abathargh** [nim-lang/Nim#23439]
### Description

Here we are, once again, with the newest issue on 8/16-bits systems!

The devel branch seems to have a regression that comes up when using tables both at runtime and compile-time (this is the same both with toTable and newTable).

This seems to be caused by this template here (lib/pure/collections/hashcommon.nim - line 58)
```nim
template genHashImpl(key, hc: typed) =
  hc = hash(key)
  if hc == 0: # This almost never taken branch should be very predictable.
    hc = 314159265 # Value doesn't matter; Any non-zero favorite is fine.
```

But this template has been there forever. Thus, I run git bisect on the compiler/stdlib and this seems to be the commit from where the bug starts happening:

```bash
[62d8ca430][~/programs/Nim]$ git bisect good
00be8f287a41be42b3763f71beecd959dd6b7aa2 is the first bad commit
commit 00be8f287a41be42b3763f71beecd959dd6b7aa2
Author: metagn <metagngn@gmail.com>
Date:   Mon Jan 8 05:44:04 2024 +0300

    trigger range check with new type inference on nkIntLit [backport:1.6] (#23179)
    
    fixes #23177
    
    `changeType` doesn't perform range checks to see if the expression fits
    the new type [if the old type is the same as the new
    type](https://github.com/nim-lang/Nim/blob/62d8ca43063197272968b4acf8c7a1ef27874c54/compiler/semexprs.nim#L633).
    For `nkIntLit`, we previously set the type to the concrete base of the
    expected type first, then call `changeType`, which works for things like
    range types but not bare types of smaller bit size like `int8`. Now we
    don't set the type (so the type is nil), and `changeType` performs the
    range check when the type is unset (nil).

 compiler/semexprs.nim              |  3 +--
 tests/overflow/twronginference.nim | 10 ++++++++++
 2 files changed, 11 insertions(+), 2 deletions(-)
 create mode 100644 tests/overflow/twronginference.nim
```

### Minimum example ###

```nim
import std/tables

const 
  test_table = {
    "test": 42,
    "test1": 24,
  }.toTable

proc main = 
  while true:
    discard

main()
```

### panicoverride.nim ###

```nim
proc exit(code: int) {.importc, header: "<stdlib.h>", cdecl.}

{.push stack_trace: off, profiler:off.}

proc rawoutput(s: string) = discard

proc panic(s: string) =
  rawoutput(s)
  while true:
    discard
  exit(1)

{.pop.}
```

### config.nims ###

```nim
switch("os", "standalone")
switch("cpu", "avr")
switch("gc", "none")

switch("avr.standalone.gcc.options.linker", "-static")
switch("avr.standalone.gcc.exe", "avr-gcc")
switch("avr.standalone.gcc.linkerexe", "avr-gcc")

when defined(windows):
  switch("gcc.options.always", "-w -fmax-errors=3")
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-03-22
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 33902d9dbb65fbfdfbd6e3b2a34c6e19eccb762f
active boot switches: -d:release

### Current Output

```text
[~/projects/nim/const_table_poc]$ nim c const_table_poc.nim
Hint: used config file '/home/mar/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/mar/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
Hint: used config file '/home/mar/projects/nim/const_table_poc/config.nims' [Conf]
.........................................................
/home/mar/projects/nim/const_table_poc/const_table_poc.nim(7, 4) template/generic instantiation of `toTable` from here
/home/mar/.choosenim/toolchains/nim-#devel/lib/pure/collections/tables.nim(314, 45) template/generic instantiation of `[]=` from here
/home/mar/.choosenim/toolchains/nim-#devel/lib/pure/collections/tableimpl.nim(60, 21) template/generic instantiation of `rawGet` from here
/home/mar/.choosenim/toolchains/nim-#devel/lib/pure/collections/hashcommon.nim(69, 14) template/generic instantiation of `genHashImpl` from here
/home/mar/.choosenim/toolchains/nim-#devel/lib/pure/collections/hashcommon.nim(61, 10) Error: cannot convert 314159265 to Hash
```

### Expected Output

```text
[~/projects/nim/const_table_poc]$ nim c const_table_poc.nim
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/mar/.choosenim/toolchains/nim-2.0.2/config/config.nims' [Conf]
Hint: used config file '/home/mar/projects/nim/const_table_poc/config.nims' [Conf]
.........................................................
/home/mar/projects/nim/const_table_poc/const_table_poc.nim(4, 3) Hint: 'test_table' is declared but not used [XDeclaredButNotUsed]
CC: ../../../.choosenim/toolchains/nim-2.0.2/lib/system.nim
CC: const_table_poc.nim
Hint:  [Link]
Hint: mm: none; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
40056 lines; 0.193s; 37.664MiB peakmem; proj: /home/mar/projects/nim/const_table_poc/const_table_poc.nim; out: /home/mar/projects/nim/const_table_poc/const_table_poc [SuccessX]
```

### Possible Solution

Using a value of hc such that it is an int expressible as a 16-bit value fixes this.

```nim
template genHashImpl(key, hc: typed) =
  hc = hash(key)
  if hc == 0: # This almost never taken branch should be very predictable.
    hc = 42  # Value doesn't matter; Any non-zero favorite is fine.
```

I did not go into what the link between the git bisect commit and this behavior may be.

**Comment by juancarlospaco** [comment]
Send PR?, `hc = static(int.high)` does not work?.

**Comment by Abathargh** [comment]
It works, I just wanted to understand if it's the right fix or not, since this is a regression that came out after that specific commit.
If you think it's ok I can do a PR like so, which I tested locally and works.

**Comment by metagn** [comment]
Very easy fix is just bitmask `314159265` to `int` at compile time (`cast[int](uint(314159265'u32 and high(uint).uint32))`), the breaking commit just made the code error as it should, `314159265` is not a valid int. But maybe `Hash`  could also be defined as `int32` on these platforms though this is a way bigger maintenance burden.

**Comment by Abathargh** [comment]
> Very easy fix is just bitmask `314159265` to `int` at compile time (`cast[int](uint(314159265'u32 and high(uint).uint32))`), the breaking commit just made the code error as it should, `314159265` is not a valid int. But maybe `Hash` could also be defined as `int32` on these platforms though this is a way bigger maintenance burden.

Is keeping the `314159265` so important? I think it's just the first 9 digits of π.. we could just put something else there like @juancarlospaco is suggesting. The commit that seems to introduce that is 65ce08f38c6a8ae05df5529a5b2d51de7aaec2d6, which seem to comment on how the value is actually unimportant.

Regarding your second point, I would honestly prefer to leave it as is, since I don't have enough expertise in what this choice would imply at large (I did compile and run the test suite with Hash = int32 with no issue though). For example int32 are ok to use on AVR chips, but using int16 is always better and faster, so if this implies a possible slow-down in lookups I'd rather keep using `int`.

**Comment by metagn** [comment]
It's not important but 1. a more random value is nicer and even the pi integer is too small to be random in 64 bits 2. bitmasking such a random value is the simplest way to have it on multiple platforms and what the compiler was already silently doing before. It's also fine to just PR `hc = 1`, I don't think anyone would complain.

**Comment by Araq** [comment]
just give it another magic number for a 16 bit system. That said, the idea of using hash tables on a 16 bit system seems odd in itself.

**Comment by Abathargh** [comment]
While I agree, this would really be useful more as a compile time thing, I use it with macros for example

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23450
