### ISSUE TITLE
AsyncJS backend : deceptive named tuple conversion

### ISSUE THREAD

**Issue by Alogani** [nim-lang/Nim#23459]
### Description

Hello,

Named tuple is not converted to an appropriate javascript code. (see more details on expected output/actual output)
I do think it is also problematic for unamed tuple, because Field0 variable do not exist.

This addition will really help write cleaner and concise code for js backend every time an imported js function expect a hashmap.

Example :
```
# Case 1: No static checks (lose the interest of using nim) :
proc getDocument(PdfJs: PdfJsLib, options: JsObject): Future[Pdf] {.importcpp: "#.getDocument(#).promise", varargs, nodecl, async.}
var page = await PdfJs.getDocument(JsObject{ data: file.arrayBuffer() })

# Case 2: Using a struct (cumbersome) :
type getDocumentArgs* = object
    data: ArrayBuffer
    worker: PdfWorker
proc getDocument(PdfJs: PdfJsLib, options: getDocumentArgs): Future[Pdf] {.importcpp: "#.getDocument(#).promise", varargs, nodecl, async.}
var page = await PdfJs.getDocument(getDocumentArgs(data = file.arrayBuffer(), worker = PdfWorker))

# Case 3: With tuple
proc getDocument(PdfJs: PdfJsLib, options: tuple[data: ArrayBuffer, worker: PdfWorker, ...]): Future[Pdf] {.importcpp: "#.getDocument(#).promise", varargs, nodecl, async.}
var page = await PdfJs.getDocument((data: file.arrayBuffer(), worker: PdfWorker))
```

Thanks !

### Nim Version

2.0.2

### Current Output

```text
import std/[jsffi, jsconsole]
console.log((data: 42))

## Generates:
console.log({Field0: "42"});
```

### Expected Output

```text
import std/[jsffi, jsconsole]
console.log((data: 42))

## Generates:
console.log({"data": 42});
```

### Possible Solution

I think the code handling the conversion is here : compiler/jsgen.nim line:1936, but recompiling nim with a different value seems to have no effect. (But I'm not used to recompile nim, so it means nothing !)

**Comment by Araq** [comment]
JS has no tuples so the compiler is free to generate code as it sees fit.
