### ISSUE TITLE
strutils fails to compile. 'invalid type: 'None' in this context

### ISSUE THREAD

**Issue by shirleyquirk** [nim-lang/Nim#23451]
### Description

```nim
import std/[strformat,strutils]
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-03-28
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: c934d5986d241c2a34c89ae3c16047299fd3a86b
active boot switches: -d:release

### Current Output

```text
Hint: used config file '/home/bwsq/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/bwsq/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
.........................................................................................
/home/bwsq/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim(73, 11) Hint: duplicate import of 'parseutils'; previous import here: /home/bwsq/.choosenim/toolchains/nim-#devel/lib/pure/strformat.nim(325, 11) [DuplicateModuleImport]
/home/bwsq/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim(78, 1) Hint: duplicate import of 'unicode'; previous import here: /home/bwsq/.choosenim/toolchains/nim-#devel/lib/pure/strformat.nim(325, 11) [DuplicateModuleImport]
.
/home/bwsq/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim(2589, 17) Error: invalid type: 'None' in this context: 'proc (bytes: int64, decimalSep: char, prefix: None, includeSpace: bool): string{.noSideEffect.}' for proc
```

### Expected Output

```text
compiles.
```

**Comment by shirleyquirk** [comment]
in 2.0, 2.0.2 and devel

workaround is to put strutils before strformat in import list

**Comment by ringabout** [comment]
!nim c
```nim
import std/[strformat,strutils]
```

**Comment by ringabout** [comment]
Cannot reporduce, do you have a reproducible example?

**Comment by juancarlospaco** [comment]
is import order even relevant in Nim?, I think they are all resolved statically at compile time. Cant repro.

**Comment by shirleyquirk** [comment]
thanks, guys: sorry about that, i knew it had to be something i was doing. 
the fact that import order mattered should have been a clue, 
i was doing this:
```nim
include std/[strformat,strutils]
```

**Comment by shirleyquirk** [comment]
there is probably an interesting bug underneath this, but i dont think including stdlib is supported, is it? feel free to close

**Comment by juancarlospaco** [comment]
But including stdlib is not recommended in the docs whatsoever.

Closing as said in https://github.com/nim-lang/Nim/issues/23451#issuecomment-2027960319
