### ISSUE TITLE
Undefined behavior when calling set.len through a Table

### ISSUE THREAD

**Issue by RolandMunsil** [nim-lang/Nim#23478]
### Description

Repro:

```nim
import tables

var tupleToSet = {(3, 5): {0, 1, 2}}.toTable

echo {0, 1, 2}.len
echo tupleToSet[(3, 5)].len
```

Output:
```
3
46
```

The bottom number is different each time I run the code.

### Nim Version

Nim Compiler Version 2.0.2 [Windows: amd64]

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23437
