### ISSUE TITLE
Optional final comma (feature request)

### ISSUE THREAD

**Issue by top-master** [nim-lang/Nim#23471]
### Summary

Don't produce error if there is a final comma-sign, followed by nothing.

### Description

Git VCS tracks even a single comma-sign as a change, hence languages like PHP opted for allowing a final comma-sign followed by nothing.

Note that PHP has not Nim's nice type checks but despite that, they think it's an advantage.

PHP allows said behaviour not just for array, but for function/method arguments as well.

### Examples

When having:
```nim
import std/strformat

type
  Person = object
    name: string
    age: Natural # Ensures the age is positive

let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30)
]
```

Then it should be allowed to have final comma-sign, like:
```nim
let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30),
]
```
So that future developer's Git-commits only add new lines, without changing existing lines, like:
```nim
let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30),
  Person(name: "Yet another person", age: 123),
]
```

**Comment by Araq** [comment]
So fix "git diff" instead.

**Comment by top-master** [comment]
Git and Git diff are both right, even if a single space, a diff is a diff,
hence fix the language like PHP did ;-)

It toke PHP years to come to the conclusion, and it's better to learn from their experience instead of instantly closing the issue without waiting for other community memebers to comment.

**Comment by top-master** [comment]
Assume two developers make almost the same change.

Having the original:
```
let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30)
]
```

First developer adds:
```
let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30),
  Person(name: "Andreas Rumpf", age: 55)
]
```
Other developer adds:
```
let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30),
  Person(name: "Yet another person", age: 123)
]
```

Now we have Git conflict, and most tools only let you choose between before or after, the nasty kind of Git conflict for a simple final-comma-sign.

**Comment by ringabout** [comment]
I don't know what you are complaining about. But did you run your example using Nim? Doesn't The optional comma already work for arrays and parameters in Nim?

**Comment by top-master** [comment]
Okay, then say that to begin with, also
the `let people = [ ... ]` sample is a copy from official web-site, and
it would be nice to use the better syntax in your docs to begin with.

**Comment by Araq** [comment]
"git diff" still needs to get smarter with respect to whitespace, for example. What are you gonna do in PHP, promote a style that doesn't use indentation? Program in assembler again? Optimizing for "git diff" is ridiculous.

**Comment by top-master** [comment]
Maybe someone should request "configurable syntax" feature for Git diff, but that's another discussion, not related to this repo.
