### ISSUE TITLE
JS case using float range causes compiler crash

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#23492]
```nim
proc foo =
  var x: range[1.0 .. 5.0] = 2.0
  case x
  of 1.0..2.0:
    echo 1
  else:
    echo 3

foo()
```

gives an error 
```
fatal.nim(53)            sysFatal
Error: unhandled exception: field 'intVal' is not accessible for type 'TNode' using 'kind = nkFloatLit' [FieldDefect]
```

**Comment by juancarlospaco** [comment]
!nim js

```nim
proc foo =
  var x: range[1.0 .. 5.0] = 2.0
  case x
  of 1.0..2.0:
    echo 1
  else:
    echo 3

foo()
```

**Comment by metagn** [comment]
Culprit

https://github.com/nim-lang/Nim/blob/779bc8474b0e4d5d77d2619bd50eaa0fc111d1e6/compiler/jsgen.nim#L1062

`transferRange` needs to be true for `range` of `float`, it should probably be true for any `range` with a big enough size

**Comment by ringabout** [comment]
Well, I have had a PR to fix this issue

The culprit is that `let typeKind = skipTypes(n[0].typ, abstractVar).kind` doesn't skip range types. Anyway the old logic is not good enough that as long as there are int/float types, `if` is generated instead of `case` no matter whether there are range of int/float. It causes performance downgrade.

```nim
import std/jsconsole
case 1
of 1:
  console.log 1
of 2:
  console.log 2
else:
  console.log 3
```
generates wrongly formated JS code
```js
if (1 == 1){  console.log(1);
  }
else if (1 == 2){  console.log(2);
  }
else{
  console.log(3);
  }

```
Instead of beautifully formatted switch-case
```js
switch (1) {
case 1:
  console.log(1);
  break;
case 2:
  console.log(2);
  break;
default: 
  console.log(3);
  break;
}
```
