### ISSUE TITLE
Move sequtils.insert & sequtils.delete into system module

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#2349]
In the [sequtils module](http://nim-lang.org/sequtils.html), there are two procs
- [insert(dest: var seq; src: openArray; pos = 0)](http://nim-lang.org/sequtils.html#insert,seq[T],openArray[T],int)
- [delete(s: var seq; first = 0; last = 0)](http://nim-lang.org/sequtils.html#delete,seq[T],int,int)

These should be moved into the system module, for consistency with (and by analogy with):
- [add(x: var seq; y: openArray)](http://nim-lang.org/system.html#add,seq[T],openArray[T])

which is the append-openArray-to-var-seq version of:
- [insert(x: var seq; item: T; i = 0)](http://nim-lang.org/system.html#insert,seq[T],T,int)
- [delete(x: var seq; i: int)](http://nim-lang.org/system.html#delete,seq[T],int)
- [add(x: var seq; y: T)](http://nim-lang.org/system.html#add,seq[T],T)

I was oblivious to the existence of these alternate versions of `insert` & `delete` until I accidentally stumbled across the `sequtils` module again.

**Comment by Araq** [comment]
No. System.nim needs to get smaller, not larger. We could improve the docs though.

**Comment by jboy** [comment]
Hm.  I agree with your general assertion that system.nim needs to get smaller.  I've often wished it was smaller in the past:  There are so many procs & types in there, I find it very difficult to read through all the procs & types, remember them all, and build a mental model of the ordering & relationships between them.  Maybe you're also coming at it from a maintenance perspective, or from a "minimising the chance of random unexpected proc interactions" perspective.

But (to state the obvious for the benefit of the issue tracker), system.nim is the container of all of Nim's built-ins: both "built-in global functions" and "built-in methods for built-in types", so you will want many of these to remain automatically-imported by default.

I've often wished that system.nim could be split up into a collection of smaller sub-modules (eg: `builtincmp.nim`, `builtinconsts.nim`, `builtinseq.nim`, `builtinset.nim`, `builtinstring.nim`, `builtintypes.nim`, `builtinvars.nim`, etc.), but I don't know that this would actually solve any underlying maintenance problem.

Can I ask what your plan is to make system.nim smaller?

(If you've already written this up somewhere, please feel free just to point me to it.)

**Comment by narimiran** [comment]
I'm closing this since it was rejected 3.5 years ago.
