### ISSUE TITLE
Using another parameter as default value to a template parameter cause internal error

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#23506]
### Description

Defining a template with a parameter with a default value that is another parameter cause internal error.
Example code:
```nim
template foo(x: int; y = x) =
  echo x, y

foo(1)
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-04-16
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 549ef24f35213302ba66e9e786c18ab9146940ee
active boot switches: -d:release

### Current Output

```text
templatedefparam.nim(1, 26) Error: internal error: expr: param not init x_536870914
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

### Expected Output

```text
Compiles or show better compile error message.
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
template foo(x: int; y = x) =
  echo x, y

foo(1)
```
