### ISSUE TITLE
theindex.html should also group procs by the type of the first parameter and the return value

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#2350]
Looking through [the documentation index, theindex.html](http://nim-lang.org/theindex.html), I can't see any section that groups procs by the type of the first parameter or by the type of the return value.  I think this auto-generated information should be added, and would be immensely valuable.

For example, there are procs that act upon (ie, first parameter) or create/return (ie, return-value) `seq[T]` distributed over the `system` & `sequtils` modules (and who knows where else).  There are procs that act upon or create/return `string` in the `system`, `strutils` & `unicode` modules (and who knows where else).

I think it would be immensely valuable, if there were a "by type" index, where you could look up the type `seq[T]` or `string` or whatever, and see a section listing all procs that accepted that type as a first parameter, and a section listing all procs that returned that type as the return value.

**Comment by andreaferretti** [comment]
Now there is a search feature in the stdlib, and it can be used to group procs by type, as requested here.

The request here is about theindex.html, though. Does it make still sense? I think the new features kind of supercede this request, but maybe it would still be worthwhile to have the whole index by type

**Comment by dom96** [comment]
IMO theindex isn't for browsing, but for searching so I consider this request implemented.
