### ISSUE TITLE
Add overloads of find(openArray) & contains(openArray) for multi-element contiguous matches

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#2351]
Add an overload of [find(a: T; item: S): int](http://nim-lang.org/system.html#find,T,S) for openArray multi-element contiguous matches; something like:
- `find[T](haystack: openArray[T]; needle: openArray[T]): int`

Likewise, add an overload of [contains(a: openArray; item: T): bool](http://nim-lang.org/system.html#contains,openArray[T],T) for openArray multi-element contiguous matches; something like:
- `contains[T](haystack: openArray[T]; needle: openArray[T]): bool`

These would be useful in general -- and specifically as analogues in the [unicode module](http://nim-lang.org/unicode.html) of the `string` operations [find(s, sub: string; start: int = 0): int](http://nim-lang.org/strutils.html#find,string,string,int) and [contains(s, sub: string): bool](http://nim-lang.org/strutils.html#contains,string,string) in the [strutils module](http://nim-lang.org/strutils.html).

**Comment by Araq** [comment]
Not happening anytime soon. PRs are always welcome.
