### ISSUE TITLE
sequtils templates (mapIt, etc) don't work with set card

### ISSUE THREAD

**Issue by remigijusj** [nim-lang/Nim#23514]
### Description

Using "it" templates with set cardinality method produces incorrect, random results (different for each run).

```nim
import std/sequtils

let s: seq[set[char]] = @[{'a', 'b', 'c'}, {'d'}]
echo s.mapIt(card(it))
```

The example uses `mapIt`, but other templates `filterIt`, `countIt`, ... also work incorrectly.
In contrast, using map with proc works fine. With packedsets, it also works fine. 
Only the combination of set type and templates produces incorrect results. 

### Nim Version

Nim Compiler Version 2.0.4 [Windows: amd64]
Compiled at 2024-03-28
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
@[48, 49]
# low integers, randomly varying on each run, always differ by 1
```

### Expected Output

```text
@[3, 1]
```

### Additional Information

Tested with multiple Nim versions:
- 1.6 series work correctly upto 1.6.12 (the issue started with version 1.6.14)
- 2.0 series do not work correctly

The same behavior on Linux (Ubuntu).

**Comment by beef331** [comment]
Related to https://github.com/nim-lang/Nim/issues/23478 ?

**Comment by ringabout** [comment]
Indeed fixed by https://github.com/nim-lang/Nim/pull/23437
