### ISSUE TITLE
Enum overloading regression 

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#23579]
### Description

```nim
type
  A = enum t
  B = enum t

proc test(_: set[A]) = discard

test { t }
```

enum sets in arguments cant resolve overloading on devel, but can on stable.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-05-06
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 1ef4d04a1e56f67d85559a7964e9467df06bc2d7

### Current Output

```text
Error: ambiguous identifier: 't' -- use one of the following:
  A.t: A
  B.t: B
```

### Expected Output

Compiles without error, as it does on stable.

**Comment by juancarlospaco** [comment]
!nim c

```nim
type
  A = enum t
  B = enum t

proc test(_: set[A]) = discard
test { t }
```

**Comment by SolitudeSF** [comment]
this is the offending commit https://github.com/nim-lang/Nim/commit/480e98c479035a8a19ff543bace3616d202e1ea2
didnt look into this, but it seems like we are trading one error for another?

**Comment by SolitudeSF** [comment]
looks like it only worked by chance, because correct enum was the first one, so not really a regression.
