### ISSUE TITLE
Ref array causing Segfault

### ISSUE THREAD

**Issue by marcgehman** [nim-lang/Nim#23582]
### Description

I'm trying to run this simple code:
This occurs if we have an array (plain or ref) within a ref object:
```
type
    TestObj = ref object
        numbers: array[0..100, float]

const size = 100
proc initTestObj(): TestObj =
    for i in 0..<size:
        result.numbers[i] = 3.0
var test = initTestObj()
```
Again, this does not occur if we use a plain array and a plain object.

I tried with different memory managers: orc, arc, refc, and all have same issue.

Is this an expected behavior? 

EDIT: removed the comment regarding basic ref arrays, as I was able to fix that by using new(), however, using arrays within a ref object still causes segfaults.

### Nim Version

2.0.0 and 2.0.4

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
const size = 100
var numbers: ref array[0..size, float]
for i in 0..<size:
    numbers[i] = 3.0
```

**Comment by jrfondren** [comment]
> removed the comment regarding basic ref arrays, as I was able to fix that by using new(),

 The fix for the updated code is the same:

```nim
type
    TestObj = ref object
        numbers: array[0..100, float]

const size = 100
proc initTestObj(): TestObj =
  new(result)
  for i in 0..<size:
      result.numbers[i] = 3.0
var test = initTestObj()  # no error
``` 

I thought you were saying that this *worked* without `new` in your original post, and that surprised me much more than that code not working, where it's expected behavior: refs are initialized to `nil`.

Default values: <https://nim-lang.org/docs/manual.html#statements-and-expressions-var-statement>

**Comment by marcgehman** [comment]
Ah okay, thanks for the clarification! Given the implicit nature of the `result` variable, I was expecting it to automatically handle creating with `new`.
