### ISSUE TITLE
[feature] inherited finalizers should be called automatically

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#236]
if a class introduces a finalizer all instances of classes that inherit from that class should call that finalizer when they are collected by the GC.

``` nimrod
#modul  A
type
  TFoo* = ref object of TObject
    data: Pointer

proc newFoo* (): TFoo =
  new (result, proc (self: TFoo) = dealloc(self.data))
  result.data = alloc0(1000)

#modul B
type
  TBar* = ref object of TFoo
    name: string

proc newBar(): TBar =
  new(result)
  result.name = "bar"

var b = newBar()

b = nil
```

in the above example, if TBar doesn't know about TFoo implementation it will introduce a memory leak.

**Comment by Araq** [comment]
This has been implemented for 0.18.
