### ISSUE TITLE
Illegal capture on async proc (except when the argument is `seq`)

### ISSUE THREAD

**Issue by sid-code** [nim-lang/Nim#2361]
If I try to compile the following (I'm aware that the code doesn't do what it intends to):

``` nimrod
proc sleepsort(xs: seq[int]) {.async.} =
  for x in xs:
    await sleepAsync(x)
    echo x
```

The compiler tells me this:

```
Error: illegal capture 'xs'
```

Now, if I change `varargs` to `seq`, it works fine. Is there a reason for this?

I've noticed that this happens for many data types, not just `varargs`. I just find it strange that it should work for `seq`.

**Comment by Araq** [comment]
You cannot capture openArray/varargs or 'var T' as that would violate memory safety.
