### ISSUE TITLE
Add "origin" parameter to fseek-wrapper setFilePos

### ISSUE THREAD

**Issue by woodgiraffe** [nim-lang/Nim#2363]
The current way to seek in a FileStream is via the [setFilePos](https://github.com/Araq/Nim/blob/devel/lib/system/sysio.nim#L270) proc, which calls [fseek](http://en.cppreference.com/w/c/io/fseek) from c's stdio, but doesn't expose the origin parameter and instead always calls it with 0, which is the SEEK_SET constant (Beginning of file).

In order to seek from the current position however it is necessary to pass the SEEK_CUR constant.

I propose to add the 3 "origin" constants from stdio to "lib/system/sysio.nim" and add an additional origin arg to setFilePos, defaulting to SEEK_SET.

**Comment by andreaferretti** [comment]
Now there exists a parameter `relativeTo` that does exactly this
