### ISSUE TITLE
Gc_ref(x: string) and Gc_ref[T](x: seq[T]) doesn't exists anymore ?

### ISSUE THREAD

**Issue by Alogani** [nim-lang/Nim#23634]
### Description

Hello,

Gc_ref(x: string) and Gc_ref[T](x: seq[T]) both throws a type mismatch on nim 2.0 when using --mm:orc or --mm:arc (works with --mm:refc)

It seems a pretty strong problem when interfacing with unmanaged memory efficiently

### Nim Version

nim v2.0.4 - fedora linux

### Current Output

```
var x1 = "nim"
GC_ref(x1)

var x2 = @["is nice"]
GC_ref(x2)

>>> nim r myfile.nim
Expression: GC_ref(x1)
  [1] x1: string

Expected one of (first mismatch at [position]):
[1] proc GC_ref[T](x: ref T)
```

**Comment by beef331** [comment]
With orc and arc `seq` and `string` are not ref counted, they're treated as value types which own their memory.

**Comment by Alogani** [comment]
Ok, I understand.
A bit deceiving we can't access more easily their internals.

But if this is not a bug, I close this issue. Thanks
