### ISSUE TITLE
The stdout.write doesn't print to terminal until new line symbol is sent

### ISSUE THREAD

**Issue by Xkonti** [nim-lang/Nim#23632]
### Description

The `stdout.write` doesn't actually print out to the terminal window until the `\n` newline symbol has been "written". Because of that, it's impossible to print something to terminal output without moving the cursor to the new line.

Procs and macros that depend on writing to `stdout` have the same issue, for example [`styledWrite` in `std/terminal`](https://nim-lang.org/docs/terminal.html#styledWrite.m%2CFile%2Cvarargs%5Btyped%5D).

### Nim Version

Nim Compiler Version 2.0.4 [Linux: amd64]
Compiled at 2024-03-28

### Operating system

Windows 11 WSL2 Ubuntu 22.04.3 LTS

### Current Output

```text
stdout.write("1") # Terminal: ""
sleep(1000)
stdout.write("2") # Terminal: ""
sleep(1000)
stdout.write("3") # Terminal: ""
sleep(1000)
stdout.write("\n4") # Terminal: "123\n"
sleep(1000)
stdout.write("5") # Terminal: "123"
sleep(1000)
stdout.write("6") # Terminal: "123"
sleep(1000)
stdout.write('\n') # Terminal: "123\n456\n"
```

### Expected Output

```text
stdout.write("1") # Terminal: "1"
sleep(1000)
stdout.write("2") # Terminal: "2"
sleep(1000)
stdout.write("3") # Terminal: "3"
sleep(1000)
stdout.write("\n4") # Terminal: "123\n4"
sleep(1000)
stdout.write("5") # Terminal: "123\n45"
sleep(1000)
stdout.write("6") # Terminal: "123\n456"
sleep(1000)
stdout.write('\n') # Terminal: "123\n456\n"
```

### Additional Information

The equivalent in Zig works properly in the same WSL2 environment:

```zig
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("1", .{});
    std.time.sleep(1_000_000_000); // 1 second in nanoseconds
    try stdout.print("2", .{});
    std.time.sleep(1_000_000_000);
    try stdout.print("3", .{});
    std.time.sleep(1_000_000_000);
    try stdout.print("\n4", .{});
    std.time.sleep(1_000_000_000);
    try stdout.print("5", .{});
    std.time.sleep(1_000_000_000);
    try stdout.print("6", .{});
    std.time.sleep(1_000_000_000);
    try stdout.print("\n", .{});
}
```

The `flushFile` proc makes it work as intended:
```nim
stdout.write("1")
stdout.flushFile()
sleep(1000)
stdout.write("2")
stdout.flushFile()
sleep(1000)
stdout.write("3")
stdout.flushFile()
sleep(1000)
stdout.write("\n4")
stdout.flushFile()
sleep(1000)
stdout.write("5")
stdout.flushFile()
sleep(1000)
stdout.write("6")
stdout.flushFile()
sleep(1000)
stdout.write('\n')
stdout.flushFile()
```

**Comment by Araq** [comment]
Use `flushFile`.

**Comment by demotomohiro** [comment]
This explains why:
https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin

**Comment by Xkonti** [comment]
> This explains why: https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin

Thank you @demotomohiro !
