### ISSUE TITLE
C++ generation issue when wrapping constructors

### ISSUE THREAD

**Issue by mantielero** [nim-lang/Nim#23656]
### Description

When wrapping C++ constructors it looks like commas might be missing

### Nim Version

2.0.2

### Current Output

```text
154 |         nimln_(22);     result = opencascade::handle<Geom_CartesianPoint>((new Geom_CartesianPoint(((float) (x_p0))((float) (y_p1))((float) (z_p2)))));
```
```


### Expected Output

```text
154 |         nimln_(22);     result = opencascade::handle<Geom_CartesianPoint>((new Geom_CartesianPoint(((float) (x_p0)), ((float) (y_p1)), ((float) (z_p2)))));
```
```


### Possible Solution

_No response_

### Additional Information

https://forum.nim-lang.org/t/11649

I am sorry I am not good in C++ to reproduce this bug. Installing opencascade library (in Archlinux: `yay -S opencascade`) and then with my [occt.nim repo](https://github.com/mantielero/occt.nim/) the following example fails:
```
cd occt.nim/examples/01 Modeling Data
nim cpp -r geom_01_cartesian_point
```

**Comment by jmgomez** [comment]
Took a look at the library and doesnt seem to be properly wrapped. What is this supposed to be doing? 

```nim
proc cnew*[T](x: T): ptr T {.importcpp: "(new '*0#@)", nodecl.}
```

What you should do instead is: 
```nim

proc newCpp*(T: typedesc): ptr T {.importcpp:"new '*0()".}
proc newCpp*[P](T: typedesc, p:P): ptr T {.importcpp:"new '*0(@)".}
proc newCpp*[P, P2](T: typedesc, p:P, p2:P2): ptr T {.importcpp:"new '*0(@)".}
proc newCpp*[P, P2, P3](T: typedesc, p:P, p2:P2, p3:P3): ptr T {.importcpp:"new '*0(@)".}
proc newCpp*[P, P2, P3, P4](T: typedesc, p:P, p2:P2, p3:P3, p4:P4): ptr T {.importcpp:"new '*0(@)".}

let test = newCpp(Axis)
let test2 = newCpp(Axis, Point(x:2), Direction(x:3))
````

I also noticed all your `constructor` calls are marked with `cdecl`. Not that it matters for the codegen, but there is no need for `cdecl` at all.

**Comment by mantielero** [comment]
Thanks for taking a look to the library.

I think I just copy/pasted from the [manual](https://nim-lang.org/docs/manual.html#importcpp-pragma-importcpp-for-procs). Where it talks about `#@`:
![image](https://github.com/nim-lang/Nim/assets/1116064/8c4c1179-cb8c-4c72-8f2c-da51c45c28a7)

About `cdecl`, I used `c2nim` for the wrapping, so I believe it was generated by it. To be honest, for me it is not very clear what `cdecl` does. I am not a computer scientist, so I have big gaps (that I try to improve little by little).

**Comment by mantielero** [comment]
I tried to make a minimal example with my library:
```nim
{.passL:"-lTKG3d -lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}

type
  GeomCartesianPoint* {.importcpp: "Geom_CartesianPoint",
                       header: "Geom_CartesianPoint.hxx", bycopy.} = object
  # Handle*[T] {.importcpp: "opencascade::handle<\'0>",
  #             header: "Standard_Handle.hxx", bycopy, pure, inheritable.} = object

# proc newHandle*[T](thePtr: ptr T): Handle[T] {.cdecl, constructor,
#     importcpp: "opencascade::handle<\'*0>(@)", header: "Standard_Handle.hxx".}


proc ccnew*[T](x: T): ptr T {.importcpp: "(new '*0#@)", nodecl.}

proc cnew*(T: typedesc): ptr T {.importcpp:"new '*0()".}
proc cnew*[P1](T: typedesc, p:P1): ptr T {.importcpp:"new '*0(@)".}
proc cnew*[P1, P2](T: typedesc, p:P1, p2:P2): ptr T {.importcpp:"new '*0(@)".}
proc cnew*[P1, P2, P3](T: typedesc, p:P1, p2:P2, p3:P3): ptr T {.importcpp:"new '*0(@)".}
proc cnew*[P1, P2, P3, P4](T: typedesc, p:P1, p2:P2, p3:P3, p4:P4): ptr T {.importcpp:"new '*0(@)".}

proc nnewGeomCartesianPoint*(x: float; y: float; z: float): GeomCartesianPoint {.
    cdecl, constructor, importcpp: "Geom_CartesianPoint(@)", header: "Geom_CartesianPoint.hxx".}

#var bHdl = newHandle( cnew nnewGeomCartesianPoint( 1.1, 2.2, 3.3 ) )  # : Handle[GeomCartesianPoint]  | Handle[geom_types.GeomCartesianPoint]
var myPtr = cnew(GeomCartesianPoint, 1.1, 2.2, 3.3 )  # <-- Compiles
var myPtr2 = cnew GeomCartesianPoint(1.1, 2.2, 3.3 )  # <-- Do not compile
```

If I use `cnew(GeomCartesianPoint, 1.1, 2.2, 3.3 ) `, it compiles and I believe is coherent with the signature that you just suggested, but `cnew GeomCartesianPoint(1.1, 2.2, 3.3 )` does not compile:
```sh
Error: attempting to call routine: 'GeomCartesianPoint'
```

**Comment by jmgomez** [comment]
Interesting, I didnt know about `#@` :) But if it tries to inline the expression, I can see why it's prone to fail. 

> cnew GeomCartesianPoint(1.1, 2.2, 3.3 ) does not compile

Of course it doesnt compile, it's invalidad Nim syntax. The first argument is the type you want to instantiate, the rest are the parameters to pass into the C++ constructor call.

**Comment by mantielero** [comment]
So what is the way forward? Should I file a different report about `#@` not working? Is  `#@` no longer valid and should the manual be updated?

For my library, I think I will remove the whole `cnew` thing and just wrap: `importcpp:"new Whatever(xxx)"`

**Comment by jmgomez** [comment]
> So what is the way forward? Should I file a different report about `#@` not working?

Does the example in the manual as it is works? I dont know what is supposed to support or not but the description it has in the manual definitely makes me think it's a bit fragile. 

 > For my library, I think I will remove the whole `cnew` thing and just wrap: `importcpp:"new Whatever(xxx)`"
 
 That's an unnecessary typing exercise :) What's wrong with my proposal `newc(Whatever, xxx)`?  You can also use it like this in case you like it more:
 ```nim
 Axis.newCpp(Point(x:2), Direction(x:3)) # generates-> new Axis(p, d)
 Whatever.newCpp(xxx) # generates -> new Whatever(xxx) (Exactly the same as your importcpp example)
 ```

**Comment by mantielero** [comment]
I would say now it is not working (at least for me). 
```nim
type
  Foo = object
  
proc cnew*[T](x: T): ptr T {.importcpp: "(new '*0#@)", nodecl.}

# constructor of 'Foo':
proc constructFoo(a, b: cint): Foo {.importcpp: "Foo(@)".}

let x = cnew constructFoo(3, 4)
```
Its compilation:
```sh
  117 |         nimlf_(8, "/home/jose/tmp/a.nim");      x__a_u11 = (new tyObject_Foo__M7RlQ7ihvx1euRj2eFyyWg(((int)3)((int)4)));
      |                                                                                                      ~~~~~~~~^~~~~~~~

```

But it used to work. And it is a behaviour defined in the manual, so I would say that now it is bug (given that it is not deprecated AFAIK). 

Another question is what the manual says: `This is only required to circumvent a limitation of the current code generator.`. So it don't know if this was thought as a temporary solution until the code generator were improved.

About my library, I barely use `cnew`. I used it at the very beginning. The thing that I don't like about the proposal is that I think it looks better:
```nim
newAxis(Point(x:2), Direction(x:3))
```
I think this was the reason why I used `cnew` at the begining and then I used `importcpp:"new Whatever(xxx)"`.

**Comment by jmgomez** [comment]
Yes, I guess it's a bug but as I said, no idea how that supposed to work and what the limitations are. That said, `This is only required to circumvent a limitation of the current code generator` dont think is a current limitation as previously shown. Not sure when that was written down though. @Araq do you have input on this?

**Comment by Araq** [comment]
> But it used to work. And it is a behaviour defined in the manual, so I would say that now it is bug

Yeah, this should continue to work.

>  @Araq do you have input on this?

"The limitations of the current code generator" I was referring to had to do with the introduction of temporaries that the code generator loves to do. That is still the case and it often conflicts with C++'s design. The idea was that `.constructor` is only necessary because the codegen loves to use temporaries.

**Comment by jmgomez** [comment]
> The idea was that `.constructor` is only necessary because the codegen loves to use temporaries.

I see, but `constructor` should be only used outside the context of `new` (which is another issue, but we should at least warn when it's misused like that). There is no temp issue when using `new` directly (imported or with a template like I shown above). 
So maybe Im missing something but I see no point on that `#@` operator/syntax outside keeping retro compatibility

**Comment by juancarlospaco** [comment]
Long time ago there was an idea to improve that kind of pattern for FFI, to allow use strformat (?).
