### ISSUE TITLE
compiler does not throw "... has to be used or discarded" error when else branch raises error

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#23677]
### Description

can catch this
```nim
if true:
  0
else: 
  echo "wow"
```

but not this:
```nim
if true:
  0
else: 
  raise newException(ValueError, "err")
```

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-06-04
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
compiles and runs
```

### Expected Output

```text
Error: expression '0' is of type 'int literal(0)' and has to be used (or discarded)
```

### Additional Information

same with `case of`

**Comment by hamidb80** [comment]
!nim c

```nim
if true:
  0
else: 
  raise newException(ValueError, "err")
```

**Comment by metagn** [comment]
~~This is intentional, the `else` branch cannot have a value since it halts execution~~ I misunderstood, the if expression is supposed to be a statement here

**Comment by hamidb80** [comment]
> This is intentional, the `else` branch cannot have a value since it halts execution

The problem is that if you write
```nim
0 
echo "Hi"
```

The compiler says you have to use it or discard it.

but when you write:

```nim
if   a: 0
elif b: 1
elif c: 2
else: raise ...

echo "Hi again"
```

it compiles!!!
isn't the `if branch` an expression?

**Comment by juancarlospaco** [comment]
> ```nim
> 0 
> echo "Hi"
> ```

Theres clearly an unused integer literal there.

**Comment by hamidb80** [comment]
> Theres clearly an unused integer literal there.

what about here?
```nim
if   a: 0
elif b: 1
elif c: 2
else: raise ...
```

**Comment by metagn** [comment]
Sorry, I misunderstood, the issue is that the if expression compiles in a statement context.

**Comment by SolitudeSF** [comment]
Why is this wrong?
