### ISSUE TITLE
[Feature] a new lint rule to require that each block must end with #. or # or a new line.

### ISSUE THREAD

**Issue by EdSaleh** [nim-lang/Nim#23674]
### Summary

[Feature] a new lint rule to require that each block must end with #. or # or a new line.

### Description

Hello,

Create a new lint rule to require that each block must end with # or #. or a new line.
This would work as a curly braces blocks found in C style languages.
Also, this could also be used to reformat space-block based code by code editor to fix any indentation issues.

Users can also use a different word symbol or use a new line for this purpose. (#., #, #/, newline, etc). The user has the option to select the keyword they would like to have for the project.

Example:

```python
import string
def atbash(sequence: str) -> str:
    """
    Example
    """
    output = ""
    for i in sequence:
        extract = ord(i)
        if 65 <= extract <= 90:
            output += chr(155 - extract)
        #.
        elif 97 <= extract <= 122:
            output += chr(219 - extract)
        #.
        else:
            output += i
        #.
    #.
    return output
#.
```

There are cases where strict block guarantees is required. Also, when copying python code sometimes spacing is not aligned correctly and having code with this style with editor support, editor would fix incorrect spacing easily.

```python
if(True):
print(True)
print(True)
#
if(True):
print(True)
print(True)
#
```

OR

```python
if(True):
print(True)
print(True)
#.
if(True):
print(True)
print(True)
#.
```
would be aligned correctly by the editor to:

```python
if(True):
 print(True)
 print(True)
#
if(True):
 print(True)
 print(True)
#
```
OR
```python
if(True):
 print(True)
 print(True)
#.
if(True):
 print(True)
 print(True)
#.
```
Users can also use new line instead of # or #. if they require and configure it to their requirements.

Thank you,

**Comment by SirOlaf** [comment]
Low effort and really bad idea, you opened the same issue in pylint (+ a couple more) and didn't even bother changing the example code or mentions of python in this one. Looks like someone trying to have fake activity on github.

**Comment by EdSaleh** [comment]
> Low effort and really bad idea, you opened the same issue in pylint (+ a couple more) and didn't even bother changing the example code or mentions of python in this one. Looks like someone trying to have fake activity on github.

I posted the proposal to different project since I see it could be useful for these projects as well, with similar indentation code block code style.
