### ISSUE TITLE
Memory leak after Exception in parseJson

### ISSUE THREAD

**Issue by jschweinsberg** [nim-lang/Nim#2367]
It seems that there is something wrong with garbage collection after `parseJson` tries to parse an invalid JSON string.
It throws an Exception (which is the right behaviour) and aborts parsing, but some memory isn't freed.

Example:
```nimrod
import json, posix

for i in 0..100000:
  try:
    discard parseJson("{invalid")
  except:
    echo "Error"

while true:
  discard sleep(1)
```

top shows 473MB memory usage...

**Comment by dom96** [comment]
This might not be the cause but you should use the ``sleep`` in the ``os`` module not the one in the ``posix`` module.

**Comment by jschweinsberg** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Oh okay. Good to know.

I'm only using `sleep` to keep the example running.  There is no
`sleep` in the original code where I've found the leak.

So I'm sure that `sleep` is not the cause. ;)

On 20.03.2015 20:09, Dominik Picheta wrote:
> This might not be the cause but you should use the |sleep| in the
> |os| module not the one in the |posix| module.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Araq/Nim/issues/2367#issuecomment-84102579>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJVDHGCAAoJECtRK1atTbmizHQP/0hBCLqx2/BOSO3bJvzyVOEv
pHoS5KdrHvTvviTojnMkbQRhW6hth9okICj7YukBQT5TV4FYpe3mFPT25sNQKKMf
cJqGJqaTD55QGYasjV6vp84BPF+qKCBSKHBOw6fSYVocem8ZFi9kyPXwxheeCf72
MKC+JnqAhEYeAkpKLs0F+mkEJsB5q1TIztWDf16aPvlydE56vn6KrMcfBoWl0D8C
JJcBS1NHjL1sNUyg3PreA5Dn+6rL3uG6A6PnBmiwg6mp1aGC9QIEBynmaMdlF73N
AV9+DdgUN1UbPHINrYj2hZpuJLqlTekiFu/gnEByVES82kapwUfR6IVxTuISKzxB
QWv1t+ntdtMTJzZLyNp18RU7pm994EpBMAiozGc9eTgFcoCTDbipHM1/3sPg3puf
GkV38Rmhize+eXD89AlsZtdnWK0P9ZjEpNmYoyPn9+dSPf2gJjzeiO288RBkj/xb
RLKOz/JHgYHnQILfP5ottDCluKsf6GA3YCLeNluSHLby7HoGAVbUX4bQJAeeLGkC
ZxOUwBFr7hLYPiYADdRAQCcavI1N3pf5O73QygNNyBZlfSC+GHZHXf9pNQ6vjoEv
/SG704WS/DVD7beFZiQIrmMkc8h2poGsrkxTDzZJKqBpS440uKfNLPrCqdlj5k7y
KrIQR+STVowqdfTyuwjA
=vtUX
-----END PGP SIGNATURE-----
