### ISSUE TITLE
Ensuring that symbols defined in an importing module are referenced

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#2368]
One use case would be to ensure that a wrapper uses all the symbols of a binding except ones that are excluded.

**Comment by Varriount** [comment]
Could you explain this a bit?

**Comment by fowlmouth** [comment]
sounds like the opposite of deadCodeElim

**Comment by EXetoC** [comment]
@fowlmouth it does?
@Varriount The idea is to generate an error with a message containing all the symbols that have neither been referenced nor excluded. This simplifies the task of making sure that a wrapper is up-to-date with the associated bindings.

**Comment by kirbyfan64** [comment]
This would be optional, right?

**Comment by EXetoC** [comment]
Of course :stuck_out_tongue:
