### ISSUE TITLE
SIGSEGV with object variants and RTTI

### ISSUE THREAD

**Issue by alex65536** [nim-lang/Nim#23690]
### Description

The simplest reproducer I have found by now is:

```nim
import std/sequtils

type
  SomeObj* = object of RootObj

  Item* = object
    case kind*: 0..1
    of 0:
      a*: int
      b*: SomeObj
    of 1:
      c*: string

  ItemExt* = object
    a*: Item
    b*: string

proc do1(x: int): seq[(string, Item)] =
  result = @[("zero", Item(kind: 1, c: "first"))]

proc do2(x: int, e: ItemExt): seq[(string, ItemExt)] =
  do1(x).map(proc(v: (string, Item)): auto = (v[0], ItemExt(a: v[1], b: e.b)))

echo do2(0, ItemExt(a: Item(kind: 1, c: "second"), b: "third"))
```

This code stably leads to segfault under my amd64 Linux machine (tested both on `2.0.4` and `devel`)

### Nim Version

```
$ nim -v
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-06-06
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 69d0b73d667c4be9383f29cda3f70e411995d9af
active boot switches: -d:release
```

Also reproducible on stable `2.0.4`.

### Current Output

```text
Traceback (most recent call last)
/home/user/repro.nim(24) repro
/home/user/repro.nim(22) do2
/home/user/.choosenim/toolchains/nim-#devel/lib/system/alloc.nim(1068) dealloc
/home/user/.choosenim/toolchains/nim-#devel/lib/system/alloc.nim(967) rawDealloc
/home/user/.choosenim/toolchains/nim-#devel/lib/system/alloc.nim(770) addToSharedFreeListBigChunks
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```

### Expected Output

```text
@[("zero", (a: (kind: 1, c: "first"), b: "third"))]
```

### Additional Information

Some extra debugging shows more details:
- replacing `sequtils.map` with a loop makes the issue go away
- compiling with `--mm:refc` doesn't reproduce the bug, but `--mm:arc` and `--mm:orc` do

Debugging points out that `eqcopy` implementation is likely at fault. The compiled C code is as follows:
```c
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___repro_u284)(tyObject_ItemExt__D8Kw4o1swHAWDzvwwWvsFw* dest_p0, tyObject_ItemExt__D8Kw4o1swHAWDzvwwWvsFw* src_p1) {
        tyObject_Item__jnMhVK55Yw3PPq6Gy9aXzMQ colontmp_;
        colontmp_ = (*dest_p0).a;
        nimZeroMem((void*)(&(*dest_p0).a), sizeof(tyObject_Item__jnMhVK55Yw3PPq6Gy9aXzMQ));
        (*dest_p0).a = TM__ckn2SibXCdoGNfJOD0JenA_5;
        (*dest_p0).a.kind = (*src_p1).a.kind;
        switch ((*dest_p0).a.kind) {
        case ((NI)0):
        {
                (*dest_p0).a._kind_1.a = (*src_p1).a._kind_1.a;
        }
        break;
        case ((NI)1):
        {
                eqcopy___system_u2621((&(*dest_p0).a._kind_2.c), (*src_p1).a._kind_2.c);
        }
        break;
        default: __builtin_unreachable();
        }
        switch (colontmp_.kind) {
        case ((NI)0):
        {
        }
        break;
        case ((NI)1):
        {
                if (colontmp_._kind_2.c.p && !(colontmp_._kind_2.c.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_._kind_2.c.p);
}
        }
        break;
        default: __builtin_unreachable();
        }
        eqcopy___system_u2621((&(*dest_p0).b), (*src_p1).b);
}
```

It does the following:
- zeroes memory under `dest_p0->a`
- copies some pre-defined constant `TM__ckn2SibXCdoGNfJOD0JenA_5` into it. As far as I understand, it is the default value of `Item`, and as a default value, it has `kind: 0` and, because `kind: 0` contains `SomeObj`, the contents of the union are filled with some RTTI data
- then we assign `kind`, switching the active union element (`(*dest_p0).a.kind = (*src_p1).a.kind`). Note that nothing is zeroed at the moment, and all the RTTI data are still in the union
- then we try to copy to the string, which has the same offset in the union as RTTI data, and copying damages these RTTI data
- program crashes :(

**Comment by alex65536** [comment]
!nim c

**Comment by alex65536** [comment]
!nim c

```nim
import std/sequtils

type
  SomeObj* = object of RootObj

  Item* = object
    case kind*: 0..1
    of 0:
      a*: int
      b*: SomeObj
    of 1:
      c*: string

  ItemExt* = object
    a*: Item
    b*: string

proc do1(x: int): seq[(string, Item)] =
  result = @[("zero", Item(kind: 1, c: "first"))]

proc do2(x: int, e: ItemExt): seq[(string, ItemExt)] =
  do1(x).map(proc(v: (string, Item)): auto = (v[0], ItemExt(a: v[1], b: e.b)))

echo do2(0, ItemExt(a: Item(kind: 1, c: "second"), b: "third"))
```

**Comment by ringabout** [comment]
@alex65536 wow, your insights are really helpful. I think it's mostly likely that `copy` needs to zero memery the union before assignement. I'm working on it. Thank you very much!

**Comment by ringabout** [comment]
It crashed with 1.6.16 with `--mm:orc -d:useMalloc`

**Comment by alex65536** [comment]
Digging further into the compiler code, I noticed the following:
1. [Here](https://github.com/nim-lang/Nim/blob/09b5ed251e4f9a47af7a0176ea4632bebdfd506a/compiler/liftdestructors.nim#L239-L252) is the algorithm for copy-assignment of object variants. The main take here is that we move the old object into the new location and call `wasMoved` for the old object.
2. `wasMoved` is basically implemented [here](https://github.com/nim-lang/Nim/blob/09b5ed251e4f9a47af7a0176ea4632bebdfd506a/compiler/ccgexprs.nim#L2308-L2309). Among other things, it calls `resetLoc()`, which in our case ([code](https://github.com/nim-lang/Nim/blob/09b5ed251e4f9a47af7a0176ea4632bebdfd506a/compiler/cgen.nim#L509-L525)) generates `nimZeroMem` + default-initialization.
3. Zeroing memory is OK, but re-intialization with the default value for this moved-out object is actually the source of this bug.

I am not proficient in the compiler internals at all, so everything below this text in this comment is just a wild guess from a person who has seen the compiler code today for the first time:
- I am unsure whether zeroing memory is OK, because the next part of the code calls copy assign for each sub-variant, and I don't know how destructors of old values behave when they encounter zeroed memory (maybe everything is OK, but again, I don't know the compiler internals well).
- Another solution would probably be resetting the location before doing recursive assignment inside the case statement (not outside). It could be slower, but seems more reliable for me.

**Comment by beef331** [comment]
> how destructors of old values behave when they encounter zeroed memory

Destructors are supposed to be written in such a way that 0'd memory indicates "this was moved"

**Comment by alex65536** [comment]
> Destructors are supposed to be written in such a way that 0'd memory indicates "this was moved"

OK, thank you, then zeroing is a nice idea indeed :)

And what happens if a `=copy()` implementation hooked by user receives zeroed memory as a destination? Or is there anything that prevents such thing from happening?

**Comment by beef331** [comment]
You call `=destroy` then copy the data over, there is no special logic for data that is 0'd `=wasMoved` should disarm `=destroy`.

**Comment by Araq** [comment]
> Destructors are supposed to be written in such a way that 0'd memory indicates "this was moved"

Note that we're moving away from 0'd memory to the more abstract "`=wasMoved`/default state".
