### ISSUE TITLE
dom addEventListener has ambiguous types

### ISSUE THREAD

**Issue by dObbOb11** [nim-lang/Nim#23698]
### Description

The addEventListener procedure from the dom library in Nim fails at compile time, seemingly no matter what arguments I provide. It simply tells me my call to the proc has `no type (or is ambiguous)`. Here is a small code sample that reproduces the issue:
```nim
import dom

proc handleKeyDown(ev: Event) {.asmNoStackFrame.} =
    echo "keydown!"

discard window.addEventListener("keydown", handleKeyDown)
```

### Nim Version

Nim Compiler Version 2.0.4 [Windows: amd64]
Compiled at 2024-03-28
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
<path to my nim file>(6, 32) Error: expression 'addEventListener(window, "keydown", handleKeyDown, false)' has no type (or is ambiguous)
```

### Expected Output

```text
It compiles to JS code correctly
```

**Comment by beef331** [comment]
You're attempting to discard a procedure that returns `void`.
