### ISSUE TITLE
Subscript notation [] doesn't work with property procs

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#237]
Following the information about reference and pointer types in the first part of the tutorial and mixing it with the properties section of the second part of the tutorial I found out that the subscript notation doesn't work with the property methods which are meant to *hide* the real variables.

I'm writting these procs because I want to export them to C (see http://forum.nimrod-code.org/t/96), but it seems that I'm forced to use then the notation `object[].accesor` which is discouraged in the first part of the tutorial. See the coments in the test case I came up with at https://github.com/gradha/Nimrod/commit/fafb645265e0072bcd1b580ad129272540259ff4 where I would expect the code from both PNormal and PPrivate to work the same, but the compiler barks on the use of PPrivate.

**Comment by Araq** [comment]
Auto-deref works with ``.experimental``.
