### ISSUE TITLE
Deadloop in Windows, `os.sleep(-1)`

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#23732]
### Description

```Nim
when defined(windows):
  import std/os
  sleep(-1)  # <- deadloop
```

BTW, on POSIX, it just returns immediately, as sleep calls `nanosleep`, which exits with errno set as `EINVAL` for negative values.

### Nim Version

At least from 1.6.14 to 2.1.1 and devel

### Possible Solution

Two direction:

1. raises a exception on all platforms when milsecs is negative.
2. add check in Windows, returns immediately for negative values

### Additional Information

In Python, time.sleep raises ValueError on negative value.

Maybe we can raises OSError as Nim's sleep is in `std/os` if the first direction is accepted.

On the other hand, golang's time.Sleep will  return immediately for negative values.

**Comment by litlighilit** [comment]
BTW, It seems to deadloop as os.sleep calls Sleep on Windows, whose parameter type, is in fact `DWORD`, an uint32, but Nim wraps it as int32, so pass negative int just becomes a large unsigned int.

Still a `DWORD` relative issue...

**Comment by Araq** [comment]
What's wrong with `-1` meaning "forever"?

**Comment by litlighilit** [comment]
on posix, it returns immediately. (and set errno to `EINVAL`)

**Comment by litlighilit** [comment]
> What's wrong with -1 meaning "forever"?

And strictly speaking, not forever, but a very large uint amount of time.

e.g. Currently on Windows:
`sleep(-1)` in fact does `Sleep(4294967295)`

a.k.a. while `sleep(-1)` means sleep forever is somewhat reasonable, it means sleep for 49 days on Windows and sleep for no time on POSIX.

**Comment by juancarlospaco** [comment]
`sleep` should take `Natural`.
