### ISSUE TITLE
`setLen(0)` allocates memory causing performance regression

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23742]
### Description

https://github.com/status-im/Nim/blob/v2.0.6/lib/system/sysstr.nim#L223

```
var vvvv: string
vvvv.setLen(0) # causes allocation
```

this is a regression from earlier - `setLen` should obvious not allocate anything in this case. `mm:orc` is ok.

### Nim Version

2.0.6/refc

**Comment by ringabout** [comment]
Which version doesn't allocate memory in refc?

That said, how to measure performance downgradation? Or would you mind checking whether https://github.com/nim-lang/Nim/pull/22690 is the cause

**Comment by arnetheduck** [comment]
> That said, how to measure performance downgradation?

This is on upgrade from 1.6 to 2.0.

In this case it was found by backtracing where allocations are coming from, in a virtual machine, and seeing [this](https://github.com/status-im/nimbus-eth1/blob/bd2ca07da64f8f8954dd3ed7ecf30b6fde9e73b4/nimbus/evm/interpreter/op_handlers/oph_call.nim#L230) line turn up which didn't before.. 

that said, what could be happening is that in 1.6, the allocation was happening somewhere else before and now doesn't, causing the accounting to change from another line to here, ie maybe before the setLen was a noop because it was operating on an already-allocated seq.

ie this might not be a setLen regression per se, but rather part of a broader change in behavior. 

Anyway, allocating in setLen(0) doesn't make sense - the reason to use `setLen` like this is to reuse existing memory if it's allocated already but if it's not, it shouldn't be - same for `newSeq(0)`, `@[]` and so on (which may happen deep in generic/parametrized code and shouldn't do anything).

#22690 is a good change in general, ie it's causing improvements overall, anecdotally at least (we're still testing).

**Comment by Araq** [comment]
> Anyway, allocating in setLen(0) doesn't make sense - the reason to use setLen like this is to reuse existing memory if it's allocated already but if it's not, it shouldn't be

Correct!
