### ISSUE TITLE
Overload resolution changes if void return

### ISSUE THREAD

**Issue by Graveflo** [nim-lang/Nim#23776]
### Description

Since this snippet behaves the way I would expect:
```nim
proc p[n:static[int]](a: array[n, char]):bool=true
proc p*[T, IDX](a: array[IDX, T]):bool=false

var g: array[32, char]
assert p(g)
```

I would expect this to not crash:
```nim
proc p[n:static[int]](a: array[n, char])=discard
proc p*[T, IDX](a: array[IDX, T])=discard

var g: array[32, char]
discard p(g)
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-05-14
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: c91b33aaba4234d8abdf04af102d71b86e285c58
active boot switches: -d:release

### Current Output

```text
Error: expression 'p(g)' has no type (or is ambiguous)
```

**Comment by beef331** [comment]
Why do you expect it not to error? You are doing `discard void`.

**Comment by Araq** [comment]
No bug here. Also "crash" is an entirely inappropriate word for "compiler produced a reasonable readable error message".
