### ISSUE TITLE
default value in object variants does not work when embedded in another object

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#23770]
### Description

If a field in an object has an object variant type, the default value from that object variant type is ignored.

```nim
type
  Enum = enum A, B
  Object = object
    case a: Enum
    of A:
      integer: int = 200
    of B:
      time: string
  Simple = object
    v = -1
  Another = object
    o = Object(a: A)
    v: Simple

echo Object(a: A)
echo Another()
```

### Nim Version

Nim Compiler Version 2.1.1 [MacOSX: arm64]
Compiled at 2024-06-21
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 2bef08774f00692963f2a00243e4287caa7572ee
active boot switches: -d:release

### Current Output

```text
(a: A, integer: 200)
(o: (a: A, integer: 0), v: (v: -1))
```

### Expected Output

```text
(a: A, integer: 200)
(o: (a: A, integer: 200), v: (v: -1))
```

**Comment by ringabout** [comment]
Here is the problem: const object variants don't work

> Const case objects never were supposed to compile, there is logic in the compiler to detect and reject that but as we can see it's not triggered.

ref https://github.com/nim-lang/Nim/issues/8015#issuecomment-491424148

related to https://github.com/nim-lang/Nim/issues/11862
