### ISSUE TITLE
Cyclic proc calls causes infinite memory usage

### ISSUE THREAD

**Issue by madonuko** [nim-lang/Nim#23827]
### Description

```nim
# Forward-declaring procedure (let's call this proc "A")
proc error*() {.raises: [].}

# called in another function (let's call this proc "B")
proc env*(key: string, default: string = ""): string {.raises: [].} =
  error()

# A used before its implmentation
# removing this line fixes the issue
let DESTDIR = env("", "")

# later, A's implementation uses B
proc error*() = discard env("", "")
```

To reproduce, paste the above code into `test.nims`, then run `nim test.nims` while having something like `htop` opened. IMPORTANT: you should press `Ctrl+C` before this freezes your computer. This TAKES IN RAM INFINITELY!  
Remove `let DESTDIR = env("", "")` and try again, the issue should disappear.

(Discovered this issue from https://github.com/FyraLabs/nimsutils/commit/996d390e22f2264e20a97accc9aac66652e760a8#diff-4ef83205176043d82365aa5e90186a2b45de4b2e4a07e4ed3b4c5a1e29cb6dbfR32)

### Nim Version

Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
—————————————————————
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-07-12
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 22ba5abd635a1b50c76acb0b80097a663cdf97c9
active boot switches: -d:release

### Current Output

```text
Hint: used config file '/home/mado/.choosenim/toolchains/nim-2.0.8/config/nim.cfg' [Conf]
Hint: used config file '/home/mado/.choosenim/toolchains/nim-2.0.8/config/config.nims' [Conf]

(program runs forever)
```

### Possible Solution

I mean at least this should not freeze the entire computer and should have a recursion limit of some sort?

### Additional Information

On 1.6.20:
```
Hint: used config file '/home/mado/.choosenim/toolchains/nim-1.6.20/config/nim.cfg' [Conf]
Hint: used config file '/home/mado/.choosenim/toolchains/nim-1.6.20/config/config.nims' [Conf]
/home/mado/repos/libhelium.nim/test.nims(4, 3) Error: cannot evaluate at compile time: a
```
Should be unrelated I think.

**Comment by Araq** [comment]
It should produce an error "cannot evaluate".

**Comment by ringabout** [comment]
> I mean at least this should not freeze the entire computer and should have a recursion limit of some sort?

It has a limitation though, you can try `--maxLoopIterationsVM:10000`

**Comment by ringabout** [comment]
It doesn't freeze my PC though; it gives an error like 5s-10s on my wsl2 (Tested with 2.0.8 and devel)

![image](https://github.com/user-attachments/assets/711b1820-7990-4caf-b8ec-a13a56eab83e)

It is consistent with 1.6.16 in a static block

```nim
static:
  # Forward-declaring procedure (let's call this proc "A")
  proc error() {.raises: [].}

  # called in another function (let's call this proc "B")
  proc env(key: string, default: string = ""): string {.raises: [].} =
    error()

  # A used before its implmentation
  # removing this line fixes the issue
  let DESTDIR = env("", "")

  # later, A's implementation uses B
  proc error() = discard env("", "")
```

**Comment by madonuko** [comment]
Interesting… for me this happens even with nimsuggest…

**Comment by ringabout** [comment]
> for me this happens even with nimsuggest…

nimsuggest does freeze computer => https://github.com/nim-lang/Nim/issues/11679

**Comment by madonuko** [comment]
That's not what I mean, opening that file with vscode (which runs `nimsuggest`) has the same behaviour as running the file with `nim` directly; it takes in an infinite amount of memory.

It's worse because if you try to kill nimsuggest, it just respawns automatically.

**Comment by ringabout** [comment]
Does it run forever, if you put it in a file with a `.nim` extension and execute `nim e test.nim` ?

**Comment by madonuko** [comment]
```
$ nim e test.nim

Hint: used config file '/home/mado/.choosenim/toolchains/nim-2.0.8/config/nim.cfg' [Conf]
Hint: used config file '/home/mado/.choosenim/toolchains/nim-2.0.8/config/config.nims' [Conf]
stack trace: (most recent call last)
19999903 calls omitted

/home/mado/test.nim(6, 8) env
/home/mado/test.nim(13, 28) error
/home/mado/test.nim(6, 8) env
/home/mado/test.nim(13, 28) error
…
/home/mado/test.nim(6, 8) env
/home/mado/test.nim(13, 28) error
/home/mado/test.nim(13, 28) Error: interpretation requires too many iterations; if you are sure this is not a bug in your code, compile with `--maxLoopIterationsVM:number` (current value: 10000000)
```

**Comment by ringabout** [comment]
> That's not what I mean, opening that file with vscode (which runs nimsuggest) has the same behaviour as running the file with nim directly; it takes in an infinite amount of memory.

> It's worse because if you try to kill nimsuggest, it just respawns automatically.

What if you disable nimsuggest in the settings and reopen the file in the vscode?

**Comment by ringabout** [comment]
> That's not what I mean, opening that file with vscode (which runs nimsuggest) has the same behaviour as running the file with nim directly; it takes in an infinite amount of memory.

> It's worse because if you try to kill nimsuggest, it just respawns automatically.

What if you disable nimsuggest in the settings and reopen the file in the vscode?

**Comment by madonuko** [comment]
Turns out I was impatient; after letting my computer freeze for straight up 5 minutes `nim test.nims` finally spits out the error message…

**Comment by madonuko** [comment]
But I mean, at what cost though? My computer has 16G of memory with 8G of zram, so I think the current `maxLoopIterationsVM` value is too high.

**Comment by ringabout** [comment]
It's probably some bug of numsuggest. I always disable nimusggest. `nim test.nims` doesn't use much memory on my PC (16G Ram + Intel 12700h)

3s on my WSL2

![image](https://github.com/user-attachments/assets/40925453-1a5f-4bdf-94a4-992c49042ce0)

**Comment by madonuko** [comment]
I think it has something to do with nim itself instead, which affects nimsuggest

**Comment by ringabout** [comment]
Now it gives a `Error: maximum call depth for the VM exceeded; if you are sure this is not a bug in your code, compile with --maxCallDepthVM:number (current value: 2000)`
