### ISSUE TITLE
nimsuggest crashes when using `--mm:arc/orc` and if an object that contains `string` or `seq` is constructed

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/Nim#23867]
### Description

nimsuggest crashes when using `--mm:arc/orc` and if an object that contains `string` or `seq` is constructed.

```nim
# config.nims
--mm: orc
```

```nim
type ObjStr = object
  s: string

let ostr = ObjStr() # <-- nimsuggest crashes
```

```nim
type ObjSeq = object
  s: seq[int]

let oseq = ObjSeq() # <-- nimsuggest crashes
```

This is really bad because many object contains `string` or `seq`. For example any function that raises an exception crashes nimsuggest because the `Exception` contains `msg: string`

### Nim Version

Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-07-20
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 31ee75f10e6482cd482d329507190ac850eee2cf
active boot switches: -d:release

### Current Output

```text
> chk src/main.nim
chk     skUnknown               Hint    ???     0       -1      ">> (toplevel): import(dirty): /home/..../src/main.nim [Processing]"      0

fatal.nim(53)            sysFatal
Error: unhandled exception: liftdestructors.nim(639, 5) `t.destructor != nil`  [AssertionDefect]
```

### Expected Output

```text
no error
```

### Additional Information

The crash happens here:
https://github.com/nim-lang/Nim/blob/31ee75f10e6482cd482d329507190ac850eee2cf/compiler/liftdestructors.nim#L991-L1010

In the function `useSeqOrStrOp`:
https://github.com/nim-lang/Nim/blob/31ee75f10e6482cd482d329507190ac850eee2cf/compiler/liftdestructors.nim#L638-L640

**Comment by SirOlaf** [comment]
Have you tried with `--v3`

**Comment by doongjohn** [comment]
> Have you tried with `--v3`

`--v3` and `--v4` does not crash.
