### ISSUE TITLE
Nim should ideally cache compilation results for multiple build targets

### ISSUE THREAD

**Issue by dhasenan** [nim-lang/Nim#2387]
I have separate executables for unittests and my main project. When I compile either one several times in a row, Nim caches everything and life is fast. When I compile one after the other, the cache is at least partially erased and much recompilation ensues.

Example: https://gist.github.com/dhasenan/6fff33d7a6da0877cef9

A workaround is to use different nim caches for each target, which results in two compilations for each change rather than a smattering of compilations per invocation of the build script.

Another workaround would be to use file modification times to judge whether recompilation is necessary. That's a bit flaky, though.

**Comment by def-** [comment]
This also significantly slows down the compilation of Nim's MAL implementation, so I'm interested in a solution as well: https://github.com/kanaka/mal

**Comment by Araq** [comment]
So use the ``--nimcache`` command line option to get separate caches?

**Comment by andreaferretti** [comment]
I think the suggestion by @Araq is the most reasonable thing, is there anything to do here?

**Comment by Araq** [comment]
@andreaferretti @genotrance is working on this.

**Comment by Araq** [comment]
This has been implemented.
