### ISSUE TITLE
Compiler infers `sink` in return type from `auto`

### ISSUE THREAD

**Issue by alex65536** [nim-lang/Nim#23902]
### Description

In #18881, there was a separate issue in the "Additional information" section.

And, even though #18881 itself is fixed, this issue is not.

The reproducer is as follows:

```nim
proc foo(a: sink string): auto = (a, a)

proc bar(a: sink int): auto = return a
```

### Nim Version

```
Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-07-27
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 39629a1adcbcc822508acc3983f444328f90dd85
active boot switches: -d:release
```

### Current Output

```text
Error: invalid type: 'sink string' in this context: '(sink string, sink string)' for result
```

### Expected Output

```text
(code compiles)
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
proc foo(a: sink string): auto = (a, a)
proc bar(a: sink int): auto = return a
```

**Comment by juancarlospaco** [comment]
@Araq See https://github.com/nim-lang/Nim/issues/23902#issuecomment-2255962058 says [your PR introduced the bug](https://github.com/nim-lang/Nim/pull/15690) (?)

**Comment by Araq** [comment]
My PR only made it visible.

**Comment by ringabout** [comment]
I'm working on it
