### ISSUE TITLE
`c_isnan` is not available for objectiveC backend

### ISSUE THREAD

**Issue by janAkali** [nim-lang/Nim#23922]
### Description

Any code that imports `std/math` library fails to compile to objectiveC with "Error: undeclared identifier: 'c_isnan'"  
Example:
```Nim
# main.nim
import std/math
```
```
$ nim objc main.nim
```
I've reproduced this error on Nim 2.0.6 and 2.0.8.
Nim v2.0.0, v2.0.2 and v2.0.4 - work fine.  

Source of error:  
Function `isNan` defaults to `c_isnan` on any backend other than `js` (including `objC`):
https://github.com/nim-lang/Nim/blob/c97a20ce492f335067c3e53731f60023fb39ae9d/lib/pure/math.nim#L193-L205

But `c_isnan` is only available for `c` and `cpp` backends:
https://github.com/nim-lang/Nim/blob/c97a20ce492f335067c3e53731f60023fb39ae9d/lib/pure/math.nim#L66-L70

### Nim Version

Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
----------------------------------------------
Nim Compiler Version 2.0.6 [Linux: amd64]
Compiled at 2024-06-17
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c00e8e71e0c8465b5a5257c76c674b803273b222
active boot switches: -d:release

### Current Output

```text
Hint: used config file '/home/archargelod/.local/share/grabnim/nim-2.0.8/config/nim.cfg' [Conf]
Hint: used config file '/home/archargelod/.local/share/grabnim/nim-2.0.8/config/config.nims' [Conf]
...........................................................................
/home/archargelod/.local/share/grabnim/nim-2.0.8/lib/pure/math.nim(281, 11) template/generic instantiation of `isNaN` from here
/home/archargelod/.local/share/grabnim/nim-2.0.8/lib/pure/math.nim(204, 20) Error: undeclared identifier: 'c_isnan'
candidates (edit distance, scope distance); see '--spellSuggest':
 (1, 3): 'isNaN'
```

### Additional Information

OS: x86_64 Linux OpenSUSE Tumbleweed
ObjC Compiler: gcc-objc v13-2.2

**Comment by litlighilit** [comment]
Maybe simply appending ` or defined(objc)` to `c_isnan` branch check would solve this.

As objc can invoke C's math.h


And I think it better to define a constant like
```nim
const CLike = defined(c) or defined(cpp) or defined(objc)
```

and use `when Clike` to replace all such things. (the similar cases may occur in many places.)
