### ISSUE TITLE
Bad error message when importing two modules with the same unqualified name

### ISSUE THREAD

**Issue by dhasenan** [nim-lang/Nim#2392]
```
mkdir -p a b
touch a/foo.nim b.foo.nim
```

Then in the current directory, file ab.nim:

```
import a.foo
import b.foo
```

Error message: `b/foo.nim(1, 1) Error: redefinition of 'foo'`

The actual error is in in ab.nim, line 2: importing a second module with the same name as a previously imported module, without renaming either.

Of course, due to #2391, renaming the imports doesn't help. At the moment, I would have to recommend prefixing the name of each module with the name of the library it is from; eg instead of having a module "yaml.parser" you would name it "yaml.yaml_parser".

**Comment by Araq** [comment]
Or: You use Nimble packages.

**Comment by andreaferretti** [comment]
`b/foo.nim(1, 2) Error: module names need to be unique per Nimble package; module clashes with <local_path>/a/foo.nim`

It seems this has been fixed
