### ISSUE TITLE
passing string to `parseutils.parseFloat(openArray[char],...)` in compile-time leads to inner error `FieldDefect`

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#23936]
### Description

When using `parseutils.parseFloat` with openArray as its parameter and string as argument, and it's called at compile-time (in static block or in const section),

the compiler crashes and complains (see `Current Output` below)

```Nim
import std/parseutils
func parsePyFloat*(
    a: openArray[char],  # here must be openArray instead of string to reproduce this bug
    res: var BiggestFloat): int =
  parseFloat(a, res)

static:
  var f = 0.0
  discard "1.0".parsePyFloat f
```

### Nim Version

Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-07-21
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 9ca646acd4565a72a7115777d58b115787b19b0c
active boot switches: -d:release

As well as 2.0.4, 2.0.6

### Current Output

```text
fatal.nim(53)            sysFatal
Error: unhandled exception: field 'node' is not accessible for type 'TFullReg' using 'kind = rkInt' [FieldDefect]
```

### Expected Output

```text
(compiles)
```

### Possible Solution

not know,

but for users, there're workaround: 

- convert `string` to `openArray` explicitly via `toOpenArray`
- use `parseFloat(string,..)` variant or strutils.parseFloat

### Additional Information

If using `parseBiggestFloat` instead of `parsesFloat`,
the error becomes:

```
fatal.nim(53)            sysFatal
Error: unhandled exception: field 'sons' is not accessible for type 'TNode' using 'kind = nkSym' [FieldDefect]
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
import std/parseutils
func parsePyFloat*(a: openArray[char], res: var BiggestFloat): int =
  parseFloat(a, res)

static:
  var f = 0.0
  discard "1.0".parsePyFloat f
```
