### ISSUE TITLE
Put 0 in range[M..N] that would otherwise exclude it

### ISSUE THREAD

**Issue by kuche1** [nim-lang/Nim#23943]
### Description

I'm able to put a 0 in a range that shouldn't allow this value
```
type limited_int = range[1..20]
var d: limited_int;
echo d
```

### Nim Version

Nim Compiler Version 2.0.4 [Linux: amd64]
Compiled at 2024-05-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 08d9e6af883be33239a88b36f6f5416e06a9ea84
active boot switches: -d:release

### Current Output

```text
`0`
```

### Expected Output

```text
`1` or an error
```

**Comment by juancarlospaco** [comment]
!nim c

```nim
type limited_int = range[1..20]
var d: limited_int
doAssert d == 1, $d
```
