### ISSUE TITLE
Invalid type in `nkWhenStmt`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23945]
### Description

The following snippet (from md5.nim):

```nim
template slice(s: string, a, b): openArray[uint8] =
  when nimvm:
    # toOpenArray is not implemented in VM
    var s2 = newSeq[uint8](s.len)
    for i in 0 ..< s2.len:
      s2[i] = uint8(s[i])
    s2
  else:
    s.toOpenArrayByte(a, b)
```

creates an `nkWhenStmt` whose `typ` is `tySequence` which is wrong, specially for the runtime branch (`s` is an `openArray`) - this disturbs the type analysis done in `nlvm` (since it uses `typ` to determine how to load the source.

### Nim Version

2.0.8

**Comment by litlighilit** [comment]
Not related to this issue itself but a fact about `"toOpenArray is not implemented in VM"`:

this's implemented, at least since v2.0.4

**Comment by beef331** [comment]
> Not related to this issue itself but a fact about `"toOpenArray is not implemented in VM"`:
> 
> this's implemented, at least since v2.0.4

*Specifically #20586 if anyone is taking notes*

**Comment by ringabout** [comment]
I think `when nimvm` should check whether the type of the two branch is compatible

```nim
proc slice(s: string, a: int, b: int): seq[uint8] =
  when nimvm:
    # toOpenArray is not implemented in VM
    var s2 = newSeq[uint8](s.len)
    for i in 0 ..< s2.len:
      s2[i] = uint8(s[i])
    s2
  else:
    12

proc bar(x: openArray[uint8]) =
  echo x

proc foo =
  bar slice("12343455", 1, 2)

foo()
```

**Comment by arnetheduck** [comment]
> I think when nimvm should check whether the type of the two branch is compatible

they are compatible in the sense that a hidden conversion should be present in the first branch that coerces it to the "most generic type" - "more or less" one could imagine the following to be deduced as `uint32`:
```nim
when a:
  uint16(42)
else:
  uint32(42)
```

because the second branch is the more general of the two - ie it's not enough to decide that they're compatible - the AST also needs to hold an entry for the thing that converts them to become that most general type.

**Comment by ringabout** [comment]
It doesn't work with `if expression`:

```nim
template slice(s: string, a, b): openArray[uint8] =
  if true:
    # toOpenArray is not implemented in VM
    var s2 = newSeq[uint8](s.len)
    for i in 0 ..< s2.len:
      s2[i] = uint8(s[i])
    s2
  else:
    s.toOpenArrayByte(a, b)

proc bar(x: openArray[uint8]) =
  echo x

proc foo =
  bar slice("12343455", 1, 2)

foo()
```

```
type mismatch: got 'openArray[byte]' for 'toOpenArrayByte("12343455", 1, 2)' but expected 'seq[uint8]'
```

**Comment by arnetheduck** [comment]
well, there exists an obvious way in which it could/should work, for both `if` and `when` ;)

**Comment by ringabout** [comment]
Yeah, someone needs to modify the relation between seqs and openarrays etc. in the function `commonType`. I will add check for nimvm first.

**Comment by arnetheduck** [comment]
>  I will add check for nimvm first.

the example is from the nim std lib, ie code "out there" is already likely being written like this
