### ISSUE TITLE
compiling 32bit nim failed

### ISSUE THREAD

**Issue by Kothric** [nim-lang/Nim#23972]
### Description

compiling 32bit nim failed from commit 298ada3412c9cf5971abc2b3b891b9bb8612e170

commit 298ada3412c9cf5971abc2b3b891b9bb8612e170
Author: ringabout <43030857+ringabout@users.noreply.github.com>
Date:   Thu Aug 15 19:28:13 2024 +0800

    fixes #23954; uint8 > 8 bit at compile-time (#23955)

    fixes #23954

**gcc version** 13.2.0 (MinGW-W64 i686-msvcrt-posix-dwarf, built by Brecht Sanders, r8)

### Nim Version

f:\dev\nimdev>nim -v
Nim Compiler Version 2.1.9 [Windows: i386]
Compiled at 2024-08-17
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 06b25bd2c40194f4b00d1d664492b6aed1dee91c
active boot switches: -d:release

### Current Output

```text
f:\dev\nimdev>koch boot -d:release --skipUserCfg --skipParentCfg --hints:off
iteration: 1
bin\nim.exe c  --skipUserCfg --skipParentCfg -d:nimKochBootstrap --nimcache:nimcache/r_windows_i386 -d:release --skipUserCfg --skipParentCfg --hints:off --noNimblePath --compileOnly compiler\nim.nim
f:\dev\nimdev\compiler\modulegraphs.nim(14, 11) Warning: imported and not used: 'algorithm' [UnusedImport]
f:\dev\nimdev\compiler\semfold.nim(424, 39) Error: type mismatch
Expression: maskBytes(val, getSize(g.config, dstTyp))
  [1] val: Int128
  [2] getSize(g.config, dstTyp): BiggestInt

Expected one of (first mismatch at [position]):
[2] proc maskBytes(arg: Int128; numbytes: int): Int128

FAILURE
```

### Expected Output

```text
Expect compiling pass.
```

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/23980
