### ISSUE TITLE
Recent codegen bug passing pointer expressions to inline iterators

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#23982]
### Description

```Nim
iterator `..`(a, b: ptr int16): ptr int16 = discard
var a: seq[int16] #; let p = a[0].addr
var b: seq[ptr int16]
for x in a[0].addr .. b[1]: # `p .. b[1]` works
  discard
```

### Nim Version

Devel head a4dff1a03e514946b419fd9af0ac08b7a4b40a50 fails

### Current Output

```text
/u/cb/.cache/nim/itrBug_d/@mitrBug.nim.c:239:15: error: 
      cannot take the address of an rvalue of type 'NI16 *' (aka 'short *')
  239 |                 colontmp_ = &(&a__itr66ug_u4->data[((NI)0)]);
      |                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```


### Expected Output

```text
Should compile.  Bug exhibition program does not test for any follow-on logic errors.
```

### Possible Solution

bisect might be a first start, but I did not do this.

### Additional Information

Works (or at least compiles) in nim-1.6.12 with both arc and refc.  Works with `{.closure.}` on the iterator.  Also works if the commented out `p` is used instead of the inline expression.  But as written, fails with both `--mm=arc` and `--mm=refc` on devel.

**Comment by ringabout** [comment]
!nim c
```nim
iterator `..`(a, b: ptr int16): ptr int16 = discard
var a: seq[int16] #; let p = a[0].addr
var b: seq[ptr int16]
for x in a[0].addr .. b[1]: # `p .. b[1]` works
  discard
```

**Comment by ringabout** [comment]
!nim c
```nim
iterator `..`(a, b: ptr int16): ptr int16 = discard
var a: seq[int16] #; let p = a[0].addr
var b: seq[ptr int16]

try:
  for x in a[0].addr .. b[1]: # `p .. b[1]` works
    discard
except IndexDefect:
  discard
```

**Comment by c-blake** [comment]
FWIW, I was using gcc-13.3 (not gcc-11.4), and an old (contemporaneous!) nim-1.6.12 build I keep around was also generating C code compilable with also clang-18.1.8 and `tcc` as well as that `gcc`.  ~~Perhaps I should remove the "Recent" qualifier in the title, if nim-core cannot repro any success case, though?~~

**Comment by c-blake** [comment]
Oh, wait - your bisect is actually trying to *run* the code, not merely compile it.  I didn't really make the example "successfully runnable".  An index defect is expected, as written.  To be more clear, it was a C-compiles vs. C backend failure I am trying to report.  So, in your bisect log summaries it seems to fail somewhere between "stable" and "devel".

Edit: and it works (compiles, not runs) at least as far back as nim-0.20.2 for me.  So, this seems like a recent regression.  It could maybe be tagged as such since both of the runaction bisects show that.

As to priority, I don't know.. the context was in porting a C code base that does a lot of "pointer arithmetic loops" and I was attempting to port the code to Nim in stages where one stage was doing similar loops without re-doing all the indexing and there may be a workaround for the Nim bug with "simple" expressions (as per comments in the code example).

**Comment by juancarlospaco** [comment]
@c-blake Ideally code repro samples should be, as small and simple as possible, runnable, and assertive.

**Comment by c-blake** [comment]
I did try to make it as simple as possible.  The starting point was hundreds of lines!  If you have a way to simplify more while preserving the C compilation success/failure patterns then by all means, go for it!
