### ISSUE TITLE
nim devel branch ./build_all.sh fails to compile `md5.nim`

### ISSUE THREAD

**Issue by doongjohn** [nim-lang/Nim#23991]
### Description

nim devel branch ./build_all.sh fails to compile `md5.nim`
`commit e38cbd3c846a8e95bed0d709e4d61cc1ad5279b2 (HEAD -> devel, origin/devel, origin/HEAD)`

### Nim Version

--

### Current Output

```text
❯ ./build_all.sh
bin/nim_csources_86742fb02c6606ab01a532a0085784effb2e753e exists.

cmd: rm -f bin/nim

cmd: cp bin/nim_csources_86742fb02c6606ab01a532a0085784effb2e753e bin/nim

cmd: bin/nim_csources_86742fb02c6606ab01a532a0085784effb2e753e -v
Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2023-01-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5b20f0685c71e68ab08f7a1941f7e160d91e538f
active boot switches: -d:release

cmd: bin/nim c --noNimblePath --skipUserCfg --skipParentCfg --hints:off koch
/home/..../nim/tools/deps.nim(1, 11) Warning: imported and not used: 'strutils' [UnusedImport]

cmd: ./koch boot -d:release --skipUserCfg --skipParentCfg --hints:off
iteration: 1
bin/nim c  --skipUserCfg --skipParentCfg -d:nimKochBootstrap --nimcache:nimcache/r_linux_amd64 -d:release --skipUserCfg --skipParentCfg --hints:off --noNimblePath --compileOnly compiler/nim.nim
/home/..../nim/compiler/modulegraphs.nim(14, 11) Warning: imported and not used: 'algorithm' [UnusedImport]
/home/..../nim/compiler/semdata.nim(18, 17) Warning: imported and not used: 'astalgo' [UnusedImport]
/home/..../nim/compiler/concepts.nim(14, 13) Warning: imported and not used: 'astalgo' [UnusedImport]
bin/nim jsonscript --noNimblePath --nimcache:nimcache/r_linux_amd64 -d:release --skipUserCfg --skipParentCfg --hints:off compiler/nim.nim
iteration: 2
compiler/nim1 c  --nimcache:nimcache/r_linux_amd64 -d:release --skipUserCfg --skipParentCfg --hints:off --noNimblePath --compileOnly compiler/nim.nim
/home/..../nim/dist/checksums/src/checksums/md5.nim(227, 21) template/generic instantiation of `slice` from here
/home/..../nim/dist/checksums/src/checksums/md5.nim(114, 10) template/generic instantiation of `slice` from here
/home/..../nim/dist/checksums/src/checksums/md5.nim(109, 6) Error: type mismatch: got 'openArray[byte]' for 'toOpenArrayByte($input, 0, len - 1)' but expected 'seq[uint8]'
FAILURE
```

### Expected Output

```text
no error
```

**Comment by ringabout** [comment]
Probably, you need to delete the `dist` directory?

**Comment by doongjohn** [comment]
Deleting the dist directory fixed the issue. Do I need to manually delete the dist directory every time I build?

**Comment by qqtop** [comment]
In a program compiled today with latest devel
nim -v
Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-08-21
Copyright (c) 2006-2024 by Andreas Rumpf

/.nimble/pkgs2/checksums-0.1.0-54473dcb2db81cc36fc6ac36ab65df0e19443510/checksums/md5.nim(116, 6) Error: type mismatch: got 'openArray[byte]' for 'toOpenArrayByte($input, 0, len - 1)' but expected 'seq[byte]'

This did not fail with Nim compiled at 2024-08-20

**Comment by ringabout** [comment]
> Do I need to manually delete the dist directory every time I build?

The compiler uses cached deps. But it could be improved in the future by comparing commit hashes to invalidate outdated deps.

**Comment by ringabout** [comment]
@qqtop I released a new version for checksums => https://github.com/nim-lang/checksums/releases/tag/v0.2.0

**Comment by qqtop** [comment]
Thank you, now it works .
Also, many thanks for your amazing work for Nim !!

**Comment by ringabout** [comment]
will be fixed in https://github.com/nim-lang/Nim/pull/24189
