### ISSUE TITLE
Output executable is not updated after changing build mode

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#24008]
### Description

When recompile code with changing build mode without changing code 3 times, third rebuild doesn't update the executable file.
Example code to see build mode.
testbuild.nim:
```nim
when defined(release):
  echo "This is release build"
elif defined(danger):
  echo "This is danger build"
else:
  echo "This is debug build"
```

### Nim Version

Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-08-24
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 4ef06a5cc56f6ef32b8ac1e7c11592597406486a
active boot switches: -d:release

### Current Output

```text
$ nim c -r -d:release testbuild.nim
...
This is release build
$ nim c -r -d:debug testbuild.nim
...
This is debug build
$ nim c -r -d:release testbuild.nim
...
This is debug build
```

### Expected Output

```text
$ nim c -r -d:release testbuild.nim
...
This is release build
$ nim c -r -d:debug testbuild.nim
...
This is debug build
$ nim c -r -d:release testbuild.nim
...
This is release build
```

### Possible Solution

Save output executable in the cache directory?

**Comment by metagn** [comment]
Debug and release builds are cached separately, the cache seems to 1. check if the nim files' [checksums match](https://github.com/nim-lang/Nim/blob/4ef06a5cc56f6ef32b8ac1e7c11592597406486a/compiler/extccomp.nim#L1068-L1069), 2. check if the output file path [is the same](https://github.com/nim-lang/Nim/blob/4ef06a5cc56f6ef32b8ac1e7c11592597406486a/compiler/extccomp.nim#L1063). Maybe we can store the output file checksum as well

**Comment by juancarlospaco** [comment]
I think for performance it should be just a short CRC, not a secure hash,
you can even append the CRC hash to the filename because it is very short.
eg https://github.com/juancarlospaco/nim-crc32/blob/master/src/crc32.nim#L79
