### ISSUE TITLE
js codegen bug for  `case` statement with just `else` branch

### ISSUE THREAD

**Issue by choltreppe** [nim-lang/Nim#24031]
### Description

```nim
case 0
else: discard
```
generates
```js
else {}
```
whithout preceding `if`

### Nim Version

Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release

**Comment by juancarlospaco** [comment]
!nim js

```nim
case 0
else: discard
```

**Comment by juancarlospaco** [comment]
@bung87 See https://github.com/nim-lang/Nim/issues/24031#issuecomment-2319108737 looks like your PR introduced a bug https://github.com/nim-lang/Nim/pull/20548

**Comment by metagn** [comment]
Could also just disallow this, not a critical regression
