### ISSUE TITLE
Pushing a hint off "disables" code reordering

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#24053]
### Description

```nim
{.push hint[ConvFromXtoItselfNotNeeded]: off.}

{.experimental: "codeReordering".}

const
  foo: MyType = 1

type
  MyType* = int

{.pop.}
```

The code above doesn't compile. It throws:
```
Error: undeclared identifier: 'MyType'
```

----

If you remove the hint push, then it compiles correctly:

```nim
{.experimental: "codeReordering".}

const
  foo: MyType = 1

type
  MyType* = int
```

### Nim Version

- Nim 2.0.9
- Nim devel

### Expected Output

```text
Code compiles.
```

**Comment by ringabout** [comment]
The parser now parses the whole module at once. `codeReordering` is enabled for the whole module. The statements that are before `{.experimental: "codeReordering".}` are not ignored. 

Besides, as shown in the https://github.com/nim-lang/Nim/issues/18288, push interferes with experimental: "codeReordering"
