### ISSUE TITLE
StringStream does not work at build time

### ISSUE THREAD

**Issue by Nycto** [nim-lang/Nim#24054]
### Description

I expect to be able to use `newStringStream` for build time evaluation, like this:

```
import streams

static:
  var s = newStringStream("foo bar baz")
  echo s.readStr(3)
```

### Nim Version

Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release

### Current Output

```text
Error: unhandled exception: field 'sym' is not accessible for type 'TNode' using 'kind = nkNilLit' [FieldDefect]
```
```


### Expected Output

```text
I expect it to print "foo"
```

### Additional Information

This appears to be happening because the implementation isn't being set when `nimvm` is enabled:

https://github.com/nim-lang/Nim/blob/c948ab9b8511ef2db31bf7b7a366f1e5eff3b0a2/lib/pure/streams.nim#L1308

**Comment by metagn** [comment]
We can easily fix `readStr` but the fact that calling a nil closure crashes the VM is bad too

Edit: Split into #24057
