### ISSUE TITLE
Bad int32-uint32 conversion RangeDefect on OSX/BSD

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#24076]
### Description

This is reduced from a less trivial program

```Nim
import std/posix
proc uid(x: uint32): Uid = Uid(x)
var y: uint32
let myUid = geteuid()
echo myUid == uid(y)
```

### Nim Version

FreeBSD11/OSX 2019/x86_64; Nim Versions 1.6.12 and Nim-devel.

I could  not get this to fail on Linux/gcc/clang (even defining `Uid=int32` and re-doing the `geteuid` `importc`).

It's theoretically possible this is just "an old, unsupported OSX/FreeBSD version", but that's not a strong theory since the Uid type changed like maybe once ever.  And Nim versions from 1.6 & 2.2rcWhatever both fail.  It could be an x86_64-only thing, though.

It would be good for someone to reproduce this, though I could also try to update my virtual machines.

### Current Output

```text
nim r test
CC: test.nim
Hint: cache/nim/d/test/test_78D49F08F7399BBAA23E3ABB9857B12DC8142E29 [Exec]
/var/tmp/lc/test.nim(5) test
/var/tmp/lc/test.nim(2) uid
/var/tmp/Nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: value out of range: 0 notin 2147483648 .. 2147483647 [RangeDefect]
Error: execution of an external program failed: 'cache/nim/d/test/test_78D49F08F7399BBAA23E3ABB9857B12DC8142E29'
```

### Expected Output

There are at least 2 problems here which might have the same underlying cause:

  - First, `0` fits in any integer and so `uid(y)` should not fail.

  - Second, the exception message range is A+1 .. A.  This just has bad optics since compiler integer range checking logic raises when the range itself seems impossible to satisfy.  Since `range[T]` is a type, impossible ranges should be blockable statically.

### Additional Information

In the top-level of the Nim repo, `grep -r 'Uid\*' lib/posix` shows the type definitions:

```
lib/posix/posix_haiku.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = uint32
lib/posix/posix_macos_amd64.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = int32
lib/posix/posix_nintendoswitch.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = cuint
lib/posix/posix_openbsd_amd64.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = int32
lib/posix/posix_other.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = int
lib/posix/posix_linux_amd64.nim:  Uid* {.importc: "uid_t", header: "<sys/types.h>".} = cuint
```
but as mentioned, I didn't really succeed in trying to synthesize something smaller than with the `import posix` for a more "portable failure".

**Comment by metagn** [comment]
`Uid` seems to be a `uint32` on [FreeBSD](https://forums.freebsd.org/threads/feasibility-of-using-uid-65535.83361/#post-547209) and on [OSX](https://opensource.apple.com/source/xnu/xnu-1228.0.2/bsd/sys/_types.h.auto.html) (ctrl+f `__darwin_uid_t`) but Nim thinks it's `int32` which causes an implicit cast in codegen from `low(int32)` to `uint32` which causes the range start of `2147483648`

Other types like `Gid` etc are also implementation defined, we can look at their values for OSX in that header but I'm not sure where to get the information for FreeBSD

Edit: OpenBSD types.h [here](https://github.com/openbsd/src/blob/master/sys/sys/_types.h)

**Comment by c-blake** [comment]
This kind of cross-OS platform portability stuff is always a morass and we don't have them in the CI.  So, in that respect I think the `A+1 .. A` error message is in some sense the worst part (though I appreciate the explanation!).

While OSX started with FreeBSD on top of a Mach microkernel at some point, I believe they have evolved separately for a long time.  Someone may have fiddled with unsigned/signed.  OSX today is definitely more important here and you might want to check these things are the same on the new Apple Silicon as they were on the x86_64 port.  My bug report came from an OSX user.

That said, https://cgit.freebsd.org/src/tree/sys/sys/_types.h says that on FreeBSD `pid_t`, `gid_t`, and `uid_t` are all `int64`.  We do have `defined(freebsd)` as a separate branch, but we probably also don't promise to support it (or most of the OS branches).  So, kind of up to nim-core how much effort to put into things.  [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_BSD_operating_systems#Popularity) has a 2005 chart showing FreeBSD being 2X more popular than OpenBSD, but there's since been 20 years of evolution in userbases. :man_shrugging: .

**Comment by metagn** [comment]
> That said, https://cgit.freebsd.org/src/tree/sys/sys/_types.h says that on FreeBSD pid_t, gid_t, and uid_t are all int64. 

Am I reading this wrong?

```c
typedef	__uint32_t	__gid_t;
...
typedef	__int32_t	__pid_t;	/* process [group] */
...
typedef	__uint32_t	__uid_t;
```

**Comment by c-blake** [comment]
Process groups are a Unix signal thing akin to a pid.  I was looking at the line defining ` __id_t`:
```C
typedef	__int64_t	__id_t;		/* can hold a gid_t, pid_t, or uid_t */
```
But I agree, even within that one file it seems a bit inconsistent since my line also says pid_t.  Now you have me thinking `types.h` and `_types.h` might not even tell the whole story. Or at least the comments may be wrong.  :man_facepalming:  I would go by the non-comment text of https://cgit.freebsd.org/src/tree/sys/sys/types.h and the `_types.h` personally.

**Comment by metagn** [comment]
@c-blake Could you still test manually if the issue was fixed?

**Comment by c-blake** [comment]
The new devel HEAD works for me on FreeBSD11 - for `Uid`, anyway.  I did not test all of the other dozens or so typedef's or any other OSes.

**Comment by metagn** [comment]
That's fine, I just wanted to make sure this issue was still fine since the CI doesn't test BSD and you probably have more complex code.

**Comment by c-blake** [comment]
I just checked a few more types and `Dev` and `Nlink` still seem broken on FreeBSD11, but `Blksize`, `Uid`, `Gid`, `Mode`, `Ino`, `Off`, `Blkcnt` all do seem to work (these are just `Stat` field types, btw).  Haven't tried to track them down in the C headers/Nim, but thought I should mention it.  Didn't test OSX for those, but I noticed you added new test code in that PR.

**Comment by metagn** [comment]
Checking the remaining inconsistencies in Stat:

`Nlink` is `uint32` on OpenBSD, `uint16` on OSX and FreeBSD, defined as `int16` for both in Nim.

`Dev` is `int32` for both and defined as `int32` in Nim. Edit: Actually `uint32` on FreeBSD.

`Ino` is uint64 on OpenBSD, uint32 on FreeBSD, seems to be uint64 for 64-bit OSX and uint32 otherwise. Defined as int in Nim. Maybe fine as is?

`Blkcnt` is also int64 on all but defined as int.

**Comment by c-blake** [comment]
Also, I perhaps should have said that the same small test program as at the top of this issue with s/Uid/Dev/ and 1.Dev (instead of `geteuid()`) and similar for Nlink fails (with a novel `0 not in 32768..32767` for `Nlink`).  But it works for `Ino` & `Blkcnt`.  No idea about OSX, but we also have the CI for that.
