### ISSUE TITLE
string literal copy error after making it empty

### ISSUE THREAD

**Issue by levovix0** [nim-lang/Nim#24080]
### Description

```nim
var a = (s: "a")
var b = "a"
a.s.setLen 0
b = a.s
assert b == ""
```

### Nim Version

Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release

### Current Output

```text
assertion error
```

### Expected Output

```text
nothing
```

**Comment by metagn** [comment]
Works if adding `prepareMutation(b)` before `b = a.s`, maybe the compiler is forgetting to do this
