### ISSUE TITLE
"Could not load" dynamic library at runtime because of hidden dependency

### ISSUE THREAD

**Issue by ziotom78** [nim-lang/Nim#2408]
I'm trying to call some functions defined in the [GNU GSL library](http://www.gnu.org/software/gsl/). Under Lubuntu 14.10 the following program will compile correctly:

``` nim
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        importc : "gsl_sf_bessel_J0" .}

echo besselJ0(1.0)
```

However, at runtime it will fail with the following message:

```
/usr/lib/libgsl.so: undefined symbol: cblas_dasum
could not load: libgsl.so
Error: execution of an external program failed
```

(I uncommented a line in `lib/system/dyncalls.nim` to get the message about `cblas_dasum`.)

The `cblas_dasum` function is defined in `libgslcblas.so`, but this dependency does not seem to be encoded in the `libgsl.so` file:

```
$ ldd /usr/lib/libgsl.so
    linux-vdso.so.1 =>  (0x00007fff9fd0c000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f829a513000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f829a14f000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f829ac61000)
```

If I import `cblas_dasum`, the error remains the same (`undefined symbol: cblas_dasum \ could not load: libgsl.so`):

``` nim
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        importc : "gsl_sf_bessel_J0" .}
proc cblas_dasum(n : cint, 
                 x : ptr cdouble, 
                 incX: int) : cdouble {. cdecl, 
                                         dynlib: "libgslcblas.so", 
                                         importc: "cblas_dasum" .}
echo besselJ0(1.0)
```

Note that `libgslcblas.so` is readily available under the same path as `libgsl.so`:

```
$ locate libgsl.so
/usr/lib/libgsl.so
/usr/lib/libgsl.so.0
/usr/lib/libgsl.so.0.17.0
$ locate libgslcblas.so
/usr/lib/libgslcblas.so
/usr/lib/libgslcblas.so.0
/usr/lib/libgslcblas.so.0.0.0
```

I tried to define `besselJ0` using two `dynlib`, but with no success:

``` nim
# This compiles fine but does not solve the problem
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        dynlib : "libgslcblas.so",
                                        importc : "gsl_sf_bessel_J0" .}
```

So far, the only workaround I found was to statically link GSL.

**Comment by Araq** [comment]
So how is this a Nim bug? That dynamic loading is broken beyond repair on Unix based systems is not news to me.

**Comment by ziotom78** [comment]
Are you implying that the bug tracker is not the right place where I should have posted this? I hope you're not asking me to repost this on the forum! ;-)

**Comment by ziotom78** [comment]
Ok, the previous comment was a joke. Let's be more serious, we do not get anywhere by simply complaining about the brokenness of Posix's dynamic loading routines. I've often heard (on the Nim forum and in the manual) that Nim's preferred way to link to external libraries is through dynamic linking, because this saves the burden of installing `-dev` packages under Unix. So IMHO Nim should provide an easy way to overcome such difficulties.

After some experiments, I think I've found a solution: use the `RTLD_GLOBAL` flag when calling `dlopen` within `nimLoadLibrary` alongside `RTLD_NOW` (https://github.com/Araq/Nim/blob/devel/lib/system/dyncalls.nim#L70). The documentation in the "Linux Programmer's manual" says that when this flag is used, "the symbols defined by this library will be made available for symbol resolution of subsequently loaded libraries", which is exactly what we need here.

I've changed `lib/system/dyncalls.nim` so that it uses this flag as well, and with this modification of the standard library, the following example compiles fine:
`````nim
proc cblas_dasum(n : cint, 
                 x : ptr cdouble, 
                 incX: int) : cdouble {. cdecl, 
                                         dynlib: "libgslcblas.so", 
                                         importc: "cblas_dasum" .}
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        importc : "gsl_sf_bessel_J0" .}

echo besselJ0(1.0)
`````
Would it be acceptable to @Araq if I change `dyncalls.nim` and make a PR? Or do you think it is not advisable to always default to `RTLD_GLOBAL`?

**Comment by Araq** [comment]
Now we're talking. :-) PR is fine but please check the git history, I vaguely remember we had this flag enabled but it caused other problems.

**Comment by ziotom78** [comment]
The only reference to `RTLD_GLOBAL` I found in the bugtracker is in #897, which however refers to the function [loadLib](https://github.com/Araq/Nim/blob/devel/lib/pure/dynlib.nim#L66-L69) from another module (`lib/pure/dynlib.nim`).

I must confess I fear a bit to introduce the `RTLD_GLOBAL` flag unconditionally… If it is not the default neither in Linux's `dlopen` nor in Nim's `loadLib`, I suspect there is some risk in using it everywhere.

In solving bug #897, @micklat added a `global_symbols` flag to the `loadLib` procedure, which is `False` by default. However, my code does not call `nimLoadLibrary` explicitly. To my limited knowledge, the only way I see to pass a `global_symbols`-like flag to  `nimLoadLibrary` is by means of a yet-to-be-implemented pragma to be used alongside (or in place of) `{. dynlib: "xxx" .}`.

**Comment by Araq** [comment]
Hrm, I think you should just use ``dynlibOverride`` and explicit linking commands then.

**Comment by FedeOmoto** [comment]
Dynamic loading the `gslcblas` library won't resolve the undefined symbol.
You need to dynamic link the library (I know two ways of doing that, I'm new to Nim...):

```Nimrod
{.link: "/usr/lib/libgslcblas.so".}
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        importc : "gsl_sf_bessel_J0" .}
echo besselJ0(1.0)
```

or:

```Nimrod
{.passL: "-lgslcblas".}
proc besselJ0(x : cdouble) : cdouble {. cdecl,
                                        dynlib : "libgsl.so",
                                        importc : "gsl_sf_bessel_J0" .}
echo besselJ0(1.0)
```

**Comment by dom96** [comment]
> (I uncommented a line in lib/system/dyncalls.nim to get the message about cblas_dasum.)

Should this line not be left uncommented so that we can all benefit from such nice messages? :)
