### ISSUE TITLE
Library paths passed incorrectly for the MSVC backend

### ISSUE THREAD

**Issue by Migel1** [nim-lang/Nim#24087]
### Description

I am compiling a nim file on Windows using MSVC build tools.

If I use default settings then the compilation passes as expected:
`C:\nimtest\nim-2.0.8\bin\nim.exe c --cc:vcc test.nim`

But if I specify a library path manually then the specified library path is ignored and the compilation ends with an error:
`C:\nimtest\nim-2.0.8\bin\nim.exe c --cc:vcc --clibdir:"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib_new\x64" test.nim`

(I provide only the "Link" part in logs since the previous part is the same.)

### Nim Version

Nim Compiler Version 2.0.8 [Windows: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
Hint:  [Link]
cl : Command line warning D9002 : ignoring unknown option '/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib_new\x64'
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'
Error: execution of an external program failed: 'vccexe.exe  --platform:amd64 /FeC:\nimtest\test.exe  C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sexceptions.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@ssince.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sctypes.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@ssysatomics.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sansi_c.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@smemory.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@ssyslocks.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sthreadtypes.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sdigitsutils.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@smiscdollars.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sassertions.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@siterators.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@scoro_detection.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sdragonbox.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sschubfach.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sformatfloat.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sobjectdollar.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sdollars.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@stypedthreads.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sstacktraces.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sbitops_utils.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@scountbits_impl.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@srepr_v2.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@swidestrs.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@score@slocks.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sexitprocs.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@ssyncio.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem.nim.c.obj C:\Users\Test\nimcache\test_d\@mtest.nim.c.obj  /nologo    /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib_new\x64" '
```

### Expected Output

```text
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
```

### Additional Information

The possible reason is that the "/LIBPATH" option must be passed only after the "/link" option for cl.exe.
If I add the "/link" option manually then this command completes successfully:
`C:\nimtest\nim-2.0.8\bin\vccexe.exe --platform:amd64 /FeC:\nimtest\test.exe  C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sexceptions.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@ssince.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sctypes.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@ssysatomics.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sansi_c.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@smemory.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@ssyslocks.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sthreadtypes.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sdigitsutils.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@smiscdollars.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sassertions.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@siterators.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@scoro_detection.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sdragonbox.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sschubfach.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sformatfloat.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sobjectdollar.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sdollars.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@stypedthreads.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@sstacktraces.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sprivate@sbitops_utils.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@scountbits_impl.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem@srepr_v2.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@swidestrs.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@score@slocks.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@sexitprocs.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@sstd@ssyncio.nim.c.obj C:\Users\Test\nimcache\test_d\@mnim-2.0.8@slib@ssystem.nim.c.obj C:\Users\Test\nimcache\test_d\@mtest.nim.c.obj  /nologo    /link /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib_new\x64"`

**Comment by metagn** [comment]
According to this stackoverflow answer: https://stackoverflow.com/a/35230294 the `/LIBPATH` option has to come ~~before~~ after `/link`.

**Comment by Migel1** [comment]
> According to this stackoverflow answer: https://stackoverflow.com/a/35230294 the `/LIBPATH` option has to come before `/link`.

The answer from your link states that the /LIBPATH option must be placed after the /link one (as I did).

**Comment by metagn** [comment]
My bad, I meant the opposite, I didn't see that you already mentioned it in the post.
