### ISSUE TITLE
GDB. tools/debug/nim-gdb.py bug

### ISSUE THREAD

**Issue by karbiv** [nim-lang/Nim#24109]
### Description

Nim's tools/debug/nim-gdb.py doesn't load in GDB session.
`gdb.SYMBOL_FUNCTIONS_DOMAIN ` doesn't exist in GDB.

SYMBOL_FUNCTION**S**_DOMAIN exists in **Guile** bindings, with plural FUNCTION**S**.
Python's binding is `gdb.SYMBOL_FUNCTION_DOMAIN` (FUNCTION, without s)

### Nim Version

Nim Compiler Version 2.1.99 [Linux: amd64]
GNU gdb (GDB) 15.1

### Known Workarounds

Renaming `gdb.SYMBOL_FUNCTIONS_DOMAIN`  to `gdb.SYMBOL_FUNCTION_DOMAIN` in tools/debug/nim-gdb.py

In lines like these

https://github.com/nim-lang/Nim/blob/6c35a36043ae910a140831d5c97c8abbae23202b/tools/debug/nim-gdb.py#L170-L176

**Comment by hugosenari** [comment]
Note: now it works with gdb-15.2, but fails with gdb-14.2
