### ISSUE TITLE
Regression from 2.0.8/`version-2-0` to `version-2-2`/`devel` with `Error: type mismatch` with templates and generics

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#24125]
### Description

```nim
template v[T, S](c: S): T = T(c)
discard v[int](0)
```

### Nim Version

Builds:
```
Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-09-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.9 [Linux: amd64]
Compiled at 2024-09-16
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 3214174f06930d240b0e35cb35c22014b89d1272
active boot switches: -d:release
```

Doesn't build:
```
Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-17
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 61e04ba0ed4b8c6567f4cfd5c48c2c2439c62371
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-17
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 1fbb67ffe9d3ec71fb1424609831eaca648c96d3
active boot switches: -d:release
```

### Current Output

```text
/tmp/k.nim(2, 15) Error: type mismatch
Expression: v[int](0)
  [1] 0: int literal(0)
```

**Comment by Araq** [comment]
Partial explicit generic instantations are not in the language spec.

**Comment by tersec** [comment]
Ok

**Comment by diegomrsantos** [comment]
```nim
template v[T](c: SomeOrdinal): T = T(c)
discard v[int, char]('A')
```
outputs

`.SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

**Comment by metagn** [comment]
> .SIGSEGV: Illegal storage access. (Attempt to read from nil?)

This happens in error reporting as a mistake from ~~#24077~~ #24010 originally, it's supposed to give this error:

```
Error: type mismatch
Expression: v[int, char]('A')
  [1] 'A': char

Expected one of (first mismatch at [position]):
[2] template v[T](c: SomeOrdinal): T
  generic parameter mismatch, expected SomeOrdinal but got 'char' of type: typedesc[char]
```

`char` doesn't seem to be part of `SomeOrdinal`.

Also the second generic parameter isn't needed in this case.

**Comment by tersec** [comment]
> > .SIGSEGV: Illegal storage access. (Attempt to read from nil?)
> 
> This happens in error reporting as a mistake from #24077, it's supposed to give this error:
> 
> ```
> Error: type mismatch
> Expression: v[int, char]('A')
>   [1] 'A': char
> 
> Expected one of (first mismatch at [position]):
> [2] template v[T](c: SomeOrdinal): T
>   generic parameter mismatch, expected SomeOrdinal but got 'char' of type: typedesc[char]
> ```
> 
> Also the second generic parameter isn't needed in this case.

The compiler shouldn't crash though, regardless

**Comment by diegomrsantos** [comment]
@metagn 

This works fine
```nim
template v[T](c: SomeOrdinal): T = T(c)
discard v[int](1)
```

but 
```nim
template v[T](c: SomeOrdinal): T = T(c)
discard v[int, char](1)
```
causes
```
Error: type mismatch
Expression: v[int, char](1)
  [1] 1: int literal(1)

Expected one of (first mismatch at [position]):
[2] template v[T](c: SomeOrdinal): T
  generic parameter mismatch, expected SomeOrdinal but got 'char' of type: char
```


I think it should be sth like "invalid type parameter char". This error logic could be causing more hidden bugs. What do you think?

**Comment by metagn** [comment]
The extra generic parameter is allowed there because `SomeOrdinal` creates an implicit generic parameter, i.e. the compiler transforms it to:

```nim
template v[T; #[hidden]# cType: SomeOrdinal](c: cType): T = T(c)
```

Some libraries depended on being able to assign to this hidden generic parameter so it was kept allowed, which is why the compiler gives the error "expected SomeOrdinal", because it's trying to overwrite it. Maybe this could be mentioned in the error message, that an *implicit* generic parameter is being assigned.

The reason we can't support only partially giving the generic parameters is because it makes overloading ambiguous with differing generic parameter numbers and can cause instantiation issues for parameters that aren't properly constrained (i.e. `foo[I, T](x: array[I, T])` vs `foo[T](x: seq[T])`, what if you do `foo[string]`?). The compiler could still infer the parameters from the call as it did before but the parameter counts need to match just so overloading works as expected.

**Comment by diegomrsantos** [comment]
Thanks a lot for explaining. What do you think about the following?

```nim
template v[T](c: SomeOrdinal): T =
  echo "v1"
  T(c)

discard v[int, int](1)
```
prints v1

```nim
template v[T](c: SomeOrdinal): T =
  echo "v1"
  T(c)
template v[T, U](c: SomeOrdinal): T =
  echo "v2"
  T(c)

discard v[int, int](1)
```

prints v2

```
nim -v
Nim Compiler Version 2.1.99 [MacOSX: arm64]
Compiled at 2024-09-19
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 755307be61e4ee7b32c8354b2c303d04bdfc3a3e
active boot switches: -d:release
```

The same happens with 2.0.8 and 1.6.20.

**Comment by metagn** [comment]
> What do you think about the following?

It's not good, if you change the order of the templates it prints `v1` instead.
