### ISSUE TITLE
`nim -c` would not link again if a C lib is updated

### ISSUE THREAD

**Issue by foldl** [nim-lang/Nim#24131]
### Description

Let's see we are building `hello.nim` with a C library `my_lib.a`.

```sh
nim c --passL:my_lib.a hello.nim
```

If `my_lib.a` is update, we re-run the above command and the `hello` executable won't be re-built.

### Nim Version

```
Nim Compiler Version 2.0.2 [Windows: i386]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

### Current Output

```text
`hello` executable won't be re-built.
```

### Expected Output

```text
`hello` executable should be updated.
```

### Known Workarounds

N/A

### Additional Information

Maybe it is impractical for `nim` to check & analyze all compiler options?

**Comment by Araq** [comment]
Nim doesn't even know that after `passL` you passed a filename and not some other random linker option. Use the `-f` switch to force a rebuild and use fewer C dependencies so that you don't have to update them all the time.
