### ISSUE TITLE
Calling algorithm reverse causes a SIGSEGV on ORC

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#24141]
### Description

The following code runs on refc, but sigsegv on orc:

```nim
import std/algorithm

func rev(s: var string) =
  s.reverse

proc main =
  var abc = "abc"
  abc.rev
  echo abc

main()
```

### Nim Version

Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-18
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 04ccd2f4f07a169a03db3cc6f9316628c03f214a
active boot switches: -d:release

### Current Output

```text
Traceback (most recent call last)
/home/esteban/AtomProjects/crap/bug.nim(11) bug
/home/esteban/AtomProjects/crap/bug.nim(8) main
/home/esteban/AtomProjects/crap/bug.nim(4) rev
/home/esteban/.choosenim/toolchains/nim-#devel/lib/pure/algorithm.nim(136) reverse
/home/esteban/.choosenim/toolchains/nim-#devel/lib/pure/algorithm.nim(119) reverse
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
Error: execution of an external program failed: '/home/esteban/AtomProjects/crap/bug'
```

**Comment by ringabout** [comment]
!nim c
```nim
import std/algorithm

func rev(s: var string) =
  s.reverse

proc main =
  var abc = "abc"
  abc.rev
  echo abc

main()
```

**Comment by ringabout** [comment]
!nim c --gc:arc
```nim
import std/algorithm

func rev(s: var string) =
  s.reverse

proc main =
  var abc = "abc"
  abc.rev
  echo abc

main()
```

**Comment by metagn** [comment]
`reverse` has a `var openarray[T]` overload which matches as `openarray[char]` for `string`, but this means the compiler doesn't know to insert `prepareMutation`. Maybe for conversions from `string` to `var openarray` it should always invoke `prepareMutation`?

**Comment by Araq** [comment]
I thought the codegen would already do that, so yes, that's what it should do.

**Comment by ringabout** [comment]
>  conversions from string to var openarray it should always invoke prepareMutation

It has already been done, but not `var string` -> `var openArray`

**Comment by Araq** [comment]
If it's `var string` already, why would it need `prepareMutation` when passed to `var openarray`?

**Comment by ringabout** [comment]
`prepareMutation` is not set up for `var string` as the parameter. Only bracket expressions and openarray conversions use `nimPrepareStrMutationV2`

```nim
proc foo(x: var string) =
  discard

var x = "123"
foo(x)
```

**Comment by ringabout** [comment]
> If it's var string already, why would it need prepareMutation when passed to var openarray?

```nim
proc foo(x: var openArray[char]) =
  discard

var x = "123"
foo(x)
```
In this case, x is of type `var string`. The backend skips the nkHiddenAddr for `x` ad generates `nimPrepareStrMutationV2`. But it doesn't handle the case for a skParam with a `var string` type

```nim
proc bar(x: var openArray[char]) =
  discard

proc foo(x: var string) =
  bar(x)

var x = "123"
foo(x)
```

**Comment by ringabout** [comment]
The culprit seems to be that `transf` folds `(addr (deref (param))` which is harmful to `openArrayLoc`
