### ISSUE TITLE
dist/checksums wrong type: preventing build_all.sh

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#24173]
Error
![image](https://github.com/user-attachments/assets/e84cefd3-694f-4ab6-91cc-5691a9764856)

This is due to checksums using uint8 instead of byte as result type for md5 in:

https://github.com/nim-lang/checksums/blob/master/src/checksums/md5.nim#L108-L116
```
template slice(s: cstring, a, b): openArray[uint8] =
  when nimvm:
    toOpenArrayByte($s, a, b)
  else:
    when defined(js):
      # toOpenArrayByte for cstring is not implemented in JS
      toOpenArrayByte($s, a, b)
    else:
      s.toOpenArrayByte(a, b)
```

It seems like the latest compilers are doing stringent typechecking on templates and cannot compile the checksum library, which might be problematic in bisecting workflow.

**Comment by tersec** [comment]
See also https://forum.nim-lang.org/t/12465#76824
