### ISSUE TITLE
nimsuggest: crash when analyzing code with generic closures

### ISSUE THREAD

**Issue by ibb-dinosaur** [nim-lang/Nim#24179]
### Description

Using the `vscode-nim` extension (version 1.2) with the language server (version 1.6), the `nimsuggest` extension crashes when analyzing specific Nim code. The code is valid and compiles without errors.

Minimal reproducible example:
```nim
import sugar

type
    Parser[T] = object
    
proc eatWhile[T](p: Parser[T], predicate: T -> bool): seq[T] =
    return @[]

proc skipWs(p: Parser[char]) =
    discard p.eatWhile((c: char) => c == 'a')
```

### Nim Version

Nim Compiler Version 2.0.8 [Windows: amd64]
Compiled at 2024-07-03

### Current Output

```text
Server failed with lineinfos.nim(318)     raise RecoverableError
Error: unhandled exception: fatal error: command expects a filename [ERecoverableError]
```

**Comment by metagn** [comment]
Guessing this causes the same issue

```nim
import sugar

type Parser[T] = T -> bool
```

**Comment by ibb-dinosaur** [comment]
Ok after looking into it I was actually wrong. It's something about the server being restarted (possibly the vscode extension issue). 
![Screenshot 2024-09-26 230147](https://github.com/user-attachments/assets/8716f93f-5132-469d-a4c8-0f5df3c0d427)

When I click Restart under the single open file, everything's fine. But when I click Restart All nimsuggest the error appears, even on an empty file. Not sure if I should open a new issue for this?

**Comment by metagn** [comment]
I was able to reproduce a crash from the code, it segfaults the compiler, so there is an issue unrelated to the server restarting.
