### ISSUE TITLE
Compiling with TCC backend and ARC/ORC memory management generates large executable

### ISSUE THREAD

**Issue by Apis035** [nim-lang/Nim#24236]
### Description

```nim
echo "hello world"
```

```sh
nim c --cc:tcc --threads:off main.nim
```

### Nim Version

2.2.0

### Current Output

Nim generates 39,169 KB executable file.

### Expected Output

Nim generates a small executable file.
On version 2.0.8, Nim generates a 105 KB executable file.

### Known Workarounds

Use memory management other than ARC/ORC.

### Additional Information

TCC version 0.9.28rc 2024-09-27_mob@3ead10dd (x86_64 Windows)

**Comment by forchid** [comment]
@Apis035 39.169k(tcc) < 105k!

**Comment by Apis035** [comment]
Apologies if it causes confusion, it supposed to be thousand separator, not decimal number.
Changed dot into comma.

**Comment by metagn** [comment]
Weird, what does 2.2.0 even generate differently vs both 2.0.10 (which also gives small output) and refc? It's not the allocator, `-d:useMalloc` has the same problem.

**Comment by Araq** [comment]
I'm keeping it open as it's so interesting but be aware we don't "officially" support TCC for reasons like this.

**Comment by janAkali** [comment]
Nim v2.2.0 generates this struct in `exceptions.nim.c`:

```c
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
```

The `vTable` line is the reason tcc inflates binary size, and it's easy to test:
Requirements: Linux + tcc + jq + sed
```sh
mkdir test; cd test
echo 'echo "hello world"' > hello.nim
nim cc --cc:tcc --threads:off -l:"-ldl -lm" --nimcache:"cache" hello.nim

cd cache
jq -r '.compile[].[1]' hello.json >> compile.sh      # extract compilation and
jq -r '.linkcmd' hello.json >> compile.sh            # linking cmds to script

sh compile.sh                           # compile C code
ls -sh ../hello                         # executable is LARGE > 20 MB
sed -i '/vTable/d' ./*exceptions.nim.c  # remove vTable line from 'exceptions.c'
sh compile.sh                           # recompile
ls -sh ../hello                         # small executable < 100 kb
```
