### ISSUE TITLE
compiler crash on `len` of `varargs[untyped]`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#24258]
### Description

```nim
template encodeList*(args: varargs[untyped]): seq[byte] =
  @[byte args.len]

let x = encodeList([22], 43)
```

### Nim Version

2.0.8

### Current Output

```text
nim c -r "/home/arnetheduck/status/nimbus-eth1/_exper/testit.nim"
.......................................................................................................................assertions.nim(34)       raiseAssert
Error: unhandled exception: renderer.nim(1313, 7) `n.len == 2` 3 [AssertionDefect]
```

**Comment by ringabout** [comment]
You probably need to use `varargsLen`

```nim
template encodeList*(args: varargs[untyped]): seq[byte] =
  @[byte varargsLen(args)]

let x = encodeList([22], 43)
echo x
```

**Comment by arnetheduck** [comment]
> You probably need to use varargsLen

... but why? `len` is a perfectly fine name for this.

**Comment by arnetheduck** [comment]
```nim
template x(v: varargs[int]) =
  echo v.len

x(2, 3, 4)
```
for comparison, this works

**Comment by ringabout** [comment]
> In addition to the untyped meta-type that prevents type checking, there is also varargs[untyped] so that not even the number of parameters is fixed:

`varargs[int]` type checks the parameters, which means `2, 3, 4` are passed as an array form. It equals to `len([1, 2, 3])`. `varargs[untyped]` passes the parameters as they are. So it is equal to `len(1, 2, 3)` which is not valid.

**Comment by arnetheduck** [comment]
sure, but why a separate name for it? it's conceptually the same thing except for some implementation details.

**Comment by ringabout** [comment]
I don't know. But in https://github.com/nim-lang/Nim/pull/12907

It said that 

>> IMO len should be made to just work on varargs by making this case behave as the following:

> as I mentioned above, it can't, it'd introduce inherent ambiguities due to the way templates work and varargs gets unboxed
