### ISSUE TITLE
Create a PDF version of "Nim Tutorial"

### ISSUE THREAD

**Issue by arisliang** [nim-lang/Nim#24285]
### Summary

Can we create a PDF version for the "Nim Tutorial" on the website https://nim-lang.org/docs/tut1.html?

This makes it easier to read in some scenarios, for example offline.

### Description

Create a PDF version for "Nim Tutorial", to help reading offline. Similar to the "Nim basics" https://narimiran.github.io/nim-basics/, which helps a lot to read.

**Comment by metagn** [comment]
You should be able to generate PDF docs by running `koch pdf` in your Nim installation and having `xelatex` installed. Offline HTML docs are also included in the Nim installation.

PDF docs are not automatically built for the website however.

**Comment by Araq** [comment]
You can also use your browser's "print" feature to produce a PDF.
