### ISSUE TITLE
`{.emit.}` quoting doesn't capture symbols and parameters inside a template

### ISSUE THREAD

**Issue by mrgaturus** [nim-lang/Nim#24282]
### Description

`{.emit.}` quoting doesn't capture symbols and parameters inside a template
```nim
template quoteWontCapture*(data: int, body: untyped) =
  var status: int
  #{.emit: [status, " = ", data, ";"].}
  {.emit: "`status` = `data`;".}
  if status != 0:
    body

proc main() =
  var x = 10
  quoteWontCapture(x):
    echo "hello world ", x

when isMainModule:
  main()

```

### Nim Version

Nim Compiler Version 2.2.0 [Linux: amd64]
Compiled at 2024-10-02
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 78983f1876726a49c69d65629ab433ea1310ece1
active boot switches: -d:release

### Current Output

```text
~/.cache/nim/bug_emit_d/@mbug_emit.nim.c: In function ‘main__bug95emit_u6’:
~/.cache/nim/bug_emit_d/@mbug_emit.nim.c:160:25: error: ‘status’ undeclared (first use in this function)
  160 |         nimln_(5);      status = data;
      |                         ^~~~~~
~/.cache/nim/bug_emit_d/@mbug_emit.nim.c:160:25: note: each undeclared identifier is reported only once for each function it appears in
~/.cache/nim/bug_emit_d/@mbug_emit.nim.c:160:34: error: ‘data’ undeclared (first use in this function)
  160 |         nimln_(5);      status = data;
```

### Expected Output

```text
hello world 10
```

### Known Workarounds

using array capturing instead works as expected:
```nim
{.emit: [status, " = ", data, ";"].}
```

**Comment by beef331** [comment]
Not an issue, template variables are gensym'd by default. Parameters do not exist in expansion.
```nim
template quoteWontCapture*(data: int, body: untyped) =
  var status {.inject.}: int
  #{.emit: [status, " = ", data, ";"].}
  {.emit: "`status` = `x`;".}
  if status != 0:
    body

proc main() =
  var x = 10
  quoteWontCapture(x):
    echo "hello world ", x

when isMainModule:
  main()
  ```

**Comment by mrgaturus** [comment]
i see, quoting is evaluated after template expansion, but i wonder why using an array instead it can capture gemsym'd symbols, that's why i opened this issue:
```nim
{.emit: [status, " = ", data, ";"].}
```
thanks for the clarification.

**Comment by beef331** [comment]
`status` is looked up as a variable outside of quotes. `data` is pasted as `x` so works just fine

**Comment by metagn** [comment]
Does `asm` have a workaround for this?

**Comment by mrgaturus** [comment]
i'm aware `{.emit.}` quoting is the same as `asm` quoting, but if `asm` supports pass an array like `{.emit.}` it think it may be the same workaround

**Comment by mrgaturus** [comment]
> Does `asm` have a workaround for this?

looks like `asm` doesn't support use arrays like `{.emit.}` and only supports use strings so there is not a workaround for `asm`
