### ISSUE TITLE
XmlParser fails on very large XML files without new lines

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#2429]
If you try to parse a XML file, which doesn't contain new lines and which size is roughly equivalent to your system's memory, the program will fail with an out of memory error.

This is caused by the logic in ``lexbase.fillBuffer``, which tries to read a complete line by exponentially increasing an internal buffer, until it no longer fits in memory:
https://github.com/Araq/Nim/blob/devel/lib/pure/lexbase.nim#L102

**Comment by Araq** [comment]
Well yes. did you encounter that in the real world? oO

**Comment by reactormonk** [comment]
@Araq don't go down the path of questioning the uses of XML.

**Comment by dom96** [comment]
This occurring in a real-world scenario is quite likely.

**Comment by kirbyfan64** [comment]
This is actually *very* likely, especially anywhere where Python's elementtree is somehow involved. It writes the whole freaking XML document on a single line. Websites that use Python might use elementtree to write XML for clients to use.
