### ISSUE TITLE
Nim Windows installation file nim-2.2.0_x64.zip marked as virus (malicious)

### ISSUE THREAD

**Issue by bhadra** [nim-lang/Nim#24301]
After I downloaded the nim-2.2.0_x64.zip from [Nim Programming Language website](https://nim-lang.org), Windows Security Microsoft Defender marked the downloaded file as virus.

Downloaded file
https://nim-lang.org/download/nim-2.2.0_x64.zip

Browser used: Microsoft Edge
OS: Windows 11

When nim-2.0.2_x64.zip was uploaded in VirusTotal, 9/56 security vendors flagged this file as malicious. Please refer attached screenshot. This issue must be resolved, since it not worth disabling anti-virus Microsoft Defender even if it is a false positive. However, 9 security vendors flagging it as false positive does not appear so convincing.

<img width="915" alt="2024-10-13_22-30-13" src="https://github.com/user-attachments/assets/da24acb2-1e70-4df7-96dd-d70e4541f6ff">

**Comment by metagn** [comment]
Age old issue, see #17820 #23307

Also a problem for golang, the likely reason is explained here: https://www.reddit.com/r/golang/comments/1729tuc/my_programs_keep_getting_flagged_as_viruses/

Workaround is maybe to use [nightlies](https://github.com/nim-lang/nightlies/) which are automatically scanned for viruses here: https://github.com/nim-lang/virus_checker/

List of false positive submission links: https://github.com/yaronelh/False-Positive-Center

**Comment by c22** [comment]
I've submitted the zip for review to Microsoft
