### ISSUE TITLE
Module alias behavior doesn't match docs

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#24329]
### Description

[The Nim manual states](https://nim-lang.org/docs/manual.html#modules-module-names-in-imports):
> A module alias can be introduced via the as keyword, after which the original module name is inaccessible

But the latest Nim version from the playground accepts this code:
```nim
import std/strutils as su
assert "no".repeat(3) == "nonono"
```
The module is still accessible without the alias.

### Nim Version

v2.2.0 from the playground

**Comment by metagn** [comment]
It says the original module *name* is inaccessible, i.e. you can't use the name `strutils` anymore, but the module is still imported as normal.

```nim
import std/strutils as su
assert strutils.repeat("no", 3) == "nonono" # undeclared identifier: 'strutils'
```

The [from import section](https://nim-lang.org/docs/manual.html#modules-from-import-statement) describes how to selectively import symbols from a module.
