### ISSUE TITLE
Unpacking nested tuples in for loop

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2436]
Should we make it a requirement to include the parenthesis when unpacking tuples in for loops? This will in turn allow for this to work:

``` nim
iterator foo(): tuple[x: tuple[y, z:int], y: tuple[y, z: int]] =
  yield ((1, 2), (3, 4))

for ((a, b), (c, d)) in foo():
  echo a, c
```

And be consistent with tuple unpacking in var/let declarations.

**Comment by def-** [comment]
I consider this uglier than what we have currently, for example for

```nimrod
for (i, x) in @[1, 2,3]: ...
```

**Comment by dom96** [comment]
I don't consider that ugly.

**Comment by reactormonk** [comment]
That will break a LOT of code, time for `2to3`-style? I like the new syntax though.

**Comment by dom96** [comment]
We can allow both I guess.

**Comment by reactormonk** [comment]
And deprecate the old one? Not sure how to implement the deprecation in the parser, but it should be possible. And I currently don't see a problem with syntax ambiguities either.

**Comment by narimiran** [comment]
Superseded by #7486 (more comments and discussion there).

**Comment by nc-x** [comment]
@narimiran 
I think both these issues are different.
  
This issue is asking for nested tuple unpacking. 
But that is not supported anywhere
```
var ((a, b), (c, d)) = ((1,2), (3,4))                 # Parsing error
```
So this is kind of asking for general pattern matching support which as per Araq's opinion should be written as a macro. So this RFC has very less chances of being accepted anyways.

**Comment by narimiran** [comment]
@nc-x So [your solution](https://github.com/nim-lang/Nim/pull/10152) doesn't work for the nested tuples? Can you make it work? :)

**Comment by nc-x** [comment]
No, my patch doesn't support nested tuple unpacking. I didn't add it because the language does not support nested tuple unpacking anywhere. IDK if araq wants them in the language.
@narimiran So your best bet would be to convince @Araq ;)

**Comment by Araq** [comment]
PRs for nested tuple unpacking will be accepted.
