### ISSUE TITLE
`add(var string, openArray[char])` overload

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#24367]
The only overloads for `add` to `string` are for char, string and [cstring](https://nim-lang.org/docs/system.html#add%2Cstring%2Ccstring). An overload that allows adding an `openArray[char]` does not exist, for things like cstrings with a specific length, sections of `seq[char]`, `ptr UncheckedArray[char]` etc. Writing it manually via `for c in openarr: str.add(c)` would be much less efficient than a specialized overload.

Same goes for `insert`.

**Comment by haoyu234** [comment]
proc add*(x: var string, y: openArray[char]) =

is in strbasics.nim
