### ISSUE TITLE
Cannot open '/lib/system.nim'

### ISSUE THREAD

**Issue by lost22git** [nim-lang/Nim#24385]
### Description

I built nim from the source and set bin dir as PATH, but got the error `cannot open /lib/system.nim` when i compiled a helloworld.nim.

### Nim Version

Nim Compiler Version 2.2.1 [Linux: arm64]
Compiled at 2024-10-29
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: d61897459d551b37964b23e82548e2c92c920e02
active boot switches: -d:release

**Comment by narimiran** [comment]
Show us your code.

**Comment by lost22git** [comment]
> Show us your code.

echo "hello"

**Comment by ringabout** [comment]
What's your OS?

**Comment by lost22git** [comment]
> What's your OS?

Android termux debian distro

**Comment by fyrak1s** [comment]
Seems related? #22369

EDIT: Also #23197

A bug in the installer.
