### ISSUE TITLE
Templates bad expansions in arguments

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#24421]
### Description

Templates expand to `rvalue=rvalue` (right-hand side literal values) arguments when the template argument and the function argument have the same name. 

Same happens inside a `main()` function.

Alternative can be change identifier names like `body = bodi` in arguments,
but its weird and don't change the fact that the compiler is using literal values as identifier names in expansions.

```nim
func f(a: string) = discard       # Expands to:
template t(a: string) = f(a = a)  # f("BUG" = "BUG")
t(a = "BUG")                      # Should be:
                                  # f(a = "BUG")
```

### Nim Version

2.2.1

### Current Output

```text
temp.nim(3, 7) Error: identifier expected, but found '"BUG"'
```

### Expected Output

Compile Ok, or give some kind of ambiguous identifier error?

### Known Workarounds

Change the name of the arguments, but you have to edit the whole code.

I found this because I have templates that use `body=body` for HTTP code,
and the `expandMacros` shows code like `f( "BUG" = "BUG" )`, but should be like `f( body = "BUG" )`,
then complains `Error: identifier expected, but found '"BUG"'`.

### Additional Information

See Bisect below...

**Comment by juancarlospaco** [comment]
!nim c

```nim
func f(a: string) = discard
template t(a: string) = f(a = a)
t(a = "BUG")
```

**Comment by beef331** [comment]
This is expected given that any usage of an identifier expands to the parameter.

**Comment by metagn** [comment]
#7811

**Comment by juancarlospaco** [comment]
Even on an identifier name left-hand side? 🤔 
In which scenarios having `f( "value" = "value" )` is a reasonable expansion?
I think should be possible to make the compiler at least produce a warning...

**Comment by beef331** [comment]
Implementing a template that invokes a macro where you actually want `"a" = "b"`.
