### ISSUE TITLE
Forum sign up not possible

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#2446]
Sorry for abusing github to report this issue, but my issue is exactly that I cannot sign up to the forum. None of my email addresses are allowed, due to the apparent restrictions:

 - Addresses can have at most 30 characters (as a hard limit on the input box).
 - University addresses (e.g., `kit.edu`) are not accepted as a valid domain (results in: `Error: Invalid email address`).

**Comment by dom96** [comment]
There is a repo for the NimForum where this should be reported instead [here](http://github.com/nim-lang/nimforum).

**Comment by flaviut** [comment]
Let's reopen this. Half of this bug report is a Nim bug, see https://github.com/Araq/Nim/blob/master/lib/pure/matchers.nim#L20-L45.

IMO, that entire module should be removed from the standard library, it doesn't belong there.
