### ISSUE TITLE
No compilation error when passing proc as arg to another proc taking ptr

### ISSUE THREAD

**Issue by zargot** [nim-lang/Nim#24485]
### Description

Passing a function as an argument to a function taking a pointer, doesn't cause a compilation error. This happens when one forgets to write the function-call parenthesis, as in `getX()`. It's easy to do by mistake, and hard to debug.

Minimal reproducible example:
```nim
proc getX: pointer = nil

proc useX(x: pointer) = discard

useX(getX) # user-error: forgot parenthesis!
```

Edit: It's my understanding that an implicit conversion from function-type to pointer-type is being performed here. I know that functions are pointers, but I'm expecting the type-safety of Nim to help me out. I would expect an explicit `cast` to be required for this code to compile, but I understand that it may be a useful feature to keep it implicit for C interop.

### Nim Version

Nim Compiler Version 2.2.1 [Linux: amd64]
Compiled at 2024-11-28
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 5340005869d513e5c6af06e5d963bcb77abb3fa3
active boot switches: -d:release

OS: Arch Linux

### Current Output

```text
compiles ok
```

### Expected Output

```text
Error: type mismatch
```

### Additional Information

I've also tested v2.0.0 and v1.6.20, which gave the same results.

**Comment by juancarlospaco** [comment]
!nim c

```nim
proc getX: pointer = nil
proc useX(x: pointer) = discard
useX(getX)
```

**Comment by beef331** [comment]
`getX` is a pointer type and all pointer types are implicitly convertible to `pointer`. https://nim-lang.org/docs/manual.html#types-reference-and-pointer-types 

> In general, a ptr T is implicitly convertible to the pointer type.

`proc` is secretly a `ptr T` so seems fine.

**Comment by metagn** [comment]
From [2.0 changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_2_0_0_details.md):

> Enabling `-d:nimPreviewProcConversion` causes `proc` to not support conversion to `pointer` anymore. `cast` may be used instead.

**Comment by zargot** [comment]
> From [2.0 changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_2_0_0_details.md):
> 
> > Enabling `-d:nimPreviewProcConversion` causes `proc` to not support conversion to `pointer` anymore. `cast` may be used instead.

Thank you! I can confirm that it produces the error I was expecting.
