### ISSUE TITLE
incorrect value range inference with abs()

### ISSUE THREAD

**Issue by wiml** [nim-lang/Nim#2448]
It looks like the range inference (see https://github.com/Araq/Nim/blob/57fa8c6d3f535acc79ef8a67a6ef7aef0c7519da/compiler/semfold.nim#L169 ) doesn't handle the case where the argument's range spans 0. The lower bound of the resulting range should be 0 if the argument's range spans 0, otherwise it should be `min(abs(low),abs(high))`.

Example:

```
proc foo(i: range[-4 .. 4]):int =
  abs(i)   # cause compiler to emit error which tells us what it thinks the type is
  return 12
```

The error message indicates that the compiler thinks that abs(i) has type `range 4..4(int)` instead of `range 0..4(int)`.

**Comment by wiml** [comment]
I don't think  4d8750a fixes the bug— consider ranges like `-10..30`, `-30..-10`, or `10..30` all of which still produce incorrect results (`0..10` vs `0..30`, `0..30` vs `10..30`, and `30..10` vs `10..30` respectively). You really do need `min`/`max` or their equivalent here.

**Comment by Araq** [comment]
Very true.

**Comment by Araq** [comment]
The type rules changed, no implicit ranges are produced anymore so this bug doesn't apply anymore.
