### ISSUE TITLE
Deprecate and replace 're' with 'nre'

### ISSUE THREAD

**Issue by BlaXpirit** [nim-lang/Nim#2511]
Nim's regular expression library ([**re**](http://nim-lang.org/re.html)) has many problems.

- Broken behavior
  - [Numerous problems with 0-length matches in 're'](https://github.com/Araq/Nim/issues/2510)
- Not supported:
  - Unicode
    - This not only means that character classes like `\w` are limited (`\w` is just A to Z), but also that bytes of one character can be separated.
  - [Replacing with a function](http://forum.nim-lang.org/t/771#4390)
  - [Splitting with captures](https://docs.python.org/3/library/re.html#re.split)
  - Countless [PCRE flags](https://github.com/flaviut/nre/blob/a665279/src/private/pcre.nim#L124-L172)
- Limited to 20 captures
- Unintuitive API
  - Many functions that do almost the same thing but differently
  - Requires passing a pre-populated `var` argument
  - Two flags are on by default, so if you want to add one more you must specify three flags manually.

Many people report problems chaotically in different places, some do pull requests, sometimes changing from a broken behavior to a wrong behavior, sometimes adding more procedures, making the API more confusing. This has gone on for too long.

There is a new library, [**nre**](https://github.com/flaviut/nre). It solves pretty much all of the problems mentioned above. It is very polished and thoroughly tested for all corner cases. It has a consistent, concise but richer API.

I suggest to include **nre** in the standard library.

Steps towards implementing this:
- [x] Implement [**nre**](https://github.com/flaviut/nre)
- [x] [Change **nre** to use inclusive upper bounds](https://github.com/flaviut/nre/issues/6)
- [x] [Encourage people to use **nre** in **re**'s documentation](https://github.com/Araq/Nim/pull/2560)
- [x] [Remake **nre**'s documentation to use Nim's docgen / reST](https://github.com/flaviut/nre/commit/0dc86145ea4ac2a0fad2b4b3625361ade4ed4970)
- [x] [Update standard library's PCRE wrapper](https://github.com/Araq/Nim/pull/2506)
- [x] [Use standard library's PCRE in **nre**](https://github.com/flaviut/Nim/commit/571c6714895d8d957092265c514242dea4c98346)
    - [ ] *([Merge](https://github.com/Araq/Nim/pull/2818) pending)*
- [x] [Reimplement **re** based on **nre**](https://github.com/BlaXpirit/nim-re-compat/blob/master/re.nim)

After 0.11.2 release:
- [x] [Drop **nre**'s support for locally compiled PCRE](https://github.com/flaviut/Nim/commit/075a5e844069979f1fc3782839e9e2cc62c61ad5)
    - [ ] *([Merge](https://github.com/Araq/Nim/pull/2818) pending)*
- [x] <strike>Move [**optional_t**](https://github.com/flaviut/optional_t) (a dependency) into standard library</strike>  
      &nbsp;[Implement an **options** library in stdlib](https://github.com/Araq/Nim/pull/2762)
- [x] [Change **nre** to use **options**](https://github.com/flaviut/nre/commit/9576bc087d20e8e5cacb9cd92c635d3f9efaf0a7)
- [x] [Move **nre** into standard library](https://github.com/Araq/Nim/pull/2818)
    - [ ] *([Merge](https://github.com/Araq/Nim/pull/2818) pending)*
- [x] [Replace **re** with the wrapper around **nre**, thus getting rid of its bugs and maintenance burden](https://github.com/flaviut/Nim/commit/1b035445e64fafd628dfea112901a9d0a0e0bcd3)
    - [ ] *([Merge](https://github.com/Araq/Nim/pull/2818) pending)*
- [x] [Deprecate **re**](https://github.com/flaviut/Nim/commit/a26c92add2e9a234dc0cb7ab8343bf1b51edf595)
    - [ ] *([Merge](https://github.com/Araq/Nim/pull/2818) pending)*

**Comment by dom96** [comment]
Relevant discussion on IRC from about 6pm onwards: http://irclogs.nim-lang.org/10-04-2015.html

**Comment by Araq** [comment]
Well I need to review these patches and test them still, but apart from that it's all fine with me.

**Comment by flaviut** [comment]
Blocked on #2515.
