### ISSUE TITLE
Bug with user defined type classes?

### ISSUE THREAD

**Issue by hakanderyal** [nim-lang/Nim#2519]
This code fails to compile:

``` nimrod
type

  MyConcept* = concept x
    draw(x)

  Holder = ref HolderObj

  HolderObj = object
    parent: Holder # this is line 9
    otherObj: MyConcept

# concept_test.nim(9, 4) Error: 'HolderObj' is not a concrete type.
```

This one compiles fine:

``` nimrod
type

  MyConcept* = concept x
    draw(x)

  Holder = ref object
    parent: Holder
    otherObj: MyConcept
```

**Comment by Araq** [comment]
Actually the compiler should report it in any case. 'concept' doesn't work this way, it's not an 'interface', it's a generic constraint.

**Comment by hakanderyal** [comment]
Yup, figured that out after fighting with the compiler for the last few days (:

And, shouldn't the complier report this as `MyConcept is not a concrete type` ?

--

On a related note: http://forum.nim-lang.org/t/673#4248

Trying to use type classes this way (interface-like) will trip most people coming from other languages with interfaces.

**Comment by hakanderyal** [comment]
Not sure if it is the same bug:

This fails to compile:

```nimrod
type
  MyConcept = concept x
    someProc(x)
  
  SomeSeq = seq[MyConcept]

var a: SomeSeq
# Error: internal error: getUniqueType
```

**Comment by fowlmouth** [comment]
You cannot instantiate concepts. `seq[MyConcept]` will match for `seq[T]` if there is a `someProc` defined for `T`
```nim
type
  MyConcept = concept x
    someProc(x)
  SomeSeq = seq[MyConcept]

proc someProc(x:int) = echo x

var s = @[1,2,3]
assert s is SomeSeq

var s2 = @[1.0, 2.0]
assert s2 isnot SomeSeq

proc work (s: SomeSeq) =
    for item in s:
        echo item
work s
```

**Comment by hakanderyal** [comment]
Thanks for explanation! I haven't thought about that SomeSeq also becomes a concept.

Might be useful to add that situation to documentation, when the user defined type classes stabilises. As both concrete types and type classes are defined in the type section, this will probably confuse newcomers.

Anyways, it would be better if the compiler gives better error messages. (I know compiler is not stupid-proof yet.)

**Comment by andreaferretti** [comment]
I think there is no bug here (other than better explaining what concepts are). Should this be closed?

**Comment by zah** [comment]
We generally keep issues like this open, because the error messages produced by the compiler can be improved. Has the situation improved in this regard as well?

**Comment by andreaferretti** [comment]
Nope, the error is still the same. It is clear enough for me, but I guess one may want more detailed output.

**Comment by Clyybber** [comment]
> Not sure if it is the same bug:
> 
> This fails to compile with internal error:
> 
> ```nim
> type
>   MyConcept = concept x
>     someProc(x)
> 
>   SomeSeq = seq[MyConcept]
> 
> var a: SomeSeq
> # Error: internal error: getUniqueType
> ```

Now outputs: `Error: invalid type: 'MyConcept' in this context: 'seq[MyConcept]' for var` which is good enough IMO.
