### ISSUE TITLE
Allow defining an executable extension in nim.cfg

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#2521]
On Linux and OSX, executables don't have an extension, which is inconvenient for `.gitignore`. It'd be nice if it was possible to specify an extension in `nim.cfg` files.

Adding a variable like `out="$modulename.bin"` seems appropriate as it provides maximum flexibility.

**Comment by def-** [comment]
Or you assume every file (non-directory) without an extension is a binary. See the first lines of Nim's gitignore: https://github.com/Araq/Nim/blob/devel/.gitignore#L1-L3

**Comment by flaviut** [comment]
@def- [I wrote most that gitignore](https://github.com/Araq/Nim/blame/devel/.gitignore#L1-L3) :stuck_out_tongue: 

The real problem here is that I have some tooling that uses the gitignore but doesn't properly parse it, it might be better to fix it in that tool, but I'm sure other people might want this.

**Comment by disruptek** [comment]
`const ExeExt* {.strdefine.} = ...` ?

**Comment by Araq** [comment]
No work on this has been done and it's not that important, closing.
