### ISSUE TITLE
Negative index obsoletion error complains about valid code.

### ISSUE THREAD

**Issue by MasonMcGill** [nim-lang/Nim#2526]
```nim
var x = ['a', 'b']
x[0 .. 0] = ['c']  # This works.
x[1 .. 0] = []     # This works.
x[0 .. -1] = []    # This doesn't.
```

This is pretty simple to work around, but it might be a reason to remove or tweak the error generation logic at some point.

**Comment by Araq** [comment]
Yes, will be done after 0.10.4 is out.

**Comment by Araq** [comment]
Now they all compile again.
