### ISSUE TITLE
Compiler error: 'yield' cannot be used within 'try' in a non-inlined iterator

### ISSUE THREAD

**Issue by l04m33** [nim-lang/Nim#2528]
The problematic code:

``` nimrod
try:
    var fileContent = await transfer.reader.read(8192)
    while fileContent.len() > 0:
        totalLen += fileContent.len()
        await c.writer.write(fileContent)
        fileContent = await transfer.reader.read(8192)
except:
    debug("transfer failed, message = $#" % [getCurrentExceptionMsg()])
    exc = getCurrentException()
```

When compiled, the compiler shows an error for the line `await c.writer.write(fileContent)`:

```
Error: 'yield' cannot be used within 'try' in a non-inlined iterator
```

I have other `await` lines in `try` blocks, but they compiled with no problem.

Then I changed the code to have only one `await` in the `try` block, and it compiled:

``` nimrod
var fileContent = await transfer.reader.read(8192)
while fileContent.len() > 0:
    totalLen += fileContent.len()

    try:
        await c.writer.write(fileContent)
    except:
        debug("transfer failed, message = $#" % [getCurrentExceptionMsg()])
        exc = getCurrentException()

    fileContent = await transfer.reader.read(8192)
```

**Comment by l04m33** [comment]
I was using **15b5f52** from the **devel** branch.

**Comment by pb-cdunn** [comment]
lib/system.nim(2966, 30) Error: 'yield' cannot be used within 'try' in a non-inlined iterator

* https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L2966

My commit was the tip of `devel`:
```
commit 8a3fd4b12988bad0547f6311c330bf61cc453fd3
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Fri Feb 19 06:06:17 2016
```

**Comment by pb-cdunn** [comment]
To be clear, I now get that error on a fresh build, following `readme.md`. I have tried removing all `*.o` files, to no avail. I am stuck with nim-0.10.0 for now.

**Comment by cdunn2001** [comment]
Oh, I see now. `nim/csources` is a separate repo. I just needed to `git pull` there before running `bin/nim c koch` in the parent repo.

**Comment by edubart** [comment]
Just got this error too, but I was using a simple if, this is a showstopper when working with async and exceptions, makes you pessimize the code to get it working.

**Comment by dom96** [comment]
Use the following pattern as a workaround:

```nim
var fut = asyncCall()
yield fut
if fut.failed: handleError(fut.error)
```

**Comment by dom96** [comment]
A full example would help here :\

**Comment by skunkiferous** [comment]
Hi. I just tried my hand at async code for the first tiem, and got the error.

```
proc readMsg(peer: AsyncSocket) {.async.} =
  assert(false, "TODO")
  discard

proc processPeer(peer: AsyncSocket) {.async.} =
  try:
    # Do some stuff ...
    # What I wanted to do:
    while true:
      await readMsg(peer) # ERROR HERE
    # What I tried instead:
    var again = true
    while again:
      var read = readMsg(peer)
      yield read # ERROR HERE
      if read.failed:
        again = false
  finally:
    # Kill socket ...

```

So, your work-around doesn't work for me. Any suggestion?

**Comment by dom96** [comment]
Handle this case outside this proc, wherever ``processPeer`` is called:

```nim
let processPeerFut = processPeer(peer)
yield processPeerFut
if processPeerFut.failed:
  # Handle error

# kill socket
```

**Comment by yglukhov** [comment]
This should work now.
