### ISSUE TITLE
Error: not all cases are covered - which cases?

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2554]
Instead of a semi-descriptive `Error: not all cases are covered`, the compiler should mention which cases are not covered.

**Comment by Varriount** [comment]
Surely this can't apply to all cases though? For enums this works, but what about integers and other types?

**Comment by Araq** [comment]
Well yes, but the compiler only counts, it doesn't know which cases are missing.

**Comment by GULPF** [comment]
Implemented in #10600
