### ISSUE TITLE
Memory leak with object variants

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2556]
The following code leaks memory:

``` nim
type T =
  ref object
    case variant: bool
    of false: x: ref int
    of true: nil

proc main =
  var z: T
  while true:
    new z
    new z.x
    z.variant = true
main()
```

The underlying issue is that the object branch can be switched if the variant is numerically zero, even if the rest of the object contains data. In this case, reference counting will ignore `z.x` when `z` is freed. Unfortunately, this does not seem to be easy to fix in a fully backwards-compatible fashion.

Variants of this bug can be used to put arbitary/invalid values in other fields. E.g.:

``` nim
type T =
  object
    case variant: bool
    of false: x: int
    of true: y: ref int

proc main =
  var z: T
  var t: int = 99
  z.x = cast[int](addr(t))
  z.variant = true
  echo z.y[]
main()
```

**Comment by Yardanico** [comment]
@Araq doesn't leak for me on devel and second example works properly

**Comment by Araq** [comment]
The language design problems around case objects remain though.

**Comment by zielmicha** [comment]
If I remeber correctly, there was a plan to disallow changing discriminator without `reset` (or maybe automatically calling `reset` when discriminator is changed?).

**Comment by Araq** [comment]
Now finally prevented at runtime.
