### ISSUE TITLE
#! source code prefix collides with Unix Shebang

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#2559]
[shebang]: http://en.wikipedia.org/wiki/Shebang_(Unix)
[filters]: http://nim-lang.org/filters.html

I think it is very bad idea for using `#!` as [parser directive / source fiter][filters] as the `#!` prefix is [Unix Shebang][shebang]. Some text editors (such as TextMate) will treat files starting with `#!` as executable, and try to execute them on **Run** command. So it is very likely users will "execute" some `.nim` with invalid command, leading to some strange errors.

I hereby propose to replace `#!` with `#|` (hash+pipe) and make `#!` obsolete.
Also Lexer should skip shebang if present `#!`, and pickup filter from 2nd line, eg.

```nimrod
#!/usr/bin/env nim c -r
#| stdtmpl(subsChar = '$', metaChar = '#')
#proc generateXML(name, age: string): string =
#  result = ""
<xml>
  <name>$name</name>
  <age>$age</age>
</xml>
```

**Comment by BlaXpirit** [comment]
I, too, think this is a problem and needs to be changed.

`#|` looks kinda weird though.

**Comment by nanoant** [comment]
Okay, do it anything that will be not likely beginning of normal comment, but not `#!`, eg.

* `#:`
* `#=`
* `#|`
* `#$`

Anything but `#!` ;)

**Comment by Araq** [comment]
Actually it works this way since forever:  #! /  (optional whitespace) is a shebang for Nim and then the 2nd line will be consulted for a #! parser directive. So we don't need to do anything.

**Comment by nanoant** [comment]
@Araq Nah, the problem is other way around. It is not problem that Nim will treat `#!/` as filter. Problem is that `.nim` script having filter directive (but no Shebang) will be treated as if it has Shebang by UNIX. The Shebang path doesn't need to start with `/``, `#!` is enough to run anything that follows.

**Comment by Araq** [comment]
How so? The file usually has no exec bit set.

**Comment by nanoant** [comment]
> How so? The file usually has no exec bit set.

Remember the `./bootstrap.sh` thing? On MinGW `#!` implies exec bit, coz FS does not support that. So all nim files having filters will be shown as executable on MinGW. On Linux, FAT systems are mounted this way so all files have exec bit set, so you may try to execute everything, but it won't work unless it is ELF or begins `#!`.

All I am just saying that `#!` for filters can lead to really strange problems. Is `#!` really something that cannot be easily changed in Nim at this stage? Come on, lets change it, when still Nim is not 1.0 and widely adopted. It will be harder to do that later.

**Comment by Araq** [comment]
Ok, let's pick #$ then but please let's have a deprecation path. So 0.12.0 will support both #$ and #! and warn about #! and in version 1.0 we won't support #! anymore.
