### ISSUE TITLE
nimcall should be fastcall

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#256]
nimcall calling convention has changed silently to stdcall, but should be fastcall

**Comment by anilanchal81** [comment]
which software I using for this. I have a package.

**Comment by Varriount** [comment]
Wrong place. Try forum.nim-lang.org

**Comment by anilanchal81** [comment]
so how I will claim my money. github is not use for me. What is the github?

**Comment by Varriount** [comment]
What language do you speak?

**Comment by anilanchal81** [comment]
malayalam
