### ISSUE TITLE
--app:gui gives an error on osx.

### ISSUE THREAD

**Issue by hakanderyal** [nim-lang/Nim#2576]
Latest devel, `echo "hello world"` app, no custom configuration.

``` nimrod
# nim c --app:gui try.nim
# ...
# [Linking]
# clang: error: unknown argument: '-mwindows'
# Error: execution of an external program failed
```

**Comment by dom96** [comment]
What is the equivalent of ``-mwindows`` for clang? Is there one?

**Comment by kirbyfan64** [comment]
@dom96 Nothing, it seems:

http://icculus.org/pipermail/quake3-commits/2014-July/002604.html

**Comment by mjoud** [comment]
I just hit this error on Linux when building a gui app with Nim/gcc. It's pretty clear from the gcc docs that this option is available only for MinGW and Cygwin targets.

**Comment by dom96** [comment]
Looks like you are correct @mjoud. Any ideas how to achieve the same thing on Mac OS X/Linux?

**Comment by mjoud** [comment]
When I think about it, Is `--app:gui` necessary at all on platforms other than win? No console window opens when executing program compiled without `--app:gui` (by double-clicking). I rarely do gui-programming so I haven't given this any thought earlier.

**Comment by Araq** [comment]
On Mac my UI application opens a console window ...

**Comment by mjoud** [comment]
Well, at least it's not necessary on Linux (which should be documented), so we're back at the OS X issue.

**Comment by johnnovak** [comment]
Confirming the issue with nim 0.13.0 on OS X 10.11.3 (El Capitan). Opening the generated executable from Finder opens a console window.

**Comment by dom96** [comment]
I think in order to get rid of a console window you need to put your application in an App Bundle (``myProgram.app`).

**Comment by dom96** [comment]
BTW I don't think this is to do with installation.

**Comment by johnnovak** [comment]
I don't think you need to put the app inside a bundle just to prevent the console window from showing. For example, check out the glfw project—all their example applications compile to single executable files on OS X (no bundle), yet they don't open a console window when launched either from Finder or the command line.

**Comment by couven92** [comment]
@PMunch and I discovered in the wxnim repo that the `--app:gui` also is problematic on Linux. IIRC the same error message popped up on Linux as well (@PMunch correct me if I'm wrong)

So on Linux `--app:gui` should simply be equivalent to `--app:console` (or no `--app` argument at all) as far as the compiler backend is concerned

**Comment by PMunch** [comment]
Yeah, I'm getting this on Linux as well. The reason for this is that Linux doesn't really differentiate between GUI and non-GUI programs as mjoud points out. So at least on Linux this flag should just not do anything.

**Comment by PMunch** [comment]
I've had a bit of a look around for compiling terminal-less GUI programs on OSX. And I'm not entirely sure what glfw does to work around this. I found someone asking about how Python does it and that's basically because it has an interpreter which is an app already. The same applies to apple-script. But for compiled programs I haven't been able to find anything but wrapping it up in a app file or a shell script like this: http://stackoverflow.com/questions/1810497/hide-console-for-tkinter-app-on-osx.

**Comment by andreaferretti** [comment]
With latest devel, this compiles fine on Mac, but opening the generated executable from Finder still opens a console window (what should it actually do, since it just echoes hello world?)
