### ISSUE TITLE
No way to wrap certain C++ templated procedures

### ISSUE THREAD

**Issue by dhasenan** [nim-lang/Nim#2579]
Take the C++ function `template<typename T> int foo(Bar<long, T> value)`. How do you wrap this in Nim? You can access _procedure_ parameters, but not _template_ parameters. The template parameter you need to supply isn't a procedure parameter.

Considering the professed intent of the `'i` element of importcpp specification strings is for templates, it would make more sense for `'i` to refer to the _i_th template parameter rather than procedure parameter.

**Comment by dhasenan** [comment]
Note that you *can* wrap `template<typename T> int foo(Bar<T> value)`. Since the parameter type in this case has only one template parameter itself, you can access that with `'*1`. However, introducing another parameter causes the compiler to emit `foo<long>(variable)`.

This difficulty is caused by a recent change of the semantics of the argument to `{.importcpp.}`, switching from template parameters to procedure parameters. This change seems to be intentional; the documentation at https://github.com/Araq/Nim/blob/devel/doc/nimc.txt#L497 explicitly refers to a way to access the procedure's return value, and templates do not have return values.

**Comment by Araq** [comment]
I don't get the problem, afaict nothing changed. '0 always was the function's return type.

**Comment by dhasenan** [comment]
Okay, someone misreported to me something that Urhonimo was doing, and I didn't verify. This isn't new behavior, it's old behavior, and it doesn't allow you to do some things that should be trivial if the `'i` stuff were more consistent between types and procedures.

`template<typename T> int foo(Bar<long, T> value)` can't be wrapped because `'i` refers to procedure parameter types. You need to extract the second template parameter of the first procedure parameter in order to instantiate the template. `'*1` will give you the first template parameter of the first procedure parameter. There is no way to access the second template parameter of the first procedure parameter.

By using template parameters rather than procedure parameters, it would be much more straightforward to wrap C++ templated functions than it currently is, it would be more consistent with wrapping types, and you could wrap more complex templated functions than is currently possible.

**Comment by dhasenan** [comment]
Also, it's entirely valid and sometimes useful to write a C++ templated function with one or more template arguments that don't appear in the function arguments or return type in any way. The current system doesn't allow that.

**Comment by Araq** [comment]
Well guess what. I didn't dream up this feature to annoy you. The type information that's required for your proposal is not that easily available at this late stage in the compilation pipeline. It's a hack that works well enough for Urhonimo.

**Comment by dhasenan** [comment]
> Well guess what. I didn't dream up this feature to annoy you.

It didn't annoy me. It confused me for a while because I hadn't found the documentation and because of the inconsistency.

You seem annoyed. Would you prefer it if I refrained from submitting any more issues regarding Nim?

**Comment by kirbyfan64** [comment]
@dhasenan I'm subscribed to this project's notifications. Trust me, stuff like this happens. All. The. Time.

**Comment by Araq** [comment]
@dhasenan I'm sorry, keep up the good work and please stay!

**Comment by Araq** [comment]
C++ interop improved a lot, please check it out again.
