### ISSUE TITLE
Integer literals' types not inferred uniformly

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2586]
``` nimrod
import unsigned
var x = 10'u8
echo x < 9 # Works
echo x > 9 # Error: type mismatch
```

It is unexpected that `x < 9` works but `x > 9` doesn't. Of course this happens because `>` is implemented as a template rewriting it to `9 < x`. Because 9 occurs before x now, 9 is automatically an int. Would be nicer if the integer type could be inferred here as well.

**Comment by Araq** [comment]
Not sure this is a bug really.

**Comment by dom96** [comment]
Looks like a bug to me.

**Comment by ozra** [comment]
Perhaps literals should be considered 'weak type guides' (unless explicitly typed). If an expression contains `typeA > weakTypeHint` and the literal fits in the type the expression is 'without it' then it is considered that type.
