### ISSUE TITLE
Maybe the repository should be "nim-lang/Nim", not "Araq/Nim"?

### ISSUE THREAD

**Issue by vi** [nim-lang/Nim#2588]
Usually if there is a Github corporation then the main repository (i.e. the one referenced from nim-lang.org page) also ends up there.

**Comment by dom96** [comment]
What advantages would that bring?

**Comment by vi** [comment]
1. Users browsing "github/nim-lang/" may wonder "where is the Nim repository itself? This way it will be in place;
2. It looks less like somebody's little private project and more like a big thing;
3. It is done this way in other projects;

**Comment by trustable-code** [comment]
+1, make it consistent and easier to find

**Comment by Araq** [comment]
Fine with me as long as github can redirect stuff properly for at least a few months.

**Comment by hakanderyal** [comment]
It makes sense as we approach 1.0 IMHO.

https://help.github.com/articles/transferring-a-repository/

Github does the redirect automatically, but couldn't find any info for duration.

Shouldn't be too troublesome, I guess.

**Comment by tebanep** [comment]
+1 This would be very useful. I for instance didn't understand very well at first if these repositories were related or part of two different projects.

**Comment by ozra** [comment]
I reacted to this too when I discovered Nim. Like, "where the fuck is it?" - it took a while to figure out it was not in the "seemingly offical" github account.

**Comment by reactormonk** [comment]
Finally kicked @Araq to do it.
