### ISSUE TITLE
Methods and modules don't work together

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2590]
4 files needed to make this problem appear:
`types.nim`:
```nimrod
type
  Console* = ref object
    mapper*: Mapper

  Mapper* = ref object of RootObj

  Mapper2* = ref object of Mapper
```
`mapper.nim`:
```nimrod
import types, mapper2

proc newMapper*: Mapper =
  newMapper2()

method step*(m: Mapper) =
  echo "Mapper"
```
`mapper2.nim`:
```nimrod
import types

proc newMapper2*: Mapper2 =
  new result

method step*(m: Mapper2) =
  echo "Mapper2"
```
`main.nim`:
```nimrod
import types, mapper, mapper2

var console = Console()
console.mapper = newMapper()
console.mapper.step()
```
Expected output: `Mapper2` (works when using fewer modules), actual output: `Mapper`

**Comment by Perelandric-Wanderer** [comment]
I encountered this before and wasn't sure what the expected behavior was.

Found that putting a method in the `types.nim` file served as a workaround.

```
method step*(m: Mapper) =                                                       
  echo "NOOP"
```

**Comment by Araq** [comment]
This triggers the same bug: 

```nim
type
  Console* = ref object
    mapper*: Mapper

  Mapper* = ref object of RootObj

  Mapper2* = ref object of Mapper

proc newMapper2*: Mapper2 =
  new result

proc newMapper*: Mapper =
  result = newMapper2()

method step*(m: Mapper2) =
  echo "Mapper2"

method step*(m: Mapper) =
  echo "Mapper"

var console = Console()
console.mapper = newMapper()
console.mapper.step()
```

**Comment by rbehrends** [comment]
I just ran into the same problem: the underlying reason seems to be that the ordering of methods matters. If there is a later method definition for a supertype, it will intercept method dispatch for method definitions for subtypes that were defined earlier. The workaround is to always define supertype methods first (or import them first).
