### ISSUE TITLE
Overloading by argument name with methods

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2595]
You can overload procs by argument name and it works fine:

``` nimrod
proc f(x: ref RootObj) = echo "x"
proc f(y: ref RootObj) = echo "y"

f((ref RootObj)()) # ambiguous
f(y=(ref RootObj)()) # y
```

Whether this is a good idea may be debated, but I'd say it works: you get ambiguity errors at the call site and can choose the proc you want by specifying the argument names.

Now the same with methods:

``` nimrod
method f(x: ref RootObj) = echo "x"
method f(y: ref RootObj) = echo "y"

f((ref RootObj)()) # x
f(y=(ref RootObj)()) # x
```

Here this stops making sense. We don't get any ambiguity error anymore and can't choose which method to call.

I guess argument names should be ignored for methods.

**Comment by Araq** [comment]
I'd argue it still makes some sense: You do select the 2nd 'm', and then at runtime binding resolution picks the first one instead.
