### ISSUE TITLE
Tables module

### ISSUE THREAD

**Issue by vladwing** [nim-lang/Nim#2599]
Compiler: ```nim -v```

```
Nim Compiler Version 0.10.2 (2015-04-10) [Linux: amd64]
Copyright (c) 2006-2014 by Andreas Rumpf

active boot switches: -d:release
```

Code:

```
type
    UUIDObject = ref object
        uuid: string

    Registry [T] = ref object
        objects: Table[string, T]

proc newRegistry[T] (): Registry[T] =
    result = Registry[T]()
    result.objects = initTable[string, T](128)

reg = newRegistry[UUIDObject]()
```

For following two code fragments, which are supposed to be equivalent, the first compiles, the second doesn't:
```
proc register* [T] (self: Registry[T], obj: T) =
    `[]=`(self.objects, obj.uuid, obj)
```

```
proc register* [T] (self: Registry[T], obj: T) =
    self.objects[obj.uuid] = obj
```

The error for the second one is:
```
Error: type mismatch: got (Table[string, UUIDObject], string, UUIDObject)
but expected one of: 
system.[]=(s: var seq[T], x: Slice[int], b: openarray[T])
system.[]=(s: var string, x: Slice[int], b: string)
system.[]=(a: var array[Idx, T], x: Slice[int], b: openarray[T])
system.[]=(a: var array[Idx, T], x: Slice[Idx], b: openarray[T])

```

This seems to me like a function resolution bug that happens in this file ```tables.nim```, line 323. If using  TableRef, instead of Table, both fail compilation. 

Is it possible that ```tables.nim``` module and the compiler are not in sync?

**Comment by Araq** [comment]
No that's an *old* bug that I need to fix some day.

**Comment by vladwing** [comment]
Can you explain why this is happening in this case?

**Comment by ozra** [comment]
Since this is marked high priority, it would be nice with a run-down of what's happening.

**Comment by fowlmouth** [comment]
I believe this is because []= doesn't exist in the module that imported this module (this using module is where register() is instantiated)
Fix with
```
export tables # top level of the module
#or 
bind tables.`[]=` # inside register()
```

**Comment by rogercloud** [comment]
In nim 0.11.2, both registers pass compile. Should mark this issue closed.
