### ISSUE TITLE
Error: (i)..(i) not disjoint from (i)..(i) for a loop that changes i

### ISSUE THREAD

**Issue by lonetech** [nim-lang/Nim#2612]
```
# Need this import for parallel to exist
import threadpool
# Also must compile with nim c --threads:on

# Need a to be some sort of array? type annotation doesn't seem necessary
const a : array[0..5, int] = [1,2,3,4,5,6]

# Need to have f
proc f(n) =
  echo "Hello ", n

# Here's the front page example, somewhat modified
parallel:
  # without the range limitation, all I got is 
  # Error: cannot prove: i <= len(a) + -1; no matter what the while tested
  var i : range[0..4] = 0
  while i < a.high:
    # This line errors out with Error: (i)..(i) not disjoint from (i)..(i)
    spawn f(a[i])
    # This line doesn't need to exist for that error
    #spawn f(a[i+1])
    # ERROR: cannot prove a[i] is disjoint from a[i+1]
    # BUT: replace 'i += 1' with 'i += 2' and the code compiles!
    i += 1
```

**Comment by lonetech** [comment]
Both problems are avoided by wrapping the code in a proc. The error seems to stem from i being global, even though it is not exported. I arrived at this program when trying the "excited" sample on the front page.

**Comment by maximvl** [comment]
I found similar problem with passing int to a spawned function which can't be changed and using it right away:

```
# Need this import for parallel to exist
import threadpool
# Also must compile with nim c --threads:on
var a : array[0..5, int] = [1,2,3,4,5,6]

# Need to have f
proc f(n: int): int =
  return n + 1

# Here's the front page example, somewhat modified
parallel:
  for i in 0..high(a):
    a[i] = spawn f(i)
```

The error is similar:
``` disjoint.nim(13, 7) Error: (i)..(i) not disjoint from (i)..(i) ```

**Comment by peheje** [comment]
Reproduced Version 0.17.2 (2017-09-18) [MacOSX: amd64]. Is the solution to wrap your code in a proc? Should the error say this?
Kind regards.

**Comment by narimiran** [comment]
> Both problems are avoided by wrapping the code in a proc.

Ok, there's a solution/workaround — can we close this?

**Comment by lonetech** [comment]
There's a workaround, but the error message was misleading and the front page example was broken. Were either of those addressed?

**Comment by Araq** [comment]
The front page doesn't contain this example anymore but we can still improve the error message. :-) This thing is under ``.experimental`` though so people are aware there are dragons. So ... closing.
