### ISSUE TITLE
Not all cases covered with unsigned numbers

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2613]
This reports not all cases covered, but they are. With signed ints it works fine (if you remember that they can be negative):

``` nimrod
import unsigned
case 10'u mod 3
of 0..2: echo "hi"
```

Maybe it should also work with `and`, but I'm not sure:

``` nimrod
case 10 and 0b11
of 0..3: echo "hi"
```

**Comment by Araq** [comment]
Well uint and uint64 are not ordinal types, so they get no 'range' types and so it doesn't compile.

**Comment by def-** [comment]
Same with every other unsigned number type except and even int literals (but not int vars):

```nimrod


import unsigned

var x = 3
case x mod 3 # This works
of -2..2: echo "hi"

case 3 mod 3 # Fails
of -2..2: echo "hi"

var z = 3'u8
case z mod 3'u8 # Fails
of 0..2: echo "hi"
```

**Comment by Araq** [comment]
That ``mod``  produces a range subtype was removed from the language. Closing.
