### ISSUE TITLE
Mark all OSErrorCode variables as such

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2631]
e.g. in `posix.nim`, `winlean.nim`/`windows.nim`

**Comment by Araq** [comment]
How to "mark" them?

**Comment by reactormonk** [comment]
They should be of type `OSErrorCode` not `cint`.

**Comment by dom96** [comment]
Give us one example of which ``cint`` you are referring to. Are you talking about POSIX/WIN API proc return values?

**Comment by reactormonk** [comment]
All the constants imported from `<errno.h>`.

**Comment by dom96** [comment]
I think a cross-platform OSErrorCode for each error code defined in posix/winapi should be defined in os.nim instead.

**Comment by Araq** [comment]
``OSErrorCode`` is now a thing.
