### ISSUE TITLE
Kill nim i

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2633]
Since it's not supported anymore, purge it.

**Comment by hakanderyal** [comment]
Agreed, it's one of the first things newcomers try to use, and gets confused with buggy behaviour.

**Comment by Araq** [comment]
I won't kill it, I'll rename it to some secret command instead. I find it handy for calculations and I know how to avoid its bugs and I know some other people do too.

**Comment by reactormonk** [comment]
How about `nim secret`?

**Comment by kirbyfan64** [comment]
Names that come to mind:

```
nim evil
nim hidden
nim magic
nim horror
nim intercal # <-- my personal favorite
nim chaos
nim the_evil_interpreter
nim death
nim nimnimnimnim
nim better-than-pascal
nim crap
```
