### ISSUE TITLE
No way to pre-size an IntSet

### ISSUE THREAD

**Issue by maxgrenderjones** [nim-lang/Nim#2646]
Perhaps I'm doing it wrong, but I'm having a play with the Euler problems and want to create a large `IntSet` to do sieve of Eratosthenes. Since `IntSet` doesn't take an `seq` in its constructor (or an initial size), it seems you need to create one, then add lots of stuff to it, causing lots of memory reallocations.

Would it make sense to add the following proc:
`proc initIntSet*(max: int): IntSet`

Assuming I'm reading it right, and the members don't have to be consecutive, would it also make sense to add a constructor that takes a `seq` i.e.:
`proc initIntSet(seq[int]): IntSet`

Also, would you be averse to adding `+` and `-` methods to include or exclude a given `int`, or is that too overlapping with the methods `incl` and `excl` / meaning of `+` as union between sets rather than add element x?

**Comment by Araq** [comment]
additional initIntSet procs are fine with me, ``+`` and ``-`` are not for the reasons that you give.

**Comment by narimiran** [comment]
> Since IntSet doesn't take an seq in its constructor (or an initial size), it seems you need to create one, then add lots of stuff to it, causing lots of memory reallocations.

I just implemented pre-sizing an IntSet and there is no measurable difference between the old and the new way. (Maybe IntSet back in 2015 (when this issue was created) were implemented differently than it is done currently)

Since there is no point in having that feature, I'm closing this.
