### ISSUE TITLE
Getting the effects of --os:standalone but still remembering which OS you're on

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2654]
In my [blog post](http://hookrace.net/blog/nim-binary-size/) I compile with `--os:standalone` to remove C standard library dependencies. For [nim-syscall](https://github.com/def-/nim-syscall) it would still be nice to know which OS we're on, so you can choose the correct syscalls:

``` nimrod
when defined(linux) and defined(amd64):
  import linux_x86_64/call
  import linux_x86_64/nr
  export call.syscall, nr.Number
elif defined(linux) and defined(i386):
  import linux_x86/call
  import linux_x86/nr
  export call.syscall, nr.Number
else:
  {.error: "No syscalls defined for your platform".}
```

 I don't know what's the best way to achieve this.

**Comment by Yardanico** [comment]
@def- define linux symbol? -d:linux

**Comment by andreaferretti** [comment]
It seems that @Yardanico solution should work fine - is there anything else here to do?

**Comment by ehmry** [comment]
This is an issue for Genode OS target, and I assumed the best solution would be to check both `defined(genode)` and `defined(posix)`, with POSIX not enabled by default for Genode.

**Comment by andreaferretti** [comment]
@ehmry So in order to compile for Genode you need os:standalone? Asking because I am not familiar with genode

**Comment by ehmry** [comment]
@andreaferretti No, I don't use os:standalone, but with Genode it should be possible to use the native libraries without the standard C runtime, but also possible to use the C/POSIX runtime so external libraries would work. I just want to make the point that there are use cases for compile-time switches that select an OS, but disable things like file-descriptor I/O, which is perhaps different from os:standalone.

**Comment by ehmry** [comment]
Basically there is running without a kernel, which I consider as standalone, and running with a kernel, but not using an OS, which I consider `not defined(posix)`. Just my two cents.

**Comment by andreaferretti** [comment]
So if I understand correctly, you want the opposite of what is asked here (os standalone, but posix syscalls defined)

**Comment by ehmry** [comment]
Disregard.

**Comment by andreaferretti** [comment]
Closing, as per @Yardanico solution, feel free to reopen if I missed something
