### ISSUE TITLE
Memory corruption (probably due to GC or C compiler bug)

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2668]
When compiling my [ntags program](https://bitbucket.org/behrends/ntags) with Nim and either the reference counting or the mark-and-sweep garbage collector and gcc 4.9 or 5.1 with `--opt:size`, I can fairly reliably observe memory corruption (the memory corruption can also occur with `--opt:speed`, but not as reliably). It does not happen with clang at all, and seems to disappear when optimization is turned off. Using the Boehm GC also makes it disappear.

This can happen on individual files, but is most easily observed on larger directories (e.g. running `ntags -R` on the entire stdlib).

This seems to happen both on OS X and Linux (though more reliably on OS X). I've been primarily using Nim 0.11.2, but the behavior can also be observed with 0.10.2.

The program uses only standard library functions, and no unsafe functionality, such as `addr` or `{.importc.}`. The program does use `add` both for strings and sequences of strings extensively. It frequently crashes inside `add(x: var seq[string], y: seq[string])`, but apparently can also fail if this code isn't used at all.

Using `-d:useSysAssert` and `-d:useGcAssert` does not reveal any further information. The program sometimes fails a sysAssert with `growObj: 1`, but only because the underlying memory is already corrupted.

With the reference counting GC, I could observe that crashes regularly happened after a `collectZCT` call, which seemed to indicate that the garbage collector may erroneously recycle memory still in use. Tracking the behavior of `interiorAllocatedPtr()`, I noticed that for the crashes, it always returned `nil` (and I mean always), which may indicate that gcc interprets something that the code does as undefined behavior and optimizes it away (without optimization, `interiorAllocatedPtr()` will return non-nil values sometimes).

**Comment by rbehrends** [comment]
Update: After noticing that the `isAccessible()` test in `interiorAllocatedPtr()` always failed because the page index was never found in `a.chunkStarts`, it turned out that disabling `TIntSet.excl` prevents the crashes. This would seem to indicate that page indices are erroneously removed from `chunkStarts`, though it isn't clear why this only happens when gcc with optimizations turned on is being used.

**Comment by rbehrends** [comment]
Part of the problem (i.e. what causes crashes because of `--opt:size`) is that stack scanning can start at addresses that are not a multiple of 8. This can be fairly easily fixed by re-aligning the stack pointer in `forEachStackSlot` to a multiple of 8, though this doesn't fix the issue that there may be misaligned C structs on the stack (e.g. due to `__attribute__((packed))`).

Unfortunately, while this fix eliminates a category of crashes, the code still occasionally crashes for other reasons (this is observable with either `--opt:speed` and `--opt:size`, and `--opt:speed` doesn't cause the stack pointer to be misaligned)

**Comment by rbehrends** [comment]
The underlying problem seems to be the storage of registers within the `jmp_buf` type by `setjmp()` calls. Not only is `jmp_buf` not machine-word aligned on some architectures (it's frequently abstracteded as an `int jmp_buf[N]` type, meaning that it is sometimes stored starting not at a machine word boundary, registers may be stored within at half-world offsets also. Stepping through the register area in halfword steps and making sure all other addresses are aligned to full word boundaries seems to fix the crashes for `x86_64` architectures.

**Comment by Araq** [comment]
Please re-open if still an issue.
