### ISSUE TITLE
`repr` can get confused by `cint`

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#2685]
I noticed that `repr` can have a rather misleading output:

    type
      SomeEnum {.size: sizeof(cint).} = enum a, b # must be cint to reproduce

      StructLike* = object 
        e* : SomeEnum
        f* : cint # must be cint to reproduce

    var x: StructLike 

    x.e = b
    echo "Enum: ", x.e
    echo "Repr: ", repr(x)

    x.f = 42
    echo "Enum: ", x.e
    echo "Repr: ", repr(x)

Produces (with line breaks removed):

    Enum: b
    Repr: [e = b, f = 0]

    Enum: b
    Repr: [e = 180388626433 (invalid data!), f = 42]

Which would suggests that the assignment to `x.f` has corrupted `x.e`, although everything seems to be fine. When removing the `size` pragma or using `int` instead of `cint`, the output of `repr` is okay.

**Comment by dom96** [comment]
Seems to be working fine now. Please reopen if I'm wrong.
