### ISSUE TITLE
gc:boehm  leads to wrong calculation result

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2688]
I extracted this from the bigints library: https://gist.github.com/def-/9279a1583805c69f8f67

Every GC correctly prints:
```
@[1]10
@[10]1000000000
@[1410065408, 2]1000000000
@[2313682944, 2328306436]1000000000
@[4016047006, 3553707656, 174246625]
```

Only Boehm prints the wrong result:
```
@[1]10
@[10]1000000000
@[1410065408, 2]1000000000
@[0]1000000000
@[1604846494, 546150553]
```
I couldn't reduce it further as the problem then magically disappeared.

**Comment by rbehrends** [comment]
This seems to be an aliasing problem in `*=`. You can avoid it by using `var c = a` instead of `let c = a`. The difference is probably due to different reallocation behavior as a result of `setLen()`.

**Comment by Araq** [comment]
The let vs var gotcha has been reported already, so I'm closing this one.
