### ISSUE TITLE
lib httpclient / net not GC-Safe

### ISSUE THREAD

**Issue by Senketsu** [nim-lang/Nim#2692]
I would expect pure lib to be GC-Safe for the sake of threading. 
Much more such as httpclient/net where without threading would cause massive freezes in gui applications.

![2015-05-11-02_05_33_ss](https://cloud.githubusercontent.com/assets/6295813/7556852/a0a37fb8-f782-11e4-8a79-020fd6746959.png)

Arch Linux , Nim version 0.11.2 - devel

**Comment by reactormonk** [comment]
Could your replace the image with text so it's easier to search?

**Comment by Senketsu** [comment]
```
lib/pure/net.nim(506, 6) Warning: 'connect' is not GC-safe as it calls 'isIpAddress'
lib/pure/httpclient.nim(383, 6) Warning: 'request' is not GC-safe as it calls 'connect'
lib/pure/httpclient.nim(438, 6) Warning: 'request' is not GC-safe as it calls 'request'
nibolo.nim(645, 6) Warning: 'updateCheck' is not GC-safe as it calls 'request'
nibolo.nim(677, 6) Error: 'updateThread' is not GC-safe as it calls 'updateCheck'
```
Sorry about that.
I suppose it goes deeper than that and compiler goes only that deep with warrnings.
[net.nim](https://github.com/Araq/Nim/blob/master/lib/pure/net.nim#L1264)

**Comment by Senketsu** [comment]
**[This post is just of informative character and not a proposal for a solution]**
I've come by this again, and i found a solution (at least good enough for me) that you might not like.
Fixes GC-safety issue with httpclient & net module that i've experience in the post above.
* For the httpclient module, its the defaultSSLContext that breaks GC-Safety (pretty obvious right ?)
Fix:
```
when not defined(ssl):
  type SSLContext = ref object
  let defaultSSLContext: SSLContext = nil
else:
  let defaultSSLContext = newContext(verifyMode = CVerifyNone)
```
to
```
when not defined(ssl):
  type SSLContext = ref object
```
and fixing the procedures definitions to not init sslContext argument. e.g:
```
proc request*(url: string, httpMethod: string, extraHeaders = "",
              body = "", sslContext = defaultSSLContext, timeout = -1,
              userAgent = defUserAgent, proxy: Proxy = nil): Response =
```
to
```
proc request*(url: string, httpMethod: string, extraHeaders = "",
              body = "", sslContext: SSLContext, timeout = -1,
              userAgent = defUserAgent, proxy: Proxy = nil): Response =
```
* For the net module, its a placement of certain two procedure declarations (only gives above error with a -d:ssl)
```
proc isIpAddress*(address_str: string): bool {.tags: [].}
proc parseIpAddress*(address_str: string): IpAddress
```
Just moving the block (along with the rest of ip* procs) with their definition to the place of their declaration fixes this issue.

**Just wanted to let you know if you anyone ever come across this issue again.**
*Not gonna make pull request as its .. not really fix, since it would break lot of old code depending on `defaultSSLContext`.*

Cheers

**Comment by dom96** [comment]
I think this is fixed now. Please reopen if it's not.
