### ISSUE TITLE
"Strict" modes, requiring mut/ref at call site for arg-mutating proc's.

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2711]
For a language to be really good imo, it should be possible to prototype and write algos quickly to test them out. It should then be straight forward to harden the code when needed.

Allowing different demands on different blocks of code is one way.

In 'hardened' code, I'd like to be able to demand that 'ref' or similar is passed with arguments to arg-mutating procedures at call site - if not: it's an error. This way argument mutating procedures are clearly visible in using code, making it much easier to follow the code without diving into every function (3rd part libs or whatnot). It should be obvious what states are changed in a context from seeing the source of the context only.

At the same time, demanding this at all times makes prototyping, code-whipping, cumbersome.
Therefore I think different strictness/demands blocks should be available.

**Comment by reactormonk** [comment]
i.e. automatic dereferencing should not produce a `var` type, require a `var ref` type instead. Sounds reasonable as a standard for me.

**Comment by Araq** [comment]
Sounds unworkable to me. So we then have a strict mode with **lots of** 'ref' annotations everywhere? I cannot imagine this being helpful for any realistic Nim program.

**Comment by ozra** [comment]
Why does it sound unworkable? The point is that you specify it for a module or function where you really want the code tightly examined, you wouldn't normally use that mode (or flag) for an entire program.
I also don't know any other language that does it - which just make them very lacking in that department, and not role models. Why was Nim created? To "be like the others"?

To be able to demand from the compiler, and code, that all mutations to state is visible from just reading the code sounds very desirable to me, especially when it's optional.

**Comment by Araq** [comment]
This thing is better left to the editor/IDE which can then show the offending expressions in red. This way you get the feature for every module, strict-mode on or off and it doesn't produce a dialect of the language. Can the editor do it easily? No, but that's why we have nimsuggest. So I rather have more nimsuggest functionality than language dialects.

**Comment by ozra** [comment]
That sounds equally good to me. I'll see if it's available for atom.

I'm really interested in nim. I'm having the luxury of getting to re-implement a system from the ground up, that is currently spread over three languages (primarily C++11), and having used C++ for more than 16 years - at this opportunity I'd really like (hopefully) to find an alternative when I'm granted such a luxurious task. The keyword in the project is performance. And that doesn't mean one shouldn't be able to have a good lang..
