### ISSUE TITLE
Generic nested table fails to compile

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2722]
```nimrod
import tables

type
  TwoKeyTable[T] = Table[string, Table[string, T]]

proc initTwoKeyTable(): TwoKeyTable[int] =
  result = initTable[string, Table[string, int]]()

var tkTable = initTwoKeyTable()
var x = tkTable["a"]
```
This fails with:
```
x.nim(10, 16) Info: template/generic instantiation from here
lib/pure/collections/tables.nim(191, 40) Error: type mismatch: got (int) but expected 'Table[system.string, system.int]'
```
Meanwhile the same code works when specifying `int` values instead of `T`:
```nimrod
import tables

type
  TwoKeyTable = Table[string, Table[string, int]]

proc initTwoKeyTable(): TwoKeyTable =
  result = initTable[string, Table[string, int]]()

var tkTable = initTwoKeyTable()
var x = tkTable["a"]
```
Extracted from https://stackoverflow.com/questions/30246999/nim-two-key-table-with-generics

**Comment by peter-the-tea-drinker** [comment]
I found another test case (I think it's related):

    type
      MyTuple[T] = tuple
        table1: Table[T,int]
        table2: Table[T,float]

    proc test[T](o:MyTuple[T],k:T)=
      echo o.table1[k]
      echo o.table2[k]

    var o:MyTuple[string]
    o.table1 = initTable[string,int]()
    o.table2 = initTable[string,float]()

    test(o,"hello")

Fails with:

`Error: type mismatch: got (int) but expected 'float'`

**Comment by Araq** [comment]
These all work with Nim devel now.
