### ISSUE TITLE
[Windows] MinGW within Nim install is missing libraries

### ISSUE THREAD

**Issue by Senketsu** [nim-lang/Nim#2723]
``` [Linking]
C:/Nim/dist/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgdi32
C:/Nim/dist/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcomdlg32
Error: execution of an external program failed
```

Just want to let you know that trying to compile with _--app:gui_ param results to this.
Seems like currently the compiler comes with mingw thats missing libs
(Its minor stuff and i feel like whiner )

Windows 7 , nim-0.11.2_x64.exe

**Comment by Varriount** [comment]
This is an unfortunate consequence of stripping the base mingw installation of 'unnecessary' files. The fix (at least for the future) is to modify tools\trimcc.nim to test if a gui application still works. I don't know what should be done for the current installer - perhaps, given the existence of #2765, a new installer set should be published?

**Comment by Araq** [comment]
@Varriount I'm still waiting for a new set of base mingw zips from you. As you know we can update these under the hood since the installer downloads it on the fly from the website.

**Comment by dom96** [comment]
@Varriount ping? http://forum.nim-lang.org/t/953

**Comment by dom96** [comment]
@Varriount Any progress on this?

**Comment by Varriount** [comment]
Planning on fixing it this weekend.

**Comment by dom96** [comment]
Make sure to ask @Araq if he fixed it already.

**Comment by Araq** [comment]
I didn't.

**Comment by trustable-code** [comment]
This issue affects me too. Workaround: Use MinGW from https://sourceforge.net/projects/mingw-w64/
