### ISSUE TITLE
High-performance BigInt support using GMP

### ISSUE THREAD

**Issue by jagtesh** [nim-lang/Nim#2725]
Many languages have built-in support for BigInts using GMP (https://gmplib.org): there's Ruby, Crystal and Julia, to name a few. I tried @def-'s nim-bigints library which doesn't use GMP. It seemed to perform significantly slower than GMP based implementations in other languages. I feel that having native support for BigInts will encourage people to use a standard high-performance implementation in their code, which will be great for code-reuse in scientific applications.

**Comment by dom96** [comment]
I agree. I think that a GMP-based BigInt module is something that is missing in the standard library. Perhaps it would be a good idea to adopt @def-'s BigInt module's API then create an implementation for GMP. The user could then choose between a slower (but native) implementation and GMP.

**Comment by def-** [comment]
I asked Araq and he said he wanted BigInts without GMP so we can use them at compiletime / in the VM. Of course nim-bigints will never have that great performance, but it could be improved.

See also:
- https://github.com/jovial/nim-gmp
- https://gist.github.com/rbehrends/91d2b2dee8ebcac08e97

**Comment by jagtesh** [comment]
Fair enough, as long as we're clear. Perhaps we should document this decision and share the links on the wiki (thanks, btw).

**Comment by def-** [comment]
I think this common API between native and gmp bigints should be more fleshed out, maybe in nim-bigints. I don't know if I'll have time for that soon.

**Comment by Araq** [comment]
Well it's available as Nimble packages. Good enough for now.
