### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#2730]
The following will make the compiler crash (that is, no error is produced, nor any output file):

    type
      Foo[a: static[int]] = array[a, int]
      Bar[a, b: static[int]] = array[b, Foo[a div 2]]

    echo "done"

As far as I can tell, the same happens whenever one tries to use arithmetic on `static[int]`, viewed as a type

**Comment by andreaferretti** [comment]
After some more experiments, it turns out that arithmetic on static types is sometimes valid. The original example makes the compiler crash. The following produces an error (but no crash)

    type Vect[N: static[int], A] = array[N, A]

    proc push[N: static[int], A](a: Vect[N, A], x: A): Vect[N + 1, A] =
      for n in 0 .. < N:
        result[n] = a[n]
      result[N] = x

The following is valid

    type
      Foo[a: static[int]] = array[a, int]
      Bar[a, b: static[int]] = array[b div 2, Foo[a]]

as well as this one

    type Vect[N: static[int], A] = array[N, A]
    proc plusOne(n: int): int = n + 1

    proc push[N: static[int], A](a: Vect[N, A], x: A): Vect[plusOne(N), A] =
      for n in 0 .. < N:
        result[n] = a[n]
      result[N] = x

**Comment by gmfawcett** [comment]
As mentioned on the forum, this seems to be an error-reporting bug, not a codegen bug. Changing line 1600 in `vmgen.nim`, and replacing `internalError(n.info, "cannot generate code for: " & s.name.s)` with `globalError(...)`, produces a reasonable compilation error message for the initial test code:

    Error: cannot instantiate Foo
    got: (float)
    but expected: (a)
        Bar[a, b: static[int]] = array[b, Foo[a/2]]

**Comment by andreaferretti** [comment]
With an updated version of the compiler, the error  reporting seems to work. Unfortunately, the previous workarounds do not work anymore

**Comment by Araq** [comment]
> Unfortunately, the previous workarounds do not work anymore

Well you need to give me your previous workarounds as test cases then. We already have lots of tests for the static_t mess, but it's never good enough to prevent regressions, apparently.

**Comment by andreaferretti** [comment]
Sorry, my fault. I was refering to the examples posted in my second post above that I claimed were working. I tried them yesterday, and I must have got something wrong, because I was under the impression they did not work anymore, but they do. Sorry for the confusion

The following (apparently similar) example, though, fails to compile

```nim
type Vect[N: static[int], A] = array[N, A]

proc plusTwo(x: int): int = x + 2

type
  Foo[a: static[int]] = Vect[a, int]
  Bar[a, b: static[int]] = Vect[a, Foo[plusTwo(b)]]
```
