### ISSUE TITLE
The '&' character in the Operators and Strings sections of the Tutorial Part I is not displayed correctly

### ISSUE THREAD

**Issue by fjanon** [nim-lang/Nim#2743]
![nim 2015-05-16 1](https://cloud.githubusercontent.com/assets/43575/7668064/deaabbea-fc24-11e4-9cbc-51b5d53b21fa.jpg)
![nim 2015-05-16 2](https://cloud.githubusercontent.com/assets/43575/7668065/deaefe44-fc24-11e4-8a2e-94b33108ab33.jpg)

With Chrome 42 on win7, on page

http://nim-lang.org/docs/tut1.html

section 'Operators', it seems that the font Source Code Pro messes up the '&' character in:

Apart from a few built-in keyword operators such as and, or, not, operators always consist of these characters: + - * \ / < > = @ $ ~ & % ! ? ^ . |

Also in Strings

The assignment operator for strings copies the string. You can use the & operator to concatenate strings and add to append to a string.

When switching to font 'monospace', everything is displayed correctly.

**Comment by kirbyfan64** [comment]
Looks fine to me...

Screenshot?

**Comment by Araq** [comment]
Looks good to me.
