### ISSUE TITLE
{.compile.} pragma with other languages

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2748]
I'd like to compile and link files in C and Objective C, while compiling the Nim project in C++. It seems like the current `{.compile.}` pragma doesn't support this and always calls the C++ compiler for these files. Should file endings determine the compiler to be used or would an option for the compile pragma be better?

**Comment by dom96** [comment]
I'd say the file extensions should be enough to determine which compiler should be used.

**Comment by Araq** [comment]
I think this we do this nowadays.
