### ISSUE TITLE
Oddity if I go to nim-lang.org/docs

### ISSUE THREAD

**Issue by kirbyfan64** [nim-lang/Nim#2750]
Looks like this:

![screenshot_2015-05-17-15-06-06](https://cloud.githubusercontent.com/assets/1690697/7671903/f83f6a92-fca6-11e4-8ac5-ecf8f64f498a.png)

**Comment by runvnc** [comment]
I don't think anything actually links to docs now though does it? Its documentation.html

**Comment by kirbyfan64** [comment]
It's still slightly weird, though...

**Comment by dom96** [comment]
``/docs/index.html`` should be removed I guess.

**Comment by Araq** [comment]
doc/index.html has been removed.
