### ISSUE TITLE
Setting a timeout causes assertion failures in httpclient

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2753]
``` nim
import httpclient

echo getContent("https://gitlab.3dicc.com/gokr/lapp", timeout=400)
```

```
Traceback (most recent call last)
a21.nim(3)               a21
httpclient.nim(491)      getContent
httpclient.nim(472)      get
httpclient.nim(445)      request
httpclient.nim(435)      request
httpclient.nim(245)      parseResponse
httpclient.nim(170)      parseBody
httpclient.nim(160)      parseChunks
net.nim(714)             recv
system.nim(3058)         failedAssertImpl
system.nim(2280)         raiseAssert
Error: unhandled exception: avail <= size - read  [AssertionError]
```

**Comment by dom96** [comment]
Can't seem to reproduce anymore, but might be time sensitive.

**Comment by bradacina** [comment]
tried this today 25 Sept 2017 @ 9:09 PM (AEST) on "https://au.yahoo.com/"

**Comment by Yardanico** [comment]
@bradacina what's the result?

**Comment by bradacina** [comment]
`retrieving https://au.yahoo.com
Traceback (most recent call last)
download.nim(35)         download
download.nim(27)         downloadPage
httpclient.nim(1179)     get
httpclient.nim(1171)     request
httpclient.nim(1148)     request
httpclient.nim(1130)     requestAux
httpclient.nim(1029)     parseResponse
httpclient.nim(942)      parseBody
httpclient.nim(924)      parseChunks
httpclient.nim(883)      recvFull
net.nim(1155)            recv
net.nim(1133)            recv
net.nim(1108)            recv
system.nim(3613)         failedAssertImpl
system.nim(3605)         raiseAssert
system.nim(2724)         sysFatal
Error: unhandled exception: avail <= size - read  [AssertionError]`

**Comment by sclee15** [comment]
I found same error today here.

```
import httpclient
import asyncdispatch

echo "checking ping";

proc ddd(): Response =
  var client = newHttpClient(timeout = 10000)
  return client.get("https://au.yahoo.com")

var response = ddd()

echo response.status
echo response.body
```

```
checking ping
Traceback (most recent call last)
hello.nim(10)            hello
hello.nim(8)             ddd
httpclient.nim(1179)     get
httpclient.nim(1171)     request
httpclient.nim(1148)     request
httpclient.nim(1130)     requestAux
httpclient.nim(1029)     parseResponse
httpclient.nim(942)      parseBody
httpclient.nim(924)      parseChunks
httpclient.nim(883)      recvFull
net.nim(1155)            recv
net.nim(1133)            recv
net.nim(1108)            recv
system.nim(3613)         failedAssertImpl
system.nim(3605)         raiseAssert
system.nim(2724)         sysFatal
Error: unhandled exception: avail <= size - read  [AssertionError]
```

**Comment by skilchen** [comment]
if you want a quick fix:
change line 1112 in lib/pure/net.nim from:
```return sslPending```
to
```return min(sslPending, size)```

my usual disclaimer: the fix works for me, but i don't know. if it is a good solution...

**Comment by bradacina** [comment]
thank you sirs!
