### ISSUE TITLE
segfault on nimsuggest - use

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2759]
To reproduce:

    bin/nimsuggest compiler/nim.nim

    use compiler/suggest.nim:20:2

Backtrace:

    nimsuggest.nim(337)      nimsuggest
    nimsuggest.nim(327)      handleCmdLine
    nimsuggest.nim(282)      mainCommand
    nimsuggest.nim(203)      serve
    nimsuggest.nim(193)      parseCmdLine
    nimsuggest.nim(123)      execute
    modules.nim(203)         compileProject
    modules.nim(151)         compileModule
    passes.nim(197)          processModule
    passes.nim(137)          processTopLevelStmt
    sem.nim(455)             myProcess
    sem.nim(424)             semStmtAndGenerateGenerics
    semstmts.nim(1408)       semStmt
    semexprs.nim(906)        semExprNoType
    semexprs.nim(2232)       semExpr
    semstmts.nim(1199)       semProc
    semstmts.nim(1139)       semProcAux
    transf.nim(790)          transformBody
    transf.nim(775)          processTransf
    transf.nim(763)          transform
    transf.nim(104)          transformSons
    transf.nim(709)          transform
    transf.nim(528)          transformFor
    transf.nim(763)          transform
    transf.nim(104)          transformSons
    transf.nim(709)          transform
    transf.nim(472)          transformFor
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by Araq** [comment]
nimsuggest has its own issue tracker now.
