### ISSUE TITLE
Windows 64 bit could not load pcre.dll

### ISSUE THREAD

**Issue by sstirlin** [nim-lang/Nim#2765]
I have a simple jester project (basically a hello world) that is built with the 64-bit Windows 11.2 Nim.  However, when I try to run my executable I get

could not load:  pcre.dll

If I use Nim 32-bit instead then it works.  Looks like there might be something funny about the pcre.dll that comes with the 64-bit compiler.

**Comment by Araq** [comment]
The DLLs that ship are 32bit DLLs since Aporia is still a 32 bit app and getting DLLs for 64 bits for open source packages is/was hard. So, no bug here.

**Comment by sstirlin** [comment]
I don't understand how this is not a bug.  Building using the 64-bit Nim presumably means that my executables will be 64-bit.  Hence they will expect a 64-bit version of all of the DLLs that are dependencies.

As it is now, if I try to use regular expressions then my program will simply not run in 64 bit.  In other words, part of the standard library is broken in 64 bit.  That seems like a showstopper to me (unless I'm missing something).

Thanks!

**Comment by dom96** [comment]
The standard library is not broken, it's simply a case of compiling or downloading 64bit pcre DLLs.

**Comment by sstirlin** [comment]
A standard library that does not work out of the box is not a standard library.

You can leave it as is, but IMHO this is a usability issue that will drive away a lot of developers.  It's especially confusing because there is a pcre.dll in the Nim bin/ dir, but it happens to be 32-bit.  Devs have no way of knowing that and will simply become frustrated.

That would be a shame because I think Nim has a lot of awesome stuff about it (I'm a noob).  I've spent many weekends on Rust, but I grew a little weary of the lifetimes and other complexities.  Since I'm a C++ coder by day I was tempted to just slip back to that, but then I gave Nim a chance.  It seems awesome.

However, within a couple of hours I was annoyed with this issue (almost to the point of giving up).  I don't think you want to lose people because of usability concerns.  Great usability is the main reason golang has any traction at all, for example.  I'll back off now, but I'm definitely not the only one who will hit this:

http://forum.nim-lang.org/t/1187

**Comment by dom96** [comment]
I agree. I will reopen this.

**Comment by sstirlin** [comment]
Cool.  Thanks!

One followup:  I just built a 64-bit pcre.dll using Visual Studio.  I have checked that it works when using both Visual Studio and MinGW as a backend for Nim (this makes sense since PCRE is straight C code).

Let me know if you want it.  PCRE comes with a cmake build script and so this was pretty easy.  Thanks

**Comment by dom96** [comment]
@sstirlin Yes please! Send it to dom [at] picheta.me if you can.

**Comment by Elihio** [comment]
Same problem. Thanks for link to forum topic. Just downloaded 64-bit dlls and it helped.

**Comment by Araq** [comment]
pcre.dlls are now distinguished.
