### ISSUE TITLE
Embedded templates with iterators fails to compile

### ISSUE THREAD

**Issue by petermora** [nim-lang/Nim#2771]
The following code fails to compile. I'm wrapping templates with templates, and if the passed value is an iterator, then I get **Error: illformed AST** message.

``` nimrod
# this compiles:
template t1(i: int): int=
  i+1
template t2(i: int): int=
  i+1

echo t1(10).t2()


# this doesn't:
template it1(i: int): iterator(): int =
  iterator result(): int {.closure, gensym.} =
    yield i+1
  result

template it2(iter: iterator(): int): iterator(): int =
  iterator result(): int {.closure, gensym.} =
    yield iter()+1
  result

let x = it1(10).it2()
```

If I save the intermediate result to a variable, then it compiles and runs fine:

``` nimrod
let x = it1(10)
let y = x.it2()
```

**Comment by reactormonk** [comment]
The error is:

    test.nim(12, 3) Error: illformed AST: iterator result(:envP): int {.closure, gensym.} = 
      goto :envP.:state
      state 0
      :envP.:state = 1
      return result = 11
      state 1
      :envP.:state = -1

`:foo` is a compiler-generated symbol.

The line with

      return result = 11

Most likely causes the issue - that's not valid nim.

**Comment by ringabout** [comment]
It compiles since Nim v 1.4.0.
