### ISSUE TITLE
Converter does not allow T(x) conversion

### ISSUE THREAD

**Issue by bit-01101** [nim-lang/Nim#2772]
type Foo = object
        bar: string

    converter toFoo*(x: string): Foo = result.bar = x

    var foo: Foo = "foobar"     # works
    discard Foo("foobar")       # Error: conversion from string to Foo is invalid

**Comment by dom96** [comment]
You need to call the converter in that case: ``discard toFoo("foobar")``. But perhaps that should be allowed.

**Comment by ozra** [comment]
Seems like the expected bahavior to me that the converter is picked and used as constructor in that case.

**Comment by Araq** [comment]
Now compiles.
