### ISSUE TITLE
keepIf doesn't return control to caller in macro.

### ISSUE THREAD

**Issue by jazzonmymind** [nim-lang/Nim#2783]
It looks like keepIf() doesn't return control to the caller from within a macro. I am new to nim, but more experienced people on IRC said it could be a bug. The reproduction is below, I extracted it from a silly thing I was working on. After calling keepIf(), it doesn't appear to go any further. There are no errors.

__nim -v__
```
Nim Compiler Version 0.11.2 (2015-05-24) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 6c8f7cc481f508ac3873d5c5529e67d60c61b8ee
```
__reproduction__
```nimrod
import macros, sequtils
macro blah(): stmt =
  var t: seq[string] = @["1", "2", "3"]
  echo "hi" # prints during compile
  keepIf(t, proc(s: string): bool = s != "3")
  echo "oh" # never reaches here
  parseStmt("[]")
blah()
```

**Comment by Araq** [comment]
Now works.
