### ISSUE TITLE
Inconsistant implementations of streams.readLine()

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#2794]
`readLine*(s: Stream, line: var TaintedString): bool` fails in cases that `readLine*(s: Stream): TaintedString` doesn't.

/cc @Araq

**Comment by avsej** [comment]
does #2799 fix the issue?

**Comment by avsej** [comment]
oh, that was peekLine

**Comment by dom96** [comment]
In what cases?

**Comment by flaviut** [comment]
If [`readLine*(s: Stream): TaintedString`](https://github.com/nim-lang/Nim/blob/d9cb85c2d81a447130307d0004b0ef515f3ff241/lib/pure/streams.nim#L288-L300) hits the end of the string, it will return `""` and not fail. If [`readLine*(s: Stream, line: var TaintedString): bool`](https://github.com/nim-lang/Nim/blob/d9cb85c2d81a447130307d0004b0ef515f3ff241/lib/pure/streams.nim#L257-L275) hits the end of the string, it will put `""` in the var parameter and return failure.

There isn't any way to tell if the end of the string has been encountered in `readLine*(s: Stream): TaintedString`. Throwing an exception or returning `nil` may be more expected.

A possible alternate implementation may be

```nim
proc readLine*(s: Stream): TaintedString =
  result = TaintedString""
  if not s.readLine(result):
    return nil
```

**Comment by andreaferretti** [comment]
Seems to be fixed

```nim
import streams

let s = newStringStream("hello")

echo s.readLine()
echo s.readLine()
echo s.readLine()
```

outputs

```
hello
t2794.nim(6)             t2794
streams.nim(307)         readLine
Error: unhandled exception: cannot read from stream [IOError]
```
