### ISSUE TITLE
Unify syntax so that `static[T]` -> `T{static}` or even `T{const} or solved automatically.

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2812]
I think it would be more obvious to the programmer to use the constraint notation (like `T{lit}`), thus: `T{static}`, or then by extension, `T{const}`. The syntax would be more heterogeneous. Comparing with C++, this would go in to template args. I like the Nim-way more, and I've implemented it like so in a specific mutator transpiler (non Nim related), and it seems to work out well in practice. What I've referred to here is when used in proc signature, and that is true for the remainder of this issue. _Regarding static type-constructor-decls I have not thought much about the relation._ 

Optimally it shouldn't be needed at all, and instead be part of a general (advanced) optimization pass. It could be an optimization option where Nim would count the calls to procs. For called-once-procs, see which _args_ are constant / compile time solvable, make optimized instantiations of procs marked for `inline`, or rather a new pragma: perhaps `{.autoSpecialize.}` or something. Procs called once only can be inlined immediately with the specialization. Any specializations can be counted individually after a proc has been chosen to be specialized, and all the instantiated specializations could then be inlined also, if they in turn are called once only. 

Of course this increases compilation time and complexity, and that's why it should be behind a specific compiler flag, just like inlining in backends. This would obviously require more effort, but saves the effort of implementing a feature whose only purpose is optimization, albeit coder 'hard guided'. Which empirically seldom yields the intended performance gain.

In the latter solution, the static[] notation could be dropped entirely and postponed as an optimization feature. Possibly just adding a guiding `autoSpecialize` pragma to reduce graphing and analyze time, which then could be acted upon _when_ such features are actually implemented.
(Getting syntax nailed down before 1.0, but posponing the bonuses..)

**Comment by andreaferretti** [comment]
I don't think that `static[T]` is going to change into `T{static}`, shoudl we reject the RFC?

**Comment by Araq** [comment]
Sadly, AST constraints cannot be subsumed under ``static`` or vice versa. See the upcoming ``macro fmt(x: untyped{strLit}`` language design fix.
