### ISSUE TITLE
Error in `static[T]` inference

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#2815]
The following compiles cleanly and prints `4`

```
type Vect[N: static[int]] = array[N, int]

proc foo[N: static[int]](xs, ys: Vect[N]): int = N

echo foo([1, 2, 3], [4, 5, 6, 7])
```

The expected result would be a compilation error, since it is not possible to infer a correct value for `N` that is valid for both `xs` and `ys`

**Comment by Araq** [comment]
Yeah I noticed that one too, it's even in our test suite as an example that *should* compile... Makes not too much sense, but I'm afraid this will break some really useful code out there.

**Comment by andreaferretti** [comment]
This seems fixed with latest devel
