### ISSUE TITLE
Destructor not called, when initialised with assignment operator

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#2821]
Originated from here: http://forum.nim-lang.org/t/1204
```nim
{.experimental.}

type T = object

proc `=`(lhs: var T, rhs: T) =
    echo "assign"

proc `=destroy`(v: var T) =
    echo "destroy"

block:
    var v1 : T
    var v2 : T = v1
```
Actual output:
```
assign
destroy
```
Expected output:
```
assign
destroy
destroy
```

**Comment by ozra** [comment]
According to http://forum.nim-lang.org/t/1204 one gets the impression that this might be a conflict because of the `=...` in the identifier. If this is the case it could be a lot simpler. Thus even possible for a newbie like me to handle?
Any ideas on the "simplicity" of the bug?

**Comment by Araq** [comment]
@ozra How destructors are injected into the AST is broken beyond repair and needs a different algorithm. I'm still thinking about the best way to do that. So quite hard to fix.

**Comment by ozra** [comment]
Aha, then it is far out of reach for me to fix. 
Curious: Aren't destructors dynamically called by GC when cells are picked for tossing? When do they have to go into AST (except for definition of course)?

**Comment by Araq** [comment]
Fixed.
