### ISSUE TITLE
Operator and infix declaration syntax

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2836]
I found this notation to be quite ugly: `for i in 0..<47`, so I wanted to make an alternative operator: `for i in 0 til 47`, which brought me back to an issue I've been thinking about for a while.

A nice feature would be to be able to declare operators in a similar fashion to Agda (Agda + Nim term rewrites cross pseudo syntax below, that are very similar) - and by extension, also for templates:
```nim
template { _ til _ }(a, b: expr): expr =
    a .. <b
```

_If this actually can be done, and I was to stupid to get that from the man, please enlighten me._

On a side note, which might be interesting to get the mind bubbling, since Nims operator precedence rules are a bit limited atm: in Agda (don't know if it's upstream yet), operators don't have fixed number precedences, but rather relative precedence. This means that the grammar formed by user operators is allowed to be ambiguous, or unsolvable, because not all operators are used in the same contexts because of their type relations. When _an expression_ is ambiguous or unsolvable because of faulty use of the declared operators, it's an error. This requires acyclic precedence graphing of the expressions in order to solve the operators precedence, and is more of an interesting note - I think the time cost might be to much to even consider it. But do not know.

It must be noted that Agda is a dependently typed, quite different language, so of course it might be hard to handle these things in a raw power language like Nim.

**Comment by yglukhov** [comment]
That would be context dependant grammar. Consider this:
```nim
var abc = 0
var def = 5
template { _ til _ }(a, b: expr): expr =
    a .. <b
for i in abc til def: ...
# It can be parsed as:
for i in abc(til(def)):
# in your case you add another meaning
for i in til(abc, def):
```
As much as I love a lot of syntax flexibility, this feature can hardly be accepted.

**Comment by ozra** [comment]
Yes, exactly. Would there be any way of getting the `for i in x til y` syntax, _without resorting to source filtering_? I really think it should be available - it won't kill me, but it just looks a lot cleaner, and that loop (..<) is _such_ a common construct.
This: ``for i in x `til` y`` does not work either, but then, it's as "unclean" anyway, so that I might as well use the existing notation.
Some lang's use `a...b` to, kind of counter intuitively, mean `..<`. That looks cleaner, but seems more error prone, so is worse than ..<.

Oh well.

**Comment by Araq** [comment]
In my opinion strongSpaces fix the operator precedence mess but cannot be enabled for political reasons. What you describe here are means to make the parsing context sensitive. Not gonna happen. That Nim can really be parsed without any symbol table is a very very nice feature.

**Comment by ozra** [comment]
Yeah, it's not worth giving up that. The compilation speed is a real win!
