### ISSUE TITLE
system.getRefCount() can't be used on different types

### ISSUE THREAD

**Issue by fowlmouth** [nim-lang/Nim#2839]
related to #1579, getRefCount can only be used on one type at a time, uncommenting any two of these fails:

``` nim
let x = (ref RootObj)()
echo x.getRefCount

let s = "HI"
echo s.getRefCount

let s2 = @[1,2,3]
echo s2.getRefCount

let s3 = @["z","x"]
echo s3.getRefCount
```

I have an ugly workaround for this:

``` nim
proc grc* (some: ref|string|seq): int =
  getRefCount(cast[ref int](some))

let x = (ref RootObj)()
echo x.grc
let s = "HI"
echo s.grc
```

and it could be fixed in system.nim with:

``` nim
proc grc (x: pointer): int {.importc: "getRefcount", noSideEffect.}
proc getRefcount*(x: seq|string|ref): int {.noSideEffect, inline.} = grc(cast[pointer](x))
```

**Comment by fowlmouth** [comment]
er so the real problem here is importc on a function without header/dynlib behaving improperly, I'm going to send a PR that adds `header:"nimbase.h"` to those functions

**Comment by Araq** [comment]
You shouldn't use getRefcount anyway. It's not reliable and always 0 for mark&sweep.

**Comment by fowlmouth** [comment]
Need to make sure that refs are safely stored in my entity lib, see entoody, I store them in block of memory and need to make sure a ref type stored there can't be freed early. And I've found getrefcount is reliable if you call gcfullcollect first.

**Comment by Varriount** [comment]
Can't you just increment the refcount by one? That should keep a reference from being gc'ed, until an accompanying decrement is made.

**Comment by fowlmouth** [comment]
wow what exactly is the issue here? The functions are broken right now, useless. I have code that now depends on this.

**Comment by fowlmouth** [comment]
@Varriount omg so helpful
No, I'm writing generic tests for gc safety. I know about GCref() and GCunref().

**Comment by narimiran** [comment]
Since `getRefcount` is now deprecated, I'm closing this.
