### ISSUE TITLE
Reconsider fastcall vs stdcall

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2842]
In most situations on the x86, with the common C compilers, `stdcall` is faster than `fastcall`.
The reasons being many (google it! _shortly: register re-use in larger procs, smaller procs being inlined instead of called, further calls requiring stacking anyway, registers sometimes not actually being real registers anyway, etc._).

Also, if this holds true regarding fastcall:
> The first two DWORD or smaller arguments are passed in ECX and EDX registers; all other arguments are passed right to left.

Then, given that `int` is 64 bit in Nim on most x86 installs, it will _only_ be detrimental for _almost_ all code, and likely slower or at tops equal, for the rest.

It might be a good idea to re-evaluate the choice before 1.0.

Best option is of course to benchmark a bunch of Nim code and see what actual use-cases yield.

**Comment by kirbyfan64** [comment]
@Varriount said on the forums that Nim uses the native pointer size as its int, so 4 bytes on x86.

**Comment by ozra** [comment]
@kirbyfan64 - few people run a 32bit OS, even fewer a 32bit machine. Personally I have Ubuntu 32 bit on one machine, but this only for testing purposes.
So, count on it being 8 bytes generally.

**Comment by kirbyfan64** [comment]
But you said the int is 64-bit on 32-bit installls. It's 32-bit (4 bytes).

**Comment by ozra** [comment]
@kirbyfan64 - ah, now I get it, you refer to the "x86" mention? I just mean all processors of x86 heritage, contrasting Atom, Z80 ;-), what have you not..

**Comment by Araq** [comment]
x86_64 uses only 1 calling convention anyway which is register based, so this discussion only applies to x86. And for x86 fastcall should be faster for the ordinary Nim code out there.

**Comment by ozra** [comment]
Alright.
