### ISSUE TITLE
Developer friendly errors for undeclared identifiers

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2844]
`somefile.nim(13, 6) Error: undeclared identifier: 'somVarName'`

Clang is exceptional and a role model in this department. When the compiler has encountered an error, we might spend some extra cycles making it more helpful.

I suggest simply using  Levenshtein distance algorithm on the scoped symbols where the error occured. Which in this case could have produced:

`somefile.nim(13, 6) Error: undeclared identifier: 'somVarName'. Did you mean 'someVarName'?`

Ofcourse if there are several near matches, they can be listed in 'nearest' order.

(I might take this on in a not too far future, if it's liked)

**Comment by kirbyfan64** [comment]
What I would really like are colors to help in visually separating hints, errors, and the possible invocations of ambiguous or overloaded functions.

**Comment by ozra** [comment]
@kirbyfan64 - create an issue if there isn't one. It's free to wish. Or make a PR..
