### ISSUE TITLE
Compiler should output errors on stderr, not stdout

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2846]
nim should behave *nixy in the *nix eco-system. One of the great benefits is the ability to "program the system" using apps as "function", by tying them together through scripts etc.

When applications don't play along with the commonly accepted methodologies, it breaks such inter-connectivity.

Errors should be output on `stderr`. Warnings, hints, all other messages on `stdout`

**Comment by reactormonk** [comment]
I perceive `stderr` as message channel, and would put warnings and hints in there as well.

**Comment by ozra** [comment]
Had it been a generic application, I'd say yes, but when it's a compiler, I'd expect all output to be information on the compilation and then it makes more sense to put just the errors out on stderr, imo.

**Comment by kirbyfan64** [comment]
Every compiler I know of (Clang, GCC, Intel) puts both warnings and errors on stderr.

**Comment by ozra** [comment]
@kirbyfan64 - alright. Then definitely as you and @reactormonk say.

**Comment by kress95** [comment]
I'm using a custom build script that colors stderr (bold red) and stdout (blue), and it's not working well with nim because it outputs everything to stdout, so +1 to this issue.

**Comment by Araq** [comment]
This has been implemented for 0.12.0.
