### ISSUE TITLE
Testament / Tester / "./koch tests" gives unreliable inconsistant results!

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2858]
I ran tests on 'devel' branch, and on my 'feature-branch' and diffed them. Baam, changes. Bugs I think. Starts digging. Nothing wrong with my code.
Runs tests again on devel - **gets new results in test output**!
It's the same devel-branch - no pull/fetch origin in between - no changes.

I will look at this immediately.

**Comment by ozra** [comment]
**This only affects compiler developers / hackers, and only if you run tests on a repo that is not the one used as 'global path nim'**.
Fix in the baking at #2862.

**Comment by Araq** [comment]
Well? has that even been a real bug?

**Comment by ozra** [comment]
I guess that one's a matter of perspective ;) In any event, the PR will execute tests according to expectation at all times (uses compiler and libs relative to the dir of the cwd of tester execution).

**Comment by Araq** [comment]
What about the people who run the tests after installation?

**Comment by ozra** [comment]
The tests rely on a "global" nim compiler for building the compiler to be tested. Then it runs `compiler/nim` for the tests.
