### ISSUE TITLE
renaming of types in sdl.nim to new style is a disaster

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#2876]
RWops is declared twice
ActiveEvent collides with ACTIVEEVENT
UserEvent collides with USEREVENT
SysWMEvent collides with SYSWMEVENT
NewTimerCallback misspelled NewTimerCallabck

and several others...
What is the recommended naming convention when a type name collides with an enum or constant, like the cases above ?

**Comment by ozra** [comment]
As I've understood the Nim recommendation, constants should be named like variables, not upper case. That would solve it, no?
`ActiveEvent` vs `active_event / activeEvent`
Or it if it enums, use a small enum-prefix.
Or use the original SDL_ prefix for enums?
Or make enums qualified pure?

Some good practise for it would be nice for future (inevitable) conflicts. Mixing TType and Type doesn't feel yippie kie yay..

**Comment by Perelandric** [comment]
The original naming conflicts were noted under the PR and have been copied to the original issue https://github.com/Araq/Nim/issues/2773 with this new one included.

**Comment by Araq** [comment]
SDL is not part of the stdlib anymore.
