### ISSUE TITLE
$ on a nil seq[T] shouldn't return "@[]"

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2889]
```nim
var x: seq[string]

echo x
```

Output:

```
@[]
```

This is incredibly misleading.

**Comment by HaCk3Dq** [comment]
What should it return then?
Its an empty seq, i think its correct, imho

**Comment by reactormonk** [comment]
Do all the procs on `seq` work with null?

**Comment by HaCk3Dq** [comment]
Only map fails from nil ```seq```

```Nimrod
var x: seq[int]

let y = map(x, proc(x: int): string = $x)
echo y
```

Output:
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```

**Comment by Araq** [comment]
@dom96 For $ perhaps but in general the point of 'len' returning 0 for 'nil' is to avoid special casing everywhere.

**Comment by bluenote10** [comment]
> What should it return then?

I would go for just the string `nil` because it has an alarming connotation, which imo is good in this case.

> Its an empty seq, i think its correct, imho

Well, literally, it is not a sequence which is empty -- it is 'nil'. I would also prefer to have a different string representation for `nil` vs `@[]`. Regarding logging, it really makes sense to see the difference.

**Comment by nanoant** [comment]
IMHO should return `nil` not `@[]`.

As for `len` I think it should crash on `nil` like any other proc, or we should treat `nil` as empty sequence consequently everywhere (i.e. `map` `len` etc.) like in Objective-C. But I prefer Nil to stay system's language, so crash.

**Comment by dom96** [comment]
I'm not sure I like the special casing that ``len`` gets.

**Comment by Araq** [comment]
We discussed this and made the decision. Also it's not dangerous anymore once 'add' also can deal with 'nil'.
