### ISSUE TITLE
Term rewriting macros being applied repeatly

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2901]
The example listed in http://nim-lang.org/docs/manual.html#term-rewriting-macros-pattern-operators

```
template t{(0|1|2){x}}(x: expr): expr = x+1
let a = 1
# outputs 2:
echo a
```

outputs `3`, because the template `t` is applied repeatly. I see both
usecases where you have a repeated application and and where you
don't, how should this be solved?

At least the documentation needs to be fixed.

**Comment by kaushalmodi** [comment]
I can reproduce this even today. Evaluating the code block in https://nim-lang.org/docs/manual.html#pattern-operators-the-operator gives "3" instead of "2".

**Comment by andreaferretti** [comment]
This is somehow implicitly stated in the manual when it mentions

> So what about 2 * a? We should tell the compiler * is commutative. We cannot really do that however as the following code only swaps arguments blindly:

The blind swap would get into an infinite loop.

As far as I can tell, this is the intended behaviour (and I think this is right: applying an optimization can trigger more optimizations), so it should just be mentioned in the manual more explicitly
