### ISSUE TITLE
import broken for certain names

### ISSUE THREAD

**Issue by ggVGc** [nim-lang/Nim#2904]
Not sure about the details, but it seems like '2d' is being parsed as a number in an import block.
```nim
import
  scene/2d/sprite,
  scene/2d/node_2d,
  math/math_2d
```
gives me this error
`Error: cannot open 'scene/2.0'f64/sprite'`

**Comment by ozra** [comment]
I introduced the `123d` as alias for `123f64` in a recent PR. However, that is not the root problem here, but rather revealed the issue.

Should numbers be allowed as first letter in import names? Or, should the lexer be made more nuanced?

**Comment by reactormonk** [comment]
Imo
```nim
import
  "scene/2d/sprite",
  "scene/2d/node_2d",
  "math/math_2d"
```

**Comment by ozra** [comment]
A, of course. Otherwise we'd have to go down C(++)-parsing road - making lexing parsing aware.

**Comment by Araq** [comment]
We need to document this breaking change, but apart from that it's fine with me.

**Comment by ozra** [comment]
I can doc it, I need to update some things relating to the num lexing in the docs anyway.
