### ISSUE TITLE
Random number change

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2907]
The Windows-specific random function at https://github.com/nim-lang/Nim/blob/devel/lib/pure/math.nim#L214 caps the random number generation at 32767 (for a good reason, see https://msdn.microsoft.com/en-us/library/398ax69y.aspx). However, since Windows XP, `rand_s`, a more secure version that writes to a `cuint`, has been available.
I don't think there's an easy way to check Windows versions in Nim, but I think it's safe to assume that people are running >= XP, so I think it would be worthwhile to switch over to `rand_s`. Something like:
```nim
proc rand(res: var cuint) {.importc: "rand_s", header: "<stdlib.h>".}
```
There would be a little bit of rewriting, but I'd be happy to do it if it people agree on the switch.
`rand_max` should also be rewritten to 4294967295, which is `UINT_MAX` on seemingly every platform (the macro doesn't have any #if/#else in `limits.h`, at least in MinGW). See https://msdn.microsoft.com/en-us/library/296az74e.aspx

Note this avoids importing things like CryptGenRandom, but they're used in the background, so it's "secure" (there are some problems, but that's another issue).

**Comment by reactormonk** [comment]
Sounds like a good idea to me, feel free to make a PR.
