### ISSUE TITLE
64-bit literals broken on x86

### ISSUE THREAD

**Issue by avsej** [nim-lang/Nim#2909]
https://github.com/nim-lang/Nim/blob/70e157d79e3953dcb122dac46e9e5ca5eacdfd99/lib/pure/times.nim#L445

```
lib/pure/times.nim(445, 17) Error: number 116444736000000000'i64 out of valid range
```

Full log: https://copr-be.cloud.fedoraproject.org/results/avsej/nim-devel/fedora-rawhide-i386/nim-0.11.3-530.g70e157d.el7.centos/build.log.gz

**Comment by yglukhov** [comment]
Mentioning @ozra

**Comment by ozra** [comment]
Just glancing at the code, it seems like my PR at #2890 will fix this problem too.

**Comment by avsej** [comment]
@ozra with your patches, it still fails on i386 https://copr-be.cloud.fedoraproject.org/results/avsej/nim-devel/fedora-rawhide-i386/nim-0.11.3-533.g7ca61f4.el7.centos/build.log.gz

**Comment by ozra** [comment]
I've narrowed this down to lib/pure/parseutils.nim : rawParseInt().
It dies as soon as the value goes beyond 32 bit. Even though it accumulates on a BiggestInt var, and echo verifies .low/.high of BiggestInt to be 64bit. Much peculiar..
I reproduced this on a 32bit machine. Not 64b.

**Comment by Perelandric** [comment]
Just hit this bug on 32-bit Arch. Can we temporarily roll back commit https://github.com/nim-lang/Nim/pull/2896 until it's figured out?
