### ISSUE TITLE
Macro documentation

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2916]
I'm taking a swing at improving the macro documentation a little, but I'm running into the wall of my ignorance as follows. You'll see what I can't identify below:

Concrete Syntax
---------------
```nim
proc hello*[T: static[int]](x: int = 3, y: float32): int {.inline.} = discard
```

AST
---
```nim
nnkProcDef(
  nnkPostfix(nnkIdent(!"*"), nnkIdent(!"hello")), # the exported proc name
  nnkEmpty(), # What is this??
  nnkGenericParams( # generic type parameters
    nnkIdentDefs(
      nnkIdent(!"T"), nnkIdent(!"SomeInteger")
    )
  ),
  nnkFormalParams(
    nnkIdent(!"int"), # the first FormalParam is the return type. nnkEmpty() if there is none
    nnkIdentDefs(
      nnkIdent(!"x"),nnkIdent(!"int"),nnkIntLit(3)
    ),
    nnkIdentDefs(
      nnkIdent(!"y"),nnkIdent(!"float32"),nnkEmpty()
    )
    nnkPragma(nnkIdent(!"inline")),
    nnkEmpty(), # What is this??
    nnkStmtList(nnkDiscardStmt(nnkEmpty())) # the meat of the proc
  )
)
```

I searched around, but the use within Nim itself obviously doesn't have exhaustive documentation to figure it out. I've tried different ways of setting up the proc to no avail.
Any helps or tricks for the future are appreciated.

**Comment by Araq** [comment]
The first empty slot is where *patterns* can be stored for TR macros/templates.
The second empty slot you wonder about is currently used for the effect tracking iirc but in general an empty slot so that we can extend the language/AST without major troubles.

**Comment by ozra** [comment]
@apense: A tip for further exploration:
- look at "compiler/renderer.nim" to see how nim concrete code is rendered from AST (in this case `^proc gproc` (line 703 atm)
- search for `^\s\spatternPos`, etc. consts, in "compiler/ast.nim" to find important const defs.

(patterns in RE above, if it wasn't obvious)

Great initiative btw!

**Comment by Araq** [comment]
This has been merged, right?
