### ISSUE TITLE
Mutually recursive types involving proc arguments fail to compile

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2920]
The following code fails to compile because C types aren't generated in the correct order. Using `var x: B` instead works, as well as introducing references in the cycle (e.g. by making `B` a `{.byref.}` type, making the `b` argument a `var` parameter, or using `ref object` instead of `object`).

```nim
type
  A = object
    p: proc(b: B)
  B = object
    a: A

var x: A
```

**Comment by yglukhov** [comment]
Duplicate of #2823?

**Comment by Araq** [comment]
Duplicate of #2823.
