### ISSUE TITLE
function overloading and recursion

### ISSUE THREAD

**Issue by Mat2** [nim-lang/Nim#2927]
Its not possible to overload functions in case of recursive function bodies:
```
proc berannAsmFill (bundle : tCodeBundle, slots : tBaseImm): tCodeBundle =
          if slots > 0: result = berannAsmFill (bundle shr 4, slots - 1)
          else: result = bundle shr 4
proc berannAsmFill (bundle : tDataBundle, slots : tBaseImm): tDataBundle =
           if slots > 0: result = berannAsmFill (bundle shr 4, slots - 1)
          else: result = bundle shr 4
```
This lead to an error. An alternative way is declaring something like this:
```
proc berannAsmFill (bundle : (tCodeBundle or tDataBundle), slots : tBaseImm): (tCodeBundle or tDataBundle) =
          if slots > 0: result = berannAsmFill (bundle shr 4, slots - 1)
          else: result = bundle shr 4
proc berannAsmFill (bundle : tDataBundle, slots : tBaseImm): tDataBundle =
           if slots > 0: result = berannAsmFill (bundle shr 4, slots - 1)
          else: result = bundle shr 4
```
Error: type mismatch: got (tCodeBundle or tDataBundle) but expected 'tCodeBundle or tDataBundle'

if I finally declare a type 'type tBundle = (tCodeBundle or tDataBundle)' and change the first line to 'berannAsmFill (bundle : tBundle, slots : tBaseImm): tBundle =' the code compiles without error.

I don't know if this behaviors are intended or caused by bugs.

**Comment by Araq** [comment]
Well you need a forward declaration for mutally recursive procs, overloading has nothing to do with it.
