### ISSUE TITLE
Bad code in documentation

### ISSUE THREAD

**Issue by alexamy** [nim-lang/Nim#2928]
In Tutorial (Part I), section "Forward declaration" code is simply can be thrown in endless recursion by calling even(1) or odd(0). My solution (isn't the best maybe) is:
```
proc odd(n: int): bool =
  if n == 0: 
    true
  else: 
    n == 1 or even(n-1)

proc even(n: int): bool =
  if n == 1:
    false
  else:
    n == 0 or odd(n-1)
```

**Comment by reactormonk** [comment]
@alexamy could you throw in a pull request?

**Comment by apense** [comment]
@alexamy Just a small recommendation: 

```nim
proc odd(n: int): bool =
  assert(n >= 0) # makes sure we don't run into negative recursion
  if n == 0: 
    true # should be false, since zero is even
...
```
Good catch!

**Comment by alexamy** [comment]
Ok. I pulled a request with all these changes.

**Comment by BigBoneDaddy** [comment]
@alexamy  Thank you Alexander for your contribution!
