### ISSUE TITLE
Parsing of range in AST

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2929]
Rather than being constructed with `nnkRange`, as `macros.nim` suggests, it seems that ranges are just treated as normal infix operators.  `dumpTree` gives:

```nim
dumpTree:
  3..5
#StmtList
#  Infix
#    Ident !".."
#    IntLit 3
#    IntLit 5
```
(Same behavior inside `for` statement)

Building a test macro this way works as expected:
```nim
macro genRepeatEcho(): stmt =
  result = newNimNode(nnkStmtList)
  var forStmt = newNimNode(nnkForStmt)
  forStmt.add(ident("i"))
  var rangeDef = newNimNode(nnkInfix).add(
    ident("..")).add(
    newIntLitNode(3),newIntLitNode(5))
  forStmt.add(rangeDef)
  forStmt.add(newCall(ident("echo"), newIntLitNode(3)))
  result.add(forStmt)

genRepeatEcho()
# gives:
# 3
# 3
# 3
```

My question is, is `nnkRange` actually used? I know `nkRange` is, but it seems there's no mapping between them in the compiler. Totally likely I'm just not seeing it, though.

`dumpTree` gives the same infix behavior in case statements, array slices, etc.
```nim
dumpTree:
  var x = {3..5}
# ...
#  Curly
#    Infix
#      Ident !".."
#      IntLit 3
#      IntLit 5
```

So sorry for this long post. Figured it would be better to place here rather than trying to get the answer over IRC.

**Comment by Araq** [comment]
Document that 'nnkRange' should not be used for constructing ASTs but instead the way you describe it.
