### ISSUE TITLE
Manual / Docs should be autogened from git hook

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2932]
Looks like the manual on the web page is out of date.

It should probably be automated so that updates to the manual automatically are generated to the web page, no explicit fiddling required.

**Comment by Araq** [comment]
The manual claims to document 0.11.2 and that is what it does. We need *additional* docs that belong to devel, but I'm sure there is already an issue created for that.

**Comment by ozra** [comment]
ah, ok.
