### ISSUE TITLE
OS X automatic build (status image) broken

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#2933]
OS X automatic builds images are broken, they return some fancy `unknown build number 'None'` output instead of the images.

![zrzut ekranu 2015-06-15 o 15 03 38](https://cloud.githubusercontent.com/assets/103067/8160406/b8ee6dc2-136f-11e5-96d0-058c0783e9bd.png)

    $ curl https://camo.githubusercontent.com/ca9a849c9ef3dbf8f2868b0f3f74cb79f07189bc/687474703a2f2f6275696c64626f742e6e696d2d6c616e672e6f72672f6275696c64737461747573696d6167653f6275696c6465723d6d61632d7833322d6275696c646572
    unknown build number 'None'

**Comment by Varriount** [comment]
This should probably be mentioned at github/nim-lang/nim-buildbot . The main reason for this is because we haven't had anyone volunteer a Mac OSX builder...

**Comment by Araq** [comment]
Move issue to github/nim-lang/nim-buildbot please.
