### ISSUE TITLE
Compiler error on building koch.exe

### ISSUE THREAD

**Issue by axbender** [nim-lang/Nim#2937]
After updating from git yesterday I keep getting the following error message:

``lib\system.nim(687, 40) Warning: unknown magic 'BitnotI64' might crash the compiler [UnknownMagic]``

This also happens after bootstrapping via:

```
git clone https://github.com/Araq/Nim.git d:\tools\nim
cd d:\tools\nim
git pull
```

**Comment by def-** [comment]
Bootstrap again from csources as described here: https://github.com/nim-lang/Nim#compiling

**Comment by axbender** [comment]
Update: Error has gone with today's pull...
