### ISSUE TITLE
Float nodes (nnkFloatLit)

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2939]
I know that `float` and `float64` use the same [compiler magic](https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L44). Is this making them both use `nnkFloat64Lit`?

```nim
dumpTree:
  42.0'f64

# gives
# Float64Lit 42.0
```

Are they really just synonyms? I don't see a need to update the docs in case this changes in the future.

FYI, is there any reason ``nnkFloat128Lit`` is in there? I guess it's useful for whoever is going to make `float128`s, though.

I'm on an amd64, if that makes any difference.

**Comment by Araq** [comment]
I don't know. Just document the current behaviour.
