### ISSUE TITLE
Distinct types with the same base type are convertible between each other

### ISSUE THREAD

**Issue by Perelandric** [nim-lang/Nim#2941]
It's possible to directly convert one distinct type to another:
```
type
  Dollar = distinct int
  Euro = distinct int

var
  d: Dollar = 1.Dollar
  e: Euro = d.Euro
```

I can understand that it makes sense to be able to convert to its base type but it seems like conversion between distinct types opens more possibilities for accidental, unintended conversions, like:
```
var double: Euro = e.Euro + d.Euro
```
If this was not permitted, it would still be possible with a more verbose syntax, making mistakes harder.
```
var
  d: Dollar = 1.Dollar
  e: Euro = d.int.Euro
```

The manual does allow this in its type conversion algorithm. Should it be made more strict?

**Comment by Varriount** [comment]
I would understand your concern if the conversion was implicit, but otherwise, what extra safely does the added verbosity give? In most cases, you already know the source variable's type, so you're already acknowledging explicitly that you want a type conversion from A to B.

**Comment by Araq** [comment]
I think it's just fine the way it is.

**Comment by Perelandric** [comment]
The extra safety comes in catching the stupid mistakes we make. Typing one variable when we meant to type another. Juggling a bunch of stuff in your head and simply typing out the wrong thing. The silly little mistakes that end up being catastrophic.

I guess my question would be what's the *benefit* of allowing direct conversion? If the types were made to be distinct, then there's usually a reason for it. 

Would you ever *want* to directly convert a Dollar to a Euro or an Imperial unit to a Metric? Are there compelling use cases for allowing it?

**Comment by reactormonk** [comment]
Imo an explicit conversion to the base type should be necessary.

**Comment by dom96** [comment]
I think this could potentially result in lot's of code breakage and I personally don't see why this should be necessary.

Looks like @Araq agrees so I will close this for now.
