### ISSUE TITLE
Printing arrays (feature request?)

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2942]
I read about [printing arrays](https://github.com/nim-lang/Nim/blob/master/lib/system.nim#L2100), and while I don't pretend to understand the details of bootstrapping or working around it, I have a suggestion.

When you try this

``` nim
echo ([3,2,1])
```

the error message `Error: type mismatch: got (Array constructor[0..2, int])` isn't very helpful if someone new comes in. A lot of high-level languages just sort of print arrays (I'm thinking mainly of Python, but it prints a bunch of things), and it's fine if Nim can't do that, but a better error message could be useful. It's not clear how to get around it when you're new (at least, I had this problem when I started). Maybe prompt to convert to a seq? 

PS I know you can make the `$` proc yourself, but it does seem like it would be in the standard library, so a good explanation message seems like a nice idea.

**Comment by Varriount** [comment]
And what do we do for unchecked arrays?

**Comment by TiberiumN** [comment]
https://github.com/nim-lang/Nim/pull/5910

**Comment by krux02** [comment]
@Varriount  good question, but generally speaking an unchecked array and an array are very different types. One type has it's size encoded in the type, the other one does not. The best thing an `$` can do on an unchecked array would be ``[...]``.

**Comment by Araq** [comment]
Printing of arrays is now supported.
