### ISSUE TITLE
Can't cast to unchecked array

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2943]
In the manual unchecked arrays are introduced with range `0..0`, but this causes problems in practice:

```nimrod
#type Uint8Array {.unchecked.} = array[0..0, uint8] # fails
type Uint8Array {.unchecked.} = array[8, uint8] # works
var packet: tuple[data: string] = (data: "foobar")
var p = cast[Uint8Array](addr packet.data[0])
```
At compile time it's still checked whether "foobar" fits into Uint8Array.

I guess this is explained by the manual's mention of

> The bounds checking done at compile time is not disabled for now, so to access s.data[C] (where C is a constant) the array's index needs needs to include C.

But then at least the error message should be improved:

    x.nim(4, 9) Error: expression cannot be casted to Uint8Array

**Comment by Araq** [comment]
An unchecked array still is not a pointer though, so why should the cast work?

**Comment by Araq** [comment]
@def- ping?

**Comment by def-** [comment]
Right, my bad.
