### ISSUE TITLE
Clarify copyright status for some files

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#2949]
Hello,

I'm trying to package this for Debian but cannot yet because of unclear licensing. Please clarify the copyright status of these files:

`lib/wrappers/libcurl.nim`: "see the curl website" is not clear enough. which particular libcurl file is this based on?

`lib/wrappers/sdl/*.nim`: These are the worst; the licensing information is very unclear.

- "Sam Lantinga" is a major copyright holder up until 2004, claiming "All rights reserved" over the "Portions created by [him]". This seems incompatible with the MPL-1.1 licensing mentioned later in the files.
- the files also say "Joint Endeavour of Delphi Innovators" without explicitly naming them as holding copyright.
- the files include changelogs that go up to 2007
- sdl_gfx.nim is completely different from the other files, mentioning neither Sam Lantinga nor the JEDI project.

`lib/wrappers/tre.nim`: - "This software is released under a BSD-style license. See the file LICENSE for details and copyright." there are several types of BSD license, please clarify.

`lib/windows/shellapi.nim`:#  Copyright (c) Microsoft Corporation. All rights reserved.

"All rights reserved" means it is not FOSS and therefore not distributable by anyone except Microsoft. But, APIs are generally thought to be not copyrightable, so I was a little surprised to see these headers on these files, that seem to just be translations of APIs. However I am not a lawyer, it would be good to get some clarification on this matter.

`tests/generics/tcan_alias_generic.nim`:## Copyright (c) 2011 FWA. All rights reserved.
`tests/generics/tcan_alias_specialised_generic.nim`:## Copyright (c) 2011 FWA. All rights reserved.
`tests/generics/tcan_inherit_generic.nim`:## Copyright (c) 2011 FWA. All rights reserved.
`tests/generics/tcan_specialise_generic.nim`:## Copyright (c) 2011 FWA. All rights reserved.
`tests/generics/tspecialised_is_equivalent.nim`:## Copyright (c) 2011 FWA. All rights reserved.

"All rights reserved" means it's not Free Software . But these files seem trivial enough that you can rewrite them or argue that it's not copyrightable and remove the headers. Again, IANAL so you should research this question yourself, or contact the authors for them to release it under a proper FOSS license.

**Comment by Varriount** [comment]
Hm.I'd like to point out that most of those files (the wrappers especially) were generated using c2nim, which preserves comments. Thus, the copyrights may not actually be valid (I'm not a lawyer, but I think the wrappers could be labeled at most as derivative works, if not plain original works).  
Disregarding recent court cases (Oracle and Google) I think most of those copyrights could be taken out. What's is usually done when a wrapper for a library is created?
