### ISSUE TITLE
"dialogs" module in stdlib requires "gtk2" from nimble

### ISSUE THREAD

**Issue by fallingduck** [nim-lang/Nim#2950]
Not much to say, can be fixed on the user's end with

    $ nimble install gtk2

But standard libraries should not require one to pull things externally. Should `dialogs` be removed from the stdlib?

**Comment by fallingduck** [comment]
As pointed out by infinity0 on IRC, `tools/nimrepl.nim` requires it as well.

**Comment by Araq** [comment]
``tools/nimrepl`` is dead as far as I can tell and indeed ``dialogs`` should be a Nimble package.

**Comment by dom96** [comment]
There is an issue which relates to this: #623

**Comment by dom96** [comment]
Dialogs now available here: https://github.com/nim-lang/dialogs
