### ISSUE TITLE
Problems with Nim Website on Mobile

### ISSUE THREAD

**Issue by sbdchd** [nim-lang/Nim#2962]
This is clearly a minor issue but when viewing the website on mobile it can be difficult to view the code examples and other items.

Maybe a more responsive design is in order?

**Comment by kirbyfan64** [comment]
Can you give a screenshot? Looks OK for me.

**Comment by sbdchd** [comment]
Here you go:
![2015-06-19 14 55 34](https://cloud.githubusercontent.com/assets/7340772/8261034/6aff0f4e-1695-11e5-83f9-7a59bce6454c.png)

**Comment by dom96** [comment]
Looks pretty good to me. Can't you simply zoom on the code examples?

**Comment by sbdchd** [comment]
Yeah you can zoom in on the code examples but I just thought their was room for improvement for mobile users visiting the site. It seems that the website should be responsive enough not to warrant zooming but maybe I am just being picky.

**Comment by kirbyfan64** [comment]
@sbdchd Maybe I'm just a bad web developer, but it can end up more difficult that you'd think to do that. You start going into columns, pixel counts, fluid widths, etc.

Of course, maybe something like [960 Grid System](http://960.gs/) or (as a lesser choice) [Skeleton](http://getskeleton.com/) would help out?

**Comment by sbdchd** [comment]
I made a basic mock up of a redesigned website [here](http://nim.narp.xyz/). 

Right now it is pretty bland, lacking the individuality the current site has, but I would say it is a start.

**Comment by reactormonk** [comment]
There's a few svgs of the flat crown somewhere you can use. I think they're liked in an issue.

**Comment by dom96** [comment]
@reactormonk https://github.com/nim-lang/assets

@sbdchd It looks interesting, it does lose a lot of the colors and character though. I don't think @Araq especially would go for it, it's nice to see you experiment though :)

**Comment by BigBoneDaddy** [comment]
@kirbyfan64 Just use Bootstrap it makes responsive easy.

**Comment by kirbyfan64** [comment]
@BigBoneDaddy If we want a bunch of CSS and fonts, 50% of which are usually never used. :)

**Comment by andreaferretti** [comment]
There is a new website now
