### ISSUE TITLE
Array ptr dereference

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2963]
Code:

```nim
var
  a = [8, 7, 3, 10, 0, 0, 0, 1]
  b = [10, 0, 0, 0 ,0 ,0 ,0, 0]
  ap = addr a
ap[] = b
echo repr(a)
```

Expected result:

    [10, 0, 0, 0 ,0 ,0 ,0, 0]

Actual result:

    [8, 7, 3, 10, 0, 0, 0, 1]

**Comment by BigBoneDaddy** [comment]
@reactormonk That is serious unexpected behavior!

**Comment by BigBoneDaddy** [comment]
@reactormonk @Araq Is there be update on this bug and it fix? It make me very concerned now about using array and pointer. How much risk to my code from this?

**Comment by Araq** [comment]
@BigBoneDaddy I don't think "dereferencing an array ptr to get a full copy" is common in Nim. We have thousands of lines of code that use 'ptr to array' in production.
