### ISSUE TITLE
Overloading a macro fails dependent on weird side-effects

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#2964]
I have a super weird problem. After a few hours of distilling a minimal reproducing problem I'm down to the following code. Basically I have an overloaded macro `call` -- one version takes one argument, the other version has an additional `untyped` argument. Despite being `{.immediate.}` this kind of overloading was working without problems at first. Suddenly it broke, with the compiler complaining `Error: in call 'call(o)' got 1, but expected 2 argument(s)`. However, the steps required to make it fail are rather dreadful (a combination of certain imports, a local proc, calling `toFloat`, and defining certain variables). If I remove any of these things it suddenly works.

```
import macros

# commenting any of these (individually!) => it compiles
import stringinterpolation
import sequtils
import math

type
  MyObject = object

# commenting this proc => it compiles
proc needed*[T](o: var MyObject) =
  discard


# this is the macro I'm actually calling
macro call[T](o: var MyObject): stmt {.immediate.} =
  result = newStmtList()

# overloaded version, commenting this => it compiles
macro call[T](o: var MyObject, va: untyped): stmt {.immediate.} =
  result = newStmtList()


# commenting this => it compiles
let asfd = 1.toFloat

# and even these two variables are required to make it fail
let x = [1,2,3]
let y = [1,2,3]

# now the actual code
var o = MyObject()
o.call()
```

If such an overloading is supposed to fail in general, it would be nice to really make it _always_ fail with a reasonable error message. If it is supposed to work though, I'm really wondering what is going on here.

**Comment by Araq** [comment]
> Despite being {.immediate.} this kind of overloading was working without problems at first.

You were lucky then. It's not supported and .immediate will be removed from the language. Sorry.

**Comment by dom96** [comment]
what. What do you mean ``{.immediate.}`` will be removed? Tons of code relies on it.

**Comment by Araq** [comment]
@dom96 There have been lots of discussions of how it can be deprecated without limiting the expressiveness of the language.

**Comment by dom96** [comment]
Yay :\
