### ISSUE TITLE
Strange OverflowError in Debug mode, nonexistent in Release mode

### ISSUE THREAD

**Issue by fallingduck** [nim-lang/Nim#2965]
The code used and output can be found in this gist: https://gist.github.com/fallingduck/41d79ab207600130b9ba

**Comment by Araq** [comment]
That is a regression, right?

**Comment by fallingduck** [comment]
Not sure. Similar description (bug fixed with -d:release) is mentioned in #2865, although the problem arose from different circumstances.

**Comment by Araq** [comment]
Btw .noSideEffect implies .gcSafe, no need to write both.

**Comment by Araq** [comment]
Not sure if that is a bug. The addition surely does overflow. Added this in line 36:

        debugecho x[3], " ", x[2]
        debugecho x[3] + x[2]

**Comment by fallingduck** [comment]
It should roll over though, should it not? It does in release mode.

**Comment by Araq** [comment]
No, the overflow error is what the spec says for signed integers. You can use +% instead to get wrap around addition for signed integers. That the release mode currently does not enforce overflow checking is unfortunate, but you really should develop in debug mode.

**Comment by fallingduck** [comment]
Alright, thanks, closing.
