### ISSUE TITLE
Trailing whitespace cleanup in a targeted manner

### ISSUE THREAD

**Issue by Perelandric** [nim-lang/Nim#2967]
Stemming from a discussion with @Araq, @dom96, @nanoant, @kirbyfan64 and @reactormonk, it seems that while there's a need/desire to clean up trailing white-spaces in `.nim` files, it can cause headache if not done in a sufficiently accommodating manner.

My suggestion is to take somewhat of a divide-and-conquer approach to the problem...

 - Contributors will list under this issue any files that ought to be "hands-off" due to potential conflicts.
 - This issue will be resolved via a series of PRs, each of which will target an orderly yet somewhat arbitrarily defined group of files.
 - Each PR will have a separate commit for every individual file in the group with its trailing white-space removed. The commits will include the filepath for clarity.
 - There will be a short period of time during which contributors may object to any of the individual commits because of conflicts not previously noted here. The objections will be excluded from the eventual merge.

It would seem this would ameliorate hopefully most of the problems arising from this issue while getting us much of the way toward the cleanup being complete. 

I'd volunteer to do the work and put together the PRs if this seems like a good idea. I'll let others decide some of the details of how long the "objection period" should last and how it should be announced.

----
*EDIT:* As noted below, this would result in far too many commits. More likely we would just give contributors the opportunity to declare "hands-off" files and then do it all at once with per project folder commits.

**Comment by kirbyfan64** [comment]
find -name \*.nim -exec sed -i {} 's/[[:space:]]*$//' \;

**Comment by nanoant** [comment]
:+1:, thank you for your involvement @Perelandric 

> This issue will be resolved via a series of PRs, each of which will target an orderly yet somewhat arbitrarily defined group of files.

I would either go for single commit fixing automatically trailing space, or one commit per each project folder, that is `compiler`, `lib`, `tests`, `doc`, `examples`. I don't think we should do separate commit per each file, this will just flood the history.

There is once advantage of having single commit, it will have some SHA that can be easily remembered.
We may also tag this SHA with `whitespace-fix` tag or similar.

But this is my opinion.

@kirbyfan64 I think we miss an argument to `find` at least here on OS X it wants one. So here's my version:

    find . -name '*.nim' -exec sed -i '' -E 's/[[:space:]]+$//' {} +

Note: using `+` instead `\;` will launch just one sed per all files (quicker), using `+` in RE instead of `*` will just match line where there is trailing whitespace, coz `*` also matches empty string.

**Comment by Perelandric** [comment]
Neither of those searches worked for me but this did: `grep --include=\*.nim -rl ./ -e "\s\+$"`

@nanoant I see your point about too many commits. Letting people flag "hands-off" files may be enough. One commit per project directory sounds good.

**Comment by dom96** [comment]
I'm still not sure about getting rid of all of the whitespace at once. What advantages does this bring versus the way we currently do things (removing whitespace only in the files that you are editing anyway)?

**Comment by Perelandric** [comment]
@dom96 Just to avoid some of the annoyances. The current way is great for convenience in that it doesn't require any extra effort, except that which may result from some conflict.

Given that you have someone (me) who's willing to spend some extra time on maintenance right now, I thought it may be worthwhile to handle as much of the safe stuff as possible all at once. Then it's done and out of the way.

If the status quo is acceptable, then stick with that.

**Comment by reactormonk** [comment]
I'm all for purges.

**Comment by kirbyfan64** [comment]
@nanoant I knew about those find and sed features, but I thought they were GNU extensions. Doesn't POSIX sed only support `*`?

**Comment by nanoant** [comment]
@kirbyfan64 `+` is available using `-E` (ERE), see POSIX ERE spec http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap09.html#tag_09_04_06, but you are right POSIX specified that `sed` should support at least `BRE`, so not all `sed` implementations may have `-E` option.

**Comment by Araq** [comment]
At this point every solution is fine with me that accomplishes that I never have to read and care about this surreal bullshit ever again. But while we're at it, also make it use consistently LF over CR-LF except for *.bat files.

**Comment by nanoant** [comment]
You may want to put following `.gitattributes` into repo:

    # ensure all text files are normalized to LF on commit
    * text=auto
    # ensure that bat files are converted to CRLF on checkout
    *.bat eol=crlf

**Comment by Perelandric** [comment]
Closing because I no longer think it's a good idea since the updates to the guidelines in `contributing.rst` seem to make it unnecessary.

If someone else sees merit in this approach, they can reopen it but I'll exclude myself from this endeavor.

**Comment by Araq** [comment]
Hu? How does contributing.rst affect this RFC?

**Comment by Perelandric** [comment]
@Araq Because it requires formatting changes to not be part of the substance of a commit that changes code. With that rule in place, the whitespaces fixes, being in a separate commit, can be ignored when reviewing cleanly dropped if needed. As such, it obviates the original impetus for this RFC.

But by all means, keep it open if you wish to continue discussing it.

**Comment by Araq** [comment]
ok ok, I am quiet now.

**Comment by dom96** [comment]
There is no way this will play nice with text editors.
