### ISSUE TITLE
nim c doesn't complain about incorrect command line parameters

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2972]
Sample:

```
nim -d:release -mmcu=atmega328 --listCmd -f c blink.nim
```

the `-mmcu=atmega328` option is incorrect, but the compiler doesn't
complain, and also doesn't produce an output file.

**Comment by Araq** [comment]
Actually that's a (mis)feature. key-value pairs separated by '=' are inserted into some configuration voodoo.

**Comment by andreaferretti** [comment]
Just noticing that if you put this in a .cfg file, you actually get the error `Error: invalid command line option: '--mmcu'`

**Comment by jyapayne** [comment]
This can be closed. The issue is that @reactormonk put only one dash in `-mmcu` which translates to `-m -m -c -u`. `-u` is the `--undef` option, which then undefines `atmega328`. I'm not sure what `-m` does, but it appears to be a valid option and `-c` is `--compileOnly`. So, nothing wrong here.
