### ISSUE TITLE
Compiling with winUnicode gives an error message

### ISSUE THREAD

**Issue by axbender** [nim-lang/Nim#2980]
Using the oldwinapi package, compiling with ``-d:winUnicode`` results in the following error message:
```...\oldwinapi-1.0.0\windows.nim(320, 14) Error: undeclared identifier: 'widechar'```

**Comment by Araq** [comment]
Don't use that. Use the *W versions of the procs instead. Also oldwinapi has its own bug tracker. ;-)

**Comment by axbender** [comment]
Shouldn't Nim do that implicitly when I define winUnicode? What is the switch good for then?

**Comment by Araq** [comment]
I agree it's a bug but move it to oldwinapi please.

**Comment by axbender** [comment]
Thanks. Moved.
