### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2987]
This may be a duplicate or previously known. EDIT: I did search, just couldn't find anything)

Some links to source in the documentation (e.g. for [readLine](https://github.com/Araq/Nim/tree/master/lib/system%5Csysio.nim#L191)) use a backslash `\` rather than the `/` for HTML. At least on Firefox, it's sending me to an invalid page. Switching slash direction fixes it.

**Comment by Araq** [comment]
Well please list aynthing you encountered. I cannot effectively search for "backslash within doc comments". Actually ... I can. Hrm.

**Comment by apense** [comment]
It seems to happen when other files are included. like `include system/atomics.nim`

https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L2725
https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L2683

**Comment by Araq** [comment]
Pretty sure this has been fixed by now.
