### ISSUE TITLE
Compilation broken on windows

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2996]
Stems from PR #2976 . Several references involve the `posix` module directly, which obviously doesn't work on Windows. [See here for an example](https://github.com/nim-lang/Nim/blob/devel/lib/pure/rawsockets.nim#L198). Examples of fixes are found in `sockets.nim` ([see here](https://github.com/nim-lang/Nim/blob/devel/lib/pure/sockets.nim#L457)). 
Import of rawsockets.nim with a working installation also fails for the same reasons

**Comment by Varriount** [comment]
Are you sure about this? The [Windows Buildbots](http://buildbot.nim-lang.org) seem to be working fine.

**Comment by apense** [comment]
Well it would have been since about two hours ago, I think. I'm on Win64. The buildbots look like they last built on the 15th. I removed Nim from my path, fetched a fresh clone from devel, and still have
compilation problems stemming from rawsockets

**Comment by Varriount** [comment]
@apense Ah, my bad. It seems that some buildbot settings didn't get changed when the move from Araq/Nim to nim-lang/Nim happened, so the buildbot wasn't building anything.
