### ISSUE TITLE
Inconsistent results passing a uint to int: literals vs variables

### ISSUE THREAD

**Issue by benekastah** [nim-lang/Nim#3004]
Example `nim i` session:

```
>>> int(3'u)
3
>>> var x = 3'u
>>> int(x)
4526163736
```

**Comment by dom96** [comment]
Pretty sure that ``nim i`` is deprecated. Does this also occur outside it?

**Comment by benekastah** [comment]
Ah, looks like it works outside of `nim i`. I guess I'll stop using it then :)
