### ISSUE TITLE
nim doc2 fails in Mac OS X due to system.nim (possibly related to #1898)

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/Nim#3005]
Using the latest version of Nim from devel branch (0.11.3, currently 17f852c769078f87e2889d5123f66c3bb6c58a4a), I have the following error when running `koch web`:
```lib/system.nim(284, 53) Error: '`' expected```

To test this further, I tried using `nim doc2` on an unrelated file:
```
sloanesimmons@localhost ~/D/n/r/helpers>nim doc2 non_guid.nim
...
Hint: used config file '/Users/sloanesimmons/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/sloanesimmons/Nim/config/nimdoc.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(284, 53) Error: '`' expected
Error: unhandled exception: '`' expected [ERecoverableError]
```

I don't see a problem with this part of system.nim (or at least, nothing obvious):
```
...
279   ## Checks for equality between two `cstring` variables
280 proc `==` *(x, y: char): bool {.magic: EqCh, noSideEffect.}
281   ## Checks for equality between two `char` variables
282 proc `==` *(x, y: bool): bool {.magic: EqB, noSideEffect.}
283   ## Checks for equality between two `bool` variables
284 proc `==` *[T](x, y: set[T]): bool {.magic: EqSet, noSideEffect.}
...
```
running on Mac OS X 10.10.3

**Comment by Araq** [comment]
Fixed via https://github.com/nim-lang/Nim/pull/3013 ?

**Comment by singularperturbation** [comment]
I can confirm - `nim doc2` is fixed.  `koch web` still fails on Mac OS X because of an issue with:

```
lib/pure/rawsockets.nim(45, 12) Error: cannot export: SO_NOSIGPIPE
```

but I was able to work around that (fix in a separate PR).  It looks like there was a conditional import of `posix` that failed to be done if using nimdoc:

```nimrod
const useWinVersion = defined(Windows) or defined(nimdoc)
```
