### ISSUE TITLE
Nim does not complain when mixing generic params and malformed var assignment

### ISSUE THREAD

**Issue by Abrasax-** [nim-lang/Nim#3006]
This code can be compiled without any alert:
```Nim
proc bar(a, b: int) = discard
proc foo[T](foos: openArray[T]) = 
  let a: 4 
  bar (a: 1, b : 2)
```
When you actually call it, you get the following error:
```Nim
foo([1, 2, 3])
#test.nim(6, 4) template/generic inst
#test.nim(3, 10) Error: type expected
```
I have discovered the  `template/generic inst` statement thanks to copy it here, because with colors it was completely black.

Everything works as expected when you replace the signature to `proc foo(foos: openArray[int])`
* * *
nim -v
```
Nim Compiler Version 0.11.3 (2015-06-27) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 17f852c769078f87e2889d5123f66c3bb6c58a4a
```
git branch: `* devel`
command: `nim c -r test.nim`

**Comment by Abrasax-** [comment]
The following snippet breaks `nim check`:
```Nim
proc foo[T](foos: openArray[T]) = 
  let a: 4
  bar (a: 1, b : 2)
  
foo([1, 2, 3])
#############
Traceback (most recent call last)
nim.nim(97)              nim
nim.nim(61)              handleCmdLine
main.nim(330)            mainCommand
main.nim(46)             commandCheck
modules.nim(206)         compileProject
modules.nim(154)         compileModule
passes.nim(193)          processModule
passes.nim(137)          processTopLevelStmt
sem.nim(455)             myProcess
sem.nim(424)             semStmtAndGenerateGenerics
semstmts.nim(1410)       semStmt
semexprs.nim(906)        semExprNoType
semexprs.nim(2131)       semExpr
semexprs.nim(889)        semDirectOp
semexprs.nim(759)        semOverloadedCallAnalyseEffects
semcall.nim(329)         semOverloadedCall
semcall.nim(309)         semResolvedCall
seminst.nim(258)         generateInstance
seminst.nim(118)         instantiateBody
transf.nim(795)          transformBody
sempass2.nim(865)        trackProc
sempass2.nim(772)        track
sempass2.nim(772)        track
sempass2.nim(755)        track
system.nim(2353)         sysFatal
Error: unhandled exception: sym is not accessible [FieldError]
```

I dont know if i should report this as a different issue

**Comment by BigBoneDaddy** [comment]
@Abrasax- I think separate issue for separate problem is good idea. Traceability and all that!

**Comment by Abrasax-** [comment]
It is not that clear for me, i discovered this bug when `nim check` crashed, so in my opinion they share the same root problem.

**Comment by dom96** [comment]
@BigBoneDaddy It's the same code sample, no need for a separate issue.

**Comment by Araq** [comment]
> I have discovered the template/generic inst statement thanks to copy it here, because with colors it was completely black

Yeah I noticed this too. Bad regression.

**Comment by Araq** [comment]
> This code can be compiled without any alert:

Yeah generics use duck-typing, like in C++. No, I don't like it either anymore. But fixing it has to wait for Nim 2.0.

**Comment by Araq** [comment]
Fixed the check bug by some other commit, fixed the highlighting problems.
