### ISSUE TITLE
Add variable shadowing warning to procs

### ISSUE THREAD

**Issue by Abrasax-** [nim-lang/Nim#3009]
The following snippet will compile without a warning, which in my opinion is not desired (first hand experience):
```Nim
proc foo(x, y: int) =
  for x in 0..1:
    for y in 0..1:
      echo x, y
```
In case such warning actually exists, it should be turned by default
Related to #2677
* * *
nim -v
```
Nim Compiler Version 0.11.3 (2015-06-27) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 17f852c769078f87e2889d5123f66c3bb6c58a4a
```

**Comment by reactormonk** [comment]
Help me a bit, what's the problem here?

**Comment by Abrasax-** [comment]
@reactormonk when you compile this:
```Nim
proc foo: int =
  let result = 1
```
You get this warning: `test.nim(2, 7) Warning: Special variable 'result' is shadowed. [ResultShadowed]`
I expect a similar warning when a declaration inside a proc has the same identifier as a proc param. In my example, i defined two times x and y. I had this problem when i wrote:
```Nim
proc insert*(img1: var IMG, img2: IMG, ox, oy: int) =
  for y in 0..<img2.h:
    for x in 0..<img2.w:
      img1[ox + x, oy + y] = img2[x, y]
```
Instead of `ox` and `oy` i wrote `x` and `y` both in the proc signature and img1 indexing. At first, i didnt know what was wrong. With  `test.nim(X, X) Warning: Param variable 'x' is shadowed. [ParamShadowed]` i could have spotted the mistake at the moment.

**Comment by Araq** [comment]
Well but 'let foo = foo-3 # no chance to use the wrong outdated 'foo'' is an idiom in Nim.

**Comment by Abrasax-** [comment]
That's a harmful idiom then. Shadowing will impose more problems than benefits.

**Comment by Araq** [comment]
It's always been a good idiom for me, preventing more than one very hard to detect bug. Don't be so quick with your judgements.

**Comment by Abrasax-** [comment]
I don't care anymore and don't want it as a feature. But i think manual/tutorials should reference this in case they don't.
