### ISSUE TITLE
Graphics should probably use sdl2?

### ISSUE THREAD

**Issue by Angluca** [nim-lang/Nim#3010]
Hi, Maybe sdl2 is better than sdl1?

**Comment by Araq** [comment]
Yeah please make it happen.

**Comment by Araq** [comment]
Hrm? It is a valid issue.

**Comment by Angluca** [comment]
Oh, Like it ! Thanks.

**Comment by dom96** [comment]
Shouldn't the graphics module be moved to nimble?

**Comment by Araq** [comment]
@dom96 yes, but it should be based on SDL 2 cause that has a better license.

**Comment by dom96** [comment]
Sure.

**Comment by BigBoneDaddy** [comment]
@Angluca You volunteer do this work?

**Comment by Angluca** [comment]
@BigBoneDaddy 
I really want to write, but I'm still learning Nim, ready to learn 2 months, otherwise I'm afraid I wrote bad code, because so many things still do not understand.
I contacted a few days Nim

**Comment by BigBoneDaddy** [comment]
@Angluca Fear not for in time we all become better providers and makers of Nim source codes. It is the power of Nim and experiences!

**Comment by dom96** [comment]
Closing because ``graphics`` module was moved out of stdlib.
