### ISSUE TITLE
inheritable placement not symmetric between object and ref object

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#3012]
In the following snippet, 3 out of 4 placements work for inheritable, but one oddly does not, causing a surprising asymmetry between `object` and `ref object`:

```
type
  A {.inheritable.} = object
  B = ref object {. inheritable .}
  C {.inheritable.} = ref object
  D = object {.inheritable.}

type
  AA = ref object of A
  BB = ref object of B
  # Error: inheritance only works with non-final objects
  # CC = ref object of C
  DD = ref object of D
```

**Comment by Araq** [comment]
Not *that* surprising as C is an "inheritable **ref** object"...

**Comment by apense** [comment]
Is this related to #2926 at all?

**Comment by andreaferretti** [comment]
Seems to compile with latest nim (ca4b971bc81b2e751e0388d80896fde7079b1679)
