### ISSUE TITLE
Compilation error on modules with same names but different locations

### ISSUE THREAD

**Issue by SPY** [nim-lang/Nim#3017]
For example i wonna write tests for modules in project directory
I create ditectory "test" and put files with same names as testable modules
For example

foo.nim

``` nimble
const Num* = 42
proc add*(x, y: int): int =
  x + y
```

test/foo.nim

``` nimble
import "../foo"
const x = 15
assert add(x, Num) == 57
```

Then i compile test/foo.nim with follow command:

```
nim c test/foo.nim
```

and got next error

```
Hint: system [Processing]
Hint: foo [Processing]
Hint: foo [Processing]
CC: foo
CC: foo
[Linking]
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed
```

**Comment by Araq** [comment]
use different names for different modules.

**Comment by Varriount** [comment]
Hm. What would the "proper" error message be here?

**Comment by Araq** [comment]
"Araq hates directories and so should you."

**Comment by Varriount** [comment]
The main problem with this is that the imported module and the importing module both have the same name, right? 
What about ignoring this, printing a warning, and let the name of the importing module shadow the imported module?

@araq I know you hate things like this, but they will happen in everyday usage (say, with common module names such as "utils").

**Comment by Araq** [comment]
@Varriount It is supported when you have different Nimble packages, so every Nimble package can have its own "utils" module. But within a single Nimble package it's good to enforce the restriction.

**Comment by Varriount** [comment]
How does nimble do that?

**Comment by Araq** [comment]
The compiler looks if there is a .nimble file in the directory and if so, the module is attached to its package. So Nimble has little to do with it.

**Comment by Araq** [comment]
Now produces a decent error message.
