### ISSUE TITLE
Please make expandSymlink() work in Windows!

### ISSUE THREAD

**Issue by axbender** [nim-lang/Nim#3023]
Please make expandSymlink() work in Windows!

**Comment by BigBoneDaddy** [comment]
@axbender What is expected behavior? Maybe full spec needed! It is most confusing situation under Windows https://en.wikipedia.org/wiki/Symbolic_link#Microsoft_Windows

**Comment by dom96** [comment]
Yeah, symbolic links are very rarely used on Windows. This is therefore low priority.

**Comment by axbender** [comment]
@BigOneDaddy: Do as the docs say: display the target of the symlink (or hardlink for that matter). I'd suggest to use e.g. the GetFinalPathNameByHandle() API function in the first place (you could also use CreateFile() on the file to retrieve advanced info => see e.g. https://msdn.microsoft.com/en-us/library/aa366789(VS.85).aspx).

This isn't a big issue, but when it comes to writing e.g. a DIR replacement, a working expandSymlink() procedure would be quite helpful...

**Comment by Araq** [comment]
PRs are welcome but nobody is working on this.
