### ISSUE TITLE
FreeBSD 10.1 failed build

### ISSUE THREAD

**Issue by AnyCPU** [nim-lang/Nim#3027]
When building from sources using instructions after `koch boot -d:release` I got:

CC: compiler_passaux
CC: compiler_depends
CC: compiler_docgen2
CC: compiler_service
CC: stdlib_net
CC: stdlib_rawsockets
CC: compiler_modules
CC: compiler_nodejs
[Linking]
clang: error: no such file or directory: 'users/dev/proj/Nim/compiler/nimcache/compiler_jsgen.o'
clang: error: no such file or directory: 'users/dev/proj/Nim/compiler/nimcache/compiler_cgen.o'
Error: execution of an external program failed
FAILURE

I checked and these files exist.

// FreeBSD 10.1, clang 3.4.1

**Comment by Araq** [comment]
Compile with --parallelBuild:1

**Comment by BigBoneDaddy** [comment]
@AnyCPU Can you give the feedback?

**Comment by AnyCPU** [comment]
Thank you, all ok)

**Comment by Araq** [comment]
@AnyCPU This was fixed before and should work with both Nim devel and Nim 0.11.2 out of the box. What version do you use?

**Comment by AnyCPU** [comment]
@Araq Nim was compiled from git master.

`nim --version` output:

>Nim Compiler Version 0.11.3 (2015-06-29) [FreeBSD: amd64]
>Copyright (c) 2006-2015 by Andreas Rumpf
>
>git hash: 2f9ad55fbdaea5e9746e868a765c2a154a983f6f
>active boot switches: -d:release

FreeBSD
>FreeBSD earth 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC >2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

Clang
>FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
>Target: x86_64-unknown-freebsd10.1
>Thread model: posix

**Comment by Araq** [comment]
This has been fixed.
