### ISSUE TITLE
Duplication of proc documentation with `nim doc`

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#3034]
`nim doc2` works fine, but `nim doc ...` in the following creates duplicate entries for forward declarations

``` nim
proc hello*(x: int): string
  # documentation comes later

proc someother*(): string =
  result = hello(3)

proc hello*(x: int): string =
  ## documentation here
  result = "hello: " & $x
```

documents 3 procs. `nim doc2` just does the two properly.  At some point, it seems like this was fixed (see #350). Guess it changed at some point.

**Comment by BigBoneDaddy** [comment]
@apense Can you backtrace the git log and find the revs that regressioned?

**Comment by apense** [comment]
Not sure how to do that

**Comment by reactormonk** [comment]
It's called bisecting. For scripting, you should be able to use `git bisect run ./koch temp doc` - maybe.

**Comment by Araq** [comment]
Workaround:

```
proc hello*(x: int): string
  ## documentation here

proc someother*(): string =
  result = hello(3)

proc hello(x: int): string =
  # no documentation here and no export marker either
  result = "hello: " & $x
```

**Comment by apense** [comment]
I can `git bisect` back to e7bb37d. After that, the magic changed. Should I regenerate from csources?
It still has the `doc` issues at e7bb37d

**Comment by Araq** [comment]
``nim doc`` is now ``nim doc2``, ``nim doc0`` is deprecated. Closing.
