### ISSUE TITLE
readFile may read past the EOF

### ISSUE THREAD

**Issue by xyz32** [nim-lang/Nim#3039]
In case of a sysfs file (eg: Beaglebone black cape slots definition) the file size at OS level is reported much bigger then the actual size, therefore "rawFileSize" will return more bytes that the file actually has. The reading process will then try to read past the EOF.

For example: readFile("/sys/devices/bone_capemgr.9/slots") will fail with an IOError
```
sysio.nim(187)           readAll
sysio.nim(176)           readAllFile
system.nim(2280)         raiseEIO
Error: unhandled exception: error while reading from file [IOError]
```

**Comment by reactormonk** [comment]
What would be the correct way to read this file?

**Comment by xyz32** [comment]
As a quick fix on my code I am doing this:
```
proc readFile*(fileName: string): string =
  var tFile = open(fileName, fmRead)
  result = ""
  try:
    while true:    
      result = result & tFile.readLine() & "\n"
  except IOError: discard
  finally:
    tFile.close()
```
Not the pest idea as it uses exceptions as part of the work-flow.

There is also the [memfiles](http://nim-lang.org/docs/memfiles.html) but I did not have the chance play with it yet.

**Comment by Varriount** [comment]
Isn't this more of a flaw in the OS?

**Comment by Araq** [comment]
> file size at OS level is reported much bigger then the actual size

So it's an OS bug.

**Comment by Varriount** [comment]
@xyz32 To clarify, this is probably better reported to the maintainers of the BeagleBone distribution. It shouldn't be the responsibility of a programming language development team to work around distribution-specific bugs.

That being said, doo any other languages (Python, Java) handle the situation correctly?

**Comment by xyz32** [comment]
@Araq Looks like this is a limitation of the "ftell" call in case "The file descriptor underlying stream is associated with a pipe, FIFO, or socket" http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html#tag_16_177

Google suggests the use of stat() instead.

Thank you.

**Comment by Araq** [comment]
@xyz32 from the same page: "Otherwise, ftell() and ftello() shall return -1, and set errno to indicate the error."

**Comment by Varriount** [comment]
So, the correct fix is to use the stat family of functions?

**Comment by Araq** [comment]
@Varriount No, just fall back to the streaming 'while' loop plus reallocations if the file's length cannot be determined.

**Comment by xyz32** [comment]
Looks like I can not amend a pull request. I will remake it.

**Comment by xyz32** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/3239
