### ISSUE TITLE
Feature Request: IDNA support

### ISSUE THREAD

**Issue by takaomag** [nim-lang/Nim#3045]
To encode, decode and check Internationalized Domain Name, it would be nice if stdlib has IDNA(Stringprep/Punycode) library like [golang.org/x/net/idna](https://godoc.org/golang.org/x/net/idna) and [Python encodings.idna](https://docs.python.org/3.5/library/codecs.html#module-encodings.idna).
Wrapping [libidn](http://www.gnu.org/software/libidn/) may be one suitable choice on Linux.

**Comment by Varriount** [comment]
If this is to be in the standard library, it's really preferable that it be implemented in pure Nim, so that additional dependencies aren't added.

**Comment by BigBoneDaddy** [comment]
@takaomag Does GNU libidn have infectious GPL style license? Nim use free as in freedom MIT license!

**Comment by apense** [comment]
Here's a gist that does the encoding: https://gist.github.com/apense/a2e7fbddfbd0f3561b82
I just translated it from the Go punycode.go file that you linked to. Seems to work, but it's not great style. Do with it what you will.

**Comment by apense** [comment]
Updated the [gist](https://gist.github.com/apense/a2e7fbddfbd0f3561b82). It's based of of Libidn (both the C# and Java implementations). Tried to document what's happening It can be made a lot cleaner, but it works. Personally, I think it's not good enough for stdlib (yet, at least)

**Comment by BigBoneDaddy** [comment]
@apense If it copy from other code what is licensing of it? Is original license of original source MIT license?

**Comment by apense** [comment]
@BigBoneDaddy well the Punycode algorithm is based off an RFC, so it should be public license. I can rename some of the functions. Really, it's a bit different because Nim differentiates between len() and runelen()
