### ISSUE TITLE
Why -O3?

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3050]
I noticed that nim uses `-O3` optimization flag for gcc/clang. It makes large executables and may lead to bugs.

See https://wiki.gentoo.org/wiki/GCC_optimization

> -O3: the highest level of optimization possible. It enables optimizations that are expensive in terms of compile time and memory usage. Compiling with -O3 is not a guaranteed way to improve performance, and in fact, in many cases, can slow down a system due to larger binaries and increased memory usage. -O3 is also known to break several packages. Using -O3 is not recommended.

Most Linux distributions prefer `-O2` over `-O3`.

Furthermore gcc allows to mark some functions with `hot` attribute (if they are really "hot") to optimize them more:

> The hot attribute on a function is used to inform the compiler that the function is a hot spot of the compiled program. The function is optimized more aggressively and on many targets it is placed into a special subsection of the text section so all hot functions appear close together, improving locality.

**Comment by Araq** [comment]
When I did the benchmarking which admittedly was a long time ago, -O3 produced the fastest code for the compiler.

**Comment by scriptum** [comment]
If -O3 helps much:

* check compiler adds `static` keyword for functions that shouldn't be exported
* use inline for hot and small functions

P.S. Seems that nim doesn't add static keyword into generated code, but IIUC only *-functions are exported?

>If a declared symbol is marked with an asterisk it is exported from the current module:

**Comment by kirbyfan64** [comment]
I have to agree. GCC -O3 has a tendency to break stuff; I've heard of code where the loop unrolling caused segfaults. Clang can do that, too, but I've never had it as bad.

**Comment by Varriount** [comment]
Has this ever been a problem with Nim though?

**Comment by nanoant** [comment]
Only problem I can see is what's the impact on compilation time. If the minimal performance improvement, but huge compilation time penalty I think we should move to `-O2`.

**Comment by scriptum** [comment]
> Has this ever been a problem with Nim though?

 I see several problems:
* using unsafe optimizations (this is not suitable for most Linux-distros and maintainers cannot change compilation flags - see #2128)
* -O3 may appear much **slower** than -O2 just because of unrolling
* slow compilation time

I tested this: https://github.com/logicchains/LPATHBench/blob/master/nim.nim with gcc 4.4
* -O2: 950 ms
* -O3: 1660 ms (!!!)

Just try and compare. gcc 4.9.2 - same -O3 is slower.

So increasing benchmarks by 10% it can ruin some applications and loose more than 50% of speed.

**Comment by def-** [comment]
> Just try and compare.

Can't confirm, -O3 is slightly faster for me in that benchmark with GCC 5.1.

**Comment by scriptum** [comment]
> Can't confirm, -O3 is slightly faster for me in that benchmark with GCC 5.1.

Now is need for all users to install gcc5 :smile: I believe optimizer in gcc5 is much better.

clang shows similar results with O2 or O3 (and it even 5% faster than gcc version).

`-finline-functions` option is makes executable slow with `-O3`.

**Comment by Araq** [comment]
> P.S. Seems that nim doesn't add static keyword into generated code, but IIUC only *-functions are exported?

Generating 'static' is not trivial nor that useful when you enable global program optimizations.

**Comment by nanoant** [comment]
@def-  Compiling `csources` single threaded using GCC 5.1 with `-O3` takes 51 seconds, with `-O2` takes 38 seconds. This makes 35% penalty for using `-O3` comparing to `-O2`, which is quite a lot. Can you tell me what is the difference in performance?

Also one thing that really worries me is that we use `-ffast-math` just like that without any hesitation.

> This option is not turned on by any -O option besides -Ofast since it can result in incorrect output for programs that depend on an exact implementation of IEEE or ISO rules/specifications for math
           functions. It may, however, yield faster code for programs that do not require the guarantees of these specifications.

This may yield to some invalid math results comparing to other compilers that never use `-ffast-math` by default.

Do we really want that?

**Comment by scriptum** [comment]
> Generating 'static' is not trivial nor that useful when you enable global program optimizations.

A dirty try:

https://github.com/scriptum/Nim/commit/7b4c0c7f464c8c56bafa98ef5453eaaa4ad9c4e4

It adds static for *several* functions (seems safe to me) but discovered some functions that aren't exported but should be (some of them are used through inlines). And there is no compile time check for that - only gcc error appears if function not exported.

Result: less binary size, some tests may run faster (C compiler inlines static functions).

E.g. nim binary size (stripped):
* without patch: 1604496
* with patch: 1588112
Aporia (not stripped - stripped):
* without patch: 644638 - 518976
* with patch: 637618 - 514872

**Comment by def-** [comment]
If anyone wants to benchmark, you can use this and the links at the bottom: https://github.com/def-/nim-benchmarksgame

The performance of a few popular applications would also be interesting, like the Nim compiler itself or https://github.com/def-/nimes .

**Comment by scriptum** [comment]
In #3084 `-O3` doubles performance. Looks like something should be inlined in Nim stdlib.

**Comment by narimiran** [comment]
Is there any newer discussion about changing optimization flag?

If not, can this be closed?
