### ISSUE TITLE
Producing Unicode with Nim doc

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#3056]
I think I know _why_ this happens, but when you have something like

``` nim
const München* = "München"
```

in the `consts` section of the generate HTML, you get

``` nim
München* = "M\xC3\xBCnchen"
```

In that case, it's pretty obvious what the intended string is. However, something like [a constants file I have](https://github.com/apense/nimfuzz/blob/master/constants.nim) has

``` nim
InternationalTlds* = [
    "бел","қаз","мон","мкд","рф","срб","укр",
    "الجزائر","مصر","بھارت","ایران","الاردن","فلسطين","پاکستان","قطر",
    "السعودية","سوريا","تونس","امارات","عمان","مليسيا","المغرب","سودان",
    "اليمن",
    "বাংলা","ভাৰত","ভারত","भारत","భారత్","ભારત","ਭਾਰਤ","ଭାରତ",
    "இந்தியா","ලංකා","இலங்கை","ไทย","சிங்கப்பூர்",
    "中国","中國","香港","台灣","台湾","新加坡","澳門","澳门",
    "გე","한국","հայ",
  ]
```

The generated HTML is 

``` nim
InternationalTlds = ["\xD0\xB1\xD0\xB5\xD0\xBB", "\xD2\x9B\xD0\xB0\xD0\xB7", 
                     "\xD0\xBC\xD0\xBE\xD0\xBD", "\xD0\xBC\xD0\xBA\xD0\xB4", 
                     "\xD1\x80\xD1\x84", "\xD1\x81\xD1\x80\xD0\xB1", 
                     "\xD1\x83\xD0\xBA\xD1\x80", "\xD8\xA7\xD9\x84\xD8\xAC\xD8\xB2\xD8\xA7\xD8\xA6\xD8\xB1", 
                     "\xD9\x85\xD8\xB5\xD8\xB1", 
[and so on...]
```

Would there be a way to plop consts (at least simple strings) directly into the HTML as Unicode?

EDIT: You can see the generated HTML in its full glory [here](http://apense.github.io/nimfuzz/nimfuzz.html#InternationalTlds)

**Comment by apense** [comment]
Update: It works fine with triple quotes, and raw string literals keep the values in there, too. Maybe we could just apply that processing (to pure strings, at least)

**Comment by Yardanico** [comment]
For anyone in the future: the issue here is that https://github.com/nim-lang/Nim/blob/devel/compiler/renderer.nim#L183 doesn't handle unicode
