### ISSUE TITLE
Error during compilation with cpp option on FreeBSD 

### ISSUE THREAD

**Issue by filcuc** [nim-lang/Nim#3059]
Nim output the following error:
```
clang++ -c  -w  -I/usr/home/filippo/Desktop/Nim/lib -o /usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.o /usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.cpp
/usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.cpp:737:9: error: assigning to 'NI' (aka 'long long') from incompatible
      type 'char *(int, int)'
        result = timezone;
```
Maybe the same error appears on linux i didn't test it it there yet

I tested it with both today Nim git snapshot and Nim 0.11.2. Same error.

**Comment by reactormonk** [comment]
Code plz.

**Comment by filcuc** [comment]
I think that the code doesn't matter since the error comes from a file generate from the Nim standard library. The code however is my NimQml HelloWorld example. It is already referenced in this issue

**Comment by Varriount** [comment]
How old is your Nim config file? Additions were made some time ago to fix C compiler arguments.

**Comment by filcuc** [comment]
Well it cannot be old, since i installed the freebsd VM yestarday and built nim from source. I will try to reproduce it with a simpler example. However the problem comes with the cpp compilation. So i don't get whats the matter with c arguments (@varriount)

**Comment by Xe** [comment]
Without a code snippet that reproduces the problem, support is going to be difficult.

**Comment by filcuc** [comment]
The following snippet shows the error

```Nim
import tables

if isMainModule:
  echo "Hello World"
```

For reproducing:
- Install on a VM PC-BSD 10.1.2 
- Build nim from git
- Compile the previous snippet with 
```
nim cpp snippet.nim
```

**Comment by filcuc** [comment]
clang version is 3.6.1

**Comment by filcuc** [comment]
@Varriount @reactormonk hope it helps

**Comment by filcuc** [comment]
![snapshot5](https://cloud.githubusercontent.com/assets/7158691/8533911/73414ed2-2438-11e5-803a-f87e256919a0.png)

**Comment by kirbyfan64** [comment]
AHA!

In `times.nim`, line 31:

```nim
timezone {.importc, header: "<time.h>".}: int
```

But, on BSD systems, [`timezone` is a function](http://www.unix.com/man-page/freebsd/3/timezone/).

**Comment by kirbyfan64** [comment]
Also, note [this](https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/libexec/bootpd/tzone.c#L10):

```c
/* XXX - Is this really SunOS specific? -gwr */
/* This is in <time.h> but only visible if (__STDC__ == 1). */
extern long timezone;
```

**Comment by filcuc** [comment]
TBH i still haven't found a workaround for this issue

**Comment by AnyCPU** [comment]
Hello guys,
It's possible to eliminate next lines from `times.nim`
```nim
when not defined(JS):
  var
    timezone {.importc, header: "<time.h>".}: int
    tzname {.importc, header: "<time.h>" .}: array[0..1, cstring]
```
to follow recommendation from `http://www.unix.com/man-page/freebsd/3/ctime/`
```
Use of the external variable tzname is discouraged; the tm_zone entry in the tm structure is
     preferred.
```
and just use `struct tm` specific code?
Thanks)

**Comment by Araq** [comment]
@filcuc can you look into this again? I got no BSD to test on.

**Comment by filcuc** [comment]
Sure
Il 04/apr/2016 11:54, "Andreas Rumpf" <notifications@github.com> ha scritto:

**Comment by kirbyfan64** [comment]
Does defining `__STDC__` work?

**Comment by filcuc** [comment]
@Araq same error with latest devel
![screenshot_20160406_000438](https://cloud.githubusercontent.com/assets/7158691/14299604/bec57db2-fb8b-11e5-92c9-4f12922f5451.png)

**Comment by filcuc** [comment]
@kirbyfan64 __STDC__ seems to not work
![screenshot_20160406_001501](https://cloud.githubusercontent.com/assets/7158691/14299866/22d293c0-fb8d-11e5-8b9d-8e178b2ea9cf.png)

**Comment by reactormonk** [comment]
@filcuc Please use text pasties if possible because then they're searchable.

**Comment by filcuc** [comment]
@reactormonk i agree but in this case there isn't anything to be searched that has not been already written
