### ISSUE TITLE
Incorrect 'not all cases are covered' when using enums with nonconsecutive items

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3060]
This:

```
type DbusTypeChar* = enum
  dtArray = 'a',
  dtBool = 'b',
  dtStruct = 'r'

type DbusType* = object
  case kind*: DbusTypeChar
  of dtBool:
    discard
  of dtArray:
    itemType*: int
  of dtStruct:
    keyType*: int
    valueType*: int
```

produces compile error:

```
a.nim(7, 3) Error: not all cases are covered
```

While this works:

```
type DbusTypeChar* = enum
  dtArray = 'a',
  dtBool = 'b',
  dtStruct = 'c'

type DbusType* = object
  case kind*: DbusTypeChar
  of dtBool:
    discard
  of dtArray:
    itemType*: int
  of dtStruct:
    keyType*: int
    valueType*: int
```

(tested on 0.11.3 and devel)

**Comment by Perelandric** [comment]
According to the manual on *enumeration types*...

>An explicit ordered enum can have holes... However, it is then not an ordinal anymore,

Then under *case statements*...

>For non ordinal types it is not possible to list every possible value and so these always require an else part.

So I'm pretty sure this is correct behavior according to the manual. 

It does seem like non-ordinals of this type could be handled, unlike strings; it would be useful.

**Comment by zielmicha** [comment]
Or maybe the error message should be something like "case without else on non-ordinal". I've spent some time looking for values I've missed.

**Comment by Varriount** [comment]
Perhaps the error message should be modified to "not all cases are covered for non-ordinal type 'DbusTypeChar'"?

**Comment by exetoc** [comment]
I do not approve of this behavior for enums, because it means you can't enforce the case statement to be exhaustive. Exhaustiveness *and* an 'else' block can be useful too for enums when parsing buffer data.

**Comment by andreaferretti** [comment]
The error has changed to `Error: selector must be of an ordinal type`.

That said, I am not sure why an exhaustiveness check cannot be performed on a non ordinal enum - the possible values are certainly known at compile time in any case

**Comment by Araq** [comment]
@andreaferretti That's a different regression, working on it...

**Comment by andreaferretti** [comment]
The error has changed to `Error: low(kind) must be 0 for discriminant`
