### ISSUE TITLE
Try-Except block not working correctly with ref object property access

### ISSUE THREAD

**Issue by Abrasax-** [nim-lang/Nim#3065]
The following snippet works:
```Nim
type Foo = ref object
  bar: array[10, int]
  
let f     = Foo()
f.bar[0]  = 777
echo f.bar[0]
```
Now, if f.bar access happens inside a try-except block like this one ...:
```Nim
type Foo = ref object
  bar: array[10, int]
  
let f = Foo() #let or var, does not matter

try:
  f.bar[0] = 777
except:
  echo "Something is wrong"
finally:
  echo "finally " & getCurrentExceptionMsg()
```
This is going to be the output: `finally`
* * *
nim -v
```Nim
Nim Compiler Version 0.11.3 (2015-07-05) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 1ad729ee3b4738cffcbf0009e8849cb57b729e91
```
git branch: `* devel`
command: `nim c -r test.nim`

**Comment by Perelandric** [comment]
What was your expected output? Seems correct to me.

**Comment by Abrasax-** [comment]
Whoops, you are right Perlandric. I dont know exactly what was wrong here, but this code works well. I'll reopen if i found out what was the issue.
