### ISSUE TITLE
Generic object as seq type causes crash

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/Nim#3069]
The following line of code causes a crash on the latest from devel branch:

``` nim
var x: seq[object] = @[]
```

Stack trace:

```
var x: seq[object] = @[]
Error: internal error: getUniqueType
Traceback (most recent call last)
nim.nim(97)              nim
nim.nim(61)              handleCmdLine
main.nim(252)            mainCommand
main.nim(63)             commandCompileToC
modules.nim(206)         compileProject
modules.nim(154)         compileModule
passes.nim(193)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1217)           myProcess
ccgstmts.nim(1113)       genStmts
ccgexprs.nim(2067)       expr
ccgstmts.nim(1113)       genStmts
ccgexprs.nim(2086)       expr
ccgstmts.nim(259)        genVarStmt
ccgstmts.nim(199)        genSingleVar
cgen.nim(429)            assignGlobalVar
ccgtypes.nim(693)        getTypeDesc
ccgtypes.nim(611)        getTypeDescAux
ccgtypes.nim(571)        getTypeDescAux
ccgtypes.nim(528)        getTypeDescAux
ccgutils.nim(102)        getUniqueType
msgs.nim(957)            internalError
msgs.nim(866)            rawMessage
msgs.nim(863)            rawMessage
msgs.nim(796)            handleError
FAILURE
```

Does nim support generic types for seqs? Or am I doing something wrong with this code?

**Comment by reactormonk** [comment]
An internal error usually warrants a bug report. But I'm not sure what you intended to do. I wouldn't build on variance in nim, case objects are usually the way to go.

**Comment by jyapayne** [comment]
I was just trying something out. I thought it might be cool to have been able to add a bunch of generic objects to a seq, kind of like in Python.

**Comment by reactormonk** [comment]
There wouldn't be much sense in that in a typed language, because the compiler needs to know the type of the value you're trying to access. If you just give it an `object`, there is basically nothing you can do with it, because there are almost no procs associated with `object`.

**Comment by jyapayne** [comment]
Alright :) Just thought the error was strange. Maybe the compiler should reject just generic objects from being used in seqs?

**Comment by reactormonk** [comment]
Yes, that's a valid bug.

**Comment by Araq** [comment]
Fails with " Error: invalid type: 'object' in this context: 'seq[object]' for var".
