### ISSUE TITLE
user-definable set size

### ISSUE THREAD

**Issue by exetoc** [nim-lang/Nim#3071]
This is probably rarely needed, but it would be nice to be able to set the size of a set manually rather than having to add a dummy member to an enum type that is sufficiently large

**Comment by Varriount** [comment]
What do you mean by 'size'? There is a 'size' pragma for enums to control the number of bytes they take up.

**Comment by exetoc** [comment]
The size taken up by a set instance. The size appears to be dictated by the enumerator with the biggest value (the one defined last). If it has a value of <= 7, then the size of a set instance will be 1 byte, and so on. So the size of the enum type appears to have no relevance.

**Comment by Varriount** [comment]
Why do you need that?

**Comment by exetoc** [comment]
for simplifying serialization/deserialization

**Comment by Varriount** [comment]
Uh, you should probably be using some form of conversion which doesn't depend on the implementation details of sets then.

**Comment by exetoc** [comment]
You don't think there should be optional size requirements? I'll consider creating a new type

**Comment by Varriount** [comment]
No, I don't. There's little reason why any code should depend on an implementation detail of a built-in data type. It's bad design, and makes it harder to change code to adapt to changing designs.

**Comment by exetoc** [comment]
well, the size would be fixed upon user request, but yes it's better to implement a new type for this rare occasion. I'm closing this.
