### ISSUE TITLE
`repr` cstring

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#3080]
Two weird things happen here.
```nim
type
  X = cstring
var x: X
echo repr(x)
```
gives
```
repr.nim(291)            reprAny

repr.nim(259)            reprAux

SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Initializing it is actually a little weirder:
```nim
type
  X = cstring
var x: X = "a"
echo repr(x)
```
gives
```nim
00000000004FF0A0"a"
```
(the hex digits (usually) change with different runs)

**Comment by Varriount** [comment]
Well, I can at least give some information about the second case. The hexadecimal digits represent the memory address of the string.
