### ISSUE TITLE
Style Guide (Documentation Style) [RFC]

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#3089]
Style Guide (Documentation)
===========================

General Guidelines
------------------

* Authors should document anything that is exported.
* Within a documentation for a procedure, a period (`.`) should follow each sentence in a comment block if there is more than one sentence in that block; otherwise, no period should be used. In other sections, complete sentences should have periods. Sentence fragments should have none.
* Documentation is parsed as RST (RestructuredText).
* Inline code should be surrounded by double tick marks (``` `` ```). With ReStructuredTest (RST), if you would like a character to immediately follow inline code (e.g., "``int8``s are great!"), escape the following character with a backslash (`\`). The preceding is typed as ``` ``int8``\s are great!```.

Module-level documentation
--------------------------

Documentation of a module is placed at the top of the module itself. Each line of documentation begins with double hashes (`##`).
Code samples are encouraged, and should follow the general RST syntax:

```nim
## The ``universe`` module computes the answer to life, the universe, and everything.
##
## .. code-block:: nim
##  echo computeAnswerString*() # "42"
```

Within this top-level comment, you can indicate the authorship and copyright of the code, which will be featured in the produced documentation.

```nim
## This is the best module ever. It provides answers to everything!
##
## :Author: Steve McQueen
## :Copyright: 1965
##
```

Users are encouraged to leave a space between the last line of top-level documentation and the beginning of Nim code (the imports, etc.).

Procs, Templates, Macros, Converters, and Iterators
---------------------------------------------------

The documentation of a procedure should begin with a capital letter and should be in present tense. Variables referenced in the documentation should be surrounded by double tick marks (``` `` ```).

```nim
    proc example1*(x: int) =
        ## Prints the value of ``x``
        echo x
```

Whenever an example of usage would be helpful to the user, please include a sample within the documentation in RST format as below.

```nim
    proc addThree*(x, y, z: int8): int =
        ## Adds three ``int8`` values, treating them as unsigned and
        ## truncating the result
        ##
        ## .. code-block:: nim
        ##  echo addThree(3, 125, 6) # -122
        result = x +% y +% z
```

The commands ``nim doc`` and ``nim doc2`` will then correctly syntax highlight the Nim code within the documentation.

Types
-----

Types should also be documented. This documentation can also contain code samples, but those are likely better placed with the functions to which they refer.

```nim
type
  NamedQueue*[T] = object ## Provides a linked data structure with names
                          ## throughout. Named for convenience. I'm making
                          ## this comment long to show how you can, too.
    name*: string ## The name of the item
    val*: T ## Its value
    next*: ref NamedQueue[T] ## The next item in the queue
```

You have some flexibility when placing the documentation:
```nim
type
  NamedQueue*[T] = object
    ## Provides a linked data structure with names
    ## throughout. Named for convenience. I'm making
    ## this comment long to show how you can, too.
    name*: string ## The name of the item
    val*: T ## Its value
    next*: ref NamedQueue[T] ## The next item in the queue
```

Make sure to place the documentation beside or within the object.

```nim
type
  ## This documentation disappears. It's basically annotating the
  ## ``type`` above.
  NamedQueue*[T] = object
    name*: string ## This becomes the main documentation for the object, which
                  ## is not what we want.
    val*: T ## Its value
    next*: ref NamedQueue[T] ## The next item in the queue

```

Var, Let, and Const
-------------------

When declaring module-wide constants and values, documentation is encouraged. The placement of doc comments is similar to the ``type`` sections.

```nim
const
  X* = 42 ## An awesome number
  SpreadArray* = [
    [1,2,3],
    [2,3,1],
    [3,1,2],
  ] ## Doc comment for ``SpreadArray``
```

Placement of comments in other areas is usually allowed, but will not become part of the documentation output.

```nim
const
  BadMathVals* = [
    3.14, ## pi
    2.72, ## e
    0.58, ## gamma
  ] ## A bunch of badly rounded values
```

In the produced documentation, the comments beside the elements of ``BadMathVals`` do not make it into the final documentation.

As a final note, Nim supports Unicode in comments just fine, so the above can be replaced with the following:

```nim
const
  BadMathVals* = [
    3.14, ## π
    2.72, ## e
    0.58, ## γ
  ] ## A bunch of badly rounded values (including π!)
```

**Comment by apense** [comment]
This wasn't supposed to be so long. I just kept going. 
Comments and suggestions are welcome.

**Comment by dom96** [comment]
> Variables referenced in the documentation should be surrounded by tick marks (`).

Shouldn't they be surrounded by two tick marks? Same goes for all other identifiers.

**Comment by apense** [comment]
@dom96 yeah I think you're right. I've always been confused about that. Apparently single ticks have no default role and are open for interpretation. I'll switch over.

**Comment by Perelandric** [comment]
>*"...otherwise, a period is not needed"*

Just to clarify, does *"not needed"* mean *"is optional"* or does it mean *"should be excluded"*?

On that same bullet point, it should read *"A period (`.`) should follow each sentence..."* instead of *"Periods (`.`) should follow each sentence..."* and *"..more than one sentence..."* instead of *"..more that one sentence..."*.

Sorry for the nits. I think this document is very clear and helpful.

**Comment by apense** [comment]
@Perelandric great catches! updated.

**Comment by Perelandric** [comment]
@apense You're going to hate me before I'm done :sweat_smile: but just want to clarify the following comments given the punctuation rules.

Both of these endings have a single sentence with a code block after it but show different punctuation. Should this require a period?
```
## ...life, the universe, and everything.

## truncating the result
```

This one ends a single sentence but has a period.
```
## is not what we want.
```

Not that any of us are going to be policing this too strictly but just want to make sure I'm understand the requirements. Thanks. :smiley:

**Comment by apense** [comment]
I really wasn't sure about the `type` section rules. I figured I would just have different examples to show either is accepted, but I should have been explicit, I think. The reason the first example you gave has a period is because it's in the general documentation. I should update that section to reflect the difference. Keep em' coming!

**Comment by jibal** [comment]
"This wasn't supposed to be so long. I just kept going."

Yeah, same here ... my apologies. But I've written a lot of technical documentation, so here goes:


"Within a documentation" -> "Within the documentation" or "Within documentation" (the latter is consistent with later sections).

"With ReStructuredTest (RST), if" -> "If"  (you just stated that it's RST; no need for the redundancy).

"in general" -- unnecessary noise.
"itself" -- ditto.

".. code-block:: nim" -- isn't Nim the default? At least capitalize it. And code blocks should have an indentation of 2 spaces, not 1.

"Users are encouraged" -- no need to be wishy-washy ... the guidelines should be positive statements.

"please" -- "you should"

"a sample" ->  "one". And I think examples should be identified as such in documentation comments.

"Types should also be documented." -- I think only exported types (or anything else) *require* documentation.

" likely" -- better would be "usually", or just omit

"This documentation disappears. It's basically annotating the ``type`` above" -> "This documentation disappears because it annotates the ``type`` keyword above, not ``NamedQueue``"

"This becomes the main documentation for the object" -- I don't think so ... that comment is attached to ``name``.

"will not become part of the documentation output" -- then they should use single "#", not double.

"As a final note" -- noise
"just fine" -- same

**Comment by apense** [comment]
@jibal thank you!

In the "This becomes the main documentation..." place, what I mean is it produces this:
```nim
NamedQueue[T] = object 
  name*: string
  val*: T                     ## Its value
  next*: ref NamedQueue[T]    ## The next item in the queue
```
```
    This becomes the main documentation for the object, which is not what we want. 
```

I changed some instructions to indicated that I mean general module documentation should be at the top.

I probably put new mistakes in my updates, but I really tried not to.

**Comment by apense** [comment]
Really, though, I think that "name" documentation issue should be put into the issue, because it really should just not produce documentation for the object itself. I'll make a new issue.

**Comment by Araq** [comment]
Why is this a bug and not a PR?

**Comment by apense** [comment]
So I could get it finalized with contributions before a PR. figured it
would be a little easier. should the PR be against the style guide?
anywhere else?

**Comment by reactormonk** [comment]
Call it `styleGuide.rst` and link to it from `contributing.rst`?

**Comment by ReneSac** [comment]
The authorship and copyright indications should be above or bellow the above documentation? This should be clearer.

**Comment by apense** [comment]
I'll do what @reactormonk suggested right after I fix what @ReneSac asked about.

**Comment by apense** [comment]
#3118 is the PR for this. Any comments from now on should be made there, but I think it's ready to pull.

**Comment by jibal** [comment]
So *all* of my suggestions were ignored?

**Comment by apense** [comment]
Oh gosh! I think I edited the file locally and didn't update the post here. None of your suggestions were ignored, really. I just need to find where I put the file I made.

**Comment by apense** [comment]
@jibal I'm just going to update the PR so I can keep better track.

**Comment by reactormonk** [comment]
Please move all discussion over to https://github.com/nim-lang/Nim/pull/3118
