### ISSUE TITLE
"out of memory" not caught by try/except

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3090]
The following doesn't get caught (when allocating data strucures larger than the availale system memory):
```
let loopc = 9_999_999_999
var 
  s0: seq[int] = @[]
  s1: seq[int] = @[]
  s2: seq[int] = @[]
try:
  s0 = newSeq[int](loopc+1)
  s1 = newSeq[int](loopc+1)
  s2 = newSeq[int](loopc+1)
except:
  echo "Memory Error"
  discard
  quit()
```
----------
Feature request for Nim V2:
Ability to store the standard system defined collections on "hidden" disk storage, so can operate on data structures of greater size than available memory, and Nim handles the swapping for the user.
For speed reasons, maybe this is a compile time option that is only enabled when wanted??

**Comment by reactormonk** [comment]
Yes, OOM exceptions tend to be ugly to handle. Because the code for the error handling can't allocate more memory, otherwise you'd have more OOM.

Btw, no need to swap stuff from nim, your OS should handle swapping.

**Comment by Varriount** [comment]
I don't think the need for such structures is great enough that it warrants being in the standard library. Most of the time, mmap or memory buffers will do what you want.

**Comment by jlp765** [comment]
I will close this.  This is the behaviour of Nim when the OS is unable to allocate memory to the application.
