### ISSUE TITLE
algorithm.binarySearch continues even when key is found

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#3105]
https://github.com/nim-lang/Nim/blob/devel/lib/pure/algorithm.nim#L65-L72

``` Nim
proc binarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    var mid = (result + b) div 2
    if a[mid] < key: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1
```

Will keep searching even when `a[mid] == key`. 

``` Nim
import algorithm
echo(binarySearch([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1))
# Expected Index: 5
# Got: 0
```

This leads to return the first occurrence of key on the array, not the first key found by binarySearch, which i can't tell if it is the expected or desired behavior. 
In [C#](https://msdn.microsoft.com/en-us/library/2cy9f6wb%28v=vs.110%29.aspx), binay search only returns the first element found:

> Duplicate elements are allowed. If the Array contains more than one element equal to value, the method returns the index of only one of the occurrences, and not necessarily the first one.

And the same behavior can be found in [Java](http://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#binarySearch-int:A-int-):

> If the array contains multiple elements with the specified value, there is no guarantee which one will be found.

Maybe there should be two procs, one for finding the first occurrence inside the array, and another for faster search.

**Comment by Abrasax-** [comment]
Also, you might want to read [Extra, Extra - Read All About It: Nearly All Binary Searches and Mergesorts are Broken](http://googleresearch.blogspot.com.es/2006/06/extra-extra-read-all-about-it-nearly.html)

**Comment by Varriount** [comment]
I believe the unsigned-add-then-truncate operator ('+%' I think?) Should solve the problem outlined in that article.

**Comment by jibal** [comment]
Why is this an issue? As long as binarySearch returns *some* valid index , it works. Exactly the same is true of Java and C# ... that's what "not necessarily" and "no guarantee" mean.

The overflow is a real bug and should be filed.

**Comment by Abrasax-** [comment]
> As long as binarySearch returns some valid index , it works
Under your definition, including os.sleep(1000) would still make it valid, but it is obvious this is not a desired property, because we don't want just it to work, but to work as fast as possible. With one line you could make it, but i'm not sure if it is desired or not. At least, for my part, i would expect to return the first occurrence, and i suppose more people expect the same as me, that's the reason behind this issue.

>"In C#, binay search only returns the first element found" -- that's exactly what the text you quoted doesn't say.
You are right, the text says the returned index is not necessary the first occurrence in the array, but again, it is implied i can and probably it will in cases where more than one key is stored.

The problem here is that, if you are using binarySearch, chances are you need it for large arrays (otherwise you would be fine with a naive for i, k in array: if k == key: return i) and in many cases duplicates are expected. What it is not expected is if client code needs *exactly* the first occurrence in the index, which i think is not going to be the norm.

>The overflow is a real bug and should be filed
You are right again, i should submit this one too.

**Comment by jibal** [comment]
"Under your definition, including os.sleep(1000) would still make it valid"

Sorry, but I'm not going to bother with such intellectually dishonest malarkey.

" it is implied "

No, it clearly isn't. The text explicitly says that you can't assume what index is returned.

**Comment by Abrasax-** [comment]
>Don't be ridiculous. Your absurd response seems (...) / penny-wise pound-foolish optimization.

First of all, i treat you with respect, and i expect the same from others. So behave yourself, i'm tempted to ignore you

>Your absurd response seems to be based on the mistaken and bizarre notion that adding an extra test that usually fails would make the code faster.

It is not a mistaken or bizarre notion, you can test it by yourself:

```Nim
import algorithm
import math
import times

proc fbinarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    var mid = (result + b) div 2
    if a[mid] == key: return mid  #Addition
    if a[mid] < key: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1
  
#Init
const MAX = 1_000
const ITE = 1_000_000
var s = newSeq[int]()

for i in 1..ITE:
  add s, random(MAX)
  
sort s, proc(a, b: int): int =
  return if     a < b: -1
         elif   a == b: 0
         else:  1
  
#fbinarySearch
block:
  let t1 = cpuTime()
  for i in 1..ITE:
    let 
      key = random(MAX)
      idx = fbinarySearch(s, key)
    assert s[idx] == key
    
  echo "RES: " & $(cpuTime() - t1)
  
#binarySearch in algorithm
block:
  let t1 = cpuTime()
  for i in 1..ITE:
    let 
      key = random(MAX)
      idx = binarySearch(s, key)
    assert s[idx] == key
```
This in my computer outputs:
```
RES: 0.7499999999999996
RES: 1.578
```
> Which is why it doesn't waste time doing log2(n) checks for an exact match, instead just doing one.

Read above, and also you are taking the assumption that calculating `k1 < k2` will always be fast. In my case it was, and still fbinarySearch beat the one from algorithm.

> I've never encountered such cases. Using a binary search to fetch the index of an element in an array with duplicates is incorrect design. In any case, it's irrelevant ... saving time for the case where there are multiple matches is penny-wise pound-foolish optimization.

Now you are baiting me. To begin with, it doesnt matter what you and i have encountered, but what thousands of nim programmers will have to face. Are you telling me an obvious and proved optimization that only takes one line is irrelevant? And i dont see whyt it is an incorrect design, you are making it out of nothing. If that were the case, you would be using plain dictionaries, not arrays.

> What the text in both the C# and Java specs implies is that implementations are free to return the index of whichever duplicate they want, and that an implementation can change and return a different index some day, and that users must not make assumptions.

You are right here, but now you are arguing just for the shake of it. Even when text opens the door for any future change, it has been the way it is for more [than 10 years](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/Arrays.java#Arrays.binarySearch%28int%5B%5D%2Cint%2Cint%2Cint%29). 
My point here is that users from Java and C# (which right now represents a big chunk of the programming community) expects that behaviour, so it could be worth to reconsider the behaviour in nim. Of course, i could continue and include others languages that do this, such as [Rust](https://github.com/rust-lang/rust/blob/50d305e498c29c022c5bca2726d22e9f09b0a437/src/libcore/slice.rs#L282), but at this point, i dont have to reinforce the idea of what users are expecting.

>There is no bug here, and "fixing" this non-bug would make binarySearch slower on average.

I have proven this claim to be false. To summarize my points:

- I'm not clear whether binarySearch should work the way it does right now. Based on major programming languages and that adding `k1 == k2: return idx` makes binarySearch faster (which is a desired property), i would expect the opposite. 
- Duplicated keys are not only expected but actually justifies arrays in binarySearch against the use of other datastructures (for example, tables).
- The mentioned optimization does make the code faster, not slower, and it only takes one line, so unless, for some reason, people expect binarySearch to actually return the first occurrence in the array (which no bs definition actually stablish that), i'd go for it.

**Comment by jibal** [comment]
"First of all, i treat you with respect"

You did not treat me with respect, and I'm done engaging with you.

**Comment by Varriount** [comment]
Since the tone of this issue has become decidedly negative, I am locking this issue. @araq or one of the other maintainers can unlock it when they see fit.

On the topic of what should be done, I would prefer that the current binarySearch algorithm be modified to use a `cmp` or `compare` procedure against the selected objects, returning some value indicating greater than, less than, or equal. This has the benefit of ending the loop at the earliest possible moment, while keeping the number of comparisons done the same.

**Comment by Araq** [comment]
The benchmark is pretty flawed though since it never performs unsucessful searches which can dominate. But for this code your version is still faster:

```nim

import algorithm
import math
import times

proc fbinarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    var mid = (result + b) div 2
    if a[mid] == key: return mid  #Addition
    if a[mid] < key: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1


proc abinarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    var mid = (result + b) div 2
    if a[mid] < key: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1

#Init
const MAX = 1_000
const ITE = 1_000_000
var s = newSeq[int]()

for i in 1..ITE:
  add s, random(MAX)

sort s, proc(a, b: int): int =
  return if     a < b: -1
         elif   a == b: 0
         else:  1

proc mainB =
  let t1 = cpuTime()
  for i in 1..ITE:
    let 
      key = random(MAX)-1000
      idx = abinarySearch(s, key)
    if idx >= 0:
      doAssert s[idx] == key
  echo "RES B: " & $(cpuTime() - t1)


#fbinarySearch
proc mainA =
  let t1 = cpuTime()
  for i in 1..ITE:
    let 
      key = random(MAX)-1000
      idx = fbinarySearch(s, key)
    if idx >= 0:
      doAssert s[idx] == key

  echo "RES A: " & $(cpuTime() - t1)

mainA()
mainB()
```

**Comment by Araq** [comment]
And for this it's slower:

```nim

import algorithm
import math
import times

proc fbinarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    let mid = (result + b) div 2
    let c = cmp(a[mid], key)
    if c == 0: return mid  #Addition
    if c < 0: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1


proc abinarySearch*[T](a: openArray[T], key: T): int =
  ## binary search for `key` in `a`. Returns -1 if not found.
  var b = len(a)
  while result < b:
    let mid = (result + b) div 2
    let c = cmp(a[mid], key)
    if c < 0: result = mid + 1
    else: b = mid
  if result >= len(a) or a[result] != key: result = -1

#Init
const MAX = 1_000_000
const ITE = 1_000_000
var s = newSeq[int]()

for i in 1..ITE:
  add s, i # random(MAX)

sort s, proc(a, b: int): int =
  return if     a < b: -1
         elif   a == b: 0
         else:  1

proc mainB =
  let t1 = cpuTime()
  var successful = 0
  for i in 1..ITE:
    let 
      key = random(MAX)#-500+1
      idx = abinarySearch(s, key)
    if idx >= 0:
      doAssert s[idx] == key
      successful += 1
  echo "RES B: " & $(cpuTime() - t1), " ", successful


#fbinarySearch
proc mainA =
  let t1 = cpuTime()
  var successful = 0
  for i in 1..ITE:
    let 
      key = random(MAX)#-500+1
      idx = fbinarySearch(s, key)
    if idx >= 0:
      doAssert s[idx] == key
      successful += 1

  echo "RES A: " & $(cpuTime() - t1), " ", successful

#binarySearch in algorithm
mainA()
mainB()
```

**Comment by data-man** [comment]
This is no longer relevant.
