### ISSUE TITLE
Json module - SIGSEGV if key not exists

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3107]
This results in SIGSEGV:
```Nimrod
import json
var data = parseJson("{\"a\":1,\"b\":2}")
echo data["a"]
echo data["c"]
```
Is that ok? Why not exception?

**Comment by Perelandric** [comment]
```
Traceback (most recent call last)
test.nim(38)             test
json.nim(990)            $
json.nim(759)            len
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Seems that it's from the `len` proc missing a `nil` check. The default when not given a `jArray` or `jObject` is to return `0`, so I'd think it would be the same for `nil`.

**Comment by dom96** [comment]
I would rather be told that what I am passing to it is ``nil``.

**Comment by scriptum** [comment]
Another strange behavior:
```
import tables
var a = newTable[string,string]()
echo a["b"] #nil
var b = newTable[string,int]()
echo b["c"] #0
b["c"] = 0
echo b["c"] #0 - same result: is key exist with value 0 or it doesn't exist?
```
Python throws exception in both cases.

**Comment by Perelandric** [comment]
I guess some `len()` procs handle `nil` and others don't. Weird.

@scriptum According to the docs, you get the default value for the type if no key exists, so this by design.
