### ISSUE TITLE
Use SOURCE_DATE_EPOCH instead of current time in docgen

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#3113]
As part of the Debian [Reproducible Builds](https://wiki.debian.org/ReproducibleBuilds) effort, we're standardising a way for documentation generators (and other tools) that want to use timestamps. It would be good if `docgen.nim` could use the time given by the [`SOURCE_DATE_EPOCH`](https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal) environment variable, instead of the current time, if the former is available.

I have a patch for this and will submit it soon.

**Comment by Araq** [comment]
Ok, go ahead, sounds good. :-)
