### ISSUE TITLE
improvements for list comprehensions

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#3116]
This

``` nim
echo lc[pair.val | (pair <- [0, 1, 2, 3].pairs, pair.val == 0, pair.val == 1), int]
```

Could be shortened to something like this

``` nim
echo lc[v | ((k, v) <- [0, 1, 2, 3], v == 0, v == 1), int]
```

And it would be nice to have the option of omitting the return type

**Comment by def-** [comment]
> And it would be nice to have the option of omitting the return type

Related to https://github.com/nim-lang/Nim/issues/2179

**Comment by ReneSac** [comment]
Better yet, if the syntax would be more familiar to nim syntax, such as anyone familiar with nim could guess what it does:
```nim
echo lc[for i, x, in [0,1,2,3]: if i == 1: x.pow 2]
```
This is analogous to what the regular nim code would be:
``` nim
var o = newSeq[int]
for i, x, in [0,1,2,3]:
  if i == 1: o.add(x.pow 2)
```
The only thing is that the ":" alone is visually kinda a week separator. It might look better moving the result to before the "for" like python:

```nim
echo lc[x.pow 2 for i, x, in [0,1,2,3]: if i == 1]
```

**Comment by rbehrends** [comment]
I still think that the specialized `lc` syntax is too limited; a simple template [can support all iterators](https://github.com/nim-lang/Nim/pull/1443#issuecomment-61439642) and work properly with type inference.

**Comment by ReneSac** [comment]
rbehrends: cool, I liked it. I'm only not sure about the name "enumerate" but the addition of the "yield" keyword solves the problem of visual separation and on top of that makes it more like normal nim code (well, it's because it is normal nim code).

The only thing is that I can't do one-liners that way:
```nim
# Error: complex statement requires indentation
echo enumerate do: for i, x in [0,1,2,4]: if i == x: yield x * 2
```

And if I try to indent it in multiple lines, the compiler will produce invalid C code:
```nim
# error: ‘result_98663’ undeclared (first use in this function)
#  LOC44 = HEX24_98117(result_98663);
echo enumerate do: 
  for i, x in [0,1,2,4]:
    if i == x: 
      yield x * 2
```

**Comment by rbehrends** [comment]
@ReneSac: I don't really care much about the choice of name; I just think that any list comprehension mechanism should allow for all use of iterators, not just a limited subset. As for the compiler error, I think this is a new bug (I wrote this a long time ago) that needs to be fixed independently; it can be avoided for now by eliding the `block:` and making `temp` and `result` both `{.gensym.}` names.

To avoid the indentation error, use parentheses, e.g.:

```nim
echo enumerate do: (for i, x in [0,1,2,4]: (if i == x: yield x * 2))
```

**Comment by ReneSac** [comment]
Thanks for the parenthesis tip. I tried adding them before, but only one pair at a time, and thus still got the same error. Now it gives the same C generation error as the indented version.

You should fill a new bug with that.

**Comment by ReneSac** [comment]
Update: the C generation error was corrected, so there is nothing more blocking rbehrends list comprehension template. I vote for deprecating the current lc in the experimental module and adding this lc as default in system maybe.

**Comment by GULPF** [comment]
List comprehensions has been deprecated in #10636 in favor of for loop macros, so this can be closed.
