### ISSUE TITLE
htmlparser has a bug

### ISSUE THREAD

**Issue by soarowl** [nim-lang/Nim#3119]
source code as following:

``` nim
import htmlparser, httpclient, os, streams, strtabs, strutils, xmltree

let content = getContent("http://lib.haxe.org/all")
let startMark = "<tbody>"
let startIndex = find(content, startMark)
let endMark = "</tbody>"
let endIndex = find(content, endMark, startIndex)
let desired = content[startIndex + startMark.len .. endIndex - 1]
let s = newStringStream(desired)
let html = parseHtml(s)
for a in html.findAll("a"):
  let href = a.attrs["href"]
  if not href.isNil:
    let project = a.innerText
    let projectHref = "/p/$1/" % project
    if href == projectHref:
      echo("install $1 ..." % project)
      let cmd = "haxelib -notimeout install $1" % project
      echo(cmd)
      #while true:
      #  let status = cmd.execShellCmd
      #  if status == 0: break
```

The result always wrong: parser stop in somewhere in middle with error expect `</a>`. But I have double checked the html source code, found proc `parseHtml` has a bug.

**Comment by Araq** [comment]
Works for me (windows 7). What's your OS/CPU, Nim version, used C compiler?

**Comment by soarowl** [comment]
Program can run, but DOM is not full. The last item should be `yhf` at present, but I got `nme-vfs`. My develop environment is (Win10 64Bit Build 10166, MSYS2 64, GCC 4.9.2). Nim is git master version. I checked the program in Win8, the result is wrong too.

**Comment by exetoc** [comment]
```
<br /><small><a href="&#x2F;u&#x2F;soywiz&#x2F
;">@s</a></small></th></tr></document>
```
that's not right. the bug I reported last year might be relevant https://github.com/nim-lang/Nim/issues/1034

**Comment by Araq** [comment]
I download it under 'foo.html' and this is the list of errors in the HTML:

foo.html(1380, 20) Error: ';' expected                
foo.html(2431, 41) Error: ';' expected                
foo.html(4162, 81) Error: '>' expected                
foo.html(4162, 96) Error: </option> expected          
foo.html(6400, 8) Error: </p> expected                
foo.html(6412, 42) Error: ';' expected                
foo.html(6417, 0) Error: </html> expected             

Every single reported error is a real error in the HTML. That it keeps things from working is unfortunate, but it makes it a minor stdlib bug.

**Comment by soarowl** [comment]
Thanks, Araq!

**Comment by Araq** [comment]
Reopening since htmlparser claims it can parse "wild" HTML and it should be able to handle missing ending tags.

**Comment by zielmicha** [comment]
htmlparser should probably use HTML5 parsing algorithm (http://www.w3.org/TR/2011/WD-html5-20110113/parsing.html, just like Python's html5lib). 
> This specification defines the parsing rules for HTML documents, whether they are syntactically correct or not. Certain points in the parsing algorithm are said to be parse errors. The error handling for parse errors is well-defined: user agents must either act as described below when encountering such problems, or must abort processing at the first error that they encounter for which they do not wish to apply the rules described below.

**Comment by Araq** [comment]
Fully agreed. Hopefully it's simple enough to implement.

**Comment by narimiran** [comment]
The original example (changed as shown below to work without warnings and errors) works correctly on Nim 0.19.


```nim
import htmlparser, httpclient, os, streams, strtabs, strutils, xmltree

let client = newHttpClient()                                # added
let content = client.getContent("http://lib.haxe.org/all")  # changed
let startMark = "<tbody>"
let startIndex = find(content, startMark)
let endMark = "</tbody>"
let endIndex = find(content, endMark, startIndex)
let desired = content[startIndex + startMark.len .. endIndex - 1]
let s = newStringStream(desired)
let html = parseHtml(s)
for a in html.findAll("a"):
  let href = a.attrs["href"]
  if href != "":                                            # changed
    let project = a.innerText
    let projectHref = "/p/$1/" % project
    if href == projectHref:
      echo("install $1 ..." % project)
      let cmd = "haxelib -notimeout install $1" % project
      echo(cmd)
```
