### ISSUE TITLE
Problem with generic lambdas

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3127]
This code won't compile:

``` nimrod
import future

type Holder[T] = object
  value*: T

proc newHolder[T](v: T): Holder[T] = Holder[T](value: v)

proc `$`[T](h: Holder[T]): string = "Holder(" & $h.value & ")"

proc map[T,U](h: Holder[T], f: T -> U): Holder[U] = newHolder[U](f(h.value))

echo(newHolder(100).map((x) => x * 2))

```

with message 

```
lambda.nim(12, 25) Warning: '(x): auto' has no type. Typeless parameters are deprecated; only allowed for 'template' [TypelessParam]
lambda.nim(12, 20) Error: type mismatch: got (Holder[system.int], proc (x: GenericParam): auto)
but expected one of:
lambda.map(h: Holder[map.T], f: proc (i0: T): U{.closure.})
system.map(data: openarray[T], op: proc (x: T): S{.closure.})
system.map(data: var openarray[T], op: proc (x: var T){.closure.})
```

If I supply paramerer type like this:

``` nimrod
echo(newHolder(100).map((x: int) => x * 2))
```

,  error disappears.

**Comment by Araq** [comment]
Very hard to implement. I think we might alternatively redesign 'map' to allow for better type inference instead of making the compiler even more complex.

**Comment by vegansk** [comment]
This is not about system.map function and it's design. It's about type inference in compiler itself.

**Comment by Araq** [comment]
As if i don't know...

**Comment by petermora** [comment]
After applying https://github.com/nim-lang/Nim/pull/3234 this code below works. However it is not the same as the original code posted above.
```nim
import future

type Holder[T] = object
  value*: T

proc newHolder[T](v: T): Holder[T] = Holder[T](value: v)

proc `$`[T](h: Holder[T]): string = "Holder(" & $h.value & ")"

proc map[T,U](h: Holder[T], f: T -> U): Holder[U] = newHolder[U](f(h.value))

proc myF[A,B](x: A): B = x * 2

echo(newHolder(100).map(myF))
```

**Comment by vegansk** [comment]
@petermora An interesting thing happens with last devel. Here (https://github.com/vegansk/nimtests/blob/49dd3791380596e77874b0a4624bc9464764a9f6/fpinnim/Ch03/List.nim#L170) the type is required, and here (https://github.com/vegansk/nimtests/blob/49dd3791380596e77874b0a4624bc9464764a9f6/fpinnim/Ch03/List.nim#L171) is not required.

**Comment by Yardanico** [comment]
@dom96 works for me.
And also https://raw.githubusercontent.com/vegansk/nimtests/49dd3791380596e77874b0a4624bc9464764a9f6/fpinnim/Ch03/List.nim works

**Comment by dom96** [comment]
Reopen if still a problem.
