### ISSUE TITLE
Version 0.11.3 for Windows

### ISSUE THREAD

**Issue by xgrommx** [nim-lang/Nim#3136]
Hello everyone. When should be a new version for Windows(0.11.3)?

**Comment by Varriount** [comment]
Hm? 0.11.3 is still in development. The current version on the 'devel' branch should compile on Windows though.

**Comment by dom96** [comment]
We don't have a date set yet. Please ask questions like these on the [Nim Forums](http://forum.nim-lang.org) or IRC next time.
