### ISSUE TITLE
Invalid bitwise and on uint64

### ISSUE THREAD

**Issue by tolson68** [nim-lang/Nim#3139]
It looks like bitwise operations on uint[n] types is not completely implemented yet otherwise I may have found a bug.

var x: uint64 = uint64(0xffffffffffffffff)
var r: uint64 = int64(x) and 0xffffffff

returns:  18446744073709551615

also requiring a cast to and/or from uint seems incorrect, because unsigned types do not seem to be implemented in system.and

**Comment by Varriount** [comment]
For now you need to import the `unsigned` module to get many unsigned operations.

**Comment by tolson68** [comment]
That did the trick.  Thanks for the quick reply
