### ISSUE TITLE
build Nim fail

### ISSUE THREAD

**Issue by xenogenesi** [nim-lang/Nim#3151]
I'd like to try Nim and I followed instructions from [download page](http://nim-lang.org/download.html)

I've tried both git and tar sources, with gcc-4.8, 4.9 and clang 3.5.2 (I'm using Debian/sid on Linux)

gcc:

     In file included from c_code/2_2/nimsrc_nim.c:5:
     c_code/nimbase.h:393:28: error: 'assert_numbits' declared as an array with a negative size
     typedef int assert_numbits[sizeof(NI) == sizeof(void*) && 64 == sizeof(NI)*8 ? 1 : -1];

clang:

    In file included from c_code/2_2/nimsrc_nim.c:5:
    c_code/nimbase.h:393:28: error: 'assert_numbits' declared as an array with a negative size
    typedef int assert_numbits[sizeof(NI) == sizeof(void*) && 64 == sizeof(NI)*8 ? 1 : -1];
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I'm doing something wrong?

Also, just a note, I seen `build.sh` *set* `CC` and `LINKER` variables, would be nice if it at least check and eventually use them from the environment.

**Comment by Araq** [comment]
Use a GCC/clang that agrees with Nim on the size of a pointer.

**Comment by xenogenesi** [comment]
My userspace is 32bit is that the problem? But I seen there's a 32bit for Windows.. isn't supported for Linux?

gcc and clang tested are the usual distributed with Debian, are you telling me I should build a toolchain just for Nim?

**Comment by dom96** [comment]
Is your Linux 32bit?

**Comment by kirbyfan64** [comment]
@xenogenesi What does running `uname -m` print? Seems like `build.sh` thinks you have a 64-bit system...

**Comment by xenogenesi** [comment]
My hardware and my kernel are 64bit but my user space is 32bit, I was gonna to install an amd64 userspace in the next days (having free time..)

    Linux hellspawn 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

    gcc: Target: i586-linux-gnu

**Comment by dom96** [comment]
You need to get a 64bit gcc or hack build.sh.

**Comment by xenogenesi** [comment]
Thanks @dom96 forced ucpu to i686 seems to build

**Comment by xenogenesi** [comment]
SUCCESS without a warning, thanks a again, issue solved :+1:
