### ISSUE TITLE
another static_t problem

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#3152]
``` nim

proc p(x: static[int]) = echo "static int"
proc p(x: int) = echo "int"

type st = static[int]

p(st(888))
```

**Comment by LemonBoy** [comment]
What is the expected result here? By passing `st(888)` you get a match during the overload resolution phase for both the definitions of `p` (both are exactMatches). We end up comparing the `sumGeneric` result which is 0 for the first definition and 1 for the second one thus making this the best candidate available.
The excerpt from the [manual](https://nim-lang.org/docs/manual.html#iterators-and-the-for-statement) makes me think that `p(888)` and `p(st(888))` should be treated the same way, this can be achieved by making `sumGeneric` take into account the `tyStatic` tag like this:
```nim
    of tyStatic:
      inc result
      result += t.sons[0].sumGeneric
      break
```

**Comment by zah** [comment]
My personal plans were to give `static[T]` a preference similar to `var` in situations like this. Is that the goal?

**Comment by LemonBoy** [comment]
That works too, at least in this example.
