### ISSUE TITLE
Slow string search

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3155]
libc always beats Nim's implementation (tested Linux x86_64):

``` Nim
import strutils, times

template `++`(s: string, offset: int): expr =
    cast[cstring](cast[int](cstring(s)) + offset)

proc altfind(s, sub: string, start: Natural = 0): int {.inline.} =
  proc strstr(a, b: pointer): pointer {.importc, header: "string.h".}
  if s.len < sub.len + start: return -1
  let res = cast[int](strstr(s++start, cstring(sub)))
  if res != 0: return res - cast[int](cstring(s))
  return -1

proc altfind(s: string, sub: char, start: Natural = 0): int {.inline.} =
  proc strchr(a: pointer, b: cint): pointer {.importc, header: "string.h".}
  if s.len < 1 + start: return -1
  let res = cast[int](strchr(s++start, sub.ord))
  if res != 0: return res - cast[int](cstring(s))
  return -1

when isMainModule:
  var res: int
  # long string
  let a = 'x'.repeat(1024*1024*1024)
  for needle in ["hello", "hello".repeat 10, "hello".repeat 1000]:
    var cpu1 = cpuTime()
    res = a.find(needle)
    echo "old ", cpuTime() - cpu1, " ", res
    cpu1 = cpuTime()
    res = a.altfind(needle)
    echo "new ", cpuTime() - cpu1, " ", res
  var cpu1 = cpuTime()
  res = a.find('c')
  echo "old ", cpuTime() - cpu1, " ", res
  cpu1 = cpuTime()
  res = a.altfind('c')
  echo "new ", cpuTime() - cpu1, " ", res
  # short strings
  let b = 'x'.repeat(128)
  cpu1 = cpuTime()
  for i in 0..1000000:
    res += b.find("hello")
  echo "old ", cpuTime() - cpu1, " ", res
  cpu1 = cpuTime()
  for i in 0..1000000:
    res += b.altfind("hello")
  echo "new ", cpuTime() - cpu1, " ", res
  cpu1 = cpuTime()
  for i in 0..1000000:
    res += b.find('c')
  echo "old ", cpuTime() - cpu1, " ", res
  cpu1 = cpuTime()
  for i in 0..1000000:
    res += b.altfind('c')
  echo "new ", cpuTime() - cpu1, " ", res

old 0.578103 -1
new 0.1501140000000001 -1
old 0.192072 -1
new 0.1860760000000001 -1
old 0.01996299999999973 -1
new 0.01987700000000014 -1
old 0.8332839999999999 -1
new 0.1506780000000001 -1
old 0.257072 -1000002
new 0.0171490000000003 -2000003
old 0.1070769999999999 -3000004
new 0.01177099999999998 -4000005
```

Why not just use libc functions for Nim strings? It's simpler, faster, shorter.

**Comment by def-** [comment]
> Why not just use libc functions for Nim strings? It's simpler, faster, shorter.

Sounds good, I'd welcome a PR.

**Comment by Varriount** [comment]
The problem with this that Nim strings can contain null characters, which strstr interpreted as string endings.

**Comment by Varriount** [comment]
In addition, the performance of strstr may vary from platform to platform. I would feel much better if a better implementation was written instead.

**Comment by scriptum** [comment]
> The problem with this that Nim strings can contain null characters, which strstr interpreted as string endings.

Is that tested enough? I use memmem - it shouldn't care about null characters.

> In addition, the performance of strstr may vary from platform to platform. I would feel much better if a better implementation was written instead.

Usually libc guarantees best performance for current CPU.  If possible it uses SSE42, if not - SSE3, if not - SSE2, if not - MMX. After all it falls back to plain C. Same for other platforms (power, arm...).
You are offering to re-implement **all** libc functionality - [from detecting CPU](http://fossies.org/dox/glibc-2.21/sysdeps_2x86__64_2multiarch_2ifunc-impl-list_8c_source.html#l00033) to platform assembly.

Some libc alternatives are slower because of compact size in cost of performance but you will definitely get performance **not slower** than in C/C++:smile:

**Comment by Varriount** [comment]
[memmem is glib specific](http://stackoverflow.com/a/1992271), so that really can't be used. As for the whole "the libc should be fastest", I doubt that argument holds for mingw-compiled programs, since it uses [msvcrt.dll](http://stackoverflow.com/questions/19053588/changing-msvcrt-dll-on-windows-system), which is... [messy](http://blogs.msdn.com/b/oldnewthing/archive/2014/04/11/10516280.aspx)

I realize that most developers use Linux or BSD, but I would really appreciate it if some thought was given with regards to Windows development. Love it or hate it, it's still a platform Nim should run on.

**Comment by scriptum** [comment]
Exactly. Glibc uses two-way algorithm accelerated with memchr and memcmp which should be even on Win platfrom. Could Nim detect if current platform has memmem?

glibc's [two-way implementation](https://github.com/lattera/glibc/blob/master/string/str-two-way.h) even could probably be adapted but it is even bigger than current `find` algorithm.

**Comment by Varriount** [comment]
@scriptum Regarding licensing, it gets a bit tricky... We wouldn't be wholesale copy/pasting the algorithm, but instead using it as a source of knowledge for implementing a new algorithm.  
If we want to be cautious, we could use a source like [this](http://www-igm.univ-mlv.fr/~lecroq/string/node26.html#SECTION00260).

**Comment by kirbyfan64** [comment]
[Bionic's `memmem`](https://github.com/android/platform_bionic/blob/master/libc/bionic/memmem.c) is implemented using the [Not So Naive algorithm](http://www-igm.univ-mlv.fr/~lecroq/string/node13.html) from the same site @Varriount linked. Maybe that would make a good base point, as, in my mind, when Google decides to use it, that's a very, very good sign. :)

**Comment by scriptum** [comment]
Indeed memmem and strstr performance is too delicate question. There are too many cases where [different algorithms behaves in different way](http://www.codeproject.com/Articles/250566/Fastest-strstr-like-function-in-C). Since non-real-life troll situations (e.g. `'x' * 1 000 000 000` haystack and `'x'*100+'l'` needle) are possible there is no perfect algorithm.

Looking into glibc showed that there is [sse42 optimized](http://www.strchr.com/strcmp_and_strlen_using_sse_4.2) version of strstr (really fast) while memmem is not optimized with sse42, maybe because of null characters it is not possible.

:question: Does Nim have intrinsics?

In that issue memchr definitely will be faster than naive loop but as mentioned above there is shortcoming with compile time evaluation (I don't know if Nim could support two versions for const expressions and for runtime). Using sse-accelerated strstr seems to be not possible for Nim's strings which may contain null char. Current find implementation probably could be optimized using memchr to find first char where to start finding.

Another solution - let users know that internal finding is slow and for performance critical applications it's better to use hand-made algorithms... AFAIK Nim doesn't have runtime library and including all possible sse-variations will cause code bloating.

**Comment by Araq** [comment]
>  llet users know that internal finding is slow

It is not slow and in 2015 I expect C compilers to find SSE-able code sections on their own. ;-)

> Does Nim have intrinsics?

There are Nimble packages out there which provide intrisics or you can wrap them on your own, it's trivial. 

But again, IMO there is nothing to fix here.

**Comment by Araq** [comment]
> Why not just use libc functions for Nim strings?

Why not produce a real benchmark that is not naive? ;-)

**Comment by Varriount** [comment]
It would be interesting to see a nimble package that implemented all those different search algorithms...

**Comment by scriptum** [comment]
> It is not slow and in 2015 I expect C compilers to find SSE-able code sections on their own. ;-)

Compiler cannot produce e.g. sse42 code because it only supported since core i7. I'm also not sure that compiler is clever enough to replace string loops with `PcmpIstrI`. glibc makes weak aliases and uses fastest possible variant on the fly.

> Why not produce a real benchmark that is not naive? ;-)

Using 1.6G wikipedia xml database as a source showed [very different results](https://gist.github.com/scriptum/7cb226ee0da568f96f26). Also in general memmem is slower than strstr. But find(char) vs memchr is still under question.

**Comment by Araq** [comment]
> Using 1.6G wikipedia xml database as a source showed very different results.

Interesting, so not consistently faster. Closing.
