### ISSUE TITLE
Linux: readLineFromStdin calls quit(0) upon EOF

### ISSUE THREAD

**Issue by uuwaan** [nim-lang/Nim#3159]
``readLineFromStdin`` proc of ``rdstdin`` module does the same job as Python's ``input``. When ``input`` gets EOF (``^D`` was pressed in terminal), it raises EOFError. ``readLineFromStdin`` does ``quit(0)``. Why is it so? Maybe, it should raise IOError instead?

**Comment by dom96** [comment]
Agreed. There should really be an EOFError too.

**Comment by Araq** [comment]
Nim has no ``EOFError``.

**Comment by dom96** [comment]
Maybe it should have one?
