### ISSUE TITLE
debian mipsel build issues

### ISSUE THREAD

**Issue by aborrero** [nim-lang/Nim#3162]
Hi!

nim was recently added to Debian. However, it fails to build from source in the mipsel arch [0].

This is the offending part:
```
[...]
/usr/bin/make -f makefile LDFLAGS="-ldl -lm" \
  myos=linux mycpu=unsupported:mipsel
make[2]: Entering directory '/«BUILDDIR»/nim-0.11.2+dfsg1'
Error: no C code generated for: [linux: unsupported:mipsel]
[...]
```

Do you have any idea about how to solve the issue?
thanks

[0] https://buildd.debian.org/status/fetch.php?pkg=nim&arch=mipsel&ver=0.11.2%2Bdfsg1-2&stamp=1438296591

**Comment by dom96** [comment]
Is MIPS equivalent to MIPSel?

**Comment by aborrero** [comment]
On 31 July 2015 at 22:19, Dominik Picheta <notifications@github.com> wrote:

> Is MIPS equivalent to MIPSel?
>

No, AFAIK they are different arches in regards to endianess (at least).

-- 
Arturo Borrero González

**Comment by infinity0** [comment]
Hi, Nim does not officially support mipsel, as can be seen by compiler/platforms.nim. I didn't explicitly disable this in the Debian package, but I guess I should do that so as to not confuse people.

**Comment by infinity0** [comment]
Although it would be interesting to add 

~~~~
    (name: "mipsel", intSize: 32, endian: littleEndian, floatSize: 64, bit: 32),
~~~~

and see if it works. I don't have a mipsel machine to test on, though. Perhaps you do?

**Comment by aborrero** [comment]
Yes, I can do test in my local mispel machine if you kindly provide me a
patch.

**Comment by infinity0** [comment]
I don't have time or knowledge to provide a patch for this I'm afraid. I don't know if the Nim upstream authors have time to try this either. So if you want this done, the best option is to spend your own time doing it.

**Comment by def-** [comment]
@aborrero Is this PR fine or do you want a patch file? https://github.com/nim-lang/Nim/pull/3163/files

**Comment by infinity0** [comment]
Ah, nice! If it's not too much effort, could you guys do the same for `powerpc64el` and `arm64`? Here are all the failing builds, feel free to write patches for anything that you think might work, and I can have the Debian build machines try to build these automatically too:

https://buildd.debian.org/status/package.php?p=nim
http://buildd.debian-ports.org/status/package.php?p=nim&suite=sid

I don't think we need a separate patch for `kfreebsd-*` - I have actually managed to get it building on a personal VM, even though the build daemons are failing, so I can investigate that separately.

**Comment by aborrero** [comment]
@def- the patch seems to fail:

```
[...]
make[1]: Entering directory '/tmp/buildd/nim-0.11.2+dfsg1'
/usr/bin/make -f makefile LDFLAGS="-ldl -lm" \
  myos=linux mycpu=unsupported:mipsel
make[2]: Entering directory '/tmp/buildd/nim-0.11.2+dfsg1'
Error: no C code generated for: [linux: unsupported:mipsel]
makefile:323: recipe for target '.check-arch' failed
make[2]: *** [.check-arch] Error 1
[...]
```

This is: the same previous issue. Am I doing something wrong?

**Comment by infinity0** [comment]
@aborrero you need to generate csources for mipsel, which you can do by cross-compiling from nim on another architecture. for the official debian package, i'm waiting for the next release which will hopefully include that.
