### ISSUE TITLE
FreeBSD compiler fails parallel builds

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#3165]
See e.g. https://buildd.debian.org/status/fetch.php?pkg=nim&arch=kfreebsd-amd64&ver=0.11.2%2Bdfsg1-2&stamp=1438295991 (using gcc) and http://buildbot.nim-lang.org/builders/freebsd-x64-builder/builds/574/steps/Compile%20Koch/logs/stdio (using clang)

Giving `--parallelBuild:1` works around the build failure in both cases, but this is probably not the best solution.

**Comment by jfhg** [comment]
This might be fixed now with commit 57c4e78bccfb60b584259e8daa9e4025116fd28c
I was seeing similar linking issues on Dragonfly BSD before that commit.

**Comment by Araq** [comment]
Fixed.
