### ISSUE TITLE
Illegal capture inside template

### ISSUE THREAD

**Issue by skyfex** [nim-lang/Nim#3173]
This code fails

```nim
var foo = 3

template newDataWindow(gnatInput: expr): expr =
    let data = gnatInput  
    let eventClosure = proc (): bool {.closure,cdecl.} =
        echo data
    0

proc wrapper() =
    var window = newDataWindow(foo)

wrapper()
```

With error message

```
test.nim(83, 13) Error: illegal capture 'data'
```

If I don't use a template, I don't get this error.

**Comment by Araq** [comment]
This is not a bug. ``cdecl`` overrides the ``closure`` calling convention and so you are not allowed to capture anything. It compiles when I remove the ``cdecl``.
