### ISSUE TITLE
Calling pointer to proc gives confusing error message

### ISSUE THREAD

**Issue by skyfex** [nim-lang/Nim#3181]
``` nim
proc foo[T](p: ptr T) =
    p()

var bar = proc () =
    echo "Hello"

foo(addr(bar))
```

This gives error `Error: undeclared identifier: 'p'`

Changing to `p[]()` works. Would perhaps be nice if `p()` would work too.

Incidentally (not sure if this is a issue), I can't change `var bar = proc ..` into `proc bar ..`. If I do that I get "Error: expression has no address". I tried adding procvar-pragma, but that didn't change it.

**Comment by Araq** [comment]
Not sure if there is any bug here. For proc pointers, use proc, not ptr proc.

**Comment by Araq** [comment]
Now fails with "Error: attempting to call undeclared routine: 'p'".
