### ISSUE TITLE
Get rid of the "pragmas are only allowed in the header of a proc" error

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3182]
This error stops me from forward declaring async procedures.

Workaround for async procs:

```nim
proc forward(): Future[T] = ...

async:
  proc forward() = 
    await foobar()
```

**Comment by Araq** [comment]
Already reported by you.

**Comment by dom96** [comment]
Where?

**Comment by dom96** [comment]
I'm going to keep this open until you or I can find where else I reported this.

**Comment by Araq** [comment]
duplicate of #1970.
