### ISSUE TITLE
Call to `createU` fails to compile

### ISSUE THREAD

**Issue by ziotom78** [nim-lang/Nim#3193]
The following program fails to compile with the latest `devel` branch:

`````nim
var x = createU(int, 3)
free(x)
`````

The error message is:
`````
test.nim(1, 16) template/generic instantiation from here
lib/system.nim(1488, 26) Error: type mismatch: got (typedesc[int])
but expected one of: 
system.sizeof(x: T)
`````

**Comment by dom96** [comment]
Caused by #3180?

**Comment by ziotom78** [comment]
Thanks for the update. Unfortunately, if I run `git pull` in the base Nim directory and then run `sh ./bootstrap.sh`, now `koch` fails to compile:

`````
lib/system/alloc.nim(328, 53) Error: ambiguous call; both system.sizeof(x: typedesc) and system.sizeof(x: T) match for: (typedesc[SmallChunk])
`````

Should I open a new issue, or stay with this one?
