### ISSUE TITLE
Unable to assign array of Child ref objects to array of Parent type

### ISSUE THREAD

**Issue by Perelandric** [nim-lang/Nim#3194]
Can't pass or assign array of child ref objects to a type defined as holding its parent ref object type (unless manual conversion is done).

```
type
  Parent = ref object of RootObject
    a: string
  Child = ref object of Parent
    b: string

proc arrPar(o: openarray[Parent]) =
  discard

var child = Child(a: "a", b: "b")

arrPar([child]) # fails
arrPar([child.Parent]) # works with manual conversion to parent
```

Works if it's not in an array.
```
var p: Parent = child
```

Is this intended? Would be more convenient to not have to do the manual conversion.

**Comment by def-** [comment]
Note that you only have to manually convert the first element of the array, as this determines the type of the entire array.

**Comment by Perelandric** [comment]
Thanks @def-, good to know, though it still makes for a clumsy API.

**Comment by Araq** [comment]
> Is this intended? Would be more convenient to not have to do the manual conversion.

Yes, the subtype relation is not lifted to arrays nor would that be sound. I wish I would get a dollar everytime this question comes up.

**Comment by Perelandric** [comment]
Thanks for the info @Araq. I searched here and in the forum but nothing came up. Must be using the wrong search terms.
