### ISSUE TITLE
Auto parametes in procs

### ISSUE THREAD

**Issue by petermora** [nim-lang/Nim#3224]
Hi,

The following code compiles and works as excepted:
```nim
proc f(x: auto): auto =
  result = x+10

echo f(0)     # prints 10
echo f(0.0)  # prints 10.0
```
However if I change the return type, then it fails to compile:
```nim
proc f(x: auto): auto =
  result = $(x+10)

echo f(0)     # fails to compile
echo f(0.0)  # fails to compile
```
By the way, it works with generics (``proc f[T,S](x: T): S =...``).
Thank you for checking,
 Peter

**Comment by petermora** [comment]
It looks like all the ``auto`` keywords resolves to the same type (like ``f[T](x: T): T`` instead of ``f[T,S)(x: T): S``). The ``auto`` nodes' ``.sym.typ.sym.name.id`` is the same number in ``semProcTypeNode(...)``, my guess is that this is the problem. However, I don't know how to fix this, I couldn't locate where the ``auto/expr`` keyword is parsed and the ``id`` is generated.

**Comment by Araq** [comment]
In compiler/semtypes.nim  iirc. 'auto' is mapped to 'tyExpr' for historical reasons...
