### ISSUE TITLE
Extending Tags and Effects

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3226]
Extends tags and effects so then can:
1. have compile time predicates associated with tme
2. have compile time values associated with them

**Comment by sirinath** [comment]
The tags and effects should be like Java, C# attributed. X10 language also has a effect system based on attributes which might be worth looking at.

**Comment by Araq** [comment]
Not before 1.0 is out. Also the benefts are unclear. ;-)

**Comment by sirinath** [comment]
You can use this to implement:

 1. code contracts
 2. proof carrying code
 3. constraint types (x10 language - http://x10.sourceforge.net/documentation/languagespec/x10-latest.pdf)
 4. extending type system (again see x10 annotations)
 5. form of dependent typing???

Code contracts can be implemented on its own also but the contract rules can be associated with the effect / tag system which can be verified later. This means the type system can become extensible and can carry proofs and metadata which might be helpful for the compiler to optimise.

I agree this needs investigation but I would like it for 1.0.
