### ISSUE TITLE
Compile time reference counting and constraints on references

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3227]
You can use the effets system to enforce and also tract compile time allocation and references to variable. You can use predicates to enforce use once or least once or at most once schematics. Also you can count how many references to a given value through the effect system. A new reference has the effect of increasing the reference count. This way you can achieve:
1. zero GC
2. better resource management
3. better optimisation: laziness, memorising, reduce computation
4. verification, code contracts

Ref: https://github.com/nim-lang/Nim/issues/3226

**Comment by Araq** [comment]
Yup, designing algorithms for this now. Do you have any papers I should look into?

**Comment by sirinath** [comment]
Not exactly but you can look at: https://en.wikipedia.org/wiki/Substructural_type_system, https://en.wikipedia.org/wiki/Effect_system, https://en.wikipedia.org/wiki/Affine_logic, http://research.microsoft.com/en-us/projects/dafny/ and similar topics.

**Comment by sirinath** [comment]
Some more refs: 
http://research.microsoft.com/apps/video/default.aspx?id=231575
http://research.microsoft.com/pubs/118791/tr.pdf
http://research.microsoft.com/en-us/projects/slayer/
http://msr-waypoint.com/pubs/73869/hedec.pdf

Mainly from MSR as it was easy for me to relocate them.

**Comment by sirinath** [comment]
Also you have https://www.rust-lang.org/ but I feel they have compramised flexibility and is too rigit of a language. Ideally you should aim to achieve the same without the extra pain.

**Comment by sirinath** [comment]
http://mmjb.github.io/T2/


Not related but interesting: http://leanprover.github.io/, https://github.com/epfl-lara/leon, http://ats-lang.sourceforge.net/ (http://www.ats-lang.org/, https://en.wikipedia.org/wiki/ATS_(programming_language) ),

**Comment by sirinath** [comment]
Languages this have this: ACL2, ATS, Rust, Dafny. Also interesting to look into C through through proofs and verification like in Mbeddr, Ada SPARK,

**Comment by sirinath** [comment]
Perhaps I missed out on: https://en.wikipedia.org/wiki/Uniqueness_type

**Comment by sirinath** [comment]
This might be also a good language to study for this purpose: https://en.wikipedia.org/wiki/ParaSail_(programming_language)
