### ISSUE TITLE
Issue parsing countup shortcut

### ISSUE THREAD

**Issue by Snowie** [nim-lang/Nim#3240]
I was playing around with nimkernel and the osdev articles, and came across something slightly odd,

I could run ```for i in 0..<len(someString):``` in the main file without issue. However, if I tried to do the same in a file imported, it would throw ```Error: undeclared identifier: '..<'``` unless I added spaces ```for i in 0 .. <len(someString)```

**Comment by Araq** [comment]
I use ..< all the time. However, old versions of Nim don't support ..< without the space. Maybe that's the issue? Some old installation screwing things up?

**Comment by Snowie** [comment]
Ah, clarify old? nim --version gives me
```
Nim Compiler Version 0.11.2 (2015-05-05) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: fd7b7a0bc1e2572648ade1f68e63db3dcd5655b7
```

**Comment by Araq** [comment]
0.11.2 has it. Can you post your code?

**Comment by Snowie** [comment]
Yeah, it works here: https://github.com/Snowie/Mero/blob/master/kernel.nim but complains without spaces here: https://github.com/Snowie/Mero/blob/master/tty.nim#L43

**Comment by Araq** [comment]
tty is imported by panicoverride which is included by system.nim, the definition of system.nim comes later and so in tty it's not yet known.

**Comment by Snowie** [comment]
Oh. Well, that makes me feel a bit daft. Thanks ^^;

**Comment by Araq** [comment]
You can move around the definitions in system.nim and create a PR if you feel like it.
