### ISSUE TITLE
Problem with unicode file names in Windows

### ISSUE THREAD

**Issue by SharplEr** [nim-lang/Nim#3241]
I have problem with unicode file names in Windows 10. For Example if i will write
**echo os.splitFile(r"greetings.nim").dir**
then result will be like: "**C:\РљРѕРґ\greetings.nim**", but real name of this file is "**C:\Код\greetings.nim**". But when I am reading line from console all is ok.

And one more thing Aporia can't open file with unicode name. Aporia is using "**os.splitFile().dir**" in source code for get full name and this is reason why I included this information in issue.

P.S. Windows command line encoding is "**DOS 866**" by default. Perhaps this is important.

**Comment by strcmp** [comment]
maybe https://github.com/nim-lang/Nim/pull/3231 helps fix it?

**Comment by jangko** [comment]
this is a bit strange. even without #3231, os.nim is capable of handling Code Page 866 correctly

**Comment by reactormonk** [comment]
@jangko write tests, we have buildbots.

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/tos.nim

**Comment by jangko** [comment]
great, now write a test for 1,112,064 characters of UTF-16 and UTF-8 for ~~each~~ many procs/iterators in os.nim...

**Comment by SharplEr** [comment]
Hm... #3231 didn't help. I realized what the problem is that the echo function displays information in the same encoding, in which the source file was saved. But os.nim functions don't take into account encoding of windows console or source file, and work only in UTF 8. So if user will input no utf 8 name of file (from console) then os.nim will not find it, and if program will display utf-8 file name then user will receive "РљРѕРґ".

**Comment by Araq** [comment]
So? Are we responsible for Windows' unusable console character handling now too? Use encodings.nim to convert between character sets.

**Comment by Varriount** [comment]
Well, at least on Windows, echo could try to convert a strong to the console encoding. What do python and ruby do?

**Comment by SharplEr** [comment]
This is a philosophical question. I think if Nim forces programmers to monitor the encoding in such trivial cases, it will generate a lot of compatibility issues (Aporia can't open file with unicode symbols in path, for example). And people will write their platform independent IO functions. But that's just my opinion.

**Comment by Araq** [comment]
> I think if Nim forces programmers to monitor the encoding in such trivial cases, it will generate a lot of compatibility issues (Aporia can't open file with unicode symbols in path on Windows, for example).

No, Nim uses UTF-8 and converts to Windows' UTF-16 format to avoid these problems. That Aporia cannot open such files is news to me, please report this properly. However, Windows itself uses a totally different encoding for its console and **that** is not our problem. I also know of no other language runtime that tries to deal with this mess.

**Comment by Varriount** [comment]
@Araq Um, Python does. My last comment contained a link exhibiting this behavior in Python.

As a general purpose output function, echo should really try to do the right thing. I don't want to have to fiddle with encodings to print things out properly on Windows.

**Comment by Araq** [comment]
@Varriount Well output can be re-directed and for example our readPassword proc already doesn't work on git's console. In my opinion people should simply set the console's encoding to UTF-8 or to whatever works.

**Comment by Araq** [comment]
Closed until somebody can explain to me where we actually have a real bug. (Aporia has its own bug tracker.)
