### ISSUE TITLE
Don't require comma with multiline import

### ISSUE THREAD

**Issue by baabelfish** [nim-lang/Nim#3249]
I feel that requiring commas in this context is a bit inconsistent with the rest of the language when comparing to other similar-looking statements.

```
import
    strutils,
    sequtils,
    tables
```

Compared to

```
let
    x = 1337
    y = 42

type
    X = enum
        Hello
        World
    Obj = object
        x: int
        y: string
```

This might also apply to some other keywords like `include`.

**Comment by Araq** [comment]
I don't mind optional commas for this. But then I would never use a whole line per import either, wastes space.

**Comment by Araq** [comment]
But ``import`` does not introduce a section. People want "one true way to do everything" now.

**Comment by arnetheduck** [comment]
aww.. I was still hoping for this to happen.. organizing imports would be so much easier without mandatory commas...
