### ISSUE TITLE
Extend Distint Types for Type Rebasing

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3254]
In type rebasing you create a new type hierarchy with all the features copied from the hierarchy you are rebasing off. This is equivalent to a new type definition with all the features of the type you are rebasing off, hence this will not be a sub type of the type you rebase off.

**Comment by Varriount** [comment]
So.. How is this different from distinct types + the borrow pragma?

**Comment by sirinath** [comment]
You need a borrow all

**Comment by dom96** [comment]
So essentially:

```nim
type
 NewType = OldType
```
?

**Comment by sirinath** [comment]
I am still new to Nim. Does the above create an alias for OltType? Ideally this is what it should be doing in the above case not rebasing the type hierarchy.

**Comment by dom96** [comment]
Yes

**Comment by sirinath** [comment]
OK.

This has left be confused on how you alias and how to rebase. If not too much trouble can you give me a example? Initially distinct looked like a rebase but was not sure if there is an option copy all.

**Comment by Varriount** [comment]
Using the `type A = B` syntax creates what is essentially a type alias (Very much like using define in C/C++). Using `type A = distinct B` creates a new type "A" with the same structure as "B", but with no relation (And thus, no implicit conversion).

**Comment by sirinath** [comment]
OK Thanks.
