### ISSUE TITLE
Enforce Accessibility through Refinement Types in Similar Scheme to Effects and Tags with Ability to Define Shorthands

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3255]
The current way to define accessibility is through defining a type inheritable and using * to denote visibility. Visibility can also be part of the type extension mechanism as tags and  effects are type extensions. This will make more fine grain visibility constraints.

Also to maintain current compatibility you can define operators like * to alias (definable short hand) these refinements. Don't bake them into the language but define them in the standard library.

Ref: https://www.fstar-lang.org/, https://en.wikipedia.org/wiki/ACL2, https://en.wikipedia.org/wiki/ATS_(programming_language), http://x10-lang.org/

**Comment by Araq** [comment]
Well visibility has deliberately kept simple because in my opinion programmers shouldn't spend time on visibility. It's a fragile thing constantly changing ("hrm this helper is useful over here, so make it public").

**Comment by sirinath** [comment]
Sure this makes sense at the core language. But why have it at all baked into the language when you can have it through meta programming and effects system. This can be defined in a standard library. (Not in the current state but if you improve the type extensibility capabilities, i.e., effects and tags). Accessibility is nothing more than an effect.

**Comment by sirinath** [comment]
One advantage of this way to look at accessibility is you can enforce that only a open file you can close. If it is not open you cannot read and write. Etc. Have a look at Plaid Language (http://www.cs.cmu.edu/~aldrich/plaid/). Type state can be modeled through effects with accessibility. This is one example. For this kind of things to work you have to have the effects system being able to control accessibility.

**Comment by Araq** [comment]
> *But why have it at all baked into the language when you can have it through meta programming and effects system.*

Because we like to spend our complexity budget on other, much more important things.

**Comment by sirinath** [comment]
My thinking is make to metaprogramming and type (including effects system) solid and rich and then many  features can be implemented through this. This is one case. Even proc vs. method distinction can be captured in the effect system and metaprogramming system.

**Comment by Varriount** [comment]
It would help if you could give some examples of how you think this should be done (the syntax, etc). Saying you want aop is all well and good, however it doesn't give much insight into *How* you want it done.

**Comment by sirinath** [comment]
Something like:

```
type @grammer(TProc) {. resolution(method = static) .}
```

matchers part of the grammar

```
type @asst.term(abc) {. xyz .}
```

matchers ast term
