### ISSUE TITLE
Document Generics, Flow Typing and Variant and their Interaction, Equivalence and Sub Typing

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3256]
This is something that needs to be documented. E.g. T1[G1] + T1[G2] == T1[G1 + G2]. Not been documented makes makes you wonder these interactions hold and whether the language is sound with regard to these interaction. These should be speced out and then tested to see if their behaviour is sound and to spec.

See: http://www.cs.cornell.edu/~ross/, http://ceylon-lang.org/, 

Also interesting: https://www.youtube.com/watch?v=2IhT8HACc2E&index=20&list=PLX8CzqL3ArzUo2dtMurvpUTAaujPMeuuU, http://www.oracle.com/technetwork/java/jvmls2015-breslav-2637899.pdf

**Comment by Araq** [comment]
It's a very valid point, but what do you mean with:  T1[G1] + T1[G2] == T1[G1 + G2].  What's your "+" here?

**Comment by sirinath** [comment]
Type union.

**Comment by Araq** [comment]
We don't have "type unions" and also the spec improved. Closing.
