### ISSUE TITLE
AOP like mass Application of Pragma, Tags, Effects

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3257]
Is it possible add AOP like features which can query and attach Pragma, Tags, Effects at matching points.

Should be very succinct so you can specify if you want to borrow all, operators, all methods, methods defined in the previous level, methods defined between n..m levels, etc. Also see: https://github.com/nim-lang/Nim/issues/3254

Ideally so the underlying features can be reused in meta programming make the underlying implementation querying the CS/TST/AST

**Comment by Varriount** [comment]
Could you explain a bit about what this entails, and what the syntax would be like?

**Comment by sirinath** [comment]
I thinks the best would be to see what other languages to and adopt it to Nim. https://en.wikipedia.org/wiki/Aspect-oriented_programming, https://en.wikipedia.org/w/index.php?title=Feature-oriented_programming&redirect=no

In the case of Nim it is best to implement them through extending the macro and template feature.

**Comment by Araq** [comment]
This can already be accomplished by  {.push myMacro.}

**Comment by Araq** [comment]
We need feature requests that have some connection to reality.
