### ISSUE TITLE
Installer: error: size of array 'assert_numbits' is negative

### ISSUE THREAD

**Issue by artemonster** [nim-lang/Nim#3258]
I've installed an official win x64 distributive (I also have MingW on my path and I am using Win10) and I get this error, when I try to compile even simple programs, like "nim c hallo.nim"
I've looked around to find similar issues, but they are all related to people, who try to compile nim from scratch. And I am sitting here, trying to use official distributive.

**Comment by kirbyfan64** [comment]
What's the full error message?

**Comment by Varriount** [comment]
Your mingw compiler and your Nim compiler are trying to compile for different architectures. The 64-bit Nim compiler expects a compiler that outputs 64-bit executables to be present on the path.

**Comment by artemonster** [comment]
Full message:
C:\Nim\lib/nimbase.h:393:13: error: size of array 'assert_numbits' is negative
C t:\Nim\lib/ypedef int assert_numbits[sizeof(NI) == sizeof(void*) && NInM_INiTB
ITS == sizeof(NI)*8 ? 1 : -1];
             ^
mbase.h:393:13: error: size of array 'assert_numbits' is negative
 typedef int assert_numbits[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof
(NI)*8 ? 1 : -1];
             ^
Error:  execution of an external program failed; rerun with --parallelBuild:1 to
 see the error message
---
I have mingw for 64 bit system. I've removed my mingw installation from PATH and used one provided with the installer. Now it works.

**Comment by FedericoCeratto** [comment]
A more informative error message would be  useful.

**Comment by Araq** [comment]
How can we influence the C compiler's error message? There is a limit to what we can do.

**Comment by ljani** [comment]
I agree the message is very confusing. If anyone ends up here from Google, for `vcc` (Visual Studio 2015) this error message is `nimbase.h(412): error C2118: negative subscript`.
