### ISSUE TITLE
Have installer run a test verifying correct compiler is installed.

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#3259]
If not installing its own version of Mingw, the Nim installer should check that a C compiler can be invoked, and if so, that the Nim compiler can actually compile a simple Nim program.
If one of the checks fails, the installer should warn the user.

**Comment by Araq** [comment]
Rather than hacking this into the NSIS based installer, write a Nim program that's invoked after installation that checks for this.

**Comment by Araq** [comment]
``finish.exe`` now exists.
