### ISSUE TITLE
Procedure redis.eval?

### ISSUE THREAD

**Issue by Moixll** [nim-lang/Nim#3260]
[EVAL script numkeys key [key ...] arg [arg ...]](http://redis.io/commands/EVAL)

redis.nim:
```
proc eval*(r: Redis, code: string, args: varargs[string]): RedisString =
  r.sendCommand("EVAL", code, args)
  return r.readSingleString()
```
Use:
```
echo r.eval("return cjson.encode({a=1,b=2,c=3})", $0)

> {"a":1,"c":3,"b":2}
```

**Comment by dom96** [comment]
I think ``redis`` is up for being removed from the stdlib and placed in a nimble package. In fact, it's right here: https://github.com/nim-lang/redis

It will be removed in the next version.

Could you create a PR to add that function to the redis repo that I linked? :)

**Comment by dom96** [comment]
Closing due to lack of feedback.
