### ISSUE TITLE
Unexpected readLine behavior

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#3263]
stream.readLine on an already allocated string unexpectedly inserts a "\0":

```Nim
var line = "" 
discard stdin.readLine(line) 
echo "len: ", line.len 
echo repr line 
echo "->", line, "<-"
```

```Bash
12345678901234567890
len: 21
0x7f30fda30050"123456\078901234567890"    # \0 after the "6"
->123456<-
```

**Comment by kirbyfan64** [comment]
Is this really surprising? It's what C and C++ do.

**Comment by rbehrends** [comment]
Proposed fix is [here](https://github.com/nim-lang/Nim/pull/3266). Could use some additional testing.

**Comment by Araq** [comment]
Fix has been applied.
