### ISSUE TITLE
Compilation of proc match(debug: static[bool]; str: string) fails if it contains type enum

### ISSUE THREAD

**Issue by Henry** [nim-lang/Nim#3268]
Compiling the following:

    proc match(debug: static[bool]; str: string) =
      type state = enum found, fail
      echo str

generates the message:

    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

If the `type` is removed or moved outside `match` it compiles.

Testing with the current Nim from github and no option complied with 

    koch boot -d:release

If the compiler is built without options the error message generated is:

    Traceback (most recent call last)
    nim.nim(104)             nim
    nim.nim(68)              handleCmdLine
    main.nim(251)            mainCommand
    main.nim(63)             commandCompileToC
    modules.nim(214)         compileProject
    modules.nim(162)         compileModule
    passes.nim(203)          processModule
    passes.nim(137)          processTopLevelStmt
    sem.nim(458)             myProcess
    sem.nim(432)             semStmtAndGenerateGenerics
    semstmts.nim(1465)       semStmt
    semexprs.nim(907)        semExprNoType
    semexprs.nim(2247)       semExpr
    semstmts.nim(1262)       semProc
    semstmts.nim(1205)       semProcAux
    semgnrc.nim(405)         semGenericStmt
    semgnrc.nim(400)         semGenericStmt
    semgnrc.nim(349)         semGenericStmt
    semgnrc.nim(360)         semGenericStmt
    system.nim(2431)         sysFatal
    Error: unhandled exception: sons is not accessible [FieldError]

**Comment by dom96** [comment]
Forum discussion for reference: http://forum.nim-lang.org/t/1585

**Comment by Henry** [comment]
Works perfectly, thanks for the fix.
