### ISSUE TITLE
FileLogger not flushing

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#3269]
By default logging.FileLogger does not flush the file buffer, buffering log messages for a potentially long time.
Passing bufSize=0 to newFileLogger mitigates the problem.
(Oddly, when passing bufSize=1 messages are still cached)

```Nim
import logging 
import os 
 newFileLogger("/tmp/status.log", fmtStr = verboseFmtStr).addHandler 
debug("hi") 
os.sleep(30000) 
debug("bye") 
```

**Comment by dom96** [comment]
We need a ``BufferSettings`` enum for ``newFileLogger``

**Comment by Araq** [comment]
I fixed this, errors and fatals now flush. Also access to the underlying flie object is now available, so flush whenever you feel like it.
