### ISSUE TITLE
internal error: for statement not eliminated

### ISSUE THREAD

**Issue by rbmz** [nim-lang/Nim#3275]
```Nim
type expr = object
  sons: seq[expr]

method `$`(e: expr): string =
  for i in 0..<10:
    result &= $e.sons[i]
```
```text
bug.nim(5, 3) Error: internal error: for statement not eliminated
Traceback (most recent call last)
nim.nim(104)             nim
nim.nim(68)              handleCmdLine
main.nim(251)            mainCommand
main.nim(63)             commandCompileToC
modules.nim(214)         compileProject
modules.nim(162)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1217)           myProcess
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2070)       expr
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2134)       expr
cgen.nim(787)            genProc
cgen.nim(757)            genProcNoForward
cgen.nim(677)            genProcAux
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2070)       expr
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2091)       expr
msgs.nim(962)            internalError
msgs.nim(936)            liMessage
msgs.nim(801)            handleError
```

**Comment by rbmz** [comment]
It's not specific to \`$\`. Recursive methods don't like for loops (even when they don't make the recursive call in the body).

**Comment by rbmz** [comment]
changing for to if:
Error: internal error: getTypeDescAux(tyEmpty)

**Comment by jangko** [comment]
i don't have any problem with the code above, could you supply your compiler and OS version?

**Comment by rbmz** [comment]
Nim Compiler Version 0.11.3 (2015-08-31) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 0e2a798af4ea210288cd85cde0373a3f13cc8025
active boot switches: -d:release

**Comment by rbmz** [comment]
Bootstrapped nim again and it got fixed. Thanks

**Comment by mildred** [comment]
Got this bug with nim 1.2.0 (js backend):
https://github.com/mildred/nim-svelte/commit/d1f30d00c5be0140fb9fcc0ee8130f2c67d661c7

When trying to replace an `items()` call which comes from a mixin in a template procedure with a first-class iterator value coming from an object.

edit: It seems to be instead: https://github.com/nim-lang/Nim/issues/9738
