### ISSUE TITLE
TR template to optimize slice comparison fails to substitute

### ISSUE THREAD

**Issue by Henry** [nim-lang/Nim#3276]
I am trying to optimize string slice comparison using a TR template but it is
not being applied as expected. I have tried using `Slice[Natural]` as a type and
also explicitly including the `..` operator in the expression. Here is a simple
example to demonstrate the problem:

```
let str = "Hello World"

template sliceCmpOpt*{s1[r] == s2}(s1: string; r: Slice[Natural]; s2: string): bool =
  echo "Should be here"
  false

if str[1..3] == "ell":
  echo "Should not be here"
```

Alternatively:

```
template sliceCmpOpt*{s1[l..h] == s2}(s1: string; l,h: Natural; s2: string): bool =
  echo "Should be here"
  false
```

neither work.

Forum discussion: http://forum.nim-lang.org/t/1595

**Comment by Araq** [comment]
Workaround:

```nim

let str = "Hello World"

template sliceCmpOpt*{`[]`(s1, r) == s2}(s1: string; r: Slice[int]; s2: string): bool =
  echo "Should be here"
  false

if str[1..3] == "ell":
  echo "Should not be here"
```

**Comment by Henry** [comment]
Treat the operator as a function, of course!  I didn't try that option.

Given that the string indexing cannot be negative I assumed `Natural` is the correct integer type for the `Slice`; does it need to be `int`?

**Comment by Araq** [comment]
Well it's infered as int for these literals and the type checking for TR macros leaves quite a lot to be desired. Btw TR macros are currently under developed as not many people use them but also the implementation is quite simple (compiler/patters.nim). Please help to make this feature more polished.

**Comment by Henry** [comment]
In my use case the range limits will be of type `Natural` so I may need to create two of these templates, one for `int` and another for `Natural`, I will play around and see how it goes.

The TR macros are THE feature which brought me to Nim, I think the concept is excellent!  However, I need alot from them for my application and will be stressing the implementation.

> Please help to make this feature more polished.

For the moment I will only be able to provide tests and bug-reports but as my knowledge of Nim grows I hope to be able to fix bugs as well.  This will take time....

**Comment by Araq** [comment]
Since then I know how to make TR macros much better but this won't happen in 2020.
