### ISSUE TITLE
Tuples without names

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3277]
Allow tuple declaration without having names such that tuple with names are a sub type of tuples without names.

**Comment by Varriount** [comment]
Why is this needed? We already have anonymous tuple construction.

**Comment by sirinath** [comment]
Because 2 tuples with the same types but different names are distinct.

**Comment by Varriount** [comment]
I still don't see that as the correct solution to this particular problem. What would be more flexible is to change the rules regarding explicit object conversions so that a converter can be used.

**Comment by sirinath** [comment]
Converters do not play well with typing. How I see names are that they are structural typing constraints on the object. Without names is without the structural typing contains. Current tuple looks more like a object with structural typing discipline.

**Comment by Araq** [comment]
We already have that.
