### ISSUE TITLE
Tuple / Object distinction

### ISSUE THREAD

**Issue by sirinath** [nim-lang/Nim#3278]
Tuples and objects seam so similar that perhaps these need rethinking and perhaps partly merging with the distinction being in typing discipline.

I suggest to make the distinguishing based on structural and nominative typing while objects and tuples both being functionally same.

Everything can be public by default but with a pragma / effect applicable on all objects. This can be define in the standard library so existing schematics for visibility will not change but can be overridden in user libraries also.

**Comment by Varriount** [comment]
If you want structural type equivalency, use converter procedures and conversion/casting.

**Comment by sirinath** [comment]
Casting and conversions breaks the guarantees and benefits afforded by the typing system and discipline.

**Comment by Varriount** [comment]
And changing the rules of implicit conversion to convert types which are structurally equivalent doesn't?

**Comment by sirinath** [comment]
Main thing that one can choose the discipline applicable at a given context. There should be no implicit conversions that violate Liskov Substitution Principle (LSP). Since nominative is more constrained than structural you can design a type system where such conversions are possible.

**Comment by Araq** [comment]
> *I suggest to make the distinguishing based on structural and nominative typing while objects and tuples both being functionally same.*

That's already the case except that ``object``  also supports inheritance and ``case objects`` which would be very hard to support in a non-nominal context.
