### ISSUE TITLE
cas bug in atomics.nim

### ISSUE THREAD

**Issue by rogercloud** [nim-lang/Nim#3279]
The cas proc windows version implementation seems not correct.
```Nim
  proc interlockedCompareExchange(p: pointer; exchange, comparand: int): int
    {.importc: "InterlockedCompareExchange", header: "<windows.h>", cdecl.}

  proc cas*[T: bool|int|ptr](p: ptr T; oldValue, newValue: T): bool =
    interlockedCompareExchange(p, cast[int](newValue), cast[int](oldValue)) != 0
```

According to [InterlockedCompareExchange doc](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683560(v=vs.85).aspx), there're two issues there.

+ interlockedCompareExchange's return value is **initial value of the Destination parameter**, which is *p*'s origin content while cas operation is processing. If cas success, the return value equals to oldValue, otherwise not equal. So implementation should be like this:

```Nim
  proc interlockedCompareExchange(p: pointer; exchange, comparand: int): int
    {.importc: "InterlockedCompareExchange", header: "<windows.h>", cdecl.}

  proc cas*[T: bool|int|ptr](p: ptr T; oldValue, newValue: T): bool =
    interlockedCompareExchange(p, cast[int](newValue), cast[int](oldValue)) == oldValue
```

+  **The parameters for this function must be aligned on a 32-bit boundary**, maybe there's some mechanism in compiler to force it, but I cannot see from the code. As [issue 1930](https://github.com/nim-lang/Nim/issues/1930) is still open, I think we'd better mark it high priority.

Because this proc is used in threadpool to implement spawn, I guess some spawn related bugs are caused by this, for example [issue 2704](https://github.com/nim-lang/Nim/issues/2704)

**Comment by Araq** [comment]
We really shouldn't use interlockedCompareExchange at all.

**Comment by rogercloud** [comment]
@Araq what's the option other than interlockedCompareExchange? I think it works after forcing 32bit aligned.

**Comment by Araq** [comment]
Using the new C++11 atomics stuff.
