### ISSUE TITLE
tyVar include base type for optEndb

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3302]
When debugging (`--debugger:endb`) extend the `PNimType` info for abstract types like `tyVar` to include the base type

**Comment by Araq** [comment]
PR? Come on, it's not hard.

**Comment by jlp765** [comment]
I don't have a wand to do this type of magic  :-) .  
Playing in the compiler is waaay beyond me.

**Comment by reactormonk** [comment]
@jip765 Don't worry, it's not that hard.

**Comment by Araq** [comment]
The embedded debugger is deprecated.

**Comment by Araq** [comment]
> Let's improve it.

It's fundamentally doomed to introduce heisenbugs everywhere. It won't ever be useful to debug non-toy programs that involve threading, async, etc.
