### ISSUE TITLE
Could asynchttpserver export processClient?

### ISSUE THREAD

**Issue by tulayang** [nim-lang/Nim#3324]
Hi, I am writting something to transfer client sockets between multiprocess via Unix domain IPC. I found `asynchttpserver.processClient` very useful, but `asynchttpserver.serve` is not. I need a custom `serve`.

Could `asynchttpserver` export `processClient` via `*`?

**Comment by dom96** [comment]
Why do you need to process the clients manually?

**Comment by tulayang** [comment]
@ dom96 

I need to call processClient, my code like this:

```
if existsEnv("ASYNC_CLUSTER"):  ## multi instances mod
    var pipefd = paramStr(1).parseInt().AsyncFD()  ## a socketpair fd from argv
    var data = $port.int() & "\r\n" & address & "\r\n"  ## pass port and adress to master process
    await pipefd.send(data, {}) 
    recvAlways(oneCallback)  ## "accept" fd from master process, call  processClient                                
else:  ## single instance mod
    bindAddr()
    listen()
    appcetAddr()
    ...
```

When used  multi instances (processes) mod, I need to pass client descroptor to child process, then the child will call `processClient`.

**Comment by dom96** [comment]
I still don't understand why ``serve`` doesn't suffice.

**Comment by Araq** [comment]
This is finally possible and will also be backported.
