### ISSUE TITLE
db_mysql [likely others too] fails on dbFormat() with '?' in query without arguments.

### ISSUE THREAD

**Issue by Senketsu** [nim-lang/Nim#3328]
On: 'Nim Compiler Version 0.11.3 (2015-09-12) [Linux: amd64]'
Example: (for the sake of readability)
` getRow(sql("""SELECT * FROM text WHERE line LIKE '%%?%%'"""))`
Result:
```
db_mysql.nim(196)        getRow
db_mysql.nim(123)        rawExec
db_mysql.nim(108)        dbFormat
system.nim(2450)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```
Culprit:
```
proc dbFormat(formatstr: SqlQuery, args: varargs[string]): string =
  result = ""
  var a = 0
  for c in items(string(formatstr)):
    if c == '?':
      if args[a] == nil:
        add(result, "NULL")
      else:
        add(result, dbQuote(args[a]))
      inc(a)
    else:
      add(result, c)
```
Exactly on line:
` if args[a] == nil:`

About:
Lets say someone as stupid as me, used a prepared query to suply into getRow() in his proc
```
var newQuery: string = "SELECT * FROM text WHERE line LIKE '%%$1%%'" % queryArg
getRow(sql(newQuery))
```
instead doing this
```
var newArg: string = "%%$1%%" % queryArg
getRow(sql("""SELECT * FROM text WHERE line LIKE ?"""), newArg)
```
and the 'queryArg' happens to be/have '?'.

If the question mark got replaced by a `"NULL"` , that would be expected behaviour
(even tough unwanted in my case) but instead it just collapses on checking wether
varargs are nil.

**Comment by jlp765** [comment]
``echo myDb.getRow(sql"SELECT * FROM text WHERE line LIKE ?", "%%?%%")``
works for me, where I am assuming you are looking for the line column in table text to contain the substring "%?%" 
e.g. column line is something like ``"my line of text with the weird substring %?% in it"``

**Comment by Senketsu** [comment]
You are thinking on a completly wrong level here pal. I think i stated issue clearly enough.
Your assumptions are wrong(x2), im not looking for anything. Just pointing out an issue.

**Comment by Araq** [comment]
How is this a bug? You prefer random NULLs superior than the runtime telling you the number of passed args didn't match? o.O

**Comment by jlp765** [comment]
The documentation should be updated to reflect that a "?" in the sql query string requires an argument for substitution into the SqlQuery

Should dbFormat check for this exception, or is this better handled with an assertion, or leave it as it is?  
As it is, it doesn't provide very explicit information as to the root cause of the error

**Comment by Senketsu** [comment]
Nevermind guys, i apologize. I forgot to put in exception handling in my proc.
Lesson learner. Dont submit bug when you are tired. Get a good sleep first.

Sorry
