### ISSUE TITLE
json getNum() fails if input is Nil

### ISSUE THREAD

**Issue by mcdee** [nim-lang/Nim#3349]
Given that the docs for getNum state "Returns default if n is not a JInt" I would expect this to work:

    import json

    let data = parseJson("{\"present\":3}")

    let absent = getNum(data["absent"], 5)
    assert(absent == 5)

but instead there is a crash:

    Traceback (most recent call last)
    test.nim(5)              test
    json.nim(619)            getNum
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

There is no nil check in getNum (and similar procs).  Should they be changed to include a nil check, for example

    proc getNum*(n: JsonNode, default: BiggestInt = 0): BiggestInt =
      ## Retrieves the int value of a `JInt JsonNode`.
      ##
      ## Returns ``default`` if ``n`` is not a ``JInt``.
      if isNil(n) or n.kind != JInt: return default
      else: return n.num

**Comment by dom96** [comment]
Works in ``devel``.
