### ISSUE TITLE
a[b]=c has different lookup rules from `[]=`(a, b, c)

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3351]
When looking for overloads of `[]=` when used indirectly by `a[b]=c` compiler seems to ignore symbols from current module (this is similar to issue #1011).

main.nim:
```
import b

b.foo(5)
```
b.nim:
```
import tables

proc foo*[T](a: T) =
  var foo = initTable[T, T]()
  foo[5] = 3 # <- this doesn't work
  `[]=`(foo, 5, 3) # <- this works
```
(Note: `a[b]` operator is also affected)

**Comment by Araq** [comment]
This should finally have been fixed on devel.

**Comment by yglukhov** [comment]
Works for me on devel

**Comment by zielmicha** [comment]
Works on current devel (recently fixed?).

**Comment by kirbyfan64** [comment]
Issue was probably the one @dom96 mentioned [here](https://github.com/nim-lang/Nim/commit/29a91669667344e3637dbff4fc2009c263af3e11) and was fixed [here](https://github.com/nim-lang/Nim/commit/ba4dd92f457b9dd52fd6eddbd3f231b040750b60).
