### ISSUE TITLE
New version of Nim does not compile my code 

### ISSUE THREAD

**Issue by Dhertz** [nim-lang/Nim#3356]
After pulling from the HEAD of devel [my code](https://github.com/Dhertz/AkaPi/blob/master/main.nim) will no longer compile, citing an error in the system library. It compiles fine with commit  721324380dc753aa59efdcd2372b4c8a0e6a9252 but not at more recent commits.

Here is the error given by the compiler:
```
lib/pure/asyncdispatch.nim(163, 6) template/generic instantiation from here
lib/system.nim(182, 13) Error: invalid type: 'Future' in this context: 'proc (a: var ref Future:ObjectType){.noSideEffect.}'
```

**Comment by Araq** [comment]
Well it's kinda hard to fix when you do "include secrets" which your git repo lacks.

**Comment by Dhertz** [comment]
Sorry about that, the file contains private API keys and other secrets. Here is an overview:

secrets.nim
```nim
const
  FORECAST_IO_KEY     = "xxxxxxxxxxxxxxxxxxxxx"
  MBTA_KEY            = "xxxxxxxxxxxxxxxxxxxxx"
  purpleEmail         = "recipient@example.com"
  myEmail             = "sender@example.com"
  SMTPServer          = "smtp.example.com"
```
