### ISSUE TITLE
Compiler paths are relative to file being compiled not current dir

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3358]
This might be a duplicate but I can't find it right now.

``~/code/test/src/foo.nim``:
```nim
echo("foo")
```

``cd ~/code/test/ && nim c -o:foo src/foo.nim`` will not create a 'foo' binary in ``~/code/test/``, only ``cd ~/code/test/ && nim c -o:./../foo src/foo.nim`` will.

**Comment by Xe** [comment]
This is true for imports too.

**Comment by dom96** [comment]
I think for imports it makes sense.

**Comment by oderwat** [comment]
when using

```
examples/test.nim
examples/test.nims
src/mymod.nim
```

with `test.nim` containing

```
import mymod

echo "...."
```

and `test.nims` containing

```
switch("path", "../src")
```

you can `nim c -r test.nim` from the `examples` direcory but running it from project root with `nim c -r examples/test.nim` it will not find the import.

Is this related and qualifies as error or what has one to use in the config to make it work?

**Comment by Araq** [comment]
This has been fixed.
