### ISSUE TITLE
winlean for win 64bit requires Handle: int64

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3363]
64 bit windows requires a Handle as int64 (currently winlean has Handle:int)

This bug causes memfiles calling ``createFileA(): Handle`` to return -1 due to int64 to int32 mapping, which causes the file handle to be interpreted as INVALID_HANDLE_VALUE.

**Comment by Araq** [comment]
int is 64 bits on a 64 bit platform. The problem must lie somewhere else.

**Comment by jlp765** [comment]
Thanks.  Yes my mistake.  

The problem was with the parameters passed to createFileA().
``GENERIC_ALL`` is not the same as ``GENERIC_READ or GENERIC_WRITE``, and this was the cause of the invalid file handle.
