### ISSUE TITLE
Create a gitter room for Nim

### ISSUE THREAD

**Issue by rogercloud** [nim-lang/Nim#3365]
A place for contributors to discuss and ask questions. I know there's a forum, but gitter is faster way for short conversations. We can also pick some important conversations and doc them for later reference.

**Comment by dom96** [comment]
What about IRC? :)

**Comment by rogercloud** [comment]
Either one is good, just need a quick a question/answer channel. :)

**Comment by rogercloud** [comment]
I missed there's nim IRC channel, will close this issue.

**Comment by pyhedgehog** [comment]
IRC doesn't passes corporate firewalls well.

**Comment by reactormonk** [comment]
@pyhedgehog https://webchat.freenode.net/

**Comment by pyhedgehog** [comment]
@reactormonk Also gitter loads logs inplace after reload.

**Comment by dom96** [comment]
@pyhedgehog http://irclogs.nim-lang.org/

**Comment by dom96** [comment]
I created one anyway.
