### ISSUE TITLE
proc visibility inside another proc

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#3371]
the following code compile without error using ver 0.11.2, but devel-branch refuse to compile it

```nimrod
import sets, hashes

proc testDistinct() =
  type
    boat = distinct int
    
  proc hash(c: boat): THash =
    var h: THash = 0
    h = h !& int(c)
    result = !$ h
  
  proc `==`(a,b: boat): bool = int(a) == int(b)
  
  var x = initSet[boat]()
  x.incl(boat(88))
```

and the error message is:

```text
bughash.nim(15, 4) template/generic instantiation from here
lib\pure\collections\sets.nim(200, 21) template/generic instantiation from here
lib\pure\collections\sets.nim(142, 12) Error: type mismatch: got (boat)
but expected one of:
hashes.hash(x: T)
hashes.hash(x: set[A])
hashes.hash(x: openarray[A])
hashes.hash(x: string)
hashes.hash(x: pointer)
hashes.hash(x: float)
hashes.hash(x: int)
hashes.hash(x: char)
hashes.hash(x: int64)
hashes.hash(x: T)
hashes.hash(x: T)
```

if i move "hash" and `==` to outside testDistinct, the hash proc will be visible again
is this expected behavior of newest Nim? :disappointed:

**Comment by Araq** [comment]
Not sure, need to investigate.

**Comment by jangko** [comment]
i found this [commit](https://github.com/nim-lang/Nim/commit/35f8cc0bdde8e923eaca8830676f1b2ad6ffe300) responsible for the above behavior.
i don't really know how to fix it without breaking things

**Comment by Araq** [comment]
Ah yeah, thanks for the reminder. Your code is broken, sorry. ;-) You need to move the hash and == to a top level position.

**Comment by jangko** [comment]
thanks for the explanation. this is not a bug then.
