### ISSUE TITLE
repr shows invalid data in certain uint fields

### ISSUE THREAD

**Issue by Abrasax-** [nim-lang/Nim#3392]
```Nim
type Foo = object
  f: uint

let foo = Foo(f: 123)
echo(repr(foo))
```
Result: `[f = (invalid data!)]`
* * *
nim -v:
```Nim
Nim Compiler Version 0.11.3 (2015-09-18) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: d93c612067462919fb1bb6acf5cc384b7043c760
```

**Comment by Abrasax-** [comment]
Somewhat related to #3123

**Comment by jyelon** [comment]
The problem appears to be simple: there's a big case-statement inside of proc reprAux, in lib/system/repr.nim.  The uint32 and uint64 types are missing from the case-statement.  I tried adding them and now it works.

However, the code in this proc is a little weird: it's using $ze(x) for reasons I cannot fathom. I hesitate to make any modifications without understanding why it is the way it is.

These types are also missing from proc addSetElem in the same file.

**Comment by zielmicha** [comment]
The `$(ze(x))` is probably an artifact from times when `$(uint32)` was not in `system`. I've removed `ze` from these calls and it appears to work.

**Comment by dom96** [comment]
@zielmicha PR please?
