### ISSUE TITLE
Add `initTable` with support of openarray[] passing

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#3396]
Now it is possible to create new  _TableRef_ with literal, like this:
```nim
let x = {"1": 1}.newTable
```
But at the same time it is not possible to create _Table_ like this:
```nim
let x = {"1": 1}.initTable
```
The same is true for OrderedTable/-Ref, and you have to explicitly dereference created table in order to receive value:
```nim
let x = {"1": 1}.newTable[]
```

I propose to add overloaded `initTable` proc in order to avoid dereferencing, and create Table like in the second snippet above.

**Comment by jlp765** [comment]
Fixed in PR #3419

**Comment by Araq** [comment]
That was always available as ``toTable``... I don't see how adding more stuff helps when you already cannot see what you need, but I supposed we could deprecate toTable. toTable reads much nicer than initTable though.

**Comment by SSPkrolik** [comment]
@Araq, yes, my concern was to bring these into `cannonical` API where newSomething, and initSomething mark value/ref constructors, and I thought it will be more 'homogenous'... Anyway, that's not a critical issue for me.
