### ISSUE TITLE
shallowCopy of seq breaks after reallocation

### ISSUE THREAD

**Issue by petermora** [nim-lang/Nim#3409]
Hi,

 Currently ``shallowCopy`` can create a link between two sequences. This is good. However, this link breaks if one of the sequences is reallocated. If this is expected behavior, then feel free to close this issue.
 In Python the connection remains until one of the sequences is overwritten.

 Let's consider the following code. It can be read from this behavior that ``newSeq[int]()`` allocates 4 slots.

 Thanks,
  Peter
```nim
proc f() =
  var orig = newSeq[int]()
  orig.add 1
  var notDeepCopy: seq[int]
  shallowCopy(notDeepCopy, orig)
  echo orig == notDeepCopy # prints true
  orig.add 2
  echo orig == notDeepCopy # prints true
  orig.add 3
  echo orig == notDeepCopy # prints true
  orig.add 4
  echo orig == notDeepCopy # prints true
  orig.add 5
  echo orig == notDeepCopy # prints false. Could this be fixed?

f() # the proc is needed for proper shallowCopy, see
    # https://github.com/nim-lang/Nim/pull/3407
```

**Comment by Varriount** [comment]
What would you suggest be done? In python, lists are composed of a pointer to a pointer to an array - this means that when the array needs to be resized, only the secondary pointer has to change. In Nim, a sequence is just a pointer to a dynamically sized array (plus the size and capacity members).

If you need behavior like that in Python, use a `ref seq[T]` type.
