### ISSUE TITLE
Release v0.11.2 has version v0.10.3 in compiler.nimble

### ISSUE THREAD

**Issue by kFo** [nim-lang/Nim#3412]
https://github.com/nim-lang/Nim/blob/fd7b7a0bc1e2572648ade1f68e63db3dcd5655b7/compiler.nimble

nimble installs it as compiler-0.10.3

**Comment by dom96** [comment]
I don't think we can fix that I'm afraid.

**Comment by dom96** [comment]
We now have this document in the wiki which will hopefully prevent this from happening in the future. https://github.com/nim-lang/Nim/wiki/Creating-a-release
