### ISSUE TITLE
Buildbot badges are broken (caching problem)

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#3413]
@Varriount Seems that Mac builder is now working, but the badge isn't. Can you have a look? This is probably due *GitHub* caching problem described on:

https://github.com/github/markup/issues/224
https://github.com/travis-ci/travis-ci/issues/822
https://github.com/travis-ci/travis-ci/issues/1970

They describe solution as `Cache-Control: no-cache` which is present on our badges, but it also needs one of `ETag`, `Last-Modified` or `Expires` - none present in the response of:

```
curl -i http://buildbot.nim-lang.org/buildstatusimage?builder=mac-x64-builder

HTTP/1.1 200 OK
Cache-Control: no-cache
Transfer-Encoding: Identity
Content-Type: image/svg+xml
Connection: keep-alive
Server: nginx/1.4.6 (Ubuntu)
Date: Sat, 03 Oct 2015 18:52:45 GMT
```

Also if you can please remove 32-bit Mac badge, as it doesn't make sense, since we are not going to build 32-bit version for OS X.

**Comment by Varriount** [comment]
Ok, will do.

**Comment by nanoant** [comment]
@Araq @Varriount Can one of you guys file a request to `support@github.com` so they reload/invalidate cache for our README? According https://github.com/github/markup/issues/224#issuecomment-48532178 now our status badges generate both `Cache-Control: no-cache` and `Last-Modified: ...`, but the badges (notably Mac) are still broken on https://github.com/nim-lang/Nim/blob/devel/readme.md.

```
$ curl -i http://buildbot.nim-lang.org/buildstatusimage?builder=mac-x64-builder
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Sat, 10 Oct 2015 11:16:04 GMT
Content-Type: image/svg+xml
Transfer-Encoding: chunked
Connection: keep-alive
Last-Modified: Sat, 10 Oct 2015 11:10:52 GMT
Cache-Control: no-cache

<svg xmlns="http://www.w3.org/2000/svg" width="91" height="18">...</svg>
```

**Comment by Araq** [comment]
I remember this issue was taken care of.
