### ISSUE TITLE
db_postgres does not support ? for args

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3430]
The db_* supported ``?`` character for specifying where sql query arguments should be replaced is no longer supported in db_postgres due to a regression in https://github.com/nim-lang/Nim/commit/08f1c6100b307e8a6f5eeb8f6647552c10d4481d

**Comment by jlp765** [comment]
#3342 fixes this

**Comment by Araq** [comment]
> *FYI in my testing #3342 does fix allowing the use of ?, but does not support Postgres $1 etc. characters now except for prepared queries. Was that the intent?*

Yes and the docs are reasonably clear about that, IMHO, so I'm closing this issue for now.
