### ISSUE TITLE
iup lib for  newer than v3.0

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3444]
(This is probably for @Araq to answer)

IUP  versions newer (greater) than 3.0 have some backwards incompatibilities (changes in key definitions, ...)

Some questions:
- is the Nim iup module going to be upgraded?,  and if so does it split into two (the current, and a newer one that is up-to-date with the latest IUP version on the web), or ????
- is this a candidate to be moved to nimble?

If it becomes a Nimble package, there are a few extra utility libraries (that are part of IUP) that could be complementary iup nimble packages.

**Comment by Araq** [comment]
Yeah, move it into a Nimble package. You could enable/disable the different version with a --define.

**Comment by jlp765** [comment]
@Araq  

do you want to create a github repository for it on Nim-Lang, rather than it be under my github account?

**Comment by Araq** [comment]
https://github.com/nim-lang/iup created.

**Comment by lazypenguin** [comment]
Some notes on 3.16:

- Most classes now have 'new' in them. See `iup_stdcontrols.h` as an example.
- Matrix was moved to the Iupcontrols project
- The following projects will need procs generated from them
    - IupControls
    - IupMatrixEx
    - IupGLCanvas
    - IupGLControls
     - IupPlot
     - IupPPlot
     - IupMglPlot
     - IupOleControl
     - IupScintilla
     - IupWebBrowser

**Comment by lazypenguin** [comment]
I have started to update the wrapper: https://github.com/lazypenguin/iup/tree/3.16.0

**Comment by dom96** [comment]
Shall we remove it from Nim's stdlib?

**Comment by Araq** [comment]
If it's compatible with our wrapper and a Nimble package.

**Comment by Araq** [comment]
iup is not part of the stdlib anymore.
