### ISSUE TITLE
template like converters

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#3448]
http://forum.nim-lang.org/t/1294#8116

Not a bug, only a wish:

Recently, when I understood that chaining of converters is too complicated, I wondered if template like converters may be possible. Current converters have a well defined return type and behave like magically called procs. It would be nice to have a converter with well defined parameter type but expr result.

Araq replied:

@Varriount But the input type is known for this template, only the return type is inferred. Looks quite easy to support.

So maybe at some time we may get that?

**Comment by StefanSalewski** [comment]
Note:

With .delegate annotation for object fields there is no more for this issue! See

http://forum.nim-lang.org/t/1901#11826

**Comment by Araq** [comment]
Note that I now prefer to simply clean up converters to allow the same since converters are already in the language and used so it's worse to have 2 features rather than one. Can you perhaps create some mini-document outlining the respective advantages / disadvantages?

**Comment by StefanSalewski** [comment]
On Wed, 2016-01-20 at 08:44 -0800, Andreas Rumpf wrote:
> Note that I now prefer to simply clean up converters to allow the
> same since converters are already in the language and used so it's
> worse to have 2 features rather than one. Can you perhaps create some
> mini-document outlining the respective advantages / disadvantages?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nim-lang/Nim/issues/3448#issuecomment-173267442

I gave a minimal working example for converters in the forum thread

http://forum.nim-lang.org/t/1901#11826

We would need one converter for each GTK related datatype which we may
pass to the C libraries. That may be some hundred or maybe thousand.
Not a big task writing them, maybe a script can do.

But my fear was that so many converters may generate much clutter, and
you said that it would be bad. Maybe reduce compilation speed?

Chaining convertes may not work, I am not sure if that can be a
problem.

Generally delegates may be a cleaner solution, because that is a one to
one relation in one direction, Nim object to corresponding C object.
