### ISSUE TITLE
math.nim: fac() int limits

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3459]
fac() only handles fac(20) before wrapping to a negative number (incorrect result).

Should this:
- be converted to a float64 and handle up to `fac(170) = 7.257415615307994e+306`
- stay as is but limit to `fac(20) = 2432902008176640000`
- something else??

**Comment by Araq** [comment]
It should really raise an overflow exception by now...

**Comment by jlp765** [comment]
`tgamma((i+1).float) == fac(i).float`

So if `fac()` is made a wrapper to `tgamma()`, then there is consistency between `tgamma()` and `fac()`.

It would require a change from `fac(int): int`  to  `fac(int):float`, or else have `fac(int): int` limit/overflow at `high(int)`

Question is, do you keep `fac()` as an `int` returning proc, or make it consistent with `tgamma` and return `float` ?

**Comment by Araq** [comment]
Fails for me with an overflow exception and 'fac' should continue to return an 'int'. I see no problem here.
