### ISSUE TITLE
why 'case' do not like 'if' that can compare between objects with same type.

### ISSUE THREAD

**Issue by bkdrong** [nim-lang/Nim#3461]
if can :
```nim
  type 
    myobj = object
            x : int
            y : int
  var m = myobj(x:1,y:2)
  if m == myobj(x:2,y:3):
    echo "=="
  else:
    echo "!="
```
  but 'case' cannot:
```nim
  case m : 
    of myobj(x:2,y:3):
      echo "=="
  else:
      echo "!="
```
Compiler complain ''Error: selector must be of an ordinal type, float or string".
if 'case' statement can write with over sentence,How good it is!

**Comment by Xe** [comment]
Can you fence your code with backticks?

   \`\`\`nimrod
   var foo = "bar"
   \`\`\`

```nimrod
var foo = "bar"
```

**Comment by kirbyfan64** [comment]
I think it's supposed to be like:

```nim
type 
  myobj = object
    x : int
    y : int
var m = myobj(x:1,y:2)
if m == myobj(x:2,y:3):
  echo "=="
else:
  echo "!="
```

and:

```nim
case m: 
of myobj(x:2,y:3):
  echo "=="
else:
  echo "!="
```

**Comment by bkdrong** [comment]
yes! the code in below:
nimrod ```
type 
  myobj = object
    x : int
    y : int
var m = myobj(x:1,y:2)
case m: 
of myobj(x:2,y:3):
  echo "=="
else:
  echo "!="
```
why the compiler complain ''Error: selector must be of an ordinal type, float or string".

**Comment by Araq** [comment]
Delegating to '==' for 'case' would be easy and useful, but it is of low priority.

**Comment by Varriount** [comment]
Wouldn't this rather complicate the semantics though? Case covers ordinal checks, and a large part of its purpose is exhaustiveness checks.

**Comment by Araq** [comment]
@Varriount we can always enforce the 'else' when we cannot compute exhaustiveness like we already do for string cases. (Which is annoying btw., but good for consistency.)

**Comment by Sod-Almighty** [comment]
Why has this issue been closed, when the issue is not actually resolved?

**Comment by glyh** [comment]
@bkdrong could you please reopen this?
