### ISSUE TITLE
Use Nim logo in presentation

### ISSUE THREAD

**Issue by kanaka** [nim-lang/Nim#3462]
I'm going to be doing a presentation about mal (https://github.com/kanaka/mal) at midwest.io. Nim is one of the implementations and I would like to use a Nim logo in the presentation.

Some questions:

* Can I use the Nim logo in a presentation?
* The only logo I've really been able is here: https://github.com/nim-lang/Nim/blob/devel/web/assets/images/logo.png Do you have a version without the shadow?
* Can you clarify the license on the logo/web assets (e.g. this https://github.com/nim-lang/Nim/tree/devel/web/assets/images)
* Do you have vector graphic versions of the Nim logo?

Thanks

**Comment by yglukhov** [comment]
https://github.com/nim-lang/Nim/blob/devel/web/assets/images/nim-logo.svg

**Comment by dom96** [comment]
This repository has better versions of the logo, please use the one most resembling the one currently used on the website https://github.com/nim-lang/assets

**Comment by Araq** [comment]
That's a solved problem, right?
