### ISSUE TITLE
Error: method is not a base

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#3468]
If there are two different types inherited of RootObj, and they have methods with same names, like in the example below:

```nim
type X = ref object of RootObj
type Y = ref object of RootObj

method draw*(x: X) {.base.} = discard
method draw*(y: Y) {.base.} = discard
```
We receive an error:
```bash
Error: method is not a base
```

Also, method signature is important here: if we add, e.g. another argument to `draw(x: X)`, and make it like `draw(x: X, a: int)`, the error is not raised.

**Comment by Araq** [comment]
Why is this a bug? The error message tries to prevent misuse. You have no inheritance chain here that could be used to resolve it properly at runtime and at compiletime you gained nothing by using 'method'.

**Comment by yglukhov** [comment]
Every object should be able to define either base or an override method, right? In this example both methods should be base, and subclasses of X can override X.draw, and subclasses of Y can override Y.draw. In other words, these two methods have nothing in common except a name, and thus they both should be base methods.

**Comment by Araq** [comment]
Well, yes I understand, but this error message was introduced to improve the usability of methods.

**Comment by Araq** [comment]
Never mind, it's just a bug. (Have a fix ready.)
