### ISSUE TITLE
case of string does not throw the error "not all cases are covered" when else block is missing

### ISSUE THREAD

**Issue by anuj-sahai** [nim-lang/Nim#3469]
As mentioned in the documentation of [case statement](http://nim-lang.org/docs/tut1.html#control-flow-statements-case-statement), *Note that it is impossible to cover all possible string values: that is why string cases always need an else branch.*

But the first example of case statement compiles and runs even when the else block is left off.

```
let name = readLine(stdin)
case name
of "":
  echo("Poor soul, you lost your name?")
of "name":
  echo("Very funny, your name is name.")
of "Dave", "Frank":
  echo("Cool name!")
```
compiles without needing the else block,
```
else:
  echo("Hi, ", name, "!")
```
Is it a bug or does the documentation need to be updated?

**Comment by anuj-sahai** [comment]
Okay, it looks like only a warning is generated, but the compilation is successful.
```
Hint: system [Processing]
Hint: cases [Processing]
cases.nim(3, 1) Warning: use 'else: discard'; non-ordinal case without 'else' is deprecated [Deprecated]
[Linking]
Hint: operation successful (9085 lines compiled; 0.163 sec total; 14.143MB; Debug Build) [SuccessX]
```
imho, the documentation should be updated to at least reflect this.

**Comment by Araq** [comment]
No, the warning will eventually become an error. The docs are correct, the implementation lags a bit behind to support old code.

**Comment by dom96** [comment]
Not a bug in my opinion.
