### ISSUE TITLE
Copy by value does not work in JS

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#347]
var a = newSeq[proc():int]()
    for i in [1,2,3,4]:
      var j = i
      var fun = proc():int = j
      a.add(fun)

    for fun in a: echo(fun())

Produces in C:

    1
    2
    3
    4

Produces in JS:

    4
    4
    4
    4

**Comment by bogen** [comment]
Reactormonk, do you still have that workaround? That gist is dead.

**Comment by reactormonk** [comment]
It's an explanation on how to do the JS generation. Not a nim WA.

**Comment by bogen** [comment]
Well, I might be looking into correcting this in the nim JS back end.

**Comment by reactormonk** [comment]
I corrected the link meanwhile.

**Comment by yglukhov** [comment]
Due to new-ll the results produced by c gen are the same as in js. Close? :)

**Comment by reactormonk** [comment]
No, I still get the incorrect results with 13c98222df26925938bdb8bb55d9af900cc5a228.

**Comment by vegansk** [comment]
@reactormonk, read "Closure changes" section here: http://nim-lang.org/news.html#Z2016-01-18-version-0-13-0-released

```
The semantics of closures changed: Capturing variables that are in loops do not produce a new environment. Nim closures behave like JavaScript closures now.

```

**Comment by Xe** [comment]
```nimrod
# cbv.nim
var a = newSeq[proc():int]()

for i in [1,2,3,4]:
  var j = i
  var fun = proc():int = j
  a.add(fun)

for fun in a: echo(fun())
```

```
xena@greedo (linux) ~/tmp/nim
➜  nim c -r cbv.nim
Hint: system [Processing]
Hint: cbv [Processing]
Hint:  [Link]
Hint: operation successful (9905 lines compiled; 0.166 sec total; 14.148MB; Debug Build) [SuccessX]
4
4
4
4
```

```
xena@greedo (linux) ~/tmp/nim
➜  nim js -d:nodejs cbv
Hint: system [Processing]
Hint: cbv [Processing]
Hint: operation successful (4637 lines compiled; 0.147 sec total; 3.358MB; Debug Build) [SuccessX]

xena@greedo (linux) ~/tmp/nim
➜  node nimcache/cbv.js
4
4
4
4
```

I don't know if this is intended or not, but it is consistent now.
