### ISSUE TITLE
Changing math.round() and adding math.integer()

### ISSUE THREAD

**Issue by oderwat** [nim-lang/Nim#3473]
I just needed something like `let a = math.round((a - b) * 100.0) / 100.0` which does not work because `math.round()` returns an `int`.

Should this not better be something like this in math module:

```nim
proc round*(x: float): float {.importc: "round", header: "<math.h>".}
proc roundToEven*(x: float): float {.importc: "lrint", header: "<math.h>".}

# and "maybe"
proc roundToInt*(x: float): int = toInt(x)
proc integer*(x: float): int = int(x)
```
So that you stay in the floating point domain when using round?

I would also prefer to have an additional `round(x, digits)` in the standard library `let x = round(a - b,2)`.

While experimenting I found that `toInt()` is also rounding. `toInt(0.5)` results in 1 which is unexpected for me. I would think `toInt()` basically drops the decimals and nothing else. While `int(0.5)` and `int(-0.5)` is doing what I expected from `toInt()`. So we could probably just change `math.round()` to return floating point like `ceil()` and `floor()` does and let `toInt()` as it is as and use it where `round()` was used before.

It even seems to me that round is using the "wrong" function to be use. `lrint()` rounds x.5 depending on x. If x is even it rounds down if x is uneven it rounds up. This is to "even out" rounding errors in financial data. Which is a nice function but probably not what I expect from `round()`, no matter if that results in an int or float type.

But then. With this information I have all I need but with "not obvious" names. So I would still like to have "round()" doing the propper mathematical round (as it is in math module) and deliver a floating point type. While we could introduce another `round()` which uses `lrint()` with either `lrint()` as name or probably `financialRound() / ieeeRound() / roundToEven()` which also returns floating point but explains what it really does. 

```nim
echo int(0.5) # 0
echo int(-0.5) # 0

echo toInt(0.5) # 1
echo toInt(-0.5) # -1

echo round(0.5) # 0
echo round(-0.5) # 0

echo round(1.5) # 2
echo round(-1.5) # 2
```

**Comment by jlp765** [comment]
C spec has these (and probably more):
`rint()`     (raises exception if not exact)
`nearbyint()`    (like `rint`, but not exception)
`nextafter()`
`nexttoward()`

**Comment by abudden** [comment]
In order to implement `formatEng` (see #4197), I need to implement a rounding function that returns a float.  Coming from a 'C' background, I would expect this to be called `round`, but this has clearly been taken by the one that returns an int.  I'm happy to create a pull-request to amend the naming / add the missing functionality, but I'd need to know which is preferred:

1. Make round return a float:
    * `round(float) -> float`
    * `lrint(float) -> int` to call math.h's `lrint` (I've no experience of this function, so I don't know if it should be renamed `financialRound` or similar)
    * `roundToInt(float) -> int` to do `int(round(x))` (or, in keeping with the semi-cryptic naming in math.h `roundl`).  Alternatively just leave it be and users can do `round(x).int` or `int(round(x))`.
2. Make a new floating point round function and "fix" the round function that returns an int:
    * `round(float) -> int` (implemented as C's `int(round(x))` rather than `lrint`)
    * `fround(float) -> float`
    * `lrint(float) -> int` (as current `round()` function)
3. Just add stuff without changing anything:
    * `round(float) -> int` (implemented as C's `lrint`)
    * `fround(float) -> float` (implemented as C's `round`)
    * `roundToInt(float) -> int` (implemented as `int(round(x))`) - not strictly required as this should be the same as `int(fround(x))`

I prefer the former option (preferably with a different name for lrint), but I would imagine that it would break a lot of code; therefore I'll wait for more experienced users to let me know their preference prior to sending a PR.

As an aside, from my limited reading around `lrint`, the rounding direction seems to depend on the direction returned by `fegetround` and set by `fesetround`.  Given that `fesetround` isn't exposed by math.nim, it seems strange to me to use `lrint`.  As I said though: I've only recently heard of `lrint`, so I might be barking up the wrong tree.

**Comment by abudden** [comment]
Another option that could be considered with option 1 would be to modify round to have multiple arguments (with a sensible default):

```
proc round*(f: float, places: int = 0): float =
  ## Round a floating point number.
  ##
  ## If `places` is 0 (or omitted), round to the nearest integral value
  ## following normal mathematical rounding rules (e.g. `round(54.5) -> 55.0`).
  ## If `places` is greater than 0, round to the given number of decimal
  ## places, e.g `round(54.346, 2) -> 54.35`.
  ## If `places` is negative, raise an exception
```

**Comment by oderwat** [comment]
My vote again to fix round and optionally having a precision, rounds with >.5 up and returns floats 👍  before Nim hits 1.0. Converting to int and other ways of rounding should have better names too.

**Comment by dom96** [comment]
> Another option that could be considered with option 1 would be to modify round to have multiple arguments (with a sensible default):

I like this idea but I think that ``round`` should continue to return an ``int``. Also the type of ``places`` should be a [`Natural`](http://nim-lang.org/docs/system.html#Natural) to prevent negative values. You can introduce an `fround` proc for convenience.

**Comment by abudden** [comment]
@dom96 regarding negative numbers, an alternative to a `Natural` would also be to allow a negative number of places:
```
round(547.652, -1) -> 550
round(547.652, -2) -> 500
round(547.652, -3) -> 1000.0
round(547.652, -4) -> 0.0
```

Why do you prefer `round` to return an `int`?  I can implement it either way obviously, but I'm interested to hear the pros/cons between:

Two functions:
```
round(54.7) -> int
fround(54.7) -> float
```
One function plus existing `int` function:
```
round(54.7) -> float
round(54.7).int -> int
```

Note that whichever we do probably results in a change to `round` as I've just noticed the current implementation is inconsistent: the javascript code does a conventional round to the nearest integer, whereas the C implementation uses `lrint` and therefore uses unconventional rounding.

```
# test.nim
import math
echo round(5.5)
echo round(6.5)
```

```bash
$ nim c -r test.nim
[snip]
6
6
$ nim js -o:test.js test.nim
# Load in browser, output is:
6
7
```

**Comment by dom96** [comment]
> @dom96 regarding negative numbers, an alternative to a Natural would also be to allow a negative number of places:

> ```
round(547.652, -1) -> 550
round(547.652, -2) -> 500
round(547.652, -3) -> 1000.0
round(547.652, -4) -> 0.0
```

I like it, but maybe it shouldn't go down to 0 at the lower index but remain at ``1000``?

> Why do you prefer round to return an int?

The main reason is that it _currently_ returns an ``int``, changing it will break code (a lot of code).

The semantics should be the same for JS and C implementations. The JS behaviour makes most sense.

**Comment by oderwat** [comment]
The future `round(54.7).int` is not what `round(54.7)` currently does. See what I wrote... round() does not do what we think what round should do.. "toint()" is rounding 0.5 to int 1 ... "round()" is rounding 0.5 to int 0!

```nim
# status quo
echo round(0.5) # int 0
echo round(0.6) # int 1
echo toInt(0.5) # int 1
echo toInt(0.6) # int 1
```

**Comment by oderwat** [comment]
> The main reason is that it currently returns an int, changing it will break code (a lot of code)

Mmaybe but I am not sure if the people know that their code uses `lrint()` which uses even/odd rounding for 0.5. Cool but.. probably just not what they think what happens.

**Comment by oderwat** [comment]
BTW...

```nim
# nim js -d:nodejs --verbosity:0
import math

echo round(0.5) # 1
echo round(1.5) # 2
echo round(2.5) # 3
echo round(3.5) # 4
```

**Comment by dom96** [comment]
@oderwat indeed. Like I said:

> The JS behaviour makes most sense.

Let's change math.random to adhere to those semantics.

**Comment by oderwat** [comment]
I would say... make `round()` returning float. Break peoples code and let them rethink their intentions! Nim is not 1.0 and this brings the opportunity to let some of them even fix their code!

**Comment by abudden** [comment]
> > @dom96 regarding negative numbers, an alternative to a Natural would also be to allow a negative number of places:

> > round(547.652, -1) -> 550
> > round(547.652, -2) -> 500
> > round(547.652, -3) -> 1000.0
> > round(547.652, -4) -> 0.0
> I like it, but maybe it shouldn't go down to 0 at the lower index but remain at 1000?

I don't think so: with -4, it's rounding such that the answer will either be 0 or 10000.  In this case it has to be 0 as 547 is much closer to 0 than 10000.

**Comment by dom96** [comment]
> I would say... make round() returning float. Break peoples code and let them rethink their intentions! Nim is not 1.0 and this brings the opportunity to let some of them even fix their code!

Perhaps you are right. I just realised that in order to support the ``places`` parameter, the ``round`` proc will need to return a float.

... or we could only support that parameter for ``fround`` heh. Nah. Fine, let's break it.
