### ISSUE TITLE
No nim doc code block generated when code blocks starts with 0x or 0b

### ISSUE THREAD

**Issue by mjoud** [nim-lang/Nim#3478]
As noted while updating `shr` docs, no code block is generated by `nim doc` when the first word in the code block is `0b...` or `0x...`. Tested with devel and v0.11.2.

```nimrod
proc doesntwork*() =
  ## .. code-block:: Nim
  ##  0x0
  discard
```

**Comment by Araq** [comment]
This has finally been fixed.
