### ISSUE TITLE
[docs] better specification for {.thread_var.}

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#3479]
Fresh new 0.12.0 on Win7

The docs states:

> thread local variables cannot be initialized within the var section

but it is not clear (to me) whether the default initialization with zeros still kicks in or not. (It does in my little test but this may be random.)

It is also possible to add no_init pragma resulting in no warning (could be redundant). 

> var x {.thread_var, no_init.}   : int

**Comment by Araq** [comment]
> but it is not clear (to me) whether the default initialization with zeros still kicks in or not.

Yes this is a requirement that needs to be documented.

**Comment by Araq** [comment]
The error message is better now "a thread var cannot be initialized explicitly; this would only run for the main thread", closing.
