### ISSUE TITLE
[0.12.0] en-dash allowed to be the first letter for an identifier

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#3480]
This compiles:

> var –x : int = 122  # the leading minus is en-dash
> echo –x

IMO it should not be allowed.

**Comment by kirbyfan64** [comment]
Yes it should. Just like `_x`. Remember: underscores and en-dashes are disregarded, so you can reference it as just `x`.

**Comment by Araq** [comment]
Well ``_x`` is not valid either, so I agree with @PavelVozenilek.

**Comment by GULPF** [comment]
Can be closed since en-dash has been removed from the language.

**Comment by andreaferretti** [comment]
Seems to be still a valid example on latest devel

**Comment by GULPF** [comment]
It should be valid, since en-dash is no longer special. Previously en-dash was treated the same as underscore, which is why a leading en-dash shouldn't have been allowed.

**Comment by Yardanico** [comment]
@andreaferretti it can be closed because en-dash doesn't have any special meaning anymore, and it's just a normal unicode character
