### ISSUE TITLE
Wrong type name in error message

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#3481]
0.12.0/64 bits on Win7

This completely example (correctly) fails:

> type
>   Foo1[T1, T2, T3, T4] = object
>   Foo2[T1, T2, T3, T4] = object
> 
>
> var  foo1 : Foo1[int, bool, float, int32]
> var  foo2 : Foo1[int, bool, bool, bool]
>
> foo1 = foo2

but the error message is:

> C:\Nim\bin>nim c a.nim
> Hint: system [Processing]
> Hint: a [Processing]
> a.nim(2, 16) Hint: 'T3' is declared but not used [XDeclaredButNotUsed]
> ... several more warnings like this
>
> a.nim(11, 8) Error: type mismatch: got (Foo1[system.int, system.bool, system.bool, system.bool]) 
> but expected 'Foo1[system.int, system.bool, system.float, system.int32]'

The problem I see is that Foo1 is mention twice in the error part, once incorrectly (should be Foo2).

**Comment by VKlayd** [comment]
It looks like all right.

>var foo1 : Foo1[int, bool, float, int32]
>var foo2 : Foo1[int, bool, bool, bool]
>
>foo1 = foo2

Both foo1 and foo2 if Foo1 type. If you change to
>var foo2 : Foo2[int, bool, bool, bool]

Message will be

>Error: type mismatch: got (Foo2[system.int, system.bool, system.bool, system.bool]) but expected 'Foo1[system.int, system.bool, system.float, system.int32]'

So. There are no error, i think.

**Comment by PavelVozenilek** [comment]
Oops, my error, I didn't notice my mistake (Foo2 not used).
