### ISSUE TITLE
Generic arguments cannot be used in templates (raising undeclared identifier)

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#3498]
Currently there is no way to use generic arguments in templates, as if their identifiers were not replaced by their generic argument values during template evaluation.

```nim
template defaultInt(t: int): expr = (var d: int; d)
template defaultFor[T](t: T): expr = (var d: T; d)

echo defaultInt(1) #<- expected 0
echo defaultFor(1) #<- expected 0, but got Error: undeclared identifier: 'T'
```

**Comment by almikhail** [comment]
I applied your patch to upstream devel and now compiler crashes on th following code:

```
type
  Tup1[T] = tuple
    t0: T
    t1: T
  Tup2[T] = tuple
    t0: T
    t2: T
  Tup[T] = Tup1[T]|Tup2[T]

template set[T](tup: Tup[T], e: expr, t: T) {.immediate.} =
  when type(tup) is Tup1[T]:
    echo "Tup1"
  else:
    echo "Tup2"
  tup.e = t

when isMainModule:
  var tup = (t0: 1, t2: 2)
  set(tup, t2, 1)
```

with error `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`. Is this construction somewhat malformed?

**Comment by Araq** [comment]
Yes, .immediate templates are not subject to type checking and about to become deprecated.
