### ISSUE TITLE
New unambiguous generics syntax (generic arguments syntax)

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#3502]
Current `some[A, B](x, y)` syntax has serious flaw, it uses same notation as array subscript operator, so the `some[A, B](x, y)` meaning depends on what `some` represents, and can be given when we know semantics of `some`. This makes it impossible to distinguish subscript call from generic call just using grammar (lexer), eg. doing syntax highlight in editor.

This implies some subtle problems, eg.:

``` nim
template arr: expr = [1, 2, 3, 4]
template arr2[N]: expr = N

# ...  in some other galaxy far, far away:

echo arr[1] #<- template eval with no args then array access, or maybe something else
echo arr2[1] #<- template eval with 1 generic arg, or maybe something else
```

As it can be observed above, we don't know what's going on until we see definition of `arr` and `arr2`, which often may be in separate file.

Therefore we should take into consideration moving away from this array subscript like syntax to something exclusive to generic arguments. Here are some propositions:
##### Current ambiguous syntax

Generic args supplied in `[Arg]`, same as subscript operator.

``` nim
proc newSeq[A](size: int): seq[A] = …

var v: seq[int]
let x = newTable[string, int]
let y = newSeq[int](10)
let z = newList[10](1) # static
```
##### 1.1. Generic args supplied in `[.Arg….]`

``` nim
proc newSeq[.A.](size: int): seq[.A.] = …

var v: seq[.int.]
let x = newTable[.string, int.]
let y = newSeq[.int.](10)
let z = newList[.10.](1) # static
```
##### 1.2. Generic args supplied in `[.Arg…]`

``` nim
proc newSeq[.A](size: int): seq[.A] = …

let x = newTable[.string, int]
let y = newSeq[.int](10)
let z = newList[.10](1) # static
```
##### 2. Generic args supplied in `(.Arg….)`

``` nim
proc newSeq(.A.)(size: int): seq(.A.) = …

var v: seq(.int.)
let x = newTable(.string, int.)
let y = newSeq(.int.)(10)
let z = newList(.10.)(1) # static
```
##### 3.1. Generic args supplied in `[:Arg…]`

``` nim
proc newSeq[:A](size: int): seq[:A] = …

var v: seq[:int]
let x = newTable[:string, int]
let y = newSeq[:int](10)
let z = newList[:10](1) # static
```
##### 3.2. Generic args supplied in `{:Arg…}`

``` nim
proc newSeq{:A}(size: int): seq{:A} = …

var v: seq{:int}
let x = newTable{:string, int}
let y = newSeq{:int}(10)
let z = newList{:10}(1) # static
```
##### 4. Generic args introduced to called ident with `::Arg`

``` nim
proc newSeq::A(size: int): seq::A = …

var v: seq::int
let x = newTable::string::int
let y = newSeq::int(10)
let z = newList::10(1) # static
```
##### 5. Generic args together with normal in `()` separated from them by `;`

``` nim
proc newSeq(A; size: int): seq(int;) = …

var v: seq(int;)
let x = newTable(string, int;)
let y = newSeq(int; 10)
let z = newList(10; 1) # static
```
##### 6.1. Generic args together with normal, each prefixed with `:`

``` nim
proc newSeq(:A, size: int) seq :A = …

var v: seq :int
let x = newTable :string, :int
let y = newSeq :int, 10
let z = newList :10, 1 # static
```
##### 6.2 Generic args together with normal, each suffixed with `.`

``` nim
proc newSeq(A., size: int) seq A. = …

var v: seq int.
let x = newTable string., int.
let y = newSeq int., 10
let z = newList 10., 1 # static
```
##### 7. Generic args inserted to call expression via `of Arg` bin-op expression

``` nim
proc newSeq(size: int) of A: seq of A = …

var v: seq of int
let x = newTable of (string, int)
let y = newSeq(10) of int
let z = newList(1) of 10 # static
```
##### 8. Generic args supplied in `\Arg…\`

``` nim
proc newSeq \A\(size: int): seq \A\ = …

var v: seq \int\
let x = newTable \string, int\
let y = newSeq \int\(10)
let z = newList \10\(1) # static
```
##### 9. Generic args supplied in `<<Arg…>>`

``` nim
proc newSeq<<A>>(size: int): seq<<A>> = …

var v: seq<<int>>
let x = newTable<<string, int>>
let y = newSeq<<int>>(10)
let z = newList<<10>>(1) # static
```
## Controversial syntaxes

Following syntaxes cannot be easily implemented in Nim without changing some other language features:
##### 1. C++/Java/Rust like syntax, generic args supplied in `<Arg…>`

This may be nice, but unfortunately it requires introducing lookahead (after `>` token) in Nim grammar parser since `<` and `>` are already parsed as comparison operators. So it basically would bring us to square one, replacing `[…]` problem with `<…>` problem, also would cause problems to text editors which use regular expression to parse and highlight Nim.

``` nim
proc newSeq<A>(size: int): seq<A> = …

var v: seq<int>
let x = newTable<string, int>
let y = newSeq<int>(10)
let z = newList<10>(1) # static
```
##### 2. Generic args supplied in `{Arg…}`

It requires removal of `{}` postfix operator, which is not widely used, but still convenient. It will not however collide with set construction syntax.

``` nim
proc newSeq{A}(size: int): seq{A} = …

var v: seq{int}
let x = newTable{string, int}
let y = newSeq{int}(10)
let z = newList{10}(1) # static
```

**Comment by reactormonk** [comment]
Or

    let arr = [1, 2, 3]
    arr(0)

and keep the old type syntax. Via https://ideone.com/NdtXNu

**Comment by ephja** [comment]
@reactormonk Perhaps it won't negatively affect the readability (for experienced users), and this syntax is equally concise. Would `arr i = foo` work? I guess not :stuck_out_tongue:

**Comment by reactormonk** [comment]
No, if `()` is your method name, you'll have to explicitly use `()`.

**Comment by gmpreussner** [comment]
Ha, I was thinking about this same thing earlier this week when studying some Julia code. They use {T}, which we already use for set constructors. I don't like any of the alternatives, to be honest, but I guess `arr(0)` wouldn't be the end of the world.

**Comment by kirbyfan64** [comment]
What about `arr.[0]`? That's what Felix does.

**Comment by reactormonk** [comment]
Or we could ditch the set constructors and use `newSet()` or `set()`, so we have `{T}` too?

**Comment by Araq** [comment]
The way to do it is to use [. .] and make the editor render it as some nice Unicode bracket.

**Comment by Varriount** [comment]
@Araq is there any way to do this which doesn't involve awkward-to-type syntax additions? The pragma syntax is bad enough, but at least it's not as common as subscripts.

**Comment by baabelfish** [comment]
Why not use angle brackets?

**Comment by dom96** [comment]
So if I understand this correctly it's only ambiguous when ``static[int]`` is involved? Could we create a special syntax for ``static``?

**Comment by nanoant** [comment]
@dom96 It is ambiguous regardless `static` use, example

```nim
proc `()`(a, b: int): int = a + b
let newList = [1, 2, 3, 4]
let pos = 1
# ...
let z = newList[pos](2)
```
vs:
```nim
type pos = int
proc newList[T](def: T): seq[T] = newSeq[T](def)
# ...
let z = newList[pos](2)
```

**Comment by dom96** [comment]
Wouldn't that example be solved by the "Types should start with a capital letter rule" (which isn't enforced right now, but perhaps could be?). I would be more inclined to get rid of ``()`` and/or ``static`` than to change the current `[]` syntax for generics.

**Comment by dom96** [comment]
IRC discussion in relation to this starts at around 10:06 here: http://irclogs.nim-lang.org/08-01-2016.html

**Comment by nanoant** [comment]
@dom96 Any conclusions from yesterday's discussion?

**Comment by dom96** [comment]
@nanoant @Araq will attempt to make the current syntax Just Work (TM).

**Comment by dom96** [comment]
To update this, as far as I remember from my discussion with Araq the idea was to supplement the current syntax with "3.1", i.e. ``foo.bar[:string, :int]`` (but the current syntax ``foo.bar[string, int]`` will still be possible)

Marking as high priority as this is has went from our radar and I think it's relatively important.

**Comment by RedBeard0531** [comment]
Maybe this is a crazy idea, but could you syntactically merge the `[]` operator and template arguments into the same AST? Then passing a template arg to a proc would be as-if you called a `magical proc[](p: proc, ts: varargs[typedesc]): proc`. Or an alternative way to visualize it would be that template procs were implemented as-if they were an array of procs indexed by typedesc rather than an ordinal, where the index was sometimes implied by the arguments.

I think this pushes the problem from the parser to the semantic analyzer which is more equipped to deal with resolving the meaning of the expression.

**Comment by timotheecour** [comment]
no-one has suggested this yet, but this is how D solved this problem (I'm adapting it to Nim here):

```nim
proc newSeq!(A)(size: int): seq!(A) = …

var v: seq!(int)
let x = newTable!(string, int)
let y = newSeq!(int)(10)
let z = newList!(10)(1) # static
```

Furthermore, in the common case of a single generic argument, the shorthand `foo!bar` can be used instead of `foo!(bar)`:
(would that shorthand syntax cause ambiguities?)
```nim
proc newSeq!(A)(size: int): seq!A = …

var v: seq!int
let x = newTable!(string, int)
let y = newSeq!int(10)
let z = newList!10(1) # static
```

NOTE: actually the D syntax is: `void fun(T)(T a){...}` , not void fun!(T)(T a){...}` but seems to me better to match declaration and caller syntax by having `!` in both.

PS: sorry in advance for keeping mentioning D but I think it's worthwhile to take inspiration from other languages.

/cc @dom96

**Comment by Yardanico** [comment]
We should probably cc @Araq

**Comment by GULPF** [comment]
I think that would be ambiguous, since `!` can be an operator. E.g `foo!bar(baz)` could either mean "call `foo` with generic argument `bar` and argument `baz`" or "call `!` with arguments `foo` and `bar(baz)`".

**Comment by timotheecour** [comment]
could Nim make it non-ambiguous by making `!` mean the next identifier is a template argument?

independently of that, the non-shorthand version `!(...)` could be made non-ambiguous as well.

Not really important which character is used in case `!` is not a good fit.

**Comment by Araq** [comment]
I like ``obj.foo[:int]()`` best. A new type of bracket, ``[: ]`` indicating type arguments. ``foo[int](obj)`` will continue to work too.

**Comment by zah** [comment]
I think we should make some effort to deprecate this style of APIs from the standard library. The `typedesc` params have a shorter syntax and have the additional benefit of participating properly in overload resolution. 

Explicit generic parameter should be used only when you override the call-site inferred types discovered by the compiler and when you obtain a proc pointer to a particular generic instantiation.

**Comment by zah** [comment]
`cast` and `newSeq` are the biggest offenders right now, which drive newcomers to the language into using explicit generic params in their own APIs.

**Comment by dom96** [comment]
That seems like it will renegade the explicit generic parameters into oblivion, and I don't like that. I've always disliked the mixing of values and ``typedesc``s in function arguments.

I would vote for going the other way around. The use of ``options.some(123)`` is inconsistent with ``options.none(int)`` which takes a type.

**Comment by dom96** [comment]
@zah it seems that generics support overloading as well:

```nim
import strutils

proc parse[Dest: int](s: string): Dest = s.parseInt()
proc parse[Dest: bool](s: string): Dest = s.parseBool()

echo(parse[int]("123"))
echo(parse[bool]("yes"))
```

That works fine. IMO typedesc should be used in limited cases, for example when querying information about a type like in the case of ``high(int)``.

**Comment by hlaaftana** [comment]
I like the idea of default generic parameters, maybe named ones like `parse[Dest = int]` could be cool too. Is there an RFC for this?

**Comment by Varriount** [comment]
@zah How do typedesc params work with type inferencing? Currently if I have a `proc foo[T](a: T)` I can call it like `foo(1)`, and the `T` parameter will be inferred.

**Comment by timotheecour** [comment]
@hlaaftana  https://github.com/nim-lang/Nim/issues/3502#issuecomment-379045563
> I like the idea of default generic parameters, maybe named ones like parse[Dest = int] could be cool too. Is there an RFC for this?

made one here: https://github.com/nim-lang/Nim/issues/7516

**Comment by timotheecour** [comment]
> That works fine. IMO typedesc should be used in limited cases, for example when querying information about a type like in the case of high(int).

let's move the discussion on when to use generics vs typedesc to here: https://github.com/nim-lang/Nim/issues/7517 ([RFC] guidelines for when to use typedesc vs generics)

**Comment by Araq** [comment]
``obj.field[:T]()`` now works. Closing for now, we'll see what people have to say about it when they tried it for real.

**Comment by timotheecour** [comment]
- [ ] doesn't seem to work
@Araq after updating to latest nim `foo[:int](1)` doesn't seem to work:
```nim
proc foo[:T](a:T):auto=return a
echo foo[:int](1)
```
gives `Error: invalid indentation`

- [ ] would signature have to match call site? eg could `proc foo[:T](a:T)` be called with `foo[int](1)` or `foo[:int](1)` interchangeably (and likewise with `proc foo[T](a:T)`) ?

- [ ] I'd like to have a syntax that makes the common case of a single generic param easy, eg analog to D's `foo!T` or `foo!(T)` ; doesn't have to be `!` if that would cause ambiguity but any non-ambiguous single character. `[:T]` can't be used in short-form syntax as `foo:T` would cause ambiguity.

**Comment by Araq** [comment]
> after updating to latest nim foo[:int](1) doesn't seem to work:

Nor is it supposed to. It only exists in dot calls so that there is still one way to write these things...

> having eventualy 1 way to do things would be nice (eg depracatingfoo[T]) if it can be done (mostly) automatically; nimfix could help upgrading to whatever new unambiguous syntax. After 1.0, it'll be too late.

It is too late. Version 1.0 is not out because of quality-of-implementation problems, not because we are generally open to syntax changes.
