### ISSUE TITLE
Converter overload resolution problem

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#3503]
When augmenting the following code...

``` nim
type Foo = object
  r: float

proc `+=`*(x: var Foo, r: float) =
  x.r += r

var a: Foo
a.r += 3.0
```

... with a converter..

``` nim
converter toFoo(r: float): Foo =
  result.r = r
```

... the compiler is attempting to use `Foo.+=` instead of `system.+=` for `a.r += 3.0` and throws the following error:

```
Error: for a 'var' type a variable needs to be passed
```

**Comment by gmpreussner** [comment]
Here's some test code with generics and concepts for testing more complicated cases:

```nim
type Foo[T] = object
  r: T

converter toFoo[T: SomeReal](r: T): Foo[T] =
  result.r = r

proc `+=`*(x: var Foo, r: SomeReal) =
  x.r += r

var a: Foo[float]
a += 3.0
```

**Comment by gmpreussner** [comment]
Workaround:

```nim
a.r = a.r + 3.0
```

**Comment by Araq** [comment]
This is comparable to #3705 ?

**Comment by gmpreussner** [comment]
I think it's the same thing, yes. So, in this case, it seems that type converters take precedence over generics in overload resolution. I think that is OK, since generics appear to me less specified than converters; just something to be aware of.

**Comment by edubart** [comment]
I have run into this problem too, I'm avoiding using converters with generics until this is fixed.

**Comment by narimiran** [comment]
The original example still throws an error, but the example in the first comment works fine in Nim 0.19.0.

> I'm OK with closing this issue as "works as expected / per spec".

Should we close this, then?
