### ISSUE TITLE
nim 0.12.0 fails to bootstrap

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#3506]
In nim 0.12.0, the C code builds bin/nim fine, and bin/nim builds ./koch fine, but ./koch fails to bootstrap:

~~~~
$ PATH=./bin/:$PATH ./koch boot -d:release --passC:-D_FORTIFY_SOURCE=2 --passC:-g --passC:-O2 --passC:-fstack-protector-strong --passC:-Wformat --passC:-Werror=format-security --passL:-Wl,-z,relrols
iteration: 1
compiler/nim0 c -d:release --passC:-D_FORTIFY_SOURCE=2 --passC:-g --passC:-O2 --passC:-fstack-protector-strong --passC:-Wformat --passC:-Werror=format-security --passL:-Wl,-z,relrols compiler/nim.nim
Hint: system [Processing]
[..]
Hint: parseopt [Processing]
compiler/commands.nim(59, 16) Error: cannot open 'doc/basicopt.txt'
FAILURE
1
~~~~

I can work around this giving koch additional options: `-p:. -p:lib/packages/docutils` but this should not be necessary. Another work around is to add these lines to `config/nim.cfg` but that also seems inappropriate because this file is meant to be installed onto users' systems.

**Comment by infinity0** [comment]
If I only give `-p:.`, this is the error:

~~~~
$ PATH=./bin/:$PATH ./koch boot -d:release -p:. --passC:-D_FORTIFY_SOURCE=2 --passC:-g --passC:-O2 --passC:-fstack-protector-strong --passC:-Wformat --passC:-Werror=format-security --passL:-Wl,-z,relrols
iteration: 1
compiler/nim0 c -d:release -p:. --passC:-D_FORTIFY_SOURCE=2 --passC:-g --passC:-O2 --passC:-fstack-protector-strong --passC:-Wformat --passC:-Werror=format-security --passL:-Wl,-z,relrols compiler/nim.nim
Hint: system [Processing]
[..]
rstast.nim
compiler/docgen.nim(16, 40) Error: cannot open 'rstast'
FAILURE
1
~~~~

**Comment by infinity0** [comment]
Also, the options workaround does not work for `koch tests` because this does not take `-p` options.

**Comment by fschmill** [comment]
I had the same problem. In my case that helped:
koch boot -d:release -p:. -p:lib/packages/docutils

**Comment by dom96** [comment]
@Araq Any ideas what is going on?

**Comment by Araq** [comment]
Seems like people bootstrap with a ``nim`` in their ``/usr/bin``.

**Comment by infinity0** [comment]
Build processes should work regardless of what's in my PATH. When I'm building gcc I don't have to uninstall the system gcc first.

**Comment by dom96** [comment]
Agreed.

**Comment by Araq** [comment]
0.13.0 is out for a while now.
