### ISSUE TITLE
nim 0.12.0 atomicLoadN undeclared identifier

### ISSUE THREAD

**Issue by almikhail** [nim-lang/Nim#3510]
Cannot use procs from system/atomics. It seems that they are all undeclared. Under Ubuntu 15.04 following snippet of code fails to compile:

```
when isMainModule:
  let i = 1
  let j = system.atomicLoadN[int](addr i, ATOMIC_SEQ_CST)
```

Generated error: `atomicLoadN.nim(3, 18) Error: undeclared identifier: 'atomicLoadN'`

**Comment by Araq** [comment]
where do we claim that atomics is a general module of the stdlib?

**Comment by almikhail** [comment]
Indeed, in system module docs there are no mentions about atomics. But in system.nim "system/atomics" included and there defines a bunch of procs. How may i use it?

 Anyway, close it if it cannot been considered as a bug.

**Comment by dom96** [comment]
I don't think you can use those procedures directly. Unless you copy those into your module yourself. Why would you want to use them anyway?

I will close this in the meantime.
