### ISSUE TITLE
Packed pragma does not work on windows

### ISSUE THREAD

**Issue by Electric-Blue** [nim-lang/Nim#3511]
`Packed` pragma does not work on windows (win-10_x64 nim-0.12.0_x64) as expected.

``` nim
type
  testStruct {.packed.} = object
    field1: int8
    field2: int32

var
  testVar: testStruct

assert(sizeof(testVar) == 5)
```

The cause is bug in mingw compiler (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52991).
Adding `-t: "-mno-ms-bitfields"` to `nim.cfg` fixed this issue for me.

**Comment by cheatfate** [comment]
Same issue #4763.

**Comment by Araq** [comment]
Duplicate of #4763 and was fixed.
