### ISSUE TITLE
Math runningStats enhancements

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3512]
### Question 1
Should the stats stuff be a separate library from the main Math library?

##### Question 1(b)
If the answer to Q1 is to separate out the stats stuff into a separate library,

should an integrated StatsSequence be added which combines a seq with the RunningStats, 

or would this be a separate nimble package if someone wanted to do this.

The thought here is to save someone doing this themselves, and it makes the handling of stats related data behave very much like a normal sequence.

### Question 2
Should the RunningStats be enhanced with 
- Skewness
- Kurtosis

as shown on [this page](http://www.johndcook.com/blog/skewness_kurtosis/)

### Question 3
Should something like `RunningRegression` be added,

 as shown on [this page](http://www.johndcook.com/blog/running_regression/)

**Comment by Araq** [comment]
Well I like the RunningStat as it is, it's a feature that it only has O(1) storage requirements. Not sure about your additions. My gut feeling is that you should make a Nimble package for it. ;-)

**Comment by jlp765** [comment]
Q2 about skewness & Kurtosis just extends the existing RunningStats (still O(1)), needs two extra storage variables in the RunningStats object, and kurtosis() and skewness() procs.

Q3 is same O(1), but is pushing 2 values rather than 1 (doing linear regression on x,y values)
and has slope() intercept() and correlation() procs

The other enhancement (on the web pages) is adding a `+` and `+=` operators, in case anyone does parallel operations and wants to combine the results.

**Comment by Araq** [comment]
everything that keeps the O(1) storage requirement is fine with me. Please go ahead.

**Comment by jlp765** [comment]
Were you wanting to separate out the stats into a separate library from the Math library?  (wasn't sure if taking the opportunity to keep Math library smaller)

If so, I assume you want to do this as a library on nim-lang, then I can do a PR on that, else I'll do a PR on the current Math library

**Comment by Araq** [comment]
I have no opinion on that matter, do what you think is better.

**Comment by jlp765** [comment]
Check out PR #3519 and see what you think.

Because of extra calcs it is slightly slower (0.6 sec for 100_000_000 pushes of data) 
;-)

**Comment by Araq** [comment]
Was merged. Reopen if questions remain.
