### ISSUE TITLE
db_postgres: prepared statement already exists

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3513]
The problem occurs when I call `getValue` for the second time with the same sql query. `getValue` calls `setupQuery`, which attempts to create prepared statemend with the same name.

**Comment by jlp765** [comment]
#3520 fixes this by adding a random number to the query identifier

**Comment by Araq** [comment]
Has this been fixed, @dom96 ?

**Comment by dom96** [comment]
Yeah. Fixed via #3514
