### ISSUE TITLE
simultaneous 'profiler:on' and 'threads:on' flags crash

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#3517]
When compiling code with both flags 'profiler:on' and 'threads:on' set,
the resulting executable crashes without an error message.

Tried debugging with gdb and get:

`Program received signal SIGSEGV, Segmentation fault. 0x004330f3 in nimProfile ()``

 and

`Program exited with code 030000000005.`

Not that good with gdb, so I don't know the line number. Tried the '--debuginfo --linedir:on', but it
didn't work. Can try again if someone could tell me what else I have to do

Info:
Nim 0.12.0 Windows 32-bit
gcc 4.9.1 (the one that comes with Nim 32-bit Windows installer)
code sample: simple 'hello world' program

**Comment by kirbyfan64** [comment]
Can't reproduce with `0.12.1` on Linux 64-bit. What's the output if you run Nim with `--debuginfo --linedir:on` (as you said before), run `gdb resulting_output_file_here`, type `run` and hit enter, and then type `bt` and hit enter?

**Comment by matkuki** [comment]
kirbyfan64, here is the entire output of your instructions.

```
GNU gdb (GDB) 7.2
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from C:\Users\Matic\Desktop\NIMROD\Rapunzel/rapunzel.exe...done.
(gdb) run
Starting program: C:\Users\Matic\Desktop\NIMROD\Rapunzel/rapunzel.exe
[New Thread 2588.0x1048]

Program received signal SIGSEGV, Segmentation fault.
0x004331eb in nimProfile ()
(gdb) bt
#0  0x004331eb in nimProfile ()
#1  0x0043b4d1 in sysfatal_16826 ()
#2  0x0044c093 in systemDatInit000 ()
#3  0x0044ee6f in PreMain ()
#4  0x0044eea5 in NimMain ()
#5  0x0044eee6 in main ()
(gdb)
```

The compiler flags are: 
```--app:console --profiler:on --out:rapunzel.exe  --threads:on --debuginfo --linedir:on```

**Comment by narimiran** [comment]
> When compiling code with both flags 'profiler:on' and 'threads:on' set, the resulting executable crashes without an error message.

Cannot reproduce with Nim 0.19, Linux 64-bit.
