### ISSUE TITLE
Inconsistent results for variance and runningStats variance

### ISSUE THREAD

**Issue by mjoud** [nim-lang/Nim#3526]
I noted that `math.variance` returns the population variance (which is less interesting from my perspective), while `variance` for `RunningStat` returns the sample variance. Personally, I'd prefer to have both `variance` and `pvariance` (Python supports this since 3.4), or some parameter `delta` to be able to adjust this.

**Comment by jlp765** [comment]
#3519 will provide both population and sample var/stddev for RunningStats

**Comment by mjoud** [comment]
I know, and that's really an improvement! On top of that, the Welford algorithm used in `RunningStat` is more robust (cf. [John D. Cook's great post](http://www.johndcook.com/blog/2008/09/28/theoretical-explanation-for-numerical-results/)).

**Comment by mjoud** [comment]
Moving discussion to #3519.
