### ISSUE TITLE
Bounds check fails when using parallel

### ISSUE THREAD

**Issue by keeakita** [nim-lang/Nim#3528]
I'm getting a bounds check error with the following code:

``` nim
{.experimental.}
import threadpool

var res: array[2400, array[500, int]]

proc waste_time(): int=
    for i in 0 .. 9999:
        result += 1

var t = 1
parallel:
    var k = -1
    for j in 0 .. 9999:
        echo res[t][t]
        k = spawn waste_time()
```

`t` is always going to be 1, which is in bounds for this array access, but the Nim compiler doesn't seem to be able to prove it:

`foo.nim(14, 21) Error: cannot prove: t <= 499 (bounds check)`

Moving the declaration of t inside the parallel block does not seem to change anything. I can provide more information if needed. It may be unrelated, but also `--boundChecks: off` still results in the bounds check error above.

**Comment by kirbyfan64** [comment]
What if you do `let t = 1`?

**Comment by oslerw** [comment]
`let` produces the same error as `var`, both inside and outside the parallel block. `const` changes the error to a disjoint error `(1)..(1) not disjoint from (1)..(1)`.

**Comment by blaiseli** [comment]
I have a similar issue with the following piece of code:

```nim
    let bcProbs = nucProbs(bcSeq, bcQuals)
    proc likelihood(barcode: string): float =
      var letter: char
      var errProb: float
      let N = bcProbs.len
      result = 1
      parallel:
        for i in 0..<N:
          (letter, errProb) = bcProbs[i]  # `Error: cannot prove: i <= len(:envP.bcProbs2) + -1 (bounds check)`
          if letter == barcode[i]:
            result = result * (1 - errProb)
          else:
            result = result * (errProb / 3)
```

Maybe I do not understand the problem well enough, but since `N` has just been computed as the length of `bcProbs`, and the code doesn't appear to modify `bcProbs`, I would have expected `i` to be bounds-checkable.

**Comment by Araq** [comment]
> Maybe I do not understand the problem well enough, but since N has just been computed as the length of bcProbs, and the code doesn't appear to modify bcProbs, I would have expected i to be bounds-checkable.

It's outside of parallel's scope, it cannot know this. :-)

**Comment by blaiseli** [comment]
Sorry, but I still do not understand. This error also happens when I move `let N = bcProbs.len` inside the `parallel` block. Probably that's not what you meant by "It's outside of parallel's scope".

**Comment by Araq** [comment]
> This error also happens when I move let N = bcProbs.len inside the parallel block.

Yes and that's something ``parallel`` need to support eventually. ;-)

**Comment by blaiseli** [comment]
I tried a different approach to looping:

```nim
    let bcProbs = nucProbs(bcSeq, bcQuals)
    proc likelihood(barcode: string): float =
      var letter: char
      var errProb: float
      result = 1
      parallel:
        for i, np in bcProbs.pairs():
          (letter, errProb) = np
          if letter == barcode[i]:
            result = result * (1 - errProb)
          else:
            result = result * (errProb / 3)
```

And this time I get something completely different:
```
Error: internal error: invalid kind for first(tyTuple)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

`bcProbs` is a sequence of `NucProb` tuples, defined as follows:

```nim
type
  NucProb = tuple
    nucl: char
    prob: float
```

This sequence is generated using the following procs:

```
proc qualToProb(letter: char): float {.inline.} = pow(10, ((33 - ord(letter)) / 10))

proc nucProbs(sequence, qualities: string): seq[NucProb] =
  let N = min(sequence.len, qualities.len)
  result = newSeq[NucProb](N)
  for i in 0..result.high:
    result[i] = (nucl: sequence[i], prob: qualToProb(qualities[i]))
```

Should I file a separate issue?

**Comment by Araq** [comment]
`parallel` is moribund and you should use Malebolgia instead.
