### ISSUE TITLE
OpenBSD doesn't support AI_V4MAPPED (nim 0.12 posix.nim)

### ISSUE THREAD

**Issue by juanfra684** [nim-lang/Nim#3534]
```
cc -w -fno-strict-aliasing -O2 -pipe   -Ic_code -c c_code/7_2/stdlib_nativesockets.c -o c
_code/7_2/stdlib_nativesockets.o
c_code/7_2/stdlib_nativesockets.c: In function 'getaddrinfo_560408':
c_code/7_2/stdlib_nativesockets.c:218: error: 'AI_V4MAPPED' undeclared (first use in this
 function)
c_code/7_2/stdlib_nativesockets.c:218: error: (Each undeclared identifier is reported onl
y once
c_code/7_2/stdlib_nativesockets.c:218: error: for each function it appears in.)
```

**Comment by juanfra684** [comment]
I would like to update the OpenBSD port of Nim to the latest version. I can wait for a proper fix but meanwhile I need a workaround. Is it possible to disable the offending code or something similar? any idea?.

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/blob/devel/lib/pure/nativesockets.nim#L207
Guess you should add `or defined(openbsd)`.

**Comment by juanfra684** [comment]
Thanks for the help. I added OpenBSD to that line and deleted 'AI_V4MAPPED' from stdlib_nativesockets.c. The difference between FreeBSD and OpenBSD is that FreeBSD defines the macro, so the build of nim doesn't fail.

I've not tested the fix because I have another unrelated error. I will reopen the bug again if the fix doesn't work.

**Comment by dom96** [comment]
Please only close this once the issue is actually fixed in devel.
