### ISSUE TITLE
XP: could not import: inet_ntop

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3539]
nimble compiles on windows xp, but doesn't start because ``inet_top`` function doesn't exist on this OS

```
could not import: inet_ntop
```

Same problem described here: http://forum.nim-lang.org/t/1785

**Comment by dom96** [comment]
Windows XP is slowly turning into the new IE6.

**Comment by encorehu** [comment]
could not import: inet_ntop error gone, but jester cant response any data to webbrowser

**Comment by dom96** [comment]
does *asynchttpserver* work?

**Comment by encorehu** [comment]
asynchttpserver also worked, only jester with ERR_EMPTY_RESPONSE(on chrome)

**Comment by dom96** [comment]
@encorehu Could you investigate the cause of this error? I'm not sure when I will have the time to get a hold of an XP vm to investigate this problem. Maybe @vegansk could help too.

btw, @vegansk, are you still working on a PR to fix this issue?

**Comment by vegansk** [comment]
@Araq, not yet. Too much work at work, so I can continue only in february :-(

**Comment by encorehu** [comment]
@dom96  @vegansk I'm sorry, jester is still NOT worked on XP with vegansk's "my" branch. but httpserver, asynchttpser is ok.

**Comment by vegansk** [comment]
@encorehu, Our organization uses jester on XP in production. Furthermore, we use devel branch after fixing this issue. Maybe you should try the head version of jester?

**Comment by encorehu** [comment]
@vegansk you are right, i  used cmd  `nimble install jester`, and  jester example is OK now, thank you very much!
