### ISSUE TITLE
[doc] assert related documentation

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#3543]
In manual:  http://nim-lang.org/docs/manual.html
1. First use of `assert` should be hyperlinked. Not everyone has C background.
2. Even more the `doAssert`  in one example.
3. Section about exception tracking should mention assert exception as the exception.
4. Unrelated to assert: in http://nim-lang.org/docs/manual.html#pragmas-compilation-option-pragmas
   there could be column telling what is the default state.

In library doc: 
1. In http://nim-lang.org/docs/system.html#AssertionError there should be mention of special property of this exception (e.g. by pointing to the description at the end). An example for dummies wouldn't make a harm.
2. `raiseAssert` and `failedAssertImpl` could have some info. The first one should point what its `raises: [AssertionError]` means.
3. The `assert` template says:

> The compiler may not generate any code at all for assert if it is advised to do so through ...

Is the word "may" proper one here?
1. Example for the `onFailedAssert` should mention where on should put the handler (at the top or bottom?) and whether one can have more than one handler in single module.

**Comment by Araq** [comment]
No real bug here.
