### ISSUE TITLE
Invalid C code generated

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#3544]
The following code
```nim
type
  BaseEnv = ref object of RootObj
  Env = ref object of BaseEnv

proc init(self: var BaseEnv) =
  echo "hello"

proc init(self: var Env) =
  init(BaseEnv(self))
```

Results in this error:

nimcache/bad.c: In function ‘init_95026’:
nimcache/bad.c:108:14: error: request for member ‘Sup’ in something not a structure or union
  LOC1 = &self->Sup;
              ^

**Comment by Araq** [comment]
That has already been reported is actually a bug in the semantic checking. Your code is disallowed there is no subtype relation for 'var ref' types.
