### ISSUE TITLE
Bad error message "could not resolve"

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#3548]
```nim
import tables

var ttt = initTable[string, int](8)
ttt["a"] = "b"
```
results in the following error message:

Error: could not resolve: ttt["a"]

The error should mention the fact that "b" is type string but an int is expected

**Comment by dom96** [comment]
In certain cases this error message is really confusing:

```
proc foo(count: Natural) =
  for i in 0..count:
    echo("asd"[i .. i+1])
```

Results in:

```
Error: could not resolve: "asd"[i .. i + 1]
```

**Comment by alphashuro** [comment]
what does it mean? i'm getting this while trying to do `echo request.headers["Authorization"]` in a jester route

**Comment by alphashuro** [comment]
nvm figured it out, `[]` and other procs for httpHeaders are actually defined in httpcore, so I had to import it. why don't i get the `undeclared field` error i usually get though?
