### ISSUE TITLE
Error message pointing to system.nim instead of user code.

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#3551]
``` nim
type EnvException = object of Exception

proc newEnvException(msg: string): EnvException =
  return newException(EnvException, msg)
```

This code generates an error pointing to system.nim instead of user code:
lib/system.nim(2503, 3) Error: type mismatch: got (ref EnvException) but expected 'EnvException'

**Comment by nc-x** [comment]
```
t3551.nim(4, 22) Error: type mismatch: got <ref EnvException> but expected 'EnvException = object'
```
Can be closed?

**Comment by lhupfeldt** [comment]
Is it fixed?

**Comment by nc-x** [comment]
I tried the code with latest devel, and the error message points to the correct location. So I think it is fixed.
