### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#3552]
```nim
type Env = ref object of RootObj

proc newEnv(x: int): Env =
  new(result)

proc newEnv*(name: string): Env =
  new_env = newEnv(1)
```

Generates this error:

Hint: weird_error [Processing]
weird_error.nim(7, 3) Error: '(weird_error.newEnv|weird_error.newEnv)' cannot be assigned to

There is no distinction between the two newEnv procs and where is the assignment to newEnv?

**Comment by kirbyfan64** [comment]
Kind of weird, but the assignment to `newEnv` is correct. Nim is case- and underscore-insensitive, so `new_env` and `newEnv` are referring to the same thing.

I agree that the two procs in the error are weird, though!

**Comment by lhupfeldt** [comment]
Thank you, I forgot about case- and underscore-insensitivity. I believe the error message should explicitly mention this, someething like "new_env (same as newEnv) cannot be assigned to"

**Comment by lhupfeldt** [comment]
The following code actually compiles:

```nim

type Env = ref object of RootObj

proc newEnv(x: int): Env =
  new(result)

proc newEnv*(name: string): Env =
  var new_env = newEnv(1)
```

I would expect this to be illegal or at least give a warning about redefining global newEnv.

**Comment by Araq** [comment]
I see nothing wrong with the error message. Error messages should be short and meaningful and not constantly assume that you're a total newbie. You don't stay a newbie. ;-)
