### ISSUE TITLE
sleepAsync() not working on Mac OS X

### ISSUE THREAD

**Issue by eliezedeck** [nim-lang/Nim#3553]
On Windows, the following code would display "Bam 0" .. "Bam 9", which is to be expected. On Mac OS X though, using El Capitan 10.11.1 but I suspect this happens on all Mac versions, it is **hanging on the "Bam 0".**

```nim
import asyncdispatch

proc scheduleSend() {.async.} =
  for c in 0..<10:
    echo "Bam " & $c
    await sleepAsync(250)

asyncCheck scheduleSend()
runForever()
```

`sleepAsync()` is probably not implemented on Mac?

**Comment by dom96** [comment]
Works fine for me. Which version of Nim are you using?

**Comment by eliezedeck** [comment]
I'm using the one from brew, 0.12.0.

Best regards,
Elie Zedeck

**Comment by niv** [comment]
Can confirm that sleepAsync doesn't work here (on OSX) either. Hangs indefinitely.

**Comment by dom96** [comment]
@niv using 0.12.0 too? Works with devel for me.

**Comment by niv** [comment]
@dom96 Yes, 0.12.0 from homebrew. Haven't tried devel yet.

**Comment by dom96** [comment]
Please try devel if you can.

**Comment by oderwat** [comment]
I am also on 10.11.2. The code hangs with Nim 0.12.0 but works with Nim devel.

I would suggest do "brew remove nim" and install Nim using https://github.com/ekarlso/nim-vm which makes using devel and testing different versions of Nim trivial also on OS X.

**Comment by dom96** [comment]
Since it works with ``devel`` I will close.
