### ISSUE TITLE
404 for documentation for module nativesockets

### ISSUE THREAD

**Issue by debunge** [nim-lang/Nim#3555]
I'm using rawsockets, compiler complains 

lib/deprecated/pure/rawsockets.nim(4, 10) Warning: rawsockets module is deprecated, use nativesockets instead 
I follow link from http://nim-lang.org/docs/net.html#Socket  to http://nim-lang.org/docs/nativesockets.html and get 404.

**Comment by dom96** [comment]
Fixed now
