### ISSUE TITLE
Feature request: compile-time proc `hasField` for Nim nodes

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#3557]
**Summary:** I am requesting a compile-time proc `hasField`, that will behave like [Python's `hasattr` function](https://docs.python.org/2/library/functions.html#hasattr), to test whether a NimNode has a particular field.

This idea results from the code I posted in this forum thread: http://forum.nim-lang.org/t/1808#11339

In the `devel` branch, a node of kind `nnkCommentStmt` now has a field `.strVal` to access the text of the documentation comment.  This is great.

However, if I attempt to compile that code with a previous version of Nim, the compilation fails with an error:
```
test1.nim(18, 18) Error: field 'strVal' cannot be found
```

It would be very convenient to be able to wrap new code like this in an if-statement, so that the field access will only be attempted if the field is present:
```
if node.hasField("strVal"):
  doSomethingWith(node.strVal)
```

Since macros are interpreted in a VM at compile-time, there's really no reason we can't derive maximum benefit from this interpreted language style, right?

**Comment by reactormonk** [comment]
There's `declared` might work:

    if declared(node.strVal):
      doSomethingWith(node.strVal)

**Comment by jboy** [comment]
Ah, you're right.  That does work, thank you!

**Comment by JesseTG** [comment]
Still could be good syntactic sugar, tough.  Hell, you could just put it in the standard library.

**Comment by reactormonk** [comment]
@JesseTG I don't see how `node.hasField("strVal")` would be more readable than `declared(node.strVal)`. Also, `declared` is a more generic concept that can be applied to a lot more situations. So you'd have to learn about two - `hasField` and `declared`.
