### ISSUE TITLE
db_postgres broken in v0.12.0?

### ISSUE THREAD

**Issue by boydgreenfield** [nim-lang/Nim#3560]
I'm getting a variety of odd errors with Nim v0.12.0 and the `db_postgres` module, which I suspect are related to this pull request (https://github.com/nim-lang/Nim/pull/3334) and this issue (https://github.com/nim-lang/Nim/issues/3430).

For example, the following insert `conn.insertId(sql("INSERT into files (id, name) VALUES (?, ?)"), fileId, fileName)` fails as it's being treated like a prepared statement:

```
Error: unhandled exception: ERROR:  prepared statement "setupQuery_Query_INSERT into files (id, name) VALUES (?, ?) RETURNING id" does not exist
 [EDb]
```

Here's a gist for reproducing the above error (note one needs to `psql -c 'create database test;'` for this to work: https://gist.github.com/boydgreenfield/5e139345dfd150618153

Needless to say, this is a big breaking regression if I've not done something really silly or missed a syntax change.

**Comment by boydgreenfield** [comment]
@dom96 are you able to reproduce with the gist?

**Comment by dom96** [comment]
@boydgreenfield Just tested it, this seems incorrect https://gist.github.com/boydgreenfield/5e139345dfd150618153#file-new_test-nim-L5, change ``name`` to ``filename`` in the sql query.

**Comment by dom96** [comment]
The error I got seems more clear:

```
Error: unhandled exception: ERROR:  column "name" of relation "files" does not exist
LINE 1: INSERT into files (id, name) VALUES ('1', 'hello.tmp') RETUR...
                               ^
 [EDb]
```

**Comment by boydgreenfield** [comment]
Sorry, will fix that in the gist (had fixed it locally). With that change I get weird state duplicate key errors, which obviously shouldn't happen:

```
f1 is 1
Traceback (most recent call last)
test.nim(33)             test
test.nim(5)              addToDb
db_postgres.nim(323)     insertID
db_postgres.nim(310)     tryInsertID
db_postgres.nim(175)     setupQuery
db_postgres.nim(97)      dbError
Error: unhandled exception: ERROR:  duplicate key value violates unique constraint "files_pkey"
DETAIL:  Key (id)=(1) already exists.
 [EDb]
```


I suppose the broader point is that I have quite a bit of `db_postgres` code that's breaking with weird error messages upon upgrading to v0.12.0. Has this affected, e.g., the forum? (Or is that SQLite-backed?)

**Comment by theduke** [comment]
I haven't looked at your gist, but the duplicate key error might be related to : #3569 .

**Comment by boydgreenfield** [comment]
@theduke Yes maybe? I still find it odd that the `PreparedStatement` code path even gets triggered here – relates to this patch https://github.com/nim-lang/Nim/commit/c0179043639ceab4f146fda2eec906fc30740b4b apparently, but I suppose we really need to take a deeper look at the v0.11.2 vs. current `db_postgres.nim` diff...

**Comment by Araq** [comment]
Snippet now works for me.

**Comment by dom96** [comment]
Can confirm it works.
