### ISSUE TITLE
async breaks when applied to a generic proc

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#3568]
``` nim
import asyncdispatch
proc foo(x: auto) {.async.} = discard
discard foo(1)
```

```
lib/pure/asyncdispatch.nim(1468, 7) Hint: Processing recvLine as an async proc. [User]
lib/pure/asyncdispatch.nim(1468, 7) Hint: Processing foo as an async proc. [User]
asyncbug.nim(3, 12) template/generic instantiation from here
lib/pure/os.nim(1167, 9) Error: implementation of 'fooIter' expected
```

**Comment by dom96** [comment]
Did some investigation:
```nim
import asyncdispatch

proc test[T](x: T): Future[T] {.async.} =
  result = x + 5

proc test2[T](x: T): Future[T] =
  var retFuture = newFuture[T]("test")
  iterator test2Iter(): FutureBase {.closure.} =
    {.push, warning[resultshadowed]: off.}
    var result: T
    {.pop.}
    result = x + 5
    complete(retFuture, result)

  createCb(retFuture, test2Iter, "test2")
  return retFuture

asyncCheck test2(5)
```
The ``test2`` procedure is what the ``async`` macro emits from the ``test`` proc above. Calling ``test2`` works, but calling ``test`` results in error that @ephja reported.

Because of this I have a feeling that this is a compiler bug.

**Comment by dom96** [comment]
@Araq please advise.

**Comment by Araq** [comment]
> The only differences I see are Ident and Sym, which shouldn't make a difference(?).

It makes a huge difference. It's a compiler bug, but no VM bug.

**Comment by ephja** [comment]
this issue could not be reproduced according to #4856, and I can't reproduce it anymore either.

**Comment by andreaferretti** [comment]
Same for me: both examples run fine now. @ephja @dom96 can we close this?

**Comment by TiberiumN** [comment]
Compiles for me
@dom96 close?
