### ISSUE TITLE
Invalid Cannot prove .. not nil

### ISSUE THREAD

**Issue by theduke** [nim-lang/Nim#3601]
This code leads to a 'cannot prove that x is not nil' error.
Why?
The msg argument is annotated with not nil, and "test" is const, so it should be ok.

``` nim
type A = ref object
  discard

proc doSomething(a: A not nil, msg: string not nil) =
  var x: string not nil = "test" & msg
```

**Comment by theduke** [comment]
Is the not nil system in such a big flux right now that I shouldn't even report such issues?

**Comment by Araq** [comment]
Good question. Yes, I think so.

**Comment by Araq** [comment]
Not a bug, there is no typing rule like "``&`` on two not-nil strings produces a not-nil string".
