### ISSUE TITLE
Nim 0.12.0 fails to import `rstast` when importing `compiler.modules`

### ISSUE THREAD

**Issue by dfdeshom** [nim-lang/Nim#3607]
I have a test program with the following line:

    import compiler.modules

and it fails to compile:

    $ nim c test.nim
    /home/dfdeshom/.nimble/pkgs/compiler-0.12.0/compiler/docgen.nim(16, 40) Error: cannot open 'rstast'

**Comment by Araq** [comment]
I don't think that's specific to 0.12.0. You need to add --path:$lib/packages/docutils  to your config.

**Comment by dfdeshom** [comment]
Ah, good to know. Yep, that worked, thanks!
