### ISSUE TITLE
incorrect `ProveInit`with delayed initialization of field

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#3608]
``` nimrod
proc make[T](): T = new(result)
```

produces warning:

``` text
nimpng.nim(1926, 7) Warning: Cannot prove that 'result' is initialized. This wil
l become a compile time error in the future. [ProveInit]
```

how could the 'result' is not initialized? :smile:

**Comment by Araq** [comment]
Not enough context. It could be that 'result' has not-nil fields etc.

**Comment by jangko** [comment]
```nimrod
type
  xx = ref object of RootObj
    a: range[0..0x7FFFFFFF]
    
  zz = ref object of xx
    b: range[1..0x7FFFFFFF]
    
proc make[T](): T = new(result)

discard make[xx]()
discard make[zz]()  #if this line is removed, the warning dissapear
```

shouldn't both line cause warning? and why uninitialized range should become compile time error in the future?

**Comment by jangko** [comment]
this very simple example also produce incorrrect warning same as above

```nimrod
type
  abc* = ref object
    w: range[2..100]
    
proc createABC(): abc =
  new(result)
  result.w = 20 #i think the compiler missed to check this part
```

the warning doesn't make any sense, right?

**Comment by Araq** [comment]
On the contrary, it works as designed. That doesn't mean I like it, but it is not a bug.

Use this instead:

```nim
proc createABC(): abc =
  result = abc(w: 20)
```

**Comment by jangko** [comment]
then it is an unpleasant feature, reduce code/coding flexibility

**Comment by Araq** [comment]
IME it works well enough.

**Comment by andreaferretti** [comment]
@Araq Your suggestion works in this simple case, but not in more complex ones. For instance

```nim
type
  Foo* = ref object
    w: range[2..100]
  Bar* = ref object
    w: range[10..50]

template create(result: expr) =
  new(result)
  result.w = 20

proc createFoo(): Foo = create(result)

proc createBar(): Bar = create(result)
```

In the template here you do not know if you are creating a `Foo` or a `Bar`, but you want to perform the same operations.

This is not a theoretical possibility: it is happening [always to me](https://github.com/unicredit/linear-algebra/blob/master/private/initialize.nim#L100-L140) when dealing with similar 32-bit/64-bit code.

**Comment by kirbyfan64** [comment]
Couldn't you do something like (untested):

```nim
result = new type(result)
```

**Comment by andreaferretti** [comment]
In [my case](https://github.com/unicredit/linear-algebra/blob/master/private/initialize.nim) `result` is one of the two following types:

```nim
type
  Matrix32*[M, N: static[int]] = object
    order: OrderType
    data: ref array[N * M, float32]
  Matrix64*[M, N: static[int]] = object
    order: OrderType
    data: ref array[M * N, float64]
```

Changing

```nim
template makeSMatrixPrivate(M, N, f, order, result: expr) =
  new result.data
  result.order = order
  # ...
```

into

```nim
template makeSMatrixPrivate(M, N, f, order, result: expr) =
  result.data = new type(result.data)
  result.order = order
  # ...
```

did not make the warning go away.

**Comment by Araq** [comment]
But that might work: 

```nim

template makeSMatrixPrivate(M, N, f, orderParam, result: expr) =
  result.data = type(result.data)(order: orderParam)
  # ...
```

**Comment by andreaferretti** [comment]
Unfortunately, it doesn't seem to work. I have switched to this style in a [proveinit branch](https://github.com/unicredit/linear-algebra/tree/proveinit) of linalg, but the warnings are still there (just try `nimble test` on that branch).
