### ISSUE TITLE
Tests failing on Travis/koch

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3618]
Travis failing:

3 tests fail

```
tests/concepts/tmanual.nim
tests/misc/tlocals.nim
tests/types/tisopr.nim
```
On my local win7 PC,

running each individually works as expected (output matches what is expected).
running via `koch test r tests\...\t....nim` fails as follows:
- `tisopr` passes (but Travis fails with unhandled exception: false)
- `tmanual` fails with `type mismatch: got (seq[int])`
- `tlocals` fails with `internal error: (filename: ast.nim, line: 1561)`

`tmanual` code doesn't return a seq[int], but echo's individual values

Line 1561 in ast.nim is the internalAssert in the following:
```
proc skipGenericOwner*(s: PSym): PSym =
  internalAssert s.kind in skProcKinds
  ## Generic instantiations are owned by their originating generic
  ## symbol. This proc skips such owners and goes straight to the owner
  ## of the generic itself (the module or the enclosing proc).
  result = if sfFromGeneric in s.flags: s.owner.owner
           else: s.owner
```
So in summary:
- tester produces different results (or interprets the result differently) compared to when they are run as a stand-alone compiled exe
- Travis running tester produces a different result to tester running on my PC (for tisopr.nim)

**Comment by Araq** [comment]
These all work now for me.
