### ISSUE TITLE
testing: assert() or doAssert()

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3630]
I note that there are a lot of lines with ``assert()`` in the test files  (500 to be precise).

``koch test r tests\somedir\txxxxx.nim`` compiles with -d:release 
so ``assert()`` is skipped.

##### Question 
Should it be ``assert()`` or ``doAssert()`` in txxxxx.nim test files ?

**Comment by Araq** [comment]
doAssert().
