### ISSUE TITLE
AppVeyor test failures

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#3633]
#### BoehmGC
Looks like the dll for boehmgc is not installed, if I read the following error correctly

```
FAIL: client.nim --gc:boehm -d:useNimRtl
Test "tests/dll/client.nim" in category "dll"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
 
Gotten:
exitcode: 1
 
Output:
 
 
```

#### Jester
Jester nimble package required?
```
FAIL: tasync_cpp.nim
Test "tests\cpp\tasync_cpp.nim" in category "cpp"
Failure: reNimcCrash
Expected:
 
 
Gotten:
cannot open 'jester'
 ```

#### Test "tests/manyloc\nake\nakefile.nim"
Don't know about this one!

**Comment by dom96** [comment]
Why the close?

**Comment by jlp765** [comment]
It looked like AppVeyor was removed from the CI test suite, so was no longer necessary.

**Comment by kirbyfan64** [comment]
I thought AppVeyor was only temporarily disabled because everyone got sick of looking at failing tests...

**Comment by Araq** [comment]
AppVeyor has annoying timeouts we need to find something better.
