### ISSUE TITLE
Error: implementation of 'math.randomize()' expected

### ISSUE THREAD

**Issue by hohlerde** [nim-lang/Nim#3640]
Using the latest devel branch under Ubuntu 15.10 and get the error "Error: implementation of 'math.randomize()' expected at line 155 col 8" when compiling the following code:

```
import math

echo "Test"
```

```
Nim Compiler Version 0.12.1 (2015-12-10) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 1a73cef7654f8adbdd672ba752e9b13b18a170b1
active boot switches: -d:release
```

**Comment by qqtop** [comment]
No problem on Opensuse Leap42.1

```nimrod
   Nim Compiler Version 0.12.1 (2015-12-11) [Linux: amd64]
  Copyright (c) 2006-2015 by Andreas Rumpf

  git hash: 1a73cef7654f8adbdd672ba752e9b13b18a170b1
  active boot switches: -d:release

```

**Comment by hohlerde** [comment]
Sorry, problem was on my side. Still had a "cc = vcc" entry in my nim.cfg file and thus compilation stopped with the above error. Changed it to gcc and everything worked.

Sorry again for the confusion.
