### ISSUE TITLE
Segfault using times module with threads

### ISSUE THREAD

**Issue by hohlerde** [nim-lang/Nim#3642]
When compiling and running the following code (testme.nim) under Ubuntu 15.10 with the devel branch, I get a segfault pretty fast.

```nimrod
import times, os

var
  workerThread1: Thread[tuple[na: int]]
  workerThread2: Thread[tuple[na: int]]

proc workerRun1(params: tuple[na: int]) {.thread.} =
  while true:
    let k = getDateStr()
    echo "1: ", k
    sleep(10)

proc workerRun2(params: tuple[na: int]) {.thread.} =
  while true:
    let k = getDateStr()
    echo "2: ", k
    sleep(10)

createThread(workerThread1, workerRun1, (na:0))
createThread(workerThread2, workerRun2, (na:0))

joinThread(workerThread1)
joinThread(workerThread2)
```

Output:
```
2: 2015-12-12
1: 2015-12-12
2: 2015-12-12
1: 2015-12-12
2: 2015-12-12
1: 2015-12-12
2: 2015-12-12
1: 2015-12-12
1: 2015-12-12
Traceback (most recent call last)
testme.nim(15)           workerRun2
times.nim(583)           getDateStr
times.nim(444)           getLocalTime
times.nim(403)           tmToTimeInfo
times.nim(489)           getTzname
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Nim devel version:
```
Nim Compiler Version 0.12.1 (2015-12-10) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 1a73cef7654f8adbdd672ba752e9b13b18a170b1
active boot switches: -d:release
```

**Comment by rbehrends** [comment]
Many time-related functions are not threadsafe. For example, `localtime()` (which is called by `getDateStr()`) is actually required to set the global variable `tzname` (and returns a pointer to a shared location).

**Comment by Varriount** [comment]
Could a lock be used to make the procedures threadsafe?

**Comment by rbehrends** [comment]
It's more involved than that. Keep in mind that third-party libraries may also be calling `localtime()` and friends and mess up the shared state. Also, this may lead to undesirable serialization bottlenecks. In principle, the best solution would be to use the reentrant functions such `localtime_r()` and use a fallback implementation with locks on systems that are not available. However: even the so-called re-entrant functions are still permitted to mess with the global state (such as setting `tzname`), even if most implementations do not do that, so you want to query `tzname`, `timezone`, and `daylight` variables exactly once at startup and store the result in static memory.

**Comment by endragor** [comment]
@Araq 
Isn't this issue a high priority or showstopper? This seems like a very common use case in a multithreaded app.

**Comment by Araq** [comment]
Is this still an issue? I thought we fixed that long ago.

**Comment by hohlerde** [comment]
Tested with the example in the opening posts with the latest devel as of now. Works now.

Thanks a lot!
