### ISSUE TITLE
nim compiler: out switch for libraries

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3644]
When the `--out` switch is used for executable, it works fine. But the switch is completely ignored when used for library.

**Comment by vegansk** [comment]
Also, when Visual C compiler is used, it generates pdb file named `$projectname.pdb`.

**Comment by narimiran** [comment]
> When the `--out` switch is used for executable, it works fine. But the switch is completely ignored when used for library.

Works on Nim 0.19.9
