### ISSUE TITLE
execProcesses poParentStreams option silently disabled on Posix

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#3659]
`osproc` contains very useful procedure `execProcesses` that allows executing multiple processes at once, from main (supervising) Nim process. In order to be able to see the output of each process, we need to either read from its `stdout/err` handle or use `poParentStreams` that redirect process `stdout/err` to parents (Nim supervisor) streams.

Unfortunatelly for some reason `poParentStreams` is disabled in the code with some vague comment made by @Araq:

> `# poParentStreams causes problems on Posix, so we simply disable it:`

What problems!? Is disabling such key option `poParentStreams` which is also a default option to this function right? If there are some problems we should put that into the docs and let the developer make a decision, rather than disabling it altogether.

FYI it was disabled in 61792dc7d6926bcaeed858f9acc00ec7e1517724, but the commit does not explain the reason of this.

**Comment by Araq** [comment]
IIRC the implementation of poParentStreams was never finished for Posix or my implementation didn't work. I'm not an expert for Posix, so please help.

**Comment by narimiran** [comment]
> Unfortunatelly for some reason poParentStreams is disabled in the code

Not anymore (Nim 0.19.9).
