### ISSUE TITLE
Async HTTP server no longer works with mark&sweep GC (or any other than RC)

### ISSUE THREAD

**Issue by nanoant** [nim-lang/Nim#3660]
Change introduced by 28e3ad945a100fd0e669bcedb7d28ddd540b6978 now makes the `asynchttpserver` crash on some more than trivial load when using non-default mark&sweep GC, that has better performance than default reference counting as outlined at my [WebFrameworkBenchmark](https://github.com/nanoant/WebFrameworkBenchmark).

In order to identify this commit I did bisection and test with simple Nim server:

``` nim
import asynchttpserver, asyncdispatch, strtabs

var server = newAsyncHttpServer(true)
proc cb(req: Request) {.async.} =
  await req.respond(Http200, "Hello World",
    {"Content-Type": "text/html"}.newStringTable())

asyncCheck server.serve(Port(8080), cb)
runForever()
```

The server was tested with [wrk](https://github.com/wg/wrk) with following params:

```
wrk -t4 -c100 -d10S --timeout 2000 -H 'Connection: keep-alive' http://localhost:8080/
```

After 28e3ad945a100fd0e669bcedb7d28ddd540b6978 commit Nim server crashes on invalid memory access when built with `--gc:markandsweep`.

```
Traceback (most recent call last)
http.nim(9)              http
asyncdispatch.nim(1617)  runForever
asyncdispatch.nim(1032)  poll
asyncdispatch.nim(1149)  cb
asyncdispatch.nim(213)   complete
asyncdispatch.nim(1257)  cb
asyncnet.nim(385)        recvLineIntoIter
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/Users/ono/Code/Projects/Nim/http '
```

@dom96 Can you please look at this. As this is change introduced by you.

**Comment by dom96** [comment]
This was consciously introduced by me. @Araq agreed to fix the M&S GC for this.

See comment here: https://github.com/nim-lang/Nim/pull/2606#issuecomment-96762212

**Comment by nanoant** [comment]
@dom96 Thanks for info, then the ball is on @Araq's court then.

**Comment by andreaferretti** [comment]
This error does not happen for me anymore. Maybe the mark and sweep GC has been fixed?

**Comment by dom96** [comment]
Closing. Reopen if you can still reproduce it @nanoant.
