### ISSUE TITLE
--stdout switch isn't working

### ISSUE THREAD

**Issue by dcbrwn** [nim-lang/Nim#3668]
```
{ nimtest }  » nim js --stdout main.nim                                                                                                      ~/lab/nimtest
Hint: system [Processing]
Hint: main [Processing]
Hint: operation successful (4683 lines compiled; 0.062 sec total; 2.256MB; Debug Build) [SuccessX]
{ nimtest }  »  
```

Could some one clarify meaning of --stdout switch? I assumed that this will force nim compiler to print compiled source into stdout. Am I wrong?

I want to develop gulp plugin to transpile nim sources to JS and ability to print compilation result to stdout will dramatically simplify development of such thing.

**Comment by zielmicha** [comment]
No, it only causes the compiler to output error messages to stdout.

**Comment by dcbrwn** [comment]
Oh, ok. Thanks!
