### ISSUE TITLE
Output when dynamic library can't be loaded, but alternative is available

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#3674]
Since https://github.com/nim-lang/Nim/commit/5b35efe5b72e97d103ffd4dbe42aece67b5c4324 an error message is printed when a dynamic library can't be loaded. This is a problem when we have alternative library versions that are later loaded successfully. For example on my system this code from the pcre module
```nim
const pcreDll = "libpcre.so(.3|.1|)"
```
fails to load `libpcre.so.3`, but then successfully loads `libpcre.so.1`. This causes tests to fail:
```
FAIL: tregex.nim
Test "tests/stdlib/tregex.nim" in category "stdlib"
Failure: reOutputsDiffer
Expected:
key: keyAYes!

Gotten:
libpcre.so.3: cannot open shared object file: No such file or directory
key: keyAYes!
```
I'm not sure how this should be fixed. I would simply revert the commit.

**Comment by Araq** [comment]
I reverted it, it can be enabled with -d:nimDebugDlopen or something.
