### ISSUE TITLE
timeToTimeInfo issue

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3678]
Today (Thu Dec 31 12:04:40 2015), timeToTimeInfo fails. The code:

``` nimrod
import times

let ts = 1451541880.Time
echo ts
let ti = ts.timeToTimeInfo
echo ti
```

fails with overflow exception:

```
Thu Dec 31 12:04:40 2015
Traceback (most recent call last)
time_issue.nim(5)        time_issue
times.nim(1163)          timeToTimeInfo
system.nim(2533)         sysFatal
Error: unhandled exception: value out of range: 0 [RangeError]
Error: execution of an external program failed: '/home/vega/work/nim/nimtests/issues/new/time_issue '
```

If I run it in release mode, it shows this dates:

```
Thu Dec 31 12:04:40 2015
Thu Jan  0 07:04:40 2016
```

**Comment by coffeepots** [comment]
Changing line 1157 & 1160 of times module from

    1157     md = days
    1160     h = daySeconds div secondsInHour + 1

to

    1157     md = if days>0: days else: 31
    1160     h = daySeconds div secondsInHour

Works for the value you give, but not sure if that breaks it for other times.
The problem looks like it's in countYearsAndDays, where

    result.days = days mod 365

returns zero for the last day of the year?

**Comment by dom96** [comment]
Time & date code sure is tricky. (Thanks to Julius Caesar et al.)

@coffeepots Please make a PR (make sure to add this as a test case at the bottom of ``times`` or wherever the tests for it are.)

**Comment by coffeepots** [comment]
I might have missed it, but do we have everything in the times module except a way to actually initialise the Time type in one operation?
I'm thinking it might be nice (or rather, necessary) to have an initTime that takes a string. I can use the parse function for TimeInfo and convert it back to a time if that's not too inefficient.
Initialising Times will also make it less awkward to create tests.

**Comment by dom96** [comment]
@coffeepots The ``Time`` type is just an int, what we have is a ``fromSeconds``. 

> I can use the parse function for TimeInfo and convert it back to a time if that's not too inefficient.

Yeah, just do that I think.

**Comment by coffeepots** [comment]
@dom96 There seems to be a further issue with times:
@vegansk originally wrote:

```nim
let ts = 1451541880.Time
echo ts # "Thu Dec 31 12:04:40 2015"
```

However, when I run this code I get:
```nim
let ts = 1451541880.Time
echo ts # "Thu Dec 31 06:04:40 2015"
```
I get 1451563480.0 for Thu Dec 31 12:04:40 2015.

@vegansk are you running some Linux flavour? I'm running Windows, so this might be why they disagree. If you're also running Windows then I dunno what's going on. However, regardless there is 6 hours difference for the same value of Time. If it's platform dependent I'm unsure what to do about it, if anything.
For info, I'm running devel Nim from 23/11/2015.

Also, any preferences over the default time layout? "yyyy-MM-dd hh:mm:ss" is more zone insensitive, whereas "ddd MMM dd hh:mm:ss yyyy" is the display format for Times.

**Comment by dom96** [comment]
@coffeepots I get the same as you (On Mac OS X). Maybe timezone difference? Looks like this agrees: http://www.epochconverter.com/.

In any case, fixing the crash should be the priority.

**Comment by vegansk** [comment]
@coffeepots, I've got the same crash on windows and linux. But my timezone is GMT+6

**Comment by coffeepots** [comment]
So... @vegansk, @dom96   I just realised that timeToTimeInfo is completely unnecessary, and you should use getLocalTime(t: Time): TimeInfo.

I completely glossed over that function, assuming that it returned the local time, but it in fact breaks down the time into TimeInfo for you.
After spending some time trying to get this code to work in all the myriad exceptional situations calenders create, it is already done and functional!

The timeToTimeInfo function should therefore either be removed, or just be an alias to getLocalTime.

**Comment by dom96** [comment]
Okay. Please deprecate it (make sure to add a doc comment like ``**Warning:** This procedure is deprecated since Nim 0.12.4, use getLocalTime or getGMTime.``). In addition, please add documentation at the top of the ``times`` module to show the basics of how the module should be used.

**Comment by vegansk** [comment]
@coffeepots, got it. Thanks!

**Comment by coffeepots** [comment]
Just thinking about how to do timeToTimeInterval.

Currently thinking of something like this:

```
proc timeToTimeInterval*(t: Time): TimeInterval =
  var tInfo = t.getLocalTime()
  initInterval(0, tInfo.second, tInfo.minute, tInfo.hour, tInfo.weekday.ord, tInfo.month.ord, tInfo.year)
```

This would mean "Thu Dec 31 06:04:40 2015"
Becomes a TimeInterval of:
(milliseconds: 0, seconds: 40, minutes: 4, hours: 6, days: 3, months: 11, years: 2015)

Is that what people would expect from a time -> time interval conversion?

**Comment by coffeepots** [comment]
Changes proposed here: https://github.com/nim-lang/Nim/commit/0ac1d68aaf0cdd6319a3433610073161af76844a

**Comment by GULPF** [comment]
This can be closed. `timeToTimeInfo` has now been deprecated for over two years.

**Comment by FedericoCeratto** [comment]
It should be moved when timeToTimeInfo is removed.
