### ISSUE TITLE
docopt import nre cause Error: redefinition of 'util'

### ISSUE THREAD

**Issue by encorehu** [nim-lang/Nim#3680]
c:\documents and settings\administrator\.nimble\pkgs\nre-1.0.0\private\util.nim(1, 2) Error: redefinition of 'util'

docopt 

    import nre
    import private/util   #this is docopt/private/util.nim

but in nre module 
also has 

    import private/util  # this is nre/private/util.nim

i think this is nim compiler's fault.

**Comment by Araq** [comment]
what is docopt? Need more context.

**Comment by reactormonk** [comment]
https://github.com/docopt/docopt.nim I assume. Got a snippet to reproduce?

**Comment by encorehu** [comment]
i use nim-0.11.2, and want to write a app to parse command line args, so i use docopt lib, but when i compile the source , i get the error Error: redefinition of 'util'.
