### ISSUE TITLE
new macros.getType behavior

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#3681]
In a conversation with Araq I found out that getType needs some attention, and an implementation that returns two values, the name, and the implementation would be appropriate. The idea is, that the name from the macros.getType should always represent the same structure as typetraits.name.

[Here](https://gist.github.com/krux02/51947553c359524c1742) is a test file, with the current behavior, and my thoughts about what I think would be more approprate. Once I implemented getType with the macros.getType and once with the typetraits.name proc.

**Comment by jangko** [comment]
i remember my cancelled PR #3652, macros.getType really need more attention

**Comment by krux02** [comment]
I would like to have a more complete mockup, including feedback from the community. Araq also mentioned that `macros.getType` needs attention, and that a breaking change is ok, as long as it is not a silent breaking change. To be honest I think, that get type should work in conjuction with `macros.getImpl`. I have no idea how the current get type works, all I can see is that is extremely inconsistent in almost everything. I think that the current implementation of `getType` tries to do something that doesn't work out. But I would like to understand the current design better, before I refuse it. I would like to have a qualified argument why it is bad, and where it fails.

**Comment by krux02** [comment]
We now have ``getTypeInst`` and ``getTypeImpl``, I like them. ``getType`` should be deprecated.
