### ISSUE TITLE
static dispatch on `macros.getAst` is broken.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#3682]
If I call a macro from another macro via `macros.getAst`, correct static dispatch based on the type of the expression dosn't work at all.

```
import macros

macro inner( t : typeDesc[int] ): string = "int"
macro inner( t : typeDesc[float] ): string = "float"

macro outer(a:typed): string = 
  result = getAst( inner(a) )

echo "inner(int): ", inner(int)      # inner(int): int
echo "outer(int): ", outer(int)      # outer(int): int
echo "inner(float): ", inner(float)  # inner(float): float
echo "outer(float): ", outer(float)  # outer(float): int    !! <-  WRONG
```

I also tried to call templates instead of macros, or used expressions that are not a typeDesc. None of them work.

**Comment by Araq** [comment]
``getAst`` wasn't designed for this at all so it's no surprise it doesn't work. The results are interesting nonetheless.

**Comment by krux02** [comment]
I got to this problem, because I needet to branch in my macro dependent of the type that I pass to my macro. I couldn't find a single way to do it. I am currently working on getType, so that at least getType gives me sufficient information.

**Comment by Araq** [comment]
This is now rejected properly. ``getAst``  now does overloading resolution but not in a way that's helping you for this case, sorry.
