### ISSUE TITLE
Error in `install_nimble.nims`

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#3685]
The script to install nimble is now broken with the new release 0.7.0 of nimble.

If nimble is installed through the script, it is not able to load nimscript resources. In particular, this failure can be shown by running `nimble install nimble@#head`.

The script should be fixed to follow the procedure outlined in the [README](https://github.com/nim-lang/nimble)

**Comment by Araq** [comment]
I fixed it, but it needs more testing.

**Comment by andreaferretti** [comment]
Great! Works for me (on Ubuntu 15.04)
