### ISSUE TITLE
Error in concepts when using functions on typedesc

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#3686]
I am trying to use concepts to define algebraic typeclasses such as monoids. My attempt goes like

```nim
proc z(x: typedesc[int]): int = 0
proc z(x: typedesc[float]): float = 0.0

type Monoid = concept x, y
  x + y is type(x)
  z(type(x)) is type(x)

echo "int is monoid -> ", 3 is Monoid # prints false
let x = 3
echo z(type(x)) # prints 0
```

As shown above, if `x` is an `int`, the function `z(type(x))` correctly reports `0`, but nevertheless `int` is not considered a monoid

**Comment by Araq** [comment]
What does ``--reportConceptFailures:on`` produce?

**Comment by andreaferretti** [comment]
It reports

```
example.nim(5, 3) Error: type mismatch: got (typedesc[int])
but expected one of: 
example.z(x: typedesc[int])
example.z(x: typedesc[float])
```

**Comment by Araq** [comment]
That's funny.

**Comment by andreaferretti** [comment]
I'd be willing to look on this. Since I am not familiar with the compiler: any hint where to start looking for concept failures?

**Comment by Araq** [comment]
``sigmatch.nim`` and ``semCompiles`` in ``semexprs.nim`` iirc

**Comment by andreaferretti** [comment]
Thank you!

**Comment by andreaferretti** [comment]
I tried to have a look, but I get stuck [here](https://github.com/nim-lang/Nim/blob/devel/compiler/sigmatch.nim#L568) where `checkedBody` is assigned `nil` by the function `c.semTryExpr`. Until this point, everything seems ok.

Apparently `c.semTryExpr` is a [closure](https://github.com/nim-lang/Nim/blob/devel/compiler/semdata.nim#L85) member of `TContext`, so I cannot determine statically what it is.

I tried to `nimgrep` for `semTryExpr` and it is used only in three places. Two are the ones I linked above, while the third is [here](https://github.com/nim-lang/Nim/blob/devel/compiler/sem.nim#L403), where it is assigned `tryExpr`.

The definition of `tryExpr` is [here](https://github.com/nim-lang/Nim/blob/devel/compiler/sem.nim#L43), so it seems a dummy procedure.

Here, I am stuck. I don't know how `c.semTryExpr` can ever return anything different from `nil`. If so, it would seem that matching any type with any concept would always fail. But of course, we know that this is not the case.

Sorry I cannot be of any more help...

**Comment by andreaferretti** [comment]
Ok, I had a better look, and I think I sort of understand where the source of the error is. It was a bit complex to follow what's happening with all the dynamic calls, so I made a similar example , where the concept is correctly recognized, and then I printed the stacktrace from there to see the relevant functions.

A minimal example that shows the bug is 

```nim
type Monoid = concept x, y
  # x + y is type(x)
  type(z(type(x))) == type(x)

proc z(x: typedesc[int]): int = 0

discard 3 is Monoid
```

The operation that fails is [resolving this overload](https://github.com/nim-lang/Nim/blob/devel/compiler/semcall.nim#L349). I copy here the relevant procedure for reference:

```nim
proc semOverloadedCall(c: PContext, n, nOrig: PNode,
                       filter: TSymKinds): PNode =
  var errors: CandidateErrors

  var r = resolveOverloads(c, n, nOrig, filter, errors)
  if r.state == csMatch: result = semResolvedCall(c, n, r)
  elif experimentalMode(c) and canDeref(n):
    # try to deref the first argument and then try overloading resolution again:
    n.sons[1] = n.sons[1].tryDeref
    var r = resolveOverloads(c, n, nOrig, filter, errors)
    if r.state == csMatch: result = semResolvedCall(c, n, r)
    else:
      # get rid of the deref again for a better error message:
      n.sons[1] = n.sons[1].sons[0]
      notFoundError(c, n, errors)
  else:
    notFoundError(c, n, errors)
  # else: result = errorNode(c, n)
```

The error arises during the semantic pass on `z(type(x))`. The line ` var r = resolveOverloads(c, n, nOrig, filter, errors)` returns `nil`; this triggers an error which eventually lets the compiler conclude that `int` is not an instance of Monoid.

Apparently, the problem is that `type(x)` is itself not correctly typed. Namely, in the function above, with `n` equal to `z(type(x))`,

```nim
n.sons[1].typ
```

is `nil`, but

```nim
c.semTypeNode(c, n.sons[1], n.sons[1].typ)
```

is `int`. So, it seems that some more typing information is not determined before trying to resolve the overload.

Sorry I am not able to conclusively resolve the issue, but I hope this helps pinpointing where the issue arises

**Comment by andreaferretti** [comment]
Great, you made  my day! :-)
