### ISSUE TITLE
AsyncDispatch module questions( Poll() default timeout and blocking procs)

### ISSUE THREAD

**Issue by karantin2020** [nim-lang/Nim#3687]
Hello. What is the reason to set default timeout in proc poll to 500ms?
Please, test:

```nim
proc acceptAlways() {.async.} = 
    while true:
        echo "Foo"
        await sleepAsync(100)

proc sleepAlways()  {.async.} = 
    while true:
        await sleepAsync(1000)
        echo "do something"

asyncCheck acceptAlways()
asyncCheck sleepAlways()

while true:
  poll(1)
```

and this one:
```nim
proc acceptAlways() {.async.} = 
    while true:
        echo "Foo"
        await sleepAsync(100)

proc sleepAlways()  {.async.} = 
    while true:
        await sleepAsync(1000)
        echo "do something"

asyncCheck acceptAlways()
asyncCheck sleepAlways()

runForever()
```

And yet about non-blocking asynchronous code.
See:

```nim
proc readf(n: int) {.async.} =
  var file = openAsync("foobar.txt" & $n, fmReadWrite)
  file.setFilePos(0)
  var data = await file.readAll()
  echo data

proc job(t: int) {.async.} =
  asyncCheck readf(t)

proc serve() {.async.} =
  for j in 1..5:
    asyncCheck job(j)

asyncCheck serve()
while true:
  poll(1)
```

It is asynchronous code (I thought). 
But it executes as synchronous. Procs execute in order as they were started.
Always read file 1, then 2 ... and last file.
Is this the same with sockets read?
Why?

Thanks

**Comment by dom96** [comment]
> What is the reason to set default timeout in proc poll to 500ms?

CPU usage. On my machine your first example uses 3.2% CPU (which isn't much but it all adds up), whereas the second example uses 0%. Essentially you want to give the CPU as much time as possible to give other processes time to do work.

But it is unfortunate that the timers are only processed after the timeout completes. This is a bug (I think it's reported somewhere), the timers need to be a part of the ``select`` call (which ``poll`` makes). I hope this makes sense.

> It is asynchronous code (I thought).
> But it executes as synchronous. Procs execute in order as they were started.

yes, it is asynchronous. But reading such small files is likely almost instantenous so it all happens sequentially anyway. There is no waiting for data involved.

**Comment by karantin2020** [comment]
> But it is unfortunate that the timers are only processed after the timeout completes. This is a bug (I   think it's reported somewhere), the timers need to be a part of the select call (which poll makes).

Yes, my decision is not well. But default timeout in poll is not good too.
Are there intentions to decide that problem? I mean something like timers in nodejs for example.

What is the best solution of that problem now? What is the best way to get max resolution of timers and async procs? Can poll timeout be less than 1ms? Is there any way to execute async procs with frequency more than 1 execution per 1ms in 1 thread?

Thanks

**Comment by dom96** [comment]
My intention is to implement timers so that they are part of the call to epoll/select/kqueue (if possible).

Currently the best thing you can do is poll with a timeout of 1ms. What is your use case?

**Comment by karantin2020** [comment]
Thanks. I will wait that changes.
Is it possible to make bindings in Nim to nodejs libs? It has async wrapers, timers, async server with best security and performance. It is best optimized

Can you give some links to instructions how to make bindings in Nim to C and C++ libs? How to make nim compile c and c++ sources with nim code?

Thanks

**Comment by dom96** [comment]
You can compile Nim to JavaScript, so you could do it that way. But I am guessing that Node uses some C libs for its event loop, in fact I'm pretty sure it uses libev(ent). Somebody on the forums is working on integrating that already it seems: http://forum.nim-lang.org/t/1927

As for making bindings, this should help: http://nim-lang.org/docs/backends.html

**Comment by dom96** [comment]
Assuming this has been resolved. Closing. Feel free to ask any more questions.
