### ISSUE TITLE
nnkCommentStmt.strVal always nil via getImpl

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#3690]
strVal(nnkCommentStmt nodes) is always nil for a node coming from getImpl. The very same macro works when invoked as a pragma macro (e.g.: {.comments.}).  A simple test exhibiting the current behavior:

``` Nim
import macros

proc commentsRec(n: NimNode) =
  if n.len > 1:
    for kid in n: commentsRec(kid)
  else:
    if n.kind == nnkCommentStmt: # node there; .strVal/.comment always nil
      if n.strVal != nil: echo n.strVal

macro comments(n: untyped): typed =
  echo "Collecting comments"    # just to get a warm fuzzy macro is called
  commentsRec(n)

proc foo(a=1, b=2) {.comments.} =
  ## foo: should be echoed twice: once for pragma macro, once for getImpl
  echo "yadda"

discard comments(foo.symbol.getImpl)
```

My output, note the comment text only gets printed once:

```
Collecting comments
## foo: should be echoed twice: once for pragma macro, once for getImpl
Collecting comments
```

We should see the comment after both "Collecting comments" headers, but strVal on the getImpl output was nil in every variant I tried.

Two use cases (there may be others): 1) completely external doc/doc2 type work (instead of registering a separate compiler pass) or 2) use in my cligen package (maintain both an API and CLI in parallel with ease) to pull out a ## as command documention.  A 3rd movitvation would be that, conceptually, it would also seem (to me at least) somewhat confusing to propagate the nnkCommentStmt node via both macro invocations, but only ever give a non-nil value via one path.

**Comment by c-blake** [comment]
I looked into it just a little (I'm no expert on internals).  There would appear to be at least several places that should probably propagate ".comment".  For example, in compiler/ast.nim:
```
  proc copyNode(src: PNode): PNode
  proc shallowCopy(src: PNode): PNode
  proc copyTree(src: PNode): PNode
```
and maybe in compiler/vm.nim:
```
  proc copyValue(src: PNode): PNode
```
I tried putting in some .comment copies there, but that didn't seem sufficient, though.  So, there must be some other place the .comment is getting implicitly dropped.

**Comment by Araq** [comment]
Yeah, but we should use the strVal field for nkCommentStmt instead and adapt the docgen. That fixes these issue as a side effect as well as eliminating the special casing in the VM.

**Comment by c-blake** [comment]
I see your point.  I think you would probably also want to move nnkCommentStmt in the NimNodeKind to be contiguous with nnkStrLit..nnkTripleStrLit, perhaps right after nnkTripleStrLit.  No? Then all the appropriate "of" branches could be extended to include comment kinds as well (or left alone if the situation only makes sense for actual strings).  I guess if you're really sure all the dozens of spots make sense for both you could put the comment enum between StrLit and TripleStrLit and it would automatically get swept up.  Anyway, since comment text already works for pragma macros, I had been imagining/hoping that a less invasive fix might propagate it for getImpl.

**Comment by c-blake** [comment]
I think this is no longer an issue (or perhaps was always a bogus bug report due to a bug in my compiler build environment -- many apologies if so, and that has been resolved for good on my end).   In any event, that test code snippet which had been failing has been working correctly for a long time. So, I think it's good to close.

**Comment by Araq** [comment]
It was fixed months ago, afaict.
