### ISSUE TITLE
Exception in except block is very inconvenient to access

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#3691]
``` Nimrod
try:
  something()
except MyException:
  let e = cast[ref MyException](getCurrentException())
  # ...
```

There should be a nicer syntax for it, e.g.:

``` Nimrod
try:
  something()
except MyException as e:
  # ...
```

**Comment by dom96** [comment]
Can we please get this? I hate having to write ``(ref NimbleError)(getCurrentException())`` everywhere.

**Comment by dom96** [comment]
@Araq Maybe you could provide some hints on how this can be implemented?

**Comment by vegansk** [comment]
:+1:
