### ISSUE TITLE
Pre/post Increment/decrement operators

### ISSUE THREAD

**Issue by karantin2020** [nim-lang/Nim#3696]
Hello. Why nim lib does not have pre/post Increment/decrement operators ++ and --?
Sometimes it is good to use them

**Comment by def-** [comment]
It's very easy to write confusing code using them. I find it cleaner to separate the inc/dec operation from the other one instead. The code ends up a bit longer, but is easier to read and understand.

**Comment by reactormonk** [comment]
@karantin2020 could you give us some code where you would like to use `++`?

**Comment by karantin2020** [comment]
```nim
iterator items*(a: string): char {.inline.} =
  var i = 0
  while i < len(a):
    yield a[i++]
    # instead of using later inc(i)
    # it is because the last inc(i) in that loop is unnecessary. It will never exec

for ch in items("hello world"): # `ch` is an iteration variable
  echo(ch)
```

Another one:
```nim
proc items*(a: string, si: ptr int): char =
  var i = si
  var oldi = i[]
  inc(i[])
  return a[oldi] # i[]++ would return old value but increment pointer referenced value. 
                 # The same with objects
```
Increment/decrement operators exist in all languages and there is nothing confusing there.
That is my own point of view. Thanks

PS. Some languages delete many useful things. As example Golang does not have very much things that exist in other languages. And it makes golang very ugly.

I see that nim is pretty beautiful language. But I miss some things here too.
Especially I think that nim-lang needs very strong, fast, secure network libs with support of http2 and some network services.
Then nim-lang can be popular like golang and can receive more investments.
Sorry for my flood.

**Comment by Varriount** [comment]
To me, having syntax like that is both confusing and a case of premature optimization. Both inline and separate expression forms will likely result in similar instructions anyway (an add/inc or sub/dec instruction). Even if they do result in slightly different instructions, the performance difference will be negligable (It's only an addition/subtraction after all).

From a compiler standpoint, allowing multiple forms of inline increments/decrements presents complications when the compiler emits the resulting C, C++, or JavaScript code. Not only must relevant bounds checking code be emitted, but there are additional corner cases to handle regarding internals such as garbage collection and closure environment updating.

**Comment by Araq** [comment]
Post increment ++ and -- are a pain to support when you have user-definable operators and they don't add any clarity.
