### ISSUE TITLE
Internal compiler error when using expressions returning typedesc as types

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3697]
```
type 
 Foo = object
 FooBar = object

proc Bar(v: typedesc[Foo]): typedesc[FooBar] {.compileTime.} = return FooBar

let f: Foo.Bar = Foo.Bar()
```

It would be nice if code like this would work, but at least error message should be printed.

**Comment by narimiran** [comment]
> at least error message should be printed.

Currently (Nim 0.19.9) this error is printed:
`Error: expression 'Bar(Foo)' has no type (or is ambiguous)`

If you feel this should be further improved, please reopen the issue.
