### ISSUE TITLE
Better error messages for #1782

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3698]
``` nim
proc foo[T](a: string, b: T): string =
  a & b

var x = "asdf".foo[string]("asd")
```

Gives an error message:

```
foo.nim(4, 15) Error: type mismatch: got (string)
but expected one of: 
foo.foo(a: string, b: T)
```

This is a common gotcha so any sort of hints from the compiler would be helpful. Related to #1782

**Comment by data-man** [comment]
Now output:

> Error: type mismatch: got <string>
> but expected one of: 
> proc foo[T](a: string; b: T): string
> 
> expression: foo("asdf")

**Comment by andreaferretti** [comment]
@data-man do you have a collection of snippets for each issue (such as i_3698.nim) that you test automatically to figure out if something related to an issue changed? Just guessing based on the file name - it would be a very  handy thing to have

**Comment by data-man** [comment]
@andreaferretti 
No, I choose randomly. :)
But I also thought about the autotester.

**Comment by Araq** [comment]
I think this error message is good enough for now.
