### ISSUE TITLE
Expose stdout in JS if node

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#370]
NodeJs provides stdout, so we can expose it.

**Comment by pyhedgehog** [comment]
Not only stdout - support for system should be extended:
* stdin = process.stdin
* addQuitProc (= c atexit) = [`process.on('exit', cb)`](https://nodejs.org/api/process.html#process_event_exit)
* readFile = require('[fs](https://nodejs.org/api/fs.html)').[readFileSync](https://nodejs.org/api/fs.html#fs_fs_readfilesync_filename_options)
and so on (at least all sysio could be implemented)

**Comment by Yardanico** [comment]
Nim uses console.log on JS backend by default now; closing.
@pyhedgehog's feature request is not really related to this issue, open another one please.
