### ISSUE TITLE
request for comments: expand logging to be more syslog-y

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#3701]
Hi,

here's a smallish proposal to extend the builtin `logging` module enough so a 1:1 syslog mapping can be achieved.

Specifically, what would be necessary is:
* add the following levels: `notice`, `alert`, and `emerg`, and the accompanying templates.
* add a syslog backend, either native or just using ffi to import from syslog.h

Adding a syslog backend can be done now too, but the missing levels (especially `notice`) are really useful.  Where `info` is a informational message, it is something you can usually ignore; and `warn` is already a, well, warning condition.

`notice` fills the gap between those by providing a level for things you want to know about (canonical example: "new account registered on your forum!") and would like to hear about - maybe in a aggregated daily update.

`alert` and `emerg` are nice-to-have but not that important (they're more suited to global/system services and would not neccessarily need a dedicated template). See https://en.wikipedia.org/wiki/Syslog#Severity_level for a definition.

The obvious advantage of syslog compatibility is that you can just plug in a SyslogLogger into the chain, and have them in your local system logs, get log rotation for free, and so on. This is pretty much standard practice in on a unixy box. You can then aggregate them, analyse them (and send them on to remote syslog services too).

If there is interest in this, I'll prepare a PR!

**Comment by niv** [comment]
Here's a very naive, lacking implemention to showcase what i meant by adding a new syslog backend: https://gist.github.com/niv/150f43bce6b73dee108e

**Comment by Araq** [comment]
Yeah, I like the idea! Please go ahead.

**Comment by niv** [comment]
Addressed in https://github.com/nim-lang/Nim/pull/4131
