### ISSUE TITLE
tables module [] and get() fails with weird type infer problem when importing rethinkdb

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#3705]
So, I can't figure out why it does that - I don't know enough about how type inferring and so on works yet, or if it's the package that has a problem. Sorry about that. :)

The problematic part is adding `rethinkdb` to the package list. It's installed from nimble.

``` nim
import rethinkdb, tables

var t = initTable[string, int]()

t["test"] = 1
echo t["test"]
```

Results in:

```
test.nim(6, 7) template/generic instantiation from here
/Users/niv/.nimble/pkgs/rethinkdb-0.1.4/private/rql.nim(272, 15) template/generic instantiation from here
/Users/niv/.nimble/pkgs/rethinkdb-0.1.4/private/queries/document.nim(15, 11) template/generic instantiation from here
/Users/niv/.nimble/pkgs/rethinkdb-0.1.4/private/utils.nim(66, 24) template/generic instantiation from here
/Users/niv/.nimble/pkgs/rethinkdb-0.1.4/private/utils.nim(57, 14) Error: type mismatch: got (Table[system.string, system.int])
but expected one of: 
system.&(x: string, y: string)
system.&(x: seq[T], y: seq[T])
system.&(x: string, y: char)
system.&(x: char, y: char)
system.&(x: T, y: seq[T])
system.&(x: seq[T], y: T)
system.&(x: char, y: string)
datum.&(b: BinaryData)
datum.&(t: TimeInfo)
datum.&(a: seq[MutableDatum])
datum.&(n: float64)
datum.&(o: openarray[tuple[key: string, val: MutableDatum]])
datum.&(a: openarray[MutableDatum])
datum.&(b: bool)
datum.&(node: JsonNode)
datum.&(s: string)
datum.&(n: int64)
datum.&(o: TableRef[system.string, types.MutableDatum])
datum.&(r: RqlQuery)
datum.&(a: openarray[T])
rql.&(r: RqlRow, e: T)
```

**Comment by Araq** [comment]
My educated guess: rethinkdb's RqlRow is just an alias for Table and yet defines another accessor.

**Comment by niv** [comment]
Doesn't seem like it!

https://github.com/rgv151/rethinkdb.nim/blob/master/private/rql.nim#L16

Appears to be a distinct type that has no relation to Table at all (or I'm reading it wrongly).

It's amazing that stuff works at all really (at least to me, but then what do I know). The rethinkdb syntax specifies for the host language to support the complete query syntax, so you get these crazy method chaining setups that built up a simple AST that is then sent to the server.

Example:
```nim
  discard waitFor g_rethinkDB.table("players").
    filter((x: RqlQuery) => x["player_name"] == playerName).
    update(&*{
      "active": true,
      "last_seen": g_rethinkDB.now(),
      "last_seen_server_ip": serverIp,
      "last_seen_server_port": serverPort.int
    }).run(noreply = true)
```

**Comment by Araq** [comment]
This shows the same problem 

```nim


import tables

var t = initTable[string, int]()

proc `[]`*[T](r: T, s: string): auto =
  result = "r.row[s]"

t["test"] = 1
echo t["test"]
```

So ... overloading resolution (OR) in this case selected the wrong accessor. That's however according to the spec of how OR works. ``rethinkdb`` should really give its accessor more generic constraints, but the spec is also a bit weird for this case.

**Comment by niv** [comment]
Thanks for clearing that up!  FWIW, I think the redis lib might have the same issue. Redis exports a proc get() and that appears to mingle with Table.get() too, resulting in the same compiler error.

**Comment by Araq** [comment]
Changing the OR rules again would break too much code. Closing.
