### ISSUE TITLE
compiler including standard library when it shouldn't

### ISSUE THREAD

**Issue by samanthadoran** [nim-lang/Nim#3708]
The compiler is trying to include <string.h> for memset in one of my modules even though I have told it not to use standard libs with: https://github.com/samanthadoran/Mero/blob/master/source/kernel.nim.cfg

The line causing the issues
```Nimrod
var handler = irq_routines[irqIndex]
```
and irq_routines is defined as
```Nimrod
var irq_routines: array[0..15, proc(regs: registers)]
```

The compiler is trying to use memset from it to 0 it before use
```C
memset((void*)(&handler), 0, sizeof(handler));
```

I'm using Nim Compiler Version 0.12.0 (2015-10-30), but I haven't tried against source yet.
Edit: Same issue with Nim Compiler Version 0.12.1 (2016-01-12)

**Comment by Araq** [comment]
What should the compiler do though? Provide its own 'memset'?

**Comment by Araq** [comment]
No feedback. Closing.
