### ISSUE TITLE
deadCodeElim always keeps one function: getRefcount

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3713]
Nim doesn't eliminate unused getRefcount function in generated c source for unknown reason:

```
$ grep -rn --include=*.c getRefcount
compiler/nimcache/stdlib_system.c:607:N_NIMCALL(NI, getRefcount)(void* p);
compiler/nimcache/stdlib_system.c:3237:N_NIMCALL(NI, getRefcount)(void* p) {
$ nim -v
Nim Compiler Version 0.12.0 (2015-10-27) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: b186493f0143fa8d977b4815e2ecda9f16a43b63
active boot switches: -d:release
```

**Comment by Varriount** [comment]
Isn't that used for the garbage collector?

**Comment by scriptum** [comment]
It is **not** used in garbage collector but:
>Whole program dead code elimination: Only used functions are included in the executable.
This function is unused and it's weird that Nim didn't eliminate it.

**Comment by Araq** [comment]
It's because .exportc'ed procs are not eliminated. stdlib bug, not a compiler bug.

**Comment by Araq** [comment]
Only a problem for the some GCs and not for our newer stuff, so closing now.
