### ISSUE TITLE
Implicit generic instantiation doesn't work with nested union types

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3717]
``` nimrod
type
  Foo[T] = object
    a: T

  Foo1[T] = Foo[T] | int

proc foo*[T](s: Foo1[Foo[T]]): T =
  5

var f: Foo[Foo[int]]
discard foo(f)
```

failes with `cannot instantiate: 'T'`. Similar errors can also be observed with types like `proc(): Foo1[T]` or concepts.

**Comment by narimiran** [comment]
This works in Nim 0.19.

I've added a test case in #9347, closing this.
