### ISSUE TITLE
Segfault in popFrame with TCC

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#3719]
Only crashes with the TCC compiler, only tested on x86-64 Linux:

``` nim
proc isAlpha(c: char): bool = c in 'a'..'z'

proc encrypt(msg: string) =
  if isAlpha msg[0]:
    return

encrypt("X")
```

The error doesn't really lead me any further:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004014ff in popFrame ()
(gdb) bt
#-1 0x00000000004014ff in popFrame ()
Backtrace stopped: Cannot access memory at address 0x100024
(gdb) 
```

This happens in older Nim versions as well. I guess I never caught it because it doesn't happen reliably. Might also just be a TCC problem. Not sure if anyone even uses TCC other than me.

**Comment by Araq** [comment]
Does it use thread local storage or --threads:on?

**Comment by def-** [comment]
No, pthreads doesn't even work with TCC.

**Comment by def-** [comment]
Seems fixed.
