### ISSUE TITLE
Iterator type aliases don't work after merge of new-ll

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3721]
```
type Foo[T] = (iterator(): T)

let f: Foo[int] = (iterator(): int = yield 5)
```
This worked before (86bb9d8b), but now (02a078238) produces error message:
`foo.nim(3, 20) Error: type mismatch: got (iterator (): int{.inline, gcsafe, locks: 0.}) but expected 'Foo[system.int]'`

**Comment by Araq** [comment]
Well you need to annotate the iterator with .closure. I think the compiler is just more picky than it used to be.

**Comment by oderwat** [comment]
```

**Comment by oderwat** [comment]
```
type Foo[T] = (iterator() : T)

let f: Foo[int] = (iterator(): int {.closure.} = yield 5)

echo f()
```

works. But emits a warning about the iterator not being used.

**Comment by Araq** [comment]
Works again.
