### ISSUE TITLE
VM SIGSEV with compile-time Table

### ISSUE THREAD

**Issue by dustinlacewell** [nim-lang/Nim#3729]
The attached code suffers from a proneness to SIGSEV when accessing the compile-time Table `registry`. It seems that sometimes accessing the `registry` Table and its data will result in a SIGSEV even though code that is executed earlier that accesses the same Table does not cause SIGSEV.

It would appear that in the circumstances in which a line causes a SIGSEV to occur that the line is being executed before other lines in the same block. (echo statements appear in stdout in the wrong order). In fact it would appear that these lines, in the circumstances in which they cause SIGSEV, are being optimized before *most* lines in the module are executed. As in, executed before the "module-level" declaration and initialization of the module-level `registry` Table.

The attached code is two files conjoined:
  * meta.nim - contains some helper wrappers around AST construction
  * magic.nim - contains some macros and helper functions for pooling partial type definitions (`component`) and then unifying partial types under a new concrete type (`bind_components`).

The current line causing a SIGSEV is marked with an `echo` statement. Notice that this line, which is SIGSEV'ing on access to the `registry` Table occurs after other accesses to the same table. Usually when this happens, simply rewriting the line or few lines a different way will convince the compiler to be happy and not SIGSEV.

[sigsev.txt](https://github.com/nim-lang/Nim/files/93604/sigsev.txt)

**Comment by jangko** [comment]
@dustinlacewell: Please, next time try to reduce your code sample. shorter is better

this is the shorter code to reproduce the bug:

```nimrod
import tables, macros

type
  Registry = Table[string, int]

var registry {.compileTime.} = initTable[string, int]()
  
macro bind_components*(): stmt {.immediate.} =  
  registry.add("test", 1)
  for component in registry.mvalues():
    discard component

bind_components()
```

**Comment by Araq** [comment]
@jangko Not fair, I told @dustinlacewell it's fine. ;-) Better than no bug report. Besides I dislike this overfitting of the compiler to tiny snippets. "Test works, fails in a bigger context" is a problem too.

**Comment by jangko** [comment]
@araq: perhaps i should say, please provide both short and long code, we need both of them. :smile: 
sorry @dustinlacewell
