### ISSUE TITLE
nimprof breaks under v0.13.0 without -d:profiler, but warning message could be clearer

### ISSUE THREAD

**Issue by boydgreenfield** [nim-lang/Nim#3741]
A simple script like:

```nimrod
import nimprof

when isMainModule:
  echo "Fails :("
```

fails to compile with:

```
Hint: system [Processing]
Hint: test [Processing]
Hint: nimprof [Processing]
lib/pure/nimprof.nim(15, 12) Warning: Profiling support is turned off! [User]
Hint: hashes [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: etcpriv [Processing]
Hint: algorithm [Processing]
Hint: tables [Processing]
Hint: math [Processing]
Hint: times [Processing]
Hint: sets [Processing]
Hint: os [Processing]
Hint: posix [Processing]
lib/pure/nimprof.nim(165, 10) Error: undeclared identifier: 'profilingRequestedHook'
```

Three issues with this:

1. One has to remove or comment out the `import nimprof` line to turn the debugger on/off. This is somewhat cumbersome vs. toggling the flag _and_ just allowing a warning to pop up;

2. For larger files that warning can get somewhat buried in the output (not easy to resolve); and 

3. The warning doesn't tell the user how to turn on profiler support (easily solved).

Will submit a PR for (3) as I just got stuck on this for a few minutes and am sure others will bump into it too. Probably worth discussing (1) as well.

**Comment by boydgreenfield** [comment]
Ignore that first PR... Github UI issue caused me to open it against my fork's `devel` branch. #3742 improves the warning (2 above).

**Comment by Araq** [comment]
Solution for 1:

```nim

when not defined(profiler) and not defined(memProfiler):
  import nimprof
```

**Comment by boydgreenfield** [comment]
@Araq – I'm fine w/ both of your proposed changes (they're just somewhat more substantial design changes which is why I wasn't sure if they'd already been discussed/dismissed for another reason).

Would you like me to update the PR to (1) auto-import nimprof as in your block above; and (2) error instead of issuing a warning?

**Comment by Araq** [comment]
Only (2) my solution for (1) is only possible for users of nimprof. Auto-injection of modules has to be done differently in the compiler. Well I guess we simply could add it to system, but meh...

**Comment by boydgreenfield** [comment]
Will do.

**Comment by Araq** [comment]
Now produces a nice error message.
