### ISSUE TITLE
Confusing error message (methods can't have same names as fields if UFCS is used)

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3748]
```
type
  Argument*[T] = ref object
    defaultValue: T

proc defaultValue(arg: Argument[bool], v: bool): Argument[bool] =
  discard

proc addArgument*(arg: int): Argument[bool] =
  let v = Argument[bool]()
  return v.defaultValue(false)

when isMainModule:
  let quix = addArgument(5)
```

produces

```
foo.nim(12, 11) Error: identifier expected, but found 'v.defaultValue'
```

It took me 20 minutes to figure out what's wrong (in a larger program)

**Comment by Varriount** [comment]
I guess the proper message would indicate that the syntax is ambiguous?

**Comment by Araq** [comment]
It's not ambiguous, field access is interpreted as field access if it can be.

**Comment by narimiran** [comment]
> It's not ambiguous, field access is interpreted as field access if it can be.

[From the manual](https://nim-lang.github.io/Nim/manual.html#special-operators-operator-dot):
" `.()` has higher precedence than the `.` operator and this allows one to handle expressions like `x.y` and `x.y()` "
