### ISSUE TITLE
FigureArray = array[-1..1, cstring]

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#3749]
type
      #FigureArray = array[-1..1, string] # compiles fine
      FigureArray = array[-1..1, cstring] # these strings are only for pango, so I choosed cstring. Of course string can be used.

    const

      Figures: FigureArray = ["pp", "xx", "yy"]

#Nim Compiler Version 0.13.0 (2016-01-20) [Linux: amd64]

#bug.nim(7, 26) Error: type mismatch: got (Array constructor[0..2, string]) but expected 'FigureArray'

**Comment by reactormonk** [comment]
You'll have to explicity convert to `cstring`.

    type FigureArray = array[-1..1, cstring]

    const Figures: FigureArray = [cstring("pp"), cstring("xx"), cstring("yy")]
