### ISSUE TITLE
Add compiler parameter to generate output from source code filters

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#375]
The source code filters can be sometimes difficult to debug because the code the user is writing is not the same which later gets compiled, so the user gets error messages on lines/columns which are not visible to him. The switch ``--verbosity:3`` can be used but it has really ugly output mixed with compiler hints. It would be nice if the compiler could grow an option to *translate* rather than compile a file, which would take input ``.tmpl`` files and generate their respective ``.nim`` version.

**Comment by Araq** [comment]
This could always be achieved with ``--hint[codeBegin]:on``.

**Comment by Varriount** [comment]
Which doesn't appear to be documented.
