### ISSUE TITLE
deprecated warning with greetings.nim in Solaris 10.

### ISSUE THREAD

**Issue by JoePython1** [nim-lang/Nim#3757]
cat greetings.nim
    # This is a comment
echo("What's your name? ")
var name: string = readLine(stdin)
echo("Hi, ", name, "!")

$nim compile greetings.nim
Hint: system [Processing]
lib/system/gc_common.nim(134, 18) Warning: use ByteAddress instead; TAddress is deprecated [Deprecated]
lib/system/gc_common.nim(135, 18) Warning: use ByteAddress instead; TAddress is deprecated [Deprecated]
lib/system/gc_common.nim(136, 18) Warning: use ByteAddress instead; TAddress is deprecated [Deprecated]
lib/system/gc_common.nim(153, 32) Warning: use ByteAddress instead; TAddress is deprecated [Deprecated]
lib/system/gc.nim(820, 19) template/generic instantiation from here
lib/system/gc_common.nim(153, 32) Warning: use ByteAddress instead; TAddress is deprecated [Deprecated]
Hint: greet [Processing]
CC: greet
CC: stdlib_system
Hint:  [Link]
Hint: operation successful (9902 lines compiled; 1.378 sec total; 8.870MB; Debug Build) [SuccessX]

**Comment by JoePython1** [comment]
This is for nim downloaded from http://nim-lang.org/download/nim-0.13.0.tar.xz

**Comment by def-** [comment]
This should be fixed by https://github.com/nim-lang/Nim/commit/4e0f8cf595338ac2bd87eca5e3c2cbaacada5736
