### ISSUE TITLE
TThread is deprecated

### ISSUE THREAD

**Issue by JoePython1** [nim-lang/Nim#3764]
If TThread is deprecated why is it still lurking around in the nim code?

    lib/pure/concurrency/threadpool.nim(331, 37) Warning: use Thread instead; TThread is deprecated [Deprecated]

**Comment by JoePython1** [comment]
Also get the following deprecated when compiling example provided in documentation:


lib/pure/concurrency/threadpool.nim(334, 48) Warning: use Thread instead; TThread is deprecated [Deprecated]
lib/pure/concurrency/threadpool.nim(471, 22) Warning: use Lock instead; TLock is deprecated [Deprecated]

**Comment by def-** [comment]
Would be fixed by https://github.com/nim-lang/Nim/pull/3106
