### ISSUE TITLE
parseBiggestInt does not raise OverflowError

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#3771]
`strutils.parseInt` has `raises: [OverflowError , ValueError]`, but `strutils.parseBiggestInt` has `raises: [ValueError]`. It seems like `OverflowError` is missing - the integer in the string may obviously still be too large to fit in a `BiggestInt`.

**Comment by GULPF** [comment]
This has been fixed (it still says `raises: [ValueError]` but it's now correct, `ValueError` is used for overflows as well).
