### ISSUE TITLE
re module needs to override deepCopy for thread safety

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3773]
When an error occurs the `find` procedure in the `re` module returns other values that are less than 0, shouldn't this raise an exception?

As an aside, passing `Regex` to a spawned procedure does not work very well.

**Comment by Araq** [comment]
> As an aside, passing Regex to a spawned procedure does not work very well.

What does that mean? I guess Regex needs to override `=deepCopy`.

**Comment by dom96** [comment]
It causes ``find`` to return ``-4`` for example. Also this:

```
concurrency_regex(49609,0x700000402000) malloc: *** error for object 0x7f8c43c036d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last)
threadpool.nim(312)      slave
concurrency_regex.nim(49) parseWrapper
strutils.nim(456)        parse
gc.nim(465)              newObjNoInit
gc.nim(439)              rawNewObj
gc.nim(951)              collectCT
gc.nim(907)              collectCTBody
gc.nim(862)              collectZCT
gc.nim(194)              prepareDealloc
re.nim(77)               finalizeRegEx
SIGABRT: Abnormal termination.
```

**Comment by Araq** [comment]
Yeah, it really should override =deepCopy.

**Comment by dom96** [comment]
Shouldn't this be caught at compile-time?

**Comment by Araq** [comment]
ORC allows to move refs between threads.
