### ISSUE TITLE
Operators in if statements ==

### ISSUE THREAD

**Issue by deavmi** [nim-lang/Nim#3782]
Been learning nim and:

```nim
if 2 == 1:
  echo("Yay")
elif 1 ==1:
  echo("kak")
else:
  echo("Boo!")
````

When I hae the `==1` next to the `1` with no space it says `expected ':'` as error. This should be fixed.

**Comment by def-** [comment]
This is probably intentional, see the syntax changes in http://nim-lang.org/news.html#Z2016-01-18-version-0-13-0-released

**Comment by deavmi** [comment]
Why you would make that a syntax requirement I don't know, however maybe the dev wants you to make sexy and clean Nim code, which I agree with. But for testing stuff out quickly it's annoying. Infact I think it should allow this.

**Comment by kirbyfan64** [comment]
Because it's more consistent.

Should `a -1` be parsed as `(a) - (1)` or `a(-1)`? The latter makes more sense. Extending that to other operators has some tradeoffs, like this issue, but overall it's less surprising.

**Comment by deavmi** [comment]
a-1 and a(-1) are the same tho.

**Comment by kirbyfan64** [comment]
No it doesn't. `a(-1)` is calling a function `a` with `-1` as an argument.

**Comment by deavmi** [comment]
Oh ssorry. I shouldn't think in maths right now. Which is ambiguous as well in this respect.
