### ISSUE TITLE
Indentation madness

### ISSUE THREAD

**Issue by deavmi** [nim-lang/Nim#3783]
Is there a point in not allowing a user to have a space say now before a variable or object declaration.

**Comment by kirbyfan64** [comment]
Can you give an example?

**Comment by deavmi** [comment]
Well I got a compilation error upon doing `var d = 2` with a before the `var`

**Comment by reactormonk** [comment]
Nim syntax is indentation-based. The spaces matter, so nim will complain about them.

**Comment by deavmi** [comment]
> _"Seems fussy to me."_ My opinion.
