### ISSUE TITLE
echo fails on objects with private fields

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#3792]
```nim
# lib.nim
type Hello* = object
  private: string
  public*: string
```

```nim
import lib

let my = Hello()
echo hello
```

Expected behaviour: Only print "public" in output

Actual behaviour: undeclared field: 'private'

I'd suggest to just skip private fields instead of erroring; that would be much more convenient than having to write custom $ procs for objects.

**Comment by Araq** [comment]
Has been implemented.
