### ISSUE TITLE
rst parser doesn't like some image urls

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3796]
``` rst
.. image:: http://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-github.png
```

does not work for example

**Comment by juancarlospaco** [comment]
**This Bug does not Reproduce anymore.**

Done this several times, if the URL works it works, Screenshot attached.

![temp](https://user-images.githubusercontent.com/1189414/46588607-b4512000-ca75-11e8-844d-1be4b98399c2.png)

:cat:
