### ISSUE TITLE
Better support for modifying XmlNodes

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3797]
At least the following procedures would be useful for my use case:
- `clear` - to clear all children of an xmlnode

Ability to set/get all the children of an xmlnode would be nice too

**Comment by narimiran** [comment]
> `clear` - to clear all children of an xmlnode

```nim
proc clear(n: var XmlNode) =
  for i in 0 ..< n.len:
    n.delete(i)
```
Is this enough? :)

**Comment by Araq** [comment]
No, that's not recursive.

**Comment by narimiran** [comment]
> No, that's not recursive.

Alright, #10711 is recursive.
