### ISSUE TITLE
Getting started section in Wiki needs update

### ISSUE THREAD

**Issue by sheerun** [nim-lang/Nim#3798]
Hey,

I'm not sure but I think "Getting Started" section in Wiki might be out of date. For example there's no csources.zip

Could someone competent update it? :)

**Comment by genotrance** [comment]
Removed the Getting Started page link altogether - everything was already covered in the Home wiki page under the Getting Started section.

This can be marked as closed if the fix is agreeable.

**Comment by dom96** [comment]
Seems good to me.
