### ISSUE TITLE
Generics and implicit typeclasses - cannot instantiate

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3800]
I think that the following code should compile, but it doesn't:
```
type
  A[T] = object
  B[T] = A
  C = B[int]
```
fails with:
```
test1.nim(5, 8) Error: cannot instantiate: 'B'
```

**Comment by Araq** [comment]
I think it shouldn't compile. ;-)

**Comment by def-** [comment]
I agree, I think what you wanted is this:

```nimrod
type
  A[T] = object
  B[T] = A[T]
  C = B[int]
```

**Comment by zielmicha** [comment]
Why not? `A` is a typeclass, so `B[T] = A` should create a typeclass alias (ignoring `T` parameter). This, for example, works:
```
type A[T] = object
type B = A

proc foo(b: B) = discard

var b: A[int]
foo(b)
```
