### ISSUE TITLE
sequtils, use open array for arguments when possible

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#3801]
http://nim-lang.org/docs/sequtils.html#filter,seq[T],proc(T)
# proc filter[T](seq1: seq[T]; pred: proc %28item: T%29: bool {.closure.}): seq[T] {.inline.}

proc filter[T](seq1: openArray[T]; pred: proc %28item: T%29: bool {.closure.}): seq[T] {.inline.}

That may be useful for filtering arrays. I asked Araq in IRC, he said it should be OK, and I did a small test myself. But maybe there is a drawback?

**Comment by genotrance** [comment]
This issue is fixed per referenced PR.
