### ISSUE TITLE
could not load: pcre.dll while excute aporia.exe in Nim-0.13.0_x64/dist/aporia-0.3.0/bin

### ISSUE THREAD

**Issue by softwaredownload** [nim-lang/Nim#3806]
could not load: pcre.dll while excute aporia.exe in Nim-0.13.0_x64/dist/aporia-0.3.0/bin

## How to reproduce the issue:

- Download http://nim-lang.org/download/nim-0.13.0_x64.exe
- Execute it and choose all Components which includes aporia-0.3.0
- Execute Nim/dist/aporia-0.3.0/aporia.exe using mingw bash, got error:
		could not load: pcre.dll

(Execute aporia.exe using Windows Command Prompt did not show the error message, it's just nothing)

## How to fix it:

Copy Nim/bin/pcre3.dll into Nim/dist/aporia-0.3.0.0/bin directory to replace the default pcre.dll

Tested on Windows 10 64 bit.

I hope someone can upload a new nim-0.13.0_x64.exe with this fix.

**Comment by Araq** [comment]
That depends on your setup / PATH. I cannot reproduce this, it works on my Win 10, 64 bit.

**Comment by softwaredownload** [comment]
My PATH is:

`C:\Nim\dist\mingw\bin;C:\Nim\bin;C:\Nim\dist\aporia-0.3.0\bin`

I tested http://nim-lang.org/download/nim-0.14.0_x64.exe today, exactly the same issue.

**Comment by Araq** [comment]
Latest Aporia packaging fixed that problem. 0.14.2 ships with Aporia 0.4.0.
