### ISSUE TITLE
nim check command emits error when using `set`, and `array` type

### ISSUE THREAD

**Issue by yuutayamada** [nim-lang/Nim#3807]
I got `ambiguous identifier: 'set' -- use a qualifier` error message
when I did `nim check` (actually editor plagin uses the check command)
IIUC `set` is system type, so should not occur this error message?
(I updated nim today and checked at `fe95125`)

set.nim:
```nim
var collection: set[int16]
assert collection == {}
```

checked with `nim check`

```sh
$ nim check set.nim 
Hint: system [Processing]
Hint: set [Processing]
set.nim(1, 17) Error: ambiguous identifier: 'set' -- use a qualifier
```

**Comment by yuutayamada** [comment]
I found similar `nim check` command error when I used array type

```nim
var a: array[0..2, int] = [1, 2, 3]
for n in a:
  echo n
```

```sh
$ nim check array.nim 
Hint: system [Processing]
Hint: array [Processing]
array.nim(1, 8) Error: ambiguous identifier: 'array' -- use a qualifier
```

**Comment by Araq** [comment]
Learn Nim's module system.

**Comment by kirbyfan64** [comment]
Basically, since you're creating a file named `set.nim`, the compiler isn't sure whether you're referring to the module or the `set` type. Same with `array`. Try renaming the file to something else.

**Comment by yuutayamada** [comment]
Thank you both. For me, the error message was mysterious.
(but after @kirbyfan64's comment, it make sense for me)
