### ISSUE TITLE
Random segfault in GC

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#3808]
While stress testing a small custom gui app (quickly switching between pages)
the program randomly crashes in 'canBeCycleRoot' after a few seconds.
It happens in debug mode as well as release (although without traceback)
Same result when updating to latest devel.

release flags:
nim -r c  --verbosity:0 --hints:off --warning[LockLevel]:off --warning[Deprecated]:off --parallelBuild:2 --opt:size --passC:-flto --passL:-flto --cc:gcc -d:release test_gui.nim

debug flags:
nim -r c  --verbosity:0 --hints:off --warning[LockLevel]:off --warning[Deprecated]:off --parallelBuild:2 --cc:tcc test_gui.nim

Nim Compiler Version 0.13.1 (2016-02-01) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: ac1e7a245093bb28a1a366f1e169ab50e6660c94
active boot switches: -d:release

``` 
Traceback (most recent call last)
test_gui.nim(224)        test_gui
base_window.nim(87)      run
base_window.nim(93)      run
base_window.nim(83)      render
test_gui.nim(185)        render
manager.nim(70)          render_unbuffered
manager.nim(51)          update_gui
widget.nim(456)          on_update
macros.nim(329)          on_update
dialog.nim(854)          Dialog_on_update_untyped
dialog.nim(467)          do_layout
widget.nim(271)          size
dialog.nim(898)          size
widget.nim(271)          size
layout.nim(220)          size
widget.nim(271)          size
frame.nim(273)           size
frame.nim(153)           size
widget.nim(271)          size
scrollable.nim(315)      size
frame.nim(153)           size
widget.nim(271)          size
layout.nim(220)          size
widget.nim(271)          size
slider.nim(236)          size
slider.nim(213)          get_graphic
theme.nim(106)           get
system.nim(2152)         &
gc.nim(486)              newObjRC1
gc.nim(951)              collectCT
gc.nim(907)              collectCTBody
gc.nim(863)              collectZCT
gc.nim(369)              forAllChildren
gc.nim(736)              nimGCvisit
gc.nim(705)              doOperation
gc.nim(221)              decRef
system.nim(1104)         canBeCycleRoot
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

here is another variant of the same error.
```
Traceback (most recent call last)
...skipped for brevity
batch.nim(96)            add_group
tables.nim(327)          []=
tableimpl.nim(87)        []=
tableimpl.nim(58)        rawInsert
gc.nim(258)              asgnRef
gc.nim(221)              decRef
system.nim(1104)         canBeCycleRoot
```

**Comment by reactormonk** [comment]
I think you forgot the code for `test_gui.nim`.

**Comment by Parashurama** [comment]
The project itself is pretty large. As I said, the library 'test_gui.nim' depends on is a custom GUI based on SDL2. (opengl)
From the error message it seems that the GC is trying to act on a nil reference, which i guess shouldn't be happening.
The project is not yet open-sourced, but it should be in the future.
Unless I'm missing something, the issue is not in my code (I hope), but somewhere in the system libs.

**Comment by Araq** [comment]
Note that a better GC is in the works and hopefully ready soon enough.

**Comment by Parashurama** [comment]
Ah, okay. 
While testing my app, I remark that the markAndSweep GC  is not  as effective at freeing memory as the default gc. It's not really important, but I'm curious.

On another subject:
What is the best way for diagnosis of memory leaks in a large app in nim.
I'm used to python, checking with weak ref which objects are still alive when they shouldn't be and C, with valgrind.
Any suggestions?

**Comment by Araq** [comment]
Compile with ``-d:useSysAssert -d:useGcAssert`` and see what it reports.

**Comment by Parashurama** [comment]
Using latest devel.
Nim Compiler Version 0.13.1 (2016-03-28) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: 8c8825b9ce1ec04a812142d85ec1369c4c0d2ca7
active boot switches: -d:release


So I got back to this problem and using your compile flags -d:useSysAssert -d:useGcAssert (in debug mode) I wasn't able to reliably produce an error, except once for some reason (see at bottom of this post).

Not using the flags however, produce the previous crash within seconds.
It might have to do with the fact that the additional asserts made the code unbearably slow while stressing the GC with many alloc/dealloc.

```
[GCASSERT] decRef: waZctDecRef
Traceback (most recent call last)
test_gui.nim(284)        test_gui
base_window.nim(122)     run
base_window.nim(128)     run
base_window.nim(107)     handle_events
sdl2_window.nim(56)      handle_events
base_window.nim(90)      dispatch_event
widget.nim(441)          dispatch_event
widget.nim(444)          dispatch_event
cevents.nim(220)         dispatch_event_internal
dialog.nim(694)          Dialog_on_mouse_motion_untyped
dialog.nim(124)          set_hover
system.nim(198)          set_hover
gc.nim(480)              newObj
```

**Comment by Parashurama** [comment]
Trying different things, I managed to make the script crash in different ways.
I hope it can be useful.
```
[GCASSERT] decRef: waZctDecRef
Traceback (most recent call last)
test_gui.nim(284)        test_gui
...skipped for brevity
dialog.nim(124)          set_hover
system.nim(198)          set_hover
gc.nim(480)              newObj

[GCASSERT] decRef: waZctDecRef
Traceback (most recent call last)
test_gui.nim(287)        test_gui
...skipped for brevity
macros.nim(325)          newWidget
system.nim(194)          new
gc.nim(480)              newObj

[GCASSERT] incRef: interiorPtr
Traceback (most recent call last)
test_gui.nim(287)        test_gui
...skipped for brevity
glyphs.nim(343)          initUnformattedDocument
gc.nim(263)              asgnRef
gc.nim(123)              incRef

[GCASSERT] decRef: interiorPtr
Traceback (most recent call last)
test_gui.nim(287)        test_gui
...skipped for brevity
batch.nim(96)            add_group
tables.nim(327)          []=
tableimpl.nim(87)        []=
tableimpl.nim(58)        rawInsert
gc.nim(264)              asgnRef
gc.nim(123)              decRef

[GCASSERT] waMarkGray
Traceback (most recent call last)
test_gui.nim(287)        test_gui
...skipped for brevity
domain.nim(138)          newVertexList
gc.nim(480)              newObj
```

**Comment by Araq** [comment]
Please try ``--gc:markAndSweep``, ``--gc:v2`` and see if it makes a difference. Unless you can submit a test program (even if large) there is little else we can do to help you.

**Comment by Parashurama** [comment]
I have been using  *--gc:markAndSweep* since I first reported the bug and it has never crashed since then.

I am currently trying to a make smaller test file reproducing the issue but i am not sure i will succeed.
Simply stressing the GC with many alloc/dealloc doesn't seem to do the trick. It may be some out-of-bounds access in C-like code.
I actually have very little **unsafe** code in the library but i will check anyway.

I tried  *--gc:v2* and  it doesn't seem to crash as often, which is not really helpful.
here is another message crash with the flags --gc:v2 -d:useSysAssert -d:useGcAssert
```
collectCycles: introduced bug E 1
freeing  0x7f49959b3f10 28 rc=3 color=w
[GCASSERT] wtf man, freeing obviously alive stuff?!!
Traceback (most recent call last)
test_gui.nim(288)        test_gui
base_window.nim(122)     run
base_window.nim(130)     run
base_window.nim(117)     render
test_gui.nim(235)        render
manager.nim(86)          render_unbuffered
manager.nim(55)          update_gui
clock.nim(143)           tick
clock.nim(111)           call_scheduled_functions
file_dialog.nim(397)     debug_memleak
macros.nim(326)          newFolderSelectDialog
file_dialog.nim(455)     initFolderSelectDialog
file_dialog.nim(132)     initFileLoadDialog
file_dialog.nim(52)      set_files
file_dialog.nim(259)     set_files
tableimpl.nim(84)        []=
tables.nim(193)          enlarge
tableimpl.nim(59)        rawInsert
gc2.nim(488)             newObjRC1
gc2.nim(943)             collectCT
gc2.nim(912)             collectCTBody
gc2.nim(823)             collectCycles
gc2.nim(687)             sweep
gc2.nim(136)             freeCyclicCell
```

**Comment by cdunn2001** [comment]
If this really is a bug in Nim (not yet certain) it's very important to track this down in your test-case. Is this a multi-threaded program? Maybe refs from different threads are in the table. What if you force the garbage-collector to run very early in your program, or very often?

**Comment by Parashurama** [comment]
It is a single threaded program gui-test program depending only on SDL2 and modern OpenGL 3+.
As a GUI library there **many** cyclic reference between parent/child/root and reference to other widgets.
There are also a few unsafe C-like functions, but skipping them has no effects.
The crashes can sometimes be triggered by calling GC_fullCollect not always.
The code itself its ~1MB of source code and not ready to be open-sourced.

I haven't yet managed to reproduce the crashes in a smaller test-program.

**Comment by Parashurama** [comment]
So I may have tentatively solved the problem. As suggested by Araq in issue https://github.com/nim-lang/Nim/issues/4053, shallowCopy can be unsafe when used with const variable.

I removed  instances of shallowCopy in a couple of places and it seems to have done the trick. (with both default **gc** and **v2**)
