### ISSUE TITLE
json: slow as hell

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3809]
I have a very BIG issue with loading ~2 MB json data. It looks like parsing time grows exponentially while increasing data size.
Here is python sample:
```python
import json
d = {}
for i in range(1, 200000):
  d[str(i)] = i
json.loads(json.dumps(d)) # 0.55 sec
```
<a href="#" title="275 sec, 500 times slower than Python!">Now guess Nim's time</a>:
```nim
import json
let jobj = newJObject()
for i in 1..<200000:
  jobj.add($i, newJInt(i))
let jobj_parsed = parseJSon($jobj)
```

**Comment by kirbyfan64** [comment]
"Now guess Nim's time" leads back to this page. Does it take 3809 seconds or something?

**Comment by scriptum** [comment]
This is a hover-spoiler :smile:

**Comment by Araq** [comment]
Give us the test-json somehow.

**Comment by def-** [comment]
@Araq It's created bye the test program.

**Comment by scriptum** [comment]
@Araq this is simplified test that exactly reproduces my case. I have a many key-value pairs in json format, approximately 2 Megabytes.

**Comment by kirbyfan64** [comment]
I had to download another web browser just to see it (on Android ATM).

**Comment by scriptum** [comment]
@kirbyfan64 I'm sorry this was simplest way to create spoiler on GitHub

**Comment by def-** [comment]
The problem is that a JObject's fields are a seq of key, val pairs. When you want to insert a new key it is checked for equivalence to each existing key. I'll try to use a HashSet instead.

**Comment by scriptum** [comment]
@kirbyfan64 0.2 - sounds good!

**Comment by def-** [comment]
@scriptum Take a look at https://github.com/nim-lang/Nim/pull/3810 please, faster than python for me.
