### ISSUE TITLE
IPv6 support for httpclient

### ISSUE THREAD

**Issue by cyisfor** [nim-lang/Nim#3811]
So, I wanted to get a file from a website over IPv6. Oops, I guess I can't! Back to python for me!

This needs to be remedied.

The ultimate solution would be writing a totally new httpclient library using asyncnet I think, as asynchttpserver to httpserver. It doesn't look like much less effort to start over again, than it would be to fix httpclient, since the "net" module already messed up, by beginning with sockets, not with addresses like it should. (you can't create a socket, without first knowing if the address is IPv6 or not.) The reordering of those roles would involve rewriting most of the net module, and some of httpclient. I fiddled with it, and the changes just propagated through the entire net module's code. Or possibly more likely, I was doing something wrong. But it looks like it'd be a mess. Easier to just write an async http client, and forget about that broken net module.

A cludgy hack to enable IPv6 in the current httpclient would be to look up the address, use that for the domain to newSocket, then look up the address again since s.connect() only lets you pass an unresolved address. But of course address look up uses leaky malloc operations, so it isn't exported by net.

You could always execProcess "curl" I guess.

**Comment by cyisfor** [comment]
I did the cludge, and submitted a pull request. Maybe if I'm really masochistic I'll write asynchttpclient.nim one of these days.

https://github.com/nim-lang/Nim/pull/3815

**Comment by Araq** [comment]
So ... is this still an issue?

**Comment by dom96** [comment]
Yes.
