### ISSUE TITLE
Initialization of base class variable

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#3816]
``` nim
type
    T* = ref object of RootObj
        x: range[1 .. 1]
    U* = ref object of T

var u = U()
```

This code generates this error message:

```
bug.nim(6, 10) Error: field not initialized: x
```

It's not an issue in this case because the field can be initialized in the constructor, but the base class might be defined in another module and the field might not be exported.

**Comment by ringabout** [comment]
When you change the low part of the range to zero, it works
```nim
type
    T* = ref object of RootObj
        x: range[0 .. 1]
    U* = ref object of T

var u = U()
```

**Comment by bung87** [comment]
doesn't this should close? it's invalid code to me.

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/20480
