### ISSUE TITLE
strange  Error: ':' expected

### ISSUE THREAD

**Issue by encorehu** [nim-lang/Nim#3822]
code:

    var a=""
    if a =="a":
      echo "a"
    else:
      echo "a:empty"

when compile, this:

    Hint: system [Processing]
    Hint: a [Processing]
    a.nim(2, 6) Error: ':' expected

i found in line2, there need a whitespace between `==` and `"a"`

    if a == "a":
    ...

or, delete a whitespace between `if a` and `==`

    if a=="a":
    ...

and the error gone

i use latest nim-0.13.0, winxp

**Comment by def-** [comment]
This is intentional, see the syntax changes in http://nim-lang.org/news.html#Z2016-01-18-version-0-13-0-released
