### ISSUE TITLE
Uniform Block Syntax

### ISSUE THREAD

**Issue by sheerun** [nim-lang/Nim#3834]
Hey,

I know, easier said than done, but I'd like to suggest an addition to already awesome nim syntax.

_Background_: I'm Ruby & JS developer so I'm not used to python's. I feel unreasonable resistance towards Nim because of its space-significant block syntax (python/coffeescript-like):

``` nim
if (42 >= 0):
  printf("42 is greater than 0")
```

_Facts_: Nim already supports two syntax features that unify few common syntax themes:
1. `someIdentifier` (js-like) and `some_identifier` (ruby-like) - Uniform Variable Naming
2. `something(subject)` (js-like) and `subject.something` (ruby-like) - Uniform Function Call 

So finally the idea: Implement Uniform Block Syntax that allows two extra block syntaxes:

javascript/c-like:

``` c
if (42 >= 0) {
  printf("42 is greater than 0")
}
```

ruby/elixir-like:

``` elixir
if (42 >= 0) do
  printf("42 is greater than 0")
end
```

I'd still _leave significant indentation_, and just _ignore_ `do`, `end`, `{` and `}` tokens. This forces proper style on module authors and at the same time allows to mark end of blocks, making code more readable (and it's probably easier to implement).

**Comment by Bulat-Ziganshin** [comment]
I should add that `(42 >= 0)` can be reduced to `42 >= 0` in all three cases. Also, we may use Lua rules for `do end` - lineend breaks a statement, and Go/C rules for `{}` - lineend doesn't break a statement. So, here we go:

```
  if 42 > 0:
    print 1
    print 2
  else:
    print 3
    print 4

  if 42 > 0 then
    print 1
    print 2
  else
    print 3
    print 4
  end

  if 42 > 0 {
    print 1;
    print 2
  } else {
    print 3;
    print 4
  }
```

And indentations in the second and third examples may be arbitrary.

**Comment by Yardanico** [comment]
This issue should probably be closed because syntax skins were removed and there's no plans to bring them back, right?

**Comment by dom96** [comment]
Yeah, the idea of syntax skins has been rejected.
