### ISSUE TITLE
Time parsing bug

### ISSUE THREAD

**Issue by Xe** [nim-lang/Nim#3838]
I am using nim to parse time objects from random people into a TimeInfo object. By using the [`timeToTimeInfo`](https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L1257-L1287) proc, I have found that the time `2016-02-07T23:17:30.154653+00:00` (unix time `1454915850`) cannot be parsed from a `Time` to a `TimeInfo` because it tries to define a day that has 24 hours in it, but the hour range only ranges from 0-23. Maybe [this line](https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L1284) is the fault?

**Comment by vegansk** [comment]
See #3678 and use ``getLocalTime`` or ``getGMTime``

**Comment by coffeepots** [comment]
Unfortunately timeToTimeInfo is broken and has to go, and as vengansk says it's redundant anyway as getLocalTime et al do the same job. Aside from the hour 24 issue there was also a problem with times at the end of the year, where countYearsAndDays rolls over to the next year for December 31st!

**Comment by dom96** [comment]
According to odc on IRC this is now fixed.
