### ISSUE TITLE
The website does not use HTTPS

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#3841]
The release sources and binaries are being served over HTTP at http://nim-lang.org/download.html

**Comment by Varriount** [comment]
I'd be willing to pay for a certificate, add long as the cost is reasonable (less than 100 USD). Anyone have a preference for which vendor?

**Comment by vegansk** [comment]
@Varriount, here is the alternative: https://letsencrypt.org/

**Comment by trustable-code** [comment]
@FedericoCeratto, good point.
A good website should use HTTPS. It can prevent fraud, looks good to the user and it also gives a higher Google rank.
I recommend https://letsencrypt.org/ or https://www.startssl.com/ . StartSSL is also free (as in free beer) and expires after 1 year. Let’s Encrypt uses a completely new approach, as it's automated, but needs additional software on the server.

**Comment by FedericoCeratto** [comment]
Letsencrypt works quite easily with Nginx: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

**Comment by def-** [comment]
"Let's Encrypt" works fine. The only thing to consider is if you want compatibility for Windows XP users: https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

**Comment by Varriount** [comment]
Should XP machines even be connected to the internet? I know XP is still being used, but by how many actual humans?

**Comment by def-** [comment]
They should definitely not be, I'm just saying you have to decide if you want to exclude those people (12% for my website).

**Comment by trustable-code** [comment]
What about making HTTPS optional?

**Comment by def-** [comment]
Google automatically uses https for its search results and people can't share links to potential WinXP users.

**Comment by Araq** [comment]
Now it is https. :-)
