### ISSUE TITLE
interact with variables at module scope in macro

### ISSUE THREAD

**Issue by shaunc** [nim-lang/Nim#3844]
The following code:
```nim
import macros

var x = 1;

macro foo() : untyped =
  inc(x)
  echo $x
  result = newStmtList()

foo()
foo()
echo $x
```
Produces
```
2
2
1
```
I am trying to define a counter so I can assign unique names in a macro. Using a random # generator seems like overkill. Any suggestions? And ... I presume this is a bug?

**Comment by vegansk** [comment]
It's because macro runs in compile time and ``var x`` lives in runtime. The working version:

```nimrod
import macros

var x {.compiletime.} = 1;

macro foo() : untyped =
  inc(x)
  echo $x
  result = newStmtList()

foo()
foo()
```

But there is another bug! See #3845

**Comment by shaunc** [comment]
Ah thanks! -- I'll close this in favor of your bug.
