### ISSUE TITLE
asynchttpserver may consume unbounded memory reading headers

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#3847]
asynchttpserver places no restrictions on headers size or count. 

``` python
print 'GET / HTTP/1.1'
i = 0
data = 's' * 10000
while True:
    i += 1
    print 'Foo%d: ' % i, data
```

For example, script from Jester README consumes 2GB and crashes (because of ulimit) after 70 seconds (on localhost, but in practice asynchttpclient is only able to process 100 Mbit/s).

`asynchttpclient` shares the same problems.

(This is a denial of service security issue which probably shouldn't be disclosed publicly, but I don't think anyone cares about Nim security.)

**Comment by dom96** [comment]
Do you think we also need to add checks to ``recvLine``?

**Comment by zielmicha** [comment]
Yes.

**Comment by cheatfate** [comment]
@dom96, @Araq this bug is not resolved. Just because there no limits on first request line too...
so request like GET /asdzxcasdzxcasd.... (many symbols without newlines) will crash asynchttpserver too.

**Comment by cheatfate** [comment]
Http header with `Hostname: asdzxcasdzxcasdzxc.... (many symbols without newlines) will crash asynchttpserver...

**Comment by dom96** [comment]
I suspected as such in my previous comment:

> Do you think we also need to add checks to ``recvLine``?

Did you miss that @cheatfate?

**Comment by dom96** [comment]
Also, you seem to suggest on IRC that fixing this requires a new proc called ``recvUntil``. I don't think that's the case, just add a sane limit in ``recvLine`` as I did for the header reading code.

**Comment by cheatfate** [comment]
@dom96 i dont miss your post, i just not understand why you not open ticket again?

**Comment by cheatfate** [comment]
@dom96, recvLine() is a good proc for **HTTP**, but if some kind of protocol requires other delimiters? So i think its better to have more general variant of recvLine() which support different kinds of delimiters...

**Comment by cheatfate** [comment]
And about

> just add a sane limit in recvLine as I did for the header reading code

I'm not using asynchttpserver (because it totally insecure), but many people use it in "production". So if you want to help them you can always:

> just add a sane limit in recvLine as I did for the header reading code

**Comment by dom96** [comment]
> @dom96, recvLine() is a good proc for HTTP, but if some kind of protocol requires other delimiters? So i think its better to have more general variant of recvLine() which support different kinds of delimiters...

Perhaps. But what protocols actually require something like this, can you name some? I don't want to end up adding this to the standard library when it's not actually needed.

**Comment by dom96** [comment]
> I'm not using asynchttpserver (because it totally insecure), but many people use it in "production".

There is a reason why I always say "Put asynchttpserver behind a reverse proxy". It should be fairly safe behind one.

**Comment by cheatfate** [comment]
@dom96, i think you can add this "DO NOT USE IT AS REAL HTTP SERVER (put it behind a reverse proxy)"

**Comment by cheatfate** [comment]
> Perhaps. But what protocols actually require something like this, can you name some? I don't want to end up adding this to the standard library when it's not actually needed.

HTTP multipart/form-data for example.
so i can easily receive part with var formPart = await recvUntil("--Asrf456BGe4h", sizeOfPart)...

**Comment by drbo** [comment]
- As I understand it, the vulnerabilities are strictly memory-consumption denial of service, so a reverse proxy can solve the problem. `asynchttpserver` can temporarily work around this by only binding to `localhost` (so that users need to reverse-proxy to it using something like nginx).
- In the long term, `asynchttpserver` needs production-quality defenses against DoS.

**Comment by Araq** [comment]
That turns an "Out of memory" DoS into an "unhandled exception" DoS.
