### ISSUE TITLE
Compile-time SIGSEGV when declaring .importcpp method with return value 

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#3848]
Sample:

``` nim
type MyObject {.importcpp: "MyObject", nodecl.} = object
method aMethod(this: ptr MyObject): bool {.importcpp: "aMethod", nodecl, base.}
```

Works fine if you remove `bool` return type from the method declaration. Also works fine if you replace `method` with `proc`.

**Comment by Araq** [comment]
You cannot importc(pp) methods.

**Comment by endragor** [comment]
Yes, I guessed that. Though I found it useful when interfacing with large class hierarchies - it helps to identify occasional redeclaration of methods that were already declared for parent types (considering you mark all methods with `{.base.}` pragma). It also acts as a hint that this function is `virtual` in C++ code.
