### ISSUE TITLE
Generic converter doesn't work

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#3850]
Not sure if it's expected to work, but here is the sample:

``` nim
type
  EnumContainer[T: enum] = object
    val: T

  MyEnum = enum
    meEnumValue

converter fromEnum[T: enum](t: T): EnumContainer[T] =
  result = EnumContainer(val: t)

let cont: EnumContainer[MyEnum] = meEnumValue
# Error: type mismatch: got (MyEnum) but expected 'EnumContainer[MyEnum]'
```

**Comment by Araq** [comment]
There is some support for generic converters but it's nasty. ;-)

**Comment by Yardanico** [comment]
@Araq, code from @endragor post doesn't work, but it works if you change "result = EnumContainer(val: t)" to "result = EnumContainer[T](val: t"
```nim
type
  EnumContainer[T: enum] = object
    val: T

  MyEnum = enum
    meEnumValue

converter fromEnum[T: enum](t: T): EnumContainer[T] =
  result = EnumContainer[T](val: t)

let cont: EnumContainer[MyEnum] = meEnumValue
# Error: type mismatch: got (MyEnum) but expected 'EnumContainer[MyEnum]'
```

**Comment by narimiran** [comment]
The original example now raises *"Error: object constructor needs an object type"*, which IMO is quite clear, and it makes it obvious that @Yardanico's fix is what is needed.

Close?

**Comment by Araq** [comment]
I agree with narimiran.
