### ISSUE TITLE
can't import symbol with same name as module

### ISSUE THREAD

**Issue by shaunc** [nim-lang/Nim#3852]
Using latest nim, if I have a module foo.nim:

```nim
proc foo() : void =
  discard
```
And then in a second module bar I have:

```nim
from foo import foo
```
The compiler crashes with
```
/Volumes/Macintosh_HD/Users/shauncutts/src/bar.nim(7, 29) Error: internal error: importSymbol: 2
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```
Presumably this is because the procedure is clashing with the module name. More reasonable than crashing would be to have the procedure shadow the module.

**Comment by vegansk** [comment]
Duplicates #3333

**Comment by shaunc** [comment]
Right -- closing this.
