### ISSUE TITLE
vcc: rand_max incorrect

### ISSUE THREAD

**Issue by warkid** [nim-lang/Nim#3853]
Definition of [random(max:float)](https://github.com/nim-lang/Nim/blob/a121c3f9eb2a348b9d6ae03ffd01aab26a238c30/lib/pure/math.nim#L232) assumes that RAND_MAX should be UINT_MAX for vcc. It is explained in comment and even links to msdn(but to a page without mention of RAND_MAX).
Actually RAND_MAX in msvc is 32767. I have this msdn [link](https://msdn.microsoft.com/en-us/library/2dfe3bzd.aspx) :) I also checked this with MSVC 2013 CE - actual code from rand.c:
```
int __cdecl rand (
        void
        )
{
        _ptiddata ptd = _getptd();

        return( ((ptd->_holdrand = ptd->_holdrand * 214013L
            + 2531011L) >> 16) & 0x7fff );
}

```

**Comment by Araq** [comment]
Nim doesn't use C's rand anymore.
