### ISSUE TITLE
Cannot convert varargs .items() iterator to closure iterator

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3854]
```nim
template toClosure(i): auto =
  iterator j: type(i) {.closure.} =
    for x in i:
      yield x
  j

iterator myiter(i: iterator): auto =
  for j in i():
    yield j

proc x[T](a: varargs[T]) =
  for i in myiter(toClosure(a.items())): # Error: illegal capture 'a'
    echo i

x([1,2,3])
# this compiles
# for i in myiter(toClosure([1,2,3].items())):
  # echo i
```
Other conversions (seq, table) are ok.

**Comment by def-** [comment]
varargs and openarray can't be stored in a variable, so I guess that's the problem with capturing them.

**Comment by scriptum** [comment]
Actually I'm trying to implement multiple interfaces to allow user to pass iterator, varargs or nothing and avoid code duplication:
https://gist.github.com/scriptum/34933a248dc22d0dd516#file-digraph-nim-L179

**Comment by Araq** [comment]
Not a bug though.
