### ISSUE TITLE
Using newSeqWith causes out of memory while newSeq doesn't

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3857]
Same sequence length, but newSeqWith fails with OOM.

``` nim
import sequtils
const N = 500000000
# var a = newSeqWith(N, 1) # out of memory

var b = newSeq[int](N)
for i in 1..<N: b[i] = 1
```

I use `ulimit -S -v 6291456` for all applications and this is likely causes OOM, but pure newSeq works and that's wierd.

**Comment by def-** [comment]
A copy of the entire seq is made when using newSeqWith, let me try to find out why.

**Comment by scriptum** [comment]
This works:
```nim
template myNewSeqWith*(varName: expr, len: int, init: expr): expr =
  var varName = newSeq[type(init)](len)
  for i in 0 .. <len:
    varName[i] = init
myNewSeqWith(a, 500000000, 1)
echo a[0]
```

**Comment by Araq** [comment]
Workarounds exist and the real problem here is the lack of a move optimizer for the old runtime, which will enable at some point.
