### ISSUE TITLE
Is there proper way to syntax check .nims file?

### ISSUE THREAD

**Issue by yuutayamada** [nim-lang/Nim#3858]
Hi Nim developers.

Is there proper way to check .nims file?

I tried following command in nim repository, but
it started installing nimble...

``` sh
$ nim check --import:system/nimscript ./install_nimble.nims
```

**Comment by Araq** [comment]
I don't think there is a way.

**Comment by AlexKotik** [comment]
Is there any progress on this issue? It is kinda annoying to write nimscripts in VSCode while all imports from system/nimscript gets red underline all around them and code completion breaks all over the place.

**Comment by Araq** [comment]
No, but you should probably write a little less of NimScript logic? ;-)

**Comment by ringabout** [comment]
update: https://github.com/nim-lang/Nim/pull/19444
