### ISSUE TITLE
parallel broken for nim-0.13.0_x64.exe

### ISSUE THREAD

**Issue by warkid** [nim-lang/Nim#3861]
**cc=vcc** parallel doesn't use more than one thread(apparent in taskmanager and msvc debugger shows only one worker thread is actually 'working', others are waiting for work).

**cc=gcc** simply crashes:

<pre>Starting program: D:\work\test\nim\parallel\tforstmt.exe                     
[New Thread 11020.0x1028]                                                    
[New Thread 11020.0x4b8]                                                     
[New Thread 11020.0x1618]                                                    
[New Thread 11020.0x48c]                                                     
[New Thread 11020.0x1a60]                                                    
[New Thread 11020.0x9d0]                                                     
[New Thread 11020.0x2a44]                                                    
[New Thread 11020.0x2300]                                                    
[New Thread 11020.0x8a0]                                                     
7                                                                            
6                                                                            
                                                                             
Program received signal SIGSEGV, Segmentation fault.                         
[Switching to Thread 11020.0x48c]                                            
0x0000000000437d15 in popFrame ()                                            
    at d:\work\test\nim\parallel\nimcache\tforstmt.c:177                     
177             frameptr_25836 = (*frameptr_25836).prev;                     
(gdb) bt                                                                     
#0  0x0000000000437d15 in popFrame ()                                        
    at d:\work\test\nim\parallel\nimcache\tforstmt.c:177                     
#1  0x000000000043803f in pwrapper_161056 (                                  
    thread=0x450990 <workersdata_157625+2640>, args=0x22fc80)                
    at d:\work\test\nim\parallel\nimcache\tforstmt.c:298                     
#2  0x00000000004163ed in slave_156623 (w=0x450990 <workersdata_157625+2640>)
    at d:\work\test\nim\parallel\nimcache\stdlib_threadpool.c:1268           
#3  0x0000000000436a30 in threadprocwrapdispatch_158809 (                    
    thrd=0x44e3b0 <workers_157622+48>)                                       
    at d:\work\test\nim\parallel\nimcache\stdlib_system.c:17257              
#4  0x0000000000436a69 in threadprocwrapstackframe_158605 (                  
    thrd=0x44e3b0 <workers_157622+48>)                                       
    at d:\work\test\nim\parallel\nimcache\stdlib_system.c:17269              
#5  0x0000000000436a9c in threadprocwrapper_158404 (                         
    closure=0x44e3b0 <workers_157622+48>)                                    
    at d:\work\test\nim\parallel\nimcache\stdlib_system.c:17281              
#6  0x00000000770a59ed in KERNEL32!BaseThreadInitThunk ()                    
   from C:\Windows\system32\kernel32.dll                                     
#7  0x00000000772db831 in ntdll!RtlUserThreadStart ()                        
   from C:\Windows\SYSTEM32\ntdll.dll                                        
#8  0x0000000000000000 in ?? ()                                              
Backtrace stopped: previous frame inner to this frame (corrupt stack?)       
(gdb) print frameptr_25836                                                   
$1 = (TFrame *) 0x0                                                          
</pre>

**Comment by Araq** [comment]
Thread local storage on Windows has been fixed.
