### ISSUE TITLE
Nim generates pointer argument for inheritable .importcpp type when passing by value is expected

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#3867]
Sample:
```nim
type AnObject {.importcpp, nodecl, inheritable.} = object

proc doSomething(obj: AnObject) {.exportc.} =
  # generated signature with .inheritable: N_NIMCALL(void, doSomething)(AnObject* obj);
  # generated signature without .inheritable: N_NIMCALL(void, doSomething)(AnObject obj);
  discard
```
It seems `inheritable` implicitly adds `byref` pragma, which, in turn, makes every occurrence of the type in signatures be converted to pointer type. Was it made on purpose? It was surprising to me: I would prefer explicitly specifying `ptr` marker when I need pointer type. It's not obvious that `inheritable` pragma adds such behaviour.

**Comment by Araq** [comment]
It's also not obvious how anything could be passed by value with .inheritable... So yes, it's a feature.

**Comment by endragor** [comment]
Well, at least when interfacing with C++, basically everything is inheritable. But you still want to control whether things are passed by value or by pointers. Thankfully, there is `bycopy` pragma which I could use.

Thanks for the reply! Closing this one.
