### ISSUE TITLE
Bad interaction between defer and async.

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#3877]
Hi there.

This is for Nim 0.13.

Referring to this nim forum thread:

http://forum.nim-lang.org/t/2044

Within async functions, "defer" statements are executed as soon as "await" is called, rather than when the scope is exited.

Example code:

``` python
import asyncdispatch, asyncnet

type

  Server = ref object
    socket: AsyncSocket

proc newServer(): Server = Server(socket: newAsyncSocket())

proc loop(server: Server, port=7687) {.async.} =
    echo "binding..."
    server.socket.bindAddr(port.Port)
    echo "bound..."
    echo "listen..."
    server.socket.listen()
    echo "listening..."

    defer:
        echo "Closing socket..."
        server.socket.close()
        echo "Closed."

    while true:

        echo "Listening for connection..."
        let (netAddr, clientSocket) = await server.socket.acceptAddr()

        echo("Accepted connection from ", netAddr)

var server = newServer()
waitFor loop(server)
```

When I compile and run that, I get this output:

``` python
binding...
bound...
listen...
listening...
Listening for connection...
Closing socket...
Closed.
```

**Comment by dom96** [comment]
The fact that ``defer`` is allowed in async procs is dangerous. I've used it in ``downloadFile`` and created some puzzling crashes.

Here is my test case:

```nim
import asyncdispatch

proc bar() {.async.} =
  echo("Hey")

proc foo() {.async.} =
  defer:
    echo "bye"
  
  await bar()

waitFor foo()
```

I'm not sure whether to disallow it outright or come up with a transformation that adds support for it.

**Comment by wizzardx** [comment]
I'm pretty clueless, but..
How does C# handle it?
Would transforming "defer" into a "try...finally" block help?

**Comment by mratsim** [comment]
@yglukhov and @dom96 I think this was solved by #7770 and #7973.

Dom's test case works on devel for me.

**Comment by Araq** [comment]
Seem to be fixed, reopen if it's still an issue.

**Comment by timotheecour** [comment]
ping @dom96 @wizzardx shall we close this?

original example also for me in devel:

```
rnim tests/nim/t97_defer_async.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r tests/nim/t97_defer_async.nim
Hint: operation successful (45862 lines compiled; 1.691 sec total; 74.332MiB peakmem; Debug Build) [SuccessX]
binding...
bound...
listen...
listening...
Listening for connection...
```

python -c 'import socket;s = socket.socket();s.connect(("127.0.0.1", 7687))'
```
Accepted connection from 127.0.0.1
Listening for connection...
```
