### ISSUE TITLE
vcc: Winsock redefintion errors

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#3879]
When using Microsoft Compiler and Visual Studio headers you can get couple of <redefinition> errors. For example:
```
C:\Program Files (x86)\Windows Kits\8.1\include\\shared\ws2def.h(221): error C2011: 'sockaddr': 'struct' type redefinition
C:\Program Files (x86)\Windows Kits\8.1\include\\um\winsock.h(477): note: see declaration of 'sockaddr'
C:\Program Files (x86)\Windows Kits\8.1\include\\shared\ws2def.h(421): error C2059: syntax error: 'constant'
C:\Program Files (x86)\Windows Kits\8.1\include\\shared\ws2def.h(615): error C2011: 'sockaddr_in': 'struct' type redefinition
C:\Program Files (x86)\Windows Kits\8.1\include\\um\winsock.h(304): note: see declaration of 'sockaddr_in'
```
To avoid this we need to pass to C compiler "WIN32_LEAN_AND_MEAN" define.
Like:
```
when defined(vcc):
  {.passC: "-DWIN32_LEAN_AND_MEAN".}
```

**Comment by veksha** [comment]
how can it be Nim issue? I think it's programmer's issue.
If you have errors (I don't) just add passC line to your program and voila. Why force this define to all developers?

Show me the piece of nim code that fails for you.

For my case I had to comment out this passC line in `lib/windows/winlean.nim` to make my program compile.
So now I must to comment it out every time I pull last Nim sources from git?
Please consider removing it or make it optional.

**Comment by Araq** [comment]
This is an old issue, please create a new one. Fwiw I always thought ``WIN32_LEAN_AND_MEAN`` is a best practice.
