### ISSUE TITLE
Async procs. Can't use 'await' in templates

### ISSUE THREAD

**Issue by maratkhafizov** [nim-lang/Nim#3885]
Hi.
When I use `await` keyword in templates, I'm getting the following error:
`asyncdispatch.nim(1324, 22) Error: expression 'future' has no type (or is ambiguous)`
Code snippet to reproduce:

``` nimrod
import asyncnet, asyncdispatch

var clients {.threadvar.}: seq[AsyncSocket]

proc processClient(client: AsyncSocket) {.async.} =
  template do_smth()=
    let line = await client.recvLine()
    if line == "":
      echo "client disconnected"
  while true:
    do_smth()
    for c in clients:
      await c.send(line & "\c\L")

proc serve() {.async.} =
  clients = @[]
  var server = newAsyncSocket()
  server.bindAddr(Port(12345))
  server.listen()

  while true:
    let client = await server.accept()
    clients.add client

    asyncCheck processClient(client)

asyncCheck serve()
runForever()
```

Nim version: 0.13.0

**Comment by dom96** [comment]
You might be able to use ``yield`` as a workaround. You won't be able to assign the result like you can with ``await`` though.

**Comment by maratkhafizov** [comment]
`yield` causes the `Error: 'yield' only allowed in an iterator`. Can't use `sslLoop` template for the same reason.

**Comment by dom96** [comment]
Have you tried using an ``{.immediate.}`` template?

**Comment by maratkhafizov** [comment]
Sorry, I don't know what was the reason of the `yield` error, but I cannot reproduce it now. Anyways, I want to read the result of async procedures. So I handle `Future` objects and use `waitFor`.

**Comment by Yardanico** [comment]
@Araq, @dom96 - close?
this template is needed to be a {.dirty.} one, and everything works then

**Comment by dom96** [comment]
I don't think so. Dirty shouldn't be necessary.

**Comment by Yardanico** [comment]
@dom96 - this code snippet wouldn't work without a dirty template because line variable is defined in a template
