### ISSUE TITLE
Feature request: Determine the amount of data pending in the network's input buffer

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#3887]
When using non-blocking sockets always useful to know how much data is available in socket's network buffer, so we can recv it in one call without blocking.

On Windows you can obtain this information using [ioctlsocket() function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738573%28v=vs.85%29.aspx).
On Posix systems you can obtain this information using BSD: [ioctl() function](https://www.freebsd.org/cgi/man.cgi?query=ioctl&sektion=2) or LINUX: [ioctl() function](http://man7.org/linux/man-pages/man2/ioctl.2.html) and [ioctl_list](http://man7.org/linux/man-pages/man2/ioctl_list.2.html).

I'm already made some changes to nativesockets.nim and want to make pull request to this feature.

**Comment by dom96** [comment]
For what use case is this useful? it sounds to me like you should simply use async await.

**Comment by cheatfate** [comment]
Yeah, its useless now.
I thought that by using **recv** call with size of buffer bigger than available data you can get block, but after some testing, i understand that i'm wrong. **recv** just returned with available data and no blocking occurs.
