### ISSUE TITLE
yearday off by one day ?

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#3890]
```
  import times
  echo "tzname       :   " , getLocalTime(gettime()).tzname
  echo "getTime      :   " , gettime()
  echo "getLocalTime :   " , getLocalTime(gettime())
  echo "yearday      :   " , getLocalTime(gettime()).yearday

  #outputs
  #getTime      :   Sun Feb 21 23:06:03 2016
  #getLocalTime :   Sun Feb 21 23:06:03 2016
  #yearday      :   51
  #
  #January 31 days + 21 days of Feb =  52 days . Or not ??
```

**Comment by def-** [comment]
In the documentation it says:

> The number of days since January 1, in the range 0 to 365.

So I would say 0 means It's January 1, 1 January 2, ...

**Comment by Tarmean** [comment]
Probably so that you can initialize it with the default 0? Still seems unintuitive, though.

**Comment by Araq** [comment]
I think the new times library fixed that or if not, there are good reasons for its behaviour.

**Comment by GULPF** [comment]
The old behavior has been kept to avoid another breaking change. Don't know if that counts as a good reason or not :)
