### ISSUE TITLE
Escape characters not recognized

### ISSUE THREAD

**Issue by r-ku** [nim-lang/Nim#3897]
Using proc as prefix operator with a string makes it no longer recognize escape characters. `u"\r\n\t"` is treated as "raw" 6 characters long string.

    proc u(x: string): string = x
    doAssert "\r\n\t".u == "\r\n\t"    # works
    doAssert u"\r\n\t" == "\\r\\n\\t"  # works but should not
    doAssert u"\r\n\t" == "\r\n\t"     # breaks but should work

**Comment by jangko** [comment]
taken from lexer.nim:

```Nimrod
    of '\"':
      # check for extended raw string literal:
      var rawMode = L.bufpos > 0 and L.buf[L.bufpos-1] in SymChars
      getString(L, tok, rawMode)
```
and SymChars is defined as:

```Nimrod
const
   SymChars*: set[char] = {'a'..'z', 'A'..'Z', '0'..'9', '\x80'..'\xFF'}
```

looks like the lexer treat any string preceded by single SymChars as raw string

**Comment by Varriount** [comment]
I fairly sure this is intentional - it allows string prefixes to interpret backslash characters in the way they choose, without extra work.

**Comment by r-ku** [comment]
Well in this case it backfires as i use string prefix to convert nim string to utf-8-compatible string type. Getting rid of escape characters is not what is needed in this case. Would it not make more sense to have `r` for raw strings and allow custom prefixes to replace "\n" with "\\n" (and others) if they need actual raw strings?

**Comment by jangko** [comment]
the parser will parse differently for different call syntax:
```Nimrod
"\r\n\t".u     #nnkCall
u"\r\n\t"      #nnkCallStrLit
u "\r\n\t"     #nnkCommand
u("\r\n\t")    #nnkCall
```

and the manual says something like this:

> Generalized raw string literals
Terminal symbols in the grammar: GENERALIZED_STR_LIT, GENERALIZED_TRIPLESTR_LIT.
The construct identifier"string literal" (without whitespace between the identifier and the opening quotation mark) is a generalized raw string literal. It is a shortcut for the construct identifier(r"string literal"), so it denotes a procedure call with a raw string literal as its only argument. Generalized raw string literals are especially convenient for embedding mini languages directly into Nim (for example regular expressions).
The construct identifier"""string literal""" exists too. It is a shortcut for identifier("""string literal""").

**Comment by Araq** [comment]
Works as the spec claims it works.

**Comment by r-ku** [comment]
Spec claims:

> The construct identifier"""string literal""" exists too. It is a shortcut for identifier("""string literal""").

However:

    proc u(x: string): string = x
    doAssert u("\r\n\t") == u"\r\n\t"     # fails

In all honesty spec does not make much sense. How can you assume that **EVERYONE** will wish to use raw string literals in this case. It would make sense if proc would subscribe to or opt out of raw string literal behaviour. It is perfectly illustrated by need of it for my `ustring` implementation.

**Comment by Varriount** [comment]
@r-ku Look at strutils.unescape

**Comment by r-ku** [comment]
This is usability problem. You can not seriously expect people to write `u"修好它"` to get utf-8 string literal in one place and `u"修好它\n".unescape` in another.

**Comment by Araq** [comment]
u "\n" # escape sequence works
u"\n" # escape sequence doesn't.

Perfectly fine IMHO.

**Comment by r-ku** [comment]
Problematic part is we cant write `u"\n".something()`, have to write `(u "\n").something()` or `"\n".u.something` neither of which are as elegant. I suppose `u` itself could unescape string but its workaround at best. It also introduces overhead to strings with escape characters. Additional copying etc.

**Comment by Araq** [comment]
So overload the 'u' so that it transforms ``string{lit}`` at compile-time.

**Comment by r-ku** [comment]
Thats a solution, thanks
