### ISSUE TITLE
command call misinterprets "(" after space as normal function call

### ISSUE THREAD

**Issue by shaunc** [nim-lang/Nim#3898]
For example,

``` nim
var a = false
assert a != true
```

works, but the following causes a compiler error:

``` nim
var a, b, c: bool
a = false
b = true
c = true
assert (a != b) == c
```

Error:

```
test.nim(5, 17) Error: type mismatch: got (empty, bool)
but expected one of: 
system.==(x: array[I, T], y: array[I, T])
system.==(x: ref T, y: ref T)
system.==(x: float, y: float)
system.==(x: int8, y: int8)
system.==(x: char, y: char)
system.==(x: T, y: T)
system.==(x: int64, y: int64)
system.==(x: pointer, y: pointer)
system.==(x: set[T], y: set[T])
system.==(x: T, y: T)
system.==(x: int32, y: int32)
system.==(x: cstring, y: cstring)
system.==(x: Enum, y: Enum)
system.==(x: float32, y: float32)
system.==(x: int, y: int)
system.==(x: int16, y: int16)
system.==(x: T, y: T)
system.==(x: seq[T], y: seq[T])
system.==(x: string, y: string)
system.==(x: ptr T, y: ptr T)
system.==(x: bool, y: bool)
```

**Comment by def-** [comment]
That looks more like an issue with the command invocation. Using brackets it works:

```nim
assert((a != b) == c)
```

**Comment by scriptum** [comment]
I got `undeclared identifier` recently for `!=` operator inside templates. Had to replace with `not (a == b)`.

**Comment by def-** [comment]
@RPG sounds like a bug because `!=` is implemented as a template itself.

**Comment by scriptum** [comment]
@def- that explains a lot. But I cannot reproduce this:)

**Comment by shaunc** [comment]
I was thinking it might have something to do with the order in which types are inferred in the two templates in question when they are composed. ... e.g. (for instance) AST resulting from `!=` doesn't yet have types and then is forced to by `assert`. Exactly how this works (and should work) is still a little bit black magic for me. I can also get the error using "echo" instead of "assert".

**Comment by shaunc** [comment]
Ok @def -- you were on the right track. The following fails too:
```nim
var a, b, c: int

a = 1
b = 2
c = 3
assert (a + b) == c
```
but if you reverse
```nim
assert c == (a + b)
```
it works.

Seems that space before paren isn't being counted in this context. Hmm... doesn't even have to do with the fact that assert is a template. For instance replacing the assert by:
```nim
proc foo(i: bool) : void
foo (a + b) == c
```
also fails. Hmm... I guess manual is unclear. I certainly want command invocation syntax to be invoked if and only if a space follows function/(...).

**Comment by Araq** [comment]
@shaunc That was intended to be dealt with ``#? strongSpaces`` but people voted against it.

**Comment by shaunc** [comment]
@Araq ... where do I vote? :) ... it could be that strong spaces goes too far, though. My preference would be to enable command invocation syntax iff space follows ident at start of expression ("prefix" position) but not affect infix evaluation.

Also currently the following fails:
```nim
proc foo(a: openArray[int]): void
foo [1, 2]
```
Perhaps if precedence of command invocation syntax is changed in parse the example invocations here could be solved without complete "strong spaces" implementation?

**Comment by Araq** [comment]
> Perhaps if precedence of command invocation syntax is changed in parse the example invocations here could be solved without complete "strong spaces" implementation?

Definitely a reasonable thing to do.
