### ISSUE TITLE
Wrong bounds check using template [] to access array in a const object

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#3899]
``` nim
type O = object
  a: array[1..2,float]
template `[]`(x: O, i: int): float =
  x.a[i]
const c = O(a: [1.0,2.0])
echo c[2]
```

makes compile time error

```
Hint: system [Processing]
Hint: t [Processing]
t.nim(4, 6) Error: index out of bounds
```

If `echo c[1]` used instead of `echo c[2]`, the compiled program prints `2.0`.
If `c` is declared as a `var`, the code works correctly.

**Comment by Araq** [comment]
Workaround: Use addressing from 0 like the rest of us ;-)

**Comment by jangko** [comment]
the error triggered here in semfold.nim:

```nimrod
proc foldArrayAccess(m: PSym, n: PNode): PNode =
  ...
  of nkBracket:
    idx = idx - x.typ.firstOrd
    if idx >= 0 and idx < x.len: result = x.sons[int(idx)]
    else: localError(n.info, errIndexOutOfBounds)
  ....
```

and the problem come from here in semexprs.nim:

```nimrod
proc semArrayConstr(c: PContext, n: PNode, flags: TExprFlags): PNode =
  ...
  result.typ.sons[0] = makeRangeType(c, 0, sonsLen(result) - 1, n.info)
```

makeRangeType in the last line of semArrayConstr need correct firstOrd and lastOrd, and I still don't know where to look for the information from inside semArrayConstr
