### ISSUE TITLE
The inconsistency of getTimezone function in times module

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3905]
On my computer (GMT+ 6) ``getTimezone`` returns -21600 for c target and -360 for js target. It's because of javascript's ``getTimezoneOffset`` function returning offset in minutes (https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L638)

Here is the code:
```nim
import times

echo getTimezone()
```

**Comment by dom96** [comment]
Fixed in #3906.
