### ISSUE TITLE
Different type inference behaviour when you use range[T] vs T with if expression

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#3907]
This doesn't compile on any system (expected):

``` nim
let a = 0'i64
let b = if false: -1 else: a
# Error: type mismatch: got (int64) but expected 'int literal(-1)'
```

However, this compiles fine on 64-bit system (`b` gets type `int`) but not on 32-bit system where int size is different from int64:

``` nim
let a: range[0'i64..high(int64)] = 0'i64
let b = if false: -1 else: a
```

Expected behaviour, in my opinion, is to always get a similar error as in the first sample.

**Comment by bung87** [comment]
still exists
