### ISSUE TITLE
Broken coroutine support in release 0.13.0

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#3910]
The "lib/pure/arch" directory is missing in the relased tarball, leading to missing coroutine support and breaking the ability to build the compiler docs. Related to #3823 

To reproduce:
tar xfJ nim-0.13.0.tar.xz && cd nim-0.13.0 && ./build.sh
echo "import coro" > test_import_coro.nim
./bin/nim -d:nimCoroutines c test_import_coro.nim

**Comment by Araq** [comment]
This has been fixed since quite a while.
