### ISSUE TITLE
Can countup and countdown iterators in Nim language be used in variable declaration?

### ISSUE THREAD

**Issue by alhabshi3k** [nim-lang/Nim#3912]
0
down vote
favorite
	

I am trying to learn Nim and its features, such Iterators; and i found that the following example works fine.

```nim
for i in countup(1,10):   # Or its equivalent 'for i in 1..10:' 
 echo($i)
```

However, The following do not works:

```nim
var 
 counter = countup(1,10) # THIS DO NOT WORK !
 # counter = 1..10   # This works

for i in counter :  
 echo($i)
```

The Nim Compiler reports the following error :

    Error: attempting to call undeclared routine: 'countup'

How countup is undeclared routine , where it is a built-in iterator !?

Or it is a bug to report about ?

What are the solutions to enforce a custom iterator in variable declaration, such countup or countdown ?

NOTE: I am using Nim 0.13.0 on Windows platform.

**Comment by def-** [comment]
That happens because `countup` is an inline iterator only. There is a definition for `..` as an inline iterator as well as a `Slice`:

- http://nim-lang.org/docs/system.html#...i,S,T
- http://nim-lang.org/docs/system.html#..,T,T

Inline iterators are 0-cost abstractions. Instead you could use a first-class closure iterator by converting the inline iterator to one:

```nim
template toClosure*(i): auto =
  ## Wrap an inline iterator in a first-class closure iterator.
  iterator j: type(i) {.closure.} =
    for x in i:
      yield x
  j

var counter = toClosure(countup(1,10))

for i in counter():
  echo i
````

**Comment by alhabshi3k** [comment]
Thanks for the clarification. 
IMHO , it would be nice to consider `countup `and `countdown `as Slicing methods beside being inline iterators. At the same time to maintain Nim language semantic and avoid complexity.

Keep the good job gentlemen.

**Comment by Araq** [comment]
Already reported and in the works.
