### ISSUE TITLE
Set [] proc expects keys to be printable?

### ISSUE THREAD

**Issue by samanthadoran** [nim-lang/Nim#3920]
Is this intended? I was using a key of something that I hadn't written a `$` proc for, and got this error.
Line causing it is:  https://github.com/nim-lang/Nim/blob/devel/lib/pure/collections/sets.nim#L157
```Nimrod
else: raise newException(KeyError, "key not found: " & $key)
```

**Comment by Araq** [comment]
No, that should be in a ``when compiles($key)``.
