### ISSUE TITLE
Generic Type Causing Macro Argument "untyped" To Be Evaluated

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/Nim#3922]
I was working on a macro and noticed this strange behaviour.

The following is the minimal example of the bug:

``` nim
import macros

macro myMacro*(head: typed, body: untyped): untyped =
  return newEmptyNode()

proc test(something: auto): string =
  myMacro something:
    if z > 3:
      result = "Surprise"

test(5)
```

When compiled, the compiler shows an error on line 8 `if z > 3:` complaining that z is not defined. However, it shouldn't care until the final AST is generated, correct?

Changing `auto` to `int`, the following compiles and runs fine, as expected:

``` nim
import macros

macro myMacro*(head: typed, body: untyped): untyped =
  return newEmptyNode()

proc test(something: int): string =
  myMacro something:
    if z > 3:
      result = "Surprise"

test(5)
```

Running on latest dev: 

```
nim -v
Nim Compiler Version 0.13.1 (2016-02-29) [MacOSX: amd64]
```

**Comment by jyapayne** [comment]
It seems this also occurs for any generic type.

Replacing the last working example with a generic parameter type causes the same issue:

```nim
import macros

macro myMacro*(head: typed, body: untyped): untyped =
  return newEmptyNode()

proc test[T: int](something: T): string =
  myMacro something:
    if z > 3:
      result = "Surprise"

test(5)
```

**Comment by Araq** [comment]
That's not a bug. There is a symbol lookup pass for generics that is not based on the types (since we don't know them). Arguably non-generic symbols should use a similar pass for more consistency.

**Comment by jyapayne** [comment]
Ok, that's interesting. So, correct me if I've got it wrong, writing a macro that depends on resolving undefined variables internal to the macro should never work, even with non-generic symbols?

**Comment by Araq** [comment]
That's what I would propose but it's a breaking change and I need to investigate what the results will be.

**Comment by andreaferretti** [comment]
With the generic preprocessing pass that has just been added, the first example now works

**Comment by jyapayne** [comment]
Cool :)
