### ISSUE TITLE
Compiler crashes when borrowing $

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#3928]
Came across this bug when working with distinct types. I wanted to create a JSON based config type with thin wrappers for the functionality I needed (mainly getting and setting keys in a dictionary). As the config were to be written to a file I also wanted to borrow the $ function to get the JSON as a string. However the compiler let me borrow the function without a return type which resulted in a SIGSEGV in the compiler when it came to an echo statement of the distinct JSON type. Below is the smallest code to reproduce.

```
type
  NewType = distinct int

proc `$`(c: NewType) {.borrow.}

var
  test: NewType = 5.NewType
echo test
```

The above code ends with: "SIGSEGV: Illegal storage access. (Attempt to read from nil?)". To make the code work change the borrow statement to: 
```
proc `$`(c: NewType):string {.borrow.}
```

**Comment by JesseTG** [comment]
~~Next time, read the fine print a bit more carefully.  If they promise low interest, this is how they *really* get you.~~
