### ISSUE TITLE
c2nim docs no longer seem to make it into the built docs

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3929]
See https://github.com/nim-lang/c2nim/issues/65

We need to make sure to include in the next release.

Just a friendly reminder.

**Comment by Araq** [comment]
Still need to automate this process better, but they are in the docs now.

**Comment by tajmone** [comment]
Seems that `docs/c2nim.html` is still (or again) missing from the documentation, both online and locally:

https://nim-lang.org/docs/c2nim.html

**Comment by Araq** [comment]
Fixed.

**Comment by kraptor** [comment]
Happened again @Araq 

https://nim-lang.org/docs/c2nim.html ---> 404

But is linked from:
https://nim-lang.org/docs/tools.html

Same as @tajmone realized some time ago.

**Comment by tajmone** [comment]
Seems that `c2nim.html` is missing again in Nim  v0.19.6!

Quite an unlike document this one, it gets regularly purged from the build.

It doesn't build locally either, even with `devel` branch.
