### ISSUE TITLE
'importc' pragma with underscores?

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#3938]
C function:
```C
Py_complex _Py_c_sum(Py_complex left, Py_complex right);
```

Nim wrapper procedure:
```nim
proc Py_c_sum*(left: PyComplex; right: PyComplex): PyComplex {.cdecl, importc: _Py_c_sum, dynlib: libraryString.}
```

This throws an error: Error: invalid token: _ (\95) !
How do I import this function?

Matic

**Comment by Araq** [comment]
With string literals.

```nim

proc Py_c_sum*(left: PyComplex; right: PyComplex): PyComplex {.cdecl, importc: "_Py_c_sum", dynlib: libraryString.}
```

**Comment by matkuki** [comment]
Thanks!

**Comment by rivasiv** [comment]
Hi 
This code generated by c2nim in process of wrapping headers:

type
  _fdb_transaction* = object
    handle*: ptr fdb_kvs_handle ## *
                             ##  ForestDB KV store handle.
                             ##

What is the proper way to fix this in such case ?

**Comment by Araq** [comment]
Use the ``#mangle`` directive for c2nim.

**Comment by rivasiv** [comment]
Thanks Araq.
