### ISSUE TITLE
JSON module constructs object for empty array

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#3950]
If you try to instantiate an empty JSON array using the constructors you get an empty object instead. Trying to create an empty object throws an error. Using parseJson and newJ*() works fine for both cases.

    echo (%[])
    => {}
    echo(%*[])
    => {}
    echo(%{})
    => Error: type mismatch: got (set[empty])
    echo(%*{})
    => Error: type mismatch: got (set[empty])
    echo(parseJson("[]"))
    => []
    echo(parseJson("{}"))
    => {}
    echo(newJArray())
    => []
    echo(newJObject())
    => {}

**Comment by Araq** [comment]
This has been fixed for 0.15.
