### ISSUE TITLE
nim 0.13.0 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [nim-lang/Nim#3968]
RE: https://github.com/Homebrew/homebrew/pull/50114

The sha256 checksum for nim 0.13.0 was originally (https://github.com/Homebrew/homebrew/commit/9f50ff3247d47f95a0e5f6fe7f2fc15a36990fe9)
688da1487eb507e0aa96b757a2a4a311123ad38ab68a10277a0415724f982b33
but for the current download on your site, it's
cd61f5e5768d4063596d6df578ae9bb5f9d52430773542987e91050b848cb1a9

The version with the original checksum can still be found here:
http://rpm-ostree.cloud.fedoraproject.org/repo/pkgs/xena/nim/nim/nim-0.13.0.tar.xz/509126e206164f9bd3b4a0a9612fb349/nim-0.13.0.tar.xz

Just wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by Araq** [comment]
We added some missing files. The new checksum is fine, relax.

**Comment by ilovezfs** [comment]
@Araq Thanks. In the future, a minor version bump would help prevent paranoia.
