### ISSUE TITLE
GC segfaults with IntSet

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#3969]
As reported by PMunch on IRC:
```nim
import json
import intsets

var cache = initIntSet()
for i in 0..100000:
    var keyEntryHash=hash(%*{"key2":i})
    assert(cache.contains(keyEntryHash)==false,"Key value not unique")
    cache.incl(keyEntryHash)
    echo i
echo "Done"
```
Segfault with default gc, works with markandsweep, v2 and boehm. Tested on Linux x86-64.

**Comment by cheatfate** [comment]
The problem is not with **IntSet**, but with
`var keyEntryHash=hash(%*{"key2":i})`
If you replace this line with
`var keyEntryHash=i`
all works perfectly...

So it looks like problem in **json** module.

I have tested it on Windows x64 using mingw and vcc...

**Comment by PMunch** [comment]
Not quite, if you replace the entire inner loop with `hash(%*{"key2":i})` it doesn't crash. So it seems to be in the combination.

**Comment by PMunch** [comment]
Did some more testing and it's definitely not the json module. Here is an example without the json module entirely:

    import intsets

    iterator `..`[T](s: Slice[T], step:int64 = 1): T {.inline.} =
      var pos: T = int(s.a)
      while pos <= int(s.b):
        yield T(pos)
        pos += step

    var
      cache = initIntSet()
    for i in -8446382337792515718..8473615295523439531..361529552343953:
        var keyEntryHash:int=cast[int](i)
        assert(cache.contains(keyEntryHash)==false,"Key value not unique")
        cache.incl(keyEntryHash)
    echo "Done"

This segfaults before the "Done" statement

**Comment by Araq** [comment]
Both programs work with the new GC.
