### ISSUE TITLE
JSON hash includes order in objects

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#3972]
According to the JSON specification: "An object is an unordered set of name/value pairs. "
This means that the object:

    {
        "key1":"value1",
        "key2":"value2"
    }

is the same as the object:

    {
        "key2":"value2",
        "key1":"value1"
    }

The hash function however, when applied to JSON objects, creates different hashes for those objects while they are technically the same object.

**Comment by def-** [comment]
With the devel branch or 0.13.0?

**Comment by PMunch** [comment]
0.13.0, I asked on IRC if it was fixed on the devel branch but Araq said he didn't think so.

**Comment by def-** [comment]
Right, it can probably happen with devel as well. I see two solutions:

1. Sort all (key,value) pairs and calculate the hash of that, much more expensive
2. Only use a part of the available information, for example just the number of elements in the table, more collisions

**Comment by scriptum** [comment]
@def- What about using symmetric operator for underlying hashes, something like xor?

**Comment by def-** [comment]
I guess that's another way, but then we're not using the `!&` of the hashes module.

**Comment by scriptum** [comment]
```nim
import hashes
template test(underlying_elements) =
  var hc = 0
  for e in underlying_elements:
    hc = hc xor e.hash
  hc = !$ (hc !& underlying_elements.len)
  echo hc

test @[1, 2, 3]
test @[3, 1, 2]
test @[4, 1, 2]
test @["foo", "bar"]
test @["bar", "foo"]
```
Should produce good distribution and less collisions. But hash function for integers could be better.

**Comment by PMunch** [comment]
Well, arrays in JSON are ordered. So all those should hash to different values.. The only good solution I've found so far is to sort they keys of an object (which are always strings) lexicographically and then hash it. This has some severe overhead though as def- mentioned.

**Comment by mirek** [comment]
What about just changing:

```
proc hash*(n: Table[string, JsonNode]): Hash =
  for key, val in n:
    result = result !& hash(key) !& hash(val)
  result = !$result
```

to:

```
proc hash*(n: Table[string, JsonNode]): Hash =
  for key, val in n:
    result = result xor (hash(key) !& hash(val))
  result = !$result
```

?

**Comment by Araq** [comment]
@mirek Exactly, please create a PR.

**Comment by PMunch** [comment]
@Araq created the PR: https://github.com/nim-lang/Nim/pull/4009
