### ISSUE TITLE
Adding echo statement causes "type mismatch" error

### ISSUE THREAD

**Issue by ratfactor** [nim-lang/Nim#3975]
I'm stumped!  I've got the source whittled down to this small example which reproduces my error:

### Does not compile

    proc doStuff() =
        var foo = 1

        proc a(): seq[string] =
            echo foo # <-------- comment me out to compile!
            result = @["hello","world"]

        proc b(s: string) =
            echo s

        proc c() =
            for row in a():
                b(row)

        c()

    doStuff()

Result:

	C:\temp\nim-wtf>nim c -r nested.nim
	Hint: system [Processing]
	Hint: nested [Processing]
	nested.nim(14, 14) Error: type mismatch: got (seq[string])
	but expected one of:
	doStuff.b(s: string)

Expected:

	1
	hello
	world

If you comment out the echo statement in `a()`, it compiles and runs fine.

### 'Un-nested' compiles

This does not occur if the procedures are not nested inside the `doStuff()` proc.  This compiles and gives the expected output when it runs:

    var foo = 1

    proc a(): seq[string] =
        result = @["hello","world"]
        #echo foo

    proc b(s: string) =
        echo s

    proc c() =
        for row in a():
            b(row)

    c()

### Assigning to a var compiles

This also does not occur if you assign the result of `a()` to a variable before using it in the for loop. This also compiles and gives the expected output when it runs:

    proc doStuff() =
        var foo = 1

        proc a(): seq[string] =
            echo foo
            result = @["hello","world"]

        proc b(s: string) =
            echo s

        proc c() =
            var a_results = a()
            for row in a_results:
                b(row)

        c()

    doStuff()

### Nim version

	C:\temp\nim-wtf>nim --version
	Nim Compiler Version 0.13.0 (2016-01-19) [Windows: amd64]
	Copyright (c) 2006-2015 by Andreas Rumpf

	git hash: a121c3f9eb2a348b9d6ae03ffd01aab26a238c30
	active boot switches: -d:release

Am I missing something obvious?

Thanks for the otherwise excellent language. I was really having a great time with Nim until I ran into this.

**Comment by dom96** [comment]
Nice find! Looks like a strange closure bug to me.

**Comment by Araq** [comment]
It's not an LL bug, but your echo changes the calling convention of ``a`` from nimcall to closure. Somehow that's enough to confuse the type checker.

**Comment by ratfactor** [comment]
Ah, yes. Because the echo uses `foo` and therefore forms a closure.  I meant to mention that you can also cause the error by replacing the echo with another simplistic use of `foo`, such as assigning another variable to its value.  The use of echo felt even more benign, so that became my focus. :-)
