### ISSUE TITLE
formatBiggestFloat uses hardcoded buffer size

### ISSUE THREAD

**Issue by benedek93** [nim-lang/Nim#398]
The implementation of formatBiggestFloat in strutils uses a finite and fixed buffer length (80) for its result, but the precision parameter is not checked whether it's too big.

This gives me a segmentation fault for the executable:

```
import strutils
echo formatBiggestFloat(1.0, precision = 200)
```

**Comment by konsumlamm** [comment]
@Araq the snippet
```nim
import std/strutils

var c = 12345678901234e60
echo formatFloat(c,ffDecimal,12)
```
still produces an internal error on latest devel:
```
lib/pure/strutils.nim(2413, 10) Error: internal error: expr: var not init precision_973080453
```
