### ISSUE TITLE
Nim script is not supporting reading from stdin.

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#3983]
As reported here 
http://stackoverflow.com/questions/36103424/how-to-read-from-the-stdin-with-nim-script/36103582 nim 
script is throwing 

> Error: undeclared identifier: 'stdin'

when reading from stdin.

**Comment by Araq** [comment]
Why would anybody want this? "Let's transform the compiler into an interactive program." Why?

**Comment by enthus1ast** [comment]
it would be nice to ask the user
  are you shure [y/n]: 
or
  param1 [foo]: 

this would be very usefull in an interactiv build/bundle process.
And it would be "always there"

**Comment by Araq** [comment]
Let's give Nimble this feature, not Nim.

**Comment by genotrance** [comment]
Nimscript claims to be a standalone scripting language. Reading from stdin seems like a really basic feature. It may be the same VM used by the compiler at compile time but seems fair to allow more capabilities when using it in nimscript mode.

**Comment by genotrance** [comment]
This has been implemented in PR #10292.
