### ISSUE TITLE
Strange UINT handling

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#3985]
Try to compile this code

```
const
  HIGHEST_64BIT_UINT = 0xFFFFFFFFFFFFFFFF'u
  HIGHEST_32BIT_UINT = 0xFFFFFFFF'u

echo($HIGHEST_64BIT_UINT)
echo($HIGHEST_32BIT_UINT)
```

With latest devel compiler i got this
`Error: cannot convert -1 to uint64`

**Comment by dom96** [comment]
Duplicate of #1429?

**Comment by cheatfate** [comment]
I think its one more, not duplicate, because of different error (so maybe one more place to patch).
