### ISSUE TITLE
int and float assignment compatibility badly broken for generics

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#3998]
Ok, I have spent the last 3 days debugging `nim-glm` and trying to figure it out why my OpenGL code just doesn't work. Turns out that the library is not at fault but int and float assignment compatibility in Nim 0.13.0 is quite badly broken. This is especially problematic with OpenGL when you're on 64-bit, so simple "undecorated" float values default to float64, but what you actually want is float32.

Consider the following:

```
type Vec3[T] = array[3, T]

var vg: Vec3[float32] = Vec3([1.0, 2.0, 3.0])

echo "vg[0]: " & $vg[0]  # prints 1.0    OK
echo "vg[1]: " & $vg[1]  # prints 2.0    OK
echo "vg[2]: " & $vg[2]  # prints 3.0    OK
echo ""

var ve: Vec3[float64]
ve = vg     # compiles, this MUST NOT be allowed!

echo "ve[0]: " & $ve[0]  # prints 2.000000473111868       INCORRECT
echo "ve[1]: " & $ve[1]  # prints 1.191169818312094e-307  INCORRECT
echo "ve[2]: " & $ve[2]  # prints 0.0078125               INCORRECT
echo ""

# Note doing the same thing is prohibited when using simple arrays:
var a64: array[3, float64]
var a32: array[3, float32]

#a32 = a64      # does not compile, correct
```

The compiler should have prevented assigning a `Vec3[float32]` to a `Vec3[float64]` variable with an error, as it would do for the simple array case. Silently doing the assignment and messing up the values is the worst possible thing that can happen in numerical code!

Integer generics are similarly broken too:

```
type Vec3[T] = array[3, T]

proc vec3[T](x: T, y: T, z: T): Vec3[T] =
  Vec3([x, y, z])

d12: Vec3[int32] = vec3(1'i8, 2'i8, 3'i8)   # should not compile but does and gives incorrect results

echo  "d12[0]: " & $d12[0]      # prints 197121
echo  "d12[1]: " & $d12[1]      # prints 0
echo  "d12[2]: " & $d12[2]      # prints 0
```

Note that the simple array case works correctly:

```
var a: array[3, int32]
var b: array[3, int64]

#a = b      # Doesn't compile; copying a int64 array into a int32 array is
            # not allowed. That's correct!
```

This was literally driving me a bit crazy that I cannot trust my numeric code anymore, so I have spent the last two days painstakingly mapping out all possible assignment / constructor combinations and marking the ones that are definitely incorrect but compile and some others scenarios that I think should compile  but actually they don't. Anyway, the biggest problem is definitely the ones that _do_ compile but then result in invalid values being assigned.

I have put together a quite extensive test suite that documents my findings of the incorrect behaviour. I know this is tedious and boring, but **please anyone who picks this up, take the time and go through all my examples and carefully consider each case that I have presented**. This is something **very fundamental** to get right in a language and I believe all the invalid cases that I have highlighted should result in compiler errors (and there's lots of them!)

Thanks!

https://github.com/johnnovak/nim-lang-bugs/tree/master/numeric

**Comment by johnnovak** [comment]
Cheers Araq! I'm hoping my examples speak for themselves, but I'm happy to explain further if I haven't made myself clear somewhere perhaps.

**Comment by yglukhov** [comment]
Similar problem in #3319.

**Comment by johnnovak** [comment]
Another simple example why all the above is evil (I've just hit this problem right now):

```
let
  normal: Vec3[GLfloat] = vec3(0.0, 0.0, 1.0)

echo normal[0]    # prints 0.0
echo normal[1]    # prints 0.0
echo normal[2]    # prints 0.0   FALSCH
```

I must do either of these two workarounds to make it work properly:
```
  normal: Vec3[GLfloat] = vec3(GLfloat(0.0), GLfloat(0.0), GLfloat(1.0))
  normal: Vec3[GLfloat] = vec3(0.0'f32, 0.0'f32, 1.0'f32)
```

Very easy to forget and the results are catastrophic...
