### ISSUE TITLE
Compiler segfaults on certain forward declarations

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4003]
The following invalid code containing a forward declaration will result in a compiler crash instead of a compiler error:

```
proc boo(p: proc)

proc quux(p: proc) =
  discard

proc boo(p: proc) =
  discard

# Hint: system [Processing]
# Hint: crash1 [Processing]
# SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Interestingly, a forward declaration _and_ a subsequent proc declaration will result in a crash too!

```
proc boo(p: proc)

proc boo(p: proc) =
  discard

proc quux(p: proc) =
  discard
```

Removing the forward declaration from the above code would make this compile. Also, changing the parameter types from `proc` to `int` or something else would result in correct compiler errors. There are a few more variations on this theme that the compiler handles correctly, please check out the detailed test cases I have put together:

https://github.com/johnnovak/nim-lang-bugs/tree/master/forward-decl

Tested with Nim 0.13.0 on Windows/MinGW-w64 & OSX/clang

**Comment by dom96** [comment]
Thank you for taking the time to put together those test cases! :)

**Comment by mbaulch** [comment]
I don't think your code is invalid. A fix has been proposed (see https://github.com/nim-lang/Nim/pull/4449).
