### ISSUE TITLE
Bad links in docs built by `koch website`

### ISSUE THREAD

**Issue by 0joshuaolson1** [nim-lang/Nim#4006]
After `./koch website`, I can browse the website's documentation offline! But many links, such as those in .../web/upload/learn.html and .../web/upload/documentation.html, have the wrong names and have a superfluous /docs/...html in them.

**Comment by MrMormon** [comment]
https://nim-lang.org/docs/learn.html and https://nim-lang.org/docs/documentation.html still exist in the website too, apparently.

**Comment by narimiran** [comment]
Fixed in the mean time.
