### ISSUE TITLE
``raises`` tag tracking error

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4011]
I wrote a function that must suppress all the exceptions, but I have the problem with tag tracking. Here is the minimal example:

``` nim
proc tryS[T](f: proc(): T): (string,T) {.raises: [].} =
  try:
    result = (nil, f())
  except:
    result = (getCurrentExceptionMsg(), nil)

proc badProc: string =
  raise newException(Exception, "Bad")

proc badProcCall: (string, string) {.raises: [].} =
  tryS do -> auto:
    badProc()
```

The error is:

```
nothrow.nim(10, 46) template/generic instantiation from here
nothrow.nim(7, 33) Error: can raise an unlisted exception: Exception
```

If I add pragma `{.raises: [Exception].}` to `badProc` definition, it changes nothing.

**Comment by Araq** [comment]
Effect tracking is correct and works as per spec (in this case). Reasons are difficult to explain, read the spec please...

Your 'tryS' needs to become a template.

**Comment by andreaferretti** [comment]
@vegansk is a template ok for your use case? I tried to follow the effect system rules but they are indeed complicated - I still cannot see why this should not work. At least, I think the docs could be improved

**Comment by timotheecour** [comment]
example didn't compile anymore due to nil string error; here's a simplified test case:
```
  proc tryS(f: proc()) {.raises: [].} = # can raise an unlisted exception: ref Exception
  # template tryS(f: proc()) = # works
    try: f()
    except: discard
  proc badProc() = raise newException(Exception, "Bad")
  proc badProcCall {.raises: [].} =
    tryS badProc
```

regardless of spec, it is indeed surprising behavior that it gives an error.
At least error is now better since https://github.com/nim-lang/Nim/pull/10582 as it gives instantiation context:

```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0208.nim(60, 30) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0208.nim(58, 5) Error: can raise an unlisted exception: ref Exception
      raise newException(Exception, "Bad")
```

**Comment by krux02** [comment]
As Arq said, you should use a template

```nim
template tryS(f: untyped): untyped  =
  try:
    ("", f())
  except:
    (getCurrentExceptionMsg(), "")

proc badProc: string =
  raise newException(Exception, "Bad")

proc badProcCall: (string, string) {.raises: [].} =
  tryS do -> auto:
    badProc()

echo badProcCall()
```
