### ISSUE TITLE
repr() and sharedtables (shared memory structures)

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#4012]
I have tried to **repr()** on **SharedTable[A, B]** object and got SIGSEGV error.

```
import sharedtables
var a = initSharedTable[int, int]()
echo(repr(a))
```

Error:

```
Traceback (most recent call last)
testshared.nim(4)        testshared
repr.nim(308)            reprAny
repr.nim(248)            reprAux
repr.nim(215)            reprRecord
repr.nim(202)            reprRecordAux
repr.nim(198)            reprRecordAux
repr.nim(255)            reprAux
repr.nim(237)            reprRef
repr.nim(247)            reprAux
repr.nim(175)            reprArray
repr.nim(248)            reprAux
repr.nim(215)            reprRecord
repr.nim(202)            reprRecordAux
repr.nim(198)            reprRecordAux
repr.nim(258)            reprAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

After some investigation i have found a problem:
`KeyValuePairSeq[A, B] = ptr array[10_000_000, KeyValuePair[A, B]]`

**repr()** try ot iterate over **data: KeyValuePairSeq[A, B]** values until it reach 10_000_000 item and cause SIGSEGV when it reach end of allocated shared memory chunk...

Is it possible to patch **repr()** to identify such structures or maybe patch **sharedtables.nim** (and i think many others modules, which using such structure)?

**Comment by Yardanico** [comment]
Still happens.

**Comment by narimiran** [comment]
It seems that this has been fixed, devel now produces:

```
[data = ptr 0x7fb6f9f3a048 --> [...],
counter = 0,
dataLen = 64,
lock = []]
```
