### ISSUE TITLE
Suggestion: strutils add `isEmpty()` proc

### ISSUE THREAD

**Issue by shawnye** [nim-lang/Nim#4019]
As string can be null or "" or "     " ,which we would ignore most of time , I suggest to add `isEmpty()` proc
<pre>
proc isBlank*(val:string):bool {.inline.} =
  return val == nil or val == ""

proc isEmpty*(val:string):bool {.inline.} =
  return val == nil or val.strip() == ""
</pre>
`isNotEmpty()` proc can be implemented by template.

The proc name is inspired from ` Apache Commons Lang's StringUtils`

**Comment by dom96** [comment]
Good idea :)

Can you create a PR to include these? Please document them as well (no need to include ``isNotEmpty()`` as you can just write ``not isEmpty()``)
