### ISSUE TITLE
download page still implies master is default branch

### ISSUE THREAD

**Issue by 0joshuaolson1** [nim-lang/Nim#4022]
But one clones into devel now unless one explicitly switches to master.

http://nim-lang.org/download.html

...at the bottom.

**Comment by dom96** [comment]
Yeah, I don't get why anyone would want to grab ``master`` from Github when they can just as well grab the archived version above.

**Comment by MrMormon** [comment]
My memory may be bad, but less than two weeks ago I [recall using master](http://forum.nim-lang.org/t/2164) from a clone without switching branches.
