### ISSUE TITLE
Overloading and self referencing type together cause compiler to segfault

### ISSUE THREAD

**Issue by nonvirtualthunk** [nim-lang/Nim#4028]
It seems that when a type that references itself is used in an overloaded proc it causes the `sumGeneric` call in sigmatch.nim to enter an infinite loop when used to determine the best match., and eventually segfault. Minimal reproducible example below:

testcase.nim

``` nim
type
   ListNode*[T] = tuple
      next : ref ListNode[T]

proc `==`* [V](a : ref ListNode[V], b : ref ListNode[V]) : bool =
   return false
```

testcase2.nim

``` nim
import testcase

when isMainModule:
   var list : ref ListNode[int]
   echo(list == nil)
```

As far as I can tell, the problem only occurs when these pieces of code are in separate files. If simply adding some sort of guard to `sumGeneric` to break out of a cycle is an acceptable solution to the problem I'd be happy to submit a PR. Adding a `seq[int]` argument that tracks the seen `PType` ids and skips any it has already recursed into seems like the easiest approach to me, but I'm new to both nim and the compiler.

Edit: Looking through issues, saw https://github.com/nim-lang/Nim/issues/4007, if this a similar situation in which the answer is "don't overload ==" then I imagine this becomes a documentation question rather than a code question.

**Comment by Araq** [comment]
Recursive tuples are not supported but the compiler doesn't catch all cases where they might occur.

**Comment by nonvirtualthunk** [comment]
Thanks Araq, I hadn't realized that was an unsupported use case. I've added https://github.com/nim-lang/Nim/pull/4056, that uses the same infinite loop breaking approach as `bothMetaCounter` in that same file to detect and raise an error message.

**Comment by dumjyl** [comment]
This gives a proper error message: `Error: illegal recursion in type 'ListNode'`

**Comment by Araq** [comment]
Indeed.
