### ISSUE TITLE
passing "proc `,`()" to nim check causes an infinite loop

### ISSUE THREAD

**Issue by adamatom** [nim-lang/Nim#4036]
Given a file with contents

``proc `,`() = discard``

nim check outputs "Error: identifier expected, but found ','" in an infinite loop.

I admit that I am a helpless noob and I now know that the comma cant be used as an infix operator, but maybe just one error message would suffice :stuck_out_tongue:

**Comment by dom96** [comment]
That's a cool bug. Thank you for the report :)

**Comment by adamatom** [comment]
Nim Compiler Version 0.13.0 (2016-03-21) [Linux: amd64]

Guess it has been fixed already? Sorry about the bogus report then.

**Comment by adamatom** [comment]
I am still getting this error on what I just checked out on the devel branch.

Here is what I just did:

git clone git@github.com:nim-lang/Nim.git
cd Nim
git clone --depth 1 https://github.com/nim-lang/csources
cd csources/
./build.sh
../bin/nim check bad_oper.nim
Hint: system [Processing]
Hint: bad_proc [Processing]
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
bad_proc.nim(1, 7) Error: identifier expected, but found ','
...

The version string generated by this nim binary that I just build:
./bin/nim --version
Nim Compiler Version 0.13.0 (2016-01-18) [Linux: amd64]

I'm running Debian unstable, which has gcc: gcc (Debian 5.3.1-13) 5.3.1 20160323

**Comment by dom96** [comment]
oh. My bad, I was doing `nim c` not `nim check` :)
