### ISSUE TITLE
SIGSEV with proc of var result returning nothing

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#4042]
Test

``` Nim
proc foo: var int = discard
let f = foo()
```

Result: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

I would expect the compiler to be able to catch situations like this (or a clearer error message).

---

``` Nim
> nim -v
Nim Compiler Version 0.13.1 (2016-04-04) [Windows: i386]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: 147961d0069ed434796eed9ceacf52914087f789
active boot switches: -d:release
```

**Comment by Araq** [comment]
See also bug #124

**Comment by Araq** [comment]
Now produces:


temp.nim(2, 21) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future.
