### ISSUE TITLE
OpenBSD compilation with "--threads:on" causes an error

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#4046]
When compiling simple source with "nim c --threads:on test.nim":
`echo("Hello World!")`
on [OpenBSD 5.8 GENERIC#1170 amd64] i got this errors:

```
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c: In function 'atomicinc_16601':
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c:5794: error: '__ATOMIC_RELAXED' undeclared (first use in this function)
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c:5794: error: (Each undeclared identifier is reported only once
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c:5794: error: for each function it appears in.)
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c: In function 'atomicdec_16606':
/home/cheatfate/projects/timerfd/nimcache/stdlib_system.c:5801: error: '__ATOMIC_RELAXED' undeclared (first use in this function)
Error: execution of an external program failed: 'gcc -c  -w -pthread  -I/home/cheatfate/Nim/lib -o /home/cheatfate/projects/timerfd/nimcache/stdlib_system.o /home/cheatfate/projects/timerfd/nimcache/stdlib_system.c'
```

**Comment by Leu-Gim** [comment]
The same on Windows, with MinGW.

**Comment by Leu-Gim** [comment]
Solved with upgrading MinGW to 4.9.3.

**Comment by cheatfate** [comment]
To solve this error i have installed GCC 4.8.2 from openbsd packages and modified config/nim.cfg a little bit:
```
@if openbsd:
  cc = gcc
  gcc.exe = "egcc"
@end
```

**Comment by Varriount** [comment]
I'm curious, what does the 'e' stand for?

**Comment by cheatfate** [comment]
@Varriount, OpenBSD does not replacing your default compiler GCC 4.2.1 when you installing new one (4.8.2 in my case) it just renames it to egcc and both compilers are allowed to use.

**Comment by Araq** [comment]
Is this still an issue?

**Comment by cheatfate** [comment]
Yep, it still an issue, OpenBSD still uses gcc 4.2.1 by default

**Comment by jrfondren** [comment]
OpenBSD also can't get past `./koch tools` due to this issue. There's a newer gcc in OpenBSD packages that gets installed as egcc, so I tried this:
```
$ sh build.sh
$ nim c koch
$ pkg_add gcc-4.9.4.p12
$ perl -i -pe 's/(compilerExe: ")gcc/\1egcc/' compiler/extccomp.nim
$ ./koch boot
```
this got well past complaints about __ATOMIC_RELAXED , but failed apparently because the versioned .tar.xz packages don't contain everything needed for a bootstrap build.

```
nimblepkg/options.nim(128, 14) Warning: Couldn't determine GIT hash: fatal: not a git repository ...
...
nimplepkg/nimscriptsupport.nim(8, 11) Error: cannot open file: compiler/ast
```

**Comment by ghost** [comment]
Is this still an issue? Also ping @euantorano  :)

**Comment by euantorano** [comment]
I doubt it, as the compiler in base is clang now, but I’ll double check this morning and really. We definitely get past `koch boot`.

**Comment by euantorano** [comment]
This seems to be solved. Steps to test (covering all of the above mentioned issues - testing on `OpenBSD 6.7 GENERIC#179 amd64)`:

```
> pkg_add xz
> ftp https://nim-lang.org/download/nim-1.2.2.tar.xz
> xzcat nim-1.2.2.tar.xz | tar xvf -
> cd nim-1.2.2
> CC=cc sh build.sh
> perl -i -pe 's/@if macosx or freebsd:/@if macosx or freebsd or openbsd:/igs' config/nim.cfg # use clang as backend, this is in devel but not the release package
> bin/nim c koch
> ./koch boot
> ./koch tools
> echo 'echo "Hello World"' > test_threads.nim
> bin/nim c -r --threads:on test_threads.nim
```

This issue can be closed.
