### ISSUE TITLE
Segfault if shallowCopy string or seq with default GC & v2

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#4053]
The following test file segfault if using default **gc** or newer **v2**, while **markAndSweep** doesn't crash.
It also crash if **const** is a **seq** of any type. Making the **const** on global scope also crash.
Using **var** to declare variable doesn't crash.

```
Traceback (most recent call last)
debug.nim(83)     debug
debug.nim(69)     newNode
gc2.nim(210)             asgnRefNoCycle
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
test file:
```nim

type
    Node = ref object of RootObj
        header: string

proc newNode*(header: string): Node =
    new(result)
    shallowCopy(result.header, header)
#~    result.header = header # no error

proc `$`(s: Node): string =
    result = "Node(" & s.header & ")"

proc main() =
    when defined(cst):
        const s = "Main"
        echo(newNode(s)) # same as newNode("Main")

    else:
        let s = "Main"
        echo(newNode(s))

main()
```

**Comment by Araq** [comment]
``shallowCopy`` is declared as unsafe for this reason. Sorry if that was the cause of the crashes you experienced.

**Comment by Parashurama** [comment]
So .. won't fix, huh!
It is actually a crash unrelated  to issue https://github.com/nim-lang/Nim/issues/3808
I think I had already read about it in the docs then promptly forgot.  my bad.
Perhaps we could clarify what exactly is unsafe in the docs.
ex: shallowCopy-ing  const variables.

But it is actually an interesting new lead for tracking down what is causing the crashes in https://github.com/nim-lang/Nim/issues/3808.

PS: should we close this issue?
