### ISSUE TITLE
Bad 'var' placement in proc definition gives unhelpful "')' expected" error message

### ISSUE THREAD

**Issue by 0joshuaolson1** [nim-lang/Nim#4067]
On making error messages more helpful, I made a `var` placement mistake while learning Nim:

`proc doSomethingToP(var p: int)...`

As a complete newbie, the error message could have pointed out:

`var p: int` versus `proc doSomethingToP(p: var int)`

Related [discussion](http://forum.nim-lang.org/t/2190) on reasoning for this grammar.

**Comment by Araq** [comment]
This got a specialized parser error message.
