### ISSUE TITLE
destructor is not called on garbage collect

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#408]
"kill Blob" is only shown once, but should be shown twice

``` nimrod

type
  TBlob = object
    data: Pointer
  TFoo = ref object
    blob: TBlob

proc destruct(o: var TBlob) {.destructor.} =
  echo "kill Blob"
  dealloc o.data

proc newBlob(size: int): TBlob =
  result.data = alloc0(size)


proc test1() =
  var blob = newBlob(10)
  echo "bye bye"

proc test2() =
  var foo = TFoo(blob: newBlob(100))
  echo "bye bye"
  reset(foo)

echo "test1"
test1()
echo "test2"
test2()

GC_fullCollect()

```

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x321ab06da32d2428f117c5abf9ce9800eaaa3940e5eda4c5e53bb22c1807983a](https://etherscan.io/tx/0x321ab06da32d2428f117c5abf9ce9800eaaa3940e5eda4c5e53bb22c1807983a)

**Comment by andreaferretti** [comment]
The following **does** work as expected, when compiled with `nim c --newruntime`:

```nim
type
  TBlob = object
    data: pointer
  TFoo = ref object
    blob: TBlob

proc `=destroy`(o: var TBlob) =
  echo "kill Blob"
  dealloc o.data

proc newBlob(size: int): TBlob =
  result.data = alloc0(size)


proc test1() =
  var blob = newBlob(10)
  echo "bye bye"

proc test2() =
  var foo = TFoo(blob: newBlob(100))
  echo "bye bye"
  reset(foo)

echo "test1"
test1()
echo "test2"
test2()

GC_fullCollect()
```

**Comment by zah** [comment]
The code is old, but the principle problem here is that the destructors are not automatically registered as finalizers. There two shouldn't be separate things in Nim. Setting up a finalizer should be done by defining a destructor for the type.

**Comment by andreaferretti** [comment]
Agreed, but what I was mentioning is that the destructor for `TBlob` **is** called when collecting `TFoo`

**Comment by AdrianV** [comment]
Since `{.destructor.}` is removed and the newruntime in the making, we can close this issue - opinions ?

**Comment by Araq** [comment]
Please leave it open, the new runtime will work with the GC and its finalizer support.

**Comment by data-man** [comment]
With  ```=destroy``` now works as expected without ```--newruntime```.

**Comment by Araq** [comment]
This works now afaict.
