### ISSUE TITLE
Make bindSym more flexible

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4087]
For now, ``bindSym`` searches for symbols that was defined before the macro definition that uses it. For example, this is not compiles with ``undeclared identifier`` error:
```nim
import macros

macro mtest: expr =
  result = bindSym("test").len.newIntLitNode

proc test(s: string): string = s

assert mtest() == 1
```

Why we need it to work? For example, I want to create compile time JSON serializer librarty (named ``jsonner`` for example) with the ability of it's customization via functions. Here is the usage example of it:
```nim
import fp.option, json, jsonner
type
  Data = object
    id: Option[int]
    name: string

# Create new entity
let d = Data(id: int.none, name: "Hello, world!")
# And serialize it
let j = d.toJson
```

``jsonner.toJson`` is the macro that can generate expression of ``JsonNode`` type. It can serialize standard types, sequences, tuples and objects. But I want to serialize ``id`` field in a custom way: if option is none, then result must be null, else it must be value of int. So, in ``toJson``, I want to find out, is there a function ``proc toJsonImpl[T](v: Option[T]): JsonNode`` defined. But I can't, because ``bindSym`` can't find it. ``bindSym("toJsonImpl", brForceOpen)`` fails at compile time in module ``jsonner``. I can implement this proc and then do ``import jsonner``, but what if I need to use ``toJson`` in ``toJsonImpl`` like this:
```nim
# Declare custom serializer
proc toJsonImpl[T](v: Option[T]): JsonNode =
  # Fails - jsonner will be imported later
  result = v.map(d => d.toJson).getOrElse(newJNull)

# Import ``toJson`` macro
import jsonner
```
I can't do that because ``jsonner.toJson`` is not defined.

It will be awesome, if ``BindSymRule`` will contain one more flag that allows searching for symbols in the place of macro invocation. Or maybe there is another solution for this problem?

**Comment by Araq** [comment]
So don't use bindSym when you cannot actually *bind* anything? How about using unresolved identifiers instead?

**Comment by yglukhov** [comment]
@vegansk, why not just define
```
proc `%`[T](o: Option[T]): JsonNode = blabla
```
in conjuction with #4075 it should work pretty well i think

**Comment by vegansk** [comment]
@Araq, it works with identifiers. Thanks!
