### ISSUE TITLE
Case statements for typedescs

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#4095]
```nim
proc p1[T:SomeNumber](x: T): T =
    case T
    of SomeReal:
        result = 0.5
    of SomeInteger:
        result = 1

proc p2[T](x: T): T =
    case T
    of SomeReal:
        result = 0.5
    of SomeInteger:
        result = 1
    else:
        discard
```

**Comment by def-** [comment]
What you can do right now is this:
```nim
proc p1[T:SomeNumber](x: T): T =
  when T is SomeReal:
    result = 0.5
  elif T is SomeInteger:
    result = 1

echo p1(10)
echo p1(10.0)
```

**Comment by Varriount** [comment]
I don't really see the need here. Case statements are primarily meant for handling ordinal types, which is why they enforce exhaustiveness checking. We already have the "when" systems to handle compile-time conditions.

**Comment by ephja** [comment]
The purpose would be exhaustiveness in this case too, with or without an 'else' branch depending on the constraint.
