### ISSUE TITLE
combination of tuple assignment and a block with a var section creates wrong c code.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#4096]
this is my test code:

```
discard """
  msg: '''21
Hello World
21
Hello World'''
"""

let (a,b) = (block:
  var
    a = 21
    b = "Hello World"
  (a, b)
)

echo a
echo b

proc main() =
  let (a,b) = (block:
    var
      a = 21
      b = "Hello World"
    (a, b)
  )

  echo a
  echo b

main()
```

This is the output of the compilation:

```
$ nim c block_assign.nim
Hint: system [Processing]
Hint: block_assign [Processing]
CC: block_assign
Error: execution of an external compiler program 'gcc -c  -w  -I/home/arne/proj/nim/Nim/lib -o /home/arne/proj/nim/break/nimcache/block_assign.o /home/arne/proj/nim/break/nimcache/block_assign.c' failed with exit code: 256

/home/arne/proj/nim/break/nimcache/block_assign.c: In Funktion »main_92014«:
/home/arne/proj/nim/break/nimcache/block_assign.c:283:6: Fehler: »LOC2« nicht deklariert (erste Benutzung in dieser Funktion)
  a = LOC2.Field0;
      ^
/home/arne/proj/nim/break/nimcache/block_assign.c:283:6: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/home/arne/proj/nim/break/nimcache/block_assign.c: In Funktion »block_assignInit000«:
/home/arne/proj/nim/break/nimcache/block_assign.c:354:12: Fehler: »LOC3« nicht deklariert (erste Benutzung in dieser Funktion)
  a_92007 = LOC3.Field0;
```

and this is the part of the generated c code:

```
N_NIMCALL(void, main_92014)(void) {
    NI a;
    NimStringDesc* b;
    NimStringDesc* LOC3;
    nimfr("main", "block_assign.nim")
    nimln(19, "block_assign.nim");
    {
        NI a;
        NimStringDesc* b;
        TY92006 LOC2;
        nimln(21, "block_assign.nim");
        a = ((NI) 21);
        nimln(22, "block_assign.nim");
        b = copyString(((NimStringDesc*) &TMP140));
        memset((void*)(&LOC2), 0, sizeof(LOC2));
        LOC2.Field0 = a;
        LOC2.Field1 = copyString(b);
    }
    a = 0;
    a = LOC2.Field0;
    b = 0;
    b = LOC2.Field1;
    nimln(26, "block_assign.nim");
    LOC3 = 0;
    LOC3 = nimIntToStr(a);
    printf("%s\012", LOC3? (LOC3)->data:"nil");
    fflush(stdout);
    nimln(27, "block_assign.nim");
    printf("%s\012", b? (b)->data:"nil");
    fflush(stdout);
    popFrame();
}
```

The problem is, that `TY92006 LOC2;` needs to be moved before the start of the block. If I do it manually, the program will compile nicely.

**Comment by Araq** [comment]
That's a known long standing bug. Originally we moved all locals to the top level function block avoiding these problems altogether but when generating C++ that's just not feasible anymore. Fixing this requires a complex analysis of wether locals "escape" their current block. Yay.

**Comment by krux02** [comment]
A block has only one value that escapes the block, and that is the result of the last experssion in the block. I am thinking about a solution that gives the result of a block a special name, something like this:

    N_NIMCALL(void, main_92014)(void) {
        NI a;
        NimStringDesc* b;
        NimStringDesc* LOC3;
        nimfr("main", "block_assign.nim")
        nimln(19, "block_assign.nim");
        {
            TY92006 result;
            {
                NI a;
                NimStringDesc* b;
                nimln(21, "block_assign.nim");
                a = ((NI) 21);
                nimln(22, "block_assign.nim");
                b = copyString(((NimStringDesc*) &TMP140));
                memset((void*)(&LOC2), 0, sizeof(LOC2));
                result.Field0 = a;
                result.Field1 = copyString(b);
            }
            a = 0;
            a = result.Field0;
            b = 0;
            b = result.Field1;
        }
        nimln(26, "block_assign.nim");
        LOC3 = 0;
        LOC3 = nimIntToStr(a);
        printf("%s\012", LOC3? (LOC3)->data:"nil");
        fflush(stdout);
        nimln(27, "block_assign.nim");
        printf("%s\012", b? (b)->data:"nil");
        fflush(stdout);
        popFrame();
    }

**Comment by krux02** [comment]
I just tested this code. It works in current version.
