### ISSUE TITLE
Funky CTRL-C shutdown behaviour

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4103]
If you try to stop a console program with CTRL-C on Windows, sometimes it gets stopped correctly and the following gets printed:

```
Traceback (most recent call last)
SIGINT: Interrupted by Ctrl-C.
```

But any of the following can also happen:
- The program crashes (and stops) and the "xyz not responsing" dialog gets shown.
- The program stops immediately but nothing gets printed to the console.
- The program hangs for a few seconds, then stops, but nothing gets printed to the console.

Unfortunately, the crash is the most likely to happen.

Tested with a simple single threaded program with the dev version with the default CTRL-C handler.

**Comment by johnnovak** [comment]
This is actually a duplicate of https://github.com/nim-lang/Nim/issues/4057

**Comment by Araq** [comment]
And what can we do to prevent this? Nim just uses the C compiler's signals implementation.

**Comment by johnnovak** [comment]
I'm not quite sure. I'm using threads in my Nim program when I see this happening. Are you implying that I should somehow write a Ctrl-C hook or something that should do some kind of cleanup to prevent the crash? I guess I'm confused by this because it's only happening on Windows, and only sometimes.

**Comment by Araq** [comment]
I think Windows runs the signal handler in its own thread causing race conditions when we access the stack information for the tracebacks. We can workaround this issue.

https://blogs.msdn.microsoft.com/shrib/2008/05/23/signals-on-windows/

**Comment by johnnovak** [comment]
Yep, I guess some workaround for Windows would be nice to prevent the crashes.

**Comment by genotrance** [comment]
Documented this in #4057 as well, but simple workaround on Windows for the near-term. You need to build with `--threads:on` and `--tlsEmulation:off` for this to work.

```nim
proc handler() {.noconv.} =
    setupForeignThreadGc()
    quit(1)
setControlCHook(handler)
```

**Comment by johnnovak** [comment]
Cheers @genotrance, that's handy!

**Comment by Araq** [comment]
Duplicate of #4057.
