### ISSUE TITLE
Forward declaration of generic procs or iterators doesn't work

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4104]
In the sample below `notGenericPrint` part compiles fine, but the generic print fails because of the invocation in the middle between declaration and implementation. Moving `print 42` line below the implementation fixes the error.

``` nim
proc notGenericPrint(val: int)
notGenericPrint 42
proc notGenericPrint(val: int) =
  echo val

proc print[T](t: T) # Error: implementation of 'print.print(t: int)' expected
print 42 # moving this line after the implementation fixes the error,
         # but such behaviour makes forward declaration pointless
proc print[T](t: T) =
  echo t
```

**Comment by sevalsixarci** [comment]
Hi, forward iterator does not work on nim 2.2.2:

Code:
```nim
iterator i1(): int

iterator i1(): int =
  yield 1
  yield 2
  
  
when isMainModule:
  for i in i1():
    echo i
```

```txt
fwdit.nim(1, 1) Error: implementation of 'i1' expected
```

Code on playground: https://play.nim-lang.org/#pasty=ntpXIYVr

**Comment by Araq** [comment]
You cannot foward declare an iterator as the compiler must be able to inline it.

**Comment by sevalsixarci** [comment]
My bad, I got confused because I was using closure too, then eliminated. Thx for feedback, I was being too chaotic, I resolved with a more linear and clean approach.
