### ISSUE TITLE
Pointer dereferencing issue when the pointer is an element of a tuple

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4105]
Dereferencing should work in this case:

```
type
  CommandChannel = Channel[string]

proc doWork(t: tuple[cmd: ptr CommandChannel, workerId: int]) {.thread.} =
  let chan = t.cmd[]
  chan.open()
```

...but it does not:
```
# ptr.nim(9, 5) Error: type mismatch: got (CommandChannel)
# but expected one of:
# system.open(f: var File, filehandle: FileHandle, mode: FileMode)
# system.open(c: var Channel[open.TMsg])
# system.open(f: var File, filename: string, mode: FileMode, bufSize: int)
# system.open(filename: string, mode: FileMode, bufSize: int)
```

Note that `t.cmd[].open()` works otherwise fine.

Looks like the tuple is the issue, a similar dereferencing pattern passes compilation in a simpler scenario:
```
var
  chan: CommandChannel
  chanPtr = chan.addr
  chanDeref = chanPtr[]

chanDeref.open()
```

Arrays are OK too (obviously, this would crash at runtime):

```
var
  channels: array[10, ptr CommandChannel]
  chanPtr = channels[3]
  chanDeref = chanPtr[

chanDeref.open()
```

**Comment by flyx** [comment]
Take a closer look:

```nim
system.open(c: var Channel[open.TMsg])
```

It says it needs a *var* Channel. But your channel is:

```nim
let chan = t.cmd[]
```

Change `let` to `var` to make it work.

**Comment by johnnovak** [comment]
Thanks, that did the trick for compiling the thing. Sadly, when storing the channel in a var, the whole thing breaks at runtime... I'll close this and raise another issue.
