### ISSUE TITLE
Nim tries to assign to m_type for .importc .inheritable objects

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4108]
I use .importc + .inheritable hack when importing plain C++ structs to get zero-mem initialization behaviour from Nim (it doesn't do that for .importcpp objects due to vtables that objects may contain). The structs I'm importing sometimes expand each other, hence the need in `inheritable` pragma. I guess it makes sense for Nim to never worry about `m_type` for imported types.

Sample:
```nim
{.emit:"""/*TYPESECTION*/
typedef struct {
float x;
float y;
} Vector2D;
""".}

type Vector2D {.importc, nodecl, bycopy, inheritable.} = object
  x: cfloat
  y: cfloat

const zeroVector = Vector2D(x: 0.0, y: 0.0)
let vector = zeroVector # Nim zeroes `vector` mem here, then tries to set m_type
```

**Comment by Araq** [comment]
You need to use ``.pure, inheritable`` to get inheritance without any m_type field.
