### ISSUE TITLE
Nim does not compile simple example

### ISSUE THREAD

**Issue by JeromSar** [nim-lang/Nim#4111]
###### Environment
Windows 7 x64, Nim installed from precompiled binary with MingW enabled, PATH setup
```
$ nim --version
Nim Compiler Version 0.13.0 (2016-01-19) [Windows: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: a121c3f9eb2a348b9d6ae03ffd01aab26a238c30
active boot switches: -d:release
```
```
$ gcc --version
gcc.exe (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Nim does not compile the example from the tutorial:
```

```nim
echo("What's your name? ")
var name: string = readLine(stdin)
echo("Hi, ", name, "!")
```

![](https://www.screenshottr.us/v/ce9ae5f06e73a92e7819b49983df8bfd/4ef4ac8bca43ad80b73fa49fee2de1e0.png)

Same problem occurs when running through cmd.exe

**Comment by def-** [comment]
The error message, which can't be read because somehow 2 messages overlap each other, indicates that your gcc version and nim version don't agree on 32bit or 64bit. Both need to be either 32bit or 64bit.

**Comment by JeromSar** [comment]
@def- Thanks for the quick reply. Seems you were right. I managed to get Nim working by moving all the new PATH entries to the front.

However, doesn't it make more sense that Nim should automatically detect the appropriate GCC? If you're installing MingW with Nim, doesn't it seem logical that Nim defaults to using that, instead of whatever is in the PATH variable? 

Either way, my issue's solved. Thanks for the help.
