### ISSUE TITLE
capture of openArray in closure breaks

### ISSUE THREAD

**Issue by shaunc** [nim-lang/Nim#4112]
The following works:

```
proc argsort(a : seq[int]) : seq[int] =
  result = toSeq(0..a.len - 1)
  proc compare(i, j: int) : int {.closure.} = cmp(a[i], a[j])
  sort(result, compare)
```

However, the following variant fails:

```
proc argsort(a : openArray[int]) : seq[int] =
  result = toSeq(0..a.len - 1)
  proc compare(i, j: int) : int {.closure.} = cmp(a[i], a[j])
  sort(result, compare)
```

with:

```
findcut.nim(26, 51) Error: illegal capture 'a'
```

Seems like a bug? Is there a workaround?

**UPDATE**

Here is a workaround that works:

```
proc argsort[T](a : T) : seq[int] =
  result = toSeq(0..a.len - 1)
  proc compare(i, j: int) : int {.closure.} = cmp(a[i], a[j])
  sort(result, compare)
```

**Comment by Araq** [comment]
It's not a bug. ``openarray`` is a (pointer, length) pair where the pointer could point to the stack which you cannot capture for memory safety reasons. We can remove the restriction by internally capturing a copy that we put on the heap, but I'm not sure it's wise.

**Comment by shaunc** [comment]
hmm... I can see that, but it seems to work for both seq and array. If this were unwise shouldn't it not do that either? Or is there some reason its easier in those cases?

**Comment by Araq** [comment]
Internally it's easier since we cannot copy openarrays while seqs and arrays can be copied.
