### ISSUE TITLE
Json locale portability.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#4117]
Exporting JSON data from locale en_US and loading it in locale fr_FR mess-up completely floating point data.
It is not an issue restricted to Nim but rather the strtod implementation that JSON depends on which is locale-dependent.

Also Nim JSON module exports data in a locale-independent manner but loads according to the current locale which amount to the same issue.

Here is how to reproduce the issue.
use a locale fr_FR or fr_CA (or any other with a different decimal character)
```nim

    let data = %* {"a": 12.1458, "b": 7.6623, "c": 1.333, "d": 2.652}
    echo data.pretty # works okay
    echo data.pretty.parseJson().pretty # only loads integer part of float
```

Some workaround is to use (on POSIX; don't know about others): setlocale(LC_NUMERIC, "C") 
before loading JSON data and reset current locale once done, but that is far from ideal.

I think our best option is to use a locale independent strtod implementation (at least for JSON and maybe other parsers) 
I am quite willing to port the code from the [ruby implementation](http://stackoverflow.com/questions/1994658/locale-independent-strtod-implementation) to Nim if needed. (and write tests, obviously )

**Comment by Araq** [comment]
Well it's not easy to reproduce this and looking at the stdlib I cannot see how this can be caused at all, all the necessary workarounds are in place.

**Comment by Parashurama** [comment]
I managed to make a test file reproducing the issue.
```nim

import posix
import json
import strutils

proc setCurrentLocale*(category: cint, locale: string) {.inline.} =
    if setlocale(category, locale).isNil:
        raise newException(ValueError, "setlocale: invalid locale: '" & locale & "'and category: " & $category)


# implicit calling of 'system/sysstr/getDecimalPoint' to permanently initialize decimal point as '.'
# for example inside module but outside of any functions.
echo parseFloat("1.99") # print 1.99

proc main() =
    # change locale inside main setting decimal point as ','
    setCurrentLocale(LC_ALL, "") # Set all to current locale

    # Can be worked around with this instead but not ideal.
    # setCurrentLocale(LC_MESSAGES, "") # Set gettext lang to current locale
    # setCurrentLocale(LC_CTYPE, "") # Set string lang to current locale

    echo parseFloat("1.99") # prints 1.0

    let data = %* {"a": 12.1458, "b": 7.6623, "c": 1.333, "d": 2.652}
    echo data.pretty # works okay
    echo data.pretty.parseJson().pretty # only loads integer part of float

main()

```

**Comment by dom96** [comment]
Can't reproduce on Mac OS X, Linux-only? or maybe it's locale-dependent somehow?

**Comment by Parashurama** [comment]
I think so too, my locale is fr_FR, but bug is also present in fr_CA.
Just to check, I updated to latest devel, but same result.

Said plainly, the issue is that decimal point character is set the first time parseFloat & co are used and doesn't care if locale LC_NUMERIC is changed later on.
I don't have any OS X to test on his bug, only various flavor of linux. (same result)

I looked at the code in 'system/sysstr/getDecimalPoint' but did not find an easy fix since we can't very well check locale LC_NUMERIC each time a float is parsed. nimParseBiggestFloat already does a copy each time a float is parsed and thats expensive enough.

**Comment by Araq** [comment]
Ok, but we can get rid of getDecimalPoint I think. In practice only '.' or ',' are used throughout the world and we can replace ',' by '.' unconditionally.

**Comment by Araq** [comment]
> I am quite willing to port the code from the ruby implementation to Nim if needed. (and write tests, obviously )

Oh that's a wonderful solution too. 👍

**Comment by Parashurama** [comment]
Ok, do we support hexadecimal floats?  It seems pretty useless, except maybe for very specific uses. (I can't think of any)
Would it replace parseFloat? It would then means that floats are always parsed  in a locale independent manner.
I see a useful proc like this, with **endp**, position of last char parsed (-1 if error)
Alternatively we throw an exception (not my preference)

```nim
proc str2_float(s: string; endp: var int): float
```


Also maybe parse within bounds to avoid slicing strings.

**Comment by Araq** [comment]
> Ok, do we support hexadecimal floats?

Not officially, no.

> Would it replace parseFloat? It would then means that floats are always parsed in a locale independent manner.

Exactly, that was the intention from the beginning. ;-)

> ... Alternatively we throw an exception (not my preference) ...

Just patch the nimParse stuff in system/sysstr.nim and call it a day, no need to design new interfaces.

**Comment by Parashurama** [comment]
Partial update: I already have some code that is working quite well, but the hard part is the corner cases.
Do we settle for a good enough parsing for corner cases (usually within one ulp of original value, sometime more), stick to the standard strtod algorithm (somewhat complex), or try to copy cpython implementation which seems even better, but obviously very complex.

 [see cpython impl](https://github.com/python/cpython/blob/master/Python/dtoa.c) (Use Bigint, and various other tricks)
[see pure python impl](https://github.com/python/cpython/blob/master/Lib/test/test_strtod.py)

**Comment by Araq** [comment]
> EDIT: btw does Nim support platform without 64bits integers? Parsing double does require int64 or it becomes significantly more complex to implement. (but not impossible)

Plenty of embedded devices but I doubt these can deal with FP properly anyway. ;-) I say it's safe to ignore this problem for now.

> Do we settle for a good enough parsing for corner cases (usually within one ulp of original value, sometime more), stick to the standard strtod algorithm (somewhat complex), or try to copy cpython implementation which seems even better, but obviously very complex.

Dependency on bigint is a big no-no, and I think standard strtod algorithm is the way to go but I don't mind other solutions really.
