### ISSUE TITLE
Body ignored in asynchttpserver for anything but POST requests

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4134]
It seems that `asynchttpserver` only parses the body in the presence of POST requests. Other methods do not receive the body at all - nor there is a way (as far as I can tell) to force parsing on demand.

According to [these](http://stackoverflow.com/questions/5905916/payloads-of-http-request-methods) [discussions](http://stackoverflow.com/questions/16339198/which-http-methods-require-a-body) and the links therein, the only method that explicitly forbids the presence of a body is TRACE. In any case, it certainly often needed at least for PUT and PATCH requests, which are meant to update a resource.

An example of program failing is

```nim
import asyncdispatch, asynchttpserver

proc handler(req: Request) {.async.} =
  await req.respond(Http200, "You sent: " & req.body & "\n")

let server = newAsyncHttpServer()

waitFor server.serve(Port(8080), handler)
```

With Curl, we can check

```
$ curl -XPOST --data hello http://localhost:8080/
You sent: hello
$ curl -XPUT --data hello http://localhost:8080/
You sent:
$ curl -XPATCH --data hello http://localhost:8080/
You sent:
```

It seems that the issue lies [here](https://github.com/nim-lang/Nim/blob/master/lib/pure/asynchttpserver.nim#L212) where there is an explicit check for the POST method. I think that the right course of action would be to read the Content-Length header (with a default of 0 is missing) and then read that many bytes into the body, whatever the method is (possibly with an assertion for TRACE).

**Comment by andreaferretti** [comment]
I could fix it using the fact that the request has a reference to the client, so I can read the body on demand, but I still think this is a bug. Alternatively, one could offer a method to read the body lazily, and document this behaviour

**Comment by andreaferretti** [comment]
I think https://github.com/nim-lang/Nim/issues/4221 is a duplicate of this. If so, there is a PR to fix the issue

**Comment by dom96** [comment]
Indeed, should be fixed now!
