### ISSUE TITLE
template/macro instantiation too nested

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4138]
Not sure if this is a bug or working as expected. Can be reproduced with:

    git clone https://github.com/flyx/NimYAML.git --branch variant-objects
    cd NimYAML
    nim c test1

(I will not update this branch so that this issue will not get outdated until closed)

**Comment by flyx** [comment]
I figured it out, it was an error in my template code. The error message is misleading, but it's not a Nim bug.

**Comment by dom96** [comment]
What was the error?

**Comment by flyx** [comment]
Error was at this line:

    var uri = when compiles(yamlTag(T)): yamlTag(T) else:
        "!nim:custom:" & (typetraits.name(type(T)))

`yamlTag(T)` returns a TagId while the other option returns a `string`.
