### ISSUE TITLE
JS backend doesn't copy 'object' when adding to 'seq'

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4139]
``` nim
type
  Test = object
    x, y: int

proc onLoad() {.exportc.} =
  var test: seq[Test] = @[]
  var foo = Test(x: 0, y: 0)
  test.add(foo)
  foo.x = 5
  echo(test[0]) # Gives (x: 5, y: 0) for JS backend, should be (x: 0, y: 0).
```

You can test this easily using this html file:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Test</title>
    <script type="text/javascript" src="test.js"></script>
  </head>
  <body onload="onLoad();" style="margin: 0; overflow: hidden;">
  </body>
</html>
```

Compile using `nim js -o:test.js file.nim`.

**Comment by philip-wernersbach** [comment]
Can confirm that this happens on 0.16.0 as well. This issue blocks porting existing Nim code to the JS backend, as code that expects copy semantics gets reference semantics at runtime (like the example).

**Comment by dom96** [comment]
Yeah, as a workaround you can explicitly create new instances of the object you are adding to a seq. This sucks but it does work (I had to do that in my project).

**Comment by dom96** [comment]
That said, fixing this bug shouldn't be too difficult. If you have some time please do have a look at it.

**Comment by philip-wernersbach** [comment]
The workaround does work, but it's not obvious how to do it in some cases. For instance, when adding sets to seqs, simply creating a new set in place of the old one does not work. For example:

```
var foo = {'a'}
var bar = seq[set[char]](@[])

bar.add(foo)

foo = {}

echo $bar # prints "@[{}]"
```

The workaround for a set would be:

```
var foo = {'a'}
var bar = seq[set[char]](@[])

bar.add(set[char]({}) + foo) # Adding the empty set to foo creates a new, anonymously referenced set

foo = {}

echo $bar # prints "@[{a}]"
```

If I get some time I'll take a look at this, but I don't have compiler experience, so I'm not confident that I'll be able to fix this without breaking other things.
