### ISSUE TITLE
Compiler removed (un)used variable

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4151]
I am not sure what commit introduced this, but it seems that now the compiler is more aggressive in removing unused vars. The case in points is the following function

```nim
proc cudaMalloc32(size: int): ptr float32 =
  var error: cudaError
  let s = size * sizeof(float32)
  {.emit: """error = cudaMalloc((void**)&`result`, `s`); """.}
  check error
```

and all similar functions [here](https://github.com/unicredit/linear-algebra/blob/f001a0ca0985d274816d7aad9a9f54515447b3d6/private/cuda/cublas.nim).

Recent builds of `devel` broke [linalg](https://github.com/unicredit/linear-algebra) because for all such functions I now get errors like

```
linear-algebra/private/cuda/cublas.nim:22:27: error: ‘error’ undeclared (first use in this function)
   {.emit: """error = cudaMalloc((void**)&`result`, `s`); """.}
                           ^
```

I think what happens is that the compiler removes the declaration `var error: cudaError` because it looks unused. But it is actually used, in the manually emitted C.

I think that the best thing would be to check if the body contains any manual `{.emit.}` statement, and in this case optimize less aggressively.

I am not sure how to fix this:

* if I declare `error` inside the C body, then nim complains about the line `check error`
* otherwise, I could write everything in Nim, but I don't know how to write something that reliably produces the line `error = cudaMalloc((void**)&result, s);` as is. The fact is that `result` is initialized as a pointer to a `float32`, then its address is passed to `cudaMalloc` as a `void**`. I was not able to produce this in Nim

**Comment by andreaferretti** [comment]
Never mind, I was able to fix it by removing the manual C statement and using `addr result` instead.

Still, I will leave this open, since it looks like a bug in any case

**Comment by Araq** [comment]
The code never was correct in the first place and what happened is different: The name mangling rules changed and locals always get a trailing 0 to prevent name clashes. So now 'result' is 'result0' but don't rely on this but instead use `result` in backticks within the .emit. This way the compiler is aware of the usage, can transform it properly and will never optimize it away later on when we actually introduce a more aggressive optimizer. :-)

**Comment by andreaferretti** [comment]
Great, so if I understand correctly the correct line should have been

```nim
{.emit: """`error` = cudaMalloc((void**)&`result`, `s`); """.}
```

with `error` in backticks. If so, I can close the issue.

In any case, I took the occasion to remove the `emit` part completely and write everything in nim :-)

**Comment by Araq** [comment]
Yup, you do understand correctly.
