### ISSUE TITLE
Improve user-friendlyness of nre & options

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#4158]
It might be a good idea to export Option so that users don't also have to do `import options` to be able to use nre.

It'd be significantly more user-friendly, especially since the error message ("Error: undeclared field: 'get'") doesn't indicate how it can be fixed.

------------------

Another option might be for the error message to suggest that the user import the correct module, eg.

```
Error: undeclared field: 'get'. Maybe you meant
proc get(...): ... -- do `import options`
```

but that might be complicated (impossible?) to implement.

**Comment by moigagoo** [comment]
As a newcomer to Nim and nre, I totally support adding `export options` to nre.nim. The error message mentioned by @flaviut is so confusing I actually had to contact him and ask what the matter was; it didn't even cross my mind that I should have imported `options`.

**Comment by moigagoo** [comment]
@dom96 What are the potential complications associated with adding `export options`?

**Comment by moigagoo** [comment]
I've given it some thought and come to the conclusion that not exporting `options` is the right thing to do. It complies well with Nim's ideology of imports being bound to modules.

However, what should be improved is the error message. Missing imports should be easier to spot.

**Comment by dom96** [comment]
Hrm. I think that adding `export options` is perfectly valid.

**Comment by moigagoo** [comment]
Well, if you say so :-) https://github.com/nim-lang/Nim/pull/4229

**Comment by moigagoo** [comment]
Pull request merged, please close the issue.
