### ISSUE TITLE
Unicode support in the official oldwinapi package is broken

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4166]
Trying to compile the following minimal Nim program with `-d:winUnicode`

```
import windows
```

will result in this error:

```
Hint: system [Processing]
Hint: win [Processing]
Hint: windows [Processing]
/Users/johnnovak/.nimble/pkgs/oldwinapi-1.0.0/windows.nim(320, 14) Error: undeclared identifier: 'widechar'
```

Things seem to work OK without specifying the `winUnicode` flag though.

I tried fixing the above error, but then it would fail on something else further down... so I didn't bother investigating further.

**Comment by Araq** [comment]
I think we need to remove '-d:winUnicode', it hasn't been tested since quite a while and nobody should use it anyway, use the -W version explicitly.

**Comment by Araq** [comment]
oldwinapi has its own issue tracker. closing.

**Comment by johnnovak** [comment]
Cool, thanks. Just realised this was already raised in oldwinapi's issue tracker...
