### ISSUE TITLE
The winlean module seems to be broken

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4167]
Trying to compile the following minimal Nim program

```
import winlean
```

will result in this error:

```
lib/windows/winlean.nim(24, 19) Error: undeclared identifier: 'Utf16Char'
```

Tried specifying `-d:winUnicode` too, that resulted in the exact same error.

I've done some digging and it turns out `Utf16Char` is defined in `system/widestrs.nim`. But that module is not meant to be imported explicitly; trying to do so would yield an `You must not import this module explicitly` error.

So it looks like something is wrong with `winlean`. It's a documented public module, so it should just work when it's imported alone by itself.

**Comment by cheatfate** [comment]
Hmm, what version of nim do you use? Latest devel version compiled your minimal Nim program without error...

**Comment by johnnovak** [comment]
I was using a few weeks' old dev build. But I just compiled the latest 5 minutes ago—exactly the same results. I've done this experiment on OS X, but I don't think that should influence the results.

**Comment by cheatfate** [comment]
I think the problem is - you trying to include windows specific winlean.nim in OS X.
If you want to omit error in your portable app, try to use:
```
when defined(windows):
  import winlean
```
Then this file will be imported only, when you compiling your application on windows, and will be not imported when you compile in OSX.

**Comment by Araq** [comment]
For cross-compiling use ``--os:windows``. Why should winlean be availabe for OS X?

**Comment by johnnovak** [comment]
Makes sense, now thinking about it, it shouldn't... I just thought this would compile on any OS because winlean is Nim code... but of course, it needs headers such as windows.h to work, forgot about that part. Thanks for the explanation.
