### ISSUE TITLE
Error message, line number correct, but text not really helpful

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4169]
# import strutils

var a = "aa.bb.cc"

echo find(a, "bb")

rr.nim(4, 10) template/generic instantiation from here
lib/system.nim(2189, 10) Error: type mismatch: got (char, string)
but expected one of: 
system.==(x: char, y: char)
system.==(x: ref T, y: ref T)
system.==(x: T, y: T)
system.==(x: pointer, y: pointer)
system.==(x: set[T], y: set[T])
system.==(x: string, y: string)
system.==(x: ptr T, y: ptr T)
system.==(x: bool, y: bool)
system.==(x: Enum, y: Enum)
system.==(x: cstring, y: cstring)
system.==(x: int, y: int)
system.==(x: int8, y: int8)
system.==(x: int16, y: int16)
system.==(x: int32, y: int32)
system.==(x: int64, y: int64)
system.==(x: T, y: T)
system.==(x: float32, y: float32)
system.==(x: float, y: float)
system.==(x: array[I, T], y: array[I, T])
system.==(x: seq[T], y: seq[T])
system.==(x: T, y: T)

**Comment by Araq** [comment]
What's wrong with the error message? 'find' uses '==', that's obvious enough but there is also an  "instantiation from here" message.

**Comment by StefanSalewski** [comment]
Well, for me that message was confusing. I had to take back all the code modifications I had done in the last 10 minutes before (the point I compiled for the last time successfully) to get an idea about the problem. Of course the error location was reported correctly, but "find" symbol was not mentioned in error text. And I was sure strutils was already imported -- what was wrong. The "template/generic instantiation" message really confused me, I had the feeling I really did something evel. But OK, when there is no easy way to improve error message for this case, than we can close this issue. Next time I will know, maybe.

**Comment by dom96** [comment]
Could we maybe turn `template/generic instantiation from here` to `template/generic instantiation from here (find procedure)`?

**Comment by Araq** [comment]
@dom96 Possible and not hard to do.

**Comment by dom96** [comment]
Great. Suggestions for a better way to format that welcome.

**Comment by nc-x** [comment]
PR https://github.com/nim-lang/Nim/pull/9207
can be closed?

**Comment by StefanSalewski** [comment]
OK, will close it.
