### ISSUE TITLE
Standalone await shouldn't read future

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4170]
```nim
import asyncdispatch

proc error() {.async.} =
  if true:
    raise newException(Exception, "Test")

proc test() {.async.} =
  let errorFut = error()
  await errorFut
  if errorFut.failed:
    echo "Caught successfully"

waitFor test()
```

Results in 

```
Traceback (most recent call last)
a13.nim(13)              a13
asyncdispatch.nim(1617)  waitFor
asyncdispatch.nim(289)   read
Error: unhandled exception: Test
  error's lead up to read of failed Future:
    Traceback (most recent call last)
    a13.nim(13)              a13
    asyncdispatch.nim(1243)  test
    asyncdispatch.nim(1230)  cb
    a13.nim(8)               testIter
    asyncdispatch.nim(1243)  error
    asyncdispatch.nim(1230)  cb
    a13.nim(5)               errorIter
  test's lead up to read of failed Future:
    Traceback (most recent call last)
    a13.nim(13)              a13
    asyncdispatch.nim(1243)  test
    asyncdispatch.nim(1235)  cb
    asyncdispatch.nim(260)   callback=
    asyncdispatch.nim(1230)  cb
    asyncdispatch.nim        testIter
    asyncdispatch.nim(289)   read [Exception]
```

**Comment by dom96** [comment]
In case anyone is wondering about the workaround for this (CC @andreaferretti). You can use ``yield`` instead of ``await`` for now:

```nim
import asyncdispatch

proc error() {.async.} =
  if true:
    raise newException(Exception, "Test")

proc test() {.async.} =
  let errorFut = error()
  yield errorFut
  if errorFut.failed:
    echo "Caught successfully"

waitFor test()
```

**Comment by dom96** [comment]
Thoughts about what to do for this are also welcome!

@cheatfate tracked it down to this commit: https://github.com/nim-lang/Nim/commit/1446dc87c301268869223e32e7efdc9c76711bad (thanks @cheatfate! :))

Before that commit a standalone ``await`` statement resulted in a singular ``yield``, whereas now a ``fut.read()`` is also generated (which raises the exception). This created confusion for @tulayang (and confused me as well). The more I think about it though the more I lean towards reverting that fix.

Please let me know your thoughts. Also, sorry about the issues!

**Comment by cheatfate** [comment]
This semantic must be "somewhere" documented. If we are using **await** on function result, then it will be expanded to "yield and read()" so exception would be raised, if future has it. But if we are using **await** on future itself, then it will be expanded to "yield only", so exception will not be raised until you do not read() manually, or you can check future.failed to avoid exception... I think such semantic was before [1446dc8](https://github.com/nim-lang/Nim/commit/1446dc87c301268869223e32e7efdc9c76711bad). And i like it.

**Comment by andreaferretti** [comment]
Thank you @dom96 ! I will fix for Rosencrantz soon.

Still, I find it odd that `await` means `yield` or `yield and read` depending on whether the awaitable is a single variable or a more complex expression. It feels like something brittle that will break eventually.

Also, using `yield` explicitly feels definitely out of place. What does it even mean in this context? I know that the `async` macro expands to something involving iterators, but the compilation process is not obvious nor documented, so I have no idea what iterator is yielding

**Comment by dom96** [comment]
> Still, I find it odd that await means yield or yield and read depending on whether the awaitable is a single variable or a more complex expression. It feels like something brittle that will break eventually.

Yeah, I have this suspicion as well. But I'm not sure what the alternative is. Any ideas?

> Also, using yield explicitly feels definitely out of place. What does it even mean in this context? I know that the async macro expands to something involving iterators, but the compilation process is not obvious nor documented, so I have no idea what iterator is yielding

It's yielding the future. It is indeed an iterator, the iterator stops executing until the yielded future completes. So when you yield a future you are asking it to "please pause me until the future I yield completes". An `await` is mostly transformed to a simple ``yield``, plus a ``future.read()``. (Hope this explains it somewhat well).

**Comment by andreaferretti** [comment]
Thank you for the explanation! What is not clear to me is

> It's yielding the future. It is indeed an iterator, ...

Who is `it` in the above sentence? Each procedure marked `async` gets its own iterator?

**Comment by dom96** [comment]
>>It's yielding the future. It is indeed an iterator, ...

> Who is `it` in the above sentence? Each procedure marked `async` gets its own iterator?

``it`` refers to the iterator, or the ``async`` procedure. But an ``async`` procedure is indeed transformed to a single iterator.

```nim
proc foo() {.async.} =
  yield newFuture()
```

->

```nim
proc foo(): Future[void] =
  iterator fooIter(): FutureBase {.closure.} =
    yield newFuture()
  var myIter = fooIter
  proc cb() =
    let nextFut = myIter()
    nextFut.callback = cb
```

(Simplified, there are some details missing, like checking for the termination of the iterator)

**Comment by andreaferretti** [comment]
Great! :-) I think this should go somewhere in the documentation of `asyncdispatch`, as it conveys what is going on, which at first looks a little mysterious...

**Comment by dom96** [comment]
I reverted it so the following should no longer raise an exception:

```nim
var fut = func()
await fut
```

Neither should this:

```nim
var fut = func()
var fut2 = func2()
await fut or fut2
```

Unfortunately the following will also not raise any exceptions:

```nim
var fut2 = func2()
await func() or fut2
```

(We might need to fix that)

Take a look at the new ``tawaitsemantics`` test for the spec.

**Comment by dom96** [comment]
After discussion with @Araq, we will need re-revert this. I agree with him that the semantics shouldn't change depending on whether a standalone future is passed to ``await`` and that we need something else for this case; I vote for ``yield``.

**Comment by dom96** [comment]
We also need to change the semantics for ``or``.

**Comment by cheatfate** [comment]
Please, just document it somewhere... not in closed issue...

**Comment by edubart** [comment]
I agree this should be re-reverted, this fooled me into thinking that `await fut`  would raise exceptions, thus making me create #4392 .

**Comment by tulayang** [comment]
Digression:

```nim
import asyncdispatch

proc f() {.async.} = 
  if true:
    raise newException(ValueError, "f() error")

proc main() {.async.} = 
  try:
    for i in 0..6:
      await f()
  except:
    echo "error"
 
waitFor main()
```

I got an exception: "Error: 'yield' cannot be used within 'try' in a non-inlined iterator", is it right?

**Comment by dom96** [comment]
Don't use ``try``:

```nim
import asyncdispatch

proc f() {.async.} = 
  if true:
    raise newException(ValueError, "f() error")

proc main() {.async.} = 
  for i in 0..6:
    var fut = f()
    yield fut
    if fut.failed: echo("error")
waitFor main()
```

**Comment by tulayang** [comment]
@dom96 

This will be a vexing problem when developping web app. I want:

```nim
routes:
  var error = ""
  var rows: seq[MyRow]
  try:
    var session = newSession("redis client") # async redis cache  
    var user = await session.get("some request")
    var db = newMyDb("mysql client")         # async mysql client
    var rows = await db.query("some sql")
    await response.send(rows)
  except:
    error = getCurrentExceptionMsg()
  if error == "":
    await response.send(error)
  else:
    await response.send(rows)
```

But, I had to write like this?

```nim
routes:
  var rows: seq[MyRow]
  var session = newSession("redis client") # async redis cache  
  var user = await session.get("some request")
  if user.failed:
    await response.send(user.error)
    return
  var db = newMyDb("mysql client")         # async mysql client
  if db.failed:
    await response.send(db.error)
    return
  var rows = await db.query("some sql")
  if rows.failed:
    await response.send(rows.error)
    return
  await response.send(rows)
```

**Comment by dom96** [comment]
@tulayang Indeed. That's a slightly different problem, one which might deserve its own issue. Unfortunately the ``try`` transformation is tricky to get right, the code which performs the transformation kind of works in some cases but fails in most. It also results in incorrect semantics.

What would be ideal is if Nim supported yields within a try statement. Then the async macro won't need to do anything. For now I think I will rewrite the code so that it gives a meaningful error when the try statement transformation cannot happen reliably.
