### ISSUE TITLE
Inconsistent type in AST for unsigned int

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#4176]
In the following snippet, the constant after int gets type tyInt8 while the unsigned gets type tyInt (which is too large and of wrong sign):

```
var xxx: int8 = 0
xxx = xxx - 127  # 127 gets type tyInt8
var yyy: uint8 = 0
yyy = yyy - 127  # 127 gets type tyInt
```

Not really sure what type it _should_ have, given the wrapping semantics of uint, but it seems odd that `tyUInt8 - tyInt` results in a  `tyUInt`

**Comment by narimiran** [comment]
> Not really sure what type it should have, given the wrapping semantics of uint, but it seems odd that `tyUInt8 - tyInt` results in a `tyUInt`

On Nim 0.19.9:

```nim
var xxx: int8 = 0
xxx = xxx - 127  # 127 gets type tyInt8
var yyy: uint8 = 0
yyy = yyy - 127  # 127 gets type tyInt

echo type(xxx)
echo type(yyy)

echo xxx
echo yyy
```

produces:
```
int8
uint8
-127
129
```
