### ISSUE TITLE
GC does not free memory

### ISSUE THREAD

**Issue by zeitbit** [nim-lang/Nim#4178]
In this example the GC does not free *list* when it goes out of scope, it grows forever:

```Nim
import os
import lists

proc test() =
    var list = initDoublyLinkedList[seq[float]]()
    # If you call 'append' only one time it works correctly
    list.append(newSeq[float](1024))
    list.append(newSeq[float](1024))

while true:
    sleep(100)
    test()
    GC_fullCollect()
    echo getOccupiedMem()
```

*Nim Compiler Version 0.13.1 (2016-05-13) [MacOSX: amd64]*

**Comment by scriptum** [comment]
Other gc results:
refc - fail
boehm - ok
v2 - ok
markandsweep - ok

**Comment by Araq** [comment]
Fixed due to the merge of prim-gc into devel.
