### ISSUE TITLE
Duplicated messages for nim check

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4183]
```nim
import strutils
var a = "aa.bb.cc"

a.setLen(100)
a[99] = 'x'

if a.len > 0:
  echo(
```

$ nim check test.nim 
Hint: system [Processing]
Hint: test [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
test.nim(9, 1) Error: invalid indentation
test.nim(9, 1) Error: invalid indentation
test.nim(9, 1) Error: ')' expected

Maybe we can filter the check messages for duplicates?

**Comment by StefanSalewski** [comment]
And maybe sorting messages for column also -- would make use of nimsuggest easier:

import strutils
var a = "aa.bb.cc"

a.seten+++++++++++++(100)
a[99] = 'x'

if a.len > 0:
  echo(0)

$ nim check test.nim
test.nim(4, 8) Error: undeclared identifier: '+++++++++++++'
test.nim(4, 2) Error: undeclared field: 'seten'
test.nim(4, 2) Error: expression '.' cannot be called
test.nim(4, 8) Error: attempting to call undeclared routine: '+++++++++++++'
test.nim(4, 8) Error: expression '+++++++++++++' cannot be called

**Comment by StefanSalewski** [comment]
But maybe nimsuggest should sent the erros in a more structured format like JSON?

**Comment by narimiran** [comment]
The first example now gives no duplications anymore:
```
proba3.nim(8, 1) Error: invalid indentation
proba3.nim(9, 1) Error: expected: ')', but got: '[EOF]'
```

The second example:
```
proba3.nim(8, 1) Error: invalid indentation
proba3.nim(4, 8) Error: undeclared identifier: '+++++++++++++'
proba3.nim(4, 2) Error: undeclared field: 'seten' for type system.string [declared in lib/system.nim(49, 3)]
proba3.nim(4, 2) Error: undeclared field: '.' for type system.string [declared in lib/system.nim(49, 3)]
proba3.nim(4, 2) Error: expression '.' cannot be called
proba3.nim(4, 8) Error: attempting to call routine: '+++++++++++++'
  found '+++++++++++++' of kind 'unknown'
proba3.nim(4, 8) Error: attempting to call routine: '+++++++++++++'
  found '+++++++++++++' of kind 'unknown'
proba3.nim(4, 8) Error: expression '+++++++++++++' cannot be called
```
