### ISSUE TITLE
Deconstruct tuple using map failed

### ISSUE THREAD

**Issue by k0pernicus** [nim-lang/Nim#4189]
Hi guys!
I'm trying to zip to sequences of integers, multiply each tuple and sum them.

This is the code I wrote:
```
## My seq
let fst_integers = @[0,1,2,3,4,5,6,7,8,9,10]
let snd_integers = @[10,11,12,13,14,15,16,17,18,19,20]
## Get tuples
let input = zip(fst_integers, snd_integers)
sum(map(input, proc(x : (int, int)) : int = x.a * x.b))
```

Unfortunately, the compiler give me this error: ```undeclared field: 'a'``` (the same error for 'b' too). Also, 'a' and 'b' are fields resulting from ```zip``` (see documentation [here](http://nim-lang.org/docs/sequtils.html#map,openArray[T],proc(T))).
Is it possible to deconstruct the tuple using an anonymous function in ```map```?

**Comment by Araq** [comment]
I think the compiler is correct, use  ``x[0] * x[1]`` instead.

**Comment by k0pernicus** [comment]
Yes - I made this and it works - but it's weird because, when you look after input, the zip structure is like ```(a: number, b: number)```...

**Comment by Araq** [comment]
``proc(x : (int, int)) : int = x.a * x.b)`` you clearly state ``x`` is a tuple of unnamed components here, so the compiler doesn't know about ``x.a``. Nothing weird going on here.

**Comment by k0pernicus** [comment]
Oh exact...
Sorry for that -_-
