### ISSUE TITLE
Crash on large GC with cyclical references

### ISSUE THREAD

**Issue by karlseguin** [nim-lang/Nim#4192]
```nim
type
  Node = ref object
    next: Node
    prev: Node
    value: int

var head = new(Node)
var current = head

for i in 0..<1_000_000:
  current.next = Node(value: i, prev: current)
  current = current.next

head = nil
GC_fullCollect()
```

Gives "execution of an external program failed" without any other context

I assume it's related to the cyclical reference since it doesn't crash if `prev` is removed. I also believe this is a bug because it doesn't crash if we reduce the number of items.

**Comment by Araq** [comment]
Fixed by merging prim-gc into devel.
