### ISSUE TITLE
Get type name as string in typeinfo

### ISSUE THREAD

**Issue by skyfex** [nim-lang/Nim#4193]
It would be great if there was a way to get the name of a type from an Any container in the typeinfo module.

I need it in a marshal-like library, and I suppose it would be useful for ORM projects too.

As far as I can see it should just be a matter of modifying TNimType to incldue a name field, and to have genTypeInfoAuxBase in ccgtypes.nim fill it with the value of typ.sim.name.s .. but I'm not sure I feel confident creating a pull request for that.

**Comment by Araq** [comment]
Your description is correct, but I'm worried about RTTI's size.

**Comment by skyfex** [comment]
> but I'm worried about RTTI's size.

True. Could it be a pragma or option though?

Or is it perhaps possible to lift specific compile-time type information to run-time?

If I could, at compile time, iterate over all the types used by a object and its subtypes to get their names and create a table, that would solve my problem too.

**Comment by Araq** [comment]
This feature is now available via ``-d:nimTypeNames`` but not yet documented and also might change again.

**Comment by Araq** [comment]
Marshalling is supposed to be done with the ``getType`` family of procs nowadays.
