### ISSUE TITLE
Mathematics module missing modf

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4195]
The `modf` function breaks a floating point number into an integral and fractional part.  This is missing from the maths module (math.nim).

Following the style of math.nim, I think this is as simple as adding the following two implementations (within `{.push noSideEffect.}`):

    when not defined(JS):
      proc modf*(x: BiggestFloat, intpart: var BiggestFloat): BiggestFloat {.importc: "modf", header: "<math.h>".}
        ## Breaks `x` into an integral and a fractional part.
        ##
        ## The integer part is stored in the object pointed by
        ## intpart, and the fractional part is returned by the function.
        ##
        ## Both parts have the same sign as x.
    else:
      proc modf*(x: BiggestFloat, intpart: var BiggestFloat): BiggestFloat =
        ## Breaks `x` into an integral and a fractional part.
        ##
        ## The integer part is stored in the object pointed by
        ## intpart, and the fractional part is returned by the function.
        ##
        ## Both parts have the same sign as x.
        var
          absolute: BiggestFloat
        absolute = abs(x)
        intpart = floor(x)
        result = absolute - intpart
        if x < 0:
          intpart = -intpart
          result = -result

Arguably, the latter is sufficient, but since most of the existing functions in the maths library use the C implementations I thought it best to be consistent.

**Comment by Araq** [comment]
Yeah, please add it as PR.

**Comment by krux02** [comment]
I would like to add my two cents, and suggest, to change the api, to return two values as a tuple

    proc modf*(x: BiggestFloat): tuple[intpart: BiggestFloat, fractpart: BiggestFloat]

**Comment by abudden** [comment]
@krux02 I agree this is nicer than having a `var float` parameter.  Another couple to add to your list:

advantages:

* forces the issue of having a "pure" nim implementation rather than using `{.importc.}`

disadvantages:

* inconsistent with other procedures in math.nim (frexp).  Having said that, given Nim hasn't got to 1.0 yet, I guess frexp could also be changed (the javascript implementation is already pure Nim).

Once I've sorted out my issues with building Nim from source (#4206), I'll submit a pull request, but (particularly as it'll be my first one), I'll have to bow to @Araq's preference on whether it's `var float` or a returned tuple.

**Comment by abudden** [comment]
Another query in terms of Nim philosophy: is it preferable to copy `math.h` naming (i.e. `modf`), or rename the function to have a more meaningful name (e.g. `splitDecimal` or even just `split`, which I don't believe has any current functionality if passed a float)?

**Comment by krux02** [comment]
@abudden I am not sure where your advantage is actually an advantage. I don't see a problem to call a well tested and optimized standart library function when available. But I would recommend, not to start a big discussion here about how to do naming and stuff. I am sorry for starting this.

**Comment by dom96** [comment]
I think this will need a different name, it's easily confused with ``fmod``.
