### ISSUE TITLE
formatSize has incorrect prefix

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4198]
formatSize (in strutils.nim) implements the following:
```
  let gigabytes = bytes shr 30
  let megabytes = bytes shr 20
  let kilobytes = bytes shr 10
  if gigabytes != 0:
    result = frmt(gigabytes, megabytes, "GB")
  elif megabytes != 0:
    result = frmt(megabytes, kilobytes, "MB")
  elif kilobytes != 0:
    result = frmt(kilobytes, bytes, "KB")
  else:
    result = insertSep($bytes) & "B"
```

I'm not sure why it stops at GB (and not TB, PB etc), but there are a couple of issues here of questionable importance:

* Kilo is written k, not K, so "KB" should be "kB"
* Strictly speaking, these are binary prefixes, so it would be better to use the IEC ones (kibi etc instead of kilo etc): https://en.wikipedia.org/wiki/Binary_prefix#IEC_prefixes, in which case it should be KiB, MiB, GiB, TiB etc
* Absolutely strictly speaking (okay, maybe I'm getting carried away now), there should be a (non-breaking?) space between the number and the unit: 4096 == "4&nbsp;KiB"

**Comment by dom96** [comment]
Fix it :)

Would be nice to extend `formatSize` so that you can choose between KiB and kB.

**Comment by abudden** [comment]
Okay!  Once I've got the test harness up and running I'll send in a pull request that does all of the above (with the kB/KiB being an option and the space being an option).

I'll also fix what I see as very weird behaviour:

```
formatSize((1'64 shl 31) + (300'64 << 20)) -> 2.234GB
```
This might look reasonable, but the result of those shifts is 2462056448 and if you divide that by 2^30, you get 2.29296875, so it should be 2.293&nbsp;GB.  What it's actually reporting seems to be the number of gigabytes (in this case 2) followed by a decimal separator, followed by the number of megabytes (2348) truncated to only show the first three characters.  This is **really** weird.  I'd almost understand if it reported 2.300&nbsp;GB (2&nbsp;GB + 300&nbsp;MB) but 2.234&nsbp;GB to mean 2&nbsp;GB **or** 234 tens-of-megabytes is just cryptic!

I can only assume that no-one is actually using this function as I can't think of many situations where you'd want to report size in this format.

**Comment by Araq** [comment]
Hey, I use it and tbh it's the only thing that makes sense to me, but fine, change it.
