### ISSUE TITLE
osproc waitForExit() is ignoring the timeout parameter

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#4200]
See https://github.com/nim-lang/Nim/blob/v0.13.0/lib/pure/osproc.nim#L971

To reproduce:
import osproc
let p = startProcess("/bin/sleep", args=["100"])
let cmd_out = p.waitForExit(timeout=1)

**Comment by cheatfate** [comment]
Looks like `timeout` parameter supported only in Windows, to resolve this we need to replace **waitpid()** with **sigtimedwait()**.

**Comment by dom96** [comment]
@cheatfate cool, wanna make a PR?
