### ISSUE TITLE
Compiler error for pragma noSideEffect isn't very helpful

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4210]
Consider this code:

``` nim
import tables
import strutils
import math

proc testProc(): void {.noSideEffect.} =
    var
        i: int
        f: float
        s: string
    let table = {'a': 1, 'b': 2, 'c': 3, 'd': 4}.toTable()
    f = log10(54712344.1123)
    i = f.int()
    s = formatFloat(f, ffScientific)
    debugEcho table['c']

when isMainModule:
    testProc()
```

Passing this to Nim produces the following error message:

```
test.nim(5, 6) Error: 'testProc' can have side effects
```

As a user, this isn't very helpful.  Okay: I understand that it has side-effects, but I can't see any side-effects:
- The first operational line (line 10) creates a hash table
- The second (line 11) calculates a logarithm
- The third (line 12) converts a floating point number to a string
- The last (line 13) is a debugEcho (which pretends to not have side-effects)

By going through the code and commenting out lines at random, I worked out that the offending function was `toTable()`, which either has side-effects or doesn't declare a `noSideEffect` pragma.  However, it would have been **so** much easier (especially for long and complex procedures) if the error message had said:

```
test.nim(5, 6) Error: 'testProc' can have side effects at (10, 50)
```

Now of course there may be multiple instances of side effects, but even if only the first one is shown the user at least has the opportunity to work through them one-by-one.  Alternatively (and better in my opinion) the error could be shown as:

```
test.nim(10, 50) Error: 'testProc' can have side effects despite noSideEffect pragma
```

with a separate entry for each line with a side-effect.  This would have the advantage that tools like [syntastic](https://github.com/scrooloose/syntastic) would mark the location of the side-effect directly.

**Comment by Araq** [comment]
Well ``noSideEffect`` predates the other effect checking which produces better error messages. ;-)
