### ISSUE TITLE
The destructor is not called for temporary objects

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4214]
Here is my test:

``` nim
type
  Data = object
    data: string

{.experimental.}

proc `=destroy`(d: Data) =
  echo d.data, " destroyed"

proc `=`(dst: var Data, src: Data) =
  echo src.data, " copied"
  dst.data = src.data & " (copy)"

proc initData(s: string): Data =
  result = Data(data: s)
  echo s, " created"

proc main =
  var x = initData"test"

when isMainModule:
  main()
```

It outputs:

```
test created
test copied
test (copy) destroyed
```

The destructor is called for the copy, but not for the original object.

**Comment by vegansk** [comment]
@Araq, is this the reason that the ``SharedString`` assignment operator is disabled? https://github.com/nim-lang/Nim/blob/devel/lib/pure/collections/sharedstrings.nim#L41

**Comment by Araq** [comment]
This works with ``--newruntime`` (which is the third iteration on the destructor feature).
