### ISSUE TITLE
Regular Expression library documentation is confusing

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4217]
I was interested in the regular expression library (in particular whether it supports named groups, which I now think it does).  In the standard library documentation (http://nim-lang.org/docs/lib.html) under impure libraries is

> [re](http://nim-lang.org/docs/re.html) This module contains procedures and operators for handling regular expressions. The current implementation uses PCRE.

Clicking on the "re" link takes you to http://nim-lang.org/docs/re.html which says:

> Regular expression support for Nim. Deprecated. Consider using the nre or pegs modules instead.

There are no links here, so I went back to the standard library page and searched for "nre".  This just has one reference under "Unofficial packages":

> [nre](https://github.com/flaviut/nre) A better regular expression library.

Clicking on this link (https://github.com/flaviut/nre) gives:

> UNMAINTAINED
> 
> [Use nre from the stdlib](https://github.com/nim-lang/Nim/blob/master/lib/impure/nre.nim)

This in turn links to https://github.com/nim-lang/Nim/blob/master/lib/impure/nre.nim

This was not a straightforward way of finding the documentation - I think the last link above needs to be included in the [standard library documentation](http://nim-lang.org/docs/lib.html), preferably with the generated documentation rather than the raw nim code.

**Comment by dom96** [comment]
The status of `re` and `nre` is currently undecided.

@Araq still prefers `re`. I tend to agree: I think that `nre`'s API isn't idiomatic enough. Right now I can't tell you what it actually solves, this issue seems to explain the rationale: https://github.com/nim-lang/Nim/issues/2511. In addition to that, I decided to show how to use `re` in my book not `nre`. I can still change it but time is certainly running out.

I guess I need to spend some time looking at the `nre` module and deciding whether we should keep it or not.

**Comment by dom96** [comment]
By the way, thank you for looking at the standard library and giving so much feedback. It really helps. Especially at this moment in time where a fresh set of eyes is really important.

**Comment by abudden** [comment]
> The status of re and nre is currently undecided.

Ah: okay, that explains a lot about the documentation.  Just to give my opinion on this: I have no strong preference on which but I do notice that `nre` supports `(?<name>..)` whereas `re` doesn't seem to.  That would be enough for me to pick `nre` as the `(?P<name>..)` feature in python is (in my opinion) one of the only things that makes regular expressions readable!

> By the way, thank you for looking at the standard library and giving so much feedback. It really helps. Especially at this moment in time where a fresh set of eyes is really important.

You're very welcome.  To be honest it's just my way of learning Nim - it's a **very** new (and exciting) language to me and I've struggled a bit with the documentation so browsing around and trying to understand how things work has been a really useful learning experience.  I've spent a lot of years programming (embedded) C, (non-embedded) C++ and python (as well as a few less palatable languages like perl) so I naturally compare Nim to those.  My use-case for Nim is primarily as a python-replacement that can easily be compiled into an easily distributable executable (rather than having to use py2exe to essentially wrap all of python into a zip file).

**Comment by moigagoo** [comment]
I was confused by this situation as well. It's certainly no good to have two competing libraries for the same task. Especially when one of them is explicitly marked as deprecated, but the two core developers of the language prefer it :-)

IMHO, nre is a clear winner. It has issues with usability, but we can address them. For example, adding `export options` made using captures easier, and adding the `contains` proc made the interface closer to re.

@dom96 I'm reading the chapter where you introduce regex at the moment, and I have to confess that I rewrite your code samples in nre anyway :-)

**Comment by Araq** [comment]
``re.nim`` is the official regex module for Nim, it's been un-deprecated.
