### ISSUE TITLE
RFC: Nim String Functions

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4218]
Having see #3745, I thought it might be interesting to do something similar for string functions:

This is a comparison of string functions, with the aim of helping to identify if any functions are missing that may need to be added, etc. (in preparation for Nim V1.0)

Don't assume I correctly identified the Nim string functions (I may have missed some, or are available in other Nimble packages).  Functions are in `strutils.nim` unless otherwise specified.

| Python Function | Nim Function |
| --- | --- |
| `str[:-1]` | `str[0..<str.high]` # Should be `str[..^1]`, but I can't get this to work |
| `str[1:]` | `str[1..str.high]` # Should be `str[1..]`, but I can't get this to work |
| `str[1:-1]` | `str[1..<str.high]` # Should be `str[1..^1]`, but I can't get this to work |
| [`str.capitalize`](https://docs.python.org/3/library/stdtypes.html#str.capitalize) | `capitalize` |
| [`str.center`](https://docs.python.org/3/library/stdtypes.html#str.center) | `center` (from Nim 0.15) |
| [`str.count`](https://docs.python.org/3/library/stdtypes.html#str.count) | `count` |
| [`str.decode`](https://docs.python.org/3/library/stdtypes.html#str.decode) |  |
| [`str.encode`](https://docs.python.org/3/library/stdtypes.html#str.encode) |  |
| [`str.endswith`](https://docs.python.org/3/library/stdtypes.html#str.endswith) | `endsWith` (for use with chars rather than strings, requires Nim 0.15 or greater) |
| [`str.expandtabs`](https://docs.python.org/3/library/stdtypes.html#str.expandtabs) | `expandTabs` (from Nim 0.15) |
| [`str.find`](https://docs.python.org/3/library/stdtypes.html#str.find) | `find` |
| [`str.format`](https://docs.python.org/3/library/stdtypes.html#str.format) | `format` **but** nowhere near as powerful as python's version |
| [`str.index`](https://docs.python.org/3/library/stdtypes.html#str.index) | `find` |
| [`str.isalnum`](https://docs.python.org/3/library/stdtypes.html#str.isalnum) | `isAlphaNumeric` |
| [`str.isalpha`](https://docs.python.org/3/library/stdtypes.html#str.isalpha) | `isAlpha` |
| [`str.isdigit`](https://docs.python.org/3/library/stdtypes.html#str.isdigit) | `isDigit` |
| [`str.islower`](https://docs.python.org/3/library/stdtypes.html#str.islower) | `isLower` |
| [`str.isspace`](https://docs.python.org/3/library/stdtypes.html#str.isspace) | `isSpace` |
| [`str.istitle`](https://docs.python.org/3/library/stdtypes.html#str.istitle) | `unicode.isTitle` (from Nim 0.15) |
| [`str.isupper`](https://docs.python.org/3/library/stdtypes.html#str.isupper) | `isUpper` |
| [`str.join`](https://docs.python.org/3/library/stdtypes.html#str.join) | `join` |
| [`str.ljust`](https://docs.python.org/3/library/stdtypes.html#str.ljust) | _done manually with repeatChar according to Nim docs, although it is deprecated_ |
| [`str.lower`](https://docs.python.org/3/library/stdtypes.html#str.lower) | `toLower` |
| [`str.lstrip`](https://docs.python.org/3/library/stdtypes.html#str.lstrip) | `strip(s, leading=false)` |
| [`str.partition`](https://docs.python.org/3/library/stdtypes.html#str.partition) | `strmisc.partition` (from Nim 0.15) |
| [`str.replace`](https://docs.python.org/3/library/stdtypes.html#str.replace) | `replace` |
| [`str.rfind`](https://docs.python.org/3/library/stdtypes.html#str.rfind) | `rfind` |
| [`str.rindex`](https://docs.python.org/3/library/stdtypes.html#str.rindex) | `rfind` |
| [`str.rjust`](https://docs.python.org/3/library/stdtypes.html#str.rjust) | `align` |
| [`str.rpartition`](https://docs.python.org/3/library/stdtypes.html#str.rpartition) | `strmisc.rpartition` (from Nim 0.15) |
| [`str.rsplit`](https://docs.python.org/3/library/stdtypes.html#str.rsplit) | `rsplit` (from Nim 0.15) |
| [`str.rstrip`](https://docs.python.org/3/library/stdtypes.html#str.rstrip) | `strip(s, trailing=false)` |
| [`str.split`](https://docs.python.org/3/library/stdtypes.html#str.split) | `split` |
| [`str.splitlines`](https://docs.python.org/3/library/stdtypes.html#str.splitlines) | `splitLines` |
| [`str.startswith`](https://docs.python.org/3/library/stdtypes.html#str.startswith) | `startsWith` for strings, `str[0] == c` for characters |
| [`str.strip`](https://docs.python.org/3/library/stdtypes.html#str.strip) | `strip` |
| [`str.swapcase`](https://docs.python.org/3/library/stdtypes.html#str.swapcase) | `unicode.swapCase` (from Nim 0.15) |
| [`str.title`](https://docs.python.org/3/library/stdtypes.html#str.title) | `unicode.title` (from Nim 0.15) |
| [`str.translate`](https://docs.python.org/3/library/stdtypes.html#str.translate) | No direct equivalent (`strutils.translate` is for word translation). Closest equivalent is `parallelReplace` in `pegs` or `re` modules. |
| [`str.upper`](https://docs.python.org/3/library/stdtypes.html#str.upper) | `toUpper` |
| [`str.zfill`](https://docs.python.org/3/library/stdtypes.html#str.zfill) | `align(padding='0')` |

**Comment by dom96** [comment]
This is brilliant! Thank you for doing this. It's exactly what I want to be done for the standard library before I can safely say "it's now 1.0 ready".

In addition to this it would be nice to think about procedures which are currently in the standard library but perhaps shouldn't be, or their API/semantics are bad.

Some things I've noticed:

* `str[:-1]` -> `str[.. ^1]`, similar for other slicing examples
* `str.format` -> I would say that `%` is equivalent: `"Foo bar: $1 $2" % [23, 42]`

**Comment by abudden** [comment]
> str[:-1] -> str[.. ^1], similar for other slicing examples

That's really useful: thank you.  I was trying to figure out a tidy way of doing it and obviously my documentation searching failed.

> str.format -> I would say that % is equivalent: "Foo bar: $1 $2" % [23, 42]

Personally I'd disagree with this - it is similar, but nowhere near as capable:
```python
s = "{greet} {name}, the square root of {x:d} is {rtx:0.4f}".format(
        name="Dominik",
        x=40,
        rtx=math.sqrt(40),
        greet="Hello"
        )
```

I'll edit the list to make it slightly less provocative though...

**Comment by dom96** [comment]
> Personally I'd disagree with this - it is similar, but nowhere near as capable:

Oh. Didn't realise Python's was that powerful :)

**Comment by abudden** [comment]
Also (python's % notation + dictionaries):
```python
s = "%(greet)s %(name)s, the square root of %(x)d is %(rtx)0.4f" % {
        'name': "Dominik",
        'x': 40,
        'rtx': math.sqrt(40),
        'greet': "Hello"
        }
```

**Comment by abudden** [comment]
Oh (probably going off topic), does Nim's `format`/`%` support any type of bracketing?
```python
#!/usr/bin/python
"Hello {1}, {0} multiplied by 10 is {0}0".format(7, "Dominik")
# Hello Dominik, 7 multiplied by 10 is 70
```
```nim
s = "Hello $2, $1 multiplied by 10 is $10" % [$7, "Dominik"]
# Error: unhandled exception: invalid format string [ValueError]
s = "Hello $2, $1 multiplied by 10 is $1 0" % [$7, "Dominik"]
# Hello Dominik, 7 multiplied by 10 is 7 0
s = "Hello $name, $number multiplied by 10 is $number0" % ["number", $7, "name", "Dominik"]
# Error: unhandled exception: invalid format string [ValueError]
```

**Comment by abudden** [comment]
@dom96 I'm trying your example

> str[:-1] -> str[.. ^1], similar for other slicing examples

```nim
var str = "abcdef"
echo str[.. ^1]
```

Without the space between `..` and `^1`, I get a compiler error: 

```
test.nim(2, 10) Error: type mismatch: got (int literal(1))
but expected one of:
system...^(a: untyped, b: untyped)
```

With the space, it prints "abcdef" (not "abcde" as expected).

I've also tried a suggestion from @Araq: using setLength to shorten a string:

```nim
var str = "abcdef"
str.setLength(str.len-1)
echo str
```

This produces:

```
test.nim(2, 4) Error: attempting to call undeclared routine: 'setLength'
```

Any suggestions?

**Comment by Araq** [comment]
It's called ``setLen``.

**Comment by abudden** [comment]
> It's called `setLen`.

Ah: thank you (and sorry for not having found it myself).

**Comment by jyapayne** [comment]
I can add most of these functions to Nim in a pull request, along with proper comments and tests. I have some free time today :)

**Comment by jyapayne** [comment]
@dom96 For a PR, would you prefer a separate commit for each proc with tests or one big commit with all procs and tests that I have added?

**Comment by dom96** [comment]
Don't really mind, whichever is easiest. All of these procs are pretty similar so it's fine to put them in the same commit I think.

**Comment by jyapayne** [comment]
For string.translate, would it be acceptable to import tables? I don't really want to introduce a dependency like that just for that proc. If it's not acceptable, where should it go?

**Comment by Varriount** [comment]
Is translate char (byte) based, or something else?

**Comment by jyapayne** [comment]
Here is the method signature I was thinking of:

```nim
proc translate(s: string, dictionary: TableRef[string, string]): string
```

The "translate" here would be used for translating words to other languages.

**Comment by Araq** [comment]
Use this signature instead:

```proc translate(s: string, replacements: proc (key: string): string): string```

**Comment by jyapayne** [comment]
@Araq, that's a good idea, I hadn't thought of it. That makes however the user wants to implement it work regardless. Very elegant :)

@Varriount The reason I thought a table would be necessary is because of lookup speed. But Araq's comment makes more sense to me now.

**Comment by jyapayne** [comment]
For isUpper, toUpper, etc, would anyone mind if I converted all of those to be unicode compatible and move them to the unicode module?

**Comment by Varriount** [comment]
I wouldn't remove the versions that already exist, however I would mark them as deprecated.

**Comment by jyapayne** [comment]
Right, that makes sense.

**Comment by jyapayne** [comment]
@Araq, for the translate proc, can a lambda type declare that it can't have side effects?

**Comment by jyapayne** [comment]
@Varriount and @Araq, how would I go about referencing the new unicode procs inside strutils for deprecated isUpper, toUpper, etc? Is there a special way to reference deprecations from other modules?

**Comment by Varriount** [comment]
You wouldn't reference them, except in the documentation. If I recall correctly, you can use a bare `{.deprecated.}` pragma

**Comment by Araq** [comment]
> For isUpper, toUpper, etc, would anyone mind if I converted all of those to be unicode compatible and move them to the unicode module?

I would. I use strutils.toUpper etc because I know what I'm doing and I like the improved speed and code size. But that's just another fight I will lose and something "Araq's lib" will offer.

**Comment by jyapayne** [comment]
@Araq, if I simply deprecate them, you'd still be able to use them, right? I'm a bit confused because this comment directly contradicts your [earlier comment](https://github.com/nim-lang/Nim/pull/4276#discussion_r65815899) about making things Unicode compatible. I simply want to contribute something that will be of use to the community.

**Comment by ReneSac** [comment]
There are very solid use cases for each version of `toUpper` and similar functions. Working correctly with unicode is much slower, and may not be what you want either. D solution for that is to have a toUpper in the [unicode module](https://dlang.org/phobos/std_uni.html#toUpper), and another toUpper in the [ascii module](https://dlang.org/phobos/std_ascii.html#.toUpper).

Also, for string formatting, there is [strfmt](https://bitbucket.org/lyro/strfmt) that is very similar to python .format(). It was suggested many times to be included in the standard library, but I don't know the status of the discussion. It would also introduce a second or third style for formating strings, which isn't really ideal.

**Comment by johnnovak** [comment]
@jyapayne May I suggest some additional stuff for the replace functionality that I think would be useful:

* `replace` (and maybe alias it to `replaceFirst` too)
* `replaceAll`
* `replaceLast`

Also, it would be nice to add a version of `replace` in the `re` module that accepts a callback so you can do your custom replace logic in a function (that's super useful in Scala, for example).

**Comment by jyapayne** [comment]
@ReneSac That's a good idea as well. I'm okay with having both at the same time. I would have to correct some libraries that import both unicode and strutils, but if Araq is okay with it, it's fine with me :)

@johnnovak I'm not sure what the expectation is with Nim, but an idea from Python's replace function could be that it has a `count` default parameter (set to 1) that will replace `count` occurrences of the word in `s`. If set to -1, then it could replace all occurrences. That would cover both `replace` and `replaceAll` with one function. As for `replaceLast`, maybe `replaceRight` or some other name that would replace starting from the right side of the string with similar parameters as `replace`?

The callback sounds like a useful idea as well :)

**Comment by johnnovak** [comment]
@jyapayne I like your `replace` & `replaceRight` idea with an optional `count` parameter. I agree that it makes sense to be consistent with the rest of the string functions that seem to follow the Python conventions.

Yeah, when you need that callback regexp replace thingy, it *really* comes in handy—for example, when you want to append additional query parameters to all URLs in a block of text (that was my specific use when I discovered it in the standard Scala lib).

**Comment by abudden** [comment]
I've updated the table to reflect the changes made in PR #4276.

**Comment by kaushalmodi** [comment]
I am using the devel version of Nim as of today and `expandTabs` is in [`strmisc`][1] instead of `strutils`.

[1]: https://nim-lang.org/docs/strmisc.html

**Comment by kaushalmodi** [comment]
@dom96 

For me, I found `str[.. ^2]` in Nim to be equivalent to `str[:-1]` in Python. Also I had to put a space between `..` and `^2` as @abudden also found out.

Similarly, `str[1.. ^0]` and `str[1.. ^1]` works the same as `str[1:]` in Python. So what's the difference between `^0` and `^1`?

**Comment by kaushalmodi** [comment]
If I import both `unicode` and `strutils` package, how do I specify that I want to use the `isUpper` proc from `unicode`, and not the deprecated version in `strutils`?

Example:

```
echo "À".isUpper()
```

Above gives: 

> Error: ambiguous call; both strutils.isUpper(s: string)[declared in lib/pure/strutils.nim(322, 5)] and unicode.isUpper(s: string)[declared in lib/pure/unicode.nim(1406, 5)] match for: (string)

**Comment by kaushalmodi** [comment]
Hello all, I have taken the comparison table in this thread and written a detailed post with full code and output about string functions between Nim and Python: https://scripter.co/notes/string-functions-nim-vs-python

Looking forward to comments and corrections.

**Comment by TiberiumN** [comment]
@kaushalmodi there's strfmt module in nimble for enhanced string formatting

**Comment by TiberiumN** [comment]
@kaushalmodi and don't forget to note that Nim is compiled and statically typed while python is interpreted dynamic :)

**Comment by TiberiumN** [comment]
@kaushalmodi 
```nim
var str = "a\tbc\tdef\taghij\tcklm\tdanopqrstuv\tadefwxyz\tzyx"
echo str[0.. <str.high]
# or
echo str[.. ^2]
```
Why ^2?
^1 works perfectly for me

**Comment by TiberiumN** [comment]
@kaushalmodi about second example - it's because you can access null terminator which is the end of any string

**Comment by TiberiumN** [comment]
@kaushalmodi also - there IS "encode" and "encode" like functions in nim - take a look at "encodings" module

**Comment by TiberiumN** [comment]
@kaushalmodi also 
```nim
echo "À".unicode.isUpper() # Does not work
```
does not work because you're trying to find some procedure which can accept string.
You can use isUpper() without "unicode" as long as you don't import strutils

**Comment by kaushalmodi** [comment]
@TiberiumN 

> there's strfmt module in nimble for enhanced string formatting

Thanks, I'll need to do some digging on that.

> and don't forget to note that Nim is compiled and statically typed while python is interpreted and dynamic :)

Of course, the point of this post is to just compare string functions between the two languages.

> ^1 works perfectly for me

It doesn't for me, at least on Linux 64-bit, Nim build from devel as of yesterday. [This][1] is what `^2` gives me, and [this][2] is what `^1`/`^0` give me. The results you see on my blog post are calculated live using Org Babel. So I did not manually paste the code and results separately.

> about second example - it's because you can access null terminator which is the end of any string

Yes, but it's still not clear as to when to use `str[1.. ^0]` vs `str[1.. ^1]`.

> also - there IS "encode" and "encode" like functions in nim - take a look at "encodings" module - convert procedure can convert from one encoding to another

Thanks. I'll take a look.

> You can use isUpper() without "unicode" as long as you don't import strutils

That's not very practical. Based on what I see, `strutils` looks like a must-have module in any Nim code where I am doing even basic string manipulation. So it will be unlikely for a scope to have `unicode` imported, but not `strutils`. 

Thanks for your comments! I was beginning to think no one was reading this Issue thread :)

[1]: https://scripter.co/notes/string-functions-nim-vs-python/#all-characters-except-last
[2]: https://scripter.co/notes/string-functions-nim-vs-python/#all-characters-except-first

**Comment by kaushalmodi** [comment]
@TiberiumN Which is the official `strfmt`? I found [lyro/strfmt][1] and [rgv151/strfmt][2].

[1]: https://bitbucket.org/lyro/strfmt
[2]: https://github.com/rgv151/strfmt

**Comment by TiberiumN** [comment]
@kaushalmodi "Yes, but it's still not clear as to when to use str[1.. ^0] vs str[1.. ^1]"
When you need to access null terminator - you use ^0, when you don't need to do it - you do ^1.
But you almost never need to access it, so just use ^1 :)

**Comment by dom96** [comment]
Here is how you should do it:

```
import strutils except isUpper
import unicode

echo "À".isUpper()
```

-----

Btw, thanks for writing that blog post! Always love to see new blog posts about Nim :)

Some feedback:

> ```nim
> var str = "a\tbc\tdef\taghij\tcklm\tdanopqrstuv\tadefwxyz\tzyx"
> # echo str[1..] Does not work.. Error: expression expected, but found ']'
> ```

This looks like a bug to me, [I reported it](https://github.com/nim-lang/Nim/issues/6212) :)

You shouldn't be showing all of the different ways to write ``startsWith`` (and the other procs), the convention is ``startsWith`` so stick to it!

**Comment by kaushalmodi** [comment]
@TiberiumN @dom96 Thanks for your feedback! I have updated my post with those.

**Comment by Yardanico** [comment]
@Araq, @dom96 can this be closed?
str.encode and str.decode - we have module "encodings" which AFAIK does the same thing.
yeah, we don't have str[:-1], str[1:]
Instead we use
str[0..^2]
str[1..^1]
and for str[1:-1] we use str[1..^2]

Also we now have better "translate"-like procedure - strutils.multiReplace

**Comment by Araq** [comment]
With the new ``strformat`` it seems on par with Python. Closing.
