### ISSUE TITLE
countdown with uint causes underflow

### ISSUE THREAD

**Issue by marshallmason** [nim-lang/Nim#4220]
When you countdown from a uint to 0, it will go into an infinite loop because countdown underflows for uints. Here is a snippet of code that demonstrates this (preventing the infinite loop to make the underflow easier to see):

`const count: uint = 5
var stop_me = false

for i in countdown(count, 0):
    echo i
    if stop_me: quit(0)
    if i == 0:
        echo "it should stop now"
        stop_me = true`

Looking at the source code for countdown, I see that it has two paths, depending on the size of int. It creates an IntLikeForCount type, which includes uint8 and uint16 cases, but not uint. Therefore, changing the above code to use uint8 or uint16 is a work-around.

**Comment by Araq** [comment]
So? Why is that a bug? It's common knowledge that not even counting works with unsigned numbers.

**Comment by Varriount** [comment]
Isn't this more of a compiler limitation though? Otherwise, why would this only be limited to specific uint types?

**Comment by Araq** [comment]
@Varriount we widen the integer type for counting but refuse to widen it to a 64 bit type which can be slow on 32 bit machines. Even worse, ``uint`` is 64 bits on a 64 bit machine so there is no signed type we could use so that -1 is available for the counting to be successful. Other workarounds are possible too but none which justifies all this complexity and the slowdowns it causes. I rather have a fast ``system.countup`` than one that supports dubious code.

**Comment by Varriount** [comment]
How does Rust handle this then?

**Comment by marshallmason** [comment]
Well, it's up to you whether this is a bug or a feature, but I reported it because it seems very wrong. I see no reason why counting should be a problem for unsigned numbers, as long as we don't try to drop it below zero.

Consider this:
```
var i: uint = 1
dec(i)
echo i
```

This works fine. But if you countdown to 0 on a uint, it will go into an infinite loop because countdown underflows at 0 rather than -1, whereas dec does not. And it works fine for uint8 or uint16, just not uint. Seems like a bug.

**Comment by RedBeard0531** [comment]
@Araq fixing this shouldn't lead to a slowdown if countdown for unsigned used the equivalent of the c goes-to operator:

```c
unsigned x = 100;
while (x-->0) {
    use(x);
}
```
