### ISSUE TITLE
Why don't ``asynchttpserver`` support request-body when ``put`` ``delete``?

### ISSUE THREAD

**Issue by tulayang** [nim-lang/Nim#4221]
I noticed that ``asynchttpserver`` only support **request-body** when ``post``:

```nim
if request.reqMethod == "post":
  ...
  if request.headers.hasKey("Content-Length"):
  ...
    request.body = await client.recv(contentLength)
```

And, I read [HTTP/1.1 Message Semantics](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#section-6.7) in particular. There said "Bodies on DELETE requests have no defined semantics.  Note that sending a body on a DELETE request might cause some existing implementations to reject the request.".

Why not support request-body when ``put`` or ``delete``?

**Comment by tulayang** [comment]
I mean that it will be trouble if I write a client or agent to communicate with some servers written by ``asynchttpserver`` or ``jester`` via RESTFul API.

JSON body is easy to handle. But I had to use a long url encoded by ``JSON`` (example: ``/resource?containers=["abc","def","ghr"]&...``), and decode on the response.

**Comment by Araq** [comment]
Oh god, don't work around it, create a PR that fixes it. You already found the section in the code. We don't mind patches. ;-)

**Comment by tulayang** [comment]
@Araq

OK. let's close this issure. :)
