### ISSUE TITLE
Include source code of examples into final user documentation

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#423]
The [nimrod examples](https://github.com/Araq/Nimrod/tree/master/examples) could be added to the final output documentation present on the website. This would be nice for users, but it would be also very nice for module docstrings, they could mention and hyperlink specific full examples rather than snippets for complex features. Also it would bring awareness to the examples directory which doesn't seem to be so much for highlighting a feature of the language and more as friendlier test case suite.

At the same time, the generated examples could point to the documentation of the procs they are using similar to the style of [the_hyperlink_vs_nimrod](https://github.com/gradha/the_hyperlink_vs_nimrod) if #422 is implemented.

**Comment by dom96** [comment]
We have a link to more examples on the front page now (Rosetta Code).
