### ISSUE TITLE
Var scope not respected in typed template declarations

### ISSUE THREAD

**Issue by mbaulch** [nim-lang/Nim#4234]
Compilation of
```nim
proc f(): bool = true

template t(impl: untyped): untyped =
  if f():
    impl

template t(i: int, impl: untyped): untyped = 
  if f():     
    impl

t:                  
  var s = 0             
t:                      
  var s = 1
```
fails with **test.nim(14, 7) Error: redefinition of 's'** while the code
```nim
proc f(): bool = true

template t(impl: untyped): untyped =
  if f():
    impl

template t(i: untyped, impl: untyped): untyped = 
  if f():     
    impl

t:                  
  var s = 0             
t:                      
  var s = 1
```
compiles successfully. the surrounding `if f():` should setup a local scope for `impl`, though of course it hasn't. Placing the template bodies in blocks doesn't help us as
```nim
proc f(): bool = true

template t(impl: untyped): untyped =
  block:
    if f():
      impl

template t(i: int, impl: untyped): untyped = 
  block:
    if f():   
      impl

t:                  
  var s = 0             
t:                      
  var s = 1      
```
fails with the same error. However, if we surround the template arguments with blocks:
```nim
proc f(): bool = true

template t(impl: untyped): untyped =
  if f():
    impl

template t(i: int, impl: untyped): untyped = 
  if f():
    impl

t:                  
  block:
    var s = 0           
t:                      
  block:
    var s = 1    
```
then the code compiles successfully.

**Comment by mbaulch** [comment]
**Additional note**
The following code should generate the same output as the first version above. As stated, the first version won't compile, but this code will:
```nim
proc f(): bool = true

template t(impl: untyped): untyped =
  if f():
    impl

t:
  var s = 0
t:
  var s = 1
```
This compiler bug seems tied to template (or more general?) overloading resolution. This agrees with the stack trace leading up to the failed addDecl call (which fails due to addUniqueSym returning false) :
```
nim.nim(115)             nim
nim.nim(71)              handleCmdLine
main.nim(253)            mainCommand
main.nim(64)             commandCompileToC
modules.nim(227)         compileProject
modules.nim(172)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
sem.nim(463)             myProcess
sem.nim(435)             semStmtAndGenerateGenerics
semstmts.nim(1521)       semStmt
semexprs.nim(870)        semExprNoType
semexprs.nim(2289)       semExpr
semexprs.nim(853)        semDirectOp
semexprs.nim(687)        semOverloadedCallAnalyseEffects
semcall.nim(343)         semOverloadedCall
semcall.nim(155)         resolveOverloads
semcall.nim(70)          pickBestCandidate
sigmatch.nim(1717)       matches
sigmatch.nim(1674)       matchesAux
sigmatch.nim(1514)       prepareOperand
semexprs.nim(26)         semOperand
semexprs.nim(2382)       semExpr
semstmts.nim(1475)       semStmtList
semexprs.nim(2384)       semExpr
semstmts.nim(477)        semVarOrLet
lookups.nim(198)         addInterfaceDecl
lookups.nim(166)         addDecl
...
```
*Note: the compiler doesn't crash. I generated this trace manually from where the error (wrongRedefinition) was called.*

**Comment by Araq** [comment]
There is no bug here, the capabilities to undo symbol table manipulations in overloading resolution are limited and that's documented behavior.

**Comment by mbaulch** [comment]
Okay. Re-reading the documentation, I still can't find a clear reference to this.

In the [Nim Manual (Typed vs untyped parameters)](http://nim-lang.org/docs/manual.html#templates-typed-vs-untyped-parameters) it says
> An untyped parameter means that symbol lookups and type resolution is not performed before the expression is passed to the template.

which I took to mean symbol lookups and type resolution for *untyped arguments*, not for *all arguments* to the template call. This is, I assume, where the behaviour is documented?

Anyway, thanks for your explanation. I think I now understand.
