### ISSUE TITLE
generic method can't be declared "base"

### ISSUE THREAD

**Issue by shaunc** [nim-lang/Nim#4246]
The following gives an error:

```nim
type
  B = object of RootObj

  D = object of B

method foo[T](obj: B, t: T) {.base.} =
  quit "override!"

method foo[T](obj: D, t: T) =
  echo "got ", $t

let obj = D()
let baseObj = B(obj)
baseObj.foo("bar")

```

> t.nim(17, 8) template/generic instantiation from here
> t.nim(9, 31) Error: invalid pragma: base

However, it also fails if `{.base.}` is omitted:

> t.nim(9, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
> override!
> Error: execution of an external program failed: '/Volumes/Macintosh_HD/Users/shauncutts/src/patdisc.nim/patdisc/t '

**Comment by Araq** [comment]
This now works.
