### ISSUE TITLE
Make pegs module compatible with javascript backend

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4247]
It would be nice to have a regex-like library working consistently across targets. Pegs seems to be the best candidate, since it is pure.

Right now there are two problems I see:
1. `transformFile` uses `readFile`, which is missing in JS. Easily solved by wrapping the whole proc in `when`.
2. After that the module compiles, but fails for even the most basic cases. E.g. this throws an exception:

``` nim
import pegs

assert "x".match(peg"x")
```

**Comment by hlaaftana** [comment]
Pegs compiles fine now and that example works. If any issues come up using pegs on JS those should be reported independently and this should be closed.

**Comment by timotheecour** [comment]
* snippet given works as of 9384f7ad35aa36a22b31d7541254e89890d6cec2 but `nim js -r tests/stdlib/tpegs.nim` fails
* `nim js -r tests/stdlib/tpegs.nim` works as of https://github.com/nim-lang/Nim/pull/14095 but it needed to change the test for that to work
* if https://github.com/nim-lang/Nim/pull/14134 is merged, the test doesn't need to change
