### ISSUE TITLE
Add rsplit, partition and rpartition functions to strutils

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4251]
See also #4218.

Python has four split functions for strings: `split`, `rsplit`, `partition` and `rpartition`.  The difference between `split` and `partition` is in principle is that `partition` includes the separators in the results (in practice it also only splits once).

```python
#!/usr/bin/python
print("ab;cd;ef".split(";", maxsplit=1))
# Prints ["ab", "cd;ef"]
print("ab;cd;ef".partition(";")) # maxsplit is always 1 in python for partition for some reason
# Prints ["ab", ";", "cd;ef"]
```

The difference between `split` and `rsplit` (or `partition` and `rpartition`) only make sense when the `maxsplit` option is provided:

```python
#!/usr/bin/python
print("ab;cd;ef".split(";", maxsplit=1))
# Prints ["ab", "cd;ef"]
print("ab;cd;ef".rsplit(";", maxsplit=1))
# Prints ["ab;cd", "ef"]
```

These functions are all very useful and it would be good to include them in `strutils.nim`.  I don't think it is necessarily required to implement `partition` and `rpartition` as separate functions: there could simply be a `keepseparators` argument to `split` and `rsplit`, something like this:

```nim
var str = "ab;cd;ef;gh"
doAssert str.split(";") == @["ab", "cd", "ef", "gh"]
doAssert str.split(";", maxsplit=1) == @["ab", "cd;ef;gh"]
doAssert str.rsplit(";") == @["ab", "cd", "ef", "gh"]
doAssert str.rsplit(";", maxsplit=1) == @["ab;cd;ef", "gh"]
doAssert str.split(";", maxsplit=1, keepseparators=true) == @["ab", ";", "cd;ef;gh"]
doAssert str.rsplit(";", maxsplit=1, keepseparators=true) == @["ab;cd;ef", ";", "gh"]
```

**Comment by jyapayne** [comment]
@Araq This should be closed now due to c9c4b6c41d9465599f4a627c09fe626cab727270.
