### ISSUE TITLE
RFC: should startsWith and endsWith work with characters?

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4252]
From a consistency perspective, it seems logical to me that you can do this:

```nim
doAssert "abc".startsWith("a") # works
doAssert "abc".endsWith("c") # works
doAssert "abc".startsWith('a') # compile error
doAssert "abc".endsWith('c') # compile error
```

The latter can easily be achieved with:

```nim
doAssert "abc"[0] == 'a'
var s = "abc"
doAssert s[s.high] == 'c'
```

however, this feels a bit more messy to me and doesn't as obviously show the intention.

**Comment by dom96** [comment]
Yeah, make a PR please :)
