### ISSUE TITLE
Very minor error in json documentation

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4255]
> `proc pretty(node: JsonNode; indent = 2): string {.raises: [], tags: [].}`
Converts node to its JSON Representation, with indentation and on multiple lines.

> `proc toUgly(result: var string; node: JsonNode) {.raises: [], tags: [].}`
Converts node to its JSON Representation, without regard for human readability. Meant to improve $ string conversion performance.

> This provides higher efficiency than the `toPretty` procedure as it does not attempt to format the resulting JSON to make it human readable.

Note the comment about "the `toPretty` procedure", whereas there is no such thing (it's called `pretty`).

**Comment by Araq** [comment]
Please create PRs right away for these minor things. :-)

**Comment by abudden** [comment]
Having just opened up the code to have a look at this, I noticed there is a `toPretty` function but it is hidden.  At the moment there is:

```nim
proc toPretty # hidden
proc pretty # public, but just calls toPretty
proc toUgly # public
```

Am I right in assuming there's a naming convention thing going on here that is the reason for `pretty`'s existence?  If so, should I also be renaming `toUgly` as `ugly`?

**Comment by dom96** [comment]
``pretty`` returns a string whereas ``toUgly`` takes a `var string` as a param. I guess that's why the difference in naming exists.

**Comment by dom96** [comment]
Just s/toPretty/pretty/ in the docs. It might also be useful to define a `ugly` proc.

**Comment by abudden** [comment]
I've sent a pull request with the comment changes.  I wondered about implementing an `ugly` proc, but it would be absolutely identical to the existing `$` proc, so is arguably unnecessary.  I must admit that as a user I would more likely look for a function like `ugly` (or `toJsonString`) than `$` but that's probably because I'm not sufficiently used to Nim.

I'm not entirely clear on the purpose of `toUgly` over `ugly` (with the result passed back as a `var` arg rather than a return value), but with `$` it's probably not a problem.

**Comment by dom96** [comment]
> I'm not entirely clear on the purpose of toUgly over ugly (with the result passed back as a var arg rather than a return value), but with $ it's probably not a problem.

I guess it's a bit more efficient because it reuses an existing string.
