### ISSUE TITLE
Problem with ref objects inheritance and operator overloading

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4267]
This example fails:

```nim
type
  DataObj = ref object of RootObj
    id: int
  ChildObj = ref object of DataObj
    str: string

proc new(id: int, str: string): ChildObj =
  result.new
  result.id = id
  result.str = str

method `==`(o1, o2: DataObj): bool =
  o1.id == o2.id

let o1 = new(1, "a")
let o2 = new(1, "b")

# Here is assertion error
assert o1 == o2
```

How can I define the equality operator for DataObj hierarchy?

**Comment by Parashurama** [comment]
I think it has to do with multi-methods. There was some talk to remove them from Nim, but I'm not sure of its status.
You can make it work like by casting the second operand to its base type.
```nim
assert o1 == DataObj(o2)
```

**Comment by Araq** [comment]
I can see no bug here. The compiler prefers the generic == over your == which requires 2 implicit downcasts.
