### ISSUE TITLE
os.walkFiles yields directories

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4280]
I saw this behaviour on Mac OS X with ``compiler/*`` as the argument. Is this expected behaviour?

**Comment by Araq** [comment]
I doubt it.

**Comment by dom96** [comment]
> I doubt it.

Still doubt it? https://github.com/nim-lang/Nim/pull/4352 ;)

**Comment by dom96** [comment]
BTW see my warning in the PR: https://github.com/nim-lang/Nim/pull/4352#issuecomment-226642610
