### ISSUE TITLE
Http header values are converted to lowercase

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4286]
This is not correct http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive and breaks any client that relies on custom information in headers, as well as `Authorization` and CORS headers.

See the note here https://github.com/nim-lang/Nim/commit/cc80eac84b2f778a6a34d9c088e9e88c3a62c0bb for a longer discussion

**Comment by dom96** [comment]
This should be fixed now.
