### ISSUE TITLE
Docs: Publish `httpcore` docs

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/Nim#4287]
`httpclient` links to http://nim-lang.org/docs/httpcore.html which is missing.

I'd be happy to build the docs myself and submit a PR, but unfortunately I couldn't find the relevant instruction or sample in the repo.

**Comment by moigagoo** [comment]
@dom96 "Source" links from http://nim-lang.org/docs/httpcore.html point to 404s. Incorrect URL are produced: https://github.com/nim-lang/Nim/tree/master/lib/pure/lib/pure/httpcore.nim

**Comment by dom96** [comment]
@moigagoo I think that's something @Araq will fix in 0.14.2 :)
