### ISSUE TITLE
Local variable clashes with imported template

### ISSUE THREAD

**Issue by mbaulch** [nim-lang/Nim#4290]
Affects Nim 0.13.0, 0.14.0. The compiler gets confused and won't resolve the template:
`main.nim`:

``` nim
import foo

let t = 1

t: discard
```

`foo.nim`:

``` nim
template t*(body: untyped): untyped = body
```

Compiling, we get the error:

`
main.nim(5, 4) Error: expression 'discard' has no type (or is ambiguous)
`

If we change `main.nim` to:

``` nim
import foo

let t = 1

t:
  if true: discard
  var X = [1, 2, 3]
  echo "A B C"
```

the error becomes:

```
main.nim(6, 3) Error: expression '
  if true: discard
  var X = [1, 2, 3]
  echo ["A B C"]' has no type (or is ambiguous)
```

Expected behaviour is that `t` (local integer) is ignored and `t` (template, from `foo`) is called. Alternatively, the error message should say that `t` is ambiguous--not that its (untyped anyway!) parameter has no type. 
_Note: The same issue occurs if the template takes multiple parameters._

**Comment by Araq** [comment]
Why is that a bug? Why not choose different local names?

**Comment by mbaulch** [comment]
Thinking about this more, I don't think there's a choice. Such overloading of `t` is taking things too far. It should definitely result in an error. I agree with you about the choice of names.

As I said:
> Alternatively, the error message should say that t is ambiguous--not that its (untyped anyway!) parameter has no type.

Tellling us **the passed block has no type** is a very cryptic way of saying **the template itself clashes with a locally defined var**. A better error message is warranted, surely?

A suggested error message (for the first example):
```
main.nim(5, 1) Error: ambiguous reference. Both foo.t and t match for 't'.
```

**Comment by narimiran** [comment]
> Why is that a bug? Why not choose different local names?

> Such overloading of `t` is taking things too far. It should definitely result in an error. 

Can we then agree that you shouldn't use the same name for different things, and close this?

**Comment by Araq** [comment]
There is definitely something weird with the scoping going on, but it's been reported a couple of times so I'm closing this one.
