### ISSUE TITLE
varargs conversion proc can not be called if private

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#4291]
a.nim

``` nim
proc privateStringify(s: string): string = s # <--- Private converter
proc variadicProc*(v: varargs[string, privateStringify]) = discard # <--- Public function that uses privateStringify
```

b.nim

``` nim
import a
variadicProc("hi")
```

```
$ nim c b.nim
.../b.nim(2, 14) Error: attempting to call undeclared routine: 'privateStringify'
```

**Comment by Araq** [comment]
I can see no bug here. What's the point of hiding privateStringify when I need to overload it anyway for my types?

**Comment by yglukhov** [comment]
In my case i wanted to override stringification for strings.
```nim
proc safeStringify[T](v: T): string = $v
proc safeStringify(v: string): string =
  if v.isNil: "(nil)"
  else: v
proc myLog(args: varargs[string, safeStringify]) = blabla
```
So basically my safeStringify covers all possible cases, and there's nothing to overload. But i tend to agree with you, that this is probably a rare usecase, and may be worked around by making the safeStringify public. If you don't see a nice way to solve this issue, feel free to close it.

**Comment by narimiran** [comment]
> If you don't see a nice way to solve this issue, feel free to close it.

Since there were no (nice) solutions in the past two years, can this be closed?
