### ISSUE TITLE
Can't use `💩` as identifier

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#4296]
```nim
💩 = "123"
echo 💩
```
fails to compile with `test.nim(1, 1) Error: undeclared identifier: '💩'`

**Comment by kirbyfan64** [comment]
http://nshipster.com/nscalendarunityear/

**Comment by flaviut** [comment]
@kirbyfan64 That's exactly what prompted me to try it out!

**Comment by ephja** [comment]
You just forgot to declare it with `var` or `let`, just as the error message indicates.

**Comment by flaviut** [comment]
Too much Python lately, sorry! 😬
