### ISSUE TITLE
Feature Request: Adding something like Haskell's typeclasses or Rust's traits

### ISSUE THREAD

**Issue by NebulaFox** [nim-lang/Nim#4297]
I have been using Nim for a couple of days now so forgive me if this comes across as a lack of understanding of the Nim langage, but I feel that Nim could benefit from something like Haskell's typeclasses or Rust's traits. Nim supports generics but it appears it does not have any way of restricting or reasoning what the generic type `T` is. I do get the impression that the closest way of "restricting" the generic type `T` is done with duck typing. If this is the case, then something like Haskell's typeclasses would be a good fit for Nim. Not only would it give a container of procedures that need to be implemented, but it can also give the generic type `T` more meaning. 

As an example, if I create a type `T` that walks and talks like a sequence, I should be able to use any procedure in the sequtils module, but that is not possible as the type system will not allow it. Hence, if I make my type `T` support the sequence typeclass/trait then I should get a load of stuff for free, like fold, map, filter, so on.

**Comment by Varriount** [comment]
You mean [concepts](http://nim-lang.org/docs/manual.html#generics-concepts)?

**Comment by NebulaFox** [comment]
Interesting. The example shows how _concepts_ will be implemented but not used. Since the complier is written in Nim, I would like help get concepts implemented and usable.
