### ISSUE TITLE
when statement doesn't verify syntax

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4301]
```nim
when false:
  "blah blah blah blah..."
  vasdar i = 0sasdsa
  i = "string value - must throw an error"
```

Compiles fine.

**Comment by kirbyfan64** [comment]
I don't think this is a bad thing. `when` is frequently used for "commenting out" code. My guess is that `vasdar i = ...` is parsed as a macro call with an assignment statement as the argument?

**Comment by Araq** [comment]
The thing that shouldn't parse is `` 0sasdsa``  (int literal immediately followed by an identifier). That's a lexer bug.

**Comment by dom96** [comment]
Indeed. The body of the ``when`` needs to be _syntactically correct_.
