### ISSUE TITLE
stdlib test structure

### ISSUE THREAD

**Issue by StrongRef** [nim-lang/Nim#4304]
[Guidelines](https://github.com/nim-lang/Nim/blob/devel/contributing.rst) says that tests for stdlib should occur under isMainModule within the same file.

If this is the case, how about moving the assertions within _Nim/tests/stdlib/*_ into isMainModule of each file (e.g. tstrutil.nim => strutils.nim)?

However, is this the best way to structure tests?
How about using the unittest module?

I could help by improving tests and moving things around if we decide on a solution. I think that tests for a given file should either be within the same file under isMainModule or as a separate file (preferred).

**Comment by Araq** [comment]
I dislike the unittest module and so don't advocate its usage. It's way too complex for what it does.

> I could help by improving tests and moving things around if we decide on a solution.

I think most tests are fine as they are now. Improvements in the testing infrastructure should be:

* Improve testament to fail after timeouts. Individual tests should be able to set its timeouts (longer running GC tests)
* Run tests in parallel to speed up the test-suite.
* Perhaps test some benchmarks and ensure no performance degradations happen.
