### ISSUE TITLE
split proc in strutils inconsistent for set[char]

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/Nim#4305]
For example:

```nim
import strutils
echo ":test:stuff:".split(':', maxsplit=1)
echo ":test:stuff:".split(":", maxsplit=1)
echo " test stuff ".split(Whitespace, maxsplit=1)
```

Outputs:
```nim
@["", "test:stuff:"]
@["", "test:stuff:"]
@["test", "stuff "]
```

I can create a pull request for this once #4276 is absorbed :)

**Comment by Araq** [comment]
Well it's inconsistent, but quite useful. Split with set[char] is almost always used for whitespace and who wants leading/trailing whitespace?

**Comment by Varriount** [comment]
While I do agree that it is convenient for *that use case*, it's going to trip up people who decide they need to split on more than one character and go from `split(..., ":")` to `split(..., {':', ';'})`. 

Additionally, it's easy enough to re-implement this behavior by adding 'strip', whereas the alternative cannot be achieved without a new version of the strip procedure.

**Comment by jyapayne** [comment]
@Araq, I think that the functionality you're talking about might be useful under a different procedure name. I agree that it's useful to strip out all characters specified like how the current test performs:

```nim
let s = " this   is     an example   "
doAssert s.split() == @["this", "is", "an", "example"]
```

However, this is inconsistent with the other procs and the assert should be expecting something like this:

```nim
doAssert s.split() == @["", "this", "", "", "is", "", "", "", "an", "example", ""]
```

Which, I agree, is very difficult to work with if you don't want any extra blank strings. Maybe a new proc called `stripSplit`, or something similar, could exist that would replicate the functionality you mentioned for strings, chars, and set[char]. What do you think?

**Comment by Araq** [comment]
Seems overkill to me, let's just fix the existing ``split`` for set[char] and hope it doesn't break too much. And document this breaking change!

**Comment by dom96** [comment]
For whitespace split the rule should be that calling ``s.split(" ").join(" ") == s``. So is the current ``split`` procedure wrong?

**Comment by jyapayne** [comment]
The two `split` procs using `string` and `char` work that way. `split` with `set[char]` does not.

```nim
var s = "   whitespace  is    not   cool"
assert s.split(" ").join(" ") == s
assert s.split(' ').join(" ") == s
assert s.split({' '}).join(" ") == s # This fails
# s == "whitespace is not cool"
```

**Comment by dom96** [comment]
That's good :)
