### ISSUE TITLE
--listFullPaths has no effect on runtime errors.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#4307]
nim --listFullPaths is inconsistent right now.
Compile time errors have an absolute filepath while runtime errors only have the filename.

```nim
proc main() =
    raise newException(ValueError, "msg!")

main()
```
called with nim c -r --listFullPaths test.nim results in
```
test.nim(5)    test
test.nim(3)    main
Error: unhandled exception: msg! [ValueError]
Error: execution of an external program failed: '/tmp/test.nim '
```
Having the full path available for runtime error, could make easier integeration with IDE and text editor for a goto error functionality.

**Comment by Araq** [comment]
--listFullPaths is totally the wrong option for this feature though. Maybe ``-d:excessiveStackTraces``.

**Comment by Parashurama** [comment]
It would depend on how you interpret the name. 'excessiveStackTraces' is a little negative, no. :)
I will look at how stacktraces are implemented (nimFrame and friends I think). 
But one problem I can already foresee is potential size bloat, if for each frame I add the file full path.

**Comment by Araq** [comment]
Yeah but the alternative is to make your tooling smarter... Thinking about it, which language implementation uses full paths in stack traces?

**Comment by Parashurama** [comment]
Python, that I know of. But anyway I just finished implementing this functionality. PR  to follow.
