### ISSUE TITLE
Is Nim the right language for me? Does it utilize multiple cores?

### ISSUE THREAD

**Issue by Dillybob92** [nim-lang/Nim#4315]
Hey everyone!

The entire reason why I am moving to Nim is because on node, we have to utilize "multiple instances", and then utilize Redis to share memory (and also for the Pub Sub System).  Which is fine! I had no problem doing that, and it's  a fairly easy way to scale.

However, let's say 1000 Websocket connections are active on an Xeon E3. 500 Players are in 83 games (6 players each). Each player is moving around the map and sending socket data to the other 5 players in their respective game. [This is not including Player Skills, Dropping an Item, Chatting, Monster Loot drops, etc, etc].

With nodejs, I would have to split these players up on multiple nodes and then either use Redis` Pub Sub to notify each time a player moves [since they will be on different node instances] -- (which is way too much overhead). **OR** through a Unix Socket (IPC)... or just simply transfer that user to that instance before joining the game. 

The reason I ask is because I made a similar topic in the Reddit golang sub weeks ago. And they said using "goroutines and channels" would be necessary. Then, I got a message from someone saying "Nim would do all that stuff for you".

The problem is though, I really love Nim's syntax and want to switch. I am just not sure how many connections "1 instance" can handle on a Nim TCP/Websocket Server.

Do we need to spin up multiple Nim instances, or just 1, and communicate through IPC? This is assuming Nim handles utilizing multiple cores in the background if we do use IPC. If that makes sense, I'm kind of lost, but thanks!

**Comment by Varriount** [comment]
*Any* system of processes will end up using multiple cores when run on a modern multitasking operating system.

Currently Nim has a very capable *single-threaded* asynchronous IO framework. This means that a single main thread can handle multiple connections (much like Python's Twisted or Tornado modules). Progress is being made on a multi-threaded version though - I just don't know how far along it is.

In addition, Nim has some very effective threading mechanisms (close in convenience to Go's capabilities). Unlike Python (and Ruby, I think), Nim is not limited by a global interpreter lock, meaning it can achieve true multithreading.This would allow delegating CPU intensive tasks to other threads.

Of course, you can also use the low-level socket capabilities with the multithreading capabilities.

Of course, you can make use of the the

**Comment by Dillybob92** [comment]
@Varriount  Thank you! Looks like Nim seems very promising and I will give it a try!

**Comment by andreaferretti** [comment]
I think this can be closed, as the question has been answered
