### ISSUE TITLE
streams lib read/write procedures are platform-dependent

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4322]
Currently, streams.nim provides read/write procedures that depend on the endianness of the current platform. It is not suitable for use in networking or, in general, whenever the data can be read/written on different machines.
Similar libraries in other languages either provide guarantee that data is written with certain endianness or provide both LE and BE read/write procedures.

**Comment by narimiran** [comment]
Superseded by https://github.com/nim-lang/RFCs/issues/27, which has more (general) discussion.
