### ISSUE TITLE
Weird/broken error message on ambiguous module/type usage

### ISSUE THREAD

**Issue by mcampbell** [nim-lang/Nim#4324]
Name a file "set.nim", and in it put:

`var x: set[int16]`

This is invalid due to the ambiguous use of `set` (the file/module name vs the system type).  But, the error message is:

`Error: Error: ambiguous identifier: 'set' --use system.set or .set`

The "`..or .set`" section of the error appears to be incorrect.

**Comment by nc-x** [comment]
The code works fine now. There is no error.
