### ISSUE TITLE
Let closures to have names.

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#4332]
Currently its very hard to debug bugs in asynchronous programs. It will be easier if some changes will be made to "asyncdispatch.nim" and "C code generator".

**Generator**
Currently closure names looks like `HEX3Aanonymous_185129_3886262122`, it would be nice to have names like `Closure[Parent procedure name]_185129_3886262122`.
Currently closure environment variable name looks like `HEX3Aenv_185197_3886262122`, it would be nice to have names like `[Procedure name]Env_185197_3886262122`.

**asyncdispatch.nim**
Is it possible to make "anonymous" procs in generated stacktrace, not to be so "anonymous"?

**Comment by Clyybber** [comment]
This has been fixed with https://github.com/nim-lang/Nim/commit/c743b2969f9e7c922cbeadab983a84389953fb24 and https://github.com/nim-lang/Nim/commit/bc179ccc3f3c0df8b0c725b477c7cfeefaef4594
