### ISSUE TITLE
Cannot close file opened async

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4334]
It seems that closing a file opened with `openAsync` fails. Saving this example

```nim
import asyncdispatch, asyncfile

proc test(path: string) {.async.} =
  let f = openAsync(path)
  try:
    close(f)
  except:
    let e = getCurrentException()
    echo e.msg

waitFor test("test.nim")
```

as `test.nim` and then running `nim c -r test` reports `Operation not permitted`.

All this running under Ubuntu 15.04 using latest Nim devel (commit 5e8646583decc45f820f4d3a1f326d23d9396d9d)

**Comment by dom96** [comment]
Could be due to this https://github.com/nim-lang/Nim/commit/fb4ff86ad666bbb21ccc07d7bd5fd4a3cdd09d56 ?

**Comment by andreaferretti** [comment]
Dunno. But are there not tests in place for asyncfile?

**Comment by cheatfate** [comment]
@dom96, mostly because of this:
[selectors.nim:135](https://github.com/nim-lang/Nim/blob/devel/lib/pure/selectors.nim#L135)
```
  proc unregister*(s: var Selector, fd: SocketHandle) =
    if epoll_ctl(s.epollFD, EPOLL_CTL_DEL, fd, nil) != 0:
      let err = osLastError()
      if err.cint notin {ENOENT, EBADF}:
        # TODO: Why do we sometimes get an EBADF? Is this normal?
        raiseOSError(err)
    s.fds.del(fd)
```
But to avoid this bug i think it must be:
```
  proc unregister*(s: var Selector, fd: SocketHandle) =
    if s.fds[fd].events != {}:
      if epoll_ctl(s.epollFD, EPOLL_CTL_DEL, fd, nil) != 0:
        let err = osLastError()
        if err.cint notin {ENOENT, EBADF}:
          # TODO: Why do we sometimes get an EBADF? Is this normal?
          raiseOSError(err)
    s.fds.del(fd)

```

Because there no operations was made on this file, descriptor was not registered in epoll, and when you tried to delete it from epoll... error happens...

**Comment by andreaferretti** [comment]
I do not understand fully, but if you add the line

```nim
let contents = await f.readAll
```

the exception is still raised.

**Comment by cheatfate** [comment]
@andreaferretti there 2 ways :)
1. i will explain you (hard way).
2. you will patch your selectors.nim (easy way).

And some easy explanations. readAll() uses read() which after one successful call makes call to selectors.nim:update() which call epoll_ctl(s.epollFD, EPOLL_CTL_DEL, fd, nil) because there no callbacks registered. So when you exit from await f.readAll(), your descriptor was already unregistered from epoll.

**Comment by cheatfate** [comment]
@andreaferretti but if you really want, i can make more wide explanation.

**Comment by cheatfate** [comment]
@andreaferretti is patch works for you?

**Comment by andreaferretti** [comment]
Let me try

**Comment by andreaferretti** [comment]
@cheatfate Yes, it seems to work fine with the modification you proposed

**Comment by cheatfate** [comment]
@andreaferretti try not use readAll() because its current implementation is too expensive, it makes reads in cycle of:
1. register in epoll
2. epoll_wait()
3. read()
4. unregister from epoll()

but must be:
1. epoll_wait()
2. read()

**Comment by andreaferretti** [comment]
So, what do you suggest instead to read the whole content of a file?

**Comment by dom96** [comment]
The bigger (unfortunately) problem with ``asyncfile`` is that it's not always async (I think on Linux for example). But depending on your use cases it's "good enough".

I guess the ``readAll`` proc could retrieve the file size and then call ``read(fileSize)`` to read everything at once. That's the only way I see of making it more efficient.

**Comment by andreaferretti** [comment]
My use case is just serving static files in Rosencrantz. I am planning to implement streaming files using chunked encoding, but for now I just support serving the whole file at once

**Comment by dom96** [comment]
Then it's fine. It will work and we can fix performance problems later without changes to your code.

**Comment by cheatfate** [comment]
If you want to be effective try to use [sendfile()](http://man7.org/linux/man-pages/man2/sendfile.2.html)

**Comment by cheatfate** [comment]
@andreaferretti and i think you now about HTTP expiration fields, because asynchttpserver and i think jester don't support it.

**Comment by andreaferretti** [comment]
@cheatfate The problem of using `sendfile` or `epoll` is that Rosencrantz would then only work on Linux, unlike `asynchttpserver`. This is (one of the reasons) why I am building on top of `asynchttpserver`.

About headers: the guiding philosophy of Rosencrantz is to provide HTTP combinators that allow to compose whatever response you want. I may provide helpers to fill expiration headers, but I will not set those fields - or any other - for the user, nor do content negotiation, etc. See [this](http://andreaferretti.github.io/rosencrantz/) for a longer explanation
