### ISSUE TITLE
case matching on set[E] where E is enum

### ISSUE THREAD

**Issue by mbaulch** [nim-lang/Nim#4338]
Wouldn't it be nice if we could define

``` nim
type E = enum
  A, B, C
```

and then, for example,

``` nim
let e: set[E] = ...
case e
  of {A}: doCaseA()
  of {A, B}: doCaseAB()
  of {}: doCaseEmpty()
  else: doCaseOther()
```

There are workarounds for accomplishing this, although all have a performance and syntactic overhead. As a quick (and slightly hackish) alternative, we could add a 'magic' proc to _system_ that exposes the bit-pattern of an enum value.

It would be wonderful if the case statement understood sets properly, though. I can't see any reason the compiler couldn't reduce this to an int lookup at compile time. Am I missing something?

EDIT: Perhaps we can match on set[T] for general T?

**Comment by Araq** [comment]
'case' needs to be rewritten to 'if - elif' that uses the overloaded ==

**Comment by mbaulch** [comment]
Of course, that's an acceptable alternative for now. It won't however, compile to a branch/jump table AFAIK. This seems like a good opportunity for optimisation and (arguably) code clarity.

Enum sets are probably the only set type for which the branch table could be generated (via C's switch), from what I can see. intX, uintX and char sets would need to be compiled like you say to if/elif/... and such. Optionally, more optimised codegen could be deployed for those cases.

Not suggesting we'd need this for 1.0, though. 'One day' is fine with me.

Would this feature create semantic issues that I've missed?

**Comment by Araq** [comment]
clang optimizes 'if - elif' chains into jump tables on its own, no need to nanny the optimizer.

**Comment by mbaulch** [comment]
That may be true. A goal of Nim (AFAIK) is to be as portable as possible. Clang isn't suitable for all architectures (or tasks).

It's puzzling that `case` matches on
- `int`: yet not on `set[E]` (for `E` enum), which has a similar internal representation
- `string`: yet not on `set[int8]`, which has a similar internal representation
- etc.

Whether `case` exists for reasons of style, performance, or both; I don't understand why it's incompatible with `set`.

**Comment by Araq** [comment]
This can now be done with the experimental ``match`` case statement macros.

**Comment by awr1** [comment]
@Araq is the `match` stuff documented anywhere?

**Comment by Araq** [comment]
Sure, https://nim-lang.org/docs/manual.html#macros-case-statement-macros
