### ISSUE TITLE
deepCopy() on a recursive structure mangles structure

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4339]
I am using Nim self-built from git 07d7d35d99526283. I have nimyaml 0.5.1.

I run this program:

    import yaml

    type Mirror = ref object
        tag:int
        other:array[0..1, Mirror]

    var m1 = Mirror(tag:1)
    var m2 = Mirror(tag:2)
    var m3 = Mirror(tag:3)

    m1.other[0] = m2; m1.other[1] = m3
    m2.other[0] = m1; m2.other[1] = m3
    m3.other[0] = m1; m3.other[1] = m2

    for i in 1..3:
        echo i
        var f = newFileStream("mirror" & $i & ".yaml", fmWrite)
        dump(m1, f)
        f.close()

        var mx : Mirror; mx.deepCopy(m1)
        m1 = mx

**Observed behavior**:

This program creates a structure of three objects which all reference each other. It deep-copies twice, and serializes the original, plus each of the deep copies. The first deep copy differs from the original. Some of the objects are duplicated within the structures. The second deep copy is the same as the first deep copy. Unless yaml is confused, it appears that deepCopy mangles recursive structures, but will not mangle structures that were themselves created by deepCopy.

I tested with several different structures. With a two-object structure, I witnessed no mangling. With a more complicated structure I got the same mangling behavior as with the 3-object test above (mangled structure but only on the first deepcopy).

**Expected behavior**:

Either deepCopy should work with recursive data structures, or the limitations should be documented ( http://nim-lang.org/docs/system.html#deepCopy,T,T mentions no limitations ).

**Comment by Araq** [comment]
It is supposed to work with cyclic structures.

**Comment by Araq** [comment]
I think this was caused due to some corruption that has been fixed. This program works fine:

```nim

type Mirror = ref object
  tag: int
  other: array[0..1, Mirror]

var m1 = Mirror(tag:1)
var m2 = Mirror(tag:2)
var m3 = Mirror(tag:3)

m1.other[0] = m2; m1.other[1] = m3
m2.other[0] = m1; m2.other[1] = m3
m3.other[0] = m1; m3.other[1] = m2

for i in 1..30000:
  echo i
  var mx: Mirror; mx.deepCopy(m1)
  echo mx.tag, " ", cast[int](mx)
  echo mx.other[0].tag, " ", cast[int](mx.other[0])
  echo mx.other[1].tag, " ", cast[int](mx.other[1])
  m1 = mx
```

Please reopen if the problem still exists.
