### ISSUE TITLE
Windows: MSVC linker error

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#4343]
Compiling this **example.nim** file:
```nim
import os
```
gives the following linker error:
```
stdlib_math.obj : error LNK2019: unresolved external symbol _round referenced in function @round_109063_1009420244@12
````
Nim version: ```Nim Compiler Version 0.14.3 (2016-06-15) [Windows: i386]```
OS: ```Windows Vista 64-bit```
C compiler and linker (MSVC 2010): 
```
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Microsoft (R) Incremental Linker Version 10.00.40219.01
```

**Comment by Araq** [comment]
Seems like MS doesn't know about C's round function.

**Comment by matkuki** [comment]
MSDN docs say only MSVC 2013 and higher have round, roundf, roundl.

**Comment by matkuki** [comment]
I'm on Vista which cannot install MSVC 2012 or higher.
Can this issue be fixed?

**Comment by Araq** [comment]
Implement math.round differently for MSVC then and create a PR.

**Comment by matkuki** [comment]
Please check the PR[https://github.com/nim-lang/Nim/pull/4362].

**Comment by matkuki** [comment]
Thanks!
