### ISSUE TITLE
I can't call the random[T](x: Slice[T]): T

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/Nim#4353]
How should it be called? I'm using `int` as a type as an example.

```nim
import random
echo random[int](low(int) .. high(int))
```
Gives me:
```
a4.nim(2, 6) Error: expression 'random' has no type (or is ambiguous)
```
While with:

```nim
import random
proc foo[T](): T = random[T](low(T) .. high(T))
echo foo[int]()
```

I get:
```
Traceback (most recent call last)
a4.nim(3)                a4
a4.nim(2)                foo
random.nim(91)           random
system.nim(2532)         sysFatal
Error: unhandled exception: over- or underflow [OverflowError]
```

**Comment by endragor** [comment]
In the first case, `random` module name somehow clashes with the `random` procedure call. For example, writing it this way makes it work:
```nim
import random as r
echo random[int](low(int) .. high(int))
```
The overflow occurs because of how the procedure is implemented - it relies on the difference of slice bounds being of the same type as the bounds. Subtracting low[T] from high[T] for integers creates overflow.

**Comment by ReneSac** [comment]
That random module is a mess... 

Module names in nim are usually in plural because of that... 'randoms' is not exactly the same thing though, but is there a better alternative?

And for the second issue, that is why signed integers shouldn't be at the core of random modules... and the test suit for random is really lacking.

Besides that, the way used to clamp the range produces biased and low quality results, and the randomize() function 

And why is the range for random[T](x: Slice[T]) exclusive when the rest of the language uses inclusive ranges?

Anyway, we need non-backwards compatible fixes here...

**Comment by kirbyfan64** [comment]
> and the test suit for random is really lacking

Well, to be fair, it's hard to test *random* numbers...

**Comment by ReneSac** [comment]
First, you should test if you can actually use the functions.

And now that I'm trying to fix things and running the test, I discovered that the only test there is completely bogus. Ok, it will compile and run if unaltered. But if I insert a call to randomize before the loop the test will fail most of the time...

**Comment by Araq** [comment]
Hey, but it's better than what we used to have. :-)

**Comment by Varriount** [comment]
Considering how new the module is, I think some incompatible changes can be made (if nothing else, this module can be deprecated and renamed to something more sane, like 'rand'.

**Comment by ReneSac** [comment]
Araq: I disagree. Your comment made me remember that we had (and still have even if now the name clashes) [Blaxpirit's random](https://github.com/BlaXpirit/nim-random) that is waaay better than the current random lib. Why wasn't it incorporated to nim libs instead of this new unrevised module? Too big?

**Comment by dom96** [comment]
The idea was to bring BlaXpirit's random lib into the standard library at some point. Moving the ``random`` proc into a ``random`` module was just the beginning.

**Comment by dom96** [comment]
But yes, the library is rather large and we need to review/edit it to ensure that it fits into the standard library. Not always an easy task unfortunately.

**Comment by ReneSac** [comment]
Blindly re-implement BlaXpirit's lib functionality wrong and with a different and broken interface is the begining of bringing it to the stdlib? I'm sorry for being harsh, but this don't seem a right step to make.

I don't see why this random module had to be created, as it only increases the difficulty of merging BlaXpirit work as far as I can see. It ends up there is a good reason why BlaXpirit lib don't offers a `random[T](x: Slice[T]): T` proc (it need branches to handle all the cases correctly), and it offers more directly what I needed (the would be `random[T](low(T) .. high(T))`).

**Comment by Araq** [comment]
It doesn't blindly re-implement anything, it provides what ``math.nim`` used to provide.
