### ISSUE TITLE
Move out `oids` module from stdlib

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#4359]
@dom96 Is there a specific reason why `oids` module still resides in stdlib?

Also, it is non-compatible with JavaScript compilation target because of `endians` module which uses very low-level pointer-based functions (which looks actually very weird also).

I think that oids module has to be pulled out to a separate package, especially after `mongo` module was.

**Comment by dom96** [comment]
It's still a useful module if you want to generate an OID.

**Comment by SSPkrolik** [comment]
@dom96  Ah, okay, so what's the best way do you see to make it JS-compliant? I would like to fix it but I'm not sure if it is better to fix oids module itself or deal with endians module.

**Comment by dom96** [comment]
Good question. I actually needed it for the JS backend at some point also so I welcome making it JS-compliant. I think @Araq will need to help here, I'm not sure why ``oids`` requires so much pointer magic.

**Comment by dom96** [comment]
I guess @Araq didn't end up being much help. Please join IRC/Gitter to bother him for an answer if this is still important :)
