### ISSUE TITLE
Getting Segmentation Fault 11 when compiling code

### ISSUE THREAD

**Issue by NebulaFox** [nim-lang/Nim#4363]
When the following code is compiled with 0.14.2, I get a segmentation fault 11.

```
type
  Branch[T] = object
    name: string
    node: Tree[T]
  
  TreeKind {. pure .} = enum
    Leaf,
    Branch

  Tree[T] = object
    case kind: TreeKind
      of TreeKind.Leaf: value: T
      of TreeKind.Branch: branches: seq[Branch[T]]

proc newBranch[T](name: string, node: Tree[T]): Branch[T] =
  Branch[T](name: name, node: node)

proc newTreeLeaf[T](value: T): Tree[T] =
  Tree[T](kind: TreeKind.Leaf, value: value)

proc newTreeBranch[T](branches: openarray[Branch[T]], ): Branch[T] =
  Tree[T](kind: TreeKind.Branch, branches: @branches)

proc branches(): Branch[int] =
  newBranch("the answer", newTreeLeaf(42))

proc tree(): Tree[int] =
  newTreeBranch([branches()])
```

**Comment by Varriount** [comment]
Could you give us a bit more information, such as a stack trace?

**Comment by endragor** [comment]
I think providing sample is enough for such issues, isn't it? When segfault occurs, there is no stack trace generated, unless Nim was compiled in debug mode.

In this particular case, the problem is that two object types recursively include each other, causing infinite recursion inside the compiler.

@NebulaFox see [macros](http://nim-lang.org/docs/macros.html) module for the recommended way to define tree structure. It's enough to have single Node type in your case. The important part is that Node is declared as `ref` of an object type.

**Comment by NebulaFox** [comment]
@Varriount I am not exactly sure how I can provide a stack trace when it is failing and compile-time.

@endragor I find it interesting that two object types recursively including each other would be a problem, as the same code written in Rust will compile and run. But, thinking out load, if were to write a linked list in C I would be allocating and using pointers: more research is needed.

Either way, an informing error would be better than a segmentation fault 11.

**Comment by Varriount** [comment]
@endragor In this case, use of only object types is mitigated by the use of a sequence type.
@NebulaFox `koch boot -d:release --stacktrace:on --linetrace:on` will give an optimized binary with stack traces, which is what I personally use.

**Comment by Varriount** [comment]
@NebulaFox I've submitted a (tentative) compiler fix at #4369. I'm no compiler expert, so I'm not sure that it's correct (I mean, it solve your problem, but it may not be the right way to solve it).

**Comment by NebulaFox** [comment]
@Varriount Thanks, also thanks for the explanation on C/C++ stance, it was very helpful. In the Rust version of the code it is doing to the same thing as the Nim code, where Nim has seq, I am using Vec in Rust.

**Comment by Varriount** [comment]
@NebulaFox My PR was accepted and pulled into the main development branch. Your example doesn't quite work though - the return type for newTreeBranch needs to be changed to 'Tree'.
