### ISSUE TITLE
tables.clear() is broken for Table[A, B]

### ISSUE THREAD

**Issue by kierdavis** [nim-lang/Nim#4365]
Compiling:

``` nim
import tables
var t = initTable[int, string]()
t.clear()
```

with the latest Nim devel gives this error:

```
testclear.nim(3, 2) template/generic instantiation from here
lib/pure/collections/tableimpl.nim(145, 14) Error: 't.data[i].hcode' cannot be assigned to
```

The definition of `clear` is:

``` nim
proc clear*[A, B](t: Table[A, B] | TableRef[A, B]) =
  # ...
```

so it can be seen that problem is that the proc attempts to mutate its argument, which is of type `Table[A, B]`. Changing this type to `var Table[A, B]` ought to fix the problem.

Presumably this also applies to `OrderedTable[A, B]` and `CountTable[A]`.

**Comment by Yardanico** [comment]
@Araq, @kierdavis fixed in latest devel
