### ISSUE TITLE
tables.`[]=`[A](t: var CountTable[A]; key: A; val: int) should support val = 0

### ISSUE THREAD

**Issue by vktec** [nim-lang/Nim#4366]
See this code example:

``` nim
import tables

var ct = initCountTable[string]()

# Create an entry
ct["foo"] = 40 # Works fine
# Now lets reset it. No del method, so we'll just set it to 0
ct["foo"] = 0 # 0 < val  [AssertionError]
```

The expression for the assertion should be `0 <= val` rather than `0 < val`.
I can make a pull request if this would be useful, however, as it is such a minor change, I thought it might be simpler for this to be done by a contributor.

**Comment by vktec** [comment]
For anyone facing the same issue, here is the workaround I am currently using:

```nim
import tables

var ct = initCountTable[string]()

# Create an entry
ct["foo"] = 40 # Works fine
# Workaround
ct.inc("foo", -ct["foo"])
```

**Comment by konqoro** [comment]
This also works:
ct["foo"] -= 40
