### ISSUE TITLE
Provide documentation by type as well as by module

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4374]
Considering the pseudo-object-orientation methodology that is supported by Nim, all of the following are valid operations on strings:

``` nim
var s = "abcdef"
s.toUpper() # defined in strutils.nim
s.high() # defined in system.nim
s.expandTabs(4) # defined in strmisc.nim
```

Similarly, here are some things you can do with `seq`:

``` nim
var t = @[1, 2, 3, 4, 5, 6]
t.add(7) # system.nim
t.pop() # system.nim
t.filter(proc(x: int): x != 3) # sequtils.nim
t.reverse() # algorithm.nim
```

From a user's point of view, it's not always obvious to me where I should be looking for the a given procedure (or what it's called).  Tools like #3745 and #4218 are really useful but they're created manually.  The Documentation Index is useful, but it is difficult to use if you're not sure what the command is called (or whether it exists).  It would be great to have something in the standard documentation that is listed by type rather than by module, a bit like the [python string types function list](https://docs.python.org/2/library/stdtypes.html#string-methods) (although that isn't actually exhaustive).

In practice, without implementing (and maintaining) this manually, I suspect this is fairly difficult, but some obvious options are:
1. An alphabetical list of all procedures (and which module they're in) that have a seq/openArray as their first argument (and repeat for strings, arrays etc).
2. An additional command/pragma of some sort could be added into the documentation to say "include this in the overall string documentation".

Option 1 is likely to produce a lot of noise as there will be a lot of functions that (e.g.) take a string as a first argument but don't fit into the object-orientated function on a string approach (e.g. `re()` in `re.nim`).

Option 2 strikes me as a much better approach, although it will involve adding a pragma/documentation note into every relevant function.

Either of the above options would involve writing something to parse all of the standard library files and pull out the relevant documentation.

I haven't the first idea about how the documentation generation works, but I'd be more than happy to start ploughing through the standard library adding some sort of documentation note to indicate which type description page (if any) each procedure documentation should be added to.  Obviously to do that, I'd need someone's opinion on what that documentation note / pragma / something else should look like.

**Comment by Araq** [comment]
Great idea. I think I will add 'cat'  (short for category) to the RST based docgen. Then you can go crazy and add  ``.. cat:: string`` to the stdlib. Deal?

**Comment by abudden** [comment]
@Araq, sounds like a deal to me: I'm happy to work through the functions and try to add as much as I can.

For sequences / arrays, will there be a syntax for multiple categories (i.e. if a function works on arrays it takes `.. cat:: array`, if it works on sequences `.. cat:: seq` and if it works on open-arrays `.. cat:: seq/array`)?  I'm not sure whether this is really necessary, but it was just a thought.

**Comment by Araq** [comment]
In fact, no RST extension is required, use 
```
 `string`:cat: 
```

And then adapt the CSS so that ``<span class="cat">`` is not visible.

**Comment by abudden** [comment]
> And then adapt the CSS so that `<span class="cat">` is not visible.

Okay!  My CSS knowledge is close to zero, but that sounds just about within my limitations...

What about multiple categories (if you think they'll be required)?

**Comment by Araq** [comment]
The documentation supports grouping by type since years now.
