### ISSUE TITLE
Wrong behavior of "split" (proc and iterator)

### ISSUE THREAD

**Issue by oderwat** [nim-lang/Nim#4377]
It seems like  `split("",",")` returns an empty array but I believe it should return an array with one empty string as element.

Besides PHP, Javascript and Python split work like this there is also:

`split(",",",")` returning an array with two empty strings.
`split("a",",")` returning an array with one element string "a".

Ruby seems to deliver an empty result for everything which does not match at least once.

Thoughts?

**Comment by dom96** [comment]
Some discussion about this here: https://github.com/nim-lang/Nim/pull/4361#issuecomment-321972633

Indeed, this is not consistent with other languages. Should we change it?

Marking as high priority due to potential breaking change and RFC to foster discussion.

**Comment by FedericoCeratto** [comment]
Indeed this looks inconsistent:
```
assert split("--", "-") == @["", "", ""] 
assert split("-", "-") == @["", ""] 
assert split("  ", "-") == @["  "] 
assert split(" ", "-") == @[" "] 
assert split("", "-") == @[""]    # fails
```
