### ISSUE TITLE
posix module cleanup

### ISSUE THREAD

**Issue by ryu0** [nim-lang/Nim#4382]
As it stands, the POSIX module contains a lot of Linux specific pieces. Many of the constants are for Linux only, because they differ on other unix flavors such as FreeBSD; in particular the termios constants. Also, the POSIX module has APIs which are Linux specific such as epoll. At the very least, I think it needs to be cleaned up so that platform specific bits are isolated from the general POSIX bits. Thoughts?

**Comment by Araq** [comment]
These need to move to ``linux.nim``, yes.

**Comment by Araq** [comment]
I don't see any termios constants in posix.nim. Not do I see ``epoll``.

**Comment by ryu0** [comment]
I was referring to the entire posix subdirectory. termios in particular has constants that are taken directly from Linux, but that are not identical to the constants that FreeBSD uses.

**Comment by dom96** [comment]
@ryu0 Please consider moving these into linux.nim and creating a PR.

**Comment by dom96** [comment]
I believe this has been done to a good extent and can now be closed.
