### ISSUE TITLE
Manual links incorrect across sections

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4397]
I was going to simply do a pull-request for the one I'd noticed, but I've investigated a bit more and I don't really understand how it is all working (partly because I'm much more familiar with the foibles of markdown than those of reStructuredText), so I thought it better to raise an issue.

Go to http://nim-lang.org/docs/manual.html#procedures-method-call-syntax

At the bottom of that section is a link to "Limitations of the method call syntax", which links to 
http://nim-lang.org/docs/manual.html#limitations-of-the-method-call-syntax

Due to the structure of the manual source and (presumably) the way the links are generated, the correct link is http://nim-lang.org/docs/manual.html#templates-limitations-of-the-method-call-syntax (note the inclusion of `templates-` as this is in `templates.rst`).

There are many other examples of this: **most of the internal links in the manual seem to be incorrect**.  I've previously submitted pull requests #4283 and #4293 when I noticed some incorrect links - I think this is a more generic problem with the way the links are created and those specific fixes probably weren't the right way to go about it.

**Comment by Araq** [comment]
Afaict there is no deep underlying issue here. It's just that the algorithm for anchor generation changed.

**Comment by romanet** [comment]
There is similar broken anchor
In section [/docs/manual.html#overloading-resolution-varargs-matching](http://nim-lang.org/docs/manual.html#overloading-resolution-varargs-matching])
[/doc/manual/type_rel.txt last line](https://github.com/nim-lang/Nim/blob/devel/doc/manual/type_rel.txt#L393) liked to ` manual.html#varargs `

```
Varargs matching
----------------

See `Varargs`_.
```

I think it meant to be `#types-varargs`

```
Varargs matching
----------------

See `Varargs <#types-varargs>`_.
```
