### ISSUE TITLE
Problem with sets in devel

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4412]
```nim
import jester, asyncdispatch, emerald

proc index(content: string) {.html_templ.} =
  html(lang = "en"):
    head:
      title: "Index"
    body:
      put content

routes:
  get "/":
    var
      s = newStringStream()
      templ = newIndex()
    templ.content = "Hello, world!"
    templ.render(s)
    resp s.data

runForever()
```

Needs current git master from jester, as latest nimble version does not work with Nim 0.14.x. emerald is the latest nimble version. This code produces the following error:

```
lib/pure/collections/sets.nim(282, 43) Error: cannot generate VM code for type(s.data[i].key)
```

Works with 0.14.2.

**Comment by mbaulch** [comment]
It looks like https://github.com/nim-lang/Nim/commit/5f83e869fa000598ab38866485dc8e58dd7d90d0 caused the issue.

**Comment by mbaulch** [comment]
The compile-time VM doesn't fully implement the Nim language. Some features are missing. I think the change to `collections/sets` (noted above) adds reliance on compile-time only features. Specifically, the limitations of type introspection.

To illustrate the issue with a smaller (and less macro-laden) example, consider
```nim
proc default[T](t: typedesc[T]): T {.inline.} = discard

static:
  var x = default(type(0))
```

which gives:

`test.nim(4, 24) Error: cannot generate VM code for type(0)`

For an example of similar code that compiles, consider:
```nim
proc default[T](t: typedesc[T]): T {.inline.} = discard

static:
  var x: type(0)
  var y = default(int)
```
