### ISSUE TITLE
Better error message on mismatched types to procedure calls

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#4416]
The current error message for when you mismatch parameter types in procedure calls is not great. Currently it reports the types as they are without any regard to compatible types. One example of this would be passing nil where the procedure expects a pointer to something. The error might look like this:

```
file.nim(0,0) Error: type mismatch: got (nil, <more parameters>)
but expected one of:
proc procedure(ptr Type,<more parameters>)
```

The error is not the nil but rather one of the other parameters which might not be obvious. This makes it hard for unfamiliar users to find which of the parameters is actually mismatched. To make matters worse having converters doesn't influence the error message at all. Types with converters should preferably be reported as their compatible type and not their original type in this error message. For example when working with C FFI one might run into the issue of converting ints of various kinds, but since the converters are not part of the error message it might be hard to see which type does not have a converter.

**Comment by yglukhov** [comment]
Somehow related to #1761?

**Comment by yglukhov** [comment]
Also related to #1104.

**Comment by Araq** [comment]
This has been improved quite a bit.
