### ISSUE TITLE
Change console encoding to UTF-8 by default

### ISSUE THREAD

**Issue by miere43** [nim-lang/Nim#4417]
Reasons:
* You can't print anything non-English to console because it's encoded to UTF-8 by Nim:
```nim
echo "привет"
```
=>
```
╨┐╤А╨╕╨▓╨╡╤В
```
* Exception messages forwarded from Windows cannot be expressed too:
```
Error: unhandled exception: ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗.
 [OSError]
```

To fix this stuff you need to manually change console encoding yourself:
```nim
when defined(windows):
  proc setConsoleOutputCP(codepage: cint): cint
    {.stdcall, dynlib: "kernel32", importc: "SetConsoleOutputCP".}
  proc getConsoleOutputCP(): cint
    {.stdcall, dynlib: "kernel32", importc: "GetConsoleOutputCP".}

  let g_originalOutputCP = getConsoleOutputCP()
  # 65001 - utf-8 codepage
  discard setConsoleOutputCP(65001)

echo "привет"

when defined(windows):
  # Restore original codepage
  discard setConsoleOutputCP(g_originalOutputCP)
```
=>
```
привет
```
```
Error: unhandled exception: Не удается найти указанный файл.
 [OSError]
```

**Comment by shawnye** [comment]
It seems that XP is not supported.

**Comment by Araq** [comment]
Create a PR please. Even Windows 10 still has this fucked up behaviour. Ridiculous.

**Comment by nxshock** [comment]
I could try to create a pull request, but I'm not sure in which file we need to add the code. This should be before the start of the main procedure (set codepage to unicode), then after the completion (return previous codepage). Please suggest.

**Comment by miere43** [comment]
@nxshock, I'll take care of it, no don't worry.
