### ISSUE TITLE
Nimble package list needs categorisation

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4418]
On http://nim-lang.org/docs/lib.html#nimble it states:

> There are currently 351 unofficial packages in the Nimble package repository.

Finding anything in there when you're not exactly sure what you're looking for or whether anything will be there is a bit like looking for the proverbial needle in a haystack.  The libraries included as standard in Nim are categorised.  It would be really nice if something similar were done with the Nimble libraries.

I'd guess this would involve firstly going through the list of existing packages and trying to figure out some sensible groups, then adding categories to the [Packages.json](https://github.com/nim-lang/packages/blob/master/packages.json) file and updating the [script that generates the documentation](https://github.com/nim-lang/Nim/blob/devel/web/nimblepkglist.nim) and finally asking people who submit new packages to include a category.

**Comment by abudden** [comment]
I guess to make it less likely that there are issues with mis-spelled categories, it might be better to nest packages.json as:

```js
{
  "category1": [
    {
      "name": "argument_parser",
      //...
    },
    {
      "name": "something",
      //...
    }
  ],
  "category2": [
    {
      "name": "somethingelse",
      //...
    }
  ],
//...
```

**Comment by abudden** [comment]
I'm happy to have a go at a couple of pull-requests for this (one for the generator and one for the package list), but I thought I ought to get the okay from the maintainers before making this change (along with any suggestions for categories if there are strong opinions: my thoughts were initially to base the categories on those for the standard library).

**Comment by andreaferretti** [comment]
You may find [this unofficial tool](http://nimble-explorer.com/) useful. It uses tags that are declared when submitting packages to Nimble.

**Comment by abudden** [comment]
@andreaferretti thanks for that - it does indeed look useful.  I'd looked at the tags and thought it would be a sensible thing to use when searching, but it is still quite nice to be able to browse a list in a meaningful way when you want to determine what is available (like you can with the standard library categories at the moment).

**Comment by dom96** [comment]
IMO tags are enough and can already model categories well. You can easily explore Nimble packages using tags via Nimble, the only missing piece is a packages website (an issue for that exists [here](https://github.com/nim-lang/nimble/issues/219) already) that makes it easier via the web browser.

I will close this issue since it's not directly related to Nim and we already have a Nimble issue that tracks a related feature.
