### ISSUE TITLE
using osPaths.parentDir(fn) results in Error: invalid pragma: rtl

### ISSUE THREAD

**Issue by apahl** [nim-lang/Nim#4424]
Running this code in Nim 0.14.2 on Ubuntu 16.04:
```Nim
import osPaths
var fn = "/home/xxx/dev/nim/somefile.csv"
var dir = splitPaths(fn)
echo(dir)
```
gives this error: `lib/pure/ospaths.nim(173, 19) Error: invalid pragma: rtl`

**Comment by Araq** [comment]
It's a bug, yes, but you're supposed to use ``import os``.

**Comment by apahl** [comment]
Ok, I was not aware of that.
`os.splitPath(fn)` does work. Thanks for the fast answer.

Kind regards,
Axel
