### ISSUE TITLE
Template parameters can't be redefined

### ISSUE THREAD

**Issue by mbaulch** [nim-lang/Nim#4430]
Is this expected? A few examples follow.

Doesn't compile:
```nim
template t(i: int) =
  var i = i
  
t(0)
```
> test.nim(4, 3) Error: identifier expected, but found '0'

Compiles:
```nim
template t(i: int) =
  var j = i
  
t(0)
```
Also compiles:
```nim
proc t(i: int) =
  var i = i
  
t(0)
```

**Comment by Varriount** [comment]
This isn't really a bug so much as implementation-defined behavior. In your example, `var i = i` is being transformed into `var 0 = 0`.

**Comment by mbaulch** [comment]
Thought about it. You're right. Good point. Closing issue.
