### ISSUE TITLE
converter floatToInt not usable in countup() function

### ISSUE THREAD

**Issue by apahl** [nim-lang/Nim#4431]
Hi, for Nim 0.14.2 on Ubuntu 16.04, this minimal converter example results in a compilation error:

``` Nim
converter floatToInt(x: float): int =
  x.toInt

for i in countup(1, 4.2):
  echo("Test")
```

`test.nim(4, 17) template/generic instantiation from here
lib/system.nim(1891, 9) Error: for a 'var' type a variable needs to be passed`

**Comment by apahl** [comment]
Maybe related to #3503.

**Comment by apahl** [comment]
If you write a countup iterator that only can use ints, the converter works:
```Nim
converter floatToInt(x: float): int =
 x.toInt

iterator countupn(a, b: int): int =
  var res = a
  while res <= b:
    yield res
    inc(res)

var x = 4.3

for _ in countupn(1, x):
  echo("Test")
```
Output:
```
Test
Test
Test
Test
```

**Comment by PMunch** [comment]
After some digging around and checking I don't understand why the function isn't simply something like:

```
iterator countupn*[S, T](a: S, b: T, step = 1): T {.inline.} =
  var
    res:int = a
    cmp:int = b
    yld:T = res
  while res <= cmp:
    yield yld
    inc(res)
```

This way anything that is convertible to an int (including custom converters, apparently those don't get called in T(variable) calls) can be passed in, as long as an int can also converted back to that type (again also including custom converters).
