### ISSUE TITLE
case ... of does not work with variables

### ISSUE THREAD

**Issue by hendi** [nim-lang/Nim#4434]
`import posix` declares some variables, e.g. `var  EAI_AGAIN* {.importc, header: "<netdb.h>".}: cint`.

The following code does not work:

```
import posix

var ret: cint = -3

case ret
of EAI_AGAIN: echo "some error"
else: echo "unknown error"
```

and fails with

`test.nim(6, 4) Error: cannot evaluate at compile time: EAI_AGAIN`

**Comment by Araq** [comment]
That's simply not supported. Sorry.
