### ISSUE TITLE
Problems with Nim on embedded system

### ISSUE THREAD

**Issue by gdelazzari** [nim-lang/Nim#4437]
I'm trying to use Nim on an STM32 project. I wrote some C functions to initialize the MCU, set the status of an LED, delay some time etc... and, after compiling a simple Nim program that imports these functions and blinks the LED, I got everything working. Then I tried to create an object that represents the LED (to test the memory allocation). This is my code:
```nim
proc MCU_init() {.importc, header: "<mcuLib.h>", cdecl.}
proc MCU_setLed(status: int) {.importc, header: "<mcuLib.h>", cdecl.}
proc MCU_HAL_Delay(ms: int) {.importc, header: "<mcuLib.h>", cdecl.}

type LED = ref object of RootObj
  status: int

method updateStatus(this: LED) {.base.} =
  MCU_setLed(this.status)

method toggleStatus(this: LED) {.base.} =
  if this.status == 0:
    this.status = 1
  else:
    this.status = 0

method setStatus(this: LED, status: int) {.base.} =
  this.status = status

MCU_init()

var myLed: LED

myLed.setStatus(0)
myLed.updateStatus()

while true:
  myLed.toggleStatus()
  myLed.updateStatus()
  MCU_HAL_Delay(75);
```

I also have my panicoverride.nim implemented:
```nim
proc printf(frmt: cstring) {.varargs, importc, header: "<printf.h>", cdecl.}
proc MCU_panic() {.importc, header: "<mcuLib.h>", cdecl.}

{.push stack_trace: off, profiler:off.}

proc rawoutput(s: string) =
  printf("%s\n", s)

proc panic(s: string) =
  rawoutput(s)
  MCU_panic()

{.pop.}
```

However, if I compile with
`nim cc -c --cpu=arm --d:release --gc:none --os:standalone --deadCodeElim:on main.nim`
the compilation is successful but the LED doesn't blink. I looked at the generated files and the `myLed` object doesn't get allocated in memory. In fact, if I manually add an `malloc()` line at the beginning of the `main()` of the generated .c files, everything works fine. I also tried with `--d:useMalloc` but it makes no difference. I tried with the GC enabled (removing the `--gc:none`) option, but then the Nim compiler gives me this:
`lib/system/alloc.nim(327, 13) Error: undeclared identifier: 'stdout'`

How am I supposed to get Nim to use `malloc()` and allocate memory for my objects?

**Comment by Varriount** [comment]
Your example never calls 'new' on the LED object (which is a reference type allocated on the heap), so it makes sense that memory is never allocated.

I don't know how complex this system is, but unless it provides the standard mmap facilities, automatic memory management isn't going to work - you'll have to use manual memory management. The manual memory management procedures are in system.nim; 'create', and 'alloc' are the two primary manual memory management procedures.

system.nim has the manual memory procedures - you'll probably be using 'create' or 'alloc'

**Comment by gdelazzari** [comment]
Ok that was my fault, I forgot to instantiate a new object. Now I have
```nim
var myLed: LED = LED()
```
But now the compiler says
`Error: system module needs 'newObj'`
Which is understandable, it probably expects me to tell him how my platform is supposed to allocate memory for a new object (correct me if I'm wrong). I also noticed something like this when working with strings: the compiler said that `copyString` was needed. So now the question is: how do I implement this kind of functions? I tried searching on the web but I couldn't find any documentation...

By the way you're right, I don't have memory management, I have just `malloc()` that increases the heap size and returns the pointer to the new block allocated. Nothing more.

**Comment by Araq** [comment]
> So now the question is: how do I implement this kind of functions? I tried searching on the web but I couldn't find any documentation...

You don't need to reimplement it, either you port the core of Nim to your device (which means reusing the existing implementation) or you don't use the feature at all. ;-)  Join us on IRC for further details, it's hard to give general advice when it comes to embedded devices.

Don't use ``--gc:none``, gc:none is about to be replaced with ``gc:stack``.

**Comment by Araq** [comment]
No feedback. Closing.
