### ISSUE TITLE
Allow to declare .importc variables with `let`

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4441]
Currently, if you `.importc`/`.importcpp` a variable with `let`, you get `'let' symbol requires an initialization` error. However, it makes a lot of sense to import C/C++ static constants as `let` rather than `var`.

**Comment by mbaulch** [comment]
For this to make sense, the compiler would have to check that `importcpp` does indeed refer to a static constant. At present, I don't think the Nim compiler performs semantic checking of C (or C++) at any such level of sophistication.

Why not just import each static constant as a var --private to the module-- and wrap it with a publicly defined constant. For instance:
```nim
var barVar {.header: "foo.h", importc: "BAR".}: cint
let bar*: cint = barVar
```
If brevity is desired, this could be streamlined with a template or macro.

**Comment by endragor** [comment]
@mbaulch I think it is up to the wrapper creator to make sure they wrap constants as constants and variables as variables. As of now you can wrap constant with `var` and it doesn't make much sense, too - you would be able to change it in Nim, but get an error on C/C++ compilation stage.

I agree there is a workaround and this is not a severe issue.

**Comment by Araq** [comment]
You can also import constants as nullary functions instead: 

```nim
proc foo(): cint {.importcpp: "FOO@".}
```

**Comment by Varriount** [comment]
Has that particular feature been documented?

**Comment by mbaulch** [comment]
I'm not sure it really needs documentation. It's a clever use of the
importcpp pattern language that (I confess) I handn't thought of.

{.importcpp: "...".} can be used with the C backend. Perhaps _that_ should
be documented. Using it this way does worry me a bit, though.

**Comment by ringabout** [comment]
Now
```nim
let SYS_getrandom {.importc: "SYS_getrandom", header: "<sys/syscall.h>".}: clong
echo SYS_getrandom # prints 318
```
works

https://play.nim-lang.org/#ix=2PCj
