### ISSUE TITLE
Strange overload resolution failure

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#4442]
I could not come up with a minimalistic example, so here are the steps to reproduce:
```
git clone https://github.com/yglukhov/nimsl.git && cd nimsl && git checkout 5660cf2 && nim c -r test
```
Error:
```
nimsl/nimsl/emulation.nim(97, 32) Error: ambiguous call; both nimsl.newVec3(x: float32, y: float32, z: float32) and nimsl.newVec3(x: float32, y: float32, z: float32) match for: (float32, float32, int literal(0))
```
Note that both oveloaded candidates are actually the same proc.

**Comment by Araq** [comment]
This is a nimble setup problem or path problem. These are different symbols:

121818 Users/andreasrumpf-mac/.nimble/pkgs/nimsl-0.1/nimsl/nimsl.nim(76,5)
117997 Users/andreasrumpf-mac/projects/nimsl/nimsl/nimsl.nim(76,5)

The first number is the symbol ID.

**Comment by yglukhov** [comment]
Yup, sorry.
