### ISSUE TITLE
Simplified profiling

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#4451]
This code does make it easier to enable or disable profiling:

``` nim
when compileOption("profiler"):
  import nimprof
```

But it might not be such an obvious solution to everyone.

We could either document this pattern or perform this check in the `nimprof`module instead or import the module implicitly (by default) when profiling is enabled.

**Comment by genotrance** [comment]
Which one do we want? Updating the docs or updating the nimprof module?

**Comment by timotheecour** [comment]
@xflywind there must be a better way than https://github.com/nim-lang/Nim/pull/17627, a flag `--profiler` should be sufficient and not require changing the sources with
```nim
when compileOption("profiler"):
  import nimprof
```

note that we can do `--import:nimprof` but that's also not satisfying as adds an import in all modules.

The exact same situation happens with libbacktrace, currently requiring either editing sources with `import libbacktrace` or passing `--import:libbacktrace`; see  https://github.com/status-im/nim-libbacktrace/issues/12


how about:
* adding `--importmain:foo` flag to nim which only does the automatic import for the main module being compiled
* making --profiler imply --importmain:profiler`
* making -d:nimStackTraceOverride imply --importmain:libbacktrace -g` (refs https://github.com/status-im/nim-libbacktrace/issues/12)


=> followup in https://github.com/timotheecour/Nim/issues/688
