### ISSUE TITLE
 ambiguous call; both unicode.toLower(s: string) and strutils.toLower(s: string) match

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#4453]
```nim
import unicode,strutils

var  b : string = "Nim"
echo b.toLower()

Error: ambiguous call; both unicode.toLower(s: string) and strutils.toLower(s: string) match for: (string)

# Nim Compiler Version 0.14.3 (2016-07-06) [Linux: amd64]
# Copyright (c) 2006-2016 by Andreas Rumpf
# 
# git hash: 834c2abfd16b3ba20a4bee8920520a3e7583a4fe
# active boot switches: -d:release
# 
```

**Comment by Araq** [comment]
So?

**Comment by qqtop** [comment]
```nim

import unicode,strutils

var  b : string = "Nim"
echo b.toLower()

# Hint: operation successful (15656 lines compiled; 0.313 sec total; 19.004MiB; Release Build) [SuccessX]
# nim
# 
# 19:30:15 lxuser@linux-yrjr:/data4/NimStuff
# 1072 $ nim -v
# Nim Compiler Version 0.14.3 (2016-06-27) [Linux: amd64]
# Copyright (c) 2006-2016 by Andreas Rumpf
# 
# git hash: 38de553b86fd5f42c726da9bceb6828fb835eff5
# active boot switches: -d:release
```
No issues here  in a compiler build on 6/27, hence I assume something 
must have changed in the latest dev. version , which causes this error.

**Comment by yglukhov** [comment]
What probably Araq was trying to say is that's not an issue, because it's true that both modules define this function. `unicode.toLower` has been introduced recently. Either fully qualify your `toLower` call, or blacklist it from importing in one of the modules (in your case: `import unicode except toLower`)

**Comment by yglukhov** [comment]
But yes, that's a nice example of breaking change, when static overloading doesn't help because unicode string and non-unicode string are the same types.

**Comment by Araq** [comment]
I am fully aware of this breaking change. Maybe news.txt needs to be more explicit about it.
