### ISSUE TITLE
Compile time file reading/writing is broken when cross compiling (especially with standalone targets)

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [nim-lang/Nim#4457]
A few problems here:
Unfortunately, it appears that the separation of host and target gets eliminated in the standard library at compile time (which I guess sort of makes sense). However, on a standalone target, this means you can no longer `import os` as it will blow up due to undefined symbols.  ospaths is also unavailable due to an `invalid pragma: rtl` issue. 

Working around the ospaths issue (by including "system/inclrtl" on standalone builds), a nasty side effect comes to light: paths can no longer be reliably constructed as the standard library has no way to detect what os is building it. 

If one sticks with unix style paths it *technically* works as windows will accept them, but this is a workaround rather than a proper solution.

Araq has mentioned the need for something like 'static import', but I'm curious if there are other thoughts on this as it's a relatively irritating impediment when trying to build embedded system friendly bindings to existing C code.

**Comment by Araq** [comment]
> If one sticks with unix style paths it technically works as windows will accept them, but this is a workaround rather than a proper solution.

Fine solution for me. Except of course we need to fix ospaths so it always can be imported (if os.nim is not used).

**Comment by Jeff-Ciesielski** [comment]
Fair enough, as I work in linux/osx this solution works fine for me.  28940ce457e7a7f3e2d1d6cc0223bc0282ce509e solved the ospaths issue, so I'll close this issue.
