### ISSUE TITLE
Visual Studio 10.0 compiler errors, 12.0 warning

### ISSUE THREAD

**Issue by haferburg** [nim-lang/Nim#4459]
var myFile: File
    if myFile.open("w:/src/test.nim", fmRead):
      try:
        let s = readLine(myFile)
        echo s
      except IOError:
        echo "IOError :("
      finally:
        close(myFile)

causes output

    nimcache\greetings.c(471) : warning C4113: 'void (__cdecl *)()' differs in parameter lists from 'Globalmarkerproc56602'
    nimcache\greetings.c(472) : error C2275: 'NIM_BOOL' : illegal use of this type as an expression
        D:\coding\Nim-0.14.2\lib\nimbase.h(260) : see declaration of 'NIM_BOOL'

See https://gist.github.com/haferburg/25796c66926f81b2efb4862568d48977 for details.

With the Visual Studio 12.0 compiler it builds, but it still outputs that warning.

**Comment by shawnye** [comment]
I am using vc2008, and got the simular warning (Globalmarkerproc56202) with you (Globalmarkerproc56602).

**Comment by jangko** [comment]
there are two separate issues actually.
1. warning C4113 which is clear, proc signature mismatch
2. error C2275, VS2010 C compiler only support C89/C90 mode. all variables declaration must be at the beginning of a block/scope. Nim compiler generate function call before variable declaration therefore this error occur.
