### ISSUE TITLE
More descriptive error messages when DLL loading fails

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#4464]
Did someone have any issues with this? Because `getLastError` can be used on Windows and `dlerror` can be used on Posix. Are there any cases where the diagnostics are lacking?

At least "The specified module could not be found" and "%1 is not a valid Win32 application" (which is odd but the symbolic name is ERROR_BAD_EXE_FORMAT) might be raised on WIndows.

**Comment by ringabout** [comment]
Use 
```nim
let lib = load("nonexistant.dll")
assert lib != nil, "Error loading library"
```
