### ISSUE TITLE
Generic proc instantiation and tuple types

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4466]
This code:

``` nim
proc identity[T](t: T): T = t

proc doSomething[A, B](t: tuple[a: A, b: B]) = discard

discard identity((c: 1, d: 2))
# type mismatch here
doSomething(identity((1, 2)))
```

gives

```
Error: type mismatch: got (tuple[c: int, d: int])
but expected one of: 
proc doSomething(t: tuple[a: int, b: int])
```

Seems like generics for tuple types do not get instantiated if there already exists an instance for a type that the argument can be cast to. So when we do `identity((1, 2))`, the existing `identity` instance for `tuple[c: int, d: int]` is used (since (int, int) can be cast to tuple[c: int, d: int]).

**Comment by Araq** [comment]
Makes sense, doesn't it? ;-)
