### ISSUE TITLE
Cannot create type alias with template invocation on right side

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#4468]
```
type
  B = object
    field1: int

template foo(): expr =
  B

type
  A = foo()

var var1: A
var var2: foo()
var1 = var2
```

Should compile, but instead fails with:
`d.nim(15, 8) Error: type mismatch: got (B) but expected 'A = object'`

I'm not sure if templates/macros in type sections are supported or if they only work by accident. I would really glad if they were supported.

**Comment by Araq** [comment]
There is a subtle ambiguity in Nim's spec here that's hard to explain...

**Comment by andreaferretti** [comment]
Seems to work fine on devel

**Comment by TiberiumN** [comment]
Compiles for me, @dom96 maybe close?
