### ISSUE TITLE
Improve error message for redefinitions

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#447]
Given the file `variable_leaks.nim`:

```
include evil_leak

when isMainModule:
  let
    some_var = 2
```

And the file `evil_leak.nim`:

```
const
  SOME_VAR = "some var"
```

The compiler produces the following output:

```
$ nimrod c variable_leaks.nim 
variable_leaks.nim(5, 12) Error: redefinition of 'some_var'
```

It would help if the redefinition error could also point to the file/line where the original definition is, since a naive case sensitive grep would not find the source of the problem.

**Comment by Araq** [comment]
Still an issue.

**Comment by data-man** [comment]
> Still an issue.

Not reproduced on devel.

```nim
include evil_leak

echo SOME_VAR

when isMainModule:
  let
    some_var = 2

  echo some_var
```

**Comment by timotheecour** [comment]
@data-man what do you mean "Not reproduced on devel." ? see https://github.com/nim-lang/Nim/issues/8581

**Comment by data-man** [comment]
@timotheecour 

I mean that ```variable_leaks.nim(5, 12) Error: redefinition of 'some_var``` don't appears for me.
Now outputs:
```
some var
2
```

**Comment by Araq** [comment]
@data-man Yeah, the example is outdated but the issue is real.
