### ISSUE TITLE
Compiler crashes - various issues

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#4484]
I have created a repository where I'll be adding minor bugs in Nim:
https://github.com/zielmicha/nim-bugs

(I did this, instead of creating lots of issues in Nim repo, to reduce clutter)

**Comment by mbaulch** [comment]
Don't worry about submitting issues of _low importance_. That's what the label system is for. Eventually, when someone gets around to fixing these, I'm worried they'll be missed if they're not in the main issue tracker.

**Comment by Araq** [comment]
@mbaulch Zielmicha did it this way on my advice since even with the tagging in place, 760 open issues are hard to deal with.

**Comment by mbaulch** [comment]
Ok. Sorry, I didn't realise that. The issues, I suppose, shouldn't get lost as long as that repo stays alive and https://github.com/nim-lang/Nim/issues/4484#issue-165319183 points to it.

**Comment by krux02** [comment]
I tested all examples, they are all fixed by now.
