### ISSUE TITLE
Linking error - repeated symbols when splitting into modules

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4485]
I have tried splitting my [Emmy](https://github.com/unicredit/emmy) library into modules, thus moving from this version where everything is included

```nim
import sequtils, math, intsets, algorithm, macros, tables, bigints

include private/structures
include private/pairs
include private/modular
include private/operations
include private/tableops
include private/quotient
include private/polynomials
include private/linear
include private/primality
```

to this version, where everything is imported

```nim
import emmy/structures, emmy/pairs, emmy/modular, emmy/operations,
  emmy/tableops, emmy/quotient, emmy/polynomials, emmy/linear,
  emmy/primality

export structures, pairs, modular, operations, tableops, quotient,
  polynomials, linear, primality
```

and consequently adding relative imports between modules.

The first version works fine: one can see that by checking out the [master branch](https://github.com/unicredit/emmy/tree/master) and running `nimble tests`.

The one where I split everything into modules now fails to link: one can see that by checking out the [modules branch](https://github.com/unicredit/emmy/tree/modules) and running `nimble tests`.

It seems that by having the procedures defined in different modules, there are repeated symbols in the generated code, and the linker gets confused

The errors are really long, but they all look like

```
tests/nimcache/emmy_primality.o: In function `addInt':
/home/andrea/workspace/Nim/lib/system/arithm.nim:320: multiple definition of `T105763075_13'
tests/nimcache/emmy_primality.o:/home/andrea/workspace/Nim/lib/system/arithm.nim:320: first defined here
```

**Comment by mbaulch** [comment]
I don't think this code should compile. The `emmy/primality` module and others are defined in the `emmy` and `tests` directories, because of the `--path:.` flag passed by your `nimble tests` task. There are ways around this, but AFAIK there isn't a sensible way for the compiler to support such naming conflicts. Have proposed a fix https://github.com/nim-lang/Nim/pull/4495.

**Comment by andreaferretti** [comment]
Thank you, I did not realize that the issue was the test modules being named the same way as the core modules. This is enough to solve the problem for me: I can just rename the test modules to something else.

Still, there is something I do not understand: it seems to me that the core modules have absolute names such as `emmy/primality`, while the test ones are just `primality`. Should not there be some name mangling done by the compiler to ensure that these get compiled without ambiguity?

**Comment by mbaulch** [comment]
That's a good plan. If you're stuck for ideas, the Nim compiler tests use the `t` prefix; so `tprimality`, `tlinear` etc. would be consistent with that.

 `tests/primality.nim` defines a module called `primality` living in `emmy`: i.e. `emmy/primality`. The `tests` directory itself doesn't actually create a module. Both modules are trying to occupy the same point in the namespace. I'm not sure how mangling can help.

As @Araq said (in https://github.com/nim-lang/Nim/pull/4495#issuecomment-233172242):
> Filenames need to be unique per Nimble-package.
