### ISSUE TITLE
Consider "flags" pragma for enum which indicates flags enum

### ISSUE THREAD

**Issue by miere43** [nim-lang/Nim#4486]
Currently you have to write such boilerplate for each enum which should be used as flags:
```nim
type
  Meh = enum
    mWow = 1, mYay = 2, mOuch = 4, mMax = high(int) # or mMax = 8

proc `or`(a, b: Meh): Meh =
  (a.int or b.int).Meh

proc `and`(a, b: Meh): Meh =
  (a.int and b.int).Meh

proc `$`(x: Meh): string =
  $(x.int)
```
You have to do such naughty things to make stuff just work:
* implement `or` proc for bitwise OR.
* implement `and` proc for bitwise AND
* create super-high enum value `mMax` so `mYay or mOuch` does not throw RangeError.
* custom `$` proc because `mYay or mOuch` produce `0 (invalid data!)` (not even 6!)

I guess you can write awesome macro to do this stuff automatically, but its sad that such things are not available out of box.
What to do?
Any enum which has `{.flags.}` pragma attached to it gets this stuff:
* `or`, `and` and other bitwise procs implemented
* max available value is bitwise OR of all enum values.
* (optionally) `in`, `notin` procs
* `$` which outputs something like `mYay and mOuch` or just a number (compiler can resolve properly `$` call for normal and flags enum at compile-time for sure, fallback to normal `$` at runtime).

```nim
type
  Meh {.flags.} = enum
    mWow = 1, mYay = 2, mOuch = 4

var x = mWow or mYay
echo mYay in x # true
```

**Comment by Araq** [comment]
Nim has a superior solution builtin, it's called a ``set`` .

**Comment by Varriount** [comment]
For what it's worth, you can generate the procedures without even a macro by using templates:

```nimrod
template genFlagProcs(typ: untyped): untyped {.dirty.} =
  proc `or`(a, b: typ): typ =
    typ(a.int or b.int)
```

**Comment by miere43** [comment]
@Araq, okay, then how do I interface with some C proc that takes uint32 flags variable?
```nim
proc someProc*(flags: uint32) {.definedsomewhere.}

type
  Some {.size: sizeof(uint32).} = enum
    yush = 1, nah = 2
  SomeFlags = set[Some]

var flags = {yush, nah}

someProc(flags) # type mismatch obviously
someProc(uint32(flags)) # conversion from set[Some] to uint32 is invalid
```
I can make `someProc` to accept `SomeFlags` but how do I ensure that this set is marshaled as uint32?
Should I just make bunch of consts instead?

**Comment by Araq** [comment]
Use your imagination:

```nim

type
  Some {.size: sizeof(uint32).} = enum
    yush = 1, nah = 2
  SomeFlags = set[Some]

proc someProc*(flags: SomeFlags) {.definedsomewhere.}
```

**Comment by miere43** [comment]
...but I still can't use sets with imported procs :(
```nim
import winlean, dynlib

type
  KeyboardModifier* {.size: sizeof(uint32).} = enum
    modAlt = 0x0001, modControl = 0x0002, modShift = 0x0004,
    modNoRepeat = 0x4000
  KeyboardModifiers* = set[KeyboardModifier]

proc registerHotKey(hWnd: Handle, id: int, fsModifiers: KeyboardModifiers,
    vk: uint32): WINBOOL
  {.stdcall, dynlib: "user32", importc: "RegisterHotKey".}

var id = 1.int
var mods = {modAlt}
var key = 0x42.uint32
if registerHotKey(0.Handle, id, mods, key) == 0:
 echo getLastError() # => 1004 => ERROR_INVALID_FLAGS
else:
  echo "no errors"
```

**Comment by Araq** [comment]
Come on, use your head please. The compiler transforms ``val`` to ``1 shl val`` for ``set`` so your enum needs to reflect that.

```nim
KeyboardModifier* = enum
    modAlt = 0, modControl = 1, modShift = 2,
    modNoRepeat = 14
```

**Comment by miere43** [comment]
Sorry for being stupid, thank you, @Araq T_T
