### ISSUE TITLE
pragma {.error: "asdf"} inconsistent when used in a proc vs. top level

### ISSUE THREAD

**Issue by haferburg** [nim-lang/Nim#4487]
```
{.error: "asdf"} # Output: `Error: asdf`
proc f() =
  {.error: "asdf"} # Output: `Error: invalid pragma: error: "asdf"`
```

The output "invalid pragma" seems like a bug.

**Comment by cheatfate** [comment]
This is not a bug, please check [Nim Manual](http://nim-lang.org/docs/manual.html#pragmas-error-pragma).

**Comment by haferburg** [comment]
Ok, then I don't understand the manual. The wording is pretty vague. It should describe where you're allowed to use it, and what happens when you do.

**Comment by andreaferretti** [comment]
I agree it is not clear why this is not a bug. @cheatfate can you expand a little?

**Comment by bluenote10** [comment]
I ran into this problem despite just having re-read this section of the manual. Looks like a bug to me, because it would clearly make sense to use `error` in a proc context as well. Note that as a work-around you can use the `{.fatal: "my compiler error".}` message.

**Comment by nc-x** [comment]
Seems to work fine now.

**Comment by Araq** [comment]
Yup, we changed this.
