### ISSUE TITLE
Not found: docs/db_common.html

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#4492]
Module db_sqlite imports db_common according to http://nim-lang.org/docs/db_sqlite.html
But http://nim-lang.org/docs/db_common.html is not found.

**Comment by jlp765** [comment]
lib/pure/db_common.nim

but the other db_xxxx modules are 

lib/impure/db_xxxxxx

**Comment by Araq** [comment]
Finally fixed with upcoming release.
