### ISSUE TITLE
Feature request: application/library version

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#4512]
Existing applications and libraries often store their version in multiple locations: the .nimble file, a const in a module, a hardcoded string in documentation files.

It would be useful to introduce a standard way to store the version number in order to:
* remove the risk of having inconsistent version numbers across a project
* make the version number accessible to to the application/library and its consumers at runtime
* ...to Nimble
* ...to "nim doc"
* ...to external tools that don't know about Nim
* allow generating a list of versioned dependencies a project was built against (useful for security)

**Comment by FedericoCeratto** [comment]
One way to make the version available to external tools could be a "nimble project-version" command that parses the .nimble file (but this requires Nimble to be installed and can lead to some catch-22 issues on buildbots).
Additionally, the .nimble format allows grepping the version string (e.g. "^version ") but this would require freezing the format.

**Comment by andreaferretti** [comment]
There is already [nimble dump](https://github.com/nim-lang/nimble#nimble-dump) that parses nimble files and outputs them in ini format. The latter is easily parsed, even by grepping

**Comment by Araq** [comment]
The one place where the version should reside in should be the ``.nimble`` file. You can ``include`` it in your code to get the version. That was one motivation to make nimble support NimScript.
