### ISSUE TITLE
Allow internal documentation generation

### ISSUE THREAD

**Issue by mathsaey** [nim-lang/Nim#4517]
It is currently impossible to generate documentation for any type/procedure/... which is not marked as external.
Adding an `internal` flag to the docgen tools which generates documentation for every type/procedure/... which has a documentation string could be useful.

**Comment by Araq** [comment]
What's the point? The docs are for users of the exposed interface.

**Comment by mathsaey** [comment]
Documentation can also be useful to explore a new codebase without looking at the exact implementation. This can be very useful when you want to explore the overall structure of a file without diving into the specifics.

Other documentation systems such as doxygen provide features to document private members for exactly this reason.

**Comment by Araq** [comment]
You can also use an editor which supports code folding for this purpose ...

**Comment by mathsaey** [comment]
That does not offer you a bunch of nice rst features such as syntax highlighting for example code, tables, ...

**Comment by narimiran** [comment]
> What's the point?

Is this then `won't fix` label and can be closed, or have you changed your mind in the last two years?

**Comment by timotheecour** [comment]
there is now `--docInternal` see https://github.com/nim-lang/Nim/pull/10413 ; which is similar but could be extended for this
