### ISSUE TITLE
Sometimes 5 is less than 3

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#4518]
```nim
# Somewhere far away...
type MyObj = ref object
converter toMyObj(f: float): MyObj = MyObj.new()
converter toMyObj(f: int): MyObj = MyObj.new()

# The bug:
var five: float = 5
var three: int = 3
for i in 0 .. 10000000:
    doAssert(five > three) # This eventually fails.
```

**Comment by yglukhov** [comment]
Thoughts: maybe nim should not try to apply converters for generic arguments during overload resolution...

**Comment by Araq** [comment]
I don't see any bugs here. People love converters and want them to applied everywhere.

**Comment by yglukhov** [comment]
I understand that it works as expected by _you_ :). I also love converters, but not in this case, really. Also I suspect that disabling_converters_for_generics would not make converters any less powerful.

**Comment by yglukhov** [comment]
If you think we should remove `<` operator for refs, i must say that sometimes 3 is equal to 5...
```nim
type MyObj = ref object
converter toMyObj(f: float): MyObj = nil
converter toMyObj(f: int): MyObj = nil
var five: float = 5
var three: int = 3
for i in 0 .. 10000000:
    doAssert(five != three)
```

**Comment by krux02** [comment]
I think this is more a tooling problem, than anything else. Meaning, that one should see, where implicit conversions take place, and when they do take place, one should easily be able to see which converter gets applied. Similar to what ensime does in Scala.

**Comment by Araq** [comment]
I see no solution for this problem.

**Comment by dom96** [comment]
For future reference, the second example doesn't need the for loop:

```nim
type MyObj = ref object
converter toMyObj(f: float): MyObj = nil
converter toMyObj(f: int): MyObj = nil
var five: float = 5
var three: int = 3
doAssert(five != three)
```

Also fails.
