### ISSUE TITLE
Compiler segfaults on non-recursive code

### ISSUE THREAD

**Issue by mihirparadkar** [nim-lang/Nim#4524]
Compiler gives the following message on below minimal example

``` nim
const
  size* = 2

proc foo[N: static[int]](A: array[N, int]): int =
  result: int = A.high - A.low

var A: array[size, int] = [1, 2]
foo(A)
```

SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by Araq** [comment]
Fails for me with:

temp.nim(10, 35) Error: cannot generate code for: N

**Comment by andreaferretti** [comment]
Type `array` is difficult to work with in generic ways because it also accepts a static range - say `array[[1 .. 5], int]`.

One workaround that I always use is to declare my own type that only accepts a static size and work with that, like

```nim
const
  size* = 2

type Array[N: static[int]; T] = array[N, T]

proc foo[N: static[int]](A: Array[N, int]): int =
  A.high - A.low

var A = [1, 2]
echo foo(A)
```
