### ISSUE TITLE
Visual Studio 10 unresolved external symbol _trunc(should we support VS2010?)

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#4532]
while investigating #4459, I found this annoying thing. VS2010 cannot compile this code:

```nimrod
from math import trunc
echo trunc(1.0)
```

with error:
```text
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/stack:33554432
/out:f:\projects\bug\truncate.exe
f:\projects\bug\nimcache\stdlib_math.obj
f:\projects\bug\nimcache\stdlib_system.obj
f:\projects\bug\nimcache\truncate.obj
truncate.obj : error LNK2019: unresolved external symbol _trunc referenced in function _truncateInit000
f:\projects\bug\truncate.exe : fatal error LNK1120: 1 unresolved externals
Error: execution of an external program failed: 'cl.exe  /DEBUG /Zi /Fd"$projectName.pdb" /F33554432  /Fef:\projects\bug\truncate.exe  f:\projects\bug\nimcache\stdlib_math.obj f:\projects\bug\nimcache\stdlib_system.obj f:\projects\bug\nimcache\truncate.obj '
```

Because of this, VS2010 also cannot compile Nim compiler because Nim compiler in vmops.nim contains call to trunc, and in VS2010 math.h there is no trunc or truncf(they are C99 functions, and VS2010 don't support them.

Should we support VS2010, or support only VS2013 and above?

**Comment by Varriount** [comment]
Couldn't a conversion be used instead of trunc?

**Comment by jangko** [comment]
we can use conversion, but this is not the only issue with VS2010, the problem is should Nim generate C89 compatible code to support VS2010 or generate C99 code and leave VS2010 behind?

**Comment by Araq** [comment]
> should Nim generate C89 compatible code

Yes.
