### ISSUE TITLE
arguments of typed macro leak into outer scope

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#4547]
I was trying to implement a macro that transforms a value declaration into a lazy initialized variable, and I realized, that the ast that was passed into the macro, is not properly replaced by the result of the macro.

``` nim
import macros

# the macro itself is not really important
macro lazy(stmtList : typed) : untyped =
  let decl = stmtList[0]
  decl.expectKind nnkLetSection
  let name = $decl[0][0].symbol
  let call = decl[0][2].copy
  call.expectKind nnkCall
  let ident = newIdentNode("get" & name)

  result = quote do:
    var value : type(`call`)
    proc `ident`() : type(`call`) =
      if value.isNil:
        value = `call`
      value

  echo result.repr

type MyObject = object
  a,b: int    

# this part, the macro call and it's result (written in the comment below) is important
lazy:
  let y = new(MyObject)

#[
  var value: type(new(MyObject))
  proc gety(): type(new(MyObject)) =
    if value.isNil:
      value = new(MyObject)
    value    
]#

echo gety().a  # works and should work
echo gety().b  # works and should work
echo y.a       # identifier y should not exist anymore
echo y.b       # identifier y should not exist anymore
```

As you can see, the macro `lazy` has an argument with a let declaration `let y =`. But the let part is not part of the output of the macro anymore. Therefore the last two lines should refuse to compile, because there is no value `y` anymore. Instead the nim compiler accepts this without problems, but then generates invalid c code:

```
Error: execution of an external compiler program 'gcc -c  -w  -I/home/arne/proj/nim/Nim/lib -o /tmp/aporia/nimcache/a1.o /tmp/aporia/nimcache/a1.c' failed with exit code: 256

/tmp/aporia/nimcache/a1.c: In Funktion »a1Init000«:
/tmp/aporia/nimcache/a1.c:381:23: Fehler: »y_99211_899815572« nicht deklariert (erste Benutzung in dieser Funktion)
  LOC5 = nimIntToStr((*y_99211_899815572).a);
                       ^~~~~~~~~~~~~~~~~
/tmp/aporia/nimcache/a1.c:381:23: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
```

Another side effect is that an expression `let y = 28` after the macro call yields `Error: redefinition of 'y'` and I can't call the procedure `gety` just `y`.

redefinition of 'y'

**Comment by Araq** [comment]
Yes, symbol table modifications are not undone after the type matching process, hence you need to use ``untyped`` for code blocks. Not sure if we can fix this for v1.

**Comment by krux02** [comment]
just in case someone sees this one year later, it is still the same problem.

**Comment by krux02** [comment]
If we can't fix it, maybe we should document this broken behavior.

**Comment by metagn** [comment]
`Error: undeclared identifier: 'y'` is now given, likely since #15158
