### ISSUE TITLE
C-style cast syntax works :)

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#4557]
Consider the next code:
```nim
import macros

dumpTree:
  proc x() =
    let i = (int32)5.5
    let u = int32 3.5
```
The `i` variable declaration compiles and works good as type-cast, because it is parsed as a command syntax, which anyway looks quite weird :)

Can we consider it a bug or feature? :)

**Comment by Araq** [comment]
It's an unforeseen feature. I know about it for quite some time now though.
