### ISSUE TITLE
cannot export `!=` for user defined type

### ISSUE THREAD

**Issue by esheldon** [nim-lang/Nim#4560]
I can define a `!=` operator on my type, and it will work within the original
module. As a contrived but simple example, this works

```nim
type
    Test = object
        values: seq[int]

proc `!=`(t1, t2: Test): seq[bool] =
    newSeq(result,2)
    result[0] = t1.values[0] != t2.values[0]
    result[1] = t1.values[1] != t2.values[1]

proc makeTest*(data: seq[int]): Test =
    result.values = data

let t1 = makeTest(@[1,2])
let t2 = makeTest(@[1,2])

let comp = (t1 != t2)
echo(comp)
```

That gives @[false, false] as expected

However, if I try to export the `!=` op it fails. For example if I have a new
file to define these things called topdef.nim
```nim
type
    Test* = object
        values: seq[int]

proc `!=` *(t1, t2: Test): seq[bool] =
    newSeq(result,2)
    result[0] = t1.values[0] != t2.values[0]
    result[1] = t1.values[1] != t2.values[1]

proc makeTest*(data: seq[int]): Test =
    result.values = data
```

and import this and use it
```nim
import topdef

let t1 = makeTest(@[1,2])
let t2 = makeTest(@[1,2])

let comp = (t1 != t2)
echo(comp)
```

that one fails with the error
```
top.nim(20, 16) template/generic instantiation from here
lib/system.nim(343, 3) Error: type mismatch: got (seq[bool])
but expected one of: 
proc `not`(x: bool): bool
```

The issue seems to be that the `!=` op is defined as a template in system.nim.
If I instead over-ride `==` or other ops that are defined by `proc` in the
system module, it works fine.

**Comment by Araq** [comment]
Don't define a '!=' for your type. Define a '==' instead.

**Comment by esheldon** [comment]
I should have made it clear:  Just defining the `==` and letting the template use `not (x==y)` also does not work.  It gives the same error actually.

E.g. for the example above, if I go ahead and define `==` and  `not` for the sequence type this works
```nim
let test = not (t1 == t2)
```
but this does not
```nim
let test = t1 != t2
lib/system.nim(343, 3) Error: type mismatch: got (seq[bool])
but expected one of: 
proc `not`(x: bool): bool
```
so somehow in the template in system.nim, the correct `not` is not being used.

**Comment by Araq** [comment]
That's just the hygiene at work here. Don't create comparisons that don't yield a bool. Come up with your own comparison operators, like ``=@``
