### ISSUE TITLE
nkDefer to nkTryStmt transformation loses type

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#4567]
in the following snipped, derived from tests/exception/tdefer1.nim, the defer is transformed into an nkTryStmt, but the TNode.typ is nil, even though it should have the type set to that of `a`:

```
# nkTryStmt.typ == tyInt
let j = 
  try: 0
  finally: echo "hi"

# nkTryStmt.typ == nil
template test(): expr =
    defer: echo "hi"
    0

let i = test()
```

**Comment by Araq** [comment]
Compiles for me.

**Comment by arnetheduck** [comment]
It compiles, but the AST is wrong, preventing type analysis - it stands to reason that the above two scenarios should produce the same AST, but they don't (even if it then happens that the C generator can live without it)

one problem is in transf.nim:893:
```
          var tryStmt = newNodeI(nkTryStmt, n.sons[i].info)
          var body = newNodeI(n.kind, n.sons[i].info)
          if i < last:
            body.sons = n.sons[(i+1)..last]
          tryStmt.addSon(body)
          tryStmt.addSon(deferPart)
          n.sons[i] = tryStmt
          n.sons.setLen(i+1)
          n.typ = n.sons[i].typ
````

`n.typ` is set to `n[i].typ` which is an `nkTryStmt` just created with `newNodeI`, which doesn't set the typ field, so it looks like the code tries to propagate type up in the tree but this cannot work.

but even if this is fixed, the body of the defer is also missing its correct type, and here I'm lost - I believe there's some code trying to differentiate between `nkStmtList` and `nkStmtListExpr` that fails for this particular case.

**Comment by stefantalpalaru** [comment]
This compilation failure with current HEAD might be related:

```nim
import unicode, unittest

type my_string = distinct string

proc show(m: my_string) =
  echo m.string

template test_suite() =
  suite "test suite":
    setup:
      var s = "foo".my_string

    teardown:
      show(s)

    test "test1":
      check 1 == 1

test_suite()
```
Relevant output:

```
unittest_teardown.nim(19, 11) template/generic instantiation of `test_suite` from here
unittest_teardown.nim(16, 10) template/generic instantiation of `test` from here
/usr/share/nim/lib/pure/unittest.nim(489, 32) template/generic instantiation of `testTeardownIMPL` from here
unittest_teardown.nim(14, 11) Error: type mismatch: got <void>
but expected one of: 
proc show(m: my_string)

expression: show(s324602)
        show(s)
            ^
```

**Comment by narimiran** [comment]
> This compilation failure with current HEAD might be related:

With Nim devel 1.1.1 your example works fine.

----

The example in the original post now produces:
```
Error: defer statement not supported at top level
```

**Comment by Araq** [comment]
I remember fixing this, please re-open if still an issue.
