### ISSUE TITLE
getType, getTypeImpl return inconsistent ASTs

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4584]
In these three cases the AST, returned by `getType` and `getTypeImpl`, differs:
1. `getType` on an object type without fields - last element in `ObjectTy` is `RecList()`.
2. `getTypeImpl` on the same type - last element is `Empty`.
3. `getTypeImpl` on a generic object type with field eliminated by type argument being void (see the code below) - last element is `RecList(RecList())`.

``` nim
import macros

macro dumptype(t: typed): stmt =
  echo t.getType.treeRepr
  quote do: discard

macro dumptypeimpl(t: typed): stmt =
  echo t.getType.getTypeImpl.treeRepr
  quote do: discard

type TEmpty = object
  discard

var t1: TEmpty

dumpType(t1)
# ObjectTy
#   Empty
#   Empty
#   RecList

dumpTypeImpl(t1)
# ObjectTy
#   Empty
#   Empty
#   Empty

type TGeneric[T] = object
  val: T

var t2: TGeneric[void]
dumpType(t2)
# Sym "TGeneric"

dumpTypeImpl(t2)
# ObjectTy
#   Empty
#   Empty
#   RecList
#     RecList

# Note nested RecList!
```

**Comment by Araq** [comment]
Well, chaning this would break code in subtle ways, we have to live with this now.
