### ISSUE TITLE
stdlib - Make hashes consistent across targets and platforms

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4588]
At the moment, `hashes` module uses `int` as a hash representation. This means that the values of the resulting hashes differ between targets. For example, in the following code sample the assertion fails on 32-bit machine:

``` nim
import hashes

const s = "The string to be hashed"
const h1 = hash(s)
let h2 = hash(s)
assert h1 == h2
```

It seems like the compiler's VM uses 64-bit `int` to evaluate the hash, leading to this mismatch.
One possible solution would be to set `Hash` to be `int64` or `int32`, with corresponding fixes in `hashes` and `tables`.

**Comment by mkfifo** [comment]
Good catch :+1:

**Comment by nigredo-tori** [comment]
> is that due to a compile-time vs run-time difference in const from let ?

Probably. Const expressions are evaluated by a VM, which, it seems, has a 64-bit int regardless of actual architecture. For example, this code outputs a 64-bit number in NimScript, but 32-bit if compiled:
```nim
import hashes
echo hash("The ")
```
The weirdest thing is that some of builtin functions still think that `int` is 32-bit:
```nim
let h = hash("The ")
assert h <= high(type(h)) # This fails!
```

**Comment by Araq** [comment]
Hmm this is nasty, but it was done for performance. Though maybe int32 for hashing doesn't harm performance?

**Comment by Parashurama** [comment]
Well I don't know about consistant hashes across all platforms.
but now that #6211 has been merged hashes are consistant between VM and compiled code for the same arch.
previously VM int/uint were always 64bits even on 32bits platforms leading to different hash function between compile time and runtime.

**Comment by dom96** [comment]
The original post's code sample works for me. As such I will close this, please reopen if still an issue.
