### ISSUE TITLE
Better docs for unittest module

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#460]
The unittest module has very few docs and the only way currently to get started with it is to read the examples in the git repo which is not exactly ideal.

**Comment by flaviut** [comment]
I've mostly addressed this in #1883, if there's something I've missed, please tell me. Otherwise, this can be closed.

**Comment by dom96** [comment]
That module needs far more documentation than that.

**Comment by flaviut** [comment]
@dom96 Can you elaborate on what needs to be documented? My tests are exactly like that example, they don't do anything differently.

**Comment by dom96** [comment]
Each of the exported symbols needs to be documented.
