### ISSUE TITLE
last statement in a procedure returning a type?

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#4612]
```nim
type
    MyObj* = object
        a*: int
        b*: bool

proc setField(mo: var MyObj, field: int): bool {.discardable.} =
    mo.a = field
        
proc createNewObject(): MyObj =
    result.setField(12) # <-- This gives: Error: type mismatch: got (bool) but expected 'MyObj = object'
```
But if the ```createNewObject``` procedure is changed to:
```nim
proc createNewObject(): MyObj =
    discard result.setField(12)
```
it works!

Is this suppose to work like this?

Matic

**Comment by mbaulch** [comment]
This is correct behavior. The return value of any `proc` (accessible as the `result` var) is automatically initialised to its default value. To find out how default values work, read [this](http://nim-lang.org/docs/manual.html#statements-and-expressions-var-statement). To illustrate this more concretely,
```nim
proc createNewObject(): MyObj =
    discard result.setField(12)
```
and
```nim
proc createNewObject(): MyObj =
    discard
```
both return a `MyObj` with `a` set to `0` (the default `int` value) and `b` set to `false` (the default `bool`) value.

**Comment by matkuki** [comment]
Thanks @mbaulch, but is the last statement that returns something in a proc implicitly assigned to result?
Because this doesn't compile:
```nim
proc temp(): bool {.discardable.} =
    result = true

proc createNewObject(): MyObj =
    var testVar= 12
    temp()
```
but this does:
```nim
proc temp(): bool {.discardable.} =
    result = true

proc createNewObject(): MyObj =
    temp()
    var testVar= 12
```

Does this mean that this:
```nim
proc createNewObject(): MyObj =
    temp()
```
is equal to:
```nim
proc createNewObject(): MyObj =
    result = temp()
```
?

**Comment by mbaulch** [comment]
The last statement of a `proc`, if it returns something, is implicitly assigned to `result`. Yes, your last two code fragments are equal. Does that make sense?

**Comment by matkuki** [comment]
Thanks for the explanation @mbaulch, I got it now.
