### ISSUE TITLE
parseopt not escaping quotes

### ISSUE THREAD

**Issue by Arnaz87** [nim-lang/Nim#4620]
When I call a Nim program like this: `./main -i "a\"b\"c"` and use the _parseopt_ module to parse the arguments, instead of getting the string `a"b"c`, I get `abc`, and if I use spaces,
instead of `a " b " c`, I get `a`, `b` and `c`.

The problem is in _/lib/pure/parseopt.nim_ in _parseWord_, at the line 45. The procedure is not considering any escape sequence starting with `\`, it just keeps going until it finds another `"`, even if it's escaped.

After looking a little more, I found that using _parseopt2_ solves the problem, by using a list of arguments instead of a concatenated command, but then why is the broken version still in the standard library and is not deprecated?

**Comment by Araq** [comment]
We tried to port our programs to parseopt2 and it caused all sort of regressions and since neither is Posix compliant, why bother? I'm fine with a breaking change if it gains us Posix compliance.

**Comment by Araq** [comment]
> /main -i "a\"b\"c" and use the parseopt module to parse the arguments, instead of getting the string a"b"c

I get ``a"b"c``.
