### ISSUE TITLE
Intermittent crashes when passing Channel as a thread argument

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4621]
This program crashes with SIGSEGV about 30% of time on my machine with the current devel (3ffb6e1ba3d8fcfc527192b9efeb2333d7485378):

``` nim
proc testThread(channel: Channel[int]) {.thread.} =
  discard

for i in 1..10:
  var thread: Thread[Channel[int]]
  var channel: Channel[int]
  channel.open()
  createThread(thread, testThread, channel)
```

OS: OS X Version 10.11.6 (15G31)

**Comment by endragor** [comment]
It seems I should actually pass pointers to channels, because channels are just obj types.

Is there an example of using channels properly while keeping everything GC-safe? I don't want to store channels in global variables, but I'm fine with storing channel pointers as fields of objects.

Wouldn't it make more sense to define channels as `ptr` types internally to hide the unsafe stuff from user?

**Comment by endragor** [comment]
This should probably closed in favor of #4622 - the problem occurs with any thread argument, and the larger the argument is, the more likely the crash is to occur. But I'd like to know your thoughts about Channels - specifically, I think there should be a user-friendly GC-safe approach to using Channels.

**Comment by Araq** [comment]
You cannot rebind a thread variable like this.

**Comment by endragor** [comment]
@Araq could you please elaborate? I did not understand that sentence in relation to the issue.

**Comment by Araq** [comment]
Use the `Chan` type from `nim-lang/threading` instead.
