### ISSUE TITLE
system.nim read/write Bytes/Buffer/Chars defaults

### ISSUE THREAD

**Issue by abudden** [nim-lang/Nim#4627]
The `readBytes`/`writeChars` etc functions in system.nim generally have the following signature:

```nim
proc funcName*(f: File, a: var openArray[T], start, len: Natural): int
```

In what I would imagine were a significant number of uses of these functions the call is likely to be:

```nim
funcName(f, myData, 0, myData.len())
```

Given that `openArray`s encapsulate a length, would it be reasonable for `start` to *default* to `0` and `len` to *default* to `a.len()-start` so that the user can just write the following when they want to use the whole buffer size?

```nim
funcName(f, myData)
```

----

Also, for ease of use, it would be nice to have a `readBytes` (and maybe others) with a signature like this:

```nim
proc readBytes*[int8|uint8](f: File, len: Natural): seq[T] =
  result.newSeq(len)
  result.setLen(f.readBytes(result, 0, len))
```

----

Combining the two modifications above would allow simple code like:

```nim
# Read 20 bytes from part-way through infile.dat and write to outfile.dat
var fpIn = open("infile.dat")
defer: fpIn.close()
fpIn.setFilePos(100)

var fpOut = open("outfile.dat", fmWrite)
defer: fpOut.close()

# Nice and simple - read 20 and write whatever you manage to read
discard fpOut.writeBytes(fpIn.readBytes(20))
```

At the moment, the best I can come up with is to replace the **single** last line with this:

```nim
# Omitted: open files as above...

# Read 20 and write whatever you manage to read
var buffer: seq[int8]
buffer.newSeq(20)
var count = fpIn.readBytes(buffer, 0, 20)
discard fpOut.writeBytes(buffer, 0, count)
```

**Comment by Araq** [comment]
``len: Natural = otherparam.len``  is currently not supported due to frontend limitations. But tbh I don't think low level IO is all that common that it needs to be particularly convenient and can even be dangerous: Endianness issues come to mind. It's easy enough to write one line templates that make it as convenient as desired within modules that require it.
