### ISSUE TITLE
Confusing error message when comparing variant objects for equality

### ISSUE THREAD

**Issue by kierdavis** [nim-lang/Nim#4628]
Compiling:

``` nim
type
  Obj = object
    case hasStr: bool
    of false:
      discard
    of true:
      str: string

let x = Obj(hasStr: false)
let y = Obj(hasStr: true, str: "Hello, world!")
echo $(x == y)
```

gives the error message:

```
test.nim(11, 10) template/generic instantiation from here
lib/nim/system.nim(2276, 3) Error: parallel 'fields' iterator does not work for 'case' objects
```

which is quite low-level and may be confusing, especially to newcomers. A better error message could be something along the lines of "`==` operator is not implemented for 'case' objects", though I'm not sure how you could detect if the object contains a 'case' block in the implementation of `==`.

**Comment by Araq** [comment]
Meh, come on. It clearly says "instantiation from here".

**Comment by andreaferretti** [comment]
You may be interested in the `variant` macro in [patty](https://github.com/andreaferretti/patty), which does generate the suitable `==` implementation

**Comment by dom96** [comment]
> Meh, come on. It clearly says "instantiation from here".

This is not the attitude we should be taking. The compiler's error messages should be as easy to understand as possible, this is a long way from that.

**Comment by Araq** [comment]
> This is not the attitude we should be taking. The compiler's error messages should be as easy to understand as possible, this is a long way from that.

``==`` is not built into the compiler, it follows the rules for generic instantiations and fails then with this error message. And it's not even a bad error message, it's precise and once you navigate into system.nim things become clear. It's the right attitude to take if you don't want to create a compiler full of special cases where suddenly the compiler needs to know the stdlib (!) just to report better error messages.

**Comment by zielmicha** [comment]
Maybe error message should contain template/proc name (similarly how stacktraces contain proc names)?

**Comment by nc-x** [comment]
PR https://github.com/nim-lang/Nim/pull/9207
Can be closed?
