### ISSUE TITLE
Abstraction pragma request

### ISSUE THREAD

**Issue by ventor3000** [nim-lang/Nim#463]
A nice feature to support OO can be {. abstact .} of a method, which marks it as 'not implemented'. All inheriting methods must implement this function, or an compiler error occurs.

**Comment by nazgul17** [comment]
Has this feature request seen any unreported progress?

**Comment by Araq** [comment]
No, and it's not clear what "type must implement this method" means for Nim: Where does it have to be implemented? Somewhere? In the same module the type is declared in?

**Comment by nazgul17** [comment]
I am inclined towards your last suggestion. What are the problems with such choice?

**Comment by ventor3000** [comment]
In my opinion, a type that inherits a type with an abstract function, must implement this abstract function _anywhere_, otherwise an compile time error happens. This feature would be greatly usefull for maintaining large object/inheritance hirearchies.

**Comment by Araq** [comment]
> This feature would be greatly usefull for maintaining large object/inheritance hierarchies.

True, but these grew out of fashion anyway. ;-)

> What are the problems with such choice?

It means we have to produce error messages after the whole program has been compiled. It is anti-modular.

**Comment by ventor3000** [comment]
>> It is anti-modular.
Cross module inheritance is anti-modular by nature (in sense of file=module thinking). The reason (at least for me) this feature would be needed is to solve larger scale problems. As a CAD/CAM programmer, I think for example of the inheritance chain:
Spatial3d=>Geometry3d=>Curve3d=>ContinuousCurve3d=>NURBS3d
Let say I introduce a new function in Spatial3d called getExtents() which returns the bounding box of the object. This function would reasonably be abstract because it is not possible to implement in an earlier case than NURBS3d. However, all functions inheriting Spatial3d need to implement this function. The way one has to do it in Nim as it is now, is to implement a dummy function invoking an error in Spatial3d. When you create a new object inheriting Spatial3d it is easy to 'forget' to implement the getExtents() function because it will just pass thru compiler silently. That is a problem and lowers code quality. (Note that this problem also could be soved by some 'interface' functionality, as in C# etc.)

**Comment by Araq** [comment]
> Note that this problem also could be solved by some 'interface' functionality, as in C# etc

Interfaces are tuples of closures in Nim.

**Comment by ventor3000** [comment]
Yes but they do not force implementation of specific functions (?)

**Comment by Araq** [comment]
Surely they do if you require your constructors to take them.

**Comment by nazgul17** [comment]
That's also how I thought to get the same behavior. However, I find it not
elegant because abstract methods would need to be treated differently from
other overriding methods. I think that, when writing a child class, one
should not worry about which methods were abstract and which weren't.

Could, instead, the error be generated at the first usage of an instance of
the extended class? This would limit the "area" where an abstract method
can be extended to "before its usage". Does it make sense?

**Comment by Araq** [comment]
Sorry, not gonna happen anytime soon. We're getting an interface macro though. :-)
