### ISSUE TITLE
fmod and other math module functions are missing in js mode

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4630]
I am using self-built nim from git. I tested the following with 006207742f43f4e793b

I write this code:

```
import math
var x = fmod(1.0, 4.0)
```

And compile it with `nim js -o:testNim.js testNim.nim`, I get an error:

```
Hint: used config file 'C:\msys64\home\Andi\work\g\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: testnim [Processing]
Hint: math [Processing]
testnim.nim(2, 9) Error: undeclared identifier: 'fmod'
```

I do not get the same problem if I run with `nim c`.

Doing a quick sweep of the documentation http://nim-lang.org/docs/math.html, I find that documented functions `trunc`, `lgamma`, `tgamma`, `erfc`, `erf`, are also missing from the math module. I believe everything else is present.

The backends page http://nim-lang.org/docs/backends.html says "Features or modules that the JavaScript platform does not support are not available... However, the modules strutils, math, and times are available" so my expected behavior is that the entirety of the math module should be available. If this is for some reason not possible I expect it to be clearly documented.

**Comment by yglukhov** [comment]
Why does `fmod` function exist at all, if there's `mod` operator?

**Comment by mcclure** [comment]
@yglukhov From my reading of the docs they have different behavior with respect to operand sign.

**Comment by define-private-public** [comment]
Is this ticket still relevant, as the `fmod` function has been marked to be deprecated:

https://nim-lang.org/0.20.0/math.html#fmod%2Cfloat32%2Cfloat32

**Comment by Araq** [comment]
Agreed.

**Comment by mcclure** [comment]
I'm sorry late response, but… "trunc" was one of the impacted functions at my last test, and it is still in the documentation and *not* deprecated… I don't think it really matters as long as the documentation is accurate. If `trunc, lgamma, tgamma, erfc, erf` are unsupported in js mode then they should be labeled in the documentation as not fully supported.

**Comment by define-private-public** [comment]
Shouldn't a new ticket for those missing functions (in JS) be created?
