### ISSUE TITLE
GC assert triggers when assigning TableRef threadvar

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4640]
Sample:
```nim
import tables

type
  ThreadPool = ref object
    threads: seq[ptr Thread[ThreadArg]]
  ThreadArg = object
    table: TableRef[string, string]

var globalTable {.threadvar.}: TableRef[string, string]
globalTable = newTable[string, string]()

proc testThread(arg: ThreadArg) {.thread.} =
  globalTable = arg.table

proc newThreadPool(threadCount: int): ThreadPool =
  new(result)
  result.threads = newSeq[ptr Thread[ThreadArg]](threadCount)
  for i in 0..<threadCount:
    echo "Initializing thread ", i, "..."
    var arg = ThreadArg(table: globalTable)
    var threadPtr = cast[ptr Thread[ThreadArg]](alloc0(sizeof(Thread[ThreadArg])))
    createThread(threadPtr[], testThread, arg)
    result.threads[i] = threadPtr

discard newThreadPool(8)
```

When compiled with `nim c --threads:on -d:useGcAssert`, this results in GC asserts triggered from created threads although the code seems valid.
```
[GCASSERT] incRef: interiorPtr
Traceback (most recent call last)
test.nim(13)             testThread
gc.nim(286)              unsureAsgnRef
gc.nim(118)              incRef
```
Nim devel, Git hash: 3fc95ce69e787b988f2f47adb035eabf082822ca
OS X 10.11.6

**Comment by Araq** [comment]
Spot the error: 

```nim

var globalTable {.threadvar.}: TableRef[string, string]
globalTable = newTable[string, string]()

proc testThread(arg: ThreadArg) {.thread.} =
  globalTable = arg.table
```

Only the main thread has an initialized globalTable because it's not "global", it's thread local.

**Comment by Araq** [comment]
Any reason why you reinvent the stdlib threadpool module?

**Comment by endragor** [comment]
@Araq 
Yes, the main thread has it initialized, and it passes the reference to other threads via the argument, then those threads set their own thread-local references. Where is the error?

I'm not reinventing the module, I just made a sample. threadpool module doesn't fit my use cases, because in my case all threads can do async IO and they should communicate with other threads at the same time (you can't wait for FlowVar and poll() at the same time). I also need more control of what threads do/store in my app.

**Comment by Araq** [comment]
Ok, my bad, try ``globalTable = deepCopy arg.table`` as a workaround.

**Comment by endragor** [comment]
After changing that line to `deepCopy(globalTable, arg.table)` I still get similar similar assertion error:
```
[GCASSERT] incRef: interiorPtr
Traceback (most recent call last)
test.nim(13)             testThread
deepcopy.nim(128)        genericDeepCopy
deepcopy.nim(102)        genericDeepCopyAux
gc.nim(286)              unsureAsgnRef
gc.nim(118)              incRef
```
