### ISSUE TITLE
Cannot inherit from generic .importcpp type

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4651]
The code below does not compile which prevents wrapping of some C++ hierarchies. The problem is specifically in parent type being generic. It compiles fine if the parent type is not generic.

``` nim
type
  Vector {.importcpp: "std::vector<'0 >", header: "vector", inheritable.} [T] = object
  VectorDerived {.importcpp: "SomeVectorDerived", nodecl.} = object of Vector[int]
  # Error: inheritance only works with non-final objects
```

**Comment by Araq** [comment]
This is not related to importcpp.

**Comment by Araq** [comment]
Workaround: Write ``object {.inheritable.}`` instead.

**Comment by metagn** [comment]
The workaround shown above gives a parser error on 2.0, so here is an example of a macro to do it on all versions: https://github.com/metagn/genericinheritablefix
