### ISSUE TITLE
Removing lines from end of file then rebuilding does not rebuild [js only?]

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4656]
This one's a bit odd. 

I am using self-built nim from git, -d:release. I tested the following with 07d7d35d995262830f86cc02f3c6. Then I upgraded to 84a09d2f5b0866491e55fef0fef541e8cc548852, tested again, and got the same results. I am on Windows 10. I am invoking Nim inside MSYS2 Bash. I am using Sublime Text as my editor.

I put these lines in a file nimtest.nim

    proc log*(msg: cstring) : void {.importcpp:"console.log(@)".}
    
    log("ONE")
    
    log("TWO")
    
    log("THREE")

I run `nim js -o:nimtest.js nimtest.nim`. I inspect nimtest.js. It ends with

    console.log("ONE");
    console.log("TWO");
    console.log("THREE");

In my editor, I delete the final line (`log("THREE")`) from nimtest.nim. Once again, I run `nim js -o:nimtest.js nimtest.nim`.

`nim js` prints the lines I'd expect it to print when it compiles:

    Hint: used config file 'C:\msys64\home\Andi\work\g\Nim\config\nim.cfg' [Conf]
    Hint: system [Processing]
    Hint: nimtest [Processing]
    Hint: operation successful (4917 lines compiled; 0.028 sec total; 3.504MiB; Debug Build) [SuccessX]

However, nimtest.js has not updated. Its file modified timestamp has not updated. When I inspect it, its final line is still `console.log("THREE");`.

If I add content to the end of the file (rather than just removing) and run `nim js`, then I get the expected behavior (nimtest.js updates). If I change content (change THREE to FOUR for example) I get the expected behavior (nimtest.js updates).

If I repeat the test with `nim c` and a file containing:

    echo "ONE"

    echo "TWO"

    echo "THREE"

I do not see the same problem. Removing the line echo "THREE" and rerunning nim c produces an executable that does not print "THREE".

**Comment by Araq** [comment]
This is a bug in compiler/ropes.nim proc equalsFile. But you shouldn't edit generated code.

**Comment by mcclure** [comment]
If I was unclear-- I did not edit generated code in any of the scenarios described above. If I refer to "removing a line" I am referring to editing nimtest.nim, the source file.
