### ISSUE TITLE
64-bit Complex type

### ISSUE THREAD

**Issue by mihirparadkar** [nim-lang/Nim#4663]
Currently, the only complex numbers in the standard library are double-precision (128-bits). However, it would be nice to have a single-precision complex type (64-bits) to enable more interoperability with C's `float complex` and C++'s `std::complex<float>` for many signal, image, and scientific libraries. I've started implementing it myself, but I'm not sure whether it is better to implement complex as `Complex[T: SomeReal]` or `Complex64, Complex128,...` with `Complex` as an alias for `Complex128`.

**Comment by Araq** [comment]
I think generic is the way to go.

**Comment by narimiran** [comment]
What is the status of this? @mihirparadkar, have you done any work? (If you can share what you have done, I can continue from there)

**Comment by jxy** [comment]
Would simply replacing `Complex` with `Complex[T]` and aliasing `Complex` to `Complex[float]` an acceptable solution to this?  If so I can make a PR quickly.  Any suggestions?

**Comment by Araq** [comment]
> Would simply replacing Complex with Complex[T] and aliasing Complex to Complex[float] an acceptable solution to this? If so I can make a PR quickly. Any suggestions?

Yes, that would be nice but the compiler won't allow overloading the typeclass ``Complex[T]`` with a non-generic ``Complex`` type alias. So we need to find a name for the generic variant.

**Comment by narimiran** [comment]
> Any suggestions?

In the mean time I've made [this PR](https://github.com/nim-lang/Nim/pull/9452), but people said that they want to see some larger changes, so I've put everything on hold for now until we figure out what exactly we want. (And that (waiting) would be my suggestion to you, too.)

**Comment by narimiran** [comment]
Since #9590 has been merged, this can be closed.
