### ISSUE TITLE
stdlib_system.c warning: 'noreturn' function does return

### ISSUE THREAD

**Issue by secretfork** [nim-lang/Nim#4664]
While playing with nim using some examples from the documentation, there's quite a few warnings:

`gcc -o m -Inimcache -IC:\nim\lib nimcache\fib.c nimcache\stdlib_system.c maths.c
nimcache\stdlib_system.c: In function 'sysfatal_15626_1689653243':
nimcache\stdlib_system.c:4909:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_81472_1689653243':
nimcache\stdlib_system.c:5274:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_21818_1689653243':
nimcache\stdlib_system.c:4933:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24464_1689653243':
nimcache\stdlib_system.c:5105:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24027_1689653243':
nimcache\stdlib_system.c:4983:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24003_1689653243':
nimcache\stdlib_system.c:4959:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24218_1689653243':
nimcache\stdlib_system.c:5033:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24050_1689653243':
nimcache\stdlib_system.c:5009:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24277_1689653243':
nimcache\stdlib_system.c:5057:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_24486_1689653243':
nimcache\stdlib_system.c:5129:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_26623_1689653243':
nimcache\stdlib_system.c:5153:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_26649_1689653243':
nimcache\stdlib_system.c:5177:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_26668_1689653243':
nimcache\stdlib_system.c:5201:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_87103_1689653243':
nimcache\stdlib_system.c:5291:1: warning: 'noreturn' function does return
 }
 ^
nimcache\stdlib_system.c: In function 'sysfatal_91221_1689653243':
nimcache\stdlib_system.c:11333:1: warning: 'noreturn' function does return
 }
 ^`

The example in question is from http://nim-lang.org/docs/backends.html and more specifically the section [_Nim invocation example from C_.
](http://nim-lang.org/docs/backends.html#backend-code-calling-nim-nim-invocation-example-from-c)I'm running windows 10, fully updated (Version 1607), nim 0.14.2 (2016-06-09) [Windows: amd64] and TDM-GCC 5.1.0 (tdm64-1)
Now while this isn't exactly a critical bug (it compiles, but with warnings), it was suggested in the nim IRC channel that I file a bug report about it. So here we go.

Let me know if I missed to include some vital info.

**Comment by secretfork** [comment]
Addendum, nim.cfg is untouched btw. Also, do note that I'm not using the gcc shipped with nim if that is of importance somehow (using http://tdm-gcc.tdragon.net)

**Comment by Araq** [comment]
Is fixed with ``--gc:arc`` which is about to become the default.

**Comment by arnetheduck** [comment]
@Araq it might be a while before orc becomes default, I think this would be worth a fix for the current Nim versions / GC as well - the compiler can generate better code when these warnings are not around
