### ISSUE TITLE
Macro expansion works differently in generics

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4669]
This one looks like a regression, since it broke my two week old code.
Consider the example:
```nim
import macros

type Marker = distinct object
var m: Marker

macro `[]`(m: Marker, y: untyped): untyped =
  ## Takes `y` in this form: `dummyProc(x)`
  ## returns `x`
  result = y[1]

macro wrap(x: untyped): untyped =
  result = quote do:
    m[dummyProc(`x`)]

# Works OK with non-generic signature
# proc foo(a: string): string =

proc foo[A](a: A): A =
  wrap(a)
```
This results in the following error:
```
test_forcomp.nim(13, 16) Error: undeclared identifier: 'dummyProc'
```
Seems like in intermediate expression `m[dummyProc(a)]` the second parameter (inside square brackets) gets inspected too, even though it's supposed to be `untyped`.

**Comment by nigredo-tori** [comment]
Bisect points to 89f3e21fc876e589de62f81aa1aa67e36eacc22e

**Comment by Araq** [comment]
This works and is what should have been used in the first place:

```nim

import macros

type Marker = distinct object
var m: Marker

macro `[]`(m: Marker, y: untyped): untyped =
  ## Takes `y` in this form: `dummyProc(x)`
  ## returns `x`
  result = y[1]

macro wrap(x: untyped): untyped =
  template t(x): untyped {.dirty.} = m[dummyProc(x)]
  result = getAst t(x)

# Works OK with non-generic signature
# proc foo(a: string): string =

proc foo[A](a: A): A =
  wrap(a)
```

**Comment by nigredo-tori** [comment]
In my case I simply moved the first macro's implementation to compile-time proc and used it directly. Wouldn't come up with this `template` workaround myself anyway - I still can't see how it works and why the initial example does not.

**Comment by Araq** [comment]
It's the expected behaviour.
