### ISSUE TITLE
Modulo is not defined in documentation

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4676]
Looking in the manual, I find `%` and `mod` listed as operators, but do not find a description of what either `%` or `mod` do.

The tutorial explains that `div` and `mod` are the integer versions of division and modulo (the manual does not explain `div`). However, this does not tell me how `%` and `mod` are different, and it does not tell me what the sign behavior of `mod` is.

The documentation for the Math module contains docs for the special `mod` in that module that operates on floats, and it explains exactly what the sign behavior of this special (float mod float) is. This strongly implies, but does not guarantee, integer `mod` has the same sign behavior.

Expected "behavior": The Nim Manual should specifically explain the definition of `%` and `mod` (and for that matter `div`) and specify how they behave with operands of differing signs. If the sign behavior is platform-dependent the manual should say that explicitly because it is important to know.

**Comment by ConsoleTVs** [comment]
it is documented here: https://nim-lang.org/docs/system.html#mod,int32,int32

And yes, the math includes a mod for floats, simply import math and mod will work on floats.

It's also listed here: https://nim-lang.org/docs/manual.html#lexical-analysis-operators

**Comment by mcclure** [comment]
To clarify, what I was really looking for was "what is the behavior of %/mod when used on operands of differing signs?". Neither of these doc links answer that question explicitly, although the one in system.html might give you an indirect answer if you look up "div" then "trunc".
