### ISSUE TITLE
Nim always expects all generic parameters to be specified even if some can be inferred

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4688]
I'd expect that this code compiles, but it doesn't:

``` nim
proc convertTo[T](v: int or float): T =
  (T)(v)
discard convertTo[float](1)
# Error: cannot instantiate: convertTo[float]; got 1 type(s) but expected 2
```

It compiles if the invocation is changed to this: `convertTo[float, int](1)`.
Nim Git hash: 84a09d2f5b0866491e55fef0fef541e8cc548852

**Comment by krux02** [comment]
Does Nim actually claim that it can infer generic types partially? I can't remember any part of feature in the manual. The bug tracker should  not be used for feature requests.

this code should solves your use case:

    proc convertToImpl[T](v: int or float): T =
      (T)(v)
    discard convertToImpl[float,int](1)

    template convertTo(t: typedesc, arg: int or float): expr =
      convertToImpl[t, type(arg)](arg)
      
discard convertTo(float, 1)

**Comment by endragor** [comment]
@krux02 
This is not a "bug tracker". There are many [feature requests here](https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AFeature).

There is no full Nim standard/specification. Manual is incomplete, it is stated right at the top of it. It's up to @Araq to decide whether this is a bug or a feature request (or neither) and what priority it has.

Thanks for the workaround.
