### ISSUE TITLE
Problem with closure iterators in js target

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4695]
`nim js` of

``` nim
iterator it(x: int): int {.closure.} =
  for i in 0..<x:
    yield i

var i = it
```

produces:

```
iterators.nim(1, 10) Error: internal error: could not find env param for it
```

**Comment by Araq** [comment]
closure iterators for JS are not yet supported. Sorry.

**Comment by ringabout** [comment]
Now Nim compiler provides a better error messages for JS backend
#15823

**Comment by narimiran** [comment]
I find `Error: Closure iterators are not supported by JS backend!` good enough error message for this to be closed.
