### ISSUE TITLE
Idetools process mode fails to return types for some queries

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#471]
The test for https://github.com/gradha/Nimrod/commit/ee5d31de53b9c2fbab9841d74d8577851ee3c388 included in #470 includes three cases where idetools returns the correct type in server mode but not in process mode, where it returns the empty string. Seems to happen with skConst, skField and skType.

**Comment by Varriount** [comment]
@reactormonk was this fixed?

**Comment by reactormonk** [comment]
Nope, I just moved it over https://github.com/nim-lang/nimsuggest/issues/9
