### ISSUE TITLE
Compiler tries to call setter, when getter with mutable reference should be assigned to.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#4711]
I was trying to improve swizzling support for a vector math library, And I encountered the following problem:

```Nim
type
  Vec4 = object
    x,y,z,w : float32

  Vec3 = object
    x,y,z : float32

proc `+=`(v0: var Vec3; v1: Vec3) =
  v0.x += v1.x
  v0.y += v1.y
  v0.z += v1.z
    
proc xyz(v: var Vec4): var Vec3 =
  cast[ptr Vec3](v.x.addr)[]

let tmp = Vec3(x: 1, y:2, z:3)
var dst = Vec4(x: 4, y:4, z:4, w:4)

xyz(dst)  = tmp # works
dst.xyz() = tmp # works
dst.xyz  += tmp # works
dst.xyz   = tmp # attempting to call undeclared routine `xyz=`
```
It would be nice if this would compile without errors, because that allows me to implement swizzling closer to what glsl swizzling is able to do. The reason, why I don't want to just implement getter setter procedures is, that with getters and setters, operators like `+=` and `*=` wouldn't work anymore.

I know that for swizzling like `xzyy` I would be forced to implement setters, I would not be able to return a reference.

**Comment by Araq** [comment]
``a[x] = y`` always invokes a setter and never a getter but that doesn't keep the getter from returning a ``var T``.
