### ISSUE TITLE
threads module ID/naming enhancements [RFC]

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4713]
1. At the moment there is no API to get ID of the current thread, even though it could be useful in some applications (e.g. logging module).
2. Threads IDs being generic types is somewhat counter-intuitive - you would have to convert them to `pointer` to store them in a table/seq. I think it makes sense to define ThreadId as an opaque pointer or int. Main thread ID would be zero pointer with current implementation.
3. Being able to name threads would also be useful at least for logging/debugging purposes.

**Comment by Araq** [comment]
1. ``devel`` has this:

proc handle*[TArg](t: Thread[TArg]): SysThread {.inline.}

2. The type is ``SysThread``.
3. If Posix/Windows support it, why not.

**Comment by endragor** [comment]
1. I meant getting *current thread* ID - such proc would not accept any arguments, like this: http://linux.die.net/man/3/pthread_self
2. So why do we have both ThreadId and SysThread? What's worrying about `SysThread` is that it is low-level handle with platform-dependent type, I'm not sure if it should be exposed.
3. Yes, it's supported there, but on POSIX the name is limited to 15 chars which is somewhat restrictive.

**Comment by Araq** [comment]
``getThreadId`` exists now and you can give thread names via ``var threadName {.threadvar.}: string`` easily enough, no need to bloat the stdlib with that.
