### ISSUE TITLE
GC hangs/crash in markStackAndRegisters when switching tasks using posix setcontext/swapcontext

### ISSUE THREAD

**Issue by katuma** [nim-lang/Nim#472]
https://gist.github.com/katuma/5736724

`nimrod compile  --run ctx.nim`

Tried M&S, refc, boehm. Sometimes it just hangs in 99% infinite loop, sometimes this segfault:

```
task1
Traceback (most recent call last)
ctx.nim(62)              ctx
ctx.nim(36)              resume
ctx.nim(21)              cowrap
ctx.nim(49)              task1
gc.nim(934)              GC_fullCollect
gc.nim(883)              collectCT
gc.nim(856)              collectCTBody
gc.nim(771)              markStackAndRegisters
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed
```

**Comment by BigBoneDaddy** [comment]
@katuma Do you still get this bug?

**Comment by reactormonk** [comment]
I just ran the sample again, can confirm, still segfaults.

**Comment by Araq** [comment]
You cannot simply wrap a C library that fucks up stack handling and except Nim's GC to swallow it. At the very least you need to use ``setupForeignThreadGc`` in the callback and mark the callback as ``.gcsafe``.

**Comment by MrMormon** [comment]
@Araq If this is expected behavior, can it be closed?
