### ISSUE TITLE
Rolling file logger segfaults in release mode when rolling over to a new file

### ISSUE THREAD

**Issue by mjoud** [nim-lang/Nim#4724]
This
```nimrod
import logging
var L = newRollingFileLogger("rolling.log", maxLines = 1000)
addHandler(L)

for i in 0..<1001:
  debug(i)
```
fails with `SIGSEGV: Illegal storage access. (Attempt to read from nil?)` in release mode only, when a new file is to be started. Windows 7, with `gcc (tdm-1) 5.1.0` and

```
Nim Compiler Version 0.14.2 (2016-06-11) [Windows: i386]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: abf4e204c2f1a8a6915a8d32c970b5ce64f58e10
active boot switches: -d:release
```

**Comment by cheatfate** [comment]
I can't reproduce it with Windows 10 x64, `gcc (GCC) 4.8.3` and `nim latest devel`.

**Comment by mjoud** [comment]
I get the same error with latest `devel`.

**Comment by yglukhov** [comment]
@mjoud, can you compile it with `-g` flag, and gdb to it and see the stack trace?

**Comment by mjoud** [comment]
No luck with `gdb`, sorry. With `-d:release --opt:none --lineTrace:on --stackTrace:on` i got the following output: 

```
Traceback (most recent call last)
testlog.nim(5)           testlog
logging.nim(262)         logLoop
logging.nim(139)         log
logging.nim(248)         log
logging.nim(241)         rotate
os.nim(583)              moveFile
os.nim(151)              raiseOSError
Error: unhandled exception: Det går inte att hitta filen.
 [OSError]
```

which translates to something like `unknown file`. Debug builds are vulnerable to this error when you have a `rolling.log.2` file present when running the example above, or for example `rolling.log`, `rolling.log.3` but not `rolling.log.2` present.

**Comment by yglukhov** [comment]
Well indeed, there is no check whether source file is present. Should be dead easy to fix. @mjoud, can you do it please?

**Comment by mjoud** [comment]
No time ATM.

Also saw #4731 which does look very similar. In my first example the file was indeed present (when rolling over).
