### ISSUE TITLE
issues with the random module

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#4726]
- `ui` type is exported, but used nowhere in the exported API.
- `proc random(max: int)` returns a number in the range `0..max-1`. This is not only inconsistent with the loops of the language, where the upper bound is normally inclusive, but it also makes it impossible to create a random number including high(int) there is no way to just get 32 random bits with this function on a single call architecture independently, because int might be 32 bits on a 32bit target.
-  there is no information how this behaves with multiple threads. Is there one random number pool per thread, or do all threads share the same pool? Is it even thread save? Do the random number generators lock access to the random bits pool?
- internal compile error type mismatch for all of them
  
  ``` Nim
  import random, sequtils
  
  let a1 = random.random(1'u64..6) # lib/pure/random.nim(90, 18) Error: type mismatch: got (uint64)
  let b1 = random.random(1'i64..6) # lib/pure/random.nim(90, 18) Error: type mismatch: got (int64)
  let c1 = random.random(1'u32..6) # lib/pure/random.nim(90, 18) Error: type mismatch: got (uint32)
  let d1 = random.random(1'i32..6) # lib/pure/random.nim(90, 30) Error: type mismatch: got (int) but expected 'int32'
  let e1 = random.random(1'u16..6) # lib/pure/random.nim(90, 18) Error: type mismatch: got (uint16)
  let f1 = random.random(1'i16..6) # lib/pure/random.nim(90, 30) Error: type mismatch: got (int) but expected 'int16'
  let g1 = random.random(1'u8..6)  # lib/pure/random.nim(90, 18) Error: type mismatch: got (uint8)
  let h1 = random.random(1'i8..6)  # lib/pure/random.nim(90, 30) Error: type mismatch: got (int) but expected 'int8'
  ```
  
  why again is this generic?
- inconsistencies on Slice and seq types
  
  ``` Nim
  echo "the range 1..6 contains the values:"
  for i in 1..6:
  stdout.write " ", i
  echo "\nincludes the 6"
  
  echo "the same range creates random values:"
  for i in 1..50:
  stdout.write " ", random.random(1..6)
  echo "\n", "does not include the 6"
  echo "random on the same range with toSeq around it"
  let theseq = toSeq(1..6)
  for i in 1..50:
  stdout.write " ", random.random(toSeq(1..6))
  echo "\n", "now it includes the 6 again"
  ```
- It would be nice if these would work as expected (including upper bound)
  
  ``` Nim
  let a2 = random.random[uint8](low(uint8)..high(uint8))
  let b2 = random.random[int8](low(int8)..high(int8))
  let c2 = random.random[uint16](low(uint16)..high(uint16))
  let d2 = random.random[int16](low(int16)..high(int16))
  let e2 = random.random[uint32](low(uint32)..high(uint32))
  let f2 = random.random[int32](low(int32)..high(int32))
  let g2 = random.random[uint64](low(uint64)..high(uint64))
  let h2 = random.random[int64](low(int64)..high(int64))
  
  # but low(uint64) and high(uint64)  don't even compile‽
  ```
# bonus section 2

It would be nice, if the random number generator could be exported as an object, so the user can have control from witch random number generator random numbers are drawn from.

It would be nice, if the source of the random bit's could be changed, for example using the mersenne twister.

It would be nice, if there is a normal distributed random number generator. (I ported one to nim, I could contribute it if it would be welcome)

**Comment by Araq** [comment]
The ``random`` module procs used to be in math.nim and have been modelled after what was in math.nim. I agree the design makes little sense, but at the same time I was glad I didn't have to think about API design. :P

**Comment by krux02** [comment]
I think I can do a better than this API and I would be interested to contribute a random module that fixes all of these problems. But how should I do it. Should I write my own random module, and then when it becomes stable this becomes deprecated? Or should I add everything within this module and mark its current members deprecated? But the only consistent API that I can come up with at the moment would deprecate almost everything. And in general, how long are things deprecated before they get removed?

**Comment by dom96** [comment]
> should I add everything within this module and mark its current members deprecated? 

This.

> And in general, how long are things deprecated before they get removed?

A long time. As part of my massive "stdlib overhaul" plan I likely will suggest that we remove all deprecated symbols at once to get the standard library ready for 1.0.

**Comment by krux02** [comment]
@dom96  I am currently digging out my old unsolved issues, To remove the deprecation tags, I recommend to remove them earlier when they reach a certain age. With tools like grep and git it should be possible to find all deprication tags that are older than age X. And everything that is older than age X can then be removed.

Towards the patch of the random module, For my needs I wrote my own version of a random module here:

https://github.com/krux02/opengl-sandbox/blob/master/includes/basic_random.nim

Not really in the spirit to give all the development support back to Nim, but it allows me to write and test my ideas of a random module without the tedious process to get a pull request through.

**Comment by andreaferretti** [comment]
@krux02 It may be worth coordinating with @oprypin since there is this nice Nimble module https://github.com/oprypin/nim-random

**Comment by dom96** [comment]
Marking as high priority as it contains some important changes that may be breaking.
