### ISSUE TITLE
Importcpp with a "var" parameter produces gibberish [0] or ,0 in JS

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4729]
I am running with nim 80fe763915ac742314069489906c5 self-built from git. I have only tested the following with `nim js`; I am not sure how to set up an appropriate `nim c` test.

I am trying to work around issue #4728. I realize that a good way to do this would be to use importcpp patterns. I put this in a file and compile it with `nim js -o:testnim.js -d:release testnim.nim`:

```
type TestType* {.importc.} = ref object of RootObj
    length* {.importc.}: float
proc newTestType*() : TestType {.importcpp:"new Object".}
proc `[]=`*(t: var TestType, key: float, val: float) {.importcpp:"#[#] = #".}
proc `[]`*(t: TestType, key: float) : float {.importcpp:"#[#]".}

var x1 {.exportc.} = newTestType()
x1[1.0] = 5.0
let x2 {.exportc.} = x1[1.0]
```

**Observed behavior**: A file is generated ending with the lines:

```
var x1 = new Object();
x1, 0[1.0000000000000000e+000] = 5.0000000000000000e+000;
var x2 = x1[1.0000000000000000e+000];
```

`proc []` generated its code fine, but `proc []=` inserted an extraneous `, 0`. The JavaScript interpreter interprets the second line, with the `, 0` as me attempting to set the `[1]` property on the number [0], and so that line becomes a noop.

I experiment and realize that the `, 0` seems to be a byproduct of `t` on `proc []=` being declared as `var`, and that `importcpp` in general behaves weirdly when `var` is present. If I try making a non-pattern, non-operator importcpp proc where the first argument is a `var`, for example:

```
type TestType* {.importc.} = ref object of RootObj
    length* {.importc.}: float
proc newTestType*() : TestType {.importcpp:"new Object".}
proc testMethod(t: var TestType, key: float) {.importcpp.}

var x1 {.exportc.} = newTestType()
x1.testMethod(2.0)
```

A file is generated ending with:

```
var x1 = new Object();
x1[0].testMethod(2.0000000000000000e+000);
```

Here the `[0]` is extraneous.

**Expected behavior**: When I specified the importcpp pattern `#[#] = #`, I expected it to emit the JS `a[b] = c` where a, b and c are my three arguments.

In the second case-- the `testMethod` with the `var` argument-- I am not sure what exactly I expected Nim to do. Obviously JavaScript has no equivalent of a `var` parameter so usually declaring a parameter as `var` doesn't make a lot of sense. However, for some parameters, it seems like Nim is passing around data items which are immutable in Nim but would be mutable in JavaScript (like arrays or objects) so in those cases the `var` designation on the parameter **is** appropriate. So I think my expected behavior is that Nim should simply ignore the `var` tag if it sees it in an `{.importc.}` or `{.importcpp.}`, and if the argument to the `var` parameter is something which the callee could not plausibly mutate (for example, `y` in `proc x(var y: float)`), then perhaps Nim should emit a warning. However, the `[0]` seen in the example is **definitely** incorrect, since the `[0]` could not work in any situation (x1 is not an array, and Nim knows this).

**Comment by yglukhov** [comment]
@mcclure, it is easy to work around, and your bindings are not totally correct. This is a more correct way:
```nim
proc `[]=`*(t: TestType, key: float, val: float) {.importcpp:"#[#] = #".}
```
Note, that `var` keyword is not needed here, since you don't intend to modify the reference itself, but rather the content it points to. Omitting `var` keywork makes the codegen correct.

**Comment by mcclure** [comment]
@yglukhov Oh, that does work! At some point it was giving me errors if I did not include the `var` on `[]=`, but now it seems to work fine. I wonder what I was doing wrong before.

**Comment by Araq** [comment]
So ...? Close?
