### ISSUE TITLE
Nimscript: mvFile segfaults on Windows

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4731]
Running this with Nim that was built with `-d:release`:
```nim
"foo.txt".writeFile("content")
echo "This gets printed"
"foo.txt".mvFile("bar.txt")
echo "This does not get printed"
```
results in the following output:
```
This gets printed
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
The file still gets moved, however.
It seems to work when using Nim with `-d:debug`.

**Comment by yglukhov** [comment]
Looks a lot like what happens in #4724

**Comment by nigredo-tori** [comment]
Not entirely. For one, here we make sure the source file exists. Also, the error is different.
