### ISSUE TITLE
Documentation: add "edit this page" ribbon / button

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#4736]
Add "edit this page" ribbon or button to documentation pages published online.
The link should not be added to documentation pages released in packages, ebooks and so on.

Links will look like: https://github.com/nim-lang/Nim/edit/devel/lib/pure/os.nim
Example: https://ensime.github.io/
See discussion in http://forum.nim-lang.org/t/2397

**Comment by Araq** [comment]
This has already been implemented and will be online with the upcoming release.
