### ISSUE TITLE
nimfix: lib/system.nim(70, 25) Error: invalid indentation

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4740]
$ cat t.nim 
echo "Hello"
stefan@AMD64X2 ~/deltoday $ nimfix t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(70, 25) Error: invalid indentation

nimfix was installed with

nim c compiler/nimfix/nimfix.nim
mv compiler/nimfix/nimfix bin

**Comment by Araq** [comment]
nimfix either needs to be revived or die.

**Comment by StefanSalewski** [comment]
On Fri, 2016-09-09 at 12:05 -0700, Andreas Rumpf wrote:
> nimfix either needs to be revived or die.
> 

You may add a note to nimfix docu, make no sense to try it currently.

**Comment by krux02** [comment]
since the PR to revive nimfix got rejected, I concider nimfix as dead. If I am wrong this issue can be opened again.
