### ISSUE TITLE
proc int(o: OP): int = # shadows type conversion

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4742]
http://forum.nim-lang.org/t/2526

**Comment by Araq** [comment]
Not a bug. Note that if your wrapped would adhere to NEP-1 no such problem would arise. ;-)

**Comment by StefanSalewski** [comment]
On Fri, 2016-09-09 at 12:05 -0700, Andreas Rumpf wrote:
> Not a bug. Note that if your wrapped would adhere to NEP-1 no such
> problem would arise. ;-)
> 

It is NEP-1 generated by c2nim

But additional to 

proc getInt32*(value: GVariant): int32 {.importc: "g_variant_get_int32",

I have added by a script procs without get prefix like

proc int32*(value: GVariant): int32 {.importc: "g_variant_get_int32",

Generally fine, but not for this case.
