### ISSUE TITLE
Sometimes Channel tryRecv() erroneously reports no messages available on the first call on Windows

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4746]
As the title says... It's hard to reproduce and but it sometimes happens. Can't give you a concrete example because when I start modifying the code, the issue goes tends to go away... I'm running the same code on Linux and Windows, side by side, and with some constellation of the code it happens on Windows deterministically, while never on Windows.

Probably a bug in the abstraction of the OS-agnostic locking primitives or something...

**Comment by johnnovak** [comment]
Oh, and a second call to tryRecv() will return true correctly on Windows. I'm 100% sure that my queue has messages in it, I'm doing a long sleep before tryRecv() to make sure of this (it's a synthetic test case).

**Comment by Araq** [comment]
Why is that a bug? tryRecv can fail if acquiring the lock fails. That means it returns 'false' even though the channel is not empty, but being written to or read from somebody else. Makes sense, it's called *tryRecv*.

**Comment by johnnovak** [comment]
Ah, that makes sense then! However, the documentation of `tryRecv` says the following:

```
try to receives a message from the channel c if available. Otherwise it returns (false, default(msg)). 
```

I understand your explanation and it's fair enough that this is the case, but then the documentation should be updated accordingly. The docs should state that it is to be expected to get `false` sometimes, even though the channel might be non empty.

The wording "if available" implies "if the queue is non-empty". I think many people would be tripped up in this.
