### ISSUE TITLE
Name conflict between template and proc parameter

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4750]
This has confused me a few times:

``` nim
type
  O = object
    i: int

  OP = ptr O

template alf(p: pointer): untyped =
  cast[OP](p)


proc t1(al: pointer) =
  var o = alf(al)

proc t2(alf: pointer) =
  var x = alf
  var o = alf(x)
```

t.nim(15, 7) Error: invalid type: 'untyped'

**Comment by kierdavis** [comment]
Slightly off-topic: if you mark up your code block in the issue description like so:

    ```nim
    type
      O = object
    # etc.
    ```

then it will be displayed with monospaced font and syntax highlighting.

**Comment by Yardanico** [comment]
@StefanSalewski this seems to be fixed in devel
