### ISSUE TITLE
nimgrep PEG not capturing the pattern 'A'

### ISSUE THREAD

**Issue by xihh87** [nim-lang/Nim#4751]
I have a `file` containing the line: `ABC News`.

Where i use the command `nimgrep --peg "'B'" /path/to/file`, the output contains the line as expected.

When instead I use the command `nimgrep --peg "'A'" /path/to/file`, the output does not contain anything.

```
[joshpar@onyx regexp]$ nimgrep --peg "'A'" file
[joshpar@onyx regexp]$ nimgrep --peg "'B'" file
file
     2: ABC News
```

**Comment by enthus1ast** [comment]
If i change `ABC News` to `UABC News` then 'A' gets found. 
But `U` is not.
