### ISSUE TITLE
[RFC] Tutorial1 - Collaborative improvements

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#4752]
## Aim
Review each section of [Tutorial1] (http://http://nim-lang.org/docs/tut1.html) as a threaded discussion within THIS RFC

The end result will be a PR the collates all the suggested improvements (or actual proposed text) from this RFC

## What you need to do
- Read/work-through/review [Tutorial1] (http://nim-lang.org/docs/tut1.html)
- Identify missing content (that isn't in [Tutorial2] (http://nim-lang.org/docs/tut2.html) )
- Identify improvements or additions to the existing content
- Add your suggestions/comments/improvements as a **reply to the appropriate section** in this RFC (having checked that your ideas haven't already been suggested)

## Notes
Suggested changes may not actually be accepted (just like any PR), but don't let that stop anyone making suggestions (or putting in PRs)

Everyone will have different likes/dislikes/suggestions.  The end result will hopefully be a even better tutorial (not that what is there isn't already good).

There is nothing stopping you adding your ideas as your own PR.  This RFC is aiming to get consensus through discussion, and through leveraging many view points so that the current doco (tutorial1) may be improved even further.

If there are no improvements identified, then at least the tutorial will have been reviewed ready for the release of Nim v1.0

**Comment by jlp765** [comment]
## NEW SECTION to add to the tutorial
This is identifying a whole new section to the tutorial (not something new to an existing section)

**Comment by jlp765** [comment]
## INTRODUCTION section
Reply here about anything to do with the Introduction

**Comment by jlp765** [comment]
## THE FIRST PROGRAM
Reply here about anything to do "The first program" section

**Comment by jlp765** [comment]
## LEXICAL ELEMENTS
Reply here about anything to do "Lexical elements" section

**Comment by jlp765** [comment]
## THE VAR STATEMENT
Reply here about anything to do "The var statement" section

**Comment by jlp765** [comment]
## THE ASSIGNMENT STATEMENT
Reply here about anything to do with "The assignment statement" section

**Comment by jlp765** [comment]
## CONSTANTS
Reply here about anything to do with the "Constants" section

**Comment by jlp765** [comment]
## THE LET STATEMENT
Reply here about anything to do with "The let statement" section

**Comment by jlp765** [comment]
## CONTROL FLOW STATEMENTS
Reply here about anything to do with the "Control flow statements" section

**Comment by jlp765** [comment]
## STATEMENTS AND INDENTATION
Reply here about anything to do with the "Statements and indentation" section

**Comment by jlp765** [comment]
## PROCEDURES
Reply here about anything to do with the "Procedures" section

**Comment by jlp765** [comment]
## ITERATORS
Reply here about anything to do with the "Iterators" section

**Comment by jlp765** [comment]
## BASIC TYPES
Reply here about anything to do with the "Basic types" section

**Comment by jlp765** [comment]
## INTERNAL TYPE REPRESENTATION
Reply here about anything to do with the "Internal type representation" section

**Comment by jlp765** [comment]
## ADVANCED TYPES
Reply here about anything to do with the "Advanced types" section

**Comment by jlp765** [comment]
## MODULES
Reply here about anything to do with the "Modules" section

**Comment by Araq** [comment]
Why is that not simply a PR? ;-)

**Comment by jlp765** [comment]
I notice that it doesn't do threaded replies like I wanted.  
Does a PR allow threaded responses to comments?

**Comment by jlp765** [comment]
Closing, because issues are not threaded discussions
