### ISSUE TITLE
Cannot use {.async.} with anonymous proc

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4753]
``` nim
import asyncdispatch

proc awaitCb(cb: proc(): Future[void]) {.async.} =
  await cb()

awaitCb(proc(): Future[void] {.async.} =
  await sleepAsync(50))
```

This sample fails to compile with two errors:

```
Error: value of type 'proc (): Future[system.void]{.gcsafe, locks: <unknown>.}' has to be discarded
Error: value of type 'Future[system.void]' has to be discarded
```

**Comment by dom96** [comment]
Workaround:

```nim
import asyncdispatch

proc awaitCb(cb: proc (): Future[void]) {.async.} =
  await cb()

proc cb() {.async.} =
  await sleepAsync(50)

waitFor awaitCb(cb)
```

**Comment by endragor** [comment]
That workaround doesn't work if you need to capture some variables from outer scope.

**Comment by dom96** [comment]
Hrm, I investigated this for a bit and I don't think the async macro is to blame. It generates an AST which looks correct to me, I think this might be a compiler bug.

**Comment by dom96** [comment]
@Araq Please take a look when you get a chance.

**Comment by dom96** [comment]
Just ran into this again so I think it deserves another ping @Araq

**Comment by enthus1ast** [comment]
just pulled nim. 
is this maybe related somehow?

```nim
import asyncdispatch, asynchttpserver

when isMainModule:
  var foo = "foo"
  var server = newAsyncHttpServer()

  proc cb(req: Request): Future[void] {.async.} =
    await req.respond(Http200, foo)
  asyncCheck server.serve(Port(8080), cb )

runForever()
```

fails with

```nim
bug.nim(10, 20) Error: type mismatch: got (AsyncHttpServer, Port, proc (req: Request): Future[system.void]{.locks: <unknown>.})
but expected one of: 
proc serve(server: AsyncHttpServer; port: Port;
          callback: proc (request: Request): Future[void]; address = ""): Future[void]
```

**Comment by endragor** [comment]
I think the problem is that `cb` uses global GCed variable `foo` , which makes it not gc-safe.

**Comment by yglukhov** [comment]
The first snipped is wrong, isn't it? `awaitCb` implicitly returns `Future[void]`, so "it has to be discarded". Can we close this? @endragor?

**Comment by endragor** [comment]
Right, the snippet needs `waitFor` or `disacrd` before the call to `awaitCb`. It compiles now, so closing this, thank you.
