### ISSUE TITLE
Compiler crash with $, converter and generics

### ISSUE THREAD

**Issue by jdmansour** [nim-lang/Nim#4766]
I think I found a compiler bug. I don't expect the following minimal example to do anything sensible, but it should not crash the compiler.

``` nim
type
  Plain = ref object
    discard

  Wrapped[T] = object
    value: T

converter toWrapped[T](value: T): Wrapped[T] =
  Wrapped[T](value: value)

let result = Plain()
discard $result
```

You need a ref type (1), a generic type (2), a converter from 1 to 2, the converter must be called (implicitly or explicitly), and you must attept to use `$` on the result. If you change the converter to a proc, there is no crash. It also doesn't crash if you create the Wrapped instance directly (and comment out the converter!).

``` nim
type
  Plain = ref object
    discard

  Wrapped[T] = object
    value: T

# converter toWrapped[T](value: T): Wrapped[T] =
#   Wrapped[T](value: value)

let result = Plain()
let w = Wrapped[Plain](value:result)
discard $w  # doesn't crash
```

I am using a fairly recent Nim from git on Windows 10.

**Comment by Araq** [comment]
This is nasty to fix. The generic instantations cause an infinite recursive regress in the compiler.

**Comment by Clyybber** [comment]
@Araq Is there another way to fix it, which would make the example code work as expected?

**Comment by Araq** [comment]
Probably but that can be a separate enhancement.

**Comment by timotheecour** [comment]
simplified test case that doesn't rely on external import:
```nim
proc toString*[T](x: T) =
  for name, value in fieldPairs(x):
    when compiles(toString(value)):
      discard
    toString(value)

type
  Plain = ref object
    discard

  Wrapped[T] = object
    value: T

converter toWrapped[T](value: T): Wrapped[T] =
  Wrapped[T](value: value)

let result = Plain()
toString(result)
```
