### ISSUE TITLE
Source maps for js target

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#4772]
Source map generation will be a great improvement in front end debugging.

**Comment by r3d9u11** [comment]
@zah @Araq Hi! Is there any progress on this theme or plans to do it ? :)

**Comment by zah** [comment]
I've been using a pull request from @alehander42 for quite some time, but I guess it needs to be cleaned up a bit before Araq will be ready to merge it:

https://github.com/nim-lang/Nim/pull/7508

**Comment by ringabout** [comment]
Since #7508 is merged, could this issue be closed?
