### ISSUE TITLE
Cannot use generic field's iterators if the importing module doesn't import the field's owning module

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4773]
Consider the project containing two files, `queuecontainer.nim` and `main.nim` (samples below). `main.nim` doesn't compile, even though it should. This seems to be related to generic iterators.

``` nim
# queuecontainer.nim
import queues

type
  QueueContainer*[T] = object
    q: ref Queue[T]

proc init*[T](c: var QueueContainer[T]) =
  new(c.q)
  c.q[] = initQueue[T](64)

proc addToQ*[T](c: var QueueContainer[T], item: T) =
  c.q[].add(item)
```

``` nim
# main.nim
import queuecontainer

# works if this is uncommented (or if the `queuecontainer` exports `queues`):
# import queues

var c: QueueContainer[int]
c.init()
c.addToQ(1)
# lib/pure/collections/queues.nim(145, 17) Error: type mismatch: got (Queue[system.int])
# but expected one of:
# iterator pairs[T](a: openArray[T]): tuple[key: int, val: T]
# iterator pairs(a: string): tuple[key: int, val: char]
# iterator pairs[T](a: seq[T]): tuple[key: int, val: T]
# iterator pairs[IX, T](a: array[IX, T]): tuple[key: IX, val: T]
# iterator pairs(a: cstring): tuple[key: int, val: char]
```

**Comment by Araq** [comment]
I need to investigate what happens here.

**Comment by dom96** [comment]
Another workaround seems to be to use ``pairs`` explicitly in line 145.

**Comment by Araq** [comment]
This is currently simply not supported. Implicit names like ``items``, ``pairs`` or field injections via ``.this`` do not work in generics/templates.

**Comment by endragor** [comment]
Maybe the stdlib should be updated then to use items/pairs explicitly? The code presented in the sample is very straightforward and doesn't use anything implicit.

**Comment by Araq** [comment]
> Maybe the stdlib should be updated then to use items/pairs explicitly? The code presented in the sample is very straightforward and doesn't use anything implicit.

Well your example code already works, but it's a good point in general.
