### ISSUE TITLE
Building dynamic library: undefined references (Linux)

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4775]
Here's the gist with a simple project: https://gist.github.com/nigredo-tori/9f774894c38f7a6a607270a6a456ea20 (run `test.sh` to reproduce the issue)
I build a Nim file as a dynamic library, and use it from the C file. However, the linker fails:

```
./libfoo.so: undefined reference to `cmdCount'
./libfoo.so: undefined reference to `cmdLine'
collect2: error: ld returned 1 exit status
```

This seems to be triggered by importing the `logging` module. Emitting code that defines the corresponding C variables allows to work around the issue.

**Comment by vegansk** [comment]
The problem is in ``os`` module that exposes ``paramStr`` and ``paramCount`` functions when it shouldn't
