### ISSUE TITLE
tnewasyncudp.nim test loops forever

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#4777]
I'm unable to execute the rest of test because [this one](https://github.com/nim-lang/Nim/blob/devel/tests/async/tnewasyncudp.nim) never ceases to run. From my tests, client manages to send everything, whereas server awaits forever. Server is able to receive x bytes (the default buffer size for my computer is 8192). Sleeping the client does not help, and i don't have this problem with a non-async socket.
***
```Bash
>nim -v
Nim Compiler Version 0.14.3 (2016-09-15) [Windows: i386]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: 20b844ec53714170957abce87d67720cd1f29f22
active boot switches: -d:release
```

**Comment by dom96** [comment]
cc @cheatfate

**Comment by cheatfate** [comment]
Very strange, but i dont have 32bit windows to test.
Could you please test all other tests from async?
Is it possible that windows firewall blocks it?

**Comment by cheatfate** [comment]
@Wh1teDuke, I have made PR for issue with firewall. Could you please apply patch and then modify your firewall/antivirus to remove tnewasyncudp.exe from rules?

**Comment by Wh1teDuke** [comment]
>Could you please test all other tests from async?

I don't have any other issue with the rest of the tests in async except for tupcoming_async.nim with upcoming defined. If i run this test alone i get 'tupcoming_async.nim(17, 22) Error: undeclared identifier: 'AsyncEvent''. For some reason, if i run it with koch test it just run forever, sometimes even crashing explorer.exe (but this is probably a different issue)

>Is it possible that windows firewall blocks it?

To make sure it wasn't the firewall, i disabled it and i got the same result. The same with antivirus. But reducing the number of swarms to 7 solved the issue.

>Could you please apply patch and then modify your firewall/antivirus to remove tnewasyncudp.exe from rules?

Applying your [patch](https://github.com/nim-lang/Nim/pull/4781) didn't have any effect on the result.

**Comment by cheatfate** [comment]
@Wh1teDuke what version of Windows you are using?

**Comment by cheatfate** [comment]
About `tupcoming_async.nim`. Something wrong with your Nim. 
If `tests/async/config.nims` present and `lib/upcoming/asyncdispatch.nim` present, then for some reason `config.nims` is not working...

**Comment by cheatfate** [comment]
I have installed windows 7 32bit and reproduced this issue. And now i understand why it happens. You was right about network buffers overflow. But more important problem is `sendTo()` operation completes immediately and `poll()` not called, so all 5000 messages will be stored in network buffers.
I will modify test in my next PR.

**Comment by cheatfate** [comment]
About `tupcoming_async.nim` test. I still can't reproduce it. Everything is fine on my Windows 7 x86.

**Comment by Wh1teDuke** [comment]
Fixed, thanks.
