### ISSUE TITLE
SIGSEGV when trying to define generic procedure

### ISSUE THREAD

**Issue by mohamedmoussa89** [nim-lang/Nim#4787]
The following will fail to compile 

``` nim
type Vector[T: int|float, N:static[int]] = array[N, T]

proc `+`[T,N](lhs: Vector[T,N], rhs: Vector[T,N]) : Vector =
  for i in 0..high(lhs) :
    result[i] = lhs[i] + rhs[i]

let A: Vector[int, 3] = [1,2,3]
let B: Vector[int, 3] = [4,5,6]

echo repr(A+B)
```

Error message

```
'SIGSEGV: Illegal storage access. (Attempt to read from nil?)'
```

Changing line 3 to any of the following will work

``` nim
proc `+`[T,N](lhs: Vector[T,N], rhs: Vector) : Vector =
proc `+`[T,N](lhs: Vector, rhs: Vector[T,N]) : Vector =
proc `+`(lhs: Vector, rhs: Vector) : Vector =
```

**Comment by krux02** [comment]
As you can see, this issue tracker is really overflowing with issues. So it would really be nice when the the cause of this problem can be analyzed, too. And then the true cause should be in the titile.

**Comment by Araq** [comment]
Fails with 'Error: cannot generate code for: N', not with a compiler crash.

**Comment by zah** [comment]
There is no bug here. Since the plus proc is not implicitly generic, the `Vector` type name used as the return type is not bound to any particular type and the compiler currently reports `cannot instantiate: 'Vector'`.

The correct code is
``` nim
type Vector[T: int|float; N:static[int]] = array[N, T]

proc `+`[T,N](lhs: Vector[T,N], rhs: Vector[T,N]): Vector[T, N] =
  for i in 0..high(lhs) :
    result[i] = lhs[i] + rhs[i]

let A: Vector[int, 3] = [1,2,3]
let B: Vector[int, 3] = [4,5,6]

echo repr(A+B)
```

or with implicit generics:

``` nim
type Vector[T: int|float; N:static[int]] = array[N, T]

proc `+`(lhs, rhs: Vector): Vector =
  for i in 0..high(lhs) :
    result[i] = lhs[i] + rhs[i]

let A: Vector[int, 3] = [1,2,3]
let B: Vector[int, 3] = [4,5,6]

echo repr(A+B)
```

**Comment by TiberiumN** [comment]
@zah but anyway any compiler crash should be fixed, so error message would be displayed

**Comment by zah** [comment]
Yes, the latest compiler displays a proper error, it doesn't crash.
