### ISSUE TITLE
seq namespace (?) regression

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4796]
Trying to compile the following code from the official tutorial

```
var
  x: seq[int]
```

will result in a compilation error:

```
seq.nim(2, 6) Error: ambiguous identifier: 'seq' --use unknown.seq or system.seq
```

Tested with 0.14.2 and the current dev branch (0.14.3).

**Comment by dom96** [comment]
It's because you named the file ``seq`` :)

**Comment by dom96** [comment]
Not sure why the error message shows ``unknown``, I think it should show ``use seq.seq or system.seq``.

**Comment by johnnovak** [comment]
Oh man, that's embarassing... I would never have figured out that this was causing it! Thanks for pointing it out! :)

**Comment by andreaferretti** [comment]
I am getting the correct error message now (use `playground.seq` or `system.seq')

**Comment by dom96** [comment]
Still getting the same error (you need to name the file 'seq'):

```
/Users/dom/temp_code/seq.nim(2, 6) Error: Error: ambiguous identifier: 'seq' --use unknown.seq or system.seq
```

**Comment by andreaferretti** [comment]
I did name it `seq` and got the error message I mentioned. I guess it is because I have a `playground.nimble` file. As far as I can tell `unknown.seq` means the `seq` module in the `unknown` nimble package.

**Comment by dom96** [comment]
That's another bug then, you can't disambiguate by nimble package name, only by the module name.

**Comment by andreaferretti** [comment]
Well, you **can** disambiguate by nimble package name, although

* not for the current package (i.e. the one you are working in), and
* for a specific version

The syntax is like this

 ```nim
import "random-0.5.3/random"
```

**Comment by dom96** [comment]
That's disambiguating by directory, not nimble package :)

**Comment by TiberiumN** [comment]
Well can we close it?
Because this code wouldn't compile at all - because x is redefined

**Comment by dom96** [comment]
Nope. Can't close until the error message improves.

**Comment by data-man** [comment]
Nim-devel now outputs
<pre><b>(3, 3) </b><font color="#DC322F">Error: </font>redefinition of &apos;x&apos;</pre>

**Comment by ghost** [comment]
This seems to work properly now:
```
~/P/stuff ❯❯❯ cat seq.nim
var
  x: seq[int]

~/P/stuff ❯❯❯ nim c -r seq.nim
Hint: used config file '/home/dian/Things/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/dian/Things/Nim/config/config.nims' [Conf]
Hint: used config file '/home/dian/nim.cfg' [Conf]
....
/home/dian/Projects/stuff/seq.nim(2, 3) Hint: 'x' is declared but not used [XDeclaredButNotUsed]
Hint:  [Link]
Hint: 21739 lines; 0.114s; 25.566MiB peakmem; Debug build; proj: /home/dian/Projects/stuff/seq.nim; out: /home/dian/Projects/stuff/seq [SuccessX]
Hint: /home/dian/Projects/stuff/seq  [Exec]
```

Close?

**Comment by ghost** [comment]
It even works with this:
```nim
# seq.nim
var seq: seq[int]
var b: seq[float]

echo seq
echo b
```
