### ISSUE TITLE
realloc leaks

### ISSUE THREAD

**Issue by Tormund** [nim-lang/Nim#4818]
realloc leaks memory on windows, when application compiled in 32bit
Leak appears only if buffer size growth and I got out of memory, for example:

```
const BUFFER_SIZE = 5000
var buffer = cast[ptr uint16](alloc(BUFFER_SIZE))

var total_size: int64 = 0
for i in 0 .. 4_000:
    let size = BUFFER_SIZE * i
    total_size += size.int64
    buffer = cast[ptr uint16](realloc(buffer, size))

dealloc(buffer)
```

But if I replace nim's alloc, realloc, dealloc to c_malloc, c_realloc, c_free, I don't have out of memory. Like this:

```
const BUFFER_SIZE = 5000
var buffer = cast[ptr uint16](c_malloc(BUFFER_SIZE))

var total_size: int64 = 0
for i in 0 .. 4_000:
    let size = BUFFER_SIZE * i
    total_size += size.int64
    buffer = cast[ptr uint16](c_realloc(buffer, size.csize))

c_free(buffer)
```

**Comment by kirbyfan64** [comment]
http://stackoverflow.com/a/4548441/2097780

No clue about the out-of-memory issue, but the leak itself isn't a Nim bug.

**Comment by yglukhov** [comment]
Nim realloc != c realloc, and has nothing to do with it. Most definitely looks like a Nim bug.

**Comment by cheatfate** [comment]
@kirbyfan64 please add `doAssert(buffer != nil)` because you don't check anything in your c_xxxxxx example, and c_realloc can work even in such case.

**Comment by Tormund** [comment]
@cheatfate. I do mistake in sample code, to try realloc with zero buffer size (got assertion) in first iteration.
So this sample with c_realloc work's perfectly:
```
const BUFFER_SIZE = 5000
var buffer = cast[ptr uint16](c_malloc(BUFFER_SIZE))

var total_size: int64 = 0
for i in 1 .. 4_000:
    let size = BUFFER_SIZE * i
    total_size += size.int64
    buffer = cast[ptr uint16](c_realloc(buffer, size.csize))
    doAssert(buffer != nil)
c_free(buffer)
```
But same code with Nim realloc still don't work, and I don't got my assertion(`doAssert(buffer != nil)`). Looks like app execution stoped somewhere from realloc proc.

**Comment by Araq** [comment]
realloc does deallocate and the problem is likely address space fragmentation.

**Comment by cheatfate** [comment]
I think problem not in fragmentation, but in algorithm of nim's realloc. At one moment of time it tries to allocate on big memory block, while holding another one big memory block (before copyMem). And c_realloc don't do this.

**Comment by cheatfate** [comment]
Ok, this is bug, on my Windows x64 it eats 20Gb of memory.
