### ISSUE TITLE
bind does not work with prefix notation

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4823]
test1.nim:

``` nim
proc fooInc(i: var int): i += 1

template doFooInc*(val: typed) =
  bind fooInc
  # Error: attempting to call undeclared routine: 'fooInc'
  #val.fooInc()
  # works
  fooInc(val)
```

test2.nim:

``` nim
import test1
var i = 1
i.doFooInc()
```

**Comment by Araq** [comment]
Seems fair to me, ``bind`` means you want clear binding rules. The dot notation rewrite rule is anything but clear.

**Comment by flyx** [comment]
`bind` means, according to the manual:

> It can be used to explicitly declare identifiers that should be bound early [...]

Which is exactly what I'm doing here. Maybe if this is not how it is expected to work, the manual should be updated?

**Comment by krux02** [comment]
if you replace ``proc fooInc(i: var int): i += 1`` with ``proc fooInc(i: var int) = i += 1`` you example works now.
