### ISSUE TITLE
Streamed futures

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4829]
A special case of future that provides a stream of data, useful for large sets of data such as for large http requests.

**Comment by nigredo-tori** [comment]
Could you please give a short code example of the desired API? It's not clear what exactly you propose, and what use cases would it serve.
Also, what is the difference with, say, [asynchronous streams](https://github.com/vegansk/nimboost/blob/master/src/boost/io/asyncstreams.nim) approach from nimboost? Why do we need to modify `Future`?

**Comment by dom96** [comment]
> Could you please give a short code example of the desired API?

Haven't worked that out yet.

> It's not clear what exactly you propose, and what use cases would it serve.

The use case I have in mind is a ``downloadFile`` procedure for the ``httpclient``. Instead of waiting for the full file to be received and saved in memory then written to memory, we need something that will allow us to save it to a file in chunks.

> Also, what is the difference with, say, asynchronous streams approach from nimboost?

I only skimmed it but this seems to just be a copy of the ``streams`` interface but made async, not really what I have in mind. 

> Why do we need to modify ``Future``?

I never said that we need to modify it, did I?

**Comment by nigredo-tori** [comment]
> Instead of waiting for the full file to be received and saved in memory then written to memory, we need something that will allow us to save it to a file in chunks.

Did almost that with async streams. It's your standard imperative stream copy, with few `await` keywords here and there. So this case seems to be covered.

> I never said that we need to modify it, did I?

OK, sorry I misinterpreted your words ("A special case of future").

 So what problems do you see with a `streams`-like API in asynchronous scenario? Are you thinking along the lines of some cosmetic API changes? Or about some other abstraction altogether, like enumerators/iteratees in Scala?

**Comment by dom96** [comment]
In general I'm not the biggest fan of the ``streams`` API, but I would need to look into your async version more.

**Comment by andreaferretti** [comment]
Just wanted to mention that this will be useful for Rosencrantz as well. [Here](https://github.com/andreaferretti/rosencrantz/blob/master/rosencrantz/staticsupport.nim#L39) I have some preliminary support to return large files by using transfer-encoding: chunked. I would like to support this also for custom data produced by users, but I miss a standard library data type that I can use to express a stream of incoming data

**Comment by dom96** [comment]
This is now implemented via the ``FutureStream`` type.
