### ISSUE TITLE
Idetools --suggest provides incorrect answers

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#484]
When using the ``--suggest`` idetools switch, the answers should be context sensitive, but they aren't. When you use the dot syntax to write ``variable.foo`` and query completions for foo* procs, idetools answers with procs matching the beginning prefix which don't have as first parameter the parameter type of the variable preceeding the proc, or even procs which don't accept parameters at all, which is absolutely wrong.

Maybe it is impossible for idetools to know that the dot syntax is being used and it considers the prefix alone without the variable type info?

**Comment by Araq** [comment]
nimsuggest has its own bug tracker now.
