### ISSUE TITLE
httpclient: remove preamble for multipart (postContent)

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4854]
New `postContent` implementation (the one that takes a client) adds an extra empty line before the body when using MultipartData. This line becomes a preamble: [RFC1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). The resulting HTTP is technically valid; however, a google search shows quite a few bugs with applications not expecting a preamble. It seems that not using preamble is more compatible.
Deprecated `postContent` implementation (without client) does not have this problem.
Related issue with Jester: https://github.com/dom96/jester/issues/86

**Comment by dom96** [comment]
I tested the script in the linked issue and it works correctly. Perhaps this was fixed on the meantime? Feel free to reopen if not.
