### ISSUE TITLE
async makes generics instantiate only once

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4856]
(Possibly related to #3568, which I cannot reproduce)
Adding `async` macro to a generic proc makes it only instantiate once, but behave like it was instantiated multiple times. For example:
```nim
import asyncdispatch

proc say[T](t: T): Future[void] {.async.} =
  echo $t

waitFor(say(123))
waitFor(say("abc"))
```
Output:
```
123
139977063424120
```
The following workaround seems to work:
```nim
proc say[T](t: T): Future[void] =
  proc impl() {.async.} =
    echo $t

  impl()
```

**Comment by nigredo-tori** [comment]
Actually, the workaround doesn't work for more substantial cases. Seems like `async` runs before the outer proc is instantiated, so it breaks somewhere on encountering a type parameter.
In my case I had to make the proc non-generic, changing all generic values to `ref object`s with corresponding casts and wrapping other generic  procs accordingly.

**Comment by endragor** [comment]
Returning Future[T] still doesn't work for `void` case:
```nim
import asyncdispatch

proc foo[T](): Future[T] {.async.} =
  discard

foo[int]().callback = proc() = echo "OK int"
foo[void]().callback = proc() = echo "OK void"

poll() # to invoke the callbacks

# lib/pure/asyncmacro.nim(301, 7) Hint: Processing foo as an async proc. [User]
# sample.nim(7, 4) template/generic instantiation from here
# sample.nim(4, 3) Error: invalid type: 'void'
```

**Comment by ephja** [comment]
Should this be re-opened then?
