### ISSUE TITLE
Generic macro to interface with JS bindings

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4859]
When interfacing with existing js libraries, one often needs to pass some functions an object containing options. Usually, these objects have many fields, and the user only sets the relevant ones. An example may be the `settings` in [jquery.ajax](http://api.jquery.com/jquery.ajax/) function, the [attributes in React components](https://facebook.github.io/react/docs/tags-and-attributes.html) and so on.

One can create custom types for these options, but usually these end up with [many fields](https://github.com/andreaferretti/react.nim/blob/master/react.nim#L28). If one creates instances of such types with only a few parameters, the remaining ones end up populated with `null`. This is an issue for two reasons:
- objects are much bigger than needed, but more important
- `null` may be an actual valid value for such objects.

Hence the need to create such objects and only populate part of the fields. As an example, let me take the following type

``` nim
type Foo = ref object
  a {.exportc.}, b {.exportc.}: cint
  c {.exportc.}: cstring
```

One can create a macro to generate an instance of `Foo` with only some fields like follows:

``` nim
import macros

macro foo(xs: varargs[untyped]): Foo =
  let a = !"a"
  var body = quote do:
    var `a` {.noinit.}: Foo
    {.emit: "`a` = {};" .}

  for x in xs:
    if x.kind == nnkExprEqExpr:
      let
        k = x[0]
        v = x[1]
      body.add(quote do:
        `a`.`k` = `v`
      )
    else:
      error("Expression `" & $x.toStrLit & "` not allowed in `foo` macro")

  body.add(quote do:
    return `a`
  )

  result = quote do:
    proc inner(): Foo {.gensym.} =
      `body`

    inner()
```

to be used like follows

``` nim
let x = foo(b = 1)
echo x.b
```

So far, so good.

The problem I am trying to solve is how to make this generic. Just making the macro generic

``` nim
macro lit[T](xs: varargs[untyped]): T =
  let a = !"a"
  var body = quote do:
    var `a` {.noinit.}: T
    {.emit: "`a` = {};" .}

  for x in xs:
    if x.kind == nnkExprEqExpr:
      let
        k = x[0]
        v = x[1]
      body.add(quote do:
        `a`.`k` = `v`
      )
    else:
      error("Expression `" & $x.toStrLit & "` not allowed in `lit` macro")

  body.add(quote do:
    return `a`
  )

  result = quote do:
    proc inner(): T {.gensym.} =
      `body`

    inner()
```

and then

``` nim
let x = lit[Foo](b = 1)
echo x.b
```

fails with `Error: Expression "b" not allowed in`lit`macro` (hence the macro is not passed an `nnkExprEqExpr` node). I think this is a compiler bug

**Comment by mjendrusch** [comment]
There seems to be some kind of error, when using a generic macro together with `varargs`. I took a quick look at what is actually passed into the macro, and noticed, that indeed, `xs.kind` is not `nnkBracket` as expected, but instead `nnkExprEqExpr`. This causes the `for`-loop to iterate through the children of `b = 1`, which results in macro failure. This behaviour also seems to hold for generic `template`s together with `varargs`. This seems to point to a bug in passing `varargs` to generic macros / templates.

A quick workaround, without using generics, would be the following:

```nimrod

macro lit(xs: varargs[untyped]): auto =
  assert(xs.len > 1)
  let typ = xs[0]
  let a = !"a"
  var body = quote do:
    var `a` {.noinit.}: `typ`
    {.emit: "`a` = {};".}

  for idx in 1..xs.len-1:
    let x = xs[idx]
    if x.kind == nnkExprEqExpr:
      let
        k = x[0]
        v = x[1]
      body.add(quote do:
        `a`.`k` = `v`
      )
    else:
      error("Expression `" & $x.toStrLit & "` not allowed in `lit` macro")

  body.add(quote do:
    return `a`
  )

  result = quote do:
    proc inner(): `typ` {.gensym.} =
      `body`
    inner()
```

then called like:

```nimrod
let x = lit(Foo, b = 1)
```

another approach for a workaround would be to not rely on `varargs`,
but on `quote` and `nnkStmtList`:

```nimrod
macro lit1(T: typedesc, xs: untyped): auto =
  let a = !"a"
  var body = quote do:
    var `a` {.noinit.}: `T`
    {.emit: "`a` = {};".}

  let sList = xs[6]
  for x in sList:
    if x.kind == nnkAsgn:
      let
        k = x[0]
        v = x[1]
      body.add(quote do:
        `a`.`k` = `v`
      )
    else:
      error("Expression `" & $x.toStrLit & "` not allowed in `lit` macro")

  body.add(quote do:
    return `a`
  )

  result = quote do:
    proc inner(): `T` {.gensym.} =
      `body`
    inner()
```

called like:

```nimrod
let x = lit(Foo) do:
  b = 1
  c = "foobar"
```

I hope this somewhat helps solve this issue.

**Comment by andreaferretti** [comment]
Great, your first example works for me. It is a little weird to have `Foo` as one of the arguments but for now it does the trick!

**Comment by mjendrusch** [comment]
Weird and hackish it is, but pretty nice in terms of syntax, it also works like this:

```nimrod
let x = Foo.lit(b = 1)
```

Then it looks quite natural, like a static method of `Foo`.

**Comment by andreaferretti** [comment]
Really nice, great! :-)

**Comment by Araq** [comment]
That is now in devel. Closing.
