### ISSUE TITLE
rst2html dumps JavaScript stuff to output

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4865]
`nim rst2html`, if used without a custom `nimdoc.cfg`, dumps the following lines into the output:

``` html
<script type="text/javascript" src="../dochack.js"></script>

<script type="text/javascript">
function togglepragma(d) {
  // ...
}

function main() {
  // ...
}
</script>
```

(shortened for readability)

These seem to be related to docgen, but useless for custom rST processing, so they should not be dumped here.

**Comment by Araq** [comment]
Can't reproduce. ``nim rst2html readme.txt`` works just fine.
