### ISSUE TITLE
startProcess changes working directory

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4867]
```nim
import os, osproc

echo getCurrentDir()
var process = startProcess("/usr/bin/true", "/usr/bin")
echo getCurrentDir()
discard process.waitForExit()
process.close()
```

Output:

```
/Users/flyx/Projects/NimYAML                                                                                                                                                                                
/usr/bin
```

The `workingDir` parameter of `startProcess` apparently does not only change the working directory of the started process, but also of the application itself.

**Comment by cheatfate** [comment]
@flyx just to be sure what OS and what flags you have used when compiling?

**Comment by flyx** [comment]
@cheatfate I am on OSX, mostly on current devel, where I found this problem. I did not use any flags.
