### ISSUE TITLE
search hack in generated offline doc is broken / still visible

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#4868]
when documentation is generated with
`nim doc file.nim` the search hack is unusable / not there / still visible

**Comment by timotheecour** [comment]
* works now for `./koch docs`, see instructions here: https://github.com/nim-lang/Nim/issues/8952#issuecomment-453877225
* didn't close because I think we could try to support search (eg via dochack.js) for third party projects too, not just Nim's docs

**Comment by narimiran** [comment]
> didn't close because I think we could try to support search (eg via dochack.js) for third party projects too, not just Nim's docs

Out of the scope. Closing as the original issue is solved.
