### ISSUE TITLE
staticRead and staticExec have different working directories

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#4871]
Given the following directory structure:

 * folder
   * code.nim
   * test.txt
 * test.txt

With the following file content:

#### folder/code.nim

```nim
static:
  echo staticExec("pwd")
  echo staticRead("test.txt")
```

#### folder/test.txt

```
child
```

#### test.txt

```
parent
```

I execute at the root directory:

```
nim c folder/code.nim
```

And the output is:

```
/Users/flyx/Projects/NimYAML                                                                                                                                                                                
child
```

So, `staticExec` uses the current working directory, while `staticRead` uses the source file's location. This is inconsistent (and undocumented) and should be fixed one way or the other.

**Comment by genotrance** [comment]
I mentioned this in IRC but given both staticExec and staticRead now use the source file's location, you cannot do something like the following using relative paths:-

```nim
macro load(filename: static[string]): untyped =
  if fileExists(filename):
    echo staticRead(filename)
```

This is because staticRead() is using the source directory to look for filename whereas fileExists() checks the working directory. At the very least, this needs to be documented. Ideally it is also made possible to use the working directory instead of changing to source dir since it is very counter intuitive the way it is right now.

**Comment by 0atman** [comment]
AHA! This caught me out. So while https://github.com/nim-lang/Nim/commit/39f03d816c2399ba44f0d88a8d4fd532ed8dfcfd did make the behavior more consistent with staticExec - it didn't fix the lack of documentation, as @genotrance suggested.

In fact, I'd say the documentation is not just lacking, but misleading:

> [staticRead is a] Compile-time readFile proc for easy resource embedding

Sounds like `staticRead` is a compile-time readFile, eh? It is not: The working directories are different.

**Comment by hoijui** [comment]
ouh mam ...

Is there a way to - at compile-time - get both the path to the project root dir, and the path to the file?
Then I could  first always come up with an absolute path of whatever file I deal with, and so would not have to worry about the different functions using different CWDs.

This feels a lot like BASH scripting, just with less control or oversight for the programmer.

**Comment by flyx** [comment]
@hoijui [currentSourcePath](https://nim-lang.org/docs/system.html#currentSourcePath.t), [getProjectPath](https://nim-lang.org/docs/macros.html#getProjectPath)
