### ISSUE TITLE
RFC: improving JavaScript FFI

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4873]
I have had some experience in compiling Nim to Js while writing [bindings for React](https://github.com/andreaferretti/react.nim). After this experience, and taking inspiration from Scala.js, I think there is the opportunity to streamline the FFI a little. Everything I suggest in the following should be doable in the stdlib, with no changes to the compiler. If there is interest in the proposal, I can try to help with the task.

I suggest the introduction of a module `jsffi` that contains some types and macros useful while interfacing with JavaScript. Here are the use cases:

1) When interfacing with existing js libraries, one often needs to pass some functions an object containing options. Usually, these objects have many fields, and the user only sets the relevant ones. An example may be the `settings` in [jquery.ajax](http://api.jquery.com/jquery.ajax/) function, the [attributes in React components](https://facebook.github.io/react/docs/tags-and-attributes.html) and so on.

One can create custom types for these options, but usually these end up with many fields. All these fields need to be declared with `{.exportc.}` to avoid name mangling. As seen in [this example](https://github.com/andreaferretti/react.nim/blob/master/react.nim#L28), this get rapidly out of control. I think one could create some macro to automate all the `exportc` declarations.

2) If one creates instances of such types with only a few parameters, the remaining ones end up populated with `null`. This is an issue for two reasons:
- objects are much bigger than needed, but more important
- `null` may be an actual valid value for such objects.

The `lit` macro [suggested by @mjendrusch in this issue](https://github.com/nim-lang/Nim/issues/4859) (and started with help from @oderwat in the forums) could be included in the module to help with such cases. It allows users to write

``` nim
type Foo = ref object
  a {.exportc.}, b {.exportc.}: cint
  c {.exportc.}: cstring

let x = Foo.lit(b = 1, c = "hello")
```

3) The manual [suggests](http://nim-lang.org/docs/manual.html#special-operators-operator) that the `.`, `.()` and `.=` operators can be overriden to interface with dynamic languages.

In the spirit of Scala [Dynamic](http://www.scala-lang.org/api/current/index.html#scala.Dynamic) I suggest to have a standard type `JsObject` in `jsffi` where such operators are in fact overriden with the corresponding member access in JS, to make [quick and dirty](https://www.scala-js.org/doc/interoperability/types.html#dynamically-typed-interface-jsdynamic) interfacing easier

4) A macro `jsObj` similar to the one in point 2 could generate literal instances of javascript objects having type `JsObject`. From the point of view of the user, generating instances of `JsObject` would simply be

``` nim
let x: JsObject = jsObj(
  a = 1,
  b = "hello",
  c = true
)
```

In fact, the macro in point 2 could become the macro `jsObj` plus a cast to the correct type.

5) Sometimes, one needs to pass objects with methods to an external API. Such methods may need to refer to the `this` object, which in javascript is dynamically bound. An example is writing React components, where one needs to provide methods such as `componentDidMount` - such methods will need to refer to the `this` object to access `this.props` and `this.state`.

The trick, shown to me by Oderwat, is to use

``` nim
var this {.importc,nodecl.}: C
```

inside the method body, where `C` is the type of `this`. Using this I have been able to write [a macro](https://github.com/andreaferretti/react.nim/blob/master/react.nim#L203) that allows users to write `componentDidMount` and such as normal procs, where `this` is passed as the first argument.

I suggest that a similar macro, more general than the one I use here, should be added in `jsffi` to make it easy to attach javascript methods to objects.

**Comment by dom96** [comment]
All of this sounds good. Go for it :)

**Comment by oderwat** [comment]
Sounds like something in the lines of: https://github.com/oderwat/nim-screeps/blob/master/src/jsext.nim ... Which uses "JSAssoc" instead of "JSObject" because it erupted from some PHP extension we made. Would be for sure a cool thing to have this streamlined in the stdlibs.

**Comment by andreaferretti** [comment]
Yeah, I think such patterns should be centralized because they are useful for everybody. I will try to put down some preliminary example and share what I come up with. Thank you for the link!

**Comment by mjendrusch** [comment]
I had quite a bit of time on my hands today, so I made a macro to address the first issue of mapping
a pragma over all objects' fields in a type section. This is what I came up with:

https://gist.github.com/mjendrusch/b09478d37ea93dee181e0b1838bfe26b

As I seem to have a lot of time on my hands recently, and JavaScript + Nim is getting more and more relevant for me, I would be glad to help with this if no one has any objections :-)

**Comment by dom96** [comment]
I don't think such a macro should be necessary. Nim needs to improve in
this case to not require these importc/exportc  pragmas for each field.

But thank you for taking the time. It will be useful in the meantime. Help
is always welcome :)

**Comment by andreaferretti** [comment]
@mjendrusch Great, thank you for your help! In fact, I am quite short on time these days, so if you are willing to contribute, I'd be very happy! I will write here some gists if I come up with solutions for the other points :-)

**Comment by mjendrusch** [comment]
Ok, so I made a quick attempt at solving 5, and found, that 4 is already solved:
So for 5 this is the macro:

https://gist.github.com/mjendrusch/1bed6eb2de838aea59ae1fd1d0c29fc2

For four, the `lit` macro would work fine, if `JsObject` were basically a wrapper around
JavaScript's objects `{}`.
Then
```nim
var a = JsObject.lit(
  x = 42,
  y = "foo"
)
```

would roughly produce that code, which would work well with such an implementation of `JsObject`:

```javascript
var a = {};
a.x = 42;
a.y = "foo";
```

**Comment by mjendrusch** [comment]
A first draft of JsObject functionality, with partial type-inference:

https://gist.github.com/mjendrusch/8d059d9bbbc7a407ed56aed8d8e48c50

This implements `.` and `.=` to infer as much type information from the assignments
as possible, to keep track of the types of all fields of a JsObj.
Example:

```nimrod
var foo = newJsObj()
foo.x = 42
# compiles:
let x: int = foo.x
foo.x = "bar"
# compiles:
let baz: string = foo.x
# does not compile:
let foobar: int = foo.x
```

**Comment by andreaferretti** [comment]
@mjendrusch Wow, you are making all this progress before I even find a moment to look at the problem! Really good!

I am looking forward to seeing a PR with all these goodies :-)

**Comment by yglukhov** [comment]
I'll just leave it here in case anyone needs it...
```nim
import macros

# Private
proc jsDictLiteral(): RootRef {.varargs, importcpp: "{@}".}
template convertSomethigToJs(s: string): RootRef = cast[RootRef](cstring(s))
proc convertSomethigToJs[T](s: T): RootRef {.importcpp: "#".}

proc dictPairLiteral(k: cstring, v: RootRef): RootRef {.importcpp: "#:#".}

proc jsdictImpl(d: NimNode): NimNode =
    d.expectKind(nnkTableConstr)
    result = newCall(bindsym"jsDictLiteral")
    for c in d:
        var key = c[0]
        if key.kind == nnkIdent:
            key = newLit($key)
        let val = c[1]
        result.add(newCall(bindsym"dictPairLiteral", key, newCall(bindsym"convertSomethigToJs", val)))

# Public
macro `@@`*(d: untyped): untyped = jsdictImpl(d)
macro jsdict*(d: untyped): untyped = jsdictImpl(d)

# Tests
when isMainModule:
    proc consoleLog() {.varargs, importcpp: "console.log(@)".}
    consoleLog(@@{hi: 123, bye: 456, blabla: "asdf"}) # Generated code: console.log({"hi":123, "bye":456, "blabla":"asdf"});
    let d = @@{
        hi: 123, bye: 456, blabla: "asdf"
    } # Generated code: var d_29103 = {"hi":123, "bye":456, "blabla":"asdf"};
    consoleLog(d)
```

**Comment by andreaferretti** [comment]
@mjendrusch Shall I make a PR with the work done so far (adding some tests, docs and so on)? Or do you prefer to make it yourself? I know not everything is done, but I think the utilities here are already useful

**Comment by mjendrusch** [comment]
@andreaferretti I should be able to finish the JsObject with flow-sensitive typing somewhere within the next few days, perhaps even by monday, it took a lot longer to get it right than I expected ...
Maybe we could wait until then, and see if we should include the JsObject-with-typechecking stuff, or if the metaprogramming involved is a bit too experimental

**Comment by andreaferretti** [comment]
Great, thank you!

**Comment by andreaferretti** [comment]
@mjendrusch Any news? I think the work you have done so far would be worthy of inclusion nevertheless!

**Comment by mjendrusch** [comment]
@andreaferretti I'm sorry, work happened, and I kind of forgot about this, but now it's done. I submitted a pull request now, albeit without type checking for the `JsObjects`, as the approaches I tried to implement that did not scale beyond simple examples.

**Comment by andreaferretti** [comment]
I had a brief look at your PR: I think it makes a great addition to the standard library! :-)

**Comment by Araq** [comment]
Most of these have been dealt with. Close?

**Comment by andreaferretti** [comment]
Close :-)
