### ISSUE TITLE
Windows CMD arguments limitations

### ISSUE THREAD

**Issue by Tormund** [nim-lang/Nim#4876]
On Windows OS we have limitations for arguments passed through command line - 32,768 characters.
Now nim passes arguments to the compiler from the command line.
Soon we will reach the limit of 32,768 characters. I got 14,842 characters in arguments at linking.
https://support.microsoft.com/en-us/kb/830473

**Comment by Araq** [comment]
What can we do as a workaround? Shorten every path into a relative one? Anything else?

**Comment by kirbyfan64** [comment]
@Araq For MSVC: https://msdn.microsoft.com/en-us/library/x2khzsa1.aspx

**Comment by Tormund** [comment]
up

**Comment by Tormund** [comment]
We can use @ option in vcc, gcc and clang

**Comment by Araq** [comment]
The compiler does do that these days.

**Comment by Tormund** [comment]
So this issue is closed?
