### ISSUE TITLE
./koch web from 0.15 is freezing

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#4877]
./koch web is freezing during while running "./tools/nimweb web/website.ini --putenv:nimversion=0.15.0".

The freeze happens with the following processes 4 being executed:
`bin/nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.15.0 --git.url:https://github.com/nim-lang/Nim -o:web/upload/asynchttpserver.html --index:on lib/pure/asynchttpserver.nim`
...and same for htmlgen.nim, httpclient.nim, smtp.nim

During the lockup strace shows:
asynchttpserver: write(2, "Processing serve as an async proc.", 34
smtp: write(2, "Processing connect as an async proc.", 36
httpclient: write(2, "template/generic instantiation from here", 40
htmlgen: write(2, " [Deprecated]", 13

Steps to reproduce: `tar xfJ nim-0.15.0.tar.xz;
cd nim-0.15.0;
sh build.sh;
./bin/nim c koch.nim;
./koch web`

Workaround: `./koch web --parallelbuild:1`

**Comment by Araq** [comment]
Could never reproduce, still a problem?

**Comment by FedericoCeratto** [comment]
It still happens with 0.16.0

Running `bin/nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off --putenv:nimversion=0.16.0 --git.url:https://github.com/nim-lang/Nim -o:doc/html/httpcore.html --index:on lib/pure/httpcore.nim` directly completes successfully

Running `/tools/nimweb --onlyDocs web/website.ini --putenv:nimversion=0.16.0` locks up

**Comment by Araq** [comment]
Any possibly remaining osproc issue is reported as an osproc issue.
