### ISSUE TITLE
Error when template arg name clashes with field name

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4886]
Sample:
```nim
type
  SomeObj = object
    id: int

template myTemplate(obj: SomeObj, id: int): bool =
  # error because `id` in obj.id named the same as the `id` arg.
  # renaming the argument fixes the error.
  var result = (obj.id == id) 
  result

let obj = SomeObj(id: 1)
echo myTemplate(obj, 1)
# Error: identifier expected, but found '1'
```
Nim Git hash: e6ff6dd9c89b3156fe50f61f6a28bcaba4aca91c

**Comment by nigredo-tori** [comment]
I think this is correct, and quite useful. Intuitively template replaces all idents, matching parameter, in its body  with corresponding value. In your case this gives a following subexpression:
```nim
(obj.1 == 1)
```
which produces the error in question.

**Comment by endragor** [comment]
As I see it, templates should be smarter than mindless find/replace - they have the necessary context to decide if replacing identifier in certain place makes sense. How is it useful?

**Comment by nigredo-tori** [comment]
I'd say that the point of templates is exactly operating on syntax trees in a most simple and predictable way possible (a more accessible alternative to macros). They don't always have enough context to check whether something produces a valid expression. For example, if `obj` in your example were `untyped`, template wouldn't be able to check if substituting field access makes sense - think [dot operators](http://nim-lang.org/docs/manual.html#special-operators-dot-operators). What if `id` was an untyped? And what if the result was `untyped`, fed to some macro post-processing that was supposed to fix this exact case? Do we really need templates to behave differently depending on the type of each argument? Just imagine reasoning about that!

Now, about usefulness. You can do this:
```nim
import future

template getter(T: typedesc, field: untyped): untyped =
  (obj: T) => obj.field

type SomeType = object
  x: int
  y: string

let t = SomeType(x: 1, y: "foo")
let getX = getter(SomeType, x)
let getY = getter(SomeType, y)

echo getX(t)
echo getY(t)
```
This is a toy example, of course, but I can see this trick can be used to implement something like lenses.

By the way, this behavior is deliberate, and is actually [mentioned in the Manual](http://nim-lang.org/docs/manual.html#templates-lookup-rules-for-template-parameters).

**Comment by endragor** [comment]
Thanks for pointing to the manual, my bad for not noticing that.
