### ISSUE TITLE
C, C++ codegen: variable initialization with block expression is broken by shadowing

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4891]
If inside a proc I initialize a variable with the result of a block expression, which shadows said variable internally, then the variable doesn't get a value.
Example:

``` nim
proc main() =
  let s = (block:
    var s: string
    "foo"
  )

  # this prints "nil"!
  echo s

main()
```

This happens with C and C++ backends only, and only inside procs.
The assignment looks like this in generated code:

``` c
NimStringDesc* s0;
{
    NimStringDesc* s0;
    s0 = (NimStringDesc*)0;
    s0 = copyString(((NimStringDesc*) &T4253654867_2));
}
```

Nim version: b77fb67fee2aca5dabbcfb6aff8cef0607ede9d0

**Comment by Araq** [comment]
Upcoming codegen fixes this. Closing already since it will be merged today.
