### ISSUE TITLE
Stack GC: memory region problem

### ISSUE THREAD

**Issue by hakanderyal** [nim-lang/Nim#4892]
In the [withRegion](https://github.com/nim-lang/Nim/blob/00cb5b4965d2aa6c6e13bdb1b9b7b3d8537cfa30/lib/system/gc_stack.nim#L76) template, the region passed in to the template is copied, thus remains unchanged.

```nimrod
template withRegion*(r: MemRegion; body: untyped) =
  let oldRegion = tlRegion
  tlRegion = r # here
  try:
    body
  finally:
    tlRegion = oldRegion
```

This defeats the purpose of having different memory regions, as there are no ways to use them.

I don't know if we should add

```nimrod
r = tlRegion
```

to the finally block, or some other solution is needed.

**Comment by Araq** [comment]
That solution seems to be good, go for it!
