### ISSUE TITLE
LibreSSL isn't recognized as legit SSL library

### ISSUE THREAD

**Issue by gangsterakato** [nim-lang/Nim#4893]
When running Nimble on a distro with LibreSSL installed in lieu of OpenSSL (like on Void Linux), Nim doesn't seem to recognize it and asks for another versions.

```
$ nimble
could not load: libcrypto.so(|.10|.1.0.1|.1.0.0|.0.9.9|.0.9.8)
```

```
$ nimble
could not load: libssl.so(|.10|.1.0.1|.1.0.0|.0.9.9|.0.9.8)
```

Current and dirty fixes are the creation of symbolic links:

```
$ ln -s /usr/lib/libcrypto.so.38 /usr/lib/libcrypto.so.10
$ ln -s /usr/lib/libssl.so.39 /usr/lib/libssl.so.10
```

**Comment by herauthon** [comment]
do also : ln -sf /usr/lib/libcrypto.so.38.0.1 /usr/lib/libcrypto.so.38

if /usr/lib/libcrypto.so.38 not
