### ISSUE TITLE
Error after codegen when shadowing template arg

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4898]
Sample:

``` nim
from streams import newStringStream

type Stream = object

template doSomething(stream: Stream) =
  let stream = newStringStream()

let s = Stream()
doSomething(s)
```

Error when compiling C code:

```
error: assigning to 'Stream99002' (aka 'struct Stream99002') from incompatible type 'Stringstreamobj97377 *' (aka 'struct Stringstreamobj97377 *')
        s_99007_1832962753 = newstringstream_97462_1780494535(((NimStringDesc*) &T1832962753_2));
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Nim Git hash: 2d2b1a9d481bffaecac35e1e52929cea66f69e0e

**Comment by nigredo-tori** [comment]
In all fairness, that example shouldn't compile at all. It should probably throw a redefinition error, since the macro results in another definition for `s`.
Here's a massaged example:
```nim
template doSomething(x: string) =
  let x = "bad"

let s = "good"
doSomething(s)
# prints "bad"
echo s
```
This one actually runs (since the types match), but overwrites the `let` binding. In generated code the declaration of a global variable is duplicated, but C, being C, permits this.

**Comment by endragor** [comment]
I never said it should compile. post-codegen errors are always a bug though.

**Comment by nigredo-tori** [comment]
So it seems there's a hack (?) in semantic checking that specifically allows multiple definitions of the same symbol, which is exactly what is causing the problem here...
https://github.com/nim-lang/Nim/blob/2d2b1a9d481bffaecac35e1e52929cea66f69e0e/compiler/astalgo.nim#L571-L576

**Comment by Araq** [comment]
This hack needs at least to ensure the symbol has the same type. Or it needs to be removed. Very interesting.
