### ISSUE TITLE
not assigned template invocations error out far away

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4905]
Compiling this program:

``` nim
true notin {false}
```

results in this error:

```
lib/system.nim(1111, 57) Error: value of type 'bool' has to be discarded
```

There are no `instantiated here` or any other messages leading to the actual place of the error, which makes it hard to trace the problem in larger files.

**Comment by cheatfate** [comment]
Yeah, got same problems when using templates, this happens because `notin` is actually template.
``` nimrod
template `notin` * (x, y: untyped): untyped {.dirty.} = not contains(y, x)
```
