### ISSUE TITLE
Error when annotating a generic parameter with "not nil".

### ISSUE THREAD

**Issue by GrundleTrundle** [nim-lang/Nim#4907]
This is with the devel branch, f176128f0728052b10a9c7ddc6e77fdfe8ece088

``` Nimrod
type
    Foo = ref object

    Thing[A] = ref object
        x: A not nil       

proc doSomething(t: Thing[Foo]) = # Error: invalid type: 'A not nil' in this context: 'proc (t: Thing[tt.Foo])'
    discard
```

I ran into this converting an object from using explicit types to a generic version.  On of the fields whose type changed to a generic parameter had a "not nil" annotation, which I left on.

**Comment by Araq** [comment]
This is really hard to fix. The error message points out that the generic type was not resovled properly due to ``not nil``.
