### ISSUE TITLE
RFC: More flexible directory creation

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4917]
Currently stdlib only provides one portable way (as far as I can see) to create a directory: `createDir`. It, however, lacks flexibility:
1. It creates the all the parent directories, which sometimes may not be what we want. Maybe we should expose some lower-level function (`createSingleDir`?) and implement `createDir` using it?
2. More importantly (in my case), it does not indicate whether the directory has already existed. This is, indeed, a preferred behaviour for most use cases (just as the comment says), but not for all. For example, this [issue](https://github.com/OpenSystemsLab/tempfile.nim/issues/5) in tempfile. We need some kind of escape hatch to access this information without reinventing `createDir` from scratch in each use case, or introducing races into our programs with `existsDir` checks. A simplest solution would be for `createDir` to return a discardable `bool` to indicate success. This should not break much existing code, but it still might break some.

**Comment by Araq** [comment]
> A simplest solution would be for createDir to return a discardable bool to indicate success.

Go for it.

**Comment by nigredo-tori** [comment]
@yglukhov, we would then have `createDir` behaviour change heavily depending on this flag, to the point of the whole proc body being a big if/else statement. I'd much rather have a separate proc that is a thin (but still platform-independent) wrapper over OS call. Python does just this with `mkdir`/`mkdirs`.

**Comment by nigredo-tori** [comment]
Should I also make similar changes to `removeDir` (make it return false if the directory did not exist)?

**Comment by Araq** [comment]
Name suggestions for the new proc:

* createDirStrict
* createDirFlat
* createFlatDir
* createStrictDir
* strictCreateDir

**Comment by nigredo-tori** [comment]
`existsOrCreateDir` sounds like it will return `true` if the directory already exists, which is the opposite of what should happen. We're still speaking about thin `mkDir` wrapper here, right?

`tryCreateDir` is one more option.

**Comment by nigredo-tori** [comment]
While we're at it: what should we do if we have an existing file at given path? Current implementation considers this a successfully created directory, which is clearly wrong.

In `createDir` we can check that the path points to a directory and raise. But what should be done in a new proc (low-level `mkdir` wrapper)? Checking it there is at odds with mapping directly to `mkdir`.

**Comment by Araq** [comment]
> existsOrCreateDir sounds like it will return true if the directory already exists, which is the opposite of what should happen.

Yes, but it's clear what 'true' means which is good.

> We're still speaking about thin mkDir wrapper here, right?

Dunno about 'thin'. :-)

> While we're at it: what should we do if we have an existing file at given path? Current implementation considers this a successfully created directory, which is clearly wrong.

Ah yeah, that needs to be fixed to raise an OSError.

> But what should be done in a new proc (low-level mkdir wrapper)? Checking it there is at odds with mapping directly to mkdir.

I think this suggests "mapping directly to mkdir" is the wrong idea.

**Comment by nigredo-tori** [comment]
> Yes, but it's clear what 'true' means which is good. 

Ok, I'll go with that.

> I think this suggests "mapping directly to mkdir" is the wrong idea.

Got it. Will return `false` if succeeded, `true` if the directory (not a file) previously existed, raise otherwise.

**Comment by Araq** [comment]
> Got it. Will return false if succeeded, true if the directory (not a file) previously existed, raise otherwise.

Ok, now that 0.15.2 is out, new features are merged quickly. Please give a shot.
