### ISSUE TITLE
Concrete types are mistaken for implicit type parameters in generic procs with type unions

### ISSUE THREAD

**Issue by shrfarzk** [nim-lang/Nim#4930]
Compiling

```
type ConcreteType = enum a b c d
type OtherType = enum x y z w

proc generic_proc[ParameterType](input: ParameterType or ConcreteType): int =
  1

echo generic_proc[OtherType](a)
```

fails with

```
Error: cannot instantiate: generic_proc[OtherType]; got 1 type(s) but expected 2
```

**Comment by flyx** [comment]
The error message is strange, but I don't see why this should be supported. Since `ParameterType` includes `ConcreteType`, it doesn't make any difference to just specifying `ParameterType` as type.

**Comment by shrfarzk** [comment]
The intention is to specify that input might be the type unknown at declaration (ParameterType, which could be any tuple, for example) or a different but known type (eg: int).

What seems to be happening is that `generic_proc` considers `ConcreteType` in its inputs an undeclared type parameter that is different from the concrete type defined above.

I realize in this example the use of two enums seems like it could cause some problems (with uniqueness, I'm not sure how nim handles this), so i tried this
```
type ConcreteType = tuple[x: bool, y: bool]
type OtherType = distinct int

proc generic_proc[ParameterType](input: ParameterType or ConcreteType): int =
  1

echo generic_proc[OtherType](1.OtherType)
```
and go the exact same result.
```
Error: cannot instantiate: generic_proc[OtherType]; got 1 type(s) but expected 2
```
Again, I want to stress that this is about declaring something like `proc do_something[T](input: T or int, T, int): T`, and calling `do_something[string](could_be_string_or_int, "abc", 5)` which is not the same as either occasionally instantiating `do_something[int](...)` or always instantiating with the type union at call site `do_something[SomeConcreteType or int](...)`
