### ISSUE TITLE
Clean up root of repo and release archives

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4934]
There is far too many files in the root of the repo. IMO the following files should be removed/moved:
- bootstrap.sh
- build_tools.sh
- contributing.txt
- docstyle.rst
- finish.nim
- install.txt
- install_nimble.nims
- install_tools.nims
- readme.txt
- start.bat

Similarly I will need to look at the release tarballs/zip, I'm sure there is room for improvement there too.

**Comment by Araq** [comment]
Should be closed once install_tools.nims and install_nimble.nims have been removed.

**Comment by dom96** [comment]
readme.txt and install.txt should still be removed IMO

**Comment by Araq** [comment]
They can be merged into a single ``readme.txt`` but the txt extension is quite important for Windows.

**Comment by Araq** [comment]
Fine, whatever.
