### ISSUE TITLE
Channels: crashes in `tryRecv` and `send`

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4950]
An attempt to pool `HttpClient` objects using a channel results in SIGSEGV inside `alloc` and `dealloc`: [Gist](https://gist.github.com/nigredo-tori/917aaac1c7e8abc4525056a89f6e8731)
To reproduce:
1. Start `server.nim`
2. Run `client.nim`. You may have to re-run it a few times.

Sorry the example is a bit involved - I tried replacing `HttpClient` with some simpler data type, but have failed to trigger the bug this way.

Tested on: Ubuntu, Nim version 01afff495cdf1b9bb0646894dac74fcfdb59d072

**Comment by Araq** [comment]
There have been allocator and channel bugfixes. Can you test again?

**Comment by nigredo-tori** [comment]
Seems to be fixed - works both on my work and home boxes.
