### ISSUE TITLE
sysFatal (IndexError) with parseUri and the / operator

### ISSUE THREAD

**Issue by dtkerr** [nim-lang/Nim#4959]
Using parseUri and `` `/` `` as shown in the example documentation:

```
let foo = parseUri("http://example.com/foo/bar") / "/baz"
assert foo.path == "/foo/bar/baz"
```

will cause a sysFatal because of improper indexing. The cause is simply that the `` `/`*(x: Uri, path: string) `` procedure assumes that `x.path` has a non-zero length. The `x.path` will have a len of 0 assuming it was only just created by `parseUri` as in the example.

I'm not sure if it's properly considered with `parseUri` and/or `initUri` not ensuring the path contains at least `"/"`, or if it's an issue with `` `/` `` itself.

**Comment by dom96** [comment]
Hrm, am I missing something? That code example works for me.

**Comment by dom96** [comment]
I guess you mean something like this:

```nim
import uri
let foo = parseUri("http://example.com") / "/baz"
assert foo.path == "/baz"
```
