### ISSUE TITLE
[Req] Better deprecation warning

### ISSUE THREAD

**Issue by rishavs** [nim-lang/Nim#4965]
Currently the warning we get for deprecated expressions is really not helpful.

For example:

`c:\users\rsharan\.nimble\pkgs\sdl2_nim-0.95\sdl2\private\sdl_libname.nim(3, 48) Warning: use 'untyped' parameters instead; immediate is deprecated [Deprecated]
`

```

c:\users\rsharan\.nimble\pkgs\sdl2_nim-0.95\sdl2\private\sdl_libname.nim(3, 24) Warning: expr is deprecated [Deprecated]
c:\users\rsharan\.nimble\pkgs\sdl2_nim-0.95\sdl2\private\rwops.nim(165, 30) Warning: expr is deprecated [Deprecated]
c:\users\rsharan\.nimble\pkgs\sdl2_nim-0.95\sdl2\private\pixels.nim(107, 33) Warning: expr is deprecated [Deprecated]
c:\users\rsharan\.nimble\pkgs\sdl2_nim-0.95\sdl2\sdl_image.nim(208, 25) Warning: expr is deprecated [Deprecated]
```

The first example is helpful. 2nd is not.

Can we use a single format for all these deprecated warnings?

Something like

`Warning!! <stuff type>: <stuff name> was [Deprecated] in <version>. Use <stuff type>: <stuff name> instead!`

**Comment by dom96** [comment]
That would be nice.

**Comment by Araq** [comment]
This feature now exists.
