### ISSUE TITLE
`system.toInt(float)` raises no exception when float out of range for int, giving bad results

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4967]
```nim
var b: int
b = toInt(1.0e300)
echo b # -9223372036854775808 # but should raise exeption from manual
# May be indeed a bug
```

**Comment by krux02** [comment]
https://github.com/nim-lang/Nim/blob/3cf3c2d722775ee3fc265e1c53733645277171e5/compiler/transf.nim#L428

**Comment by timotheecour** [comment]
still a bug as of 1.5.1 73ce40aaf71196faa08072216bd826a94b5d40b1:

```nim
when true:
  template main =
    var b: int
    b = toInt(1.0e300)
    echo b # -9223372036854775808 # but should raise exeption from manual
  static: main()
  main()
```
prints:
-9223372036854775808
-9223372036854775808

also, in js, it gives
system.nim(1483, 17) Error: illegal conversion from 'float' to 'int'
