### ISSUE TITLE
ICE when macro and call identifier is the same as the module name

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#497]
macro_bug2.nim:

```nimrod
import macro_bug

type TObj = object

proc f(o: TObj) {.macro_bug.} = discard
```

macro_bug.nim:
```nimrod
import macros

macro macro_bug*(s: stmt): stmt {.immediate.} =
  s.expectKind({nnkProcDef, nnkMethodDef})

  var params = s.params

  let genericParams = s[2]
  result = newNimNode(nnkProcDef).add(
    s.name, s[1], genericParams, params, pragma(s), newEmptyNode())

  var body = body(s)

  # Fails here.
  var call = newCall("macro_bug", s.params[1][0])
  body.insert(0, call)
  result.add(body)
```

This doesn't happen if either macro_bug.nim or the macro identifier is renamed, or if the the "macro_bug" string is changed to something else.

lib/nimrod/core/macros.nim(329, 26) Error: internal error: expr(skMacro); unknown symbol
Traceback (most recent call last)
nimrod.nim(79)           nimrod
nimrod.nim(55)           HandleCmdLine
main.nim(487)            MainCommand
main.nim(256)            CommandCompileToC
main.nim(210)            CompileProject
main.nim(168)            compileModule
passes.nim(192)          processModule
passes.nim(136)          processTopLevelStmt
cgen.nim(1210)           myProcess
ccgstmts.nim(875)        genStmts
ccgexprs.nim(1884)       expr
ccgstmts.nim(875)        genStmts
ccgexprs.nim(1948)       expr
cgen.nim(854)            genProc
cgen.nim(824)            genProcNoForward
cgen.nim(763)            genProcAux
ccgstmts.nim(875)        genStmts
ccgexprs.nim(1884)       expr
ccgstmts.nim(875)        genStmts
ccgexprs.nim(1884)       expr
ccgstmts.nim(875)        genStmts
ccgexprs.nim(1846)       expr
ccgcalls.nim(292)        genCall
ccgcalls.nim(124)        genPrefixCall
cgen.nim(566)            initLocExpr
ccgexprs.nim(1823)       expr
msgs.nim(781)            InternalError
msgs.nim(761)            liMessage
msgs.nim(674)            handleError

**Comment by reactormonk** [comment]
Compiles as of https://github.com/Araq/Nim/commit/9bd72fc0d96c1ce2e0c162b446346ec0e39712e2

**Comment by Araq** [comment]
Fails for me with an ICE again.

**Comment by Araq** [comment]
Now fails with an appropriate error message.
