### ISSUE TITLE
Bad codegen when comparing isNil results

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4975]
Sample:
```nim
var s1, s2: string
s2 = ""
let eq = (s1.isNil) == (s2.isNil)
echo eq # true!!
```
During codegen, the parens are omitted and so the operation order becomes incorrect. `nim cpp` actually errors out, because C++ is more strict:
```
sample.cpp:318:50: error: comparison between pointer and integer ('int' and 'NimStringDesc *')
        eq_95013_2492582993 = (s1_95009_2492582993 == 0 == s2_95010_2492582993 == 0);
                               ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
```
Nim v0.15.2

**Comment by scroot** [comment]
Nim: 0.15.2 
Copyright (c) 2006-2016 by Andreas Rumpf
git hash: 5cb50364eb1f70677f619882cfafbd3ede45356f
active boot switches: -d:release

Windows  10 build 14931

var s1, s2: string
s2 = ""
let eq = (s1.isNil) == (s2.isNil)
echo eq # true!!
---------------------------
true
[Finished in 1.6s]
测试正常
