### ISSUE TITLE
Generic `==` for seq[Time] does not compile

### ISSUE THREAD

**Issue by goldenreign** [nim-lang/Nim#4981]
```
Nim Compiler Version 0.15.2 (2016-11-01) [Linux: amd64]
git hash: 0f3419685fecc554f6ce28dee3e4630480358c3b
```

Code:

```nim
import times

let seqA: seq[Time] = @[0.fromSeconds, 0.fromSeconds]
let seqB: seq[Time] = @[0.fromSeconds, 0.fromSeconds]
echo seqA == seqB
```

Compilation error:

```
times_compare.nim(5, 11) template/generic instantiation from here                                                                                 
lib/nim/system.nim(2179, 6) Error: '==' can have side effects
```

This is because [proc `==` for seq[T]](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/system.nim#L2179) has `noSideEffect` pragma but underlying [proc `==` for Time](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/pure/times.nim#L233) and [proc `-` for Time](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/pure/times.nim#L219) do not.
If I add `noSideEffect` pragma to [proc `-` for Time](https://github.com/nim-lang/Nim/blob/0f3419685fecc554f6ce28dee3e4630480358c3b/lib/pure/times.nim#L219) then code compiles but I do not know if it is the best way to fix the issue.

**Comment by Araq** [comment]
Yes but additionally the generic should not be annotated with .noSideEffect, the compiler can infer that depending on the instantiation.
