### ISSUE TITLE
finish.exe crashes immediately

### ISSUE THREAD

**Issue by tvasenin** [nim-lang/Nim#4983]
```
C:\bin\nim-0.15.2>finish.exe
Traceback (most recent call last)
finish.nim(165)          finish
finish.nim(117)          main
os.nim(347)              expandFilename
os.nim(151)              raiseOSError
Error: unhandled exception: The filename, directory name, or volume label syntax is incorrect.
 [OSError]
```
OS: Windows 10 (1607) x64

**Comment by tvasenin** [comment]
Ок, looks like it has been fixed in devel: c21bc6c61c3a0c8e50ed11204ad7e57215a1bcf6.

Waiting for a new version to be released, as it blocks installation via zip on Windows.

**Comment by Araq** [comment]
A new release is quite a few months away though. Can you compile your own 'finish.exe' from devel?

**Comment by tvasenin** [comment]
I can do that, but I have to install nim first :)
Looks like I'll have to use installer to do that (which would invalidate the whole "")

**Comment by dom96** [comment]
@Araq could we simply not repackage the zip with a new finish.exe?

**Comment by Araq** [comment]
> Anyway, If this bug is not worth a minor release, maybe it'd be a good idea at least to put the warning for all Windows users, in order to not confuse the newcomers?

The bug only appears with long paths, I believe. I know finish.exe works perfectly well for most users.

**Comment by Araq** [comment]
> @Araq could we simply not repackage the zip with a new finish.exe?

that would be an unreproducible build.

**Comment by dom96** [comment]
> that would be an unreproducible build. 

what does that mean?

**Comment by Araq** [comment]
Workaround: Your PATH likely conains ';;' (which implies an empty string direcory). Cleanup your PATH and finish.exe should work.

**Comment by cheatfate** [comment]
or you have last symbol of your PATH variable ';'.

**Comment by tvasenin** [comment]
Yes, my user PATH variable ends with `;` (and both user and system PATH variables don't have `;;`) and, AFAIK, it is the default value for Windows 10:
```
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
```

"Remove trailing slash" workaround works, but, given it's the default value for Win10, I believe it's going to block a lot of (new) users.

**Comment by Araq** [comment]
0.16.0 doesn't have this bug anymore.
