### ISSUE TITLE
Compilation of symlinked files appear in wrong directory.

### ISSUE THREAD

**Issue by oderwat** [nim-lang/Nim#4986]
When I compile a file which is symlinked from another directory the resulting binary is put into that folder. I think this is an unexpected behaviour and the executable should be placed into the directory of the symlink.

```
cd ~
mkdir checkout
echo "echo 12345" > ~/checkout/mysource.nim
cd /usr/local/src/
mkdir somebuild
cd somebuild
ln -s ~/checkout/mysource.nim mysource.nim
nim c mysource.nim
ls mysource # file not found
ls ~/ckeckout/mysource # file is here
```

**Comment by Araq** [comment]
Play stupid games, win stupid prizes.
