### ISSUE TITLE
.cfg files (, parsecfg) and quoting

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#499]
```
--parallelBuild:1
```

in a nimrod.cfg file results in an error: `identifier expected, but found '1'`

This is a confusing limitation, after investigating I noticed that it requires the `1` to be quoted.

It shouldn't be necessary to quote this, quoting should only be necessary when a value with spaces is provided and in fact I would perhaps argue that it would not be necessary either but that's how the config format works I guess.

The same goes for the parsecfg module in the stdlib.

**Comment by jangko** [comment]
I have tested with latest devel branch, turn out this is no longer valid issue, parsecfg can accept both quoted and unquoted literal such as, including negative int:
```text
--build:1
--parallel:"123"
--neg:-1
--negsym:-abc
```

**Comment by Araq** [comment]
The compiler uses its own config parser, fyi.
