### ISSUE TITLE
uint16 is not 2byte ?

### ISSUE THREAD

**Issue by scroot** [nim-lang/Nim#4991]
```
type foo = ref object
  ty: uint8 
  age:uint16
  memo:array[16,char]

var d = ""
d.add(0x11.char)
d.add(0x00.char)
d.add(0x00.char)
d.add("hello")

var obj = new(foo)
obj = cast[foo](d[0].addr)
echo repr(obj)
```

--------------
ref 0000000000930060 --> [ty = 17,
age = 26624,
memo = ['e', 'l', 'l', 'o', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0']]

-------------
Nim Compiler Version 0.15.2 (2016-10-23) [Windows: amd64]
git hash: 5cb50364eb1f70677f619882cfafbd3ede45356f
active boot switches: -d:release

**Comment by jangko** [comment]
this is because the C compiler add padding to the first ty: uint8, not a bug in the Nim compiler.
try swap the position of ty and age, and memo will start with 'h'.

**Comment by scroot** [comment]
thanks , it worked
