### ISSUE TITLE
newAsyncSocket should raise an OS error plus other inconsistencies

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4995]
https://github.com/nim-lang/Nim/pull/4936#issuecomment-256117901

Ensure that:

* [``newAsyncNativeSocket()``](https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncdispatch.nim#L813) doesn't raise an error.
* [``newAsyncSocket()``](https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncnet.nim#L103) raises an OS error.

**Comment by Araq** [comment]
I think 'new*' constructors should always raise and never return ``invalidSocket`` etc. The socket creations that are low level wrappers shouldn't be named 'new*' (not sure if they are now).

**Comment by dom96** [comment]
What should we call them then?

**Comment by Araq** [comment]
``createSocket``

**Comment by dom96** [comment]
This needs to be fixed and it's a breaking change so I'm marking as high priority.

I do agree with Araq here. The procs unfortunately need to be renamed.
