### ISSUE TITLE
nre module breaks os templates

### ISSUE THREAD

**Issue by jdbernard** [nim-lang/Nim#4996]
This code:

```nim
import os, sequtils

echo toSeq(walkFiles("."))
```

compiles and works correctly. Adding `nre` to the import list causes it to no longer compile:

```nim
import nre, os, sequtils

echo toSeq(walkFiles("."))
```

Fails to compile with:

```test.nim(3, 21) Error: attempting to call undeclared routine: 'walkFiles'```

Tested on [33ebf3e5](https://github.com/nim-lang/Nim/commit/33ebf3e5fb05f45abadeff4747ab0e3031f75dd0)

**Comment by dom96** [comment]
That sure is an interesting bug.

**Comment by jdbernard** [comment]
Indeed! My guess is that some template or type is being defined in `nre` that is conflicting with the signature of the templates in the `os` module, but I was hoping someone more familiar with the codebase might have a stronger lead.

**Comment by jangko** [comment]
this one with nre compiles
```nimrod
import os, nre
for x in walkFiles("."):
  echo x
```

this one without nre, produce the same error as above

```nimrod
import os
let a = walkFiles(".")

nnn.nim(2, 18) Error: attempting to call undeclared routine: 'walkFiles'
```

**Comment by jdbernard** [comment]
That is interesting. That seems to confirm that this is an issue with the compiler getting confused about what type of symbol `walkFiles` is. When we use it in an expression where it has to be an iterator according to the grammar it's fine.

It also makes me wonder maybe it's not just an issue with `walkFiles`, but also with `toSeq`.  `nre` defines a `toSeq` symbol, so maybe that's the cause of the compiler's confusion?

I could easily be wrong, correct me if I am, but I think that second case is correct behavior because `walkFiles` is an inline iterator and inline iterators are not first class citizens in Nim, you can't assign then to variables. So the compiler is legitimately looking for a routine there.

**Comment by dom96** [comment]
I think that when ``nre`` is imported we should get an ambiguous error because as you said ``toSeq`` is also defined in ``nre``. I guess this is a template/proc overloading problem, the interaction between templates and procedures is indeed tricky when it comes to overloading.

**Comment by jdbernard** [comment]
Definitely seems to be a conflict between `nre.toSeq` and `sequtils.toSeq`. The following works:

```nim
import nre, os, sequtils

echo $sequtils.toSeq(walkFiles("*"))
```

**Comment by Araq** [comment]
This is actually documented behaviour and you need to use something like ``import nre except toSeq``.
