### ISSUE TITLE
httpclient.nim 's gc-unsafe async proc

### ISSUE THREAD

**Issue by sclee15** [nim-lang/Nim#4998]
please take a look at below code

`
import httpclient, asyncdispatch

proc a() {.async.} =
    var client = newAsyncHttpClient()
    var b = await client.getContent("http://google.com")
    echo b

waitFor a()
echo "done"
`
this proc "a" doesn't access any global variable
however i get following warning

lib/pure/asyncmacro.nim(291, 7) Hint: Processing a as an async proc. [User] get.nim(3, 10) template/generic instantiation from here lib/pure/asyncmacro.nim(31, 8) Warning: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory [GcUnsafe2] 

so i replicated the newHttpClient and trying to findout what caused GcUnsafe
and i found that "sslContext = defaultSslContext" causes GcUnsafe

proc newHttpClient*(userAgent = defUserAgent,
    maxRedirects = 5, sslContext = defaultSslContext, proxy: Proxy = nil,
    timeout = -1): HttpClient =

here's my hope.

1. i hope gcunsafe error gives me more clue.
2. make async related standard library gcsafe

thank you.

**Comment by anh** [comment]
Za
