### ISSUE TITLE
read of failed future messages pile up in exception when using try/except with async/await

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4999]
Sample:
```nim
# asyncstack.nim
import asyncdispatch

proc raiseProc() {.async.} =
  if true:
    raise newException(ValueError, "the error")

proc anotherProc() {.async.} =
  await raiseProc()

proc topProc() {.async.} =
  try:
    await anotherProc()
  except:
    echo "Error: ", getCurrentExceptionMsg()

discard topProc()
poll()
```
This program outputs:
```
Error: the error
  raiseProc's lead up to read of failed Future:
    Traceback (most recent call last)
    asyncstack.nim(16)       asyncstack
    asyncmacro.nim(49)       topProc
    asyncmacro.nim(34)       cb
    asyncstack.nim(12)       topProcIter
    asyncmacro.nim(49)       anotherProc
    asyncmacro.nim(34)       cb
    asyncstack.nim(8)        anotherProcIter
    asyncmacro.nim(49)       raiseProc
    asyncmacro.nim(34)       cb
    asyncstack.nim(5)        raiseProcIter
```
So "read of failed Future" messages pile up in the exception msg for each .async proc in the "stack", even though the user doesn't actually call any read(). This doesn't seem like expected behaviour when using try/except with .async procs. I'd expect the output to be:
```
Error: the error
```

**Comment by dom96** [comment]
Hopefully my PR improves things: https://github.com/nim-lang/Nim/pull/6809

Note that even Nim now shows re-raised locations in the stack traces though.

**Comment by narimiran** [comment]
> Hopefully my PR improves things: #6809

Since this was merged and the output is now more informative than in the original post, I'm closing this.
