### ISSUE TITLE
Tuple construction with subranges fails

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#500]
The following code:

``` nimrod
type
  TTest = tuple[x: range[0..80], y: range[0..25]]

let x: TTest = (2, 23)
echo(x)
```

Fails with:

```
a20.nim(4, 16) Error: type mismatch: got (tuple[int, int]) but expected 'TTest'
```

During compilation.

**Comment by jackmott** [comment]
any workarounds for this?

**Comment by Araq** [comment]
```nim

type
  R80 = range[0..80]
  R25 = range[0..25]
  TTest = tuple[x: R80, y: R25]

let x: TTest = (2.R80, 23.R25)
echo(x)
```

**Comment by iffy** [comment]
What is that `.R80` syntax called?  (I'm trying to look it up in the manual to read more about why this works).  It's not casting, right?

**Comment by Clyybber** [comment]
It's a normal type conversion using the Uniform Function Call Syntax. It is the same as writing `let x: TTest = ( R80(2), R25(23) )`
