### ISSUE TITLE
Improvements to times.nim

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#5004]
This is an issue for me which lists things I want to improve in the `times` module after #4984 has been merged.

 * [ ] The format strings `z`, `zz` and `zzz` should be able to parse a `Z` character, which is a special case that represents UTC.
 * [ ] Check what the line `info.monthday = sv` in parsing `M` is for and possibly remove it
 * [ ] Improve ``proc `-` ``, its implementation is horrible
 * [ ] review DST

**Comment by qqtop** [comment]
getTimeZone and getTzname  is in the docs but not exported after the recent merge.

**Comment by flyx** [comment]
@qqtop: Yes, because the online documentation is for the recent release 0.15.2, where those procs still exist. Since it is automatically generated, those procs will vanish when the docs are regenerated for the next release.

**Comment by baabelfish** [comment]
Microseconds would nice too

**Comment by flyx** [comment]
@baabelfish: I think `times` is the wrong module if you want microsecond precision. The problem is that all calculation converts `TimeInfo` to `Time` which is by definition in seconds. So you will basically lose your microseconds as soon as you do anything with it.

**Comment by qqtop** [comment]
Hope you can fix this too , as it messes up my schedule for March 2100 

```nim

import times

echo getDaysInMonth(mFeb,2100)         # 28
echo getDayOfWeekJulian(28, 2, 2100)   # Sunday
echo getDayOfWeekJulian(1, 3, 2100)    # Tuesday  ???

```

**Comment by flyx** [comment]
@qqtop: That's not an error. The Julian calendar does not include the rule that `00` years are only leap years if they are divisible by `400` (this was the change the Gregorian calendar introduced). So in the Julian calendar, February 2100 has 29 days and therefore, 28.2.2100 and 1.3.2100 are two days apart.
