### ISSUE TITLE
A version of httpclient that uses streams in the stdlib

### ISSUE THREAD

**Issue by NebulaFox** [nim-lang/Nim#5020]
I decided I would build a script in `nim` that would download some rather large files, as you do. I wanted to use `httpclient` but it bothered me that there were no streams for the body, just strings. This meant to me that the downloaded data is stored into memory. After reading the source of `httpclient`, this is indeed the case. I can see how this would not be a problem for small files but when downloading rather large files - that is files that would easily deplete any RAM - it would be a bit of a problem. So, in my naive attempt, I changed all usage of strings, when downloading the body, into streams; and here is my gist for it [httpclientstreams.nim](https://gist.github.com/NebulaFox/89926ebfa56840ca49a0202cc39d9de3).

I successfully tested my changes on downloading some images and other media with `httpclientstreams`. As a result of using streams, I removed all the `*Content` methods, because as a user, if I just wanted the content, I would provide a `Stream` and forget about the `Response`. As an additional consequence of using streams for the body of the response, I have also removed the `body` field from `Response`.

As this was strictly a naive attempt, there are leftover `proc`s from `httpclient` that should be deleted, but in saying that is `httpclientstreams` an acceptable implementation to be included into the stdlib?

A couple of other things to note is a benefit of using `streams` is that it would make it possible to process the incoming body of data on the fly. And, I can see `httpclient` easily using the streamed-version encapsulating the methods with `StringStream`, however I do understand that `streams` is not supported for JavaScript.

**Comment by Araq** [comment]
Oh this is actually a PR. This needs to be applied asap.

**Comment by NebulaFox** [comment]
I would be happy to do that, however there are a few questions:

* Do you want `httpclient` to use `streams` rather than `string`s?
* Or do you want `streams` and `string`s to coexist?

If `streams` and `string`s coexist, how do you want to handle the duplication of code?

* Would it possible to create a small interface so that `string`s and `streams` can be interchange 
* Or just use `streams` as the interface/base
* Or deal with it later

**Comment by Araq** [comment]
Make it work with streams and the old string based API should still be kept and call the streams API via ``newStringStream``.

**Comment by NebulaFox** [comment]
I managed to find some time to implement my changes, but it looks it's already been done. Suggest to close this issue? Just for your information, my version is here https://github.com/NebulaFox/Nim/blob/devel/lib/pure/httpclient.nim.

**Comment by Araq** [comment]
Sorry, indeed. We choose a different implementation.
