### ISSUE TITLE
Clarification  of Discarding Future in asyncdispatch

### ISSUE THREAD

**Issue by NebulaFox** [nim-lang/Nim#5021]
In the documentation in `asyncdispatch` under the heading of **Discarding Futures**

> Futures should **never** be discarded. This is because they may contain errors. If you do not care for the result of a `Future` then you should use the `asyncCheck` procedure instead of the `discard` keyword.

Which lead me to believe I should write

```
asyncCheck await myAsyncProc()
```

This fails to compile as await returns the contained type not the Future, and so with the documentation in mind I end up with

```
asyncCheck myAsyncProc()
```

as I was under the impression that `asyncCheck` would `await` and check the `Future` for errors for me. I then realised that's not how async/await works, I ended up with

```
let f = myAsyncProc()
asyncCheck(f)
discard await f
```
which isn't that concise. I maybe missing something here, but would it not be better to have something like

```
await asyncCheck myAsyncProc()
```
instead?

This would mean `asyncCheck` would need to be written to pass the `Future` along, as it is currently returns `void`; and rewrite the documentation

> Futures should **never** be discarded. 
> ```
> discard await myAsyncProc()
> ```
>This is because they may contain errors. If you do not care for the result of a `Future` then you should use the `asyncCheck` procedure.
> ```
> await asyncCheck myAsyncProc()
> ```

**Comment by dom96** [comment]
``await`` already checks the future for errors for you.

``asyncCheck`` should be used if you do not want to ``await`` future.

**Comment by cdunn2001** [comment]
I misunderstood this too. Dom96's simple clarification would have been enough for me.
