### ISSUE TITLE
Adding a mention of the `unsafeAddr` operator to the Nim manual

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#5038]
Inspired from this thread here on the forums: http://forum.nim-lang.org/t/2628

Is it fine if I add a blurb about `unsafeAddr` in this section of the manual: https://github.com/nim-lang/Nim/blob/devel/doc/manual/stmts.txt#L671  It seems like something that really important to have mentioned.

**Comment by Araq** [comment]
Yes, please go ahead.

**Comment by bluenote10** [comment]
@define-private-public Your commit looks good, but there doesn't seem to be a PR for it?

**Comment by narimiran** [comment]
@define-private-public Just a reminder that PR would be nice so this issue can be closed ;)

**Comment by bluenote10** [comment]
I just discovered that there was a PR https://github.com/nim-lang/Nim/pull/5330 but Araq had a concern with the text.
