### ISSUE TITLE
high(float) & low(float)

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#5039]
There exists `high(int)` and `low(int)`, but when I tried to do `high(float)`, the compiler gave me an `Error: invalid argument for 'high'`

Is it possible to add `high()` and `low()` procs for the `float` type?

**Comment by Araq** [comment]
What that be? Floats support +-INF. When is this useful?

**Comment by define-private-public** [comment]
Sorry, didn't know about that.  I was using it along with this random proc: http://nim-lang.org/docs/random.html#random,float

**Comment by dom96** [comment]
Wouldn't it make sense for ``high(float)`` to return ``INF``?

**Comment by Araq** [comment]
And what would that accomplish?

**Comment by dom96** [comment]
It would save me time googling why `high(float)` doesn't work.

**Comment by define-private-public** [comment]
I think that might be an okay idea.  It's logical if people think there is a `high(int), high(short), high(char)`, they might assume that there is a `high(float)`, even though floating point numbers are radically different.  It would stop people from having to learn another "gotcha," for this language.

**Comment by Araq** [comment]
> It would save me time googling why high(float) doesn't work.

You can save my time now and tell me why you wrote high(float) in the first place.

**Comment by Araq** [comment]
>  It would stop people from having to learn another "gotcha," for this language.

"My non-sensical expression didn't compile" is NOT a gotcha.

**Comment by tmerr** [comment]
Interesting... Rust's f32::MAX gives the highest finite value https://doc.rust-lang.org/stable/std/f32/

**Comment by Yardanico** [comment]
@tmerr why it can be useful though?

**Comment by tmerr** [comment]
@Yardanico no idea. It seems like c++'s float max does the same thing: http://www.cplusplus.com/reference/limits/numeric_limits/ . It would be good to understand the motivation for this before making a decision in nim

**Comment by yglukhov** [comment]
It might be useful for generic code, imo.

**Comment by johnnovak** [comment]
The only thing that would make sense to me is to return the highest/lowest safely representable value. But i'm finding hard to find a real-world use-case for this... The numerical limit constants are probably enough for all practical purposes.

**Comment by skilchen** [comment]
Just for fun, i was playing around with floats. If somebody is interested in some of the special floats, please take a look at: https://play.nim-lang.org/?gist=6dca0bb2f6b2fb99fa4fbb9e8af3d74a

**Comment by bluenote10** [comment]
Can be closed now that https://github.com/nim-lang/Nim/pull/6570 is merged.
