### ISSUE TITLE
Add Arduino's "map()" function to the system library

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#5040]
I'm talking about this here: https://www.arduino.cc/en/Reference/Map.  It's very useful to have, I've only seen a handful of languages have it by default.  It's pretty trivial to implement but nice to have ready.

```nim
# maps one value from one range to another
proc map*(x, a, b, p, q: float): float =
  return (x - a) * (q - p) / (b - a) + p
```

Is it fine if I submit a PR?  Is there anything else you want done for it?  There also might be a better name to give this function as it's already taken by something else.

**Comment by Araq** [comment]
That should be ``math.mapRange`` or ``math.mapInterval`` but I'm against it. Once in the stdlib, it will grow to support "generic numeric types including integers" followed by a list of bugfixes to get it right in the face of integer overflows.

**Comment by dom96** [comment]
I agree with @Araq. For now the code is short enough that people can just reimplement it, but if you've got the time then please put it in a Nimble package.
