### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#5052]
Compilation stops with error:
```...nim-devel\lib\pure\times.nim(486, 10) Error: '-' can have side effects```

My system:
Windows Vista 64, GCC 5.2.0 x86, latest Nim repo.

Matic

**Comment by Araq** [comment]
Strange, I bootstrap on Windows daily. Can you be more specific?

**Comment by matkuki** [comment]
No problem, here's the whole output:
[output.txt](https://github.com/nim-lang/Nim/files/613246/output.txt)

Any ideas?

**Comment by matkuki** [comment]
Sorry! I hit the wrong button.

**Comment by matkuki** [comment]
Updating the csources fixes this.
