### ISSUE TITLE
Nim cross-platform libraries

### ISSUE THREAD

**Issue by JackLehman** [nim-lang/Nim#5054]
Sorry, this is not an issue but I am looking for some open source cross-platform Nim libraries that compile to at least 2 or 3 target languages. 

I need that to run some experiments on Nim compiler.

Is there any open source libraries written in Nim?

**Comment by yglukhov** [comment]
I would say that majority of nim libraries would satisfy your needs. Also here are some of the libs I happened to contribute to. The following can be compiled to C, JS and asm.js (with help of emscripten).
[nimx](https://github.com/yglukhov/nimx), [sound](https://github.com/yglukhov/sound), [rod](https://github.com/yglukhov/rod), [async_http_request](https://github.com/yglukhov/async_http_request), [nimsl](https://github.com/yglukhov/nimsl), [minecraft](https://github.com/yglukhov/minecraft), [variant](https://github.com/yglukhov/variant), [nuuid](https://github.com/yglukhov/nim-only-uuid)
This one can be compiled to C and JS (no emscripten yet): [coverage](https://github.com/yglukhov/coverage).

**Comment by Araq** [comment]
Most nimble packages are cross platform.
