### ISSUE TITLE
Generate a single self-contained C source file

### ISSUE THREAD

**Issue by CrazyPython** [nim-lang/Nim#5056]
This is a mix of a feature request and a usage question.

I'm in quite a conundrum.

 - Many many programming competitions (where you attempt to solve problems within an execution time limit*) only accept a few languages - C, C++, and Java
 - C/C++ are the only languages fast enough to use
 - C/C++ takes a very long time to write
 - The competition has a four-hour time limit to write 
 - Nim compiles to C, but requires that nim static libraries be present on the compiling machine

I feel like a small tweak could be made to make nim source output 100% portable. Is this possible?

<sub>*[here's an example](http://usaco.org/index.php?page=viewproblem2&cpid=511)</sub>

**Comment by Araq** [comment]
Nim produces C code that is tied to the OS/CPU/CC combination. It's not a tool for producing readable portable C. Instead I would try to convince the programming competitions that it's 2016 now and we got Nim, Rust, D, Swift for writing high performance code. Fortran often beats C. "C/C++ are the only languages fast enough to use" never was true to begin with.

**Comment by CrazyPython** [comment]
@Araq I agree. If any of you want to petition "them", I would recommend convincing USACO - usaco.org
