### ISSUE TITLE
supporting 'x[y] *= z' and so on when `[]` is overloaded

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#5064]
should this work?
```nim
proc `[]`(x: var int, i: int): var int = x
var i = 0
i[0] = 0 # Error: could not resolve: i[0]
i[0] *= 0
```

**Comment by krux02** [comment]
I aready asked Araq a very similar question, and no it should not work. You error is tententional. If you want your code to compile you should define the `[]=` proc.

**Comment by ephja** [comment]
The problem is that it doesn't work with compound assignment

**Comment by krux02** [comment]
What do you mean by compound assignments?

**Comment by ephja** [comment]
@krux02 `k *= y` for example

**Comment by krux02** [comment]
Yes for conpound assignments you have the operator you just described. implement both for maximum benefit.

**Comment by Araq** [comment]
Krux02 is correct.
