### ISSUE TITLE
toTime(getGMTime(...)) doesn't work correctly when local timezone is not UTC

### ISSUE THREAD

**Issue by MednauN** [nim-lang/Nim#5065]
Sample program:
```
import times
echo int64(fromSeconds(0).getLocalTime().toTime())
echo int64(fromSeconds(0).getGMTime().toTime())
```
Output:
```
0
25199
```
Expected output:
```
0
0
```
Environment: OS Win10, timezone: UTC +7

When I change local timezone to UTC, this code works fine.

**Comment by MednauN** [comment]
Found out that the issue doesn't appear on macOS. Seems like it's Windows-only.

**Comment by flyx** [comment]
Can you give the output of

```nim
echo fromSeconds(0).getLocalTime()
echo fromSeconds(0).getGMTime()
```

I would run it myself, but I don't have any functioning Windows environment currently.

**Comment by Araq** [comment]
@flxy on my machine

```
1970-01-01T01:00:00+01:00
1970-01-01T00:00:00+00:00
```

**Comment by MednauN** [comment]
@flyx 
```
1970-01-01T07:00:00+07:00
1970-01-01T00:00:00+00:00
```

**Comment by flyx** [comment]
This works correctly:

```nim
echo fromSeconds(3600).getLocalTime()
echo fromSeconds(3600).getGMTime()
```

Output (`+01:00`; wil not work on `+07:00`, try `3600 * 7` there):

```
3600
3600
```

The problem is that on Windows, `mktime` returns `-1` if the given date interpreted as local time lies before January 1, 1970. On OSX, it returns the correct negative amount of seconds. So this seems to be a Windows limitation, and the only thing that can be done here is to check the result of `mktime` for `-1` on Windows and if true, raise some exception.

**Comment by MednauN** [comment]
Yes, works correctly starting with `3600 * 7 - 1` for UTC +7.
Checked the output of `mktime`, it returns `-1` indeed. And if I understand correctly, since `mktime` accepts local time, `TimeInfo` is being converted to local time before calling `mktime` and there is where the problem lies.
So, if add, like, 1 day to `TimeInfo` before calling `toTime` and substract 1 day after that, everyting will work fine. Something like that should do the trick:
```
proc toTimeSafe*(timeInfo: TimeInfo): Time =
  when defined(windows):
    if timeInfo.year == 1970 and timeInfo.month == mJan and timeInfo.monthDay == 1:
      var safeTimeInfo = timeInfo
      safeTimeInfo.monthDay += 1
      return safeTimeInfo.toTime() - 1.days
  return timeInfo.toTime()
```

**Comment by MednauN** [comment]
Found function `_mkgmtime` on Windows that accepts time in GMT rather than local time. Using this instead of `mktime` may also help. And for Linux there is `timegm` which do the same.
