### ISSUE TITLE
Feature Request: Command line option to swap out/disable/enable runtime files at compile time

### ISSUE THREAD

**Issue by Immortalin** [nim-lang/Nim#5072]
Currently to use Nim without a host OS would require hacking the system/ folder; becoming a platform for GC research is also one of Nim's goals. A temporary fix for both is to have a command line flag that can enable/disable and/or replace runtime files depending on the dependency graph etc. e.g. 

``` nim

--runtime-replace:alloc.nim my-alloc.nim # replace alloc.nim with my-alloc.nim and disable osalloc.nim as it is only required by alloc.nim

**Comment by Immortalin** [comment]
This would allow Nim to serve as a platform for GC research as it makes hacking on the compiler much easier

**Comment by Araq** [comment]
This feature already exists. Use a ``.nims`` config file with something like:

```
patchFile("stdlib", "asyncdispatch", "$lib/upcoming/asyncdispatch")
```
