### ISSUE TITLE
addEvent in upcoming/asyncdispatch causes GC crashes on Windows

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5075]
This issue was discussed between @Araq and @cheatfate and was already fixed by 9b68b878b25ab77d51aaf067b8037a1e2b1283af and 5c46f268802217b774df23d4dcf07a6f7b0ebc20.
@cheatfate was going to prepare a reproducible sample.

**Comment by cheatfate** [comment]
This is more complex issue, causes problems for
current version of `asyncdispatch.nim` - windows addRead/addWrite.
upcoming version of `asyncdispatch.nim` - windows addTimer/addEvent/addRead/addWrite.

**Comment by ringabout** [comment]
If this still is a issue, or someone can provide a reproducible example, feel free to reopen.
