### ISSUE TITLE
Paths are converted to lowercase on Windows

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5076]
Nim seems to handle module names differently between OSes. It keeps case on *nix, but converts all paths and module names to lowercase on Windows. So if you have a module (and filename) that starts with an uppercase letter, say `MyModule.nim`, then on Windows Nim will consider it to be `mymodule`, while on other systems it's `MyModule`. So we get code that compiles on Unix, but errors with `undeclared identifier` on Windows or vice versa.

**Comment by Araq** [comment]
Produced a regression, cannot compile Nimble on windows anymore.
