### ISSUE TITLE
suboptimal C code generation

### ISSUE THREAD

**Issue by mmitkevich** [nim-lang/Nim#5083]
Hi, 
first of all Nim is cool.
I currently investigate possibilities of writing performance-critical (high frequency trading are) code in Nim.

Tried simple example (Nim code and generated C code below)

Looking through the code I've found that cycle
``` nim
var cc:int64 = 0
for i in 0..<n:
    let order = newOrder(price=i,size=i)
    cc = cc + order.price
```
is twice as slow compared to iterator
``` nim
iterator generate(n: int) : Order =  
    for i in 0..<n:
        yield newOrder(price = i, size = i)
var cc:int64 = 0
for order in generate(n):
    cc = cc + order.price
```

The reason is that first snipped calls genericReset twice for Order object, as it could be found in the generated C code.

```
		NI i_103094_2401175358;
		i_103094_2401175358 = ((NI) 0);
		{
			while (1) {
				if (!(i_103094_2401175358 < ((NI) 100000000))) goto LA3;
				i_103089_2401175358 = i_103094_2401175358;
				genericReset((void*)(&order_103090_2401175358), (&NTI103006));
				order_103090_2401175358.Sup.m_type = (&NTI103006);
				genericReset((void*)(&order_103090_2401175358), (&NTI103006));
				order_103090_2401175358.Sup.m_type = (&NTI103006);
				neworder_103025_2401175358(((NI64) (i_103089_2401175358)), ((NI64) (i_103089_2401175358)), IL64(0), (&order_103090_2401175358));
				cc_103078_2401175358 = (NI64)(cc_103078_2401175358 + order_103090_2401175358.Sup.price);
				i_103094_2401175358 += ((NI) 1);
			} LA3: ;
		}
```

I think it could be treated as a bug.

Code is attached in zip

[tmp.zip](https://github.com/nim-lang/Nim/files/626757/tmp.zip)

 Thank you.

**Comment by Araq** [comment]
Sorry, low priority as it doesn't affect correctness.

**Comment by Araq** [comment]
Will be fixed with --gc:arc too.
