### ISSUE TITLE
Compilation warnings aren't shown in imported modules

### ISSUE THREAD

**Issue by MednauN** [nim-lang/Nim#5085]
I have 2 sample files:
`module_with_warning.nim`:
```
proc someFunc*() =
  {.warning: "test warning".}
  echo "some text"
  
someFunc()
```
and `run_module.nim`:
```
import module_with_warning

someFunc()
```

When I run `nim c module_with_warning.nim` it gives output:
```
Hint: used config file '<my path to nim>\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: module_with_warning [Processing]
module_with_warning.nim(2, 12) Warning: test warning [User]
CC: module_with_warning
CC: stdlib_system
Hint:  [Link]
Hint: operation successful ...
```
Everyting alright, test warning is present.
And when I run `nim c run_module.nim`, it gives:
```
Hint: used config file '<my path to nim>\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: run_module [Processing]
Hint: module_with_warning [Processing]
CC: run_module
CC: stdlib_system
CC: module_with_warning
Hint:  [Link]
Hint: operation successful ...
```
No warning here.

Maybe I misunderstood something and it's not a bug, but I expect the warning to appear in both cases. Or at least to have an option to enable/disable warning output.

**Comment by Araq** [comment]
Pretty sure that was fixed too. Reopen if still an issue.
