### ISSUE TITLE
finish.exe unhandled exception

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#5086]
I have downloaded and extracted nim-0.15.2_x64.zip under Windows 10.
When I start finish.exe it gives this:

C:\Users\s.krauter\Documents\Programs\nim>finish
Traceback (most recent call last)
finish.nim(165)          finish
finish.nim(117)          main
os.nim(347)              expandFilename
os.nim(151)              raiseOSError
Error: unhandled exception: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
 [OSError]

Any ideas what the problem could be?

**Comment by trustable-code** [comment]
Issue is not important for me anymore. I got it to work with nim-0.15.2_x64.exe.

**Comment by dom96** [comment]
In case it's needed to fix this, could you tell us the contents of your PATH environment variable?

**Comment by trustable-code** [comment]
Here the contents of my PATH variable (after installation of Nim):

PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\OpenVPN\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Users\s.krauter\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Nim\bin;C:\Program Files\Nim\dist\mingw;C:\Program Files\Nim\dist\mingw\bin;C:\Users\s.krauter\.nimble\bin;C:\Users\s.krauter\Documents\Programme\Nim\bin;C:\Users\s.krauter\Documents\Programme\Nim\dist\mingw;C:\Users\s.krauter\Documents\Programme\Nim\dist\mingw\bin

**Comment by Araq** [comment]
This has been fixed.
