### ISSUE TITLE
Allow foldl() and foldr() to accept sequences of zero length

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#5089]
In other languages like Haskell, their fold functions allow the programmer to give it an empty list/sequence and return with throwing an error:
http://zvon.org/other/haskell/Outputprelude/foldl_f.html

It's as nice if I have to do this:

```nim
let s = seq[int]
#...
if len(s) != 0:
  return foldl(s, a + b)
else:
  return 0
```

Where I could just do this instead:
```nim
let s = seq[int]
# ...
return foldl(s, a + b)
```

An extra parameter (the initial value) might need to be added to the proc, but I think it's a lot more elegant (and easier on the programmer).

**Comment by andreaferretti** [comment]
In fact [there is already](http://nim-lang.org/docs/sequtils.html#foldl.t,,,) :-)

**Comment by define-private-public** [comment]
Well, I feel dumb...

Thanks.
