### ISSUE TITLE
Cannot implement distinct seq with setLen

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5090]
Sample:
```nim
type MySeq = distinct seq[int]

proc setLen(s: var MySeq, newLen: Natural) {.borrow.}

var mySeq = MySeq(newSeq[int]())
mySeq.setLen(10)
```
Error after codegen:
```
error: request for member 'Sup' in something not a structure or union
  (&myseq_97061_3173352949) = (TY97041*) setLengthSeq(&((&myseq_97061_3173352949))->Sup, sizeof(NI), ((NI) 10));
                                                                                  ^
```
Nim d6ab21eed53df590b25742c06ac4dff908d8b27d

**Comment by krux02** [comment]
as far as I know distinct is something that you should not use at the moment, better use an object with a single member. This does of course not make this less of a bug.

**Comment by Araq** [comment]
That's not true, ``distinct`` is used everywhere and the above is just a bug.

**Comment by krux02** [comment]
Ok, but I still have a rough memory about a conversation, that involved not using `distinct` in favor of `object`.
