### ISSUE TITLE
Android support for upcoming/asyncdispatch

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5094]
At the moment ioselectors picks `epoll` for Android (because it has `defined(linux)`). Android does support `epoll`, but its NDK doesn't have `ulimit.h` and `sys/signalfd.h`. So it seems ioselectors_epoll should be modified to have `when defined(android)` checks and not use `ulimit`/`signalfd` when it is `true`.

/сс @cheatfate

**Comment by cheatfate** [comment]
If it don't have `ulimit.h` how android can obtain maximum number of open file descriptors for process?

**Comment by endragor** [comment]
I think `sysconf(_SC_OPEN_MAX)` should work.

According to man: `POSIX.1-2008 marks ulimit() as obsolete.`. I guess that's why it's not present on Android.

**Comment by cheatfate** [comment]
`signalfd` is important part of `ioselectors` for linux. If i disable it, then i must disable functions which works with `process exits` and `signals`... Does it really dont have support of `signalfd`, or maybe it just hidden?

**Comment by cheatfate** [comment]
Could you explain me this
github.com/android/platform_bionic/blob/master/libc/include/sys/signalfd.h

**Comment by endragor** [comment]
Yeah, it was added in API level 21 (Android 5.0+), but most applications today target API level 16 (Android 4.1+), so that majority of Android users are supported. About 40% of Android devices today are 4.x: https://developer.android.com/about/dashboards/index.html

As you can see, there is no `signalfd.h` in `jb-release` branch: https://github.com/android/platform_bionic/tree/jb-release/libc/include/sys

**Comment by cheatfate** [comment]
Ok, i understand.
`sysconf` is also a problem, because it returns so called `soft limit`, but we need `hard limit` which process could not change at runtime. Could you check `getrlimit`?

**Comment by cheatfate** [comment]
Ok i have one solution, we can add `defined(android)` branch to include `ioselectors_poll.nim`.
So everything except sockets/files/events will be disabled.

**Comment by endragor** [comment]
`getrlimit` should work.

Using `poll` will work, too, but a better strategy should be to enable `epoll`, because it's the newest mechanism and is supported on Android, just without `registerSignal`/`registerProcess` part.

**Comment by andreaferretti** [comment]
This may be related but I'm not sure https://github.com/nim-lang/Nim/pull/5772

**Comment by cheatfate** [comment]
@andreaferretti you can close this issue, because it was fixed, but for some reason not closed.
https://github.com/nim-lang/Nim/commit/ac4ccc695f880fa0f8add1d4d2236a72498cbd08
