### ISSUE TITLE
Endless loop in net.accept

### ISSUE THREAD

**Issue by recoilme** [nim-lang/Nim#5118]
My server not work if client was incorrectly closed (killed) I see endless loop in this string: 
https://github.com/nim-lang/Nim/blob/devel/lib/pure/net.nim#L583
So if socket raise some connection error accept will no work more.
Example:
```
proc acceptconn(server:Server): Socket =
    try:
      result = createSocket()
      server.socket.accept(result)#endless loop and no option for catch exception and continue work
    except:
      debug("exception in serve:")
      debug($result.getSocketError())
      closeClient(result)
      result = nil
    return result
```

**Comment by dom96** [comment]
Can you show us more of your code?

As a workaround you can use ``server.socket.accept(result, {})``

**Comment by recoilme** [comment]
Hi, Dominik!
We are writing little database server based on sophia engine. Asi think - problem in this place:

**Comment by recoilme** [comment]
Log file looks like: https://gist.github.com/recoilme/fed8836388a3a521e176013ba11570dd

**Comment by recoilme** [comment]
I add: server.socket.accept(result, {}) as you suggest, thanks! (https://github.com/recoilme/pudge/blob/master/pudge.nim#L737) and disable buffering for sockets - now it works... Before 256 forks( We are create 262 after another server restart) So i change limit in threadpool in nim source to 1024. Will wait for morning^ but right now server  work good!

**Comment by dom96** [comment]
Glad that the workaround works. I'm not sure what the best fix here is.

Endless loops are bad, but the idea behind this is that with the ``NoDisconn`` flag you will always get a valid accepted socket, no matter how long it takes. I'm not sure what the reason is, I guess you have many clients connecting at once and they are all disconnecting immediately after connecting (or during the connection)?

**Comment by recoilme** [comment]
Sorry,  i am not 100% sure what problem was in endless loop, and anyway we have workarround. So i close issue. Thanks for help Dominik!
