### ISSUE TITLE
Calling split("") on string hangs program

### ISSUE THREAD

**Issue by filipux** [nim-lang/Nim#5119]
In some languages calling split("") on a string will conveniently return a list of it's characters. For example,  running `"hello".split("")` in javascript will return `["h", "e", "l", "l", "o"]`

In nim, the same code will hang the program indefinitely.

Nim Compiler Version 0.15.2 (2016-10-22) [MacOSX: amd64]

**Comment by dom96** [comment]
Related discussion on the forum: http://forum.nim-lang.org/t/2348/1

**Comment by dom96** [comment]
As mentioned in the forum this should raise an error just like in Python.
