### ISSUE TITLE
using backticks in quote causes wrong deprication warning (stmt and expr)

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5120]
```Nim
import macros

macro foo(arg): string =
  let lit = newLit("")
  
  result = quote do:
    var str: string = `lit`
```

compiler warnings:
```
/home/arne/proj/nim/Nim/lib/system.nim(69, 3) Warning: expr is deprecated [Deprecated]
/home/arne/proj/nim/Nim/lib/system.nim(71, 3) Warning: stmt is deprecated [Deprecated]
```

**Comment by chrisheller** [comment]
That seems to be coming from semQuoteAst in semexprs.nim.  https://github.com/nim-lang/Nim/blob/devel/compiler/semexprs.nim#L1655

**Comment by chrisheller** [comment]
I just changed that to typed/untyped as per Araq's comments here,  http://forum.nim-lang.org/t/2025#12617 , and that got rid of the warnings. 

@Araq do you want a pull request for this?  Any other things that should be considered here?
