### ISSUE TITLE
getType proc family - surprising output in presence of alias with free parameter

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#5121]
```nim
import macros

type
  A = object
  AConst[X] = A

macro dumpType(t: typedesc): untyped =
  echo t.getType[1].typeKind
  echo t.getType[1].treeRepr
  newEmptyNode()

dumpType(A)
# without AConst:
#   ntyObject
#   Sym "A"
# with AConst:
#   ntyGenericBody
#   Sym "AConst"
```
The mere presence of `AConst` type alias changes `getType` output to something unexpected.

**PS:**
Additionallly, `getTypeInst[1]` and `getTypeImpl[1]` for `AConst[int]` return this:
```
BracketExpr
  Sym "AConst"
  Sym "int"
``` 
This exactly matches the result for a generic instantiation:
```nim
type B[X] = object
# for B[int]:
# BracketExpr
#   Sym "B"
#   Sym "int"
```
This means that we can't disambiguate an instantiation of a generic type from an instantiation of such alias, which is required for some applications (think reimplementing type equality algorithm).

Tested on aedafb99787d3613c6776bea625d9a43b2b7a8ea.

**Comment by Araq** [comment]
> This means that we can't disambiguate an instantiation of a generic type from an instantiation of such alias, which is required for some applications (think reimplementing type equality algorithm).

Yeah sure, reimplement your own type checker that differs in subtle ways from Nim's what could possibly go wrong? ;-)

**Comment by metagn** [comment]
Now (2.0) the above example gives:

```
ntyObject
Sym "A"
```

Issue might still exist in other cases but this one works now
