### ISSUE TITLE
Missing operations for int64

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5122]
There is no:
- operator ``/``
- function ``toFloat``

**Comment by Araq** [comment]
Well float is 64bits and so cannot cover all of int64.

**Comment by vegansk** [comment]
Yes, these are the operations with the loss of precision. Whether it will be acceptable if I implement them via cast to float?

**Comment by ringabout** [comment]
Now we have `toBiggestFloat` which is same as `toFloat` but for `BiggestInt`.
```nim
var a = 12'i64

echo toBiggestFloat(a)
```

**Comment by timotheecour** [comment]
* operator /

=> div

> Now we have toBiggestFloat which is same as toFloat but for BiggestInt.

there's also `float`:
```
var a = 12'i64
echo float(a)
```
