### ISSUE TITLE
system/timers missreports time in wine and windows

### ISSUE THREAD

**Issue by rbmz** [nim-lang/Nim#5146]
```
include "system/timers"

from os import sleep

var t0 = getTicks().Nanos
sleep(1000)
var t1 = getTicks().Nanos
  
echo float(t1 - t0)/1_000_000_000
```

```
output:
linux: 1.000199
wine: 0.010002387
windows 7 (cross-compiled in linux): 0.003843485
```

I know about the times library, but it seemed to be quite imprecise in windows and nim's garbage collector seems to rely on system/timers so I thought I'd report.

My use case is for the stopwatch library, this is the relevant issue we have: https://github.com/define-private-public/stopwatch/issues/1

**Comment by Araq** [comment]
well that's not how the API works. You MUST not take the diff from 'Nanos' but use the '-' for Ticks instead! Nevertheless it seems wrong by a factor of 1000, still investigating.
