### ISSUE TITLE
C++ codegen: type alias with exportc leads to incorrect generated code

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#5149]
Example:
**a.nim:**
```nim
type
  X* = object
    a: int
  Y* {.exportc.} = X

proc impl*(x: X) =
  echo "it works"
```
**b.nim:**
```nim
import ./a

proc run(y: Y) =
  impl(y)

run(Y())
```
Compiling **b.nim** with `cpp` backend leads to this error:
```
/home/dmitry/work/tmp/dynlib/nimcache/dups_b.o: In function `run_prMnBx24lrAl4F5T4VBWIw(Y)':
dups_b.cpp:(.text+0xf6): undefined reference to `impl_12kjjADT6kRMb9a9albDQ9bBQ(Y)'
```
The reason is that **b.nim** defines `Y` not as an alias, but as a separate struct type, resulting in mismatched definitions for `impl_12kjjADT6kRMb9a9albDQ9bBQ`.

Tested on: e1828733f1eb187ef5a6ef58aea2704c8513d917
Bisect points to: 7bd473c59b9c54aca18b85efd78d484e0306c7be

**Comment by Araq** [comment]
I have a fix for this, but I don't like it. IMO the compiler should forbid this construct, you can't annotate implementation details like this after the actual type definition.
