### ISSUE TITLE
Build issue on RHEL 6.7

### ISSUE THREAD

**Issue by carloscosta** [nim-lang/Nim#5151]
Hi Nim developers,

I found an issue compiling from source the version http://nim-lang.org/download/nim-0.15.2.tar.xz in my machine, a Red Hat Enterprise Linux Server release 6.7 server.

After download, I ran the command `sh build.sh` as suggested. Got the following linking errror:

> c_code/2_2/stdlib_osproc.o: In function `nospwaitForExit':
> stdlib_osproc.c:(.text+0x17cb): undefined reference to `clock_gettime'
> stdlib_osproc.c:(.text+0x1863): undefined reference to `clock_gettime'
> stdlib_osproc.c:(.text+0x1a7e): undefined reference to `clock_gettime'
> collect2: ld returned 1 exit status

To resolve the issue, I opened the build.sh script and added `-lrt` to the LINKFLAG when my `$uos` is linux.

I hope I am helping somewhat.
Best regards!
Carlos.

**Comment by dom96** [comment]
Thanks for reporting. I believe this is already fixed in the latest code, but won't be fully fixed until we release a new version :)
