### ISSUE TITLE
epochTime reports negative numbers and inconsisten results in Windows

### ISSUE THREAD

**Issue by rbmz** [nim-lang/Nim#5165]
```
import times
var acc = 0.0

for i in 0..<10000000:
  var t0 = epochTime()
  var t1 = epochTime()
  acc += t1 - t0

echo acc
```

sample output (many runs):
```
0.2053232213947922
0.2868634938495234
0.2911319518461824
0.3012332766084001
0.1134112435393035
0.1547119343886152
0.1386491021839902
-0.06694710080046207
0.07292055629659444
0.04386777780018747
0.3495538961142302
0.4371763499220833
0.1511758855776861
```

(Cross-compiled from linux, if that matters).

**Comment by dom96** [comment]
Results are consistent on OS X, so it appears that this is a Windows issue. Can anyone confirm without cross-compiling?

**Comment by define-private-public** [comment]
I can confirm it.  Check that referenced issue for more details.

**Comment by rbmz** [comment]
I don't think the referenced issue has any more details about this issue. The (still unreported as of now) OS X issue seems unrelated to me.

**Comment by jlp765** [comment]
I couldn't reproduce it on a win7 64-bit compiled as cpp not c  using mingw (and not ported from Linux)

Tested by wrapping in another loop of 100 iterations, and  
if acc < 0: echo ac

**Comment by rbmz** [comment]
@jlp765 I could only reproduce 2 of 3 runs with your version.

I tested in win7 64-bit with a cross-compiler 32 bit exe

**Comment by jlp765** [comment]
@rbmz can you place this around the calls to epochTime()

```
{.push posix: off.}
  # calls to epochTime() here
{.pop.}
```
and try the cross compile again

**Comment by rbmz** [comment]
Tried it and the problem persisted. Then I compared the nimcaches and the same files were produced regardless of the pragma.

**Comment by jlp765** [comment]
Yeah OK, I was wondering if the cross compile caused it to use a different algorithm to be used, in ``lib/pure/times.nim``

```
  when not defined(useNimRtl):
    proc epochTime(): float =
      when defined(posix):
        var a: Timeval
        posix_gettimeofday(a)
        result = toFloat(a.tv_sec) + toFloat(a.tv_usec)*0.00_0001
      elif defined(windows):
        var f: winlean.FILETIME
        getSystemTimeAsFileTime(f)
        var i64 = rdFileTime(f) - epochDiff
        var secs = i64 div rateDiff
        var subsecs = i64 mod rateDiff
        result = toFloat(int(secs)) + toFloat(int(subsecs)) * 0.0000001
      else:
        {.error: "unknown OS".}
```

You could try swapping the order of when statement to (assuming this is of course where the problem is)

```
  when not defined(useNimRtl):
    proc epochTime(): float =
      when defined(windows):
        var f: winlean.FILETIME
        getSystemTimeAsFileTime(f)
        var i64 = rdFileTime(f) - epochDiff
        var secs = i64 div rateDiff
        var subsecs = i64 mod rateDiff
        result = toFloat(int(secs)) + toFloat(int(subsecs)) * 0.0000001
      elif defined(posix):
        var a: Timeval
        posix_gettimeofday(a)
        result = toFloat(a.tv_sec) + toFloat(a.tv_usec)*0.00_0001
      else:
        {.error: "unknown OS".}
```
and see if that makes a change.

**Comment by rbmz** [comment]
That wasn't it. Moreover, the push/pop pragmas seem to be ignored.
If I swap `when defined(windows):` and `when defined(linux):` I get the following compilation error:

`lib/pure/times.nim(569, 9) Error: undeclared identifier: 'posix_gettimeofday'`

**Comment by cheatfate** [comment]
Because `epochTime()` uses `posix_gettimeofday()` and `getSystemTimeAsFileTime()` negative results are possible, when OS adjusts time() via (ntp, ntpdate or any other time synchronizing).

Windows 10 x64, and i can't reproduce it.

**Comment by cheatfate** [comment]
@rbmz are you running your tests in VM?

**Comment by rbmz** [comment]
@cheatfate no

**Comment by GULPF** [comment]
IMO this can be closed. There's nothing Nim can do about this and `epochTime` isn't supposed to be monotonic anyway.

**Comment by Araq** [comment]
Cannot reproduce and even if I could, we can't fix OS glitches.
