### ISSUE TITLE
Internal error with named tuples in iterator yield statement

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#5173]
items_pair.nim is 

```Nim
type
  TRange = object
    low: int
    high: int

iterator items(range: TRange): int =
  var i = range.low
  while i <= range.high:
    yield i
    inc i

type PairsRecord = tuple
  a: int
  b: char

iterator pairs(range: TRange): PairsRecord = #tuple[a: int, b: char] =
  for i in range:  # uses Range.items
    yield (a: i, b: char(i + ord('a'))) # this is the line of the error

for i, c in TRange(low: 1, high: 3):
  echo c
```

Compiling with most recent Nim gives.

items_pair.nim(18, 13) Error: internal error: expr(nkExprColonExpr); unknown node kind
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>

The problem doesn't occur if I use unnamed tuples or objects.

**Comment by krux02** [comment]
I could further reduce the problem, and add a minimally different change that does work. 
```Nim
iterator someIterator(): tuple[i: int, c: char] =
  let tup = (i: 1, c: 'c')  
  yield(tup)            # works nicely
  yield((i: 1, c: 'c')) # semantically the same, does not work

for i, c in someIterator():
  echo i, c
```
The cause of this bug is very likely in the implementation of the yield statement, so I would rename to issue to something related to the yield statement.
