### ISSUE TITLE
new import syntax doesn't work?

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5185]
```nim
import nimblepkg/cli, nimblepkg/tools
```

works, but this fails:

```nim
import nimblepkg/[cli, tools]
```

**Comment by Araq** [comment]
works for me. Bootstrapping problem?

**Comment by dom96** [comment]
Also, now that I think about it. Shouldn't the following syntax be used for this instead?

```nim
from nimblepkg import cli, tools
```

**Comment by Araq** [comment]
No, that would not be consistent with anything else.

**Comment by dom96** [comment]
I don't know what is going on but the following works:

```nim
import strutils
import nimblepkg/[cli, tools]
```

and yet if I remove the first import it doesn't:

```nim
import nimblepkg/[cli, tools]
```

> No, that would not be consistent with anything else.

This is how it works in Python. Although admittedly in Python you always importing modules, not variables/procedures/templates/etc. Why can't we add modules into the list of things that can be imported using this syntax?

**Comment by Araq** [comment]
Your proposed syntax is ambiguous: What if I have a  nimblepkg.nim and a  nimblepkg/ directory?

**Comment by dom96** [comment]
There is still something wrong with this syntax.

```
~/projects/untar » tree              
.
├── master.tar.gz
├── src
│   ├── untar
│   ├── untar.nim
│   └── untarpkg
│       ├── gzip.nim
│       └── tarfile.nim
└── untar.nimble
```

```nim
import untarpkg/[tarfile, gzip] # Doesn't work
import untarpkg/tarfile, untarpkg/gzip # Does work
```

**Comment by moigagoo** [comment]
I know the issue is closed, but I wanted to share some additional info. I've also encountered this issue, and the workaround is to use `import src/untarpkg/[tarfile, gzip]`.

**Comment by dom96** [comment]
I guess you just need to upgrade to devel.
