### ISSUE TITLE
vccexe and the compiler version

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5194]
I have the project that produces static library. And it must be compiled with VS 2008, because this library is used in another project that uses VS 2008. But I can't do that because I have also installed VS 2015. vccexe doesn't provide mechanism to choose the required compiler version.

**Comment by crackedmind** [comment]
I think, you can do `set VS140COMNTOOLS=` as workaround. And don't forget to clean nimcache directory

**Comment by krux02** [comment]
Is this a question, or a bug report for visual studio?
