### ISSUE TITLE
The compatibility with visual c 2008 is broken.

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5195]
It's done in the commit https://github.com/nim-lang/Nim/commit/a13e2bd5ec9b152474a19aa3fe372df8a25d47be. This compiler doesn't support /FS switch

**Comment by dom96** [comment]
At least you can remove that switch easily. Do we want to support Visual C 2008 out of the box? It is rather old now.

**Comment by vegansk** [comment]
We have one project that still uses VS2003 :-) And it will not be ported to the latest VS because codebase is really damn huge and we cannot expect that there will be no problems with the project or with some of it's dependencies.

Nevermind, I can easily write project's own nim.cfg
