### ISSUE TITLE
Missing vccexe in binary distribution for windows

### ISSUE THREAD

**Issue by crackedmind** [nim-lang/Nim#5210]

**Comment by Araq** [comment]
'koch tools' should build it for you though.

**Comment by crackedmind** [comment]
And this is a problem. I don't have mingw32, only visual c++. And `koch tools` also needs vccexe

**Comment by barcharcraz** [comment]
I fixed this by changing "vccexe.exe" in the cfg files to cl.exe

**Comment by crackedmind** [comment]
@barcharcraz tnx, i missed this options

**Comment by Araq** [comment]
Nim now ships with vccexe.exe.
