### ISSUE TITLE
Unstable tuple destructuring behavior in Nim VM

### ISSUE THREAD

**Issue by subsetpark** [nim-lang/Nim#5221]
With nim version:
```
Nim Compiler Version 0.16.0 (2017-01-09) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```

Here's a snippet of a `nim secret` session:

```nimrod
[i]; nim secret
Hint: used config file '/usr/local/Cellar/nim/0.16.0/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: stdin [Processing]
>>> let (_, _, a) = (1, 2, 3)
>>> echo a
4377210336
>>> let (_, _, b) = (1, 2, 3)
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
 ~/code/nim
```

Needless to say, the same code when compiled produces the expected output:

```
[i]; ./scratch
3
3
```

Interestingly, changing the number of elements in the tuple resolves the first error but leaves the second:

```nimrod
>>> let (_, a) = (1, 2)
>>> a
2
>>> let (_, b) = (1, 2)
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by subsetpark** [comment]
Perhaps unsurprisingly, the file which runs and compiles normally fails with the same SIGSEGV if the lines are put in a `static` block.

**Comment by kirbyfan64** [comment]
Err... there's a reason it's called `nim secret`.

**Comment by Araq** [comment]
@kirbyfan64 well he asked on IRC whether he should report it and I said yes.  Often, like in this case, it's a general VM bug, not specific to the REPL.

**Comment by krux02** [comment]
I just made a test file that can be executed to check this error:

```Nim
block:
  let (_, _, a) = (1, 2, 3)
  let (_, _, b) = (1, 2, 3)
  assert a == b
    
static:
  let (_, _, a) = (1, 2, 3)
  let (_, _, b) = (1, 2, 3)
  assert a == b
```
