### ISSUE TITLE
`path` config option doesn't work when compilation is invoked from a different directory

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/Nim#5228]
We have two directories foo and bar, and we want to import foo/foo.nim from bar/bar.nim. To do it, we should set `path` option to `../src` in bar/bar.nim.cfg, bar/config.nims, bar/bar.nims, or explicitly in `nim c` call.

In any of these cases, compiling bar/bar.nim fails with import error if invoked from the root directory and succeeds when invoked from bar.

Here's a sample repo to reproduce the issue https://github.com/moigagoo/nimpathtest

Reproduced on Nim 0.16.0, Windows 10.

**Comment by Araq** [comment]
Works on OSX at least.

**Comment by moigagoo** [comment]
Confirm that it works on OSX.

On a side note:

> paths are interpreted relatively from the file they are specified in

It looks like they are interpreted relatively from the dir the compilation is invoked in. If I leave only `switch("path", "./foo")`, compilation still works with `nim c -r bar/bar`.

**Comment by moigagoo** [comment]
Nim dump output from inside bar:

```
$ nim dump
Hint: used config file 'C:\Users\moigagoo\scoop\apps\nim\current\config\nim.cfg' [Conf]
-- list of currently defined symbols --
niminheritable
nimrequiresnimframe
nimbabel
nimrod
nimeffects
nimalias
nimlocks
nimKnowsNimvm
nimtypedescfixed
nimunion
nimmixin
nimcomputedgoto
nimparsebiggestfloatmagic
nimNewShiftOps
nimvarargstyped
nimnewshared
nimhygiene
nimDistros
nimImmediateDeprecated
nimArrIdx
gcc
nimnomagic64
nimnode
-- end of list --
..\foo
.foo
C:\Users\moigagoo\scoop\apps\nim\current\lib\pure
C:\Users\moigagoo\scoop\apps\nim\current\lib\core
C:\Users\moigagoo\scoop\apps\nim\current\lib\arch
C:\Users\moigagoo\scoop\apps\nim\current\lib\pure\unidecode
C:\Users\moigagoo\scoop\apps\nim\current\lib\js
C:\Users\moigagoo\scoop\apps\nim\current\lib\posix
C:\Users\moigagoo\scoop\apps\nim\current\lib\windows
C:\Users\moigagoo\scoop\apps\nim\current\lib\wrappers\linenoise
C:\Users\moigagoo\scoop\apps\nim\current\lib\wrappers
C:\Users\moigagoo\scoop\apps\nim\current\lib\impure
C:\Users\moigagoo\scoop\apps\nim\current\lib\pure\concurrency
C:\Users\moigagoo\scoop\apps\nim\current\lib\pure\collections
C:\Users\moigagoo\scoop\apps\nim\current\lib\deprecated\pure
C:\Users\moigagoo\scoop\apps\nim\current\lib\deprecated\core
C:\Users\moigagoo\scoop\apps\nim\current\lib
C:\Users\moigagoo\scoop\apps\nim\current\lib
```

**Comment by moigagoo** [comment]
I think I can see the problem. `.foo` should be `.\foo`.

**Comment by moigagoo** [comment]
On Mac, the values are ../foo and ./foo, which is correct, thus the proper path resolution.

**Comment by moigagoo** [comment]
Silly workaround: `switch("path", ".\\foo")`. Works on Windows and OSX.
