### ISSUE TITLE
Links in docs shouldn't point to master

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5229]
otherwise edits occur against master and PRs are created [against master too](https://github.com/nim-lang/Nim/pull/5223#issuecomment-272969967).

**Comment by Araq** [comment]
No, the website's docs are about the latest stable release. The corresponding source code for this is in master.

**Comment by dom96** [comment]
Should we accept PRs against master then?

**Comment by Araq** [comment]
No, why?
