### ISSUE TITLE
Tuple unpacking from iterator fails with parentheses

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#5230]
```nim
type PairsRecord = tuple
  a: int
  b: char

iterator pairs(low: int, high: int): PairsRecord =
  for i in low..high:
    yield (a:i, b:char(i + ord('a')))

proc main() =
  for (i,c) in pairs(1, 13):
    echo "i=", i, " c=", c

main()
```
items_pair.nim(10, 7) Error: identifier expected, but found '('

Works when parentheses removed.

**Comment by Araq** [comment]
That's how Nim's grammar works. Since there is no tuple unpacking involved really, we don't support ``()`` in this context. Otherwise you would complain ``for ((i, a), b) `` is not supported.

**Comment by yglukhov** [comment]
@Araq are there any design problems with tuple unpacking, or it might be implemented in future?

**Comment by Araq** [comment]
It's not clear what  ``for (x, y) in a`` should mean when ``a`` is a seq consisting of tuples. Should it invoke ``pairs`` or unpack the tuples?
