### ISSUE TITLE
paramCount and paramStr from the "os" module are defined on Posix

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#5236]
The documentation claims they are not:
https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L1376

**Comment by vegansk** [comment]
It's defined for executables and not defined for dynamic libraries, see https://github.com/nim-lang/Nim/pull/5138

**Comment by dom96** [comment]
As far as I can tell the docs are correct. Closing.
