### ISSUE TITLE
[nim v0.16.0]  can not build with --cc:vcc

### ISSUE THREAD

**Issue by shawnye** [nim-lang/Nim#5247]
`nim c  --cc:vcc -d:release --cpu:i386 -t:/MD   main.nim`

<pre>
CC: main
Error: unhandled exception: 系统找不到指定的文件。(Translate: Can not find the specified file.)
Additional info: Requested command not found: 'vccexe.exe /c --platform:x86 /nologo /MD -DWIN32_LEAN
_AND_MEAN /O2  /IE:\yexy6\nim-0.16.0\lib /Fog:\dev\nim\md5maker\nimcache\main.obj g:\dev\nim\md5maker\nimcache\main.c'. OS error: [OSError]
</pre>

I found the nim.cfg has been changed a lot from v0.15.2

I don't know where the `vccexe.exe` is .

**Comment by ringabout** [comment]
follow the instructions for https://github.com/pragmagic/godot-nim/issues/35#issuecomment-411746776
 
works for me(win10 + amd64).
