### ISSUE TITLE
Lazy man Suggestion: make colon(:) optional in var definition, just like Golang 

### ISSUE THREAD

**Issue by shawnye** [nim-lang/Nim#5248]
As a lazy man, I suggest makeing colon(:) optional in var definition if possible, just like Golang , that is:

`var str: string` ==&gt;  `var str string`

I forget colon(:) each time I come back to nim.

**Comment by Araq** [comment]
I suggest Golang allows the colon in var definition if possible. It's just more readable and Golang's halfassed ways of doing declarations are only shared by SQL anyway. Rust, Scala, TypeScript all use the colon for type annotations.

**Comment by cupen** [comment]
no please. It's unreadable.

**Comment by krux02** [comment]
please close this as rejected. It is a minor detail that doesn't matter that much at all. It is not worth discussing.

@cupen Try reasoning without using the Go language. Go is not seen as a Language with features worth copying here. When you have some scientific research or evidence that supports your argument, why no colon is better than a colon, then it is a different story.

**Comment by Araq** [comment]
> Go is not seen as a Language with features worth copying here.

We copied its ``defer`` statement fwiw.
