### ISSUE TITLE
0xFFFFFFFF convert to int32 result in 4294967295?

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#5251]
```nimrod
import typetraits
proc `$`*[T](some:typedesc[T]): string = name(T)

proc test(x: int64) = echo x
const
  A = 0xFFFFFFFF'i32 #'
  B = 0xFFFFFFFF.int32

test(A)
test(B)

echo "type of B is ", B.type
echo "B > int32.high ? ", B > int32.high
```

Nim Compiler Version 0.16.0
output is the same on both 32/64 bit mode:
-1
4294967295
type of B is int32
B > int32.high ? true

**Comment by krux02** [comment]
I think that A should raise a compile error, or at least a warning.  `0xFFffFFff` is in my opinion not a valid _int32_ literal. _uint32_ would be ok though.

_B_ should behave like _A_ currently does.

**Comment by Araq** [comment]
A should produce -1, that's what was asked for. B should produce a compiletime error.

**Comment by khchen** [comment]
I think A is ok, it use a hex format to represent a -1 value. The type must be int32 becasue I specify it.
B has the problem. It do a "int64 to int32" convert. However, the convert should raise a error.  
(0xFFFFFFFF without suffix always generate a int64 type value on both 32/64 bit)

**Comment by khchen** [comment]
We answer the question at the same time, lol.

**Comment by krux02** [comment]
I don't think B should produce a compile time error. When I call `int32` on an `int64` at runtime, I would also not expect a runtime error.

**Comment by khchen** [comment]
Here is a similar problem:
```nimrod
import winim
import typetraits

proc `$`*[T](some:typedesc[T]): string = name(T)

const
  A = 0xFFFFFFFE'u32 #'
  B = not A

echo A.type
echo B.type
echo B.int64
# echo B # Compile Error: cannot convert -4294967295 to uint64
echo cast[uint32](B)
```
output:
uint32
uint32
-4294967295
1

B is already uint32, however, I need use cast[uint32] to get the correct value.

**Comment by khchen** [comment]
Another type problem:
```nimrod
import typetraits
proc `$`*[T](some:typedesc[T]): string = name(T)
const
  A = -2147483648
  B = 2147483647
  C = -2147483648.int

echo A.type # int64, why not just int?
echo B.type # int, correct
echo C.type # int, correct
```
A literal should be a int type if it is possible.

**Comment by krux02** [comment]
I think this bug should get a tag `integer-literals-are-special`. Integer literals are treated specially in Nim, and there are known problems with it.

**Comment by markus-oberhumer** [comment]
See also issue #6829.

**Comment by Araq** [comment]
Now it fails to compile with "temp.nim(8, 17) Error: 4294967295 can't be converted to int32" which is good.

And the other example works as expected now.
