### ISSUE TITLE
Negative line count when compiling large file

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#5254]
I encounter an error message when compile a large source file:
> winapi.nim(-29432, 46) Error: type mismatch: got (int literal(2148139013)) but expected 'SCODE = int32'

The correct output should be winapi.nim(36104, 46)
-29432 = 0xFFFF8D08, 0x8D08 = 36104
The compiler only use a int16 value to store the line count.

**Comment by Araq** [comment]
yup.

**Comment by vitvakatu** [comment]
It's pretty easy to change, but here is the comment in compiler's code:
`  TLineInfo* = object          # This is designed to be as small as possible,
                                           # because it is used
                                           # in syntax nodes. We save space here by using
                                           # two int16 and an int32.
                                           # On 64 bit and on 32 bit systems this is
                                           # only 8 bytes.
    line*, col*: int16
    fileIndex*: int32`

As for me, it's premature optimization as it is, so I request opinions of team members about this issue

**Comment by Araq** [comment]
I would change it to uint16 for 'line', keeps the size benefits.

**Comment by Araq** [comment]
Was changed to uint16, so now your files can have more than 32_000 lines of code.
