### ISSUE TITLE
os.getTempDir() on Android

### ISSUE THREAD

**Issue by lbmn** [nim-lang/Nim#5260]
On [Termix](https://termux.com) (and likely other non-rooted device environments) many parts of the Unix filesystem are not writable.

This causes Nimble (and likely lots of other Nim stuff) to fail trying to write to /tmp.  There should ideally be a temp dir setting in `nimble.ini`, but many other Nim programs would still be affected by this issue.  

Perhaps [os.getTempDir()](https://github.com/nim-lang/Nim/blob/master/lib/pure/ospaths.nim#L521) should read getEnv("TEMP") on all platforms, and return an OS-specific default if it's blank.

An equivalent of [is_writable](http://php.net/manual/en/function.is-writable.php) in Nim's stdlib would also be helpful.

**Comment by Araq** [comment]
We need android as a first class OS and special case getTempDir for this.

**Comment by cheatfate** [comment]
```
/* Generate a unique temporary filename using up to five characters of PFX
   if it is not NULL.  The directory to put this file in is searched for
   as follows: First the environment variable "TMPDIR" is checked.
   If it contains the name of a writable directory, that directory is used.
   If not and if DIR is not NULL, that value is checked.  If that fails,
   P_tmpdir is tried and finally "/tmp".  The storage for the filename
   is allocated by `malloc'.  */
extern char *tempnam (const char *__dir, const char *__pfx)
```

**Comment by lbmn** [comment]
Would this be a good way to do it?

```nim

var getTempDir2_Cache = ""

proc getTempDir2*(): string =
  const
    envKeysToTry = @["NIMTMP", "TMPDIR", "TEMP", "TMP"]
    unixTmpDir = "/tmp/"
    windowsTmpDir = "C:\\WINDOWS\\TEMP\\"
    termuxTmpDir = "/data/data/com.termux/files/home/tmp/"
  # Use cache for repeat call speed:
  if getTempDir2_Cache != "":
    return getTempDir2_Cache
  proc getTempDir2_Search(): string =
    # First try via environmental value:
    for envKey in envKeysToTry:
      let envVal = getEnv(envKey).string
      if envVal == "": continue
      return if envVal[^1] == DirSep: envVal
             else: envVal & DirSep
    # Guess based on OS:
    when defined(windows): return windowsTmpDir
    if existsDir(termuxTmpDir): return termuxTmpDir
    # The last default:
    return unixTmpDir
  getTempDir2_Cache = getTempDir2_Search()
  return getTempDir2_Cache

```

**Comment by Araq** [comment]
That's not .gcsafe and why would the stdlib introduce NIMTMP? That's app specific, not Nim stdlib specific.

**Comment by MeinFuehrer** [comment]
What's the takeaway presently?

**Comment by MineFuehrer** [comment]
So, what's the takeaway from this?

**Comment by lbmn** [comment]
My code above was just a crude concept - I'm sure there are better ways to do it. 

Patching in my own getTempDir alternative seemed to work, but shortly thereafter I decided that compiling on Android is a bad idea to begin with.  So I didn't tinker with Nim on Termux any further.

Araq will decide if/when to change the stdlib.

**Comment by TiberiumN** [comment]
@libman why it's a bad idea?
For using applications myself I don't want to cross-compile them. Sure, I need to do this if I want to share my app as .apk

**Comment by TiberiumN** [comment]
Fixed now (with couven92 PR)

**Comment by TiberiumN** [comment]
@dom96 probably close?
