### ISSUE TITLE
quote copies NimNode into its tree

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5267]
When  using _quote_,  The VM copies that NimNode into the AST. This can be intentional, or a bug and it should just put the reference in the Tree. When this is intentional, I think it should be documented, when it is not intentional, it should be considered as a bug:

```Nim
import macros

static:
  let call = newCall( bindSym"echo", newLit"Hallo Welt" )

  let embeded = quote do:
    proc foo(): void =
      `call`

  call.add newLit"!!!"

  let embededCall = embeded[0][6][0]
  echo embededCall.lispRepr
  echo call.lispRepr
```
output:
```
Call(Sym(echo), StrLit(Hallo Welt))
Call(Sym(echo), StrLit(Hallo Welt), StrLit(!!!))
```

expected, when no deep copy is done in quote:
```
Call(Sym(echo), StrLit(Hallo Welt), StrLit(!!!))
Call(Sym(echo), StrLit(Hallo Welt), StrLit(!!!))
```

**Comment by Araq** [comment]
This has been fixed, right?

**Comment by krux02** [comment]
no, not as far as I know

**Comment by krux02** [comment]
Well new I can agree that quote does a deep copy on nodes that are injected via backtick. But still I think it should be written in the documentation. And that is easy to fix.
