### ISSUE TITLE
error passing seq to a macro.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#5272]
The following code generate weird AST while passing a seq.
result is: ``len([@, [1, 0, 2, 5, 6]])``
```nim
import macros

macro testmacro*(content: openArray[int]): int =
    result = newNimNode(nnkStmtListExpr)
    let wcontent = newNimNode(nnkBracket)
    for w in content:
        wcontent.add w
    result.add newCall("len", wcontent)
    echo repr result

echo testmacro([1,0,2,5,6]) # works as expected.
echo testmacro(@[1,0,2,5,6]) # fails with weird AST
```

**Comment by stisa** [comment]
I think that's because `@` is a proc that converts an array to a seq, and in the macro `content` is actually of type `NimNode`, so your for loop isn't iterating over elements of the openarray but on the children of the node ( using the `items` iterator from macros ).

`echo treerepr content` gives 
```
Prefix
  Sym "@"
  Bracket
    IntLit 1
    IntLit 0
    IntLit 2
    IntLit 5
    IntLit 6
```

**Comment by krux02** [comment]
this works

```Nim
import macros

macro testmacro*(content: static[openArray[int]]): int =
    result = newNimNode(nnkStmtListExpr)
    let wcontent = newNimNode(nnkBracket)
    for w in content:
        wcontent.add newLit(w)
    result.add newCall("len", wcontent)
    echo repr result

echo testmacro([1,0,2,5,6])  # works as expected.
echo testmacro(@[1,0,2,5,6]) # works as expected.
```

**Comment by Araq** [comment]
> I think that's because @ is a proc that converts an array to a seq, and in the macro content is actually of type NimNode, so your for loop isn't iterating over elements of the openarray but on the children of the node ( using the items iterator from macros ).

Exactly, no bug here, your macros need to become smarter.
