### ISSUE TITLE
streams.readLine(): string should raise IOError, but doesn't

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#5281]
There's two variants of readLine() in the streams module; one writing into a var parameter, the other returning a string.

The returning variant should raise a IOError according to the documentation header, but instead it just returns "" on EOF.

Even if that is the intended behaviour, then this is not workable because plaintext files often contain empty lines in between content.

**Comment by Araq** [comment]
Are you sure it doesn't return 'nil' on EOF?

**Comment by niv** [comment]
It doesn't for me, on OSX. Just returns "" for all  attempts at readLine after EOF. Even so, if nil is the desired behaviour instead of an IOError (but the rest of the api raises IOError), the docs should match up.

**Comment by dom96** [comment]
Can you remember which stream type in particular you were using? StringStream? FileStream?

**Comment by niv** [comment]
The issue happens with both stream types, as can be observed with this simple program:

```test.nim
import streams

let fs = newFileStream("test.nim")
while true:
  let ln = fs.readLine()
  echo "read: ", repr(ln)

let ss = newStringStream("a\nb\nc\n")
while true:
  let ln = ss.readLine()
  echo "read: ", repr(ln)
```

Neither while loop will ever raise an exception as the documentation promises, despite reaching EOF:

```
proc readLine(s: Stream): TaintedString {..}
Reads a line from a stream s. Note: This is not very efficient. Raises EIO if an error occurred.
```

**Comment by mpcjanssen** [comment]
Another example which never ends and never prints `nil!!!`

```nim
import os
import zip/gzipfiles
let gzStream = newGzFileStream(paramStr(1))

var i = 0

try:
  while true:
    let line = gzStream.readLine()
    if line == nil:
      echo "nil!!!"
    i = i + 1
    if i mod  10000 == 0 :
      echo i
except:
  echo "done"
```

**Comment by mpcjanssen** [comment]
Seems an issue in the underlying `readChar` at https://github.com/nim-lang/Nim/blob/devel/lib/pure/streams.nim#L177 which signals `EOF` with `\0` .
