### ISSUE TITLE
case in a template compile error

### ISSUE THREAD

**Issue by GaveUp** [nim-lang/Nim#5283]
On 0.16.0 this code results in a `value of type 'string' has to be discarded` error during compilation.

```Nim
template t(): typed =
  case 1
    of 1: "1"
    else: ""
echo t()
```

Araq suggested adding parentheses to work around the issue but they seemed to have no effect.

```Nim
template t(): typed =
  (case 1
    of 1: "1"
    else: "")
echo t()
```

**Comment by krux02** [comment]
I never managed to get `typed` as the result to do anything yet. I am not sure of it's purpose. But you can use both `untyped` or `string` as a result type instead.

**Comment by ringabout** [comment]
Since `typed` is deprecated and as `krux02` said changing return type to `string` or `untyped` works.

```
Warning: `typed` will change its meaning in future versions of Nim. 
`void` or no return type declaration at all has the same meaning 
as the current meaning of `typed` as return type declaration. [Deprecated]
```

Close this issue.
