### ISSUE TITLE
asyncdispatch doesn't handle thread exit properly

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5299]
The sample below raises "Too many open files" error on Linux/macOS, and occasionally crashes on Windows.
```nim
import asyncdispatch

type MyThread = Thread[void]

proc asyncThread() {.thread.} =
  let fd = newAsyncNativeSocket()
  fd.closeSocket()

var threads = newSeq[ptr Thread[void]](8)

for c in 1..1_000:
  for i in 0..<threads.len:
    var t = cast[ptr Thread[void]](alloc0(sizeof(MyThread)))
    threads[i] = t
    createThread(t[], asyncThread)

  for t in threads:
    joinThread(t[])
    dealloc(t)
```
These changes fix FD leaking on nix systems, but Windows crash still remains: https://github.com/endragor/Nim/commit/2bb101dc47cb363f807beebc85bd634ac5c7d233

/cc @cheatfate

**Comment by endragor** [comment]
Seems that the Windows crash disappears when enabling `--gc:markAndSweep`, so could be GC-related. `-d:useGcAssert` and `-d:useSysAssert` yield nothing though.

**Comment by cheatfate** [comment]
This is not asyncdispatch, but this is still bug. @endragor you need to rename topic.

```nim
import sets

var somethingElse {.threadvar.}: ref string

type MyThread = Thread[void]

proc asyncThread() {.thread.} =
  new somethingElse

var threads = newSeq[ptr Thread[void]](8)

for c in 1..1_000:
  echo "Test " & $c
  for i in 0..<threads.len:
    var t = cast[ptr Thread[void]](alloc0(sizeof(MyThread)))
    threads[i] = t
    createThread(t[], asyncThread)

  for t in threads:
    joinThread(t[])
    dealloc(t)
```

**Comment by endragor** [comment]
Opened #5301 to track Windows crash issue. This issue is still valid for FD leaks, I'll open a PR for it.

**Comment by narimiran** [comment]
I've tried both provided examples and they seem to work on the latest devel on Linux.

@endragor can you test it on Windows and report back if it has been fixed or not?

**Comment by narimiran** [comment]
No response for (almost) a year. Closing.
