### ISSUE TITLE
Argument ordering can lead to ignoring of some arguments.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#5307]
platform: Linux x64
nim version:  latest (76eb20d2d35335)
Here is an example with trying to make an LTO build, but the bug appear for all kind of argument.

this works just fine and makes an LTO build.
``nim c --listCmd --passc: -flto --passl: -ftlo  main.nim``

while this doesn't and ignore any kind of passc or passl argument.
``nim c --listCmd --passc: -flto --passl: -ftlo --cc:gcc  main.nim``

Setting the compiler first, then passing options works just fine.
``nim c --cc:gcc   --listCmd --passc: -flto --passl: -ftlo --cc:gcc  main.nim``

This is surprising behavior and should be corrected, I think .

Looking at the compiler code, it seems fairly simple to solve.
compiler/commands.nim line 603
and `setCC` in compiler/extccomp.nim
using '-cc" option overwrite any passC/passL option set before.
adding passC/passL  option to another global variable and appending to compileOptions when argument parsing is finished should work okay.

I can make a PR if this seems an acceptable solution.

**Comment by Araq** [comment]
Not sure. The config system has the same problem, set ``cc`` late and the options will be gone. Do we then use a two pass system for this too? The config system needs to get simpler, not more complex.

**Comment by Parashurama** [comment]
Well in that case this need to be more thought out.
First, we need to agree on desired behavior for the parser.
If i understood this correctly:  passC/passL don't replace previously set value but are appended to a list of option.
I was thinking any passC/passL option as arg or in any config files are added to a separate option list COMPILE/LINK_OPTIONS.
And then after loading all .cfg and parsed arguments, those three list are joined as needed.

**Comment by Araq** [comment]
Yes, that's how passC/passL work, but these are C compiler specific, so if I set CC these options need to be removed again. Consider this:  config contains passC for GCC and then on the command line I set cc=vcc. How can I remove this passC setting in the config?

**Comment by Parashurama** [comment]
Well, shit.
I can't think of a solution at the moment.
Even requiring -cc:compiler before any --passC/passL in the cmdline doesn't work if it ignores any such option set in .cfg files.

**Comment by Araq** [comment]
> Even requiring -cc:compiler before any --passC/passL in the cmdline doesn't work if it ignores any such option set in .cfg files.

I think you misunderstand me.
