### ISSUE TITLE
Importing system/gc_stack triggers undeclared ident

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#5308]
-- nogc.nim --

import system/gc_stack
var rx: MemRegion

withRegion rx:
  discard 0

 [bpr: nim]$ nim c --gc:stack -d:release nogc.nim
Hint: used config file '/home/bpr/Applications/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: nogc [Processing]
Hint: gc_stack [Processing]
lib/system/osalloc.nim(12, 3) Error: undeclared identifier: 'sysAssert'
 [bpr: nim]$ uname -a
Linux brogoff-mv-lo-u 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:42:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 [bpr: nim]$  nim -v
Nim Compiler Version 0.16.1 (2017-01-31) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 8071648129909d47ff7d8d071938ba4c078fc7e4
active boot switches: -d:release

**Comment by Parashurama** [comment]
You are not supposed to import system/gc_stack into your module, everything is already available from system.nim if you pass the ``--gc:stack`` (included via system/mmdisp.nim)
This works just fine
```nim
var rx: MemRegion

withRegion rx:
    discard 0
```

**Comment by bpr** [comment]
It works if I don't import system/gc_stack. I wonder when that happened, because it used to work...
