### ISSUE TITLE
Nimble package list no longer works on lib.html

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#5318]
Nimble package list on https://nim-lang.org/docs/lib.html no longer works and displays "If you are reading this you are missing nimblepkglist.js or have javascript disabled in your browser"

This is due to HTTP content being blocked (http://irclogs.nim-lang.org/packages?callback=gotPackageList).

**Comment by dom96** [comment]
Should be working now.

**Comment by watzon** [comment]
Looks like it's back to not working anymore https://nim-lang.org/docs/lib.html#nimble-unofficial-packages

**Comment by dom96** [comment]
The latest Nim must have broken the JS script. I get an error in the console:

```
Uncaught TypeError: c_13203.charCodeAt is not a function
    at cstrToNimstr (nimblepkglist.js:174)
    at getcurrentexceptionmsg_11657 (nimblepkglist.js:1090)
    at gotPackageList (nimblepkglist.js:1113)
    at packages:1
```

**Comment by dom96** [comment]
Fixed. See #6161 for new issue.

**Comment by genotrance** [comment]
This is broken yet again. 

https://nim-lang.org/docs/nimblepkglist.js => 404

**Comment by andreaferretti** [comment]
This may be a good opportunity to remove that list from there, since rendering it blocks browsers more often than not, and substitute it with a link to https://nimble.directory/ or something
