### ISSUE TITLE
Cannot unregister/close AsyncEvent from within its handler

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5331]
This was introduced by recent changes. It was possible to unregister/close AsyncEvent from its handler (which makes sense, similar to sockets) and now you get `Descriptor [N] is not registered in the queue!` raised by poll(). Sample:
```nim
import upcoming.asyncdispatch

let e = newAsyncEvent()
addEvent(e) do (fd: AsyncFD) -> bool:
  e.unregister()
  e.close()

e.setEvent()
poll()
```

/cc @cheatfate

**Comment by cheatfate** [comment]
I think to fix this issue, i will add more comments to `asyncdispatch` documentation.
Something like
``` nimrod
## If you need to unregister `AsyncEvent` object inside of callback for this event,
## do not use `unregister`, just return `false` on exit from this callback.
```

**Comment by endragor** [comment]
How would you close() the event in such case?

**Comment by cheatfate** [comment]
ok, wait for a patch.
