### ISSUE TITLE
Seq of object literals skips unmentioned fields

### ISSUE THREAD

**Issue by J0eCool** [nim-lang/Nim#5339]
Reproducing code:
```nim
type
  Dirs = object
    left: int
    up: int
    right: int
    down: int

let
  a = Dirs(
    left: 1,
    right: 2,
  )
  b = Dirs(
    up: 1,
    down: 2,
  )
  works = @[
    a,
    b,
  ]
  fails = @[
    Dirs(left: 1, right: 2),
    Dirs(up: 1, down: 2),
  ]
echo a
echo b
echo works
echo fails
echo works == fails
```

Output:
```
(left: 1, up: 0, right: 2, down: 0)
(left: 0, up: 1, right: 0, down: 2)
@[(left: 1, up: 0, right: 2, down: 0), (left: 0, up: 1, right: 0, down: 2)]
@[(left: 1, up: 2, right: 0, down: 0), (left: 1, up: 2, right: 0, down: 0)]
false
```

Compiled with `nim c -r test.nim`, with release nim compiler 0.16.0, git hash b040f74356748653dab491e0c2796549c1db4ac3, on Windows 64-bit

This also happens with varargs, e.g.
```nim
proc workaroundSeq(args: varargs[Dirs]): seq[Dirs] =
```

**Comment by Araq** [comment]
It doesn't skip them, it seems to ignore the field names and use the underlying order.

**Comment by J0eCool** [comment]
Er, right, that's what I meant by the fairly-unspecific "skips"
The generated C code builds a struct literal with no gaps, thus having the effect of using the underlying order. A simple fix might be to use [designated initializers](https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html)? Not sure about the Nim compiler internals but it's an option if that's convenient.

**Comment by Araq** [comment]
We support C89 here which doesn't have them.
