### ISSUE TITLE
Enable manual destructor invocation for implicitly generated destructors

### ISSUE THREAD

**Issue by jacobdufault** [nim-lang/Nim#5342]
Right now, it does not appear to be possible to manually invoke the destructor for a type when that destructor is defined implicitly, ie, it contains a destructable type.

```nim
{.experimental.}

type
  A = object
  B = object
    a: A

proc `=destroy`(a: A) = echo "~A"

`=destroy`(A()) # Compiles and works as expected
# `=destroy`(B()) # Does not compile.
```

**Comment by Araq** [comment]
So? Manual destruction invocations defeat the purpose.

**Comment by jacobdufault** [comment]
This is useful if you have memory that is not managed by the Nim runtime / GC and you explicitly call free.

**Comment by ringabout** [comment]
The original example doesn't work anymore, so I modified the example which doesn't work at Nim 1.0.x.

```nim
type
  A = object
  B = object
    a: A

proc `=destroy`(a: var A) = echo "~A"

var x = A()
var y = B()
`=destroy`(x)
`=destroy`(y)
``` 

/usercode/in.nim(13, 11) Error: internal error: destructor turned out to be not trivial
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>

**Comment by timotheecour** [comment]
> So? Manual destruction invocations defeat the purpose.

eg use case: destructor calling another destructor, eg: https://github.com/nim-lang/RFCs/issues/244
```nim
proc `=destroy`*[T](dest: var Isolated[T]) {.inline.} =
  # delegate to value's destroy operation
  `=destroy`(dest.value)
```

**Comment by Araq** [comment]
I wrote this 4 years ago when destructors worked very differently...
