### ISSUE TITLE
koch.nim syntax error in git commit 379bde

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#5347]
Compilation of koch.nim now has this error:

<pre>
koch.nim(227, 31) Error: invalid character constant
</pre>

Looks like it's because of this:

<pre>
 nimexec("c --cc:vcc --app:gui -o:downloader.exe --noNimblePath " &
         "--path:..\ui tools\downloader.nim")
</pre>

There are unescaped backslash characters in there.

I'm compiling under Debian 8.

**Comment by Araq** [comment]
Fixed.
