### ISSUE TITLE
Surprising behaviour when printing tuple with seq

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5350]
```nim
echo(("asd", @[""]))
```

Gives

```
(Field0: asd, Field1: @[])
```

Note the lack of ``"`` inside the ``@[]``.

**Comment by bluenote10** [comment]
Isn't this always the case and not specific to the tuple? All of the following result in `@[]` for me:

    echo(("asd", @[""]))
    echo @[""]
    let x = @[""]
    echo x

Which would also be consistent with `$` in general, i.e., `echo @["Hello", "World"]` produces `@[Hello, World]` (also no quotes, just the pure strings).

**Comment by dom96** [comment]
Relevant IRC discussion: https://irclogs.nim-lang.org/07-02-2017.html#17:12:30

**Comment by GULPF** [comment]
Fixed by #6825?

**Comment by Yardanico** [comment]
Current output:
```nim
(Field0: "asd", Field1: @[""])
```

**Comment by dom96** [comment]
Yep, fixed.
