### ISSUE TITLE
seq[empty] not allowed in array initializations

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#5356]
When trying to create an array of sequences I ran into this annoying problem. When initialising the array as such:
```var b:array[ -2..2, seq[int] ] = [ @[], @[], @[], @[], @[] ]```
I get the error message:
```Error: type mismatch: got (array[0..4, seq[empty]]) but expected 'array[-2..2, seq[int]]'```
The error is the same if the initial statement is changed from -2..2 to 0..4 so that's not the issue (maybe this should also be improved as an error message?). The problem is that it expects int sequences and is unable to accept empty sequences and make them into int sequences like it can in normal sequence assignments.

**Comment by PMunch** [comment]
This still happens, although not if any of the seqs contains an int. But with seqs not being able to be nil any longer one could simple not initialise an empty array of seqs and it would do the same thing. But I'm going to keep this issue open as it technically is still an issue.

**Comment by krux02** [comment]
Well empty seqences are allowed in array initializations, just when you put that at the beginning of an array the type of that array will be affected.

These are two working ways to do it properly.

```Nim
var a:array[ -2..2, seq[int] ] = [ `@`[int]([]), @[], @[], @[], @[] ]
var b:array[ -2..2, seq[int] ] = [ newSeq[int](), @[], @[], @[], @[] ]
```

**Comment by Araq** [comment]
@krux02 We need to ensure this typing rule for array literals is covered in the manual.
