### ISSUE TITLE
typedesc.name is None in macro context.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5358]
I am not entirely sure if I use the typedesc parameter here correctly. It could be that I just use it wrong.

```Nim
import typetraits

macro foobar(typ: typedesc): untyped =
  echo name(typ)

foobar(int)
foobar(float)
```
output:
```
None
None
```
i would expect something like this:
```
int
float
```

**Comment by krux02** [comment]
well when I look at this now, I think that `typ` should be of type `NimNode` and `name(typ)` should fail to compile. when typ is declared as `typ: static[typedesc]`, `typ` should have the type `typedesc` and calling name on it should work. But I am not so sure about it. I think typedesc values/tyes are super confusing.

**Comment by krux02** [comment]
Mentioning `getType`, shouldn't that become deprecated? I mean there is already `getTypeInst` and `getTypeImpl`, but to be honest I am myself a bit confused, because there is also `getImpl`.  

I don't really like the idea to introduce a distinct TypeNode. I mean generally it isn't too bad. But a lot of code that I've written, like the ast_pattern_matching or the recursive tree traversal should work for both types and expressions.

**Comment by zah** [comment]
The idea is that `NimNodeType` would match everywhere where a `NimNode` is accepted, but you'll be able to call the additional type-related operations over it. When I said `getType`, I meant the whole family of related functions. `getImpl` will still return regular nodes, but it should be possible to call it both over symbols and types.

**Comment by deansher** [comment]
Perhaps this is a simpler incarnation of the same bug?
```
from typetraits import name

echo name(if true: int else: string) # None
```
Here's my version:
```
deans-mbp-3:the-edge-of-Nim dean$ nim --version
Nim Compiler Version 0.19.0 [MacOSX: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release
deans-mbp-3:the-edge-of-Nim dean$
```

**Comment by krux02** [comment]
Well this one is fixed by now. `typedesc` is passed as `NimNode`.
