### ISSUE TITLE
It seems that -r executed process doesn't inherit env

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5364]
On macOS I had to set ``DYLD_LIBRARY_PATH`` and when I compile my application with ``nim c -r program`` it doesn't appear to be detecting that I set that env var. Whereas if I just run `./program` then it works fine.

**Comment by yglukhov** [comment]
That is macos behavior. `DYLD_LIBRARY_PATH` is not inherited for "security" reasons.

**Comment by dom96** [comment]
I see. Fun.
