### ISSUE TITLE
Destructor not called for specialized generic types

### ISSUE THREAD

**Issue by jacobdufault** [nim-lang/Nim#5366]
Destructor resolution does not work the same as proc resolution. In fact, specialized destructors are never even considered.

```nim
{.experimental.}

type A[T] = object

# This proc will never get called, even if the one below is commented out.
proc `=destroy`(o: A[int]) =
  echo "!!! destroy A[int] !!!"
proc `=destroy`[T](o: A[T]) =
  echo "!!! destroy A[T] !!!"

proc foo(o: A[int]) =
  echo "!!! foo A[int] !!!"
proc foo[T](o: A[T]) =
  echo "!!! foo A[T] !!!

proc main() =
  var a: A[int]
  a.foo()

main()
```

This program gives the output

```
!!! foo A[int] !!!
!!! destroy A[T] !!!
```

Note that `` `=destroy`(o: A[int])`` is never called, even if  `` `=destroy`[T](o: A[T])`` is commented out.

**Comment by zah** [comment]
Seems like the recent versions of Nim have regressed even further and now generic types cannot have destructors at all:

``` nim
{.experimental.}

type A[T] = object

# This proc will never get called, even if the one below is commented out.
#proc `=destroy`(o: var A[int]) =
#  echo "!!! destroy A[int] !!!"

proc `=destroy`[T](o: var A[T]) =
  echo "!!! destroy A[T] !!!"

proc foo(o: A[int]) =
  echo "!!! foo A[int] !!!"

proc foo[T](o: A[T]) =
  echo "!!! foo A[T] !!!"

proc main() =
  var a: A[int]
  a.foo()

main()
```

Produces:

```
destructors.nim(19, 7) Error: internal error: '=destroy' operator is generic
```

**Comment by Araq** [comment]
@zah compiled with ``--newruntime``?

**Comment by zah** [comment]
Works under `newruntime`, but why does it have to be enabled in order for the destructors to work? They are not incompatible in spirit with the old runtime.

**Comment by zah** [comment]
The compiler also doesn't accept the following syntax, which should work IMO:

``` nim
type A[T] = object

# This proc will never get called, even if the one below is commented out.
proc `=destroy`(o: A) =
  echo "!!! destroy A !!!"
```

**Comment by Araq** [comment]
This works now according to spec. It requires `--cursorInference:off` btw.
