### ISSUE TITLE
{.discardable.} pragma not work in some situation

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#5374]
Example code:
```nimrod
proc test1(): int64 {.discardable.} = discard
proc test2(): int {.discardable.} = discard

if true:
  test1()
else:
  test2()
```
Error message: 

> Error: value of type 'int64' has to be discarded

Compiler: Nim Compiler Version 0.16.0 (2017-01-08) [Windows: amd64]

**Comment by vitvakatu** [comment]
Confirmed.
Nim Compiler Version 0.16.1 (2017-02-25) [Linux: amd64]
I would like to work with this issue, but I'm new to Nim and do not have ideas what I should look for.

**Comment by dom96** [comment]
You can try something like this ``./koch temp c --verbosity:3 -r test_file.nim``. It will show you a traceback of where the error message comes from, you might be able to investigate the related code from there.

**Comment by vitvakatu** [comment]
@dom96, thank you, I will investigate for some time and will report about results (or lack of results)

**Comment by TiberiumN** [comment]
Seems to be fixed

**Comment by hlaaftana** [comment]
This can be closed, it was fixed
