### ISSUE TITLE
threadpool memory leak

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#5375]
This will slowly leak memory:
```nim
import threadpool

type A = ref object
  f: int

proc doThingsToA(a: A) =
  discard

proc myFunc() =
  let a = A(f: 5)
  spawn(doThingsToA(a))

while true:
  myFunc()
```

**Comment by Araq** [comment]
I doubt it's a real GC issue, but for now we have no "leak" label.

**Comment by ghost** [comment]
Can't seem to reproduce with ARC on latest devel - running the binary by itself and it stays on 1076KB of memory, Valgrind or MSAN report no leaks either.

**Comment by ghost** [comment]
It does seem to leak with refc though, the issue seems like that `a` in `doThingsToA` doesn't get free'd unless you call GC_fullCollect() manually:

```nim
import threadpool

type A = ref object
  f: int

proc doThingsToA(a: A) =
  discard
  # remove the next line and it'll leak
  GC_fullCollect()

proc myFunc() =
  let a = A(f: 5)
  spawn(doThingsToA(a))

while true:
  myFunc()

```
