### ISSUE TITLE
regression in abaf5d0b: "internal error: environment misses"

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#5376]
Compiling https://github.com/zielmicha/capnp.nim with compiler version abaf5d0b results in "internal error: environment misses: old" (previous commit is fine). This is quite complex code with lots of generics etc, so I haven't yet isolated root cause, but I maybe just this error message will help.

**Comment by Araq** [comment]
Yes, that is very helpful, thanks. I guess I should introduce yet another flag for this then.

**Comment by Araq** [comment]
Works again, as far as I can tell. Reopen if still an issue.
