### ISSUE TITLE
PThread callback doesn't work with --threads:on and --tlsEmulation:on on OSX

### ISSUE THREAD

**Issue by cjbest** [nim-lang/Nim#5381]
From Nim, call a c function that takes a callback to be executed on a pthread, [like in this code](https://gist.github.com/anonymous/e0a225a0fb8f0574ff82aaf51266a091)

Running this on OSX, I see:
```
$ nim c -r repro.nim
Will it work?
It worked!

$ nim c -r --threads:on repro.nim
Will it work?
<hangs indefinitely>

$ nim c -r --threads:on --tlsEmulation:off repro.nim
Will it work?
It worked!
```

I'm new to Nim and I don't totally understand what tlsEmulation does, but I'm guessing we expect this code to work either way?

**Comment by Araq** [comment]
Use and read about ``setupForeignThreadGc``.
