### ISSUE TITLE
CI artifacts

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5387]
I really really want to use our CI not just for testing but also to offer binary builds of Nim (and related tools) to our users. I mainly thought that Travis/AppVeyor didn't make this possible, but [certain news](https://twitter.com/rustlang/status/831219313189089280) have prompted me to change my mind.

I'm writing this issue in case anybody would like to give this a shot. As a first step I would like to see the following binaries produced for each commit:

* Linux x86 and x86_64
* Windows x86 and x86_64

macOS may even be possible with Travis CI nowadays but I remember seeing issues with it.

**Comment by FedericoCeratto** [comment]
CircleCI builds on Linux and OSX and hosts the build artifacts via HTTPS

**Comment by Araq** [comment]
We have nightly builds now.
