### ISSUE TITLE
nimsuggest completion sometimes misses imported symbols

### ISSUE THREAD

**Issue by JCavallo** [nim-lang/Nim#5397]
I am currently working on a neovim plugin for nim and I would like to use nimsuggest to provide completion, but I cannot make it behave as I expect in the following case :

File 1 (test1.nim) :

```
type
  MyType* = enum
    myEnum1,
    myEnum2
```

File 2 (test2.nim) :

```
import test1


```

When I call nimsuggest  with parameters `sug test2.nim:3:0`, there is no output, but I expected to have MyType, myEnum1, myEnum2.

However, I noticed that if I modify File 2 like :

```
import test1

test1.
```

Then calling nimsuggest with `sug test2.nim:2:0` effectively suggests symbols from test1.nim

Edit :
Nim Compiler Version 0.16.0 (2017-01-23) [Linux: amd64]
git hash: e17969c03f38874c57140b7162aa74318fa1cb2c
active boot switches: -d:release --gc:markAndSweep

**Comment by Araq** [comment]
Read the manual.
