### ISSUE TITLE
Array index type is lost when using enum range

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#540]
The following example works fine:

``` nimrod
when isMainModule:
  type
    TDirection = enum
      north, east, south, west
    TLevelSetting = array[TDirection, float]

  var level: TLevelSetting = [1.0, 2.0, 3.0, 4.0]
  for i in level[east..south]:
    echo($i)
```

However, if we change the definition of `TLevelSetting` to use only a range of the enum types, the compiler seems to _forget_ about the `TDirection` enum and casts it to an integer value:

``` nimrod
when isMainModule:
  type
    TDirection = enum
      north, east, south, west
    TLevelSetting = array[north..south, float]

  var level: TLevelSetting = [1.0, 2.0, 3.0]
  for i in level[east..south]:
    echo($i)
```

With this version the compiler says there's an error:

```
slice.nim(8, 17) Error: type mismatch: got (TLevelSetting, TSlice[TDirection])
but expected one of: 
system.[](a: array[Idx, T], x: TSlice[Idx]): seq[T]
system.[](a: array[Idx, T], x: TSlice[int]): seq[T]
system.[](s: string, x: TSlice[int]): string
system.[](s: seq[T], x: TSlice[int]): seq[T]
```

Is it a bug that enum ranges can't be used as an array range type definition due to the type being casted to an integer? I tried forcing the array type with an explicit TSlice:

``` nimrod
TLevelSetting = array[TSlice[TDirection](north..south), float]
```

but then the compiler barks at the `north..south` part:

```
slice.nim(5, 45) Error: ordinal type expected
```

**Comment by data-man** [comment]
On devel the second test outputs

> 2.0
> 3.0

**Comment by andreaferretti** [comment]
Confirmed - it is working now
