### ISSUE TITLE
``packed`` is not working with mingw

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5401]
It's mingw bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52991), but maybe we can switch on vcc style ``#pragma pack`` for it?

**Comment by vegansk** [comment]
Found workaround:
```nim
when defined(windows) and defined(gcc):
  {.passC:"-mno-ms-bitfields".}
```

**Comment by Araq** [comment]
Which version of MingW do you use?

**Comment by vegansk** [comment]
Version 5.3.0

**Comment by cheatfate** [comment]
This is duplicate issue for #4763.
