### ISSUE TITLE
Assigning from base to subclass throws ObjectConversionError

### ISSUE THREAD

**Issue by baabelfish** [nim-lang/Nim#5403]
```nim
type
    A = object of RootObj
        x: int
    B = object of A
        y: int

var x = A(x: 42)

block: # All fine using cast
    var y = cast[B](x)
    y.y = 1
    echo y # prints (y: 1, x: 42)
    
block:
    var y = B(x) # Error: unhandled exception: invalid object conversion [ObjectConversionError]
```

Should the latter work or at least be compile time error?

**Comment by Araq** [comment]
I think the current behaviour is fine (your cast is totally wrong btw and produces a stack corruption). You cannot convert A to B because A is not a B. Also use 'ref object' for sanity, but this is widely documented by now.
