### ISSUE TITLE
Compiler regression with struct member names

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#5404]
This morning I found i wasn't able to compile some code using `parseopt2.getopt()` as the `key` member of the tuple that is returned was being named `key_0` in the generated C code.

Here is a sample of the C code that was generated: https://gist.github.com/samdmarshall/fb4b4a92feedd263ee8b3cfb1ee4b0bc

Here is the output of `nimble build`:  https://gist.github.com/samdmarshall/82e3a6ce2239036709174ba97ec48266

I was using a version of the nim compiler built from 4ac6a26, and was not able to reproduce the issue any more when reinstalling 0.16.0. This leads me to conclude there was a regression introduced between the 0.16.0 release and the 4ac6a26 version i was using.

**Comment by Araq** [comment]
Well yes, the name mangling rules changed. Without any snippet or link I cannot do anything for you.

**Comment by samdmarshall** [comment]
oops, my apologies; this is the code in question: https://github.com/samdmarshall/necromancy/blob/bbfb29d88e4c29f590826d2be50addd0a4963c97/src/necromancy.nim#L45

**Comment by Araq** [comment]
Cannot test:

```
 ... /Users/andreasrumpf-mac/projects/necromancy/src/nimcache/necromancy_view.c:11:10: fatal error: 'termbox.h' file not found
        ... #include "termbox.h"
        ...          ^
```

**Comment by samdmarshall** [comment]
Here is a much more succinct example that demonstrates the problem i was having. I was able to move past this by removing the `{.importc.}` statement off the struct member **key**, and thus was able to remove my problem; but i'm told that this can cause structs to break compatibility due to alignment problems. 

https://gist.github.com/samdmarshall/90393fb137fe142e1d8a27821f356322
