### ISSUE TITLE
Invalid "lock level <unknown>" warning when callbacks are involved

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5415]
The sample below produces `declared lock level is 0, but real lock level is <unknown>` warning, even though it can be seen that a() never locks anything.

```nim
proc someCbProc(cb: proc()) =
  cb()

proc a() {.gcsafe, locks: 0.} =
  someCbProc(proc() = discard)

a()
```

Git hash: 363b1c0a41e4b554c46d8aa5af5ad1ed31523628

**Comment by dom96** [comment]
Possibly related to #6186
