### ISSUE TITLE
onThreadCreation is not invoked for spawn()ed threads

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5416]
Sample:
```nim
import threadpool

var someVal {.threadvar.}: int
someVal = 42

onThreadCreation() do ():
  someVal = 42

proc getSomeVal(): int =
  result = someVal

doAssert(^spawn(getSomeVal()) == 42)
```

Git hash: 363b1c0a41e4b554c46d8aa5af5ad1ed31523628

**Comment by endragor** [comment]
The problem is that the thread pool is initialized when the program starts. Perhaps it should be changed to be initialized on the first call to spawn()?

**Comment by Araq** [comment]
Meh. When you use the thread pool you don't know when threads are created, so I don't think we should support ``onThreadCreation``. Seems wiser to implement ``.threadvar, duplicate`` instead.

**Comment by endragor** [comment]
Would `.duplicate` work here if `onThreadCreation` doesn't? In the sample above the line `someVal = 42` is also evaluated when the threadpool's threads are already created.

**Comment by dom96** [comment]
Wouldn't it be better for ``{.threadvar.}`` to have these "duplicate" semantics by default?

**Comment by Araq** [comment]
> Would .duplicate work here if onThreadCreation doesn't? In the sample above the line someVal = 42 is also evaluated when the threadpool's threads are already created.

Good point, it wouldn't.

**Comment by endragor** [comment]
onThreadCreation is now removed. Problem solved.
