### ISSUE TITLE
The compilation of jester routes is broken on devel

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5417]
```
git clone https://github.com/dom96/jester && cd jester/tests && nim c -r alltest.nim
```

fails with:

```
lib/pure/asyncmacro.nim(291, 7) Hint: Processing match as an async proc. [User]
alltest.nim(10, 1) template/generic instantiation from here
lib/core/macros.nim(333, 70) template/generic instantiation from here
alltest.nim(27, 27) Error: invalid control flow: thisRoute
```

Nim hash is 363b1c0a41e4b554c46d8aa5af5ad1ed31523628

**Comment by dom96** [comment]
:open_mouth:

**Comment by vegansk** [comment]
Git bisect shows that It was broken in 97e2696

**Comment by vegansk** [comment]
The problem is that symbol ``thisRoute``, generated by the macros.genSym, has  owner of kind ``skPackage``, assigned to it in [this line](https://github.com/nim-lang/Nim/blob/devel/compiler/vm.nim#L1447). And in [that line](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L33) the owner of the proc context is the symbol of kind ``skIterator``, generated by the async macro.

**Comment by vegansk** [comment]
Here is the minimal test case:
```nim
import macros

macro genBody: untyped =
  let s = genSym(nskLabel, "test")
  result = quote do:
    block `s`:
      break `s`

proc test() =
  genBody()
```
