### ISSUE TITLE
Compiling with kissfft library, have to manually include nimble path for header

### ISSUE THREAD

**Issue by cjbest** [nim-lang/Nim#5431]
@dom96 suggested I make an issue here.

Going to use the [kissfft](https://github.com/m13253/nim-kissfft) library in the obvious way fails to compile:
``` sh
$ nimble install kissfft
$ echo "import kissfft/kissfft" > repro.nim
$ nim c repro.nim
Error: execution of an external compiler program 'clang -c  -w  -I/usr/local/Cellar/nim/0.16.0/nim/lib -o /Users/cjbest/tuna/nimcache/kissfft_kissfft.o /Users/cjbest/tuna/nimcache/kissfft_kissfft.c' failed with exit code: 1

/Users/cjbest/tuna/nimcache/kissfft_kissfft.c:11:10: fatal error: 'kissfft/kiss_fft.h' file not found
#include "kissfft/kiss_fft.h"
         ^
1 error generated.
```
kiss_fft.h is in the package, but doesn't get copied to nimcache, and the package seems to not be included by default. It works if you compile with:
```sh
$ nim c --cincludes:`nimble path kissfft` repro.nim
```

I'm not sure what the fix is, but it would be nice if the right stuff got included by default.

**Comment by dom96** [comment]
My idea was to get ``nim`` to implicitly add ``--cincludes:<path>`` for each nimble package. But I think @Araq wants something more explicit, he mentioned a pragma to me in PM.

**Comment by ringabout** [comment]
Nim devel on windows
`nim r --eval:"import kissfft/kissfft"` this compiles

cmdfile.nim(1, 15) Warning: imported and not used: 'kissfft' [UnusedImport]
