### ISSUE TITLE
strutils.escape creats wrong C string literals

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5434]
I am not sure, where exacty strutils.escape is used, but in this example it creates invalid code:

according to this documentation here: https://en.wikipedia.org/wiki/Escape_sequences_in_C
\x escape sequences may contain more than two digits to encode a character. Therefore the following sample gets interpreted wrongly

```
import strutils

static:
  let str = """
banana

crocodile

deadbeef

Xoobar
"""

  let escapedString = escape(str)
  echo escapedString
  let printfCall = """printf("%s\n", $1);""" % [escapedString]

proc main(): void =
  {. emit: printfCall .}

main()
```

output:
```
"banana\x0A\x0Acrocodile\x0A\x0Adeadbeef\x0A\x0AXoobar\x0A"
banana
\254rocodile
\357

Xoobar
```

The c from crocodile is interpreted as part of the `\x0A` sequence, and therefore there is an `\x0Ac` follewed by an rocodile. deadbeef is completely eaten by the hex escape sequence.

strutils.escape

**Comment by Araq** [comment]
The Nim compiler emits octal sequences for this reason. *YOU* use escape string here plus .emit. The Nim compiler doesn't check what you .emit is actually valid C code (how could it?).
