### ISSUE TITLE
Wrong method called

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#5439]
Sample program:
```nim
type
  Control* = ref object of RootObj

  ControlImpl* = ref object of Control

  Container* = ref object of ControlImpl

  ContainerImpl* = ref object of Container

method testProc*(control: Control) = echo "wrong method"
  
method testProc*(container: Container) = echo "correct method"
    
proc main()

main() # wrong method called

proc main() =
  var container = new ContainerImpl
  container.testProc()

# main() # correct method called

```
If "main()" is called below, the method of Container is called, which is correct.
If "main()" is called above, the method of Control is called, which is wrong.

Tested under Arch Linux AMD64 with Nim 0.16.0 and 0.16.1 (2017-02-25).

**Comment by Araq** [comment]
Cannot reproduce. Works for me for every OS/Nim version that I try.

**Comment by trustable-code** [comment]
New info: happens only when compiling with d:release.

**Comment by Araq** [comment]
Ha, indeed.
