### ISSUE TITLE
[RFC] braces skin

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5449]
Is it safe to use braces skin in the real projects? Or this feature can be removed in the future?

**Comment by dom96** [comment]
I don't know what @Araq's plans are but I am opposed to this feature. An IDE should provide it not the language.

**Comment by vegansk** [comment]
@dom96, I don't think that it's possible. For example, if nim-mode will support that, how it will communicate with magit and it's magit-blame command, or with tons of other plugins that I use?

There is read macros in Lisp, quasiquotes in Haskell, even in javascript there is readtables in sweet.js. Let's throw away the skins, but add the possiblilty of setting an external parser (or transformer) for the source code :-)

That's what I want to try to implement via macros :-)

**Comment by Araq** [comment]
> Is it safe to use braces skin in the real projects? Or this feature can be removed in the future?

It's not safe, don't use it.

> There is read macros in Lisp, quasiquotes in Haskell, even in javascript there is readtables in sweet.js. Let's throw away the skins, but add the possiblilty of setting an external parser (or transformer) for the source code :-)

I'm all ears. How would this feature work?

**Comment by dom96** [comment]
I use Nim because of its syntax. Personally whenever I consider using another library I often look at its source code and if I see something non-standard I immediately get discouraged from using it. When seeing a library written with braces instead of whitespace I would have the same reaction, as I'm sure many others would also.

So please, just learn to love whitespace :)

**Comment by dom96** [comment]
As for putting this feature in the IDE: I don't think it's impossible. Although I don't understand what your reasoning is. What's magit? I assume a ``git`` plugin for emacs? Surely you could transform its diffs into curly braces?

But maybe this is a limitation in emacs' plugin infrastructure.

**Comment by vegansk** [comment]
@Araq, I want to try to implement this feature using macros, so let's return to it when I'll have something to show. 
You can look at [this example](https://github.com/jlongster/jsx-reader) - the implementation of JSX syntax in javascript using sweet.js readtables.
