### ISSUE TITLE
Confusion over `existsOrCreateDir`

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#5459]
Talking about this: https://github.com/nim-lang/Nim/blob/master/lib/pure/os.nim#L1091

With what the docs says:
```
Returns true if the directory already exists, and false otherwise
```

So even if the function successfully creates a directory it returns false.  Wouldn't we want it to return `true` on successful directory creation?

**Comment by trustable-code** [comment]
I think the return value is not important, because it raises an exception when the directory could not be created.

**Comment by Araq** [comment]
Exactly.
