### ISSUE TITLE
Don't use relative imports for non relative modules (aka babel libs)

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#546]
Suddenly some of my code stopped compiling: the code depended on argument_parser and it failed to compile due to undefined TRunes. The argument_parser is installed through babel and I first started looking around babel paths and compiler version to see if anything changed, only until I realised I had created an unicode.nim file in the current relative path.

I was about to suggest compiling all available stdlib module names into the nimrod compiler so it can hint warnings if another named like that is present, but I think it would be possible to avoid this issue if modules imported through babel path (or other path parameters) were unable to import module files in the current working directory.

Which means that a user would never be able to *override* a module like unicode used by the argument_parser module. Or maybe there's a ``import $stdlib/unicode`` to force the import use the stdlib version instead of a local ``unicode.nim``? Or maybe this module *shadowing* is a feature?

**Comment by dom96** [comment]
Could we maybe add a pragma or flag that explicitly states ``--override:panicoverride.nim``?
