### ISSUE TITLE
Confusion over 'countLines()'

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#5460]
It says: "This is the same as len(splitLines(s)), but much more efficient because it doesn't modify the string creating temporal objects."

This is wrong. While countLines(s) returns 0 for a string without line break, len(splitLines(s)) returns 1.

My suggestion:
- Make countLines() the same as len(splitLines(s)), because this is what the name suggests and what you need to calculate the height of a text.
- If needed, add another proc 'countLineBreaks()', which has the behavior of the existing countLines().

**Comment by Araq** [comment]
Make it behave according to the documentation.

**Comment by trustable-code** [comment]
This change should be mentioned in the changelog of the next release.
