### ISSUE TITLE
Compilation error dependent on position of static[...] type parameter

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#5480]
The following 

```nimrod
  type
    Base[T] = ref object of RootObj
    Test[T, N: static[int]] = ref object of Base[T]
```

fails with

```
Error: cannot instantiate Base
got: (T)
but expected: (T)
```

However, it works when switching the position of `T` and `N`.

**Comment by bluenote10** [comment]
Stupid me: The problem is of course that by using a `,` the compiler expects `T` to be a `static[int]` as well. When using a semicolon the compiler interprets `T` independently and it works as well.

So I think we can close this, or at least tag it "low priority" + "error message", because it was mainly the message which confused me.

**Comment by narimiran** [comment]
> I think we can close this

Closing.
