### ISSUE TITLE
Codegen error - expected identifier before ')' token (probably regression)

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#5481]
Compiling this:
```
import reactor/async, reactor/loop

proc test2() {.async.} =
  var input: Input[byte]

  (await input.receiveAll(1)).echo
  (await input.receiveSome(1)).echo
```
gives
```
/home/michal/cctl/reactor/tests/nimcache/reactor_test_streams_close.c: In function ‘Marker_TY_GoZ8DkEzW9cd06f6x6d9b7HA’:
/home/michal/cctl/reactor/tests/nimcache/reactor_test_streams_close.c:1276:25: error: expected identifier before ‘)’ token
  switch ((*a).fut291869.) {
```

* It's quite challenging to reduce this example to not use reactor.nim, I'll try to do it later.
* I'd like to bisect, but 0.16.0 can't compile 0.15.2. Is there a good way to bisect that far in the past?

**Comment by Araq** [comment]
It's good enough, I have a fix for this already.

> I'd like to bisect, but 0.16.0 can't compile 0.15.2.

Why not?
