### ISSUE TITLE
`==` for OrderedTable should consider equal content but different size as equal.

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#5487]
Atm both the content and the size needs to be identical to consider both OrderedTables equal.
Should we maybe also consider identical content but different sizes as equal?

**Comment by Araq** [comment]
What does this mean? How can the content be the the same but the sizes not?

**Comment by enthus1ast** [comment]
if i create a table like this 
`[("wrong?","foo"), ("wrong?", "foo2")].newOrderedTable()`
or this
```
    var b = newOrderedTable[string, string]()
    b.add("wrong?", "foo")
    b.add("wrong?", "foo2")
```
looks identical first but it is not, cause internally it looks like this:

```
(gdb) p t0
$1 = {data = 0x2cc030, counter = 2, first = 25, last = 26}
(gdb) p s0
$2 = {data = 0x2cb030, counter = 2, first = 1, last = 2}
```
(as far as i understand the issue here)

**Comment by enthus1ast** [comment]
i think `==` should return true for both of them.
