### ISSUE TITLE
`clang.options.debug` ignored for `-d:debug` on Mac

### ISSUE THREAD

**Issue by cdunn2001** [nim-lang/Nim#5503]
In `Nim/config/nim.cfg`:

    clang.options.debug = "-g Q"
    clang.options.always = "-w QQ"
    clang.options.speed = "-O2 QQQ"
    clang.options.size = "-Os QQQQ"

I add/remove Qs to see what is actually passed to the compiler from where. `always` appears. And with `-d:release`, `speed` appears. But with `-d:debug`, I see `always`, but not `debug`.

My command-line: `nim -d:debug --verbosity:3 --out:main.exe c main.nim`, and my `main.nim.cfg` (the only other cfg processed):
```
hint[XDeclaredButNotUsed]=off
--threads:on
--threadAnalysis:off
-d:nimPinToCpu
```

Example compile-lines, release, and debug:

    clang -c  -w QQ -pthread -O2 QQQ  -I...

    clang -c  -w QQ -pthread  -I

Unfortunately, `--verbosity:3` does not show cfg processing. Could you point me to the lines of compiler code I should look at?

**Comment by cdunn2001** [comment]
Nim version: I am at the tip of `devel` as of last week.

**Comment by Araq** [comment]
``-d:debug`` doesn't affect C compiler options on any platform. You're looking for ``--debugger:native``.
