### ISSUE TITLE
Better macro error message

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5506]
```nim
import macros

proc helloWorld() =
  echo "Hallo World"
  
macro invoke(name: string): untyped =
  return newCall(name)

invoke("helloWorld")
```

Gives:

```
a6.nim(9, 8) Error: identifier expected, but found '"helloWorld"'
```

This error message could be improved.

**Comment by Yardanico** [comment]
The code which outputs this error is https://github.com/nim-lang/Nim/blob/devel/compiler/lookups.nim#L22, but I don't know what can be improved there.

**Comment by jxy** [comment]
I guess you could make ``newCall`` to error out if the kind of its first argument is not in ``{nnkIdent, nnkSym, nnkClosedSymChoice, nnkOpenSymChoice}``.  Anything else missing in that set?

**Comment by Araq** [comment]
> This error message could be improved.

How so? 

> Anything else missing in that set?

Sure, ``f()()`` is a thing.

**Comment by jxy** [comment]
There's no way for ``newCall`` to error out then.  Try

``` nim
import macros

proc helloWorld() =
  echo "Hallo World"
  
macro invoke(name: string): untyped =
  return newCall(name)

proc `()`(x: string) = echo x
invoke("helloWorld")
```

So you could improve the error message.  Something like

```
Cannot call
  "helloWorld"()
Undefined `()`(string).
```

or something similar.

**Comment by data-man** [comment]
Nim-devel now outputs

<pre><font color="#DC322F">Error: </font>in expression &apos;&quot;helloWorld&quot;()&apos;: identifier expected, but found &apos;&quot;helloWorld&quot;&apos;</pre>
