### ISSUE TITLE
[Feature Request] Add ability to resolve names of symbols at runtime

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#5516]
I've been looking at the `dynlib` module and it seems to call directly through to the `dlfcn.h` APIs for `dlopen`/`dlclose`/`dlsym`/`dladdr`. This works and is easy to use when implementing against a C basic API, but not when implementing against other libraries written in Nim. This is due to the custom name mangling that is implemented in the nim compiler. I am requesting that some of the functionality of the compiler be exposed through the `dynlib` module to allow us to resolve the names of nim procs declared in other libraries that we load.

I realize that this may require modification of the method of mangling symbol names as the current method seems to be only deterministic at compile-time, not run-time. I am not wholly familiar with the code enough to say one way or another how big of a change this would.

**Comment by Araq** [comment]
You're supposed to use ``exportc`` to override the name mangling.

**Comment by samdmarshall** [comment]
I see that as separate to the feature request I filed; as third party libraries cannot always be controlled in that regard.

**Comment by Araq** [comment]
You cannot export third part libraries in your DLL without wrapping them. "Third part libraries" can almost justify anything.

**Comment by samdmarshall** [comment]
I'm not sure if i follow, if i have access to `dladdr` and `dlsym` through the `dynlib` module, i shouldn't need to wrap anything. When interfacing with a C library this is no problem, but when interfacing with a nim library this becomes a problem because of the name mangling.

**Comment by Araq** [comment]
Actually C too has name mangling on Windows at least, depending on the calling convention. And for Nim code you're supposed to use ``exportc``. What else could we offer?
