### ISSUE TITLE
Module docs: 2 suggestions...

### ISSUE THREAD

**Issue by mark-summerfield** [nim-lang/Nim#5525]
(1) The title of each module in the docs should be written "module-name Module" not "Module module-name" since this puts the important information first.

(2) The Imports section's structure should be changed. For example if this were the threadpool module it should be:

# Imports
`import threadpool`
Dependencies:  `cpuinfo`, `cpuload`, `locks`

With the dependencies links as now of course.

**Comment by Araq** [comment]
(1) Or we remove the word "module" instead?
(2) I think the "Imports" word should be changed to "Dependencies" instead.

**Comment by mark-summerfield** [comment]
Yes I think both are the best things to do. I still suggest including `import *modname*` above the Dependencies if poss.
