### ISSUE TITLE
Doc query re public/private + suggestion re deprecated

### ISSUE THREAD

**Issue by mark-summerfield** [nim-lang/Nim#5529]
(1) Why is it that the unexported unicode RuneImpl appears in the docs (which I find surprising) and the unexported osproc ProcessObj does not appear in the docs (which is what I'd expect)?

(2) It is a bit annoying reading the docs only to discover the function you've just read about is deprecated. Why not gather all the deprecated stuff and put it at the end?

**Comment by Araq** [comment]
(1) looks like a serious docgen bug.
(2) we should simply remove more deprecated stuff IMO.

**Comment by mark-summerfield** [comment]
Given that Nim isn't yet 1.0 deleting deprecated sounds like a good idea. But post 1.0 it will have to be kept and then pushed to the end.

Also, quite often it seems to me, the order of functions could be improved a lot, e.g., always put the easiest or preferred method first, so in system, maybe open(filename should be before open(File; and in osproc, surely quoteShell should come before quoteShellWindows & quotShellPosix (and should say it is cross-platform)?
