### ISSUE TITLE
fmWrite doesn't truncate file with openAsync, unlike open()

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5531]
open and openAsync (from `asyncfile` module) treat fmWrite mode inconsistently:

`open("myfile", fmWrite)` - truncates file
`openAsync("myfile", fmWrite)` - does not truncate file

I think they should behave consistently in this regard and open's behaviour (truncation) is what I expected from the fmWrite mode.

**Comment by dom96** [comment]
I tried to reproduce this and couldn't. Maybe my test is wrong? I added it to the tester in any case. https://github.com/nim-lang/Nim/commit/4d931c62763fd68e3f6e874f977402f3ae5d144b

or maybe it's OS-specific, in which case my test will fail D:

Closing for now.

**Comment by mjoud** [comment]
Stumbled upon this issue. I can reproduce this locally on Linux. It also works on the playground (https://play.nim-lang.org/?gist=a79c30133a31c6652dbdac7853e6e17a).

**Comment by dom96** [comment]
So I made an attempt to fix this by using ``open`` on Unix. [But Windows is still an issue](https://ci.appveyor.com/project/dom96/nim/build/1100#L1445). Can anyone run the code that @mjoud posted on Windows to see what the behaviour of ``open`` on windows is?

**Comment by nc-x** [comment]
@dom96
```
Nim Compiler Version 0.17.3 [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 5e93eb9d7a839984c99789a4b9409b7a70f691f7
active boot switches: -d:release
```

The output of @mjoud 's code on Windows 10 is
```
open.txt: 0
openasync.txt: 8
```
