### ISSUE TITLE
nim compile caches built files incorrectly

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#5537]
Some compilers take arguments that consist of paths to files that will be consumed by the compiler/driver and used during the actual compile process. I came across and example of this when working on #5536 and using the flag `-fsanitize-blacklist`, which takes a file that gets parsed by the driver and then applies attributes to functions matched by name to be ignored by the address sanitizer tooling. When changes were made to this file, the `.c` files that were produced from my nim code were not rebuilt, nor were the resulting object files from the C code. So between compiles, unless i changed the `nim.cfg` file or completely wiped out the `nimcache/` directory, i wouldn't see any changes between builds because of reusing the old cached object files.

I'm not sure of what the proper solution is to this, since it would require directly integrating a compiler backend into the nim compiler and adopting the use of whatever functionality that backend provides instead of creating a pass-through to system specific compilers (like what currently exists). That seems like a non-feasible option, but i'm not sure how this can be solved cleanly otherwise.

**Comment by Araq** [comment]
I don't understand. the generated C code even contains the command used for the C compiler in a comment, so when the C code changes (or just the comment in the file), it's rebuilt.

(Btw use ``-f`` to enforce a full compile, no need to delete nimcache manually.)

**Comment by samdmarshall** [comment]
Sorry, I think i left out a bit of info there that was important. I have `foo.nim` that is being built to C, then assembled into an object file then linked. I am specifying an additional compiler flag via `passC` in the format of `-some-flag=file.txt`. The `file.txt` will get read by the compiler, and apply changes to the C code during compile-time. However, when i'm running `nimble build` or `nim compile` when changes are only made to the `file.txt` (not `foo.nim`) then I only see the existing object files get re-linked, not the object files getting produced by the compiler from the C files. I don't think that nim is correctly handling this case because it isn't aware that code has implicitly changed, even if the files it looks at have not.

**Comment by Araq** [comment]
So make it aware of the dependency. ``const dummyDep* = staticRead"file.txt"``

**Comment by samdmarshall** [comment]
I think this is the job of the nim compiler, not the end user since it is the one incurring the technical burden here by being a driver over the existing compiler driver being used (clang).

**Comment by Araq** [comment]
The Nim compiler is unaware of the semantics of what's passed via ``passC`` to the C compiler. You are already "burdened" with the ``passC`` and yet cannot add the dependency? Sorry, this makes no sense.

**Comment by samdmarshall** [comment]
OK, I think this behavior should be outlined as part of the passC flag documentation; with the two suggestions you gave (declaring a dependency through `staticRead` or by using the `-f` flag to force recompilation.

**Comment by Araq** [comment]
PRs are welcome to improve the docs...

**Comment by samdmarshall** [comment]
ok cool, I'll try to make one for this later today. 🙂
