### ISSUE TITLE
problems with == on NimSym

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5551]
As soon as I work on the NimSym value, `==` fails:

```Nim
import macros

static:
  let sym1   = genSym()
  let sym2   = genSym()
  let sym3   = sym1
  let nimsym = sym1.symbol
  echo sym1        == sym1        # true
  echo sym2        == sym3        # false
  echo sym3        == sym1        # true
  echo sym1.symbol == sym1.symbol # false  <--- !!!
  echo nimsym      == nimsym      # true
```

It is definitively not a showstopper, because when I have the symbol still wrapped in a NimNode, equality checks work as expected. It just that I can't really use the type NimSym, when I mean the type NimSym and not any arbitrary node.

**Comment by Araq** [comment]
Fixed.
