### ISSUE TITLE
Macro With typedesc[enum] Argument

### ISSUE THREAD

**Issue by gccwatcher** [nim-lang/Nim#5561]
Nim compiler version is 0.16.1-a20a8e6 is unable to handle **typedesc[enum]** argument inside macro, code sample below. If change `for i in T` to `for i in Color` it works as expected:

```
#
import macros

type Color = enum Red, Green, Blue

macro DISPATCH (T: typedesc[enum]): untyped =
    var s = ""
    #for i in Color:
    for i in T:
        s &= "echo \"color is \" $" & $i & "\L"
    result = parseStmt(s)

DISPATCH(Color)

#
# output is:
#
# macro_typedesc_enum.nim(9, 14) template/generic instantiation from here
# lib/system.nim(2071, 15) Error: invalid argument for 'low'
```

**Comment by Araq** [comment]
That's not how things work. There is no specialization for your macro so 'T' has indeed unknown type properties. Use ``getType`` to determine the enum's fields in the macro. Oh and building strings and passing them to ``parseStmt`` is unnecessarily complex. Work with the ASTs directly.

**Comment by gccwatcher** [comment]
Andreas, thank you very much for clarifications.
