### ISSUE TITLE
No bounds checking in JS target?

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5563]
Not sure if these are the same issue or not, but as far as I saw:

* The JS target doesn't check ``seq`` accesses to ensure that the ``seq`` has enough data.
* When the ``seq`` is ``nil`` there is also no error. In fact, I didn't even see an error in Firefox's JS console :\

**Comment by idlewan** [comment]
Also not checked when using dom objects.
For example:
```nim
import dom
var tags = document.getElementsByTagName("inexistent_tag");
if tags[0].classList.contains("something"):  # tags[0] should error
    ...
```
