### ISSUE TITLE
type mismatch: got (Socket) but expected 'Socket = ref SocketImpl'

### ISSUE THREAD

**Issue by Krognol** [nim-lang/Nim#5572]
I'm trying to assign a socket to an object with a Socket field.

The object in question looks like
```nim
type 
    Session* = ref object
        Connection*: Socket

# Assignment
var socket = newSocket()
session.Connection = socket
...
```

**Comment by cheatfate** [comment]
Your source is incomplete, so your error could not be reproduced...

**Comment by Krognol** [comment]
```nim
type
  Session* = ref object
    Connection*: Socket

method Connect*(s: Session) {.base.} =
  if s.Connection == nil:
    var socket = newSocket()
    s.Connection = socket # Error  occurs here
```

**Comment by Araq** [comment]
The crucial import list is still missing.

**Comment by Krognol** [comment]
It's present in the file, just forgot to include it in the code block.

**Comment by Krognol** [comment]
The problem seems to have been that the `net` package was being imported in another file that was imported in the Session file. Removing the import fixed it.
There should really be some better error message for that.
