### ISSUE TITLE
moveFile is broken on Linux

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5579]
It uses ``rename`` call from c standard library. ``man 2 rename`` says that we can use it only when file will be placed on the same filesystem.

I have two filesystems, one for ``/`` and another for ``/home``. And I can't move the file from ``/tmp`` to my home directory:

```
Traceback (most recent call last)
test.nim(4)              test
os.nim(632)              moveFile
os.nim(154)              raiseOSError
Error: unhandled exception: Invalid cross-device link
Additional info: Invalid cross-device link [OSError]
```

**Comment by cheatfate** [comment]
Its known semantic, as you mentioned, so its not broken, it uses `syscall` with limitations.

**Comment by vegansk** [comment]
``posix.rename`` is not broken. But ``os.moveFile`` is broken because it doesn't move files in certain conditions.
