### ISSUE TITLE
Unpleasant docs theme

### ISSUE THREAD

**Issue by Atlantic-Manta** [nim-lang/Nim#5584]
The theme of Nim's documentation is very unpleasant to ready on my laptop. The theme is light and the font is not bold but very thin. Here is what you should do, make the text **bold** and make the theme **dark** and make the highlights bold and bright. Just do something to make it easy to read. Thank you.

**Comment by kirbyfan64** [comment]
The font's pretty much normal thickness, and I don't think making everything bold would do much other than caused temporary blindness... Also, darkening the background color would just make it blend too easily with the text.

Maybe you mean you think the font colors should be a bit darker?

**Comment by AtlanticManta** [comment]
It looks well on my smartphone. But on my laptop, it looks bad.

**Comment by dom96** [comment]
> AtlanticManta

> Atlantic-Manta

![](https://media.giphy.com/media/Lq3ueCSWjnQPu/giphy.gif)
