### ISSUE TITLE
coroutines twait test fails on MacOS.

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#5586]
```
./twait
Traceback (most recent call last)
twait.nim(19)            twait
coro.nim(271)            run
coro.nim(183)            switchTo
coro.nim(223)            runCurrentTask
twait.nim(10)            testCoroutine1
coro.nim(205)            suspend
coro.nim(183)            switchTo
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
CC @rokups

**Comment by rokups** [comment]
Dont have the hardware. :|

**Comment by cheatfate** [comment]
I dont have hardware too, but VM can be used...

**Comment by rokups** [comment]
But that is illegal ;)

**Comment by cheatfate** [comment]
common, i have already tested it on FreeBSD and DragonFlyBSD and everything works fine, only stupid MacOS needs your attention.

**Comment by andreaferretti** [comment]
What is this twait test? Any chance to reproduce this?

**Comment by rokups** [comment]
It tests [proc wait()](https://github.com/nim-lang/Nim/blob/devel/lib/pure/coro.nim#L302) which waits until other coroutine finishes execution.

**Comment by cheatfate** [comment]
@andreaferretti, this is https://github.com/nim-lang/Nim/blob/devel/tests/coroutines/twait.nim test.
Currently this test disabled from Travis CI MacOS tests as you can see here
https://travis-ci.org/nim-lang/Nim/jobs/245079004#L3331.
But this test shows that current implementation of coroutines is unstable and cannot be used on MacOS.

**Comment by DylanModesitt** [comment]
This no longer appears to be an issue on macOs (for me at least - 10.15)

**Comment by timotheecour** [comment]
@DylanModesitt indeed; please send a PR to remove `disabled: "macosx"` from `tests/coroutines/twait.nim` 
(and maybe `disabled: "openbsd"`, idk)

**Comment by DylanModesitt** [comment]
@timotheecour do you want to close this? (the issue didn't get linked)
