### ISSUE TITLE
[RFC] newFileStream(string, FileMode) returns nil

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5588]
``newFileStream(string, FileMode)`` returns nil if it can't open file. Maybe this API should be coherent with ``system.open``?

**Comment by dom96** [comment]
``system.open`` returns a ``bool``. I think the current behaviour of ``newFileStream`` is consistent with that of ``open``. Thoughts?

**Comment by genotrance** [comment]
Many calls to open() raise an error - databases, json, memfiles, etc. Raising an exception seems to be the consistent method.

**Comment by Araq** [comment]
We need an ``openFileStream`` proc that raises an exception. The existing ``newFileStream`` needs to stay, too much code depends on it.

**Comment by twetzel59** [comment]
+1

**Comment by data-man** [comment]
Or to add one more parameter to newFileStream.

**Comment by twetzel59** [comment]
@data-man I like the simpicity and intuitiveness of you suggestion.

My concern is that the behavior will not be consistent, and this leads to less documented/understandable APIs...

Also, the default arg is a breaking change.
For example,
```nim
proc readImage(filename: string not nil): Image {.raises[ImageError].} =
  var stream = newFileStream()
  if not stream.isNil:
    #blah
  else:
    raise newException(ImageError, "failed")
```
After changing this, the above no longer will work as expected. With the ``raises`` pragma, it won't compile, either.

**Comment by twetzel59** [comment]
@Araq, should I try to implement this? This would be my first contribution, and it seems both easy and doable, while still being helpful.

If the RFC process still needs more discussion, that's fine too :)

**Comment by Araq** [comment]
@twetzel59 cool, go for it.

**Comment by twetzel59** [comment]
@Araq, I'm working on it now, and I was wondering about your opinion on this: will implementing the new proc deprecate the old ``newFileStream(string; FileMode; int)``?

**Comment by twetzel59** [comment]
I have implemented it. For now, I am going to not add the deprecated pragma, but I am going to update ``newFileStream`` docs to reflect the change.
