### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by qqquinta** [nim-lang/Nim#5590]
```nim
proc bar(pr: proc()) =
  pr()

proc foo*() =
  var b: int = 1

  bar proc() =
    if b > 1:
      b = 2: # There is a syntax error
    b = 3
```
>  Error:  type mismatch: got (proc (){.closure, noSideEffect, gcsafe, locks: 0.}, void)
> but expected one of: 
> proc bar(pr: proc ())

If I remove last line, the error message will be relevant.

```nim
proc bar(pr: proc()) =
  pr()

proc foo*() =
  var b: int = 1

  bar proc() =
    if b > 1:
      b = 2:  # Same syntax error
```
> Error: invalid indentation

**Comment by Araq** [comment]
But the compiler is allowed to perform type checking before syntax checking. The syntax error means the proc is finished and then it's type checked. 'nim check' would report both errors.

**Comment by narimiran** [comment]
> If I remove last line, the error message will be relevant.

With Nim devel 1.1.1, the error message is relevant even without removing the last line.
