### ISSUE TITLE
Index of null terminator in string is not out of bounds

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5592]
```nim
var s = ""
s[0] = 'a' # No exception
```

**Comment by yglukhov** [comment]
Currently there are some dependencies on this behavior in Nim std lib. So fixing this issue should probably start with getting rid of such dependencies. Lets decide whether we want to move in this direction. @Araq, @dom96.

**Comment by dom96** [comment]
It would be a bit weird if the following worked:

```nim
var s = ""
let foo = s[0]
```

but your example gave an exception. Unless you think that both should give an exception?

**Comment by yglukhov** [comment]
This sample doesn't give any exceptions with latest devel:
```nim
var s = ""
let foo = s[0] # No exception here
s[0] = 'a' # And no exception here
```
I think that both cases should raise index error.

**Comment by dom96** [comment]
Should this also raise an index error?

```nim
var s = "a"
let foo = s[1]
s[1] = 'a'
```

**Comment by yglukhov** [comment]
yup. index error should be raised when `i >= len`. now it is raised when `i > len`

**Comment by dom96** [comment]
Yeah, unfortunately a lot of code relies on this behaviour.

**Comment by yglukhov** [comment]
True, but still manageable.

**Comment by Araq** [comment]
This is not a bug, this is documented behaviour. If you want to change the behaviour, start a forum thread or RFC or something.
