### ISSUE TITLE
can't compile with var name "near" and --threads:on

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#5598]
on Windows following code can't be compiled with --threads:on
all tested compilers (gcc, vcc, bcc) report a syntax error
on linux this works

```nim
proc test(a, c: float; distance: var float) =
  var near = a - c
  distance = if (near < 0): a + c else: near


var
  a = 1.0
  c = 2.0
  d: float

test(a, c, d)
echo d    
  
```

**Comment by yglukhov** [comment]
Maybe it would be better to treat "near" as C keyword and mangle it accordingly?

**Comment by AdrianV** [comment]
"far" has the same problem - yes it would be good of the words were treated as C keywords
