### ISSUE TITLE
Dynamic dispatch is not working correctly

### ISSUE THREAD

**Issue by brechtm** [nim-lang/Nim#5599]
I would expect the following to output also "inner Derived", but it doesn't:

```nim
type
    Base = ref object of RootObj
    Derived = ref object of Base

method inner(obj: Base) {.base.} =
    quit "to override"

method outer(obj: Base) {.base.} =
    echo "outer"
    obj.inner()

method inner(obj: Derived) =
    echo "inner Derived"

var x: Derived
x.outer()
```

**Comment by Araq** [comment]
x is nil. It has no runtime type that can be used for dispatching. So ``nop`` is chosen. We can make it die wiht an exception instead but this code will never work.

**Comment by brechtm** [comment]
Aha. So this is indeed partially due to my ignorance. :-)
But raising an exception would be a good thing to do.
