### ISSUE TITLE
Regression after fixing ``typeRel``

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5615]
git bisect says that commit 568c954062c203383be0073126b2e7090721364f breaks this code:

```nim
type
  Obj5[T] = ref object of RootObj
    x_impl: T

proc newObj5[T](x: T): Obj5[T] =
  new(result)
  result.x_impl = x

proc x[T](v476205: Obj5[T]): T {.used.} =
  v476205.x_impl

type
  Obj6[T, U] = ref object of Obj5[T]
    y_impl: U

proc newObj6[T, U](x: T; y: U): Obj6[T, U] =
  new(result)
  result.x_impl = x
  result.y_impl = y

proc x[T, U](v477606: Obj6[T, U]): T {.used.} =
  v477606.x_impl

proc y[T, U](v477608: Obj6[T, U]): U {.used.} =
  v477608.y_impl

let e = newObj6(1, "a")
echo e.x
echo e.y
```

Error:
```
generr.nim(28, 6) template/generic instantiation from here
generr.nim(9, 8) Error: cannot instantiate: 'T'
```

**Comment by vegansk** [comment]
@jangko, please check your fix

**Comment by jangko** [comment]
interesting, I will take a look

**Comment by jangko** [comment]
If I change:

```Nim
let e = newObj6(1, "a")
echo e.x
echo e.y
```

to:
```Nim
let e = newObj6(1, "a")
echo e.x_impl
echo e.y_impl
```

the problem is gone, Although I must admit that the error message is really confusing.
probably this is another issue, or could you explain your code further? seems like they were macros/template expansion.

**Comment by vegansk** [comment]
@jangko, your workaround is unacceptible because it's the implementation of immutable fields for objects produced by this macro: http://vegansk.github.io/nimboost/docs/0.4.0/boost/typeutils.html#the-data-keyword

**Comment by jangko** [comment]
sorry, the numbers blurred my vision, now I understand what the problem is.

**Comment by vegansk** [comment]
But you are right, it's really produced by macro :-)

**Comment by jangko** [comment]
sorry for being careless when typing PR #5633 title, so this issue is not closed automatically. Now this issue can be closed. Thanks
