### ISSUE TITLE
math module: procs like SQRT() don't have generics, to handle types other than float

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#562]
To do sqrt of int values, rather than cast the ints to float, I did like in the  following code, but surely this should be in the math module??

import strutils, math

proc sqrt_(x: int): float {.importc: "sqrt", header: "<math.h>".}
proc sqrt_(x: int64): float {.importc: "sqrt", header: "<math.h>".}

var x1:int = 25
var x2:int64 = 25

echo(sqrt(x1))
echo(sqrt(x2))

**Comment by dom96** [comment]
I'm going to close this because I think that it's best to make this type of conversion explicit.

**Comment by kirbyfan64** [comment]
Why not just accept any integers? Doesn't Nim have type classes for this?

**Comment by dom96** [comment]
I suppose we could do that. There is a lot of procedures in the math module which only take floats, should we make all of them work with any number type?

**Comment by kirbyfan64** [comment]
@dom96 I would think so. I normally don't mind explicit conversions, but I feel this could get annoying very quickly.

**Comment by dom96** [comment]
It shall be done.

**Comment by genotrance** [comment]
```nim
proc sqrt*(x: SomeNumber): float64 {.importc: "sqrtf", header: "<math.h>".}
```

That one proc should cover all cases right?

**Comment by andreaferretti** [comment]
I think this should be closed - after all nim does not allow, say floating point division on integers without an explicit conversion. I don't see why `sqrt` and friends should be any different

**Comment by jlp765** [comment]
From a user perspective and a mathematics perspective, you don't think that `sqrt(1)` is invalid or any different to `sqrt(1.0)`.

I note that system has

``proc `/` (x, y: int): float {..}``

But it is mixing two input parameter types that forces type conversion.

**Comment by bluenote10** [comment]
> after all nim does not allow, say floating point division on integers without an explicit conversion

But it does via `lenientops`.

**Comment by Araq** [comment]
I don't see how

Error: ambiguous call; both math.sqrt(x: float32)[declared in lib/pure/math.nim(140, 7)] and math.sqrt(x: float64)[declared in lib/pure/math.nim(141, 7)] match for: (int literal(4))

could be resolved satisfactorily. Closing.

**Comment by genotrance** [comment]
```nim
proc sqrt(x: SomeNumber): float64 {.importc: "sqrtf", header: "math.h".}

echo sqrt(16)
echo sqrt(64.064)
echo sqrt(0x7FFFFFFFFFFFFFFF)
```

This works just fine, why is it not a satisfactory solution?

**Comment by andreaferretti** [comment]
Because you have decided to use float64 over float32, while other users may want a different precision
