### ISSUE TITLE
Segfault while trying to allocate

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#5636]
This happens when testing [rosencrantz](https://github.com/andreaferretti/rosencrantz) - which is just a thin wrapper over `asynchttpserver` under load. It also only seem to happen in release mode.

[This](https://github.com/andreaferretti/rosencrantz/issues/14) is the relevant bug.

Apparently some assertion in `rawAlloc` fails, but it is difficult to figure out what is going on exactly

**Comment by andreaferretti** [comment]
It seems that the error appears [at this line](https://github.com/nim-lang/Nim/blob/devel/lib/system/alloc.nim#L563)

```nim
c.freeList = c.freeList.next
```

**Comment by Araq** [comment]
It's a corruption that I've been hunting for quite some time now. It should disappear with ``--gc:markandSweep``  or ``--gc:boehm``. Can you confirm?

**Comment by andreaferretti** [comment]
I will try on monday

**Comment by andreaferretti** [comment]
It does not happen anymore - I think it was fixed by https://github.com/nim-lang/Nim/commit/c65ff403b27e1655504298ea65457cf1e00f4ebd

**Comment by andreaferretti** [comment]
Sorry, I was too eager to close this. It seems not to happen anymore when using `--stackTrace:on` and `--linetrace:on`, but it still happens when removing the linetrace option (which means I cannot pinpoint an exact place where the error happens anymore - still in `rawAlloc` but I do not have a line).

I confirm that both `--gc:markandSweep` or `--gc:boehm` make the error disappear

**Comment by Araq** [comment]
Is this still an issue with devel? GC stability is constantly improving.

**Comment by andreaferretti** [comment]
This seems to be working now! :-)

**Comment by Vindaar** [comment]
Just a heads up that I seem to have stumbled on the same / a similar bug while trying to make arc work with `ggplotnim` (at least in principle, meaning to get rid of `deepCopy` calls; `arraymancer` unfortunately is still blocked on that front anyways).

The related commit:
https://github.com/Vindaar/ggplotnim/pull/84/commits/0497d150ad4890f416f6785a3eb88e4a5fe129de

If I run (using the commented out `clone` code) one of the test cases, I end up with somewhat random errors in unrelated code to the changes. It's not always at the same place though. I stumbled on this issue, because it failed with the same
```
c.freeList = c.freeList.next
```
line half an hour ago. Now however:

```sh
Program received signal SIGSEGV, Segmentation fault.
prepareDealloc__fvhnFro5wEfzy879alizcUQ (cell=cell@entry=0x7ffff6d77490)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc_common.nim:417
417       if t.finalizer != nil:
(gdb) bt
#0  prepareDealloc__fvhnFro5wEfzy879alizcUQ (cell=cell@entry=0x7ffff6d77490)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc_common.nim:417
#1  0x00005555555796e4 in collectZCT__EN6T32AMm3va9bsrdxtF0cg (
    gch=gch@entry=0x555555832680 <gch__IcYaEuuWivYAS86vFMTS3Q>)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc.nim:728
#2  0x0000555555579916 in collectCTBody__XHio9cMpnLoH7GyCj1Z9besg_2 (
    gch=gch@entry=0x555555832680 <gch__IcYaEuuWivYAS86vFMTS3Q>)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc.nim:771
#3  0x0000555555579aae in collectCT__XHio9cMpnLoH7GyCj1Z9besg (
    gch=gch@entry=0x555555832680 <gch__IcYaEuuWivYAS86vFMTS3Q>)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc.nim:798
#4  0x0000555555579d5c in rawNewObj__ehkAaLROrd0Hc9aLROWt1nQ (typ=0x5555558476c0 <NTI__CGV9aEVh5CxW9bdmpIDWUXfA_>, 
    size=size@entry=64, gch=gch@entry=0x555555832680 <gch__IcYaEuuWivYAS86vFMTS3Q>)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc.nim:410
#5  0x000055555557a8e0 in newObj (typ=typ@entry=0x5555558476c0 <NTI__CGV9aEVh5CxW9bdmpIDWUXfA_>, size=size@entry=64)
    at /home/basti/src/nim/nim_git_repo/lib/system/gc.nim:439
#6  0x000055555570c3be in toDf__Rlq0KW9aqGoy8yumvgcjY3A (t=0x7fffffff5000)
    at /home/basti/CastData/ExternCode/ggplotnim/src/ggplotnim/dataframe/arraymancer_backend.nim:345
#7  0x00005555557e807e in NimMainModule () at /home/basti/CastData/ExternCode/ggplotnim/tests/testDf.nim:906
#8  0x00005555557f1df6 in NimMainInner () at /home/basti/src/nim/nim_git_repo/lib/pure/unittest.nim:254
#9  0x000055555578939c in NimMain () at /home/basti/src/nim/nim_git_repo/lib/pure/unittest.nim:262
#10 0x00005555557893cf in main (argc=<optimized out>, args=<optimized out>, env=<optimized out>)
    at /home/basti/src/nim/nim_git_repo/lib/pure/unittest.nim:269
```

The line 345 in arraymancer_backend points to a pairs iterator for an `OrderedTable[string, seq[string]]`.

I'll probably open a full issue, but I have no idea how to create a reproducible example from this. The error doesn't happen with boehm or markAndSweep though.
