### ISSUE TITLE
Internal assert when using ``compiles``

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5638]
```nim
type X = object
  a_impl: int

proc a(x: X): int =
  x.a_impl

var x: X
assert compiles((block:
  x.a = 1
))
```

fails to compile due to internal assert in semcall.nim:254. Git hash 7e351fc

**Comment by Araq** [comment]
I'm reverting this patch.

**Comment by vegansk** [comment]
@Araq, can you show the code that is broken by this patch?

**Comment by Araq** [comment]
Sorry, no, we have no small snipped to reproduce it and it's closed source.
