### ISSUE TITLE
readline(TFile, var string) segfaults if second argument is nil

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#564]
When the string parameter to readline is not initialized, the procedure segfaults. This occurs because it tries to reuse an existing string, but does not check if it has actually been initialized.

```nimrod
var f: TFile

discard open(f, "example.txt", fmRead)
while true:
  var line: string
  if not readLine(f, line):
    break
  echo line
close(f)
```

**Comment by dom96** [comment]
Postponed until ``not nil`` is ready.

**Comment by AbstractLife** [comment]
:smiley:
