### ISSUE TITLE
-d:debugHeapLinks no longer works

### ISSUE THREAD

**Issue by bpr** [nim-lang/Nim#5657]
19:07 $ nim c -d:debugHeapLinks any_file.nim
Hint: used config file '/Users/bpr/Applications/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
lib/system/alloc.nim(343, 21) Error: undeclared field: 'heapLink'

**Comment by Araq** [comment]
Am I missing something? Was this ever documented anywhere?

**Comment by bpr** [comment]
You're probably right, I didn't even look! I was just trying out the changes to @cdunn2001's thread problem from the forum and it stopped compiling because of this. If it's an undocumented feature I'll close this.
