### ISSUE TITLE
min/max vararg behavior is broken

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5669]
Intentionally by this commit: 9aeccda2629ae0828fbcd4fd8aa50b3abc7e95b3
Is there any reason for this?
This code no longer compiles:
```nim
discard max(1'u32, 2'u32)
```

**Comment by Araq** [comment]
Thanks to the varargs behaviour even something like ``mybool.max`` used to compile.

**Comment by yglukhov** [comment]
#5734 somewhat addresses the problem, so I'm closing this one.
