### ISSUE TITLE
Please add GOTO to Nim

### ISSUE THREAD

**Issue by vasili111** [nim-lang/Nim#5670]
While code generation from diagrams is possible without using GOTO, it is much easier when you have GOTO. For example, [DRAKON Editor](https://github.com/stepan-mitkin/drakon_editor) can generate code from DRAKON diagrams and with GOTO it is much easier to do make support for the code generation. Also, GOTO is very powerful command and sometimes is helpful in conventional programming. Please add GOTO to Nim.

**Comment by Araq** [comment]
Not gonna happen. Makes several analysis passes harder to implement, and can be worked around easily with a state machine.

**Comment by kirbyfan64** [comment]
In most cases like that, you can just do something like:

```nim
type State {.pure.} = enum
  A, B, C, D

var st = State.A

while true:
  case st
  of State.A:
    foo
    bar
    st = State.B
  of State.B:
    break
  # ...
```

**Comment by dom96** [comment]
Feel free to continue the discussion. But seeing as this feature won't be implemented I will close this issue.
