### ISSUE TITLE
Document my first month of contributions under our BountySource campaign

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#5672]
The highlight of my work this month was the merging of the concepts branch. The support for parametric concepts is now greatly improved and more than 10 outstanding issues were closed. The merge didn't come without problems - the early adopters were quick to report several regressions, which I'll be fixing in the coming days, before focusing on implementing the rest of the [spec](https://github.com/nim-lang/Nim/blob/devel/doc/manual/generics.txt#L201) in the upcoming month.

Besides the work on the concepts branch, I also submitted pull requests for a number of unrelated issues:

* Support for forward declarations of generic procs
https://github.com/nim-lang/Nim/issues/4104, https://github.com/nim-lang/Nim/issues/4908

* Templates can now implement perfect forwarding with varargs
https://github.com/nim-lang/Nim/issues/5455

* Comprehensive set of diagnostics for incorrect object construction:
https://github.com/nim-lang/Nim/pull/5564

* Other miscellaneous issues:
https://github.com/nim-lang/Nim/issues/5296, https://github.com/nim-lang/Nim/issues/4756, https://github.com/nim-lang/Nim/issues/5167, https://github.com/nim-lang/Nim/issues/5428

I'd like to thank the community for the great support and the shareholders at my companies ([Flapit](https://www.flapit.com) & [Adpow](https://www.adpow.com)) for letting me reduce my work week and dedicate an entire day for Nim.

**Comment by andreaferretti** [comment]
Wow, the spec has grown very complex! I hope I will be able to sort out what I need in simple cases :-)

By the way, the last paragraph allows to use concepts to generate some interface type like in https://networkos.net/nim/collections.nim/doc/api/collections/iface.html or did I misunderstand the whole thing?

**Comment by zah** [comment]
Yes, you understood correctly. The so called "VTable Types" are similar to the interface classes in a traditional OOP language. They can be used to reduce code bloat or when you need to create a polymorphic collection of objects. Otherwise, the recommendation is still to try to author most of your code to use generic procs, accepting value types as all other possible argument types (such as ref, ptr, vtref, etc) are compatible with such an interface.

**Comment by dom96** [comment]
Brilliant job @zah :)

I have posted $1500 for the 5 Fridays that you have worked during the month of March. You should be able to claim it via [this link](https://www.bountysource.com/issues/43879517-document-my-first-month-of-contributions-under-our-bountysource-campaign).

**Comment by zah** [comment]
Apparently, I must close the issue to claim the bounty :)
