### ISSUE TITLE
specialized generic proc dotcall mismatch

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#5673]
don't know if this is a bug or not, but if the regular proc call syntax works, then dotcall syntax should works too.

```Nim
type
  BMP* = ref object
    
  BMPResult*[T] = object
    data*: T
    
proc convert*[T](bmp: BMP, bitsPerPixel: int): BMPResult[T] =
  discard
  
var bmp: BMP
var res = bmp.convert[string](8)   # this one failed to compile
#var res = convert[string](bmp, 8) # this one compiles
```

the error message
```text
bug.nim(11, 14) Error: type mismatch: got (BMP)
but expected one of:
proc convert[T](bmp: BMP; bitsPerPixel: int): BMPResult[T]
```

**Comment by Araq** [comment]
> don't know if this is a bug or not, but if the regular proc call syntax works, then dotcall syntax should works too.

Not at all, ``x.y[z]``  is parsed as ``(x.y)[z]`` (correct interpretation for array access) and not as ``x.(y[z])`` (the required interpretation for generics). It's not a compiler bug, it's maybe a problem with the spec, but I'm sure there is an RFC open for this already, hence closing this one.
