### ISSUE TITLE
setLen() crash

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#5675]
```nim
var s = newString(10)

s[0] = '0'
s[1] = '1'
s[2] = '2'
s[3] = '3'
s[4] = '4'
s[5] = '5'
s[6] = '6'
s[7] = '7'
s[8] = '8'
s[9] = '9'
s[10] = 'x'

s.setLen(5)
echo s
s.setLen(2)
echo s
s.setLen(2)
echo s
s[2] = '2'
s.setLen(3)
echo s
s[6] = '6'
```
```
Nim Compiler Version 0.16.1 (2017-04-01) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 7e351fc7fa96b4d560c5a51118bab22abb590585
active boot switches: -d:release

$ nim c t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/stefan/NEdx/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t [Processing]
Hint:  [Link]
Hint: operation successful (10837 lines compiled; 0.111 sec total; 17.938MiB peakmem; Debug Build) [SuccessX]
stefan@nuc ~/NEdx $ ./t
01234
01
01
012
Traceback (most recent call last)
t.nim(23)                t
system.nim(2637)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

The last line makes it crash.

**Comment by trustable-code** [comment]
You try to access character 6 of a string with a length of 3 characters. To me the "index out of bounds" exception looks correct.

**Comment by dom96** [comment]
Yep, this behaviour is correct.

@StefanSalewski what do you think should happen in this case?

**Comment by StefanSalewski** [comment]
For me that behaviour was totally unexpected -- I thought I had a string of length 10, so access to index position 0 to 9 would be allowed all the time.

From above example, it seems that access to the terminating 0x byte is even allowed?
```
s.setLen(2)
echo s
s[2] = '2'
s.setLen(3)
```

I used such a string as a buffer, filling it char by char and using setLen() each time when done. For a few times it worked, but after some iterations I got the crash, because I accessed a position greater than allowed by setLen(). Fix is to do setLen(MaxInitialLenght) each time at the beginning of the loop. Because that was very unexpected for me (and it was used surrounded by other complicated code), it took me more than one hour to find :-)

I think at least we should include a hint to that fact in the docs, maybe in setLen() documentation. When using a string as a buffer as I did, we now need two calls to setLen() for each loop iteration, because we do not know the actual length in advance.

**Comment by dom96** [comment]
Why don't you just append to the string using `add`?

**Comment by StefanSalewski** [comment]
It is a performance critical operation, and add() is 3 to 4 times slower than filling the string with []. (Well,the 3 to 4 times was measured by myself in early Nim days and it was confirmed by Araq at that time.)

**Comment by dom96** [comment]
If you're changing the size of the string every time you add a character then you're recreating what `add` does! Probably an even slower version of ``add``.

**Comment by Araq** [comment]
We can speed up ``add`` but there is no bug here, you seem to have confused "capacity" with "length". Can happen to the best of us.
