### ISSUE TITLE
ImportC pragma for enum members

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#5676]
The Nim coding style guide suggests that enum member identifiers should be in camelCase. In C it is more usual to PascalCase or to CAPITALIZE identifiers of enum members, or more often than not, the values are defined instead of declaring them in an enum.

However, when importing C headers to Nim, it often makes sense to pack multiple defines together as a Nim enum type with members that have values to indicate that the constants are related. For these situations it would be nice if the nim enum could have nim-like identifiers, but import them from the appropiate C symbol name if needed, just as we already can with object attributes, procs and vars.

Like this:
``` nim
type MyEnum = enum
  myMember {.importc: "MY_MEMBER".}
```

The example above should be able to import both of the following C declarations:
``` c
typedef enum {
  MY_MEMBER = 42
} MyEnum;
```
and
``` c
#define MY_MEMBER 42
```

I realize that in these cases the actual value of the `myMember` member would not be known to Nim and that might be an issue. 

*In case of the first C example, we would obviously also annotate the `MyEnum` nim type declaration with the `importc` pragma.*

**Comment by Araq** [comment]
The codegen doesn't use C enum names at all though, it uses the integer literals directly.

**Comment by couven92** [comment]
Hmm... makes sense... Then this is probably not much of an issue at all... Unless we ever do the voodoo magic to do importC for const symbols. And there are strong arguments against ever doing that.

We can close this one then :)
