### ISSUE TITLE
Two tester improvements

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5681]
- [x] Don't ignore test files that have no "header" (a comment specifying their filename). It's too easy to miss tests that way.
- [x] Show _how_ the test passed in the output (whether the test was only compiled or compiled and executed). It's too easy to miss the fact that an "output" spec is needed for the tester to run the test.

**Comment by bluenote10** [comment]
Related discussion: https://github.com/nim-lang/Nim/issues/5472
