### ISSUE TITLE
https://nim-lang.org/docs/ points to a broken page

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#5686]
I'd expect it to give an index of available documentation, like https://nim-lang.org/documentation.html does (yeah, it's not linked from anywhere, but it's convenient to just cut off a part of the url from a random docs link)

Instead, the main page is shown, but without images/css

**Comment by Araq** [comment]
@dom96 Can you make this work?

**Comment by dom96** [comment]
These website files should not be in the ``docs`` directory. Is ``nimweb`` still putting them there or are they just stale ones?

**Comment by dom96** [comment]
I added a redirect: https://nim-lang.org/docs/ -> https://nim-lang.org/documentation.html

**Comment by arnetheduck** [comment]
lgtm

**Comment by Araq** [comment]
> These website files should not be in the docs directory. Is nimweb still putting them there or are they just stale ones?

Of course they should be. It always contains docs for the latest stable release so that I don't have to update stuff all the time on a new release.

**Comment by dom96** [comment]
What? Perhaps you misunderstood me. The ``docs`` directory should only contain the docs, not the nim-lang.org index.html page (nor any of the other pages).

**Comment by Araq** [comment]
Ah yeah, misunderstanding, we can remove index.html et al.
