### ISSUE TITLE
toSeq(1..n) is slow because Slice[T] does not have len defined

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#5703]
toSeq in sequtils relies on the presence of len proc for a type to preallocate the sequence.
len* is not defined in system.nim for Slice[T]. I don't mind preparing a pull request if approach will be agreed.

```

template toSeq*(iter: untyped): untyped=
  when compiles(iter.len):  
     ## fast
  else:
    ## slow

```
I suggest adding to system.nim:
```
 proc len*[T](x: Slice[T]): int = 
   result = b - a + 1
```

**Comment by Araq** [comment]
``toSeq(1..n)`` only comes up for toy examples though. Production code uses ``Slice[int]`` directly and saves the seq with known contents.

**Comment by cooldome** [comment]
closed on PR 5847
