### ISSUE TITLE
Incorrect time interval calculation

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#5704]
parse("19700101-000000", "yyyyMMdd-hhmmss").toTime - parse("19000101-000000", "yyyyMMdd-hhmmss").toTime  returns 2208983679

Should be 2208988800 according to RFC 868

**Comment by andreaferretti** [comment]
It returns `2208988800` for me, both on devel and on play.nim-lang.org

**Comment by FedericoCeratto** [comment]
Nim 0.17.0 running on Linux. Same with 0.16.0. The output of the two toTime run independently are:
1970-01-01T00:00:00+00:00
1900-01-01T00:00:00+00:00

**Comment by andreaferretti** [comment]
Weird. I am using Ubuntu 16.04 and I get the correct results with either devel or 0.17. Anything else particular regarding your configuration?

**Comment by FedericoCeratto** [comment]
It can be reproduced by changing timezone `sudo dpkg-reconfigure tzdata` or symlinking ` /etc/localtime`
E.g. 
```
$ sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime && ./mytest                                       
2208988800
$ sudo ln -fs /usr/share/zoneinfo/ROK /etc/localtime && ./mytest
2208986872
```

**Comment by GULPF** [comment]
I don't think 2208988800 is the correct result. With `TZ=Asia/Seoul` the first date is interpreted as `1970-01-01T00:00:00+09:00:00` and the second one as `1900-01-01T00:00:00+08:27:52`. So `Asia/Seoul` changed its utc offset somewhere between the dates. This affects the time diff between the dates (`2208983679` is still wrong though).

**Comment by GULPF** [comment]
This is fixed by #6552 (but note my previous comment on why both `2208983679` and `2208988800` was incorrect).

**Comment by andreaferretti** [comment]
Can I close?

**Comment by GULPF** [comment]
This can be closed.
