### ISSUE TITLE
Minor array initialiser enhancement

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#5705]
In C, you can do either of the following:

```
float a1[3] = {1.0, 2.0, 3.0};
float a2[] = {1.0, 2.0, 3.0};
```

But in Nim you must always specify the size of the array:

```
var a1: array[3, float32] = [1.0, 2.0, 3.0]
```

It would be nice to have the option to let the compiler figure out the size, just like in C:

```
var a2: array[float32] = [1.0, 2.0, 3.0]
```

Obviously, you can leave out the type and then the compiler will figure out the size, but then you need to specify the type of the first element in some other way:

```
var a1 = [1.0, 2.0, 3.0]       # array of float64s on the 64-bit compiler
var a2 = [1.0'f32, 2.0, 3.0]   # workaround, var a2: array[float32] =... would be nicer
```

Concrete example why this is slightly bothering me (I'd like to use the first form, but I have to use the second):

```
var a1: array[GLfloat] = [
  1.0, -2.0,  3.0
 -4.0,  5.0, -6.0
  7.0, -8.0,  9.0
]

var a2 = [
 GLfloat(1.0), -2.0,  3.0
        -4.0,   5.0, -6.0
         7.0,  -8.0,  9.0
]
```

**Comment by Araq** [comment]
> Obviously, you can leave out the type and then the compiler will figure out the size, but then you need to specify the type of the first element in some other way.

But that's the way I like it and it doesn't need an alternative to accomplish the same.
