### ISSUE TITLE
Impossible to capture in closure the argument of type openarray

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#5709]
The following code fails with "Error: illegal capture 's'"

```
proc filter(s: openarray[bool]) : auto =
  iterator it : int {.closure.} =
    for i in 0..<len(s):
      if s[i]: yield i
  return it

```

**Comment by Araq** [comment]
That's not a bug. An openarray is a (pointer, length) pair, the pointer usually points to stack memory, you cannot capture it. You can capture an explicit copy instead so that it can reside on the heap.
