### ISSUE TITLE
asyncdispatch.newDispatcher() -- Why?

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/Nim#5717]
If asyncdispatch functions accepted a `PDispatcher` parameter, then `newDispatcher()` would have some value.

As it is, when I `fork()` a process, I have to be very, very careful that I have not yet registered wrong ends of pipes with the *global* dispatcher.

**Comment by dom96** [comment]
Yeah, there should probably be a way to set the global dispatcher, that would be an easy solution.

**Comment by TiberiumN** [comment]
@dom96 with #5782 merged there is setGlobalDispatcher() now
