### ISSUE TITLE
Regression: generic function type cause internal errors

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#5723]
```
type
  FutureCallback[T] = (proc(future: Completer[T]))

  Completer[T] = object
    discard
```

crashes compiler from devel branch. git bisect returns commits between 77a4512ae8 and c605d5757

**Comment by zah** [comment]
I have fixed this [here](https://github.com/nim-lang/Nim/pull/5677), so I'm going to close this issue.
