### ISSUE TITLE
distros.nim -  detectOs() not detecting

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#5736]
detectOs(OpenSUSE)  returns false on a current openSuse Tumbleweed system because
it only looks at uname and not at uname and release, so I suggest that

line 160 which currently looks like so:

```nim
 of Distribution.OpenSUSE:
    result = "suse" in toLowerAscii(uname())
```

be changed to:

```nim
 of Distribution.OpenSUSE:
    result = "suse" in toLowerAscii(uname()) or "suse" in toLowerAscii(release())
```

which gives the expected result of true.

Maybe someone else can help to verify this issue on other systems too 
to see if this change would provide better and correct Os detection.

**Comment by dom96** [comment]
When writing issues that have a suggested code change you may as well create a PR, please do that.

**Comment by konqoro** [comment]
Manjaro doesn't work either.

**Comment by konqoro** [comment]
No sorry, wrong issue. I will open an other for `foreignDepInstallCmd`
