### ISSUE TITLE
async + threads:on + globals = error

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5738]
```nim
import asyncdispatch
var s = "hi"
proc foo() {.async.} = echo s
```
```
nim c --threads:on test.nim
```
```
test.nim(3, 12) template/generic instantiation from here
Projects/nim/lib/pure/asyncmacro.nim(31, 8) Error: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory
```
Originated from https://github.com/dom96/jester/issues/110

**Comment by zielmicha** [comment]
I had very similar problem with reactor.nim, looks like thread analysis inside iterators is broken.

**Comment by Araq** [comment]
That works as expected. You cannot use global GC'ed memory with ``--threads:on``.

**Comment by zielmicha** [comment]
Shouldn't this only apply to gcsafe procs?
> We call a proc p GC safe when it doesn't access any global variable that contains GC'ed memory (string, seq,  ref or a closure) either directly or indirectly through a call to a GC unsafe proc.

**Comment by yglukhov** [comment]
@Araq, are you saying that the following code should not compile with `--threads:on`?
```nim
var s = "hi"
proc foo() = echo s
```
Because now it compiles just fine ;)

**Comment by Araq** [comment]
No, I'm saying what the manual says and you ignore what the ``.async`` transformation does.

**Comment by yglukhov** [comment]
Well I know that `async` puts `gcsafe` everywhere. But what's the reason for that? As far as I understand `async` procs are perfectly safe to use globals in a single thread.

**Comment by andreaferretti** [comment]
@dom96 Do you have an idea why `gcsafe` is used in `async`?

**Comment by yglukhov** [comment]
Future defines it's callback as `gcsafe`, because one might want to make a `gcsafe` async proc. So every callback we store in the future should be `gcsafe`. I wonder if we can somehow allow both `gcsafe` and `gcunsafe` code in futures...
