### ISSUE TITLE
setFilePos and getFilePos do not support files larger than 2GB on Windows

### ISSUE THREAD

**Issue by cpterry** [nim-lang/Nim#5765]
In sysio.nim the C functions fseek and ftell are used, which take or return long int offsets. On 64 bit Windows long ints are 32 bit, causing issues for files larger than 2GB. I think this can be fixed by changing fseek and ftell to fseeko and ftello and or _fseeki64 and _ftelli64 depending on the compiler.

**Comment by trustable-code** [comment]
Confirmed.
How exactly can we solve it?

**Comment by Araq** [comment]
I don't know, but anything that has not been tested with Visual C++ will not be accepted.

**Comment by simonkrauter** [comment]
I think this issue is fixed and can be closed.

``setFilePos`` uses now ``_fseeki64`` under 64 bit Windows.

https://github.com/nim-lang/Nim/blob/version-1-2/lib/system/io.nim#L101

```nim
when defined(windows):
  when not defined(amd64):
    proc c_fseek(f: File, offset: int64, whence: cint): cint {.
      importc: "fseek", header: "<stdio.h>", tags: [].}
    proc c_ftell(f: File): int64 {.
      importc: "ftell", header: "<stdio.h>", tags: [].}
  else:
    proc c_fseek(f: File, offset: int64, whence: cint): cint {.
      importc: "_fseeki64", header: "<stdio.h>", tags: [].}
    proc c_ftell(f: File): int64 {.
      importc: "_ftelli64", header: "<stdio.h>", tags: [].}
else:
  proc c_fseek(f: File, offset: int64, whence: cint): cint {.
    importc: "fseeko", header: "<stdio.h>", tags: [].}
  proc c_ftell(f: File): int64 {.
    importc: "ftello", header: "<stdio.h>", tags: [].}
```
