### ISSUE TITLE
Nim Info manual

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#5766]
Hello,

Is there a plan to generate an Info (GNU TexInfo format) manual for Nim so that the whole of https://nim-lang.org/documentation.html is available for offline consumption too?

Here's one usage of that:

- For emacs users, the Info manual can be kept open in one window.  Reference code from that window can then be easily copied over to the practice nim code buffer window.

Or can someone with reStructuredText and Texinfo knowledge show me how I can best do that convesion locally?

*[Googling][3] shows me [few][1] [options][2], but I don't know which is the best one.*

---

I tried

```
pandoc docs.rst -o docs.texi
```

But it looks like `docs.rst` is pointing to html files instead of other sub-.rst files. I am looking for a solution that generates an Info manual with the whole hierarchy and references intact.

[3]: https://www.google.com/search?q=convert+restructuredtext+to+texinfo
[1]: http://docutils.sourceforge.net/sandbox/texinfo-writer/README.html
[2]: http://pandoc.org/demos.html

**Comment by Araq** [comment]
Use ``koch web`` to build the HTML docs on your local machine.
