### ISSUE TITLE
Automatic configuration of path

### ISSUE THREAD

**Issue by Immortalin** [nim-lang/Nim#5767]
Rust configures PATH automatically when installing. Why not do this too for nim?

**Comment by Araq** [comment]
But we do that. Run ``finish.exe``.

**Comment by Immortalin** [comment]
@Araq where can I find this on the linux build?

**Comment by Araq** [comment]
On Linux you're supposed to know how to edit ``.bashrc``. ;-)

**Comment by Immortalin** [comment]
@Araq it creates unnecessary friction, poor UX.

**Comment by Araq** [comment]
So what do you suggest? We write some stuff into your ``bashrc`` and pray for the best?

**Comment by Immortalin** [comment]
@Araq it seems to work for Rust...

**Comment by Araq** [comment]
Yes, so tell me how Rust does it.

**Comment by yglukhov** [comment]
Maybe rust is just installed to `/usr/local/bin`?
