### ISSUE TITLE
fastRows / rows command after Exec command is getting Out Of Sync error.

### ISSUE THREAD

**Issue by Bennyelg** [nim-lang/Nim#5771]
Hey,
I'm  execute Create statement using the `exec` proc from `db_mysql`
after the table is created, I tried to fetch for some table data using rows/fastRows proc but I get the annoying error Command Out of Sync. 

I tested both procs individually and they work just fine. but exec follow by rows/fastRows proc is failing.
any idea why?

**Comment by Araq** [comment]
No idea, maybe this is of help: https://dev.mysql.com/doc/refman/5.7/en/commands-out-of-sync.html

**Comment by Bennyelg** [comment]
What is the equivalent of mysql_free_result() inside db_mysql which I cannot find somehow.

**Comment by Araq** [comment]
Why did you close it? What's the solution?
