### ISSUE TITLE
Regression with SSL on Windows 

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#5775]
```
httpclient.nim(1245)     downloadFile
httpclient.nim(1176)     get
httpclient.nim(1168)     request
httpclient.nim(1151)     request
httpclient.nim(1145)     request
httpclient.nim(1111)     requestAux
httpclient.nim(1066)     newConnection
Error: unhandled exception: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:
lsv1 alert internal error [SslError]
```

After PR #5763 I get the above error when trying to download https://nim-lang.org/download/nim-0.16.0.tar.gz

**Comment by TiberiumN** [comment]
Maybe this is not a Nim regression?
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137
https://askubuntu.com/questions/649000/openssl-curl-error-ssl23-get-server-hellotlsv1-alert-internal-error
http://stackoverflow.com/questions/30538542/tlsv1-alert-internal-error-during-handshake
https://github.com/FreeRDP/FreeRDP/issues/681

**Comment by dom96** [comment]
It might be both, but it does work when I revert the PR.

**Comment by Araq** [comment]
Indeed, can reproduce here.
