### ISSUE TITLE
 Linenoise returned nil [IOError]

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#5795]
```nim
import terminal,rdstdin

proc exitHandler() {.noconv.} =
    echo("Have a nice day")
    addQuitProc(resetAttributes)
    quit(0)
   
setControlCHook(exitHandler)  

var z = readLineFromStdin("Write something or press Ctrl-C to exit : ")
echo z
 
```

pressing Ctrl-C throws error rather than expected output of exitHandler

```nim
 rdstdin.nim(109)         readLineFromStdin
 Error: unhandled exception: Linenoise returned nil [IOError]
```

**Comment by krux02** [comment]
I already fixed the problem. Someone else must have undone it:
https://github.com/nim-lang/Nim/pull/5351

**Comment by krux02** [comment]
aparently this is a won't fix. Sorry to tell you that. You can close it now.

**Comment by Araq** [comment]
No, *you* don't want to fix it. I will.

**Comment by timotheecour** [comment]
linenoise puts the terminal in raw mode so ctrl C can't trigger a signal handler directly however https://github.com/nim-lang/Nim/pull/16977 can close this by reporting a status indicating whether for eg ctrl C or ctrl D was used to return to caller of linenoise, which user can then use to call `exitHandler` if they choose
