### ISSUE TITLE
hint pragma applied only on a single symbol

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#5810]
When I apply a hint pragma on a variable, proc, type, etc. I'd expect the pragma to only affect that particular symbol.

``` nim
var
  x {.hint[XDeclaredButNotUsed]: off.} = 42
  y = 24
```

generates not hints, warnings or errors. But actually the compiler should omit the hint for `x`, but again generate the hint for `y`.

If a hint pragma is specified as a statement all on its own, the current behaviour is as expected.

**Comment by Araq** [comment]
Use ``.used`` instead. ;-)

**Comment by couven92** [comment]
@Araq 
``` nim
var x {.used.} = 42
```

gives the following error message:
> invalid pragma: used

**Comment by couven92** [comment]
Works in 0.17
