### ISSUE TITLE
float32 literals are translated to double literals in C

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5821]
this function fails
``` Nim
proc main(): void =
  let y: float32 = 47.11'f32
  doAssert y == 47.11'f32
```

here is the generated C code:
``` C
N_NIMCALL(void, main_UXECz2j6inWSkSqQMQDhsA)(void) {
	NF32 y;
	y = 4.7109999999999999e+01;
	{
		if (!!((y == 4.7109999999999999e+01))) goto LA3_;  // <------ here is the problem		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_X9bGGOoNyKehOTF7f2xys3g_2));
	}
	LA3_: ;
}
```

The generated literal is not a 32 bit ``float`` literal like the Nim literal, it does not have the ``f`` suffix that is required for the C float literal, therefore. It is of type double and therefore there will be an implicit conversion to double of y. That is wrong.

I got this bug from this forum entry:
https://forum.nim-lang.org/t/2956

This bug is easy to fix, because simply putting the right suffix for the floating point literal already fixes the problem, as you can see in the example program here:
```C
#include <stdio.h>

int main() {
	float y;
	y = 4.7109999999999999e+01;
  if (y == 4.7109999999999999e+01f) {
    printf("true\n");
  } else {
    printf("false\n");
  }
  if (y == 4.7109999999999999e+01) {
    printf("true\n");
  } else {
    printf("false\n");
  }
}
```
output:
```
true
false
```

**Comment by cdunn2001** [comment]
@dom96, Does that work for you? When I run your new test with your change, I still see the problem. But your test-case is good. If I alter the nimcache `.c` to append `f` as described by @krux02, the test passes.

**Comment by cdunn2001** [comment]
I also tried your fix

    ((float) 47.11)

Yes, that works. But that's not what your change is generating (on my Mac):
```c
 71   a = 4.7109999999999999e+01;
 72   nimln_(7, "tissue5821.nim");
 73   {
 74     if (!!((a == (4.7109999999999999e+01))) goto LA3_;
 75       raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_8gxvsyO39bHQk    gvdRj0Cegg_2));
 76   }
```

**Comment by dom96** [comment]
Yes, it works for me. Did you bootstrap the compiler?

**Comment by cdunn2001** [comment]
After 1ad15419434a43132393e50fe0ab9ffdbdf0171a, it does work. Thanks!
