### ISSUE TITLE
Nim beginner's feedback: "echo([1, 2, 3])" does not work

### ISSUE THREAD

**Issue by markus-oberhumer** [nim-lang/Nim#5828]
I've recently introduced Nim to a number of colleagues (mostly with a C++ and Go background), and I want to share some of the feedback I got.

Surprise: you cannot print an array
```
echo([1, 2, 3])      # does not compile
var a = [4, 5, 6]
echo a               # does not compile
```

A trivial (but probably incorrect) fix is below, but I guess there must be other implications why something like this not enabled by default.
```
diff --git a/lib/system.nim b/lib/system.nim
index 9b41253..0d7f926 100644
--- a/lib/system.nim
+++ b/lib/system.nim
@@ -1513,6 +1513,7 @@ proc repr*[T](x: T): string {.magic: "Repr", noSideEffect.}
   ##  var i = @[1, 2, 3, 4, 5]
   ##  repr(s) #=> 0x1055eb050[0x1055ec050"test2", 0x1055ec078"test2"]
   ##  repr(i) #=> 0x1055ed050[1, 2, 3, 4, 5]
+proc `$`*[I, T](x: array[I, T]): string = repr(x)
 
 type
   ByteAddress* = int
```

**Comment by trustable-code** [comment]
The correct syntax is:
```nim
echo(@[1, 2, 3])
echo @[1, 2, 3]
var a = @[4, 5, 6]
echo a
```

See https://nim-lang.org/docs/tut1.html#advanced-types-sequences

**Comment by def-** [comment]
@trustable-code That's a seq, not an array. Different thing.

**Comment by dom96** [comment]
Indeed, there is a reason that a ``$`` doesn't exist for arrays. Unfortunately I searched for it but could not find and I also cannot remember the reason.

**Comment by stisa** [comment]
Looking here https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L2425 the reason seems to be "causes bootstrapping to fail", don't know if that's still the case.

**Comment by Araq** [comment]
Still the case. :-)

**Comment by zah** [comment]
Well, this can be solved with a simple `when defined(...)` check.

**Comment by krux02** [comment]
Well just to add my two cents. I also would really like echo to work with array types. Defining ``echo`` on array types simply reduces friction when using the Nim language for beginners. And it reduces for me in case I forget the detail that ``echo`` does not simply work on array types.

**Comment by markus-oberhumer** [comment]
Thanks!

**Comment by markus-oberhumer** [comment]
I'm not sure if the following is a side effect of #5910 or some other recent changes - please have a look at this small test program which fails with current nim git devel:

```
discard """
  output: '''OK'''
"""

proc default[T](t: typedesc[T]): T {.noinline.} =
  var v: T
  v

proc test() =
  doAssert default(int) == 0
  doAssert default(float) == 0.0
  doAssert default(string) == nil
  doAssert default(cstring) == nil
  doAssert default(seq[int]) == nil

  doAssert $default(int) == "0"
  doAssert $default(float) == "0.0"
  doAssert $default(string) == ""
  doAssert $default(cstring) == ""
  doAssert $default(seq[int]) == "nil"

static:
  test()
test()

echo "OK"
```

```
$ nim c t5828.nim 
Hint: used config file '/home/hosts/amd64-linux/build/nim/nim-git/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t5828 [Processing]
stack trace: (most recent call last)
t5828.nim(23)            t5828
t5828.nim(18)            test
lib/system.nim(3639)     raiseAssert
lib/system.nim(2739)     sysFatal
lib/system.nim(2739, 7) Error: unhandled exception: $default(string) == "" 
```

**Comment by Araq** [comment]
@markus-oberhumer Please open an new issue for this. If it's not a bug we'll tell you, if it's a regression, we'll fix it. This issue is about "cannot echo an array" and that works now. I cannot reopen this issue for some valid but unrelated question.

**Comment by markus-oberhumer** [comment]
@Araq You're right, I've opened #6594.
