### ISSUE TITLE
Nim beginner's feedback: inconsistent integer overflow checks

### ISSUE THREAD

**Issue by markus-oberhumer** [nim-lang/Nim#5829]
I've recently introduced Nim to a number of colleagues (mostly with a C++ and Go background), and I want to share some of the feedback I got.

Surprise: integer overflows are handled different at compile-time vs. runtime
```
const a = 1 shl 62
var   b = 1 shl 62

echo(a * 2) # problem: no error (and surprising result !)
echo(b * 2) # ok: runtime error - overflow
```

Runtime integer overflow checks are generally regarded as a very welcome feature, but there might be some remaining implementation (or specification) issues.

**Comment by krux02** [comment]
Well when you use ``toHex`` from the ``strutils`` module, then it is easier to see what is wrong with ``a * 2``. But indeed the result is interesting.

If I remember correctly the reason for this behaviour was the goal to have constants like the language go has. In Go constants are calculated in arbitrary precision, and a cast is not necessary, when the final result is a valid value for the resulting number type.

This causes problems, and I would also really like to have the exact same behaviour of Numbers when used in the NimVm as when they are compiled down to C and then evaluated.
