### ISSUE TITLE
Nim 0.17: Error when compiling

### ISSUE THREAD

**Issue by Krognol** [nim-lang/Nim#5833]
`nim c -d:ssl --threads:on some_file.nim`

Results in

`Error: invocation of external linker program failed. Access is denied.
 5`

GCC is in my path (and in the .cfg).

Windows 10 64bit

**Comment by Krognol** [comment]
Moving the mingw location fixed it. Somehow.

**Comment by mini-eggs** [comment]
Heads up for anyone else. I downloaded Nim [here](https://nim-lang.org/install_windows.html) and set my env var pointing to my Downloads folder where I unzipped the file downloaded. Don't do that, move it to `C:\nim-0.17.0_x64\nim-0.17.0\bin`
