### ISSUE TITLE
nim doc2 --project does not recursively create subdirectories

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#5834]
When running `nim doc2 --project a.nim` where `a.nim` imports `sub / b.nim` the documentation for `b.nim` fails to create, because `nim doc2` does not create the `sub` subdirectory under the `htmldocs` output path.

**Comment by Araq** [comment]
Why would it? It's generated code. Flat means it's easier to get the navigation links right.

**Comment by couven92** [comment]
With that argument, why does `nim doc2` then create the `htmldocs` folder?

**Comment by Araq** [comment]
This has been implemented.
