### ISSUE TITLE
Nim-0.17.0 finish.exe: patch substring not found: #gcc.path = r"$nim\dist\mingw\bin"

### ISSUE THREAD

**Issue by softwaredownload** [nim-lang/Nim#5835]
Nim-0.17.0

`./finish.exe`:

>  patch substring not found: #gcc.path = r"$nim\dist\mingw\bin"

**How to Reproduce the issue:**

Nim folder:
C:\nim

mingw64 folder:
C:\mingw

Path environment:
C:\mingw\bin 
C:\nim\bin

Run:
`finish.exe`

> bin/nim.exe is already in your PATH [Skipping]
> MingW installation found at C:\mingw\bin
> Do you want to patch Nim's config to use this?
> (Not required since it's in your PATH!) (y/n) y
> Could not patch 'config/nim.cfg' [Error]
> Reason: patch substring not found:
> #gcc.path = r"$nim\dist\mingw\bin"

gcc.path in C:\nim\config\nim.cfg

`gcc.path = r"..\mingw64\bin" # winrelease`

I fixed it by comment out the line above in nim.cfg

**Comment by Araq** [comment]
I uploaded a new set of zips. Please redownload and test it.

**Comment by softwaredownload** [comment]
I tested nim-0.17.0_x64.zip on Windows, it is working now
