### ISSUE TITLE
Can't initialise object fields in the same line

### ISSUE THREAD

**Issue by konqoro** [nim-lang/Nim#5836]
When trying to initialise some fields of an object to a value in the same line, the compiler fails with the error shown below.

```
type MyObject = object
    x, y: float

proc newMyObject(): MyObject =
    # (result.x, result.y) = (1.0, 1.0) # works
    result.x, result.y = 1.0
```

I get: `bug.nim(6, 5) Error: type mismatch: got (float) but expected 'MyObject = object'`

**Comment by Araq** [comment]
Yes, that's how the language works. Tuple unpacking needs ``()``.

**Comment by konqoro** [comment]
@Araq but the commented code is tuple unpacking. However the bug report is about this syntax `var myVar1, myVar2, myVar3 = 0.0` which works otherwise but not with object fields. Better example: 
```
type MyObject = object
    x, y: int

var res: MyObject
res.x, res.y = 1

var x, y = 1
```

**Comment by konqoro** [comment]
I see now what was wrong. `var x, y = 0 ` doesn't work outside of var or let.
