### ISSUE TITLE
json.to() is not worth using compared to marshal.to[T]

### ISSUE THREAD

**Issue by Krognol** [nim-lang/Nim#5848]
I was excited to hear that there would be a json specific marshaling macro with the new version. However, it's not quite what I expected.

The problem that I ran into was that if an object had a set of extra fields, but the json payload didn't have that key, it'd throw a `KeyError`. For example:

```nim
import marshal, json

type 
  SomeObject = object
    key1: int
    key2: int
    key3: int

let payload = """{"key1": 1, "key2": 2}"""

let obj = marshal.to[SomeObject](payload)

let js = parseJson(payload)

# This would throw a `KeyError` because the json payload is missing the key `key3`
let obj2 = js.to(SomeObject) 

echo obj
echo obj2 
```

While `marshal.to[T]` would just leave the missing field with a zero value and continue without problem.

I'm not sure if this is just an oversight, but I'll be sticking to `marshal.to[T]` until some changes are done to `json.to`.

**Comment by endragor** [comment]
The usual solution to this is to have additional flags for parsing procedure, for example:
```nim
js.to(SomeObject, {ParseOption.AllowMissingKeys, ParseOption.IgnoreUnknownKeys})
```

**Comment by andreaferretti** [comment]
I would be very surprised if an exception **was not** raised

**Comment by endragor** [comment]
Yes, I agree the current behaviour makes sense as the default.

**Comment by loloiccl** [comment]
#5856 and #5879 are related with this issue.
Reference to these are helpful to fix this issue.

**Comment by dom96** [comment]
Relying on ``marshal.to``'s behaviour isn't a good idea because the format that is used for marshalling only happens to be JSON, there are special fields that it looks for and i'm sure many edge cases which you have not found.

The plan for ``json.to`` is to support ``Option[T]`` types in the object definitions for this use case.
