### ISSUE TITLE
Minor issue : compiling with doc2 throws Error: ambiguous call

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#5853]
Simple example:

```nim
# test.nim
import os
## Documentation here
echo("User home  dir " , getHomeDir())
```
Compile with nim doc2 test
```nim
test.nim(3, 36) Error: ambiguous call; both ospaths.getHomeDir() and os.getHomeDir() match for: ()
```
The error  seems to have no effect and the file test.html is created fine.

**Comment by daneb** [comment]
Hello

Could I ask for some help?

In reading up, I see ambiguous calls have the decided behavior of raising an error.
getHomeDir() is defined in "ospaths" but not in "os".
So I don't see how this is ambiguous. Ultimately I would like some guidance on how to fix it?

Thank you

**Comment by Araq** [comment]
ospaths.nim contains some ``when defined(nimdoc)``  special rules so that the docgen can generate the docs for ospaths as well as for os.nim. The logic is likely wrong though causing this problem. It should only take a bit trial and error until every combination (``nim c ospaths``, ``nim c os``, ``nim doc2 ospaths``, ``nim doc2 os``) works.

**Comment by Yardanico** [comment]
@Araq doesn't happen for me anymore.
Output:
```nim
Hint: used config file '/home/tiber/nim/config/nim.cfg' [Conf]
Hint: used config file '/home/tiber/nim/config/nimdoc.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: times [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: operation successful (22710 lines compiled; 0.278 sec total; 28.027MiB peakmem; Debug Build) [SuccessX]
```
