### ISSUE TITLE
Range type inference leads to counter-intuitive behvaiour

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5854]
Nim modifies range types under the hood when you make arithmetic operations on them. For example if you add 2 to the type range[0..127], you get range[2..129]. While being useful in some cases, in others this leads to problems that can not be seen, until the program encounters some values that cause range errors in runtime. For example:
```nim
type
  n16* = range[0'i16..high(int16)]

const someCondition = true

var level: n16 = 1
let maxLevel: n16 = 1

if someCondition:
  # Runtime error
  level = min(level + 2, maxLevel)
else:
  # This works
  level = min(maxLevel, level + 2)
```
The code that errors out in this case looks logical and you would never guess that it can error out in runtime, but it does. Simply swapping the operands of `min` fixes it.

**Comment by Araq** [comment]
I agree, these implicit subrange computations cause more harm than good. Already on the agenda.
