### ISSUE TITLE
Cannot 0xFFFF_FFFF to uint32 "type mismatch"

### ISSUE THREAD

**Issue by WetDesertRock** [nim-lang/Nim#5858]
When attempting to assign 0xFFFF_FFFF to a uint results in this error message: 

> type mismatch: got (int64) but expected 'uint32'

Example:
```nim
var
  myuint: uint32

# Tests cases, uncomment to check them
myuint = 0xFFFF_FFFF
# myuint = 0x7FFF_FFFF # This works
# myuint = (0x7FFF_FFFF + 1) # So does this
# myuint = 0x8000_0000 # But not this

echo myuint


# The error looks somewhat like:
#   tests.nim(7, 8) Error: type mismatch: got (int64) but expected 'uint32'
```

It appears that it thinks uint32's abide by the same assignment rules as int32's?

**Comment by markus-oberhumer** [comment]
According to the discussion at #5944 this is the expected and documented behaviour (you must use `0xFFFF_FFFFu32`), so this issue should be closed.
