### ISSUE TITLE
Modifying a read-only string using a cstring

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#5860]
It is possible to change the value of a read-only string using a cstring.

```nim
let x = "aaaaaaaa"
var y: cstring = x

y[3] = 'b'
echo x
```
The result is "aaabaaaa". I expected "y" to be a copy of "x", but this is not the case. Making "x" a constant causes a segmentation violation.

**Comment by Araq** [comment]
No bug here. Be careful with ``cstring``'s.

**Comment by lscrd** [comment]
OK, but it means that using a cstring must be considered unsafe when assigning a string to a cstring, which is a frequent case, as we create an alias even when the string is read-only.
