### ISSUE TITLE
noSideEffect in os module

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#5880]
The `noSideEffect` pragma behaves incorrectly with some procs in `os`. Using `symlinkExists`, `fileExists` or `dirExists` in a `noSideEffect` proc compiles without error.

**Comment by GULPF** [comment]
After looking up the reason for this I feel a bit confused. The reason that most procs in the `os` module are marked with `sideEffect` is because they call `osLastError()`. The funny thing is that `osLastError()` accesses the global `errno` on POSIX, but on Windows it calls some WINAPI function. This means that `osLastError()` (and by extension most procs in the `os` module) is only marked with `sideEffect` on POSIX, not on Windows. To me this just seems like an implementation detail - surely calling a WINAPI function to get the last error is a `sideEffect` just like getting it from a global.

Is the problem that all `importc` procs needs to be explicitly marked with `sideEffect` when applicable? If so, that seems easy to fix but will likely break a bunch of code that relies on the current situation.

**Comment by dom96** [comment]
> Is the problem that all importc procs needs to be explicitly marked with sideEffect when applicable? If so, that seems easy to fix but will likely break a bunch of code that relies on the current situation.

Yep. Breakage is fine as whatever code that breaks will be wrong anyway.
