### ISSUE TITLE
State of the REPL

### ISSUE THREAD

**Issue by 6A** [nim-lang/Nim#5886]
After spending the good part of my day working on a REPL, I discovered that it already exists, as the [`nim secret`](https://github.com/nim-lang/Nim/blob/ab31b776ef00df4a43f8afccb2e7c39a05616d2a/compiler/main.nim#L261) command.

Is there any specific reason for keeping it secret? Nothing in the manual or docs refers to this feature.

**Comment by kirbyfan64** [comment]
It was killed in #2633, and IIRC the rationale was that it had a crapton of odd bugs/edge-cases in it.

**Comment by andreaferretti** [comment]
It also relies on the interpreter (the thing which is used in macros and compile time function execution) and as such it cannot import modules that rely on C code, that is, most of the stdlib

**Comment by dom96** [comment]
> it cannot import modules that rely on C code, that is, most of the stdlib

This is the biggest problem with it.
