### ISSUE TITLE
About ambiguous ``concept``

### ISSUE THREAD

**Issue by tulayang** [nim-lang/Nim#5888]
## ambiguous

I found the ``concept`` will be ambiguous if one ``concept`` look like a subclass of another ``concept``: 

```nim
type
  CA = concept c
    c.x is int

  CB = concept c
    c.x is int
    c.y is string

  Opt = object
    x: int
    y: string

proc f1(c: CA) =
  echo "f1"

proc f1(c: CB) = 
  echo "f2"

var o: Opt

echo o is CA # true
echo o is CB # true

o.f1() # Error: ambiguous call; both test.f1(c: CB) and test.f1(c: CA) match for: (Opt)
```

If you have many files and many ``concepts``, this will be a trouble. Could ``Opt`` explicitly specify  ``CA`` or ``CB`` to match only one? Just like ``implement interface`` or ``extends abstract class`` in java or typescript?:

```nim
type
  Opt = object impl CA
```

## ``cast`` trouble

And I found I can not use ``cast``  with ``concept``:

```nim
type
  CA = concept c
    c.x is int
    c.stream is Stream

  Stream = object
    data: pointer

proc cb(stream: ptr Stream) {.cdecl.} =
  var c = cast[CA](stream.data) # Error: expression cannot be cast to CA

proc f(c: CA) =
  # ...
  cb(c.stream.addr)
``` 

``object of`` can work normally:

```nim
type
  CA = ref object of RootObj
    x: int
    stream: Stream

  Stream = object
    data: pointer

proc cb(stream: ptr Stream) {.cdecl.} =
  var c = cast[CA](stream.data)

proc f(c: CA) =
  # ...
  cb(c.stream.addr)
```

However, you must export ``x`` to another module if you use ``object of``. Then, the ``x`` had to be a public member, although I want it to be a private member. I mean that  Nim lacks **protected member** of OOP.

```nim
import ca

type
  MyObj = ref object of CA 

proc f2(m: MyObj) =
  echo m.x # x must be exported in ca module
```

## instantiate trouble

Is this expected by compiler?

```nim
type
  CA = concept c
    c.x is int
  
  Opt = ref object
    x: int

proc f(c: CA) = 
  echo "f"
  echo c.x # Error: undeclared field: 'x'

var o = new(Opt)
echo o is CA # true

o.f()
```

**Comment by zah** [comment]
This is not finished, but concepts will support "refinement", which is something similar to inheritance:
https://nim-lang.org/docs/manual.html#generics-concept-refinement

Concepts are not concrete types and you cannot cast values to them. The "VTable types" derived from concepts will be concrete types:
https://nim-lang.org/docs/manual.html#generics-vtable-types

The last code example is a genuine issue. I'll investigate it.

**Comment by tulayang** [comment]
I met new troubles:

## multiple modules trouble

These codes, will be ``true`` if they are in the some module: 

```nim
type
  CA* = concept c
    c.x is int

  Opt* = object
    x: int

var o: Opt
echo o is CA # true 
```

However, the output is ``false`` if they are in multiple different module: 

```nim
# a1.nim
type
  CA* = concept c
    c.x is int
```

```nim
# a2.nim
import a1

type
  Opt* = object
    x: int
```

```nim
# a3.nim
import a1, a2

var o: Opt
echo o is CA # false
```

`nim c -r a3.nim`

## compile trouble

If I set ``CA`` to ``a1.CA``, the compiler will hang up:

```nim
# a1.nim
type
  CA* = concept c
    c.x is int
```

```nim
# a2.nim
import a1

type
  Opt* = object
    x: int
```

```nim
# a3.nim
import a1, a2

var o: Opt
echo o is a1.CA 
```

`nim c -r a3.nim`
