### ISSUE TITLE
shr produces undefined behaviour

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5889]
The documentation only explains behaviour for int64, and it says the shift is logical (discarded bits are filled with zeroes). Well, it's true for int64, but for other signed types the shift is arithmetic. Pretty sure it shouldn't be this way.

Sample:
```nim
let intVal: int = -1
let int8Val: int8 = -1
let int16Val: int16 = -1
let int32Val: int32 = -1
let int64Val: int64 = -1

echo(intVal shr 7)
echo(int8Val shr 7)
echo(int16Val shr 7)
echo(int32Val shr 7)
echo(int64Val shr 7)
```
Output on macOS (64-bit):
```
144115188075855871
-1
-1
-1
144115188075855871
```
Git hash: 2b8a1cee8cbeddb3e64193a59a78b5d0f46d2fda

**Comment by Araq** [comment]
This should have been fixed.

**Comment by endragor** [comment]
Yes, can confirm this is fixed in `devel`.
