### ISSUE TITLE
Sigmatch error in fitting anonymous tuples to generic types

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#5890]
``` nim
type
  ValueHolder[T] = ref object
    value: T

  SomeTuple[T] = tuple
    x: ValueHolder[T]
    y: ValueHolder[T]

proc foo[T](): ref SomeTuple[T] =
  new(result)
  result[] = (x: nil, y: nil)

var x = foo[string]()
```

The nil values used in the tuple literal force the compiler to try to guess the tuple field types. This guesswork would in turn fail only when the fields have a generic ref object type.

**Comment by philip-wernersbach** [comment]
Since this used to work, what is the source of this regression?
