### ISSUE TITLE
parseopt2 does not process arguments passed to initOptParser(cmdline: seq[string])

### ISSUE THREAD

**Issue by noirb** [nim-lang/Nim#5896]
initOptParser accepts a seq[string] of arguments, but appears to ignore any values passed in and only uses the values provided by `commandLineParams()`.

```nim
    import parseopt2
    
    var argv: seq[string] = @["-a=1", "--bee=2", "-c:3"]
    # argv here is ignored, and only the system-provided args are processed
    var parser = initOptParser(argv)
    for kind, key, val in getopt():
      echo "kind: ", kind, "\tkey:val  --  ", key, ":", val
```

Expected output when run with no arguments:

    kind: cmdShortOption    key:val  --  a:1
    kind: cmdLongOption     key:val  --  bee:2
    kind: cmdShortOption    key:val  --  c:3

Output when run with `--arg=someval`:

    kind: cmdLongOption     key:val  --  arg:someval

This also appears to be true of parseopt:

```nim
    import parseopt
    # args passed here are ignored
    var parser = initOptParser("-a=1 --bee=2")
```

**Comment by Parashurama** [comment]
It's not clear here if passing some args to intOptParser is meant to override cmdline args or to be prepended to it.
intOptParser code comment says:
```nim
## inits the option parser. If ``cmdline == ""``, the real command line
## (as provided by the ``OS`` module) is taken.
```

**Comment by Araq** [comment]
Good point, it's meant to override it.

**Comment by dom96** [comment]
@Parashurama please use "fixes #issue_number" in your commits to automatically close these issues when your commits are merged.
