### ISSUE TITLE
Macros on AST require exported procs / consts

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#5897]
I have written a macro which modifies the AST of the user. All the const/procs declared in the new AST must be exported with `*` otherwise Nim throws undeclared identifier.

This is not ideal as it leaks implementation details and expose procs/const I do not want users to use directly.

For example my macro replace the syntax `foo[ _, _]` by `foo[span, span]`.
Replacement is done [here](https://github.com/mratsim/Arraymancer/blob/ac35a2e0f14ff351d9e13fd2d8dd11bf0283f61f/src/arraymancer/accessors_slicer.nim#L234) and `span` definition is [here](https://github.com/mratsim/Arraymancer/blob/ac35a2e0f14ff351d9e13fd2d8dd11bf0283f61f/src/arraymancer/accessors_slicer.nim#L142) 

I get
`Error: undeclared identifier: 'span'` if I delete the `*` export symbol.

Same issue with procs called in macros like [here](https://github.com/mratsim/Arraymancer/blob/ac35a2e0f14ff351d9e13fd2d8dd11bf0283f61f/src/arraymancer/accessors_slicer.nim#L347) and declared [here](https://github.com/mratsim/Arraymancer/blob/ac35a2e0f14ff351d9e13fd2d8dd11bf0283f61f/src/arraymancer/accessors_slicer.nim#L317).

I suppose it's because AST is modified in-place, i.e. in the importing code which doesn't see non-exported procs/consts

**Comment by Araq** [comment]
Use ``bindSym("span")`` in your macro? And copy the AST over to the result, don't mutate it.

**Comment by mratsim** [comment]
Thanks.

Regarding the copy of the AST, I'm saying mutating in-place but I think I'm actually copying:
I load the user AST, parse it, and create a new result from scratch with rearranged, new or deleted nodes. I then pass the result to the proper proc.
