### ISSUE TITLE
Cannot disable 'rangeChecks' in VM.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#5903]
{.push: rangeChecks:off} can be used to disable rangeChecks while converting from numerical type to another in runtime code. However this has no effect at compile time.
```nim
proc getBits(x: int16) =
  # real code is obviously very different
  # and I need access to integer bit data
  {.push: rangeChecks:off}
  echo x.uint16
  {.pop.}

let A = -3'i16
A.getBits # this works

static:
  let B = -3'i16
  B.getBits # this fails

```

**Comment by Araq** [comment]
This is a feature, ``rangeChecks: off`` is for speed, not for changing semantics (the stdlib contains this mistake too). Use ``cast[uint16](x)`` for a bit reinterpretation.

**Comment by Parashurama** [comment]
As far as I know, **cast** is not allowed in the VM.

**Comment by Araq** [comment]
Some casts are now allowed in the VM.
