### ISSUE TITLE
Can we remove pointer from VM?

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#5911]
I just checkout the ``pointer`` type. As far as I know the pointer cannot be set to anything when on the nimvm/nimscript. Casting is not allowed when on the vm, and operations that change the value of ``pointer`` don't exist either. Therefore the type ``pointer`` can only have the value ``nil``, nothing else. That is not very useful, therefore the question to remove it.

**Comment by Araq** [comment]
```nim
type
  TFullReg = object   # with a custom mark proc, we could use the same
                      # data representation as LuaJit (tagged NaNs).
    case kind: TRegisterKind
    of rkNone: nil
    of rkInt: intVal: BiggestInt
    of rkFloat: floatVal: BiggestFloat
    of rkNode: node: PNode
    of rkRegisterAddr: regAddr: ptr TFullReg
    of rkNodeAddr: nodeAddr: ptr PNode
```

That's the content of a register in the VM. Which ``pointer`` are you talking about?

**Comment by krux02** [comment]
I am talking about the ``pointer`` type in ``var t: pointer``.
```Nim

static:
  var p1: pointer = alloc(10)
  var v1: int
  var p2: = cast[pointer](v1.addr)
```

- ``alloc`` is not allowed on the vm
- ``cast`` is not allowed on the vm

I don't see a way to set the value of ``pointer`` at all at the moment.

**Comment by krux02** [comment]
Well not really important
