### ISSUE TITLE
Possibly not unloading libraries causing valgrind memory leak (minor)

### ISSUE THREAD

**Issue by ashleybroughton** [nim-lang/Nim#5921]
# Description
There appears to be a memory leak of kinds when using asyncdispatch and compiling with the -d:ssl flag. This appears to happen using both 0.16.0 and 0.17.0

## Setup
```
nim --version && echo "import asyncdispatch" > test.nim
```
> Nim Compiler Version 0.17.0 (2017-05-17) [Linux: amd64]
> Copyright (c) 2006-2017 by Andreas Rumpf
> 
> git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
> active boot switches: -d:release

## Results without -d:ssl
```
nim c test.nim && valgrind ./test
```

> Hint: used config file '/home/test/src/nim-0.17.0/config/nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: test [Processing]
> Hint: asyncdispatch [Processing]
> Hint: os [Processing]
> Hint: strutils [Processing]
> Hint: parseutils [Processing]
> Hint: math [Processing]
> Hint: algorithm [Processing]
> Hint: times [Processing]
> Hint: posix [Processing]
> Hint: ospaths [Processing]
> Hint: tables [Processing]
> Hint: hashes [Processing]
> Hint: heapqueue [Processing]
> Hint: options [Processing]
> Hint: typetraits [Processing]
> Hint: nativesockets [Processing]
> Hint: net [Processing]
> Hint: sets [Processing]
> Hint: deques [Processing]
> Hint: selectors [Processing]
> Hint: epoll [Processing]
> Hint: macros [Processing]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/test.o /home/test/src/nim-valgrind-test/nimcache/test.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_system.o /home/test/src/nim-valgrind-test/nimcache/stdlib_system.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_asyncdispatch.o /home/test/src/nim-valgrind-test/nimcache/stdlib_asyncdispatch.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_strutils.o /home/test/src/nim-valgrind-test/nimcache/stdlib_strutils.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_net.o /home/test/src/nim-valgrind-test/nimcache/stdlib_net.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_sets.o /home/test/src/nim-valgrind-test/nimcache/stdlib_sets.c [Exec]
> Hint:  [Link]
> Hint: operation successful (31567 lines compiled; 10.145 sec total; 54.746MiB peakmem; Debug Build) [SuccessX]
> ==4657== Memcheck, a memory error detector
> ==4657== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
> ==4657== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
> ==4657== Command: ./test
> ==4657==
> ==4657==
> ==4657== HEAP SUMMARY:
> ==4657==     in use at exit: 0 bytes in 0 blocks
> ==4657==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
> ==4657==
> ==4657== All heap blocks were freed -- no leaks are possible
> ==4657==
> ==4657== For counts of detected and suppressed errors, rerun with: -v
> ==4657== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

## Results with -d:ssl
```
nim c -d:ssl test.nim && valgrind ./test
```

> Hint: used config file '/home/test/src/nim-0.17.0/config/nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: test [Processing]
> Hint: asyncdispatch [Processing]
> Hint: os [Processing]
> Hint: strutils [Processing]
> Hint: parseutils [Processing]
> Hint: math [Processing]
> Hint: algorithm [Processing]
> Hint: times [Processing]
> Hint: posix [Processing]
> Hint: ospaths [Processing]
> Hint: tables [Processing]
> Hint: hashes [Processing]
> Hint: heapqueue [Processing]
> Hint: options [Processing]
> Hint: typetraits [Processing]
> Hint: nativesockets [Processing]
> Hint: net [Processing]
> Hint: sets [Processing]
> Hint: openssl [Processing]
> Hint: dynlib [Processing]
> Hint: deques [Processing]
> Hint: selectors [Processing]
> Hint: epoll [Processing]
> Hint: macros [Processing]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/test.o /home/test/src/nim-valgrind-test/nimcache/test.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_system.o /home/test/src/nim-valgrind-test/nimcache/stdlib_system.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_asyncdispatch.o /home/test/src/nim-valgrind-test/nimcache/stdlib_asyncdispatch.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_strutils.o /home/test/src/nim-valgrind-test/nimcache/stdlib_strutils.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_net.o /home/test/src/nim-valgrind-test/nimcache/stdlib_net.c [Exec]
> Hint: gcc -c  -w  -I/home/test/src/nim-0.17.0/lib -o /home/test/src/nim-valgrind-test/nimcache/stdlib_sets.o /home/test/src/nim-valgrind-test/nimcache/stdlib_sets.c [Exec]
> Hint:  [Link]
> Hint: operation successful (32333 lines compiled; 9.918 sec total; 54.746MiB peakmem; Debug Build) [SuccessX]
> ==4617== Memcheck, a memory error detector
> ==4617== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
> ==4617== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
> ==4617== Command: ./test
> ==4617==
> ==4617==
> ==4617== HEAP SUMMARY:
> ==4617==     in use at exit: 3,205 bytes in 8 blocks
> ==4617==   total heap usage: 17 allocs, 9 frees, 9,227 bytes allocated
> ==4617==
> ==4617== LEAK SUMMARY:
> ==4617==    definitely lost: 0 bytes in 0 blocks
> ==4617==    indirectly lost: 0 bytes in 0 blocks
> ==4617==      possibly lost: 0 bytes in 0 blocks
> ==4617==    still reachable: 3,205 bytes in 8 blocks
> ==4617==         suppressed: 0 bytes in 0 blocks
> ==4617== Rerun with --leak-check=full to see details of leaked memory
> ==4617==
> ==4617== For counts of detected and suppressed errors, rerun with: -v
> ==4617== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by ashleybroughton** [comment]
Further investigating this issue, I isolated the library loading / unloading code into a test file.  
If I load the SSL library manually without passing in -d:ssl, and make sure to unload it, I do not get this issue. This leads me to believe that there's a missing nimUnloadLibrary call missing somewhere.

https://gist.github.com/ashleybroughton/c7e0f8ce40ed0f86481468e9ef4d278d

**Comment by ashleybroughton** [comment]
Not so much a leak as it would be a single reference to the library not being freed.  
Shouldn't cause a memory consuming leak.

**Comment by BLeAm** [comment]
Any updates on this issue? I think I still experienced this problem with httpclient when turn -d:ssl on, Valgrind reported memory leaks and memory usage of the process keeps accumulating over time.

**Comment by ghost** [comment]
The original issue is not really an issue - unloading libraries like that will be done by the OS after the program is done anyway (the same as with globals).

As for @BLeAm  - I'm not sure what's your exact issue, can you show the code?

**Comment by ghost** [comment]
I think you should make a separate issue because this one is different

**Comment by ringabout** [comment]
> The original issue is not really an issue - unloading libraries like that will be done by the OS after the program is done anyway (the same as with globals).

If so, please close this issue.
