### ISSUE TITLE
async macro modifies nested procedures

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5923]
Sample:
```nim
import asyncdispatch

proc someAsync(): Future[void] {.async.} =
  proc somethingNested() =
    if true:
      return
  somethingNested()

waitFor someAsync()
```
.async macro tries to modify `return` statement here, even though it shouldn't touch nested procedures.

**Comment by narimiran** [comment]
Either I don't understand this issue or something was changed in the newer versions, because this is what I see when I compile your example with `-d:nimDumpAsync` on Nim 0.19:

```nim
proc someAsync(): Future[void] =
  var retFuture370014 = newFuture[void]("someAsync")
  iterator someAsyncIter370015(): FutureBase {.closure.} =
    proc somethingNested() =
      if true:
        return

    somethingNested()
    complete(retFuture370014)

  # etc.
```

The nested procedure seems untouched.

**Comment by dom96** [comment]
Fixed then I guess. Closing.
