### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by oggio88** [nim-lang/Nim#5936]
```
import tables

proc foo( 
        p1 : TableRef[string, string] = nil, 
        p2 : TableRef[string, string] = nil
        ) : void =
    discard

foo( 
    p1 = nil,
    p2 = nil,
)
```
this crashes the compiler with "SIGSEGV: Illegal storage access. (Attempt to read from nil?)"
note that it compiles fine if you pass to foo only one keyword argument

**Comment by andreaferretti** [comment]
Does not crash for me on devel (crashes on v0.17.0 though), can I close it?

**Comment by andreaferretti** [comment]
I am closing this, since it is fixed on devel. Please, reopen it if you think there is still something to consider
