### ISSUE TITLE
0.17.0 Cannot compile asyncdispatch with --threads:on option

### ISSUE THREAD

**Issue by melvinjoya** [nim-lang/Nim#5939]
importing asyncdispatch and compiling with --threads:on causes an error which I believe is due to the order in which the generated stdlib_asyncdispatch.c defines it's includes.

**test.nim**
`import asyncdispatch`

**nim c --threads:on test.nim**
> In file included from nimcache\stdlib_asyncdispatch.c:14:0:
.choosenim/toolchains/mingw32/i686-w64-mingw32/include/ws2tcpip.h:124:8: error: redefinition of 'struct ip_mreq'
 struct ip_mreq {
        ^
In file included from .choosenim/toolchains/mingw32/i686-w64-mingw32/include/winsock.h:38:0,
                 from .choosenim/toolchains/mingw32/i686-w64-mingw32/include/windows.h:92,
                 from nimcache\stdlib_asyncdispatch.c:12:
.choosenim/toolchains/mingw32/i686-w64-mingw32/include/psdk_inc/_ip_mreq1.h:12:8: note: originally defined here
 struct ip_mreq {
        ^

nimcache\\**stdlib_asyncdispatch.c**
```#include "nimbase.h"
#include <string.h>
#include <windows.h>
#include "winsock2.h"
#include "ws2tcpip.h"
#include <setjmp.h>
```

**Comment by cheatfate** [comment]
Looks like you trying to build on Windows.
I'm not using `choosenim`, and i'm able to compile your test.nim without problems on Windows 10 x64, via
```
Nim Compiler Version 0.17.1 (2017-06-04) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: c59bc0cc183ccaed25e8e4a3cc286f2bb351405b
active boot switches: -d:release
```
and 

```
gcc (GCC) 4.8.3
```

It looks like not `Nim compiler` issue, but `choosenim` issue. So maybe you need to create issue there https://github.com/dom96/choosenim.

**Comment by Araq** [comment]
Choosenim doesn't set the PATH to GCC and instead copies gcc.exe around. Yeah, choosenim bug.
