### ISSUE TITLE
< operators and templates

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [nim-lang/Nim#5950]
There is something special about the < operator in template expressions; I might be missing something, but it seems like a compiler bug to me. You be the judge (win10, nim0.17):

```
import math
import system

type
  Vector*[N: static[int], T] =
    array[N, T]

# template for common operation patterns; 
# adding this unary overload makes the < operator fail; works for all others though
template elementwise (action: expr, a, c: untyped): untyped =
  for i in 0..<N:
      c[i] = action(a[i])

template elementwise (action: expr, a, b, c: untyped): untyped =
  for i in 0..<N:
      c[i] = action(a[i], b[i])



proc `>`*[N, T](p, q: Vector[N, T]): Vector[N, bool] {.noInit.} =
  # wtf, why did this break out of the blue?
  elementwise(`>`, p, q, result)

proc `<`*[N, T](p, q: Vector[N, T]): Vector[N, bool] {.noInit.} =
  elementwise(`<`, p, q, result)

  
proc test(): void =
  let vec1 = [1, 2, 3]
  echo repr((vec1 > vec1))

test()
```

**Comment by Parashurama** [comment]
using {.explain.} pragma make this work.
```nim
proc `>`*[N, T](p, q: Vector[N, T]): Vector[N, bool] {.noInit.} =
  # wtf, why did this break out of the blue?
  elementwise(`>`, p, q, result) {.explain.}
```
I will investigate further.

**Comment by Araq** [comment]
Never define ``>`` and ``>=`` Nim has templates for these.

**Comment by EelcoHoogendoorn** [comment]
Right; they are always defined as the complement of < and <= I presume then. Makes sense I guess; cant think of a situation where this would not be the desired behavior in any case. But a compiler message explaining this would have been helpful.

**Comment by EelcoHoogendoorn** [comment]
> Never define > and >= Nim has templates for these.

Hmm... not defining > works well enough for my straight elementwise binary comaprison; but the case for a broadcasting comparison seems more tricky, ie something `like`
```
template elementwise_broadcast(action: expr, a, b, c: untyped): untyped =
  for i in 0..<N:
      c[i] = action(a[i], b)

proc `>`*[N, T](p: Vector[N, T], k: T): Vector[N, bool] {.noInit.} =
  elementwise_broadcast(`>`, p, k, result)
```
These operators are not autogenerated; but defining them proves a tad tricky too; I have to put brackets around access operators, otherwise precendence rules go wonky; or why it is that it fails without the round brackets? And is this intended behavior?
```
        if (rdir[i]) > 0.0:
```

**Comment by Araq** [comment]
Never define ``>`` and ``>=``.

**Comment by EelcoHoogendoorn** [comment]
If I may repeat myself as well then.. ;)... is there a compiler warning for it now?

**Comment by Araq** [comment]
No, but it's covered by our 2nd tutorial.
