### ISSUE TITLE
typetraits type.name returns Base type name instead of Child type name in proc or method.

### ISSUE THREAD

**Issue by ftsf** [nim-lang/Nim#5955]
When a child ref object is passed to a proc or method `type.name` returns the name of the Base type instead of the child type.

```nim
import typetraits

type BaseFoo = ref object of RootObj
type ChildFoo = ref object of BaseFoo

proc newChildFoo(): ChildFoo =
  result = new(ChildFoo)

var foo = newChildFoo()


proc frob*(foo: BaseFoo): string =
  return foo.type.name

method frobMethod*(foo: BaseFoo): string =
  return foo.type.name

echo foo.type.name
echo frob(foo)
echo frobMethod(foo)
```

```
expected output
ChildFoo
ChildFoo
ChildFoo

actual output:
ChildFoo
BaseFoo
BaseFoo
```

**Comment by Varriount** [comment]
In addition, using the typeinfo module isn't much help either, as all the type retrieval procedures only retrieve the type information of the variable/parameter passed in, not the type information of the reference.

**Comment by Araq** [comment]
That is not a bug, typetraits is not RTTI.

**Comment by ftsf** [comment]
Is there an alternative way to get the run-time type name (not necessarily as string) of an inherited ref object?

**Comment by Parashurama** [comment]
There are some hacks to get access to type pointer (see:  typeinfo module) and from there
The most robust way to do this might be to do something like this:
```nim
type
    Base = ref object of RootRef

    Child = ref object of Base

method classname(self: Base): string = "Base"
method classname(self: Child): string = "Child"
```
Now any instance of Base or Child can access to RTTI class name.
In a real world program, you would probably generate these methods with a few macros.
