### ISSUE TITLE
Cannot index tuple with int, despite being in range

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [nim-lang/Nim#5960]
I would expect the following to compile, but it gives "Error: cannot evaluate at compile time: p"
```
type Permutation* = range[0..1]

let p: Permutation = 1

let a = [1, 2]
let t = (1, 2)

echo(repr(a[p]))
echo(repr(t[p]))  # this does not compile
```

Is this intended behavior? Id argue that compile-time-constant arrays and tuples are only syntactically different. The fact that p has the same range as the number of fields of t should be all the compiler needs to know, right?

**Comment by EelcoHoogendoorn** [comment]
As for the reason I care; I'd like to do a branchless swap/permutation of the fields of a tuple. If there is some other method of achieving that result, that would be just as interesting as the answer to the original question

**Comment by EelcoHoogendoorn** [comment]
To further clarify; I could use an array instead of a tuple and add some accessor procs to get named field like syntax; which is what I did originally... until I ran into a seeming compiler bug relating to nested arrays. That is array[n, array[m, t]] only seems to work correctly when n=m. But more on that in a separate issue later.

**Comment by EelcoHoogendoorn** [comment]
Just had a realization; indexing a tuple only makes sense when all fields have the same type; this particular tuple in question does so the compiler might as well accept it as a special case; but in general an array with compile time constant length is indeed the more appropriate construct for this application... so ill get to working out what my beef with them is exactly.

**Comment by EelcoHoogendoorn** [comment]
Not all fields need to have the same type of course; just all fields of the ordinal being indexed with. Shouldnt be hard to add as a compiler rule i imagine.

**Comment by EelcoHoogendoorn** [comment]
#5962 describes the reason I went down the path described here

**Comment by Araq** [comment]
```nim


type Permutation* = range[0..1]

const p: Permutation = 1

let a = [1, 2]
var t = (1, 2)

swap(t[p], t[1-p])

echo(repr(a[p]))
echo(repr(t[p]))
```

const works and so does swap.

**Comment by EelcoHoogendoorn** [comment]
To summarize my understanding: const works because it denotes a compile-time constant; ie, the same as putting the 1 directly in the square brackets.

However, do you agree it would be nice if Ordinals with the same range as the set of valid compile time constants for any given tuple indexation had the same behavior?

**Comment by Araq** [comment]
> However, do you agree it would be nice if Ordinals with the same range as the set of valid compile time constants for any given tuple indexation had the same behavior?

No, I'd rather make ``static T`` work with arrays finally. (Just how many bugs can a single feature have?)

**Comment by EelcoHoogendoorn** [comment]
I agree, thatd be nice too :). But one does not preclude the other.

Since the point of subrange types is for the compiler to be able to make these kind of inferrences at compile time, it is slightly intuitive that it does not realize this operation is safe. But yeah, being able to do something in theory and having it make its way to the top of your priority stack are different things, I am well aware, and indeed the static T thing is a lot more urgent.
