### ISSUE TITLE
Error in calling finalizers

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#5978]
I have a couple data types which hold a reference to a GPU pointer, where some data is allocated, as well as a non managed pointer which points somewhere inside this data array. The strategy is to wrap an unmanaged pointer (such as those returned by CUDA) into a managed one and add a finalizer to clean up.

The definition looks like

```nim
type CudaVector*[A] = object
  data*: ref[ptr A]
  fp*: ptr A
  len, step*: int32
```
and there is [a similar one for matrices](https://github.com/unicredit/neo/blob/master/neo/cudadense.nim#L18-L27).

The idea is that many vectors and matrices can share the same data but point into different places inside this data. (Here `fp` is the actual inner pointer, while `data` is a reference to a pointer to the beginning of the data.) When the last reference to the data goes away, I want to clean it up. Hence there is [this finalizer](https://github.com/unicredit/neo/blob/master/neo/cudadense.nim#L33-L35)

```nim
proc freeDeviceMemory[A](p: ref[ptr A]) =
  if not p[].isNil:
    check cudaFree(p[])
```
Each time I create a new vector or matrix, either:

* `data` is initialized [using the finalizer](https://github.com/unicredit/neo/blob/master/neo/cudadense.nim#L46), or
* `data` is [copied from a pre-existing vector or matrix](https://github.com/unicredit/neo/blob/master/neo/cudadense.nim#L134)

When launching the tests, though, I get an error while locating the finalizer:

```
Traceback (most recent call last)
unittest.nim(405)        scopy
gc.nim(550)              newSeqRC1
gc.nim(525)              newObjRC1
gc.nim(245)              prepareDealloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

The [relevant line](https://github.com/nim-lang/Nim/blob/devel/lib/system/gc.nim#L245) is

```nim
if t.finalizer != nil:
```

Similarly with gc v2:

```
Traceback (most recent call last)
unittest.nim(404)        scopy
unittest.nim(307)        testEnded
unittest.nim(126)        testEnded
unittest.nim(193)        testEnded
repr.nim(81)             reprEnum
gc2.nim(479)             newObjNoInit
gc2.nim(454)             rawNewObj
gc2.nim(961)             collectCT
gc2.nim(927)             collectCTBody
gc2.nim(897)             collectZCT
gc2.nim(224)             prepareDealloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

The [relevant line](https://github.com/nim-lang/Nim/blob/devel/lib/system/gc2.nim#L224) is

```nim
if cell.typ.finalizer != nil:
```

I think this is a bug with the GC. It doesn't seem to fail with either boehm or mark and sweep, but I am not sure whether they are triggered at different thresholds or whether they simply do not support finalizers.

To reproduce the bug, it **should** be enough to run `nimble testcuda` from the [neo](https://github.com/unicredit/neo) repository, after removing [this temporary workaround](https://github.com/unicredit/neo/blob/master/neo.nimble#L66). But, as all bugs related to GC, it may disappear with different memory available and so on. Maybe a `GC_fullCollect()` is enough to restore it.

An annoyance may be that the relevant part of the library requires to have CUDA installed.

**Comment by andreaferretti** [comment]
I tried to reproduce a small example, without CUDA, but the issue does not appear there. I leave this for posterity

```nim
import random

type
  CPointer*[A] = ptr UncheckedArray[A]
  Chunk = object
    data: ref[ptr byte]
    fp: CPointer[byte]

proc cleanChunk[A](p: ref[ptr A]) =
  dealloc(p[])

proc makeChunk(n: int): Chunk =
  new result.data, cleanChunk
  result.fp = cast[CPointer[byte]](alloc(n))
  result.data[] = cast[ptr byte](result.fp)
  for i in 0 ..< n:
    result.fp[i] = byte(rand(256))

proc copy(c: Chunk): Chunk =
  Chunk(
    data: c.data,
    fp: c.fp
  )

proc createGarbage() =
  var count = 0
  for _ in 1 .. 100000:
    let chunk = makeChunk(10000)
    for _ in 1 .. 1000:
      let chunk1 = copy(chunk)
      if chunk1.fp[100] == byte(23):
        inc(count)
    if rand(10) == 0:
      GC_fullCollect()
  echo count

when isMainModule:
  createGarbage()
```

**Comment by Araq** [comment]
Not a problem with ORC.
