### ISSUE TITLE
Cannot cast pointer to char in cpp

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5979]
```nim
var a: pointer
let b = cast[char](a)
```
```
nim cpp test.nim
```
```
Error: execution of an external compiler program 'clang++ -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test.o /Users/yglukhov/nimcache/test.cpp' failed with exit code: 1

/Users/yglukhov/nimcache/test.cpp:95:30: error: cast from pointer to smaller type 'NIM_CHAR' (aka 'char') loses information
        b_jMbWDpGpOqhqU7TWn5m0uA = ((NIM_CHAR) (a_MKOwYvPH6MkTSfJQoSvUmg));
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by krux02** [comment]
Well maybe the error should already be in the Nim compiler, but the fact that this fails I don't see as an error at all.

**Comment by TiberiumN** [comment]
I think this is clang-only issue?
Because on Windows with latest Visual compiler I don't have any errors

**Comment by TiberiumN** [comment]
And in CPP source code file I have exact line as yours:
"b_nQ36LxrhQjhh64OQreRUtA = ((NIM_CHAR) (a_xzOgHt2oY9bilgf3P0vBXUg));"

**Comment by yglukhov** [comment]
@TiberiumN Indeed, that might be clang specific behavior.
@krux02, what's wrong with this code? `cast` is supposed to allow "unsafe" casts.

**Comment by Araq** [comment]
But the bitwidths are not the same so it looks like a cast that is really not useful. what's the use case?

**Comment by yglukhov** [comment]
The use-case is different low-levelish stuff when you want to store auxiliary values in a pointer.
- In different C APIs you pass a callback along with `void*` context. It should not necessarily be a valid pointer.
- In my [variant](https://github.com/yglukhov/variant) type I use pointer to store any POD data who's size is `<= sizeof(pointer)`. And `char` is exactly that.

**Comment by Araq** [comment]
Ok, that is convincing use case.

**Comment by krux02** [comment]
Well the question should be, should Nim behave the same as the clang compiler? Because I think getting the information that the sizes mismatch might be an important information.

I propose this Nim code:
```Nim
var a: pointer
let b = char(cast[int](a))
```
This code uses a cast that doesn't change the size of the type and then uses a conversion of the resulting integer type. This is more explicit in what you want and still allows you to detect unwanted or unsafe casts in the language.

**Comment by yglukhov** [comment]
Given that nim `cast` is already as unsafe as possible (sometimes it even behaves as `reinterpret_cast`), bitwidth mismatch is not the scariest problem in this context =)

**Comment by krux02** [comment]
Well I disagree that cast should be as unsafe as possible.

**Comment by Araq** [comment]
> This code uses a cast that doesn't change the size of the type and then uses a conversion of the resulting integer type. This is more explicit in what you want and still allows you to detect unwanted or unsafe casts in the language.

Hmm that is a very good idea too.

**Comment by krux02** [comment]
@yglukhov In my opinion the ``cast`` in Nim is the ``reinterpret_cast`` from c++, but I don't see anything wrong to only allow reinterpretation casts of types that actually have the same size.

**Comment by andreaferretti** [comment]
I also like the version of @krux02 better. It should behave the same (no runtime cost) and still it is more clear and explicit
