### ISSUE TITLE
Concepts don't play well with distinct primitive types, e.g. distinct float or string

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#5983]
Basically in the code below concept is used not to generate 120 candidate operators for each operation +, -, *,dollar and define only one for a concept. Error messages become impossible to read listing 120 candidate procs 

```
import typetraits
const currencies = ["USD", "EUR"] # in real code 120 currencies
type USD* = distinct float # in real code 120 types generates using macro
type EUR* = distinct float

type CurrencyAmount = concept c
  type t = c.type
  const name = c.type.name
  name in currencies

proc `$`(x: CurrencyAmount): string = 
  $float(x) & x.name

let amount = 20.USD
echo amount

```

code fails on float(x) with `Error: type mismatch: got (CurrencyAmount) but expected 'float`

**Comment by Araq** [comment]
Why don't you use something like this instead:

```nim
type
  Currency = enum Usd, Eur, ... # 120 currencies 

  Money[C: Currency; V] = V
```

**Comment by cooldome** [comment]
Mainly because the following doesn't work either:
10.Money[Eur]

and writing Money[Eur](10) is not the usability users expect.

In real code there one more layer that tags money amounts with dates, syntax jitter starts getting annoying rather quickly

**Comment by Araq** [comment]
That's easily solved too though:

```nim
template money(value: typed, t: typedesc): untyped = Money[t](10)

10.money(Eur)
```
