### ISSUE TITLE
Crash with strutils.find in another thread

### ISSUE THREAD

**Issue by tosteram** [nim-lang/Nim#5987]
strutils.find() causes crash when called in another thread in the release mode.
Nim version 0.16.0 and 0.17.0 on Windows 10, 32bit-OS

Here's a sample code:
```
# test_str.nim
import strutils, threadpool

proc myfind(str, sub: string, start:int=0): int=
  let c0= sub[0]
  let fin= str.len-sub.len
  var i= start
  while i<=fin:
    if str[i]==c0:
      var found= true #expected
      for k in 1..<sub.len:
        if sub[k]!=str[i+k]:
          found= false
          break
      if found:
        return i
    inc i
  #end while; not found
  return -1

proc test() : int =
  const s="x1234567"
  echo "test starts"
  let pos= when defined(use_myfind): s.myfind("123")
           else: s.find("123")
  return pos

#---
var fv= spawn test()

const s="abcdefg1234"
let pos= s.find("efg")
echo "in main: ", $pos

echo "from test(): ", ^fv
```
Compile: nim c --threads:on -d:release test_str.nim

However, the program runs normally, when compiled:
  nim c --threads:on test_str.nim
or
  nim c --threads:on -d:release -d:use_myfind test_str.nim

the same issue occurs with strutils.replace(s, sub, by: string)

**Comment by TiberiumN** [comment]
Doesn't happen for me on Windows 10 with Visual studio compiler (vcc)

**Comment by tosteram** [comment]
I'm using mingw-w64, gcc 4.8.2.
Now I compiled with vcc as you did, and you are right.
Maybe this issue has something to do with the gcc compiler (?)

**Comment by TiberiumN** [comment]
@tosteram it doesn't happen to me with mingw-w64 and gcc 4.9.1

**Comment by TiberiumN** [comment]
Version info:
```
C:\Users\Tiberium>gcc -v
Using built-in specs.
COLLECT_GCC=C:\Users\Tiberium\.choosenim\toolchains\mingw32\bin\gcc.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-4.9.1/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw491/i686-491-win32-dwarf-rt_v3-rev1/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=win32 --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw491/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw491/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw491/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw491/prerequisites/i686-w64-mingw32-static --with-cloog=/c/mingw491/prerequisites/i686-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='i686-win32-dwarf-rev1, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw491/i686-491-win32-dwarf-rt_v3-rev1/mingw32/opt/include -I/c/mingw491/prerequisites/i686-zlib-static/include -I/c/mingw491/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw491/i686-491-win32-dwarf-rt_v3-rev1/mingw32/opt/include -I/c/mingw491/prerequisites/i686-zlib-static/include -I/c/mingw491/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw491/i686-491-win32-dwarf-rt_v3-rev1/mingw32/opt/lib -L/c/mingw491/prerequisites/i686-zlib-static/lib -L/c/mingw491/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: win32
gcc version 4.9.1 (i686-win32-dwarf-rev1, Built by MinGW-W64 project)
```

**Comment by tosteram** [comment]
Version info of my gcc:

> C:\Home\progs\Nim>gcc -v
> Reading specs from c:/apps/win-builds-32/bin/../lib/gcc/i686-w64-mingw32/4.8.2/specs
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=c:/apps/win-builds-32/bin/../libexec/gcc/i686-w64-mingw32/4.8.2/lto-wrapper.exe
> Target: i686-w64-mingw32
> Configured with: ../gcc-4.8.2/configure --prefix=/opt/windows_32 --with-sysroot=/opt/windows_32 --libdir=/opt/windows_32/lib --mandir=/opt/windows_32/man --infodir=/opt/windows_32/info --enable-shared --disable-bootstrap --disable-multilib --with-arch=pentium3 --enable-threads --enable-languages=c,c++ --enable-checking=release --with-system-zlib --with-python-dir=/lib/python2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --with-gnu-ld --verbose --enable-java-home --with-java-home=/opt/windows_32/lib/jvm/jre --with-jvm-root-dir=/opt/windows_32/lib/jvm --with-jvm-jar-dir=/opt/windows_32/lib/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar='/root/yypkg_packages/processing/gcc-full/antlr-*.jar' --disable-java-awt --disable-gtktest --build=x86_64-slackware-linux --host=i686-w64-mingw32 --target=i686-w64-mingw32
> Thread model: win32
> gcc version 4.8.2 (GCC)

Mine is v4.8.2. Hm.. I should update the compiler.
