### ISSUE TITLE
Different handling of .emit with and without native debugger

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5989]
Sample:
```nim
proc doSome() =
  var isOk = false
  {.emit: """
#ifndef SOME_MACRODEF
`isOk` = NIM_TRUE;
#endif""".}
  if isOk: echo "OK"

doSome()
```
This compiles fine and outputs `OK` when compiling without `--debugger:native` switch. But if you add the switch, you get:
```
error: expected expression
        nimln_(3, "emittest.nim");      #ifndef SOME_MACRODEF
                                        ^
```
(emit is outputted on the same line with `nimln_`)

Git hash: 0f3e1f17e99fcebdf77fdc837b96c9810b1910bc

**Comment by ringabout** [comment]
Reopen because it is not fixed yet.

**Comment by ringabout** [comment]
use
```nim
proc doSome() =
  var isOk = false
  {.emit: """

#ifndef SOME_MACRODEF
`isOk` = NIM_TRUE;
#endif""".}
  if isOk: echo "OK"

doSome()
```

**Comment by Clyybber** [comment]
Should still work without this workaround IMO

**Comment by ringabout** [comment]
@Clyybber 
It is duplicated of https://github.com/nim-lang/Nim/issues/6345, so I didn't reopen it.

**Comment by ringabout** [comment]
Duplicate of  #6345
