### ISSUE TITLE
variables inside top-level for loops not included in closure environment

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#600]
Variables that occur in for loops outside procedures are not properly included in the environments for closures that need them.

For example, consider the following code:

```nimrod
for i in 1..1:
  var reported = false
  proc report() =
    reported = true
```

The C code for `reported = true` will fail, because `reported` is a local variable of `moduleInit` and cannot be accessed from the function that `report` is compiled to.

**Comment by dom96** [comment]
Fixed as of ``devel``.
