### ISSUE TITLE
Add support for redirecting stdin,stdout, and stderr in osproc.startProcess

### ISSUE THREAD

**Issue by chrisheller** [nim-lang/Nim#6001]
This is to match the functionality that Python's subprocess module supports; being able to supply alternate handles for stdin, stdout, and stderr when starting a child process.

**Comment by chrisheller** [comment]
I used ``getRealHandle`` as the name to match what os.nim uses internally for the ``getFileInfo`` proc,  but sort of implies that the C level file handles are not "real".

**Comment by timotheecour** [comment]
we should close as duplicate of https://github.com/nim-lang/Nim/issues/7999

**Comment by timotheecour** [comment]
closing as duplicate of https://github.com/nim-lang/Nim/issues/7999
