### ISSUE TITLE
Cannot use typedesc parameter in importcpp patterns

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#6029]
Sample:
```nim
proc printTypeName(T: typedesc) {.importcpp: "printf(\"The type is: %s\\n\", \"#\")", header: "cstdio".}
printTypeName(int)
```
Output:
```
The type is: 
```
Expected output:
```
The type is: int
```
Git hash: 5334fd453317fef04ea929fe4a4f4f2e0f6f5dbb

**Comment by andreaferretti** [comment]
Uh? I don't think C++ should know anything of a Nim construct that exists solely at compile time.

I am not sure what oyu are trying to do, but it could make sense to consider the [typetraits](https://nim-lang.org/docs/typetraits.html) module

**Comment by endragor** [comment]
Hmm, in fact this does work:
```
proc printTypeName(T: typedesc) {.importcpp: "printf(\"The type is: %s\\n\", \"'1\")", header: "cstdio".}
printTypeName(int)
```
It outputs `The type is: NI`, so it uses codegenerated name for the type, which makes more sense. So the question is why `#` doesn't work for this case.

**Comment by zah** [comment]
The difference is that `#` refers to the run-time parameters and `typedesc` doesn't create any run-time parameters. `'1` on the other hand refers to the first "generic param" of the function, which happens to be the typedesc param here.

**Comment by endragor** [comment]
Thanks! I think we can conclude there is no bug/problem here.
