### ISSUE TITLE
Remove/deprecate securehash module.

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#6033]
Aside from having a rather underdeveloped interface, the sha-1 hash provided by the securehash module isn't secure at all. If we really need a module providing secure hashing functions, using something from Nimble would be better.

**Comment by andreaferretti** [comment]
I agree. I think for next version, we should look into the stdlib and deprecate a few things that are not well developed (see also https://github.com/nim-lang/Nim/issues/5786 )

**Comment by Araq** [comment]
This module is used by the compiler and was seen as useful enough. It should be named to ``checksum`` though. It's not used for anything security critcial, in fact, it replaced MD5 checksums inside the compiler.

**Comment by yglukhov** [comment]
May I suggest adding some `digest` module that will contain commonly used hashing algorithms? Also  current impl of `securehash` doesn't provide a way to `init/update/complete` hashing context, this should be addressed as well IMO.

**Comment by enthus1ast** [comment]
when i used this unit first i understand the purpose of it like so:
the securehash unit always implements a hash that is claimed to be safe and is updated when the current implementation lost the "secure" status.

Maybe this does makes no sense cause when the hash changes i also maybe have to change code (or configuration of some written code). 

Node.js has a module (forgot the name) that does exactly that, but is also capable of "updateing" saved hashes in connected dbs, after the next login of a user.

**Comment by Araq** [comment]
I think all we need to do for now is to rename it and state clearly it's not part of the stdlib. It's used by the compiler.

**Comment by tankfeeder** [comment]
I've already implement a lot of crypto functions with test vectors on PicoLisp (including all SHA3 finalists):
https://bitbucket.org/mihailp/tankfeeder/src/default/crypto/

This is my blake2b implementation as warm up:
https://bitbucket.org/mihailp/blake2/src

If somebody will write code i will help with implementation and tests if will be required.

**Comment by dom96** [comment]
If it's not part of the stdlib then it should be moved out of the stdlib and into the compiler.
