### ISSUE TITLE
Nim compiler generates variables for discarded proc return values

### ISSUE THREAD

**Issue by noxpo** [nim-lang/Nim#6037]
Both the C and C++ backends generate code with variables defined and assigned for discarded return values of proc calls.
The last statement of this:
```Nim
proc said(s: string): string =
  result = s
  echo s

discard said("Hi")
```
becomes this:
```C
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = said_405dVsq9bxHSpYc3Cn25Clg(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_2));
```
Wouldn't a cast with `(void)` for C and `static_cast<void>()` for C++ be better?

**Comment by Araq** [comment]
The C optimizer optimizes it away anyway.

**Comment by noxpo** [comment]
Yes, but I wrapped a C++ class which has no default constructor, and now the C++ compiler slaps me because it cannot initialize these pointless variables...

**Comment by Araq** [comment]
Ah, good point.
