### ISSUE TITLE
proc `defaultSize=`*(self: Window; width: int; height: int) =

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6038]
Not really a bug, but maybe some inconsistency.

```nim
proc setDefaultSize*(self: Window; width: int; height: int) =
  gtk_window_set_default_size(cast[ptr Window00](self.impl), int32(width), int32(height))

proc `defaultSize=`*(self: Window; width: int; height: int) =
  gtk_window_set_default_size(cast[ptr Window00](self.impl), int32(width), int32(height))
```

Seems that the second proc compiles fine. But

```nim
myWin.defaultSize = (200, 200)
```
what is the intended use case does not work. Well

```nim
myWin.`defaultSize=`(200, 200)
```

may work, but makes no sense. So when tuple assignment is not possible, then the compiler should complain when proc name ends with "=" and there are more than 2 proc arguments.

**Comment by Araq** [comment]
I don't see any inconsistency.

```nim

proc `defaultSize=`*(self: Window; dim: tuple[width: int; height: int]) =
  gtk_window_set_default_size(cast[ptr Window00](self.impl), int32(dim[0]), int32(dim[1]))

myWin.defaultSize = (200, 200)
```

**Comment by StefanSalewski** [comment]
Ah yes, that notation is indeed possible and useful. I guess it will be not easy to generate it automatically by gobject-introspection, but I can provide it at least for this proc manually.

Will close this issue, thanks.
