### ISSUE TITLE
[Feature] Qt support

### ISSUE THREAD

**Issue by ShalokShalom** [nim-lang/Nim#6043]
Hi there :) 

I am new to the community and found in Nim a solution 

Now, i think the only thing missing is Qt support. OK, a little bit effort from my side to learn the language as well :P 

Qt offers a couple of benefits, first of all its very easy and widespread. :)
I think these both projects combined can offer such a easy access to low level performance and quick results, that it will be a joy to develop. I see, there are already C++ Wrappers 

 Both, KDE Librarys and Qt is written in C++ as well and Nim can compiles into it, so i think its the perfect team. Qt itself is the largest open source toolkit and also the prefered framework for a lot of C++ developers. 

QML is a very easy modeling language for designing GUIs. So it might be also nice to combine Nim with that one

**Comment by dom96** [comment]
Like I said, if you want Qt then implement it :)

This issue tracker isn't the right place to request such things so I will close this.

**Comment by bluenote10** [comment]
Does [that](https://github.com/rgv151/qml.nim) help?

**Comment by ShalokShalom** [comment]
Thanks a lot. I will put this on the Qt documentation, if possible.

**Comment by FedericoCeratto** [comment]
See https://github.com/nim-lang/needed-libraries/issues/14 instead
