### ISSUE TITLE
Sample code from tutorial does not compile with 'undeclared identifier' error

### ISSUE THREAD

**Issue by nonylene** [nim-lang/Nim#6044]
I'm learning nim with tutorial.

A sample code shown in ["Method call syntax" section in tutorial 2](https://nim-lang.org/docs/tut2.html#object-oriented-programming-method-call-syntax) does not compile.

## Environment

- mac OS X 10.11.6

I installed with brew.

```
$ nim --version
Nim Compiler Version 0.17.0 (2017-05-18) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```

## Code

- hello.nim

```
echo {'a', 'b', 'c'}.card
```

## Compile result

```sh
$ nim c -r hello.nim
Hint: used config file '/usr/local/Cellar/nim/0.17.0/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: hello [Processing]
hello.nim(1, 6) Warning: a [b] will be parsed as command syntax; spacing is deprecated [Deprecated]
hello.nim(1, 6) Error: undeclared identifier: '{}'
```

This statement seems to be from https://github.com/nim-lang/Nim/blob/86c73cd/doc/tut2.rst#L209.

`echo ({'a', 'b', 'c'}.card)` works well and outputs `3`.

**Comment by genotrance** [comment]
`echo ({'a', 'b', 'c'}.card)` still gives the deprecated error. We could either do one of the following, unless there's other options.

```nim
var v = {'a', 'b', 'c'}.card
echo v
```

OR

`{'a', 'b', 'c'}.card.echo`

**Comment by Araq** [comment]
The snippet that works both for old and upcoming Nims is: 

```nim
echo({'a', 'b', 'c'}.card)
```
