### ISSUE TITLE
Strange behaviour when importing `locks` for use in a generic type

### ISSUE THREAD

**Issue by mathsaey** [nim-lang/Nim#6049]
Using `withLock` seems to lead to some strange behavior when the lock in question is a field of a generic type defined in another module. It's easiest to show this with an example:

Module `lib.nim`:
```
import locks

type MyType* [T] = object
  lock: Lock

proc createMyType*[T]: MyType[T] =
  initLock(result.lock)

proc use* (m: var MyType): int =
  withLock m.lock:
    result = 3
```

In another module (`mod.nim`):

```
import lib

var m = createMyType[int]()
echo $m.use()
```

Compiling `mod` now leads to the following error:

```
mod.nim(4, 8) template/generic instantiation from here
lib.nim(10, 12) template/generic instantiation from here
lib/core/locks.nim(62, 4) Error: attempting to call undeclared routine: 'acquire'
```
importing the `locks` module in `mod.nim` solves this issue.

The workaround is fairly easy, but I figured I should report this anyway, since it doesn't seem like this should be the case. It's also not trivial to figure out that you need to import locks in the `mod` module.

**Comment by andreaferretti** [comment]
Doesn't look like a bug. `withLock` is a template which just wraps the body with calls to `acquire` and `release`, hence these must be in scope.

It is a tricky thing which may be confusing for beginners - a similar example would be a module returning a table (if you try to print it, you need to `import tables`) - but I am not sure what would be a solution

**Comment by Araq** [comment]
well ``withLock`` could capture ``acquire`` and ``release`` properly, so it's just a stdlib issue.

**Comment by mathsaey** [comment]
`withLock` is only used in `lib.nim`, where `acquire` and `release` are both in scope. As far as I know, the lock is never even visible from `mod.nim`, so requiring the user to `import locks` breaks encapsulation at the very least.

**Comment by andreaferretti** [comment]
Sorry, you are both right, I had misread the example. That would break encapsulation indeed. I somehow thought that `use` was a template

**Comment by jangko** [comment]
a quick fix in locks.nim:
add this line:  `mixin acquire, release`

```nim
template withLock*(a: Lock, body: untyped) =
  ## Acquires the given lock, executes the statements in body and
  ## releases the lock after the statements finish executing.
  mixin acquire, release # add this line
  a.acquire()
  {.locks: [a].}:
    try:
      body
    finally:
      a.release()
```

**Comment by mathsaey** [comment]
Why does `mixin` need to be used instead of `bind`? 

> The bind statement is the counterpart to the mixin statement. It can be used to explicitly declare identifiers that should be bound early (i.e. the identifiers should be looked up in the scope of the template/generic definition)
> ...
> But a bind is rarely useful because symbol binding from the definition scope is the default. 

Given that documentation, I would assume that `bind` is the correct fix for this. (I know it doesn't work while `mixin` does, I'm just wondering why.

Furthermore, is there any documentation about when a template/generic is instantiated at callsite, and when it's instantiated at "use" site? It doesn't seem immediately obvious.

Finally, is it worth creating a pull request that adds the `mixin` to `withLock`? I can create it later if it is.

**Comment by Araq** [comment]
``bind`` should work here too (please check!) but perhaps it's better to make ``withLock`` work with any type that supports ``acquire`` and ``release``.

**Comment by mathsaey** [comment]
It doesn't work with `bind` in the latest devel.

Do you mean `template withLock*[T](a: T, body: untyped) = ...`? I would not mind adding it, but `withLock` seems kind of a misnomer in that case.
