### ISSUE TITLE
SIGSEGV when generic is a type named after a module

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#6052]
Test
````nim
# A.nim
type A* = object
# B.nim
import A
var s = newSeq[A]()
# var s: seq[A] = @[] # It works
````
Result: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`
No issue if `A` is used outside a generic context
* * *
````nim
>nim -v
Nim Compiler Version 0.17.1 (2017-07-04) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 9e12db445959ce7c791ec7480ea08e9e02f96bba
active boot switches: -d:release
````

**Comment by andreaferretti** [comment]
I think the issue has to do with the fact that the module itself is called `A`. If you call it something else, the error disappears

**Comment by krux02** [comment]
The example does not compile in current Nim, it results in an error message. The issue about a crash is resolved by now though

**Comment by Clyybber** [comment]
Shouldn't it just work though?
