### ISSUE TITLE
Nim Tutorial (Part I) need update

### ISSUE THREAD

**Issue by soul916** [nim-lang/Nim#6062]
In Nim Tutorial (Part I) Tuple Section has wrong description:

```
Tuple unpacking only works in var or let blocks. The following code won't compile:

import os
var
  path = "usr/local/nimc.html"
  dir, name, ext = ""
(dir, name, ext) = splitFile(path) # --> Error: '(dir, name, ext)' cannot be assigned to
```

But below code work correctly in nim v0.17.0:
```
import os
var dir,name,ext = ""
(dir,name,ext) = split_file("/tmp/a/b/c/d.x")
echo dir, " ", name, " ", ext
```

**Comment by Araq** [comment]
Yes indeed, this feature came later. This remark should just be removed from the docs.

**Comment by dom96** [comment]
A [PR](https://help.github.com/articles/about-pull-requests/) would be nice for these types of things.
