### ISSUE TITLE
Module nimscript, docu bug, ScriptMode = enum

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6065]
https://nim-lang.org/docs/nimscript.html

ScriptMode = enum

That enum is pure! Not visible from docs, and hard to guess as main dev generally do not like pure enums. I tried to use "mode = Whatis" which fails. Should be "mode = ScriptMode.Whatis" I guess, but have not tested yet.

**Comment by Araq** [comment]
Well ``mode = ScriptMode.Whatis`` now works and the two different enum kinds are to be merged. So I think it's fair to close this one.
