### ISSUE TITLE
paramCount() / paramStr(int) either buggy or misnamed

### ISSUE THREAD

**Issue by noxpo** [nim-lang/Nim#6066]
As can be seen from the fact that parameters are numbered starting from 0, but ```paramStr(paramCount())``` returns the last param instead of exploding. If this behavior is intended, stating that what you get from paramStr(0) is not a parameter but the command name, it is confusing as hell.

**Comment by Araq** [comment]
The docs need to be improved but these procs work as designed.

**Comment by StefanSalewski** [comment]
>is confusing as hell.

I don't think so. When I am not totally wrong it works like in many other languages. If your program has one parameter, then paramCount is 1, and paramStr(1) gives that parameter. paramStr(0) is just one ADDITIONAL option to get the executable name, which can be useful. Maybe there should be, or maybe there is an alias for this, like getProgName()?

**Comment by Araq** [comment]
> Maybe there should be, or maybe there is an alias for this, like getProgName()?

There is ``os.getAppDir`` and ``os.getAppFilename`` which actually work better than paramStr(0). ;-)

**Comment by Araq** [comment]
from https://nim-lang.org/docs/os.html#paramStr,int

"i should be in the range 1..paramCount(),"

the docs are fine.

**Comment by noxpo** [comment]
> When I am not totally wrong it works like in many other languages.
The difference to C's argv and argc is that argc is the total number of entries in argv, **including** the program name, which is accessed as "argument zero" with ```argv[0]```. paramCount() gives me the number of actual parameters, **excluding** the program name, but still letting me access the latter as "parameter zero" with ```paramStr(0)```. That seemed inconsequential to me, but since it is documented behavior, I will happily live with it :)
