### ISSUE TITLE
Invalid indentation in type decl. with generic + pragma

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6072]
The following produces `invalid indentation` error

```Nim
type
  Node[T] = ref NodeObj[T]
  NodeObj[T] {.acyclic, final.} = object
    left, right: Node[T]
    data: string
```

Removing either [T] or the pragma works.

This is important to use the {.explain.} pragma for concepts like `Container[T]`

**Comment by Araq** [comment]
The correct syntax is

```nim
type
  Node[T] = ref NodeObj[T]
  NodeObj {.acyclic, final.} [T] = object
    left, right: Node[T]
    data: string
```

**Comment by mratsim** [comment]
Wow, I would never have guessed that.

I think the current syntax is unintuitive as in all other cases the generic is directly after the function/type name and the pragmas are just before the `=` sign.

**Comment by narimiran** [comment]
This has been fixed in the mean time, and the unintuitive syntax (`NodeObj {.acyclic, final.} [T] = object`) is now deprecated in favour of `NodeObj[T] {.acyclic, final.} = object`.
