### ISSUE TITLE
except in export has no effect, contrary to docs

### ISSUE THREAD

**Issue by Serenitor** [nim-lang/Nim#6074]
From the docs:
https://nim-lang.org/docs/macros.html#statements-export-statement
`export math except pow # we're going to implement our own exponentiation`

I can't get this to work for me though.

**module_a.nim**
```
import tables except `[]`
export tables except `[]`

# custom table accessor
proc `[]`* [A, B](table: var Table[A, B], key: A): var B = table[key]
```

**module_b.nim**
```
import module_a

var test = initTable[string, int]()
test["hey"] = 22
echo test["hey"]
```

yields:
> Error: ambiguous call; both tables.[](t: var Table[[].A, [].B], key: A) and module_a.[](table: var Table[[].KeyType, [].ValType], key: KeyType) match for: (Table[system.string, system.int], string)

**Comment by GULPF** [comment]
This has been fixed now.
