### ISSUE TITLE
Type inference failing for case as expression with raise as default case

### ISSUE THREAD

**Issue by Victorious3** [nim-lang/Nim#6101]
The following code fails with
```
expression 'case foo
of 10: 20
else:
raise
var e1109813: ref ValueError
new(e1109813)
e1109813.msg = "Duh?"
e1109813.parent = nil
e1109813' has no type (or is ambiguous)
```

```nim
  let foo = 5
  let bar: int = case foo
  of 10: 20
  else: raise newException(ValueError, "Duh?")
```

My guess is that it can't deduce the type because it's only looking at the default value. To me this looks like a valid case expression (the same works in scala without a problem), but if it isn't then the error message is misleading at best.

**Comment by Araq** [comment]
``raise`` has the type ``void`` and so the above is invalid Nim code. I agree the error message could be better.

**Comment by Victorious3** [comment]
@Araq Well, allowing a throw in the default case would spare me a bunch of assignments so as far as I'm concerned, it's a valid usecase. It's a fairly common pattern.
The other option would be to return some sort of dummy value and then check for that later (and raise the exception) but that's not ideal at all.

**Comment by andreaferretti** [comment]
I agree: in any case, there should be a way to express a switch where some "impossible" cases are considered (the compiler forces you too) but explicitly marked as errors

**Comment by Araq** [comment]
This is supported in later versions of Nim.
