### ISSUE TITLE
Type inference failing for nested generics and proc types

### ISSUE THREAD

**Issue by Victorious3** [nim-lang/Nim#6104]
```nim
import typetraits

type ProcType = proc(i: int): int
proc a(i: int): int = i
proc b(i: int): int = i

let l1: ProcType = a # Works as expected
let l2 = a

# type mismatch: got (array[0..1, proc (i: int): int{.noSideEffect, gcsafe, locks: 0.}]) but expected 'array[0..1, ProcType]'
let l3: array[2, ProcType] = [a, b] 
let l4: array[2, ProcType] = [ProcType(a), ProcType(b)] # This is the workaround I ended up using

# type mismatch: got (array[0..1, proc (i: int): int{.noSideEffect, gcsafe, locks: 0.}]) but expected 'array[0..1, proc (i: int): int{.closure, noSideEffect, gcsafe, locks: 0.}]'
let l5: array[0..1, proc (i: int): int{.noSideEffect, gcsafe, locks: 0.}] = [a, b]

# What type is l6 ?!
let l6 = [a, b]

static:
  echo l6.type.name # array[0..1, proc (i: int): int{.noSideEffect, gcsafe, locks: 0.}]
```

The background to this is that I had a static table of procs and I wanted to make sure that I could only insert procs matching my proc type to it.

**Comment by Araq** [comment]
No bug here, it's just that you don't know about ``.nimcall`` vs. ``.closure`` calling conventions and the fact that implicit type conversions are not lifted to array types (which is true for every programming language I'm aware of).

**Comment by Victorious3** [comment]
Then how do I do the equivalent?
In C I can create an array of function pointers with a typedef.

**Comment by mratsim** [comment]
@Victorious3 I think just noSideEffect is enough, cf my [nim-rmad](https://github.com/mratsim/nim-rmad/blob/master/src/autograd.nim#L52) library.
