### ISSUE TITLE
Nim Tutorial doc bugs

### ISSUE THREAD

**Issue by mooskagh** [nim-lang/Nim#6125]
1. "discard-statement" link in ["comments"](https://nim-lang.org/docs/tut1.html#lexical-elements-comments) section leads to non-existing "#discard-statement", show lead to "#procedures-discard-statement"

1. In ["For statement"](https://nim-lang.org/docs/tut1.html#control-flow-statements-for-statement) section there is "The built-in $ operator turns an integer..." text, yet there's no context for it. No uses of $ in examples around that place.

1.  In ["When statement"](https://nim-lang.org/docs/tut1.html#control-flow-statements-when-statement) section, it says "it is often better to use a when false: statement than to use real comments. This way nesting is possible.". But with multiline real comments nesting is also possible, so that doesn't sound like a valid reason.

1. in ["Properties"](https://nim-lang.org/docs/tut2.html#object-oriented-programming-properties) section the first code snippet doesn't indicate that the last three lines are from different module. Otherwise (from within the same module) the last line "s.host = 34" wouldn't call the property and would be a direct assignment instead,

**Comment by filcuc** [comment]
Lmvc
