### ISSUE TITLE
koch boot fails on Raspberry Pi 3 running Raspbian

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#6130]
When running `./koch boot` on my Raspberry Pi 3 (ARM architecture), the nim compiler fails critically in the first iteration

```
pi@raspberrypi:/usr/local/src/Nim $ sudo ./koch boot -d:release
iteration: 1
compiler/nim0 c -d:release --nimcache:nimcache/r_linux_arm compiler/nim.nim
Hint: used config file '/usr/local/src/Nim/config/nim.cfg' [Conf]
Hint: used config file '/usr/local/src/Nim/compiler/nim.cfg' [Conf]
Hint: system [Processing]
Hint: nim [Processing]
--- Skipping unrelevant lines ---
Hint: scriptconfig [Processing]
CC: compiler_nim
Error: invocation of external compiler program failed. Cannot allocate memory 12
FAILURE
```

**Comment by TiberiumN** [comment]
Can you try to close all other applications, desktop managers etc?

**Comment by couven92** [comment]
@TiberiumN well that got me further: now it failed at:
```
CC: compiler_importer
Error: invocation of external compiler program failed. Cannot allocate memory 12
FAILURE
```

**Comment by TiberiumN** [comment]
@couven92 you can make swap file bigger, and it will compile (but will take some time)

**Comment by dom96** [comment]
Yeah, you need a swap file. Nim is running out of memory.

**Comment by yglukhov** [comment]
Besides the suggested workarounds, I think Nim should really behave better in regards to memory consumption, given that Nim advertises itself as "systems" language. Related: https://github.com/nim-lang/Nim/issues/5375, https://github.com/nim-lang/Nim/issues/6031, https://github.com/nim-lang/Nim/issues/6031.

**Comment by dom96** [comment]
I think it's fair to require more than 1GB of ram for bootstrapping.

**Comment by TiberiumN** [comment]
Yeah, probably for 1.0 we need to provide binary releases to most popular supported platforms (linux 32/64bits and also arm, windows, mac os).


If you try to bootstrap "gcc", I think it would require much memory too

**Comment by couven92** [comment]
Well, for release builds for vanilla latest version, the `build.sh` from [`csources`](https://github.com/nim-lang/csources) works fine

**Comment by dom96** [comment]
I don't think this is a Nim issue, you just need to create swap on your RPi. Closing.
