### ISSUE TITLE
Unused imports still increase binary size

### ISSUE THREAD

**Issue by lbmn** [nim-lang/Nim#6134]
As first [mentioned on the forum](https://forum.nim-lang.org/t/3061): it seems that adding superfluous **import**s from which nothing gets used increases the final binary size despite ``--deadCodeElim:on`` / ``{.deadCodeElim: on.}`` .  **This is by no means a priority issue, just an answer to the question on the forum.**

Simply appending an unused import nearly doubles the size of a simple "hello world" program.  Screenshot using using Nim 0.17.0 on Ubuntu 17.04, and my stupid old [nimr](https://gist.github.com/lbmn/ce65093a2d10dcd47be84bb4652bacfd) tool (which, when run as ``nims``, s being for small, uses ``--d:release --opt:size`` and then the [UPX](https://en.wikipedia.org/wiki/UPX) v3.91 binary compression tool):

![20170723-090450](http://libman.org/img/scr/20170723-090450.png)

I then wrote [a little shell script](https://gist.github.com/lbmn/4a687dca0c939b505b8f9107879af07f#file-nimbinsizetest-sh) to see which stdlib modules have this impact.  Here's [a link to the (cleaned up) output](https://gist.github.com/lbmn/4a687dca0c939b505b8f9107879af07f#file-nimbinsizetest-output) on my machine. 

Adding a superfluous ``import`` to a Nim program always (except for the ``system`` module) adds a little to the binary size, with both GCC 6.3.0 and Clang 4.0.  It's usually under a couple KB per module, but sometimes as much as 37 KB.  With GCC, using UPX nullifies this effect for the vast majority of stdlib modules, but not all of them.  With Clang, using UPX results in greater shrinkage rate, but it never fully hits the same size as without the unused import.

(EDIT: moved the shell script and its output to a link.  Sorry, I suddenly had to run AFK and initially submitted this text with some mistakes.)

**Comment by jangko** [comment]
something like `import strutils` indeed generate some bloat code.
when I take a look at generated C code for main module, it contains comething like:

```C
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
}```

even though those xxxinit000 itself do nothing. and because of this, the linker cannot eliminate them.
