### ISSUE TITLE
odd TimeInterval behavior

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6135]
toTimeInterval(fromSeconds(0)) returns `(milliseconds: 0, seconds: 0, minutes: 0, hours: 0, days: 3, months: 0, years: 1970)` using Nim 0.17 and 0.16 on 23 Jul 2017

[tio.run example](https://tio.run/##y8vM/f8/M7cgv6hEoSQzN7WYKzU5I1@hJD8EyPHMK0ktKkvM0Ugrys8NTk3Oz0sp1jDQ1Pz/HwA "Nim – Try It Online")

There's no documentation on the expected behavior (e.g. should it return the interval between now and 1 Jan 1979?)

**Comment by dom96** [comment]
I think this makes sense. You should diff two `Time`s in most circumstances which would give an expected result.

Documentation is always in need of improvement though :)
