### ISSUE TITLE
Could we change {.noSideEffect.} to {.pure.}?

### ISSUE THREAD

**Issue by Zac-Garby** [nim-lang/Nim#6146]
The pragma `noSideEffect` seems a little long winded. Would it be possible to change this, or add an alias, called `pure`, since they basically mean the same thing?

**Comment by baabelfish** [comment]
https://nim-lang.org/docs/manual.html#pragmas-nosideeffect-pragma

**Comment by TiberiumN** [comment]
So @baabelfish means that "func" may become a default keyword for funcs

**Comment by Zac-Garby** [comment]
Oh, that'd be good - thanks :)
