### ISSUE TITLE
nimble and koch executables in win32 distribution are x64, not x86

### ISSUE THREAD

**Issue by stpettersens** [nim-lang/Nim#6147]
Hi.

I wanted to install the *winregistry* module, but I cannot run nimble on my 32-bit system as the `nimble` executable included  is not 32-bit, but 64-bit.

Surely this is a mistake. 

Thanks. Otherwise, I'm liking Nim so far; seems promising for some projects I'm going to try.

**Comment by dom96** [comment]
You may have better luck using [choosenim](https://github.com/dom96/choosenim) for installation :)

**Comment by stpettersens** [comment]
Thanks. Will try it.

**Comment by Araq** [comment]
Duplicate of #6028.
