### ISSUE TITLE
app crash & no show traceback in windows

### ISSUE THREAD

**Issue by ga1axy** [nim-lang/Nim#6150]
```nim
import net, threadpool

proc send_packet(ipaddr: string): int {.thread.} =
  var socket = newSocket(sockType = SOCK_DGRAM, protocol = IPPROTO_UDP)
  result = socket.sendTo(ipaddr, Port(9999), "packet")


echo ^spawn(send_packet("127.0.0.1"))

var ipaddr: string
echo ^spawn(send_packet(ipaddr))
```

Windows 10:
```
Hint: C:\nim\test_spawn.exe  [Exec]
6
Error: execution of an external program failed: 'C:\nim\test_spawn.exe '

$ nim -v
Nim Compiler Version 0.17.0 (2017-05-18) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
active boot switches: -d:release

$
```

Linux:
```
Hint: /home/ga1axy/nim/test_spawn  [Exec]
6
Traceback (most recent call last)
threadpool.nim(329)      slave
test_spawn.nim(12)       send_packetWrapper
test_spawn.nim(6)        send_packet
net.nim(1370)            sendTo
net.nim(1348)            sendTo
nativesockets.nim(239)   getAddrInfo
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/ga1axy/nim/test_spawn '
ga1axy@rvr ~/nim $ nim -v
Nim Compiler Version 0.17.0 (2017-06-01) [Linux: arm]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release
ga1axy@rvr ~/nim $
```

**Comment by TiberiumN** [comment]
because your second code block uses uninitialized ipaddr variable

_Отправлено с моего Xiaomi Redmi 4 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ga1axy** [comment]
sorry english.

i understand.
why no show traceback?
and show application error popup?

**Comment by TiberiumN** [comment]
@ga1axy about error popup:
Nim only showes errors as pop-ups of application is compiled with --app:gui on Windows

_Отправлено с моего Xiaomi Redmi 4 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ga1axy** [comment]
no show traceback!
show! [http://imgur.com/a/p4TPO](http://imgur.com/a/p4TPO)

**Comment by TiberiumN** [comment]
@ga1axy well, you need to launch it from console

**Comment by ga1axy** [comment]
i launch console.

> nim c -r --threads:on test_spawn

**Comment by dom96** [comment]
This is mostly Windows' fault, and there is no easy way to prevent it. I recall reading an article about it that said there is no fool-proof way to stop showing that GUI dialog.

**Comment by genotrance** [comment]
What's the expected action on this one?
