### ISSUE TITLE
Compilation time slowdown

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#6156]
With the newest devel-branch compiler (0.17.1) compilation seems to take about a hundred times longer, at least in debug mode. Koch's second pass lasts for 20 minutes already and it's still on about a half of the modules list. It's not specific to compiling the compiler, the same with a tineest prigram - just processing `system.nim` takes several minutes. Windows, MinGW 4.9.3.

**Comment by Leu-Gim** [comment]
Still on iteration 2, processing modules, 40 minutes already. It doesn't hang, processed modules' list slowly increases, it consumes 100% of CPU's core and 200MB RAM, free RAM available - nothing unusual except this speed.

**Comment by Leu-Gim** [comment]
Well, it finished (1 iteration), took 45 minutes. It always were just seconds and then MinGW took most of time.

**Comment by Leu-Gim** [comment]
No problem with "-d:release", just a second for processing modules and several seconds for the whole `koch boot`.

**Comment by jangko** [comment]
windows 10-64bit, GCC 7.1.0

devel branch: koch boot
* iteration 1: 14secs - 28 secs
* iteration 2: 2670 secs / 44,5mins
* iteration 3: out of patience

same thing happened with nim 0.17.0
no problem with release mode.

could this be related to appveyor time out? if yes, this is a top priority issue

**Comment by TiberiumN** [comment]
Yeah, it seems this is a high priority issue

**Comment by Leu-Gim** [comment]
@jangko

**Comment by Araq** [comment]
This has been fixed and was the slowdown/timeouts for appveyor too. The only question remains: Was 0.17.0 affected?

**Comment by jangko** [comment]
>  The only question remains: Was 0.17.0 affected?

sorry, it was my mistake to think 0.17.0 also slow. 
0.17.0 is ok
