### ISSUE TITLE
Updating Types at Macro Time

### ISSUE THREAD

**Issue by erhlee-bird** [nim-lang/Nim#6159]
The goal of the compose macro I've written below is to take some of the attribute constraints present in a concept and inject them into another type.

After invoking the compose macro, the A type is successfully made Funky; however, the compiler does not allow access to the truth attribute that should now be present.

<details>
  <summary>Code for the Compose Macro (Click to Expand)</summary>
  <p>

```
import macros

type VisitorProc = proc (node: NimNode): NimNode

proc ast_walk(node: NimNode, visitor: VisitorProc): NimNode =
  ## Use a visitor to walk NimNodes and modify them in-place.
  result = visitor(node)
  for i in 0 .. < result.len:
    result[i] = result[i].astwalk(visitor)

macro compose*(attrs: varargs[typed], body: untyped): typed =
  ## Take a list of concept types and inject the attribute constraints into any
  ## object type definitions provided.
  result = body

  result = result.ast_walk do (node: NimNode) -> NimNode:
    if node.kind == nnkObjectTy:
      node.expectLen(3)
      if node[2].kind == nnkEmpty:
        node[2] = newNimNode(nnkRecList)
    result = node

  # Gather all of the Concept attribute constraints.
  # All of the new attributes to inject.
  var identdefs: seq[NimNode] = @[]
  for attr in attrs:
    attr.expectKind(nnkSym)
    # Look up the provided concept type.
    let lookup = getImpl(symbol(attr))
    lookup.expectKind(nnkTypeDef)
    lookup.expectLen(3)
    let typeclass = lookup[2]
    typeclass.expectKind(nnkTypeClassTy)
    typeclass.expectLen(4)
    typeclass.last.expectKind(nnkStmtList)
    let stmts = typeclass.last
    # Extract any attribute constraints.
    # e.g. x.attribute is bool
    #      Infix(Sym(is),
    #            DotExpr(Sym(k), Ident(!"acceleration")),
    #            Sym(Vector2d))
    for child in stmts:
      if (child.kind != nnkInfix or
          (child[0].kind != nnkSym and $child[0] != "is") or
          child[1].kind != nnkDotExpr or
          child[1][1].kind != nnkIdent or
          child[2].kind != nnkSym):
        continue
      identdefs.add(newIdentDefs(ident($child[1][1]), ident($child[2]),
                                 newEmptyNode()))

  result = result.ast_walk do (node: NimNode) -> NimNode:
    if node.kind == nnkRecList:
      for identdef in identdefs:
        node.add(identdef)
    result = node
```
  </p>
</details>

<p></p>

```
type
  Funky = concept f
    f.truth is bool

compose(Funky):
  type
    A = object of RootObj

type
  B = object of A

echo(A() is Funky)  # true only with 0.17.1, false on the others.
# echo(A().truth)   # Raises a compiler error.
echo(B() is Funky)  # true
```

My expectations/hopes/wildest dreams for the above code would be for A and B to both become Funky and for A to properly expose the injected truth attribute.

Are macro modifications performed at compile time or somewhat after?
By using typed arguments for the macro, is the macro delayed to some time after compile time?

**Comment by Araq** [comment]
> Are macro modifications performed at compile time or somewhat after?

At compile time.

> By using typed arguments for the macro, is the macro delayed to some time after compile time?

'typed' vs 'untyped' is about the question whether the arguments passed to the macro are type checked ('typed') or not ('untyped') but it's all done at compiletime.

**Comment by erhlee-bird** [comment]
I've distilled a much cleaner example of the issue I am working through.
Type definitions seem to get mangled after being processed through a macro.

```
import macros

macro test*(body: untyped): untyped =
  result = body

test:
  type A = object
    attr: bool

echo(A().attr)
```

`test.nim(10, 9) Error: field 'attr' cannot be found`

> Nim Compiler Version 0.17.1 (2017-07-31) [Linux: amd64]
> Copyright (c) 2006-2017 by Andreas Rumpf
> git hash: 3d543b1539f8d5dde5746c90c5de5fa3df1cadfd
> active boot switches: -d:release

> Nim Compiler Version 0.17.0 (2017-05-17) [Linux: amd64]
> Copyright (c) 2006-2017 by Andreas Rumpf
> git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
> active boot switches: -d:release

**Comment by jxy** [comment]
Macro is not really the problem here.  The following code breaks, too.
``` nim
type O=object                                                                                        
  v:bool                                                                                             
echo O().v     # Error: field 'v' cannot be found                                                   
let x=O()      # Name it first,                                                                      
echo x.v       # and it works.
```

@erhlee-bird Rename the issue or submit a new one?

**Comment by erhlee-bird** [comment]
Hey @jxy that actually helps a lot.
I didn't realize that the object needed a binding before allowing access.
Once the bindings are provided, the initial code seems to work.

Thanks for the help.
This issue can be closed.
