### ISSUE TITLE
Nimble list doesnt show in some browsers

### ISSUE THREAD

**Issue by tankfeeder** [nim-lang/Nim#6161]
https://nim-lang.org/docs/lib.html
Nimble list on the bottom

FF stable works
Yandex stable works
IE 11 works
Edge works
Vivaldi dev works

Chrome and Opera stable doesnt work.
I mean this text:
If you are reading this you are missing nimblepkglist.js or have javascript disabled in your browser.

**Comment by TiberiumN** [comment]
Maybe duplicate of https://github.com/nim-lang/Nim/issues/5318 ?

**Comment by dom96** [comment]
#5318 was fixed. This seems to be a new issue.

**Comment by euantorano** [comment]
I can't reproduce this on Chrome stable (`Version 60.0.3112.78 (Official Build) (64-bit)` as of writing). Can you check the developer console to see what error is reported if any (you can open the developer console [as described here](https://developers.google.com/web/tools/chrome-devtools/console/)) and post the error as part of this issue?

**Comment by tankfeeder** [comment]
chrome stable 60.0.3112.78 didnt work, now it works!
i thought somebody fixed it.

and opera stable works too.

**Comment by andreaferretti** [comment]
Works fine for me on FIrefox Ubuntu

**Comment by TiberiumN** [comment]
Works fine for me on Chrome 60.0.3112.90 on Antergos (Arch-based distro)

**Comment by tankfeeder** [comment]
now works everywhere.
