### ISSUE TITLE
times.countLeapYears gives wrong results

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#6178]
```nim
import times

# imho, this would be the correct implementation
proc countLeapYears(yr: int): int =
  (yr - 1) div 4 - (yr - 1) div 100 + (yr - 1) div 400

proc showProblem(fromYr, toYr: int) =
  for yr in fromYr..toYr:
    echo yr, " ", times.countLeapYears(yr), " ", countLeapYears(yr)

# none of 1900, 1901, 1902, 1903 is a leap year
# but times.countLeapYears increments at 1903
showProblem(1900, 1905)
echo ""

# 2004 is a leap year
# but times.countLeapYears increments only after 2005
showProblem(2004, 2006)
echo ""

# same problem as above 
# times.countLeapYears increments too late
showProblem(2020, 2022)
```
Output (the bold values are wrong):
1900 460 460
1901 460 460
1902 460 460
1903 **_461_** 460
1904 **_461_** 460
1905 461 461

2004 485 485
2005 **_485_** 486
2006 486 486

2020 489 489
2021 **_489_** 490
2022 490 490

**Comment by GULPF** [comment]
This is not really a bug. The documentation explains that the proc returns the number of leap days that has passed until Jan 1 of the given year. The current behavior is IMO more useful.

**Comment by skilchen** [comment]
I evidently don't agree with you. The current behavior is wrong according to the documentation. In my understanding of the documentations countLeapYears should increment in every year following a leap year. 
There is no leap day in the years 1900-1903. Why does countLeapYears increment in 1903?
There is a leap day in 2004 (before Jan 1 2005), why is it not counted until Jan 1 2006?
There is a leap day in 2020 (before Jan 1 2021), why is it not counted until Jan 1 2022?
The current behavior is a consequence of the used floating point division and the final truncating to an int, instead of using integer division in every calculation (btw. the C macro from https://www.codeproject.com/Articles/7358/Ultra-fast-Algorithms-for-Working-with-Leap-Years also uses integer division.)

With the current implementation of countLeapYears you get 366 for eg. countDays(2006) - countDays(2005). For me this doesn't make sense.

**Comment by GULPF** [comment]
I'm sorry, you're right. The current implementation is broken.
