### ISSUE TITLE
Type inference bug with typedesc and typedesc[type]

### ISSUE THREAD

**Issue by fy0** [nim-lang/Nim#6183]
Sorry, only some pictures here.
![6c4b243b-7ea8-4757-a61c-044178c7486f](https://user-images.githubusercontent.com/1579850/28968568-268ca6a0-7953-11e7-9a38-47ff63371572.jpg)

Type mismatch, after read document I got typedesc is a special class.
OK, I changed parameter's type to typedesc and it works.

But when I want use typedesc[ClassA] to match the specific class, it crashed.
![87daefe3-c1df-4f74-ae5c-b58c2b9064a2](https://user-images.githubusercontent.com/1579850/28968594-4d942480-7953-11e7-888e-dd28641e79f5.jpg)

P.S.: Document of ImportCpp let me so confused and waste a lot of time. Why not just use a simplest cpp class snippet as example?
P.S.2: Every c++ binding helper library is broken.

**Comment by dom96** [comment]
Please post code as well, not just pictures.

**Comment by fy0** [comment]
```nim
{.compile: "test.cpp"}

const
    hTest = r"test.h"

type
    ClassA {.final, header: hTest, importcpp: "ClassA".} = object
        px: int


proc test(self: ptr ClassA) {.importcpp: "#->test(@)".}
proc cnew(T: typedesc): ptr T {.importcpp: "(new '*0#)", nodecl.}
proc cnew2(T: typedesc[ClassA], x: int): ptr T {.importcpp: "#new '*0#", nodecl.}

var a = ClassA.cnew()
var b = ClassA.cnew(123)

a.test()
b.test()
```

**Comment by genotrance** [comment]
@fy0: please also attach the `test.cpp` and `test.h` files to reproduce this.

**Comment by fy0** [comment]
@genotrance It's a long time ago, I will try to find it. I guess code is very simple.

**Comment by krux02** [comment]
I just tested the example code, this is the output:

```
(px: 21943)
100
123
```

I guess the problem has been resolved.
