### ISSUE TITLE
macro error messages, quote do: and illegal proc names

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6184]
Araq, I think I found the reason for the macro "quote do:" trouble we talk about yesterday. Following code gives this compiler message: bt.nim(18, 77) Error: type expected

That refers to the :bool in line
proc `procName`(self:  `wt`;  p: proc (self: `wt`, cr: Obi; arg: `at`): bool; a: `at`) =

But all compiles file when I do not import gintro!

And it becomes clear when I modify import list:

import gintro/[gio, gtk, gobject, glib, cairo]
#import gintro/gio except Application, newApplication

Compiler message now is nice:

bt.nim(24, 10) Error: type mismatch: got (None) but expected 'bool'

So it is easy to find the reason:

```
stefan@nuc ~/cairo_anim $ grep -A1 "proc false" ~/.nimble/pkgs/gintro-0.1.0/gintro/*.nim
/home/stefan/.nimble/pkgs/gintro-0.1.0/gintro/gtk.nim:proc false*(): gboolean {.
/home/stefan/.nimble/pkgs/gintro-0.1.0/gintro/gtk.nim-    importc: "gtk_false", libprag.}
```
So it is clear that I have to remove the autogenerated proc false from gtk.nim. But the problem is, that it can be really hard to find such type of problems :-( 

```nim
stefan@nuc ~/cairo_anim $ cat bt.nim 
import gintro/[gtk, gobject, glib, cairo]
import gintro/gio except Application, newApplication
import macros
import strutils

type
  Obi = ref object
    i: int

macro drawConnect(widget: Obi; signal: string; p: untyped; arg: typed): typed =
  let wt = getType(widget)
  let at = getType(arg)
  let signalName = ($signal).replace("-", "_")
  let procNameCdecl = newIdentNode("connect_for_signal_cdecl_" & signalName)
  let procName = newIdentNode("connect_for_signal_" & signalName)
  let scName = newIdentNode("sc" & signalName)
  result = quote do:
    proc `procName`(self:  `wt`;  p: proc (self: `wt`, cr: Obi; arg: `at`): bool; a: `at`) =
      when a is RootRef:
        GC_ref(a)

proc drawCB(w: Obi; cr: Obi; arg: int): bool =
  echo "draw"
  return false

proc activate (app: Obi) =
  let button = new Obi
  button.drawconnect("draw",  drawCB, 1)

proc main =
  echo 1

main()

```

**Comment by StefanSalewski** [comment]
Well, the basic problem was indeed:

```
gtk.nim:proc bool*(self: PrintSettings; key: string): bool =
```

With

```
import gintro/gtk except bool
import gintro/gobject except bool
import gintro/glib except bool
import gintro/cairo except bool
import macros
import strutils
import gintro/gio except Application, newApplication, bool
```
all works fine. But it is not easy to find the reason for such trouble.

I had already checked for proc names like int, int64, float and such, but forget filtering for bool and false.

Where can I find a complete list of all these symbols which should not be used for proc names?

**Comment by krux02** [comment]
I think this issue needs to be reformalized if it still matters. I have no idea what is going on.

**Comment by StefanSalewski** [comment]
Oh yes, after nearly two years we should really close this issue. I think the basic issue was that there was a automatically generated proc with name false, which generated problems for some macros. But the compiler has changed since then, so it makes no sense to investigate this issue further, so I will close it now.
