### ISSUE TITLE
Field cannot be found on anonymous instances (rvalues) if field is not initialized

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#6185]
To track the true issue behind https://github.com/nim-lang/Nim/issues/6159

```nimrod
type
  O = object
    x: int
echo O(x: 1).x     # ok
echo O().x         # Error: field 'x' cannot be found
```

Observations:

* The problem extends to multiple fields, i.e., if there is a partial initialization of several fields, only those which are initialized are accessible.
* Note: The error is different from `Error: undeclared field: 'y'` when trying to access a truly non-existing field.

This might be intended behavior, in which case the error message could be more explicit: _Accessing fields on rvalues requires initialization, but field `x` is not initialized._ (Not sure if rvalue is the proper term in Nim terminology)

**Comment by andreaferretti** [comment]
As mentioned by @Quelklef on gitter, this is now fixed
