### ISSUE TITLE
exportc will generate static and non-static declaration for (proc addInt)

### ISSUE THREAD

**Issue by shaoxie1986** [nim-lang/Nim#6188]
I write a test proc to export,just like :
```nim
proc addInt(a, b: int): int {.exportc.} = 
  let c = a + b
  result = c
```

and using: nim c --app:lib test.nim
get the error:
/Users/xxx/project/nim/nimcache/test.c:24:21: error: static declaration of 'addInt' follows non-static declaration
static N_INLINE(NI, addInt)(NI a, NI b);
                    ^
/Users/xxx/project/nim/nimcache/test.c:23:15: note: previous declaration is here
N_NIMCALL(NI, addInt)(NI a, NI b);
              ^
/Users/xxx/project/nim/nimcache/test.c:37:21: error: static declaration of 'addInt' follows non-static declaration
static N_INLINE(NI, addInt)(NI a, NI b) {
                    ^
/Users/xxx/project/nim/nimcache/test.c:23:15: note: previous declaration is here
N_NIMCALL(NI, addInt)(NI a, NI b); 

and the test.c:
```c
23:N_NIMCALL(NI, addInt)(NI a, NI b);
24:static N_INLINE(NI, addInt)(NI a, NI b);
37:static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
```

**Comment by Araq** [comment]
That is not what's happening. What's happening is that you use an extern name that is already taken by Nim.

**Comment by shaoxie1986** [comment]
@Araq How lucky I am.^_^.

**Comment by andreaferretti** [comment]
Maybe there should be an error message for such cases?

**Comment by Araq** [comment]
That's hardly sufficient, in general we don't know which symbols have been #included already.

**Comment by dom96** [comment]
If the error message cannot be improved then feel free to close.

**Comment by narimiran** [comment]
> If the error message cannot be improved then feel free to close.

Can this be (easily) improved? Close?

**Comment by Araq** [comment]
Ideally we would emulate a linking step just to get better error messages. Also the internal Nim symbol should be ``nimAddInt``, but closing as won't fix.
