### ISSUE TITLE
collection types should contain collection kind in the Name for better debugger support.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#6202]
When a pretty printer for gdb is implemented, a regular expression is applied on the type name to decide if the pretty printer can be used for that type or not. When the name of the type would be ``TY_NIMSEQ_[...]`` or something similar, the regular expression could be much more precise.

https://github.com/krux02/opengl-sandbox/blob/master/fancyglpkg/nim-gdb.py#L58

**Comment by Araq** [comment]
This has been implemented.
