### ISSUE TITLE
strutils.formatEng relies on a distinction of "" and nil string

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#6205]
As discussed earlier the nil value strings and seq types should go away. [strutils.formatEng](https://github.com/nim-lang/Nim/blob/devel/lib/pure/strutils.nim#L1995) relies on the distinction of nil strings and empty strings

This causes a problem in this PR: https://github.com/nim-lang/Nim/pull/6206

**Comment by dom96** [comment]
> As discussed earlier the nil value strings and seq types should go away.

Where was this discussed?

**Comment by krux02** [comment]
In the irc chat.

**Comment by dom96** [comment]
A link would be nice, but okay :)

**Comment by krux02** [comment]
Sorry for not putting a link. I know there are irc logs, but I don't have grep access to them.

**Comment by dom96** [comment]
The only distinction I see is with the ``unit`` parameter, is that what you meant? https://github.com/nim-lang/Nim/blob/devel/lib/pure/strutils.nim#L2095

If so then I guess we should be using an ``Option[string]`` for that, fairly trivial change, no?

Unfortunately I think that a lot of code in the wild uses this sort of thing. :\

**Comment by dom96** [comment]
Giving high priority because this is a breaking change.
