### ISSUE TITLE
Stack bottom issues in foreign thread.

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#6208]
Related to discussion in #6182.

Some unexpected/broken behaviour exhibited by the default garbage collector in foreign threads:
1. Variables in stack frame directly containing GC setup (`setupForeignThreadGC`) do not get marked by the GC, and can be prematurely collected!
2. Invoking `setupForeignThreadGC` without tearing down the previous GC does nothing. But this is rather dangerous since the stack bottom pointer continues to point to the previous location. This means that stack variables that are lower than that location are not marked and can be prematurely collected! `setupForeignThreadGC` should either raise an error in this case, or move the pointer down if required (`setStackBottom` seems to include the required mechanics, too).

Here's a small project, illustrating both issues: https://github.com/nigredo-tori/various-examples/tree/master/nim/foreign-stack-bottom

Checked this with Nim 0.17.0 and devel @ Ubuntu 16.04.

**Comment by nigredo-tori** [comment]
The way `setupForeignThreadGC` determines stack size is also flawed. Since stackTrace is enabled in the definition, we have an "invisible" `FR_` local variable, and quite fat one at that. Depending on compiler's ideas on the order the variables should have in stack, we can lose a large chunk as well, leading, again, to premature collection.

**Comment by Araq** [comment]
All not an issue anymore thanks to ORC.
