### ISSUE TITLE
Allow Nimrod build.sh to build relative to any current working directory

### ISSUE THREAD

**Issue by shevegen** [nim-lang/Nim#621]
Hello.

Right now it seems that the script:

build.sh

Requires you to be in the same directory when you wish to invoke it.

For instance:

  sh build.sh

works fine and builds nimrod.

But if you do this here:
  mkdir BUILD
  cd BUILD
  sh ../build.sh

It terminates with an error:

  gcc -w -O3 -fno-strict-aliasing -Ibuild -c build/2_1/nimrod.c -o build/2_1/nimrod.o
  gcc: error: build/2_1/nimrod.c: No such file or directory
  gcc: fatal error: no input files
  compilation terminated.

It seems as if it assumes hardcoded directory paths. In this example, build/
directory is assumed to be in the cwd (current working directory).

I would suggest that the command given to gcc honours the prefix used.

In the above example, when I invoked sh ../build.sh, I gave the information
that could be used in the first argument to sh ("../build.sh") so this information
could be used in build.sh.

The gcc command could then be substituted with:

gcc -w -O3 -fno-strict-aliasing -Ibuild -c ../build/2_1/nimrod.c -o build/2_1/nimrod.o

automatically. (The -o directive could remain as it is, the whole idea behind a 
special build directory is to not tarnish the main extracted directory, although
perhaps for sake of consistency, options to control where the resulting .o 
files are put should also be considered - right now everything seems to be
hardcoded.)

I am not entirely sure how shell scripts take commandline argument (I do not
use shell scripts myself, I switched to .rb files everywhere when I need 
automation).

Why would this be a good improve? I can give you a reason why I wanted 
this initially. I build all my software from source and I use a set of ruby
scripts that compile for me. One of these scripts automatically creates
directories for me where to build in these files (some GNU autoconfigure
projects insist on build-directories, and cmake based projects often
also required special build dirs).

Thanks.

**Comment by andreaferretti** [comment]
I think this can be closed, as Nim is currently built by koch

**Comment by dom96** [comment]
The release tarballs still include this sh file, but I don't think we should implement this. It'll just complicate the script.
