### ISSUE TITLE
Inconsistency in parentheses requirement after echo

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#6210]
Hello,

I was playing the the `join` proc from `strutils`. Here is the test code:

```nim
import strutils
echo "Sequences:"
echo @["a", "b", "c"].join(" ")
echo join(@["a", "b", "c"], " ")
echo "Lists:"
# echo ["a", "b", "c"].join(" ") # Does not work, Error: cannot instantiate: echo["a", "b", "c"]; got 3 type(s) but expected 0
echo (["a", "b", "c"].join(" ")) # Works!
echo join(["a", "b", "c"], " ") # Works!
var list = ["a", "b", "c"]
echo list.join(" ") # Works too!
```

Note that these instances of `echo` work without parentheses:

```nim
echo @["a", "b", "c"].join(" ")
var list = ["a", "b", "c"]
echo list.join(" ")
```

But when I do:

```nim
echo ["a", "b", "c"].join(" ")
```

I get:

> nim_src_28505k2d.nim(10, 6) Warning: a [b] will be parsed as command syntax; spacing is deprecated [Deprecated]
> nim_src_28505k2d.nim(10, 6) Error: cannot instantiate: echo["a", "b", "c"]; got 3 type(s) but expected 0

---

```
> nim --version
Nim Compiler Version 0.17.1 (2017-08-08) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: c406d0b7a7d75793f88a0e560a694b4c4e18a48c
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
I think this is correct - the warning in fact tells you the reason: `echo [1, 2, 3]` it is parsed as `a[b]`. The reason why the other are not parsed like this is - well, because they do not start with a `[`

**Comment by kaushalmodi** [comment]
Sorry, I don't understand the inner workings of Nim. I just started reading Nim In Action this week and am playing with the syntax. 

> echo [1, 2, 3] it is parsed as a[b]

I don't even understand what that warning means. What does "being parsed as a[b]" mean? If parentheses are optional after echo, should this case be handled? Or should the error be more directive for a user : "Don't start an expression starting with [ after echo"?

Also, what's the suggested convention for Nim? Should procedure arguments be always wrapped in parentheses?

Apologies for so many questions... I am just trying to put myself on the right path and I am learning Nim.

**Comment by andreaferretti** [comment]
Well, it is parsed as `[]` access, much like `x[2]` in

```nim
let x = @[1, 2, 3]
echo x[2]
```

It tries to "access the 1, 2, 3 element of the echo value", so to speak

**Comment by kaushalmodi** [comment]
> It tries to "access the 1, 2, 3 element of the echo value", so to speak

Thanks, so should this be fixed? As `echo` is procedure, would it ever be legal to access such elements from a bare procedure identifier?

**Comment by TiberiumN** [comment]
@kaushalmodi it probably can't be fixed since this is a syntax of nim

**Comment by andreaferretti** [comment]
The parser is as context free as possible, so at the moment of parsing it does not know that echo is a procedure. Moreover, you can define our own accessor `[]` on pretty much every type, so I think it could be defined on echo as well

**Comment by Yardanico** [comment]
This was fixed in https://github.com/nim-lang/Nim/commit/ddc131cf07972decc206e033b2dd85a42eb1c98d

**Comment by kaushalmodi** [comment]
Thank you! I confirm the fix!
