### ISSUE TITLE
Cannot write str[1 ..]

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6212]
```nim
var str = "a\tbc\tdef\taghij\tcklm\tdanopqrstuv\tadefwxyz\tzyx"
echo str[1..] # Does not work.. Error: expression expected, but found ']'
```

It would be nice if this was allowed.

**Comment by Araq** [comment]
I don't want postfix operators in Nim and in general you're against syntax additions too :P.

**Comment by dom96** [comment]
Could we create a special case just for this?

**Comment by Araq** [comment]
And how are we gonna support this for overloaded operators? What's the signature of '..' that allows for this? How is it different from 'str[..N]' which would also be a unary '..'?

**Comment by thomassross** [comment]
I like this addition. I would also like if you were able to remove the space while slicing: https://github.com/nim-lang/Nim/issues/4218#issuecomment-222781878

**Comment by kaushalmodi** [comment]
@thomassross There's a bit of inconsistency with when skipping a space after `..` is fine (see https://github.com/nim-lang/Nim/issues/6216). Looks like fixing that inconsistency is not on the highest priority as it affects only "newbies".. I'd just stick with using spaces around `..`, **always**.
