### ISSUE TITLE
Can't use empty sets as tuple field values (unless the set is a var/let value)

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6213]
This code ends up with a type mismatch error according to which myVar's value is of type "seq[tuple[x: set[empty]]]"

```
type MyEnum = enum a, b
type MyTuple = tuple[x: set[MyEnum]]

var myVar: seq[MyTuple] = @[ (x: {}) ]
```

However, using a var/let value works:
```
let emptySet: set[MyEnum] = {}
var myOtherVar: seq[MyTuple] = @[ (x: emptySet) ]
```

**Comment by TiberiumN** [comment]
Probably because compiler can't interfere set type here (for some reason)

**Comment by dom96** [comment]
Yeah, to the compiler the type of `{}` is `set[empty]` which isn't compatible with `set[MyEnum]`.

@Araq is this something we want to support?

**Comment by narimiran** [comment]
> Yeah, to the compiler the type of {} is set[empty] which isn't compatible with set[MyEnum].

So we need to specify the type of the empty set. Should this be closed, or is it something y'all want to work on?

**Comment by Araq** [comment]
No, this needs to be improved.

**Comment by dom96** [comment]
Related problem I just ran into:

```
type
  Foo = tuple
    f: seq[string]
    s: string

proc e(): seq[Foo] =
  return @[
    (@[], "asd")
  ]

echo e()
```

```
a2.nim(7, 10) template/generic instantiation of `@` from here
/Users/dom/projects/nim/lib/system.nim(1380, 19) Error: invalid type: 'empty' in this context: 'proc (a: array[0..0, tuple of (seq[empty], string)]): seq[tuple of (seq[empty], string)]{.noSideEffect.}' for proc
```
