### ISSUE TITLE
"..<" shortcut template does not work when declaring fixed length array

### ISSUE THREAD

**Issue by Smaehtin** [nim-lang/Nim#6215]
```nim
var stuff: array[0..<1024, int]
```

Failes to compile with:

`test.nim(2, 19) Error: ordinal type expected`

**Comment by dom96** [comment]
Probably because of the way the `..<` is defined. It works if you add a space after the `..`. Sounds like a possibly easy issue to fix.

**Comment by kaushalmodi** [comment]
As discussed in the above referenced issue, it would be better to always uses a space after the `..` operator to avoid surprises.

**Comment by dom96** [comment]
Indeed. You should put a space before and after the `..`.

**Comment by narimiran** [comment]
> Indeed. You should put a space before and after the `..`

```nim
var stuff: array[0 .. <1024, int]
```
works, but it raises `Warning: < is deprecated [Deprecated]`.

---

Using `..<` with spaces around it (this is the usual way to declare excluding range, right?): 
```
var stuff: array[0 ..< 1024, int]
```
raises the same thing as in OP: `Error: ordinal type expected`

**Comment by dom96** [comment]
My advice is outdated. It seems @GULPF's observations are correct.

**Comment by kaushalmodi** [comment]
This came up in the forum today: https://forum.nim-lang.org/t/4130.

**Comment by dom96** [comment]
This also came up in https://youtu.be/IGTuv_KKLFs?t=6950.
