### ISSUE TITLE
mingw package on website is missing a header

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6219]
https://github.com/dom96/choosenim/issues/24#issuecomment-312877750

``sec_api/wchar_s.h``

**Comment by Araq** [comment]
I checked both ``.7z`` packages from https://nim-lang.org/install_windows.html

These both contain: 

mingw64\x86_64-w64-mingw32\include\sec_api\wchar_s.h

Maybe choosenim has to install MingW like my ``finish.exe`` does?

**Comment by dom96** [comment]
@JorySchossau Any thoughts?

**Comment by JorySchossau** [comment]
The packages took to be updated, even the nim-lang.org/downloads/mingw32.7z which did not originally have these headers. wchar_s.h is present and the cpp biulds work just fine. The choosenim installation for windows also works. All is well!

**Comment by dom96** [comment]
Interesting. But since it's there now we can close this :)
