### ISSUE TITLE
Update Debian/Ubuntu Repository

### ISSUE THREAD

**Issue by codenoid** [nim-lang/Nim#6221]
*very simple and easy way to install nim

**Comment by dom96** [comment]
huh? What does this mean? Update the package for Nim?

**Comment by codenoid** [comment]
yup, current version is `0.12.0`

**Comment by TiberiumN** [comment]
@codenoid you're wrong?
https://launchpad.net/ubuntu/+source/nim
0.17.0 here

**Comment by TiberiumN** [comment]
@codenoid also packages are not maintained by Nim creators, they're maintained by other users

**Comment by TiberiumN** [comment]
@codenoid 0.17.0 here too - https://packages.debian.org/search?keywords=nim

**Comment by dom96** [comment]
Yeah. @FedericoCeratto is the maintainer and AFAIK he always keeps the packages up to date. Maybe your distro is behind the times?

**Comment by FedericoCeratto** [comment]
@codenoid  perhaps you are using xenial? https://packages.ubuntu.com/search?keywords=nim

**Comment by TiberiumN** [comment]
@codenoid what happened?

**Comment by codenoid** [comment]
i cant install it from launchpad

**Comment by TiberiumN** [comment]
@codenoid you need to download Nim .deb package from launchpad

**Comment by codenoid** [comment]
```
Nim Compiler Version 0.17.0 (2017-05-17) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
active boot switches: -d:release
```

**Comment by shulhi** [comment]
@codenoid how do you install it? Can't find the deb package in launchpad.

**Comment by codenoid** [comment]
@shulhi from .tar.xz ^^

**Comment by shulhi** [comment]
@codenoid ok got it, but that's more like building from source.
