### ISSUE TITLE
Migrate parts of the stdlib to babel

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#623]
As per discussion on [IRC](http://build.nimrod-code.org/irclogs/12-10-2013.html) parts of the stdlib should be moved to babel now that it is fairly stable and babel v0.1 is right around the corner.

Current decisions of what should be kept and what shouldn't follow:

### Migrate into babel

- [x] Wrappers
  - [x] gtk2
  - [x] windows
  - [x] x11
  - [x] opengl
  - [x] sdl
  - [x] cairo
  - [x] lua
  - [x] libcurl
  * **Exceptions**: Any wrapper which is a dependency for modules in the ``impure`` directory, e.g. pcre. posix.nim must also stay.
- [ ] "Unknown stuff like **subexes**"
- [ ] romans
- [ ] xmldom & xmldomparser
- [x] dialogs.nim
- [x] osinfo*

### Stay in stdlib
* Sockets & asyncio
* cookies.nim
* httpserver, httpclient, ftpclient, scgi. Collectively known as the "web stuff"
* db_*

**Comment by EXetoC** [comment]
What about the async stuff for example? But then it seems essential to have a metapackage with those libs as dependencies.

**Comment by Varriount** [comment]
The async modules are considered a core part of the language

**Comment by EXetoC** [comment]
It would be trivial to install them though.

**Comment by dom96** [comment]
It would be trivial to install all things. Should move the whole stdlib to Nimble?

**Comment by dom96** [comment]
@Araq Why the decision to put some of the packages in your account vs. nim-lang?

In any case, please finish this off and mark the ones that you do off.

**Comment by Araq** [comment]
A package under nim-lang is official, under Araq is not. Unofficial packages are not necessarily good enough for our quality standards. :P

**Comment by Araq** [comment]
I moved the stuff that I think should be moved out of the stdlib. So IMHO this issue can be closed finally.

**Comment by dom96** [comment]
Where is the windows module?

**Comment by Araq** [comment]
nim-lang/oldwinapi
