### ISSUE TITLE
Varargs not working with specific function names

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6241]
```
proc `!?`(xs: varargs[int]) = discard
!?(1, 2) #type mismatch: got ((int, int))

proc `ww`(xs: varargs[int]) = discard
ww(1, 2) #no error
```

**Comment by Parashurama** [comment]
I think its becase you called `!?` like an operator instead of a function
this works:
```nim
`!?`(1, 2)
```
since your function name contains symbols/spaces you need to wrap it with ``
```nim
 `this is a function name`(arg0, arg1)
```

**Comment by Araq** [comment]
No bug here ``!?(1, 2)`` means "pass tuple to the unary operator" (what else could it mean, by its prefix position, it's clearly an unary operator);  ``ww(1, 2)`` means "pass 1 and 2 to ww".

`!?`(1, 2)  in contrast means "treat operator as identifier" and so that one works too.
