### ISSUE TITLE
Unable to get compile switches in NimScript

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#6242]
### File `switches.nim.cfg`
``` nim
cc = vcc
--passC: "/DVCC_TEST_SWITCH" # just as an example, passing this preprocessor won't break anything
```
### File `switches.nims`
``` nim
echo get("cc")
echo get("passC")
```
Running `nim e switches.nims` produces:
```
vcc

```
I would expect `nim` to also output the value of the `passC` switch. Alternatively, I'd be fine with having a proc in `nimscript` á la `proc getSwitch(switch: string): seq[string]` as you can pass some switches more than once.

**Comment by Araq** [comment]
That's not how things work. ``get`` is about "configuration variables" (kinda like environment vars) but ``passC`` does not set a config var.

**Comment by couven92** [comment]
Ah, okay, I solved my specific issue for this by simply using the `%=` syntax in config files instead.
