### ISSUE TITLE
appending double to string doesn't work on VM

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#6244]
```Nim
static:
  var s: string = ""
  s.add 123.456
```

```
[...]/Nim/lib/system/sysstr.nim(298, 16) Error: cannot 'importc' variable at compile time
```

I would like to fix it, but sysstr.nim is confusing me. I don't know what happens.

**Comment by Parashurama** [comment]
Actually the code is pretty simple.
the expr s.add 123.456
calls overloaded proc add(x: string; v: float) =
with stringify the double and append to string.
the problem is that  stringifying the double uses sprintf which is cimported, and thus not available at compile time.
EDIT: 
I have been working on and off on a pure nim version of float -> str and str -> float.
but its slow going ( It's actually not that easy to avoid rounding errors in those conversions) 
CPython version is ~3000 LOC.

**Comment by TiberiumN** [comment]
@Parashurama 3kloc? wow

**Comment by Parashurama** [comment]
Yup. here is a link:
https://github.com/python/cpython/blob/master/Python/dtoa.c
plus all header.
It's based on a pretty standard implementation and modified heavy for python internals.

**Comment by dom96** [comment]
I'm surprised there is a `proc add(x: string; v: float) =` 0_o

**Comment by krux02** [comment]
@Parashurama I think it's not that easy, ``sysstr.add`` is not an exported function, therefore it is not a simple overload. There is no ``proc add(x: string; v: float)`` in ``system.nim``. I don't know what happens and how the compiler wants to use that function.

@TiberiumN I don't think that it is necessary to have a pure ``float`` -> ``string`` conversion. The implementation is complicated and the execution will be slow. That conversion is already built into the VM, and it calls the C library internally, I don't see a problem here.

**Comment by Araq** [comment]
>  There is no proc add(x: string; v: float) in system.nim. I don't know what happens and how the compiler wants to use that function.

There is, in ``lib/system/sysstr.nim``:

```nim

proc add*(result: var string; x: float) =
  ...
```

No compiler magic going on here.

**Comment by Araq** [comment]
> I'm surprised there is a proc add(x: string; v: float) = 

I added this overload in order to speedup a JSON benchmark after discussing its interface with the people in IRC. ;-)

**Comment by Parashurama** [comment]
I was not implying that ```proc add(x: string; v: float)``` was an exact definition.
just a string `add` proc  overloaded for double. 
I didn't have a copy of nim compiler at hand to check.

**Comment by krux02** [comment]
@Araq Well it seems that this "speedup" caused a compatibility break on the VM. Can you fix it? Or at least explain, how the language knows that this function needs to be called?

Btw I worked with the json library, and I have to say it is not necessarily a fast json parser, I have little comparison though, and I did not do a performance test, but my intuition tells me that the fasted json parser library should have nodes that are nothing more than pointers into a memory mapped json file. All operations would then parse the file further as needed. This has the advantage that a full traversal of the json file should only require a single stack (``seq``) of nodes for recursive data structures, so no gc activity.

**Comment by Araq** [comment]
> Or at least explain, how the language knows that this function needs to be called?

What's there to explain? It's ordinary overloading resolution. Note that sysstr is included by system.nim and the proc has an export marker.

> but my intuition tells me that the fasted json parser library should have nodes that are nothing more than pointers into a memory mapped json file.

Yeah and then it would fail if the JSON doesn't fit the RAM. Note that JSON has a parser and on top of that the GC'ed ``JsonNode``'s. You can use the parser for ALL input sizes.

**Comment by krux02** [comment]
Sorry I don't really want to talk here about json, sorry for even entering the discussion. I just found out my idea is already implemented as i nimble package here: https://github.com/OpenSystemsLab
