### ISSUE TITLE
removal of the php backend

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#6245]
While working on a PR I stumbled upon remains of the PHP backend. I don't think that backend is working. I don't think anybody cares for that backend. I think the codebase could be cleaned up if that backend doesn't matter anymore. I suggest to memove it.

**Comment by enthus1ast** [comment]
afai its implemented in `jsgen` side by side with the js code. 
And it can at least compile my email script.

**Comment by rosshadden** [comment]
It was removed in #7606.
