### ISSUE TITLE
Add a converter from T to Option[T]

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6246]
I think this would be a nice way to make the Option type less verbose. `Nullable<T>` in C# behaves similarly. 

E.g this would be valid:
```nim
var a = none(int)
a = 1
```

**Comment by dawkot** [comment]
I'm afraid you can't overload `=` this way, but a template like this should be enough:
```
template `<-`[T](x: var Option[T], v: T): untyped =
    x = some(v)
```

**Comment by GULPF** [comment]
No need to overload =, it can be done with a converter:

```nim
converter toOption[T](t: T): Option[T] =
    return some(t)
```

**Comment by dom96** [comment]
Adding RFC label because this deserves some discussion. 

I think it's a pretty good idea. Haven't thought about the possible drawbacks too much though.

**Comment by vegansk** [comment]
It's a very bad idea!

```nim
import options

type T = ref object
  v: int

proc `$`(o: T): string = $o.v

proc f(o: Option[T]) = echo o

converter toOption(t: T): Option[T] =
  return some(t)

var x: T

f(x)
```

```
Traceback (most recent call last)
test.nim(15)             test
test.nim(8)              f
options.nim(151)         $
test.nim(6)              $
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by GULPF** [comment]
Good catch, but I feel like it should be solvable. This seems to work, but I might be missing something:

```nim
converter toOption(t: T): Option[T] =
  when T is ref:
    if t.isNil:
      return none(T)
    return some(t)
  else:
    return some(t)
```

This makes `f(nil)` work as well, which might be undesired behavior. Perhaps it's solvable with `not nil` somehow?

**Comment by yglukhov** [comment]
Converters can ruin your day, especially generic ones, especially if they are in sdt lib.
https://github.com/nim-lang/Nim/issues/4518

**Comment by vegansk** [comment]
@yglukhov +100500 , they are like `#define TRUE FALSE` in C code

**Comment by GULPF** [comment]
I agree that converters are dangerous in general, but I don't see the harm in this case. When strings are no longer nilable, it would be good if Optiont[T] was more ergonomic.

For the record, it's easy to cause segfaults with Option[T] without touching any converters:
```nim
import options

type T = ref object
  v: int

proc `$`(o: T): string = $o.v

proc f(o: Option[T]) = echo o

let x = some(T(v: 1))
let y = x.map do (value: T) -> T: nil
f(y) # SIGSEGV

var z : T
f(some(z)) # SIGSEGV
```

**Comment by vegansk** [comment]
@GULPF , in your case this is explicit error, and you need to write this erroneous code. In my case the error is not so explicit for the programmer that reads the code.

Btw, why do you think that the calling `some` to translate `T` to `Option[T]` is so verbose if It makes the code more self-documented? And, for example, scala has implicit conversions but it doesn't have implicit conversion to Option type in stdlib, scalaz, cats, etc.

**Comment by GULPF** [comment]
I don't agree that it's explicit that `some(t)` will give give segfaults when `t` is nil. With a converter that handles `nil` as `none` it isn't even a problem anyway. And if the variable gets defined as `Option[T]` instead of `T` and then converted (which is a lot more natural, even without the converter), the problem doesn't occur either.

I don't like explicitly calling `some` because it's documentation which contains very little information. `t` and `some(t)` represents the same value, so it should always be "safe" to convert it. Migrating code from `nil` to `Option[T]` becomes a lot easier as well.

Although I might be biased from programming in C# :) There are definitely cases where the converter will enable bizarre code, e.g
```nim
let y = (5).map do (x: int) -> int: 4
```

C# doesn't have this problem since `Nullable<T>` doesn't have any fancy methods.

**Comment by vegansk** [comment]
@GULPF , T and Option[T] is not the same value in functional programming, don't know about C# :-) Option[T] describes the context of the computation, in which the value of type T may or may not exist at any time of that computation. Either[E, A] describes computations with possible error, Validation[E, A] - with multiple errrors accumulator, and so on. And for functional programmer it's really matters :-)

`some(t)` doesn't produce segfault itself, this code does: `let y = x.map do (value: T) -> T: nil`. Because we don't have `not null` types. And scala has the same problems :-(

**Comment by GULPF** [comment]
Well my reasoning is that `int` represents all ints. `Option[int]` is just an extension of that, which represents all ints + nil. So all values which are representable in `int` are also representable in `Option[int]`. `some(5)` and `5` are not literally the same, but they represent the same thing (the number five). I guess this view mostly reflects how `Nullable<T>` is used, as is implied in the name `Nullable` :) 

> some(t) doesn't produce segfault itself, this code does: let y = x.map do (value: T) -> T: nil. Because we don't have not null types. And scala has the same problems :-(

I know, but I think it's rare that a proc that uses `Option[T]` will check both `isSome` and `get.isNil`, so even if `some(nil.T)` doesn't cause a segfault in itself, it represents (imo) an invalid state for `Option[T]` which will cause a segfaul _somewhere_.

**Comment by vegansk** [comment]
I think that you need this feature to work https://nim-lang.org/docs/manual.html#types-not-nil-annotation. I guess it's more close to Nullable from C#

**Comment by dom96** [comment]
After looking at this again I no longer think this is a good idea. I much rather be explicit in your original code. 

I'm going to close this as I think the discussion has come to its fruition. We can reopen if there is a  more active discussion.
