### ISSUE TITLE
Equality of OrderedTable is incorrect

### ISSUE THREAD

**Issue by nazgul17** [nim-lang/Nim#6250]
Hi,

I think I spotted a bug in the `==` function for OrderedTable (maybe other tables too).
If you run:
```
let
  a = {3: 1}.toOrderedTable
  b = {3: 2}.toOrderedTable
echo a, " == ", b, " ", a == b
echo b, " == ", a, " ", b == a
```
you will get
```
{3: 1} == {3: 2} true
{3: 2} == {3: 1} true
```

Probably, it has to do with [line 648 in tables module](https://github.com/nim-lang/Nim/blob/master/lib/pure/collections/tables.nim#L637): not sure how OrderedTables are implemented, but when the keys are the same, a difference in values should return false.

**Comment by andreaferretti** [comment]
This is a regression: in v0.16.0 it works as expected

**Comment by enthus1ast** [comment]
```
    if isFilled(t.data[ht].hcode) and isFilled(s.data[hs].hcode):
      if (s.data[hs].key != t.data[ht].key) and (s.data[hs].val != t.data[ht].val):
        return false
```

```
    if isFilled(t.data[ht].hcode) and isFilled(s.data[hs].hcode):
      if (s.data[hs].key != t.data[ht].key) or (s.data[hs].val != t.data[ht].val):
        return false
```
