### ISSUE TITLE
shr operator should keep the sign bit on signed types.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#6255]
The right shift operator is useful with both, keeping the sign bit, and not keeping the sign bit. But for not keeping the sign bit, that is what unsigend integers are for. Therefore I recommend that on signed integers the sign is kept.

```Nim
echo toBin(-123 , 64)        # 1111111111111111111111111111111111111111111111111111111110000101
echo toBin(-123 shr 1, 64)   # 0111111111111111111111111111111111111111111111111111111111000010
                 # should be # 1111111111111111111111111111111111111111111111111111111111000010
```
I think it does make sense to see negative integers in binary with an infinite amount of ones at the left. And therefore it does make sense when they fill up with ones from the left.

**Comment by jangko** [comment]
I forget where it was mentioned that Nim only have logical right shift and have no arithmetic right shift.
But I agree that we need both logical and arithmetic right shift.
perhaps using new operator such as `sar` mimicking assembly `shr`/`shl` for logical shift and `sar` for arithmetic right shift

**Comment by krux02** [comment]
Well I think that `shl`/`shr`  on `uint` should be logical hift and `shr`/`srl` on `int` should be arithmetic shift. Everything is possible with that, it is the useful operator for each type. Just imagine if you had infinite amount of bits how would the right shift work?

**Comment by Araq** [comment]
I have never needed ``sar`` in my entire life. What's its point? The operation of "bit shifting" obviously treats the number as bit strings, so 

> Well I think that shl/shr on uint should be logical hift and shr/srl on int should be arithmetic shift.

makes little sense to me.

**Comment by krux02** [comment]
```Nim
echo(-123'i8  shr 1)  # 66
echo(-123'i16 shr 1)  # 32706
echo(-123'i32 shr 1)  # 2147483586
echo(-123'i64 shr 1)  # 9223372036854775746
```

```C
#include <stdio.h>
#include <stdint.h>

int main() {
  printf("%d\n",  (int8_t)(-123) >> 1); // -62
  printf("%d\n", (int16_t)(-123) >> 1); // -62
  printf("%d\n", (int32_t)(-123) >> 1); // -62
  printf("%d\n", (int64_t)(-123) >> 1); // -62
}
```

Guess what I think is more consistent. And as I said, I think both bit shifting operators should be available, and distinguishing them by type is generally a good idea. And when you look at the example above: 
```Nim

echo toBin(-123 , 64)        # 1111111111111111111111111111111111111111111111111111111110000101
echo toBin(-123 shr 1, 64)   # 0111111111111111111111111111111111111111111111111111111111000010
#                              ^
# why does it make sense to you to introdice a 0 here instead of a 1?

```

**Comment by Araq** [comment]
This discussion is futile, shr/shl for integers will stay as they are.

**Comment by krux02** [comment]
Well maybe I am just not good with the right reasons to do like I suggest to do it. But The programming language C has this behaviour. I think it is implementation defined behaviour, but it most implementations do arithmetic right shift on signed integers, and I think they have good reason to do so. I don't think it is good reason to just be different than C.

**Comment by Araq** [comment]
> I don't think it is good reason to just be different than C.

Swapping between big/little endian, writing an integer byte by byte are common use cases and work with unsigned shifts regardless of whether the integer is signed or not. The reason is never "just to be different". You can analyse millions of lines of C. You will find that a real 'sar' operation (as opposed to "wrongly used >> on ints" or "it doesn't matter because the numbers are small positive in practice") is **rare**.  Good defaults are about common cases, not fringe cases.

**Comment by krux02** [comment]
Well is sapping between big/little endian, and writing an integer byte by byte affected by this change? I don't think so. And my argument is more that arithmetic right shift should be possible, I don't see it possible right now. And when it should be made possible, I think signed integers are the right place to do it. 

Java and JavaScript both have a distinct right shift operator for arithmetic shifting, but this extra operator is only necessary, because those languages do not have unsigned integers.

**Comment by Araq** [comment]
It is not a bug.

**Comment by krux02** [comment]
While it is not a bug. The c2nim conversion tool could introduce a bug because of this behaviour difference.

**Comment by donlzx** [comment]
The arithmetic right shift operator is very important for writing optimized routines for scientific computing.   Please consider adding a new operator or change the ```shr``` operator.

**Comment by krux02** [comment]
well, it doesn't need to be an operator, but it should be available. I looked at the implementation of the right shift operator in the generated C files, and it does a cast to unsigned numbers before doing the right shift operator. I guess this is because the behaviour of the right shift operator of signed numbers is implementation defined and this cast to unsigned simply removes dependency on this implementation defined behaviour. And yet I don't like it.

**Comment by Araq** [comment]
Feature request: Implement ``system.ashr`` (No new operator please)

**Comment by krux02** [comment]
@Bulat-Ziganshin In C the behavior of >> on singned numbers is actually unspecified. It is just that accorss C implementors it has settled to use arithmetic right shift.

**Comment by Bulat-Ziganshin** [comment]
@andreaferretti thanks. will it work with "let" instead of const" too? binary "^" operation isn't documented in manuals, there is only mention of https://nim-lang.org/docs/system.html#^.t,int

**Comment by andreaferretti** [comment]
I don't think it will work, because the constant has to be known at compile time. Maybe in some cases the C compiler can recognize such a pattern nevertheless, but I wouldn't rely on it if performance is critical.
