### ISSUE TITLE
idea: "in debug echo" | only in debug template | const debug = not defined(release)

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#6258]
## 1) 
First idea "was only in debug mode" echo:
```
template dbg*(args: varargs[untyped]) =
  ##like `debugEcho` but removed when compiled with -d:release 
  when not defined release: debugEcho args

dbg "hallo"
```

## 2)
But we also could have this.
but it may clashes with logging.debug
```
# withDebug
# onDebug
# whenDebug
template debug*(body: untyped) =
  when not defined release:
    body

debug echo "hello"
```

## 2a)
```template debug(args: varargs[string, `$`])```

## 2b)
```template debug(body: proc)```

## 3) 
or:
```
const debug = not defined(release)
when debug: echo "hello"
```

## 4)
or we do nothing and have:
```
when defined(debug): echo "hello"
when not defined release: echo "hello"
```

**Comment by Araq** [comment]
It's usually not wise to depend on ``defined(release)``, instead I prefer library specific debugging features. Thus I vote for (4), different people should use different switches.
