### ISSUE TITLE
Order of types in type section sometimes matter

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6259]
Usually, the order of types defined in a type section doesn't matter. This compiles without problems:
```nim
type

    Foo = object
        field: Bar

    Bar = enum
        a, b, c
```

But in this case if fails with `file.nim(4, 19) Error: ordinal type expected`:
```nim
type

    Foo = object
        field: set[Bar]

    Bar = enum
        a, b, c
```

If `Bar` is moved above `Foo` it works.

**Comment by Vindaar** [comment]
Yup, this confused the hell out of me for a while right now.
