### ISSUE TITLE
Unable to initialize after overloading assigement operator (ref GC)

### ISSUE THREAD

**Issue by BigEpsilon** [nim-lang/Nim#6260]
$ nim --version
    Nim Compiler Version 0.17.1 (2017-08-07) [Linux: amd64]
    Copyright (c) 2006-2017 by Andreas Rumpf

    git hash: 93ef3bcf276e867e300ecbe37772c5cc2d618fdb
    active boot switches: -d:release

The following code:

    type 
        container[T] = object
            val: seq[T]

    proc `=`[T](d: var container[T], s: container[T]) =
        echo "= container called"
        echo s
        echo d
        shallowCopy(d.val, s.val)

    var c = container[int](val: @[1, 2, 3])

With the following command options:

    $ nim c --run main2.nim

generates the following error:

    = container called
    (val: @[1, 2, 3])
    (val: nil)
    Traceback (most recent call last)
    main2.nim(11)            main2
    main2.nim(9)             =
    gc.nim(287)              unsureAsgnRef
    gc.nim(196)              incRef
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)

However, no error occurs if I use the the markAndSweep GC:

   $ nim c --gc:markAndSweep --run main2.nim

outputs:

    = container called
    (val: @[1, 2, 3])
    (val: nil)

**Comment by andreaferretti** [comment]
Adding the GC tag but I am not really sure whether this is a GC issue

**Comment by narimiran** [comment]
Currently (Nim 0.20.99) the snippet doesn't `SIGSEGV` anymore, but — nothing is printed, i.e. ``proc `=` `` is not called.

**Comment by Araq** [comment]
N/A anymore, now there is ORC and a refined system for =hooks.
