### ISSUE TITLE
rollingFileLogger deletes file on every start.

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#6264]
I think same issue but another flavour: #6141

I would expect it to append to the LOGFILE.txt on every start of the program.
But roll over when max lines exeedet.

But it seems to delete the file on every start, thus old log lines are lost.
I think this behavior was not intendet?
```
import logging
import times
var L = newConsoleLogger()
var rL = newRollingFileLogger("LOGFILE.txt", fmtStr = verboseFmtStr) #, mode = fmAppend)

addHandler(L)
addHandler(rL)

debug($epochTime())
info($epochTime())
warn($epochTime())
error($epochTime())
```

**Comment by FedericoCeratto** [comment]
@Yardanico this is a bug, not a feature
