### ISSUE TITLE
Cannot compile program with VS 2017 backend?

### ISSUE THREAD

**Issue by anta40** [nim-lang/Nim#6266]
My laptop runs 64-bit Windows 10, and the only C compiler installed is VS 2017. No GCC. And I have Nim 0.17.0 x86_64 with its nim.cfg untouched (C:\nim\bin is already in %PATH%, btw).  

Steps to reproduce:
1. Run **Developer Command Prompt for VS 2017**
2. Run **vccexe**. You'll get this message:

> "C:\WINDOWS\system32\cmd.exe" /C "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall && SET"
> cl.exe
> Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x86
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> usage: cl [ option... ] filename... [ /link linkoption... ]

3. Compile a ["Hello world" code](https://nim-by-example.github.io/hello_world/): **nim c --cc:vcc -r hello.nim**

> Hint: used config file 'C:\nim\config\nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: hello [Processing]
> CC: hello
> CC: stdlib_system
> "C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64 && SET"
> "C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64 && SET"
> cl.exe /c /nologo /IC:\nim\lib /FoC:\Users\Cipta-NB\Codes\Nim\nimcache\hello.obj C:\Users\Cipta-NB\Codes\Nim\nimcache\hello.c
> cl.exe /c /nologo /IC:\nim\lib /FoC:\Users\Cipta-NB\Codes\Nim\nimcache\stdlib_system.obj C:\Users\Cipta-NB\Codes\Nim\nimcache\stdlib_system.c
> hello.c
> stdlib_system.c
> C:\nim\lib\nimbase.h(482): error C2118: negative subscript
> C:\nim\lib\nimbase.h(482): error C2118: negative subscript
> Hint:  [Link]
> "C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64 && SET"
> cl.exe /nologo /DEBUG /Zi /F33554432 /FeC:\Users\Cipta-NB\Codes\Nim\hello.exe C:\Users\Cipta-NB\Codes\Nim\nimcache\hello.obj C:\Users\Cipta-NB\Codes\Nim\nimcache\stdlib_system.obj
> LINK : fatal error LNK1181: cannot open input file 'C:\Users\Cipta-NB\Codes\Nim\nimcache\hello.obj'
> Error: execution of an external program failed: 'vccexe.exe    --platform:amd64 /nologo /DEBUG /Zi /F33554432  /FeC:\Users\Cipta-NB\Codes\Nim\hello.exe  C:\Users\Cipta-NB\Codes\Nim\nimcache\hello.obj C:\Users\Cipta-NB\Codes\Nim\nimcache\stdlib_system.obj '

Seems like not working. I replaced the original nim.cfg with [the very latest one](https://github.com/nim-lang/Nim/pull/6261). Well basically the same error still persist.

**Comment by Yardanico** [comment]
Something with cpu architecture mismatch

**Comment by jangko** [comment]
@anta40, you are using 32bit msvc compiler, mixed with 64bit nim compiler.
try this:
`nim c --cpu:i386 --cc:vcc -r hello.nim` to produce 32bit code

or switch to vs2017 64bit mode or use 32bit nim compiler

btw, this is not a bug or nim compiler issue

**Comment by Yardanico** [comment]
@dom96 maybe close? this is really not a nim issue

**Comment by anta40** [comment]
@jangko 
It seems that I ran the wrong command prompt. I tried **x64 Native Tools Command Prompt for VS 2017** and compilation went fine.

Guess I'll close this :)
