### ISSUE TITLE
sleepAsync() resolution

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#6270]
I'm building a somewhat complex network traffic emulator which should be able to generate precise rates of several thousand events per second. At this time asyncSleep() only allows for integer millisecond resolution, which is not enough for me to get the required rates.

The current sleep() and addTimer() functions all use millisecond arguments, and changing the API to floats will probably break a lot. Would it be acceptable to allow these function to accept floats for the intervals instead so that sub-millisecond delays/intervals can be made on platforms that support this?

````
proc sleepAsync*(ms: int | float): Future[void] =
````

**Comment by dom96** [comment]
Sure. If you want to make a PR for this please go right ahead. Should be easier now that upcoming has been merged in :)

**Comment by zevv** [comment]
https://github.com/nim-lang/Nim/pull/7251
