### ISSUE TITLE
internal error with bad empty sequence syntax

### ISSUE THREAD

**Issue by jackmott** [nim-lang/Nim#6273]
Going through the chat example in Nim in Action I was able to cause an internal error in the compiler, under linux, with the following code:

```
import asyncdispatch, asyncnet

type 
  Client = ref object
    socket: AsyncSocket
    netAddr: string
    id: int
    connected: bool

  Server = ref object
    socket: AsyncSocket
    clients: seq[Client]

proc newServer() : Server = 
    Server(socket: newAsyncSocket(), clients:@[])   # the missing space between : and @ is the cause
````

compiler error:
`Error: internal error: (filename: semobjconstr.nim, line: 47)

This is caused by the missing space in `clients:@[]`

**Comment by Yardanico** [comment]
@jackmott it's fixed in devel and outputs this:
"dd.nim(15, 11) Error: incorrect object construction syntax"
Yeah, bad error message, but no compiler error :)

**Comment by Yardanico** [comment]
@jackmott duplicate of https://github.com/nim-lang/Nim/issues/5999, can you close your issue?

**Comment by jackmott** [comment]
great, closing.
