### ISSUE TITLE
Wiki: Whitespace-FAQ: Link to syntax filters is broken

### ISSUE THREAD

**Issue by kozec** [nim-lang/Nim#6278]
Hello,

on https://github.com/nim-lang/Nim/wiki/Whitespace-FAQ wiki page, in part that explains workaround for Nim's issue with tabs, there is mention about syntax filter, but no actual explanation how to fix the issue. Additionally, link points to http://nim-lang.org/filters.html, non existing page.

Nim is currently throwing syntax error whenever tab is used, so it may be better to include filter required to fix the problem directly in Whitespace wiki page.

**Comment by Yardanico** [comment]
@kozec I fixed this link

**Comment by kozec** [comment]
Thanks :)

By the way, I found, in meantime, that filter `#? replace("\t", "    ")` works around the problem.

**Comment by Yardanico** [comment]
@kozec yes, it is.

**Comment by dom96** [comment]
You should seriously consider using spaces instead of this hack to get tabs support.

**Comment by kozec** [comment]
I did. And found it would mean reconfiguring every tool I'm using to do this exact translation or just press space 2 or 4 times all the time. There is no advantage and both sounds like major PITA.

**Comment by Araq** [comment]
Use better tools?

**Comment by kozec** [comment]
> Use better tools?

Line compiler that can parse \t? :)

Frankly, I found, since I opened this, that this behavior is considered a _feature_ of Nim. And since I can't really imagine where such notion could come from, I'd rather leave it alone. I've seen enough of weirdass programming decisions to know when there is no chance for improvement.

**Comment by Yardanico** [comment]
@kozec ok, what would be your answer to fact, that most of python application/packages use spaces?
even pep8 says that developer should use spaces

**Comment by kozec** [comment]
@Yardanico I'd say I don't exactly care about their opinion, as long as they don't try to shove it down my throat. For example by trowing syntax errors...
