### ISSUE TITLE
Methods with generics don't work

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#6283]
As reported here: https://forum.nim-lang.org/t/3128/

```nim
type
    Console* = ref object of RootObj
    ViewportConsole* = ref object of Console

method draw*[T](self: Console, engine: T) {.base.} =
    echo "Ignoring a Console..."

method draw*[T](self: ViewportConsole, engine: T) =
    echo "Drawing a ViewportConsole on ", engine, "..."

var consoles: seq[Console] = @[]
consoles.add(new(Console))
consoles.add(new(ViewportConsole))

for console in consoles:
    console.draw("blah blah")
```

Expected output:
```
Ignoring a Console...
Drawing a ViewportConsole on blah blah...
```
Actual output:
```
Ignoring a Console...
Ignoring a Console...
```
Removing the generic from `draw` makes it work.

Instantiating the method for the correct types can also make it work (or fail to compile even):

```nim
var vc = new(ViewportConsole)
vc.draw("foo")
```

**Comment by andreaferretti** [comment]
It seems to me this has to be a duplicate but I could not find anything

**Comment by Araq** [comment]
This is not a bug. The second generic draw is never instantiated.

**Comment by andreaferretti** [comment]
Still seems a bug to me. Calling a method should use dynamic dispatch. I fail to see a good reason for this not to happen here

**Comment by deansher** [comment]
Has a consensus developed on this behavior over time? Alternatively, has @Araq explained his perspective?
