### ISSUE TITLE
httpclient crash when performing get request

### ISSUE THREAD

**Issue by konqoro** [nim-lang/Nim#6284]
Code:
```
import httpclient

const url = "http://www.insomnia.gr/"
var client = newHttpClient()

client.downloadFile(url, "page.html")
let body = client.getContent(url)
```
Fails with:
```
Traceback (most recent call last)
bug_http.nim(11)         bug_http
httpclient.nim(1194)     getContent
streams.nim(110)         readAll
streams.nim(102)         readData
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

I believe the problem is that `downloadFile` sets `client.getBody = false` [here](https://github.com/nim-lang/Nim/blob/master/lib/pure/httpclient.nim#L1246)

**Comment by Yardanico** [comment]
@konqoro yeah, it actually downloads the page but then crashes

**Comment by pyloor** [comment]
With async it doesn't work, too

```
import httpclient, asyncnet, asyncdispatch, asyncfile

const url = "http://google.de/"

proc dndl() {.async.} =
  var client = newAsyncHttpClient()

  echo 1
  await client.downloadFile(url, "page.html")

  echo 2
  let body = await client.getContent(url)
  echo body

  echo 3

when isMainModule:
  waitFor dndl()
```
Returns:
```
./bughttp
1
2
Traceback (most recent call last)
bughttp.nim(18)          bughttp
asyncdispatch.nim(1010)  waitFor
asyncdispatch.nim(1045)  poll
asyncdispatch.nim(179)   processPendingCallbacks
asyncmacro.nim(34)       cb0
httpclient.nim(1194)     getContentIter
asyncmacro.nim(393)      readAll
asyncmacro.nim(34)       cb0
asyncdispatch.nim(1293)  readAllIter
asyncstreams.nim(81)     read
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

But if i change the order of the requests, then it works:

```
import httpclient, asyncnet, asyncdispatch, asyncfile

const url = "http://google.de/"

proc dndl() {.async.} =
  var client = newAsyncHttpClient()

  echo 1
  let body = await client.getContent(url)
  echo body

  echo 2
  await client.downloadFile(url, "page.html")

  echo 3

when isMainModule:
  waitFor dndl()
```

Returns:
- Output of google
- Downloads file

It seems that after downloading the file, something happens to the client...

**Comment by konqoro** [comment]
> It seems that after downloading the file, something happens to the client...

Yes exactly: [line 1246](https://github.com/nim-lang/Nim/blob/master/lib/pure/httpclient.nim#L1246)

**Comment by konqoro** [comment]
I try to understand how that works but it seems there are procs that accept getBody as parameter and there is also HttpClientBase field getBody. ... it is kind of messy.

**Comment by pyloor** [comment]
As far as I understand it, the getBody bool is used for parsing need of the body.
downloadFile -> resolves to get -> resolves to request with param HttpGet method -> resolves to requestAux. requestAux needs to now how to handle the body. if getBody is true: use parseBody and return a StringStream.

The downloadFile function does not want to parse the body but to store it via a FileStream. Thus getBody is set to false to avoid usage of parseBody.

I hope someone understands my bad description :(

**Comment by dom96** [comment]
I believe the fix is simple: use ``defer`` to reset the state of ``client.getBody``.

**Comment by dom96** [comment]
Indeed, that fixes the issue ^ :)
