### ISSUE TITLE
Thread analysis bug

### ISSUE THREAD

**Issue by 10c8** [nim-lang/Nim#6286]
The following code, using `jester` and `nimongo`:
```nim
var db: Database[Mongo]

let
    mongoCur = newMongoWithURI(config.getSectionValue("database", "connectionString"))
    connected = mongoCur.connect()

if connected:
    db = mongoCur[config.getSectionValue("database", "databaseName")]
else:
    quit(1)

proc getUser(username: string): string =
    let user = db["accounts"].find(bson.`%*`({
        "username": username
    })).one()

    # ...

    result = "test"

routes:
    post "/user":
        let username = request.formData["username"].body
        var authResponse: string = ""

        let user = getUser(username)

        if user == nil:
            authResponse = json.`%*`{
                "status": "error"
            }
        else:
            authResponse = json.`%*`{
                "status": "ok",
                "info": user
            }

        resp authResponse
```

Only compiles with the compiler option `--threadAnalysis:off`. Without it, the compilation fails:
```
lib/nim/core/macros.nim(359, 13) Error: type mismatch: got (proc (request: Request, response: Response): Future[system.bool]{.locks: <unknown>.}, Settings)
but expected one of:
proc serve(match: proc (request: Request; response: Response): Future[bool];
          settings: Settings = newSettings())

    let x = internalErrorFlag()
              ^
stack trace: (most recent call last)
```

**Comment by Yardanico** [comment]
it's due to the fact that you're using global variable.
nim has thread-local gc, so by default memory can't be shared between threads.
you can either use raw pointer (ptr), or boehm gc which has shared heap

**Comment by dom96** [comment]
This isn't a thread analysis bug but I will keep it here because I think the error message could improve.

Three things could improve the error message:

* Mentioning the ``--threadAnalsysis:off`` flag.
* Explicitly mentioning that the passed in proc isn't gcsafe.
* Explaining why the passed in proc isn't gcsafe: "The anon proc defined on line <x> isn't gcsafe because it accesses 'db' variable defined on line 0" (or similar).

**Comment by enthus1ast** [comment]
Ref: #6186

**Comment by yglukhov** [comment]
> Mentioning the --threadAnalsysis:off flag in the error message as a possible fix.

Why would Nim recommend a way to shoot users foot? `--threadAnalsysis:off` should be the last resort hammer buried deep in the docs.

**Comment by Araq** [comment]
Since then effect inference got fixed.
