### ISSUE TITLE
static bug

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#6297]
```
type
  Array[M: static[int]] = array[M, int]

proc t(): int = 1
let n = t()

var m: Array[n]
```

Result: Compiler hangs instead of displaying `Error: cannot evaluate at compile time: n`

**Comment by narimiran** [comment]
> Compiler hangs instead of displaying `Error: cannot evaluate at compile time: n`

This is *exactly* what is displayed in Nim 0.19.0 — this can be closed.

**Comment by andreaferretti** [comment]
Agreed
