### ISSUE TITLE
Error: cannot 'importc' variable at compile time

### ISSUE THREAD

**Issue by cabhishek** [nim-lang/Nim#6308]
Recent changes [osenv.nim](https://github.com/nim-lang/Nim/commit/b018ddca033a04518ce41f2030c200c76f82aded) might have caused a regression. My test build started failing with the error:

`lib/pure/includes/osenv.nim(75, 9) Error: cannot 'importc' variable at compile time`

Travis error [log](https://travis-ci.org/cabhishek/nimlox/builds/270985905)

```
Nim Compiler Version 0.17.1 (2017-09-01) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: b2a5f978602ff39a9bd2b302d2acdd241f09086a
active boot switches: -d:release
```

**Comment by Yardanico** [comment]
@cabhishek try latest devel

**Comment by Araq** [comment]
Has been fixed.
