### ISSUE TITLE
`$` fails at runtime when applied to a default tuple or object containing `distinct string`.

### ISSUE THREAD

**Issue by jaccarmac** [nim-lang/Nim#6310]
Perhaps this is actually expected behavior, but couldn't find an explanation for this behavior in the docs...

My Nim's from choosenim and the `devel` channel, compiled just before I tested this, so probably `3bc7dbbd9757750fc4c75581891abb8e9849eab7` though I haven't compiled myself just yet. Can absolutely do so if it's an issue.

Tested on both an up-to-date Windows 10 box and a machine running Gentoo kernel 4.12.5.

Code to duplicate: https://gist.github.com/jaccarmac/f21c781f5d4809fbf0a682067d56fe41

Expected behavior: Documentation explains why the annotated sections fail or the compiler slaps my wrist before panicking at runtime.

Actual behavior: The program fails at the commented sections as annotated.

**Comment by jaccarmac** [comment]
Just had the (in retrospect obvious) idea to check my example with `string` as well as `distinct string` and it fails in the same way. So perhaps less mysterious but still something that would be nice to catch at compile time.

**Comment by dom96** [comment]
This will be fixed as a side-effect once strings are no longer `nil` by default :)

Btw, please lean towards embedding your code into the issue (gists can disappear).

**Comment by jaccarmac** [comment]
Ooh, is that issue actually going to be fixed, where's the tracking on it if I may ask?

**Comment by jaccarmac** [comment]
> Btw, please lean towards embedding your code into the issue (gists can disappear).

For completeness' sake :-)

```nim
type
    DistinctString = distinct string
    DSTuple = tuple[ds: DistinctString] # or string
    DSObject = object
        ds: DistinctString # or string

proc `$`(ds: DistinctString): string {.borrow.} # also fails without pragma and with the following body
#    ds.string

# uncomment to let echo y succeed
# proc `$`(dst: DSTuple): string =
#     $dst.ds

# uncomment to let echo z succeed
# proc `$`(dso: DSObject): string =
#     $dso.ds

var x: DistinctString # works
echo x

var y: DSTuple # fails
echo y

var z: DSObject # fails but succeeds outside project
echo z
```

**Comment by jaccarmac** [comment]
Since it's a nil issue the same problem seems to occur with the other default-nil types (ref, ptr, proc, and seq). Since I don't imagine there are plans to fix nil pointers and references at the least, is there a possible fix for the default $ implementation or do I need to be manually aware of everywhere I could form a nil in my program?

**Comment by Araq** [comment]
Works as expected, for better or worse. 

You also need to borrow ``isNil``:

```nim

proc isNil(ds: DistinctString): bool {.borrow.}
```
