### ISSUE TITLE
Feature. Pragma {.notCompileIfUnused.}

### ISSUE THREAD

**Issue by Grabli66** [nim-lang/Nim#6311]
It will be good to have a pragma, that can stop compiling if there is any unused variable in code.
Programmer often can not notice unused variables. And if code will not compile with message that there are unused variables, he will notice that surely.
This pragma can help programmer to keep code clean from unused garbage.

**Comment by Araq** [comment]
Ugh, no. 

1. Unused symbols are not nearly important enough as bug indicators.
2. They already are reported. Patch your CI if you want these to fail your builds. (And you do use a CI, right?)

**Comment by Grabli66** [comment]
No. I dont use CI
I use 
nim compile mycode.nim

**Comment by dom96** [comment]
@Araq what's wrong with providing this as a feature?

**Comment by yglukhov** [comment]
Maybe its better to provide a cli flag to treat arbitrary warnings as errors? In any case I would agree that this feature is far from the top priority.

**Comment by Araq** [comment]
I already made my arguments and won't accept a PR that implements this either. Compiler complexity is also always an issue.
