### ISSUE TITLE
Should the docs say nimvm is rare?

### ISSUE THREAD

**Issue by da99** [nim-lang/Nim#6312]
Should the documentation for [nimvm](https://nim-lang.org/docs/system.html#9) include a short message explaining that `nimvm` is rare and for expert programmers?

**Comment by Yardanico** [comment]
@da99 why? you can check if your procedure executed at compile-time with this constant

**Comment by da99** [comment]
Nevermind. More info. is provided in the manual: https://nim-lang.org/docs/manual.html#statements-and-expressions-when-nimvm-statement 

Originally, the reason I asked was because of Araq's comment: "That's true, but since when nimvm is rare and more for expert programmers I don't think a nicer alias is justified."
https://github.com/nim-lang/Nim/issues/5518#issuecomment-286551291
