### ISSUE TITLE
nim.cfg -d:release switch doesn't work

### ISSUE THREAD

**Issue by ntilotta** [nim-lang/Nim#6319]
When I create a nim.cfg (not a nimble package) and putting -d:release inside, with the nim c file.nim command, it says release build, but it emits a debug release instead.

Nim Compiler Version 0.17.0 (2017-05-17) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
active boot switches: -d:release

**Comment by Yardanico** [comment]
how do you know that it's a debug build?

**Comment by Yardanico** [comment]
@ntilotta how can you check if it's a debug build?

**Comment by ntilotta** [comment]
main.nim
`echo "Hello, World!"`
Debug build: 188.5 kB (nim c main.nim)
Release build: 82.4 kB (nim c -d:release main.nim)

When I do it with a nim.cfg file, it still 188.5 kB, even if I add the --opt:size switch inside nim.cfg

**Comment by dom96** [comment]
You cannot add `-d:release` to the config file because this flag is actually defined inside the main ``nim.cfg`` file. This is an unfortunate gotcha, what you can do is copy the flags that ``-d:release`` sets from ``nim.cfg`` into your own file.

**Comment by ntilotta** [comment]
@dom96 thank you for your help, I close this issue

**Comment by dom96** [comment]
@ntilotta might I ask: why do you keep re-starring the jester repo? Every couple of weeks I see this:

![screen shot 2017-09-27 at 13 52 15](https://user-images.githubusercontent.com/246651/30914292-1ca95d60-a38b-11e7-9916-f4d2412ab62b.png)

**Comment by ntilotta** [comment]
@dom96 I apologize for this, I'm working on a tool to track and to star/unstar repos in trends automatically, and jester is commonly at second position and it's similar to the flask/sinatra project, I will exclude Nim language, sorry again ^.^ (btw it's just an excercise with ML)

**Comment by dom96** [comment]
> @dom96 I apologize for this, I'm working on a tool to track and to star/unstar repos in trends automatically, and jester is commonly at second position and it's similar to the flask/sinatra project, I will exclude Nim language, sorry again ^.^ (btw it's just an excercise with ML)

No worries, I was just wondering if you were trolling me :)
