### ISSUE TITLE
dash-style broken?

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#6325]
```nim
var someName = 1

some_name = 1  # OK
some-name = 1  # Error: undeclared identifier: 'some'
```

This should be fixed, or the manual should be changed.

**Comment by Yardanico** [comment]
Identifiers in Nim can be any string of letters, digits and underscores, beginning with a letter. 
@johnnovak

**Comment by johnnovak** [comment]
@Yardanico Not quite, dashes are also allowed, according to the manual:

https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality

**Comment by Yardanico** [comment]
@johnnovak it was changed
https://github.com/nim-lang/Nim/pull/6272

**Comment by Yardanico** [comment]
docs were not regenerated because there's no new Nim release yet

**Comment by johnnovak** [comment]
Cool, makes sense, thanks!

**Comment by Yardanico** [comment]
You can close it yourself :)

**Comment by Yardanico** [comment]
@jlhouchin You can close it yourself :)
