### ISSUE TITLE
Conditional object fields with static condition: generic param must be explicit even when not used

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6331]
I am not sure if it is a bug or work as intended:

With conditional object field depending on a static value, procs and templates definition must mention the generic parameter in signature even when not used. This is not needed when there is no conditional object field.

Examples:

1. No conditional object field, the template does not specify the generic parameter [B,T]
```Nim
type
  Backend* = enum
    Cpu

  Tensor*[B: static[Backend]; T] = object
    shape: seq[int]
    strides: seq[int]
    offset: int
    data: seq[T]

template shape*(t: Tensor): seq[int] =
  t.shape
```

2. Conditional object field, failure with `Cannot generate code for: B`
```Nim
type
  Backend* = enum
    Cpu,
    Cuda

  Tensor*[B: static[Backend]; T] = object
    shape: seq[int]
    strides: seq[int]
    offset: int
    when B == Backend.Cpu:
      data: seq[T]
    else:
      data_ptr: ptr T

template shape*(t: Tensor): seq[int] =
  t.shape
```

3. Conditional object field, explicit declaration of generic params, no failure
```Nim
type
  Backend* = enum
    Cpu,
    Cuda

  Tensor*[B: static[Backend]; T] = object
    shape: seq[int]
    strides: seq[int]
    offset: int
    when B == Backend.Cpu:
      data: seq[T]
    else:
      data_ptr: ptr T

template shape*[B,T](t: Tensor[B,T]): seq[int] =
  t.shape
```

**Comment by beef331** [comment]
Closed by #21528
