### ISSUE TITLE
Document #?

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/Nim#6333]
According to [this text from the wiki](https://github.com/nim-lang/Nim/wiki/Unofficial-FAQ#why-are-tabs-forbidden) you can do `#? replace(sub = "\t", by = " ")` to replace tabs with spaces in the file. I haven't seen this anywhere else, is there an explanation to it somewhere?

**Comment by Yardanico** [comment]
@hlaaftana yes, close please :)
https://nim-lang.org/docs/filters.html#available-filters-replace-filter
