### ISSUE TITLE
Syntax error when compiling koch

### ISSUE THREAD

**Issue by davidkupka** [nim-lang/Nim#6344]
Steps to reproduce:
```
$ git clone https://github.com/nim-lang/Nim.git
$ cd Nim
$ git clone --depth 1 https://github.com/nim-lang/csources.git
$ cd csources
$ sh build.sh
$ cd ../
$ bin/nim c koch
$ ./koch boot -d:release
```

Expected result:
Completes without errors.

Got result (from bin/nim c koch step):
```
Hint: used config file '/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Nim/koch.nim.cfg' [Conf]
Hint: system [Processing]
lib/system.nim(408, 27) Error: type mismatch: got (type int)
but expected one of:
proc high[T](x: T): T
```

Additional info:
If Nim AND csources are from tag v0.17.0 it works but not on master.

**Comment by Araq** [comment]
That means you have an outdated ``system.nim``. Uninstall previous Nim versions to make it work.

**Comment by Yardanico** [comment]
@davidkupka in fresh docker container?
Is it on docker hub? can you provide the link?
I'll test myself

**Comment by davidkupka** [comment]
```
$ docker run -ti fedora /bin/bash
(in container) # dnf install -y git gcc
(in container) # git clone -b master git://github.com/Araq/Nim.git
(in container) # cd Nim
(in container) # git clone --depth 1 git://github.com/nim-lang/csources
(in container) # cd csources
(in container) # sh build.sh # Replace with build.bat on windows
(in container) # cd ..
(in container) # bin/nim c koch
(in container) # ./koch boot -d:release
```

**Comment by Yardanico** [comment]
@davidkupka you should clone devel if you want to build nim yourself

**Comment by Yardanico** [comment]
@davidkupka if you want release version - use https://nim-lang.org/download/nim-0.17.0.tar.xz

**Comment by davidkupka** [comment]
@Yardanico I just followed compilation instructions in readme https://github.com/nim-lang/Nim/blob/devel/readme.md. Feel free to close this issue as invalid if it's intended only for people who know what they're doing. I've figured that checking out last released version of Nim and csources does the trick, too.

**Comment by Yardanico** [comment]
@davidkupka no, you didn't just follow instructions here, you've cloned another branch (not devel)

**Comment by davidkupka** [comment]
@Yardanico I won't argue with you. I literally copy-paste commands from readme.md.

**Comment by Yardanico** [comment]
@davidkupka how it can be possible that you copy-pasted commands, if this
https://github.com/nim-lang/Nim/issues/6344#issuecomment-327777316
is different from this:
```
$ git clone https://github.com/nim-lang/Nim.git
$ cd Nim
$ git clone --depth 1 https://github.com/nim-lang/csources.git
$ cd csources
$ sh build.sh
$ cd ../
$ bin/nim c koch
$ ./koch boot -d:release
```

**Comment by Araq** [comment]
I think that's been caused by the too new C sources that cannot compile the 'master' branch as that has not been updated yet.

**Comment by Araq** [comment]
Can you try again, 'master' has been updated to v0.17.2.

**Comment by kaushalmodi** [comment]
I came across this issue today when trying to build the devel branch.

**Comment by dom96** [comment]
Pro Tip: https://github.com/dom96/choosenim#installation

**Comment by kaushalmodi** [comment]
choosenim didn't work for me when I tried last time [https://github.com/dom96/choosenim/issues/15#issuecomment-304382834]. So I stuck with just building it manually. It works that way! *Just that I made a mistake of updating to my fork remote than the actual upstream remote.*

**Comment by dom96** [comment]
Oh 😢 
That's too bad.

**Comment by Yardanico** [comment]
Was fixed according to the discussion
