### ISSUE TITLE
Assignment overload does not distinguish between var, let, return values

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6348]
To implement efficient seq-like value semantics, overloading the assignment operator `=` is needed. However, every use of `=` will then create a copy even object construction

```Nim
type
  Baz = object
    data: int
  Foobar = object
    a: int
    data_ref: ref Baz


proc newFoobar(a: int, data: int): Foobar =
  result.a = a
  new result.data_ref
  result.data_ref[].data = data

proc `=`(dest: var Foobar, src: Foobar) =
  dest.a = src.a
  new dest.data_ref
  dest.data_ref[] = src.data_ref[]

  echo "Value copied"

let a = newFoobar(10, 50)
echo a.repr
```

Output:
```
Value copied
[a = 10,
data_ref = ref 0x10eec8060 --> [data = 50]]
```

Trying to implement [move optimization](https://nim-lang.org/docs/manual.html#ast-based-overloading-move-optimization) doesn't work, I get `Error: cannot bind another '=' to: Foobar`
with the following code:
```Nim
type
  Baz = object
    data: int
  Foobar = object
    a: int
    data_ref: ref Baz


proc newFoobar(a: int, data: int): Foobar =
  result.a = a
  new result.data_ref
  result.data_ref[].data = data

proc `=`(dest: var Foobar, src: Foobar) =
  dest.a = src.a
  new dest.data_ref
  dest.data_ref[] = src.data_ref[]

  echo "Value copied"

proc `=`(dest: var Foobar, src: Foobar{call}) =
  system.`=`(dest, src)

  echo "Value moved"

let a = newFoobar(10, 50)
echo a.repr
```

**Comment by edubart** [comment]
This makes assignment overloading unusable for huge objects in performance critical apps.

**Comment by Araq** [comment]
Assignment overloading is unusable for everything right now.

**Comment by Araq** [comment]
I'm closing this since ``=sink`` is now a thing and any bugs with it should be reported separately.
