### ISSUE TITLE
Unclear error message when assigning ambiguous proc to variable

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#6359]
Test
```nim
proc foo(a: int) = discard
proc foo(b: int) = discard
let f = foo
```
Result:
```nim
Test.nim(3, 5) Error: invalid type: 'None'
```
My original case wasn't as obvious as this example. I would expect a message along the lines of `Error: ambiguous call; both ...`
***
```nim
>nim -v
Nim Compiler Version 0.17.2 (2017-09-10) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 3bf8ced69e7b2b5c4c0ef57d8aa3726f2e5906fc
active boot switches: -d:release
```

**Comment by metagn** [comment]
This happens for any routines with the same name, not necessarily with the same signature. A possible error message would be:

`Error: identifier 'foo' matches both in.foo(a: int) [declared in /usercode/in.nim(1, 6)] and in.foo(a: string) [declared in /usercode/in.nim(2, 10)] and a type conversion must be used to declare a procvar`

If one of the routines has empty arguments, it would also say `Did you mean to do 'foo()'?`

**Comment by jibal** [comment]
> I would expect a message along the lines of `Error: ambiguous call; both ...`

It's not a call ... you're trying to get a pointer to the proc.
