### ISSUE TITLE
Compilation with --memTracker:on fails.

### ISSUE THREAD

**Issue by slyshykO** [nim-lang/Nim#6363]
..\lib\system\alloc.nim(345, 30) Error: undeclared field: 'origSize'

**Comment by krazzei** [comment]
I just ran into this issue too, it looks like BigChunk might have changed its 'orgSize' to just 'size'. Renaming it to 'size' at that line (and a few others) seems to get it to compile, but I'm not sure if this is intended or not.

Also, I'm on Windows 10 with nim version 0.17.2. Here is my build command:
`nim.exe c --opt:none --debugger:native --app:gui -o:.\\bin\\rogue_like.exe --debuginfo --NimblePath:C:\\Users\\MyUserName\\.nimble\\ --memTracker:on .\\src\\rogue_like.nim`

**Comment by Araq** [comment]
This now compiles again.
