### ISSUE TITLE
Many procs in strutils don't work with strings containing zero bytes

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#6368]
For example, `startWith` is implemented like this:
```
proc startsWith*(s, prefix: string): bool =
  var i = 0
  while true:
    if prefix[i] == '\0': return true
    if s[i] != prefix[i]: return false
    inc(i)
```
This obviously doesn't work when `prefix` contains null bytes. The procs will also break when #5596 is implemented.

**Comment by Araq** [comment]
These have all been fixed.
