### ISSUE TITLE
AssertionError with nimble pkg folders without version

### ISSUE THREAD

**Issue by mjoud** [nim-lang/Nim#6377]
Arch Linux

```$ nim --version
Nim Compiler Version 0.17.2 (2017-09-11) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```

fails with

``` 
Traceback from system (most recent call last)
Error: unhandled exception: len(ver) == 0 or contains({0, 35, 48..57}, ver[0]) Wrong version: mjo/.nimble/pkgs/wx [AssertionError]
```

when there are folders present in the nimble pkg without a proper version, `wx` in my case. Solution is to rename the folders to a dummy version `wx-0.1`.

Interestingly, my username contains a dash and in the error message above, only the part after the dash in my username in printed (`mjo` instead of `xxx-mjo`).

Possibly introduced with #6335 (not verified).

**Comment by dom96** [comment]
How did a package with no version end up in `~/.nimble/pkgs/`?

**Comment by Yardanico** [comment]
@dom96 maybe it's because of this?
>Interestingly, my username contains a dash and in the error message above, only the part after the dash in my username in printed (mjo instead of xxx-mjo).

**Comment by dom96** [comment]
But...

> when there are in folders present in the nimble pkg without a proper version, wx in my case. Solution is to rename the folders to a dummy version wx-0.1.

**Comment by mjoud** [comment]
They are manually cloned repos, for example pmunch/wxnim fork, which is ahead of Araq's wxnim.

**Comment by Yardanico** [comment]
@mjoud ah, then you shouldn't just straight clone them to your nimble packages.
you should clone the repo and run "nimble install" from it

**Comment by Yardanico** [comment]
@mjoud versions in directory names are needed for Nimble and Nim to work properly

**Comment by mjoud** [comment]
So it seems. 

@dom96 [this Reddit user](https://www.reddit.com/r/nim/comments/6yuaus/comment/dmwxdip) probably has the same problem.

**Comment by Yardanico** [comment]
@mjoud well he didn't clone repos manually it seems

**Comment by dom96** [comment]
> you should clone the repo and run "nimble install" from it

Not anymore, now you should clone the repo and *run `nimble develop` from it* :)

**Comment by Araq** [comment]
Why is this a regression? Why is this still open?

**Comment by dom96** [comment]
Because Nim used to ignore packages that had no version in it (I changed that).
