### ISSUE TITLE
Crappy error message when method is called with negated boolean without using parantheses

### ISSUE THREAD

**Issue by dunca** [nim-lang/Nim#6378]
```
var flag = true

doAssert(not(flag))
doAssert(not flag)
doAssert (not flag)
doAssert not flag
```

It fails to compile on the last line: "Error: wrong number of arguments". Could use a more specific message

**Comment by Yardanico** [comment]
well it's a normal error message: you're trying to call doAssert with two arguments if I'm not mistaken

**Comment by andreaferretti** [comment]
I agree it's pretty understandable

**Comment by yglukhov** [comment]
or rather 
```nim
`not`(doAssert, flag)
```
?

**Comment by GULPF** [comment]
I don't understand why it shouldn't compile. Is `not` marked as an operator with compiler magic? If that's the case, perhaps the compiler should handle unary operators differently.

Either way, the error could be improved by specifying what proc received the wrong number of arguments.

**Comment by andreaferretti** [comment]
Now even I find it confusing. Why is `not` - a unary operator - applied like if it was a binary operator?

**Comment by Araq** [comment]
Because the parser only knows operators and keyword operators and the position determines whether it's parsed as unary or binary operator.

**Comment by Araq** [comment]
This now works.
