### ISSUE TITLE
Sorting fails in "nim secret"

### ISSUE THREAD

**Issue by dunca** [nim-lang/Nim#6379]
>>> var c=[1,2,3,4,-1]
>>> import algorithm
Hint: algorithm [Processing]
>>> c.sort(cmp)
stack trace: (most recent call last)
stdin(3)
lib\pure\algorithm.nim(199) sort
lib\pure\algorithm.nim(130) merge
lib\pure\algorithm.nim(25) *
lib\pure\algorithm.nim(25, 22) Error: unhandled exception: value out of range
Error: unhandled exception: unhandled exception: value out of range [ERecoverableError]

For strings:

>>> var a = "cba"
>>> import algorithm
Hint: algorithm [Processing]
>>> a.sort(cmp)
>>> a
cba
>>>

The same code works fine outside of the vm

**Comment by Yardanico** [comment]
@Araq, this is fixed in devel (probably after merged PR by @Parashurama )

**Comment by Araq** [comment]
Still deserves a test case.

**Comment by Yardanico** [comment]
@Araq make a test with "static" block?
