### ISSUE TITLE
internal error: openArrayLoc

### ISSUE THREAD

**Issue by Tyler-Yocolano** [nim-lang/Nim#6384]
Specs:
Windows 10,
Nim 0.17.2 64-bit

Link to broken tree: https://github.com/Tyler-Yocolano/nimbomb/tree/0c004d7e8974e23c4f5120f253db767926596ca7

with .\koch temp c
```
Error: internal error: openArrayLoc: ResourceType
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(163)            mainCommand
main.nim(74)             commandCompileToC
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(217)          processModule
passes.nim(135)          processTopLevelStmt
cgen.nim(1316)           myProcess
ccgstmts.nim(1125)       genStmts
ccgexprs.nim(2126)       expr
ccgstmts.nim(1125)       genStmts
ccgexprs.nim(2123)       expr
ccgstmts.nim(505)        genBlock
ccgexprs.nim(2126)       expr
ccgstmts.nim(1125)       genStmts
ccgexprs.nim(2148)       expr
ccgstmts.nim(258)        genVarStmt
ccgstmts.nim(241)        genSingleVar
ccgstmts.nim(73)         loadInto
ccgcalls.nim(548)        genAsgnCall
ccgcalls.nim(176)        genPrefixCall
ccgcalls.nim(142)        genArg
ccgcalls.nim(129)        openArrayLoc
msgs.nim(1051)           internalError
msgs.nim(948)            rawMessage
msgs.nim(945)            rawMessage
msgs.nim(869)            handleError
msgs.nim(859)            quit
FAILURE
```

ResourceType is an enum defined in resourcetypes.nim, theres like 50 of them.

Changes here: https://github.com/Tyler-Yocolano/nimbomb/commit/0c004d7e8974e23c4f5120f253db767926596ca7

Prev commit: https://github.com/Tyler-Yocolano/nimbomb/tree/ba93ef31343cca5266b956858d1ab48f04939481 compiles, but doesn't run (my fault). I don't use commit or branches right, I know.

**Comment by Araq** [comment]
Please give me a snippet that reproduces the problem and that I can add to the test suite.

**Comment by Araq** [comment]
No feedback. Closing.

**Comment by Tyler-Yocolano** [comment]
Sorry, I couldn't isolate the issue.  And either way, I have re-added the
same code structure elsewhere and now it works.  That specific branch does
not though.
