### ISSUE TITLE
A warning for unused but conflicting procs would be nice

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6393]
```nim
proc x(): int = 7
proc x(): string = "strange"

#var h: int = x() # does not compile
# but why is there no warning for the two procs?
# As they make no sense. (Reported by a gintro user)
```

**Comment by dom96** [comment]
Should https://github.com/nim-lang/Nim/commit/13c6037fd4119fbc67b31524bfb271652cc3df84 be merged into devel?

**Comment by Araq** [comment]
Can't, it needs to be fixed slightly differently.

**Comment by Araq** [comment]
This is actually implemented, but doesn't work as expected. Since this is annoying me on a personal level, showstopper bug.

**Comment by zah** [comment]
Well, I want to implement return type overloading eventually. Should we track this as a separate feature issue?

**Comment by Araq** [comment]
Return type overloading would be an RFC.
