### ISSUE TITLE
Parser not catching incorrect pragma stmts

### ISSUE THREAD

**Issue by konqoro** [nim-lang/Nim#6395]
The following code compiles without errors:
```
proc p(): int {.noSideEffect} = 4
echo p()
```
Expected result: it should fail due to pragma not closed correctly.

**Comment by stisa** [comment]
That's working as intended, see the grammar [here](https://nim-lang.org/docs/manual.html#syntax-grammar) :

`pragma = '{.' optInd (exprColonExpr comma?)* optPar ('.}' | '}')`

Both `{. some .}` and `{. some }` are valid pragmas.

**Comment by Yardanico** [comment]
well manual misses this

**Comment by konqoro** [comment]
So close?
