### ISSUE TITLE
Casting to a typedesc argument always fails

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6406]
Test case

```Nim
import sequtils

proc remap(s: seq[int], T: typedesc): seq[T] =
  s.map do (x: int) -> T:
    x.T

echo remap(@[1,2,3], float)
```

Compile error:
```
test2.nim(24, 11) template/generic instantiation from here
test2.nim(22, 7) Error: type expected
```

Replacing `x.T` with `x.float` compiles and runs fine:

```Nim
import sequtils

proc remap(s: seq[int], T: typedesc): seq[T] =
  s.map do (x: int) -> T:
    x.float
echo remap(@[1,2,3,4], float) #outputs @[1.0, 2.0, 3.0, 4.0]
```

Workaround is to not use typedesc.

**Comment by Bennyelg** [comment]
Try this.
```nim
proc remap(s: seq[int], T: typedesc): seq[T] =
  s.map do (x: int) -> T:
    cast[T](x)
```
echo remap(@[1,2,3], int)

**Comment by edubart** [comment]
Thanks for the suggestion, that workaround worked.

**Comment by mratsim** [comment]
Another alternative

```
import sequtils

proc remap[T](s: seq[int], typ: typedesc[T]): seq[T] =
  s.map do (x: int) -> T:
    x.T

echo remap(@[1,2,3], float)
```

You can do T: SomeReal or T: SomeInteger to specialize your proc too.

**Comment by Yardanico** [comment]
@Bennyelg, @edubart it's better to use T(x) here, and not cast[T](x)

**Comment by Bennyelg** [comment]
@Yardanico Thanks, I didn't knew this 💃

**Comment by Yardanico** [comment]
@Bennyelg look at last @mratsim's comment, his code is exactly the same.
x.T = T(x)

**Comment by edubart** [comment]
Just found that is not only inside inside an anonymous proc, its casting with typedesc in general, simpler case:

```Nim
proc mycast(a: int, U: typedesc): U =
  a.U

echo mycast(1, float32)
```

```
play.nim(4, 12) template/generic instantiation from here
play.nim(2, 5) Error: type expected
```

**Comment by mratsim** [comment]
This works for me, from my experience, if you want generics, even as parameter, it must be declared in [T] too to avoid compiler complaining, not sure if intended though:
```Nim
proc mycast[T](a: int, dummy_typedesc: typedesc[T]): T =
   a.T

echo mycast(1, float32)
```

**Comment by narimiran** [comment]
Works correctly with Nim 0.19.9
