### ISSUE TITLE
Exports not showing up in doc gen for asyncdispatch

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6412]
https://nim-lang.org/docs/asyncdispatch.html

No exports section.

Also docs for ``asyncfutures`` aren't being generated.

**Comment by skellock** [comment]
Is this still an issue?  

## asyncdispatch

The docs for `asyncdispatch` are showing the exports section as of Oct 2, 2018 (a year later).

![image](https://user-images.githubusercontent.com/68273/46388887-dd9c3580-c69c-11e8-86f8-63d397d9b1db.png)

## asyncfutures

Also `asyncfutures` [seems to exist](https://github.com/nim-lang/Nim/blob/afd5b003105cadda78e5a4a8bd9b91ca95ac0972/tools/kochdocs.nim#L199) now too:

![image](https://user-images.githubusercontent.com/68273/46388940-2b18a280-c69d-11e8-94ca-340a5144875a.png)


Does that seem right nowadays?

**Comment by dom96** [comment]
Yay, looks like it's fixed :)
