### ISSUE TITLE
`nim c` writes executable to unexpected location

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#6413]
Given a directory structure as follows:

```
└───src
    │   hello.nim
```

You would expect that running `nim c src/hello.nim` from the root would write `hello.exe` to the root, resulting in a tree like:

```
│   hello.exe
│
└───src
    │   hello.nim
    │
    └───nimcache
            hello.c
            hello.json
            hello.o
            stdlib_system.c
            stdlib_system.o
```

In actual fact, it writes the output executable into the `src` directory:

```
└───src
    │   hello.exe
    │   hello.nim
    │
    └───nimcache
            hello.c
            hello.json
            hello.o
            stdlib_system.c
            stdlib_system.o
```

This can be a bit surprising and causes problems when you have a nimble package following the recommended structure:

```
└───src
    │   hello.nim
    │
    ├───hello
    │       test.nim
```

Running `nim c src/hello.nim` in this case will fail on posix systems as the name `hello` already exists as a directory.

**Comment by mratsim** [comment]
Now I remember why compiling Nim toy code always needed very long line like
```bash
nim c --out:bin/toycode --nimcache:./nimcache -r subdir/toycode.nim
```
Nimcache is also in the subdirectory by the way

**Comment by dom96** [comment]
I think where the .exe is written makes sense. @Araq mentioned a way to overcome this Nimble gotcha though, I can't remember what his plan was though.

**Comment by euantorano** [comment]
I can't think of a single tool that acts in this way though other than Nim, which makes the behaviour completely non obvious to me.

**Comment by Araq** [comment]
This behaviour is very useful for ``staticExec"nim c tool/helper"`` so that you know where the helper.exe will reside in. ``cwd`` is more fragile. You can use ``--out`` to influence the result anyway, nothing wrong here.

**Comment by dom96** [comment]
I'm reopening this to fix the Nimble-related gotcha.

**Comment by Araq** [comment]
Open a Nimble bug instead.

**Comment by dom96** [comment]
This isn't a Nimble bug... it requires changes in the compiler. And I do recall you coming up with a solution to it a while ago.

**Comment by timotheecour** [comment]
@Araq  @dom96 can we close this? `nim c src/hello.nim` now creates `src/hello.out` in case of clash
