### ISSUE TITLE
Return semantics vary depending on return style

### ISSUE THREAD

**Issue by obadz** [nim-lang/Nim#6422]
```nim
proc toCharArray1(N : static[int], s: string): array[N, char] =
    doAssert s.len < N
    let x = cast[ptr array[N, char]](s.cstring)
    x[]

proc toCharArray2(N : static[int], s: string): array[N, char] =
    doAssert s.len < N
    let x = cast[ptr array[N, char]](s.cstring)
    result = x[]
    
let x = toCharArray1(10, "abc")
let y = toCharArray2(10, "abc")
echo "x = ", $x, " and y = ", $y
```
I'd expect to see `"x = abc and y = abc"` but instead I get `"x =  and y = abc"`
Tested with nim version 0.17.0.

**Comment by obadz** [comment]
(Incidentally, if there's a better way to turn a `string` into an `array[N, char]` I'd love to know..)

**Comment by andreaferretti** [comment]
As far as I know, you need to either use `return` or assign the `result` variable, unless the body is a single expression, in which case just putting the expression without `return` will do

**Comment by GULPF** [comment]
> As far as I know, you need to either use return or assign the result variable, unless the body is a single expression, in which case just putting the expression without return will do.

>In other words, it is not that the semantics changes based on return style, rather putting an expression on the last line is not returning at all (unlike, say, in scala)

I don't think that's correct. This works and prints `x = abc and y = abc`:

```nim
proc toCharArray1(N : static[int], s: string): ptr array[N, char] =
    doAssert s.len < N
    let x = cast[ptr array[N, char]](s.cstring)
    x

proc toCharArray2(N : static[int], s: string): array[N, char] =
    doAssert s.len < N
    let x = cast[ptr array[N, char]](s.cstring)
    result = x[]
    
let x = toCharArray1(10, "abc")
let y = toCharArray2(10, "abc")
echo "x = ", $(x[]), " and y = ", $y
```

**Comment by Araq** [comment]
> As far as I know, you need to either use return or assign the result variable, unless the body is a single expression, in which case just putting the expression without return will do

This is not restricted to single expressions.
