### ISSUE TITLE
Random number generation isn't random when executed at compile time

### ISSUE THREAD

**Issue by OrangeFlash81** [nim-lang/Nim#6424]
I am trying to use this code to generate 100 random numbers between 1 and 1000 at compile time, as part of a macro:

```nim
import random

macro x(): untyped =
    var randomNumbers: seq[int] = @[]

    for i in 1..100:
        randomNumbers &= random(1000)
    
    echo $randomNumbers

x()
```

However, `randomNumbers` always ends up with all elements being 87; here is the compilation output:

```nim
Hint: used config file 'C:\Program Files\Nim\nim-0.17.2\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: randomNumberBug [Processing]
Hint: random [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
@[87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87]
Hint:  [Link]
Hint: operation successful (17907 lines compiled; 0.453 sec total; 28.027MiB peakmem; Debug Build) [SuccessX]
```

If `random`'s argument is changed, then the repeated number is different, but is still not random.

I tried to use the `randomize` proc, but it's a C import and those aren't available at compile time.

I'm using Nim 0.17.2 with GCC 6.3.0 on Windows 10.

**Comment by Yardanico** [comment]
@OrangeFlash81 you should call randomize() with some seed at compile-time

**Comment by OrangeFlash81** [comment]
@Yardanico Oh, thanks - I didn't realise `randomize` accepted an argument. What's best to use for a seed - is there a Nim equivalent to C's `time(NULL)`?

**Comment by dom96** [comment]
The VM does not support the FFI (which the times module depends on). So the best thing you can do is (Unix-only):

```nim
import random, strutils

macro x(): untyped =
    randomize(staticExec("date +'%s'").parseint)
    var randomNumbers: seq[int] = @[]

    for i in 1..100:
        randomNumbers &= random(1000)
    
    echo $randomNumbers

x()
```

You can create your own executable that spits out the current time and call that for cross-platform compatibility, or just use whatever command Windows provides.
