### ISSUE TITLE
deprecated proc should be seen as deprecated from the documentation

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6425]
Besides the text, there is no visual difference for procs with pragma {.deprecated.}.
I think it would be better for nim docgen to have a specific style for deprecated things

Some suggestions:
- Display deprecated
- Italicize the text
- Have a greyer background

**Comment by hlaaftana** [comment]
Strikethrough perhaps?

**Comment by awr1** [comment]
Where deprecation is (already) mentioned in the Nim docs, the version number by which it began to be deprecated in usually mentioned. How important is this? If it's important, do we want some mechanism that keeps track of whatever `NimVersion` is when a new deprecation is added and we generate the docs? (How would other projects besides the Nim compiler be able to use this?)

**Comment by dom96** [comment]
It's useful in answering the question of "How urgently do I need to fix code which uses this?"

The longer the procedure has been deprecated the higher the chance it'll be removed in the next release.

**Comment by awr1** [comment]
Thought about it a little again and the idea of auto-tracking the version of deprecation, whilst fancy, would probably be too complicated. Maybe you could do some weird thing where you can define a version string to the compiler and original version numbers of deprecated symbols could be recorded in JSON, but this all feels like too messy of an idea...

At the very least, what about an optional two-string tuple argument for `{.deprecated.}`, e.g. 
```nim
proc foo() {.deprecated: ("1.0.0", "Use bar() instead.").}
```

**Comment by narimiran** [comment]
Currently (Nim 1.3.x, and probably for some time already), if a procs is marked with `{.deprecated.}` or `{.deprecated: "deprecation message".}`, that will be shown as a first line in the documentation under the proc header.
