### ISSUE TITLE
random lib and return value type issue

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6432]
[This random proc](https://github.com/nim-lang/Nim/blob/master/lib/pure/random.nim#L84) is surprising with float32:
`proc random*(max: float): float`

According to the signature it should only accepts floats and not float32, but it does accept float32. And confusingly even if input is float32, output is float, except if you force it at float32.

One of the two behaviour is expected:
    1. Accept float only and returns float only, as per the type signature
    2. Accept T: SomeReal but return T (so if float32 return float32, if float return float)

Test case
```Nim
import random, typetraits
let a = random(10'f32)
echo a.type.name # float

let b: float32 = random(10'f32)
echo b.type.name # float32
```

**Comment by Araq** [comment]
``float32``  converts to ``float``.
