### ISSUE TITLE
Seq assignment is slower than expected

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6433]
While doing some benchmarks in nim, I've noticed that all my methods that did copy on a `seq[float32]` via assignment was actually slowing performance down more than math float operations. The following test case demonstrates

Test case:
```Nim
import times, sequtils

proc newSeqUninitialized[T](len: Natural): seq[T] {.noSideEffect,inline.}=
  result = newSeqOfCap[T](len)
  result.setLen(len)

let size = 1000000
var data = newSeqWith(size, -3.67'f32)
var s1, s2 : seq[float32]
var start: float

start = cpuTime()
for i in 0..<10000:
  s1 = newSeqUninitialized[float32](size)
  copyMem(s1[0].addr, data[0].addr, size*sizeof(float32))
echo "copymem ", cpuTime() - start

start = cpuTime()
for i in 0..<10000:
  s2 = data
echo "assignment ", cpuTime() - start

assert s1[0] == s2[0]
assert s1[size-1] == s2[size-1]
```

Outputs:
```
copymem 4.339192000000001
assignment 51.280579
```

*NOTE: Compiled with -d:release and latest nim*

Compared with copyMem it's in the order of 10x slowdown.

As my use case is deep learning, I do need to copy huge seqs in the order of 1000000 floats, thousands of times per second for traning a small deep neural network.

This example already show the slowdown, however in my program it's even slower.

**Comment by Parashurama** [comment]
If i remember right, it's because copying seq[non GCref type] doesn't yet use memcpy, but rather follow same path as seq[GC-ed type]. ie: copy each items individually.

It may have changed since then, but it would explain your slow down.

**Comment by edubart** [comment]
My perf shows genericAssignAux at 95% cpu usage, I've read the code at
https://github.com/nim-lang/Nim/blob/07cf7d3340734eaf400a09eade04b6493e9a34a1/lib/system/assign.nim#L55
indeed it does a for loop over the seq, even more it casts and does call itself in this for loop for each float instance, now its clear why the performance was bad..
