### ISSUE TITLE
{.deprecated.} gives false warning on proc with typedesc arg

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6436]
I'm trying to deprecate some procs to use foo\[T\](arg) instead of foo(arg, T) syntax.

However deprecating foo(arg, T) gives deprecation warning even for foo\[T\](arg) syntax:

```Nim
proc foo(size: int, T: typedesc): seq[T]  {.deprecated.}=
  result = newSeq[T](size)


proc foo[T](size: int): seq[T]=
  result = newSeq[T](size)


let bar = foo[int](10) # Warning foo is deprecated

echo bar
```

**Comment by zah** [comment]
This is not related to the issue, but what problems did you have with the deprecated typedesc alternative? Overloading with typedesc is actually the better-supported and recommended API for mandatory type arguments.

**Comment by mratsim** [comment]
Familiarity and consistency. I type someProc[T](foo) almost everywhere and I end up typing the same the procs I shouldn't.
Muscle memory is hard to beat so embrace it.

**Comment by narimiran** [comment]
No false warnings on Nim 0.19.9
