### ISSUE TITLE
shallow copying does not seem to work

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#644]
Doing a shallow copy of strings (or objects containing strings) does instead seem to perform a regular copy. Unless I'm missing something, the generated code seems to be identical for both shallowCopy and a normal assignment.

``` nimrod
var s = "x"
var t: string
shallowCopy t, s
add(s, "y")
echo t

type StrObj = object {. shallow .}
  str: string

var sobj = StrObj(str: "x")
var tobj: StrObj
tobj = sobj
add(sobj.str, "y")
echo tobj.str

sobj = StrObj(str: "x")
shallowCopy tobj, sobj
add(sobj.str, "y")
echo tobj.str
```

Further experimentation indicates that the problem with shallowCopy goes away when putting the code inside a proc (i.e., when variables are local rather than global); however, the shallow pragma still appears to be ignored.

**Comment by rbehrends** [comment]
After reconsidering this issue, I believe the problem lies with `shallowCopy` accepting a non-var parameter as its RHS. A version where both lhs and rhs are var parameters, should be safe. One solution would be to deprecate `shallowCopy` as `unsafeShallowCopy` to make explicit that you're doing something very similar to taking the `addr` of the rhs and to create a safe version, e.g.:

```nim
proc shallowAssign[T](lhs: var T, rhs: var T) {.noSideEffect, magic: "ShallowCopy".}
```

**Comment by alaviss** [comment]
With the introduction of ARC and move semantics, is this issue still relevant @Araq?

**Comment by Araq** [comment]
Indeed.
