### ISSUE TITLE
One can define polymorphic proc that cannot be called

### ISSUE THREAD

**Issue by olwi** [nim-lang/Nim#6440]
Nim forum discussion is here: https://forum.nim-lang.org/t/3201

Two arrays of the same size and element type but with different index boundaries seem to be distinct types for the purpose of (polymorphic) proc definitions, so this compiles:
```nim
proc p(a: array[10, int]) = discard
proc p(a: array[-1 .. 8, int]) = discard
```
but they seem to be treated as identical when attempt to call this proc is made, so this:
```nim
var a: array[10, int]
p(a)
```
fails to compile with the following error message:
```
test.nim(6, 2) Error: ambiguous call; both test.p(a: array[0..9, int])[declared in test.nim(1, 5)] and test.p(a: array[-1..8, int])[declared in test.nim(2, 5)] match for: (array[0..9, int])
```
Nim compiler version:
```
> nim -v
Nim Compiler Version 0.17.2 (2017-09-07) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release
```

This leads to rather paradoxical situation that you can define (polymorphic) proc that you cannot call.

**Comment by Araq** [comment]
I see no problem here. This paradoxical situation is not all that uncommon in other programming languages either.
