### ISSUE TITLE
Provide module name

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6443]
It would be nice to have a way to access the current module name so that one can prefix symbols with module name like ThisModule.activate() or self.activate(). Most other languages support this feature, I think for Python it is __name__. Use case is avoiding ambiguity without necessary to fixing the module code when module is renamed. One example was https://forum.nim-lang.org/t/3192 where it is necessary that proc names which are passed typed to macros are unique, but I think there are more use cases.

**Comment by Yardanico** [comment]
you can do that

**Comment by zah** [comment]
Already supported with `system.currentSourcePath`:
https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L3622

**Comment by StefanSalewski** [comment]
Great. Unfortunately I am not sure if that is what I want. How can I make the last line of this source code compile and work?

```nim
# nim c test4.nim
proc p7 = echo "called proc p7 of module test4"

p7()

test4.p7()

echo currentSourcePath()

currentSourcePath.p7() 
```

**Comment by Yardanico** [comment]
@StefanSalewski you would get currentSourcePath() in macro, remove .nim and past it into source code

**Comment by StefanSalewski** [comment]
Yes, then I can write

```nim
  qualifyMyProcNameWithModulePrefixAndExcecuteIt(p7)
```

ThisModule.p7() or Self.p7() would be a bit shorter still :-)

But I have to admit: ThisModule or Self prexix may be not well defined for use inside of macros. Would it give the module name containing the macro or the module name from which the macro is called?

**Comment by Yardanico** [comment]
@StefanSalewski you can do that with lineinfo:
```nim
import macros, strutils

macro a(data: untyped): untyped = 
  # echo module where this node is placed
  echo data.lineinfo.split(".nim(")[0]
  result = data

```
