### ISSUE TITLE
getTimezone returning incorrect results

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#6450]
Hi there.

I'm on Nim release 0.17.2.

My OS is 64-bit Linux (Debian Sid).

Am in timezone SAST, +0200.

I'd expect times.getTimezone() to return -7200, but instead it returns 0.

Here's a workaround function my code has, to return the correct figure:

```
proc getLocalTimeZone(): int =
  return getLocalTime(getTime()).timezone
```

**Comment by Bennyelg** [comment]
Osx same as Linux, validated and yepm -7200.

**Comment by GULPF** [comment]
I noticed that the timezone becomes correct after calling either `getLocalTime` or `getGmTime` for the first time

```nim
echo getTimeZone() # 0
discard getGmTime(getTime())
echo getTimeZone() # -3600

```

**Comment by GULPF** [comment]
This is fixed by https://github.com/nim-lang/Nim/pull/6466
