### ISSUE TITLE
Nim should have a time type that includes fractional seconds.

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#6451]
At the moment, for broken down date and time info, we have the TimeInfo type.

That matches the C struct, but unfortunately doesn't have a floating-point second.

Here's a structure I'm using in my code that attempts to work around that:

```
type TimeStamp = object
  timeInfo: TimeInfo
  secondFloatpart: float
```

And then a couple of functions I use to work with that:

```
proc initTimeStamp(timeInfo: TimeInfo, secondFloatPart: float): TimeStamp =
  assert secondFloatPart >= 0
  assert secondFloatPart < 1
  return TimeStamp(timeInfo: timeInfo, secondFloatpart: secondFloatpart)

proc toFloat(x: TimeStamp): float =
  return x.timeInfo.toTime.float + x.secondFloatpart
```

Ideally TimeInfo would have a "microsecond" field, similar to Python's datetime.datetime class.

**Comment by cheatfate** [comment]
@andreaferretti please add label `feature request` too. This is not a bug.

**Comment by andreaferretti** [comment]
Makes sense :-)
