### ISSUE TITLE
mingw installed via finish.exe fails to link if Nim located in path with whitespace

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/Nim#6452]
Sorry to kick off the return from my one year abstinence with a bug report, but here it is...

On Windows, when installing mingw via Finish.exe, compilation of Nim programs will fail in the linking stage if Nim (and hence mingw) was installed in a path that contains whitespace. 

Repro steps:

1. Download nim-0.17.2_x64 from https://nim-lang.org/install.html
2. Unpack zip into "C:\Program Files\Nim\" or "C:\Nim Test\" (note that there is a space in the paths)
3. Run finish.exe and let it fetch mingw (will be installed in e.g. "c:\Program Files\Nim\dist\")
4. Try to compile any Nim program

Result: Compilation fails during link phase with "Error: invocation of external linker program failed. Access denied."

Expected: Compilation succeeds.

Workaround: Install Nim in path that does not contain spaces, i.e. "C:\Nim\"

**Comment by Araq** [comment]
This is a ``nim`` bug, not a ``finish.exe`` bug.
