### ISSUE TITLE
typetraits feature request - get subtype of a generic type

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6454]
I need to get the subtype of of generic parameter inside a function. I see that there is a genericHead in typetraits that get the "container". I would love to have a way to get the subtype.

> seq[int].genericHead will be just seq

Use case, use TT.genericTail instead of "int" in the following proc

```Nim
proc Foo[TT](a: TT): array[2, TT] =
  result[0] = newSeq[int](10)
```

Note this can also be solved with generic generics https://github.com/nim-lang/Nim/issues/3856

**Comment by mratsim** [comment]
Found a workaround with:

```Nim
macro getSubType(T: typedesc): untyped =
  getTypeInst(T)[1][1]

proc Foo[TT](a: Node[TT]): array[2, TT] =
  result[0] = newSeq[getSubType(TT)](10)
```

**Comment by zah** [comment]
This issues was closed by accident, reopening.
