### ISSUE TITLE
Compiler crashes on ptr void

### ISSUE THREAD

**Issue by obadz** [nim-lang/Nim#6456]
The Nim compiler seems to crash when objects have a `ptr void` member and neither give an explicit error message nor a line number. For example:

```nim
type
    a* = object
        b*: int
        c*: ptr void  
    
proc main() =
    var x = a(b: 4)
    echo $x.b

main()    
```
Yields:

```
Error: internal error: getTypeDescAux(tyVoid)
Traceback from system (most recent call last)
```
(No tracebacks provided)

Tested with nim version 0.17.0.

**Comment by Yardanico** [comment]
@obadz yeah, it shouldn't crash, but you can't do "ptr void"
use "pointer" instead
```nim
type
    a* = object
      b*: int
      c*: pointer 
    
proc main() =
    var x = a(b: 4)
    let a = "hello"
    x.c = cast[pointer](a)
    echo cast[int64](x.c)  # Pointer as int :)
    echo cast[string](x.c)

main()
```

**Comment by obadz** [comment]
@Yardanico,

It took me a while to realize this was even causing the error because of the lack of error message / line number.

Also I didn't put this ptr void there, c2nim did.

I replaced by `pointer`.

**Comment by zah** [comment]
Fixed in https://github.com/nim-lang/Nim/pull/8127

**Comment by shirleyquirk** [comment]
same crash on
```nim
import sharedlist
var s:SharedList[void]
s.init()
```
obvs low priority, just sayin.
