### ISSUE TITLE
Redundant memset for objects holding seqs

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6458]
This code:
```Nim
type Foo = object
  size: int
  data: seq[int]

proc newFoo(): Foo {.inline.} =
  discard

proc main() =
  var a = newFoo()

main()
```

Generates this C code with `-d:release`
```C
N_NIMCALL(void, main_gkzuRuXidpry9aEX9acGKfSw)(void) {
	tyObject_Foo_3Blw9a0Y0XV66g6o3A9cX9a7Q a;
	memset((void*)(&a), 0, sizeof(a));
	chckNil((void*)(&a));
	memset((void*)(&a), 0, sizeof(a));
	newFoo_Ov9ahZG9aQFilGFUNX86r3rwtest2((&a));
}
```

There is an additional redundant `memset`, and also an unnecessary `chckNil` (&a will always be a valid pointer because we are on the stack).

Changing `data` from `seq[int]` to something simple type like `int` generates what I would expect:

```C
N_NIMCALL(void, main_gkzuRuXidpry9aEX9acGKfSw)(void) {
	tyObject_Foo_3Blw9a0Y0XV66g6o3A9cX9a7Q a;
	a = newFoo_Ov9ahZG9aQFilGFUNX86r3rwtest2();
}
```

Thus there are some optimizations that could be done in the C code generator for objects that holds seqs (skipping that `chckNil` and `memset`)

**Comment by Yardanico** [comment]
https://github.com/nim-lang/Nim/issues/4168 ?

**Comment by edubart** [comment]
Actually there is no much problem with those redundant memsets, I've checked that gcc optimizes out the double call, just the chckNil it doesn't.

**Comment by edubart** [comment]
I've checked the GCC assembly output, if the `chckNil` wasn't there, the gcc would optimize out the second memset, so the fix here could be potentially to just remove the unecessary `chckNil` call.

**Comment by ringabout** [comment]
seq isn't nil anymore.
Now it generates

```c
static N_INLINE(void, newFoo_foo_4)(tyObject_Foo__FIDSNwXGF9aFdRLolyuTS0g* Result) {
	(*Result).size = 0;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
}
N_LIB_PRIVATE N_NIMCALL(void, main_foo_6)(void) {
	tyObject_Foo__FIDSNwXGF9aFdRLolyuTS0g a;
	nimZeroMem((void*)(&a), sizeof(tyObject_Foo__FIDSNwXGF9aFdRLolyuTS0g));
	newFoo_foo_4((&a));
}
```
