### ISSUE TITLE
Trying to use `object or `tuple` typeclass as a variable's type crashes compiler (internal error)

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#6461]
Both this
```nim
var o: object
```
and this
```nim
var o: tuple
```
result in "Error: internal error: getTypeDescAux(tyBuiltInTypeClass)".

**Comment by andreaferretti** [comment]
The compiler should not crash in the first place, rather output a sensible error message. Still, the code above of course cannot work, since these are non concrete types

**Comment by Leu-Gim** [comment]
Yeah, I understand, the issue is about crash instead of displaying the error message.

**Comment by GULPF** [comment]
Fixed by https://github.com/nim-lang/Nim/commit/fa0f5d0238d5656ace070b86ecc9cdec60568fdb

**Comment by andreaferretti** [comment]
I confirm this is fixed
