### ISSUE TITLE
import statements not resolving paths correctly?

### ISSUE THREAD

**Issue by koranza** [nim-lang/Nim#6463]
I have a program that doesn't compile after running `choosenim devel`  today and compiling with `nim c test.nim` 

```nim
# name: test.nim
import nimqml
echo "hello world"
```

`/home/[USERNAME]/.nimble/pkgs/nimqml-0.7.1/nimqml.nim(13, 16)`
`Error: cannot open 'private/dotherside/nim'`

The corresponding line reads: 
`include private/dotherside.nim`

However, the error message says it's trying to look up "/nim" instead of the ".nim" extension

**Comment by Araq** [comment]
The ``include`` should leave out the ``.nim`` extension.
