### ISSUE TITLE
Behavior for adding days with TimeInterval

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6465]
Due to DST, this happens in my timezone:
``` nim
let d = parse("2017-03-25 12:00", "yyyy-MM-dd hh:mm")
echo d          # 2017-03-25T12:00:00+01:00
echo d + 1.days # 2017-03-26T13:00:00+02:00
```
By adding a day, the time changed with one hour. This is arguably not a bug. F.ex Pythons `timedelta` assumes a day is always 24 hours. On the other hand, `timedelta` doesn't allow years and months, so it always represents a fixed amount of time (with the assumption that a day is 24 hours).

Since `TimeInterval` handles months and years, it already represents a non-fixed amount of time, so in my opinion it would make sense to handle days as non-fixed as well. This is also how Java's `Duration` class handles it.

**Comment by Bennyelg** [comment]
By running your example exactly as it is I get
2017-03-25T12:00:00+03:00
2017-03-26T12:00:00+03:00

**Comment by GULPF** [comment]
Well, the result depends on your timezone. The issue is that in my timezone (Europe/Stockholm) DST activates on 26/3, which means that there is only 23 hours between 2017-03-25T12:00:00 and 2017-03-26T12:00. On linux you you can reproduce it by running `TZ=Europe/Stockholm ./program`.

**Comment by FedericoCeratto** [comment]
@GULPF the related PR implement tests across timezones
