### ISSUE TITLE
instantiationInfo does not give proper filename or line number

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/Nim#6469]
It looks like the instantantiationInfo proc doesn't give filename or line number (using current HEAD of devel).

```nim
proc main()=
  echo instantiationInfo()

when isMainModule:
  main()
```
gives `(filename: ???, line: -1)`

**Comment by citycide** [comment]
You need to use it inside a compile-time construct, since Nim will only know what your file and code is when it's compiling it.

like a `template`:

```nim
template getFileInfo () =
  let (file, line) = instantiationInfo()
```

or a compile time `proc`:

```nim
proc getFileName (): string {.compileTime.} =
  result = instantiationInfo(fullPaths = true).file

const filename = getFileName()
```

**Comment by singularperturbation** [comment]
Thanks @citycide - I was originally calling this from a compile-time proc and was getting the same error.
It looks like I can still get it to work from a proc (not a template) if I do:

```nim
proc getFileName(): static[string] =
  instantiationInfo(fullPaths = true).filename

const fullFile: string = getFileName() & " HEY"

when isMainModule:
  echo fullFile
```

**Comment by citycide** [comment]
Nice, now I've picked up `static[T]`!

I'd guess with the general rule of `simple --> advanced` that a static proc like this would be preferred over a template?

**Comment by lightness1024** [comment]
this is so wrong. Nim just had to expand the call at compile time and be a good boy. putting stuff in a template to get it to work rapes the principle of least astonishment.

**Comment by Araq** [comment]
> rapes the principle of least astonishment.

Maybe if you completely ignore its very name **instantiationInfo**. The principle of least astonishment has actually very little to do with "I'm unable to read".

**Comment by zah** [comment]
ibn4 `currentSourcePath`
