### ISSUE TITLE
Cannot disable nil checks

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6479]
I want to disable nil checks, they do seem to appear in C generated code even when compiling with `-d:release` the only possible way to disable them is to pass `--checks:off` but I dont want to disable all checks, just the nil checks, so `--nilChecks:off` is missing.

**Comment by mratsim** [comment]
In this [RFC](https://github.com/nim-lang/Nim/issues/3531), it appears that Nim does not have (robust?) enough nil checks.

**Comment by edubart** [comment]
This is done by https://github.com/nim-lang/Nim/pull/6480
