### ISSUE TITLE
Windows backslash missing: "import ./foo/[bar, baz]" not working on windows 

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6485]
From this Appveyor report - https://ci.appveyor.com/project/mratsim/arraymancer/build/315#L95:

This line:
```Nim
import  ./activation/[sigmoid, relu]
```

is interpreted as
`'.activation\sigmoid'`

So a backslash is missing

**Comment by Araq** [comment]
Can't reproduce, for me ``import ./lib/pure/[encodings, strutils]`` works.
