### ISSUE TITLE
expandFilename works only on existing files and directories.

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6486]
Also, the documentation does not mention this behavior.

**Comment by dom96** [comment]
So unless there is a use case for this I think it's fine to just document this behaviour.

**Comment by FedericoCeratto** [comment]
Expanding file names is very common for logging (you don't want to log out a relative path). A typical use case is to log out that you are going to create a file before doing so.

**Comment by andreaferretti** [comment]
I think one reason it work like that is symlinks (assuming this function also resolves them). You cannot expand the filename without knowing whether some intermediate part is a symlink, and for that you have to touch the filesystem and work on existing paths. If instead this is a pure function with no reference to the filesystem, it makes sense that it works at an abstract level without requiring files to exist

**Comment by Araq** [comment]
I think it's fine.

```nim

proc expandFilename*(filename: string): string {.rtl, extern: "nos$1",
  tags: [ReadDirEffect], noNimScript.} =
  ## Returns the full (`absolute`:idx:) path of an existing file `filename`.
  ##
  ## Raises `OSError` in case of an error. Follows symlinks.
```
