### ISSUE TITLE
Edit button on online manual

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6492]
The manual at https://nim-lang.org/docs/manual.html could have a very visible "Edit" button on each chapter using the seeSrc mechanism from https://github.com/nim-lang/Nim/blob/devel/config/nimdoc.cfg#L55 to encourage contributions.

**Comment by Araq** [comment]
Well, go for it.

**Comment by ringabout** [comment]
This issue has been fixed in devel.
http://nim-lang.github.io/Nim/manual.html
