### ISSUE TITLE
Pragma codegenDecl doesn't work inside iterators

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6497]
I need to use `__restrict__` C keyword inside an iterator, but when inside an iterator codegenDecl does not work, test case:

```Nim
iterator myitems(s : seq[int]): int =
  var data {.codegenDecl: "$# __restrict__ $#".} :ptr int = nil
  yield 1

for i in @[1].myitems:
  discard
```

This generates the following C code:

```C
		NI* data;
		nimln_(2, "test2.nim");
		data = NIM_NIL;
```

`NI* data` should have been `NI* __restrict__ data`

Any workarounds? I want to use restrict to make GCC optimize my iterator better.

**Comment by ringabout** [comment]
The issue is at `transformVarSection` in `transf.nim`.
