### ISSUE TITLE
Internal error for tuples with some procs inside

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#6499]
```nim
let x = (chr, 0) # can be anything as the 2nd argument
```
causes "internal error: proc has no result symbol" in `cgen.nim`/`genProcAux`.
The same for `toU8`, both "magic".

**Comment by Yardanico** [comment]
ag

**Comment by mratsim** [comment]
Probably related to built-ins cannot be passed as procvar: https://github.com/nim-lang/Nim/issues/2172

**Comment by narimiran** [comment]
This doesn't produce an error anymore with Nim 1.5
