### ISSUE TITLE
Limitation of parseExpr within templates

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#6508]
`parseExpr` does not seem to resolve variable names properly within templates. For instance:

```nimrod
import macros

macro parse(e: string): untyped =
  result = parseExpr($e)

block:
  # works
  let x = 1
  echo parse("x") 

block:
  # works
  proc test(x: int) =
    echo parse("x")
  test(1)

block:
  # fails with: Error: undeclared identifier: 'x'
  template test(x: int) =
    echo parse("x")
  test(1)
```

A work-around is to write the template as:

```nimrod
  template test(x: int) =
    let xLocal {.inject.} = x
    echo parse("xLocal")
  test(1)
```

This is in general a minor issue, but it becomes a pretty ubiquitous problem when trying to use string interpolation a la `fmt"$x"`. The implementations rely on `parseExpr` and in order to make the string interpolation work a lot of ugly `injects` variables or even `dirty` templates are required.

**Comment by Araq** [comment]
This is how template expansion works, parameters are replaced by the arguments that are passed to the template. They are not replaced inside string literals, how could they? 

Can't be fixed.

**Comment by bluenote10** [comment]
Okay, that probably makes sense. I was hoping that it is possible to use some compiler magic to "store" the symbol names from a template in each occurrence of `parseExpr` and at the point of evaluation it looks up regular symbols plus the attached template symbols. But that's probably not how symbol lookup works.
