### ISSUE TITLE
Line Too Long should ignore comments.

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#6519]
Currently, in version 0.17.2 (2017-09-07) when enabling the compiler option LineTooLong

In nim.cfg:
  hint[LineTooLong]=on

**Nim reports commented lines. It should ignore those, and only regard actual code.**
Possible steps forward are either:   
- To remove comments and then check 
- or find the string position where comments start which is the end of the line. (unless the # sign is within a string)
I am guessing it should be easy to fix, but I don't really have any idea about the internal workings.

Thank you!

**Comment by Araq** [comment]
Comments are part of the source code. Why should they be special and subject to the line length limit?

**Comment by kobi2187** [comment]
As far as I understand, limiting code's line length aims to improve readability and keeping things more concise, in effect, urging refactoring of messy code, or long chains of operations.
Comments have a different purpose. They describe what happens. Even though "omit needless words" is a fine principle for writing, putting constraints when a developer finally adds some comments may put him off from doing it :-)
don't you agree?

**Comment by Araq** [comment]
The line length limit has nothing to do with enforcing refactorings. It's just that many editors still suck at automatic line wrappings so people have to do it manually. This includes comments, the problem is that horizontal scrolling is very annoying to do. And many people like narrow windows so that two can fit on the same screen.

**Comment by citycide** [comment]
I agree - I don't think comments should be excluded from this. As an example I was going through `libui`'s C++ source recently and a lot of its comments are [ungodly long](https://github.com/andlabs/libui/blob/5fa7ba487e67eaffd82cacbdecd014a4ede5bb1e/windows/areaevents.cpp#L25). Definitely an annoyance.

**Comment by kobi2187** [comment]
I understand. Thanks for the consideration.
