### ISSUE TITLE
A way to poll() completing all operations that can be completed immediately

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#6523]
In cases where you don't want poll() to block execution, you also want it to complete all operations that can be completed immediately in single call. However, poll() performs at most one operation on each file descriptor and you don't have a way to know if calling poll(0) again makes sense.

One way to resolve this is to make poll return a bool indicating whether any operation was performed during the poll. Then you could call poll(0) in a loop while it performs any operation (calls any callback). As soon as it doesn't, you can move further.

**Comment by Yardanico** [comment]
@endragor Can't you use hasPendingOperations for that?

**Comment by endragor** [comment]
No, hasPendingOperations simply indicates whether there are any registered handles. You don't know whether you can do something immediately until you invoke the underlying selector.

**Comment by endragor** [comment]
Although maybe it's actually a problem of implementation that calling poll(0) multiple times can be more beneficial than doing it once. poll(0) could execute all operations on single descriptor until something returns EWOULDBLOCK. From what I see in the code, it is actually what happens on posix systems, but the problem I encounter happens on Windows. I'll try to prepare a code sample where the problem can be seen.

**Comment by endragor** [comment]
The problem can be seen both on macOS and Windows - tried doing poll(0) 10 times and it performs more operations than if called once.

**Comment by yglukhov** [comment]
@endragor, please have a look at #6614. That should do what you want as a side effect.

**Comment by endragor** [comment]
I'm not sure how that would help this particular problem, but that PR is definitely useful in general.

This problem is about the case when you have to do instant polls (`poll(0)`), but would like to use all available capacity of a single socket that can be used without blocking. You usually want this in games - you can call poll(0) between frames to read/send data without blocking. (you can also try to do this with multiple threads, but it makes things overly complicated).

For example, current async HTTP client code is implement this way:
```
while true:
  let line = await client.recvLine()
  # process line
```
With current implementation if you call poll(0) once, only one line will be processed, even if OS already has the whole response in its queue waiting for you to retrieve it. So if you call `poll(0)` once per frame, it means you receive only up to 1 line of HTTP headers per frame, which obviously doesn't make sense. Similar problem occurs with any other protocol, too, because networking code is usually structured like:
```
while true:
  let packet = await s.recvPacket()
  # process packet
```
And this structure does not imply that you want to process only one packet per poll() call. You usually want to process all that is available.

**Comment by yglukhov** [comment]
@endragor, correct me If I'm wrong, but thats what you're gonna get with my pr merged *if* `client.recvLine()` completes the future immediately when there is enough data. My PR makes it so that all cascading futures will complete in one go.

**Comment by yglukhov** [comment]
e.g. if one completion callback completes subsequent future, the second completion callback will be fired before returning from `complete` of the very first completion callback. You can call that recursion  from some perspective.

**Comment by endragor** [comment]
The way receive/sends are currently implemented at the lowest level, is that they just register a callback for read/write event for the specific socket, so they will never complete immediately. Otherwise probably yes, that would work. In fact there is:

```
    # TODO: The following causes a massive slowdown.
    #if not cb(socket):
    addRead(socket, cb)
```
So if that commented line is removed, it should probably work as you described.

**Comment by dom96** [comment]
> So if that commented line is readded, it should probably work as you described.

We should try this instead of adding ``drain``. There is a reason I disabled it but that was a long time ago and I probably ran into some other bug (which was hopefully fixed in the meantime).

**Comment by Araq** [comment]
``proc drain`` exists now and is what I think was requested.
