### ISSUE TITLE
Feature request: Variable length arrays (stack arrays)

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#6524]
GCC and some other compilers supports variable length arrays, see https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html
and they are allowed in ISO C99.

The advantage of variable length arrays is that they usually are allocated on stack (but not always), thus much faster because:

- There is no need to find and allocate a memory region on the heap (`malloc` + `free`)
- Reading and writing to stack memory can be faster

They can be also implement using `alloca`, thus could be implemented without touching the C codegen, a brief of it's usage in `man 3 alloca`:

> SYNOPSIS
>        #include <alloca.h>
>        void *alloca(size_t size);
>
> DESCRIPTION
>        The alloca() function allocates size bytes of space in the stack frame of the caller.  This temporary space is automatically freed when the function that called alloca() returns to its caller.
> 

One interesting thing about `alloca` as you can see is that they don't need to free the space as it is automatically freed because it's on the stack.

Some implementations of VLA fallbacks to standard heap allocation when `alloca` is not available or if the size is too huge to allocate on the stack.

Maybe this could be implemented using the upcoming new destructors, using `alloca` when it's available otherwise falling back to standard heap allocation and free on destruction.

**Comment by bpr** [comment]
I put together a quick prototype of your suggested implementation via alloca a while ago here https://github.com/bpr/nim-vla based on a post to the Nim forum from @rbehrends.

**Comment by Araq** [comment]
Can be done as a library as @bpr showed. There is currently no interest in exposing even more different array-like types, sorry. Closing.
