### ISSUE TITLE
Additional examples for the JSON module

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6531]
See topic [here](https://forum.nim-lang.org/t/3255)

It is not trivial to go from this

```Nim
import json

var field1, field2, field3 : str
var jz : JsonNode

field1 = jz["node1"].getStr
field2 = jz["node2"].getStr
field3 = jz["node3"].getStr
```
`KeyError` if the field does not exist

to this:

```Nim
field1 = jz{"node1"}.getStr 
```

No key error

**Comment by diegogub** [comment]
+1

**Comment by Araq** [comment]
That's just a hint that a TR macro transformation was applied, you can ignore these.
