### ISSUE TITLE
js backend 0.17.3: array bounds check for non zero based arrays is buggy

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#6532]
The following example produces an index out of bounds exception on the js backend of Nim 0.17.3 in debug mode (nim js -r example.nim):
```nim
const MonthNames: array[1..12, string] = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]

proc test() =
    for i in 11..12:
        echo "test idx: ", i, " ", MonthNames[i]

test()
```
To fix this issue, i think the code on line 1070 in jsgen.nim (0.17.3) should be changed from:
```nim
      r.res = "chckIndx($1, $2, $3.length-1)-$2" % [b.res, rope(first), a.res]
```
to
```nim
      r.res = "chckIndx($1, $2, $3.length+$2-1)-$2" % [b.res, rope(first), a.res]
```

But i very evidently don't know enough Nim to be sure, if this fix is really correct.

**Comment by Araq** [comment]
This fix should do it indeed. PR please.
