### ISSUE TITLE
Feature request: Enhanced stack traces

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#6536]
Hi there.

So we already have two really nice debugging tools:

1. Stack traces.

2. Ability to print out local variables in a function by calling the "locals()" magic function.

I'd like to request a debug option to combine the two - print local variable values at every level of the stack trace. Performance would obviously suffer a LOT, but it can be great for debugging, or for code that doesn't need good performance.

eg, this is one of my favourite python libs for highly detailed error capturing and logging:

http://brennivin.readthedocs.io/en/latest/brennivin.traceback2.html

Edit: It's also present in the Python stdlib:

https://docs.python.org/2/library/cgitb.html

**Comment by Araq** [comment]
Sorry, not gonna happen soon.
