### ISSUE TITLE
Feature request: C++-like RAAI semantics

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#6539]
This probably overlaps a lot with Araq's recent work on destructors, escape analysis, and move semantics.

But basically, would be really nice to be able to make this kind of library:

https://github.com/libSDL2pp/libSDL2pp

The point not being something like making yet another SDL2 wrapper (tm), but rather being able to use the very powerful C++ RAII semantic in general.

**Comment by Araq** [comment]
Yeah well, my RFCs cover that. No need to keep this issue open.
