### ISSUE TITLE
Unsigned integers are sometimes converted to signed when casting to a float

### ISSUE THREAD

**Issue by mforsb** [nim-lang/Nim#6549]
It seems that unsigned integers are cast to signed integers when they are not first bound to a variable, but only sometimes. This is probably a bug, or at least _highly_ confusing.
```nim
var a = not 0                                   # -1 as expected
var b = not 0'u64                               #  18446744073709551615 as expected
var aFloat = float(a)                           # -1.0 as expected
var bFloat = float(b)                           #  1.844674407370955e+19 as expected
var aInlineFloat = float(not 0)                 # -1.0 as expected
var bInlineFloat = float(not 0'u64)             # -1.0 but should be the same as bFloat
var c = float(1'u64 - 3'u64)                    # -2.0 but should be 18446744073709551614
var d = float(18446744073709551615'u64)         # -1.0 **not** as expected
var e = float(18446744073709551615'u64 + 1'u64) #  0.0 as expected
```
```
$ nim --version
Nim Compiler Version 0.17.2 (2017-09-07) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release
```

**Comment by jangko** [comment]
I don't think this is a bug.
all of the example above actually in harmony with Nim Manual, they are type conversion, not a mere type casting like C.
Nim Manual also says something about type cast, which is equals to C++ reinterpret_cast, using different syntax than the above example.

I don't think the information provided in the manual confusing. it is very clear.

**Comment by wiml** [comment]
I just ran into this as well; I think it's pretty clearly a bug. It still behaves this way in Nim 1.4.0, 1.2.6, and 1.0.2. I'm running it on x86_64 on ubuntu.

```nim
const v = 18446744073709551615'u64

echo v
echo float32(v)
echo float64(v)
```

produces (via `nim c --run floatfail.nim`):

```
18446744073709551615
-1.0
-1.0
```

The second two lines should be `1.844674407370955e+19` or so.

**Comment by shirleyquirk** [comment]
i can't reproduce this since https://github.com/nim-lang/Nim/pull/19890 enabled uint->float conversions
but the bug is still there in genLiteral: https://github.com/nim-lang/Nim/blob/77891cedaeeb9283793c34b231d8d8c4f19002de/compiler/ccgexprs.nim#L65-L67

**Comment by bung87** [comment]
> i can't reproduce this since #19890 enabled uint->float conversions but the bug is still there in genLiteral:
> 
> https://github.com/nim-lang/Nim/blob/77891cedaeeb9283793c34b231d8d8c4f19002de/compiler/ccgexprs.nim#L65-L67

can't not reproduce in e68a6ea759c65ec2ec92cfe5ef922c5c3ef0623e, seems fixed ? what's the bug left ?
