### ISSUE TITLE
Please add pipe2 support to posix stdlib

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#6553]
pipe is in there, like this:

proc pipe*(a: array[0..1, cint]): cint {.importc, header: "<unistd.h>".}

Please also add pipe2:

http://man7.org/linux/man-pages/man2/pipe.2.html

**Comment by wizzardx** [comment]
Sorry, looks like that is very linux specific, rather than posix. Probably belongs in some other library :-)

**Comment by wizzardx** [comment]
Just going to re-open for a bit; interested to hear what Nim devs think of linux-specific headers vs general posix headers.

**Comment by Araq** [comment]
We have ``lib/posix/linux.nim`` already, just add it there. Btw I'm not a fan of feature requests that take as much time to describe as the implementation to write.

**Comment by wizzardx** [comment]
Sorry :-/. I'm a total noob with the Nin codebase; don't know where things go, or if they're meant be be added there in the first place! (eg I initially closed the ticket for that resaon).
