### ISSUE TITLE
procs with return types that do not return a value or set result should warn or error

### ISSUE THREAD

**Issue by jackmott** [nim-lang/Nim#6557]
a procedure with a return type but that fails to return anything, and never sets the `result` value will compile without warning or error. Example:

```nim
proc example() : int =
  echo "Hello World"
```

This probably compiles because it is returning the implicit result with the default value.  In cases where result is never set (or perhaps has paths where it is not set), it may be better to issue a compile time warning or error.  My personal preference would be an error. But at least a warning will help people rapidly track down their bug.

**Comment by Yardanico** [comment]
"has paths where its not set" no, that's the reason result variable is useful. if in some path it's not set - it will contain default value for that type

**Comment by jackmott** [comment]
good point, disregard that idea.

**Comment by andreaferretti** [comment]
@Yardanico Still, I would say this is a major source of bugs. I'd rather be a little more explicit than have the compiler accept procs such as 

```nim
proc example() : int =
  echo "Hello World"
```

I would be happy with a much more relaxed check - either `result` appears explicitly somewhere in the body, or the `return` keyword is used - not necessarily on all possible branches. It happens often to just forget to return anything

**Comment by Yardanico** [comment]
@andreaferretti I was exactly talking about this. I just said that checking that some paths don't return value at all would lead to many false positives, but I'm generally OK with checking if "result" is set

**Comment by akbcode** [comment]
Implicitly returning the default value is a bad idea. Wasted a few minutes trying to hunt down the source of bugs due to this.

**Comment by Araq** [comment]
I think the time is ripe to enforce initialization for all code paths. The analysis exists already.

**Comment by andreaferretti** [comment]
@Araq great news! Just make sure that the following will still compile (I used to have warnings about missing initialization on code like this):

```nim
type Foo = object
  a: int
  b: string

proc myFoo(): Foo =
  result.a = 3
  result.b = "hi"
```

**Comment by Araq** [comment]
We are rolling out experimental:strictDefs which does this.
