### ISSUE TITLE
Implement an `asArray` macro

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6563]
Inspired by this: https://github.com/nim-lang/Nim/pull/6301/files#diff-15d82a47d4b87ec3cce5f6262d3828ceR339

```nim
var x = [
  12.Rune,
  13.Rune,
  14.Rune,
  ...
]
```

Makes me want to cry.

So let's allow this:

```nim
var x = asArray[Rune]([
  12,
  13,
  14,
  ...
])
```

(Or similar)

And add it to the stdlib! (possibly to ``sequtils``)

**Comment by Yardanico** [comment]
@dom96 why sequtils if it would operate on arrays too?

**Comment by dom96** [comment]
because ``sequtils`` should be renamed to ``listutils``, many procs there operate on arrays too.

**Comment by Yardanico** [comment]
@dom96 only map from sequtils can be used for arrays (and insert for inserting array into sequence)

**Comment by mratsim** [comment]
Second this, for interfacing with C I often have to write a lot of code like this:

```Nim
var foo = [a.cint, b.cint, c.cint, d.cint]

let bar = baz(addr foo)
```

**Comment by konqoro** [comment]
You can just write: 
```
var x = [
  12.Rune,
  13,
  14,
  ...
]
```

**Comment by Yardanico** [comment]
Yeah ^

**Comment by Yardanico** [comment]
@konqoro you can't

**Comment by konqoro** [comment]
@Yardanico it worked with cint but not with Rune...

**Comment by Yardanico** [comment]
@konqoro yes because cint is a built-in type

**Comment by GULPF** [comment]
I think it's because cint is just a type alias, but Rune is a distinct type.

```nim
type Rune = int32 # Works
# type Rune = distinct int32 # Doesn't work

var x = [
  12.Rune,
  13,
  14
]
```

**Comment by Araq** [comment]
> because sequtils should be renamed to listutils, many procs there operate on arrays too.

They all return seqs though so the name is fine. Also "list" implies a linked list in Nim.
