### ISSUE TITLE
compiler gives "statement not allowed after return" even if it is only followed by "when false: ..."

### ISSUE THREAD

**Issue by luka-mikec** [nim-lang/Nim#6569]
I'm not sure if this is a bug or intended behaviour.

The following code doesn't compile:
```
when true:
  return 0
when false:
  return 1
```
But it would be useful in some situations:
```
  when declared smth: 
    return 0
  when not declared smth: 
    return 1
```

I'm not sure if _whens_ are supposed to be evaluated first (but that was my impression, since they are used for conditional compilation); in that case, I guess the above code should compile, since (when smth really is declared) the whole code boils down to just "return 0".

**Comment by GULPF** [comment]
You should use `else` (you can also use `elif`, but not needed here of course):
```nim
  when declared smth: 
    return 0
  else: 
    return 1
```

**Comment by Yardanico** [comment]
@luka-mikec - @GULPF is right, you should use "else" here

**Comment by luka-mikec** [comment]
I see, thank you!
