### ISSUE TITLE
threadpool deadlocks even when preferSpawn() returns true

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#6573]
the following example deadlocks on linux and windows. Might be related to https://github.com/nim-lang/Nim/issues/4597 but I have many cores.

The code tries to use preferSpawn() to decide whether to spawn or not, but this does not help - most of the time. Sometimes the code does not lock.

```nim
include threadpool

var countSpawn = 0

proc available*(): int =
  return gSomeReady.counter


proc doInc(base: int; final: int): int =
  if base < final:
    echo base, " ",available()
    if preferSpawn():
      atomicInc(countSpawn)
      var r = spawn doInc(base + 1, final)
      result = ^r
    else:
      result = doInc(base + 1, final)
  else:
    result = base


proc run() =
  var test = spawn doInc(1, 500)
  echo ^test

run()  
echo "spawned ", countSpawn
```

**Comment by mikra01** [comment]
Hi AdrianV, please try the compiler flag --d:nimRecursiveSpawn  
the deadlock should be away (works for me)

**Comment by mikra01** [comment]
I assume now you already tried the flag nimRecursiveSpawn.  Afther checking the implementation I think the problem is that you try to use more than 256 threads recursively. But there is actually a limit on it: 
const
  MaxThreadPoolSize* = 256
If you will stay below this limit, your program behaves as expected.

**Comment by AdrianV** [comment]
I know about MaxThreadPoolSize - that why I tried with more. As far as I  understood, preferSpawn should tell me if I can spawn or not. The problem is that I want to use spawn in recursive problem, where I can't tell before how often i need to spawn (a tree like structure). So what's the purpose of preferSpawn, when I can't prevent deadlocks with it ?

**Comment by mikra01** [comment]
yes you are right; thats a bug. I quickchecked again. the counter of the semaphore "gSomeReady" within "preferSpawn()" is not accessed atomically nor within the lock. thats the problem I assume...

**Comment by Araq** [comment]
Use the new Malebolgia library, std/threadpool is moribund.
