### ISSUE TITLE
Async locks

### ISSUE THREAD

**Issue by SunDwarf** [nim-lang/Nim#6586]
As I discussed on IRC, it would be nice to have locks for the `asyncdispatch` module, for usecases such as preventing two functions doing a HTTP request at the same time for ratelimit purposes, or similar.

**Comment by dom96** [comment]
Yeah, so as further discussed I'm not sure this is actually needed. 

https://irclogs.nim-lang.org/24-10-2017.html#17:56:30

As such I think I'm afraid I will close this. If you disagree please reopen though :)
