### ISSUE TITLE
Inconsistent results for echo and $

### ISSUE THREAD

**Issue by markus-oberhumer** [nim-lang/Nim#6594]
Since the release of nim-0.17.2 there have been some changes to printing a `nil` string, which now gives inconsistent results for `echo` and `$`:

```
var a: string = nil
var b = $a

echo 1, a, 2            # prints "12" with current nim git
echo 3, b, 4            # prints "34" with current nim git 

doAssert b == ""        # FAILS
```

Somewhat related, I really wish Nim would adopt Go's semantic concept of *a zero value should yield a useable object*. It seems there is some work in the [araq-no-nil branch](https://github.com/nim-lang/Nim/tree/araq-no-nil) though, so maybe it's not too late.

**Comment by krux02** [comment]
I agree, I actually have a PR here, but it introduces weird crashes:

https://github.com/nim-lang/Nim/pull/6206

**Comment by Araq** [comment]
The printing is consistent, that ``nil`` is not exactly the same as ``""`` is expected for now.

**Comment by markus-oberhumer** [comment]
@Araq Are you sure that `$a` should return `nil` ??

**Comment by Araq** [comment]
Yes.

**Comment by krux02** [comment]
well as soon as the default value of a string is not nil anymore, or the nil string is equivalent of the empty string, then this behavior should change.
