### ISSUE TITLE
cant use w/ #!shebang

### ISSUE THREAD

**Issue by takano32** [nim-lang/Nim#66]
Many script programming languages are commonly able to comment out w/ '#'.
Nimrod is also able to do it.

And many script programming languages are able to use w/ #!shebang.
# !shebang is i.e.

``` scheme
#!/usr/bin/env gosh

(define (fib n)
  (if (< n 2) 1
    (+ (fib (- n 2)) (fib (- n 1)))))

(print (fib 30))
```

But Nimrod cant kick w/ #!shebang.

**Comment by jabbalaci** [comment]
I'm a bit late but if you want to call nim via env, then you can try this:

    #!/usr/bin/env -S nim r --hints:off

Suppressing unused import warnings:

    #!/usr/bin/env -S nim r --hints:off --warnings:off
