### ISSUE TITLE
Feature request for "export" of local symbols on proc/types defined within a module

### ISSUE THREAD

**Issue by kdheepak** [nim-lang/Nim#6607]
Currently Nim supports the `export` statement, which is useful for forwarding an imported symbol. I'm requesting for a equivalent "export" (perhaps `exportall`) to allow for exporting a local symbol in a module as an alternative to using `*`.

Reasoning: 

- It's easier to glance at the top of a file by a library developer to grok all the symbols available to use by that library
- git diffs on a library that changes private functions to exported symbols becomes more clear, i.e. one line succinctly describes the changes 

Example:

```Nim
exportall add, mul

add(x:MyObject, y:MyObject): MyObject = ...
mul(x:MyObject, y:MyObject): MyObject = ...
sub*(x:MyObject, y:MyObject): MyObject = ...
div*(x:MyObject, y:MyObject): MyObject = ...
```

**Comment by GooRoo** [comment]
@kdheepak How do you imagine exporting of objects and their fields with this syntax?

**Comment by Araq** [comment]
I don't like it and your reasons don't convince me. :-)

> It's easier to glance at the top of a file by a library developer to grok all the symbols available to use by that library

Without the type signatures that's pretty shallow to look at.

> git diffs on a library that changes private functions to exported symbols becomes more clear, i.e. one line succinctly describes the changes

Purely a question of taste, a single char diff is traded for a single line diff.

**Comment by kdheepak** [comment]
Thanks for looking at This! It is a question of taste, but to clarify it would be a single line diff with a single export statement versus a multiple line diff with each line having a single character diff with the current `*`. 

I do agree with you in that in some cases not having the type signatures there can require that the reader scroll to the line of the function anyway, since they don't convey enough information. 

Julia supports this `export` syntax ([example](https://github.com/JuliaLang/julia/blob/master/base/mathconstants.jl#L11)), which I think reads well – this is where I got the idea from. Feel free to close this if you think this does not warrant any further discussion.

**Comment by Araq** [comment]
Seems unwise at this point to support more syntax for the same feature.
