### ISSUE TITLE
if expressions

### ISSUE THREAD

**Issue by jackmott** [nim-lang/Nim#6609]
Currently if statements are not very flexible when used as expressions, for example the following is not allowed:

```nim
let format =
    if channels == 1:
        TextureInternalFormat.RED
    elif channels == 3:
        TextureInternalFormat.RGB
    elif channels == 4:
        TextureInternalFormat.RGBA
    else:
        echo "Texture Format Unknown, assuming RGB"  #This echo causes an error
        TextureInternalFormat.RGB
```

Probably if expressions should have at least the same flexibility as case expressions

**Comment by GooRoo** [comment]
@jackmott not sure about correctness, but this seems to work:

```nim
let format = 
  if channels == 1:
    TextureInternalFormat.RED
  elif channels == 3:
    TextureInternalFormat.RGB
  elif channels == 4:
    TextureInternalFormat.RGBA
  else:
    (echo "Texture Format Unknown, assuming RGB";
    TextureInternalFormat.RGB)
```

https://ideone.com/hvcHpR

**Comment by jackmott** [comment]
Yes there are workarounds, but @Araq asked me to file on issue on this.

**Comment by kobi2187** [comment]
Isn't there a problem with the **indentation** of the first example?

**Comment by jackmott** [comment]
@kobi2187 just some artifact of cut and paste, I've fixed it.

**Comment by bluenote10** [comment]
Might be related to https://github.com/nim-lang/Nim/issues/3827.

**Comment by Araq** [comment]
Making this a showstopper since it's critical for version 1.
