### ISSUE TITLE
speeding up idea: Boyer Moore for all subsequence searches.

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#6616]
I had an idea: 

- using a smart string searching algorithm like boyer-moore, would likely speed up all the applications that use string matching in the std lib. 
I assume it'd be possible for byte arrays to _use the same algorithm_ and not just strings, to get a comparable speedup.
- A related idea is data structures that abstract an algorithm. for example, instead of reversing an array, make a structure that holds this array, and its length, and computes the correct index, as if the array was reversed. 0 would be len-1, 3 would be len -4, -1 would be 0, -2 would be 1. 
something like:  
proc calc(pos:int) = len + (i * -1) -1

There might be other use cases, such as a _slice_, which is a certain "_window_" to the underlying sequence.
What do you guys think?

**Comment by data-man** [comment]
@kobi2187 

> using a smart string searching algorithm like boyer-moore

strutils.find already uses the "Quick search" algorithm.

**Comment by kobi2187** [comment]
oh, that's great. didn't know that. Can that be modified to work on other indexable collections?

**Comment by data-man** [comment]
IMO, the big problem is that the standard library does not use concepts.
This will require a huge work.

**Comment by data-man** [comment]
Also, see my PR: #6582

**Comment by kobi2187** [comment]
@data-man what work will it require? besides coming up with names for all the interfaces :-)

**Comment by kobi2187** [comment]
```proc find[T]*(a: SkipTable, s, sub: T[], start: Natural = 0, last: Natural = 0): int```
I'm just a beginner, so maybe I got this wrong, but wouldn't something like this work for all indexable sequences? IOW, those which support indexed array access. (because those algorithms require jumping to different indices to skip some work)

**Comment by data-man** [comment]
> wouldn't something like this work for all indexable sequences?

Yes, it will work for any indexable sequences

The best resource for finding strings that I know about: [EXACT STRING MATCHING ALGORITHMS](http://www-igm.univ-mlv.fr/~lecroq/string/index.html)
With a full description of algorithms, their analysis and C-source codes.
Also you can port to Nim [SMART (string matching algorithms research tool)](http://www.dmi.unict.it/~faro/smart/) ;)

**Comment by andreaferretti** [comment]
I think [Cello](https://github.com/unicredit/cello) is relevant here. It is a string library I wrote, mainly aimed at string matching

**Comment by Araq** [comment]
We always try to use the "best" algorithm but this is not actionable as it is not backed up by any benchmarks.
