### ISSUE TITLE
Implementation of high/low for all uint types

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#6620]
Since `uint` and `uint64` are not `Ordinal`, it is currently not possible to use `high`/`low` on them in contrast to `uint8`/`uint16`/`uint32`. This is unfortunate when writing generic algorithms which make use of `high`/`low` and should work on all number types. As a workaround it is currently necessary to bring some manual implementations into scope like:

```nimrod
proc low*[T: uint|uint64](x: typedesc[T]): T =
  cast[T](0)

proc high*[T: uint|uint64](x: typedesc[T]): T =
  cast[T](-1)
```

For consistency it would be nice to have them by default. Note: I'm not trying to make them `Ordinals`, but just because they don't have all properties of an `Ordinal` (I assume overflow checks), the types still have a smallest/largest value.

Also there is currently an inconsistency in `high` and `low`, because `high` is defined for `high[T: Ordinal](x: T)` while `low` uses no type selector, i.e., `low[T](x: T)`. As a result, the following code

```nimrod
var x: uint
echo low(x)
```

errors with `Error: invalid argument for 'low'` (a local error from `semLowHigh` in `semexprs.nim` when handling the magic), while trying to use `high` gives the clearer type mismatch.

If desired, I can work on that.

**Comment by markus-oberhumer** [comment]
Actually I'd rather like to understand why `uint` and `uint64` are **not** `Ordinal` - system.nim vaguely talks about *implementation reasons*.

**Comment by markus-oberhumer** [comment]
Here is the version I'm currently using in my local system.nim.

Note that I do not use typeclasses (issue #6840) and there still is a codegen bug (see #6839).

```
template low* (_: uint): uint = 0'u
template high*(_: uint): uint = not 0'u
template low* (_: uint64): uint64 = 0'u64
template high*(_: uint64): uint64 = not 0'u64
template low* (_: typedesc[uint]): uint = 0'u
template high*(_: typedesc[uint]): uint = not 0'u
template low* (_: typedesc[uint64]): uint64 = 0'u64
template high*(_: typedesc[uint64]): uint64 = not 0'u64
```

**Comment by kaushalmodi** [comment]
Getting `high(uint)` and `low(uint)` will probably help fix https://github.com/nim-lang/Nim/issues/11551 and https://github.com/nim-lang/Nim/issues/11552.

**Comment by Araq** [comment]
This has finally been implemented.
