### ISSUE TITLE
Feature request: a version of tuples that generates `.fieldname`

### ISSUE THREAD

**Issue by alehander42** [nim-lang/Nim#6623]
I post this as an issue after some chat with @dom96 in gitter

In projects where Nim is used with the js target, tuple types greatly help with typechecking. 
Very often js api-s require nim compiled functions to take some objects with several fields and this field combination is used only there, e.g. `{x: int, flag: bool}`.

So currently you have two solutions:

* define a one-off type in a type section out of the proc (which is exactly something tuples should fix)
* cast each field (which just sucks)

This is resolved in TypeScript using `{x: int, flag: bool}` annotation and tuples in Nim work perfectly for the typechecking too, but they generate `.Field1`, `.Field2` which obviously doesn't work for those cases (because the js code passes x and y)

So something like `object[x: int, flag: bool]` which works exactly as tuple-s but generates the field name on access would help a lot. 

I guess the implementation can easily reuse or generalize tuple-s typechecking and just add a little code in the generators for field accesses (I am not entirely sure how useful such a type would be for the C backend). I've implemented an extremely hacky version of that for a project I work on, and it's extremely helpful so I wonder if other people would like this feature in the lan

**Comment by mratsim** [comment]
I'm probably missing something but why doesn't that work for your use case?

```Nim
let foo: tuple[x:int, flag:bool] = (42, true)

echo foo.x
echo foo.flag
```

**Comment by alehander42** [comment]
Ok, it needs an example :D 

you have a callback, that needs to deal with {x: a number, y: a boolean}

you write

```nim
stuff.on(msg) do(data: tuple[x: int, flag: bool]):
  echo data.x
```

`echo data.x` is compiled to 

`rawEcho(cstrToNimstr((data_64009.Field0)+""));`

this doesn't work (obviously), because tuples field access is compiled to `.Field<number>`

And this hypothetical `object[x: int, flag: bool]` compiles field access to `.fieldname`

**Comment by Araq** [comment]
Seems very hard to implement as you can pass a ``tuple[nameA, nameB: int]`` to something expecting ``(int, int)``. How can the code generator ensure consistent tuple accesses for this?

**Comment by alehander42** [comment]
Well I imagine that this wouldn't be required for such a type. I imagine it more as an inline definition of an object type which accidentally looks similar to a tuple.

So an argument with `object[field: T]` will type match eventually exactly objects with the same structure(and not tuples, because tuples actually have a different representation). In most cases that wouldn't even matter, because those proc-s would be probably called by js code and not other nim code.

Because of that I don't think it's even extremely important for users to be able to construct `object[]`-s. Maybe object{x: 2, y: 4} would be equivalent to a better typed `js{x: , y: ..}`?

**Comment by Araq** [comment]
But then you can just write a macro that does that.

**Comment by alehander42** [comment]
and how will the macro for the arg in proc definition possibly work? it can't create a type definition inline in `proc f(name: macroInvocation(x = Typ)`

the only thing I can think of is reusing a tuple in the proc signature to reuse the typechecking and then wrap all uses of the argument with something which wouldn't improve anything as I can just cast now as well

**Comment by alehander42** [comment]
actually I do implement it like that in my fork: I have a macro which I can invoke as `proc f(name: jsobject(x = int))` , but I add a magic field in the resulting tuple type and then I generate different field access in jsgen based on that, which is a huge hack and I am not sure how can I do something like that without support from the compiler

or without ability to inject a new type definition in the closest module scope

**Comment by stisa** [comment]
Maybe try using the `jsffi` module for the callback object, eg https://nim-lang.org/docs/jsffi.html#..m,JsObject,
It could lead to less type safety though

**Comment by alehander42** [comment]
@stisa `js` is an alias for `JsObject`. That's the solution I used initially, but not only it leades to less type safety, you need to cast each field manually to pass it to other normal typesafe nim functions.
