### ISSUE TITLE
await inside array/dict literal produces invalid code - Part 2

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#6626]
```nim
import asyncdispatch

proc check(a: array[4, int]) =
    doAssert(a[0] == 1) # fails
    doAssert(a[2] == 2) # fails

proc bar(): Future[int] {.async.} =
    await sleepAsync(500)
    result = 3

proc foo() {.async.} =
    await sleepAsync(500)
    check [1, 2, await bar(), 4] # <--- The bug is here

waitFor foo()
```

Similar to #5314

EDIT: I've changed original title/desc to better stress the severity of this
EDIT: I must have messed something up bisecting nim. If this is a a regression, it has nothing to do with changes in 7eeef4aae7391f0e9e53c9009cf722545cee954c.

**Comment by dom96** [comment]
@Yardanico ``JS``?

**Comment by Araq** [comment]
This is really hard to support in today's codegen. I'm marking this as an error for now.
