### ISSUE TITLE
Macro matching fails because of irrelevant overload

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#6643]
```nim
proc foo(x: int) = discard # Comment this out to make it work
macro foo(x: untyped{nkTableConstr}): untyped = discard
foo({"adsf": "asdf"})
```
```
test.nim(3, 4) Error: type mismatch: got (array[0..0, (string, string)])
but expected one of:
proc foo(x: int)
macro foo(x: untyped{nkTableConstr}): untyped
```

**Comment by Araq** [comment]
Documented behaviour.

**Comment by yglukhov** [comment]
Note to future self: for this to work properly nim would require something like SFINAE (try sempass the argument, rollback if no match, try match as untyped, fail if still no match). Apparently this feature is not in the nearest plans, might be revisited later. Moreover this might be harder to implement than sfinae, because sempass can cause compile-time side effects which can be hard to rollback.

Could not find it in the docs, btw.
