### ISSUE TITLE
Incorrect http redirect handling

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6649]
getNewLocation in the httpclient module fails to create a valid redirect URL: `client.get("https://amizone.net/")` 
Related to  #6652

**Comment by dom96** [comment]
Presumably this was closed with #6659.

**Comment by dom96** [comment]
Woops, there is another PR for this.

**Comment by dom96** [comment]
Relevant PR is here: https://github.com/nim-lang/Nim/pull/6653

Seems we can close this.
