### ISSUE TITLE
compiler crash during quote

### ISSUE THREAD

**Issue by oggio88** [nim-lang/Nim#6671]
this code does not compile
```nim
import macros

static:
    var name : string
    let ast = quote do:
        var b : string = `name`
    echo treeRepr(ast)
```
the result is
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
but what is really funny is that removing the last line or changing the type of "name" to seq[string] makes it compile fine

**Comment by Yardanico** [comment]
@oggio88 it's probably because "name" is a string, and string is nil by default.

**Comment by oggio88** [comment]
@Yardanico yes but also seq[string] is nil by default

**Comment by jangko** [comment]
both run-time and compile-time echo show inconsistent result
```Nim
var nilstring : string
var nilseq: seq[string]
echo nilstring  # blank/nothing
echo nilseq     # nil
```

repr too:
```Nim
echo repr(nilstring)  # 0000000000000010""
echo repr(nilseq)     # nil
```

but equality show both are true:
```Nim
echo nilstring == nil   # true
echo nilseq == nil      # true
```

perhaps, it's not directly related to quote, but something related to string?

**Comment by Yardanico** [comment]
@jangko do you get same results with isNil?

**Comment by jangko** [comment]
> do you get same results with isNil?

yup, both is true, run-time and compile-time

**Comment by jangko** [comment]
> but what is really funny is that removing the last line or changing the type of "name" to seq[string] makes it compile fine

this is really strange, the quote seems blindly accept the nil without checking the source type.
it should not compile at all.

**Comment by krux02** [comment]
this is resolved
