### ISSUE TITLE
Improve error message for `==` used with object variants

### ISSUE THREAD

**Issue by GooRoo** [nim-lang/Nim#6677]
Follow-up of #6674 

```nim
import unittest

type
  VariantKind = enum
    vkNumber, vkString

  Variant = object
    case kind: VariantKind
    of vkNumber:
      numberValue: int
    of vkString:
      stringValue: string

proc initVariant(val: int): Variant = Variant(kind: vkNumber, numberValue: val)
proc initVariant(val: string): Variant = Variant(kind: vkString, stringValue: val)

suite "object variants":
  test "default equality operator":
    check:
      Variant(kind: vkNumber, numberValue: 42) == initVariant(42)  # Error: parallel 'fields'
                                                                   # iterator does not work
                                                                   # for 'case' objects
      Variant(kind: vkString, stringValue: "foo") == initVariant("foo")
      Variant(kind: vkString, stringValue: "42") != initVariant(42)

  test "custom equality operator":
    proc `==`(lhs, rhs: Variant): bool =
      lhs.kind == rhs.kind and (
        case lhs.kind:
        of vkNumber:
          lhs.numberValue == rhs.numberValue
        of vkString:
          lhs.stringValue == rhs.stringValue
      )
    check:
      Variant(kind: vkNumber, numberValue: 42) == initVariant(42)  # works fine now
      Variant(kind: vkString, stringValue: "foo") == initVariant("foo")
      Variant(kind: vkString, stringValue: "42") != initVariant(42)
```
results in a compile error (with `--verbosity:2`):
```
test.nim(17, 7) template/generic instantiation from here
test.nim(18, 8) template/generic instantiation from here
test.nim(19, 5) template/generic instantiation from here
test.nim(20, 48) template/generic instantiation from here
lib\pure\unittest.nim(569, 28) template/generic instantiation from here
lib\system.nim(2384, 3) Error: parallel 'fields' iterator does not work for 'case' objects
    for a, b in fields(x, y):
    ^
```
The actual problem:
```proc `==`*[T: tuple|object](x, y: T): bool``` from *stdlib* is not able to work with objects with `case` inside.

The compiler's log output has nothing in common with "clear error message" because:

1. First five messages are related to `unittest` module and not to the actual problem.
1. Error in `system.nim` shows some internal things which are absolutely out of context. I never called "parallel `fields` iterator" directly, then why does compiler tell me about it?
    * There is no path or trace from my code to the place where the actual problem happened. 

As a side note: I wasn't able to run it with `--verbosity:3` 'cause compiler crashes all the time with "Unknown IO Error"

**Comment by Araq** [comment]
Error messages that teach you how Nim really works are still clear error messages.

**Comment by GooRoo** [comment]
@Araq, no, they are not. 

Even C++, widely known for its ugly error messages (especially when it comes to templates), shows you the full "path" from your code to the place where error actually happens. 

Good standard library should just work. As a developer I give no shit about its internal implementation, and even if I use it incorrectly, I want to know why. 

I spent half an hour in order to understand the reason of an error because I couldn't imagine that it's just a poor stdlib implementation.

**Comment by bluenote10** [comment]
I remember that this error was also hard to understand for me when I saw it for the first time.

A general wish I have for the `template/generic instantiation from here` errors is to include which template or generic was actually instantiated, e.g., `==`, which is mainly the missing bit of information in the error. This is mainly confusing when the line of code involves multiple template/generic instantiations. In this case I haven't found a better solution than to got to `lib\system.nim(2384, 3)` and scroll up a few line to actually see what was instantiated.

@Araq Would it be possible to have messages like `template/generic instantiation of <...> from here` or is there a technical limitation I'm not aware of?
