### ISSUE TITLE
Reassigning local var to seq of objects results in nil element in Object's seq field

### ISSUE THREAD

**Issue by acolley** [nim-lang/Nim#668]
This code demonstrates a problem I'm having. Not sure if this is a bug or an intended feature but it's not caught by the compiler as something that cannot be done.

``` nimrod
import strutils

type
  TThing = ref object
    data: int
    children: seq[TThing]

proc `$`(t: TThing): string =
  result = "($1, $2)" % @[$t.data, join(map(t.children, proc(th: TThing): string = $th), ", ")]

proc somethingelse(): seq[TThing] =
  result = @[TThing(data: 20, children: @[])]

proc dosomething(): seq[TThing] =
  result = somethingelse()

  result = @[TThing(data: 10, children: result)]

when isMainModule:
  echo($dosomething()[0]) # results in segfault as tries to dereference a null pointer
```

The line `result = @[TThing(data: 10, children: result)]` results in the `children` seq having a nil element as the first element.

**Comment by Araq** [comment]
The codegen is just too smart and produces too optimized code that ignores the aliasing in 'result = @[result]'

**Comment by Araq** [comment]
Still a problem, raising its priority.
