### ISSUE TITLE
Compiler crash when using a macro that tries to modify a static var

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6681]
```nim
import macros, strutils

static:
    var constX = 99

var x = 2

macro myMacro: untyped =
    parseStmt "constX = x"

myMacro()
```

> PS C:\Users\dawkot\Documents\NetRPG> nim c --out:"bin\test" -r "c:\Users\dawkot\Documents\NetRPG\test.nim"
> Hint: used config file 'C:\Users\dawkot\.choosenim\toolchains\nim-#devel\config\nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: test [Processing]
> Hint: macros [Processing]
> Hint: strutils [Processing]
> Hint: parseutils [Processing]
> Hint: math [Processing]
> Hint: algorithm [Processing]
> CC: test
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.c: In function 'NimMainModule':
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.c:126:2: error: 'constX_QlEpHHXQcUUwCd3CWV1P0A' undeclared (first use in this function)
>   constX_QlEpHHXQcUUwCd3CWV1P0A = x_9bf4p1FLrvkXIchOKUUtCcw;
>   ^
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.c:126:2: note: each undeclared identifier is reported only once for each function it appears in
> Hint:  [Link]
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x151): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x16d): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x181): undefined reference to `@suiteStarted_9aAyDoHTMoiLoSiMpkUAFNw@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x1a1): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x1bd): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x1d1): undefined reference to `@suiteStarted_IXWI0IZVUaexE074PboPzQ@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x1ee): undefined reference to `NTI_dLGU9cWWYqlqOn8lpRVsx9cw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x207): undefined reference to `@suiteStarted_zvRCVP5x4ZBpPV2Xx9cPHZA@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x274): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x290): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x2a4): undefined reference to `@testStarted_EYS8dFM0pZmDNdV9c1cyo4Q@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x2c4): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x2e0): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x2f4): undefined reference to `@testStarted_0WlfvTsMUPRHUfLeuXrGAg@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x311): undefined reference to `NTI_dLGU9cWWYqlqOn8lpRVsx9cw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x32a): undefined reference to `@testStarted_YRuPwQXlDxZko9bSMypk3hA@8'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x397): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x3b3): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x3cd): undefined reference to `@failureOccurred_NAlHeCfOfz1bBvtw2rCPGw@12'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x3f0): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x40c): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x426): undefined reference to `@failureOccurred_HopmjhtOQil8N9axQ5kNI3w@12'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x446): undefined reference to `NTI_dLGU9cWWYqlqOn8lpRVsx9cw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x465): undefined reference to `@failureOccurred_Fsq9aCTSjbGiV7TYpR757Lw@12'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x4d4): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x4f0): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x515): undefined reference to `@testEnded_E5f9a05hVCAPvYslPV2f4TQ@16'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x538): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x554): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x579): undefined reference to `@testEnded_AsoOYSa1sGgPTBsUoT9cxsw@16'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x599): undefined reference to `NTI_dLGU9cWWYqlqOn8lpRVsx9cw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x5c3): undefined reference to `@testEnded_hPRwDS9aOIRJ5MB9buAX30Wg@16'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x632): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x64e): undefined reference to `NTI_kvLOVRX6Za2S0C2QxHXy9cQ_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x65f): undefined reference to `@suiteEnded_EF53BADEiH9a6amiy7eitMg_2@4'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x67c): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x698): undefined reference to `NTI_dU6QGtP3KgqXg9bZP3nhpWw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x6a9): undefined reference to `@suiteEnded_IIGQUyJJjT9cNV9c34JPjWGA@4'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x6c6): undefined reference to `NTI_dLGU9cWWYqlqOn8lpRVsx9cw_'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x6dc): undefined reference to `@suiteEnded_RS3dEHKAbuhOugXu1dXVHg@4'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x720): undefined reference to `stdlib_sequtilsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x725): undefined reference to `stdlib_futureDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x72a): undefined reference to `stdlib_typetraitsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x72f): undefined reference to `stdlib_optionsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x734): undefined reference to `stdlib_streamsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x739): undefined reference to `stdlib_dynlibDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x73e): undefined reference to `stdlib_winleanDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x743): undefined reference to `stdlib_timesDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x748): undefined reference to `stdlib_hashesDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x74d): undefined reference to `stdlib_setsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x752): undefined reference to `stdlib_ospathsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x757): undefined reference to `stdlib_osDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x75c): undefined reference to `stdlib_terminalDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x761): undefined reference to `stdlib_unittestDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x766): undefined reference to `pipe_pipeDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x76b): undefined reference to `stdlib_endiansDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x770): undefined reference to `stdlib_tablesDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x775): undefined reference to `stdlib_intsetsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x77a): undefined reference to `stdlib_listsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x77f): undefined reference to `stdlib_queuesDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x784): undefined reference to `stdlib_strtabsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x789): undefined reference to `stdlib_critbitsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x78e): undefined reference to `msgpack4nim_msgpack4nimDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x793): undefined reference to `unknown_utilsDatInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7b6): undefined reference to `stdlib_sequtilsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7bb): undefined reference to `stdlib_futureInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7c0): undefined reference to `stdlib_typetraitsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7c5): undefined reference to `stdlib_optionsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7ca): undefined reference to `stdlib_streamsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7cf): undefined reference to `stdlib_dynlibInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7d4): undefined reference to `stdlib_winleanInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7d9): undefined reference to `stdlib_timesInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7de): undefined reference to `stdlib_hashesInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7e3): undefined reference to `stdlib_setsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7e8): undefined reference to `stdlib_ospathsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7ed): undefined reference to `stdlib_osInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7f2): undefined reference to `stdlib_terminalInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7f7): undefined reference to `stdlib_unittestInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x7fc): undefined reference to `pipe_pipeInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x801): undefined reference to `stdlib_endiansInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x806): undefined reference to `stdlib_tablesInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x80b): undefined reference to `stdlib_intsetsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x810): undefined reference to `stdlib_listsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x815): undefined reference to `stdlib_queuesInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x81a): undefined reference to `stdlib_strtabsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x81f): undefined reference to `stdlib_critbitsInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x824): undefined reference to `msgpack4nim_msgpack4nimInit000'
> c:\Users\dawkot\Documents\NetRPG\nimcache\test.o:test.c:(.text+0x829): undefined reference to `unknown_utilsInit000'
> C:/Users/dawkot/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: c:\Users\dawkot\Documents\NetRPG\nimcache\test.o: bad reloc address 0x20 in
>  section `.eh_frame'
> C:/Users/dawkot/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
> Error: execution of an external program failed: 'gcc.exe   -o C:\Users\dawkot\Documents\NetRPG\bin\test  c:\Users\dawkot\Documents\NetRPG\nimcache\test.o c:\Users\dawkot\Documents\NetRPG\nimcache\stdl
> ib_system.o c:\Users\dawkot\Documents\NetRPG\nimcache\stdlib_macros.o c:\Users\dawkot\Documents\NetRPG\nimcache\stdlib_strutils.o c:\Users\dawkot\Documents\NetRPG\nimcache\stdlib_parseutils.o c:\Users
> \dawkot\Documents\NetRPG\nimcache\stdlib_math.o c:\Users\dawkot\Documents\NetRPG\nimcache\stdlib_algorithm.o    '

**Comment by andreaferretti** [comment]
Maybe it should not crash this way, but it does not make sense to modify a static var based on the content of a var because they exist at different times

**Comment by genotrance** [comment]
This no longer crashes since static now has its own scope. Now you just get:

`lib\core\macros.nim(456, 1) Error: undeclared identifier: 'constX'`

**Comment by andreaferretti** [comment]
Agreed, can close
