### ISSUE TITLE
fields not initialized: array with enum index type as object field.

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#6682]
```nim
type
    Fields = enum
        A=1, B, C

    Obj = object
        fld: array[Fields, int]

var a: Obj # this works
var b = Obj() # this doesn't (also doesn't works with additional fields)
```
this results in an error. there is no problem if enum starts from zero.
```
testfile.nim(9, 12) Error: fields not initialized: fld.
```

**Comment by Araq** [comment]
What's the bug here? The compiler prevents you from creating an invalid object.

**Comment by Parashurama** [comment]
I was refering to the fact that ```var b = Obj()``` is valid if **Fields** starts from 0 and invalid if not.
I was expecting an array[Fields, int] automatically initialised to zero, independant from the fact that its first index is 1.
