### ISSUE TITLE
Compiler crashes for invalid importcpp

### ISSUE THREAD

**Issue by alehander42** [nim-lang/Nim#6683]
When I write an invalid importcpp for the js backend, the compiler gets an IndexError instead of displaying a meaningful message

```nim
var amdRequire {.importcpp: "amdRequire(#, #)".}: proc(s: int)
amdRequire(0)
```

**Comment by Araq** [comment]
Now fails with:


temp.nim(3, 11) Error: wrong importcpp pattern; expected parameter at position 2 but got only: 1
