### ISSUE TITLE
Proc names shadowing an internal type cannot be exported

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#6693]
As a helper function, I had defined a `proc range(...) = ...`, and calling this proc from within the module seems to work fine. During a refactoring I moved the proc to a different module, making it an exported `proc range*(...) = ...`. Apparently this does not work, because the proc is now hidden by the internal type `range`. I don't know if this is intended behavior. Some ideas how to solve the problem:

- Make the import/export work despite shadowing internal types.
- Disallow symbols shadowing an internal type in general (was it always allowed?).
- If the current behavior is exactly as it should be, it would be nice if the compiler produces a warning for any function with an exporting `*` that shadows an internal type. Some like `"<symbol-name>" cannot be exported, because it is shadowed by an internal type. It will only be accessible from within the same module`. This would clarify that this is semi-supported, and reduce the time to track down issues during refactoring.

Reproducible example:

```nimrod
# alib.nim
proc range*() = echo "yo"
```

```nimrod
# main.nim
const localDef = false
when localDef:
  # works
  proc range*() = echo "yo"
  range()
else:
  # doesn't work
  import alib
  range()
```

The behavior is not specific to `range` but applies for all internal types, and also not specific to proc definitions, i.e., the behavior with variables is the same.

Note: Using the fully qualified name `alib.range` works, so it looks like it is more an import gotcha.

**Comment by Yardanico** [comment]
Yes, I had the same issue with "range" in nimpylib

**Comment by Araq** [comment]
Types are not overloadable and so the compiler should flag it as "ambiguous: both system.range and foo.range are possible". Of course fixing this will break code. Again.
