### ISSUE TITLE
Feature request: macros as variable declaration pragmas

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6696]
Forum thread [link](https://forum.nim-lang.org/t/3310).

Example:

Being to do this with a user-defined macro 

```Nim
{.pragma: align64, codegenDecl: "$# $# __attribute__((aligned(64)))".}
var foo{.align64.} = [1, 2, 3, 4]
```

```Nim
macro align64*(x: untyped): untyped =
  expectKind(x, nnkIdent)
  result = x
  when defined(js):
    return
  # codegenDecl code goes here


# This works
proc foo() {.align64.} =
  discard


# Get this to work
let bar {.align64.} = [1, 2, 3, 4]
```

**Comment by yglukhov** [comment]
And for types as well! =)

Question is to which AST macros should be applied though?
```nim
let bar {.foo.} = 123
```
Might be transformed to
```nim
foo(let bar = 123)
```
or
```nim
let foo(bar) = 123
```
or smth else? The first variant looks more useful and allows crazier things. However, what if the let section has more decls?
```nim
let
  bar {.foo.} = 123
  buz = 456
```
Should the let section be split now to the following?
```nim
foo(let bar = 123)
let buz = 456
```

**Comment by couven92** [comment]
Would also like this for Type declarations like:

``` nim
import macros
macro myMagicTypeMacro(ast: untyped): untyped =
  result = ast

type MyMagicType {.myMagicTypeMacro.} = object of RootObj
  foo: int
```

**Comment by mratsim** [comment]
Related: https://github.com/nim-lang/Nim/issues/1930, https://github.com/nim-lang/Nim/issues/1930

**Comment by Skrylar** [comment]
In the case of Flatbuffers (and Capnproto, any serializer, etc) this would let you place format-specific tags on an object and avoid needing to take over the entire type section.
```nim
import macros

macro sporg(unused: untyped): untyped =
  discard

type
  thingdo = object
    foo {.sporg: true.}: int # something like this should work, as it does in C# (and Go, kind of)

macro cocainum(x: typedesc): untyped =
  let t = gettypeimpl(gettype(x)[1])
  echo lisprepr t

cocainum(thingdo)
```

**Comment by andreaferretti** [comment]
@Skrylar I tried to re-read your comment a few times but I could not parse it :-(

**Comment by Bulat-Ziganshin** [comment]
@andreaferretti he meant that now we can apply macro to type in this way:

```
sporg true:
  type thingdo = object foo 
```
and this feature will allow to add per-type pragmas right to the type definitions

**Comment by metagn** [comment]
This is now implemented, but without arguments like `{.sporg: true.}`, see https://nim-lang.org/docs/decls.html

**Comment by timotheecour** [comment]
the new design is being discussed here: https://github.com/nim-lang/RFCs/issues/220, TLDR the syntax will likely change from (lhs,typ,rhs) params to a single AST param
