### ISSUE TITLE
Missing inline pragmas in std lib?

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#6701]
I have still no exact idea about what the problem was in

https://forum.nim-lang.org/t/3305

but missing inline pragma in strutils.toLowerAscii() may be an explanation. So was there a good reason why it was not applied? Well for me toLowerAscii() is absolutely no critical function, so I do not really care -- but for the starter of that thread it may have been of some importance, he tried to fix it with strange bit fiddling trick, and seems to be frustrated now.

**Comment by krux02** [comment]
I am closing this, because I don't don't see a question or issue.

**Comment by Araq** [comment]
Also enable link-time optimizations for speed.
