### ISSUE TITLE
Function type mismatch

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#6706]
Why the function with more strict restrictions can't be used in the place where less restrictions is needed?

```nim
import future

proc withX(x: int): (y: int) -> int =
  discard

withX(1)((y: int) => y + 1)
```

```
issue.nim(6, 9) Error: type mismatch: got (proc (y: int): int{.noSideEffect, gcsafe, locks: 0.})
but expected one of: 
proc (y: int): int{.closure.}
```

Nim Playground: https://play.nim-lang.org/?gist=d908dfe82f84a9b50a21e036f54daf23

**Comment by vegansk** [comment]
Without `future` dependency, the error is the same:
```nim
proc withX(x: int): proc(y: int): int =
  discard

withX(1)(proc(y: int): int = y + 1)
```

**Comment by vegansk** [comment]
One more comment. It's the regression, I can't compile my old code

**Comment by vegansk** [comment]
Oops, there is error in example, will reopen issue after creating correct example
/close

**Comment by genotrance** [comment]
What was the fix here? Question was asked recently on IRC.

https://irclogs.nim-lang.org/13-12-2018.html#01:16:29
