### ISSUE TITLE
isServing isn't declared and isn't compiling

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#6707]
Line [488](https://github.com/nim-lang/Nim/blob/06a63479295c4e3564de49c15d5877ca8db84196/nimsuggest/nimsuggest.nim#L488)

How's this working without a ```var``` declaration? I couldn't compile nimsuggest with nim@#head until I added the declaration.

**Comment by andreaferretti** [comment]
How did you compile it? Did you use `koch tools`?

**Comment by genotrance** [comment]
Yes, I used koch tools.

**Comment by Yardanico** [comment]
It is declared here:
https://github.com/nim-lang/Nim/blob/cc893b968b6204622727cf6f9362519752297a0e/compiler/options.nim#L108
