### ISSUE TITLE
Add mechanism to recover from failed imports

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#671]
As explained in http://stackoverflow.com/questions/19954952/how-do-i-recover-from-a-failed-import-in-nimrod/19961025 it would be nice to have a way to _recover_ from an import which fails, either to customize the error message or to fall back to a secondary piece of code which implements a placeholder API (maybe) or chains a different import to provide it.

**Comment by Araq** [comment]
os.fileExists can now be used at compile-time.

**Comment by Araq** [comment]
```nim


template imp(x) = import x

when compiles(imp foo):
  echo "foo"
when compiles(imp strutils):
  echo "strutils"
```

now works.
