### ISSUE TITLE
Portable fsmonitor

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6718]
fsmonitor should support OSX and Windows as well.

**Comment by dom96** [comment]
fsmonitor will be taken out of the stdlib.

**Comment by bluenote10** [comment]
Please don't remove it from the core libs. See my comment [here](https://forum.nim-lang.org/t/3159) why having general solution in the stdlib is an important feature for the build ecosystems.

**Comment by dom96** [comment]
> The reason why having it in the standard library could be beneficial: One of the things I'm missing the most compared to Scala development is SBT's ~compile/~run/~test functionality, which allows to easily set-up source code watchers and re-run the compiler (and optionally arbitrary entry points or tests) whenever the source code changes.

Couldn't this be implemented outside of the compiler? Perhaps just as an app that calls the compiler. I don't see much advantage in integrating this with the compiler.

**Comment by dom96** [comment]
Overall though, it's not the end of the world if we remove it. Adding things to the stdlib in the future will be easy once a mature fsmonitor package is created.

**Comment by bluenote10** [comment]
> Couldn't this be implemented outside of the compiler? Perhaps just as an app that calls the compiler. I don't see much advantage in integrating this with the compiler.

Not the compiler but the standard lib :). If it becomes a dependency there will be a chicken/egg problem: A .nimble file is able to define package dependencies, but if the .nimble itself has a dependency (for the file watchers stuff) it is not runnable to resolve the dependencies.

> Overall though, it's not the end of the world if we remove it. Adding things to the stdlib in the future will be easy once a mature fsmonitor package is created.

Agreed, since a generic/portable API would probably be much different anyway, it can be re-introduced e.g. under a different name.

**Comment by dom96** [comment]
I'm not sure I follow. Are you wanting to integrate it with Nimble?

**Comment by bluenote10** [comment]
Yes, somehow I want to bring SBT's `~run`/`~test` features (or all these npm watcher approaches) into the Nim world. Makes such a huge difference for test driven development.

**Comment by dom96** [comment]
Okay, so once again: why does this need to be inside nimble? Why can't you build an external app that calls Nimble when appropriate?

**Comment by bluenote10** [comment]
It's surely possible (see almost all my repos where I have tried various work-around to this), but the development experience lacks compared to built-in support:

- how to make this external app cross platform?
- how to handle and install the dependencies of the external app itself?
- how to handle task forwarding?
- how to sync knowledge of "triggers" of the external app with the build system itself? In most build systems this knowledge is available only on build system level and is unknown to an external app.

I can only recommend to play around with SBT to see its power. It is just so nice that people can check out any SBT project, run a single, standardized command (`sbt ~test`) no matter what system they are on, and go into a development mode, where you basically see the immediately effects as you type. I was always trying to offer the same in Nim, but there is currently no easy solution and pushing file monitoring out into a third party dependency would probably make it even harder to accomplish this goal.

**Comment by dom96** [comment]
To be honest I'd be reluctant to add this functionality to Nimble.

> how to make this external app cross platform?

Just like any other app? What is it about this task that makes cross platform support more difficult?

> how to handle and install the dependencies of the external app itself?

Using Nimble

> how to handle task forwarding?

I'm not 100% this is what you mean, but:

```
execProcess("nimble c blah")
```

> how to sync knowledge of "triggers" of the external app with the build system itself? In most build systems this knowledge is available only on build system level and is unknown to an external app.

Can you give an example of this?

----

Overall, I am pretty conservative with what makes it into Nimble. Package managers are complex beasts and these additional features only add to the complexity, it'd be better if it was implemented separately.

**Comment by bluenote10** [comment]
> What is it about this task that makes cross platform support more difficult?

Only that a bash solution or even an npm based solution is currently much easier than a Nim solution. Having a nice cross platform solution in the standard library would change that.

What you are suggesting is a custom solution, and won't achieve the _single, standardized command_ property. Every project would have to re-implement the same, and in practice no one will.

I understand your reservation, which is why I'm more looking into possibilities to maybe start out with an addon to Nimble (also the motivation for https://github.com/nim-lang/nimble/pull/427).

**Comment by FedericoCeratto** [comment]
@bluenote10 is something like this what you are looking for? https://github.com/FedericoCeratto/nim-testrunner/

**Comment by bluenote10** [comment]
Yes, the test runner goes in the right direction and is pretty cool for running ad-hoc stuff. What I'm really after is the way this is integrated in modern build systems like SBT or Gradle though. The motivation is the same as the Gradle team had in their [design](https://blog.gradle.org/introducing-continuous-build):

> With Maven, the same watch functionality needs to be implemented for each plugin or you have to use a plugin that has a predefined set of goals. We wanted to do better than that. We wanted any plugin to be able to leverage the power of continuous builds without having to supply additional information. We also wanted the set of tasks to execute to be completely ad-hoc. Since Gradle needs to know a task’s inputs and outputs for incremental builds, we had all the information necessary to start watching for changes.

**Comment by FedericoCeratto** [comment]
@bluenote10 sounds like you want something that monitor files for changes and gives hints to Nimble and Nim to [re]build in the most efficient way. Perhaps this is the use-case you had in mind for Nimble-as-a-library?

**Comment by dom96** [comment]
I still think we should move ``fsmonitor`` out of the stdlib.

**Comment by zah** [comment]
Reacting to file system changes should be a feature supported by the async event loop. On Linux for example, the `inotify` API returns a file descriptor that can be queried for events with the same `epoll` call sitting at the heart of the event loop.

**Comment by ConsoleTVs** [comment]
Just wondering why https://nim-lang.org/docs/fsmonitor.html is down...

**Comment by dom96** [comment]
Because it'll be moved out of the stdlib.

**Comment by dom96** [comment]
@zah I don't think the event loop needs to know anything about inotify. It's file descriptors all the way down, no?

**Comment by zah** [comment]
@dom96, if the low-level APIs (such as `register(fd)`) are enough to implement `fsmonitor` on top of `asyncdispatch`, then yes, but IMO we need to investigate this before we banish `fsmonitor` in user-land.

**Comment by dom96** [comment]
We can always add ``fsmonitor`` back to the stdlib. As it is currently it shouldn't be used anyway as it relies on a deprecated async implementation.

**Comment by dom96** [comment]
Please move to https://github.com/nim-lang/needed-libraries/issues if it's not already there. This will be closed once #9529 is merged.
