### ISSUE TITLE
Expression return bug

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6722]
```nim
type
  Int = ref object
    x: int

proc foo(): int {.discardable.} =
  return 42

proc bar(): Int =
  new result
  result.x = 42
  foo()

echo bar().x
```

The discardable `foo` is returned yielding an error:

```
a1.nim(9, 3) Error: type mismatch: got (int) but expected 'Int = ref Int:ObjectType'
```

Marking as showstopper because I have a pending stdlib change which reproduces this bug (and people might hit it)

**Comment by Araq** [comment]
This is not a bug at all, ``.discardable`` means "discardable in a void context" not "type check and if it doesn't fit, discard ti".

**Comment by dom96** [comment]
Fair
