### ISSUE TITLE
Compilation error with "newseq[string]"

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#6726]
The following program doesn't compile:

```Nim
import gdk2
var x = newSeq[string]()
```

Indeed, gdk2 exports several procedures with name "string" which seems to confuse the compiler. It worked in a previous (and not too old) version of the compiler, but I don't know which one. Of course, to see more clearly the problem, we can replace the first line by ```proc string: string = "some text"```.

There are several easy workarounds. For instance:
* replacing first line by ```import gdk2 except string``` (not the best solution, I think)
* replacing second line by ```var x: seq[string] = @[]```
* replacing second line by ```var x = newSeq[system.string]()```.

But, in fact, is there a bug? If the behaviour is normal, is it possible to get a more friendly error message?

**Comment by bluenote10** [comment]
Related issue: https://github.com/nim-lang/Nim/issues/6693
