### ISSUE TITLE
Possible bug related to generics type resolution/matched

### ISSUE THREAD

**Issue by zlash** [nim-lang/Nim#6732]
Hello,
I expect the following snippet to fail compilation, however it compiles correctly. 
The `.type.name` expressions show different types on both `echo` calls when, as I understand, they should be `ref`s to the same object.
I apologize in advance If it is not a bug and a misunderstanding of nim from my part

```nim
import typetraits

type
    TT[T] = ref object of RootObj
        val: T
    CB[T] = proc (v: T): void

proc testGeneric[T](val: TT[T], cb: CB[T]): void =
    echo val.type.name
    echo $val.val


var tt = new(TT[seq[string]])
echo tt.type.name
tt.testGeneric( proc (v: int): void =
    echo $v )
```

**Comment by zah** [comment]
The output from the devel branch is:

```
TT[seq[string]]
TT[seq[string]]
```

What was the output you got?

**Comment by andreaferretti** [comment]
I think the problem is that this example should not compile. The two `T` in  `TT[T]` and `CB[T]` are different: from `TT` the compiler can infer `T = seq[string]`, but from `CB` it can deduce `T = int`.

**Comment by zah** [comment]
Ah, I see. This should be an error indeed.

**Comment by zlash** [comment]
Exactly, as @andreaferretti said.
FYI, i'm running `Version 0.17.2 (2017-09-08)` and the output of the snippet is: 

```
TT[seq[string]]
TT[system.int]
0
```
