### ISSUE TITLE
`low` and `high` on a distinct type doesn't return the distinct type

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6733]
I would expect this to work:

```nim
type A = distinct int

proc foobar(a: A) = discard

foobar(low(A))
# in.nim(5, 7) Error: type mismatch: got (int)
# but expected one of: 
# proc foobar(a: A)
```

**Comment by narimiran** [comment]
Convert the result of `low(A)` back to `A` type:
```
foobar(A(low(A)))
```

**Comment by Adrien79** [comment]
@GULPF: I agree, I was about to open an issue for the same thing.

@narimiran: yes you can convert back but this does not respect the signature of high and low
```proc high*[T: Ordinal](x: typeDesc[T]): T```
And with the conversion I'm getting warnings like this:
```lib\system.nim(1991, 19) Hint: conversion from Point to itself is pointless [Con                                                              vFromXtoItselfNotNeeded]```

**Comment by Araq** [comment]
Finally fixed this one.
