### ISSUE TITLE
Can't create seq containing both literals and non-literals

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#6737]
This code:
```
let l: uint64 = 2
let a = @[0, l]
```
results in compiler error: `foo.nim(3, 14) Error: type mismatch: got (uint64) but expected 'int literal(0)'`

This code worked in 0.17.0.

**Comment by Araq** [comment]
Seems correct that it doesn't work? The first element of an array literal determines the type.

**Comment by zielmicha** [comment]
`int literal(0)` should be castable to any integer type, so I would expect the compiler to be smart enough - at least it was previously. 

I can understand this change if it simplifies the compiler.

**Comment by krux02** [comment]
Even though the error message is a bit weird, it is correct behavior. The type of the seq/array is deduced from the type of the first element, in this case it is an `int literal(0)` which in this context is not different at all from an int. The second parameter is not automatically convertable to `int`.

**Comment by narimiran** [comment]
> Seems correct that it doesn't work? 

> it is correct behavior.

Agreed. And I would add that this is exactly the behaviour I would expect.

With three votes for it, I think we can close it.

**Comment by Araq** [comment]
The spec says:

> An array expression may be constructed by the
array constructor ``[]``. The element type of this array expression is
inferred from the type of the first element. All other elements need to be
implicitly convertable to this type.
