### ISSUE TITLE
Incorrect int64 overflow with JS backend

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6752]
Test case:
```nim
proc foo() =
    let x = 711127'i64
    let y = x * 86400'i64 # Overflow with js backend, but not with other backends
foo()
```

**Comment by Araq** [comment]
Seems correct to me, on JS ``int`` is 32bits and 61_441_372_800 doesn't fit in 32 bits.

**Comment by GULPF** [comment]
You're correct, but there still seems to be an issue somewhere.

This works (but shouldn't?):

```nim
import typetraits
let x = 711127
let y = x * 86400
doAssert type(y).name == "int"
doAssert y > high(int)
```

This works (and should?):
```nim
let x = 711127'i64
doAssert type(x * 86400'i64).name == "int64"
let y = x * 86400'i64
```

This doesn't work (but should?):
```nim
proc foo() =
    let x = 711127'i64
    doAssert type(x * 86400'i64).name == "int64"
    let y = x * 86400'i64 # Overflow
foo()
```

**Comment by skilchen** [comment]
As @Araq  told us in another context JS has only float64 numbers. Unless you are using bitwise operations. Then the float64 numbers are indeed handled as int32. So as long as you don't use bitwise operations, i think it is safe to turn of this overflow check off, if you keep in mind that you have only 53 bits of precision available to represent integers exactly in float64 numbers. You can have something like int53 in JS but not really int64.
