### ISSUE TITLE
JS integer division off by one

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6753]
```nim
let x = -1861876800
const y = 86400
echo (x - 86399) div y # JS backend gives `-21551`, should be `-21550`
```

**Comment by Araq** [comment]
Seems a JS issue? JS only knows about floating point arithmetic.

**Comment by skilchen** [comment]
On the c backend `div` performs truncating division on integers (rounding towards zero). Expressed in Javascript:
```Javascript
Math.trunc(x / y)
```
But for `x div y` Nim on the js backend generates:
```Javascript
Math.floor(x / y)
```
In many date/time related areas you need floor division (rounding towards negative infinity). I assume  it is no longer possible to change the way how `div` is translated to javascript. So the example becomes:
```nim
let x = -1861876800
const y = 86400
when defined(js):
  echo x div y
else:
 echo (x - y + 1) div y
```
to perform floor division on both backends

**Comment by Araq** [comment]
No, we need to do ``trunc`` then and it's just a bug. ``changelog`` needs to mention that it's a slightly incompatible bugfix.

**Comment by skilchen** [comment]
In the documentation for `div` in module `system` we are told:
```nim
  ## computes the integer division. This is roughly the same as
  ## ``floor(x/y)``.
```
this is not the way Nim currently handles it on the C backend. Nim does roughly the same as trunc(x/y). 

a somewhat related thing:
```nim
import math
echo -5 mod 3
echo -5.0 mod 3.0
```
gives:
> -2
> 1.0 (or 1 on the js backend, but this is only due to the different way floats are converted to strings)

the first is the result of using truncating division (Nim delegates the work to the % operator of the backend) and the second is the result of using floor division (x - floor(x / y) * y as documented in the math module). 

Is this difference between integers and floats intended?

**Comment by Araq** [comment]
> Is this difference between integers and floats intended?

No, but that's a different bug. ``mod`` is not ``div``.

**Comment by GULPF** [comment]
This can still be reproduced if the code is inside a proc:
```nim
let x = -1861876800.int64
const y = 86400
echo (x - (y - 1)) div y # Now gives `-21550`

proc foo() =
    let x = -1861876800.int64
    const y = 86400
    echo (x - (y - 1)) div y # Still gives `-21551`
foo()
```
