### ISSUE TITLE
vcc and atomics.nim: atomicLoad/atomicStore missing

### ISSUE THREAD

**Issue by mikra01** [nim-lang/Nim#6760]
Hi all, 

as disussed here : https://forum.nim-lang.org/t/3324  

the atomics.nim is not that unified between gcc (c11) and vcc ( properitary ). 

Especially atomicStore and atomicLoad is missing for the vcc. I fiddled around a little bit and got that following solution running: https://gist.github.com/mikra01/2d217f484b2679d10154a72f21022390 
( I am open to rename the proc-names and I just added interlockedExchange, InterlockedAnd,, InterlockedOr)

It would be nice if this could be merged into the atomics.nim so I can remove it locally (and others don´t need to fiddle around too)
https://github.com/mikra01/timerpool/blob/master/timerpool.nim

**Comment by Araq** [comment]
We now have ``lib/pure/concurreny/atomics.nim`` with implementations for vcc.

**Comment by mikra01** [comment]
ok  great; thank you very much.
