### ISSUE TITLE
Using : (constructor arguments) for passing values to functions with default arguments causes a compiler crash.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#6765]
Function:
`proc myFunc*(myObject: ObjectType, x: int = 0) =`

Crashes:
`myObject.myFunc(x: 1)`

Should be:
`myObject.myFunc(x = 1)`

So yes, user error. That said, the compiler completely crashes instead of giving a syntax error. This ONLY happens when an object is involved AND the function is run as myObject.myFunc.

Paste of crash with Stack/Line trace enabled in the compiler (0.17.3 with -d:release): 
https://pastebin.com/UzMefn8p

Cause? semtypes.nim:1423 tries to use typeExpr.typ.kind in an if check, yet typeExpr.typ null.

**Comment by dom96** [comment]
Hope the #GithubGameOff is going well ;)

Thanks for submitting this bug!

**Comment by kayabaNerve** [comment]
`type Obj = object

proc test(o: Obj, x: int = 0) = discard; 

Obj().test(x: 1)`

Code courtesy of Serenit0r
