### ISSUE TITLE
Cleanup macros.nim core module

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#6778]
- Deprecate the ``!`` operator.
- Deprecate ``repr`` and use ``$`` instead.
- Remove deprecated operations.
- Check the documentation.

**Comment by konqoro** [comment]
remove compileTime pragmas?

**Comment by konqoro** [comment]
and what about removing cmpIgnoreCase and import strutils instead?

**Comment by konqoro** [comment]
also remove `toNimIdent`

**Comment by Bennyelg** [comment]
Hey, Just need remove them?
I already see that in example:
proc `!`*(s: string): NimIdent {.magic: "StrToIdent", noSideEffect, deprecated.}
tagged as deprecated 
If so, please assign me ?

**Comment by Araq** [comment]
Can't assign you. Create a PR and I will invite you afterwards. Deal?

**Comment by Bennyelg** [comment]
Ok, I'll do that first thing tomorrow! :)

**Comment by konqoro** [comment]
So after the documentation was updated, toNimIdent appears in it. Though there is still `ident(string) is NimIdent` and `toNimIdent(string) is NimIdent`, one less option but still confusing which to use.

Also it is not clear what is the proper way to check the name (string) of an NimIdent. You can convert the string to an NimIdent using the above procs or turn the NimIdent to a string and use string comparison such as cmpIgnoreCase. Stating which is the proper way would be helpful.

**Comment by Bennyelg** [comment]
Hey, Im working on this fix.
newbie questions:
Introduce a pure enum instead of this nnk mess. -> can you elaborate ?
Deprecate repr and use $ instead, replace repr with $ not sufficient.
when I try in example to replace it I get this:
```
type mismatch: got <NimNode>
but expected one of:
proc `$`(i: NimIdent): string
proc `$`(s: NimSym): string
proc `$`(x: string): string
proc `$`(s: WideCString): string
proc `$`[T: tuple |
    object](x: T): string
proc `$`(x: uint64): string
proc `$`(x: int64): string
proc `$`[T, IDX](x: array[IDX, T]): string
proc `$`[Enum: enum](x: Enum): string
proc `$`(w: WideCString; estimate: int; replacement: int = 0x0000FFFD): string
proc `$`[T](x: set[T]): string
proc `$`[T](x: seq[T]): string
proc `$`(x: int): string
proc `$`(x: cstring): string
proc `$`(x: bool): string
proc `$`(x: float): string
proc `$`(x: char): string
```
which is understandable due to the repr proc which look like this:
```proc repr*[T](x: T): string {.magic: "Repr", noSideEffect.}```

**Comment by konqoro** [comment]
1) remove nnk from all the enums and mark the type with the {.pure} pragma.

**Comment by Bennyelg** [comment]
@konqoro 
so instead nnkObjConstr -> ObjConstr ?
this wont work.
example:
```result = ObjConstr.newTree(arg.type.getTypeInst[1])```
``` undefine undentifier```

**Comment by konqoro** [comment]
@Bennyelg  if you submit a PR I will help you with the errors.

**Comment by Araq** [comment]
> Introduce a pure enum instead of this nnk mess. -> can you elaborate ?

Please don't do this, this needs at least a discussion. Probably there are other more backwards compatible ways to avoid the nnk prefix.

**Comment by Bennyelg** [comment]
I'll start with a simple pull request to get my self in business
