### ISSUE TITLE
Feature request for a NimNode to typedesc conversion proc in macros

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#6785]
Currently, `macros.nim` does not offer a way to convert a `NimNode` (obtained from `getType` on a typed expression) into the corresponding typedesc:

```nim
import macros

proc f(T: typedesc[SomeInteger]) =
  echo "called f with some integer"

proc f(T: typedesc[string]) =
  echo "called f with string"

macro aMacro(x: typed) =
  let typeNode = x.getType()
  # Call f at compile time is not possible because
  # typeNode can't be converted to typedesc.
  f(typeNode)

aMacro(1)
aMacro("string")
```

Error:

```
test.nim(13, 4) Error: type mismatch: got (NimNode)
but expected one of: 
proc f(T: typedesc[SomeInteger])
proc f(T: typedesc[string])
```

Note that there is a workaround: Doubling the argument of the macro into `aMacro(x: type, typedescOfX: typedesc)`, and one could write a wrapper macro that takes a typed expression `x` and generates the AST `aMacro(x, type(x))`.

**Comment by jangko** [comment]
similar with above issue, inside macro/`compile time proc` we cannot convert NimNode back into compile-time-value without workaround.  An `intLit` or `strLit` of course can use `intVal` and `strVal`, but something like enum need few more lines to convert it back into compile-time-value.

for example:

```Nim
type
  Fruit = enum
    apple
    banana
    orange
    
macro hello(x: static[Fruit]) =
  echo x  # here x is a compile time value

macro foo(x: typed) =
  # x is a symbol
  echo "possible but not simple"

macro bar(x: untyped) =
  # x is a list of idents
  echo "possible but not simple"

hello(apple) # ok

foo(apple)

bar:
  apple
  banana
  orange
```
  
we have static param and typedesc param for macro, we can convert NimNode into runtime literal.
additional compiler magic to convert NimNode into compile-time-value and compile-time-type-literal will be handy.

**Comment by krux02** [comment]
The issue as it is proposed cannot work. Let's assume there would be a ``typedescVal``, it would return a ``typedesc`` without a generic parameter. So you would not be able to call ``f`` on it. Here is an example:

```nim
proc f(T: typedesc[SomeInteger]) =
  echo "called f with some integer"

proc f(T: typedesc[string]) =
  echo "called f with string"

static:
  let xxx = [int, string]  # xxx is now such a typedesc
  echo f(xxx[0])
```

nimout:
```
scratch.nim(51, 9) Error: type mismatch: got <typedesc>
but expected one of: 
proc f(T: typedesc[SomeInteger])
proc f(T: typedesc[string])
```

You have to generate the call to ``f`` to make it work


```nim
import macros

proc f(T: typedesc[SomeInteger]) =
  echo "called f with some integer"

proc f(T: typedesc[string]) =
  echo "called f with string"

proc f(arg: NimNode) =
  let someInt = bindSym"SomeInteger"
  echo someInt.getImpl.treeREpr
  #echo arg.treeRepr

macro aMacro(x: typed) =
  result = quote do:
    f(typeof(`x`))

aMacro(1)        # called f with some integer
aMacro("string") # called f with string

```

**Comment by bluenote10** [comment]
I don't get what your example has to do with the original example. In the original example all necessary information should be in the `NimNode`.

**Comment by krux02** [comment]
Please elaborate on what you don't understand. I went into quite some detail about why your proposal can't work. ``typedesc`` is very confusing.

**Comment by jangko** [comment]
@krux02 thank you for the enum magic, that would be very useful.

@bluenote10 : I think from @krux02 example, he want to says `typedesc typedesc` and possibly another `typedesc typedesc typedesc ...` is really confusing.
```Nim
static:
  let xxx = [int, string]  # xxx is now such a typedesc
  echo f(xxx[0])
```

but your example also a bit confusing, I think if it modified a bit, it would make your intention clearer.
perhaps what you want is something like this:
```Nim
import macros

proc f(T: typedesc[SomeInteger]) =
  echo "called f with some integer"

proc f(T: typedesc[string]) =
  echo "called f with string"

macro aMacro(x: typed) =
  let typeNode   = x.getType()
  const T = typeMagic(typeNode)  # `typeMagic` is not available in macros module
  f(T)

aMacro(1)
aMacro("string")
```

**Comment by zah** [comment]
It's certainly possible to define semantics that will make @krux02's example work.
You can treat the overloaded typedesc procs as methods using dynamic dispatch based on the "concrete" type stored in the "abstract" typedesc instance variable.

**Comment by bluenote10** [comment]
@krux02 The use case is to call `f` at compile time. Within the macro the type of `x` is fully determined because it is `typed`. If the macro is called with `1` the type can be inferred to `int` and thus all information to call `f(int)` is available. Your snippet is an example of typedescs losing their generic argument -- I don't see the connection.

Your work-around doesn't address the use case, which is to call `f` within the macro statically, not returning an AST of `f` calls.

**Comment by krux02** [comment]
> It's certainly possible to define semantics that will make @krux02's example work. You can treat the overloaded typedesc procs as methods using dynamic dispatch based on the "concrete" type stored in the "abstract" typedesc instance variable.

Sorry, but no. _procs_ remain _procs_ with static dispatich. And _methods_ remain _methods_ with dynamic dispatch. This is out of discussion.

> The use case is to call f at compile time. 
To clear things up. Macros are compiled "at compile time" to bytecode, and they are evaliated "at compile time". Let's call these _macro compile time_ and _macro run time_. You want to call `f` at _macro run time_, but the overload resolution of ``f`` needs to happen at _macro compile time_. But at _macro compile time_ you don't know the arguments yet.

> Within the macro the type of x is fully determined because it is typed. 

Not at macro compile time. It is only part of the ``NimNode`` value.

> If the macro is called with 1 the type can be inferred to int and thus all information to call f(int) is available. 

Nope.

> Your snippet is an example of typedescs losing their generic argument -- I don't see the connection.

Try again.

**Comment by mratsim** [comment]
If `typedesc` is misdesigned that's an argument to overhaul typedesc, not to close this reasonable feature in my opinion.

Currently I can't use the `sameType` macro from a IdentDef to check if `sameType(x, bindSym"seq")` with x being `nnkBracketExpr(ident"seq", ident"int")` because I have no way to convert back x to a typed node after parsing it from a proc definition.

I.e. another case of https://github.com/nim-lang/RFCs/issues/44

**Comment by mratsim** [comment]
Another: https://forum.nim-lang.org/t/8913
