### ISSUE TITLE
encodeUrl and decodeUrl cannot be used by JS targets

### ISSUE THREAD

**Issue by darkmusic** [nim-lang/Nim#6804]
`encodeUrl` and `decodeUrl` are in module `cgi`, which imports module `os`, so it cannot be used by JS targets.  The error given by module `os` when attempting to `nim js` a nim file containing a `import cgi` statement is the following:
`lib/pure/os.nim(27, 10) Error: OS module not ported to your operating system!`

**Comment by dom96** [comment]
These procedures should be moved into the uri module.

**Comment by dom96** [comment]
First PR material? :)

If someone wants to tackle this, make sure to keep a deprecated copy of these procs in the cgi module.

**Comment by Veladus** [comment]
Okay, I will try this, but might take some time since I've never done a PR before, but I want to get engaged :)
