### ISSUE TITLE
Testament output diffs

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6811]
In some cases it's really difficult to tell the difference between the "Expected" and "Gotten" output. A diffing feature would be nice.

**Comment by bluenote10** [comment]
:+1: I was struggling with the output matching as well before. I was wondering for quite some time if something like #6812 is technically feasible and if it could simplify these compiler output tests?

**Comment by narimiran** [comment]
+1

**Comment by timotheecour** [comment]
Note:
there's some partial support:
```
categories.nim:622:27:    discard execShellCmd("diff -uNdr outputExpected.txt outputGotten.txt")
```
maybe time to use lib/experimental/diff.nim

we should both the diff, and the expected, and output, to make it easier to update test case when it needs to be updated (ie, don't just show the diff)

**Comment by timotheecour** [comment]
I've added unittest_light with `assertEquals`, `mismatch` in https://github.com/nim-lang/Nim/pull/10182 ; it could be used in tests, and produces helpful err msg showing where the 1st mismatch is, along with context, taking care of highlighting whitespace mismatches, etc

**Comment by Araq** [comment]
This has been implemented for quite some time now.
