### ISSUE TITLE
Feature Request: Default compiler C

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#6828]
Why specify compiling to C if it is the most common compiler back-end.

If other back-end specified, then if over-rides the default.
e.g.,

``nim -r test.nim``  -> compiles to C
``nim c -r test.nim`` -> still backwardly compatible
``nim cpp -r test.nim`` -> compiles to C++
...

**Comment by dom96** [comment]
I actually think the ``c`` stands for ``compile``, ``cc`` is ``compile to c``.

Sorry, but I don't think this should be changed so I'm closing this.
