### ISSUE TITLE
Impossible to create an empty const array

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#6853]
The following line fails to compile:
  `const required_fields: array[0, tuple[f1: int, f2: string]] = []`

with Error
```
Error: type mismatch: got (array[0..-1, empty]) but expected 'array[0..-1, tuple[f1: string, f2: stri
ng]]'
```

Empty const arrays can be useful in macros for example

**Comment by Yardanico** [comment]
This won't make any sense, you compile-time sequences then

**Comment by cooldome** [comment]
seq is a work-around, but arrays should work as well
