### ISSUE TITLE
Compiler error on mixed types in a seq

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6858]
The compilation fails with: `Error: type mismatch: got (seq[Bar]) but expected 'seq[Foo]'`

Code:
```
type
  Foo = object of RootObj
    items: seq[Foo]
  Bar = object of Foo

var x = Foo(items: @[Foo(), Bar()])
x = Foo(items: @[Bar()])               # fails here
```
Demo: https://play.nim-lang.org/?gist=36f75dd106810a6129e07872a7a0a606

**Comment by Araq** [comment]
Documented behaviour. The first expression in an array literal determines the array's type.
