### ISSUE TITLE
For loops with 0..<uint16 started to error with ambiguous call.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#6866]
Not sure if its new error or feature? I have just updated nim to new git version (8fbe37b2d813f00ca934cee2fe17bc2e24f82f88) and new error happened in my code:

```
var number: uint16 = 12
for i in 0..<number:
  echo i
```

```
mtest.nim(2, 11) Error: ambiguous call; both system...(a: uint32, b: uint32)[declared in lib/system.nim(2033, 13)] and system...(a: uint64, b: uint64)[declared in lib/system.nim(2033, 13)] match for: (int literal(0), uint16)
```

Maybe a `max(a: uint16, b: uint16)` should be added to system.nim?

**Comment by andreaferretti** [comment]
I am not sure about the cause, but a quick fix is to use `0'i16` as the first elememt for iteration, like `0'i16 ..< number`

**Comment by treeform** [comment]
I used `0..<int(number)` to fix it. Your method works too.

**Comment by narimiran** [comment]
Since we have two solutions, can we mark this as solved, and close it?

**Comment by treeform** [comment]
Ok
