### ISSUE TITLE
nimsuggest def should go to definition, not forward declaration

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6867]
As an example, when trying to go to the definition of startProcessAfterFork at https://github.com/nim-lang/Nim/blob/c039bbf6e1186ba8a6f65fa6e0179c8245f2d483/lib/pure/osproc.nim#L888 it goes to https://github.com/nim-lang/Nim/blob/c039bbf6e1186ba8a6f65fa6e0179c8245f2d483/lib/pure/osproc.nim#L727 rather than https://github.com/nim-lang/Nim/blob/c039bbf6e1186ba8a6f65fa6e0179c8245f2d483/lib/pure/osproc.nim#L912

It would be super cool if it could also see through the `{.magic: "RealImpl".}` style forward declarations and go to the real impl in the compiler, but I could see that being much harder.

**Comment by andreaferretti** [comment]
Closing because of https://github.com/nim-lang/nimsuggest/issues/79
