### ISSUE TITLE
'nim' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by 1j01** [nim-lang/Nim#6878]
It's added to my *system PATH*, so apparently I have to open an administrative command prompt to access `nim`, probably until I restart my computer or otherwise logout.

And VS Code (with a Nim extension) says:
> No 'nim' binary could be found in PATH environment variable

(even after restarting the application)

And in the integrated terminal it of course can't access it either:
```
Isaiah@ironsmith MINGW64 /c/Users/Isaiah
$ nim
bash: nim: command not found
```

So basically I can't get started with Nim without restarting my computer,
or using an admin command prompt, which doesn't seem like a great idea
(and on another day I probably wouldn't have thought to try that)

The whole installation [and getting started](https://github.com/nim-lang/website/issues/56) experience seems rather half baked. Why's there no installer? I see mentions of an installer when searching through the issues. Was it abandoned?

(btw I had to do the manual 'download mingw and place in folder' thing for some reason (I don't know why it would fail to download) ((and I went and extracted it before realizing that wasn't part of the instruction and so I had to wait for it to extract a second time)))

**Comment by Araq** [comment]
> It's added to my system PATH, so apparently I have to open an administrative command prompt to access nim, probably until I restart my computer or otherwise logout.

If you don't run ``finish.exe`` as admin (and why would you, that's not documented anywhere) the user specific PATH environment variable is changed and no restart is required.

> And in the integrated terminal it of course can't access it either:

Bash is not the "integrated terminal" on Windows.

> Why's there no installer? I see mentions of an installer when searching through the issues. Was it abandoned?

The traditional installer worked worse than finish.exe, that's why.

> (btw I had to do the manual 'download mingw and place in folder' thing for some reason; I don't know why it would fail to download ((and I went and extracted it before realizing that wasn't part of the instruction and so I had to wait for it to extract a second time)))

I don't know either, the concrete error message would have been helpful. Your bug report is rather half baked.

**Comment by 1j01** [comment]
Hm, it's available now, maybe because I hit okay on the env vars dialog after checking to see that it was there. Or maybe Windows updated the env vars after an hour or two. Either way I think Windows being shitty is a definite component of this. I ran into the same sort of problem installing `yarn` recently.

> If you don't run finish.exe as admin

I didn't... and I do see the entry in the user PATH now, so maybe I missed it.

> Bash is not the "integrated terminal" on Windows.

I meant the VS Code integrated terminal.

> The traditional installer worked worse than finish.exe, that's why.

Why did it work worse? Was it something inherent to Windows installers, or could it be made to, for instance, place the distribution files into a folder in Program Files and then run `finish.exe`? I feel like it'd be worth it just to have a proper installation location (instead of in my Downloads folder which I'd like to be able to reorganize).

> I don't know either, the concrete error message would have been helpful. Your bug report is rather half baked.

I just remember it said it "Failed", seemed pretty nondescript (at a glance). 
Do you want me to go through the install process again, and paste the output?

**Comment by Araq** [comment]
> I just remember it said it "Failed", seemed pretty nondescript (at a glance).
Do you want me to go through the install process again, and paste the output?

Nah, I know the problem. Will be fixed with the next release ("curl.exe" with spaces in its path).

> Why did it work worse? Was it something inherent to Windows installers, or could it be made to, for instance, place the distribution files into a folder in Program Files and then run finish.exe? I feel like it'd be worth it just to have a proper installation location (instead of in my Downloads folder which I'd like to be able to reorganize).

We found no good tool that allows us to do the optional downloads or configuration adaptations. A Nim program works much better then some barbaric scripting language that's embedded into an setup.exe builder.

**Comment by Araq** [comment]
No feedback. Closing.
