### ISSUE TITLE
Async procs don't properly support `finally`

### ISSUE THREAD

**Issue by MednauN** [nim-lang/Nim#6880]
Nim from commit c7ba4d91a34882e94969595ba70763f9f642423c
```nim
import asyncdispatch

proc failingProc(): Future[void] {.async.} =
  if true:
    raise newException(Exception, "Look ma, I'm an exception!")

proc catchingProc(): Future[void] {.async.} =
  try:
    await failingProc()
  except:
    echo "except"
  finally:
    echo "finally"

catchingProc().waitFor()
```
"except" is called, but not "finally"

If raise an exception before `await` like this
```nim
proc catchingProc(): Future[void] {.async.} =
  try:
    if true:
      raise newException(Exception, "No one can catch me!")
    await failingProc()
  except:
    echo "except"
  finally:
    echo "finally"
```
proc fails with exception. Neither "except" nor "finally" is called.

After removing "except" block like this
```nim
proc catchingProc(): Future[void] {.async.} =
  try:
    await failingProc()
  finally:
    echo "finally"
```
"finally" is called.

That's really misleading - the code is compiled without any errors or warnings but simply doesn't work. I think it would be nice to have at least some warning if these cases are not supported.

**Comment by cheatfate** [comment]
@MednauN if you read documentation of `asyncdispatch.nim` you can find this:

```
## Handling Exceptions
## ~~~~~~~~~~~~~~~~~~~
##
## The most reliable way to handle exceptions is to use ``yield`` on a future
## then check the future's ``failed`` property. For example:
##
##   .. code-block:: Nim
##     var future = sock.recv(100)
##     yield future
##     if future.failed:
##       # Handle exception
##
## The ``async`` procedures also offer limited support for the try statement.
##
##    .. code-block:: Nim
##      try:
##        let data = await sock.recv(100)
##        echo("Received ", data)
##      except:
##        # Handle exception
##
## Unfortunately the semantics of the try statement may not always be correct,
## and occasionally the compilation may fail altogether.
## As such it is better to use the former style when possible.
```

But core problem of implementation try/except/finally is C/C++ not support `goto` inside to `try/except/finally` block.

**Comment by MednauN** [comment]
@cheatfate my concern is that there is no indication when "try" block will work and when it won't. If it works only within specific requirements, maybe it's worth to add a compilation error if the code block doesn't match these requirements.

**Comment by yglukhov** [comment]
All of the samples work as expected now.
