### ISSUE TITLE
noreturn branches of case statements shouldn't contribute to type

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6885]
This code currently fails to compile:

```nim
let val = 1
var test = case val
    of 1: true
    of 2: false
    else: quit "huh?"
```

`quit` is labeled `{.noReturn.}` so the compiler knows that if the else branch executes, `test` will never be assigned to. This ugly workaround is currently required:

```nim
let val = 1
var test = case val
    of 1: true
    of 2: false
    else: (quit "huh?"; true)
```

**Comment by GULPF** [comment]
Related: #842
