### ISSUE TITLE
Add support for Sticky Bit permissions in OS module

### ISSUE THREAD

**Issue by NopeDK** [nim-lang/Nim#6896]
As per title, could support for the Sticky Bit (S_ISVTX) be added?

Quick patch that passes stdlib test suite:
[Patch.diff](https://pastebin.com/PpekPnrG)
[Patch.test](https://pastebin.com/6bFNFUeH)
Program output with patch:
[Patch.ls](https://pastebin.com/Cc24ft9A)

Thank you

**Comment by dom96** [comment]
We don't typically accept patches, any chance you could create a PR?

**Comment by NopeDK** [comment]
I have attempted to create a pull request. (#6901)

**Comment by NopeDK** [comment]
Advanced permissions will either force users to consider them when using os.nim for basic tasks or will be too hacky to implement.
I have closed the pull request and the issue.
