### ISSUE TITLE
json.to and Option[T] fails on JNull in JSON list literal

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#6902]
Json.to now recognizes the absent of a optional key as None[T]. But fails on an JNull value

```
import json, options
type
  Obj = object
    requiredNum: int
    optionalNum: Option[int]
  Objs = seq[Obj]

var j0 = parseJson("""{"requiredNum": 0, "optionalNum": null}""")
echo j0.to(Obj)

var j1 = parseJson("""[{"requiredNum": 0, "optionalNum": null}]""")
echo j1.to(Objs)
```

fails with:

```
json.nim(1367)
Error: unhandled exception: Incorrect JSON kind. Wanted '{JNull, JString}' in 'temp229022["optionalNum"]' but got 'JInt'. [JsonKindError]
```
it could be that the first error is fixed when changeing json.nim:1690 to

          if `lenientJsonNode`.isNil or `jsonNode`.kind == JNull : `workaround`[`optionGeneric`]() else: some[`optionGeneric`](`value`)

but then j1 still fails with:
```
lib/pure/json.nim(1903, 25) Error: type mismatch: got (JsonNode, int)
but expected one of:
proc `{}`(node: JsonNode; keys: varargs[string]): JsonNode

expression: {}(temp229031, i229238)
```

**Comment by dom96** [comment]
Are you testing this on ``devel``? I'm seeing the compile-time error you're quoting.

**Comment by dom96** [comment]
This seems to only be an issue when using ``to`` on a list JSON literal.

**Comment by enthus1ast** [comment]
Yes on devel. The second error message is after my attempt to fix the first bug.

**Comment by dom96** [comment]
I'm on devel and getting the second error message without any changes.

**Comment by enthus1ast** [comment]
yes you're right, forget to rebuild Nim, first error is gone, seconds still there.

**Comment by enthus1ast** [comment]
sorry dom96 i was too fast. Error is still there just comment out the second test.
