### ISSUE TITLE
Comparisons between extreme Time values are broken

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6905]
```nim
import times
const hi = Time(Time.high)
const lo = Time(Time.low)

echo lo <= hi # true
echo hi <= lo # also true !?!?!
```

It looks like the issue is that for some reason it is comparing times via subtraction rather than signed comparison: https://github.com/nim-lang/Nim/blob/28e0bf9dcd62f387c79f767848cadd8b71d825de/lib/pure/times.nim#L243

I'm using Time.high and Time.low as sentinel values that are supposed to act newer/older than any real file. This came up when I noticed that min(high, low) was returning high and files that didn't exist were considered up to date!

**Comment by GULPF** [comment]
I think it was done this way because `time_t` is supposed to an opaque type, so `<`, `>` and `=` had to be defined in terms of `difftime`. I'll fix this in  #6552.

**Comment by RedBeard0531** [comment]
> because time_t is supposed to an opaque type

Actually c and c++ guarantee that time_t is an arithmetic type: http://en.cppreference.com/w/c/chrono/time_t. C11 even goes as far as banning complex and imaginary times!

**Comment by Araq** [comment]
> Actually c and c++ guarantee that time_t is an arithmetic type: http://en.cppreference.com/w/c/chrono/time_t. C11 even goes as far as banning complex and imaginary times!

Irrelevant, Nim's Time just happens to use ``time_t``.
