### ISSUE TITLE
[Documentation] |foo| --> Warning unknown substitution

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6907]
Compiling this with Nim doc gives unknown substitution:

```Nim
proc absolute_error*[T](y_true, y: T): T =
  ## Absolute error for a single value, |y_true - y|
  result = abs(y_true - y)
```

```
Warning: unknown substitution 'y_true - y' [UnknownSubstitutionX]
```

**Comment by Araq** [comment]
That is an unknown reStructuredText substitution. http://docutils.sourceforge.net/docs/user/rst/quickref.html#substitution-references-and-definitions
