### ISSUE TITLE
[Documentation] uneven '*' character --> Error '*' expected

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6910]
I'm trying to use `nim doc` on a file with a dependency on @andreaferretti Nimcuda.

`nim doc` fails for any line with uneven number of star characters. As far as I know nimcuda documentation is autogenerated by c2nim and have a lot of such:

[cublas_api.nim(139, 52)](https://github.com/unicredit/nimcuda/blob/master/nimcuda/cublas_api.nim#L139)
```Nim
  ##  cublasSetVector (int n, int elemSize, const void *x, int incx, 
  ##                   void *y, int incy) 
```

[cuda_occupency(265, 4)](https://github.com/unicredit/nimcuda/blob/master/nimcuda/cuda_occupancy.nim#L265)
```Nim
##  If *blockSize is 0, then the given combination cannot run on the device.
```

Error is:
```
Error: '*' expected
```

**Comment by Araq** [comment]
The doc gen uses reStructuredText. Fix your documentation.
