### ISSUE TITLE
httpclient: maxRedirects do not limit redirection

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#6916]
Any value other than 0 does not limit the number of redirects that httpclient is following. However in the deprecated get procedure setting maxRedirects has the desired effect.
Test case:
```nim
discard """
  output: '''302 FOUND
302 FOUND
'''
"""

import httpclient

proc test_redirect() =
  var client = newHTTPClient(maxRedirects = 1)
  let data = client.get("http://httpbin.org/redirect/2")
  echo $data.status

proc test_redirect_1() =
  let data = get("http://httpbin.org/redirect/2", maxRedirects = 1)
  echo $data.status

test_redirect()
test_redirect_1()
```
this will output:
```
200 OK
302 FOUND
```
instead of the expected:
```
302 FOUND
302 FOUND
```
This is due to the recursive call of client.request on line 1170 of httpclient.nim.

There are some other issues with the redirect handling as well:
- in the procedure downloadFile the redirect handling doesn't work at all, because downloadFile sets `client.getBody = false` but it is not possible to follow a redirect if you don't read the body of the redirect response.
- if you use a proxy and the redirect response directs you to a https url on another host, then you need to first establish a new proxy tunnel, otherwise the redirection doesn't work.

Unfortunately currently i am unable to propose a fix for these issues.

**Comment by narimiran** [comment]
```nim
import httpclient

proc test_redirect() =
  var client = newHTTPClient(maxRedirects = 1)
  let data = client.get("http://httpbin.org/redirect/2")
  echo $data.status

test_redirect()
```

in Nim 0.19.9 produces `302 FOUND`.
