### ISSUE TITLE
Object variants issue

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#6918]
This according to [the manual](https://nim-lang.org/docs/manual.html#types-object-variants) should not be allowed:
```
type
  NodeKind = enum
    nkInt, nkFloat
  
  Node = ref NodeObj
  NodeObj = object
    case kind: NodeKind
    of nkInt: intVal: int
    of nkFloat: floatVal: float

let a: Node = Node(kind: nkInt, intVal: 2)
echo a.intVal
# invalid: would change the active object branch:
a.kind = nkFloat
a.floatVal = 2.0
echo a.floatVal
```
But this code compiles and executes fine.

**Comment by bluenote10** [comment]
I think this is currently expected behavior. The `invalid` in the manual refers to "invalid at runtime", i.e., you would get an exception. However, this is also the number one reason why I avoid using object variant. I have opened an RFC to discuss if making them typesafe would be an option:  #6921

**Comment by konqoro** [comment]
Guys, the linked code in the manual does throw a run-time error. So this is a bug and the Language Design and Documentation tags are misleading.

**Comment by Yardanico** [comment]
@konqoro there's no documentation tag on it

**Comment by twetzel59** [comment]
On latest git, I can confirm that this is happening with the following code:
```nim
type
  NodeKind = enum
    nkInt, nkFloat
  
  Node = object
    case kind: NodeKind
    of nkInt: intVal: int
    of nkFloat: floatVal: float

var a: Node = Node(kind: nkInt, intVal: 2)

a.kind = nkFloat

case a.kind:
of nkInt:
  echo a.intVal
of nkFloat:
  echo a.floatVal
else:
  discard
```

It seems to output the 2 interpreted as a float:
```
> nim c -r main
9.881312916824931e-324
```

**Comment by twetzel59** [comment]
I just noticed something that might be important. The code in the manual does indeed raise an exception (as it should). But clearly this is not consistent, as shown by the sample at the beginning of this issue.

With some tinkering, I found that the exception is properly raised when there are multiple compatible variants.

The following code raises an exception, as it should:
```nim
type
  NodeKind = enum
    nkInt, nkTest, nkFloat
  
  Node = object
    case kind: NodeKind
    of nkInt, nkTest: intVal: int
    of nkFloat: floatVal: float

var a: Node = Node(kind: nkTest, intVal: 2)

a.kind = nkFloat
```

**Comment by ghost** [comment]
I believe that the issue can be closed now:
```
2
/home/dian/Stuff/nima/ttas.nim(14) ttas
/home/dian/Stuff/nima/lib/system/assign.nim(243) FieldDiscriminantCheck
/home/dian/Stuff/nima/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: assignment to discriminant changes object branch; compile with -d:nimOldCaseObjects for a transition period [FieldError]
```

**Comment by Araq** [comment]
Indeed, got fixed for version 1.
