### ISSUE TITLE
Inconsistent outOfMemHook behavior

### ISSUE THREAD

**Issue by erhlee-bird** [nim-lang/Nim#6920]
```
import system, tables

var outOfMem: ref OutOfMemError
outOfMem.new()
outOfMem.msg = "No memory left."

proc memError() {.gcsafe, locks: 0.} = raise outOfMem
system.outOfMemHook = memError

type TableObj = object
  table: Table[int, int]

while true:
  try:
    var t = cast[ptr TableObj](alloc0(sizeof(TableObj)))
    t.table = initTable[int, int]()  # Comment this line out!
  except:
    echo("Error!")
    quit(18)
```

`$ nim c --gc:stack test.nim && (ulimit -v 20000; ./test; echo $?)`

Running the code as is results in a segfault and a lost exception.
If you comment out the line invoking initTable, the code works as expected and enters the exception handling block.

I tried using ptr instead of ref for the pre-allocated Exception, but I get an `Error: only a 'ref object' can be raised`

**Comment by Araq** [comment]
So disable memory overcommitment. Nim cannot fix your broken OS.
