### ISSUE TITLE
Compiler crash when one function argument is dependant on another

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6927]
```nim
proc myProc(a = 2, b = a): int = b
discard myProc()
```
> error: 'a' undeclared (first use in this function)
>   T1_ = myProc_SXE2aaubEsthxye2ECOMKw(((NI) 2), a);

**Comment by twetzel59** [comment]
This has been brought up again on the forum: https://forum.nim-lang.org/t/3562

**Comment by genotrance** [comment]
This no longer crashes on #head - please verify and close.

**Comment by andreaferretti** [comment]
Confirmed

**Comment by skilchen** [comment]
It produces a runtime error on the js backend. 

If you try to call `myProc` from another procedure:
```nim
proc myProc(a = 2, b = a): int = b

proc test() =   
  echo myProc()
  
when isMainModule:  
  echo myProc()
  test()
```
the compiler produces:
```
Error: internal error: environment misses: a
```
which seems reasonable to me (except that this still compiles on the js backend and produces a runtime error). 

The question is, if Nim really wants to support this. If yes, my example should compile and run on all backends and produce the output:
```
2
2
```
But then comes the next lover of oddities wanting to to things like:
```nim
var x = 2
proc myProc(a: var int = x, b: var int = a): int = 
  inc(a)
  b

when isMainModule:  
  var y = 1
  echo myProc()
  echo myProc(b = y)
  echo x
```
which unfortunately works on the c backend but nowhere else...
IMHO Nim should refuse to compile all of this with the message that `a` is not defined.

**Comment by zah** [comment]
This should be just fixed for the JS target as well.
