### ISSUE TITLE
[RFC] Keep global random procs

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#6934]
The recent additions to `random.nim` are great (196977f623c3e3384e943c08cb85e6e0ded31109), however the procs being deprecated would still be useful in lots of cases when you don't want to bother maintaining own random generator but rather use the default one.
Thus I suggest keeping those as shortcuts. `proc random(a: int): int = random(sharedRandom, a)`. Also why change the names to `rand`?

**Comment by Araq** [comment]
The ``random`` family or procs treats the upper bound as exclusive, this is not consistent with the rest of Nim and makes ``0..high(int)``  impossible to represent. The ``rand`` procs do have inclusive upper bounds and already have an overload without the explicit state that uses the shared global state implicitly! :-)

**Comment by yglukhov** [comment]
My bad, haven't noticed the new shortcuts.

**Comment by dom96** [comment]
For reference, here is the original issue https://github.com/nim-lang/Nim/issues/4726
