### ISSUE TITLE
os.findExe() shouldn't look in current directory on posix, unless exe has a /

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6939]
On posix, the current directory isn't implicitly added to PATH, and it is generally considered a bad idea to include it explicitly. The rule is that commands without a slash only consider the PATH, and commands with a / are evaluated relative to pwd without looking through PATH.

That said, it may be nice to have a way to opt-in to the current behavior since it is extremely useful in a few cases, such as test suites.

**Comment by Araq** [comment]
The first thing I do on a Posix system is to add '.' to my PATH. Security does not exist anyway, nothing protects my home dir properly which holds all the sensitive data.

**Comment by zielmicha** [comment]
This isn't true that this isn't security issue - if you are on a multi-user system, you might have current directory set to a directory containing untrusted executable files (e.g. home of other user).

**Comment by zielmicha** [comment]
Or even Dropbox shared folder. Also, my PR #6364 fixes that.

**Comment by Araq** [comment]
Yes, I know you can and should use multiple users. It seems currently the best way to get some protection but if I do that, I still can have the dot in my PATH, it's orthogonal.
