### ISSUE TITLE
formatFloat with precision=0 should not produce a decimal separator

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#6940]
```nim
echo formatFloat(1.5, ffDecimal, precision=0)
echo formatFloat(1.5e10, ffScientific, precision=0)
```
on the c/cpp backend currently produces:
```
2.
2.e+10
```
imho it should produce:
```
2
2e+10
```
instead, as it already does on the js backend.

The easiest fix would be to replace the ```frmtstr[1] = '#'``` on line 1968 in strutils.nim with ```frmtstr[1] = '0'```

**Comment by Araq** [comment]
IMO formatFloat should never produce a number that is not looking like a float and it should produce ``2.0`` to convey the inherit danger of rounding problems.
