### ISSUE TITLE
Printing a recursive type crashes the compiler

### ISSUE THREAD

**Issue by Arnaz87** [nim-lang/Nim#6943]
This code crashes the compiler and doesn't give any error message. If the last line is commented compiles fine.

~~~ nim
type
  Node = object of RootObj
    children: seq[Node]

let tree = Node(children: @[])
echo tree # Commenting this line compiles just fine
~~~

Compiler output
~~~
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: tmp [Processing]
Traceback from system (most recent call last)
~~~

`nim -v`
~~~
Nim Compiler Version 0.17.2 (2017-09-11) [Linux: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
~~~

**Comment by mratsim** [comment]
Works for me on devel

**Comment by mratsim** [comment]
Edit: it doesn't crash but actually the rest of the code is not executed, strange (tested by adding an `echo` at the end)

**Comment by nc-x** [comment]
> Works for me on devel
@mratsim Are you sure?
Because for me, on the latest devel, `nim c t.nim` just crashes and using `koch temp` I get -
```

**Comment by andreaferretti** [comment]
I get the same result as @mratsim on OSX (no crash, no echo)

**Comment by neelesh-c** [comment]
nim --version
```
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-06-12
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: aaceec074456dcbbd6409faf07146a584b7439eb
active boot switches: -d:release
```

It crashes the compiler with a segfault.

**Comment by dom96** [comment]
This is terminating the compiler with no error message.

**Comment by jangko** [comment]
looks like a related to #6220, compiler crash because of recursive type.
a duplicate?

**Comment by Arnaz87** [comment]
Probably deeply they are the same issue, but on the surface it doesn't seem like it, it's not the same type of recursion. And this issue seems more useful because of the minimal code to reproduce.

**Comment by Araq** [comment]
This now works.
