### ISSUE TITLE
Using a variable of type `int | float` causes internal compiler error

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6946]
```nim
type Num = int | float

proc double(n: Num): auto = n + n

# Both of these are fine
echo double 1
echo double 1.0

var n: Num
if true:
  n = 1
else:
  n = 1.0

discard double n
```

**Comment by Yardanico** [comment]
@RedBeard0531 the issue here is that you're trying to call "double" proc based on runtime type of "n", which doesn't exist.
I mean that "double" proc is instantiated for all types at compile-time (you can see it in C code compiled by Nim)

**Comment by RedBeard0531** [comment]
Oh, I'm not saying I expect this to work (although that would be cool). I just think it should generate a real error rather than crashing the compiler.
