### ISSUE TITLE
Internal compiler error when using keywords arguments

### ISSUE THREAD

**Issue by Ralf12358** [nim-lang/Nim#6948]
The following code:

```
type
  A* = object
    a*:  int
    b*:  int

var a = A(a: 0, 0)
```

... causes an ... 

> Error: internal error: (filename: semobjconstr.nim, line: 47)

Nim Compiler Version 0.17.0 (2017-05-18) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
active boot switches: -d:release

**Comment by nc-x** [comment]
```
Nim Compiler Version 0.17.3 [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: cf9bee1702e41438ad3c55f33f64d179422df807
active boot switches: -d:release
```
gives proper error message-
```
b.nim(6, 17) Error: incorrect object construction syntax
```

**Comment by Yardanico** [comment]
It was fixed and reported before - https://github.com/nim-lang/Nim/issues/5965
Closing
