### ISSUE TITLE
asyncnet missing udp functionality

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6956]
At the very least it is missing sendTo and recvFrom.

**Comment by cheatfate** [comment]
`asyncdispatch` has both.

**Comment by FedericoCeratto** [comment]
To offer a consistent interface, asyncnet should support TCP, UDP, ICMP, raw IP and hooks to implement other protocols.

**Comment by dom96** [comment]
I'm marking this as easy because this should just be a case of creating wrappers for the functions implemented in ``asyncdispatch``
