### ISSUE TITLE
Securehash is not parsimonious with MD5 and other hash modules

### ISSUE THREAD

**Issue by Skrylar** [nim-lang/Nim#6961]
Securehash was removed from the standard library briefly (and then returned.) I propose the code there should be moved to a module named SHA1. The rationale is:

- Only SHA-1 is implemented in the code there.
- MD5 is in a module named "md5" and not "messagedigest." Parsimony suggests that algorithms are either in a module named after their specific implementation (as md5 is) or by family name (as sha is).

Backwards compatibility can be added by replacing the existing securehash with a module that imports the new sha1 module and re-exports it. A compile-time deprecation warning can be put in to warn users of the move.

ALTERNATIVELY

The move and export/import as before, without deprecation. In this alternate a "messagedigest" module would also be added which import/exported md5 as well. I can see an argument for being able to simply import a family (ex. import whirlpool or fnv) or a specific implementation as-needed. "Some" security APIs (Open/Libre SSL?) have generic interfaces for crunching hashes yet retain the option to use a specific one (NaCl and Sodium come to mind.)

IN CLOSING

I know that SHA is technically called "secure hash," but that implies to a casual reader that it is indeed secure. SHA1 is not secure, though it remains _useful_. If later versions (2, 3, 256-bit etc) were also in the module it might make more sense, but they are not.

**Comment by yglukhov** [comment]
I would vote for a generic digest standard lib, that implements common algos (md5, sha*, etc) as well as provides a uniform interface to extend it. Some projects might become useful in this enterprise:
- https://github.com/apense/shimsham
- https://github.com/jangko/nimSHA2
- https://github.com/onionhammer/sha1
- https://bitbucket.org/mihailp/sha3/
- https://bitbucket.org/mihailp/blake2/src

**Comment by dom96** [comment]
I vote for s/securehash/sha1/. The API it exposes should match md5's.
