### ISSUE TITLE
Implement constant member variables of objects

### ISSUE THREAD

**Issue by 9898287** [nim-lang/Nim#6964]
Currently, there is no way of having a constant member of an object, such as
```
type
    AnimalObj = object
        name: const string
        age: int
```

Now, if you have allocated an AnimalObj with new(), even if you use `let`, the members can be changed.  This is because the reference of the object does not change even if you change its referred members.

```
type
    AnimalObj = object
        name: const string
        age: int

let myDog = new(AnimalObj) 
myDog.name = "Scout"
myDog.name = "Ranger"    # valid!
```

Implementing this would 
1. Give compilers a chance to optimize code in the long run
2. Enforce const-correctness

**Comment by Araq** [comment]
That's not how ``const`` works at all, ``const`` is not a type modifier.

**Comment by 9898287** [comment]
@Araq  
You misunderstand this, that snippet was to convey the idea of implementing a mutability modifier in the type declaration. That code does/should not compile, obviously.

**Comment by Araq** [comment]
Yeah, we don't want mutability to be a property of the involved types, that never works well. Look into my wite tracking pass if you care about mutability.
