### ISSUE TITLE
system cleanup

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6967]
This was originally mentioned by @krux02 in https://github.com/nim-lang/Nim/issues/5827#issuecomment-340551052.

> Thinks that I think that are not necessary in the sysetm module are rather these things:
> ```
> cint, cstring, ...
> stmt, expr, ...  (deprecated)
> PFrame, TFrame  (debuger api, should be debugger package)
> on, off, ...  (just there to allow inconsistent boolen names)
> internalNew
> ze, ze64, ...,  (Nim has now proper unsigned integers, you never need this)
> +%, *%, ... (Nim has proper unsigned integers, you never need this)
> ```

I agree with most of these. In particular the unsigned integer procs and the boolean name aliases. Others might be more tough to move/remove as they are used by many people and are part of my book (this is true in particular for the FFI types which I would love to move to an ffi module).

**Comment by cheatfate** [comment]
`cint` is very nice thing, just because `int` has different behavior from `cint`.
About `proper unsigned integers` this is great delusion... There many issues in tracker and many of them are alive just because nim has very poor support of unsigned integers.
`PFrame` needed to generate exceptions, i dont think `debugger` is appropriate package for exceptions...

**Comment by Araq** [comment]
Not gonna happen for version 1.

**Comment by mratsim** [comment]
The `+%` is not used `uint` but on `ByteAddress` and `int` as far as I know, in particular [Jehan post on pointer arithmetics](https://forum.nim-lang.org/t/1188#7366) is often referred to and uses `+%` and `-%` to compute pointer offsets.

`cint` and `cstring`, I use them but can do without or move it to a compat library. My main grip with those is that they are not highlighted like int and float are by nimsuggest/VS code.

Never used the rest.

**Comment by dom96** [comment]
IMO the fact that cstring, cint, etc are in system makes it far too easy to mix "wrapper code" and high-level Nim code. I'd love to see those moved to an ``ffi`` module, but I think that ship has sailed.

I don't particularly care about the rest. Removing ``on`` and ``off`` seems like a useless alias to me, but it's not that important.

Anyway, I shall close this unless anyone wants to chime in with a strong message of support for the removal of these.

**Comment by Araq** [comment]
I know how to clean up ``system.nim`` but we lack any sensible deprecation path ("system.cint is deprecated, import ffi.cint instead" -- ugh).
