### ISSUE TITLE
Internal error reported when var is defined as enum

### ISSUE THREAD

**Issue by georgiy-pruss** [nim-lang/Nim#6969]
Maybe it's related to other bugs but I didn't find such internal error with enums.

$ cat eerror.nim

var state: enum A,B,C,D,E,F

$ nim c eerror    
Error: internal error: getTypeDescAux(tyBuiltInTypeClass)    
No stack traceback available    
To create a stacktrace, rerun compilation with ./koch temp c <file>

Of course, with separate type definition it's ok:

type State = enum A,B,C,D,E,F
var state: State

$ nim --version
Nim Compiler Version 0.17.2 (2017-09-07) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

**Comment by jangko** [comment]
this also produce ICE

```Nim
var a: object a: int
# or
var b: ref object a: int
# or
var c: ptr object a: int
```

**Comment by genotrance** [comment]
None of these examples crash anymore.

**Comment by andreaferretti** [comment]
Confirmed
