### ISSUE TITLE
asyncjs assign async proc doesnt work

### ISSUE THREAD

**Issue by Dankr4d** [nim-lang/Nim#6971]
The following code doesnt work with asyncjs:
```
import asyncjs

var foo = proc(): Future[void] {.gcsafe, closure, async.} =
  echo "baa"

waitFor foo()
```
Stacktrace:

> stack trace: (most recent call last)                                                                                                                                                                                    
> lib/js/asyncjs.nim(137)  async                                                                                                                                                                                          
> lib/js/asyncjs.nim(92)   generateJsasync                                                                                                                                                                                
> lib/system.nim(3756)     failedAssertImpl                                                                                                                                                                               
> lib/system.nim(3748)     raiseAssert                                                                                                                                                                                    
> lib/system.nim(2811)     sysFatal                                                                                                                                                                                       
> asyncjsassignbug.nim(3, 32) template/generic instantiation from here                                                                                                                                                    
> lib/system.nim(2811, 7) Error: unhandled exception: kind(arg) == nnkProcDef

**Comment by Yardanico** [comment]
СС @alehander42
