### ISSUE TITLE
Corrupted stack traces

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#6975]
`nim --version` 
```
Nim Compiler Version 0.17.3 [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: e0e1241a54b8ad03ac45cdd56b845370a7e050f3
active boot switches: -d:release
```
-------------
Code (saved as `bug2.nim`) - 
```
type
    A = ref object of RootObj
    R = ref object of Exception

proc add(): A =
    raise R()

proc p*(): seq[A] =
    result = @[]
    while true:
        try:
            result.add(add())
        except R:
            discard

discard p()
```
1) `nim c --run bug2.nim` and then `CTRL+C` **sometimes** shows `bug2 has stopped working` , at other times gives -
```
SIGINT: Interrupted by Ctrl-C.
Traceback (most recent call last)
bug2.nim(16)             bug2
bug2.nim(12)             p
R:ObjectType(39772872)   �I���H�E�H��`]�UH��H��►H�M►H�U↑H�E►H�E��H��►]�UH��H��0H�M►H�U↑H�E►H�E�H�E�
SIGINT: Interrupted by Ctrl-C.
```
2) `koch temp c bug2.nim` and then running `bug2.exe` from cmd and then `CTRL+C` **sometimes** gives -
```
Traceback (most recent call last)
bug2.nim(16)             bug2
bug2.nim(12)             p
bug2.nim(6)              add
rawAlloc(196608)         gc.nim
HïE°Hâ──`]├UHëσσHâ∞∞PHëM►Hì♣ôm☻(7076416) incRef
gc.nim(4457088)          HïE°Hâ──`]├UHëσσHâ∞∞`Hì♣∟n☻
SIGINT: Interrupted by Ctrl-C.
```
---------------
Note:
This is a random corruption. Some times the stack traces are proper.

**Comment by Yardanico** [comment]
Oh, this may be compiler/OS dependent, because I can't reproduce it on macOS with clang

**Comment by nc-x** [comment]
Not sure about it being OS specific, but it did take me about 40-50 tries to reproduce the issue myself on Windows.

**Comment by nc-x** [comment]
And this issue occurs only with the default/mark&sweep gc.
Because for all other gc's there is no stack trace, the application just crashes with ` application_name has stopped working`

**Comment by ringabout** [comment]
I can't reproduce it in windows with Nim v 1.5

**Comment by ringabout** [comment]
Feel free to reopen if someone could reproduce this issue.

```
nim -v           
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-01-10
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

gcc

```
Thread model: posix
gcc version 8.1.0 (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project)
```
