### ISSUE TITLE
Change the behaviour of `toCountTable` proc

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/Nim#6976]
Currently, `toCountTable` creates a `CountTable` with value `1` for each key. My point is that this is useless in the most common use case for `CountTable`, i.e. counting occurrences of elements in an open array.

The typical counting routine is as  follows:
```nim
let mySeq = @[1, 2, 1, 3, 1, 4]
var myCounter = initCountTable[int]()

for item in mySeq:
  myCounter.inc item
```
As you can see, `toCountTable` isn't used here.

If we did use it, we'd get the wrong result:
```nim
let mySeq = @[1, 2, 1, 3, 1, 4]
var myCounter = mySeq.toCountTable()

for item in mySeq:
  myCounter.inc item
```
All values will be higher than they should by 1. In this context, if any value can be chosen as a default for `toCountTable`, it should be `0` not to break the actual counting.

However, I suggest `toCountTable` to actually count elements instead of filling the values with placeholders. The change will be submitted in a PR.

**Comment by Araq** [comment]
Ok, go for it, seems wise.

**Comment by moigagoo** [comment]
https://github.com/nim-lang/Nim/pull/6977
