### ISSUE TITLE
Type inference for 'if' statements changed

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#6980]
This code used to compile but doesn't anymore:

```nim
proc foo: bool {.discardable.} =
  true

if true:
  foo()
else:
  raise newException(ValueError, "argh")
```

**Comment by LemonBoy** [comment]
I think that a cleaner fix would be to make `nkRaiseStmt` as implicitly discardable, I've tested this locally and it allows this snippet to compile.
