### ISSUE TITLE
Strange behaviour of 0.17.3 (working ok in 0.17.2)

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#6989]
When running [this script](https://gist.github.com/anonymous/8d179d004d1219e2483a0a9f62984f7c) with [this input file](https://gist.githubusercontent.com/anonymous/e20c2178fc1cc1bd8a404b3d46b692d3/raw/57f7b09828921c100aa86f0d2d181d6ca0287cde/playground.nim), in stable 0.17.2 version I get the (correct) answer:

```
kgdchlfniambejop
fjpmholcibdgeakn
```

in about 0.15 seconds.

---

Compiling the same thing in devel 0.17.3 version gives a lot of random characters (this is just a few first lines):

```
ffppjppffpocccapohbbpaapphaabgabjalclaplaappdapadlpadaaaalaaaalaaladalabadaladadaffikpadaapklaaaapaakkpkamaaaaaaaaaaaaaaaaeaaaabnaaaaaaaaaaaaaaaaaaaaapkjdeaaaealaaaaaapaaaeaaaaaaachhhhhhhhhhhhhhhhhhkhhajhhhhfhhhhhhahhhhhahhaheehhfhhahhhhdhhbahdhdhhadhhahhhjhlhhhhadgahhhhfhhhdhhhdhhhhhhdfehadhhdhddekdgcchdppdolboadagddaadhahdhahaddddddgddhdcdddcadedapdddadadddagdahahddhhdddhahddanhebbcbebdeeeppehehefhhhhfhdphplhampfpphpfppophokfoofogfgpgooopagfhfofoppfofbofpfopoldfofffeddogpdpdpdkpdkfpedpopdneknknnndnopnoooonononoodoooknkkkohooooooooookooooooooooooojooopoaoooocooooodoepofolooobebooobobdoboboookooobbbbooooobobbobnobebbbobobhbolakopobbhboonoooobbobookoboboboobdodbdbdadododoooddooaoeobooooaododgdodooondoododoodooooobooookoojoogooojojgbogoooofooooofoaogaoogooggggeldkkjkbkkfbdbc
```

and after a minute I had to manually stop it.

**Comment by Araq** [comment]
OS, CPU and C compiler?

**Comment by narimiran** [comment]
> OS, CPU and C compiler?

OS: Manjaro Linux  
CPU: Intel i7-970  
C compiler: gcc (GCC) 7.2.1 20171128

Both 0.17.2 and 0.17.3 were installed via `choosenim`.

**Comment by Yardanico** [comment]
Same random output on Arch Linux with Clang 5.0.1
Intel i5 4460

**Comment by Araq** [comment]
It works with this line

```nim

      result = result[result.len - rot .. result.high] & result[0 ..< result.len - rot]
```

Investigations continue...

**Comment by skilchen** [comment]
It also works with this insertion before proc dance
```nim
when compiles(BackwardsIndex(1)):
  proc pred*(x: BackwardsIndex, y = 1): BackwardsIndex =
    BackwardsIndex(x.int + y)
  template `..<`*(a, b: untyped): untyped =
    ## a shortcut for 'a..pred(b)'.
    a .. pred(b)
```
somehow in the template `..<`  in system.nim the call `pred(b)` erases the property (type) of b being a BackwardsIndex.

**Comment by dom96** [comment]
This seems possibly related: https://github.com/nim-lang/Nim/issues/6992

**Comment by narimiran** [comment]
Any news on this one?

**Comment by skilchen** [comment]
I now think that there is no misterious type erasure problem at work here. During the introduction of `BackwardsIndex`it was simply overlooked that the logic for `pred` and `succ` has to be reverted for backwards indices. Currently there is only one generic implementation of `pred` and `succ` for any ordinal type. 
Maybe it would be enough to add overloads for BackwardsIndex like so:
```nim
proc succ*(x: BackwardsIndex, y = 1): T {.magic: "Pred", noSideEffect.}
proc pred*(x: BackwardsIndex, y = 1): T {.magic: "Succ", noSideEffect.}
```
I didn't investigate if there are other places, where backwards indices should be handled separately.
