### ISSUE TITLE
newString(len) has off-by-one error

### ISSUE THREAD

**Issue by luked99** [nim-lang/Nim#6991]
I think newString() might have an off-by-one error.

```
var s = newString(0)
s[0] = 'a'   # this works fine!
s[1] = 'b'   # this fails as you might expect
```

And so-on for larger values. I'm not sure to what extent this is a bug, or by design.

**Comment by Yardanico** [comment]
@luked99 Strings in Nim are null-terminated

**Comment by Araq** [comment]
It's by design but there is already an RFC to change that. Closing.

**Comment by yglukhov** [comment]
#5596
