### ISSUE TITLE
Feature request: pragma for commutative procs

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#6994]
A somewhat common scenario is to implement operators where the operands are of different types. Sometimes, these operators should be commutative, i.e. the order of the operands shouldn't matter. To make this work in Nim, the proc must be overloaded with the arguments switched. I propose that a simple macro for adding the overload automatically should be introduced. A naive implementation would look something like this (bad since it copies the entire proc, but you get the idea):

```nim
import macros

macro commutative*(arg: untyped): untyped =
  doAssert arg[3].len == 3
  let overload = copyNimTree(arg)
  (overload[3][1], overload[3][2]) = (overload[3][2], overload[3][1])
  result = newStmtList(arg, overload)

proc `+`(a: int, b: bool): int {.commutative.}=
  a + b.ord

echo 1 + true
echo true + 1
```

An additional advantage of such a pragma is that the doc comment doesn't need to be duplicated and synced manually.

**Comment by andreaferretti** [comment]
Or just use a template

**Comment by Araq** [comment]
Feel free to create a PR and to add that to `sugar.nim` or similar but we won't work on this.
