### ISSUE TITLE
Sequtils map fails with inline proc

### ISSUE THREAD

**Issue by Adrien79** [nim-lang/Nim#7015]
This compiles:
```nim
import sequtils
proc pos*(x: int): int = x + 2
var
  test = @[1, 3, 5, 7]
  res = map(test, pos)
```
but the same snippet fails with inline pragma:
```nim
import sequtils
proc pos*(x: int): int {.inline.} = x + 2
var
  test = @[1, 3, 5, 7]
  res = map(test, pos)
```

**Comment by Araq** [comment]
The compiler is correct ``map`` takes .closure procs. These are not compatible with ``.inline`` procs.

**Comment by Adrien79** [comment]
Maybe this should be documented in `sequtils`. Currently this is not mentioned at all, and it is a bad surprise when inlining a proc is breaking the program.
