### ISSUE TITLE
runnableExamples doesn't work in templates

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#7018]
```nim
template run*(body: untyped) =
  ## runs body

  runnableExamples:
    DOES_NOT_COMPILE
    doAssert false

  body

run: discard
```

**Comment by Yardanico** [comment]
@RedBeard0531 - as mentioned in IRC by @Araq, currently template needs to be instantiated somewhere to make runnableExamples work

**Comment by RedBeard0531** [comment]
@Yardanico  see the last line :)

**Comment by GULPF** [comment]
This also prevents runnableExamples from working with generics:

```nim
proc foo*[T]()  =
    runnableExamples:
        doAssert false
    discard

foo[int]()
```

**Comment by RedBeard0531** [comment]
Until this is resolved is it possible for the compiler to reject `runableExamples` in places where they don't work? It seems dangerous to add a new testing framework that will silently not run any tests, since it gives a false sense of security. Hopefully, compiler `{.magic.}` is magical enough to do this.

**Comment by Araq** [comment]
Detecting this is as much work as fixing it.
