### ISSUE TITLE
`when` is not allowed in type definition

### ISSUE THREAD

**Issue by Dankr4d** [nim-lang/Nim#7025]
`when`  is not allowed in type definition.
But this would be helpful when the types are closely interwoven.
```nim
type
  when defined(js):
    Foo* = proc () 
  else:
    Foo* = proc (): Future[void] 
```

fails with 
`foo.nim(4, 3) Error: identifier expected, but found 'keyword when' `

**Comment by Yardanico** [comment]
But Future[void] and void types are very different, you can't call await on the second one

**Comment by cheatfate** [comment]
@Dankr4d 
```nim
when defined(js):
  type
    Foo* = proc ()
else:
  type
    Foo* = proc (): Future[void]
```

**Comment by cheatfate** [comment]
And this is not an issue, its just language syntax...

**Comment by enthus1ast** [comment]
@cheatfate the problem is when the types are depending on each other and cannot live in a second type block. In most cases your solution is usable but in some not.

**Comment by enthus1ast** [comment]
consider this case (on line 27): https://gist.github.com/enthus1ast/b934b3a15ca73975e68622771a22c3b5
The events are depending on MsgIoClient
MsgIoClient depends on the events and ClientTransportBase. 
So they all have to be in the same type block.

**Comment by yglukhov** [comment]
@enthus1ast, as a workaround:
```nim
when defined(js):
  type CallbackResult = void
else:
  type CallbackResult = Future[void]
```
;)

As a side note, `Future` is available for js in `asyncjs`.

**Comment by enthus1ast** [comment]
@yglukhov this indeed works with simple types. But please take a look at my comment above.
This type definition does not let us split the types to multiple `type` blocks. So your solution is not working on this case (correct me if I'm wrong please :) )

**Comment by cheatfate** [comment]
@enthus1ast, maybe i dont understand properly, but what the reason for "all types must be under same type block"?

**Comment by enthus1ast** [comment]
if they not share the same type block, 
the order of occurrence gets important:
```nim
type
  # This works
  Foo3* = object
    f1*: Foo1
    f2*: Foo2
  Foo1* = distinct int
  Foo2* = distinct int
```

```nim
type
  # This fails with: Error: undeclared identifier: 'Foo1'
  Foo3* = object
    f1*: Foo1
    f2*: Foo2    
type Foo1* = distinct int
type Foo2* = distinct int
```
This often is not a problem but when `when`  is not allowed in a type block a construct like this would be
harder:
```nim
# Does not compile
type 
  Foo2* = distinct int
type 
  Foo1* = ref object
    f3*: Foo3
type
  Foo3* = ref object
    f1*: Foo1
    f2*: Foo2    


# Does compile
type
  Foo3* = ref object
    f1*: Foo1
    f2*: Foo2    
  Foo1* = ref object
    f3*: Foo3
  Foo2* = distinct int


# But this is not possible:
type
  Foo3* = ref object
    f1*: Foo1
    f2*: Foo2    
  when true:
    Foo1* = ref object
      f3*: Foo3
  else:
    Foo1* = ref object
      f3*: int 
  Foo2* = distinct int
```


@yglukhov comments seems to be the solution for our particular problem btw. Thank you!

**Comment by cheatfate** [comment]
@enthus1ast please explain me what the principal difference between my first comment example and yglukhov's one?

**Comment by enthus1ast** [comment]
@cheatfate we can get around our circular dependency when we define a type for this return. (im talking about the code from the gist)
You are absolutely right for @Dankr4d code example!

**Comment by Araq** [comment]
Then the next person will say "omg, 'when' works in 'type' but not the same way in 'var', 'let' and 'const' sections" so we have to add it for all of these. Then ever y macro needs to be aware of more alternative spellings in var/let/const sections. Best way to create bloat. If we want to merge 'type' sections to gain more flexibility, lets merge 'type' sections in the semantic pass instead.

**Comment by awr1** [comment]
`when` can work as an type expression. Some parentheses are required for proc typedefs, however, so the parser doesn't get confused:

```nim
import asyncdispatch

type
  Foo* = (when defined(js):
            (proc ())
          else:
            (proc (): Future[void]))
```
