### ISSUE TITLE
[RFC] new runtime based on destructors

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#7041]
Since many people are interested in this, here is a short to do list.

- [x]  edit the 'destroyer' pass to adhere to the rules as outlined in the "spec" at https://github.com/nim-lang/Nim/wiki/Destructors and ensure copies, moves and destructors are introduced in all the right places

- [x] implement the rule "sink parameters are consumed exactly once" in compiler/sempass2
- [x] implement 'lent' pointers. Check the implementation of ``tyVar`` for an example. Most of the required additions have been done already.
- [x] implement the borrow checking that ensures 'lent' and 'var' do not outlive the scope they originate from
- [x] ensure that --newruntime uses an alternative cleaned up system.nim that uses ``core/seqs.nim``, ``core/strs.nim`` etc.
- [x] the C backend needs to know about --newruntime and produce different code for string, seqs and refs. Since these additions introduce many more ``try`` statements, it's wise to base this work on the C++ codegen, not the pure C codegen. Otherwise it seems unrealistic to get competitive performance.
- [x] update the stdlib containers to use 'sink' and 'lent' annotations 
- [x] port programs to use --newruntime

**Comment by narimiran** [comment]
[Newruntime: Todo](https://github.com/nim-lang/Nim/issues/11217)

**Comment by Araq** [comment]
Succeeded by https://github.com/nim-lang/Nim/issues/11217
