### ISSUE TITLE
Signal handler safety

### ISSUE THREAD

**Issue by manuelmessner** [nim-lang/Nim#7042]
There was a [disussion on IRC](https://irclogs.nim-lang.org/08-01-2018.html#17:15:41) about the safety of signal handlers:

In C only certain functions are safe to be called from inside a signal handler.
These functions can be viewed at  [`man 7 signal-safety`](http://man7.org/linux/man-pages/man7/signal-safety.7.html).

Can the nim compiler ensure signal safety in a way?
The suggested solutions on IRC were:

1. Using the effect system
1. Using `gcsafe`

Can something like this be implemented?

**Comment by sargun** [comment]
Has any progress been made here?

**Comment by Araq** [comment]
There is ``-d:noSignalHandler`` and then Nim doesn't mess with them and you're free to do what you need to do.

**Comment by Araq** [comment]
Since signal handlers are so restricted to what is allowed inside them, manual code reviews suffice. If in doubt, it is not supported in a signal handler.
