### ISSUE TITLE
Invalid generated code for recursive nested procs

### ISSUE THREAD

**Issue by d3zd3z** [nim-lang/Nim#705]
The code below causes invalid code generation with the Nimrod compiler as of 166f6ea4bf190ad81845d8abeed50af1f6bfade6.
It seems to require both the mutual recursion and the capture to provoke the problem.

```nimrod
proc cached(limit: int): (proc (n: int): int) =
  var cache = newSeq[int](limit)
  proc getLen2(n: int): int
  proc getLen(n: int): int =
    if n < limit:
      if cache[n] == 0:
        let tmp = getLen2(n)
        cache[n] = tmp
        result = tmp
      else:
        result = cache[n]
    else:
      result = getLen2(n)
  proc getLen2(n: int): int =
    if n == 1:
      1
    elif n mod 2 == 0:
      1 + getLen(n div 2)
    else:
      1 + getLen(n * 3 + 1)
  getLen
echo(cached(100)(10))
```

**Comment by d3zd3z** [comment]
It appears that although the simpler example in #581 is fixed, the original example above still fails as of 6597bef8d97e2cf8b32723d0f7c8fbb0f7f48f58. I think this issue should be reopened.

**Comment by reactormonk** [comment]
Still fails with:

    /tmp/nimcache/test.c: In function ‘getlen2_89061’:
    /tmp/nimcache/test.c:394:43: error: ‘HEX3Aenv_89088’ undeclared (first use in this function)
       LOC8.ClPrc = getlen_89064; LOC8.ClEnv = HEX3Aenv_89088;
                                               ^
    /tmp/nimcache/test.c:394:43: note: each undeclared identifier is reported only once for each function it appears in
    Error: execution of an external program failed

**Comment by dtomas** [comment]
Some more minimalistic examples:

This compiles:
```nim
proc foo(x = "hello") =
    proc bar() = echo(x & " world")
    proc baz() = bar()
    baz()
```
as well as this:
```nim
proc foo() =
    proc bar() = echo("hello world")
    proc baz1() = bar()
    proc baz2() = bar()
    baz1()
    baz2()
```
but this fails:
```nim
proc foo(x = "hello") =
    proc bar() = echo(x & " world")
    proc baz1() = bar()
    proc baz2() = bar()
    baz1()
    baz2()
```
Error output:
```
gcc -c  -w  -I/home/dt/src/nim-0.11.2/lib -o /home/dt/test/nimcache/testclosure.o /home/dt/test/nimcache/testclosure.c
/home/dt/test/nimcache/testclosure.c: In function ‘baz2_90012’:
/home/dt/test/nimcache/testclosure.c:365:39: error: ‘HEX3Aenv_90034’ undeclared (first use in this function)
  LOC1.ClPrc = bar_90006; LOC1.ClEnv = HEX3Aenv_90034;
                                       ^
/home/dt/test/nimcache/testclosure.c:365:39: note: each undeclared identifier is reported only once for each function it appears in
Error: execution of an external program failed
```
So the failure conditions seem to be:
- Closure bar accesses some variable in foo's scope.
- Closure bar is used in more than one closure.

**Comment by zielmicha** [comment]
Another simpler (?) example:
```
proc foobar*() =
  var foo: (proc())
  proc bar() = foo()

  foo = proc() =
    bar()

  var a = bar
```

**Comment by Araq** [comment]
Fixed by the merge for new-ll.
