### ISSUE TITLE
async macro doesn't support "except Exception as ex" syntax

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#7051]
```nim
proc foo(): Future[void] {.async.} =
  try:
    await newFuture[void]()
  except Exception as ex:
    echo ex
```

**Comment by yglukhov** [comment]
This is fixed by now

**Comment by zah** [comment]
@Yardanico, are you making sure that test cases for these issues are present in the test suite?

**Comment by zah** [comment]
Ditto for:
https://github.com/nim-lang/Nim/issues/6880
https://github.com/nim-lang/Nim/issues/7052

**Comment by Yardanico** [comment]
And should I put all these tests in one file?

**Comment by zah** [comment]
It's perfectly possible that some of these are already tested (e.g. the support for `finally` blocks). My remark was that you should try to search for coverage of the bug in the test suite before closing any issue.

Otherwise, it's usually best if you extend some existing test case with a similar thematic. 

Regarding making HTTP requests, I think there is already a precedent for this.

**Comment by yglukhov** [comment]
I doubt these issues are specifically covered now. Most of the newly revealed functionality is covered by iters tests, although indirectly. Nevertheless I think we should close these issues regardless if a test exists or not. There's no incentive to write a formal test case only to change the issue's state to "closed".

**Comment by Yardanico** [comment]
About https://github.com/nim-lang/Nim/issues/2650 - original issues was fixed 2 years ago

**Comment by Yardanico** [comment]
I've written a test-case for 4 issues (filename - tasync_tranfs.nim)
```nim
discard """
  file: "tasync_transf.nim"
  exitcode: 0
  output: '''
Handled exception
Reached finally
Success!
before await
after await
finally
'''
"""
import asyncdispatch

#6880
proc failingProc() {.async.} =
  if true:
    raise newException(Exception, "Test exception")

proc catchingProc() {.async.} =
  try:
    await failingProc()
  #7051
  except Exception as ex:
    echo "Handled exception"
  finally:
    echo "Reached finally"

proc returnString(): Future[string] {.async.} = 
  return "Hello there"

#2528
proc doStuff() {.async.} = 
  try:
    var fileContent = await returnString()
    if fileContent == "Hello there":
      let anotherString = await returnString()
    echo("Success!")
  except:
    echo("Failed")

#7052
proc foo(): Future[void] {.async.} =
  try:
    echo "before await"
    discard await returnString()
    echo "after await"
  except Exception:
    echo "Exception"
  except:
    echo "except"
  finally:
    echo "finally"

proc main() {.async.} = 
  await catchingProc()
  await doStuff()
  await foo()

waitFor(main())
```
But I don't know if we need a test-case for #7052, and #2650 was fixed 2 years ago.
