### ISSUE TITLE
No documentation for \u escape sequence

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#7068]
I stumbled across the support for "\u1234" in the lexer:  https://github.com/nim-lang/Nim/blob/3647c9c8222f2bfecf88d56403455e56084634f9/compiler/lexer.nim#L661-L670

Is is supposed to be a supported feature? If so, it should probably be documented. And it should probably support the full unicode space, not just the BMP.

**Comment by Araq** [comment]
I thought the documentation was updated too when I merged this PR...

**Comment by GULPF** [comment]
> And it should probably support the full unicode space, not just the BMP.

Agreed. @Araq Would you accept a PR to extend `\u` to support the full unicode space? JavaScript uses this syntax which I think is acceptable: `"\u{1D306}"` (this syntax could coexist with `"\uXXXX"` of course).

**Comment by Araq** [comment]
@GULPF Yes, if you also update the spec.
