### ISSUE TITLE
runnableExamples doesn't support import strformat except `%`

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#7069]
input: 
```nim
import strformat except `%`
```

output:
```nim
import strformat except %
```

**Comment by andreaferretti** [comment]
Can you expand a little?

**Comment by Araq** [comment]
I noticed. ;-)

**Comment by RedBeard0531** [comment]
@andreaferretti the output loses the backticks around %, which causes a weird parsing error. Separately, it isn't usable for this specific purpose because it automatically imports all of the current module. But I think there is a general issue with its handling of backticks.

**Comment by andreaferretti** [comment]
I see that the output loses backticks. I just do not understand the output of *what*

**Comment by Araq** [comment]
This works now.
