### ISSUE TITLE
[RFC] Reintroduce readChar

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7072]
`readChar` was deprecated in 794d36cf31d8f7debc2ede1f7792fdbcc0a1ef5e for performance reasons. I also think that noone would want to use `readChar` over an arbitrary stream. However `readChar` on `stdin` is a pretty common use case for user-interactive command line apps, and I don't see anything wrong about it. So how about reintroducing new `proc readChar(): char` that reads from stdin?

**Comment by dom96** [comment]
I agree this should be reinstated.

Some more info here: https://stackoverflow.com/questions/48186397/nim-readchar-deprecated-what-to-use-instead#comment83407398_48187759

**Comment by Araq** [comment]
Ok.

**Comment by RedBeard0531** [comment]
Should it be named `readStdinChar`? There doesn't seem to be a common pattern of `readFoo` implicitly reading from stdin in nim. Unless you also want `readLine()` to default to reading from stdin, then that would be reasonable.

**Comment by dom96** [comment]
No, the current ``readChar`` should just be de-deprecated.
