### ISSUE TITLE
"smallest" in CountTable doesn't work

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#7076]
In the following example, "c" has the expected value, but we expect "c.smallest" to be `('b', 1)` and we get `('\0', 0)` instead:

```nim
import tables

var c = initCountTable[char]()

c.inc('a')
c.inc('a')
c.inc('b')

echo c
echo c.smallest
```

**Comment by GULPF** [comment]
This is fixed on devel :)

**Comment by data-man** [comment]
Can be closed.
Fixed on devel.

**Comment by lscrd** [comment]
Fine. Thanks!
