### ISSUE TITLE
[Question] Restoring compiler as a service

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#7081]
I'm working on a Nim project that takes annoyingly long to compile (probably due to extensive use of macros and generated code), so I've became interested in compiler as a service (running compiler in a persistent process). It seems that there was support for it some time ago (as `nim serve`). I've hacked together something that mostly works (apart for generating duplicate code for some closures). 
Does it make sense to try to work on this further or will I hit some unavoidable design change?

```nim
proc checkGraph(graph: ModuleGraph, lastCompilation: float) =
  for idx, info in fileInfos:
    let fn = ($info.quotedFullName).strip(chars={'\"'})
    if fn.len == 0:
      continue
    if not existsFile(fn) or getFileInfo(fn).lastWriteTime.float > lastCompilation - 1:
      if existsFile(fn):
        echo getFileInfo(fn).lastWriteTime.float, " ", lastCompilation
      else:
        echo "not exists"
      echo "reset ", info.quotedFullName, " ", idx
      markDirty(graph, idx.int32)
      markClientsDirty(graph, idx.int32)

import posix

proc commandServe(graph: ModuleGraph; cache: IdentCache) =
  var lastCompilation: float = 0
  while true:
    echo "press enter to recompile"
    discard stdin.readLine()

    checkGraph(graph, lastCompilation)
    lastCompilation = epochTime()

    clearPasses()
    gLastCmdTime = epochTime()
    searchPaths.add(options.libpath)

    extccomp.initVars()
    semanticPasses()
    registerPass(cgenPass)

    compileProject(graph, cache)

    let pid = fork() # fork, so we don't need to restore C generator state manually every time
    if pid == 0:
      cgenWriteModules(graph.backend, graph.config)
      if gCmd != cmdRun:
        let proj = changeFileExt(gProjectFull, "")
        extccomp.callCCompiler(proj)
      quit(0)
    else:
      wait(nil)
```

**Comment by Yardanico** [comment]
Araq mentioned that he'll work on new version of symbol files, maybe they can help you?

**Comment by dom96** [comment]
nimsuggest is essentially a "compiler as a service", it might not offer the commands for compiling but adding that shouldn't be problematic.

**Comment by Araq** [comment]
> Does it make sense to try to work on this further or will I hit some unavoidable design change?

It makes sense but I don't know what it takes to make it reliable. I focus on a pure frontend cache fwiw to keep the complexity managable.

**Comment by zah** [comment]
I've worked on the previous implementation of CaaS and I don't think there are any insurmountable obstacles. Just a lot more work to make it work reliably - it affects many of the sub-systems within the compiler that use caches of various kinds that have to be cleaned up between compilations.
