### ISSUE TITLE
Error on method call syntax within a template

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#7085]
Following code doesn't work:

```nim
# Module A
proc foo(a: string): string =
  return a

template baz*(a: string): string =
  var b = a.foo()
  b
```

```nim
# Module B
import A

echo baz("hello")
# xxx template/generic instantiation from here
# xxx Error: attempting to call undeclared routine: 'foo'
```

Works replacing the method call by a regular proc call. Also works as is when using the template within module A. Also works when exporting `foo`. I can only guess the compiler tries to resolve the method call too late. The *method call limitations* section of the manual does not mention this specific case.

**Comment by jangko** [comment]
this is a well known issue, many people already encounter it when using generics. no wonder it also affected templates.
usually, mixin can solve this kind of problem.
```Nim
template baz*(a: string): string =
  mixin foo
  var b = a.foo()
  b
```
but it would be nice if the compiler can activate the mixin automatically inside template and generics without specifically typing it (like C++ template).

**Comment by nitely** [comment]
@jangko except now `foo` will be picked from caller scope if it's defined there 🤕 

```nim
# Module B
import A

proc foo(a: string): string =
  return "bye"

echo baz("hello")
# bye
```

**Comment by metagn** [comment]
Old issue, but an answer was never given, it's `bind foo` not `mixin foo`, ~~which also fixes many of these "private symbol in template" issues~~

**Comment by nitely** [comment]
@hlaaftana Using bind instead of mixin throws the same error.

**Comment by metagn** [comment]
My bad, I was talking out of my ass, it doesn't fix these issues. No one mentioned `bind` before though so it might help understand what's happening to know that it doesn't work.
