### ISSUE TITLE
CountTable smallest method returns zero-value of type

### ISSUE THREAD

**Issue by maximpertsov** [nim-lang/Nim#7088]
`proc smallest[A](t: CountTable[A]): tuple[key: A, val: int]` always returns a tuple of the zero-value of type `A` with frequency `0`.

Example:
```
>>> import tables
>>> var t = initCountTable[int]()
>>> t.inc(50)
>>> echo t.smallest()
(key: 0, val: 0)
```

**Comment by data-man** [comment]
@maximpertsov 
See https://github.com/nim-lang/Nim/issues/7076

**Comment by Yardanico** [comment]
Fixed in devel, closing :)
