### ISSUE TITLE
Memory error when checking if a variable is a string in concept

### ISSUE THREAD

**Issue by okamsn** [nim-lang/Nim#7092]
Hello, the following code compiles and then fails to run:
```nim
type stringTest = concept x
  x is string

let a: stringTest = "111"
```
It gives the error

> Traceback (most recent call last)
> string_err.nim(5)        string_err
> SIGSEGV: Illegal storage access. (Attempt to read from nil?)

When doing 

```nim
type stringTest = concept x
  x is string

let a: stringTest = "111"
let b: stringTest = "01"
```
I get the message "out of memory". This is on Ubuntu 17.10 with Nim 17.3.

I feel like this should work, but I am still learning the language, and so am not sure why it wouldn't.

**Comment by Yardanico** [comment]
@okamsn stringTest is a concept, not a concrete type. You can't create an object of a concept type.

**Comment by okamsn** [comment]
Alright, so if I was trying to make a type that has certain requirements, should I be using a concept?

I know that the following code does run and compile in the same setup.

```nim
type intTest = concept x
  x is int

let a: intTest = 1
echo a
```

Is there some automatic conversion going on here, then?

**Comment by zah** [comment]
In this context, the concept is just used to verity that the value or the right-hand side of the assignment conforms to the concept requirements. The variables will end up with the concrete type of that value (here, this is string or int). There shouldn't be a crash, so this is a genuine bug that must be investigated.

**Comment by DavidMeagher1** [comment]
this might be old, but i did find it works fine with cstrings

```nim
type cstringTest = concept x
  x is cstring

let a = cstringTest("hello".cstring)
echo a
```
