### ISSUE TITLE
Unknown IO error on Windows 10

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7111]
Seems there is a new crash caused by changes in Windows 10:

https://forum.nim-lang.org/t/3367

**Comment by dandevelo** [comment]
This seems to happen only when using  VS code. Looks like it is related to this one:

https://github.com/Microsoft/vscode/issues/36630#issuecomment-350063413

**Comment by Araq** [comment]
I get the same problems with Python scripts running in VSCode. Not a Nim bug.
