### ISSUE TITLE
`1 mod 0` gives NaN with JS backend

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#7127]
Since `mod` is mapped to the `%` JavaScript operator, `1 mod 0` gives `NaN` instead of raising an `DivByZeroError` exception.

**Comment by krux02** [comment]
does javascript have a modulo operator with integer behavior? As far as I know it's not supported in the backend.

**Comment by skilchen** [comment]
@GULPF with your PR #7118 
`1.0 mod 0.0`  also gives `nan`. 

(btw: please don't deprecate `math.fmod` in #7118.)

**Comment by GULPF** [comment]
@skilchen 
 #7118 is about `mod` for floats, this issue is about `mod` for integers. That PR spawned some discussion on IRC and it's unlikely that it will be merged because Araq wants to remove the `div` and `mod` keywords, but why do you want to keep `fmod`? With that PR `mod` would do the same thing.

@krux02 
I was about to say that Nim should still generate a guard in the codegen for debug builds, but apparently Nim doesn't generate a guard for `div` either (so `1 div 0` gives infinity). I don't know if this is by design, but if it is then this issue can be closed.

**Comment by skilchen** [comment]
IMHO to deprecate something, you need to provide good reasons. There is nothing wrong with `fmod`. 
And the available documentation for `fmod` (manual page, internet search etc.) is much more extensive than the available docs for `mod` in Nim. 

Your PR #7118 also changes the border case of `x.float mod 0.0`. Currently this returns `x`. I admit, that it is very likely that nobody cares about this breaking change.

**Comment by ringabout** [comment]
It works since Nim v1.4
