### ISSUE TITLE
type + macro parsing regression

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7128]
This was probably changed long ago, but used to work before.
```nim
import macros
macro foo(a: untyped): untyped = newIdentNode("int")
type A = foo do:
  echo "hi"
```
Error:
```
test.nim(3, 10) Error: type expected
```

It would be nice to support this syntax again, or better without the `do` keyword. A toy project that relied on this feature: https://github.com/yglukhov/persistent_enums

**Comment by Araq** [comment]
This works though:

```nim

import macros
macro foo(a: untyped): untyped = newIdentNode("int")
type A = (foo do:
  echo "hi")
```

**Comment by yglukhov** [comment]
Yes, the issue was mainly about the parsing rules. Will there be any ambiguity problem if the parser would support the following syntax?
```nim
type A = foo:
  echo "hi"
```
