### ISSUE TITLE
Copyright line needs updating

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/Nim#7129]
Latest nim devel gives this output with --version:

```
Nim Compiler Version 0.17.3 [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 73af427f23f7a235f114074625d7137837add427
active boot switches: -d:release
```

The 2017 should be changed to 2018.

**Comment by Yardanico** [comment]
No it's shouldn't

**Comment by Yardanico** [comment]
https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by cabhishek** [comment]
@wizzardx see [this](https://github.com/nim-lang/Nim/commit/faea0f9a70ee8850191a1e7ab3cc0da0e3a2cf8f#diff-3cfdfab46b76fca4a44ba7cdd5447096), [this](https://github.com/nim-lang/Nim/commit/faea0f9a70ee8850191a1e7ab3cc0da0e3a2cf8f) and [this](https://github.com/nim-lang/Nim/commit/49320add23a3df1112727f280f4bf5346221f7f9). Not sure what was the final resolution.
