### ISSUE TITLE
echo(i ^ 2)

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#7133]
Since some years I am struggling with missing power operator. ^ and ** seems still not to work. Writing i * i may be good enough, but for longer var names like (velocity * velocity) it is not that nice.

```nim
let i: int = 2

echo(i ^ 2)
```

```
t.nim(3, 8) Error: type mismatch: got (int, int literal(2))
but expected one of: 
template `^`(x: int): BackwardsIndex

expression: i ^ 2
```

**Comment by GULPF** [comment]
The power operator is part of the math module, but beware of #2897

**Comment by StefanSalewski** [comment]
Ah, interesting. I had indeed the feeling that ^ was working once for power of integers, so I may have imported math that time.

But I think ^ should be available by default without need of importing math, i ^ 2 or x ^ 2 for i int and x float is a very common operation. Or, maybe we can get a better error message for this use case?

**Comment by dom96** [comment]
The compiler should offer suggestions for operators defined in other modules.

As far as moving ``^`` to system, I think it's fine to leave it in ``math``.

**Comment by StefanSalewski** [comment]
OK, I will close this issue for now, as it is not that important for Nim V1.0
