### ISSUE TITLE
nimsuggest crash in VS Code

### ISSUE THREAD

**Issue by rrenderr** [nim-lang/Nim#7138]
Install VS Code version 1.19.2 and extension NIm version 0.5.28. Operation system - OSX High Sierra (10.13.1)
Nim tools are up to date.
After launch i have crash with next StackTrace:

console.ts:123 [Extension Host] Nimsuggest returns unknown port number: nimsuggest.nim(627)      nimsuggest
nimsuggest.nim(623)      handleCmdLine
nimsuggest.nim(503)      mainCommand
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(218)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(576)             myProcess
sem.nim(539)             semStmtAndGenerateGenerics
semstmts.nim(1914)       semStmt
semexprs.nim(793)        semExprNoType
semexprs.nim(2380)       semExpr
importer.nim(178)        evalImport
importer.nim(155)        impMod
importer.nim(141)        myImportModule
modules.nim(203)         importModule
modules.nim(180)         compileModule
passes.nim(218)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(576)             myProcess
sem.nim(539)             semStmtAndGenerateGenerics
semstmts.nim(1914)       semStmt
semexprs.nim(793)        semExprNoType
semexprs.nim(2380)       semExpr
importer.nim(176)        evalImport
importer.nim(155)        impMod
importer.nim(141)        myImportModule
modules.nim(203)         importModule
modules.nim(180)         compileModule
passes.nim(218)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(576)             myProcess
sem.nim(539)             semStmtAndGenerateGenerics
semstmts.nim(1914)       semStmt
semexprs.nim(793)        semExprNoType
semexprs.nim(2380)       semExpr
importer.nim(178)        evalImport
importer.nim(155)        impMod
importer.nim(141)        myImportModule
modules.nim(203)         importModule
modules.nim(180)         compileModule
passes.nim(218)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(576)             myProcess
sem.nim(539)             semStmtAndGenerateGenerics
semstmts.nim(1914)       semStmt
semexprs.nim(793)        semExprNoType
semexprs.nim(2372)       semExpr
semstmts.nim(1663)       semProc
semstmts.nim(1587)       semProcAux
semexprs.nim(1438)       semProcBody
semexprs.nim(2354)       semExpr
semstmts.nim(1847)       semStmtList
semexprs.nim(2274)       semExpr
semexprs.nim(700)        semIndirectOp
semexprs.nim(2260)       semExpr
semexprs.nim(776)        semDirectOp
semexprs.nim(629)        semOverloadedCallAnalyseEffects
semcall.nim(391)         semOverloadedCall
semcall.nim(215)         resolveOverloads
semcall.nim(91)          pickBestCandidate
sigmatch.nim(2262)       matches
sigmatch.nim(2218)       matchesAux
sigmatch.nim(2052)       prepareOperand
semexprs.nim(26)         semOperand
semexprs.nim(2321)       semExpr
semstmts.nim(1238)       semLambda
semexprs.nim(1438)       semProcBody
semexprs.nim(2354)       semExpr
semstmts.nim(1847)       semStmtList
semexprs.nim(2331)       semExpr
semstmts.nim(167)        semIf
semstmts.nim(101)        semExprBranch
semexprs.nim(2354)       semExpr
semstmts.nim(1847)       semStmtList
semexprs.nim(2352)       semExpr
semexprs.nim(1389)       semAsgn
semexprs.nim(44)         semExprWithType
semexprs.nim(2321)       semExpr
semstmts.nim(1238)       semLambda
semexprs.nim(1438)       semProcBody
semexprs.nim(2354)       semExpr
semstmts.nim(1847)       semStmtList
semexprs.nim(2331)       semExpr
semstmts.nim(167)        semIf
semstmts.nim(101)        semExprBranch
semexprs.nim(2354)       semExpr
semstmts.nim(1847)       semStmtList
semexprs.nim(2357)       semExpr
semstmts.nim(506)        semVarOrLet
semexprs.nim(44)         semExprWithType
semexprs.nim(2246)       semExpr
semexprs.nim(777)        semDirectOp
semexprs.nim(674)        afterCallActions
semexprs.nim(19)         semTemplateExpr
vm.nim(1676)             semAfterMacroCall
system.nim(2827)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]

**Comment by rrenderr** [comment]
After clean up and reinstall all I have next StackTrace:

  ERR Nimsuggest returns unknown port number: Traceback (most recent call last)
nimsuggest.nim(627)      nimsuggest
nimsuggest.nim(623)      handleCmdLine
nimsuggest.nim(503)      mainCommand
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(218)          processModule
passes.nim(136)          processTopLevelStmt
sem.nim(576)             myProcess
sem.nim(539)             semStmtAndGenerateGenerics
semstmts.nim(1914)       semStmt
semexprs.nim(793)        semExprNoType
semexprs.nim(2372)       semExpr
semstmts.nim(1663)       semProc
semstmts.nim(1520)       semProcAux
pragmas.nim(1063)        pragma
pragmas.nim(1059)        pragmaRec
pragmas.nim(1020)        singlePragma
pragmas.nim(671)         semCustomPragma
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by Yardanico** [comment]
You need to provide Nim code which triggers NimSuggest crash

**Comment by yglukhov** [comment]
I've filed a bug to nimsuggest tracker for the second case: https://github.com/nim-lang/nimsuggest/issues/78

**Comment by Araq** [comment]
Can't reproduce.
