### ISSUE TITLE
Minor Unittest colour bug in exception handling

### ISSUE THREAD

**Issue by Sud0nim** [nim-lang/Nim#7152]
When running unittest, if an exception is raised during a test the colour of the terminal text is not changed back to default during the exception handling. For example, as shown below, when this occurs the text is then stuck in the green colour of the [OK] output of the test even after program exit.

![image](https://user-images.githubusercontent.com/28996548/35527500-04ddc788-057f-11e8-9344-6255fe6e60d4.png)

I am not very familiar with debugging the compiler, but it seems like the issue originates in the test macro: https://github.com/nim-lang/Nim/blob/master/lib/pure/unittest.nim#L380

**Comment by ringabout** [comment]
Please supply the code which causes the exception, otherwise it is hard to find the reason.
