### ISSUE TITLE
strip() weird behavior 

### ISSUE THREAD

**Issue by juanfra684** [nim-lang/Nim#7159]
I don't know if I'm doing something wrong or strip() doesn't have a clear documentation. The OS is Linux with GCC.

```nim
import strutils

echo "a.1".strip(chars={'a', '.', '1'})
echo "abc.123".strip(chars={'a', '.', '1'})
echo "Aabc.123".strip(chars={'a', '.', '1'})
echo "Aabc.123".strip(chars={'a', '3'})
```

Output:
```

bc.123
Aabc.123
Aabc.12
```

**Comment by pqflx3** [comment]
'Strip' only removes chars from the front or back, and by default both, So this looks correct.

Are you trying to remove all these characters? There are various 'replace' 'multiReplace' procs

**Comment by juanfra684** [comment]
I want to remove the chars in `chars={}`. The doc is not really clear here:

>  Strips chars from s and returns the resulting string.
>  If leading is true, leading chars are stripped. If trailing is true, trailing chars are stripped.

`multiReplace()` did the trick. I will send a PR changing the first phrase. Thanks for the help.
