### ISSUE TITLE
`nim -c` can't compile files without an extension

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#7166]
It would be preferable to have an option to be able to provide the raw file path, thus being able to compile files not ending on `.someextension` .

**Comment by Yardanico** [comment]
Closing because it works:
![image](https://user-images.githubusercontent.com/21169548/35635794-4df993ce-06c0-11e8-8f48-d97a781d0daa.png)

**Comment by Clyybber** [comment]
Oh, so it seems to work when the file has a dot in the name, but without one it doesn't. Sorry i didn't test it enough.

**Comment by Clyybber** [comment]
Can we reopen this?

**Comment by Yardanico** [comment]
Yes, ok

**Comment by Araq** [comment]
I don't see the need to support this. Use file extensions.
