### ISSUE TITLE
Unsigned integers could not be incremented/decremented

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#7173]
This code fails to compile:

```nim
when isMainModule:
  var a = 0'u
  var c = 1'u
  inc(a, c)
```
with error:
```
Error: type mismatch: got (uint, uint)
but expected one of: 
proc inc[T: Ordinal | uint | uint64](x: var T; y = 1)
```

**Comment by Araq** [comment]
``inc`` takes an ``int``  as the optional second argument. Use ``+=`` instead for this case.

**Comment by johnnovak** [comment]
@Araq That works of course, but what's the reasoning behind this limitation? It's no big deal, but it's slightly annoying that I can't always use `inc/dec` consistently.

**Comment by Araq** [comment]
Dunno, it just makes more sense this way, ``inc(myEnum, 2)`` should compile.

**Comment by Bulat-Ziganshin** [comment]
can it be just overloaded? i think it's just a library issue

**Comment by dom96** [comment]
Different ``inc`` ideas?

I've also been annoyed by this. We should fix it.

**Comment by johnnovak** [comment]
I guess @Araq meant that if there was another version of `inc` that took an unsigned type as the first parameter, then the second one needs to be unsigned as well. But I don't quite see why that would be a problem? Or maybe he can explain to us what he meant :)

**Comment by Araq** [comment]
For me ``inc`` has the type ``(var T, int)`` and nothing else. Use ``+=`` for unsigned + unsigned.

**Comment by narimiran** [comment]
What's the status of this?

> [a] For me `inc` has the type `(var T, int)` and nothing else. 
or
> [b] I've also been annoyed by this. We should fix it.

If it is [a], then this can be closed. If it is [b], I'll make a PR.

**Comment by Araq** [comment]
It is "[c] undecided".

**Comment by narimiran** [comment]
Closing with the description @krux02 gave in #9931, as I think it applies also here:

> It took me a while as well to understand the difference. In my code I always used += while the standard library really prefers inc over +=.
> 
> Even though both inc and += do practically exactly the same, the concept is a bit different. The idea behind inc is to increment anything. This includes enum values. The offset is then specified by an integer, but it thas the default to 1. So inc is really made for while loops and iterators, while += is really meant for addition where both argument types are the same. This won't work for enums as adding two enum values doesn't really work.
> 
> I hope I could clear the question. I am closing this issue now though as it is more a question rather than a real issue description.
