### ISSUE TITLE
Confusing error message when calling toSeq using a non-iterator

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#7182]
```nim
import sequtils

type A = object
iterator items(self: A): int = discard
discard toSeq(A())  #type mismatch: got (seq[A], int)
```
This works:
```nim
discard toSeq(A().items)
```
Normally "toSeq" calls the "items" iterator if it finds one on it's own.
```nim
toSeq(1..10)
```

**Comment by Yardanico** [comment]
But should it?
1..10 is actually an iterator, and A() is not

**Comment by dawkot** [comment]
My bad then.
Still, the error message is pretty confusing.

**Comment by timotheecour** [comment]
* error msg would be better under this RFC: https://github.com/nim-lang/Nim/issues/8774  since toSeq would be able to use a template constraint for the untyped param
* independently of that, https://github.com/nim-lang/Nim/pull/8711 actually makes your test case work

**Comment by narimiran** [comment]
> #8711 actually makes your test case work

That is now merged and this indeed works.
