### ISSUE TITLE
"repr" returning invalid code

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#7186]
```nim
import macros

macro descLambda(x: proc): string = repr(x)

assert descLambda(proc(x: string) = echo x) == "proc (x: string) = echo [x]"

assert compiles(proc (x: string) = echo[x]) #fails
```

**Comment by GULPF** [comment]
You're missing a space between `echo` and `[x]`.

**Comment by dawkot** [comment]
Still fails.

**Comment by stisa** [comment]
Works for me on 0.17.3 ( commit: b87ef6553201c73e24b1b53641cc18abe17d6e9b ) by adding a space.
```nim
assert compiles(proc (x: string) = echo [x])
```
Assigning the version without space to a variable
```nim
var a = proc (x: string) = echo[x]
```
the compiler says `Error: cannot instantiate: echo[x]; got 1 type(s) but expected 0`

**Comment by Yardanico** [comment]
@stisa AFAIK space is required because of this - https://github.com/nim-lang/Nim/commit/ddc131cf07972decc206e033b2dd85a42eb1c98d
