### ISSUE TITLE
Times module lacks a way to generate 'Z'

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#7189]
```nim

import times

echo utc(now())
```

Produces something like ``2018-02-06T08:26:38+00:00`` and not ``2018-02-06T08:26:38Z``. Worse, there doesn't seem to be a way to make ``times.format`` produce the 'Z' instead.

**Comment by Araq** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by Araq** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @GULPF.

Possibly related issues are #5444 (Nim hangs forever in infinite loop in nre library), #1077 (Assignment causes number to go out of range), #3755 (rdstdin  disappeared from documentation index), #651 (Dereferencing a casted ``ptr array[...]`` causes incorrect C to be generated), and #4996 (nre module breaks os templates).

**Comment by GULPF** [comment]
Related: #7017
