### ISSUE TITLE
Cannot use concept twice in proc signature

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#7194]
Here is an example:

```nim
type Foo = concept c
  c.blah is bool

proc blah(x: int): bool = true

proc blah(x: string): bool = false

proc bar(x: Foo, y: Foo): bool = x.blah or y.blah

proc baz(x: Foo): bool = x.blah

echo baz("hi")

# echo bar(3, "hi")
```

If we decomment the last line, it fails with

```
foo.nim(14, 9) Error: type mismatch: got (int literal(3), string)
but expected one of: 
proc bar(x: Foo; y: Foo): bool
first type mismatch at position: 2
required type: Foo
but expression '"hi"' is of type: string

expression: bar(3, "hi")
```

I think this is actually the root cause of https://github.com/nim-lang/Nim/issues/6842

**Comment by zah** [comment]
This is the expected behavior. By default, the concept is considered a [bind-once type](https://nim-lang.org/docs/manual.html#generics-type-classes). If you want the concept to be freely matched to different types in each parameter position, you have to use the distinct modifier:

```
proc bar(x, y: distinct Foo): bool = x.blah or y.blah
```

**Comment by andreaferretti** [comment]
I find this behaviour rather innatural, but good to know!
