### ISSUE TITLE
big problems with newlines recent changes

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#7202]
I have updated the compiler and discovered that majority of our tests a broken. In tests we generate a lot output and compare against baseline files. The difference were in line endings.
The baseline files are checked into version control and VC is line end agnostic, so if you pull files on Windows you  get files with CR+LF, if pull files on linux you get LF. If you ask VC if files are different if they differ only in line end characters, it will say files are the same.

Ok, I have updated our code to use `\p` instead of `\n` everywhere and it has fixed the file tests, but it has also broken many other tests which use triple quote multiline strings. Multiline strings use `\n` all the time and it can't be changed. 

At this stage I don't see how are tests can be fixed. We either need the way to control line endings in multiple line strings or revert this change.

P.S.
Is it possible to change the behavior of VC? Checked, the answer is no. You can put something into VC config, but it will affect all projects not just this one (we use one VC for all projects), so it is not the option.
It is a showstopper for us.

**Comment by cooldome** [comment]
Effectively, as soon as yo have put a single `\p` into your code, triple quote strings are banned feature for you.

**Comment by Araq** [comment]
Good you report it now. :-) I think it makes sense that triple quotes default to ``\L``. Can you use something like this?

```nim

template p(s: string{lit}): string = s.replace("\n", "\p")

p"""problem 
solved?"""
```

**Comment by cooldome** [comment]
I'll give it a shot on Monday

**Comment by Araq** [comment]
Any news on this?

**Comment by cooldome** [comment]
Apologies for the delay,
I was under impression that Nim test suite once checked in into our VC is also affected, but it was not the case.
`p` template did work.
Closing the issue
