### ISSUE TITLE
On Windows: When app type is GUI, error message can't be seen, about missing DLL file or procedure

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#7212]
When app type is CLI, the error message about missing DLL file or procedure appears in the terminal.
When app type is GUI, the error message does not appear anywhere.
Suggestion: The error message should be shown over MessageBox(), when app type is GUI and platform is Windows.

**Comment by Araq** [comment]
That is exactly what is done. Maybe not for the DLL loading mechanism though.
