### ISSUE TITLE
Code falling through into exception handler when no exception thrown.

### ISSUE THREAD

**Issue by GrundleTrundle** [nim-lang/Nim#7232]
This seems to be related to commit d24b6667c6f74b61ea697bf91ce454f297ddac91, if I check out a version before that commit, I'm working again.  

I had no luck trying to get a small testcase for this.  Attached is the nim module and it's associated cpp file.  Hopefully that has enough information for you to see what's going on.  If there's something else I can provide, let me know.

[sourcefiles.zip](https://github.com/nim-lang/Nim/files/1735438/sourcefiles.zip)

In the nim module, the point the code is falling through is on line 121, going directly into the handler on 122.   If you look in the cpp file, the associated line is 1628, and you can see how the code drops into the exception handler.

**Comment by cooldome** [comment]
Thanks for reporting, I think I know where the problem is. I’ll do the fix.
