### ISSUE TITLE
RFC: Import Module Namespaces

### ISSUE THREAD

**Issue by pqflx3** [nim-lang/Nim#7250]
This is my best attempt at summarizing the discussion in IRC [02.23](https://irclogs.nim-lang.org/23-02-2018.html)

### Purpose:
We need a syntax for disambiguation of import statements, in particular, with regaurds to their resolution to an abolute '.nim' file path.

### Goals:
Solution to be as general as to allow nim, nimble, and future package managers to specify arguments to the nim compiler.

### Is there currently a problem? 
Yes. when 'random' and 'sha1'  were added to std lib, they conflicted with existing nimble packages.

### Could we just require conflicting nimble packages to change?
No. We could, but then future additions to nim std lib might conflict with already existing nimble packages. There needs to be a clean solution.

## Consider:

I want to use std libs 'strutils'. Easy as:
```nim
import strutils   # uses std lib's strutils
```
What if I want to use 'jester'? ```$>nimble install jester```
```nim
import jester   # use nimble pkg jester
```
How about 'random'?
```nim
import random  # uses std lib's random
```
What if we have the 'random' nimble pkg? ```$>nimble install random```
Now what does this do?
```nim
import random   # which does this resolve to?
```
Nimble doesn't enforce a package namespace (i.e. putting you code inside nimbledir/pkgs/random-v1/random/random.nim), but allows top level modules (i.e. nimbledir/pkgs/random-v1/random.nim)
So we introduced 'std' to explicity specify which module
```nim
import std / random   # uses std lib's random
```
But how do we specify using nimble's random? Right now import statements are resolved using compiler provided 'path', and stdlib's path's are listed first. So
```nim
import random   # finds std lib's random first
```
### Could we switch the order of nimble paths before stdlibs?
No. We could, but then `import strutils` could then be in conflict with a future nimble package. In fact, all std lib modules could potentially conflict, unless rewritten to `import std / strutils`. Forcing all existing projects to use `import std / ... ` seems infeasible.

# Solution 1: 'pkg' namespace
One propsal is to have an 'pkg' "namespace" or "scope"
```nim
import pkg / random
```
This will tell the compiler it needs to use the restricted set of paths for 'pkg', just like 'std' restricts the path to just stdlib paths. It opens up the idea for "import namespaces" or call it whatever you wish.
Then, we would need a default ordering of "import namespaces" for the covetted, simple, sugar
 ```import package```
which requires no "import namespace" specifier. E.g. { std, pkg, local } meaning: "prefer std lib paths, before nimble paths, before local relative paths".
With this preferred order, 'std' could almost be removed.

### Won't 'std' and 'pkg' conflict with local dirs?
No. They could, but it should be against convenction to have a dir named 'pkg' in your project. A workaround would be to use relative path imports ```import "./pkg/mypackage ```

### Difficulty:
How do we tell the compiler which paths are in which "import namespace"?
--stdPath:
--pkgPath:
Or maybe some kind of command line variable to allow more namespaces?

# Solution 2: '$' packages
We could offer a way to resolve package names to specifically provided paths.
`$> nim c ... --var:random=/some/path/to/random-v1/
```
import $random
```

The only problem I see depending on a library that needs to specify a path this way.
E.g.:
MyProject -> depends on SomeLib -> depends on nimble 'random'. How does 'SomeLib' describe this?

# Solution 3: Hybrid?
Specify a list of paths via command line for a particular "import namespace"
`$>nim c ... -var:std=/path/... this is the existing --path ../, --var:pkg=/path/to/nimble/pkgs/`
Then we could have 
```nim
import $std / strutils    # uses std lib paths
import $pkg / random   # uses nimble paths
import strformat   # uses an ordered hierarchy of "import namespaces"
```

# Solution 4: Explicit nimble namespacing
Cut our losses, require nimble pkgs to update and use namespacing (i.e. random-v1/random/random.nim)
Thus:
```nim
import random   # uses std lib random
import random/random   # uses nimble's random
```
Note that the sugar: if not found,  `import jester` try also `import jester/jester`
Likely leaves the same mess as 'import random'

Edits and corrections are likely needed in what I've summarized.

**Comment by Araq** [comment]
Excellent summary with no obvious mistakes.

**Comment by dom96** [comment]
Yep, thanks for taking the time to create this write up :)

**Comment by euantorano** [comment]
Another thing that could be lumped in with this is handling the case of multiple Nimble libraries with the same name by different authors. In Go and PHP, this is resolved by using imports like `github.com/euantorano/sysrandom` (Go) or `euantorano\sysrandom` (PHP). I think that if we’re looking at changing things relating to imports anyway, we should look at solving this issue too

**Comment by pqflx3** [comment]
Something I'm not too familiar with is how dependencies find their dependencies.

```
MyProject
- ProjectA
- ProjectB
 - SubProjectC/
     srcDir/
        subprojectC.nim
        subprojectC.nimble
        subprojectC/
          foo1.nim
          many/
            dirs/
              later/
                foo2.nim
                   import $root / foo1   # shortcut for "../../../foo1"
```

If I build 'MyProject', how are the paths for SubProject C added? Or rather, in what order are dependencies compiled?

I ask because it may relate to adding `import $root / my_other_module_in_same_package`
where `$root` is an "import namespace" containing the path of the current project. What happens if a dependency wants to use `$root`?

When you compile 'SubProjectC' it's `$root` is different than say when I compile 'MyProject'

**Comment by Araq** [comment]
The easiest solution seems to be to introduce a special ``pkg`` pseudo-directory that means "do not consider the stdlib's locations". This way nimble with its explicit --path overrides continues to work without any patch. ``pkg`` is a slightly misnomer then though.

**Comment by siliconvoodoo** [comment]
I kind of liked the possibility of shadowing std modules by introducing drop-in replacements that would have, say, logging, better performance, or more features. package authors supposedly know that they are naming stuff in conflict with the stdlib since the std predates.
Though this could be seen as a security hole.
But if we can have the same thing without module shadowing, at the cost a shadowing module declaring a list of export/usings or whatever (~defines in C?), for the thing it wants to replace, then that's enough too.

**Comment by dom96** [comment]
> The easiest solution seems to be to introduce a special pkg pseudo-directory that means "do not consider the stdlib's locations". This way nimble with its explicit --path overrides continues to work without any patch. pkg is a slightly misnomer then though.

Why not introduce it to mean "do not consider the stdlib **nor the local modules**"? That way ``--path`` will imply ``--pkgPath``.

**Comment by dom96** [comment]
For reference, as far as I know the decision is to do the following:

* Introduce the ``pkg``
  * Example: ``import pkg/random``
  * Semantics: search paths specified by ``--path`` for a ``random`` module. **Do not search any stdlib paths**.
  * Stdlib paths will be specified via a new flag, for example ``--stdPath:<dir>``. This way the compiler will know which paths are part of the ``std`` prefix, and which are part of the ``pkg`` prefix.

Hope that makes sense.

**Comment by yglukhov** [comment]
Imo, the solution is more convoluted and unintuitive than it should be. Suggestion:
1. If import stmt starts with a word, this word is a package name.
2. `std` is the package shipped with nim and contains standard library modules.
3. If import stmt starts with `.` or `..` - this is a relative-to-current-module import.

Backward compatibility:
1. If import path is not relative, and is not found, it falls back to relative. If still not found, it falls back to the insides of `std`. Optionally emit a deprecation message if match is found.

These simple rules allow the precise and intuitive control over what is imported, without introducing additional magic words like `pkg`.

Comparison of the two approaches (sample taken from a real life):
With pkg word:
```nim
from strutils import nil # is it std or relative?
import asyncnet, asyncdispatch, net, times, nativesockets, algorithm, logging # Are these std or relative?
import kademlia # ? Is this an std module or what?
import pkg / [ eth_keys, rlp, ranges, ttmath, nimcrypto ] # Interesting fact: all of the modules actually are coming from different packages
```

My approach:
```nim
from std/strutils import nil
import std/[asyncnet, asyncdispatch, net, times, nativesockets, algorithm, logging]
import ./kademlia
import eth_keys, rlp, ranges, ttmath, nimcrypto
```

A note about drop-in replacement. My take on it that nimble should allow overriding a package origin, thus allowing you to easily fork some existing package or even an stdlib. But this topic is outside this discussion, imo.

**Comment by siliconvoodoo** [comment]
I love the `std/`, now, that's "explicit is better than implicit" zen in action.

**Comment by mratsim** [comment]
Something that was touched upon in #6700 but is missing here is how to deal with submodules.

From an user point of view, `import foo/submodule` is great and working. From a dev point of view I don't see how I can respect nimble structure with a `src/` dir, keep meaningful directory names and not trigger the warning when a package grows like Arraymancer:

```
├── src
│   ├── arraymancer.nim
│   ├── autograd
│   │   ├── ag_accessors.nim
│   │   ├── ag_data_structure.nim
│   │   ├── autograd.nim
│   │   ├── gates_basic.nim
│   │   ├── gates_blas.nim
│   │   └── gates_reduce.nim
│   ├── datasets
│   │   └── mnist.nim
│   ├── io
│   │   └── io_csv.nim
│   ├── linear_algebra
│   │   ├── least_squares.nim
│   │   └── linear_algebra.nim
│   ├── math_ops_fusion
│   │   └── math_ops_fusion.nim
│   ├── ml
│   │   ├── metrics
│   │   │   ├── accuracy_score.nim
│   │   │   └── common_error_functions.nim
│   │   └── ml.nim
│   ├── nn
│   │   ├── activation
│   │   │   ├── relu.nim
│   │   │   └── sigmoid.nim
│   │   ├── layers
│   │   │   ├── conv2D.nim
│   │   │   ├── linear.nim
│   │   │   └── maxpool2D.nim
│   │   ├── loss
│   │   │   ├── cross_entropy_losses.nim
│   │   │   ├── loss.nim
│   │   │   └── mean_square_error_loss.nim
│   │   ├── nn.nim
│   │   ├── optimizers
│   │   │   └── optimizers.nim
│   │   └── shapeshifting
│   │       └── reshape_flatten.nim
│   ├── nn_primitives
│   │   ├── backend
│   │   │   ├── ...
│   │   │   └── nnpack_interface.nim
│   │   ├── fallback
│   │   │   └── conv.nim
│   │   ├── nn_primitives.nim
│   │   ├── nnp_activation.nim
│   │   ├── ...
│   │   └── private
│   │       ├── p_activation.nim
│   │       ├── p_logsumexp.nim
│   │       ├── p_nnp_checks.nim
│   │       └── p_nnp_types.nim
│   ├── object_pool
│   │   └── object_pool.nim
│   ├── private
│   │   ├── ...
│   └── tensor
│       ├── ...
│       ...
```

I get
```Nim
Error: Package 'arraymancer' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'arraymancer', but file 'maxpool2D.nim' is in a directory named 'nn/layers' instead. This will be an error in the future.
      Hint: If 'nn/layers' contains source files for building 'arraymancer', rename it to 'arraymancer'. Otherwise, prevent its installation by adding `skipDirs = @["nn/layers"]` to the .nimble file.
```

Same thing for `ag_accessors`. Basically if you use the `srcDir = 'src'` option, it seems like nimble wants each directory to only have a single file with the same name as the directory. This forces putting everything in a `private` directory or having a deep nesting.

**Comment by yglukhov** [comment]
One more benefit of my suggestion is that "package structure validation" is no longer necessary as the imports will be deterministic and the namespaces are separated.

**Comment by dom96** [comment]
@yglukhov regarding your suggestion, it's important to remember that not all packages "start with a word". We should look at what spurred this discussion on in the first place: the conflict between the ``random`` package and ``random`` stdlib module.

```nim
import random # Stdlib or package?
```

Does your suggestion solve this problem?

**Comment by yglukhov** [comment]
> Does your suggestion solve this problem?

Sure, according to my suggestion `random` is a package. To make it stdlib, use `std/random`.

According to backward compatibility rule, if "random" can't be resolved as a package, it will fallback to `./random`, and then to `std/random`.

**Comment by Araq** [comment]
``./foo`` is ugly and relative to the current module should have the highest priority. IMO.

**Comment by yglukhov** [comment]
Well I consider the current import semantics to be flawed. Yes, adding `pkg` magic word allows more control over the user intention. However, there remains a flaw, that the users will use `pkg` magic only when they hit a problem, to workaround it, otherwise they will just `import foo` as long as it works. Now we end up in a situation that nim stdlib can no longer introduce `foo` module, as it may break existing code.

My main point is "explicit import semantics" from my suggestion will prevent users from such potential problem (yes, there still remains package names clashing problem that has to be addressed).

@dom96, I really care about your book, but I care about Nim more, hope you understand me. And books have errata ;)

@Araq, `./foo` ugliness is subjective. I personally find it ugly too, but I'm ready to sacrifice it for consistency :).

**Comment by lightness1024** [comment]
@dom96 that is called the sunk cost fallacy.

**Comment by Araq** [comment]
> Yes, adding pkg magic word allows more control over the user intention. However, there remains a flaw, that the users will use pkg magic only when they hit a problem, to workaround it, otherwise they will just import foo as long as it works. Now we end up in a situation that nim stdlib can no longer introduce foo module, as it may break existing code.

And otherwise a nimble package cannot add ``foo`` since it breaks all the clients that already use ``foo`` to mean "relative to the current module". You're merely moving the problem around, not solving it.

**Comment by yglukhov** [comment]
@Araq, "relative to the current module" should start with `./` or `../`. The case you described falls into my "backward compatibility" rule, which ideally should be deprecated eventually.

**Comment by juancarlospaco** [comment]
On Python `import foo` is just syntax sugar for `__import__("foo")`.
I even use it all the time like `__import__("ptpdb").set_trace()`.
I say just keep it simple, and when you need disambiguation use `import("foo")` or `import("foo.bar.baz")` or `import("foo/bar/baz")`.
And that is similar to the rest of the language, that you can do `echo "foo"` or `echo("foo")`.
You dont need new Documentation for this, just works like the rest.
:thinking:

**Comment by andreaferretti** [comment]
@juancarlospaco this is the reason why imports in python cannot analyzed statically, which, by the way, is one of the reasons why packaging tools have a hard time in python
