### ISSUE TITLE
Too many digits from float32 to string

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#7252]
Code:
```
let v32:float32 = 1.00001
let v64:float64 = 1.0000001
echo v32
echo v64
write(stdout, v32)
echo ""
write(stdout, v64)
```

Expected output:
```
1.00001
1.0000001
1.00001
1.0000001
```

Actual output:
```
1.000010013580322
1.0000001
1.00001
1
```

echo with float32 prints too many digits that exceed precision of float32.
It seems float32 value is converted to float64 value before converted to string.

echo with float64 and write with float32 is fine but write with float64 lose precision.
There is proc write(f: File; r: float32), but no proc write(f: File; r: float64).
it seems float64 value is converted to float32 when it is passed to write.

**Comment by krux02** [comment]
wtf, this needs a fix, at least the write part.  The first part with `1.00001` printing actually `1.000010013580322` is technically not wrong. float can't hold the value `1.00001` exactly so it is rounded to a value that it can hold. And when you print that value it has a lot of digits. And you did not specify how many digits you want for printing. So you can't really complain about that. But the last one is just wrong.

**Comment by krux02** [comment]
well I looked at the code. write just uses `c_fprintf(f, "%g", r)` and that just does print with 6 digits precision, because no precision is specified. The implementation of echo deriviates here and makes sure that it is printed with enough precision.

**Comment by Araq** [comment]
There is no ``$`` for float32 nor it is easy to implement since C seems to lack such a facility, everything that uses varargs in C is converted to double first iirc.

**Comment by krux02** [comment]
I could also modify it further to this:

```nim
proc writeFloatToBuffer(buf: var array[64, char]; value: SomeFloat): int =
  ...
  const fmt = when value is float32: "%8g" else: "%.16g"
  var n: int = c_sprintf(buf[0].addr, fmt, value)
```
