### ISSUE TITLE
nim -r doesn't persist environment vars

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7256]
This is an annoying little quirk that makes debugging harder.

**Comment by andreaferretti** [comment]
Uh? Doesn't this relate to Nimble instead? Why is the issue in this repo (and what is it exactly about)?

**Comment by dom96** [comment]
I was meant to write ``nim`` but was working on Nimble so that must have resulted in a brain fart, but it is definitely a bug in ``nim`` (likely the ``osproc`` module actually).

**Comment by Araq** [comment]
```nim


import os, osproc

proc main =
  if paramCount() == 1 and paramStr(1) == "child":
    echo "child ", getEnv"mymy"
  else:
    echo "parent"
    putEnv "mymy", "value here"
    let p = startProcess("./temp", args=["child"], options={poParentStreams})
    echo p.waitForExit()

main()
``` 

works for me (OSX)

**Comment by genotrance** [comment]
I tried on Windows and it worked for me too.

```c:\> set A=1```

```nim
import ospaths

echo getEnv("A")
```

```c:\> nim c -r a.nim```

**Comment by andreaferretti** [comment]
The example of @genotrance works for me on OSX (`A=1 nim c -r a.nim`)

**Comment by dom96** [comment]
Maybe @Araq is right and it's some odd security feature. Does it work for you with ``DYLD_LIBRARY_PATH``?

**Comment by yglukhov** [comment]
`DYLD_LIBRARY_PATH` is not inherited per macos system behavior.
