### ISSUE TITLE
Effect system doesn't seem to handle inheritance correctly

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7257]
I'm getting complaints about an "unlisted effect: RootEffect" for a procedure that has `tags: [ReadIOEffect]`. Surely everything inherits from RootEffect and so listing `ReadIOEffect` means that `RootEffect` is also listed?

**Comment by dom96** [comment]
To reproduce try adding ``getOpenSslVersion()`` to ``raiseSSLError`` procedure in the `net` module.

**Comment by dom96** [comment]
Now I remember, I mentioned a similar issue in this PR: https://github.com/nim-lang/Nim/pull/7229#issuecomment-366759766

**Comment by cooldome** [comment]
I think it works in opposite direction: ``RootEffect`` means any effect, while ``ReadIOEffect`` is a particular effect

**Comment by Araq** [comment]
Yes.
