### ISSUE TITLE
compiler crash using "foo[N: static[Natural]]"

### ISSUE THREAD

**Issue by skunkiferous** [nim-lang/Nim#7258]
The follwing code causes a compiler (nim.exe) crash on Windows x64 on the current devel branch (on my system):

```nim
type
  StringValue*[LEN: static[Natural]] = array[LEN+Natural(2),char]
  StringValue16* = StringValue[14]
```

It seems to be a stack-overflow. Changing Natural to int resolves the issue.

> nim.exe --version
> Nim Compiler Version 0.17.3 [Windows: amd64]
> Copyright (c) 2006-2018 by Andreas Rumpf
> 
> git hash: e4515f304abf9b9ce029b634b38fce2a398a16fc
> active boot switches: -d:release

**Comment by krux02** [comment]
There is an infinite recursion in replaceTypeVars. I would like to fix it, but I don't know what to do about it. I don't know what replaceTypeVars is exactly about. @Araq Can you provide some specification what replaceTypeVars is supposed to do?

compiler/semtypinst.nim(268) replaceTypeVarsS
compiler/semtypinst.nim(243) replaceTypeVarsN
compiler/semtypinst.nim(206) replaceTypeVarsN
