### ISSUE TITLE
parseopt is really incorrent

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#726]
```
      for i in countup(1, ParamCount()): 
        result.cmd = result.cmd & quoteIfContainsWhite(paramStr(i).string) & ' '
```

and than parse it using arbitrary rules, not taking " into account, which was just explicitly introduced! Thinks like `nirmod compile --path:"/i like spaces/projects/"` never (at least not in 0.9.2) worked.

That's why #702 broke parser.

**Comment by timotheecour** [comment]
> To clarify: parseopt is still incorrect, so use parseopt2. 

`parseopt.cmdLineRest`  has been fixed here: https://github.com/nim-lang/Nim/pull/10291 and I don't know of another bug with it
`parseopt2.cmdLineRest` is being fixed here https://github.com/nim-lang/Nim/pull/10304

> (or some high level module, preferably)

like cligen for example
