### ISSUE TITLE
Problem assigning 0x8000000 (or greater) to a uint32 anywhere but in a when expression

### ISSUE THREAD

**Issue by nucky9** [nim-lang/Nim#7260]
In this code:
```nim
when cpuEndian == bigEndian:
  const
    rMask: uint32 = 0xff000000
    gMask: uint32 = 0x00ff0000
    bMask: uint32 = 0x0000ff00
    aMask: uint32 = 0x000000ff
else:
  const
    rMask: uint32 = 0x000000ff
    gMask: uint32 = 0x0000ff00
    bMask: uint32 = 0x00ff0000
    aMask: uint32 = 0xff000000
```
The second aMask assignment fails with the warning ```nim message: 'type mismatch: got (int64) but expected 'uint32' ```, even though the assignment in the `when` statement does work. Also assignments outside either the `when` or the `else` also fail (i.e. writing `const a: uint32 = 0xF0000000` anywhere other than in the `when` fails).

I tested further, and it is anything over 0x70000000 that fails (i.e, anything that assigns to the highest bit) when the assignment is made in the else clause.

**Comment by Parashurama** [comment]
You can use a suffix for integer literal value:
```rMask: uint32 = 0xff000000'u32```
This is a current limitation of in that value >= 0x8000000 are treated as int64 and thus not implicitly assignable to smaller int (uint32 here)

**Comment by nucky9** [comment]
Thanks - I did know that I can explicitly cast it to make it work, and it makes sense that it is treated as int64. But it doesn't make sense why it is accepted if it is within the `when` expression (the first rMask assignment works fine).

**Comment by GULPF** [comment]
The first assigment doesn't work either, it's just that `when` branches that are not taken are not semchecked. If you change it to `when true` the first assignment will fail.

**Comment by Araq** [comment]
No bug here, integer literals are not of type uint32. Read the manual.
