### ISSUE TITLE
Better error message when finding line number fails

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#7268]
For some syntax errors like the following (tested on 0.17.2; fixed on 0.18.0)
```nim
var x: int: 0
```
the compiler can't find out the line number where the error appears,
it prints out `???(???, 0) Error: identifier expected, but found ''`.
Also `nimsuggest` doesn't recognize this as an error.

Maybe it would be good to find as many of these as possible because it's quite hard to find those without line number in bigger source code.
So my idea was, that the error message could additionally ask the user to find the line and open an issue on github about it, this would help to make the compiler more correct.

**Comment by Araq** [comment]
This particular bug was fixed.

**Comment by tim-st** [comment]
@narimiran is it fixed?

**Comment by narimiran** [comment]
> is it fixed?

On my end (with Nim 0.19.9) it produces `foo.nim(1, 11) Error: in expression '(
  0)': identifier expected, but found ''`, so the correct position of the error is correctly detected.

I cannot keep it open on an assumption that somewhere else it might not work. If there are some examples where it fails, I'll reopen it.

**Comment by tim-st** [comment]
I think it's not a good idea to close as many open issues as possible just to bring the number of open issues down.
