### ISSUE TITLE
Generic with constraint on multiple parameters fails to typecheck

### ISSUE THREAD

**Issue by aviator01** [nim-lang/Nim#7269]
I think I found a bug with generic typechecking, but I'm still a bit new to Nim, so I may be wrong.  This code fails to compile:

```nim
type
    Foo = object of RootObj

    Gen[T: Foo, V: Foo] = object

    Gen2[T: Foo, V: Foo] = object
        p: Gen[T, V]
```

The error is:
```
main.nim(19, 15) Error: cannot instantiate Gen
got: <type T: Foo, type V: Foo>
but expected: <T: Foo, V: Foo>
```

However, with a single generic parameter, it compiles fine:

```nim
type
    Foo = object of RootObj

    Gen[T: Foo] = object

    Gen2[T: Foo] = object
        p: Gen[T]
```

This is using the latest commit from the devel branch.

**Comment by zah** [comment]
I guess this example was artificially simplified (what would be the point of having generic params if they are restricted to a single type?). We may discover a more general problem in the compiler while examining the issue, but I'm curious what was original real-wold use case that brought you to discover the issue?

**Comment by aviator01** [comment]
Yes, I just tried to produce the shortest example I could, maybe I made it a bit too short!  I was using an object with an inline array of a generic type and length, which worked fine (again, this is slightly simplified, I have a more specific base class constraint I'm using):

```nim
type
    DataItem*[TField: RootObj, FieldCount: static[int]] = object
        fields: array[FieldCount, TField]

discard DataItem[RootObj, 5]()
```

I then decided to add another generic field:

```nim
type
    DataItem*[TField: RootObj, TExtra: RootObj, FieldCount: static[int]] = object
        fields: array[FieldCount, TField]
        extraData: TExtra

discard DataItem[RootObj, RootObj, 5]()
```

Which caused the error.  I then started testing, and realized that literally any time there are two generic constrained types, it produces that error.

**Comment by aviator01** [comment]
And, just for further context, the reason I'm specifying constraints on the `TField` and `TExtra` generic parameters is because it won't let me only specify a single static constraint like this:

```nim
type
    DataItem*[TField, TExtra, FieldCount: static[int]] = object
        fields: array[FieldCount, TField]
        extraData: TExtra

discard DataItem[RootObj, RootObj, 5]()
```

This produces errors for all uses of `TField` and `TExtra`: `main.nim(23, 35) Error: type expected`

If I take out the third generic parameter, it works:

```nim
type
    DataItem*[TField, TExtra] = object
        fields: array[5, TField]
        extraData: TExtra

discard DataItem[RootObj, RootObj]()
```

So there's something seriously weird going on with generic constraints.

**Comment by zah** [comment]
The other possible solution is to use:

```nim
type
  DataItem*[TField, TExtra; FieldCount: static[int]] = object
    ...

```

Notice how the generic parameters are separated with a semicolon instead of a comma. This prevents assigning the same type to all of the parameters.

**Comment by aviator01** [comment]
Right, thanks.  I was wondering how to do that 😄

**Comment by narimiran** [comment]
> I then decided to add another generic field: (...) Which caused the error. 

Both the original example and this one from the comment don't produce the error anymore in Nim 0.19.
