### ISSUE TITLE
exec("nimgrab 'https:// -- some problems on windows

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#7275]
I have these code in https://github.com/StefanSalewski/gintro/blob/master/gintro.nimble
```
try:
    exec("wget 'https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/gobject.nim' -O gobject.nim")
  except:
    try:
exec("nimgrab 'https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/gobject.nim' gobject.nim")
```
Worked fine in Linux, both wget and nimgrab.

Now windows users reported that for nimgrab they have to remove the single quotes (https://github.com/StefanSalewski/gintro/issues/24). It is a bit strange that command behaves differently on Linux and Windows, and error message is not really helpful. And question is: Is this the (without single quotes) the recommended form for all OS?

`
exec("nimgrab https://raw.githubusercontent.com/StefanSalewski/oldgtk3/master/oldgtk3/gobject.nim gobject.nim")
`

**Comment by Araq** [comment]
Command line parsing is OS specific, Windows does not use single quotes iirc. No bug here.

**Comment by StefanSalewski** [comment]
OK no bug, but I would need a hint.

Is there a form for the exec string that should work for all OS, or do I have to test for OS and supply different command strings (with and without single quotes)

**Comment by dom96** [comment]
Is ``nimgrab``'s purpose literally to allow nimscript to download things?

Are we going to implement Nim programs for each case where the FFI cannot be used?

**Comment by StefanSalewski** [comment]
dom, the fact is that gintro needed 3 files from oldgtk3 package for compiling generator program. Only for this task, and generally users of gintro will not want to use and install full oldgtk3. So I was happy to get download of 3 single files working with wget. Araq told me then to use nimgrab instead for windows users.

Other ways would be:
- make gintro depend on oldgtk3
- do a full git clone of oldgtk3 only for install gintro
- copy 3 files from oldgtk3 package to gintro

**Comment by Araq** [comment]
> Is nimgrab's purpose literally to allow nimscript to download things?

No, it's used by the installer. 

> Are we going to implement Nim programs for each case where the FFI cannot be used?

Even if it were for nimscript, it would be wise. I can remove 'nimgrab' and ensure my Nim bulid doesn't download things, for a .compileTime proc things are harder to review.

**Comment by Araq** [comment]
> Is there a form for the exec string that should work for all OS, or do I have to test for OS and supply different command strings (with and without single quotes)

The version without quotes should work for both Unix and Windows.

**Comment by StefanSalewski** [comment]
OK, then I will remove the single quotes from the strings.

**Comment by cheatfate** [comment]
@StefanSalewski on Windows you can use
https://github.com/nim-lang/Nim/blob/devel/tools/urldownloader.nim
It is available and working since Windows 2000, but of course it will use SSL/TLS versions which are supported by particular Windows version (https://marclsitinfrablog.wordpress.com/windows-sharepoint-articles-posts/windows-support-for-ssltls-versions/)
