### ISSUE TITLE
`runnableExamples` don't have own scope for imports

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#7285]
Consider the following example under `nim 0.18.0`:
```nim
import unicode

proc test1*(rune: Rune): Rune =
  ## test proc 1
  runnableExamples:
    #import unicode
    assert test1(Rune(1)) == Rune(1) # the same with doAssert
  return rune

proc test2*(rune: Rune): Rune =
  ## test proc 2
  runnableExamples:
    assert test2(Rune(1)) == Rune(1)
  return rune
```

The generated `*_examples.nim` imports the file `*.nim` but has no access to the imports that are already imported and usable in this file (here `unicode`).
For this example line 6 has to be uncommented to work. But then both examples work, which is unconsistent because the second proc would need `unicode` too. I think either both should have access to all imported modules or each of them should import the modules required for the example to work, but not like it's implemented now.

**Comment by Bennyelg** [comment]
Its not inheritance the module procs immediately when `runnableExamples`?

**Comment by dom96** [comment]
Yeah, each ``runnableExamples`` should have its own scope.

**Comment by Araq** [comment]
The ``import unicode`` is required for both examples. That the second works without is a bug we can prevent by generating a Nim file per 'runnableExamples' section.

**Comment by dom96** [comment]
> That the second works without is a bug we can prevent by generating a Nim file per 'runnableExamples' section.

Why not just generate multiple ``block``s?

**Comment by Araq** [comment]
It already does generate multiple blocks but ``import`` cannot be used within a block, so it's extracted to the top level.

**Comment by tim-st** [comment]
I think it's good to have the imports required at every `runnableExample` scope for one reason: the developer knows exactly which modules to import to test the examples. But if that was the idea behind, there is an other thing that is unexpected: when I generate the docs and imported e.g. `unicode` in this scope, every assert (example) can be found in the html doc but not the import that was forced (here `unicode`).

**Comment by Araq** [comment]
> I think it's good to have the imports required at every runnableExamples scope for one reason: the developer knows exactly which modules to import to test the examples. 

That was the idea behind it, yes.

> when I generate the docs and imported e.g. unicode in this scope, every assert (example) can be found in the html doc but not the import that was forced (here unicode).

Ouch...
