### ISSUE TITLE
Wrong comparison with empty string in version 0.18

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#7291]
In version 0.18, the result of the comparison `"a" > ""` is `false` instead of `true`. The result is correct with version 0.17.2.

**Comment by Yardanico** [comment]
Even more strange - BOTH `"a" > ""` and `"a" < ""` output false!

**Comment by skilchen** [comment]
This bug was introduced by the following commit:
```
commit 0b52466bb83a747ee7c3325f20b741ad243c0c6a
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Fri Jan 19 09:26:11 2018 +0100

  bugfix: do not call memcmp for nil strings

```
I think, line 33 in lib/system/sysstr.nim should be changed from:
```nim
result = 0
```
to
```nim
result = a.len - b.len
```
