### ISSUE TITLE
SIGSEGV when passing empty array to strutils format

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#7293]
```nim
echo "$#" % []
# SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

I've tried to debug this. It seems accessing the `varargs` param returns `nil` when the index is out of bounds, instead of raising `IndexError`. I don't understand why, since it works as expected outside of `strutils`. Checking the index is within the array bounds would fix this, but hide the other error. I think there are 2 unrelated bugs here.

**Comment by skilchen** [comment]
what about changing line 2298 in strutils.nim from:
```nim
if num >% a.high: invalidFormatString()
```
to
```nim
if num > a.high: invalidFormatString()
```
?

**Comment by nitely** [comment]
As I said, that would fix it. But does not explain why accessing `varargs` returns `nil` when out of bounds.

**Comment by skilchen** [comment]
ok, thats probably because on line 416 we have: 
```nim
{.push checks: on, line_trace: off .} # this is a hot-spot in the compiler!
```
and the corresponding `{.pop.}` is on line 2409, so we have no bounds checking here

**Comment by nitely** [comment]
Ah, that explains it. Thanks :smile: . If you are going to fix this, the fix must be applied on every cae branch. btw, it will also fail for arrays with negative range indices like: `array[-10 .. -5, string]`
