### ISSUE TITLE
Search feature doesn't work on all docs pages 

### ISSUE THREAD

**Issue by cabhishek** [nim-lang/Nim#7294]
Ways to reproduce:

1) Goto https://nim-lang.org/docs/tut1.html
2) Type `json` in the search bar and click `Module Json` from the search result (works)
3) On the actual Json module page type `macros` (or anything), the search bar doesn't work anymore 

This used to work prior to `v0.18.0` and is quite critical for discoverability. 

Browser shows following error:
```
dochack.js:1448 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at dosearch_28190 (dochack.js:1448)
    at wrapper_28415 (dochack.js:1527)
```
Tested on `Chrome Version 64.0.3282.186 (Official Build) (64-bit)`

**Comment by Yardanico** [comment]
Can reproduce on Firefox 58, but error is a bit different:
![image](https://user-images.githubusercontent.com/21169548/36939581-2be64bb4-1f44-11e8-9a42-d17e92d10b01.png)

**Comment by mjoud** [comment]
The id `searchInput` is duplicated since #6723. https://github.com/nim-lang/Nim/blob/devel/config/nimdoc.cfg#L112-L113

**Comment by cabhishek** [comment]
@mjoud Good point and it leads invalid value lookup. 

In `dochack.js`
```
var elem_28417 = document.getElementById("searchInput");
var value_28418 = elem_28417.value; // undefined
```
