### ISSUE TITLE
Is this a bug about unsigned constant value?

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#7300]
```nimrod
proc test1(u: uint32) = echo u-1
template test2(u: uint32) = echo u-1
var a = 0'u32
const b = 0'u32

test1(a)
test2(a)
test1(b)
test2(b)
```
Output:
> 4294967295
4294967295
4294967295
18446744073709551615

Nim Compiler Version 0.18.0

**Comment by cheatfate** [comment]
@andreaferretti it looks like not `unsigned` bug, but something worse.

18446744073709551615 = 0x1999999999999999, even with better scenario of this bug i will expect to see 0xFFFFFFFFFFFFFFFF.

**Comment by skilchen** [comment]
> @cheatfate claimed: 18446744073709551615 = 0x1999999999999999

for me that is not true:
```nim
import strutils
const x = 0x1999999999999999'u
const y = 0xFFFFFFFFFFFFFFFF'u
echo x, "  ", toHex(cast[int64](x), 16)
echo y, " ",  toHex(cast[int64](y), 16)
```
```
1844674407370955161  1999999999999999
18446744073709551615 FFFFFFFFFFFFFFFF
```

**Comment by cheatfate** [comment]
@skilchen that was my mistake, or windows calculator mistake which not copy pasted full value and strip one symbol from behind, so you are right its unsigned problem.

**Comment by timotheecour** [comment]
@LemonBoy your PR https://github.com/nim-lang/Nim/pull/8095 says it fixes https://github.com/nim-lang/Nim/issues/7300 but the problem is still there: this still prints

4294967295
4294967295
4294967295
18446744073709551615

ie, `test2(b)` is wrong (should be `4294967295`)
