### ISSUE TITLE
Compiler manual is not that clear about int literal

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#7304]
As forum user lscrd reported, this text is not fully correct about int literals:

```
There exists a literal for each numerical type that is defined. The suffix starting with an apostrophe (''') is called a type suffix. Literals without a type suffix are of the type int, unless the literal contains a dot or E|e in which case it is of type float.
```

At a different position this correct explanation exists:
```
An integer literal that has no type suffix is of this type if it is in the range low(int32)..high(int32) otherwise the literal's type is int64.
```

**Comment by twetzel59** [comment]
@StefanSalewski I have looked at the forum, and I am interested in improving the manual. Do you mind clarifying what is wrong with the first statement?

As I think I understand, it could read (as an example):
... of the **integer type of the minimum width to represent the value**, unless the literal contains a dot or E|e in which case it is of type float.

**Comment by StefanSalewski** [comment]
twetzel, sorry english is not my native language, so I have some problems to give a good suggestion.

Your suggestions is wrong, because integer literals are of type int or int64, but never something like int16.

Maybe we could write: "Literals without a type suffix are of AN INTEGER type, unless the literal contains a dot or E|e in which case it is of type float." "This INTEGER type is type int if the literal is in the range low(int32)..high(int32) otherwise the literal's type is int64."

**Comment by twetzel59** [comment]
Off the top of my head, that sounds correct

**Comment by twetzel59** [comment]
I'll consider making a pull request once I write the changes, possibly tomorrow or sometime in the next few days :)

**Comment by twetzel59** [comment]
I'm going to work on this now.
