### ISSUE TITLE
(x, y, z) += f(...) does not work

### ISSUE THREAD

**Issue by Tetralux** [nim-lang/Nim#7306]
For a procedure `f` that looks like this:
```nim
proc f(): tuple[arg1, arg2: int, arg3: float] =
  return (1, 2, 4.5)
```
Or this:
```nim
proc f(): (int, int, float) =
  return (1, 2, 4.5)
```
[Edit: You can imagine that this might be just one of the procedures with multiple return values in my program.]

This works:
```nim
var x, y: int
var z: float
(x, y, z) = f()
```
But this does not:
```nim
var x, y: int
var z: float
(x, y, z) += f() # Note the '+', for example.
```
Which you might expect to behave the same as this:
```nim
var x, y: int
var z: float
block:
  var x2, y2: int
  var z2: float
  (x2, y2, z2) = f()
  x += x2
  y += y2
  z += z2
```

They give the following errors:
- With a `tuple`:
```
test.nim(9, 11) Error: type mismatch: got <tuple of (int, int, float), tuple[arg1: int, arg2: int, arg3: float]>
but expected one of:
proc `+=`[T: SomeOrdinal | uint | uint64](x: var T; y: T)
  first type mismatch at position: 1
  required type: var T: int or int8
  but expression '(x, y, z)' is of type: tuple of (int, int, float)
proc `+=`[T: float | float32 | float64](x: var T; y: T)
  first type mismatch at position: 1
  required type: var T: float or float32
  but expression '(x, y, z)' is of type: tuple of (int, int, float)

expression: (x, y, z) += f()
```
- Without a `tuple`:
```
test.nim(9, 11) Error: type mismatch: got <tuple of (int, int, float), tuple of (int, int, float)>
but expected one of:
proc `+=`[T: SomeOrdinal | uint | uint64](x: var T; y: T)
  first type mismatch at position: 1
  required type: var T: int or int8
  but expression '(x, y, z)' is of type: tuple of (int, int, float)
proc `+=`[T: float | float32 | float64](x: var T; y: T)
  first type mismatch at position: 1
  required type: var T: float or float32
  but expression '(x, y, z)' is of type: tuple of (int, int, float)

expression: (x, y, z) += f()
```

**Comment by andreaferretti** [comment]
This is no surprise, `+` is not defined for tuples. Assignment via `(x, y, z) = f()` is a destricturing assignment, there is no particular reason why this should work with any operator such as `+`.

In fact just doing `tuple1 + tuple2` will not compile. You can define your own operators, such as in the following example:

```nim
proc `+`(a, b: (int, int)): (int, int) =
  let (a1, a2) = a
  let (b1, b2) = b
  return (a1 + b1, a2 + b2)
  
template `+=`(a: var (int, int), b: (int, int)) =
  a = a + b

var
  x = (1, 2)
  y = (3, 4)

x += y
echo x
```

**Comment by Tetralux** [comment]
@andreaferretti 
You're not seriously suggesting that I do that for every combination of types and arity that I might use throughout a program, are you?

It also doesn't fix it if I named my return values using a `tuple`, so I'd have to overload `+=` for those seperately, using nearly identical code. Seems like a waste of my time to me.
Unless there's a way to name my return values without using a `tuple` in the way described above?
Similar to:
```nim
proc f(): (arg1, arg2: int, arg3: float) = ...
```

**Comment by andreaferretti** [comment]
You can avoid repeating for each different type by using generics like this:

```nim
proc `+`[A: SomeNumber](a, b: (A, A)): (A, A) =
  let (a1, a2) = a
  let (b1, b2) = b
  return (a1 + b1, a2 + b2)
```

You can generate procs like this for different arities using macros.

The template itself can work with any type like this:

```nim
template `+=`(a, b: untyped) =
  a = a + b
```

That said, I am not suggesting anything. I am just remarking that `+` is not defined for tuples - the same is true, say, for python or scala. I don't know any language where `+` is automatically lifted to tuples - Nim allows you to do it in your own code with minimal impact.
