### ISSUE TITLE
strutils wordWrap skips characters

### ISSUE THREAD

**Issue by ryanc-signiq** [nim-lang/Nim#7311]
It looks like wordWrap will skip the first character of the second chunk of a single split string.

It can be reproduced with the following code:

`echo wordWrap("AAAAAAAABBBBBBBBCCCCCCCCDDDDDDDDEEEEEEEEFFFFFFFFGGGGGGGGHHHHHHHH", 8)`

Run that and count the B's, there will be only 7 and the total number of characters in the resulting string will be 63, not 64

**Comment by ryanc-signiq** [comment]
Submitted a PR for this: https://github.com/nim-lang/Nim/pull/7312

**Comment by Yardanico** [comment]
Closed since https://github.com/nim-lang/Nim/pull/7312 was merged
