### ISSUE TITLE
Standard Library documentation should include when public methods/types are introduced

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#7318]
Methods (and types) in the standard library should include when (what version of Nim) they were released in, and can expect to be supported for. This would also compliment the existing deprecation listings that are provided. Since there isn't any versioning of the official language and standard library documentation (https://nim-lang.org/docs/lib.html), it is difficult to determine what compatible versions of the language and compiler exist -- outside of the version that is listed as the docs generated for. As far as I can tell the only way to figure this out is by performing a git-blame on the source code of relevant lines from the source repository.

**Comment by Araq** [comment]
The documentation is versioned, e.g. https://nim-lang.org/0.16.0/httpclient.html

It's hardly known though. :-)

**Comment by samdmarshall** [comment]
Interesting, I didn't know the website had the versioned documentation. However, short of making a script to diff the docs (though you would be better off just using git-blame on the source); there still isn't a way to determine when things are introduced ☹️

**Comment by Araq** [comment]
Well once v1 is out everything coming after v1.0 will be annotated with a version. So in the long run there won't be a problem. :-)

**Comment by narimiran** [comment]
As mentioned above:
* you can manually check previous versions of docs
* this will be coming after v1.0

I know it isn't perfect, but I'm closing this so we can focus on more pressing issues.
