### ISSUE TITLE
Quote captures `result` of containing macro

### ISSUE THREAD

**Issue by StasRuinsEverything** [nim-lang/Nim#7323]
Hello! Here's a contrived reproduction:
```nim
import macros

macro mac(): untyped =
  quote do:
    proc test(): int =
      (proc(): int = result = 123)()

mac() # Error: type mismatch: got <int literal(123)> but expected 'NimNode = ref NimNodeObj'
echo test()
```
Using `return` instead circumvents the issue.

**Comment by PMunch** [comment]
Yeah this is a really strange and annoying bug. One way I've found to still be able to use result in quote do is to do this:
```
import macros

macro mac(): untyped =
  let res = newIdentNode("result")
  quote do:
    proc test(): int =
      (proc(): int = `res` = 123)()

mac() # Error: type mismatch: got <int literal(123)> but expected 'NimNode = ref NimNodeObj'
echo test()
```

**Comment by PMunch** [comment]
I have figured out a nice simple fix for this now: https://github.com/PMunch/Nim/commit/60896543236220e854894641f0964dccbe6a0fab. It's still not completely done but I hope to have it done by tomorrow and create a PR for this.

**Comment by PMunch** [comment]
Done, here is the PR for my fix: https://github.com/nim-lang/Nim/pull/7343

**Comment by krux02** [comment]
maybe this problem is resolved when the quote do macro is limited to bind proc- macro- and template-symbols. To my experience binding var-, let-, param, etc symbols always goes wrong.

**Comment by PMunch** [comment]
@krux02 maybe close this issue as well?

**Comment by krux02** [comment]
I can confirm, this works now.

**Comment by mem-memov** [comment]
I've just copied the code from the top of the report and run it with Nim 0.19.2. It produced the same error message.

**Comment by SolitudeSF** [comment]
works on devel
