### ISSUE TITLE
Keep Getting Error while attempting to compile

### ISSUE THREAD

**Issue by Lite5h4dow** [nim-lang/Nim#7328]
Error = `HError: unhandled exception: Unknown IO Error [IOError]`

Cause = Unknown

Only ever happens when I attempt to compile a program. and happens frequently but always at a random time. could be 2 lines in could be 10.

**Comment by Yardanico** [comment]
@Lite5h4dow I assume you use VSCode ? This is a VSCode bug

**Comment by Yardanico** [comment]
@Lite5h4dow probably a duplicate of this - https://github.com/nim-lang/Nim/issues/7111
