### ISSUE TITLE
how to get property of json in stdtmpl?

### ISSUE THREAD

**Issue by shinriyo** [nim-lang/Nim#7329]
I wrote the code.

```
#? stdtmpl | standard
#import json
#proc generateIndexHTMLPage(title: string, tabs: openarray[JsonNode]): string =
#  result = ""
<head><title>$title</title></head>
<body>
  <div id="menu">
    <ul>
  #for item in items(tabs):
    <li><a href=
    #item["id"]
    >
    #item["name"]
    </a></li>
  #end for
    </ul>
  </div>
</body>
```

item is json like this `{"id":1, "name": "hoge"}`.

`item` is type `JsonNode`.
So, I should get id like `item["id"]`

```
expression 'item["id"]' is of type 'JsonNode' and has to be discarded
```
error.

however, I changed `discard item["id"]`, it never return string...

**Comment by shinriyo** [comment]
I changed like this.
I used `${item["name"]}`.
perhaps inside of `${}` can use code?

```
#? stdtmpl | standard
#import json
#proc generateIndexHTMLPage(title: string, tabs: openarray[JsonNode]): string =
#  result = ""
<head><title>$title</title></head>
<body>
  <div id="menu">
    <ul>
  #for item in items(tabs):
    <li><a href=users/${item["id"]}>${item["name"]}</a></li>
  #end for
    </ul>
  </div>
</body>
```

<img width="486" alt="screen shot 2018-03-13 at 18 50 36" src="https://user-images.githubusercontent.com/396927/37334521-7765dc0a-26ef-11e8-946a-7ffb381cf8a9.png">

However, double quote, `"` was shown... 
And, multi byte string, like Japanese can't?

**Comment by dom96** [comment]
Glad you got it to work :)

**Comment by andreaferretti** [comment]
Can I close?

**Comment by shinriyo** [comment]
@andreaferretti yes!
