### ISSUE TITLE
asyncfile getFileSize issue in linux

### ISSUE THREAD

**Issue by abijahm** [nim-lang/Nim#7347]
```nim
import asyncdispatch,asyncfile

proc main(){.async.}=
  var file = openAsync("hello.txt")
  echo file.getFileSize()
  echo await file.readAll()
  echo file.getFilePos()

waitFor main()
```
hello.txt

```txt
hello humans!
```

windows output
```
13
hello humans!
13

```
linux output
```
13

0
```

**Comment by PMunch** [comment]
Yeah, the issue is here: https://github.com/nim-lang/Nim/blob/411b9aeac75239d4e93ae4655f8d00b871c2cc04/lib/pure/asyncfile.nim#L81. It seeks to the end of the file and reads out the position. A bit strange than getFilePos afterwards is 0 though. What it should do is store the current position, do the seek and set result as it does now, then seek back to the current position.

**Comment by dom96** [comment]
Possibly related to https://github.com/nim-lang/Nim/issues/5532 and/or https://github.com/nim-lang/Nim/issues/5531

**Comment by dom96** [comment]
This is on 0.18.0, right?

**Comment by Yardanico** [comment]
@dom96 I tested it on latest Nim devel (on Arch Linux), and it behaves exactly like @abijahm explained

**Comment by abijahm** [comment]
```
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release
```
am using windows subsystem for linux

**Comment by jangko** [comment]
this is the current implementation of asyncfile.getFilepos

```Nim
proc getFilePos*(f: AsyncFile): int64 =
  ## Retrieves the current position of the file pointer that is
  ## used to read from the specified file. The file's first byte has the
  ## index zero.
  f.offset
```
although the doc says it "Retrieves the current position...", I don't see any any retrieval action inside that proc. f.offset is updated elsewhere among read and write operations, interleaved between windows and posix code, arggghh.....
