### ISSUE TITLE
Deprecate ``callsite`` builtin

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#7369]
- I know of no use cases for it.
- It slows down the compiler by roughly 1-2% as it requires us to keep original call ASTs around.

**Comment by PMunch** [comment]
Would it be possible to still get the line info of a call? The combparser library I wrote uses it to create meaningful error messages

**Comment by Araq** [comment]
You can take the line info of the first argument instead, right?

**Comment by PMunch** [comment]
If the macro has an argument. So it would work in my case, but it's not a general solution.

**Comment by Araq** [comment]
well there is always ``system.instantiationInfo``

**Comment by PMunch** [comment]
Hmm, I guess. But that requires you to wrap your macro in a template if you want that information, making documentation a bit strange. Benefit is of course that you could also wrap a proc in it..

But overall I guess that's a good enough solution.

**Comment by PMunch** [comment]
By the way, having something like this:

```nim
import macros

macro addInstantiationInfo(x: untyped): untyped =
  let
    origName = x[0]
    procName = genSym(nskProc)
    params = x[3].copy()
  x[0] = procName
  var paramNames: seq[NimNode] = @[]
  for i in 1..params.len-1:
    paramNames.add params[i][0]
  x[3].insert(1, nnkIdentDefs.newTree(
        newIdentNode("instantiationInfo"),
        (quote do:
          tuple[filename: string, line: int]
        ),
        newEmptyNode()
      )
    )
  result = quote do:
    `x`
    template `origName`() =
      `procName`(system.instantiationInfo())
  result[1][3] = params
  echo result.treeRepr
  for param in paramNames:
    result[1][6][0].add param


proc hello(x: int) {.addInstantiationInfo.} =
  echo x
  echo instantiationInfo

var x = 5
hello(x) # outputs (filename: "test.nim", line: 35)
hello(10) # outputs (filename: "test.nim", line: 36)
```
somewhere would be really nice.

**Comment by PMunch** [comment]
Any way `system.instantiationInfo` could be expanded to include column number by the way?
