### ISSUE TITLE
Doc gen: separate safe and unsafe procedures

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7372]
Inspired by the documentation for ``asyncnet``, in particular this function: https://nim-lang.org/docs/asyncnet.html#recvInto,AsyncSocket,pointer,int

I think it would make sense to visually separate safe and unsafe procedures under two different headings. I think discouraging the use of unsafe procedures is a good idea.

**Comment by dom96** [comment]
Are you going to close all issues that nobody is working on?

> How would the docgen know.

Simple:

* Does the function either take or return a `ptr`? if so then it's unsafe.

**Comment by alehander42** [comment]
That's not a very good definition of safe IMO: can other functions segfault? yes, do we have a way to always detect that? not really

**Comment by timotheecour** [comment]
> That's not a very good definition of safe IMO

indeed (would lead to both false positives and false negatives)

D has concept of `@safe`  `@trusted` and `@system` as explained here https://dlang.org/spec/memory-safe-d.html 
In the D implementation, It leads to using a proliferation of attributes in code that is painful to use
Unless Nim has a better way to handle it with minimal amount of required attributes (eg full program analysis) (eg similar to effect system or exception tracking or some pragmas), it wouldn't be worth it

**Comment by krux02** [comment]
This isn't an issue, it is just an opinion. People can agree to it or not. But I think if nobody is active in issues like these anymore, yes they should be closed. There is no point to keep them around.

**Comment by Araq** [comment]
Here is what to do: Add an "UNSAFE!" scream to the procs we think require it.
