### ISSUE TITLE
Strange error when I trying to call socket.close()

### ISSUE THREAD

**Issue by r3d9u11** [nim-lang/Nim#7380]
Hi. I have a strange error with method "close" of async socket. It happens if socket was created from one thread, but method called from second thread (yes, I know that it is not a good practice, but...):
```
import asyncdispatch, asyncnet, threadpool, strutils, locks
from os import sleep

type
  MyObj = ref object
    sock: AsyncSocket

var olock: Lock
var obj {.guard: olock.}: MyObj

initLock(olock)

proc someThread() {.gcsafe.} =
  {.locks: [olock].}:
    obj.new()
    obj.sock = newAsyncSocket()
    obj.sock.bindAddr(Port(12345))
    obj.sock.listen()

spawn someThread()
sleep 500

{.locks: [olock].}:
  obj.sock.close()
```
Exception:
```
undefinedTraceback (most recent call last)
main.nim(24)             main
asyncnet.nim(619)        close
asyncdispatch.nim(966)   closeSocket
selectors.nim(135)       unregister
tables.nim(151)          []
Error: unhandled exception: key not found: 3 [KeyError]
```
[vscode example (zip)](https://github.com/nim-lang/Nim/files/1829642/thr_spawned_socket.zip)
(also I had "key not found: 18", ...)

What key? Any ideas what does mean this exception? 
Is it possible to get round this excepted behavior and save a current parallel and lite 
structure of application?

Thanks!

**Comment by dom96** [comment]
> It happens if socket was created from one thread, but method called from second thread (yes, I know that it is not a good practice, but...)

I'm afraid there is no "but" here, you simply cannot do that. Each thread has its own event loop, that's the reason this error happens.

**Comment by r3d9u11** [comment]
@dom96 is there lite way to call this method from thread-owner?

**Comment by r3d9u11** [comment]
@dom96 well, I think this question for another theme or discussion.
Thanks for your clarification!

**Comment by dom96** [comment]
You'd have to communicate between the threads using channels for example.

**Comment by r3d9u11** [comment]
@dom96 I tried to escape from Channels, because [it looks so hard and huge (for my views)](https://forum.nim-lang.org/t/3669/1#22886).

I'm wondered, that I can't just use shared memory and mutex for this simply task (because this task - it's a workaround for another task :face_with_head_bandage: ) :( Think it's due to GC. I'm did some experiments with initialization aysncsocket into shared memory directly, but had no success yet: access to methods of socket did raised exception. Something like a:
```
type
  MyObj = ref object
    sock*: ptr AsyncSocket

proc initializer*[T](dest: pointer) {.inline.} =
  var prototype: T
  copyMem(dest, addr prototype, sizeof(prototype))

proc allocObject*[T](): ptr T =
  result = cast[ptr T](allocShared0(sizeof(T)))
  initializer[T](result)
...
proc someThread() =
  {.locks: [olock].}:
    obj.sock = allocObject[AsyncSocket]()
    obj.sock[].bindAddr(Port(12345))
    ...
...
```

As I understand Channels (Actors before) it's a main conception for parallel application in Nim, right? And as I see, only this conception can works correctly in Nim (at least in this problem), even if object was declared in shared memory - I can't just access for it directly for another thread.

Does I'm understand it correctly?
