### ISSUE TITLE
Very bizarre quote bug

### ISSUE THREAD

**Issue by alehander42** [nim-lang/Nim#7381]
One of the strangest bugs I've seen with Nim

```nim
import macros

macro a*: untyped =
  let name = newLit("name")
  result = quote:
    var b {.importc: `name`.}: int
  echo result.treerepr

a()
```

```
VarSection
  IdentDefs
    PragmaExpr
      Sym "b"
      Pragma
        ExprColonExpr
          Ident ident"importc"
          Ident ident"2"
    Sym "int"
    Empty
```

You can see instead of a string, we get ident 2 for importc

If you add more importc with quote, you get 3 etc

So I guess it's some kind of index instead of node issue

obviously one can use constant for now ( @zah gave me a workaround:)

```nim
import macros

macro a*: untyped =
  let name = newLit("name")
  let x = ident("x")
  result = quote:
    const `x` = `name`
    var b {.importc: x.}: int
  echo result.treerepr

a()
```

**Comment by jangko** [comment]
deep inside `quote:`, it generate something like this:

```Nim
template test(x, y: untyped): typed =
  var b116013 {.importc: x.}: int
  var c116015 {.importc: y.}: int
  
test("abc", "def")
```

turn out, this is a template vs importc pragma problem.
inside template, importc pragma somehow cannot recognize template param.
I am curious if this also affecting other pragmas inside template

**Comment by Araq** [comment]
> I am curious if this also affecting other pragmas inside template

That is a feature. Inside templates, pragmas are kept as they are. We can probably change that, the tests will tell us where the problematic cases are.

**Comment by krux02** [comment]
This has been reported multiple times. 

I am closing this in favor of  #10326
