### ISSUE TITLE
Add testing and documentation for more modules that can run in VM - nimscript, compile time

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#7383]
Per some brute force [analysis](https://gist.github.com/genotrance/cc575b760428289586e141f2ef64c3ba), it's clear that several Nim modules (67) can potentially work in the VM. In fact, if you see [test_nimscript.nims](https://github.com/nim-lang/Nim/blob/devel/tests/test_nimscript.nims), there's at least 17 modules that are known and routinely tested.

However, the [documentation](https://nim-lang.org/docs/nims.html) only shows 4 modules as officially expected to work.

The goal of this issue is to track the work associated with doing the following in order:-
- Add (if not already present), VM test cases for all procs of the 4 documented modules
- Add VM test cases for all procs of 14 additional modules already in test_nimscript.nims
- Expand addition of VM test cases for the balance 48 modules

As PRs for the test cases are accepted, the nims documentation will also be updated to publish those modules as available.

If a particular proc in one of these modules doesn't work as expected in the VM, there are multiple options:-
- Don't add that module to the list at all since multiple such procs or minimal value in enabling it
- Open issues to fix proc in VM depending on validity, feasibility and value and then add module when issues are fixed
- Add the module but with a proc pragma that marks that specific proc as unavailable in the VM so that they won't be usable in nimscript and are automatically documented that they won't work in VM. This is contingent on this new pragma functionality being added to the Nim VM and corresponding docgen functionality.

As an aside, it's also useful to add another pragma or equivalent that marks a module as VM ready. This could help whitelist such modules so that availability is clear to end user.

There are more fundamental limitations of the VM such as memory management or missing FFI that prevent several other modules from even loading. Note the failures [encountered](https://gist.github.com/genotrance/cc575b760428289586e141f2ef64c3ba) in 0.18.0. These may be circumvented some time in the future but will be handled case by case after the existing list of modules are enabled.

**Comment by genotrance** [comment]
Notifying @Araq and @FedericoCeratto since they have already worked on this.

**Comment by akavel** [comment]
As to the following: 

> - Add (if not already present), VM test cases for all procs of the 4 documented modules
> - Add VM test cases for all procs of 14 additional modules already in test_nimscript.nims

**Where should the "VM test cases for all procs" be added?** In [test_nimscript.nims](https://github.com/nim-lang/Nim/blob/devel/tests/test_nimscript.nims), I only see a list of imported modules, no tests for specific procs. Is it enough if the tests are present in the `when isMainModule:` blocks in the imported files? I guess it has to be done in some other way, as during import, I'd expect `isMainModule` is false/undefined?

Second question: **how do I then run the VM test cases for the procs?**

I'm particularly interested in doubling down on VM tests, so that [my pet issue in VM](https://github.com/nim-lang/Nim/issues/11761) hopefully gets some new insights as to why it fails, and thus hopefully has its chances of being resolved increased.

**Comment by genotrance** [comment]
`isMainModule` procs will be called with `nim c`.

There are some nims files in the tests folder. See [this](https://github.com/nim-lang/Nim/blob/devel/tests/tools/tnimscriptwithmacro.nims) for an example.

Three ways to do this:
- Using above method, create/duplicate a whole bunch of tests
- Enable some method in testament to run existing code in `nim c` and `nim e` with some flag
- Expand [testament](https://github.com/nim-lang/Nim/blob/devel/testament/categories.nim#L401) to run `isMainModule` tests with `nim c` and `nim e`

Latter two will require copying and renaming the file from .nim to .nims and probably a bunch of edits since a lot of tests might not work due to VM limitations. I think best is to start with the first option and expand when it makes sense.

**Comment by genotrance** [comment]
The documentation is better off, closing.
