### ISSUE TITLE
A easy standart way to disambiguate var and non-var arguments?

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#7384]
For now such code works:
```nim
proc p(a: var int or int) =
  template t = a = 7
  when compiles(t()):
    a=7
  # do yet smth wit `a`...

var x = 3
p[var int] x
echo x  # => 7

let y = 3
p y
echo y  # => 3
```
Quite long and non-readable.
I turns out a more general solution is possibble:
```nim
template isVar(x: typed): bool = compiles(reset(x))
```
which can be used just as ``when a.isVar:``.
Shouldn't it be in StdLib? Or maybe there is already some standart and easy way?

**Comment by mratsim** [comment]
Linked to https://github.com/nim-lang/Nim/issues/7366 in my opinion.

**Comment by andreaferretti** [comment]
Why not use overloads? https://github.com/unicredit/cello/blob/master/cello.nim#L487-L492

**Comment by Leu-Gim** [comment]
@andreaferretti: I meant cases when branches differ not much, when most part of the proc is the same for both branches, so `when`'s are more applicable. It's possible then to separate the common part into a template and include that in 2 overloaded procs, yet it's again too much burden for such a little thing, yet there can be several common and differing parts interwoven.

**Comment by Leu-Gim** [comment]
@mratsim: Yes, I too tried to get that info from AST.

**Comment by zah** [comment]
This code can be as simple as that:

```nim

**Comment by Leu-Gim** [comment]
Thanks, **zah**, already better than with ``compiles``.

**Comment by Araq** [comment]
I consider this issue solved but don't want to add it to the stdlib, it doesn't seem to come up very often.
