### ISSUE TITLE
Parser bug: some type classes cant be aliased

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#7391]
These should all be valid, but are rejected by the parser:
```nim
type
    R = ref
    V = var
    D = distinct
    P = ptr
```

**Comment by andreaferretti** [comment]
I am not sure they should be valid, I would use

```nim
type P[T] = ptr T
```

and so on

**Comment by GULPF** [comment]
That's not the same thing, since it requires a generic argument. Here's a better example:
```nim
var x: int
echo x is enum  # Valid
echo (x is ref) # Valid
echo x is ref   # Parser error
```

**Comment by andreaferretti** [comment]
It requires a generic argument because you are dealing with generic types :-)

I don't understand what `echo x is ref   # Parser error` has to do with your previous examples

**Comment by GULPF** [comment]
> I don't understand what `echo x is ref # Parser error` has to do with your previous examples

Because it's the same parser bug as the original example. They are not generic types, they are type classes, in the same sense that `enum` and `proc` are type classes.

[Here's a usage of the `ref` type class in the system module](https://github.com/nim-lang/Nim/blob/abfcbaa74c8951b1df573c79f67be65af15e6c22/lib/system.nim#L209).

**Comment by andreaferretti** [comment]
Well, of course they are type classes, they are just ones that are derived from generic types. For every generic type `F[A]` you have the type class `F` which is essentially `F[A] for some A`.

Still, I am not sure that your original example should be valid, but I don't care much one way or the other

**Comment by GULPF** [comment]
> Well, of course they are type classes, they are just ones that are derived from generic types. For every generic type `F[A]` you have the type class `F` which is essentially `F[A] for some A`.

Oh, I forgot about that rule. That makes sense. However, it is possible to alias other type classes derived from generic types, so `ref`/`var`/`distinct`/`ptr` are still exceptions to the rule:
```nim
type
  G[A] = object
  T = G
```
