### ISSUE TITLE
Feature request: copy dir function in nimscript

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7393]
I don't see a cpDir function in Nimscript in both [the docs](https://nim-lang.org/docs/nimscript.html) and [source code](https://github.com/nim-lang/Nim/blob/2a8d2ad4cde1c942a9dbc44598f65d4acf1e0aa6/lib/system/nimscript.nim).

Trying to use os didn't work:

```nim
from os import copyDir

copyDir("./foo/", "./bar/")
# Error: cannot 'importc' variable at compile time
```

**Comment by cooldome** [comment]
here is an example how it can be implemented:
https://github.com/nim-lang/Nim/pull/7284

**Comment by genotrance** [comment]
I'm planning on adding the following procs to `nimscript` with the equivalent proc name from the `os` module.
- cpDir() = copyDir()
- mvDir() = moveDir()
- pwd() = getCurrentDir()
- where() = findExe()
