### ISSUE TITLE
Strange behavior of stdin with imported threadpool

### ISSUE THREAD

**Issue by r3d9u11** [nim-lang/Nim#7396]
Hi. I have a strange behavior of stdin with imported threadpool:
main.nim
```
import threadpool
import strutils

var cmd = 0x00
while (cmd != 0x01):
  stdout.write("> ")
  var buff = stdin.readLine()
  if buff.len < 1: continue
  echo ">>>>>> '" & buff & "'"
  cmd = parseInt(buff)
```
result output:
```
Running executable
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff72e2700 (LWP 15293)]
[New Thread 0x7ffff70e3700 (LWP 15294)]
[New Thread 0x7ffff6e64700 (LWP 15295)]
[New Thread 0x7ffff6be5700 (LWP 15296)]
> >>>>>> '9-thread-info'
Thread 1 "main" hit Breakpoint 1, NimMainModule () at Prog-Experiments/Nim/misc/stdin_bug/src/main.nim:10
10	  cmd = parseInt(buff)
```
![1](https://user-images.githubusercontent.com/15020827/37817986-abe7f4c6-2e89-11e8-9aca-0f4a8c1ec1de.png)

Where from `XXX-thread-info`? (this trouble hides if remove or comment `import threadpool`)

**Comment by dom96** [comment]
Can't reproduce on macOS.

Also, have you tried it in a standalone terminal? Maybe VS code is doing something weird?

**Comment by r3d9u11** [comment]
@dom96 yes, think it must be moved to vscode ([here](https://github.com/pragmagic/vscode-nim/issues/85) is another troubles with std IO and vscode)
