### ISSUE TITLE
`man nim` : No manual entry for nim

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7401]
is there no man page for nim? would be nice to have
```
brew install nim

which nim
/Users/timothee/homebrew//bin/nim

echo $MANPATH
/Users/timothee/homebrew//share/man:/Users/timothee/homebrew//share/man:

man nim
No manual entry for nim
```

**Comment by twetzel59** [comment]
You're right. I'm curious what others think about this. I've never made a man page before, but I don't imagine it's complicated...

What do you imagine for the content? Should it be the ``nim --help`` info structured as a man page, or should a more detailed document be written?

**Comment by Araq** [comment]
Nim also lacks a ``.chm`` help file for Windows 95.

**Comment by FedericoCeratto** [comment]
The official Debian package provides manpages for nim, nimble, nimgrep, nimsuggest
They are autogenerated from the help commands. You can reuse them in "brew" and other.

**Comment by timotheecour** [comment]
indeed, for autocompletion and man page generation this works: https://github.com/c-blake/cligen/issues/23#issuecomment-381294245
just a matter of integrating these in nim distributions (incl homebrew formula)

**Comment by Araq** [comment]
Work on it or let it be, but I need the number of issues to go down.
