### ISSUE TITLE
finding number of nim packages can be confusing

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7410]
This came up in https://github.com/timotheecour/D_vs_nim/issues/3

for someone not very familiar with nim trying to figure out how many packages does nim have, things can be confusing:

https://nimble.directory/packages.xml shows only ~194 packages but https://github.com/nim-lang/packages shows ~640 packages

it's made worse by the fact that https://github.com/nim-lang/Nim/issues/7400 still prevents someone browsing https://nim-lang.org/docs/lib.html from seeing packages, and the fact that https://nimble.directory/ doesn't show the total number of packages.

https://nimble.directory/packages.xml
shows:
```
<description>New and updated Nim packages</description>
    <link>https://nimble.directory/packages.xml</link>
    <lastBuildDate></lastBuildDate>
    <pubDate></pubDate>
    <ttl>3600</ttl>
```
but doesn't specify what it means by `new and updated`; 

how about:
* specify total number of packages in https://nimble.directory/ (or maybe total + total new since <date>), eg as done in https://code.dlang.org/ which shows `Displaying results 1 to 21 of 1250 packages found.`

* change description in https://nimble.directory/packages.xml to show: `New and updated Nim packages since <date>`

**Comment by data-man** [comment]
nimble.directory isn't Nim-lang's project.

https://github.com/FedericoCeratto/nim-package-directory/issues

**Comment by timotheecour** [comment]
ok, closing this and opening https://github.com/FedericoCeratto/nim-package-directory/issues/7
