### ISSUE TITLE
Ambiguous call error when it's not

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7416]
```nim
type
  Foo[T] = object
  IntFoo = Foo[int]
  OBJORTUP = object|tuple

proc bar(b: object|tuple) = discard # Change argument type to `OBJORTUP` to make it work
proc bar(b: IntFoo) = discard

var f: IntFoo
bar(f)
```
```
test.nim(10, 4) Error: ambiguous call; both test.bar(b: object or tuple)[declared in test.nim(6, 5)] and test.bar(b: IntFoo)[declared in test.nim(7, 5)] match for: (Foo[system.int])
```

EDIT: Changed `var f: Foo[int]` to `var f: IntFoo` for better clarity.

**Comment by andreaferretti** [comment]
It definitely seems ambiguous to me

**Comment by yglukhov** [comment]
It's not really. Since `IntFoo` is a concrete type, it should be preferred over a generic type `object|tuple`. E.g. the following sample works:
```nim
type
  Foo[T] = object
  IntFoo = object
  SomeObj = (int, int)

proc bar(b: object|tuple) = discard
proc bar(b: IntFoo) = discard

var f: IntFoo
bar(f)
```

**Comment by andreaferretti** [comment]
Are concrete types always preferred over generic ones? Asking because I am not sure, I always try to avoid ambiguity, so I may never have noticed.

Makes sense, but in general I think that introducing rules for overloading precedence tends to create complexity which is most often not needed

**Comment by yglukhov** [comment]
>> Are concrete types always preferred over generic ones?

Yep. [Overloading resolution](https://nim-lang.org/docs/manual.html#overloading-resolution)

**Comment by andreaferretti** [comment]
Now that I think of it, I have probably used that the compiler selects the most specific overload afew times, if only to distinguish `T` from `var T`

**Comment by ringabout** [comment]
It works since Nim 0.20.0

**Comment by ringabout** [comment]
This could be closed now.
