### ISSUE TITLE
create a nim slack team

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7418]
(also asked on https://www.reddit.com/r/nim/comments/6jqsjx/anyone_interested_in_having_a_nim_slack_team/ but that question was closed for commens)

In D we have a forum and IRC, but after slack was added it became very popular and a lot of discussions happen there now.
In particular the channels and threads are a neat way to organize discussions as opposed to having a single channel and single thread. Also slack can support IRC integration IIRC

Lots of people use slack (eg at work) and would make switching back and forth bw nim slack and other team slacks easy.

**Comment by data-man** [comment]
Welcome to [gitter.im/nim-lang/Nim](https://gitter.im/nim-lang/Nim) ! :)

**Comment by timotheecour** [comment]
I'm aware of that; however I miss many of the functionalities in the more popular, widely used slack:
* anyone can create channels, they're low friction and good to organize conversations around themes; having just 1 chat room just results in noise
* threads: likewise, allows threaded conversations to easily scope discussions and make them easy to follow

take a look at the D slack to see how well these work (I can send invite if needed)

**Comment by data-man** [comment]
Why all your proposals look like "do as in D"?

**Comment by timotheecour** [comment]
I'm much more familiar with D and interested in seeing whether nim would be a good fit for future my next projects instead of D ; besides it's always a good idea to borrow/steal features and tools from other languages (see also https://github.com/timotheecour/D_vs_nim/ to track these)

**Comment by mratsim** [comment]
Unfortunately Slack will close its IRC integration on May 15th: https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP.

Also, we already have [Discord](https://discordapp.com/), [Gitter](https://gitter.im/) and [Matrix](https://matrix.org/blog/home/) bridges with IRC. We can also add #nim-foo, #nim-games, #nim-embedded like what was done for #nim-offtopic (though it's not as easily discoverable as on Slack).

On another note, Sketch, Bootstrap, React, Node discussion are also happening a lot on [Spectrum](https://spectrum.chat/).

In any case, whatever we do I think the first requirement is a Gitter, IRC, Matrix and Discord bridge.

**Comment by Yardanico** [comment]
@mratsim `matterbridge` is on of the best (if not the best) solutions for making bridges between different networks. It supports Gitter, IRC, Telegram, XMPP, Matrix, Discord and much more

**Comment by dom96** [comment]
We already have a Slack team. It's just a case of providing a way for anyone to join and a bridge between Slack<->IRC

**Comment by timotheecour** [comment]
@dom96 do you mind sending me an invite at timothee DOT cour2 AT gmail DOT com ?

**Comment by dom96** [comment]
It's just me, @Araq and @zah in there currently. It's our little chat room so I'll have to discuss it with them first.

**Comment by alehander42** [comment]
@timotheecour still, Slack also have some problems: 

Too many threads can also lead to fragmentation, you have a limited history for unpaid customers, and I can't see how easy would the slack threads map to gitter/irc

**Comment by krux02** [comment]
Well I close this as rejected, slack seems to be the wrong solution for open source projects. A slack bridge is still very welcome as all other forms of bridges to other chat platforms.

**Comment by genotrance** [comment]
I have my own personal slack bridge I use for my account using matterbridge. It would be nice to have an official bridge.

I had proposed bridging the Telegram group in the past but everyone wasn't as receptive to the proliferation of bridges. I don't see the difference in 3 vs 8 but that's just me.

**Comment by timotheecour** [comment]
* @genotrance could you please share some details on how to set it up?
can I read/write to nim IRC channel using slack?
can I search nim IRC channel msgs using slack?

* channels and lack of threads is the number 1 thing I'm missing when using gitter compared to slack; it results in very fragmented threads, harder to follow / search, and overall it's less efficient to use. Is there any way to use channels with the tools we're using?

**Comment by timotheecour** [comment]
@genotrance  thanks! I'm running into issues, eg:

[0000]  INFO irc:          Connecting chat.freenode.net:7000
[0002] ERROR irc:          disconnect: error: closing connection: SASL authentication failed

I try putting the username and password I use when connecting to https://webchat.freenode.net/?channels=nim 
eg: if I populate fields nickname and username with bob, and password with myawesomepassword here:
![image](https://user-images.githubusercontent.com/2194784/47683583-3e7c3800-db8d-11e8-8ab2-b0b9950791aa.png)

putting these 3 fields in Nick, NickServNick and NickServPassword results in `disconnect: error: closing connection: SASL authentication failed`

* is `Password=""` correct above?
* are the only fields I need to change marked as `set as needed` ?

**Comment by genotrance** [comment]
Makes no sense why it doesn't work. Probably try removing the password=""? 

Anyway, best to check out the sample toml for guidance.

https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample

You could also just try nickserv auth rather than sasl. That's what I used to do until I ran into the following issue. 

https://github.com/42wim/matterbridge/issues/482
