### ISSUE TITLE
[search] nimgrep option --machine_readable to allow integrating with other tools

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7428]
I'd like to have an nimgrep option --machine_readable to be easily parsable by a program, eg:

```
file:line:col:nb_bytes_match:match:nb_bytes_line:line
```
which would print results 1 per line with all available context, eg:
```
lib/system.nim:1586:3:4:repr:100:*[T](x: T): string {.magic: "Repr", noSideEffect.}
```

currently it's tricky to use (and filter results via grep) because the context (file) is not shown in each line, eg:
```
lib/system.nim
  1586: proc repr*[T](x: T): string {.magic: "Repr", noSideEffect.}
  1586: proc repr*[T](x: T): string {.magic: "Repr", noSideEffect.}
```

so it's hard to filter via cmd line eg grep.

this would enable something like:
```
nimgrep -w --machine_readable --ignoreStyle "$1" **/*.nim| grep -E '\b(iterator|proc|template|macro) '
```

## links
https://github.com/nim-lang/Nim/issues/7419

**Comment by Araq** [comment]
We have ``nimsuggest`` for editor integration.

**Comment by Araq** [comment]
This was implemented with ``--oneline``.
