### ISSUE TITLE
Missing documentation for asyncfutures

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#7438]
https://nim-lang.org/docs/asyncfutures.html

I would provide a PR, but I am not sure what is there to do - isn't the documentation for the stdlib auto-generated from the modules themselves?

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/blob/devel/web/website.ini#L31 :)

**Comment by andreaferretti** [comment]
https://github.com/nim-lang/Nim/pull/7445

For these simple changes should I just commit to devel next time or do you prefer a PR anyway?

**Comment by Yardanico** [comment]
@andreaferretti this issue is about asyncfutures, but in your PR you add asyncstreams, is that correct?

**Comment by andreaferretti** [comment]
@Yardanico D'oh, you're right - in fact I needed both. I have added a commit with asyncfutures as well :-)
