### ISSUE TITLE
Can not print chinese words on windows command line

### ISSUE THREAD

**Issue by xland** [nim-lang/Nim#7441]
code:
echo("你好，世界！")

output:
浣犲ソ锛屼笘鐣岋紒

（out put is unreadble words）

windows 10，
nim-0.18.0

**Comment by dom96** [comment]
Followed this? https://stackoverflow.com/a/388500/492186

**Comment by xland** [comment]
Why go-lang/rust-lang do not need to do this manually?

**Comment by dom96** [comment]
Good question. Perhaps they run this command in the background? or maybe they perform some other trick? If you could find out that would be great :)

**Comment by xland** [comment]
Sorry,I can not find out the reason.
I think it has something to do with the code file's encoding.
ANSI or utf-8

**Comment by lightness1024** [comment]
it works correctly on linux. Note that on windows, batch (.bat) files has the same problem, try to echo your string in an utf-8 encoded .bat, it will behave the same. To get it to reasonably work, maybe you need to same your .nim file in little endian utf16 without BOM, I think that's the format windows expect. The console can be switched to accept utf8 but it's not supported and very buggy, not recommended at all.

**Comment by Yardanico** [comment]
@lightness1024 no, no, no! You SHOULDN'T save .nim files in any other encoding than UTF-8!

**Comment by xland** [comment]
This is a big problem for Chinese,Japanese,Korean users.

**Comment by data-man** [comment]
@xland 
Try this:
```nim
proc getACP(): uint {.stdcall, dynlib: "kernel32", importc.}

proc getConsoleCP(): uint {.stdcall, dynlib: "kernel32", importc.}
proc setConsoleCP(cp: uint): int32 {.stdcall, dynlib: "kernel32", importc.}

proc getConsoleOutputCP(): uint {.stdcall, dynlib: "kernel32", importc.}
proc setConsoleOutputCP(cp: uint): int32 {.stdcall, dynlib: "kernel32", importc.}


var
  acp = getACP()

# or try:
# acp = 65001
  ccp = getConsoleCP()
  cocp = getConsoleOutputCP()

setConsoleCP(acp)
setConsoleOutputCP(acp)

echo("你好，世界！")

setConsoleCP(ccp)
setConsoleOutputCP(cocp)
```
I didn't test in Windows.

**Comment by lightness1024** [comment]
instead of hacking the user's bash session as we established it was dangerous already, it would be better to convert the encodings of the string. if .nim must stay as utf8, then just do something along the likes of:
```nim
import encodings
echo(convert("你好，世界！", destEncoding: getCurrentEncoding(), srcEncoding="utf-8")
```

**Comment by Yardanico** [comment]
@lightness1024 I generally agree with you, but it shouldn't be called "utfEcho" because it's windows console's problem that it doesn't have unicode by default (and echo can easily print unicode).

**Comment by lightness1024** [comment]
I admit that I couldn't find a good name. I stuttered on the name but you've got to get on with your life at some point, so I picked whatever was short enough. what name would be good for that ?

**Comment by siliconvoodoo** [comment]
![image](https://user-images.githubusercontent.com/25970839/38348528-5b5a9abe-38dd-11e8-9cf3-56eec0b320bd.png)
I'm getting this on my japanese windows. Which is to be expected, 你 is purely chinese and must not exist in JIS.

If I use `chcp 65001` the output (of simple echo) is completely blank (a newline).
And finally, If I use `utfEcho` on a chcp console, I get:
![image](https://user-images.githubusercontent.com/25970839/38348545-78729660-38dd-11e8-98e3-33416ac47b41.png)

**Comment by siliconvoodoo** [comment]
@data-man I tried your code, after adding some `discard` to get it to build, it outputs the exact same garbage than "raw echo, raw console" case above.

**Comment by Araq** [comment]
This is supposed to be supported via ``--define:nimSetUtf8CodePage`` during compilation. Sadly, it doesn't work and I don't know why. On my Windows 10 machine I cannot get it to produce correct output, maybe my fonts don't support it? Strange.

**Comment by siliconvoodoo** [comment]
I just tried, and using `--define:nimSetUtf8CodePage` behaves exactly the same as the `chcp 65001` case above, which if people read [stackoverflow ](https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line/388500#comment18773451_388500)would be aware is a bad thing to do.

**Comment by siliconvoodoo** [comment]
![image](https://user-images.githubusercontent.com/25970839/38351489-a1747c7e-38ea-11e8-88c1-ace229f0cf21.png)

**Comment by siliconvoodoo** [comment]
Last idea, I'm coming back on my original suggestion, windows is made to work in some kind of 1993 version of UCS16. Using code pages (ACP stuff) is not ideal, and results in the limitation we observe here with 你 not being displayable on my JIS locale. Convert should provide a way to convert to UCS16 and not limit itself to those MBCS code pages.

**Comment by siliconvoodoo** [comment]
https://github.com/khchen/winim/blob/master/winim/winstr.nim
anything involving `WideCharToMultiByte(CP_UTF8...` must be doing it right. I'll try

**Comment by dom96** [comment]
Thank you for your thorough investigation @siliconvoodoo :)

Now how do we fix this bug?

**Comment by xland** [comment]
Thank you all.
I am on my QingMing holiday.
I'll try your suggestions a few days later.

**Comment by xland** [comment]
how about this issue's progressing

**Comment by Araq** [comment]
Nobody knows how to fix it...

**Comment by xland** [comment]
How about this issue's progressing?

**Comment by mjoud** [comment]
This is indeed annoying. [Go](https://github.com/golang/go/blob/1705962cf976a001bb9929146e5690a957ed630e/src/internal/poll/fd_windows.go#L702), [LLVM](https://github.com/llvm-mirror/llvm/blob/dc281ceff88bbc1102d38b43facfe2b2a35bfb8f/lib/Support/raw_ostream.cpp#L619) and [Python](https://github.com/python/cpython/blob/e5024517811ee990b770fca0ba7058742d00e032/Modules/_io/winconsoleio.c#L958) all use `WriteConsoleW` for writing to the windows console.

**Comment by dom96** [comment]
Then we should do the same. Please PR and test it well :)

**Comment by Araq** [comment]
Aha, that's what to use, interesting. :-)

**Comment by Araq** [comment]
This has been fixed afaict.
