### ISSUE TITLE
v0.18 - regression - string indexing

### ISSUE THREAD

**Issue by ivan1** [nim-lang/Nim#7444]
Following code does not work in v0.18, but succeeds in ~ v0.13:

    let x = "abcdefg"
    doAssert x[^3 .. ^0] == "efg"

Thanks!

**Comment by andreaferretti** [comment]
It seems to be a problem about the null terminator of a string,

```nim
let x = "abcdefg"
doAssert x[^3 .. ^1] == "efg"
```

works

**Comment by narimiran** [comment]
Also

```nim
let x = "abcdefg"
doAssert x[^3 .. ^0] == "efg\0"
```

works, and to me it looks like a correct behaviour.

**Comment by dom96** [comment]
Yeah, I'm also leaning towards this being correct behaviour now.

**Comment by ivan1** [comment]
We are true programmers and so we start counting at zero: for example, for s="abcdefg" input string we type s[0] to refer to the first character. Now, what we would type to refer to the last?  s[^1] or s[^0] ?

**Comment by narimiran** [comment]
@ivan1 We would/should type `s[^1]` to refer the last element.

Explanation:  
Think of `^x` as a shortcut for `s.len - x`, and you'll see that the last index should indeed be `^1`, which is similar to another zero-based indexing language - Python, where you have negative indices to count from the end, and the last element has an index `-1`.  
Or to put it differently, `^1` is what the most programmers would expect to be the index of the last element, and we shouldn't introduce introduce something confusing which would lead to many "off by one" errors.

**Comment by Araq** [comment]
This is correct behaviour now and you're supposed to use ``s[^1]`` (that is nothing new btw).
