### ISSUE TITLE
[WONTFIX] already-clicked links in generated doc are undistinguishable from normal text

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7452]
(i'm on OSX, using chrome)

example:
in
https://nim-lang.org/docs/lib.html
after clicking on `packages repo` (https://github.com/nim-lang/packages)
and refreshing https://nim-lang.org/docs/lib.html I see:

![image](https://user-images.githubusercontent.com/2194784/38157736-6c7d7b98-343e-11e8-902f-77e2fab5f964.png)

the `packages repo` shows up as normal text (at least very hard to distinguish from normal text, at least for me)

presumably, a simple color scheme / css change would fix this?

**Comment by trustable-code** [comment]
I think you talk about the CSS rule "a:visited { color: #00334d; }" in https://github.com/nim-lang/Nim/blob/devel/config/nimdoc.cfg#L417 .
On my screen, it's no problem no to distinguish a visited link from normal text.

**Comment by Yardanico** [comment]
![default](https://user-images.githubusercontent.com/21169548/38161807-8cbbd256-34de-11e8-8783-97da49d1d116.png)
It's fine for me too

**Comment by mratsim** [comment]
Confirmed on OSX with Opera:

![2018-03-31_19-08-33](https://user-images.githubusercontent.com/22738317/38165643-f76f85ba-3516-11e8-8291-8867504b5ca0.png)

**Comment by dom96** [comment]
Feel free to change the colour for visited links to a pleasant purple :)

**Comment by narimiran** [comment]
This has been fixed.

**Comment by krux02** [comment]
This shows your are reall not showing any respect

 * This issue has been fixed. You could at least have tried if it is still valid.
 * This is an issues with many participants and upvotes. So it clearly matters.
 * You should close non important issus, for example this one https://github.com/nim-lang/Nim/issues/8879 where nobody would care.
