### ISSUE TITLE
Parameter of macros can't be evaluate at compile-time?

### ISSUE THREAD

**Issue by r3d9u11** [nim-lang/Nim#7464]
Hi. I've got exception:
```
macro init*(backend: static[int]): typed =
  when backend == 1: # excepted with message: "cannot evaluate at compile time: backend"
    discard
  else:
    discard

init 1
```
Parameters and result of the macros are evaluating before compilation, no?
Thanks.

**Comment by Yardanico** [comment]
@r3d9u11 you should use "if" instead of "when" because macro is already executed at compile-time

**Comment by data-man** [comment]
Change ```when``` to ```if```.

**Comment by r3d9u11** [comment]
thanks for hint, but I can't use if statement.

inside when statement I'm calling another macros, who doing import different packages. and it can be used only with when statement.

**Comment by data-man** [comment]
```nim
template init*(backend: static[int]): typed =
  when backend == 1: # excepted with message: "cannot evaluate at compile time: backend"
    discard
  else:
    discard

init 1
```

**Comment by r3d9u11** [comment]
@data-man many thanks, this works! I should use templates instead of macros in this task.
