### ISSUE TITLE
ambiguous call on `$` for uint8/uint16/uint32 range types

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7467]
Currently the following throws an ambiguous call:

```Nim
const
  Foo* = 0x200'u16
  Bar*    = 0xFFF'u16

type
  MyRange   = range[Foo .. Bar]

var a: MyRange
echo a
```
`Error: ambiguous call; both system.$(x: uint64)[declared in lib/system/repr.nim(28, 5)] and system.$(x: int)[declared in lib/system.nim(1898, 5)] match for: (MyRange)`
But  changing it to `var a: uint16` doesn't get an ambiguous call.

The workaround is straightforward:
```Nim
proc `$`(m: MyRange): string  {.inline.} =
  system.`$`(m.int)
```

But it would be better if range types didn't need special overloads for printing.
I suppose Nim is trying to find matching converters, found two for uint64 and for int and then is stuck in an ambiguous call.

**Comment by narimiran** [comment]
https://github.com/nim-lang/Nim/pull/10495 fixed it (and added tests for it in `tests/range/trange.nim`).
