### ISSUE TITLE
splitLines should have an option to keep newline

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7478]
same as in https://dlang.org/library/std/string/split_lines.html
eg how about:
```nim
iterator splitLines(s: string, keepNewline = false): string {..}
```

what's the simplest workaround in the meantime?

**Comment by Araq** [comment]
Append ``"\p"``? Why are newlines important to keep?

**Comment by PMunch** [comment]
Well, there is overhead in cutting away newlines just to immediately add them back again. And if the last line didn't end with a newline you would need to have a condition to add only if it existed in the original input. Would be easier to just have a keepNewline flag.

**Comment by lightness1024** [comment]
As explained here: https://msdn.microsoft.com/en-us/library/system.stringsplitoptions(v=vs.110).aspx
