### ISSUE TITLE
Strange output for tut2 exception reporting

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#749]
The tutorial says on exceptions that they can be logged with `repr(e)`. However, testing the following example:

``` nimrod
try:
  raise newException(EIO, "PEBKAC")
except:
  let
    e = getCurrentException()
    msg = getCurrentExceptionMsg()
  echo "Got exception ", repr(e), " with message ", msg
```

Outputs something rather opaque:

```
Got exception ref 0x10f4aa050 --> []
 with message PEBKAC
```

The `repr(e)` of the exception doesn't mention it is an exception or its type, so it's quite useless for debugging or logging.

**Comment by andreaferretti** [comment]
With latest Nim, the field `name` is not private anymore, so the above prints

```
Got exception ref 0x7f86c15a5050 --> [parent = nil,
name = 0x7f86c15a62a8"IOError",
msg = 0x7f86c15a6050"PEBKAC",
trace = 0x7f86c15a8050"Traceback (most recent call last)\10"
"in.nim(2)                in\10"
""]
with message PEBKAC
```

which is a little more informative (or one could just print `e.name`).

That said, it would be nice to add `$` for exceptions
