### ISSUE TITLE
[minor] `CC: file` messages during compilation should be Hints (so we can turn them off)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7493]
`CC: file` messages during compilation should be Hints (so we can turn them off)
* it's just more consistent to have these as Hints (almost everything else is)
* example use case: I'm writing a tool that calls nim via exec and I want to turn off these `CC: file` messages in output

**Comment by data-man** [comment]
Use nim --verbosity:0 c <file>

**Comment by Araq** [comment]
You implemented that with ``--hint[CC]:off``
