### ISSUE TITLE
deprecated modules don't show up as being deprecated in docs + other related points

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7494]
Several points:

- [x] https://nim-lang.org/docs/parseopt2.html doesn't show any mention of deprecated and yet parseopt2.nim shows  top-level `{.deprecated.}`
- [x] It was really not obvious that parseopt2 is deprecated in favor of parseopt given that suffix 2 seems to indicate its newer; this impression was also reinforced given that some spelling mistakes were corrected from parseopt to parseopt2 (eg: dected => detected)
- [x] parseopt2.nim mentions deprecated but makes no mention of what should be used in place; I saw the answer to that in https://forum.nim-lang.org/t/3654/1#22771 
- [x] how would we specify a deprecation message (eg "use parseopt instead") for such top-level deprecation so that it'd show up in deprecation compiler messages ? https://nim-lang.org/docs/manual.html#pragmas-deprecated-pragma is under-documented (as also mentioned in this comment: https://github.com/nim-lang/Nim/issues/7468#issuecomment-378170689)

**Comment by dom96** [comment]
IMO:

* ``deprecated`` pragma should support something like ``{.deprecated: {replacement: parseopt}.}``, or some other syntax to specify the replacement
* the doc gen should be able to generate an "in-your-face" banner at the top of a module which states that the module is deprecated.
* in general, we should stop relying on people writing text in the docs, which is what we have done for deprecations. I can easily mark a procedure deprecated, and the docs will not mention it unless I explicitly add a sentence to mention it, the doc gen should do this automatically (the ability of the doc gen to understand that it's a deprecation will also mean that we can style it better).

**Comment by timotheecour** [comment]
> deprecated pragma should support something like {.deprecated: {replacement: parseopt}.}, or some other syntax to specify the replacement
So we have:
`{.deprecated: [TFile: File, PStream: Stream].}` for types (see https://nim-lang.org/docs/manual.html#pragmas-deprecated-pragma)
`{.deprecated: "Use bar instead".} for procs` (undocumented, see https://github.com/nim-lang/Nim/issues/7468#issuecomment-377873314)
for anything else looks like we're stuck for now with just `{.deprecated .}

* It would be nice to have consistent syntax
* in some cases there is no easy symbol replacement (maybe they're not available anymore, or in a different module etc); in those cases a free form string should always be an option.

How about supporting these:
```nim
{.deprecated: "use module foobar instead" .} # new: always supported, in all contexts
{.deprecated: [TFile: File, PStream: Stream].} # still supported
{.deprecated: [TFile: File, PStream: Stream], "additional deprecation comment" .} # new
```

**Comment by data-man** [comment]
> are the [TFile: File, PStream: Stream] meant for tooling?

Yes, for Nimfix.

**Comment by dom96** [comment]
I don't think we should be using free-standing text. Mainly because the doc gen then has no ability to present it. If we explicitly specify a replacement module then the doc gen can create a link automatically to that module.

**Comment by data-man** [comment]
@dom96 

```{.deprecated: [TFile: File, PStream: Stream], "additional deprecation comment" .}```
Looks nice.
E.g.
```{.deprecated: [TFile: File, PStream: Stream], "Deprecated in v. 0.18" .}```

**Comment by dom96** [comment]
There are other pieces of meta data that we might want to include, you just demonstrated one: the version. We should come up with something more flexible.

**Comment by timotheecour** [comment]
still though, there will be cases where there's not direct symbol to symbol replacement; in this case a string telling user why the sybmol was deprecated and how to fix his code is the best thing we have. It won't be usable by tooling but it's better than not showing a deprecation message at all.

Eg:
"Foo moved to a nimble package bar"
"replace foo(a,b) by bar(b, a)"
"Foo not supported anymore"

**Comment by mratsim** [comment]
See also #6425 for suggested visual cues for deprecated proc

**Comment by narimiran** [comment]
I went through your list and managed to check every checkbox. Closing.
