### ISSUE TITLE
net.nim with SSL support is leaking memory

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#7498]
Offensive line:

```nim
    socket.sslHandle = SSLNew(socket.sslContext.context)
```

Maybe other places are leaking memory too.

**Comment by Araq** [comment]
never mind, it's freed in ``close``. For some reason I missed it.

**Comment by dom96** [comment]
Bah, so this ever present leak doesn't actually exist? :/

**Comment by Araq** [comment]
It does exist, maybe we don't call ``close`` everywhere properly (likely).
