### ISSUE TITLE
[minor] with --parallelBuild:1 , no file gets compiled apparently

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7502]
very odd:
```
nim c --listCmd --parallelBuild:1 -f -o:app -r foo.nim
```
shows no `clang -c ...` line in output (seems buggy)

with any other value of `--parallelBuild:`, it shows files getting compiled (as it should)

**EDIT**
NOTE: the file compiles/runs just fine, and if i add a new--nimcache value it does put all the files there, but just doesn't print anything (CC ... or clang -c ....), hence it's just a minor bug

**Comment by cheatfate** [comment]
@timotheecour which operation system you are using?

**Comment by dom96** [comment]
Are you sure this isn't just caching? Nim doesn't show the clang line if it doesn't have to recompile the code (because the files didn't change).

**Comment by timotheecour** [comment]
yes I'm sure, the `-f` flag is being used. Besides, I also tried with --nimcache:nimcache_new

**Comment by Araq** [comment]
Can't reproduce on my OSX.

**Comment by cheatfate** [comment]
@timotheecour do you use latest devel version? or you use previous releases of Nim?

**Comment by timotheecour** [comment]
I use `brew install nim`
nim --version
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise

**Comment by cheatfate** [comment]
@timotheecour please try latest devel version.

**Comment by timotheecour** [comment]
after `brew reinstall --HEAD nim`
```
nim --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 992300b30057e2b3b489b90fb0e7011607e3e8cf
active boot switches: -d:release -d:useLinenoise
```

same issue.

NOTE: the file compiles/runs just fine, and if i add  a new`--nimcache` value it does put all the files there, but just doesn't print anything (`CC ...` or `clang -c ....`), hence it's just a minor bug

**Comment by narimiran** [comment]
> NOTE: the file **compiles/runs just fine**, and if i add a new `--nimcache` value it does put all the files there, but just doesn't print anything (`CC ...` or `clang -c ....`), hence it's just a minor bug

Closing.

**Comment by nc-x** [comment]
@narimiran
I can agree with closing this issue because nobody can reproduce it, but the current reason does not justify closing it. Because a minor bug is a bug nonetheless.
