### ISSUE TITLE
Unit testing involving floats

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#7504]
I'm working on writing a geometry library right now and that involves all sorts of finagling with floating point numbers.  Now I was trying to test constructing a vector from a polar form:

```nim
  test "initVectorPolar()":
    let
      c = initVector(0, 2)
      d = initVectorPolar(2, PI / 2)

    check(c == d)
```

And the unit testing framework is giving me this:

```
[Suite] Vector Tests
    tests/vector.nim(25, 12): Check failed: c == d
    c was (x: 0.0, y: 2.0)
    d was (x: 1.224646799147353e-16, y: 2.0)
  [FAILED] initVectorPolar()
```

Python's `unittest` module has this nice little method called `assertAlmostEqual()` which is perfect for testing floating point "equality".  Can Nim's `unittest` module get something like this?

**Comment by Araq** [comment]
Since the epsilon in this code is specific to your needs, it shouldn't be in the stdlib:

```nim

const
  eps = 1.0e-7 ## Epsilon used for float comparisons.

proc `=~` *(x, y: float): bool =
  ## Compare two complex numbers `x` and `y` approximately.
  result = abs(x.re-y.re) < eps and abs(x.im-y.im) < eps
```

**Comment by andreaferretti** [comment]
In [neo](https://github.com/unicredit/neo) I define my own approximate comparison `~=` operator and then just use `check(c ~= d)`

**Comment by mratsim** [comment]
Idem in Arraymancer, I have my own epsilon and it even differs from checks to checks.

Furthermore parallel reduction on floating points are not deterministic so I don't get the same results on OpenMP/Cuda/OpenCL.

**Comment by Araq** [comment]
We don't have to support everything.

**Comment by cooldome** [comment]
I am using the following wrapper on top of standard ``check`` and finding rather convenient as epsilon is an argument:
```
template check_close*(epsilon: float, conditions: untyped): untyped = 
  template `=~` *(x, y: float): bool {.inject.} =
    abs(x - y) < epsilon
  check: 
    conditions
```

**Comment by planetis-m** [comment]
almostEqual in math is better suited for unit testing. So close?
