### ISSUE TITLE
`-d:identifier` is case insensitive (not partially case insensitive)

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#7506]
The rules for CT defines are different compared to other identifiers. Using `-d:foo` results in both `defined(foo)` and `defined(Foo)` being true. This causes this contrived example to fail:
```nim
# Compile with nim c -d:Foo="foo"
# Results in 'Error: unhandled exception: invalid integer: foo'
const foo {.intdefine.}: int = 0
const Foo {.strdefine.}: string = ""
```
Changing this would likely break a lot of code (e.g both `defined(JS)` and `defined(js)` are commonly used) and it's unlikely that it will cause any real issues, so it might be best to keep the special rules. In that case the behavior needs to be documented.

**Comment by Araq** [comment]
This is the intended behaviour, yes.
