### ISSUE TITLE
The experimental pragma and `.` code infection

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7526]
I was reading the manual and noticed that the Dot operators are under a ``{.experimental.}`` pragma, but the ``jsffi`` module exports a dot operator so if you import it your code will be infected with an experimental feature without you even knowing about it!

We need to solve this somehow.

**Comment by andreaferretti** [comment]
Mark the dot operator as not experimental? ;-)

**Comment by dom96** [comment]
Sure, we can do that. But this is a wider issue to all experimental features. After 1.0 experimental features will still be subject to change, so we can't allow users to use them accidentally.

**Comment by andreaferretti** [comment]
I understand, my comment was a little tongue in cheek. But still, the dot operator overloading is quite central to the jsffi module, which is all about providing nice interoperability with the untyped js model. The only other option I see is marking jsffi itself as experimental

**Comment by Araq** [comment]
No, the other solution is that the *usage* of an overloaded dot operator also needs to be done with ``{.experimental.}``. Note that I am not saying that we should do that, but it's a solution.

**Comment by hlaaftana** [comment]
Isn't that already the case, except the compiler gives a deprecated warning about the declaration? All that would have to be done is `{.push warning[Deprecated]: off.}` for the 3 experimental macros and remove `{.experimental.}`

**Comment by alehander42** [comment]
overloading `.` seems stable enough, probably it doesn't need the experimental tag anymore?

**Comment by GULPF** [comment]
Here's an idea: in addition to requiring the `{.experimental: "xxx".}` pragma for modules that uses experimental features, a compiler flag `--experimental:xxx` should be required to compile projects where such modules are imported. That way there is no way to way to accidentally use something experimental.

**Comment by Araq** [comment]
> Here's an idea: in addition to requiring the {.experimental: "xxx".} pragma for modules that uses experimental features, a compiler flag --experimental:xxx should be required to compile projects where such modules are imported. That way there is no way to way to accidentally use something experimental.

That won't well with indirect dependencies. Import 4 different Nimble packages and your command line contains ``--experimental:everything``. I think depending on the experimental feature, either require an .experimental at the declaration site or at the declaration site as well as the usage site.

**Comment by Araq** [comment]
We solved this by having ``manual_experimental.rst``. Which I now consider to be the best solution, all things considered. At least it doesn't cause splits of the language into dialects.
