### ISSUE TITLE
ioselectors allocate all possible file descriptors at start

### ISSUE THREAD

**Issue by aguspiza** [nim-lang/Nim#7538]
By default docker sets maximun file descriptors to 1048576. But other linux systems set it even higher, like 1500000 or more.

```newSelector[T]()``` is allocatting maxFD file descriptors at start. Internally Selector is using ```SelectorKey[T]``` objects to store FD info, each ```SelectorKey[T]``` is at least 32 bytes (40 for ```SelectorKey[AsyncData]```). So 40M just at start.

For a simple workaround that clamps maxFD to a defined or reasonable value:

```nim
proc newSelector*[T](): Selector[T] =
  # Retrieve the maximum fd count (for current OS) via getrlimit()
  var a = RLimit()
  if getrlimit(RLIMIT_NOFILE, a) != 0:
    raiseOsError(osLastError())
  var maxFD = int(a.rlim_max)
  doAssert(maxFD > 0)
  
  var epollFD = epoll_create(MAX_EPOLL_EVENTS)
  if epollFD < 0:
    raiseOsError(osLastError())
  
  when defined(maxFileDescriptors):
    const maxFileDescriptors {.intdefine.}: int = 132072
    if maxFD > maxFileDescriptors:
      maxFD = maxFileDescriptors
  
  when hasThreadSupport:
    result = cast[Selector[T]](allocShared0(sizeof(SelectorImpl[T])))
    result.epollFD = epollFD
    result.maxFD = maxFD
    result.fds = allocSharedArray[SelectorKey[T]](maxFD)
  else:
    result = Selector[T]()
    result.epollFD = epollFD
    result.maxFD = maxFD
    result.fds = newSeq[SelectorKey[T]](maxFD)
```
For a proper solution we should dynamically increase fds upto maxFD if we are requesting more than some initialFileDescriptors file descriptors

For more info: https://forum.nim-lang.org/t/3713/2#23258

**Comment by cheatfate** [comment]
This is not an issue, this is planned behavior. By default all Linux OS (Arch/Debian/Ubuntu) using not more then 32,768 file descriptors per process.
If you fill uncomfortable with this, you can adjust your process limits with `setrlimit(RLIMIT_NOFILE)` before you start using `Selector`.
Dynamic grow of array is not a solution, `ioselectors` was designed to avoid memory allocations.

**Comment by aguspiza** [comment]
Thanks, setrlimit solves my issue.  It would be nice to have it in ioselectors.

But any async nim program will use 40MB (per selector??) when running inside docker. If the reason to avoid allocations is performance, I think it could be reasonable to do just 2 allocations, one at start with maxFD clamped to 32768 (or any reasonable value), and if clamped value is reached another alloc to original maxFD. This way you pay only for what you really use.

**Comment by aguspiza** [comment]
I have added a pull request #7564 to add setrlimit to posix.nim and move duplicated definitions from poll and epoll of RLimit and getrlimit to posix.nim too

**Comment by dom96** [comment]
Seems we can close this.
