### ISSUE TITLE
[RFC] Naming convention for in-place mutating procs

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7551]
**Disclaimer: this only applies to procs with a mutating and non-mutating version. Not procs like `pop` that always mutate.**

### Context

There seems to be 2 conventions currently for proc that either mutate their arguments in-place or return a new T:

- Prefixing with a `m` for the mutating version: 
  - `items` and `mitems`
  - `pairs` and `mpairs`
- Have the verb be the in-place mutation and the past participle return a new T
  - `reverse` and `reversed` in `algorithm`
  - `sort` and `sorted`
  - `rotate` and `rotated`

### History

A long time ago (September 2017), I was trying to find a name for in-place reciprocal (x -> 1/x), ensue a [conversation on IRC](https://irclogs.nim-lang.org/25-09-2017.html#19:49:50) with various propositions including `reciprocaled` and `mreciprocal`

### Proposal

Some names are very strange to "-ed" but we can always prefix with a `m`. I would like to make all the new procs that accept out-of-place and in-place versions use the m prefix for their in-place version.

I also would like to add that to NEP-1.

### Transition for current procs

I have no idea

**Comment by Araq** [comment]
As I said on IRC, ``m`` prefix is a mutable view into a collection, it doesn't mutate the collection itself. As such there is no inconsistency with ``-ed`` named procs. The only thing that is currently lacking is a way to write an in-place ``strutils.replace`` for example. This can be named ``replaceIn``, nice and short.
