### ISSUE TITLE
nim --helpfull (combines --help and --advanced for easier grepping of cmds)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7562]
--advanced seems a bit less useful than a combined thing, eg `--helpfull` as often users don't know whether cmd is in --help or --advanced and have to grep for both.
if noone wants to implement, would PR's be accepted?

**Comment by data-man** [comment]
I propose combine --help and --advanced into --help and remove --advanced switch.

**Comment by timotheecour** [comment]
or, --help and --advanced with --advanced containing --help.
don't care which option is used so long there's an option with everything
