### ISSUE TITLE
[RFC] Add a `NotImplementedError`

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7584]
I think a `NotImplementedError` would be a useful addition to system especially when porting libraries and some functionality is missing.

**Comment by bluenote10** [comment]
Had the same need some time ago: https://github.com/nim-lang/Nim/pull/5320

**Comment by dom96** [comment]
I propose a pragma as well: ``{.stub.}`` or something (I'm sure there is a better name).

**Comment by Araq** [comment]
-1 from me, just declare your own exception type. You can do this btw

```nim

template awesomeTemplate() =
  {.error: "not implemented".}
```

**Comment by yglukhov** [comment]
`assert(false, "Not implemented")` or `assert(false, "Abstract method called")` is what I've been using :)

**Comment by CodeDoes** [comment]
Would be useful to have a error show up if the method isn't overloaded

**Comment by Araq** [comment]
Inherit your own exception but in the stdlib it would only encourage bad style, turning compiletime errors into runtime errors.
