### ISSUE TITLE
[feature] Nim error messages should show line contents, would save lots of debugging time

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7586]
- [ ] proposal: add an option `--showLineContext:int`

this would save tons of debugging time:

with `--showLineContext:0 ` (default value), same as current behavior
```
/Users/timothee/git_clone/nim/timn/bugs/t15_tuple.nim(47, 17) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(324, 7) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(49, 15) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(74, 16) Error: identifier expected, but found '0'
```

with `--showLineContext:1 `
```
/Users/timothee/git_clone/nim/timn/bugs/t15_tuple.nim(47, 17) template/generic instantiation from here:  let a1 = a0 & ("8 / 2", 4).to1Tuple
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(324, 7) template/generic instantiation from here:   join((tup0, tup1))
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(49, 15) template/generic instantiation from here:     iteration a
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(74, 16) Error: identifier expected, but found '0':     iterateFor a, b
```

possible future extension: `--showLineContext:2,3 `
shows 2 lines above(including self line), 3 lines below (strictly below)

```
/Users/timothee/git_clone/nim/timn/bugs/t15_tuple.nim(47, 17) template/generic instantiation from here:
  when true:
    let a1 = a0 & ("8 / 2", 4).to1Tuple
  else:
    let a1 = a0
  # when true:
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(324, 7) template/generic instantiation from here:
  ## ``join((tup0, tup1))``.
  join((tup0, tup1))

proc zipExpr(outerLen, innerLen: int): PNimrodNode {.compileTime.} =
  result = newPar()
```

- [ ] with `--colorizeLineContext:true` we'd also:
* highlight (say in green) line at context 0 to distinguish from context above/below
* highlight ~~(say in blue)~~ (with underscore, so it works with spaces too) column mentioned in error message **EDIT**

**EDIT** nimgrep's logic can be reused for that purpose

**Comment by dom96** [comment]
Pretty sure ``--verbosity:3`` already shows this.

**Comment by timotheecour** [comment]
with `--verbosity:3` all i get is 1 line context at the end; which is quite different and not as useful. Also, it's doing other stuff too; it's good to keep features orthogonal

```
/Users/timothee/git_clone/nim/timn/bugs/t15_tuple.nim(47, 17) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(324, 7) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(49, 15) template/generic instantiation from here
/Users/timothee/.nimble_choosenim/pkgs/tuples-0.1.0/tuples.nim(74, 16) Error: identifier expected, but found '0'
      iterateFor a, b
                 ^
```

**Comment by alehander42** [comment]
I have to agree, I even think it's very useful to file context visible by default: would that somehow break anything depending on the output?

**Comment by alehander42** [comment]
`verbosity:3` shows one line indeed, and it also shows too much stuff one usually doesn't always need

**Comment by Araq** [comment]
``----hint[source]:on`` is the switch to get this. Somebody needs to make it the default and/or document it.

**Comment by timotheecour** [comment]
@Araq 
I added `hint[Source]:on` to nim.cfg and it still shows error messages without line contents, eg:

```
nim c -o:app -r bugs/t20_jester_type_mismatch.nim
Hint: used config file '/Users/timothee/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/timn/nim.cfg' [Conf]
/Users/timothee/.nimble_choosenim/pkgs/jester-0.2.0/jester.nim(531, 21) Error: type mismatch: got <Time> but expected 'int'
```
(note: as for the error itself, i just filed https://github.com/dom96/jester/issues/138)

also tried with: `----hint[source]:on` or `hint[source]:on`

**Comment by Araq** [comment]
@timotheecour, strange, I tested it from command line and it worked just fine. It's also enabled with ``--verbosity:2`` fwiw.

**Comment by timotheecour** [comment]
NOTE: also, it's verbosity:2 or 3, not 3.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/7635

**Comment by CodeVance** [comment]
this should be closed

**Comment by Araq** [comment]
I marked it with "documentation". The documentation has not been improved.

**Comment by drslump** [comment]
I had a go at documenting the hints https://github.com/nim-lang/Nim/pull/8625

**Comment by timotheecour** [comment]
could we reopen? the problem is still there:

```nim
proc foo2[]()=
  var foo2: int = 3.0
proc foo1[]()=
  foo2()
proc main()=
  foo1()

main()
```

nim c --hint:source:on issue_7586.nim
```
issue_7586.nim(5, 1) template/generic instantiation from here
issue_7586.nim(6, 7) template/generic instantiation from here
issue_7586.nim(4, 7) template/generic instantiation from here
issue_7586.nim(2, 19) Error: type mismatch: got <float64> but expected 'int'
    var foo2: int = 3.0
                    ^
```

instead of:
```
issue_7586.nim(7, 1) template/generic instantiation from here
    proc main()=
issue_7586.nim(8, 7) template/generic instantiation from here
    foo1()
issue_7586.nim(6, 7) template/generic instantiation from here
    foo2()
issue_7586.nim(4, 19) Error: type mismatch: got <float64> but expected 'int'
    var foo2: int = 3.0
                    ^
```

it doesn't have to be the default with `--hint:source:on`, it could be via `--hint:sourceAll:on` if needed, there needs to be a flag for that
