### ISSUE TITLE
stdlib bitops incorrect result for popcount

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#7587]
```
echo popcount(0b11111111'i8)
```
returns 32 which can't be right given that byte has only 8 bits.

P.S.
Internally popcount converts ``int8`` to ``uint32`` which produces wrong result for for negative numbers due to sign extention. It needs to cast ``int8` to `uint8` first then convert to `uint32`  or implement `uint8` directly

**Comment by bung87** [comment]
https://play.nim-lang.org/#ix=2mbS

this problem is gone.

**Comment by timotheecour** [comment]
indeed; or via a 1 liner: `echo "import bitops; doAssert popcount(0b11111111'i8) == 8" | nim r -`
@bung87 if you want to help, a PR (with "closes #7587") that adds a test case would be appreciated; I can review it promptly

just add 1 test to `tests/stdlib/tbitops.nim`

thanks!

**Comment by bung87** [comment]
ah, I was trying to fix it, but it seems `tests/stdlib/tbitops.nim` is breaking without any modification. I dont know the history of this tests. not sure I can handle this.

**Comment by timotheecour** [comment]
that's odd, `nim r tests/stdlib/tbitops.nim` works for me; are you sure you're using a correct nim?
all these should work:
```
# use an "external" nim (quick and dirty sanity check, make sure to use recent nim)
nim r --lib:lib tests/stdlib/tbitops.nim

# build nim locally from scratch (via bootstrap)
sh build_all.sh # build nim locally (on posix)

# build nim locally but not from scratch (faster)
bin/nim_csources c -o:bin/nim_temp1 -d:release compiler/nim.nim

# then re-run test:
bin/nim_temp1 r tests/stdlib/tbitops.nim # --lib:lib not needed in this case
```

**Comment by bung87** [comment]
ok ,let me try, thanks!
