### ISSUE TITLE
`nimgrep --nocolor` is ignored on posix; should be instead: `--nimgrep --color=[auto]|true|false`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7591]

**Comment by Mouvedia** [comment]
wontfix label you sure?

**Comment by timotheecour** [comment]
> [Mouvedia] wontfix label you sure?

I was asked to close some of the issues I had opened to reduce their number based on importance level; feel free to reopen or better, open a PR :-)

**Comment by Mouvedia** [comment]
@timotheecour https://nim-lang.org/blog/2020/04/03/version-120-released.html#bugfixes

**Comment by timotheecour** [comment]
> @timotheecour nim-lang.org/blog/2020/04/03/version-120-released.html#bugfixes

well the script that generates release notes doesn't take into account `wontfix` labels...

**Comment by Clyybber** [comment]
@timotheecour But this *is* fixed.

**Comment by timotheecour** [comment]
ah ok https://github.com/nim-lang/Nim/pull/12288 indeed fixes it and i checked it works, thanks! (the wontfix label predated the fix)
