### ISSUE TITLE
`sh build.sh` should build in bin/nim_bootstrap to avoid being overwritten by `./koch boot -d:release`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7594]
in instructions in README.md,
`sh build.sh` should build in bin/nim_bootstrap instead of bin/nim to avoid being overwritten by ./koch boot -d:release
that way, if while hacking on compiler, ./koch boot -d:release creates an un-usable bin/nim, we don't have to rerun `sh build.sh` again and can just edit the nim files and re-run ./koch boot -d:release

**Comment by Araq** [comment]
``./koch boot -d:release`` does not create an un-usable ``bin/nim``, it only overwrites the final binary when bootstrapping succeeded. And when it succeeded it was good enough to succeed again with more fixes. Btw for compiler development you can use ``koch temp``.
