### ISSUE TITLE
[WONTFIX] `Error: cannot evaluate at compile time` for typedesc parameters (works for generics)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7596]
```nim
#[ 
* with typedesc:
a.type.foo1
Error: cannot evaluate at compile time: T


* with generic:
foo2[a.type]()
ok
]#

proc doInit[T]():auto=
  var a: T
  return a

proc len(T: typedesc[tuple]):auto=
  return 2 # doesn't matter; simplified from a more complex example

# proc foo1(T: typedesc[tuple])=
proc foo1(T: typedesc[tuple])=
  const n=T.len

proc foo2[T]()=
  const n=T.len

let a=(bar1:1,bar2:2)
a.type.foo1 # CT error
# foo2[a.type]() # ok

```

This should work right?
If not, I'd like to understand the rationale why it can't be made to work ~~and that would give a strong argument towards using generics instead of typedesc params in https://github.com/nim-lang/Nim/issues/7517 ([RFC] guidelines for when to use typedesc vs generics )~~

**EDIT**: see workaround [here](https://github.com/nim-lang/Nim/issues/7596#issuecomment-409358764) using an intermediate generic

**Comment by mratsim** [comment]
Yes typedesc are quirky and you need generics anyway when you want to constrain typedesc parameters at the moment:

```Nim
proc len(T: typedesc[tuple]):auto=
  return 2 # doesn't matter; simplified from a more complex example

# proc foo1(T: typedesc[tuple])=
proc foo1[T](_: typedesc[T])=
  const n=T.len

let a=(bar1:1,bar2:2)
a.type.foo1
```

**Comment by timotheecour** [comment]
/cc @zah 
actually this is a duplicate of https://github.com/nim-lang/Nim/issues/8486 ; in which I also show a workaround using an intermediate generic:

```nim
proc defaultImpl[T]():T=
  var a: T
  return a
template default*[T](t: typedesc[T]): T = defaultImpl[T]()
```
so user code can still use `typedesc` variant, but it complicates the library code (which must use a generic variant)
