### ISSUE TITLE
Proposal: concise and elegant operators

### ISSUE THREAD

**Issue by luav** [nim-lang/Nim#7613]
Nim has operators `in notin is isnot not`, which seems to be over verbose (`notin isnot`) and takes redundant build-in / reserved terms.

It would be more concise, elegant and result in less reserved terms to provide the following notation:
  - `notin` -> `not in`
  - `isnot` -> `not is`
  - suggested `notof` in #2991 -> `not of`

`not` is extremely beneficial to be used with `in is of` operators and also it would be nice to use it with `and or xor` operators to have the concise and comprehensive Boolean algebra support.

Note that unlike Python's `a is not b` that is `not(a is b)`, which is not expressive since could be read as `a is (not b)`, the proposed notation `a not is b` is unambiguous, i.e. expressive and concise.

**Comment by Araq** [comment]
There is little elegance in two word operators, a concept that Nim does without nicely. The special grammar rule is more complex than the additional keywords when we already have keyword operators for readability purposes (``and``, ``or`` come to mind).

**Comment by KeepCoolWithCoolidge** [comment]
While programming languages do not need to follow normal language patterns, `not is` seems especially awkward to my English-speaking ear. `isnot` is unambiguous because the intercession of a parenthesis is not possible. Also, isn't `not(a is b)` the same as `a is (not b)`?

**Comment by luav** [comment]
@KeepCoolWithCoolidge `a is (not b)` obviously differs from `not(a is b)`, for example:
```Python
>>> 1 is (not 0)
False
>>> not(1 is 0)
True
```
As for the proposed uniform, concise and structured syntax, which reduces the number of operators then it would be beneficial for any formal language and it does not matter how in sounds on some "normal language". English is far from been unambiguous or concise.

The less keywords and rules in the language, the more structured and uniform it is, the faster and easier it can be mastered. That is why Python is the most popular programming language and that is why Esperanto is learned literally 10x faster than English.

**Comment by Araq** [comment]
> The less keywords and rules in the language, the more structured and uniform it is, the faster and easier it can be mastered. 

Your proposal adds rules to the language. Python with ``notin`` would be just as popular.

**Comment by luav** [comment]
Python community would never accept `notin` otherwise it would also accept many other extensions becoming totally different and just another mediocre language.

**Comment by KeepCoolWithCoolidge** [comment]
Ah, I stand corrected. In my defense, it is early where I am.

**Comment by KeepCoolWithCoolidge** [comment]
Also, I was thinking in terms of types. Is not used for numerical values is it? Nim manual says that it is used to check for type  equivalence at compile time. Are we getting concepts confused, perhaps?

**Comment by Araq** [comment]
> Python community would never accept notin otherwise it would also accept many other extensions becoming totally different and just another mediocre language.

I will never accept ``not in`` and ``not is`` otherwise I would also accept many other extensions becoming totally different and just another mediocre language.

**Comment by luav** [comment]
@Araq: A subjective [comparative overview of some efficient programming languages](https://sdevprog.blogspot.ch/2018/04/overview-of-efficient-programming.html) (3rd edition includes Nim).
