### ISSUE TITLE
Proposal: `emit` pragma refinement for the *expressive* backend binding

### ISSUE THREAD

**Issue by luav** [nim-lang/Nim#7614]
[Emit pragma](https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-emit-pragma) provides much more concise integration with the backends (C++/C/JS) than the wrappers writing and it deserves to be expressed by the dedicated notation. Moreover, the dedicated notation would allow to:
a) express the embedded code,
b) optionally handle it differently from the regular "triple quoted string literals" and
c) even to have the syntax highlighting out of the box (if [``` block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) is used).

For example, instead of:  
`{.emit: ["""fprintf(stdout, "%d\n", cvariable + (int)""", nimVar, ");"].}`  
the much more readable version with the automatic syntax highlighting by both Github, BitBucket and various IDEs would be:
```c
```fprintf(stdout, "%d\n", cvariable + (int)```, nimVar, ```);```

**Comment by Araq** [comment]
The emit pragma is a hacky way of doing things and hacky ways don't deserve a nice syntax.
