### ISSUE TITLE
Threadpool `awaitAny()` problem on macOS

### ISSUE THREAD

**Issue by allochi** [nim-lang/Nim#7638]
Hi,

I'm having a problem running the following code on macOS 10.13 Intel i7, although, it runs perfectly on a Linux server. I also tried to run it on a different macOS machine with the same problem.

The problem:
The code runs, threads are done with their tasks, but `awaitAny()` doesn't report back all the finished threads/tasks, and the while loop never finishs, since `awaitAny()` never returns -1.

I talked about this problem in Gitter, at the time the problem in the sample code was solved by using `setMinPoolSize()`, but then on a real world program (or extended sample), even setting  `setMinPoolSize(MaxThreadPoolSize)` causes the same problem.

```nim
import threadpool, os

proc timer(d: int): int =
  echo("sleep: ", d)
  sleep(d)
  echo("done: ", d)
  return d

var durations = [4000, 2000, 3000, 4000, 5000, 6000]
var tasks: seq[FlowVarBase] = @[]
var results: seq[int] = @[]

for i in 0 .. durations.high:
  tasks.add(spawn timer(durations[i]))

var index = awaitAny(tasks)
while index != -1:
  results.add(^cast[FlowVar[int]](tasks[index])) # A. cast FlowVarBase to get the value
  tasks.del(index)
  echo($results)
  index = awaitAny(tasks)

sync()
```

**Comment by allochi** [comment]
Hi, I'm trying to do all possible tests, so I spent some time today testing this on Docker and Vagrant, I get the same problem with both on the same machine.

I can understand why the problem persist on Docker, but Vagrant suppose to be a full VM.

Anyway, I'm happy to do any required tests, and help as much as possible.

**Comment by dom96** [comment]
That ``cast`` looks dangerous, can't you use a safe cast there?

**Comment by allochi** [comment]
@dom96 I really don't care about the cast since it's just a sample code, even if you remove it the problem remains, it won't work on macOS (I tried)

Regarding the cast, to be honest I wish if there is another way to return a result within `FlowVarBase `, I don't see anything in the documentation, your advice is appreciated.

**Comment by Araq** [comment]
> Regarding the cast, to be honest I wish if there is another way to return a result within FlowVarBase, I don't see anything in the documentation, your advice is appreciated.

Use a type conversion like so  FlowVar[int](myFlowVarBase)

**Comment by allochi** [comment]
Thanks a lot @Araq, I confirm, the code works now.

Regarding casting, what you suggest is what I tried originally, but I get this error:

```
Error: type mismatch: got <FlowVarBase> but expected 'FlowVar[system.int]'
```

**Comment by Araq** [comment]
>  but I get this error

That would be another bug. :-)

**Comment by allochi** [comment]
Yeah, sorry, and thanks!
