### ISSUE TITLE
Regex module re does not work in JavaScript.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#7640]
It would be nice if it did, or there was an api compatibility layer that used js's regex.

**Comment by treeform** [comment]
Also the error should probably be better then:
`lib/impure/re.nim(100, 3) Error: undeclared identifier: 'copyMem'`

**Comment by liwt31** [comment]
For a workaround, use [nim-regex](https://github.com/nitely/nim-regex). It's purely written in Nim and as far as I know has no JS compatibility issue.

**Comment by treeform** [comment]
Nice I will take a look at this!

**Comment by ringabout** [comment]
`jsre` is merged. Could this issue be closed?
#14870
