### ISSUE TITLE
Misleading "Error: not all cases are covered" when unexpected closing braket

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#7642]
Would be nice, if the error message in this case could be improved.

Example program:
```nim
type Enum1 = enum a, b
var enum1 = a
case enum1
of a:
  echo "a" )
of b:
  echo "b"
```
Result: "Error: not all cases are covered"
Expected result: unexpected closing braket or something

**Comment by jangko** [comment]
duplicate of #3515?

**Comment by trustable-code** [comment]
@jangko, yes, duplicate of #3515
