### ISSUE TITLE
Having a void field leads to a compile-time crash with SIGSEGV

### ISSUE THREAD

**Issue by 6A** [nim-lang/Nim#7651]
I wanted a placeholder for a field whose type had yet to be defined, and decided to go with `void`.

However, defining the type itself (using the code below, for example) does not lead to an error, but using it in a function (directly, or by having another type referencing it) leads to a compiler exception with the following message: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`.

### No error
```nim
type Test = object
  placeholder: void
```

### No error
```nim
type
  Test = object
    placeholder: void
  Other = ref object
    test: Test
```

### Error
```nim
type Test = object
  placeholder: void

proc directUse(t: Test) = discard
```

### Error
```nim
type
  Test = object
    placeholder: void
  Other = ref object
    test: Test

proc indirectUse(t: Other) = discard
```

## Version
```
Nim Compiler Version 0.18.0 [Windows: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 5ee9e86c87d831d32441db658046fc989a197ac9
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
Confirmed
