### ISSUE TITLE
TLineInfo on windows 32bit

### ISSUE THREAD

**Issue by Tormund** [nim-lang/Nim#7654]
TLineInfo has fields:
` line*, col*: int16`

So maximum line index is 32768, but we have modules with over 32k lines.
Getting error on compilation:

```
lexer.nim(155)           getLineInfo
msgs.nim(639)            newLineInfo
system.nim(2850)         sysFatal
Error: unhandled exception: value out of range: 32768 [RangeError]
```

For example this package 
https://github.com/Tormund/winim
(winapi.nim)

**Comment by zah** [comment]
You should be able to split this file in some sub-sections that can be included in a single module.

**Comment by Tormund** [comment]
I made this, but this is hacky =)

**Comment by data-man** [comment]
With int16
> Hint: operation successful (121382 lines compiled; 3.806 sec total; 342.344MiB peakmem; Release Build)

With int
> Hint: operation successful (121382 lines compiled; 3.913 sec total; 424.141MiB peakmem; Release Build)

I don't think there is a big saving memory.

**Comment by zah** [comment]
I can think of a hack where some extra bits are stuffed in the `fileIdx` field. Just 4 more bits will get us above 1M lines.

**Comment by Araq** [comment]
> I don't think there is a big saving memory.

70MB is not a big saving?

**Comment by data-man** [comment]
Of course, in comparison with gigabytes of memory.

**Comment by data-man** [comment]
Why for nimpretty no savings? :)
