### ISSUE TITLE
Union types in javascript

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7658]
Not sure if it's possible or planned to make union types work in Javascript, currently it compiles but as separate fields.

```Nim
type Foo{.union.} = object
  as_bytes: array[8, int8]
  data: int64


let a = Foo(data: 12345)

echo a.as_bytes # [0, 0, 0, 0, 0, 0, 0, 0]
echo a.data     # 12345

a.as_bytes[0] = 1

echo a.data     # 12345
echo a.as_bytes # [1, 0, 0, 0, 0, 0, 0, 0]
```

I suppose unions in JS should be disallowed like `casts` are.

**Comment by Araq** [comment]
@alehander42 Sure but we can at least produce a nice error message.
