### ISSUE TITLE
Can not compile with --os:standalone --gc:none

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7662]
```nim
# test.nim
# empty
```
```nim
# panicoverride.nim
proc panic(s: string) = discard
proc rawoutput(s: string) = discard
```
```
nim c --gc:none --os:standalone --stacktrace:off ~/test.nim
Error: system module needs 'newSeq'
```

**Comment by yglukhov** [comment]
But it works with `--deadCodeElim:on`. Should `--os:standalone` or `--gc:none` imply `--deadCodeElim:on`?

**Comment by Araq** [comment]
yeah, there are plans to make ``--deadCodeElim:on`` the default and remove the switch altogether.

**Comment by dom96** [comment]
Why remove the switch? The ability to disable it might come in handy someday.

**Comment by Araq** [comment]
> Why remove the switch? The ability to disable it might come in handy someday.

It's battle-tested to the point the language works better with it than without it.

**Comment by Araq** [comment]
Closing since deadCodeElim is now always on.
