### ISSUE TITLE
httpclient.generateHeaders() not setting Content-Length if body.len=0

### ISSUE THREAD

**Issue by oswjk** [nim-lang/Nim#7680]
This is problematic when using httpclient to do a POST request with an empty body and the other end is AsyncHttpServer which requires POST requests to have the Content-Length set.

I think the fix should be just to take out the `body.len > 0` check from https://github.com/nim-lang/Nim/blob/devel/lib/pure/httpclient.nim#L771. That way we include the user-set Content-Length, if any, but otherwise always include the Content-Length derived from `body.len`.

**Comment by cabhishek** [comment]
related to issue #2884 and [commit](https://github.com/nim-lang/Nim/commit/c4009c61820190c188f6bcf7469754b3c40201e5).

**Comment by hlaaftana** [comment]
[relevant code in asynchttpserver](https://github.com/nim-lang/Nim/blob/devel/lib/pure/asynchttpserver.nim#L231)
