### ISSUE TITLE
identifier expected (whitespace-related)

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#7685]
Consider this toy example:

```nim
import strutils

let n = 3
for i in 1 .. n:
  echo "a".repeat(n - i - 1)
  echo "a".repeat(n - i- 1)
  echo "a".repeat(n-i -1)
  echo "a".repeat(n-i- 1)
  echo "a".repeat(n -i- 1)
  echo "a".repeat(n- i- 1)
  echo "a".repeat(n - i -1)
  echo "a".repeat(n-i-1)
```

Can you tell (without checking) which of these lines will raise an error and which will work?

Is this behaviour intended/wanted or should be corrected?

**Comment by Araq** [comment]
The compiler now warns about inconsistent spacing and as far as I can tell it otherwise works as designed.
