### ISSUE TITLE
Remove some modules and procs deprecated around 0.12.x and older

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#7689]
That seems like a reasonable amount of time to start with.

**Comment by data-man** [comment]
@tersec 
AFAIR, @Yardanico is already working on this.

**Comment by tersec** [comment]
Huh, https://github.com/nim-lang/Nim/pull/7690 didn't get linked here automatically.

**Comment by tersec** [comment]
@data-man that would work for me also, obviously.

**Comment by Yardanico** [comment]
@tersec this can probably be closed because @Araq did a clean-up himself (I was busy preparing for exams sadly). Can this be closed?

**Comment by dom96** [comment]
I'll close it. If @Araq thinks there is more to do we can reopen.
