### ISSUE TITLE
[regression] nimscript.task crash the compiler

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#7696]
how to reproduce:

* create file 'config.nims' contains:
```nim
task specTests, "Run spec tests":
  --r
  setCommand "c", "test"
```
* create file 'test.nim' contains anything you like:
```nim
echo "hello"
```

* run with command 'nim specTests'

error messages:
```text
Traceback (most recent call last)
nim.nim(113)             nim
nim.nim(102)             handleCmdLine
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

git bisect tell the bad commit is [here](https://github.com/nim-lang/Nim/commit/b503ca03f697d7364efe0bc5cf367e9e8bd12418)

**Comment by jangko** [comment]
here is the culprit in options.nim, missing ConfigRef.arguments initialization:

```nim
proc newConfigRef*(): ConfigRef =
  result = ConfigRef(cppDefines: initSet[string](),
    headerFile: "", features: {})
```

don't know how to create a test case for this kind of bug.

**Comment by Araq** [comment]
Works for me but I just changed Nim so that concats on nil strings don't cause crashes. :-)

**Comment by jangko** [comment]
👍 , very good. one less crash. confirmed

**Comment by jangko** [comment]
the compiler crash again, this time on windows only
```Nim
Traceback (most recent call last)
nim.nim(114)             nim
nim.nim(103)             handleCmdLine
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
```text
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-05-21
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 5472574f721ae08cb696f4129abcff54e1e88d83
active boot switches:
```

**Comment by Araq** [comment]
Works for me on Windows too.

**Comment by jangko** [comment]
it works with release mode compiler but crash with debug mode compiler
