### ISSUE TITLE
move fsmonitor out into a Nimble package

### ISSUE THREAD

**Issue by flowck** [nim-lang/Nim#7710]
The fsmonitor page is returning the 404 error. The error page shows the default message from nginx and its version. I would suggest a custom 404 page.

https://nim-lang.org/docs/fsmonitor.html

**Comment by dom96** [comment]
We need to move this module out into a nimble package.

**Comment by dom96** [comment]
Actually, here is an issue with some discussion so I'm going to close this in favour of it: https://github.com/nim-lang/Nim/issues/6718
