### ISSUE TITLE
Nim allow array construction of polymorphic object but crash at runtime

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#7712]
again while investigating #4799, I found another issue. Nim allow array construction of polymorphic object, but crash at runtime. 

While array construction of ref/ptr polymorphic objects is allowed. I think the compiler should disallow this kind of array construction of non ref/ptr objects. Need to investigate the generic version too.

at least GCC 7.3.0 still allow this kind of construct, but I don't see any reason Nim should do the same.
 
```Nim
type
  Fruit = object of RootObj
    name: string
    
  Apple = object of Fruit
    taste: string
    
  Banana = object of Fruit
    color: string

var a = Apple(name: "apple", taste: "sweet")
var b = Banana(name: "banana", color: "yellow")

var x = [a, b] #crash at here
```

error message at runtime(not Nim compiler crash):
```Text
PS F:\projects\bug> .\zap
zap.nim(20)              zap
assign.nim(124)          genericAssign
assign.nim(97)           genericAssignAux
system.nim(2844)         sysFatal
Error: unhandled exception: invalid object assignment [ObjectAssignmentError]
```

**Comment by Araq** [comment]
This is not supported anymore, check the changelog please.

**Comment by jangko** [comment]
shouldn't this is not allowed at compile time, why at runtime?

**Comment by Araq** [comment]
Because I don't have the type relation "convertible but would slice" in the compiler.
