### ISSUE TITLE
No support for unix domain sockets in asyncnet

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#7716]

**Comment by zevv** [comment]
I've added basic support for AF_UNIX sockets here:

https://github.com/zevv/Nim/commit/7eeb45295a001bf3b9c3204cd83b73de5b76a728

I'd appreciate a review from @dom96  before creating a pull request

**Comment by dom96** [comment]
Looks mostly good. Please create a PR for more in-depth comments.

My high-level observations:

* Don't like the proc in net being exported
* Need recvFrom/sendTo in async too

**Comment by Araq** [comment]
``connectUnix`` is now a thing.
