### ISSUE TITLE
multiple auto params allow partial generic deduction, but only on number types

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/Nim#7720]
```nim
proc add(x, y: auto): auto = x + y

echo add(1i8, 2i8)
echo add[int8](1, 2i8) # compiles
echo add[int8, int8](1, 2)

proc add2[T, U](x: T, y: U): auto = x + y

echo add2(1i8, 2i8)
when false:
  echo add2[int8](1, 2i8) # doesn't compile
echo add2[int8, int8](1, 2)

proc concat(x, y: auto): auto = x & y

echo concat("abc", "def")
when false:
  echo concat[string]("abc", "def") # doesn't compile
echo concat[string, string]("abc", "def")
```

**Comment by Clyybber** [comment]
The 4th line doesn't compile anymore, but instead fails with `expression 'add[int8](1, 2'i8)' cannot be called`..

**Comment by Yardanico** [comment]
@hlaaftana why choose?

**Comment by Clyybber** [comment]
This isn't fixed :)

**Comment by hlaaftana** [comment]
So what is the issue now? `x, y: auto` should only produce 1 generic type? `auto` shouldn't have a generic binding at all?

**Comment by metagn** [comment]
I'm closing this. I don't see any issue here except what is already covered by #7728, and that is the following not compiling:

```nim
proc concat(x, y: auto): auto = x & y

echo concat("abc", "def")
echo concat[string]("abc", "def")
```

`x, y: auto` should imply `x, y: T`, even if it implying `x: T, y: U` is preferred, `x, y: Foo[auto]` still implies `x, y: Foo[T]`. Other than this, if auto shouldn't allow explicit generic invocation (it should) then another issue should be opened for it.
