### ISSUE TITLE
Macro + quote do + proc creation: wrong result scope

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7722]
When using "result" in a quote do statement, the result variable has the wrong scope:

```Nim
import macros

macro foo1(): untyped =

  result = newStmtList()
  result.add quote do:
    proc init(foo: int): int =
      result = foo

foo1()
```

Errors:
- Error: type mismatch: got <int> but expected 'NimNode = ref NimNodeObj'
- (nimsuggest): closure calling convention for top level routines is invalid
- (nimsuggest): illegal capture result of type <NimNode>

Note that if typedesc are involved it works

```Nim
import macros

macro foo1(): untyped =

  result = newStmtList()

  result.add quote do:
    proc init(foo: int, bar: typedesc[int]): int =
      result = foo

foo1()
```

**Comment by zah** [comment]
This has been reported before:

https://github.com/nim-lang/Nim/issues/7323
