### ISSUE TITLE
Macros: quasiquoting + dot or bracket syntax: dot and brackets are ignored

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7726]
The quasiquoting interpolation ignores dot call/fields. Test case:

```Nim
import macros

macro foo(): untyped =
  let a = @[1, 2, 3, 4, 5]
  result = quote do:
    `a.len`


macro foo2(): untyped =
  let a = @[1, 2, 3, 4, 5]
  let len = a.len
  result = quote do:
    `len`

echo foo() # Outputs @[1, 2, 3, 4, 5] instead of 5
echo foo2() # Outputs 5
```

**Comment by mratsim** [comment]
Brackets are also ignored:

```Nim
import macros

macro foo(): untyped =
  let a = @[1, 2, 3, 4, 5]
  result = quote do:
    `a.len`


macro foo2(): untyped =
  let a = @[1, 2, 3, 4, 5]
  let len = a.len
  result = quote do:
    `len`

macro foo3(): untyped =
  let a = @[1, 2, 3, 4, 5]
  let len = a.len
  result = quote do:
    `a[2]`

echo foo()  # Outputs @[1, 2, 3, 4, 5] instead of 5
echo foo2() # Outputs 5
echo foo3() # Outputs @[1, 2, 3, 4, 5] instead of 3
```

**Comment by dom96** [comment]
Yeah, and idents aren't handled correctly. I have to write ``let foo = newIdentNode("foo")`` all over my code and then use it inside my `quote`. It's super messy.

**Comment by krux02** [comment]
Yes, the backticks on expressions should, when not supported, at least come with a sane error message. 


@dom96 sorry, this is a very late reply, but your comment is on an entirely different issue. And I am aware of it.

**Comment by egaburov** [comment]
is the fix in works? Ability to call functions  in unquote parts help to keep code clean

**Comment by krux02** [comment]
there is this branch from me: https://github.com/nim-lang/Nim/pull/11823
