### ISSUE TITLE
--Debugger:native is broken by nil strings comparison commit

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7746]
Test case
```Nim
echo 1
```

Compile with --debugger:native: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

Bisect points to this commit: https://github.com/nim-lang/Nim/commit/f64f9e50cca38db24f68ee70d979fd55b1c49868

**Comment by cheatfate** [comment]
Compiler crash log

**Comment by mratsim** [comment]
Probably duplicate of #7730
