### ISSUE TITLE
Enable the __tcc_cas in the atomics.nim for tcc in windows.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#7750]
The cas function for TinyC is disabled for windows in the atomics.nim, in fact it works for windows.

https://forum.nim-lang.org/t/3794/1#23666

**Comment by genotrance** [comment]
Updated test [results](https://www.dropbox.com/s/prbrtdd63rv2hsa/testresults-tcc.html) with latest tcc from #head. Passes the threads tests but still 20 failing tests. Also, [snip](https://github.com/genotrance/snip) still hangs on run.

**Comment by genotrance** [comment]
Latest win32 build of [tcc](https://www.dropbox.com/s/u9w2i0haj8nc5u6/tcc.zip) for convenience.
