### ISSUE TITLE
xpath style macros.findChild()

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#7752]
It'd be nice to be able to select nodes in an AST using [something like xpath](https://msdn.microsoft.com/en-us/library/ms256086(v=vs.110).aspx).

For example, given the following tree:

```
StmtList
  TypeSection
    TypeDef
      Ident "Animal"
      Empty
      RefTy
        ObjectTy
          Empty
          OfInherit
            Ident "RootObj"
          Empty
  MethodDef
...
```

This code would work as follows:

```nim
n.path("Ident")
# Ident "Animal"
# Ident "RootObj"
n.path("TypeDef//ObjectTy")
# ObjectTy
#   Empty
#   OfInherit
#     Ident "RootObj"
#   Empty
```

**Comment by dom96** [comment]
This sounds like it should go into https://github.com/nim-lang/needed-libraries to be honest. Perhaps we could integrate it into the stdlib once it becomes stable.
