### ISSUE TITLE
Generic type resolution issue - Default argument equal to previous argument

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7756]
A followup on #7755

This gives `Error: type mismatch: got <seq[T]> but expected 'seq[int]'`

```Nim
proc foo[T](x: seq[T], y: seq[T] = x) =
  discard

let a = @[1, 2, 3]
foo(a)
```

**Comment by loloiccl** [comment]
This is related to #1046.
What is expected to happen when a parameter is used in another parameter's default value?
