### ISSUE TITLE
Async undefined behavior

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#7758]
This simple code shows undefined behavior inside of asyncdispatch.

Conceptually this code must be completed in 1 poll call, but currently it completes for my PC in debug mode in `2108216`, `2110094`, `2100304` poll calls.

```nim
import asyncdispatch

proc task() {.async.} =
  await sleepAsync(1000)

when isMainModule:
  var counter = 0
  var f = task()
  while not f.finished:
    inc(counter)
    poll()

echo counter
```

**Comment by dom96** [comment]
Fun :)

**Comment by dom96** [comment]
I don't think this is undefined behaviour, it depends on how fast the CPU executes these poll's.

This will go away once timers are implemented in the event loop.
