### ISSUE TITLE
Allow =destroy on pointer types. (previously experimental feature)

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7776]
The following used to work:

```Nim
import opencl

{.experimental.}

type clResource = PCommandQueue | PKernel | PProgram | PMem | PContext

template release*(queue: PCommandQueue) = check releaseCommandQueue(queue)
template release*(kernel: PKernel) = check releaseKernel(kernel)
template release*(program: PProgram) = check releaseProgram(program)
template release*(buffer: PMem) = check releaseMemObject(buffer)
template release*(context: PContext) = check releaseContext(context)

proc `=destroy`*(clres: clResource) =
  release clres
```

The error now is:
Error: signature for '=destroy' must be proc[T: object](x: var T)

Looking at the previous code we had this:

https://github.com/nim-lang/Nim/blob/8ce9e434348f6f63b81f7a788bd4093996dbaca7/compiler/semstmts.nim#L1364-L1387

And now:

https://github.com/nim-lang/Nim/blob/608017801d3625dc8c7991073a0ef84440314c24/compiler/semstmts.nim#L1309-L1331

So it seems like the old experimental destructors were removed.

There is a plan to have destructors replace finalizer for ref objects. It would be also very useful to have destructors for ptr types especially for wrapping C libraries that gives an opaque type and the corresponding destroy/release proc.

**Comment by genotrance** [comment]
Simpler example to reproduce this:

```nim
type
  abc = object

proc `=destroy`(a: var abc) =
  echo "hello"

let a = abc()
```

`ctest.nim(4, 1) Error: signature for '=destroy' must be proc[T: object](x: var T)`

Note that this works just fine with #head on Windows but not on Linux.

**Comment by Araq** [comment]
Not gonna happen, the destructor design is for objects (it's already complex enough IMO) but it's easy enough to wrap a ``ptr`` in an object.

**Comment by genotrance** [comment]
But abc is a plain object in my example. And why does it work on Windows?

**Comment by Araq** [comment]
because your Nim version is only up-to-date on Windows?

**Comment by Araq** [comment]
> However, with abc = object, I get:

Works for me with ``--newruntime``.

**Comment by genotrance** [comment]
It works with --newruntime but I see weird behavior.

```nim
type
  abc = object
    a: int
  
proc `=destroy`(a: var abc) =
  echo "Destroy"
    
echo "Start"
var c = abc()
echo "Preset"
c.a = 5
echo c.a
echo "Done"
```

Output:
```
Start
Destroy                   <=== should be after Done
Preset
5
Done
```

**Comment by mratsim** [comment]
Here is another use case for at least a `lent` lifetime analysis on pointer types.

For optimization purposes I need to take a `ptr UncheckedArray[T]` to the raw data from a `Tensor[T]` and apply compiler hints like `__restrict__` and `__builtin_assume_aligned`.

This can be done in nim with:

```Nim
{.pragma: restrict, codegenDecl: "$# __restrict__ $#".}
proc builtin_assume_aligned[T](data: ptr T, n: csize): ptr T {.importc: "__builtin_assume_aligned",noDecl.}

let x = @[0, 1, 2, 3, 4]

let x_ptr{.restrict.} = builtin_assume_aligned(x[0].unsafeAddr, 16) # I don't actually know the alignment of seq types
```

Unfortunately `x_ptr` can escape its scope.

At initial glance, we could think wrapping in an object to use with destructors would work
```Nim
type MyPtr[T] = object
  p: ptr T
```

but you can only use `lent` if this type is already a part of another type (i.e. has an address). And if it already has an address you cannot apply codegenDecl pragma to it.

I see 3 solutions:

1. Pointers are unsafe, and by using them all bets are off. You should know what you're doing.

2. Add the possibility to `codegenDecl` in a type: that would allow restrict though it would not help for assume-aligned

3. Tag pointers with `lent` or a lifetime/escape analysis pragma
