### ISSUE TITLE
Catch array out-of-bounds at compile-time in any case

### ISSUE THREAD

**Issue by dset0x** [nim-lang/Nim#7781]
Hello, I'm going through nim tutorials and figured that this might be something nim will want to catch at compile-time in the future:

```nim
# Given
let arr : array[1..1, int] = [10]

# index-out-of-bounds at compile-time
echo arr[0]

# index-out-of-bounds at run-time
let idx = 0
echo arr[idx]

# index-out-of-bounds at run-time
for i in 0..0:
  echo arr[i]
```

Same goes for non 1-indexed arrays, with e.g. `-1`.

**Comment by Araq** [comment]
Thanks but not for version 1. In the longer run we catch all of these with better flow dependent typing.
