### ISSUE TITLE
Ability to check for effects at compile-time

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7789]
```nim
proc foo() {.tags: [MyTag].} = ...

proc bar() = foo()

when MyTag in bar.tags:
  echo("Bar has MyTag!")
```

same for ``raises``. That would make the effect system much more useful.

**Comment by twetzel59** [comment]
Is ``tags`` a magical field?

**Comment by arkanoid87** [comment]
this should be closed as effecttraits seems to cover the required checks

https://play.nim-lang.org/#ix=3ud2

**Comment by ringabout** [comment]
See also https://github.com/nim-lang/Nim/pull/15503
