### ISSUE TITLE
suggestion: allow user to specify pattern for output executable name in config file

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#7801]
my suggestion is regarding the -o command line switch that specifies the output name for the executable.
I would like nim to read a config file, and know how to name the output file.
for example:
$name.exe
$name_$year-$month-$day

PS: it's late night here, if the feature isn't clear please reply

**Comment by data-man** [comment]
You can do it with ```-o:name.ext``` or ```--out:name.ext```

**Comment by genotrance** [comment]
This is probably much easier to do as part of a build script (rename output file after it is built) instead of building functionality into the compiler.

**Comment by kobi2187** [comment]
I agree with you. [nake](https://github.com/fowlmouth/nake) is very suitable for such things.
and you're right the compiler is not the best place for this functionality.
I'll close the request.

**Comment by Yardanico** [comment]
@kobi2187 why would you need nake for that? You can use pure nimscript

**Comment by kobi2187** [comment]
Simply because I never tried it before. offtopic: Is there a nice tutorial for setting up all these basic tools?
