### ISSUE TITLE
Remove cookies module from stdlib

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7810]
This module really shouldn't be in the stdlib in the first place IMO

**Comment by Araq** [comment]
Huh? What is wrong with it?

**Comment by dom96** [comment]
It's 77kloc and doesn't belong in the stdlib. It's trivial to implement in web frameworks.

**Comment by Araq** [comment]
I like it though and other web related stuff is also in the stdlib. Seems arbitrary, why does *this* tiny module that causes no harm nuked?

**Comment by dom96** [comment]
Because the web moves fast and this module is currently outdated. Instead of creating a PR to a compiler repo it was far easier to adopt it into my project. I believe it should therefore be removed.

**Comment by andreaferretti** [comment]
Jester is not the only web framework, though. The cookies module may turn out ot be useful in other situations (I am no using it in Rosencrantz, but it can still be used **with** it)

**Comment by dom96** [comment]
It's a tiny module and I don't see why it should be in the stdlib when it's
so trivial and often necessary to implement it in the relevant web
framework.

**Comment by Araq** [comment]
Fine go ahead, it's not that important, but I consider it a mistake. Python has https://docs.python.org/2/library/cookie.html fwiw. On a related note, these security concerns regarding the JavaScript package management ecosystem made me change my mind, I am now more in favour of a "batteries included stdlib".

**Comment by andreaferretti** [comment]
@dom96 what did change in the cookie specification?

**Comment by CodeDoes** [comment]
Cookies are timeless. As long as there are websites there will be cookies. If it was more complex to implement then it belongs in nimble. But I think there's a saying that simple things belong in the stdlib.

**Comment by narimiran** [comment]
What is the consensus on this one?

Should it be part of the stdlib or moved to [graveyard](https://github.com/nim-lang/graveyard)?

**Comment by andreaferretti** [comment]
I am not sure what outdated means, and @dom96 did not explain. As far as I know, cookies spec has not changed in ages

**Comment by dom96** [comment]
Here is a very recent addition to cookies:
https://caniuse.com/#feat=same-site-cookie-attribute

**Comment by andreaferretti** [comment]
That is a [draft](https://tools.ietf.org/html/draft-west-first-party-cookies-07) which is not even in any RFC yet. The relevant [RFC](https://www.ietf.org/rfc/rfc6265.txt) is unchanged since 2011. It seems a silly reason to remove a module from the standard library

**Comment by dom96** [comment]
That's not the only reason:

* It's a small module.
* It's trivial to implement
* *It's outdated*
* It has a niche use case which is filled by web frameworks anyway

**Comment by andreaferretti** [comment]
I will not insist - I will replicate the functionality in Rosencrantz when I find the time

**Comment by narimiran** [comment]
Araq just said in #10604:
> I don't like it at all, we should keep these modules in the stdlib if they are used and reasonably free of issues. They don't cost us much maintainance.

Closing this with the "won't fix" label.
