### ISSUE TITLE
future/sugar `=>` syntax breaks with generics

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#7816]
Recently I'm getting all kinds of compilation errors when using the future/sugar `=>` syntax. I now noticed that it is related to generic procs:

```nimrod
import sequtils
import sugar

proc tester[T](x: T) =
  let test = toSeq(0..5).map(i => newSeq[int]())

tester(1)
```

Error:

```
test.nim(7, 7) template/generic instantiation from here
test.nim(5, 32) template/generic instantiation from here
lib/system.nim(3559, 14) Error: cannot instantiate: 'T'
```

The expression does work when it appears in a non-generic context, and I'm pretty sure such code used to work before.

**Comment by Araq** [comment]
This is a though one. Can I have the commit that introduced the regression please?

**Comment by timotheecour** [comment]
@bluenote10 @Araq I doubt it ever worked; but my PR https://github.com/nim-lang/Nim/pull/8679 will fix this:

```nim
when defined(case2):
  import sequtils
  import sugar

  proc tester[T](x: T) =
    let test = toSeq(0..5).map(i => newSeq[int]())
    echo test

  tester(1)

when defined(case3):
  import sequtils
  proc tester[T](x: T) =
    let test = toSeq(0..5).map2(i => newSeq[int]()) # pending renaming map2 to map
    echo test

  tester(1)
```


rnim -d:case2 tests/nim/lambda/t01_lambda_exp3.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r -d:case2 tests/nim/lambda/t01_lambda_exp3.nim

@[@[], @[], @[], @[], @[], @[]]
