### ISSUE TITLE
Can't convert expression when surrounded with parens using %*

### ISSUE THREAD

**Issue by xmonader** [nim-lang/Nim#7817]
Using %* to convert a nim structure surrounded by parens crashes

## Versions
Nim 0.18

## How to reproduce
```nim
echo $(%*{"id": "myid"})
```
```
{"id":"myid"}
```

```nim
echo $(%*({"id": "myid"}))
```

## stacktrace

```
lib/pure/json.nim(789, 36) Error: type mismatch: got <tuple of (string, string)>
but expected one of:
proc `%`(s: string): JsonNode
proc `%`(n: BiggestInt): JsonNode
proc `%`(n: float): JsonNode
proc `%`(b: bool): JsonNode
proc `%`(keyVals: openArray[tuple[key: string, val: JsonNode]]): JsonNode
template `%`(j: JsonNode): JsonNode
proc `%`[T](elements: openArray[T]): JsonNode
proc `%`(formatstr, a: string): string
proc `%`(formatstr: string; a: openArray[string]): string
proc `%`(f: string; t: StringTableRef; flags: set[FormatFlag] = {}): string
proc `%`(o: ref object): JsonNode
proc `%`(o: enum): JsonNode
proc `%`(o: object): JsonNode

```

**Comment by GULPF** [comment]
This is expected behavior. `%*` is a macro so it gets passed an unevaluated expression, which means that the surrounding `()` will prevent it from treating `{}` specially. It could theoretically strip any surrounding parens before doing anything else, but I don't see what the point would be.

**Comment by xmonader** [comment]
@GULPF  I understand, I'm okay with proper documentation for the usage

**Comment by hlaaftana** [comment]
This is the correct way to do what you want

```nim
echo $(`%*`({"id": "myid"}))
```

**Comment by Araq** [comment]
@GULPF I think it's better to support superfluous () in the macro as done in my patch.
