### ISSUE TITLE
[regression] overloaded generic template cannot instantiate: 'T'

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#7829]
this oversimplified example was taken from real project

```Nim
proc testAux*[T](): int =
  discard

template test*[T](): untyped =
  testAux[T]()

template test*[T](x: int): untyped =
  testAux[T]()

var inter = test[int]()
```

if the second template commented, all will be fine

error messages:
```text
abc.nim(4, 16) Error: cannot instantiate: 'T'
```

**Comment by jangko** [comment]
git bisect says the first bad commit is [here](https://github.com/nim-lang/Nim/commit/bdcb72959729a5c4b195f9bf6b2ac8783c27f38e)

**Comment by xomachine** [comment]
[This problem](https://forum.nim-lang.org/t/3835) may be related.
