### ISSUE TITLE
Compiler crashes when using generics syntax in type definition

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#7839]
When compiling the following code (tested on 0.18.1 windows amd64 (git 34029263725ef931863ea73966dc08588758dada) and on nim playground) the compilation fails without an error.
I don't know if the syntax is ok though.

```nim
# the following code will break compilation without any error or hint
# `exited with code=3221225725`
type A[I: SomeOrdinal, E] = tuple # same for object
  length: int
 
echo A.sizeof # works without the following proc
 
proc newA*[I: SomeOrdinal, E](): A[I, E] = # works without `SomeOrdinal`
  discard
```

Update: the problem is solved, if `proc newA*[I: SomeOrdinal, E](): A[I, E]` is replaced by `proc newA*[I: SomeOrdinal, E](): A`, so it has nothing to do with `someOrdinal` as thought before.

**Comment by tim-st** [comment]
Update: The code works if `type A[I: SomeOrdinal, E] = tuple` is changed to `type A[I, E] = tuple`
so the crash comes from the type definition.
Thus it's maybe related to https://github.com/nim-lang/Nim/issues/8071
