### ISSUE TITLE
Error: invalid type: 'T' in this context: 'array' for var

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#7840]
Hello,

Based on [this][1] discussion on Reddit, I tried out this snippet from the manual from [here][2].

Here's the actual snippet I tried to compile:

```nim
var a {.noInit.}: array [0 .. 1023, char]
echo "Is the uninitialized variable 'a' declared? ", declared(a)
echo "Value of uninitialized variable 'a': ", a
```

But that gives this error:

> nim_src_wHNzVo.nim(4, 5) Error: invalid type: 'T' in this context: 'array' for var

*(I tried the same snippet without the spaces around `..` too, but I get the same error.)*

[1]: https://www.reddit.com/r/nim/comments/8k7ny8/my_random_notes_on_nim_wip/dz6ncuw/
[2]: https://nim-lang.org/docs/manual.html#statements-and-expressions-var-statement

**Comment by data-man** [comment]
Remove the space between ```array``` and ```[```.
Works for my (but ```a``` anyway initialized with zero).

**Comment by kaushalmodi** [comment]
Thanks! I confirm both..

1. Removing that space before `[` fixes the compilation (*each time I get back to trying Nim, I seem to get stalled by these space-related issues!*).
2. Also the `{.noInit.}` doesn't seem to do anything.

So the example needs to be fixed in manual.

**Comment by data-man** [comment]
> So the example needs to be fixed in manual.

Fixed in https://github.com/nim-lang/Nim/commit/6a229a8793b8724ab1055fba25d1a38d4199c5e3
