### ISSUE TITLE
asyncfile and asyncsocket have different behaviour when using readLine at empty line.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#7844]
Asyncsocket will return string with "\n" when it get an empty line, and empty string when encounter EOF. But the asyncfile return empty string both when encounter empty line and EOF.

**Comment by dom96** [comment]
Not sure if this is an issue. Sockets and Files are different and reading lines from a synchronous file also has this behaviour. AFAIK files also have a procedure that let's you check if they're at EOF, sockets don't.

**Comment by dom96** [comment]
Closing as I still don't think this is an issue.
