### ISSUE TITLE
Spurious "not GC-safe" warning

### ISSUE THREAD

**Issue by mooskagh** [nim-lang/Nim#7847]
Code:

```nim
import os
import ospaths
import parsetoml

proc GetConfigFileName() : string =
  return joinPath(getAppDir(), "lc0client.toml")

proc ReadConfig() : TomlTableRef =
  return parseFile(GetConfigFileName())
```

Check with:
```bash
$ nim check --verbosity:2 a.nim
```

Unreasonable warning:
```
a.nim(9, 19) Warning: not GC-safe: 'parseFile(GetConfigFileName())' [GcUnsafe]
```

**Comment by Araq** [comment]
We are not responsible for ``parsetoml``. Reopen when you have a test case that shows a wrong Nim compiler / stdlib behaviour.

**Comment by dom96** [comment]
I went through (admittedly skimmed) parsetoml and I didn't see anything that could be causing this gc unsafe warning. It's also odd that it only shows up under higher verbosity?

**Comment by Araq** [comment]
>  It's also odd that it only shows up under higher verbosity?

No, that's what the compiler does. It emits more warnings under a higher verbosity.

**Comment by Araq** [comment]
This is likely why:

```nim

# Forward declaration
proc parseValue(state: var ParserState): TomlValueRef
```

**Comment by PMunch** [comment]
Why does that forward declaration make it not GC safe?

**Comment by dom96** [comment]
We need better errors for this IMO

**Comment by Araq** [comment]
No test case. Closing.

**Comment by dom96** [comment]
Okay, well, let's please at least document this behaviour and answer @PMunch's question.

**Comment by narimiran** [comment]
> Why does that forward declaration make it not GC safe?

Recently I had a similar situation with a forward declaration, and I received the following explanation:
_"... the effect tracker doesn't like forward declarations, so it now thinks that `[]=` can have side effects. It will probably work if you add `noSideEffect` to the forward declaration."_

In a similar fashion, this is fixed by:
```nim
# Forward declaration
proc parseValue(state: var ParserState): TomlValueRef {.gcsafe.}
proc parseInlineTable(state: var ParserState): TomlValueRef {.gcsafe.}
```

I'm sending this fix upstream and closing this.
