### ISSUE TITLE
Strings are non-nil in VM

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#7859]
Commit: c12726d41e7df20bce452b6d7f8959d8b9e401a9

Not sure if that was an intended change, but currently strings work incompatibly between VM and runtime - they are initialized to `""` in VM and to `nil` and runtime. And `var s: string = nil` works in VM, yet the string is still set to `""`.

**Comment by endragor** [comment]
`isNil` returns `false` in VM and `true` in runtime for a default string.

**Comment by Yardanico** [comment]
well, yeah, that's still an issue

**Comment by nigredo-tori** [comment]
Hit this as well, since I had something like `x: string = nil` for default arguments in my build scripts. This change breaks such code subtly and silently.

**Comment by Araq** [comment]
> Hit this as well, since I had something like x: string = nil for default arguments in my build scripts. This change breaks such code subtly and silently.

The change is not yet complete, that's why. It is ``devel``, after all... ``nil``/``isNil`` for strings/seqs will **fail** to compile in the future.

**Comment by Araq** [comment]
There is no 'nil' for strings anymore.
