### ISSUE TITLE
instantiationInfo.filename is incorrect in nimscript(.nimble file)

### ISSUE THREAD

**Issue by 7sDream** [nim-lang/Nim#7861]
nim version: 0.18.0

---

Add a task in an default `.nimble` file

```nim
task root, "show the full path of package root":
  let scriptPath = instantiationInfo().filename
  echo scriptPath
  let projectRoot = parentDir(scriptPath)
  echo projectRoot
```

run `nimble root`, it shows:

```text
  Executing task root in /home/i7sdream/code/nimchat/nimchat.nimble
home/i7sdream/code/nimchat/nimchat.nimble
home/i7sdream/code/nimchat
```

with screenshot:
![image](https://user-images.githubusercontent.com/7822577/40376857-027cecf2-5e22-11e8-90ba-ae49fc436ef9.png)

---

Another problem about the `instantiationInfo`

```nim
proc projectRoot(): string =
  let scriptPath = instantiationInfo().filename
  echo scriptPath
  return "/" & parentDir(scriptPath)

task root, "show the full path of package root":
  echo projectRoot()
```

this time `nimble root` gives: 

```text
  Executing task root in /home/i7sdream/code/nimchat/nimchat.nimble
???
/
```

---

**Notice:** Anyone who also want to get root dir of project/package, you can use [`thisDir`](https://nim-lang.org/docs/nimscript.html#thisDir) in `nimscript` package.

**Comment by genotrance** [comment]
Works on Windows, fails on Linux on #head.

**Comment by ringabout** [comment]
> Another problem about the instantiationInfo

another problem is duplicated of  https://github.com/nim-lang/Nim/issues/11689

**Comment by ringabout** [comment]
I didn't quite understand the first problem.
Tested first problem on Windows and Linux, works for me.
