### ISSUE TITLE
Memory corruption on newSeq[MyAlignedType](1)

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#7865]
Compile and run to reproduce a crash:
```nim
{.passC: "-march=native".}

type
  m256d {.importc: "__m256d", header: "immintrin.h".} = object

proc set1(x: float): m256d {.importc: "_mm256_set1_pd", header: "immintrin.h".}

for _ in 1..1000:
  var x = newSeq[m256d](1)
  x[0] = set1(1.0)
```

The reason is clear, Nim incorrectly computed the amount bytes that needs to be allocated:
From lib/system/gc.nim:
```nim
proc newSeq(typ: PNimType, len: int): pointer {.compilerRtl.} =
  let size = addInt(mulInt(len, typ.base.size), GenericSeqSize)
```
GenericSeqSize is 16 bytes and  typ.base.size is 32 bytes. 48 bytes are allocated. 
Due alignment and padding it is not enough. It should 64 bytes instead, there is a padding between seq header and data.

**Comment by krux02** [comment]
I tried to compile it with the ``--newruntime`` switch, and the code block does not crash. But I can't explain why this is the case. According to my understanding of newruntime, it should crash for exactly the same reason.

**Comment by narimiran** [comment]
FWIW, it still crashes with the default GC, but it works with `--gc:arc`.

**Comment by Araq** [comment]
Well it works with --gc:arc so that's good enough.
