### ISSUE TITLE
using a symbol for generic argument doesn't work

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#7875]
This really should compile.

```nim
import macros

type
  MyType[T] = object

# this is totally fine
var mysym: MyType[float32]

macro foobar(): untyped =
  let floatSym = bindSym"float32"

  result = quote do:
    var mysym: MyType[`floatSym`]

  echo result.repr # var mysym117054: MyType[float32]

foobar()
```
error message:
```
cannot instantiate MyType
got: <float32>
but expected: <T>
```

I am generating type expressions in a macro and I get symbols via "getTypeInst". When I use these type symbols in a macro like above, I get the exact same error message.

**Comment by krux02** [comment]
well I have a workaround:

```nim
import macros

type
  MyType[T] = object

# this is totally fine
var mysym: MyType[float32]

macro foobar(): untyped =
  let floatSym = bindSym"float32"

  result = quote do:
    var mysym: MyType[type(`floatSym`)]

  echo result.repr

foobar()
```
``¯\_(ツ)_/¯``

**Comment by jangko** [comment]
this is actually pretty easy to fix, but then the bindSym will return a typedesc, not a symbol anymore.
we have some alternatives:

1. keep bindSym as is, and add new function such as `bindType` to handle this return type. (not a breaking change)
2. rename bindSym to `bindSymAndType`. (break a lot)
3. keep the bindSym name but whenever it bind to a typedesc, it return a typedesc. (weird and maybe break existing code)

please share your thoughts.

**Comment by krux02** [comment]
@jangko I would really like tho ``typedesc`` to be removed from the AST as much as possible. They are exposed in the macros API and just make it unnecessarily complicated to write macros.

**Comment by timotheecour** [comment]
@krux02 code on top works on latest devel => close?
