### ISSUE TITLE
IndexError in streams.readStr()

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#7877]
Might be related to #7860.

https://github.com/nim-lang/Nim/blob/e206a8d95240e766474d601f529fef1c0026f80f/lib/pure/streams.nim#L250-L264

Both calls to `addr(string(result)[0])` error out when invoked from [untar](https://github.com/dom96/untar).

```
untar.nim(99)           extract
streams.nim(254)         readStr
system.nim(2843)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

I am unable to get a simpler test case to fail but changing to `cstring(result)` gets it working again with `untar`. I'm also curious whether other instances such as `addr(result[r])` in [readAll()](https://github.com/nim-lang/Nim/blob/e206a8d95240e766474d601f529fef1c0026f80f/lib/pure/streams.nim#L89) also need such changes but not able to get it to fail with `newFileStream(xyz).readAll()`.

`addr(result[r])` => `cast[pointer](cast[int](result.cstring)+r)` /?

**Comment by genotrance** [comment]
@data-man: what about `readStr()` and `peekStr()`? There's also instances of addr(strname[x]) in `ssReadData()`, `ssPeekData()` and `ssWriteData()`.

**Comment by data-man** [comment]
@genotrance 
```readStr()``` and ```peekStr()``` works as expected.
