### ISSUE TITLE
parsecfg cannot deal with the empty value pair

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#7880]
file "mydb.cfg" contains:
[default]
dbname=testdb1
client_encoding=UTF8
user=
password=

The following code:
```nim
import parsecfg, tables

var cfg: Config
cfg = load_config("mydb.cfg")
for k, v in cfg["default"]:
   echo k, "=", v
```

The output is:
dbname=testdb1
client_encoding=UTF8
user=password

**Comment by Araq** [comment]
Why would it? The parser is not line based.

**Comment by data-man** [comment]
Reopened.
I'm sure it's a bug. Value of a key can be empty.

**Comment by GULPF** [comment]
The syntax for an empty value is `""`. The syntax in the issue example is invalid, but for some reason `parsecfg` just ignores syntax errors.

**Comment by data-man** [comment]
@GULPF 
> The syntax for an empty value is "".

I saw tens Windows INI files with empty key's values.
https://en.wikipedia.org/wiki/INI_file
But it's
> The INI file format is an informal standard for configuration files for some platforms or software.

**Comment by GULPF** [comment]
@data-man

This is from the documentation of `parsecfg`:

>The parsecfg module implements a high performance configuration file parser. The configuration file's syntax is similar to the Windows .ini format, but much more powerful, as it is not a line based parser. String literals, raw string literals and triple quoted string literals are supported as in the Nim programming language.This is an example of how a configuration file may look like:

So `parsecfg` essentially uses it's own format, which uses `""` for empty values.

**Comment by data-man** [comment]
I've read.
But really for a file with five lines user should write his own parser?
Why not make parsecfg more universal and "smarter"?

**Comment by Yardanico** [comment]
@data-man so we can't use our own formats everywhere and need to follow other ones?

**Comment by data-man** [comment]
@Yardanico 
> our own formats

There's nothing to be proud of.
There were hundreds of different formats (archives, multimedia, etc.) about which no one remembers and no one uses.
In the meantime, the situation is this: newcomers tried Nim, tried using stdlib and step on the first rakes.
And they are told: «this is by design» or «it's our own format».
As a result, Nim loses users.
We need to decide for whom we write software - for ourselves or for users.

**Comment by Yardanico** [comment]
So by your logic we should just make our stdlib similar to python's because there are a lot of python programmers?

**Comment by data-man** [comment]
Sadly, you didn't understand the main thing.
There are other theses?

**Comment by data-man** [comment]
In any case, it isn't for us to decide. :)

**Comment by Araq** [comment]
Well the new standard for this is TOML, but ``parsecfg`` predates TOML. We should have ``parsetoml`` in the stdlib, but ``parsecfg``is what it is.
