### ISSUE TITLE
non-ASCII letters gives error when using object

### ISSUE THREAD

**Issue by Paalon** [nim-lang/Nim#7884]
From https://forum.nim-lang.org/t/3860
The following code

```nim
type Test* = object
  あ: int
  い: int

proc add(test: Test): int =
  test.あ + test.い

let a = Test(あ: 123, い: 122)

echo a
echo add(a)
```

gives the following error

```
test.nim(8, 1) Error: invalid indentation
```

**Comment by tim-st** [comment]
The following seems to work:

```nim
type Test* = object
  `あ`: int
  `い`: int

proc add(test: Test): int =
  test.`あ` + test.`い`

let a = Test(あ: 123, い: 122)

echo a
echo add(a)
```

But I would prefer direct unicode support for variable names too.

**Comment by Yardanico** [comment]
@tim-st it actually exists, probably it's the issue with that specific set of characters:
```nim
let привет = 1
echo привет


type тест = object
  один: int
  два: float

let новый = тест(один: привет, два: 2.0)
echo новый
``` works without any issues

**Comment by tim-st** [comment]
@Yardanico 
Interesting, thanks! I'm pretty sure I had problems with german umlauts when they were it start of the variable name, but I can't recreate the errors with the current version.

**Comment by data-man** [comment]
```nim
import unicode
echo "あ".isAlpha
echo "い".isAlpha
```
true
true

**Comment by Paalon** [comment]
This also gives error.
```nim
import math

type Normal* = object
  μ*: float
  σ*: float

proc entropy*(d: Normal): float =
  (ln(TAU) + 1)/2 + ln(d.σ)

let ε = Normal(μ: 0.0, σ: 1.0)

echo ε
echo entropy(ε)
```

```
test.nim(8, 28) Error: expression expected, but found ')'
```

**Comment by Paalon** [comment]
@Yardanico Your example is also works for greek and japanese.

```nim
type Test* = object
  один: int
  два: int

proc add(test: Test): int =
  test.один + test.два

let a = Test(один: 123, два: 122)

echo a
echo add(a)
```
This also gives error. When using `brabra.brabra` the code emit error.

**Comment by Paalon** [comment]
I think umlaut also gives error.
```nim
type Test* = object
  öl: int
  water: int

proc add(test: Test): int =
  test.öl + test.water

let a = Test(öl: 123, water: 122)

echo a
echo add(a)
```

```
test2.nim(6, 7) Error: undeclared identifier: '.ö'
```

**Comment by jangko** [comment]
this is what the manual says:
> All Nim source files are in the UTF-8 encoding (or its ASCII subset).

> Currently any Unicode character with an ordinal value > 127 (non ASCII) is classified as a letter and may thus be part of an identifier but later versions of the language may assign some Unicode characters to belong to the operator characters instead.

both statements from Nim manual clearly states that Nim language want to support unicode and it is encoded in UTF-8. But if we look into the lexer.getSymbol, it's also clear that it is not a valid UTF-8 decoder.

fixing this bug is not too difficult, besides lexer.getSymbol, perhaps we need to look into identifier comparison, and tweaking sighash/codegen a bit.

but i don't know about the performance impact, probably the performance degradation will not too bad.
or we can make this feature optional, enabled by compiler switch and make some changes to the manual.
