### ISSUE TITLE
`$` not overloaded for ref objects

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#7890]
Is it on purpose that `$` is not overloaded for ref objects? The following doesn't work (obviously deref is possible):

```nimrod
type
  Test = ref object
    a, b, c: int

let o = Test(a: 1, b: 2, c: 3)
echo o
```

**Comment by hlaaftana** [comment]
What would the output be? The same as `$(o[])`? In that case, do you define an overload for `ref (tuple | object)` or all ref types? `ref (tuple | object)` would be a really obscure bloat of the system module, and defining it for all ref types wouldn't seem perfectly logical.

**Comment by Araq** [comment]
On purpose yes. In fact, I sometimes have bugs due to the default ``$`` for object and want to remove it again. ``object`` is about information hiding, you cannot just lift it from the fields.
