### ISSUE TITLE
alloc fails after 4GB

### ISSUE THREAD

**Issue by brentp** [nim-lang/Nim#7894]
on a machine with 20GB of ram and a machine with 256GB, this code:
```Nim
import os

var saved = newSeq[seq[int8]]()

for i in 0..20:
  # one of these is 0.25GB.
  echo i
  var x = newSeq[int8](250000000)
  sleep(1000)
  saved.add(x)

for x in saved:
  echo x.len
```

results in:
```
Traceback (most recent call last)
t.nim(8)                 t
system.nim(755)          newSeq
gc.nim(482)              newSeq
gc.nim(475)              newObj
alloc.nim(794)           rawAlloc
alloc.nim(599)           getBigChunk
alloc.nim(543)           splitChunk
alloc.nim(220)           addChunkToMatrix
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

I can adjust the size of the allocation and this appears to happen suspiciously close to 4GB of total memory. Does not happen with boehm collector (though that does give a warning about the large block).

**Comment by Araq** [comment]
This should not be an issue with ``devel``.

**Comment by Clyybber** [comment]
Still happens on latest devel.

**Comment by Araq** [comment]
Runs just fine for me on Win64. What OS do you use?

**Comment by brentp** [comment]
64bit linux (ubuntu and debian). gcc 5.4.0

mine fails at iteration 19, so maybe bump from 0..100 ?

thanks for looking into it.

**Comment by Araq** [comment]
Works for me even with ``-d:useSysAssert -d:useGcAssert``

**Comment by brentp** [comment]
I just checked with devel:
```
brentp@lorax:~/src/Nim$ ./bin/nim --version
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-06-11
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 1074cc1fb9bd0a69f1990f936dd82313cfb2c2c8
active boot switches: -d:release
```

and I still get:
```
Traceback (most recent call last)
t.nim(8)                 t
system.nim(755)          newSeq
gc.nim(482)              newSeq
gc.nim(475)              newObj
alloc.nim(794)           rawAlloc
alloc.nim(599)           getBigChunk
alloc.nim(543)           splitChunk
alloc.nim(220)           addChunkToMatrix
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/t '
```
anything else I can try or info I can provide?

**Comment by Clyybber** [comment]
Fails for me at the 19th-20th step on latest devel, linux 64bit and gcc 8.1.1 too.

**Comment by Araq** [comment]
Nah, it's fine, thank you. I can kind of reproduce it.

**Comment by mratsim** [comment]
Another case in the forum: https://forum.nim-lang.org/t/4088

**Comment by pb-cdunn** [comment]
Ok. This explains the behavior I've seen. My program takes a number of large input files. I see a crash with the full input, which happens to be about 4GB total (approx. 450 files @ 10MB each). When I remove half, using only half the input, there is no crash. It doesn't matter which half I remove. So yes, this seems to happen right around 4GB.

**Comment by pb-cdunn** [comment]
Uh oh. I seem to have a similar crash on `0.18.0`, so reverting to that is not helping.

`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

The difference is that with `0.18.0`, it crashes well before reading 4GB. (`devel` crashes at about 4GB.) It only reads about 30% of 4GB before crashing.

I don't think reverting to `0.17` is an option, so if this is not fixed soon, I fear we will have to switch to a different programming language and re-write.

**Comment by Araq** [comment]
@pb-cdunn I'm working on it, but as a workaround, I can also make ``-d:useMalloc`` work with the GC. This would circumvent Nim's allocator but everything else would work as before.

**Comment by pb-cdunn** [comment]
That might be a good quick solution. Otherwise, they're suggesting I re-write in C++, which would take several days but would make some people feel good.

I adopted C++ 20 years ago, when everybody told me "C++ is slow", and "New languages are dangerous." I heard the same kinds of fears 10 years ago when I adopted Python. Drives me crazy. But change is difficult. Nim is what C++ and Python should have been all along.

**Comment by pb-cdunn** [comment]
> as a workaround, I can also make -d:useMalloc work with the GC. This would circumvent Nim's allocator but everything else would work as before.

On a branch is fine.

**Comment by Araq** [comment]
One workaround that works for me (TM) is to change ``alloc.nim`` the definition of ``HugeChunkSize`` to

```nim

HugeChunkSize = 100 * 1024 * 1024
```

**Comment by pb-cdunn** [comment]
Crashed. And it crashed sooner than before. I'll try rebuilding all of Nim ...

**Comment by Araq** [comment]
Keep in mind that on Linux memory overcommitment can also produce these very same crashes. And then it would just be an undetected OOM.

**Comment by Araq** [comment]
@pb-cdunn What does ``-d:useSysAssert -d:useGcAssert`` tell you?

**Comment by pb-cdunn** [comment]
```
$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           251G        4.1G        228G         49M         19G        245G
Swap:           31G        518M         31G
$ cat /proc/sys/vm/overcommit_memory
1
```
If that's the problem, how would I avoid it?

**Comment by pb-cdunn** [comment]
With `-d:useSysAssert`, my program is abysmally slow. Maybe someone else can try that, or I can try the example someone posted.

**Comment by pb-cdunn** [comment]
So instead of that change in `alloc.nim`, I've tried
```nim
  25   MaxFli = 25
```
So
```nim
MaxBigChunkSize=33030144
HugeChunkSize=33030145
```
Now it exits fast. I turned on all debuginfo I could find, `-d:useSysAssert -d:useGcAssert -d:nimBurnFree`, and I found nothing at all. Same crash, but much sooner.

**Comment by brentp** [comment]
thank you.

**Comment by pb-cdunn** [comment]
That worked for me too.
