### ISSUE TITLE
Filenames with non-ascii chars fail to compile

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#7897]
The following file `ä.nim` fails to compile on nim 0.18.0 (linux and windows, target gcc):
```nim
echo 1
```

Maybe internally a bit related to https://github.com/nim-lang/Nim/issues/7884 and https://github.com/nim-lang/Nim/issues/3241

**Comment by trustable-code** [comment]
In my opinion we should not allow Unicode characters with an ordinal value > 127 (non ASCII) in filenames.

**Comment by Clyybber** [comment]
Filenames are (at least in unixes) arrays of bytes, so a non ascii unicode character is internally composed of multiple ascii characters. Why should we prohibit those filenames?
