### ISSUE TITLE
Codegen issue with importc object

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#7900]
I'm working on wrapping libarchive and have run into a codegen error. A simple example below.

C header file with a struct
```c
struct abc {
  int def;
};
```

Nim file that imports struct (generated using c2nim --header:headerfile abc.h)
```nim
{.passC: "-I.".}
const headerfile = "abc.h"

type
  abc {.importc: "abc", header: headerfile, bycopy.} = object

var test: abc
```

Nim compiles it fine but gcc errors out.

```
Hint: used config file 'C:\Users\gt\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: a [Processing]
a.nim(6, 5) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
CC: a
CC: stdlib_system
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -I.  -IC:\Users\gt\.choosenim\toolchains\nim-0.18.0\lib -o C:\Users\gt\Desktop\a\nimcache\a.o C:\Users\gt\Desktop\a\nimcache\a.c' failed with exit code: 1

C:\Users\gt\Desktop\a\nimcache\a.c:33:1: error: unknown type name 'abc'; use 'struct' keyword to refer to the type
 abc a_CRXu5JbqbSlTgHYyE9cHHuQ;
 ^~~
 struct
```

If I make the above line to `struct abc a_CRXu5JbqbSlTgHYyE9cHHuQ;`, it compiles fine.

Meanwhile, if I run c2nim without the --header:headerfile flag, it generates
```nim
type
  abc {.bycopy.} = object

...
```
If I use that version, it works fine but it won't work for libarchive which has a bunch of procs which need the importc. Running with --header is also not an option since I am running c2nim through nimgen which generates temporary files so --header points to a non-existent file.

**Comment by Araq** [comment]
This is not a bug, use ``.importc: "struct abc"`` instead. Maybe it's a c2nim issue though.
