### ISSUE TITLE
Support empty toOpenArray

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#7904]
Currently can't create an empty openArray out of `toOpenArray`. I recall some conversation about `str[x .. y]` becoming an openArray in some cases, so I thought this would be allowed:

```nim
proc bar(s: openArray[char]) =
  assert s.len == 0

proc foo() =
  var s = "asd"
  bar(toOpenArray(s, 0, -1))
  bar(toOpenArray(s, 1, 0))

foo()
```

**Comment by data-man** [comment]
Can be closed?
