### ISSUE TITLE
Calling `len` on array passed into inline-iterator using generic Iterable concept crashes compiler

### ISSUE THREAD

**Issue by elemakil** [nim-lang/Nim#7908]
I am new to nim and thus it is quite possible that my code is neither valid nor idiomatic `nim`. However, it seems to crash the compiler which is not good in any case.

My minimal code example is:

````nim
type 
  Iterable[T] = concept iterable
    for item in iterable:
      type(item) is T

iterator test[T](it: Iterable[T]): T =
  let total = len(it)
  for t in it:
    yield t

for j in test([1,2,3,4]):
  echo("j=" & $j)
````

Which I compile and run with `nim c -r foo.nim` which then outputs:

````
Hint: used config file '/usr/local/Cellar/nim/0.18.0_1/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: foo [Processing]
foo.nim(7, 7) Hint: 'total' is declared but not used [XDeclaredButNotUsed]
foo.nim(11, 14) template/generic instantiation from here
foo.nim(11, 14) template/generic instantiation from here
Error: internal error: invalid kind for last(tyUserTypeClassInst)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
````

Removing the line `let total = len(it)` produces a program that runs with the expected output. Replacing the array literal by a sequence literal (i.e. `[1,2,3,4]` -> `@[1,2,3,4]`) also produces the expected output. This may be related to #6277, however, I can confirm that the test-case included in #6277 does not crash my compiler. 

I am on MacOS 10.11.6; I have installed nim using `brew`; `nim --version` outputs:

````
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
````

I'm afraid I don't have the `koch` executable, otherwise I'd post the stacktrace as advised in the error message. Is it possible to install it without (re)compiling nim?

**Comment by genotrance** [comment]
Works fine on #head.

**Comment by andreaferretti** [comment]
Confirmed
