### ISSUE TITLE
Strange behaviour when seq is passed as last argument of varargs proc

### ISSUE THREAD

**Issue by xzfc** [nim-lang/Nim#7914]
`Nim Compiler Version 0.18.0 [Linux: amd64]`

```
import strutils

proc fn(arg: varargs[string, `$`]) =
  echo arg.join(" ")

fn(0, 1, @["2", "3", "4"])
fn(0, 1, $(@["2", "3", "4"]))
```
Expected the same output on both lines, but the actual output is the following:

```
2 3 4
0 1 @["2", "3", "4"]
```

---

Another example:

```
proc fn(arg: varargs[int]) =
  echo @arg

fn(0, 1, @[2, 3, 4])
```

It outputs `@[2, 3, 4]`, but it should not be compiled at all.

**Comment by data-man** [comment]
Now outputs:
1. ```Error: cannot convert seq[string] to varargs[string]```
2. ```Error: cannot convert seq[int] to varargs[int]```

**Comment by narimiran** [comment]
This was fixed by https://github.com/nim-lang/Nim/pull/8186 and produces the errors mentioned in the comment above.
