### ISSUE TITLE
`/` works for int,int32 but not for int64 + unsigned

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7920]
```nim
echo(4'i64 / 8'i64)
```

Presumably this should be possible.

## links
(EDIT)
[Dividing duration - Nim forum](https://forum.nim-lang.org/t/7263)

**Comment by andreaferretti** [comment]
Don't we have the `lenientops` module already for this case? For integers, we have `div` for integer division, to get flloating point division one cast cast to float or import `lenientops`

**Comment by dom96** [comment]
> Don't we have the lenientops module already for this case?

Yeah, we do. Sadly ``lenientops`` doesn't offer this either.

> Forcing the programmer to write the float conversion explicitly makes it a bit more clear that the precision might be bad.

👍

**Comment by narimiran** [comment]
Since the explanation why this is not implemented (and the problems connected to it) was given, this can be closed.

**Comment by krux02** [comment]
Well there is is ``proc `/`(x, y: int): float``. And this should exist or not exist for the same reasons as ``proc `/`(x, y: int64): float`` which does not exist. For me this is an issue of ``Why isn't ``int`` an alias ``int64``, like ``float`` is an alias to ``float64``?

**Comment by avitkauskas** [comment]
Well, really. On 64-bit systems `int` is `int64` and behaves the same as in the explanation above:
```nim
let a = high(int)
let b = a / (a - 10)
let c = a / (a - 500)

doAssert(b == c)
```

**Comment by al6x** [comment]
Possible improvements would be a better error message explaining this problem. Right now the error message is confusing:

```Nim
let v: int64 = 100
echo v / 10
```

Message  `Error: type mismatch: got <int64, int literal(10)>`

**Comment by timotheecour** [comment]
this came up again in https://forum.nim-lang.org/t/7263 and is indeed suprising behavior.

re-opening for reasons already given, for eg in https://github.com/nim-lang/Nim/issues/7920#issuecomment-483366579 or https://github.com/nim-lang/Nim/issues/7920#issuecomment-483373635
```nim
proc main[T]()=
  var a = T(1)
  var b = T(2)
  echo a / b

main[int]() # ok
main[int32]() # ok
main[int64]() #  Error: type mismatch: got <int64, int64>
# ditto
# main[uint64]() 
# main[uint]()
# main[uint32]()
```

this is inconsistent:
* either `/` should be deprecated for `int` (may be most logical) with a msg pointing to using `a.float / b.float` 
* or `/` should be added for SomeInteger

**Comment by juancarlospaco** [comment]
```nim
echo 4.uint8 / 2.uint8
echo 4.uint16 / 2.uint16
echo 4.uint64 / 2.uint64
echo 4.byte / 2.byte
```

**Comment by Araq** [comment]
There is no bug here. "inconsistent" is not a bug, it's a word.
