### ISSUE TITLE
Rename SomeNumber to SomeReal

### ISSUE THREAD

**Issue by Paalon** [nim-lang/Nim#7925]
Currently,

```nim
type
  SomeReal* = float|float32|float64
    ## type class matching all floating point number types
  SomeNumber* = SomeInteger|SomeReal
    ## type class matching all number types
```
However, floating point number is *NOT* real number. Floating point number is floating point number. This should be `SomeFloat`. `SomeInteger|SomeFloat` should be `SomeReal`.
The name `SomeNumber` should be like:
```nim
type SomeNumber* = SomeReal|SomeComplex|...
```

**Comment by Yardanico** [comment]
@Paalon please search in devel docs (and not in 0.18.0) before submitting your issue. SomeReal is already SomeFloat in devel.

**Comment by Paalon** [comment]
Sorry my fault. How to see the devel docs?

**Comment by Yardanico** [comment]
@Paalon why did you close this issue? SomeNumber is still here in devel.
And about docs - you would have to generate them yourself

**Comment by andreaferretti** [comment]
`SomeReal` used to be any floating point value. Now that has been renamed to `SomeFloat`, but we cannot use `SomeReal` in place of `SomeNumber`, because that would cause a backwards compatibility issue. I suggest that we keep `SomeFloat` and `SomeNumber` as they are today, and close this issue

**Comment by Yardanico** [comment]
@andreaferretti and what about TS proposing this addition to SomeNumber (SomeComplex):
type SomeNumber* = SomeReal|SomeComplex|...

**Comment by andreaferretti** [comment]
It does make sense, but it is breaking anyway - if someone wrote some proc that only works on real numbers and used the `SomeNumber` concept, after the change it would accept a complex number as well, which may not be intended

**Comment by Paalon** [comment]
How about `Real = SomeInteger|SomeFloat` and `Number = Real|Complex`?

**Comment by Araq** [comment]
Name it ``ComplexOrNumber`` or something, but there are no ``real`` numbers in computing.

**Comment by narimiran** [comment]
> I suggest that we keep `SomeFloat` and `SomeNumber` as they are today, and close this issue

Agreed. This is a breaking change for no real benefit. Closing.
