### ISSUE TITLE
Compiler reading from null when using the tables library

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#7926]
The file I'm trying to compile uses the tables library from the stdlib. When I try to compile it, my v0.18.0 hash 5ee9e86c87d831d32441db658046fc989a197ac9 compiler reads from nil.

My source is here: https://github.com/kayabaNerve/Currency/blob/master/src/Reputation/State.nim.
I'm also using the following config: https://github.com/kayabaNerve/Currency/blob/master/src/nim.cfg. 

The exact output is this:

Hint: State [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

When I use `koch temp c file`, to get a traceback, I also get this output https://pastebin.com/pFGyQ7Tk.

**Comment by Yardanico** [comment]
@kayabaNerve just a small suggestion - don't use pastebin - it contains ads, needs JS and a lot of other things. Use gist or bpaste or any other similar pasting service :)

**Comment by dom96** [comment]
s/``Table``/``Table[string, BN]``/

**Comment by dom96** [comment]
Also I wouldn't be surprised if this is already fixed in ``devel``.

**Comment by kayabaNerve** [comment]
Thanks! Solved.
