### ISSUE TITLE
There's no `$` for openArray

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#7940]
```nim
import strformat
proc foo(x: openArray[int]) =
  echo fmt"{x}"
```

Compiling that gives this error:

```
lib/pure/strformat.nim(268, 13) Error: type mismatch: got <openarray[int]>
but expected one of:
proc `$`(x: string): string
proc `$`(s: WideCString): string
proc `$`[T: tuple |
    object](x: T): string
proc `$`(x: uint64): string
proc `$`(x: int64): string
proc `$`[T, IDX](x: array[IDX, T]): string
proc `$`[Enum: enum](x: Enum): string
proc `$`(w: WideCString; estimate: int; replacement: int = 0x0000FFFD): string
proc `$`[T](x: set[T]): string
proc `$`[T](x: seq[T]): string
proc `$`(x: int): string
proc `$`(x: cstring): string
proc `$`(x: bool): string
proc `$`(x: float): string
proc `$`(x: char): string
```

**Comment by Yardanico** [comment]
that's because $ is not defined for openarray

**Comment by kaushalmodi** [comment]
Ah, was just going to comment on that.. here's an even smaller example:

```
proc testOpenArray(x: openArray[int]) =
    echo x 
```

**Comment by data-man** [comment]
From my patched superpupercool system.nim :)
```nim
proc `$`*[T](x: openarray[T]): string =
  ## generic ``$`` operator for openarrays that is lifted from the components
  ## of `x`. Example:
  ##
  ## .. code-block:: nim
  ##   $(@[23, 45].toOpenArray(0, 1)) == "[23, 45]"
  collectionToString(x, "[", ", ", "]")
```

**Comment by Yardanico** [comment]
@data-man what do you have in your patched superpupercool system.nim and why you don't make PRs? 💃

**Comment by kaushalmodi** [comment]
@data-man Of course I tried it and didn't work.. your superpupercool system.nim has `collectionToString` defined too :P

**Comment by Yardanico** [comment]
@kaushalmodi no, collectionToString is a proc defined in system.nim, but it's not exported.

**Comment by data-man** [comment]
@Yardanico 

Because PRs for system.nim often isn't accepted.

> what do you have in your patched superpupercool system.nim

Many **T**hings. :-D

**Comment by Yardanico** [comment]
@data-man well, you should at least try to make a PR, so there will be a discussion and people will decide if it's good to put it in system.nim

**Comment by data-man** [comment]
_Should_ try?
No, I'll spend my time better.

**Comment by Yardanico** [comment]
Well, it means that you don't want to contribute to Nim 🗡

**Comment by Yardanico** [comment]
@data-man I didn't mean that you should just commit, I've meant that you should make PRs, but ok :D

**Comment by data-man** [comment]
@Yardanico 

I hope that Araq wouldn't object to this improvement. ;)
