### ISSUE TITLE
JS compile error with insert + inline

### ISSUE THREAD

**Issue by michael72** [nim-lang/Nim#7942]
The following code fails to compile with JS / nodejs backend (current develop)

```nim
import sequtils

type
  Foo* = ref object
    items: seq[int]

{.push inline.}
proc bar*(s: Foo) =
  s.items.insert(0, 0)
{.pop.}
```
compiling with
```console
nim js -d:nodejs chk.nim
```
I get the compile output:
```console
Hint: system [Processing]
Hint: chk [Processing]
Hint: sequtils [Processing]
Hint: macros [Processing]
chk.nim(9, 10) template/generic instantiation from here
lib\system.nim(1593, 7) template/generic instantiation from here
chk.nim(7, 8) Error: attempting to call undeclared routine: 'inline'
```
using `{.inline.}` instead of `{.push inline.}` and `{.pop.}` or calling some other function than `insert` solves the problem.

**Comment by Araq** [comment]
``push inline`` is not a thing. It's ``push callconv: inline`` iirc and the inline directive is ignored for the JS target anyway.
