### ISSUE TITLE
MultipartData format proc should be exposed to retreive content

### ISSUE THREAD

**Issue by Imperator26** [nim-lang/Nim#7945]
I'd like to be able to retrieve what's inside a `MultipartData` object. I noticed that the `httpclient` module uses the proc `format` but it doesn't have the `*` so it can't be used outside of the module. Is it possible to expose it?

**Comment by dom96** [comment]
Plenty of hacky ways to do it, but you may as well make a PR.

**Comment by Imperator26** [comment]
Pull request #7946
