### ISSUE TITLE
nim with clang does not generate pdb files on windows

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#7957]
Running nim with verbosity 3, I see these commands - 
```
clang.exe -c  -w -g -gcodeview -IC:\Nim\lib -o C:\Users\alpha\Desktop\n\nimcache\t.o C:\Users\alpha\Desktop\n\nimcache\t.c
clang.exe -c  -w -g -gcodeview -IC:\Nim\lib -o C:\Users\alpha\Desktop\n\nimcache\stdlib_system.o C:\Users\alpha\Desktop\n\nimcache\stdlib_system.c
clang.exe   -o C:\Users\alpha\Desktop\n\t.exe  C:\Users\alpha\Desktop\n\nimcache\t.o C:\Users\alpha\Desktop\n\nimcache\stdlib_system.o
```

--------------------------
Note - 
`clang.options.debug = "-g -gcodeview"`
in `nim.cfg`
and compiled using `nim c --debugger:native --verbosity:3 t.nim`

---------------------------
After manually modifying the last command to include `-g`, I get a pdb file but source file information is completely wrong.

**Comment by cooldome** [comment]
Please confirm if you have used command line switch: ``-debugger:native``

**Comment by nc-x** [comment]
Command used to compile - `nim c --debugger:native  --verbosity:3  t.nim`
