### ISSUE TITLE
Can't use using statement with object fields

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#796]
The following example doesn't compile:
```nimrod
type
    Wrapper = object
      s: string

when isMainModule:
  var s = ""
  using s
  add("something")
  echo s
  var x: Wrapper
  x.s = ""
  using x.s
  add("something")
  echo x.s
```
The compiler complains that ``'x.s' is not a variable, constant or a proc name``. Can the ``using`` statement be extended to object fields?

**Comment by Araq** [comment]
This works with the new ``.this`` pragma now. ``using`` now does something else.
