### ISSUE TITLE
latest devel nim cannot compiled with vc2003, vc2005, vc2008, vc2012

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#7968]
The latest devel nim compiler generated the following error:
```nim
compiler_vm.obj : error LNK2019: unable to resolve symbol _log2
```

Seems the log2 is not exist before vc2013.

**Comment by jangko** [comment]
> Seems the log2 is not exist before vc2013.

that's right, before vc2013, msvc only support C89 and not C99. see #4532
vc2010 should also affected by this.

Like `trunc` from #4532, one possible solution is to implement it in Nim:

```Nim
proc log2(n: float64) : float64 = log10( n ) / log10( 2 )
```
