### ISSUE TITLE
[typetraits] Tuple type name confusion

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#7976]
Hello,

I don't know how to correctly describe this bug.. see the below examples to understand the issue.

```nim
import strformat, typetraits
type Person = tuple[name: string, age: int]
let 
  person1: Person = ("Peter", 30)
  person2 = (name : "Peter", age : 30)
echo fmt"Tuple person1 of type {$person1.type} = {person1}"
echo fmt"Tuple person2 of type {$person2.type} = {person2}"
```

```text
Tuple person1 of type Person = (name: "Peter", age: 30)
Tuple person2 of type Person = (name: "Peter", age: 30)
                      ^^^^^^ <-- was expecting "tuple[name: string, age: int]" here
```

```nim
import strformat, typetraits
type Person = tuple[name: string, age: int]
let 
  person1 = (name : "Peter", age : 30)
  person2: Person = ("Peter", 30)
echo fmt"Tuple person1 of type {$person1.type} = {person1}"
echo fmt"Tuple person2 of type {$person2.type} = {person2}"
```
```text
Tuple person1 of type tuple[name: string, age: int] = (name: "Peter", age: 30)
Tuple person2 of type tuple[name: string, age: int] = (name: "Peter", age: 30)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <- was expecting "Person" here
```

---

As `Person` is type `tuple[name: string, age: int]`, the type "name" gets stuck to the first type I use to declare the variable.

**Comment by Vindaar** [comment]
It actually seems to be even weirder (at least to me). It's not the order in which you declare the variable, but the order in which you print the names:
```nim
import strformat, typetraits
type Person = tuple[name: string, age: int]
let 
  person1: Person = ("Peter", 30)
  person2 = (name : "Peter", age : 30)
echo fmt"Tuple person1 of type {$person1.type} = {person1}"
echo fmt"Tuple person2 of type {$person2.type} = {person2}"
```
prints them both as `Person`, whereas
```nim
import strformat, typetraits
type Person = tuple[name: string, age: int]
let 
  person1: Person = ("Peter", 30)
  person2 = (name : "Peter", age : 30)
echo fmt"Tuple person1 of type {$person2.type} = {person2}"  # simply moved up
echo fmt"Tuple person2 of type {$person1.type} = {person1}"
```
prints them as `tuple`. But if instead of `$` one directly calls `name` it works just fine:
```nim
import strformat, typetraits
type Person = tuple[name: string, age: int]
let 
  person1: Person = ("Peter", 30)
  person2 = (name : "Peter", age : 30)
echo fmt"Tuple person1 of type {name(person1.type)} = {person1}"
echo fmt"Tuple person2 of type {name(person2.type)} = {person2}"
```
prints the first as `Person` and the second as `tuple` as one would expect.

**Comment by timotheecour** [comment]
see this comment https://github.com/nim-lang/Nim/issues/8569#issuecomment-411503153

**Comment by kaushalmodi** [comment]
Interesting. I just rebuilt Nim devel and looks like this issue got fixed by a positive side-effect of some commit :D

@timotheecour @Araq If you guys know which commit could have fixed this, please link that commit here for future reference. Thanks to whoever fixed this 👍

**Comment by timotheecour** [comment]
@kaushalmodi  @Araq I verified that it was as a side effect of my recent PR https://github.com/nim-lang/Nim/pull/10071; not exactly sure why though.
I'm adding a test case so we avoid future regressions (we should always add a test case before closing!)=> see PR https://github.com/nim-lang/Nim/pull/10169

**Comment by kaushalmodi** [comment]
This issue has been fixed for a while; closing it.
