### ISSUE TITLE
Corrupted strings when passing data to C

### ISSUE THREAD

**Issue by floydnunez** [nim-lang/Nim#7993]
I have a C program that calls Nim code, obvs after a call to NimMain().

I keep a sequence of a complex type on the nim side, which C accesses by its index. This type contains two cstring. I malloc this type on the C side, pass it to a function on Nim, which copies its data from the sequence element, and thus the C side can control the lifetime of this object.

The two cstrings in the complex type contain trash, or sometimes strings I used on debugging statements. The cints in the type are correct.

Stepping with GDB reveals the type is already corrupted on the sequence on the nim side.

The complex data type has 6 elements, and the program starts failing with a sequence of 128 elements. With 127 everything works fine. Also, the corruption begins on the first elements, and normally after the element 40 everything works fine. It seems it depends on the number of elements in the type, as when I was building an example, the bug disappeared when I took out one element of the struct, but it came back when raising the sequence size to 256.

I am on Windows, with MinGW 6.3.0 and Nim 0.18.0

nim_side.nim:
```
import strutils

type
  PART_DATA {.exportc.} = object
    part_number: cint
    top_data: cstring
    bottom_data: cstring
    icon: cint
    part_type: cint
    some_data: cint

var current_data_set: seq[PART_DATA]

proc load_part_data(data_group: cint) {.exportc.} =
  current_data_set = @[]
  for i in countup(0, data_group - 1):
    let elem = PART_DATA(part_number: cint(i), top_data: cstring("first string:" & intToStr(int(data_group))), 
      bottom_data: cstring("second string:" & intToStr(i)), 
      icon: cint(2), part_type: data_group, some_data: cint(3))
    current_data_set.add(elem)

#needed so part_data is exported correctly?
proc placeholder_1(): PART_DATA {.exportc.} =
  discard
  
proc get_part_by_ref(part_number: cint, refer: ptr PART_DATA) {.exportc.} =
  echo "before get"
  let obj = current_data_set[int(part_number)]
  echo "get done!: ", obj.top_data
  refer.part_number = obj.part_number
  refer.top_data = obj.top_data
  refer.bottom_data = obj.bottom_data
  refer.icon = obj.icon
  refer.part_type = obj.part_type
  refer.some_data = obj.some_data 
```

main.c
```
#include <stdlib.h>
#include <stdio.h>
#include "nim_side.h"


int main(int argc, char* argv[]) {
	NimMain();

	int size = 129;
	if (argc > 1){
		size = atoi(argv[1]);	
	}
	printf("sequence size: %d\n", size);

	load_part_data(size);
	for (int index = 0; index < size; index++) {
		PART_DATA* elem_ref = malloc(sizeof(PART_DATA));
		get_part_by_ref(index, elem_ref);
		printf("index: %d part_number: %d top_data: %s bottom_data: %s icon: %d part_type: %d some_data: %d\n", 
			index, elem_ref->part_number, elem_ref->top_data, elem_ref->bottom_data,
			elem_ref->icon, elem_ref->part_type, elem_ref->some_data);
		free(elem_ref);
	}
	printf("end!\n");
}
```

Makefile

```
CC=gcc
WARNINGS= -Wall -Wextra -Wshadow 
NIM_INCLUDES=-Inimcache -I /3htp/nim/nim-0.18.0/lib 

OS := $(shell uname)
ifeq ($(OS),Darwin)
  INCLUDES = -I ../include -L .
  NIM_INCLUDES=-I nimcache -I /usr/local/bin/nim/lib/
endif

DEPS = nimcache/nim_side.c
#gotta add all the .o in nimcache. Need at least one entry for every nim library used!
#stdlib.o: needed by system
#stdlib_strutils and the rest of that line, needed by strutils
OBJ = nimcache/nim_side.o \
      nimcache/stdlib_system.o \
      nimcache/stdlib_strutils.o nimcache/stdlib_parseutils.o nimcache/stdlib_math.o nimcache/stdlib_algorithm.o \
      main.o 
C_OPTIONS = -Wno-incompatible-pointer-types $(WARNINGS) 
CFLAGS = -g

test.exe: $(OBJ)
	$(CC) $(OBJ) -o test.exe $(CFLAGS) $(NIM_INCLUDES) $(INCLUDES) 
	@echo "\n\nSUCCESS!\n\n"

nimcache/%.o: nimcache/%.c
	$(CC) -c -o $@ $< $(CFLAGS) $(NIM_INCLUDES) 

main.o: main.c 
	$(CC) -c main.c -o main.o $(CFLAGS) $(INCLUDES) $(NIM_INCLUDES) $(C_OPTIONS) 

nimcache/nim_side.c: nim_side.nim
	nim c --noMain --noLinking --header:nim_side.h nim_side.nim

clean:
	rm *.o nimcache/* test.exe 

```

**Comment by floydnunez** [comment]
Adding echo statements around the objects creations makes the problem way worse, so I assume I am mangling the string pointers somehow.

**Comment by yglukhov** [comment]
Could it be wrong GC stack initialization? Try adding `GC_disable()` in the top scope of your nim file.

**Comment by floydnunez** [comment]
That fixes it, but don't know if that's what I want?

I will most definitely do more complex stuff on the nim side that will require the GC.

**Comment by floydnunez** [comment]
Compiling with --gc:v2 also fixes it (while removing GC_disable()), so I am gonna go with that for now, even tho the documentation says it is not production ready.

**Comment by Araq** [comment]
This is wrong

```nim

bottom_data: cstring("second string:" & intToStr(i))
```

The GC creates the string and is allowed to free it, you don't ``GC_ref`` it.

**Comment by floydnunez** [comment]
Aaah, ok.

This also explains what I was doing wrong.

https://forum.nim-lang.org/t/2743

Thanks.
