### ISSUE TITLE
creating nkState doesn't work

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#7994]
```
import macros

macro states(): untyped =
   result = newStmtList()
   let s = newTree(nnkState, newIdentNode("world"))
   s.add newTree(nnkStmtList, newCall(bindSym"echo", newStrLitNode("hello")))
   result.add s
   result.add newTree(nnkGotoState, newIdentNode("world"))
   echo result.repr

states()
```
Fails with:

```
testgoto.nim(13, 7) template/generic instantiation from here
testgoto.nim(6, 22) Error: undeclared identifier: 'world'
```

**Comment by Araq** [comment]
Where is it documented that you are allowed to create such a node with a stmt list?

**Comment by yglukhov** [comment]
I would prefer for `nkState` to work like `nkBlock` as well. Currently `nkState` has to contain a label only, and then be followed by its "children":
```
nkStmtList(
  nkState(nkIntLit(123)),
  stmt1,
  stmt2,
  # ...
)
```
This smells a lot like a C label (which in fact it is), while it should be more structured.

**Comment by Araq** [comment]
The problem with ``nkState`` and its goto sibling is that the AST officially does not support these. Otherwise all the macro transformations that we write would need to work on unstructured control flow which is hard.

**Comment by yglukhov** [comment]
Well, I agree that `nkState` should not be used at all in user code. Especially at this point, when it's semantics will likely change. Should we somehow remove it from `macros.nim`?

**Comment by Araq** [comment]
Well some macros might want to implement their own ``.closure`` iterator transformations, so it's a tough problem with no obvious solutions.

**Comment by yglukhov** [comment]
With the recent changes it is now technically possible to give `nkState` block-like semantics. In fact that's the only way I see for JS backend to support closure iters. There are some small details to be figured though.
