### ISSUE TITLE
The condition variables API is incomplete

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#7998]
At the moment Nim offers just a pair of `signal` and `wait` APIs for its condition variables:
https://github.com/nim-lang/Nim/blob/master/lib/core/locks.nim#L5

In other programming languages there are separate calls such as `notifyOne`, `notifyAll` or even `notify(n)` when signalling the condition:

https://en.cppreference.com/w/cpp/thread/condition_variable
https://docs.python.org/3/library/asyncio-sync.html#asyncio.Condition

Furthermore, perhaps async options may be provided over the same underlying OS primitives. @cheatfate should be able to comment on this as he has implemented similar APIs in his [asynctools](https://github.com/cheatfate/asynctools) repo.

The [threadpool module](https://github.com/nim-lang/Nim/blob/devel/lib/pure/concurrency/threadpool.nim#L20) defines additional primives such as a `Semaphore` which are currently not exported. I think these can be moved to the `locks` module and exported.

**Comment by zielmicha** [comment]
I don't think its possible to implement async mutexes etc using pthreads (I have implemented async mutexes using Futures, the same is done in asynctools)

**Comment by yglukhov** [comment]
Well there's at least one way to do that. Lock the mutex in a background thread, and signal the main thread when it's locked. Can't say anything about how practical it would be :)

**Comment by Clonkk** [comment]
> In other programming languages there are separate calls such as notifyOne, notifyAll or even notify(n) when signalling the condition:


> The threadpool module defines additional primives such as a Semaphore which are currently not exported. I think these can be moved to the locks module and exported.

Any news on both these features ? Having semaphore & notifyAll on the standard library would be great

**Comment by disruptek** [comment]
Any thoughts at all?  I don't want to implement something that will be obsoleted...

**Comment by Araq** [comment]
Looks like a minefield and async locks cannot be implemented by Posix locks as @zielmicha noted.
