### ISSUE TITLE
const Table losing object variant data at runtime

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8007]
Const tables are losing values from object variant.

Test case:

```Nim
type
  CostKind = enum
    Fixed,
    Dynamic

  Cost = object
    case kind*: CostKind
    of Fixed:
      cost*: int
    of Dynamic:
      handler*: proc(value: int): int {.nimcall.}

proc foo(value: int): int {.nimcall.} =
  sizeof(value)

const a: array[2, Cost] =[
  Cost(kind: Fixed, cost: 999),
  Cost(kind: Dynamic, handler: foo)
]

# OK with arrays & object variants
echo a # [(kind: Fixed, cost: 999), (kind: Dynamic, handler: ...)]

import tables

const b: Table[int, Cost] = {
  0: Cost(kind: Fixed, cost: 999),
  1: Cost(kind: Dynamic, handler: foo)
}.toTable

# KO with Tables & object variants
echo b # {0: (kind: Fixed, cost: 0), 1: (kind: Dynamic, handler: ...)} # <----- wrong behaviour

const c: Table[int, int] = {
  0: 100,
  1: 999
}.toTable

# OK with Tables and primitive int
echo c # {0: 100, 1: 999}

# For some reason the following gives
#    Error: invalid type for const: Cost
# const d = Cost(kind: Fixed, cost: 999)

# OK with seq & object variants
const d = @[Cost(kind: Fixed, cost: 999), Cost(kind: Dynamic, handler: foo)]
echo d # @[(kind: Fixed, cost: 999), (kind: Dynamic, handler: ...)]

```

**Comment by zah** [comment]
I've done a very brief investigation on this and it seems like a codegen bug.

If you assign some of the wrongly computed expressions to a separate const, the problem goes away:

``` nim
import tables

const b: Table[int, Cost] = {
  0: Cost(kind: Fixed, cost: 999),
  1: Cost(kind: Dynamic, handler: foo)
}.toTable

const cost = b[0].cost
echo cost
``` 

In the codegen, each table access spills the body of the entire table as a local array and a lookup is performed over this array. Besides being quite inefficient, the code generated for this local arrays is what seems to contain the error.

**Comment by LemonBoy** [comment]
The problem is indeed in the codegen phase, the generated code is something like this:
```c
	T4_.kindU.S1.cost = ((NI) 999);
	T4_.kindU.S2.handler = ((NI) 0);
```
Since both `cost` and `handler` overlap the latter will always prevail on the former.
I think the root of the problem is in `opcLdNull` where all the fields are instantianted and the extra ones are never scrubbed once the discriminant is set.
I don't even know if variant types are supposed to be supported by the VM seeing that
```nim
const d = Cost(kind: Fixed, cost: 999)
```
doesn't even compile (but works just fine if you swap `const` with `let`).

**Comment by Araq** [comment]
> I don't even know if variant types are supposed to be supported by the VM seeing that

They work in the VM but the codegen makes no attempt to create the proper const union initializers.
