### ISSUE TITLE
The array primitive is too complex.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#8026]
First of all, I don't want to complain that ``array[MyEnum, MyObject]`` compiles. That is very useful, and I would like to keep this working. 

The problem I have is, how it is implemented. For me the a programming languase has some primitive components, that I can attach together to create more complex structures. And it is important that these primitives are as minimal as possible. A float32 is just a CPU number type. pointers are addresses. 

And now there is the array. An array is not just N elements. It also has this index type that could be anything. Well you can argue for the users of an array, and say how cool it is to use an enum as the index type of an array. But as the writer of generic code this is really bad. Because all of the sudden when I have to implement something for all primitives (for example serialization), I don't just need to deal with the primitives and an array of a length, but I also need to add code that deals with all cases that an array index type can be. 

My proposal is to have a type in system.nim that could be called ``primitiveArray`` that has exactly two generic parameters. The length as an int and the type of the elements. The ``array`` that is used everywhere can be implemented as an alias type for this ``primitiveArray`` type. Then all of a sudden ``array`` isn't a primitive anymore, because ``primitiveArray`` is the primitive then. Compiler backends will become simpler, because they now only need to care about ``primitiveArray`` (more likely to be correct). And generic code that needs to work on all primitives to work on all primitive compositions, will also become simpler and more likely to be correct.

**Comment by mratsim** [comment]
As far as I know, the index can be:

  - an integer N
  - a range of int a..b that does not need to start from 0 (and can even start from a negative)
  - an enum without holes, which maps to a range

Just to make sure we are on the same page, you want to remove ranges and enums indices, which as a side-effect makes all primitiveArrays start at index 0?

**Comment by Araq** [comment]
``int(low(IndexType))..int(high(IndexType))`` in a generic solves your problems without all the fuzz of introducing yet another builtin type. Also the index type cannot be left unspecified since it's an open question of whether this index type would be unsigned or signed.
