### ISSUE TITLE
koch web fails on devel in times_examples.nim

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8032]
```
C: stdlib_algorithm
Hint:  [Link]
Hint: operation successful (21675 lines compiled; 1.339 sec total; 38.75MiB peakmem; Debug Build) [SuccessX]
Hint: /tmp/kmodi/downloads_overflow/Nim/lib/pure/times_examples  [Exec]
times_examples.nim(190)  times_examples
system.nim(3803)         raiseAssert
system.nim(2857)         sysFatal
Error: unhandled exception: toTimeInterval(a) ==
    initTimeInterval(0, 0, 0, 10, 0, convert(Seconds, Hours, -dt.utcOffset), 1, 0, 0, 1970) times_examples.nim(190)  [AssertionError]
Error: execution of an external program failed: '/tmp/kmodi/downloads_overflow/Nim/lib/pure/times_examples '
[Examples] failed
```

To recreate the issue:

```
# set the timezone env var TZ to something else than UTC
koch web
```

.. this assertion is failing:

```nim
block:
    let a = fromUnix(10)
    let dt = initDateTime(1, mJan, 1970, 0, 0, 0, local())
    doAssert a.toTimeInterval() ==
        initTimeInterval(years = 1970, days = 1, seconds = 10,
                         hours = convert(Seconds, Hours, -dt.utcOffset))
```

**Comment by kaushalmodi** [comment]
OK, so if I put `import os` at the very top of `times_examples.nim` and add this `putEnv`, the test passes:

```nim
    putEnv("TZ", "UTC")
    let a = fromUnix(10)
    let dt = initDateTime(1, mJan, 1970, 0, 0, 0, local())
    doAssert a.toTimeInterval() ==
        initTimeInterval(years = 1970, days = 1, seconds = 10,
                         hours = convert(Seconds, Hours, -dt.utcOffset))
```

**Comment by kaushalmodi** [comment]
Workaround:

```
TZ=UTC koch web
```

But that test failing probably means that it's a bug that's revealed for non-UTC time zones?

**Comment by GULPF** [comment]
I don't know if it's the cause, but the test looks wrong. It assumes that the UTC offset consists of whole hours, but that isn't necessarily true (especially not in 1970).

**Comment by skilchen** [comment]
The test also fails for any timezone west of Greenwich. `initTimeInterval` and `toTimeInterval` do not perform any kind of normalization, so if `dt.utcOffset == 3600` the examle code 
```nim
echo initTimeInterval(years = 1970, days = 1, seconds = 10,
                      hours = convert(Seconds, Hours, -dt.utcOffset))
```
will produce: `1970 years, 1 day, -1 hour, and 10 seconds`

but: 
```nim
echo fromUnix(10).toTimeInterval()
```
will produce: `1969 years, 11 months, 31 days, 23 hours, and 10 seconds`

Given to correct documentation comment `To be used when diffing times.` a more appropriate runnable example might be:
```
  runnableExamples:
    let a = fromUnix(10)
    let b = fromUnix(1_500_000_000)
    let ti = b.toTimeInterval() - a.toTimeInterval()
    doAssert a + ti == b
```

Btw. can we eliminate the many warnings `Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]` produced by `nim doc times` (and therefore also by `koch web`)? I think, the warnings are a consequence of the `benign` pragma annotation, which - as far as i understand - is only useful on forward declarations.
