### ISSUE TITLE
nim/pure/asyncmacro.nim not GC-safe

### ISSUE THREAD

**Issue by ibrokemypie** [nim-lang/Nim#8036]
Not sure if this is an issue, but it is stopping me from compiling with this error:
``lib/nim/pure/asyncmacro.nim(361, 31) Error: 'sessionHandleSocketMessageIter' is not GC-safe as it calls 'readData'``

**Comment by andreaferretti** [comment]
Do you have a reproducible example?

**Comment by dom96** [comment]
This likely means that your ``sessionHandleSocketMessage`` async procedure isn't GC-safe.

**Comment by narimiran** [comment]
@ibrokemypie any news on this one? Was the problem the one that @dom96 pointed out? Can we close this?

**Comment by ibrokemypie** [comment]
I don't know what this was related to I am sorry, feel free to close
