### ISSUE TITLE
spawn of threadpool do not return FlowVar when thread proc return void

### ISSUE THREAD

**Issue by 7sDream** [nim-lang/Nim#8040]
```nim
import threadpool

proc echoId(): void {.thread.} =
  while true:
    echo getThreadId()

var thread = spawn echoId()

await thread
```

compile with `nim c -r --threads:on main.nim`, and shows:

```
Error: expression 'spawn echoId(),' has no type (or is ambiguous)
```

two workaroud for this example:

1. Just delete the `var thread =` and use `sync()` instand of `await thread`
2. Use `createThread` and `joinThread` in threads module

But both of them has disadvantage:

1. When I only want to join 1 of 10 `void`-return threads, I can't just use `sync()`
2. When I have both `void`-return and `int`-return threads, I will mix `spawn` and `createThread`, It's confusing and inconsistent

---

Tested in 0.18.0 and devel channel.

---

Workaround: use an int or bool as a return type even if you don't want return anything. thanks @Vindaar

**Comment by Araq** [comment]
Use Malebolgia instead of threadpool.nim.
