### ISSUE TITLE
{.async.} pragma cannot be used for proc types

### ISSUE THREAD

**Issue by b71729** [nim-lang/Nim#8042]
#### Description
The `{.async.}` pragma cannot be used in conjunction with the `proc` type. This is unlike other pragmas such as `{.gcsafe.}` or `{.locks.}`.

#### Repro
```
type Route = tuple[path: Regex, handler: proc(req:Request) {.async.}]
===
"attempting to call undeclared routine: 'async'"
```

#### Workaround
Declare proc as having return type `Future[T]`. Doesn't looks like this then accurately represents the procedure, if it has `{.async.}` applied.

**Comment by Araq** [comment]
``async`` is not a pragma, it is a macro. 

Workaround:

```nim
type Route = tuple[path: Regex, handler: proc(req:Request): Future[void]]
```
