### ISSUE TITLE
Shallow types are not shallow

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#8044]
```nim
type Foo {.shallow.} = object
  v: seq[int]

var s = @[1, 2, 3]
var f: Foo
f.v = s
doAssert((addr f.v[0]) == (addr s[0])) # Fails
```

**Comment by mratsim** [comment]
Actually, shallow types promise that copies are shallow.

Was the initialization supposed to be shallow too?

Copy is still shallow on latest devel

```Nim
type Foo {.shallow.} = object
  v: seq[int]

var s = @[1, 2, 3]
var f: Foo
f.v = s
# doAssert((addr f.v[0]) == (addr s[0]))

let g = f
doAssert((addr f.v[0]) == (unsafeAddr g.v[0]))
```

**Comment by timotheecour** [comment]
ping on this: it's blocking this test in nim-ranges: https://github.com/status-im/nim-ranges/blob/master/tests/ttypedranges.nim#L74
```nim
  test "shallowness":
    var s = @[1, 2, 3]
    var r = s.toRange()
    var r2 = r
    s[0] = 5
    # check(r[0] == 5) # XXX: Uncomment once nim bug #8044 is fixed
    r[1] = 10
    check(r2[1] == 10)
```

**Comment by Araq** [comment]
I doubt this ever worked.

**Comment by yglukhov** [comment]
I must have mixed something up because I can't find a version where it worked differently, went back to 0.17.0.

After all this behavior may be justified as "shallowness doesn't affect field assignments", so maybe it's just a matter of documentation. Anyways I'm ok with this being closed.

**Comment by Araq** [comment]
Ah also I confused with a different issue wrt ``shallow``.
