### ISSUE TITLE
[terminal] Request: styledWrite variant that does not end in a newline

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8046]
`writeLine` is like `write` but with a newline.

We have `styledWriteLine` and `styledEcho`. Both end the output with a newline.

Can a `styledWrite` be added that behaves like `write` i.e. no newline?

*I tried doing it myself but tweaking macros is out of my reach at the moment.*

Related:

In the below excerpt from `styledWriteLine` definition:

```nim
  result.add(newCall(bindSym"write", f, newStrLitNode("\n")))
  if reset: result.add(newCall(bindSym"resetAttributes", f))
```

Why is resetAttributes called **after** the trailing newline? Wouldn't it be cleaner to do the reset before the newline?

**Comment by dom96** [comment]
I guess ``styledWriteLine`` should just be renamed to ``styledWrite``, I assume it's equivalent to ``styledEcho``?

**Comment by kaushalmodi** [comment]
`echo` == `stdout.writeLine` (newline at end)

So the current `styledEcho` == `stdout.styledWriteLine` (newline at end) makes sense!

But.. `write` echoes output without appending with newline. We don't have a `styledWrite` equivalend for that.

**Comment by kaushalmodi** [comment]
ugh; a `writeStyled` already exists, but that writes **only** the `Style` enum values.. does not write `ForegroundColor` or `BackgroundColor`.

Would it be better to rename that to `styledOnlyWrite`? (that does not write newlines too as it calls `write` internally).

So in summary we will end up with these:

1. `styledWriteLine`, `styledEcho` (**already exist**)
2.  `styledWrite` (**this PR adds**)
3.  `styledOnlyWrite (**rename** from `writeStyled`)

The only reason I think the existing `writeStyled` (pt 3 above) needs to stay is that it has some Windows specific code, if not for that, `styledWrite` (style + fg + bg) would be a superset of `writeStyled` (only style).

@Araq?
