### ISSUE TITLE
Converter applied when it should not be

### ISSUE THREAD

**Issue by rokups** [nim-lang/Nim#8049]
```nim
type ustring* = distinct string
converter toUString*(s: string): ustring = ustring(s)
proc `[]`*(s: ustring, i: int): ustring = s
echo "abcdefgh"[1..^2]
```
Results in error: `lib/system.nim(3591, 33) Error: type mismatch: got <ustring> but expected 'char = Char'`.
Removing converter fixes the issue. This used to work in 0.16.

**Comment by cooldome** [comment]
Backward indices are now working in a different way, read release notes of 0.18.0

**Comment by rokups** [comment]
I noticed that, but i do not think this is related. Despite that i tried adding `proc `[]`*(s: ustring; i: BackwardsIndex): ustring = s` but it changed nothing.

**Comment by Yardanico** [comment]
@rokups hmm, strange, for me this works:
```nim
type ustring* = distinct string
converter toUString*(s: string): ustring = ustring(s)
proc `[]`*(s: ustring, i: int): ustring = s
echo "abcdefgh"[1..^2]
```

**Comment by Yardanico** [comment]
@rokups 
```nim
type ustring* = distinct string
converter toUString*(s: string): ustring = ustring(s)
proc `[]`*(s: ustring, slice: HSlice): ustring = s
proc `$`*(s: ustring): string {.borrow.}
let a = ustring("abcdefgh")

echo a[1 .. ^ 2]
```
