### ISSUE TITLE
A question regarding compiler procs that take nodes/types/symbols but not a context

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#8055]
should all procs that take one or more nodes/types/symbols also take a context? Sometimes it's not required semantically, but it might be useful for debugging purposes.

**Comment by Araq** [comment]
No, they shouldn't. For debugging you can use ``newPartialConfig()`` or assign it to a global variable.

**Comment by ephja** [comment]
The problem with the first approach seems to be that the 'fileInfos' field for example won't be populated.

**Comment by Araq** [comment]
Well ok, fair enough, but all the different context object definitions in the compiler have a ``config`` field that can be used for this.
