### ISSUE TITLE
Deprecation warnings for enum values print twice

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8063]
As an example, `styleUnknown` value of the `Style` enum in terminal.nim was deprecated in devel in https://github.com/nim-lang/Nim/commit/4616b28c7b592c8204d9f77f3c1f7db2fb7186d8 using:

```nim
{.deprecated: [styleUnknown: styleItalic].}
```

Now below:

```nim
import terminal
stdout.styledWriteLine("italic text ", {styleUnknown})
```

prints the same warning twice:

```
...
Hint: ospaths [Processing]
test_styleUnknown_deprecation.nim(2, 41) Warning: use styleItalic instead; styleUnknown is deprecated [Deprecated]
test_styleUnknown_deprecation.nim(2, 41) Warning: use styleItalic instead; styleUnknown is deprecated [Deprecated]
```

**Comment by kaushalmodi** [comment]
Above example doesn't work any more after the deprecation of `styleUnknown` was removed in https://github.com/nim-lang/Nim/commit/3f6168b3372013c0d4b938e6a83849199d9756c9.

**Comment by kaushalmodi** [comment]
Here is a new test case:

```nim
type
  Foo* = enum
    fooX

{.deprecated: [fooA: fooX].}

let
  foo: Foo = fooA

echo foo
```

Though, looks like this bug of "double printing of deprecation" got fixed by some other commit. This is fixed as of d0366c519487610ff26d28175e98a9c3ef178670.

@timotheecour Any help on how to add test case for this before I close this issue? Thanks!

**Comment by narimiran** [comment]
> Though, looks like this bug of "double printing of deprecation" got fixed by some other commit. 

On my end also looks ok.

> Any help on how to add test case for this before I close this issue? 

Three weeks was enough of waiting time. I'm closing this.

**Comment by timotheecour** [comment]
> @timotheecour Any help on how to add test case for this before I close this issue? Thanks!

=> https://github.com/nim-lang/Nim/pull/10508

> Three weeks was enough of waiting time. I'm closing this.

@kaushalmodi  just ping me again next time :)
