### ISSUE TITLE
Some bugs with nimpretty

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#8078]
```nim
# comment

var x = 1
```
becomes
```nim
# comment


var x = 1
```

**Comment by BarelyMalicious** [comment]
```nim
while true:
  if true:
    discard
  # comment 3
```
becomes
```nim
while true:
  if true:
    discard                   # comment 3
```

**Comment by BarelyMalicious** [comment]
```nim
proc a() =
  while true:
    discard
    # comment 1

  # comment 2
  discard
```
becomes
```nim
proc a() =
  while true:
    discard
  # comment 1

  # comment 2
  discard
```

**Comment by BarelyMalicious** [comment]
```nim
(not false)
```
becomes
```nim
( not false)
```

**Comment by BarelyMalicious** [comment]
Unhandled exception when file does not exist

```
λ nimpretty a
nimpretty.nim(75)        nimpretty
nimpretty.nim(71)        main
os.nim(528)              copyFile
oserr.nim(66)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
 [OSError]
```

Needs a simple `try except` [here](https://github.com/nim-lang/Nim/blob/2dab490ec10f8aa0b7f8c0001bcef522747346ab/nimpretty/nimpretty.nim#L71)

**Comment by BarelyMalicious** [comment]
```nim
if true: "true" else: "false"
```
becomes -
```nim
if true: "true"else: "false"
```

**Comment by BarelyMalicious** [comment]
```nim
let a =
    if true: 15 # comment 1
    else: 27 # comment 2
```
becomes - 
```nim
let a =
    if true: 15               # comment 1
    else: 27                  # comment 2
```

But 
```nim
let a =
    if true: 15123123123.001230123 # comment 1
    else: 27 # comment 2
```
becomes 
```nim
let a =
    if true: 15123123123.001230123 # comment 1
    else: 27                  # comment 2
```
i.e. comments are not aligned.

**Comment by BarelyMalicious** [comment]
Bikeshedding -
  
```nim
proc longfunctionname(f1: proc (x: int, y: int, z: bool), f2: proc(x: bool, y: bool, z: int)) =
  discard
```
becomes -
```nim
proc longfunctionname(f1: proc (x: int; y: int; z: bool); f2: proc(x: bool;
    y: bool; z: int)) =
  discard
```
  
IMO it should become
```nim
proc longfunctionname(f1: proc (x: int; y: int; z: bool); 
    f2: proc(x: bool; y: bool; z: int)) =
  discard
```
This seems more readable to me.
(Here emphasis should be given on the fact that the 2nd parameter to long function name is split into the new line. Indentation should be whatever seems right)

Same when function call is made.

**Comment by BarelyMalicious** [comment]
```
import strutils

echo "hello".toLowerAscii().toUpperAscii().toLowerAscii().toUpperAscii().toLowerAscii().toUpperAscii().toLowerAscii().toUpperAscii()
```
This gets split up as -
```
import strutils

echo "hello".toLowerAscii().toUpperAscii().toLowerAscii().toUpperAscii(
    ).toLowerAscii().toUpperAscii().toLowerAscii().toUpperAscii()
```

IMO, the closing bracket `)` should have been on the same line, and the next line start with `.`

**Comment by BarelyMalicious** [comment]
It does not take care of functions which have been already split by the developer
  
https://github.com/andreaferretti/patty/blob/fa58873be1cd729d9de3634a5897aacda3bcd890/patty.nim#L201-L204
  
becomes
```nim
newNimNode(nnkElifBranch).add(
      infix(newDotExpr(ident("a"), ident("kind")), "==", newDotExpr(ident("b"),
          ident("kind"))),
      condition
    ),
```

**Comment by dom96** [comment]
> becomes -
>
>```
>proc longfunctionname(f1: proc (x: int; y: int; z: bool); f2: proc(x: bool;
>    y: bool; z: int)) =
>  discard
>```

It should become:

```nim
proc longfunctionname(
  f1: proc (x: int, y: int, z: bool),
  f2: proc(x: bool, y: bool, z: int)
) =
  discard
```

I've recently become a big fan of this layout.

(btw, please make nimpretty output commas already).

**Comment by Araq** [comment]
> It should become:

Meh, I think it's ugly and it is not in our style guide.

**Comment by dom96** [comment]
@Araq you need to be more specific. Also you should explain how you think it should look.

**Comment by andreaferretti** [comment]
The rule of thumb that I use is that if I cannot align things horizontally (because the line becomes too long), then I align them vertically, as @dom96 suggests

**Comment by jshulver-sage** [comment]
I quite like this:

```nim
proc longfunctionname(f1: proc (x: int, y: int, z: bool),
                      f2: proc (x: bool, y: bool, z: int)) = 
  discard
```

Although I guess

```nim
proc reallyActuallyVeryLongFunctionNameThatWouldMakeAJavaDeveloperBlush(f1: proc (x: MyVeryLongParameterisedType[ThisMightBeAConceptOrSomething, LoremIpsumEtc], y: int, z: bool),
                                                                        f2: proc (x: bool, y: bool, z: int)) = 
  discard
```

Doesn't work so well and would look better like:

Although I guess in this situation you might want it to look more like:

```nim
proc reallyActuallyVeryLongFunctionNameThatWouldMakeAJavaDeveloperBlush(
    f1: proc (x: MyVeryLongParameterisedType[Option[OfConcept], LoremIpsumEtc], 
              y: int, z: bool),
    f2: proc (x: bool, y: bool, z: int)) = 
  discard
```

Although in this case there's probably something to be said for shining objects which are not usually very desirable.

**Comment by Araq** [comment]
> Also you should explain how you think it should look.

For me how nimpretty handles it is fine.

Nimpretty breaks up long lines by a simplistic scheme. If it gets it wrong, that means you can reformat this line on your own as long as it fits nimpretty's rules and nimpretty is designed to be cautious about the formatting the programmer did. If you don't like how nimpretty works, feel free to submit PRs but nimpretty's job is not to get arbitrary line wrapping "right". Maybe later versions will do that but so far it's out of its scope.

> (btw, please make nimpretty output commas already).

I like semicolons more though and objectively it helps slightly in readability as there is a clearer distinction between "ident list" separation vs "type list" separation.

**Comment by dom96** [comment]
Semicolons in argument lists is a major showstopper for me to adopt nimpretty so please consider changing this.

**Comment by andreaferretti** [comment]
At the very minimum it should be configurable or respect the existing convention. Trying nimpretty on my own files generates giant diffs just because it changes every `,` into a `;`

**Comment by dom96** [comment]
I'm not sure about making it configurable, AFAIK the idea behind a tool like this is to make all formatting consistent.

**Comment by andreaferretti** [comment]
Most tools that make formatting consistent accept a set of configurations, for instance [scalafix](https://scalacenter.github.io/scalafix/docs/users/configuration)

Since both `,` and `;` are valid I do not see a way to enforce one or the other without making some users unhappy

**Comment by Araq** [comment]
> I'm not sure about making it configurable, AFAIK the idea behind a tool like this is to make all formatting consistent.

Ok, how about this solution: The first usage in this context determines what ``nimpretty`` will use. If you use a ';', all places use ';' consistently, if you use ',', it doesn't touch it. (As it is sometimes required to be ';' for disambiguation.)

**Comment by andreaferretti** [comment]
@Araq I like this solution!

**Comment by timotheecour** [comment]
actually how about the following simple rule instead, based on the following semantic difference bw `,` vs `;` in param list:
```nim
proc foo(a, b: int; c, d: string) = discard # OK
proc foo(a, b: int, c, d: string) = discard # OK
proc foo(a; b: int, c, d: string) = discard # Error: typeless parameters are obsolete
```

suggested rule:
* use `;` only after a list (length>1) of type-less arguments, right after the type, eg: `a, b, c: int;`
* use `,` everywhere else.

eg:
```nim
#input
proc foo(z: int, a, b: int, c, d: string, e: float, f: float)
#rewritten to:
proc foo(z: int, a, b: int; c, d: string; e: float, f: float)
```

**Comment by Araq** [comment]
I disagree that this rule is "simple". :-) I also see no benefits over what ``nimpretty`` currently does (I implemented the idea that I described above).

**Comment by andreaferretti** [comment]
@timotheecour The problem with your proposal is that it will generate giant diffs for some users ( some users prefer `,`, others `;`). The proposal by @Araq is conservative and will keep everyone happy with their prefered style
