### ISSUE TITLE
Incorrect executable name of the C compiler when performing crosscompilation

### ISSUE THREAD

**Issue by xomachine** [nim-lang/Nim#8081]
```bash
$ nim c --os:windows any_file.nim
```
gives an error:
```
Error: execution of an external compiler program 'gcc.exe <...>' failed with exit code: 127
```
As you can see, the compiler executable was invoked with `.exe` extension, and it caused the error.

Further analysis has shown that in this case both of `hostOS` and `targetOS` fields in [the code](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/extccomp.nim#L528-L530) are equal to `osWindows`
Nim version:
```
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-06-20
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 1be82d96a682338ba53832bcc2772b7865b47b57
active boot switches:
```

**Comment by Yardanico** [comment]
BTW, this is how I cross-compile for windows from macOS/linux:
https://github.com/vk-brain/Nickel/blob/master/src/nickel.nims#L21

**Comment by xomachine** [comment]
It looks like the problem lies in the wrong assumption [here](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/platform.nim#L233-L235)

**Comment by data-man** [comment]
> the problem lies in the wrong assumption here

No, it's [here](https://github.com/nim-lang/Nim/blob/devel/compiler/extccomp.nim#L550) and below. :-)

**Comment by xomachine** [comment]
@data-man I don't see any problem in the code you pointed. `.exe` looks like a field where the compiler executable name is taken. The decision about the extension is being made at [this](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/extccomp.nim#L553) line, and the `needsExeExt` function relies on [hostOS and targetOS](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/extccomp.nim#L528-L530) fields, which is being set by [setTarget function](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/platform.nim#L233-L235) from [here](https://github.com/nim-lang/Nim/blob/559a7615ad8e2e169aa9684f034c156881d88d4d/compiler/commands.nim#L596) if `--os` flag is set.

So if I'd want to crosscompile the code to the windows target from Linux, I will set the `--os:windows` option, that causes `hostOS` to become `osWindows` and then `needsExeExt` returns `true`.

**Comment by dom96** [comment]
Suggested workaround: https://irclogs.nim-lang.org/22-09-2018.html#10:07:41

**Comment by LemonBoy** [comment]
@xomachine 
Can you try the following patch?

```diff
diff --git a/compiler/platform.nim b/compiler/platform.nim
index 7eb897816..63657ced9 100644
--- a/compiler/platform.nim
+++ b/compiler/platform.nim
@@ -230,9 +230,9 @@ proc setTarget*(t: var Target; o: TSystemOS, c: TSystemCPU) =
   #echo "new Target: OS: ", o, " CPU: ", c
   t.targetCPU = c
   t.targetOS = o
-  # assume no cross-compiling
-  t.hostCPU = c
-  t.hostOS = o
+  # # assume no cross-compiling
+  # t.hostCPU = c
+  # t.hostOS = o
   t.intSize = CPU[c].intSize div 8
   t.floatSize = CPU[c].floatSize div 8
   t.ptrSize = CPU[c].bit div 8
@@ -251,4 +251,6 @@ proc nameToCPU*(name: string): TSystemCPU =
   result = cpuNone
 
 proc setTargetFromSystem*(t: var Target) =
-  t.setTarget(nameToOS(system.hostOS), nameToCPU(system.hostCPU))
+  t.hostOS = nameToOS(system.hostOS)
+  t.hostCPU = nameToCPU(system.hostCPU)
+  t.setTarget(t.hostOs, t.hostCPU)
```

You'll also have to point `gcc` to the "right" compiler but I guess that was expected.

**Comment by apahl** [comment]
Thanks a lot for making it work again!

Kind regards, Axel
