### ISSUE TITLE
Octal int literal behavior differs from `parseOct` - change `parseOct`?

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#8082]
In a discussion on IRC today (20/06/18) it was noticed that the behavior of octal int literals differs from that of strings of octal numbers, which are parsed.

To be precise, the following for octal int literals:
```nim
let i1 = 0o5   # valid
let i2 = 0O5  # invalid. see below
let i3 = 0c5   # valid
let i4 = 0C5   # valid
```
creating `i2` results in 
```
Error: 0O5 is not a valid number; did you mean octal? Then use one of '0o', '0c' or '0C'
```

Whereas `parseOct` of `parseutils.nim` supports the set of `{'o', 'O'}` as the second character for octals (https://github.com/nim-lang/Nim/blob/master/lib/pure/parseutils.nim#L73).

The question that came up is: should the behavior of `parseOct` respect that of octal int literals? 

Personally I find 'c' and 'C' somewhat weird, since they are both valid values for a hex number. But that's just me. :)

**Comment by kaushalmodi** [comment]
> Personally I find 'c' and 'C' somewhat weird

Same here.

But whatever is decided, it would be nice for the literals and `parseOct` to respect the exact same prefixes.

**Comment by Araq** [comment]
Remove the ``c`` syntax in the compiler/the spec.
