### ISSUE TITLE
`typetraits.name` behaves unexpected

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#8083]
```nim
import typetraits

type A = object
type B = int
type C = A

let b = 1.B
let c = C()
echo b.type.name #B
echo c.type.name #A
```
I expected either 
```nim
echo b.type.name #B
echo c.type.name #C
```
or
```nim
echo b.type.name #int
echo c.type.name #A
```
I would prefer the first result, since the second can be found out without the usage of `typetraits` with `a is int` etc (assuming this doesn't use `typetraits`).

Nim version: 0.18.0 win64

**Comment by Araq** [comment]
Type aliases are just aliases, they cannot be used for some quirky distinction that Nim's type system does **not** make.

**Comment by tim-st** [comment]
Ok, just thought that type `B` is also only an alias of `int` and there the type output is `B` instead of `int` e.g. the type output is the alias name.
