### ISSUE TITLE
Module `sequtils`: should provide `mzip`

### ISSUE THREAD

**Issue by lucatrv** [nim-lang/Nim#8102]
As in subject, example:
```
import sequtils
var array1 = [1, 2, 3, 4]
var array2 = [3, 4, 5, 6]
for x in mzip(array1, array2):
  x.b += x.a
```

**Comment by krux02** [comment]
I tried to implement mzip. The problem is that the compiler doesn't allow to implement mzip, and that is the real problem. Here is my experiment:

```nim
iterator mzip[T,U](arg1: var openArray[T], arg2: var openArray[U]): (var T,var U) {.inline.} =
  var i = 0
  let len = min(len(arg1), len(arg2))
  while i < len:
    yield((arg1[i], arg2[i]))
    i += 1

var array1 = [1, 2, 3, 4]
var array2 = [3, 4, 5, 6]
for a, b in mzip(array1, array2):
  a += b

echo array1
```

this shoul work, but it doesn't I get the following compile error:

```
scratch.nim(6, 25) Error: 'arg2' is not the first parameter; context: 'arg2[i]'; see https://nim-lang.org/docs/manual/var_t_return.html
```

The link provided in the error message doesn't work anymore.

**Comment by hlaaftana** [comment]
Apparently this exact iterator has been mentioned in #7373, and I think these two ideas not complementing each other is part of the reason for the new for loop macros which this would have to utilize if that was the case.

**Comment by krux02** [comment]
well an inferior version of mzip does work

```nim
iterator mzip[A,B](a: var openarray[A]; b: openarray[B]): tuple[a: var A; b: B] =
  let len = min(len(a), len(a))
  var i = 0
  while i < len:
    yield((a[i], b[i]))
    i += 1

var array1 = [1, 2, 3, 4]
var array2 = [3, 4, 5, 6]
for a,b in mzip(array2, array1):
  a += b

echo array1
echo array2
```

**Comment by narimiran** [comment]
This was discussed (again) internally and we decided to reject this feature request, sorry.
