### ISSUE TITLE
Scintilla Nim(rod) outdated lexer

### ISSUE THREAD

**Issue by xv** [nim-lang/Nim#8111]
Back in 2009, Andreas (@Araq) submitted the Nim(rod) lexer for Scintilla. The lexer is now outdated and is missing the `#[ ... ]#` block comment feature, as well as case-sensitivity(?) and an updated language name.

~~From what I understood, the Nim lexer is based on the Python one, and Python does not support the new block comment styling. Thus, an updated version may require its own definitions now~~. Not entirely. Though it does use Python's `SCE_P_XXX` definitions.

Neil Hodgson, the head of Scintilla, states that submitting and updating lexers is the sole responsibility of the contributor. So, we can't expect him to update it himself.

~~Any willingness to work on that?~~ See below.

**Comment by xv** [comment]
I forked Scintilla and made these two commits:

[5f36b99](https://github.com/xv/scintilla/commit/5f36b9953efb9dd59a2346d0373df4aeb8fceef6) - `Add styling for #[ .. ]# block comment`
[4b76c69](https://github.com/xv/scintilla/commit/4b76c69acfb7537d01027cb4d593b9da1d3c82b0) - `Rename Nimrod to Nim`

I have also updated the SciTE .properties file for the language to the latest name and keywords.

I'll be submitting them to the Scintilla repo at SourceForge in separate .patch files.

**Comment by dom96** [comment]
> I'll be submitting them to the Scintilla repo at SourceForge in separate .patch files.

Thank you for doing this :)

**Comment by xv** [comment]
No problem :)

Already submitted the patches, but I got a reply back from Neil and they need a couple of changes which I am currently working on.

Nim is going to be its own lexer for the sake of backward compatibility, as Neil requested.
See https://sourceforge.net/p/scintilla/feature-requests/1220/

**Comment by Araq** [comment]
Great work. But this is not a Nim issue and it's not clear what it takes to close this.
