### ISSUE TITLE
Manual and implementation mismatch for integer literals

### ISSUE THREAD

**Issue by kubo39** [nim-lang/Nim#8113]
An integer literal `0__0` seems legal in the manual, but lexer treats it as an error.

### Manual:

```
hexdigit = digit | 'A'..'F' | 'a'..'f'
octdigit = '0'..'7'
bindigit = '0'..'1'
HEX_LIT = '0' ('x' | 'X' ) hexdigit ( ['_'] hexdigit )*
DEC_LIT = digit ( ['_'] digit )*
OCT_LIT = '0' ('o' | 'c' | 'C') octdigit ( ['_'] octdigit )*
BIN_LIT = '0' ('b' | 'B' ) bindigit ( ['_'] bindigit )*

INT_LIT = HEX_LIT
        | DEC_LIT
        | OCT_LIT
        | BIN_LIT
```

https://nim-lang.org/docs/manual.html

### Code:

```nim
echo 0__0
```

### Output:

```console
$ nim c zero.nim
Hint: used config file '/home/kubo39/.choosenim/toolchains/nim-0.18.0/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: zero [Processing]
zero.nim(1, 6) Error: invalid token: _
```

**Comment by Vindaar** [comment]
On current devel, the error message has been improved to:
```
Error: only single underscores may occur in a token: '__' is invalid
```
However, the extract from the manual you show seems clear. It's the optional prefix (depending on hex, dec, oct or bin literal, then a single digit of the correct type and then as many `_<digit>` pairs as desired, where the `_` is optional. Note that there is no `*` behind the `['_']`, but only behind the parentheses.

**Comment by kubo39** [comment]
Thank you for the explanation.

I tried this on #head, and found another problem. (I'm sorry, this may not be the scope of this problem...)

### Code:

```nim
echo 0_
```

### Output:

```console
$ nim c zero.nim
Hint: used config file '/home/kubo39/.choosenim/toolchains/nim-#head/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: zero [Processing]
zero.nim(1, 6) Error: only single underscores may occur in a token: '__' is invalid
```

**Comment by Vindaar** [comment]
That's a valid point. The error message should reflect that a literal must not end with an underscore, instead of the one you receive.

An attempt to improve that message: https://github.com/nim-lang/Nim/pull/8114
