### ISSUE TITLE
Problem with using both 'include' and 'import'

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#8124]
When using both 'include' and 'import', the same global variable define in the file is not the same, which generate very strange problem and uneasy to debug.
Here is the example:
t1.nim
```
var
   g1*: seq[int]

proc init_g1*() =
   g1 = @[1,2,3]

proc show_g1*() =
   echo repr g1
   echo g1
```

t2.nim
```nim
include t1

proc show_g1_in_t2*() =
   echo "in t2"
   show_g1()
```

t3.nim
```nim
import t1

proc show_g1_in_t3*() =
   echo "in t3"
   show_g1()
```

t4.nim
```nim
import t2, t3

init_g1()
show_g1_in_t2()
show_g1_in_t3()
```

Run t4.nim, give the following result:
```nim
in t2
0038A028[1, 2, 3]

@[1, 2, 3]
in t3
nil

nil
```

**Comment by demotomohiro** [comment]
include statement in t2.nim just read t1.nim as text file and insert that in t2.nim.
So t2.nim have g1, init_g1 and show_g1 in t2.nim's namespace that are distinct from same name variable/proc in t1.nim imported from t3.nim.
Use 'import' in t2.nim if you want to access same global variable from different module.

How 'import' and 'include' statement work are explained here:
https://nim-lang.org/docs/manual.html#modules

**Comment by andreaferretti** [comment]
Agreed, there is nothing wrong. When you `include` module A into module B, the variable gets declared as part of module B - as everything else in fact

**Comment by slangmgh** [comment]
Yes, I know it seems ok.
But, first, it is almost wrong when the same file is include by one file and at the same time import by another file, and such problem is very difficult to debug, so maybe a warning is fine.

**Comment by narimiran** [comment]
As other commenters already mentioned, I also see nothing wrong here.

`import` and `include` are documented in the manual, and the differences between them are explained there ("The include statement does something fundamentally different than importing a module: it merely includes the contents of a file.").
