### ISSUE TITLE
regex: replacef from re: example from doc fails

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8136]
taking example from doc: https://nim-lang.org/docs/re.html#multiReplace,string,openArray[tuple[Regex,string]]

```nim
import re
let temp="var1=key; var2=key2".replacef(re"(\w+)=(\w+)", "$1<-$2$2")
echo temp
```

nim c -o:app -r tests/t34_re_replacef.nim

/Users/timothee/.choosenim/toolchains/nim-#devel/lib/impure/re.nim(459) replacef
/Users/timothee/.choosenim/toolchains/nim-#devel/lib/system.nim(3788) failedAssertImpl
/Users/timothee/.choosenim/toolchains/nim-#devel/lib/system.nim(3781) raiseAssert
/Users/timothee/.choosenim/toolchains/nim-#devel/lib/system.nim(2843) sysFatal
Error: unhandled exception:
not (result == nil)  [AssertionError]
Error: execution of an external program failed: './app '

 nim --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-05-07 15:34:50
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release

**Comment by narimiran** [comment]
Cannot reproduce with Nim v0.19.0, probably there were several `nil`-fixes in the mean time.

Should be closed.

**Comment by timotheecour** [comment]
indeed, works now, thx for looping in!
