### ISSUE TITLE
[regression?] correct comparisons for nil strings/seqs? 

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#8137]
given this test
```nim
proc test() =
  var a: string
  echo  a == nil
  a = ""
  echo a == nil
  var b: seq[int]
  echo b == nil
  b = @[]
  echo b == nil
  
test() 
```
Nim 0.18.0 produces:
```
true
false
true
false
```
After commit [correct comparisons for nil strings/seqs](https://github.com/nim-lang/Nim/commit/f64f9e50cca38db24f68ee70d979fd55b1c49868) it produces:
```
true
true
true
true
```
Is this really what you mean by `correct comparisons for nil strings/seqs`? 

(issue #8136 is related to this)

**Comment by hlaaftana** [comment]
I think now `nil` seq/string is the same thing as empty seq/string

**Comment by skilchen** [comment]
in the changelog we have this:

- ``nil`` for strings/seqs is finally gone. Instead the default value for
  these is ``"" / @[]``.

I don't understand how this could imply that both `"" == nil` and `@[] == nil` are now `true`, while `isNil("")` and `isNil(@[])` remain `false` as before.

**Comment by Araq** [comment]
I've said it before. New strings/seqs are coming and ``nil`` and ``isNil`` will **fail to compile**. No confusion will be possible.

**Comment by skilchen** [comment]
Excellent! Good luck with this abitious endeavor!

**Comment by krux02** [comment]
can this be closed then?

**Comment by Araq** [comment]
Not as long as ``isNil(str)`` compiles.

**Comment by dom96** [comment]
This will break my book :(

This example at least: https://github.com/nim-lang/Nim/blob/devel/tests/niminaction/Chapter2/resultaccept.nim

**Comment by krux02** [comment]
@dom96 I am sorry for you. But it will be for the greater good. And I think your example will still be understandable and valuable even if nil won't exist anymore in the language.

**Comment by narimiran** [comment]
> can this be closed then?

> Not as long as `isNil(str)` compiles.

`isNil(str)` doesn't compile anymore. This can be closed.
