### ISSUE TITLE
Outdated example to invoke Nim from C

### ISSUE THREAD

**Issue by teroz** [nim-lang/Nim#8139]
The documentation of [Nim invocation example from C](https://nim-lang.org/docs/backends.html#interfacing-backend-code-calling-nim) is completely outdated.

### original issue

Nim compiler generates a statically linked library which does not link.

```gcc -o m -I./nimcache -Ipath/to/nim/lib libfib.a maths.c```
```
/tmp/cce625tz.o: In function `main':
maths.c:(.text+0x9): undefined reference to `NimMain'
maths.c:(.text+0x1c): undefined reference to `fib'
```

**Comment by hlaaftana** [comment]
Did you compile with `--app:staticLib`?

**Comment by teroz** [comment]
Yes I did. I'm using ubuntu 1604 nim 0.18
![screenshot from 2018-06-29 13-50-59](https://user-images.githubusercontent.com/853846/42090893-84eefda8-7ba3-11e8-9cdc-bb8825a73190.png)

**Comment by dom96** [comment]
Might help if you could show us your code (both the .c and .nim)

**Comment by teroz** [comment]
Sure thing. Am using the c and nim file from the [example](https://nim-lang.org/docs/backends.html). So that's the fib.nim and maths.c. 
Works fine when dynamically linked.
fib.nim
```
proc fib(a: cint): cint {.exportc.} =
  if a <= 2:
    result = 1
  else:
    result = fib(a - 1) + fib(a - 2)
```

maths.c
```
#include "fib.h"
#include <stdio.h>

int main(void)
{
  NimMain();
  for (int f = 0; f < 10; f++)
    printf("Fib of %d is %d\n", f, fib(f));
  return 0;
}```

**Comment by krux02** [comment]
The documentation is outdated, the cache is now located in `~/.cache/nim`. On my machine I could compile with this command:

nim c --noMain --noLinking --header:fib.h fib.nim
gcc -o m -I$HOME/.cache/nim/fib_d/ -I$HOME/proj/nim/Nim/lib $HOME/.cache/nim/fib_d/*.c maths.c
