### ISSUE TITLE
`Do not import it!` appears in docs but doesn't give a warning/hint

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8151]
D20180628T152047

https://nim-lang.org/docs/ospaths.html shows:
```
Include file that implements 'osErrorMsg' and friends. Do not import it!Include file that implements 'getEnv' and friends. Do not import it!
```

```nim
import ospaths
echo "ok"
```

- [ ] no warming shown on cmd line though:
nim c -o:app --hints:on --warnings:on -r bugs/t24_ospaths.nim

- [ ] instead of `Do not import it!`, would be more helpful to have: `Do not import it! instead, import os`

**Comment by Araq** [comment]
That warning is outdated, ``ospaths`` is a module of its own nowadays.

**Comment by GULPF** [comment]
This has been fixed - the warning has been removed from the docs.

**Comment by andreaferretti** [comment]
Still on the documentation online

**Comment by GULPF** [comment]
Well the docs will be regenerated for the next release, there's nothing more that can be done for this issue.
