### ISSUE TITLE
[RFC] proposal: isThrown

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8152]
proposal: isThrown to simplify tests.
It works but any help improving it would be welcome!

```nim
template isThrown*(expr: untyped, T: typedesc = typedesc[Exception]) : bool =
    try:
      when compiles(if false: discard expr):
        discard expr
      else:
        expr
      false
    except ref T:
      true
    except:
      false

proc test_isThrown*()=
  doAssert isThrown(raiseAssert("foo"))
  doAssert isThrown(if false: discard).not

  doAssert isThrown(if false: discard, Exception).not
  doAssert isThrown(if true: raise newException(Exception, "foo"), Exception)
  doAssert isThrown(if true: raise newException(IOError, "foo"), Exception)
  doAssert isThrown(if true: raise newException(Exception, "foo"), IOError).not

  doAssert isThrown(if true: raiseAssert("foo"), AssertionError)
  doAssert isThrown(if true: raiseAssert("foo"), Exception)

  proc foo():auto=
    return 1

  doAssert isThrown(foo).not
```

**Comment by hlaaftana** [comment]
https://nim-lang.org/docs/unittest.html#expect.m,varargs[typed],untyped

**Comment by timotheecour** [comment]
thanks, have to admit I didn't know about `expect` ; however isThrown is more flexible and easier to use IMO (could be adapted to handle multiple types, not a single type, if needed)

**Comment by andreaferretti** [comment]
I think this should go into `unittest` anyway, so if you think you approach is more flexible, I suggest to make a PR to include it into `unittest`

**Comment by cooldome** [comment]
expect supports mutiple exception types out of box already. I find expect a better fit for unittest library.

**Comment by timotheecour** [comment]
isThrown is more flexible than `expect` because it allows code to handle result in whatever way (eg, log something custom in case isThrown is false followed by asserting).
No objection against adding support for multiple exceptions though

**Comment by dom96** [comment]
https://nim-lang.org/docs/system.html#doAssertRaises.t,untyped,untyped
