### ISSUE TITLE
[regression] at compile time parseutils.parseInt no longer works on fields of objects/tuples

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#8154]
At compile time:
  `parseutil.parseInt` no longer sets the destination variable, if the variable is a field in an object or tuple.

To reproduce:
```nim
import parseutils

type Obj = object
  i: int
  
proc foo(): Obj =
  discard parseInt("1", result.i, 0)

macro mtest(): untyped =
  echo "compile time: ", foo()
  
proc ptest() =
  echo "run     time: ", foo()
  
mtest()
ptest()
```
when compiled and run with something like `nim c --verbosity:0 -r test.nim` this test used to produce:
```
compile time: (i: 1)
run     time: (i: 1)
```
as expected. But with the latest devel version it produces:
```
compile time: (i: 0)
run     time: (i: 1)
```
which is wrong.

I think, this regression was introduced by commit [Improve vm support for ref types](https://github.com/nim-lang/Nim/commit/236bc06b5f1a1a1fc4a711007aed0b60b6656a4f)

**Comment by kaushalmodi** [comment]
I have to yet try this PR: https://github.com/nim-lang/Nim/pull/8146 that attempts to fix the regressions caused by that commit. If that PR solves this too, then may be this should be added to the tests too.
