### ISSUE TITLE
Support "#." for auto-enumerated lists in RST docs

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8158]
Can this style of auto-enumerated list also be supported in RST docs:

```
#. Item 1
#. Item 2
#. Item 3
```

[Spec][1]:

> In addition, the auto-enumerator, "#", may be used to automatically enumerate a list.

---

I believe this should be simple to implement because the below in RST docs also enables auto-enumeration:

```
1. Item 1
1. Item 2
1. Item 3
```

[1]: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#enumerated-lists

**Comment by Araq** [comment]
Strange, I remember implementing this...

**Comment by kaushalmodi** [comment]
I couldn't understand the code completely in rst.nim, but I looks like that you detect the "#" earlier in the code, but then the '#' case-of doesn't exist later.. The alphas and nums are handled, but the '#' case does to else: discard?
