### ISSUE TITLE
Missing stdlib modules

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#8164]
The following modules are listed in `lib.html` on devel but can't actually be imported (not even on 0.18.0):
```nim
# All of these fails
import rstast
import rstgen
import rst
import highlight
import sexp
import fsmonitor
```

**Comment by Araq** [comment]
Well the import is ``packages/docutils/rstast`` but it's not a simple fix, the docgen needs to understand subdirectories...

**Comment by GULPF** [comment]
Why the weird import path? Now that we have the `std` namespace they should be moved to `std` or `std / docutils`.

**Comment by Araq** [comment]
This shouldn't block the release any further.
