### ISSUE TITLE
missing `ospaths.absolutePath` function to get absolute path from a path

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8174]
We're missing `ospaths.absolutePath` function to get absolute path from a path

* This would be the same as https://dlang.org/phobos/std_path.html#absolutePath
* this should be in `ospaths`
* `expandFilename` in `os` is not what I'm looking for (that function checks whether the return path exists, which is not good, eg when the file doesn't exist yet, etc)
* furthermore, the name `expandFilename` is not good, since it's hard to search (should contain `absolute` instead, as in most languages), and isn't just for files but also dirs
* this function should allow a root (defaults to cwd)
* when `rel` is absolute, it would return rel regardless of base

proposed interface:

```nim
proc absolutePath(rel: string, base: string = nil): string
```

implementation: see https://forum.nim-lang.org/t/4004 ; I'm having a difficulty in using getCurrentDir in ospaths

**Comment by mashingan** [comment]
See the snippet [here](https://forum.nim-lang.org/t/4004#24923) and try whether it works for your OS

**Comment by timotheecour** [comment]
@mashingan no it did not, stiil causes link errors in case user doesn't explicitly calls `getCurrentDir` in his code (i'm on OSX)

**Comment by timotheecour** [comment]
PR: https://github.com/nim-lang/Nim/pull/8213

**Comment by FedericoCeratto** [comment]
#6587 was already addressing this

**Comment by timotheecour** [comment]
@FedericoCeratto  see https://github.com/nim-lang/Nim/pull/6587#issuecomment-402832478

**Comment by FedericoCeratto** [comment]
absolutePath("a", "b/") == "b" / "a" is quite counter-intuitive.
Also joinPath("b", "a") does that already.

**Comment by timotheecour** [comment]
> absolutePath("a", "b/") == "b" / "a" is quite counter-intuitive.

same as https://dlang.org/phobos/std_path.html#absolutePath

> Also joinPath("b", "a") does that already.

doesn't handle edge cases, see #8213

**Comment by andreaferretti** [comment]
@timotheecour Maybe not everything should be "same as D", otherwise we would be using D in the first place! ;-)
