### ISSUE TITLE
Nim logo art work url?

### ISSUE THREAD

**Issue by markprocess** [nim-lang/Nim#8183]
What is a good replacement for:

https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-withBackground.png

Ref https://github.com/moigagoo/nimage/issues/16

Thanks, Mark

**Comment by hlaaftana** [comment]
https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-crown.png
https://nim-lang.org/assets/img/logo.svg

**Comment by markprocess** [comment]
Thanks. Ref https://github.com/moigagoo/nimage/pull/17
