### ISSUE TITLE
cannot build Nim versions between v0.9.4 and v0.13.0 (to search when regression occurred)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8191]
Was trying to find when regression https://github.com/nim-lang/Nim/issues/8188 occurred unfortunately I cannot build Nim versions between v0.9.4 and v0.13.0

* choosenim can't build nim before 0.16.0 (see my bug report https://github.com/dom96/choosenim/issues/66)

* I wrote the following bash script to build versions of nim prior to that but it fails when https://github.com/nim-lang/csources.git doesn't have a git tag corresponding to the nim version I'm trying to build:

# this successfully compiles v0.9.4:
d_build_nim_version Nim_9_4 v0.9.4 v0.9.4 nimrod nimrod

# this successfully compiles v0.13.0:
d_build_nim_version Nim_13_0 v0.13.0 v0.13.0 nim nim

# this doesn't work and I'm not sure how to fix that since https://github.com/nim-lang/csources.git doesn't have a corresponding git tag
d_build_nim_version Nim_12_0 v0.12.0 v0.9.4 nim nimrod

```nim
d_build_nim_version(){
  echo "$@"
  dir="$1"
  version_nim="$2"
  version_csources="$3"
  #TODO: IMPROVE by auto inferring name, name_csources (eg: >= v0.13.0: nim ; <= v0.9.4: nimrod)
  name="$4"
  name_csources="$5"
  git clone -b $version_nim --single-branch --depth 1 https://github.com/nim-lang/Nim $dir && cd $dir
  git clone -b $version_csources --single-branch --depth 1 https://github.com/nim-lang/csources.git
  echo running build.sh
  (cd csources && sh build.sh && cd ..)
  ./bin/$name_csources --version

  # BUG: this fails when  version_csources != version_nim
  ./bin/$name_csources c koch
  ./koch boot -d:release
  ./compiler/$name --version

  # optional: this didn't exist till some point later
  # ./koch tools
}
```

The error:
```
./bin/nimrod c koch
Hint: system [Processing]
lib/system.nim(143, 40) Warning: unknown magic 'Addr' might crash the compiler [UnknownMagic]
lib/system.nim(154, 44) Warning: unknown magic 'Addr' might crash the compiler [UnknownMagic]
lib/system.nim(161, 39) Warning: unknown magic 'TypeOf' might crash the compiler [UnknownMagic]
lib/system.nim(265, 62) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(273, 59) Warning: unknown magic 'DotDot' might crash the compiler [UnknownMagic]
lib/system.nim(288, 16) Error: ']' expected

```

**Comment by genotrance** [comment]
Looks like you already tried the reverse of what I was [thinking](https://github.com/dom96/choosenim/issues/66#issuecomment-402025097). 

Does my idea work - building 0.12.0 with 0.13.0 csources?

I'm also curious why all those csources were never checked in. How was Nim compiled in the past?

cc @araq, @dom96

**Comment by Araq** [comment]
> I'm also curious why all those csources were never checked in. How was Nim compiled in the past?

With csources, but the tagging is missing, I think.

**Comment by timotheecour** [comment]
@Araq so you're saying we should be able to use `git checkout $hash` instead of `git checkout $tag` when the tag is missing, for an appropriate $hash that is guaranteed to exist in the git log?

**Comment by Araq** [comment]
Yes, but there is also:

https://nim-lang.org/download/nim-0.10.2.tar.gz
https://nim-lang.org/download/nim-0.11.0.tar.xz
https://nim-lang.org/download/nim-0.11.2.tar.xz
https://nim-lang.org/download/nim-0.12.0.tar.xz
https://nim-lang.org/download/nim-0.13.0.tar.xz

All containing the C sources that were used to build these releases, afaict.

**Comment by dom96** [comment]
The C sources used to be in the Nim repo, they were removed from the history because they took up a hell of a lot of space. You can download the source tarballs from the Nim website though:

```
dom@p:~$ ls /var/www/nim-lang.org/download/ | grep nim
nim-0.10.2-old.zip
nim-0.10.2_x32.exe
nim-0.10.2_x64.exe
nim-0.10.2.zip
nim-0.11.0.tar.gz
nim-0.11.0.tar.xz
nim_0.11.0_x32.exe
nim-0.11.0_x32.exe
nim_0.11.0_x64.exe
nim-0.11.0_x64.exe
nim-0.11.0.zip
nim-0.11.2.tar.xz
nim-0.11.2_x32.exe
nim-0.11.2_x64.exe
nim-0.11.2.zip
nim-0.12.0.tar.xz
nim-0.12.0_x32.exe
nim-0.12.0_x64.exe
nim-0.12.0.zip
nim-0.13.0.tar.xz
nim-0.13.0_x32.exe
nim-0.13.0_x64.exe
nim-0.13.1.tar.xz
nim-0.14.0.tar.xz
nim-0.14.0_x32.exe
nim-0.14.0_x64.exe
nim-0.14.2_old.tar.xz
nim-0.14.2.tar.xz
nim-0.14.2_x32.exe
nim-0.14.2_x64.exe
nim-0.15.0.tar.xz
nim-0.15.0_x32.exe
nim-0.15.0_x64.exe
nim-0.15.2.tar.xz
nim-0.15.2_x32.exe
nim-0.15.2_x32.zip
nim-0.15.2_x64.exe
nim-0.15.2_x64.zip
nim-0.16.0.tar.gz
nim-0.16.0.tar.xz
nim-0.16.0.tar.xz.sha256
nim-0.16.0_x32.exe
nim-0.16.0_x32.zip
nim-0.16.0_x32.zip.sha256
nim-0.16.0_x64.exe
nim-0.16.0_x64.zip
nim-0.16.0_x64.zip.sha256
nim-0.16.1_x32.zip
nim-0.16.1_x64.zip
nim-0.17.0.tar.gz
nim-0.17.0.tar.gz.sha256
nim-0.17.0.tar.xz
nim-0.17.0.tar.xz.sha256
nim-0.17.0_x32.zip
nim-0.17.0_x32.zip.sha256
nim-0.17.0_x64.zip
nim-0.17.0_x64.zip.sha256
nim-0.17.2.tar.gz
nim-0.17.2.tar.gz.sha256
nim-0.17.2.tar.xz
nim-0.17.2.tar.xz.sha256
nim-0.17.2_x32.zip
nim-0.17.2_x32.zip.sha256
nim-0.17.2_x64.zip
nim-0.17.2_x64.zip.sha256
nim-0.18.0.tar.gz
nim-0.18.0.tar.gz.sha256
nim-0.18.0.tar.xz
nim-0.18.0.tar.xz.sha256
nim-0.18.0_x32.zip
nim-0.18.0_x32.zip.sha256
nim-0.18.0_x64.zip
nim-0.18.0_x64.zip.sha256
nimbuild.zip
nimrod_0.8.14.exe
nimrod_0.8.14.zip
nimrod_0.9.0.exe
nimrod_0.9.0.zip
nimrod_0.9.2.exe
nimrod_0.9.2.zip
nimrod_0.9.4_linux_amd64.tar.gz
nimrod_0.9.4_linux_i386.tar.gz
nimrod_0.9.4_linux_ppc64.tar.gz
nimrod_0.9.4_macosx_amd64.zip
nimrod_0.9.4_windows_amd64_full.exe
nimrod_0.9.4_windows_amd64_full.zip
nimrod_0.9.4_windows_amd64_slim.exe
nimrod_0.9.4_windows_amd64_slim.zip
nimrod_0.9.4_windows_i386_full.exe
nimrod_0.9.4_windows_i386_full.zip
nimrod_0.9.4_windows_i386_slim.exe
nimrod_0.9.4_windows_i386_slim.zip
nimrod_0.9.6.exe
nimrod_0.9.6_x64.exe
nimrod_0.9.6.zip
nimrod_gamera_0.9.2.exe
```

**Comment by timotheecour** [comment]
@Araq https://nim-lang.org/download/nim-0.10.2.tar.gz gives 404 Not Found (the others work but not sure yet where would regression be)
@dom96 
> You can download the source tarballs from the Nim website though

how ? I dont' have access to server and wget/curl doesn't work on https://nim-lang.org/download

**Comment by dom96** [comment]
> how ? I dont' have access to server and wget/curl doesn't work on https://nim-lang.org/download

... you grab the filename in my paste and append it to https://nim-lang.org/download/. For example: https://nim-lang.org/download/nimrod_0.9.0.zip

**Comment by Araq** [comment]
There is little else we can do.
