### ISSUE TITLE
SIGSEGV instead of compiler error when type variable is defined in when:false block

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8194]
nim c -o:app -r bugs/t28_SIGSEGV.nim
BUG: this creates a SIGSEGV which in more complex cases can be hard to debug since we don't have source info:
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

if we comment out
```
when false:
   type ret = int
```

then we get the compiler error we expect:
Error: undeclared identifier: 'ret'

```nim
template foo*(): untyped =
  when false:
    type ret = int
  ret

when isMainModule:
   var a: foo()
```

**EDIT**
after compiling with stacktrace through: `./koch temp` :
$git_clone_D/nim/Nim/bin/nim_temp c -o:app -r bugs/t28_SIGSEGV.nim

Traceback (most recent call last)
nim.nim(133)             nim
nim.nim(97)              handleCmdLine
main.nim(162)            mainCommand
main.nim(73)             commandCompileToC
modules.nim(124)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(103)          processTopLevelStmt
sem.nim(592)             myProcess
sem.nim(560)             semStmtAndGenerateGenerics
semstmts.nim(1893)       semStmt
semexprs.nim(910)        semExprNoType
semexprs.nim(2445)       semExpr
semexprs.nim(2051)       semWhen
semexprs.nim(2521)       semExpr
semstmts.nim(1834)       semStmtList
semexprs.nim(2523)       semExpr
semstmts.nim(478)        semVarOrLet
semtypes.nim(1484)       semTypeNode
semtypes.nim(1272)       semTypeExpr
semexprs.nim(59)         semExprWithType
semexprs.nim(2414)       semExpr
semexprs.nim(894)        semDirectOp
semexprs.nim(790)        afterCallActions
semexprs.nim(31)         semTemplateExpr
sem.nim(409)             semAfterMacroCall
semexprs.nim(2521)       semExpr
semstmts.nim(1834)       semStmtList
semexprs.nim(2342)       semExpr
semexprs.nim(1116)       semSym
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by narimiran** [comment]
Not reproduced on Nim devel v0.20.99.
