### ISSUE TITLE
Program Crash/Synchronization Mishandling?

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#8201]
I am not 100% sure if this program is correct usage, but I believe it is.  The actual program I started with was more complex, didn't use random junk data/procs, and had good reasons for wanting to just keep 'p' worker procs live over a possibly enormous input list.  This seemed a small and maybe portable reproduction of the core issue.

```Nim
import cpuinfo, threadpool, random

proc workStr(str: string): string = $str[^1]   # meaningless string->string busywork

proc randWork*(seed, N: int) =
  let p = countProcessors() + 2     #I get ~16% failure rate with this p
  var fts: seq[FlowVarBase] = @[ ]
  var r = initRand(seed)
  for i in 0..<N:
    let str = $r.rand(1000000000)   # Just random strings to pass to workStr
    if fts.len < p:
      fts.add(spawn(workStr(str)))
    else:
      let j = blockUntilAny(fts)          # We never collect ^fts[j] for this bug report
      fts[j] = spawn(workStr(str))   # It happens with or without such collection.
  var n = min(p, fts.len)         #XXX awaitAny never returns -1 for me.  That is..
  while n > 0:                    #XXX ..a smaller fish to fry.  So, just count.
    let j = blockUntilAny(fts)
    dec(n)

randWork(12345, 30000)
```
With devel Nim (and perhaps many others?), this program (compiled with --threads:on, of course), for me about 16% of the time I get a SEGV at ``fv.ai.idx`` in ``nimFlowVarSignal`` with ``fv.ai == nil`` (in spite of the ``if``-guard to prevent that).  Even more rarely, control flow gets further to:
  ``nimFlowVarSignal.signal(fv.ai.cv.c)`` ->sig..-> ``__pthread_cond_signal(cond=0x0)``

The crash happens early on in the 30,000 loops.  It is nowhere near the end which is not the canonical ``awaitAny != -1`` loop.  I leave my weird version there in case it gives any insight.  You can delete that while loop and still get crashes.

The generated C looks fine for the 'if' guard.  So, some other thread (probably the main thread..``awaitAny`` seems a likely culprit) seems to sometimes zero the pointer between the if-guard comparison and the immediately subsequent access.  The only intervening logic in ``nimFlowVarSignal`` is the ``acquire(fv.ai.cv.L)`` which I have never seen crash, but which presumably also could.

I saw the ``compiler.lowerings.createWrapperProc`` comment just before ``nimFlowVarSignal`` call generation says using thread-local view of ``fv``, but I did not track down where such views come from/how they operate.  If there's nothing wrong with my usage, this seems like a pretty critical race condition.

It may be sensitive to the Linux scheduler (I am on 4.17.2) and hard to reproduce on Windows.  Or it may be _more_ sensitive to the Windows scheduler.  Also, to reproduce, you may want a shell script or batch file to run the program like 100 times in a couple nested loops or something.  Maybe fiddle with ``p`` and the ``N`` arg to ``randWork`` until you can get high % failure rates from the script.  Then run & re-run in a debugger to trap the error with more context if you need it.

**Comment by c-blake** [comment]
Following up on this, I reproduced the runtime memory error on 3 different Intel CPUs spanning 7 years of CPU generations, 2 versions of ``gcc``, and 1 version of ``clang``, all on two versions of Linux, in release mode and non-release mode.  I get the crash every time (sometimes 90% of the program runs..sometimes 10%).  I could try some really old versions of Nim, too, if you need me to.  I kinda suspect this has always been a problem, but requires fast & furious thread activity to manifest.  Let me know if you have trouble reproducing this.

Digging into it a little bit more, I see that the return value of ``cas`` is ``discard``ed in the second ``for`` loop in ``awaitAny``.  It doesn't seem like it would ever makes sense for ``cas`` to be only "best effort" like that..If the assumption is that no other ``flowVars[i].ai`` can have the same ``addr ai`` as the current thread's local var due to thread-local heaps, then why use not just check for ``addr ai`` without ``cas`` at all?

**Comment by Araq** [comment]
On OSX's scheduler it fails very often.

**Comment by Araq** [comment]
The major culprit here seems to be that ``fts[j] = spawn(workStr(str))`` line without ever reading from the flow variable, but ``blockUntilAny`` seems fundementally flawed in its interface too. :-/

**Comment by c-blake** [comment]
Well, as mentioned in my ``collect ^fts[j]`` side-comment in the code, it happens for me with our without reading the ``flowVar``, but all code changes, compiler changes, OS scheduler changes, parallelism changes vary the frequency of failure.

Adding some code to read it does makes the exception more rare for me, but it still happens.  I'll include an updated program anyway for easy cut & paste.  This still reliably fails for me a few per cent of the time.  Maybe on OSX with certain background activity it fails more reliably.  I changed the ``workStr`` to just return the ``len`` of the ``string`` to have something to sum to use the output.

There is a much more minor issue of ``blockUntilAny`` not returning -1.  It seems like this is the intended interface, but I am happy to be corrected.  That is probably unrelated? but definitely more easily worked around.

```Nim
import cpuinfo, threadpool, random

proc workStr(str: string): int = str.len

proc randWork*(seed, N: int) =
  let p = countProcessors() + 4
  var fvs: seq[FlowVarBase] = @[ ]
  var r = initRand(seed)
  var sum = 0
  for i in 0..<N:
    let str = $r.rand(1000000000)
    if fvs.len < p:                 #Fill the p slots with work
      fvs.add(spawn(workStr(str)))
    else:
      let j = blockUntilAny(fvs)    #Wait for free slot to launch new work
      sum += ^cast[FlowVar[int]](fvs[j])
      fvs[j] = spawn(workStr(str))

  when defined(blockUntilAnyFinalWorks):
    var j = blockUntilAny(fvs)      #Collect final p jobs
    sum += ^cast[FlowVar[int]](fvs[j])
    while j >= 0:
      j = blockUntilAny(fvs)
      sum += ^cast[FlowVar[int]](fvs[j])
  else:
    var n = min(p, fvs.len)         #blockUntilAny never returns -1.  So count.
    while n > 0:
      let j = blockUntilAny(fvs)
      sum += ^cast[FlowVar[int]](fvs[j])
      dec(n)
  echo "sum: ", sum

randWork(54321, 50000)
```

**Comment by c-blake** [comment]
Anyway, since you did reproduce it and since we don't seem to have an immediate solution, you may want to mark this issue as a bug or something so somebody else might notice.

**Comment by Araq** [comment]
> There is a much more minor issue of blockUntilAny not returning -1. It seems like this is the intended interface, but I am happy to be corrected. That is probably unrelated? but definitely more easily worked around.

It never returns -1 since there is no contention for the blockUntilAny. -1 is only returns when all the other flow variables already participate in a different call to blockUntilAny. Yes, I know it's weird.

**Comment by c-blake** [comment]
Ok.  Yeah.  Weird.  I deleted the extraneous code from the example to clean it up.

**Comment by Araq** [comment]
Threadpool is deprecated.
