### ISSUE TITLE
Is bootstrapping still required

### ISSUE THREAD

**Issue by svnpenn** [nim-lang/Nim#8207]
From the readme:

> First, the C source of an older version of the Nim compiler is needed to
> bootstrap the latest version because the Nim compiler itself is written in the
> Nim programming language. Those C sources are available within the
> `nim-lang/csources` repository.

http://github.com/nim-lang/Nim#compiling

I checked the history and this paragraph was essentially added 5 years ago with
a16e6bd - so is this still the case? cant Nim just being installed from here:

http://nim-lang.org/install.html

then be used to build from `devel`? it seems odd that C bootstrapping would
still be needed 5 years later.

**Comment by Araq** [comment]
Well we try our best to keep the csources step optional but it allows us to break compatibility and clean up deprecated cruft. So, it will be this way for the foreseeable future.
