### ISSUE TITLE
times.format: should allow writing arbitrary strings inside format string, like python strftime("D%Y%m%dT%H%M%S")

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8214]
in python we can write arbitrary strings within the format string, and the special characters are distinguished by "%", eg:
`python -c 'from datetime import *; print(datetime.now().strftime("D%Y%m%dT%H%M%S"))'`

in nim, I dont' see how to do that, only valid characters are the special ones (and there is no % to distinguish them) PLUS space eg:
```nim
echo "My formatted time: ", format(now(), "yyyyMMdd HHmmss")
```

I'd like to have a version as flexible as python, eg:

```nim
echo "My formatted time: ", format2(now(), "D{yyyy}{MM}{dd}T{HH}{mm}{ss}")
```
it'd work in much same way as fmt"foo{bar}", and `{` would be escaped via `{{`

**Comment by skilchen** [comment]
Quote from https://nim-lang.org/docs/times.html:
> Other strings can be inserted by putting them in ''. For example hh'->'mm will give 01->56. The following characters can be inserted without quoting them: : - ( ) / [ ] ,. However you don't need to necessarily separate format specifiers, a unambiguous format string like  yyyyMMddhhmmss is valid too.

Please note that @GULPF the excellent current main contributor to times.nim has a PR open [New implementations of times.parse & times.format](https://github.com/nim-lang/Nim/pull/8094). The above part of the documentation in the proposed new version:

> Other strings can be inserted by putting them in ''. For example hh'->'mm will give 01->56. The following characters can be inserted without quoting them: : - ( ) / [ ] ,. A literal ' can be specified with ''.
>
> However you don't need to necessarily separate layout patterns, a unambiguous layout string like yyyyMMddhhmmss is valid too (although only for years in the range 1..9999).

**Comment by timotheecour** [comment]
thanks! closing
