### ISSUE TITLE
bad example in https://nim-lang.org/docs/docgen.html

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8215]
- [ ] in https://nim-lang.org/docs/docgen.html it says:
> The full output can be seen here: docgen_sample2.html. As you can see, the tool has extracted additional information provided to it by the compiler beyond what the doc command provides, such as pragmas attached implicitly by the compiler. 

as of right now, https://nim-lang.org/docs/docgen_sample.html and https://nim-lang.org/docs/docgen_sample2.html look identical (there are no pragmas etc)

maybe a better sample.nim could be given to illustrate the difference

- [ ] also, `nim doc2` is not documented in `nim --helpfull`

**Comment by andreaferretti** [comment]
I think doc2 and doc were merged together, so now doc2 is left jsut for backwards compatibility

**Comment by PMunch** [comment]
Yeah `doc2` got renamed to `doc`, and `doc` got renamed to `doc0`. The idea is to deprecate the old `doc`. So that comparison should simply be removed, as there are no longer two commands.

**Comment by timotheecour** [comment]
=> see PR https://github.com/nim-lang/Nim/pull/8418

**Comment by timotheecour** [comment]
@PMunch @andreaferretti I'm seeing a single line with old docs here:
srcdoc: "system/threads.nim;system/channels.nim;js/dom" (which uses old doc0)
all the rest is using srcdoc2 (which uses doc2)
not sure why this exception
