### ISSUE TITLE
nim command line should be nested instead of flat (cf git command line)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8216]
example to illustrate:
--project and --docSeeSrcUrl:url are only relevant for nim doc, it would make more sense to nest them under "doc".

There are several ways to do that:

* git way (eg: git diff --no-index file1 file2) => `git --no-index` disallowed

* this nim project https://github.com/c-blake/cligen which allows generating cmd line from top-level functions, dispatching the appropriate subflags to subcommands to avoid mixing them in 1 soup

* quick fix, simplest to implement: prefixing flags with relevant top-level name, eg: 

```
--project
--docSeeSrcUrl:url
=>
--doc.project
--doc.seeSrcUrl:url
```

Other example:
```
--skipCfg
--skipUserCfg
--skipParentCfg
--skipProjCfg
=>
--cfg.skip
--cfg.skipUser
--cfg.skipParent
--cfg.skipProj
```

```
--objChecks:on
--infChecks:on
--fieldChecks:on
...
=>
--checks.obj:on
--checks.inf:on
--checks.field:on
```

```
--hint[source]=on
=>
--hint.source=on # avoids having to escape `--hint[source]` for use in bash, etc
```

etc.
Note: we could have multi-level too if needed, eg:
```
--lang.js.enableFeatureX
```

Any of these would be more scalable than what we have, and make it easier to grok and extend nim's command line.

**EDIT**: looks like configVar is related to this, see:
`if strutils.find(switch, '.') >= 0: options.setConfigVar(conf, switch, arg)`
in compiler/commands.nim ; except this doesn't check whether argument exists, eg: `nim c --foo.bar.baz test.nim` doesn't error

- [ ] —listCmdshould be a hint

**Comment by timotheecour** [comment]
as shown in https://github.com/nim-lang/Nim/pull/8757, the proper way to handle nesting is to use
`--doc:seeSrcUrl:url` instead of `--doc.seeSrcUrl:url` because the latter would lead to ambiguities (silently accepting wrong code) because of the catch-all clause `setConfigVar` (for better or for worse)

**Comment by krux02** [comment]
Well the compiler command line interface isn't the best, and that is also a known issue. But this discussion is in my opinion too much opinion based and therefore I am closing this.

If you create an alternative argument parser with the the following attributes:

 * easy to maintain (clean simple code)
 * better structuring of arguments
 * better documentation management (e.g. a macro that fetches doccomments from to display them in the help text)
 * compatibility layer for the old interface

Then I am willing to merge the PR. But currently I don't think it is worth arguing about the details on how those arguments should be named.
