### ISSUE TITLE
doAssertRaises should accept Exception as well as no argument

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8222]
```
doAssertRaises(Exception):
  assert false
```

system.nim(4206, 10) Error: exception already handled
    except Exception as exc:

=> should be allowed

```
doAssertRaises:
  assert false
```

Error: type mismatch: got <void>
but expected one of:
template doAssertRaises(exception, code: untyped): typed

=> should accept Exception as default argument

**Comment by Araq** [comment]
It's never wrong to be explicit about what should be raised. -1 from me.

**Comment by dom96** [comment]
> It's never wrong to be explicit about what should be raised. -1 from me.

Same

```nim
doAssertRaises(Exception):
  assert false
```

This needs to be fixed though.

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/issues/8222#issuecomment-403953791

i fixed it here https://github.com/nim-lang/Nim/pull/10172
