### ISSUE TITLE
Nim crashes upon compilation with a nimcache flag inside nim.cfg

### ISSUE THREAD

**Issue by stefanos82** [nim-lang/Nim#8236]
I have created `nim.cfg` under my `src`.

In it I have added the following lines:
```txt
o:"bin/foo"
nimcache=getCurrentDir()
```
As soon as I run it, it crashes and throws the following message:
```txt
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
I have looked for standard Nim environment variables, but all I could find was `$project_path`.

My project format is the following:
```txt
Project
    src
        nim.cfg
        foo.nim
    bin
        foo
```
I want nimcache folder to be right under `Project` directory.

**Comment by genotrance** [comment]
Correct syntax is:

```nim
--nimcache:"../nimcache"
-o:"bin/foo"
```

**Comment by stefanos82** [comment]
@genotrance hyphens are optional.

Also, `--nimcache:nimcache` will do just fine, but that was not the question.

**Comment by genotrance** [comment]
Then better to take my comment as "working syntax" cause I tried that and it worked.

**Comment by ringabout** [comment]
the issue has been fixed

now it gives
```
D:\QQPCmgr\Desktop\Nim\test.nim.cfg(2, 24) Error: expected identifier, but got: (
```
