### ISSUE TITLE
[regression] dynamic dispatch on multiple arguments crashes compiler

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#8246]
This program can't be compiled with the latest devel version of Nim:
```nim
type
  Foo = object of RootObj
  Bar = object of Foo
    x: int

method mm(a: Foo, b: Foo) {.base.} =
  echo "mm: Foo, Foo"    

method mm(a: Bar, b: Bar)  =
  echo "mm: Bar, Bar"
  
method mm(a: Foo, b: Bar)  =
  echo "mm: Foo, Bar"
  
method mm(a: Bar, b: Foo)  =
  echo "mm: Bar, Foo"

proc test() =
  var foo: Foo
  var bar: Bar

  mm(foo, foo)
  mm(foo, bar)
  mm(bar, foo)
  mm(bar, bar)

test()
```
This issue is related to the fact that currently the CI tests fail. 

The very surprising and slightly disturbing fact is: this issue is caused by the line `{.deprecated: [SomeReal: SomeFloat].}` in [system.nim](https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L109). 

Without this deprecation, the test-program compiles and runs correctly and so do the currently failing tests `method\tmultim2` and `method\tmultim6`

**Comment by timotheecour** [comment]
@LemonBoy  indeed, I was seeing unrelated failures :

https://travis-ci.org/nim-lang/Nim/jobs/401284582
https://github.com/nim-lang/Nim/pull/8213

```
FAIL: tmultim2.nim C
Test "tests/method/tmultim2.nim" in category "method"
Failure: reNimcCrash
Expected:
Gotten:
internal error: genMagicExpr: mTypeTrait


FAIL: tmultim6.nim C
Test "tests/method/tmultim6.nim" in category "method"
Failure: reNimcCrash
Expected:
Gotten:
internal error: genMagicExpr: mTypeTrait
```
hopefully the PR fixed it, but, curious how this regression was even possible; wouldn't have that failing test prevented the PR that introduced the bug from being green? or was it a flaky failure?

**Comment by LemonBoy** [comment]
> curious how this regression was even possible

Luck. Every time the `system.nim` was modified the compiler would pick one of the three `and` overloads (`mAnd`, `mBitandI`, `mTypeTrait`) but it was lucky enough to pick one of the first two that work fine with bools.
