### ISSUE TITLE
Deprecated code detected in strutils

### ISSUE THREAD

**Issue by stefanos82** [nim-lang/Nim#8252]
@Araq and @dom96,

I think the title says it all.

Since a string cannot be nil, we need to either deprecate this piece of code or remove it entirely.

[strutils.nim#L467](https://github.com/nim-lang/Nim/blob/master/lib/pure/strutils.nim#L467)

**Comment by narimiran** [comment]
*[I guess the original link pointed at something else than it does now]*

I've checked the file for `nil`s and it seems this can now be closed?

**Comment by stefanos82** [comment]
Seems like it.

I have checked the file myself and have changed by orders of magnitude since I first reported it.

Closing it.

Special thanks to both of you @Yardanico and @narimiran for your valuable feedback.
