### ISSUE TITLE
[ospaths] BUG: splitFile("/a.txt").dir = "" ; + other bugs with splitFile

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8255]
- [ ] bug 1:
nim:
echo splitFile("/a.txt")
(dir: "", name: "a", ext: ".txt") #definitely wrong

python:
os.path.split("/a.txt")
('/', 'a.txt')

- [ ] bug 2:
nim:
echo splitFile("a/")
(dir: "a/", name: "", ext: "") # violates good sense, and also documention: "dir does not end in DirSep. extension includes the leading dot."

python:
os.path.split("a/")
('a', '')

- [ ] bug 6
echo splitFile("a/..")
(dir: "a", name: ".", ext: ".")
should be:
(dir: "a", name: "..")

**Comment by Araq** [comment]
Bug 1 is documented behaviour and encoded in the return type!

**Comment by andreaferretti** [comment]
I think bug 1 is about dir, which should be `/`

**Comment by timotheecour** [comment]
> I think bug 1 is about dir, which should be /

yes, that is the bug I'm referring to

**Comment by timotheecour** [comment]
=> PR to fix it: https://github.com/nim-lang/Nim/pull/10047
