### ISSUE TITLE
[RFC] skip CI runs (travis/AppVeyor) when AST doesn't change

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8265]
travis/AppVeyor can take a while to run, could this optimization be done:

~~* upon a git push, check if previous state before that push was green; if it was, and if commit doesn't change AST (eg only comments or spacing that doesn't change AST), then skip running travis/AppVeyor~~

**EDIT:**
* upon a git push, f commit doesn't change AST (eg only comments or spacing that doesn't change AST), then skip running travis/AppVeyor ; the state shown is same as before that git push (whether failing or passing)

* as an escape solution, closing / reopening PR would still trigger travis/AppVeyor

This would make improving docs an easier process

**EDIT** as mentioned below, see Related PR #6999

**Comment by dom96** [comment]
Sure, we can add lots of rules like this. We need to make sure these rules can detect the desired circumstances reliably though.

**Comment by timotheecour** [comment]
(edited above)

**Comment by Araq** [comment]
The last thing we need is "clever" testing. Even whitespace changes can break the documentation generation, for example.

**Comment by timotheecour** [comment]
> Even whitespace changes can break the documentation generation, for example.

for these, we could run only documentation generation, not the whole test suite

**Comment by data-man** [comment]
Related PR #6999

**Comment by narimiran** [comment]
Since @Araq didn't like neither #6999 nor this revival, I'm closing this as a rejected proposal.
