### ISSUE TITLE
[regression] [times.format] Error: attempting to call undeclared routine: 'format'

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8273]
@GULPF this regression could be caused by https://github.com/nim-lang/Nim/pull/8094

```nim
when true:
  from times import nil # BUG
when false:
  import times # ok but may not be desirable when there are symbol conflicts

echo times.format(times.now(), "yyyy")

/Users/timothee/git_clone/nim/timn/bugs/t41_times_format.nim(6, 18) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/pure/times.nim(2105, 13) Error: attempting to call undeclared routine: 'format'
    result = f.format(dt)

```

works:
nim --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-07-02
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release

fails:
$nimc_D/bin/nim_devel --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-07-10
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 25bf0d1683ce7203c004a5b14d92dcbe6ff40331
active boot switches:

**Comment by skilchen** [comment]
I think, this is one more of the problems with `static`...
```nim
from times import nil
var f = "yyyy"
echo times.format(times.now(), f)
```
works. But I have no idea, what a good solution to this regression would look like.

**Comment by dom96** [comment]
I'm really confused why this worked before #8094.

**Comment by timotheecour** [comment]
@dom96 could you explain what you mean?

before PR, eg for current git master (instead of devel) at 2a8d2ad4cde1c942a9dbc44598f65d4acf1e0aa6
proc format*(dt: DateTime, f: string): string 

after PR:
proc format*(dt: DateTime, f: string): string
proc format*(dt: DateTime, format: static[string]): string

why wouldn't it work before PR?

what I'm confused by is why wouldn't it work after PR.

**Comment by timotheecour** [comment]
@dom96 @skilchen @GULPF
eureka! turns out your guess was a red herring:

> I think, this is one more of the problems with static...


the problem here is that `format` is used as both arg and fn name:

```nim
 proc format*(dt: DateTime, format: static[string]): string {.raises: [].} =
  ## Overload that validates ``format`` at compile time.
  const f = initTimeFormat(format)
  result = f.format(dt)
```

it works if we have either of these instead:

```nim
proc format*(dt: DateTime, f: static[string]): string {.raises: [].} =
  ## Overload that validates ``format`` at compile time.
  const f2 = initTimeFormat(f)
  result = f2.format(dt)

proc format*(dt: DateTime, format: static[string]): string {.raises: [].} =
  ## Overload that validates ``format`` at compile time.
  const f = initTimeFormat(format)
  result = times.format(f, dt)
```

My preference is for `proc format*(dt: DateTime, f: static[string]): string {.raises: [].} =` which is more symmetrical with the other overload:
`proc format*(dt: DateTime, f: string): string =`

On that note, should we make it an error to have an argument that has same name as proc/template name ? It's just begging for bugs like this one.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/8290

**Comment by dom96** [comment]
> why wouldn't it work before PR?

Oh, never mind. I thought you were using ``strfmt`` for some reason, that's why I was confused.
