### ISSUE TITLE
`koch web`: parallelization does not work (see current travis failures)

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#8274]
The command `koch web` tries to build the documentation in parallel using all available processors. But this always fails, and then the work is repeated serially. The parallel build of the documentation always fails, because today building the documentation involves running the `runnableExamples`. But this does not work in parallel, because the multiple running compilers will eventually clobber each others nimcache.
We therefore regularly see  messages like `undefined reference to <whatever>` eg. in the build logs of travis, but also if we run `koch web` locally and redirect the output to a file. We also see the misterious message `external program failed, retrying serial work queue for logs!` in the output of `koch web` which marks the switch from parallel to serial work.
Until someone comes up with a solution to prevent the race condition on the nimcache, when multiple compilations run in parallel, it is probably advisable to disable the parallelization in [nimweb.nim](https://github.com/nim-lang/Nim/blob/devel/tools/nimweb.nim#L320) by changing line 320 from 
```nim
 mexec(commands, c.numProcessors)
```
to
```nim
 mexec(commands, 1)
```

**Comment by Araq** [comment]
No, the better fix is to fix ``runnableExamples``.

**Comment by skilchen** [comment]
Are you looking for a fix like #8281?
