### ISSUE TITLE
Allow heterogenous variable declarations in tuple unpacking

### ISSUE THREAD

**Issue by Quelklef** [nim-lang/Nim#8283]
Currently tuple unpacking looks like one of the following 3 cases:

```nim
var x: int
var y: char
(x, y) = producesTuple()
```

```nim
var (x, y) = producesTuple()
```

```nim
let (x, y) = producesTuple()
```

There is no way to signify that, for instance, I want `x` to be a `var` type, but `y` to be single-assignment. If I want to do this currently, I have to do:

```nim
let res = producesTuple()
var x = res[0]
let y = res[1]
```

Which is rather verbose. Since there's a tradeoff, then, between properly documenting `let` variables and changing a 1-liner into a 3-liner, people are likely going to choose the 1-liner, leading to less-than-optimally documented code.

I propose an alternative syntax which allows for terse code and per-variable declaration:

```nim
var x: int
(x, let y) = producesTuple()
```

Where each individual variable can be marked `var`, `let`, or already declared.

This could, of course, be achieved via some `:=` macro, but it would be nice to have natively and seems like a natural extension of the current syntax.

I haven't dealt with modifying the Nim compiler before, but I'd be happy to try my best in implementing it if people think it's a good idea.

**Comment by Araq** [comment]
I see no problem here that needs yet-another language feature.

**Comment by Quelklef** [comment]
I mean, no, it doesn't do anything that can't already be done, but it would be really nice to have. I know I'd personally make good use of it on my current project, in which I have many lines like: `var val: V; (val, head) = parseV(code, head)` and would much prefer `(let val, head) = parseV(code, head)`.

Besides, it seems strange to allow homogenous unpacking declarations like `var (x, y) = f()` _without_ allowing for something like this.

Also, I realized that a macro would have to be much uglier than simply `(let a, var b) := f()` because `(let a, var b)` is invalid syntax and doesn't get parsed.

That being said, it is, of course, your final call.

**Comment by cooldome** [comment]
```
let (x, _) = producesTuple()
var (_, y) = producesTuple()
```

**Comment by Bulat-Ziganshin** [comment]
It just looks like too minor feature. Every experienced developer may come with a long list of features, each one being useful in concrete place or two. We can't implement them all :)  So, the art of language design is to choose features that are really useful in many places. That said, i like `(var x,let y) = ..` idea, but such usecases probably doesn't come too often.

**Comment by Araq** [comment]
Solution:

```nim

var (x, y) = producesTuple()
# you are not force to mutate 'x' here.
```
