### ISSUE TITLE
Compiler hangs when using generics

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#8295]
Git hash: 1102f9aaf1c3d09640f0bb1cbd5e543871fcdc7c

Nim hangs when compiling this:

```nim
type
  AtomicType = pointer|ptr|int

  Atomic[T: AtomicType] = distinct T

  Block[T: AtomicType] = object

  AtomicContainer[T: AtomicType] = object
    b: Atomic[ptr Block[T]]
```

Removing type specification from `AtomicContainer` declaration makes it compile:
```nim
  AtomicContainer[T] = object
    b: Atomic[ptr Block[T]]
```

**Comment by Araq** [comment]
Is that a regression?

**Comment by endragor** [comment]
I don't think so, this also reproduces on a quite old commit.
