### ISSUE TITLE
Remove asyncio and dependencies

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8298]
This means removing ``asyncio`` and removing or at least rewriting the following:

* scgi

Refs #8261. There may be other dependencies, I haven't checked.

**Comment by Araq** [comment]
I like ``scgi`` fwiw. And I've said it before, I actually want a "batteries included" stdlib.

**Comment by dom96** [comment]
Okay, so rewrite it to use asyncdispatch.

**Comment by narimiran** [comment]
Closed by #10248.
