### ISSUE TITLE
compiler wrongly accepts `{. noSideEffect }` (should be {. noSideEffect .}`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8302]
```nim

proc fun1() {. noSideEffect .} = discard

# Error: invalid indentation
# proc fun2() { noSideEffect .} = discard

# BUG: should not compile
proc fun3() {. noSideEffect } = discard

# Error: invalid indentation
# proc fun4() { noSideEffect } = discard
```

**Comment by GULPF** [comment]
This is intentional afaik, but it's probably only documented in the [language grammar](https://nim-lang.org/docs/manual.html#syntax-grammar):
```
pragma = '{.' optInd (exprColonExpr comma?)* optPar ('.}' | '}')
```

**Comment by timotheecour** [comment]
yikes. everything else is paired, this just seems overly lax with 0 benefit, eg:
```nim
[# ... #]
probably others...
{. .} but {. } still ok?
```

this could lead to hard to find bugs when `}` would be mis-interpreted by user as a closing brace but recognized and used by compiler as closing pragma, in more complex code

**Comment by Araq** [comment]
> this could lead to hard to find bugs when } would be mis-interpreted by user as a closing brace but recognized and used by compiler as closing pragma, in more complex code

Since {} is so rare in Nim code, that never happened.

**Comment by Araq** [comment]
Works according to the spec.
