### ISSUE TITLE
type mismatch error drops crucial pragma info when there's only 1 argument

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8305]
on a type mismatch error, nim does an optimization when there's only 1 argument, however that optimization drops information that's useful for debugging such as pragmas, without which it's impossible to grok why the mismatch occurred. It's a bug.

```nim
#[ 
 ]#

proc fun*(s: string): string {.  .} = discard

when true:
  proc foo*[T, S](op: proc (x: T): S {. cdecl .}): auto = 1
  echo foo(fun)

else:
  proc foo*[T, S](a:int, op: proc (x: T): S {. cdecl .}): auto = 1
  echo foo(0, fun)

```

```
Error: type mismatch: got <proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](op: proc (x: T): S): auto

expression: foo(fun)
    echo foo(fun)
```
This error msg is useless, it misses the fact that 1st argument is "proc (x: T): S{.cdecl.}" (ie, misses pragma)

Now replace code above with "when false" (which adds a dummy argument, which causes nim error messages to show extended error message)
```
Error: type mismatch: got <int literal(0), proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](a: int; op: proc (x: T): S): auto
  first type mismatch at position: 2
  required type: proc (x: T): S{.cdecl.}
  but expression 'fun' is of type: proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}

expression: foo(0, fun)
    echo foo(0, fun)
```

* furthermore, it may not be abvious which pragma mis-maches cause the error (eg .noSideEffect, gcsafe, locks: 0 are fine, but cdecl is not), but that's a separate issue : ideally compiler would tell you that.

**Comment by Quelklef** [comment]
You get the same amount of information in both errors; in the first one, some is implied:

- Position of type mismatch (always the first if only one arg)
- Expected type
- Actual type recieved

What's the issue?

**Comment by timotheecour** [comment]
This error msg is not useful, it misses the fact that 1st argument is "proc (x: T): S{.cdecl.}" (ie, misses pragma, which is the only thing that matters for this mismatch.

**Comment by timotheecour** [comment]
if you're still not convinced hopefully this will:
```nim
proc fun*(s: string): string {.  .} = discard

when false:
  proc foo*[T, S](op: proc (x: T): S {. cdecl .}): auto = 1
  proc foo*[T, S](op: proc (x: T): S {. safecall .}): auto = 1
  echo foo(fun)

else:
  proc foo*[T, S](a:int, op: proc (x: T): S {. cdecl .}): auto = 1
  proc foo*[T, S](a:int, op: proc (x: T): S {. safecall .}): auto = 1
  echo foo(0, fun)

```

```
Error: type mismatch: got <proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](op: proc (x: T): S): auto
proc foo[T, S](op: proc (x: T): S): auto

expression: foo(fun)
    echo foo(fun)
```
is very confusing (and useless for debugging what went wrong)

vs:

```
Error: type mismatch: got <int literal(0), proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](a: int; op: proc (x: T): S): auto
  first type mismatch at position: 2
  required type: proc (x: T): S{.cdecl.}
  but expression 'fun' is of type: proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}
proc foo[T, S](a: int; op: proc (x: T): S): auto
  first type mismatch at position: 2
  required type: proc (x: T): S{.safecall.}
  but expression 'fun' is of type: proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}

expression: foo(0, fun)
    echo foo(0, fun)
```

**Comment by Quelklef** [comment]
No, I got it. That's what the :+1: was for :P

**Comment by timotheecour** [comment]
lol , i posted before refreshing and seeing it :)

**Comment by kaushalmodi** [comment]
This seems similar to this: https://github.com/nim-lang/Nim/issues/8043, similar in the sense that the compiler is not pointing the obvious error.

**Comment by timotheecour** [comment]
definitely a different bug, but both are very real bugs :-)
