### ISSUE TITLE
`findExe` should have an option to match unix `which` (and python `shutil.which`) behavior (cwd not searched, and by default symlinks not followed)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8311]
`findExe` should by default work like unix which (and python `shutil.which`):
* `cwd` not searched
* symlinks not resolved

```
## unix
which foo
/Users/timothee/homebrew//bin/foo

## python
python3 -c 'from shutil import *; print(which("foo"))'
/Users/timothee/homebrew//bin/foo

## nim
echo 'import os; echo os.findExe("foo")' | inim
INim 0.2.5
Nim Compiler Version 0.18.1 [MacOSX: amd64] at /Users/timothee/.nimble/bin/nim
/Users/timothee/homebrew//bin/../Cellar/foo/HEAD-81082d5/bin/foo
# or, if ./foo exists, it'd return that instead, which is not what should be done (by default at least)
```

* More generally, API's (such as `findExe`) should be orthogonal, and just do 1 thing and not 2 things like resolving symlinks on the result (principle of separation of concerns):
```nim
# this is preferable in terms of orthogonal API rather than cramming options in a single function
echo "foo".which.realPath
```

* if breaking change to `findExe` is not OK, we can introduce `os.which` (or do like python, introduce a higher level/cleaned up (on hindsight) module `shutil`) ; advantage is it could be extended to support returning a `seq` (from `which -a`) 

## example use case where proposed `which` could be used: inim
which currently resorts to shelling to which/where on posix/windows @AndreiRegiani
https://github.com/AndreiRegiani/INim/blob/c32bd4f27fbb24e67afc8552bff18184532525bf/src/inim.nim#L34

**Comment by dom96** [comment]
Some possibly relevant discussion here: https://github.com/nim-lang/Nim/pull/5049

**Comment by Araq** [comment]
It's not called ``which``.

**Comment by timotheecour** [comment]
@Araq would a `which` PR be accepted?

**Comment by Araq** [comment]
No. You can add another option to ``findExe`` though.
