### ISSUE TITLE
`nim doc foo` generates stuff that should be under a .gitignore'd directory

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8323]
/cc @skilchen after 6de52d2b747074e993707adca2f74143134ce127 
```
git status
# nothing, it's clean
nim doc lib/pure/ospaths.nim
git status
lib/pure/ospaths_examples_nimcache/ # this is generated
lib/pure/ospaths_examples.nim  #upon error, this is generated and not deleted
```

## proposal:
root generated files under a .gitignore'd directory, or allow customizing where these go, eg:
nim doc --docGeneratedRoot=/tmp/nimdoc/ lib/pure/ospaths.nim

generates:

/tmp/nimdoc/ospaths_examples_nimcache/ # this is generated
/tmp/nimdoc/ospaths_examples.nim  #upon error, this is generated and not deleted
(and maybe, /tmp/nimdoc/ospaths.html, but not sure about this last point)

**Comment by andreaferretti** [comment]
Why? I think it is often useful to commit the docs. Github will even generate a static site for you based on the contents of a docs directory.

In any case, you can customize the output of nim doc with `-o` as with any command

**Comment by timotheecour** [comment]
> Why? I think it is often useful to commit the docs

lib/pure/ospaths_examples_nimcache and lib/pure/ospaths_examples.nim are not related to docs
(they're generated when `nim doc lib/pure/ospaths.nim` fails, and perhaps generated and then removed when it succeeds)

> In any case, you can customize the output of nim doc with -o as with any command
it doesn't customize where these (lib/pure/ospaths_examples_nimcache and lib/pure/ospaths_examples.nim) go.

I also have --nimcache:"/Users/timothee/tmp/nim/nimcache/" in ~/.config/nim.cfg but it's not taken into account. Nor is `--nimcache:"/Users/timothee/tmp/nim/nimcache/"` on cmd line

**Comment by andreaferretti** [comment]
Sorry, now I see the issue

**Comment by timotheecour** [comment]
@andreaferretti => fixed this in https://github.com/nim-lang/Nim/pull/8392
