### ISSUE TITLE
`xmltree.findAll` doesn't work as expected with `htmlparser` for non-lowercase names

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#8329]
I tried the example from [here](https://nim-lang.org/docs/htmlparser.html#example-transforming-hyperlinks) on something like
```html
<P class=MsoNormal 
style="MARGIN-BOTTOM: 0pt; LINE-HEIGHT: normal; TEXT-AUTOSPACE: ; mso-pagination: none; mso-layout-grid-align: none"><SPAN 
lang=de 
style='FONT-SIZE: 12pt; FONT-FAMILY: "TimesNewRoman","serif"; mso-bidi-font-family: TimesNewRoman; mso-ansi-language: #0007'>1</SPAN><I><SPAN lang=de 
style='FONT-SIZE: 12pt; FONT-FAMILY: "TimesNewRoman,Italic","serif"; mso-bidi-font-family: "TimesNewRoman,Italic"; mso-ansi-language: #0007'>2<o:p></o:p></SPAN></I></P>
```
but `html.findAll("P")` doesn't work, instead only `html.findAll("p")` works, which is unexpected.

**Comment by GULPF** [comment]
I don't think this is fixable, due to Nim using the same data structure for XML and HTML. Tags in XML are case sensitive afaik.

**Comment by Araq** [comment]
@GULPF at least ``findAll`` can grow an option to support this.

**Comment by GULPF** [comment]
IMO sooner or later we will need to introduce a seperate type for HTML, even if it's just `type HtmlNode = distinct XmlNode`.
