### ISSUE TITLE
except zero and null are false

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#8332]
I want to write like c,c++ syntax (if x%2:...) instead of (if x%2 == 0: ...)

**Comment by SolitudeSF** [comment]
```
converter toBool(i: SomeNumber): bool = i != 0
```

**Comment by develooper1994** [comment]
I know but there is 3 process in your syntax has 

1. x%2 -> 1
2. 1 == 0 . Is this True or False?
3. if false . True or False?

C/C++ languages except zero false, others true. Now;
1. x%2 -> 1
2. if 1 . True or False? 1 excepts false when compile time.
Old compliers cannot make conversation.

**Comment by Yardanico** [comment]
2. False in Nim
3. False in Nim

**Comment by andreaferretti** [comment]
I don't think this is a good idea. If conditions accept a boolean, which is semantically not an integer. Otehr language mix booleans with other types, and thus have to deal with "falsey" values, which is just a complication.

For instance, in Javascript, the following values are falsey: `false`, `0`, `-0`, `null`, `undefined`, `""` and `Nan`. I am rather happy that Nim only allows if conditions on booleans.

**Comment by develooper1994** [comment]
If nim complier understand and calculate at compile time there is no problem. But it is optional syntax for flexibility.

**Comment by dom96** [comment]
This is a bad idea. Closing.
