### ISSUE TITLE
giving value to variable declaration while assignment

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#8334]
var x=-2,y=3:int
const x=-2,y=3:int
let x=-2,y=3:int

There is no syntax like that. It will be nice.

**Comment by bluenote10** [comment]
There is:

```
var
  x = -2
  y = 3

var x, y = (-2, 3)
```

**Comment by develooper1994** [comment]
There is not. that will give flexible writing. It is just my suggestion.
I understand. Thanks.
var
  x = -2
  y = 3
 :uint8
var x, y:int16 = (-2, 3)
