### ISSUE TITLE
Type mismatch error with alias types are useless

### ISSUE THREAD

**Issue by LemonBoy** [nim-lang/Nim#8339]
```nim
import sequtils

var x: seq[float] = @[1].mapIt(it)
```
Gives the following error message:
`foo.nim(3, 25) Error: type mismatch: got <seq[outType]> but expected 'seq[float]'`

I think `outType` should be resolved and presented to the user, otherwise the error message is completely useless.

I've toyed with this representation:
```
foo.nim(3, 25) Error: type mismatch: got <seq[outType = EXPANDED]> but expected 'seq[float]'
```
and
```
foo.nim(3, 25) Error: type mismatch: got <seq[outType]> but expected 'seq[float]'
Where:
outType = EXPANDED
```
but neither is too appealing to me.

**Comment by timotheecour** [comment]
the 1-liner `foo.nim(3, 25) Error: type mismatch: got <seq[outType = EXPANDED]> but expected 'seq[float]'` is better since there could be multiple such mismatch errors

**Comment by LemonBoy** [comment]
One more data point
```nim
type E = char
var x: proc (x: E)
proc u(x:float) =
  discard
x = u
```

gives

```
foo.nim(5, 3) Error: type mismatch: got <proc (x: float){.noSideEffect, gcsafe, locks: 0.}> but expected 'proc (x: E){.closure.} = proc (x: Char){.closure.}'
```

**Comment by andreaferretti** [comment]
@LemonBoy It is because the problem is not with aliases but with generics (the title is misleading)

**Comment by LemonBoy** [comment]
That was to show how verbose the error message may become, this is what `master` spits out
```
Error: type mismatch: got <proc (x: float){.noSideEffect, gcsafe, locks: 0.}> but expected 'proc (x: E){.closure.}'
```

With some changes I did it now spits

```
Error: type mismatch: got <proc (x: float){.noSideEffect, gcsafe, locks: 0.}> but expected 'proc (x: E){.closure.} = proc (x: Char){.closure.}'
```

**Comment by timotheecour** [comment]
clang uses aka instead of = for that. i dont care either way
