### ISSUE TITLE
Can't create variant with an enum with holes

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/Nim#8340]
```nim
type
  Enum* = enum
    Field1 = 0,
    Field2 = 1,
    Field3 = 345

  Test* = ref object
    case kind*: Enum
    of Field1:
      type1*: float
    of Field2:
      type2*: string
    of Field3:
      type3*: int
```

This used to work in Nim 0.18.0, but on the latest devel it causes a compiler error:

```
file1.nim(9, 5) Error: selector must be of an ordinal type
```

The line it's talking about is the case statement. If I remove the holes, it compiles fine. Is this a bug or the intended behavior?

**Comment by BarelyMalicious** [comment]
@jyapayne  https://github.com/nim-lang/Nim/pull/8264

**Comment by jyapayne** [comment]
@BarelyMalicious Ah, I see, thanks. Any idea on how to replace the above with something equivalent?

**Comment by BarelyMalicious** [comment]
@jyapayne Sorry, no idea. You might have better luck asking at irc/gitter or the forums.

**Comment by Araq** [comment]
> Is this a bug or the intended behavior?

Intended behaviour.

**Comment by Araq** [comment]
> You might have better luck asking at irc/gitter or the forums.

Yeah, because this github issue tracker clearly looks abandoned. Only produces 50 posts each day.
