### ISSUE TITLE
[RFC] `extractFilename("usr/lib/")` should return "lib" (not "") and be called `baseName` (since works with dirs)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8341]
/cc @dom96  this is relevant for https://github.com/nim-lang/Nim/pull/8315#discussion_r202540102

* Most languages have a `baseName` function instead of `extractFilename` ; and I see `extractFilename` comes from `Delphi`, `FreePascal`, which are more "fringe" for Nim userbase (IMO) compared to the other ones.
More importantly, `extractFilename` is not a good name because it works with directories, eg in "/home/bob", "bob" is not really a filename (it's a directory); that's why every other language uses basename.

* path semantics can be ambiguous due to things like trailing `/` etc; it's annoying but we should find the most sensible semantics.

Currently `extractFilename("usr/lib/")` returns `""` ; let's see how other languages handle this corner case:

## these return "lib":
* unix cmd line
* C (cf http://man7.org/linux/man-pages/man3/basename.3.html)
* D
* node.js

## these return ".":
* C++ boost::filesystem::basename or c++17 std::experimental::filesystem

## these return "":
* python https://docs.python.org/3/library/os.path.html

# proposal: deprecate `extractFilename` (keeping its behavior so code won't break), and introduce `baseName` which would work as unix, C, D, node.js.

rationale:
* directories can be specified either with trailing `/` or not (eg, in environment variables, and shouldn't affect their basename. eg: `DESTDIR=/tmp/foo run_prog` or `DESTDIR=/tmp/foo/ run_prog` should have same semantics
* an actual directory name or file name can never be empty, but python's convention of returning empty "" breaks that assumption.
* on posix, using C's `basename` convention, ~~`isHidden("./git/")`~~  **EDIT** `isHidden(".git/")` would be true which makes more sense; using python's convention, it would be false (with https://github.com/nim-lang/Nim/pull/8315 implementation)

would a PR be accepted for that?

**Comment by Araq** [comment]
Meh, "basename" is a terrible name, might as well call it ``pathTail``. And the fact that ``extractFilename`` "works on directories too", well it really doesn't, you're misusing it for ``pathTail``. That's not a good reason for deprecating it.

**Comment by kaushalmodi** [comment]
baseName would be a familiar name as it's used by many shells too (bash, tcsh). 

Another data point: https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Components.html

**Comment by timotheecour** [comment]
not married to `basename`, but that what it's called in unix, C, D, node.js (and python, except with Nim's semantic) so ppl may be familiar with that already.
As for semantics, would you guys be ok w a function (whatever the name, pathTail or basename) that had semantics of C's basename?

**Comment by kaushalmodi** [comment]
Continuing my previous comment, the Emacs basename would return "" too for "/foo/lib/".

**Comment by dom96** [comment]
> on posix, using C's basename convention, isHidden("./git/") would be true which makes more sense; using python's convention, it would be false (with #8315 implementation)

The Python result makes more sense to me. ``.`` means current directory, so to me that's not a hidden path.

> More importantly, extractFilename is not a good name because it works with directories, eg in "/home/bob", "bob" is not really a filename (it's a directory); that's why every other language uses basename.

I disagree with this too. ``"bob"`` in this context could very well be a file thanks to how binaries are named on Unix. So IMO ``extractFilename`` is perfectly fine, and unless there is a real use case for ``basename``'s semantics **I am rejecting this RFC.**

**Comment by kaushalmodi** [comment]
@timotheecour Emacs has a strong requirement (seen in many functions, API) that directory names always end in "/". In Unix systems, a directory is a "file" too! Semantically everything is a "file". So sticking to a "/"-ending is the best way to distinguish directories. 

So in response to your rationale section:

> directories can be specified either with trailing / or not (eg, in environment variables, and shouldn't affect their basename. eg: DESTDIR=/tmp/foo run_prog or DESTDIR=/tmp/foo/ run_prog should have same semantics

That's a bad idea. Then we cannot distinguish whether an input arg is a file or a directory. How about having something as [`file-name-as-directory`][1]? That will convert the env var parsed directory names to ones ending in "/". 

> an actual directory name or file name can never be empty, 

If the extractFilename is returning "", it means that you are looking at a directory name, not a "Filename". So it makes perfect sense to me. It can be used to check of the input argument is a directory (if that code is using a strong convention of always ending directory names in "/"). 

[1]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Names.html#Directory-Names

**Comment by timotheecour** [comment]
> So sticking to a "/"-ending is the best way to distinguish directories.
> It can be used to check of the input argument is a directory (if that code is using a strong convention of always ending directory names in "/").

@kaushalmodi unfortunately there are tons of code that doesn't follow this convention, so we can't use that logic

@dom96 I just fixed a typo, I meant `isHidden(".git/")` ; which IMO should be true (as in `java.io.File.isHidden`).

Anyway looks like these 2 statements are contradicting:

> And the fact that extractFilename "works on directories too", well it really doesn't, you're misusing it for pathTail

> extractFilename is perfectly fine, and unless there is a real use case for basename's semantics

If we're not introducing basename/pathTail, other possibilities are:
* introducing stripTrailingSep (which just strips tailiing separator (if any) without further transformations on the input as `normalizedPath` does):
`doAssert stripTrailingSep("a/b/.///") == "a/b/."`
* add an optional arg to `extractFilename`: `extractFilename(path: string, bool ignoreTrailingSep = false)`

**Comment by Araq** [comment]
> As for semantics, would you guys be ok w a function (whatever the name, pathTail or basename) that had semantics of C's basename?

```nim

import os

let (head, tail) = splitPath("/foo/bar")
echo head, " ", tail
```

**Comment by timotheecour** [comment]
the main issue is trailing `/`:
```nim
>>> import os
>>> let (head, tail) = splitPath("/foo/bar/")
>>> echo head, ":", tail,":"
/foo/bar::
```

`basename` in unix, C, D, node.js would return `bar`, not `""`

**Comment by kaushalmodi** [comment]
At least to me it seems to be a special case that can be dealt with:

```nim
import os, strformat

proc myBaseName(path: string): string =
  var (head, tail) = splitPath(path)
  if tail == "":
    (head, tail) = splitPath(head)
  return tail

let paths = ["/foo/bar/",
             "/foo/bar"]
for p in paths:
  echo fmt"path = `{p}', basename = `{p.myBaseName}'"
```

Outputs:

```
path = `/foo/bar/', basename = `bar'
path = `/foo/bar', basename = `bar'
```

**Comment by Araq** [comment]
Well we can fix/change ``splitPath``.
