### ISSUE TITLE
`=~` template from re.nim doesn't work in generics

### ISSUE THREAD

**Issue by Vindaar** [nim-lang/Nim#8342]
Just stumbled on this rather weird bug. The `=~` doesn't seem to work in a generic proc, because the `matches` variable doesn't seem to be injected. Reduced my code to a minimum example (of course the 2 generic cases don't need to be generic here).

I just tested this on the current devel https://github.com/nim-lang/Nim/commit/fc0bcccc15ec5cf3351cf65b22c7a038d82d4b35 (commit 13000, yay).

The following works as expected
```nim
import re
proc dsets(): string =
  let pattern = re(r"run_(\d+)/chip")
  let dset = "run_123/chip"
  if dset =~ pattern:
    result = matches[0]

echo dsets()
```
But any of these two:
```nim
import re
proc dsets[T](): string =
  let pattern = re(r"run_(\d+)/chip")
  let dset = "run_123/chip"
  if dset =~ pattern:
    result = matches[0]

echo dsets[int]()
```
```nim
import re
proc dsets(dtype: typedesc): string =
  let pattern = re(r"run_(\d+)/chip")
  let dset = "run_123/chip"
  if dset =~ pattern:
    result = matches[0]

echo dsets(int)
```
just throws:
```sh
Error: undeclared identifier: 'matches' 
```

**Comment by Araq** [comment]
That's not a bug, it requires a ``mixin matches`` declaration in generics. You can argue the spec is weird here, which is fair enough, but already has its own issue.
