### ISSUE TITLE
Windows: can't compile with var name "far"

### ISSUE THREAD

**Issue by Aldlevine** [nim-lang/Nim#8345]
This is a similar issue to #5598, and I imagine the solution is the same. I'm currently solving it by renaming the variable "far", but this obviously feels a bit kludgy. Thanks!

**Comment by tim-st** [comment]
Do you have an example that doesn't work?

**Comment by Aldlevine** [comment]
My specific issue results from a macro that's parsing a GLSL shader to identify uniforms, so it won't serve as a good example. However, I can set up a simple case as soon as I get the time.

**Comment by Aldlevine** [comment]
Okay, this isn't the same exact result that I'm experiencing in my main project (the main project actually prints an error, while this just hangs indefinitely), but it appears to result from the same source as changing the field 'far' to anything else fixes the issue in both cases.

```nim
type
  MyType = ref object
    far: int

let t = MyType()
t.far = 10
echo t.far
```

compiled using:
```shell
nim c --threads:on --cc:vcc test.nim
```

Also, just a few additional notes:
1. Compiled using Visual Studio 2017 (same code is fine on Linux).
2. I initially thought this impacted variable names, but it seems to only impact object fields.
3. It only seems to be an issue when compiling with `threads:on`.
4. It doesn't affect the sibling keyword 'near'.

**Comment by Yardanico** [comment]
@Aldlevine by the way, this issue is not about Windows, it's probably about Visual Studio C Compiler, because a lot of people (like me) use MinGW on Windows for Nim.

**Comment by dom96** [comment]
I guess you can simply copy what was done here: https://github.com/nim-lang/Nim/commit/93f0f1c6e4a7f6b2c4cd19f7cc246c18531ae0c0. Could you try it and make a PR?

**Comment by Aldlevine** [comment]
@Yardanico thanks for clarifying. I should have been more precise initially.
