### ISSUE TITLE
[ospaths] toSeq(parentDirs("/a/b")) returns @["/a/b", "/a", ""] instead of @["/a/b", "/a", "/"] (last entry wrong)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8353]

**Comment by Bennyelg** [comment]
Works fine when I compile it
```nim
import ospaths
import sequtils
for e in parentDirs("/Users/benny/Work"):
    echo(e)


echo(toSeq(parentDirs("/Users/benny/Work")))
```

**Comment by Bennyelg** [comment]
Same with
```
toSeq(parentDirs("/a/b"))
```

**Comment by timotheecour** [comment]
yes, that's the problem, it should be `@["/a/b", "/a", "/"]`, not `@["/a/b", "/a", ""]`
the last entry `""` is bad

**Comment by Bennyelg** [comment]
Yea, I was misleading by the issue name.

**Comment by timotheecour** [comment]
related to that: https://github.com/nim-lang/Nim/issues/8395 ospaths: `tailDir("/usr/local/bin")` should be "usr/local/bin" instead of "local/bin" (because of `/`) #8395

**Comment by timotheecour** [comment]
* fixed by https://github.com/nim-lang/Nim/pull/13236
* likewise for 
> related to that: #8395 ospaths: tailDir("/usr/local/bin") should be "usr/local/bin" instead of "local/bin" (because of /) #8395
