### ISSUE TITLE
times module: table repeated twice

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8385]
the same table is repeated twice in https://nim-lang.org/docs/times.html, under this:
`proc format(dt: DateTime; f: string): string {..}`
and this:
`proc parse(value, layout: string; zone: Timezone = local()): DateTime {..}`
even though source code only has 1 table defined.

this leads to confusion, as reader will try to spot if there are any difference between the 2 tables.
would be better to just refer to the same table (via href or just "see table below format")

**Comment by GULPF** [comment]
This has been cleaned up already in #8094
