### ISSUE TITLE
Type deduction in generic broken with default parameter value

### ISSUE THREAD

**Issue by LemonBoy** [nim-lang/Nim#8390]
Test case (notice how `y` is initialized to `1` rather than `1.0`):

```nim
import typetraits

proc x[T:SomeFloat](q: openarray[T], y: T = 1) =
  echo q.type
  echo y.type

x(@[1.0])
```

The output is:
```
openarray[int]
int
```

**Comment by Araq** [comment]
This is not a template. In general the compiler is overly happy to ignore generic constraints, as long as they "match" the compiler doesn't bother to also use them to constrain the possible concrete types.

**Comment by LemonBoy** [comment]
Beside the failed constraint on the generic parameter I'm also surprised to see that when the procedure is instantiated the `T` is bound to the value of the generic parameter. That's not what the matcher does because I guess it'd have noticed that a `seq[float]` is not convertible to `openarray[int]`.

**Comment by Clyybber** [comment]
Now outputes
```
openArray[float64]
float64
```
which seems correct?

**Comment by bung87** [comment]
seems correct
