### ISSUE TITLE
typed procs with for loops are not renderable

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#8397]
Example
```
proc test(x: int): int =
  for j in 0..<x:
    result.inc j
```

``test`` proc get rendered as
```
proc test(x: int): int =
  block :tmp115052:
    var j
    var i = 0
    block :tmp115053:
      while i < x:
        j = i
        inc(result, j)
        inc i, 1
```

Two issues: variable ``j`` has no type. Blocks are using `:tmp` gen prefix, parser rejects it.

**Comment by Araq** [comment]
The real problem here is that for loops get eliminated so early. This should not be done.

**Comment by cooldome** [comment]
Thanks for reply,
I actually I agree, getImpl should return AST before transformation phase. 
I will prepare a new PR

**Comment by Araq** [comment]
Your PR was merged, closing.
