### ISSUE TITLE
problem with default value of NimNode.

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#8402]
This code does not compile (on development branch)

```Nim
import macros

static:
  var empty: NimNode
  let otherEmpty = empty
```
this is the error message:
```
scratch.nim(5, 13) Error: attempt to access a nil address
```

This is a regression, in latest release this is not yet a problem.

**Comment by GULPF** [comment]
This was probably caused by me and I think I have a fix, I'll open a PR for it soon.

**Comment by krux02** [comment]
@GULPF I think it is ok, when you remove the nil state for NimNode entirely and make it by default initialized with an empty node. That would also remove a lot of nil checks in the compiler as well. As far as I know the nil state is only something that can come up on non initialized variables.

**Comment by GULPF** [comment]
@krux02 I don't disagree that it might be useful to always initialize `NimNode` to an empty node, but this bug isn't specific to `NimNode`. E.g this fails to:
```nim
static:
  type R = ref object
  var empty: R
  let otherEmpty = empty
```

**Comment by krux02** [comment]
Well, then I guess you have to fix this. And extend a test case to also cover this.
