### ISSUE TITLE
SIGSEGV on generic macro returning a type

### ISSUE THREAD

**Issue by Quelklef** [nim-lang/Nim#8406]
The following SIGSEGVs:

```nim
macro f(x: static[int]): untyped = discard
proc g[X: static[int]](v: f(X)) = discard
```

This _is_ valid with the type system, though, right? Since `X` is known at compile-time it can be used to generate a type for `v`? I want to do something like this:

```nim
type MyFancyConcreteType = ...
type MyFancyGenericType[N: static[int]] = ...

macro Choose(N: static[int]): untyped =
  if N == 2:
    return ident("MyFancyConcreteType")
  else:
    return nnkBracketExpr.newTree(ident("MyFancyGenericType"), newIntLitNode(N))

var x: Choose(2)  # of MyFancyConcreteType
var y: Choose(3)  # of MyFancyGenericType[3]

# Generic procs may still be written
proc doSomethingWithEither[N: static[int]](v: Choose(N)) = ...
```

Is this possible, SIGSEGV or no; should I abandon the idea?

**Comment by mratsim** [comment]
I don't know if it should work or not.

At the moment you can generate the proc in the macro or use a wrapper type like I did in [Stint](https://github.com/status-im/nim-stint/blob/master/stint/private/datatypes.nim).

In you example that would be something like this:
```Nim
macro Choose(N: static[int]): untyped =
  if N == 2:
    return ident("MyFancyConcreteType")
  else:
    return nnkBracketExpr.newTree(ident("MyFancyGenericType"), newIntLitNode(N))

type MyFancyConcreteType = ...
type MyFancyGenericType[N: static[int]] = ...

type MyFancyType[N: static[int]] = object
  impl: Choose[N]

var x: Choose(2)  # of MyFancyConcreteType
var y: Choose(3)  # of MyFancyGenericType[3]

# Generic procs may still be written
proc doSomethingWithEither[N: static[int]](v: MyFancyType[N]) = ...
```

You should put a full working example, btw. I think your issue is linked to https://github.com/nim-lang/Nim/issues/7231

**Comment by Quelklef** [comment]
Yes, I believe you helped me implement your solution a while back. I decided I wanted to see if I could find a solution involving no wrapper types.

What do you mean by a full working example? In regards to the bug, or to my intended feature?

**Comment by mratsim** [comment]
I meant:

```Nim
type MyFancyConcreteType = object
type MyFancyGenericType[N: static[int]] = object
  foo: array[N, int]
```

Instead of `type MyFancyConcreteType = ...` so that we can directly copy-paste like the lazy programmers we are :).

**Comment by Quelklef** [comment]
Ah, I'll be sure to keep that in mind for the future ;-)

**Comment by saem** [comment]
Tested in playground, no more sigsev, an error is produced instead: `/usercode/in.nim(2, 28) Error: expression '' has no type (or is ambiguous)`

**Comment by metagn** [comment]
Early generic evaluation bug again, can link #8551 and #22607 right now but there are more related issues

As described in the other issues, delegating to a generic type is a workaround

```nim
macro f(x: static[int]): untyped = discard
type FWrapper[x: static int] = f(x)
proc g[X: static[int]](v: FWrapper[X]) = discard
```
