### ISSUE TITLE
Nim file named the same as C file causes Nim file to be linked twice.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#8407]
When a Nim file (a.nim) is used with a C file (a.c) of the same name, Nim would not throw any error as if they were both Nim files. C will compile the code yet nimcache will only have an object file for the Nim file. When linking, the following errors will occur:
```
a.o: In function `a_LXoXxA4bUETX9cn8hX3n8qA':
a.nim:1: multiple definition of `a_LXoXxA4bUETX9cn8hX3n8qA'
```

Shouldn't the "module names need to be unique per Nimble package;" error occur?

**Comment by mratsim** [comment]
Note: I've been using stb_image for months and it didn't have any issue: https://github.com/define-private-public/stb_image-Nim/tree/master/stb_image even though the .c and .nim files are named the same.

cc @define-private-public

**Comment by define-private-public** [comment]
Could you provide some information about what version of Nim you are using?

**Comment by kayabaNerve** [comment]
Devel. The code referenced is fine only because it's a Nimble package, according to our Gitter chats.

**Comment by Araq** [comment]
This has been fixed recently.
