### ISSUE TITLE
[RFC] Standardize how paths are treated in the header pragma.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#8408]
When working with pragmas, specifically the ones involving the compiler and linker, how paths are treated vary wildly. In a source tree where:

- All Nim is under /nim.
- All C is under /c.
- The nimcache is /build/nimcache.
- The compiler is called from the root of tree.

The passC pragma will work off wherever the Nim compiler is called (c/).
The compile pragma will be relative to the current Nim file (../c/file.c)
The header pragma will be relative to the nimcache directory (../../c/file.h).

I understand why Nim handles passC as it does, because it doesn't change he passC pragma at all, and do not want to change that. I do believe that the compile and header should have consistent paths though. Therefore, I would like to request the change that just like modules and the compile pragma, the header pragma's path be relative to the Nim file it is in.

**Comment by Araq** [comment]
Yeah, let's change what how ``.header`` does it.
