### ISSUE TITLE
Less strict branch expression semantics

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#842]
Not all branches needs to evaluate to a value, provided that an exception is raised for example, in the branches that do not:

``` nimrod
let x = if true: 0 elif true: 0 else: raise newException(E_Base, "")
```

**Comment by def-** [comment]
The `noReturn` pragma should help with this.

**Comment by cooldome** [comment]
implemented in https://github.com/nim-lang/Nim/pull/6954
