### ISSUE TITLE
locally built docs point to wrong branch in `Source` link (`Edit` one is ok though)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8420]
./koch web
open doc/html/times.html
click on `Source` under "proc format(dt: DateTime; f: static[string])"
it points to: 
https://github.com/nim-lang/Nim/blob/master/lib/pure/times.nim#L2105
which is not ok (that line doesn't even exist in branch master); it should point to branch `devel` by default since (by some convention which is odd to me) development (and default for git clone) for Nim is under `devel` branch instead of `master`.

click on `Edit` link: it points to:
https://github.com/nim-lang/Nim/edit/devel/lib/pure/times.nim#L2105
which is ok (starts from correct branch)

## suggested solution:
allow customizing which branch is shown in these links, eg:
```nim
# we should allow these (currently doesn't work):
./koch web --git.commit=devel
# and to point docs to my fork / myfeaturebranch:
./koch web --git.url=https://github.com/timotheecour/Nim --git.commit=myfeaturebranch
```

NOTE: the `git.url` syntax I suggest comes from what I'm seeing in logs:
bin/nim doc2 --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.18.1 --git.url:https://github.com/nim-lang/Nim -o:web/upload/0.18.1/pcre.html lib/wrappers/pcre.nim

the `git.commit` syntax comes from nimweb.nim: 
```nim
var commit = getConfigVar(d.conf, "git.commit")
      if commit.len == 0: commit = "master"
```
although I'm not sure how to set git.commit from ./koch web currently

i also tried adding this to ~/.config/nim.cfg
--git.url:"https://github.com/timotheecour_temp/Nim"
--git.commit:pr_exp_temp_branch

but only `--git.commit` had an effect (and we should probably allow setting from cmd line anyways, since it'd enable: ./koch web --git.commit=`git branch`)

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/8423

**Comment by Araq** [comment]
This was done on purpose as these docs eventually need to point to 'master' anyway as master refers to the latest stable release. But I agree it's a really bad solution and I welcome your PR.
