### ISSUE TITLE
proposal: `bitEquals` in system.nim ? (has implementation + tests) ; to test bit pattern equality regardless of type #22

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8436]
```nim
import unittest

proc bitEquals[T1, T2](a1:T1, a2:T2): bool =
  ## returns true if bit patterns of ``a1``, ``a2`` are same
  let p1 = unsafeAddr(a1)
  let p2 = unsafeAddr(a2)
  let n1 = sizeof a1
  let n2 = sizeof a2
  return n1 == n2 and equalMem(p1, p2, n1)

proc test()=
  type B=object
    age:int

  type C=ref object
    age:int

  type B2[T]=object
    foo:T

  let a1=1
  let a2=1
  let foo = @[1,2]

  let c1=C(age:1)
  let c2=C(age:1)
  let c1b = c1

  let s1="foo"
  let s2="fo" & "o"

  check:
    c1 != c2
    not bitEquals(c1, c2)
    c1 == c1b
    bitEquals(c1, c1b)

    s1 == s2
    not bitEquals(s1, s2)

    bitEquals(1, 1)
    not bitEquals(1, 1.0)
    not bitEquals(1, 2)
    bitEquals(1, a1)
    bitEquals(a1, a2)
    bitEquals(B(age:10), B(age:10))
    not bitEquals(B(age:10), B(age:11))

    bitEquals(B2[int](foo:1), B2[uint](foo:1))

    bitEquals([1,2], [1,2])
    not bitEquals([1,2], [1,3])

    bitEquals(@[1,2], @[1,2]) # this case is interesting: the litterals have same addr
    not bitEquals(@[1,2], foo)

    not bitEquals(@[1.0,2.0], @[1,2])
    bitEquals([byte 0, 0, 0, 0], [0'u32])
    not bitEquals([byte 0, 0, 0, 0], [0'u64])

test()
```

(analog to D's `val1 is val2` which is useful in some cases)

**Comment by hlaaftana** [comment]
`bitEquals(@[1,2], @[1,2]) # this case is interesting: the litterals have same addr`

Probably optimized by C compiler

The only benefit I can think of from this proc is that it turns `eq(a, b)` into `eq(&a, &b)`. Beyond that it's too simple an implementation to add to the system module in my opinion.

```nim
proc eq[T, U](a: ptr T, b: ptr U): bool =
  when sizeof(T) != sizeof(U):
    false
  else:
    equalMem(a, b, sizeof(T))
```

**Comment by timotheecour** [comment]
is `proc eq[T, U](a: ptr T, b: ptr U)` already defined? can't find it by string search in Nim repo. In any case, `val1 is val2` is used often in phobos, and inlining the code of `bitEquals` whereever this is needed seems error prone. Doesn't have to be in system module thouhg; can you recommend another module in lib?

**Comment by data-man** [comment]
> can you recommend another module in lib?

bitops?

**Comment by timotheecour** [comment]
it enables speed optimizations in certain operations, see for eg https://github.com/nim-lang/Nim/pull/8612#issuecomment-415201549

**Comment by Araq** [comment]
It enabled speed optimizations in the 90ies. Compilers now detect ``memcmp`` like loops and rewrite them.

**Comment by Araq** [comment]
Still unconvinced.
