### ISSUE TITLE
RFC: nice parameter syntax

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [nim-lang/Nim#8450]
RATIONALE: the current syntax for procedure parameters supports many features (generic part, type params, static params...), but the syntax was evolved gradually and isn't perfectly [natural and orthogonal](https://github.com/nim-lang/Nim/issues/8363#issuecomment-408069075).

Existing parameter syntax 
- gives different semantics to the same syntax used in left (generic) and right parts of parameters specs: `proc f[T: int|ref] (v: int|ref)`
- forces to use different syntax for the same semantics in different parts: `proc f[T1: int|ref] (T2: typedesc[int|ref])`
- 'var' parameter class is specified in the front of spec, while typedesc/static classes are specified as part of type specs: `proc f(var x: int;  y: static[int];  T: typedesc[ref])`

---

This proposal describes the syntax that is:
- the same for generic and common parts, except for different defaulting (type/const are supposed in generic part)
- any param is described by 5 sections (class, ident, type, possible values, default value), each of which may be omitted
- each section has natural meaning, i.e. `: type` always describes parameter type, while `==values` used to describe a set of possible values
- implements all (?) existing Nim features 
- adds new feature - overloading by constant value with simple concise syntax
- overloads for specific type get shorter
- declaration may be started with 'type'/'const' word making its class more obvious

Proposed parameter syntax is:
```
[ 'var' | 'type' | 'const' ]
   [ idents [ : types] [ == values] [ = default_value]
   | values [ = default_value]
   ]
```
with the following meaning of each part:
- `[ 'var' | 'type' | 'const' ]` specifies a parameter kind - value (default for right part), variable, type (assumed by default in generic part) or compile-time constant (default for non-type params in generic part)
- `idents` specify one or more identifiers - all get the same specification
- `: types` specifies the parameter type (or type predicate), 'any' by default
- `== values` specifies possible parameter values (type predicate for types, 'x|y|z...' otherwise)
- `= default_value` specifies the default parameter value
- `idents [ : types] ==` part may be omitted if we provide the possible values spec

### Type parameters

Proposed syntax for type params is `type T [==types] [=default]` instead of current ones: `T [:types] [=default]` for the left part and `T: typedesc'['types']' [=default]` for the right part.

I.e. we propose uniform syntax `==types` to specify possible types while current syntax uses `:types` on the left and `typedesc[types]` on the right for the same purpose.

We also propose shorter syntax `types [=default]` for the cases when identifier for the parameter isn't required. The 'type' keyword almost always can be omitted. Examples follow:

`proc f[int]()` in the new syntax is the same as `proc f[T: int]()` in the existing one.

`proc f(int)` is the same as old `proc f(T: typedesc[int])`. As you see, descriptions of type params in both generic and right parts of the function header will look identical, unlike the existing Nim syntax. It also allows to drop the parameter name when we don't need it.

`proc f[int32|int64]()` ==> `proc f[T: int32|int64]()`, type predicates keeps all the power they have in the existing Nim syntax.

`proc f [T == int32|int64]()` ==> `proc f[T: int32|int64]()`, here we actually define id for the type. We use '==' to say `it may be one of int32 or int64`, while `T: int32|int64` syntax in both left and right parts will be reserved for the meaning `T may have type int32 or int64`.

`proc f [T = int]()` keeps the old meaning 'T can be any type, int if omitted'.

`proc f(T = int)` ==> `proc f(T: typedesc = int)`. Again, in the proposal, the same syntax in left and right parts mean the same; we can infer that T is a type from its default value.

`proc f(T == int|ref = int)` ==> `proc f(T: typedesc[int|ref] = int)`. Here we specify both a list of possible values of type T (int|ref) and the default value 'int'. If we don't need a name for the type, it may be omitted along with '==', so `proc f(int|ref = int)` means the same but without name for the type.

`proc f[T == int|ref = int]()` ==> `proc f[T: int|ref = int]()`. Again, the syntax for generic part is exactly the same as for right part of function header.

A few extra examples where we omit various parts of type specs: `proc f( T = int;  U == int|ref;  int|ref = int;  int|ref )`. We can move all these specs into generic part without any changes: `proc f[ T = int;  U == int|ref;  int|ref = int;  int|ref ]()` which in old syntax is `proc f[ T = int;  U: int|ref;  _: int|ref = int;  _: int|ref ]()` 

`proc f[T](U == any;  type V)` - the T/U/V specs are equivalent - they all specify unrestricted type parameters. Keyword 'type' is necessary only for types in right part without '=dflt' and '==values' parts, but can be added to any specification of type parameter for clarity. For comparison, the same declaration in the current syntax is `proc f[T](U,V: typedesc)`.

### Compile-time constants

Proposed syntax for constant params is `const T [:types]  [==values] [=default]` instead of current `T static'['types']' [=default]`, so we basically replace 'static[]' in the type spec with 'const' in front. In the generic part, 'const' almost always may be omitted. We also propose shorter syntax `values [=default]` for the cases when identifier for the parameter isn't required. Examples follow:

`proc f[C: int]()` translates to `proc f[C: static[int]]()` in the old syntax. Note that generic part cannot have value parameters, so we suppose that C is const, but it can be also specified explicitly: `proc f[const C: int]()`.

`proc f(const C: int)` translates to `proc f(C: static[int])` in the old syntax. Again, the proposed syntax is the same for left and right parts, except that we can drop 'const' in generic part.

`proc f[C: int|ref]()` ==> `proc f[C: static[int|ref] ]()`, i.e. we keep the full power of type predicates.

`proc f[C = 3]()` ==> `proc f[C: static[int] = 3]()`, the constant type may be dropped (and thus inferred) if we supply default value or list of possible values. `proc f(const C = 3)` for the same in right part.

`proc f[C: int|ref = 3]()` ==> `proc f[C: static[int|ref] = 3]()` for a constant with two possible types and default value. 

`proc f(const C: int|ref = 3)` ==> `proc f(C: static[int|ref] = 3)` is the same for constant in the right part.

### Overloading by constant value

The proposal provides syntax for new feature - overloading by constant value. The simple example:
```Nim
proc fib[0]() = 1
proc fib[1]() = 1
proc fib[N:int]()  =  fib[N-1]() + fib[N-2]()
```
or the same with const param in right part:
```Nim
proc fib(const 0) = 1
proc fib(const 1) = 1
proc fib(const N: int)  =  fib(N-1) + fib(N-2)
```

Similar to C++, this requires that more specific overload (for 0 or 1) is selected preferably over more general overload (for any int N).

The following declarations are equivalent:
```Nim
proc fib(const N: int == 0) = 1
proc fib(const N == 0) = 1
proc fib(const 0) = 1
```
In the second one we dropped type since it can be inferred from the only possible value, and in the third one we dropped "N==" part since we don't need an identifier (for the only possible value).

### More examples - compile-time constants

`proc f[C == 3|4]()` - we may provide a list of possible values, similar to list of types (do we really need that?).

`proc f[C: int == 3|4]()` - the same with explicitly specified type.

`proc f[C: int == 3|4 = 3]()` - the same with explicitly specified type and default value.

`proc f[C == 3|4 = 3]()` - with list of possible values and default value.

`proc f[const C]()` - C declared as generic constant that may have any type.

### Values/variables

The syntax for value and variable parameters are exactly the same as in the current Nim. The only new feature is list of possible values `==values`, which I propose to simply prohibit for the moment. By enabling it, we may support function overloading by runtime values, which may be further developed into pattern matching:
```Nim
proc f(3) = 4
proc f(4) = 5
```

### Transition from the existing syntax

If this proposal will be accepted, Nim will need to support both old and new syntaxes for the transition period, so let's analyse whether it's possible without additional pragmas:
- var/value parameters syntax isn't changed at all
- existing typedesc/static specifiers are incompatible with the proposed syntax, so they may coexist in the transition period
- afaik, the only incompatibility is `f[ T: int|ref ]()` which now means that T is a type, while in the proposed syntax it means that T is a constant having type int or ref

What you will say? In particular, I find `==values` syntax natural, but ugly - do you have better ideas? 

Another important drawback of this proposal is incompatible treatment of `[T:typ]` syntax, do you have any ideas about it? My best idea is to make transition in two steps - first add `==values` syntax and force every library to switch to it, and only then change the meaning of this syntax.

Also, existing syntax may be extended to give `proc f(int)` meaning of `proc f(_:int)` while we effectively steal this syntax for type parameter stick to 'int'

PS: This is just RFC, not proposal. It can pave the way to better, more uniform parameter syntax.

**Comment by andreaferretti** [comment]
I find the examples not very readable. Could you add, for each one, the current version along with how it will change in the proposed syntax?

In particular I am not sure already of the first example: `proc f[int32]( x:int; int64)`. I guess that this should replace `proc f[T: int32](x: int, U: typedesc[int64])`, but the example is so contrived, having both a type parameter constrained to only be int32 **and** a typedesc parameter constrained to only be int64 that I am not really sure

**Comment by Bulat-Ziganshin** [comment]
Yeah, I tried to balance between simplicity, completeness and amount of examples. It seems that I should add more examples, gradually introducing more advanced features, with translation to the current syntax. I'm going to make updates...

**Comment by Bennyelg** [comment]
== for assignment is pretty confusing dont you think?

**Comment by pqflx3** [comment]
What does `== values` do that a type class / range does do in the type parameter?

```nim
import typetraits
import strformat

type
  ThreeOrFour = range[3..4]
  Int32orInt64 = int32 | int64
  TypeInt32orInt64 = typedesc[int32 | int64]

proc foo(a : ThreeOrFour = 3): int = return a
proc bar[ T : Int32orInt64 = int32] ( t : T = 1): Natural =  return t + 1
proc baz( u : TypeInt32orInt64 = int32): string =
   &"{u.type}: {u.high}"

when isMainModule:
  echo foo 4
  echo bar[int64](int64(2))
  echo baz(), baz(int64)
```
Output:
```
4
3
int32: 2147483647 int64: 9223372036854775807
```

**Comment by andreaferretti** [comment]
@Bulat-Ziganshin Thank you for expanding/clarifying. Personally, I find the old syntax more readable in most examples, but it might be just that I am used to it.

**Comment by Bulat-Ziganshin** [comment]
> == for assignment is pretty confusing don't you think?

@Bennyelg but it's not an assignment, it's "equal to". In the current syntax, we write '[T: int]' or '[T: typedesc[int])' to specify that T should be 'int' and nothing else. My syntax for that 'T==int' - it's ugly, but I think it's NOT confusing, unlike two existing ones! And yeah, I'm looking for something better - the RFC is open for improvements (or just another design fixing the problems I listed).

**Comment by Bulat-Ziganshin** [comment]
> What does == values do that a type class / range doesn't do in the type parameter?

@pqflx3 : 
- it doesn't provide any new features for type parameters
- it proposes uniform and imho more natural syntax: 'T: int' means 'T has type int' in both parts of parameter list, while 'T== int' always stands for 'T itself is type int'
- it provides new feature of overloading by constant values as well as simplifies overloading by type:

```Nim
proc parse(x: string; int) = ...
proc parse(x: string; T==seq) = ...

proc fib(const 0|1) = 1
proc fib(const N: int) = fib(N-1) + fib(N-2)
```

**Comment by Quelklef** [comment]
I strongly disagree with using `==` for typeclasses. It goes against the principles you referenced; specifically, it violates "Be consistent: Don’t make similar things different, including in spelling, behavior, or capability. Don’t make different things appear similar when they have different behavior or capability.".

`==` means "is equal to". What we want to convey is "is a" or "is one of". I think `X of A|B` or `X in A|B` (preferred) would be much better.

**Comment by Quelklef** [comment]
I also disagree with moving `var` and `const` to the left, for two reasons. (I really like `const` replacing `static[]`, though!).

Reason 1:

Currently, Nim follows the rule "the type comes after the colon". If you see an identifier followed by a colon, you know that the identifiers type, *in its whole*, is after that colon. Moving `var` and `const` to the left violate this.

Reason 2:

If `var` and `const` are moved to the left of the identifier, this seems to imply that they share semantics with `var` and `const` in variable declarations and definitions. While this is true for `const`, it is *not* true for `var`. A `var` parameter does not simply mean "this parameter is mutable", it means something else entirely but implies that the parameter is mutable

**Comment by Bulat-Ziganshin** [comment]
> == means "is equal to". What we want to convey is "is a" or "is one of". I think X of A|B or X in A|B would be much better.

@Quelklef Well, '==' in my proposal may be used to specify exactly one value. But in practice, if parameter may have exactly one value, we don't need to name it at all and probably in most cases, the single value name will be given without name at all.

So, '==' will be usually used with more than one value, which makes '==' symbol confusing. of/in/is may be a better choice: T of int|ref, T in int|ref, T is int|ref.

OTOH, for types, we may have just a single word for concept representing multiple types: T of ref, T in ref, T is ref.

For me, 'is' looks better than of/in for the second case, and similar in the first one.

Although I thought about some symbols, sort of "@" or "(...)". One drawback of my proposal is that combining '==' and '=' parts is a bit ugly, but with is/of/in it looks better: `T is int|ref = int` vs current syntax: `[T: int|ref = int]` or `(T: typedesc[int|ref] = int)`.

**Comment by Quelklef** [comment]
> Well, '==' in my proposal may be used to specify exactly one value.

Eh, personally I read `f[T: int]` as "`T` is an item of the singleton `{int}`"

**Comment by Quelklef** [comment]
... I mean, sure, why not?

**Comment by Bulat-Ziganshin** [comment]
>Overloading by constant value - Not needed

@mratsim I agree that we don't need to introduce this feature until we need to put fib[0], fib[1] and fib[N] definitions into separate places (and probably separate modules). C++ added this feature because it didn't have static if.


> If var and const are moved to the left of the identifier, this seems to imply that they share semantics with var and const in variable declarations and definitions. While this is true for const, it is not true for var. 

@Quelklef I never thought about it, since it doesn't mentioned in the manual. That said, this part of proposal is independent. We may choose to allow var/const/type on the left, on the right, or both places, or allow 'const' but not 'var' - it can be done independently of the rest of proposal.

**Comment by Quelklef** [comment]
> @Quelklef I never thought about it, since it doesn't mentioned in the manual. That said, this part of proposal is independent. We may choose to allow var/const/type on the left, on the right, or both places, or allow 'const' but not 'var' - it can be done independently of the rest of proposal.

Of course `var` should be allowed. It's already a feature.

My vote is for allowing them on the right only. I am against allowing for either syntax to be used interchangeably, because they seem like the should do different things. And perhaps we'll want them to do different things; I, for one, would love it if `f(var x: T) = body` meant `f(x: T) = var x = x; body`. (Plus, this would be consistent with the semantics of `var x: T` in declarations).

**Comment by Bulat-Ziganshin** [comment]
@Quelklef of course I mean on which side to allow 'var' :)

I collect answers and will make v2 of proposal. Since var is already on the right, and no one supported my personal preference of having var/type/const on the left side, I will put them on the right. My own preference will be provided as optional sub-proposal.

>Seems related to #7517 by @timotheecour.

Yes, definitely! It also related to other generic-related issues discussed here.

> Like Andrea, I have trouble parsing the whole thing, especially how the :, == translate to real use.

Yeah, this proposal is my complete disaster. While proposing very little changes, I made it on first attempt over-complicated, and on the second one, over-long. I'm sorry.

@mratsim please edit your post - it seems that parser eated [...] in code samples. You may use backticks around code samples to prevent that.

**Comment by Quelklef** [comment]
Not to be mean, but I also found this proposal kind of difficult to read. Version two sounds like a good idea; if you like, I could read over it and give a review before you make a new github issue. If you're interested, DM me on gitter (@Quelklef; I'm in the Nim chat)

**Comment by Bulat-Ziganshin** [comment]
@Quelklef  even I hardly can read it, despite I perfectly know that it proposes. This reminds me of last year situation when I failed to parse the paper, reinvented the method described there on my own, and still barely can understand the paper :)
