### ISSUE TITLE
nimpretty feature requests

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8458]
- [x]  `nimpretty --margin=0` # means infinity (ie no line wrap); can pass any integer, eg 80, 120...
**EDIT** this now exists: `nimpretty --maxLineLen:N`
- [ ] `nimpretty --fixcase=true` # when true, changes case of identifiers to same case as symbol declaration, eg: `splitlines` will become `splitLines` because symbol declared as `splitLines`
- [ ] `nimpretty --safe` # this one runs a subset of all transformations run by nimpretty that is known to work (eg, not break code)
- [ ] use a git hook to give a warning when PR would generate a style violation; so PR author can fix it before it gets in hands of reviewer, see [1]; this requires `git nimpretty` to only consider style violations local to PR diff. Note that it should be a warning, not an error (eg when a PR has to move a block of code and it may be undesirable to nimpretty it for whatever reason, or if running nimpretty would somehow result in broken code due to a bug in nimpretty)
- [x] `nimpretty --tabwidth=2` # when set, changes tab width to requested value (useful when some source code uses tab width inconsistent with other code in a project)
**EDIT** this now exists: `nimpretty --indent:N`

## links
* [1] http://kaskavalci.com/using-git-hooks-to-format-your-code/
* https://stackoverflow.com/questions/43974371/run-git-clang-format-on-series-of-git-commits
* https://clang.llvm.org/docs/ClangFormatStyleOptions.html
* https://engineering.mongodb.com/post/succeeding-with-clangformat-part-1-pitfalls-and-planning/

**Comment by Araq** [comment]
Instead of ``--tabwidth`` you can fix the source file so that the first indentation uses the desired number of spaces. ``--margin`` is a bit against nimpretty's "zero configuration" philophy too. ``--fixcase`` will be though to support. ;-)

**Comment by FedericoCeratto** [comment]
fixcase should instead support user-configurable styles (snake_case, camelCase, ...) at file and whole-project granularity

**Comment by timotheecour** [comment]
(moved from top-post for easy individual reference wo creating a new issue)
- [ ] `nimpretty --difflines:commit` which is the exact analog of `git clang-format` which only applies formatting on lines that appear in the diff wrt `commit` This is very useful to apply formatting changes without creating un-necessary large diffs
        (especially when `nimpretty`  changes its output over time; and it will)

**Comment by kuon** [comment]
Would it be possible to add support for stdin to stdout to nimpretty?

`nimpretty -` should read from stdin and write to stdout.

**Comment by pb-cdunn** [comment]
Also, **nimpretty** makes a mess of `json %*` macro code.

**Comment by narimiran** [comment]
> Also, nimpretty makes a mess of json %* macro code.

Can you please post an example (as a separate issue, ideally), because I was not able to reproduce the mess you mention?

**Comment by pb-cdunn** [comment]
@narimiran , see #11937.

**Comment by polypus74** [comment]
> Would it be possible to add support for stdin to stdout to nimpretty?

> `nimpretty -` should read from stdin and write to stdout.

To compound this problem shell process substitution is broken because nimpretty renames input filepaths not ending in ".nim": `nimpretty --out:/dev/stdout <(cat)`

And complains cannot open /dev/fd/45.nim

Or `/dev/stdin -> /dev/stdin.nim`, for that matter.

**Comment by FedericoCeratto** [comment]
[nimfmt](https://github.com/FedericoCeratto/nimfmt) now implements a feature to fix casing with user-configurable parameters

**Comment by Clyybber** [comment]
nimpretty's `--maxLineLen` option addresses the first point of this Issue (I updated the issue accordingly)

**Comment by dom96** [comment]
I found this article which looks very informative on this topic http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/

**Comment by noahehall** [comment]
+1 for this feature request

if we could also add: `nimpretty someDir` to recursivelly prettify all `*.nim` files at any depth

**Comment by Araq** [comment]
Not planned.
