### ISSUE TITLE
{.nimcall.} convention won't avoid the creation of closures

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#8473]
Code
```nim
proc a(v: int) =
  proc b {.nimcall.} = echo v
  b()
a(5)
```
Compiles without a complaint. The opposite would add type safety against the creation of closures.
***
```nim
>nim -v
Nim Compiler Version 0.18.1 [Linux: i386]
Compiled at 2018-07-14
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 9b98add6c714474e261df1a0a17819282dfd1975
active boot switches: -d:release
```

**Comment by zielmicha** [comment]
Probably related to #5688

**Comment by zah** [comment]
Should be a simple check in `lambalifting.nim`.

**Comment by stefantalpalaru** [comment]
The "nimcall" pragma seems to be erased at some point. If you replace it with "fastcall", you get the proper error message:

```text
closure.nim(2, 30) Error: illegal capture 'v' because 'b' has the calling convention: <fastcall> 
```

**Comment by bung87** [comment]
https://play.nim-lang.org/#ix=2tgN should be closed

**Comment by Clyybber** [comment]
@bung87 But it should *not* compile.
