### ISSUE TITLE
[endb] miscellaneous issues

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8478]
## major issues
- [ ] [endb] `nim --debugger:endb`: `eval 1+2` doesn't do anything #8454
- [ ]  `g` (globals) doesn't work, but `l` (locals) works:
eg, can be see on test case of https://github.com/nim-lang/Nim/issues/8454, 
```
>b 10
*** endb| >>l
*** endb| Frame (2 slots):
a = 10
b = 0x10c625048[1, 2, 3]
*** endb| >>g
*** endb| Globals:
```

## minor issues
- [ ] `control + D` should just quit endb (as in gdb, lldb); instead it prints a ginormous stacktrace
(workaround: `q`)

**Comment by Araq** [comment]
ENDB is dead, we try to make GDB a pleasent experience. :-)

**Comment by dom96** [comment]
Since endb is dead I think we can close this.
