### ISSUE TITLE
Cannot assign hex literals (where the leftmost bit is set) to a uint

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8480]
(unless if we add the literal suffix)

```nim
let
  x: uint32 = 0x80000000     # fails
  y: uint32 = 0x80000000'u32 # works
```

This may or may not be a bug, needs clarification.

**Comment by Araq** [comment]
It's not a bug. Integer literals have the type ``int`` and 0x80... is negative, can't put a negative number into an ``uint32``. Hex notation is inherently flawed IMO and a legacy.
