### ISSUE TITLE
`XDG_CONFIG_DIR` env var ignored (prevents disabling ~/.config/nim.cfg for 1 process)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8491]
I tried ignoring what's in my `~/.config/nim.cfg` to run test suite locally (which would otherwise fail because of things like `--hint[source]=on` which affect expected outputs) via
```
XDG_CONFIG_DIR=$HOME/config_alt/ ./koch tests
```
however, it was still reading ~/.config/nim.cfg as can be seen via:

```
XDG_CONFIG_DIR=$HOME/config_alt/ nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r '--hint[Conf]=on' -f test.nim
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/timn/nim.cfg' [Conf]
```

that's odd because `getConfigDir` should read `XDG_CONFIG_DIR ` (I'm on OSX):
```
proc getConfigDir*(): string {.rtl, extern: "nos$1",
    tags: [ReadEnvEffect, ReadIOEffect].} =
    when defined(windows): return string(getEnv("APPDATA")) & "\\"
    elif getEnv("XDG_CONFIG_DIR"): return string(getEnv("XDG_CONFIG_DIR")) & "/"
    else: return string(getEnv("HOME")) & "/.config/"
```

NOTE: if I redefine HOME instead (eg via `HOME=$HOME/config_alt/`) this causes other issues, eg:
```
HOME=$HOME/config_alt/ nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r '--hint[Conf]=on' test.nim

Error: getAppFilename failed. (Error was: Unable to read /Users/timothee/config_alt//.choosenim/current. (Error was: No installation has been chosen. (File missing: /Users/timothee/config_alt//.choosenim/current)))
```

Note: simply renaming temporarily `~/.config/nim.cfg` is not a viable option, as other processes might depend on it while the cmd running via over-ridden `XDG_CONFIG_DIR` is running (eg `XDG_CONFIG_DIR=$HOME/config_alt/ ./koch tests` which takes time)

**Comment by Araq** [comment]
And where do we claim to support ``XDG_CONFIG_DIR``? Maybe the OS shouldn't throw a never ending clusterfuck of "conventions" that "good" software must follow at application developers.

**Comment by dom96** [comment]
I guess the problem is that ``nim c -r`` doesn't pass the env var to your executable?

**Comment by Araq** [comment]
The compiler's documentation does not mention XDB_CONFIG_DIR.

**Comment by timotheecour** [comment]
as mentioned by @kaushalmodi in another issue (https://github.com/nim-lang/Nim/issues/8661#issuecomment-413631993), the root cause is that we were using the wrong env var `XDG_CONFIG_DIR`; it should've been `XDG_CONFIG_HOME` ; this PR https://github.com/nim-lang/Nim/pull/8662 will fix it!
