### ISSUE TITLE
String allocations do not result in warnings with --gc:none

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#8497]
Nim commit d5c9255cab9c111f8fa930e4cd42d6671877bd9d

There are no warnings produced by Nim when compiling this snippet with `--gc:none`, even though both `newString` and `echo` allocate GCed memory here (`echo` implicitly calls `$` which allocates).

```nim
proc mayAllocate() =
  discard newString(10)
  echo 123

mayAllocate()
```

**Comment by timotheecour** [comment]
related to https://github.com/nim-lang/Nim/issues/8373 but not sure if it's a duplicate

**Comment by endragor** [comment]
It's just the commit where I reproduced the issue. I add it to every issue I file as a habit. It serves as a reference point for those who would later be looking into the issue.

**Comment by dom96** [comment]
Duplicate of #8373
