### ISSUE TITLE
Effect system reports that alloc may raise with --gc:none

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#8498]
Nim d5c9255cab9c111f8fa930e4cd42d6671877bd9d

This code doesn't compile with `--gc:none`:
```nim
proc mayRaiseApparently() {.raises: [].} =
  dealloc(alloc(10))

mayRaiseApparently()
```

The problem is that `alloc` may call user-defined `outOfMemHook`, which can potentially raise, so technically this is expected. However, with `--gc:none` it's a good idea to put `{.raises: [].}` everywhere to ensure nothing raises an exception - exceptions use GCed memory, and they can screw things up when you deal with manual memory management. The fact that effect system thinks `alloc` may raise in `--gc:none` forces you to add a lot of `try/except` in `{.raises: [].}` procedures, which clutters code and negatively impacts performance.

A simple solution is to define the `outOfMemHook` callback with `{.raises: [].}` in no-GC mode.

**Comment by Araq** [comment]
Now works with ``--gc:none``.
