### ISSUE TITLE
[request] Varargs forms of and/xor/or

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8503]
Continuing on something I brought up in here, https://github.com/nim-lang/Nim/issues/8487#issuecomment-409412788 although the context was bitwise ops and not booleans in general.

Lengthy chains of boolean expressions such `a and b and c and d and e ...` can be more simply represented in languages like lisp as `(and a b c d e ...)`

Prefix notation in Nim would allow us to emulate this, but there's a problem:
```nim
var
  x = `and`(true, true)       # works
  y = `and`(true, true, true) # fails
```
It only works for two arguments! And personally, I'm not too interested in using prefix notation for just matters of two bools.

Adding varargs forms of `or`/`xor`/`and` could allow repeated uses to be collapsed, e.g.
```nim
var z = (someBoolExpression1 and
         someBoolExpression2 and
         someBoolExpression3 and
         someBoolExpression4 and
         # ...
```
to:
```nim
var z = and(someBoolExpression1,
            someBoolExpression2,
            someBoolExpression3,
            someBoolExpression4,
            # ...
```
which I personally feel is more elegant.

Would like to know your thoughts.

**Comment by Araq** [comment]
This can easily be added without change the language if you can live with the backticks for prefix notation: `` `and`(a, b, c) ``

I like the idea but IMO it doesn't come up often enough and ``a and b and c`` is readable enough.

**Comment by mratsim** [comment]
You can just implement `fold` for varargs. Works with `and`, `or`, `+`, `&`, anything.

**Comment by awr1** [comment]
IMO backtick prefix notation is fine. Either way (with or without them) I would personally find a few use cases for a varargs form of the bool operators somewhere. I don't know how often the backtick notation used by nim users though, so others might find it ugly.

@mratsim is `foldl`/`foldr` not implemented for varargs?

**Comment by mratsim** [comment]
It might work, it takes an untyped parameter so i think it works with seq, array, openarray and varargs:

https://nim-lang.org/docs/sequtils.html#foldl.t,untyped,untyped

**Comment by skilchen** [comment]
Using `foldl` (if it worked at all, which i don't think it does) you would loose the short-circuiting behavior of `and` and `or` but short-circuiting is also the key feature you loose if you implement `and`/`or` as prefix procedures on vararg[bool]:
```nim
proc `and`*(conds: varargs[bool]): bool =
  for cond in conds:
    if not cond:
      return false
  return true

proc t(): bool =
  echo "hello"
  result = true
  
proc f(): bool =
  echo "world"
  result = false
  
echo `and`(2 > 3, 1 == 1, 2 == 2, 3 == 4, t(), f())  
```
which produces:
```
hello
world
false
```
You would need to write a macro... Something that i am still unable to do.

**Comment by skilchen** [comment]
Mostly to demonstrate how bad I am at writing macros, this is my result in attempting to write short-circuiting ` and` and `or` for varargs:
```nim
import macros
import strutils

macro `and`*(conds: varargs[untyped]): untyped =
  var r = ""
  for i, cond in conds:
    if i > 0:
      r.add(" and ")
    let s = $toStrLit(cond)
    r.add(s.splitLines[^1])
  result = parseExpr(r)
  
macro `or`*(conds: varargs[untyped]): untyped =
  var r = ""
  for i, cond in conds:
    if i > 0:
      r.add(" or ")
    let s = $toStrLit(cond)
    r.add(s.splitLines[^1])
  result = parseExpr(r)
        
proc t(): bool =
  echo "hello"
  result = true
  
proc f(): bool =
  echo "world"
  result = false

when isMainModule:
  echo `and`(f(), t())
  echo `or`(f(), t())
  echo `and`(1 < 3 and 3 != 4, t(), f())
  echo `or`(1 < 3 and 3 != 4, 1/0 > 1, 1 > 2 or 3 < 4, t(), f())
```

What would be the correct way to write something like this?

**Comment by mratsim** [comment]
Here is a short-circuiting fold alternative:

```Nim
import macros


macro staticFoldl(op: untyped, args: varargs[untyped]): untyped =

  assert args.len >= 2, "You need at least 2 params to fold over"

  result = args[0]
  for i in 1 ..< args.len:
    let arg = args[i]
    result = quote do:
      `op`(`result`, `arg`)


proc t(): bool =
  echo "hello"
  result = true

proc f(): bool =
  echo "world"
  result = false

when isMainModule:
  echo staticFoldl(`and`, f(), t())
  echo staticFoldl(`or`, f(), t())
  echo staticFoldl(`and`, 1 < 3 and 3 != 4, t(), f())
  echo staticFoldl(`or`, 1 < 3 and 3 != 4, 1/0 > 1, 1 > 2 or 3 < 4, t(), f())
```

**Comment by Araq** [comment]
Use a macro for this. No new language features required.
