### ISSUE TITLE
[RFC] Add a backend flag to override `nim c` to a different language.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#8508]
`nim c`  is the default command for compiling projects, and many users see `nim c` not as `Compile Nim to the C Language`, but `Nim Compile`. Therefore, I'd like to request a backend flag for use in config files for projects to say what language to compile to. This, of course, could still be overridden using something other than `nim c` (`nim js`) or by using the `--backend` option yourself on the CLI.

This idea has also been brought up in https://github.com/nim-lang/Nim/issues/6201 and on 8/1/2018 in the Nim IRC channel, with support in both places.

**Comment by andreaferretti** [comment]
Are you intentionally posting a duplicate? You linked the existing issue yourself

**Comment by kayabaNerve** [comment]
The existing one wasn't an RFC. If it doesn't need to be, then sorry.

**Comment by kayabaNerve** [comment]
The existing one didn't have an RFC label and I was trying to give it a more formal RFC versus generic issue. If that was an issue, I'm sorry. That said, Araq did label the existing one `Accepted RFC` 5 hours ago...

**Comment by andreaferretti** [comment]
No problem, I was just surprised: usually duplicates happen because the author cannot find the original issue... :-)
