### ISSUE TITLE
Compiler cannot parse tuple type used as a generic param

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8513]
```nim
proc test(foo: seq[tuple[int]]) = discard
```
output:
```
c:/nimtests $ nim c --run genericparse.nim
Hint: used config file 'c:\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: genericparse [Processing]
genericparse.nim(7, 29) Error: ':' or '=' expected, but got ']'
```

**Comment by hlaaftana** [comment]
The point of the `tuple[]` syntax is that you can give fields names. If you don't need the name use `(int,)` or give it a dummy name like `tuple[a: int]`. Proc types require names too but the future/sugar package has the \`->\` macro which fills them in for you. If you want `tuple[int]` implemented start a RFC about it if you want, even though the proc type version of it was mentioned in #10 7 years ago

**Comment by awr1** [comment]
Funny, I could've sworn `tuple[int]` could have worked without field names, especially as it is already possible to use tuples in an unnamed way, e.g.
```nim
var x = (1, 2, 3)
```
I guess I will close this for now.
