### ISSUE TITLE
[RFC] Consistent Pragma Syntax for Type Declarations

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8514]
Nim allows two placements for pragmas within a type declaration:
```nim
type A {.pragma.} = object
type B = object {.pragma.}
```
I realize that part of Nim's philosophy is to allow some degree of permissiveness wrt style, e.g. case insensitive identifiers, however I feel allowing both placements is not really necessary. [For instance, the section on `{.acyclic.}` in the Nim manual uses both, inexplicably. ](https://nim-lang.org/docs/manual.html#pragmas-acyclic-pragma) In fact, from my reading the Nim manual doesn't specifically tell you where you can put pragmas (apart from the BNF grammar).

Generic type restraints already don't allow things like:
```nim
proc x[T: object {.union.}](a: ref T) = discard
```
so we should not have to worry about breaking something like that. (I can't imagine why someone would need this type of functionality, anyway.)

Personally, if previous usage were not a concern, I would prefer type B. However, the most common style in Nim, looking at the compiler, Arraymancer, NLVM, Mofuw, and numerous other repos, is overwhelmingly type A, so I would suggest deprecating type B. There also seems to be cases where type B is completely unallowed, e.g.
```nim
type Cardinal = enum {.pure.}
  north, east, south, west
```
does not compile.

Ofc a change like flat-out disallowing type B will inevitably break something for someone, somewhere, but I would recommend something like a compiler warning at the very least.

Let me know your thoughts.

**Comment by BarelyMalicious** [comment]
https://github.com/nim-lang/Nim/issues/1872

**Comment by mratsim** [comment]
The shallow pragma works works on both sides:

```Nim
type Foo = object {.shallow.}
  data: seq[int]


type Bar {.shallow.} = object
  data: seq[int]
```

But the acyclic pragma only works on the right hand side if it's a ref object

```Nim
type Foo = ref object {.acyclic.}
  data: Foo


type Bar {.acyclic.} = ref object # Error invalid pragma
  data: Bar
```

But on both side if it's a object + ref object
```Nim
type
  Baz {.acyclic.} = object
    data: BazRef
  BazRef = ref Baz
```

**Comment by Araq** [comment]
``acyclic`` applies to ``object`` and your ``Bar`` is a ``ref object``, that's why. But I agree it's silly. :-)

**Comment by dom96** [comment]
Yeah, let's deprecate type B.

**Comment by awr1** [comment]
Something I noticed yesterday: `{.inheritable.}` pragma needs to be fixed, only currently works with type B format
