### ISSUE TITLE
doAssert AST expansion excessive

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8518]
not clear whether this should be considered a bug or not:

```nim
#[ 
BUG:
/Users/timothee/git_clone/nim/timn/bugs/compiler/t01_doAssert_regex_match.nim(26) t01_doAssert_regex_match
/Users/timothee/git_clone/nim/timn/bugs/compiler/t01_doAssert_regex_match.nim(22) test
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3746) raiseAssert
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2807) sysFatal
Error: unhandled exception: match(text,
  const
    pattern383604 = (states: [(kind: reEOE, cp: 191, outA: -1, outB: -1, isGreedy: false,
                            idx: 0, isCapturing: false, name: "", flags: [], min: 0,
                            max: 0, cps: (data: [], counter: 0), ranges: [],
                            shorthands: [], cc: 0), (kind: reDigit, cp: 100, outA: 0,
        outB: -1, isGreedy: false, idx: 0, isCapturing: false, name: "", flags: [], min: 0,
        max: 0, cps: (data: [], counter: 0), ranges: [], shorthands: [], cc: 0), (
        kind: reSkip, cp: 191, outA: 1, outB: -1, isGreedy: false, idx: 0,
        isCapturing: false, name: "", flags: [], min: 0, max: 0,
        cps: (data: [], counter: 0), ranges: [], shorthands: [], cc: 0)], groupsCount: 0,
                   namedGroups: (data: [], counter: 0))
  pattern383604,
      m, 0) t01_doAssert_regex_match.nim(22)  [AssertionError]
Error: execution of an external program failed: '/tmp/nim//app '

 ]#
import regex
import std/unittest

proc test()=
  let text = "a"
  var m:RegexMatch
  # let r = re"(\w\d?)+"
  let r = re"\d" # same with const

  when defined(case1):
    # ok: prints: /Users/timothee/git_clone/nim/timn/bugs/compiler/t01_doAssert_regex_match.nim(38, 20): Check failed: text.match(r, m)
    check text.match(r, m)

  when defined(case2):
    # ok: AssertionError
    doAssert text.match(r, m)

  when defined(case3):
    # BUG!
    doAssert text.match(re"\d", m)

  #NOTE: `assert` behaves same as doAssert

test()
```

in more complex examples, the AST expansion can be a lot worse, generating a huge message.

**Comment by nitely** [comment]
This is 'cause `re` is a template. Well it actually does exactly what the stacktrace shows:

```
template re(expression: string): Regex:
    const pattern = toPattern(expression)
    pattern
```

For those that don't want to read nim-regex code. Other than the odd traceback, it seems to work as expected (in this case raises assertionError).

**Comment by timotheecour** [comment]
I know, but isn't `unittest.check` behavior better? (ie not recurse the AST, just print the expression):

/Users/timothee/git_clone/nim/timn/bugs/compiler/t01_doAssert_regex_match.nim(38, 20): Check failed: text.match(r, m)

**Comment by nitely** [comment]
Sure. I was just adding information I thought it was relevant to the issue :sweat_smile:

**Comment by andreaferretti** [comment]
Check can do that because it is a macro. doAssert does not even have the opportunity to see the expression, because, as @nitely remarked, `re` is a template and so the expression that is passed is to doAssert is the whole thing printed above.

Nothing to fix here (IMO) - it makes sense to have assert and doAssert, and then build more complex systems on top of these using macros (which `check` does)

**Comment by dom96** [comment]
Not a bug.

**Comment by timotheecour** [comment]
> Check can do that because it is a macro. doAssert does not even have the opportunity to see the expression

well, I just did :-) see https://github.com/nim-lang/Nim/pull/9332/files
