### ISSUE TITLE
Problem with .isNil for string inside of macro

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#8520]
https://forum.nim-lang.org/t/4096

I am still not sure if it is a bug -- the Hlaaftana reply was not that helpful.

**Comment by dom96** [comment]
It will be removed AFAIK. But I wouldn't be surprised if we keep it for backwards compat so I guess the macro problem should be fixed.

**Comment by jangko** [comment]
duplicate of #7859? looks similar

**Comment by dom96** [comment]
Yeah, looks like it.
