### ISSUE TITLE
`Error: invalid type for const: T` prevents default initializing at compile time when T has a reference field

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8521]
```nim
proc defaultImpl[T]():T=
  var a: T
  return a

type App = object
  a: ref int

proc foo(): auto=
  let val = defaultImpl[App]()
  return val

proc test(): auto=
  when defined(case1):
    # ok
    const val = defaultImpl[ref int]()
    echo repr(val)

  when defined(case2):
    # Error: invalid type for const: App
    const val = defaultImpl[App]()

  when defined(case3):
    # ok
    let val = defaultImpl[App]()
    echo repr(val)

  when defined(case4):
    # Error: invalid type for const: App
    const val = foo()

  ## EDIT: case5 is unrelated => see https://github.com/nim-lang/Nim/issues/8733
  when defined(case5):
    # Error: cannot evaluate at compile time: val
    var val{.compileTime.} = defaultImpl[App]()
    echo repr(val)

test()
```

/cc @Araq 
This is a blocker for doing compile time reflection (and doing many things that rely on it). Any chance this could be fixed?

* it also limits https://github.com/nim-lang/Nim/pull/8490

* **EDIT** it's also inconsistent with the fact that this works:
```nim
const foo = defaultImpl[seq[seq[string]]]()
```
(`seq` and `string` are reference types)

**Comment by GULPF** [comment]
I'm very surprised that `const a: ref int = nil` compiles, although it seems like it breaks if you do anything with `a`:
```nim
const a: ref int = nil
echo a[] # C compiler complains here
```

IMO this is the expected behavior, a const of a `ref` type doesn't make any sense. Note that the limitation is specifically for const, not for compile time:
```nim
# Works fine
static:
  var a: ref int
  new(a)
  a[] = 1
  echo a[]
```

**Comment by andreaferretti** [comment]
I think this makes sense, right? You cannot have a constant reference, the actual address will be unknown until runtime. You *can* do this in the case of nil, although I am not sure how useful this is

**Comment by timotheecour** [comment]
> Note that the limitation is specifically for const, not for compile time:

when `static: var a: int` is inside a proc, it gives compile error.

**Comment by timotheecour** [comment]
> You cannot have a constant reference, the actual address will be unknown until runtime. You can do this in the case of nil, although I am not sure how useful this is

It's useful for generic programming. And yes, the value should obviously be nil, but it doesn't compile.

**Comment by Araq** [comment]
> This is a blocker for doing compile time reflection (and doing many things that rely on it). Any chance this could be fixed?

No, it makes no sense to support every type ``T`` for a ``const`` section. And it doesn't block anybody from writing good software no matter how many grandiose nouns you use to describe the issue.

**Comment by timotheecour** [comment]
the problem is when a type `T` contains a (sub-sub-...) field which has a `ref`.  That field will (currently) prevent `T` from being in const section, even if we're not dereferencing that field.

**Comment by timotheecour** [comment]
> Note that the limitation is specifically for const, not for compile time

EDIT: just added a new test case (see `case5`) with `var val{.compileTime.} = defaultImpl[App]()` ; that also fails

**Comment by timotheecour** [comment]
@GULPF you're right, case5 is unrelated, moved it to https://github.com/nim-lang/Nim/issues/8733

**Comment by Araq** [comment]
"Error: invalid type for const: App" is a good error message and works as designed. Closing.
