### ISSUE TITLE
"Ordinal Type Expected" with float ranges (implementation of rand()?)

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8530]
Just grabbed devel and compiled. Got this when I `import random`:
```
lib\pure\random.nim(131, 40) Error: ordinal type expected
```
Culprit is here:
```nim
proc rand*(r: var Rand; max: range[0.0 .. high(float)]): float {.benign.} = # <- error line
  ## Returns a random number in the range 0..max. The sequence of
  ## random number is always the same, unless `randomize` is called
  ## which initializes the random number generator with a "random"
  ## number, i.e. a tickcount.
  let x = next(r)
  when defined(JS):
    result = (float(x) / float(high(uint32))) * max
  else:
    let u = (0x3FFu64 shl 52u64) or (x shr 12u64)
    result = (cast[float](u) - 1.0) * max
```

**Comment by skilchen** [comment]
Strange. I have no such problems and the CI's surely would complain if importing random would cause any problems. Could you please show a running example exposing this error?

**Comment by GULPF** [comment]
It looks like you're using the latest stdlib with an old compiler. Float ranges where added recently.

**Comment by awr1** [comment]
Very odd.... I had literally just deleted my entire Nim folder and cloned it again just a few hours ago. Checked my PATH to make sure I didn't have another Nim compiler in there, too. After recloning it and compiling again, everything works fine.
