### ISSUE TITLE
proposal: a runnableExamples below a proc becomes part of that symbol doc; would fix #7280 and result in easier to read code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8536]
## proposal
* P1: a `runnableExamples:` block right after a symbol definition becomes part of that symbol's documentation

* P2: a `runnableExamples(module):` block becomes part of module top-level documentation. This avoids ambiguities in case we want to define other symbols before module-level documentation (also makes it easier to search for these across files on the cmd line, eg to see at a glance which modules have such top-level doc)

proposal P2 is independent from P1

benefits:
* would actually solve the pesky #7280 issue
* would allow using `import foo` inside `runnableExamples` (which is currently impossible), very useful in case a unittest requires it
* it's cleaner to have `runnableExamples` below the symbol rather than inside it: 1 less indentation level, and easier to read procs without obfuscating implementation with unittest
* allows 1-liner proc definitions, not currently possible with embedded `runnableExamples`:
```nim
proc foo2*():auto=1+1
  ## mydoc2
runnableExamples: doAssert foo2() = 2

proc foo3*():auto=1+1 ## mydoc3
runnableExamples: doAssert foo3() = 2
```
NOTE: for the case of foo3, `mydoc3` isn't currently being output, but that's another orthogonal bug.

## no breaking change
in https://github.com/nim-lang/Nim/issues/7280#issuecomment-403159800 @Araq said:

> well it [runnableExamples ] already works as a top level statement and is then part of the module's documentation.

Turns out this isn't true: `runnableExamples` is being run when running `nim doc` but the **code isn't output in the html**:

```nim
runnableExamples:
  doAssert true

proc foo*()=
  ## mydoc
  discard
runnableExamples:
  doAssert 1==1
```

`nim doc bugs/doc/t02_runnableExamples_toplevel.nim`

generates:

![image](https://user-images.githubusercontent.com/2194784/43681664-4c86f960-980f-11e8-869a-81a731cdb839.png)

**This is actually good news**: it means P1 is not a breaking change

**Comment by Araq** [comment]
> it's cleaner to have runnableExamples below the symbol rather than inside it: 1 less indentation level, and easier to read procs without obfuscating implementation with unittest

No, it's not and would be yet another new concept/feature inconsistent withthe rest of Nim. Documentation comments come after the proc header in Nim!

**Comment by timotheecour** [comment]
@araq in https://github.com/nim-lang/Nim/issues/7280#issuecomment-403125255 you mentioned:

> I agree with GULPF, this looks reasonable to support. However, it also means that runnableExamples can do what any other template in Nim cannot.

so if we ever want to fix https://github.com/nim-lang/Nim/issues/7280 , looks like we'd anyway need to introduce a concept inconsistent with the rest of Nim.

What is your plan to address #7280 ? 

with my proposal, #7280 would be addressed, and import statements would become feasible in `runnableExamples` blocks, a useful feature for unittests.
