### ISSUE TITLE
Compiler SIGSEGV crash with closure on first build

### ISSUE THREAD

**Issue by michael72** [nim-lang/Nim#8538]
Because I had some trouble with closure iterator in [zero_functional](https://github.com/zero-functional/zero-functional) I created a [test repository ](https://github.com/michael72/nim-compile-crash).

So when cloning the repo and building it with nim everything is fine.
Running the build with a "clean" nim - so to say a nim that is used for the first time - the build crashes with SIGSEGV.
This is what actually happens when using travis-ci here - nim sources are checked out, compiled and then my source code is compiled with the nim compiler.

The nim code leading to the bug is located [here](https://github.com/michael72/nim-compile-crash/edit/master/closure_iterator.nim)
A failed build log is [here](https://travis-ci.org/michael72/nim-compile-crash/builds/412241873)

I could maybe help, but I don't really know how to debug the nim compiler

**Comment by BarelyMalicious** [comment]
@michael72 Compile nim compiler in debug mode (Remove `-d:release` here (or instead build using `koch`)) https://github.com/michael72/nim-compile-crash/blob/master/.travis.yml#L11 and then re-run Travis. It should give a proper stack trace instead of SIGSEGV.

**Comment by michael72** [comment]
ok - see https://travis-ci.org/michael72/nim-compile-crash/builds/412246263

**Comment by BarelyMalicious** [comment]
https://github.com/michael72/nim-compile-crash/blob/master/.travis.yml#L11 `bin/nim *c* compiler/nim.nim` (you deleted the `c` as well)

**Comment by BarelyMalicious** [comment]
I ran it and these are the logs https://travis-ci.org/BarelyMalicious/nim-compile-crash/builds/412247515

**Comment by BarelyMalicious** [comment]
@michael72 Well looks like it does not crash when nim is built using `koch` 
  
https://travis-ci.org/BarelyMalicious/nim-compile-crash/builds/412249117 
  
https://github.com/BarelyMalicious/nim-compile-crash/blob/test/.travis.yml#L11

**Comment by michael72** [comment]
OK - that's great!
I'll try to investigate a little what is going on here (although the code looks a bit tough) - otherwise I can use `koch`

**Comment by michael72** [comment]
OK - gonna close this one as `seq` initialization is now done automatically using the correct compiler (which was the actual issue here)
