### ISSUE TITLE
[TODO] `nim --run foo.nim arguments...` doesn't handle quoting / escaping arguments correctly

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8553]
```nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/compiler/t08_run_escape_args.nim "foo" bar "foo bar" 'foo"bar'
```
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file

bugs/compiler/t08_run_escape_args.nim:
echo "ok1"

not sure if related to https://github.com/nim-lang/Nim/issues/6818 but in case it is, this [comment](https://github.com/nim-lang/Nim/issues/6818#issuecomment-410452497)
> Because the bugs were fixed, as far as I could tell

would become untrue

**Comment by Araq** [comment]
This has been fixed. Reopen if it's still an issue.

**Comment by timotheecour** [comment]
@Araq I don't have sufficient permissions to reopen; could you reopen? issue still there as of now (e63c66b8104225cefe0413471410ef4c072f9954)

**Comment by timotheecour** [comment]
i fixed it here: https://github.com/nim-lang/Nim/pull/10291
