### ISSUE TITLE
`{.line: ("FAKEFILE",0, 0).}:` doesn't work on windows; works on posix (file reset to `cwd`\FAKEFILE instead of FAKEFILE)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8557]
in https://github.com/nim-lang/Nim/pull/8555 

setting `{.line: ("FAKEFILE",0, 0).}:` resets the file to "FAKEFILE" on posix; but on windows it resets it to `C:\projects\nim\FAKEFILE`  as can be seen in failures in appveyor (but not travis)

setting `{.line: ("/FAKEFILE",0, 0).}:` resets the file to "/FAKEFILE" on posix; but on windows it resets it to `C:\FAKEFILE`  as can be seen in failures in appveyor (but not travis)
definitely a bug on windows

**Comment by nc-x** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/10154 (most probably). Can be closed.
