### ISSUE TITLE
[CI] CI jobs shouldn't rerun automatically unless triggered via PR close/reopen or PR push to reduce resource consumption / queuing time

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8560]
this PR https://github.com/nim-lang/Nim/pull/8555 was failing on appveyor(windows), I didn't do anything to it (no PR close/reopen, no push), yet appveyor somehow decided to restart running the job.
this wastes resources and slows down running CI for other PR's that must wait in the queue.

we should not run CI unless triggered via PR close/reopen or PR push

**Comment by Araq** [comment]
Whatever, work on it or not but this is an issue tracker for the Nim programming language, not your personal Todo list.
