### ISSUE TITLE
Regression in mapIt for enums

### ISSUE THREAD

**Issue by coffeepots** [nim-lang/Nim#8566]
The commit https://github.com/nim-lang/Nim/commit/ba5e2d6fcb4d1dd5fde523076dafeed77360dba5 causes a regression in the following code:

```
proc enumValues(E: typedesc[enum]): string =
  result = mapIt(E, $it).join(", ")
               # ^ Error here
```
Raising `'typedesc' metatype is not valid here; typed '=' instead of ':'?`

More specifically, this manifests within the `nim-chronicles` library here: https://github.com/status-im/nim-chronicles/blob/master/chronicles/options.nim#L106

**Comment by LemonBoy** [comment]
Thanks for spotting this edge case, it should be fixed now :)
