### ISSUE TITLE
[typetraits] `echo A[B]` prints differently depending on unrelated code

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8569]
```nim
import typetraits

type
  C[T] = object

type MyInt = int
type C2=C

when defined(case1):
  echo C2[int]   # C2[system.int]
  echo C2[MyInt] # C2[system.int]

when defined(case2):
  echo C2[MyInt]  # C2[t01_resolveTypeName2.MyInt]
  echo C2[int]    # C2[t01_resolveTypeName2.MyInt]

# EDIT: using `name` instead of `$` doesn't make a difference, unlike test case for related issue https://github.com/nim-lang/Nim/issues/7976#issuecomment-395246665
when defined(case3):
  echo C2[MyInt].name #C2[t01_resolveTypeName2.MyInt]
  echo C2[int].name #C2[t01_resolveTypeName2.MyInt]

when defined(case4):
  echo C2[int].name #C2[system.int]
  echo C2[MyInt].name #C2[system.int]
```

NOTE: related to, but probably not identical, to https://github.com/nim-lang/Nim/issues/8570, see note there

**Comment by andreaferretti** [comment]
(you don't have to prefix all issues with BUG, that's kind of the point of an issue tracker :-D)

**Comment by timotheecour** [comment]
Note: https://github.com/nim-lang/Nim/issues/7976 seems super related to https://github.com/nim-lang/Nim/issues/7976 ; I'm hesitant to call it an actual duplicate because:
* this issue is for generics, whereas other one for tuple
* in this issue, using `name` vs `$` makes no difference, but for other one it makes the bug disappear

**Comment by jangko** [comment]
looks like both of this issue and #7976  have something in common:
* #7976 happened because of generic proc instantiation _cache_ mechanism.
* this bug occurs because of generic type instantiation _cache_ mechanism.

and I think it might also plaguing `macros.getTypeXXX` families.

**Comment by mratsim** [comment]
I find it quite hard to just write `getType` macro code, see https://github.com/nim-lang/Nim/issues/7719, making it robust is very hard, see for example this stress test: https://github.com/nim-lang/Nim/pull/8531#issuecomment-410436458.
