### ISSUE TITLE
[git] rename git branch `devel` to `master` and `master` to `stable`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8576]
was discussed briefly in https://forum.nim-lang.org/t/4091#25452 and @araq seemed in favor so putting it here so it doesn't get forgotten

copying from that post:

In vast majority of git projects, `master` means branch with latest developments, but in Nim, `master` points to latest dot release IIUC, and `devel` is the branch with latest developments.

## [EDIT] changes in code + docs would also need to happen right after
non exhaustive list:
- [ ] `let commit = getConfigVar(d.conf, "git.commit", "master")`
- [ ] `exec("git checkout -f master")`
- [ ] `docker pull nimlang/nim:devel`
- [ ] `git checkout devel`

## SCRATCH BELOW

thanks @dm1try  for correcting me on this point
~~Here's an example where this non-standard convention gets in the way when deleting a feature branch after it was merged (via a PR) to `devel`, git complains (with a warning) because it expects HEAD to point to master, not a custom name like `devel` if we were using `master` instead of `devel`, we wouldn't have this warning~~
```
git checkout devel
git pull --ff-only
git branch -d pr_fix_7492_doAssert_bad_stacktrace_simple
warning: deleting branch 'pr_fix_7492_doAssert_bad_stacktrace_simple' that has been merged to
         'refs/remotes/rdev/pr_fix_7492_doAssert_bad_stacktrace_simple', but not yet merged to HEAD.
Deleted branch pr_fix_7492_doAssert_bad_stacktrace_simple (was 11e70d109).
```

**Comment by Araq** [comment]
Please give me a detailed list of git instructions and I'll do it. Maybe I'll test first with a dummy repo and ensure not every outstanding PR gets broken.

**Comment by dom96** [comment]
AFAIK we can just do the following:

* Create branch off `master` called `stable`.
* merge ``devel`` into ``master``.
  * Do so periodically while PRs for ``devel`` exist
  * Tell people to make PRs on top of ``master``
  * at some point decline PRs on top of ``devel``

**Comment by timotheecour** [comment]
I suggest doing it in 2 steps insead of 1 step due to fact that `master` already has a different meaning, and the fact that code (and docs) relies on these hardcoded names:

* step 1 (could happen now): rename branch `master` to `stable` and immediately delete branch `master`
* fix doc and code refs: code should now only mention `stable` and `devel`
* wait for 1 month, fixing any issues as they occur
* step 2: rename `devel` to `master` and make sure `git clone` now points to `master`
* fix doc and code refs: code should now only mention `stable` and `master`

**Comment by dm1try** [comment]
i'm just lurking here but..
the first part is true:
> In vast majority of git projects, master means branch with latest developments

at least in open-source projects on Ruby

the second part is not true:
 > git complains (with a warning) because it expects HEAD to point to master, not a custom name like devel

this complaint should be in the git warning then :) I mean the complaint in the message has nothing with "HEAD to point to master". the same message will be received when `master` will be a default branch and the next PR will be merged with squashing. 

see, `(was 11e70d109)` in the warning, [this commit](https://github.com/nim-lang/Nim/pull/8469/commits/11e70d1098f2591430b88a45d8324e4a4487c872) was provided in [PR](https://github.com/nim-lang/Nim/pull/8469)
but it was squashed and merged as [`d07d148`](https://github.com/nim-lang/Nim/commit/d07d148597f999de873867dcafc39411b49d009d), that's all the story

**Comment by timotheecour** [comment]
@dm1try thanks for your correction, edited my post

**Comment by dom96** [comment]
> step 1 (could happen now): rename branch master to stable and immediately delete branch master

Why delete it immediately?
