### ISSUE TITLE
`Error: redefinition of ` should show where previous definition is; in some cases can be super confusing

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8581]
see example here: https://github.com/nim-lang/Nim/issues/8580, which I'm rewriting here:

```nim
#[
BUG:
/Users/timothee/git_clone/nim/timn/bugs/stdlib/t01_mapIt_redefinition_of_t.nim(6, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/stdlib/t01_mapIt_redefinition_of_t.nim(9, 9) Error: redefinition of 't'
D20180808T142452
]#

import sequtils

when defined(case1):
  proc test() =
    # BUG
    let t = [1,2].mapIt(it)

test()
```

In this case it's hard to spot for users not familiar with implementation of `mapIt` where the previous definition was. 
There are similar cases

the compiler knows where previous definition was, and should just show it

**Comment by Araq** [comment]
Duplicate of https://github.com/nim-lang/Nim/issues/447. It's somewhat hard to implement as it requires minor compiler refactorings.

**Comment by timotheecour** [comment]
redefinition error messages were improved in https://github.com/nim-lang/Nim/commit/539fc5d58b77d43c19d10a3949841c26dcd2cffc
