### ISSUE TITLE
[feature] random.unpredictableSeed, from pid, threadid, time

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8588]
same as https://dlang.org/library/std/random/unpredictable_seed.html

**EDIT**
just figured that nim has this:
```nim
proc randomize*() {.benign.} =
    let now = times.getTime()
    randomize(convert(Seconds, Nanoseconds, now.toUnix) + now.nanosecond)
```
this could be improved for more randomness, as done here: https://github.com/dlang/phobos/blob/v2.081.1/std/random.d#L1549
which mixes `pid`, `threadid`, and `time`

```d
if (!seeded)
        {
            uint threadID = cast(uint) cast(void*) Thread.getThis();
            rand.seed((getpid() + threadID) ^ cast(uint) MonoTime.currTime.ticks);
            seeded = true;
        }
        rand.popFront();
        return cast(uint) (MonoTime.currTime.ticks ^ rand.front);
```

## minor
- [ ] would be good to update docs because randomize doesn't appear next to randomize(seed), and its docstring doesn't contain seed, so its easy to miss.

**Comment by timotheecour** [comment]
my simple attempt results in miserable failure, and what seems like a bug in nim number generator: https://github.com/nim-lang/Nim/issues/8589

**Comment by narimiran** [comment]
I don't see any *significant* benefit of "more randomness". Closing as rejected.
