### ISSUE TITLE
Compiler crashes when concatenating a string with `nil`

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#8592]
The following code crashes without linenumber on `Nim Compiler Version 0.18.1 [Windows: amd64]; Compiled at 2018-07-14; git hash: 332469692d5053c6c935163e196b117b6979c8e7`
```nim
proc test(): string =
  result = nil & ""
```
with
`Error: unhandled exception: false ast.nim(1606) getStrOrChar [AssertionError]`

Maybe a better error message is sufficient [here](https://github.com/nim-lang/Nim/blob/730ce53b71a207edf93abe09c14c150b9c360028/compiler/ast.nim#L1605).

**Comment by tim-st** [comment]
Yes, it was/will be changed. But this code wasn't a try to concatenate `nil` with a `string`, instead I wanted to show a situation where compiler crashes without line number. These crashes without linenumber are very bad and force the developer to search the bug on his own...

**Comment by stefanos82** [comment]
Ah yes, you are completely right. How come I have missed that? Indeed that's a very unfortunate situation for the user.

**Comment by Araq** [comment]
Now fails with 

```
Error: type mismatch: got <nil, string>
```

I know these crashes without line info are bad but they are not caused by a single reason.
