### ISSUE TITLE
[Regression] Code no longer compiles with VS2013, VS2015

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#8594]
I have traced the regression to this commit: c3d5ec8eadf3aa887f34231c2d7b5818923818d4

PR does the following checks:
```
const windowsCC89 = defined(windows) and (defined(vcc) or defined(bcc))
```
Check is incorrect without considering version of VC compiler.

I suggest reverting because VS2013 compiler was released in 2012 or 6 years ago. 

Correct change requires checking compiler version.

**Comment by Araq** [comment]
> I suggest reverting because VS2013 compiler was released in 2012 or 6 years ago.

Ok, please make it happen.

**Comment by jangko** [comment]
@cooldome, what exactly is the error messages?
