### ISSUE TITLE
Parsing ended but there was still input remaining

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8595]
90% sure this is a regression:

```nim
import times

echo(parse("2016-06-20T06:54:31.892+00:00", "yyyy-MM-dd'T'hh:mm:ss"))
```

Error:

```
Failed to parse '2016-06-20T06:54:31.892+00:00' with format 'yyyy-MM-dd'T'hh:mm:ss'. Parsing ended but there was still input remaining.
```

CC @GULPF

**Comment by GULPF** [comment]
This was an intentional change, ``parse`` no longer ignores trailing chars in the input. IMO it's correct behavior, if the input was `2016-06-20T06:54:31.892+02:00` the old behavior would give the wrong result. The fix is to use a format that matches the expected input.

**Comment by dom96** [comment]
Okay, I think the new behaviour is fine then. Let's just make sure it's documented.
