### ISSUE TITLE
tool for code coverage? lcov + `--passC:--coverage --passL:--coverage` doesn't work

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8598]
the only thing I could find was https://hookrace.net/blog/nim-code-coverage/
however instructions didn't work: /cc @def-
after `lcov --base-directory . --directory . -c -o x.info`, `x.info` ends up empty
really would love to be able to reproduce these results @def- had here(https://hookrace.net/public/coverage-minimal/cov/x.nim.gcov.html)

**Comment by timotheecour** [comment]
from my understanding, that library requires heavily modifying source code of project for which I want code coverage:
``
Add "import coverage" and the top of your sources and add "{.cov.}" to every proc.
```

hardly seems practical; how long would that manual task take for a project like nim itself?

instead, it should be automatic, and enabled by compiler via a flag `nim -cov=coverage_options foo.nim`

**Comment by samuelroy** [comment]
@timotheecour I made a working version of HookRace code coverage version through a Nimble task. It's automated and based on the unit tests in the folder `tests/`. 

You can check it out here: https://github.com/samuelroy/nim-coverage. Let me know if it works for you.

**Comment by timotheecour** [comment]
thanks! will comment directly in your repo

**Comment by Araq** [comment]
Well I consider this question solved then.

**Comment by timotheecour** [comment]
can we re-open?
* unfortunately that project seems to have hit a wall, see blocker issue here https://github.com/samuelroy/coco/issues/13
* I have a concrete idea how to address this, and may work on it when I have cycles or help with whoever wants to tackle this:
  * instrument code (analog to how nimprof does it but simpler)
  * doesn't have the issues of nimprof that I mentioned here https://github.com/nim-lang/Nim/issues/10121 since those were accuracy related; here we just care about hit/no-hit (or, as an extension, number of hits for a line of code)
I'm almost sure this will work and not be too complex to implement
