### ISSUE TITLE
`.cache/projectname` pollutes `.cache` - put in `.cache/Nim/projectname` instead

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#8599]
With the new `.cache` feature, nim places intermediary files in `.cache/projectname` - this is problematic, because nim's cache handling is broken in several ways and requires frequent clearing.. and improvement would be to have the ability to clear all `Nim` stuff in one go. This is also more in line with how other applications typically use `.cache` - in a sub-directory named after itself: `.cache/Nim/projectname`.

**Comment by timotheecour** [comment]
agreed; see also arguments provided here https://github.com/nim-lang/Nim/pull/8585#issuecomment-411809365
* The XDG_CACHE_HOME is shared by many applications.. Would it be better to have nim use $XDG_CACHE_HOME/nim/?
* More than clash, I was thinking about ease of removing nim cache files. The .cache has my browser cache too. So if I want to remove just nim cache dirs, rm -rf $XDG_CACHE_HOME/nim would work nicely.
* Also for precedence, other tools create there subdirs in the XDG_CACHE_HOME. Google Chrome, for example, creates $XDG_CACHE_HOME/google-chrome/, and Firefox creates$XDG_CACHE_HOME/mozilla/firefox/.

**Comment by Araq** [comment]
Ok, do it, I notice again more I'm the only person on this planet who dislikes this never-ending nesting of directories.

**Comment by mratsim** [comment]
But aren't you developing on Windows anyway? ;)

**Comment by kaushalmodi** [comment]
It's obvious, but let's ensure that the `nim/` (Note: I like lower case.. also consistent with other apps.. `google-chrome`, `firefox`, ..) gets added to both `~/.cache/` and `$XDG_CACHE_HOME/`.

**Comment by Araq** [comment]
> But aren't you developing on Windows anyway? ;)

I develop on Linux, OSX and Windows, believe it or not. Linux only when I have to though.

**Comment by dom96** [comment]
While we're at it, can we get Nim to check for ``nim.cfg`` in ``/etc/nim/nim.cfg`` instead of ``/etc/nim.cfg``?

**Comment by timotheecour** [comment]
and put these in ~/.config/nim/ :
nim.cfg
config.nims

maybe also `nimble` instead of ~/.nimble
