### ISSUE TITLE
deprecate python-isms like `isUpper(string)` (etc); we only need it on `char` or `Rune`, not `string`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8600]
in python, there is no concept of `char`; only of `str`:
```py
type('abc') #str
type('abc'[0]) #str
```
so in python **they need to come up with rather arbitrary** rules that operate on a whole string; this is inconsistent and leads to endless debates, see https://github.com/nim-lang/Nim/issues/7963#issuecomment-394848671
```py
'ABC  DEF'.isupper() #true even though `' '.isupper()` is false for spaces
```

Nim, being a compiled language, distinguishes bw `char` and `str`, so we don't need to provide an arbitrary answer on whether `"FOO BAR"` is considered `upper` or not; application writers can decide for these semantics on their own, using Nim stdlib primitives on `char`/`Rune`; eg: `str.allIt(it.isUpper or it == ' '` if they want

The only primitive needed here is: 
* `isUpperAscii(char)`, `isUpper(Rune)` (clear semantics)
* this should not be in stdlib: `isUpper(string)` `proc isUpper(string, skipNonAlpha)` and should be deprecated (its semantics are controversial)

## proposal
* deprecate `isUpperAscii`, `isUpper`  (+ similar things, on a case by case basis) that take a `string` input
* do not deprecate `isUpperAscii(c)` and `isUpper(Rune)`  (+ similar)

## Note
* https://github.com/nim-lang/Nim/pull/8003#issuecomment-396072952
* see also comment from @kaushalmodi https://github.com/nim-lang/Nim/pull/8003#issuecomment-396072952 in this PR #8003
* https://github.com/nim-lang/Nim/issues/7963#issuecomment-395944470 by @GULPF 
* https://github.com/nim-lang/Nim/pull/8001 was the "wrong" fix to https://github.com/nim-lang/Nim/issues/7963 ; which is why I created this issue

**Comment by timotheecour** [comment]
great to hear that's what we agreed on; but there are no currently open bugs to track this, hence this issue.
Furthermore, this issue covers other things not handled in https://github.com/nim-lang/Nim/pull/8003 (beyond just isUpper):
any function isFoo that's just result of apply test isFoo on consecutive char/Rune seems like it could go away and be replaced in user code by `str.allIt(isFoo)` or `str.byRune.allIt(isFoo)`. IIRC there are more of such functions there

**Comment by dom96** [comment]
IMO this is tracking this already https://github.com/nim-lang/Nim/pull/8003

Closing.
