### ISSUE TITLE
[WONTFIX] [error msg] errors should always point to instantiation context in nim code 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8602]
t15_emit_error_context.nim:
```nim
import t15_emit_error_context2
```

t15_emit_error_context2.nim:
```nim
{.emit: "}".}
```

```
rnim bugs/compiler/t15_emit_error_context.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/compiler/t15_emit_error_context.nim
Error: execution of an external compiler program 'clang -c  -w  -I/Users/timothee/git_clone/nim/Nim/lib -o /tmp/nim//nimcache/timn_t15_emit_error_context2.c.o /tmp/nim//nimcache/timn_t15_emit_error_context2.c' failed with exit code: 1

/tmp/nim//nimcache/timn_t15_emit_error_context2.c:24:1: error: extraneous closing brace ('}')
}
^
1 error generated.
```

error should show:
```nim
t15_emit_error_context2.nim(1,5): `emit` failed
```

in more complex cases it can be trickier to figure things out (yes I know, `timn_t15_emit_error_context2.c` is shown)

**Comment by Araq** [comment]
``.emit`` means "I am on my own", it doesn't work with nlvm, Nim's VM, Nim's JS backend. I am not sure what you're proposing here.

**Comment by timotheecour** [comment]
i was just proposing that when emit results in **compilation error** (eg as above), the error message also shows where this came from, ie:

nim c foo.nim
...
bar.nim(10,2): error in emit statement:
Error: execution of an external compiler program 'clang -c  -w  -I/Users/timothee/git_clone/nim/Nim/lib -o /tmp/nim//nimcache/timn_t15_emit_error_context2.c.o /tmp/nim//nimcache/timn_t15_emit_error_context2.c' failed with exit code: 1
/tmp/nim//nimcache/timn_t15_emit_error_context2.c:24:1: error: extraneous closing brace ('}')
```

**Comment by andreaferretti** [comment]
@timotheecour it is not obvious that the error comes from emit, is it? The Nim compilation step is finished and worked fine, the error appears later while compiling C to to machine code

**Comment by timotheecour** [comment]
* emit statement could simply add  
`// foo.nim:123: emit` before emitted code so at least looking at this file we can see where it came from

* the code that calls clang knows the c file / nim file association so could, on failure, echo out the corresponding nim file.
