### ISSUE TITLE
Incomplete types being generated in C code from ptr to unchecked array

### ISSUE THREAD

**Issue by zacharycarter** [nim-lang/Nim#8616]
In the linked repo - a datastructure is defined as such:

```nim
const ArrayDummySize* = when defined(cpu16): 10_000 else: 100_000_000
type
  DynArray* {.unchecked.}[T] = array[0..ArrayDummySize, T]
  RtArray*[T] = ptr Dynarray[T]
```

An iterator is defined for the type - 
```
iterator mitems*[T](self: var RtArray[T],maxIndex: Natural): var T {.inline.} =
  for i in 0..maxIndex:
    yield self[i]
```

This is causing the code generated for this type to be incomplete in some generated C files.
Example - https://github.com/zacharycarter/frag/tree/a608060eace6397476c2764a015ffb62e5eeceea

**Comment by zacharycarter** [comment]
@Araq - can you elaborate on why this was closed?

**Comment by Araq** [comment]
Because this issue was fixed to the best of our knowledge.
