### ISSUE TITLE
./koch doc looks for the nim binary in the wrong location

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#8618]
`./koch docs` sometimes calls `bin/nim` e.g. `bin/nim doc2 --hint[Conf]:off ... ` and sometimes looks for it in the binary path, e.g. when building manual_snippet_101.nim leading to inconsistent behavior.

**Comment by drslump** [comment]
@FedericoCeratto I believe this changes (https://github.com/nim-lang/Nim/pull/8622) should fix the issue, although I wasn't able to reproduce the problem with the latest version of the compiler.

**Comment by Araq** [comment]
This has been fixed.
