### ISSUE TITLE
streams.newStringStream silently accepts nil value

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#863]
When `streams.newStringStream` is passed a `nil` value, it [get's set as the data field](https://github.com/Araq/Nimrod/blob/devel/lib/pure/streams.nim#L233) without problem, but later calls to operate on the returned stream like `readData` fail.

I'd prefer the API to fail as soon as possible given wrong input. The question is whether this proc should return `nil` or [raise EIO](https://github.com/Araq/Nimrod/blob/devel/lib/pure/streams.nim#L15).

Most likely the same decision should be applied to [newFileStream](https://github.com/Araq/Nimrod/blob/devel/lib/pure/streams.nim#L263) as well. Then documented.

Also, would it make sense to sprinkle `assert` checking for nil values in all the other procs and document the procs will fail in release builds?

**Comment by Araq** [comment]
This program does not crash anymore:

```nim

import streams

let x = newStringStream(nil)

var buf: array[4, char]
echo x.readData(addr buf, sizeof(buf))
``` 

Closing.
