### ISSUE TITLE
Config should be in its own directory

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8653]
https://github.com/nim-lang/Nim/issues/8599#issuecomment-412138212:

Nim should check for ``nim.cfg`` (et al.) in /etc/nim/nim.cfg instead of /etc/nim.cfg.

**Comment by kaushalmodi** [comment]
The canonical place on unix systems is `~/.config/FOO/FOO.cfg`.

**Comment by kaushalmodi** [comment]
@Araq: You are not using `$XDG_CONFIG_HOME` in that commit. Looks like few people agreed with that suggestion.

**Comment by kaushalmodi** [comment]
Also, https://github.com/nim-lang/Nim/issues/8599#issuecomment-412233994 /cc @timotheecour.

**Comment by Araq** [comment]
```nim

proc getUserConfigPath(filename: string): string =
  result = joinPath(getConfigDir(), filename)
``` 

Already was there and ``os.getConfigDir`` uses ``$XDG_CONFIG_HOME``. There was nothing for me to do. And if it doesn't work, that's a different issue.

**Comment by kaushalmodi** [comment]
> And if it doesn't work, that's a different issue.

OK. Thanks. So this deserves another issue. The `"/nim/" needs to be appended in `getUserConfigPath` too it seems.

**Comment by timotheecour** [comment]
> Already was there and os.getConfigDir uses $XDG_CONFIG_HOME. There was nothing for me to do. And if it doesn't work, that's a different issue.

getConfigDir was using XDG_CONFIG_DIR, which, as pointed by @kaushalmodi , should've been `XDG_CONFIG_HOME` ; will be fixed in @kaushalmodi 's  https://github.com/nim-lang/Nim/pull/8662

**Comment by dom96** [comment]
@Araq Do we also have to fix our install scripts? Won't all the .cfg files still go to ``/etc/``?
