### ISSUE TITLE
proposal: `--unsupportedFlag=[error|warn|ignore]` to help with backward compatibility

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8672]
## motivation
* whenever I need to use an older version of nim or other tools (eg nimble), I keep running into errors because my ~/.config/nim.cfg has hints or flags that are not supported by that older version of nim.
So I have to comment these, and remember to uncomment them later; it gets worse if I have binaries or services that rely on these flags being there in the meantime.
* it also causes bugs/breakages, see: https://github.com/nitely/nim-regex/issues/18#issuecomment-413724584 and https://github.com/nim-lang/nimble/issues/520

## proposal
add `--unsupportedFlag=[error|warn|ignore]` to help with backward compatibility

it would only help starting from commit that introduces this flag, but it's still useful in the future.

**Comment by Araq** [comment]
Actually you can use ``@if <condsym> --newflag:on @end`` but it's close to impossible to know the relation between the conditional symbol and the feature... :-)

**Comment by drslump** [comment]
can't the `@if <cond>` just check against the version? That seems the easier way to ensure compatibility with multiple version of the compiler with a single `nim.cfg`.

**Comment by Araq** [comment]
What we should do, is this: Every switch/experimental feature of name ``X`` should have a corresponding ``nimHasX`` define.

**Comment by timotheecour** [comment]
why not instead `nimHas(flag: static[string])` ?

**Comment by Araq** [comment]
Because the conditional symbols mechanism exists already. Simpler to implement too.
Yes, it works in ``nim.cfg`` via ``@if symbol``.
It works in ``nims`` via ``when defined(symbol)``.

**Comment by timotheecour** [comment]
related question: https://forum.nim-lang.org/t/4081#25409 (noone answered...) in nim.cfg how to have conditional flags to depend on compiler version?

**Comment by jangko** [comment]
>What we should do, is this: Every switch/experimental feature of name X should have a corresponding nimHasX define.

This solution will cover #8644 too.

**Comment by Araq** [comment]
Well, we have ``@if`` and ``when defined`` and ``when declared`` and it's good enough and has perfect backward compat because it exists since forever.
