### ISSUE TITLE
Calling a proc with missing parameter and keyword syntax on other parameter crashes compiler

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#8683]
Tested on devel
```nim
from algorithm import SortOrder

proc insertionSort*[T](A: var openArray[T], cmp: proc (x, y: T): int = system.cmp, order: static[SortOrder]) =
  const cmpToInt = when order == SortOrder.Ascending: 1 else: -1
  var i = 1
  while i < A.len:
    var x = A[i]
    var j = i - 1
    while j >= 0 and cmp(A[j], x) == cmpToInt:
      A[j+1] = A[j]
      dec(j)
    A[j+1] = x
    inc(i)

proc insertionSort*[T](A: var openArray[T], cmp: proc (x, y: T): int = system.cmp) =
  insertionSort[T](A, cmp, SortOrder.Ascending)
  
var x = @[1,9,4,2,1]
x.insertionSort(order=SortOrder.Descending)
echo x
```
Errors:
`Error: internal error: expr(nkClosedSymChoice); unknown node kind`

I tested with `static` and without both the same error.

**Edit:**
The following shows what works, what doesn't work and what crashes:
```nim
var x = @[1,9,4,2,1]
x.insertionSort(cmp=system.cmp, order=SortOrder.Descending) # works
x.insertionSort(order=SortOrder.Descending, cmp=system.cmp) # works
x.insertionSort(cmp=system.cmp, SortOrder.Descending) # works
x.insertionSort(system.cmp, order=SortOrder.Descending) # works
x.insertionSort(system.cmp, SortOrder.Descending) # works
# works not and crashes: x.insertionSort(order=SortOrder.Descending)
# works not but crashes not: x.insertionSort(SortOrder.Descending)
x.insertionSort(cmp=system.cmp) # works
x.insertionSort(system.cmp) # works
x.insertionSort() # works
echo x
```
In my opinion all of the lines above should work. Also from what one can read [here](https://nim-lang.org/docs/tut1.html#procedures-named-arguments) and below one would assume that it works.

This also crashes with the same error when the last parameter has a default value, too:
```nim
proc insertionSort*[T](A: var openArray[T], cmp: proc (x, y: T): int = system.cmp, order = SortOrder.Ascending) =
```

**Comment by tim-st** [comment]
I found a workaround it's described [here](https://github.com/nim-lang/Nim/issues/8684#issuecomment-414074925).

**Comment by hlaaftana** [comment]
Reduced test case:

```nim
proc foo[T](bar: proc (x, y: T): int = system.cmp, baz: int) =
  discard

proc foo[T](bar: proc (x, y: T): int = system.cmp) =
  discard

foo[int](baz = 5) # compiles if you remove baz = 5 on devel, doesn't on 0.18.0
```

Note that this works without system.cmp:

```nim
proc a[T](x, y: T): int =
  discard

proc a(x, y: string): int =
  # when this proc is removed, you get internal error: getTypeDescAux(tyGenericParam)
  discard

proc foo[T](bar: proc (x, y: T): int = a, baz: int) =
  discard

proc foo[T](bar: proc (x, y: T): int = a) =
  discard

foo[int]()
```

Stack traces for both for the last example:

<details><summary>test.nim(8, 40) Error: internal error: expr(nkOpenSymChoice); unknown node kind</summary>
Traceback (most recent call last)
nim.nim(133)             nim
nim.nim(97)              handleCmdLine
main.nim(162)            mainCommand
main.nim(73)             commandCompileToC
modules.nim(124)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(103)          processTopLevelStmt
cgen.nim(1378)           myProcess
ccgstmts.nim(1152)       genStmts
ccgexprs.nim(2250)       expr
ccgcalls.nim(548)        genCall
ccgcalls.nim(187)        genPrefixCall
ccgcalls.nim(170)        genArg
cgen.nim(495)            initLocExprSingleUse
ccgexprs.nim(2368)       expr
msgs.nim(524)            internalError
msgs.nim(495)            liMessage
msgs.nim(324)            handleError
msgs.nim(314)            quit</details>

<details><summary>Error: internal error: getTypeDescAux(tyGenericParam)</summary>
Traceback (most recent call last)
nim.nim(133)             nim
nim.nim(97)              handleCmdLine
main.nim(162)            mainCommand
main.nim(73)             commandCompileToC
modules.nim(124)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(103)          processTopLevelStmt
cgen.nim(1378)           myProcess
ccgstmts.nim(1152)       genStmts
ccgexprs.nim(2250)       expr
ccgcalls.nim(548)        genCall
ccgcalls.nim(187)        genPrefixCall
ccgcalls.nim(170)        genArg
cgen.nim(495)            initLocExprSingleUse
ccgexprs.nim(2189)       expr
cgen.nim(887)            genProc
cgen.nim(850)            genProcNoForward
cgen.nim(800)            genProcPrototype
ccgtypes.nim(873)        genProcHeader
ccgtypes.nim(393)        genProcParams
ccgtypes.nim(820)        getTypeDescAux
msgs.nim(529)            internalError
msgs.nim(405)            rawMessage
msgs.nim(402)            rawMessage
msgs.nim(324)            handleError
msgs.nim(314)            quit</details>

**Comment by tim-st** [comment]
In Python it is [not allowed](https://stackoverflow.com/questions/16932825/why-cant-non-default-arguments-follow-default-arguments), in Nim it could be allowed because the signature is [clearly defined](https://nim-lang.org/docs/manual.html#overloading-resolution), but I think it would be ok do forbid non default parameters after default ones.
At least there should be a consistent way imo.

**Comment by Araq** [comment]
> Does a default-valued parameter followed by a required one make any sense?

Sure, it does. Nim supports named arguments.

**Comment by tim-st** [comment]
I have update nim to latest dev version, and the specific bug is fixed, but nim still doesnt allow` to match
`x.insertionSort(SortOrder.Descending)`
only
`x.insertionSort(order=SortOrder.Descending)` matches.

**Comment by LemonBoy** [comment]
`x.insertionSort(SortOrder.Descending)` makes no sense since the first argument is the `cmp` predicate.
