### ISSUE TITLE
[WONTFIX] [TODO] [travis] fails with 0 work being done: "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8698]
https://travis-ci.org/nim-lang/Nim/jobs/418379132

```
Worker information
hostname: b76e9485-6f27-4125-b485-c336d163d438@1.production-1-worker-org-05-packet
version: v4.0.0 https://github.com/travis-ci/worker/tree/e5cb567e10c0eefe380e81c9a2229ac8fb6a16ce
instance: f800f13 travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 862.177036ms
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by dom96** [comment]
This seems like a Travis issue?

**Comment by timotheecour** [comment]
perhaps but more likely it's an issue with our configuration:
these links indicate what we can try in this case:
https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by dom96** [comment]
I don't think so. The build you linked doesn't appear to have started, usually you get system information which is completely controlled by Travis so I see absolutely no reason why this could be our fault. Please report it on Travis' issue tracker or just assume it's a small hiccup and hope it only happens 0.01% of the time.

**Comment by timotheecour** [comment]
> The build you linked doesn't appear to have started

could we re-open? it just happened again: https://travis-ci.org/nim-lang/Nim/jobs/421327786 ; this time after a bunch of code had run; it failed after `tests/testament/tester '--nim:compiler/nim ' cat lib `

> hope it only happens 0.01% of the time

that doesn't seem to be the case

it could genuinely be a configuration param we could optimize (eg increasing a timeout)

**Comment by Araq** [comment]
We can try this:

https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
