### ISSUE TITLE
`type outType = type(10)` prints as `int literal(10)` instead of `int`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8704]
```nim
# [`type outType = type(10)` prints as `int literal(10)` instead of `int` · Issue #8704 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/8704)
import typetraits

when defined(case1):
  type outType = type(10)
when defined(case2):
  let x=10
  type outType = type(x)

doAssert int is outType
doAssert outType is int

echo outType.name # BUG: int literal(10)
echo outType # BUG: int literal(10)

echo int.name # ok: int

# BUG: int literal(10) => this one could be due to `https://github.com/nim-lang/Nim/issues/8569` (compiler reuses whatever cached type name was previously found)
echo int
```

the 1st bug (`echo outType.name` shown as `int literal(10)`) looks new
it happens with `case1`; doesn't happen with `case2` (ie only happens with litterals)

the subsequent ones could be due to https://github.com/nim-lang/Nim/issues/8569

**Comment by mratsim** [comment]
Maybe we need a `typemod` magic (for type modifier), that can catch:
  - literals
  - static
  - lent
  - var

and maybe it can be extended to parameters constraints like {call} as well.

**Comment by timotheecour** [comment]
maybe the new `typeof` @araq introduced could do that?
```nim
proc typeof*(x: untyped; mode: TypeOfMode = typeOfIter)
```

**Comment by krux02** [comment]
This is not a bug, it is a feature. The type of ``10`` is actually an integer literal that knows it's value at compile time. You could complain thet ```int literal(10)`` is an ugly name to represent this type though.

**Comment by timotheecour** [comment]
but that feature seems buggy, for example this code prints:

```nim
iterator (): int literal(10){.inline, noSideEffect, gcsafe, locks: 0.}
```
instead of:
```nim
iterator (): int {.inline, noSideEffect, gcsafe, locks: 0.}
```

```nim
iterator fun(): auto =
  var x = 12
  yield 10
  yield 20
  yield x

echo type(fun)
```
