### ISSUE TITLE
[WONTFIX] everything in sequtils returns a `seq` except 1 overload `iterator filter` (which overloads proc filter) => inconsistent

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8708]
everything in sequtils returns a `seq` (or operates on each element of a seq) except `iterator filter` [1]
(there's also `proc filter` and `filterIt`; these are consistent with sequtils as they return a seq)

`iterator filter` doesn't belong in sequtils.nim; it's one of those gotchas that gets you and needs to be deprecated.
it should be in a new cleaned up module (eg `functional.nim`) that operates lazily (instead of eagerly) and returns iterators (instead of seq), for all common operations:
filter, map, reduce, group, etc

[1] `iterator filter*[T](s: openArray[T], pred: proc(x: T): bool {.closure.}): T =`
[2] `proc filter*[T](s: openArray[T], pred: proc(x: T): bool {.closure.}): seq[T] {.inline.}`
[3] `filterIt` (returns `seq`)

**Comment by awr1** [comment]
On the topic of return types in sequtils I wonder if `map/mapIt` should be able to return an `array[]` type (instead of a seq) given an input of type `array[]`

**Comment by timotheecour** [comment]
possibly, with the advantage of avoiding GC; but shd be renamed to avoid surprising behavior when a seq is expected as output; but please open a separate issue for this and let's discuss that there (to avoid mixing different topics)

**Comment by mratsim** [comment]
@awr1, you can probably piggyback on https://github.com/nim-lang/Nim/issues/7996 and discuss maybe converting `sequtils` into `containers`.

**Comment by dom96** [comment]
> On the topic of return types in sequtils I wonder if map/mapIt should be able to return an array[] type (instead of a seq) given an input of type array[]

A size-less array isn't really used in Nim's stdlib

**Comment by dom96** [comment]
So the ``filter`` iterator shouldn't be in ``sequtils`` because it doesn't yield a ``seq[T]``? It's an iterator... iterators yield single items. There is nothing wrong with it being in ``sequtils``, we should perhaps instead define iterators for the other operations too.
