### ISSUE TITLE
`assert` should not be used in tests (instead: use doAssert, or require, expect etc from unittest)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8709]
my understanding is that for tests (including unittests in runnableExamples, isMainModule, and `tfoo.nim` for a module `foo.nim`), we should not use `assert` (which is disabled in release mode) but instead we should use one of these: doAssert, require, expect etc from unittest (which are not disabled)

for eg, sequtils uses ~60 doAssert and ~125 assert (haven't narrowed down the ones used in tests but that's a majority of those)
we can close this issue after all modules are upgraded (could be done in bulk)

having the non-preferred way in our tests will just lead to more such code being copy pasted in other locations when people add more tests; so needs to be eradicated to prevent that

**Comment by Araq** [comment]
Ok, but the tester doesn't compile with -d:release except for special tests that override the default. So there is no bug here.
