### ISSUE TITLE
`somestring[^1].unsafeAddr` doesn't work but `somestring[1].unsafeAddr` works

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8732]
```nim
let s="abc"
echo s[0].unsafeAddr
echo s[1].unsafeAddr
echo s[s.len-1].unsafeAddr
echo s[^1]
when defined(case1):
  # Error: expression has no address; maybe use 'unsafeAddr'
  echo s[^1].unsafeAddr
```

**Comment by hlaaftana** [comment]
This would work if the proposal (i dont know where it is, i think in some PRs comments) with ^^ for backwards indexes and `template [][T](val: T, i: BackwardsIndex): auto = val[val ^^ i]` was implemented

**Comment by Araq** [comment]
There is no documentation that suggests it should work.
