### ISSUE TITLE
[WONTFIX] `{.compileTime.}` var doesn't work inside proc

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8733]
```nim
var val1 {.compileTime.} = 1

when defined(case1):
  proc foo() =
    # Error: cannot evaluate at compile time: val2
    var val2 {.compileTime.} = 1
```

/cc @GULPF from your comment in https://github.com/nim-lang/Nim/issues/8521#issuecomment-414065364
> It looks like {.compileTime.} is broken inside procs

**Comment by Araq** [comment]
This is not supposed to work.

**Comment by awr1** [comment]
should we emit a special error message is `{.compileTime.}` is in a proc body?

**Comment by krux02** [comment]
You can still use const. So yes there is no need to change anything for this.

```nim
proc foo() =
  # Error: cannot evaluate at compile time: val2
  const val2 = 1
```
