### ISSUE TITLE
bugs with parentDir

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8734]
* (migrated from https://github.com/nim-lang/Nim/issues/8255):

- [ ] bug 2:
* parentDir("a/b//")==a/b is a bug
 (but parentDir("a/b/") == a is OK)

- [ ] bug 3:
echo parentDir("/")
empty, which is a bug
rdmd --eval 'std.path.dirName("/").writeln'
/
os.path.split("/")
('/', '')
Curiously, echo splitFile("/") is correct:
(dir: "/", name: "", ext: "")
shouldn't `parentDir` be implemented in terms of splitFile? or is that for efficiency optimization ? (if so, see https://github.com/nim-lang/Nim/issues/8256)

- [ ] bug 4:
echo parentDir("/a.txt")
empty, which is a bug

- [ ] bug 5
documentation says: "dir does not end in DirSep" but should say "dir does not end in DirSep" unless it's "/"

## NOTE: D and python differ for the following case:
```
D:
rdmd --eval 'std.path.dirName("/a/a/").writeln'
/a
python:
os.path.split("/a/a/")
('/a/a', '')
nim:
echo parentDir("/a/a/")
/a
```
that one should be documented

**Comment by Araq** [comment]
If empty signals "invalid path" then ``parentDir("/") == ""`` is correct as the root has no parent.

**Comment by timotheecour** [comment]
@araq could we re-open ? only bug 2 got fixed, all the others are still bugs:
* bug 4
* bug 5
* bug 3: returning empty may be sensible but it is inconsistent with splitFile

(I did have a fix for this in https://github.com/nim-lang/Nim/pull/10633 but it got closed; IIRC the only contention was on `parentDir(".")` ;  maybe we can revive that PR and address that comment, possibly with an optional arg)
