### ISSUE TITLE
[doc] `nim doc --project` creates wrong href links, eg: test3.html instead of util/test3.html

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8736]
if we workaround https://github.com/nim-lang/Nim/issues/8218 by pre-creating output dirs (eg mkdir doc/util), `nim doc --project -o:doc/ test1.nim` succeeds but the href for test3 imported module is wrong (points to test3.html instead of util/test3.html) in import list
(see test case in https://github.com/nim-lang/Nim/issues/8218#issue-338796544)

**Comment by Araq** [comment]
That has been fixed.
