### ISSUE TITLE
RFC httpcore: Make HttpCode an enum

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8751]
The ship might have sailed and/or there are probably very good reasons for it: why is HttpCode not an enum?

https://github.com/nim-lang/Nim/blob/964f1ff7a77e0cc1c73f12d02969421c36d32e1c/lib/pure/httpcore.nim#L15-L23

http://irclogs.nim-lang.org/19-09-2016.html#19:48:27

https://github.com/nim-lang/Nim/blob/964f1ff7a77e0cc1c73f12d02969421c36d32e1c/lib/pure/httpcore.nim#L49-L96

**Comment by timotheecour** [comment]
@mratsim isn't `HttpCode* = distinct range[0 .. 599] ` sufficient? still provides type safety, and easier to switch between integer <=>  HttpCode ; what's benefit of enum?

**Comment by hlaaftana** [comment]
Maybe not being an enum is useful so the client doesn't break if the server sends an unsupported error code, or just that it doesn't have to deal with having holes.

**Comment by Araq** [comment]
Yeah, I agree with @timotheecour

**Comment by dom96** [comment]
> why is HttpCode not an enum?

Extensibility. There are plenty of non-standard HTTP codes.

**Comment by mratsim** [comment]
Thank you all, closing then.
