### ISSUE TITLE
[parser] `a => counter+=1` parsed as `(a => counter) += 1`, violating the spec, and causing issues with =>

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8759]
/cc @Araq 
```nim
import macros

dumpTree:
  # violates spec: arrow like operators have lowest precedence
  a1 => counter += 2
  # ditto
  a2 => counter *= 2
  # violates spec: `^` should have higher precedence than += (regardless of `^` being right-associative)
  a3 ^= counter += 2
```

```
StmtList
  Infix
    Ident "+="
    Infix
      Ident "=>"
      Ident "a1"
      Ident "counter"
    IntLit 2
  Infix
    Ident "*="
    Infix
      Ident "=>"
      Ident "a2"
      Ident "counter"
    IntLit 2
  Infix
    Ident "^="
    Ident "a3"
    Infix
      Ident "+="
      Ident "counter"
      IntLit 2
```

## NOTE
this affects sugar.nim =>, zero-functional, and lambda PR https://github.com/nim-lang/Nim/pull/8679

## spec:
https://github.com/nim-lang/Nim/blob/devel/doc/manual.rst#L573
/Users/timothee/git_clone/nim/Nim/doc/manual.rst

**Comment by metagn** [comment]
1 here has to be 0. I would almost hope it's not a typo because it's been there since the initial implementation of arrow operators (2014).

https://github.com/nim-lang/Nim/blob/af140966ea5b58ea248459acb74bf84537deb423/compiler/lexer.nim#L976
