### ISSUE TITLE
[unidecode] Make `loadUnidecodeTable` use the path to unicode.dat on user's system by default

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8767]
The `findNimStdLib` function should be made available to the user (and not just live in nimeval.nim: from https://github.com/nim-lang/Nim/blob/964f1ff7a77e0cc1c73f12d02969421c36d32e1c/compiler/nimeval.nim#L78-L90).

Using that, the default value of the `loadUnidecodeTable` proc param can be set to `findNimStdLib() / "pure/unidecode/unidecode.dat"`.

Then user just needs to do `loadUnidecodeTable()`.

**Ref**: The snippet in [this forum answer][1] does not work as-is.

[1]: https://forum.nim-lang.org/t/4154#25866

**Comment by GULPF** [comment]
> Using that, the default value of the loadUnidecodeTable proc param can be set to findNimStdLib() / "pure/unidecode/unidecode.dat".

That only works if Nim is installed. IMO it would be better to just embeed the file by default.

**Comment by kaushalmodi** [comment]
> That only works if Nim is installed.

Hmm, that's a great point. Then should `findNimStdLib() / "pure/unidecode/unidecode.dat"` be set as default if that exists.. else leave the current default as is.

I opened this issue so that `loadUnidecodeTable` can work out-of-box.

*As a side effect, `findNimStdLib()` will be available for anyone to use.*

> IMO it would be better to just embeed the file by default.

That solution would also be good instead.

**Comment by kaushalmodi** [comment]
Counter point to:

> IMO it would be better to just embeed the file by default.

But what if the user does not want to embed the data file at compile time, and instead use the one specified by `loadUnidecodeTable` at run time?
