### ISSUE TITLE
[unidecode] Update the unidecode.bat file

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8770]
Ref: https://github.com/nim-lang/Nim/issues/8768#issuecomment-415855283

**Comment by kaushalmodi** [comment]
Once that is done, also uncomment this test. The commented test was masking this bug:

https://github.com/nim-lang/Nim/blob/964f1ff7a77e0cc1c73f12d02969421c36d32e1c/tests/stdlib/tunidecode.nim#L10

**Comment by Araq** [comment]
I remember updating it.
