### ISSUE TITLE
-d:release flag wierd behaviour

### ISSUE THREAD

**Issue by matkuki** [nim-lang/Nim#8772]
This code (test.nim):
```nim
let
    a = @[1,2,3,4,5]
try:
    if a[1 .. ^100].len() < 4:
        echo "TEST"
except:
    echo "ERROR"
```
compiled with `nim c test.nim`, works as expected and echo's `ERROR`.
But compiled with `nim c -d:release test.nim` throws a segfault:
`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

Another example:
```nim
let
    a = @[1,2,3,4,5]
try:
    echo a[300]
except:
    echo "ERROR"
```
compiled with `nim c test.nim`, works as expected and echo's `ERROR`.
But compiled with `nim c -d:release test.nim` echo's `0`

I have no idea what's going on.

Specs:
- Windows 10 x64,
- Nim Compiler Version 0.18.1 [Windows: amd64]
    Compiled at 2018-08-24
    Copyright (c) 2006-2018 by Andreas Rumpf
- VC++ 14 (Visual Studio 2017) or MinGW GCC 7.3.0

Matic

**Comment by matkuki** [comment]
@hlaaftana ,
Ahhh, so it works if you add `--rangeChecks:on`, for the first example. Thanks for the explanation!

**Comment by Araq** [comment]
We will make this code illegal by making ``IndexError`` ``quit`` in debug mode instead. You cannot recover from bugs. The spec *always* said it's illegal.

**Comment by matkuki** [comment]
@Araq 
Excellent, thanks!
