### ISSUE TITLE
please implement http put and delete in httpClient

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#8777]
- Implement HTTP `PUT` and `DELETE` methods on `httpClient` and `asyncHttpClient`.

**Comment by hlaaftana** [comment]
I don't understand, does it not work?

**Comment by juancarlospaco** [comment]
Theres no HTTP `PUT` and `DELETE` methods on `httpClient` and `asyncHttpClient`.

**Comment by hlaaftana** [comment]
There's no `put` or `delete` proc, but you still can use PUT and DELETE.

```nim
import httpclient, asyncdispatch

let client = newAsyncHttpClient()
let response = await client.request("http://httpbin.org/put", HttpPut)
```

The [HTTP method enum](https://nim-lang.org/docs/httpcore.html#HttpMethod) is in the httpcore module which httpclient exports but I guess that might be hard to find in the documentation. If you want to add put and delete alias procs to httpclient you can define them in your own code.

**Comment by juancarlospaco** [comment]
It would be nice just to have:
- `httpClient.put()`
- `httpClient.delete()`
- `asyncHttpClient.put()`
- `asyncHttpClient.delete()`

Yes I know theres workaround and hacks you can use on your own code, also some API use an HTTP header to "fake" a `PUT` with a `POST`, but even more if you say theres super easy to implement, then would be nice to have, instead of additional hacks, I am not complaining about the design or anything else, I just say would be nice to have those useful procs in.
:cat:

**Comment by huglyfe** [comment]
I'm going to take a look at this over the next few days.  Good idea.

**Comment by juancarlospaco** [comment]
I appreciate the quick response and the good work, keep it up :grey_exclamation: :smile_cat:

**Comment by juancarlospaco** [comment]
I appreciate the quick response and the good work, keep it up :grey_exclamation: :smile_cat:

**Comment by juancarlospaco** [comment]
I appreciate the quick response and the good work, keep it up :grey_exclamation: :smile_cat:

**Comment by dom96** [comment]
This should be fairly easy to solve.

Simply replicate the ``get`` and ``post`` procs, change the HTTP method that they are using and that should be all that's needed. These procedures are just simple aliases for what @hlaaftana [showed](https://github.com/nim-lang/Nim/issues/8777#issuecomment-415993486).

**Comment by juancarlospaco** [comment]
Thanks everyone for the excellent work, the improvements really make a less verbose and human code. :slightly_smiling_face:
