### ISSUE TITLE
[ospaths] cmpPaths("abc/def", "abc//def") returns !=0; should return 0

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8780]

**Comment by mratsim** [comment]
Maybe we should have a Path "distinct string" type that stores validated canonical paths.

**Comment by Araq** [comment]
Paths as a separate ``distinct string`` type make more and more sense, but let's also fix what we got.

**Comment by mratsim** [comment]
Relevant: https://irclogs.nim-lang.org/06-09-2018.html#14:17:36

**Comment by timotheecour** [comment]
@mratsim 

> Maybe we should have a Path "distinct string" type that stores validated canonical paths.

see: [WIP] [RFC] new path handling module that uses Nim's type system, using Path instead of string #8362
