### ISSUE TITLE
`nim --verboselog:/tmp/log.txt ...` to log more context when needed  while not obfuscating stdout

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8789]
## example use case 1
in  7bb93c730ea87fd2437dea1d93e889fb4a2c08f4 (show all mismatching overloads again), @Araq disabled a feature that could've improved mismatch errors in most cases (eg being less verbose) but which could cause issues in some cases (as pointed by @andreaferretti [here](https://github.com/nim-lang/Nim/issues/8200#issuecomment-416236923)

## example use case 2
`nim --hints.ExtendedContext:on` is similarly super useful in some cases but in other cases it adds too much to stdout

## example use case 3
similarly, hints.CC and hints.Processing most often add too much noise but in rare cases are useful (eg to see which file was being processed right before an error which otherwise left no trace)

**Comment by Araq** [comment]
Rejected, you might as well use ``nim c foo.nim >redirected.log``.
