### ISSUE TITLE
Code Generation Bug with Closure Iterators

### ISSUE THREAD

**Issue by Varriount** [nim-lang/Nim#879]
While working on a cartesian product iterator, I came across a codegen bug. The error and code which demonstrates the bug are located at this gist (two files) -> https://gist.github.com/Varriount/8852176

**Comment by dom96** [comment]
@Varriount The code in the gist doesn't compile: getting invalid indentation errors. Tried fixing those, but more errors keep coming.

**Comment by Araq** [comment]
Pretty sure that's been fixed by now. Feel free to reopen with proper snippet that triggers it.
