### ISSUE TITLE
"from module2 as mod import nil" doesn't work anymore

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#8790]
```
from module2 as mod import nil
```
on latest devel now gives the error:
```
Error: cannot open file: module2asmod
```
I can git-bisect if necessary.

**Comment by Clyybber** [comment]
I suppose this is the PR that introduced that regression https://github.com/nim-lang/Nim/pull/8726, will test soon.

**Comment by GULPF** [comment]
I will look into this
