### ISSUE TITLE
`import ./[options]` does not work (gives: "Error: cannot open file: ./[options]" instead of behaving like `import current_dir/[options]`)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8792]

**Comment by timotheecour** [comment]
it should be (IMO) based on orthogonality of features:
```nim
import bar/foo #ok
import ./foo #ok: foo is relative to ./

import bar/[foo] #ok
import ./[foo] # error
```

here's an example where it's useful to have:
in compiler/nim.nim:
```nim
import
  commands, lexer, condsyms, options, msgs, nversion, nimconf, ropes,
  extccomp, strutils, os, osproc, platform, main, parseopt,
  nodejs, scriptconfig, idents, modulegraphs, lineinfos
```
it's not clear which of these are in ./ (ie, compiler) vs `std/` (eg strutils)

eg, once https://github.com/nim-lang/Nim/pull/8614 (Nim now allows modules with same name in a package) is implemented, keeping that ambiguitiy is not good, and following code is better (IMO):

```nim
import
  ./[commands, lexer, condsyms, options, ... ]
  std/[strutils, os, osproc, ...]
```

**Comment by Araq** [comment]
1. Dots are ugly.
2. Orthogonality of features means you need to write ``"." / [foo, bar]`` which works.

**Comment by Clyybber** [comment]
```
./somepath
```
is standard and
```
"." / somepath
```
is much more ugly IMO.

**Comment by Araq** [comment]
There is no "standard", Nim is its own programming language.

**Comment by dom96** [comment]
So you want two ways to do the same thing? This is really unnecessary.

**Comment by timotheecour** [comment]
also this:
```
import ./foo/[bar1, bar2] # works
import ./[bar1, bar2] # error
```
