### ISSUE TITLE
`Error: undeclared field: 'foo'` should show type (+ where type is defined) (hard to guess in generic code)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8794]
probably this would be good: `getSymRepr(c.config, sym)` to show type + where it's defined.

TODO (timothee):
format this in a proper sentence:  (+ where type is defined) (hard to guess in generic code)

**Comment by mratsim** [comment]
I agree and the error message should probably be `undeclared field of routine 'foo' for type 'bar' defined at ...` due to UFCS.
