### ISSUE TITLE
Unary `.` operator can't be parsed

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#8797]
From what I can tell, this limitation is not included in the manual. 

```nim
import macros

# OK
dumpTree:
  let x = y . z

# Error: expression expected, but found '.'
dumpTree:
  let x = .y
```

Notably, this limitation prevents this from compiling:

```nim
# OK
import .. / module

# Error: expression expected, but found '.'
import . / module
```

**Comment by Araq** [comment]
The ``.`` is not an operator.

**Comment by GULPF** [comment]
That's fine, but it needs to be reflected in the manual. [From the manual](https://nim-lang.org/docs/manual.html#lexical-analysis-operators):

> Nim allows user defined operators. An operator is any combination of the following characters:
> ```
> =     +     -     *     /     <     >
> @     $     ~     &     %     |
> !     ?     ^     .     :     \
> ```

**Comment by Araq** [comment]
Good point. Single-char ``.`` and ``:`` are not operators.
