### ISSUE TITLE
`compiles(expr) with context: let `context = compilesWithContext(expr)` with context.{ok, warnMsg, errorMsg} to simplify tests

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8803]
a lot of tests would be greatly simplified with following feature:

```nim
let context = compilesWithContext(foo.bar)
doAssert: not context.ok
doAssert context.errorMsg == "Error: undeclared field: 'bar'"
```
with:
```nim
type Context = object
  ok: bool
  warnMsg: string # possibly split into (file, line, col, msg)
  errorMsg: string
```

currently, tests can have only 1 error per test, forcing related tests to be split, eg:
```
tests/types/tparameterizedparent0.nim:4:3:  errormsg: "inheritance only works with non-final objects"
tests/types/tparameterizedparent1.nim:4:3:  errormsg: "inheritance only works with non-final objects"
tests/types/tparameterizedparent3.nim:4:3:  errormsg: "attempt to redefine: 'color'"
tests/types/tparameterizedparent4.nim:4:3:  errormsg: "attempt to redefine: 'grain'"
```
with this simple feature, these could all be collapsed into a single test, eg:

**EDIT**
tests/types/tparameterizedparent0.nim could be rewritten as:
```nim
# bug #5264
type
  Kapal* = enum
    Besar

  Apple[T] = object of T
    color: int

let ctx = compilesWithContext(Apple[Kapal](color: 13))
doAssert not ctx.ok
doAssert ctx.errMsg ==  "inheritance only works with non-final objects"
doAssert ctx.line == 9

# now we can handle more `compilesWithContext` in same file
```

instead of:
```nim
discard """
  file: "tparameterizedparent0.nim"
  line: 14
  errormsg: "inheritance only works with non-final objects"
"""
# bug #5264
type
  Kapal* = enum
    Besar

  Apple[T] = object of T
    color: int

var x = Apple[Kapal](color: 13)
echo x
```

## EDIT
@Araq mentioned also: use 'nimout' and 'cmd: "nim check"'
eg: $nimc_D/tests/generics/tmetafield.nim

## note
as I noted here https://github.com/nim-lang/Nim/pull/9916#issuecomment-445725347
> nim check succeeding is equivalent to macros.compiles(foo) ; which is a subset of all reportable errors

EDIT: actually not quite equivalent, 1 seems to report more errors than the other i forgot which

* see also https://github.com/nim-lang/Nim/issues/9906 `nim check` doesn't report some compiler errors (eg: static array bound check)

**Comment by Araq** [comment]
I don't understand this proposal at all. Please elaborate.
