### ISSUE TITLE
[json] Add `pairs` iterator for `JArray`

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8818]
Currently pairs iter works only for JsonNode objects of JObject type, not to JArray type.

See [my comments here][1].

### Proposal

Add `pairs` iter for JArray too:

```nim
iterator pairs*(node: JsonNode): tuple[idx: int, val: JsonNode] =
  ## Iterator for the child elements of `node`. `node` has to be a JArray.
  assert node.kind == JArray
  var idx = 0
  for elem in items(node.elems):
    yield (idx, elem)
    idx += 1
```

*.. and probably `mpairs` too?*

[1]: https://gitter.im/nim-lang/Nim?at=5b880fc1c2bd5d117af52f3a

**Comment by Araq** [comment]
Every ``pairs`` that doesn't yield (key, value) pairs but is just a workaround for the missing ``sugar.enumerate`` needs to die.

**Comment by dom96** [comment]
> Every pairs that doesn't yield (key, value) pairs but is just a workaround for the missing sugar.enumerate needs to die.

So this can be closed then?

**Comment by Araq** [comment]
Well others may disagree and ``sugar.enumerate`` is missing.

**Comment by ringabout** [comment]
This issue can be closed with latest devel version
```nim
import json
import std/enumerate


let jsonNode = parseJson"""[1, 2, 3, 4]"""
doAssert jsonNode.kind == JArray
for idx, value in enumerate(jsonNode):
  echo $idx & " -> " & $value
```

```
0 -> 1
1 -> 2
2 -> 3
3 -> 4
```

**Comment by kaushalmodi** [comment]
@xflywind Thanks.
