### ISSUE TITLE
debug integration protocol with other languages

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/Nim#8827]
I want to make debug integration with c/c++. I have a c/c++ code base. I also want to incorporate with nim language. I can not debug like "csharp<=>fsharp" relation.

**Comment by mratsim** [comment]
I'm not familiar with .Net debugging but gdb/lldb works in Nim + C codebases.

What do you want?

Btw make sure to read this: https://nim-lang.org/blog/2017/10/02/documenting-profiling-and-debugging-nim-code.html#using-gdb-lldb

**Comment by develooper1994** [comment]
I can step-over c# code from f#.

**Comment by alaviss** [comment]
And you can step from Nim code to C/C++ and vice versa as well.

**Comment by krux02** [comment]
There is gdb support for Nim types by now, start script is located in ``bin/nim-gdb``. They are by far not prefect, but they are a starting point. They use a gdb API that is not supported by most editors/gdb frontends that I tested them with, but it works to debug Nim applications in emacs, eclipse, and the gdb terminal. If you have issues with that, please create a new issue specifically for the gdb integration.
