### ISSUE TITLE
`\r` produced by Nim color handling on posix

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8828]
`curl https://api.travis-ci.org/v3/job/422915784/log.txt | less` shows ^M characters:
which is a `\r` , a windows specific thing, it shouldn't be produced on travis logs (which is processed on posix), which probably indicates smthg in stdlib color handling produces that `\r`

![image](https://user-images.githubusercontent.com/2194784/44941363-c0e4a900-ad50-11e8-83aa-0fb2960e1bb4.png)

(that log came from https://github.com/nim-lang/Nim/issues/8824#issuecomment-417589340)

**Comment by Araq** [comment]
We don't output "Build language: C; Build group: stable". Looks like a travis bug to me.

**Comment by timotheecour** [comment]
ok you may be right, I reported it on travis then

**Comment by Araq** [comment]
Also ... HTTP usually encourages CR+LF over just LF so it's arguably a ``less`` bug.

**Comment by timotheecour** [comment]
ok found it: `less -r` doesn't show ^M
