### ISSUE TITLE
Generic functions can't be rewritten with dot notation.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#8837]
The Nim compiler doesn't treat `a.print()` as `print(a)` when there's a generic, no matter where I put the `[]`.

```
proc print*[T](p: pointer) =
    echo cast[T](p)

var a: pointer = alloc0(1)

print(a) #Doesn't work, as it shouldn't.
print[int](a) #Works.
a.print() #Doesn't work, as it shouldn't.
a.print[int]() #Doesn't work, despite the fact it should.
a[int].print() #Doesn't work, as it shouldn't.
a.[int]print() #Doesn't work, as it shouldn't.
```

The pointer printing was the most concise example I could think of. Sorry for involving pointers/alloc0.

This has been tested on a Windows compiler from 8-2 and Linux compiler from 8-31.

**Comment by hlaaftana** [comment]
`a.print[:int]` was added for this reason.

**Comment by kayabaNerve** [comment]
That does work 🤔 yet that issue isn't directly related.

**Comment by mratsim** [comment]
I think it's exactly the same issue. The bracket is ambiguous in dot syntax because `a.foo[bar]()` could be:

- `a.foo` returns a container of procs and you get the item at position `bar` which is a proc that you call
- `foo` is a generic proc and `bar` is a type

**Comment by kayabaNerve** [comment]
Got it. Thanks for the explanation there @mratsim . Sorry for saying it wasn't related.
