### ISSUE TITLE
\0 in comment replaced with 0 in docs

### ISSUE THREAD

**Issue by michaelkrukov** [nim-lang/Nim#8841]
## Description
Comments for readChar and peekChar are different from comments for them in source code. Difference is `'\0'` in source replaced by `'0'` in the documentation. It doesn't seems right. Correct me if i'm wrong.

## Links
https://nim-lang.org/docs/streams.html#readChar
https://github.com/nim-lang/Nim/tree/master/lib/pure/streams.nim#L177

**Comment by Araq** [comment]
I think RST uses the backslash for escaping and so that should have been written ``\\0``, but it's definitely something we need to look into.
