### ISSUE TITLE
[major] `someObject is object|int|tuple` fails (but `someObject is int|object|tuple` works...)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8846]
/cc @araq
reduced from a real use case:
```nim
type ObjectLike4* = tuple|object|int
type ObjectLike5* = int|tuple|object
type ObjectLike6* = object|int|tuple

type A = object
  tint: int

echo A is ObjectLike4
echo A is ObjectLike5
echo A is ObjectLike6

echo (1,2) is ObjectLike4
echo (1,2) is ObjectLike5
echo (1,2) is ObjectLike6

echo () is ObjectLike4
echo () is ObjectLike5
echo () is ObjectLike6

var a:A
echo a is ObjectLike4
echo a is ObjectLike5
echo a is ObjectLike6
```

prints:
true
true
false
false
true
true
true
true
true
true
true
false

every entry marked as false is a bug.

looks like:
* when T is object or tuple, `T is Foo1|Foo2|Foo3` doesn't take into account the 1st element Foo`
* when T is int, no bug
* when T is an instance of a tuple, there is a bug IF the instance is of size > 0

seems like a pretty serious bug...

## probably related
```nim
#BUG:D20180902T180936:here
type ObjectLike = object|tuple
when defined(case1):
  # Error: type mismatch: got <A>
  proc fun*[T:ObjectLike](a:T)=discard
when defined(case2):
  # ok
  proc fun*[T:tuple|object](a:T)=discard

type A = object
fun(A())
```

**Comment by LemonBoy** [comment]
Can you check if #8723 solves this?

**Comment by LemonBoy** [comment]
Meh, this is just a tame parser bug. When `type X = object | <something>` is parsed `parseObject` sees the leading `object` as a definition of an empty object and not as a "object typeclass" as it should.
