### ISSUE TITLE
`type(unnamedTuple).name`  inconsistent

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8861]
depending on context, `type(unnamedTuple).name` prints as `tuple of (int, int)` or as `(int, int)` ; it's inconsistent.
named tuples are consistent though.

```nim
import typetraits

block:
  let a = @[(1,2)]
  echo a.type #seq[tuple of (int, int)]
  echo a[0].type #(int, int)
block:
  let a = @[(a:1,b:2)]
  echo a.type #seq[tuple[a: int, b: int]]
  echo a[0].type #tuple[a: int, b: int]
```

## **EDIT** also this is inconsistent:
D20180904T195420
`tuple[]` instead of `tuple()` or `()` for empty tuple: the implementation looks like:
```nim
if t.n != nil:
      # generates a tuple[...]
elif sonsLen(t) == 0:
      # generates tuple[] # => BUG
else:
      # generates un-named tuple () 
```

the case above marked BUG should be considered as a un-named tuple since t.n = nil; eg this could be weird if we get an empty slice an unnamed tuple (when that's supported...) and then it returns a named (empty) tuple instead of a unnamed tuple; other cases are in generic code eg with variadic arguments: we shouldn't special case the case of empty tuple

## proposal
- [ ] to make it consistent, and also more inline with how named tuples print, I recommend that 
`type(unnamedTuple).name = tuple(int, int)` (etc)

- [ ] in case above, when `t.n == nil:` we should treat it as a unnamed tuple

**Comment by Araq** [comment]
Ok, but ``tuple(int, int)`` is not a syntax that exists.

**Comment by timotheecour** [comment]
well neither is `tuple of (int, int) ` ...

looks like it could be a simple fix:
```
if prefer == preferTypeName: result = "("
      else: result = "tuple of ("
```
=>
```
result = "tuple("
```
or:
```
result = "("
```

**Comment by timotheecour** [comment]
EDIT: actually `()` is ambiguous as it can mean both type and instance:
`type A = ()` and let a = ()` both currently work
so maybe `tuple()` is better

**Comment by timotheecour** [comment]
now gives:
```
seq[(int, int)]
(int, int)
seq[tuple[a: int, b: int]]
tuple[a: int, b: int]
```
as of 7f077a76fea389ce4f55e18857c499fadb3958fa
(i fixed tuple rendering in https://github.com/nim-lang/Nim/pull/14812 and https://github.com/nim-lang/Nim/pull/14799, and already added test cases)
