### ISSUE TITLE
Overloading: incorrect proc resolution with openarray

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8865]
In the following case, Nim doesn't properly resolve the proc overloaded:

```Nim
# resolution.nim
proc toHex*(a: openarray[int], lowercase = false): string =
  result = "Foo!"
```

```Nim
# resolution2.nim
import strutils
import ./resolution

let a = [1, 2, 3, 4]

echo a.toHex # Fails expected BiggestInt
echo toHex(a) # Fails expected BiggestInt

echo resolution.toHex(a) # works
echo a.toHex(false) # works
```

Impact on all proc overloaded with an optional parameter.

For example: https://github.com/cheatfate/nimcrypto/blob/b52a895f9ab220fdd883d76f2347e94753a69fb3/nimcrypto/utils.nim#L169-L172

**Comment by andreaferretti** [comment]
What does it mean to overload with an optional parameter? If the parameter is optional, the resolution is ambiguous, isn't it?

**Comment by skilchen** [comment]
The problem is not related to the optional parameter. `openArray[int]` is not considered as more specific than an unconstrained generic parameter:
```nim
proc foo[T](x: T) = echo "generic"
proc foo(x: int) = echo "int"
proc foo(x: openarray[int]) = echo "openarray[int]"
foo(5)
foo([1,2,3])
```
produces:
```
int
generic
```

**Comment by LemonBoy** [comment]
@skilchen hit the nail on the head, here's what sigmatch reports:

```
Candidate 'toHex' at lib/pure/strutils.nim(823, 5)
  exact matches: 0
  generic matches: 1
  subtype matches: 0
  intconv matches: 0
  conv matches: 0
  inheritance: 0
Candidate 'toHex' at resolution.nim(1, 5)
  exact matches: 0
  generic matches: 0
  subtype matches: 0
  intconv matches: 0
  conv matches: 1
  inheritance: 0
```

**Comment by mratsim** [comment]
@andreaferretti, the thing is, it's not even ambiguous in the test case.

**Comment by Araq** [comment]
That's a ``strutils`` bug. Workaround ``import strutils except toHex``
