### ISSUE TITLE
[Bug]strip() not clear white-space escape characters

### ISSUE THREAD

**Issue by muhammad-al-baqir-khalid** [nim-lang/Nim#8869]
strip() should clear "\n" from string because it's just whitespace escape characters
example:
`import strutils`
`var x = "\n".strip()`
`echo(x)`

in python it's does the job like it's should be 
https://stackoverflow.com/questions/24646461/python-why-does-str-strip-automatically-removes-all-the-escape-characters?lq=1

**Comment by andreaferretti** [comment]
It seems that this is because `\n` is not listed here https://nim-lang.org/docs/strutils.html#Whitespace

**Comment by muhammad-al-baqir-khalid** [comment]
Thanks so much a pull added

**Comment by kaushalmodi** [comment]
Hmm, I am not able to reproduce this issue on Nim devel (built today).

Evaluating:

```nim
import strutils
echo "«" & "\n string \n \n\n".strip() & "»"
echo "«" & "\n".strip() & "»"
```

gives:

```
«spacious»
«string»
```

**Comment by muhammad-al-baqir-khalid** [comment]
it's keep one line empty
try
`import strutils
echo ("\n \n").strip()`

**Comment by kaushalmodi** [comment]
@muhammad-al-baqir-khalid 

The empty line is because of `echo ""` 😄

**Comment by kaushalmodi** [comment]
@muhammad-al-baqir-khalid See `stdout.write` ([example][1]) if you want to echo without newlines.

[1]: https://scripter.co/notes/nim/#echo-without-newlines

**Comment by muhammad-al-baqir-khalid** [comment]
@kaushalmodi Thanks 👍 i know it but i just forget echo make new line
