### ISSUE TITLE
[runnableExamples] relative imports `import ./foo` should be rebased in runnableExamples, otherwise gives "Error: cannot open file"

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8878]
bar/t116_runnableExamples_relpath.nim:
```nim
import ./t116_runnableExamples_relpath2
runnableExamples:
  import ./t116_runnableExamples_relpath2
```
bar/t116_runnableExamples_relpath2.nim:
```nim
# empty (doesn't matter)
```

```
rnim tests/nim/t116_runnableExamples_relpath.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r tests/nim/t116_runnableExamples_relpath.nim
# works

nim doc tests/nim/t116_runnableExamples_relpath.nim
Error: cannot open file: ./t116_runnableExamples_relpath2
```

## proposal
* option 1:
runnableExamples should rebase relative imports in source code into either absolute ones (just as it's done with top-level implicit import `import "/path/to/bar/t115_isNamedTuple.nim"`)
* option 2 (probably even better, but could be done in subsequent improvement):
both relative imports in source code as well as top-level implicit import could also be rebased relative to current directory, to avoid adding environmental details (cwd) in generated runnableExamples; `-p:$PWD` can then be passed to the command that compiles the generated runnableExamples

## notes
* see: `proc extractImports(n: PNode; result: PNode)`

**Comment by Araq** [comment]
This has been fixed by calling ``nim`` with a ``--path`` parameter.
