### ISSUE TITLE
internal compiler error: openArrayLoc

### ISSUE THREAD

**Issue by micklat** [nim-lang/Nim#888]
When compiling my little test program, I get this error:

```
Error: internal error: openArrayLoc: PPyRef
```

Steps to reproduce:
0. use the current nimrod devel (d87579fd)
1. clone https://github.com/micklat/NimBorg, revision 6d2dfa
2. cd NimBorg/test
3. nimrod -r -p=../.. c test_mpl.nim

my system is ubuntu 12.04, with gcc 4.6.3.

**Comment by jangko** [comment]
this is the shorter code to reproduce the bug without any dependencies. the same bug of #2240, #3586, only with different facet

```nimrod
type
  PyRef = object
  PPyRef* = ref PyRef

converter to_py*(i: int) : PPyRef = nil

proc to_tuple*(vals: openarray[PPyRef]): PPyRef = 
  discard

proc abc(args: varargs[PPyRef]): PPyRef {.discardable.} = 
  let args_tup = to_tuple(args)

abc(1)
```
