### ISSUE TITLE
Cryptic error when including file that does not exist

### ISSUE THREAD

**Issue by half-potato** [nim-lang/Nim#8881]
Nim 0.18 compiler spits out:
```
  Verifying dependencies for replicate@0.1.0
   Building replicate/replicate using c backend
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: replicate
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/home/amai/.nimble/bin/nim" c --noBabelPath  -o:"/home/amai/replicate/replicate" "/home/amai/replicate/src/replicate.nim"
        ... Output: Hint: used config file '/home/amai/.choosenim/toolchains/nim-0.18.0/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: replicate [Processing]
        ... Hint: Test [Processing]
        ... Hint: Test1 [Processing]
        ... SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
with no line number when I attempt to include a file that includes a file that has a const array of an object declared in that file.

Full code here (truncated to ~20 lines for ease of debugging)
https://github.com/half-potato/replicate-nim-bug

**Comment by Vindaar** [comment]
While I'm not sure what is meant by "file that does not exist" (all files exist, as far as I can tell), I just ran it on current devel https://github.com/nim-lang/Nim/commit/4aba2981dd47672744191bd17b39bb149f494637 and it works just fine.

**Comment by PMunch** [comment]
I get a normal `Error: cannot open file: <missing file>` error, so I think this can be closed.
