### ISSUE TITLE
Minor "OR TYPES" error

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#8887]
Maybe my understanding of OR types is just wrong?

```nim

proc sqrPlus0(x: var float; i: int) =
  x = x * x + float(i)

proc sqrPlus1(x: var float | var int; i: int) =
  echo x + (type(x))(i)
  x = x * x

var x = 2.0; sqrPlus0(x, 1); echo x

var y = 2.0; sqrPlus1(y, 1); echo y
```

```
$ nim c t.nim
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t [Processing]
t.nim(11, 22) template/generic instantiation from here
t.nim(7, 3) Error: 'x' cannot be assigned to
```

**Comment by hlaaftana** [comment]
I assume it parses as `(var float) | (var int)` and the fact that it's a union makes something skip the `var` flags of either type, so it comes out as `float | int`. This is supported by the fact that `var (float | int)` works. I don't think behaviour like `(var float) | int` could be supported or useful, so maybe this should be an error.

**Comment by nc-x** [comment]
Changing `x: var float | var int` to `x: var (float | int)` makes it work
