### ISSUE TITLE
Recent change to sentTo did not apply to windows.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#8898]
```net.sendTo no longer returns an int and now raises an OSError.```

But not windows? Using it requires this code:

```  
  when defined(windows):
    var success = reactor.socket.sendTo(address.host, address.port, data)
    if success == -1:
      print "failed to send", address
  else:
    reactor.socket.sendTo(address.host, address.port, data)
```

**Comment by dom96** [comment]
``reactor``?

The ``sendTo`` function has the same definition on all OS':

https://github.com/nim-lang/Nim/blob/devel/lib/pure/net.nim#L1400
