### ISSUE TITLE
quoted symbols `foo` should not be replaced in template substitution

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8899]
to avoid running into https://github.com/nim-lang/Nim/issues/8882 and allow a common (for me at least) idiom, I'd like to suggest that a quoted symbol `name` should not be replaced in template substitution
```nim
type Bar = object
  name: string
proc funAux(name: string)=discard

template fun(name = ""): untyped =
  # this gives errors, see https://github.com/nim-lang/Nim/issues/8882
  funAux(name = name)
  let foo = Bar(name: name)

  # proposal: avoid name substitution when symbol is quoted:
  funAux(`name` = name) # in this example, would substitute as: funAux(name = "")
  var foo = Bar(`name`: name) # in this example, would substitute as: Bar(name: "")
  foo.`name` = "baz"
fun()
```

The workaround (renaming the template arguments) is not great, eg:
```nim
type Bar = object
  name: string
  niter: int

template fun(niter2: int, name2 = ""): untyped =
  # ....
  Bar(niter:niter2, name: name2)
```

**Comment by Araq** [comment]
This keeps coming up but the template substitution mechanism should remain simple, rename your template parameters when you have a conflict like this.

**Comment by Araq** [comment]
Then you rename your object field. :P

**Comment by dom96** [comment]
I would propose the opposite: only substitute quoted symbols.

In fact, I'm pretty sure I got @Araq to agree to this over PM at one point...

**Comment by krux02** [comment]
@yyyc514 @timotheecour 

nested templates solve all problems

```nim
var resp: tuple[body: string]

template renderInner(bodyArg: string): untyped =
  resp.body = bodyArg

template render*(body: string) :untyped =
  renderInner(body)

render(body = "raw content")

echo resp
```

@dom96 I would agree on it as an initial design choice, but right now it would just break too much code.

**Comment by dom96** [comment]
Maybe we could use a different symbol for the quoting to have a transition period?

**Comment by yyyc514** [comment]
Nested templates. Nice thanks. Will work for now.

**Comment by Araq** [comment]
> Maybe we could use a different symbol for the quoting to have a transition period?

Gah, no, quoting is so ugly, but I think you mean, "quote in dot notation to get the replacement"?
