### ISSUE TITLE
Create binary file in temporary folder.

### ISSUE THREAD

**Issue by DanielSokil** [nim-lang/Nim#8910]
Are there any plans to be able to run a source file without creating a binary file?
For example, when running `nim c -r main.nim`:
The results are a native binary and nimcache folder.

I like how golang handles this:
When running `go run main.go`:
It runs the program in a tmp directory: `/tmp/go-build680322009/b001/exe/main` and returns output.

**Comment by Araq** [comment]
``nim c -r main.nim && rm ./main`` does the job.

**Comment by timotheecour** [comment]
* not robust in case the binary generated by nim fails on `foo bar`: `nim c -r main.nim foo bar` => `rm ./main` won't be called
* not cross platform
i think the feature @DanielSokil wants is reasonable and probably trivial to implement

**Comment by dom96** [comment]
Why is this feature reasonable? What's so bad about a binary being produced?

A better version of @Araq's command is:

```
nim c -r --out:/tmp/blah main.nim
```

**Comment by DanielSokil** [comment]
Let's say you have 50 nim files in a folder, it takes more time to find the file you want, when there is:
`file.nim` and `file` binary file.
@dom96 `nim c -r --out:/tmp/blah main.nim` Would work, but it is not as simple as `go run main.go`

**Comment by dom96** [comment]
You can easily create an alias in your shell for that command.

**Comment by DanielSokil** [comment]
Thanks @dom96.
### `alias nimr='nim c -r --out:/tmp/nim-cache'` Works perfectly.
