### ISSUE TITLE
counting the empty substring in a string results in infinite loop

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#8919]
This example will never terminate:

```nim
import strutils

proc test(s, sub: string): int =
  count(s, sub)

echo test("hello world", "")
```

Since Nim allows the replacement of the empty substring, it would be probably reasonable to return the number of replacements that would be performed by `replace(s, "")`, ie. `len(s) + 1` in the case of counting the empty substring (or the empty set[char]).

**Comment by dom96** [comment]
I agree. I recall a similar discussion to this which might be useful to look up.

**Comment by skilchen** [comment]
Counting the empty string is not an API misuse as someone else claims. But raising an exception is better than looping infinitely. 

In some circles the empty string is considered as the identity operator of string concatenation. From this point of view it makes sense to allow the replacement of the empty string and therefore to count the occurrences of such replacements.

But currently it would be more important to fix the handling of the empty string (aka zero-length match) in re.nim where in some cases it also ends in infinite loops.

**Comment by Araq** [comment]
It is an API misuse and the fact that it needs special code logic everywhere suggests that the view  "the identity operator of string concatenation" is just wrong.

**Comment by skilchen** [comment]
The messages produced about the API misuse could be better:
```nim
echo count("", "")
```
produces
```
.../lib/pure/strutils.nim(1474, 12) `
0 < len(sub)`  [AssertionError]
```
and the similar `echo count("", {})` produces
```
.../lib/pure/strutils.nim(1492, 12) `
0 < card(subs)`  [AssertionError]
```
A line-break before the first "`" instead of after it, would be better.

An explicit message such as "counting the empty string is an API misuse" or something similar would be helpful for logically impaired people like me.

Two other observations about the empty string:
-  `strutils.find("somestring", "", n)` returns n for any non-negative n. 
- `strutils.rfind("somestring", "", n)` returns 0 for any non-negative n.

I was expecting to get -1 when searching outside of the bounds of "somestring" (like for every other substring).
Are these bugs or legitimate consequences of my adversarial API misuse?
