### ISSUE TITLE
.cfg cross-compilation not working

### ISSUE THREAD

**Issue by markprocess** [nim-lang/Nim#8921]
https://nim-lang.org/docs/nimc.html#cross-compilation

    Another way is to make Nim invoke a cross compiler toolchain:

    nim c --cpu:arm --os:linux myproject.nim
    For cross compilation, the compiler invokes a C compiler named like $cpu.$os.$cc (for example 
    arm.linux.gcc) and the configuration system is used to provide meaningful defaults. For example for  
    ARM your configuration file should contain something like:

    arm.linux.gcc.path = "/usr/bin"
    arm.linux.gcc.exe = "arm-linux-gcc"
    arm.linux.gcc.linkerexe = "arm-linux-gcc"

produces

    Error: execution of an external compiler program 'gcc -c  -w  -I'/root/.choosenim/toolchains/nim-#devel/lib' -o /root/.cache/nim/myproject_d/myproject.c.o /root/.cache/nim/myproject_d/myproject.c' failed with exit code: 1

Note it is calling gcc, not arm-linux-gcc

debian x64, choosenim devel

**Comment by cup** [comment]
I am having same problem. @Araq can you advise?

**Comment by nc-x** [comment]
Can you provide some details as to which OS you are using and what command are you running.
Running the command in the above post on termux (android), it is looking for `arm-linux-gnueabihf-gcc`, which is correct according to https://github.com/nim-lang/Nim/blob/23fc93fc2d0e409fba92ddbb02772d4ba5bb9c0f/config/nim.cfg#L23

**Comment by Yardanico** [comment]
Are you sure your configuration file is actually used (e.g. you see something like `Hint: used config file '/home/dian/.nim/config/nim.cfg' [Conf]` but with your cfg file while compiling the code?

**Comment by cup** [comment]
~~~
$ cat app.nim
echo "sunday"

$ cat nim.cfg
amd64.windows.gcc.exe = "x86_64-w64-mingw32-gcc"
amd64.windows.gcc.linkerexe = "x86_64-w64-mingw32-gcc"

$ nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]

$ nim c --cpu:amd64 --os:windows app.nim
Hint: used config file 'C:\nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\Steven\Desktop\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: app [Processing]
CC: stdlib_io.nim
Error: invocation of external compiler program failed. The system cannot find
the file specified.
Additional info: "Requested command not found: \'gcc.exe -c -w -mno-ms-bitfields
-IC:\\nim\\lib -IC:\\Users\\Steven\\Desktop -o
C:\\Users\\Steven\\nimcache\\app_d\\stdlib_io.nim.c.o
C:\\Users\\Steven\\nimcache\\app_d\\stdlib_io.nim.c\'. OS error:" 2
~~~

**Comment by nc-x** [comment]
Why do you want to cross compile from windows to windows though? 
In my minimal testing, this use case does not work, otherwise actual cross-compilation works fine.

**Comment by cup** [comment]
@nc-x my compiler is `x86_64-w64-mingw32-gcc`, so I need Nim to use that.
However currently it only uses `gcc` and ignores my settings.

**Comment by nc-x** [comment]
@cup can you try 
`nim c --cpu:amd64 --os:windows --cc:gcc app.nim` (i.e. add `--cc:gcc`)

If this does not work then maybe windows is special cased somewhere.

**Comment by cup** [comment]
@nc-x that doesnt change anything

**Comment by nc-x** [comment]
👍🏻 
I will have a look at this on my windows tomorrow or day after.

**Comment by Yardanico** [comment]
@nc-x what about
```
gcc.exe = "x86_64-w64-mingw32-gcc"
gcc.linkerexe = "x86_64-w64-mingw32-gcc"
```
?

**Comment by genotrance** [comment]
Just use -d:mingw

https://nim-lang.org/docs/nimc.html#cross-compilation-for-windows

**Comment by cup** [comment]
@genotrance I would ask that you not make suggestions without trying them first:

~~~
$ nim c -d:mingw app.nim
Hint: used config file 'C:\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: app [Processing]
CC: stdlib_io.nim
Error: invocation of external compiler program failed. The system cannot find
the file specified.
Additional info: "Requested command not found: \'gcc.exe -c -w -mno-ms-bitfields
-IC:\\nim\\lib -IC:\\Users\\Steven\\Desktop -o
C:\\Users\\Steven\\nimcache\\app_d\\stdlib_io.nim.c.o
C:\\Users\\Steven\\nimcache\\app_d\\stdlib_io.nim.c\'. OS error:" 2
~~~

**Comment by nc-x** [comment]
@Yardanico that works.
Also I created a PR for cross compiling from host to host - https://github.com/nim-lang/Nim/pull/12859

**Comment by genotrance** [comment]
@cup - no where in this issue did you mention that this is Win => Win cross-compilation. Why that's something you want is beyond me but anyway, `-d:mingw` which I added didn't cover that case. If that's something that is needed, we can look into it.

https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L86

Please also stop deleting your comments. Doesn't help with understanding the issue at all.

**Comment by cup** [comment]
@genotrance 

https://github.com/nim-lang/Nim/issues/8921#issuecomment-562981618
