### ISSUE TITLE
Regression: stack trace line numbers are messed up for asserts

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#8928]
```nim
import random
proc foo() =
  if rand(0 .. 1) == 0: assert(false)
  assert(false)
foo()
```
Question: which of the asserts failed given the following stack trace?
```
test.nim(6)              test
system.nim(3788)         foo                                   <-- Note line number
system.nim(3778)         failedAssertImpl
system.nim(3771)         raiseAssert
system.nim(2818)         sysFatal
Error: unhandled exception: /home/yglukhov/test.nim(4, 9) `false`  [AssertionError]
```

**Comment by timotheecour** [comment]
where's the bug?
```nim
import random
proc foo() =
  if rand(0 .. 1) == 0: assert(false, "foo1")
  assert(false, "foo2")
foo()
```
t54_issue_8928.nim(4, 9) `false` foo2 [AssertionError]

note: line numbers displayed in error messages start at 1, not 0.
column numbers in some error messages are off by 1 in some cases, which is a separate issue that I'm tackling in another PR

**Comment by LemonBoy** [comment]
@timotheecour You removed the `{.line: instantiationInfo(fullPaths = true).}` line in `assertImpl`, that's why the stack trace changed.
