### ISSUE TITLE
var s = "a" # in --app:staticlib will crash

### ISSUE THREAD

**Issue by markprocess** [nim-lang/Nim#8932]
Reprository https://github.com/markprocess/nim-staticlib

https://github.com/markprocess/nim-staticlib/issues/1

**Comment by alaviss** [comment]
You've to initialize the GC first, call `NimMain()` from your C file like this:

```c
void NimMain(void);

int main() {
  NimMain();
  /* everything else go here */
}
```

This is because `string`s are backed by the GC.
