### ISSUE TITLE
Internal compiler error for proc alias

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#8935]
If I remember correctly proc alias with const keyword was possible some years ago. Now with const, let or var we get some different internal errors:

```nim
#const
#  myPrint = echo

#let
#  myPuts = system.echo

const # or let or var
  testForMe = assert
testForMe(1 + 1 == 2)

#puts "puts is alias for echo"
#print "print is also alias for echo"
```

```
$ nim c t.nim 
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: t [Processing]
t.nim(8, 15) Error: internal error: expr(skTemplate); unknown symbol
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
stefan@nuc /tmp/hhh $ nim -v
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-09-05
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 4aba2981dd47672744191bd17b39bb149f494637
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
It should be possible to do this today as well, but it only makes sense with procs that are non-generic. The generic ones are just "recipes" to instantiate a non-generic one with concrete types, hence it does not make sense to bind it to a runtime variable

**Comment by hlaaftana** [comment]
It's still possible, it's just that `assert` is a template and not a proc

**Comment by narimiran** [comment]
> But maybe we can improve the error message -- internal error is a bit confusing, although the source of the error is mentioned: expr(skTemplate)

Current devel (0.20.99) produces: `Error: VM problem: dest register is not set`

**Comment by timotheecour** [comment]
my PR https://github.com/nim-lang/Nim/pull/11822 fixes this, see test case

**Comment by narimiran** [comment]
> But maybe we can improve the error message -- internal error is a bit confusing, although the source of the error is mentioned: expr(skTemplate)

Currently with the latest Nim devel, this is the error message: `Error: invalid type: 'template (cond: untyped, msg: string)' for const. Did you mean to call the template with '()'?`

I consider this an improved error message.
