### ISSUE TITLE
Again: Capturing a closure from another closure produces codegen errors (see #581)

### ISSUE THREAD

**Issue by AndreasBriese** [nim-lang/Nim#8939]
This is the "old" case of scope problems mentioned in #581.
.. and it is solved and compiling

```
# compiling.nim
proc outer(x: int) = 
  echo x
  proc inner() =
    echo x
  inner()

outer(2)
```

This has the same structure but here is an openArray the parameter in scope. 

```
# not_compiling.nim

proc outer(x: openArray[int]) = 
  echo x
  proc inner() =
    echo x
  inner()

outer([1, 2])
```

It won't compile with:
not_compiling.nim(6, 10) Error: illegal capture 'x' of type <openarray[int]> which is declared here: not_compiling.nim(3, 11)

Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-09-03
Copyright (c) 2006-2018 by Andreas Rumpf
active boot switches: -d:release

EDIT:
Can be circumvented by casting the openArray to var in outer(). But by definition outer's parameters  should have been in scope of inner(), i guess.  
```
proc outer(x: openArray[int]) = 
  echo x
  var x = @x
  proc inner() =
    echo x
  inner()

outer([1, 2])
```

**Comment by Araq** [comment]
This would break memory safety and is disallowed for this reason. This is not a bug. Will make the error message even clearer though.
