### ISSUE TITLE
[RFC] Exportable using statements

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#8943]
`using` statements alias to typed, named arguments in procedures/functions and are exceptionally useful for repetitive arguments. However, a using statement can only be local to a module as it stands currently.
```nim
# using1.nim

type
  Foo* = object
    blah: int

using foo*: Foo
```
```nim
# using2.nim

import using1

proc bar(foo; x: int) =
  discard

var foo: Foo
foo.bar(1)
```
Compiling `using2.nim` gives us a `Error: typeless parameters are obsolete`. Curiously, even if we didn't have that procedure there, the compiler accepts the using statement with the asterisk. 

Allowing using statements to become exportable would be very useful for procedures across multiple modules that use similar, repetitive arguments. To denote a using statement for export the name should be denoted with asterisk, the same way as exports are generally done in Nim (duh).

**Comment by Araq** [comment]
> Allowing using statements to become exportable would be very useful for procedures across multiple modules that use similar, repetitive arguments. 

``using`` statements *should* be attached to the module only for navigability. "Goto definition" on a parameter that has an implicit using type wouldn't go to the ``using`` declaration. 

As a workaround you can put the ``using`` in an ``include`` file.

> To denote a using statement for export the name should be denoted with asterisk, the same way as exports are generally done in Nim (duh).

That the star is allowed here is just a bug.
