### ISSUE TITLE
compiler workchain 

### ISSUE THREAD

**Issue by AndreasBriese** [nim-lang/Nim#8946]
Currently this won't compile: not_compiling.nim(2, 8) Error: undeclared identifier: 'x'

```
proc outer() = 
  echo x

let x = [1, 2]
outer()
```
i would suggest to introduce a step of reordering the lines in a way that import, const, var, let, proc are arranged at top before compiling the source. i guess it may scramble up with the line addresses in error messaging and a scheme to readdress the lines might be needed. Anyway imo the current situation is inconvenient and reminds me of writing pascal in the '80s.

**Comment by alaviss** [comment]
It already exists, undocumented (see #8806), but highly experimental.

**Comment by mratsim** [comment]
Duplicate https://github.com/nim-lang/Nim/issues/5287

You can try `{.reorder: on.}`

**Comment by AndreasBriese** [comment]
Yep {.reorder: on.} does the trick.

```
{.reorder: on.}

proc outer() = 
  echo x

let x = [1, 2]
outer()
```

But unfortunately does not work on #8947
