### ISSUE TITLE
The file 'dochack.js' not generated with the documentation

### ISSUE THREAD

**Issue by sodic** [nim-lang/Nim#8952]
The `doc` and `doc2` commands produce an HTML document which relies on a file named `dochack.js`. Since the commands do not generate this file, most of the documentation's dynamic functionalities are broken.

### Minimal example
Make a file called `sample.nim` with the following content:
```nim
## This module is a sample

proc foo*(bar: int): int = 
  ## Adds 1 to the provided bar.
  bar + 1
```
Run the `doc` commands as described [in the official documentation](https://nim-lang.org/docs/docgen.html):
```bash
nim doc sample.nim
```
Open the generated `sample.html` file and try to group entries or use the search bar. The operation should fail and an error should be reported in the console.
### Conclusion
 - **If this is a bug**, nothing else needs to be said.
 - **If this is an improper/incoplete way to go about generating documentation** and the file is indeed present when the docs are generated in a proper manner, I believe the [online documentation](https://nim-lang.org/docs/docgen.html) should be updated.
 - **If this is the intended behavior** and those dynamic functionalities should be disabled by default (e.g. a flag needs to be added to generate the `dochack.js` file), that should also be mentioned in the online `docgen` documentation. In addition, I would propose to disable said functionalities in a more obvious way like not having them appear in the HTML at all (instead of them silently failing).

**Comment by timotheecour** [comment]
dochack.js is not enough theindex.html is also needed ; even after:

nim doc -o:htmldocs --project --index:on pathto/main.nim
nim js -o:htmldocs/dochack.js $nimc_D/tools/dochack/dochack.nim
open htmldocs/main.html # in chrome
# open developper tools; type something in search bar; shows error that theindex.html is missing

**Comment by Araq** [comment]
Now it's built with ``koch docs``.

**Comment by timotheecour** [comment]
verified this now works locally including `search`:
```
./koch docs
python -m SimpleHTTPServer 9009
open http://localhost:9009/md5.html
# now search works
```
