### ISSUE TITLE
Regression after PR #8940, cpp backend broken

### ISSUE THREAD

**Issue by sinkingsugar** [nim-lang/Nim#8964]
Anytime I try to compile with `cpp` gcc fails to compile `stdlib_typeinfo.cpp`

Reverting the PR fixes the issue.

**Comment by sinkingsugar** [comment]
Tried quickly didn't manage to make anything simple enough tho.

Might be related to the many foreign cpp types I have tho in the big projects I compile.

**Comment by sinkingsugar** [comment]
Quick repro:
```
import marshal
const nothing = ""
var bar = marshal.to[int](nothing)
```
( notice this code will finally crash anyway, but the point is that we get gcc errors before even running )

**Comment by sinkingsugar** [comment]
We definitely need to test everything in both c and cpp imho.

**Comment by skilchen** [comment]
Try to compile `lib/pure/marshal.nim` on the cpp backend before #8940. If it worked for you before, this was some kind of a lucky accident. For me it doesn't compile on every version of Nim I currently have on my linux system (the oldest being 0.17.2).

**Comment by sinkingsugar** [comment]
Well, Works perfectly before this PR for me or I would have not proposed it as repro case.

**Comment by sinkingsugar** [comment]
@LemonBoy Tested your fork/PR #8966 on our quite big codebase, seems to work ok for this specific case at least !

**Comment by LemonBoy** [comment]
> Try to compile lib/pure/marshal.nim on the cpp backend before #8940.  If it worked for you before, this was some kind of a lucky accident.  For me it doesn't compile on every version of Nim I currently have on my  linux system (the oldest being 0.17.2).

Please open another ticket, that's another problem. Long story short the compiler won't cast your decayed array into a reference.
