### ISSUE TITLE
Typetraits arity: off-by-one for arrays

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8965]
Test case:

```Nim
import typetraits

let t = (1, 2, 3)
doAssert t.type.arity == 3, "Found arity: " & $t.type.arity

let a = [1, 2, 3]
doAssert a.type.arity == 3, "Found arity: " & $a.type.arity
```

**Comment by zah** [comment]
Since `array` is a generic type, `arity` here refers to the number of generic arguments of the type (so, 2 is correct). `len` can be defined for the tuple types to help in generic code that must deal with tuples and arrays in uniform way.

**Comment by andreaferretti** [comment]
(even `proc len(t: tuple): int = type(t).arity` would do, right?)

**Comment by zah** [comment]
Yes

**Comment by mratsim** [comment]
haha, I see! Closing then unless we retag this as `need documentation`?
