### ISSUE TITLE
Docs built from devel have incorrect cross-module, source, edit links

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8974]
Example: https://kaushalmodi.github.io/nim-nightly-docs/cpuinfo.html ([`.travis.yml`][1] used to build these docs)

**Incorrect links**:

![image](https://user-images.githubusercontent.com/3578197/45583037-c251bd80-b888-11e8-9f5b-d5651354866e.png)

As of typing, they are built from https://github.com/nim-lang/Nim/tree/b9dc486db15bb1b4b6f3cef7626733b904d377f7 commit.

The issue can be recreated locally too after running `koch docs`.

- [x] Fix the Imports links - Probably fixed in https://github.com/nim-lang/Nim/commit/3467c455c0a90a9f507e92b72cb7dd1a9aaf85e8
- [x] Fix the Source link
- [x] Fix the Edit link

[1]: https://github.com/kaushalmodi/nim-nightly-docs/blob/3935051d9b9c55b93a4efbdd1875f655322bdef4/.travis.yml

**Comment by Araq** [comment]
I know, the new documentation generator is still in the works...

**Comment by kaushalmodi** [comment]
OK. Also, just for record, the search doesn't work too.

Additionally, I plan to add `htmltest` (a CLI utility to test all the links) in Travis.

It will look like this: https://travis-ci.org/kaushalmodi/nim-nightly-docs/builds/428903236#L483 (right now, it is crashing because of links like https://kaushalmodi.github.io/nim-nightly-docs/system.html#+%,IntMax32,IntMax32 (which will be hopefully fixed soon).

**Comment by kaushalmodi** [comment]
@Araq The Source and Edit links are broken on the released 0.19.0 docs too: https://nim-lang.org/docs/cpuinfo.html

**Comment by kaushalmodi** [comment]
This got fixed today along with https://github.com/nim-lang/Nim/issues/9083.

**Comment by timotheecour** [comment]
see also https://github.com/nim-lang/Nim/issues/9295 which remains an issue today
