### ISSUE TITLE
`locals` doesn't work with generics

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8985]
`nim c -d:case1 main.nim` works
`nim c main.nim` fails: `Error: invalid type: 'Foo2' for var`

looks like system.locals returns incomplete type (only the head) for generics; it somehow works with `case1`, maybe due to some caching mechanism for generics

D20180917T105102
```nim
proc numFields*(T: typedesc[tuple|object]):auto=
  var t:T
  var n=0
  for _ in t.fields:
    inc n
  return n

type Foo1=object
  a1: string
type Foo2[T]=object
  a2: T

proc test=
  var foo1: Foo1
  var foo2: Foo2[int]
  let c1=locals()

  when defined(case1):
    block:
      let c2 = (foo1:foo1, foo2: foo2)
      echo numFields(c2.foo2.type)

  block:
    # Error: invalid type: 'Foo2' for var
    echo numFields(c1.foo2.type)

test()
```

**Comment by mratsim** [comment]
This sounds similar to https://github.com/nim-lang/Nim/issues/7737.

**Comment by timotheecour** [comment]
are you sure? I don't have `varargs` in my example, whereas  #7737 says:

> The example is a bit verbose, I could boil it a bit down if that helps to fix the bug. It seems like varargs is causing the problem, because without varargs, it just works.

**Comment by mratsim** [comment]
I would say

> Generics are causing the problem because without generics it just works

;)

locals might use varargs-like mechanism internally.
