### ISSUE TITLE
Allow optional parameters to be ignored when procedure is taken as argument

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#8987]
I recently ran into something which I think Nim should support. I was trying to do this:
```
for key in myString.split('+').map(strip):
  discard # Doesn't matter what goes here
```
But I'm unable to map the `strip` procedure over the sequence because it doesn't have the signature `proc (x: T): S`. Looking at strip is has the signature `proc strip(s: string; leading = true; trailing = true; chars: set[char] = Whitespace): string`. The issue here is that the optional parameters are not ignored when comparing the signatures. In fact wrapping it like this works:
```
for key in myString.split('+').map(proc (x: string): string = x.strip):
  discard # Doesn't matter what goes here
```

**Comment by andreaferretti** [comment]
(a workaround is `mapIt(strip(it))`)

**Comment by Araq** [comment]
Known feature request. Duplicate of something. ;-)
