### ISSUE TITLE
`defined(nimdoc)` special case causes `nim doc` failures, eg with jester: Error: undeclared identifier: 'EWOULDBLOCK'

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8989]
main.nim:
```nim
import jester
echo "ok1"
```

```
# this works:
nim c main.nim
```

```
# this doesn't work:
nim doc main.nim
```
I get:
```
template/generic instantiation from here
/Users/timothee/.nimble/pkgs/httpbeast-0.2.1/httpbeast.nim(183, 36) Error: undeclared identifier: 'EWOULDBLOCK'
```

## links
* seeing same error here: https://nimble.directory/ci/badges/httpbeast/nimdevel/doc_build_output.html

## EDIT
the culprit is:
`const useWinVersion = defined(Windows) or defined(nimdoc)` in $nimc_D/lib/pure/nativesockets.nim

Curious why we need all these `defined(nimdoc)` special cases; ideally `nim doc` could be built on each platform and generate platform specific docs.

**Comment by Araq** [comment]
No, that is not what is happening, the ``net`` module or similar maps ``nim doc`` to the Windows variant.

**Comment by timotheecour** [comment]
just sent out https://github.com/dom96/httpbeast/pull/14 as a really ugly workaround; what's a better workaround?

> No, that is not what is happening, the net module or similar maps nim doc to the Windows variant.

well I'm seeing things like `const useWinVersion = defined(Windows) or defined(nimdoc)` ; isn't that error prone?

**Comment by Araq** [comment]
That's a jester bug.
