### ISSUE TITLE
how to profile? using `--profiler:on` causes: Error: undeclared identifier: 'framePtr'

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8991]
main.nim: empty
```
nim c --profiler:on main.nim
lib/system/profiler.nim(92, 23) Error: undeclared identifier: 'framePtr'
```

I was trying to see how to profile code, and was following https://nim-lang.org/docs/estp.html 
I also tried following instructions in `lib/pure/nimprof.nim`:
`import std/nimprof` gives:
```
Error: Profiling support is turned off! Enable profiling by passing `--profiler:on --stackTrace:on` to the compiler (see the Nim Compiler User Guide for more options).
```
adding `--profiler:on ` gives, again, `Error: undeclared identifier: 'framePtr'`

## links
* https://github.com/nim-lang/Nim/wiki/Profiling
* https://nim-lang.org/docs/estp.html
* https://nim-lang.org/docs/nimc.html (memProfiler)
* https://stackoverflow.com/questions/31624145/how-to-use-nimprof

**Comment by narimiran** [comment]
Can confirm and reproduce on my end.

These exact steps used to work before, now they don't work neither in stable (0.19.0) nor devel.
