### ISSUE TITLE
internal error: genTypeInfo(tyProxy) on js target when assigning empty NimNode

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#8997]
I noticed that the DSL I use in NimSVG works on the C target, but when using the same approach on the JS target it gives an error. The problem comes down to this:

```nimrod
import macros

type
  Node* = ref object
    children: seq[Node]


proc newNode*(): Node =
  Node(children: newSeq[Node]())


macro build*(body: untyped): untyped =

  template appendElement(tmp, childrenBlock) {.dirty.} =
    bind newNode
    let tmp = newNode()
    tmp.children = childrenBlock  # this line seems to be the problem

  let tmp = genSym(nskLet, "tmp")
  let childrenBlock = newEmptyNode()
  result = getAst(appendElement(tmp, childrenBlock))

  echo "Resulting AST:"
  echo result.repr


build(body)
```

The AST created by the macro is:

```nimrod
let tmp128134 = newNode()
tmp128134.children =
```

This problematic expression seems to be `tmp128134.children =` assigning an empty `NimNode`.

**Comment by LemonBoy** [comment]
I think that an assignment with a `nkEmpty` RHS should be caught during the semantic analysis and rejected instead of have it silently compiled as a noop.

CC @araq, what's your take on this?

**Comment by Leon-Watschengaun** [comment]
How is that even allowed to use words like genType,internal,target .
In a world we live today it must be inappropriate to even think about them, knowing what kind of dark history(not related to colour).
Generally speaking I do believe we can all agree that some specific function words should be changed.
With love from Leon.

**Comment by SolitudeSF** [comment]
github doesnt have a mechanism to stop freshly created accounts from posting?
