### ISSUE TITLE
osproc.select() is broken on Windows.

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#90]
When trying to use `osproc.select()` on a process in Windows, `select()` only reports the process as being readable when the process exits. This is not correct, and it causes the process to halt when its stdout pipe gets filled up.

I believe that there isn't a way to fix this (although I have investigated this a while ago, so my memory might not serve me correctly). I think the select() function should be removed in favour of an asynchronous process implementation or asynchronous stream implementation.

**Comment by Araq** [comment]
We now use IO completion ports.

**Comment by dom96** [comment]
For those that find this issue: you can use https://github.com/cheatfate/asynctools to get async osproc functionality.
