### ISSUE TITLE
Some global variables are initialized too late

### ISSUE THREAD

**Issue by nortiero** [nim-lang/Nim#9007]
Hi! I've noticed that global variables defined after main proc but accessed by some other procedure are still uninitialized. This leads to surprising behavior, imho. 

This may be a perfectly known and reasonable thing, unbeknownst to me.

nim 0.18.0 & devel

Expected: `v1: 100.0 v3: 65536` . Got: `v1 100.0 v3: 0`

```
proc gore
var v1 = 100.0f
proc main =
    echo "v1: ", v1
    gore()
main()
var v3 = 65536
proc gore =
    echo "v3: ", v3
```

**Comment by nortiero** [comment]
I should add that it works as expected by moving main() to eof!

**Comment by Araq** [comment]
``main`` is called before the assignment ``v3 = 65536``, calls ``gore``, ``gore`` outputs ``v3`` which is still 0. It's the expected behaviour.
