### ISSUE TITLE
pegs doesn't work in nimscript

### ISSUE THREAD

**Issue by KeepCoolWithCoolidge** [nim-lang/Nim#9009]
When you try to use pegs module in a nimscript, you get an error:

> Hint: used config file '/Users/macbookpro/Documents/clutter_process/fix_opaque_structs.nims' [Conf]
> stack trace: (most recent call last)
> fix_opaque_structs.nims(7)
> lib/pure/pegs.nim(1695)  peg
> lib/pure/pegs.nim(1687)  parsePeg
> lib/pure/pegs.nim(1469)  getTok
> lib/pure/pegs.nim(1341)  getTok
> lib/pure/pegs.nim(1217)  skip

PegParser inherits from PegLexer. This seems to be okay with compiled code, but VM does not appear to be able to access the parent's buf variable. A work around is to combine the Lexer and Parser into one object...but that doesn't resolved underlying problem. This is probably already pointed out in another issue, but I thought I'd bring it up. Being able to use pegs in nimscripts is highly desirable

**Comment by alaviss** [comment]
Can you also include a small snippet showing the problem? It could be used as a test case if this issue is fixed.

**Comment by demotomohiro** [comment]
I got a error that looks like related to this issue.

Following code works.
```nim
import pegs

let mypeg = peg"'xyz'"

echo find("xyz", mypeg)
```

But when I changed ``let`` to ``const``, I got ``index out of bounds`` error.

```nim
import pegs

const mypeg = peg"'xyz'"

echo find("xyz", mypeg)
```
Compiling above code generate following error:
```console
f:\temp>nim c -r testpeg.nim
Hint: used config file 'f:\project\nim-lang\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: testpeg [Processing]
Hint: pegs [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: macros [Processing]
stack trace: (most recent call last)
testpeg.nim(3)
..\project\nim-lang\Nim\lib\pure\pegs.nim(2040) peg
..\project\nim-lang\Nim\lib\pure\pegs.nim(2032) parsePeg
..\project\nim-lang\Nim\lib\pure\pegs.nim(1814) getTok
..\project\nim-lang\Nim\lib\pure\pegs.nim(1685) getTok
..\project\nim-lang\Nim\lib\pure\pegs.nim(1685, 13) Error: index out of bounds
```

**Comment by gemath** [comment]
This should probably be closed. The following works as a NimScript now:

```Nim
import pegs

var mypeg {.compileTime.} = peg"'xyz'"

static:
  echo find("xyz", mypeg)
```

With `mypeg` defined as a `const` instead, we get

``Error: invalid type for const: Peg``

which may be an unrelated error.

**Comment by Araq** [comment]
The "unrelated error" is the expected behaviour.
