### ISSUE TITLE
debugger:native is currently unusable, coupled with gc and types diagnostics

### ISSUE THREAD

**Issue by sinkingsugar** [nim-lang/Nim#9013]
`cpp` backend
just adding a `--debugger:native` will result in `multiple definition of nimTypeRoot`

Really we need a test for those critical things. Cpp should be more tested before any serious release.

I suspect that the fix or work related to #8964 messed up things a bit.
adding `importc` to the `nimTypeRoot` var to make it extern in every compiled modules var and emitting a global `nimTypeRoot` somewhere fixes it.

**Comment by LemonBoy** [comment]
Here's your patch:
```nim
when defined(nimTypeNames):
  when declared(ThisIsSystem):
    var nimTypeRoot {.compilerProc.}: PNimType
  else:
    var nimTypeRoot {.importc.}: PNimType
```

**Comment by sinkingsugar** [comment]
That was quick! thank you @LemonBoy
