### ISSUE TITLE
Gendepend breaks on pkg/[mod1, mod2] imports

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/Nim#9022]
```nim
import sdl2/[mixer, audio] # invalid module name: [mixer, audio]
```

Relevant lines:

https://github.com/nim-lang/Nim/blob/9995f50050298dc435a237b29dd0ff258ba25b9b/compiler/depends.nim#L37-L40

**Comment by LemonBoy** [comment]
Works fine on `devel`.
