### ISSUE TITLE
FutureStream misbehaviour

### ISSUE THREAD

**Issue by dm1try** [nim-lang/Nim#9024]
completion of a stream, while some data is still being read, leads to missing chunks in the reading

test example:
```nim
# tfuturestreams.nim
import asyncdispatch

var stream = newFutureStream[string]()

proc test_future_stream() {.async.} =
  await sleepAsync 1 # make sure that callbacks are scheduled and are not called directly,
                     # see asyncfutures.callSoon implementation

  for _ in 0..5:
    await stream.write("x")

  var read_future = stream.read_all()
  stream.complete()
  yield read_future
  let data = read_future.read()
  assert(data.len == 6, "actual data len = " & $data.len)

waitFor test_future_stream()
```

real reproducible case in #8994, see [this comment](https://github.com/nim-lang/Nim/issues/8994#issuecomment-423281323) for more info

**Comment by dom96** [comment]
I'm going to fold this into https://github.com/nim-lang/Nim/issues/7126

**Comment by dm1try** [comment]
#7126 looks like one of the cases there `producer/consumer` queue can be used

even though `FutureStream` was bootstrapped for solving that particular thing, the current issue shows that `producer/consumer` queue has a broken implementation and anyone who will try to use it as a synchronization primitive could meet the same problem.
