### ISSUE TITLE
Deprecate and remove MD5 from stdlib

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#9037]
It should not be actively used except for legacy purposes.

Three test dependencies I found are `tests/testament/`, `tests/deps/jester-#head/`, and `tests/manyloc/keineschweine/`, of which the first two straightforwardly can be switched to `std/sha1`, which is at least somewhat better. `tests/manyloc/keineschweine/` seemsto have MD5 baked more deeply in, but that in no way warrants continued support of this hazardous cryptographic hash.

Ideally, before 1.0, https://github.com/nim-lang/Nim/issues/7337 allows switching to a modern cryptographic hash, such as SHA2 or SHA3, while remaining in the stdlib. That Nim has in its stdlib two cryptographic hashes, MD5 and SHA1, which are both broken, while not having any currently secure cryptographic hashes, is worse than either having none or having only secure cryptographic hash functions.

**Comment by zielmicha** [comment]
I agree that SHA2 should be added to stdlib, but MD5 should not be removed due to legacy reasons.

Also, MD5 is not hazardous for all purposes - for example, HMAC-MD5 is still safe. Or other, non-cryptographic uses of MD5 (e.g. replacing CRC32 as checksum algorithm).

**Comment by Araq** [comment]
It's a fight we can only lose, crypto changes all the time, SHA-2 might become deprecated too. I think it's fine to keep outdated algorithms in the stdlib, existing protocols may require them. Don't patronize our users, everybody should know by now that security in computing is a terrible joke to begin with.

**Comment by mratsim** [comment]
Lots of website that offer downloads are giving a MD5 hashes. While you can forge the hash, it's still good enough and if more is wanted one can always use signed packages.

**Comment by Araq** [comment]
Sorry, not gonna happen.
