### ISSUE TITLE
Awesome language guys!

### ISSUE THREAD

**Issue by NaymanHohnheimer** [nim-lang/Nim#9038]
Hello there! My name is Nayman(she/her), and I was looking around for cool new open source projects that might need a bit of 'councelling' in diversity and inclusivity (I'm not really a programmer haha).   

I saw that there was a pushback to adding a Code of Conduct recently. I think we all know why this is. I have seen a lot of toxicity in the community while skimming through the forum and repo. There sure are a lot of, to say it mildly, alt-right speaking folks on board. They probably don't want to ackowledge their privilege in realation to other minority groups, especially in the tech field. Adding a code of conduct (i recommend the Contributor covenant, written by the lovely Coraline Ehmke) will allow you to remove such toxic people from the community for good. Some people might be good programmers, and they might contribute the code, but they are in they might impact it negatively by making the community an unwelcomming place for people of color and sexual minorities. It is just as important, if not more, to have people skills, than it is to know programming, so I implore you to skim through the CoC and even the post-meritocracy manifesto: https://www.contributor-covenant.org/  and  https://postmeritocracy.org/  
If you disagree, don't close the issue, but discuss it with me :)

Thanks for reading!

P.S.
When reviewing the project's code I saw the phrase Master/Slave... This kind of terminology can lead to awkwardness and overall is dated terms. Don't you think we can do a little better? What I propose is something like Python just did, which was AMAZING of them. I feel like by keeping this we are excluding and not including everyone. Waiting to hear your thoughts...

**Comment by slammerhammer** [comment]
I completely agree with you. Toxicity has absolutely no place in open-source communities and the outdated terms that I dare not to repeat should be replaced by more friendly terms

**Comment by Clyybber** [comment]
To the troll that operates the accounts @NaymanHohnheimer @slammerhammer @NaamanIskowitch:
Please stop. You are not gaining anything from doing this.

**Comment by NaymanHohnheimer** [comment]
Thank you, and I agree!
Here are some suggestions:
- replace enabled with traditionally_abled 
- replace disabled with differently_abled (or just remove the terms completely)
- replace blacklist with do_not_accept_list
- replace whitelist with do_accept_list
- remove any instances of the numbers '14' and '88' (for obvious reasons)

There are hundreds more, but even just these will make the project a much more welcoming place for various ethnic minorities that might bring their experiences here.



> To the troll that operates the accounts @NaymanHohnheimer @slammerhammer @NaamanIskowitch:
> Please stop. You are not gaining anything from doing this.

This is the kind of reactionary thinking that I am talking about. Whenever someone tries to get rid of the problem, they are accused of being an SJW. Basic decency isn't SJW.

**Comment by SwapnillTek** [comment]
> Thank you, and I agree!
> Here are some suggestions:
> 
> * replace enabled with traditionally_abled
> * replace disabled with differently_abled (or just remove the terms completely)
> * replace blacklist with do_not_accept_list
> * replace whitelist with do_accept_list
> * remove any instances of the numbers '14' and '88' (for obvious reasons)
> 
> There are hundreds more, but even just these will make the project a much more welcoming place for various ethnic minorities that might bring their experiences here.
> 
> > To the troll that operates the accounts @NaymanHohnheimer @slammerhammer @NaamanIskowitch:
> > Please stop. You are not gaining anything from doing this.
> 
> This is the kind of reactionary thinking that I am talking about. Whenever someone tries to get rid of the problem, they are accused of being an SJW. Basic decency isn't SJW.

differently_abled is genius. I like it. should be implemented immediatley

**Comment by NaymanHohnheimer** [comment]
Thank you! I am trying, but there is obviously some pushback from the more problematic guys :(

**Comment by hlaaftana** [comment]
This language has been around for 10 years, why choose now to pull crap like this?

**Comment by NaymanHohnheimer** [comment]
NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

NOT ADDING THE CONTRIBUTOR COVENANT TO THE PROJECT IS TRANSPHOBIC AND RACIST

Come on, do you really want to be seen by the twittersphere as the language of the far-right? Just add it

**Comment by spillednothing** [comment]
Wow so passionate and progressive, my startup needs more people like you

**Comment by NaymanHohnheimer** [comment]
> Wow so passionate and progressive, my startup needs more people like you

Thanks, I do free consulting, though I might be busy fixing the nim devs for a while haha

**Comment by x1040** [comment]
This should be apparent to everybody by now, but @NaymanHohnheimer is a troll.

Look at their username: "NaymanHohnheimer", and what is written on their profile: "Naiman HohnHeimer"

![image](https://user-images.githubusercontent.com/43506674/45922728-3e4f9500-be89-11e8-83c9-fe863192957e.png)

A real person wouldn't misspell their own name.

The picture is not even theirs: it is from a girl named Gabby Rose, featured in an article from 2012 (10th grade at the time): https://www.clevelandjewishnews.com/archives/program-for-teenage-jewish-girls-expands-in-cleveland/article_46530788-065b-11e2-88f8-0019bb2963f4.html I don't see a reason why anybody would use a 6 year old picture of themself as a teenager

The only significance of the picture is that it shows up with the first 15 results for most search engines when searching "jewish girl". 

Google: 
![image](https://user-images.githubusercontent.com/43506674/45922679-b452fc80-be87-11e8-9306-09d6d4042c0b.png)

DuckDuckGo:

![image](https://user-images.githubusercontent.com/43506674/45922683-c59c0900-be87-11e8-951f-af3046efcb9b.png)
 

The same goes for @SwapnillTek with a picture stolen from here: https://imgflip.com/memetemplate/37670347/Lazy-Indian-Programmer, easily findable by searching for "lazy Indian programmer" in a search engine



It should be obvious from looking at @NaymanHohnheimer, @SwapnillTek, @NaamanIskowitch, and @slammerhammer's issue history that this is not a serious attempt at contributing to a project, but just people that are trying to raise conflict in as many open-source communities as possible. Even more suspicious is the fact that they were all created today or yesterday. I have reason to believe that this all one person that thinks they're doing something funny.


My recommendation is that this post are locked as spam, and the users mentioned be banned from this repo, if possible.

**Comment by enthus1ast** [comment]
@NaymanHohn why do you do this kinda cr*p? Why do you disturb people that actually DO stuff? People that tries to make the world a better place? What have you build and shared with the world (for free)? What have you archived? I bet nothing. Go and cry yourself to sleep.

**Comment by dom96** [comment]
Do not humour trolls please.
