### ISSUE TITLE
Cannot explicitly instantiate generic templates and macros with static parameters

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9040]
* proc allows calling `proc fun*[N: static int](): auto =` with `fun[2]` but not macro or template
* case2b is fishy as `N:int` syntax accepts both 2 and int

```nim
import std/macros

when defined(case1):
  # Error: type expected
  macro fun*[N: static int](): untyped =
    # 1 # original bug report
    newLit 1 # EDIT

  const a = fun[2]()

when defined(case2):
  # compiles: ok
  proc fun*[N: static int](): auto =
    1
  const a = fun[2]()

when defined(case2b):
  # compiles, but this exposes an ambiguity in `N:int` syntax as it accepts both 2 and int
  proc fun*[N: int](): auto =
    1
  const a = fun[2]()
  const a2 = fun[int]()

when defined(case3):
  # Error: type expected
  template fun*[N: static int](): untyped =
    1
  const a = fun[2]()

when defined(case3b):
  # Error: type expected
  template fun*[N: int](): untyped =
    1
  const a = fun[2]()
```

**Comment by zah** [comment]
"regular" static params don't have this problem though, so you can work-around with:

```nim
template fun*(n: static int): untyped = 1
```

**Comment by exelotl** [comment]
This bit me yesterday, makes it hard to use templates for a generic fixed-point arithmetic API.
```nim
var n = toFixed[int32,5](3.142)  # new fixed-point number with 5 fractional bits
```

**Comment by metagn** [comment]
Still an issue, now says "expected type, but got: 2".

Culprit:

https://github.com/nim-lang/Nim/blob/f1789cc465bcabc7afe0fe991df615246cfadb3b/compiler/semexprs.nim#L1068

Somewhat related case, also caused by `setGenericParams`:

```nim
proc newSeq[x: static int]() = echo x

template foo =
  newSeq[123]()

foo()
```

This time caused by this line:

https://github.com/nim-lang/Nim/blob/f1789cc465bcabc7afe0fe991df615246cfadb3b/compiler/semexprs.nim#L3177
