### ISSUE TITLE
Openarray of openarrays: Generic version compiles but not "normal"

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9041]
The following compiles

```Nim
func foo[T](x: openarray[openarray[T]]): T =
  x[0][0]
```

but the following throws
```Nim
func foo(x: openarray[openarray[int]]): int =
  x[0][0]
```
` Error: invalid type: 'openarray[int]' in this context: 'proc (x: openarray[openarray[int]]): int{.noSideEffect.}' for proc`

**Comment by krux02** [comment]
I migrate this issue to my own issue.
