### ISSUE TITLE
RACIST NAZI BIGOTS 

### ISSUE THREAD

**Issue by Sooja** [nim-lang/Nim#9048]
REMOVE THE TERMS SLAVE AND MASTER BEFORE I REPORT YOU ON GITHUB

**Comment by TimothyBergher** [comment]
I tried warning them. Bunch or fascists they are, wont even accept the Contributor Covenant

**Comment by TimothyBergher** [comment]
READ THIS AND ASK YOURSELVES IF YOU ARE ON THE RIGHT SIDE:
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/

**Comment by TimothyBergher** [comment]
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/
https://postmeritocracy.org/

**Comment by TimothyBergher** [comment]
READ IT
