### ISSUE TITLE
Misleading "processing <modulename>" for long compile-time evaluations

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#9052]
When compiler processes macros/`static:`,
possibly for significant time (up to infinity),
the last message in the console remains about processing the last processed module.
That module to that moment is already successfully processed and has nothing to do with the current delay,
but for the user it looks likes that module's processing hangs the compiler;
and anyway it looks the very intention of those "processing ..." messages is to see what's going on
and what causes problems, if any, in such case it misleads.

```nim
import strutils
macro x: untyped =
  for i in 0..30000000: # adjust the number to your computer's performance to see the effect :)
    discard
x()
```

**Comment by Araq** [comment]
The [Processing] is emitted before the semantic checking pass, so it's technically correct and outputs it as soon as the processing starts. However, imports are processed and also produce [Processing] messages and there are no [Processing end] messages.

**Comment by Leu-Gim** [comment]
These absent "processing end" are what I meant. Just some " Done." at the same line would be enough and almost not increasing verbosity.

**Comment by krux02** [comment]
I don't see a problem here.
