### ISSUE TITLE
openFileStream missing

### ISSUE THREAD

**Issue by peheje** [nim-lang/Nim#9063]
The stream documentation refers to a "openFileStream" function, but the source refers to a "discard" line. https://nim-lang.org/docs/streams.html

**Comment by alaviss** [comment]
That is because @Araq ran the doc generator on `devel` IIRC, 3 commits after release, one of which contains `openFileStream`.

The implementation can be found here: https://github.com/nim-lang/Nim/blob/2870ca5d717996d8451282de56c20418c89162a9/lib/pure/streams.nim#L446

**Comment by peheje** [comment]
Cool. Thanks for the update.

tir. 25. sep. 2018 01.59 skrev alaviss <notifications@github.com>:

**Comment by Araq** [comment]
Fixed by the release of 0.19.
