### ISSUE TITLE
Closures containing types with destructors cause compiler error

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#9064]
The following fails [this assertion](https://github.com/nim-lang/Nim/blob/548fc778c9b7048f474bf53c5d665bb8425e3343/compiler/destroyer.nim#L363) (`v.kind == nkSym`):
```nim
type Foo = object

proc `=destroy`(self: var Foo) = discard

proc bar() =
  var foo: Foo
  discard proc() = discard foo

bar()
```
since `foo` becomes a `nkDotExpr` (`:env.foo1`).

**Comment by Araq** [comment]
Extensive closure usage means you're not using enough templates. :-)

**Comment by jwollen** [comment]
Seems to be fixed
