### ISSUE TITLE
floating point modulo/remainder not available at compiletime (and in the VM)

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#9066]
```nim
import math

static:
  echo 5.0 mod -3.0
```
produces:
`Error: cannot 'importc' variable at compile time`

I know that `fmod`  is available to compute the floating point remainder at compiletime and in the VM. But `fmod` has been deprecated. 

The following simple implementations of `mod` and `floorMod` wouldn't cause any problems at compiletime and in the VM:
```nim
proc `mod`(x, x: float): float =
  x - trunc(x / y) * y
proc floorMod(x, y: float): float =
  x - floor(x / y) * y
```

**Comment by GULPF** [comment]
Fixed by #9591
