### ISSUE TITLE
[docgen] Show the commit used to generate the devel docs

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9073]
Right now, the devel docs ( https://nim-lang.github.io/Nim/ ) show just the Nim version. But it is not granular enough for devel docs.

Instead of just:

> **Version** 0.19.0

Can that be changed to something like below?

> **Version** 0.19.0 ( [4b2f0035](https://github.com/nim-lang/Nim/tree/4b2f0035007d4060dd16279c8c5e49c0cfb3b8f7) )

Ref: https://github.com/nim-lang/Nim/pull/8992#issuecomment-422356433

**Comment by kaushalmodi** [comment]
@timotheecour 

Ref: https://github.com/kaushalmodi/std_vector/issues/6#issuecomment-636280871

> I'm working on a PR to add git hash+dirty bit at which nim doc were run

You can tag to close this issue in that PR.

**Comment by narimiran** [comment]
Devel docs show the date at the bottom. IMO, that should be granular enough for most users.
