### ISSUE TITLE
Redefinition error at C side for system modules non-exported compilerproc objects

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#9075]
```nim
type TGenericSeq {.compilerproc.} = object # compiles w/o `compilerproc`
# further needed probably just for declaration not being ignored
var s: TGenericSeq
echo s.repr
```
Gives from MinGW `error: redefinition of 'struct TGenericSeq'`.

**Comment by Araq** [comment]
So? Where do we claim you're free to use ``.compilerproc`` on your own stuff?

**Comment by Leu-Gim** [comment]
Nowhere, but it compiles, producing wrong C sources - should fail instead at Nim side?

**Comment by Araq** [comment]
It's like using ``.exportc: "foo"`` twice and expect a meaningful result. It doesn't work this way.
