### ISSUE TITLE
ksywka

### ISSUE THREAD

**Issue by sp00ck** [nim-lang/Nim#9077]
-  Czy  jest szansa dodania ksywki dla funkcji w obiekcie?
coś jak jest w Ruby alias_method po prostu pewna metoda mogła by się nazywac na dwa sposoby. 
- Brakuje mi literałów z Ruby, czyli pewnych wartości, które sa niezmienne i unikalne w skali całego programu. coś jak `:test ` 
- W jaki sposób mozna dodac biblioteke w C?

**Comment by andreaferretti** [comment]
This is what I get from google translate, to save other people time:

# nickname

* Is there a chance to add a nickname for a function in the object? something like in Ruby aka method simply a method could be called in two ways.
* I miss the Ruby literals, i.e. certain values that are unchanging and unique in the scale of the entire program. something like: test
* How can I add a library in C?

**Comment by Araq** [comment]
This is silly, who knows if the OP will be able to understand our response.

**Comment by dom96** [comment]
Thankfully we've got a couple of Polish developers among us. My Polish is rusty and I'm too lazy to use accents, but let me give it a shot :)

----

* Nie ma, ale mozesz napisac `macro` ktory pozwoli takie cos zrobic. Nawet to by byl dobry pierwszy macro dla kogos kto nigdy nie uzywal ich w Nim.

* O tym to ja nie wiem. Nie uzywalem Ruby duzo wiec nie wiem do konca jak ``:test`` dziala. Ale cos podobnego napewno da sie zrobic. Nim jest bardzo elastyczny :)

* http://rosettacode.org/wiki/Call_a_foreign-language_function#Nim

**Comment by sp00ck** [comment]
second point

alias for method of object
object.printok()
alias printok to okprint
object.okprint() is good method and this same than above

in my opinion this must be implemented in language
