### ISSUE TITLE
[docgen] The search box is not working on devel docs

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9080]
To reproduce the issue:

- Visit https://nim-lang.github.io/Nim/tut1.html
- Type anything in the search box, like "proc". Nothing will show up.

Also the browser inspector (Ctrl + Shift + I) shows these errors:

```
Loading failed for the <script> with source “https://nim-lang.github.io/dochack.js”. tut1.html:1202
ReferenceError: search is not defined[Learn More]
tut1.html:1:1
onkeyup
https://nim-lang.github.io/Nim/tut1.html:1:1
```

**Comment by kaushalmodi** [comment]
I confirm that this issue exists only on the docs deployed from devel branch. The stable release docs (like the recent 0.19.0 docs have functioning search. Example: Search works fine on https://nim-lang.org/docs/tut1.html ).

So the search is basically broken for folks who build docs locally.

**Comment by kaushalmodi** [comment]
Of course it does! I fixed it in a PR but forgot to reference this commit 😛

Thanks for the ping.

**Comment by timotheecour** [comment]
hah! thanks for fixing it then :)

**Comment by timotheecour** [comment]
however take a look at https://github.com/nim-lang/Nim/issues/9198 ...

**Comment by kaushalmodi** [comment]
I've just fixed the script placement for dev docs in that commit. I don't know JS at all. So I've pinged the author of the fuzzy search logic in that issue.
