### ISSUE TITLE
`jsondoc` generates HTML file with JSON content

### ISSUE THREAD

**Issue by dm1try** [nim-lang/Nim#9081]

**Comment by 0xACE** [comment]
I'm currently meddling with `jsondoc` and have encountered this issue.

I'm curious, what should we expect it to generate? Should it print out the RST format as is?

**Comment by Araq** [comment]
We already have the output in a full tree format, it's called HTML.

**Comment by timotheecour** [comment]
@dm1try when you close, please add a comment; here I'm assuming it's: closed as duplicate of https://github.com/nim-lang/Nim/issues/11953
