### ISSUE TITLE
Regression: overriding streams.write(T) does not work on 0.19 anymore

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#9091]
```nim
import streams

type Mine = ref object
  a: int

proc write*(io: Stream, t: Mine) =
  io.write("sure")

let str = newStringStream()
let mi = new Mine

str.write(mi)
```
On 0.18, this works as expected (it prints "sure").
0.19 fails with:

```
test.nim(12, 11) Error: type mismatch: got <Mine>
but expected one of:
proc `$`[T: tuple |
    object](x: T): string
proc `$`(x: bool): string
proc `$`[T](x: set[T]): string
proc `$`(x: uint64): string
proc `$`(x: float): string
proc `$`(x: char): string
proc `$`[T](x: openArray[T]): string
proc `$`[Enum: enum](x: Enum): string
proc `$`(x: int): string
proc `$`(w: WideCString; estimate: int; replacement: int = 0x0000FFFD): string
proc `$`(s: WideCString): string
proc `$`[T, IDX](x: array[IDX, T]): string
proc `$`(x: string): string
proc `$`(x: cstring): string
proc `$`[T](x: seq[T]): string
proc `$`(x: int64): string
```

**Comment by LemonBoy** [comment]
Quoting the manual here:

> An empty subscript [] notation can be used to derefer a reference, the addr procedure returns the address of an item. An address is always an untraced reference. Thus the usage of addr is an unsafe feature.

And:

> The . (access a tuple/object field operator) and [] (array/string/sequence index operator) operators perform implicit dereferencing operations for reference types:

Moreover:

> Automatic dereferencing is also performed for the first argument of a routine call. But currently this feature has to be only enabled via {.experimental: "implicitDeref".}:

And since:

```nim
type Mine = ref object
  a: int
```

This means that

```nim
str.write(mi)
```

won't work and you have to:
- Introduce a deference `mi[]`
- Add `"implicitDeref"` to your file

The title of the ticket is completely off the track though.

**Comment by demotomohiro** [comment]
I Added proc ``$`` for type ``Mine`` to that code, and that was compiled without err.
But proc ``$`` for ``Mine`` was never called.

```nim
  import streams

  type Mine = ref object
    a: int

  proc `$`(t: Mine): string = "Not sure"

  proc write*(io: Stream, t: Mine) =
    io.write("sure")

  let str = newStringStream("      ")
  let mi = new Mine

  str.write(mi)
  str.setPosition 0
  echo str.readAll
```

I think problem is, varargs's second parameter ``$`` proc of following proc from streams module was tried to match ``Mine`` and that caused compile error even if that proc was not called when ``proc `$`(t: Mine)`` is defined.

```nim
  proc write*(s: Stream, args: varargs[string, `$`])
```

Here is sample code that cause same kind of error:

```nim
  type
    AObj = object
      x: int

  # if this proc was defined, this code can be compiled without error and print "test AObj"
  #proc foo(a: AObj): string = ""
  proc foo(a: int): string = ""

  proc test(args: varargs[string, foo]) =
    echo "varargs"

  proc test(a: AObj) =
    echo "test AObj"

  let x = AObj()
  test(x)
```

I think this problem is related to "Substitution failure is not an error" (SFINAE) in C++.

**Comment by niv** [comment]
Sorry about the lack of clarity w.r.t. ref, @LemonBoy. I just took this example from a existing codebase, and there it works with the ref type in place. But the example behaves the same without the type being ref. 0.19 fails to compile the call to this write proc, 0.18 picks it up correctly.

**Comment by ringabout** [comment]
It works since Nim v1.2.0.
