### ISSUE TITLE
Regression: 0.18 code with mapIt() fails to compile on 0.19

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#9093]
```nim
import strutils, sequtils

let inp = "a:b,c:d"

echo inp.split(",").mapIt(it.split(":"))
```
This used to work on 0.18 (output: @[@["a", "b"], @["c", "d"]])

0.19 fails with:

```
test.nim(5, 20) template/generic instantiation from here
../.choosenim/toolchains/nim-0.19.0/lib/pure/collections/sequtils.nim(690, 19) Error: type mismatch: got <seq[string]> but expected 'string = Alias'
```

**Comment by kaushalmodi** [comment]
Calling all the recent authors of `mapIt`:

- @timotheecour  ed9fd2b63cde3b82dac26bbe9f92634cfd009884
- @LemonBoy 32b62097a2636c5053d842939d34e2a0fa3f9e33
- @skilchen 9bacdd64c1a30ab77d2701f877262f8f7c164c36

**Comment by LemonBoy** [comment]
Not much of a regression here, for some reason iterators are preferred to procedures in `type()` expressions (#8901 comes to mind) and that's enough to confuse our simple-minded `mapIt`.

In the following snippet:
```nim
  type outType = type((
    block:
      var it{.inject.}: type(items(s));
      op))
```
Where `op` is `it.split(":")` the compiler picks the `split` iterator that returns `string` instead of the `split` procedure that returns `seq[string]`.

**Comment by skilchen** [comment]
I only fixed a typo in in this procedure. Personally I would never use it.
You could try:
```nim
echo inp.split(",").mapIt(seq[string], it.split(":"))
```
to get the previous result, or
```nim
echo inp.split(",").mapIt(string, it.split(":"))
```
to get some kind of flatmap...

**Comment by kaushalmodi** [comment]
@skilchen what is the `mapIt(type, arg)` syntax?

About "flatmap", that's just a string representation of the sea, right? (Would be a pain to parse that I think).

This worked when I tried:

```
echo inp.split(",").mapIt($it.split(":"))
```

But the output of that won't be very useful.
