### ISSUE TITLE
[docgen] URL Encode chars like % in the URL

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9097]
Links like https://nim-lang.github.io/Nim/system.html#+%,IntMax32,IntMax32 should encode the non-alpha-numerical chars like `+`, `%` and `,`. And the same applies to many other similar chars in other links in the doc.

URL encoding ref: https://www.w3schools.com/tags/ref_urlencode.asp

Specifically the unencoded `%` char is causing an external tool `htmltest` to crash and is preventing me from testing link validity in the whole site: https://github.com/nim-lang/Nim/issues/8974#issuecomment-421579314

/cc @Araq

**Comment by LemonBoy** [comment]
Like this?
```patch
diff --git a/config/nimdoc.cfg b/config/nimdoc.cfg
index 96e91283a..ddaaaa1ee 100644
--- a/config/nimdoc.cfg
+++ b/config/nimdoc.cfg
@@ -38,7 +38,7 @@ doc.section.toc = """
 # * $seeSrc: generated HTML from doc.item.seesrc (if some switches are used).
 
 doc.item = """
-<dt id="$itemSym"><a name="$itemSymOrID"></a><pre>$header</pre></dt>
+<dt id="$itemSym"><a name="$itemSymOrIDEnc"></a><pre>$header</pre></dt>
 <dd>
 $desc
 $seeSrc
@@ -48,7 +48,7 @@ $seeSrc
 # Chunk of HTML emitted for each entry in the HTML table of contents.
 # See doc.item for available substitution variables.
 doc.item.toc = """
-  <li><a class="reference" href="#$itemSymOrID"
+  <li><a class="reference" href="#$itemSymOrIDEnc"
     title="$header_plain">$name<span class="attachedType" style="visibility:hidden">$attype</span></a></li>
 """
 
```

**Comment by kaushalmodi** [comment]
@LemonBoy That worked perfectly. Now I get links like `Nim/doc/html/system.html#%3E%3D%25.t%2Cuntyped%2Cuntyped`. Do you want to commit that?

**Comment by kaushalmodi** [comment]
@LemonBoy Actually hold off on committing this.. looks like the `id` in the target is not set with the encoded url.. testing more.

**Comment by Araq** [comment]
> @Araq Mind if I remove the name attribute altogether and just use the id attribute?

Not at all.

**Comment by kaushalmodi** [comment]
`theindex.html` seems to be not affected with this change in `nimdoc.cfg`.. I still find the literal `%` instances in *just* the `theindex.html`:

```
html/theindex.html
1392:          data-doc-search-tag="system: `%%`(x, y: int64): int64" href="system.html#%%,int64,int64">system: `%%`(x, y: int64): int64</a></li>
1394:          data-doc-search-tag="system: `%%`(x, y: IntMax32): IntMax32" href="system.html#%%,IntMax32,IntMax32">system: `%%`(x, y: IntMax32): IntMax32</a></li>
```

**Comment by kaushalmodi** [comment]
Adding back that `escapeLink` almost works except that there is mismatch in definition of what should be escaped between:

- `rstgen / escapeLink` used to generate theindex.html -- https://github.com/nim-lang/Nim/blob/de8cb0a1cf06d091dbe586fed85fb1cf904a33ac/lib/packages/docutils/rstgen.nim#L426-L434

- `uri / encodeUrl` used by `$itemSymOrIDEnc` in `nimdoc.cfg` -- https://github.com/nim-lang/Nim/blob/de8cb0a1cf06d091dbe586fed85fb1cf904a33ac/lib/pure/uri.nim#L48-L67

@Araq Should `rstgen.nim` just use `uri / encodeUrl` ?
