### ISSUE TITLE
0.19.0 --gc: destructors and --gc:v2 woes

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9117]
I was trying to confirm the new stack size of seq under different GCs ([destructors seems to keep length on the stack](https://github.com/nim-lang/Nim/blob/4f8cf945fb2dc9292af97a0b88eff658263d3325/lib/core/seqs.nim#L15-L23) contrary to [refcounted seq](https://github.com/nim-lang/Nim/blob/4f8cf945fb2dc9292af97a0b88eff658263d3325/lib/system.nim#L434-L440)) and had the following issue :

```Nim
# Test case
var a: seq[int]
echo a.sizeof
```

Default GC: 8

--gc:destructors: `../../../../.choosenim/toolchains/nim-0.19.0/lib/pure/typetraits.nim(41, 3) Error: undeclared identifier: 'runnableExamples'`
--gc:v2: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

```
$ nim -v
Nim Compiler Version 0.19.0 [MacOSX: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release
```

**Comment by Azyrael** [comment]
i get the same errors. this already happens when trying to compile an empty file.
trying to use boehm results in an error not finding the boehmgc.dll, while markAndSweap is marked by the compiler as no option for the gc.
the others work fine though(refc, none, regions)

**Comment by mratsim** [comment]
it's `--gc:markandsweep` and for Boehm I'm pretty sure you have to put one of those in your path: https://github.com/ivmai/bdwgc/wiki/Download

**Comment by narimiran** [comment]
Running with `--gc:v2` now produces `8`.

`--gc:destructors` has an unrelated error (which should be fixed before we can test it here)

**Comment by narimiran** [comment]
Update: `--gc:destructors` now produces `16`.

@mratsim can this be closed now?
