### ISSUE TITLE
[regression] ./koch tests: Error: overloaded 'readFile' leads to ambiguous calls (with ~/.config/nim/config.nims)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9120]
./koch tests r tests/stdlib/tbitops.nim
system/sysio.nim(388, 6) Error: overloaded 'readFile' leads to ambiguous calls

Note: `./koch tests r` fails with every file I tried
I'm on OSX

**EDIT** this happens only when ~/.config/nim/config.nims exists (even if it's empty)

**Comment by jangko** [comment]
cannot reproduce on windows, wsl, osx

**Comment by timotheecour** [comment]
tested it on a fresh repo using latest devel:
git rev-parse HEAD
2dfd09b1bef5c7d7dcba02b8c80856bce7aa685e

what revision did you use?

**Comment by Araq** [comment]
The CIs are green too and run ``koch tests``.

**Comment by jangko** [comment]
>what revision did you use?

2dfd09b1bef5c7d7dcba02b8c80856bce7aa685e

**Comment by timotheecour** [comment]
@araq @jangko after investigation this happens only when ~/.config/nim/config.nims exists (even if empty) ; I updated top-level msg

**Comment by Araq** [comment]
Told you I hate the config system. ;-)
