### ISSUE TITLE
ties are rounded differently on c and js backends

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#9125]
On the c-like backends ties (values exactly between 2 adjacent integers) are rounded "away from zero".
On the js backend ties are rounded toward positive infinity.
```nim
import math
echo round(-1.5)
```
produces `-2` on the c backend, but `-1` on the js backend.

**Comment by skellock** [comment]
That's interesting that the JS spec [calls that out](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round#Description) directly:

> If the fractional portion is exactly 0.5, the argument is rounded to the next integer in the direction of +∞. **Note that this differs from many languages' round() functions, which often round this case to the next integer away from zero**, instead giving a different result in the case of negative numbers with a fractional part of exactly 0.5.

Emphasis is theirs.

**Comment by skilchen** [comment]
Another rounding differenc:
In the stringification all backends round ties "away from zero", but
on the c backends Nim rounds ties to nearest even
on the js backend Nim rounds ties up or down according to the sign of the float.

```nim
import strutils
echo formatFloat(2.5, ffDecimal, 0))
```
produces `2.` on the c backend, but `3` on the js backend.
On the c backends we also have the enforced decimal point, which is missing on the js backend.

The `round` procedure never rounds ties to nearest even: `echo round(2.5)` produces `3.0` on all backends.
