### ISSUE TITLE
Test failures on 32bit Linux

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#9138]
Here is the test results: https://ptpb.pw/lqNr.html
 
Tested on OpenSUSE Tumbleweed i586. Only the C, C++ backends are tested.

**Comment by mratsim** [comment]
Apparently the ptpb.pw triggers Trojan alert on some PCs so here is a screenshot:

![2018-10-11_11-59-28](https://user-images.githubusercontent.com/22738317/46796842-dbe20a00-cd4d-11e8-97c3-4c50c9a90687.png)

**Comment by LemonBoy** [comment]
CC @GULPF 
Have a look at the `ttimes.nim` failure, the module does some `int64` to `int` conversions that trip the range checks on 32bit targets.

CC @krux02 
Have a look at the `tobject3.nim` and `tsizeof.nim` failures, it's probably a matter of changing of how the alignment is calculated for 32bit targets.

The remaining failures are out-of-order error messages (meh) and the `log(4.0, 3.0) == ln(4.0) / ln(3.0)` assertion in `math.nim` that doesn't trigger and probably has to be replaced with a epsilon comparison.

**Comment by krux02** [comment]
@LemonBoy It looks like the test from tsizeof is from before my merge. My implementation is not based on equal output anymore. Therefore I assume the test on tobject3 is not based on my current implementation of sizeof.

**Comment by alaviss** [comment]
@skilchen 

```
32 32 1.26185953617095947 1.26185953617095947 false
64 64 1.26185950714291484 1.26185950714291484 false
```

For both gcc 8.2.1 and clang 7.0.0, on OpenSUSE Tumbleweed i586

**Comment by skilchen** [comment]
Ok, this invalidates my assumption that recent 32bit versions of gcc or clang would give better results in this case. Now my proposal to fix the currently failing test in `math.nim` would be to apply the following patch:
```patch
diff --git a/lib/pure/math.nim b/lib/pure/math.nim
index f04cb50..2b65900 100644
--- a/lib/pure/math.nim
+++ b/lib/pure/math.nim
@@ -808,7 +808,9 @@ when isMainModule:
     doAssert floorMod(-8.5, 3.0) ==~ 0.5

   block: # log
-    doAssert log(4.0, 3.0) == ln(4.0) / ln(3.0)
+    let r1 = log(4.0, 3.0)
+    let r2 = ln(4.0) / ln(3.0)
+    doAssert r1 == r2
     doAssert log2(8.0'f64) == 3.0'f64
     doAssert log2(4.0'f64) == 2.0'f64
     doAssert log2(2.0'f64) == 1.0'f64
```
and let someone with a 32bit system verify that the `math.nim` test no longer fails using something like `nim c -r <path_to_nim>/lib/pure/math.nim`

**Comment by alaviss** [comment]
Seems to work here

**Comment by Araq** [comment]
They have all been fixed.
