### ISSUE TITLE
[appveyor] AppVeyor build failed even though nothing shown as failed in appveyor log

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9148]
in https://github.com/nim-lang/Nim/pull/9124 CI shows:
```
continuous-integration/appveyor/pr — AppVeyor build failed
```
link to job: https://ci.appveyor.com/project/dom96/nim/build/4987
says: Failed an hour ago in 1 hr

nothing in logs shows why it failed (eg, no `Failure:`) (even looking at complete logs downloaded)
(I saved a copy, if needed)

**EDIT** this just happened again in another PR:
https://github.com/nim-lang/Nim/pull/8711 https://ci.appveyor.com/project/dom96/nim/build/4988

**Comment by timotheecour** [comment]
related (but for travis):
* [travis] The job exceeded the maximum time limit for jobs, and has been terminated #8707

but here, logs don't mention anything about timing out

**Comment by kaushalmodi** [comment]
I think that Appveyor gets so desperate to fail the test that it doesn't even print the reason (and that is arbitrary too.. whether to print the reason or not).

This is the sign:

> Failed an hour ago in **1 hr**

**Comment by dom96** [comment]
There isn't much we can do about this except build out our own CI infrastructure. I doubt this will happen unless somebody has the time to do so.

I don't think keeping this open is helpful to anyone.
