### ISSUE TITLE
[Regression] converter to string leads fail to compile  on 0.19

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#9149]
```nim
type
  Container = ref object
    data: int

converter containerToString*(x: Container): string = $x.data

var c = Container(data: 123)
var str = string c
echo str

if c == nil: # this line can compile on v0.18, but not on 0.19
  echo "c is nil"

if not c.isNil:
  echo "c is not nil"
```

**Comment by Bennyelg** [comment]
yea, as the warning said already 
```compile with --nilseqs:on for a migration period```

**Comment by Araq** [comment]
This is a regression, ``nil`` is available for ``ref object`` and so the ``==`` should compile.

**Comment by krux02** [comment]
As a workaround ``if c.isNil:`` does work.

**Comment by Bennyelg** [comment]
is it really a valid to check if 
```nim 
something == nil
```
?

**Comment by krux02** [comment]
@Bennyelg yes it is valid to check is something is nil. It is just not valid to test if a ``string`` or a ``seq`` is nil. In this case it's the converter in combination with the implementation of the error message is causing the problem.

My recommendation is not to use converter. Write the conversion explicity.

**Comment by Bennyelg** [comment]
@krux02  The concept of Converters is new for me, looks like something which magnitude errors and exceptions.

**Comment by khchen** [comment]
> My recommendation is not to use converter. Write the conversion explicity.

I agree you. Don't use converter if it is not necessary. However, this code is part of my [winim/com](https://github.com/khchen/winim) , it depends on converter so that people can use COM object like a script langauge.

**Comment by narimiran** [comment]
> Don't use converter if it is not necessary. However, this code is part of my winim/com , it depends on converter so that people can use COM object like a script langauge.

Two lines below you have used `if not c.isNil:`, why can't you use `if c.isNil` in the place where `if c == nil` currently fails?
