### ISSUE TITLE
`nim js -d:nodejs main.nim` gives: `system.nim(1443, 7) Error: cannot 'importc' variable at compile time` with a config.nims

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9153]
```
nim js -d:nodejs bugs/js/t01_nodejs.nim
```
(from https://nim-lang.org/docs/backends.html)

gives:
system.nim(1443, 7) Error: cannot 'importc' variable at compile time`

even for empty nim file

**Comment by skilchen** [comment]
its the presence of the `config.nims` again ...

**Comment by timotheecour** [comment]
no error with
`nim js --skipParentCfg --skipUserCfg -d:nodejs bugs/js/t01_nodejs.nim`
so indeed, looks like having a config.nims causes issues.
https://github.com/nim-lang/Nim/issues/9120 could be related
