### ISSUE TITLE
`nim doc` on entry file fails with SIGSEGV in v0.19.0

### ISSUE THREAD

**Issue by citycide** [nim-lang/Nim#9155]
This occurs on both Windows (Win 10 x64) & Linux (Ubuntu 14.04 x64):

```shell
git clone https://github.com/citycide/glob.git
cd glob
nimble install
nim doc --project -o:htmldocs src/glob.nim
```

This creates the html file for local import `src/glob/regexer.nim`, then compiles `runnableExamples`, and finally fails having not created `htmldocs/glob.html` with:

`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

Running `nim doc` on the entry file alone fails the same way:

```shell
mkdir htmldocs # btw, can `nim doc` just create necessary directories?
nim doc -o:htmldocs/glob.html src/glob.nim
```

If I use v0.18.0, `--project` in the first command appears to do nothing and only `htmldocs/glob.html` is created, so I have to generate each local module's docs manually.

**Comment by timotheecour** [comment]
* did u try nim devel? IIRC some related SIGSEGV issues with nim doc were recently fixed
* what's the stacktrace with a nim built without -d:release (to show debug info)?

I can try it too in a bit if you don't have time

**Comment by citycide** [comment]
Ah yeah it seems to work in `devel` so I'll close this out.
