### ISSUE TITLE
Is this possible to turn Nim code into "Native C"?

### ISSUE THREAD

**Issue by midnio** [nim-lang/Nim#9164]
By meaning of "Native C" is something like coffeescripts transpiling. For a example
```nim
proc fact(n: int): int =
    if n == 1: 1 else: n * fact(n - 1)
```

to

```c
int fact(int n) {
    if (n == 1) {
        return 1
    }
    else {
        return n * fact(n - 1)
    }
}
```

Is this possible for nim transpiler?

**Comment by midnio** [comment]
I already haved a look, and they're based on nim C library.

**Comment by krux02** [comment]
with ``{.exportc.}`` you can control how a function is called in the generated C file. If your questions have been answered, can you close this issue then?

**Comment by midnio** [comment]
Ok, sorry.
