### ISSUE TITLE
Missing docstrings are replaced with other text

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#9169]
For example: https://nim-lang.org/docs/nre.html#replace%2Cstring%2CRegex%2Cproc%28string%29

> proc replace(str: string; pattern: Regex; subproc: proc (match: string): string): string {...}
>
>    "is greater" operator. This is the same as y < x.   Source Edit

**Comment by flaviut** [comment]
duplicate of https://github.com/nim-lang/Nim/issues/8872

**Comment by timotheecour** [comment]
close the original bug, it's not there anymore

devel docs: https://nim-lang.github.io/Nim/nre.html#replace%2Cstring%2CRegex%2Cproc%28RegexMatch%29

![image](https://user-images.githubusercontent.com/2194784/47740248-8dc97380-dc34-11e8-95b4-3d53a788a7a0.png)

stable docs published still have the problem, oh well... /cc @araq (the fix: just wait till 20.0 or use devel docs is good enough for me; I always prefer devel docs anyways)
https://nim-lang.org/docs/nre.html#replace%2Cstring%2CRegex%2Cproc%28string%29
