### ISSUE TITLE
Question - Can I send libraries my using Pull Request?

### ISSUE THREAD

**Issue by midnio** [nim-lang/Nim#9187]
I want to implement Python (built-in) libraries to Nim (stdlib). Can I send them using Pull Requests?

**Comment by midnio** [comment]
Or I need a permission to implement them (to create new libraries*).

**Comment by andreaferretti** [comment]
What do you mean exactly?

* A Nim library whose interface is similar to python stdlib? In this case you have something like [nimpylib](https://github.com/Yardanico/nimpylib), [nim-pythonfile](https://github.com/achesak/nim-pythonfile) and others
* A library to generate python bindings for Nim libraries? In this case, there is [nimpy](https://github.com/yglukhov/nimpy)
* A library to call python from inside Nim? In this case you can use [python](https://github.com/nim-lang/python) or the higher level [nim-pythonize](https://github.com/marcoapintoo/nim-pythonize)

In general, all these things can be implemented as external libraries published in Nimble, as in the case of the examples I posted above.

More generally, if you have something you think would be useful for the standard library, you can send a PR, no permission required. But of course it will be subject to discussion: it is not convenient to include everything in the stdlib, for reasons of quality, mantainance and evolving the language

**Comment by midnio** [comment]
I just want to implement itertools library to Nim because i find it useful.

**Comment by midnio** [comment]
So i can implement it without any permissions by sending pr, thanks. I want implement them because Python libraries are awesome.

**Comment by genotrance** [comment]
https://narimiran.github.io/itertools/ in case of overlap.

**Comment by midnio** [comment]
holy... Thank you :P

**Comment by midnio** [comment]
Actually it does not everyting Python's itertool can do
I'll try upgrade it.

**Comment by narimiran** [comment]
> Actually it does not everyting Python's itertool can do

Hey, I'm the author of the mentioned `itertools`.

I have neglected this library for some time, but I've started working on it again and since few hours ago we now have combinatoric iterators :)

As you have noticed, some of the iterators are still missing, but my plan was to include them sooner or later.

> I'll try upgrade it.

Send a PR when you do :)

**Comment by midnio** [comment]
Then where is the library repo?

**Comment by narimiran** [comment]
https://github.com/narimiran/itertools/

**Comment by midnio** [comment]
Ok, i find it.
