### ISSUE TITLE
[os] `removeFile(path)` also removes directories ; not documented

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9200]
mkdir /tmp/d01/foobar
```nim
removeFile "/tmp/d01/foobar" # succeeds, instead of throwing error (and fails if dir has non-empty contents)
```

the documentation mentions nothing about behavior on directories.

## proposal
* throw if `path` is a directory (whether empty or not)
* add an overload `removeDir(path: string, recursive = true)` to allow removing only empty directories, when `recursive=false` (throwing if not dir or not empty)

## note: file vs dir vs path
my understanding is that in most of nim, the following convention is used:
* file: a path corresponding to a file (excluding directories)
* dir: a path corresponding to a directory
* path: a path corresponding to a file or a directory

however this isn't always consistent (and places where it's inconsistent should be fixed)

**Comment by kaushalmodi** [comment]
I agree, I think `existsDir` should be used to check if arg is a dir, and if not, then throw an error if not.

**Comment by mcintyrechris** [comment]
I think the documentation should be updated, but the behavior should remain the same. If it is desired to change the behavior, this will probably break some really old code. As far as I can tell, this has been the behavior since the inception of the procedure.

**Comment by mcintyrechris** [comment]
Sorry, I misread the title as `removeDir` for some reason; I claim sleep deprivation. Ignore my previous "pull request".

**Comment by timotheecour** [comment]
@mcintyrechris  yes PR would be appreciated thanks!

**Comment by mcintyrechris** [comment]
@timotheecour Done, but I didn't create any tests for this `recursive` option yet as I'm not familiar with the test requirements. If someone wanted to add a PR to my downstream repo or something, I can add some tests.
