### ISSUE TITLE
Feature Request - Use "*" * n to replicate strings

### ISSUE THREAD

**Issue by midnio** [nim-lang/Nim#9238]
I love python's `"*" * 10` to replicate any string like `"Hello, Nim. " * 100`. Can we implement this to Nim?

**Comment by alexnask** [comment]
```nim
import strutils
proc `*` (s: string; n: Natural): string = repeat(s, n)

echo "*" * 10
```

**Comment by tim-st** [comment]
I'd like to have it too in `strutils` as an alias for `repeat`.
```nim
import strutils
proc `*`*(s: string | char, count: Natural): string = repeat(s, count)
```

**Comment by andreaferretti** [comment]
It is so easy to introduce an alias that I wouldn't bother putting it inot the stdlib. In any case, one can just write `"Hello, Nim".repeat(100)`. Otherwise we risk a proliferation of inconsistent operators

**Comment by Araq** [comment]
Sorry, but it's easy enough to have this shortcut in your own code.
