### ISSUE TITLE
nre returns "" instead of nil for missing matches

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#9243]
```nim
let ex2 = "foo".find(re("(?<foo>foo)(?<bar>bar)?"))
doAssert ex2.captures["bar"] == nil
```

In this example, captures cannot return nil as nil is used to represent the empty string. The distinction between "no match" and "empty match" is significant and useful when it comes to regular expressions.

**Comment by timotheecour** [comment]
other std libraries had the same issue after the not-nil string change.
what do you suggest for ease of migration?
https://github.com/nim-lang/Nim/issues/8638 would help assess impact of such change

**Comment by flaviut** [comment]
A possible option for nre might be to have `captures[]` throw an exception when attempting to access an undefined capture, and provide some sort of API to detect if a capture exists (e.x. `"foo" in captures` or `4 in captures`).

It'd still be necessary to figure out what the correct return type for `captures.toSeq` (and `captures.toTable`) would be, although there are still issues with nim-lang/RFCs#512 there. I'm leaning towards returning `seq[Option[string]]` there, but there might be some other way to do it.

**Comment by Araq** [comment]
Go for it.
