### ISSUE TITLE
"%NIM%/config/nim.cfg" is not being read

### ISSUE THREAD

**Issue by rivy** [nim-lang/Nim#9244]
`nim compile ...` is not reading the configuration file at "%NIM%/config/nim.cfg" (as it should be per the [documentation](https://nim-lang.org/docs/nimc.html#compiler-usage-configuration-files)).

```shell
C:>ver
Microsoft Windows [Version 10.0.17134.320]

C:>nim --version
Nim Compiler Version 0.19.0 [Windows: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release
```

**Comment by Araq** [comment]
Works for me, %NIM% here means Nim's installation directory.

**Comment by rivy** [comment]
@araq, thanks for the reply.

When defined as "the `nim` installation directory", yes, it finds a "nim.cfg" directory.

But that's not what "%NIM%/config/nim.cfg" means on windows. By defining it as "%NIM%/config/nim.cfg" (similar to "%APPDATA%/nim/nim.cfg" a bit later), the documentation is saying that the NIM environment variable controls where the nim.cfg files is located. But %NIM% is not used at all.

If you want to leave it as is, the documentation needs to be altered to point out the truth (eg, change it to something like "<NIM_INSTALL_ROOT>/nim/nim.cfg", or, my personal preference, actually implement the use of the NIM environment variable to allow flexibility in placing the system config file within the file system (defaulting to "NIM_INSTALL_ROOT" if NIM is null/missing).

**Comment by Araq** [comment]
This idea of allowing for a flexible "directory hierarchy" only to patch it via **flat** environment variables that lack this hierarchy (because it never works!) isn't what Nim uses.

**Comment by rivy** [comment]
I'm not sure what you mean by that... if you mean that you don't think environment variables are a good way of directing program access, I disagree. The community widely and successfully uses the [XDG Base Directory specification](https://wiki.archlinux.org/index.php/XDG_Base_Directory) and, in fact, you're using it here. In fact, IMO, you're being overly restrictive here by limiting it only to *nix platforms; I think it should be used regardless of platform to allow windows users access to the ability to define where they want their files to be placed and read.

But, in this case, if you don't want to implement the %NIM% indirection, just updating the documentation to say what is really going on would be fine.
