### ISSUE TITLE
getOccupiedMem Undocumented

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#9245]
`getOccupiedMem()` is completely Undocumented, at least a 1 line Documentation on the `proc` would make it appear on [TheIndex](https://nim-lang.org/docs/theindex.html) or [System](https://nim-lang.org/docs/system.html)
Simple to Fix. :sweat_smile:

**Comment by CNunezEng** [comment]
I will take care of this.

**Comment by demotomohiro** [comment]
``getOccupiedMem()`` is declared in lib/system.nim and it already has document.

This command generates lib/system.html but there is no ``getOccupiedMem()`` in this page.

```console
nim doc lib\system.nim
```

``getOccupiedMem()`` is declared under ``when not defined(nimscript) and hasAlloc:``.
I thought this ``when`` prevents this procedure's document.
I temporarily removed this ``when`` condition but ``getOccupiedMem()`` didn't appeared in the document.

I added following test procedure in lib/system.nim and ``testtest()`` appeared in the document.

```nim
proc testtest*(): int {.rtl.}
  ## Test test

proc testtest(): int {.rtl.} = 0
```

Then, I moved ``testtest()`` implementation to system/test.nim and added ``include "system/test.nim"`` in lib/system.nim.

lib/system.nim:
```nim
proc testtest*(): int {.rtl.}
  ## Test test

include "system/test.nim"
```

lib/system/test.nim:
```nim
proc testtest(): int {.rtl.} = 0
```

Then ``testtest()`` disappeared from document!
I changed ``testtest()`` to ``testtest*()`` in lib/system/test.nim, but it still didn't appeared in the document.

Like this ``testtest()``, ``getOccupiedMem()`` is declared in lib\system.nim and implemented in other file under lib/system directory (alloc.nim, gc_regions.nim, mmdisp.nim).
It seems like a bug of ``nim doc`` command.
This might be not simple to Fix.

**Comment by narimiran** [comment]
> `getOccupiedMem()` is completely Undocumented, at least a 1 line Documentation on the proc would make it appear on TheIndex or System

It has documentation: https://nim-lang.github.io/Nim/system.html#getOccupiedMem
and it has entry in the Index: https://nim-lang.github.io/Nim/theindex.html#getOccupiedMem
