### ISSUE TITLE
Cannot 'importc' variable at compile time with times library.

### ISSUE THREAD

**Issue by ajm113** [nim-lang/Nim#9247]
Hi, trying out Nim for the first time. Definitely loving everything, up until now, it seems like I'm experiencing an issue building my project the moment I started using `times` library.

### Code:

```
import times

proc getSafeUnixTime*(): int64 =
  result = toUnix(getTime())
```

### Build Command:

`nim c -d:ssl --app:console -o:bin/app --nimcache:./nimcache src/app`

### Error:

`lib/nim/pure/times.nim(1325, 5) Error: cannot 'importc' variable at compile time`

### Environment:

Nim Version: `0.18.0` -- Yes, I know I'm a version behind, but I didn't see any commits regarding this issue exactly in the change log as I'm aware of. (Using pacman atm)

- OS: Arch Linux x86_64
- Kernel: 4.18.12-arch1-1-ARCH
- CPU: Intel i7 950 (8) @ 3.068GHz
- Memory: 24094MiB

### What I tried:

- `sudo mv /usr/lib/nim/compiler.nimble /usr/lib/nim/compiler/`
- Skipping default configs when compiling.
- Delete nim cache.
- Reading issues that had a somewhat similar issue, but no success.

P.S: Any eta regarding the latest update to the Arch repo?

Thanks!

**Comment by ajm113** [comment]
Should just be a static block, I believe if I understand you correctly.

e.g of usage:
```
import utils/unixTimestamp

var timestamp = getSafeUnixTime()

# ...

```

**Comment by ajm113** [comment]
Can confirm issue exists on the latest build.

Steps:

1. `sudo pacman -R nim`
2. `cd /tmp && git clone https://github.com/nim-lang/Nim.git`
3. `cd Nim && sh build_all.sh`
4. Attempted to build project: `/tmp/Nim/bin/nim c -d:ssl --app:console -o:bin/app --nimcache:./nimcache src/app.nim`

Same error.

`/tmp/Nim/bin/nim --version`

```
Nim Compiler Version 0.19.0 [Linux: amd64]
Compiled at 2018-10-08
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 7cadb5a65d20a9c08d3bc1c9ab9f182b764e7364
active boot switches: -d:release
```

**Comment by Araq** [comment]
For now, can't reproduce.

**Comment by krux02** [comment]
I tried to reproduce on Arch Linux, no problem at all, your code sample compiles just fine.

**Comment by elbow-jason** [comment]
I can reproduce this issue with this simple example:

```nim
import system
import streams

proc myComptimeProc(): string =
  stderr.write("called myComptimeProc")
  "the error did not happen"

const myConst: string = myComptimeProc()

when isMainModule:
  echo(myConst)
```

On this version:
```
➜  no_stderr_at_comptime_error nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-12-15
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

The error:
```
➜  no_stderr_at_comptime_error nimble build --verbose
  Verifying dependencies for no_stderr_at_comptime_error@0.1.0
   Building no_stderr_at_comptime_error/no_stderr_at_comptime_error using c backend
  Executing /home/elbow-jason/.asdf/installs/nim/1.4.2/bin/nim c --colors:on --noNimblePath -d:NimblePkgVersion=0.1.0 -o:/home/elbow-jason/Workspace/nims/no_stderr_at_comptime_error/no_stderr_at_comptime_error /home/elbow-jason/Workspace/nims/no_stderr_at_comptime_error/src/no_stderr_at_comptime_error.nim
Hint: used config file '/home/elbow-jason/.asdf/installs/nim/1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/home/elbow-jason/.asdf/installs/nim/1.4.2/config/config.nims' [Conf]
.....
/home/elbow-jason/Workspace/nims/no_stderr_at_comptime_error/src/no_stderr_at_comptime_error.nim(8, 3) Error: cannot 'importc' variable at compile time; stderr
     Error: Build failed for package: no_stderr_at_comptime_error
        ... Execution failed with exit code 1
        ... Command: /home/elbow-jason/.asdf/installs/nim/1.4.2/bin/nim c --colors:on --noNimblePath -d:NimblePkgVersion=0.1.0 -o:/home/elbow-jason/Workspace/nims/no_stderr_at_comptime_error/no_stderr_at_comptime_error /home/elbow-jason/Workspace/nims/no_stderr_at_comptime_error/src/no_stderr_at_comptime_error.nim
```

**Comment by ghost** [comment]
@elbow-jason that's a different issue and I'm not sure if we could fix it - `stderr` is a file handle that is only available at runtime
