### ISSUE TITLE
Ugly error message when incorrectly trying to access a static variable inside a template

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9248]
```nim
template foo =
  static:
    let x = "foo"
  echo #[static]# x

foo()
```

> Error: execution of an external compiler program 'gcc -c  -w  -I/home/dawkot/.choosenim/toolchains/nim-0.19.0/lib -o /home/dawkot/.cache/nim/test_d/test.c.o /home/dawkot/.cache/nim/test_d/test.c' failed with exit code: 1
> 
> /home/dawkot/.cache/nim/test_d/test.c: In function ‘NimMainModule’:
> /home/dawkot/.cache/nim/test_d/test.c:136:22: error: ‘x_9bf4p1FLrvkXIchOKUUtCcw’ undeclared (first use in this function)
>   T1_[0] = copyString(x_9bf4p1FLrvkXIchOKUUtCcw);
>                       ^
> /home/dawkot/.cache/nim/test_d/test.c:136:22: note: each undeclared identifier is reported only once for each function it appears in

**Comment by ringabout** [comment]
First program produces better error messages since Nim v1.0

```
/usercode/in.nim(3, 9) Hint: 'x`gensym133006' is declared but not used [XDeclaredButNotUsed]
/usercode/in.nim(6, 4) template/generic instantiation of `foo` from here
/usercode/in.nim(4, 19) Error: undeclared identifier: 'x`gensym133006'
```

Second program compiles since Nim v1.0

```
(filename: "???", line: 0, column: -1)
```

This issue could be closed.
