### ISSUE TITLE
`--listFullPaths` not honored by `declared in foo.nim` messages

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9270]
"declared in pathto/foo.nim" should use absolute path when `--listFullPaths` is given as compiler option.
Currently I'm getting:
```
/pathto/foo.nim(62, 25) Error: ambiguous call; both ospaths.lastPathPart(path: string)[declared in ../../../Nim/lib/pure/ospaths.nim(409, 5)] and p_ospaths.lastPathPart(path: string)[declared in pending/p_ospaths.nim(27, 5)] match for: (string)
      let dirname = subdir.lastPathPart
```

* relative paths pointing to outside of current directory don't' make much sense either so one could also argue that these should be absolute even without `--listFullPaths` ; EDIT these are relative to a path in import path, not to current directory
* paths such as `pending/p_ospaths.nim` are shown relative to import path instead of relative to current directory, that makes them harder to search for in complex cases

At very least though,  `--listFullPaths` should make all these paths absolute

## reproducible example
main.nim:
```nim
include os
include osproc
```
gives:
```
/Users/timothee/git_clone/nim/Nim/lib/pure/osproc.nim(1258, 3) Error: redefinition of 'c_system'; previous declaration here: ../../../../Nim/lib/pure/os.nim(38, 5)
ls ../../../../Nim/lib/pure/os.nim
gls: cannot access '../../../../Nim/lib/pure/os.nim': No such file or directory
```
note that the relative path is not relative to current dir but to a path in the import path

**Comment by krux02** [comment]
Pleas fix the title, it's too long. I don't understand it. And what is with your tag `fix_in_progress`? Why does it use underscores? No tag uses underscores. By the way, when you are working on it, you can just assign yourself to it. You don't need a tag for that. Also when there is a PR for an issue, this is also visible in the issue, no need for a tag for that.

**Comment by timotheecour** [comment]
> Pleas fix the title, it's too long

done

> And what is with your tag fix_in_progress? Why does it use underscores? No tag uses underscores

done

> you can just assign yourself to it

done

> Also when there is a PR for an issue, this is also visible in the issue, no need for a tag for that.

that tag is still useful regardless since I can use that tag to filter search results and see what's already (or not yet) being worked on among a set of search results

btw, did you see https://github.com/nim-lang/Nim/pull/10054#issuecomment-451815745 ? for some reason I'm blocked from commenting on any issue/PR that was authored by you; if you want to avoid seeing notifications from me, there are more productive ways (including just asking me)

**Comment by krux02** [comment]
Well I was in a bad mood and I blocked you intentionally. But since you asked nicely I unblocked you again.
