### ISSUE TITLE
CompileTime

### ISSUE THREAD

**Issue by qqtop** [nim-lang/Nim#9273]
```
echo CompileDate, "   " ,CompileTime
```
seems to return UTC , which should be mentioned in the docs.

**Comment by eqperes** [comment]
#9283

**Comment by timotheecour** [comment]
side note: I kind of dislike `CompileDate` and `CompileTime` since these return string and are only useful for display, and don't interact well with std/times ; instead adding a proc to return UTC time (say, `int`,  in seconds) would be much more useful and flexible and inter-operable.

**Comment by alaviss** [comment]
Since #9283 is merged, this issue should be closed.
