### ISSUE TITLE
add sequence.none(predicate) to sequtils

### ISSUE THREAD

**Issue by jabbalaci** [nim-lang/Nim#9282]
In Kotlin, you can do the following ([doc](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/none.html)):

```kotlin
val isEven: (Int) -> Boolean = { it % 2 == 0 }
val zeroToTen = 0..10
println("zeroToTen.none { isEven(it) } is ${zeroToTen.none { isEven(it) }}") // false
println("zeroToTen.none(isEven) is ${zeroToTen.none(isEven)}") // false

val odds = zeroToTen.map { it * 2 + 1 }
println("odds.none { isEven(it) } is ${odds.none { isEven(it) }}") // true
```

In the module [sequtils](https://nim-lang.org/docs/sequtils.html), we have `all` and `any`, but `none` is missing. Let's see the following tests:

```nim
test "none":
  var text: string

  text = "HELLO THERE"    # no lowercase letter
  check text.none(isLowerAscii) == true
  text = "HELLo THERE"    # 'o' is lowercase
  check text.none(isLowerAscii) == false

test "noneIt":
  var text: string

  text = "HELLO THERE"    # no lowercase letter
  check text.noneIt(it.isLowerAscii) == true
  text = "HELLo THERE"    # 'o' is lowercase
  check text.noneIt(it.isLowerAscii) == false
```

`none` is actually `not any`, but it's easier to read IMO. You can read  `text.none(isLowerAscii)` like this: "in text, no character is lowercased".

If you agree to add it to sequtils, I can send a PR.

**Comment by Araq** [comment]
Sorry but no. ``none`` is not a good name for this and I don't like bloating ``sequtils`` further. Rejected, sorry.

**Comment by jabbalaci** [comment]
OK, no problem.
