### ISSUE TITLE
Exception doesn't clear result value

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#9286]
Test
```nim
import options
type Foo  = ref object
  i:      int

proc next(foo: Foo): Option[Foo] =
  try:    assert(foo.i == 0)
  except: return      # 2º: none
  return some(foo)    # 1º: some

proc test =
  let foo = Foo()
  var opt = next(foo) # 1º Some
  while isSome(opt) and foo.i < 10:
    inc(foo.i)
    opt = next(foo)   # 2º None
  assert foo.i == 1, $foo.i

test()
```
Result
```nim
`foo.i == 1` 10 [AssertionError]
```
Expected

The second time should return none, but `isSome(opt)` is always equals to true
***
```nim
>nim -v
Nim Compiler Version 0.19.0 [Linux: i386]
Compiled at 2018-10-09
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 72e15ff739cc73fbf6e3090756d3f9cb3d5af2fa
active boot switches: -d:release
```

**Comment by hlaaftana** [comment]
Are you compiling with -d:release? -d:release implies `--assertions:off` which stops `assert` from raising an exception. Use `doAssert` if you want it to work in release mode too.

**Comment by Wh1teDuke** [comment]
No, but it is not triggered in the playground. I will update my compiler and see if the issue persists.

**Comment by Araq** [comment]
This was a regression, introduced in 0.19, 0.18 doesn't have this problem.
