### ISSUE TITLE
missing top-level [source] [edit] links in all rst documentation files + at top-level of nim files

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9296]
* every module (eg foo.rst or foo.nim) that gets turned into docs should have a corresponding top-level [source] [edit] links, as found for individual symbols, eg like here:

![image](https://user-images.githubusercontent.com/2194784/46767116-d4acf480-cc98-11e8-9fe0-a4c8704de1d5.png)

* in some cases, eg https://nim-lang.github.io/Nim/macros.html you have to scroll a lot to see the 1st  [source] [edit] links; so adding a top-level one would remove barrier of entry for users to improve docs

* in some other cases, there are no [source] [edit] links at all, eg:
https://nim-lang.github.io/Nim/contributing.html

* Note: a single top-level [source] [edit] at the top of the html is not the correct approach, see for example cases like https://nim-lang.github.io/Nim/contributing.html where multiple source files end up in the html; in this case, 
doc/contributing.rst and doc/docstyle.rst

instead it should be the other way around: each source file yield a top-level [source] [edit] link, so that 2 [source] [edit] links would be shown for https://nim-lang.github.io/Nim/contributing.html  (the 2nd one starting at "Documentation Style" section)

**Comment by Araq** [comment]
These links are effectively unused and not worth putting more effort into. We got close to 0 PRs improving the docs after the ``[Edit]`` button's introduction.

**Comment by timotheecour** [comment]
I'm used this [Edit] links a number of times; having as low barrier of entry for PR's makes the difference between a user thinking:
* ok, I found a typo/doc issue / other simple issue, let me fix it since it's a click away
vs:
* nevermind, takes too much time to suggest an edit, I'll just leave the typo as is

**Comment by Araq** [comment]
Well I'm glad to hear that, that was its purpose.

**Comment by timotheecour** [comment]
fixed by https://github.com/nim-lang/Nim/pull/15642; remaining cases (source/edit links for include files) are covered in https://github.com/nim-lang/RFCs/issues/328
