### ISSUE TITLE
allow `import` inside `block`: makes N runnableExamples run N x faster, minimizes scope pollution

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9300]
## proposal

allow `import` statements inside a `block`, as in following code:
```nim
block:
  import os
```
It currently gives: `Error: 'import' is only allowed at top level`.

## rationale
* currently, `nim doc foo.nim` where foo.nim contains N `runnableExamples` blocks will generate N files and N compilations
I measured (on synthetic test cases; I can share code if needed) that running a single compilation+run on a file that concatenates N runnable tests runs **N times faster** than running the N runnable tests separately, since the overhead is almost always compilation step (+ overhead of starting a process etc). For N=50 (not unreasonable) that's a **50X speedup**.

As we improve our docs with more runnableExamples, this problem is gonna become more and more pressing. I often run into timeout issues on travis already (https://github.com/nim-lang/Nim/issues/8707), and appveyor is still taking often > 8 hours to process a build (https://github.com/nim-lang/Nim/issues/8640)

* allowing `import` inside a `block` can improve code health in a number of cases, avoiding symbol pollution and symbol clashes from too many top-level imports

* **EDIT** likewise with tests: this could be used for PR's like https://github.com/nim-lang/Nim/pull/9318 which refactors several tests into 1 file (again, for improving speed of running tests)

## Note
even if `.. code-block:: :test:` were used instead of `runnableExamples`, the exact same problem would be there (code is same underneath): the reason we're splitting runnableExamples into seperate files currently is to support `import` inside runnableExamples, which is needed for various reasons (eg allowing importing other modules inside a runnableExamples block without polluting the original module amongst other use cases, and making each runnableExamples independent scope-wise).

**Comment by Araq** [comment]
Terrible. Took D specialized scoping rules to recover from this feature.

**Comment by krux02** [comment]
From my experience with that feature in scala, I think it is not a good feature. When you have this feature, people will optimize "scope pollution" as you said it. But there isn't a real benefit to it, it's just a waste of time. Initially I did optimize this "scope pollution" but after I started using intellij which handles global imports automatically and I never had problems with it, I could dismiss local imports easily and never look back.

**Comment by timotheecour** [comment]
my proposal addresses the speed problem of running `nim doc` ; what else do you recommend ?

**Comment by krux02** [comment]
well I guess it is easy to support an import statement in the ``runableExamples`` block.

**Comment by Araq** [comment]
We can also only split the runnable examples into multiple files if different ``import`` statements are used.

**Comment by krux02** [comment]
Sounds like a good idea. But if it's done, It should be mentioned in the documentation of runnableExamples so that users have a chance to optimize the runnable examples to have identical imports.
