### ISSUE TITLE
compile error when "new object" with importcpp

### ISSUE THREAD

**Issue by shaoxie1986** [nim-lang/Nim#9303]
nim code is(main.nim):
```nim
{.emit: """
  class Foo{
  public:
    Foo()
    {
      i = 123;
    }
  private:
    int i;
  };
""".}

type
  FooPtr = ptr Foo
  Foo = object {.importCpp: "Foo".}

proc newFoo(): FooPtr {.importCpp: "new Foo(@)".}

let obj = newFoo()
```

-----------------------------------------------
compile with:
nim cpp main.nim

error is:
```
/home/xxxx/.cache/nim/main_d/main.cpp:1552:33: error: assigning to 'tyObject_Foo_74iaLl2c3KjmnnEwNiJXmA *' from incompatibletype 'Foo *'
        obj_504D06U7aNQiNeDY9b9bZDGw = new Foo();
```

nim version is:
0.19.1-dev

**Comment by alaviss** [comment]
You might want to wrap your code in ` ```nim ` block to avoid markdown "formatting" it.

**Comment by alaviss** [comment]
Anw, here is the fix

```nim
{.emit: """
class Foo{
public:
Foo()
{
  i = 123;
}
private:
  int i;
};
""".}

type
  FooPtr = ptr Foo
  Foo {.importCpp: "Foo".} = object

proc newFoo(): FooPtr {.importCpp: "new Foo(@)".}

let obj = newFoo()
```

`{.importcpp.}` has to be placed next to `Foo`, not `object`. I think the compiler should detect this and raise an error.

**Comment by shaoxie1986** [comment]
@alaviss thanks for reminding me the format

**Comment by shaoxie1986** [comment]
@alaviss and thanks, you code can compile

**Comment by ringabout** [comment]
`Foo = object {.importCpp: "Foo".}` is not valid syntax anymore, which gives `invalid indentation` on Nim 2.0.0
