### ISSUE TITLE
Regular Expressions: replacing empty patterns only works correctly in nre

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#9306]
Using [nre](https://github.com/nim-lang/Nim/blob/devel/lib/impure/nre.nim):
```nim
import nre
echo replace("bar", re"^", "foo")
echo replace("foo", re"$", "bar")
echo replace("foo", re"", "-")
```
produces:
```
foobar
foobar
-f-o-o-
```
as expected. 

Using [re](https://github.com/nim-lang/Nim/blob/devel/lib/impure/re.nim) instead:
```nim
import re
echo replace("bar", re"^", "foo")
echo replace("foo", re"$", "bar")
echo replace("foo", re"", "-")
```
each `replace` ends in an infinite loop.

And @nitely's [Module regex](https://nitely.github.io/nim-regex)
```nim
import regex
echo replace("bar", re"^", "foo")
echo replace("foo", re"$", "bar")
echo replace("foo", re"", "-")
```
produces:
```
foobfooafoor
fobarbarbarfoo
-f-o-o
```
which doesn't make much sense... But this is not a Nim issue.

**Comment by Araq** [comment]
Endless loops are just as fine here IMO, garbage in, garbage out.

**Comment by kaushalmodi** [comment]
I ended up on `re` `replace` entering an endless loop just yesterday, for a simple toy example:

```
import re 
echo replace("hello", re"$", "!") # hello!
```

**Comment by kaushalmodi** [comment]
> Endless loops are just as fine here IMO, garbage in, garbage out.

I didn't follow.

**Comment by skilchen** [comment]
@araq 
>Endless loops are just as fine here IMO, garbage in, garbage out.

Neither the empty string nor zero-length matches are garbage.
