### ISSUE TITLE
No obvious way to determine result types of overloaded procedures in code

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9325]
A simple fix could be a template like `any` in this example: 
```nim
template any(T: type): untyped = cast[T](0)

func identity(x: not string): type x = x

assert identity(any int) is int
assert identity(any float) is float
assert (not compiles(identity(any string)))
```

**Comment by mratsim** [comment]
Don't `cast` and don't call it `any`

The current way is to create `var`, apply the operation and return `type`. For example:

```Nim
template getResultType(call: untyped, T: typedesc): typedesc =
  var x: T
  type(call(x))

func identity(x: not string): type x = x

assert getResultType(identity, int) is int
assert getResultType(identity, float) is float
```

And straight from the standard lib https://github.com/nim-lang/Nim/blob/ef820769a47722cd33935dd94642aca9ecc09a8b/lib/pure/collections/sequtils.nim#L663-L679

I agree that it is not ideal and something in typetraits would be nicer.

**Comment by krux02** [comment]
too vague, not descriptive enough.
