### ISSUE TITLE
deprecation syntax inconsistent for objects, not possible for const/let/var

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9331]
* {.deprecated: "msg" .} works for routines/types but not for const/let/var:
```nim
block:
  # works
  const Foo {.deprecated.}  = 1

block:
  # Error: annotation to deprecated not supported here
  # const Foo {.deprecated: "bla".}  = 1
```

* deprecated for object type inconsistent all other deprecated forms:
for pretty much everything, `{.deprecated: "blabla".}` goes before the `=` but not for object type:
```nim
block:
  # object type: deprecated goes after `=`
  type Foo = object {.deprecated: "blabla".}
    a: int

block:
  # every thing else: deprecated goes before `=`: enum, routines, const/let/var
  type Foo {.deprecated: "asdf" .} = enum
    a
```

**Comment by alaviss** [comment]
This could have been separated to two issues, each with a small, not an essay title:

- deprecated pragma with annotation doesn't work for variables
- deprecated pragma is inconsistant for object type

Seriously, you should start minimizing your issue title to not scare people away, avoiding symbols might be a good start. Just my 2¢.

**Comment by timotheecour** [comment]
> Seriously, you should start minimizing your issue title to not scare people away, avoiding symbols might be a good start. Just my 2¢.

I understand your points and will keep in mind; there's a tradeoff between precision and conciseness; regarding symbols, `{.deprecated: "msg" .}` may make it easier to search (via `{.deprecated: "`) compared to `deprecated pragma with annotation` when searching with `in:title` but YMMV
likewise with grouping vs splitting related issues; in some similar past cases others were recommending grouping instead; so it's not completely obvious.
