### ISSUE TITLE
Code coverage stopped working in version 0.19.0

### ISSUE THREAD

**Issue by flenniken** [nim-lang/Nim#9363]
I tried running code coverage on several of my nim files and all generate an error (shown below).  If I switch back to version 0.18.0, they work as expected.  Let me know if you cannot reproduce and I will put effort into making a simple case.

Error messages:

```
Capturing coverage data from .
Found LLVM gcov version 10.0.0, which emulates gcov version 4.2.0
Scanning . for .gcda files ...
geninfo: WARNING: no .gcda files found in . - skipping!
Finished .info-file creation
Reading tracefile coverage.info
lcov: ERROR: no valid records found in tracefile coverage.info
```

**Comment by Araq** [comment]
I'm unfamiliar with ``LLVM gcov``. What could be the reason it stopped working? We still produce valid C code...

**Comment by alaviss** [comment]
The `.gc*` files used by `gcov` are produced in the cache folder (`~/.cache/nim/<file>_(d|r)`). I've not tried this with `0.18.0`

**Comment by flenniken** [comment]
Thanks, I changed the lcov directory switch to --directory ~/.cache/nim/ and now it works in 0.19.0. In 0.18.0 the *.gcda files were stored in the project's nimcache directory.

**Comment by alaviss** [comment]
Glad you have it worked. Please close the issue if there aren't any problems left.

As a small piece of advice, you could also use the `--nimcache:/path/to/cache` switch to tell the compiler where to put the cache :)

**Comment by flenniken** [comment]
Closing this issue because there is a solution.
