### ISSUE TITLE
iOS platform definition (and where to get all os and cpu arch supported)

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9369]
I'm curious what defines the iOS constant (if it's actually defined).

In platform.nim I see no mention of it even though osMacosx and osAndroid are defined there:
https://github.com/nim-lang/Nim/blob/af0c497f5dd375b83ab2f51ab4619e2843b846b5/compiler/platform.nim#L19-L25

Searching for iOS in the code shows that it's used in 2 places:

https://github.com/nim-lang/Nim/blob/72e15ff739cc73fbf6e3090756d3f9cb3d5af2fa/lib/pure/includes/osenv.nim#L61
https://github.com/nim-lang/Nim/blob/72e15ff739cc73fbf6e3090756d3f9cb3d5af2fa/lib/system/syslocks.nim#L141-L144

Are there other places than platform.nim that defines compile-time target specific constants?

**Comment by Araq** [comment]
@yglukhov knows more...

**Comment by narimiran** [comment]
Pinging @yglukhov once more. (I would like to close this)

**Comment by yglukhov** [comment]
I use `--os:macosx -d:ios` to compile to ios.

**Comment by krux02** [comment]
Since the activity here is now mostly gone I am closing it.
