### ISSUE TITLE
Windows compiler build fails

### ISSUE THREAD

**Issue by sinkingsugar** [nim-lang/Nim#9375]
Getting an error while building nim, `nim` iteration @ `commands.nim` line 51: `cannot open file: ../doc/basicopt.txt`

Tests looked green otherwise so I merged in distribution...

**Comment by Araq** [comment]
This is known problem with GCC v8, use a different GCC. Note that we don't know yet if it's a Nim bug or a GCC bug, but using a different GCC helps.

**Comment by sinkingsugar** [comment]
It was definitely working few commits before tho. As I never changed windows gcc in ages :(

**Comment by sinkingsugar** [comment]
using clang and adding respective `--cc:clang` to all required steps works.

**Comment by sinkingsugar** [comment]
@LemonBoy Very curious, have you checked what happens C code side? Specifically you could just compare before the specific suspicious commit and after.

I have to say it's a little bit scary but at same time it's only gcc on Windows as far as I understand.

**Comment by nc-x** [comment]
@sinkingsugar
Which gcc version are you on?
I had this same issue but updating to gcc v8.2.0 (rev3) (mingw-w64 from msys2) fixed the issue.

**Comment by sinkingsugar** [comment]
Not sure, I will check on the build machine but probably indeed older :)
So weird that the issue goes down to gcc tho... quite scary.

**Comment by LemonBoy** [comment]
Can confirm that the bootstrap succeeds with `gcc v8.2.0 (rev3)`

**Comment by sinkingsugar** [comment]
btw I'm not quite sure but I probably was using the `mingw-w64` package from nim-lang website... Not super sure but worth check it.

Also I suppose we can close this as long as we can put some big warning somewhere :) also ... or `vcc` was able to bootstrap nim.

**Comment by Araq** [comment]
I think we should default to ``-O2`` instead of ``-O3``. And I'd like to switch to clang on Windows for the default compiler of Nim, produces better code for me and can be used without setting any PATH.
