### ISSUE TITLE
old changelogs should be kept instead of erased

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9376]
/cc @araq in 7f81519f4114dbb49fcd68ca2361920bf374fb1c the changelog for v0.19.X was removed to start the new changelog for v0.20.X; it's useful to keep around these old changelogs and they should be in the git repo, not somewhere else

# proposal

* changelog.md always points to latest changelog (as is already the case)
* everytime a new version is tagged, `git mv changelog.md changelog.version.md' (eg: changelog.0.19.md) ; optionally, in a changelog subdirectory 
* introduce back older changelogs using above naming scheme

**Comment by Araq** [comment]
They are kept in the website repo.

**Comment by kaushalmodi** [comment]
I wondered the same too. I have been more than once confused trying to find old changelogs but always forgot to ask.

Can we please have the changelogs like:

```
# Nim 0.19.1
...

# Nim 0.19.0
...

# Nim 0.18.0
...
```

.. simply append the new changelog to the top.

Here are just few examples to list:

- https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md
- https://github.com/tmux/tmux/blob/master/CHANGES

**Comment by timotheecour** [comment]
> Can we please have the changelogs like:

all in 1 file doesn't scale; plus, tooling can merge these if REALLY needed (say, to generate a doc that contains all merged changelogs); plus it's easier to find/search what you're looking for if in different files

I really like these changelogs: https://dlang.org/changelog/2.082.0.html

**Comment by kaushalmodi** [comment]
> all in 1 file doesn't scale; plus, tooling can merge these if REALLY needed (say, to generate a doc that contains all merged changelogs); plus it's easier to find/search what you're looking for if in different files

OK. That makes sense.

> I really like these changelogs: https://dlang.org/changelog/2.082.0.html

Wow, that changelog looks sweet! I am completely sold on your `git mv` suggestion. Also that will allow me to grep for changes from the same repo, instead of looking separately into the website repo just for changelogs.

**Comment by timotheecour** [comment]
and as a minor point, `git mv` preserves history, unlike moving to a different repo ; but the bigger argument here is what u just said: "that will allow me to grep for changes from the same repo, instead of looking separately into the website repo just for changelogs"
