### ISSUE TITLE
Non-ref objects aren't properly copied on the JS target

### ISSUE THREAD

**Issue by recloser** [nim-lang/Nim#9389]
When non-ref objects, tuples, arrays and sets are passed into literal constructors of other non-ref objects they are stored as a reference instead of being properly copied. Also, the ``@`` seq constructor never copies the array passed to it.

Regular assignments like ``a = b`` seem to work fine, though.

```nim
block:
    type TestObj = object
        x, y: int

    let obj = TestObj(x: 1, y: 2)
    var s = @[obj]
    s[0].x += 123
    echo obj.x, " ", s[0].x

block:
    var nums = {1, 2, 3, 4}
    let obj = (n: nums)
    nums.incl 5
    echo (5 in nums), " ", (5 in obj.n)

block:
    let tup1 = (a: 100)
    var tup2 = (t: (t2: tup1))
    var tup3 = tup1
    tup2.t.t2.a = 300
    echo tup1.a, " ", tup2.t.t2.a, " ", tup3.a

block:
    proc foo(arr: array[2, int]) =
        var s = @arr
        s[0] = 500

    var nums = [1, 2]
    foo(nums)
    echo nums[0]
```
JS output:
```
124 124
true true
300 300 100
500
```

C output:
```
1 124
true false
100 300 100
1
```

**Comment by recloser** [comment]
The fix I pushed to my repo seems to work fine. All JS tests pass, and the generated JS looks fine to me too. It fixes some unnecessary array copies like in ``let x = [1, 2, 3]``, too. I'm not sure if it covers all cases though.

**Comment by Araq** [comment]
Create a PR to find out.
