### ISSUE TITLE
nimpretty changes indentation level of trailing comment

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9398]
```nim
proc fun() =
  echo "ok1"
  # echo "ok2"

fun()
```
nimpretty wrongly un-indents comment as:
```nim
proc fun() =
  echo "ok1"
# echo "ok2"

fun()
```

**Comment by Araq** [comment]
That's gonna be a tough one.

**Comment by timotheecour** [comment]
because regular comments aren't part of AST?

what if we made them part of AST ? (and have a field indicating whether they're doc comment or regular)

**Comment by Araq** [comment]
> what if we made them part of AST ? 

They were but users complained. ;-) Ok, it also implied that comments could only be inserted in specific parts of the code and it's a messy thing.

Anyway, it's hard to fix because of other reasons. (Or maybe not hard, just annoying.)
