### ISSUE TITLE
nimpretty aligns comment annoyingly

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9399]
```nim
proc foobar(a: int, b: int, body: untyped) = discard

proc testFoobar() =
  let firstFar = 1
  let secondVar = 2
  foobar(firstFar, secondVar):
    const a = 1 # checks it's const
```
wrongly aligns comment as:
```nim
proc foobar(a: int, b: int, body: untyped) = discard

proc testFoobar() =
  let firstFar = 1
  let secondVar = 2
  foobar(firstFar, secondVar):
    const a = 1               # checks it's const
```

**Comment by Araq** [comment]
That's actually a feature and works as intended but I can see why it's kinda annoying. :P 

I have a better idea of how to produce these alignments...

**Comment by timotheecour** [comment]
> That's actually a feature and works as intended

* which one works as intended, case1, case2 or both?

* one thing to keep in mind is minimizing diffs triggered by unrelated changes, eg:
for case2, changing `foobar(firstFar, secondVar):` to foobar(firstFar, secondVar, thirdVar):` should not change alignment of comment below

**Comment by Araq** [comment]
Both.

**Comment by timotheecour** [comment]
@Araq it seems alignment issues are the main thing preventing widespread use of `nimpretty` ; In https://github.com/nim-lang/Nim/issues/8458 I suggested a `nimpretty --safe` option that would just run a "safe" subset of all what `nimpretty` does, so it could simply exclude alignment until these alignment issues are ironed out; as it stands, we can't use `nimpretty` in the wild ; with `nimpretty --safe`  we could

**Comment by Araq** [comment]
Implementing ``nimpretty --safe`` is as much work as fixing ``nimpretty``.

**Comment by timotheecour** [comment]
how about the simpler, more consistent rule:

always indent comment as follows:
```
some code[1 space][hash][space][comment]
const a = 1 # foo bar
```

as it stands, I find the hard-coded value of `31` for the comment to be inconsistent, since it only applies on certain AST nodes (eg after `const a = 1`) but not others (eg after `proc testFoobar2() =`)

```nim
#[
CHECKME: re-indentation inconsistent
]#

proc testFoobar*(): auto = # foo2
  discard


proc testFoobar() =
  foobar(firstFar):
    const a = 1               #  foo2

proc testFoobar() = #foo1
  proc testFoobar2() = #    foo2
    foobar(firstFar):
      const a = 1             # foo2

proc testFoobar() = # foo1
  proc testFoobar2() = # foo2
    proc testFoobar2() = # foo2
      foobar(firstFar): # foo2
        const a = 1           # foo2
        let a2 = 1            # foo2
        a2.inc()              # foo2
        let a = echo: # foo
          echo "a"            # foo
        const asomevery_very_very_long_name = 1 # foo2

```

**Comment by Araq** [comment]
My own plan was to make the layouter produce tabs for this and then in a postprocessing step the tabs are aligned if that doesn't lead to too long lines.

**Comment by timotheecour** [comment]
unless I'm mis-understanding something in your plan, a problem with that is that a small code change can have non-local effects, resulting in large diffs; do you have a simple input/output example?
