### ISSUE TITLE
Refs and ptrs aren't properly stored in object fields and in arrays on JS target

### ISSUE THREAD

**Issue by recloser** [nim-lang/Nim#9410]
```nim
block:
    var someint = 500

    let p: ptr int = someint.addr
    let tup = (f: p)
    p[] = 654
    echo p[], " ", tup.f[]

block:
    var someint = 500

    let p: ptr int = someint.addr
    let arr = [p]
    p[] = 256
    echo someint, " ", p[], " ", arr[0][]

block:
    var someref: ref int
    new(someref)
    var someref2 = someref

    let tup1 = (f: someref)
    var tup2 = (f: someref)
    tup2.f = someref

    someref[] = 543

    echo someref[], " ", tup1.f[], " ", tup2.f[], " ", someref2[]
```
JS output
```
654 undefined
256 256 undefined
543 undefined undefined 543

```
C output
```
654 654
256 256 256
543 543 543 543
```

**Comment by mratsim** [comment]
Are pointers even supposed to work on the JS target?

**Comment by dom96** [comment]
Good question. My gut instinct tells me they are not.

**Comment by recloser** [comment]
@dom96 The presence of tests such as taddr.nim in the js category suggests otherwise.
From what I gathered the jsgen impl does try to handle ptrs and refs (including non object refs) already, but it's just quite unfinished and buggy right now.

**Comment by krux02** [comment]
Supporting non-object pointers/ref on the javascript target seems to be a very hard task to do. I think a much more sane solution would be to raise a compilation error whenever ``ptr int``, ``ptr float``, etc is requested. Javascript doesn't have such a thing as ``ptr int`` and pretending it does exist only causes problems that cannot properly be solved.

**Comment by yglukhov** [comment]
Pointers should be fine, it is pointer arithmetic that can get flaky. And pointer type casting doesn't work at all. As @krux02 said there's only so much we can do to "support" pointers, but I wouldn't agree the existing support is completely useless and needs to be banned. Pointers are unsafe territory, so anyway one should know what he's doing and what is the pointer semantics (which is "different") on native or js target.

**Comment by recloser** [comment]
Yes, JS doesn't have such a thing as `ptr int`, but pretending that it does does seem necessary to make Nim code work on a basic level. And, like I said, the jsgen already tries to deal with that to some degree. A `var int` param for example is simply a `ptr int` that's simply implicitly dereferenced. What do you think happens when you pass in an int to some proc that takes a `var int` param and modifies it? After all JS numbers are value types so you can't just pass it in as is. The jsgen accounts for that and will make that that int variable boxed and pass a ptr to the proc. The proc sees that `var int` as a ptr internally. That's what the `etyBaseIndex` type is used for in jsgen.

I don't know why you changed the title to something this vague and overly specific at the same time. This isn't just about ints, it also affects seqs, strings and probably more stuff, and it's definitely related to how the copying ("storing") of ptrs/refs is handled.

I think that these problems definitely can and should be solved. Ordinary Nim code that uses something like a `ref seq` to share a seq between two objects should work properly on the JS target. Look at my PR in which I already fixed a bunch of issues. LemonBoy also describes there how non obj ptrs/refs are handled. Run the tests and compare JS and C outputs and you'll see that it more or less works correctly. The tests actually fail because of stuff not strictly related to this. The jsgen is buggy as hell and right now even things like `high(getSomeSeq())` cause double evals.

**Comment by recloser** [comment]
That's where the trick with `etyBaseIndex` lies. It's not just the box, it's the object + displacement. So if you need to take addr of an int on an object like `addr(foo.x)`, the ptr on js side will actually hold a ref to `foo` like this: `[foo, "x"]`. A boxed local var like `var theBox = [123]` will just be passed as `[theBox, 0]`. Look at LemonBoy's explanation here: https://github.com/nim-lang/Nim/pull/9411#discussion_r226244406

**Comment by Araq** [comment]
> Javascript doesn't have such a thing as ptr int and pretending it does exist only causes problems that cannot properly be solved.

But the codegen can support it and it's part of Nim. It's the compiler's job to bridge over these differences and we should try to minimize them. It's not unsolvable.
