### ISSUE TITLE
tfragment_gc test is flaky on OSX

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9421]
eg: https://api.travis-ci.org/v3/job/442929178/log.txt
```
FAIL: tfragment_gc.nim C
Test "tests/fragmentation/tfragment_gc.nim" in category "fragmentation"
Failure: reOutputsDiffer
Expected:
occupied ok: true
total ok: true

Gotten:
occupied ok: true
total peak memory 247.18MiB
total ok: false

```

search for tfragment_gc and you'll see it affects a number of PR's

Note: this is a bit troubling, why does OSX on travis use so much memory? 

(82 * 1024 * 1024) = 86MB, but this uses 247MB

this seems like a regression

here's a snippet:
```nim
import strutils, data

proc main =
  var m = 0
  # Since the GC test is slower than the alloc test, we only iterate 100_000 times here:
  for i in 0..100_000:
    let size = sizes[i mod sizes.len]
    let p = newString(size)
 #   c_fprintf(stdout, "iteration: %ld size: %ld\n", i, size)

main()

let total = getTotalMem()
```

## first happened recently
searching through tfragment_gc in PR's, the 1st time I see this failure happening on OSX on travis is https://github.com/nim-lang/Nim/pull/9388 ie around october 16 2018 (1 day ago)

**Comment by alaviss** [comment]
It might be worth noting that I've also reproduced this a lot of time on Haiku x86_64.

**Comment by Araq** [comment]
It doesn't fail all the time though, sometimes it's green, but I'll disable these tests now.

**Comment by timotheecour** [comment]
> I'll disable these tests now

ok but let's keep this issue open please, as there's an underlying issue

**Comment by Araq** [comment]
Is there though? I haven't tried yet but I bet I cannot reproduce this problem on my OSX box.

**Comment by timotheecour** [comment]
>  I cannot reproduce this problem on my OSX box

well not on your OSX box (nor mine, last time I tried), but on travis's OSX box it happens; isn't that something we should consider?
could that be due to environmental difference eg less RAM in these machines?

**Comment by Araq** [comment]
I don't know but this tests runs in parallel with lots of others and always was fragile, so it's not a regression.

**Comment by Araq** [comment]
This test was disabled.
