### ISSUE TITLE
Missing docs for alloc, alloc0, allocShared ...

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9424]
The `alloc`, `alloc0`, `allocShared`, ... procs that are defined here for 0.19 are missing from the [documentation](https://nim-lang.org/docs/system.html):

https://github.com/nim-lang/Nim/blob/f6c5c636bb1a1f4e1301ae0ba5a8afecef439132/lib/system.nim#L1739-L1851

The `create` procs are visible, the only apparent difference being the pragmas:
`{.noconv, rtl, tags: [], benign.}` for allocs and `{.inline, benign.}` for creates.

**Comment by evanperryg** [comment]
A similar thing seems to exist with functions labeled with the async pragma.

This code:

```nim
# foo.nim
import asyncdispatch

proc hello*() {.async.} =
  ## says hello.
  echo "hello, world!"

proc goodbye*() =
  ## says goodbye.
  echo "goodbye, world!"
```

when run through `nim doc` on 0.19.2 will show both functions, but will only show the doc text for `goodbye`. This behavior can also be seen in the missing documentation for [readAll in asyncdispatch](https://nim-lang.org/docs/asyncdispatch.html#readAll%2CFutureStream%5Bstring%5D)

**Comment by narimiran** [comment]
>  the only apparent difference being the pragmas

Not the only difference.

The other difference (which is the real reason here, from what I can tell) is that procs with generated docs have the body, while the others don't have it.

```nim
proc foo =
  ## this will be visible
  discard

proc bar
  ## not visible
```

**Comment by narimiran** [comment]
Fixed by https://github.com/nim-lang/Nim/pull/11173
