### ISSUE TITLE
Somehow get `table.keys.join(", ")` to work

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#943]
Right now it works via `toSeq(table.keys).join(", ")`, but that's ugly.

**Comment by Yardanico** [comment]
We can create a shortcut which would iterate over all keys and return a sequence, but is this really needed?
@dom96

**Comment by andreaferretti** [comment]
Or `join` could be made to work with iterators

**Comment by Yardanico** [comment]
@andreaferretti probably, but then you'll need to call it like
join(table.keys, ", ")

**Comment by Araq** [comment]
`` toSeq(table.keys).join(", ")`` is just fine.
