### ISSUE TITLE
Small RFC. Minimal stacktrace for Exceptions when frames are disabled

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#9434]
Nim exceptions have wonderful stack traces in debug mode, but there is none in the release mode. While it is possible to enable stack traces in release mode, they quite pricey in terms of performance. Therefore I want to propose something more lightweight for release build when frames are disabled.

When frames are disabled: report just one level of stack trace. Idea is to fill in one StackTraceEntry object for Exception using lineinfo of the raise statement itself. This is definitely possible with minor changes to the codegen and might even possible to achieve with system library changes only.

I will implement it if there is no clear objects.

**Comment by Araq** [comment]
Ok, go for it.

**Comment by dom96** [comment]
Sounds beautiful.
