### ISSUE TITLE
Make 'koch xz' create os-specific release archives

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9436]
Ref: https://gitter.im/nim-lang/Nim?at=5bc90344c08b8b306737145a

> also ... we can consider to avoid the zip bomb by producing nim_linux.tar.xz, nim_osx.tar.xz, nim_other.tar.xz

/cc @Araq

**Comment by dom96** [comment]
Please link to our irclogs whenever you can: https://irclogs.nim-lang.org/18-10-2018.html#22:03:48

Also, please elaborate. It's hard to know what this issue actually means: what does `koch xz` do now that it should do differently?

**Comment by kaushalmodi** [comment]
> Please link to our irclogs

The gitter links are permalinks, so I thought they would be fine. Anyways, I use Gitter, so pasting permalinks from there was more natural. I'll keep this in mind next time.

> what does koch xz do now that it should do differently?

It should package only OS-specific stuff for a provided switch. I can think of `koch xz -d:linux_release` (or something like that). Then it should not pack files in Nim or csources needed for installation on osx/Windows. And then likewise for `-d:windows_release`  and `-d:osx_release` options.

**Comment by kaushalmodi** [comment]
The idea is to build the tar.xz on "X" OS, and run `koch testinstall` on that same OS, and then deploy that. So we will be doing that individually on all 3 OSes (already doing that on linux and osx: https://github.com/kaushalmodi/nightlies/releases).

When each of that 3.xMB file is extracted, it explodes to 500+MB. That explosion is reduced if each archive contains files necessary only for that OS.

_See how other languages deploy OS/arch specific installations: https://golang.org/dl/ (Though, it's really awesome that Nim compressed archive is **just 3.xMB!!**)._

Also it doesn't make sense for a user of X OS to get the extra stuff for Y and Z OSes.

This is just 3 OSes, what if more OSes are added in the future? So also from the aspect of readying for the future, it would be useful to modularize the xz packing.

**Comment by dom96** [comment]
> See how other languages deploy OS/arch specific installations: https://golang.org/dl/ (Though, it's really awesome that Nim compressed archive is just 3.xMB!!).

Pretty sure Go's archives contain binaries, not source code to build the binaries. This is an important distinction.

It's already painful enough to generate C sources and binaries for Windows. Do you really want to do that for however many OS' we've got and upload that to nim-lang.org and create download links on the website for each of them? We should instead focus on creating archives for binaries, it should rarely be necessary to use the C sources.

IMO time shouldn't be spent on this.

**Comment by kaushalmodi** [comment]
> Pretty sure Go's archives contain binaries, not source code to build the binaries.

That's correct.

From what I understood, @Araq mentioned that right now we need to package variations of csources for different platforms? And so we end up a lot of csources redundancy.

This is certainly low priority.

**Comment by narimiran** [comment]
On nightlies we now have both `nim-0.19.9-linux.tar.xz` and `nim-0.19.9-osx.tar.xz`. Since I don't use that, my question is: is that what you wanted originally, i.e. can this be closed?

**Comment by kaushalmodi** [comment]
I'll close this as this is a very low priority thing. I was thinking of having the \*-linux.tar.xz contain only the Linux-specific files, and not Windows and macOS files too, and similarly for \*-osx.tar.xz.
