### ISSUE TITLE
re.replace("foo", re"", "-") returns -foo, inconsistent with nre.replace

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9437]
Detailed comment: https://github.com/nim-lang/Nim/issues/9315#issuecomment-429677984

/cc @skilchen 

**EDIT by @timotheecour**
```nim
import re
echo replace("foo", re"", "-")
# -foo
```

* nre returns `"-f-o-o-"`
* strutils.replace returns `"-f-o-o-"`
* Python/JS/whatever also does it this way (see https://github.com/nim-lang/Nim/pull/9280#issuecomment-428843621)
* nim-regex "-f-o-o" but pending https://github.com/nitely/nim-regex/issues/29 (which seems accepted), shall return `"-f-o-o-"`
* strutils.multiReplace currently crashes (https://github.com/nim-lang/Nim/issues/9557)
* count throws on empty string (since https://github.com/nim-lang/Nim/pull/9280)

copying over the comment from @skilchen :
-----------------

```nim
import re
echo replace("foo", re"", "-")
```
produces:
-foo
While in the common understanding of regular expressions there is an empty string in front of any string, one between every substring of length 1 and one at the end of the string.
nre.nim produces the usually expected -f-o-o-
With nre as well as in the other languages I know the following is also possible:
```nim
import nre
echo replace("foo", re"^|$", "-")
```
which produces
-foo-
as expected, but using re you get: -foo which doesn't seem correct.
```nim
import re
echo "".replacef(re"([^\d]*)(\d*)([^\w]*)", "$1 - $2 - $3")
```
still produces an empty line, which doesn't seem correct, I would expect - -. However on a string that usually should be split using this pattern, it works:
```nim
import re
echo "abc123###".replacef(re"([^\d]*)(\d*)([^\w]*)", "$1 - $2 - $3")
```
correctly produces:
abc - 123 - ###

---------------

## further discussion
* https://github.com/nim-lang/Nim/commit/8955470644972e2d1f2b029650c04505ebacca23#r30894413
@Araq said:
> There is no wrong logic here, we don't claim to be bug-compatible with other regex engines.

if we're departing from other regex engines, an option could be to throw ; but at least it'd be nice to have consistent behavior across re,nre,nim-regex

**Comment by krux02** [comment]
Can you please copy the detailed comment here into the issue where it is visible. And please don't use imperative in the issue title, name the title.

**Comment by timotheecour** [comment]
@krux02 done

**Comment by timotheecour** [comment]
@xflywind thanks for self-assigning this; maybe also define `-d:nimLegacyReReplace` for backward compatibility in your PR?
