### ISSUE TITLE
Destructors are always injected in the outermost scope

### ISSUE THREAD

**Issue by LemonBoy** [nim-lang/Nim#9440]
This is pretty bad because we can't implement the RAII pattern in a safe way. The following example shows a seemingly correct program that __only__ calls the destructor on the last-created instance of the `X` object.
If the destructor task is to free the allocated resources (I've implemented some destructors for some `importc`'d stuff in order to avoid writing a lot of alloc/dealloc calls) then we get a silent leak.

```nim
type
  X = object

proc `=destroy`(x: var X) =
  echo "Destroyed"

proc main() =
  for x in 0 .. 2:
    var obj = X()
    echo obj
  # The destructor call is invoked after "end" is printed
  echo "end"

main()
```

Another test case:
```nim
proc main() =
  block:
    var obj = X()
    echo obj
    # The destructor is not called when obj goes out of scope
  echo "end"
```

**Comment by Araq** [comment]
I know, it's by design, but we can discuss it, of course. Problem is that C++ has quite some problems with temporaries that are destroyed a bit too early, Nim tries to mitigate this by delaying the destruction to the end of the function. In loops, thanks to destructive moves/assignments the destructor is still called early enough to ensure no leaks happen.

**Comment by LemonBoy** [comment]
If I have to sink/destroy the temps by hand I may directly call the destructor as well, the idea is to avoid this boring and error-prone bookkeeping activity. If you couple this with the unpredictability of the finalizers you have no way to automagically release the acquired resources and we're back to C-style alloc/free (and hope you covered all the exit paths) (even though the `__cleanup__` attribute can be used there :)

I understand that detecting the out-of-scope condition is hard since the variable may escape (covering this case may be slightly easier w/ the `sink`/`lent` annotations) either directly or via a pointer but I'd reconsider the choice of the injection site.

**Comment by Araq** [comment]
I don't understand how any of this follows. In C++ objects are destroyed when leaving the scope, in Nim when leaving the proc. Just as deterministic.

**Comment by Araq** [comment]
The only use case that I can come up with where it matters is locking but that's pretty bad since for locking I want to have an explicit (but checked) ``multilock`` statement to ensure no deadlocks can occur.

**Comment by LemonBoy** [comment]
Yeah, the determinism is there but it is highly unpractical in the above example: the destructor for the first two `obj`  is never called whereas in a similar C++ code it would've been called three times.

**Comment by Araq** [comment]
Well if you override ``=destroy`` you also need to override ``=sink`` and ``=`` and then you can see how the problem goes away. :-)

**Comment by krux02** [comment]
@LemonBoy I am not 100% sure if your statement in C++ is correct. The C++ optimizer is allowed to eleminate a lot of temorary objects so that you can't rely on ever constructer to be called when you expect it. Providing a constructor is more of a promise to the compiler how to clean up an object, but not a promise of the compiler to call it when you expect it.

**Comment by krux02** [comment]
@Araq maybe you should create an error to enforce that rule.

**Comment by LemonBoy** [comment]
> I am not 100% sure if your statement in C++ is correct

The "as-if" rule & the standard cover in-depth what an optimizer can do. If you don't care about side-effects the whole program can be safely compiled away :)

> you can see how the problem goes away

I'm afraid I don't see how `sink` saves the day, in the above snippet it is called to transfer the RHS onto the zeroed out `obj` variable.

**Comment by Araq** [comment]
> I'm afraid I don't see how sink saves the day, in the above snippet it is called to transfer the RHS onto the zeroed out obj variable.

It must not be zeroed out, that is a clear bug if it is :-)

**Comment by zah** [comment]
I've started studying the destructors implementation in 1.0.6 and immediately ran into this issue.

If a type has a destructor, but not a sink operator, then I think there should be a default sink operator that destroys the previous instance before copying the bits of the moved object. This would avoid the user mistake presented in this issue.

I'm also a bit confused about the signature of the sink operator. Shouldn't the source parameter has a `var` type too, so its fields can be moved/stolen? Consider moving a string field to the destination object.

**Comment by Clyybber** [comment]
@zah We inject wasMoved/zeroMem after a sink if it is required. This way we can elide those where possible.
Thanks to cooldome sink does exactly what you specified now afaik.
Araq is working on scope based destructor injection as we speak.

**Comment by timotheecour** [comment]
## right before https://github.com/nim-lang/Nim/pull/14790

Destroyed
()
Destroyed
()
Destroyed
()
end
Destroyed

## right after:
Destroyed
()
Destroyed
Destroyed
()
Destroyed
Destroyed
()
Destroyed
end

## devel 1.5.1 2f213db7eed7fb715b803559b38af4148cff02e1:
()
Destroyed
()
Destroyed
()
Destroyed
end
