### ISSUE TITLE
`nim doc` no longer documents imports from stdlib

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#9449]
Following up on issue #9447:
while the issue reported there has indeed been fixed, the documentation of the imports has also disappeared.

### Example
```nim
import sequtils
export sequtils

proc myproc*() =
  echo "do something"
```
### Current Output
![image](https://user-images.githubusercontent.com/8120120/47248756-f29ef580-d40c-11e8-9ce1-d40f29419367.png)

### Expected Output
![image](https://user-images.githubusercontent.com/8120120/47248793-35f96400-d40d-11e8-8a41-57c57724fe50.png)

### Additional Information
The imports from the stdlib disappeared with:
```
86556ebfdbbd4b8e9edc9d3085ea21d6c0bae2e2 is the first bad commit
commit 86556ebfdbbd4b8e9edc9d3085ea21d6c0bae2e2
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Fri Sep 7 01:53:09 2018 +0200

  compiler refactoring; use typesafe path handing; docgen: render symbols between modules
```

**Comment by Araq** [comment]
That works as designed, only the imports from the same Nimble package are listed now.
