### ISSUE TITLE
`nim doc` doesn't use default nimdoc.cfg with config.nims in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9450]
Since past few days I have started using `~/.config/nim/config.nims` and today I see another unexpected impact of that (first one being https://github.com/nim-lang/Nim/issues/9420).

When running `nim doc`, it now doesn't seem to look at the default `nimdoc.cfg` that gets installed with Nim.

### Example

Place a `config.nims` in `~/,config/nim/` dir, and run `nim doc` on any Nim file.

### Current Output

**With** `config.nims` in place, the nim-default `nimdoc.cfg` is not read. I see below on doing `nim doc foo.nim`:

```
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: system [Processing]
...
```

If I remove that `config.nims`, running `nim doc foo.nim` shows:

```
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nimdoc.cfg' [Conf]
Hint: system [Processing]
...
```

### Expected Output

I was expecting to see this instead:

```
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nimdoc.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: system [Processing]
...
```

### Additional Information

Nim version:

```
Nim Compiler Version 0.19.1 [Linux: amd64]
Compiled at 2018-10-19
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: cd9bc941e1315f47efd1ec567249a16347c0319a
active boot switches: -d:release
```

Probably related: https://github.com/nim-lang/Nim/issues/9405

**Comment by narimiran** [comment]
I've tried this on Nim 1.3.5, and it seems it works correctly now, or at least I couldn't reproduce it.

**Comment by kaushalmodi** [comment]
It works.. though now it's making 1 pass of nimdoc.cfg and 2 passes of all the other configs:

```
Hint: used config file '/home/kmodi/usr_local/apps/7/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/7/nim/devel/config/config.nims' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/7/nim/devel/config/nimdoc.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/7/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/7/nim/devel/config/config.nims' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
```
