### ISSUE TITLE
db misses an API to precompile the query and bind data later.

### ISSUE THREAD

**Issue by mikra01** [nim-lang/Nim#9453]
dbFormat is used to substitute the param values. 
the question mark (?) is matched on the entire sql-string instead
of binding by the database. This would harden the API and the
database is able to cache the (already parsed) prepared statements.
At the moment the database does a hard-parse  on every invocation.

#### example for sqlite3 to demonstrate the issue:
```nim
import db_sqlite

const create_table1_sql = sql"""
create table if not exists ttab(
  id integer primary key,
  question text,
  answer text
);"""

const insert_sql = sql"""
insert into ttab (id,question,answer) values (?,'how do you do ?',?)
 """

let db = open(":memory:","","","") 
db.exec(create_table1_sql)
db.exec(insert_sql,1,"fine!") # index out of bounds is raised here
db.close

#[ runtime outcome is:
  db_sqlite.nim(139)       exec
  db_sqlite.nim(129)       tryExec
  db_sqlite.nim(119)       dbFormat
  system.nim(2939)         sysFatal
  Error: unhandled exception: index out of bounds [IndexError]
]#
```

#### Solution:
DbType already present within db_common.nim; for db_postres.nim
there is also a "prepare" proc already present but
unfortunately the parameter dbType is missing.

The API could be extended a little bit (introduce new procs without affecting the 
present API) so that the caller is able to promote the dbTypes. 
Or introduce a preparedStatement object (better solution I think) and bind the values like this:  ps.setString(1,"fine!")
Binding (driver layer) would be not that difficult then.

### Additional Information

this affects the entire db-driver layer.

Discussion can be found here:
https://forum.nim-lang.org/t/4320

related discussion here
https://github.com/nim-lang/Nim/issues/5768

also in the past some issues relating this problem
bubbled up:
https://github.com/nim-lang/Nim/issues/3328
https://github.com/nim-lang/Nim/issues/6571

**Comment by krux02** [comment]
Please rephrase the title, ``db_*.nim dbFormat problems`` is not a good title.

**Comment by mikra01** [comment]
yep, that's correct - you got me now :smiley: the api would consist of a generic part and a vendor specific one. Also connection pooling and that stuff. But that is not that easy as it looks. I'd like to contribute here but I could only offer modest timeslots.. I also was not sure if I should file a bug or feature request.

**Comment by krux02** [comment]
@mikra01 yes the issue templates are still quite new and not final. Since they are supposed to help your feedback is very welcome.

**Comment by mikra01** [comment]
@krux02 thank you the changed topic looks much better now. The thing is that all related issues here from the past are just symtoms (missing parameter binding).
I also checked the new issue templates. they look very good for me. clean and concise. nothing to add further...

**Comment by xzfc** [comment]
I have made a fork of db_sqlite that uses ``sqlite3_bind_*`` calls instead of quoting everything into strings.
https://github.com/xzfc/ndb.nim

Noteworthy, you can just replace ``import db_sqlite`` with ``import ndb/sqlite`` in your example to get it work as intended.

Reusing precompiled statements is not supported at the moment, but I am considering adding it.

**Comment by mikra01** [comment]
@xzfc exactly thats it :-) (low-level api). Also dbNulls are handled the right way. I glanced at it shortly (but not tried yet). you could get rid of the dbQuoting-stuff now. Additional remark: within the iterator you could put a finally in it to make the database happy if the iterator is aborted with break by the caller (I think it was your thread in the forum a few days ago)

**Comment by xzfc** [comment]
@mikra01 
Yep, in ndb/sqlite, `dbQuote` isn't used to generate query string, and iterators have proper finalizers (I have pushed it just now).

Concerning `preparedStatements`, yes, this makes sense.

**Comment by mikra01** [comment]
I recently found now a timeslot to implement what I thought. please take a look at it: https://github.com/mikra01/nimdb . A starter would be the examples directory (tested wth 0.19.9). At the moment I am fiddling with ODBC....
