### ISSUE TITLE
Crash when closing an unopened file on debian 8.

### ISSUE THREAD

**Issue by flenniken** [nim-lang/Nim#9456]
Nim crashes when closing an unopened file on debian 8.  It works on the Mac.  The document doesn't say what it is suppose to do, but it would easier to use, if closing did nothing when the file wasn't open.  Whether you change it or not, I think the documentation should specify how it behaves in this case.

Here is the close doc:

https://github.com/nim-lang/Nim/blob/master/lib/system.nim#L3092

Here are the steps to reproduce the issue:

```
root@ad928cb4f3d1:~/code/test# cat t2.nim

var file:File
file.close()

root@ad928cb4f3d1:~/code/test# nim c -r --hints:off t2
CC: t2
Traceback (most recent call last)
t2.nim(3)                t2
sysio.nim(133)           close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: './t2 '

root@ad928cb4f3d1:~/code/test# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@ad928cb4f3d1:~/code/test# 
```

**Comment by Vindaar** [comment]
I guess we should check whether the pointer is nil. :)
