### ISSUE TITLE
newSeqUninitialized seems to perform initialization

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#9459]
I would have expected that `newSeqUninitialized` does not perform initialization as a performance optimization. However, in my experiments it looks like it always initializes:

### Example
```nim
import sequtils, sugar

let s = newSeqUninitialized[int](1_000_000_000)
echo s.all(x => x == 0)
```

### Current Output
```
true
```

### Expected Output
```
false
```

### Additional Information
Compiled with `-d:release`.

**Comment by krux02** [comment]
Just because you perceive something as initialized it doesn't mean that it is initialized. Memory allocated from the system is by default set to 0 for security reasons.

**Comment by LemonBoy** [comment]
You're asking the GC to fetch some memory from the OS since the freelist cannot satifsy your request. On linux this means we ask `mmap` a page with the `MAP_ANONYMOUS` and that, at least on linux, means that it's zeroed out.
Here's a small excerpt from the [man page](http://man7.org/linux/man-pages/man2/mmap.2.html):
> The mapping is not backed by any file; its contents are initialized to zero.

**Comment by krux02** [comment]
@LemonBoy thanks for the better explanation.

**Comment by krux02** [comment]
if you want uninitialized data to contain non 0 bits, then you have to deallocate non 0 bit data first.

**Comment by Araq** [comment]
> The other reason was that I measured that alloc + dealloc of the same size is significantly faster, e.g. a factor of ~5 for 1 million ints. I was wondering if this is the expected overhead of going through the GC or due to initialization? But it looks like alloc also gives me zeroed memory...

Educated guess, it's always the GC...

**Comment by mratsim** [comment]
`newSeqUnitialized` didn't initialize when it was added. Though I'm still using the following in Arraymancer:

```Nim
func newSeqUninit*[T](len: Natural): seq[T] {.inline.} =
  result = newSeqOfCap[T](len)
  result.setLen(len)
```

One thing that could be improved would be to restrict it to types that supports copyMem. Just numbers is a bit to restrictive (you can't use it with complex for example).
