### ISSUE TITLE
isNil magic doesn't work with the result of ^flowvar

### ISSUE THREAD

**Issue by sid-code** [nim-lang/Nim#9466]
I can't prove that the result of spawn is not nil.

I realize that combining two experimental features and expecting things to work isn't realistic, but this might be low-hanging fruit in improving the behavior of `isNil`.

### Example

```nim
{.experimental: "parallel".}
{.experimental: "notnil".}
import threadpool

type
  AO = object
    x: int
    
  A = ref AO not nil

proc process(a: A): A =
  return A(x: a.x+1)

proc processMany(ayys: openArray[A]): seq[A] =
  var newAs: seq[FlowVar[A]]

  parallel:
    for a in ayys:
      newAs.add( spawn process(a) )
  for newAflow in newAs:
    let newA = ^newAflow
    if isNil(newA):
      return @[]
    # Error: cannot prove 'newA' is not nil
    result.add(newA)
```

### Current Output

```
pnntest.nim(25, 16) Error: cannot prove 'newA' is not nil

```

### Expected Output

The isNil + early return should establish that newA is not nil.

**Comment by timotheecour** [comment]
note that this issue was closed as the error was turned into a warning but the underlying problem remains that not nil is unaware of control flow and warning is still being issued, refs https://github.com/nim-lang/Nim/pull/17538#issuecomment-808761794
