### ISSUE TITLE
Incorrect projectDir() reported from global config.nims

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9467]
The `projectDir()` reported from a global `config.nims` (the `~/.config/nim/config.nims`) is reported differently based on the location of the Nim file being compiled.

### Example

Create a dummy project using `nimble init dummy` so that you end up with a dir structure like this:

```
./
├── dummy.nimble
├── src/
│  ├── dummy/
│  │  └── submodule.nim
│  └── dummy.nim
└── tests/
   ├── config.nims
   └── test1.nim
```

and then do **git init** inside that directory.

The content of files in that nimble project is not important, but the content of `~/.config/nim/config.nims` is:

```nim
# ~/.config/nim/config.nims
task debugProjectDir, "debug project dir":
  echo "projectDir() = " & projectDir()

task debugProjectDir2, "debug project dir":
  selfExec "debugProjectDir src/dummy.nim"
```

### Current Output

On running `nim debugProjectDir`, I get:

```
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
projectDir() = /home/kmodi/sandbox/nim/dummy
```

On running `nim debugProjectDir2`, I get:

```
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
projectDir() = /home/kmodi/sandbox/nim/dummy/src
```

### Expected Output

I was expected **projectDir() = /home/kmodi/sandbox/nim/dummy** to be printed for both the cases. My understanding is that the project dir should be one containing the .nimble file or the .git/ directory (pick one).

### Possible Solution

1. Look for a .nimble file in current or parent directories. If not found,
2. then look for a .git() dir in current or parent directories.

For simplicity, let's say I defined a project dir to be the one containing the .git dir. So if I update the `~/.config/nim/config.nims` to below:

```nim
proc getGitRoot(): string =
  ## Get the path to the current git root directory.
  const
    maxAttempts = 10            # arbitrarily picked
  var
    path = projectDir() # projectDir() needs nim 0.20.0 (or nim devel as of Tue Oct 16 08:41:09 EDT 2018)
    attempt = 0
  while (attempt < maxAttempts) and (not existsDir(path / ".git")):
    path = path / "../"
    attempt += 1
  if not existsDir(path / ".git"):
    error("Unable to determine the git root, projectDir() = $1" % [projectDir()])
  result = path

task debugProjectDir, "debug project dir":
  echo "projectDir() = " & projectDir()
  echo "getGitRoot() = " & getGitRoot()

task debugProjectDir2, "debug project dir":
  selfExec "debugProjectDir src/dummy.nim"
```

I get the `getGetRoot()` output to be consistent:

```
km²~/sandbox/:nim/dummy> nim debugProjectDir
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
projectDir() = /home/kmodi/sandbox/nim/dummy
getGitRoot() = /home/kmodi/sandbox/nim/dummy                     <---------------------

km²~/sandbox/:nim/dummy> nim debugProjectDir2
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: used config file '/home/kmodi/stow/pkgs/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
projectDir() = /home/kmodi/sandbox/nim/dummy/src
getGitRoot() = /home/kmodi/sandbox/nim/dummy/src/../                     <---------------------
```

**Comment by timotheecour** [comment]
> My understanding is that the project dir should be one containing the .nimble file or the .git/ directory (pick one).

I vote for the one containing the .nimble file, because this should be orthogonal to git; eg a single git repo can contain multiple nimble projects

**Comment by kaushalmodi** [comment]
@timotheecour 

> I vote for the one containing the .nimble file, because this should be orthogonal to git; eg a single git repo can contain multiple nimble projects

That's a valid point. 

>  unfinished sentence :)

Hah! Thanks, fixed that.. was copy/paste of "So if I update the ~/.config/nim/config.nims to below:" from above :)

**Comment by krux02** [comment]
Well maybe the documentation of ``projectDir()`` needs a waring. If the result from ``projectDir`` leaks into the binary, the program will be unportable. Moving the project from one directory to another will already breaks the binary.

**Comment by dom96** [comment]
> My understanding is that the project dir should be one containing the .nimble file or the .git/ directory (pick one).

A project file is the file you are compiling, I'm guessing project dir is deduced from that. Based on that definition this works as expected.

**Comment by kaushalmodi** [comment]
@dom96 This discussion resurfaced today on the IRC.. 

> I'm guessing project dir is deduced from that. Based on that definition this works as expected.

Given that, the `projectDir()` is not very reliable.. we need something akin to the `getGitRoot()` I showed above. Would something like that be accepted in Nim core?

**Comment by kaushalmodi** [comment]
Closing this issue as the `projectDir()` in config.nims is consistent with the definition of `macros.getProjectPath`: https://nim-lang.github.io/Nim/macros#getProjectPath .

**Comment by disruptek** [comment]
Yes, but `getProjectPath` yields an incorrect result when run on a project which follows the Nimble-recommended structure with `./src/project.nim` and `./project.nimble`:

```nim
import macros
import strutils

static:
  assert getProjectPath().endsWith("src")
```

**Comment by kaushalmodi** [comment]
As per Nim, "project" means whatever file is getting compiled directly by Nim; it has no association with Nimble. 

If you do `nim src/a/a.nim`, the "project for" is src/a, go figure. 

I'll create an RFC for a new `getProjectRoot` that returns the dir holding .nimble, .git (in that order of precedence, whichever is found first.

**Comment by kaushalmodi** [comment]
@disruptek If you get a chance, please start an RFC for that. I'll pitch in.

**Comment by kaushalmodi** [comment]
In summary, the `projectDir()` that we have right now is not designed to be in a global config.nims. It's probably good only in Nim code, not in config files.
