### ISSUE TITLE
https://nim-lang.github.io/docs/lib.html gives 404

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9468]
stable docs are under:
https://nim-lang.org/docs/lib.html [EDIT]
bleeding edge docs are under:
https://nim-lang.github.io/Nim/lib.html
I see no reason why `docs` is changed to `Nim` (and `Nim` is kind of redundant with rest of url nim-lang.github.io)

### Possible Solution
write bleeding edge docs to https://nim-lang.github.io/docs/ instead of https://nim-lang.github.io/Nim/
(and maybe reroute https://nim-lang.github.io/Nim/ to https://nim-lang.github.io/docs/ although I think a breaking change here would be ok since it's recent)

**Comment by kaushalmodi** [comment]
> I see no reason why docs is changed to Nim (and Nim is kind of redundant with rest of url nim-lang.github.io)

That's how the GitHub Pages work. 

If you have a repo named FOO in a GitHub organization named BAR, and you set up GitHub Pages (one way is committing to gh-pages branch, like we do), the deployed URL is `https://BAR.github.io/FOO`. We cannot customize that URL. 

We are simply reusing the output of the the `koch docs` in the nim-lang/Nim repo Travis tests, and committing those to the gh-pages branch. And so we get the URL we have. 

To get the URL you suggested, we'd need to create a "docs" repo and run Travis in that, though I don't know how to trigger each build in that hypothetical "docs" repo with each commit to "Nim" repo. 

Currently, we also have the advantage that the devel docs don't get updated until all the tests pass. 

If we move the docs generation to a separate "docs" repo, we need to ensure these:

1. The docs get updated each time a commit is made to devel branch in Nim repo. 
2. This happens only if the tests pass in that repo. 

---

Also it's not clear what threads.html vs lib.html has to do with the domain URL. Fixing that 404 is a separate issue.

**Comment by timotheecour** [comment]
> Also it's not clear what threads.html vs lib.html has to do with the domain URL. Fixing that 404 is a separate issue.

fixed, was a typo

**Comment by timotheecour** [comment]
ok, thanks for explanation, I guess I can close
