### ISSUE TITLE
nre doesn't document quantifiers `re"foo{2,4}"`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9470]
~~nre doesn't support quantifiers `re"foo{2,4}"`~~ [EDIT] it's not documented

it's supported by `re`, nim-regex (https://nitely.github.io/nim-regex/) and lots of regex libraries (eg https://dlang.org/phobos/std_regex.html)

```
x{n,m}   at least n x and at most m x (greedy)
x{n,}    at least n x (greedy)
x{n}     exactly n x
x{n,m}?  at least n x and at most m x (ungreedy/lazy)
x{n,}?   at least n x (ungreedy/lazy)
x{n}?    exactly n x
```

I'd rather just use `nre` as discussed elsewhere but this prevents from using it in some cases

## note
assigned to @flaviut based on doc/codeowners.rst

**Comment by skilchen** [comment]
Why do you think that `nre` doesn't support quantifiers. Please provide some examples of what you expect and what `nre` matches. 
```nim
import nre
echo replace("fofoofooofobarfoofofoo", re"fo{1,3}", "")
```
produces:
```
bar
```
which seems correct to me.

**Comment by timotheecour** [comment]
ok great; changed title to nre doesn't document quantifiers `re"foo{2,4}"`
indeed, I don't see it documented anywhere in https://nim-lang.github.io/Nim/nre.html#contains%2Cstring%2CRegex%2Cint

**Comment by skilchen** [comment]
Reproducing the [PCRE](http://pcre.org/) documentation in `nre` probably doesn't make sense. 
I would recommend reading `man pcresyntax` or the relevant parts of http://pcre.sourceforge.net/pcre.txt

Btw. http://nim-lang.github.io/Nim/pcre.html is another example showing that either the doc-comments or the docgen have potential for improvements ...

**Comment by flaviut** [comment]
I have no plan to reproduce the PCRE docs in nre, but I'll make a link to the syntax more prominent.
