### ISSUE TITLE
oswalkdir Docs is wrong

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#9473]
https://nim-lang.org/docs/oswalkdir.html#walkDirRec.i%2Cstring

The Documentation is wrong, is not even related to what the module does, looks like from other module.

```nim
iterator walkDirRec(dir: string; filter = {pcFile, pcDir}): string
```
> "is greater" operator. This is the same as y < x.

Documentation Bug. Easy to Fix. :cat:

**Comment by timotheecour** [comment]
#9432 ?
