### ISSUE TITLE
Error when cross-compiling for windows under linux with mingw32

### ISSUE THREAD

**Issue by loongw** [nim-lang/Nim#9474]
Error: execution of an external compiler program 'i686-w64-mingw32-gcc -c -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I/usr/lib/nim -o /home/hao/linux_share/nim/PTA/nimcache/stdlib_system.o /home/hao/linux_share/nim/PTA/nimcache/stdlib_system.c' failed with exit code: 1

/home/hao/linux_share/nim/PTA/nimcache/stdlib_system.c:19:10: fatal error: Windows.h: No such file or directory
 #include "Windows.h"

**Comment by Araq** [comment]
Get a Mingw with a Windows.h.

**Comment by loongw** [comment]
Mingw always comes with a lower case `windows.h`. 
So I think it would be better to use `#include "windows.h"`, since it works on both linux and windows.

**Comment by Araq** [comment]
Oh ok, sorry.

**Comment by MrRobinnn** [comment]
same problem :'(
and  I tried to install Mingw then got  this EROR: 
/usr/bin/x86_64-w64-mingw32-ld: /tmp/ccbiFYGK.o:change.cpp:(.rdata$.refptr._ZSt4cout[.refptr._ZSt4cout]+0x0): undefined reference to `std::cout'
