### ISSUE TITLE
os.getEnv() is hidden in the docs

### ISSUE THREAD

**Issue by jabbalaci** [nim-lang/Nim#9481]
It's a problem with the documentation generator.

I wanted to read more about `os.getEnv()`. On https://nim-lang.org/docs/os.html it's under the Exports, which brought me to https://nim-lang.org/docs/ospaths.html . However, "getEnv" is not found on this page. It turned out that `ospaths.nim` includes `osenv.nim` (see https://github.com/nim-lang/Nim/blob/master/lib/pure/ospaths.nim#L537), which contains the proc `getEnv()`.

Expected output: `getEnv` should be listed in the docs of `ospaths` IMO.

**Comment by narimiran** [comment]
Fixed in devel docs: `os.getEnv()` is visible: https://nim-lang.github.io/Nim/os.html#getEnv%2Cstring%2Cstring
