### ISSUE TITLE
nimpretty should hardcode indentation amount to 2 spaces

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9502]
nimpretty currently applies to rest of file the 1st indentation it finds; in following case it uses an indentation of 1 space instead of usual 2:

```nim
proc foo1() =
 echo "bar"

proc foo2() =
  echo "bar"
```
nimpretty output:
```nim
proc foo1() =
 echo "bar"

proc foo2() =
 echo "bar"
```

I understand this may be by design but is that a good idea? especially if nimpretty is meant as a 0-config indentation tool? that'll lead to potential fragmentation of styles and larger diffs down the line, eg: if a user adds a different indentation as the very 1st proc in a file, the next time nimpretty is applied, a large diff will result (changing indentation everywhere in the file).

## proposal
hardcode indentation of 2 spaces, used throughout Nim codebase and large majority of nimble packages
I don't see any disadvantage to using 2 spaces

**Comment by Araq** [comment]
It is by design, plenty of people really prefer 4 spaces and since it can still be done with zero configuration it fits nimpretty's "philosophy".

**Comment by Araq** [comment]
But instead of ``--indentSpaces:2`` how hard is it to get the first indentation level right?

**Comment by timotheecour** [comment]
true for a single file; not so if you either have lots of files (or if they're auto-generated somehow)

**Comment by Araq** [comment]
Alright...

**Comment by b3liever** [comment]
Come on its fine as it is...
