### ISSUE TITLE
doc comment at end treats previous expression as discarded

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9519]
not 100% sure whether this is a bug or by design but it is surprising:

this gives:
`Error: expression 'fun0()' is of type 'string' and has to be discarded` 
changing `## foo` to `# foo` removes the error

```nim
when defined(true):
  template foo(fun): untyped=
    fun()
    ## foo

  proc fun0(): auto = "asdf"
  echo foo(fun0)
```

**Comment by Araq** [comment]
It's by design, the rationale here is 

a) it's hard to care for these nkDocComment nodes everywhere in the sematic checking.
b) conceptually it's like Python's """foo""" documentation string/comment and so is allowed to influence the type/discard checking.
