### ISSUE TITLE
recursive function with static argument changes argument type from enum to int

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#9520]
The output is not correct and weirdly enough only recursive functions are affected.

### Example
```nim
type
  MyEnum = enum
    Val1, Val2

proc myproc(a: static[MyEnum], b: int) =
  if b < 0:
    myproc(a, -b)

  echo $a

myproc(Val1, -10)
```

### Current Output
```
0
0
```

### Expected Output
```
Val1
Val1
```

Interestingly that if you remove unrelated recursive call then you will get expected output: ``Val1``.

**Comment by krux02** [comment]
an enum is internally represented as an integer. A static arguments instanciates the function for each argument value. My guess it that during this instantiation the information that a is actually an enum is lost.

**Comment by mratsim** [comment]
Related to this I suppose: https://github.com/nim-lang/Nim/issues/7375
