### ISSUE TITLE
`AsyncHttpClient` get request fails with no errors/output

### ISSUE THREAD

**Issue by citycide** [nim-lang/Nim#9524]
Both `AsyncHttpClient.get` and `AsyncHttpClient.getContent` fail and cause the application to quit. There are no errors but nothing after the request is executed.

### Example
```nim
import asyncdispatch, httpclient

proc thing (): Future[void] {.async.} =
  let url = "https://api.github.com/zen"
  let client = newAsyncHttpClient()
  echo 1
  let res = await client.get(url)
  echo 2
  echo(await res.body)
  echo 3

asyncCheck thing()
```

### Current Output
```shell
> nim c -d:ssl -r t2.nim
# ...
Hint: operation successful (52225 lines compiled; 1.201 sec total; 92.645MiB peakmem; Debug Build) [SuccessX]
Hint: E:\dev\nim\t2.exe  [Exec]
1
```

### Expected Output
```shell
> nim c -d:ssl -r t2.nim
# ...
Hint: operation successful (52225 lines compiled; 1.201 sec total; 92.645MiB peakmem; Debug Build) [SuccessX]
Hint: E:\dev\nim\t2.exe  [Exec]
1
2
Avoid administrative distraction. # some random response from GitHub api
3
```

### Additional Information

The synchronous `HttpClient` works correctly:

```nim
import httpclient

proc thing () =
  let url = "https://api.github.com/zen"
  let client = newHttpClient()
  echo 1
  let res = client.get(url)
  echo 2
  echo res.body
  echo 3

thing()

```

```shell
> nim c -d:ssl -r t2.nim
# ...
Hint: operation successful (52222 lines compiled; 1.963 sec total; 74.473MiB peakmem; Debug Build) [SuccessX]
Hint: E:\dev\nim\js-boost\t2.exe  [Exec]
1
2
Non-blocking is better than blocking. # no joke GitHub actually returned this (very appropriate)
3
```

**Comment by dom96** [comment]
This isn't a bug though, change ``asyncCheck`` to ``waitFor``. You are executing an async proc and then not waiting for it to finish its work and so your program exits.

**Comment by citycide** [comment]
Aw, well I wish I could have heard that in IRC when I put the code there. Is a docs update for `asyncCheck` warranted then because it's not clear to me that's how it works, just that it discards the result.

> Sets a callback on future which raises an exception if the future **finished with an error**.

How does it do that if it doesn't wait for completion?

https://nim-lang.org/docs/asyncfutures.html#asyncCheck%2CFuture%5BT%5D

**Comment by dom96** [comment]
>> Sets a callback on future which raises an exception if the future finished with an error.

> How does it do that if it doesn't wait for completion?

By setting a callback... :)

Happy to accept any improvements to these docs though.
