### ISSUE TITLE
Why do we have type classes?

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#9533]
Inspired by a [newbie question](https://irclogs.nim-lang.org/27-10-2018.html#18:03:47): "What's the difference between `proc tail[T](xs: seq[T])` and `proc tail(xs: seq)`?

Honestly the only reason for the second syntax to me seems to be: less typing. If that is the only reason then IMO it's grounds for this to be removed. We are already all using the more explicit syntax and offering this as an alternative is simply more overhead and more opportunity for breakage.

Thoughts?

**Comment by mratsim** [comment]
I'm using the second syntax when T doesn't matter, for example when working only on metadata like `len` for sequences or shape or strides for tensors.

**Comment by krux02** [comment]
don't forget: less visual noise. I don't see any problems in supporting both.

**Comment by dom96** [comment]
> There are things that can't be expressed with generics, e.g the type Table|HashSet (contrived example of course).

Maybe I'm misunderstanding, but:

```
proc foo[T, U](x: Table[T, U] | HashSet[T])
```

> don't forget: less visual noise. I don't see any problems in supporting both.

Less clarity as well. I prefer to be explicit rather than guess what the code is doing, and with these type classes I will need to do that. For example:

```nim
proc foo(x: seq, y: seq)
```

Is this ``proc foo[T](x: seq[T], y: seq[T])`` or ``proc foo[T, U](x: seq[T], y: seq[U]``? I can learn which one it is but it's not clear and many newbies will feel the same.

**Comment by krux02** [comment]
Is the question answered by now?

**Comment by alehander42** [comment]
Another example afaik is tuple: something that accepts a generic tuple needs `tuple`

**Comment by dom96** [comment]
Well, I must admit I am disappointed because I still prefer the more explicit syntax and would prefer we solved this problem differently.

But oh well.
