### ISSUE TITLE
Shadow DOM support in libs/js/dom.nim [Feature Request]

### ISSUE THREAD

**Issue by Epictek** [nim-lang/Nim#9535]
### Summary
We should be able to create and attach Shadow DOMs now that most browsers support them.
Firefox is to support them in the latest update/already does in nightly and chromium has support for them already.

### Additional Information
Dom Spec: https://www.w3.org/TR/dom41/#interface-shadowroot

**Comment by ringabout** [comment]
This can be closed now?
