### ISSUE TITLE
Error: undeclared identifier: '|'

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#9540]
This error is raised **sometimes** depending on the *number* of imports.

### Working example

Taken from [here](https://github.com/nim-lang/Nim/blob/4362ba7293e7527ff57f69bf2a0e95fdfd84985e/tests/generics/t5707.nim):
```nim
import sugar

proc foo[T]: seq[int] =
    return lc[x | (x <- 1..10, x mod 2 == 0), int]

doAssert foo[float32]() == @[2, 4, 6, 8, 10]
```

### Failing example

(Found out about it when I was doing [this PR](https://github.com/nim-lang/Nim/pull/9531).)

Now change just the first line to: `import macros, sugar, tables, typetraits` and you get `Error: undeclared identifier: '|'`.

Ok, it must be one of the three new imports. Let's find out which one:

1. If we do `import macros, sugar` and it compiles just fine.

2. `import sugar, typetraits` also compiles just fine. So it must be tables, right?

3. `import sugar, tables` and — compiles just fine!

4. Also, any of the following also works: `import macros, sugar, tables`, `import macros, sugar, typetraits`, `import sugar, tables, typetraits`.

Once again, only when all four imports are present there is the error:

```nim
import sugar, typetraits, tables, macros

proc foo[T]: seq[int] =
    return lc[x | (x <- 1..10, x mod 2 == 0), int] # Error: undeclared identifier: '|'

doAssert foo[float32]() == @[2, 4, 6, 8, 10]
```

### Expected Output

Compile without an error.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.1 [Linux: amd64]
Compiled at 2018-10-28
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by krux02** [comment]
List comprehension should be deprecated/removed as fast as possible. Don't use it.

As a note to myself I should update the documentation to say away from it.

**Comment by narimiran** [comment]
> List comprehension should be deprecated/removed as fast as possible. Don't use it.

I personally don't use it. But the example posted is in the tests, and depending on the number of the imports it fails.

And until `lc` is changed/removed, the stuff like this shouldn't happen.

**Comment by krux02** [comment]
I just want to remove it. Without substitution. It will just solve problems. Nobody is or should use it.

**Comment by dom96** [comment]
Yes, list comprehension should be removed. We are getting for loop expressions as a replacement.
