### ISSUE TITLE
Illegal recursion in type with {.importc.}

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#9545]
The following causes an illegal recursion in `Bar`. This seems to be a combination of `importc/pp`, the field order in `Bar` (swapping fixes it) and the type of `b` (only for byte-sized types?).

```nim
type
  Foo {.importc.} = object

  Bar = object
    b: byte
    foo: Foo
```

**Comment by krux02** [comment]
This seems to be related to the sizeof alignof implementation, since this algorithm is also responsible to detect illegal recursions in types.
