### ISSUE TITLE
logging error should go to stderr instead of stdout

### ISSUE THREAD

**Issue by xmonader** [nim-lang/Nim#9547]
logging module logs errors `error` proc for Console writes to stdout instead of stderror 

### Example
```nim
var L* = newConsoleLogger()
addHandler(L)

error("should got to stderr")
```

### Current Output
stderr is empty
stdout has the message

### Expected Output
stderr has the message
stdout is empty

### Possible Solution
having a special case for errors to stderr instead of stdout
https://github.com/nim-lang/Nim/blob/master/lib/pure/logging.nim#L153

**Comment by dom96** [comment]
Araq will probably hate me for this. But in fact, [shouldn't all logs go to stderr](https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout)?

The main reason for this is that stderr is where diagnostic information should go. Stdout is where the programs output goes, and keeping stdout clean of diagnostic information allows a program's output to be easily piped to other programs.

**Comment by krux02** [comment]
@dom96 I totally agree. Even though I don't think piping program output around and parsing it isn't really good software design.

**Comment by xmonader** [comment]
It sounded like an easy to pick task so I created a PR for it https://github.com/nim-lang/Nim/pull/9554
