### ISSUE TITLE
Concept related crash only when compiling to JS

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9550]
```nim
type Foo = concept c
    for v in c: (v is char)

func foo(c: Foo) = (for v in c: discard)
foo @['a', 'b' ,'c']
```

> ../../.choosenim/toolchains/nim-#devel/lib/system.nim(3936, 12) Error: internal error: expr(nkBracketExpr, tyUserTypeClass)

**Comment by narimiran** [comment]
The example successfully compiles in Nim 0.20.99.

**Comment by litlighilit** [comment]
... I've sadly found this just fix for `func` but not `proc`  :(

That's, the following still results in the same compile crash:
```Nim
type Foo = concept c
    for v in c: (v is char)

proc foo(c: Foo) = (for v in c: discard)
foo @['a', 'b' ,'c']
```

(just use `proc` instead of `func`)

**Comment by litlighilit** [comment]
This seems to fix for `seq` but not `array`.

That's, the following code will still result in the same compile error:

```Nim
type Foo = concept c
    for v in c: (v is char)

func foo(c: Foo) = (for v in c: discard)
foo ['a', 'b' ,'c']
```

(just use an `array` instead of a `seq`)

**Comment by ringabout** [comment]
progress: https://github.com/nim-lang/Nim/pull/23535
