### ISSUE TITLE
strutils.multiReplace() crashes if search string is ""

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#9557]
```nim
import strutils
var
  search = ""
  replacement = "abc"
echo "string".multiReplace(search, replacement)
```

Crash output
```
strutils.nim             multiReplace
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

This works on 0.18.0 but fails on 0.19.0 and #head.

**Comment by krux02** [comment]
I am not sure if "" should be supported. If the search engine is non utf-8 multibyte characters aware, it can destroy characters. I would prefer if this would just raise an error for illegal argument.

**Comment by Araq** [comment]
> I am not sure if "" should be supported. If the search engine is non utf-8 multibyte characters aware, it can destroy characters. I would prefer if this would just raise an error for illegal argument.

Excellent point that I never considered before. However, IMO an empty string simply doesn't "match" and so the original string is returned unmodified.

**Comment by genotrance** [comment]
Search string could be "" at runtime, I would prefer the proc would handle it rather than having to check myself. It's not too much work but everyone else using the proc will also benefit.

That being said, even the `replace()` proc is broken from Araq's definition.

```nim
import strutils

echo "abc".replace("", "a")

# Prints aaabaca
```

**Comment by timotheecour** [comment]
> However, IMO an empty string simply doesn't "match" and so the original string is returned unmodified.

```nim
import nre
doAssert replace("foo", re"", "-") == "-f-o-o-"
```
likewise with nim-regex (and re pending https://github.com/nim-lang/Nim/issues/9437)

**Comment by dom96** [comment]
This should be consistent with ``replace`` I guess.

**Comment by Araq** [comment]
> This was discussed and we choose this implemementation because Python/JS/whatever also does it this way.

That is what I said before knowing it breaks UTF-8 and can only be fixed by even more special logic for empty matches which is bad.

**Comment by timotheecour** [comment]
@Araq 
knowing that, would it be possible to enforce the same behavior across these for dealing with empty match string:
* re.replace
* nre.replace
* count
* strutils.replace
* strutils.multiReplace
* nim-regex (external)

and could that behavior be to throw an error (either doAssert or ValueError)
seems like a saner behavior, that would catch some bugs

**Comment by timotheecour** [comment]
@krux02 there were a few options discussed in this issue; which option did you pick in your commit?

**Comment by krux02** [comment]
@timotheecour well you can look in the commit and see. But sure. In this PR strutils won't match empty strings on anything anymore. I didn't touch ``re`` or ``nre`` because those are wrappers for PCRE and I can't control what PCRE matches and what it doesn't match.

**Comment by timotheecour** [comment]
for clarity, here's new behavior:
```
echo multiReplace("abcd", ("", "123",))
abcd
```

also, @genotrance  I think your original issue was wrong, since `replacement` has to be `varargs[(string, string)]` ; I'll edit it in top-post

**Comment by dom96** [comment]
Really? We've changed the way ``replace`` works again?!

**Comment by krux02** [comment]
Was it changed in the past? The only alternative to "empty string doesn't match on anything" is to make everything ``utf8``, and state clearly that ``string`` is only for ``utf8`` data.

**Comment by timotheecour** [comment]
the only alternative is throwing

**Comment by Araq** [comment]
We don't throw on API usage bugs, we could have used ``doAssert`` but that makes people nervous who value "continue" over "crash and burn".

**Comment by timotheecour** [comment]
/cc @Araq 
> We don't throw on API usage bugs, we could have used doAssert 

huh? see https://github.com/nim-lang/Nim/pull/9280 and your comment (https://github.com/nim-lang/Nim/pull/9280#issuecomment-428840784) in pretty much the same context (for ``count`` on empty string)
> This should instead use assert or doAssert, it's an API misuse.

> but that makes people nervous who value "continue" over "crash and burn".

which is why I suggested in https://github.com/nim-lang/Nim/pull/9280#issuecomment-428786497 (as well as here) to throw (by that I mean a recoverable exception) instead of `doAssert` 
My suggestion is to simply throw `CatchableError` (or perhaps `ValueError` but I like the simplicity of using the root of catchable errors) 
That's not `crash and burn`, that's normal exception handling mechanism ; it can peacefully coexist inside a production-server-that-can-never-die

**Comment by Araq** [comment]
But programming bugs are not recoverable/catchable errors, see the RFC I wrote.
