### ISSUE TITLE
document `nim --nep1:on`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9564]
we should document the switch `--nep1:on` ; it may not be perfect but still useful; we can just document it in `--fullhelp` and specify it's still experimental; that'll make more people use it and make it easier to find/report bugs with this tool in the wild

learned about it here: https://github.com/nim-lang/Nim/pull/9510#issuecomment-434180531

**Comment by Araq** [comment]
Before I document it I want to change it to ``--styleCheck:off|hints|error``.
