### ISSUE TITLE
linter to enforce named arguments for bool parameters

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#9565]
Assuming NEP1 will have some lint checker or formatter, 
I propose the following: 
when passing a boolean argument, always prefix it with the argument name.
Readability is improved a lot when instead of just "true" or "false", we use the name of the argument.

**Comment by timotheecour** [comment]
it has a linter already, undocumented --nep1

**Comment by Araq** [comment]
Nobody is working on this. Sad, I know.
