### ISSUE TITLE
`not` as prefix operator causes problems

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#9574]
Even though not looks much like a function call, it is a symbol, and that causes confusion.

### Example

```nim
proc isFalse(a: int): bool = false

assert not isFalse(3) # parsed as infix not with ``assert`` as argument
assert not(isFalse(3)) #  ^^ same
```

### Additional Information

this is the original issue: https://github.com/nim-lang/Nim/issues/8300

**Comment by timotheecour** [comment]
from https://github.com/nim-lang/Nim/issues/8300#issuecomment-434406032 by @Araq 

> Well we can decide that ``not`` is special and always only an unary operator. That would fix it and no code out there uses an overloaded binary ``not`` operator anywhere, I guess.
