### ISSUE TITLE
codegen ignores `cppDefine` for object fields

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#9575]
Add this to `config.cfg` or checkout this PR https://github.com/nim-lang/Nim/pull/9587
```
cppDefine = "compl"
cppDefine = "typeof"
cppDefine = "restrict"
```
  
Now,
This fails to compile - 
```
type
  x = object
    typeof: string
    compl: int
    restrict: float
let y = x()
echo y
```
  
But this compiles - 
```
var
  typeof: string
  compl: int
  restrict: float

echo typeof, compl, restrict
```

**Comment by nc-x** [comment]
@Araq Reverting this commit https://github.com/nim-lang/Nim/commit/dd8cbf5fca7becf43b5cec07ecf7e579308e2e7a fixes this issue. [But then it will cause the issue #5404  to reoccur]

**Comment by ringabout** [comment]
It works in devel with/without `config.cfg`.
`(typeof: "", compl: 0, restrict: 0.0)`
