### ISSUE TITLE
illegal proc with untyped param causes internal error instead of error message

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9593]
## BUG1:
this gives internal error instead of regular CT error
`Error: internal error: getTypeDescAux(tyExpr)`
for this:
```nim
proc foo(a: untyped)=discard
foo(0)
```

## BUG2:
this is accepted but should give regular CT error as in above case
```nim
proc foo(a: untyped)=discard
```

**Comment by timotheecour** [comment]
@krux02 verbatim error messages (eg `internal error: getTypeDescAux(tyExpr)`) are much more useful than generic ones (eg `illegal proc`) when searching for issues; yes it's in the body of the issue but won't work for `in:title` queries
your 2nd change `proc foo(a: untyped)` => `illegal proc with untyped param` is fine though, since it's less likely to be 100% match to another use case

**Comment by krux02** [comment]
I am optimizing titles for reading, not for search. When I see the issue title I want to know what it is about. I don't want to dig through details. This means no unsupported markup like ``:(`)`` or internal symbols like ``getTypeDescAux`` unless they are the cause of the problem.

**Comment by Araq** [comment]
There is a fulltext search anyway, no need to restrict the search to titles.
