### ISSUE TITLE
Cannot use a typedesc variable in a template

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#9611]
Passing a typedesc to a template seems to fail when the parameter is a typedesc variable:

### Example

```nim
proc aProc(A: typedesc) =
  var a: A

template aTemplate(A: typedesc) = 
  var a: A

var T: typedesc[int]
aProc(int)       # works with concrete type
aTemplate(int)   # works with concrete type
aProc(T)         # works with typedesc variable
aTemplate(T)     # fails with typedesc variable
```

### Current Output

```
test.nim(11, 11) Error: type expected

```

Interestingly passing the typedesc variable to the template works, if the template does not use the type explicitly in variable/type/function definitions and only calls procs that take typedescs. For instance the code compiles when changing the typedesc to

```nim
template aTemplate(A: typedesc) = 
  aProc(A)
```

The common work-around of using a local type alias like `type AA = A` doesn't seem to help here.

**Comment by Araq** [comment]
``var T: typedesc[int]`` is not valid Nim and should be rejected.
