### ISSUE TITLE
Using a template as a routine pragma no longer works

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#9614]
From the manual:
>Whole routines (procs, iterators etc.) can also be passed to a template or a macro via the pragma notation:
>```nim
>template m(s: untyped) = discard
>
>proc p() {.m.} = discard
>```
>
>This is a simple syntactic transformation into:
>```nim
> template m(s: untyped) = discard
>
>m:
>  proc p() = discard
>```

This works in 0.19.0, but with latest devel it gives `Error: invalid pragma: m`. It only fails when a template is used, with a macro it still works.

**Comment by GULPF** [comment]
Git bisect says the regression was introduced in 33458894da13da7134604639c129273bfb0cb1c1. Ping @LemonBoy

**Comment by mratsim** [comment]
Are you sure it's a regression?

See https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-custom-annotations

```Nim
template dbTable(name: string, table_space: string = "") {.pragma.}
template dbKey(name: string = "", primary_key: bool = false) {.pragma.}
template dbForeignKey(t: type) {.pragma.}
template dbIgnore {.pragma.}
```

I think it's the new syntax, but the old one probably requires a deprecation period and/or a big warning in the changelog.
