### ISSUE TITLE
Compiler should check if binary is creatable in the folder

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#9618]
On windows when I try to build a binary in a folder where admin rights are required (for example `nimpretty` when nim is installed to `%programfiles%\Nim`) the compilation starts (since cache folder is writeable) and at the last step gcc tries to create the file next to the `.nim` file and the build process crashes with gcc error.

It would be better if it's checked **before** the compilation starts if the target directory is writeable for that user. I assume it's the same on linux.

`nim c -d:release "C:\Program Files\Nim\nimpretty\nimpretty.nim"`
```
Hint:  [Link]
C:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86
_64-w64-mingw32/bin/ld.exe: cannot open output file C:\Program Files\Nim\nimpret
ty\nimpretty.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc.exe   [...]'
```

With admin rights it works as expected.

E: I read into this a bit and it seems it's not easy to solve this 100%. For me only two different such cases ever appeared: 1) No admin rights for this directory; 2) same file was created before and runs / is locked
So if these could be checked once before creation, I think it would solve all practical cases.

**Comment by krux02** [comment]
@tim-st I honestly don't see a problem here. The error message "cannot open output file C:\Program Files\Nim\nimpret
ty\nimpretty.exe: Permission denied" is pretty clear to me.

**Comment by tim-st** [comment]
Sure, but instead it could also show the error _before_ the compilation is done and additionally this would give the same error for all backends. Also I stripped a huge block from the error message, without this it's harder to find the error message from gcc.

**Comment by krux02** [comment]
Yes for sure nim could check for everything. It can check if the destination is readable. It can check if the destination is approximately enough free space. It can check if your system has enough ram to run the compiler, etc ... But you know what, I don't want to support this. It is just replicated work and you already get the error messages and they are pretty clear.

@Araq I don't know how you think about this, for me this is a won't fix and I would like to close it.

**Comment by bluenote10** [comment]
The general argument against upfront checks applies: Checking before does not guarantee that the write actually succeeds, since the rights could change in between the check and the write (or the folder is gone or whatever). In the end, it requires to duplicate the error handling.
