### ISSUE TITLE
Incorrect parseopt parsing ?

### ISSUE THREAD

**Issue by fenekku** [nim-lang/Nim#9619]
The parseopt module (only tested with new one) does not take `""`` as option value, leading to unexpected parsing. I think this is undesirable, but maybe you think not.

### Example
 
```nim
# testParsing.nim
import parseopt

for kind, key, val in parseopt.getopt():
  case kind
  of cmdArgument:
    echo "kind: ", kind, " key: ", key, " val: ", val
  of cmdLongOption, cmdShortOption:
    echo "kind: ", kind, " key: ", key, " val: ", val
  of cmdEnd: assert(false) # cannot happen
```

On the command line:

`./testParsing --option="" --anotherOption tree`

### Current Output
```
kind: cmdLongOption key: option val: --anotherOption
kind: cmdArgument key: tree val: 
```

### Expected Output
```
kind: cmdLongOption key: option val: 
kind: cmdLongOption key: --anotherOption val:
kind: cmdArgument key: tree val: 
```

### Additional Information

This was run on fish shell.

Also:

```nim
var p = initOptParser("""--option="" --anotherOption tree""")
for kind, key, val in p.getopt():
  case kind
  of cmdArgument:
    echo "kind: ", kind, " key: ", key, " val: ", val
  of cmdLongOption, cmdShortOption:
    echo "kind: ", kind, " key: ", key, " val: ", val
  of cmdEnd: assert(false) # cannot happen
```

outputs:

```
kind: cmdLongOption key: option val: ""
kind: cmdLongOption key: --anotherOption val:
kind: cmdArgument key: tree val: 
```

**Comment by krux02** [comment]
@Araq what is the status on parseopt? Remind me if I misremember, but didn't you mention that there was a new parseopt that was more correct?

**Comment by krux02** [comment]
I see an empty argument. In bash (and other shells), the command line ``./testParsing --option="" --anotherOption tree`` is split in these arguments: ``"--option=" "--anotherOption" "tree"``. ``--option=""`` is a concatenation of ``"--option="`` and ``""``, which is the same as just ``"--option="``

**Comment by dom96** [comment]
I've already mentioned this to Araq but I suppose I should post this publicly too: new parseopt behaviour broke Aporia :(

<img width="1392" alt="screen shot 2018-11-05 at 20 45 42" src="https://user-images.githubusercontent.com/246651/48025584-c63ce600-e13b-11e8-9429-9198241d9238.png">

(Yep, I still use it).

**Comment by krux02** [comment]
@dom96 I can't even build aporia anymore, and that has nothing to do with optparsing.

**Comment by dom96** [comment]
@krux02 that doesn't matter. The Nim parsing behaviour changed. I've been running the same version of Aporia for years.

**Comment by dom96** [comment]
@krux02 this is where ``choosenim`` comes in.
