### ISSUE TITLE
`include` doesn't work with lists

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#9627]
With `import` it work to do something like this:
``` Nim
import folder / [moduleOne, moduleTwo]
```
But doing the same with an `include` yields this error message:
```
Error: invalid module name: '[moduleOne, moduleTwo]'
```

**Comment by Araq** [comment]
Sorry, but we don't claim these work with ``include``.

**Comment by PMunch** [comment]
Yeah I know it doesn't explicitly say that it works, I just found it odd and assumed it wasn't intentional.
