### ISSUE TITLE
`removeSuffix` with default param `chars = Newlines` should be deprecated => use stripLineEnd

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9628]
/cc @Araq  ok for following?

now that we have `stripLineEnd` , I'd like to deprecate `removeSuffix` with default param `chars = Newlines` ; ie:

currently we have:
```nim
proc removeSuffix*(s: var string, chars: set[char] = Newlines)
```

I'd like to have instead:
```nim
proc removeSuffix*(s: var string) {.deprecated.: "use stripLineEnd(s) or removeSuffix(s, chars=Newlines) " .}
```
and add this
```nim
proc removeSuffix*(s: var string, chars: set[char])
```
(the other overloads being unchanged)

what users want most of the time is to strip the last newline (as specified in `stripLineEnd`), not all newlines (as done in `removeSuffix(s)` ) ; a common use case is postprocessing the output of shell cmd output which inserts a single newline (so removing all newlines is probably not what user wants); that's why languages have `chomp` (called `stripLineEnd`, in Nim)

 if they do want to remove all newlines they can still use `removeSuffix(s, chars = Newlines)`

* likewise, `proc removeSuffix*(s: var string, chars: set[char] = Newlines)` could probably be deprecated (again, deprecation would only affect the default param, so `proc removeSuffix*(s: var string, chars: set[char] ` would  be added)

[EDIT]: fixed typos in above text (was using removePrefix in places where I meant removeSuffix)

**Comment by dom96** [comment]
Can you explain why you want to do this? Am I missing the reason from your post? It seems like a pretty important thing to mention.

**Comment by timotheecour** [comment]
I just fixed some typos (was using removePrefix in places where I meant removeSuffix)

Although I didi give a rationale in last part, let me expand on it:

* the default param of `removeSuffix` is kind of arbitrary: while a default param of`Whitespace` is common in other languages (as is the case for `proc strip*(s: string, leading = true, trailing = true, chars: set[char] = Whitespace): string`), the `Newlines` default param of `removeSuffix` (and `removePrefix`) seems arbitrary, eg I'm not seeing the equivalent in other languages, eg:

all these have special case for space, but not newline:
  * D: https://dlang.org/phobos/std_string.html
  *  python: https://www.tutorialspoint.com/python3/python_strings.htm 
  * go: https://golang.org/pkg/strings/#TrimSpace

and both python and D have a way to remove the **last** newline (which I added to nim via `stripLineEnd`), which is a useful thing in common scenarios, eg: postprocessing the output of shell cmd output which inserts a single newline; removing **all** newlines is probably not what user wants in this case; but if user wants it, `removeSuffix(s, chars=NewLlines)` is still available

**Comment by Araq** [comment]
I don't understand any of this. You want to replace 

```nim
proc removeSuffix*(s: var string, chars: set[char] = Newlines)
```

with 

```nim
proc removeSuffix*(s: var string) {.deprecated.: "use stripLineEnd(s) or removeSuffix(s, chars=Newlines) " .}
proc removeSuffix*(s: var string, chars: set[char])
```

But where is the advantage? At some point we have to assume people have read ``removeSuffix``'s documentation, why patronize our users?

**Comment by krux02** [comment]
according to [wikipedia](https://en.wikipedia.org/wiki/Suffix) ``Newlines`` isn't a suffix and a default argument for a suffix that technically isn't a suffix is not a good idea.

**Comment by Araq** [comment]
If you don't like ``removeSuffix``, don't use it. There is plenty of stuff in Nim's stdlib that I personally don't like either, but at some point you have to grow up and focus on what's important.
