### ISSUE TITLE
what is this ...tests/stdlib/tmath2.nim ???

### ISSUE THREAD

**Issue by skilchen** [nim-lang/Nim#9653]
What does this [tmath2 test](https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/tmath2.nim) test???

**Comment by krux02** [comment]
the first comment says it, it tests the interpreter. The name is weird though.

**Comment by skilchen** [comment]
What interpreter???
It simply wastes some cycles during every test run and doesn't test  anything meaningful, except maybe that it is only compiled and not run. Otherwise it would block the stdlib tests as it reads from stdin.
I think it should be removed.

**Comment by krux02** [comment]
I have the feeling that it is the remainder of a very old test that was written for the parser. But everything it tested is now also covered by the other tests that also test for functionality.  But that is just a rough guess.

**Comment by andreaferretti** [comment]
Yeah the history shows it has only minor modifications since January 2014. Before that, it had a different name, so I cannot tell at a glance, but I suspect it is a leftover from the early days of the interpreter, when there was not a more complete testing infrastracture yet

**Comment by andreaferretti** [comment]
It is essentially unchanged since 21 Feb 2010 in commit https://github.com/nim-lang/Nim/commit/d913fdb2800d83680e413cd8a5f07b7f85deac6e#diff-fa176b83e89624d4fc810bf87ed527f9 where it was called `tests/accept/compile/tmath.nim`. Before that it was just `tests/tmath.nim`, but I cannot go back further in time in the Github interface

**Comment by andreaferretti** [comment]
In fact, it is essentially unchanged since the first commit https://github.com/nim-lang/Nim/blob/405b86068e6a3d39970b9129ceec0a9108464b28/tests/tmath.nim
