### ISSUE TITLE
static param gets wrong value if a nested proc accesses it

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9656]
/cc @Araq 
BUG: code below prints ` forwardResult1:false` instead of ` forwardResult1:true`

```nim
macro dispatchGen7*(forwardResult: static bool = true): untyped =
  echo "forwardResult1:", forwardResult # BUG: will show: forwardResult1:false
  proc callWrapped(): NimNode =
    let ignore = forwardResult # comment this => will show: forwardResult1:true
    discard

  let callWrapd=callWrapped()

dispatchGen7(forwardResult=true)
```

reduced from a pending PR to cligen

**Comment by zah** [comment]
This should be a duplicate of https://github.com/nim-lang/Nim/issues/9509

**Comment by krux02** [comment]
yes it is a duplicate. @timotheecour  you can add this example as a comment to the other issue if you think it should be covered in a fix for that issue. I am closing this in favor of #9509
