### ISSUE TITLE
Ambiguous procs lead to "undeclared identifier" error message

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#9660]
```nim

import parseopt, parseopt2

for kind, key, val in getopt("foo --bar"):
  discard
```

**Comment by Araq** [comment]
My bad.

**Comment by dom96** [comment]
When even you're getting these things wrong it sounds like a good idea to improve the error message.

**Comment by Araq** [comment]
The real program was more like

```nim
from parseopt import nil
from parseopt2 import nil

for kind, key, val in getopt("foo --bar"):
  discard
```

and the error message is good enough, I must learn to read.

**Comment by dom96** [comment]
A simple "did you mean parseopt.getopt" would help out a lot.

**Comment by Araq** [comment]
1. That would have confused my as much as the existing error message.
2. That's likely covered by some of our "error messages" issues.
