### ISSUE TITLE
proc foo(arg: untyped) causes problems

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#9669]
I currently try to disallow procedure declarations with ``untyped`` or ``typed`` parameters, because people try to do it and then complain that the compiler crashes. These procedures pass the semantic checking but then crash at the backend.

The problem is, builtins (magic) are often declared with ``untyped`` and ``typed`` parameters. So my semantic checking would refuse to accept the builtins. I currently do not have a good solution to deal with those builtins.

**Comment by Araq** [comment]
``sym.magic == mNone``?

**Comment by krux02** [comment]
Could be the solution. I thought about it as well, but not that evening anymore. Thanks.
