### ISSUE TITLE
tfuturevar fails when activated

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#9695]
The test [tfuturevar](https://github.com/nim-lang/Nim/blob/devel/tests/async/tfuturevar.nim) is not executed, even though it should be executed. When it is activated, it fails.

this is the output on my machine
```
tfuturevar.nim(46)       tfuturevar
asyncmacro.nim(307)      main
asyncmacro.nim(39)       main_continue
tfuturevar.nim(29)       mainIter
asyncfutures.nim(313)    read
[[reraised from:
tfuturevar.nim(46)       tfuturevar
asyncdispatch.nim(1658)  waitFor
asyncfutures.nim(308)    read
]]
Error: unhandled exception: Future still in progress.
Async traceback:
  tfuturevar.nim(46)    tfuturevar
  asyncmacro.nim(307)   main
  asyncmacro.nim(39)    main_continue
    ## Resumes an async procedure
  tfuturevar.nim(29)    mainIter
  asyncfutures.nim(313) read
Exception message: Future still in progress.
Exception type: [ValueError]
Error: execution of an external program failed: '/home/arne/proj/nim/Nim/tests/async/tfuturevar '
```

**Comment by dom96** [comment]
Why is it not executed? Didn't we fix this problem?

**Comment by krux02** [comment]
I am currently fixing this problem. The reason this test was not executed is the default action for a test was "compile" not "run" so the test was only compiled. I changed it now to "run" and I am hitting a bunch of broken tests that we didn't notice.

**Comment by dom96** [comment]
I recall a PR that changed the default action to "run". I thought it was merged but I guess not, might be worth searching for it.

**Comment by Araq** [comment]
It was merged but didn't solve the problem completely. Sad, I know. The testament logic is still messy (but getting better).

**Comment by krux02** [comment]
@dom96 I changed the default action to run in my current PR: https://github.com/nim-lang/Nim/pull/9697 it reactivates many tests from hybernation.

**Comment by Araq** [comment]
This test never worked.

**Comment by ringabout** [comment]
This is indeed a regression, see PR https://github.com/nim-lang/Nim/pull/16090

And the tests work in Nim v0.17.2
