### ISSUE TITLE
Converters: generic converter is not instantiated when multiple converters are involved

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#9698]
This one is easier to describe from compiler internals perspective.
When within one call multiple converters are used, for example first argument is converted using generic converter and second argument is converted using non generic converter then flag ``genericConverter`` in ``TCandidate`` gets overridden by second converter to ``false`` and instantiation of first converter is not going to happen

I will provide a fix.

**Comment by n0bra1n3r** [comment]
Hi guys, this seems to still be happening in NIm 1.2.4. My specific case is that I'm using a generic converter forward-declared with `importcpp("#")`. Here's the error:

```
C:\Src\WorldEngine\main.nim(527, 15) Error: type mismatch: got <ShadowSample, RefCntAutoPtr[Diligent.IEngineFactory], RefCntAutoPtr[Diligent.IRenderDevice], ptr ptr IDeviceContext, int32, ptr ISwapChain>
but expected one of:
proc initialize(this: var ShadowSample; pEngineFactory: ptr IEngineFactory;
               pDevice: ptr IRenderDevice; ppContexts: ptr ptr IDeviceContext;
               numDeferredCtx: int32; pSwapChain: ptr ISwapChain)
  first type mismatch at position: 3
  required type for pDevice: ptr IRenderDevice
  but expression 'this.m_pDevice as RefCntAutoPtr[IRenderDevice]' is of type: RefCntAutoPtr[Diligent.IRenderDevice]

expression: initialize(this, this.m_pEngineFactory as RefCntAutoPtr[IEngineFactory],
           this.m_pDevice as RefCntAutoPtr[IRenderDevice], data(ppContexts),
           numDeferredCtx,
           fromRefCntAutoPtr(this.m_pSwapChain as RefCntAutoPtr[ISwapChain]))
```
Note that the first conversion (for the 2nd param) succeeds, but not for the 3rd (and 6th).

I guess I could use this opportunity to try and contribute if it's an actual bug and you guys think it's an easy fix. :)
