### ISSUE TITLE
tasyncssl crashes when activated

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#9707]
[tasyncssl](https://github.com/nim-lang/Nim/blob/devel/tests/async/tasyncssl.nim) fails when activated

```
exitcode: 1

Output:
tasyncssl.nim(66)        tasyncssl
system.nim(3930)         failedAssertImpl
system.nim(3923)         raiseAssert
system.nim(2970)         sysFatal
Error: unhandled exception: /home/arne/proj/nim/Nim/tests/async/tasyncssl.nim(66, 10) `msgCount == swarmSize * messagesToSend`  [AssertionError]
```

**Comment by skilchen** [comment]
`tasyncssl.nim` does not work with current versions of openssl (1.1.1 and later). As soon as [travis](https://travis-ci.org/) upgrades openssl the test will indeed fail. The test already fails on [appveyor](https://ci.appveyor.com/project/Araq/nim/builds/20209458/tests) and has been disabled to keep the CI green.

**Comment by dom96** [comment]
Merging into https://github.com/nim-lang/Nim/issues/9689
