### ISSUE TITLE
msg field in tester, is not used

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#9708]
In [tcheckedfield1](https://github.com/nim-lang/Nim/blob/devel/tests/objvariant/tcheckedfield1.nim) there is a line ``msg: "Warning: cannot prove that ..."``, but this spec isn't used properly.

I made a test that should fail:

tfoobar.nim
```nim
discard """
  msg: "Warning: cannot prove that field 'x.s' is accessible [ProveField]"
  line:51
  action: compile
"""
```

But this test doesn't fail, it is just a success. There is clearly no warning message from the compiler, it is an empty test. It should fail.

### Possible Solution
The tester needs some automatic testing as well.  Some tests that must fail, if they don't it means the tester is broken.

**Comment by Clyybber** [comment]
The mentioned test uses `nimout` now.
