### ISSUE TITLE
`nimfind` feedback

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9712]
/cc @Araq 

- [ ] why not use a standard output format like json, which is supported everywhere instead of something custom like
```
symbol definition
symbol_usage:col
etc
```

it makes it a lot easier to add fields in a safe manner that won't break backward compatibility
if users want a flat list as currently done, it's trivial to go from json to flat list, but the reverse is not possible in a robust, change-compatible way

optionally, it can even be a flat list of json entries (instead of a single json node) in case we want to pipe stdout lazily without having to parse the entire output, eg:
```
{"type":"def", "file":"foo.nim", "col":32, "line":12}
{"type":"use", "file":"bar.nim", "col":32, "line":12}
{"type":"use", "file":"bar2.nim", "col":32, "line":14}
```

- [x]  `./koch tools` should build nimfind, eg:
```
nim -o:bin/nimfind -d:release -d:nimcore -d:nimfind tools/nimfind.nim
```
=> https://github.com/nim-lang/Nim/pull/9723

- [x] nimfind excludes from the `use` list the symbol we're querying, eg:
```
proc foo(a: int)=
  a.inc # if you query `a` here, that line will be excluded in `use` list
  a.inc
```
this isn't convenient for tools such as refactoring tools that want to rename a symbol

Note: that was by design apparently (see code: `discard "don't output the line we already know"`) but I propose we include it in the list (at least as an option)

- [ ] doesn't seem documented but nimfind seems to return results in the following format, it should be documented
```
symbol definition:line:col
symbol_usage:line:col
etc
```

- [ ] seems like a bug:
```nim
macro fun(args: typed): untyped =
  discard

proc test()=
  fun "ok1"
  fun "ok2"
  "ok2".fun()
```

returns:
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:1:7
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:6:3
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:6:7
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:7:9
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:7:8

I would expect instead:
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:1:7
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:6:3
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t01.nim:7:9

- [x] nimfind seems to return the 1st definition that matches a given line, eg:

```nim
proc bar(x: int) = echo 1

proc bar(x: float) = echo 2

proc fun[T](x: T) =
  bar(x)

proc test()=
  fun(1)
  fun(1.0)

test()
```
nimfind /pathto/bugs/nimfind/t04.nim:7:3
returns:
/pathto/bugs/nimfind/t04.nim:2:6

even though both overloads `bar(int)` and `bar(float)` are matched by `bar` at that line (as exercised in different code paths, since I'm calling `fun(1)` and `fun(1.0)`)

would be nice to instead return a seq of (definition, usage) instead of the (first_definition: string, usage:seq[string])

(which goes back to my other point above about using json instead of custom format, which isn't change-compatible)

**Comment by Araq** [comment]
It uses the format you wrote a PR for, that "every" editor supports. JSON would only complicate matters.

**Comment by timotheecour** [comment]
- [ ] nimfind can't rebuild and query at same time (should either work or give an error)
this doesn't work:
$nimc_D/bin/nimfind --rebuild --project:$timn_D/bugs/nimfind/t01.nim $timn_D/bugs/nimfind/t01.nim:5:4
this works:
$nimc_D/bin/nimfind --rebuild --project:$timn_D/bugs/nimfind/t01.nim
$nimc_D/bin/nimfind $timn_D/bugs/nimfind/t01.nim:5:4

**Comment by timotheecour** [comment]
> It uses the format you wrote a PR for, that "every" editor supports. JSON would only complicate matters.

I'm not talking specifically about file:line:col (that could be `{“type” : “def”, loc: “foo/bar.nim:32:2”}`) which still allows for other fields

**Comment by timotheecour** [comment]
- [ ] multiple definitions:
this `nimfind seems to return the 1st definition that matches a given line, eg:` was marked as solved however I'm now seeing:

$nimc_D/bin/nimfind $timn_D/bugs/nimfind/t04.nim:7:3

/Users/timothee/git_clone/nim/timn/bugs/nimfind/t04.nim:2:6
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t04.nim:7:3
/Users/timothee/git_clone/nim/timn/bugs/nimfind/t04.nim:7:3

**Comment by timotheecour** [comment]
- [ ] need a test suite

**Comment by Araq** [comment]
nimfind is dead.
