### ISSUE TITLE
Infinite loop from generic default RHS dependent upon type

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#9713]
Trying to compile this sends the compiler into an ever growing memory footprint infinite loop:
```Nim
proc foo*[T, W](A, B: openArray[T]; maxVal: W=W(0), unit: W=1.W): W =
  discard
echo foo("hi", "ho", unit=1.5)
```
Presumably, it would crash once RAM is exhausted, but I don't let it get past 16GB.

I was trying to workaround this problem with
```Nim
proc foo*[T, W](A, B: openArray[T]; maxVal: W=W.high, unit: W=1.W): W =
  discard
echo foo("hi", "ho", unit=1.5)
```
which I would be even happier to use, but that fails with 
```
errorway.nim(3, 9) template/generic instantiation of `foo` from here
errorway.nim(1, 48) Error: type mismatch: got <type type(W.high)>
```
So, I'm not sure if it is intended to be supported.  I found some "nearby" issues, but none seemed quite the same.

**Comment by c-blake** [comment]
Perhaps related (but maybe not) this also causes a compiler infinite loop, _without_ runaway memory consumption:
```Nim
type C = int
proc foo*[T](x: openArray[T], maxVal=C.high, unit=1.C): int =
  discard
echo foo("a")
```
It works if you replace `C.high` with `2.C` or something.  Also, the "nearby" issues I meant were https://github.com/nim-lang/Nim/issues/8432 and https://github.com/nim-lang/Nim/issues/8938 .

**Comment by c-blake** [comment]
Especially the second form (just using `sometype.high` as a default initializer) seems like it would be fairly common usage.  It does work fine with `T.high` (same type as generic[]).

**Comment by c-blake** [comment]
As just a slight update - all 3 variants have caused unbounded memory consumption as part of the infinite loop for a while now.  Maybe @Araq can give some guidance as to what he thinks *should* work, in an ideal world?

**Comment by Araq** [comment]
They all should work afaict. If you feel like tinkering with the compiler, I would start with ``koch temp`` and investigate ``compiler/semtypinst.nim`` in particular.

**Comment by c-blake** [comment]
Another slight update, the second form now compiles and runs correctly (i.e.,  `type C =int` ... `maxVal=C.high`).  The initial form still infinite loops.  Probably best to leave the issue open until that's resolved.

**Comment by narimiran** [comment]
> The initial form still infinite loops.

Cannot reproduce with Nim devel 1.1.1 for neither of three examples.

**Comment by c-blake** [comment]
Thanks for noticing that this needed updating/closing.  I can confirm the problem seems gone on recent Nim's.
