### ISSUE TITLE
Minor issues in docs regarding keywords

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#9725]
- [Relevant section](https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords): `unsafeAddr` is not listed as a keyword, I think it should be added as it functions similar to `addr` but has special semantics with `let`.
- [Relevant section](https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality): The section on identifier partial case insensitivity should be expanded to mention that the same follows for keywords.

**Comment by krux02** [comment]
I would like to add, that we plan to emit warnings, when a keyword isn't the standard way of using a keyword. For example `vA_r` is identical to `var` but it is certainly counterproductive to ever use it.

**Comment by awr1** [comment]
Is the "canonical" way to type out identifiers just all lowercase? No `notIn` or `isNot`, rather `notin` and `isnot`?

**Comment by Araq** [comment]
Yes, ``notin`` and ``isnot``.
