### ISSUE TITLE
styledEcho does not show any color/style in msys2 mingw64 shell

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#9729]
I am using 
```bash
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2018-11-11
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 37d88e5168508870d69a990e5002a9ea113843f9
```
on my Windows7 64 bits. The following code from https://scripter.co/notes/nim
```nim
import terminal
styledEcho "unstyled text", styleBright, fgGreen, "[PASS]", resetStyle, fgGreen, " Yay!"
styledEcho "unstyled text", styleBright, fgRed, "[FAIL]", resetStyle, fgRed, " Nay :("
```
shows only gray characters in msys2 mingw64 shell
```
unstyled text[PASS] Yay!
unstyled text[FAIL] Nay :(
```

however, it will show colorful characters in the DOS prompt

**Comment by Araq** [comment]
Windows exposes an API for this, we use the Windows API for this, we cannot fix your broken msys2 shell.

**Comment by andrewgohlk** [comment]
Hi,
I know this issue was considered closed.
But I found that we could use 'terminal' & 'termstyle' lib accordingly, depending on the terminal-type as follows:

```
import terminal as tm, termstyle as ts

if tm.isatty(stdout):
  # User terminal for Windows CMD console.
  tm.styledEcho tm.fgRed, tm.styleBright, "My bright red text in Win-CMD console."
else:
  # Use termstyle for MSYS2 xterm console.
  echo ts.red ts.bold "My bright red text in MSYS2-xterm console."
```

Not sure if we can create a template to wrap around the different formats, as I'm new to Nim-lang too.
