### ISSUE TITLE
deprecate typedesc in favor of type

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9731]
```nim
var x: int = 0
proc foo(T: type): var T = x
foo int
```
```
template/generic instantiation of `foo` from here
inim_1542371335.nim(4, 28) Error: type mismatch: got <int> but expected 'None'
```

**Comment by bluenote10** [comment]
According to the [typedesc reforms PR](https://github.com/nim-lang/Nim/pull/7681), `proc(T: type)` is now the same as `proc(T: typedesc)`, isn't it? Why should it be forbidden again?

**Comment by narimiran** [comment]
> `proc(T: type)` is now the same as `proc(T: typedesc)`, isn't it? 

Yes, the original example throws the same error regardless if one uses `type` or `typedesc`. Analogously, @krux02's example works whichever version you use.

**Comment by krux02** [comment]
I wasn't aware of that PR. I guess  then typedesc should be deprecated in favor of type. I don't like it when things can be referred by different names.

**Comment by mratsim** [comment]
This seems like a better test case, the original one is actually a closure which might brings yet other issues:

```Nim
var x: int = 0

proc foo(T: type, x: var T): var T = x
foo(int, x)
```
```
Error: type mismatch: got <type int, int>
but expected one of:
proc foo(T: type; x: var type): var type
  first type mismatch at position: 2
  required type: var None
  but expression 'x' is of type: int

expression: foo(int, x)
```

**Comment by Araq** [comment]
No, we should deprecate ``type`` in favour of ``typedesc``.
