### ISSUE TITLE
genOid has low entropy (creates lots of 0 bits)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9741]
root cause of:
[[critical] inserted oid's have low entropy with lots of 0's (5bef5960c7dcd43e00000001 instead of 5bef58c408de32fe5a33a29b) · Issue #65 · SSPkrolik/nimongo](https://github.com/SSPkrolik/nimongo/issues/65)

here's the D implementation for reference (which doesn't have this problem):
https://github.com/vibe-d/vibe.d/blob/ce494843201f15899353e6bfcdcbead3872c751c/data/vibe/data/bson.d#L900
```d
	/** Generates a unique object ID.
	 *
	 *   By default it will use `Clock.currTime(UTC())` as the timestamp
	 *   which guarantees that `BsonObjectID`s are chronologically
	 *   sorted.
	*/
	static BsonObjectID generate(in SysTime time = Clock.currTime(UTC()))
	{
		import std.datetime;

		BsonObjectID ret = void;
		ret.m_bytes[0 .. 4] = toBigEndianData(cast(uint)time.toUnixTime())[];
		ret.m_bytes[4 .. 7] = toBsonData(MACHINE_ID)[0 .. 3];
		ret.m_bytes[7 .. 9] = toBsonData(cast(ushort)ms_pid)[];
		ret.m_bytes[9 .. 12] = toBigEndianData(ms_inc++)[1 .. 4];
		return ret;
	}
```

**Comment by narimiran** [comment]
Closed by #10248.

**Comment by timotheecour** [comment]
issue remains, despite fact it was moved to graveyard; depending on outcome of https://github.com/nim-lang/Nim/pull/10248#issuecomment-453306831 we should migrate this issue to graveyard or re-open

**Comment by narimiran** [comment]
Fixed by https://github.com/nim-lang/Nim/commit/9ac0cbdd51e838bbe4b040ac2df67fa050e6ac07

**Comment by timotheecour** [comment]
ok after https://github.com/nim-lang/Nim/pull/10500 results are at least consistent with what D (vibe.d) and mongo (shell) produce from within 1 thread
```d
    foreach(i;0..10){
      auto id = BsonObjectID.generate();
      writeln(id);
    }
```
```
>for(i=0;i<10;i++) {x = ObjectId(); print(x);}
5c52a121aea679ec63a6d23b
5c52a121aea679ec63a6d23c
5c52a121aea679ec63a6d23d
5c52a121aea679ec63a6d23e
5c52a121aea679ec63a6d23f
5c52a121aea679ec63a6d240
5c52a121aea679ec63a6d241
5c52a121aea679ec63a6d242
5c52a121aea679ec63a6d243
5c52a121aea679ec63a6d244
```
