### ISSUE TITLE
Backticked vars misinterpreted by quote do: when creating pragmas

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#9745]
I'm using macros to create types with `quote do:` but added pragmas are not working correctly since backticked variables are interpreted incorrectly.

### Example
```nim
import macros

var
  typ {.compiletime.} = "struct ABC"
  name {.compiletime.} = "ABC".newIdentNode()

macro abc(): untyped =
  result = newNimNode(nnkStmtList)

  result.add(quote do:
    type `name` {.importc: `typ`.} = object
  )

  echo result.repr

abc()
```

### Current Output
```
type
  ABC {.importc: 3.} = object
```

### Expected Output
```
type
  ABC {.importc: "struct ABC".} = object
```

Note that `name` is interpreted correctly, only contents in side the pragma section are misinterpreted. If you add more elements - e.g. `header` or something else, you get numbers again.

**Comment by genotrance** [comment]
Thanks for sharing. If `quote do:` is unreliable, is `parseStmt()` better? Makes the code readable. That being said, since this is a library I'm working on, I want reliable interpretation so let me know if writing full trees is worth it.

**Comment by alehander42** [comment]
https://github.com/alehander42/breeze this might make it a bit easier to build trees too.

**Comment by genotrance** [comment]
Thanks I'll check it out. For now I'm using parseStmt because it is a bit more readable than building full trees.

**Comment by mratsim** [comment]
I've also noticed that the symbol pass for importc and exportc is done very early. For example it is done before template are expanded here: https://github.com/nim-lang/Nim/issues/9366.

**Comment by krux02** [comment]
current output:

```
type
  ABC {.importc: "struct ABC".} = object
```
