### ISSUE TITLE
lldb can't continue on NilAccessError, stuck after EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9753]
nim c --debugger:native bugs/lldb/t01.nim
lldb bugs/lldb/t01

```
import segfaults

proc main =
  try:
    var x: ptr int
    echo x[]
  except NilAccessError:
    echo "caught a crash!"

echo "ok1"
main()
echo "ok2"
```

```
(lldb) r
Process 54064 launched: '/tmp/nim/app' (x86_64)
ok1
Process 54064 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001000112df app main_uF9bc3kVsWoixdO2cWVyMwg + 239 at /Users/timothee/git_clone/nim/timn/bugs/lldb/t01.nim:6
   3    proc main =
   4      try:
   5        var x: ptr int
-> 6        echo x[]
   7      except NilAccessError:
   8        echo "caught a crash!"
   9
Target 0: (app) stopped.
(lldb) c
Process 54064 resuming
Process 54064 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001000112df app main_uF9bc3kVsWoixdO2cWVyMwg + 239 at /Users/timothee/git_clone/nim/timn/bugs/lldb/t01.nim:6
   3    proc main =
   4      try:
   5        var x: ptr int
-> 6        echo x[]
   7      except NilAccessError:
   8        echo "caught a crash!"
   9
Target 0: (app) stopped.
```

## note
I'm on OSX (mojave)
can't test on gdb because of https://stackoverflow.com/questions/52529838/gdb-8-2-cant-recognized-executable-file-on-macos-mojave-10-14 as mentioned here https://github.com/nim-lang/Nim/issues/9634

**Comment by timotheecour** [comment]
not necessarily, see https://github.com/nim-lang/Nim/issues/9634#issuecomment-436872126 for another case where c++ code works but not nim code, with lldb; 
for this issue, I haven't investigated c++ case

**Comment by alaviss** [comment]
I still don't see why this is a Nim bug. It's the compiler job to generate code that works correctly natively. The fact that it doesn't work on LLDB is an LLDB bug. You can't compare with C++ because of the differences between implementation of underlying functions and exceptions. I think you should raise this to the LLVM bug tracker. I'm certain that LLDB developers would be interested in it.

**Comment by timotheecour** [comment]
update: I tried using same technique as in https://github.com/nim-lang/Nim/issues/9634#issuecomment-443568939 ; result:
* on OSX high sierra, 10.13.6, lldb has same issue; gdb works
* on OSX mojave, lldb has the issue; gdb works

conclusion: this time, it's an lldb issue, unlike #9634

**Comment by timotheecour** [comment]
update: 
this could be root cause: https://stackoverflow.com/questions/26829119/how-to-make-lldb-ignore-exc-bad-access-exception
also related: https://bugs.llvm.org/show_bug.cgi?id=22868

> lldb always stops on EXC_BAD_ACCESS and will not continue. The result is SIGSEGV cannot be passed. That is, this does not work:
process handle SIGSEGV --stop false --pass true --notify false
Programs that expect to continue processing by turning SIGSEGV into an exception cannot be run under lldb. In particular this affects the Go programming language:

there are embryos of solutions here: https://stackoverflow.com/questions/26829119/how-to-make-lldb-ignore-exc-bad-access-exception

**Comment by krux02** [comment]
I tested on gdb. Works flawlessly.

**Comment by Araq** [comment]
Try to compile with ``-d:noSignalHandler``.

**Comment by timotheecour** [comment]
just did, same issue; I'm pretty sure the culprit lies in https://github.com/nim-lang/Nim/issues/9753#issuecomment-443636916
unfortunately, gdb is really in bad state on OSX (see https://github.com/Homebrew/homebrew-core/issues/34750

> If upstream refuses to fix macOS versions and nobody submits fixes to it, it might be better to pull gdb from homebrew completely and leave the patching to a tap. From homebrews perspective, fixing software and releasing that fixed software is up to upstream, debian openssl maintainers can probably tell you what a bad idea it is to leave patches to the packagers.

so arguments like "only gdb is supported" by Nim doesn't really help if you're on OSX; my hope is stuff like https://stackoverflow.com/questions/26829119/how-to-make-lldb-ignore-exc-bad-access-exception is fixable and lldb should be worthy of keeping as a supported option (it really mostly works apart from that, and has more modern codebase, more traction / features compared to gdb IIUC)

**Comment by timotheecour** [comment]
filed https://bugs.llvm.org/show_bug.cgi?id=40669, following up there
