### ISSUE TITLE
Nimpretty calculates line length incorrectly

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#9769]
Nimpretty currently breaks up lines that are longer than 77 characters, but it should only break up lines that are longer than 80 characters.

### Input
Line below is 78 characters long, so it should not be changed by nimpretty.
```nim
var FOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO: string = 1 + 2 + 3
```

### Output
```nim
var FOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO: string = 1 + 2 +
    3
```

**Comment by randydsmithjr** [comment]
I do believe it is because of the comment in layouter.nim for the softLinebreak function, correct me if I'm wrong.
# XXX Use an algorithm that is outlined here:
# https://llvm.org/devmtg/2013-04/jasper-slides.pdf
# +2 because we blindly assume a comma or ' &' might follow

**Comment by Araq** [comment]
The algorithm works better with this +2. :-)
