### ISSUE TITLE
`pairs` iterator calling a helper proc with tuple return type will cut the iterator yield into half

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#9778]
The combination of `pairs` iterator calling a helper proc with tuple return type will cut the iterator yield into half with strange output. Other helper proc with different return type don't exhibit this behaviour, only helper proc with **tuple** return type.

### Example
```nim
proc iterAux(a: seq[int], i: var int): (int, int) =
  result = (a[i], a[i])
  inc i

iterator pairs(a: seq[int]): (int, int) =
  var i = 0
  while i < a.len:
    yield iterAux(a, i)

var x = newSeq[int](10)
for i in 0 ..< x.len:
  x[i] = i

for k,v in x:
  echo k, v
```

### Current Output
```
01
23
45
67
89
```

### Expected Output
```
00
11
22
33
44
55
66
77
88
99
```
### Additional Information
* change the helper proc return type to object will remove the problem
* add temporary variable before `yield` will remove the problem e.g. using let or var
* if the tuple consist of three element, the yield also become third of expected length
* looks like it call the helper proc proportional to the number of tuple elements

**Comment by LemonBoy** [comment]
The problem is easy to spot if you look at the post-`transf` AST:

```nim
var
  k
  v
var i = 0
block :tmp154185:
  while i < len(x):
    k = iterAux(x, i)[0]
    v = iterAux(x, i)[1]
    echo [k, v]
```
The easy solution is to save the result of `iterAux` into a temporary variable and then slice it but that may introduce an extra copy...

**Comment by jangko** [comment]
This is still a valid issue.

**Comment by ringabout** [comment]
I bump the priority, since it has been reported multiple times.

**Comment by disruptek** [comment]
The priority should be adjusted not because it's been reported multiple times -- after all, I myself reported it twice -- but because it's a serious bug.  If it's not going to be fixed soon, please add some documentation about the fact that iterators don't work correctly.  Three years is too long.

**Comment by Araq** [comment]
```nim

proc transformYield(c: PTransf, n: PNode): PNode =
  ...
  # XXX: BUG: what if `n` is an expression with side-effects?
```
