### ISSUE TITLE
NilAccessError in Nim DLL without NimMain() initial call

### ISSUE THREAD

**Issue by jfb** [nim-lang/Nim#9792]
`mono.nim`  create windows dll

```nim
import strutils
import algorithm
import segfaults 

proc sort_str(str:cstring):cstring {.stdcall, exportc, dynlib .} =
    var tmp = $str
    result = tmp.split("&").sorted(cmp).join("")
```
build command

>nim c --app:lib mono.nim

`test1.py` call `sort_str` 

```python
import ctypes

dll = ctypes.WinDLL("mono.dll")
#dll.NimMain()

if __name__ == '__main__':
    for i in range(1000000):
        r = dll.sort_str(ctypes.create_string_buffer("aaaaa&bbbbbb&eee&e12312&sdfsdf&werwer&sdfsddsf&sdfwerw&sdfwerw&werwe&sdfsdfsee&ffffff&ffff"))
```
without `dll.NimMain()`  will cause [NilAccessErro] erro

```
python test1.py
mono.nim(7)              sort_str
strutils.nim             split
gc.nim(482)              newSeq
gc.nim(475)              newObj
alloc.nim(781)           rawAlloc
Error: unhandled exception:  [NilAccessError]
```
nim version

```
Nim Compiler Version 0.19.0 [Windows: i386]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release
```

gcc version
```
gcc version 6.3.0 (i686-win32-dwarf-rev1, Built by MinGW-W64 project)
```

Is NimMain not executing?

**Comment by tim-st** [comment]
Not related to the `NilAccessError` issue but you can workaround this without an explicit call to `NimMain()` by using `nimpy`:
`nimble install nimpy@#head`

`mono.nim`
```nim
import nimpy

import strutils
import algorithm

proc sort_str(s: string): string {.exportpy.} =
  s.split('&').sorted().join()
```
Compile on windows using `nim c -d:release --app:lib --out:mono.pyd mono.nim`

Then create a python file `test.py`:

```python
import mono

if __name__ == '__main__':
    for i in range(1000000):
        r = mono.sort_str("aaaaa&bbbbbb&eee&e12312&sdfsdf&werwer&sdfsddsf&sdfwerw&sdfwerw&werwe&sdfsdfsee&ffffff&ffff")

    print("finished :)")
```

**Comment by jfb** [comment]
Thank you for your help, pyd is working fine. But I want to generate a generic windows dll, such as can be called by `VB`.

**Comment by mratsim** [comment]
It's in the documentation, you have to call NimMain to initialise Nim internals: https://nim-lang.org/docs/backends.html#interfacing-backend-code-calling-nim.

This is especially true for code that relies on the GC like strutils. Though in the future with `destructors` we might not need a NimMain at all.

Does that answer you?

**Comment by jfb** [comment]
thx.
