### ISSUE TITLE
Release notes are not DRY enough

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#9801]
Just looked at Crystal's release note: Compare that to Nim's introducing noise:

https://crystal-lang.org/2018/11/01/crystal-0.27.0-released.html

https://nim-lang.org/blog/2018/09/26/version-0190-released.html

```
The Nim team is happy to announce that the latest release of Nim, version 0.19.0, is now available. Nim is a systems programming language that focuses on performance, portability and expressiveness.
Installing 0.19.0

If you have installed a previous version of Nim using choosenim, getting Nim 0.19.0 is as easy as:

$ choosenim update stable

If you don’t have it already, you can get choosenim by following these instructions or you can install Nim by following the instructions on our install page.
```

Of course it is a minor issue, but one really gets tired when reading again and again. I guess it is automatically generated, and hoped it would disappear at some point in time.

The text "Nim is a systems ..." does really not belong at this location. "The Nim team is happy ..." -- well when I want to learn about latest Rust release, I do not care much about feelings of it devs.

Finally, the choosenim section, which is new since a few releases: Maybe OK, but it is covered by the Download/Install page already.

**Comment by StefanSalewski** [comment]
One more remark: As Araq already noted some years ago, announcement of a new release does not fit well under BLOG field, NEWS would be much better. But I think that would be hard to change in Nim's Homepage.

**Comment by GULPF** [comment]
Since the release blog posts are often posted on reddit, many people that are unfamiliar with Nim will read them (in fact, that's how I found Nim). For that reason it's good to have a small description of what Nim is in every release post.

**Comment by StefanSalewski** [comment]
Indeed, for posting it on reddit it is fine, so I will close this.
