### ISSUE TITLE
--gc:destructors and --threads:on: hello world does not compile

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#9809]
```nim
echo "hello world"
```
compilation fails if you add ``--gc:destructors --threads:on`` compilation switches.
Error:
```
Hint: system [Processing]
lib\system\threads.nim(43, 10) Error: You must not import this module explicitly
```

**Comment by jfb** [comment]
`threads off`

```
λ nim c --gc:destructors --threads:off hello.nim
Hint: used config file 'd:\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
..\..\..\d:\nim\lib\pure\typetraits.nim(41, 3) Error: undeclared identifier: 'runnableExamples'
```

**Comment by Araq** [comment]
I'm actively working on ``--gc:destructors`` and sadly once this compiles the compiler would still generate wrong code for Nim's builtin string destructors.

**Comment by cooldome** [comment]
Is it `destroyer.nim` problem? I don't mind helping if you have a test case

**Comment by Araq** [comment]
No, the problem lies somewhere else. The instantiation of ``seq[string]`` within system.nim lacks a properly generated sink operation. But sure, you can look into it, the bug is in some compiler place that you've seen by now. :-)

**Comment by cooldome** [comment]
works well now. Closed.
