### ISSUE TITLE
nimpretty messes alignment, after import statement

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#9811]
example:
```
import future,
       strutils

proc issue() =
       echo "formatting issue"
```

nimpretty remembers the indentation from the import block, and uses it later on.

**Comment by nc-x** [comment]
Reopen? AFAICT, this didn't get fixed by https://github.com/nim-lang/Nim/issues/9811, it was only a documentation change.

**Comment by Araq** [comment]
By design nimpretty detects the indentation by the first "section of spaces" that it encounters. Use ``--indent:2`` switch to prevent it from doing that.
