### ISSUE TITLE
Emscripten and cpp compiler don't work

### ISSUE THREAD

**Issue by rrenderr** [nim-lang/Nim#9812]
Made a little sample:
test.nim
  echo "Hello world!"

1. Compile it to C
nim c --cc:clang 
--clang.exe=C:/emsdk/emscripten/1.37.1/emcc.bat 
--clang.linkerexe=C:/emsdk/emscripten/1.37.1/emcc.bat 
--os:linux "--cpu:i386" --passC:-v test.nim

All work fine and compiler includes paths in log looks like:
C:\\emsdk\\emscripten\\1.37.1\\system\\lib\\libcxxabi\\include" 
C:\\emsdk\\emscripten\\1.37.1\\system\\include\\compat
...
C:\\emsdk\\emscripten\\1.37.1\\system\\include\\SDL 

2. Compile it to CPP
nim cpp  --cc:clang 
--clang.exe=C:/emsdk/emscripten/1.37.1/emcc.bat 
--clang.linkerexe=C:/emsdk/emscripten/1.37.1/emcc.bat 
--os:linux "--cpu:i386" --passC:-v test.nim

There are 3 issues: Invalid architecture, invalid include search path and wrong Defines (there are no defines __EMSCRIPTEN_major__ -D __EMSCRIPTEN_minor__ e.t.c.).

Compiler Includes paths in log looks like:
 C:\Users\agt\.choosenim\toolchains\nim-0.19.0\lib
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include
 C:\Program Files (x86 10\include\10.0.16299.0\ucrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared
 C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um
 C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt
fatal error: 'sys/mman.h' file not found

**Comment by Araq** [comment]
That's not a Nim bug.
