### ISSUE TITLE
Cannot use a case object as table key

### ISSUE THREAD

**Issue by sid-code** [nim-lang/Nim#9815]
It is not possible to use a case object as a table key. The `newTable[CaseObject, CaseObject]()` proc will not compile. `initTable[CaseObject, CaseObject]()` will compile, but something like `table[key] = val` will not compile, producing the same error as `newTable` (the error is shown below).

This strikes me as odd, as there is a clear example of this being done in [this StackOverflow answer](https://stackoverflow.com/questions/38133424/any-types-in-tables-table-like-sets-in-nim). The code in the answer isn't 100% correct but fixing up the minor issues leads to the same issue here. This leads me to believe that this issue is a regression.

This compile message shows up using the compiler built from a pull from devel a couple of minutes ago.

### Example
```nim
import tables
import hashes

type
  VariantKind = enum K1, K2
  VariantType = object
    case kind: VariantKind
      of K1: num: int
      of K2: chr: char

# dummy useless hash
proc hash(v: VariantType): Hash = !$0

# option 1: use a Table
var vtable = initTable[VariantType, VariantType]()
let v1 = VariantType(kind: K1, num: 5)
vtable[v1] = v1 # <-- Error: parallel 'fields' iterator does not work for 'case' objects

# option 2: use a TableRef
let vtableref = newTable[VariantType, VariantType]()
# that error now is thrown for the above line
```

### Current Output
```
test.nim(37, 13) template/generic instantiation of `[]=` from here
/home/sid/Nim/lib/pure/collections/tableimpl.nim(98, 21) template/generic instantiation of `raw
Get` from here                                           
/home/sid/Nim/lib/pure/collections/tableimpl.nim(37, 48) template/generic instantiation of `==`
 from here                                               
/home/sid/Nim/lib/system.nim(2621, 3) Error: parallel 'fields' iterator does not work for 'case
' objects                                    

```

### Expected Output
successful compilation

**Comment by Araq** [comment]
You also need to implement a ``==`` operator that works for your case object. The error message says "instantiation from here" for the system's equality operator which is insufficient. Not ideal, but no bug here and it can be found out by reading the table's module documentation here https://nim-lang.org/docs/tables.html
