### ISSUE TITLE
{.compileTime.} procs do not update compileTime var

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9817]
cc @alaviss and @krux02, linked to the proposal to remove static return types https://github.com/nim-lang/Nim/pull/9686 and https://github.com/nim-lang/Nim/issues/8051.

The following does not work as expected with compileTime pragma:

```Nim
template initArrayWith*(idx, generator: untyped): untyped =
  var result: array[idx, type(generator)]
  for mval in mitems result:
    mval = generator
  result

var state {.compileTime.} = 0
proc fill(): int {.compileTime.} =
  result = state
  inc state
  
var stateRT = 0
proc fillRT(): int =
  result = stateRT
  inc stateRT

const Arr = initArrayWith(1..10, fill()) # [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
echo Arr
let a = initArrayWith(1..10, fillRT()) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
echo a
```

Switching to a static return type instead we have the proper result at compile-time

```Nim
template initArrayWith*(idx, generator: untyped): untyped =
  var result: array[idx, type(generator)]
  for mval in mitems result:
    mval = generator
  result

var state {.compileTime.} = 0
proc fill(): static int =
  result = state
  inc state

var stateRT = 0
proc fillRT(): int =
  result = stateRT
  inc stateRT

const Arr = initArrayWith(1..10, fill())
echo Arr
let a = initArrayWith(1..10, fillRT())
echo a
```

**Comment by deech** [comment]
https://github.com/nim-lang/Nim/commit/f86b827d9e10f0178f1bb89d1c7df8c6b7b7eba0 seems to fix your issue.

**Comment by mratsim** [comment]
it seems completely unrelated though.

**Comment by deech** [comment]
You're right. It doesn't fix the issue, I ran the wrong version of your code.

**Comment by deech** [comment]
I took another run at this issue and I think I know why the problem is occurring but don't know how to fix it. If someone is willing to help I can cut a PR.

I have simplified the above example to:
```
template t(s: untyped): untyped =
  var x : array[3,int]
  for i in mitems x:
    i = s
  x

var x {.compileTime.} : int = 0
proc p(): int {.compileTime.} =
  result = x
  inc x

const C = t(p())
echo C
```

It reproduces the bug by outputting `[0,0,0]` but this variation of the template does the right thing:
```
template t(s: untyped): untyped =
  var x : array[3,int] = [s,s,s]
  x
```

It outputs what we want:
```
[0,1,2]
```

This indicates that when the `{.compileTime.}` pragma is enabled template parameters are evaluated earlier than they should be so instead of expanding to:
```
  var x : array[3,int]
  for i in mitems x:
    i = p()
  x
```

it's doing:
```
  var x : array[3,int]
  for i in mitems x:
    i = 0
  x
```
 
and the version where the for loop is explicitly unrolled expands to:
```
  var x : array[3,int] = [p(),p(),p()]
  x
```

which is why it does the right thing.

One approach to solving this might be to not evaluate `proc` calls in a template's argument list and instead splice in an explicit call wherever it's used in the template. As I said, if someone wants to point me in the right direction I can try and fix it.

**Comment by deech** [comment]
If there's confusion about why the example above is outputting [0,0,0] instead of `[1,1,1]` as in the original:
```
template initArrayWith*(idx, generator: untyped): untyped =
  var result: array[idx, type(generator)]
  for mval in mitems result:
    mval = generator
  result
```

I think it's because the `type(generator)` results in a compile time function call to `fill` so it expands to something like:
```
template initArrayWith*(idx, generator: untyped): untyped =
  var result: array[idx, type(0)]
  for mval in mitems result:
    mval = 1
  result
```

**Comment by Araq** [comment]
Sounds good.

**Comment by krux02** [comment]
Well, global compile time state is problematic anyway. It will cause problems with incremental compilation. Here is a version that works without global compile time state.

```Nim
template initArrayWith*(idx, generator: untyped): untyped =
  let gen = generator
  var result: array[idx, type(gen())]
  for mval in mitems result:
    mval = gen()
  result

proc genFill(): proc(): int =
  var state = 0
  proc myFill(): int =
    result = state
    state += 1
  return myFill

const Arr = initArrayWith(1..10, genFill()) # [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
echo Arr
let a = initArrayWith(1..10, genFill()) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
echo a
```
