### ISSUE TITLE
range expression (`..`) with `<` fails to compile when used in case statement

### ISSUE THREAD

**Issue by erhlee-bird** [nim-lang/Nim#9819]
The following snippet fails to compile with a choosenim downloaded version of Nim 0.19.0.

When using the `..` operator and `<` operator together in a case statement without a space between them, the code doesn't compile..

```nim
  proc test(x: int) =
    case x:
      of 0 ..< 2:
        echo "yes"
      else:
        echo "no"

  test(0)
  test(1)
  test(2)
```

```sh
.choosenim/toolchains/nim-0.19.0/lib/system.nim(336, 6) Error: type mismatch: got <HSlice[system.int, system.int]> but expected 'int'
```

When I put at least one space between the `..` operator and the `<` operator, the code works as expected, but I do get a deprecation warning using 0.19.0.

```nim
  proc test(x: int) =
    case x:
      of 0 .. < 2:
        echo "yes"
      else:
        echo "no"

  test(0)
  test(1)
  test(2)
```

```sh
  a.nim(3, 13) Warning: < is deprecated [Deprecated]
  yes
  yes
  no
```

Looking up documentation on https://nim-lang.org/docs/system.html for `..`, I get the following.

> binary slice operator that constructs an interval [a, b], both a and b are inclusive. Slices can also be used in the set constructor and in ordinal case statements, but then they are special-cased by the compiler.  

I think this is either a bug or a special case as described above.

**Comment by andreaferretti** [comment]
I think it should work. Just mentioning that `..<` is an operator in itself, it is not the composition of the `..` and `<` operators. The `<` unary operator has been deprecated since it was alwyas meant to be used in combination with `..` anyway, so `..<` is the preferred method for exclusive ranges at this point.

**Comment by Araq** [comment]
The ``case`` statement doesn't use the ``..`` operator, it's syntax built into the case statement. The compiler is correct with this error message.

**Comment by mratsim** [comment]
I think a specific error message for using `..<` in a case statement would be helpful.

Currently we get
```Nim
var x = 10
case x
of 0 ..< 3:
  echo "match"
else:
  echo "not match"
```
```
system.nim(500, 24) Error: type mismatch: got <HSlice[system.int, system.int]> but expected 'int'
```

So the error doesn't even reference the case statement call site.
