### ISSUE TITLE
Type paremeters in templates fail to compile

### ISSUE THREAD

**Issue by flaviut** [nim-lang/Nim#982]
``` nimrod
template foo[T](body: stmt): stmt {.immediate.} =
    var b: T
    body

foo[int]():
    discard "" # Anything else too
```

fails to compile with `Error: wrong number of arguments`, while replacing the T with a `typedesc` of the same name compiles fine: 

``` nimrod
template foo(T: typedesc, body: stmt): stmt {.immediate.} =
    var b: T
    body

foo(string):
    discard "" # Anything else too
```

has no issues compiling.

Edited as per zah's remark.

**Comment by Araq** [comment]
The code works without the ``.immediate`` and immediate templates are deprecated for a while now. Closing.
