### ISSUE TITLE
quit() fails with "unreachable statement after 'return'"

### ISSUE THREAD

**Issue by smithtim** [nim-lang/Nim#9832]
The following fails to compile, giving: `Error: unreachable statement after 'return'`

```nim
echo "hello"
quit()
echo "goodbye"
```
Is this expected behavior?

If so, it might be worth mentioning in the documentation that `quit` does not supersede the requirement that all code must be reachable.  https://nim-lang.org/docs/system.html#quit%2Cint

The error message could also be improved to `Error: unreachable statement after 'quit'`.

**Comment by timotheecour** [comment]
note: sometimes adding early return (or early quit) is useful during debugging ; one way to avoid this error is to write instead:
`if true: return` (probably shd work w `if true: quit()` too)

**Comment by GULPF** [comment]
This is the expected behavior. This happens for all procs marked with the `{.noReturn.}` pragma, not only `quit()`. The error message could definitely be improved

**Comment by smithtim** [comment]
I agree with @timotheecour that early return/quit can be useful in debugging.  My own preference would be for reachability checking to be disabled by default.  Reachability cannot be fully checked anyway, since it is an undecidable property related to the halting problem.

Is there a way to disable reachability checking?  I don't see one in the compiler docs. https://nim-lang.org/docs/nimc.html

**Comment by timotheecour** [comment]
maybe the error msg could mention the `if true: return` workaround

**Comment by Araq** [comment]
> Reachability cannot be fully checked anyway, since it is an undecidable property related to the halting problem.

That's true for almost every analysis a compiler might attempt and hence an invalid argument.
