### ISSUE TITLE
`nim c -r main.nim foo1 "" foo3` doesn't handle empty params or params w quotes

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9842]
`nim c -r main.nim foo1 "" foo3` skips empty param:

```nim
import os
proc main()=
  echo commandLineParams()
main()
```
```
nim c -r $timn_D/tests/nim/all/t0016.nim foo1 foo2 "" foo4
@["foo1", "foo2", "foo4"]
# expected: @["foo1", "foo2", "", "foo4"]
```

it works only if we compile first, and THEN run
```
$timn_D/tests/nim/all/t0016 foo1 foo2 "" foo4
@["foo1", "foo2", "", "foo4"]
```

in D, this works fine:
```d
import std.stdio;
void main(string[]args){
  writeln(args);
}
```

dmd -run $timn_D/tests/nim/all/t0017.d foo1 foo2 "" foo3
["/var/tmp/dmd_run080TTh", "foo1", "foo2", "", "foo3"]

**Comment by Araq** [comment]
And once it "works" it's totally obfuscated code that should be rewritten.

**Comment by timotheecour** [comment]
it's also broken with arguments that contain quotes or single quotes; I wrote a PR that fixes this and adds test case, see https://github.com/nim-lang/Nim/pull/10291
