### ISSUE TITLE
`deprecated` proc called from bar.nim doesn't give deprecation warning if bar.nimble exists

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9854]
/cc @dom96 @Araq 
Is this by design? I'm not seeing it documented anywhere

BUG: `nim c ~/temp/bar/bar.nim` gives no warning (when ~/temp/bar/bar.nimble is present)
OK: `nim c -d:case1 ~/temp/bar/bar.nim` gives deprecation warning
OK: if you remove ~/temp/bar/bar.nimble, `nim c ~/temp/bar/bar.nim` now gives a warning

/pathto/foo.nim:
```nim
proc funAux*() {.deprecated.} =
  discard
proc fun*()=
  funAux()
```

~/temp/bar/bar.nimble: (empty)
~/temp/bar/bar.nim:
```nim
import "/pathto/foo.nim"
proc main()=
  fun()
  when defined(case1):
    funAux()
main()
```

**Comment by GULPF** [comment]
Seems like the expected behavior to me. Why would Nim warn you about using deprecated procs in code that the package doesn't own?

**Comment by narimiran** [comment]
> Seems like the expected behavior to me. 

Closing.
