### ISSUE TITLE
parseutils.parseInt shouldn't use an exception that inherits from system.Defect

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#9857]
Exceptions that inherit from `system.Defect` are only supposed to be raised as a result of programmer mistakes. However, `parseutils.parseInt` raises `OverflowError` when parsing fails, which is clearly not a programmer mistake. It should raise a `ValueError` or similar instead.

Note that `strutils.parseInt` claims it raises a `ValueError` when parsing fails, but since it uses `parseutils.parseInt` internally it will raise _either_ a `ValueError` or a `OverflowError`.

Fixing this would be a breaking change.

**Comment by Araq** [comment]
Ok, but we should do it.

**Comment by Araq** [comment]
I don't think your proposed solution is wise. Parsing a number that happens to overflow is really different from not parsing a number at all. It should produce different error messages when exposed to a human being, for example.

**Comment by Araq** [comment]
Seems to be an oversight indeed.
