### ISSUE TITLE
`Error: internal error: genLiteral: ty is nil` when a `var` is accessed in `quote do`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9864]
/cc @Araq 
here's a minimal test case after a really painful reduction from cligen /cc @c-blake

```nim
import macros, tables

proc bar(shOpt: Table[string, int])=discard

macro dispatchGen(): untyped =
  var shOpt = initTable[string, int]()
  shOpt["foo"] = 10
  result = quote do:
     bar(`shOpt`)

dispatchGen()
```

 nim c -r $timn_D/bugs/all/t0027.nim
```
/Users/timothee/git_clone/nim/timn/bugs/all/t0027.nim(15, 12) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/all/t0027.nim(15, 12) template/generic instantiation from here
???(0, 0) Error: internal error: genLiteral: ty is nil
```

## note: 
/cc @krux02 
* could be related to https://github.com/nim-lang/Nim/issues/9607  but probably not a dup, since the code presented here should be valid (and the fix suggested here https://github.com/nim-lang/Nim/issues/9607#issuecomment-435710210 doesn't apply here)
also, since I found these other bugs while trying to debug this, the following could be related too:
* maybe related to https://github.com/nim-lang/Nim/issues/9866
* maybe related to https://github.com/nim-lang/Nim/issues/9865

**Comment by timotheecour** [comment]
either related or a reduction:

```
#[
KEY 
D20181204T222045

/Users/timothee/git_clone/nim/timn/bugs/all/t0029.nim(28, 12) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/all/t0029.nim(28, 12) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/all/t0029.nim(23, 13) Error: internal error: genLiteral: ty is nil
    shOpt.data.setLen 1 # fails
]#

import macros

type
  Foo = object
    data: seq[int]

proc bar(a: Foo)=discard

proc shOpt(): auto =
  var shOpt: Foo
  # shOpt.data.setLen 0 # works
  shOpt.data.setLen 1 # fails
  shOpt

macro dispatchGen(): untyped =
  # const shOpt = shOpt() # works
  var shOpt = shOpt() # fails

  result = quote do:
     bar(`shOpt`)

dispatchGen()
```

**Comment by rlsdevine** [comment]
Trying to build the INim REPL which uses cligen and I get this error. I then tried both code snippets above and it's also present for those.  Using v1.02.
