### ISSUE TITLE
`index out of bounds` errors should show `index` and `bound`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9880]
`index out of bounds` errors should show `index` and `bound` in error message; it would often save a lot of debugging time

the code needs to be updated in a number of places:
```
compiler/ccgexprs.nim:878:39:        localError(p.config, x.info, "index out of bounds")
compiler/semfold.nim:492:37:      localError(g.config, n.info, "index out of bounds: " & $n)
compiler/semfold.nim:496:41:    else: localError(g.config, n.info, "index out of bounds: " & $n)
compiler/semfold.nim:504:37:      localError(g.config, n.info, "index out of bounds: " & $n)
compiler/vm.nim:424:26:  errIndexOutOfBounds = "index out of bounds"
lib/core/typeinfo.nim:197:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:204:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:214:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:222:39:      raise newException(IndexError, "index out of bounds")
lib/pure/base64.nim:71:13:    # avoid index out of bounds when lineLen == encoded length
lib/pure/collections/sharedstrings.nim:52:41:  else: raise newException(IndexError, "index out of bounds")
lib/pure/collections/sharedstrings.nim:56:41:  else: raise newException(IndexError, "index out of bounds")
lib/pure/subexes.nim:88:44:  if result >=% a.len: raiseInvalidFormat("index out of bounds: " & $result)
lib/system/chcks.nim:19:25:  sysFatal(IndexError, "index out of bounds")
lib/system/jssys.nim:161:35:  raise newException(IndexError, "index out of bounds")
```

i suggest using a single routine to generate the error message, eg:
```nim
template formatErrorIndexBound(index: int, n: int): string =
  "index out of bounds: index: " & $index &" n: " & $n
```

**Comment by timotheecour** [comment]
/cc @kaushalmodi now that PR was merged, there are still some remaining cases, eg:
see failing test commented out here: $nimc_D/tests/misc/tinvalidarrayaccess2.nim

see also:

compiler/vm.nim:424:26:  errIndexOutOfBounds = "index out of bounds"
lib/core/typeinfo.nim:197:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:204:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:214:39:      raise newException(IndexError, "index out of bounds")
lib/core/typeinfo.nim:222:39:      raise newException(IndexError, "index out of bounds")
lib/system/chcks.nim:26:25:  sysFatal(IndexError, "index out of bounds")
lib/system/jssys.nim:161:35:  raise newException(IndexError, "index out of bounds")

**Comment by timotheecour** [comment]
glad some ppl appreciate importance of helpful error messages, I certainly do (by helpful I mean in particular: shows relevant runtime/compiletime context such as variables involved). I'm busy with other PR's at the moment, until then, feel free to tackle some of these :)

**Comment by BontaVlad** [comment]
Made a PR [here](https://github.com/nim-lang/Nim/pull/10228)

**Comment by Araq** [comment]
This was implemented.
