### ISSUE TITLE
Some nimgrep issues

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#989]
`nimgrep ".*" system.nim` yields nothing.
`nimgrep "a.*" system.nim` Works.
`nimgrep ".*a" system.nim` Works too.
`nimgrep ".*$" system.nim` Continually prints the last line in the file.

This doesn't seem to work as expected:

```
nimgrep -r --confirm "(....)(....)" "$1 test $2" system.nim
/home/ex/src/Nimrod/lib/cycle.h
     2:  * Copyright (c) 2003, 2007 Matteo Frigo
     -> system.nimight (c) 2003, 2007 Matteo Frigo
     [a]bort; [y]es, a[l]l, [n]o, non[e]:
```

I was just trying to figure out how to reference groups in the replacement string, at which point I noticed that the file/directory positional argument was being treated as something else.

**Comment by andreaferretti** [comment]
Still happen
