### ISSUE TITLE
Cyrillic symbols in Windows terminal

### ISSUE THREAD

**Issue by MaxUNof** [nim-lang/Nim#9900]
If string starts with non-cyrillic symbol echo is normally. If string starts with cyrillic symbol echo is empty.
![image](https://user-images.githubusercontent.com/26873765/49686137-3656d700-fb01-11e8-8948-16d0a797d0ac.png)
![image](https://user-images.githubusercontent.com/26873765/49686142-42db2f80-fb01-11e8-9b5d-fad298d68507.png)
Nim version - 0.19.9

**Comment by dom96** [comment]
Probably related to #7441

**Comment by Araq** [comment]
This has been fixed.
