### ISSUE TITLE
compiler bug?

### ISSUE THREAD

**Issue by m4d3bug** [nim-lang/Nim#9919]
here is my example code in wslinux
```
proc myWriteln(f: File, attachList: varargs[array[string,string]]) =
  for data in items(attachList):
    write(f, data)
  write(f, "\n")
  echo attachList[0][1]

myWriteln(stdout, 
    [ [   
        """
            One,Two,Three,Four
            1,2,3,4
            10,20,30,40
            100,200,300,4百
        """,
        "Billing账单.csv"
    ]]
    # [
    #     """
    #         One,Two,Three,Four
    #         1,2,3,4
    #         10,20,30,40
    #         100,200,300,4百
    #     """,
    #     "Billing账单.csv"
    # ]
)
```
I got some  wrong in compiler time and there are some message about the code showing in the vscode same  as I meet in the compiler time
```
ordinal type expected

Error: internal error: invalid kind for lastOrd(tyString)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp check <file>
```
even if what I typed is wrong in  varargs[array[string,string]], but the compiler should not crash,am i right?

**Comment by Aareon** [comment]
I definitely agree that the compiler shouldn't crash like this in this case.
However, the compiler is expecting a range in position 1 of `array`. Try:
```nim
varargs[array[0..1,string]])```

**Comment by Aareon** [comment]
I definitely didn't get the expected output with this method, this is just an example of "getting it to work".

**Comment by narimiran** [comment]
> `varargs[array[string,string]]`

This is your problem, this is not a valid Nim syntax.

For the `varargs` usage see [this part of the manual](https://nim-lang.github.io/Nim/manual.html#types-varargs).
For correct declaration of `array` type see [this part of the manual](https://nim-lang.github.io/Nim/manual.html#types-array-and-sequence-types): the first parameter is an "ordinal type", as the error message said.

There are several solutions:

```nim
proc myWriteln(f: File, attachList: varargs[array[2, string]]) =
  for data in items(attachList):
    write(f, data)
    write(f, "\n")
  echo attachList[0][1]

myWriteln(stdout,
    [
        """
            One,Two,Three,Four
            1,2,3,4
            10,20,30,40
            100,200,300,4百
        """,
        "Billing账单.csv"
    ],
    [
        """
            One,Two,Three,Four
            1,2,3,4
            10,20,30,40
            100,200,300,4百
        """,
        "Billing账单.csv"
    ],
    [
        """
            One,Two,Three,Four
            1,2,3,4
            10,20,30,40
            100,200,300,4百
        """,
        "Billing账单.csv"
    ]
)
```
Notice that when you're calling the function arguments are not `stdout, array[array]` as in your example, but `stdout, array, array, array, (...)` — that's the point of using `varargs`: you can pass variable number of arguments (in this case three arrays).

Notice also the changed the parameter `attachList: varargs[array[2, string]]`: each argument is an array with two strings.
