### ISSUE TITLE
`nim c -o:- main.nim` for portable /dev/null (useful for editor integration)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9936]
@Araq PR accepted for this?
/cc @GULPF 

context: see https://github.com/nim-lang/Nim/pull/9916#issuecomment-445725347

>> Why should a command used for editor integration output a file? Yes, you can do tricks like output to /dev/null, but then we need different commands for error checking on different platforms...

> as shown in top post, you can use --noLinking, eg: nim c --errorMax:0 --noLinking main.nim (but misses link errors)
> or we can (in other PR) add support for a cross platform -o:- that achieve same effect as a cross platform /dev/null(posix), null(windows)

(on windows in particular it can be tricky to specify the equivalent of dev/null so might as well do the right thing once and not let users mess it up)

## precedent in other languages:
```
dmd -o-               do not write object file
ldc2 -o-                                     - Do not write object file
```
(there may be more)

## note
would also help with https://github.com/Varriount/NimLime/issues/137 /cc @Varriount

**Comment by narimiran** [comment]
Opinion, not an issue.
