### ISSUE TITLE
`genericAssign` does not take care of the `importC` variables

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#9940]
Function returns object with C struct fails to retain the content of the C struct.

### Example

```nim
{.emit:"""/*TYPESECTION*/
typedef struct { int x; } S;
void init(S *x){ x->x = 1; }
""".}

type S {.importc: "S".} = object
  x {.importc: "x".}: cint
proc init(x:ptr S) {.importc: "init".}

type
  T = object
    a: seq[float]
    b: seq[float]
    c: seq[float]
    d: seq[float]
    s: S

proc newT(): auto =
  var t:T
  t.s.addr.init
  echo "before newT returns: t.s.x = ",t.s.x
  t

var t = newT()
echo "after newT returns:  t.s.x = ",t.s.x
```
You need four or more GC referenced objects inside `T` to trigger this bug.

### Current Output

```
before newT returns: t.s.x = 1
after newT returns:  t.s.x = 0
```

### Expected Output

```
before newT returns: t.s.x = 1
after newT returns:  t.s.x = 1
```

### Possible Solution

No.

### Additional Information

This is the generated C code
``` C
N_LIB_PRIVATE N_NIMCALL(void, newT_pLBfOS1qghLT4LhmhRnaSA)(tyObject_T_pn9agxIzxh6TMBU1AhdyuiA* Result) {
        tyObject_T_pn9agxIzxh6TMBU1AhdyuiA t;
        tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
        nimZeroMem((void*)(&t), sizeof(tyObject_T_pn9agxIzxh6TMBU1AhdyuiA));
        init((&t.s));
        nimZeroMem((void*)T1_, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
        T1_[0] = copyString(((NimStringDesc*) &TM_gwtBaQA9botmXjhFeyWykZg_4));
        T1_[1] = nimIntToStr(((NI) (t.s.x)));
        echoBinSafe(T1_, 2);
        genericAssign((void*)Result, (void*)(&t), (&NTI_pn9agxIzxh6TMBU1AhdyuiA_));
}
```
My guess is that the `genericAssign` copies the C struct incorrectly.

**Comment by Araq** [comment]
It does that by design. We don't know if these imported structs are completely defined. But I agree it's bad, I'm changing it and we will see what it breaks.

**Comment by andreaferretti** [comment]
I am not sure exactly what this will imply, but it is pretty common to have opaque structures that are only partially defined in C APIs. For an example, see [CUDA](https://github.com/unicredit/nimcuda/blob/master/nimcuda/cublas_api.nim#L111-L115).

I don't think this fix will impact anything, as these types are always meant to be passed around as opaque pointers, plus this pattern is so common that I am sure @Araq is well aware of it, just a little worried about 

> I'm changing it and we will see what it breaks

:-D

**Comment by jxy** [comment]
Bit by this again.  How can we make it behave?

**Comment by Araq** [comment]
There is a pragma for this, ``.imcompleteStruct``.

**Comment by jxy** [comment]
It does not help in this case.

```
$ cat t9940.nim 
{.emit:"""/*TYPESECTION*/
typedef struct { int x; } S;
void init(S *x){ x->x = 1; }
""".}

type S {.importc: "S", incompleteStruct.} = object
  x {.importc: "x".}: cint
proc init(x:ptr S) {.importc: "init".}

type
  T = object
    a: seq[float]
    b: seq[float]
    c: seq[float]
    d: seq[float]
    s: S

proc newT(): auto =
  var t:T
  t.s.addr.init
  echo "before newT returns: t.s.x = ",t.s.x
  t

var t = newT()
echo "after newT returns:  t.s.x = ",t.s.x
$ nim c -r t9940.nim
Hint: used config file '/usr/home/jin/src/Nim_devel/config/nim.cfg' [Conf]
Hint: used config file '/usr/home/jin/src/Nim_devel/config/config.nims' [Conf]
Hint: operation successful (7710 lines compiled; 0.055 sec total; 9.953MiB peakmem; Debug Build) [SuccessX]
Hint: /usr/home/jin/tmp/t9940  [Exec]
before newT returns: t.s.x = 1
after newT returns:  t.s.x = 0
```

Unless I'm using it wrong.

**Comment by Araq** [comment]
You are, there is no way to embed ``S`` into your object when the compiler doesn't know its size. All you can use is ``s: ptr S`` here.

**Comment by jxy** [comment]
Even though I gave the compiler this,
```
type S {.importc: "S".} = object
  x {.importc: "x".}: cint
```
it still doesn't know its size?

How can the compiler create such an object?  Is `var s = S(x:1)` legal?

**Comment by Araq** [comment]
If you give the compiler everything it needs why ``.importc`` it?

**Comment by jxy** [comment]
Sorry if I'm turning this issue into a support ticket.  Without `importc` how do I call external library functions on Nim objects?  Can you please give me an example how the above code should be modified?

**Comment by Araq** [comment]
This works:

```nim


{.emit:"""/*TYPESECTION*/
typedef struct { int x; } S;
void init(S *x){ x->x = 1; }
""".}

type S = object
  x: cint
proc init(x:ptr S) {.importc: "init", nodecl.}

type
  T = object
    a: seq[float]
    b: seq[float]
    c: seq[float]
    d: seq[float]
    s: S

proc newT(): auto =
  var t:T
  t.s.addr.init
  echo "before newT returns: t.s.x = ",t.s.x
  t

var t = newT()
echo "after newT returns:  t.s.x = ",t.s.x
```

But your example with the emit statement is contrived, usually you import C code from a header file or you import a native code from a DLL. Maybe use c2nim which knows these things.

**Comment by jxy** [comment]
I guess the gist of this issue is that we cannot simply embed a C struct inside an object, unless we redefine the C struct in Nim and make sure the C and Nim versions have the same memory layout.
