### ISSUE TITLE
Make isNil return true for undefined for the JS backend

### ISSUE THREAD

**Issue by alehander42** [nim-lang/Nim#9946]
Now, first, I know most people would immediately say "nil is null, it can't be undefined" and that this would be insane: please read my arguments first.

First, `nil` is actually *equal* (for some meanings of equal) to undefined in JavaScript:  It's not obvious that we need to prefer `===` to `==` in this case.

`nil` describes invalid states for values: `isNil` is often used to guarantee typesafe access to fields/elements of values, usually types as ref.

The problem is: there is no way for this to work generally correctly if `isNil` doesn't return true for `undefined`, as one can access JavaScript objects created by other language/api, where `undefined` is the default value for a field. In this case we either need to 

* `a.isUndefined and a.isNil`(but now this is not portable to the C backend: a big problem. we also need to add the isNil magic to isUndefined: not even sure if this works correctly)

* `a.isStuff` which is a shortcut for isUndefined and isNil: again, not portable to the C backend and is it easy to make it recognizable by nil analysis

* `a.isNil` returns true for undefined: the simplest possible solution, and add `isNull` or `isUndefined` if somebody really needs to diff between those

This issue is inevitable in the JavaScript backend: that's why JavaScript itself has two different eq operators. Basically a solution will just ensure we use `==` instead of `===`, so in a way `null == undefined` is actually a very correct thing to assume in our own standard lib too. (And still provide isNull etc for `===`).

**Comment by alehander42** [comment]
Notice, this is not just an example, typescript's options directly produce undefined by default

`{x:number,y?:number}` y is undefined

**Comment by Araq** [comment]
Ok, can't argue with these arguments coming from deep experience.

**Comment by alehander42** [comment]
This was fixed in https://github.com/nim-lang/Nim/pull/9960

**Comment by g5becks** [comment]
There is an even bigger problem here I’m afraid. From what I can tell, nim uses null as the default value for all objects and properties when compiling to js which is incoherent with JavaScript . In js, undefined is the default value for all uninitialized properties.

Null is and actual value in js, undefined is the absence of a value. If I pass an options object to a method that has null set as the default instead of undefined, this can cause big issues.

If I need to create a separate issue for this I can, as this is something that really needs to be addressed.

**Comment by Araq** [comment]
"incoherent with JavaScript" doesn't mean much, Nim compiles to JS and Nim code follows Nim's semantics, not JS's.

> Null is and actual value in js, undefined is the absence of a value. If I pass an options object to a method that has null set as the default instead of undefined, this can cause big issues.

Or it can work out just fine... Please give an example that is not based on misconceptions of how language specifications and compilers work.
