### ISSUE TITLE
parseopt's OptParser.cmd doesn't properly quote double-quoted arguments

### ISSUE THREAD

**Issue by kirbyfan64** [nim-lang/Nim#9951]
### Example

```nim
import parseopt

var p = initOptParser(@["echo \"quoted\""])
echo p.cmdLineRest  # can also use p.cmd to reproduce, but it didn't work in play.nim-lang.org
```

### Current Output
```
"echo "quoted""
```

### Expected Output
```
'echo "quoted"'
# or
"echo \"quoted\""
```

### Possible Solution

The problem seems to be with the [quote function](https://github.com/nim-lang/Nim/blob/v0.19.0/lib/pure/parseopt.nim#L76), which doesn't bother checking if there are any double-quotes within the string or anything like that.

### Additional Information

Came up with my [bluecap rewrite in Nim](https://github.com/kirbyfan64/bluecap).

**Comment by dom96** [comment]
#8452 related?

**Comment by kirbyfan64** [comment]
@dom96 Maybe, though that seems to be more parsing-related, whereas this seems to be related to parseopt's re-quoting. (Also, it was already fixed in 0.19, but this isn't...)

**Comment by Araq** [comment]
The quoting rules are shell specific and there is no way to do this properly. You need to use the API differently, ``cmdLineRest`` is inherently unreliable.

**Comment by kirbyfan64** [comment]
Could we at least have access to the `idx` property then? Right now, it's pretty much impossible to reliably get hold of the remaining, unparsed command line arguments. (FWIW quoteShellCommand works correctly here, it's just the parseopt quote that doesn't.)

**Comment by kirbyfan64** [comment]
FWIW I'm just closing this now, though IMO there should at least be a warning in the docs that it's unreliable.

**Comment by timotheecour** [comment]
why close? its a bug

**Comment by Araq** [comment]
It is unfixable on Unix.

**Comment by timotheecour** [comment]
it is, see https://github.com/nim-lang/Nim/pull/10291
