### ISSUE TITLE
"ordinal type expected" error on enum

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#9952]
[Nimnuklear](https://github.com/genotrance/nimnuklear/) is no longer [compiling](https://travis-ci.org/genotrance/nimgen/jobs/467064976#L2002) after commits to devel in the last two days. Build ran around 3:52pm GMT on 12/12/2018.

Same code compiled just fine on 12/10/2018 with [devel](https://travis-ci.org/genotrance/nimgen/builds/466119294). That build ran around 6:10pm GMT.

Here's a snippet of the failure:

```nim
type
  edit_flags* {.size: sizeof(cint).} = enum
    EDIT_DEFAULT = 0, EDIT_READ_ONLY = (1 shl (0)), EDIT_AUTO_SELECT = (1 shl (1)),
    EDIT_SIG_ENTER = (1 shl (2)), EDIT_ALLOW_TAB = (1 shl (3)),
    EDIT_NO_CURSOR = (1 shl (4)), EDIT_SELECTABLE = (1 shl (5)),
    EDIT_CLIPBOARD = (1 shl (6)), EDIT_CTRL_ENTER_NEWLINE = (1 shl (7)),
    EDIT_NO_HORIZONTAL_SCROLL = (1 shl (8)), EDIT_ALWAYS_INSERT_MODE = (1 shl (9)),
    EDIT_MULTILINE = (1 shl (10)), EDIT_GOTO_END_ON_ACTIVATE = (1 shl (11))

  edit_types* {.size: sizeof(cint).} = enum
    EDIT_SIMPLE = EDIT_ALWAYS_INSERT_MODE         # <====
    EDIT_FIELD = EDIT_SIMPLE.int32 or EDIT_SELECTABLE.int32 or EDIT_CLIPBOARD.int32,
```

```
b.nim(11, 19) Error: ordinal type expected
```

**Comment by alaviss** [comment]
From the [Manual](https://nim-lang.org/docs/manual.html#types-enumeration-types):

> For better interfacing to other programming languages, the fields of enum types can be assigned an explicit ordinal value.
> An explicit ordered enum can have _holes_
> However, it is then not an ordinal anymore

So the fact that that code used to compile is a bug.

**Comment by nc-x** [comment]
You can change it to
```
EDIT_SIMPLE = EDIT_ALWAYS_INSERT_MODE.int32
```
just as in the next line and it should work.

**Comment by Araq** [comment]
But this should compile, the spec should be more precise here and ``EDIT_ALWAYS_INSERT_MODE`` is a valid enum value.
