### ISSUE TITLE
Showstopper regression: Nimscript no longer works 

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#9965]
It is impossible to configure a project using Nim script. All set switches are ignored completely. Regression introduced today.

**Comment by nc-x** [comment]
Might be because of https://github.com/nim-lang/Nim/commit/bb8586923794291ddabd122490fd2ab7ccc71ee0#diff-5fdd8f1b1ac3aa10d48e0af960fb8c17R92 which overwrites configuration using .cfg file.

**Comment by cooldome** [comment]
Yes, regression caused by this line. Please revert

**Comment by nc-x** [comment]
Please try the PR and see if it fixes the issue 
https://github.com/nim-lang/Nim/pull/9966
