### ISSUE TITLE
Potential bug in asyncdispatch involving var parameters

### ISSUE THREAD

**Issue by PrimordialHelios** [nim-lang/Nim#9972]
A program using var parameters in a procedure marked async will fail to compile.

### Example
```nim
import asyncdispatch

proc myproc(x: var int) {.async.} = x = 6
  
var x: int
waitFor myproc(x)
echo x
```

### Current Output
```
temp1.nim(3, 25) template/generic instantiation from here
temp1.nim(4, 3) Error: illegal capture 'x' of type <var int> which is declared here: temp1.nim(3, 12)
```

### Expected Output
Program should compile and echo `6`

### Additional Information
removing the `waitFor` function call and the `{.async.}` pragma makes the program compile and run just fine.
I'm not sure if this is intentional or not. It doesn't seem like it though, so I figured I should file a bug report anyway

**Comment by cheatfate** [comment]
This is not a bug, current version of asyncdispatch do not supports transformation of `var` arguments. It is also very hard to achieve safety if this will work.

**Comment by PrimordialHelios** [comment]
Alright, that makes sense.
Is there a way to `waitFor` a future, but with a timeout? I know `withTimeout` exists, but that doesn't return the return value I need, it just returns a bool.
