### ISSUE TITLE
Prohibit Style Insensitivity In Language Features

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#9980]
I generally understand the argument for style insensitivity in user defined `proc`'s, types etc but I urge you disallow it for keywords, compiler supplied base types and basically anything else hard coded into the language. There is no gain there, only loss. For example this compiles today:
```
pRoC foo (t: type_desc[sTRING]): sTrinG = discard

diSCarD foo(typeDESC(type_of("hello world")))
```

**Comment by Araq** [comment]
I can write similar distractions in Java via its ``\uXXXX`` Unicode support. Nobody minds.

1. ``string`` is not a keyword.
2. There are good reasons against this special casing: It's more logic in the compiler, more complex rules to document, to read, to learn.

**Comment by deech** [comment]
1. Isn't `string` a compiler supplied base type? 
2. You acknowledge there are good reasons to disallow special casing in this case but then close the issue. I don't understand.

**Comment by Araq** [comment]
I updated my reply to make it less ambiguous.
