### ISSUE TITLE
Cant build nimsuggest with user config.nims present

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#9986]
Building nimsuggest on latest devel fails with
```
Error: system module needs: unsureAsgnRef
```
if even empty config.nims is present in `~/.config/nim`

**Comment by timotheecour** [comment]
@SolitudeSF 
seems closed on latest devel 0409f2348e2ac69a717e4ec7628a99c49fd42f0d (probably earlier)
feel free to reopen (or reply here) if not the case
